### ISSUE TITLE
IOS- Profile - The avatar is not displayed in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13811] opened 2022-12-23 00:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to Setting - Profile
4. Disable the internet connection in the device
5. Tab Profile icon

## Expected Result:
Avatar in offline mode should be displayed as in online

## Actual Result:
The avatar is not displayed in offline mode

## Workaround:
Uknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209250147-6fbf6343-e0f8-42c4-a626-2cba44bdce6a.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2022-12-28 13:48
I'm having issues signing up via BrowsterStack to test this on iOS. @mallenexpensify if you're online today can you confirm this is reproducible please? Thanks

**Comment by mallenexpensify** [comment] 2022-12-28 23:20
I can't reproduce.  I followed the repro steps, tested a couple times, but every time I was offline, my avatar still showed. 
@kbecciv am I holding it wrong?  Anything else I should be doing?

**Comment by kbecciv** [comment] 2022-12-29 14:44
@mallenexpensify Checking with current build, update you shortly.

**Comment by kbecciv** [comment] 2022-12-29 14:49
@mallenexpensify I can reproduce the issue with my testing account applausetester+0901abb@applause.expensifail.com/Feya86Katya

https://user-images.githubusercontent.com/93399543/209969953-9c9f60e3-6772-4d12-a38b-3be649f568de.MP4

**Comment by mallenexpensify** [comment] 2022-12-30 02:01
Tested on production and staging and wasn't able to reproduce. (also.. I can't upload vid or photos now, just restarted comp too ¯\_(ツ)_/¯ ) 
@kbecciv can you think of any thing I might be doing _wrong_ or why it might not be working on my end?

**Comment by laurenreidexpensify** [comment] 2023-01-03 13:55
Asking for help in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1672754061893769)

**Comment by laurenreidexpensify** [comment] 2023-01-03 17:16
Closing as per convo in Slack

**Closed by laurenreidexpensify** 2023-01-03 17:16 UTC
Labels: Daily, Bug
