### ISSUE TITLE
[$250] Log in - Shortcut modal doesn't open after logout

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46441] opened 2024-07-29 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Signout if you are logged in
2. Refresh the page
3. Press CMD+j (MacOS) to open shortcut modal

## Expected Result:
Shortcut modal opens

## Actual Result:
Shortcut modal doesn't opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ec7bda4b-07f6-4889-b7e5-5cc3c063587b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a68d890586fd897d</li>
        <li>Upwork Job ID: 1818064897776942918</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment] 2024-07-29 19:35
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment] 2024-07-29 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - Shortcut modal doesn't open after logout

### What is the root cause of that problem?
We are subscribing to the shortcut modal in AuthScreen
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L280-L295
but the AuthScreen is rendered if the user is already authenticated
### What changes do you think we should make in order to solve the problem?

We should take the subscription to a more general component like `NavigationRoot` or `Expensify` or `App` 
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-29 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - Shortcut modal doesn't open after logout

### What is the root cause of that problem?
We are subscribing to the shortcut modal in AuthScreen
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L280-L295
but the AuthScreen is rendered if the user is already authenticated
### What changes do you think we should make in order to solve the problem?

We should take the subscription up in to a more general component like `[NavigationRoot](https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/Navigation/AppNavigator/index.tsx#L15-L16)` or `Expensify` or `App` 
_We can also check for other shortcuts which can be shown without authentication and do the same._
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2024-07-29 23:23
I can repro

**Comment by jayeshmangwani** [comment] 2024-07-30 11:22
@jliexpensify Do we really need to show the shortcut page on the sign-in screen? We intentionally added all shortcut modals to the AuthScreen, as every shortcut will work after sign-in

**Comment by jliexpensify** [comment] 2024-07-31 05:55
Ah, thanks for that context! In that case, we can close this one.

**Closed** 2024-07-31 05:55 UTC
Labels: External, Daily, Help Wanted, Bug
