### ISSUE TITLE
[PAY AUG 22ND][$250] Search-Skeleton during loading & in empty state are aligned differently compared to production

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46949] opened 2024-08-07 09:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go back to Inbox.
4. Open workspace switcher and select the new workspace.
5. Go to Search.
6. Navigate through the empty Search sections to check how the skeleton during loading and the skeleton in empty state are aligned differently on staging and production.

## Expected Result:
The skeleton during loading and the skeleton in empty state should have similar alignment (only slight deviation on production).

## Actual Result:
The skeleton during loading and the skeleton in empty state has larger deviation in alignment compared to production.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3241ec1e-2640-4c30-959f-8d0aec0bf601

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011af2fbb0ab06fc24</li>
        <li>Upwork Job ID: 1821143733082880779</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103432889</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by IuliiaHerets** [comment] 2024-08-07 09:46
We think that this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment] 2024-08-07 11:14
@shawnborton confirming with you the correct expectation here so we can move this forward.

**Comment by trjExpensify** [comment] 2024-08-07 11:17
either way, this will be external. Adding the label to get a C+ assigned to move the deploy blocker along.

**Comment by trjExpensify** [comment] 2024-08-07 11:27
^^ Not a web deploy blocker either, removed that label.

**Comment by Kicu** [comment] 2024-08-07 11:29
@trjExpensify almost everything related to Search was done by me @WojtekBoman from SWM, and the newest iteration of skeleton empty views was implemented in here by @filip-solecki also from SWM.

So if you don't mind we could assign one our devs to this.
It doesn't look like a big bug, and in addition we can make sure empty "skeleton" views have correct padding in other places as well.

CC @blazejkustra

**Comment by shawnborton** [comment] 2024-08-07 11:32
I had already reported this one to @filip-solecki and I believe @filip-solecki was planning on fixing it already?

**Comment by shawnborton** [comment] 2024-08-07 11:33
Take a look at [this comment](https://github.com/Expensify/App/pull/44137#issuecomment-2229350014) @trjExpensify

**Comment by trjExpensify** [comment] 2024-08-07 11:39
>So if you don't mind we could assign one our devs to this.

Great, works for me! 

>I had already reported this one to @filip-solecki and I believe @filip-solecki was planning on fixing it already?

Course you did! 🦅 👁️ @filip-solecki can you comment so we can assign this one to you to make sure we get this done? 

As this was reported in a PR already, and accepted to be fixed in a follow-up PR, I'm demoting it as a deploy blocker.

**Comment by shawnborton** [comment] 2024-08-07 11:40
I respectfully disagree @Krishna2323, I asked Filip to fix this as a quick follow up to the project three weeks ago. This isn't a new bug.

**Comment by filip-solecki** [comment] 2024-08-07 11:41
Yes it's on my list, but I am quite busy right now and @Guccio163 will take care of this 🚀

**Comment by Guccio163** [comment] 2024-08-08 11:22
Hi @IuliiaHerets, can you let me know if I understand the issue correctly? 

> The skeleton during loading and the skeleton in empty state has larger deviation in alignment compared to production.

`Loading page`s are exactly the same in staging and production, the problem is the alignment of `Empty page`. `Loading page` is mentioned, because we measure the `Empty page`'s alignment towards it.

Production:
- Empty page vary in both vertical and horizontal alignment

Staging:
- Empty page is vertically aligned with Loading page, it vary only in (smaller than production, but not perfect) horizontal alignment

What we aim to achieve:
- Perfectly aligning `Empty page` to the `Loading page` so that there's no 'glitch' between them

Comparison of `Loading page`s in staging and production (uploaded screenshot instead of recording because it is easier to capture):

vertical alignment:
<img width="1837" alt="Screenshot 2024-08-08 at 13 10 16" src="https://github.com/user-attachments/assets/d49d0a01-806e-40e2-9c36-c9a1b5eb18ab">

horizontal alignment:
<img width="918" alt="Screenshot 2024-08-08 at 13 12 07" src="https://github.com/user-attachments/assets/2fec4fd2-333e-46cf-a896-e40d1888cffe">

Comparison of `Empty page`s in staging and production:

https://github.com/user-attachments/assets/0a083dff-5417-4c11-87f2-01057dd384df


cc @blazejkustra

**Comment by shawnborton** [comment] 2024-08-08 11:26
Can we also address [this particular comment too](https://github.com/Expensify/App/pull/44137#issuecomment-2229350014)? I think that's the biggest visual glitch we need to solve.

**Comment by Guccio163** [comment] 2024-08-08 11:40
Actually it is interesting case, because on your video @IuliiaHerets there is exactly the opposite situation: the **staging** has both horizontal and vertical switches and **production** has only horizontal ones. On @shawnborton 's video in [this comment](https://github.com/Expensify/App/pull/44137#issuecomment-2229350014) there is only horizontal variation too, I suppose that using staging app. 

Staging:

https://github.com/user-attachments/assets/69034a3a-8691-42fb-832a-7e767a7029ca

Production:

https://github.com/user-attachments/assets/1cb813de-fae5-4ec8-b8e3-b77c09321ddb

I'll to dig right into it, but it's interesting that we have exactly opposite situations

**Comment by Guccio163** [comment] 2024-08-08 11:41
> Can we also address https://github.com/Expensify/App/pull/44137#issuecomment-2229350014? I think that's the biggest visual glitch we need to solve.

@shawnborton you mean the horizontal alignment of `Empty page` right?

**Comment by shawnborton** [comment] 2024-08-08 11:41
Yeah, when you jump from loading rows to the empty state, there is a difference in horizontal padding which causes the jumpiness. Both of your videos directly above illustrate this.

**Comment by Guccio163** [comment] 2024-08-08 11:47
@shawnborton Yeah, I think this is exactly the case that I have to solve here, as a matter of fact, this was exactly what I was trying to confirm with @IuliiaHerets, though there's also the vertical jump (shows on production here and on staging in @IuliiaHerets's case) which makes a big difference and can mean smth more 🤔

**Comment by shawnborton** [comment] 2024-08-08 11:48
Cool, I agree with you we should align on both the horizontal and vertical padding of both the loading rows and the empty state.

**Comment by Guccio163** [comment] 2024-08-08 13:30
I just found out that in narrow view both staging and production has mismatched components' widths between Empty and Loading pages, I'll try to handle it in this PR too!

Staging narrow window:

https://github.com/user-attachments/assets/44eb3168-85de-4f6c-89ae-cae2f1b39285

Production narrow window:

https://github.com/user-attachments/assets/9b61f267-9936-487b-a893-39d1b4430c4b

**Comment by shawnborton** [comment] 2024-08-08 13:38
Awesome, thanks for digging into this one!

**Comment by Guccio163** [comment] 2024-08-08 15:04
@shawnborton @IuliiaHerets Also when I'm on it, what do you think about aligning `Loading page` with `Results page` (not empty)? Vertically it's normal that they will vary (Loading page doesn't have f.ex. filters), but I could try to match them to align horizontally. Then it would be about tweaking both `Loading` and `Empty` pages' widths to match `Results` page.

Here's video of the horizontal difference between `Loading` and `Results` pages.

https://github.com/user-attachments/assets/34fd03ba-c829-444d-8a17-7ef9ac064587

**Comment by shawnborton** [comment] 2024-08-08 15:07
> but I could try to match them to align horizontally. 

Yes, that was the whole point of my original comment to @filip-solecki [here](https://github.com/Expensify/App/issues/46949#:~:text=this%20particular%20comment%20too). Or maybe I am misunderstanding you?

**Comment by shawnborton** [comment] 2024-08-08 15:08
Yes, I think ideally we should use the same horizontal padding between loading/empty state/results. Whatever we currently have for results should be the guide here I would think? Which I think is just 20px of horizontal padding around the rows.

**Comment by jliexpensify** [comment] 2024-08-19 10:41
Thanks for the heads up!

Payment Summary:

- C+: @rayane-djouah $250

https://www.upwork.com/jobs/~011af2fbb0ab06fc24

**Comment by jliexpensify** [comment] 2024-08-21 23:56
@rayane-djouah is a checklist needed for this?

**Closed** 2024-08-23 01:55 UTC
Labels: External, Engineering, Daily, Bug
