### ISSUE TITLE
[$500] IOU - Returning to the Workspace selection, another workspace is displayed for a second

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34282] opened 2024-01-10 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab--- Request money--- Distance
3. Enter start point and finish way point
4. Tap next
5. Select the first Worspace
6. Tap app back button

## Expected Result:
The pre-selected first workspace should be selected and displayed on tapping back

## Actual Result:
The second workspace is shown as selected for an second and then only pre-selected first workspace selected and displayed on tapping back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/817d5180-5314-406f-b5bf-8089e684adf8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015be8f0bebfdc2b11</li>
        <li>Upwork Job ID: 1745151743078821888</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-10 18:36
Dupe of https://github.com/Expensify/App/issues/33068

**Closed** 2024-01-18 00:31 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
