### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] iOS - Screen flashes after selecting inputs while creating a Room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28950] opened 2023-10-05 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27836
## Action Performed:
1. Log into HT account on Expensify app
2. While having at least 2 workspaces, selecting the FAB button
3. Select "send message" and select "room" tab
4. Begin inputting options in any form available on page eg "Who can post", "Visibility", etc

## Expected Result:
User is able to input values without problems while creating room

## Actual Result:
Screen begins to blink and flashes while options are selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c43b5e2e-313b-422d-8269-5fc20b39f42d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010914cc66f062c549</li>
        <li>Upwork Job ID: 1710021385577029632</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-05 20:27
@dangrous I have tested a revert of this PR https://github.com/Expensify/App/pull/27836 and it seems like this regression is resolved

It feels like the textares if stuck enlarging and shrinking or something

**Comment by abdel-h66** [comment] 2023-10-05 20:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Screen flicker when creating a room. 

### What is the root cause of that problem?
The issue comes from `KeyboardAvoidingView` used in the `WorkspaceNewRoomPage`, when the behavior is set to height, coming back from a select in the form, (workspace for example) will trigger the autofocus and brings up the keyboard. 

Somehow, the height keeps being recalculated indefinitely until the keyboard is closed and then opened manually by focusing the text input. 

### What changes do you think we should make in order to solve the problem?

Changing the behavior property from height to padding seems to fix the issue 

```js
<KeyboardAvoidingView
   style={{height: '100%'}}
   behavior="padding"
   // Offset is needed as KeyboardAvoidingView in nested inside of TabNavigator instead of wrapping whole screen.
   // This is because when wrapping whole screen the screen was freezing when changing Tabs. 
   keyboardVerticalOffset={variables.contentHeaderHeight + variables.tabSelectorButtonHeight + 
   variables.tabSelectorButtonPadding + insets.top}
 > 
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by situchan** [comment] 2023-10-05 21:29
@abdel-h66 thanks for the proposal. We added KeyboardAvoidingView separately from ScreenWrapper in [this commit](https://github.com/Expensify/App/commit/85519f7126884aae050112ccb8de85564c7cc372) to fix freeze issue on iOS.
Do you have better solution to remove this workaround and still use the benefit of keyboard avoiding behavior in ScreenWrapper?

**Comment by mountiny** [comment] 2023-10-06 00:06
This was fixed by reverting, and its fixed in staging

**Comment by mountiny** [comment] 2023-10-13 09:40
@abdel-h66 hey! we are going to use your solution in the PR so you will get paid 25% of the reward $125 for your proposal. Thank you for contributing ❤️ 

https://github.com/Expensify/App/pull/29541

**Comment by mountiny** [comment] 2023-10-17 01:07
@kadiealexander no need for chekclist on this one, the originating PR is clear for the backlog here.

Only need to pay $125 to @abdel-h66 for their solution

**Comment by kadiealexander** [comment] 2023-10-26 07:13
@abdel-h66 please apply here https://www.upwork.com/jobs/~010914cc66f062c549

**Comment by abdel-h66** [comment] 2023-10-27 08:09
Done @kadiealexander thank you

**Comment by kadiealexander** [comment] 2023-10-30 01:57
Sweet, contract sent!

**Comment by kadiealexander** [comment] 2023-11-01 05:22
Paid!

**Closed by kadiealexander** 2023-11-01 05:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
