### ISSUE TITLE
Settings - Address line 1 field isn't providing a suggestion for "Tatabánya"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38092] opened 2024-03-11 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4416343&group_by=cases:section_id&group_id=229070&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Profile - Address
2. Type "Tatabánya" in the Address line 1 field

## Expected Result:
There should be suggestions

## Actual Result:
Address line 1 field isn't providing a suggestion for "Tatabánya"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d331f87-c905-42b0-84f5-9053753b9520

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-11 21:04
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-11 21:04
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by godofoutcasts94** [comment] 2024-03-11 22:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Settings - Address line 1 field isn't providing a suggestion for "Tatabánya"
### What is the root cause of that problem?
The root cause is here : 
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L57
we have defined types as `address` because of which it is unable to fetch any suggestions for "Tatabánya"
### What changes do you think we should make in order to solve the problem?

If we remove the `resultTypes = 'address',` from here, we do get suggestions for "Tatabánya"
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-11 22:07
Updated [Proposal](https://github.com/Expensify/App/issues/38092#issuecomment-1989520735)

**Comment by Tony-MK** [comment] 2024-03-12 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings - Address line 1 field isn't providing a suggestion for "Tatabánya"

### What is the root cause of that problem?

In the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx#L147) component, we do not specify the `resultTypes` prop as an empty string.

https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch/index.tsx#L57

Therefore, in the [`AddressSearch`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch) component, the [`resultTypes`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch/index.tsx#L57) default to address and the request is going to look like `command=Proxy_GooglePlaces&proxyUrl=/place/autocomplete/json?input=Tatabánya&types=address`.

However, the Google Autocomplete API does not support types=address this for more supported types: https://developers.google.com/maps/documentation/places/web-service/supported_types

### What changes do you think we should make in order to solve the problem?


Just how like  we set `resultTypes` as an empty string in [`IOURequestStepWaypoint`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx) over [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L232), we should also do the same for the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx) component.

Let's introduce the `resultTypes` prop to the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx)  over [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx#L147) like `resultTypes="";`.

**Recommended**

Since **Tatabánya** is an establishment, the Google Autocomplete API suggests we use `resultTypes` as `'street_address|establishment'` to find locations in the future.

### What alternative solutions did you explore? (Optional)

Instead of setting the default value of `resultTypes` as  `address`, we should set it to either `""` or  `"street_address|establishment"`.

Then, fix up the rest of the places like [`IOURequestStepWaypoint`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L232-L233)

**Comment by Tony-MK** [comment] 2024-03-12 13:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings - Address line 1 field isn't providing a suggestion for "Tatabánya"

### What is the root cause of that problem?

In the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx#L147) component, we do not specify the `resultTypes` prop as an empty string.

https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch/index.tsx#L57

Therefore, in the [`AddressSearch`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch) component, the [`resultTypes`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressSearch/index.tsx#L57) default to address and the request is going to look like `command=Proxy_GooglePlaces&proxyUrl=/place/autocomplete/json?input=Tatabánya&types=address`.

However, the Google Autocomplete API did not find the precise address so no result was found.

More supported types: https://developers.google.com/maps/documentation/places/web-service/supported_types#table3

### What changes do you think we should make in order to solve the problem?


Just how like  we set `resultTypes` as an empty string in [`IOURequestStepWaypoint`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx) over [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L232), we should also do the same for the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx) component.

Let's introduce the `resultTypes` prop to the [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx)  over [here](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx#L147) like `resultTypes="";`.

**Suggestion**

Since **Tatabánya** is an establishment, the Google Autocomplete API suggests we use `'geocode'` to find locations in the future for [`AddressForm`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/components/AddressForm.tsx) and [`IOURequestStepWaypoint`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L232-L233).

### What alternative solutions did you explore? (Optional)

Instead of setting the default value of `resultTypes` as  `address`, we should set it to either `""` or  `"geocode"`.

Then, fix up the rest of the places like [`IOURequestStepWaypoint`](https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L232-L233)

**Comment by godofoutcasts94** [comment] 2024-03-12 13:57
Hey @Tony-MK, I tried to do this - `resultTypes = "street_address|establishment"` but I am still seeing this :
<img width="1470" alt="Screenshot 2024-03-12 at 7 26 41 PM" src="https://github.com/Expensify/App/assets/158435970/b891cb1a-5f1b-4dde-904a-a7823f2ea12a">

**Comment by godofoutcasts94** [comment] 2024-03-12 13:59
Updated [Proposal](https://github.com/Expensify/App/issues/38092#issuecomment-1989520735)

**Comment by godofoutcasts94** [comment] 2024-03-12 14:21
There are a lot of edits in the proposal please look into this edit if needed 
<img width="1470" alt="Screenshot 2024-03-12 at 7 51 17 PM" src="https://github.com/Expensify/App/assets/158435970/8968cf98-b23d-4971-8cef-68a8e5217627">

**Comment by godofoutcasts94** [comment] 2024-03-12 15:41
Since there was too many edits. So posting new proposal. 

## Proposal
Settings - Address line 1 field isn't providing a suggestion for "Tatabánya"
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The root cause is here :
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L57
and here :
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L81
we are using the `resultTypes as types=address` in  Google Places API endpoint. We have defined types as address because of which it is unable to fetch any suggestions for "Tatabánya"
### What changes do you think we should make in order to solve the problem?

We remove the `resultTypes = 'address'`, from here:
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L57
here :
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L81
and here :
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L85
we do get suggestions for "Tatabánya" as the API is able to fetch broader set of results.

### What alternative solutions did you explore? (Optional)
Alternatively, we can set it as `''` i.e. `resultTypes=''` over here :
https://github.com/Expensify/App/blob/b8f16ba88889df5f5852ce9e7a574148a85638f1/src/components/AddressSearch/index.tsx#L57

### Result :
https://github.com/Expensify/App/assets/158435970/3b7d01a8-170a-4d53-a0bd-3c710b2be40f

**Comment by puneetlath** [comment] 2024-03-12 22:15
Hmm, I kind of don't feel like this is really a bug. It looks like `Tatabánya` is a city name. I think it's fine to expect a user to type in something a little more specific than just a city name. 

I'm going to close this, but feel free to comment if you disagree. Sorry to everyone who posted proposals, but that's the risk of proposing before the `External` label is added.

**Closed by puneetlath** 2024-03-12 22:15 UTC
Labels: Daily, Bug

**Comment by godofoutcasts94** [comment] 2024-03-13 04:27
> Hmm, I kind of don't feel like this is really a bug. It looks like `Tatabánya` is a city name. I think it's fine to expect a user to type in something a little more specific than just a city name before showing suggestions. 
> 
> 
> 
> I'm going to close this, but feel free to comment if you disagree. Sorry to everyone who posted proposals, but that's the risk of proposing before the `External` label is added. 

I just disagree on closing this issue on one thing that what about the resultType being address which is an unsupportable api endpoint, which according to Google place api doesn't even exists. How about that ??

**Comment by puneetlath** [comment] 2024-03-14 17:44
@neil-marcellini do you have any thoughts about that?
