### ISSUE TITLE
[$500]  IOU - All of the IOU chats disappear when I do the same IOU and turn the connection on

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30839] opened 2023-11-03 12:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with a new account on device A (main)
2. Log in with the same account on device B
3. Disable the internet connection on device A
4. Split a bill with 2 users on device B
5. Split the same bill with 2 users on device A
6. Enable the internet connection on device A
7. Click/tap on the "back" button on device A

## Expected Result:
I should see permanent, duplicated chats of the ones with errors.

## Actual Result:
I can only see the chats with errors and they disappear when tapped.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
</details> Main device

https://github.com/Expensify/App/assets/93399543/592f0740-c7c7-4107-844b-0df1b08d5712

</details> Secondary device

https://github.com/Expensify/App/assets/93399543/05f6aafd-cdbc-4c44-a32b-746457cf5141

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018104751b5e6c6df2</li>
        <li>Upwork Job ID: 1720420276449742848</li>
        <li>Last Price Increase: 2023-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27813512</li>
<li>tienifr | Contributor | 27813513</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-11-09 00:57
Reassigning another 🐛  team member, I'm going OOO until Tuesday, November 14, and will take it back if it's still open by my return date.

@dylanexpensify  - Required action from the team: 

Please keep an eye out that this one is moving forward and we find a proposal, thanks!

**Comment by dylanexpensify** [comment] 2023-11-14 09:44
bump @tienifr for reply to above 🙇‍♂️

**Comment by alexpensify** [comment] 2023-11-16 20:19
@ntdiary any feedback or are we good to move forward here?

**Comment by nkuoch** [comment] 2023-11-21 15:57
Will look at it tomorrow

**Comment by nkuoch** [comment] 2023-11-22 10:32
As we're already showing a creation error on the main report, I think it would make sense to just remove split reports from Onyx back end side [there](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportAPI.php#L4494) (by passing null instead of the error object).
cc @luacmartins what do you think?

**Comment by luacmartins** [comment] 2023-11-22 18:25
I like the idea, I think it makes sense to keep the error in one place and remove the other reports.

**Comment by nkuoch** [comment] 2023-11-23 10:54
Then I can do myself php side.

**Comment by nkuoch** [comment] 2023-11-24 09:30
Yes, when we try to open an optimistic report that didn't get created due to an error, let's not call openReport. Let's show the report with the error and allow the user to clear it himself.

**Comment by alexpensify** [comment] 2023-11-29 19:41
PR is still in review!

**Comment by alexpensify** [comment] 2023-12-01 18:09
Daily Update: PR is in review

**Comment by alexpensify** [comment] 2023-12-04 21:39
Daily Update: PR has a few comments but moving forward.

**Comment by alexpensify** [comment] 2023-12-06 18:50
Daily Update: The PR has been merged, so we will need to wait on automation here.

**Comment by alexpensify** [comment] 2023-12-08 17:39
Daily Update: No automation yet. 🤔

**Comment by alexpensify** [comment] 2023-12-11 18:48
@nkuoch can you share if this one is complete? I'm trying to identify if automation failed here and I need to prepare the manual payment process. Thanks!

**Comment by alexpensify** [comment] 2023-12-13 22:00
@ntdiary - can you provide feedback if this one is complete? I'm trying to identify why automation has failed here or if it should remain open. Thanks!

**Comment by alexpensify** [comment] 2023-12-18 23:48
Ok, thanks, I was OOO last Friday and working on the payment process.

**Comment by alexpensify** [comment] 2023-12-19 00:38
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @tienifr $500 
-  Contributor+ that helped on the issue and/or PR - @ntdiary $500 

Upwork Job: https://www.upwork.com/jobs/~018104751b5e6c6df2

Extra Notes regarding payment: No automation here, so I'll just manually write this one out.

**Comment by alexpensify** [comment] 2023-12-19 00:42
@ntdiary - if you can add the checklist details, that will be great and we can close out. 

Everyone has been paid in Upwork.

**Comment by alexpensify** [comment] 2023-12-19 19:04
I agree then, no regression test is needed here. With this news, I'm going to close out this GH.

**Comment by alexpensify** [comment] 2023-12-19 19:05
Thank you for the help here!

**Closed by alexpensify** 2023-12-19 19:04 UTC
Labels: Reviewing, External, Weekly, Bug
