### ISSUE TITLE
[HOLD for c+ payment in newdot] [$1000] Dev: "0:undefined:" displayed in reaction emoji tooltip

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23307] opened 2023-07-20 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. React message with any emoji
4. Right click on reacted emoji
5. Notice "0:undefined:" will be displayed

## Expected Result:
"0:undefined:" displayed should not displayed in reaction emoji tooltip

## Actual Result:
"0:undefined:" displayed in reaction emoji tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev v1.3.43-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3198c7dc-a4b7-4826-b6ed-44d4d3b52861

![Screenshot 2023-07-20 at 5 02 49 PM](https://github.com/Expensify/App/assets/93399543/2aed8b70-5c9c-46a2-a4c9-fa989312b3fa)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689854537784799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca4a5f95b82060ec</li>
        <li>Upwork Job ID: 1682153064419074048</li>
        2023-07-20<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>jfquevedol2198 | Contributor | 25679499</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-20 21:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"0:undefined:" displayed in reaction emoji tooltip.

### What is the root cause of that problem?
The root cause is that we pass `reaction.emoji` to `showReactionList` in [this line]().
https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Reactions/ReportActionItemEmojiReactions.js#L99

### What changes do you think we should make in order to solve the problem?
We should pass `reaction.emojiName` to `showReactionList`.
```js
    reactionListRef.current.showReactionList(event, popoverReactionListAnchor.current, reaction.emojiName, props.reportActionID);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by ayazhussain79** [comment] 2023-07-20 21:20
This bug might be regression of this [PR](https://github.com/Expensify/App/pull/17996)

**Comment by jfquevedol2198** [comment] 2023-07-20 21:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: "0:undefined:" displayed in reaction emoji tooltip

### What is the root cause of that problem?
1. In this line, `reaction.emoji` is undefined.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Reactions/ReportActionItemEmojiReactions.js#L98-L100

2. In this line, `Report.hasAccountIDReacted` is not found.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/pages/home/report/ReactionList/PopoverReactionList.js#L189

### What changes do you think we should make in order to solve the problem?

1. Update this [line](https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Reactions/ReportActionItemEmojiReactions.js#L98-L100) to
```javascript
    reactionListRef.current.showReactionList(event, popoverReactionListAnchor.current, reaction.emojiName, props.reportActionID);

2. Update this [line](https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/pages/home/report/ReactionList/PopoverReactionList.js#L189)
```javascript
    const hasUserReacted = Report.hasAccountIDReacted(this.props.currentUserPersonalDetails.accountID, reactionUsers);
```
By doing this:  popup should look like follows, Its missing Emoji on Popup.
<img width="545" alt="image" src="https://github.com/Expensify/App/assets/137529618/d8bc250d-b0fb-42a6-a11c-8dbafdafa25b">

3. We need to do this:

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/libs/EmojiUtils.js#L395-L406

In `EmojiUtils.getUniqueEmojiCodes`, 
users should be
```javascript
    {[accountID]: {skinTones: {createdAt, skinTone}}
```
But on `PopoverReactionsList`, its passing like this:
```javascript
    [ {accountID, skinTone} ]
```
Update `EmojiUtils.getUniqueEmojiCodes` like this:
```javascript
const getUniqueEmojiCodes = (emojiAsset, users) => {
    const uniqueEmojiCodes = [];
    _.each(users, (userSkinTones) => {
        _.each(lodashGet(userSkinTones, 'skinTones'), (createdAt, skinTone) => {
            const emojiCode = getPreferredEmojiCode(emojiAsset, skinTone);
            if (emojiCode && !uniqueEmojiCodes.includes(emojiCode)) {
                uniqueEmojiCodes.push(emojiCode);
            }
        });
        if (_.has(userSkinTones, 'skinTone')) {
            const skinTone = _.get(userSkinTones, 'skinTone');
            const emojiCode = getPreferredEmojiCode(emojiAsset, skinTone);
            if (emojiCode && !uniqueEmojiCodes.includes(emojiCode)) {
                uniqueEmojiCodes.push(emojiCode);
            }
        }
    });
    return uniqueEmojiCodes;
};
```

<details><summary>RESULT</summary>
<img width="529" alt="image" src="https://github.com/Expensify/App/assets/137529618/f1d884f2-cc7f-4c7a-8d40-002e219d48a6">
</details> 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by stitesExpensify** [comment] 2023-07-20 22:15
I agree that this is most likely a regression from that PR.

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 22:46
@stitesExpensify Yeah @jfquevedol2198  [Proposal](https://github.com/Expensify/App/issues/23307#issuecomment-1644654568) looks good to me!

C+ Reviewed!
🎀 👀 🎀

**Comment by stitesExpensify** [comment] 2023-07-21 17:32
@jfquevedol2198 proposal looks good to me!

**Comment by jfquevedol2198** [comment] 2023-07-21 21:39
PR is ready
cc @Santhosh-Sellavel @stitesExpensify

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 17:52
@jfquevedol2198 This is due for payment today, and payment will be handled by @kadiealexander!

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 17:53
@kadiealexander I think this qualifies for a speed bonus, please check as it completed 72 business hours, not sure why Melvin didn't trigger that comment.

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 18:01
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: As per this [comment](https://github.com/Expensify/App/pull/23371#issuecomment-1648622436), we are just improving the changes missed out [here](https://github.com/Expensify/App/pull/17996)
* [ ]  [@stitesExpensify] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A should be caught while testing
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A As its really basic UI
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [x]  [@kadiealexander] Link the GH issue for creating/updating the regression test once the above steps have been agreed upon:


@stitesExpensify Do you agree with the above, if so please check off 2nd alone. Thanks, If you differ on any of the above please let me know thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-03 22:18
> @kadiealexander I think this qualifies for a speed bonus, please check as it completed 72 business hours, not sure why Melvin didn't trigger that comment.

@kadiealexander Can you check this summarize so I can collect payment on ND, thanks!

**Comment by kadiealexander** [comment] 2023-08-03 23:25
Payouts due:

- [ ] Issue Reporter: $250 @ayazhussain79 (to be paid in Upwork)
- [ ] Contributor: $1000 + $500 bonus @jfquevedol2198 (to be paid in Upwork)
- [ ] Contributor+:  $1000 + $500 bonus @Santhosh-Sellavel (to be paid in NewDot)

Eligible for 50% #urgency bonus? Yes

Upwork job is [here](upwork.com/jobs/~01ca4a5f95b82060ec).

**Comment by Santhosh-Sellavel** [comment] 2023-08-04 00:59
Thanks, Requested Payment on ND!

**Comment by JmillsExpensify** [comment] 2023-08-04 04:07
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-04 04:18 UTC
Labels: External, Engineering, Weekly, Needs Reproduction, Awaiting Payment, Bug
