### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250]  Android - Split - Keyboard opens and closes when tapping on split input of the last user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42821] opened 2024-05-30 09:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4585180
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Precondition:
- Samsung keyboard is used.

1. Launch New Expensify app.
2. Go to FAB > Split expense > Manual.
3. Enter amount > Next.
4. Select many participants so that the confirmation page is scrollable.
5. On confirmation page, tap on the split amount input next to the last user in the list.

## Expected Result:
Keyboard will open without issue.

## Actual Result:
Keyboard opens and closes when tapping on the split amount input of the last user in the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1d58adb2-bd3b-467e-8579-d0bc4443886d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd23cc3f2ade28b9</li>
        <li>Upwork Job ID: 1796562307300827136</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102596353</li>
<li>tienifr | Contributor | 102596356</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser / @isabelastisser</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @isabelastisser</details>

**Comment by izarutskaya** [comment] 2024-05-30 09:04
We think this issue might be related to the #vip-split.

**Comment by goldenbear101** [comment] 2024-05-31 18:19
Hello,
I believe the problem described involves the Samsung keyboard on Android devices where it opens and closes when tapping on the split amount input of the last user in a scrollable list in the Expensify app. This issue is reproducible in both staging and production environments.

**Comment by goldenbear101** [comment] 2024-05-31 18:19
let me take the job up, if you may

**Comment by goldenbear101** [comment] 2024-05-31 19:29
Contributor details
Your Expensify account email: irvinwoluchem@expensify.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017e81b8541352d771

**Comment by goldenbear101** [comment] 2024-05-31 19:36
Contributor details
Your Expensify account email: [irvinwoluchem@gmail.com]
Upwork Profile Link: https://www.upwork.com/freelancers/~017e81b8541352d771

**Comment by goldenbear101** [comment] 2024-05-31 19:54
Contributor details
Your Expensify account email: irvinwoluchem@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017e81b8541352d771

**Comment by goldenbear101** [comment] 2024-06-03 20:40
**Proposal**
The issue is that when using the Samsung keyboard on the Android version of the New Expensify app, the keyboard opens and closes immediately when tapping on the split amount input field next to the last user in the list on the confirmation page.

**Root Cause**
The root cause is likely due to a conflict between the UI elements and the keyboard behavior when the screen is scrollable. Specifically, tapping on the input field near the bottom of a scrollable view might cause the view to adjust, resulting in the keyboard closing unexpectedly.

**Proposed Changes**
To solve the problem, the following changes are recommended:

1. Adjust Viewport and Scroll Behavior
Ensure that the viewport and scroll behavior are properly adjusted when the input field is focused.

```
// Adjust the viewport and scroll behavior
function handleInputFocus(event) {
    const inputField = event.target;
    // Scroll the view to ensure the input field is fully visible
    scrollView.scrollTo({
        y: inputField.offsetTop - keyboardHeight,
        animated: true,
    });
    // Ensure the keyboard remains open
    inputField.focus();
}
```
2. Prevent Keyboard from Closing
Implement logic to prevent the keyboard from closing when the input field is focused.

```
// Prevent the keyboard from closing
inputField.addEventListener('focus', handleInputFocus);
```
3. Update the Confirmation Page Layout
Ensure that the layout of the confirmation page is properly adjusted to accommodate the keyboard when it is opened.

```
// Adjust the layout of the confirmation page
<ScrollView contentContainerStyle={styles.scrollViewContent}>
    {participants.map((participant, index) => (
        <View key={participant.id} style={styles.participantRow}>
            <TextInput
                style={styles.splitInput}
                onFocus={handleInputFocus}
                placeholder="Enter amount"
                value={participant.amount}
                onChangeText={(text) => updateParticipantAmount(index, text)}
            />
        </View>
    ))}
</ScrollView>
```
4. Test with Samsung Keyboard
Ensure that the changes are tested specifically with the Samsung keyboard to verify that the issue is resolved.
```
// Test with Samsung keyboard
function testWithSamsungKeyboard() {
    // Simulate the conditions of the issue
    simulateKeyboardOpen();
    // Verify that the keyboard remains open
    assert(keyboardIsOpen());
}
```
**Expected Result**
When tapping on the split amount input field next to the last user in the list, the keyboard should open without any issues and remain open, allowing the user to input the split amount.

By implementing these changes, the user experience on the Android version of the New Expensify app will be improved, ensuring that the keyboard behavior is consistent and reliable when entering split amounts for the last user in a scrollable list.

**Comment by isabelastisser** [comment] 2024-06-04 01:28
@dukenv0307, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment] 2024-06-04 14:46
@dukenv0307, please review the new proposal above. Thanks!

**Comment by isabelastisser** [comment] 2024-06-11 14:49
@dukenv0307, can you please share an update? Thanks!

**Comment by isabelastisser** [comment] 2024-06-20 20:10
Payment summary:

@tienifr requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102596356) (Contributor) $250
@dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102596353) (Reviewer) $250

**Comment by isabelastisser** [comment] 2024-06-20 20:12
The payments were processed in Upwork. All set.

**Closed by isabelastisser** 2024-06-20 20:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
