### ISSUE TITLE
[HOLD for payment 2024-03-07] [$125] Web - Thread - Console error shows up when opening message in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37253] opened 2024-02-27 02:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread

## Expected Result:
No console error will show up

## Actual Result:
Console error shows up when opening message in thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3fde0adc-3caa-4a6f-8b56-03900565f8fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd70450a1c9c7c93</li>
        <li>Upwork Job ID: 1762304222689734656</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by askavyblr** [comment] 2024-02-27 02:58
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

Console error shows up when Reply in the thread

**What is the root cause of that problem?**

scrollRef.current?.getScrollableNode().childNodes[0] is undefined.

https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/components/FlatList/MVCPFlatList.js#L49

**What changes do you think we should make in order to solve the problem?**

getScrollableNode() method returns undefined, meaning that there is no scrollable node available at the time this function is called.

Ensure that getScrollableNode() returns a valid element before trying to access its childNodes property.

**What alternative solutions did you explore? (Optional)**

**Comment by jeremy-croff** [comment] 2024-02-27 03:25
I cannot reproduce this on latest main

**Comment by sobitneupane** [comment] 2024-02-27 04:32
Thanks for the proposal @askavyblr.

I think we can simply do the following change to solve the issue.

```diff
-    const getContentView = React.useCallback(() => scrollRef.current?.getScrollableNode().childNodes[0], []);
+    const getContentView = React.useCallback(() => scrollRef.current?.getScrollableNode()?.childNodes[0], []);
```

cc: @techievivek

**Comment by techievivek** [comment] 2024-02-27 04:55
@sobitneupane Changes looks good to me, will you push the PR for this?

**Comment by techievivek** [comment] 2024-02-27 04:55
I can review and merge.

**Comment by askavyblr** [comment] 2024-02-27 04:58
@techievivek can i raised the PR

**Comment by sobitneupane** [comment] 2024-02-27 05:01
> Changes looks good to me, will you push the PR for this?

Sure @techievivek.

**Comment by askavyblr** [comment] 2024-02-27 05:03
@techievivek I will give you the solution first, please assign it to me

**Comment by sobitneupane** [comment] 2024-02-27 05:27
@techievivek 

@dukenv0307's [proposal](https://github.com/Expensify/App/issues/37253#issuecomment-1965792048) deals with the root cause of the issue. I think we can go with his proposal.

**Comment by MitchExpensify** [comment] 2024-03-09 18:13
*Payment summary*:

C+: $125 @sobitneupane (NewDot)
C: $125  @dukenv0307 (Upwork)

I couldn't find any older contract for you @dukenv0307 so I created this job, let me know when you've accepted the offer and I'll issue payment 🙇  https://www.upwork.com/jobs/~016662aefe6aa80518

**Comment by techievivek** [comment] 2024-03-12 05:51
Not overdue, we are issuing the payments. CC @MitchExpensify

**Comment by MitchExpensify** [comment] 2024-03-12 20:56
Waiting on @dukenv0307 to accept the offer in order to pay 🙇

**Comment by youssef-lr** [comment] 2024-03-12 23:39
@dukenv0307 I think I lowered the bounty due to this being just a console error and it's not really affecting the user. Do you think the console error is a smoke for an actual bug in the UI that is noticeable by the user?

**Comment by MitchExpensify** [comment] 2024-03-17 00:00
Bump on accepting this offer as a next step @dukenv0307 https://www.upwork.com/nx/wm/offer/101299289

**Comment by MitchExpensify** [comment] 2024-03-19 21:51
Paid and contract ended 🙇

**Closed by MitchExpensify** 2024-03-19 21:51 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by sobitneupane** [comment] 2024-03-21 13:17
Requested payment in newDot.

Payment Summary: https://github.com/Expensify/App/issues/37253#issuecomment-1986938218

**Comment by JmillsExpensify** [comment] 2024-03-22 21:26
$125 approved for @sobitneupane based on summary.
