### ISSUE TITLE
[Awaiting Checklist Completion] [$1000] Web – Contact Method – Dashes are not changing to red upon entering invalid magic code.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22187] opened 2023-07-04 15:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open your profile.
2. Click on "Contact methods".
3. Click on "New contact method".
4. Add new contact and then proceed to next step.
5. Write an invalid magic code so that error appear.
6. Notice dashes or input fields are not changed to red due to error.

## Expected Result:
Dashes should change to red upon entering invalid magic code.

## Actual Result:
 Dashes are not changing to red upon entering invalid magic code.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8a613c23-788f-4f21-9ec3-a5437c0ed13c

https://github.com/Expensify/App/assets/93399543/f6915264-62df-4665-ac89-20c56c8d7599

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688460879570129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01327a7e34d0845a95</li>
        <li>Upwork Job ID: 1677362154843287552</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-07-07 17:02
@aimane-chnaif - how are the proposals here?

**Comment by jbeoris** [comment] 2023-07-08 12:42
I believe I have already fixed this issue. Check below. Very simple fix.

<img width="905" alt="image" src="https://github.com/Expensify/App/assets/8835724/b9d4975f-21a3-4be5-818c-c08b2548c2c7">

**Comment by jbeoris** [comment] 2023-07-08 12:46
Contributor details
Your Expensify account email: jackbeoris@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0165e33e93f86ebbd4

**Comment by ygshbht** [comment] 2023-07-08 14:08
Duplicate like #22190 :(

**Comment by jbeoris** [comment] 2023-07-08 16:45
<img width="873" alt="image" src="https://github.com/Expensify/App/assets/8835724/418543a4-599b-4614-be1f-b4a695daa1d0">
 Here is a proposed fix that appears to be working.

**Comment by twisterdotcom** [comment] 2023-07-10 21:32
Ah, this is a dupe of https://github.com/Expensify/App/issues/20416. Thanks for pointing it out @ygshbht.

@jbeoris, @bernhardoj and @samh-nl - feel free to move these proposals over there!

**Comment by twisterdotcom** [comment] 2023-07-17 15:19
Okay, if @aimane-chnaif agrees, I think we can go ahead. I'd still be intrigued to know whether we should HOLD until after https://github.com/Expensify/App/issues/18244#issuecomment-1634506185 is deployed to avoid conflicts, or if it's really negligible.

Either way, I'd be happy to assign you. If it's going to be HELD though, I think we'd prefer to hold on assigning as well, to give you the opportunity to hit the 3 day turnaround after we unhold. I would just remove the `Help Wanted` in that instance and we'd assign you once we were ready.

**Comment by ygshbht** [comment] 2023-07-18 15:42
Glad to see this progressing! If it makes any difference, regarding the error, i had mentioned the solution for this {here)[https://github.com/Expensify/App/issues/22190#issuecomment-1621047883]  
![image](https://github.com/Expensify/App/assets/65986357/aa32f5af-c70b-4510-b265-57b272470b91) in #22190

**Comment by flodnv** [comment] 2023-07-24 13:21
This should've been merged earlier, the only reason is I was ooo. As such, I would recommend this is eligible for the bonus @twisterdotcom

**Comment by twisterdotcom** [comment] 2023-08-02 14:22
Payment summary:

- @aimane-chnaif paid $1500 here: https://www.upwork.com/nx/wm/workroom/34252840/overview
- @bernhardoj paid $1500 here: https://www.upwork.com/nx/wm/offer/new/32195282
- @usmantariq96 paid $250 here: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25905224

**Comment by twisterdotcom** [comment] 2023-08-02 14:22
@aimane-chnaif - Still need the Checklist completing here please.

**Comment by twisterdotcom** [comment] 2023-08-06 19:01
Bump @aimane-chnaif.

**Comment by twisterdotcom** [comment] 2023-08-10 11:00
This one can't be reassigned really @aimane-chnaif so please prioritise it today.

**Closed** 2023-08-14 09:38 UTC
Labels: External, Daily, Bug
