### ISSUE TITLE
[$500] Chat - Private notes - 'Go back to home page' takes back to private notes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28586] opened 2023-10-02 08:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any user report
3. Click on header to open user details
4. Click on private notes
5. Click on My note and in note, enter any invalid expensify link eg: copy the current URL and add some text behind it
6. Click on go back to home page on 'Hmm its not here' page and observe that it takes back to private notes instead of home page

## Expected Result:
On go back to home page, app should take user back to home page

## Actual Result:
On clicking go back to home page when invalid link is opened from private notes, app takes user back to private notes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c2f190a0-e4b3-495b-a816-0ccd58d5b1b8

https://github.com/Expensify/App/assets/115492554/259efd1d-6adc-4cce-8031-408ce2f17bb7

https://github.com/Expensify/App/assets/115492554/a4f6c1b1-5d26-40ef-b367-210d7d525888

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696093010047599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea4787b34602b8d9</li>
        <li>Upwork Job ID: 1708765978713968640</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-02 08:48
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking on 'Go back to home' takes back to private notes page instead of home page
### What is the root cause of that problem?
In `Navigation` we go back when `shouldEnforceFallback` is `false`
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/libs/Navigation/Navigation.js#L124-L135
and in `FullPageNotFoundView` there is no `shouldEnforceFallback` passed in `Navigation.goBack` and the default value of `shouldEnforceFallback` being `false` navigates to the previous page.
https://github.com/Expensify/App/blob/00933e121f0952b7d1c2a3d577a04d2acc208de8/src/components/BlockingViews/FullPageNotFoundView.js#L47-L48
### What changes do you think we should make in order to solve the problem?
I think going back is the desired behavior. We can create a different string 'Go back' for `linkKey` like `notFound.goBack`
and use 
```js
onBackButtonPress: () => Navigation.goBack(ROUTES.HOME),
```
and when we use the `linkKey` 'notFound.goBackHome', we should pass `shouldEnforceFallback` as true to `Navigation.goBack(ROUTES.HOME, true)`.
We have a string in `common` for `Go back`. We may consider using that if we wish instead of creating a new `goBack` in `notFound`
### What alternative solutions did you explore? (Optional)

**Comment by saranshbalyan-1234** [comment] 2023-10-02 08:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Go back to home page' takes back to private notes on mWeb
### What is the root cause of that problem?
Need to change onLinkPress to  Navigation.navigate(ROUTES.HOME),
https://github.com/Expensify/App/blob/4ebeea00ebf1470bbf085a51cb9b9ec0735cf511/src/components/BlockingViews/FullPageNotFoundView.js#L42-L52
https://github.com/Expensify/App/blob/ab48f3f531c5aa6e36ca1a850613f827c880a320/src/components/BlockingViews/BlockingView.js#L46-L55
I both the above pages, default value for linkKey is 'notFound.goBackHome' is onPress which is calling  Navigation.dismissModal() which causes this behaviour.
If the default value is GoHone, we should be navigating to home.
### What changes do you think we should make in order to solve the problem?
Need to change default value of onLinkPress to like this in both the places.
```javascript
 onLinkPress: () =>  Navigation.navigate(ROUTES.HOME),
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by andrzej-nowak** [comment] 2023-10-02 12:03
It is because of Navigation Management on React native. This is very normal issue. If you hire me. I can do it in 2 hours.
I sent proposal on Upwork. Andrzej Nowak.
Please give me an offer, I will do the job. Thank you.

**Comment by s77rt** [comment] 2023-10-02 17:03
I'm not sure about the current behaviour whether the links in the menu item should be clickable. Or even if we should store rich text in notes. Asked in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696266142168929).

**Comment by sakluger** [comment] 2023-10-02 20:51
I am not passionate about fixing this issue. I do think that you should be able to add links in private notes, but don't think it's really an issue that if you get to the "Page not found" screen and click "Go back home" that it just takes you to the previous page.

Either way, let's see how the Slack conversation settles.

**Comment by s77rt** [comment] 2023-10-06 01:28
No updates in Slack yet. @sakluger Do you think we should close this one?

**Comment by s77rt** [comment] 2023-10-09 14:49
Not overdue. Still discussing in slack

**Comment by s77rt** [comment] 2023-10-12 18:32
Not overdue. Just bumped the slack thread

**Comment by sakluger** [comment] 2023-10-12 23:34
I think we should close this issue. We discussed extensively [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696266142168929). In my view, if a user somehow get to that page, clicks the "Go back home" link, and ends up on the Private Notes page again, they will figure out that they have to click back again to go back home. I'm going to close.

**Closed by sakluger** 2023-10-12 23:34 UTC
Labels: External, Daily, Help Wanted, Bug
