### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Settings - Left hand menu and RHP do not open instantly when opening from link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44585] opened 2024-06-28 00:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/settings/preferences/priority-mode
2. Note that the left hand menu and the priority-mode pop-up does not open instantly
3. Click Home
4. Click Account settings
5. Navigate through the settings

## Expected Result:
In Step 1, when opening the settings from link, the left-hand menu and RHP will open instantly
In Step 5, the selected tab will be highlighted

## Actual Result:
In Step 1, when opening the settings from link, the left-hand menu and RHP do not open instantly
In Step 5, the selected tab is not highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0a0a8a14-333d-4765-9481-24a112c14b39

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fca7dda4a362b49</li>
        <li>Upwork Job ID: 1806491850550694979</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103070943</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-06-28 00:34
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-28 00:34
We think that this bug might be related to #vip-vsp

**Comment by MitchExpensify** [comment] 2024-07-01 20:48
Waiting on proposals, Melvin

**Comment by kaushiktd** [comment] 2024-07-02 03:39
### Please re-state the problem that we are trying to solve in this issue.
Settings - Left hand menu and RHP do not open instantly when opening from link

### What is the root cause of that problem?
The root cause of the issue is that the necessary data for rendering the left-hand menu and right-hand panel (RHP) is not immediately available when navigating directly to a specific URL, causing a delay in rendering and resulting in incomplete UI display. This occurs because the components try to render before the data is fully loaded, leading to a delay in the UI being displayed and the selected tab not being highlighted.

### What changes do you think we should make in order to solve the problem?
To resolve this issue, ensure that the component explicitly handles the loading state and waits for the necessary data before rendering the main content. Here’s how you can do it:

- Add a Loading State:

    - Use a state variable to track whether the component is still loading.
    - Use a useEffect hook to update this state once all required data has been fetched.
- Conditional Rendering:
- 
    - Render a loading indicator while waiting for the data.
    - Render the main content only after all necessary data is available.
  
 const [isLoading, setIsLoading] = useState(true);
 useEffect(() => {
        if (priorityMode !== undefined && user !== undefined && preferredTheme !== undefined) {
            setIsLoading(false);
        }
    }, [priorityMode, user, preferredTheme]);

    if (isLoading) {
        return (
            <ScreenWrapper>
                <Text>Loading...</Text>
            </ScreenWrapper>
        );
    }

**video:-** https://drive.google.com/file/d/1OP8jCA7-NAS8CtGB8jPgdhnhJKyKhS9q/view?usp=sharing

**Comment by grogou** [comment] 2024-07-02 09:19
### Please re-state the problem that we are trying to solve in this issue.

When opening the settings from link, the left-hand menu and RHP do not open instantly.
The selected tab is not highlighted

### What is the root cause of that problem?

The `LottieView` component in the `lottie-react-native` package causes an infinite re-render loop when the `autoPlay` property is set to `true`. This prevents the Settings page from rendering properly. Due to the continuous re-rendering of the component, the highlighting is also not working. The problem occurs not only on the Preferences page but also on all settings pages that have Lottie animations, such as the Security page.

### What changes do you think we should make in order to solve the problem?

I initially tried to control the Lottie animation manually as recommended in the [documentation](https://docs.expo.dev/versions/latest/sdk/lottie/). However, this approach did not work as expected.
```js
useEffect(() => {
  // Attempt to control the animation programmatically instead of using autoPlay
  // animation.current?.play();
}, []);
```
To avoid the infinite re-rendering, I used a state variable autoPlayDelay that temporarily holds the autoPlay value. This conditionally renders an empty view which prevents the infinite re-renders.
```js
const [autoPlayDelay, setAutoPlayDelay] = useState(autoPlay);
useEffect(() => {
    const ac = new AbortController();
    if (autoPlayDelay) {
        setTimeout(() => setAutoPlayDelay(false), 0);
    }
    return function cleanup() {
        ac.abort();
    };
}, []);

// If the image fails to load or app is in background state, we'll just render an empty view
// using the fallback in case of a Lottie error or appState.isBackground to prevent
// memory leak, see issue: https://github.com/Expensify/App/issues/36645
// 
// autoPlayDelay is using to prevent infinite re-renders when autoPlay is enabled
if (isError || appState.isBackground || autoPlayDelay) {
    return <View style={[aspectRatioStyle, props.style]} />;
}
```

https://github.com/Expensify/App/assets/10712881/5890a4f9-aecd-4890-b7bb-c97e96eaf9ff

**Comment by MitchExpensify** [comment] 2024-07-06 16:15
@abdulrahuman5196 please review the proposals above as a next step, thanks!

**Comment by abdulrahuman5196** [comment] 2024-07-08 20:29
Hi @MitchExpensify, I am having lesser availability now. Kindly re-assign the labels for another C+. Unassigning myself from the issue.

**Comment by MitchExpensify** [comment] 2024-07-10 22:17
Looking for a volunteer here https://expensify.slack.com/archives/C02NK2DQWUX/p1720649838512589

**Comment by grogou** [comment] 2024-07-11 05:55
@MitchExpensify what about our proposals?

**Comment by Kicu** [comment] 2024-07-11 14:52
hey @ishpaul777 I will take a deeper look tomorrow. But from my experience there is no single way of debugging these things.
Could be that some underlying library is not ready React concurrent (which we didn't know about) or could be our code.
Out of context Im afraid I can't help much with this, but I will spend a bit of time tomorrow to take a look and write some kind of response.

Meanwhile other people could still try to find the solution - in the end we want to stick to Strict Mode

**Comment by kaushiktd** [comment] 2024-07-12 06:06
@ishpaul777  Today, I pulled code, and while it works fine, there is a one-second delay. What do you want me to do next regarding this issue?
[screen-capture.webm](https://github.com/user-attachments/assets/94c78751-a991-408e-aa02-e23a75b587ef)

**Comment by MitchExpensify** [comment] 2024-07-15 16:23
Priority mode is used for day to New Expensify use so I think this fits into #wave-collect. Accessing it via the URL directly isn't mainline so labelling it polish

**Comment by MitchExpensify** [comment] 2024-07-16 17:56
Reassigning as I'm headed on leave 🙇

**Comment by WojtekBoman** [comment] 2024-07-18 14:04
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by marcaaron** [comment] 2024-07-18 19:03
Sounds good!

**Comment by marcaaron** [comment] 2024-08-06 01:01
I think we're just waiting on payment for @ishpaul777 at this point.

**Comment by RachCHopkins** [comment] 2024-08-07 00:41
Payment approved in UpWork for @ishpaul777 - sorry for the delay Ishpaul!

**Closed by RachCHopkins** 2024-08-07 00:41 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by RachCHopkins** [comment] 2024-08-07 00:45
Payment Summary:

- Contributor: @ishpaul777 paid $250 via [Upwork](https://www.upwork.com/nx/wm/workroom/37845134/overview)
- Contributor+: @WojtekBoman does not require payment (Contractor)

**Comment by RachCHopkins** [comment] 2024-08-07 00:49
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
