### ISSUE TITLE
[$500] Workspace - The middle message flows out of the container when the email is longer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9287] opened 2022-06-02 00:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
2. Add a new member with a big email to the workspace via Manage Members > Invite
3. Log-in as the member and send a message in the member's workspace chat
4. Log back in again to the admin account and remove the member from the workspace via Manage Members > Remove
5. Now log-in as the member again and navigate to the workspace chat
## Expected Result:
Verify the all messages (footer and middle) doesn't go out of the container and you can see the whole message.

## Actual Result:
The middle message flows out of the container when the email is long.
## Workaround:
visual
## Platform:

Where is this issue occurring?

- Android
- Mobile Web

**Version Number:** 1.1.70-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5593655_Screenshot_20220601-163231_New_Expensify](https://user-images.githubusercontent.com/43996225/171523001-06c4a946-85fa-4e39-a79d-805502a4e209.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2022-06-02 03:27
Posted!

Internal - https://www.upwork.com/ab/applicants/1532202118117892096/job-details
External - https://www.upwork.com/jobs/~0128e737173a7ddbbd

**Comment by parasharrajat** [comment] 2022-06-02 07:56
This may be a regression from https://github.com/Expensify/App/pull/8409.

**Comment by michaelhaxhiu** [comment] 2022-06-02 10:15
Came here to say something similar to Rajat - I could've sworn we fixed this in the past. Let's identify if this is a regression and if so, run through the RCA process like usual.

**Comment by rushatgabhane** [comment] 2022-06-02 21:11
Okay, I'll get back to this tomorrow

**Comment by jliexpensify** [comment] 2022-06-03 01:14
Assigning Kadie as I'm heading OOO

**Comment by rushatgabhane** [comment] 2022-06-05 22:22
> This one which only happens for archived policy expense chat and I think RenderHTML is causing it

@thesahindia Hmm, I highly doubt because content width is set to 80% https://github.com/Expensify/App/blob/50da22fa41944f42b7c36ba7a91f0ab737eb6cc6/src/components/RenderHTML.js#L19


<hr />

> The email is wrapped inside Tooltip and that's what causing this

Yep, that's close but doesn't explain why that's a problem or a fix for it.

### Fix 

Add this prop to Tooltip `containerStyles={[styles.dInline]}`

https://github.com/Expensify/App/blob/26956bb813f2c0ef9b256b06a3d90df10b82e5d2/src/components/ReportWelcomeText.js#L116

<img width="460" alt="image" src="https://user-images.githubusercontent.com/29673073/172072487-9bb13a80-28ef-4d48-abdf-493a1149e727.png">

**Comment by rushatgabhane** [comment] 2022-06-05 22:51
Alright, so here's what I think.

- This is occuring because of `RenderHTML`. We started using `RenderHTML` for messages that _can be long_ very recently (~10 days).
- So the root cause behind this issue is new and **unknown**.
- This issue is a regression from #9199, and not #8409


I think we should treat the issue mentioned on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1654158847672999) as a seperate issue.

- It is a regression from #8409. 
- And a fix for it is to add `containerStyles={[styles.dInline]}` to the `Tooltip` in `ReportWelcomeText`. 
- To avoid further regressions, we should **_redesign_** `Tooltip`.

**Comment by rushatgabhane** [comment] 2022-06-06 00:08
Update: aha!

Adding `styles.breakAll` fixes `RenderHTML` being nested inside `Text` on Web.
But on native, `styles.breakAll` is a no-op, THIS IS THE ROOT CAUSE!

So this looks like a purely css solution to me!
cc: @thesahindia

**Comment by kadiealexander** [comment] 2022-06-09 03:16
Price doubled! Please get your proposals in.

**Comment by sobitneupane** [comment] 2022-06-10 10:29
> Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)

@rushatgabhane I am bit confused by 'from an account that's on the policyExpenseChat beta'. What is policyExpenseChat beta? How can I be on the policyExpenseChat beta? Can you help me on this?

**Comment by rushatgabhane** [comment] 2022-06-10 10:31
>  How can I be on the policyExpenseChat beta? Can you help me on this?

@deetergp can you please help @sobitneupane get on the beta?

**Comment by rushatgabhane** [comment] 2022-06-10 19:37
@sobitneupane what's your email for new expensify? It'll be needed to add to the beta

**Comment by allroundexperts** [comment] 2022-06-12 20:28
# Proposal

## Issue
The `Text` component in react native is a special component that is unique relative to the layout. Everything inside is not considered to be part of the flex layout. In short, we should not use a View wrapped in Text having a child Text ie: 
```
<Text>
  <View>
    <Text>Text</Text>
  </View>
</Text>
```
ref: https://reactnative.dev/docs/text#containers

## Solution
We should not use `View` inside the `Text` component. The `RenderHTML` function returns a `View` with a child `Text`. As such, wrapping the response inside `Text` causes the overflow issue. We should change the following:
https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/components/ReportWelcomeText.js#L63-L122
To:
```
<>
            {isPolicyExpenseChat && isArchivedRoom && <RenderHTML html={reportArchivedText} />}
            <Text style={[styles.mt3, styles.mw100, styles.textAlignCenter]}>
                {!(isPolicyExpenseChat && isArchivedRoom)
                    && (
                        <>
                            {/* Add align center style individually because of limited style inheritance in React Native https://reactnative.dev/docs/text#limited-style-inheritance */}
                            <Text style={styles.textAlignCenter}>
                                {props.translate('reportActionsView.beginningOfChatHistoryPolicyExpenseChatPartOne')}
                            </Text>
                            <Text style={[styles.textStrong]}>
                                {/* Use the policyExpenseChat owner's first name or their email if it's undefined or an empty string */}
                                {lodashGet(props.personalDetails, [props.report.ownerEmail, 'firstName']) || props.report.ownerEmail}
                            </Text>
                            <Text>
                                {props.translate('reportActionsView.beginningOfChatHistoryPolicyExpenseChatPartTwo')}
                            </Text>
                            <Text style={[styles.textStrong]}>
                                {ReportUtils.getPolicyName(props.report, props.policies)}
                            </Text>
                            <Text>
                                {props.translate('reportActionsView.beginningOfChatHistoryPolicyExpenseChatPartThree')}
                            </Text>
                        </>
                    )}
                {isChatRoom && (
                    <>
                        {/* Add align center style individually because of limited style inheritance in React Native https://reactnative.dev/docs/text#limited-style-inheritance */}
                        <Text style={styles.textAlignCenter}>
                            {roomWelcomeMessage.phrase1}
                        </Text>
                        <Text style={[styles.textStrong]} onPress={() => Navigation.navigate(ROUTES.getReportDetailsRoute(props.report.reportID))}>
                            {ReportUtils.getReportName(props.report, props.personalDetails, props.policies)}
                        </Text>
                        <Text>
                            {roomWelcomeMessage.phrase2}
                        </Text>
                    </>
                )}
                {isDefault && (
                    <>
                        {/* Add align center style individually because of limited style inheritance in React Native https://reactnative.dev/docs/text#limited-style-inheritance */}
                        <Text style={styles.textAlignCenter}>
                            {props.translate('reportActionsView.beginningOfChatHistory')}
                        </Text>
                        {_.map(displayNamesWithTooltips, ({
                            displayName, pronouns, tooltip,
                        }, index) => (
                            <Text key={displayName}>
                                <Tooltip text={tooltip}>
                                    <Text style={[styles.textStrong]} onPress={() => Navigation.navigate(ROUTES.getDetailsRoute(participants[index]))}>
                                        {displayName}
                                    </Text>
                                </Tooltip>
                                {!_.isEmpty(pronouns) && <Text>{` (${pronouns})`}</Text>}
                                {(index === displayNamesWithTooltips.length - 1) && <Text>.</Text>}
                                {(index === displayNamesWithTooltips.length - 2) && <Text>{` ${props.translate('common.and')} `}</Text>}
                                {(index < displayNamesWithTooltips.length - 2) && <Text>, </Text>}
                            </Text>
                        ))}
                    </>
                )}
            </Text>
        </>
```

## Result

### Android
<img width="341" alt="Screenshot 2022-06-13 at 1 26 11 AM" src="https://user-images.githubusercontent.com/30054992/173252310-dbebfe98-8230-4db1-a48b-a0c58f3986cf.png">

### Web
<img width="403" alt="Screenshot 2022-06-13 at 1 28 11 AM" src="https://user-images.githubusercontent.com/30054992/173252379-a221ef34-4134-47f7-830c-6015aa1db320.png">

**Comment by sobitneupane** [comment] 2022-06-13 02:34
> @sobitneupane what's your email for new expensify? It'll be needed to add to the beta

sobit.neupane.111@gmail.com and sobit.neupane.111+2@gmail.com

**Comment by rushatgabhane** [comment] 2022-06-13 15:52
> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously ([contributing.md](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md))

@allroundexperts I'm holding on the review until your first issue is closed.

**Comment by rushatgabhane** [comment] 2022-06-13 15:52
New proposals are welcome!

**Comment by allroundexperts** [comment] 2022-06-15 17:54
@rushatgabhane My issue got closed. Can you review my proposal now?

**Comment by rushatgabhane** [comment] 2022-06-16 08:50
@allroundexperts your proposal makes sense. You've given a reason why [wrapping `<RenderHTML>` inside `<Text>` is a problem. 
](https://github.com/Expensify/App/issues/9287#issuecomment-1146893826)
```
// This is bad
<Text>
    <RenderHTML html={longText} />
</Text>
```

Don't forget to take care of spacing (top margin) in the PR.

**Comment by deetergp** [comment] 2022-06-21 16:30
@rushatgabhane I agree — @allroundexperts's proposal looks solid. Let's go with that one!

**Comment by jliexpensify** [comment] 2022-06-22 23:28
Sent invites to @allroundexperts and @rushatgabhane

**Comment by allroundexperts** [comment] 2022-06-28 07:03
@jliexpensify Applied on upwork!

**Comment by mvtglobally** [comment] 2022-07-05 04:40
Issue not reproducible during KI retests. (First week)

**Comment by rushatgabhane** [comment] 2022-07-05 15:30
> Issue not reproducible during KI retests

Interesting.. we don't have a PR yet. cc: @allroundexperts

**Comment by allroundexperts** [comment] 2022-07-05 15:33
@rushatgabhane That's true.

**Comment by mvtglobally** [comment] 2022-07-12 04:38
Issue not reproducible during KI retests. (Second week). Not sure if we are missing any step. 
@rushatgabhane  are you able to repro?

**Comment by rushatgabhane** [comment] 2022-07-12 06:44
@mvtglobally not reproducible.

**Comment by rushatgabhane** [comment] 2022-07-12 07:06
@jliexpensify I'm curious if a C+ is compensated when a proposal is [approved](https://github.com/Expensify/App/issues/9287#issuecomment-1157405583), but the issue is fixed by another [PR](https://github.com/Expensify/App/pull/9378).

**Comment by jliexpensify** [comment] 2022-07-12 07:13
@rushatgabhane let me take this one to the team and I'll get back to you with an answer!

**Comment by rushatgabhane** [comment] 2022-07-14 01:30
@jliexpensify appreciate it, thank you! 😊

**Comment by jliexpensify** [comment] 2022-07-14 03:06
Paid both, closing!

**Closed by jliexpensify** 2022-07-14 03:06 UTC
Labels: Exported, External, Engineering, Weekly
