### ISSUE TITLE
[$250] Task - Link in system message is not underlined and no "Copy URL to clipboard" menu for link

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40467] opened 2024-04-18 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a task.
3. Go to task report.
4. Add a single line link description in []() format.
5. Note that the link in system message is not underlined.
6. Change the description to multiline link.
7. Note that the link in system message is now underlined.
8. Right click on the link in the system message.
## Expected Result:
In Step 5, the single line link in the system message will be underlined.
In Step 8, right clicking on the link in the system message will invoke "Copy URL to clipboard" option.
## Actual Result:
In Step 5, the single line link in the system message is not underlined.
In Step 8. right clicking on the link in the system message invoke context menu for the entire system message, instead of "Copy URL to clipboard" option for the link.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e2bd6cfa-cfb5-4105-959a-958ed9dc2950

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a44464a57aff770b</li>
        <li>Upwork Job ID: 1781092961225887744</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-04-18 15:10
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors. 

We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment] 2024-04-18 15:10
We think this bug might be related to #vip-vsb

**Comment by miljakljajic** [comment] 2024-04-18 16:59
@jasperhuangg what do you think - definitely a deploy blocker? I think this could be worked on externally, right?

**Comment by jasperhuangg** [comment] 2024-04-18 22:46
Seems like a pretty minor bug and doesn't need to be a blocker

**Comment by jasperhuangg** [comment] 2024-04-18 22:48
It looks like something that wasn't taken into consideration in https://github.com/Expensify/App/pull/40200, I think we should get the author of the PR to fix this @bernhardoj

**Comment by jasperhuangg** [comment] 2024-04-18 22:50
I don't think we need to treat this as a regression from https://github.com/Expensify/App/issues/39496, since it wasn't originally included in the requirements for the issue it was solving https://github.com/Expensify/App/issues/39496. But we should still fix it for the sake of consistency across all types of links.

**Comment by mallenexpensify** [comment] 2024-04-24 00:13
@eh2077 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks. I see `Reviewing` here but unsure what the linked PR is

**Comment by bernhardoj** [comment] 2024-04-24 01:40
@mallenexpensify this is a missing case from my PR, so we are handling it [here](https://github.com/Expensify/App/pull/40625)

**Comment by eh2077** [comment] 2024-04-24 02:01
Unassign myself since the fix PR https://github.com/Expensify/App/pull/40625 is already ongoing.

**Comment by bernhardoj** [comment] 2024-04-24 02:02
Done

**Closed** 2024-05-06 23:15 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Bug
