### ISSUE TITLE
[$500] DEV: mWeb - Bottom Spacing Issues on NewChatSelectorPage

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28609] opened 2023-10-02 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Have a chat list that reaches the full screen OR
2. Expand the content in the Room tab and select the 'Welcome message' input in this PR (soon to be merged) - https://github.com/Expensify/App/pull/27836

## Expected Result:
Content should reach to the top of software keyboard/bottom of screen

## Actual Result:
Content ends before it reaches the bottom of screen/top of keyboard

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.75.2
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-28 at 12 52 37 (1)](https://github.com/Expensify/App/assets/93399543/23e283ee-d13f-4760-b66a-a259f6efd003)

![Screenshot 2023-09-29 at 14 01 39 (1)](https://github.com/Expensify/App/assets/93399543/a0346265-15b8-4f49-9d5a-a3f9c4dc8ffc)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695976040947749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f8b38c2bf78c3c2</li>
        <li>Upwork Job ID: 1708820161758822400</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by micahelchan623** [comment] 2023-10-03 02:27
**Proposal**

**Please re-state the issue**
Content should reach to the top of software keyboard/bottom of screen

**What is the root cause of the problem?**
The root cause is that the content container inside KeyboardAvoidingView is not handled

**What changes do you think should be made to fix this problem?**
on `NewChatPage.js`
```ts
               <KeyboardAvoidingView
                    style={{height: '100%'}}
                    behavior="padding"
                    keyboardVerticalOffset={
                        variables.contentHeaderHeight + insets.top + (Permissions.canUsePolicyRooms(betas) ? variables.tabSelectorButtonHeight + variables.tabSelectorButtonPadding : 0)
                    }
                    contentContainerStyle={{flexGrow: 1}}   //<-- add this line
                >
```

**What other alternative options did you explore? (Optional)**

**Comment by redpanda-bit** [comment] 2023-10-05 02:43
Also to add to this issue if you scroll up from the bottom spacing the spacing grows and user is unable to scroll back down. See video:

https://github.com/Expensify/App/assets/25206487/4b629625-93cf-48f6-bf10-ec8357336671

**Comment by redpanda-bit** [comment] 2023-10-06 18:30
This issue is still happening on main ios safari mweb.

https://github.com/Expensify/App/assets/25206487/f6850534-c73f-4693-855e-2eb827399991

**Comment by bondydaa** [comment] 2023-10-09 17:20
@redpanda-bit can you confirm if your video is of a simulator or physical device?

> The [second image](https://user-images.githubusercontent.com/93399543/271967759-a0346265-15b8-4f49-9d5a-a3f9c4dc8ffc.png) is just what happens when you have a hardware keyboard connected in the simulator. I don't think that's a bug it's just the behaviour of the simulator.

If it's a physical device then maybe we need to investigate more but closing this out for now as I agree if this is a simulator only issue then we don't need to worry about it.

**Closed by bondydaa** 2023-10-09 17:20 UTC
Labels: External, Daily, Help Wanted, Overdue

**Comment by redpanda-bit** [comment] 2023-10-09 20:12
This is happening on physical device also. My previous video was on the ios simulator. Now I tested on a physical device (iphone 7 safari) and it's still happening – video below.

With beta on, mWeb safari
Navigate to Send Message
Focus on the Room name input
Scroll up from the bottom of the Create room button
Scroll down -> bottom spacing issue

https://github.com/Expensify/App/assets/25206487/c8a14fe4-0438-49f6-947d-96e309daaf1b
