### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] mWeb/Safari - IOU - Next button in BNP in Request money and Send money is blocked by address bar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31134] opened 2023-11-09 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap + > Request money.
3. Go back to Home.
4. Tap + > Send money.

## Expected Result:
The Next button in BNP in Request money and Send money page will not be blocked by browser address bar.

## Actual Result:
The Next button in BNP in Request money and Send money page is blocked by browser address bar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/c07ab549-ca4d-4bee-9da2-ac1f596a869f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e7d88002f72cbd2</li>
        <li>Upwork Job ID: 1722641847224213504</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-11-13 09:33
Awaiting proposal review

**Comment by sarious** [comment] 2023-11-13 10:56
@fedirjh 
Well, is it related only for Chrome browser?
Is this "Open in the app" banner created in app or by 3rd party service?

**Comment by getusha** [comment] 2023-11-13 11:00
@sarious based on the bug report it's happening on `iOS: mWeb Safari`

**Comment by sarious** [comment] 2023-11-13 12:40
> @sarious based on the bug report it's happening on `iOS: mWeb Safari`

Oh, I see. Just want to reproduce it and  understand the origin of this banner. It looks like not the component of app? 
I don't see this banner on either the local version or the staging version on iOS mWeb Safari.

**Comment by sarious** [comment] 2023-11-14 11:02
@izarutskaya could you provide, please, the complete steps to reproduce this issue?
I'm trying to reproduce in simulator iPhone 14 Simulator Version: 16.4. The link: https://staging.new.expensify.com
But I don't see a notification on top of the page about opening the app.

**Comment by greg-schroeder** [comment] 2023-11-16 18:24
@ishpaul777 @izarutskaya any chance you could help answer @sarious's questions above?

**Comment by izarutskaya** [comment] 2023-11-17 11:13
I can still reproduce it on iPhone 14 Pro Max/iOS16.6.1
Build v1.4.0-3
If I try to change text size on my device the button becomes more visible, but I'm not sure if this will help

https://github.com/Expensify/App/assets/115492554/21fdb6cf-96f5-4cb7-a5b8-371105668392

**Comment by sarious** [comment] 2023-11-17 18:14
> The smart app banner is exclusive to safari mobile only, I think we use a webpack plugin for production and staging builds only, so you might not able reproduce this on simulator, you can try playing with configuration for webpack dev file, it may work but it still requires a physical device to be able to reproduce as far as i can tell, i'll add more details soon (currently i am AFK)

Well, thank you for answering! I've been checking on staging environment: staging.new.expensify.com. And it seems it doesn't matter is it physical device or emulator.

**Comment by greg-schroeder** [comment] 2023-11-20 18:29
Progress still being made towards a solution - @fedirjh should @sarious be assigned to this given you called this a regression?

**Comment by sarious** [comment] 2023-11-20 19:45
> > You have to install the "New Expensify" app on your device, I am able to reproduce this consistently on stag.
> 
> @ishpaul777 So it seems that this bug requires a physical device to test it?
> 
> > But any solution implemented for this can not be tested in dev Enviornment as far as i can tell, as smart banner we use to promote app require Universal Linking setup and https://staging.new.expensify.com/apple-app-site-association to be set up (I am unaware of these configs. for dev enviornment if its possible)
> 
> Maybe we should create a similar config for dev env and use it for testing?

Well, It will be good to have the possibility to test the behaviour of App banner for dev env. Not only for this issue. It seems it would be great for testing reasons of all fixes, before deploying it.

**Comment by getusha** [comment] 2023-11-20 19:54
@sarious you can check this https://github.com/Expensify/App/issues/20709 issue to see how it was tested, and apply it.

**Comment by sarious** [comment] 2023-11-20 21:18
> @sarious you can check this #20709 issue to see how it was tested, and apply it.

well, okey, I had some ideas how to try to fix current problem, but it will be good to have a possibility to check the solution. 
In #20709 the problem little bit different, but the solution may be similar (haven't looked yet).. but #20709 is possible to test in dev.

**Comment by greg-schroeder** [comment] 2023-11-26 20:14
Any luck reproducing this @sarious?

**Comment by sarious** [comment] 2023-11-26 21:32
> https://kaumadiechamalka100.medium.com/how-to-implement-universal-link-app-link-in-react-native-a33eb6532612

Well, it seems we need to implement some core solution of debugging this app banner. It looks like that someone who has Paid Apple developer account should configure app.

**Comment by getusha** [comment] 2023-11-26 22:13
@sarious you can raise this to `expensify-open-source` channel, similar issue has been fixed before.

**Comment by greg-schroeder** [comment] 2023-12-04 22:43
@sarious were you able to get that discussion rolling or do you need someone to step in?

**Comment by sarious** [comment] 2023-12-05 08:51
> @sarious were you able to get that discussion rolling or do you need someone to step in?

It seems @fedirjh has added some fix for Safari browser. It should work.

By the way, I think it would be good to implement a possibility to test "Install/open" banner to prevent future issues. How do I promote this idea so that someone will do it, if it possible at all?

**Comment by greg-schroeder** [comment] 2023-12-15 00:03
Okay so ... actually I think this one wasn't reviewed by @getusha after all, as it was handled alongside several others by @fedirjh and @c3024 here: https://github.com/Expensify/App/pull/32460

Sorry, I withdrew the offer I made by mistake.

**Closed by greg-schroeder** 2023-12-15 00:03 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
