### ISSUE TITLE
[$1000] Web - Attachment doesn't get removed after deletion if user is in the carousel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22195] opened 2023-07-04 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Send multiple attachments from account A to account B
2. Send other attachments from account B to account A
3. Open the carousel from account A and click next to view the attachment sent from account B
4. Go to account B and delete the last attachment sent
5. Go to account A's open carousel and go slide through the carousel back and forth

## Expected Result:
The last deleted attachment should by dynamically removed from the carousel after account B deleted the attachment

## Actual Result:
Attachments do not get dynamically removed after being deleted. Account A still can view attachments while inside the carousel.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/165998ea-84b0-43d4-83bf-c28bd17c767b

https://github.com/Expensify/App/assets/93399543/64e94407-aa33-4725-8c8c-7079d5c8a455

**Expensify/Expensify Issue URL:**
**Issue reported by:** Nathan Mulugeta
React JS development and Quality Assurance (GH @Nathan-Mulugeta)
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688459866242579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce9b5c2ee8d8a1a2</li>
        <li>Upwork Job ID: 1676425599861682176</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-04 18:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Attachement doesn't get removed after deletion f user is in the carosuel

### What is the root cause of that problem?

`AttachmentCarousel` component doesn't update its attachments list when `reportActions` props changed.

These are the root cause.


### What changes do you think we should make in order to solve the problem?

We need to update `attachments` state when `reportActions` props changed
Add lifecycle method `componentDidUpdate` and update attachemnts dynamically

Below is the pseudo code
```
    componentDidUpdate(prevProps, prevState) {
        if (_.isEqual(prevProps.reportActions, this.props.reportActions)) {
            return;
        }

        this.reportActionsChanged(prevState.attachments, prevState.page);
    }
```

This works as expected.

You can test https://github.com/s-alves10/App/tree/fix/issue-22195


### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-07-05 02:59
Reproduced:

https://github.com/Expensify/App/assets/59587260/a2eca061-5dd7-4364-ae16-d59a567b597d

**Comment by kadiealexander** [comment] 2023-07-05 05:00
Good find, thanks @bernhardoj! Closing as per [this discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1684437905757379).

**Closed by kadiealexander** 2023-07-05 05:00 UTC
Labels: External, Daily, Help Wanted, Bug
