### ISSUE TITLE
Room - LHN is empty after leaving public room anonymously

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44800] opened 2024-07-04 03:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log out of ND if logged in.
2. Navigate to a public room link.
3. Tap on the room header.
4. Tap Leave.

## Expected Result:
LHN will not be blank after leaving public room anonymously.

## Actual Result:
LHN is blank after leaving public room anonymously.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9e6cc002-4dd4-4b8e-a274-8567c6237e77

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-04 03:33
@hayata-suenaga FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 03:33
We think that this bug might be related to  #vip-vsb

**Comment by situchan** [comment] 2024-07-04 04:54
FYI: we're hiding Leave button in #44560

**Comment by RachCHopkins** [comment] 2024-07-04 05:56
@hayata-suenaga I'm new to the BugZero team, do you need me to do anything on this?

**Comment by hayata-suenaga** [comment] 2024-07-04 07:33
> FYI: we're hiding Leave button in https://github.com/Expensify/App/pull/44560

Seems like the bug will be fixed when the leave button is hidden in the [linked PR](https://github.com/Expensify/App/pull/44560). Removing the deploy blocker and and closing this issue as the issue is tracked in [this issue](https://github.com/Expensify/App/issues/43404).

**Closed by hayata-suenaga** 2024-07-04 07:33 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug, DeployBlocker

**Comment by hayata-suenaga** [comment] 2024-07-04 07:38
@RachCHopkins, this issue is about a bug that is categorized as a "deploy blocker". These are bugs that are found in the staging New Expensify but those that don't exist on production. This means that the bug was introduced in the code that was recently written. We have to fix these bugs before we deploy the new code to production.

Usually, an internal engineer is assigned to these issues and they handle the issue.

As a bug zero, you can do:
- tag internal engineer who was assigned to a deploy blocker issue on New Expensify if they haven't commented on the issue for a while
- If there is some contributor who identify themselves as the one introduced the bug, you can assign them so that they can fix the bug (usually, the assigned internal engineer does this, but if they haven't commented on the issue, you can also do that)

In this particular issue, the fix has already been worked on, so I decided to close this issue.
