### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Review duplicates - "Unhold" option appears for expenses that are pending duplicate reviews

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44892] opened 2024-07-05 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses with the same amount and merchant.
4. Go to transaction thread of any expense.
5. After Review duplicates button appears, click on the report header.
6. Click Unhold.

## Expected Result:
"Unhold" option should be appear for expenses that are pending review for duplicates.

## Actual Result:
"Unhold" option appeara for expenses that are pending review for duplicates.
Clicking Unhold does not unhold the expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/11941eb6-be2e-4628-9293-a43a26e9767b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9c4febbfea1864e</li>
        <li>Upwork Job ID: 1810654131699118867</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103060862</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by izarutskaya** [comment] 2024-07-05 10:39
We think this issue might be related to the #collect project.

**Comment by ahmedGaber93** [comment] 2024-07-09 12:38
Reviewing today

**Comment by ahmedGaber93** [comment] 2024-07-10 05:41
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/44892#issuecomment-2211758468) LGTM!
I agree "we shouldn't allow `unhold` if it's hold because of duplicate expenses violation" because `unhold` action will not affect on anything as it is not a real hold with `transaction.comment?.hold` value

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-07-10 13:05
PR is ready

cc: @ahmedGaber93

**Comment by ahmedGaber93** [comment] 2024-07-21 11:40
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40153
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40153/files#r1685718142
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. Yes

### Regression Test Proposal

1. Submit 2 expenses with the same amount and merchant to a workspace
2. Open the transaction thread of the duplicated expense
3. Press the chat header
4. Verify there is no "Unhold" option

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment] 2024-07-24 15:10
Requested in ND.

**Comment by ahmedGaber93** [comment] 2024-07-25 09:50
@zanyrenney Could you please pay out this when you have a chance?

**Comment by zanyrenney** [comment] 2024-07-25 14:04
**payment summary**

@ahmedGaber93 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/103060862) (Reviewer) - paid $250 via upwork.
@bernhardoj requires payment through NewDot Manual Requests - owed $250

**Closed by zanyrenney** 2024-07-25 14:04 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-26 00:40
$250 approved for @bernhardoj
