### ISSUE TITLE
[$500] Web - IOU - Vague distance request created offline can't be edited as a distance request when online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29535] opened 2023-10-13 08:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch new expensify
2. Global Create > Request Money
3. Select Distance option
4. Disable the internet connection
5. Enter a vague start location like “SF”
6. Enter a vague finish location like “LA”
7. Finish the request creation flow
8. Enable the internet connection
9. Navigate to the request with the error
10. Click on the request

## Expected Result:
You are navigated to the initial page for creating a distance request and you can see waypoints that have a red dot

## Actual Result:
You are either navigated to the expense report which looks like a normal but failed cash request (with no waypoints) or you are navigated to an error page with the request gone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/52204940-dd72-458b-ad5d-0075a6eac28d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/115492554/6cc6d990-db4a-4c67-9301-d5a8dcd4371d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4103de3895a7405</li>
        <li>Upwork Job ID: 1712745304128917504</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment] 2023-10-13 12:26
Might be related to [this](https://github.com/Expensify/App/issues/28289)

**Comment by neil-marcellini** [comment] 2023-10-13 16:02
This is effectively a duplicate of [Handle errors with geocoding for offline distance requests](https://github.com/Expensify/App/issues/22719#top). We haven't implemented this yet. Please treat this as this issue for the regression test right now.

**Closed** 2023-10-13 16:02 UTC
Labels: External, Daily, Help Wanted, Bug
