### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Web - Inconsistent behavior while choosing the option between PriorityModePage and LanguagePage.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23113] opened 2023-07-18 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account.
2. Open inspect, choose Network tab.
3. Go to Settings => Preferences => Language, choose the current checked language.
4. Notice that's there's no api was called.
5. Go to PriorityModePage, choose the current priority mode, notice that there's an api was called.

## Expected Result:
In PriorityModePage user chose the selected value, we shouldn't call the api (like LanguagePage).

## Actual Result:
In PriorityModePage user chose the selected value, the api was called every time.

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/058619c3-cb23-46e9-aa35-c2fa6c07ae47

https://github.com/Expensify/App/assets/93399543/e29007ec-9d5f-46a9-a26e-1ac984e54e24

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689667345964279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01174dc912248e0fd8</li>
        <li>Upwork Job ID: 1681381724619579392
<li>Last Price Increase: 2023-07-25</li></li>
        2023-07-18<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reporter | 25724127</li>
<li>aimane-chnaif | Reviewer | 25793802</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-18 17:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent behavior while choosing the option between PriorityModePage and LanguagePage.
### What is the root cause of that problem?
We're updating priorityMode every time, even when user has selected the current `priorityMode`:
https://github.com/Expensify/App/blob/88b94166003fa369d6c74d2fa782754166203775/src/libs/actions/User.js#L639-L655
### What changes do you think we should make in order to solve the problem?
We should add a early return (similar to our LanguagePage logic), if user selected the current value, we should do nothing.
```javascript
    const updateMode = React.useCallback((mode) => {
        if (mode.value === props.priorityMode) {
            Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
            return;
        }
        User.updateChatPriorityMode(mode.value)

    }, [props.priorityMode]);

  <SelectionListRadio
                sections={[{data: priorityModes}]}
                onSelectRow={updateMode}
                initiallyFocusedOptionKey={_.find(priorityModes, (mode) => mode.isSelected).keyForList}
            />

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by b4s36t4** [comment] 2023-07-18 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistent behavior while choosing the option between PriorityModePage and LanguagePage.
### What is the root cause of that problem?

RCA for this issue is here https://github.com/Expensify/App/blob/72bb2a24cf9529409c884f8423b6538072816f77/src/pages/settings/Preferences/PriorityModePage.js#L49 we're not doing any check here and directly calling the API to update the preference.

### What changes do you think we should make in order to solve the problem?

We should create a new function which checks that the select Mode is already selected or not.

Like below 

```jsx
const updatePriorityMode = (mode) => {
        if (mode.isSelected) {
            Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
            return;
        }

        User.updateChatPriorityMode(mode.value);
    };
```
And use this function in `onSelectRow` prop to not update the already selected key.

### What alternative solutions did you explore? (Optional)
NA

## Result

[ib.webm](https://github.com/Expensify/App/assets/59088937/727e35f6-156c-4bba-a7ab-9b8aa036349f)

**Comment by jfquevedol2198** [comment] 2023-07-18 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistent behavior while choosing the option between PriorityModePage and LanguagePage

### What is the root cause of that problem?
There is no check the passed mode is already selected or not.

https://github.com/Expensify/App/blob/72bb2a24cf9529409c884f8423b6538072816f77/src/libs/actions/User.js#L639-L655

### What changes do you think we should make in order to solve the problem?
To keep consistency like updating Locale, need to check the passed mode is selected previously or not.
If its already selected, skip API call to update mode and navigate previous page directly.

```javascript
function updateChatPriorityMode(mode, isSelected = false) {
    if (!isSelected) {
        const optimisticData = [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: ONYXKEYS.NVP_PRIORITY_MODE,
                value: mode,
            },
        ];
        API.write(
            'UpdateChatPriorityMode',
            {
                value: mode,
            },
            {optimisticData},
        );
    }
    Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
}
```

and, update [this line](https://github.com/Expensify/App/blob/72bb2a24cf9529409c884f8423b6538072816f77/src/pages/settings/Preferences/PriorityModePage.js#L49) like this:

```javascript
onSelectRow={(mode) => User.updateChatPriorityMode(mode.value, mode.isSelected)}
``` 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mehvash-Khan** [comment] 2023-07-18 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unnecessary API call is being made while choosing already selected Priority Mode in `settings/preferences` of the user.

### What is the root cause of that problem?
The case where user clicks on already selected priority mode is not handled and API call is make irrespectively.

### What changes do you think we should make in order to solve the problem?
Below proposal is similar to how we are handling change of language. Instead of making changes in file `PriorityModePage.js`, change can be made in `User.js` where function ` updateChatPriorityMode` is being called. Subscribe to the Onyx key `ONYXKEYS.NVP_PRIORITY_MODE` which will have current mode stored in it. 

```js
let priorityMode;
Onyx.connect({
    key: ONYXKEYS.NVP_PRIORITY_MODE,
    callback: (val) => (priorityMode = val),
});
```

Check if new mode selected matches the onyx key value. If yes, navigate to `settings/preferences` page and return null as below:

```js
function updateChatPriorityMode(mode) {

    if(mode === priorityMode){
        Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
        return;
    }

    const optimisticData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.NVP_PRIORITY_MODE,
            value: mode,
        },
    ];
    API.write(
        'UpdateChatPriorityMode',
        {
            value: mode,
        },
        {optimisticData},
    );
    Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
}
```



### What alternative solutions did you explore? (Optional)
Other solution can be to add condition where calling onSelect handler in `PriorityModePage.js`.

**Comment by getusha** [comment] 2023-07-19 04:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting the selected priority mode will perform an api call
### What is the root cause of that problem?
when `updateChatPriorityMode` is called there is no check if the new value is the same as previous one to avoid unnecessary api calls
### What changes do you think we should make in order to solve the problem?

Instead of passing `mode.value` to `updateChatPriorityMode` we can pass `mode` and destructure the value and isSelected, inside it.

https://github.com/Expensify/App/blob/5419d9ba7bb33347160ff20fc061e48d914eac6e/src/pages/settings/Preferences/PriorityModePage.js#L49
To
```js
User.updateChatPriorityMode(mode)
```
here is how we use it inside the function:
```js

const {value, isSelected} = mode;

if(isSelected) {
    Navigation.navigate(ROUTES.SETTINGS_PREFERENCES);
    return;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-07-20 20:29
@0xmiroslav could you review the proposals here?

**Comment by lschurr** [comment] 2023-07-24 18:38
Thanks @aimane-chnaif - can you review the proposals?

**Comment by lschurr** [comment] 2023-07-26 20:24
Bump @aimane-chnaif

**Comment by lschurr** [comment] 2023-08-10 16:52
Payment summary:

- Bug reporter: @hungvu193 $250
- Contributor: @hungvu193 $1000
- Contributor+: @aimane-chnaif $1000

**Comment by lschurr** [comment] 2023-08-10 16:52
@aimane-chnaif could you work through the checklist? https://github.com/Expensify/App/issues/23113#issuecomment-1664331644

**Comment by lschurr** [comment] 2023-08-10 16:54
Payments have been issued in Upwork.

**Comment by lschurr** [comment] 2023-08-11 16:14
Thanks! Reviewing.

**Comment by lschurr** [comment] 2023-08-11 16:16
Assigned - July 27th, 11:44am PT
Merged - July 31st, 1:31pm PT

Cool, I agree there was a weekend in between so this should be considered under 3 business days.

**Comment by lschurr** [comment] 2023-08-11 16:19
I've fixed this and gave a bonus to both @hungvu193 and @aimane-chnaif in Upwork.

New payment summary:

- Bug reporter: @hungvu193 $250
- Contributor: @hungvu193 $1500
- Contributor+: @aimane-chnaif $1500

**Comment by lschurr** [comment] 2023-08-11 16:19
@aimane-chnaif could you work on the checklist so that we can close this one out?

**Comment by cristipaval** [comment] 2023-08-14 09:40
Agree, we can proceed with the payment here @lschurr

**Comment by lschurr** [comment] 2023-08-14 15:17
Great, payments have been issued. Closing.

**Closed by lschurr** 2023-08-14 15:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
