### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Send invoice - "Chat Report" appears in room mention list after sending invoice

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43988] opened 2024-06-19 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Type #.
4. Note that there is no Chat report in the mention list.
5. Go to FAB > Send invoice.
6. Send invoice to anyone under the same workspace.
7. Go to workspace chat.
8. Type #.
9. Select Chat Report from the list.

## Expected Result:
If Chat Report is a valid room mention, selecting it from the list should result in highlighted #Chat Report in the composer.

## Actual Result:
Selecting Chat Report from room mention list does not highlight the mention. # disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/badd0cdb-aad8-4db3-bff1-2f854a44bab5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01327604e093a2db66</li>
        <li>Upwork Job ID: 1803444749926103230</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102956284</li>
<li>bernhardoj | Contributor | 102956286</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by izarutskaya** [comment] 2024-06-19 12:27
We think this issue might be related to the #vip-vsb

**Comment by bernhardoj** [comment] 2024-06-19 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A "Chat report" shown in the report mentions suggestions after sending an invoice.

### What is the root cause of that problem?
A report will show in the suggestion if it passes the `canReportBeMentionedWithinPolicy` condition.
https://github.com/Expensify/App/blob/e0ff35b59e7743be7e666915f53f1b14a6ca1633/src/libs/ReportUtils.ts#L6934-L6940

An invoice room is considered a chat room.
https://github.com/Expensify/App/blob/e0ff35b59e7743be7e666915f53f1b14a6ca1633/src/libs/ReportUtils.ts#L968-L970

The invoice room has a Chat report as the name. Chat report is basically a default name for a report. If you see the invoice room header, the name isn't Chat room because there is another logic to get the invoice room name.

### What changes do you think we should make in order to solve the problem?

I don't think we should include the invoice room as a mentionable room because it's not a room that follows a room name condition that starts with a #. So, I suggest ignoring the invoice room in `canReportBeMentionedWithinPolicy`.
```
return isChatRoom(report) && !isInvoiceRoom(report) && !isThread(report);
```

**Comment by ahmedGaber93** [comment] 2024-06-20 20:40
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/43988#issuecomment-2178671142) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment] 2024-06-21 12:21
Hmmmm the proposal kind of makes sense as in I think will solve the issue, but the invoice room is kind of a chat room I think.... so not sure if it is technically correct.

I see this was added here https://github.com/Expensify/App/pull/40303 as part of the Invoicing v1 project. So let's ask @rezkiy37, @cristipaval and @madmax330

**Comment by rezkiy37** [comment] 2024-06-24 08:50
It wasn't mentioned in the [doc](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY). So we need to clarify with Exfy devs.

**Comment by cristipaval** [comment] 2024-06-24 09:53
The invoice room is a private workspace room. So, it makes much sense from the user standpoint to be mentionable. Is it possible to mention workspace chats? As part of the Invoicing v1 project, we want to make the invoice rooms behave as much as possible, such as workspace chats. cc'ing @davidcardoza to confirm.

**Comment by ahmedGaber93** [comment] 2024-06-24 11:56
Not overdue, still discussing https://github.com/Expensify/App/issues/43988#issuecomment-2182649077

**Comment by davidcardoza** [comment] 2024-06-24 22:10
An invoice room mention should follow the same pattern as a workspace chat mention. There has been no proposal for an invoice room mention to deviate from the behavior of a workspace room.

**Comment by ahmedGaber93** [comment] 2024-06-25 17:06
If we will allow the invoice room to be mentionable, what is the mentionable `roomName` in this case

**Comment by davidcardoza** [comment] 2024-06-26 14:49
The mentionable `roomName` should be the room title, using your video in the GH OP as an example, the mention would look like `#maggot`

For some background the `roomName` of an invoice room changes based on who is viewing the room. 

- An invoice receiver will see the `roomName` as %senderWorkspaceName%
- An invoice sender will see a different `roomName` will see either : %receiverDisplayName% (or primaryLogin fallback if one isn't set) or %receiverWorkspaceName%  based on if the invoice receiver is an existing Expensify workspace admin

**Comment by bernhardoj** [comment] 2024-06-26 16:26
But a user display name can have multiple words and a room mention pattern is #{singleWord}. This mention only works for #admins, #announce, and user-created policy room.

**Comment by davidcardoza** [comment] 2024-06-28 00:59
Interesting, let me bring this up in Slack.

**Comment by davidcardoza** [comment] 2024-06-28 01:12
Discussing here - https://expensify.slack.com/archives/CSL3XBCCR/p1719536877926699

**Comment by ahmedGaber93** [comment] 2024-06-28 11:11
Not overdue, still Discussing

**Comment by ahmedGaber93** [comment] 2024-07-01 18:34
Not overdue, still discussing. @davidcardoza Can you share what is the discussion [here](https://github.com/Expensify/App/issues/43988#issuecomment-2195912961) result?

**Comment by davidcardoza** [comment] 2024-07-02 00:35
We agreed to not make invoice rooms mentionable as it will increase the scope. We may revisit some other time, but for now let's move forward with not allowing invoice rooms to be mentionable.

**Comment by ahmedGaber93** [comment] 2024-07-02 08:30
@iwiznia based on the above comment ☝️ I think we can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/43988#issuecomment-2178671142) now.

**Comment by bernhardoj** [comment] 2024-07-02 13:15
PR is ready

cc: @ahmedGaber93

**Comment by slafortune** [comment] 2024-07-11 13:12
Ended contract for this GH with UpWorks

**Comment by bernhardoj** [comment] 2024-07-16 02:07
Payment should be due [tomorrow](https://github.com/Expensify/App/issues/43988#issuecomment-2220189727) (07-17)

**Comment by ahmedGaber93** [comment] 2024-07-16 11:41
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40303
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40303#issuecomment-2230676127
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.


### Regression Test Proposal

1. Click FAB > Send invoice.
2. Send an invoice to anyone under a workspace.
3. In the invoice room, type #
4. Verify there is no Chat Report in the list

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment] 2024-07-17 02:59
Requested in ND.

**Comment by ahmedGaber93** [comment] 2024-07-18 05:58
@slafortune Could you please pay out this when you have a chance. Thanks!

**Comment by slafortune** [comment] 2024-07-18 16:03
@ahmedGaber93 Paid $250 for the C+ role via UpWorks

@bernhardoj is owed $250 for the Contributor Role via NewDot

**Closed by slafortune** 2024-07-18 16:03 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-19 02:26
$250 approved for @bernhardoj
