### ISSUE TITLE
[$250] Web -Send Invoice - Comments sent after an invoice get hidden when returning to invoice report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41318] opened 2024-04-30 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Send an invoice to user B
3. Open the invoice room and send a comment
4. Click on the IOU to open the expense details page
5. Click on the header to go back to the invoice room

## Expected Result:
The IOU gets highlighted and the comment under the IOU will be visible

## Actual Result:
Only the IOU is seen and the comment under the IOU is hidden

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d996f185-8aea-4e0b-96eb-1afcf0953465

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e2e9b3f101f09fc</li>
        <li>Upwork Job ID: 1785304503598456832</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2024-04-30 13:44
Invoice highlighting is a new feature that isn't possible on production, so this shouldn't be considered a blocker.

**Comment by Julesssss** [comment] 2024-04-30 13:45
**Prod**
![Screenshot 2024-04-30 at 14 45 00](https://github.com/Expensify/App/assets/10736861/c0801933-4a09-44af-8db9-54c1532d55bf)

**Comment by Julesssss** [comment] 2024-04-30 13:53
Hmm, our automation didn't assign a BZ team member

**Comment by cristipaval** [comment] 2024-04-30 15:09
#vip-billpay related cc @danielrvidal

**Comment by danielrvidal** [comment] 2024-04-30 19:57
Are we sure this is not tied to a bigger issue with comment linking? I think you should be able to see the comments if you scroll down so I think it's tied to comment linking which should be getting fixed in general. @trjExpensify do you agree?

**Comment by trjExpensify** [comment] 2024-05-01 21:26
Yeah, it looks like that's a comment linking issue broadly. 

1. Scroll back in a chat you have a lot of history 
2. Go to a thread / or start one 
3. Click the hyperlink in the page header to return to the page header
4. Observe the chat beneath the parent comment can't be scrolled. 

I'd suggest moving this to #vip-vsb. CC: @roryabraham as well!

**Comment by danielrvidal** [comment] 2024-05-02 04:15
@roryabraham is there already an issue for this or should we move it over to #vip-vsb?

**Comment by Julesssss** [comment] 2024-05-07 08:19
> @roryabraham is there already an issue for this or should we move it over to #vip-vsb?

Bumping this question, not sure what to do here yet.

**Comment by rezkiy37** [comment] 2024-05-07 13:44
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-05-07 13:49
Seems like this bug is associated with a [PR](https://github.com/Expensify/App/pull/40303). I am an author. I am going to fix it like a regression.

**Comment by rezkiy37** [comment] 2024-05-08 10:50
Just opened a draft PR. Will opened for review soon 🙂

**Comment by mvtglobally** [comment] 2024-05-13 14:18
Issue not reproducible during KI retests. (First week)

**Comment by rezkiy37** [comment] 2024-05-13 14:28
The [PR](https://github.com/Expensify/App/issues/41318) has been merged.

**Comment by Santhosh-Sellavel** [comment] 2024-05-16 18:19
Please assign @mananjadhav for C+ here as he reviewed PR!

**Comment by mananjadhav** [comment] 2024-05-26 19:07
Thanks for assigning. The PR was deployed to production 4 days ago.

**Comment by mananjadhav** [comment] 2024-06-02 15:52
@trjExpensify Can you please help with the payout summary? The offending [PR](https://github.com/Expensify/App/pull/40303) was already identified before I was assigned. 

I don't think we need a regression test for this one.

**Comment by trjExpensify** [comment] 2024-06-03 15:25
Agreed, the regression tests for the invoice project should get added centrally as part of the project. 

Payment summary as follows: 

$250 to @mananjadhav for the C+ review of [the PR](https://github.com/Expensify/App/pull/41829). 

Feel free to request. Closing!

**Closed by trjExpensify** 2024-06-03 15:25 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by mananjadhav** [comment] 2024-06-03 19:24
Thanks @trjExpensify

**Comment by JmillsExpensify** [comment] 2024-06-07 03:50
$250 approved for @mananjadhav
