### ISSUE TITLE
Red dot with suspicious transaction message appears on "Assign cards"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34034] opened 2024-01-05 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704402195601959

## Action Performed:
1. Open app
2. go to settings > Wallet
3. Click on "Expensify card" in the "Assigned cards"

## Expected Result:
Card details displayed

## Actual Result:
Red dot with suspicious transaction message appears. Clicking on Inbox shows me no transactions to review as suspicious.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-01-04 at 1 59 50 PM](https://github.com/Expensify/App/assets/38435837/6d9649b0-2a36-4780-961a-901aed5684b4)

![Screenshot 2024-01-04 at 1 59 59 PM](https://github.com/Expensify/App/assets/38435837/b6d69e32-2fb3-45dc-bdb3-ff8f03bad5ea)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2024-01-08 20:10
Looks like a dupe of https://github.com/Expensify/App/issues/33923

**Closed by bfitzexpensify** 2024-01-08 20:10 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
