### ISSUE TITLE
[SMARTSCAN] [$500] MEDIUM: Scan - Workspace admin sees empty report when employee manually enters Scan request details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29828] opened 2023-10-17 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [Employee} Create a scan request in the workspace chat
3. [Employee] Manually enter amount and merchant
4. [Admin] Click on the expense preview in the workspace chat with employee when the preview appears

## Expected Result:
Workspace admin should be able to view the expense in expense report page

## Actual Result:
Workspace admin is unable to view the expense in expense report page. Only the amount is seen in the report page. There is no expense preview that leads to expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/0f15c20b-f03a-4e84-b33c-4679cd198c73

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100429f58a52793a1</li>
        <li>Upwork Job ID: 1714385920798265344</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by AmjedNazzal** [comment] 2023-10-18 10:51
Is this realy a bug? from what I can see the receipt is whispered as long as the RECEIPT_STATE is SCANREADY or SCANNING so it seem to be by design, if the admin would click on another report and back or refresh, if the RECEIPT_STATE had already changed to SCANCOMPLETE or SCANFAILED then the admin would see it just fine but some kind of refresh would have to happen so that on the admin side a new OpenReport command is called and the updated state of the receipt is received, so again, I don't know if this is really a bug.

**Comment by sakluger** [comment] 2023-10-28 01:12
Still waiting for proposals.

**Comment by sakluger** [comment] 2023-10-31 16:28
I asked for help from our expert contributors: https://expensify.slack.com/archives/C03UK30EA1Z/p1698769699421359

**Comment by sakluger** [comment] 2023-11-02 18:52
Callstack was out for a bank holiday yesterday, hoping to hear back today.

**Comment by artus9033** [comment] 2023-11-03 09:47
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by trjExpensify** [comment] 2023-11-03 11:47
👋 Stumbled across this one. Can I confirm the problem is: 

1. User uploads a receipt, while it's scanning it's a whisper only visible to the requestor ✅ 
2. User enters/modifies one of these fields manually: merchant, date or amount 
3. The scanning process stops because of that, so it should no longer be a whisper ✅ 
4. The iou/expenseReport preview component becomes visible in the DM/workspace chat ✅ 
5. A participant other than the requestor clicks the report preview component to navigate to the iou/expenseReport view
6. There's a delay in showing the _request preview_ component inside the report to access the request details, it requires a refresh ❌ 

@cristipaval I wanted to put this on your radar because of https://github.com/Expensify/App/issues/28932 just in case there's an overlap here before @artus9033 moves it forward.

**Comment by cristipaval** [comment] 2023-11-03 11:49
Thanks for pinging me @trjExpensify! At the first glance, this one seems to have the same root cause with the one that I am working on.

**Comment by artus9033** [comment] 2023-11-03 12:49
Thanks for notifying me @trjExpensify. I started investigating the issue and there seems to be more problems, which you might want to take a look at:
- regarding your issue checklist, step 3 does not work properly at the moment - after manually modifying the amount, the IOU is still a whisper only visible to the requestor; however, the total amount of requests in the workspace is modified and visible to the other user, although they naturally don't see the details of the whisper request itself
![image](https://github.com/Expensify/App/assets/10586109/05554786-a315-4b14-a846-d110e95243f6)
![image](https://github.com/Expensify/App/assets/10586109/efaf6577-cbce-4247-a8c1-13ff6c1728b8)
![image](https://github.com/Expensify/App/assets/10586109/93e4da82-2a0c-4a34-b2ad-e7ab2a824b33)

- sometimes scans that have not been modified manually freeze at the scanning stage and never finish being processed
- finally, if a scan passes processing successfully, the individual request starts carrying a proper sum, however, stays at TBD for the requestor and at 0.00 for the other user; this is also visible in staging.expensify.com

![reproduction-min](https://github.com/Expensify/App/assets/10586109/b3518d72-c5f7-42f3-90f4-a578893f8260)

These issues seem to refer to the API server - could you check if scanning is fine on your side?

**Comment by sakluger** [comment] 2023-11-03 18:19
I'm going to be OOO all next week, so I'm going to assign another BZ member now to look after the issue while I'm out.

**Comment by sonialiap** [comment] 2023-11-06 11:10
@cristipaval would you like to take over this issue or add it to https://github.com/Expensify/App/issues/28932 since you're already working on that?

**Comment by cristipaval** [comment] 2023-11-06 11:52
yes sure, I'll watch this to see if it gets fixed after my work gets deployed.

**Comment by dylanexpensify** [comment] 2023-11-07 16:48
bump @neil-marcellini @artus9033 on @trjExpensify's [question](https://github.com/Expensify/App/issues/29828#issuecomment-1795086664)! 🙇‍♂️

**Comment by artus9033** [comment] 2023-11-08 08:35
You're welcome @trjExpensify 

> Oh hm, but I thought they were saying above that it does, it just sometimes needs a refresh to make the whisper go away? (i.e that's the bug in step 6).
Oh, right, indeed the status changes after navigating to another chat or refreshing on the requestor's side, at least it does so today.

> Out of curiosity, how long did you wait or how did you conclude it's stuck scanning? Sometimes, receipt scanning can take a good while. Is it still in the scanning state now?
For PDF files, which apparently are accepted by the app, it never completed even if waiting for tens of minutes. Today it works, on the other hand, so this point can be discarded now.

> To confirm I'm understanding this, are these the steps?
Indeed they were, however, I have just checked today and can't reproduce this anymore - neither 'TBD' nor '0.00' happens. Since the old workspace I reproduced this in still shows 'TBD', it seems something must have changed on backend side in the meantime.

**Comment by cristipaval** [comment] 2023-11-08 14:26
[Web-E PR](https://github.com/Expensify/Web-Expensify/pull/39523) is still in review

**Comment by trjExpensify** [comment] 2023-11-08 17:17
>Oh, right, indeed the status changes after navigating to another chat or refreshing on the requestor's side, at least it does so today.

Cool, so the fix there is more so the immediacy of the update (i.e it shouldn't need a refresh or navigating away/back). It's not clear where that's being addressed?

>For PDF files, which apparently are accepted by the app, it never completed even if waiting for tens of minutes. Today it works, on the other hand, so this point can be discarded now.

Got it. I know we had [this issue with PDF](https://github.com/Expensify/App/issues/27680) receipts being displayed in the front-end, but they should still complete or fail at large. 

>Indeed they were, however, I have just checked today and can't reproduce this anymore - neither 'TBD' nor '0.00' happens. Since the old workspace I reproduced this in still shows 'TBD', it seems something must have changed on backend side in the meantime.

Perfect, so seems like we're a-ok here. 

So to me it's just that first one to confirm where it's being fixed. If it's not being addressed in @cristipaval's PR, then we need to focus this issue on it. 👍

**Comment by artus9033** [comment] 2023-11-09 12:44
I'll investigate if these issues have something in common

**Comment by artus9033** [comment] 2023-11-09 15:27
I believe that it might be that the Pusher problems described by @cristipaval [here](https://github.com/Expensify/App/issues/30042#issuecomment-1803678446) can be the source of the problem, or at least a part of it. I will check again after that fix is deployed to your backend.
CC: @trjExpensify

**Comment by trjExpensify** [comment] 2023-11-09 16:21
Perfect, sounds good to me. It's merged and awaiting a deploy 👍

**Comment by sonialiap** [comment] 2023-11-10 17:51
Not overdue, [PR](https://github.com/Expensify/App/pull/31061) still in review

**Comment by cristipaval** [comment] 2023-11-13 11:56
[Web-E PR](https://github.com/Expensify/Web-Expensify/pull/39523) is still in staging.

**Comment by cristipaval** [comment] 2023-11-15 08:39
> [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/39523) is still in staging.

Web-E is in prod. Hold removed.

**Comment by cristipaval** [comment] 2023-11-15 13:22
This one should be retested now that the BE fixes are deployed into production.

**Comment by trjExpensify** [comment] 2023-11-15 14:01
Nice! @artus9033 do you want to continue with the retest and evaluate what (might) be left to do.

**Comment by artus9033** [comment] 2023-11-16 15:47
Sure thing @trjExpensify.

Indeed, the behaviour with scanning is much more stable after the fix has been deployed. However, the original issue is indeed present: editing the scan request manually during scanning causes it not to be visible in the other user's session without a refresh (the report is "empty", as described in this issue).
However, I reckon that the root cause of this issue still lays on the backend side. The scanned expense it is still a whisper and this status doesn't change at all even within time after manually assigning a value & merchant name.

As can be seen in the screenshot below, the request is still a whisper on the employee's side (left; "only visible to you"), but the admin of the workspace (right) sees a request, however the transaction itself is only a whisper thus is not visible to them. To sum up, if I am correct, this is the reason why transaction details are not displayed: because they are not sent over from the backend to them.

<img width="1141" alt="image" src="https://github.com/Expensify/App/assets/10586109/0004237b-a78d-4ee7-87a4-f9b6418a5947">

CC: @cristipaval

**Comment by cristipaval** [comment] 2023-11-20 12:14
aaaah, I see what you're now seeing. The total amount that the workspace owes the employee includes the amount requested for the transaction that is still being scanned, correct?

**Comment by trjExpensify** [comment] 2023-11-21 01:27
>As can be seen in the screenshot below, the request is still a whisper on the employee's side (left; "only visible to you"), but the admin of the workspace (right) sees a request, however the transaction itself is only a whisper thus is not visible to them. To sum up, if I am correct, this is the reason why transaction details are not displayed: because they are not sent over from the backend to them.

Is this the "delay" in updating to not being a whisper? 

>6. There's a delay in showing the request preview component inside the report to access the request details, it requires a refresh ❌

**Comment by artus9033** [comment] 2023-11-21 09:05
> aaaah, I see what you're now seeing. The total amount that the workspace owes the employee includes the amount requested for the transaction that is still being scanned, correct?

Correct - that's exactly the thing.

**Comment by trjExpensify** [comment] 2023-11-21 13:22
Interesting, yeah. I was giving it a go to repro this and the whisper went away for a request to a workspace (i.e `expense` report) after editing it twice, but it didn't for a request to another person (i.e `iou` report). That seems inconsistent with your result above as that's showing the "stuck whisper" on a request to a workspace, so I wonder what the cause of that is? 

https://github.com/Expensify/App/assets/16232057/344b89d6-6cbc-45ac-98cb-0db01c7068f2

**Comment by cristipaval** [comment] 2023-11-21 14:18
Unassigning myself according to [this](https://expensify.slack.com/archives/C05DWUDHVK7/p1700512341847949)

**Comment by artus9033** [comment] 2023-11-22 10:50
@trjExpensify I checked today and it seems like this is reproducible if you hurry to edit the amount manually before scanning is finished - afterwards, the request remains a whisper forever.

Moreover, I compared the network responses with the newest backend changes. I created a test workspace with 4 requests, one of which remained a whisper forever (if you would like to investigate on your side, it's [this one](https://dev.new.expensify.com:8082/r/1354590800694222)).

The below is a screenshot of network traffic regarding actions (`reportActions_1354590800694222`) from the requestor's side:
<img width="554" alt="image" src="https://github.com/Expensify/App/assets/10586109/5ff5780f-1a87-46fb-970a-2fd558a6ef69">

And below is from the other recipient's side:
<img width="498" alt="image" src="https://github.com/Expensify/App/assets/10586109/9438af0b-bcc8-4a9c-a30e-2141d631c897">

As it can be seen, the missing action is 795...508:
<img width="533" alt="image" src="https://github.com/Expensify/App/assets/10586109/ff443b64-e696-4ee6-a2cb-dff99aafd202">
That indeed is a whisper (`whisperedTo` is a one-element array) and contains `IOUTransactionID` 503...303, which in turn is:
<img width="519" alt="image" src="https://github.com/Expensify/App/assets/10586109/e3df55d2-0c2d-45a1-bf59-3f02d0953437">

And this transaction (503...303) contains the missing report item (left: requestor, right: other recipient):
<img width="1475" alt="image" src="https://github.com/Expensify/App/assets/10586109/603a44b8-6a7d-465f-bf0c-32f484c54b1e">

However, as seen, both sides see a valid total sum (all four transactions taken into account), despite the fact that the other recipient "sees" only 3 of them.

This makes me certain that the bug is some kind of race condition or inconsistent handling of state between scanning and manual editing on backend side.

**Comment by sonialiap** [comment] 2023-11-22 11:50
Sasha has been [back from OOO](https://github.com/Expensify/App/issues/29828#issuecomment-1792926639) for a couple weeks but I never unassigned myself, doing that now since we don't need two BZ on this issue

**Comment by trjExpensify** [comment] 2023-11-22 11:53
Cool @arthurmfgtab so I think @Gonals & @cristipaval you might need to dig into this then. CC: @mountiny as well. :)

**Comment by arthurmfgtab** [comment] 2023-11-27 10:45
@trjExpensify I think you meant to tag @artus9033 😄

**Comment by trjExpensify** [comment] 2023-11-27 10:48
Haha, yup. I totally did!

**Comment by sakluger** [comment] 2023-11-27 17:55
Switching to weekly since this is Internal but doesn't have an assigned engineer. It's in the "FIRE" section of the milestone, so an engineer should pick it up once they have time.

**Comment by Victor-Nyagudi** [comment] 2023-12-02 08:25
This issue also involves interrupting the receipt scanning albeit while splitting a bill in a workspace room.  This time, an error is shown after the interruption. 

- https://github.com/Expensify/App/issues/32376

Not sure if it's related but just thought I'd mention it.

**Closed** 2024-01-11 09:32 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug, SmartScan
