### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Android - App crashes when create new chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52496] opened 2024-11-13 18:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2809@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login with gmail account
2. Go to FAB> Start chat> Add email address> Finish the flow
3. Go to FAB> Start chat

## Expected Result:
App should not crash

## Actual Result:
App crashes when create second new chat from FAB

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1311.txt](https://github.com/user-attachments/files/17737378/1311.txt)

https://github.com/user-attachments/assets/7522d213-88a9-428b-ae8c-1394d035b9b1

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856802999983156406</li>
        <li>Upwork Job ID: 1856802999983156406</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104951617</li>
<li>QichenZhu | Contributor | 104951622</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by francoisl** [comment] 2024-11-13 19:12
So far I'm unable to repro on my physical device, let's look at the logs though.

**Comment by rlinoz** [comment] 2024-11-13 19:53
Ok it just happened to me, not sure how yet, so let's not remove the blocker label for now.

**Comment by francoisl** [comment] 2024-11-13 19:54
Was it on HybridApp or standalone?

The crash file attached in the OP seems to be from HybridApp, but I'm also unable to repro there,  and don't see any fresh crash reports in Firebase.

```
11-13 18:52:06.116 W/ActivityManager( 1781): Missing app error report, app = org.me.mobiexpensifyg crashing = false notResponding = true
11-13 18:52:06.176 E/ActivityManager( 1781): ANR in org.me.mobiexpensifyg (org.me.mobiexpensifyg/yapl.android.ReactNativeActivity)
11-13 18:52:06.176 E/ActivityManager( 1781): PID: 8936
11-13 18:52:06.176 E/ActivityManager( 1781): Reason: Input dispatching timed out (4f4765e org.me.mobiexpensifyg/yapl.android.ReactNativeActivity (server) is not responding. Waited 10004ms for MotionEvent)
11-13 18:52:06.176 E/ActivityManager( 1781): Parent: org.me.mobiexpensifyg/yapl.android.ReactNativeActivity
11-13 18:52:06.176 E/ActivityManager( 1781): Frozen: false
11-13 18:52:06.176 E/ActivityManager( 1781): Load: 5.37 / 5.55 / 6.35
```


```
11-13 18:52:06.181 D/ActivityManager( 1781): Completed ANR of org.me.mobiexpensifyg in 13576ms, latency 11ms
11-13 18:52:06.181 D/Debug   ( 1781): low && ship && 3rdparty app crash, do not dump
11-13 18:52:06.183 I/Dialog  ( 1781): mIsDeviceDefault = true, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
11-13 18:52:06.192 I/DecorView( 1781): [INFO] isPopOver=false, config=false
11-13 18:52:06.193 I/DecorView( 1781): updateCaptionType >> DecorView@3f7e4b4[mobiexpensifyg], isFloating=true, isApplication=false, hasWindowControllerCallback=false, hasWindowDecorCaption=false
11-13 18:52:06.193 D/DecorView( 1781): setCaptionType = 0, this = DecorView@3f7e4b4[mobiexpensifyg]
11-13 18:52:06.206 I/DropBoxManagerService( 1781): add tag=data_app_anr isTagEnabled=true flags=0x6
11-13 18:52:06.208 D/ScrollView( 1781): initGoToTop
11-13 18:52:06.213 D/ScrollView( 1781): initGoToTop
11-13 18:52:06.226 D/RestrictionPolicy( 1781): isGoogleCrashReportAllowed : ret=true userId =0
11-13 18:52:06.232 I/SurfaceFlinger( 1022): id=35590 createSurf (0x0),-1 flag=80004, WindowToken{e0005ae android.view.ViewRootImpl$W@66e9e29}#0
11-13 18:52:06.235 D/InputTransport( 1781): Input channel constructed: 'a519f4f', fd=625
11-13 18:52:06.235 D/InputTransport( 1781): Input channel constructed: 'a519f4f', fd=644
11-13 18:52:06.235 D/InputTransport( 1781): Input channel constructed: 'a519f4f', fd=649
11-13 18:52:06.236 I/SurfaceFlinger( 1022): id=35591 createSurf (0x0),-1 flag=80004, a519f4f Application Not Responding: org.me.mobiexpensifyg#0
11-13 18:52:06.241 V/WindowManager( 1781): Changing focus from Window{4f4765e u0 org.me.mobiexpensifyg/yapl.android.ReactNativeActivity} to Window{a519f4f u0 Application Not Responding: org.me.mobiexpensifyg} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:583 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6497 com.android.server.wm.WindowManagerService.addWindow:2050 com.android.server.wm.Session.addToDisplayAsUser:211 
```

**Comment by rlinoz** [comment] 2024-11-13 19:54
standalone built from the staging branch on a physical device

**Comment by rlinoz** [comment] 2024-11-13 20:13
Yeah this is hard to repro, I feel like there is some kind of race condition happening

**Comment by rlinoz** [comment] 2024-11-13 20:24
Steps:

1 - Create button > Start chat
2 - Go back using the gesture to go back (the back button on the device probably also works)
3 - Repeat until it freezes

**Comment by rlinoz** [comment] 2024-11-13 20:52
I thought it was the KeyboardAvoidingView PR, but it is not, tested a revert locally and didn't fix the issue.

**Comment by rlinoz** [comment] 2024-11-13 20:54
I gotta go soon, will add the help wanted label

**Comment by rlinoz** [comment] 2024-11-13 21:06
Following this steps https://github.com/Expensify/App/issues/52496#issuecomment-2474713301 I was able to reproduce it in the production branch

**Comment by rlinoz** [comment] 2024-11-13 21:12
Reproduced in version 9.0.47-1 downloaded from the store, which I believe it is the prod version right now.

So I think it should be safe to remove the deploy blocker, what do you think @francoisl ?

I gotta go now though

**Comment by francoisl** [comment] 2024-11-13 21:16
Ah ok then yes, sounds good, let's demote. Also seems to only happen in this specific flow of opening chats back to back, which is not a core flow.
Thanks for looking.

**Comment by MFaheemRajput** [comment] 2024-11-14 00:25
model mapping. I have to check that model keys are allowed to update.

**Comment by QichenZhu** [comment] 2024-11-14 08:14
This might help:

https://github.com/software-mansion/react-native-reanimated/issues/6418#issuecomment-2296107100

> This problems occurs, because when the user is moving an item, it triggers an update. This update synchronously triggers the logic responsible for scrolling the list (so it triggers another update). This means that there is a recursive call to the ShadowTree::commit function in RN. Currently such recursive calls lead to a deadlock (on Android). The issue seems to have been noticed by the RN team and had been addressed in https://github.com/facebook/react-native/pull/44725, but the fix is currently behind a feature flag. I tested it, and it seems to resolve our issue. I'm not sure when this behavior will be made default.

**Comment by rlinoz** [comment] 2024-11-14 14:46
adding this one to quality since it is flaky

**Comment by jacobkim9881** [comment] 2024-11-15 14:40
> Steps:
1 - Create button > Start chat
2 - Go back using the gesture to go back (the back button on the device probably also works)
3 - Repeat until it freezes

That indeed makes a crash. It feels like letting the app load twice though loading isn't finished.

**Comment by QichenZhu** [comment] 2024-11-16 06:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App occasionally freezes after entering Start Chat screen.

### What is the root cause of that problem?
This is an upstream issue described in this comment https://github.com/software-mansion/react-native-reanimated/issues/6418#issuecomment-2296107100 and this PR https://github.com/facebook/react-native/pull/44725.

> These recursive commit+mount operations happen because it's possible to trigger state updates while we mount changes in the host platform (e.g.: we create the scroll view and we update the state to set the content offset). Those state updates trigger more mount operations, which deadlock in the mentioned place.

### What changes do you think we should make in order to solve the problem?
The upstream fix is currently behind a feature flag, so we could put this on hold until they make it the default, then upgrade React Native.

### What alternative solutions did you explore? (Optional)
Enable the feature by changing the condition in the lines below to `true`.

[`node_modules/react-native/ReactAndroid/src/main/jni/react/fabric/Binding.cpp`](https://github.com/facebook/react-native/blob/2e994fdddb05955ee8dcce1e2151288977dd1c5e/packages/react-native/ReactAndroid/src/main/jni/react/fabric/Binding.cpp#L486-L487)

```C++
  if (true /* ReactNativeFeatureFlags::
          allowRecursiveCommitsWithSynchronousMountOnAndroid() */) {
```

PS: I remember several freeze issues came up after PR https://github.com/Expensify/App/pull/48772 was merged, so it was reverted. Those issues might share the same root cause as this one, but PR https://github.com/Expensify/App/pull/48772 wasn’t the root cause.

**Comment by ahmedGaber93** [comment] 2024-11-17 01:02
@QichenZhu Thanks for the proposal.

I tested your proposal, and it fixes the issue, also react-native-reanimate team mention this fix https://github.com/software-mansion/react-native-reanimated/issues/6418#issuecomment-2298202842, it allows a piece of code that depend on a feature flag to run **but not enabled the feature on the whole app.** I tested it as possible, and it works well, But I don't know if there are any consequences of this or not, so let's see what @rlinoz think?

**Comment by rlinoz** [comment] 2024-11-18 14:35
Asked internally for thoughts on enabling the feature flag.

**Comment by VictoriaExpensify** [comment] 2024-12-02 00:32
Hey @ahmedGaber93 - can you please complete the checklist in the comment above and accept our offer in Upwork so I can pay you? https://www.upwork.com/nx/wm/offer/104951617

Contributor: @QichenZhu paid $250 via Upwork

**Comment by ahmedGaber93** [comment] 2024-12-02 12:27
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A. It is a known issue external library https://github.com/software-mansion/react-native-reanimated/issues/6418#issuecomment-2296107100

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A.

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.



- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:




### Test:


#### Android native only
1. Tap FAB > Start chat > Go back by swiping or using header back button.
2. Repeat the above steps multiple times (~10 times) and verify the app is not crashed.


Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment] 2024-12-02 12:34
> can you please complete the checklist in the comment above and accept our offer in Upwork so I can pay you?

@VictoriaExpensify Checklist have been completed, and I will get paid via NewDot

**Comment by VictoriaExpensify** [comment] 2024-12-05 02:54
Raised a request to add the regression test to test rail - https://github.com/Expensify/Expensify/issues/450650

**Comment by VictoriaExpensify** [comment] 2024-12-05 02:55
Update Payment Summary:
Contributor: @QichenZhu paid $250 via Upwork
C+: @ahmedGaber93 owed $250 via NewDot

**Closed by VictoriaExpensify** 2024-12-05 02:55 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-05 11:30
$250 approved for @ahmedGaber93
