### ISSUE TITLE
Search filters - Invited member is able to see the disabled tags in tag filter

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48493] opened 2024-09-03 17:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Create a new workspace.
3. [User A] Add a few tags in Workspace settings > Tags.
4. [User A] Disable all the tags.
5. [User A] Invite User B to the workspace.
6. [User B] Go to workspace chat.
7. [User B] Click + > Submit expense > Manual > Enter amount > Next.
8. [User B] Note that there is no Tag field on the confirmation page.
9. [User B] Go to Search > Filters.
10. [User B] Click Tag.

## Expected Result:
Invited member should not able to see the disabled tags in tag filter.

## Actual Result:
Invited member is able to see the disabled tags in tag filter.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ee165020-0dab-4c05-9fc3-61561afe65e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-03 17:12
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment] 2024-09-03 17:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can see the disabled tags in the search filters, which should not be the case, they should be not visible.
### What is the root cause of that problem?
The issue occurs because we are not checking whether a tag is enabled when generating the list of tag names.
### What changes do you think we should make in order to solve the problem?


https://github.com/Expensify/App/blob/6ef175251d0a6a0c77d86061bb64088d8bc075d0/src/libs/PolicyUtils.ts#L308
To resolve this, we should modify the code to include a check for whether a tag is enabled before adding it to the list of tag names.
https://github.com/Expensify/App/blob/6ef175251d0a6a0c77d86061bb64088d8bc075d0/src/libs/PolicyUtils.ts#L308

It should be wrapped with a condition to ensure only enabled tags are included:

```
if (tag.enabled) {
    uniqueTagNames.add(getCleanedTagName(tag.name));
}

```

### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment] 2024-09-03 17:58
https://github.com/user-attachments/assets/07726fc8-6036-43e6-98a7-bc11aa913606

**Comment by johncschuster** [comment] 2024-09-05 20:59
I think the behavior should depend on whether or not an expense has been tagged with a given tag. For example, if expenses have been tagged with both Tag A and Tag B, and Tag B is disabled at some point in time, I think Tag B should still be an available filter on the Expenses page.

That said, if Tag B has been disabled and there are NO expenses that have been tagged with Tag B, I would expect Tag B to not show up in the search results.

**Comment by johncschuster** [comment] 2024-09-05 20:59
@IuliiaHerets can you please retest the behavior with the criteria I've shared above?

**Comment by 289Adam289** [comment] 2024-09-09 14:30
Hi I'm from SWM and I am currently working on Search v2. Hiding Tag B when there are no expenses tagged with Tag B is a good idea but unfortunately I don't think it is currently possible. Advanced filters get list of all tags from onyx, hence we don't have any information if there exists expense tagged with B.

**Comment by johncschuster** [comment] 2024-09-09 21:55
Thanks for chiming in, @289Adam289! Given the way we handle getting tags currently, does the behavior in this issue sound expected, or do you feel there's still something not quite right here that needs to be fixed?

**Comment by 289Adam289** [comment] 2024-09-10 07:34
I agree with @abzokhattab comment https://github.com/Expensify/App/issues/48493#issuecomment-2327070061, so everything works as expected.

**Comment by johncschuster** [comment] 2024-09-12 21:51
Great! If this behavior is currently expected, let's close the issue.

**Closed by johncschuster** 2024-09-12 21:51 UTC
Labels: Daily, Overdue, Bug
