### ISSUE TITLE
[$1000] Split bill - "Payment details not found" for a split with 1 person

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18682] opened 2023-05-09 21:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Click + -> Split Bill
3. Input amount and click continue
4. Select 1 attendee
5. Submit Split Bill
6. Click in "split $XX for description" link in chat

## Expected Result:
Payment details should be displayed (or link should be not clickable)

## Actual Result:
"Payment details not found" error page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No, in provided build 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cc809f9f-04f7-47f8-808b-c0eb4da4dba9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7c0e8f33a8afe00</li>
        <li>Upwork Job ID: 1658164498367459328</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-05-09 21:44
Issue is not reproductible in provided build https://18652.pr-testing.expensify.com/ 

https://github.com/Expensify/App/assets/93399543/8db88031-1392-4680-b82a-dad097bec084

**Comment by aldo-expensify** [comment] 2023-05-09 22:08
Reproduced in production:

![image](https://github.com/Expensify/App/assets/87341702/d1b0c61d-c362-4bdf-87d0-797292797eb8)

**Comment by hungvu193** [comment] 2023-05-10 03:16
I think this is backend issue, with split request, the `IOUReportID` is not found inside `originalMessage` object.
<img width="1728" alt="Screenshot 2023-05-10 at 10 15 30" src="https://github.com/Expensify/App/assets/16502320/1f0e29af-51ea-4547-9f69-a4843961c280">

**Comment by wildan-m** [comment] 2023-05-10 04:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Split bill - "Payment details not found" for a split with 1 person

### What is the root cause of that problem?
We haven't defined what to show when performing a split bill with 1 person.

Previously, the split text isn't clickable and now we are making it clickable on purpose, have a look at [this PR](https://github.com/Expensify/App/pull/18143).

### What changes do you think we should make in order to solve the problem?

According to [the PR](https://github.com/Expensify/App/pull/18143), for the split bill, we'll show the participant page at the moment.

Then we can modify this line
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/components/ReportActionItem/IOUAction.js#L72-L79

To
```
    const isBillSplit = lodashGet(props, 'action.originalMessage.type') === 'split';
    const hasMultipleParticipants = props.chatReport.participants.length > 1;
    const onIOUPreviewPressed = () => {
        if (hasMultipleParticipants || isBillSplit) {
            Navigation.navigate(ROUTES.getReportParticipantsRoute(props.chatReportID));
        } else {
            Navigation.navigate(ROUTES.getIouDetailsRoute(props.chatReportID, props.action.originalMessage.IOUReportID));
        }
    };
```

Also determining isSplitBill with room participants' length isn't reliable, it will not true if we split bill with only one person. Then we can change:
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/components/ReportActionItem/IOUAction.js#L109

To:
```
                    isBillSplit={isBillSplit}
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by pecanoro** [comment] 2023-05-10 16:10
Not sure if this is going to be gone after the refactor is over for manual requests.

**Comment by pecanoro** [comment] 2023-05-10 16:13
This is the page that is supposed to be opening but for some reason, it opens the wrong one with only one participant:

![image](https://github.com/Expensify/App/assets/6474442/69966991-ef1b-4200-aba3-5f656abffe47)

**Comment by luacmartins** [comment] 2023-05-15 18:03
@aldo-expensify that comment makes sense, but we are already addressing it [here](https://github.com/Expensify/App/pull/18760/files#diff-ed950dc7498a8d4e088533184eda957a6392f6ddd94963728bb4b087dd707fe4R91)

**Comment by aldo-expensify** [comment] 2023-05-15 18:06
@luacmartins ahh, thanks! I'll close this one then.

**Closed by aldo-expensify** 2023-05-15 18:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
