### ISSUE TITLE
[$500] Android-IOU- Tapping back and then next in Request Money flow shows wrong page with $0 amount, then app crashes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28707] opened 2023-10-03 10:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap Request money
4. Enter an amount
5. Tap next
6. Select an user
7. Tap back button in app and navigate to request money page
8. Tap next

## Expected Result:
When user taps "next" from request money page, the contacts page must be displayed and app must not crash.

## Actual Result:
When user taps "next" from request money page, the contacts page must be displayed. But, again the request money page is displayed with Zero amount in mweb and web. In Android, the request money page is displayed with Zero amount and then app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/277733e3-3faa-4f6f-a9b9-c384f0508df8

https://github.com/Expensify/App/assets/115492554/ef5a0133-5f65-4481-8b2c-65b2b8d9ff2c

[utest-dl.s3.amazonaws.com_12102_26469_432782_6222926_bugAttachment_Bug6222926_1696319226552%21crash.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231003T101613Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Credential=AKIAJ.txt](https://github.com/Expensify/App/files/12791436/utest-dl.s3.amazonaws.com_12102_26469_432782_6222926_bugAttachment_Bug6222926_1696319226552.21crash.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231003T101613Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Credential.AKIAJ.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123350be82c6cc62d</li>
        <li>Upwork Job ID: 1712353638661038080</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 27156465</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-10-12 06:24
Good bug report, I updated the issue title to be a bit more clear.

**Comment by mananjadhav** [comment] 2023-10-12 06:32
@BhuvaneshPatil's proposal looks good here. I would recommend solving the amount issue as well. 

🎀 👀 🎀 C+ reviewed.

**Comment by sakluger** [comment] 2023-10-13 17:53
Oh interesting. @BhuvaneshPatil just to confirm, the original bug is not reproduceable, but this new, similar issue is reproduceable? And your same proposal will fix the new issue?

If that's true, then I think we should continue on with your solution, but I'd like @mananjadhav's feedback as well.

**Comment by mananjadhav** [comment] 2023-10-16 05:08
I'll have to test the flow before we conclude.

**Comment by mananjadhav** [comment] 2023-10-18 10:18
I think @BhuvaneshPatil's change should work. 

Also I would recommend not raising the PR until it is officially assigned to you. I understand this was earlier assigned, but the expected behavior and the bug changed. Hence we should wait for the review and internal engineer approval. 

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-10-18 16:20
I'll continue with the existing one. Can you confirm if it is merge with the latest `main`?

**Comment by sakluger** [comment] 2023-10-23 20:07
For timing, we'll use Oct 18 as the assignment date (here's where the assignment happened: https://github.com/Expensify/App/issues/28707#issuecomment-1768484423)

**Comment by mananjadhav** [comment] 2023-11-01 19:41
@marcochavezf The PR was reverted, but we didn't discuss the next steps. Should we create another fix to cover both the issues? The proposed solution will differ from the original one.

**Comment by sakluger** [comment] 2023-11-01 22:47
Discussing next steps in expensify-open-source in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1698878804349519

**Comment by sakluger** [comment] 2023-11-02 19:10
@BhuvaneshPatil do you mind having a look at the new issue to see if you're able to raise another PR that would solve both issues?

**Comment by sakluger** [comment] 2023-11-02 19:10
FYI I removed the "Hold for payment" from the title - with the regression, we aren't ready to pay yet.

**Comment by sakluger** [comment] 2023-11-03 23:37
Reassigning BZ since I'm OOO all next week.

**Comment by MitchExpensify** [comment] 2023-11-07 00:58
How is the PR coming along @BhuvaneshPatil ?

**Comment by MitchExpensify** [comment] 2023-11-09 20:47
Friendly bump @BhuvaneshPatil

**Comment by sakluger** [comment] 2023-11-13 22:41
Thanks @MitchExpensify! I'll take this one back over.

**Comment by mananjadhav** [comment] 2023-11-16 14:05
yeah please add this issue as well for fixed issues.

**Comment by arosiclair** [comment] 2023-11-20 15:03
@BhuvaneshPatil what's the status of your follow up PR?

**Comment by BhuvaneshPatil** [comment] 2023-12-14 11:11
PR has been merged

**Comment by arosiclair** [comment] 2023-12-14 15:28
Automations failed it looks like. This was deployed [a week ago](https://github.com/Expensify/App/pull/31579#issuecomment-1843656507). I think that means this is clear for payment @sakluger

**Comment by mananjadhav** [comment] 2023-12-17 18:29
Quick bum on the payout for this one @sakluger

**Comment by sakluger** [comment] 2023-12-18 22:54
**Summarizing payouts for this issue:**

Contributor: @BhuvaneshPatil $500 (paid via Upwork)
Contributor+: @mananjadhav $500 (payable via Manual Request)

Upwork job: https://www.upwork.com/jobs/~0123350be82c6cc62d

**Comment by sakluger** [comment] 2023-12-18 22:55
I'm going to close this issue out. @mananjadhav please bump me on Slack if the issue needs to be reopened for your payment.

**Closed by sakluger** 2023-12-18 22:55 UTC
Labels: External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-12-26 16:27
$500 payment approved for @mananjadhav based on summary above.
