### ISSUE TITLE
[HOLD #33518] [$500]  Scan - Confirmation page resets to empty field when previous scan request creation fails

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35064] opened 2024-01-24 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a scan request with an invalid file that will result in an error. (use corrupted pdf attached)
3. Create another scan request and reach the confirmation page

## Expected Result:
 will not change when the previous scan request creation fails

## Actual Result:
When the first request creation results in error, the confirmation page for the second request is reset to empty fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8d95d6c6-e197-4771-bf23-267eafe2ecb1

![default-file-icon (9)](https://github.com/Expensify/App/assets/78819774/84c5d88c-4a8e-4626-a2c0-8da4f2e35637)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c62efac50e9080f0</li>
        <li>Upwork Job ID: 1750180736709853184</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-24 15:37
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by bernhardoj** [comment] 2024-01-24 15:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The request confirmation info becomes empty when there is a failed scan request.

### What is the root cause of that problem?
The money request create page depends on transaction draft onyx. When there is a request money fails, it will clear the transaction draft onyx.
https://github.com/Expensify/App/blob/a8a3a4c13c78cc424c7f242a6a38d9076561e726/src/libs/actions/IOU.js#L539-L543

### What changes do you think we should make in order to solve the problem?

Don't clear the transaction draft onyx when fails because we already did it in optimistic data.

**Comment by abdulrahuman5196** [comment] 2024-01-29 10:11
Will be working on proposal review today.

**Comment by abdulrahuman5196** [comment] 2024-01-31 16:39
Still pending review. Will close out before tomorrow.

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:52
> Still pending review. Will close out before tomorrow.

Still working on review. Will check or re-assign accordingly

**Comment by JmillsExpensify** [comment] 2024-02-07 16:33
@abdulrahuman5196 Any update on your review?

**Comment by abdulrahuman5196** [comment] 2024-02-08 19:38
Hi, Sorry for the delay. Will take care of this in my morning or will re-assign tomorrow night.

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:22
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-02-12 06:29
Hi @JmillsExpensify , the root cause is same as this issue - https://github.com/Expensify/App/issues/33518. And would be fixed if we fix that issue.

we can put this issue on hold for the same.

**Comment by bernhardoj** [comment] 2024-02-12 07:52
@abdulrahuman5196 I was going to ask whether I should copy my proposal to there, but I see @adriancova proposal is the same as what I propose. Just curious, why don't we go with that?

**Comment by bernhardoj** [comment] 2024-02-12 08:19
@abdulrahuman5196 I see. Please correct me if I'm wrong, but I think it's not possible to have overlapping transaction drafts if we clear out the draft on optimistic data, even when creating multiple transactions while offline using `OPTIMISTIC_TRANSACTION_ID`.

Here is how it would run
1. Start a new money request
2. Confirm the money request
3. The draft of OPTIMISTIC_TRANSACTION_ID is cleared (optimistically)
4. Start a new money request with the same OPTIMISTIC_TRANSACTION_ID
5. The draft is new

If I understand correctly, OPTIMISTIC_TRANSACTION_ID is only being used when creating a new money request.

**Comment by JmillsExpensify** [comment] 2024-02-14 16:31
Adding a hold per the above comment.

**Comment by abdulrahuman5196** [comment] 2024-02-16 13:04
> @abdulrahuman5196 I see. Please correct me if I'm wrong, but I think it's not possible to have overlapping transaction drafts if we clear out the draft on optimistic data, even when creating multiple transactions while offline using `OPTIMISTIC_TRANSACTION_ID`.
> 
> Here is how it would run
> 
>     1. Start a new money request
> 
>     2. Confirm the money request
> 
>     3. The draft of OPTIMISTIC_TRANSACTION_ID is cleared (optimistically)
> 
>     4. Start a new money request with the same OPTIMISTIC_TRANSACTION_ID
> 
>     5. The draft is new
> 
> 
> If I understand correctly, OPTIMISTIC_TRANSACTION_ID is only being used when creating a new money request.

@bernhardoj I am not actually getting your point.

The key for storing in Onyx is still the same and whereever we use the draft data the same key is used. This causes collision since the same key will be used for the new draft request as well.

https://github.com/Expensify/App/blob/7b836cfcee79084177191e3dfb4a927698b09eb4/src/libs/actions/IOU.js#L1234

https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/actions/IOU.js#L156


I hope this clears up the context. If you have some suggestions or proposal to fix the same. Could you kindly comment in the other linked issue?

**Comment by abdulrahuman5196** [comment] 2024-02-16 18:23
>because we already did it in [optimistic data](https://github.com/Expensify/App/blob/a8a3a4c13c78cc424c7f242a6a38d9076561e726/src/libs/actions/IOU.js#L403-L407).

Ah!! @bernhardoj I got your point. It seems in scan flow, we delete the transaction data optimistically itself, so there is no point in deleting it again in failure data or success data.

But the same is not being done currently in optimistic data of split bill. We don't delete it optimistically as I checked, so if its not deleted we would be using that optimistic data at some place was my thought process. Let me check again if we can use https://github.com/Expensify/App/issues/33518#issuecomment-1867998289 proposal itself to solve the case similar to how scan flow is handled.

**Comment by JmillsExpensify** [comment] 2024-02-21 01:39
Still on hold for the linked issue.

**Comment by JmillsExpensify** [comment] 2024-03-06 04:37
Still held on linked issue.

**Comment by abdulrahuman5196** [comment] 2024-03-07 14:27
The linked issue changes are already in production.

@JmillsExpensify / @lanitochka17 Could you kindly re-test and close this issue, if its not reproducible?

**Comment by lanitochka17** [comment] 2024-03-07 16:10
Issue is not reproducible on the latest build 1.4.48-0


https://github.com/Expensify/App/assets/78819774/f44a2bfb-0e49-4e58-8133-c2fa71b91b56

**Comment by JmillsExpensify** [comment] 2024-03-13 04:23
Looks like QA isn't able to reproduce this issue, so I'm going to close.

**Closed** 2024-03-13 04:23 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
