### ISSUE TITLE
[Hold for payment Aug 27th][$250] Flicker of not found page after comment linking

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#46222] opened 2024-07-25 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:**

## Action Performed:

- In a chat with many messages copy the link to a message and send it
- Clear the app cache (Troubleshoot -> Clear cache and restart)
- Click on the message link from the first step
- See not found page for a second

## Expected Result:

Do not see not found page

## Actual Result:

See not found page

## Workaround:

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/711587a0-218d-44f0-b0c0-b90a8f7d33da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faa299c0b6dbd239</li>
        <li>Upwork Job ID: 1816947627232739954</li>
        <li>Last Price Increase: 2024-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103312251</li>
<li>ishpaul777 | Contributor | 103312254</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by FitseTLT** [comment] 2024-07-25 19:27
This is super related with https://github.com/Expensify/App/issues/46217

**Comment by Christinadobrzyn** [comment] 2024-07-26 20:30
Yes, I think this should be closed in favour of https://github.com/Expensify/App/issues/46217

@ishpaul777 do you think you can be the C+ on this https://github.com/Expensify/App/issues/46217?

**Comment by Christinadobrzyn** [comment] 2024-07-26 21:24
Hey @brunovjk would you mind if @ishpaul777 takes this as C+ since they are working on a solution based on this comment? https://github.com/Expensify/App/issues/46222#issuecomment-2251211898

**Comment by brunovjk** [comment] 2024-07-26 21:36
> Hey @brunovjk would you mind if @ishpaul777 takes this as C+ since they are working on a solution based on this comment? [#46222 (comment)](https://github.com/Expensify/App/issues/46222#issuecomment-2251211898)

No at all @Christinadobrzyn , Let's smash this bug!!! 😁 If you need help with anything, don't hesitate to ask.

**Comment by brunovjk** [comment] 2024-07-26 23:36
> Hey @brunovjk would you mind if @ishpaul777 takes this as C+ since they are working on a solution based on this comment? [#46222 (comment)](https://github.com/Expensify/App/issues/46222#issuecomment-2251211898)

No at all @Christinadobrzyn, thank you for ask :D

**Comment by janicduplessis** [comment] 2024-07-27 00:02
https://github.com/Expensify/App/issues/46217 Is actually a different bug, but both happen during comment linking and have similar repro steps.

**Comment by Christinadobrzyn** [comment] 2024-07-29 15:46
Thanks @ishpaul777 and @janicduplessis maybe I'll put a HOLD on this GH while a PR is worked on here https://github.com/Expensify/App/issues/46217

And then we can retest this to see if it's resolved? Does that sound like a good plan?

**Comment by janicduplessis** [comment] 2024-07-30 05:49
I have consolidated the fixes in https://github.com/Expensify/App/pull/46315 to make it easier to test. Most of the issues are fixed except for one on android when scrolling down after comment linking sometimes it is very janky. I am planning to look at this this week.

**Comment by Christinadobrzyn** [comment] 2024-07-30 17:11
Awesome! Thanks for the update @janicduplessis!

**Comment by Christinadobrzyn** [comment] 2024-07-31 17:34
Update for Melvin - PR - https://github.com/Expensify/App/pull/46315 is in the works!

**Comment by Christinadobrzyn** [comment] 2024-08-01 22:34
Update for Melvin - PR - https://github.com/Expensify/App/pull/46315 is in the works!

**Comment by janicduplessis** [comment] 2024-08-02 03:54
PR should be ready by tomorrow, just need to complete reviewer checklist and test all platforms.

**Comment by janicduplessis** [comment] 2024-08-05 16:54
@ishpaul777 You can start reviewing, I just need to complete the checklist and platform screenshots, will be able to do that today.

**Comment by janicduplessis** [comment] 2024-08-05 21:32
@ishpaul777 PR is ready!

**Comment by Christinadobrzyn** [comment] 2024-08-20 20:57
PR in staging - getting close! https://github.com/Expensify/App/pull/46315

**Comment by Christinadobrzyn** [comment] 2024-08-26 15:13
Awesome! Looks like the 7th day of prod is tomorrow so let's prep for payment.

- @janicduplessis you are with Margelo so paid separately, correct?
- Do we need a regression test for this?

Payouts due:

 Contributor+: $250 @ishpaul777 (upwork offer - https://www.upwork.com/ab/applicants/1816947627232739954/hired)

**Comment by janicduplessis** [comment] 2024-08-26 17:19
@Christinadobrzyn correct!

**Comment by Christinadobrzyn** [comment] 2024-08-27 18:37
Regression test - https://github.com/Expensify/Expensify/issues/423694

paid out based on this [payment summary ](https://github.com/Expensify/App/issues/46222#issuecomment-2310457441)

**Comment by Christinadobrzyn** [comment] 2024-08-27 18:38
Closing as complete!

**Closed by Christinadobrzyn** 2024-08-27 18:38 UTC
Labels: Reviewing, External, Daily, Bug
