### ISSUE TITLE
[HOLD for payment 2023-05-16] Unable to use keyboard arrow navigation in the list if open "new chat"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18516] opened 2023-05-05 23:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on "+" FAB menu icon
3. Click on "New chat"
4. Press CMD+K
5. Press up/down arrows keys in the keyboard to navigate in the chat list
## Expected Result:
User is able to navigate in the chat switcher list by using the up/down arrows keys

## Actual Result:
Nothing happens when user presses the up/down arrows keys

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236586532-eed167e5-aa71-4270-b9b9-b919ed2bce1d.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-05-08 12:49
Huh this is weird because if you go directly to "Search" (or "New chat") the arrow keys work just fine, something with pressing "CMD + K" removes the arrow key listener or something

**Comment by Beamanator** [comment] 2023-05-08 12:51
And can confirm this is reproducible in staging, and isn't reproducible in production

**Comment by Beamanator** [comment] 2023-05-08 13:10
Looks like this could have been caused by https://github.com/Expensify/App/issues/17590 or https://github.com/Expensify/App/issues/18420

Posted in Slack to get some ideas: https://expensify.slack.com/archives/C01GTK53T8Q/p1683551147132719

**Comment by azimgd** [comment] 2023-05-08 13:29
👀

**Comment by mollfpr** [comment] 2023-05-08 13:39
@Beamanator I checkout to this PR https://github.com/Expensify/App/pull/18273 and is not reproduce.


https://user-images.githubusercontent.com/25520267/236838475-db07894b-aa61-43d6-9d63-017c0c668125.mov

**Comment by azimgd** [comment] 2023-05-08 13:43
@Beamanator this looks like a side-effect of listener re-subscription implemented here: https://github.com/Expensify/App/pull/18425

**Comment by Beamanator** [comment] 2023-05-08 13:43
@mollfpr thanks so much for checking there!

**Comment by Beamanator** [comment] 2023-05-08 13:44
@azimgd Thanks for looking into that! Do you want to suggest a fix for this? :D If not I will look into solving 👍

**Comment by Beamanator** [comment] 2023-05-08 13:50
@mollfpr or @mananjadhav do you have free time to test & record screenshots for ^ PR?

(@mananjadhav was auto-assigned but since this a deploy blocker I'm hoping to get this resolved quickly)

Also @azimgd thanks for the quick PR! Can you add a few more details WHY that change is needed (in the PR)? I Also added a comment about doing a few more tests for your change

**Comment by mollfpr** [comment] 2023-05-08 13:52
@Beamanator Yes, I'm quite free for this 😁

**Comment by Beamanator** [comment] 2023-05-08 13:54
Thanks @mollfpr - assigned you to the PR 👍

**Comment by aldo-expensify** [comment] 2023-05-08 17:09
Since it is the end of the day for @Beamanator , I'll take over to finish this.

**Comment by aldo-expensify** [comment] 2023-05-08 17:58
New PR up: https://github.com/Expensify/App/pull/18599

**Comment by aldo-expensify** [comment] 2023-05-08 18:01
Hmm, I see that the problem in the issue seems very similar to https://github.com/Expensify/App/issues/18419

Basically, the `BaseOptionsSelector` keep consuming events like arrow keys after you navigated to a different view because it remains open in the background.

**Comment by neil-marcellini** [comment] 2023-05-08 18:51
Does this really need to be a deploy blocker? We should probably fix it but it seems like quite an edge case issue.

**Comment by aldo-expensify** [comment] 2023-05-08 19:03
> Does this really need to be a deploy blocker? We should probably fix it but it seems like quite an edge case issue.

I'm not aware of a criteria based on being an edge case for considering something a deploy blocker or not.

I think we should just review https://github.com/Expensify/App/pull/18599 and proceed if it fixes it.

**Comment by aldo-expensify** [comment] 2023-05-08 22:41
https://github.com/Expensify/App/pull/18599 was deployed to staging in version 1.3.11-3. I confirmed that the bug is no longer there:


https://user-images.githubusercontent.com/87341702/236953113-0f03ff02-d586-4bf7-a22b-0585eec869d2.mov

Removing this as a deploy blocker.

**Comment by roryabraham** [comment] 2023-05-09 00:00
@aldo-expensify should we close this?

**Comment by aldo-expensify** [comment] 2023-05-09 15:56
> @aldo-expensify should we close this?

I didn't close it because I'm not sure if there is some compensation to be handled.

**Comment by NicMendonca** [comment] 2023-05-16 13:33
@aldo-expensify I am not sure! Can you confirm?

**Comment by mollfpr** [comment] 2023-05-16 13:38
I didn't get to review the PR, so I'm not eligible for the compensation.

**Comment by NicMendonca** [comment] 2023-05-18 16:04
Thank you for confirming that @mollfpr 🙌

**Closed by NicMendonca** 2023-05-18 16:04 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
