### ISSUE TITLE
[$1000] mWeb Android - Not able to create multiline description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22284] opened 2023-07-05 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + icon and select assign task option
2. Enter title and enter description
3. Click on :leftwards_arrow_with_hook: icon of keyboard which is in bottom right corner

## Expected Result:
Should add new line same app

## Actual Result:
 Not able to add new line
 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/763a8478-ac32-4ea2-8566-d13b079d0bf3

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688318894783959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6d942e70811c529</li>
        <li>Upwork Job ID: 1686831253824323584</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>chiragxarora | Contributor | 26157668</li>
</ul></li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-07-11 18:26
Lots of high priorities. Getting to this tomorrow

**Comment by muttmuure** [comment] 2023-07-14 14:07
Still not had time

**Comment by muttmuure** [comment] 2023-07-17 15:44
Seeing this as fixed 

https://github.com/Expensify/App/assets/46995600/6f45a638-a56e-4a99-8f0d-6a6782db06e4

Maybe we caught it somewhere else?

**Comment by muttmuure** [comment] 2023-07-17 15:47
@aimane-chnaif did we push a fix for android for this?

**Comment by muttmuure** [comment] 2023-07-19 12:11
I'm also seeing this as fixed on Android Chrome. Am I holding it wrong here? 

https://github.com/Expensify/App/assets/46995600/71f1cd8c-d2fc-4a0a-84b9-39a4cb70ad61

**Comment by gadhiyamanan** [comment] 2023-07-19 12:15
@muttmuure still able to reproduce with real device
https://github.com/Expensify/App/assets/54790231/05e35e4c-4c0b-43d5-b131-10b497a29710

**Comment by ahmedGaber93** [comment] 2023-07-20 14:14
@gadhiyamanan can you share some info about your device model and android version.

**Comment by muttmuure** [comment] 2023-07-26 06:55
Catching up from ooo

**Comment by muttmuure** [comment] 2023-07-28 17:27
Sorry, I'm not able to reproduce this. I'm going to close it for WAQ. If it comes up later and someone can reproduce it then we can reopen this one and credit the first reporter.

**Comment by muttmuure** [comment] 2023-07-31 14:13
BrowserStack says the device is real, but I will ask someone on the BZ team if they have an android

**Comment by mananjadhav** [comment] 2023-08-03 05:45
Thanks for the proposals folks. @muttmuure I am not sure why this is tagged `Internal`.

@chiragxarora I checked your proposal, but removing the `submitOnEnter` won't work as it will cause a regression [here](https://github.com/Expensify/App/issues/21205). We explicitly added the submit on enter behavior here. Can you post an updated proposal that doesn't break the other issue?

I don't have an Android device to reproduce this right now (I'll post an update in 2-3 hours), but based on my experience I am fairly confident that this  is an issue.

**Comment by mananjadhav** [comment] 2023-08-07 02:25
Thanks for the comment @chiragxarora. We can still use multiline with Shift + Enter. Let me confirm the behavior with the team. Raised a comment [here](https://github.com/Expensify/App/issues/21205#issuecomment-1667093102)

**Comment by mananjadhav** [comment] 2023-08-08 16:50
As per the [comment](https://github.com/Expensify/App/issues/21205#issuecomment-1668250551) on the other issue, we want the conditional behavior. @chiragxarora Can you update your proposal?

**Comment by mananjadhav** [comment] 2023-08-10 03:56
Yes let's just disable this for mobile.

**Comment by mananjadhav** [comment] 2023-08-10 05:27
I saw the comment  and yeah I am fine with the condition as well. We don't want to use `isSmallScreenWidth`.

**Comment by mananjadhav** [comment] 2023-08-13 11:23
I've tested this on a physical iOS device.  Submit on enter is an issue on mobile Safari like Android.

@chiragxarora's proposal looks good to me.

🎀 👀 🎀  C+ reviewed.

**Comment by mananjadhav** [comment] 2023-08-13 13:06
Should’ve mentioned works fine on native app.

**Comment by mananjadhav** [comment] 2023-08-16 17:19
@chiragxarora I commented on the PR for missing screenshots.

**Comment by mananjadhav** [comment] 2023-08-25 18:22
This was deployed to production 2 days back, but the title wasn't updated.

**Comment by mananjadhav** [comment] 2023-08-31 13:52
@muttmuure Can you post the payout summary here? This has been in production for 7 days but the title wasn't updated.

**Comment by mananjadhav** [comment] 2023-09-03 20:14
I would call this as small polish/feature request. We linked the other issue, and the comment says it was expected change. I also don't think we need a regression test here.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:14
Waiting on payment summary for NewDot payment.

**Comment by muttmuure** [comment] 2023-09-11 13:59
Reporter - @gadhiyamanan $250
C - @chiragxarora $1500
C+ - @mananjadhav $1500

**Comment by muttmuure** [comment] 2023-09-19 01:51
offer sent!

**Comment by gadhiyamanan** [comment] 2023-09-19 02:31
@muttmuure i didn't get any offer

**Comment by muttmuure** [comment] 2023-09-19 03:05
Sent one to you too @gadhiyamanan

**Comment by gadhiyamanan** [comment] 2023-09-19 03:06
@muttmuure offer accepted, thanks!

**Comment by muttmuure** [comment] 2023-09-19 03:25
All paid up

**Closed by muttmuure** 2023-09-19 03:25 UTC
Labels: Reviewing, External, Engineering, Weekly, Needs Reproduction, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 09:13
$1,500 payment approved for @mananjadhav based on BZ summary above.
