### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250] Android & iOS - Expensify Card - Previous data is not cleared when issuing new card

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53375] opened 2024-12-02 11:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/5285123
**Email or phone of affected tester (no customers):** applausetester+khcategory18@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Expensify Card is set up.

Issue 1:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Tap on any member.
4. Tap New card.
5. Go through card issue flow and remember all the details.
6. After issuing the card, tap New card to issue another card.
7. Go through the card issue flow.
8. Note that the previous data entered in Step 5 is preserved and not reset.

Issue 2:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Tap Issue card.
4. Go through card issue flow.
5. After issuing the card, tap Issue card to issue another card.
6. Note that app shows the confirmation page from the previous card assignment instead of starting the flow with Step 1.

## Expected Result:
When starting another card issue flow after issuing a card, the previous data will be cleared (production behavior).

## Actual Result:
When starting another card issue flow after issuing a card, the previous data is preserved.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4582ba10-6697-48e5-9560-49aa66b529fa

https://github.com/user-attachments/assets/3acadcb3-bd8b-4f64-89b2-93edb68b70d8

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863614110562904926</li>
        <li>Upwork Job ID: 1863614110562904926</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by koko57** [comment] 2024-12-02 11:08
I can take a look

**Comment by Julesssss** [comment] 2024-12-02 11:30
Ah, thanks Vit. I will unsub

**Comment by koko57** [comment] 2024-12-02 11:52
@allgandalf I tested on web while my ios app is building - I cannot repro the first issue - after successfully issuing a card while I'm going through the flow I need to provide the new data BUT of course on Step 5 I will get the same value when issuing a physical card again - because we always default to "User's card"

but I wonder if it's only the mobile issue? TBH it should work the same

**Comment by koko57** [comment] 2024-12-02 11:55
yet still there weren't any changes applied (that I'm at least aware of) that could cause such problem.

**Comment by koko57** [comment] 2024-12-02 11:57
Ok, I was able to reproduce it. Digging now

**Comment by koko57** [comment] 2024-12-02 14:40
Straaange, bc we are clearing the data from Onyx

- is there anything I don't see in these logs?

<img width="1400" alt="Screenshot 2024-12-02 at 17 57 55" src="https://github.com/user-attachments/assets/94a9e1ca-4366-4533-9675-90c714acb628">

**Comment by mountiny** [comment] 2024-12-02 15:59
I have demoted as the users are not blocked from adding cards, adding to the expense projectš and exporting

**Comment by koko57** [comment] 2024-12-04 07:52
I'm back I can continue working on that

**Comment by mountiny** [comment] 2024-12-04 12:23
thanks!

**Comment by koko57** [comment] 2024-12-04 16:15
craaaazy - when I add this to success data for issueExpensifyCard
<img width="481" alt="Screenshot 2024-12-04 at 17 12 33" src="https://github.com/user-attachments/assets/4e7d4f12-5460-4d23-b215-db8a035f65b4"> 
after the request is sent and we get the response - the confirmation step is displayed and the data is still there 😱 something's very very strange here, I will continue digging

**Comment by koko57** [comment] 2024-12-04 16:24
btw I've noticed that the Verify Magicode Modal's submit button is a little bit higher than the submit button of each step of the flow (I think they should be in the same position, shouldn't they?)
![Simulator Screenshot - iPhone 15 Pro - 2024-12-04 at 17 17 35](https://github.com/user-attachments/assets/c280a234-c8ab-4b8c-8f56-e36b3e5814c3)
![Simulator Screenshot - iPhone 15 Pro - 2024-12-04 at 17 17 32](https://github.com/user-attachments/assets/0a99ce6d-6cb5-407e-be01-118be5f4cc38)

@mountiny I've search through the issues but I haven't found any like this - maybe we can create a new one? I don't want to fix it here as it's necessary to check how it's aligned with the other flows that this modal is used in and maybe if it's necessary make it consistent everywhere.

cc @shawnborton @dubielzyk-expensify

**Comment by shawnborton** [comment] 2024-12-04 16:38
> I think they should be in the same position, shouldn't they?

Agree, they should be identical.

**Comment by mountiny** [comment] 2024-12-04 17:44
Yeah that will be from the edge-to-edge feature enablement cc @kirillzyusko

**Comment by mountiny** [comment] 2024-12-04 17:49
Created an issue for that to keep the concerns separated https://github.com/Expensify/App/issues/53583

**Comment by ikevin127** [comment] 2024-12-04 18:40
I looked into this briefly when it still had the `Help Wanted` label and here's what I found:

- I think the issue might have something to do with the fact that for some reason, on native devices, the `IssueNewCardPage` and some of the steps seem to mount multiple times as one goes through each step
- after adding a card and being navigated back to the cards list, when clicking `New card` which opens a modal with the steps -> some of the steps are still mounted from the previous instance, causing old data to be pushed to onyx again

What I found unusual is that I noticed we call `Card.clearIssueNewCardFlow()` in 3 different places which still does not seem to clear the data (this issue) as intended:

- in `IssueNewCardPage` only on unmount:

https://github.com/Expensify/App/blob/f3a128d30097926b0305d7a84580f6d39daaa5c4/src/pages/workspace/expensifyCard/issueNew/IssueNewCardPage.tsx#L33-L37

- on `AssigneeStep` in `handleBackButtonPress`:

https://github.com/Expensify/App/blob/f3a128d30097926b0305d7a84580f6d39daaa5c4/src/pages/workspace/expensifyCard/issueNew/AssigneeStep.tsx#L59-L66

- on `ConfirmationStep` when `isSuccessful` is true and after calling navigate back to cards list:

https://github.com/Expensify/App/blob/f3a128d30097926b0305d7a84580f6d39daaa5c4/src/pages/workspace/expensifyCard/issueNew/ConfirmationStep.tsx#L56-L62

##

A solution that worked in fixing the issue was to add `Card.clearIssueNewCardFlow()` in `IssueNewCardPage` once **when the component mounts** - while this solution fixes the issue, as mentioned above I think there are deeper issues with the flow that need to be addressed regarding mount / unmount behaviour and multiple calls of `Card.clearIssueNewCardFlow()`.

Hope this helps in fixing the issue.

**Comment by koko57** [comment] 2024-12-05 11:20
Thanks for the hint, I will check it out!

**Comment by koko57** [comment] 2024-12-05 19:40
I cannot confirm this
> the IssueNewCardPage and some of the steps seem to mount multiple times as one goes through each step
@ikevin127 how were you able to find out that?

> A solution that worked in fixing the issue was to add Card.clearIssueNewCardFlow() in IssueNewCardPage once when the component mounts 

this one works, but unfortunately it breaks the flow from the member's page - skipping Assignee Step with assignee already assigned - we land on the Assignee Step.

**Comment by ikevin127** [comment] 2024-12-05 20:02
> skipping Assignee Step with assignee already assigned

This could be fixed with checking if Assignee exists and clearing all data except Assignee such that it would go to the next step and not break that flow.

**Comment by koko57** [comment] 2024-12-09 11:09
nope - I wish it was that easy - issueNewCard is undefined when IssueNewCardPage is mounting, then somehow the data kicks back in

**Comment by koko57** [comment] 2024-12-10 12:08
no, it still doesn't work like intended, but I've just found something that might be the root cause of the problem, so maybe we won't need such a workaround

**Comment by koko57** [comment] 2024-12-10 12:39
looks like clearIssueNewCardError runs after clearIssueNewCardFlow and as we pass issueNewCard from the confirmation step as an argument and it's used to set the new issueNewCard object we end up with the old object in the new flow

**Comment by koko57** [comment] 2024-12-10 14:31
I've also found that we've running the clear errors function twice unnecessarily twice. Will fix it as well in my PR

**Comment by koko57** [comment] 2024-12-11 08:37
In my draft I removed all the other instances where clearIssueNewCardFlow is triggered, I've left only the one in the IssueNewCardPage useEffect return function, but something is still off. Looks like we should stay with clearing the issueNewCard in these 3 places instead of the useEffect. I need to check why it behaves this way and then I will make some appropriate changes to make my PR ready for the review

**Comment by koko57** [comment] 2024-12-12 13:59
opening my PR for the review - the current solution works fine https://github.com/Expensify/App/pull/53867

**Comment by jliexpensify** [comment] 2024-12-30 02:27
Kadie is OOO so I'll take care of checklist and payment

**Comment by jliexpensify** [comment] 2024-12-30 02:30
Whoops didn't realise there was already a job created.

Payment Summary

- C+: @allgandalf $250 (to be paid via Upworks)

https://www.upwork.com/jobs/~021863614110562904926

**Comment by jliexpensify** [comment] 2024-12-30 09:31
Bump @allgandalf to accept the offer please

**Comment by jliexpensify** [comment] 2024-12-30 10:08
Paid and job closed!

**Closed by jliexpensify** 2024-12-30 10:08 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
