### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] mWeb/Safari- Chat - Focus is in the start of the message when opening a report with a draft message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31708] opened 2023-11-22 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:** https://github.com/Expensify/App/pull/31295

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open any chat and enter a message without sending it
2. Go back to LHN and open the same chat

## Expected Result:
The focus is on the end of the message so user can continue typing

## Actual Result:
The focus is on the start of the message. User needs to manually move the cursor to the end to continue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/223ba67f-7e1e-473c-a324-3dadc7b9073d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc3a996f2399bc80</li>
        <li>Upwork Job ID: 1727336945085743104</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27867013</li>
</ul></li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-22 15:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

For mobile Safari, when a draft message is opened, the cursor is at the beginning of the message instead of the end.

### What is the root cause of that problem?

We're only setting selection for mobile Safari if `shouldAutoFocus` is true, but we're not using `shouldAutoFocus` to set focus, we're intentionally setting it to false.

### What changes do you think we should make in order to solve the problem?

We should set the selection for mobile Safari regardless of whether we're autofocusing - setting selection on initial load won't have an impact if we're not focusing the composer. It's unnecessary dependency.

**Comment by conorpendergrast** [comment] 2023-11-23 16:39
I have reproduced on iOS, in Safari 👍

**Comment by burczu** [comment] 2023-11-27 13:25
Not overdue, I'll be reviewing this issue soon.

**Comment by burczu** [comment] 2023-11-28 09:55
First of all, I've checked how this works on Android mWeb and it does not focus the input when we get back to the chat that is in edit mode, so I think this is the expected behaviour of this issue (not putting the cursor at the end, just not focusing the input at all).

That being said, [the solution](https://github.com/Expensify/App/issues/31708#issuecomment-1823197048) from @bernhardoj solves the issue this way and make the app on iOS and Android mWeb working consistently, so I believe we should proceed with it.

[The solution](https://github.com/Expensify/App/issues/31708#issuecomment-1823020227) from @erquhart indeed moves the cursor at the end, but it does not change the behaviour on Android so the outcome is inconsistent on both devices.

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment] 2023-11-28 16:31
This sounds good to me! That conditional (`!(Browser.isMobileSafari() && !shouldAutoFocus);`)is a bit confusing to parse through so please add a comment there. Will assign you now!

**Comment by burczu** [comment] 2023-12-11 09:42
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:

**https://github.com/Expensify/App/pull/21371**

* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

**https://github.com/Expensify/App/pull/21371#discussion_r1422189723**

* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**n/a**

* [x]  [@burczu] Determine if we should create a regression test for this bug.

**I'm not sure about regression test here - it doesn't block the App from being usable, it was just small inconvenience only in one of the environments we support.**

* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@conorpendergrast] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by conorpendergrast** [comment] 2023-12-12 20:49
@burczu This was a bug identified by Applause, so we likely don't need a new regression test. Thanks!

**Comment by conorpendergrast** [comment] 2023-12-12 20:54
Payouts due:

- [x] Contributor: $500 @bernhardoj - [contract](https://www.upwork.com/nx/wm/workroom/35602510/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01fc3a996f2399bc80).

**Comment by conorpendergrast** [comment] 2023-12-12 20:54
All done, thanks everyone

**Closed by conorpendergrast** 2023-12-12 20:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
