### ISSUE TITLE
[$500] Bank account - On selecting "I accept expensify terms", error not displayed for "Account number"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35345] opened 2024-01-30 00:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4251914
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap workspaces--- Workspace
4. Tap Bank Account
5. Tap Connect manually
6. Select "I accept expensify terms"

## Expected Result:
When user select "I accept expensify terms", error must be displayed for both "Routing number" & "Account number" 

## Actual Result:
Error displayed for "Routing number" but not shown for "Account number" when user select "I accept expensify terms".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cb3c8d6c-beb9-47e3-b651-e4d538f54300

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019df4e12cd288976c</li>
        <li>Upwork Job ID: 1752123886122000384</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-30 01:43
We only show errors for fields that are touched, since the first one is focused it's marked as touched.

The account number is never touched so it won't show the error yet.

**Comment by joekaufmanexpensify** [comment] 2024-01-30 14:45
Agreed. This is not a bug.

**Closed by joekaufmanexpensify** 2024-01-30 14:45 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by joekaufmanexpensify** [comment] 2024-01-30 15:38
Hm, but if the user clicks out of the routing number field, we will still show an error there, no?

**Comment by joekaufmanexpensify** [comment] 2024-01-30 16:34
Hm, personally I think this is fine and not worth changing anything now.

**Comment by jeremy-croff** [comment] 2024-01-30 19:32
> > Hm, but if the user clicks out of the routing number field, we will still show an error there, no?
> 
> @joekaufmanexpensify Yes, if the user proactively blurs the routing number field, it will still show an error and blur the routing number input.
> 
> But on native Android/iOS if we toggle the checkbox, the input won't be blurred and no error will show, I think that makes more sense (allowing the users to continue to type on the inputs right after the user toggles the checkbox, less manual action from user) and we should do the same for mWeb/web.

Based on what you shared I actually think native has a bug to not trigger the validation. 
If they follow the order of the list as we present it to the user: 
1. fill out account number 
2. tap Routing, and account number gets validated
3. fill out routing number incorrectly
3. tap 'i accept term'
here it should validate the routing number
So that I can be informed of whether or not I can 'Continue'

**Comment by joekaufmanexpensify** [comment] 2024-01-31 16:07
I'm not sure I understand the report. If you follow the 4 steps you listed above we do throw an incorrect routing number error.

**Comment by jeremy-croff** [comment] 2024-02-01 03:07
> I'm not sure I understand the report. If you follow the 4 steps you listed above we do throw an incorrect routing number error.

The report is describing how I think it should be behaving, which is how web is handling!

However if you look at the video from https://github.com/Expensify/App/issues/35345#issuecomment-1917227581 they actually demonstrate this being broken in native. Since clicking I accept does not trigger validation.
