### ISSUE TITLE
Resend link button doesn't have any feedback

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20541] opened 2023-06-09 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on Profile > contact method > new contact method
3. Add an email/phone number
4. Click on the newly added email/phone number
  5. Click on the `resend magic code`
## Expected Result: 
Link opacity should decrease on long press or press/click
## Actual Result: 
There is no feedback

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a99f5faa-39c8-45af-8539-cb4ec276285c

https://github.com/Expensify/App/assets/43996225/d25d59a9-05ef-461a-9275-712a62fd191e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685992553732829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-10 03:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Resend magic code button in verify contact method page does not have press/click feedback.

### What is the root cause of that problem?
We are using a plain text showing the Resend magic code with no styling on pressing/clicking.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L141-L146

### What changes do you think we should make in order to solve the problem?

Do what we do in sign in code input, that is wrap the text with PressableWithFeedback. We can control the `hoverDimmingValue` and `pressDimmingValue`.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L242-L253

I think we can follow the same value for the dimming. Also, notice that we are disabling the button if offline. I think we should have the same behavior.

**Comment by alitoshmatov** [comment] 2023-06-12 10:59
I think this is going to be solved in https://github.com/Expensify/App/pull/19409

**Comment by trjExpensify** [comment] 2023-06-12 14:33
Cool, good to know it seems to be known. @rushatgabhane can I get a second opinion on this being the same root cause wrt to PressableWithFeedback before I close this out.

**Closed** 2023-06-13 13:15 UTC
Labels: Daily, Bug
