### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Task - Task assignee profile opens when clicking on the header of task report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30182] opened 2023-10-23 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat > + > Assign task
3. Create a task with no assignee
4. On the task report, click on the report header
5. Verify that the task details page shows up
6. Repeat Step 1 to 3 with task with an assignee

## Expected Result:
Task details modal opens when clicking on the report header of the task with assignee

## Actual Result:
Task assignee profile opens instead of task details modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/98ecb578-86dc-4389-b749-e6396d338137

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01852a4aad8299505f</li>
        <li>Upwork Job ID: 1716479601614000128</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-10-23 15:49
I am able to repro this.

**Comment by FitseTLT** [comment] 2023-10-23 16:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task assignee profile opens when clicking on task report header
### What is the root cause of that problem?
Because of this line:
https://github.com/Expensify/App/blob/844b3b96b5bcd80c5c7bd376648a921939e25d10/src/libs/ReportUtils.js#L2074-L2077
It navigates to participant or assignee detail when the task has an assignee
### What changes do you think we should make in order to solve the problem?

We should change those line to display the task detail whether there is participant( assignee) is there or not
### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-10-24 04:43
@FitseTLT @alitoshmatov Thank you for your proposals.
Both have very similar proposals but need more reasoning in their RCA.
Can you both elaborate on why this happens when we only assign during creating a task but not on the task after we assign an assignee where we have no assignee while creating the task?

**Comment by alitoshmatov** [comment] 2023-10-24 05:28
@shubham1206agra Looks like there is another issue with updating assignee of the task. 
https://github.com/Expensify/App/blob/9945d3c10ae2a6b51e1758ec56fdf6860bc90f30/src/libs/actions/Task.js#L469
In `editTaskAssigneeAndNavigate` we are not updating `participantAccountIDs` with optimistic data, But we updating it when creating new task
https://github.com/Expensify/App/blob/ceb319fc92f4d2984469f6cac6aa0d01cbaf75fa/src/libs/ReportUtils.js#L3027

Thus when we edit task assignee this field is not getting updated resulting in the above error. Also this is causing issue where when we create a task with a assignee and then change assignee, clicking on the header results in showing wrong assignee(below video)

https://github.com/Expensify/App/assets/59907218/6b86bb48-ffc2-4a2f-a483-3a1f8e5585a3

**Comment by FitseTLT** [comment] 2023-10-24 07:18
> @FitseTLT @alitoshmatov Thank you for your proposals. Both have very similar proposals but need more reasoning in their RCA. Can you both elaborate on why this happens when we only assign during creating a task but not on the task where we have no assignee while creating the task? And please also post a video too

https://github.com/Expensify/App/blob/844b3b96b5bcd80c5c7bd376648a921939e25d10/src/libs/ReportUtils.js#L2071-L2079

Ok @shubham1206agra as you can see above in the code when there is no assignee or even if you assigned yourself on the task `participantAccountIDs.length === 1` will be false so the details page of the task report will be navigated but when there is an assignee (not the creator of the task) `participantAccountIDs.length === 1` will be true and it will navigate to the participants or assignee detail page. Also tried to include a debugging video. Thanks!

https://github.com/Expensify/App/assets/38649957/2330272f-85e4-4c33-9da5-f2301fbddf7a

**Comment by shubham1206agra** [comment] 2023-10-25 16:20
@bernhardoj Can you put a video to confirm your solution works in every case?

**Comment by shubham1206agra** [comment] 2023-10-26 06:08
Since @bernhardoj's [proposal](https://github.com/Expensify/App/issues/30182#issuecomment-1776559324) came first after my comment for detailed RCA and it fixes more wide problems.

Let's go with this proposal then.

🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment] 2023-10-30 23:51
@shubham1206agra - bumping, can you please review this PR? Thanks!

**Comment by alexpensify** [comment] 2023-11-01 18:45
Looks like the PR is merged, waiting for automation here.

**Comment by alexpensify** [comment] 2023-11-03 16:29
@shubham1206agra -  to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by alexpensify** [comment] 2023-11-06 23:46
@shubham1206agra bumping again, I'm trying to get ready for the payment date. Thanks!

**Comment by shubham1206agra** [comment] 2023-11-07 02:07
**BugZero Checklist:**

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28200

* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28200/files#r1384260896

* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required as this is an edge case

* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. Not required as this is an edge case

* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by alexpensify** [comment] 2023-11-09 00:30
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @bernhardoj $500 + $250
-  Contributor+ that helped on the issue and/or PR - @shubham1206agra $500 + $250 

Upwork Job: https://www.upwork.com/jobs/~01852a4aad8299505f

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment:  This one was before the pre-urgency bonus change, and was merged in 3 business days.

**Comment by alexpensify** [comment] 2023-11-09 00:30
@bernhardoj and @shubham1206agra - can you please apply to the job here: 

https://www.upwork.com/jobs/~01852a4aad8299505f

It looks like the automation didn't assign it to you. Thanks, I'll complete the required steps tomorrow.

**Comment by alexpensify** [comment] 2023-11-09 17:20
@bernhardoj and @shubham1206agra - I've started the process in Upwork. Please accept and I can apply the bonuses and close this GH. Thanks!

**Comment by alexpensify** [comment] 2023-11-09 17:32
After reviewing the payment summary again, I confirmed with the team that the PR for this one was created after the announcement (on October 24) related to the discontinuation of the urgency bonus. The conversation is here:

https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379

My apology for not catching this sooner, but the base payment will remain the same.

**Comment by alexpensify** [comment] 2023-11-09 23:03
@shubham1206agra has been paid in Upwork. @bernhardoj needs to accept and then we can pay in Upwork. Thanks!

**Comment by alexpensify** [comment] 2023-11-10 05:46
Perfect, everyone has been paid via Upwork! Great work!

**Closed by alexpensify** 2023-11-10 05:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
