### ISSUE TITLE
[$500] IOU - No way to dismiss IOU report with RBR from LHN when paying deleted request offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39315] opened 2024-03-30 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4463293
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Request money from User B
3. [User B] Go to 1:1 DM with User A and click on IOU preview to go to IOU report
4. [User B] Go offline
5. [User B] Pay elsewhere the report and stay in IOU report
6. [User A] Delete the IOU request
7. [User B] Go online
8/ [User B] After not here page shows up, navigate to a different chat

## Expected Result:
The IOU report with RBR should dismiss from LHN

## Actual Result:
The IOU report with RBR does not dismiss from LHN. There is no way to dismiss the RBR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e990f24f-0247-4990-b4e8-52201ba5a999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cc4c27732f8c447</li>
        <li>Upwork Job ID: 1775336903837138944</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-30 16:27
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-03-30 16:27
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-04-03 07:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The IOU report with RBR does not dismiss from LHN. There is no way to dismiss the RBR

### What is the root cause of that problem?
When User B paid the IOU and goes online, the back-end will return `errorFields.notFound` on the report in Onyx, because the IOU was already deleted by User A

This is a known case, we can see that [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/home/ReportScreen.tsx#L291), we will show not found page specifically in the case of `errorFields.notFound` here, but we didn't have any logic to clear the `notFound` report after leaving the screen, so the report and it's RBR will be stuck there.

### What changes do you think we should make in order to solve the problem?

Add logic to clear the `notFound`/inaccessible report after leaving the screen, so the report and it's RBR will be stuck there.

Pseudocode (to be added [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/home/ReportScreen.tsx#L306)):
```
useEffect(() => {
    if (prevIsFocused && !isFocused && report.reportID && shouldHideReport) {
        Report.deleteReport(report.reportID);
    }
}, [isFocused, report?.reportID, shouldHideReport]);
```

`shouldHideReport` here means that the report is not accessible, and has no `helpfulErrors` (see [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/home/ReportScreen.tsx#L293) for more info)

We can optionally further improve the logic to:
- `deleteReport` only if the user switched to a new report (by making use of `isTopMostReportId`), that means if the user opens settings page and the errored report loses focus, the report will not be deleted
- After deleting the report, make sure to purge the errored report screen from the route, so that it could not be "go back" to from another report.

### What alternative solutions did you explore? (Optional)
NA

**Comment by kadiealexander** [comment] 2024-04-04 22:04
@DylanDylann bump!

**Comment by DylanDylann** [comment] 2024-04-05 10:57
@nkdengineer After deleting the request in the second device, the screen is navigated to the main report and the IOU report with a red dot appears after a moment. I think the error report shouldn't appear in this case. Could you check again and update the proposal

https://github.com/Expensify/App/assets/141406735/ab123e91-9452-4f68-91a8-b5518cca4f75

**Comment by kadiealexander** [comment] 2024-04-09 05:31
@nkdengineer did you have any thoughts on the feedback above?

**Comment by nkdengineer** [comment] 2024-04-10 04:23
@kadiealexander @DylanDylann  I'll give an update in 24h, thanks 🙏

**Comment by nkdengineer** [comment] 2024-04-11 16:55
It seems the behavior here has changed, I'll need some more time to check, I'll do tomorrow.

Thanks for the patience!

**Comment by kadiealexander** [comment] 2024-04-12 05:01
Not overdue, still looking for proposals!

**Comment by kadiealexander** [comment] 2024-04-15 04:34
@nkdengineer any thoughts on an updated proposal?

**Comment by nkdengineer** [comment] 2024-04-17 11:49
Sorry I haven't been able to get back to this, I will try to give an update tomorrow.

**Comment by kadiealexander** [comment] 2024-04-18 04:14
Not overdue, please get your proposals in! 📣

**Comment by DylanDylann** [comment] 2024-04-22 00:02
@nkdengineer Any update here? Could you reproduce anymore?

**Comment by kadiealexander** [comment] 2024-04-23 06:03
@mvtglobally confirmed this is no longer reproducible. Closing, please reopen if you still experience the issue.

**Closed by kadiealexander** 2024-04-23 06:03 UTC
Labels: External, Daily, Help Wanted, Bug
