### ISSUE TITLE
[$250] Chat - 1:1 DM refreshes itself, composer + action menu closes

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44498] opened 2024-06-26 19:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Bug was found when validating #43307
**Version Number:** 9.0.2-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Tap on FAB - Start chat
4. Enter a Gmail address that doesn't have an account yet
5. Tap on the account
6. Tap on the "+" button next to the composer

## Expected Result:
I should be able to use the + menu and the chat shouldn't refresh itself.

## Actual Result:
Chat - 1:1 DM resreshes itself for a few times after opening. Composer + action menu closes and the chat starts refreshing again. The menu is inaccessible.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b542b503-c1b0-4975-8461-70e16dcec978

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129f8c701589e31b8</li>
        <li>Upwork Job ID: 1806096676893409978</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by m-natarajan** [comment] 2024-06-26 19:32
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-26 19:32
We think that this bug might be related to  #vip-vsb

**Comment by Christinadobrzyn** [comment] 2024-06-26 19:44
@arosiclair @roryabraham @c3024 - can you double-check if this relates to https://github.com/Expensify/App/pull/43307

**Comment by Christinadobrzyn** [comment] 2024-06-26 22:08
I'm able to reproduce the bug in the OP

https://github.com/Expensify/App/assets/51066321/135118f6-58f3-4430-b552-e9757db0c364

**Comment by pecanoro** [comment] 2024-06-27 14:02
I am not sure if it's the same RCA, but I am getting something similar and I can't send any messages at all: https://expensify.slack.com/archives/C049HHMV9SM/p1719413599651529

**Comment by Christinadobrzyn** [comment] 2024-06-27 14:28
Asking if this is the same as https://github.com/Expensify/App/issues/44419

**Comment by arosiclair** [comment] 2024-06-27 14:31
Looks like we're fixing this here: https://github.com/Expensify/App/pull/44544

**Comment by mountiny** [comment] 2024-06-27 15:33
confirmed its fixed by https://github.com/Expensify/App/pull/44544 gonna add it to the list of issue it fixes

**Comment by mountiny** [comment] 2024-06-27 17:00
CPed to staging, confirmed this is fixed 🎉 

https://github.com/Expensify/App/assets/36083550/9a21c6d9-586e-49d9-85b1-d469329f708e

**Comment by mountiny** [comment] 2024-06-27 17:00
We will handle C+ payment on the other linked issue, we can close this one now

**Closed by mountiny** 2024-06-27 17:00 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
