### ISSUE TITLE
 IOU - Currency display inconsistency for IOU created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14841] opened 2023-02-05 03:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot, login
2. Go offline
3. Request 500 in MXN currency
4. Go online (refresh the page if necessary)

## Expected Result:
Currency should be displayed in the same way while offline and online

## Actual Result:
When offline currency and amount are displayed as "500 MXN", but when back online they are displayed as "MX$500"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.65.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/216799536-a992a37b-7e1f-49d7-931a-b45f11cc2f46.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2023-02-08 18:12
so far ive not been able to reproduce this.

**Comment by maddylewis** [comment] 2023-02-13 13:29
sounds like this is reproducible for others - https://expensify.slack.com/archives/C049HHMV9SM/p1676290180115709?thread_ts=1674645382.555109&cid=C049HHMV9SM

**Comment by maddylewis** [comment] 2023-02-14 19:24
asked if this is worth fixing here - https://expensify.slack.com/archives/C049HHMV9SM/p1676390641405659

**Comment by maddylewis** [comment] 2023-02-14 20:51
confirmed this is not a bug. closing!

**Closed by maddylewis** 2023-02-14 20:51 UTC
Labels: Daily, Bug
