### ISSUE TITLE
[$250] Feature request - Show content when open deep link from other user profile which is not in contacts list reported by @aimane-chnaif 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11922] opened 2022-10-17 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
It shows loading forever. Especially, when someone shares user profile link from other social app and open it, user gets confused.

## Solution: 
The page should show content. i.e. no access page, 404 page, or show "not in contacts" message and create new chat button, etc. At least should show close button to exit this page and go back to home screen.

## Context/Examples/Screenshots/Notes: 

https://user-images.githubusercontent.com/43996225/196248925-da8b0e72-4adf-43d9-9bc2-0953c92dabde.mp4

Platform:
Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web
Logs: https://stackoverflow.com/c/expensify/questions/4856
Expensify/Expensify Issue URL: 
Issue reported by: @aimane-chnaif 
Slack conversation: https://expensify.slack.com/archives/C01GTK53T8Q/p1666005837666169
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2022-10-17 19:47
I'm not super clear on what kind of links cause this problem. Adding eng for a second pair of eyes.

**Comment by alex-mechler** [comment] 2022-10-17 22:52
Are there any logs errors when this happens? Its possible that this is a bug and not a new feature

**Comment by alex-mechler** [comment] 2022-10-18 18:50
Looks like there is no console errors from my limited testing. Seems useful that we would show / do anything other than an infinite loader here, but I'm not sure what yet. Doing some more digging / exploring before continuing

**Comment by alex-mechler** [comment] 2022-10-18 23:37
Okay, after digging in more, properly loading the details for the user in this case would be quite a large amount of internal API work, so lets stick with showing an error growl and closing the modal. 

Sending this external

**Comment by ntrepanier** [comment] 2022-10-19 16:51
Based on what @alex-mechler said above. I agree that this isn't really worth fixing at this point. As it's a feature request and not a bug, I'm going to go ahead and close it. Feel free to re-open if you disagree.

**Comment by stitesExpensify** [comment] 2022-11-07 15:25
@aimane-chnaif it actually looks like this issue is _not_ fixed by that PR. The app actually breaks instead of an endless loading spinner if the user has no details whatsoever (including no email/login) 😅 

<img width="1727" alt="2022-11-07_08-23-54" src="https://user-images.githubusercontent.com/42391420/200347864-812291a0-4f46-4f6c-800c-4c646b17b530.png">

**Comment by stitesExpensify** [comment] 2022-11-11 21:50
Thank you for bringing this up @aimane-chnaif after re-looking at this, I agree that you should get the reporting bonus since this issue was created before the one that I fixed in my PR. 

@michaelhaxhiu can you create an upwork so that we can hire and pay @aimane-chnaif the reporting fee, and then close this issue back out?

**Comment by michaelhaxhiu** [comment] 2022-11-14 18:21
https://www.upwork.com/jobs/~01cd49405208836adb

invited you @aimane-chnaif. Let's pay and close today if possible :)

**Comment by michaelhaxhiu** [comment] 2022-11-16 13:50
Hired, waiting on confirmation and then I'll pay it.

**Comment by michaelhaxhiu** [comment] 2022-11-18 18:49
Paid and closing.

**Closed by michaelhaxhiu** 2022-11-18 18:49 UTC
Labels: External, Engineering, Daily, NewFeature, Help Wanted
