### ISSUE TITLE
[HOLD for payment 2024-09-25] [$250] Contact Method - Magic code doesn't arrive unless user requests again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43359] opened 2024-06-10 12:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** berhanesarah.testing+ftu@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging as a new user
2. Go to profile settings-->Contact Methods
3. Wait for the magic code to arrive

## Expected Result:
Magic code is sent to the email

## Actual Result:
Magic code is not sent to the email unless the user clicks "Didn't receive a magic code?"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c0ede88-1b11-4337-9c35-90ff0eab2fcc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107ec935581e086f0</li>
        <li>Upwork Job ID: 1800154329461508272</li>
        <li>Last Price Increase: 2024-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 103693808</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by mountiny** [comment] 2024-06-10 13:13
Marking as external so we might get help from contributors sooner

**Comment by TheGithubDev** [comment] 2024-06-10 16:34
Contributor details
Your Expensify account email: thecoolrayyan@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~0184d64a438e2e09d2

**Comment by luacmartins** [comment] 2024-06-10 17:36
I wasn't able to reproduce this in staging. Adding a new contact method sent me the email.

**Comment by luacmartins** [comment] 2024-06-10 17:36
Gonna demote to NAB

**Comment by allroundexperts** [comment] 2024-06-12 08:38
@lanitochka17 Is this still happening? Seems to be fixed for me as well.

**Comment by lanitochka17** [comment] 2024-06-12 17:39
Issue is still reproducible 

https://github.com/Expensify/App/assets/78819774/93e2a4ca-8f00-49aa-8c26-2757af1f0d3b

**Comment by grgia** [comment] 2024-06-18 11:17
@lanitochka17 is this still occurring on staging?

**Comment by grgia** [comment] 2024-06-19 10:35
Closing for now as I cannot reproduce

**Comment by lanitochka17** [comment] 2024-08-21 16:00
Issue is still reproducible on the latest build 9.0.23-0

https://github.com/user-attachments/assets/07120aa2-f4c2-4e98-81ec-3a283c2878bf

**Comment by wildan-m** [comment] 2024-08-22 09:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Magic code will not be sent unless the user requests it again.

### What is the root cause of that problem?

We are not sending any request code unless it's manually pressed

### What changes do you think we should make in order to solve the problem?
Modify [this useEffect](https://github.com/Expensify/App/blob/50de692ff915d7998bff3fb0d024446b59912b52/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.tsx#L134-L140) to call `User.requestContactMethodValidateCode` when `validatedDate` empty and `validateCodeSent` is false.

src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.tsx
```tsx
    useEffect(() => {
        if (isEmptyObject(loginData)) {
            return;
        }

        User.resetContactMethodValidateCodeSentState(contactMethod);

        // initialCodeValidateRequestedRef is required to prevent duplicate calls in React strict mode 
        if (!loginData?.validatedDate && !loginData?.validateCodeSent && !initialCodeValidateRequestedRef.current) {
            User.requestContactMethodValidateCode(contactMethod);
            initialCodeValidateRequestedRef.current = true;
            return;
        }
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, []);
```

To prevent the "linkHasBeenResent" text from appearing on the initial page load, we can add a new state called "validateCodeSentIsPressed" to display the message only after the resent link has been pressed at least once.

src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.tsx
```tsx
                        <Text style={[StyleUtils.getDisabledLinkStyles(shouldDisableResendValidateCode)]}>{translate('validateCodeForm.magicCodeNotReceived')}</Text>
                    </PressableWithFeedback>
                    {hasMagicCodeBeenSent && validateCodeSentIsPressed && (
                        <DotIndicatorMessage
                            type="success"
                            style={[styles.mt6, styles.flex0]}
```
[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/43359-code-not-send-on-contact?expand=1)

### What alternative solutions did you explore? (Optional)
If we want to keep the user to trigger the validationCode manually, we can add new screen that contain the send validation button or at least change `Didn't receive a magic code?` to something `Send magic code` and replace the text to `Didn't receive a magic code?` when the button pressed at least once

**Comment by mountiny** [comment] 2024-08-26 23:06
@allroundexperts @wildan-m Why can we not make the api request when user clicks the button that navigates them? it feels like a better spot for this api call than the useEffect. But both work

**Comment by wildan-m** [comment] 2024-08-27 02:46
@mountiny I think that's better approach.

My [proposal updated](https://github.com/Expensify/App/issues/43359#issuecomment-2304159073)
I've added it as my 2nd alternative

@allroundexperts I will create the PR with that solution. Let me know if we still want to use the useEffect approach.

**Comment by wildan-m** [comment] 2024-08-27 04:49
@allroundexperts The PR is ready for review. https://github.com/Expensify/App/pull/48047

**Comment by mountiny** [comment] 2024-09-21 07:54
$250 to @wildan-m and to @allroundexperts

**Comment by mountiny** [comment] 2024-09-21 07:55
cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-09-23 02:57
Payment summary:

Contributor: @wildan-m - $250 - will be paid via Upwork on 9/25
C+: @allroundexperts - $250 - can make a manual request via ND on 9/25

**Comment by greg-schroeder** [comment] 2024-09-25 02:33
This isn't overdue

**Comment by mountiny** [comment] 2024-09-25 09:51
@wildan-m @allroundexperts have you been paid? Can we close?

**Comment by allroundexperts** [comment] 2024-09-25 12:43
I have noted it down. We can close it out.

**Comment by greg-schroeder** [comment] 2024-09-25 19:21
Well, payment date is today, so I'm doing it now. :)

**Comment by greg-schroeder** [comment] 2024-09-25 19:22
Paid

**Closed by greg-schroeder** 2024-09-25 19:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-14 21:57
$250 approved for @allroundexperts
