### ISSUE TITLE
[$500] Settings - Pronouns list is not translated dynamically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22089] opened 2023-07-02 23:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app in another device and login with user A (device 2)
3. From device 1, click on your avatar
4. From device 1, open profile settings
5. From device 1, click on Pronouns option and type "they" for example in the search bar
6. From device 2, change language to Spanish

## Expected Result:
The Pronouns list should translated dynamically, currently it does only if you click back and navigate to Pronouns settings again

## Actual Result:
The Pronouns list is not translated dynamically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b9ed5f23-0350-429d-8da6-c6a36ae92b21

https://github.com/Expensify/App/assets/93399543/b776116f-85ce-4143-92d9-65ffb7ea836d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688240365001069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a28be895fb2072a1</li>
        <li>Upwork Job ID: 1697070055301615616</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-02 23:36
The same issue for User name.
Reproduction steps:
1- Open the app and login with user A (device 1)
2- Open the app and login with user A (device 2)
3- From device 1, Click on your avatar
4- From device 1, Go to profile settings
5- From device 1, Click on display name option
6- From device 2, change the display name

Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1688245970202529

Uploading Recording #5296.mp4…

**Comment by anmurali** [comment] 2023-07-03 14:27
<img width="399" alt="image" src="https://github.com/Expensify/App/assets/14225673/5e5d8c94-eb24-430e-8630-fefcc888158a">
I cannot reproduce

**Comment by mejed-alkoutaini** [comment] 2023-07-05 13:33
@anmurali Hi, are you will not able to reproduce? I'm able to reproduce with many devices

**Comment by kbecciv** [comment] 2023-07-28 16:35
@huzaifa-99 Did you check again with latest build?

**Comment by kbecciv** [comment] 2023-08-26 14:09
Hello @huzaifa-99 @anmurali Coming back from OOO, checking if able to reproduce in latest build

**Comment by kbecciv** [comment] 2023-08-26 14:15
Reproduced on build 3.57-5

https://github.com/Expensify/App/assets/93399543/7bdedfd7-e4e9-49c0-be8a-f613827dc45a


https://github.com/Expensify/App/assets/93399543/69a21a6b-9d3b-41cd-9353-78c358c03321

**Comment by anmurali** [comment] 2023-08-31 02:13
Looks like still reproducible in latest build

**Comment by bir-dv** [comment] 2023-08-31 09:26
I want to work on this issue.

**Comment by bir-dv** [comment] 2023-08-31 09:30
Contributor details
Your Expensify account email: brukjoseph@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0164009477845d701a

**Comment by burczu** [comment] 2023-09-04 06:42
Not overdue - I'll review proposals today.

**Comment by burczu** [comment] 2023-09-04 12:10
Since proposals from both @c3024 and @huzaifa-99 are very similar, I prefer [the one](https://github.com/Expensify/App/issues/22089#issuecomment-1617304553) from @huzaifa-99 - I believe adding `preferredLocale` as a dependency of `useCallback` is more reasonable because it is the property that is actually changing when we change the language in the App. The change of the `translate` method (used in @c3024's [proposal](https://github.com/Expensify/App/issues/22089#issuecomment-1617110690)) is just a side effect of it.

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-09-05 07:41
@c3024 In React [docs](https://legacy.reactjs.org/docs/hooks-rules.html#eslint-plugin) the default setting recommended for the `react-hooks/exhaustive-deps` rule is `warn`, so in my opinion this rule is designed to notify developers that maybe they have forgotten adding some dependencies to `useEffect`/`useCallback`/`useMemo` hooks. But if adding all the values to the deps array does not make sense, we should not do it.

**Comment by burczu** [comment] 2023-09-06 13:06
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by MonilBhavsar** [comment] 2023-09-12 02:40
I see we have mixed use of translate and props.preferredLocale in dependencies.  I don't think we have a rule here. we can discuss in slack in #expensify-opensource, and agree on using one dependency.

**Comment by MonilBhavsar** [comment] 2023-09-14 16:32
Awaiting reviews

**Comment by burczu** [comment] 2023-09-18 11:07
> There's another issue relating to locale change for emoji suggestion list here https://github.com/Expensify/App/issues/25735 where they've [concluded](https://expensify.slack.com/archives/C01GTK53T8Q/p1692876804755169) that searching in English should also display the Spanish result and vice versa.

I don't think what applies to searching emojis applies also to searching for pronouns... Also I have concerns about the "vice versa" part of your comment - for emojis they wanted to allow searching in english if you set spanish, but not allowing searching in spanish when you set language to english.

This behaviour for emojis seems reasonable but for regular search it is strange... What do you think @MonilBhavsar?

**Comment by c3024** [comment] 2023-09-18 11:09
It appears that the page was refactored and changed significantly and `translate` was added to the dependencies already.

**Comment by burczu** [comment] 2023-09-18 11:10
@c3024 You mean it's fixed already?

**Comment by c3024** [comment] 2023-09-18 11:20
Yes

**Comment by MonilBhavsar** [comment] 2023-09-20 04:37
@burczu did you get a chance to take a look?
I see that dependency is added, so should be fixed

**Comment by burczu** [comment] 2023-09-20 10:07
@MonilBhavsar sorry for the delay - I have quite a lot on my now. I'll check it today.

**Comment by burczu** [comment] 2023-09-20 12:06
@MonilBhavsar Re-tested and I can confirm it's fixed now.

**Closed** 2023-09-25 15:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
