### ISSUE TITLE
[Held on 28618] [$500] IOU - User navigates to Money Request page when refresh Category page and go Back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30984] opened 2023-11-07 12:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to any conversation
3. Click + button > Request Money> Scan
4. Upload a receipt
5. Click on Category field
6. Refresh the page
7. Click Back button on IOU screen

## Expected Result:
User should be navigated back to the Final confirmation screen

## Actual Result:
User navigates to Money Request page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/bb687034-5470-47d2-8664-aaf6bc96fb1b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d1dbb7f19dde814</li>
        <li>Upwork Job ID: 1721860229053939712</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-11-07 12:02
Similar issue reported [here](https://github.com/Expensify/App/issues/30682)

**Comment by FitseTLT** [comment] 2023-11-07 13:42
> Similar issue reported [here](https://github.com/Expensify/App/issues/30682)

Nope. That is a separate issue.

**Comment by erquhart** [comment] 2023-11-07 13:46
This should be solved by https://github.com/Expensify/App/issues/30884, same solution proposed: https://github.com/Expensify/App/issues/30884#issuecomment-1793852071

**Comment by anmurali** [comment] 2023-11-29 04:32
Held on https://github.com/Expensify/App/pull/28618

**Comment by anmurali** [comment] 2023-12-13 14:50
Closing this as it is a dupe of https://github.com/Expensify/App/issues/30884

**Closed by anmurali** 2023-12-13 14:50 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
