### ISSUE TITLE
Expensify Card - Empty state card is top centered instead of middle centered

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46488] opened 2024-07-30 11:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings.
3. Go to Expensify Card.

## Expected Result:
The empty state card will be middle centered (production behavior).

## Actual Result:

Empty state card is top centered instead of middle centered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6f210635-f344-4d7a-9a20-cfdeaf973394

![Bug6557060_1722324180584!production](https://github.com/user-attachments/assets/ce25ad8d-f21f-4e52-96f2-8c0c55b3e3a5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-30 11:25
We think this issue might be related to the #collect project.

**Comment by koko57** [comment] 2024-07-30 12:00
Kind of. It was hard to center, bc we have a content below that appears after scrolling and on some devices the modal was cut off at the bottom (making the text hidden). I can work on this to fix it

**Comment by OfstadC** [comment] 2024-07-30 12:11
Assigned to me while I was OoO - reassigning since this is time sensitive and i'm not back online fully until tomorrow . I can nab it back tomorrow if this ends up not being a blocker - or as urgent

**Comment by koko57** [comment] 2024-07-30 13:39
it should not be a blocker as it's behind the beta

**Comment by koko57** [comment] 2024-07-31 06:45
As I introduced the change and I am still working on the Workspace Feed project, can I be assigned to fix this issue?

cc @mountiny

**Comment by koko57** [comment] 2024-08-02 10:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Empty state modal is not centered. 

### What is the root cause of that problem?
Changes from https://github.com/Expensify/App/pull/45996 - previously the modal had additional styles similar to the ones suggested in the [previous Proposal](https://github.com/Expensify/App/issues/46488#issuecomment-2258154311)

https://github.com/Expensify/App/blob/5430694a832c70b0541dff5d12242f5a204f00e5/src/pages/workspace/expensifyCard/EmptyCardView.tsx#L34

but they were insufficient in some cases, because on some devices the modal was cut off - that's why I introduced the "flex-start" change. 

The real problem though was that the EmptyStateComponent wrapper's height was not calculated properly.

### What changes do you think we should make in order to solve the problem?

1. Change mt5 to pt5 (margin to padding) in this line: 
https://github.com/Expensify/App/blob/5430694a832c70b0541dff5d12242f5a204f00e5/src/pages/workspace/expensifyCard/EmptyCardView.tsx#L26
2. On iOS we additionally need to add SafeArea inset top to the equation for calculating header height, because it's not taken into account in windowHeight value (it's the same as screenHeight)

<img width="661" alt="Screenshot 2024-08-01 at 20 16 16" src="https://github.com/user-attachments/assets/32f1a980-8ef7-443e-9433-4d1ef7349872">

this way we'll get the proper height for both iOS and Android (please ignore red line, the teal line is important here)
![Screenshot_1722535171](https://github.com/user-attachments/assets/40e7552a-9e54-4a58-a703-efaf011f178b)
![Screenshot_1722535227](https://github.com/user-attachments/assets/bedf3f65-2492-4c59-922e-d2f0ea62bc20)
![Simulator Screenshot - iPhone 15 Pro - 2024-08-01 at 19 59 42](https://github.com/user-attachments/assets/8e995307-8b4b-4b51-a632-e5cb978cf549)
![Simulator Screenshot - iPhone 15 Pro - 2024-08-01 at 19 59 33](https://github.com/user-attachments/assets/7ba287b8-043d-4538-99cf-8fdb9a456697)

and we don't see the skeletons after scrolling (which was the case on some devices earlier) but the disclaimer is appearing right away.


### What alternative solutions did you explore? (Optional)

-

**Comment by DylanDylann** [comment] 2024-08-05 03:46
@koko57 Please raise a PR for this

**Comment by DylanDylann** [comment] 2024-08-05 03:47
@anmurali  Please assign me and @koko57 to this issue

**Comment by koko57** [comment] 2024-08-06 09:01
@DylanDylann PR ready for review https://github.com/Expensify/App/pull/46860

**Comment by koko57** [comment] 2024-08-30 07:24
@mountiny I think we can close it

**Comment by mountiny** [comment] 2024-09-02 11:42
Thanks!

**Closed by mountiny** 2024-09-02 11:42 UTC
Labels: Reviewing, Engineering, Monthly, Bug
