### ISSUE TITLE
[HOLD for payment 2023-07-26] Connect Bank - Connect bank account step counter disappeared

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23091] opened 2023-07-18 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2.  Go to setting => workspace => your workspace
3. Bank account => Connect Manually
4. Observe that  "Step 1 of 5" that appears not appears in the header like the production

## Expected Result:
 In manually connecting we should have a Step counter

## Actual Result:
In manually connecting  Step counter is missed from the header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/76e33624-397d-44ca-aadb-2987a6004ede

https://github.com/Expensify/App/assets/93399543/f8172d27-af27-4f28-b338-c7f1ad917882

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689660526773759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-18 14:18
## Proposal
by : @ahmdshrif 

### Problem Restatement:
The problem we are addressing is that the steps counter is not appearing in the header of the manual connect to the bank feature.

### Root Cause:
The root cause of this issue is the refactoring of the `HeaderWithBackButton` component from a class component to a function component. During this refactoring, the default value of `shouldShowStepCounter` was changed. Previously, the default value was true, as shown in this code: [ link](https://github.com/Expensify/App/blob/0b00e1cc82a4f6023aff6b89796a91fba6be91a2/src/components/HeaderWithBackButton.js#L129). However, when the component was converted to a function component, the default value of `shouldShowStepCounter` was mistakenly set to false, as seen in this code: [ link](https://github.com/Expensify/App/blob/1e2a9a371e15a120f1752ed86f0a31b589a3982b/src/components/HeaderWithBackButton/index.js#L40). As a result, any component that did not explicitly pass the `shouldShowStepCounter` prop would take the default value of false, causing the steps counter to be hidden.

### Proposed Solution:
To resolve the problem, we recommend reverting the aforementioned change and setting the default value of `shouldShowStepCounter` back to true. By doing so, the steps counter will be correctly displayed in the header.
an additional issue related to the connect with Plaid in production. Once the initial issue is addressed, the steps counter should not be displayed during the Plaid integration. We have proposed a solution for this in the following Slack thread: https://expensify.slack.com/archives/C049HHMV9SM/p1689660306598649?thread_ts=1689660228.939159&cid=C049HHMV9SM

### Alternative Solution Explored:
An alternative solution that has been explored is to keep the default value of `shouldShowStepCounter` as false and explicitly pass this prop to all the places where the steps counter needs to appear like BankAccountManualStep.js

**Comment by luacmartins** [comment] 2023-07-18 17:17
@ahmdshrif thanks for the investigation. I took a closer look at that prop and I think it's unnecessary since we can derive its value from `subStep` prop. I went ahead with my solution of removing the prop entirely.

**Comment by situchan** [comment] 2023-07-18 17:22
This regression came from https://github.com/Expensify/App/pull/21852 and there's possibility that PR would be reverted. - https://github.com/Expensify/App/issues/23052#issuecomment-1640394821

**Comment by luacmartins** [comment] 2023-07-18 17:23
I think even if we revert that PR, this is still a good clean up

**Comment by jasperhuangg** [comment] 2023-07-18 18:33
We just CP'd the fix, I'll retest and close this out once the CP is done

**Comment by jasperhuangg** [comment] 2023-07-18 18:37
<img width="1703" alt="Screenshot 2023-07-18 at 11 37 05 AM" src="https://github.com/Expensify/App/assets/31285285/085492cf-75eb-4eb0-83bc-015703c05d39">

**Comment by jasperhuangg** [comment] 2023-08-14 17:11
@ahmdshrif sorry about that! We'll make sure you get paid out. Thanks for raising this to your attention.

**Comment by situchan** [comment] 2023-12-21 20:41
@ahmdshrif please ask for help in [this slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1703178198003739) which is a lot quicker than waiting for update on closed GH

**Comment by mallenexpensify** [comment] 2023-12-23 17:16
First off.. let's reopen this puppy 🐶 

@ahmdshrif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013d200e4dffabf2cf

(sidenote.. this very likely won't be paid, in final, til after the holidays, sorry for the delay)

**Comment by mallenexpensify** [comment] 2023-12-23 18:01
Reporter: @ahmdshrif paid $250 via Upwork (report was in July)

**Closed by mallenexpensify** 2023-12-23 18:01 UTC
Labels: DeployBlockerCash, Engineering, Weekly, Awaiting Payment, Bug
