### ISSUE TITLE
[HOLD E/E#213315] Group - When creating a group/1:1 chat, a message is displayed that the group is not online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11503] opened 2022-10-01 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

On hold for https://github.com/Expensify/Expensify/issues/213315

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in any account
3. Click on the green + button
4. Click on the "New group" option
5. Select 8 random users from the search list.
6. Click Crate a Group

## Expected Result:
No messages should appear on the screen when a new group is created

## Actual Result:
When creating a group, a message is displayed that the group is not online

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193414574-5df75fb9-bfe2-4e46-9839-12c0cf14ae26.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-10-03 09:59
This is definitely caused by this refactoring: https://github.com/Expensify/App/pull/10452

Not sure now why the reportID is not accessible when the report is created as it should be in optimistic

**Comment by mountiny** [comment] 2022-10-03 10:32
@iwiznia The create chat/group chat commands are not refactored yet. I assume this should be resolved once these actions are optimistic hence the reportID will always be there and we should not face this issue.

Then I would say to remove the deploy blocker and wait for the refactorings to be completed. Stites is working on them now afaik and it should not take too long to complete.

**Comment by mountiny** [comment] 2022-10-04 09:05
This is not a deploy blocker as this is a small design issue and it will be resolved by the api refactor done by @stitesExpensify 

I will put this in hold and assign you @stitesExpensify so you can then close this on out with your API refactor PR

**Comment by mountiny** [comment] 2022-10-04 09:10
Actually I have mentioned this in the appropriate App PR to be part of the testing steps there to make sure this is fixed by those changes. Closing this

**Closed by mountiny** 2022-10-04 09:10 UTC
Labels: Engineering, Weekly, Improvement
