### ISSUE TITLE
Web - Chat - Clicking on the link https://staging.new.expensify.com/statement123 navigates to a blank screen within the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9158] opened 2022-05-24 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8980
## Action Performed:
1. Launch the app.
2. Open any report.
3. Send this link - https://new.expensify.com/statements/123
and click on the link
4. Insert "staging" and click the link

## Expected Result:
Verify that clicking on the link navigates the app to a screen within the app.

## Actual Result:
Step3 : Opens in a new tab to login to NewDot production
Step4 : Blank screen within the app opens

## Workaround:
Unknown
## Platform:

Where is this issue occurring?
NOTE : Other than web in all other environments clicking https://.new.expensify.com/statements/123(https://new.expensify.com/statements/123) leads to blank page
- Web 
- iOS 
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.66.0
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/170137381-ba8b9544-183f-4440-a0c8-2a69968d824e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by TomatoToaster** [comment] 2022-05-24 22:09
Ah interesting. I'm going to try looking into this tomorrow because I have an idea of how the relinking is supposed to work, but if I can't figure this out by tomorrow, I'll make this external.

**Comment by rushatgabhane** [comment] 2022-05-25 10:16
Step 3 isn't a bug. `new.expensify.com/statements/123` isn't supposed to work on staging.

**Comment by rushatgabhane** [comment] 2022-05-25 10:29
Step 4 isn't a bug because `statements/123` doesn't exist.
We should def handle it in a better way tho

**Comment by Julesssss** [comment] 2022-05-25 10:48
> Step 3 isn't a bug. `new.expensify.com/statements/123` isn't supposed to work on staging.

I agree, but the next QA step resolves this: 

> 4. Insert "staging" ...

**Comment by Julesssss** [comment] 2022-05-25 10:49
> Step 4 isn't a bug because `statements/123` doesn't exist. We should def handle it in a better way tho

I also agree with this. This issue sounds like new logic rather than a regression, right? We should handle links to URLs which don't exist.

**Comment by rushatgabhane** [comment] 2022-05-25 10:52
> This issue sounds like new logic rather than a regression, right? Something like: handle links to statements that don't exist

Yep, I agree!

**Comment by TomatoToaster** [comment] 2022-05-25 15:06
Oh neat! So should we repurpose this issue to be about better handling links to statements that don't exist or make a new one and close this?

**Comment by Julesssss** [comment] 2022-05-25 17:20
I'm making this a NewDot deploy blocker and it looks like it was introduced by [this PR](https://github.com/Expensify/App/pull/8980). It would be great if we could treat this with urgency as it remains the final blocker for the [release](https://github.com/Expensify/App/issues/9151). 

Please remember to add the `CP Staging` label to the PR so that the fix is included in the release build. Thanks!

**Closed** 2022-05-25 17:42 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by rushatgabhane** [comment] 2022-05-25 17:47
Is it just me or I get the white screen on production too.

https://user-images.githubusercontent.com/29673073/170329412-7f97be8f-0a8b-4abd-804b-840c88fd4cfe.mov

**Comment by thienlnam** [comment] 2022-05-25 17:58
> Is it just me or I get the white screen on production too.

The white screen you're seeing is actually different from the error in the description.  What email are you using to try to access those links? I think it's because you don't have access to a wallet.

Those links work for me on production besides https://new.expensify.com/statements/202205 since you can only view previous month statements

![Screen Shot 2022-05-25 at 10 58 44 AM](https://user-images.githubusercontent.com/30609178/170331533-b1dd1738-eb3f-477d-9f7b-9407039e0b75.png)

**Comment by rushatgabhane** [comment] 2022-05-25 18:06
That makes so much sense, thank you!!
