### ISSUE TITLE
Request Money - Error messages is showing at the different levels

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14024] opened 2023-01-05 16:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with the same account in the main testing device and a secondary device
3.Disable the internet connection in the main testing device
4. From the main + menu, create a money request with the account logged in the secondary device
5. In the secondary device request money to the main testing device account
6. Enable the internet connection in in the main testing device, the money request request will be sent and will get a response an error.
7. Verify that the chat row in the LHN appears greyed out with a solid red dot icon
8. Click into the chat that failed to create that have a red dot
9. Verify you see an error message in-line beneath the welcome message because it failed to be created.

## Expected Result:
Both errors must be on the same level.

## Actual Result:
Error messages is showing at the different levels

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.48.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Web](https://user-images.githubusercontent.com/93399543/210835444-bc703de0-c88a-42f4-ad95-18f1c8f4110f.png)

![Screenshot_20230105_160837_Chrome](https://user-images.githubusercontent.com/93399543/210835486-4eeca2c0-d0cd-4ee0-baf0-5b2543e6fb43.jpg)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01230028c8f7540a83</li>
        <li>Upwork Job ID: 1611127125601341440</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-01-05 22:26
I'm not sure that I understand what the issue is. @kbecciv could you please clarify?

**Comment by luacmartins** [comment] 2023-01-09 16:48
Bump @kbecciv. I'm still not sure what the issue is here. Could you please clarify what you mean by `Error messages is showing at the different levels`?

**Comment by kbecciv** [comment] 2023-01-11 16:05
We are expecting to see two errors messages in one line. 

![image](https://user-images.githubusercontent.com/93399543/211855871-16cbef1f-df72-49f6-b2f8-d5cc864a6dcd.png)

**Comment by luacmartins** [comment] 2023-01-11 18:29
@kbecciv I'm still not sure that I understand. Are you saying that we expect layout 1, layout 2 or neither?

**Layout 1**
![210835486-4eeca2c0-d0cd-4ee0-baf0-5b2543e6fb43 (1)](https://user-images.githubusercontent.com/22219519/211888367-bc26c2f7-810c-41e7-b29c-1123a3cdc583.jpg)

**Layout 2**
![210835486-4eeca2c0-d0cd-4ee0-baf0-5b2543e6fb43](https://user-images.githubusercontent.com/22219519/211888478-68fb850b-487f-4db1-8ce9-27aae399d4cd.jpg)

**Comment by kbecciv** [comment] 2023-01-12 15:06
I would expect to see Layout 1, but we can ask in Slack for more opinions.

**Comment by luacmartins** [comment] 2023-01-12 15:57
@shawnborton can you confirm if Layout 1 above is what we would expect vs the center-aligned error message from the OP?

**Comment by luacmartins** [comment] 2023-01-12 17:13
Discussed in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1673541388823159), and we'll handle this in [this PR](https://github.com/Expensify/App/pull/13647). Closing this issue!

**Closed by luacmartins** 2023-01-12 17:13 UTC
Labels: Daily, Internal, Bug
