### ISSUE TITLE
[HOLD for payment 2023-02-06] [$2000] Message gets unselected after user press Command + C highlighting the text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14300] opened 2023-01-13 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any  account.
2. Go to any report, select a paragraph by dragging the mouse and press Command + C to copy it.
3. Notice that the paragraph gets unselected after that.

## Expected Result:
The message should stay selected after being copied.

## Actual Result:
The message gets unselected after being copied.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [x] MacOS /Safari

**Version Number:** v1.2.54-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212421096-308ab14f-3d51-4ab0-8fcd-fd654575acd0.mov

https://user-images.githubusercontent.com/43996225/212421227-e352fb34-9236-4704-9829-eb41530c5cff.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673617885136949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab10f30691f511bc</li>
        <li>Upwork Job ID: 1614055083385741312</li>
        <li>Last Price Increase: 2023-01-21</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-01-14 00:21
Able to reproduce.

**Comment by allroundexperts** [comment] 2023-01-14 01:01
## Proposal

### Fix

```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626..cd7998363 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -29,6 +29,7 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    const originalRange = selection.getRangeAt(0);
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -43,6 +44,7 @@ function setHTMLSync(html, text) {
 
     selection.removeAllRanges();
     document.body.removeChild(node);
+    selection.addRange(originalRange);
 }
 
 /**

```

**Comment by tienifr** [comment] 2023-01-14 01:29
# Proposal

This happens due to we're clearing the selection ranges after copying on Safari. We need to restore the original ranges after adding the custom range.

The code below will do it, please note here it's making sure to add **all the original ranges**, since we cannot assume that there'll only be 1 range in the selection.
```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626e..46fa15291a 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -6,6 +6,30 @@ import * as Browser from '../Browser';
 
 const canSetHtml = () => lodashGet(navigator, 'clipboard.write');
 
+/**
+ * Get all selection ranges
+ * @param {Selection} selection
+ * @returns {Array<Range>}
+ */
+const getAllSelectionRanges = (selection) => {
+    const ranges = [];
+
+    for (let i = 0; i < selection.rangeCount; i++) {
+        ranges.push(selection.getRangeAt(i));
+    }
+
+    return ranges;
+};
+
+/**
+ * Add ranges to selection
+ * @param {Selection} selection
+ * @param {Array<Range>} ranges
+ */
+const addRangesToSelection = (selection, ranges) => {
+    ranges.forEach(range => selection.addRange(range));
+};
+
 /**
  * Deprecated method to write the content as HTML to clipboard.
  * @param {String} html HTML representation
@@ -29,6 +53,8 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    const currentRanges = getAllSelectionRanges(selection);
+
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -42,6 +68,8 @@ function setHTMLSync(html, text) {
     }
 
     selection.removeAllRanges();
+    addRangesToSelection(selection, currentRanges);
+
     document.body.removeChild(node);
 }
 

```

**Comment by allroundexperts** [comment] 2023-01-14 01:53
@tienifr Multiple ranges are only allowed in Firefox. Since this code is running on Safari ONLY, therefore, there will ALWAYS be a single range. So looping over all the ranges is useless.

**Comment by tienifr** [comment] 2023-01-14 02:19
Assuming it’s true, I believe we should still do this for future proofing,
browser behavior can change any time, especially when the Selection API
already accepts multiple ranges signature.

Also when writing any code I want to ensure it works on any browser, rather
than needing to confirm the branch of code only runs on Safari to have the
assurance that it’s fine.

Would like to here others’s thought on this too!

**Comment by s77rt** [comment] 2023-01-14 11:17
### Proposal
```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626e..c24cd7199e 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -1,49 +1,18 @@
-// on Web/desktop this import will be replaced with `react-native-web`
-import {Clipboard} from 'react-native-web';
 import lodashGet from 'lodash/get';
 import CONST from '../../CONST';
 import * as Browser from '../Browser';
 
-const canSetHtml = () => lodashGet(navigator, 'clipboard.write');
-
-/**
- * Deprecated method to write the content as HTML to clipboard.
- * @param {String} html HTML representation
- * @param {String} text Plain text representation
- */
-function setHTMLSync(html, text) {
-    const node = document.createElement('span');
-    node.textContent = html;
-    node.style.all = 'unset';
-    node.style.opacity = '0';
-    node.style.position = 'absolute';
-    node.style.whiteSpace = 'pre-wrap';
-    node.style.userSelect = 'text';
-    node.addEventListener('copy', (e) => {
-        e.stopPropagation();
-        e.preventDefault();
-        e.clipboardData.clearData();
-        e.clipboardData.setData('text/html', html);
-        e.clipboardData.setData('text/plain', text);
-    });
-    document.body.appendChild(node);
-
-    const selection = window.getSelection();
-    selection.removeAllRanges();
-    const range = document.createRange();
-    range.selectNodeContents(node);
-    selection.addRange(range);
-
-    try {
-        document.execCommand('copy');
-    } catch (e) {
-        // The 'copy' command can throw a SecurityError exception, we ignore this exception on purpose.
-        // See https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html#the-copy-command for more details.
+const canSetHtml = () => {
+    if (CONST.BROWSER.SAFARI === Browser.getBrowser()) {
+        // Although Safari do support text/html we don't use it for the following reason:
+        // Safari sanitize "text/html" data before writing to the pasteboard when using Clipboard API,
+        // whitespaces in the start of line are stripped away.
+        // See https://webkit.org/blog/10855/async-clipboard-api/ for more details.
+        return false;
     }
 
-    selection.removeAllRanges();
-    document.body.removeChild(node);
-}
+    return lodashGet(navigator, 'clipboard.write');
+};
 
 /**
  * Writes the content as HTML if the web client supports it.
@@ -59,21 +28,13 @@ const setHtml = (html, text) => {
         throw new Error('clipboard.write is not supported on this platform, thus HTML cannot be copied.');
     }
 
-    if (CONST.BROWSER.SAFARI === Browser.getBrowser()) {
-        // Safari sanitize "text/html" data before writing to the pasteboard when using Clipboard API,
-        // whitespaces in the start of line are stripped away. We use the deprecated method to copy
-        // contents as HTML and keep whitespaces in the start of line on Safari.
-        // See https://webkit.org/blog/10855/async-clipboard-api/ for more details.
-        setHTMLSync(html, text);
-    } else {
-        navigator.clipboard.write([
-            // eslint-disable-next-line no-undef
-            new ClipboardItem({
-                'text/html': new Blob([html], {type: 'text/html'}),
-                'text/plain': new Blob([text], {type: 'text/plain'}),
-            }),
-        ]);
-    }
+    navigator.clipboard.write([
+        // eslint-disable-next-line no-undef
+        new ClipboardItem({
+            'text/html': new Blob([html], {type: 'text/html'}),
+            'text/plain': new Blob([text], {type: 'text/plain'}),
+        }),
+    ]);
 };
 
 /**
@@ -82,7 +43,7 @@ const setHtml = (html, text) => {
  * @param {String} text
  */
 const setString = (text) => {
-    Clipboard.setString(text);
+    navigator.clipboard.writeText(text);
 };
 
 export default {
```

### RCA
Safari supports `navigator.clipboard.write` so we can use it to copy html, but it's does not work as you'd expect, as it sanitise the html and results in an unwanted output. For that we opted to use a deprecated way to copy content as html and I think that was a wrong move. What we should have done instead is to treat Safari as if it does not support `navigator.clipboard.write` because it's support is really not that great. (for the rest of this comment Safari is considered not to support html)
BTW Firefox also does not support that, so we are not leaving Safari in the shade. Apparently only Chrome supports that feature correctly.

Moving to the solution...

#### HTML:
Safari does not support html, so we should use `setString`. I have added a condition on `canSetHtml` to return `false` if the browser is safari.

#### TEXT:
The current code uses `Clipboard` from `react-native-web` which also does not work great. Selected message will get unselected after CTRL+C. It looks as they are using the deprecated method as well. (This also effects Firefox)
I have swapped the use of `react-native-web` with `navigator.clipboard.writeText` which is [supported on all browsers](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#browser_compatibility).


### Results


https://user-images.githubusercontent.com/16493223/212469299-3c496b0b-6fb6-4483-b2c9-2c6bdb45b5d0.mp4

**Comment by Santhosh-Sellavel** [comment] 2023-01-15 17:54
@anmurali or @youssef-lr 
Unassigning this one due to limited availability this week, can you assign another C+ here to continue review here, thanks!

**Comment by mollfpr** [comment] 2023-01-18 17:33
@s77rt Your proposal introduces regression where paste with match style not working on Safari where it was working on staging.


https://user-images.githubusercontent.com/25520267/213253297-8e6cdc52-63f0-4d5c-9461-e21298fcfd45.mov

**Comment by mollfpr** [comment] 2023-01-18 17:44
@tienifr Can you pointing it out when there will be more than 1 range count in this issue?

**Comment by s77rt** [comment] 2023-01-18 17:58
@mollfpr I think the regression is not related to my proposal. Please check on your local dev before applying the proposal, you will get the same behaviour.

**Comment by mollfpr** [comment] 2023-01-18 18:04
@s77rt I did check before applying the proposal, and it works like in staging. It only happen after I apply your proposal diff.

**Comment by tienifr** [comment] 2023-01-18 18:05
@mollfpr Also the fact that when restoring the range, we `removeAllRanges` and then `restore only first range` doesn't sound right semantically. When looking at it other people will need to have very deep understanding of where that code runs and technical details of the Selection API in order to know if it might be correct, even then it cannot be sure that it will not break In the future.

**Comment by tienifr** [comment] 2023-01-18 18:30
Since the fix for this issue is rather straightforward, I think the completeness of the solution is a major factor, this criteria was mentioned on other issues like [here](https://github.com/Expensify/App/issues/13616#issuecomment-1370270078).

Let's leave @mollfpr to make the call on this.

Thanks

**Comment by s77rt** [comment] 2023-01-18 18:32
@mollfpr Ah I got it now, the paste and match style works with html only not with markdown.
With my proposal we are no longer copying as html (because it's not supported well on Safari) so everything is copied as a text (markdown).

**Comment by mollfpr** [comment] 2023-01-18 19:01
@tienifr Thanks for your concern and that's really great to think about future breaks as well! IIRC we don't give full support for other browsers than Chrome and Safar. Also, I could find any plan for Chrome to implement the multiple add range.

As the spec https://www.w3.org/TR/selection-api/#dom-selection-addrange on Chrome _addRange_ only accept 0 for the range count other than that do nothing. So @allroundexperts [proposal](https://github.com/Expensify/App/issues/14300#issuecomment-1382616690) is valid for this case.

---

I also found a similar issue to this with copying text inside the composer. But, the issue is not solved with the _addRange_ proposal.


https://user-images.githubusercontent.com/25520267/213270427-508276c9-e1e6-4f81-863f-ac9f7530b076.mov

@youssef-lr Should we fix it in this issue?

**Comment by s77rt** [comment] 2023-01-18 19:15
@mollfpr Finally, a reason that I can use to back up my proposal 😅

**Comment by wildan-m** [comment] 2023-01-19 07:52
### Proposal

### Root Cause

The selection get unselected during `setHtml` execution.

### Solution
Save the original range and restore it back after `setHtml` process is completed.

`selection.getRangeAt(0)` and `selection.addRange` will only work for nontext elements.

To programmatically get and set selection we can play with element's `selectionStart`, `selectionEnd` and `setSelectionRange`.

Please test it here:

https://github.com/wildan-m/App/tree/wildan-14300-MessageGetUnselected

### Changes
```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626..71d66c177 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -3,6 +3,7 @@ import {Clipboard} from 'react-native-web';
 import lodashGet from 'lodash/get';
 import CONST from '../../CONST';
 import * as Browser from '../Browser';
+import { length } from 'localforage';
 
 const canSetHtml = () => lodashGet(navigator, 'clipboard.write');
 
@@ -29,6 +30,12 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    let originalRange = selection.getRangeAt(0);
+    const firstAncestorChild = originalRange.commonAncestorContainer.firstChild;
+    
+    if(firstAncestorChild && isTextElement(firstAncestorChild))
+        originalRange = getInputSelection(firstAncestorChild);
+
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -42,7 +49,13 @@ function setHTMLSync(html, text) {
     }
 
     selection.removeAllRanges();
-    document.body.removeChild(node);
+
+    if(firstAncestorChild && isTextElement(firstAncestorChild))
+        firstAncestorChild.setSelectionRange(originalRange.start, originalRange.end);
+    else
+        selection.addRange(originalRange);
+
+        document.body.removeChild(node);
 }
 
 /**
@@ -59,7 +72,7 @@ const setHtml = (html, text) => {
         throw new Error('clipboard.write is not supported on this platform, thus HTML cannot be copied.');
     }
 
-    if (CONST.BROWSER.SAFARI === Browser.getBrowser()) {
+   if (CONST.BROWSER.SAFARI === Browser.getBrowser()) {
         // Safari sanitize "text/html" data before writing to the pasteboard when using Clipboard API,
         // whitespaces in the start of line are stripped away. We use the deprecated method to copy
         // contents as HTML and keep whitespaces in the start of line on Safari.
@@ -85,6 +98,66 @@ const setString = (text) => {
     Clipboard.setString(text);
 };
 
+const isTextElement = (el) => {
+    if (el instanceof HTMLInputElement) {
+        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types
+        if (/|text|email|number|password|search|tel|url/.test(el.type || '')) {
+            return true;
+        }
+    }
+    if (el instanceof HTMLTextAreaElement)
+        return true;
+
+    return false;
+}
+
+// ref: https://stackoverflow.com/a/4931963/1174657
+const getInputSelection = (el) => {
+    var start = 0, end = 0, normalizedValue, range,
+        textInputRange, len, endRange;
+
+    if (typeof el.selectionStart == "number" && typeof el.selectionEnd == "number") {
+        start = el.selectionStart;
+        end = el.selectionEnd;
+    } else {
+        range = document.selection.createRange();
+
+        if (range && range.parentElement() == el) {
+            len = el.value.length;
+            normalizedValue = el.value.replace(/\r\n/g, "\n");
+
+            // Create a working TextRange that lives only in the input
+            textInputRange = el.createTextRange();
+            textInputRange.moveToBookmark(range.getBookmark());
+
+            // Check if the start and end of the selection are at the very end
+            // of the input, since moveStart/moveEnd doesn't return what we want
+            // in those cases
+            endRange = el.createTextRange();
+            endRange.collapse(false);
+
+            if (textInputRange.compareEndPoints("StartToEnd", endRange) > -1) {
+                start = end = len;
+            } else {
+                start = -textInputRange.moveStart("character", -len);
+                start += normalizedValue.slice(0, start).split("\n").length - 1;
+
+                if (textInputRange.compareEndPoints("EndToEnd", endRange) > -1) {
+                    end = len;
+                } else {
+                    end = -textInputRange.moveEnd("character", -len);
+                    end += normalizedValue.slice(0, end).split("\n").length - 1;
+                }
+            }
+        }
+    }
+
+    return {
+        start: start,
+        end: end
+    };
+}
+
 export default {
     setString,
     canSetHtml,

```

**Comment by wildan-m** [comment] 2023-01-20 00:05
### Proposal (Updated)

### Root Cause

The selection get unselected during `setHtml` execution.

### Update Log
This update includes preserving the selection direction.
`addRange` doesn't keep the direction, we can change it with `setBaseAndExtent` instead.

### Solution
Save the original range and restore it back after `setHtml` process is completed.

We can use `setBaseAndExtent` to restore the current selection and its direction. `setBaseAndExtent` will only work for nontext input elements.

To programmatically get and set selection inside text element, we can play with the element's `selectionStart`, `selectionEnd`, and `setSelectionRange`.

Please test it here:

https://github.com/wildan-m/App/tree/wildan-14300-MessageGetUnselected

<details><summary>Selection direction test case</summary>

1. Make text selection
2. Extend selection using `shift+→`
3. Perform `cmd+C`
4. Press `shift+ ←`

Expected result:
Since the initial direction before the copy process is forward direction, then if we press `shift+ ←` then the selection should be reduced, not extended the selection to the left side. 

</details>

### Changes
```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626..15ed54f1f 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -29,6 +29,14 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    let originalSelection = null;
+    const firstAnchorChild = selection.anchorNode.firstChild;
+
+    if(firstAnchorChild && isTextElement(firstAnchorChild))
+        originalSelection = getInputSelection(firstAnchorChild);
+    else
+        originalSelection = saveSelection(selection);
+
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -42,6 +50,12 @@ function setHTMLSync(html, text) {
     }
 
     selection.removeAllRanges();
+
+    if(firstAnchorChild && isTextElement(firstAnchorChild))
+        firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
+    else
+        restoreSelection(selection, originalSelection);
+
     document.body.removeChild(node);
 }
 
@@ -85,8 +99,77 @@ const setString = (text) => {
     Clipboard.setString(text);
 };
 
+const isTextElement = (el) => {
+    if (el instanceof HTMLInputElement) {
+        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types
+        if (/|text|email|number|password|search|tel|url/.test(el.type || '')) {
+            return true;
+        }
+    }
+    if (el instanceof HTMLTextAreaElement)
+        return true;
+
+    return false;
+}
+
+// ref: https://stackoverflow.com/a/4931963/1174657
+const getInputSelection = (el) => {
+    var start = 0, end = 0, normalizedValue, range,
+        textInputRange, len, endRange;
+
+    if (typeof el.selectionStart == "number" && typeof el.selectionEnd == "number") {
+        start = el.selectionStart;
+        end = el.selectionEnd;
+    } else {
+        range = document.selection.createRange();
+
+        if (range && range.parentElement() == el) {
+            len = el.value.length;
+            normalizedValue = el.value.replace(/\r\n/g, "\n");
+
+            // Create a working TextRange that lives only in the input
+            textInputRange = el.createTextRange();
+            textInputRange.moveToBookmark(range.getBookmark());
+
+            // Check if the start and end of the selection are at the very end
+            // of the input, since moveStart/moveEnd doesn't return what we want
+            // in those cases
+            endRange = el.createTextRange();
+            endRange.collapse(false);
+
+            if (textInputRange.compareEndPoints("StartToEnd", endRange) > -1) {
+                start = end = len;
+            } else {
+                start = -textInputRange.moveStart("character", -len);
+                start += normalizedValue.slice(0, start).split("\n").length - 1;
+
+                if (textInputRange.compareEndPoints("EndToEnd", endRange) > -1) {
+                    end = len;
+                } else {
+                    end = -textInputRange.moveEnd("character", -len);
+                    end += normalizedValue.slice(0, end).split("\n").length - 1;
+                }
+            }
+        }
+    }
+
+    return {
+        start: start,
+        end: end,
+        direction: el.selectionDirection,
+    };
+}
+
+const saveSelection = (selection) => {
+    return [selection.anchorNode, selection.anchorOffset, selection.focusNode, selection.focusOffset];
+}
+
+const restoreSelection = (selection, savedSelection) => {
+    selection.setBaseAndExtent(savedSelection[0], savedSelection[1], savedSelection[2], savedSelection[3]);
+}
+
 export default {
     setString,
     canSetHtml,
     setHtml,
-};
+};
```

**Comment by mollfpr** [comment] 2023-01-20 11:42
Thanks for the proposal @wildan-m! Could you attach the full diff of your proposal?

>Note: custom getInputSelection seems complicated because it also handles IE's strange handling of line breaks. If we don't care about IE we can directly use selectionStart, selectionEnd and selectionDirection for our purpose.

Is `getInputSelection` will be used only for IE? But our `setHTMLSync` function is called specific for Safari. Could you clarify this?

**Comment by wildan-m** [comment] 2023-01-20 12:34
@mollfpr the diff is in `Changes` section of my proposal. If you need to review you can also check it in my branch

https://github.com/wildan-m/App/tree/wildan-14300-MessageGetUnselected

> Is getInputSelection will be used only for IE? But our setHTMLSync function is called specific for Safari. Could you clarify this?

It will be used for all browsers that use the setHTMLSync and it will also handle the special cases for IE.

If we don't want to support IE, then we can change it to:
```
const getInputSelection = (el) => {
     return {
         start: el.selectionStart,
         end: el.selectionEnd,
         direction: el.selectionDirection,
     }
}
```

**Comment by wildan-m** [comment] 2023-01-20 12:56
@mollfpr sure, here are my updated changes:


https://github.com/wildan-m/App/blob/wildan-14300-MessageGetUnselected/src/libs/Clipboard/index.js
```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626..367aa60c1 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -6,6 +6,32 @@ import * as Browser from '../Browser';
 
 const canSetHtml = () => lodashGet(navigator, 'clipboard.write');
 
+const isTextElement = (el) => {
+    if (el instanceof HTMLInputElement) {
+        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types
+        if (/|text|email|number|password|search|tel|url/.test(el.type || '')) {
+            return true;
+        }
+    }
+    if (el instanceof HTMLTextAreaElement) { return true; }
+
+    return false;
+};
+
+const getInputSelection = (el) => {
+    return {
+        start: el.selectionStart,
+        end: el.selectionEnd,
+        direction: el.selectionDirection,
+    }
+}
+
+const saveSelection = selection => [selection.anchorNode, selection.anchorOffset, selection.focusNode, selection.focusOffset];
+
+const restoreSelection = (selection, savedSelection) => {
+    selection.setBaseAndExtent(savedSelection[0], savedSelection[1], savedSelection[2], savedSelection[3]);
+};
+
 /**
  * Deprecated method to write the content as HTML to clipboard.
  * @param {String} html HTML representation
@@ -29,6 +55,13 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    let originalSelection = null;
+    const firstAnchorChild = selection.anchorNode.firstChild;
+
+    if (firstAnchorChild && isTextElement(firstAnchorChild)) {
+        originalSelection = getInputSelection(firstAnchorChild);
+    } else { originalSelection = saveSelection(selection); }
+
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -42,6 +75,11 @@ function setHTMLSync(html, text) {
     }
 
     selection.removeAllRanges();
+
+    if (firstAnchorChild && isTextElement(firstAnchorChild)) {
+        firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
+    } else { restoreSelection(selection, originalSelection); }
+
     document.body.removeChild(node);
 }
```

**Comment by anmurali** [comment] 2023-01-20 21:07
@wildan-m - I sent you an offer via Upwork

**Comment by mollfpr** [comment] 2023-01-20 21:09
@anmurali Let’s wait until @youssef-lr approves the proposal 😅

**Comment by anmurali** [comment] 2023-01-20 21:11
Ok I will leave it as hired, @wildan-m please wait till @youssef-lr posts here and then accept it.

**Comment by anmurali** [comment] 2023-01-23 22:17
@youssef-lr - bump on reviewing this please

**Comment by youssef-lr** [comment] 2023-01-24 01:48
The proposal looks good to me and tested well! @wildan-m please raise a PR and assign me as a reviewer, also to save some review time, please base it off this diff below, I went ahead and removed the extra functions as they are only used in one place, we don't need to create them.

```diff
diff --git a/src/libs/Clipboard/index.js b/src/libs/Clipboard/index.js
index efffd9626e..9d1fb5539d 100644
--- a/src/libs/Clipboard/index.js
+++ b/src/libs/Clipboard/index.js
@@ -6,6 +6,18 @@ import * as Browser from '../Browser';
 
 const canSetHtml = () => lodashGet(navigator, 'clipboard.write');
 
+const isTextElement = (el) => {
+    if (el instanceof HTMLInputElement) {
+        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types
+        if (/|text|email|number|password|search|tel|url/.test(el.type || '')) {
+            return true;
+        }
+    }
+    if (el instanceof HTMLTextAreaElement) { return true; }
+
+    return false;
+};
+
 /**
  * Deprecated method to write the content as HTML to clipboard.
  * @param {String} html HTML representation
@@ -29,6 +41,24 @@ function setHTMLSync(html, text) {
     document.body.appendChild(node);
 
     const selection = window.getSelection();
+    let originalSelection = null;
+    const firstAnchorChild = selection.anchorNode.firstChild;
+
+    if (firstAnchorChild && isTextElement(firstAnchorChild)) {
+        originalSelection = {
+            start: firstAnchorChild.selectionStart,
+            end: firstAnchorChild.selectionEnd,
+            direction: firstAnchorChild.selectionDirection,
+        };
+    } else {
+        originalSelection = {
+            anchorNode: selection.anchorNode,
+            anchorOffset: selection.anchorOffset,
+            focusNode: selection.focusNode,
+            focusOffset: selection.focusOffset,
+        };
+    }
+
     selection.removeAllRanges();
     const range = document.createRange();
     range.selectNodeContents(node);
@@ -42,6 +72,13 @@ function setHTMLSync(html, text) {
     }
 
     selection.removeAllRanges();
+
+    if (firstAnchorChild && isTextElement(firstAnchorChild)) {
+        firstAnchorChild.setSelectionRange(originalSelection.start, originalSelection.end, originalSelection.direction);
+    } else {
+        selection.setBaseAndExtent(originalSelection.anchorNode, originalSelection.anchorOffset, originalSelection.focusNode, originalSelection.focusOffset);
+    }
+
     document.body.removeChild(node);
 }
```

**Comment by wildan-m** [comment] 2023-01-24 06:15
@youssef-lr, @mollfpr, I've created [the PR](https://github.com/Expensify/App/pull/14506) including updates from the latest feedback. Please review it. Thank you

**Comment by mollfpr** [comment] 2023-01-24 11:02
Thanks, @wildan-m! I will review the PR within an hour.

**Comment by mollfpr** [comment] 2023-02-02 12:04
> [@mollfpr / @youssef-lr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/13396

> [@mollfpr / @youssef-lr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/13396#issuecomment-1413630194

**Comment by wildan-m** [comment] 2023-02-07 03:11
Hi, is there any regression caused by the PR?

**Comment by mollfpr** [comment] 2023-02-07 03:36
No mention in the PR so there’s no regression was reported.

@anmurali can we issue the payment here? Thanks!

**Comment by wildan-m** [comment] 2023-02-10 02:35
Bump @anmurali

**Comment by mollfpr** [comment] 2023-02-14 14:07
Bump again @anmurali

**Comment by kadiealexander** [comment] 2023-02-14 20:57
Hey team, I'll help out with this one. @mollfpr I've issued payment for you, @wildan-m and @hungvu193 I've sent contracts to you both. Please let me know when they've been accepted and I'll issue payment.

**Comment by wildan-m** [comment] 2023-02-14 22:05
@kadiealexander accepted the offer. Thank you

**Comment by kadiealexander** [comment] 2023-02-14 22:37
Paid with a speed bonus, thanks for your work here @wildan-m!

**Comment by wildan-m** [comment] 2023-02-14 22:59
> Paid with a speed bonus, thanks for your work here @wildan-m!

Awesome! You're welcome. Thanks for the payment and its bonus

**Comment by kadiealexander** [comment] 2023-02-15 00:03
Cool, everyone is paid! Will leave the BugZero Checklist for @mollfpr and @youssef-lr :)

**Comment by youssef-lr** [comment] 2023-02-27 15:39
@mollfpr I've edited the checklist, double check please if I missed something.

**Comment by mollfpr** [comment] 2023-02-27 15:54
@youssef-lr Yup, I agree with you! Thanks for the update on the checklist. We'll be able to close this out then.

**Closed** 2023-03-09 18:54 UTC
Labels: External, Weekly, Help Wanted, Overdue, Awaiting Payment, Bug
