### ISSUE TITLE
[$250]  Report layout distorted for mostly invoice type reports

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47608] opened 2024-08-18 13:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723897707932549

## Action Performed:
1. Go to staging.new.expensify.com
2. Click the Fab and create an Invoice
## Expected Result:
No visual issues after creating Invoice reports
## Actual Result:
Invoice report looks distorted
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bbaf70df-64de-4291-8050-483719575f45

![Snip - (6) New Expensify - Google Chrome](https://github.com/user-attachments/assets/384e86e0-05aa-4779-810c-1998ab7f21f2)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc208c0f633e111a</li>
        <li>Upwork Job ID: 1825580782358038372</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by isabelastisser** [comment] 2024-08-19 17:11
@davidcardoza, does this belong to vip-billpay?

**Comment by codewaseem** [comment] 2024-08-20 13:58
I think this is same as https://github.com/Expensify/App/issues/44388

**Comment by isabelastisser** [comment] 2024-08-21 17:29
thanks @suneox! hold for https://github.com/Expensify/App/issues/44388

**Comment by isabelastisser** [comment] 2024-09-03 20:16
Asked in Slack: https://expensify.slack.com/archives/CSL3XBCCR/p1725394548852899

**Comment by wildan-m** [comment] 2024-09-07 07:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mostly invoice type reports have distorted layout.

### What is the root cause of that problem?

REPORTPREVIEW created date is older than CREATED action, this makes REPORTPREVIEW shift to the top and distort the layout.

### What changes do you think we should make in order to solve the problem?
Ensure the REPORTPREVIEW created date newer than CREATE action created date.

Modify this step:

https://github.com/Expensify/App/blob/4af620b439636f714ff72a26320ed57f9d2faac3/src/libs/actions/IOU.ts#L1922-L1940

To 

```tsx
    // STEP 5: Build optimistic reportActions.
    const [optimisticCreatedActionForChat, optimisticCreatedActionForIOUReport, iouAction, optimisticTransactionThread, optimisticCreatedActionForTransactionThread] =
        ReportUtils.buildOptimisticMoneyRequestEntities(
            optimisticInvoiceReport,
            CONST.IOU.REPORT_ACTION_TYPE.CREATE,
            amount,
            currency,
            trimmedComment,
            receiver.login ?? '',
            [receiver],
            optimisticTransaction.transactionID,
            undefined,
            false,
            false,
            false,
        );

    // Set the created time for optimisticCreatedActionForChat
    optimisticCreatedActionForChat.created = DateUtils.getDBTime();

    const reportPreviewAction = ReportUtils.buildOptimisticReportPreview(chatReport, optimisticInvoiceReport, trimmedComment, optimisticTransaction);

    // Set the created time for reportPreviewAction to be after optimisticCreatedActionForChat
    reportPreviewAction.created = DateUtils.getDBTime(new Date().getTime() + 1000); // Adding 1 second to ensure it's after (Optional)

    optimisticInvoiceReport.parentReportActionID = reportPreviewAction.reportActionID;
    chatReport.lastVisibleActionCreated = reportPreviewAction.created;
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/47608-broken-invoice-layout?expand=1)
### What alternative solutions did you explore? (Optional)
Directly add 1 second to 

```tsx
     const reportPreviewAction = ReportUtils.buildOptimisticReportPreview(chatReport, optimisticInvoiceReport, trimmedComment, optimisticTransaction);
    

    // Set the created time for reportPreviewAction to be after optimisticCreatedActionForChat
    reportPreviewAction.created = DateUtils.getDBTime(new Date().getTime() + 1000); // Adding 1 second to ensure it's after (Optional)
```

**Comment by wildan-m** [comment] 2024-09-07 07:58
[Proposal Updated](https://github.com/Expensify/App/issues/47608#issuecomment-2335109216)

- describe add 1 second is optional, we already fixed the getDate call order

**Comment by suneox** [comment] 2024-09-09 17:12
@wildan-m Thank for your proposal, but currently this issue can not reproduce

**Comment by isabelastisser** [comment] 2024-09-09 18:34
Thanks for the update, @suneox! I will close the issue then.

**Closed by isabelastisser** 2024-09-09 18:34 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by wildan-m** [comment] 2024-09-09 22:19
@suneox it's already fixed

https://github.com/Expensify/App/blob/063cc10e7dc28ab99a2e659728202b1ea184db88/src/libs/ReportUtils.ts#L5721-L5723
