### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] Web - Login - App crashes when login to HT account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31803] opened 2023-11-23 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with HT account - [applausetester+mnchat1@applause.expensifail.com](mailto:applausetester+mnchat1@applause.expensifail.com)

## Expected Result:
Verify the UI has a loading "skeleton" state (offline avatar and placeholder lines) and loads after a few moments and the loading state is not visible anymore

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/906ac3af-4d84-4cbf-9e5c-0234f4118394

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eec53be34df7522e</li>
        <li>Upwork Job ID: 1735048003260628992</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-11-23 22:08
@kbecciv do you have any crash log or console error?

**Comment by luacmartins** [comment] 2023-11-23 22:15
I suspect it might be coming from this PR - https://github.com/Expensify/App/pull/31711. Gonna try to help @aldo-expensify reproduce this issue first

**Comment by luacmartins** [comment] 2023-11-23 22:18
Hmm actually, I'm seeing the crash log below without a HT account

![Screenshot 2023-11-23 at 3 18 02 PM](https://github.com/Expensify/App/assets/22219519/f652262f-667c-4db6-95b4-b0ecb58af00d)

**Comment by situchan** [comment] 2023-11-23 22:19
Seems like what @quinthar reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1700768086040859)

**Comment by luacmartins** [comment] 2023-11-23 22:22
Seems to come from this line - https://github.com/Expensify/App/blob/1163dc3837dfb04a985f3106026ede7b77108cca/src/libs/OptionsListUtils.js#L396

**Comment by situchan** [comment] 2023-11-23 22:23
https://github.com/Expensify/App/pull/31061 is candidate

**Comment by luacmartins** [comment] 2023-11-23 22:30
Yea, I'm trying to reproduce in dev

**Comment by aldo-expensify** [comment] 2023-11-23 22:49
> Seems to come from this line
> 
> https://github.com/Expensify/App/blob/1163dc3837dfb04a985f3106026ede7b77108cca/src/libs/OptionsListUtils.js#L396

For this to happen, we would need to fail to find the IOU here

https://github.com/Expensify/App/blob/36105a3d62c54b5430f674dc1d7ec3b7752ab8ae/src/libs/OptionsListUtils.js#L425-L431

**Comment by luacmartins** [comment] 2023-11-23 22:53
correct, this is the data I have. You can see that the reportID doesn't exist in `allSortedReportActions`

![Screenshot 2023-11-23 at 3 52 53 PM](https://github.com/Expensify/App/assets/22219519/e2a2c6b6-de3b-44d8-872c-871982305d85)

**Comment by aldo-expensify** [comment] 2023-11-23 22:57
Reproduced:

1. Have 2 accounts logged in different sessions and start a chat between them
2. Request money from one of them
3. The other received the pusher event and crash

Going to check if this happens in production

**Comment by aldo-expensify** [comment] 2023-11-23 23:01
hmm I have been only able to reproduce in dev, but not staging/production

**Comment by aldo-expensify** [comment] 2023-11-23 23:08
hmm, pusher events are not working anymore in my env...

**Comment by luacmartins** [comment] 2023-11-23 23:09
merge main on web-e, I just fixed it here - https://github.com/Expensify/Expensify/issues/338941

**Comment by aldo-expensify** [comment] 2023-11-23 23:16
This is the pusher events that cause the things to explode:

```
{
    "updates": [
        {
            "data": [
                {
                    "key": "report_3759538206565919",
                    "onyxMethod": "merge",
                    "value": {
                        "lastActorAccountID": 11033970,
                        "lastMentionedTime": null,
                        "lastMessageText": "$2.00 request",
                        "lastReadTime": null,
                        "lastVisibleActionCreated": "2023-11-23 23:11:15.398",
                        "maxSequenceNumber": 1,
                        "reportID": "3759538206565919"
                    }
                },
                {
                    "key": "reportActions_3759538206565919",
                    "onyxMethod": "merge",
                    "shouldNotify": true,
                    "value": {
                        "9135915664676949581": {
                            "actionName": "IOU",
                            "actorAccountID": 11033970,
                            "automatic": false,
                            "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_19.png",
                            "childReportID": 1130822545444080,
                            "childType": "chat",
                            "created": "2023-11-23 23:11:15.398",
                            "isAttachment": false,
                            "lastModified": "2023-11-23 23:11:15.398",
                            "message": [
                                {
                                    "html": "$2.00 request",
                                    "isDeletedParentAction": false,
                                    "isEdited": false,
                                    "reactions": [],
                                    "text": "$2.00 request",
                                    "type": "COMMENT",
                                    "whisperedTo": []
                                }
                            ],
                            "originalMessage": {
                                "IOUReportID": 3759538206565919,
                                "IOUTransactionID": "1282493847044555760",
                                "amount": 200,
                                "comment": "",
                                "currency": "USD",
                                "lastModified": "2023-11-23 23:11:15.398",
                                "participantAccountIDs": [
                                    11033970,
                                    11033972
                                ],
                                "type": "create"
                            },
                            "person": [
                                {
                                    "style": "strong",
                                    "text": "test-moneyreq@expensifail.com",
                                    "type": "TEXT"
                                }
                            ],
                            "previousReportActionID": "7277686818659270939",
                            "reportActionID": "9135915664676949581",
                            "reportActionTimestamp": 1700781075398,
                            "sequenceNumber": 1,
                            "shouldShow": true,
                            "timestamp": 1700781075,
                            "whisperedToAccountIDs": []
                        }
                    }
                },
                {
                    "key": "report_3759538206565919",
                    "onyxMethod": "merge",
                    "value": {
                        "chatReportID": "5721531069860615",
                        "chatType": "",
                        "currency": "USD",
                        "description": null,
                        "hasOutstandingChildRequest": false,
                        "hasOutstandingIOU": true,
                        "hasParentAccess": true,
                        "iouReportID": null,
                        "isDeletedParentAction": null,
                        "isOwnPolicyExpenseChat": false,
                        "isPinned": false,
                        "isWaitingOnBankAccount": false,
                        "lastActorAccountID": 11033970,
                        "lastMentionedTime": null,
                        "lastMessageHtml": "$2.00 request",
                        "lastMessageText": "$2.00 request",
                        "lastReadSequenceNumber": 0,
                        "lastReadTime": null,
                        "lastVisibleActionCreated": "2023-11-23 23:11:15.398",
                        "lastVisibleActionLastModified": "2023-11-23 23:11:15.398",
                        "managerID": 11033972,
                        "nonReimbursableTotal": 0,
                        "notificationPreference": "always",
                        "oldPolicyName": "",
                        "ownerAccountID": 11033970,
                        "parentReportActionID": "5628178967538067842",
                        "parentReportID": "5721531069860615",
                        "participantAccountIDs": [
                            11033972,
                            11033970
                        ],
                        "policyID": "769D1BB08FEC917C",
                        "policyName": null,
                        "reportID": "3759538206565919",
                        "reportName": "IOU",
                        "stateNum": 1,
                        "statusNum": 1,
                        "submitterPayPalMeAddress": "",
                        "total": 200,
                        "type": "iou",
                        "visibility": null,
                        "visibleChatMemberAccountIDs": [],
                        "welcomeMessage": "",
                        "writeCapability": "all"
                    }
                },
                {
                    "key": "report_5721531069860615",
                    "onyxMethod": "merge",
                    "value": {
                        "iouReportID": "3759538206565919",
                        "participantAccountIDs": [
                            11033970
                        ]
                    }
                },
                {
                    "key": "transactions_1282493847044555760",
                    "onyxMethod": "merge",
                    "value": {
                        "amount": 200,
                        "billable": false,
                        "cardID": 11051,
                        "category": "",
                        "comment": {
                            "comment": ""
                        },
                        "created": "2023-11-23",
                        "currency": "USD",
                        "filename": "",
                        "hasEReceipt": false,
                        "merchant": "Request",
                        "modifiedAmount": 0,
                        "modifiedCreated": "",
                        "modifiedCurrency": "",
                        "modifiedMerchant": "",
                        "originalAmount": 0,
                        "originalCurrency": "",
                        "parentTransactionID": "",
                        "receipt": [],
                        "reimbursable": true,
                        "reportID": "3759538206565919",
                        "status": "Posted",
                        "tag": "",
                        "transactionID": "1282493847044555760"
                    }
                },
                {
                    "key": "report_5721531069860615",
                    "onyxMethod": "merge",
                    "value": {
                        "hasOutstandingChildRequest": true
                    }
                },
                {
                    "key": "report_5721531069860615",
                    "onyxMethod": "merge",
                    "value": {
                        "lastActorAccountID": 11033972,
                        "lastMentionedTime": null,
                        "lastMessageText": "test-moneyreq3@expensifail.com owes $2.00",
                        "lastReadTime": "2023-11-23 23:11:15.408",
                        "lastVisibleActionCreated": "2023-11-23 23:11:15.408",
                        "maxSequenceNumber": 2,
                        "reportID": "5721531069860615"
                    }
                },
                {
                    "key": "reportActions_5721531069860615",
                    "onyxMethod": "merge",
                    "shouldNotify": true,
                    "value": {
                        "5628178967538067842": {
                            "actionName": "REPORTPREVIEW",
                            "actorAccountID": 11033972,
                            "automatic": false,
                            "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png",
                            "childMoneyRequestCount": 1,
                            "childReportID": 3759538206565919,
                            "childStateNum": 1,
                            "childStatusNum": 1,
                            "childType": "iou",
                            "created": "2023-11-23 23:11:15.408",
                            "isAttachment": false,
                            "lastModified": "2023-11-23 23:11:15.408",
                            "message": [
                                {
                                    "html": "test-moneyreq3@expensifail.com owes $2.00",
                                    "isDeletedParentAction": false,
                                    "isEdited": false,
                                    "reactions": [],
                                    "text": "test-moneyreq3@expensifail.com owes $2.00",
                                    "type": "COMMENT",
                                    "whisperedTo": []
                                }
                            ],
                            "originalMessage": {
                                "lastModified": "2023-11-23 23:11:15.408",
                                "linkedReportID": "3759538206565919"
                            },
                            "person": [
                                {
                                    "style": "strong",
                                    "text": "test-moneyreq3@expensifail.com",
                                    "type": "TEXT"
                                }
                            ],
                            "previousReportActionID": "6783530264347664382",
                            "reportActionID": "5628178967538067842",
                            "reportActionTimestamp": 1700781075408,
                            "sequenceNumber": 2,
                            "shouldShow": true,
                            "timestamp": 1700781075,
                            "whisperedToAccountIDs": []
                        }
                    }
                }
            ],
            "eventType": "onyxApiUpdate"
        }
    ],
    "lastUpdateID": "7550",
    "previousUpdateID": "7544"
}
```

We can see here:

- `REPORTPREVIEW` is inserted to onyx in key `reportActions_5721531069860615`. This has `"linkedReportID": "3759538206565919"`
- In the same Onyx event, another update inserts the IOU report `3759538206565919`

I think the problem is that the `REPORTPREVIEW` gets inserted causing a re-render before the IOU report is inserted. I think we should just update the front end code so it doesn't crash and display something else while we don't find the IOU report

**Comment by luacmartins** [comment] 2023-11-23 23:21
Sounds good, wanna work on a fix?

**Comment by aldo-expensify** [comment] 2023-11-23 23:24
@luacmartins what are your thoughts on: https://github.com/Expensify/App/pull/31806 🙏

**Comment by luacmartins** [comment] 2023-11-23 23:28
hmm but in the log I linked above iouReport is defined, we just don't have any reportAction for it in Onyx

**Comment by aldo-expensify** [comment] 2023-11-23 23:32
> hmm but in the log I linked above iouReport is defined, we just don't have any reportAction for it in Onyx

Which log? this? https://github.com/Expensify/App/issues/31803#issuecomment-1824979383

**Comment by aldo-expensify** [comment] 2023-11-23 23:34
When I reproduced, `iouReport` was not found and then `ReportUtils.getReport` returns `{}`. I mean this line:

```
const iouReport = ReportUtils.getReport(ReportActionUtils.getIOUReportIDFromReportActionPreview(lastReportAction));
```

**Comment by luacmartins** [comment] 2023-11-24 00:09
> correct, this is the data I have. You can see that the reportID doesn't exist in `allSortedReportActions` and `lastIOUMoneyReport` is undefined
> 
> 
> 
> ![Screenshot 2023-11-23 at 3 52 53 PM](https://github.com/Expensify/App/assets/22219519/e2a2c6b6-de3b-44d8-872c-871982305d85)
> 
> 

I logged this when logging into my account in staging. We can see a full iouReport there and it's present in Onyx, but that same report has no reportAction in Onyx

**Comment by aldo-expensify** [comment] 2023-11-24 00:12
and did it crash that time you logged in? The version of the crash I reproduced doesn't happen after login in, maybe it can happen in more than one way?

**Comment by luacmartins** [comment] 2023-11-24 00:20
Yes, I'm in mobile but I can record a video when I get back

**Comment by aldo-expensify** [comment] 2023-11-24 00:25
I think it would be good to know in your case if the `reportActions` for the IOU load at some point, regardless of the crash. If it is just that during that render they were not available, but in the next one they would have been, the fix in the PR https://github.com/Expensify/App/pull/31806 would work. If the `reportActions` never load, then it is a different problem

**Comment by luacmartins** [comment] 2023-11-24 00:30
They never seemed to load because refreshing the page didn't fix the issue. So maybe we do have multiple issues here.

**Comment by aldo-expensify** [comment] 2023-11-24 00:40
> They never seemed to load because refreshing the page didn't fix the issue. So maybe we do have multiple issues here.

😢

**Comment by aldo-expensify** [comment] 2023-11-24 00:44
I see that the reportActions for the IOU come in the OpenApp request for me when I login. I'll check the backend code and see if I can find a case where we don't load these reportActions.

**Comment by aldo-expensify** [comment] 2023-11-24 00:58
Does your IOU have a `parentReportActionID`?

**Comment by aldo-expensify** [comment] 2023-11-24 01:04
hmm login in into the account having the issue here could help with debugging, but I'm getting a [second verification](https://expensify.slack.com/archives/C9YU7BX5M/p1700787750319769) that I can't pass

**Comment by luacmartins** [comment] 2023-11-24 01:10
Here's a video. Refreshing the page results in the same error:

https://github.com/Expensify/App/assets/22219519/d4b232c4-85e2-478d-a9a0-0f46419c3772

**Comment by luacmartins** [comment] 2023-11-24 01:14
Hmm my call to OpenApp doesn't return reportActions for that reportID 8668808441392607:

![Screenshot 2023-11-23 at 6 13 36 PM](https://github.com/Expensify/App/assets/22219519/141f3609-d2de-4c3f-9834-325b323b7f90)

**Comment by aldo-expensify** [comment] 2023-11-24 01:40
I have been debugging the account [applausetester+mnchat1@applause.expensifail.com](mailto:applausetester+mnchat1@applause.expensifail.com)

And I think I have narrowed down the problematic report to:

```
[
    {
        "reportID": 4259526448723151,
        "isPinned": false,
        "isThread": true,
        "isArchivedRoom": false,
        "type": "expense",
        "chatType": null,
        "parentReportActionID": "2332071123794222759",
        "parentReportID": "3003828422686844",
        "isOwnPolicyExpenseChat": false,
        "lastRead": "2023-10-09 19:26:04.831",
        "lastActionCreated": "2023-10-26 19:52:25.210",
        "reportName": "Request",
        "sharedReportList": [
            {
                "accountID": 11357510,
                "email": "applausetester+mnchat1@applause.expensifail.com",
                "permissions": "read, write"
            },
            {
                "accountID": 7976487,
                "email": "andres.serna@team.expensify.com",
                "permissions": "read, write"
            }
        ],
        "participants": [
            "andres.serna@team.expensify.com",
            "applausetester+mnchat1@applause.expensifail.com"
        ],
        "managerID": 0,
        "managerEmail": "__fake__",
        "lastActionType": "IOU",
        "ownerAccountID": 11124256,
        "reportNameValuePairs": {
            "expensify_policyID": "8F5F364CB02B8264",
            "lastNotifiedReportActionTimestamp": "2023-10-26 19:52:25.210",
            "lastReadTime_11357510": "2023-10-09 19:26:04.831",
            "lastReadTime_7976487": "2023-10-26 19:52:25.210",
            "oldPolicyName": "",
            "parentReportActionID": "2332071123794222759",
            "parentReportID": "3003828422686844",
            "type": "expense"
        },
        "state": 2,
        "status": 4
    }
]
```

This the only expense/iou report that has managerID = 0, which would cause the code to try to access `reportAction.actorAccountID` in the line `report.managerID || reportAction.actorAccountID`

This report is in a free workspace, so I'll try to play with that to see if it happens. What kind of report is it in you case @luacmartins ?

**Comment by aldo-expensify** [comment] 2023-11-24 02:22
There are two things that are unexpected and I haven't been able to replicate:

- Expense report in a workspace with managerID = 0, how did it lose the manager?
- reportActions not loading for an iou/expense report during OpenApp

**Comment by aldo-expensify** [comment] 2023-11-24 02:32
uggh I think I found something that was confusing me a lot. Somehow, the code [here](https://github.com/Expensify/App/blob/87608953848bbbc2a6c9958cdc2d06a9a0e2ff39/src/libs/OptionsListUtils.js#L429-L436) was able to find the IOU reportActions, even when they were not in Onyx

Now I see that we have this collection `allSortedReportActions` that we never clean up, not even during logout, so I had dirty data there from previous sessions:

https://github.com/Expensify/App/pull/20223/files#diff-733528d957ae6a80eb863637fa5d54278c89c6121998f3574fa8c0aba935daebR90

**Comment by aldo-expensify** [comment] 2023-11-24 02:36
> reportActions not loading for an iou/expense report during OpenApp

I was able to cause this by removing the `parentReportActionID` NVPs that pointed to the IOU action of the iou/expense report. This `parentReportActionID` is tied to the chat report we create per transaction. If you clean it, then OpenApp doesn't load anymore the reportActions for the iou/expense report.

This is not enough to cause the crash, we also need the managerID to be 0.

**Comment by aldo-expensify** [comment] 2023-11-24 02:36
Its the end of the day here, I'll continue tomorrow, this is a deploy blocker, but I don't think we plan to deploy tomorrow and is not a main flow I believe.

**Comment by mountiny** [comment] 2023-11-24 10:11
@koko57 i think that make sense to be safe.

@aldo-expensify i think i have seen that the reports might be missing the managerID if they have been created from oldDot. But newDot expects to have the managerID in place correctly.

For example i believe the GBR does not work for the admin if they are not set as manager on the report

**Comment by koko57** [comment] 2023-11-24 12:33
should I mark the PR ready for review? I've also tested the case with workspace - the fix works fine

**Comment by aldo-expensify** [comment] 2023-11-24 17:42
Thanks @koko57 and @mountiny for fixing it!

**Comment by aldo-expensify** [comment] 2023-11-24 17:59
I logged in with the account [applausetester+mnchat1@applause.expensifail.com](mailto:applausetester+mnchat1@applause.expensifail.com) and it didn't crash

I also verified that the expense report  `4259526448723151` doesn't have reportActions and that its managerID is 0, so I think this is the case when it crashes at login.

**Comment by aldo-expensify** [comment] 2023-11-24 18:00
And thanks @luacmartins for the help yesterday!

**Comment by aldo-expensify** [comment] 2023-12-06 21:16
I think there is no payment to be issues here, I'll just close this since the offending PR was reverted.

**Comment by allroundexperts** [comment] 2023-12-09 02:09
Hi @aldo-expensify!

I reviewed https://github.com/Expensify/App/pull/31817 and my payment is still pending. Can you please write a payment summary? Thanks

**Comment by aldo-expensify** [comment] 2023-12-12 15:35
@muttmuure added `Bug` because we need to process @allroundexperts 's payment for reviewing PR https://github.com/Expensify/App/pull/31817

This issue is about a regression caused by PR: https://github.com/Expensify/App/pull/31061

**Comment by allroundexperts** [comment] 2023-12-12 15:37
Thanks @aldo-expensify. Can you please write a payment summary?

**Comment by mallenexpensify** [comment] 2023-12-13 21:25
@allroundexperts can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01eec53be34df7522e

Pay should be $500 for the review, I believe.  @muttmuure

**Comment by mallenexpensify** [comment] 2023-12-13 21:28
Contributor+: @allroundexperts owed $500 via NewDot

**Comment by mallenexpensify** [comment] 2023-12-13 21:29
@allroundexperts can you complete the BZ checklist? Thx

**Comment by allroundexperts** [comment] 2023-12-14 01:46
## Checklist

1. This bug was caused by https://github.com/Expensify/App/pull/31061. The author is aware of this bug.
2. N/A
3. N/A
4. I think a regression test is not needed here because this involved a crash after just logging in to an account. This should be already covered in prior test cases.

**Comment by JmillsExpensify** [comment] 2023-12-14 05:09
$500 payment approved for @allroundexperts based on summary above.

**Comment by aldo-expensify** [comment] 2023-12-18 15:51
@allroundexperts did you receive your payment?

**Comment by mallenexpensify** [comment] 2023-12-19 04:44
This should all be wrapped up, so closing.  Reply if you disagree!

**Closed by mallenexpensify** 2023-12-19 04:44 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
