### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] @expensify.sms is shown in money request preview to a user with phone number login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19500] opened 2023-05-23 22:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Request money from a user with phone number as their username/login
2. Notice the preview shows the phone number with @expensify.sms

## Expected results: 
@expensify.sms should not be shown
# Actual results: 
@expensify.sms is shown
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/090cbbc2-d406-4f8a-94dc-18300e2da23b)

<img width="956" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/f2632ce9-d7b1-4b22-8513-49801aa99ad0">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684687294956929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd7a65ee362d3cbf</li>
        <li>Upwork Job ID: 1661385702706524160</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by bogoroh** [comment] 2023-05-24 03:20
<img width="710" alt="Screenshot 2023-05-23 at 10 20 24 PM" src="https://github.com/Expensify/App/assets/4615263/cfc3c848-466f-4bda-bd5f-4d4229b025f3">
We seem to add this for all login with phone number. Is this not correct?

**Comment by bogoroh** [comment] 2023-05-24 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are appending "@expensify.sms" at the end of the phone number. 

### What is the root cause of that problem? 
When an account gets created we do run a method to append this to the end of the phone number. The lodashGet method to render this text is usually the DB response to render and has the nice translated format as a fallback. I believe it should be the other way around.

https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/components/ReportActionItem/ReportPreview.js#L120

#### Fix screenshots
<img width="499" alt="Screenshot 2023-05-23 at 10 31 22 PM" src="https://github.com/Expensify/App/assets/4615263/768e3334-5ab3-493a-a32a-295fc07fb9ff">
<img width="750" alt="Screenshot 2023-05-23 at 10 31 27 PM" src="https://github.com/Expensify/App/assets/4615263/028a0465-2431-40a3-b3c7-f3001c1834c4">

### What changes do you think we should make in order to solve the problem?
We should update the fallback to be the direct DB response and let the primary option be translated and nicely formatted.

We should do this for iou.payerSettled as well
`{props.translate('iou.payerOwesAmount', {payer: managerName, amount: reportAmount}) || lodashGet(message, 'html')}`



### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment] 2023-05-24 14:36
@parasharrajat - looks like we already have some proposed fixes for this one 👍

**Comment by maddylewis** [comment] 2023-05-30 14:17
@parasharrajat - what are you thinking about @dhairyasenjaliya's most recent suggestion? https://github.com/Expensify/App/issues/19500#issuecomment-1564842487

**Comment by maddylewis** [comment] 2023-06-05 13:36
@parasharrajat will have an update on next steps this week 👍

**Comment by maddylewis** [comment] 2023-06-08 13:54
@parasharrajat - let me know your thoughts on the existing proposals or if we should update the offer for this issue. thanks!

**Comment by mountiny** [comment] 2023-06-12 20:32
There is another Pr I believe where @hoangzinh might want to remove it, cant find the link just now.

I think we dont have to keep it that way, it was a hot fix for one bug, but its fine to take a different appraoch if argued well.

@parasharrajat given this issue is already 3 weeks old can we prioritize picking a solution? Thanks!

**Comment by maddylewis** [comment] 2023-06-14 00:18
hiya @dylanexpensify - i am OOO until June 20. 

we're seemingly still trying to find the best solution for this one - https://github.com/Expensify/App/issues/19500#issuecomment-1588048005

it sounds like @parasharrajat is reviewing the issue that @hoangzinh mentioned here - https://github.com/Expensify/App/issues/19500#issuecomment-1588816645, and then we'll go from there. 

since this is already 3 weeks old, i suppose we could reach out to callstack/swm on Thursday or Friday if we haven't decided on a solution. 

I'll snag this one back from you once i return - thanks!

**Comment by mountiny** [comment] 2023-06-14 16:22
@parasharrajat @hoangzinh any update here?

**Comment by dylanexpensify** [comment] 2023-06-19 08:33
Let us know what you're thinking @parasharrajat !

**Comment by maddylewis** [comment] 2023-06-20 15:21
back from OOO - snagging this one back! 

thanks @dylanexpensify!

**Comment by mountiny** [comment] 2023-06-20 18:14
I agree this might fix it, lets retest it once @hoangzinh resolves the merge conflicts.

**Comment by mountiny** [comment] 2023-06-23 14:53
I iwll be ooo next week but this should be fine over the course of that time

**Comment by maddylewis** [comment] 2023-06-26 13:42
waiting for this PR to merge to see if that fixes this one - https://github.com/Expensify/App/pull/20446

**Comment by maddylewis** [comment] 2023-06-27 17:04
PR is still open / in review.

**Comment by maddylewis** [comment] 2023-06-30 13:04
okay, it looks like this is merged - https://github.com/Expensify/App/pull/20446

@parasharrajat are you able to confirm if this issue is still outstanding after the linked PR was merged?

**Comment by maddylewis** [comment] 2023-07-05 13:09
thanks @parasharrajat!

**Comment by mountiny** [comment] 2023-07-06 02:15
@parasharrajat could you also check if this change will help with this? https://github.com/Expensify/App/pull/21578

**Comment by mountiny** [comment] 2023-07-10 20:27
This is still on hold

**Comment by maddylewis** [comment] 2023-07-19 20:39
i believe this is still on hold

**Comment by mountiny** [comment] 2023-07-19 21:03
I think it does not have to be on hold anymore, can we retest it actually? @maddylewis @parasharrajat thanks!

**Comment by mountiny** [comment] 2023-07-20 16:11
@parasharrajat @bernhardoj can you retest this to confirm if its still an issue?

**Comment by mountiny** [comment] 2023-07-20 19:20
@robertjchen so this is fixed right?

**Comment by maddylewis** [comment] 2023-07-21 16:59
offer sent!

**Comment by maddylewis** [comment] 2023-07-21 18:21
@bernhardoj has been paid. since it looks like this is no longer an issue, am i good to close this one out?

**Closed** 2023-07-21 19:31 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
