### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] LHN - RBR appears on the wrong workspace chat for an error occurring on another workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47874] opened 2024-08-22 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1097@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to Old Dot and sign up with a new account
2. Go to settings > Account and validate the account
3. Navigate to staging.new.expensify.com and sign in with the same account signed in on Old Dot
4. Create a workspace and name it as "Workspace 1" to make things easier to notice
5. Go to workspace editor and enable workflows
6. Go to workflows and enable delayed submission and set it to manual and enable approvals also
7. Create another workspace and name it as "Workspace 2"
8. Navigate to Workspace 1 chat and create a manual expense
9. Click on submit but do not click on approve
10. Navigate to Old dot and refresh the page
11. Go to reports and click on the expense created on ND
12. Click on detail and change the workspace from workspace 1 to workspace 2
13. Go to New dot and wait for a few seconds for the change to take effect
14. After the changes took effect (Workspace 1 will not have RBR on the LHN and instead workspace 2 will have RBR and the expense will be moved to it)
15. Go to workspace chat 2 and create a scan expense with a normal picture so that it will throw error after it is done scanning
16. Observe the LHN of workspace chat 1 on the LHN

## Expected Result:
No RBR will be present on the workspace chat 1

## Actual Result:
RBR is present on workspace chat 1 even if the scan expense which has an error is on the workspace chat 2. When opening the workspace chat 1 with RBR there is nothing inside the workspace chat.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a55bb442-598c-44df-8fa9-7fab7a178439

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a69a9ddbd29631a</li>
        <li>Upwork Job ID: 1828511929613408564</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment] 2024-08-22 16:55
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment] 2024-08-27 19:16
Reproduced, opening up.

**Comment by SIMalik** [comment] 2024-09-03 04:57
**_Proposal_**

**Please re-state the problem that we are trying to solve in this issue.**
The Left-Hand Navigation (LHN) - Red Brick Road (RBR) indicator is incorrectly appearing in a workspace chat due to an error originating in a different workspace.

**What is the root cause of that problem?**
At Step-9, during the SubmitReport response, the following REPORTPREVIEW action was received for iouReportID: "5726784747188717" in Workspace 77-1: [Complete SubmitReport Response](https://github.com/user-attachments/files/16839154/Workspace77-1-First-SubmitReport.json).

```
        {
            "key": "reportActions_2380165600597457",
            "onyxMethod": "merge",
            "value": {
                "5238883410418754601": {
                    "actionName": "REPORTPREVIEW",
                    "actorAccountID": 18253981,
                    "avatar": "https:\/\/[d2k5nsl2zxldvw.cloudfront.net](http://d2k5nsl2zxldvw.cloudfront.net/)\/images\/avatars\/default-avatar_14.png",
                    "childCommenterCount": 0,
                    "childLastActorAccountID": 18253981,
                    "childLastMoneyRequestComment": "",
                    "childLastReceiptTransactionIDs": "",
                    "childLastVisibleActionCreated": "",
                    "childMoneyRequestCount": 1,
                    "childOldestFourAccountIDs": "",
                    "childRecentReceiptTransactionIDs": [],
                    "childReportNotificationPreference": "hidden",
                    "childType": "expense",
                    "childVisibleActionCount": 0,
                    "created": "2024-09-02 05:16:26.449",
                    "lastModified": "2024-09-02 05:16:26.449",
                    "message": [
                        {
                            "html": "Workspace 77-1 owes Rs\u00a05.00",
                            "text": "Workspace 77-1 owes Rs\u00a05.00",
                            "type": "COMMENT",
                            "whisperedTo": []
                        }
                    ],
                    "originalMessage": {
                        "lastModified": "2024-09-02 05:16:26.449",
                        "linkedReportID": "5726784747188717"
                    },
                    "person": [
                        {
                            "style": "strong",
                            "text": "O77F O77L",
                            "type": "TEXT"
                        }
                    ],
                    "reportActionID": "5238883410418754601",
                    "shouldShow": true
                }
```
At Step-14, the reportActionID: "5238883410418754601" was marked as deleted in Workspace 77-1:  [[Complete OpenReport Response](https://github.com/user-attachments/files/16842595/Workspace77-1OpenReport.json)]
```
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "",
                            "text": "",
                            "isEdited": false,
                            "whisperedTo": [],
                            "isDeletedParentAction": false,
                            "deleted": "2024-09-02 05:40:23.154"
                        }
                    ],
                    "originalMessage": {
                        "deleted": "2024-09-02 05:40:23.154",
                        "lastModified": "2024-09-02 05:16:26.449",
                        "linkedReportID": "5726784747188717"
                    },
```
Simultaneously, the iouReport (ID: "5726784747188717") was shifted to Workspace 77-2 with a new reportActionID: 7661044324410620555. [[Complete OpenReport Response](https://github.com/user-attachments/files/16842727/Workspace77-2OpenReport.json)]

However, the deleted reportActionID: "5238883410418754601" remains linked to Workspace 77-1. Now when Workspace77-1 try process it, it follows the following steps to find the errors

https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/OptionsListUtils.ts#L744

https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/OptionsListUtils.ts#L492

https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/ReportUtils.ts#L7067

And at following line it has wrongly picked the linkedReportID: "5726784747188717"  which is an ID of iouReport and has been shifted in second Workspace 77-2
https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/ReportActionsUtils.ts#L921

Due to this wrong IOUReportID 5726784747188717 of Workspace 77-2 following line return true and causing to show RBR
```
shouldShowRBRForMissingSmartscanFields(IOUReportID)
```
https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/ReportUtils.ts#L7068


**What changes do you think we should make in order to solve the problem?**
Replace
https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/ReportUtils.ts#L7062-L7063
With

```
function hasSmartscanError(reportActions: ReportAction[]) {
    const nonDeletedReportActions = reportActions.filter(action => !ReportActionsUtils.isDeletedAction(action));

    return nonDeletedReportActions.some((action) => {
```

**What alternative solutions did you explore?**
If we expect getIOUReportIDFromReportActionPreview to always return a non-deleted reportAction ID, we should modify the function directly.

Replace
https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/ReportActionsUtils.ts#L917-L922
With

```
 /**
  * Get the iouReportID for a given report action.
 */
function getIOUReportIDFromReportActionPreview(reportAction: OnyxEntry<ReportAction>): string {
    return isActionOfType(reportAction, CONST.REPORT.ACTIONS.TYPE.REPORT_PREVIEW) && !isDeletedAction(reportAction)? getOriginalMessage(reportAction)?.linkedReportID ?? '-1' : '-1';
}
```

**After Code Change:**
Local:
![47874-withoutRBR](https://github.com/user-attachments/assets/364d26d4-a7ae-4ff5-9034-ba5ce8c340ac)

**Comment by SIMalik** [comment] 2024-09-05 20:29
@garrettmknight @ntdiary

1.
> @SIMalik, curious how did you start analyzing from the code below? Which component in the OP called this createOption function?

The getAllReportErrors function is called in multiple parts of the app. Specifically, when we click on a scanned expense that has or will have violations, it follows the following path to trigger the function.
 
https://github.com/Expensify/App/blob/156b8b0da67d1df00b2dbc0aa0f25ed2f03f9ef3/src/hooks/useReportIDs.tsx#L98-L114
https://github.com/Expensify/App/blob/156b8b0da67d1df00b2dbc0aa0f25ed2f03f9ef3/src/libs/SidebarUtils.ts#L108
https://github.com/Expensify/App/blob/2c041292660d1d3b04cb2e19a72b56d16e70ef52/src/libs/OptionsListUtils.ts#L492

https://github.com/user-attachments/assets/aed3e3cc-af00-463e-bcb0-c913ac0f2937


2.
> As for the solution, if we decide to modify hasSmartscanError, I would prefer to
function hasSmartscanError(reportActions: ReportAction[]) {
    return reportActions.some((action) => {
        if (!ReportActionsUtils.isDeletedAction(action)) {
            return false
        }
// or
function hasSmartscanError(reportActions: ReportAction[]) {
    return reportActions.some((action) => {
        if (!ReportActionsUtils.shouldReportActionBeVisible(action, action.reportActionID)) {
            return false
        }
 
 Yes, we can modify the function      
https://github.com/Expensify/App/blob/156b8b0da67d1df00b2dbc0aa0f25ed2f03f9ef3/src/libs/ReportUtils.ts#L7075-L7080

to:
```
function hasSmartscanError(reportActions: ReportAction[]) {
    return reportActions.some((action) => {
        if ((!ReportActionsUtils.isSplitBillAction(action) && !ReportActionsUtils.isReportPreviewAction(action)) || ReportActionsUtils.isDeletedAction(action)) {
            return false;
        }
        const IOUReportID = ReportActionsUtils.getIOUReportIDFromReportActionPreview(action);
```
>Additionally, these two RBRs should also not be displayed when switching to workspace 1

1. The RBR for Workspace 1 is no longer displayed.
2. **Left Bottom RBR:**
This seems to be a separate issue, unrelated to the workspace. The RBR appears in other cases as well, as shown in the video. However, if you'd prefer to address it here, I can investigate further. Otherwise, we can raise a separate issue for it.

https://github.com/user-attachments/assets/ad5167d5-b7db-4a5a-877b-f31abbbc7a34

**Comment by SIMalik** [comment] 2024-09-09 14:41
Contributor details
Your Expensify account email: f18ba010@ibitpu.edu.pk
Upwork Profile Link: https://www.upwork.com/freelancers/~0111172c8e8a5b3f55?viewMode=1

**Comment by neil-marcellini** [comment] 2024-09-10 23:08
> OK, I think we can move forward with @SIMalik's [proposal](https://github.com/Expensify/App/issues/47874#issuecomment-2325602648).

Cool, I agree. They did a good job finding the root cause.

> Furthermore, if we don’t want to collect any errors related to deleted `reportActions`, we can also filter `reportActions` directly in `getAllReportErrors`.

I think we should take this approach because it seems the most simple. If an action is deleted I don't think it should be causing an error.

**Comment by SIMalik** [comment] 2024-09-11 07:44
Contributor details
Expensify account email: f18ba010@ibitpu.edu.pk
Upwork Profile Link: https://www.upwork.com/freelancers/~01511dd712b8a399be?viewMode=1

**Comment by SIMalik** [comment] 2024-09-12 17:45
Hi @neil-marcellini, @ntdiary,

The code has been updated as per your suggestions. I made the change according to the new code. Specifically, I replaced the following line:
https://github.com/Expensify/App/blob/d389de2c9a6ae0d51d03fea9edcfe78d0dd88861/src/libs/OptionsListUtils.ts#L474

with

```
const reportActionsArray = Object.values(reportActions ?? {}).filter(action => !ReportActionsUtils.isDeletedAction(action));

```
This ensures we are only processing non-deleted reportActions, as suggested. Let me know if this aligns with your expectations.

Thanks!

https://github.com/user-attachments/assets/06791eb9-2e6d-4cf2-9cd9-517ceefeb3fb

**Comment by neil-marcellini** [comment] 2024-10-09 17:35
How's this going? When you do you think the PR will be ready?

**Comment by SIMalik** [comment] 2024-10-26 05:06
Hi @neil-marcellini, @ntdiary

I hope this message finds you well. Please see the following details regarding the job offer on Upwork, which I have yet to receive. Could you kindly assist with any necessary actions to help move this forward?


https://github.com/Expensify/App/issues/47874#issuecomment-2338315958 melvin-bot:
> Unable to store contributor details.

https://github.com/Expensify/App/issues/47874#issuecomment-2342315624 melvin-bot:
> The BZ member will need to manually hire SIMalik for the Contributor role. Please store your Upwork details and apply to our Upwork job so this process is automatic in the future!


https://github.com/Expensify/App/issues/47874#issuecomment-2342900925
[SIMalik](https://github.com/SIMalik) commented [on Sep 11](https://github.com/Expensify/App/issues/47874#issuecomment-2342900925)

> Contributor details 
Expensify account email: [f18ba010@ibitpu.edu.pk](mailto:f18ba010@ibitpu.edu.pk) 
Upwork Profile Link: https://www.upwork.com/freelancers/~01511dd712b8a399be?viewMode=1


Thank you for your time and support in helping facilitate this process. Please let me know if you need further information from my end.

Best regards,
SIMalik

**Comment by SIMalik** [comment] 2024-10-28 13:35
https://github.com/Expensify/App/issues/47874#issuecomment-2428231172 melvin-bot:
> * @SIMalik requires payment (Needs manual offer from BZ)

**Comment by garrettmknight** [comment] 2024-10-29 18:25
@SIMalik offer out to you in Upwork https://www.upwork.com/nx/wm/offer/104649625

**Comment by garrettmknight** [comment] 2024-10-29 18:26
@ntdiary request when you're ready.

**Closed** 2024-10-30 09:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-30 16:29
$250 approved for @ntdiary
