### ISSUE TITLE
Android - Emoji - Change default skin tone/list of frequently used doesn't work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10106] opened 2022-07-26 03:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/9677

## Action Performed:
1. Go to App and login with any account
2. Access any chat you prefer
3. Click on Emoji
4. Click on Change default skin tone
5. Send multiple emoji to add them to the list of most used emoji
6. Log out

## Expected Result:
Functions Change default skin tone should  be able to selected

## Actual Result:
Change default skin tone doesn't work

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/180916462-1878be4e-5809-4b43-9096-474c7ef06117.mp4

https://user-images.githubusercontent.com/93399543/180916473-f64f9fb4-b7bd-4e49-82c1-95b9546f7d5b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-07-26 17:23
This seems like two separate bugs. Was unable to reproduce the frequently used emojis bug. But the default skin tone feature appears to be broken completely.

**Comment by mvtglobally** [comment] 2022-07-26 18:36
@marcaaron Do you want us to log them separately?

**Comment by luacmartins** [comment] 2022-07-26 23:52
I was unable to reproduce the frequently used emojis bug, but setting the skin tone seems broken. It immediately reverts back to the default. 

cc @danieldoglas since you seem to have implemented the `updatePreferredSkinTone` command.

**Comment by luacmartins** [comment] 2022-07-27 00:23
hmm changing the return type from string to integer seems to fix the issue, but I'm not sure why since we seem to either accept string or int in App 🤔

**Comment by luacmartins** [comment] 2022-07-27 00:29
The issue seems to be this `===` [here](https://github.com/Expensify/App/blob/ce229bc1812ded576ce29d007fa3c03be8d1cd75/src/components/EmojiPicker/getSkinToneEmojiFromIndex.js#L10). If we are passing a string instead of int, we should not check for type. So a few possible solutions:

1. Update Web-E to send int instead of string
2. Update that equality to just `==`
3. Update the `skinTone` key [here](https://github.com/Expensify/App/blob/ce229bc1812ded576ce29d007fa3c03be8d1cd75/assets/emojis.js#L30-L48) to strings

**Comment by luacmartins** [comment] 2022-07-27 00:56
Hmm so 3 is not really an option since that NVP seems to be saved as an int and returned as such in OpenApp, which would break that functionality. I'm not a big fan of using `==`, so I think the solution is to remove the blocker label and make these changes in Web-E.

Web-E PR [here](https://github.com/Expensify/Web-Expensify/pull/34424). Removing blocker label.

**Comment by danieldoglas** [comment] 2022-07-27 01:51
That's my bad. After some discussion, I decided that the changes for NVPs were not necessary to test in all platforms before opening the PR, but it looks like I was wront.

**Comment by luacmartins** [comment] 2022-07-27 01:56
No worries! I created a PR to fix this in Web-E.

**Comment by kavimuru** [comment] 2022-07-27 18:06
@marcaaron  A separate issue is logged for "frequently used emoji's are not saved" #10134

**Comment by luacmartins** [comment] 2022-07-27 21:15
Cool. We have a fix for the default skin tone and a separate one for the frequently emoji one. I'll close this one out then! Thanks!

**Closed by luacmartins** 2022-07-27 21:15 UTC
Labels: Engineering, Daily
