### ISSUE TITLE
[$1000] Web - No transition animation when selecting users in the Request money / Split bill flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25850] opened 2023-08-24 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the FAB
2. Click either Request money or Split bill
3. Enter any amount
4. Click the green next button

## Expected Result:
There should be a transition animation when opening the selection

## Actual Result:
There is no transition animation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/38aaaa8c-6959-4ead-8243-d84400d71150

https://github.com/Expensify/App/assets/115492554/95719417-39ef-4193-86d9-f99704590948

**Expensify/Expensify Issue URL:**

**Issue reported by:** @joh42

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692047364460929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01899f9953a92032b7</li>
        <li>Upwork Job ID: 1694866275443363840</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-08-24 13:26
Proposal from @joh42
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There is no transition animation when we go to the user selection step in both the Request money and Split bill flows.
### What is the root cause of that problem?
The root cause is that we instantly focus the _Name, email, or phone number_ input, preventing the transition animation from finishing.
### What changes do you think we should make in order to solve the problem?

Let me first state that any solution to this issue will require changes to both the [MoneyRequestParticipantsSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) and the [MoneyRequestParticipantsSplitSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js) to make sure this issue is solved for both the Request money and Split bill flows.
The general approach for solving this kind of issue is to focus using the [ScreenWrapper's](https://github.com/Expensify/App/blob/main/src/components/ScreenWrapper/index.js) `onEntryTransitionEnd`, as has been discussed [on Slack](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1689957344.255689). Here's how to implement that:
1. Implement ref forwarding for both the [MoneyRequestParticipantsSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) and the [MoneyRequestParticipantsSplitSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js)
2. If we want to avoid tight coupling by focusing the OptionsSelector directly from the [MoneyRequestParticipantsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js), add an imperativeHandler to both the [MoneyRequestParticipantsSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) and the [MoneyRequestParticipantsSplitSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js), with a function for focusing the OptionsSelector in those components
3. Add `onEntryTransitionEnd` to the [MoneyRequestParticipantsPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js). When this is fired, we check which of the aforementioned selectors are rendered based on the `iouType`, and then focus the OptionsSelector of that component
It's worth noting that the selectors are conditionally rendered, but since the `iouType` does not change I do not foresee any problems using `onEntryTransitionEnd` here:
https://github.com/Expensify/App/blob/70c525952d33563d88efbaf799b840ab769716ed/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L97-L111
I do not necessarily think this is the cleanest approach however, as it requires adding ref forwarding to two different components. As such, I'll explain an alternate solution below that is worth considering for this specific bug:
### What alternative solutions did you explore? (Optional)
#### Alternative 1:
Instead of implementing ref forwarding, we can pass the [ScreenWrapper's](https://github.com/Expensify/App/blob/main/src/components/ScreenWrapper/index.js) `didScreenTransitionEnd` to both the [MoneyRequestParticipantsSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js) and the [MoneyRequestParticipantsSplitSelector](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js). Then we have a `useEffect` in both those components solely listening to the `didScreenTransitionEnd` prop. When it changes to true, we focus the options selector.
This is essentially the exact same solution as using `onEntryTransitionEnd`, but it's cleaner because we do not have to worry about ref forwarding nor which of the selectors is currently rendered. As you can see here, `didScreenTransitionEnd` works the same way as `onEntryTransitionEnd`:
https://github.com/Expensify/App/blob/70c525952d33563d88efbaf799b840ab769716ed/src/components/ScreenWrapper/index.js#L48-L55
Therefore I actually think this might be the optimal solution here.
#### Alternative 2:
We could pass `shouldDelayFocus={true}` to the OptionsSelector. This would be a one-line fix, but according to the aforementioned [Slack discussion](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1689957344.255689) we should move away from this approach to focusing.
#### Alternative 3:
We could use `InteractionManager.runAfterInteractions` for focusing, but again, like with `shouldDelayFocus`, this is something that we should move away from.

**Comment by garrettmknight** [comment] 2023-08-25 00:16
We should fix this for consistency with the mobile app.

**Comment by b4s36t4** [comment] 2023-08-25 00:18
This is dupe of #22388

**Comment by garrettmknight** [comment] 2023-08-28 16:47
@b4s36t4 thanks for the catch. Closing.

**Closed by garrettmknight** 2023-08-28 16:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
