### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Web - Loader animation appears on clicking resend magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22083] opened 2023-07-02 22:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if you are logged in
2. Enter an email
3. Click continue and wait for 30seconds
4. Click resend code

## Expected Result:
No loader animation on sign in button

## Actual Result:
Loader animation on sign in button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6fa127f6-a43b-4cd4-bee8-af5db7a43d58

https://github.com/Expensify/App/assets/93399543/b6e03afc-5b0b-4933-adf0-4060a6660c0e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688225638202929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f28b124d7b31c045</li>
        <li>Upwork Job ID: 1675925621136752640</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by lazar-stamenkovic** [comment] 2023-07-03 19:21
Agree with the  @gitvolo's proposal. think it's correct fix. because resendValidateCode doesn't require any loading animation on the frontend while calling api.

**Comment by s77rt** [comment] 2023-07-04 12:32
@samh-nl Thanks for the proposal. I don't your think you are solving the correct issue here. Your problem re-statement does not look so correct. I don't see what inconsistency you are referring to.

**Comment by s77rt** [comment] 2023-07-04 12:36
@bernhardoj Thanks for the proposal. Your RCA is correct. The three suggested solutions are similar (with option 2 and option 3 being exactly the same). They do the job well but also completely remove the user feedback. I think we should discuss the expected behaviour on Slack (posting in few mins).

**Comment by s77rt** [comment] 2023-07-04 12:38
@gitvolo Thanks for the proposal. Please always try to re-write the problem that we are solving on your own words. The RCA is correct. The solution makes sense but it's proposed by @bernhardoj already.

**Comment by s77rt** [comment] 2023-07-04 12:41
@samh-nl I don't see how that relates to this issue. The loader should show if something is being loaded and has nothing to do with errors.

**Comment by s77rt** [comment] 2023-07-05 13:43
As per the Slack discussion we should be good to go with removing the loading spinner. Let's go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/22083#issuecomment-1617731364) (option 1).

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by s77rt** [comment] 2023-07-08 01:27
Not overdue. @grgia ^

**Comment by grgia** [comment] 2023-07-10 15:46
Good to go, @bernhardoj

**Comment by MitchExpensify** [comment] 2023-07-18 20:54
Added a reminder to pay to my calendar. 

Friendly reminder to get the BZ steps above addressed @s77rt - Thank you!

**Comment by s77rt** [comment] 2023-07-18 21:50
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/14854
- The offending PR has been commented on: https://github.com/Expensify/App/pull/14854#discussion_r1267334354
- A discussion in #expensify-bugs has been started: Not needed. This is not really a bug but a design perspective, we could have caught that if it was brought to discussion with the design team.
- Determine if we should create a regression test for this bug: No

**Comment by MitchExpensify** [comment] 2023-07-18 23:04
Awesome, thanks @s77rt !

**Comment by MitchExpensify** [comment] 2023-07-24 16:41
Reporting bonus paid @chiragxarora 

C+ paid with bonus to @s77rt 

@bernhardoj invited you to the [Upwork Job](https://www.upwork.com/jobs/~01f28b124d7b31c045) and will close this out once we get payment over to you!

**Comment by MitchExpensify** [comment] 2023-07-24 19:31
Thanks! Paid and contract ended 🚀 

Great job everyone

**Closed by MitchExpensify** 2023-07-24 19:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
