### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Dev: Lounge Access -  Display name with no spacing on LoungeAccess page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28256] opened 2023-09-26 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Change your display name to very long name
2. Go to Settings => Profile => Lounge Access.
3. Observer the Display name.

## Expected Result:
Display name should have the spacing left, right.

## Actual Result:
Display name with no spacing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.69-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1cf41cdb-8d5f-4244-a3d3-fea7f86b4ca1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694673434455339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a75a17aaf196848</li>
        <li>Upwork Job ID: 1706652568219099136</li>
        <li>Last Price Increase: 2023-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26897544</li>
<li>hungvu193 | Reporter | 26897545</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by kbecciv** [comment] 2023-09-26 12:52
Proposal by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694673434455339

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We didn't have the padding horizontal for our `overlayContent` here, which caused the issue:
https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/settings/Profile/LoungeAccessPage.js#L72
### What changes do you think we should make in order to solve the problem?
We should add `styles.ph5` [here](https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/settings/Profile/LoungeAccessPage.js#L72) to make `overlayContent` has horizontal padding.

### What alternative solutions did you explore? (Optional)
N/A

<details><summary>Result</summary>

https://github.com/Expensify/App/assets/16502320/ee108280-11b7-4fec-ba1a-03572b82399a


</details>

**Comment by ishpaul777** [comment] 2023-09-26 13:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Lounge Access - Display name with no spacing on LoungeAccess page.
 
 ### What is the root cause of that problem?
 We didn't have the padding horizontal for overlayContent [here](https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/settings/Profile/LoungeAccessPage.js#L72).

```jsx
 <View style={[styles.flex1, styles.justifyContentCenter, styles.alignItemsCenter, styles.pt5]}> 
 ```
 
### What changes do you think we should make in order to solve the problem?
We should add `styles.avatarSectionWrapper` to the view styles and remove `styles.alignItemsCenter`

What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2023-10-13 15:37
hey @zanyrenney, can you please just pay out this issue please? Thanks!

**Comment by zanyrenney** [comment] 2023-10-16 11:18
Yep, on it @Julesssss

**Comment by JmillsExpensify** [comment] 2023-12-11 01:30
@zanyrenney Mind updating your payment summary with the amount that should be paid? Re-open for that part.

**Comment by zanyrenney** [comment] 2023-12-12 10:02
PAYMENT SUMMARY

@hungvu193 requires payment [offer](https://www.upwork.com/nx/wm/offer/26897544) (Contributor) - PAID $50
@parasharrajat does not require payment (Eligible for Manual Requests) - due $750 - $500 + $250 urgency
@hungvu193 requires payment [offer](https://www.upwork.com/nx/wm/offer/26897544) (Contributor) - PAID $750, $500 + $250 URGENCY.

**Comment by JmillsExpensify** [comment] 2023-12-12 18:45
$750 payment approved for @parasharrajat based on summary above.

**Comment by zanyrenney** [comment] 2023-12-13 11:07
closing!

**Closed by zanyrenney** 2023-12-13 11:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
