### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] The up-to-edit feature doesn't work when the message contains an embedded image.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52319] opened 2024-11-11 17:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-3
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1731121206505619)

## Action Performed:
1. Navigate to any chat
2. Compose any message and add a attachment
3. Send the message
4. Press the up arrow on the keyboard to edit
## Expected Result:
User able to edit the sent message
## Actual Result:
Up to edit feature doesn't work
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/c85f012b-ca8c-497b-9acf-142f1c5b9a4a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856262688043659757</li>
        <li>Upwork Job ID: 1856262688043659757</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 104956482</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-11-11 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the last message sent in a chat includes an attachment, pressing the ArrowUp key does not open the edit box, preventing the user from editing that message
### What is the root cause of that problem?
When a message with an attachment is sent, the selection.start value is set to the length of the text in that message. Because of this, the condition in the code that triggers the edit box doesn’t pass, which is why the edit box isn’t activated.
hence this condition will be false: 
https://github.com/Expensify/App/blob/9d8571bc9e504aabbb75c690a3bca3918ed565bd/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L482
### What changes do you think we should make in order to solve the problem?
To fix this, we could simplify the condition by checking only if `isEmptyComment` is true, as the `selection.start <= 0` check seems unnecessary.
### What alternative solutions did you explore? (Optional)
we could set selection.start to 0 whenever a message is sent with an attachment.

**Comment by jliexpensify** [comment] 2024-11-12 04:26
@Expensify/design before I make this External, do you want to review this [thread](https://expensify.slack.com/archives/C049HHMV9SM/p1731121206505619) and weigh in and confirm this is something we want to change? Shawn has shared thoughts [here](https://expensify.slack.com/archives/C049HHMV9SM/p1731354971213749?thread_ts=1731121206.505619&cid=C049HHMV9SM) already. Thanks!

**Comment by shawnborton** [comment] 2024-11-12 07:50
I think it makes sense to fix this, yes. Basically whether a message has an image or not shouldn't change your ability to hit the up arrow to quickly edit it.

**Comment by jliexpensify** [comment] 2024-11-12 09:08
Ty Shawn, lets do it!

**Comment by jayeshmangwani** [comment] 2024-11-12 12:09
Thanks for the proposal, @Shahidullah-Muffakir. Removing `selection.start <= 0` as you suggested would break the current functionality for moving to the first line when pressing the up key in the composer.

**Steps to reproduce the issue after applying your change:**

1. Press **Command + Space** in the composer to add a new line.
2. Press the up key.
3. Nothing happens, whereas in the current version of the app, pressing the up key in the composer allows the cursor to move to the first line.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-12 16:12
> Thanks for the proposal, @Shahidullah-Muffakir. Removing `selection.start <= 0` as you suggested would break the current functionality for moving to the first line when pressing the up key in the composer.
> 
> **Steps to reproduce the issue after applying your change:**
> 
> 1. Press **Command + Space** in the composer to add a new line.
> 2. Press the up key.
> 3. Nothing happens, whereas in the current version of the app, pressing the up key in the composer allows the cursor to move to the first line.

@jayeshmangwani , Oh, got it, thanks for explaining that! I could reproduce it now.

Given that, what do you think of the alternative approach I mentioned in my [proposal](https://github.com/Expensify/App/issues/52319#issuecomment-2468908181): setting selection.start to 0 whenever a message is sent with an attachment?

**Comment by jayeshmangwani** [comment] 2024-11-13 11:34
@daledah I tried adding `setSelection` before the `isFocused` condition, but I feel this could introduce a regression. Although the issue doesn't consistently reproduce, I've managed to replicate it a few times. Here are the steps:

1. Go to any workspace chat.
2. Type `@` to open the mention suggestion.
3. Navigate to the LHN and submit an expense to that workspace (from step 1).
4. Observe that when returning to the workspace chat, a modal opens—though it shouldn't.

https://github.com/user-attachments/assets/e9570064-3b7b-435d-b8be-39a65b6f5eb3

**Comment by jayeshmangwani** [comment] 2024-11-13 11:38
@Shahidullah-Muffakir I have a question for this [comment](https://github.com/Expensify/App/issues/52319#issuecomment-2470952844): if we add the `setSelection((prevState) => ({ ...prevState, start: 0, end: 0 }));` in `onClear`, are we not setting `setSelection` twice? We’re already calling `setSelection(e.nativeEvent.selection)` in `ComposerWithSuggestions`.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-13 16:57
> @Shahidullah-Muffakir I have a question for this [comment](https://github.com/Expensify/App/issues/52319#issuecomment-2470952844): if we add the `setSelection((prevState) => ({ ...prevState, start: 0, end: 0 }));` in `onClear`, are we not setting `setSelection` twice? We’re already calling `setSelection(e.nativeEvent.selection)` in `ComposerWithSuggestions`.

@jayeshmangwani , in this part: https://github.com/Expensify/App/blob/be4d7f50949d52aa9f2cb9a8ac495ef19473edde/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L514-L519

the             `setSelection(e.nativeEvent.selection)`, won't be executed as the `!textInputRef.current?.isFocused()`, will be true in the case of sending attachment.

and just to not re-rerun this       `    setSelection((prevState) => ({ ...prevState, start: 0, end: 0 }));` on the onClear function twice for a text only message, we can add check if the input is not focused then run it.


```
if(!textInputRef.current?.isFocused()){
 setSelection((prevState) => ({ ...prevState, start: 0, end: 0 }));
}
```

Also, I noticed that `setSelection((prevState) => ({ ...prevState, start: 0, end: 0 }));` is also being called in the Composer component’s onClear function
here:
https://github.com/Expensify/App/blob/e6b416726fbe7171e84f048a8874c1b9254b6a26/src/components/Composer/implementation/index.tsx#L278

**Comment by jayeshmangwani** [comment] 2024-11-14 06:24
> called in the Composer component’s onClear function 

Just to confirm, is onClear triggered only for text only message?

**Comment by Shahidullah-Muffakir** [comment] 2024-11-14 07:16
> Just to confirm, is onClear triggered only for text only message?


No, clear is triggered for all messages, regardless of whether they include attachments or are text-only.
https://github.com/Expensify/App/blob/e6b416726fbe7171e84f048a8874c1b9254b6a26/src/components/Composer/implementation/index.tsx#L278


In clear, `setSelection({ start: 0, end: 0 })` is called to reset the selection, but it only updates the local state `selection` within the Composer component. Since this reset is only applied to Composer's own internal selection state, it doesn’t affect the selection state in ComposerWithSuggestions.
https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/components/Composer/implementation/index.tsx#L63-L68
In ComposerWithSuggestions, we maintain a separate local selection state using which we decide to open the comment edit box if the selection.start <=0,  
https://github.com/Expensify/App/blob/e6b416726fbe7171e84f048a8874c1b9254b6a26/src/components/Composer/implementation/index.tsx#L63
This means the selection reset on `clear` in `Composer` doesn’t propagate to `ComposerWithSuggestions`, which is why we need to explicitly update the selection state of ComposerWithSuggestions in the `onClear`:
https://github.com/Expensify/App/blob/be4d7f50949d52aa9f2cb9a8ac495ef19473edde/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L700

**Comment by jayeshmangwani** [comment] 2024-11-14 07:40
@Shahidullah-Muffakir While testing your changes, I discovered another bug related to the up-to-edit feature (reproducing on staging as well), which I believe we should address within this issue. Could you confirm if the root cause is the same for message with attachment as well as the bug described below, and whether your proposal will fix it?

**Steps to reproduce:**

1. Type a message in the chat, then tap outside the composer to remove focus.
2. Press the Send button.
3. Tap on the composer again.
4. Press the up key. (Expected: It should open the edit mode for the last message, but currently it does nothing.)

Let me know if your solution will cover this case as well.

https://github.com/user-attachments/assets/4b7891ad-8c9b-4bfa-8dbd-ec4f3a526470

**Comment by jayeshmangwani** [comment] 2024-11-14 08:11
@Shahidullah-Muffakir Cool, please add your comments https://github.com/Expensify/App/issues/52319#issuecomment-2470952844  https://github.com/Expensify/App/issues/52319#issuecomment-2474203557 https://github.com/Expensify/App/issues/52319#issuecomment-2475588671 to the main proposal in one place and update the proposal so I can review it again.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-14 08:31
@jayeshmangwani, [Proposal](https://github.com/Expensify/App/issues/52319#issuecomment-2468908181) updated, Thank you.

**Comment by jayeshmangwani** [comment] 2024-11-14 10:00
Hey @Shahidullah-Muffakir, thanks for updating the proposal, and sorry for the back-and-forth. Since this is the main component of the app, I need to test some parts thoroughly, which is why it's taking a bit longer to approve the proposal.

Also, from your [proposal](https://github.com/Expensify/App/issues/52319#issuecomment-2468908181), it seems to work fine in testing, but I don't entirely agree with setting `setSelection({ start: 0, end: 0 })` in `onClear`. The reasons are:

1. In `Composer/implementation/index.tsx`, when we send the message and clear the text, only the `clear` function is called, and at that time `onSelectionChange` won't trigger. So, setting the selection to 0 will only happen from one place.
2. For the `ComposerWithSuggestions component`, when the text is cleared, both `onSelectionChange` and `onClear` are called. So, setting `setSelection` in both places feels a bit odd right now. We should either set `setSelection` from `onSelectionChange` or from `onClear`.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-14 19:54
No problem, @jayeshmangwani.
Regarding the setSelection({ start: 0, end: 0 }) placement, I see your point about the redundancy in calling setSelection in both onClear and onSelectionChange within ComposerWithSuggestions. However, the Composer component itself also handles selection changes in both clear and onSelectionChange. 
As we are passing onSelectionChange as a prop to Composer component from ComposerWithSuggestions
https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/components/Composer/implementation/index.tsx#L277
What do you think about this? I’ll also keep looking .

**Comment by jayeshmangwani** [comment] 2024-11-14 20:00
> Composer component itself also handles selection changes in both clear and onSelectionChange

Yes, but in the `Composer` component, `onSelectionChange` is not triggered when we press the send button. On the other hand, in `ComposerWithSuggestions`, both `clear` and `onSelectionChange` are called when pressing send or when clearing the composer.

**Comment by Shahidullah-Muffakir** [comment] 2024-11-15 01:18
> Yes, but in the `Composer` component, `onSelectionChange` is not triggered when we press the send button. 

When we send message the clear function of `Composer` component is being called, inside that function `onSelectionChange` is also being called.

**Comment by jayeshmangwani** [comment] 2024-11-18 09:43
Thanks to everyone for the proposals above!

I've tested a few cases, and calling `setSelection` before the `!textInputRef.current?.isFocused()`condition in `onSelectionChange` resolves the issue without causing any problems during testing. Based on this, I suggest we proceed with @daledah's [Proposal](https://github.com/Expensify/App/issues/52319#issuecomment-2469581967).

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment] 2024-12-04 03:16
Bumping @jayeshmangwani for the checklist.

Payment Summary

- C: @daledah $250 (to be paid via Upworks)
- C+: @jayeshmangwani $250 (to be paid via N.D)

[Upwork job](https://www.upwork.com/jobs/~021856262688043659757)

**Comment by jayeshmangwani** [comment] 2024-12-04 07:21
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39007#issuecomment-2516388982

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A 

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open any chat.
2. Send a message with an attachment.
3. Wait until the attachment is sent.
4. Press the Up key.
5. Verify that the Edit composer is displayed.


Do we agree 👍 or 👎

**Comment by jliexpensify** [comment] 2024-12-08 21:19
Paid and job closed.

@jayeshmangwani - [here's the summary for your request.](https://github.com/Expensify/App/issues/52319#issuecomment-2516080012)

**Closed by jliexpensify** 2024-12-08 21:19 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 11:25
$250 approved for @jayeshmangwani
