### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$250] Tag-After unselecting state option, region selected is shown in state field.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47301] opened 2024-08-13 09:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4848505
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: Upload dependent tags as admin in old dot
1. Launch app
2. Tap on employee workspace chat
3. Tap plus icon -- submit expense
4. Enter an amount and tap next
5. Unselect State option
6. Select a Region option

## Expected Result:
After unselecting state option, region selected must not be shown in state field.

## Actual Result:
After unselecting state option, region selected is shown in state field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/23dfb947-2147-4ef1-b15a-86afe3de7a23

[Bug6570685_1723538561973!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/user-attachments/files/16597498/Bug6570685_1723538561973.Dependent_-_Multi_Level_tags_NEW.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dd65aecb20eb97f</li>
        <li>Upwork Job ID: 1823301758645340925</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103580205</li>
<li>situchan | Contributor | 103580206</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by izarutskaya** [comment] 2024-08-13 09:51
We think this issue might be related to the #vip-vsb

**Comment by grgia** [comment] 2024-08-13 10:13
Looks like this is related to multi-level tags, I demoted from deploy blocker

**Comment by grgia** [comment] 2024-08-13 10:16
Or potentially categories. cc @trjExpensify could you confirm

**Comment by grgia** [comment] 2024-08-13 10:17
I'm not sure what the expected behavior is here, looking to tag the project lead

**Comment by trjExpensify** [comment] 2024-08-13 11:58
Is this the PR on staging that's the culprit? https://github.com/Expensify/App/pull/46977 CC: @daledah @situchan 

>I'm not sure what the expected behavior is here, looking to tag the project lead

We shouldn't put values in the wrong level of tag. When it comes to dependent tags, the second dependent level of tag should not be visible unless the first level has been selected. Similarly then, if you remove the first level, we remove the second level.

>Pre-condition: Upload dependent tags as admin in old dot

That said. Why do QA keep running multi-tag tests with dependent tags? (CC: @isagoico). AFAIK, we didn't officially build support for them in NewDot. A better test is independent multi-tags, or two levels of coding imported as tags from an accounting solution. CC: @joekaufmanexpensify as displaying tags was built in wave6.

**Comment by joekaufmanexpensify** [comment] 2024-08-13 15:55
Agree with using independent tags for tests going forward.

**Comment by trjExpensify** [comment] 2024-08-17 10:52
> Is this the PR on staging that's the culprit? #46977 CC: @daledah @situchan

This PR is in the regression period, so they should fix it. 👌

**Comment by jliexpensify** [comment] 2024-08-19 00:41
Tagging in @situchan to review and fix

**Comment by FitseTLT** [comment] 2024-08-19 17:08
This regression is causing https://github.com/Expensify/App/issues/47631

**Comment by jliexpensify** [comment] 2024-08-20 00:41
Note for myself: No payment required as this was a regression

**Comment by situchan** [comment] 2024-09-12 18:17
⚠️ We got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the [PR](https://github.com/Expensify/App/pull/47687) of this issue was only deployed to **production** on Aug 30 in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-06]** according to Aug 30's production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

**Comment by jliexpensify** [comment] 2024-09-12 23:29
Thanks @situchan - is a checklist needed?

I'll get payment sorted shortly.

**Comment by jliexpensify** [comment] 2024-09-12 23:37
Ah wait - [was this a regression?](https://github.com/Expensify/App/issues/47301#issuecomment-2297754619)

If so, no payment needed?

**Comment by situchan** [comment] 2024-09-13 05:11
Oh yes, no payment
We added automated tests to avoid regressions in the future.
We can just close this issue.

**Comment by jliexpensify** [comment] 2024-09-13 05:15
Thanks for confirming!

**Closed by jliexpensify** 2024-09-13 05:15 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
