### ISSUE TITLE
The tooltip loses its position when typing and deleting large amount

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#16573] opened 2023-03-27 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open web chrome
2. Click on + icon and click on send money
3. Place your mouse on the currency and notice that the tooltip is in center
4. Now without moving your mouse, just type in large number and delete it
5. Notice that the tooltip loses its position

## Expected Result:
The tooltip should not lose its position when typing and deleting large amount continuously

## Actual Result:
The tooltip loses its position when typing and deleting large amount continuously

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.90-4
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/228030251-531fe5f4-3d24-433e-9835-fd351c566638.mp4

https://user-images.githubusercontent.com/43996225/228030268-65ad256e-dda3-4322-9705-597dd9237de3.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1679902897561019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-03-28 16:38
I do not think that the tooltip should show when the cursor is not hovering over anything actionable - That would not be expected, closing as not a bug

**Closed by MitchExpensify** 2023-03-28 16:38 UTC
Labels: Daily, Bug
