### ISSUE TITLE
[$500]  IOU - The selected category moves to the top of the list when <8 categories active

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36912] opened 2024-02-20 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4327825
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable categories and add 3 categories, add an employee to the policy. Setup OldDot Collect Policy:
https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. In the category section, select the category at the bottom of the list
10. Navigate to the categories section again

## Expected Result:
The selected category should remain in its place in alphabetical order if <8 categories are active

## Actual Result:
The selected category moves to the top of the list when <8 categories active

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3ea33476-5caf-4b1d-ae6e-444810e520c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ddec0e527151c87</li>
        <li>Upwork Job ID: 1759967177619148800</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 15:44
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by tgolen** [comment] 2024-02-20 17:52
@lukemorawski It appears this could be related to your PR https://github.com/Expensify/App/pull/35567. Can you confirm?

I'm going to demote this issue from being a deploy blocker to being a normal bug.

cc @cristipaval

**Comment by lukemorawski** [comment] 2024-02-21 09:59
@tgolen I can confirm that this is still reproducible on latest `main` but I don't see how my PR would cause that behaviour as `getFilteredOptions` params where untouched.

**Comment by tgolen** [comment] 2024-02-21 16:49
@tienifr I'm going to assign to you for now.

**Comment by tgolen** [comment] 2024-02-21 19:42
@tienifr would you mind commenting on this issue so I can then assign it to you?

**Comment by DylanDylann** [comment] 2024-02-22 02:41
@tgolen  This is intentional in [here](https://github.com/Expensify/App/issues/35553#issuecomment-1921632377)

> Also a bonus is that the selected category now will come as the first item in the list, consistent with the a-lot-of-categories UX.

I think we need to confirm the expectations first. @Expensify/design Could you guys check this issue and verify if we should fix it? Note that: In many other places, the selected option is in the first position on the list

cc @tienifr

**Comment by dubielzyk-expensify** [comment] 2024-02-22 03:26
In my mind the category list shouldn't reorder based on selection but keen to hear what @dannymcclain and @shawnborton thinks. I don't feel too strongly though

**Comment by shawnborton** [comment] 2024-02-22 13:23
Hmm I could be wrong here, but I think if the list options are less than say 9, we never reoder the list even after one is selected. But if the list is super long, the current selected list item moves to the top and we get a UI that looks like this:

![CleanShot 2024-02-22 at 08 23 15@2x](https://github.com/Expensify/App/assets/2319350/caa60485-bb91-47e8-8911-416bf96d169d)

cc @trjExpensify - thoughts on that?

**Comment by dannymcclain** [comment] 2024-02-22 14:08
>Hmm I could be wrong here, but I think if the list options are less than say 9, we never reoder the list even after one is selected. But if the list is super long, the current selected list item moves to the top and we get a UI that looks like this:

This was how I thought it worked as well. But seeing this issue pop up made me question why we have a bunch of conditional logic (ie - added complexity) for lists at all. I mean you know me, I'm a set it and forget it kinda guy! 😂 

>IMO we should have consistent behavior in both cases... I don't see any downside with having the selected item on top consistently in both cases.

Now I think I'm trending toward agreeing with this perspective.

**Comment by trjExpensify** [comment] 2024-02-23 02:42
>@trjExpensify - thoughts on that?

Yep, agreed. With 8 or less there's no "recent" section or search input and therefore the selected category doesn't sit above that section in the list - it remains in place. For [comparison](https://github.com/Expensify/App/issues/36912#issuecomment-1959447443) with what you posted above: 

<img width="260" alt="image" src="https://github.com/Expensify/App/assets/16232057/e26a1726-b78a-428b-af87-1002fca0d6cc">

**Comment by DylanDylann** [comment] 2024-02-23 09:49
Currently, I see 2 options:

1. We will always display the selected option at the first of the list. Then we don't need to do anymore and [this bug](https://github.com/Expensify/App/issues/36912#issuecomment-1961016060) also doesn't happen
2. We still keep the current design and will create a new bug to fix [new above bug ](https://github.com/Expensify/App/issues/36912#issuecomment-1961016060)

**Comment by Julesssss** [comment] 2024-02-23 10:18
> Note that, if we always keep the selected option at the first of the list, this bug won't happen

Choosing behavior to avoid bugs isn't a good reason. but I'm also a bit unsure where we aligned based on the above comments. @Expensify/design & @trjExpensify, did we align on [this](https://github.com/Expensify/App/issues/36912#issuecomment-1959447443)?

**Comment by trjExpensify** [comment] 2024-02-23 10:45
The behaviour came from the categories doc in wave6. Latest ref [here](https://expensify.slack.com/archives/C02MW39LT9N/p1704742105229939?thread_ts=1704741107.302739&cid=C02MW39LT9N).

**Comment by Julesssss** [comment] 2024-02-23 11:41
Thanks. So keeping the option in place aligns with 2 here:

> 1. We will always display the selected option at the first of the list. Then we don't need to do anymore and [this bug](https://github.com/Expensify/App/issues/36912#issuecomment-1961016060) also doesn't happen
> 2. We still keep the current design and will create a new bug to fix [new above bug ](https://github.com/Expensify/App/issues/36912#issuecomment-1961016060)

**Comment by DylanDylann** [comment] 2024-02-23 11:43
Yes, I am reviewing this PR

**Comment by tgolen** [comment] 2024-02-23 16:18
FWIW I like always displaying the selected option at the first of the list (option 1).

- It's a consistent UX in all cases
- It makes the code less complex (which helps with technical debt, maintenance, and yes, preventing bugs)

I feel that having the UX change based on the number of items in the list just feels like we are getting more clever than we need to. Let's go with the most simple solution first, and if we get significant customer feedback that this isn't ideal, we can change it later.

**Comment by dannymcclain** [comment] 2024-02-23 16:36
_Personally_ I tend to [agree with Tim](https://github.com/Expensify/App/issues/36912#issuecomment-1961617492). But I think this behavior is something that has been talked about widely and decided upon by the larger team. I'm hesitant to let my opinion override a widely agreed upon and documented behavior. 🤷‍♂️

**Comment by shawnborton** [comment] 2024-02-23 17:43
I don't feel too strongly. I think the idea behind not changing the order on the smaller amounts of list items (less than 9) was that you can see all of the items in your viewport, and thus it might feel weird if you have the list jumping when you can see the entire screen at once? 

That being said, definitely down to go with consistency here.

**Comment by DylanDylann** [comment] 2024-02-26 11:26
@tgolen @Julesssss What is the final confirmation?

**Comment by Julesssss** [comment] 2024-02-26 12:15
Alright, thanks everyone. So we all agree on the consistent component behaviour for now... which is this option: 

> We will always display the selected option at the first of the list. Then we don't need to do anymore and https://github.com/Expensify/App/issues/36912#issuecomment-1961016060 also doesn't happen

@DylanDylann you may want hold for a few hours just in case of any final objections

**Comment by DylanDylann** [comment] 2024-02-27 03:21
@Julesssss If there aren't any objections, let's close this issue. @tienifr Also close [this PR](https://github.com/Expensify/App/pull/37127)

**Closed** 2024-02-27 08:51 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
