### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Bug: Edit message compose box has no characters limit reported by @Tushu17

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11710] opened 2022-10-10 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Website/App
2. Go to chat.
3. Send a message.
4. Edit that message.

## Expected Result:
It should have characters limit like message compose box have limit of 60000 characters.

## Actual Result:
There is no character limit.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194938509-eabde8c8-b6eb-4bfa-a905-7645fc775be7.mov

https://user-images.githubusercontent.com/43996225/194938528-636628cb-b5dd-4f83-a383-f11df40ccdf7.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665417463480339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-10-10 20:34
### Proposal

Add `hasExceededMaxCommentLength`
 
```const hasExceededMaxCommentLength = this.state.draft.length > CONST.MAX_COMMENT_LENGTH;```

use it at view for border color by adding this to style `hasExceededMaxCommentLength && styles.borderColorDanger` https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/home/report/ReportActionItemMessageEdit.js#L191

we need to add ``` <ExceededCommentLength commentLength={this.state.draft.length} />```  inside the `View` below (it should be after the buttons) https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/home/report/ReportActionItemMessageEdit.js#L227

the erorr should be at the right side for that we need to use `marginLeft: 'auto'` here
https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/components/ExceededCommentLength.js#L18
( I will be adding the style at another issue as proposed [here](https://github.com/Expensify/App/issues/11386#issuecomment-1261414468))

We also need to disable the button by using ```isDisabled={hasExceededMaxCommentLength} ``` https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/home/report/ReportActionItemMessageEdit.js#L235

We also wanna keep the user from saving the edit changes by enter so for that we can add another if statement 
```js
        if(this.state.draft.length > CONST.MAX_COMMENT_LENGTH){
            e.preventDefault();
            return;
        }
```

https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/home/report/ReportActionItemMessageEdit.js#L176

**Comment by joekaufmanexpensify** [comment] 2022-10-10 21:45
Reproduced on web: 

![2022-10-10_17-43-44 (1)](https://user-images.githubusercontent.com/54866469/194957048-ec810b73-ef7e-4916-aa63-9476c22db85d.gif)

**Comment by thesahindia** [comment] 2022-10-11 20:40
@Puneet-here's [proposal](https://github.com/Expensify/App/issues/11710#issuecomment-1273795251) looks good to me but looks like we have on concern.

> When I tried edit and saving a big code block (more than 50k chars) I got an error, so we should decide the limit here I have posted it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1665439023026769) to get some eyes.

@luacmartins, please share your thoughts on this.


C+ reviewed 🎀👀🎀

**Comment by luacmartins** [comment] 2022-10-12 00:49
@Puneet-here what login did you use to get those errors? I could try to look at our server logs.

**Comment by Puneet-here** [comment] 2022-10-12 03:02
> @Puneet-here what login did you use to get those errors? I could try to look at our server logs.

I was using puneet.here121+1@gmail.com

**Comment by luacmartins** [comment] 2022-10-12 14:53
Thanks! I did see the error in the server and I think the problem is that we save both the original message and each edit that was made to it. We discussed it in more details [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1664559337865919) and we might change the limit down to 15k chars or something like that.

**Comment by luacmartins** [comment] 2022-10-12 14:54
That being said, I think that's a different issue that will be addressed [here](https://github.com/Expensify/App/issues/11432). So we can go ahead with @Puneet-here proposal.

**Comment by luacmartins** [comment] 2022-10-12 15:25
Reassigning @muttmuure as CM to this issue.

**Comment by luacmartins** [comment] 2022-10-12 15:25
@muttmuure could you please create the Upwork job?

**Comment by muttmuure** [comment] 2022-10-19 15:29
Job is here, sorry for the delay I was ooo most of last week: https://www.upwork.com/jobs/~011043b676c61cbec4

**Comment by Puneet-here** [comment] 2022-10-19 15:31
Jumped the process a little and pushed the PR just now.

**Comment by Puneet-here** [comment] 2022-10-19 15:33
> Job is here, sorry for the delay I was ooo most of last week: https://www.upwork.com/jobs/~011043b676c61cbec4

Applied to the job.

**Comment by muttmuure** [comment] 2022-10-19 15:42
Awesome, offer sent

**Comment by luacmartins** [comment] 2022-11-03 17:23
@muttmuure was this paid out? Can we close the issue?

**Comment by muttmuure** [comment] 2022-11-07 11:51
Waiting for @thesahindia and @Tushu17 to apply to the job and I'll pay in one go

**Comment by muttmuure** [comment] 2022-11-07 11:54
Oh I've clarified that I can pay Puneet now

**Comment by thesahindia** [comment] 2022-11-07 11:54
Applied!

**Comment by muttmuure** [comment] 2022-11-07 12:01
Puneet and Sahil paid - just waiting for Tushar

**Comment by Tushu17** [comment] 2022-11-07 14:23
@muttmuure Okay applied, Thank you.

**Comment by muttmuure** [comment] 2022-11-11 11:36
@Tushu17 has been paid and everyone's contract has ended. Closing out

**Closed by muttmuure** 2022-11-11 11:36 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
