### ISSUE TITLE
[WAVE 7] Outstanding amount does not show up in LHN with GBR

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33993] opened 2024-01-05 01:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704298794713139

## Action Performed:
1. Create a  control workspace in OD
2. Invite member B
3. Create and submit report as user B in OD
4. Login to ND as admin

## Expected Result:
Should show in the LHN with GBR for the expense report submitted

## Actual Result:
not showing up in my LHN with a GBR
 
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/253993c2-fe38-404b-9ffc-b0cad620669e

![image (11)](https://github.com/Expensify/App/assets/38435837/1f5d74c9-a353-4fdd-9d3c-5581fd1723cc)

![image (12)](https://github.com/Expensify/App/assets/38435837/ece33ac4-d7a1-4761-8f8a-0b436af3ab17)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f8e7170461fb0db</li>
        <li>Upwork Job ID: 1744889607391125504</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-01-10 01:11
Confirming I'm able to reproduce.  I'm guessing it needs to be internal. Posted in the Wave 7 room
https://expensify.slack.com/archives/C02NZ2HGJAZ/p1704849060476979

**Comment by marcochavezf** [comment] 2024-01-12 02:13
No update, wrapping up a hold request issue and come back to this one.

**Comment by marcochavezf** [comment] 2024-01-14 21:39
No update, still working on the other hold request issue

**Comment by marcochavezf** [comment] 2024-01-15 19:59
> No update, still working on the other hold request issue

**Comment by marcochavezf** [comment] 2024-01-18 18:42
Working on it

**Comment by marcochavezf** [comment] 2024-01-19 01:53
PR up

**Comment by marcochavezf** [comment] 2024-01-29 18:15
The [PR](https://github.com/Expensify/Web-Expensify/pull/40575) was already deployed to production. I think we can close this one @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-01-30 22:05
Closing, @hoangzinh since the PR was in the Web/E repo, it didn't look like we needed C+ to review, so I'm assuming compensation isn't due.  Thx

**Closed by mallenexpensify** 2024-01-30 22:05 UTC
Labels: Reviewing, Daily, Internal, Bug
