### ISSUE TITLE
Log in - Set Password button isn't responding for 2FA account  

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12643] opened 2022-11-10 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Input email with existing Two Factor Authentication and click Continue
3. Click Forgot? link
4. Click link from email to open Set Password page
5. Input a valid password and click Set Password button

## Expected Result:
User would expect to see 2FA field to proceed further or at least confirmation screen, that password has been changed.

## Actual Result:
Set Password button isn't responding for 2FA account, in fact password has been changed. Clicking it one more time shows error message that link is expired.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201143146-978f40fc-6d6d-46f5-91b9-43609d8eca7c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2022-11-13 23:47
Alright here's my to-do list here: 

- [ ] The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead).
- [ ] The bug is reproducible, following the reproduction steps
- [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
- [ ] If you’re unable to reproduce the bug:
- [ ] Add the Needs reproduction label.
- [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.
- [ ] The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?)
- [ ] The GH was created by an Expensify employee or a QA tester.
- [ ] Contributors should not be creating Expensify/App GHs. Instead, they should submit their bug report in #expensify-open-source per [the steps in CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#proposing-a-job-that-expensify-hasnt-posted). If you encounter a GH created by a contributor, close it and ask them to post the Bug / NewFeature in #expensify-open-source first.
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification.

Then follow the rest of this process: https://stackoverflow.com/c/expensify/questions/14418

**Comment by conorpendergrast** [comment] 2022-11-14 00:53
Reproduced through conor@expensifail.com. 

I know that we do have some significant changes to passwords planned, so as a result I am going to close this out as a bug we will not fix.

**Closed by conorpendergrast** 2022-11-14 00:53 UTC
Labels: Daily, Bug
