### ISSUE TITLE
[$250] mweb - IOU - Tapping pay elsewhere button in header grey out IOU preview for few seconds

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39314] opened 2024-03-30 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4464523
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon --- request money
4. Enter an amount and tap next
5. Tap request
6. Open newly created expense to open IOU report page
7. Tap pay elsewhere button in header

## Expected Result:
In IOU report page, tapping pay elsewhere button in header must not grey out IOU preview for few seconds

## Actual Result:
In IOU report page, tapping pay elsewhere button in header grey out IOU preview for few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0283b55-5e74-433b-92c4-3dc1669a421e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1acc8625fd29f6e</li>
        <li>Upwork Job ID: 1777821827439878144</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-30 16:21
@chiragsalian  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-30 16:21
We think that this bug might be related to #vip-vsp

**Comment by chiragsalian** [comment] 2024-04-01 18:42
I can reproduce this issue on web too. Its more easily reproducible when i set network speed to "slow 3g" in chrome developer tools. I have not verified but i suspect the issue is from the change in this PR - https://github.com/Expensify/App/pull/33124. It looks like the optimistic data is not being set the same way as production.

imo not a blocker since this is a minor bug and only affects optimistic data. removing blocker label and demoting.

cc @robertjchen since I noticed you are working on this - https://github.com/Expensify/App/issues/31345. Should the IOU preview be greyed out or not as the API processes `PayMoneyRequest`. I feel like perhaps it should not be greyed out but wanted to double-check with you.

**Comment by robertjchen** [comment] 2024-04-01 18:46
Yep, not a blocker for sure- let me followup on the correct behavior.

**Comment by robertjchen** [comment] 2024-04-09 06:30
Confirmed that it should **NOT** be greyed out 👍

**Comment by pac-guerreiro** [comment] 2024-04-11 17:52
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by chiragsalian** [comment] 2024-04-15 20:04
Sure go for it @pac-guerreiro. When you get the chance let us know your ETA and proposal.

**Comment by pac-guerreiro** [comment] 2024-04-16 09:11
@chiragsalian @lanitochka17 

Currently I'm not able to reproduce this issue 😅 Can you check if this issue is still present?

**Comment by lanitochka17** [comment] 2024-04-16 15:52
Issue is not reproducible on the latest build 1.4.62-10


https://github.com/Expensify/App/assets/78819774/86be7d63-54b5-4a91-9c8c-54d19cc9ef98

**Comment by chiragsalian** [comment] 2024-04-16 22:37
Closing this issue since its not reproducible. If it reoccurs feel free to reopen the issue.

**Closed by chiragsalian** 2024-04-16 22:37 UTC
Labels: External, Engineering, Daily
