### ISSUE TITLE
[HOLD #27510][$500] Dev: Web - Selecting a workspace selects other (all) workspaces as well

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27588] opened 2023-09-16 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start money request flow
2. Ensure you have multiple workspaces created
3. Upon selecting one workspace(for split)
4. Observe all workspaces are selected

## Expected Result:
Only selected workspace should be selected

## Actual Result:
All workspaces are selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70-5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c96a8dd-cc8e-402b-b028-6ac1cbb5c893

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694781139958309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd4d5419ef8224cd</li>
        <li>Upwork Job ID: 1703111319192711168</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-16 18:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting a workspace selects other (all) workspaces as well

### What is the root cause of that problem?
While calculating `isSelected` here - 
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/OptionsList/BaseOptionsList.js#L176-L186

We check for accountID only, as workspace chats/reports have accountID 0.
We are showing other workspaces as selected as well

### What changes do you think we should make in order to solve the problem?
- We have to add, `reportID` to participant as well.
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L169
- While calculating `isSelected` we need to check reportID as well if accountID is 0.
Following conditions shall be changed
```js
if (option.accountID && option.accountID === item.accountID) return true
if (option.reportID && option.reportID === item.reportID) return true
```
 

### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment] 2023-09-16 18:52
This is a duplicate of https://github.com/Expensify/App/issues/27510.

**Comment by BhuvaneshPatil** [comment] 2023-09-16 19:02
Not a dupe, that's about showing workspace details and this one is about multiple workspaces being selected. Both have different RCA and solutions as well

**Comment by saranshbalyan-1234** [comment] 2023-09-18 00:33
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Selecting a workspace selects other (all) workspaces as well

### What is the root cause of that problem?
Upon searching i found that value of isSelected is only based on accountID, as all workspace have accountId as 0 its causing the issue. Which results in selecting all the workspaces.

[App/src/components/OptionsList/BaseOptionsList.js]

```javascript
 const isSelected = _.some(selectedOptions, (option) => { 
     if (option.accountID === item.accountID) { 
         return true; 
     } 
  
     if (_.isEmpty(option.name)) { 
         return false; 
     } 
  
     return option.name === item.searchText; 
 }); 
``` 


### What changes do you think we should make in order to solve the problem?
Instead of searching with accountID we need to search with reportID only as reportID is different for everything.

We have to pass reportID here

[App/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js]
Line: 169

```javascript
newSelectedOptions = [...participants, {accountID: option.accountID, login: option.login, selected: true, reportID: option.reportID}];
``` 

and need to change this to
[App/src/components/OptionsList/BaseOptionsList.js]


```javascript
const isSelected = _.some(selectedOptions, (option) => { 
     if (option.reportID === item.reportID) { 
         return true; 
     } 
     if (_.isEmpty(option.name)) { 
         return false; 
     } 
     return option.name === item.searchText; 
 }); 
``` 


### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment] 2023-09-19 05:05
@BhuvaneshPatil, do you know why, when you click split with a workspace, you get this blank _account_ that shows up? I noticed in your screenvid and it shows for me too
<img width="411" alt="image" src="https://github.com/Expensify/App/assets/22508304/077b0c62-67f1-4022-99a4-88070be2db6a">

**Comment by BhuvaneshPatil** [comment] 2023-09-19 05:37
@mallenexpensify This is known issue - https://github.com/Expensify/App/issues/27510

**Comment by mallenexpensify** [comment] 2023-09-19 05:53
Thanks @BhuvaneshPatil , I was unable to reproduce, going to put this on hold pending
- #27510

**Comment by BhuvaneshPatil** [comment] 2023-09-19 06:38
@mallenexpensify I think I mis-understood with what you have said.

To reproduce this issue we need more than 1 workspace.

When we select a workspace, notice is shows  check icon for all the workspaces

**Comment by BhuvaneshPatil** [comment] 2023-09-19 06:39
> @mallenexpensify This is known issue - https://github.com/Expensify/App/issues/27510

I was mentioning about the workspace detail not showing in selected participant, that is the issue linked.
This one is about, multiple workspace showing check icon when we select on workspace

**Comment by mallenexpensify** [comment] 2023-10-04 17:30
- #27510

Above closed and I'm unable to reproduce this so I'm closing
@BhuvaneshPatil and/or @robertKozik , if you're able to repro, please comment. 

https://github.com/Expensify/App/assets/22508304/12187bb5-25c2-4ade-90f8-7cae7b8498a1

**Closed by mallenexpensify** 2023-10-04 17:30 UTC
Labels: External, Weekly, Overdue
