### ISSUE TITLE
[$500] Allow Desktop AhDoc and Dev builds to be installed alongside production

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#24426] opened 2023-08-11 14:19 UTC
### Problem

We recently [enabled the ability](https://github.com/Expensify/App/issues/16805) to install mobile apps side by side, preventing the need to constantly reinstall and re-authenticate after testing a dev or AdHoc build. However, we didn't do the same thing for Desktop.

### Solution

Let's do the same thing for Desktop!

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af6dab8731944ef3</li>
        <li>Upwork Job ID: 1690005246967926784</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by Talha345** [comment] 2023-08-11 18:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We want to allow multiple builds for each environment to be installed concurrently on a system.

### What is the root cause of that problem?

This was never implemented which can bee seen in the config [file](https://github.com/Expensify/App/blob/main/config/electronBuilder.config.js) as we have static values for appID, productName, and dmg etc.

### What changes do you think we should make in order to solve the problem?

We can make the configuration file dynamic and generate separate builds for each environment by making the following changes:

```
const appIds = {
    production: 'com.expensifyreactnative.chat',
    staging: 'com.expensifyreactnative.chat.staging',
    adhoc: 'com.expensifyreactnative.chat.adhoc',
};
```

Then we can use: `appId: appIds[process.env.ELECTRON_ENV]`.

Similarly, we should follow the same pattern and update productName for clarity like: 

```
productNames: {
    production: 'New Expensify',
    staging: 'New Expensify Staging',
    adhoc: 'New Expensify AdHoc',
},
```

and use it like `productName: productNames[process.env.ELECTRON_ENV]`.

Same hash can be used for the dmg section and the following configs can be updated under dmg:

```
title: productNames[process.env.ELECTRON_ENV]
artifactName: `NewExpensify-${process.env.ELECTRON_ENV}-${version}.dmg`,

```
### What alternative solutions did you explore? (Optional)

**Comment by jeet-dhandha** [comment] 2023-08-12 06:56
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Build desktop app separately for different environments

### What is the root cause of that problem?
- Dynamic Values are not used for below details (Currently only used for `s3Bucket`): 
    - productName
    - appId
    - dmg.title
    - dmg.artifactName
    - protocols.name (Optional - Only if needed.)

### What changes do you think we should make in order to solve the problem?
- We can use `process.env.ELECTRON_ENV` to set the values dynamically. (As suggested by everyone, i am just giving extra details, that's all.)

```js

const env = process.env.ELECTRON_ENV;

// Below can be used to set values for productName, dmg.title
const names = {
    production: "New Expensify",
    staging: "New Expensify Staging",
    dev: "New Expensify Dev",
    adhoc: "New Expensify Adhoc",
};

const artifactName = names[env].split(" ").join("") + ".dmg";

const appIds = {
    production: "com.expensifyreactnative.chat",
    staging: "com.expensifyreactnative.staging.chat",
    dev: "com.expensifyreactnative.dev.chat",
    adhoc: "com.expensifyreactnative.adhoc.chat",
};

```

- For logos we can use `ExpensifyCashLogo.js` to render logos dynamically. This was created for that sole purpose but haven't been used yet. (I don't know why.)

- Also we will need to update color in `new-expensify-dev.svg` from `.st2{fill:#002e22}` to `.st2{fill:#03D47C}`. Others like `new-expensify-staging.svg` and `new-expensify.svg` are already using above color.

- For other places like Share QR code, etc. can be updated using ExpensifyCashLogo.js.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by Julesssss** [comment] 2023-08-14 14:33
Thanks all. Given the relative simplicity of these changes, I think going with the first proposal is fine.

**Comment by Julesssss** [comment] 2023-09-11 07:27
We had some issues with the test builds, I just rebuilt and it should work this time.

**Comment by Julesssss** [comment] 2023-09-15 03:38
This isn't a regression, as it was up to me to verify this... but the prod builds are failing due to these changes. 

We're [defaulting](https://github.com/Expensify/App/actions/runs/6184283226/job/16810396238#step:6:131) to the Dev environment when building the prod app... 

```
 • signing         file=desktop-build/mac/New Expensify Dev.app identityName=Developer ID Application: Expensify, Inc.
```

**Comment by Julesssss** [comment] 2023-09-15 04:19
> Note: When running npm run build-desktop-adhoc locally, the build generated uses word marks of dev environment. This is because .env.adhoc file is missing on localhost.

@allroundexperts I think this happened, like you predicted.

**Comment by allroundexperts** [comment] 2023-12-01 02:00
@Julesssss @lschurr What's the update here? The PR got merged long time ago.

**Comment by Julesssss** [comment] 2023-12-21 15:33
Sorry, just saw this. 

I think we should just close the issue as it's unlikely we'll find time to work on this

@allroundexperts do we need a 50% payment to make this fair? We merged a change but had to revert

**Comment by allroundexperts** [comment] 2023-12-21 15:36
Yea, sounds good!

**Comment by Julesssss** [comment] 2023-12-21 15:57
Hey @lschurr would you mind paying out $500 to @allroundexperts please when you have a moment. Thanks

**Comment by allroundexperts** [comment] 2023-12-21 15:59
I get paid through the App @Julesssss. A payment summary comment is all I need 😄

**Comment by lschurr** [comment] 2023-12-22 19:35
Payment summary:

- Contributor+: @allroundexperts $500

**Comment by lschurr** [comment] 2023-12-22 19:35
I think we can close yeah?

**Closed by lschurr** 2023-12-22 19:35 UTC
Labels: Reviewing, External, Engineering, Monthly, Improvement

**Comment by JmillsExpensify** [comment] 2024-01-24 23:48
$500 payment to @allroundexperts based on comment above.
