### ISSUE TITLE
[$500] Web - Use is getting two magic codes upon signing in once

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30181] opened 2023-10-23 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1698035667000719

## Action Performed:
1. Log in with user: [kevin+p2p2@expensifail.com](mailto:kevin+p2p2@expensifail.com)

## Expected Result:
Use is getting only one magic codes upon signing

## Actual Result:
Use is getting two magic codes upon signing in once

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details> n/a

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f1bb78860f2e492</li>
        <li>Upwork Job ID: 1716502092203872256</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>samilabud | Contributor | 27500698</li>
</ul></li>
    </ul>
</details>

**Comment by samilabud** [comment] 2023-10-23 21:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Use is getting two magic codes upon signing in once

### What is the root cause of that problem?
When user account has SAML enabled and tries to login, the application sends the magic code(like when the users does not have SAML enabled) and displays a form for the user indicating that must selected how to be authenticated if using single sign-on or using magic code, at this point the user has a magic code in the mail but can't be used, so if the user selects the magic code authentication then he will get a second code.

### What changes do you think we should make in order to solve the problem?
We should send the magic code after confirm the user account has not SAML enabled.

**Comment by samilabud** [comment] 2023-10-24 15:50
## Proposal
[Updated](https://github.com/Expensify/App/issues/30181#issuecomment-1776016473)

**Comment by lschurr** [comment] 2023-10-26 15:51
@robertKozik could you review the proposal here?

**Comment by robertKozik** [comment] 2023-10-26 20:22
Hi @samilabud can you provide more information about the approach/implementation which you would carry out? Now your proposal is very general in my opinion

**Comment by samilabud** [comment] 2023-10-26 21:55
## Proposal
[Updated](https://github.com/Expensify/App/issues/30181#issuecomment-1776016473)
@robertKozik  please verify again

**Comment by lschurr** [comment] 2023-10-30 15:19
@robertKozik could you review the updated proposal?

**Comment by robertKozik** [comment] 2023-10-31 00:37
Thanks for updating the proposal @samilabud. I now have a clear understanding of your plan, and I'm fully on board with it.

🎀 👀 🎀 C+ reviewed

**Comment by lschurr** [comment] 2023-11-02 16:07
@madmax330 could you do a quick review on this one?

**Comment by robertKozik** [comment] 2023-11-27 21:55
Still in review process

**Comment by samilabud** [comment] 2024-01-14 00:46
Hi @robertKozik please check again when you get a chance please 🙏🏼

**Comment by allroundexperts** [comment] 2024-01-16 23:56
Taking this over!

**Comment by samilabud** [comment] 2024-03-11 19:51
I have updated the PR last week, could you check @allroundexperts ?

**Comment by allroundexperts** [comment] 2024-03-11 19:52
Sorry, this never showed up in my reviews. @lschurr can you please re-open this and assign the PR to me?

**Comment by allroundexperts** [comment] 2024-05-07 20:46
This has pending payments. @lschurr can you please help?

The PR got reviewed and merged successfully. However, the underlying issue was fixed from the backend so the changes were not needed anymore. As such, the PR was later reverted.

**Comment by lschurr** [comment] 2024-05-07 21:09
Thanks @allroundexperts - Just clarifying, the Upwork job on this GH is just assigned to @samilabud. Is that the only payment for this one? Or is there a different PR I should be looking at?

**Comment by allroundexperts** [comment] 2024-05-07 21:10
@lschurr I get paid via New dot, so a payment summary would be all that's required for me.

**Comment by JmillsExpensify** [comment] 2024-06-28 17:26
Re-opening for the payment summary for @allroundexperts

**Comment by allroundexperts** [comment] 2024-06-28 17:59
Hi @JmillsExpensify!

Why did you close this?

**Comment by lschurr** [comment] 2024-07-01 18:04
Payment summary:

- Contributor: @samilabud $500 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/35339516/overview))
- Contributor+: $500 @allroundexperts (to be requested in NewDot)

**Comment by JmillsExpensify** [comment] 2024-07-01 19:40
$500 approved for @allroundexperts

**Comment by twisterdotcom** [comment] 2024-11-18 17:05
Relabelling as Lauren is OOO now.

**Comment by stephanieelliott** [comment] 2024-11-22 03:19
> Payment summary:
> 
> Contributor: @samilabud $500 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/35339516/overview))
> Contributor+: $500 @allroundexperts (to be requested in NewDot)

Not sure why this is still open, it seems like we're all done here? closing but please comment if this should remain open.

**Closed by stephanieelliott** 2024-11-22 03:19 UTC
Labels: Reviewing, External, Daily, Not a priority, Bug
