### ISSUE TITLE
[$1000] Web - The ampersand (&) is not displaying properly in the NewDot under the category selector

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34735] opened 2024-01-18 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705434349164419

## Action Performed:
1. Log in in Olddot as Admin of the Collet policy and invite Employee to the collect policy.
2. Add Category with ampersand (&)
3. Log in as Employee in NewDot
4. Select WS and  start requesting money
5. Open Category section

## Expected Result:
The ampersand (&) is displaying properly in the NewDot under the category selector

## Actual Result:
The ampersand (&) is not displaying properly in the NewDot under the category selector

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (46)](https://github.com/Expensify/App/assets/93399543/1c3cf051-301b-4884-9a38-46db68f59856)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd5614918bf77eaf</li>
        <li>Upwork Job ID: 1749541623825879040</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2024-01-22 21:16
This is reproducible with our NewDot testing policy with the categories that come from NetSuite.

**Comment by AliSinaYOusofi** [comment] 2024-01-22 22:15
one of my clients project had the same bug ( in a blogging website), the problem was with encoding/decoding of contents.

**Comment by AliSinaYOusofi** [comment] 2024-01-22 22:27
Contributor details
Your Expensify account email: tinayousofiali@expensify.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0158977eac7b003cfb

**Comment by situchan** [comment] 2024-01-25 14:42
No proposals yet

**Comment by FitseTLT** [comment] 2024-01-31 16:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The ampersand (&) is not displaying properly in the NewDot under the category selector

### What is the root cause of that problem?
The BE is returning html encoded categories.
### What changes do you think we should make in order to solve the problem?

We need to `_.unescape` or use `htmlDecode` in here
https://github.com/Expensify/App/blob/a44e80436248c8ec39a9e28d618364181a0df829/src/libs/OptionsListUtils.ts#L913-L914
### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment] 2024-01-31 19:41
Starting leave so re-assigning!

**Comment by situchan** [comment] 2024-02-01 11:05
> We have done a similar thing to tags to remove unnecessary escaping keys 

@FitseTLT can you please share permalink for this?

**Comment by FitseTLT** [comment] 2024-02-01 11:14
@situchan Here is an example code it is done in https://github.com/Expensify/App/pull/32365
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L816-L817

**Comment by situchan** [comment] 2024-02-01 11:43
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/34735#issuecomment-1919412901) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2024-02-01 12:12
I experienced this issue earlier but seems like recently fixed in backend for new categories.

But still doubt of old existing categories. Maybe related to `Maybe it's something to do with the category originally being imported from NetSuite?`
I asked folks [here](https://expensify.slack.com/archives/C049HHMV9SM/p1706789365745599?thread_ts=1705614422.974109&cid=C049HHMV9SM) and [here](https://expensify.slack.com/archives/C049HHMV9SM/p1706789247366549?thread_ts=1705434349.164419&cid=C049HHMV9SM) who reported this bug.

**Comment by rushatgabhane** [comment] 2024-02-01 12:14
yea it was a backend bug but it's fixed now.

**Comment by FitseTLT** [comment] 2024-02-01 12:27
I think it is dependent on where the categories are imported from but I don't think it is fixed in BE because now if u enter `&amp;` that will automatically be decoded in old dot and displayed as `&` but in ND it will display `&amp;`. I think we should refer to the person who reproduced it and created the issue.

**Comment by MonilBhavsar** [comment] 2024-02-02 06:01
Should this be fixed from backend? Do we have exact ways to reproduce this issue. I created similar category from oldDot and it is displayed correctly

**Comment by rushatgabhane** [comment] 2024-02-02 06:03
@MonilBhavsar yea this bug is already fixed. do nothing?

**Comment by situchan** [comment] 2024-02-02 06:04
@rushatgabhane this is not "do nothing" issue. Please check https://expensify.slack.com/archives/C049HHMV9SM/p1705434349164419

**Comment by rushatgabhane** [comment] 2024-02-02 06:05
ah thanks! looks like it's a backend bug then

**Comment by MonilBhavsar** [comment] 2024-02-02 06:07
Yes, some users are still experiencing this bug

**Comment by FitseTLT** [comment] 2024-02-02 08:32
> ah thanks! looks like it's a backend bug then

I don't think this should be considered as a BE issue. This is issue is similar to https://github.com/Expensify/App/issues/30734 which is `Parent: Child` tags were displaying with escaping slash before colon (`Parent\: Child`) but in OD it unescapes it automatically when it displays it and What was finally decided in [here](https://github.com/Expensify/App/issues/32203#issuecomment-1847630109) is that we need to even return to the BE as escaped and only unescape it when we display it as it is how OD is sending to the BE and we re-implemented it.

**Comment by MonilBhavsar** [comment] 2024-02-05 08:48
Made this internal while I figure the root cause

**Comment by MonilBhavsar** [comment] 2024-02-09 11:10
Discussing it here https://expensify.slack.com/archives/C03TQ48KC/p1707467669800489

**Comment by muttmuure** [comment] 2024-02-12 15:55
@MonilBhavsar @cead22's comment is here:

> I think ideally we don't store html encoded things in the DB, and we encode/escape them before displaying them.
> Is there a way to add a category in old dot today with & that gets stored as &amp; in the database? If so, do we know why?
> Is there a way to add a category in old dot with &amp; that gets displayed as &amp;? If not, do we know why?
> I think it's fine to do nothing for old dot, but I think we shouldn't compromise on new dot, and if we agree the ideal is not html-encoding when storing in the DB (and only sanitizing for Bobby Tables), and the html-encoding (or escaping) when displaying them, we should do that


Are all of your questions answered?

**Comment by MonilBhavsar** [comment] 2024-02-14 11:04
Yes answered. I think we all agree that we do nothing for categories added in oldDot but take necessary steps for categories added in newDot. So I am going to create a new issue for wave8 - simplified collect to ensure categories added from newDot are always decoded across all layers of the app.

**Comment by MonilBhavsar** [comment] 2024-02-14 12:23
Closing in favor of https://github.com/Expensify/App/issues/36473

**Closed by MonilBhavsar** 2024-02-14 12:23 UTC
Labels: Engineering, Daily, Internal, Bug
