### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] User without display name shows two same emails on mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21245] opened 2023-06-21 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Click on new chat and provide an email of a User B (new user)
3. Click on header of chat and copy the email of User B
4. Go to the chat composer and type @ and paste the email and notice that for the user that has no display set, two same emails are shown. For users without display name, one email should have shown.
## Expected Result: 
User without display name should show one email on mention
## Actual Result: 
User without display name shows two same emails on mention

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7b7e3272-1985-4f39-ab99-417503463ed8

<img width="957" alt="Screenshot (373)" src="https://github.com/Expensify/App/assets/43996225/fa43ab2e-83ee-4134-b819-e6d4bc8084aa">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686819408619579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f9042e91e3c7e0f</li>
        <li>Upwork Job ID: 1672348765519577088</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-21 19:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User without display name shows two same emails on mention

### What is the root cause of that problem?
The user mention is displayed by the following code.
https://github.com/Expensify/App/blob/1e71ef26c27595f965549ed1db201738b77c2f56/src/components/MentionSuggestions.js#L67-L68

If the user has not set display name, `item.text` and `item.alternateText` are set to the email.

So two same emails are displayed.

### What changes do you think we should make in order to solve the problem?

If `item.text` and `item.alternateText` are equal, we can set `item.alternateText` to an empty string.
```
const styledHandle = item.text === item.alternateText ? '' : getStyledTextArray(item.alternateText, props.prefix);
```

### What alternative solutions did you explore? (Optional)

**Comment by flaviadefaria** [comment] 2023-06-23 21:00
I think this should be fixed to only display one email if the user does not have a name. Added the external label.

**Comment by alitoshmatov** [comment] 2023-06-24 07:30
@StevenKKC I think you should update your proposal to also conditionally render `Text` component here
https://github.com/Expensify/App/blob/b8aeec0bcf2cac06d51129f287f932ba0421ed4e/src/components/MentionSuggestions.js#L94-L106

**Comment by offroader** [comment] 2023-06-24 11:59
In the proposal above, you are going to remove/hide the handle (right part with grey color). I think it'd be better to remove left part (display name with bold font style) and keep handle, that would indicate that the suggested user doesn't have a display name, and all emails in the list would maintain same styling. What do you think?

**Comment by StevenKKC** [comment] 2023-06-25 01:12
@alitoshmatov Updated proposal(https://github.com/Expensify/App/issues/21245#issuecomment-1601569294).

**Comment by narefyev91** [comment] 2023-06-26 09:20
Proposal of @StevenKKC looks good to me https://github.com/Expensify/App/issues/21245#issuecomment-1601569294
Some code changes can be discussed in direct PR
🎀 👀 🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2023-06-27 23:15
Thanks @narefyev91 for reviewing the proposal, assigning @StevenKKC 🚀

**Comment by flaviadefaria** [comment] 2023-07-13 16:03
@narefyev91  can you please complete the checklist above so that I can process payment? Thanks!

**Comment by narefyev91** [comment] 2023-07-13 16:47
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/18951/files
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - https://github.com/Expensify/App/pull/18951/files#r1262815825
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - let's have this QA steps (in case that it was some regressions)
Test:
1. Open app and login with User A
2. Click on new chat and enter an email of a User B (new user)
3. Click on header of chat and copy the email of User B
4. Click on any chat and go to the chat composer
5. type @ and an email address of a User B who has not set display name
6. Verify that one email is shown.
Do we agree 👍 or 👎

**Comment by flaviadefaria** [comment] 2023-07-17 09:41
@priya-zha offer sent!
@StevenKKC -  I'm not sure that I have the right Steven in UW, to confirm, can you send me a link to your profile or confirm your name in UW? Thanks!

**Comment by StevenKKC** [comment] 2023-07-17 09:43
@flaviadefaria My upwork profile is https://www.upwork.com/freelancers/~0128670d4717009718. Thanks.

**Comment by flaviadefaria** [comment] 2023-07-18 10:19
@StevenKKC offer sent!

**Comment by StevenKKC** [comment] 2023-07-18 12:37
@flaviadefaria Thanks. Accepted.

**Comment by flaviadefaria** [comment] 2023-07-19 12:22
All done!

**Closed by flaviadefaria** 2023-07-19 12:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
