### ISSUE TITLE
User is able to request an IOU from Concierge

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20991] opened 2023-06-18 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign up with a new account
2. Click on 'Request money' link
4. Enter amount & Click on 'Next' button
5. Select 'Concierge' from the contacts section
6. Click on 'Request' button

## Expected Result: 
Concierge shouldn't be listed on the contacts section of an IOU flow
## Actual Result: 
Concierge is listed on the contacts section of an IOU flow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7c314ba9-80f6-4c98-8d9b-2c90d2bf91cf

<img width="955" alt="Screenshot (370)" src="https://github.com/Expensify/App/assets/43996225/b359729b-77c6-4e64-a331-b14437511a84">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687100910635549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment] 2023-06-18 18:34
On the video is a list of places where Concierge starts to appear after the latest staging release. 

[Screencast from 2023-06-18 21-31-32.webm](https://github.com/Expensify/App/assets/57330233/d9693957-41ec-409e-b4e7-f833c4def522)

**Comment by Pujan92** [comment] 2023-06-19 13:14
@Natnael-Guchima Is it only for new accounts bcoz I am not able to reproduce it?

**Comment by Natnael-Guchima** [comment] 2023-06-19 13:17
@Pujan92 I think it is only reproducible for new accounts with no prior chat history

**Comment by Pujan92** [comment] 2023-06-19 14:15
Ok, somehow not able to reproduce in dev.

**Comment by tjferriss** [comment] 2023-06-19 19:44
I'm able to reproduce the issue using a brand new account.

<img width="1353" alt="Screenshot 2023-06-19 at 12 43 28" src="https://github.com/Expensify/App/assets/8292562/afcf4fc9-5268-4297-a3d1-9f0807915a1a">

**Comment by luacmartins** [comment] 2023-06-19 20:55
More context [here](https://expensify.slack.com/archives/C07J32337/p1687190181349549). This Auth [PR](https://github.com/Expensify/Auth/pull/8141) seems to fix the issue. I'll remove the blocker label and put this issue on hold for the Auth deploy. Once we deploy, we should confirm this is fixed on staging.

**Comment by tjferriss** [comment] 2023-06-22 05:09
It looks like the Auth PR has been deployed. Can we take this off hold?

**Comment by neil-marcellini** [comment] 2023-06-23 16:54
Yep! @tjferriss would you please see if this is fixed on staging?

**Comment by neil-marcellini** [comment] 2023-06-26 16:36
Gentle bump @tjferriss

**Comment by Natnael-Guchima** [comment] 2023-06-27 10:56
This seems to be fixed on the latest release.

**Comment by neil-marcellini** [comment] 2023-06-27 15:54
Great, thanks you, closing this. No reporting bonus is needed since applause reported it.

**Closed by neil-marcellini** 2023-06-27 15:54 UTC
Labels: Engineering, Daily, Bug

**Comment by Natnael-Guchima** [comment] 2023-06-27 16:05
@neil-marcellini I am the one who reported this issue. You can find my name on the 'issue reported by' section.

**Comment by neil-marcellini** [comment] 2023-06-28 15:59
I responded on Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1687967956625009?thread_ts=1687100910.635549&cid=C049HHMV9SM).
