### ISSUE TITLE
App crashes when switching workspace from workspace switcher

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#51005] opened 2024-10-17 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Coming from https://expensify.slack.com/archives/C049HHMV9SM/p1729164622564699
**Version Number:** v9.0.50-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MonilBhavsar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729164622564699

## Action Performed:
Break down in numbered steps
1. Have a high traffic account with few workspaces and reports
2. Try to switch the workspace from the workspace and notice app crashes

## Expected Result:
Describe what you think should've happened
App should not crash and workspace should be switched
## Actual Result: 
Describe what actually happened
App crashes
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

<img width="1728" alt="Screenshot 2024-10-17 at 4 37 55 PM" src="https://github.com/user-attachments/assets/fe97be50-684b-4d29-b639-ea4a137f77f4">

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MarioExpensify** [comment] 2024-10-17 11:59
👀 into it. @MonilBhavsar do you have any sample account you can share so I can reproduce the issue?

**Comment by MonilBhavsar** [comment] 2024-10-17 12:01
It happens on my test account - monil+2@expensifail.com

**Comment by MonilBhavsar** [comment] 2024-10-17 12:19
I am now seeing infinite loaders :/
Could anyone please try these steps ^

**Comment by MarioExpensify** [comment] 2024-10-17 12:45
> I think this has something to do with switching between #focus and most recent mode.
> 
> I was seeing the crash consistently on each click. I am now trying to get it back by -
> 
> 1. Switch to #focus mode and logout
> 2. Signin again so very limited reports are fetched
> 3. Switch workspace
> 
> Currently, I see "Hmm, it's not there page" but not crash

I tried the above steps with my own Expensify account, I could not crash nor see infinite loaders, but it got stuck in focus mode (didn't load the rest of the chats when changed the mode to most recent). I had to logout and log back in to see everything back.

**Comment by trjExpensify** [comment] 2024-10-17 14:55
What are we doing with this issue then? 

>Btw, I still see infinite loading everywhere and broken URL

Is that being looked into somewhere else?

**Comment by MarioExpensify** [comment] 2024-10-17 15:38
I just got a Hight Traffic account following [this SO](https://stackoverflowteams.com/c/expensify/questions/14504), still cannot reproduce the issue in Staging (neither the crash nor the fail to load). Is there any other step we can go through before discarding this as a DeployBlocker? Just making sure I'm not forgetting any step and possibly causing some issues down the road @trjExpensify @MonilBhavsar

**Comment by trjExpensify** [comment] 2024-10-17 15:56
Nope, just the ones in the SO: https://stackoverflowteams.com/c/expensify/questions/9980

**Comment by MarioExpensify** [comment] 2024-10-17 16:08
Okay, thank you @trjExpensify, closing this one as specified in the SO.

**Closed by MarioExpensify** 2024-10-17 16:08 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
