### ISSUE TITLE
Dev: Web -  Web page not loading after clicking "View all receipts"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23635] opened 2023-07-26 12:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click settings > Workspaces > Reimbursements.
2. In "Capture receipts" click "View all receipts"
3. The external web page is not loading.

## Expected Result:
The external web page should load.

## Actual Result:
The external web page isn't loading.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45.8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e26df81d-3522-40a1-8e58-9b163f3398c9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyankrawat
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690357348100359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:37
Just getting to this since it was re-assigned from MattC. @Gonals can I request your input on (1) reproduction and (2) whether this is `external` or `internal`? It's a Dev issue so I can't reproduce it on my side.

I tried on production & staging, and it's working fine. I figure this is just on Dev.

**Comment by priyankrawat** [comment] 2023-07-31 14:28
Hey guys, just wanted to confirm if folks are rewarded for reporting bugs on Dev as this one was reported by me?

**Comment by ishpaul777** [comment] 2023-08-02 08:04
## Problem 
 - Web page not loading after clicking "View all receipts" 
 
## Root Cause 
One of below
1. the url for old dot dev is changed and we have not updated url [here](https://github.com/Expensify/App/blob/main/src/CONST.js#L471).

2. Olddot dev is down.

3. we are using this url just as placeholder on dev

**Comment by Gonals** [comment] 2023-08-02 09:42
@michaelhaxhiu, this is working fine for me in dev. I think it is just that contributors don't have access to dev oldDot. I think we can close this. Feel free to reopen if you disagree

**Closed by Gonals** 2023-08-02 09:42 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
