### ISSUE TITLE
[HOLD for Payment 2024-08-26][$400] Accounting - NetSuite - No error message if no option is selected for segment display

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46536] opened 2024-07-30 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/46155
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segment/record" button
10. Start adding a custom segment with any rendom data until the "How should this custom segment be displayed in Expensify?" step
11. Click on the "Next" button without making a selection
12. Click on "fix the errors"

## Expected Result:
There should be an error message to choose Tags or Report fields.

## Actual Result:
No error message given if no option is selected for segment display. Nothing happens if I click on "fix the errors".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/303779b0-bdf6-487d-8141-7ba0fbe76ebe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015eb22121c664b750</li>
        <li>Upwork Job ID: 1819084414296998813</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103426964</li>
<li>cretadn22 | Contributor | 103426965</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by izarutskaya** [comment] 2024-07-30 19:54
We think this issue might be related to the #wave-control.

**Comment by ikevin127** [comment] 2024-08-02 19:05
Will review today.

**Comment by ikevin127** [comment] 2024-08-03 02:18
@cretadn22 Thank you for the proposal. Unfortunately, your proposed solution does not attempt to address the issue as per the **Expected result** since it's proposing changing the type of form / form functionality instead of fixing the `fix the errors` button which currently does not seem to do anything to notify the user that they should choose one of the available options.

I will ask the design team their take on this and once we have a more detailed idea of what we want to do here from a visual POV, then you can update your proposal to match the expectations if still interested 🙂

##

@Expensify/design Do we have a specific design / behaviour for a form of this type when clicking `fix the errors` ?

If there's no predefined / expected behaviour, I'm wondering: what if when clicking `fix the errors` we highlight the first option, same behaviour like when the option is hovered over (see video below) but maybe with a blink animation or something similar to draw attention.

The main idea here is to fulfil the **Expected result** which says:
> There should be an error message to choose Tags or Report fields.

Which, as a developer I translate to:
Wwhen the user clicks on `fix the errors` - we should notify them visually that they have to choose one of the options.

**Wdyt ?**

<video src="https://github.com/user-attachments/assets/c996224f-50cc-4081-a894-2f6a075b30b8">

**Comment by dubielzyk-expensify** [comment] 2024-08-04 22:16
We generally have the first option pre-selected, but in this case I'm not sure that's desirable. 

I'd at least want the error message to simply just say "Please select an option above" or something like that. 

Keen to hear @Expensify/design thoughts oo

**Comment by shawnborton** [comment] 2024-08-05 13:30
Yeah, I agree with Jon's suggestion here.

**Comment by shawnborton** [comment] 2024-08-05 13:36
> Yes, I’ve noticed that in the initial step, the "Next" button doesn’t appear if the page is a selection list. Therefore, I recommend hiding the "Next" button on the Step 5 page and users move to the next page immediately after selecting an option.

I forget where we landed with this, but I thought we always wanted to show a Next button for selection lists when we are in one of these sequential stepper flows.

**Comment by shawnborton** [comment] 2024-08-05 13:56
How do we avoid this scenario then where an option is preselected and there's no way to advance to the next step?
![image](https://github.com/user-attachments/assets/972b7ae7-5c11-4771-a819-d325b39b4e8f)

**Comment by ikevin127** [comment] 2024-08-05 17:47
@cretadn22 I don't see any slear statement from @Expensify/design confirming which way we should go with the implementation.

Given this, please drop a video of the behaviour from your existing proposals for us to see and decide which version is desirable here.

**Note:** The reason why I suggested not rushing in a new proposal / assuming a decision **before** we have a clear response from the design team is because it might end up not being the desired behaviour.

In the future you can simply post a few vids of the behaviour of different versions - as that might be easier to review by design, and once confirmed you can safely update / post a new proposal.

**Comment by shawnborton** [comment] 2024-08-06 12:57
If we use option 1 though, we need to make sure the pre-selected item has a background color.

**Comment by dannymcclain** [comment] 2024-08-06 13:40
>Hmm I lean towards the section option here so that the user can choose which one they want first.

I think this is how I'm leaning too, just because it forces the user to make an active choice, which seems appropriate in this configuration setting.

>If we use option 1 though, we need to make sure the pre-selected item has a background color.

Regardless of the direction we go, the selected item needs a background color. Not sure why but this has been popping up so frequently lately. I wonder if there's anything we can do to make this "just work" a little bit better.

**Comment by shawnborton** [comment] 2024-08-06 13:56
I'm cool with option 2. To be clear though, we already have existing patterns for when you submit a form and no options are selected don't we?

**Comment by shawnborton** [comment] 2024-08-06 14:05
Any and all of our forms. When you use the submit button and the form is incomplete, we throw an error.

**Comment by ikevin127** [comment] 2024-08-06 20:48
@cretadn22's [updated proposal](https://github.com/Expensify/App/issues/46536#issuecomment-2269373151) looks good to me. The root cause was identified and the proposed main solution fixes the issue according to the discussion with the design team ([ref1](https://github.com/Expensify/App/issues/46536#issuecomment-2271360558), [ref2](https://github.com/Expensify/App/issues/46536#issuecomment-2271363414)) and the issue's **Expected result**.

♻️ **Proposal feedback:** The proposal's solution wasn't detailed clearly enough in order to easily understand what / where code needs to be changed, for example where props like `errorText` and `styles` come from or to what FormProvider does `shouldHideFixErrorsAlert` needs to be passed in order to achieve the result proposed by the solution.

Keep in mind for future proposals that the proposal needs to be detailed enough such that anybody with access to the codebase can easily implement the solution, regardless of how familiar they are with the codebase.

##

<details>
<summary>For reference this is how the implementation will look</summary>

<img width="372" alt="Screenshot 2024-08-06 at 13 22 23" src="https://github.com/user-attachments/assets/27981e81-3d36-4a5d-b8a4-ee7acc168d68">

</details>

> [!note]
> ### PR Notes
> Make sure to use `translate` for the error message and have it placed in en / es translation files, more precisely in `workspace.netsuite.import.importCustomFields.customSegments.errors`.
>
> EN: `Please select one of the options listed above.`
> ES: `Por favor, seleccione una de las opciones enumeradas arriba.`
>
> ❗**Make sure to confirm the translations on Slack using the preview screen I attached above.**
> ℹ️ **Make sure to test the implementation well on all platforms.**


🎀👀🎀 C+ reviewed

**Comment by shawnborton** [comment] 2024-08-07 15:04
I think that would be my vote, since this is a sequential stepper flow, I like having the Next button at the bottom. Curious what the rest of the @Expensify/design team thinks though!

**Comment by dannymcclain** [comment] 2024-08-07 15:17
Makes sense to me to treat them the same! 

>since this is a sequential stepper flow, I like having the Next button at the bottom

We may want to go ahead and make this The Law™: Stepper flows _always_ use a next button at the bottom and never auto-advance upon selection.

**Comment by dubielzyk-expensify** [comment] 2024-08-08 04:44
I'm okay with that. Just be aware that in another flow around workspace cards we break this The Law™ then 😅 We can take that separate though.

**Comment by shawnborton** [comment] 2024-08-08 11:54
Usually design doesn't handle translation requests, cc @blimpich 

My best guess would be `Por favor elige una opción arriba` though

**Comment by blimpich** [comment] 2024-08-08 20:55
> Asking here: [expensify.slack.com/archives/C01GTK53T8Q/p1723118396756249](https://expensify.slack.com/archives/C01GTK53T8Q/p1723118396756249)

responded in thread

**Comment by ikevin127** [comment] 2024-08-11 01:12
PR is in `Review` and we're closing in for merge! 🚀

**Comment by slafortune** [comment] 2024-08-13 19:56
This is being worked on, it will have a 7-day regression period, so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by ikevin127** [comment] 2024-08-20 18:17
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-08-26]** according to yesterday’s production deploy from https://github.com/Expensify/App/pull/47091#issuecomment-2296918867.

cc @slafortune

**Comment by blimpich** [comment] 2024-08-21 19:12
@cretadn22 I agree, and I'm happy that we fixed a lot of small issues in addition to the original issue here. How about we bump it up to $400?

**Comment by ikevin127** [comment] 2024-08-26 07:15
cc @slafortune

**Comment by slafortune** [comment] 2024-08-26 17:32
@cretadn22 paid via [Upworks](https://www.upwork.com/nx/wm/workroom/38026929/overview)

**Comment by ikevin127** [comment] 2024-08-26 19:04
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44942
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44942/files#r1731682353
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Click on FAB - New workspace.
2. Enable "Accounting" in the "More features" page.
3. Navigate to "Accounting".
4. Connect to NetSuite and upgrade the workspace to Control when asked.
5. Wait for the sync to finish.
6. Navigate to Accounting - Import - Custom Segments/records.
7. Click on the "Add custom segment/record" button.
8. In the first step, Click on the "Next" button without making a selection.
9. Verify that a new error message appear: "Please select an option above.".
10. Start adding a custom segment until the "How should this custom segment be displayed in Expensify?" step.
11. Click on the "Next" button without making a selection.
12. Verify that a new error message appear: "Please select an option above.".

Do we agree 👍 or 👎.

cc @slafortune

**Comment by slafortune** [comment] 2024-08-26 19:45
@ikevin127 paid via [Upworks](https://www.upwork.com/nx/wm/workroom/38026859/overview)

**Closed by slafortune** 2024-08-26 19:45 UTC
Labels: Reviewing, External, Weekly, Bug
