### ISSUE TITLE
[HOLD https://github.com/Expensify/App/pull/35004] [$500] Message does not show marked as unread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35085] opened 2024-01-24 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706113206869959

## Action Performed:

1. Have newDot in a tab that's not focused (not entirely sure this is necessary)
2. Switch to another window (not entirely sure this is necessary)
3. Receive a message and click on the browser notification window

## Expected Result:
Message should be marked unread

## Actual Result:
Message is marked as read
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/8e71a7c0-26f9-42db-b12d-23d23ea60cd9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cf8b94333ea6d61</li>
        <li>Upwork Job ID: 1750221760012480512</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-25 00:44
https://github.com/Expensify/App/pull/35004 would fix this

**Comment by wildan-m** [comment] 2024-01-25 07:28
I'm not getting any browser notifications in new dot or locally, I've allowed the browser notification permission. Any setting that we have to enable?

**Comment by muttmuure** [comment] 2024-01-30 15:45
Let's put this on Hold and see if the linked PR fixes this

**Comment by jeremy-croff** [comment] 2024-01-31 04:15
Testing this on branch from https://github.com/Expensify/App/pull/35004
It will mark the LHN as unread where currently it will be read. ( half improvement )
However it does not place the unread marker on the message.

https://github.com/Expensify/App/issues/33680 seems like the same issue.

**Comment by jeremy-croff** [comment] 2024-02-02 23:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Messages that are unread do not show up as unread when the chat is already open and navigating to it from a notification.
This is only reproducable on chats that are already open. And it's not related to a notification.

### What is the root cause of that problem?
When a chat is open, we do not mark the messages as unread if they get received because this check prevents that https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsList.js#L233 as the last active time is when we opened the report, and all the messages after that are later and so it marks it all as read thinking you're active. Even when minimized and accessing from a notification deep link.

We don't have a way to reset that lastReadTimeRef yet, to compare against except for when we navigate away to another report.

### What changes do you think we should make in order to solve the problem?
What we can do is use app focus information with this hook: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/hooks/useAppFocusEvent/index.ts#L9
To reset that lastReadTimeRef when the user focuses on the chat again. That way it knows that the unread messages before that new timestamp, are actually new.

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-02 23:56
> I'm not getting any browser notifications in new dot or locally, I've allowed the browser notification permission. Any setting that we have to enable?

The conditions for the browsers notification to trigger are:
Allow chrome notifications from OS
Allow expensify notifications from chrome
Send a message to a minimized chrome

**Comment by muttmuure** [comment] 2024-02-05 17:03
OK so the linked PR is also being proposed to be held.

**Comment by muttmuure** [comment] 2024-02-05 17:04
In which case, which issue should we pursue here? Can this issue be fixed independently of what you're suggesting here?  

https://github.com/Expensify/App/issues/34829#issuecomment-1924443959

**Comment by muttmuure** [comment] 2024-02-05 17:04
Taking off hold

**Comment by jeremy-croff** [comment] 2024-02-05 17:09
> In which case, which issue should we pursue here? Can this issue be fixed independently of what you're suggesting here?
> 
> [#34829 (comment)](https://github.com/Expensify/App/issues/34829#issuecomment-1924443959)

It looks like the final fix of the linked PR is going to only improve electron visibility. Making the fix independent of the issue mentioned here. Original fix of the linked PR would've also addressed this.

My latest proposal I posted here will address this issue seperately.

**Comment by akinwale** [comment] 2024-02-08 08:09
We can move forward with @jeremy-croff's [proposal](https://github.com/Expensify/App/issues/35085#issuecomment-1924916967) here.

🎀👀🎀 C+ reviewed.

**Comment by jeremy-croff** [comment] 2024-02-08 13:44
> We can move forward with @jeremy-croff's [proposal](https://github.com/Expensify/App/issues/35085#issuecomment-1924916967) here.
> 
> 🎀👀🎀 C+ reviewed.

Thank you! While I really appreciate the assignment, this might be already fixed by this pending PR:
https://github.com/Expensify/App/pull/35948

**Comment by aldo-expensify** [comment] 2024-02-08 20:17
> Thank you! While I really appreciate the assignment, this might be already fixed by this pending PR:
https://github.com/Expensify/App/pull/35948

Thanks @jeremy-croff for pointing that out, I guess we should hold on that and check if the issue persists after it is merged

**Comment by muttmuure** [comment] 2024-02-12 17:00
Still held on https://github.com/Expensify/App/pull/35948

**Comment by aldo-expensify** [comment] 2024-02-16 02:06
Changing to `Weekly` while on hold

**Comment by muttmuure** [comment] 2024-03-08 15:45
Still held

**Comment by jeremy-croff** [comment] 2024-03-14 01:46
@muttmuure This is now fixed as per https://github.com/Expensify/App/issues/33680
No need to hold, and I retested to confirm.

**Comment by aldo-expensify** [comment] 2024-03-20 00:38
> @muttmuure This is now fixed as per #33680 No need to hold, and I retested to confirm.

Thanks!, I'll close it then

**Closed by aldo-expensify** 2024-03-20 00:38 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
