### ISSUE TITLE
[$250] Search - App returns to expense report on Inbox after editing report field in Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47554] opened 2024-08-16 08:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has report fields.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Go to Search.
5. Go to Drafts.
6. Click on the View button next to the report title.
7. Click on any report field.
8. Edit the report field and save it.

## Expected Result:
App will remain on the expense report RHP on Search after editing report field.

## Actual Result:
App returns to the expense report on Inbox after editing report field in Search.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2025c2e7-2938-4349-89dc-90f9269cba60

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b90139d632f76bb</li>
        <li>Upwork Job ID: 1826366986418491339</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-08-16 08:18
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-08-16 09:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App return to the expense report after updating money report fields.

### What is the root cause of that problem?
When we submit the report fields edit, dismiss the modal with the expense report ID if it's not a report title.
https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/EditReportFieldPage.tsx#L78-L84

### What changes do you think we should make in order to solve the problem?

Use `goBack` instead.

**Comment by nkdengineer** [comment] 2024-08-16 09:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App returns to the expense report on Inbox after editing report field in Search.

### What is the root cause of that problem?
After we edit the report field, we dismiss the modal with `reportID` as the expense report then we will close the edit report field page and move to the report screen.

https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/EditReportFieldPage.tsx#L83

The same problem with the delete case
https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/EditReportFieldPage.tsx#L90
### What changes do you think we should make in order to solve the problem?
We should just use go back as we do in the money request flow [here](https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/iou/request/step/IOURequestStepAmount.tsx#L131)

OPTIONAL: we can add the fallback route to the expense report

https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/EditReportFieldPage.tsx#L83

https://github.com/Expensify/App/blob/5d098460c6800ae49d52c24b05662f5179c6aaf2/src/pages/EditReportFieldPage.tsx#L90
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-08-22 00:35
Looks like a dupe https://github.com/Expensify/App/issues/47179

**Comment by ikevin127** [comment] 2024-08-22 19:18
✅  Issue was addressed in already opened PR https://github.com/Expensify/App/pull/47721#issuecomment-2305463989 that is soon to be merged.

**Comment by s77rt** [comment] 2024-08-22 19:19
@greg-schroeder Let's close this

**Comment by greg-schroeder** [comment] 2024-08-22 20:08
done

**Closed by greg-schroeder** 2024-08-22 20:08 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by bernhardoj** [comment] 2024-08-26 13:33
@greg-schroeder after updating the report fields, it doesn't navigate to the large expense report screen, but it still closes the report RHP.

https://github.com/user-attachments/assets/ef125312-d56b-4bfd-a570-463e9bf6b556
