### ISSUE TITLE
[HOLD for Payment 2023-12-21] [$500] App is calling OpenApp instead of ReconnectApp when reloading the page

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#32590] opened 2023-12-06 21:17 UTC
Context https://expensify.slack.com/archives/C03SDMF9YJ2/p1701887907195709 (private)

OpenApp should _only_ be called when we are first initializing the app (after login basically) and ReconnectApp in any other case, but right now, we always call OpenApp on every reload, which is wrong.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b01257e6ae73d2aa</li>
        <li>Upwork Job ID: 1732509709419290624</li>
        <li>Last Price Increase: 2023-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28015537</li>
<li>paultsimura | Contributor | 28015538</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-06 22:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
OpenApp is called on every page refresh.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/d180ba9d9d53898397363a1cba5add7918e31e4c/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L149-L150

### What changes do you think we should make in order to solve the problem?

We should add a condition inside SessionUtils.isLoggingInAsNewUser to early return false if eventually no email was found by matching the URL:

```js
    if (!!sessionEmail && !linkedEmail) {
        return false;
    }
```

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/SessionUtils.ts#L4-L26



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-12-07 10:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`OpenApp` is called on every page refresh.

### What is the root cause of that problem?
**Disclaimer:** There will be a lot of text, but please try to keep up with my thoughts as I tried a [simpler solution](https://github.com/Expensify/App/issues/32590#issuecomment-1843791975), but it looks like a workaround, and while investigating, I found a deeper issue with the session handling. The RCA is long, the solution will be simple.

This particular issue comes from https://github.com/Expensify/App/issues/29013, where the author had an intention to fix the case when there was an attempt to log in to different accounts during one session:
1. Try login as a suspended user
2. Go back
3. Log in with a real user

For some reason, it was decided to use the `SessionUtils.isLoggingInAsNewUser`, which isn't supposed to be here, as its purpose is to handle the transition URLs, which contain `email` in the URL params.

We already were checking the `SessionUtils.didUserLogInDuringSession`, which should do the job for that issue, but the `didUserLogInDuringSession` was (and is) working incorrectly.

#### Now to the actual investigation of the `didUserLogInDuringSession` logic:

This function is intended to indicate whether a user was logged in during the session – meaning there was no page reload after the login, or the user did not open the app being already logged in.

It relies on the Onyx `SESSION` updates, and this is the root cause of the incorrect behavior:

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/SessionUtils.ts#L30-L45

However, when logging in as a suspended user, and clicking "back", we explicitly call `redirectToSignIn`, which resets Onyx data and the `loggedInDuringSession` value:

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/signin/EmailDeliveryFailurePage.js#L78

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/actions/SignInRedirect.ts#L76-L84

And now we are redirected back to the SignIn page, relying on the Onyx `SESSION` update to set the `loggedInDuringSession` again to `true`, which will never happen because the Onyx `SESSION` does not change: it already was in the default state when signing in as a suspended user, so calling `clearStorageAndRedirect` did not make any change to the `SESSION` key, therefore the `Onyx.connect` in `SessionUtils` was not triggered and the `didUserLogInDuringSession` remains `undefined` after reset, which makes the `SessionUtils.didUserLogInDuringSession()` an unreliable source of truth. This all can be verified by adding corresponding logs inside the `Onyx.connect` in `SessionUtils` to track setting and resetting the value of `loggedInDuringSession`.

### What changes do you think we should make in order to solve the problem?
**First**, we should change the logic of the reset function to set the value to `true` instead of `undefined`. This is a safe change since resetDidUserLogInDuringSession is called only on `redirectToSignIn`, therefore we expect that when a user lands on the `SignIn` page, the sign-in process will be initiated, and we'll make use of `loggedInDuringSession = true` after the successful sign in.

```js
function resetDidUserLogInDuringSession() {
    loggedInDuringSession = true;
}
```

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/SessionUtils.ts#L47-L49

**Second**, remove the change introduced in https://github.com/Expensify/App/issues/32590, since now this logic will be handled by the fixed `SessionUtils.didUserLogInDuringSession()`:

```js
const shouldGetAllData = !!isUsingMemoryOnlyKeys || SessionUtils.didUserLogInDuringSession();
```
https://github.com/Expensify/App/blob/d180ba9d9d53898397363a1cba5add7918e31e4c/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L150

### What alternative solutions did you explore? (Optional)

**Comment by chiragsalian** [comment] 2023-12-08 23:52
I think the proposal sounds good to me too.
Feel free to create the PR @paultsimura

**Comment by paultsimura** [comment] 2023-12-09 07:58
Thank you. The PR is ready for review: https://github.com/Expensify/App/pull/32775

**Comment by paultsimura** [comment] 2023-12-15 14:19
PR was deployed to production on Dec 14, the automation didn't work 🤔 
cc: @sonialiap

**Comment by sonialiap** [comment] 2023-12-15 14:22
Thanks for the ping, Pavlo! I'll update the issue title manually

**Comment by sonialiap** [comment] 2023-12-22 09:42
@paultsimura $500 - paid ✔️ 
@fedirjh $500 - paid ✔️

**Closed** 2023-12-22 09:46 UTC
Labels: Reviewing, External, Weekly, Bug
