### ISSUE TITLE
[HOLD for payment 2024-03-04] [$250] Remove MoneyRequestCategoryPage.js and copy any changes since Nov 27 into IOURequestStepCategory.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34606] opened 2024-01-16 20:46 UTC
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `MoneyRequestCategoryPage`
**New Component** `IOURequestStepCategory`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa1b22b861ac0e42</li>
        <li>Upwork Job ID: 1747632761920925696</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28129737</li>
<li>dukenv0307 | Contributor | 28130978</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2024-01-16 21:06
Please add a proposal for the changes that are necessary (I know I gave a brief overview, but your proposal should cover more details as I copy/pasted that into at least a dozen issues).

**Comment by lindseydortch** [comment] 2024-01-16 23:35
## Please re-state the problem that we are trying to solve in this issue.
We want to remove the `MoneyRequestCategoryPage` logic into `IOURequestStepCategory` and copy the changes from November 27 onward. 

## What is the root cause of that problem?
This is a part of the Wave 5 cleanup effort, so the goal is to refactor the navigation among screens. 

## What changes do you think we should make in order to solve the problem?
1. A new component `` will be created
2. There is only one change since November 27  which moved the location of the `useThemeStyles` import was changed to Line 10 instead of 13, so the file can be copied over as is. 
https://github.com/Expensify/App/blob/a7a3e7feec0c4da822779c4c0f0657f2fcbeeb62/src/pages/iou/MoneyRequestCategoryPage.js#L10
3 and 4. The only instance where this component is called and needs to be replaced with new component is 
https://github.com/Expensify/App/blob/a7a3e7feec0c4da822779c4c0f0657f2fcbeeb62/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L100
5. The route will then need to be updated in (if applicable) https://github.com/Expensify/App/blob/d9ee78d6614dbb8b620b5b362dbbc198dec6b8c5/src/ROUTES.ts#L363
6. I didn't see any updating logic in this file, so we should be able to skip this step here 

## What alternative solutions did you explore? (Optional)
N/A

**Comment by njmulsqb** [comment] 2024-01-17 01:38
I would love to take this!

**Comment by tgolen** [comment] 2024-01-17 14:59
As a reminder: comments like "I would like to work on this" have nothing to do with who is selected to do the work. I appreciate the gusto though! Please follow the contributor guidelines.

**Comment by anmurali** [comment] 2024-01-22 23:04
@thesahindia - can you review the two proposals above please?

**Comment by brunovjk** [comment] 2024-01-23 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove `MoneyRequestCategoryPage` and copy any changes since Nov 27 into `IOURequestStepCategory`

### What is the root cause of that problem?
This belongs to [Wave 5 cleanup](https://github.com/Expensify/App/issues/29107)
Phase 2 is all about removing the original components and any of the duplicated efforts.

### What changes do you think we should make in order to solve the problem?

> 1. Look at the history of the Old Component
> 2. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes

- From [history change](https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestCategoryPage.js)
We can see that only one update was made to the 'useThemeStyles' 'path'. This change is also seen in the [new component](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/pages/iou/request/step/IOURequestStepCategory.js#L6C36-L6C50).
- This way there will be **no need to arrange any changes** from `MoneyRequestCategoryPage` to be transferred to `IOURequestStepCategory`

> 3. Replace all uses of the Old Component with the New Component
> 4. Remove all traces of Old Component

- There's no use of `MoneyRequestCategoryPage` in any component. We can delete it.
- The new component has it [`StackNavigator`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L83), [`Navigation/linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L396), [`SCREENS.MONEY_REQUEST`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L126) and [`ROUTE`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L331-L335) already configured, we must remove `MONEY_REQUEST.CATEGORY` from the same places:

https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L100
https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L433
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L145
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L281-L284

- Also in [`Navigation/types.ts`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/types.ts#L210-L213) we need to update 
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/types.ts#L210-L213
to
```
    [SCREENS.MONEY_REQUEST.STEP_CATEGORY]: {
        transactionID: string;
        backTo: string;
    };
```

> 5. Be sure to update all routes and navigation to use the new :action param (instead of being hard-coded with "create")
> 6. Update any logic like isEditing to use the new action param from the route

- Update
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L331-L335
to
```
    MONEY_REQUEST_STEP_CATEGORY: {
        route: ':action/:iouType/category/:transactionID/:reportID?',
        getRoute: (action: ValueOf<typeof CONST.IOU.ACTION>, iouType: ValueOf<typeof CONST.IOU.TYPE>, transactionID: string, reportID: string, backTo: string) =>
            getUrlWithBackToParam(`${action}/${iouType}/category/${transactionID}/${reportID}`, backTo),
    },
```

- We dont need to update 
https://github.com/Expensify/App/blob/5edf172457de71f5fa77d9ddf30e03726db346a2/src/components/MoneyRequestConfirmationList.js#L749
Since we are goint to use this component:
https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L804


### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2024-01-25 10:23
I have the context of this epic. I can take over this issue as C+ contributor

**Comment by anmurali** [comment] 2024-01-29 23:30
Reassigned to you @DylanDylann

**Comment by DylanDylann** [comment] 2024-01-30 06:09
As discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949), we need to use `IOURequestStepCategory` in the create/edit flow for both request money and split bill flow

@brunovjk I appreciate your proposal with detailed implementation but your proposal doesn't all cases as above discussion

@dukenv0307 [Your proposal](https://github.com/Expensify/App/issues/34606#issuecomment-1896031635) look good to me 

🎀 👀 🎀 C+ reviewed

**Comment by amyevans** [comment] 2024-02-12 21:28
How's the review stage coming along @dukenv0307 @DylanDylann? Seems like progress might be a little stagnant, @dukenv0307 can you address @DylanDylann's feedback from last week in the PR? Thanks!

**Comment by anmurali** [comment] 2024-02-16 15:37
Rotating for backup during my OOO till Feb 29th

**Comment by stephanieelliott** [comment] 2024-02-19 23:25
PR is being actively reviewed

**Comment by stephanieelliott** [comment] 2024-02-27 02:39
PR was deployed to staging a few hours ago!

**Comment by stephanieelliott** [comment] 2024-03-05 01:23
This was deployed to prod on 2/28, seems the automation didn't work so am updating manually

**Comment by stephanieelliott** [comment] 2024-03-06 23:53
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $250 PAID via Upwork
 - Contributor+:  @DylanDylann $250 PAID via Upwork
 
 Upwork job is here: https://www.upwork.com/jobs/~01aa1b22b861ac0e42

**Closed by stephanieelliott** 2024-03-06 23:53 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
