### ISSUE TITLE
[$500] [Workflows] Workspace - Unable to auto update currency to USD for the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39444] opened 2024-04-02 20:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468674&group_by=cases:section_id&group_order=asc&group_id=283225
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace with HUF as default currency
3. Navigate to Workspace settings - More features
4. Enable workflows
5. Open workflows
6. Go offline
7. Go online
8. Click on "Connect bank account"
9. Click on "Update to USD"

## Expected Result:
I should be able to do it for the first time

## Actual Result:
Unable to auto update currency to USD for the first time. "Oops! It appears that your workspace currency is set to a different currency than USD. To proceed, please set it to USD and try again" message appears. I'm able to do it for the second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d2c3ef2c-472c-494d-854a-069052fcda4d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef1de5890d617574</li>
        <li>Upwork Job ID: 1775668746526109696</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-02 20:42
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-02 20:42
We think that this bug might be related to #wave-collect - Release 1

**Comment by sakluger** [comment] 2024-04-03 23:36
I agree this is a wave-collect bug.

**Comment by s77rt** [comment] 2024-04-04 04:08
I'm not able to reproduce

**Comment by s77rt** [comment] 2024-04-04 04:22
@GandalfGwaihir

> we allow the user to connect bank account even when the policy is still in draft stage i.e.CreateWorkspace has got a response from BE yet

Why do you think that the workspace is still in draft in this case? Also even if the CreateWorkspace is not done yet the UpdateWorkspaceGeneralSettings and OpenReimbursementAccountPage requests won't be made until the workspace is created

**Comment by nkdengineer** [comment] 2024-04-04 14:12
## Proposal
      
### Please re-state the problem that we are trying to solve in this issue. 
- Workspace - Unable to auto update currency to USD for the first time
### What is the root cause of that problem?
- Given these below steps:
1. We click to create new workspace, API ```CreateWorkspace``` is called. (If done, it will return ```outputCurrency: "EUR"```)
2. When the above API is in progress, open "More feature" screen then toggle "Workflows" feature, then we click on "Update to USD" API ```UpdateWorkspaceGeneralSettings``` is called. (If done, it will return ```outputCurrency: "USD"```).
3. If the API ```UpdateWorkspaceGeneralSettings``` is done before ```CreateWorkspace```, ```outputCurrency``` will be ```"EUR``` finally. So that leads to the bug.
### What changes do you think we should make in order to solve the problem?
- We can make sure before we click on "Update to USD", there is no persistent request.
- To do it, we can update [this](https://github.com/Expensify/App/blob/0b2f55fefa8519b86f58730a85e851409f631524/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L188) to:
```
                            disabled={isOffline || !isPolicyAdmin || !isEmpty(persistentRequests)}
```
- In the above, ```persistentRequests``` is from Onyxdata
```
    persistedRequests: {
        key: ONYXKEYS.PERSISTED_REQUESTS
    }
```

### What alternative solutions did you explore? (Optional)
- Instead of checking whether there is any persisted request like main solution, we can just make sure there is no persisted request like 'CreateWorkspace', 'OpenMoreFeaturePage', ... that will leads to the current bug

**Comment by s77rt** [comment] 2024-04-05 01:17
@nkdengineer Thanks for the proposal. Your RCA is not correct

> If the API UpdateWorkspaceGeneralSettings is done before CreateWorkspace

Write requests are sequential and follow the FIFO principal. The second request will be sent only after the first one is completed.

**Comment by s77rt** [comment] 2024-04-05 01:35
@GandalfGwaihir From your video I see that `OpenReimbursementAccountPage` is executed before `UpdateWorkspaceGeneralSettings` which is not the correct order. Let's investigate that

**Comment by nkdengineer** [comment] 2024-04-05 03:19
@s77rt I updated the RCA in my [proposal](https://github.com/Expensify/App/issues/39444#issuecomment-2037327220)

**Comment by s77rt** [comment] 2024-04-05 14:29
@nkdengineer Thanks for the update. I still don't think the RCA is correct/complete
> the outputCurrency will be EUR for a while, until the API in step 2 is successfully

Even if the currency is overwritten back to EUR. The bank page shouldn't load (OpenReimbursementAccountPage should not be be executed) until the currency is updated correctly to USD (after UpdateWorkspaceGeneralSettings is completed)

**Comment by s77rt** [comment] 2024-04-08 19:41
Still looking for proposals

**Comment by s77rt** [comment] 2024-04-11 20:58
Still looking for proposals

**Comment by s77rt** [comment] 2024-04-15 11:05
Same ^

**Comment by sakluger** [comment] 2024-04-17 19:28
@s77rt thoughts on @GandalfGwaihir's latest comment?

**Comment by s77rt** [comment] 2024-04-17 22:02
@GandalfGwaihir Thanks for the update. In this case can you please update your RCA explaining why we are seeing the problem and not what we are not doing? The error is based on `policy.outputCurrency` and that should be updated after `UpdateWorkspaceGeneralSettings`. Since we are seeing the error this means that the value is not updated correctly, let's investigate that

**Comment by s77rt** [comment] 2024-04-19 17:25
@GandalfGwaihir Thanks for the update. Your RCA is still not complete. Before we open the `ReimbursementAccountPage` we are making a call to `UpdateWorkspaceGeneralSettings` which updates the `policy.outputCurrency` both optimistically and on server's response. Why are we still seeing the error?

**Comment by nkdengineer** [comment] 2024-04-20 11:05
## Proposal
          
### Please re-state the problem that we are trying to solve in this issue. 
- The api ```OpenReimbursementAccountPage``` is called before ```UpdateWorkspaceGeneralSettings```.
### What is the root cause of that problem?
- Assume that theAPI are called in expected order: ```EnablePolicyWorkflows``` => ```UpdateWorkspaceGeneralSettings``` => ```OpenReimbursementAccountPage```. But in this case, the actual order is ```EnablePolicyWorkflows``` => ```OpenReimbursementAccountPage``` => ```UpdateWorkspaceGeneralSettings```, that leads to the bug. But why? Below is detail.

- After the API ```EnablePolicyWorkflows``` is called successfully, the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L74-L76.
- Calling ```pause``` will set ```isQueuePaused``` to ```true```.
- Then, because the ```isQueuePaused``` is ```true```, the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L58-L60
- Because ```Promise.resolve()``` is returned, leads to the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L130-L135
- Because ```resolveIsReadyPromise``` is called, leads to the below promise is resolved:
https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/libs/API/index.ts#L162
- As we can see, the API ```OpenReimbursementAccountPage``` is called.
### What alternative solutions did you explore? (Optional)
- We can update:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L188
to:
```
                            disabled={isOffline || !isPolicyAdmin || !!policy?.pendingFields?.areWorkflowsEnabled}
```

**Comment by nkdengineer** [comment] 2024-04-20 11:09
## Proposal
             
### Please re-state the problem that we are trying to solve in this issue. 
- The api ```OpenReimbursementAccountPage``` is called before ```UpdateWorkspaceGeneralSettings```.
### What is the root cause of that problem?
- Assume that the API are called in expected order: ```EnablePolicyWorkflows``` => ```UpdateWorkspaceGeneralSettings``` => ```OpenReimbursementAccountPage```. But in this case, the actual order is ```EnablePolicyWorkflows``` => ```OpenReimbursementAccountPage``` => ```UpdateWorkspaceGeneralSettings```, that leads to the bug. But why? Below is detail.

- After the API ```EnablePolicyWorkflows``` is called successfully, the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Middleware/SaveResponseInOnyx.ts#L36-L39
that leads to the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L74-L76
- Calling ```pause``` will set ```isQueuePaused``` to ```true```.
- Then, because the ```isQueuePaused``` is ```true```, the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L58-L60
- Because ```Promise.resolve()``` is returned, leads to the below logic is called:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Network/SequentialQueue.ts#L130-L135
- Because ```resolveIsReadyPromise``` is called, leads to the below promise is resolved:
https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/libs/API/index.ts#L162
- As we can see, the API ```OpenReimbursementAccountPage``` is called.
### What alternative solutions did you explore? (Optional)
- We can update:
https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L188
to:
```
                            disabled={isOffline || !isPolicyAdmin || !!policy?.pendingFields?.areWorkflowsEnabled}
```

**Comment by nkdengineer** [comment] 2024-04-20 11:11
@s77rt I removed my original proposal and posted a new [one](https://github.com/Expensify/App/issues/39444#issuecomment-2067640929) with the new RCA and solution

**Comment by s77rt** [comment] 2024-04-20 22:55
@nkdengineer Thanks for the update.

> After the API EnablePolicyWorkflows is called successfully, the below logic is called

That logic is only executed when the client is not in sync (missing onyx updates). We have an early return that occur in the rest of the cases https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Middleware/SaveResponseInOnyx.ts#L28-L30

Were you able to reproduce the missing onyx updates case?

**Comment by nkdengineer** [comment] 2024-04-21 01:10
@s77rt
> Were you able to reproduce the missing onyx updates case

 Yeah, I can reproduce it. First, I add the below ```log``` function to this [one](https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Middleware/SaveResponseInOnyx.ts#L36):
```
   console.log("**********************", {command: request.command})
```
- Here is the result:

https://github.com/Expensify/App/assets/161821005/d94abd55-83c1-4634-b7e6-f5f8ce51ce7f

**Comment by nkdengineer** [comment] 2024-04-21 01:25
Also, there are 2 things please help note:
- I tried to remove this [line](https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/libs/Middleware/SaveResponseInOnyx.ts#L38) and the bug is gone. 
- In the above video, the key point is that you need to click on "New workspace" and then toggle "Workflows" feature right after that.

**Comment by s77rt** [comment] 2024-04-21 22:00
@nkdengineer Thanks for checking that but the root cause is still unclear. Can you elaborate more? I see you got a not found view, perhaps its related.

**Comment by nkdengineer** [comment] 2024-04-21 22:39
@s77rt 

> I see you got a not found view, perhaps its related.

This will be fixed [here](https://github.com/Expensify/App/issues/39443)

**Comment by nkdengineer** [comment] 2024-04-21 22:42
> root cause is still unclear

Could you identify any unclear sections in my RCA so that I can make updates accordingly? Thank you.

**Comment by s77rt** [comment] 2024-04-22 19:45
@nkdengineer The chain effect makes sense but what trigged that chain is not clear i.e. why is the client out-of-sync? (specifically why this happens only in this scenario)

**Comment by nkdengineer** [comment] 2024-04-22 23:46
> why is the client out-of-sync

Here is what I see when creating a new workspace and then toggle workflow feature:
1. API ```CreateWorkspace``` returns ```lastUpdateID: 277284366``` and ```previousUpdateID: 277283967``` so we set ```lastUpdateIDAppliedToClient``` to ```277284366```.


2. Then API ```GetMissingOnyxMessages``` returns ```lastUpdateID: 277284259``` and ```previousUpdateID: 277283967``` so we set ```lastUpdateIDAppliedToClient``` to ```277284259``` 


3. Then API ```EnablePolicyWorkflows``` returns ```lastUpdateID: 277284459``` and ```previousUpdateID: 277284395```. In [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/libs/actions/OnyxUpdates.ts#L150), we compare the ```lastUpdateIDFromClient``` to ```previousUpdateID``` and because ```277284259``` < ```277284395```, so ```doesClientNeedToBeUpdated``` return ```true```

**Comment by s77rt** [comment] 2024-04-23 18:07
@nkdengineer Why in your case you are making a call to `GetMissingOnyxMessages`? This can't be related to `CreateWorkspace` alone. I can't reproduce the bug that way


https://github.com/Expensify/App/assets/16493223/97ff1f17-4517-402f-84fe-5d5cb1bc4f9b


https://github.com/Expensify/App/assets/16493223/fd88f1b0-b335-43e2-9952-33d045fb1bbe

**Comment by nkdengineer** [comment] 2024-04-23 20:22
> Why in your case you are making a call to GetMissingOnyxMessages

Do you always not encounter the call to ```GetMissingOnyxMessages```? From my perspective, there are times when ```GetMissingOnyxMessages``` is not called, and in those cases, the bug does not manifest

**Comment by s77rt** [comment] 2024-04-24 09:55
@nkdengineer We need to identify what trigger that in the first place and preferably fix it there.

**Comment by sakluger** [comment] 2024-04-27 00:05
Looks like the solution is still being discussed.

**Comment by s77rt** [comment] 2024-04-29 16:30
Not overdue. Still looking for clear RCA

**Comment by mvtglobally** [comment] 2024-05-01 14:01
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-05-01 19:42
Sounds like it's not reproducible, let's close the issue.

**Closed by sakluger** 2024-05-01 19:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
