### ISSUE TITLE
[HOLD for payment 2023-10-24] [$1000]  Android - Expensify logo zooms in when the app is opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26681] opened 2023-09-04 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Close the app if it is opened
2. Open the android app

## Expected Result:
The Logo should not zoom

## Actual Result:
The Logo zooms in when the app is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5af11f79-f3b0-4687-aaf1-c81bef080376

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693428178713599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7a9b095901075b6</li>
        <li>Upwork Job ID: 1698750724755542016</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>jo-ui | Reporter | 26923545</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-09-04 15:47
Possibly due to the Android alternate dimension resources. 

Not occurring on Android 13 Pixel 6A: 

https://github.com/Expensify/App/assets/10736861/34df5246-3f2a-475f-a705-015caa2dd990

**Comment by puneetlath** [comment] 2023-09-04 16:50
@Julesssss I see you assigned. Do you want to take this or shall I make it external?

**Comment by Julesssss** [comment] 2023-09-04 17:04
It can go external, I'm just taking the engineer manager duty as I'm familiar with native Android resources and can help triage the proposals (also I was tagged on the Slack thread)

**Comment by joh42** [comment] 2023-09-04 19:19
Not occurring on Oneplus 6 (with a 19:9 aspect ratio)

**Comment by jo-ui** [comment] 2023-09-04 19:46
I've tested it on android 12, Samsung galaxy A31 and A30s and it is reproducible

**Comment by Julesssss** [comment] 2023-09-11 10:14
> android 12, Samsung galaxy A31 and A30s and it is reproducible

Great, so let's open it up for contributors. Ideally someone with one of these devices.

**Comment by puneetlath** [comment] 2023-09-11 15:09
It's open! Waiting on proposals. Going to increase the bounty.

**Comment by PiyushChandra17** [comment] 2023-09-12 15:07
Seems like it's working fine on Android 12 (probably on all devices Pixel devices). @Julesssss @puneetlath 

https://github.com/Expensify/App/assets/47579287/de6f3ec7-684a-446e-b1a4-58a96684a553

**Comment by PiyushChandra17** [comment] 2023-09-12 15:29
@aimane-chnaif Thanks for the update. Also is it running on the dev or production ?

**Comment by Julesssss** [comment] 2023-09-13 02:17
> Seems like it's working fine on Android 12 (probably on all Pixel devices)

Yeah, it's occurring on other Android forks.

**Comment by Julesssss** [comment] 2023-09-18 02:39
Thanks @alex2bc. The Android scaleType sounds promising, but I can't really assign the issue to you without confirming this resolves the issue. 

Would you mind creating a PR without being officially assigned? Then I can create a build and ask QA to manually confrim the fix. If successful I will assign you. Let me know if that sounds good!

**Comment by Julesssss** [comment] 2023-09-26 05:20
Hey @zoontek, curious if you have any ideas about this bug or would like to work on it?

**Comment by zoontek** [comment] 2023-09-26 08:09
Yes, this is an issue with OneUI 4 (Samsung, Android 12). See https://github.com/zoontek/react-native-bootsplash/issues/466

The proposed fix will not work, as it happens on the system thread, not on the app one (Samsung failed to implement the  SplashScreen API properly)

It has been fixed on OneUI 5:

- https://issuetracker.google.com/issues/251807014
- https://issuetracker.google.com/issues/247486677
- https://issuetracker.google.com/issues/217891919

I'm currently working on a fix for react-native-bootsplash to pass a ratio using native constants for the problematic devices. I could apply it on the Expensify app once it's released (or directly switch back to the package since v5 is more or less the same as the custom implem I made here)

**Comment by Julesssss** [comment] 2023-09-26 08:55
That's great, thank you for your response!

I will happily hold this issue for you if you'd like to let us know if/when a fix is ready.

**Comment by zoontek** [comment] 2023-09-26 08:56
I will work on it this week. But will need external testers, as I don't have Samsung dev phones. Will keep you in touch 🙂

**Comment by mvtglobally** [comment] 2023-09-28 03:19
Issue not reproducible during KI retests. (First week)

**Comment by Julesssss** [comment] 2023-09-28 03:32
> Issue not reproducible during KI retests. (First week)

We believe this is unque to certain devices (OneUI 4)

**Comment by zoontek** [comment] 2023-09-28 08:46
@Julesssss I will probably ship this fix in react-native-bootsplash: https://github.com/zoontek/react-native-bootsplash/compare/master..fix-oneui-4-issue

The idea behind it is simple: It's appears that Samsung OneUI v4 render the splash screen icon at 0.5x of the correct size. Given [SplashScreen API image dimensions](https://developer.android.com/develop/ui/views/launch/splash-screen#dimensions), this means 288dp * 0.5 = 144dp.

![Frame 1](https://github.com/Expensify/App/assets/1902323/93492f04-04e0-4079-a480-71eea34a74c3)

We can't really fix the initial size during [the launch sequence](https://developer.android.com/develop/ui/views/launch/splash-screen#launch), as it's handled by the OS (OneUI v4). So I apply a dedicated background drawable in such case (with 144dp logo) + pass a 0.5 logo size ratio to the react-native app, which will update the logo accordingly (`react-native-bootsplash` offers a hook, `useHideAnimation`, that handles that for you)

Here's is a video where I invert the result of `isOneUI4()`:

https://github.com/Expensify/App/assets/1902323/31fbb440-2a47-4030-8571-3895f15077d5

You can see that it starts at normal size, but the fixed size is preserved once the app start + during the logo animation. When keeping `isOneUI4()` untouched, this would result in a complete launch sequence at 0.5x size for Samsung OneUI v4 devices.

Sure, this is not perfect. But without an OS update from Samsung, this cannot be fixed at app level. Having a smaller, but coherent logo seems the "less worse" solution.

What do you think? You think I can make a proposal out of this?

**Comment by Julesssss** [comment] 2023-09-28 09:14
Yeah, that's a reasonable solution given the limitations here. Please create a proposal and we'll go from there!

**Comment by Julesssss** [comment] 2023-09-28 12:10
Love it.

**Comment by zoontek** [comment] 2023-09-28 15:00
@Julesssss I applied on Upwork. Expect a PR next week.

**Comment by zoontek** [comment] 2023-10-02 19:00
@Julesssss The PR is here: https://github.com/Expensify/App/pull/28644

I also fixed [a regression currently on main](https://github.com/Expensify/App/commit/282105f59c13628655548f951bd6a00b4eae15ab#commitcomment-128934338) (which is clearly visible in [this video](https://github.com/Expensify/App/issues/26681#issuecomment-1715915309) - at the end we can see that the SVG is cut on the right)

**Comment by Julesssss** [comment] 2023-10-03 07:55
Thanks, that's great, look forward to testing once C+ has been reviewed.

**Comment by puneetlath** [comment] 2023-10-23 17:49
@ArekChr friendly reminder about the checklist.

**Comment by puneetlath** [comment] 2023-10-24 15:10
Just to clarify - @aimane-chnaif is the C+ on this PR, not @ArekChr is that right?

**Comment by ArekChr** [comment] 2023-10-25 09:26
@puneetlath Yes, @aimane-chnaif took over C+ role

**Comment by puneetlath** [comment] 2023-10-27 13:10
Ok cool. @aimane-chnaif do you get paid on NewDot or Upwork?

**Comment by puneetlath** [comment] 2023-10-30 15:04
All paid. Thanks everyone!

**Closed by puneetlath** 2023-10-30 15:04 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
