### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000] Web - Profile - Profile error is not dismissed even after opening further menus and coming back

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25405] opened 2023-08-17 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Click on profile pic and upload unsupported image eg: webp format image
5. Observe that app displays error below profile picture
6. Open any submenu like Display name, Contact method and revisit back to profile
7. Observe that error is still not dismissed

## Expected Result:
App should dismiss error on profile page as soon as we navigate to another page

## Actual Result:
App does not dismiss error on profile page even when we navigate to another page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b062e167-bb38-45ea-834a-0cd7458fc3a9

https://github.com/Expensify/App/assets/115492554/2fb00aaf-1716-46a9-a0ed-ea49cd050f45

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691319644122389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ab616209feb88d9</li>
        <li>Upwork Job ID: 1692451442740764672</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26401335</li>
<li>dukenv0307 | Contributor | 26401336</li>
<li>Dhanashree-Sawant | Reporter | 26401337</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-08-18 17:22
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Web - Profile - Profile error is not dismissed even after opening further menus and coming back

### What is the root cause of that problem?

We are using the state to save the errors in the `AvatarWithImagePicker` component here

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/components/AvatarWithImagePicker.js#L111-L113

### What changes do you think we should make in order to solve the problem?

Since we are moving towards functional components in the future, we should migrate the component to a functional one in this issue only.
After migration
In `AvatarWithImagePicker`, we can use `useImperativeHandle` to expose a method for clearing the errors 
```js
useImperativeHandle(ref, () => ({
    clearError() {
        setError(null, {});
    }
}));
```

And use it before Navigation calls like this by using ref `ref.current.clearError()`

Or

After refactoring, we can use `useIsFocused` hook from `@react-navigation/native` but this makes code a little complex

### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2023-08-21 11:40
Reviewing now!

**Comment by jjcoffee** [comment] 2023-08-21 11:54
@dukenv0307 [proposal](https://github.com/Expensify/App/issues/25405#issuecomment-1682408288) LGTM! It has the correct RCA and a good solution, so I'm happy to go with it.

@shubham1206agra's suggestion to migrate the component to a functional one is nice, but seems a bit out of scope for this issue. Happy to defer to the internal engineer if they disagree!

For completeness' sake - @namhihi237 and @lucentdevteam are duplicates of @dukenv0307's proposal.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by kaushiktd** [comment] 2023-08-23 13:01
### Please re-state the problem that we are trying to solve in this issue.
Profile error is not dismissed even after opening further menus and coming back

### What is the root cause of that problem?
We use Navigation.navigate to open other menus, ProfilePage is already in the stack navigator. when we go to the other menu and come back,
the state in avatarWithImagePicker is not changing that's why the error is shown.

### What changes do you think we should make in order to solve the problem?
In the AvatarWithImagePicker component, expose a method to clear the error directly using a regular class method on the below file:
https://github.com/Expensify/App/blob/main/src/components/AvatarWithImagePicker.js#L111-L113

```
class AvatarWithImagePicker extends React.Component {
// ... other code

clearError() {
this.setState({ validationError: null });
}

// ... other code
}

```

In our parent component, where we are rendering the `ProfilePage`, we can use a ref to call the `clearError` method on the `AvatarWithImagePicker` component here:
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.js

```
function ProfilePage(props) {
// ... other code
const avatarRef = useRef(null);
// ... other code
return (
<ScreenWrapper includeSafeAreaPaddingBottom={false}>
{/* ... other JSX */}
<ScrollView>
<AvatarWithImagePicker
ref={avatarRef}
// ... other props
/>
{/* ... other JSX */}
</ScrollView>
</ScreenWrapper>
);
}
```


When we want to navigate to a new screen, call the clearError method within MenuItemWithTopDescription component here
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.js#L131

```
onPress = {() => {
if (avatarRef.current) {
avatarRef.current.clearError();
}

Navigation.navigate(detail.pageRoute);
}}
```

change in `onPress` function here:
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.js#L139

```
onPress = {() => {
if (avatarRef.current) {
avatarRef.current.clearError();
}
 
Navigation.navigate(ROUTES.SETTINGS_PERSONAL_DETAILS)
}}
```

Video:
https://drive.google.com/file/d/1EJ5oEk_3MTHlBjNxWxrru3-ozDweRemo/view?usp=sharing

**Comment by laurenreidexpensify** [comment] 2023-08-23 14:33
@neil-marcellini is OOO, finding someoen else to review

**Comment by laurenreidexpensify** [comment] 2023-08-27 09:38
Neil is back on Monday, so we'll get review done then

**Comment by laurenreidexpensify** [comment] 2023-08-29 15:54
Bumped Neil in Slack :)

**Comment by neil-marcellini** [comment] 2023-08-30 00:20
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/25405#issuecomment-1682408288) also looks good to me. I do think it would be better if this followed our more typical error handling approach of storing the error message in Onyx and displaying an X button to dismiss the error message, but I'm not super passionate about it. What do you think @laurenreidexpensify? I'll hire @dukenv0307 now and we can change the plan later if we want.

**Comment by jjcoffee** [comment] 2023-08-31 08:28
@neil-marcellini In this case I think you'd see that the avatar hasn't updated and so navigating away from the page is a sort of implicit dismissal of the error message. Open to arguments though!

**Comment by laurenreidexpensify** [comment] 2023-09-12 16:16
We're ready to merge this one I believe

**Comment by jjcoffee** [comment] 2023-09-18 13:28
@laurenreidexpensify I think @neil-marcellini is OOO, should we assign another engineer?

**Comment by jjcoffee** [comment] 2023-09-29 08:31
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - looks like the behaviour was always there.
 - The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
 - A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
 - Determine if we should create a regression test for this bug. **No** - I don't think it's particularly impactful for an error to get "stuck".
 - If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by jjcoffee** [comment] 2023-09-29 08:32
@laurenreidexpensify Just noting that the PR was [approved](https://github.com/Expensify/App/pull/26148#pullrequestreview-1605545494) with a small change that was addressed within 3WD, then merging was delayed due to the internal engineer being OOO (as well as the merge freeze) so I think the timeliness bonus may be due here.

**Comment by neil-marcellini** [comment] 2023-10-02 17:24
Not overdue, bump @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2023-10-03 08:42
@jjcoffee agree - with synopsis, will adjust now

**Comment by laurenreidexpensify** [comment] 2023-10-03 08:47
Payment Summary:

- External issue reporter - @dhanashree-sawant $250, payment issued in Upwork
- Contributor that fixed the issue - @dukenv0307 $1000 + 50% bonus = $1500, payment issued in Upwork 
- Contributor+ that helped on the issue and/or PR - @jjcoffee $1000 + 50% = $1500, payment issued in Upwork

**Comment by laurenreidexpensify** [comment] 2023-10-03 08:53
@jjcoffee bump on regression steps + final checklist

**Comment by jjcoffee** [comment] 2023-10-03 08:58
@laurenreidexpensify Thanks! Checklist is completed [here](https://github.com/Expensify/App/issues/25405#issuecomment-1740512389).

**Comment by laurenreidexpensify** [comment] 2023-10-04 11:59
great thanks, we done!

**Closed by laurenreidexpensify** 2023-10-04 11:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
