### ISSUE TITLE
[HOLD for payment 2023-06-29] [HOLD for payment 2023-06-28] Tooltip not present on multiple avatar groups

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20934] opened 2023-06-16 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group to two people
2. In the LNH, hover over the grouped avatars
## Expected Result: 
Tooltips for the avatars should be displayed
## Actual Result: 
Tooltips are not displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d679e2a1-cf8d-4a69-bffb-23238a606b28

https://github.com/Expensify/App/assets/43996225/baca499b-e794-49cf-9a25-139398c0977e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686944792622739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment] 2023-06-16 20:01
# Proposal

## Please re-state the problem
Tooltip not present on multiple avatar groups

## What is the root cause of the problem?
The root cause is that the `ReportUtils.getAccountIDForLogin` function is not working properly due to the recent `accountID` migration.

## What changes do you think we need to make in order to fix this problem?
https://github.com/Expensify/App/blob/818ca92f837383b8d1d45512a4f44c7c95b16211/src/libs/ReportUtils.js#L854-L856
Now the `personalDetails` are changed to have `accountID` as keys instead of `login`. Therefore we need to fix this to iterate over the `allPersonalDetails` object until it finds the `login` and return the `accountID` for that account.

**Comment by iwiznia** [comment] 2023-06-19 15:42
This is a dupe of https://github.com/Expensify/App/issues/20716

**Comment by iwiznia** [comment] 2023-06-22 19:32
What? I closed this because it is a dupe Melvin, leave me alone!

**Comment by luacmartins** [comment] 2023-06-23 16:01
Gonna remove the blocker label so it doesn't show up in a future checklist if this ever gets reopened.

**Closed** 2023-06-23 16:01 UTC
Labels: DeployBlockerCash, Engineering, Weekly, Awaiting Payment, Bug
