### ISSUE TITLE
Adding Stop first in distance request leads to remove finsh point and other data

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29773] opened 2023-10-17 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rakshitjain13
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697268905255679

## Action Performed:
1. Click on '+' FAB icon
2. Click on Request Money Button
3. Click on Distance Tab
4. Click on add stop
5. select any address say Mumbai
## Expected Result: 
A stop should be added with user entered location
## Actual Result: 
Finish Point get missing and other information related to stop

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/8ad8341f-bf2b-4414-bc9b-a291883d72b3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/5366d85e-ac0b-4174-9856-f303ca5cc04e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/b8b7a05e-1929-42bb-92cb-53670442c471

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/7e9a8540-b7f4-4a31-b129-ff839d72a649

https://github.com/Expensify/App/assets/38435837/4a191437-09c9-400d-a2c6-eb025b3e0188

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-10-17 13:47
Dupe of https://github.com/Expensify/App/issues/29748

**Closed by conorpendergrast** 2023-10-17 13:47 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
