### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] Chat - After creating a money request, email are first displayed, then changed to set name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30456] opened 2023-10-26 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Request money -> Manually -> Use an account with set user name -> Request

## Expected Result:
The immediately installed username is displayed at the top of the page

## Actual Result:
At the top of the page, first, the email is displayed, and then it changes to the set username

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/31329490-f6ed-4727-994f-883ef8347a3e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef7eaea70e5f02e1</li>
        <li>Upwork Job ID: 1717582124675444736</li>
        <li>Last Price Increase: 2023-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27438378</li>
<li>bernhardoj | Contributor | 27438383</li>
</ul></li>
    </ul>
</details>

**Comment by peymancyb** [comment] 2023-10-26 18:24
I am checking this issue 👀

**Comment by cooldev900** [comment] 2023-10-27 01:20
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
After creating a money request, email are first displayed, then changed to set name in LHN.
### What is the root cause of that problem?
The root cause is because it returns displayName at the first time after creating a money request instead of firstname and lastname.
At that time, the displayName in allPersonalDetails[accountID] Object is an email address that represents user's login content.

https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/libs/ReportUtils.js#L1175-L1179

https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/libs/ReportUtils.js#L1189-L1197

### What changes do you think we should make in order to solve the problem?
So we need to check if the personalDetail includes firstName and lastNae and if it doesn't include, we can return displayName.
```
function getDisplayNameForParticipant(accountID, shouldUseShortForm = false) {
    if (!accountID) {
        return '';
    }
    const personalDetails = getPersonalDetailsForAccountID(accountID);
    const shortName = personalDetails.firstName || personalDetails.lastName || personalDetails.displayName;
    const longName = personalDetails.firstName ||  personalDetails.lastName ? `${personalDetails.firstName || ''} ${personalDetails.lastName || ''}` : personalDetails.displayName
    return shouldUseShortForm ? shortName : longName;
}
```
### What alternative solutions did you explore? (Optional)

If we don't want to change getDisplayNameForParticipant function, the backend should return correct displayName that include firstName and lastName in personalDetail. And we need to sync personalDetails data to backend after selecting participants when requesting money and also we should consider other edge cases.

**Comment by s77rt** [comment] 2023-10-27 13:08
@cooldev900 Thanks for the proposal. I don't think your RCA is correct. From what I can tell and based on the attached screenshot, we re-creating the personalDetails item object even though we have it. And by doing so we are overwriting the displayName field. Can you please recheck if that's the case?

**Comment by s77rt** [comment] 2023-10-27 15:17
@cooldev900 That's not what I meant. This is the flow:
1. personal details is holding the correct displayName (firstname lastname)
2. after making a money request, personal detaills' displayName is overwritten (email@test.com)
3. later the displayName is corrected from the backend (firstname lastname)

The bug is on step 2, which means that the bug is on the frontend and not the backend..

**Comment by cooldev900** [comment] 2023-10-27 15:23
oh, let me re-check now.

**Comment by cooldev900** [comment] 2023-10-27 16:12
It is personalDetails item before requesting money.
```
{
    "A15929525": {
        "accountID": 15929525,
        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_13.png",
        "displayName": "Name Name",
        "firstName": "Name",
        "lastName": "Name",
        "login": "ca19901101+test04@gmail.com",
        "pronouns": "",
        "timezone": {
            "automatic": true,
            "selected": "America/Chicago"
        },
        "payPalMeAddress": "",
        "phoneNumber": "",
        "validated": true
    },
    "P15929525": {
        "accountID": 15929525,
        "login": "ca19901101+test04@gmail.com",
        "displayName": "Name Name",
        "firstName": "Name"
    }
}
```
It is one right after requesting money.
```
{
    "A15929525": {
        "accountID": 15929525,
        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_6.png",
        "displayName": "ca19901101+test04@gmail.com",
        "firstName": "Name",
        "lastName": "Name",
        "login": "ca19901101+test04@gmail.com",
        "pronouns": "",
        "timezone": {
            "automatic": true,
            "selected": "America/Chicago"
        },
        "payPalMeAddress": "",
        "phoneNumber": "",
        "validated": true,
        "isOptimisticPersonalDetail": true
    },
    "P15929525": {
        "accountID": 15929525,
        "login": "ca19901101+test04@gmail.com",
        "displayName": "ca19901101+test04@gmail.com",
        "firstName": "Name"
    }
}
```
```
{
    "A15929525": {
        "accountID": 15929525,
        "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_13.png",
        "displayName": "Name Name",
        "firstName": "Name",
        "lastName": "Name",
        "login": "ca19901101+test04@gmail.com",
        "pronouns": "",
        "timezone": {
            "automatic": true,
            "selected": "America/Chicago"
        },
        "payPalMeAddress": "",
        "phoneNumber": "",
        "validated": true,
        "isOptimisticPersonalDetail": true
    },
    "P15929525": {
        "accountID": 15929525,
        "login": "ca19901101+test04@gmail.com",
        "displayName": "Name Name",
        "firstName": "Name"
    }
}
```
We are overwriting displayName twice after requesting money.

**Comment by s77rt** [comment] 2023-10-27 17:13
@cooldev900 Can you please update your proposal fixing this issue?

**Comment by cooldev900** [comment] 2023-10-27 17:49
Yes, I am doing.

**Comment by s77rt** [comment] 2023-10-28 10:23
@cooldev900 Thanks for the update. I still don't think your RCA is correct. The root cause is the displayName being overwritten in the first place.

For future proposal please don't write a new comment but instead update the existing one.

**Comment by s77rt** [comment] 2023-10-28 10:36
@bernhardoj Thanks for the proposal. Your RCA is correct. The solution looks good to me but we can keep the `isNewChatReport` condition for consistency*.

*The other issue was fixed by https://github.com/Expensify/App/pull/29279

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/30456#issuecomment-1783750558)

**Comment by grgia** [comment] 2023-10-30 15:04
Thanks for the proposal @bernhardoj, all yours!

**Comment by s77rt** [comment] 2023-11-07 21:22
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20679
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20679#discussion_r1385589394
- A discussion in #expensify-bugs has been started: I don't think this is needed here
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Login with a HT account
2. Request money from a user with a display name that you have not chatted with before
3. Verify the user display name is displayed correctly (in the report header)

**Comment by conorpendergrast** [comment] 2023-11-14 21:44
## Payouts due:

Issue Reporter: N/A - Applause
- [x] Contributor: $500 @bernhardoj - [contract paid and ended](https://www.upwork.com/nx/wm/workroom/35329706/overview)
- [x] Contributor+: $500 @s77rt - [contract paid and ended](https://www.upwork.com/nx/wm/workroom/35295629/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01ef7eaea70e5f02e1).

**Comment by conorpendergrast** [comment] 2023-11-14 21:54
Regression test request created: https://github.com/Expensify/Expensify/issues/336527

All done, thanks everyone!

**Closed by conorpendergrast** 2023-11-14 21:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
