### ISSUE TITLE
[$500] Web – Login –Contact method isn’t added to NewDot if verify secondary login in OldDot via link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36069] opened 2024-02-07 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4287005
**Email or phone of affected tester (no customers):** ponikarchuks+137224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in to NewDot with any account
3. Log into OldDot with the same account and add a Secondary Login from Account Settings e.g. [mypersonal+validateTest@gmail.com](mailto:mypersonal+validateTest@gmail.com)
4. Open validate secondary log in email Verify secondary email for Expensify and copy the last part of the URL, i.e. /v/16/WSSWMNNM (Everything after the /v/)
5. In a text box - Formulate the URL by using the path obtained from step 3 http://staging.new.expensify.com/v/
- E.g http://staging.new.expensify.com/v/12116/WSSWMNNMH
6. Navigate to the compiled link

## Expected Result:
Secondary login has been validated in NewDot

## Actual Result:
Secondary login / Contact method is not added to NewDot when try to verify secondary login in OldDot via the changet to NewDot magic link. Contact method is added to NewDot only after relogin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a50b3f1-70d8-41d4-b7e3-b8e8843dc55c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JordanLevy19** [comment] 2024-02-13 12:56
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
After verifying a secondary login or contact method through OldDot, this update is not immediately reflected in NewDot.
 
**What is the root cause of that problem?**
The root cause appears to be a synchronization issue between the backend and the NewDot application, particularly in how state updates (related to secondary login verifications) are managed and reflected within the UI. The ContactMethodsPage component doesn’t seem to update upon verification events, possibly due to limitations in the current subscription logic to Onyx keys or the handling of navigation routes related to contact methods.

**What changes do you think we should make in order to solve the problem?**

**Optimize Onyx Subscriptions**
Ensure that the components handling contact methods, especially ContactMethodsPage, subscribe more effectively to updates in ONYXKEYS.LOGIN_LIST and ONYXKEYS.SESSION. This would involve modifying the withOnyx wrapper to ensure immediate responsiveness to changes.

**Refine Navigation Logic**
Review the ROUTES.ts logic, focusing on routes that are directly related to managing contact methods (SETTINGS_NEW_CONTACT_METHOD, SETTINGS_CONTACT_METHOD_DETAILS, etc.). This would involve ensuring navigation to and from these routes triggers the appropriate state updates or UI refreshes.

**Comment by akinwale** [comment] 2024-02-14 17:17
The suggested solution in the [proposal](https://github.com/Expensify/App/issues/36069#issuecomment-1941460423) is vague and doesn't actually solve the issue.

**Comment by anmurali** [comment] 2024-02-16 15:17
Rotated the label since I will be OOO till 29th! I can take it back when I return!

**Comment by MitchExpensify** [comment] 2024-02-18 23:36
I don't think manually manipulating the link to include "new" is something any user is going to do - Closing

**Closed by MitchExpensify** 2024-02-18 23:36 UTC
Labels: External, Daily, Help Wanted, Bug
