### ISSUE TITLE
Web - Screen flickers when navigating back from workspace announce member details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23661] opened 2023-07-26 16:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the announce channel of any workspace
2. Click on the chat header to go to settings
3. Click on members link
4. From the members list, click on any member to go to the details page
5. Click on the back button in RHN to navigate back
6. Repeat steps 4 and 5 multiple times and notice the screen flickers (specially the expensify logo)

## Expected Result:
 Screen should not flicker

## Actual Result:
Screen is flickering

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ebe7a29f-8d56-4dbb-9121-655fa1896b06

https://github.com/Expensify/App/assets/93399543/0b045770-ff5f-407a-a94d-fc8e85e16061

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690365133184539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment] 2023-07-28 20:03
closing!

**Closed by NicMendonca** 2023-07-28 20:03 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by NicMendonca** [comment] 2023-08-11 18:56
I am still not able to reproduce this, or noticing anything out of the oridinary
