### ISSUE TITLE
[$250] Markdown - Space in the Code Block is removed after Manually copying and pasting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43331] opened 2024-06-08 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4606901
**Email or phone of affected tester (no customers):** dave0123seife+admin@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a 1:1 chat
2. Send a message with a Code block. Make the code block a multiline with an extra line between the markdown and text.
3. Manually Copy and paste the message with the code block

## Expected Result:
The correct markdown format is pasted

## Actual Result:
The markdown format removes the line space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e03a5c13-5f3a-487e-a84c-a479d2d3caa5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e40385be5828d12</li>
        <li>Upwork Job ID: 1802910270409896448</li>
        <li>Last Price Increase: 2024-07-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-06-08 14:08
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-08 14:08
We think that this bug might be related to #vip-vsp

**Comment by kpadmanabhan** [comment] 2024-06-10 10:48
@lanitochka17 : this is related to https://github.com/Expensify/App/issues/39971
This is on hold as PR for this is blocked due to another related issue.
Awaiting update.
CC: @jayeshmangwani / @roryabraham

**Comment by jayeshmangwani** [comment] 2024-06-10 11:03
@kpadmanabhan Are you sure this is related to https://github.com/Expensify/App/issues/39971 ?

I have tested again after applied the solution from the PR  https://github.com/Expensify/App/pull/42892 and it doesn't solve the current issue, can you please link between this issue and other one how they are related ?

**Comment by MitchExpensify** [comment] 2024-06-11 03:08
Not overdue, ball is in @kpadmanabhan 's court

**Comment by kpadmanabhan** [comment] 2024-06-13 23:30
@MitchExpensify / @jayeshmangwani : sorry for late response. On it now.

In main HEAD, copying using `Copy to Clipboard` menu item works fine with complete text from the code block. But using CTRL+C copies only the current text without the newline inside the code. 


https://github.com/Expensify/App/assets/76063588/ff40cd7b-e9f1-4150-aee2-4777ca6888d1



The fix for https://github.com/Expensify/App/issues/39971 will not solve this issue. The text is already trimmed while copying to clipboard. 
Working on this. Will update soon here.

**Comment by kpadmanabhan** [comment] 2024-06-14 11:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pasted code block trimming trailing newline characters.

### What is the root cause of that problem?
Two concerns from the initially reported problem. 
1. From the initial video recording in bug description, the text is NOT selected in full. Only 1 trailing newline is selected by selecting the text. To select the complete code block, one will need to go till end of code block till end of message. The same is demonstrated in the video recording further below.

2. Send button is not enabled because the trailing CR LF (\n) while pasting is not considered in selection and hence not considered in the range length.

`src\hooks\useHtmlPaste\index.ts`
```
const insertAtCaret = (target: HTMLElement, text: string) => {
        . . . 
        // Move caret to the end of the newly inserted text node.
        range.setStart(node, node.length);
        range.setEnd(node, node.length);
        . . . 
```

### What changes do you think we should make in order to solve the problem?
Check if this is a code block or is text having trailing newline, then calculate range accordingly with offset.

`src\hooks\useHtmlPaste\index.ts`
```
const insertAtCaret = (target: HTMLElement, text: string) => {
    . . . 

        // Move caret to the end of the newly inserted text node.
        // Text with newline at end or code block that ends with ``` 
        // These lines must be pasted in full and "Send" button enabled.
        // length reduced by an offset of 1 character to accommodate the trailing \n (CR LF) 
        const offset = text.trimEnd().endsWith('```') || text.endsWith('\n') 
            ? node.length - 1 : node.length;
        range.setStart(node, offset);
        range.setEnd(node, offset);
    . . . 
```
This makes sure that the correctly selected code block is pasted in full and send button is enabled.

https://github.com/Expensify/App/assets/76063588/4baa4629-ce7a-4a54-9a2b-2ec0fe8be913


### What alternative solutions did you explore? (Optional)
N.A.

**Comment by kpadmanabhan** [comment] 2024-06-14 11:29
@MitchExpensify / @jayeshmangwani / @lanitochka17 : if you think this solves the issue reported, please mark this bug external and kindly assign.

**Comment by msuleman526** [comment] 2024-06-18 21:09
You need to change the field to text area field and onPaste we need to handle the code. 

Code on handle paste: 
const text = cipboardData.getData('text/plain');
const formattedText = text.replace(/\r?\n/g, '\n');

Code is just a sample

**Comment by msuleman526** [comment] 2024-06-18 21:09
Contributor Details:
Expensive account Email: suleman.muh526@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c87dbd15282b0aef

**Comment by MitchExpensify** [comment] 2024-06-19 23:44
@eVoloshchak which proposal should we go with?

**Comment by eVoloshchak** [comment] 2024-06-20 13:34
@MitchExpensify, we might want to put this on hold for https://github.com/Expensify/App/issues/39971, which in turn is held for https://github.com/Expensify/App/issues/42216. Both already have PR's open, this issue _might_ be resolved after applying both

**Comment by jayeshmangwani** [comment] 2024-06-20 13:40
@eVoloshchak I think Space in the code block will not be resolved in this PR https://github.com/Expensify/App/issues/39971. I'm not sure if this will issue https://github.com/Expensify/App/issues/42216 will solve the current issue, but in my opinion, both have different RCAs

**Comment by kpadmanabhan** [comment] 2024-06-20 13:44
@eVoloshchak I think we should not create so many inter-dependencies. It is better to address each separately with it's defined scope.

**Comment by kpadmanabhan** [comment] 2024-06-24 17:45
@eVoloshchak / @MitchExpensify : bumping up for response based on [this comment](https://github.com/Expensify/App/issues/43331#issuecomment-2180744029) and [this comment](https://github.com/Expensify/App/issues/43331#issuecomment-2180736291).

**Comment by MitchExpensify** [comment] 2024-06-25 04:22
Putting on hold for the time being based on your recommendation, but what do you think about @kpadmanabhan 's [comment](https://github.com/Expensify/App/issues/43331#issuecomment-2180736291) @eVoloshchak ?

**Comment by MitchExpensify** [comment] 2024-07-01 21:25
Bump @eVoloshchak

**Comment by eVoloshchak** [comment] 2024-07-04 13:41
Applied both solutions from https://github.com/Expensify/App/issues/39971 and https://github.com/Expensify/App/issues/42216, @jayeshmangwani is correct, this does not solve our issue

**Comment by eVoloshchak** [comment] 2024-07-04 13:47
@kpadmanabhan, your [proposal](https://github.com/Expensify/App/issues/43331#issuecomment-2167821876) doesn't resolve the issue for me, there's still one line removed from the code block, could you double-check is this is still working for you please?

But most importantly, if we use the `Copy from clipboard` action instead of copying the message manually, the caret position is invalid: 

https://github.com/Expensify/App/assets/9059945/f423fe81-4086-48be-a777-d7dcd823d8e0

**Comment by MitchExpensify** [comment] 2024-07-04 19:24
Off hold!

**Comment by kpadmanabhan** [comment] 2024-07-04 20:15
@eVoloshchak : please refer to the second video recording in [my proposal](https://github.com/Expensify/App/issues/43331#issuecomment-2167821876). 
There I select, not just till end of code block, but till end of outside of code block message. This selects the entire code block and no lines are removed in this case.  In your recording [here](https://github.com/Expensify/App/issues/43331#issuecomment-2209045025), you are not selecting till outside of the code block message, which is the reason the last newline is not selected and hence not pasted.
 
As I mentioned in the root cause, there are 2 points. One is how much we click and drag and select. The other is the code fix that I have proposed.

**Comment by eVoloshchak** [comment] 2024-07-08 14:57
> Send button is not enabled because the trailing CR LF (\n) while pasting is not considered in selection and hence not considered in the range length.

@kpadmanabhan, could you double-check if this is still reproducible for you?

**Comment by kpadmanabhan** [comment] 2024-07-12 05:41
> could you double-check if this is still reproducible for you?
@eVoloshchak I will test with latest main and with my changes and then let you know. 
Looks like @jayeshmangwani and @mallenexpensify are facing strange issues in staging as well. Need to check what's going wrong.

**Comment by kpadmanabhan** [comment] 2024-07-13 22:34
> @kpadmanabhan, could you double-check if this is still reproducible for you?

@eVoloshchak :
https://github.com/Expensify/App/pull/42892#issuecomment-2227120479

**Comment by MitchExpensify** [comment] 2024-07-16 17:45
Reassigning as I'm heading on leave 🙇

**Comment by adelekennedy** [comment] 2024-07-18 23:32
@kpadmanabhan taking this over from Mitch - it sounds like from your last comment that this issue isn't reproducible but you're running into a similar issue?

**Comment by kpadmanabhan** [comment] 2024-07-19 07:56
@adelekennedy that's correct. However I will test again on main HEAD and confirm as myself, @jayeshmangwani , @eVoloshchak and @MitchExpensify were seeing different behaviours.

**Comment by adelekennedy** [comment] 2024-07-23 21:37
@eVoloshchak what are the next steps here?

**Comment by kpadmanabhan** [comment] 2024-07-27 01:18
In latest `main` `HEAD` I still see these behaviour as explained and shown in [my proposal](https://github.com/Expensify/App/issues/43331#issuecomment-2167821876).

Also pasting of text from "Copy to clipboard" context menu is ending up placing the corner at end of code block.
@eVoloshchak : the issue you mentioned is not reproducible at my side.

@adelekennedy : the core issue seems to be fixed. however there are regressions w.r.t copying using mouse / trackpad click and drag. if you do nmot click and drag till outside of the message (not just till outside code block), then this works fine in `main` `HEAD`. 

Please let me know if you need further details.

**Comment by kpadmanabhan** [comment] 2024-07-30 10:31
@eVoloshchak / @adelekennedy : shall i pick this up for fixing? key problem here is the selection of text from code block. 
fix will be that in case selection is till end of message and the data from clipboardv endswith code block, then add extra newline if selected till end.

please suggest if i may proceed with the fix.

**Comment by mallenexpensify** [comment] 2024-07-30 23:50
@eVoloshchak 👀 above plz

**Comment by eVoloshchak** [comment] 2024-08-01 16:44
I'm not sure if this is worth fixing, it's not a bug with the app itself, but rather the way OS handles text selection.
I can observe the same behavior here on GitHub

https://github.com/user-attachments/assets/a752f357-56f7-49b4-9eeb-d6096fb3325d

@mallenexpensify, @adelekennedy, what are your thoughts?

**Comment by adelekennedy** [comment] 2024-08-01 22:01
I'd move to close it in that case, it's low priority any way

**Closed by adelekennedy** 2024-08-01 22:01 UTC
Labels: External, Daily, Help Wanted, Bug
