### ISSUE TITLE
Unable to access private room on staging but shows a page with composer on production

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20831] opened 2023-06-15 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot at first and login with User A (an incognito window might be good for this)
2. Create a new workspace and invite User B
3. Create a new room in PRIVATE mode **on the Workspace you just created**.
4. Send a message to that room
5. Click on the header of the room > `Share code` > `Copy URL to clipboard`.  
6. In another web chrome, login **on staging.new.expensify.com** with User B and paste the URL on the tab on User B side
7. Result: See that on User B, it shows 'unable to access the chat' even when the User B was invited to the room
8. Follow the same steps on production app and see that 'Unable to access' message is not shown. Instead a blank page with chat composer is shown. Inconsistency between staging and production environment is seen
## Expected Result: 
Should be able to access private room on staging
## Actual Result: 
Unable to access private room on staging but shows a page with composer on production

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ff559641-9558-4b9b-9a0d-6220b6898033

https://github.com/Expensify/App/assets/43996225/a0bdcddf-3d81-4a00-9771-cea9e8dee6ba

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686722925761399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9b420914de094eb</li>
        <li>Upwork Job ID: 1669474116334002176</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-15 22:13
Thanks @avi-shek-jha for asking in the Slack thread that, if it's on staging only, should it be a deploy blocker.  I asked https://expensify.slack.com/archives/C049HHMV9SM/p1686867131810959?thread_ts=1686722925.761399&cid=C049HHMV9SM and internally.  

@amyevans wasn't sure about internal/external

**Comment by cead22** [comment] 2023-06-15 22:45
@mallenexpensify @kavimuru are we certain the conversation should actually load, and that what we're seeing on staging isn't by design? The thing is, the video doesn't show the channel actually loading, it just shows the skeleton UI that suggests it's loading

**Comment by cead22** [comment] 2023-06-15 22:49
cc @dukenv0307 @fedirjh @aldo-expensify  is it possible this is by design, and was implemented in [this PR](https://github.com/Expensify/App/pull/20407)?

**Comment by mallenexpensify** [comment] 2023-06-15 22:54
I wondered the same thing @cead22 .  But "Private" appears to mean "Private to the workspace", so the chat should load if a user is a member of the workspace (as it does on production).   Since this is a deploy blocker, let me test again

**Comment by mallenexpensify** [comment] 2023-06-15 23:24
Tested again and was able to reproduce

**Comment by mallenexpensify** [comment] 2023-06-15 23:37
Discussing here
https://expensify.slack.com/archives/C01GTK53T8Q/p1686868596435629

**Comment by cead22** [comment] 2023-06-15 23:51
Maybe this isn't caused by that PR since it is on staging and production, so the behavior from the PR should be the same on both

**Comment by mallenexpensify** [comment] 2023-06-16 00:29
Upon multiple retests (where I double checked I was logged in on both production for User B with the correct accounts) I was unable to produce. 

Where I think the _problem_ is is that, when creating a new room, we state `People invited to this room can find it` and... there's no way I can find to invite people to the room.

**Comment by mallenexpensify** [comment] 2023-06-19 23:08
Bumping to weekly since it needs reproduction and/or it might be a feature request?  Will dig in soon-ish

**Comment by mallenexpensify** [comment] 2023-06-30 17:41
Still need to look into

**Comment by mallenexpensify** [comment] 2023-07-11 23:57
I'm going to close this for now since I wasn't able to reproduce and Vit mentioned this a [few weeks ago](https://expensify.slack.com/archives/C01GTK53T8Q/p1686901296000759?thread_ts=1686868596.435629&cid=C01GTK53T8Q)
> I am not sure about the each behaviour either but we definitely do not have the invite flow implemented.

I think we're planning on addressing this flow but it'll take a while to get everything fleshed out

**Closed by mallenexpensify** 2023-07-11 23:57 UTC
Labels: Engineering, Weekly, Internal, Needs Reproduction, Overdue
