### ISSUE TITLE
[HOLD for payment 2024-11-29] mWeb - Chat -Contextual menu does not close on selecting delete, edit comment & reply in thread opt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52744] opened 2024-11-19 09:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5237958
**Email or phone of affected tester (no customers):** applausetester+ck31118@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to 1:1 DM
3. Send message
4. Long press on the message for the action menu to open
5. Select either, delete comment, edit comment or reply in thread options (Note: Contextual menu does not close)
6. Select any of the 3 emojis displayed in the menu (Note: Contextual menu does not close)

## Expected Result:
Contextual menu should close automatically when selecting delete comment, edit commnet or reply in thread options

## Actual Result:
Contextual menu does not close automatically when selecting delete, edit comment & reply in thread options
When delete comment option is selected, the action menu does not close & the confirmation modal is displayed behind the action menu.
Same issue happens when selecting reply in thread & edit comment options. User has to tap anywhere outside to close the menu

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2e9ebe0b-1d17-4f74-9805-27839032acb3

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by rojiphil** [comment] 2024-11-19 10:10
@teneeto Can we raise a quick PR to fix this?

**Comment by teneeto** [comment] 2024-11-19 10:20
Adding a fix now

**Comment by teneeto** [comment] 2024-11-19 10:21
Please assign issue to me

**Comment by rojiphil** [comment] 2024-11-19 11:29
> Edit box is not auto-focused when editing a comment. Is it the same root or need to create a new issue?

@IuliiaHerets Yeah. It is the same root cause and will be fixed with the PR for this issue.

**Comment by IuliiaHerets** [comment] 2024-11-19 11:51
Pin/Unpin modal is not dismissed after selecting

**Comment by rojiphil** [comment] 2024-11-19 12:07
@cristipaval The [PR](https://github.com/Expensify/App/pull/52752) is ready for review. Please have a look. Thanks.

**Comment by chiragsalian** [comment] 2024-11-21 01:02
Not a blocker, tested and confirmed [here](https://github.com/Expensify/App/issues/52733#issuecomment-2489846486) that the CP worked.

**Comment by bfitzexpensify** [comment] 2024-11-29 18:57
I believe this is a regression from https://github.com/Expensify/App/issues/50818. Closing this out.

**Closed by bfitzexpensify** 2024-11-29 18:57 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
