### ISSUE TITLE
[$250]  BA - All - User is prompted to manually enter bank account and routing number after connecting account via Plaid

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49391] opened 2024-09-18 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4977692
**Email or phone of affected tester (no customers):** applausetester+091724dr009@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App
2. Log in with a applause.expensifail account
3. Go to existing workspace or create new one
4. Navigate to Workspace settings > More features > Workflows > Connect bank account
5. Select the "Connect with plaid" method to add a bank account
6. Select "Chase" bank, enter the credentials "user_good / pass_good" and follow the flow
7. Checkmark "Plaid Saving" account
8. After returning from Plaid to ND select the bank account ending in 1111
~9. On page "Manually add your bank account" enter incorrect account - 1111222233334444~
~10. Click/tap "Next"~

## Expected Result:
After returning from Plaid to ND and selecting the bank account ending in 1111 (action 8 above), user should be taken to step 2 in the bank account setup flow.

## Actual Result:
After returning from Plaid to ND and selecting the bank account ending in 1111, user is taken to "Step 1 - Manually add your bank account" and prompted to enter their account number and routing number manually.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/92046543-c68b-49e2-9acd-bdb328de5dbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836806526771494788</li>
        <li>Upwork Job ID: 1836806526771494788</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-18 14:14
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-09-23 16:39
Hey @allroundexperts, what do you think of the proposal from last week?

**Comment by allroundexperts** [comment] 2024-09-23 16:51
Thanks for your proposal @abzokhattab. I think your proposal would work only if the last 4 characters are different. Isn't there a way to get the full bank account number?

**Comment by allroundexperts** [comment] 2024-09-23 16:52
I'm also wondering on why does the user have to fill in the bank account number again, when he selected a bank account in the previous step. @sakluger @IuliiaHerets Maybe you know?

**Comment by sakluger** [comment] 2024-09-25 00:10
> I'm also wondering on why does the user have to fill in the bank account number again, when he selected a bank account in the previous step.

Good catch. They shouldn't have to do both - if Plaid connects successfully, then they shouldn't have to manually enter the account and routing numbers. Manual entry is just a fallback option if they can't connect via Plaid. I wonder if this is unique to Staging/Dev, since I know adding a bank account is different on staging & dev.

**Comment by sakluger** [comment] 2024-09-26 20:31
Right, we'll generally never return a full account number, only the last four digits for privacy/security reasons.

**Comment by sakluger** [comment] 2024-09-27 16:38
I don't know if there's a minimum length for bank accounts  - I feel like I've seen some pretty short bank account numbers.

**Comment by sakluger** [comment] 2024-10-06 20:45
@allroundexperts still not quite sure how to move this one forward. What do you think we should do here?

**Comment by allroundexperts** [comment] 2024-10-07 07:13
Posted about this in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1728285153080089). Let's see if anyone knows why user is being asked to manually add there bank details.

**Comment by sakluger** [comment] 2024-10-09 22:44
No updates.

**Comment by sakluger** [comment] 2024-10-14 17:31
Still no updates.

**Comment by sakluger** [comment] 2024-10-17 20:43
I'm pretty confident that users shouldn't have to manually enter account & routing number after connecting via Plaid, even in Staging. Once they connect via Plaid, we would pull their account & routing number from Plaid.

@allroundexperts what are next steps assuming that what I described above is the expected behavior?

**Comment by allroundexperts** [comment] 2024-10-20 20:58
> @allroundexperts what are next steps assuming that what I described above is the expected behavior?

@sakluger Given that's the case, we'd need to create a new issue for it, and investigate why its not pulling information from Plaid. We can put this one on hold till that is resolved.

**Comment by sakluger** [comment] 2024-10-22 16:57
Can we just repurpose this issue for that investigation? I feel like this exising issue becomes irrelevant since the user would no longer be asked to enter an account and routing number after connecting via Plaid.

**Comment by sakluger** [comment] 2024-10-24 23:23
No updates.

**Comment by allroundexperts** [comment] 2024-10-28 21:07
Still awaiting proposals.

@sakluger Maybe we can ask someone from the expert agency to look at this?

**Comment by sakluger** [comment] 2024-10-31 22:06
Hey @abzokhattab, were you able to test based on the new requirement?

**Comment by sakluger** [comment] 2024-11-01 18:42
I updated the GH issue title and the Expected Results and Actual Results in the OP.

I'm also labeling as `#quality`, but I also asked for confirmation in Slack that it's under the right project.

**Comment by tgolen** [comment] 2024-11-01 20:02
I did some debugging on this today and put my findings in [this slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1728285153080089).

**Comment by tgolen** [comment] 2024-11-01 20:34
I got confirmation in [that Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1728285153080089) from @nkuoch that this is working as intended and is not a bug. I'm going to close this out.

**Closed by tgolen** 2024-11-01 20:34 UTC
Labels: External, Daily, Help Wanted, Bug
