### ISSUE TITLE
[$1000] Tooltip position changes after closing fab menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13638] opened 2022-12-15 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Hover over Fab icon
2. Click on it to open
3. Click on it again to close

## Expected Result: 
The tooltip position stays the same (left of centre)

## Actual Result : 
The tooltip position changes (centre) 

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207954222-963fafa7-041a-4722-aea6-75505fb79b78.mp4

https://user-images.githubusercontent.com/43996225/207954345-ab05b404-a924-4576-906c-7a7991a00040.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671121404845929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017865baf3b71f832d</li>
        <li>Upwork Job ID: 1603839332202037248</li>
        <li>Last Price Increase: 2022-12-16</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2022-12-15 23:03
Gonna work on this one!

**Comment by luacmartins** [comment] 2022-12-16 19:47
Not sure if it's worth fixing this since it looks like an edge case and doesn't break any functionality (it only shifts the tooltip slightly, but resets the position if you hover the button again). I'll make this external.

**Comment by luacmartins** [comment] 2022-12-16 20:36
@0xmiroslav proposal looks good to me!

**Comment by laurenreidexpensify** [comment] 2022-12-19 12:05
Offers sent in Upwork

**Comment by laurenreidexpensify** [comment] 2022-12-28 11:26
Weird., this has been deployed to prod 7 days ago but automation failed. Moving forward with payment now.

**Comment by laurenreidexpensify** [comment] 2022-12-28 11:27
Eligible for 3 day bonus as PR was created and merged on 16 Dec.

**Comment by laurenreidexpensify** [comment] 2022-12-28 11:31
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.2.41-4 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/13671

If no regressions arise, payment will be issued on 2022-12-28. :confetti_ball:

After the hold period, please check if any of the following need payment for this issue, and if so check them off after paying:
- [x] External issue reporter
- [x] Contributor that fixed the issue
- [x] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by laurenreidexpensify** [comment] 2022-12-28 11:32
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@thesahindia  / @luacmartins] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@thesahindia  / @luacmartins] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@thesahindia  / @luacmartins] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@laurenreidexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by laurenreidexpensify** [comment] 2023-01-03 13:58
@thesahindia @luacmartins when you are back from holidays pls can you fill out remaining details. Thanks

**Comment by thesahindia** [comment] 2023-01-03 14:10
Actually this bug was present from the starting so I think we can skip the checklist. Also it wasn't an edge case. Let's just add a regression test?

**Comment by laurenreidexpensify** [comment] 2023-01-03 14:38
SGTM

**Comment by michaelhaxhiu** [comment] 2023-01-09 19:48
Re-opening this GH so @laurenreidexpensify can ensure it's finalized, and then go from there!

**Comment by laurenreidexpensify** [comment] 2023-01-10 13:39
@daraksha-dk offer sent - will get this actioned ASAP for you

**Comment by laurenreidexpensify** [comment] 2023-01-10 16:30
Paid! Sorry for the oversight here!

**Closed by laurenreidexpensify** 2023-01-10 16:30 UTC
Labels: Reviewing, External, Daily, Bug
