### ISSUE TITLE
[$1000] Web - App does not change Spanish emoji text to emoji on change of language

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23305] opened 2023-07-20 20:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Ensure that language currently is English
3. Open any report
4. Type :helado: (Spanish for ice cream) or any other Spanish emoji text
5. Change the language to Spanish and observe that message in compose box does not change to emoji
6. Change report and revisit to see that now it is changed to ice cream emoji

## Expected Result:
App should change Spanish emoji text to emoji when we change the language to Spanish

## Actual Result:
App does not change Spanish emoji text to emoji when we change the language to Spanish and needs revisit to change

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/827fa161-46f4-4bed-8d6a-5d18e46093d2

https://github.com/Expensify/App/assets/93399543/aba7d8a7-86ad-4e79-becf-4d396d174d72

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689854158724759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c549a3221d600158</li>
        <li>Upwork Job ID: 1683650330760372224</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 25797008</li>
<li>dhanashree-sawant | Reporter | 25797010</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-07-20 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not change spanish emoji text to emoji on change of language
### What is the root cause of that problem?
The message value not update if language change
https://github.com/Expensify/App/blob/99519f2347f91a2328f0e143e8a2859628412ffa/src/pages/home/report/ReportActionCompose.js#L287-L291
### What changes do you think we should make in order to solve the problem?
Update the message value when language change
```javascript
 if (this.props.preferredLocale === prevProps.preferredLocale && this.props.report.reportID === prevProps.report.reportID && !shouldSyncComment) { 
     return; 
 } 
  
 this.updateComment(this.props.comment); 
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sophiepintoraetz** [comment] 2023-07-25 01:28
Yup!
![2023-07-25_13-27-10 (1)](https://github.com/Expensify/App/assets/42940078/3fde9381-8339-4497-a4ea-57970ea00b56)

**Comment by sophiepintoraetz** [comment] 2023-07-25 01:44
Not overdue - waiting on proposals

**Comment by lorentzimys** [comment] 2023-07-25 03:00
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
App does not change spanish emoji text to emoji on change of language

### What is the root cause of that problem?
The comment is not updated because 'shouldSyncComment' does not takes into account locale change.

### What changes do you think we should make in order to solve the problem?
[ahmedGaber93](https://github.com/ahmedGaber93) logic was almost correct except the condition of 'shouldSyncComment' should be slightly different. I suggest it to be this way: 

```
  const localeChanged = prevProps.preferredLocale !== this.props.preferredLocale;
  const shouldSyncComment = localeChanged || (prevProps.comment !== this.props.comment && this.state.value !== this.props.comment);

  // As the report IDs change, make sure to update the composer comment as we need to make sure
  // we do not show incorrect data in there (ie. draft of message from other report).
  if (this.props.report.reportID === prevProps.report.reportID && !shouldSyncComment) {
      return;
  }

 this.updateComment(this.props.comment); 
```

### What alternative solutions did you explore? (Optional)
none

**Comment by lorentzimys** [comment] 2023-07-25 03:02
Contributor details
Your Expensify account email: lorentzimys1@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/~019f8212604bc5ba98)

**Comment by ahmedGaber93** [comment] 2023-07-25 13:16
> const shouldSyncComment = localeChanged || (prevProps.comment !== this.props.comment && this.state.value !== this.props.comment);

@lorentzimys I think `shouldSyncComment` based on `localeChanged` will return **incorrect value** if there is no emoji like :helado: need to update.

My alternative solution https://github.com/Expensify/App/issues/23305#issuecomment-1644540264  work in this point and `shouldSyncComment` will return true if **locale is changed and there is emoji like :helado: need to update**.

Thanks!

**Comment by ArekChr** [comment] 2023-07-25 13:18
The proposal from @ahmedGaber93 looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by bondydaa** [comment] 2023-07-27 23:03
assigned, leave me alone melvin

**Comment by sophiepintoraetz** [comment] 2023-07-28 05:05
@ahmedGaber93 - are you ready to get started on the PR?

**Comment by ahmedGaber93** [comment] 2023-07-28 07:56
@sophiepintoraetz @ArekChr [PR](https://github.com/Expensify/App/pull/23779) is now ready for review.

**Comment by sophiepintoraetz** [comment] 2023-08-02 04:48
Waiting on a review from @bondydaa

**Comment by bondydaa** [comment] 2023-08-02 22:58
I was actually talking to @stitesExpensify about this yesterday IRL and he mentioned we might have done this on purpose, going to double check if he had a second to review this or not.

**Comment by bondydaa** [comment] 2023-08-03 15:05
ok chatted with stites and he thought it was a little different case at first so 👍 full steam ahead. will review the pr now.

**Comment by ahmedGaber93** [comment] 2023-08-22 01:25
@sophiepintoraetz, any updates about payment here? This issue has been merged in production since 13 days ago

**Comment by sophiepintoraetz** [comment] 2023-08-22 07:47
Apologies @ahmedGaber93 - usually there's another checklist that comes through about initiating payments/BZ regression testing but we're all set here.

**Closed by sophiepintoraetz** 2023-08-22 07:47 UTC
Labels: Reviewing, External, Weekly, Bug
