### ISSUE TITLE
Split Bill- Multiple tap of back button left to " Details", user navigated to "LHN"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24434] opened 2023-08-11 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap split bill
4. Enter amount
5. Tap Next
6. Select any 2 users
7. Tap next
8. Tap Split amount
9. Tap on header
10. Tap on the side, adjacent to each user, to note its profile page opening
11. Tap back button left to "details"

## Expected Result:
On single tap of back button left to " Details" , user must be navigated to "conversation" page

## Actual Result:
User has to tap many times the back button next to "details", then instead of navigating to conversation page, user is directly navigated to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ea248353-e1ba-43b9-b42c-de7db50caf39

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-08-14 17:46
I've seen several issues with navitaging back from a sub-menu. I'd like to check if this related to any of the following:

https://github.com/Expensify/App/issues/23796
https://github.com/Expensify/App/issues/23758
https://github.com/Expensify/App/issues/23725

@mountiny on https://github.com/Expensify/App/issues/23725, you mentioned looking at as a general solution as part of the navigation follow ups tracking project. Do you think this issue should go there too?

**Comment by adamgrzybowski** [comment] 2023-08-16 17:52
I have a problem with reproducing this one. I am getting `its not here` page after splitting the bill on Stagin. Any idea what that may be? BTW I tested this on my local main and it works fine. Can't reproduce this bug locally.

<img width="384" alt="image" src="https://github.com/Expensify/App/assets/67908363/8fee4fda-dfd8-4179-a69e-f83797dae1dd">

**Comment by adamgrzybowski** [comment] 2023-08-16 17:57
Okay I was able to open this on staging and still can't reproduce the bug

https://github.com/Expensify/App/assets/67908363/4f1b9066-27b4-4382-81f7-9444b8ff5246

**Comment by mountiny** [comment] 2023-08-16 20:16
@lanitochka17 @kavimuru Could you reproduce again? Otherwise lets close this @sakluger

**Comment by sakluger** [comment] 2023-08-17 18:34
I'm going to close for now since it doesn't seem to be reproduceable on the latest build.

**Closed by sakluger** 2023-08-17 18:34 UTC
Labels: Daily, Overdue, Bug
