### ISSUE TITLE
[$250] iOS - Distance expense-Unable to submit distance expense offline, Next button is unresponsive or works with delay

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52781] opened 2024-11-19 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify staging app and sign in.
2. Tap FAB - Submit expense.
3. Choose Distance option.
4. Disable internet connection.
5. Type in distance points and tap Next button.

## Expected Result:
User is able to create Distance expense offline.

## Actual Result:
User is not able to create Distance expense offline, Next button becomes unresponsive.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/55628cb2-572c-422a-86bf-44e7f7b58c7a

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859634020737443781</li>
        <li>Upwork Job ID: 1859634020737443781</li>
        <li>Last Price Increase: 2024-12-19</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-11-22 16:43
No proposals yet.

**Comment by Condo97** [comment] 2024-11-23 16:52
Hello, I've been working on this and I have a proposal for a fix. The fix is in regard to rendering issues with OfflineIndicator. I have already found the fix and would like to get hired and submit the pull request. What are the next steps?

Proposal:
Fix rendering issues with OfflineIndicator. Due to the nature of offline handling and React rendering, it may cause the renderer to position part of OfflineIndicator over the button in a view update. If the view refreshes, like if the user swipes left on the screen slightly, the view updates again and OfflineIndicator's invisible head is rendered correctly and the button can be pressed.
The fix is in regard to getting the view correct the first time. Instead of having the view render incorrectly and then wait for an update, the fix makes sure the view is rendered correctly the first time and no invisible head is covering the button.
It's a very simple fix but it's taken me over 12 hours to figure out! Works in tests and across devices!

**Comment by Condo97** [comment] 2024-11-23 16:54
Contributor details
Your Expensify account email: acoundou@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01237b4ed5e35e0560?mp_source=share

**Comment by Condo97** [comment] 2024-11-23 16:54
Hello, I've been working on this and I have a proposal for a fix. The fix is in regard to rendering issues with OfflineIndicator. I have already found the fix and would like to get hired and submit the pull request. What are the next steps?

Proposal:
Fix rendering issues with OfflineIndicator. Due to the nature of offline handling and React rendering, it may cause the renderer to position part of OfflineIndicator over the button in a view update. If the view refreshes, like if the user swipes left on the screen slightly, the view updates again and OfflineIndicator's invisible head is rendered correctly and the button can be pressed.
The fix is in regard to getting the view correct the first time. Instead of having the view render incorrectly and then wait for an update, the fix makes sure the view is rendered correctly the first time and no invisible head is covering the button.
It's a very simple fix but it's taken me over 12 hours to figure out! Works in tests and across devices!

**Comment by sakluger** [comment] 2024-11-25 16:02
Hi @Condo97, could you please follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) when posting your proposal? If you'd like more guidance on how to make a good proposal, you can review the [Contributing Guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-expensify-jobs) again or look at past closed jobs in the repo to see which proposals have been selected.

**Comment by Condo97** [comment] 2024-11-25 19:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the Distance option, when user switches to offline state and navigates to and from the Start or Stop views, the Next button becomes unresponsive.

### What is the root cause of that problem?
Button is incorrectly rendered with an invisible overlay from OfflineIndicator. This can be especially seen because the button is surprisingly not _entirely_ disabled, but only disabled when tapped on the bottom half or ⅔. And when the user triggers another view refresh to the button (i.e. by swiping left slightly to expose the Scan option) it works correctly.

### What changes do you think we should make in order to solve the problem?
With the state change of isOffline, its primitive value needs to be read rather than the value of the object itself.

**Comment by abdulrahuman5196** [comment] 2024-11-26 17:22
@Condo97 , Kindly add code pointers in the repo, where you think the issue is happening and how do you intend to solve it.

**Comment by Condo97** [comment] 2024-11-27 03:01
@abdulrahuman5196 The issue is happening in src/components/OfflineIndicator.tsx line 37. I intend to solve it by getting the primitive value instead of its object value to ensure the view is rendered correctly.

I'm not sure what you mean by adding pointers in the repo. I was told not to make a pull request until the proposal has been accepted. Should I go ahead and make one, or do you mean something else? Thank you.

**Comment by sakluger** [comment] 2024-12-02 17:11
@Condo97 here is an example of a correctly formatted proposal from a previous Github issue that uses code pointers: https://github.com/Expensify/App/issues/52023#issuecomment-2458935669

**Comment by Condo97** [comment] 2024-12-03 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the Distance option, when user switches to offline state and navigates to and from the Start or Stop views, the Next button becomes unresponsive.

### What is the root cause of that problem?
Button is incorrectly rendered with an invisible overlay from OfflineIndicator. This can be especially seen because the button is surprisingly not _entirely_ disabled, but only disabled when tapped on the bottom half or ⅔. And when the user triggers another view refresh to the button (i.e. by swiping left slightly to expose the Scan option) it works correctly.

https://github.com/Expensify/App/blob/a40eb994e4cad7c27147ea2dab507497ff0803e5/src/components/OfflineIndicator.tsx#L37-L39

### What changes do you think we should make in order to solve the problem?
With the state change of isOffline, its primitive value needs to be read rather than the value of the object itself.

```typescript
// Use valueOf
if (!isOffline.valueOf) {
  return null;
}
```

https://github.com/Expensify/App/blob/a40eb994e4cad7c27147ea2dab507497ff0803e5/src/components/OfflineIndicator.tsx#L37-L39

This fixes the rendering issue.

**Comment by sakluger** [comment] 2024-12-05 16:42
Hey @abdulrahuman5196 - thoughts on the lastest proposal above?

**Comment by abdulrahuman5196** [comment] 2024-12-06 10:46
Checking now

**Comment by abdulrahuman5196** [comment] 2024-12-06 11:58
@Condo97 I don't think that the RCA and solution is correct. isOffline is a boolean value not an object

https://github.com/Expensify/App/blob/a9bf599522215bc8c844d587374fd4f04d6b860b/src/hooks/useNetwork.ts#L9

**Comment by abdulrahuman5196** [comment] 2024-12-06 11:58
No proposal to approve yet

**Comment by sakluger** [comment] 2024-12-09 16:13
Waiting for new proposals.

**Comment by sakluger** [comment] 2024-12-12 22:59
Still no new proposals.

**Comment by abdulrahuman5196** [comment] 2024-12-16 16:20
No proposals

**Comment by linhvovan29546** [comment] 2024-12-19 03:30
I couldn't reproduce this issue on the main branch. Can anyone confirm if it still exists?

**Comment by sakluger** [comment] 2024-12-19 14:50
I asked for a retest in Slack: https://expensify.slack.com/archives/C9YU7BX5M/p1734619813748899

**Comment by mvtglobally** [comment] 2024-12-20 00:13
Fixed


https://github.com/user-attachments/assets/20001099-934a-4cf2-b109-77956590c345


https://github.com/user-attachments/assets/a2304a2d-40ab-482a-8497-403a2a38aee1

**Comment by mvtglobally** [comment] 2024-12-21 02:31
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2024-12-23 17:19
> Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-12-24 22:03
Alright, I'll close for now! We can reopen if it becomes reproduceable again.

**Closed by sakluger** 2024-12-24 22:03 UTC
Labels: External, Daily, Help Wanted, Bug
