### ISSUE TITLE
[Ideal Nav] WS switcher - Delayed transition of breadcrumbs from Workspace / Chat to Expensify / Chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38281] opened 2024-03-14 09:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- There are at least two workspaces.
- One of the workspaces has other members,

1. Go to staging.new.expensify.com.
2. Open workspace switcher > Select a workspace.
3. Go to Profile > Workspaces.
4. Select a different workspace that has members.
5. Go to Members.
6. Click on the invited members > Message <user>.

## Expected Result:
The breadcrumbs (Expensify / Chat) will sync with the changes in LHN.

## Actual Result:
LHN shows all the chats first, then followed by the change of breadcrumbs (Workspace / Chat) to Expensify / Chat. The transition is not smooth.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6cfa1f5b-21bf-4e76-90e6-74b9a376caf4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment] 2024-03-14 09:58
@techievivek I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by techievivek** [comment] 2024-03-14 13:29
Doesn't need to be a blocker but I am checking the diff to figure out which PR could have caused this regression.

**Comment by techievivek** [comment] 2024-03-14 13:30
Also, I can see there is a slight delay but not sure if this is due to some recent PR.

**Comment by mountiny** [comment] 2024-03-14 14:21
I think this is not really a blocker but something to look at maybe from the performance perspective

cc @WojtekBoman since you worked on the switcher

**Comment by trjExpensify** [comment] 2024-03-15 12:29
Yeah, let's take a look at this for sure.

**Comment by alexpensify** [comment] 2024-03-16 00:47
Cool, this one is associated with WAVE-Collect

**Comment by techievivek** [comment] 2024-03-18 11:46
Gentle bump @WojtekBoman, can you please take a look into this issue? 🙏

**Comment by alexpensify** [comment] 2024-03-22 19:26
A PR is in review for this one.

**Comment by alexpensify** [comment] 2024-03-29 17:36
Weekly Update: The PR is in review

**Comment by alexpensify** [comment] 2024-04-02 21:56
Weekly Update: This PR is in staging, so we will wait for automation here.

**Comment by alexpensify** [comment] 2024-04-09 22:17
Noted, I'll keep this in mind during the payment period.

**Comment by twisterdotcom** [comment] 2024-04-10 11:19
Okay, let's get this reverted and fixed then. We can close our issue @paultsimura. @WojtekBoman and @parasharrajat for the fix.

@alexpensify I think we need them assigned to this issue no?

**Comment by WojtekBoman** [comment] 2024-04-10 12:10
I looked into it and I know how to fix that. I'll prepare a PR :)

**Comment by alexpensify** [comment] 2024-04-10 14:38
The assignments have been updated here.

**Comment by WojtekBoman** [comment] 2024-04-11 11:39
@parasharrajat https://github.com/Expensify/App/pull/40016

**Comment by alexpensify** [comment] 2024-04-15 21:31
Holding on for the payment action until the regression is addressed since the other issue is closed.

**Comment by alexpensify** [comment] 2024-04-17 20:22
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

@mallenexpensify is going to step in and help out on the Bug Zero side.

**Comment by alexpensify** [comment] 2024-04-23 22:36
Catching up from being OOO and going to remove @mallenexpensify. I checked the PR and it looks like we are waiting for a review.

**Comment by alexpensify** [comment] 2024-04-23 22:38
I've bumped the PR reviewer for help.

**Comment by alexpensify** [comment] 2024-04-25 22:49
There is a discussion going on here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1713308280227079

**Comment by alexpensify** [comment] 2024-04-30 22:30
Thanks for the update, I've updated the GH accordingly.

**Comment by alexpensify** [comment] 2024-05-07 21:55
Weekly Update: The PR is still under review

**Comment by alexpensify** [comment] 2024-05-14 22:12
Weekly Update: It looks like the last PR was approved, and now we are waiting for automation. Is that correct @parasharrajat?

**Comment by alexpensify** [comment] 2024-05-17 16:46
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@trjExpensify - While I'm offline, I need help here completing the payment process after this one clears the 7-day period. That said, it looks like the PR created regression, so we need to address that asap. Thanks!

**Comment by alexpensify** [comment] 2024-05-28 18:13
Noted, I'm going through my BZ batch soon and was planning to grab this one back.

**Comment by alexpensify** [comment] 2024-05-29 23:08
Alright, keeping the summary as is since this was a more complicated PR and was quickly addressed: 

https://github.com/Expensify/App/issues/38281#issuecomment-2057511288

@parasharrajat please submit the request in Chat.

**Closed by alexpensify** 2024-05-29 23:08 UTC
Labels: Reviewing, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-06-17 15:53
$250 approved for @parasharrajat per [this summary](https://github.com/Expensify/App/issues/38281#issuecomment-2057511288).
