### ISSUE TITLE
[HOLD for #27884] [$500] Task -  Disabled "Add Reaction" on deleted assignee task notification after a moment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28621] opened 2023-10-02 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and add a title, then share it somewhere.
2. Confirm the tasks and complete them.
3. Reopen the tasks.
4. Delete the tasks and hover over the delete notification.
5. Notice that "Add Reaction" is enabled.
6. Refresh the page and observe that "Add Reaction" is now disabled.

## Expected Result:
 "Add Reaction" should not be disabled when hovering over the deleted assigned tasks notification after refreshing the page. It should either remain disabled after deleting the assigned tasks without waiting a moment, or it should not be disabled at all.

## Actual Result:
"Add Reaction" is disabled after a moment when hovering over the deleted assigned tasks notification.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d1dc21f1-9803-47a0-a7df-74f99c4258d8

https://github.com/Expensify/App/assets/93399543/332e7b78-2084-434f-83e2-63cf05e7324c

https://github.com/Expensify/App/assets/93399543/1391ae0e-b481-4d46-b09f-ee078eebcf40

https://github.com/Expensify/App/assets/93399543/ee907568-860c-4430-851d-fcb48aa5444a

https://github.com/Expensify/App/assets/93399543/ede8030d-a2f2-48b7-8e2a-d31f433a547f

https://github.com/Expensify/App/assets/93399543/8d544393-2344-4346-9257-9d4c16c472c7

https://github.com/Expensify/App/assets/93399543/4666514c-7f24-4176-8e59-ef72196b0f0c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695449091829779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd509c6ee69b901c</li>
        <li>Upwork Job ID: 1708866409372258304</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by martin12345678900** [comment] 2023-10-02 16:22
**Proposal**
**Please re-state the problem that we are trying to solve in this issue**
When adding a task, completing it and then we cancel it, first time we are able to hover and see the reactions.

**What is the root cause of the problem**
This is due to this code , where we don't check for type of action (in this case it's TASKCANCELLED)

[https://github.com/Expensify/App/blob/05aa0c317e12a230977188dd5afb18cf4015bcb1/src/libs/ReportActionsUtils.js#L589-L591C2](url)

**What changes do you think we should make in order to solve the problem?**
We can add an additional check for the action name in see if the it's type is TASKCANCELLED
```javascript
return reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED || lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false);
```
**What alternative solutions did you explore? (Optional)**

**Comment by martin12345678900** [comment] 2023-10-02 16:26
Contributor details
Your Expensify account email: martinkolev2004@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/martink80

**Comment by abdulrahuman5196** [comment] 2023-10-03 16:40
On @tienifr 's proposal here https://github.com/Expensify/App/issues/28621#issuecomment-1744133781
I am not sure if root cause 2 is relavant to this particular issue. But I will come back to that. 

On the root cause 1. the below is an example reportAction from server for the cancel action after refreshing.

Even in the reportAction, the `isDeletedParentAction` flag is not present inside the `message` key which is used in the `isMessageDeleted` function. But still its working after refresh. Not sure If I had missed something in the proposal.

Could you kindly provide information on why its working(reactions not shown in context menu) on this case as well?


```
{
  "actionName": "TASKCANCELLED",
  "actorAccountID": 14321923,
  "automatic": false,
  "avatar": "https://d1wpcgnaa73g0y.cloudfront.net/8652017f3bd218b57b61db0c65a947339c74107c.png",
  "isAttachment": false,
  "originalMessage": {
    "taskReportID": 6690522316780141,
    "type": "TASKCANCELLED",
    "text": "deleted task: tititit",
    "html": "deleted task: tititit",
    "lastModified": "2023-10-03 15:33:42.124",
    "title": "tititit",
    "isDeletedParentAction": true,
    "reactions": [
      {
        "emoji": "fire",
        "users": [
          {
            "accountID": 14321923,
            "skinTone": -1
          }
        ]
      }
    ]
  },
  "message": [
    {
      "type": "TEXT",
      "style": "normal",
      "text": "deleted task: tititit"
    }
  ],
  "person": [
    {
      "type": "TEXT",
      "style": "strong",
      "text": "Abdul rahuman Abdul rahuman"
    }
  ],
  "reportActionID": "492571325956984651",
  "shouldShow": true,
  "created": "2023-10-03 15:33:38.283",
  "isFirstItem": false,
  "pendingAction": null,
  "timestamp": 1696347218,
  "reportActionTimestamp": 1696347218283,
  "previousReportActionID": "2571787378646686224",
  "lastModified": "2023-10-03 15:33:42.124",
  "whisperedToAccountIDs": [],
  "sequenceNumber": null,
  "childReportID": 6690522316780141,
  "childType": "task",
  "childReportName": "tititit",
  "childManagerAccountID": 14244652
}
```

**Comment by esh-g** [comment] 2023-10-04 11:24
# Proposal

## Please re-state the problem
Emoji actions are enabled for some time for report actions indicating closing/re-opening of a task.

## What is the root cause of this problem?
The root cause if that the emojis are only shown when the `reportAction` has a message in it. And the message is only there when the `reportAction` is present in `props.reportActions` in `BaseReportActionContextMenu.js`
https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L57-L62

Now this `props.reportActions` comes from the `originalReportID` passed to the context menu here:
https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L188

This `originalReportID` comes from the `ReportUtils.getOriginalReportID` function which in-turn calls the `ReportUtils.isThreadFirstChat` function.
https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/libs/ReportUtils.js#L690-L692

Basically this function checks if the `childReportID` is equal to `currentReportID`.

Now if we see the task completed action created optimistically, we see that there is no `childReportID`, but after updating from backend, the `childReportID` appears and this task completed action becomes a child of the report where the task was first shared. Which means that the `originalReportID` becomes the `shareDestination` report of the task, which in-turn does not have this report action. Thus, `props.reportActions` passed to `BaseReportActionContextMenu` doesn't include this task and it does not have message, thus the emojis stop showing.

<img width="393" alt="Screenshot 2023-09-27 at 5 30 35 PM" src="https://github.com/Expensify/App/assets/77237602/adda1183-0edc-444b-a6a6-f31e4e6df35c">

## What changes should be done to fix this?
We should return the `childReportID` while building a `taskReportAction` optimistically here:

https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/libs/ReportUtils.js#L2436-L2445

like this:
 ```js
 childReportID: taskReportID
 ```

**Comment by stephanieelliott** [comment] 2023-10-06 05:18
Hey @abdulrahuman5196 can you please review these proposals when you get a chance?

**Comment by abdulrahuman5196** [comment] 2023-10-06 05:24
Yes. Will do it today. On my checklist for today items.

**Comment by esh-g** [comment] 2023-10-06 11:53
Actually I think this will get fixed in this issue: https://github.com/Expensify/App/issues/27884
Because this will remove the `childReportID` from the backend and we will be allowed to add the reactions then

**Comment by abdulrahuman5196** [comment] 2023-10-09 17:03
TAL now

**Comment by abdulrahuman5196** [comment] 2023-10-09 18:27
On @dukenv0307 's proposal here https://github.com/Expensify/App/issues/28621#issuecomment-1746380086. I think its the opposite we want here, like `We don't want to show reactions on deleted task notification similar to other task notification on the thread`. Correct me if wrong @stephanieelliott

**Comment by stephanieelliott** [comment] 2023-10-11 05:16
Yep, agreed @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-10-13 13:57
Reviewing again

**Comment by stephanieelliott** [comment] 2023-10-17 01:37
Put on `Hold` and adjusted labels!

**Comment by stephanieelliott** [comment] 2023-10-30 16:30
https://github.com/Expensify/App/issues/27884 was merged, looks like it fixed this issue -- retested and it's not happening anymore!

**Closed by stephanieelliott** 2023-10-30 16:30 UTC
Labels: External, Monthly, Help Wanted, Bug
