### ISSUE TITLE
[Workspace Feeds] [$250] Expensify card - Unable to issue new cards to members

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48199] opened 2024-08-28 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47844
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace and invite an existing Gmail member
3. Navigate to Workspace settings - More features
4. Enable "Expensify Card"
5. Navigate to Workspace settings - Expensify Card
6. Click on the "Issue new card" button
7. Add Regions bank with Plaid
8. Click on the "Issue new card" button again
9. Choose the bank account and member
10. Choose "Physical" or "Virtual" card
11. Set any limit type
12. Set any limit
13. Set any name
14. Click on the "Issue card" button

## Expected Result:
The card should be added for the member

## Actual Result:
Unable to issue new cards to members. I'm returned to the "Expensify Card" after issuing the card but it's not added for the member. Affects both the "Expensify Card" flow and a card added from the "Members" page after selecting one.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8ac60ef8-b4fa-4155-80c9-61810b8b46e7

https://github.com/user-attachments/assets/81be4dd8-e398-4223-9c5b-a5043bb496a6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01daeec4f6ff832c54</li>
        <li>Upwork Job ID: 1831039312939789039</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103809990</li>
<li>allgandalf | Contributor | 103809991</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by arosiclair** [comment] 2024-08-28 18:44
I found [these logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228b9da17b9de05b63-VIE%22)+AND+timestamp:[2024-08-27T16:02:42.605Z+TO+2024-08-27T18:02:42.605Z]&index=logs_expensify-030008) for that test user which show `CreateExpensifyCard` failing with error `404 Business not provisioned`. I think this probably doesn't need to block App deploy, but I'm not sure. 

@mountiny can you take a look? cc @nkuoch since I see you authored most of `CreateExpensifyCard`.

**Comment by arosiclair** [comment] 2024-08-28 18:48
Asked if this is related to the fireroom [here](https://expensify.slack.com/archives/C07H44EDCHX/p1724870846930859) as well

**Comment by arosiclair** [comment] 2024-08-28 21:40
Removed the label since this looks to be behind a beta ([slack convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1724868873581799)) and assigning to @mountiny to take a look when he gets back.

**Comment by mountiny** [comment] 2024-08-29 05:36
Thanks! I have seen this error before for some testers. Not sure yet what is leading to it as they should be provisioned when they enter the new card flow

**Comment by koko57** [comment] 2024-08-29 07:44
@mountiny @arosiclair although nothing has changed since CreateExpensifyCard was merged let's keep in touch whether it's a BE or FE issue. I'll look into it later if it could be some problem on the FE side.

**Comment by nkuoch** [comment] 2024-08-30 07:27
Maybe it just hasn't been implemented FE side yet?
From the video and the logs, I see that we never actually called `ConfigureExpensifyCardsForPolicy`.
It should have been called after adding the vbba successfully. 
We shouldn't allow to call `CreateExpensifyCard` from the front end if the workspace hasn't been provisioned.

**Comment by koko57** [comment] 2024-08-30 07:31
@nkuoch this was implemented, but I'll check why ConfigureExpensifyCardsForPolicy is not called, thanks!

**Comment by mountiny** [comment] 2024-09-02 10:17
I think this might be some old policy which enabled the feature before we had this fully implemented. 

@IuliiaHerets Can you confirm if you can repro this starting from scratch with a new account?

**Comment by mountiny** [comment] 2024-09-02 10:18
Asked in QA [here](https://expensify.slack.com/archives/C9YU7BX5M/p1725272281514249)

**Comment by IuliiaHerets** [comment] 2024-09-03 12:33
@mountiny QA team still can repro the issue, build - v9.0.28-0

https://github.com/user-attachments/assets/feabf629-9031-40b8-9ee7-aa435492c5d4

**Comment by mountiny** [comment] 2024-09-04 09:43
Alright we will need to debug this more, seems like some race condition or we skip calling some API command during the card setup

**Comment by koko57** [comment] 2024-09-04 11:18
@mountiny can we retest it? The request cannot be triggered only when we don't have the bankAccountID. probably it occurred for the same reason we had a problem with https://github.com/Expensify/App/issues/45729. As now we're getting the same bankAccountList object we should have all the necessary data. I cannot reproduce ConfigureExpensifyCardsForPolicy locally.

**Comment by mountiny** [comment] 2024-09-05 14:30
@allgandalf @DylanDylann will look into this one as soon as they can to try to narrow down the rootcause here

**Comment by DylanDylann** [comment] 2024-09-06 02:59
@mountiny I confirmed that CONFIGURE_EXPENSIFY_CARDS_FOR_POLICY isn't called 

The problem: The backend doesn't return `bankAccountID` in bankAccountList > accountData

<img width="808" alt="Screenshot 2024-09-06 at 09 58 32" src="https://github.com/user-attachments/assets/d44344f6-98fa-46fe-be47-59dbd9bd3e7a">

**Comment by mountiny** [comment] 2024-09-06 09:09
Perfect, yeah, so the problem is different formats of the bank account ID, which is a relic issue from the past. for some API commands, we return the data straight from Auth, and for some, we modify the data shape in Web, and it's causing this mess.

I also see that the methodID is actually bankAccountID 🤦 so you can use that

**Comment by mountiny** [comment] 2024-09-06 11:04
This should be fixed in staging now

**Closed by mountiny** 2024-09-06 11:04 UTC
Labels: Reviewing, External, Daily, Bug
