### ISSUE TITLE
[Re-test] Workspace - "Hmm it's not here" message appears briefly when changing tags

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41905] opened 2024-05-09 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41723
## Action Performed:
Preconditions: Have a Collect WS with Tags and Taxes enabled. Have at least one tag added
1. Log in with an expensifail account
2. Navigate to FAB - Send invoice
3. Finish the invoice flow
4. Open the invoice details
5. Change the tag

## Expected Result:
No error should be visible

## Actual Result:
"Hmm it's not here" message appears briefly when changing tags

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a8fccb28-4676-4390-8f09-6bca738df30d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-09 12:57
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-05-10 08:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Hmm it's not here" message appears briefly when changing tags

### What is the root cause of that problem?
For the invoice report, we move to this case and update the `iouReport` in `IOUUtils.updateIOUOwnerAndTotal `

https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/libs/actions/IOU.ts#L2398

In here we have the logic to swap `managerAccountID` and `ownerAccountID` when the total < 0. But for `invoice` report, the total is always `<0` so the `managerAccountID` is changed to the current user

https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/libs/IOUUtils.ts#L88-L92

And then not found page appear briefly by this condition
https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/libs/ReportUtils.ts#L2597-L2599
https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/pages/iou/request/step/IOURequestStepTag.tsx#L83
### What changes do you think we should make in order to solve the problem?
I think `invoice` report is similar with `expense` report, we should add the check for invoice report here so the `iouReport` can be updated correctly in optimistic data.

```
} else if ((ReportUtils.isExpenseReport(iouReport) || ReportUtils.isInvoiceReport(iouReport)) && typeof iouReport.total === 'number') {

```

https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/libs/actions/IOU.ts#L2388
### What alternative solutions did you explore? (Optional)
If the invoice report should be updated in `IOUUtils.updateIOUOwnerAndTotal`, we should change this condition accordingly for this report like this


```
if ((iouReportUpdate.total) * (ReportUtils.isInvoiceReport(iouReport) ? -1 : 1) < 0) {
```
https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/libs/IOUUtils.ts#L88-L92

**Comment by strepanier03** [comment] 2024-05-16 00:14
Working on testing this, haven't been able to repro so far but will keep working on it.

**Comment by strepanier03** [comment] 2024-05-21 20:59
I am only able to test via Browserstack and I'm still struggling to recreate this. I added testing labels so we can get some weekly testing done before moving forward.

**Comment by strepanier03** [comment] 2024-05-29 21:11
Retesting for now.

**Comment by mvtglobally** [comment] 2024-05-30 01:29
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2024-06-10 21:28
Pausing during retesting, no repro for 1 week. Holding.

**Comment by strepanier03** [comment] 2024-06-13 23:38
Pausing during retesting.

**Comment by strepanier03** [comment] 2024-06-18 02:23
Retesting.

**Comment by strepanier03** [comment] 2024-06-20 20:45
I'm not able to repro this still. Closing now.

**Closed by strepanier03** 2024-06-20 20:45 UTC
Labels: Daily, Overdue, Bug, retest-weekly
