### ISSUE TITLE
[HOLD for payment 2023-10-16] [$1000] Web - Chat - Hover effect lost after opening popover again before closing it.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25582] opened 2023-08-21 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Open the pop over right clicking
3. Move the pointer to the left or the right and right click again.

## Expected Result:
The hover effect is present

## Actual Result:
The hover effect is lost

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/992b7225-c2ed-4660-a46e-830c2f9a0498

https://github.com/Expensify/App/assets/115492554/ba2a8cb1-0b08-4871-b0e4-fa1b8dc8a81f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @getusha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691745427354299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c432588dbb79d8dd</li>
        <li>Upwork Job ID: 1693717160574693376</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26972863</li>
<li>getusha | Contributor | 26972865</li>
<li>getusha | Reporter | 26972866</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-08-21 14:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hover effect lost after opening context menu popover again before closing the opened one.
### What is the root cause of that problem?
We are passing `toggleContextMenuFromActiveReportAction` as `onHide` argument, which will make the `isContextMenuActive` false, currently we are passing empty function to be triggered for `onShow` param.

https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/pages/home/report/ContextMenu/ReportActionContextMenu.js#L59-L60

https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/pages/home/report/ReportActionItem.js#L226-L227

when we set isContextMenuActive to true here, when the previous context menu closes it will replace our true value with false. because `onHide` is triggered after the new `isContextMenuActive` update.

### What changes do you think we should make in order to solve the problem?


We should set `isContextMenuActive` to true `onShow` instead of calling it here:

https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/pages/home/report/ReportActionItem.js#L215

We should move `setIsContextMenuActive` to here, to be triggered onShow after onHide is called. this will insure it has the updated value.
https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/pages/home/report/ReportActionItem.js#L226-L226


```js
() => setIsContextMenuActive(true),
```

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-08-21 14:48
> onHide is triggered after the new isContextMenuActive update
@getusha I am about to propose the same solution but just wanted to understand the above point.

**Comment by getusha** [comment] 2023-08-21 15:07
@Pujan92 

https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/pages/home/report/ReportActionItem.js#L215

after the above update `onHide` will be triggered for the previous context menu then the new popover shows right? Once the onHide function is triggered, it will set the state to false, overriding the updated value which was set before opening the popover.

**Comment by getusha** [comment] 2023-08-21 20:37
@aimane-chnaif i have a proposal [here](https://github.com/Expensify/App/issues/25582#issuecomment-1686470940)

**Comment by tjferriss** [comment] 2023-08-24 16:19
@abdulrahuman5196 can you please review the proposals?

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:12
Apologies for the delay. Will check and update soon

**Comment by tjferriss** [comment] 2023-09-05 19:16
@abdulrahuman5196 any updates on your checks?

**Comment by abdulrahuman5196** [comment] 2023-09-11 19:15
Sorry folks for the delay. Will test on mobile and update sooner.

**Comment by tjferriss** [comment] 2023-09-12 21:58
I'm not actually able to reproduce this issue anymore. The hover effect is no longer lost.

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by getusha** [comment] 2023-09-13 17:23
Still able to reproduce.

**Comment by getusha** [comment] 2023-09-15 11:32
@abdulrahuman5196 any updates?

**Comment by abdulrahuman5196** [comment] 2023-09-15 17:24
> @tjferriss the issue still happens (tested on `main`)
> Screen.Recording.2023-09-13.at.12.05.27.mov

I think this is different issue than what this issue was initially created for. The initial issue is not reproducible anymore. 

But this seems to be a related issue. If its fine we can convert this issue to make sure only the message with context menu is highlighted. If that is the experience we want @tjferriss

**Comment by getusha** [comment] 2023-09-15 17:35
@abdulrahuman5196 please refer to this comment https://github.com/Expensify/App/pull/24515#discussion_r1300623349

https://github.com/Expensify/App/assets/75031127/dde8a1c9-9dc6-467c-84a6-9cf9232d1658

**Comment by tjferriss** [comment] 2023-09-16 22:24
I'm going to close this issue out as I don't view this hover effect as a bug, but as intended.

**Comment by getusha** [comment] 2023-09-17 06:59
@trjExpensify the hover effect is being lost when you move the mouse out but not the first time.

**Comment by lschurr** [comment] 2023-09-18 00:33
Sounds like this should be reopened according to these comments - https://github.com/Expensify/App/issues/27578#issuecomment-1722479126

**Comment by dhanashree-sawant** [comment] 2023-09-18 04:28
Moving my proposal here from #27578

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We are solving the problem of app removing background color from message when we again right click on same message to open popover
### What is the root cause of that problem?
Currently we use `IsContextMenuActive` boolean value in `ReportActionItem.js` to check if any action was done on current message and it is used to also set background color for the message. We set the boolean value as true first in `showPopover` and then reset the value to false for previous message using `toggleContextMenuFromActiveReportAction` in `showContextMenu` function call in same `showPopover` function.
Because of this, if we right click on same message, we set the `IsContextMenuActive` true for that message but since previous message too was same, we set `IsContextMenuActive` false again for it causing the issue.
### What changes do you think we should make in order to solve the problem?
We will need to change the position of `setIsContextMenuActive` function to the end of `showPopover`, it will ensure that previous selected message `IsContextMenuActive` is set to false and current selected message `IsContextMenuActive` is set to true later on avoiding the current issue.
We can do that by removing this line from [here](https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/pages/home/report/ReportActionItem.js#L238)
```
setIsContextMenuActive(true);
```
and adding it below [this](https://github.com/Expensify/App/blob/2427a06ed24f0649e55c14dbf4ae1a2a9ebe2109/src/pages/home/report/ReportActionItem.js#L253) line
### What alternative solutions did you explore? (Optional)

**Comment by tjferriss** [comment] 2023-09-25 05:22
> the hover effect is being lost when you move the mouse out but not the first time.

@getusha thanks for the description. I see it now. @abdulrahuman5196 what do you think of the proposals?

**Comment by abdulrahuman5196** [comment] 2023-09-27 11:13
Reviewing now

**Comment by tjferriss** [comment] 2023-09-29 04:40
@abdulrahuman5196 have you had a chance to review the proposals?

**Comment by abdulrahuman5196** [comment] 2023-09-29 15:21
@getusha 's proposal here https://github.com/Expensify/App/issues/25582#issuecomment-1686470940 looks good and works well. Tested on other platforms as well and it works fine.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2023-09-29 16:56
> @abdulrahuman5196 have you checked carefully the issues I mentioned on the small screen?

@bernhardoj yes. Couldn't find any. Let me know if you still find any.

**Comment by getusha** [comment] 2023-09-30 14:08
@bernhardoj that can be fixed if necessary, can you just apply the following diff without removing `setIsContextMenuActive(true)` and see if the issue persists?

<details><summary>Diff</summary>

```diff
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index fe1dcf248f..96e9a6d52f 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -247,7 +247,7 @@ function ReportActionItem(props) {
                 props.action.reportActionID,
                 originalReportID,
                 props.draftMessage,
-                () => {},
+                () => setIsContextMenuActive(true),
                 toggleContextMenuFromActiveReportAction,
                 ReportUtils.isArchivedRoom(originalReport),
                 ReportUtils.chatIncludesChronos(originalReport),
```

</details>

**Comment by getusha** [comment] 2023-10-01 09:51
@bernhardoj this is a straight forward issue with minor change and all of the proposals are similar. i'll also leave the final call for @abdulrahuman5196 @pecanoro

**Comment by abdulrahuman5196** [comment] 2023-10-01 14:12
IMO I don't think its an issue. It just acts as an extra check.
 I am still aligned towards the approved solution.

**Comment by pecanoro** [comment] 2023-10-02 04:06
@aimane-chnaif I still can reproduce on main!

Assigning @getusha to the issue

**Comment by abdulrahuman5196** [comment] 2023-10-02 09:12
> @abdulrahuman5196 can I have some feedback on my proposal [here](https://github.com/Expensify/App/issues/25582#issuecomment-1687297869)? I think it better addresses the root cause, and it's different from the selected proposal

I think that the proposal was fine. I choose based on the simplest solution to achieve the expected result without any regression or long term losses.

**Comment by getusha** [comment] 2023-10-02 22:25
@abdulrahuman5196 @pecanoro the [PR](https://github.com/Expensify/App/pull/28639) is ready!

**Comment by abdulrahuman5196** [comment] 2023-10-16 18:42
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. This issue should be present from before.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Go to any chat
2) Open the pop over right clicking
3) Move the pointer to the left or the right and right click again.
4) Move the mouse out of the report item
5) Verify that the hover effect is not lost when the popover is opened

**Comment by getusha** [comment] 2023-10-19 12:49
@tjferriss I received $50 offer for reporting bonus, i think it should be $250 since this issue was created before the announcement.

**Comment by pecanoro** [comment] 2023-10-23 13:56
@tjferriss Friendly bump since this is waiting on you.

**Comment by tjferriss** [comment] 2023-10-25 20:28
The payments have been sent via Upworks.

**Closed by tjferriss** 2023-10-25 20:28 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
