### ISSUE TITLE
[$1000] Web - Workspace name has no tooltip in Details section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20077] opened 2023-06-02 17:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an admin room
2. Click on the chat header
3. Hover over the workspace name
4. Observe that there is no tooltip

## Expected Result:
Tooptip with a label named 'Workspace'should be displayed as it does on other parts of the app when hovering over clickable text (link)

## Actual Result:
No tooltip is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5a5db78b-e10b-4d65-9f7e-199411960569

https://github.com/Expensify/App/assets/93399543/3becb715-ea2e-4a0a-b25c-636666d64259

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima
  

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685000867438649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011535b9ad2eb17c0b</li>
        <li>Upwork Job ID: 1666463593926651904</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-02 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace name has no tooltip in Details section 
### What is the root cause of that problem?
We haven't applied tooltip for this text
### What changes do you think we should make in order to solve the problem?
We should wrap `chatRoomSubtitleText` with `Tooltip` component here
https://github.com/Expensify/App/blob/050e158f8f121d25dba170d12ada352e2cd32b1a/src/pages/ReportDetailsPage.js#L168

### What alternative solutions did you explore? (Optional)

**Comment by michaelhaxhiu** [comment] 2023-06-07 15:14
Easily reproducible. It's surely missing!

**Comment by Kazuya-san** [comment] 2023-06-07 15:57
** Please re-state the problem that we are trying to solve in this issue.**

Web - Workspace name has no tooltip in Details section 

**Problem Statement**
The current issue in the GitHub repository is related to the absence of a tooltip for the workspace name in the Details section of the web application.

**Root Cause**
Upon reviewing the code, it has been identified that the tooltip component has not been applied to the workspace name (chatRoomSubtitleText) in the ReportDetailsPage.js file.

Proposed Solution:
To address this issue, the following technical changes should be made:

Open the ReportDetailsPage.js file located at App/src/pages/ReportDetailsPage.js.
Navigate to line 167, where the workspace name (chatRoomSubtitleText) is being rendered.
Wrap the chatRoomSubtitleText with a Tooltip component, which will provide the desired tooltip functionality.

**Alternative Solutions (Optional)**
During the review process, alternative solutions were not explored as the proposed solution directly addresses the issue by applying the necessary Tooltip component.

**Comment by Kazuya-san** [comment] 2023-06-07 15:58
**### Please re-state the problem that we are trying to solve in this issue**

Web - Workspace name has no tooltip in Details section

**### Problem Statement**
The current issue in the GitHub repository is related to the absence of a tooltip for the workspace name in the Details section of the web application.

**### Root Cause**
Upon reviewing the code, it has been identified that the tooltip component has not been applied to the workspace name (chatRoomSubtitleText) in the ReportDetailsPage.js file.

**### Proposed Solution**
To address this issue, the following technical changes should be made:

Open the ReportDetailsPage.js file located at App/src/pages/ReportDetailsPage.js.
Navigate to line 167, where the workspace name (chatRoomSubtitleText) is being rendered.
Wrap the chatRoomSubtitleText with a Tooltip component, which will provide the desired tooltip functionality.

**### Alternative Solutions (Optional)**
During the review process, alternative solutions were not explored as the proposed solution directly addresses the issue by applying the necessary Tooltip component

**Comment by BhuvaneshPatil** [comment] 2023-06-07 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace name has no tooltip in Details section

### What is the root cause of that problem?
We are not wrapping the {chatRoomSubtitleText} in tooltip component.
https://github.com/Expensify/App/blob/b00fc124c40839d6888d2bec6ed50d4a69edbc6b/src/pages/ReportDetailsPage.js#L158-L164
### What changes do you think we should make in order to solve the problem?
We should wrap the component <Pressable/>  component that renders the `chatRoomSubtitleText` with `Tooltip` component. and the prop `text` equal to `common.settings` (this detail is missing in other proposals).

### What alternative solutions did you explore? (Optional)
None

**Comment by michaelhaxhiu** [comment] 2023-06-07 16:50
My thinking was that we should show a tool tip because other RHN areas in the product tend to have one in this location. 

Though now I am testing how we handle other DMs with users, and there doesn't appear to be a tool tip there either 🤔 

![inconsis](https://github.com/Expensify/App/assets/13206896/82c45f56-2856-4544-8ee5-d703a71c0bd8)

But if I click my avatar, it expands the RHN drawer and I see a tool tip here:
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/13206896/b432f05c-74ea-4840-9c4c-4b5cd74b5f64">

It does feel inconsistent though to me - do you agree? I think your root question is "What's the expected behavior?" right?

**Comment by Natnael-Guchima** [comment] 2023-06-07 17:02
> What is the issue here? 
> @michaelhaxhiu because you triaged this. What do you think we should show in the tooltip? 
> 
> @Natnael-Guchima What should be visible on the tooltip content?

I am thinking that it should display the workspace name as it does on workspace section.  In that way, it would be consistent with the workspace section and gives the user a sense that the name is clickable.

**Comment by michaelhaxhiu** [comment] 2023-06-07 23:03
Overall, I'm sold by your argument @parasharrajat. 

I will close this GH. If you'd like to raise a more specific bug report about how to improve this, you are welcome to try your hand @Natnael-Guchima.

**Closed by michaelhaxhiu** 2023-06-07 23:03 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by michaelhaxhiu** [comment] 2023-06-07 23:34
While that's true, I think it's also my job as a BZ assignee to make a choice on whether or not we proceed with a given bug report (or feature request). I chose to proceed here initially, and then went back on that choice! So I'm at fault too. Either way it's all good. onwards.
