### ISSUE TITLE
[$500] Create an ESLint rule to detect multiple uses of withOnyx

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#27463] opened 2023-09-14 18:05 UTC
# Problem
When `withOnyx` is used multiple times while composing components, it adds overhead to what Onyx has to keep track of and also prevents optimizations like batched render updates from working to their full potential.

# Solution
Create a custom ESLint in https://github.com/Expensify/eslint-config-expensify/tree/main/eslint-plugin-expensify which detects when `withOnyx()` is used multiple times in the same file, and throws an error. The error should give instructions on the best practices which is something like:

> Only use withOnyx() once. If there are dependent Onyx keys, they can all be handled in a single instance of withOnyx through the use of selectors. 

That should also link to the [Onyx readme](https://github.com/Expensify/react-native-onyx/blob/main/README.md), and I'm going to write a specific section in there about the best practice that we can link to. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f185d4f92edd4f6c</li>
        <li>Upwork Job ID: 1702383017796775936</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26743007</li>
<li>studentofcoding | Contributor | 26743012</li>
</ul></li>
    </ul>
</details>

**Comment by needpower** [comment] 2023-09-14 18:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`withOnyx()` can be called multiple times while composing components.

### What is the root cause of that problem?
Sometimes developers do not notice that `withOnyx()` is already called, and create a new call instead of extending the existing one.

### What changes do you think we should make in order to solve the problem?
Create a new eslint rule in https://github.com/Expensify/eslint-config-expensify/blob/main/eslint-plugin-expensify/ called `no-multiple-onyx-calls` which will display an error message in case of multiple calls, e.g.
```js
export default compose(
    withOnyx({
        isCheckingPublicRoom: {
            key: ONYXKEYS.IS_CHECKING_PUBLIC_ROOM,
            initWithStoredValues: false,
        }
    }),
    withOnyx({
        isSidebarLoaded: {
            key: ONYXKEYS.IS_SIDEBAR_LOADED,
        },
    })
)(Component)
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by alitoshmatov** [comment] 2023-09-14 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create an ESLint rule to detect multiple uses of withOnyx 
### What is the root cause of that problem?
Feature request
### What changes do you think we should make in order to solve the problem?
We should add a new rule to https://github.com/Expensify/eslint-config-expensify/tree/main/eslint-plugin-expensify to check if `withOnyx` is used more than once

We can achieve it with something like this:
```javascript

module.exports = {
    meta: {
        type: 'problem',
        docs: {
            description: "Prevent multiple calls to 'withOnyx' function in a file",
            category: 'Best Practices',
            recommended: true,
        },
        fixable: 'code',
    },

    create(context) {
        const callStack = [];

        return {
            CallExpression(node) {
                if (node.callee.name === 'withOnyx') {
                    callStack.push(node);
                }
            },

            'Program:exit'() {
                if (callStack.length > 1) {
                    context.report({
                        node: callStack[1],
                        message: "Multiple calls to 'withOnyx' function are not allowed in a file.",
                    });
                }
            },
        };
    },
};
```

### What alternative solutions did you explore? (Optional)

**Comment by studentofcoding** [comment] 2023-09-14 20:19
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Create an ESLint rule to detect multiple uses of `withOnyx`

## What is the root cause of that problem?
Feature request for Create an ESLint rule to detect multiple uses of `withOnyx`

## What changes do you think we should make in order to solve the problem?

We should add a new rule to https://github.com/Expensify/eslint-config-expensify/tree/main/eslint-plugin-expensify to check if `withOnyx` is used more than once, and use the same pattern and modules like others ESLint files (lodashGet, _ (underscore), and message) with the details below:

1. On [CONST.js](https://github.com/Expensify/eslint-config-expensify/blob/main/eslint-plugin-expensify/CONST.js) we add `NO_MULTIPLE_ONYX_IN_FILE` with our desired details so we can use later on `no-multiple-onyx-in-file.js`

```
module.exports = {
    MESSAGE: {
        ...
        NO_MULTIPLE_ONYX_IN_FILE: 'Example: Only use withOnyx() once. If there are dependent Onyx keys, they can all be handled in a single instance of withOnyx through the use of selectors.',
        ...
    },
};
``` 

2. Create `no-multiple-onyx-in-file.js` on [eslint-plugin-expensify](https://github.com/Expensify/eslint-config-expensify/tree/main/eslint-plugin-expensify) and use the same pattern modules

```
const _ = require('underscore');
const lodashGet = require('lodash/get');
const message = require('./CONST').MESSAGE.NO_MULTIPLE_ONYX_IN_FILE;

module.exports = {
    create: context => {
        let withOnyxCount = 0;

        return {
            CallExpression(node) {
                const calleeName = lodashGet(node, 'callee.name');

                if (calleeName === 'withOnyx') {
                    withOnyxCount += 1;

                    if (withOnyxCount > 1) {
                        context.report({
                            node,
                            message,
                        });
                    }
                }
            },
            'Program:exit': () => {
                withOnyxCount = 0;
            },
        };
    },
};
```

In the above example, the error is reported if there are multiple `withOnyx` calls in the same file, and reset to 0 when ESLint finishes traversing the file.

## What alternative solutions did you explore? (Optional)

If we want to show the error directly on any multiple `withOnyx` we can use the below approach

```
const _ = require('underscore');
const lodashGet = require('lodash/get');
const message = require('./CONST').MESSAGE.NO_MULTIPLE_ONYX_IN_FILE;

module.exports = {
    create: context => {
        let withOnyxCount = 0;

        return {
            CallExpression(node) {
                const calleeName = lodashGet(node, 'callee.name');

                if (calleeName === 'withOnyx') {
                    withOnyxCount += 1;

                    if (withOnyxCount > 1) {
                        context.report({
                            node,
                            message,
                        });
                    }
                }
            },
        };
    },
};
```

cc: @tgolen @mallenexpensify @mollfpr

**Comment by mollfpr** [comment] 2023-09-15 18:05
>When withOnyx is used multiple times while composing components, it adds overhead to what Onyx has to keep track of and also prevents optimizations like batched render updates from working to their full potential.

@tgolen To clarify the lint only detect multiple `withOnyx` in the compose function?
E.g.

```js
compose(
    withOnyx({
        A,
    }),
    withOnyx({
        B
    })
)
```

Or also detect `withOnyx` inside the other HOC e.g. `withPolicy`.

```js
compose(
    withPolicy,
    withOnyx({
        A,
    })
)
```

**Comment by tgolen** [comment] 2023-09-15 19:11
I was really only thinking of targeting multiple `withOnyx` in the compose function (the first example). 

I didn't consider about the second example, but I am guessing we don't have very many HOCs that use `withOnyx()`. It's probably fine for now. I think of `withPolicy` more like it's own component, just like any other component.

**Comment by mollfpr** [comment] 2023-09-18 13:55
@needpower Could you elaborate on your solution to show the error on multiple Onyx calls?

@alitoshmatov Seems nice, but it will be great if we show the error on all other Onyx calls, not just on the first duplicate.

![Screenshot 2023-09-18 at 20 31 24](https://github.com/Expensify/App/assets/25520267/8602b02f-3411-465f-9e45-7d57c0163f28)

>I was really only thinking of targeting multiple withOnyx in the compose function (the first example).

@ZhenjaHorbach Great idea, but I prefer to stick to the expectation above. Also,  please don't leave the root cause section empty.

@studentofcoding Could you explain why we need to add `Program:exit`? Is there any significant different without it?

**Comment by studentofcoding** [comment] 2023-09-18 14:07
Hey @mollfpr, we can benefit from adding `Program:exit` only if we want to include this ESLint to run into our automatic test, so:
- It'll give `error` for each `withOnyx` found on all files (as it'll reset to 0, when finishing checking the file)

But, if we want to only run the checking on specific files that opened, then the alternative approach will be sufficient (with also using and extending the pattern that we already have for other ESLint rule)
```
const _ = require('underscore');
const lodashGet = require('lodash/get');
const message = require('./CONST').MESSAGE.NO_MULTIPLE_ONYX_IN_FILE;

module.exports = {
    create: context => {
        let withOnyxCount = 0;

        return {
            CallExpression(node) {
                const calleeName = lodashGet(node, 'callee.name');

                if (calleeName === 'withOnyx') {
                    withOnyxCount += 1;

                    if (withOnyxCount > 1) {
                        context.report({
                            node,
                            message,
                        });
                    }
                }
            },
        };
    },
};
```

**Comment by alitoshmatov** [comment] 2023-09-18 14:11
@mollfpr You are right we can achieve that by following code 
```javascript

module.exports = {
    create(context) {
        const callStack = [];

        return {
            CallExpression: (node)=> {
                if (node.callee.name === 'withOnyx') {
                    callStack.push(node);
                }
                if (callStack.length > 1) {
                    context.report({
                        node: callStack[callStack.length - 1],
                        message: "Multiple calls to 'withOnyx' function are not allowed in a file.",
                    });
                }
            },
        };
    },
};
```
Where we report an error on every last instance of `withOnyx`

**Comment by studentofcoding** [comment] 2023-09-18 15:21
> Thanks @studentofcoding, for the explanation. I think our automatic action is to run `npm run lint` and I believe it will work without the hook.
> 
> 
> 
> @alitoshmatov Could you update that to your proposal? Thanks!


Just for another context, the fix on @alitoshmatov above are already apart on my initial Alternative solution @mollfpr

**Comment by alitoshmatov** [comment] 2023-09-18 15:24
Updated my proposal - https://github.com/Expensify/App/issues/27463#issuecomment-1719941582

**Comment by mollfpr** [comment] 2023-09-18 15:36
>Just for another context, the fix on @alitoshmatov above are already apart on my initial Alternative solution https://github.com/Expensify/App/issues/27463#issuecomment-1720088085 4 days before @mollfpr

I believe @alitoshmatov is posting it first.

A couple of proposals seem similar, just different in the logic of showing the error. I think there's no difference on which it's better, so I'll choose the first posted proposal that works.

The [proposal](https://github.com/Expensify/App/issues/27463#issuecomment-1719941582) from @alitoshmatov looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by studentofcoding** [comment] 2023-09-18 21:49
> > Just for another context, the fix on @alitoshmatov above are already apart on my initial Alternative solution [#27463 (comment)](https://github.com/Expensify/App/issues/27463#issuecomment-1720088085) 4 days before @mollfpr
> 
> I believe @alitoshmatov is posting it first.
> 
> A couple of proposals seem similar, just different in the logic of showing the error. I think there's no difference on which it's better, so I'll choose the first posted proposal that works.
> 
> The [proposal](https://github.com/Expensify/App/issues/27463#issuecomment-1719941582) from @alitoshmatov looks good to me!
> 
> 🎀 👀 🎀 C+ reviewed!

Although I understand that the order matters, I believe the correctness and thoroughness of details (in this case, using all modules we already used on another ESLint) will also add the point for choosing a proposal. 

But, if it's not, then I just want to speak my mind about this, cheers!

**Comment by neil-marcellini** [comment] 2023-09-19 00:06
@mollfpr I actually like @studentofcoding's [proposal](https://github.com/Expensify/App/issues/27463#issuecomment-1720088085) better because the program exit thing seems like a good idea, and more importantly he used the correct error message mentioned in the issue. 

In the interest of speed I'm going to hire him now, hopefully everyone feels good about this.

**Comment by studentofcoding** [comment] 2023-09-19 06:54
Thanks, @neil-marcellini

Upon Reading the Readme on https://github.com/Expensify/eslint-config-expensify it's said that the PR should be there, therefore it's ready to review on https://github.com/Expensify/eslint-config-expensify/pull/73 @mollfpr @tgolen

**Comment by studentofcoding** [comment] 2023-09-19 14:37
The PR is ready @neil-marcellini @mollfpr @tgolen https://github.com/Expensify/eslint-config-expensify/pull/73

**Comment by studentofcoding** [comment] 2023-09-21 04:39
The follow up PR is ready for review @tgolen @mollfpr https://github.com/Expensify/App/pull/27840, thanks!

**Comment by studentofcoding** [comment] 2023-09-22 03:10
Hey @MelvinBot the PR is merged yesterday (takes 2 days)

**Comment by studentofcoding** [comment] 2023-09-27 00:34
Hey @tgolen, as the PR is merged 6 days ago, and @MelvinBot didn't automatically report it. I believe the waiting time for payment is only 1 day left and tomorrow it should be released right?

**Comment by tgolen** [comment] 2023-09-27 01:23
I believe so, but I am not involved in that part of the process too much. @mallenexpensify might know better since he is handling the payment side for this issue.

**Comment by studentofcoding** [comment] 2023-09-27 01:28
Thanks for it @tgolen, This is also happening on [another PR](https://github.com/Expensify/App/issues/24341), in which we have to change the Title of the Issue. If I need to do anything, do let me know @mallenexpensify, thanks!

**Comment by studentofcoding** [comment] 2023-09-27 17:43
> Hey @tgolen, as the PR is merged 6 days ago, and @MelvinBot didn't automatically report it. I believe the waiting time for payment is only 1 day left and tomorrow it should be released right?

Can we have a guide on this condition @mallenexpensify ? Thanks!

**Comment by mallenexpensify** [comment] 2023-09-29 15:13
Contributor: @studentofcoding paid $750 via Upwork, includes 50% urgency bonus
Contributor+: @mollfpr is due $750. Unsure if paying via Upwork or NewDot yet, will know next week.

**Comment by mallenexpensify** [comment] 2023-10-02 13:51
confirming payment for @mollfpr internally 
https://expensify.slack.com/archives/C01SKUP7QR0/p1696254687480909

**Comment by mollfpr** [comment] 2023-10-19 12:49
@mallenexpensify I should be paid via Upwork since I already have the contract for this issue.

**Comment by mallenexpensify** [comment] 2023-10-20 00:56
Thanks @mollfpr , I agree, updated the above to reflect you've been paid via Upwork!

**Closed by mallenexpensify** 2023-10-20 00:56 UTC
Labels: Reviewing, External, Weekly, NewFeature
