### ISSUE TITLE
[$500] LHN last message is not updating after deleting attachment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26564] opened 2023-09-02 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Send any attachment
3. Observe the sub-title in LHN
4. Click on attachment in tab 1 see it opens in modal
5. Open same report in other tab (tab2) and delete the attachement.
6. Observe that after delete modal get's closed but not LHN updating.
## Expected Result: 
LHN should update as well with next previous message
## Actual Result: 
Not updating

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c8777fbe-de78-4ac9-b775-17af278089d4

https://github.com/Expensify/App/assets/43996225/5f65e207-3a6b-4e5c-97ad-36ce4c1f4eac

**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692975870405119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f650b305c679ab3</li>
        <li>Upwork Job ID: 1698475872240963584</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-09-05 05:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN last message is not updating after deleting attachment

### What is the root cause of that problem?
The function `getLastMessageTextForReport` as shown [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/OptionsListUtils.js#L387) is used to decide on the text used in LHN. Now, within `getLastMessageTextForReport`, we use `isReportMessageAttachment` [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/OptionsListUtils.js#L394) to find out if the `lastMessageTextFromReport` is an attachment. Since `lastMessageText` and `lastMessageHtml` is sufficient to decide on whether it is attachment or not based on [code here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/isReportMessageAttachment.js#L15-L20), we can depend on them for making this decision. However, the decision is also based on `lastMessageTranslationKey` which does not seem proper here. Using `lastMessageTranslationKey` to decide on the `lastMessageTextFromReport` seems to be the reason for this problem.

### What changes do you think we should make in order to solve the problem?

We can avoid using `lastMessageTranslationKey` as follows [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/OptionsListUtils.js#L394C1-L394C1)
  
`  if (ReportUtils.isReportMessageAttachment({text: report.lastMessageText, html: report.lastMessageHtml})) {`

The above condition is safe as `lastMessageTranslationKey` itself is determined based on `lastMessageText` and `lastMessageHtml` as [shown here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/ReportActionsUtils.js#L399C13-L399C13) in `getLastVisibleMessage` function.

Further, I am not sure if there is a need to set `lastMessageHtml` [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/ReportActionsUtils.js#L401) as part of implementation of [PR here](https://github.com/Expensify/App/pull/26194).
I have asked a [query there](https://github.com/Expensify/App/pull/26194#issuecomment-1705954197). 

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-05 10:17
The pusher doesn't return lastMesageTranslationKey

<img width="1440" alt="Screenshot 2023-09-05 at 17 16 20" src="https://github.com/Expensify/App/assets/141406735/c68752f5-fd3f-4280-84e1-19139e20cbb6">

 I think we should fix this from BE side

**Comment by adelekennedy** [comment] 2023-09-06 21:39
@jjcoffee can you review the proposals above?

**Comment by jjcoffee** [comment] 2023-09-07 13:21
This seems like a pretty edgy edge case to me! It requires being signed in as the same user in two tabs, which in itself is a pretty unlikely use case - but then adding on top of that trying to switch between tabs and make actions on one and see the changes on another is just not something I think a normal user would do. I recommend closing unless there's a deeper issue. cc @adelekennedy 

Additionally, the RCAs proposed so far don't seem to be correct as the behaviour doesn't happen when logged in to a separate account, but `lastMesageTranslationKey` is also not returned in the pusher event in that case:
![image](https://github.com/Expensify/App/assets/27287420/7342c00e-b4df-4fec-b098-abf3a41313b1)

**Comment by rojiphil** [comment] 2023-09-07 14:22
> the RCAs proposed so far don't seem to be correct as the behaviour doesn't happen when logged in to a separate account

That's interesting! Will check why?

**Comment by adelekennedy** [comment] 2023-09-11 05:37
Let's close this! I love eliminating edge cases

**Closed by adelekennedy** 2023-09-11 05:37 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
