### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web - User can use the composer and chat while the RHP is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23403] opened 2023-07-22 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Make sure you have a workspace created.  
1. Login and open any chat room.
2. Go to settings by clicking on your avatar and open the RHP.
3. Refresh the page ( IMPORTANT! ).
( Now we want to open any Modal, let's use the "delete workspace" modal )
4. Go to workspaces and click on a workspace.
5. Click on the 3 dots at the top right.
6. Click Delete workspce to show the modal
7. Click Cancel to close the modal
8. Now start typing while The RHP is open.

## Expected Result:
User Shouldn't be able to type anything because the RHP is open, and the composer text input is not focused.

## Actual Result:
Once the user start typing while the RHP is open, The composer is focused and user can use it to type and send messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 21-07-23 08_28_24.webm](https://github.com/Expensify/App/assets/93399543/7215f84b-e2d6-40a9-ad2e-629995e165d8)

https://github.com/Expensify/App/assets/93399543/ff116105-95c5-4e46-9b29-0cf0fd93042e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689919902028749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a88e9c324c81b2d4</li>
        <li>Upwork Job ID: 1689477016355319808</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26489111</li>
<li>Ahmed-Abdella | Reporter | 26489112</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-25 04:45
Reproduced:

https://github.com/Expensify/App/assets/59587260/f9333a49-4bd3-46d1-8e22-1fff61ddeba0

**Comment by kadiealexander** [comment] 2023-07-25 04:46
@parasharrajat as the C+ for https://github.com/Expensify/App/issues/23184, do you think this has the same root cause?

**Comment by kadiealexander** [comment] 2023-07-26 03:18
Awesome thanks Rajat! I'll place this on hold for @Santhosh-Sellavel's investigation [here](https://github.com/Expensify/App/issues/16098#issuecomment-1648754109) too.

**Comment by kadiealexander** [comment] 2023-08-07 04:30
@Santhosh-Sellavel any update?

**Comment by PauloGasparSv** [comment] 2023-08-09 23:13
Hey @kadiealexander we discussed this issue and https://github.com/Expensify/App/issues/16098 over at this [slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1690242585218809) and [we decided](https://expensify.slack.com/archives/C02NK2DQWUX/p1691622467032029?thread_ts=1690242585.218809&cid=C02NK2DQWUX) that it is best to close https://github.com/Expensify/App/issues/16098 and work on this issue as usual  letting the CPlus/Engineer assigned here take care of the bug.

Putting this off hold and changing back to daily.

**Comment by kadiealexander** [comment] 2023-08-10 03:21
Thanks @PauloGasparSv!!

**Comment by aswin-s** [comment] 2023-08-10 04:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Composer is focused even when a modal is open and user is allowed to type in the composer.

### What is the root cause of that problem?

Once user closes a `PopoverMenu` it sets the modal visibility prop to `false` even when there are other modals open. This causes the ReportActionCompose to get auto focused because of this line. In this case it is the ThreeDotMenu in header button that resets the modal visibility to `false` on closure. 

https://github.com/Expensify/App/blob/d6a14d797753e8b7886b3c85a4450ff9cdd6e6be/src/pages/home/report/ReportActionCompose.js#L211



### What changes do you think we should make in order to solve the problem?

Popups are not regular modals and shouldn't be setting modal visibility value in Onyx. Since Popup is extending BaseModal it also inherits onHideModal logic from it.

https://github.com/Expensify/App/blob/d6a14d797753e8b7886b3c85a4450ff9cdd6e6be/src/components/Modal/BaseModal.js#L68-L76

To prevent resetting modal visibility state we should set the `shouldSetModalVisibility` prop of [PopoverMenu](https://github.com/Expensify/App/blob/d6a14d797753e8b7886b3c85a4450ff9cdd6e6be/src/components/PopoverMenu/index.js#L73) component to false.

```tsx
  <PopoverWithMeasuredContent
            anchorPosition={props.anchorPosition}
            anchorAlignment={props.anchorAlignment}
            onClose={props.onClose}
            isVisible={props.isVisible}
            // Add this prop
            shouldSetModalVisibility={false}

```
### What alternative solutions did you explore? (Optional)
None

**Comment by ArekChr** [comment] 2023-08-11 11:05
@aswin-s I feel that adding the `shouldSetModalVisibility` prop might complicate the logic. I'm leaning towards the idea that we shouldn't control things from the level of the props. Perhaps it is possible to check if RHP is opened? That might avoid additional props.

**Comment by b4s36t4** [comment] 2023-08-13 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - User can use the composer and chat while the RHP is open
### What is the root cause of that problem?
Main RCA for this issue https://github.com/Expensify/App/issues/23403#issuecomment-1672535028 as mentioned in this proposal.

Also We have an issue here in this snippet as well https://github.com/Expensify/App/blob/a3d3cc77db822054953cf250bd42eda0efe6823c/src/pages/home/report/ReportActionCompose.js#L716.

We're checking if the modal is visible or not which is kinda working in most-cases but cases like this would cause the issue.

### What changes do you think we should make in order to solve the problem?

I feel there could be two solutions for this.

1. If we're focusing on the `modal` onyx key we should have write some logic which will track the onyx key before setting the value to it. If the `modal.isVisible` is already set to `true` we should track the existing value and have to rely on that before setting value to onyx key.

Ex: If the first modal set's value as `true`, when we open the `ConfirmModal` we should track the existing key and we shouldn't set any value inside the `ConfirmModal` leaving the state as it is.

2. Leaving the existing implementation as it is with the `Modal` logic, https://github.com/Expensify/App/blob/a3d3cc77db822054953cf250bd42eda0efe6823c/src/pages/home/report/ReportActionCompose.js#L716 inside this function we should also check for the Navigation focus logic. We're also using navigation focus related logic to copy,paste the text with the composer so I feel this should work too.

Instead of just relying the on `modal.isVisible`'s value, we should also check `this.props.navigation.isFocused()` value to prevent the focus https://github.com/Expensify/App/blob/a3d3cc77db822054953cf250bd42eda0efe6823c/src/pages/home/report/ReportActionCompose.js#L721 here in this function.



### What alternative solutions did you explore? (Optional)
NA

**Comment by kadiealexander** [comment] 2023-08-14 01:37
Not overdue, @ArekChr please check the proposals above when you get a moment :)

**Comment by ArekChr** [comment] 2023-08-16 11:22
> ```js
> function isCPNRoute() {
>   const rootState = navigationRef.getRootState();
>   const lastRoute = _.last(rootState.routes);
>   return lastRoute.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR;
> }
> ```

@ginsuma We could further enhance security by leveraging `useIsFocused` from `@react-navigation/native` to check the screen is focused. Utilizing the navigation state seems like a good approach to preventing regressions, mainly when the report screen isn't focused during modals closes.

[Proposal](https://github.com/Expensify/App/issues/23403#issuecomment-1674618778) LGTM!

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by ArekChr** [comment] 2023-08-16 11:42
@b4s36t4 That's right, the proposals are similar and straightforward, they rely on navigation state so I chose the first one, the change I suggested is a minor thing in my opinion

**Comment by MariaHCD** [comment] 2023-08-16 13:19
It looks like @ArekChr chose @ginsuma's [proposal](https://github.com/Expensify/App/issues/23403#issuecomment-1674618778)? With the change that `useIsFocused` should be used instead of introducing a new function `isCPNRoute`. Is that right, @ArekChr?

Additionally, for `shouldAutoFocus`, can we also use `useIsFocused` instead of `isCPNRoute`?

**Comment by MariaHCD** [comment] 2023-08-16 13:59
And by `two checks`, you mean use `isCPNRoute` as well as `useIsFocused`?

**Comment by ArekChr** [comment] 2023-08-16 15:29
> And by `two checks`, you mean use `isCPNRoute` as well as `useIsFocused`?

Yes

**Comment by b4s36t4** [comment] 2023-08-16 15:31
@ginsuma Thanks for the support ❤️. @ArekChr I don't think we need two checks here. Both of the checks does same thing although. But I feel `useIsFocused` the simple and stright forward apporach.

**Comment by kadiealexander** [comment] 2023-08-20 23:58
@MariaHCD are we ready to go with the proposal here?

**Comment by MariaHCD** [comment] 2023-08-21 13:25
@ginsuma @ArekChr, should this issue be part of https://github.com/Expensify/App/issues/15992?

From that issue, it sounds like we want to avoid patches like this and have a more holistic solution to the composer focus issue. What do you think?

**Comment by kadiealexander** [comment] 2023-08-22 01:17
@Ahmed-Abdella are you still able to reproduce this?

**Comment by Ahmed-Abdella** [comment] 2023-08-22 01:28
@kadiealexander It is no longer reproducable neither on DEV  or STAGE

**Comment by Ahmed-Abdella** [comment] 2023-08-22 01:30
@kadiealexander Earlier today, it was reproducible on STG but not on DEV. Now, it is not reproducible on either.

**Comment by MariaHCD** [comment] 2023-08-25 13:36
https://github.com/Expensify/App/pull/18648 has been merged and deployed. @Ahmed-Abdella, could you verify if this issue is still reproducible?

**Comment by Ahmed-Abdella** [comment] 2023-08-25 13:44
@MariaHCD I have checked and found that the issue is no longer reproducible on both staging and production.

**Comment by MariaHCD** [comment] 2023-08-25 13:57
Thanks, @Ahmed-Abdella! I tested on dev and haven't been able to reproduce the issue either. I think we can close this. I don't believe any payments will need to be made here. cc: @kadiealexander

**Comment by situchan** [comment] 2023-08-25 14:07
We should put this on another hold - ReportActionCompose is being big refactored again in https://github.com/Expensify/App/pull/25758.
Here's hold announcement: https://expensify.slack.com/archives/C02NK2DQWUX/p1692874524400529

**Comment by MariaHCD** [comment] 2023-08-25 14:13
@ginsuma regarding https://github.com/Expensify/App/pull/18648#issuecomment-1686676751, could you provide a recording of the regression you described there? I'm not really sure it's a problem 🤔 

Thanks for heads up @situchan! Agreed that this should be on hold but I do want to determine if this is really a problem or not since it's not reproducible and I'm not sure if [this](https://github.com/Expensify/App/pull/25758) regression is really a regression. Thoughts, @ArekChr?

**Comment by b4s36t4** [comment] 2023-08-25 15:19
This issue re-produceable after the above merge. Bug here - https://expensify.slack.com/archives/C049HHMV9SM/p1692976685634629

**Comment by kadiealexander** [comment] 2023-08-29 05:19
@ginsuma your video doesn't display the behaviour described in the OP, it's clear you can't type while the RHP is open. 

I'm no longer able to reproduce this either.

**Comment by ArekChr** [comment] 2023-08-29 07:54
This issue is still valid and reproduced on staging and dev env. 

https://github.com/Expensify/App/assets/24796318/3b1f3600-e0fb-49e8-81d5-7ad7bb80773e

**Comment by Ahmed-Abdella** [comment] 2023-08-29 14:12
Yes, I am able to reproduce this issue once again now.

**Comment by MariaHCD** [comment] 2023-09-04 08:40
Okay, looks like we don't have anyone else working on this bug so let's proceed here! 

I believe the solution here will also fix this: https://expensify.slack.com/archives/C049HHMV9SM/p1692946269895169

@ArekChr does your [recommended proposal](https://github.com/Expensify/App/issues/23403#issuecomment-1680422969) still stand or has anything changed since then?

**Comment by Ahmed-Abdella** [comment] 2023-09-04 13:12
Hey, @MariaHCD sorry for that, but shouldn't it be under 250$ as it is reported and go external before 30 Aug, or I miss something? sorry again

**Comment by b4s36t4** [comment] 2023-09-04 13:22
@Ahmed-Abdella I think because of update with the bot, upwork will only show 50$. I'm sure it's 250$ because this was create before the change.

**Comment by MariaHCD** [comment] 2023-09-04 13:47
Since this bug was reported in July (and before the [change on Aug 30th](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649)), I think the previous rates will apply for this issue. I'll defer to @kadiealexander, though!

**Comment by Ahmed-Abdella** [comment] 2023-09-04 13:52
@MariaHCD  then should I accept the offer or wait for @kadiealexander to change it

**Comment by MariaHCD** [comment] 2023-09-04 14:24
I think you can wait until @kadiealexander is able to address this

**Comment by kadiealexander** [comment] 2023-09-05 02:25
Agreed! I'll change the amounts. Sorry team, these kinds of changes are never smooth!

**Comment by ArekChr** [comment] 2023-09-12 07:54
I have been OOO for three days after @b4s36t4 got assigned.

**Comment by ArekChr** [comment] 2023-09-14 08:13
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I think we may have a regression test for that issue.

Regression Test Proposal

1. Login and open any chat room.
2. Go to settings by clicking on your avatar and open the RHP.
3. Go to workspaces and click on any workspace.
4. Click on the three dots at the top right.
5. Click Delete workspace to show the modal.
6. Click Cancel to close the modal.
7. Start typing while The RHP is open.
8. Ensure that the composer is still not focused and that input doesn't change.

Do we agree :+1: or :-1:

**Comment by kadiealexander** [comment] 2023-09-20 04:11
Payouts due:

- [ ] Issue Reporter: $250 @Ahmed-Abdella
- [ ] Contributor: $1000 @b4s36t4

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/23403#issuecomment-1714888255)

Upwork job is [here](https://www.upwork.com/jobs/~01a88e9c324c81b2d4).

**Comment by kadiealexander** [comment] 2023-09-20 04:50
Payments complete!

**Closed by kadiealexander** 2023-09-20 04:50 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by b4s36t4** [comment] 2023-09-20 05:06
@kadiealexander https://github.com/Expensify/App/issues/23403#issuecomment-1715193712 as per the comment maybe bonus applies? @ArekChr for any input if possible?

**Comment by ArekChr** [comment] 2023-09-20 09:36
@kadiealexander I was at the RNEU conference when this proposal was approved, which caused me to postpone the review for three days

**Comment by b4s36t4** [comment] 2023-09-22 15:18
@kadiealexander friendly bump ^^.
