### ISSUE TITLE
[AU] Chat - Only a single word is copied when using "Copy to clipboard" on a sentence

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53734] opened 2024-12-07 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5312619
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Log out

1. Navigate to https://staging.new.expensify.com/r/2091104345528462
2. Hover over a sentence with multiple words
3. Right click on a word
4. Click on "Copy to clipboard"
5. Paste is somewhere

## Expected Result:
The full sentence should be copied.

## Actual Result:
Only a single word is copied when using "Copy to clipboard" on a sentence.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/24fd759e-7289-4fc6-81f3-0dcb3ca36d63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by QichenZhu** [comment] 2024-12-09 12:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Safari, _Copy to clipboard_ copies only one word instead of the whole message.

### What is the root cause of that problem?
The app checks if the selection is empty. If so, it copies the entire message. Otherwise, it copies only the selected text.

https://github.com/Expensify/App/blob/9d418f5dfb471859677df5d364abc9e72daec1c4/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L386

However, the word under the cursor is automatically selected after right-clicking in Safari and Chrome on MacOS.

In Safari, the timing is: `mousedown` event -> word selection -> `contextmenu` event.

In Chrome, the timing is: `mousedown` event -> `contextmenu` event -> word selection.

The app accesses the selection in `contextmenu` event handler. In Safari, the word is already selected by the time the handler runs, but in Chrome, it’s not.

https://github.com/Expensify/App/blob/1db6abb66106b1a855321f907408357fbcc8f78c/src/components/PressableWithSecondaryInteraction/index.tsx#L86

More info: https://stackoverflow.com/a/71979616.

### What changes do you think we should make in order to solve the problem?
Call `onSecondaryInteraction()` in `mousedown` event handler.

```TSX
const executeSecondaryInteractionOnMouseDown = (event: MouseEvent) => {
    if (!onSecondaryInteraction || event.button !== 2) {
        return;
    }

    onSecondaryInteraction(event);

    if (withoutFocusOnSecondaryInteraction) {
        element.blur();
    }
};

const preventDefaultOnContextMenu = (event: MouseEvent) => {
    if (!onSecondaryInteraction) {
        return;
    }

    event.stopPropagation();
    if (preventDefaultContextMenu) {
        event.preventDefault();
    }
};
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
Consider adding more manual testing effort on desktop Safari if it’s worth it.

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2024-12-09 19:36
This is not a bug. If you click on a single word to copy, it's only going to copy that single word. If you want the entire sentence to be copied, you need to highlight the entire sentence and then copy. 

This is working by design, so closing.

**Closed by CortneyOfstad** 2024-12-09 19:36 UTC
Labels: Daily, Overdue, Bug

**Comment by QichenZhu** [comment] 2024-12-10 08:50
@CortneyOfstad I think the problem is the mismatch between visual cues and the actual result. For example, in Slack and Discord, when right-clicking a word, it’s highlighted with a blue background, so the user expects the word to be copied.

<img width="919" alt="Slack" src="https://github.com/user-attachments/assets/f793ed23-0f08-4715-b571-19434b533d9d">

<img width="919" alt="Discord" src="https://github.com/user-attachments/assets/7ef87e4e-ae47-4e38-9c1c-992026a99099">

<p></p>

In our app, however, right-clicking a word highlights the entire message with a grey background, so the user expects the entire message to be copied.

<img width="905" alt="Expensify" src="https://github.com/user-attachments/assets/65a55983-788d-44b6-a4ed-f17ab1ebfcd7">

<p></p>

There's also inconsistency between platforms: in Safari, only the word is copied, while in Chrome and native apps, the entire message is copied.
