### ISSUE TITLE
[HOLD 33725][$500]  Web - Chat - Two Messages can not be selected when they are divided by reply

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35946] opened 2024-02-06 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Add a reply to the message
5. Send another message
6. With mouse select last message and continue to select first message with reply

## Expected Result:
Messages should be selected in a consistent manner where there is no 'jumping' or 'flashing' of the highlighted area. The highlighted area shouldn't be disrupted by 'reply to threads' in the chat. 

## Actual Result:
The highlighted area is no consistently selected when you drag the curser over it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eb044560-264f-4cdf-8a54-5c5504f0b6e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135be761efeca8eb4</li>
        <li>Upwork Job ID: 1754943044230656000</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-06 19:00
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Christinadobrzyn** [comment] 2024-02-06 20:38
I can reproduce this but I'm not sure if this is expected... going to reach out to the team to see what they think.

**Comment by Christinadobrzyn** [comment] 2024-02-08 21:54
I think we can broaden the scope of this OP to allow for users to highlight an entire chat thread regardless of breaks in the chat - asking the team for a review - https://expensify.slack.com/archives/C066HJM2CAZ/p1707429247200849

**Comment by mananjadhav** [comment] 2024-02-12 13:01
@Christinadobrzyn Any updates on the discussion? I can't access the slack thread.

**Comment by Christinadobrzyn** [comment] 2024-02-12 23:16
no response from the team yet, I'll keep monitoring our decision

**Comment by Christinadobrzyn** [comment] 2024-02-13 23:58
Gonna try the BZ room to see if I can get an answer - https://expensify.slack.com/archives/C01SKUP7QR0/p1707868596042429

Also asking QA if they know what is expected here - https://expensify.slack.com/archives/C9YU7BX5M/p1707868718740389

**Comment by Christinadobrzyn** [comment] 2024-02-14 16:24
Talking this over with QA @isagoico we both agree this should be fixed to mimic the highlight abilities of Slack or GH 

Expected behaviour: 

You should be able to highlight an entire 'area' of a chat without it glitching or being disrupted by a 'reply to chat thread'. 

So the behaviour should be more like this: 

https://github.com/Expensify/App/assets/51066321/f0019e3d-1a7c-4c74-8329-a54c1c48d647

instead of how it is now where the highlighted area 'jumps' around and isn't consistent. 


https://github.com/Expensify/App/assets/51066321/eb220076-40ba-4c17-94a0-f5440499c624


Let me know your thoughts @Santhosh-Sellavel!

**Comment by mananjadhav** [comment] 2024-02-19 18:52
Okay I get what you mean @Christinadobrzyn. This is now open for proposals.

**Comment by brandonhenry** [comment] 2024-02-20 06:33
### Proposal

#### Problem Statement
The issue at hand is that text selection within the chat messages is being reset when trying to copy the text of an entire chat thread

#### Root Cause
The root cause of this problem is the extensive use of inline styles throughout the project. Inline styles lead to new objects being created on each render, which in turn causes React components to re-render more frequently than necessary. This frequent re-rendering resets the text selection, as the DOM elements are being replaced.

#### Proposed Solution
To address this issue, we should refactor the codebase to minimize the use of inline styles. Instead, we should adopt a more static approach to styling, such as using CSS classes or styled-components. This will reduce the frequency of re-renders and help preserve text selection. The specific steps would include:

1. Identify components with inline styles that are causing frequent re-renders.
2. Refactor these components to use CSS classes or styled-components.

#### Alternatives Considered
- **Debouncing Re-renders:** Implementing a debounce mechanism to limit the frequency of re-renders. However, this might not address the root cause and could introduce complexity.
- **Using React.memo:** Wrapping components with React.memo to prevent unnecessary re-renders. This could be a partial solution but might not fully solve the problem if the inline styles are still causing new objects to be created.

#### Effort and Cost Estimation
The effort required for this solution involves a thorough review of the codebase and refactoring of multiple components. It is a medium to large effort, I'd say this either be de-prioritized or done internally. I'm happy to accept but only for a higher amount but this ticket itself has some pretty heavy implications just based on how the codebase is structured

**Comment by Christinadobrzyn** [comment] 2024-02-20 15:17
Thanks @mananjadhav! We're accepting and reviewing proprosals

**Comment by Victor-Nyagudi** [comment] 2024-02-21 15:28
This one's tricky. 

First, the text with the reply count in between messages is not meant to be selected or copied because of these lines. Both have `styles.userSelectNone`.

https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/pages/home/report/ReportActionItemThread.tsx#L61-L64

https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/pages/home/report/ReportActionItemThread.tsx#L67-L71

The `dataSet` value is used to remove them from the clipboard content in `SelectionScraper`.

https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/libs/SelectionScraper/index.ts#L91-L97

This pattern has been used in multiple places in the code base e.g. https://github.com/Expensify/App/issues/26694.

Secondly, if you inspect the HTML, you'll notice that the `div`s housing the different messages are arranged in reverse i.e. message 2 `div` is below message 1, but the messages rendered on the page are in the correct order. 

After tinkering a bit on codepen, I found that even if there's a `div` or `button` in between that shouldn't be selected, you should still be able to select everything else just fine. 

All that being said, I believe the order in which the messages are rendered or the HTML produced could be interfering with the selection behavior - unless maybe this worked at some point and is now broken.

I thought about changing the message order or playing around with how the HTML is generated, but I felt like this could have some unintended side effects. 

Either way, I'm letting this one go, so hopefully this provides some context to the next person who decides to take a crack at it.

**Comment by Christinadobrzyn** [comment] 2024-02-21 20:10
hi @mananjadhav could you take a peek at the proposals we have so far? Thanks!

**Comment by quinthar** [comment] 2024-02-25 09:06
I'm curious if the new comment-linking code changes the order of <divs> to be correct? /cc @Szymon20000  I think right now the <divs> are in the opposite order they are displayed, and we're using some kind of hack on flat list to show it opposite?

**Comment by perunt** [comment] 2024-02-25 14:28
We made a change some time ago and have been using this setup in production ever since. Now, it renders as truly inverted, meaning without any stylistic tricks

**Comment by Christinadobrzyn** [comment] 2024-02-28 01:18
Thanks @mananjadhav do you think we should raise the bounty here?

**Comment by nagypite** [comment] 2024-02-29 11:44
The problem clearly seems to be coming from the inverted rendering order, see recording below:

![Screenshot at: 2024-02-29 12-33-23](https://github.com/Expensify/App/assets/661868/3ede39a6-6545-45b1-81d1-0b8f02830ece)
[Screencast at: 2024-02-29 12-28-23.webm](https://github.com/Expensify/App/assets/661868/9b33791f-5d60-45f5-9c66-f6b15eee9696)

First it shows on the left side the current staging selection behavior, then a modified dev version without the inversion, selection working as expected. The latter one was achieved by removing a single line:

```diff
diff --git a/src/components/InvertedFlatList/BaseInvertedFlatList.tsx b/src/components/InvertedFlatList/BaseInvertedFlatList.tsx
index e284005052..29f090d46f 100644
--- a/src/components/InvertedFlatList/BaseInvertedFlatList.tsx
+++ b/src/components/InvertedFlatList/BaseInvertedFlatList.tsx
@@ -10,18 +10,17 @@ function BaseInvertedFlatList<T>(props: FlatListProps<T>, ref: ForwardedRef<Flat
     return (
         <FlatList
             // eslint-disable-next-line react/jsx-props-no-spreading
             {...props}
             ref={ref}
             windowSize={WINDOW_SIZE}
             maintainVisibleContentPosition={{
                 minIndexForVisible: 0,
                 autoscrollToTopThreshold: AUTOSCROLL_TO_TOP_THRESHOLD,
             }}
-            inverted
         />
     );
 }
 
 BaseInvertedFlatList.displayName = 'BaseInvertedFlatList';
 
 export default forwardRef(BaseInvertedFlatList);
```

@perunt Could you give some context about the decision around the inverted rendering?

> We made a change some time ago and have been using this setup in production ever since. Now, it renders as truly inverted, meaning without any stylistic tricks

Should I look into changing the rendering order, or is this something that shouldn't be meddled with?

**Comment by mananjadhav** [comment] 2024-02-29 13:58
I checked this [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1709207067557479) for some additional feedback. Afaik, we shouldn't be changing the `inverted` flag and look at styling workarounds.

Tagging @roryabraham here for their feedback too.

**Comment by s77rt** [comment] 2024-03-03 00:21
We already dealt with this bug here https://github.com/Expensify/App/issues/1341. The bug is in RNW and we have an upstream PR https://github.com/necolas/react-native-web/pull/2151 however that PR is closed in favor of a react-native fix https://github.com/facebook/react-native/issues/30383. Yet we applied the fix here https://github.com/Expensify/react-native-web/pull/2 and here https://github.com/Expensify/react-native-web/pull/3 but that change is no longer in place as I think we switched back to the upstream RNW repo here https://github.com/Expensify/react-native-web/pull/6 and left behind the patch.

I think our options are:
1. Reapply the patch (assuming we actually forgot it and it was not removed intentionally cc @roryabraham)
2. Hold on https://github.com/facebook/react-native/issues/30383

**Comment by Christinadobrzyn** [comment] 2024-03-04 21:32
Thanks @s77rt let me know if I can help with making those decisions - @mananjadhav what do you think would be best?

**Comment by Christinadobrzyn** [comment] 2024-03-07 05:17
Just checking in on an update @s77rt and @mananjadhav - thanks!

**Comment by mananjadhav** [comment] 2024-03-10 18:50
@roryabraham Could you please confirm if we intentionally did not add the patch?

I don't think the upstream issue is going to be worked upon anytime soon.

**Comment by Christinadobrzyn** [comment] 2024-03-13 03:53
DMd @roryabraham re https://github.com/Expensify/App/issues/35946#issuecomment-1987329556

**Comment by Christinadobrzyn** [comment] 2024-03-19 07:30
Ah thanks for the context @brandonhenry! 

Do I have it right that we should HOLD this for https://github.com/Expensify/App/issues/33725

Does that sound like a plan @mananjadhav and @puneetlath?

**Comment by mananjadhav** [comment] 2024-03-20 14:37
Yeah I think it makes sense to wait. Not sure why @mallenexpensify is tagged. But yeah we can hold.

**Comment by Christinadobrzyn** [comment] 2024-03-25 08:40
HOLD for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-04-04 08:16
Just checking in here, @mananjadhav can you provide an update? I'm a little lost where we are here.

**Comment by Christinadobrzyn** [comment] 2024-04-16 06:33
this is on hold for - https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-04-26 07:42
This is still on hold for - https://github.com/Expensify/App/issues/33725 

I do think this still needs to be fixed

**Comment by Christinadobrzyn** [comment] 2024-05-03 10:18
This is still on hold for - https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-05-14 09:03
@mananjadhav do you think we're still on hold for https://github.com/Expensify/App/issues/33725?

I just retested and this is still happening

**Comment by mananjadhav** [comment] 2024-05-16 19:37
Yes . We're still held on the linked issue.

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:50
On hold for - https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-05-28 08:05
On hold for - https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:41
Hey @mananjadhav does this still need to be on hold for https://github.com/Expensify/App/issues/33725?

**Comment by Christinadobrzyn** [comment] 2024-06-20 19:33
on hold for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-06-24 23:34
on hold for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-07-02 21:27
on hold for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-08-05 22:45
on hold for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-10-08 07:17
still on hold for https://github.com/Expensify/App/issues/33725

**Comment by Christinadobrzyn** [comment] 2024-11-12 01:28
still on hold for https://github.com/Expensify/App/issues/33725

**Comment by garrettmknight** [comment] 2024-11-12 10:28
I'm going to close this for now - If we get a customer reporting, we can reopen.

**Closed by garrettmknight** 2024-11-12 10:28 UTC
Labels: Engineering, Monthly, Internal, Bug, Hot Pick
