### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Request money - Missing Tooltip for "Cancel" Icon Linked to "Request money, get $250"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35507] opened 2024-01-31 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Navigate to FAB (Floating Action Button) > Request Money > Add Amount
2, At the bottom, observe that the "Cancel" icon associated with "Request money, get $250" lacks a tooltip

## Expected Result:
The "Cancel" icon associated with "Request money, get $250" should have a tooltip, similar to the Cancel Icon displayed when editing text in conversations

## Actual Result:
The "Cancel" icon associated with "Request money, get $250" does not have a tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c0280e78-22ac-477b-bcc3-2b27e40d7f04

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fe88086e3f5b2fc</li>
        <li>Upwork Job ID: 1752773353838592000</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-31 19:19
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by DylanDylann** [comment] 2024-01-31 19:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Cancel" icon associated with "Request money, get $250" does not have a tooltip

### What is the root cause of that problem?
We don't wrap Cancel button by Tooltip component
### What changes do you think we should make in order to solve the problem?
Should add Tootltip component
```
<Tooltip text={translate('common.close')}>
                               .....
</Tooltip>

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by dragnoir** [comment] 2024-01-31 19:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Missing tooltip for cancel icon

### What is the root cause of that problem?

No tooltip component arount the icon on src/components/ReferralProgramCTA.tsx

### What changes do you think we should make in order to solve the problem?

Add Tooltip around `PressableWithoutFeedback` on src/components/ReferralProgramCTA.tsx line 47

**Comment by Tony-MK** [comment] 2024-01-31 19:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request money - Missing Tooltip for "Cancel" Icon Linked to "Request money, get $250

### What is the root cause of that problem?

We don't have a parent tooltip component on the icon component.

https://github.com/Expensify/App/blob/dev/33976/src/components/ReferralProgramCTA.tsx#L56

### What changes do you think we should make in order to solve the problem?


Wrap the `Icon` component with the `Tooltip` and insert the text prop.

```
 <Tooltip text={translate('videoChatButtonAndMenu.tooltip')}>
...
</>
```

Just like [`BaseVideoChatButtonAndMenu`](https://github.com/Expensify/App/blob/main/src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.tsx#L85-L86) component.

**Comment by JmillsExpensify** [comment] 2024-02-01 20:14
@mollfpr Is paid via NewDot, so no Upwork offer is necessary. Offer sent to @DylanDylann.

**Comment by DylanDylann** [comment] 2024-02-02 11:08
@mollfpr PR https://github.com/Expensify/App/pull/35646 is ready to review

**Comment by JmillsExpensify** [comment] 2024-02-14 16:36
Contributor has been paid out! @mollfpr Please complete the BZ checklist before requesting in Expensify. I'm going to close the issue in the meantime, though I'll circle back when I receive your request.

**Closed by JmillsExpensify** 2024-02-14 16:36 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by mollfpr** [comment] 2024-02-15 13:41
> [@mollfpr / @DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr / @DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I can't trace it back to the previous commit, probably the issue because we forgot to add a tooltip for the icon button.

> [@mollfpr / @DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1708004231670919

>[@mollfpr / @DylanDylann] Determine if we should create a regression test for this bug.
 [@mollfpr / @DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I think we don't need a specific regression test for this specific icon button. If we have guidance on how to handle creation an icon button.

**Comment by trjExpensify** [comment] 2024-02-29 23:09
Confirming the payment summary here is correct: https://github.com/Expensify/App/issues/35507#issuecomment-1944014331

$500 to @mollfpr for the C+ review. 
$500 to @DylanDylann for the fix.
