### ISSUE TITLE
CRITICAL [SNH]: Login information is revealed when typing

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#21024] opened 2023-06-19 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat between to users, with both users in two different devices (Ex: 1 tab in Chrome, 1 in Incognito)
2. Type in the chat with one user

## Expected Result:
In the other user's device, you should see the first user's displayName in the "is typing" indicator

## Actual Result:
In the other user's device, notice that you see the first user's email address in the "is typing" indicator

## Workaround:
No workaround, but yes everything works as normal

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** Main - latest & staging
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/3885503/e3b1aad2-8297-4da6-87a8-e14bff15328f

**Issue reported by:**
**Slack conversation:** (internal link: https://expensify.slack.com/archives/C04QEB4MJEQ/p1686962571877449)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-06-19 10:46
Seems dupe of https://github.com/Expensify/App/issues/20956

**Comment by Beamanator** [comment] 2023-06-19 11:10
Ooh yep good call @Pujan92 👍

**Closed** 2023-06-19 11:14 UTC
Labels: Daily, Bug
