### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] [HOLD for payment 2023-08-16] The total requested amount does not update until the IOU is clicked on or the page is refreshed

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24267] opened 2023-08-08 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "request money."
2. Enter the desired amount and recipient's email address, and click "request money."
3. Repeat step 2 to make a second request with the same recipient.
4. Delete the first request from the reply thread.
5. Observe that the total requested amount does not update in real-time.

## Expected Result:
The total requested amount should update in real-time after deleting the first request and making a second one.

## Actual Result:
The total requested amount does not update until the IOU is clicked on or the page is refreshed.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.51-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation  

https://github.com/Expensify/App/assets/43995119/f83caa21-89b3-45e0-9c1f-7aeb9f18e83f

https://github.com/Expensify/App/assets/43995119/de2896a0-3b40-477c-9d37-3b8ce4a8a3ed

**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691494603760399 
reported earlier in 
Issue reported by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1691444951222519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136af4481ecaa59a7</li>
        <li>Upwork Job ID: 1689346748730482688</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 26035056</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-08 14:49
Dupe of https://github.com/Expensify/App/issues/24241

**Comment by mvtglobally** [comment] 2023-08-08 15:27
its not repro in PROD, not sure how it was on the previous builds. we will update first reported accordingly. 
@isabelastisser  @srikarparsi pls double check if anything would've re-intro this issue or we can just close it

**Comment by srikarparsi** [comment] 2023-08-08 16:41
Hey @dukenv0307, your proposal looks good to me and tests well. Will you be able to get a PR out in the next 30-45 minutes or so?

**Comment by StevenKKC** [comment] 2023-08-08 16:43
@srikarparsi This issue is dupe of https://github.com/Expensify/App/issues/24241 and I have already posted my proposal in https://github.com/Expensify/App/issues/24241#issuecomment-1668968935

**Comment by srikarparsi** [comment] 2023-08-08 16:45
Sorry about that, didn't see your proposal there. @StevenKKC, can you please create a PR in that case as soon as possible?

**Comment by srikarparsi** [comment] 2023-08-08 16:45
@dukenv0307, sorry for jumping the gun and asking you to work on this. Since @StevenKKC posted his proposal before yours, I think it makes sense to let @StevenKKC take over this PR.

**Comment by StevenKKC** [comment] 2023-08-08 16:45
@srikarparsi Yes, no problem.

**Comment by srikarparsi** [comment] 2023-08-08 17:08
@StevenKKC please assign me to review once you have the PR ready. Will you be able to have it out in the 30 minutes to 1 hour? Since this is a deploy blocker, we tend to move a little faster on these.

**Comment by StevenKKC** [comment] 2023-08-09 14:47
@srikarparsi @isabelastisser Can someone please assign this issue to me?

**Comment by tewodrosGirmaA** [comment] 2023-08-09 16:34
@StevenKKC I would like to clarify that I was the original reporter of this bug and I have also reported three other bug reports that have the same root cause as this one. However, I noticed that my name was changed to another reporter in this report. I would appreciate it if my name is restored as the original reporter.

For reference, I reported this bug 5 days ago (1, https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989, 2, https://expensify.slack.com/archives/C049HHMV9SM/p1691166781356339) while someone else reported it 4 days ago (https://expensify.slack.com/archives/C049HHMV9SM/p1691235556837429). I believe it is important to credit the correct person for reporting a bug.

Thank you for your attention to this matter.

**Comment by srikarparsi** [comment] 2023-08-09 18:45
@StevenKKC, can you please fill out this checklist when you have a chance: https://github.com/Expensify/App/issues/24267#issuecomment-1670904865

**Comment by tewodrosGirmaA** [comment] 2023-08-09 18:49
> @StevenKKC, can you please fill out this checklist when you have a chance: https://github.com/Expensify/App/issues/24267#issuecomment-1670904865

I was the original reporter of this bug and I have also reported three other bug reports that have the same root cause as this one. However, I noticed that my name was changed to another reporter in this report. I would appreciate it if my name is restored as the original reporter.

For reference, I reported this bug 5 days ago (1, https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989, 2, https://expensify.slack.com/archives/C049HHMV9SM/p1691166781356339) while someone else reported it 4 days ago (https://expensify.slack.com/archives/C049HHMV9SM/p1691235556837429). I believe it is important to credit the correct person for reporting a bug

**Comment by srikarparsi** [comment] 2023-08-09 18:57
Hey @tewodrosGirmaA, definitely, I didn't respond to your first [comment](https://github.com/Expensify/App/issues/24267#issuecomment-1671765087) as I haven't taken a look into it yet but I'll reply here once I look into it.

**Comment by tewodrosGirmaA** [comment] 2023-08-09 18:59
> Hey @tewodrosGirmaA, definitely, I didn't respond to your first [comment](https://github.com/Expensify/App/issues/24267#issuecomment-1671765087) as I haven't taken a look into it yet but I'll reply here once I do.

Thank you

**Comment by tewodrosGirmaA** [comment] 2023-08-10 08:13
I am confident that the following aspects share a common origin: the **total amount**, **request count**, **currency with the amount when we Change the language to Spanish**, and the fact that the **reply thread** is not updated in real-time. Please verify this information.

**Comment by tewodrosGirmaA** [comment] 2023-08-10 08:35
My point is that, for example, when we encountered the 'Reply Thread' bug that I reported in this thread: Link to the thread (https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989), the reply thread was not updating in real-time. As a result, the requested money was not being deleted, and the total amount was not being calculated correctly. This issue had a common underlying cause. However, I'm pleased to report that it now works perfectly fine during my recent testing

**Comment by srikarparsi** [comment] 2023-08-10 17:23
Hi @tewodrosGirmaA. Just to clarify, you are saying that you reported these two issues.

1. [After deleting a reply and going back, two replies temporarily appear on the request](https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989)
2. [The currency doesn't update for the IOU when you change the language from english to spanish](https://expensify.slack.com/archives/C049HHMV9SM/p1691166781356339)

And that is similar to the issue reported by @namhihi237?
[Total amount doesn't update when an IOU request is deleted](https://expensify.slack.com/archives/C049HHMV9SM/p1691235556837429)

I read through the reproducible steps for both of your issues and they do seem like valid issues but they are different from this issue @namhihi237 reported. I believe you could still get compensated if GH issues are created from your posts and they are fixed.

**Comment by tewodrosGirmaA** [comment] 2023-08-10 17:28
> Hi @tewodrosGirmaA. Just to clarify, you are saying that you reported these two issues.
> 
> 1. [After deleting a request and going back, two replies temporarily appear on the parent request](https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989)
> 2. [The currency doesn't update for the IOU when you change the language from english to spanish](https://expensify.slack.com/archives/C049HHMV9SM/p1691166781356339)
> 
> And that is similar to the issue reported by @namhihi237?
> [Total amount doesn't update when an IOU request is deleted](https://expensify.slack.com/archives/C049HHMV9SM/p1691235556837429)
> 
> I read through the reproducible steps for both of your issues and they do seem like valid issues but they are different from this issue @namhihi237 reported. I believe you could still get compensated if GH issues are created from your posts and they are fixed.

OK, thank you

**Comment by tewodrosGirmaA** [comment] 2023-08-13 04:26
Hey @srikarparsi, could you please update my name? I discovered that my issue has been identified as a duplicate in Slack. You can find more details about this issue in the following Slack conversation: Slack Conversation Link (https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989)

**Comment by StevenKKC** [comment] 2023-08-15 06:15
* [X]  The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20841
* [X]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20841/files#r1294230314
* [X]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
* [X]  Determine if we should create a regression test for this bug.
* [X]  If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Open a chat with a user have chatted together before
2. Click + in compose and create 2 requests money
3. Click request money view
4. Delete one of requests
5. Verify that total amount is updated after being deleted

**Comment by tewodrosGirmaA** [comment] 2023-08-15 16:42
Hey @srikarparsi, could you please update my name? I discovered that my issue has been identified as a duplicate in Slack. You can find more details about this issue in the following Slack conversation: Slack Conversation Link (https://expensify.slack.com/archives/C049HHMV9SM/p1691168685718989)

**Comment by StevenKKC** [comment] 2023-08-16 06:12
@jasperhuangg I apologize for my mistake and thank you for pointing it out.

**Comment by isabelastisser** [comment] 2023-08-18 20:23
@srikarparsi @StevenKKC, can you please confirm my summary below is correct? Do you know if the urgency bonus applies to this issue? Thanks!

Issue reported by: @namhihi237 $250
Approved proposal: @StevenKKC $1000, $500 urgency bonus

**Comment by StevenKKC** [comment] 2023-08-22 06:53
@srikarparsi Can you please confirm the urgency bonus applies to this issue?

**Comment by srikarparsi** [comment] 2023-08-23 16:27
Hi @isabelastisser! Yes, the [summary](https://github.com/Expensify/App/issues/24267#issuecomment-1684399573) looks correct! @StevenKKC should receive the urgency bonus.

**Comment by isabelastisser** [comment] 2023-08-23 19:42
Thanks @srikarparsi!

@namhihi237 and @StevenKKC ! The payments should be set in Upwork, please review your accounts. Thanks!

> [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
]
(https://github.com/Expensify/Expensify/issues/310599)

**Closed by isabelastisser** 2023-08-23 19:42 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
