### ISSUE TITLE
[$1000] Rate Unit Not Changing in Reimbursement Section for New Workspace (Offline)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22506] opened 2023-07-09 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences and enable "Force Offline".
2. Navigate to Settings > Existing Workspace > Reimbursements and observe that successfully change the unit.
3. Go back and access Create Workspace > Reimbursements.
4. Change the unit, save the changes, and observe that the unit is not saved like the existing workspace.
## Expected Result: 
The unit of Rate should change according to user preference in the Reimbursement section for the new workspace, even while offline like the existing workspace.
## Actual Result: 
Unit of Rate does not change according to user preference in the Reimbursement section for new workspace, even while offline like existing workspace.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7b25ee0d-8fb9-48dd-84a7-e253e9efaa43

https://github.com/Expensify/App/assets/43996225/710c078b-2d14-4dd9-8f2e-55e18ca24639

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688827215546309
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a93a76d96d74494</li>
        <li>Upwork Job ID: 1679101262575960064</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-07-12 12:11
I was able to successfully reproduce this one. The mileage rate didn't successfully change, at least in the front-end. Triaging to the community.

**Comment by s77rt** [comment] 2023-07-12 18:51
@namhihi237 Thanks for the proposal. Your RCA makes sense and so the solution. But I'm afraid we won't be able to predict such data as the `customUnits` seems to be identified by a random id that is coming from the backend.

**Comment by s77rt** [comment] 2023-07-12 19:05
Asking on Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1689188606465439

**Comment by JmillsExpensify** [comment] 2023-07-12 22:38
Dupe of https://github.com/Expensify/App/issues/17198. Closing

**Closed by JmillsExpensify** 2023-07-12 22:38 UTC
Labels: External, Daily, Help Wanted, Bug
