### ISSUE TITLE
[Hold for #27392] [$500] mWeb-Profile-Asia/Calcutta is displayed as Asia/Kolkata & selected timezone not shown with tick mark

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27927] opened 2023-09-21 09:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: change device time zone to India
1. Go to https://staging.new.expensify.com/

2. Tap profile icon
3. Tap profile
4. Tap timezone
5. Toggle on "automatically determine your location" and note Asia/Calcutta is displayed
6. Toggle off "automatically determine your location"
7. Tap Asia/Calcutta to note selected option not shown with tick mark on top
8. Enter Asia
9. Scroll down to find Asia/Calcutta, then Asia/Kolkata

## Expected Result:
When user taps Asia/Calcutta, the option Asia/Calcutta with tick mark should be displayed inside on top. Both automatically determine location and time zone options must show same spelling and not Calcutta/Kolkata and tapping on it, inside the same timezone option must be displayed with tick mark on top.

## Actual Result:
When user taps Asia/Calcutta, the option Asia/Calcutta with tick mark is not found on top. When user enters Asia in search and scroll down, the option Asia/Calcutta with tick mark not found, but shown Asia/Kolkata , and that also without tick mark.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f8197a9b-c7be-4a6c-b308-7081f23501a8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2fd5178e62c26f5</li>
        <li>Upwork Job ID: 1704963311276171264</li>
        <li>Last Price Increase: 2023-09-28</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27049168</li>
<li>tienifr | Contributor | 27049171</li>
</ul></li>
    </ul>
</details>

**Comment by pranabs1ngh** [comment] 2023-09-21 21:49
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

When user taps Asia/Calcutta, the option Asia/Calcutta with tick mark is not found on top. When user enters Asia in search and scroll down, the option Asia/Calcutta with tick mark not found, but shown Asia/Kolkata , and that also without tick mark

## What is the root cause of that problem?

`Asia/Calcutta` option is missing from timezones list in TIMEZONES.js file.

## What changes do you think we should make in order to solve the problem?

Simply adding this option into the list fixes the issue. When timezone option is selected, after adding this item in the list, it comes preselected with a tickmark which is the expected result of this issue.

**Comment by NicMendonca** [comment] 2023-09-27 14:04
> let's wait and see how to standardize the timezone data 

@ntdiary is this being worked on elsewhere?

**Comment by NicMendonca** [comment] 2023-10-02 20:26
@ntdiary proposals for you here!

**Comment by NicMendonca** [comment] 2023-10-05 20:50
@hayata-suenaga this is waiting on your review: https://github.com/Expensify/App/issues/27927#issuecomment-1744740894

**Comment by hayata-suenaga** [comment] 2023-10-06 01:34
sorry for the delay in assignment

**Comment by hayata-suenaga** [comment] 2023-10-10 01:43
the draft PR is up ⬆️

**Comment by hayata-suenaga** [comment] 2023-11-06 21:11
@tienifr could you check if the issue was fixed by the other PR?

**Comment by situchan** [comment] 2023-11-06 21:30
That PR was reverted due to crash on macOS Sonoma

**Comment by hayata-suenaga** [comment] 2023-11-06 23:58
Then should we proceed with the proposed solution?

**Comment by situchan** [comment] 2023-11-07 05:22
Actually, I think we can close as https://github.com/Expensify/App/issues/27392 should cover this issue as well.

**Closed** 2024-01-03 17:24 UTC
Labels: Reviewing, External, Monthly, Bug
