### ISSUE TITLE
[Hold #15212][$1000] Web - New marker does not go away when Report is automatically marked as read

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21875] opened 2023-06-29 13:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat with history;
2. Mark any message as unread;
3. Refresh the page OR switch the tab and come back;
4. On left, see that the report has been marked as read, but the New marker is still visible;
5. Repeat Step 3;
6. See that the New marker did go away the second time.

## Expected Result:
The New marker should go away the first time.

## Actual Result:
 The New marker goes away the second time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4fd24e09-8500-4515-89ac-2881f31531d0

https://github.com/Expensify/App/assets/93399543/5f419250-bc6c-4867-9652-70b8644de3a2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DanutGavrus
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687948133361189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107af640eb3758e2b</li>
        <li>Upwork Job ID: 1675894728590426112</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-29 13:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New marker does not go away when Report is automatically marked as read
### What is the root cause of that problem?
1. In `ReportActionsView.js`, if we switch the chrome tab and come back, or refresh the current tab, the `report's lastReadTime` updates to a new value;
2. In `ReportUtils.js`, the method `isUnread` does `return lastReadTime < lastVisibleActionCreated`, so it would retun false;
3. But, in `ReportActionsView.js` inside `componentDidUpdate`, we do not check if the report automatically became `read` in order to clear `this.state.newMarkerReportActionID`.
### What changes do you think we should make in order to solve the problem?
We should add this logic:
```js
if (!ReportUtils.isUnread(this.props.report) && this.state.newMarkerReportActionID != '') {
    this.setState({
        newMarkerReportActionID: '',
    });
}
```
inside `componentDidUpdate` in `ReportActionsView.js`.

**Comment by mollfpr** [comment] 2023-06-29 16:13
@sonialiap please hold triaging this. I will try investigating this, maybe can be solved by https://github.com/Expensify/App/pull/21557.

**Comment by mollfpr** [comment] 2023-06-30 18:03
@sonialiap It's okay now to triage this. We have different root causes for the issue in the PR above. Thank you!

**Comment by hwakstar** [comment] 2023-07-03 16:07
Hello
I checked your job description and I am sure that can solve it.
I hope that work with you.
Warm regards

**Comment by DanutGavrus** [comment] 2023-07-03 16:26
@fedirjh Should we ask on Slack about holding this one for [15212](https://github.com/Expensify/App/issues/15212)?  

I'm asking as [20759](https://github.com/Expensify/App/issues/20759) was recently completed instead of also being held and seems related.

Thanks!

**Comment by coeur85** [comment] 2023-07-03 18:42
Contributor details
Your Expensify account email: ahmed.coeur@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/magdi

**Comment by DanutGavrus** [comment] 2023-07-04 07:41
> There is an tracker issue for all unread marker issue, and all related issues, should be added to it. It doesn’t make sense to proceed with solution while we are working on a refactor.

Ok, I understand!

**Comment by hwakstar** [comment] 2023-07-04 08:24
Contributor details
Your Expensify account email: [anastasiiamaksymovaa@gmail.com](mailto:anastasiiamaksymovaa@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0184d3368b71c2b81c

**Comment by hwakstar** [comment] 2023-07-04 08:27
Contributor details
Your Expensify account email: [[anastasiiamaksymovaa@gmail.com](mailto:anastasiiamaksymovaa@gmail.com)]
Upwork Profile Link: https://www.upwork.com/freelancers/~0184d3368b71c2b81c

**Comment by sonialiap** [comment] 2023-07-06 21:40
Updated to Hold

**Comment by sonialiap** [comment] 2023-07-14 12:03
still on hold

**Comment by sonialiap** [comment] 2023-07-17 13:54
On hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-07-20 10:23
Still on hold but https://github.com/Expensify/App/issues/15212 is progressing 🎉 so hopefully soon

**Comment by sonialiap** [comment] 2023-07-24 15:02
Changing to weekly since a design doc is involved

Still on hold but https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-08-11 13:34
Still on hold

**Comment by sonialiap** [comment] 2023-08-29 18:02
Still hold

**Comment by sonialiap** [comment] 2023-09-12 04:33
Still hold

**Comment by sonialiap** [comment] 2023-09-20 10:26
still on hold

**Comment by sonialiap** [comment] 2023-10-02 04:44
On hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-23 10:37
On hold for https://github.com/Expensify/App/issues/15212

**Comment by sonialiap** [comment] 2023-10-31 21:17
PR for https://github.com/Expensify/App/issues/15212 is super close to being approved and merged, exciting! Hopefully soon we'll be able to re-test this one and either close or look for proposals

**Comment by sonialiap** [comment] 2023-11-10 17:24
PR for https://github.com/Expensify/App/issues/15212 is close but not yet merged. Waiting

**Comment by sonialiap** [comment] 2023-11-20 15:09
Waiting for https://github.com/Expensify/App/pull/25935 to test this again

**Comment by MonilBhavsar** [comment] 2023-11-21 17:22
> Expected Result: The New marker should go away the first time.

When marking the message as unread manually, the new marker should go second time.

That said, this issue should be fixed. We can retest and most probably close it

**Comment by sonialiap** [comment] 2023-12-04 13:16
@MonilBhavsar bumping [Fedi's question](https://github.com/Expensify/App/issues/21875#issuecomment-1821391543), do you know the answer?

**Comment by sonialiap** [comment] 2023-12-14 11:15
@fedirjh sounds like we still have an issue here and need proposals, is that correct?

**Comment by MonilBhavsar** [comment] 2023-12-15 05:30
As per the design, we should not remove marker when user switches the tab. For the refresh I think it is fine as the components are remounted.

**Closed** 2024-01-08 16:17 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
