### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Dev: Web - Delete task message text color change in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27804] opened 2023-09-19 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select assign task
3. Enter title and create task
4. Go to task thread and delete the task
5. Go to parent report screen
6. Go offline

## Expected Result:
Delete task message text color should not change

## Actual Result:
Delete task message text color changes to gray

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba3ad250-d785-4016-ae39-8fbdad154e9e

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695104920660599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b184e9e64be3573</li>
        <li>Upwork Job ID: 1704196739021500416</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26887595</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-21 15:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Delete task message text color change in offline mode

### What is the root cause of that problem?
We are setting pendingAction for parentReportAction
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/libs/actions/Task.js#L816

But we don't re-set pendingAction to null in successData and failureData
### What changes do you think we should make in order to solve the problem?
1. In SuccessData, update pendingAction to null for parent reportAction
2. In FailureData, update pendingAction to null for parent reportAction

**Comment by robertKozik** [comment] 2023-09-25 11:14
Thank you both for your proposals @ZhenjaHorbach @dukenv0307 . I think the proper root cause was introduced by @dukenv0307 and solution tackles the cause directly. That's why I think we should proceed with @dukenv0307 [proposal](https://github.com/Expensify/App/issues/27804#issuecomment-1726829241)

🎀 👀 🎀 C+ reviewed

**Comment by johncschuster** [comment] 2023-09-26 15:47
Thanks, @robertKozik! I'll assign the issue to @dukenv0307.

**Comment by johncschuster** [comment] 2023-10-12 20:57
Payment has been issued to @dukenv0307 via Upwork

**Comment by johncschuster** [comment] 2023-10-12 20:57
@chiragsalian / @robertKozik is this issue supposed to have a BZ Checklist? I'm not sure how to generate that.

**Comment by chiragsalian** [comment] 2023-10-16 20:55
> And after that, we wait for the final review from @chiragsalian

Sorry, is there something pending from me? I see this [PR](https://github.com/Expensify/App/pull/28211) was merged 2 weeks ago. If there is something still pending for me let me know.

**Comment by johncschuster** [comment] 2023-10-19 20:37
I... don't _think_ so. @dukenv0307, did we miss something?

**Comment by johncschuster** [comment] 2023-10-20 11:00
@dukenv0307 

> I just added a note here, @robertKozik approves this issue within 3 working days. And after that, we wait for the final review from @chiragsalian

This isn't quite right. It looks like the PR was created on `2023-09-25` and approved on `2023-09-29`.

![Screenshot of Google Chrome (10-20-23, 5-58-57 AM)](https://github.com/Expensify/App/assets/5579997/5238d975-690d-4816-943d-e74a6c16e77c)


![Screenshot of Google Chrome (10-20-23, 5-59-08 AM)](https://github.com/Expensify/App/assets/5579997/bd410418-4f1b-4c13-8e5b-34cb164d9ca9)

**Comment by johncschuster** [comment] 2023-10-20 11:05
@gadhiyamanan, I just noticed you weren't invited to the job. I've just invited you directly on Upwork. Can you please accept the Reporter role? Thank you!

**Comment by gadhiyamanan** [comment] 2023-10-20 11:07
@johncschuster applied

**Comment by johncschuster** [comment] 2023-10-24 21:38
@gadhiyamanan thanks! I've sent the proposal. Can you accept that? I'll get payment issued right away!

**Comment by gadhiyamanan** [comment] 2023-10-25 02:41
@johncschuster offer accepted, thanks!

**Comment by johncschuster** [comment] 2023-10-27 18:15
Thanks for the ping, @dukenv0307! I thought the bonus was calculated on the date the PR is submitted, but it looks like I had that wrong! You are indeed eligible. Thanks for your patience while I confirmed that!

**Comment by johncschuster** [comment] 2023-10-27 18:26
I've issued the bonus 🎉

**Closed by johncschuster** 2023-10-27 18:26 UTC
Labels: External, Daily, Awaiting Payment

**Comment by gadhiyamanan** [comment] 2023-11-07 07:06
@johncschuster can you please approve milestone in upwork?
Payment is pending

**Comment by johncschuster** [comment] 2023-11-09 20:27
Thank you for the ping, @gadhiyamanan! I've just issued payment. Sorry for missing it!
