### ISSUE TITLE
Invoice - Invoice preview shows negative amount and LHN shows 0.00

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51255] opened 2024-10-22 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Send an invoice to anybody.
4. In the invoice chat, click on the invoice preview.
5. Return to the main invoice chat.

## Expected Result:
- Invoice preview will not show negative amount
- LHN will not show 0.00 as the submitted amount

## Actual Result:
- Invoice preview shows negative amount
- LHN shows 0.00 as the submitted amount
- In the invoice report, the report header also shows 0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/227ba552-86d4-4491-8cf9-fcc5113cef88

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-22 13:54
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-22 13:54
We think that this bug might be related to #vip-bills

**Comment by Christinadobrzyn** [comment] 2024-10-23 04:54
I'm not able to reproduce this on the web or iOS Safari. Asking QA what piece is missing in the Op to reproduce this.

**Comment by izarutskaya** [comment] 2024-10-23 13:11
Not reproducible for tester

https://github.com/user-attachments/assets/d2cff273-9a65-4706-b3e6-152e11a04f2c

**Comment by Christinadobrzyn** [comment] 2024-10-24 02:03
Thanks for the restest - there is something strange happening with amounts, I saw something very briefly yesterday. I'll try to capture it. We'll close this for now

**Closed by Christinadobrzyn** 2024-10-24 02:03 UTC
Labels: Daily, Bug
