### ISSUE TITLE
[HOLD for payment 2023-07-28] [HOLD for payment 2023-07-26] Clicking on 'From' link navigates to main chat rather than navigating to the previous IOU thread report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23102] opened 2023-07-18 16:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open an existing chat
2. Click on 'Request money' link
3. Enter amount & click on 'Next' button
4. Click on 'Request' button
5. Click on IOU preview component & observe that user is navigated to IOU thread report and IOU preview component is displayed 
6. Click on the IOU preview component & observe that user is navigated to a report where IOU detail is displayed
7. Click on 'From' link
## Expected Result: 
User should be navigated to to the IOU thread report where user was navigated on step 5
## Actual Result: 
User is navigated to main chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 2023-07-18 17-29-49.webm](https://github.com/Expensify/App/assets/43996225/fec37088-fc04-4b03-a1c8-9a09c24640ea)

https://github.com/Expensify/App/assets/43996225/bb2cd368-5756-4647-b373-dd5f3e795bf7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689691734672829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-07-18 16:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on 'From' link navigates to main chat rather than navigating to the previous IOU thread report

### What is the root cause of that problem?
In `HeaderWithBackButton` component, we are using `AvatarWithDisplayName`, there we are providing the `report` prop - 
https://github.com/Expensify/App/blob/f74512d7d0baf641a6dd67fabcf4a0f72f519639/src/components/HeaderWithBackButton/index.js#L83-L87

In this case if `parentReport` is not null, it's passed. And thus we are redirected to `parentReport`.

### What changes do you think we should make in order to solve the problem?
We shall change it to - 
```
report={report || parentReport}
```

In this case, if report is null, parentReport will be used. But for our case(in this bug) we want to be redirected to `report`(the page that shows IOU preview. But as `parentReport` being non null, it will be passed and we are redirected to the chat

### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment] 2023-07-18 17:13
Huh why did this get changed to daily?

**Comment by neil-marcellini** [comment] 2023-07-18 18:05
👀 I'm looking into this now.

**Comment by neil-marcellini** [comment] 2023-07-18 19:07
@BhuvaneshPatil thanks for your proposal, I think you're on the right track, but I think reversing the OR statement would cause a problem. We need to understand why we pass the parentReport sometimes. I see it was added in [this commit](https://github.com/Expensify/App/commit/59756beaec1dc41221e924441b02fe9f6fa4561f).

The reasoning in [the proposal](https://github.com/Expensify/App/issues/19438#issuecomment-1559270629) is the following.
> An issue that arises is that the [report](https://github.com/Expensify/App/blob/4a77116cb842ba61ebcb8816bae75fe20029448b/src/components/MoneyRequestHeader.js#L105) we are passing to HeaderWithCloseButton is [using props.parentReport in a singleTransactionView](https://github.com/Expensify/App/blob/4a77116cb842ba61ebcb8816bae75fe20029448b/src/components/MoneyRequestHeader.js#L80) which means the pin option won't work.

That's no longer, true, now we simply pass the report. I'm going to remove the `parentReport` prop from HeaderWithBackButton entirely. I'll make sure pinning the report still works.

**Comment by Nikhil-Vats** [comment] 2023-07-18 19:13
@neil-marcellini I was also analysing the root cause of this issue and I came to the same conclusion. This doesn't exist on prod because it was [removed in this PR](https://github.com/Expensify/App/pull/21092) but now in [this PR](https://github.com/Expensify/App/pull/21852) it was added back. I will be happy to open a PR for this right now if you want me to.

**Comment by neil-marcellini** [comment] 2023-07-18 19:14
Nice thanks for finding the PR that added it back. That's the source of the regression. I have a PR in the works now.

**Comment by neil-marcellini** [comment] 2023-07-24 16:26
@allroundexperts would you please help me out by taking care of the checklist above? Usually C+ does this.

**Comment by flaviadefaria** [comment] 2023-07-26 09:11
@allroundexperts @neil-marcellini is the below correct?

@Natnael-Guchima = $250 (reporting bonus - UW)
@allroundexperts = $1000 (request via Expensify)

Also @allroundexperts can you please fill out the checklist above? Thanks!

**Comment by flaviadefaria** [comment] 2023-07-31 08:52
Bump on the above @allroundexperts.

**Comment by flaviadefaria** [comment] 2023-08-01 11:05
@neil-marcellini should you be filling it out then? You are the one tagged so maybe that's how it works for internal issues?

**Comment by neil-marcellini** [comment] 2023-08-02 14:20
IMO C+ should always fill out the checklist. Seems like a reasonable ask for $1,000. I will do it this time to keep things moving.

**Comment by neil-marcellini** [comment] 2023-08-02 14:20
I think we should add a regression test because it's very easy to test and it's a core feature of our chat app now; people will be going into threads and going back to the parent often.

**Comment by flaviadefaria** [comment] 2023-08-02 14:24
@neil-marcellini @allroundexperts does this look good for the regression test or would you recommend adjusting it in anyway?

Open an existing chat
Click on 'Request money' link
Enter amount & click on 'Next' button
Click on 'Request' button
Click on IOU preview component & observe that user is navigated to IOU thread report and IOU preview component is displayed
Click on the IOU preview component & observe that user is navigated to a report where IOU detail is displayed
Click on 'From' link
User should be navigated to to the IOU thread report where user was navigated on step 5

**Comment by neil-marcellini** [comment] 2023-08-02 14:25
**Regression Test Proposal**

1. Open an existing chat
1. Click on the plus button in the composer
2. Click Request money
3. Enter amount & click on 'Next' button
4. Click on 'Request' button
5. Click on IOU preview component
6. Verify that the user is navigated to IOU report and IOU preview component is displayed
7. Click on the IOU preview component
8. Verify that the user is navigated to the thread report where the IOU detail is displayed
9. Click on 'From' link
10. Verify that you are navigated back to the IOU report in step 6

Do we agree 👍 or 👎

**Comment by flaviadefaria** [comment] 2023-08-02 14:26
Are these [payment](https://github.com/Expensify/App/issues/23102#issuecomment-1651309244) amounts correct? 

Since there's no contributor assigned I'm assuming we're only paying the report and the C+ for reviewing the PR?

**Comment by flaviadefaria** [comment] 2023-08-03 09:06
Offer sent to @Natnael-Guchima!

**Comment by Natnael-Guchima** [comment] 2023-08-03 09:50
Accepted the offer. Thanks @flaviadefaria

**Comment by flaviadefaria** [comment] 2023-08-03 10:02
Paid so closing this!

**Closed by flaviadefaria** 2023-08-03 10:02 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
