### ISSUE TITLE
[Hold for #34409] [$500]  Android - Public room - Extra spacing above the room header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34050] opened 2024-01-05 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33829
## Action Performed:
1. Log out.
2. Tap on public room link on a different app. (https://staging.new.expensify.com/r/2376199970894587)
3. Log in to any account

## Expected Result:
The room header has adequate spacing

## Actual Result:
There is extra spacing above the room header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![Bug6333402_1704477952176!Screenshot_20240106_020324](https://github.com/Expensify/App/assets/78819774/722ef045-3715-43c8-82c6-56025e4c13b1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fc3d6204dc1c3d6</li>
        <li>Upwork Job ID: 1745516903101734912</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by blimpich** [comment] 2024-01-05 18:48
I don't consider this a blocker, considering it only occurs on Android and is a fairly minor UI mishap.

**Comment by situchan** [comment] 2024-01-05 19:05
I am not able to reproduce on main

<img width="346" alt="34050" src="https://github.com/Expensify/App/assets/108292595/45e1000d-1bca-4be6-86e6-b6f78ef51f2e">

**Comment by blimpich** [comment] 2024-01-05 22:04
Hmmm, interesting. Maybe we should close this issue then if its not reproducible on main.

**Comment by greg-schroeder** [comment] 2024-01-05 22:53
Fine with that especially given it's super niche

**Comment by blimpich** [comment] 2024-01-11 18:36
Not overdue. Waiting to hear back from @situchan before assigning this out to external contributors.

**Comment by situchan** [comment] 2024-01-11 18:43
reproduced

![header](https://github.com/Expensify/App/assets/108292595/cf382430-a237-4409-9984-c2e8f3550ae0)

**Comment by bernhardoj** [comment] 2024-01-12 06:29
This is related to https://github.com/Expensify/App/issues/34154.

Read the detail [here](https://github.com/Expensify/App/issues/34154#issuecomment-1888505091) for more info.

**Comment by situchan** [comment] 2024-01-15 16:55
I am not sure it's related. This issue is about spacing, while https://github.com/Expensify/App/issues/34154 is about status bar style

**Comment by bernhardoj** [comment] 2024-01-16 03:27
<img width="819" alt="image" src="https://github.com/Expensify/App/assets/50919443/b9829531-172d-4b95-91e8-b567f3bd8a9f">

**Comment by greg-schroeder** [comment] 2024-01-18 00:35
Hmm - @situchan what do you think about the above comment/context?

**Comment by greg-schroeder** [comment] 2024-01-22 16:56
Bump @situchan on the above

**Comment by greg-schroeder** [comment] 2024-01-22 20:47
Held

**Comment by greg-schroeder** [comment] 2024-01-31 17:04
Still held

**Comment by greg-schroeder** [comment] 2024-02-06 01:11
Same

**Comment by s77rt** [comment] 2024-02-08 06:41
Another case (diff reproduction steps) has been reported here https://github.com/Expensify/App/issues/36010. Please make sure that one is covered.

**Comment by greg-schroeder** [comment] 2024-02-14 21:54
held

**Comment by situchan** [comment] 2024-02-26 16:38
Holding [PR](https://github.com/Expensify/App/pull/34409) was C+ approved today, not merged yet

**Comment by greg-schroeder** [comment] 2024-03-02 00:15
PR was merged and deployed to prod

**Comment by greg-schroeder** [comment] 2024-03-02 00:15
Let's retest to see if it works - I can't test this personally cause I don't have an android device, asking QA

**Comment by greg-schroeder** [comment] 2024-03-13 10:54
Will bump QA

**Comment by mvtglobally** [comment] 2024-03-14 15:41
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2024-03-14 23:33
Looks like deep link is broken.
I am not able to go to public room with anonymous user on android phone. Stuck on login.

**Comment by mvtglobally** [comment] 2024-03-20 03:41
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2024-03-25 11:26
I think I'm going to close this as QA can't repro

**Comment by greg-schroeder** [comment] 2024-03-25 11:26
Reopen if you disagree

**Closed by greg-schroeder** 2024-03-25 11:26 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug, retest-weekly
