### ISSUE TITLE
[$500] Chat - Pressing ESC closes the video preview modal instead of Download and Playback modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36902] opened 2024-02-20 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on "Add attachment"
2. Upload a video
3. Click on three dot then press ESC

## Expected Result:
Pressing ESC should not close the video preview modal, it should only close the Download and Playback modal

## Actual Result:
Pressing ESC closes the video preview modal instead of Download and Playback modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d065cc86-d7db-4d5f-b2b9-95c45258e03c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb3dff1b828d5004</li>
        <li>Upwork Job ID: 1759958094772105216</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2024-02-20 15:18
Edge case, not a blocker

**Comment by hkopser99** [comment] 2024-02-20 17:42
Hey @Julesssss if this is an edge case can we still review/submit proposals or will this be assigned down the road if/when it becomes a higher priority?

**Comment by Julesssss** [comment] 2024-02-21 10:00
@hkopser99 yeah, my comment was just to remove the high priority label. THis will be made external 👍

**Comment by hkopser99** [comment] 2024-02-21 10:36
**Proposal:** 

**Please re-state the problem that we are trying to solve in this issue:**

When a user presses esc instead of ending the video player preview during the video attachment upload flow, it escape from the attachment upload completely.

**What is the root cause of that problem?:** Default escape key behavior escapes from the video preview modal and prevents user from proceeding with uploading the attachment rather than simply pausing the video preview.

**What changes do you think we should make in order to solve the problem?**

In BaseVideoPlayer.js I would implement logic to recognize an esc key press, override default behavior, and use a callback that would call pauseVideo() if isVideoPlaying is set to true.

**What alternative solutions did you explore? (Optional):**

Given existing functionality, this seems like the smoothest solution unless additional functionality is desired when a use presses esc on desktop browsers or MacOS App.

**Comment by bernhardoj** [comment] 2024-02-21 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing ESC closes both the video player popover and the video player preview modal.

### What is the root cause of that problem?
Both video player preview modal (BaseModal) and video player popover (PopoverWithoutOverlay) catch the ESC event. PopoverWithoutOverlay listens for keydown, while BaseModal (`react-native-modal`) listens for keyup event.
https://github.com/Expensify/App/blob/74540f8d59ed6423064a168dba985085d11b228c/src/components/PopoverProvider/index.tsx#L61-L72

https://github.com/Expensify/App/blob/74540f8d59ed6423064a168dba985085d11b228c/patches/react-native-modal%2B13.0.1.patch#L21-L38

In `react-native-modal`, we prevent the propagation when a modal handles the ESC, but we didn't do that for PopoverWithoutOverlay, so the event is propagated to all views.

### What changes do you think we should make in order to solve the problem?

We should follow the same pattern we already have in `react-native-modal`, that is to stop the propagation.

```
if (closePopover()) {
    e.stopImmediatePropagation();
}
```

`closePopover` will return true if it passes the early return.
https://github.com/Expensify/App/blob/74540f8d59ed6423064a168dba985085d11b228c/src/components/PopoverProvider/index.tsx#L24-L32

However, this still won't work because PopoverWithoutOverlay and BaseModal listen for different events (mentioned on the root cause). We should decide whether we want to use `keyup` or `keydown`.

### What alternative solutions did you explore? (Optional)
Use BaseModal instead of PopoverWithoutOverlay by removing `withoutOverlay`.
https://github.com/Expensify/App/blob/74540f8d59ed6423064a168dba985085d11b228c/src/components/VideoPopoverMenu/index.js#L28-L37

**Comment by jjcoffee** [comment] 2024-02-21 12:39
Happy that @bernhardoj's [proposal](https://github.com/Expensify/App/issues/36902#issuecomment-1956464502) identifies the correct root cause and that the solution fits decently with it. I think it makes sense to switch to `keyup` to keep things consistent with the `BaseModal`, unless anyone has reasons to believe `keydown` is better?

@hkopser99 Thanks for your proposal! Unfortunately it's lacking somewhat in details, and the solution proposed doesn't match the expected result (we don't want to pause the video). Please also make sure to use the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) exactly as it appears (don't strip the formatting), as this makes it easier for everyone to parse your proposal quickly. :pray: 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by hkopser99** [comment] 2024-02-21 12:43
@jjcoffee Thanks for reviewing and the feedback. I will do better next time and will use the exact proposal template.

**Comment by Christinadobrzyn** [comment] 2024-02-21 18:38
@Julesssss would you be able to review the decision here - https://github.com/Expensify/App/issues/36902#issuecomment-1956563285 when you have a moment

**Comment by Julesssss** [comment] 2024-02-22 10:41
Yep, I missed this somehow. Done!

**Comment by bernhardoj** [comment] 2024-02-22 11:00
PR is ready

cc: @jjcoffee

**Comment by Rajat1120** [comment] 2024-02-23 17:01
Now, it doesn't even show the preview of the video

Uploading Screen Recording 2024-02-23 at 10.27.24 PM.mov…

**Comment by Rajat1120** [comment] 2024-02-23 17:04
Contributor details
Your Expensify account email: rajatkumarsaha254@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/rajatkumar16

**Comment by jjcoffee** [comment] 2024-03-12 10:41
This hit [production](https://github.com/Expensify/App/pull/37077#issuecomment-1970132458) 2 weeks ago.

**Comment by jjcoffee** [comment] 2024-03-12 10:49
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - this was a latent bug in `PopoverWithoutOverlay` that the video player implementation brought to light
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

Desktop only:
1. Open any chat
2. Add a new video attachment. Verify the attachment preview is shown.
3. On the video player control, press the three dots button. Verify the video player popover is shown
4. Press ESC
5. Verify the video player popover is closed
6. Press ESC again
7. Verify the attachment preview is closed

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-03-12 10:49
@Christinadobrzyn Checklist complete! This one's [due payment](https://github.com/Expensify/App/issues/36902#issuecomment-1991337199), the automation just looks to have failed.

**Comment by Christinadobrzyn** [comment] 2024-03-13 04:39
Ah thanks for moving this along @jjcoffee 

Payouts due:

Contributor: $500 @bernhardoj (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36436009/overview)
Contributor+: $500 @jjcoffee (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36436097/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01cb3dff1b828d5004).

Regression test: https://github.com/Expensify/Expensify/issues/378294

Closing! let me know if I missed anything!

**Closed by Christinadobrzyn** 2024-03-13 04:39 UTC
Labels: Reviewing, External, Engineering, Weekly, Improvement, Bug
