### ISSUE TITLE
[$500] Private Note - Link changed to text in the Private Note after saved 2nd time.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30076] opened 2023-10-20 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697045812115269

## Action Performed:
1. Open a chat with other user
2. Click header => Private notes
3. Click My note => Note
4. Input any link (eg: [google.com](http://google.com/)) => Save
5. Click Note, remove all and input link again  (eg: [google.com](http://google.com/))  => Save
6. Click Note => Save, Observed that text back to link

## Expected Result:
Link should not change to text in the Private Note after saved 2nd time.

## Actual Result:
Link changed to text in the Private Note after saved 2nd time.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/85972c46-9211-45a9-8205-e390475cfcbe

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/81273003-e4a1-4e4c-b33f-37d2ba31d57c

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/31c88229-624a-4075-98ae-46f9038d4bc3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9c64682f-3a2c-41f6-bf58-768fa35ff549

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

  

https://github.com/Expensify/App/assets/93399543/89577825-bf6a-4502-9af5-df294e6345f9

https://github.com/Expensify/App/assets/93399543/6f6b512b-2d46-4e46-af83-2847b22473ca

</details>

<details>
<summary>MacOS: Desktop</summary>

 

Uploading Screen Recording 2023-10-12 at 00.46.03.mov…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01845ea2c6e56f7e38</li>
        <li>Upwork Job ID: 1715351205310087168</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27439928</li>
<li>eh2077 | Contributor | 27439932</li>
<li>namhihi237 | Reporter | 27439936</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-10-20 12:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Editing and saving a private note that contains a link without making a change, re-creates the link. 

### What is the root cause of that problem?

Adding a private note that contains a link will create the AutoLink on save. And when a link is removed, we will check for removed links and generate the new HTML. For the case of editing and saving a private note that contains a link without making a change, we are not supposed to generate a new HTML, as this process will trigger the Auto link again. 

https://github.com/Expensify/App/blob/b7eb0f14cb0afe98a21f5c0d9c9baaec29c71b8c/src/pages/PrivateNotes/PrivateNotesEditPage.js#L107


### What changes do you think we should make in order to solve the problem?
Since saving a private note that contains a link with a new change is considered an expected behavior per https://github.com/Expensify/App/issues/29225#issuecomment-1757332445 we can make sure that saving a note without making a change does not trigger the autolink by comparing the original note and new draft and checking differences and then in that case we return early. 

```js
    const savePrivateNote = () => {
        const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');

        const trimmedPrivateNote = privateNote.trim();

        if(originalNote === trimmedPrivateNote) {
            dismissKeyboardAndGoBack()
            return;
        }

        const editedNote = Report.handleUserDeletedLinksInHtml(trimmedPrivateNote, originalNote);
        Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);
        dismissKeyboardAndGoBack()
    };
```


### What alternative solutions did you explore? (Optional)

N/A

**Comment by samilabud** [comment] 2023-10-20 13:05
How you can send a proposal at the same time the issue is published? OMG 💨

**Comment by brunovjk** [comment] 2023-10-20 13:54
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Editing and saving a private note that contains a link without making a change, re-creates the link.
> 
> ### What is the root cause of that problem?
> Adding a private note that contains a link will create the AutoLink on save. And when a link is removed, we will check for removed links and generate the new HTML. For the case of editing and saving a private note that contains a link without making a change, we are not supposed to generate a new HTML, as this process will trigger the Auto link again.
> 
> https://github.com/Expensify/App/blob/b7eb0f14cb0afe98a21f5c0d9c9baaec29c71b8c/src/pages/PrivateNotes/PrivateNotesEditPage.js#L107
> 
> ### What changes do you think we should make in order to solve the problem?
> Since saving a private note that contains a link with a new change is considered an expected behavior per [#29225 (comment)](https://github.com/Expensify/App/issues/29225#issuecomment-1757332445) we can make sure that saving a note without making a change does not trigger the autolink by comparing the original note and new draft and checking differences and then in that case we return early.
> 
> ```js
>     const savePrivateNote = () => {
>         const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');
> 
>         const trimmedPrivateNote = privateNote.trim();
> 
>         if(originalNote === trimmedPrivateNote) {
>             dismissKeyboardAndGoBack()
>             return;
>         }
> 
>         const editedNote = Report.handleUserDeletedLinksInHtml(trimmedPrivateNote, originalNote);
>         Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);
>         dismissKeyboardAndGoBack()
>     };
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> N/A

@abdel-h66 I tried your solution, `dismissKeyboardAndGoBack()` didn't work here, I updated your solution:
```
    const savePrivateNote = () => {
        const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');
        const trimmedPrivateNote = privateNote.trim();

        if(originalNote != trimmedPrivateNote) {
            const editedNote = Report.handleUserDeletedLinksInHtml(trimmedPrivateNote, originalNote);
            Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);
        }

        Keyboard.dismiss();

        // Take user back to the PrivateNotesView page
        Navigation.goBack(ROUTES.PRIVATE_NOTES_VIEW.getRoute(report.reportID, route.params.accountID));
    };
```
And now it works fine, make sense?

Thanks.

**Comment by brunovjk** [comment] 2023-10-20 14:28
In the `main branch` we have:
https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/PrivateNotes/PrivateNotesEditPage.js#L107-L107

However, in another branch, like this one, we have:
https://github.com/Expensify/App/blob/b7eb0f14cb0afe98a21f5c0d9c9baaec29c71b8c/src/pages/PrivateNotes/PrivateNotesEditPage.js#L107

I managed to reproduce the error using `main const editedNote`, but when I removed `parser.htmlToMarkdown(...).trim()`, like the branch presented previously, the error in this `issue` is no longer reproduced.

@kbecciv, @namhihi237 and @abdel-h66 Do you know why this is? I'm new here, thank you.

**Comment by brunovjk** [comment] 2023-10-20 14:43
> ## Proposal
...
> 
> ```js
>     const savePrivateNote = () => {
>         const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');
> 
>         const trimmedPrivateNote = privateNote.trim();
> 
>         if(originalNote === trimmedPrivateNote) {
>             dismissKeyboardAndGoBack()
>             return;
>         }
> 
>         const editedNote = Report.handleUserDeletedLinksInHtml(trimmedPrivateNote, originalNote);
>         Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);
>         dismissKeyboardAndGoBack()
>     };
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> N/A

@abdel-h66  I don't know why but `dismissKeyboardAndGoBack` doesn't seem to work.
[notback.webm](https://github.com/Expensify/App/assets/95647348/a5a542c2-1346-4b31-a3c0-ee31ed3d9423)



I changed your solution a bit, and here on my local it works fine:
```
    const savePrivateNote = () => {
        const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');
        const trimmedPrivateNote = privateNote.trim();

        if(originalNote != trimmedPrivateNote) {
            const editedNote = Report.handleUserDeletedLinksInHtml(trimmedPrivateNote, originalNote);
            Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);
        }

        Keyboard.dismiss();

        // Take user back to the PrivateNotesView page
        Navigation.goBack(ROUTES.PRIVATE_NOTES_VIEW.getRoute(report.reportID, route.params.accountID));
    };
```
[worked.webm](https://github.com/Expensify/App/assets/95647348/f33a1327-83b0-4ebf-9705-edfbbad6519b)

@abdel-h66 Make sense?

**Comment by abdel-h66** [comment] 2023-10-20 15:04
I see the condition switch, I will take some later to check why the keyboard dismiss didn't work before the refactoring.

**Comment by eh2077** [comment] 2023-10-20 15:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Private Note - Link changed to text in the Private Note after saved 2nd time.

### What is the root cause of that problem?

The root cause of this issue is that, when saving private note, we don't clear the draft of the private note, see

https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105-L113

So when we open to edit the private note again, the initial draft is same as the draft of previous editing, see

https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/PrivateNotes/PrivateNotesEditPage.js#L67

`Report.getDraftPrivateNote(report.reportID)` returns the previous saved private ntoe draft.

For example, we enter private note

```
google.com
```

and save it. From the private note view page, we see `google.com` in hyper link.

If we edit the private note again, the initial draft is 

```
google.com
```

which is incorrect. It should be 

```
[google.com](https://google.com)
```

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should clean up private note draft when saving the note. We can add

```js
debouncedSavePrivateNote('');
```

in the end of method [savePrivateNote](https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105). 

Back to avoid converting plain link text to hyperlink when saving without making change, we can check and early return if `privateNote.trim()` is equal to `originalNote`. So the improved version of method  [savePrivateNote](https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/PrivateNotes/PrivateNotesEditPage.js#L105) will be like

```js
    const savePrivateNote = () => {
        const originalNote = lodashGet(report, ['privateNotes', route.params.accountID, 'note'], '');

        if (privateNote.trim() === originalNote.trim()) {
            Keyboard.dismiss();
            // Take user back to the PrivateNotesView page
            Navigation.goBack(ROUTES.PRIVATE_NOTES_VIEW.getRoute(report.reportID, route.params.accountID));
            return;
        }

        const editedNote = Report.handleUserDeletedLinksInHtml(privateNote.trim(), parser.htmlToMarkdown(originalNote).trim());
        Report.updatePrivateNotes(report.reportID, route.params.accountID, editedNote);

        // We want to delete saved private note draft after saving the note
        debouncedSavePrivateNote('');

        Keyboard.dismiss();
        // Take user back to the PrivateNotesView page
        Navigation.goBack(ROUTES.PRIVATE_NOTES_VIEW.getRoute(report.reportID, route.params.accountID));
    };
```



<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/4403c2d6-274e-4399-9f9a-c800675a9a68
</details>



### What alternative solutions did you explore? (Optional)

N/A

**Comment by Natnael-Guchima** [comment] 2023-10-20 20:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private Note - Link changed to text in the Private Note after saved 2nd time
### What is the root cause of that problem?
The root cause is that we are comparing `originalCommentMarkdown` ( [google.com](https://google.com/) ) with `newCommentText` (google.com) and return a `removedLinks` of [‘https://google.com/’] here
https://github.com/Expensify/App/blob/1fa4923da3a4fa1a22a4696644a7959f867c63bf/src/libs/actions/Report.js#L1174

Then, we use `removedLinks` to remove anchor tag of `htmlForNewComment` if the `removedLink` matchs with the link of htmlForNewComment then return a pure text (google.com) here
https://github.com/Expensify/App/blob/1fa4923da3a4fa1a22a4696644a7959f867c63bf/src/libs/actions/Report.js#L1151
### What changes do you think we should make in order to solve the problem?

We should convert `newCommentText` to markDown data type and store in a variable as below

```JavaScript
const newCommentMarkdown = parser.htmlToMarkdown(htmlForNewComment);
```

Then pass `newCommentMarkdown` instead of newCommentText to `parser.getRemovedMarkdownLinks` as below

```JavaScript
const removedLinks = parser.getRemovedMarkdownLinks(originalCommentMarkdown, newCommentMarkdown);
```

`removedLinks` will be an empty array if originalComemntMarkdown, and newCommentMarkdown are equal, resulting in the anchor tag from htmlForNewComment won’t be removed.

**Result** 

before: 
https://github.com/Expensify/App/assets/57330233/86da91be-abfc-48fa-9b53-e701d1ed1180

after: 
https://drive.google.com/file/d/1OR6_U4HvZ4A881YZ-IAlE4byQGLr5kIZ/view?usp=sharing
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-10-23 21:07
@fedirjh can you review the proposals above?

**Comment by Li357** [comment] 2023-10-30 16:13
Reviewing now!

**Comment by Li357** [comment] 2023-10-30 16:16
Agree with @eh2077's solution! assigning.

**Comment by eh2077** [comment] 2023-11-01 14:05
@fedirjh PR https://github.com/Expensify/App/pull/30688 is ready for review, thanks!

**Comment by Li357** [comment] 2023-11-21 16:09
@fedirjh @eh2077 Are we good to close this one out?

**Comment by abekkala** [comment] 2023-11-22 15:47
### PAYMENTS: 

- Reporter: @namhihi237 [$50]
- Fix: @eh2077 [$500]
- PR Review: @fedirjh [$500]

**Comment by abekkala** [comment] 2023-11-22 15:50
@namhihi237 - @eh2077 - @fedirjh : Payments sent and contracts ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-11-22 15:51
https://github.com/Expensify/Expensify/issues/338631

**Closed by abekkala** 2023-11-22 15:51 UTC
Labels: Reviewing, External, Weekly, Bug
