### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Workspace room - No red dot in LHN for same WS room once internet connection is enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35061] opened 2024-01-24 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4226256&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. On main device, create a workspace room from the FAB button
3. Disable the internet connection in the device
4. Click the header of the workspace room to open the room details page
5. Click "Settings"
6. Rename the room (#examplerename) and hit save (Note: inputs are grayed out (50% opacity)
7. Sign into the same account on another device or incognito window (Note: in this case I signed in on mobile web - please check the video attachment for secondary device on mobile web)
8. Create another workspace room on the same workspace with the same name (#examplerename)
9. In the main testing device - enable the internet connection

## Expected Result:
Red dot should appear in LHN once internet connection is enabled in main device for a WS room that is created on secondary device with same name

## Actual Result:
No red dot in LHN for same WS room once internet connection is enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/957e4057-f64c-4b0d-92de-2ff741abcb31

![Bug6353198_1706102039463!Screenshot__11_](https://github.com/Expensify/App/assets/78819774/b1e1ec4c-c38a-47f1-aacf-148c8d0ad66e)

https://github.com/Expensify/App/assets/78819774/eff4633c-dbe7-4f25-9b05-8b1abe1d7803

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132f5dcb3eeda3dc1</li>
        <li>Upwork Job ID: 1750167560080097280</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28129966</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-24 14:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN doesn't show a red dot error when there is an error.

### What is the root cause of that problem?
The red dot will show if there is an error.
https://github.com/Expensify/App/blob/6cfdd6f47fe5f932b70f440104accffea586ef60/src/libs/SidebarUtils.ts#L322-L323

And `hasErrors` is defined before `result.allReportErrors`.
https://github.com/Expensify/App/blob/6cfdd6f47fe5f932b70f440104accffea586ef60/src/libs/SidebarUtils.ts#L309

So, it's always false

### What changes do you think we should make in order to solve the problem?

Put `hasErrors` after `result.allReportErrors`

**Comment by cead22** [comment] 2024-01-24 21:33
In the interest of moving this forward quickly, I'm good with solving this here. @Santhosh-Sellavel does the proposal look good to you?

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 15:29
@bernhardoj's proposal LGTM!

> we can just have a new local var called allReportErrors and use it for both hasErrors and result.allReportErrors

This sounds good to me!

C+ Reviewed
🎀 👀 🎀 

cc: @cead22

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 16:57
Waiting for CME Review.

I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

https://github.com/Expensify/App/issues/31748#issuecomment-191079021

cc: @NikkiWines

**Comment by kadiealexander** [comment] 2024-01-30 01:29
@NikkiWines @cead22 any thoughts on Santhosh's assessment?

**Comment by NikkiWines** [comment] 2024-01-30 02:18
That proposal looks good to me - we can assign another C+ if the PR is up before @Santhosh-Sellavel is back!

**Comment by bernhardoj** [comment] 2024-01-30 04:53
PR is ready

**Comment by kadiealexander** [comment] 2024-02-15 03:55
Payouts due:

- [x] Contributor: $500 @bernhardoj 
- [ ] Contributor+: $500 @Santhosh-Sellavel

Upwork job is [here](https://www.upwork.com/jobs/~0132f5dcb3eeda3dc1).

**Comment by kadiealexander** [comment] 2024-02-18 23:35
@Santhosh-Sellavel don't forget about the checklist please!

**Comment by kadiealexander** [comment] 2024-02-22 01:41
Santhosh is OOO til March - @NikkiWines could you please help with the BugZero checklist in his absence?

**Comment by NikkiWines** [comment] 2024-02-22 19:10
@kadiealexander done!

**Comment by kadiealexander** [comment] 2024-02-23 01:18
Closing, Santhosh can request payment on NewDot!

**Closed by kadiealexander** 2024-02-23 01:18 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 17:42
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-05-31 04:28
$500 approved for @Santhosh-Sellavel
