### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] valid html code displays 'this is beginning...' and invalid html code displays weird symbol in LHN for few seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19789] opened 2023-05-30 01:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send valid html code. eg: `&#32;`
4. Observe the message in LHN
5. Send invalid html code. eg: `&#21;`
6. Observe the message in LHN
## Expected Result: 
App should display the message as it is in LHN
## Actual Result: 
App displays 'This is beginning...' message for valid HTML code and  weird emoji for invalid HTML code for few seconds in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/12284b7c-b522-44f0-bf31-c5c872deb5a9

https://github.com/Expensify/App/assets/43996225/78e6cc99-09f3-4e9f-931f-374441e0ffc3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685097977437509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114e290337f545c10</li>
        <li>Upwork Job ID: 1663626267506884608</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-05-30 16:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When you send valid html code like `&#32;`, LHN displays `this is beginning ...`.
When you send invalid html like `&#21;1, LHN displays weird symbol.

### What is the root cause of that problem?

The root cause of this issue is in the following function
https://github.com/s-alves10/App/blob/95efb234dc6d9c14d01fa7ffafb2c3d90bfd82f7/src/libs/ReportUtils.js#L642-L644

We decode the `lastMessageText` first and add some processing to it. But `lastMessageText` was already decoded text as you can see from where the above function is used.

Double decoding is the main reason.

### What changes do you think we should make in order to solve the problem?
Simply removing the decoding part in the function would solve the issue.

```
function formatReportLastMessageText(lastMessageText) {
    return String(lastMessageText).replace(CONST.REGEX.AFTER_FIRST_LINE_BREAK, '').substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH).trim();
}
```

This works perfectly.

This issue is similar to [issue 19539](https://github.com/Expensify/App/issues/19539). Both issues can be solved in a PR

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/502de519-9595-42d7-804d-dc83aac5a912


</details>

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-05-30 19:20
Hey @parasharrajat looks like there are a few proposals already in the scrollback.

**Comment by therealsujitk** [comment] 2023-05-30 19:31
Very similar to #19539. If we can get the logic that the server is using we can prevent similar issues from coming up in the future.

**Comment by stitesExpensify** [comment] 2023-05-31 21:01
Yes I think we should wait. I'll update the title

**Comment by therealsujitk** [comment] 2023-06-01 15:43
After some testing I found that the issue cannot be resolved by simply removing `Str.htmlDecode()` - [The reason](https://github.com/Expensify/App/issues/19539#issuecomment-1571870772).

The reason for this issue is with the [Expensify/expensify-common](https://github.com/Expensify/expensify-common) package and this is the line that's causing it.

https://github.com/Expensify/expensify-common/blob/c898563fe851d9a4d594fa9afbdd1ddab5971636/lib/ExpensiMark.js#L589

[underscore](https://www.npmjs.com/package/underscore)'s `unescape()` function [only decodes a limited set of characters](https://stackoverflow.com/questions/36352155/unescape-function-from-underscore-js-not-working) (`&amp;` becomes `&`, but it doesn't decode html entities such as `&#32;`). 

Because of this only few parts of the string are being unescaped before it is returned. To resolve this `_.unescape(replacedText);` will have to be replaced with `Str.htmlDecode(replacedText);`.

Slack Discussion - https://expensify.slack.com/archives/C01GTK53T8Q/p1685590681879659

<hr>

The PR I created (#19962) fixes #19539 but not this one. My suggestion is to fix the issue with this package first and then create a PR to update the dependency and fix issues such as this one. I found a few instances of `Str.htmlDecode()` being used on top of `parser.htmlToText()`, this will have to be removed as well.

**Comment by therealsujitk** [comment] 2023-06-02 04:59
I've opened a PR for this - https://github.com/Expensify/expensify-common/pull/543. Also, I believe this issue is a regression.

**Comment by therealsujitk** [comment] 2023-06-02 19:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user types in HTML entities such as `&#32;`, they get rendered.

### What is the root cause of that problem?

The reason for this is because we're unescaping the text string twice, first using `_.unescape()` in Expensify/expensify-common and second using `Str.htmlDecode()` in this repository.

### What changes do you think we should make in order to solve the problem?


To resolve this we switch to using `Str.htmlDecode()` in Expensify/expensify-common and remove the use of `Str.htmlDecode()` in this repository when it's used on top of `parser.htmlToText()`.

The reason we have to use `Str.htmlDecode()` is because `_.unescape()` decodes only a limited set of entities and leaves out the rest (ex: `&#32;`) resulting in an incomplete decode. This will fix issues such as [this](https://github.com/Expensify/App/issues/19539#issuecomment-1571870772). Why this is necessary is further explained [here](https://github.com/Expensify/App/pull/19237#issuecomment-1574029786).

### What alternative solutions did you explore? (Optional)
None.

**Comment by therealsujitk** [comment] 2023-06-02 19:21
I've added my proposal because I haven't been assigned to this issue, sorry for creating a PR in Expensify/expensify-common without being assigned. I'll close the PR if we decide to go with another proposal.

**Comment by therealsujitk** [comment] 2023-06-06 12:22
I think this can be taken off HOLD?

**Comment by stitesExpensify** [comment] 2023-06-07 15:00
I can't add @alitoshmatov until they comment on this issue.

**Comment by s77rt** [comment] 2023-06-07 15:40
@alitoshmatov @therealsujitk Let's keep the discussion in this issue.

@alitoshmatov For E/App we need a PR that removes outdated htmlDecode for plain text.

**Comment by alitoshmatov** [comment] 2023-06-07 18:03
@s77rt I am working on PR, just to clarify, how can I test if code is working as expected after removing `Str.htmlDecode` since it is not the same with `parser.htmlToText`. I mean `Str.htmDecode` might have been added to cover some cases which `parser.htmlToText` does not cover.

**Comment by s77rt** [comment] 2023-06-07 18:40
@alitoshmatov Just remove the instances where `Str.htmlDecode` is used on a text.

**Comment by alitoshmatov** [comment] 2023-06-08 07:27
Opened PR - https://github.com/Expensify/App/pull/20443

**Comment by stephanieelliott** [comment] 2023-06-15 19:11
Reapplying the `Bug` label to get another BZ member on this while I am OOO til July 3. Thanks @Christinadobrzyn,  this PR was deployed to staging yesterday so probably not much to do here other than wait to issue payment!

**Comment by Christinadobrzyn** [comment] 2023-06-16 17:46
moving to weekly since PR is under review

**Comment by s77rt** [comment] 2023-06-16 17:48
No PR is under review. https://github.com/Expensify/App/pull/20443 is merged. Waiting to be deployed to production

**Comment by s77rt** [comment] 2023-06-19 11:57
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/19237
- The offending PR has been commented on: https://github.com/Expensify/App/pull/19237#issuecomment-1597040243
- A discussion in #expensify-bugs has been started: I'm pretty sure we don't have much to discuss here, the encoding issue was a thing going for a long time and we started fixing this a couple of weeks ago, this is just a propagation of the fix.
- Determine if we should create a regression test for this bug: No

**Comment by Christinadobrzyn** [comment] 2023-06-21 23:02
Hired in Upwork

Internal job: https://www.upwork.com/ab/applicants/1663626267506884608/job-details
External job: https://www.upwork.com/jobs/~0114e290337f545c10

@dhanashree-sawant reporter
@parasharrajat C+
@alitoshmatov contributor

Speed bonus applies - https://github.com/Expensify/App/issues/19789#issuecomment-1591384591

**Comment by Christinadobrzyn** [comment] 2023-06-22 16:11
Ah thanks @parasharrajat! I'll just pay the reporter when we're ready!

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:30
Paid @dhanashree-sawant for reporting. Closed job in Upwork. Closing this GH.

**Closed by Christinadobrzyn** 2023-06-23 23:30 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug
