### ISSUE TITLE
[HOLD for payment 2022-08-30] [$250] Web - Login container isn't in center @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9509] opened 2022-06-21 13:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the login page
2. Decrease the screen size

## Expected Result:
Login container should be in the center

## Actual Result:
Login container isn't in center

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- 
- Desktop App

**Version Number:** 1.1.78.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/174805956-32393d8e-d727-469e-94a7-1a283726d6c0.mov

**Upwork job link:** https://www.upwork.com/jobs/~01c152638d05db933a

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654600244913639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2022-06-23 23:52
Easily reproducible, making this a FirstPick

**Comment by Justicea83** [comment] 2022-07-06 19:20
adding external so our contributors can take a look

**Comment by michaelhaxhiu** [comment] 2022-07-12 16:08
Upwork job link - https://www.upwork.com/jobs/~01c152638d05db933a

**Comment by metehanozyurt** [comment] 2022-07-12 17:18
## Proposal
### Cause

style information is not given when the application is at medium screen width (800-1024).

 props.isSmallScreenWidth ? styles.signInPageNarrowContentMargin : {},
 !props.isMediumScreenWidth ? styles.signInPageWideLeftContentMargin : {},

0-800 >> styles.signInPageNarrowContentMargin (marginTop: '40%')
800-1024 >> {}
1024 - ...  >> styles.signInPageWideLeftContentMargin (marginTop: '44.5%')
### Solution

We can solve this problem by giving still information with small screen or big screen separation. So it will be in the same position for medium and large screens.

https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/pages/signin/SignInPageLayout/SignInPageContent.js#L56-L60

```js
 behavior="position"
                contentContainerStyle={[
                    props.isSmallScreenWidth ? styles.signInPageNarrowContentMargin : styles.signInPageWideLeftContentMargin,
                    styles.mb3,
                    StyleUtils.getModalPaddingStyles({

```

**Comment by SahilSharma29** [comment] 2022-07-14 12:53
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> ## Action Performed:
> 1. Go to the login page
> 2. Decrease the screen size
> 
> ## Expected Result:
> Login container should be in the center
> 
> ## Actual Result:
> Login container isn't in center
> 
> ## Workaround:
> Unknown
> 
> ## Platform:
> Where is this issue occurring?
> 
> * Web
> * Desktop App
> 
> **Version Number:** 1.1.78.1
> 
> **Reproducible in staging?:** Yes
> 
> **Reproducible in production?:** Yes
> 
> **Email or phone of affected tester (no customers):** any
> 
> **Logs:** https://stackoverflow.com/c/expensify/questions/4856
> 
> **Notes/Photos/Videos:** Any additional supporting documentation
> 
>  Screen.Recording.2022-06-02.at.11.51.58.PM.mov 
> **Upwork job link:** https://www.upwork.com/jobs/~01c152638d05db933a
> 
> **Issue reported by:** @thesahindia
> 
> **Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654600244913639
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)



> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> ## Action Performed:
> 1. Go to the login page
> 2. Decrease the screen size
> 
> ## Expected Result:
> Login container should be in the center
> 
> ## Actual Result:
> Login container isn't in center
> 
> ## Workaround:
> Unknown
> 
> ## Platform:
> Where is this issue occurring?
> 
> * Web
> * Desktop App
> 
> **Version Number:** 1.1.78.1
> 
> **Reproducible in staging?:** Yes
> 
> **Reproducible in production?:** Yes
> 
> **Email or phone of affected tester (no customers):** any
> 
> **Logs:** https://stackoverflow.com/c/expensify/questions/4856
> 
> **Notes/Photos/Videos:** Any additional supporting documentation
> 
>  Screen.Recording.2022-06-02.at.11.51.58.PM.mov 
> **Upwork job link:** https://www.upwork.com/jobs/~01c152638d05db933a
> 
> **Issue reported by:** @thesahindia
> 
> **Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654600244913639
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by SahilSharma29** [comment] 2022-07-14 12:57
Hii there is a simple solution to ride this issue, for centering the login container we fix it by using some styling according to the dimensions of the mobile by using this it's fixed and responsive also from all devices. Please apply this method I hope this will work.

**Comment by Santhosh-Sellavel** [comment] 2022-07-15 18:44
@metehanozyurt Can re-write your update proposal's new comment.

**Comment by metehanozyurt** [comment] 2022-07-16 21:33
## Updated Proposal
### Cause

style information is not given when the application is at medium screen width (800-1024). Its ok when height above the 854 (variables.minHeightToShowGraphics) because splits horizontally. But when screen height split vertically.

 props.isSmallScreenWidth ? styles.signInPageNarrowContentMargin : {},
 !props.isMediumScreenWidth ? styles.signInPageWideLeftContentMargin : {},

0-800 >> styles.signInPageNarrowContentMargin (marginTop: '40%')
800-1024 >> {}
1024 - ...  >> styles.signInPageWideLeftContentMargin (marginTop: '44.5%')

### Solution

We can solve this situation by adding a second rule that checks the width and height information (`(props.isMediumScreenWidth && props.windowHeight < variables.minHeightToShowGraphics)`).


https://github.com/Expensify/App/blob/02fb4e9738fbe491c3a8e48dfb7abd141320baa6/src/pages/signin/SignInPageLayout/SignInPageContent.js#L55-L67

need to change like this

```
<LoginKeyboardAvoidingView
                behavior="position"
                contentContainerStyle={[
                    props.isSmallScreenWidth ? styles.signInPageNarrowContentMargin : {},
                    !props.isMediumScreenWidth || (props.isMediumScreenWidth && props.windowHeight < variables.minHeightToShowGraphics) ? styles.signInPageWideLeftContentMargin : {},
                    styles.mb3,
                    StyleUtils.getModalPaddingStyles({
                        shouldAddBottomSafeAreaPadding: true,
                        modalContainerStylePaddingBottom: 20,
                        safeAreaPaddingBottom: props.insets.bottom,
                    }),
                ]}
            >
```

https://user-images.githubusercontent.com/6093207/178557429-5527b264-32cb-4bf1-991d-9fb10c9991ab.mp4

**Comment by sketchydroide** [comment] 2022-07-25 15:58
@Santhosh-Sellavel are you happy with @metehanozyurt improved coment and solution?

**Comment by Justicea83** [comment] 2022-07-25 16:12
>@Santhosh-Sellavel are you happy with @metehanozyurt improved comment and solution?

Personally, I think it looks good

**Comment by Santhosh-Sellavel** [comment] 2022-07-26 16:06
Sorry, @metehanozyurt  missed this one out earlier!

@metehanozyurt Proposal looks good!
🎀 👀 🎀  C+ Reviewed!

cc: @sketchydroide

**Comment by michaelhaxhiu** [comment] 2022-07-26 17:35
@metehanozyurt @Santhosh-Sellavel @thesahindia you've been invited to the job on upwork.

**Comment by michaelhaxhiu** [comment] 2022-08-04 21:44
Seems like the PR is close, this is coming along

**Comment by michaelhaxhiu** [comment] 2022-08-11 12:15
deployed to staging, waiting now

**Comment by michaelhaxhiu** [comment] 2022-08-22 08:11
We are still waiting on the deploy here, seems it's not ready yet.

**Comment by mvtglobally** [comment] 2022-08-23 04:19
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment] 2022-08-30 13:08
All paid.

**Closed by michaelhaxhiu** 2022-08-30 13:08 UTC
Labels: Exported, External, Engineering, Weekly, FirstPick, Improvement, Awaiting Payment
