### ISSUE TITLE
 "Hmm.. it's not here ..." message is shown while open the #announce first time  for sometime in incognito mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18924] opened 2023-05-14 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Copy any #announce url and open in incognito mode
2. try to login with same account
3. observe the screen

## Expected Result: 
"Hmm.. it's not here ..." message should not show
## Actual Result: 
"Hmm.. it's not here ..." message is appeared for some time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1cacc05b-df2c-44b8-bd7c-cccfc18415a7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @iravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683124917717009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment] 2023-05-15 17:32
I also can't reproduce

**Comment by dylanexpensify** [comment] 2023-05-16 09:05
Unable to reproduce. @kavimuru can you repro?

**Comment by dylanexpensify** [comment] 2023-05-17 07:14
Closing

**Closed by dylanexpensify** 2023-05-17 07:14 UTC
Labels: Daily, Needs Reproduction, Bug
