### ISSUE TITLE
[$2000] App fails on devices using recent node/npm with JavaScript error - reported by David Frenkiel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8888] opened 2022-05-06 04:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Git clone, npm install, npm run web

## Expected Result:
App runs without invalid hook call JavaScript error.

## Actual Result:
Browser window opens and remains blank, and there’s an invalid hook call... error in the JavaScript console.

There do appear to be invalid hook calls in react-native-safe-area-context in SafeAreaContext.tsx.

## Workaround:
Using an old node/npm version (e.g. 14.9.0/6.14.8) resolves the issue.

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.56-0
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="728" alt="expensify_m1_issue_1" src="https://user-images.githubusercontent.com/43995119/167069597-31c06d18-4296-4d48-88a7-f4d53cbd1949.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ David Frenkiel
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650494818552169?thread_ts=1650471398.505469&cid=C01GTK53T8Q

**Job Post:** https://www.upwork.com/jobs/~01570a3972089306b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-05-06 16:52
Not running an M1 mac so can't properly test this.

**Comment by JediWattson** [comment] 2022-05-07 00:31
I just wanted to point out that I'm having the issue on an i5 intel macbook, so I don't think it's specific to m1

Also I wanted to share if you run "npm install" after the initial install you'll get this error.
This install was run using: 
node v18.0.0
npm v8.6.0

<img width="571" alt="Screen Shot 2022-05-06 at 8 23 44 PM" src="https://user-images.githubusercontent.com/6119181/167230436-483403af-7a74-4c80-9d53-521aba8630b3.png">

**Comment by muas19** [comment] 2022-05-07 06:39
This issue affects not only m1 macbooks.

**Comment by kevinksullivan** [comment] 2022-05-11 13:36
@frenkield please apply to [the job](https://www.upwork.com/jobs/~01d7a1a2773917835b) for reporting the issue. Thanks!

**Comment by muas19** [comment] 2022-05-11 13:37
Proposal
The app works on a downgrade of node. Use node version 14
 brew install node@14
 brew unlink node
 brew link node@14
 brew link --force --overwrite node@14

**Comment by frenkield** [comment] 2022-05-11 17:14
Thanks, @kevinksullivan.

So sorry, I'm not quite sure how this works. Am I applying just for the bug submission, or for both the submission and the fix?

**Comment by tortutales** [comment] 2022-05-11 17:24
If it's working for old node versions my proposal is to add a node version spec in the `package.json` file
In that way every developer, no matter what node version has, the project will have a local dependency with that node version

**Comment by Santhosh-Sellavel** [comment] 2022-05-12 03:19
@tgolen Able to reproduce this one at my end, what are we looking for here as a solution?

**Comment by kaushiktd** [comment] 2022-05-12 04:42
It will be difficult to give any technical description at this point because first, it needs to be checked after doing a version upgrade or downgrade.

**Comment by tgolen** [comment] 2022-05-12 17:16
OK, thanks for the update. I think until we know what the problem is, we should avoid making any guesses about how to solve the problem. My comment still stands though, that I think the first solution that should be looked at is updating the third-party-lib.

**Comment by jrstanley** [comment] 2022-05-13 19:59
### Proposal:

I can replicate this issue on my M1 Mac. I define the issue and propose solutions below.

### Steps to reproduce:
1. Clone repo
2. `npm install`
3. `npm run web`
4. Observe application launches and UI loads
5. Exit `npm run web`
6. `npm install`
7. Observe error relating to `npm run compile` command
8. `npm run web`
9. Observe application launches but UI does not load. Web console errors.
10. Exit `npm run web`
11. Remove `npm run compile &&` from `scripts/react-native-web.sh`
12. `npm install`
13. `npm run web`
14. Observe application launches and UI loads

### VIDEO:
[**currently uploading**] This video demonstrates the reproduction steps above and highlights the issue as identified and explained below.

### The issue:
The issue appears to occur when `scripts/react-native-web.sh` is called more than once. The script is called every time `npm install` due to the  `postinstall` entry in `package.json`.

On first install the `react-native-web` package installed from a private package hosted on the Expensify `react-native-web` GitHub repository. The entry for this is also in `package.json`. The `package.json` file in the [Expensify `react-native-web` repo](https://github.com/Expensify/react-native-web) [contains an npm scripts entry named compile](https://github.com/Expensify/react-native-web/blob/master/package.json#L7). This script is called upon in `react-native-web.sh`.

As part of `react-native-web.sh` the script cd's into `node_modules/react-native-web` and, amongst other things, [copies the contents](https://github.com/Expensify/App/blob/main/scripts/react-native-web.sh#L10) of `node_modules/react-native-web/packages/react-native-web` into `node_modules/react-native-web`. This includes a [`package.json` file](https://github.com/Expensify/react-native-web/blob/master/packages/react-native-web/package.json) which crucially does not contain a scripts entry.

On subsequent runs of `npm install` the `postinstall` `react-native-web.sh` script attempts to run `npm run compile` in `node_modules/react-native-web` except, this command no longer exists in the `package.json` file that was copied from the directory `packages`. Crucially, this error causes the remainder of the `react-native-web.sh` file not to execute.

**Workaround to prove the issue:**
Remove the line `npm run compile &&` from `scripts/react-native-web.sh` when calling `npm install` after the first initial install. The application will this time run and the UI will load in the browser. Note: this does not factor any issues that may arise from not calling `npm run compile`.

### Possible solutions:
1. Modify `scripts/react-native-web.sh` such that commands following `npm run compile` do not require that command to run successfully. This could be done by updating the line from `npm run compile &&` to npm run compile;` (note the semicolon).
2. OR, reset the contents of `node_modules/react-native-web` to that of the dependency defined in the root `package.json`. This can be achieved by adding a `prepare ` entry to the `scripts` property in `package.json` as follows: `"prepare": "rm -rf ./node_modules/react-native-web",`. On the first install, this would attempt to remove a directory that doesn't exist. On subsequent installs it would remove `node_modules/react-native-web` and the `npm install` command would then install it fresh from the repository as defined in `package.json`. `react-native-web.sh` would then run on this directory "as new" (i.e. without previous modifications).
3. Modify `scripts/react-native-web.sh` to perform similar actions as described in (2), instead of creating a new entry in `package.json`. This would have the benefit of containing the related logic in one script.

**Comment by tgolen** [comment] 2022-05-16 20:48
OK, awesome. Thank you! Which proposal do you prefer? I think for me, the order of preference would be 3 > 2 > 1.

**Comment by jrstanley** [comment] 2022-05-16 21:05
@tgolen I share the same preference as you, however I think there is a practical issue that - right now - I can't think around with 3. It's the case where you `npm install` and it correctly installs `react-native-web`, I don't think there's a reliable way to determine whether or not the installed version is "correct" (without hard-coding hashes) to then decide whether or not to clear the directory/reinstall before proceeding.

With that in mind, although it does displace the logic a little, I think 2 may be the better approach. I think it is proper that we run this in the 'prepare' phase, and having it in package.json ensures this isn't missed. It will also more closely resemble the behaviour with older versions of npm, where we will reinstall the `react-native-web` package each time. I would suggest rather than trying to place an `rm` directly in the `package.json`, we;

1. Create a new file `scripts/react-native-web-prepare.sh`
2. In this file `rm -rf ./node_modules/react-native-web`
3. In `package.json` add a new `scripts` entry `"prepare": "scripts/react-native-web-prepare.sh",`

How does this sound?

**Comment by tgolen** [comment] 2022-05-16 21:10
OK, that sounds good to me! Makes sense.

**Comment by jrstanley** [comment] 2022-05-16 21:31
Perfect, thanks @tgolen! How do we take things from here?

**Comment by tgolen** [comment] 2022-05-17 19:31
@kevinksullivan Can get you hooked up with a job in Upwork to apply for (which will get you payment) and you can proceed with a PR.

**Comment by Santhosh-Sellavel** [comment] 2022-05-17 19:35
@jrstanley 
As per [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) 
> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

I see you are already assigned to https://github.com/Expensify/App/issues/8607

cc: @tgolen

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 11:02
@jrstanley Yes, you can start working on your PR!

**Comment by kevinksullivan** [comment] 2022-05-19 11:25
All set on Upwork side! @frenkield @jrstanley please accept the offers and I will pay this out once it's fixed with no regressions.

**Comment by tgolen** [comment] 2022-05-20 14:11
OK, thanks for the update. It definitely sounds like preinstall is broken!
Yikes.

**Comment by Santhosh-Sellavel** [comment] 2022-05-23 21:03
Not overdue, any update @jrstanley ?

**Comment by tgolen** [comment] 2022-05-24 15:03
Wow, love all that. I mostly agree with your order of preference, but I would make a slight modification to it:

5 (npm ls)
4ii (publish to npm - noting the maintenance this entails)
3 (write and check for presence of a file)
6 (build artefact in forked repo)
4i (yarn)

We are starting to publish more and more things in NPM (for example, we are doing it right now with `react-native-onyx`), so I think that's a very viable route and one that I would probably consider before the file or artifact (since those are kinda just hacks).

**Comment by tgolen** [comment] 2022-05-24 17:40
OK, great! Let's explore that more then. What would need to happen in order to publish it on NPM? cc @AndrewGable looping you in here because of our recent work to publish `react-native-onyx` to NPM.

**Comment by tgolen** [comment] 2022-05-24 21:23
I'm going to be OOO for a while, so I will reassign this in the meantime. Have fun with the NPM version!

**Comment by Santhosh-Sellavel** [comment] 2022-05-30 17:22
Checking this now, sorry for the delay!

**Comment by Santhosh-Sellavel** [comment] 2022-05-30 17:25
Alright, @jrstanley I believe we are still in the discussion here, any further update on this?

**Comment by AndrewGable** [comment] 2022-05-30 18:10
It's published to `npm` as of Friday: https://www.npmjs.com/package/react-native-onyx

**Comment by AndrewGable** [comment] 2022-05-30 18:19
The most obvious solution that I haven't seen mentioned is merging our changes into the upstream published package. Have we tried that?

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 16:43
@AndrewGable 
I'm going on OOO. But I still keeping this assigned to me. If there are any immediate C+ duties needed here feel free to unassign me & re-apply exported label thanks!

**Comment by AndrewGable** [comment] 2022-06-09 20:35
@jrstanley any thoughts on the above?

**Comment by Santhosh-Sellavel** [comment] 2022-06-20 18:38
Can we double this up or wait? @AndrewGable 
cc: @kevinksullivan

**Comment by kevinksullivan** [comment] 2022-06-24 03:43
Posted a fresh version of the job and doubled price.

https://www.upwork.com/jobs/~01570a3972089306b9

**Comment by aqiftekhar** [comment] 2022-06-24 13:09
> The actual issue you are facing is because the Web project Cannot find module '@lwc/eslint-plugin-lwc'
> 
> Error in VS Code: Failed to load plugin '@lwc/eslint-plugin-lwc' declared in '--config » eslint-config-expensify': Cannot find module '@lwc/eslint-plugin-lwc'
> 
> <img alt="image" width="1172" src="https://user-images.githubusercontent.com/8364171/175535195-1c40376b-d9b9-4507-924d-6beb00053236.png">
> 
> The above error that occurred in the component: - is also because of this. I guess, fixing eslint issue will fix the problem.
> 
> <img alt="image" width="1291" src="https://user-images.githubusercontent.com/8364171/175541488-ab40e8fd-a5ef-49ae-96c1-8d10e7312dc6.png">


This link will help to fix this issue. 
https://www.geeksforgeeks.org/react-js-error-boundaries/

**Comment by Santhosh-Sellavel** [comment] 2022-06-30 19:05
@AndrewGable I think we should double this up. Because 16.15.1 LTS Recommended For Most Users, and with that version this issue is a blocker for development.
cc: @kevinksullivan

**Comment by sunny-2504** [comment] 2022-06-30 20:38
Proposal
I've encountered the same problem you're facing in my job. The most common reason for this error to occur is using the react hooks in the wrong place(inside loops or nested functions) or because of a version mismatch. 
What I would do to resolve this issue :
1. Refine the code(these types of errors mostly occur because of poor code structure).
2. Rewrite the functions(sync or async) where the react hooks are being used.

**Comment by Santhosh-Sellavel** [comment] 2022-07-04 17:00
@sunny-2504 
Can you elaborate more and write a detailed/informative on the code changes you are proposing. 

Look out through [these](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Awaiting+Payment%22) past issues to get an idea about how we expect proposals.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) first!

Thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-07-04 17:02
Kindly bump this down to `weekly` while we wait for new/updated proposals, thanks! 
@AndrewGable  @kevinksullivan

**Comment by kevinksullivan** [comment] 2022-07-06 21:46
Ah, wrong issue. Disregard.

**Comment by kevinksullivan** [comment] 2022-07-15 23:55
Still waiting on proposals, updating the price.

**Comment by kevinksullivan** [comment] 2022-07-27 18:52
Price doubled.

**Comment by AndrewGable** [comment] 2022-08-09 00:10
I think we are actually working on this one internally and might be able to close this

**Closed** 2022-08-09 22:26 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Help Wanted

**Comment by kevinksullivan** [comment] 2022-08-09 22:30
@frenkield can you apply for the job so I can pay the reporting bonus? i'm not having any luck with Upwork search.

https://www.upwork.com/jobs/~01570a3972089306b9

**Comment by frenkield** [comment] 2022-08-09 22:45
Thanks, @kevinksullivan. I just applied.

**Comment by kevinksullivan** [comment] 2022-08-09 22:48
Hired! Mind accepting and then I can pay this out @frenkield ?

**Comment by frenkield** [comment] 2022-08-09 22:53
All set, @kevinksullivan.
