### ISSUE TITLE
[HOLD for payment 2023-09-21] [HOLD for payment 2023-09-18] [$500] Expensify logo vs notification color mismatch

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26255] opened 2023-08-29 20:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Login with user A on Android app (make sure notification is on for the app)
2 Login with user B on chrome browser
3 From User B on chrome, send a message to User A. This will trigger a notification.
4 Verify the color of the expensify logo is blue on the notification while the app has green

## Expected Result:
Logo color should be consistent

## Actual Result:
The notification has Expensify logo in Blue color while the actual app is in green

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**  

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0051472c-9c57-4bc2-a712-65e590f53271

https://github.com/Expensify/App/assets/115492554/7a3580b5-572e-4301-aa1e-c2d8340140bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692481632188449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01981452361d59e3c3</li>
        <li>Upwork Job ID: 1696839765016084480</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>GItGudRatio | Contributor | 26427949</li>
<li>avi-shek-jha | Reporter | 26427950</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-08-29 20:33
@Julesssss thoughts on this one?

**Comment by Julesssss** [comment] 2023-08-30 10:58
Nice, @GItGudRatio shared the solution already 👍 

The correct colour is `#03D47C`. 

While we're modifying the icon bg colour, I'm wondering if we should also change the white notification icon to be dark to better match our app icon. The problem is that this is displayed at such a low resolution that it might not look great... What do you think @shawnborton?   

![Screenshot 2023-08-30 at 11 56 08](https://github.com/Expensify/App/assets/10736861/8437dc00-622a-49d5-84df-b3d633afa08b)

**Comment by Julesssss** [comment] 2023-08-30 10:59
Manually reducing the cost of this task.

**Comment by narefyev91** [comment] 2023-08-30 12:08
@GItGudRatio good finding - your proposal looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment] 2023-08-30 13:11
Let's just see what the @Expensify/design team thinks about [the notification icon](https://github.com/Expensify/App/issues/26255#issuecomment-1698942030), and then I'll assign @GItGudRatio.

**Comment by dannymcclain** [comment] 2023-08-30 14:13
I feel like we probably just want that to match the app icon, right @shawnborton?

If we did that the background would be `#03D47C` and the iconmark would be `#002E22`.
![image](https://github.com/Expensify/App/assets/7516624/61319b17-fb86-4b7a-86ed-3511468c643d)

If legibility is an issue at that size, I wonder if we invert it so the colors are consistent but maybe it would work a little better at that tiny size?
Inverted would mean the background would be `#002E22` and the iconmark would be `#03D47C`.
![image](https://github.com/Expensify/App/assets/7516624/4ad898e2-43ea-49c5-ac21-bea401567119)

Would love for Shawn to weigh in here too.

**Comment by Julesssss** [comment] 2023-08-30 14:39
@shawnborton yeah we control the colour via the the `ic_notification` png asset [here](https://github.com/Expensify/App/blob/main/android/app/src/main/res/drawable-hdpi/ic_notification.png) (and in a few size variants)

**Comment by shawnborton** [comment] 2023-08-30 14:42
Sweet, then I say let's go with Danny's [first suggestion here](https://github.com/Expensify/App/issues/26255#issuecomment-1699270004) to match our app icon.

**Comment by Julesssss** [comment] 2023-08-30 15:05
Cool. In that case @dannymcclain could you please provided an updated PNG asset to match [this one ](https://github.com/Expensify/App/blob/main/android/app/src/main/res/drawable-xxxhdpi/ic_notification.png)please?

![ic_notification](https://github.com/Expensify/App/assets/10736861/be43251d-34b4-4232-80f0-be5a2d49d47b)

**Comment by IamAwais488** [comment] 2023-08-30 16:55
I can solve this issue, do I need to submit proposal on upwork?

**Comment by dannymcclain** [comment] 2023-08-30 17:00
Let me know if you need any other sizes and I'll be happy to export.
![ic_notification](https://github.com/Expensify/App/assets/7516624/a7cc0437-8668-4a17-9b41-4a1138e40246)

**Comment by dannymcclain** [comment] 2023-08-30 19:26
@GItGudRatio ok this should be more of what you're looking for. This .ZIP is identical to the one you referenced (but with updated images).

[Android_Images_Updated.zip](https://github.com/Expensify/App/files/12479504/Android_Images_Updated.zip)

**Comment by dannymcclain** [comment] 2023-08-30 19:59
@GItGudRatio oh my gosh 🙈 good catch. I'm so sorry. Let's try that again. Apologies!
[Android Images Take 2.zip](https://github.com/Expensify/App/files/12479722/Android.Images.Take.2.zip)

**Comment by getusha** [comment] 2023-08-31 06:27
We can probably use an icon which have a background of black, instead of transparent.

**Comment by Julesssss** [comment] 2023-08-31 09:12
> Also, I don't have access to a physical iPhone and notifications don't work on iOS simulator, @Julesssss can you please let me know if the logo on iOS notification works well or do we need to update that as well?

Lets focus on Android first, I believe the iOS notification uses our full-sized logo. 

________

> I noticed that the notification icon is either white or black depending on the dark/light mode. Is this alright?

Ah my bad. Yeah the OS is going to override our colour then... That's fine, and I think we should stick with the new asset because not every Android OS varient will do this. Some lucky Motorola user might see the correct icon colour 🤷

**Comment by Julesssss** [comment] 2023-08-31 09:13
Hi @IamAwais488, in this case I had already confirmed [this solution](https://github.com/Expensify/App/issues/26255#issuecomment-1698942030).

**Comment by avi-shek-jha** [comment] 2023-08-31 17:08
Hello, As a reporter, I received an offer for just **50 dollars instead of the standard 250 dollars**. It is my understanding that I get paid 250 USD for every bug reported. Has there been any changes to the policy? or Can anyone send me the correct offer ?

**Comment by Julesssss** [comment] 2023-09-01 07:58
Hey @NicMendonca, could this be a bug with our automation? I thought we didn't pay out until the PR is merged?

**Comment by getusha** [comment] 2023-09-01 08:00
> Hello, As a reporter, I received an offer for just 50 dollars instead of the standard 250 dollars. It is my understanding that I get paid 250 USD for every bug reported. Has there been any changes to the policy? or Can anyone send me the correct offer ?

@avi-shek-jha check this https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649

**Comment by avi-shek-jha** [comment] 2023-09-02 23:32
> > Hello, As a reporter, I received an offer for just 50 dollars instead of the standard 250 dollars. It is my understanding that I get paid 250 USD for every bug reported. Has there been any changes to the policy? or Can anyone send me the correct offer ?
> 
> @avi-shek-jha check this https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649

@getusha I understand but I reported it on Aug 19 and the Github issue was created on 29 Aug. The post says that new changes will take place from Aug 30 right ?

**Comment by Julesssss** [comment] 2023-09-11 02:37
^ This was due to our HOLD. It should recieve urgency bonus IMO

**Comment by AndrewGable** [comment] 2023-09-11 17:10
FYI - This caused a deploy blocker: https://github.com/Expensify/App/issues/27145

I reverted the original PR here: https://github.com/Expensify/App/pull/27177

The icon looked like this: 
![image_720](https://github.com/Expensify/App/assets/2838819/a995c86b-b7e6-465c-a578-7365f2613cfe)

When it should look like this:
![image_480](https://github.com/Expensify/App/assets/2838819/b3141a4d-d2fc-4ec5-92da-2c15122367de)

**Comment by Julesssss** [comment] 2023-09-12 03:04
Damn, okay thanks. We'll resubmit but this time just with the background colour change 👍

**Comment by Julesssss** [comment] 2023-09-12 03:13
New PR that simply updates the bg colour: https://github.com/Expensify/App/pull/27213

**Comment by Julesssss** [comment] 2023-09-15 03:05
Seems like our changes were valid after all. Lets make sure this issue isn't closed. I'll eventually resubmit the changes.

**Comment by NicMendonca** [comment] 2023-09-20 12:53
@narefyev91 bump on [the BZ checklist](https://github.com/Expensify/App/issues/26255#issuecomment-1719175453)!

**Comment by NicMendonca** [comment] 2023-09-21 20:10
@Julesssss just to confirm - are we waiting until 09-21 for payment?

**Comment by Julesssss** [comment] 2023-09-22 01:31
yeah, payment can occur now.

**Comment by NicMendonca** [comment] 2023-09-22 18:28
- reporter: @avi-shek-jha - $250 
- contributor: @GItGudRatio - $1500
- c+: @narefyev91 (does not require payment): n/a
- PR reviewer: @aimane-chnaif - $500


@aimane-chnaif please request payment in Expensify. Otherwise, please apply to t[he job](https://www.upwork.com/jobs/~01981452361d59e3c3) if you require payment via Upwork

@avi-shek-jha @GItGudRatio you've both been paid 

bump @narefyev9 on  BZ checklist!

**Comment by NicMendonca** [comment] 2023-09-25 19:43
> Otherwise, please apply to t[he job](https://www.upwork.com/jobs/~01981452361d59e3c3) if you require payment via Upwork

^^

**Comment by NicMendonca** [comment] 2023-09-25 19:49
ok everyone has been paid! 🎉

**Closed by NicMendonca** 2023-09-25 19:49 UTC
Labels: External, Daily, Design, Awaiting Payment, Bug
