### ISSUE TITLE
[hold for payment 2024-08-27] [$250] Distance -Distance rate is not grayed out after editing "Tax rate" & "Tax reclaimable" offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47329] opened 2024-08-13 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4849591
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Tax is enabled.
- Distance rates are enabled.
- Track tax in DIstance rates is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Distance rates.
4. Go offline.
5. Tap on any rate.
6. Edit "Tax rate" and "Tax reclaimable on".
7. Return to distance rate list.

## Expected Result:
The distance rate will be grayed out after editing "Tax rate" or "Tax reclaimable on" offline.

## Actual Result:
The distance rate is not grayed out after editing "Tax rate" or "Tax reclaimable on" offline.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/71db7762-531e-4430-8249-533e9c29e63f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01495987645fc6b7df</li>
        <li>Upwork Job ID: 1823734401301545382</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103534987</li>
<li>FitseTLT | Contributor | 103534988</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by FitseTLT** [comment] 2024-08-13 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate is not grayed out after editing "Tax rate" & "Tax reclaimable" offline

### What is the root cause of that problem?
Here we are missing `taxClaimablePercentage` and `taxRateExternalID`
https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L115-L120
### What changes do you think we should make in order to solve the problem?

We need to add pendingFields `taxClaimablePercentage` and `taxRateExternalID` to the checks here
https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L115-L120

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-08-14 14:52
Reproduced. I also verified that we generally do grey out the main option row if there is an offline change to a setting associated with it.

**Comment by ikevin127** [comment] 2024-08-14 22:28
♻️ Reviewing proposal today.

**Comment by ikevin127** [comment] 2024-08-15 01:43
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/47329#issuecomment-2286403238) LGTM. The RCA is correct and the proposed solution fixes the issue according to the **Expected result**.

🎀👀🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2024-08-15 13:24
@FitseTLT is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment] 2024-08-16 13:44
PR pending

**Comment by FitseTLT** [comment] 2024-08-16 22:14
PR ready

**Comment by joekaufmanexpensify** [comment] 2024-08-19 14:15
TY! I see it's merged now

**Comment by ikevin127** [comment] 2024-08-20 22:56
⚠️ PR was just deployed to production ~10 minutes ago but automation failed to add the hold -> this should be on **[HOLD for Payment 2024-08-27]** according to today's production deploy from https://github.com/Expensify/App/pull/47591#issuecomment-2299886099.

cc @joekaufmanexpensify

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:16
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:16
Payments here are:

- $250 to @FitseTLT for PR via upwork. 
- $250 to @ikevin127 for C+ via upwork.

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:55
All set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:56
@FitseTLT $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:56
@ikevin127 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:57
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-08-27 13:57 UTC
Labels: Reviewing, External, Daily, Bug
