### ISSUE TITLE
Requests are not condensing into the same report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33377] opened 2023-12-20 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703026542463749

## Action Performed:
Precondition :  There is an existing expense report in a workspace chat
1. Submit a expense report to workspace

## Expected Result:
 I would have expected the new request to be added to the existing one so I see two receipts in the request summary and could go into the latest request report with two requests rather than them being separate in the workspace room

## Actual Result:
Showing as separate receipts

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (5)](https://github.com/Expensify/App/assets/38435837/bb460636-e929-437b-aaa9-70e342c12480)

![image (4)](https://github.com/Expensify/App/assets/38435837/45e8019c-a636-45c4-9f1b-d14e82edeb83)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2024-01-05 21:08
I can't reproduce this one either -closing

**Closed by adelekennedy** 2024-01-05 21:08 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
