### ISSUE TITLE
[$1000] Task - Back button doesn't close the RHN when selecting assignee from task report header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21626] opened 2023-06-26 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to "+" button -> assign task
2. add title and description ->  next
3. Choose an assignee and share somewhere
4. Now it must show assign task page.
5. Go to current assignee, and click to change, it will show a list of contacts ( on the assignee page)
6. Click back button.
Notice that the title, description and other details aren't shown.
## Expected Result:
The back button should close the modal

## Actual Result: 
We are taken back to the screen where we see the task details

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0cb91482-92f6-484e-a172-a7291c16cfff

https://github.com/Expensify/App/assets/43996225/b398cb7a-1f60-4c52-b418-a5ce129bb34b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687362061844169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01577ce883e6822047</li>
        <li>Upwork Job ID: 1673473625965637632</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-26 23:29
I can repro this one!

**Comment by ygshbht** [comment] 2023-06-27 00:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users encounter an issue where, upon modifying the details (such as title, description, assignee, etc.) of an existing task, those details are not displayed on the task modification screen if they navigate back.

### What is the root cause of that problem?
The problem arises due to differences in how task details are populated when creating a task versus modifying an existing one. For instance, during task creation, the NewTaskPage component uses the following code to populate task details:

```
function onSubmit(values) {
    TaskUtils.setDetailsValue(values.taskTitle, values.taskDescription);
    Navigation.navigate(ROUTES.NEW_TASK);
}
```

Here, the **TaskUtils.setDetailsValue()** function populates the task title and description. Similarly, other components are responsible for setting other pieces of task data.

However, when modifying an existing task, such as by clicking the header in the TaskHeader component, these details aren't set. The current code looks like this:
```
<PressableWithFeedback
    onPress={() => {
        Navigation.navigate(ROUTES.getTaskReportAssigneeRoute(props.report.reportID))
    }}
/>
```

Due to this disparity, when a user navigates back from the task modification page, the task details are missing because they were never set for this particular scenario.

### What changes do you think we should make in order to solve the problem?
As an initial approach to resolve this issue, we could extend the use of TaskUtils.setDetailsValue() to also populate task details when modifying an existing task:
```
<PressableWithFeedback
    onPress={() => {
        TaskUtils.setDetailsValue(props.report.taskTitle, props.report.taskDescription);
        Navigation.navigate(ROUTES.getTaskReportAssigneeRoute(props.report.reportID))
    }}
/>
```
This modification will populate some task details, ensuring that they are displayed correctly even if a user navigates back from the task modification page. More data can be populated similarly to provide a more complete solution.

**Comment by s-alves10** [comment] 2023-06-27 03:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task details(title, description, assignee) don't display when changing assignee

### What is the root cause of that problem?

Task pages use Oynx store(`OYNXKEYS.TASK` and `ONYXKEYS.COLLECTION.REPORT`) to store and retrieve the values.

When creating the task, after calls API(`CreateTask`), task details are merged in the Onyx store(`ONYXKEYS.COLLECTION.REPORT`) and Onyx store(`OYNXKEYS.TASK`) is cleared here
https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/libs/actions/Task.js#L182

After created the task, navigating the task report page shows the [TaskHeader](https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/components/TaskHeader.js)

The title, description, and assignee information are retrieved from the Onyx store(`ONYXKEYS.COLLECTION.REPORT`) as you can see here
https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/components/TaskHeader.js#L50-L51
https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/components/TaskHeader.js#L129

Task information was stored in Onyx store(report) when creating and `TaskHeader` shows the information correctly.

When user goes to the assignee editing modal, task modals use Onyx store(`OYNXKEYS.TASK`) but this store was cleared already when creating the task.
This is the root cause.

### What changes do you think we should make in order to solve the problem?

For case 1, we have to get task information(title, description, assignee) from the report and store them in the Onyx store(`OYNXKEYS.TASK`). We have `useEffect` for this.


```
    useEffect(() => {
        TaskUtils.setTaskReport(props.report);
        TaskUtils.setDetailsValue(props.report.reportName, lodashGet(props.report, 'description', ''));
        const logins = PersonalDetailsUtils.getLoginsByAccountIDs([assigneeAccountID]);
        TaskUtils.setAssigneeValue(lodashGet(logins, 0, ''), assigneeAccountID, '');
    }, [props.report]);
```

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/bb165531-8812-4366-af51-4e8094a1aa78


</details>

### What alternative solutions did you explore? (Optional)

**Comment by ashimsharma10** [comment] 2023-06-27 17:18
Dear contributors,

Are we preventing the task details page on navigating back or are we restoring the taks details ?

**Comment by Nikhil-Vats** [comment] 2023-06-27 17:48
#21705 is the same issue but with the correct expectation. This issue reports the same bug but the expectation, title, etc. are wrong here.

**Comment by ashimsharma10** [comment] 2023-06-27 17:52
I think it's the same root cause. We can either preserve the details on going back . Or restrict going back to details page from asignee

**Comment by jliexpensify** [comment] 2023-06-30 01:15
@allroundexperts we have a few proposals, could you review them?

Also, can I get your thoughts on whether the root cause is related to this other issue? https://github.com/Expensify/App/issues/21909

**Comment by jliexpensify** [comment] 2023-07-01 06:46
Yes, I would think we would want to restore/keep the details as well, it makes the most sense: if all you're doing is changing to a new assignee, then they should see the same task details as the old one.

**Comment by jliexpensify** [comment] 2023-07-01 06:49
However, let me bring this up internally (since there's some debate in this issue https://github.com/Expensify/App/issues/21705).

**Comment by thienlnam** [comment] 2023-07-03 16:35
> I think this is because we’re using the same assignee selector, but in the flow where you edit the assignee - we’re still using Navigation.back() or something which takes you to the last page instead of closing it

Basically, if you're trying to change the assignee the back button should close the modal instead of going back to the details page

**Comment by ygshbht** [comment] 2023-07-03 17:17
Hello @thienlnam, 

I understand that you've updated the issue title from "[$1000] Task details like title, description, assignee don't display when trying to change the assignee" to "Task - Back button doesn't close the RHN when selecting assignee from task report header".

The original issue pertains to task details not populating correctly during the process of changing the assignee for an existing task, which seems different from the current title which addresses the behavior of the back button.

Could you kindly shed more light on your perspective regarding this change? This would greatly aid in aligning our understanding about the core issue at hand.

**Comment by thienlnam** [comment] 2023-07-03 17:32
> @thienlnam I think we also should update the actual and expected result to make this issue clear.

Done

> @ygshbht 

> The original issue pertains to task details not populating correctly during the process of changing the assignee for an existing task

The expected outcome was incorrect here. In this flow, you're done creating the task and are trying to change the assignee. Clicking the back button when deciding to change the assignee from the task screen should not take you back to the 'Edit Task' page. It should close the modal. The same outcome happens when you try to edit the title or description. Hitting the back button closes the modal

**Comment by ygshbht** [comment] 2023-07-04 05:13
@thienlnam ,

Thank you for your response and the clarification. I understand your perspective - the back button behavior should close the modal in the context of changing the assignee, title, or description of an already created task.

However, an additional aspect to consider, and what I believe was the original intent of @kavimuru, is whether the original details (like the existing assignee or title) should be displayed when one attempts to edit these fields. Having these details present might enhance the user experience by providing a reference point to their previous selections.

@kavimuru, could you kindly confirm your intended behavior in this situation? Were you expecting the current details to be displayed when attempting to edit the task details, or was your primary concern around the navigation flow? Your input will help ensure we're addressing the issue accurately.

**Comment by jliexpensify** [comment] 2023-07-04 05:26
@kadiealexander Hello! I'm OOO the next few days so just assigning this in case there's a proposal we want to go with.

There's also an on-going chat around this behaviour with @thienlnam - https://github.com/Expensify/App/issues/21626#issuecomment-1615565003

**Comment by kadiealexander** [comment] 2023-07-05 01:50
The expected behaviour is that the whole modal closes and takes you back to the main task details, this screen should never show:

![image](https://github.com/Expensify/App/assets/59587260/5e5bb848-f7e5-4943-853b-1ef6266567f2)

**Comment by Nikhil-Vats** [comment] 2023-07-05 05:44
This issue can be closed as it is a dupe of https://github.com/Expensify/App/issues/21200 which was created before this one.

**Comment by kadiealexander** [comment] 2023-07-05 05:45
Ah, you're totally right, thank you @Nikhil-Vats! Closing this as a dupe.

**Closed by kadiealexander** 2023-07-05 05:45 UTC
Labels: External, Daily, Help Wanted, Bug
