### ISSUE TITLE
[PAY 16TH MAY][$250] Distance - Amount in confirmation page does not update after changing distance

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41389] opened 2024-05-01 07:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Distance.
4. Enter waypoints A and B.
5. Proceed to confirmation page.
6. Note that the amount is X.
7. Click Distance.
8. Add a waypoint C and save it.

## Expected Result:
The amount in the distance expense confirmation page will update accordingly.

## Actual Result:
The amount in the distance expense confirmation page still shows the previous amount X.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c5caf07c-9b34-452c-b6d5-1efba28d48fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014927ad327a4ee68d</li>
        <li>Upwork Job ID: 1785629574758776832</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-05-01 07:44
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-01 07:44
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-05-01 07:45
Production

https://github.com/Expensify/App/assets/115492554/87f76e3a-29cb-4266-a584-ef23e074db25

**Comment by cretadn22** [comment] 2024-05-01 09:08
This is regression from this PR https://github.com/Expensify/App/pull/40307

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount field isn't updated when updating waypoint list

### What is the root cause of that problem?
We utilize TransactionUtils.getDistance(transaction) to obtain the distance for computing the amount. However, when modifying the waypoint, transaction?.comment?.customUnit?.quantity remains unchanged, resulting in the amount field not being updated.

### What changes do you think we should make in order to solve the problem?
When updating the waypoint list, it's also necessary to ensure that transaction?.comment?.customUnit?.quantity is updated accordingly.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jjcoffee** [comment] 2024-05-01 14:44
@cretadn22's [proposal](https://github.com/Expensify/App/issues/41389#issuecomment-2088186951) makes sense to me!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by neil-marcellini** [comment] 2024-05-01 15:49
Ah woops, thanks for finding the problem and a good solution @cretadn22. I'll assign you now to get this moving. @grgia please feel free to re-assign to me, or I'm happy for you to manage it if you prefer.

**Comment by jjcoffee** [comment] 2024-05-14 10:51
Looks like automation failed here, this hit [production](https://github.com/Expensify/App/pull/41430#issuecomment-2101803528) May 9, so payment is due May 16. @jliexpensify

**Comment by jliexpensify** [comment] 2024-05-15 00:10
Thanks @jjcoffee! Does a checklist need to be completed?

Payment Summary

- C+: @jjcoffee $250

[Upwork job](https://www.upwork.com/jobs/~014927ad327a4ee68d)

**Comment by jliexpensify** [comment] 2024-05-15 02:35
@cretadn22 hmm apologies, I didn't see that you were invited to the Upworks job so I assumed you were from one of the agencies. 

Are you Nguyen T.?

Can you also add your full name to your GH, so we can easily view and invite you? Thanks!

**Comment by jliexpensify** [comment] 2024-05-15 02:54
Offer sent, please add your name to your GH profile - thanks!

**Comment by jjcoffee** [comment] 2024-05-15 09:31
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40307
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40307/files#r1601300483
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any workspace chat
2. Go to + > Submit expense > Distance.
3. Enter waypoints A and B.
4. Proceed to confirmation page.
5. Note the amount displayed
6. Click Distance
7. Add a waypoint C and save it
8. Confirm that the amount updates correctly on the confirmation screen

Do we agree 👍 or 👎

**Comment by neil-marcellini** [comment] 2024-05-16 18:44
Thanks for cleaning up after me! 😅

**Comment by jliexpensify** [comment] 2024-05-16 23:55
Paid and job closed.

**Closed by jliexpensify** 2024-05-16 23:55 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
