### ISSUE TITLE
[Payment due 2024-05-30][$250] [Held requests] Held expense button includes the word expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40831] opened 2024-04-23 21:28 UTC
<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by Nodebrute** [comment] 2024-04-23 21:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Held expense button includes the word expense
### What is the root cause of that problem?
We are using hold expense in en.ts file
https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/languages/en.ts#L714-L715
### What changes do you think we should make in order to solve the problem?

We can change these transalations to hold/unhold and remove expense from here. 
https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/languages/en.ts#L714-L715
We should also update spanish translation
### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2024-04-26 21:02
This one is on my testing list, I should have an update soon.

**Comment by alexpensify** [comment] 2024-04-29 23:38
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment] 2024-05-02 18:27
I've tried testing and unable to submit an expense in a test account. My other account doesn't have the hold option, so I reached out in Slack to clarify.

**Comment by alexpensify** [comment] 2024-05-02 18:32
@rushatgabhane can you please confirm if one of the proposals will fix this issue? Thanks!

**Comment by rushatgabhane** [comment] 2024-05-02 18:38
yes @ZhenjaHorbach's proposal would fix the issue - https://github.com/Expensify/App/issues/40831#issuecomment-2073500307

🎀👀🎀

**Comment by alexpensify** [comment] 2024-05-07 19:01
@rushatgabhane - it looks like the PR is ready for your review. Keep me posted if you are unable to help. Thanks!

**Comment by alexpensify** [comment] 2024-05-13 21:53
Thank you, looks like we are moving along here.

**Comment by alexpensify** [comment] 2024-05-14 22:29
@ZhenjaHorbach - looks like there was an issue with Upwork. Please apply here: https://www.upwork.com/jobs/~0176380086c55565e5

Thanks!

**Comment by alexpensify** [comment] 2024-05-15 22:33
Payouts due: TBD

- [ ] Contributor: $250 @ZhenjaHorbach - I accidentally paid early and we need to keep this GH open until the 7 day mark
- [ ] Contributor+: $250 @rushatgabhane - please submit a request via Chat when the PR goes into prod, thanks! 

Upwork job is [here](https://www.upwork.com/jobs/~0176380086c55565e5).

**Comment by alexpensify** [comment] 2024-05-15 22:34
Flagging that I started the Upwork process early, but we need to wait for this one to go into production. This was a manual error when I was working through other 2024-05-15 due dates.

**Comment by alexpensify** [comment] 2024-05-17 15:19
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@kadiealexander - I've already completed the payment process in Upwork by mistake. That said, I need help watching over this one to ensure there is no regression while I'm OOO. When this does go into production, we can close it after the 7-day period. Thanks!

**Comment by rushatgabhane** [comment] 2024-05-21 06:53
no action needed. pending prod deployment

**Comment by alexpensify** [comment] 2024-05-28 23:24
I'm back online and moving back to Weekly.

**Comment by alexpensify** [comment] 2024-05-28 23:30
I've updated the summary here: 

https://github.com/Expensify/App/issues/40831#issuecomment-2113592522

@rushatgabhane - please send a request in Chat - Thanks!

**Closed by alexpensify** 2024-05-28 23:30 UTC
Labels: Reviewing, External, Daily, Bug
