### ISSUE TITLE
[$1000] Web - App is frozen when searching for currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22533] opened 2023-07-09 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Open Setting
3. Click Default currency
4. Search any thing eg: USD

## Expected Result:
The application works properly when searching currency

## Actual Result:
Observed that after pressing the app key the app is frozen and unresponsive.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a214b5fb-1fab-40c6-b299-3a22f4006277

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688895256590139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7ba75a40ba4eb47</li>
        <li>Upwork Job ID: 1678809867787522048</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-10 12:00
@namhihi237 can you confirm if the condition for this to occur is specifically when you create a new workspace, or does it happen on existing workspaces too if you complete steps 2-4? Thanks

**Comment by laurenreidexpensify** [comment] 2023-07-10 14:56
I can reproduce this but I want to confirm first whether keyboard search is expected behaviour for this.

**Comment by brightmanforever022** [comment] 2023-07-10 16:43
Hello, I tried to reproduce this issue but I can't reproduce this issue.
It does work for me properly on my mac.
Can you try one more and let you know please.
I want to work on this issue as my first issue task on this team.
@laurenreidexpensify  @namhihi237 

https://github.com/Expensify/App/assets/99243239/620e6e9d-5c9c-431a-83d7-2bd9d557af69

**Comment by sobitneupane** [comment] 2023-07-14 04:37
Waiting for proposal

**Comment by brightmanforever022** [comment] 2023-07-17 17:15
Hi.
I am trying to reproduce this issue but everything works perfectly for me and I can't reproduce.
Can you try to reproduce this issue one more?

**Comment by brightmanforever022** [comment] 2023-07-17 23:29
I want to reproduce this issue and fix it but I can't reproduce it.
Can you show me on my local this issue for 10 seconds? I can wait for you anytime.
@namhihi237 @laurenreidexpensify @sobitneupane

**Comment by sobitneupane** [comment] 2023-07-21 03:15
@laurenreidexpensify Can you still reproduce the issue? I was unable to reproduce.

**Comment by laurenreidexpensify** [comment] 2023-07-21 17:25
agree no longer reproducible. Closing

**Closed by laurenreidexpensify** 2023-07-21 17:25 UTC
Labels: External, Daily, Help Wanted, Bug
