### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Android - Chat - Starting chat with specific number, user directed to hmm it's not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38879] opened 2024-03-23 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4447645
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab --- start chat
3. Enter +79585702746 and select the contact

## Expected Result:
Starting chat with specific number, user must be directed to specific contact page

## Actual Result:
Starting chat with specific number, user directed to hmm it's not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2393f461-521a-4a9f-bfd9-32097bb6f89e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f0c32c8537d50a1</li>
        <li>Upwork Job ID: 1772777450410250240</li>
        <li>Last Price Increase: 2024-04-03</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-23 14:42
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-23 14:43
We think that this bug might be related to #vip-vsp

**Comment by jayeshmangwani** [comment] 2024-03-28 13:05
@suneox In Android and iOS , If I start chat with the `+79585702746` , i am not able to see not here page instead I can see loading 
 skeletons only

**Comment by jayeshmangwani** [comment] 2024-03-28 14:07
@nkdengineer Thanks for the proposal, your proposal makes sense, I have few questions :

1. In web its working fine and issue is only in mWeb and native devices,  so whats the RCA that issue in only in mobile devices ?
2. It looks like that `shouldFetchReport` being called one more extra time in mobile devices then web, that causing this issue, so rather then adding the `isLoadingInitialReportActions` to `shouldFetchReport` function, can we prevent the `shouldFetchReport` function's extra rendering in mobile devices ?

**Comment by nkdengineer** [comment] 2024-03-28 14:58
> In web its working fine and issue is only in mWeb and native devices, so whats the RCA that issue in only in mobile devices ?

@jayeshmangwani I can reproduce this issue on desktop web too, what behavior do you observe there?

**Comment by jayeshmangwani** [comment] 2024-03-28 15:04
https://github.com/Expensify/App/assets/35371050/40c97278-d5d0-4a7a-a9d9-8bad809bf263

@nkdengineer This is the behaviour I am getting in the latest code, let me know if you have different outcome

**Comment by jayeshmangwani** [comment] 2024-03-28 15:38
> @jayeshmangwani I can reproduce this issue on desktop web too, what behavior do you observe there?

@nkdengineer Would you upload a video of your desktop web outcome ?

**Comment by nkdengineer** [comment] 2024-03-28 16:08
> @nkdengineer Would you upload a video of your desktop web outcome ?

@jayeshmangwani Here it is:

https://github.com/Expensify/App/assets/161821005/0ee7cfb2-98fc-4008-b196-46f25319bd67

I think the reason why it's sometimes reproducible, sometimes not is because when network is fast, the `openReport` returns with `createChat` error before the next `openReport` runs, and we already have the check to avoid `openReport` again if there's `createChat` error, inside `shouldFetchReport`

**Comment by nkdengineer** [comment] 2024-03-28 16:10
> For https://github.com/Expensify/App/issues/38879#issuecomment-2023031781the RCA and solution the same with my proposal

@suneox To be fair, your proposal at most only fixes 1/2 of the issue. The chat header is skeleton loading indefinitely in your own attached POC screenshot.

cc @jayeshmangwani

**Comment by jayeshmangwani** [comment] 2024-03-29 07:49
@lanitochka17 Can we please test this issue again again , does QA team is still able to reproduce this issue ?

**Comment by nkdengineer** [comment] 2024-03-29 09:26
> @lanitochka17 Can we please test this issue again again , does QA team is still able to reproduce this issue ?

@jayeshmangwani Are you not able to reproduce the issue now?

Please note there's the infinite loading chat header as well, that's definitely still reproducible in all platforms.

**Comment by jayeshmangwani** [comment] 2024-03-29 10:00
No I am not able to reproduce the mentioned issue @nkdengineer

**Comment by nkdengineer** [comment] 2024-04-01 14:56
> No I am not able to reproduce the mentioned issue @nkdengineer

@jayeshmangwani  In your posted video [here](https://github.com/Expensify/App/issues/38879#issuecomment-2025447180), the report header is skeleton-loading indefinitely, could you confirm you're still seeing that?

**Comment by jayeshmangwani** [comment] 2024-04-01 14:58
@nkdengineer I am saying is that now I am not able to reproduce original issue that is mentioned in the description 
Neither `hmm it's not here page` nor the `Skeleton Animation for the chat page`

**Comment by nkdengineer** [comment] 2024-04-01 15:06
> @nkdengineer I am saying is that now I am not able to reproduce original issue that is mentioned in the description
Neither hmm it's not here page nor the Skeleton Animation for the chat page

Now I can't reproduce too, seems it's a bit flaky.

We can still move forward to fix the infinite-Skeleton issue in the report header, it's part of the issue here.

What do you think?

**Comment by nkdengineer** [comment] 2024-04-02 06:05
> Yes, if the header is only loading infinitely, then we should fix the header part in this issue.

@jayeshmangwani [My proposal](https://github.com/Expensify/App/issues/38879#issuecomment-2023031781) already covered that case, we can move forward here 🚀

**Comment by jayeshmangwani** [comment] 2024-04-02 11:22
@nkdengineer Right now, when we start a chat with an invalid number, we can see the header infinitely and on LHN, we can see the chat, and when we go to another chat then the invalid number chat will disappear from the LHN, ad you stated in Proposal, if we remove the block of code that reset the personal details to null, then Do LHN chat will disappear or not when we go to the other chat?

I am attaching a video here of the current version of working with invalid chat.

https://github.com/Expensify/App/assets/35371050/0beaa5f1-8cbc-4412-b5ce-79b741dcb0e5

**Comment by nkdengineer** [comment] 2024-04-02 15:38
> if we remove the block of code that reset the personal details to null, then Do LHN chat will disappear or not when we go to the other chat?

@jayeshmangwani The behavior will still be the same as it is now, the LHN chat will disappear when we go to the other chat. Just that the infinite skeleton loading in the chat header is now fixed.

**Comment by jayeshmangwani** [comment] 2024-04-03 16:27
We are not able to reproduce the original issue that is described in the description; now, we only see the infinite loader for the header of the invalid user's(number) chat, and @nkdengineer 's [Proposal](https://github.com/Expensify/App/issues/38879#issuecomment-2023031781) will solve the header issue; we can do it with the proposal.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-04-04 09:34
@jayeshmangwani The PR is [here](https://github.com/Expensify/App/pull/39585).

**Comment by bfitzexpensify** [comment] 2024-04-23 16:04
Switching this to daily to action on Thursday. 

@nkdengineer I sent an offer to you via Upwork. 

@jayeshmangwani please complete the BZ checklist - thank you!

**Comment by jayeshmangwani** [comment] 2024-04-23 16:43
@bfitzexpensify I will complete the checklist tomorrow

**Comment by jayeshmangwani** [comment] 2024-04-24 17:02
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22612
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22612/files#r1578208405
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:  **The discussion is not needed here. This issue can be caught in testing when we start chatting with the invalid user.**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open App > Press FAB > Start chat
2. Enter invalid phone number, i.e +79585702746
3. After opening the report, verify that the error appears and the header doesn't display skeleton
4. Clear the error
5. Press FAB > Start chat again
6. Verify that the phone number that we entered above doesn't appears as recent contact

Do we agree 👍 or 👎

**Comment by bfitzexpensify** [comment] 2024-04-25 00:47
Thanks @jayeshmangwani - proposed those steps be added via https://github.com/Expensify/Expensify/issues/390645. 

Payment will be completed tomorrow. 

@nkdengineer a reminder to accept the Upwork job offer.

**Comment by bfitzexpensify** [comment] 2024-04-26 13:52
Payment to @jayeshmangwani complete. Bumping @nkdengineer in Slack again so we can close this out.

**Comment by nkdengineer** [comment] 2024-04-26 19:11
@bfitzexpensify Thanks for bumping, I accepted the offer 🙏

**Comment by bfitzexpensify** [comment] 2024-04-26 19:35
Thanks! Payments complete. Closing this out

**Closed by bfitzexpensify** 2024-04-26 19:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
