### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Request - Merchant and category rows disappear in the confirmation page after adding receipt

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33588] opened 2023-12-26 13:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to workspace chat > + > Request money .
2. Go to Manual > Enter amount > Next.
3. Click 3-dot menu > Add receipt.
4. Add a receipt.

## Expected Result:
Merchant and category rows will not disappear in the confirmation page,

## Actual Result:
Merchant and category rows disappear in the confirmation page,

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a1dc8a24-2174-4f81-b471-d76019a4ddb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179ee4404d0db5b5f</li>
        <li>Upwork Job ID: 1739641592076816384</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-26 14:02
This is a regression from https://github.com/Expensify/App/pull/30721

**Comment by paultsimura** [comment] 2023-12-26 14:26
@aimane-chnaif this is expected for the Scan requests since the values are auto-generated there.
A manual request with an attached receipt does not behave like a Scan, therefore it should be allowed to enter these fields there. Was this specific case discussed in the PR?

**Comment by paultsimura** [comment] 2023-12-26 14:38
Yes, and this was the [response](https://github.com/Expensify/App/pull/30721#issuecomment-1863329128) from @youssef-lr:

> SmartScan should take care of those fields and not the user

We don't initiate the SmartScan process for in this case, do we? I think there was a misunderstanding in that discussion, otherwise the SmartScan shouldn't have been mentioned. Please correct me if I'm wrong.

**Comment by mountiny** [comment] 2023-12-26 22:36
Removing the blocker, I agree this can be closed but assigning @youssef-lr to confirm

**Comment by youssef-lr** [comment] 2023-12-27 05:13
Hmm I missed this case, I think we should keep the date & merchant field if the receipt is added from a manual tab. @JmillsExpensify do you agre?

**Comment by paultsimura** [comment] 2023-12-27 09:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The date & merchant fields are missing on the Confirmation step.

### What is the root cause of that problem?
The `shouldShowSmartScanFields` is set incorrectly: we assume the SmartScan will be initiated when the transaction has a receipt, but when it's a manual request with a receipt attached, the SmartScan will not take place, and the hidden fields will not be filled.

https://github.com/Expensify/App/blob/283dc3e5cdc77e230aff3406b37317fc0b1c0439/src/pages/iou/request/step/IOURequestStepConfirmation.js#L350

### What changes do you think we should make in order to solve the problem?
We should change this condition to check whether the IOU request is a Scan, since the SmartScan will be initiated only for this type of requests:

```js
shouldShowSmartScanFields={requestType !== CONST.IOU.REQUEST_TYPE.SCAN}
```



### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-12-27 11:54
@youssef-lr I think it really depends whether we run the smartscan or not in this case, if we do we should remove it imho

**Comment by youssef-lr** [comment] 2023-12-29 15:36
>I think it really depends whether we run the smartscan or not in this case, if we do we should remove it imho
Agreed @mountiny, let's wait for some input from @JmillsExpensify and @trjExpensify as well

**Comment by JmillsExpensify** [comment] 2023-12-30 05:31
If it's a paid workspace, so Collect or Control, we always scan the receipt after the fact in the background. It does matter if the user opts to scan or manually attaches a receipt. That said, can I get an updated summary on what we're discussing?

**Comment by mountiny** [comment] 2023-12-31 09:40
The question in here is:

Is the manual request where you post-add a receipt and the confirmation screen equivalent of just straight up scanning a receipt? Hence should the fields at the confirmation page be same for both flows - when we add a receipt to the manual request we hide category and merchant as those will be filled with smartscan

**Comment by youssef-lr** [comment] 2024-01-02 22:04
@mountiny to answer your question though, if we send a receipt and an amount it won't be scanned, because the transaction is not considered partial anymore

**Comment by trjExpensify** [comment] 2024-01-03 11:02
>Is the manual request where you post-add a receipt and the confirmation screen equivalent of just straight up scanning a receipt? Hence should the fields at the confirmation page be same for both flows - when we add a receipt to the manual request we hide category and merchant as those will be filled with smartscan

@mountiny can you restate the question please, you mention hiding category here so I'm a bit confused.

**Comment by mountiny** [comment] 2024-01-04 15:14
1. You start creating manual request
2. you are in the confirmation page
3. you have merchant and category there
4. you add receipt at this point

Should the merchant and category field dissapear since this would be Smartscan now?

**Comment by youssef-lr** [comment] 2024-01-04 15:16
@mountiny I think it's `merchant` and `date`, category always remains as we don't smartscan it, right?

**Comment by youssef-lr** [comment] 2024-01-04 15:20
>if we send a receipt and an amount it won't be scanned, because the transaction is not considered partial anymore

Correction here, transaction needs both a merchant and an amount set to be considered not partial. So I think if **both** are supplied along with a receipt, it won't get scanned.

https://github.com/Expensify/Web-Expensify/blob/d2d76c62e7b2f46a97effe36c96fbe52e2abd218/lib/Hit.php#L683

**Comment by mountiny** [comment] 2024-01-04 15:32
Ok that seems about right, however i think in this case we are discussing if we should smartscan it or not/ if the manual request with added receipt should be equivalent of just scanning a receipt?

**Comment by youssef-lr** [comment] 2024-01-04 15:59
One use case I'm thinking of is someone might want to add a receipt and also amount/merchant because they believe the receipt is not much readable, or they want the amount to show up right away. Hiding the fields afterwards will make the user submit then head to the transaction to fill in the details.

**Comment by mountiny** [comment] 2024-01-04 16:43
> One use case I'm thinking of is someone might want to add a receipt and also amount/merchant because they believe the receipt is not much readable, or they want the amount to show up right away (but also keep a receipt included). Hiding the fields afterwards will make the user submit then head to the transaction to fill in the details.

I think we wanted to go the other way, basically streamline the scan flow as much as possible so the user does not have to think about anything like this, they can add it post creation if they think its non-readable but we should just let them see if it fails as most of the time it should succeed

@trjExpensify @JmillsExpensify I think you have been involved in these convos so curious for your take

**Comment by trjExpensify** [comment] 2024-01-05 01:29
Thanks for clarifying what we're talking about with [this numbered flow](https://github.com/Expensify/App/issues/33588#issuecomment-1877260910), super helpful. 

As a recap, on OldApp here's what we do: 

1. + > manually create 
2. All fields are visible 
3. Attach a receipt via the empty state thumbnail
4. Merchant field is still visible and required to proceed with creating the expense
5. Hit save
6. SmartScan doesn't appear to be initiated on the front-end to the user (i.e SmartScanning....), it's only SmartScan'd in the background as part of the "Concierge DoubleCheck" audit feature to highlight if anything on the manually entered expense is different than read by SmartScan for admins. 

So from a UX standpoint; the user has manually created an expense, filled out the details manually, and attached a receipt image manually as well. I don't see why we need to change that in NewDot really. If you went the `Manual` route you don't expect the `Scan` process to be initiated. 

With that then; 

1. Global Create > Request Money > Manual
2. Enter an amount > choose a participant 
3. Land on the "Manual" confirmation screen with all fields visible as normal 
4. Attach a receipt manually > stay on the "Manual" confirmation screen with all fields visible as normal, merchant name still required to enter to proceed.
5. Enter a merchant name > request > land in the workspace chat > request does not appear as a "Receipt scan in progress..." whisper as the SmartScan process isn't initiated on the front-end for the user, nor alters any data on the manually entered request even if Concierge DoubleCheck runs for the admin's benefit.

**Comment by mountiny** [comment] 2024-01-05 14:27
Sounds good then!

**Comment by youssef-lr** [comment] 2024-01-10 03:10
I'm going to work on this next week @trjExpensify with your suggested solution.

**Comment by trjExpensify** [comment] 2024-01-23 15:18
👋 @paultsimura are you referring to something in these steps not being accurate/needing clarifying? 

1. Global Create > Request Money > Manual
2. Enter an amount > choose a participant
3. Land on the "Manual" confirmation screen with all fields visible as normal
4. Attach a receipt manually > stay on the "Manual" confirmation screen with all fields visible as normal, merchant name still required to enter to proceed.
5. Enter a merchant name > request > land in the workspace chat > request does not appear as a "Receipt scan in progress..." whisper as the SmartScan process isn't initiated on the front-end for the user, nor alters any data on the manually entered request even if Concierge DoubleCheck runs for the admin's benefit.

**Comment by paultsimura** [comment] 2024-01-23 15:25
I was just a bit confused by the discrepancy between the initial conclusions and the final ones. After re-checking the steps, everything's clear 👌

**Comment by JmillsExpensify** [comment] 2024-01-24 03:11
Sounds great, thanks Tom for helping push this one along!

**Comment by getusha** [comment] 2024-01-25 17:28
@trjExpensify @JmillsExpensify, what's the next step here, should i post this on slack to get proposals?

**Comment by paultsimura** [comment] 2024-01-25 18:37
@getusha AFAIU, it's being worked on internally: https://github.com/Expensify/App/issues/33588#issuecomment-1884122408

**Comment by getusha** [comment] 2024-01-25 18:49
Thanks @paultsimura, i missed that.

**Comment by JmillsExpensify** [comment] 2024-01-31 03:30
Still in Youssef's queue

**Comment by trjExpensify** [comment] 2024-01-31 16:59
@youssef-lr are you still good to take this on? Resurfaced [here](https://expensify.slack.com/archives/C02MW39LT9N/p1706720193381839?thread_ts=1706717450.983399&cid=C02MW39LT9N) recently with internal testing!

**Comment by youssef-lr** [comment] 2024-01-31 17:49
@JmillsExpensify @trjExpensify going to send a PR this week.

**Comment by trjExpensify** [comment] 2024-01-31 18:01
Nice, thanks!

**Comment by youssef-lr** [comment] 2024-01-31 18:02
@paultsimura I think with your proposal the receipt will still show up as being scanned.

**Comment by paultsimura** [comment] 2024-01-31 18:15
> @paultsimura I think with your proposal the receipt will still show up as being scanned.

@youssef-lr It won't, here's the recording:

https://github.com/Expensify/App/assets/12595293/ab126a20-8461-40db-8865-e009dce39ced

**Comment by youssef-lr** [comment] 2024-02-01 18:26
Ah right, `replaceReceipt` already marks the state as OPEN. Sounds good then.

**Comment by paultsimura** [comment] 2024-02-02 00:14
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35599

**Comment by JmillsExpensify** [comment] 2024-02-15 15:58
Updated the payment summary above. There are no auto-contracts for this issue, so I'm creating those now.

**Comment by getusha** [comment] 2024-02-15 17:15
[@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30721
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/30721/files#r1491344743
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a this is a special case that was missed by the PR author.**
 [@getusha] Determine if we should create a regression test for this bug. **Yes**
 [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open any workspace chat > + > Request money
2. Select Manual > Enter any amount > Next
3. Click top right menu icon > Add receipt
4. Upload a receipt
5. Verify that fields such as `date` and `merchant` are present and remain unchanged from their state prior to uploading the receipt.
6. Add a value to merchant field > Request money
8. Verify the created request doesn't start the SmartScan process

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-02-15 20:34
Everyone paid out and the regression test has been added. Closing this one!

**Closed by JmillsExpensify** 2024-02-15 20:34 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
