### ISSUE TITLE
[$250] Workspace - Submit button loads infinitely and is not deactivated while offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46865] opened 2024-08-06 09:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bezawitgebremichael+r@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on settings and navigate to workspace
3. Create a new workspace
4. Go back and navigate to subscription page
5. Click on "Request early cancellation" (http://new.expensify.com/settings/subscription/request-early-cancellation-survey)
6. Disconnect from the internet
7. Select on one of the radio buttons
8. Write something inside the input field with the placeholder "Your response"
9. Click on the submit button

## Expected Result:
When going offline the submit button becomes deactivated as this is the normal behavior in other places of the app.

## Actual Result:
After going offline the submit button does not get deactivated and is clickable, when clicked it loads infinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/96970e74-b3bf-44db-bd8d-bf15f9372672

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0ba7134ea0d5d07</li>
        <li>Upwork Job ID: 1821841069474712472</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103622533</li>
<li>Krishna2323 | Contributor | 103622534</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by etCoderDysto** [comment] 2024-08-06 10:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Submit button loads infinitely and is not deactivated while offline
### What is the root cause of that problem?
We are enabling the button in offline mode here
https://github.com/Expensify/App/blob/d7c6bca4cce86dbbd3c90f57895f363ef8e6a587/src/components/FeedbackSurvey.tsx#L110-L115
### What changes do you think we should make in order to solve the problem?

We should remove enabledWhenOffline prop
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-08-12 20:20
reviewing

**Comment by situchan** [comment] 2024-08-13 02:39
> When going offline the submit button **becomes deactivated**

@miljakljajic can you please confirm the expected result is correct?

**Comment by miljakljajic** [comment] 2024-08-21 10:13
Yes @Krishna2323 that is the expected pattern (see UX patterns here: https://stackoverflowteams.com/c/expensify/questions/12847)

**Comment by situchan** [comment] 2024-08-21 15:34
Thanks for confirmation @miljakljajic, though contributors don't have access to SO)
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/46865#issuecomment-2270910278) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by situchan** [comment] 2024-08-22 06:36
@daledah watching your video, I am not sure what that case is. Can you please share repro step?
Btw, please prioritize [this PR](https://github.com/Expensify/App/pull/47687)

**Comment by situchan** [comment] 2024-08-22 20:11
@daledah thanks for reporting. It's a separate bug.
What we're fixing here is wrong offline pattern, while what you reported is online case.

**Comment by situchan** [comment] 2024-09-10 07:28
⚠️ We got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the [PR](https://github.com/Expensify/App/pull/47813) of this issue was only deployed to **production** on Aug 30 in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-06]** according to Aug 30's production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

**Comment by aldo-expensify** [comment] 2024-09-10 18:56
Sounds good, thanks for finding that @situchan. I understand that we are past the payment date then, correct?

**Comment by situchan** [comment] 2024-09-10 18:57
> I understand that we are past the payment date then, correct?

correct

**Comment by aldo-expensify** [comment] 2024-09-10 19:59
I think this may explain the missing `Deployed to production` comment: https://expensify.slack.com/archives/C01GTK53T8Q/p1725066007454299

**Comment by miljakljajic** [comment] 2024-09-12 15:18
I'll get this paid!

**Comment by miljakljajic** [comment] 2024-09-12 15:20
Both contributors paid and contracts ended - closing out

**Closed by miljakljajic** 2024-09-12 15:20 UTC
Labels: External, Weekly, Awaiting Payment, Bug
