### ISSUE TITLE
[$500] Tag  - "Missing tag" error appears & disappears when change Category on created request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37644] opened 2024-03-01 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+gmcategory2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot
- "People must tag expenses" option is disabled by Admin
1. As employee navigate to Workspace chat> +> Request money> Manual
2. Add amount> Select Category and add Merchant> Complete the flow
3. Go to created IOU detail page
4. Edit Category section and add new category

## Expected Result:
Selected category should be displayed and no error messages should occur

## Actual Result:
"Missing tag" error message appears and disappears when change Category on created Manual request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eb759c2d-28ea-4aed-a39f-bfffbef1e677

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd47387167e68ba4</li>
        <li>Upwork Job ID: 1763729758329421824</li>
        <li>Last Price Increase: 2024-03-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-01 21:10
We think that this bug might be related to #wave36
CC @greg-schroeder

**Comment by lanitochka17** [comment] 2024-03-01 21:10
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by s77rt** [comment] 2024-03-02 01:41
Not able to reproduce


https://github.com/Expensify/App/assets/16493223/70ca941c-abcc-4661-92e2-cbfefd199e27

**Comment by omarnagy91** [comment] 2024-03-03 15:23
## Proposal

### Problem:

When  creating  a  manual  expense  request,  if  the  user  edits  the  category  after  initial  submission,  a  "Missing  tag"  error  briefly  flashes  even  though  the  "People  must  tag  expenses"  setting  is  disabled.

### Root  Cause:

The  issue  is    caused  by  incorrect  validation  logic  in  the  hasMissingSmartscanFields  function  or  the  getViolationsOnyxData  function.  These  functions  is  incorrectly  triggering  the  "Missing  tag"  error  even  when  the  policy  does  not  require  tags.

### Proposed  Changes:

**Modify  the  validation  logic  in  the  hasMissingSmartscanFields  function:**

```
function hasMissingSmartscanFields(transaction: OnyxEntry<Transaction>): boolean {
    const parentReport = allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${transaction?.reportID}`] ?? null;
    const policy = ReportUtils.getPolicy(parentReport?.policyID ?? '');

    // Only check for missing tags if the policy requires them
    if (policy?.requiresTag) {
        return TransactionUtils.getTag(transaction) === '';
    }

    // Otherwise, only check for missing amount, date, and merchant
    return TransactionUtils.areRequiredFieldsEmpty(transaction);
}
```



This  change  ensures  that  the  "Missing  tag"  error  is  only  triggered  when  the  policy  actually  requires  tags.

**Alternatively,  modify  the  getViolationsOnyxData  function:**

If  the  issue  is  in  the  getViolationsOnyxData  function,  you  would  need  to  modify  the  logic  that  checks  for  missing  tags  to  also  consider  the  policy  requirements.

### Alternative  Solutions:

Another  possible  solution  could  be  to  investigate  the  state  management  in  the  MoneyRequestView  component  to  see  if  there  is  a  problem  with  how  the  state  is  being  updated  when  the  category  is  changed.  However,  based  on  the  information  provided,  fixing  the  validation  logic  seems  like  the  most  likely  solution.

By  implementing  the  proposed  changes,  we  can  ensure  that  the  "Missing  tag"  error  is  only  displayed  when  it  is  truly  required  by  the  policy,  preventing  confusion  and  improving  the  user  experience.

**Comment by s77rt** [comment] 2024-03-03 16:54
@omarnagy91 Thanks for the proposal. Were you able to reproduce the bug? Seeing this is a deploy blocker, were you able to find the offending PR?

**Comment by omarnagy91** [comment] 2024-03-03 19:29
@s77rt 
I can't find the offending PR through git bisect yet 
I was able to reproduce the bug

**Comment by omarnagy91** [comment] 2024-03-03 19:31
@s77rt 
could you please provide me with any specifics you need about the issue ?

**Comment by s77rt** [comment] 2024-03-04 05:40
@omarnagy91 I'm still unable to reproduce. I can't validate the root cause but seeing this is a deploy blocker and no recent changes to `hasMissingSmartscanFields`, it's probably not the root cause and something broke somewhere else.

**Comment by omarnagy91** [comment] 2024-03-04 13:35
@s77rt 
commit 631d206773ca38ccf01e5e3d75297025dc4f2e9f
Author: dukenv0307 <dukenv0307@gmail.com>
Date:   Fri Feb 23 13:38:18 2024 +0700

    fix replace hasMissingRequiredFields by hasMissingSmartscanFields
  I think this is the commit

**Comment by omarnagy91** [comment] 2024-03-04 13:57
@s77rt 
should I update my proposal 
I should just add the requiresTag code to it and It's complete  
what's your comment ?

**Comment by omarnagy91** [comment] 2024-03-04 14:15
commit caa025bb01c10a9a0ef592ff018f4266f024de22
Author: dukenv0307 <dukenv0307@gmail.com>
Date:   Tue Feb 6 11:49:24 2024 +0700

    fix error message disappear

**Comment by omarnagy91** [comment] 2024-03-04 14:45
@s77rt it's one of those three commits I am still analyzing everything 
I am just doubtful that's why I provided all three 
commit 02296e884a636fa8772b27013ec52878ea059af7
Author: VickyStash <vikstash@gmail.com>
Date:   Tue Jan 16 12:42:24 2024 +0100

    Migrate MoneyRequestView to TypeScript

**Comment by omarnagy91** [comment] 2024-03-04 15:53
**Proposal**

**Problem:**

The "Missing tag" error occurs in the `MoneyRequestView.tsx` component within a specific code context. This error disrupts the user experience because the application attempts to display and interact with tag-related data that may not exist within certain transactions.

**Root Cause:**

The `shouldShowTag` calculation incorrectly determines that the tag section in the UI should be displayed, even when the `transaction` object lacks a valid tag field. The logical flaw lies in this line of code:

JavaScript

```
const shouldShowTag = isPolicyExpenseChat && (transactionTag || OptionsListUtils.hasEnabledTags(policyTagLists));

```


**Proposed Changes:**

To resolve this issue, the `shouldShowTag` logic should be revised to ensure that a meaningful `transactionTag` value exists before determining if the tag section should be rendered. Below is the corrected code:

JavaScript

```
const shouldShowTag = isPolicyExpenseChat && 
                      (transactionTag !== undefined && transactionTag === '' && 
                      OptionsListUtils.hasEnabledTags(policyTagLists));

```



**Explanation of Changes:**

The fix explicitly checks that `transactionTag` is not undefined and is not an empty string, guaranteeing a valid value before proceeding with the logical OR operation.

**Alternative Solutions Explored:**

1.  **Downstream Error Handling:** I considered adding error handling within the `getViolationsForField('tag')` function to handle cases where the 'tag' field is missing. However, this is a reactive solution and doesn't directly address the root cause.
    
2.  **Data Consistency:** The possibility of ensuring consistent data and always providing a 'tag' field (even an empty one) upstream was explored. While ideal, this might require broader changes and coordination beyond the immediate scope of the issue.

**Comment by s77rt** [comment] 2024-03-04 16:46
@omarnagy91 Both https://github.com/Expensify/App/pull/34564 and https://github.com/Expensify/App/pull/35871 are already on production, they can't be the offending PRs.

**Comment by roryabraham** [comment] 2024-03-04 18:32
@deetergp try searching console logs for Onyx and seeing what updates are getting applied? without further investigation my guess would be that the front-end and the back-end aren't in agreement about whether a tag is required. So something like this is happening:

- You take an action to update a category
- the front-end optimistically computes violations and decides that a missing tag is a violation
- you send the request to update the category
- the back-end decides there's no violations and updates Onyx accordingly

**Comment by deetergp** [comment] 2024-03-04 18:37
Since the violations feature is in beta, this does not need to be a blocker. Also, one of our internal engineers has a draft PR going that should address this https://github.com/Expensify/App/pull/37461/files

**Comment by roryabraham** [comment] 2024-03-04 18:39
removing `Help Wanted` and putting this on HOLD for https://github.com/Expensify/App/pull/37461

**Comment by deetergp** [comment] 2024-03-14 15:34
I just requested a retest in our [QA Slack channel](https://expensify.slack.com/archives/C9YU7BX5M/p1710430438081979). I'll report back when I know more.

**Comment by kavimuru** [comment] 2024-03-14 16:35
Tester is still able to reproduce.

https://github.com/Expensify/App/assets/43996225/002660d4-de1b-4e6e-b86c-323aab7b596c

**Comment by s77rt** [comment] 2024-03-18 23:42
@deetergp Let's reopen this. I was able to reproduce, I had to logout and login again. This bug is internal as the BE returns `policy.requiresTag` as true even if it's false in old dot.

<img width="660" alt="Screenshot 2024-03-19 at 12 38 12 AM" src="https://github.com/Expensify/App/assets/16493223/e28792db-35f9-41e1-a8ad-e13528333a9d">

**Comment by deetergp** [comment] 2024-03-27 04:19
I have not had a chance to dig much deeper into this. I hope to get to it before the week is out.

**Comment by deetergp** [comment] 2024-04-03 15:04
Hoping to get to this today.

**Comment by deetergp** [comment] 2024-04-15 17:08
Still have not had a chance to look into this. Hopefully sometime this week.

**Comment by deetergp** [comment] 2024-04-19 00:28
I just retested this on staging and am not able to reproduce. Can anyone else?

**Comment by roryabraham** [comment] 2024-04-19 19:00
@cead22 was this the same as the bug we tried debugging for a few hours on a call about a month ago? I know that one was also inconsistently reproducible, but you also traced the source and fixed it right?

**Comment by cead22** [comment] 2024-04-19 22:19
Yeah this should be fixed

**Closed by cead22** 2024-04-19 22:19 UTC
Labels: Engineering, Weekly, Internal
