### ISSUE TITLE
[$500] [Held requests] System message for hold/unhold request is not gray like other system messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36894] opened 2024-02-20 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Request money from any user
3. Navigate to request details page
4. Edit amount/date/description
5. Click 3-dot menu > Hold request
6. Enter a reason and save it
7. Click 3-dot menu > Unhold request

## Expected Result:
The system message for hold and unhold request should be in gray like other system messages

## Actual Result:
The system message for hold and unhold request is black instead of gray

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e2d44432-e60e-43f2-aa83-a5eebe628394

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d47ff630bf2f2350</li>
        <li>Upwork Job ID: 1759954343597240320</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-20 14:53
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by johnmlee101** [comment] 2024-02-20 16:07
I think this should definitely be fixed, although I don't know if its deploy-blocker worthy.

**Comment by johnmlee101** [comment] 2024-02-20 16:08
@BartoszGrajdek can you take a look at this? 
as part of your PR here https://github.com/Expensify/App/pull/33897

**Comment by BartoszGrajdek** [comment] 2024-02-20 16:29
Yeah, I'll create a fix for that 😄

**Comment by johnmlee101** [comment] 2024-02-20 16:34
Thanks! 🙇

**Comment by trushpatel1** [comment] 2024-02-20 18:44
Project Overview:
I understand that Expensify is transitioning its platform to React Native. The specific issue (#36894) is part of this larger migration effort.

Proposal Details:

Issue Analysis: My initial step will involve a thorough review of the issue as detailed in GitHub issue #36894. This includes understanding the existing challenges and the desired outcomes post-migration.

Technical Solution:

Code Refactoring: The existing code will be refactored for compatibility with React Native, ensuring a smooth transition across platforms.
Testing and Debugging: A comprehensive testing strategy will be employed to identify and resolve any bugs or issues. This includes unit testing for individual components and integration testing to ensure overall app stability.
Performance and Security: Special attention will be paid to maintaining high performance and robust security, especially given the financial nature of the Expensify app.
Documentation and Reporting:

Detailed documentation will be provided, outlining the changes made, reasons for these changes, and any new practices implemented.
Regular updates will be communicated throughout the project duration.
Final Submission:

The completed solution will be submitted via a pull request on the Expensify/App GitHub repository, in accordance with the contributing guidelines. This submission will include screenshots and evidence of testing on all platforms.
Budget and Timeline:

Proposed Fixed Price: $500

**Comment by johnmlee101** [comment] 2024-02-20 21:16
@BartoszGrajdek what's the latest?

**Comment by BartoszGrajdek** [comment] 2024-02-20 21:44
Sorry - too many fixes / other issues to handle at once 😅 

It looks like the change in the draft PR fixes the problem, I need to test it first though

**Comment by robertjchen** [comment] 2024-02-20 22:08
Yep, this is not a deploy blocker- we're looking into this!

**Comment by MonilBhavsar** [comment] 2024-02-21 05:07
Should be fixed by <ReportActionItemBasicMessage

**Comment by BartoszGrajdek** [comment] 2024-02-21 19:46
@MonilBhavsar is right this issue was fixed by https://github.com/Expensify/App/pull/36851 - I didn't have the latest main 

I'll change the PR above into a clean-up since some code is not needed now. Do we still want to create the util function mentioned [here](https://github.com/Expensify/App/pull/36956/files#r1496681904)? I can now delete all [these lines](https://github.com/Expensify/App/blob/c2f8a534b1bf1f21cf3b84162f051f3de2f97a29/src/pages/home/report/ReportActionItemFragment.tsx#L135-L144) so aside from some edge cases all system message styles will be handled [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js), that's why I'm not sure if it's needed now  cc @youssef-lr

**Comment by youssef-lr** [comment] 2024-02-23 01:19
@BartoszGrajdek I think continuing that PR sounds good to, I still think we should clean this up so that we are only handling this logic in one place, [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L463-L472) sounds good.

**Comment by youssef-lr** [comment] 2024-02-26 12:34
Not overdue.

**Comment by youssef-lr** [comment] 2024-02-28 02:21
Reviewing PR today.

**Comment by robertjchen** [comment] 2024-03-01 19:03
Ongoing discussion in PR 👍

**Comment by robertjchen** [comment] 2024-03-12 11:48
Awaiting tests by @youssef-lr (and we also switched focus to partial pay/approve, but will revisit after that is out)

**Comment by youssef-lr** [comment] 2024-03-12 23:45
Sorry haven't got to get back to that PR, but it's really just a clean up of the code now. The issue is fixed.

**Comment by robertjchen** [comment] 2024-03-21 02:33
@youssef-lr let me know how I can help finish this one out? 🙏

**Comment by trjExpensify** [comment] 2024-04-02 10:53
What's the next step on this issue?

**Comment by youssef-lr** [comment] 2024-04-04 22:56
@trjExpensify this is fixed, but we wanted to cleanup the code in the PR instead, so it's not really affecting the product. I'll get back to the PR review tomorrow.

**Comment by trjExpensify** [comment] 2024-04-08 22:16
Great! How's that going?

**Comment by trjExpensify** [comment] 2024-05-07 12:48
Bump on this one. Can we get it done? Thanks!

**Comment by youssef-lr** [comment] 2024-05-07 20:41
I think we can close this for now. The issue is fixed, I'm not sure it's wroth spending time right now on the clean up as it's pretty minor and is not causing any issues. What do you think @trjExpensify?

**Comment by trjExpensify** [comment] 2024-05-07 20:48
I think it's fine to create another issue for it, but we shouldn't forget about drying up the code and avoiding duplicating the logic. Perhaps it can come in-line with the enhanced system message project? CC: @deetergp @dylanexpensify

**Comment by deetergp** [comment] 2024-05-08 17:39
What is it that needs to be cleaned up here?

**Closed** 2024-05-29 16:54 UTC
Labels: Reviewing, Engineering, Weekly
