### ISSUE TITLE
[$1000] Deleted offline message appears at the receiver side for a brief moment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20414] opened 2023-06-07 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot and login with User A
2. Go to a chat with User B
3. Open User B on another web chrome (To reproduce the bug properly, place User A and User B window side by side)
4. From user A, click on force offline and send a message to User B and then delete it, then go online.
5. On User B see that the deleted message appears for a small period of time. (If user A sends a message and deletes it on offline mode, User B shouldn't be able to see it even if its' for a small period of time)
## Expected Result: 
User B should not receive deleted message even if it's for a small period of time
## Actual Result: 
User B receives deleted message for a brief period of time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/19d3ce83-f6ce-4c96-bdbb-4c0f069f8dd4

https://github.com/Expensify/App/assets/43996225/29e590d7-45bd-46e4-9659-29d45ee0e5a7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685872481026039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6f2e8bb760b8eae</li>
        <li>Upwork Job ID: 1666895787077824512</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-06-08 19:51
Sure, I'll throw external on this. I feel like nobody is going to encounter it in real life but I love the polish.

**Comment by twisterdotcom** [comment] 2023-06-12 10:16
@sobitneupane how do we feel about @huzaifa-99's proposal?

**Comment by eh2077** [comment] 2023-06-12 11:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Deleted offline message appears at the receiver side for a brief moment.

### What is the root cause of that problem?

In offline mode, adding a comment and deleting it will send two requests to the backend. 

The root cause of this issue is that, currently, each pusher event is pushed separately, see 

https://github.com/Expensify/App/blob/6035b3e205f737180e9eeb6ab84b3fa984aa2744/src/libs/actions/User.js#L592-L610

So

```jsOnyx.update(pushJSON);
Onyx.update(pushJSON);
```

is called twice for new comment and deleted comment.

### What changes do you think we should make in order to solve the problem?

From method [subscribeToUserDeprecatedEvents](https://github.com/Expensify/App/blob/6035b3e205f737180e9eeb6ab84b3fa984aa2744/src/libs/actions/User.js#L592-L610), we know that we're migrating to the new solution to push events in batch.

The issue https://github.com/Expensify/Expensify/issues/279347 might include more information but it's not open to public. 

**_It looks like this issue should be hold for the migrating to complete._**

I think this issue can be fixed from backend before pushing a batch of events to clients. The backend can merge requests with same `onyxMethod` and `key`.

Or we can also fix it from frontend in `react-native-onyx`. In method [Onyx.update](https://github.com/Expensify/react-native-onyx/blob/5a97bf5282e614b9e9357fb8d620815f0399cef5/lib/Onyx.js#L1183), we can merge responses with same  `onyxMethod` and `key` in batch.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by thienlnam** [comment] 2023-06-13 22:05
Hmm, I think we should close this issue

Basically the problem exists because the command is queued offline and then occurs in order and so the message you see gets created and then deleted. This will happen to anything queued in order like this, and the same replay effect happens when you edit something multiple times offline

This is the kind of thing that would be taken care of in a single swoop if we decided to add handling for this, but I believe our stance on this has been it's fine and not worth handling.  I'm going to close but if that is untrue feel free to re-open

**Closed by thienlnam** 2023-06-13 22:05 UTC
Labels: External, Daily, Help Wanted, Bug, Upwork Automation
