### ISSUE TITLE
Search (Chats) - Extra left and right padding, entire row is not highlighted when hovered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54121] opened 2024-12-13 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/S
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1311020@applause.expensifail.com
**Issue reported by:** Applause - Internal Team
**Component** Chat Report View

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search
3. Go to Chats
4. Hover over any message

## Expected Result:
- Each message item in Chats will not have extra left and right padding
- When hovering over the message, the entire row will be highlighted

## Actual Result:
- Each message item in Chats has extra left and right padding
- When hovering over the message, the entire row is not highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ee6c6f6b-afc4-42bd-87d3-8fcde5e50bc1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-12-13 17:55
Production:

https://github.com/user-attachments/assets/9e2cd9d7-ccb6-4bf9-97e1-69aa3f424508

**Comment by luacmartins** [comment] 2024-12-13 17:57
Potential suspect https://github.com/Expensify/App/pull/53482 @marcochavezf @FitseTLT @mananjadhav

**Comment by FitseTLT** [comment] 2024-12-13 18:00
Yep will take a :eyes: into it please assign me @lucamartins

**Comment by luacmartins** [comment] 2024-12-13 19:12
Thanks @FitseTLT. Let me know if I can help

**Comment by luacmartins** [comment] 2024-12-13 21:48
any luck @FitseTLT?

**Comment by FitseTLT** [comment] 2024-12-13 21:49
still digging will hope fully raise a fix in a few hours 👍

**Comment by FitseTLT** [comment] 2024-12-13 21:50
But confirmed it is caused by my PR

**Comment by luacmartins** [comment] 2024-12-13 23:26
Fix being CPed

**Comment by mananjadhav** [comment] 2024-12-14 04:38
Thanks @luacmartins @FitseTLT. I was offline

**Comment by luacmartins** [comment] 2024-12-16 15:49
Fixed in staging.

**Closed by luacmartins** 2024-12-16 15:49 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
