### ISSUE TITLE
IOU Preview'a shows `owns` status for paid IOU reports after login

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24194] opened 2023-08-07 03:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create DM between user A and B.
2. Login with both on two devices.
3. Send money request from A to B.
4. Pay the request from B to A.
5. Exchange a few messages.
6. Repeat 3-4.
7. Logout both accounts.
8. Login with user A.

## Expected Result:
All pass IOU reports preview should have proper status.

## Actual Result:
Until we open the report, the wrong status is shown on IOU previews.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-5
**Reproducible in staging?:** Needs repro
**Reproducible in production?:** needs repro
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/f378df96-4ffd-4e64-b178-02060fbad314
https://github.com/Expensify/App/assets/43995119/21392285-e792-401d-abb7-657393a5cbc6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690841741048119 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-08-07 20:11
asked question in Slack - the reproduction steps here are unclear, we shouldn't add the needs reproduction label unless the attempted steps have been shared.

**Comment by adelekennedy** [comment] 2023-08-09 05:25
I think this is a dupe of [this issue](https://github.com/Expensify/App/issues/22946) - I'm also unable to reproduce so gonna close this!

**Closed by adelekennedy** 2023-08-09 05:25 UTC
Labels: Daily, Needs Reproduction, Bug
