### ISSUE TITLE
[$250] iOS - Attachment - App crashes when editing comment with video

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46114] opened 2024-07-24 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to DM
3. Type any message (do not send it)
4. Tap + > Add attachment
5. Select a video
6. Send the video
7. Long press on the message with text and video
8. Tap Edit comment

## Expected Result:
App will not crash

## Actual Result:
App crashes on iOS app
Console error shows up on web app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6f95d7bd-c746-4c82-8e1f-6de594d7920f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2f80c595cce99e8</li>
        <li>Upwork Job ID: 1816209661264574315</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103271953</li>
<li>nkdengineer | Contributor | 103271954</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment] 2024-07-24 13:32
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-24 13:33
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-07-25 07:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes on iOS app
Console error shows up on web app

### What is the root cause of that problem?
In https://github.com/Expensify/react-native-live-markdown/blob/ff55579f673c049a6eb6cdf38ffc223315309b07/parser/index.ts#L194, we don't have code to `parseTreeToTextAndRanges` for video tag yet. So it throws error [here](https://github.com/Expensify/react-native-live-markdown/blob/ff55579f673c049a6eb6cdf38ffc223315309b07/parser/index.ts#L195)

### What changes do you think we should make in order to solve the problem?

Add code to `parseTreeToTextAndRanges` for video tag [here](https://github.com/Expensify/react-native-live-markdown/blob/ff55579f673c049a6eb6cdf38ffc223315309b07/parser/index.ts#L194), it's quite similar to [img tag](https://github.com/Expensify/react-native-live-markdown/blob/ff55579f673c049a6eb6cdf38ffc223315309b07/parser/index.ts#L178-L194).

Pseudocode for it:
```
else if (node.tag.startsWith('<video data-expensify-source="')) {
    const src = node.tag.match(/data-expensify-source="([^"]*)"/)![1]!; // always present
    const rawLink = node.tag.match(/data-raw-href="([^"]*)"/);
    const linkString = rawLink ? Utils.unescapeText(rawLink[1]!) : src;
    const attachmentName = node.children?.join('')?.replaceAll('&#32;', ' ');

    appendSyntax('!');
    if (attachmentName) {
      appendSyntax('[');
      processChildren(Utils.unescapeText(attachmentName || ''));
      appendSyntax(']');
    }
    appendSyntax('(');
    addChildrenWithStyle(linkString, 'link');
    appendSyntax(')');
  }
```

### What alternative solutions did you explore? (Optional)

**Comment by MariaHCD** [comment] 2024-07-25 13:27
I am going OOO so I won't be able to see this through completion. @slafortune could you reassign an internal engineer here?

**Comment by MariaHCD** [comment] 2024-07-25 14:15
Actually, @mountiny is willing to take over for me! Thanks!

**Comment by mountiny** [comment] 2024-07-25 22:46
cc @tomekzaw @BartoszGrajdek for visibility

**Comment by nkdengineer** [comment] 2024-07-26 05:16
@ZhenjaHorbach @mountiny  this [PR](https://github.com/Expensify/react-native-live-markdown/pull/440) is ready for review

**Comment by nkdengineer** [comment] 2024-07-26 08:32
This [PR](https://github.com/Expensify/react-native-live-markdown/pull/440) is merged. I'll create PR to bump new version soon

**Comment by nkdengineer** [comment] 2024-08-02 05:33
@ZhenjaHorbach The PR is [here](https://github.com/Expensify/App/pull/46693).

**Comment by slafortune** [comment] 2024-08-13 20:00
This is being worked on, it will have a 7-day regression period, so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by slafortune** [comment] 2024-08-23 17:17
@ZhenjaHorbach and @nkdengineer  - both paid via UpWorks as the C+ and Contributor roles.

**Closed by slafortune** 2024-08-23 17:17 UTC
Labels: Reviewing, External, Weekly, Bug
