### ISSUE TITLE
Web - Refreshing the page while details page is open navigates to a different chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21109] opened 2023-06-20 11:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to Concierge chat
3. Click on header of Concierge to open up the details page on the right hand pane
4. Now refresh the page and notice that the Concierge chat disappears and a different chat is shown. But the details page of Concierge is still present.

## Expected Result:
 Refreshing the page while details page is open should not navigate to a different chat

## Actual Result:
Refreshing the page while details page is open navigates to a different chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/234be5e8-6e97-4cb9-a3a1-b7ec07ebd854

https://github.com/Expensify/App/assets/93399543/d06d0826-68db-40e8-9971-99883964ff2e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686677516367249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2023-06-20 13:37
I think same dupe of this https://github.com/Expensify/App/issues/20780

**Comment by dylanexpensify** [comment] 2023-06-21 13:59
Couldn't repro on chrome, and agree seems to be a dupe. closing

**Closed by dylanexpensify** 2023-06-21 13:59 UTC
Labels: Daily, Bug
