### ISSUE TITLE
Not able to do reply thread with attachments in WS chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20238] opened 2023-06-06 03:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Profile setting
2. Create a new workspace
3. Then go to WS Chat.
4. Send an attachment
5. Try to reply in the thread.
## Expected Result: 
User should be able to  send reply in thread even for attachment thread
## Actual Result: 
Error message appears and not able to reply in thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/00fb26c0-6dfe-441a-b0ff-9cea639fc0d5

https://github.com/Expensify/App/assets/43996225/5ae07355-f9db-4ea4-84cb-5ebde5530982

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685707954067339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119e5938b32c3e46d</li>
        <li>Upwork Job ID: 1676322243091922944</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-06-07 04:56
I just tried to reproduce this issue on Safari 16.5, and I wasn't able to reproduce the issue. Creating the thread in the workspace chat worked perfectly. I'm adding `needs reproduction` and will leave open for a bit before closing it out. 

![Screenshot 2023-06-06 at 22 55 36](https://github.com/Expensify/App/assets/1127863/e46438fd-8451-4609-8494-97057faf6bd4)

**Comment by niravkakadiya25** [comment] 2023-06-07 05:29
Now onwards, Not able to see WS chat except #announcement and #admin @JmillsExpensify 
https://github.com/Expensify/App/assets/100456857/03337470-3da7-429b-8a1c-dec7c6d76b53

**Comment by niravkakadiya25** [comment] 2023-06-07 05:42
@JmillsExpensify Here is it reproduces Steps and video as well
1. Goto Profile setting
2. Create a new WS
3. then go to WS Chat.
4. Send an attechments
5. Try to reply in the thread.

https://github.com/Expensify/App/assets/100456857/5ba427b4-30c4-4afd-bbfe-1276bc8a5fff

**Comment by JmillsExpensify** [comment] 2023-06-08 03:35
Thank you! Got the error this time, and based on the Auth error, I'm going to first triage internally. 

![Screenshot 2023-06-07 at 21 34 24](https://github.com/Expensify/App/assets/1127863/0edd92e6-5f03-4d52-b6f3-154980de6b8a)

**Comment by JmillsExpensify** [comment] 2023-06-08 03:36
@puneetlath mind double checking my thoughts above? You might also need to re-assign since your headed OOO soon.

**Comment by puneetlath** [comment] 2023-06-08 21:12
Yeah, definitely sounds like an internal. Maybe it makes sense for @stitesExpensify or @chiragsalian to take over since it relates to threads.

**Comment by JmillsExpensify** [comment] 2023-06-09 03:27
Raised in NewDot.

**Comment by JmillsExpensify** [comment] 2023-06-14 06:02
Would appreciate your thoughts on the above!

**Comment by stitesExpensify** [comment] 2023-06-14 14:14
@JmillsExpensify where did you bring this up in newdot? I think I might have missed that one?

**Comment by JmillsExpensify** [comment] 2023-06-21 05:16
Still internal and waiting to be picked up.

**Comment by chiragsalian** [comment] 2023-06-26 17:54
I'm not actively working on this issue. @stitesExpensify are you?

**Comment by stitesExpensify** [comment] 2023-06-27 15:41
Sounds good, switched!

**Comment by chiragsalian** [comment] 2023-07-05 23:51
Its on my plate but my plate is swamped so I'm unsure when i can get to this. Should i just post in engg-chat looking for volunteer or are you okay if i tackle this slightly later?

**Comment by chiragsalian** [comment] 2023-07-07 19:19
Found the issue, its not really related to threads. Created threads from attachments works just fine. 
The bug was in the logic of notifying participants and policy reports. When the user threads an attachment with themselves we were attempting to notify accountID 0 which threw the error. If other participants were in the thread it would work just fine.

Either way, i fixed the code to address this bug. Placing the PR for review in a bit.

**Comment by stitesExpensify** [comment] 2023-07-19 17:43
Looks like the web PR was deployed to production last week, so is this fixed @chiragsalian ?

**Comment by chiragsalian** [comment] 2023-07-21 17:35
I'm pretty sure its resolved. QA even tested it on staging. Closing this issue, feel free to reopen if its not resolved.

**Closed by chiragsalian** 2023-07-21 17:35 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
