### ISSUE TITLE
[$500] Chat - Two pop-ups are displayed at the same time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31735] opened 2023-11-22 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Open any chat with several comments or send them
4. Hover the mouse over any comment -> add a reaction
5. Hover over another comment

## Expected Result:
The previous pop-up should close when the next pop-up opens

## Actual Result:
Two pop-ups are displayed at the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/844008e9-1d70-4faf-96d7-9d9e95d7b29d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df547c67743aa751</li>
        <li>Upwork Job ID: 1727388305945669632</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-22 18:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Two mini context menu appears at the same time when EmojiPicker is opened

### What is the root cause of that problem?

We prevent closing mini context menu below when opening EmojiPicker
https://github.com/Expensify/App/blob/a273354130bbbc057dee4eefb1f9ac0371bec26a/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L130
https://github.com/Expensify/App/blob/a273354130bbbc057dee4eefb1f9ac0371bec26a/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L143
https://github.com/Expensify/App/blob/a273354130bbbc057dee4eefb1f9ac0371bec26a/src/pages/home/report/ContextMenu/ContextMenuActions.js#L73

This is the root cause

### What changes do you think we should make in order to solve the problem?

`shouldKeepOpen` was used to prevent closing the mini context menu when EmojiPicker is opened. Looks like an intentional behavior

Simply updating 
https://github.com/Expensify/App/blob/a273354130bbbc057dee4eefb1f9ac0371bec26a/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L143
to
```
         openContextMenu: () => setShouldKeepOpen(false),
```
would solve the issue

Note: We might need to remove all use of `shouldKeepOpen` and `openContextMenu`

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2023-11-22 20:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two mini context menu appears at the same time when EmojiPicker is opened
### What is the root cause of that problem?
We prevent closing mini context menu using `shouldKeepOpen` when opening EmojiPicker
### What changes do you think we should make in order to solve the problem?
We need to remove `shouldKeepOpen` here.
https://github.com/Expensify/App/blob/0cca90ab9aa7fd9467ef45ca35c4d0ad3c3334ae/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L130
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-11-22 21:50
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning.
If something pops up that needs urgent attention please reapply label or ask in slack.

**Comment by it-education-md** [comment] 2023-11-23 13:11
@aimane-chnaif  you are right.
This is not bug

**Comment by abdulrahuman5196** [comment] 2023-11-24 09:58
@abekkala Seems like an intentional behavior. Kindly check if this is still a bug, after back from holidays.

**Comment by abekkala** [comment] 2023-11-27 18:45
I agree, this is expected and not a bug. Closing

**Closed by abekkala** 2023-11-27 18:45 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
