### ISSUE TITLE
[$1000] Default avatar changes after a few seconds of starting a new chat with an existing account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23332] opened 2023-07-21 04:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create 2 accounts
2. Start a conversation from one account with the other using the search

## Expected Result:
default avatar should not change
## Actual Result:
 the default avatar that appeared during the search and the start of the conversation changes to another default avatar after a few seconds
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.45-5
**Reproducible in staging?:** yes
**Reproducible in production?:** haven't checked
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7d41e8ac-bb1a-4d70-b1fd-f080c3aee432

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689789714639089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d58542f791b71b70</li>
        <li>Upwork Job ID: 1683966628798455808</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-07-25 22:25
I don't have access to a dev environment so I can't reproduce the bug.

**Comment by aldo-expensify** [comment] 2023-07-25 22:37
> I don't have access to a dev environment so I can't reproduce the bug.

This can be reproduced in staging (and production too I guess)


https://github.com/Expensify/App/assets/87341702/22706a3c-6ea7-4ed5-b388-d475deb9df26

**Comment by aldo-expensify** [comment] 2023-07-25 22:38
Updated the issue body

**Comment by tjferriss** [comment] 2023-07-25 22:43
Got it. I just tested and saw the wrong colored profile icon for a split second both on the right hand-nav and in the chat. Then it flipped to the correct one.

**Comment by JmillsExpensify** [comment] 2023-07-26 03:09
Oh weird. Should I un-assign myself from this issue TJ? Looks like we are both assigned.

**Comment by railway17** [comment] 2023-07-26 07:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default avatar changes after a few seconds of starting a new chat with an existing account

### What is the root cause of that problem?
After creating the report from the search list, accountID is getting from API response that is returned from `command=OpenReport`.
This API response contains a newly added personalDetailList item.
But this accountID is different from the request param which was generated from the frontend side.
We are displaying default avatars that are based on accountID (that is getting in `UserUtils.getDefaultAvatar`).
Because 2 accountIDs are different, default avatars are displayed differently in the search list and report.
![Screenshot at Jul 26 14-59-54](https://github.com/Expensify/App/assets/29966461/feab91e9-1360-4a71-b6c1-f80a17f2ccde)
![Screenshot at Jul 26 15-00-27](https://github.com/Expensify/App/assets/29966461/3012e25c-4c07-43a5-956a-8544ef8253a1)


### What changes do you think we should make in order to solve the problem?
We should fix OpenReport API in order to return the same accountID and avatar URL that is requested from the frontend side.
I don't know backend code but suggest using default variable with the requested accountID.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2023-07-31 12:13
I don't think there's solution to fix this as optimistic accountID is different from real accountID and default avatars are generated differently,

**Comment by situchan** [comment] 2023-07-31 12:14
This issue is clearly seen in offline mode.

https://github.com/Expensify/App/assets/108292595/b1f03251-2e05-4d71-9bd9-6b5f86b64ed9

**Comment by railway17** [comment] 2023-07-31 12:18
@situchan 
do you mean there is no way to fix by updating the API?

**Comment by situchan** [comment] 2023-07-31 12:19
It's designed logic. Frontend cannot estimate accountID generated by backend.

**Comment by railway17** [comment] 2023-07-31 12:23
> It's designed logic. Frontend cannot estimate accountID generated by backend.

Yes, so I suggested passing the generated accountID from frontend to backend.
In the API side, we can use received parameter as a default value.
While doing it, we need to validate uniqueness.
If not unique, we need to generate the accountID from backend and update also persistent value in frontend.
This is just my solution for this issue

**Comment by situchan** [comment] 2023-07-31 12:29
@railway17 please read following discussions before persisting your proposal.
- https://expensify.slack.com/archives/C01GTK53T8Q/p1688995928956959
- https://expensify.slack.com/archives/C01GTK53T8Q/p1689452076372489

**Comment by aldo-expensify** [comment] 2023-07-31 17:51
hmm, thanks for the investigation, I see little to do if the accountID is used to determine the default avatar, specially for the offline case. We could fix it by stop using the accountID in the equation and only consider the display name or email, but I'm not sure if we want that.

**Comment by tjferriss** [comment] 2023-08-03 18:43
@aldo-expensify are you suggesting we hold off on fixing the issue?

**Comment by aldo-expensify** [comment] 2023-08-03 18:46
@tjferriss nop, I'm just not sure if we can really do something about it.

Do we want to remove the `accountID` from the calculation of the avatar? This has the downside that if two accounts have the same `displayName`, and you don't have the `login`, then you will see the same default avatar. I think this downside is enough to not do it and just live with this changing avatar thing.

thoughts?

**Comment by tjferriss** [comment] 2023-08-09 04:26
@situchan do you have any thoughts on @aldo-expensify comments above?

**Comment by situchan** [comment] 2023-08-09 04:30
I also don't like avatar depending on `displayName`.
If I don't know user's `login` and that user changes display name, avatar will change dynamically.

Seems like no solid solution yet

**Comment by aldo-expensify** [comment] 2023-08-09 17:21
Ok, I think we should just close it then, for now it doesn't seem feasible because of the accountID change.

Thanks!

**Closed by aldo-expensify** 2023-08-09 17:21 UTC
Labels: External, Daily, Help Wanted, Bug
