### ISSUE TITLE
Focus not set to the right side modal when opened reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12654] opened 2022-11-10 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the right side modal (navigate to settings it will open the modal)
2. Try tabbing
3. Notice the focus is not automatically set to the right side modal

## Expected Result: 
The focus should be set to the right side modal when opened

## Actual Result: 
The focus stays where it was and on next tab continues from there

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.26-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201208652-4caafde3-76b5-4bdf-adfb-4fcc42651e1a.mp4

https://user-images.githubusercontent.com/43996225/201208675-8c64d710-5a8f-458d-add7-4b7ca240bfdf.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668112822577749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thesahindia** [comment] 2022-11-11 14:08
This is a duplicate of https://github.com/Expensify/App/issues/5516

P.S. We aren't focusing on accessibility right now.

**Closed** 2022-11-11 20:58 UTC
Labels: Daily, Bug
