### ISSUE TITLE
[HOLD #11768] Navigating Back takes the user to the home screen on the web - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10506] opened 2022-08-24 03:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app from the home URL (https://staging.new.expensify.com/).
  2. Opening a new Chat from RHN (SearchPage)
  3. Navigate to another chat from RHN (SearchPage).
  4. Go Back.
  
## Expected Result:
The user should not leave the app.

## Actual Result:
User is taken out of the app.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659433336320769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-08-25 08:16
This looks like almost an exact duplicate of https://github.com/Expensify/App/issues/10507 - I think we can close this since #10507 has more details

**Comment by marcaaron** [comment] 2022-08-25 11:43
Putting this one on HOLD.

**Comment by marcaaron** [comment] 2022-08-25 11:46
Let's leave it open for now we won't be accepting any proposals just yet. Agree it seems similar to the other issue, but it's good to have the different test cases.

**Comment by johncschuster** [comment] 2022-10-18 20:10
It looks like this is still reproducible. I'm going to apply the `Engineering` label.

@marcaaron, do you feel this issue should still be on HOLD?

**Comment by johncschuster** [comment] 2022-10-21 20:44
@marcaaron bump. What are your thoughts? Should we keep this on HOLD, or should we work on it?

**Comment by marcaaron** [comment] 2022-10-24 17:16
yep, I think we should investigate it as part of the Tracking issue linked above titled "Get Control of Navigation". It's something we should take to the maintainers and first try to fix at the library level.

**Comment by johncschuster** [comment] 2022-10-25 20:58
Just bumping to keep Melvin happy. This issue has been added to the Tracking issue you mentioned. I'm going to downgrade the label to `Weekly`, but will keep bumping so it doesn't erode and close.

**Comment by JmillsExpensify** [comment] 2022-11-03 18:29
Snagging this since I'm asssigned on the tracking issue.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:50
Check the tracking issue for the latest updates.

**Comment by JmillsExpensify** [comment] 2022-11-16 05:11
Still on hold Melvin.

**Comment by JmillsExpensify** [comment] 2022-11-22 07:14
Still held as this initiative goes through the design process.

**Comment by JmillsExpensify** [comment] 2022-11-27 06:38
Still holding on the larger react navigation project.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:50
Still on hold for navigation.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:57
Still on hold for navigation. No ETA.

**Comment by JmillsExpensify** [comment] 2023-02-14 06:19
Same same

**Comment by JmillsExpensify** [comment] 2023-05-03 05:01
Still on hold

**Comment by JmillsExpensify** [comment] 2023-06-07 05:04
Coming off hold very soon!

**Comment by JmillsExpensify** [comment] 2023-07-12 13:27
Working on testing this week.

**Comment by JmillsExpensify** [comment] 2023-08-16 13:56
Still trying to make time. Low priority.

**Comment by JmillsExpensify** [comment] 2023-10-10 17:26
> The user should not leave the app.

Re-tested and I can confirm this no longer happens.

**Comment by JmillsExpensify** [comment] 2023-10-10 17:26
Payout summary: $250 to @parasharrajat for issue reporting

**Comment by JmillsExpensify** [comment] 2023-10-10 17:27
I'm going to close this issue, though please make sure to send a request via NewDot!

**Closed by JmillsExpensify** 2023-10-10 17:27 UTC
Labels: Engineering, Monthly, Planning, Bug

**Comment by JmillsExpensify** [comment] 2023-10-12 22:13
$250 payment approved for @parasharrajat based on summary above.
