### ISSUE TITLE
Android - Message between ` symbols is not visible on the screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19493] opened 2023-05-23 21:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19333

## Action Performed:
1. Login to NewDot
2. Open any chat
3. Input following to compose box: ` any message here `
4. Submit message

## Expected Result:
Message should be visible in chat

## Actual Result:
Message is not visible in chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:**  Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/c4ee532a824643afe0474a2e799191dfc8c81d818c22a19aadd1da57d5c65988

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment] 2023-05-24 05:05
dupe of https://github.com/Expensify/App/issues/17441

**Comment by michaelhaxhiu** [comment] 2023-05-31 17:58
@jayeshmangwani agreed

**Comment by michaelhaxhiu** [comment] 2023-05-31 17:58
nice 1 :)

**Closed** 2023-05-31 17:58 UTC
Labels: Daily, Overdue, Bug
