### ISSUE TITLE
[$250] Duplicate thread created when expenses with comments are deleted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47004] opened 2024-08-07 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+39ch39@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Submit an expense on a workspace
3. Click into the expense
4. Click the header and hold the expense
5. Click the workspace name to return to the workspace chat
6. Click back into the expense
7. Click the header and delete the expense

## Expected Result:
A duplicate thread is created when an expense that is on hold is deleted. This duplicate thread has a join button.

## Actual Result:
The user should return to the workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8bd9c50a-3014-403c-8ded-ec75178bdd38

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b38e49613507a1d</li>
        <li>Upwork Job ID: 1823386133744847971</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertjchen</details>

**Comment by izarutskaya** [comment] 2024-08-07 21:18
We think this issue might be related to the #collect project.

**Comment by wildan-m** [comment] 2024-08-14 03:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense: Unexpected issue with join button and double thread creation while deleting expense.

### What is the root cause of that problem?

For join button issue, after the deletion, the report type will be replaced from expense to standard chat type and it will skip [this check](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/libs/ReportUtils.ts#L7309).

### What changes do you think we should make in order to solve the problem?

We should check for deleted parentReportAction to prevent anyone from joining it.

src/libs/ReportUtils.ts
canJoinChat
```tsx
    if (ReportActionsUtils.isDeletedParentAction(parentReportAction)) {
        return false;
    }    
```

For issue with duplicate thread, I think that's a BE issue, I can't reproduce it while offline.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sakluger** [comment] 2024-08-16 00:12
Hey @akinwale - can you take a look at the proposal we received?

**Comment by akinwale** [comment] 2024-08-16 08:05
@wildan-m's [proposal](https://github.com/Expensify/App/issues/47004#issuecomment-2287772893) works here, but the duplicate thread issue is from the BE. We can go ahead if we want to fix only the issue with the join button in the frontend.

🎀👀🎀 C+ reviewed.

**Comment by srikarparsi** [comment] 2024-08-19 21:20
I'm no longer able to reproduce this, I think this has been fixed in the BE. @sakluger or @akinwale do you think you could verify and if so we can close out this issue.

https://github.com/user-attachments/assets/10100b56-cf42-4b2f-b8b7-81578c64f1ac

**Comment by wildan-m** [comment] 2024-08-21 01:49
@srikarparsi it's reproducible in the latest staging

https://github.com/user-attachments/assets/ed868ae7-7085-4cbb-9025-c710b075c54d

**Comment by srikarparsi** [comment] 2024-08-22 15:59
I see what you're saying. I looked into this and I think it's entirely a BE issue. A duplicate thread should not be created when an expense that is on hold is deleted. That is also why we see the join button. I don't have time to look into this currently but @sakluger do you think you could help fit this into a wave and see if there's any volunteers. I can try to pick this back up the week after next week if no one's available.

**Comment by sakluger** [comment] 2024-08-23 21:50
I posted in #wave-collect to see if we can find any volunteers to help.

**Comment by sakluger** [comment] 2024-08-23 21:50
I'm also going to add another BZ member to manage the issue while I'm OOO through 8/30.

**Comment by trjExpensify** [comment] 2024-08-26 13:17
Another one for eyes from @robertjchen related to Held requests.

**Comment by robertjchen** [comment] 2024-08-27 05:06
Agreed, this may be related to how `DeleteMoneyRequest` / `DeleteReport` handles the deletion of held items on the BE- I'm guessing it's not finding and moving the thread over (hence the `Join` button and the duplicate `[deleted]` item, one of which is a thread)

**Comment by sakluger** [comment] 2024-08-30 17:52
I'm back so I will take over management of this issue again.

**Comment by robertjchen** [comment] 2024-09-04 18:19
Taking this one over

**Comment by sakluger** [comment] 2024-09-09 05:16
Thanks @robertjchen! Commenting for melvin.

**Comment by robertjchen** [comment] 2024-09-09 21:17
Was able to reproduce the issue locally, looking in the backend.

**Comment by robertjchen** [comment] 2024-09-13 07:17
Making some fixes elsewhere to the hold flow, will revisit after

**Comment by robertjchen** [comment] 2024-09-16 08:37
Same, fixing hold flow elsewhere before revisiting this week

**Comment by robertjchen** [comment] 2024-09-18 05:58
Looks like it's down to the way the chat thread is created on the held expense. We're creating a thread one-level down:

### Normal Expense (deleted)

<img width="617" alt="Screenshot 2024-09-18 at 1 50 33 PM" src="https://github.com/user-attachments/assets/151aa5c9-182e-4d79-8f84-fdac7402d5b4">

### Held Expense (deleted)

<img width="686" alt="Screenshot 2024-09-18 at 1 50 50 PM" src="https://github.com/user-attachments/assets/aa928e1c-1afe-46f6-9021-835b2465f7a4">

**Comment by robertjchen** [comment] 2024-09-18 07:44
Major BE fixes in progress/testing. A few issues were found and will need to be addressed together:
- The transactions threads are not being created in the proper location (duplicate thread)
- The transaction threads are not initialized properly as to set the notification preference (join button)
- While debugging the above, discovered that the participants list was not being properly generated, so the proper Onyx updates were not going out (potentially related to the other other open issues).

**Comment by robertjchen** [comment] 2024-09-18 08:40
So, after testing this in-depth, it appears that the issue is actually not hold specific- the same "duplicate thread" and "join button" issue exists for non-held reports with just comments on them:

https://github.com/user-attachments/assets/c48677d2-7d77-4f6e-accf-34977117ae70

**Comment by robertjchen** [comment] 2024-09-18 08:44
Un-assigning my self to focus on actual hold-related issues. @sakluger could you please find another engineer to look into this? It's a bit of a corner case, so I made it a `Weekly` for now.

Notes for the next person taking this on:

I think we just need to set the notification preference of the chat thread to `always` and that should make the `Join` button disappear. That's what worked for me locally at least.

**Comment by trjExpensify** [comment] 2024-09-18 10:40
@robertjchen and I were chatting about this in thread [here](https://expensify.slack.com/archives/C036QM0SLJK/p1726653357646329?thread_ts=1726504580.971829&cid=C036QM0SLJK). 

The bug report is a bit misconstrued, and it really just comes down to the delete expense report case that's converted to a chat report to preserve any comments on it in thread has a `join` button at the top of it if you visit it again. It's a pretty minor point, and doesn't prevent you from commenting on it or what not, so we're just going to close it out. 

No duplicate expenses or messages or stuff like that is happening. 👍

**Closed by trjExpensify** 2024-09-18 10:40 UTC
Labels: Weekly, Internal, Bug
