### ISSUE TITLE
[HOLD for payment 2024-02-14] [LOW] [$500] Web - Chat - Console error shows up when opening emoji picker and then clicking on send button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32743] opened 2023-12-08 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Click on the emoji picker
4. Click Send button

## Expected Result:
No console error

## Actual Result:
Console error shows up - Uncaught TypeError: Cannot read properties of null (reading 'onCloseCallback')

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6bb451e0-388d-421f-a37f-39d684afcc36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a72f5508e45e17d</li>
        <li>Upwork Job ID: 1733213660108169216</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28128112</li>
<li>mkhutornyi | Contributor | 28128113</li>
</ul></li>
    </ul>
</details>

**Comment by happy-devs** [comment] 2023-12-08 20:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An unescaped method is showing as an console error.

### What is the root cause of that problem?
The `onCloseCallback` method mentioned in the error is in the `activePopoverRef.current` ref, which may not have it present at the time of being used.

`if (activePopoverRef.current.onCloseCallback) {
            activePopoverRef.current.onCloseCallback();
        }
`

### What changes do you think we should make in order to solve the problem?

remove or escape the method on `current` to prevent it from being invoked unless present

**Comment by Pujan92** [comment] 2023-12-11 18:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error for closing the emoji picker

### What is the root cause of that problem?
Earlier in this [PR](https://github.com/Expensify/App/pull/29152) we have set the `onCloseCallback`, `onOpenCallback` to fix the popover stuck issue. But now it has been removed in the other [PR](https://github.com/Expensify/App/pull/30556) to maintain a list of modals closeModal methods. 
`closePopover` method calls the close method of the `activePopoverRef` which resets the ref and `isVisible` state change of `Popover` also calls the close method again and in that execution `activePopoverRef` is null which throws the console error.
https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/components/PopoverProvider/index.tsx#L15-L23

### What changes do you think we should make in order to solve the problem?
We can get rid of the `onOpenCallback`, `onCloseCallback` fields as it is not needed now as pointed out above due to this [PR](https://github.com/Expensify/App/pull/30556) changes.

**Comment by strepanier03** [comment] 2023-12-19 21:10
All right, we would like to move forward and fix this error.

**Comment by strepanier03** [comment] 2023-12-19 22:34
Discussing [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1703025254781929) still.

**Comment by strepanier03** [comment] 2023-12-21 22:24
@hoangzinh - Please pause until next week. I'll update this on the 28th when I'm back in the office.

**Comment by strepanier03** [comment] 2023-12-28 19:31
@hoangzinh - I don't have an update yet. The holidays and out of office across the team are leading to a bit of a delay. I'll check again tomorrow to see if there's an update I can share here. 

I think it's safe to pause again until next week unless I come back with an update early tomorrow.

**Comment by Pujan92** [comment] 2024-01-02 07:30
> Btw, is there anyone still reproduce this bug?

https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/components/EmojiPicker/EmojiPicker.js#L47
https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/components/EmojiPicker/EmojiPicker.js#L174
No, it seems the ref setup has been updated in this [PR](https://github.com/Expensify/App/pull/33537) which returns early and prevents extra execution.
https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/components/PopoverProvider/index.tsx#L15-L20
I still believe we should remove `onOpenCallback` and `onCloseCallback ` part as it is not needed.

**Comment by strepanier03** [comment] 2024-01-03 21:13
Bumped the thread again, will update as soon as possible.

**Comment by strepanier03** [comment] 2024-01-08 20:30
Per [this](https://expensify.slack.com/archives/C066HJM2CAZ/p1704322313311749?thread_ts=1703025254.781929&cid=C066HJM2CAZ) I'm adding to the VSB vip with Low priority.

**Comment by strepanier03** [comment] 2024-01-12 00:01
Low priority atm.

**Comment by strepanier03** [comment] 2024-01-18 18:57
@hoangzinh - If you have a proposal that looks good we should go for it and take the normal next steps. Being Low doesn't mean we can't work on it, just that it's not the biggest priority. 

Feel free to take next steps if the proposal is the one you recommend!

**Comment by quinthar** [comment] 2024-01-22 01:44
Yes if it's a real bug and we've got proposals, let's do it!

**Comment by strepanier03** [comment] 2024-01-25 02:22
@MonilBhavsar can you review the suggested [proposal](https://github.com/Expensify/App/issues/32743#issuecomment-1847833981) and assign @mkhutornyi if you agree?

Thanks!

**Comment by MonilBhavsar** [comment] 2024-01-29 07:34
Proposal looks good. Let's fix it and remove unnecessary usages 🚀

**Comment by strepanier03** [comment] 2024-02-13 19:05
Looks like we're good until tomorrow. @hoangzinh feel free to finish the checklist and I'll handle the reg test.

**Comment by strepanier03** [comment] 2024-02-15 21:46
Got it, thanks @hoangzinh I'll finish this up now.

**Comment by strepanier03** [comment] 2024-02-15 21:50
Okay, paid and contract ended. Thanks again for helping to get this finished @hoangzinh and @mkhutornyi 🙌

**Closed by strepanier03** 2024-02-15 21:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
