### ISSUE TITLE
[HOLD for payment 2024-07-26] [CSV] Add Download action to Search page

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#44576] opened 2024-06-27 23:45 UTC
We should complete [this section of the doc](https://docs.google.com/document/d/1dwKo6o6PK-t5DlQlmZzP-B6uIvPOv74d6hc4rDgu8fs/edit#bookmark=id.obe0uzqshi7b).

This will add the Download option to the bulk action button in the Search page and effectively download the file.

It is important to handle the offline modal and the modal for errors as well.

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by trjExpensify** [comment] 2024-06-28 13:42
@filip-solecki can you comment here so I can assign you before I pop labels on it?

**Comment by filip-solecki** [comment] 2024-07-01 07:02
Hi! I am Filip from SWM an expert agency and I'd like to work on this!

**Comment by JmillsExpensify** [comment] 2024-07-10 04:28
Looks like we're still waiting on the PR.

**Comment by trjExpensify** [comment] 2024-07-11 11:19
The PR for #44577 merged this morning, so taken this off hold. 👍

**Comment by rushatgabhane** [comment] 2024-07-25 17:32
1. Log in to the account with some expenses
3. Go to search
4. Select a few items
5. Click on "X selected" button
6. Click "Download"
7. When offline you should see Modal with information otherwise the file will be downloaded and contain the selected items

**Comment by rlinoz** [comment] 2024-07-25 18:26
Oh I think we are good, this is a new functionality and we just asked for the testing steps to be created in Testrails

https://github.com/Expensify/Expensify/issues/414444

**Comment by JmillsExpensify** [comment] 2024-07-26 19:40
Payment summary above is accurate. This is part of a broader initiative, so we'll handle the regression test centrally. @rushatgabhane please submit an expense via New Expensify!

**Comment by trjExpensify** [comment] 2024-07-29 23:08
Confirming the payment summary as follows: 

- $250 to @rushatgabhane for the C+ review.

**Comment by JmillsExpensify** [comment] 2024-07-29 23:20
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment] 2024-08-07 14:25
All payments made and regression steps are being added centrally.

**Closed by JmillsExpensify** 2024-08-07 14:25 UTC
Labels: Daily, NewFeature, Overdue, Awaiting Payment
