### ISSUE TITLE
[$250] LHN- LHN shows "This chat is with..." instead of last message if deleting thread message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50685] opened 2024-10-12 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5074346&group_by=cases:section_id&group_order=asc&group_id=292106
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open a chat with some messages displayed.
3. Right click over the last message.
4. Click on "Reply in Thread"
5. Send any message in thread chat.
6. Delete the just sent reply.
7. Return to the first chat.
8. Delete the recently threaded message.
9. Verify that chat preview in LHN now displays the previous message.

## Expected Result:
When deleting the last message of a chat, the chat preview in LHN, should display the previous message.

## Actual Result:
When deleting a threaded message, displayed last in a chat conversation, the chat preview shows "This chat is with user" instead of the previous message in chat.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c280f491-364d-46ee-a752-c554232d7e73

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846016204171199063</li>
        <li>Upwork Job ID: 1846016204171199063</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @AndrewGable</details>

**Comment by IuliiaHerets** [comment] 2024-10-12 17:06
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-12 17:06
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-10-15 02:32
Easy to repro. External as far as I can tell!

![image](https://github.com/user-attachments/assets/2c523ec2-ce13-4866-8d7b-dc8bd9432730)

**Comment by huult** [comment] 2024-10-15 06:54
This is a backend issue. `lastMessageText` returns an empty string when the message is deleted.

- <img width="1510" alt="Screenshot 2024-10-15 at 13 54 05" src="https://github.com/user-attachments/assets/5a61f4b2-0997-4bd8-a320-a7d8a9d93fc9">

- <img width="1511" alt="Screenshot 2024-10-15 at 13 54 25" src="https://github.com/user-attachments/assets/617df28b-0b1b-4c3d-b1fb-52c66731c2f4">

**Comment by RachCHopkins** [comment] 2024-10-20 21:41
@AndrewGable can you take a gander at this please?

**Comment by Shahidullah-Muffakir** [comment] 2024-10-21 23:06
Seems like resolved, I couldn't reproduce it.

**Comment by RachCHopkins** [comment] 2024-10-22 04:26
@paultsimura can you confirm?

**Comment by RachCHopkins** [comment] 2024-10-29 00:51
@AndrewGable can you please take a look?

**Comment by muttmuure** [comment] 2024-10-29 16:13
I vote we close this

**Comment by RachCHopkins** [comment] 2024-10-30 01:53
@AndrewGable do you agree that this should be closed?

**Comment by AndrewGable** [comment] 2024-10-31 17:29
Yes!

**Closed by AndrewGable** 2024-10-31 17:29 UTC
Labels: Daily, Internal, Overdue, Bug
