### ISSUE TITLE
Dependent tags - Not here page opens when clicking on second level tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38682] opened 2024-03-20 16:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace
- The Collect workspace has multilevel dependent tags
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Tags
4. Click on the second level tag (North+test or South)

## Expected Result:
Tag settings RHP opens without issue

## Actual Result:
Not here page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/02d80af9-ee31-4b82-b4eb-60c3865334e7

[Bug6420688_1710950667432!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/Expensify/App/files/14669772/Bug6420688_1710950667432.Dependent_-_Multi_Level_tags_NEW.csv)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed882f03ce5893b6</li>
        <li>Upwork Job ID: 1771230284623380480</li>
        <li>Last Price Increase: 2024-03-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-20 16:36
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-20 16:36
We think that this bug might be related to #wave-control

**Comment by twisterdotcom** [comment] 2024-03-20 16:56
>Precondition:
>User is admin of Collect workspace
>The Collect workspace has multilevel dependent tags

We are preventing this right @trjExpensify - so we can just close this? Or should we start solving these for Control?

**Comment by trjExpensify** [comment] 2024-03-20 17:12
You'll be able to have multi-level tags as a result of the QBO integration. Not dependent tags though, so we should fix that under the guise of #wave-control -- and generally support for them properly

**Comment by twisterdotcom** [comment] 2024-03-22 17:39
@JmillsExpensify I've put this in the Wave Control project, but I haven't put a status as I'm not sure when we want to support dependent tags. Gonna make it Weekly and assign Internal for now.

**Comment by twisterdotcom** [comment] 2024-04-03 13:24
Given this probably won't be picked up until after May 1, gonna downgrade it to monthly.

**Comment by twisterdotcom** [comment] 2024-06-13 23:35
Is somebody internal already working on dependent tags now @trjExpensify?

**Comment by trjExpensify** [comment] 2024-06-19 15:05
>Is somebody internal already working on dependent tags now @trjExpensify?

Not in #wave-collect. Ariel is [progressing CSV import](https://expensify.slack.com/archives/C06ML6X0W9L/p1718747215797199), incl. multiTags in #wave-control. So I expect dependent tags to be there if anywhere. CC: @JmillsExpensify

**Comment by twisterdotcom** [comment] 2024-07-15 15:32
I also have two other dependent tag issues which seem to be `Internal`:

- https://github.com/Expensify/App/issues/43574
- https://github.com/Expensify/App/issues/44915

**Comment by twisterdotcom** [comment] 2024-08-16 23:33
@yuwenmemon I hear you are taking on Dependent Tags on newDot. Would you like to be assigned all of these glorious issues?

**Comment by yuwenmemon** [comment] 2024-08-17 02:06
Yes please!

**Comment by yuwenmemon** [comment] 2024-09-18 06:04
I'm actually unable to reproduce this. And since this bug is ancient @lanitochka17 can we pleas retest?

**Comment by twisterdotcom** [comment] 2024-09-30 16:25
Did we get a retest @lanitochka17?

**Comment by yuwenmemon** [comment] 2024-10-09 04:36
@lanitochka17 bump! 🙇🏽

**Comment by lanitochka17** [comment] 2024-10-09 13:22
Issue is not reproducible on the latest build 9.0.46-4

https://github.com/user-attachments/assets/9777298f-45e3-49a8-af3a-b83052c4a01d

**Closed** 2024-10-09 16:49 UTC
Labels: Weekly, Internal, Bug, retest-weekly
