### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Chat - Compose box stays in the middle when reduced with a several lines message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49541] opened 2024-09-20 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat.
3. On compose box, start writing a message adding new lines until a scrollbar can be seen.
4. Tap on the "Expand" button.
5. Keep adding lines to the message until a scrollbar can also be seen with the compose box expanded.
6. Reduce the compose box size.
7. Verify if you are scrolled to the bottom when the compose box is reduced.

## Expected Result:
When the compose box with a written message of several lines is reduced in size, the user should be scrolled to the bottom of it.

## Actual Result:
When the compose box with a written message of several lines is reduced in size, the user is not scrolled to the bottom. The compose box is displayed in the middle of the message.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/214f305d-409a-41ef-bfe1-ad25b9f580d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838742813045152105</li>
        <li>Upwork Job ID: 1838742813045152105</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104312306</li>
<li>FitseTLT | Contributor | 104312308</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 15:19
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-09-20 15:19
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-09-20 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Compose box stays in the middle when reduced with a several lines message

### What is the root cause of that problem?

We're not scrolling into view when the composer size changes 

### What changes do you think we should make in order to solve the problem?

Add this line

```
textInput.current?.scrollIntoView({ behavior: 'instant' });
```

here

https://github.com/Expensify/App/blob/5f0a5da406fcf819fdb842857e2bbb061d018270/src/components/Composer/index.tsx#L394-L397

**Comment by FitseTLT** [comment] 2024-09-20 19:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Compose box stays in the middle when reduced with a several lines message

### What is the root cause of that problem?
When we toggle isComposerFullSize there is a code that sets the scrollTop to the previous scrollTop (the scrollTop in the previous isComposerFullSize state)
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Composer/index.tsx#L268-L271
so when the when the composer was full size the scroll top had a smaller value (that is because the composer had greater height and needs to scroll with smaller value to show the bottom of the composer than when it is non-full size) so when we switch it to non-full size that small value of scrollTop will not be enough to show the bottom of the composer.
### What changes do you think we should make in order to solve the problem?

We need to set the scrollTop in such a way that the content on the bottom of the composer will be persitent on toggling isComposerFullSize so: we should add height state to hold previous clientHeight the change
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Composer/index.tsx#L232
```
            setPrevScroll(textInput.current.scrollTop);
            setPrevHeight(textInput.current.clientHeight);
```
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Composer/index.tsx#L268-L271

```
 if (!textInput.current || prevScroll === undefined || prevHeight === undefined) {
            return;
        }
        // eslint-disable-next-line react-compiler/react-compiler
        textInput.current.scrollTop = prevScroll + prevHeight - textInput.current.clientHeight;
       
```
### What alternative solutions did you explore? (Optional)
We if we want the center of the content persistent we can change
```
        textInput.current.scrollTop = prevScroll + prevHeight / 2 - textInput.current.clientHeight / 2 ;

```

**Comment by QichenZhu** [comment] 2024-10-02 05:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer's caret scroll position is not maintained after resuming from expanded mode.

### What is the root cause of that problem?
The line below maintains the `scrollTop` of the `Composer`, which means it maintains the scroll position of the first line in the visible area. If the distance between the first line and the caret is greater than the `Composer` height after resizing, the first line is still visible, but the caret is not.

https://github.com/Expensify/App/blob/526845be71fe922f56ce39cadb602c336bff4fac/src/components/Composer/index.tsx#L269

### What changes do you think we should make in order to solve the problem?
In Chrome, if the caret is not visible, after typing a charector, the caret will be scrolled to the visible area. We can implement similar behavior by replacing the above line with the code below.

```TSX
const selectionRect = window.getSelection()?.getRangeAt(0).getBoundingClientRect();
const textInputRect = textInput.current.getBoundingClientRect();

if (selectionRect && (selectionRect.top < textInputRect.top || selectionRect.bottom > textInputRect.bottom)) {
    textInput.current.scrollTop = prevScroll + selectionRect.top - textInputRect.top;
} else {
    // eslint-disable-next-line react-compiler/react-compiler
    textInput.current.scrollTop = prevScroll;
}
```

### What alternative solutions did you explore? (Optional)
In Chrome, after you blur and focus the Composer, the caret will be scrolled into the visible area. We can emulate this behavior by inserting the code below after the line mentioned in the root cause.

```TSX
const selectionRect = window.getSelection()?.getRangeAt(0).getBoundingClientRect();
const textInputRect = textInput.current.getBoundingClientRect();

if (selectionRect && (selectionRect.top < textInputRect.top || selectionRect.bottom > textInputRect.bottom)) {
    textInput.current.blur();
    textInput.current.focus();
}
```

**Comment by QichenZhu** [comment] 2024-10-02 06:33
Could we clarify the expected behavior? Since some content has to be hidden after shrinking the `Composer`, what should be visible after resizing? The first line, the middle of the text, the last line, or the caret  `▎`?

| Behavior | Expanded | Collapsed |
|-----------| ---------- | ---------- |
| The first line is visible (current behavior) | <pre>Line 1<br>Line 2<br>Line 3<br>Line 4 ▎<br>Line 5<br>Line 6<br>Line 7<br>Line 8<br>Line 9<br>Line 10<br>Line 11</pre>  | <pre>Line 1<br>Line 2<br>Line 3</pre>  |
| The middle of the text is visible | <pre>Line 1<br>Line 2<br>Line 3<br>Line 4 ▎<br>Line 5<br>Line 6<br>Line 7<br>Line 8<br>Line 9<br>Line 10<br>Line 11</pre>  | <pre>Line 5<br>Line 6<br>Line 7</pre>  |
| The last line is visible | <pre>Line 1<br>Line 2<br>Line 3<br>Line 4 ▎<br>Line 5<br>Line 6<br>Line 7<br>Line 8<br>Line 9<br>Line 10<br>Line 11</pre>  | <pre>Line 9<br>Line 10<br>Line 11</pre>  |
| The caret is visible | <pre>Line 1<br>Line 2<br>Line 3<br>Line 4 ▎<br>Line 5<br>Line 6<br>Line 7<br>Line 8<br>Line 9<br>Line 10<br>Line 11</pre>  | <pre>Line 4 ▎<br>Line 5<br>Line 6</pre>  |

**Comment by dannymcclain** [comment] 2024-10-02 16:30
Hmm, what's shown in the video honestly doesn't feel weird to me. It kinda looks like we're "respecting" the scroll position that was already there. But I also think it could make sense to always show the cursor/caret. So I think personally I'd opt for one of those two options. Let's see what @dubielzyk-expensify thinks!

**Comment by FitseTLT** [comment] 2024-10-02 17:50
> In my opinion, we should scroll to the caret position instead. 

@rayane-djouah If a user has scrolled up from where the cursor is located and switches the composer size I doubt if the user expects it to be scrolled to the caret position. What I think and based my proposal on was we should as much as possible make the visible content of the composer consistent across the two composer size states. Currently, we are making the top content consistent that's why we facing the current issue.  So we can make the bottom or middle of content consistent instead. @dannymcclain WDYT

**Comment by dubielzyk-expensify** [comment] 2024-10-03 03:05
I actually think we should respect the scroll position over the caret here. Cause I think you'd expect the view to expand not for the view to shift and follow the caret. I vote scroll position 👍

**Comment by dannymcclain** [comment] 2024-10-03 13:35
Ok thanks Jon! That makes me think that our _current_ behavior is what we want (keep the first visible line in view when resizing).

**Comment by FitseTLT** [comment] 2024-10-03 14:13
> Ok thanks @dubielzyk-expensify! That makes me think that our _current_ behavior is what we want (keep the first visible line in view when resizing). Do you agree?

The logic of the expected result in the OP is that switching to full-size and back to normal-size, they expected the content visible to be on the same scroll level it was before toggling to full-size. This happens in most cases but when the scroll level is the down-end, when the user changes to full-size, the top line when it was non-full sized will now be in the middle on full-size (obviously b/c full-size will accomodate more content) so when swiching back to non-full sized it will keep the first line in view so it will be in a scrolled-up state than it was originally, which kind of unexpected.

**Comment by dubielzyk-expensify** [comment] 2024-10-04 00:05
Ahhh right. I see what you mean now. I guess because the text grows from bottom up it feels weird that we align the scroll position to the top of the compose bar.  Okay I think I get it. 

In that instance I guess I think we should make sure that it follows the bottom of the compose bar. So when you expand, the last line should stay the same. That way you never get into a weird thing where you're at the bottom of the compose bar, expand it, and you lose your position. Does that sound right?

**Comment by dannymcclain** [comment] 2024-10-04 14:18
Yeah that sounds good to me! I guess for the composer the bottom is really the "anchor" so what you're suggesting makes sense.

**Comment by anmurali** [comment] 2024-11-12 02:49
Rotating the label so we can assign another BZ member while I am OOO

**Comment by JmillsExpensify** [comment] 2024-12-18 11:22
Payment summary: 

- Contributor: $250 @FitseTLT 
- Reviewer: $250 @rayane-djouah

**Comment by JmillsExpensify** [comment] 2024-12-18 11:26
Contributors paid out and regression test created, so I'm closing this one.

**Closed by JmillsExpensify** 2024-12-18 11:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
