### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$1000] IOU - Selecting currency in BNP and pressing "CMD+ENTER" results in accidental redirection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23395] opened 2023-07-22 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Select any valid 1:1 chat room
3. Click on the + button in the compose box.
4. Click on "Request money" in the action menu
5. Enter any amount of currency
6. Click on the currency
7. In the currency selection menu, press the "CMD+ENTER" key combination

## Expected Result:
The modal window of currency selection should close and the user should get to the previous window of currency amount input with correctly selected currency

## Actual Result:
The modal currency selection window closes and the user is redirected to a random chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d1afee70-f2da-4c3d-95e8-0b7e2019a0f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Inernal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015204edc11a150c2b</li>
        <li>Upwork Job ID: 1684299342131027968</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25995133</li>
<li>samh-nl | Contributor | 25995135</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-25 11:25
@MitchExpensify I am not sure about this one, seems like a niche edge case where I am not sure if we should worry about.

**Comment by mountiny** [comment] 2023-07-25 11:29
@azimgd from your experience, have we been catching such flows before?

**Comment by mountiny** [comment] 2023-07-25 12:30
Yeah so I think if we want to solve this it would have to be in general

**Comment by MitchExpensify** [comment] 2023-07-26 20:27
Ok cool, as long as we solve in general this seems worth fixing

**Comment by MitchExpensify** [comment] 2023-07-26 20:33
Not overdue, Melvin

**Comment by mollfpr** [comment] 2023-07-31 11:55
@samh-nl The solution seems good and works well on Web and Desktop. I need to test the shortcut on the native platform based on this test case https://github.com/Expensify/App/pull/17708.

**Comment by MitchExpensify** [comment] 2023-08-02 17:23
@mollfpr checking in on this one, have you had a chance to test?

**Comment by mollfpr** [comment] 2023-08-04 15:36
Sorry for the delay; need more time to test this. I'll give an update tomorrow.

**Comment by mollfpr** [comment] 2023-08-06 14:29
I agree with @samh-nl [proposal](https://github.com/Expensify/App/issues/23395#issuecomment-1646602158). Let's go with that, and we also need to test the shortcut keyboard on the native to make sure everything still working well.

🎀 👀 🎀 C+ reviewed!

**Comment by johnmlee101** [comment] 2023-08-07 19:08
Agreed! Looks good

**Comment by MitchExpensify** [comment] 2023-08-09 20:54
Not overdue, Melvin - Actively being worked on

**Comment by mollfpr** [comment] 2023-08-14 17:25
Thanks @samh-nl. For the process here, you will need to raise a PR in E/App after the https://github.com/Expensify/react-native-key-command/pull/32 is merged.

**Comment by mollfpr** [comment] 2023-08-21 13:42
Not overdue

**Comment by mollfpr** [comment] 2023-08-25 13:22
Not overdue, still waiting for the update on the PR.

**Comment by mollfpr** [comment] 2023-08-31 14:15
Friendly bump to review the [PR](https://github.com/Expensify/react-native-key-command/pull/32) @johnmlee101

**Comment by mollfpr** [comment] 2023-09-01 16:54
@johnmlee101 @samh-nl While recording the test, I discovered that this issue is not reproduced anymore. I also checked again in the staging, and I got the same result. Could you guys confirm?

**Comment by MitchExpensify** [comment] 2023-09-03 13:38
I can also no longer reproduce this

**Comment by mollfpr** [comment] 2023-09-05 11:29
@MitchExpensify @johnmlee101 Since we already hired @samh-nl and the PR is already up, should this issue be due to compensation? The RCA from @samh-nl will resolve the root cause, and we are still okay to get the PR to be merged.

**Comment by mollfpr** [comment] 2023-09-07 03:36
Friendly bump @MitchExpensify for clarification

**Comment by MitchExpensify** [comment] 2023-09-07 10:36
Does @samh-nl 's PR still need to be merged seeing as this not reproducible anymore @mollfpr ?

Totally appreciate the effort here so open to suggestion on what we think is fair. It's my understanding that this was solved entirely separately to this issue, e.g. We didn't build off or take inspiration from any of the proposal/PR, so doesn't technically require compensation.

**Comment by mollfpr** [comment] 2023-09-07 11:19
I think the RCA of @samh-nl is correct, and it will improve our keyboard command.

> Personal time or resources applied towards investigating a proposal will not guarantee compensation. Compensation is only guaranteed to those who propose a solution and get hired for that job.

The doc says that if the contributor gets hired, the compensation is guaranteed.

**Comment by MitchExpensify** [comment] 2023-09-07 12:06
That is true and thanks for working through this with me as my hope is to be fair and abide by the guidelines of course! So to summarize where this landed:

The issue is not reproducible anymore however the contributor was hired and submitted the PR for review. 

Seeing as the PR hasn't been merged and therefore not all steps have been finished I think we should either:

1. Leave the PR as is and compensate 75% seeing as the final steps haven't been taken
2. Reopen this issue, work to merge the PR, complete the final BZ steps and compensate 100%

Whether we do 1 or 2 depends on how useful the change is seeing as the issue itself is not reproducible anymore. For that judgement, I'm curious what you think @johnmlee101 🙇

**Comment by mollfpr** [comment] 2023-09-12 11:45
Friendly bump @johnmlee101

**Comment by johnmlee101** [comment] 2023-09-15 06:54
Let's go with 2. I think the change is important

**Comment by MitchExpensify** [comment] 2023-09-15 17:49
> Reopen this issue, work to merge the PR, complete the final BZ steps and compensate 100%

Over to you @mollfpr & @samh-nl !

**Comment by mollfpr** [comment] 2023-09-18 10:36
I'm retesting the PR upstream and completing the records.

**Comment by MitchExpensify** [comment] 2023-09-22 21:43
What's the latest @mollfpr ?

**Comment by mollfpr** [comment] 2023-09-25 16:17
Sorry for the delay.

We have an issue on Android while navigating the list with the arrow key. There's a fix and explanation in the PR.

**Comment by MitchExpensify** [comment] 2023-09-30 11:59
Looking at the PR I'm am not 100% sure on the latest here @mollfpr . What do we need to do to get this over the line?

**Comment by mollfpr** [comment] 2023-10-03 12:06
The upstream [PR](https://github.com/Expensify/react-native-key-command/pull/32) is merged. @samh-nl Let's open PR to bump the package version.

**Comment by MitchExpensify** [comment] 2023-10-18 21:07
Wow whats up Melvin! Is this actually being held for payment at this point?

**Comment by mollfpr** [comment] 2023-10-19 12:42
@MitchExpensify I think we are ready for payment here; the last PR merged on October 10th. I'll complete the checklist soon.

**Comment by mollfpr** [comment] 2023-10-20 16:43
> [@johnmlee101] The PR that introduced the bug has been identified. Link to the PR:
> [@johnmlee101] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/react-native-key-command/pull/5

There's also another PR in the E/App that causing the issue, because it got resolve before the fix in upstream merged.

> [@johnmlee101] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr / @samh-nl] Determine if we should create a regression test for this bug.
 [@mollfpr / @samh-nl] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Click on the FAB
2. Go to Request money
3. Click on the currency symbol to open the currency selector
4. Press CMD+Enter
5. Verify that the currency selector is closed, returning the user to the enter money amount page
6. 👍 or 👎

**Comment by MitchExpensify** [comment] 2023-10-22 18:37
Mind helping me understand if the fix has been on prod for 7 days without regression? The Melvin updates are causing me doubt

**Comment by mollfpr** [comment] 2023-10-23 02:34
@MitchExpensify The PR is included in the production release: https://github.com/Expensify/App/releases/tag/1.3.83-11, which is on Oct 14th.

**Comment by MitchExpensify** [comment] 2023-10-25 17:11
Mind taking a peak at the BZ steps @johnmlee101 https://github.com/Expensify/App/issues/23395#issuecomment-1765319309 👀

**Comment by mollfpr** [comment] 2023-10-25 17:18
@MitchExpensify I already have the Upwork contract.

**Comment by MitchExpensify** [comment] 2023-10-28 21:22
Paid and contracts ended!

**Closed by MitchExpensify** 2023-10-28 21:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
