### ISSUE TITLE
[$1000] App crashed when revisiting thread from left room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26256] opened 2023-08-29 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new room
2. Send a message, create a thread with that message, pin that thread for later use.
3. Go back to our room and leave it then go back to the previous thread that you pinned.
4. Notice that app is crashed.

## Expected Result:
App shouldn't be crashed

## Actual Result:
App crashed when revisiting thread from left room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/415e0e2b-350b-430a-bfb0-80ac2f0617e5

https://github.com/Expensify/App/assets/115492554/edfe1097-9fab-44c5-a424-5757c5cf26ea

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692703142297279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ed400862f0d676e</li>
        <li>Upwork Job ID: 1696683478876925952</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-08-29 21:23
This happens in prod, so NAB. This is the console error I'm seeing.
![Screenshot 2023-08-29 at 3 22 59 PM](https://github.com/Expensify/App/assets/22219519/4fc6c285-5f27-4684-a106-c39d8f34fb11)

Thrown here:
![Screenshot 2023-08-29 at 3 23 21 PM](https://github.com/Expensify/App/assets/22219519/faf080c6-e4da-4929-be0c-d88ffdfc1846)

**Comment by s-alves10** [comment] 2023-08-29 22:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when revisiting a thread from left room

### What is the root cause of that problem?

When we leave the room, the API returns the following data, that is, clears the room report
![image](https://github.com/Expensify/App/assets/126839717/2517cd61-5c95-43cf-8a33-98e1c554e87e)

When we revisit the chat thread after that, the `originalReport` becomes null below
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/pages/home/report/ReportActionItem.js#L136-L137

When rendering mini context menu, we call `ReportUtils.chatIncludesChronos` below
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/pages/home/report/ReportActionItem.js#L565

and `chatIncludesChronos` doesn't check the validity of the report as you can see below
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/libs/ReportUtils.js#L2895-L2897

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can use `lodashGet` in `chatIncludesChronos` function instead of referring the property directly

```
function chatIncludesChronos(report) {
    const participants = lodashGet(report, ['participantAccountIDs']);
    return participants && _.contains(participants, CONST.ACCOUNT_ID.CHRONOS);
}
```

This works as expected

### What alternative solutions did you explore? (Optional)

**Comment by robertKozik** [comment] 2023-08-31 11:43
Hi all @s-alves10 @hungvu193 ! I wanted to check your proposals but I have problems with reproduction. Could you check on your end that it's still reproducible? 

https://github.com/Expensify/App/assets/61146594/d1817da9-aaf8-4cbf-9146-eabb0e874204

**Comment by kbecciv** [comment] 2023-08-31 11:46
@hungvu193 No worries about your proposal.
@CortneyOfstad @luacmartins - he is reporter of the issue and his proposal -  https://github.com/Expensify/App/issues/26256#issuecomment-1698312564

**Comment by robertKozik** [comment] 2023-08-31 11:58
Thanks for confirming @kbecciv 🙇🏼‍♂️

**Comment by CortneyOfstad** [comment] 2023-09-01 15:56
@hungvu193 Are you still able to reproduce this?

**Comment by sourcecodedeveloper** [comment] 2023-09-01 21:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Steps to reproduce
    Create a new room
    Send a message, create a thread with that message, pin that thread for later use.
    Go back to the room and leave it and wait for few seconds, it is not necessary to revist thread from left room to observe the crash.
    Notice that app is crashed.

### What is the root cause of that problem?

Api response from LeaveRoom

{
    "jsonCode": 200,
    "requestID": "7fffff3e983ade57-MCT",
    "onyxData": [
        {
            "onyxMethod": "set",
            "key": "report_6306073816172336",
            "value": null
        }
    ]
}

The report is being set to null and then later being fetched in ReportActionItem 

 const originalReport = props.report.reportID === originalReportID ? props.report : ReportUtils.getReport(originalReportID);

The originalReport is then sent to ReportUtils.chatIncludesChronos to be used in the MiniReportActionContextMenu

<MiniReportActionContextMenu
    reportID={props.report.reportID}
    reportAction={props.action}
    isArchivedRoom={ReportUtils.isArchivedRoom(originalReport)}
    displayAsGroup={props.displayAsGroup}
    isVisible={hovered && !props.draftMessage && !hasErrors}
    draftMessage={props.draftMessage}
    isChronosReport={ReportUtils.chatIncludesChronos(originalReport)}
/>


The root cause being the implementation for chatIncludesChronos is assuming report would be defined and not null.
function chatIncludesChronos(report) {
    return report.participantAccountIDs && _.contains(report.participantAccountIDs, CONST.ACCOUNT_ID.CHRONOS);
}


### What changes do you think we should make in order to solve the problem?
lodashGet being proposed is useful but when report is set to null, lodashGet will still return null so check needs to be put to ensure lodashGet does not return null.

const participantAccountIDs = lodashGet(report, "participantAccountIDs", {}) || {};

The implementation would change to
function chatIncludesChronos(report) {
    const participantAccountIDs = lodashGet(report, "participantAccountIDs", {}) || {};
    return participantAccountIDs && _.contains(participantAccountIDs, CONST.ACCOUNT_ID.CHRONOS);   
}

attached video, 
[bug_solution.webm](https://github.com/Expensify/App/assets/141340971/bbfbe1d2-93a5-4c62-94fd-6eaa0814b484)



### What alternative solutions did you explore? (Optional)

As suggested by previous proposal, 
using lodashGet without the null check returns undefined when boolean is expected
const participants = lodashGet(report, ['participantAccountIDs']);

As suggested by previous proposal return early also returns null when report is null and boolean is expected
return report && report.participantAccountIDs && _.contains(report.participantAccountIDs, CONST.ACCOUNT_ID.CHRONOS);

**Comment by CortneyOfstad** [comment] 2023-09-05 14:06
@luacmartins @robertKozik Since this doesn't seem to be reproducible, good to close?

**Comment by s-alves10** [comment] 2023-09-05 15:24
For a few mins, please

**Comment by luacmartins** [comment] 2023-09-05 15:54
Ok, gonna close this issue. Thanks for the discussion!

**Closed by luacmartins** 2023-09-05 15:54 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
