### ISSUE TITLE
[Ready for payment][$250] Add some basic runtime type validation in Onyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39852] opened 2024-04-08 19:09 UTC
coming from https://github.com/Expensify/Expensify/issues/363913...

### Problem
It is possible to queue incorrect Onyx updates from Auth. Twice now, we have seen an array used in place of an object in an Onyx update in Auth, which when merged completely removes the object and replaces it with an array.

### Solution
While we recognize that there a number of more elegant solutions to this (compile time type validation of Onyx updates in the back-end being a prime candidate), we should apply a simple solution to prevent simple mistakes from having catastrophic effects, as we have seen occur in production twice already.

What this means is - let's update Onyx such that:

- it will not apply any updates where we try to merge an array into an object, or vice-versa
- it will log an alert if we do try to do that (except on dev, of course)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152270829f1a6f929</li>
        <li>Upwork Job ID: 1777413537488273408</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by mananjadhav** [comment] 2024-04-08 20:21
@ShridharGoel Wouldn't we need to check if it's an Array for the existingValue as well? I am assuming we're using the existing block with `OnyxUtils.get(key).then(existingValue`.


@roryabraham 
1. The following is true for all/any environment right?

> it will not apply any updates where we try to merge an array into an object, or vice-versa

2. Would `Logger.logAlert` suffice for the mismatch? do we need any sendActionToDevTools?

**Comment by dominictb** [comment] 2024-04-09 05:08
Contributor details
Your Expensify account email: dominic-tb@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f70bed1934fd35d5

**Comment by sea1375** [comment] 2024-04-09 05:51
**### Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Add some basic runtime type validation in Onyx #39852

**What is the root cause of that problem?**
The validation of the datatype for Onyx update will be done in the backend but double validation in the frontend is helpful in order to prevent simple mistakes.

**What changes do you think we should make in order to solve the problem?**
The functions for Onyx update such as Onyx.set(), Onyx.update() are performed by write(..., onyxData, ...) function in the @libs/API/index.ts.
As the parameter for Onyx, we can see a variable - onyxData(which is consist of OptimisticData and onyxDataWithoutOptimisticData). Here, OptimisticData is enough to compare the types of old and new.

There is the example of optimisticData variable below. (refer to tunction signIn())
```
const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.ACCOUNT,
            value: {
                ...CONST.DEFAULT_ACCOUNT_DATA,
                isLoading: true,
                loadingForm: twoFactorAuthCode ? CONST.FORMS.VALIDATE_TFA_CODE_FORM : CONST.FORMS.VALIDATE_CODE_FORM,
            },
        },
    ];
```

We can get the old value from "key" property, and compare it with "value" property.
```
const promise1 = new Promise((resolve, reject) => {
    if (oldValueType !== newValueType) {
        Logger.logAlert();
        Promise.reject();
    } else {
        // Do the original action
        Promise.resolve();
    }
});
Promise.all([promise1]).then((values) => {
    console.log(values);
});
```
**What alternative solutions did you explore? (Optional)**
N/A

**Comment by sea1375** [comment] 2024-04-09 05:55
Contributor details
My Expensify account email: sea.dream0000@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e06e26f8cd83d24f

**Comment by mananjadhav** [comment] 2024-04-09 06:15
I think @ShridharGoel's proposal makes sense. Pending response from @roryabraham .

🎀 👀 🎀 C+ reviewed.

**Comment by dominictb** [comment] 2024-04-09 08:30
@mananjadhav That proposal won't work in many cases, as mentioned in [my proposal](https://github.com/Expensify/App/issues/39852#issuecomment-2044143831). 

Some examples where that solution will cause regression:
- When we try to clear an Array key (we won't be able to clear)
- When there're many updates in update array, but only one of them is invalid

Can you double check on that?

cc @roryabraham

**Comment by dominictb** [comment] 2024-04-09 14:15
> At once we pass either an object or array to merge. So, if the existing value is an object and the new value is not, we'll not continue with the merge, and vice-versa.

@ShridharGoel So is it correct that you're suggesting to run `OnyxUtils.get(key).then(existingValue =>` to check the `existingValue` for every change? (without batching changes)

**Comment by james-tindal** [comment] 2024-04-09 14:35
Any solution is likely to conflict with https://github.com/Expensify/react-native-onyx/pull/523

**Comment by james-tindal** [comment] 2024-04-09 14:56
Contributor details
Your Expensify account email: expensify@mesbrown.co.uk
Upwork Profile Link: https://www.upwork.com/freelancers/~01372c73faaf7896d3

**Comment by roryabraham** [comment] 2024-04-09 18:06
> The following is true for all/any environment right?

correct

> Would Logger.logAlert suffice for the mismatch?

yes

**Comment by roryabraham** [comment] 2024-04-09 18:11
Sorry if this wasn't clear, but this change should apply not only to `Onyx.merge`, but also to `Onyx.set` and `Onyx.mergeCollection`. As such, I don't think any of the current proposals are sufficient

**Comment by sea1375** [comment] 2024-04-09 18:41
I think that the write() function in the @libs/API/index.ts performs all the commands such as merge(), set(), mergeCollection(), and so on by following the command type. The first parameter of write() function is command such as "ONYXKEYS.MERGE". Even though the parameter is MERGE_COLLECTION, it works.

**Comment by dominictb** [comment] 2024-04-10 06:49
[Proposal updated](https://github.com/Expensify/App/issues/39852#issuecomment-2044143831) to handle the `Onyx.set` and `Onyx.mergeCollection` too, based on [this expectation update](https://github.com/Expensify/App/issues/39852#issuecomment-2045812413)

**Comment by kadiealexander** [comment] 2024-04-12 05:27
@mananjadhav bump for review please!

**Comment by mananjadhav** [comment] 2024-04-12 15:51
Will review this today/tomorrow.

**Comment by roryabraham** [comment] 2024-04-15 16:52
Going to move forward with @dominictb's proposal - I like how it abstracted `isUpdateCompatibleWithExistingValue`.

**Comment by mananjadhav** [comment] 2024-04-15 17:03
> Going to move forward with @dominictb's proposal - I like how it abstracted `isUpdateCompatibleWithExistingValue`.

Agreed.

**Comment by roryabraham** [comment] 2024-04-18 21:54
[PR](https://github.com/Expensify/react-native-onyx/pull/532) is still in draft

**Comment by roryabraham** [comment] 2024-04-19 19:50
PR was taken out of draft, I left a comment there

**Comment by dominictb** [comment] 2024-04-22 11:34
@mananjadhav requesting your PR review again. Thanks!

**Comment by roryabraham** [comment] 2024-04-22 18:07
PR is in review and should hopefully be merged soon

**Comment by roryabraham** [comment] 2024-04-25 22:43
Onyx PR merged. @dominictb please open a PR to upgrade react-native-onyx to 2.0.35+ ASAP to complete this issue. Thanks!

**Comment by dominictb** [comment] 2024-04-26 02:47
Sure!

**Comment by roryabraham** [comment] 2024-05-01 16:47
E/App PR has been merged, thanks everyone. now we just hurry up and wait for it to be deployed.

**Comment by roryabraham** [comment] 2024-05-07 00:21
Unfortunately the E/App PR to upgrade Onyx was reverted due to a regression from an [unrelated Oynx PR](https://github.com/Expensify/react-native-onyx/pull/519). I've asked someone else to redo the upgrade PR, so there's nothing more to do here except for wait for Onyx to be fixed and upgraded again for this to go to staging.

**Comment by kadiealexander** [comment] 2024-05-16 05:09
Not overdue.

**Comment by mananjadhav** [comment] 2024-05-16 19:28
@roryabraham Are we expecting any updates on the Onyx version?

**Comment by mananjadhav** [comment] 2024-05-26 19:02
Waiting for an update from @roryabraham on this one.

**Comment by mananjadhav** [comment] 2024-06-02 15:47
Quick bump @roryabraham. Did you get chance to look at the previous comments?

**Comment by mananjadhav** [comment] 2024-06-12 17:53
Just checked and it seems @roryabraham is OOO. Let's wait for him to come back by this week, else will ask to reassign.

**Comment by roryabraham** [comment] 2024-06-20 17:08
Ok, so this is definitely out in production right now, and I _think_ it was deployed in https://github.com/Expensify/App/pull/42772.

So that means it's been on prod for about a week. Given the unrelated delays, I suggest we pay this out right away and then close this.

**Comment by mananjadhav** [comment] 2024-06-22 00:20
@kadiealexander this is ready for payout. Can you update the payment summary?

**Comment by kadiealexander** [comment] 2024-06-24 00:05
Payouts due:

- [ ] Contributor: $250 @dominictb 
- [ ] Contributor+: $250 @mananjadhav ([Upwork](https://www.upwork.com/nx/wm/offer/102848486))

Upwork job is [here](https://www.upwork.com/jobs/~01fa19d7d3c5fda1fb).

@dominictb please apply on Upwork, I couldn't find your account.

**Comment by mananjadhav** [comment] 2024-06-24 08:21
@kadiealexander I don't need the Upwork payout. I have requested on NewDot.

**Comment by kadiealexander** [comment] 2024-06-24 08:23
Withdrawn, thanks Manan!

**Comment by JmillsExpensify** [comment] 2024-06-24 16:23
$250 approved for @mananjadhav

**Closed** 2024-06-27 03:11 UTC
Labels: External, Daily, Overdue, Bug
