### ISSUE TITLE
[$500] mWeb/Safari - IOU - The cursor only starts blinking when I tap inside the amount field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32861] opened 2023-12-11 21:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.11.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Do a manual request using the FAB
3. Tap inside the amount field

## Expected Result:
The cursor should start blinking without the extra tap

## Actual Result:
The cursor only starts blinking when I tap inside the amount field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1fc6e9c6-586b-464a-888c-2ad89b2e87f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acf864d013ffc103</li>
        <li>Upwork Job ID: 1734318924475326464</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28066136</li>
</ul></li>
    </ul>
</details>

**Comment by dksingla** [comment] 2023-12-14 04:37
The problem arises because iOS Safari restricts programmatically focusing on an input element to prevent the virtual keyboard from loading. You can find more details on this issue at https://bugs.webkit.org/show_bug.cgi?id=195884.

I've raised a bug report at https://bugs.webkit.org/show_bug.cgi?id=266334, proposing a solution to allow programmatically focusing if the "inputmode" is set to "none." If this gets addressed, no further changes will be necessary.

In the meantime, I am actively exploring potential workarounds.

Best regards,
Deepak

**Comment by dksingla** [comment] 2023-12-14 04:41
Contributor details
Your Expensify account email: deepak.stoic@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/fullstackdeveloperdeepak

**Comment by dksingla** [comment] 2023-12-14 04:43
Contributor details
Your Expensify account email: deepak.stoic@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/fullstackdeveloperdeepak

**Comment by dksingla** [comment] 2023-12-14 04:44
Contributor details
Your Expensify account email: deepak.stoic@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0119f037acfe0172f6

**Comment by keisyrzk** [comment] 2023-12-14 12:47
On fresh main `1.4.12-0-364-ge81ed8f4c5` I cannot reproduce the issue on iOS web safari, macOS web and iOS as well.
Please find the videos attached

iOS safari
https://github.com/Expensify/App/assets/18525360/fe11fb79-af10-4976-bd64-ec15054229d3

macOS chrome
https://github.com/Expensify/App/assets/18525360/34c5b8dd-931c-4ecf-9a3f-8cba7cb4d868

iOS
https://github.com/Expensify/App/assets/18525360/41bfbc00-c296-4f94-bd38-9e6693026320

**Comment by abekkala** [comment] 2023-12-15 20:17
Tagged DB in #vip-vsb to confirm adding to the project.

**Comment by abekkala** [comment] 2023-12-19 18:56
posted in CS for job pick up

**Comment by abekkala** [comment] 2023-12-19 21:11
@puneetlath 
### STATUS
I'm ooo though Jan 03

This is at the beginning. waiting on proposals. I did a call out for CS to pick up (slack link above)

**Comment by waterim** [comment] 2023-12-20 10:24
Hello, Im Artem from Callstack and would like to take this issue!

**Comment by waterim** [comment] 2023-12-20 15:57
Im not able to reproduce this issue: 

https://github.com/Expensify/App/assets/39777589/6a0c9df2-2b58-4cab-8fbd-01021c43721a

**Comment by puneetlath** [comment] 2023-12-22 21:58
@fedirjh are you able to reproduce it? If not, let's close this.

**Comment by quinthar** [comment] 2023-12-26 01:46
Hm, actually if this is related to expenses, #vip-vsb is the wrong place.  Can move this to #wave5?

**Comment by puneetlath** [comment] 2023-12-26 19:10
Since none of us are able to reproduce, I'm going to go ahead and close it. Anyone - feel free to comment/reopen if you're able to reproduce!

**Closed by puneetlath** 2023-12-26 19:10 UTC
Labels: External, Daily, Overdue, Bug
