### ISSUE TITLE
Wallet section always be greyed out when offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43724] opened 2024-06-13 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718251299751059

## Action Performed:
1. Go offline
2. Go to Wallet Page

## Expected Result:
We only should disable the "Enable wallet" button and shouldn't greyed out because there are no pending action
## Actual Result:
Wallet section always be greyed out
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/5335ce7d-3915-40c1-baab-d4e94c0f1ded

![Snip - (71) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/53cc6940-eb2a-4643-b39c-b46af889001f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by truph01** [comment] 2024-06-13 23:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet section always be greyed out

### What is the root cause of that problem?
- In this:
https://github.com/Expensify/App/blob/11c1184700cdaf1ffdec56ccbc66f8d0e9ef66db/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L388
we always use ```pendingAction={CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}```.
### What changes do you think we should make in order to solve the problem?
- We should update the above logic to ```userWallet.pendingAction``` or ```pendingAction={walletTerms.pendingAction}```

### What alternative solutions did you explore? (Optional)

**Comment by neonbhai** [comment] 2024-06-13 23:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The wallet balance is greyed out when the user is offline

### What is the root cause of that problem?
We set the pendingAction for the balance to

https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L388

This is a constant (value never updated through user actions). This effectively has the effect of always greying the balance when the user is offline.

This was designed to signal to the user that the balance is not up to date when the user is offline. In this case we are signalling this even when no wallet is connected and no balance is being fetched.

### What changes do you think we should make in order to solve the problem?
We should only grey out the numbers when the user has connected their wallet. We will use `hasActivatedWallet` and change:

https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L388
to:

```jsx
pendingAction={hasActivatedWallet ? CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD : undefined}
```

### Alternatively
Since we do signal to the user that they are offline, they do 

Since users when offine would see the offline indicator and will not expect the balance to be realtime. We can remove the pending action from [here](https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L388)

**Comment by VictoriaExpensify** [comment] 2024-06-14 01:17
Hi @m-natarajan - sorry I'm not really understanding the problem here. From your explanation and the recording, I can see that when the app is offline, the ability to enable the wallet is greyed out. That is expected because you would need to be online to enable this.

What is it that you don't think should be greyed out?

**Comment by DylanDylann** [comment] 2024-06-14 02:57
@VictoriaExpensify  We should only disable the "enable wallet" button when offline. But all wallet section shouldn't be greyed out when we don't have any pending action

**Comment by DylanDylann** [comment] 2024-06-14 02:59
I discovered this bug while working on another PR. Happy to take over as C+ if this is external

**Comment by VictoriaExpensify** [comment] 2024-06-16 23:54
I'm still not sure I follow, @DylanDylann . The wallet hasn't been enabled, so there is no wallet. And you can't enable the wallet because your offline. So, to me, it makes sense that it is all greyed out in this scenario.

If I'm misunderstanding something, please let me know. But for now, I'm going to close this one because I don't think it's a bug.

**Closed by VictoriaExpensify** 2024-06-16 23:54 UTC
Labels: Daily, Bug
