### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] [Xero] An error appears in the console when entering the "Import" menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41862] opened 2024-05-08 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41561
## Action Performed:
Create a WS and add a XERO account to it
1. Open New Expensify app STG
2. Log in with the prepared account
3. Navigate to the WS settings with the added XERO account
4. Navigate to the Accounting menu
5. Click on "Import" in the XERO settings menu
6. Navigate through the tabs in RHP

## Expected Result:
When opening the "Import" menu in the XERO account settings, no errors should appear in the console

## Actual Result:
When opening the "Import" menu in the XERO account settings, an error appears in the console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bfafbc06-54fe-4ca8-b2e9-dfa7818ed201

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015376233957c1d4bf</li>
        <li>Upwork Job ID: 1789036868706181120</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-05-08 19:14
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-08 19:15
We think that this bug might be related to #wave-collect - Release 2

**Comment by johncschuster** [comment] 2024-05-10 20:56
I agree that this should be in #wave-collect release 2.

cc @zanyrenney just so you know this is an issue 👀

**Comment by GoodWork0903** [comment] 2024-05-11 00:00
Hello

**Comment by GoodWork0903** [comment] 2024-05-11 00:03
Hi
This error is simple.
Please contact me.

Contributor details
My Expensify account email : solomon21century@outlook.com
Upwork Profile : https://www.upwork.com/freelancers/~01a27ebc4cfff91f79
Thank you for your attention.

**Comment by johncschuster** [comment] 2024-05-14 20:55
@GoodWork0903 If you would like to solve this issue, please submit a [proposal](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md#proposal)

**Comment by johncschuster** [comment] 2024-05-14 21:04
@GoodWork0903 If you would like to solve this issue, please submit a [proposal](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md#proposal)

**Comment by GoodWork0903** [comment] 2024-05-15 00:50
Proposal
Please re-state the problem that we are trying to solve in this issue.

✔When you are trying to entering the Import menu, error occur in console✔

What is the root cause of that problem?

✔ This error seems like promise error.✔

What changes do you think we should make in order to solve the problem?

✔First, I have to check your asynchronous functions, I think that there is no difficult problem in here.✔
Thanks

**Comment by trjExpensify** [comment] 2024-05-16 11:01
Putting this on everyone's radar @lakchote @rushatgabhane @mananjadhav @hungvu193

**Comment by johncschuster** [comment] 2024-05-16 17:33
Thanks for that, @trjExpensify!

**Comment by mananjadhav** [comment] 2024-05-16 21:42
I'v raised a PR to fix this. There was a typo in the Routes.

**Comment by c3024** [comment] 2024-05-17 03:45
Unassigning myself as [this is dealt by others](https://github.com/Expensify/App/pull/42324#issuecomment-2116221021).

**Comment by trjExpensify** [comment] 2024-05-22 23:20
PR merged into the freeze branch.

**Comment by johncschuster** [comment] 2024-06-10 14:26
@mananjadhav, can you complete the BZ Checklist when you have a moment? Thank you!

**Comment by johncschuster** [comment] 2024-06-10 14:40
# Payment Summary:
Contributor: @mananjadhav  - $250 - paid via Manuaul Request
Contributor+: @hungvu193 - Already paid (confirmed via DM)

**Comment by rushatgabhane** [comment] 2024-06-10 14:47
@johncschuster xero project had a flat fee. no need to pay per issue on this or other issues

**Comment by trjExpensify** [comment] 2024-06-10 15:06
Yep, we can close this!

**Closed by trjExpensify** 2024-06-10 15:06 UTC
Labels: External, Weekly, Awaiting Payment, Bug
