### ISSUE TITLE
[HOLD for payment 2024-01-18] [HOLD for payment 2024-01-17] Scan - No red dot for Amount and Merchant when viewing failed scan request as Admin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34179] opened 2024-01-09 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [Member] Go to workspace chat.
2. [Member] Create scan request with receipt that will fail the scanning.
3. [Admin] When the scanning fails, navigate to the workspace chat with member.
4. [Admin] Open the request details view.

## Expected Result:
Admin sees red dot for empty Amount and Merchant row

## Actual Result:
There is no red dot for Amount and Merchant when viewing as Admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2fc2d829-5d00-46fd-85ef-2eeb2367bfb6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131c5620c048a6293</li>
        <li>Upwork Job ID: 1744814084372897792</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2024-01-09 19:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No red dot for amount and merchant appear when admin viewing failed scan request

### What is the root cause of that problem?

This looks like a regression of this PR https://github.com/Expensify/App/pull/33633

We check the editability of the receipt here
https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/libs/ReportUtils.ts#L1950-L1953

As you can see, only requestor can edit the request. So the admin can't edit the request and `canEditReceipt` will be `false`
https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/components/ReportActionItem/MoneyRequestView.js#L161

So `hasErrors` will be `false` as well.
https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/components/ReportActionItem/MoneyRequestView.js#L225

This is the root cause

### What changes do you think we should make in order to solve the problem?

I think the admin or manager should be able to edit the scan request as well

Update the code
https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/libs/ReportUtils.ts#L1950-L1953

to

```
    if (fieldToEdit === CONST.EDIT_REQUEST_FIELD.RECEIPT) {
        const isRequestor = currentUserAccountID === reportAction?.actorAccountID;
        return !TransactionUtils.isReceiptBeingScanned(transaction) && !TransactionUtils.isDistanceRequest(transaction) && (isRequestor || isAdmin || isManager);
    }
```

`isAdmin` and `isManager` are defined as 
https://github.com/Expensify/App/blob/5df6055eb88862b738bafae9911d71749927fa04/src/libs/ReportUtils.ts#L1942-L1944

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/39613300-33b0-49b1-a0e7-26317946e32e)


</details>

### What alternative solutions did you explore? (Optional)

**Comment by youssef-lr** [comment] 2024-01-09 20:10
@s-alves10 that would allow the admin to edit a receipt, we decided in the past that are no use cases for an admin or manager to update the receipt of the request.

**Comment by s-alves10** [comment] 2024-01-09 20:13
> we decided in the past that there are no use cases for an admin or manager to update the receipt of the request

If so, I think this isn't a bug and we can close this out

**Comment by youssef-lr** [comment] 2024-01-09 20:14
I need to double check whether we want to display errors for the admin still, can be fixed by just removing `canEditReceipt` from here `hasErrors = canEditReceipt && TransactionUtils.hasMissingSmartscanFields(transaction);`

**Comment by youssef-lr** [comment] 2024-01-09 21:55
Sorry my bad here, I shouldn't have changed `canEdit` to `canEditReceipt` in that line in my PR. Raising a PR now.

**Comment by youssef-lr** [comment] 2024-01-09 22:40
Removing blocker, I think regular deploy cycle is fine for this bug.

**Comment by thienlnam** [comment] 2024-01-10 03:47
Looks like a fix was merged but I'll ask to get it CPed so we can get rid of the blocker

**Comment by youssef-lr** [comment] 2024-01-12 03:47
No payment needed here.

**Closed by youssef-lr** 2024-01-12 03:47 UTC
Labels: Engineering, Weekly, Internal, Awaiting Payment
