### ISSUE TITLE
[$250] `Hmm... it's not here` page opens when tapping from a chat to account settings and back again

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40833] opened 2024-04-23 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713903304262189

## Action Performed:
1. Open any DM
2. Click on avatar "account settings"
3. Click on "chat" icon
## Expected Result:
DM chat appear
## Actual Result:
hmmm...it's not here message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f55e82b9-fe82-4a01-8aa3-0470c7093520

https://github.com/Expensify/App/assets/38435837/d786169b-73e8-43d5-8d06-4e697c82fd62

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169c244e0bbbf915e</li>
        <li>Upwork Job ID: 1783140153165897728</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2024-04-23 21:49
The 2nd video shows it happening in production, so this is not a blocker.

**Comment by luacmartins** [comment] 2024-04-23 21:52
I cannot reproduce this, given the console errors, seems like there is a network issue.

**Comment by davidcardoza** [comment] 2024-04-24 00:09
But it's happening in both staging and production, it's shown in both recordings. I can continue to reproduce this in either staging or production.

**Comment by luacmartins** [comment] 2024-04-24 14:25
Yes, this is what I said above. Since this happens in prod, it's not a deploy blocker.

**Comment by luacmartins** [comment] 2024-04-29 18:45
Still looking for proposals

**Comment by luacmartins** [comment] 2024-05-01 19:08
Still waiting on proposals

**Comment by anmurali** [comment] 2024-05-06 19:42
I cannot reproduce this. Are we sure we should keep this open? @luacmartins

**Comment by luacmartins** [comment] 2024-05-06 22:17
I can't reproduce it either and it seems like several contributors also can't. @davidcardoza if you're still experiencing this, could you follow the steps below please?

1. Open your browser console (cmd + option + i)
2. Navigate to the `Network` tab
3. Open the report
4. Locate the request to `OpenReport`
5. Post the `requestID` here

**Comment by davidcardoza** [comment] 2024-05-07 04:05
I can no longer reproduce, unfortunately. Going to close this out.

**Closed by davidcardoza** 2024-05-07 04:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
