### ISSUE TITLE
Searching currency with symbols like `*,(,)` crashes native apps and triggers console error in web

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14415] opened 2023-01-19 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Open Request Money/Send Money/Split Bill
4. Click on currency
5. In search, try to search with either of the symbols: *,(,)

## Expected Result:
It should display that symbol in search box without any error

## Actual Result:
It crashes the app on android and does not display the symbol on windows and mac and it also displays console error 'Invalid regular expression'

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213548475-c2e4c64f-4b3c-4795-918d-7ce7efbff581.mp4

https://user-images.githubusercontent.com/43996225/213548520-c2065743-7c73-41ee-833a-15c12d61c4cb.mp4

https://user-images.githubusercontent.com/43996225/213548616-f564713b-4f7d-4bb9-8d36-590debce42ec.mp4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/213548646-0a0df3bc-8188-4a36-a406-c46e02e8937b.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674124529838879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2023-01-20 09:22
Oh weird - I can't reproduce this on web, Mweb or Android - 

![2023-01-20_09-21-22](https://user-images.githubusercontent.com/62073721/213660238-7cf2993d-a61b-49c7-965c-a2b755e58030.png)

**Comment by laurenreidexpensify** [comment] 2023-01-20 09:23
@mateocole I am OOO next week so reassigning, can you continue to troubleshoot this pls.

**Comment by iwiznia** [comment] 2023-01-20 14:00
Dupe of https://github.com/Expensify/App/issues/14229

**Closed by iwiznia** 2023-01-20 14:00 UTC
Labels: Daily, Bug
