### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000]  App allows user with phone number as primary login to open new room page even though user is not part of any workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22515] opened 2023-07-09 04:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should have phone number as default contact method and user should not have any workspace or should not be part of any workspace
1. Open the app
2. Click plus and observe that 'new room' option is not available as user is not part of any workspace
3. Visit https://staging.new.expensify.com/workspace/new-room and observe that app allows user to open the page, there are no values in workspace dropdown
## Expected Result: 
App should not allow user to open new room page if they are not part of any workspace
## Actual Result: 
App allows user to open new room page using deep link even if they are not part of any workspace

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fcbfa7b5-63e9-4c12-9f8d-cfcb7389f056

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688839037138309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01077c40d090f8e4b1</li>
        <li>Upwork Job ID: 1678461778227703808</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-07-10 17:44
posted to slack. I can't reproduce this.

**Comment by kevinksullivan** [comment] 2023-07-10 17:50
clarified the issue and was able to reproduce

**Comment by mollfpr** [comment] 2023-07-13 12:17
Reviewing

**Comment by mollfpr** [comment] 2023-07-13 16:11
Thanks for the proposals!

The [proposal](https://github.com/Expensify/App/issues/22515#issuecomment-1627634772) from @GItGudRatio looks good to me! I think it's best time to create a new method e.g., in `PolicyUtils` to check if the user is eligible to create a room so that we can reuse it in `WorkspaceNewRoomPage` and `FloatingActionButton`.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-07-14 04:45
> The RCA from @GItGudRatio isn't correct, The problem here is not related to phone number account or email account. it should be in WorkspaceNewRoomPage, we are missing the check workspaces.length that is checked in FloatingActionButtonAndPopover.

It might be right, but it did give us an information why it's only happen with the phone number account in the first place. Also, they did mention it in the **_What changes_** part, so I think we didn't miss the information.

> the email account that has permission to create room also has the same bug.

I agree with this.

My concern is both proposals have the same solution, just slightly different on the variable, and @GItGudRatio proposed it first.

**Comment by mollfpr** [comment] 2023-07-17 14:55
Not overdue; the PR just gets merged and waits to be deployed to staging.

**Comment by kevinksullivan** [comment] 2023-07-19 12:35
Offer sent to @dhanashree-sawant

**Comment by kevinksullivan** [comment] 2023-07-24 14:56
@mollfpr can you fill out the details above? Thanks!

**Comment by mollfpr** [comment] 2023-07-25 04:08
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. The implementation for dismissing the modal on the workspace new page was a long time ago, so this not be the case, it might be between the implementation of the deep link, and we didn't catch this case.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

_Precondition: Use an account that has been enrolled in the policyRooms beta and does not have any workspaces._

1. Login to ND.
2. Go to any chat and paste the URL: https://staging.new.expensify.com/workspace/new-room
3. Click on the URL
4. **Verify** the "New Room" page does not open up.
5. 👍 or 👎

**Comment by mollfpr** [comment] 2023-07-25 04:10
The PR is eligible for the speed bonus. The assignment is on Jul 14, and the PR merge is on Jul 15.

**Comment by kevinksullivan** [comment] 2023-07-28 18:17
Payouts:

Reporter: @dhanashree-sawant $250
Contributor: @GItGudRatio $1,500 (merge bonus included)
C+: @mollfpr $1,500 (merge bonus included)

**Comment by kevinksullivan** [comment] 2023-07-28 18:20
The good ol' upwork bug is not letting me close your contracts @mollfpr @GItGudRatio . 
<img width="1351" alt="image" src="https://github.com/Expensify/App/assets/22508290/92483788-01d2-4ca1-9644-269170b2a526">


I will set a reminder to come back to this.

**Closed by kevinksullivan** 2023-07-28 18:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
