### ISSUE TITLE
[$250] IOS -  infinite loading appears when opening a thread where user was mentioned

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41913] opened 2024-05-09 13:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715208055536019

## Action Performed:
1. Have a workspace chat room with user A,B,C and D 
2. As user B login to web and iOS app
3. As user C mention user B
4. Message in the thread as user D where user B is mentioned
5. Get notification for user B in iOS
6. Tap on the thread reply notification
## Expected Result:
The thread should open and load quickly
Also, the thread should be visible on all platforms

## Actual Result:
The thread opens but shows an infinite loading screen
The thread is not visible on any platform.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f21ca039-2153-4dfe-aa61-9411769568d0

https://github.com/Expensify/App/assets/38435837/7ce38410-15e4-48bb-883f-48bbe2b0cb72

[profile-trace.zip](https://github.com/Expensify/App/files/15256333/profile-trace.zip)

[logs-2024-05-08 22_28_35.633.txt](https://github.com/Expensify/App/files/15256336/logs-2024-05-08.22_28_35.633.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bee0cae802d4b70b</li>
        <li>Upwork Job ID: 1790735134802354176</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by miljakljajic** [comment] 2024-05-15 13:27
This is also being discussed in newdot performance, added the external label to see if we can get some potential solutions here too.

**Comment by getusha** [comment] 2024-05-19 12:25
Waiting for proposals.

**Comment by getusha** [comment] 2024-05-22 18:00
Waiting for proposals

**Comment by getusha** [comment] 2024-05-28 11:29
Waiting for proposals, i'll check if this is still reproducible

**Comment by neil-marcellini** [comment] 2024-05-28 18:16
I'll take this on internally since it might be a backend issue. I'll try to reproduce it or find logs.

**Comment by mvtglobally** [comment] 2024-05-30 01:34
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-06-04 19:16
> I'll take this on internally since it might be a backend issue. I'll try to reproduce it or find logs.

@neil-marcellini , removed `External` and `Help Wanted` and added `Internal`

**Comment by getusha** [comment] 2024-06-05 12:13
Not overdue, just made internal

**Comment by miljakljajic** [comment] 2024-06-12 09:30
How we doing on this one @neil-marcellini? I appreciate it's been a busy couple weeks with the fires, just wondering how this issue will be prioritised now

**Comment by neil-marcellini** [comment] 2024-06-21 19:56
Woops, sorry this got lost in my K2 since I've been hiding issues owned by others. I guess I should stop doing that, otherwise I will miss this kind stuff which actually does require my attention.


Anyways, I'm not really sure how to prioritize this one. It shouldn't be MEDIUM because that's testing tools. I'll put it as critical now, then check if I can reproduce it.

**Comment by neil-marcellini** [comment] 2024-06-21 20:34
I just tested this and it worked fine following the test steps I provided. I think it has been fixed since the original report. I'm going to close it and we can re-open the issue if we encounter a similar bug in the future.


https://github.com/Expensify/App/assets/26260477/3c6d7801-2bda-41c6-aeff-8cee755c2bd0

**Closed by neil-marcellini** 2024-06-21 20:34 UTC
Labels: Weekly, Internal, Bug
