### ISSUE TITLE
[$1000] Clicking workspace room on LHN navigates to blank page reported by @aimane-chnaif

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12240] opened 2022-10-28 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with expensifail account (A) and create a workspace if there not any
2. Invite a public domain gmail account (B) as a member of the workspace
3. Create a room in account A in the workspace where account B is a member
4. Login in Account B
5. Click on the policy room created in account A

## Expected Result:
Should open the room

## Actual Result:
Blank page appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198672762-d0dc4d7e-84c9-4f77-af59-bceb78cc6586.mp4

https://user-images.githubusercontent.com/43996225/198672802-37fc2b3d-7aec-476e-863b-9d6711cfef12.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666927845089389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2022-10-28 19:27
hmm, I actually wasn't able to reproduce this taking the steps in the OP

@kavimuru and @aimane-chnaif  would you mind clarifying reproduction steps and/or to check the reproduction steps again. 

Thanks!

**Comment by kavimuru** [comment] 2022-10-28 19:57
@abekkala I am adding the new video depicting the issue.

https://user-images.githubusercontent.com/43996225/198721662-acbbfdf5-2597-45b4-8233-ec1793eefa7c.mp4

**Comment by abekkala** [comment] 2022-10-31 16:03
@joelbettner While recreating this I came to a bit of a different outcome but still believe that there is something to fix. 

1. Login with account A that has `policyRooms` beta enabled and create a workspace if there not any
2. Invite other account (B) that has `policyRooms beta` not enabled as a member of the workspace
3. Create a new room in account A in the workspace where account B is a member
4. Login in Account B

This is where my test is different rather than: 
5. Click on the policy room created in account A

After logging int Account B i don't even have the room showing. So while this states that when clicking on the room they're provided a blank page. 
I don't have the room showing at all.

**Comment by joelbettner** [comment] 2022-10-31 18:08
Yeah, there is definitely something fishy going on here. Good for an external, though, as this is all appears to be in App. Going to add the label.

**Comment by joelbettner** [comment] 2022-10-31 18:09
Sorry @techievivek, didn't mean to assign you. 😆 The page was refreshing when I was trying to click a different button and I accidentally ended up clicking the "Demolition" button.

**Comment by abekkala** [comment] 2022-11-02 11:54
https://www.upwork.com/ab/applicants/1587774979442769920/job-details

https://www.upwork.com/jobs/~0139d76c4c5b53e2d2

**Comment by michaelhaxhiu** [comment] 2022-11-03 23:37
Hey @abekkala, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out :). 

This is posted to upwork so now we need to wait. But if you feel it's there is no interest, you can consider doubling the price ahead of the 7 day window to get more eyes on it ([context here)](https://expensify.slack.com/archives/C01SKUP7QR0/p1667516675396059).

**Comment by abekkala** [comment] 2022-11-07 12:29
doubled to $500
https://www.upwork.com/ab/applicants/1587774979442769920/job-details
https://www.upwork.com/jobs/~0139d76c4c5b53e2d2

**Comment by s77rt** [comment] 2022-11-09 12:02
a bit unrelated, can you please indicate how to enable such beta features per account?

**Comment by thesahindia** [comment] 2022-11-09 12:16
@abekkala, can you please assign me again. I was unassigned mistakenly. 
<img width="620" alt="Screenshot 2022-11-09 at 5 46 14 PM" src="https://user-images.githubusercontent.com/83179295/200828140-07247262-085a-455b-a06a-ced864a3088d.png">

**Comment by thesahindia** [comment] 2022-11-09 12:19
> a bit unrelated, can you please indicate how to enable such beta features per account?

You don't have to enable any beta for default policy rooms. If you are looking into something else then you can check [Permissions.js](https://github.com/Expensify/App/blob/main/src/libs/Permissions.js)

P.S. You can ask questions at `#expensify-open-source`

**Comment by techievivek** [comment] 2022-11-09 12:28
Assigned @thesahindia

**Comment by thesahindia** [comment] 2022-11-09 12:28
Let's re-apply "help wanted" label.

**Comment by s77rt** [comment] 2022-11-09 12:29
Is this fixed? Are you still accepting proposals?

**Comment by thesahindia** [comment] 2022-11-09 12:29
> Is this fixed? Are you still accepting proposals?

Yes, it's open to proposals.

**Comment by s77rt** [comment] 2022-11-09 13:02
Is this really considered a bug?
It's seems pretty normal to me, a user with no `policyRooms` permission is not supposed to be able to use the `policyRooms` features

**Comment by s77rt** [comment] 2022-11-09 13:07
@abekkala 
> After logging int Account B i don't even have the room showing

Same thing here, and i suppose same thing will go for the previous uploaded videos, the room is showing there just because it was there when they logged using Account A (then being stored in the localStorage) -- refreshing the page will make the room no longer appear

**Comment by abekkala** [comment] 2022-11-10 18:49
@aldo-expensify can you let me know where we're at here? Do you need the `help wanted` label re-applied?

**Comment by aldo-expensify** [comment] 2022-11-10 19:42
Oh yes, you are right, this should have the `help wanted` label.. we haven't assigned this to a contributor, @thesahindia is the C+

**Comment by abekkala** [comment] 2022-11-14 13:17
@aldo-expensify and to confirm there have been no accepted proposals yet?

**Comment by aldo-expensify** [comment] 2022-11-15 00:48
Yes, no accepted proposals

**Comment by abekkala** [comment] 2022-11-15 19:51
https://www.upwork.com/jobs/~0139d76c4c5b53e2d2
Price doubled to $1000

**Comment by puneetlath** [comment] 2022-11-17 21:21
@aldo-expensify To help us clear out the large backlog of /App bugs, we're putting the spotlight every bug in the repo already than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:  
 
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by aldo-expensify** [comment] 2022-11-17 23:41
Tried to reproduce this today in dev and in production, the gmail account can open the room just fine.

@kavimuru since you were able to reproduce this in the past, can you give this another round and check if this is still happening?

**Comment by puneetlath** [comment] 2022-11-18 16:48
@abekkala are you able to reproduce this? If not, let's go ahead and close it.

**Comment by railway17** [comment] 2022-11-21 08:56
> I am adding the new video depicting the issue.
@kavimuru 
I think my replication step is similar to yours, but I can't reproduce it from my side.
Could you kindly let me know if I missed something in my test steps?
https://www.loom.com/share/c55dcf21106c40498bf5d96cc8b8f1df

**Comment by abekkala** [comment] 2022-11-21 12:58
When attempting to recreate I still get the same outcome I did on Oct 31:

1. Login with account A that has policyRooms beta enabled and create a workspace if there not any
2. Invite other account (B) that has policyRooms beta not enabled as a member of the workspace
3. Create a new room in account A in the workspace where account B is a member
4. Login in Account B

This is where my test is different rather than:
5. Click on the policy room created in account A

After logging into Account B i don't even have the room showing. So while this states that when clicking on the room they're provided a blank page.
I don't have the room showing at all.

**Comment by thesahindia** [comment] 2022-11-21 13:30
> @kavimuru since you were able to reproduce this in the past, can you give this another round and check if this is still happening?

bump @kavimuru

**Comment by railway17** [comment] 2022-11-21 13:32
> This is expected. User shouldn't see the user created policy room if they aren't in policyRooms beta

@thesahindia 
So, this issue is referred for both accounts that are in policyRooms beta? right?
If yes, my above loom video is correct steps?

**Comment by thesahindia** [comment] 2022-11-21 13:56
The issue is about seeing the user created policy room at account B (you shouldn't see the user created policy room because account B isn't in the beta)

**Comment by iwiznia** [comment] 2022-11-21 16:31
So am I understanding this is not a bug and expected when users are not in the beta? If so, let's close.

**Comment by abekkala** [comment] 2022-11-21 18:32
> This is expected. User shouldn't see the user created policy room if they aren't in policyRooms beta

Ah, ok. yes, that makes sense and matches the reproduction I did on Oct 31. It makes sense that the account not on the beta would not see the room which is what is happening. 

I'm going to close this one out.

**Closed by abekkala** 2022-11-21 18:32 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
