### ISSUE TITLE
[$250] IOU - Payment turns into Submitted expense for a short time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42719] opened 2024-05-28 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in as a Gmail account
2. Navigate to FAB - Pay someone
3. Enter any amount
4. Enter a new Gmail address without an Expensify account
5. Create the IOU

## Expected Result:
It should remain as a paid IOU

## Actual Result:
Payment turns into Submitted expense. It reverts back in a few seconds if you open the IOU or refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/180de32b-e892-497d-97f1-407b3d0f470b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b66ef1fd86c13a9c</li>
        <li>Upwork Job ID: 1795517213267488768</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-05-28 18:02
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexrasla** [comment] 2024-05-29 02:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we are trying to solve here is that sometimes when we "Pay Someone" with an email account that is not registered with Expensify, we run into a bug that causes the text to say `owes` instead of `paid` after some time.

### What is the root cause of that problem?

The root cause of this problem is that the latest report data is not being read from the Onxy data store. The report read from the `allReports` [here](https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/libs/ReportUtils.ts#L802) is outdated when read, saying the Onxy report has a `statusNum: 1` (open), and thus rendering the default text of `iou.payerOwes`. However, the latest stored data in the Onxy report is `statusNum: 4` which causes the `ReportUtils.isSettled` function to return true, and thus returns the correct `iou.payerPaid` text [here](https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/components/ReportActionItem/ReportPreview.tsx#L216). 

### What changes do you think we should make in order to solve the problem?
In order to solve this problem, we just need to read the latest Onxy report data when checking if the report `isSettled` [here](https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/libs/ReportUtils.ts#L805). Once we have the latest data from the Onxy store, the `statusNum` will be `4` and will equal `REPORT.STATUS_NUM.REIMBURSED`, and the correct `paid` text will show on the UI.

### What alternative solutions did you explore? (Optional)

I explored changing the `isSettled` to also check if `report.statusNum == REPORT.STATUS_NUM.OPEN`, but that doesn't seem to make logical sense to see if a report is settled.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jjcoffee** [comment] 2024-05-29 09:53
Pretty sure this is a BE issue as the IOU displays correctly initially and then turns into the submitted expense once the `SendMoneyElsewhere` call completes. `SendMoneyElsewhere` returns an onyx update that sets the report to submitted:

```json
{
"stateNum": 1,
"statusNum": 1,
}
```

**Comment by greg-schroeder** [comment] 2024-06-01 02:36
Ah, fair enough. Okay I will move Internal then

**Comment by greg-schroeder** [comment] 2024-06-01 02:41
Updated

**Comment by greg-schroeder** [comment] 2024-06-03 18:40
Waiting for an internal engineer to grab this

**Comment by greg-schroeder** [comment] 2024-06-05 20:22
Same as above

**Comment by greg-schroeder** [comment] 2024-06-06 22:52
Same as above

**Comment by greg-schroeder** [comment] 2024-06-17 21:35
No updates here yet

**Comment by greg-schroeder** [comment] 2024-07-16 21:55
Still waiting for an engineer to pick this up as it's internal

**Comment by mvtglobally** [comment] 2024-08-03 04:06
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-08-09 04:24
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2024-08-14 10:34
I'm going to close this as not reproducible, but please reopen if you disagree.

**Closed by greg-schroeder** 2024-08-14 10:34 UTC
Labels: Monthly, Internal, Bug, Hot Pick
