### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Compose box - Browser's back arrow do not focus composer if first image preview open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42368] opened 2024-05-18 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: upload multiple images in chat
1. Open the first uploaded image
2. Click the "Back" button in the browser

## Expected Result:
Composer gets focused

## Actual Result:
Last uploaded image preview opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb43f2cf-5fee-4545-8f25-4066cce2a725

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013929a859819a7038</li>
        <li>Upwork Job ID: 1792347976114130945</li>
        <li>Last Price Increase: 2024-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
<li>tsa321 | Contributor | 102496699</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by jliexpensify** [comment] 2024-05-20 00:18
Can repro, adding `External` and probably fits into `VSB` best?

**Comment by tsa321** [comment] 2024-05-20 04:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue

Browser back button open other images when user opens first attachment image in attachment view (and won't close attachment view) and press the back button.

### What is the root cause of the problem?

In here:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L152-L157

When back button is pressed, the modal will close but not completely hidden yet. The code above will set modal visibility to false too early and will make:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L283-L284

`shouldAutoFocus` to be true. This will make RNMarkdownTextInput:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Composer/index.tsx#L324

autofocus to be true. 
This will make composer immediately focused even though the modal is not completelly hidden(because there is some animation). The trap focuse in react native modal will detect if focus is outside modal and will make focus back to element inside the modal, and here will eventually make the image changes to other/ next images.
More context is in here:

https://github.com/Expensify/App/issues/27237#issuecomment-1746060535

and here : https://github.com/Expensify/App/issues/27237#issuecomment-1751632831

### What changes do you think we should make in order to solve the problem?

In here we should add a condition:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L155-L156

we should add a condition, the code could be:

```
if (Modal.areAllModalsHidden()) {
    Modal.setModalVisibility(false);
    Modal.willAlertModalBecomeVisible(false);
}
```

This will check whether all modals is hidden completely. 
Then the set of `setModalVisibility` and `willAlertModalBecomeVisible` are already exist in BaseModal - hideModal:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Modal/BaseModal.tsx#L76

we could use it.
This already fixed this issue.

<br />

To solve the [closed issue](https://github.com/Expensify/App/issues/27237) that reappears above, in baseModal, we could call hide modal only in here:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Modal/BaseModal.tsx#L244

so we add hideModal inside `handleDismissModal` then remove onModalHide and onDismiss property of ReactNativeModal. This is because many types of modal (whether the modal support onModalHide or not) used in the app and put the hideModal call in here will make sure the hideModal is executed once.

**Comment by arjun-dureja** [comment] 2024-05-20 05:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When an image attachment is opened inside a chat, pressing the browser back button will result in another image displaying, rather than being navigated back to the chat.

### What is the root cause of that problem?

Inside the [AttachmentCarousel](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/index.tsx) component, the [updatePage](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/index.tsx#L79) function is unexpectedly being called when the browser back button is pressed (due to how `onViewableItemsChanged` on FlatList). This causes [onNavigate](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.tsx#L195) to be called with the first attachment in the viewable items, which then navigates the user to a different attachment.

### What changes do you think we should make in order to solve the problem?

We should detect when the back button is pressed (potentially using a ref) and then return early inside the [updatePage](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/index.tsx#L79) function. This will ensure that we're not unnecessarily fetching a different image and navigating the user to it. It will allow the user to go back to the chat



### What alternative solutions did you explore? (Optional)

I looked into updating how modals are dismissed and shown, but realized that it would be more efficient to solve this through the attachment carousel logic

**Comment by CleverWolf1220** [comment] 2024-05-20 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose box - Browser's back arrow do not focus composer if first image preview open

_This issue is reproducible for video attachments as well._

### What is the root cause of that problem?
In [`FlatList`](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L188-L215) component of `AttachmentCarousel`, `onViewableItemsChanged` is called when pressing browser back button without user interection.

### What changes do you think we should make in order to solve the problem?
We should add `waitForInteraction: true` in [`viewabilityConfig`](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L26-L30)

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-05-22 09:16
I can take over this issue as C+

**Comment by jliexpensify** [comment] 2024-05-22 10:46
All yours @DylanDylann!

**Comment by DylanDylann** [comment] 2024-05-24 07:59
@tsa321 Could you detail this point? Which logic does that?

> The trap focuse in react native modal will detect if focus is outside modal and will make focus back to element inside the modal, and here will eventually make the image changes to other/ next images.

**Comment by DylanDylann** [comment] 2024-05-24 08:04
@arjun-dureja Could you deep dive into this point and explain why the updatePage is called? Is there any reference, document that explain why onViewableItemsChanged is triggered?

> due to how onViewableItemsChanged works on FlatList

**Comment by DylanDylann** [comment] 2024-05-24 08:13
@CleverWolf1220 Why waitForInteraction will resolve this problem?

**Comment by tsa321** [comment] 2024-05-24 12:42
@DylanDylann  Focus event catch by react native modal `ModalFocusTrap`  is in here:

https://github.com/necolas/react-native-web/blob/54c14d64dabd175e8055e1dc92e9196c821f9b7d/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L137

The function of this file based on the comment is to trap focus so the focus won't leave modal, if the focus is outside of modal, the trap focus will focus last element inside modal.

The code flow is:  Composer focused (from autofocus of RNMarkdownTextInput)-> focus event triggered -> catch by trapFocus (which will try to focus child or last descendant  element of the modal -> trap focus looping through descendant element -> until last element of the image list reached -> try to to focus the element of the attachment list -> then will cause `onViewableItemsChanged` will be fired because of the focus of the trapFocus attempt and make viewable image change to last rendered (initialNumToRender is 3 so the third attachment)-> will execute the handler in:

https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/home/report/ReportAttachments.tsx#L21-L25

Then navigate back to the modal attachment.

**Comment by DylanDylann** [comment] 2024-05-28 02:28
Hi Melv, thanks for tagging me. I will complete my review today

**Comment by CleverWolf1220** [comment] 2024-05-28 02:43
@DylanDylann 

> @CleverWolf1220 Why waitForInteraction will resolve this problem?

Sorry for late response. I found that my proposal solves this issue but causes other problems.

**Comment by DylanDylann** [comment] 2024-05-28 09:48
@tsa321's [proposal](https://github.com/Expensify/App/issues/42368#issuecomment-2119658251) looks good to me. Let's go with them

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment] 2024-06-11 03:07
@DylanDylann there wasn't a regression, right?

**Comment by dangrous** [comment] 2024-06-11 15:58
Yeah I think https://github.com/Expensify/App/issues/43222 unfortunately. I think we reverted this PR and @tsa321 is working on an updated fix [here](https://github.com/Expensify/App/pull/43343) (let me know if that's right @DylanDylann and @tsa321)

**Comment by tsa321** [comment] 2024-06-11 16:08
@dangrous yes, my previous PR caused a regression. But after in latest main after bumping the latest version of `react-native-live-markdown` the regression issue and this issue are fixed. 
But I notice this issue is also happens in edit message compose box. So in my newer  [PR](https://github.com/Expensify/App/pull/43343), I am reverting my previous PR and fixing this same issue on edit compose box.

**Comment by jliexpensify** [comment] 2024-06-12 00:05
Thanks for confirming everyone - so given that this is a regression, but also isn't (?), how should we handle payments here? Is it $125, or are we keeping at $250?

**Comment by dangrous** [comment] 2024-06-12 16:20
seems sorta weird that `react-native-live-markdown` would have fixed this - and the regression - though, right? Is there some other root cause? @DylanDylann and @tsa321 let me know what you think.

Not sure about payment, if we're able to still use this to fix a bug I think maybe it's fine?

**Comment by DylanDylann** [comment] 2024-06-12 16:31
@tsa321 Could you detail the problem mentioned in the new PR? (please attach a video for new bugs)

**Comment by tsa321** [comment] 2024-06-12 17:45
@DylanDylann same issue as this issue but in edit composer box

https://github.com/Expensify/App/assets/114975543/0352851b-e0f7-47f3-9e4b-11227cb2a1dc

**Comment by DylanDylann** [comment] 2024-06-14 07:42
@jliexpensify Let's remove the awaiting payment label. The PR is in the reviewing stage

**Comment by DylanDylann** [comment] 2024-06-14 07:43
@dangrous The original issue still reproduces in other places. Give me a bit of time to deep dive into the new PR

**Comment by DylanDylann** [comment] 2024-06-17 11:37
@tsa321 I can't reproduce your bug

https://github.com/Expensify/App/assets/141406735/cf1726e9-79ce-40cb-af8f-dfcdb146f903

**Comment by tsa321** [comment] 2024-06-17 12:34
@DylanDylann you are right. I think the behavior has changes, maybe after FocusTrap implemented. Should I close my PR?

**Comment by jliexpensify** [comment] 2024-06-18 09:42
@DylanDylann removed, does this mean that I'm not paying on the 20th? If so, will remove that from the title as well.

**Comment by DylanDylann** [comment] 2024-06-18 09:46
Summary: we have worked on this issue for a long time. After the original PR was merged, It caused a regression then we reverted the PR. Fortunately, while creating a new PR, we discovered that this issue was fixed by the new FocusTrap implementation.

**Comment by DylanDylann** [comment] 2024-06-18 09:51
@jliexpensify @dangrous  I am unsure how we handle the compensation for this case. Maybe half of the compensation might be a decent solution

**Comment by jliexpensify** [comment] 2024-06-18 09:59
Thanks for the summary. Hmm yeah, this is interesting - a regression would usually mean half the standard payout, which would be $125. But the solution wasn't actually used in the end.

I feel like we shouldn't compensate since another PR fixed the issue, but honestly I'm fine with $125 for each of you since there was some work involved. @dangrous , thoughts?

**Comment by dangrous** [comment] 2024-06-20 16:30
So given that another PR fixed the issue, I think typically in case we don't move forward with payment. But would love to work with y'all on future issues!

**Comment by jliexpensify** [comment] 2024-06-20 22:56
Thanks Daniel. I've cancelled the contracts and removed the job.

**Closed by jliexpensify** 2024-06-20 22:56 UTC
Labels: External, Weekly, Bug
