### ISSUE TITLE
[HOLD for payment 2024-06-20] Troubleshoot - App is stuck offline after "Force offline" toggled on and off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43116] opened 2024-06-05 12:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to Account settings > Troubleshoot
3. Toggle on and off the "Force offline" toggle

## Expected Result:
The App should go online after switching off the "Force offline" toggle

## Actual Result:
The App is stuck in the offline state. The offline indicator remains.
User is forced to either refresh the page or force-kill the app in order to return online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/57b3c1ac-4921-4f29-9e1d-997b9e664229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment] 2024-06-05 12:19
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neil-marcellini** [comment] 2024-06-05 17:22
Frontend only bug. In fact, since this is a test tool only it shouldn't be a blocker at all

**Comment by pecanoro** [comment] 2024-06-05 18:35
@ShridharGoel Please don't post proposals until the `HelpWanted` label has been added since we usually want the original authors to fix the bugs they caused

**Comment by pecanoro** [comment] 2024-06-05 18:36
@nkdengineer This bug is coming from your PR here: https://github.com/Expensify/App/pull/41719/

**Comment by pecanoro** [comment] 2024-06-05 18:39
Assigning @Santhosh-Sellavel and @nkdengineer since they were the original author and reviewer of the PR that caused it.

**Comment by nkdengineer** [comment] 2024-06-05 18:42
I'm here. I will create a PR tomorrow morning.

**Comment by nkdengineer** [comment] 2024-06-06 03:46
@Santhosh-Sellavel this [PR](https://github.com/Expensify/App/pull/43159) is ready for preview

**Comment by strepanier03** [comment] 2024-06-20 21:48
Aaaah, I made the job before I reviewed above and it looks like this might be a fix for a bug stemming from https://github.com/Expensify/App/pull/41719. 

Seeing as this is a fix for a regression caused, I don't believe there is any payment due here.

**Comment by strepanier03** [comment] 2024-06-20 21:56
I'll circle back to this tomorrow in case there's any pushback. If not I'll cancel the job I make in Upwork and close this out.

**Comment by strepanier03** [comment] 2024-06-24 23:59
Closing out, thanks everyone!

**Closed by strepanier03** 2024-06-24 23:59 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
