### ISSUE TITLE
Tax and tax amount are updated little bit delayed in transaction thread page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39804] opened 2024-04-08 09:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-13
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**Found when executing PR :** https://github.com/Expensify/App/pull/39638
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
User is an employee of Collect workspace that has taxes.Set few tax rates 5%, 10%,0% etc

1. Go to https://staging.new.expensify.com/
2. Go to workspace chat.
3. Create a manual request with tax that is not 0%.
4.Quickly go to transaction thread

## Expected Result:
Tax and tax amount must be updated without delay in transaction thread page.

## Actual Result:
Tax and tax amount are updated in a little bit delayed way in transaction thread page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f79f0588-1494-434c-9552-a111ae8e327d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-08 09:46
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-08 09:46
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment] 2024-04-08 10:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax and tax amount are updated in a little bit delayed way in transaction thread page.

### What is the root cause of that problem?

We don't pass the `taxCode` and `taxAmount` to `getMoneyRequestInformation` function to build the optimistic transaction so `tax` and `taxAmount` are only displayed when the `RequestMoney` API is complete

https://github.com/Expensify/App/blob/ce06355873778a69c78e40e0f33e4648f3462826/src/libs/actions/IOU.ts#L2079
### What changes do you think we should make in order to solve the problem?


We should accept passing `taxCode` and `taxAmount` into `getMoneyRequestInformation` function and use it to build the optimistic transaction. So the `tax` and `taxAmount` can be displayed immediately when the request is created.
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-08 10:04
@Julesssss I can raise the PR to fix this issue ASAP if my proposal is selected.

**Comment by Julesssss** [comment] 2024-04-08 10:07
@laurenreidexpensify and @techievivek will perform initial triage before we open it up for contributors, but that shouldn't take long 👍

**Comment by MonilBhavsar** [comment] 2024-04-08 10:15
Dupe of https://github.com/Expensify/App/issues/39615

**Comment by techievivek** [comment] 2024-04-08 10:51
Great, going to close it out then, thanks.

**Closed by techievivek** 2024-04-08 10:51 UTC
Labels: Engineering, Daily, Bug
