### ISSUE TITLE
Chat - App crashes when returning online after sending message offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26204] opened 2023-08-29 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25675
## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Send a message to any chat
4. Add a reply to the message
5. Go online

## Expected Result:
App does not crash

## Actual Result:
App crashes a while after going online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d1639c07-a49a-48a3-af09-a52260a83827

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2023-08-29 14:08
![image](https://github.com/Expensify/App/assets/6474442/e18b3da5-b3c9-486a-999b-c56a1eca5038)

**Comment by s-alves10** [comment] 2023-08-29 14:11
Please check [here](https://github.com/Expensify/App/pull/25675/files#diff-fe33cbcd8e75aecbda4bf5db37848b95325493869f783ae6505f9a1fcf9c7c9cR56)

`parentReportAction` may have undefined value but the PR doesn't care about this

**Comment by pecanoro** [comment] 2023-08-29 14:11
@s-alves10 yes, I know, I posted in the PR, it's definitely that line

**Comment by s-alves10** [comment] 2023-08-29 14:13
@ginsuma can fix this shortly, I think

**Comment by pecanoro** [comment] 2023-08-29 14:17
@ginsuma seems offline so I think I am going to revert the PR and the contributor can handle it tomorrow when they come back online.

**Comment by luacmartins** [comment] 2023-08-29 18:21
I think the real root cause is actually coming from the API - https://github.com/Expensify/Web-Expensify/pull/38626/files. ReconnectApp is returning an array instead of an object and the data in Onyx is messed up.

**Comment by luacmartins** [comment] 2023-08-29 20:15
We reverted the offending PR. Removing the blocker label.

**Comment by chiragsalian** [comment] 2023-08-29 20:56
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.

**Closed by chiragsalian** 2023-08-29 20:56 UTC
Labels: Reviewing, Engineering, Weekly
