### ISSUE TITLE
[$500]  Assignee - Incorrect Focus in Assignee Notification Option During Offline-to-Online Transition

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35195] opened 2024-01-25 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, FAB > Add Title > Add assignee and share > Assignee email and checkbox appear in conversation
2,go to Settings > Preference > Enable Force offline
3, Go back to conversation > Click assignee email to open details > Go to notification > Choose notification option
4,go to Settings again> Preference > Disable Force offline
5, Go back to conversation again > Click assignee email to open details > Go to notification > Observe incorrect focus on the first option instead of the selected one

## Expected Result:
The focused option should always be the selected one

## Actual Result:
The assignee notification option is incorrectly focused when transitioning from offline to online during the assignee details in the task assignment process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3aa38188-5a97-4b18-a533-158ae08e7dd0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f11d85eb75352527</li>
        <li>Upwork Job ID: 1750638495102738432</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-01-26 07:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
In BaseSelectionList, we only init `focusedIndex` without re-updating it when value updated

```
    const [focusedIndex, setFocusedIndex] = useState(() => flattenedSections.allOptions.findIndex((option) => option.keyForList === initiallyFocusedOptionKey));
```
### What changes do you think we should make in order to solve the problem?

We can use this `useEffect` to ensure focus updated

```
    useEffect(() => {
        setFocusedIndex(flattenedSections.allOptions.findIndex((option) => option.keyForList === initiallyFocusedOptionKey));
    }, [initiallyFocusedOptionKey, flattenedSections.allOptions]);

```

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-01-26 09:19
[Proposal Updated](https://github.com/Expensify/App/issues/35195#issuecomment-1911595643)


Fix incorrect RCA and change main proposal

**Comment by isabelastisser** [comment] 2024-01-29 15:29
@eVoloshchak, can you please review the proposals? Thanks!

**Comment by isabelastisser** [comment] 2024-01-30 18:26
@eVoloshchak please provide an update. Thanks!

**Comment by eVoloshchak** [comment] 2024-01-31 14:52
I'm unable to reproduce this on new/staging/dev

https://github.com/Expensify/App/assets/9059945/2ef12829-be6e-44e4-a94d-71a852f95d26

@wildan-m, could you please double check is this is still ppresent?

**Comment by wildan-m** [comment] 2024-01-31 15:08
@eVoloshchak just reproduced it from the staging. It's better to use Chrome network throttling to make it offline, we have to click the notify button as soon as we turn on the network.

https://github.com/Expensify/App/assets/11847279/aa5a703b-0826-4e0a-8314-b103e96142ed

**Comment by eVoloshchak** [comment] 2024-02-02 00:24
Thank you @wildan-m, was able to reproduce this using your steps. Another key is to change 'Mute' to 'Immediately' while offline, not the other way around, as issue is present only for the first case

The [proposal](https://github.com/Expensify/App/issues/35195#issuecomment-1911595643) looks good to me!

🎀👀🎀 C+ reviewed!

**Comment by marcaaron** [comment] 2024-02-02 01:33
I'm not able to clearly tell what the actual issue is here. Is this something we actually need to fix? If not, I would vote to close it thoughts @isabelastisser ?

**Comment by marcaaron** [comment] 2024-02-02 01:33
Actually, sorry, I'm just going to close it and we can reopen it if there is a strong argument.

**Comment by wildan-m** [comment] 2024-02-02 01:37
@marcaaron I think it's a legit bug, the issue is focused style doesn't match the selected option on re-opened the menu. Please review again from this video.

https://private-user-images.githubusercontent.com/11847279/301207898-aa5a703b-0826-4e0a-8314-b103e96142ed.mp4

**Comment by eVoloshchak** [comment] 2024-02-03 17:57
@marcaaron, @isabelastisser,  I think this is a valid bug
Due to a combination of going online and selecting a notification option when offline, we end up with the following 
<img width="400" alt="Screenshot 2024-02-03 at 18 55 33" src="https://github.com/Expensify/App/assets/9059945/3bb1a23c-29d8-43b3-994c-43fc3c0465d8">

Incorrect item is highlighted, it should be the one with the checkmark

**Comment by isabelastisser** [comment] 2024-02-05 14:37
@marcaaron, can you please review the comments above? Do you think we should work on this?

**Comment by marcaaron** [comment] 2024-02-05 23:48
No, I think there are much more valuable issues to focus on.

**Closed** 2024-02-05 23:48 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by wildan-m** [comment] 2024-02-05 23:56
@marcaaron No worries, in the future, it might be beneficial to involve a team in assessing the significance of a bug before applying any external labels.

**Comment by marcaaron** [comment] 2024-02-06 01:01
Yes well I am not sure why the `External` label was added at the time the issue was created and no discussion could take place. Perhaps that was a mistake @lanitochka17.
