### ISSUE TITLE
[$250] Report total not updating in Report preview when submit multiple expenses

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42635] opened 2024-05-27 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716809482808369

## Action Performed:
1. Have a workspace chat with "instant submit"
2. As an employee submit a manual expense and upload a receipt 
3. Repeat this for 3 or 4 times

## Expected Result:
Report preview TOTAL amount should update any time a new expense is submitted

## Actual Result:
Report total doesn't update until you navigate away, then back or refreshing the page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/55e4abf5-15dd-4bc1-afcb-a82031cca0bd

https://github.com/Expensify/App/assets/38435837/ff1e5f25-59ad-4d70-9814-e77d9599de70

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018814f7fc6448c9e7</li>
        <li>Upwork Job ID: 1796018768198230016</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by bernhardoj** [comment] 2024-05-27 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report preview total doesn't update when adding a new expense.

### What is the root cause of that problem?
This happens when we add a new expense with a currency that is different from the report currency. BE needs to calculate the conversion first before updating the amount.

So, it's expected, but maybe confusing.

### What changes do you think we should make in order to solve the problem?

I think to improve it, we can gray out the amount as we did for the total amount in the report here when the amount is still pending.
<img width="1349" alt="image" src="https://github.com/Expensify/App/assets/50919443/98bf66c1-1a0b-4d72-bea9-ad8322241bb8">

To check whether the amount is still pending or not, we can use `ReportUtils.hasUpdatedTotal`. We already have it here
https://github.com/Expensify/App/blob/672124ba8d5f4a216a196598b6844b0dc51024a2/src/components/ReportActionItem/ReportPreview.tsx#L133

so, the next thing to do is to apply the gray-out style when `hasUpdatedTotal` is false as we did here,
https://github.com/Expensify/App/blob/672124ba8d5f4a216a196598b6844b0dc51024a2/src/components/ReportActionItem/MoneyReportView.tsx#L121

to the amount text of report preview.
https://github.com/Expensify/App/blob/b7d6a689236bac2bf2a6b0dd7648e8c719eea4d5/src/components/ReportActionItem/ReportPreview.tsx#L332

<img width="365" alt="Screenshot 2024-05-27 at 23 03 52" src="https://github.com/Expensify/App/assets/50919443/ded27498-cba7-4d29-879d-0f85838493bf">

_maybe we should disable the submit button too?_

### What alternative solutions did you explore? (Optional)
Increase the `childMoneyRequestCount` in success data instead of optimistically.
https://github.com/Expensify/App/blob/b7d6a689236bac2bf2a6b0dd7648e8c719eea4d5/src/libs/ReportUtils.ts#L4239

and decrease it when delete money request in success data too.

**Comment by strepanier03** [comment] 2024-05-30 03:08
Working on testing it.

**Comment by strepanier03** [comment] 2024-05-30 03:20
Able to repro.

**Comment by Beamanator** [comment] 2024-06-05 07:22
@sobitneupane can you please review the proposal above?

**Comment by sobitneupane** [comment] 2024-06-05 10:09
Thanks for the proposal everyone.

We need to wait for the api response to update the amount if the amount is in different currency than the report currency. We have similar issue in report total inside the IOU report, for which the total amount is grayed out until we receive the response and the total is updated. 

> Report preview TOTAL amount should update any time a new expense is submitted

@Beamanator I don't think we can achieve the expected behavior. Should we gray out the amount similar to IOU report total? Or should we display some message indicating the the total amount is being updated?

**Comment by mvtglobally** [comment] 2024-06-10 12:36
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment] 2024-06-10 14:54
@bernhardoj Whenever you have a moment, could you please take a look at [this](https://github.com/Expensify/App/issues/42635#issuecomment-2149411130).

**Comment by bernhardoj** [comment] 2024-06-10 15:22
@sobitneupane do you mean to tag @Beamanator?

**Comment by sobitneupane** [comment] 2024-06-11 06:23
> @sobitneupane do you mean to tag @Beamanator?

Yup. My bad.

**Comment by Beamanator** [comment] 2024-06-11 14:55
Sorry team! I was hoping @bernhardoj would investigate for me :trollface: 

I'll try to get to this Thurs or Friday this week :pray

**Comment by sobitneupane** [comment] 2024-06-14 04:43
Waiting for update.

https://github.com/Expensify/App/issues/42635#issuecomment-2160973748

**Comment by sobitneupane** [comment] 2024-06-18 06:48
https://github.com/Expensify/App/issues/42635#issuecomment-2167200276

**Comment by sobitneupane** [comment] 2024-06-21 06:11
We are waiting on @Beamanator for clarification of Expected output.

https://github.com/Expensify/App/issues/42635#issuecomment-2149411130

**Comment by sobitneupane** [comment] 2024-06-25 06:10
https://github.com/Expensify/App/issues/42635#issuecomment-2182071675

**Comment by strepanier03** [comment] 2024-06-27 18:33
@Beamanator - Friendly bump for an update if you have one.

**Comment by sobitneupane** [comment] 2024-06-28 06:59
https://github.com/Expensify/App/issues/42635#issuecomment-2195431328

**Comment by Beamanator** [comment] 2024-07-04 09:56
Sooo sorry @sobitneupane I was pretty wrapped up in some other stuff, can you please summarize what you want my input on? 🙏

**Comment by sobitneupane** [comment] 2024-07-05 08:04
> Expected Result:
Report preview TOTAL amount should update any time a new expense is submitted
 
 We need to wait for the api response to update the amount if the amount is in different currency than the report currency. We have similar issue in report total inside the IOU report, for which the total amount is grayed out until we receive the response and the total is updated.
 
 I don't think we can achieve the expected behavior. Should we gray out the amount similar to IOU report total? Or should we display some message indicating the the total amount is being updated?

**Comment by mvtglobally** [comment] 2024-07-11 03:43
Issue not reproducible during KI retests. (Second week)

**Comment by sobitneupane** [comment] 2024-07-12 06:36
https://github.com/Expensify/App/issues/42635#issuecomment-2210398238

**Comment by mvtglobally** [comment] 2024-07-19 03:12
Issue not reproducible during KI retests. (Third week)

**Comment by Beamanator** [comment] 2024-07-23 18:57
If this hasn't been reproducible for 3 weeks, let's close it eh?

**Closed by Beamanator** 2024-07-23 18:58 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by bernhardoj** [comment] 2024-07-24 11:08
@Beamanator it's easily reproducible.

https://github.com/user-attachments/assets/53e081a1-04d9-403e-9828-abd74a2eed16
