### ISSUE TITLE
[HOLD for payment 2024-05-06] [HOLD for payment 2024-05-03] Quick action - Fallback avatar is displayed on quick action after user avatar loads

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40996] opened 2024-04-25 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39229
## Action Performed:
1.  Go to staging.new.expensify.com
2. Submit a request to a user you haven't chatted with before
3. Click on 'FAB'

## Expected Result:
Avatar on quick action should be similar to the one loaded on report and LHN of the new user

## Actual Result:
Avatar on quick action remained to be a fallback avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/11913b70-8281-481a-b97a-dcf35c6e24b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-25 15:48
@flodnv  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment] 2024-04-26 11:18
I am looking if reverting https://github.com/Expensify/App/pull/39229 will fix this

**Comment by mountiny** [comment] 2024-04-26 11:18
Making a revert here https://github.com/Expensify/App/pull/41087

**Comment by grgia** [comment] 2024-04-26 11:48
cc @Kicu

**Comment by mountiny** [comment] 2024-04-26 12:04
This was not fully fixed with the revert, however, after refresh I have got the correct avatar there. 

https://github.com/Expensify/App/assets/36083550/24f9283b-3923-4acf-b3fd-48d71cb485a2

@Kicu would you be able to include this flow in your testing steps for the second PR?

**Comment by mountiny** [comment] 2024-04-26 12:05
Can you please comment on this issue so I can assign you and @grgia so you can then address this avatar logic, please? Thanks!

**Comment by Kicu** [comment] 2024-04-26 12:15
@mountiny if you feel like reverting is the best course of action then of course feel free to. However when Im watching your recording I don't really see how this is better.

Clearly there is an underlying bug where quick action displays the "older" avatar. In your case after revert its the first "optimistic" avatar that we get after - sure its a green one but its not the final one for the user. So the bug of not refreshing avatar correctly I think was there.

In general what I intended to fix was this changing (flashing) of one avatar to the other after the api call finishes. The original bug can be seen on your recording from 0:40 - 0:44.
So if we revert we just change the bug with fallback avatar to the old bug that was always there.

I will of course investigate how to best fix this

**Comment by mountiny** [comment] 2024-04-26 12:50
> In general what I intended to fix was this changing (flashing) of one avatar to the other after the api call finishes. The original bug can be seen on your recording from 0:40 - 0:44.
So if we revert we just change the bug with fallback avatar to the old bug that was always there.

Yep, I am aware of that, this issue existed before the PR. The other two blockers were actually fixed and we can deploy now, so that was the train of thoughts.

**Comment by mountiny** [comment] 2024-04-26 12:51
cc @Gonals for visibility as this is related to the QAB

**Comment by s77rt** [comment] 2024-04-26 17:19
@mountiny Can you assign me here

**Comment by Christinadobrzyn** [comment] 2024-05-03 09:28
@Kicu do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-05-07 05:11
@Kicu @s77rt do you know if we need a regression test for this?

**Comment by s77rt** [comment] 2024-05-07 15:25
@Christinadobrzyn We don't need a regression test for this once since it was caused by a recent PR. Any needed regression test will be added in https://github.com/Expensify/App/issues/38743

**Comment by Christinadobrzyn** [comment] 2024-05-08 07:28
Thank you @s77rt! It looks like this can be closed without payment as @Kicu is a [contractor](https://github.com/Expensify/App/issues/40996#issuecomment-2083834652). 

Closing but let me know if I'm missing anything.

**Closed by Christinadobrzyn** 2024-05-08 07:28 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by Kicu** [comment] 2024-05-29 13:19
FYI a PR that implements similar functionality that the original PR was merged. If by any chance the bug would come back please ping me. But I believe it should be fixed.
