### ISSUE TITLE
[HOLD for payment 2024-03-13] [HOLD for payment 2024-02-20] [$500] [MEDIUM] Distance - Address is duplicated when dragging one point over an empty point

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33919] opened 2024-01-04 01:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-3 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat > + > Request money > Distance
2. Click Finish
3. Enter an address and save it
4. Hold and drag the Finish point above the Start point

## Expected Result:
The Finish point will become Start point

## Actual Result:
The Finish point is duplicated to become Start point
This issue also occurs when dragging Start point with address to below empty Finish point

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bba6f2ad-5c23-467f-a80f-4a701aee807b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019049b6059932909e</li>
        <li>Upwork Job ID: 1742713103147515904</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28081723</li>
</ul></li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-04 02:36
.

**Comment by yh-0218** [comment] 2024-01-04 15:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Address is duplicated when dragging one point over an empty point
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/libs/actions/Transaction.ts#L243
This is `Onyx.merge` problem.
### What changes do you think we should make in order to solve the problem?
We can use `Onyx.set`.
But this has many problem. so we need to use `Onyx.merge` two times.
```js
 comment: {
            waypoints: null
},
```
and then
```js
comment: {
            waypoints,
},
```
then we can clear `setOptimisticWaypoints(null);`
### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment] 2024-01-04 15:39
hi, @parasharrajat when drag, waypoints value is correct.
like this {waypoint1: {lab: 1, ...}, waypoint2: {}}
but merged result is {waypoint1: {lab: 1, ...}, waypoint2: {lab: 1, ...}}
To solve this. we will get two step `Onyx.merge`
This works very well.

**Comment by stephanieelliott** [comment] 2024-01-12 20:46
Hey @tienifr any update on a PR?

**Comment by dylanexpensify** [comment] 2024-01-18 20:08
@tienifr any updates?

**Comment by stephanieelliott** [comment] 2024-01-19 19:11
Hi @tienifr can you give an update on the progress of the PR please?

**Comment by stephanieelliott** [comment] 2024-01-30 04:42
Hey @tienifr @parasharrajat can you give an update on where we are with the PR?

**Comment by dylanexpensify** [comment] 2024-02-02 20:13
Thanks @parasharrajat! Any update here?

**Comment by stephanieelliott** [comment] 2024-02-06 05:42
Still under active review, seems like we are wrapping up though

**Comment by stephanieelliott** [comment] 2024-02-08 06:59
> The perf test failure seems not related to this PR. I'll pull main tomorrow to verify if it works.

@tienifr have you had a chance to do this yet?

**Comment by CortneyOfstad** [comment] 2024-02-20 15:47
@stephanieelliott so [my GH](https://github.com/Expensify/App/issues/36366) was a regression based on this GH. Per the SO [here](https://stackoverflowteams.com/c/expensify/questions/7582/7583#7583) the payment on this GH needs to be reduced 👍 Just wanted to give you a heads up before paying this out. Thanks!

**Comment by stephanieelliott** [comment] 2024-02-21 07:32
Ah thanks @CortneyOfstad! Seems like the other issue was fixed and has the same payment date, so no need to extend the 7 day hold on this.

**Comment by francoisl** [comment] 2024-03-01 01:03
@tienifr any luck with the new fix?

**Comment by stephanieelliott** [comment] 2024-03-05 00:51
New PR is on staging

**Comment by stephanieelliott** [comment] 2024-03-14 17:07
@parasharrajat bump to complete the BZ checklist please!

**Closed** 2024-03-19 01:52 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:40
$250 approved for @parasharrajat
