### ISSUE TITLE
[HOLD for payment 2024-01-05][$500] Search - Nothing happens when hitting Enter key on the selected user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33654] opened 2023-12-27 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to Search.
2. Hit Enter.

## Expected Result:
The user in the list is selected.

## Actual Result:
Nothing happens when hitting Enter key.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2107da3e-f100-4d68-bb75-ef631e97fd43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d7fac1fa0422658</li>
        <li>Upwork Job ID: 1740463680635154432</li>
        <li>Last Price Increase: 2023-12-28</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28071858</li>
<li>Pujan92 | Contributor | 28071859</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-12-27 18:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Row isn't selected on pressing enter for option selector

### What is the root cause of that problem?
In this [PR](https://github.com/Expensify/App/pull/33491) we have added `testID` manually which seems problematic for fetching that data-testID reportid value.

### What changes do you think we should make in order to solve the problem?
Remove these static testID.

**Comment by Pujan92** [comment] 2023-12-27 19:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Row isn't selected on pressing enter for the option selector

### What is the root cause of that problem?

- In this [PR](https://github.com/Expensify/App/pull/33491) we have added `testID` for the input and on pressing an enter it will fetch `testID` of the focused element here.
https://github.com/Expensify/App/blob/9e81447833a4b9f9ea34a91f01185b0687ddb66a/src/components/OptionsSelector/BaseOptionsSelector.js#L305-L307

Due to that `focusedItemKey` will be `options-selector-input` and `focusedOption` will be undefined and it will return early.

https://github.com/Expensify/App/blob/9e81447833a4b9f9ea34a91f01185b0687ddb66a/src/components/OptionRow.js#L167-L168

### What changes do you think we should make in order to solve the problem?
We should avoid comparing the `keyForList` when the `focusedItemKey` is `options-selector-input` here.

https://github.com/Expensify/App/blob/9e81447833a4b9f9ea34a91f01185b0687ddb66a/src/components/OptionsSelector/BaseOptionsSelector.js#L307

**Comment by Beamanator** [comment] 2023-12-27 19:51
Hmm @Pujan92 it looks like https://github.com/Expensify/App/pull/33491 was merged 3 hours ago and is not on staging yet, but the bug is reproducible in staging

**Comment by situchan** [comment] 2023-12-27 19:53
@Beamanator it's automation bug. Already deployed to staging. As you see, it's in deploy checklist

<img width="716" alt="Screenshot 2023-12-28 at 1 52 44 AM" src="https://github.com/Expensify/App/assets/108292595/a0b06b5f-c8d8-4da0-aadf-6a52d939b52d">

**Comment by Pujan92** [comment] 2023-12-27 19:56
Yes, I am seeing that change with the inspect element in the staging.

**Comment by Beamanator** [comment] 2023-12-27 20:03
Ooh good catch! 

While I like your solution @Pujan92 , I don't really like that we started using `testID` OptionRow in https://github.com/Expensify/App/pull/33265/files for a non-test-related fix 🤔  do y'all think we should update that to just `id`? Or am I crazy?

**Comment by Pujan92** [comment] 2023-12-27 20:15
I agree @Beamanator , using `nativeId` makes sense instead of `testID`.

**Comment by situchan** [comment] 2023-12-27 20:24
> I don't really like that we started using `testID` OptionRow in https://github.com/Expensify/App/pull/33265/files for a non-test-related fix 🤔 do y'all think we should update that to just `id`?

Agree

**Comment by Beamanator** [comment] 2023-12-27 20:42
Nice, @Pujan92 are you up for making that change along with the change you proposed?

**Comment by Pujan92** [comment] 2023-12-27 20:43
Yes @Beamanator.

**Comment by situchan** [comment] 2023-12-27 20:43
I am up too for reviewing and testing 😄

**Comment by Beamanator** [comment] 2023-12-27 20:44
Amazing, thanks to both of you! Assigned :D

**Comment by Beamanator** [comment] 2023-12-27 22:04
PR Merged! requesting CP to staging

**Comment by mountiny** [comment] 2023-12-28 20:04
this is fixed, thank you!

**Comment by jliexpensify** [comment] 2024-01-05 04:25
Hi @situchan - bump to complete the checklist please!

**Comment by jliexpensify** [comment] 2024-01-05 04:25
Payment Summary:

- Contributor: @Pujan92 $500
- C+: @situchan $500 

[Upwork job](https://www.upwork.com/jobs/~012d7fac1fa0422658)

**Comment by situchan** [comment] 2024-01-05 04:28
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33265
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33265/files#r1437244150
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was deploy blocker, which means QA team caught this during regression test on staging build.
So no need another regression test.

**Comment by jliexpensify** [comment] 2024-01-05 05:11
Paid and closed!

Note: there were 2 payment dates (the 4th and 5th) and I'm OOO for the next 2 days so I paid now. It's the 5th in the APAC region as well :)

**Closed by jliexpensify** 2024-01-05 05:11 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
