### ISSUE TITLE
[$500] mweb - Animations missing in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36021] opened 2024-02-07 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account with gmail
3. Go offline once onboarding modal is displayed
4. Close the modal
5. Tap on bottom settings icon
6. Select Workspaces option
7. Select top settings icon
8. Select Preferences & Security menu

## Expected Result:
Animations across the application should load in offline mode

## Actual Result:
Animations missing in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/346ccf42-305f-4e88-843f-4e582c42e353

![image](https://github.com/Expensify/App/assets/93399543/44320564-bad2-4906-907f-dbeb35750a66)
![image](https://github.com/Expensify/App/assets/93399543/67aa523c-ffee-4ab6-8d27-3241aa6935f2)
![image](https://github.com/Expensify/App/assets/93399543/4ea86e57-0048-4a35-a189-53b164754419)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de6190c174f9a8cb</li>
        <li>Upwork Job ID: 1755223473745489920</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2024-02-13 23:08
I can't reproduce this and we aren't getting bites - this is off our roadmap so I'm closing for now

**Closed by adelekennedy** 2024-02-13 23:08 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by brunovjk** [comment] 2024-02-15 14:08
Sorry for the delay @adelekennedy I was investigating.
I can reproduce in `dev.new.expensify...` (both staging server or not), not just by following the steps proposed above, the animations do not work in Offline. In `staging.new.expensify...` and `new.expensify...` the animations work well in offline mode. I will continue investigating.

**Comment by brunovjk** [comment] 2024-02-15 14:38
Sorry for the delay @adelekennedy I was investigating.
I can reproduce in `dev.new.expensify...` (both staging server or not), not just by following the steps proposed above, the animations do not work in Offline.
In `staging.new.expensify...` and `new.expensify...` the animations work well in offline mode.
<details>
<summary>Reproduce-36021/dev-new-expensify - 02/15/2024</summary>


https://github.com/Expensify/App/assets/95647348/6937523e-a3f4-4adc-9d09-7152b7eb768d

</details>
<details>
<summary>Reproduce-36021/staging-new-expensify - 02/15/2024</summary>


https://github.com/Expensify/App/assets/95647348/d45bb281-a11c-4f5f-8981-1271a82c45b5

</details>

Still investigating the root causes of this issue

**Comment by brunovjk** [comment] 2024-02-15 14:49
Sorry for the delay @adelekennedy I was investigating.
I can reproduce in `dev.new.expensify...` (both staging server or not), not just by following the steps proposed above, the animations do not work in Offline.
In `staging.new.expensify...` and `new.expensify...` the animations work well in offline mode.
<details>
<summary>Reproduce-36021/dev-new-expensify - 02/15/2024</summary>


https://github.com/Expensify/App/assets/95647348/6937523e-a3f4-4adc-9d09-7152b7eb768d

</details>
<details>
<summary>Reproduce-36021/staging-new-expensify - 02/15/2024</summary>


https://github.com/Expensify/App/assets/95647348/d45bb281-a11c-4f5f-8981-1271a82c45b5

</details>

Maybe I'm missing something here, but I believe this [PR](https://github.com/Expensify/App/pull/32789) should have fixed it. I will continue to investigate the root causes of it.
