### ISSUE TITLE
[$250] Group chat - LHN preview shows "made admin" incorrectly when changing Group Chat member role

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41837] opened 2024-05-08 12:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Send a message to the group chat
5. Click on chat header > Members
6. Promote a member to admin
7. Note that group chat preview in LHN is the message sent in Step 4
8. Send a message to another chat
9. Go to Account settings > Troubleshoot
10. Select Clear cache and restart
11. After the app is restarted, note the group chat preview in LHN

## Expected Result:

The whisper message  in LHN should not be there for the incorrect user.

## Actual Result:
The group chat preview in LHN shows system message for making member admin after the app is restarted (incorrect) while there is no system message in the group chat (correct)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f491dded-818e-42ab-8374-36d128a0562e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d089c025af3fea83</li>
        <li>Upwork Job ID: 1790556079306735616</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment] 2024-05-08 12:26
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment] 2024-05-15 01:34
<img width="1441" alt="image" src="https://github.com/Expensify/App/assets/14225673/f3dfff8f-bdf9-4807-ab84-ff7c8a25eee8">
This is odd cause the message shows up only in LHN but not in the room!

**Comment by MrMuzyk** [comment] 2024-05-17 09:12
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2024-05-17 09:56
I've managed to reproduce that. Can you specify what expected result should be here?

Should we display message about making a new admin in chat and LHN is previewing the message correctly or should we preview last message send in chat and ignore info about making a new admin?

**Comment by jayeshmangwani** [comment] 2024-05-20 06:48
IMO, the Expected result should be that the system message should display a message in chat that `made ${user} an admin`, but what is your opinion about the expected behavior here @anmurali ?

**Comment by MrMuzyk** [comment] 2024-05-20 14:06
In that case I believe the issue is on the BE side. This message about making someone an admin is a whisper targeted only at selected account IDs and not a message sent to the whole chat room. 

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionsList.tsx#L200-L211

`shouldReportActionBeVisible` filters out any message that is a whisper to an account that has different ID than the currently logged in user.

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportActionsUtils.ts#L539-L542

<img width="1920" alt="Screenshot 2024-05-20 at 15 59 53" src="https://github.com/Expensify/App/assets/23487612/9a213748-a95d-4cf2-86a9-7feb28a8765a">

In order for the message to display properly it should not be a whisper

**Comment by jayeshmangwani** [comment] 2024-05-21 07:18
Hi @marcaaron I am tagging you here because this issue is related to Group creation flow. Recently, you have worked on this [PR](https://github.com/Expensify/App/pull/39757), and in that PR we have added a comment about [system messages](https://github.com/Expensify/App/pull/39757#issuecomment-2052616418), so the issue we are getting here is:

If we make a user to admin and then refresh the page, we are getting the text `made {user} an admin` for the LHN alternate text, but not getting the system message inside the chat,

<img width="1680" alt="Screenshot 2024-05-20 at 8 54 14 PM" src="https://github.com/Expensify/App/assets/35371050/f4453870-13d6-46bd-a6cf-ffdbb0dc7df4">

So we have two questions:

1. The system message `made {user} an admin`  should be shown in the chat ? If yes, it[ looks like a BE issue](https://github.com/Expensify/App/issues/41837#issuecomment-2120535124); if Not...
2. Should we hide the `made {user} an admin` on LHN alternate text and should show the last text from the report?

**Note: Removed User and Invited User system message shown in both chat and the LHN.**

**Comment by marcaaron** [comment] 2024-05-21 20:44
>The system message made {user} an admin  should be shown in the chat

Incorrect, this should only appear for the user who's role was changed.

>Should we hide the made {user} an admin on LHN alternate text and should show the last text from the report?

I would say that it should not. It's a whisper message intended for one person so it should not appear. Can you verify where this data comes from?

**Comment by marcaaron** [comment] 2024-05-21 20:46
I updated the title and description as there were some things incorrect about it.

**Comment by MrMuzyk** [comment] 2024-05-22 09:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group chat - LHN preview shows "made admin" incorrectly when changing Group Chat member role

### What is the root cause of that problem?

Component displaying the text on the LHN uses this util method and line below is causing the issue

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/OptionsListUtils.ts#L635

`report?.lastMessageText` returns text for the last message sent in this report but this isn't the last message that should be displayed to the end user. 

I'm rather sure that this is correct behaviour from the BE side (would be great to double check with someone who is certain of it)

### What changes do you think we should make in order to solve the problem?


We should update this line so it returns text from last visible report action instead. 

`lastReportAction` is such action that is created in the beginning of this util method so we can reuse that here

```    return lastMessageTextFromReport || (lastReportAction?.message?.[0]?.text ?? '');```

<img width="1410" alt="image" src="https://github.com/Expensify/App/assets/23487612/3146482b-186f-4a7b-a18d-7949770f8f30">

### What alternative solutions did you explore? (Optional)

If it would be case that BE returns incorrect `lastMessageText` field inside the report then it would have to be fixed on the BE side. Like I've stated in root cause I'm not 100% sure - technically it was lastMessageText but this message is not meant to be displayed to end user

**Comment by marcaaron** [comment] 2024-05-28 21:26
Ok, hmm I _believed_ that we filter out the inaccessible whisper messages when calling `OpenReport`. But looking more into it seems that we have specifically filtered them by type. 🤔 

@rlinoz I found you in a recent blame for the filtering logic from [this PR](https://github.com/Expensify/Auth/pull/10734/files). Do you agree with what I said above? Seems like any and all whisper messages should not be returned in the `getChats()` call. WDYT?

**Comment by marcaaron** [comment] 2024-05-28 21:28
The only one's that are there are `ACTION_ACTIONABLEMENTIONWHISPER` and `ACTION_ACTIONABLEREPORTMENTIONWHISPER` so I would assume we have this problem for any new whisper messages we added (surprised it did not show up until now if I am right).

Also brings up a good question about whether we should continue to support the `lastMessageText` field or do something else. I'm not sure the best way to handle this though and my plate is full atm we should bring this to Slack if possible. Gonna slap an `Internal` label on this one and hopefully there's enough context.

**Comment by marcaaron** [comment] 2024-05-29 19:16
Hopefully, a good side effect where the LHN has the correct message in it 😄

**Comment by jayeshmangwani** [comment] 2024-06-04 04:51
Not overdue, BE issue so will be handled internally

**Comment by jayeshmangwani** [comment] 2024-06-11 14:05
@rlinoz Has an internal issue been created to handle [this backend bug](https://github.com/Expensify/App/issues/41837#issuecomment-2136141469), or should we assign someone to handle it?

**Comment by rlinoz** [comment] 2024-06-11 14:39
No internal issue has been created, I believe we can add the hot pick to this one though, since it already has the internal label.

**Comment by jayeshmangwani** [comment] 2024-06-17 09:56
Hot Pick label added, though waiting to be picked by an internal engineer.

**Comment by jayeshmangwani** [comment] 2024-06-21 05:26
Waiting for an internal engineer to grab this

**Comment by anmurali** [comment] 2024-06-26 03:43
All things split is paused. So would make sense to make this a Monthly.

**Closed** 2024-09-09 18:42 UTC
Labels: Monthly, Internal, Bug, Hot Pick
