### ISSUE TITLE
[DISTANCE] MEDIUM: [$500] Only allow admins to manually edit distance request amount and currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30654] opened 2023-10-31 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698001650923669

## Action Performed:
1. Make a new distance request.
2. Go to the request.
3. After it has loaded, go offline.
4. Change the currency in the amount.
5. Go back online.
## Expected Result: 
The currency should be changed
## Actual Result: 
The currency is not changed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/7da7bf96-a473-426d-9b79-6181517efcf1

https://github.com/Expensify/App/assets/38435837/cbd56d3a-7c42-4be9-b055-25267ba2174b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9c85c43ba1d6c35</li>
        <li>Upwork Job ID: 1719835802236735488</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 27772651</li>
<li>DylanDylann | Contributor | 27772653</li>
<li>esh-g | Reporter | 27772658</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Gonals</details>

**Comment by DylanDylann** [comment] 2023-10-31 20:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Unable to change currency when offline in distance request

### What is the root cause of that problem?
- Currently, when calling ```UpdateDistanceRequest``` with currency data, BE does not update the currency, it still returns the original currency.
- When the user is in offline mode, and updates currency from "A" to "B", ```optimisticData``` is update to B. Then turn on the network, API will be called and updated to currency to A. That leads to the current behavior.

### What changes do you think we should make in order to solve the problem?


- We should avoid user from changing currency in case edit distance request like below:
- Update 
https://github.com/Expensify/App/blob/ed5009dd51bd90aff917b6566b51056519fef739/src/pages/iou/steps/MoneyRequestAmountForm.js#L240
to
```
                <TextInputWithCurrencySymbol
                    isDisabled={TransactionUtils.isDistanceRequest(transaction)}
```

**Comment by samilabud** [comment] 2023-11-02 03:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to change currency when offline in distance request

### What is the root cause of that problem?
When we update the currency using 'distance request' we use a method called _IOU.updateDistanceRequest_, this method doesn't update the currency (this behavior occurs online - if you update the page you can see the currency is the first one you selected- and offline).

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/EditRequestPage.js#L128

These are the API request and response of _IOU.updateDistanceRequest_ function:

<img width="855" alt="API Request payload" src="https://github.com/Expensify/App/assets/5216036/5b071f8e-3ca8-485b-a67e-376bd2b7a2be">

<img width="871" alt="API Response DOP" src="https://github.com/Expensify/App/assets/5216036/c08d21df-4a31-4914-8c2c-c22a35a42b38">


### What changes do you think we should make in order to solve the problem?
I think the simplest change is to call the function (used in the manual request) _IOU.editMoneyRequest_ method when using 'distance request' as shown below :

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/EditRequestPage.js#L126

```
function editMoneyRequest(transactionChanges) {
        if (TransactionUtils.isDistanceRequest(transaction)) {
            IOU.updateDistanceRequest(transaction.transactionID, report.reportID, transactionChanges);
            IOU.editMoneyRequest(transaction.transactionID, report.reportID, transactionChanges);
        } else {
            IOU.editMoneyRequest(transaction.transactionID, report.reportID, transactionChanges);
        }
        Navigation.dismissModal(report.reportID);
    }

```

This is the result:

https://github.com/Expensify/App/assets/5216036/fa2907be-ef64-4c98-b038-04f642c7462a

**Comment by twisterdotcom** [comment] 2023-11-07 14:59
Some internal discussions actually ongoing now about whether to even allow changing the currency of a distance request. Please HOLD. https://expensify.slack.com/archives/C03SSAQ7P/p1698248408690509

cc @neil-marcellini

**Comment by twisterdotcom** [comment] 2023-11-09 21:48
Okay, @neil-marcellini am I right now that we don't want to allow for changing the currency at all now? Once it's created, the currency is set by the workspace it's created on.

**Comment by alitoshmatov** [comment] 2023-11-13 09:31
Reviewing

**Comment by alitoshmatov** [comment] 2023-11-13 16:32
@DylanDylann proposal looks good and tests well, also it covers all cases where page is accessed through deeplink. 

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2023-11-13 16:33
@samilabud Your proposal misses a point which we are not allowing changing currency

**Comment by twisterdotcom** [comment] 2023-11-13 21:12
@neil-marcellini would love your technical input here. We won't allow currency changes at all now, we will just eventually allow moving different currency distance expenses between different currency workspaces. If so, I think we should close this, as _offline_ is working fine and we would need to change _online_.

**Comment by twisterdotcom** [comment] 2023-11-21 13:50
Asked Neil in Slack here just to double check my understanding: https://expensify.slack.com/archives/C01SKUP7QR0/p1700574586634009

**Comment by neil-marcellini** [comment] 2023-11-21 17:22
@MonilBhavsar may I take over this issue?

**Comment by twisterdotcom** [comment] 2023-11-21 17:42
Okay, we're good to go here. @neil-marcellini has reviewed, so I'm going to assign @DylanDylann.

**Comment by DylanDylann** [comment] 2023-11-23 10:48
@neil-marcellini Currently, we cannot change the currency in the distance request, so should we need the BE fix?

**Comment by MonilBhavsar** [comment] 2023-11-23 11:10
Looks like Neil is taking a look

**Comment by DylanDylann** [comment] 2023-11-27 17:04
@neil-marcellini Please help check my comment https://github.com/Expensify/App/issues/30654#issuecomment-1824203318

**Comment by neil-marcellini** [comment] 2023-11-29 19:56
Thanks for the ping @DylanDylann. I will get started on the backend changes soon and let you know when they are done.

**Comment by alitoshmatov** [comment] 2023-12-01 09:30
Waiting for backend changes

**Comment by neil-marcellini** [comment] 2023-12-01 16:51
Starting now 👀

**Comment by neil-marcellini** [comment] 2023-12-01 18:23
Not overdue

**Comment by neil-marcellini** [comment] 2023-12-02 01:17
I'm still working on the changes based on @DylanDylann's [proposal](https://github.com/Expensify/App/issues/30654#issuecomment-1787959880). 
> We also need update from BE follow this requirement:
> 1. We should not allow editing the amount or currency when creating distance request
> 2. We only allow the admin of the workspace to edit the amount or currency when editing distance request.

I have implemented item 2. I'll work on item 1. From the root cause it sounds like we need to add another point.

> Currently, when calling UpdateDistanceRequest with currency data, BE does not update the currency, it still returns the original currency.

3. Verify that the updated currency is returned when an admin edits a distance request

**Comment by neil-marcellini** [comment] 2023-12-02 01:21
Oh actually point 1 is already true on the backend.

**Comment by neil-marcellini** [comment] 2023-12-02 01:50
Ok the backend PR is under review!

**Comment by DylanDylann** [comment] 2023-12-07 15:46
@neil-marcellini Please ping me once the BE is done. Thanks

**Comment by neil-marcellini** [comment] 2023-12-08 17:31
Sorry for the delay. Review went slowly and I need to fix some additional tests. I'll ping you when it's ready.

**Comment by neil-marcellini** [comment] 2023-12-08 17:31
Removing reviewing until I get both backend PRs ready again.

**Comment by neil-marcellini** [comment] 2023-12-09 00:07
The Web-E PR was already merged. The [Auth PR](https://github.com/Expensify/Auth/pull/9321) is holding on that and is waiting for a review.

**Comment by neil-marcellini** [comment] 2023-12-13 19:04
The Auth PR has changes requested, because we switched to a new command while I was working on this, so I need to move the changes over there before putting this up for review again.

**Comment by neil-marcellini** [comment] 2023-12-19 15:57
I'll try to squeeze in some updates to my backend PR tomorrow.

**Comment by neil-marcellini** [comment] 2023-12-20 17:32
I got the backend PR up for review again

**Comment by neil-marcellini** [comment] 2023-12-26 16:40
The backend PR was finally merged and should be deployed today. @DylanDylann you can probably finish off the frontend PR soon.

**Comment by neil-marcellini** [comment] 2023-12-27 17:48
The Auth PR was deployed

**Comment by DylanDylann** [comment] 2023-12-28 03:27
Thanks @neil-marcellini

**Comment by neil-marcellini** [comment] 2023-12-28 20:31
❗ 🔥 Heads up, I'm going to be OOO working 0% from 1/1-1/12/24. I'll be back on 1/15/24. I'm planning to work 50% tomorrow 12/29. Please feel free to un-assign, re-assign, whatever. When I return I'll pick back up whatever I can and do my best to GSD in order of priority. I will also post all of my assigned issues in #engineering-chat in Slack to try to recruit volunteers.

**Comment by alitoshmatov** [comment] 2024-01-04 13:35
@twisterdotcom PR is ready for a review by internal engineer, can you reassign another internal for engineer since @neil-marcellini is OOO till 15th January

**Comment by twisterdotcom** [comment] 2024-01-04 14:51
@alitoshmatov could you link the PR? I'll find an engineer.

**Comment by twisterdotcom** [comment] 2024-01-04 14:52
Eugh, it will do the same for Neil. Let me see who's on the Wave 5 team.

**Comment by alitoshmatov** [comment] 2024-01-04 14:55
The PR is here https://github.com/Expensify/App/pull/31778

**Comment by twisterdotcom** [comment] 2024-01-18 17:39
Weird we didn't get the automation. Okay, gonna send offers to you all.

**Comment by twisterdotcom** [comment] 2024-01-18 17:50
Gonna close, no need for regression.

**Closed by twisterdotcom** 2024-01-18 17:50 UTC
Labels: Reviewing, Weekly, Internal, Bug, Distance
