### ISSUE TITLE
[HOLD for payment 2024-05-22] Tag – “Add tag” button missing when create new workspace and enable tags

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42092] opened 2024-05-13 18:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Create new workspace
4. Click on More features and enable tags

## Expected Result:
“Add tag” button appears in the top right corner

## Actual Result:
“Add tag” button missing in the top right corner when create new workspace and enable tags

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bf3cec91-9537-48f3-bb34-2e9336e83e5c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-05-13 18:03
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment] 2024-05-13 18:49
Seems like a regression caused by https://github.com/Expensify/App/pull/41351 cc @s77rt @roryabraham

**Comment by s77rt** [comment] 2024-05-13 19:27
Working on it

**Comment by Beamanator** [comment] 2024-05-14 08:03
PR CP'd! https://github.com/Expensify/App/pull/42106#issuecomment-2109441763

**Comment by Beamanator** [comment] 2024-05-14 09:35
Testing well on staging! 👍  (noted here - https://github.com/Expensify/App/pull/42106#issuecomment-2109730189)

**Comment by bfitzexpensify** [comment] 2024-05-23 15:11
This was a fix for a regression related to https://github.com/Expensify/App/issues/41279, so no payment here. Closing this out.

**Closed by bfitzexpensify** 2024-05-23 15:11 UTC
Labels: Engineering, Daily, Awaiting Payment
