### ISSUE TITLE
[HOLD for payment 2024-11-20] [$125] [Search v2.2] Remove Invoice type from LHN if workspaces don't have it enabled

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#51620] opened 2024-10-28 22:39 UTC
## Problem
We currently show `Invoice` as a Search type in the LHN for users, but that's confusing if they never enabled that feature

## Solution 
Avoid confusion and remove the `Invoice` type if users don't have this option enabled in any of their policies
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851031006738225317</li>
        <li>Upwork Job ID: 1851031006738225317</li>
        <li>Last Price Increase: 2024-11-04</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104759689</li>
<li>jaydamani | Contributor | 104770908</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by luacmartins** [comment] 2024-10-28 22:57
> only push it to the array if policyID from query is undefined

I think this part is incorrect. We want to push it to the array if you have any policies with invoices enabled in Onyx.

**Comment by jaydamani** [comment] 2024-10-29 03:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove Invoice type from LHN in Search if it is not enabled

### What is the root cause of that problem?

Invoice type is added to search LHN from [here](https://github.com/expensify/app/blob/b2d14a13b2dac82be60c79b6959bda14741e01f1/src/pages/Search/SearchTypeMenu.tsx#L91) and it is always added to the LHN Menu even if user does not use invoices.

### What changes do you think we should make in order to solve the problem?

A user will only use invoices if it is enabled in one of their workspaces or they have received an invoice from somebody else as admins can send Invoice to users outside their workspace and the user will not be added to workspace. So, we need to update [here](https://github.com/expensify/app/blob/b2d14a13b2dac82be60c79b6959bda14741e01f1/src/pages/Search/SearchTypeMenu.tsx#L91) to only add Invoices to menu items if they have a workspace with invoices or an invoice has been sent to them. The updated logic would look like this. The Implementation can be done like below:

Current:

https://github.com/Expensify/App/blob/b2d14a13b2dac82be60c79b6959bda14741e01f1/src/pages/Search/SearchTypeMenu.tsx#L71-L108

New:

```js
const session = useOnyx(ONYXKEYS.SESSION)

const typeMenuItems = [
    ...
]

if (PolicyUtils.hasWorkspaceWithInvoices(session?.email) || ReportUtils.hasInvoiceReports()) typeMenuItems.push({
    title: translate('workspace.common.invoices'),
    type: CONST.SEARCH.DATA_TYPES.INVOICE,
    icon: Expensicons.InvoiceGeneric,
    getRoute: (policyID?: string) => {
        const query = SearchQueryUtils.buildCannedSearchQuery({type: CONST.SEARCH.DATA_TYPES.INVOICE, status: CONST.SEARCH.STATUS.INVOICE.ALL, policyID});
        return ROUTES.SEARCH_CENTRAL_PANE.getRoute({query});
    },
})

typeMenuItems.push({
    title: translate('travel.trips'),
    type: CONST.SEARCH.DATA_TYPES.TRIP,
    ...
})
```

#### Policies with Invoice
We can reuse some of the logic from the Send Invoice button for FAB, which currently looks like this:

https://github.com/Expensify/App/blob/ce0161406526fe7b333cbca7c08f93a74f5204e5/src/libs/PolicyUtils.ts#L597-L612

so, hasWorkspaceWithInvoices will look like:
```js
function hasWorkspaceWithInvoices(currentUserLogin) {
    const activePolicies = getActivePolicies(allPolicies);
    return activePolicies.some((policy) => shouldShowPolicy(policy, NetworkStore.isOffline(), currentUserLogin) && policy.areInvoicesEnabled);
}
```

#### Invoice Report to external members
```js
function hasInvoiceReports() {
    const allReports = ReportConnection.getAllReports();
    return allReports.some(report => isInvoiceReport(report))
}
```

Note: all the code samples are for explaination only and can be improved during PR

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by alexpensify** [comment] 2024-10-31 15:25
@eVoloshchak - when you get a chance, can you please review if one of these proposals will fix the issue? Thanks!

**Comment by alexpensify** [comment] 2024-11-02 05:22
@eVoloshchak any update here? Thanks!

**Comment by alexpensify** [comment] 2024-11-05 02:02
@eVoloshchak please keep me posted if you are unable to review. I will need to reassign by Wednesday if no answer.

**Comment by luacmartins** [comment] 2024-11-05 23:14
@eVoloshchak any updates here?

**Comment by luacmartins** [comment] 2024-11-05 23:16
Actually, @Krishna2323's proposal looks good, so gonna assign the issue to him.

**Comment by luacmartins** [comment] 2024-11-05 23:26
@Krishna2323 please prioritize this PR as it's a high value one

**Comment by luacmartins** [comment] 2024-11-05 23:29
Love it! Thank you.

**Comment by luacmartins** [comment] 2024-11-06 02:14
AH I see. Thanks for bringing that up. @jaydamani are you available to work on the PR?

**Comment by jaydamani** [comment] 2024-11-06 03:19
I am not available right now but I can work on it tomorrow so if it's urgent please assign it to @Krishna2323 Also, I think whoever implements it should be compensated so, if it's assigned to @Krishna2323 then they should be compensated.

**Comment by luacmartins** [comment] 2024-11-06 15:48
Sure, I'll reassign to you @jaydamani since you're proposal was more complete as @Krishna2323 pointed out above.

**Comment by jaydamani** [comment] 2024-11-06 20:20
Starting work on this

**Comment by jaydamani** [comment] 2024-11-06 23:24
Created [PR](https://github.com/Expensify/App/pull/52148)

**Comment by alexpensify** [comment] 2024-11-21 06:17
Payouts due: 2024-11-20

- [ ] Contributor: $250 @jaydamani - paid via Upwork 
- [ ] Reviewer: $250 @rushatgabhane - Please submit a Chat request and please confirm if there should be a regression test here. 

Upwork job is [here](https://www.upwork.com/jobs/~021851031006738225317).

**Comment by alexpensify** [comment] 2024-11-25 19:53
Closing

**Closed by alexpensify** 2024-11-25 19:53 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-11-26 13:44
$125 approved for @rushatgabhane
