### ISSUE TITLE
Task – Assignee custom name is not visible in the task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39426] opened 2024-04-02 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468742
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat
4. Create a task and assign it to a user with a custom name

## Expected Result:
Assignee custom name is visible in the task

## Actual Result:
Assignee custom name is not visible in the task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/02f27da6-691d-4908-8cf4-cf2c1e1c4967

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a6cf192e2c42cc8</li>
        <li>Upwork Job ID: 1775237848166469632</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-02 17:35
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-02 17:35
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment] 2024-04-02 18:45
Taking a look now

**Comment by luacmartins** [comment] 2024-04-02 19:00
I believe this is caused by https://github.com/Expensify/App/pull/38957

**Comment by luacmartins** [comment] 2024-04-02 19:03
I'm gonna demote this as a blocker since it doesn't really affect the functionality that much and let the original contributor work on a fix.

**Comment by luacmartins** [comment] 2024-04-02 19:03
@ahmedGaber93 could you please work on a fix for this regression since it comes from your PR? cc @sobitneupane @puneetlath

**Comment by luacmartins** [comment] 2024-04-02 19:04
Reassigning to @sobitneupane since they reviewed the offending PR.

**Comment by ahmedGaber93** [comment] 2024-04-02 19:11
> @ahmedGaber93 could you please work on a fix for this regression since it comes from your PR?

I will take a look, but about the expected behavior, we decide based on here https://github.com/Expensify/App/issues/38079#issuecomment-2011276957 and here https://github.com/Expensify/App/issues/38079#issuecomment-2014623920 to prioritize login over display name for all the mentions in the app including task preview.
@luacmartins

**Comment by luacmartins** [comment] 2024-04-02 19:17
Hmm so is this the new expected behavior @puneetlath ?

**Comment by puneetlath** [comment] 2024-04-02 19:24
Yes, this is expected. We decided to make mentions consistent and always look the same, including in task previews. We should update whatever testrail test is currently testing this for that. I'll post in #qa.

**Comment by luacmartins** [comment] 2024-04-02 19:29
Thanks for confirming. Seems like we can just close this issue then!

**Closed by luacmartins** 2024-04-02 19:29 UTC
Labels: External, Engineering, Daily

**Comment by isagoico** [comment] 2024-04-03 01:02
TC has been updated to reflect this new behavior🎉 

![image](https://github.com/Expensify/App/assets/44479856/c05c5b44-c995-479f-88d8-b29ae53e5496)

**Comment by puneetlath** [comment] 2024-04-03 01:21
Great, thanks @isagoico!
