### ISSUE TITLE
[$500]  BA - Last character of input fields is removed after coming back to BA form

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32386] opened 2023-12-01 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces
2. Select a workspace
3. Go to "Bank account"
4. Click on "Connect manually"
5. Enter the routing number and the account number
6. Click on the arrow to go back
7. Click on "Connect manually" again

## Expected Result:
The information entered before should remain untouched

## Actual Result:
The last character of the fields is being removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4e8fbce6-1bee-444a-9b85-4eb2d402d37d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01350ef5348b72e4c8</li>
        <li>Upwork Job ID: 1731701564650864640</li>
        <li>Last Price Increase: 2023-12-04</li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-12-04 15:52
@bernhardoj thanks for the initial investigation. Yeah, @aimane-chnaif that's a good question. It seems like there were a couple refactors and reverts of this code which caused the variable names `value` and `inputValue` to get out of sync. The more small fixes we merge without reverting, the harder it is to do a revert.

@luacmartins, your opinion here would be helpful on how you think we should proceed.

**Comment by luacmartins** [comment] 2023-12-04 17:51
I think we should just revert the PR since it caused multiple blockers and let the original contributor work on a fix since this is still within the regression period. Here's the revert PR - https://github.com/Expensify/App/pull/32440

**Comment by yuwenmemon** [comment] 2023-12-04 20:50
Revert deployed, closing this out!

**Closed by yuwenmemon** 2023-12-04 20:50 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug

**Comment by s77rt** [comment] 2023-12-22 22:05
I don't think the checklist applies here as the offending PR got reverted.
