### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Update page header and empty state for Workspaces page

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#43022] opened 2024-06-04 07:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.78-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @shawnborton @Expensify/design 
**Slack conversation:** [Internal](https://expensify.slack.com/archives/C03TME82F/p1717432659728369)

## Action Performed:
1. Create a new account and then navigate to Settings > Workspaces

## Expected Result:
1. The page header for Workspaces should use the same illustrated header style we use elsewhere in Settings.
2. The empty state for workspaces should use an h1 instead of an h2 for "Create a new workspace"

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

**Current:**
![image](https://github.com/Expensify/App/assets/2319350/3b5d4a4c-7a18-4e44-9612-f75e6bb379b4)

**Proposed changes:**
![image](https://github.com/Expensify/App/assets/2319350/7115f1b7-c74f-4dd5-b9f5-c5b3e3fac587)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d21d805d8f99e07</li>
        <li>Upwork Job ID: 1799170581237331921</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102685032</li>
<li>Nodebrute | Contributor | 102685035</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by shawnborton** [comment] 2024-06-04 07:08
This should be a super easy fix, so I think $125 is reasonable here.

**Comment by shawnborton** [comment] 2024-06-04 07:45
@dragnoir looks like you quickly commented on the issue to get your proposal in first and then made edits. This is what I saw come through:
![CleanShot 2024-06-04 at 09 30 51@2x](https://github.com/Expensify/App/assets/2319350/44b35df2-d5ac-45be-ad03-a768694a9c24)

Checking with our internal team what our expected guidelines are with that sort of behavior. In the meantime, I don't think this one has been opened up for proposals just yet anyways.

**Comment by slafortune** [comment] 2024-06-07 20:04
Sorry for my delay!

**Comment by shawnborton** [comment] 2024-06-10 14:21
How is this one going? Do we have any acceptable proposals here?

**Comment by getusha** [comment] 2024-06-10 17:11
Reviewing proposals, i'll update today

**Comment by getusha** [comment] 2024-06-11 01:17
I think this is a super simple straight forward issue,
I suggest going with @Nodebrute's [proposal](https://github.com/Expensify/App/issues/43022#issuecomment-2146788028) that had a complete information about the solution (before making edits)
Please avoid making extensive edits after posting a proposal, otherwise the proposal will not be considered thanks.

🎀 👀 🎀 C+ Reviewed.

**Comment by slafortune** [comment] 2024-07-03 02:10
@Nodebrute Paid ✅ 
@getusha Can you please complete the checklist and accept the [automatic offer](https://www.upwork.com/nx/wm/offer/102685035)?

**Comment by getusha** [comment] 2024-07-03 15:27
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: **N/a this a design change**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **No, it's a simple UI modification**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by getusha** [comment] 2024-07-03 15:28
@slafortune i'd like to request the payment via ND

**Comment by slafortune** [comment] 2024-07-03 15:35
Ah Yes @getusha  - great!  This GH was created on June 4th, after May 25 so that will work!  I'll cancel the offer in Upworks.

Please complete the checklist for NewDot payment to be approved.

**Comment by getusha** [comment] 2024-07-08 16:16
https://github.com/Expensify/App/issues/43022#issuecomment-2206553332
here is the checklist

**Comment by JmillsExpensify** [comment] 2024-07-08 17:37
Ah thanks! I'll reach out to Stevie via NewDot to get the payment summary.

**Comment by slafortune** [comment] 2024-07-08 20:03
Since the regression was more than the 7 day holding period, there is not a penalty.

Payment is due **JULY 10TH** in NewDot
@getusha - Role C+ is due $250

**Comment by JmillsExpensify** [comment] 2024-07-10 16:23
$250 approved for @getusha

**Closed** 2024-07-10 16:42 UTC
Labels: External, Weekly, Awaiting Payment, Bug
