### ISSUE TITLE
iOS/mWeb - Chat - Message compose box can be moved 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9014] opened 2022-05-14 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Open any chat
4. Try to write a message and use fingers to move the compose box

## Expected Result:
Compose box should be static and should not be able to move

## Actual Result:
The compose box can be moved independently.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.60-0

**Reproducible in staging?:**  Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168422372-6889bbda-82d1-4862-8114-08e3df19a279.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-05-15 22:58
This is a duplicate of https://github.com/Expensify/App/issues/5894 – the attempted solution `iosSafariAutoScrollback` never really worked and created other issues, so was reverted [here](https://github.com/Expensify/App/pull/8571).

There's some relevant info [here](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d)

**Comment by roryabraham** [comment] 2022-05-15 23:00
Going to close this out as a dupe and reopen https://github.com/Expensify/App/issues/5894

**Closed by roryabraham** 2022-05-15 23:00 UTC
Labels: Engineering, Daily
