### ISSUE TITLE
Threads - Nothing happens when Clicking Profile picture in detail of Group Chat thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39760] opened 2024-04-05 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife+hl5@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any Group chat.
2. Start a thread
3. Click on the header of the thread to go to the Details page
4. Hover over the profile picture. Notice that there is a Pointer Cursor.
5. Click on the Profile Picture. Notice that nothing happens when clicking.

## Expected Result:
If there is a pointer cursor. Clicking the profile must display the picture in full size.

## Actual Result:
Clicking the profile does nothing even if there is a Pointer cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5f04dd02-7465-4a37-b403-b3390bd4b00c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-05 18:23
We think this issue might be related to the #vip-vsb.

**Comment by shahinyan11** [comment] 2024-04-05 18:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Threads - Nothing happens when Clicking Profile picture in detail of Group Chat thread
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/0e6dba4fe604421dd30103b9a065deea3460b870/src/components/RoomHeaderAvatars.tsx#L21C9-L23C10) we prevent navigation to avatar page when for group chats 
### What changes do you think we should make in order to solve the problem?
Remove [this](https://github.com/Expensify/App/blob/0e6dba4fe604421dd30103b9a065deea3460b870/src/components/RoomHeaderAvatars.tsx#L21C9-L23C10) condition 

### What alternative solutions did you explore? (Optional)
Or if this is a expected behavior we can also change styles to remove pointer

**Comment by greg-schroeder** [comment] 2024-04-05 21:43
This might be expected - can you confirm this comment https://github.com/Expensify/App/issues/39760#issuecomment-2040418031 @marcaaron? <3

**Comment by marcaaron** [comment] 2024-04-06 00:07
Yes, not a bug we just didn't add it yet. We should add it. But let's get the feature mostly done first.

**Comment by greg-schroeder** [comment] 2024-04-15 03:02
Okay this is held right now, will check for updates weekly on group chat progress

**Comment by greg-schroeder** [comment] 2024-04-24 20:47
Held

**Comment by greg-schroeder** [comment] 2024-05-07 09:36
Held

**Comment by greg-schroeder** [comment] 2024-05-09 05:35
@marcaaron do you know if "Front End PR 2" is done yet?

**Comment by marcaaron** [comment] 2024-05-09 21:53
Oh sorry, yes, it's been done for quite a while 🥲

**Comment by marcaaron** [comment] 2024-05-09 21:54
We actually have an open issue for this already and someone is working on it. Gonna close this one out.

**Closed by marcaaron** 2024-05-09 21:54 UTC
Labels: Weekly, NewFeature
