### ISSUE TITLE
[$1000] Web - Flagged Attachments Can Still Be Downloaded Despite Removal triggering page crash

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22900] opened 2023-07-14 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From User A, Initiate a chat with User B
2. From User A, send a image as attachments
3. From User A, select the image (imp step)
4. From user B, flag the attachment  as “harrasment” which removes the attachment
5. Verify attachment visible and download possible although it has been removed by User B
6. Refresh the page
7. Observe page crash

## Expected Result:
1. Attachment removed completely and download not possible
2. The chat interface opens after refresh

## Actual Result:
Page crashes on refresh. Download was possible despite "removal' notification

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ee2a7c8d-0472-482a-b10a-5c27e75d446f

https://github.com/Expensify/App/assets/93399543/8741cea3-162f-4701-a8af-015494780d9e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689290039120479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e95547668103d5e</li>
        <li>Upwork Job ID: 1681350016062918656</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by crazy-coding** [comment] 2023-07-14 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When the application navigates to the route specifically designed for handling attachment reports.
FYI. ReportAttachments.js component.
This route opens a modal that contains the attachment source, which has already been removed.

https://github.com/Expensify/App/blob/78f8a702512bf8ae91d2fe29e834e8e0c05ae786/src/pages/home/report/ReportAttachments.js#L22:L40


### What changes do you think we should make in order to solve the problem?

At this stage, we have the option to navigate to the report page or close the modal after performing a pre-check to ensure that the attachment URL is available.

### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jfquevedol2198** [comment] 2023-07-14 17:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Flagged Attachments Can Still Be Downloaded Despite Removal triggering page crash

### What is the root cause of that problem?
Clicking on `Download` button doesn't check availability of attachment.
When user try to visit the page of attachment to be already flagged, `AttachmentCarousel` throws error `Attachment not found`, so the page crashes.

https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/components/AttachmentCarousel/index.js#L192-L195

### What changes do you think we should make in order to solve the problem?
1. `Download` click needs check availability of Attachment
     If its not available, need to show Error message like `Attachment is removed or flagged, not available to download`
2. When user try to visit the page of attachment to be already flagged, 
    solution A: displays Error message like `Attachment is removed or flagged, not available to download`
    solution B: redirect to report page
    solution C: keep current behaviour

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bfitzexpensify** [comment] 2023-07-18 17:03
Reproduced.

**Comment by crazy-coding** [comment] 2023-07-18 19:07
Please review my [proposal](https://github.com/Expensify/App/issues/22900#issuecomment-1636169950)

**Comment by bfitzexpensify** [comment] 2023-07-24 12:28
@abdulrahuman5196 bump to review the proposals that have been shared - thanks!

**Comment by crazy-coding** [comment] 2023-07-26 17:10
@abdulrahuman5196 Please consider reviewing my [proposal](https://github.com/Expensify/App/issues/22900#issuecomment-1636169950)

**Comment by abdulrahuman5196** [comment] 2023-07-26 19:35
Sorry for the delay will close it out in the morning

**Comment by bfitzexpensify** [comment] 2023-07-31 10:21
Reminder to review when you get a moment @abdulrahuman5196 - thank you

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:55
Reviewing today

**Comment by abdulrahuman5196** [comment] 2023-08-01 14:37
@bfitzexpensify I have question on UX, what is experience when we are seeing a attachment in the view and the attachment gets deleted due to changes on some other place.
1) Should we close the attachment modal?
2) Auto change and show the next image?
3) Show PageNotFound kind of view?

**Comment by jfquevedol2198** [comment] 2023-08-01 15:40
## Updated Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Flagged Attachments Can Still Be Downloaded Despite Removal triggering page crash

### What is the root cause of that problem?
When the AttachmentModal is open and the attachment is flagged, nothing is happening on AttachmentModal.
So Download is still available, and Flagged Attachment preview is still available.
Something should be happened.

### What changes do you think we should make in order to solve the problem?
When Attachment is flagged, If Attachment Modal is open, AttachmentModal should be updated.
If the flagged attachment is open on AttachmentModal
    a. If next attachment preview is available, it should be switched to next attachment preview.
    b. If no next attachment preview, dismiss AttachmentModal

### What alternative solutions did you explore? (Optional)
N/A

**Comment by crazy-coding** [comment] 2023-08-01 15:48
@abdulrahuman5196 I think this issue is not happening now. There's a little gap after flagging. But AttachmentModal is closing successfully after flagging the attachment message.

**Comment by bfitzexpensify** [comment] 2023-08-01 16:02
@crazy-coding is correct, I was just able to confirm that the image modal is closing gracefully just after the image is flagged as offensive. I think we can go ahead and close this out.

**Closed by bfitzexpensify** 2023-08-01 16:02 UTC
Labels: External, Daily, Help Wanted, Bug
