### ISSUE TITLE
[HOLD for payment 2024-09-17][$250] Web - Concierge - Concierge in unavailable workspace when create new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44480] opened 2024-06-26 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a444@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with a new Gmail account
3. Complete the onboarding modal requests
4. Take a look at the Concierge chat header

## Expected Result:
There should be only Concierge label on Concierge chat header

## Actual Result:
"Concierge in unavailable workspace" can be seen on the Concierge chat header after creating a new account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![14!image](https://github.com/Expensify/App/assets/78819774/0b7c0391-f452-4060-b386-7b2b96066e18)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013152861e0170f045</li>
        <li>Upwork Job ID: 1806787876528252448</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103818556</li>
<li>wildan-m | Contributor | 103818557</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by lanitochka17** [comment] 2024-06-26 16:02
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mvtglobally** [comment] 2024-07-11 03:51
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-07-11 16:39
I also was unable to reproduce this. Closing.

**Comment by IuliiaHerets** [comment] 2024-08-13 06:16
Issue is still reproducible on the latest build v9.0.19-9, unavailable workspace appears for a moment before the Onboarding modal opens
![1308_1](https://github.com/user-attachments/assets/5749939e-41b4-460f-a168-7946639dcf5f)

https://github.com/user-attachments/assets/122db380-4bb0-41d9-b0a4-a8ff4ca1b920

**Comment by sakluger** [comment] 2024-08-14 18:38
@jainilparikh are you still interested in working on this one?

**Comment by sakluger** [comment] 2024-08-20 16:59
@allgandalf any updates?

**Comment by wildan-m** [comment] 2024-08-22 17:58
@allgandalf if someone can better explain the root cause but ended up with similar other proposal solution, which proposal will be selected?

**Comment by b4s36t4** [comment] 2024-08-22 20:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Concierge - Concierge in unavailable workspace when create new account
### What is the root cause of that problem?

The real problem relies in the `ReportScreen` component where we're rendering `HeaderView` component. 

Inside `ReportScreen` component we're rendering `HeaderView` with a prop `report` which is a object derives from object read from `onyx`

https://github.com/Expensify/App/blob/15805221bdd48e88bc39991895cbb26172bb106e/src/pages/home/ReportScreen.tsx#L327

https://github.com/Expensify/App/blob/15805221bdd48e88bc39991895cbb26172bb106e/src/pages/home/ReportScreen.tsx#L169-L255

The case which the issue is reproducible  is where this object contains all the keys but all the values inside are `undefined` in which it passes the first `if` condition inside `getReportName` function.

Now after the `if` we have another condition where we're checking the `polices` from onyx and verifying that the report isn't from one of the policies.

When we create a new account, `allReports` will be empty and `report.policyName` is also `undefined` which qualifies this condition and here we're returning the `Unavailable Workspace` string.

https://github.com/Expensify/App/blob/ed910fa1cae6597ea317f24bd7d4d60e4f6f4d5e/src/libs/ReportUtils.ts#L745

> This happens with-in micro-seconds of time diff on writing the data to onyx and component re-render.


To summarize the first `if` condition is failing because we're not sending an empty object from `ReportScreen` whereas the 2nd condition is getting succeed because of the time-diff of getting updated data i.e `report` and `allReports` which is giving the `unavailableTranslation`.

### What changes do you think we should make in order to solve the problem?


We can simply return `noPolicyFound` from 2nd `if` condition which will return empty string in this cause because `returnEmptyIfNotFound` is true.

> We need to make sure the `returnEmptyIfNotFound` is respected everywhere in the codebase to make sure we don't cause any regressions.

### What alternative solutions did you explore? (Optional)

Currently we have `policyId` condition `_FAKE_` value in-case of empty policy related to report. We can also do same for `policyName` and return `_FAKE_` value from `ReportScreen` component and have a condition inside `getReportName` function to handle it carefully.

> We should only send `_FAKE_` value if the `policyName` doesn't exist from `report` which doesn't exist for `conceirge` and `expensify`'s report.

**Comment by b4s36t4** [comment] 2024-08-22 20:18
Gentle bump @allgandalf for proposal review :)

**Comment by wildan-m** [comment] 2024-08-23 04:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web Concierge is unavailable for a brief moment when creating a new account.

### What is the root cause of that problem?

On the initial login, there is a moment that report and policies are being loaded and we call `getPolicyName`

<img width="998" alt="SCR-20240823-jsoq-2" src="https://github.com/user-attachments/assets/cd2ff3fb-3c64-4dc4-a673-e7db2fea7c38">

When the policies empty and loading then it will enter this check:

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/ReportUtils.ts#L745-L747

This can happen for new account or existing one.


### What changes do you think we should make in order to solve the problem?

Add `!report.reportID || isEmptyObject(allPolicies)` to this check:

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/ReportUtils.ts#L741

We can also refactor `(!allPolicies || Object.keys(allPolicies).length === 0)` to `isEmptyObject(allPolicies)` here:

https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/libs/ReportUtils.ts#L745

### What alternative solutions did you explore? (Optional)
Alternative 1
define isConcierge chat as one of kind of chat that not need to display `renderAdditionalText`
Chang [this code](https://github.com/Expensify/App/blob/156f0a2bd0e94558ad621caa701bd749dd124bfe/src/pages/home/HeaderView.tsx#L114-L124) to:
```tsx
    const renderAdditionalText = () => {
        if (isConciergeChat || shouldShowSubtitle() || isPersonalExpenseChat || !policyName || !isEmptyObject(parentNavigationSubtitleData) || isSelfDM) {            
            return null;
        }
```

Alternative 2
I am unsure when the unavailable workspace is supposed to appear and cannot find sufficient information, but I suggest removing that option entirely and displaying an empty string for all cases where it is not found.

Alternative 3
Similar to prev proposals but with optimization to condition

in getPolicyName
```tsx
    const noPolicyFound = returnEmptyIfNotFound ? '' : unavailableTranslation;
    if (isEmptyObject(report)||(isEmptyObject(allPolicies) && !report?.policyName) ) {
        return noPolicyFound;
    }

    const finalPolicy = policy ?? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`];
    const parentReport = getRootParentReport(report);

```

**Comment by mvtglobally** [comment] 2024-08-23 12:06
Issue not reproducible during KI retests. (Second week)

**Comment by sakluger** [comment] 2024-08-23 21:51
Hey @allgandalf could you please review the outstanding proposals?

I'm also going to add another BZ member to monitor while i'm OOO (Back 8/30).

**Comment by lschurr** [comment] 2024-08-27 20:42
Any update here @allgandalf?

**Comment by lschurr** [comment] 2024-08-28 15:32
Bumped in Slack as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1724859115299129

**Comment by lschurr** [comment] 2024-09-04 15:48
@cristipaval is out on leave - going to put this in Slack to get another Engineer added

**Comment by sakluger** [comment] 2024-09-04 18:10
Let's just auto-assign a new engineer.

**Comment by sakluger** [comment] 2024-09-04 18:11
@allgandalf do you mind posting "🎀👀🎀 C+ reviewed" again to get a new engineer auto-assigned? Thanks!

**Comment by lschurr** [comment] 2024-09-04 18:30
Gonna remove myself since you're back Sash :)

**Comment by mjasikowski** [comment] 2024-09-04 18:44
Thank you for the summary @allgandalf. The proposal by @wildan-m looks good, we can go ahead with this one.

**Comment by wildan-m** [comment] 2024-09-05 06:58
@allgandalf The PR is ready https://github.com/Expensify/App/pull/48621

**Comment by mvtglobally** [comment] 2024-09-09 04:10
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2024-09-13 16:37
Issue not reproducible during KI retests. (Third week)

**Comment by sakluger** [comment] 2024-09-20 15:07
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@allgandalf] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@allgandalf] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@allgandalf] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@allgandalf] Determine if we should create a regression test for this bug.
- [ ] [@allgandalf] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@sakluger] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sakluger** [comment] 2024-09-20 15:08
Summarizing payment on this issue:

Contributor: @wildan-m $250, paid via Upwork
Contributor+: @allgandalf $250, paid via Upwork

**Comment by sakluger** [comment] 2024-09-26 23:11
Thanks!

**Closed by sakluger** 2024-09-26 23:11 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
