### ISSUE TITLE
[$250]  Compose box - Public Image link doesn't display image preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52130] opened 2024-11-06 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5187439
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New expensify app in iOS
2. Send: ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
) to a chat along with some text.

## Expected Result:
Image previews should be available in compose box and in chat history

## Actual Result:
Image previews are not available

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e54d0f28-c1d8-434c-8c90-cc4d9980da8b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854955488136976314</li>
        <li>Upwork Job ID: 1854955488136976314</li>
        <li>Last Price Increase: 2024-11-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by ikevin127** [comment] 2024-11-10 01:07
This is the actual image URL used in the testing video:

```
https://images.unsplash.com/photo-1709983723739-d72ea88434dd?g=80&w=2940&auto=format&fit=crop&ixliberb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
```

I looked into this and unless there's a regression test which failed, based on which this issue was created - I think this is expected behaviour because we don't have the preview functionality available on native platforms, only on web based platforms (Web, Desktop and Android / iOS mWeb).

In **react-native-live-markdown** -> [`MarkdownTextInput.web.tsx`](https://github.com/Expensify/react-native-live-markdown/blob/4a62d9b1c58c1800c8c79fc6a3c66a3e724064b5/src/MarkdownTextInput.web.tsx) calls `forceRefreshAllImages` which makes the preview available on **web only** when using the proper syntax, which is not called on native (`MarkdownTextInput.tsx`) because `forceRefreshAllImages` is web based.

Example of the feature on web based platforms:
```md
Test image markdown syntax

![test](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?g=80&w=2940&auto=format&fit=crop&ixliberb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
```

<details>
<summary>Example on Android: mWeb</summary>

https://private-user-images.githubusercontent.com/39538890/367725502-742e3511-abd8-4506-b129-560584bc93e4.mov

</details>

On native platforms (iOS / Android) we only see the picture after posting it using image markdown syntax, for example:

```
Test test

![test](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?g=80&w=2940&auto=format&fit=crop&ixliberb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
```

When posted, this will display Test test, under which we will see the actual picture:

https://github.com/user-attachments/assets/2832a1cd-bfca-43f4-b3f8-556debd4825a

##

I was able to gether this information from the following PRs:
- https://github.com/Expensify/react-native-live-markdown/pull/500
- https://github.com/Expensify/App/pull/49250

@bfitzexpensify Unless this issue is about implementing the previews feature on native platforms, I think it can be closed as not a bug.

**Comment by bfitzexpensify** [comment] 2024-11-14 14:04
Here are the test details that caught this:

Steps

1. Navigate to any chat.
2. Compose a new message with both a public image URL and accompanying text.
3. Example: An inline image and some text! off
4. Verify that the image thumbnail displays below the message in the composer.
5. Send the message.
6. Verify that the message correctly displays the image thumbnail alongside the text.
7. Click on the thumbnail.
8. Verify that the image preview modal correctly displays

**Comment by rojiphil** [comment] 2024-11-14 18:34
> Here are the test details that caught this:

Thanks @bfitzexpensify. The regression test comes from [this PR](https://github.com/Expensify/App/issues/37246#issuecomment-2427559620). But, based on the comment [here](https://github.com/Expensify/App/issues/52130#issuecomment-2470299825) it does not look like a regression here. I think we can close this out unless there is something more to the story.

**Comment by bfitzexpensify** [comment] 2024-11-14 19:12
Cool, agreed.

**Closed by bfitzexpensify** 2024-11-14 19:12 UTC
Labels: External, Daily, Help Wanted, Bug
