### ISSUE TITLE
[Ready for payment][$250] Queue command length log is not displaying correctly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40820] opened 2024-04-23 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40619
**Version Number:** 1.4.64-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Open Desktop App
2. Go to Network > Turn on slow 3g
3. Open any report and make sure there is no persistent request.
4. Send any message
5. Send 2nd and 3rd messages

## Expected Result:
Verify that there is a log [info] [SequentialQueue] 'AddComment' command queued. Queue length is 1 - "" is shown for the 1st message and for 2nd and 3rd messages it should show 
 log [info] [SequentialQueue] 'AddComment' command queued. Queue length is 2 - ""
a log [info] [SequentialQueue] 'AddComment' command queued. Queue length is 3 - ""

## Actual Result:
A `log [info] [SequentialQueue] 'AddComment' command queued. Queue length is 1 -`  is shown when sending 2nd and 3rd messages also

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/db983e4e-bf8f-4bef-9e71-19ae508cb628

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176305de79a2b01c6</li>
        <li>Upwork Job ID: 1783010633846906880</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by nkdengineer** [comment] 2024-04-24 07:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending multiple. 'AddComment' command. Queue length is 1 -  is shown when sending 2nd and 3rd messages also.

### What is the root cause of that problem?
After the first log for `[info] [SequentialQueue] 'AddComment' command queued. Queue length is 1`. The request was already successful, so the request is [removed from the queue](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Network/SequentialQueue.ts#L77).

When we send another 'AddComment' command after that, the queue length now is actually still 1, which misleads that the queue length didn't increase after the first `AddComment`, while the fact is that it was queued just fine, but was removed from the queue after the request is successful.

So the problem here is that when we remove the command from the queue, we're not logging anything to indicate that the request is removed and not tell the new length of the queue.

### What changes do you think we should make in order to solve the problem?

When we remove the command from the queue, add logs to indicate that the request is removed and tell the new length of the queue.

So in [here](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/actions/PersistedRequests.ts#L44) we can update to
```
Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, requests).then(() => {
        Log.info(`[SequentialQueue] '${requestToRemove.command}' removed from the queue. Queue length is ${getLength()}`);
});
```

We can even be more specific by passing into `PersistedRequests.remove` the reason for removal (request succeeded/failed/cancelled), the reason is clear from its usage [here](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Network/SequentialQueue.ts#L77), [here](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Network/SequentialQueue.ts#L85) and [here](https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/Network/SequentialQueue.ts#L93), then log that reason too when we log the "request removed from queue" message.

### What alternative solutions did you explore? (Optional)
We can add logs into any other places that changes the `persistedRequests` queue in anyway, so it's extra clear when debugging.

**Comment by kadiealexander** [comment] 2024-04-29 06:01
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714370416480019).

**Comment by kbecciv** [comment] 2024-04-29 13:12
Issue is still reproducible, build 1.4.67.0

https://github.com/Expensify/App/assets/93399543/d6621f1e-6099-4926-9662-50f9cebeb1eb

**Comment by Julesssss** [comment] 2024-04-30 07:29
Yeah, I like the additional log

**Comment by kadiealexander** [comment] 2024-05-16 04:59
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@ishpaul777] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@ishpaul777] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@ishpaul777] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@ishpaul777] Determine if we should create a regression test for this bug.
- [ ] [@ishpaul777] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-05-16 05:01
Payouts due:

- [ ] Contributor: $250 @nkdengineer
- [ ] Contributor+: $250 @ishpaul777

Upwork job is [here](https://www.upwork.com/jobs/~0176305de79a2b01c6).

**Closed** 2024-05-20 05:40 UTC
Labels: Reviewing, External, Daily, Bug
