### ISSUE TITLE
[HOLD for payment 2024-01-18] [$500] Web - IOU - Clicking on blank space next to 'From' link navigates user to main report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33907] opened 2024-01-03 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create an IOU report
2. Click on the IOU preview component
3. Click on a blank space next to from link of the IOU report header

## Expected Result:
RHP should be opened and 'Details' page should be be displayed as it does for task report

## Actual Result:
User is navigated to main report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/684562b5-a45f-4328-95e9-38bb08efe9a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d27b574e0b4def7f</li>
        <li>Upwork Job ID: 1742652043004137472</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28089418</li>
</ul></li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-04 00:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - IOU - Clicking on blank space next to 'From' link navigates user to main report

### What is the root cause of that problem?

`ParentNavigationSubtitle` follow parent (`AvatarWithDisplayName`) layout.

### What changes do you think we should make in order to solve the problem?

`ParentNavigationSubtitle` style add `alignSelf:'flex-start'`, so it out will be out of context.

https://github.com/Expensify/App/blob/3b85e1f528e33b1e10ff05166a5490931e35e5c6/src/components/ParentNavigationSubtitle.tsx#L35

```js
style={[pressableStyles,{alignSelf:'flex-start'}]}
```


### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2024-01-04 09:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Currently, users are unable to interact with the money request header to view its details. Instead of opening the details, clicking on the header redirects users back to the previous page.

### What is the root cause of that problem?

Upon examination, it is observed that the discrepancy arises due to the utilization of different components for the report page header and the money request details page. The `ReportScreen.js` employs the `<HeaderView>` component, which allows users to click and open the details in a side window. This functionality is implemented through the `PressableWithoutFeedback` wrapper.

However, the money request page uses the `<MoneyRequestHeader>` component, which lacks this click-to-open feature. This component is currently not enclosed within a `PressableWithoutFeedback` or similar wrapper that would facilitate the opening of detail windows upon interaction.

Reference to the current implementation can be found here:
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/home/ReportScreen.js#L214-L233

The screenshot attached below highlights the difference in implementation. The `<HeaderView>` is nested within a `PressableWithoutFeedback`, enabling the opening of detail pages, which is not the case with `<MoneyRequestHeader>`.

![image](https://github.com/Expensify/App/assets/12425932/5b705edf-d005-441d-91cc-df403ded9fb7)

https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/home/HeaderView.js#L254-L255

### What changes do you think we should make in order to solve the problem?

To resolve this issue, the `<MoneyRequestHeader>` should be wrapped within a `PressableWithoutFeedback` component, mirroring the implementation found in `<HeaderView>`. This modification will enable the money request header to function interactively, allowing users to access details with a click, enhancing the user experience.

**Comment by garrettmknight** [comment] 2024-01-05 18:42
@thesahindia can you give these a look when you get a chance?

**Comment by garrettmknight** [comment] 2024-01-08 20:07
@thesahindia quick bump to review these. Thanks!

**Comment by garrettmknight** [comment] 2024-01-18 20:38
Summary of payments:
- Contributor: @dukenv0307 $500 paid via Upwork
- Reviewer: @thesahindia $500

**Comment by garrettmknight** [comment] 2024-01-18 20:39
Dropping to weekly for @thesahindia to suggest a regression test and request payment.

**Comment by luacmartins** [comment] 2024-02-05 22:22
Test steps look good to me

**Comment by garrettmknight** [comment] 2024-02-06 10:54
QA updated - on you to request payment @thesahindia

**Comment by luacmartins** [comment] 2024-02-20 00:11
Closing as per previous comment!

**Closed by luacmartins** 2024-02-20 00:11 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-10 18:13
$500 approved for @thesahindia
