### ISSUE TITLE
[$500] Room - Can invite valid phone account multiple times into the room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30190] opened 2023-10-23 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698051749271339

## Action Performed:
1. Create a WS
2. Create a room with workspace
3. Click room header => Members => Invite
4. Input an invalid phone (eg: +3233232432) then select and click invite
5. Repeat step 4

## Expected Result:
The app should show an error when inviting an invalid phone number

## Actual Result:
The system does not show errors and may invite invalid phone numbers multiple times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/743a5366-d528-4b33-9a91-dfb567e3e9f8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/c68c9eb5-3753-4b61-873b-c12e8764a49d

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/2ac1eda6-c936-4a4d-ab42-8ca6dfe7c336

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/327bca18-2ee5-4799-976c-bf11b0185f5c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/99be7c54-ad4d-4166-8d08-99c5fe0d8563

https://github.com/Expensify/App/assets/93399543/b9b73670-07b6-4acf-ac07-e3bf98664f00

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/09927803-c318-4b7c-bec6-e0114b43ad87

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da7f12cf9ed3d23f</li>
        <li>Upwork Job ID: 1716509714359189504</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27539247</li>
<li>namhihi237 | Reporter | 27539248</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-23 17:55
I think number provided number(`+3233232432`) is valid number

**Comment by FitseTLT** [comment] 2023-10-23 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room allows multiple invitation for phone number which is already a member
### What is the root cause of that problem?
The problem lies in this line of code
https://github.com/Expensify/App/blob/844b3b96b5bcd80c5c7bd376648a921939e25d10/src/libs/OptionsListUtils.js#L1237-L1238
Because we are comparing the phone number input of the user with the return value of `addSMSDomainIfPhoneNumber` function which concatinates '@expensify.sms' so it will never be equal hence that's why it allows an existing phone number to be in the list
### What changes do you think we should make in order to solve the problem?

Change 
https://github.com/Expensify/App/blob/844b3b96b5bcd80c5c7bd376648a921939e25d10/src/libs/OptionsListUtils.js#L1237-L1238
to 
`
        !_.find(optionsToExclude, (optionToExclude) => optionToExclude.login === searchValue.toLowerCase()) &&

`
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-10-26 09:01
Updated [comment](https://github.com/Expensify/App/issues/30190#issuecomment-1775773819) And I think this bug is worthy of fixing.

**Comment by DylanDylann** [comment] 2023-10-26 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Room - Can invite invalid phone account multiple times into the room

### What is the root cause of that problem?
I found out there are 2 related bug that need to be fixed:

**1. Issue 1**: (The bug that is mentioned in this issue https://github.com/Expensify/App/issues/30190)
- Actual: If inviting phone number A (for example +3233232432)  encounters an error from BE side, then we search A again, it still can be found in the result list, so A can be added multiple times.
- RCA: if inviting A encounters an error, it is not added to ```excludeLogins```, so when we search A again, it still appears in the result.

**2. Issue 2**:
- If the member list already contains A, then we type A in the search input, it will display as ```No results found``` rather than ```A@expensify.sms is already a member of Workspace```.
- RCA: 
https://github.com/Expensify/App/blob/8c76d2aff5ebbaa11a951e4cdf85d1cadb6d6548/src/pages/workspace/WorkspaceInvitePage.js#L235-L237
Based on the above logic, we are displaying ```messages.userIsAlreadyMember``` only when ```usersToInvite``` is empty and ```excludeUsers``` includes ```searchValue```. In case phone number A already existed, in ```excludeUsers``` it is ```A@expensify.sms```, ```searchValue``` is just A, so the conditions ```usersToInvite.length === 0 && excludedUsers.includes(searchValue)``` will be false, leads to the bug.
### What changes do you think we should make in order to solve the problem?
**1. Issue 1**: 
- This is expected, so i think we do not need to fix it
https://github.com/Expensify/App/blob/9e50be49a4831bb5d7699e5032cbc3487f956f16/src/libs/PolicyUtils.js#L200
**2. Issue 2**:
- Update
https://github.com/Expensify/App/blob/8c76d2aff5ebbaa11a951e4cdf85d1cadb6d6548/src/pages/workspace/WorkspaceInvitePage.js#L235
to
```
if (usersToInvite.length === 0 && (excludedUsers.includes(searchValue) || excludedUsers.includes(OptionsListUtils.addSMSDomainIfPhoneNumber(searchValue).toLowerCase()))) 
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by greg-schroeder** [comment] 2023-10-27 16:51
awaiting proposal review from @rushatgabhane

**Comment by greg-schroeder** [comment] 2023-11-01 11:05
Bump @rushatgabhane

**Comment by Beamanator** [comment] 2023-11-06 12:28
Updated issue title to reflect that the bug is about **valid** phone numbers

**Comment by Beamanator** [comment] 2023-11-06 13:48
yes... approved today, Melvin!

**Comment by DylanDylann** [comment] 2023-11-08 03:42
@rushatgabhane PR https://github.com/Expensify/App/pull/31010 is ready for review

**Comment by greg-schroeder** [comment] 2023-11-09 11:30
PR is being reviewed

**Comment by greg-schroeder** [comment] 2023-11-14 16:47
Reviews continue on linked PR

**Comment by greg-schroeder** [comment] 2023-11-26 20:10
Bump @rushatgabhane on PR review when you get a chance :)

**Comment by greg-schroeder** [comment] 2023-12-19 02:22
Merged. Awaiting deploy to staging -> prod

**Comment by rushatgabhane** [comment] 2024-01-02 05:45
FYI, the PR was reverted https://github.com/Expensify/App/pull/31010#issuecomment-1869463115 because it caused a performance regression on large accounts.

**Comment by rushatgabhane** [comment] 2024-01-02 05:46
@DylanDylann we have to raise a new PR

**Comment by DylanDylann** [comment] 2024-01-02 05:54
@rushatgabhane sure. I will raise a new PR

**Comment by greg-schroeder** [comment] 2024-01-03 18:40
@rushatgabhane so given this was reverted, the 2024-01-03 payment date is incorrect, right? I think that's from the CP being deployed.

@DylanDylann can you link the new PR?

**Comment by DylanDylann** [comment] 2024-01-03 19:05
@greg-schroeder I am working on it, I need to double-check because the latest main has a lot of changes

**Comment by greg-schroeder** [comment] 2024-01-03 19:12
Okay got it, thanks!

**Comment by DylanDylann** [comment] 2024-01-04 08:52
The new [PR](https://github.com/Expensify/App/pull/33928) is ready to review

**Comment by greg-schroeder** [comment] 2024-01-26 18:39
New PR was merged, awaiting deploy to staging -> prod

**Comment by Beamanator** [comment] 2024-01-31 08:56
Seems like the PR for this was reverted again 😬 https://github.com/Expensify/App/pull/35335 so no payment due yet

**Comment by greg-schroeder** [comment] 2024-02-06 01:29
RIP

**Comment by greg-schroeder** [comment] 2024-02-06 01:31
Are we even going to move forward here at all? It seems this might not actually go forward with another PR based on what @mountiny is saying in the linked PRs

**Comment by DylanDylann** [comment] 2024-02-06 01:35
@rushatgabhane @mountiny I cannot reproduce this issue in staging anymore. Anyone can help confirm

**Comment by Beamanator** [comment] 2024-02-13 14:42
Added `retest-weekly` to get more eyes from applause, would be great if this got fixed automagically somehow 😅 😳

**Comment by greg-schroeder** [comment] 2024-02-16 05:18
I also couldn't repro, I think I'm going to close this given two failures to reproduce and also https://github.com/Expensify/App/issues/30190#issuecomment-1928611881. Reopen if you disagree

**Closed by greg-schroeder** 2024-02-16 05:18 UTC
Labels: External, Weekly, Bug, retest-weekly
