### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] mWeb - Save Button is being overlapped by the keyboard on Welcome Message Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30175] opened 2023-10-23 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697888584763929

## Action Performed:
1. Open the app.
2. Go to #announce/#admins chat
3. Click on header > Details > Settings > Welcome message
4. Click on the welcome message input.
5. Observe that the Save button is not visible.

## Expected Result:
Save button should be shown at the top of keyboard just like in pages like Legal Name Page, Private Note Edit Page etc

## Actual Result:
Save button is not visible when keyboard is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6facf132-d195-414a-af4d-0fcde16a9da7

https://github.com/Expensify/App/assets/93399543/6eeceb54-bb50-4294-96c3-f0aec38e25f7

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016aded3956387f9c7</li>
        <li>Upwork Job ID: 1716446113884372992</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27341830</li>
<li>aman-atg | Contributor | 27341831</li>
<li>aman-atg | Reporter | 27341833</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-23 13:28
Proposal by: @aman-atg
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1697888584763929

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Save button is being overlapped by the keyboard on Welcome Message page

### What is the root cause of that problem?
The root cause of this problem is that we haven't used the `shouldEnableMaxHeight` and `includeSafeAreaPaddingBottom={false}` props for the ScreenWrapper on this page, which is resulting in the keyboard overlapping the Save button

### What changes do you think we should make in order to solve the problem?

We should use both of these props here to prevent the keyboard from overlapping the Save button like we have on other pages
https://github.com/Expensify/App/blob/0d11e0b3b07488ff11ad69a78800a0995733f07a/src/pages/ReportWelcomeMessagePage.js#L78

**Comment by s77rt** [comment] 2023-10-23 22:35
@aman-atg Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍. Please comment and tag me so you can be assigned.

**Comment by s77rt** [comment] 2023-10-23 22:42
@aman-atg Thanks! Let's get this fixed 🚀 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/30175#issuecomment-1775197684)

**Comment by Li357** [comment] 2023-10-24 04:29
Looks good!

**Comment by JmillsExpensify** [comment] 2023-10-24 22:56
PR review in progress

**Comment by s77rt** [comment] 2023-11-03 10:19
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18662
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18662#discussion_r1381422269
- A discussion in #expensify-open-source has been started: https://expensify.slack.com/archives/C01GTK53T8Q/p1699006095512429
- Determine if we should create a regression test for this bug: I feel like a regression test would be useless here because the bug can resurface in any place in the App. Adding a checklist item to the PR review process is more effective in preventing such bugs

**Comment by Li357** [comment] 2023-11-14 17:16
Are we good to close this?

**Comment by s77rt** [comment] 2023-11-14 17:47
This is awaiting payment.

**Comment by JmillsExpensify** [comment] 2023-11-24 18:26
To clarify, wasn't this issue associated with a regression?

**Comment by JmillsExpensify** [comment] 2023-11-24 18:26
It appears so based on this issue: https://github.com/Expensify/App/issues/30707

**Comment by s77rt** [comment] 2023-11-24 18:47
@JmillsExpensify No. It seems that the a new issue was found during the PR testing. But it's not related.

**Comment by JmillsExpensify** [comment] 2023-11-24 18:56
Thanks for confirming. Given that the delay in the PR was on our side, payment summary as follows:

 - Issue reporter: @aman-atg $50
 - Contributor: @aman-atg $750 (incl. urgency bonus)
 - Contributor+: @s77rt $750 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment] 2023-11-24 19:08
Everyone paid out based on the above payment summary and no regression test. Closing.

**Closed by JmillsExpensify** 2023-11-24 19:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
