### ISSUE TITLE
[HOLD App#11910] Chat - Two admis and two announce rooms have been created after click Create a Free Policy in OldDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12061] opened 2022-10-21 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12013

## Action Performed:
1. Log in staging.expensify.com
2. Create a new account and validate it
3. After set a Password - Create Control Policy
4. Go to Settings - Policy
5. Select New Policy
6. Select Free Policy
7. Flow will direct you to NewDot
8. Check admin policy

## Expected Result:
One admis and One announce rooms have been created after Create a Free Policy

## Actual Result:
Two admis and two announce rooms have been created after click Create a Free Policy in OldDot
Also one admin and one announce is showed as Unavailable, but after refresh it shows as normal.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any new Control Policy

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (13)](https://user-images.githubusercontent.com/93399543/197235003-03e36ad3-2e43-4c14-8df5-2677fa95aefa.png)

https://user-images.githubusercontent.com/93399543/197235033-c776b21b-29a8-44d5-905f-2071afce4421.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-10-21 15:57
@mountiny sorry man, can you check if your PR broke this, QA are saying this was introduced with https://github.com/Expensify/App/pull/12038

**Comment by mountiny** [comment] 2022-10-21 16:01
Asked @alex-mechler as this would have to be related to the initial logic change rather than the follow up fix of syntax

**Comment by francoisl** [comment] 2022-10-21 17:15
Thanks for reporting @kbecciv. We've been investigating and figured this is not a blocker:

> Two admins and two announce rooms have been created after click Create a Free Policy in OldDot

This is now normal, and is related to https://github.com/Expensify/App/pull/12013. The behavior is currently different on production because that PR has not been deployed to production yet.

> Also one admin and one announce is showed as Unavailable, but after refresh it shows as normal.

@alex-mechler was able to reproduce this on production, so it doesn't appear to be a regression. We believe it's a bug though, so we'll keep this issue open for further investigation.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/2229301/197252067-59027281-5d04-4d71-8409-a5771eb8f162.png">

**Comment by alex-mechler** [comment] 2022-10-21 17:20
I wonder if this is related to https://github.com/Expensify/App/issues/11910 (which has a pr up)

**Comment by francoisl** [comment] 2022-10-21 23:13
I'm going to be OOO next and won't have time to look into this one more today, going to put it back in the pool.

**Comment by mountiny** [comment] 2022-10-24 09:53
Assigning Autoassigner because bug zero initiative.

I think this was not a bug per se, but we should somehow differentiate between the rooms in LHN.

@alex-mechler Would you be able to provide a summary of the findings from the fireroom? I havent been able to follow the latest there.

**Comment by alex-mechler** [comment] 2022-10-24 15:59
> Would you be able to provide a summary of the findings from the fireroom? I havent been able to follow the latest there.

- Two admin rooms is not a bug here, as two policies were created. This is normal behavior now that https://github.com/Expensify/App/pull/12013 is live, as there is assigned guides in the room.
- Unknown Workspace was reproducible in production, so this was not a blocker. This _is_ unexpected though, and should be fixed. Its possible that https://github.com/Expensify/App/issues/11910 is related, but not confirmed.

**Comment by mountiny** [comment] 2022-10-24 17:18
> Unknown Workspace was reproducible in production, so this was not a blocker. This is unexpected though, and should be fixed. Its possible that https://github.com/Expensify/App/issues/11910 is related, but not confirmed.

**Comment by mountiny** [comment] 2022-10-24 17:20
Lets put this on hold for this https://github.com/Expensify/App/issues/11910 actually as it seems similiar.

**Comment by alex-mechler** [comment] 2022-10-24 17:59
If 11910 doesn't solve this, I'll update the OP here!

**Comment by maddylewis** [comment] 2022-11-02 13:53
waiting for update on this one - https://github.com/Expensify/App/issues/11910

**Comment by mvtglobally** [comment] 2022-11-03 03:18
Issue not reproducible during KI retests. (First week)

**Comment by alex-mechler** [comment] 2022-11-03 18:55
I was also not able to reproduce this. It looks like https://github.com/Expensify/App/issues/11910 solved the issue, so I'm going to close this one out

**Closed by alex-mechler** 2022-11-03 18:55 UTC
Labels: Engineering, Weekly
