### ISSUE TITLE
[Situ is out until May] [HOLD for payment 2024-03-22] [HOLD for payment 2024-03-20] Chat - Emoji is not showing in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38169] opened 2024-03-12 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send an emoji

## Expected Result:
The emoji shows up in chat

## Actual Result:
The emoji is not showing up in chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d2a21c3-df00-4d30-8fb8-6ab074b91032

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-12 19:43
@yuwenmemon  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-12 19:43
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by situchan** [comment] 2024-03-12 20:02
Looks like https://github.com/Expensify/App/pull/37559 caused regression. expensify-common version bump in that PR includes changes from https://github.com/Expensify/expensify-common/pull/649 which should be only merged with #37814.

**Comment by situchan** [comment] 2024-03-12 20:12
> Looks like that well pre-dates it - so if you're correct I think we should revert [Expensify/expensify-common#649](https://github.com/Expensify/expensify-common/pull/649) and then update expensify-common in this repo and CP that.

Agree

**Comment by kbecciv** [comment] 2024-03-12 20:14
@yuwenmemon 
Emojis not displayed in task and IOU description also, I believe this might stem from the same underlying issue, but I'll double-check.
Let me know if we need a separate issue. Thanks

https://github.com/Expensify/App/assets/93399543/db2c10d5-4088-4ad9-91c6-4e5dd899449e

**Comment by luacmartins** [comment] 2024-03-12 20:14
Agree with the revert of https://github.com/Expensify/expensify-common/pull/649

**Comment by luacmartins** [comment] 2024-03-12 22:47
This is fixed in staging

**Comment by luacmartins** [comment] 2024-03-12 22:47
Adding bug label to process payment

**Comment by yuwenmemon** [comment] 2024-03-12 22:56
This is resolved

**Comment by trjExpensify** [comment] 2024-03-22 13:38
Can someone confirm who we're paying and for what here? The PR linked [here](https://github.com/Expensify/App/issues/38169#issuecomment-1999333368) looks like a revert.

**Comment by situchan** [comment] 2024-03-22 14:20
Me as reviewed that PR (along with [finding the root cause](https://github.com/Expensify/App/issues/38169#issuecomment-1992473919)) and was not involved in offending PR.

**Comment by trjExpensify** [comment] 2024-04-02 14:03
Ah okay, cool. So payment summary as follows: 

- $500 to @situchan for the C+ review

Sent you an offer!

**Comment by trjExpensify** [comment] 2024-04-10 14:23
@situchan is out until May. I'm dropping this to weekly.

**Comment by situchan** [comment] 2024-05-20 07:37
I am back. Can you please send new offer? Old one was expired.

**Comment by trjExpensify** [comment] 2024-05-20 10:12
New offer sent.

**Comment by trjExpensify** [comment] 2024-05-20 22:54
Situ paid, closing!

**Closed by trjExpensify** 2024-05-20 22:54 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
