### ISSUE TITLE
DEV: Back button on assignee page returns to confirm task instead of task detail

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23686] opened 2023-07-26 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Assign task" section.
3. Enter a title and create the task.
4. Click on "Assignee" and then press the back button
## Expected Result: 
Pressing the back button on the assignee page should not take the user back to the confirm task page
## Actual Result: 
Pressing the back button on the assignee page returns the user to the confirm task page
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a06dc141-08d7-4092-b2e2-b06deb8e251f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690275742922289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-07-26 20:21
Dupe of https://github.com/Expensify/App/issues/21200

**Comment by kevinksullivan** [comment] 2023-07-28 18:54
Thanks @Pujan92

**Closed by kevinksullivan** 2023-07-28 18:54 UTC
Labels: Daily, Needs Reproduction, Bug
