### ISSUE TITLE
[HOLD #12259][Image] Android app & mWeb/Safari - Profile - The default avatar changes after removing the avatar image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12007] opened 2022-10-19 21:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Profile
4. Remove the avatar image

## Expected Result:
The default avatar shouldn't change

## Actual Result:
The default avatar changes

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Android app
- Mobile Web Safari (iOS)

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196804415-6c2c953d-6d1d-400b-b1cb-b1c53f5c5860.mp4

**Android app**

https://user-images.githubusercontent.com/93399543/201954824-1226538d-b987-45fc-8f70-e0105621405f.mp4

**mWeb/safari**

https://user-images.githubusercontent.com/93399543/201955586-7e1cf426-9285-4630-be5d-f552b9717031.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-10-28 00:52
@youssef-lr accidentally unassigned you while assigning me.  Also put on hold pending @Beamanator 's work on 
- https://github.com/Expensify/App/issues/10894

 If you have a solution in the works, drop in a comment to see if Beaman is 👍 to implement

**Comment by mallenexpensify** [comment] 2022-10-31 16:27
Oh hold

**Comment by mvtglobally** [comment] 2022-11-03 03:17
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2022-11-03 15:41
ooooh, not reproducible!!? I  like that .  Either way... it's on hold

**Comment by mallenexpensify** [comment] 2022-11-07 16:39
On hold

**Comment by mallenexpensify** [comment] 2022-11-07 22:58
Hold on #10894

**Comment by Beamanator** [comment] 2022-11-12 00:13
@trjExpensify are you going to take over for @mallenexpensify on this one?

**Comment by trjExpensify** [comment] 2022-11-15 01:29
~Nah. 😛~ Yep, sure thing!  

I can't reproduce this on staging web `v1.2.27-3` chrome, nor iOS mWeb. Can you? I'm inclined to close it at this point. 

The issue title has `mWeb/Chrome` but all platforms listed in the `Platform`. Can you confirm where this is happening, @kbecciv? I don't have an Android to check if that's the only place we're experiencing this issue.

**Comment by kbecciv** [comment] 2022-11-15 02:09
@trjExpensify Checking with team, will update you shortly

**Comment by kbecciv** [comment] 2022-11-15 15:15
@trjExpensify Issue is reproduced on Android app and mWeb/safari:

**Android app**

https://user-images.githubusercontent.com/93399543/201954824-1226538d-b987-45fc-8f70-e0105621405f.mp4

**mWeb/safari**


https://user-images.githubusercontent.com/93399543/201955586-7e1cf426-9285-4630-be5d-f552b9717031.mp4

**Comment by trjExpensify** [comment] 2022-11-15 15:38
@Beamanator to confirm, this is still an issue that should be on hold right?

**Comment by Beamanator** [comment] 2022-11-15 20:37
Huh good question, if I remember correctly, this "default avatar" business is going to be fixed by @roryabraham... Rory weren't you looking into implementing a default avatar SVG that's a file, not a URL? And I thinkkkk that was going to be in another issue?

**Comment by trjExpensify** [comment] 2022-11-18 19:29
Friendly bump on the question above, @roryabraham?

**Comment by trjExpensify** [comment] 2022-11-21 14:05
>if I remember correctly, this "default avatar" business is going to be fixed by @roryabraham... Rory weren't you looking into implementing a default avatar SVG that's a file, not a URL?

It's not this issue is it? https://github.com/Expensify/App/issues/12658

**Comment by trjExpensify** [comment] 2022-11-24 16:38
Okay, so mystery solved here then @Beamanator, it's https://github.com/Expensify/App/issues/9703 that @cristipaval is going to be working on?

**Comment by Beamanator** [comment] 2022-11-24 16:39
Yes indeedy! Thanks for updating - we can hold this on that one, hopefully it'll resolve itself 🙏

**Comment by trjExpensify** [comment] 2022-11-29 14:37
After revisiting this issue, it seems a bit superfluous to me:

- we have an image caching issue for mobile 
- we have an image caching issue for web/desktop
- we have an issue to bundle default avatars as SVG for a fall back when avatar images aren't loaded/cached

This issue has been created specific to the `profile` page on Android and mWeb/Safari, but I'm struggling to understand why during the implementation of the initiatives above this case won't be tested in the relevant PRs to ensure the solution works as intended.

**Comment by trjExpensify** [comment] 2022-12-08 21:47
#9703 has been encapsulated into https://github.com/Expensify/App/issues/12259, so the hold in the title needs an update. Regardless, I still question the purpose of keeping this issue open @Beamanator.

**Comment by Beamanator** [comment] 2022-12-13 12:48
Good call @trjExpensify - I think this should just be added as a testing step in @grgia 's PR to implement hard-coded default avatars, yeah?

**Comment by trjExpensify** [comment] 2022-12-13 14:27
Yeah, exactly.. we're basically jus QA'ing that the hard-coded default avatars are there after you remove a custom one, which should be accounted for in the testing steps of the PR that introduces them.

**Comment by Beamanator** [comment] 2022-12-13 15:30
So I think we can just close this one, do we need to add a comment to https://github.com/Expensify/App/issues/12259, explaining what we just discussed?

**Comment by trjExpensify** [comment] 2022-12-15 01:33
Yep, donezo!

**Closed by trjExpensify** 2022-12-15 01:33 UTC
Labels: Weekly, Planning
