### ISSUE TITLE
[$250] Android - Compose box shifts to the top when the keyboard opens

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12622] opened 2022-11-09 23:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to any chat
3. Tap the compose box

## Expected Result:
Proper padding should be there between keyboard and compose box

## Actual Result:
Compose box shits to the top of the page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android  

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200962131-0c7df393-2c32-49a0-8561-45e1f1ea2b70.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Julesssss 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667922302937219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~010a8681fe8590e35d
- Upwork Job ID: 1593531077904134144

**Comment by Julesssss** [comment] 2022-11-10 10:57
Part of the Keyboard issue grouping. @JmillsExpensify

**Comment by Julesssss** [comment] 2022-11-10 10:59
Hey @kavimuru, was the team not able to reproduce this issue?

**Comment by kavimuru** [comment] 2022-11-17 15:58
@Julesssss Our testers can reproduce this issue 

https://user-images.githubusercontent.com/43996225/202495330-192fee75-da2e-4f96-aab6-fd8be5475820.mp4

**Comment by JmillsExpensify** [comment] 2022-11-18 09:04
@Julesssss Thanks, assigning myself. Not sure why Github just notified me but that's a separate topic. I'll also it is to the tracking issue.

**Comment by JmillsExpensify** [comment] 2022-11-18 09:06
Creating an Upwork job now and getting this process kicked off. cc @tgolen for visibility

**Comment by Julesssss** [comment] 2022-11-18 11:23
Awaiting proposals

**Comment by tgolen** [comment] 2022-11-18 22:16
I'm not able to reproduce it. Is it a specific version of Android? I think that until we have clear reproduction steps, we should just close this.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1228807/202812202-d998c421-0859-4af0-806e-1fc2bb5526cf.png">

**Closed by tgolen** 2022-11-18 22:16 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by JmillsExpensify** [comment] 2022-11-18 22:25
This is why we need Android for BZ! Luckily Browerstack is coming.

**Comment by swiftpipe** [comment] 2022-11-19 02:08
I tried it on my phone (Samsung A51) it still works fine. I think this problem occurs depending on the device model

https://user-images.githubusercontent.com/37079377/202829276-e6857077-bad8-4d16-b75f-867c9f9868d8.mov

**Comment by Julesssss** [comment] 2022-11-22 14:24
I'm okay with closing this, but it is still occurring. 

The problem is that the steps aren't 100% reproducible. After opening the search page, and switching between chats I often see this bug. I reproduced it just a minute ago, but of course as soon as I started recording it didn't occur 🙄 

Let's close on the understanding that we don't yet have fully reproducible steps. Something is missing from our current steps and I'm not yet sure what that is.

**Comment by Julesssss** [comment] 2022-11-24 11:23
The keyboard issues are wider, and others will need to review that also.

**Comment by JmillsExpensify** [comment] 2022-11-26 21:37
Agree that the keyboard issues are wider. As for the reproducibility, I think this comes down to whether it's a bug because we can reproduce it on any Android phone, versus wether we can reproduce it on one of the major Android phones in the market (focusing on the US market, because that's where our users overwhelmingly are).

**Comment by JmillsExpensify** [comment] 2022-11-26 21:40
So specifically speaking to Samsung A51, that phone was announced in December 2019. It's going on three years, which is fine but I think that also makes it harder to optimize for. Then on top of that, we have the much bigger convo on which brands/devices in the Android ecosystem we're going to support and which we aren't. I would say for now we should keep this closed unless we can reproduce on another, either newer or "pure" Android device from Google.

**Comment by Julesssss** [comment] 2022-11-28 10:51
> So specifically speaking to Samsung A51, that phone was announced in December 2019. 

It was reproducible for me on a brand-new Pixel 6a. Rather than being device specific, I think there are additional requirements to reproduce which we are unaware of.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:49
Thanks added the `Needs Reproduction` label, though I'm inclined to keep it closed until we figure out how to reproduce it everytime.

**Comment by Julesssss** [comment] 2022-11-29 12:49
I'm not 100% sure that this is resolved, but based on my work to use adjustResize in the past I believe there's a good chance [this PR](https://github.com/Expensify/App/pull/13106) entirely resolves this issue.
