### ISSUE TITLE
[$500] iOS - Log out - App flashes briefly when logging out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37291] opened 2024-02-27 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Tap Profile settings.
3. Tap Log out.

## Expected Result:
App will not flash when logging out

## Actual Result:
App flashes briefly when logging out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/873863da-3c76-42a9-bf63-85625233a11e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b5b9e8d283e67e9</li>
        <li>Upwork Job ID: 1762478035092205568</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 14:01
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Julesssss** [comment] 2024-02-27 14:26
I can't reproduce on iOS, and I verified this isn't occurring on Android. @kbecciv which iOS model did this occur on?

https://github.com/Expensify/App/assets/10736861/97a78a0c-547f-4fd4-acf9-2d2290c7a706

**Comment by Julesssss** [comment] 2024-02-27 14:27
This isn't a blocker, and it doesn't seem related to VIP-VSB either. Reducing priority, and if we can't reproduce on a specific device I'm going to close the issue.

**Comment by Julesssss** [comment] 2024-03-01 09:14
I'm not convinced this is reproducable, closing.

**Closed by Julesssss** 2024-03-01 09:14 UTC
Labels: External, Engineering, Daily, Help Wanted

**Comment by kbecciv** [comment] 2024-03-05 17:39
@Julesssss iPhone 15 Pro Max / iOS 17.3.1

**Comment by kbecciv** [comment] 2024-03-06 17:26
@mkhutornyi Issues is no longer reproduced!
