### ISSUE TITLE
[$500] Web - Request money - Emoji reaction is not working

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26736] opened 2023-09-05 00:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 users on 2 browsers
2. User A create a workspace and invite user B
3. User B create request money for Workspace
4. User B click request money preview
5. User B send any message and react on the message
6. User A only sees the message and does not see user B's reaction
      
## Expected Result:
User A can see user B's reaction

## Actual Result:
User A can not see user B's reaction

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e9fe6c5e-2137-4721-a30f-ed7cf95e1807

https://github.com/Expensify/App/assets/93399543/5ce2c1f2-866c-49ff-8850-3aeb621df3bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693483218312999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ca3b57653c7668e</li>
        <li>Upwork Job ID: 1699153652203536384</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by binary3oul** [comment] 2023-09-05 21:55
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request money - Emoji reaction is not working on User A

### What is the root cause of that problem?

When user A adds an emoji, the API responses from onyxData are returned as an empty array.

![Screenshot 2023-09-05 165012](https://github.com/Expensify/App/assets/134395032/81a80974-041d-47ff-8016-98f6d5019051)

In contrast, when user B adds an emoji icon, the response that arrives at the front-end looks like this:

![Screenshot 2023-09-05 165047](https://github.com/Expensify/App/assets/134395032/62896101-7484-417d-a6cd-6eb8dc2bc647)

### What changes do you think we should make in order to solve the problem?

I believe the back-end (BE) adds an "if" condition specifically for user A to prevent socket emission.
We need to update BE

**Comment by burczu** [comment] 2023-09-06 11:58
@johncschuster I agree with @binary3oul that it looks like BE bug - I think we should change the label to `Internal` to get an opinion from backend engineer.

**Comment by johncschuster** [comment] 2023-09-06 20:17
Thanks, @burczu! In that case, I'll change this to `Internal` 👍

**Comment by Li357** [comment] 2023-09-06 22:16
This almost seems like an intentional move on how expense reports are shared in the backend with an unintended consequence. Asking about it [here](https://expensify.slack.com/archives/C03TQ48KC/p1694038451170229) in #eng-chat

**Comment by Li357** [comment] 2023-09-11 13:44
Verified the backend fix worked! Closing this out.

**Closed by Li357** 2023-09-11 13:44 UTC
Labels: Engineering, Daily, Overdue, Bug
