### ISSUE TITLE
[$500] Mweb - IOU - When user creates distance request, unexpected error is displayed.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32824] opened 2023-12-11 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Workspace chat
3. Tap plus icon --- request money --- Distance
4. Enter start "1907 Woodland Ave, Coffeyville, KS" and finish "1859 County RD 4300"  waypoints
5. Tap next
6. Tap Request

## Expected Result:
User must be able to create distance request.

## Actual Result:
When user creates distance request, unexpected error is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fabd3c19-0dfa-4677-a716-8743344f8e89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab7e708380b1f9ec</li>
        <li>Upwork Job ID: 1734241321301344256</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-12-12 10:59
Cannot reproduce the bug.

**Comment by dksingla** [comment] 2023-12-15 11:06
Seems to be a BE error. It's producible with the 'Start' and 'Finish' used in the bug report. Following is the response from the server.

```
{
  "code": 666,
  "jsonCode": 666,
  "type": "Expensify\\Libs\\Error\\ExpError",
  "UUID": "80ADBEDB-6248-4C16-B2EA-85E03A744715",
  "message": "An unexpected error occurred, please try again. If the error persists, please reach out to concierge@expensify.com.",
  "title": "",
  "data": {
    "onyxData": [
      {
        "onyxMethod": "merge",
        "key": "transactions_5587980153775394500",
        "value": {
          "errors": {
            "1702638081170151": "An unexpected error occurred, please try again. If the error persists, please reach out to concierge@expensify.com."
          }
        }
      }
    ]
  },
  "htmlMessage": "",
  "onyxData": [
    {
      "onyxMethod": "merge",
      "key": "transactions_5587980153775394500",
      "value": {
        "errors": {
          "1702638081170151": "An unexpected error occurred, please try again. If the error persists, please reach out to concierge@expensify.com."
        }
      }
    }
  ],
  "requestID": "835e3010fe2e2e39-BOM"
}
```

**Comment by MitchExpensify** [comment] 2023-12-15 21:51
Does this need to be handled internally @c3024 ?

**Comment by c3024** [comment] 2023-12-17 16:51
Yes, this needs to be internal.

**Comment by MitchExpensify** [comment] 2023-12-20 12:31
@neil-marcellini, as the distance maestro, what do you think this error message should read as?

**Comment by MitchExpensify** [comment] 2023-12-27 10:52
Is this wave 5 @DylanDylann ?

**Comment by MitchExpensify** [comment] 2024-01-01 00:37
Not overdue but realizing I tagged the wrong Dylan - @dylanexpensify* - Is this wave 5?

**Comment by mvtglobally** [comment] 2024-01-03 05:49
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment] 2024-01-04 22:06
> @dylanexpensify* - Is this wave 5?

Friendly bump :)

**Comment by c3024** [comment] 2024-01-05 09:28
@cead22 this needs to be dealt internally.

**Comment by MitchExpensify** [comment] 2024-01-08 23:39
> this needs to be dealt internally.

Reassigned the label to assign an internal engineer based on this comment from @c3024

**Comment by mvtglobally** [comment] 2024-01-11 05:58
Issue not reproducible during KI retests. (Second week)

**Comment by aldo-expensify** [comment] 2024-01-11 14:44
The issue has been identified in the backend and will be fixed by this PR: https://github.com/Expensify/Web-Expensify/pull/40462

**Comment by iwiznia** [comment] 2024-01-11 18:15
Removed the $ from https://github.com/Expensify/Web-Expensify/pull/40462 because you need to update secure too

**Comment by aldo-expensify** [comment] 2024-01-11 20:07
Web-S PR: https://github.com/Expensify/Web-Secure/pull/2627

**Comment by aldo-expensify** [comment] 2024-01-15 15:35
Fix is in staging https://github.com/Expensify/Web-Expensify/pull/40462

**Comment by aldo-expensify** [comment] 2024-01-15 15:41
Confirmed that this is fixed:


https://github.com/Expensify/App/assets/87341702/d50cd9cb-da2d-48e4-82b2-eb25c0c00d5c

Confirmed that this has been fixed in staging

**Closed by aldo-expensify** 2024-01-15 15:41 UTC
Labels: Engineering, Daily, Internal, Bug
