### ISSUE TITLE
[HOLD for payment 2023-06-07] [$1000] Login - No message that the account was "Closed Successfully" below the email field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18686] opened 2023-05-09 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login to ND
3. Navigate to Settings > Security
4. Click/tap on "Close Account"

## Expected Result:
User are logged out and that there's a message in the login screen that the account was "Closed Successfully" below the email field.

## Actual Result:
User are logged out, but that there's no a message in the login screen that the account was "Closed Successfully" below the email field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
https://expensify.testrail.io/index.php?/tests/view/3447225

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/008c5a1d-88a8-4461-abbe-2154dd05c64c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db54583762870fd2</li>
        <li>Upwork Job ID: 1656431594058833920</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-05-09 22:10
QA team is Failed the step 9 on TestRail
![image](https://github.com/Expensify/App/assets/93399543/47bfcd5e-9767-4002-94ca-4ee3208329a1)

**Comment by hungvu193** [comment] 2023-05-10 03:00
## Proposal
I'm able to reproduce this issue.
### Please re-state the problem that we are trying to solve in this issue.
Login - No message that the account was "Closed Successfully" below the email field
### What is the root cause of that problem?
When we closed the account, we also logged user out and when logging out we also clear the Onyx storage.
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/libs/actions/SignInRedirect.js#L31-L54
Because of that, the information from `ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM` is also cleared, which causes the issue.
### What changes do you think we should make in order to solve the problem?
We shouldn't clear `ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM` when user logged out, because we still need to use it.
So we need to add this key to the `keysToPreserve` array inside `clearStorageAndRedirect` function.
```javascript
 const keysToPreserve = [];
    keysToPreserve.push(ONYXKEYS.NVP_PREFERRED_LOCALE);
    keysToPreserve.push(ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM);
    keysToPreserve.push(ONYXKEYS.ACTIVE_CLIENTS);
    keysToPreserve.push(ONYXKEYS.DEVICE_ID);
```
Also with browser that enable the auto-fill function, the message isn't showed because it will trigger text change when user logged out, and because we also cleared the "Close account successfully" message on text change, we can consider remove this piece of code inside onTextInput of LoginForm:
https://github.com/Expensify/App/blob/45c3212061983394e0919839248512874c2af83f/src/pages/signin/LoginForm.js#L116C15-L118

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2023-05-10 22:50
Was able to repro on MacOS / Safari, didn't find any similar issues, agree this is unexpected behavior.

**Comment by httol** [comment] 2023-05-11 01:19
<img width="347" alt="image" src="https://github.com/Expensify/App/assets/4971746/d5fa4d23-d0d3-40a9-b126-f003188c477e">
<img width="380" alt="image" src="https://github.com/Expensify/App/assets/4971746/6ab2a6ce-32ca-42c4-a30f-ca30e9f09163">
Reproducible in staging?: Yes
Reproducible in production?: No
Seems the problems only exsit in staging

**Comment by dukenv0307** [comment] 2023-05-11 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User are logged out, but that there's no message in the login screen that the account was "Closed Successfully" below the email field.

### What is the root cause of that problem?
There're 2 problems:
1. The Onyx value `closeAccount` that's used to show the account closed message here https://github.com/Expensify/App/blob/a7dc7c717729afd54db436eaa5e9216a55da18c1/src/pages/signin/LoginForm.js#L193, was removed after the user closes the account. Because when the user closes account the user is logged out immediately, and we're clearing most Onyx values when logging out.

2. When the text input in the `LoginForm` is autofilled by the browser, it will trigger text change which will clear the account closed message as can be seen here: https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/pages/signin/LoginForm.js#L117

### What changes do you think we should make in order to solve the problem?


1. We should preserve the `ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM` key when logging out, we can add `keysToPreserve.push(ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM);` below this line https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/libs/actions/SignInRedirect.js#L35

2. When text change, we need to check if it's autofilled by browser, if yes then we'll not clear the close account message. We only clear close account successful message when text changes due to user input.

The approach to check if input is autofilled is already used here https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/components/TextInput/BaseTextInput.js#L134 in the code base.

We can introduce a new method somewhere common for reuse
```
isInputAutofilled(inputRef) {
        if (!inputRef.matches) {
            return false;
        }

        return inputRef.matches(':-webkit-autofill') || inputRef.matches(':autofill');
    }
```

Then change this condition https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/pages/signin/LoginForm.js#L116

to 
```
if (this.props.closeAccount.success && !isInputAutofilled(this.input)) {
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by tienifr** [comment] 2023-05-15 10:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After close the account, "Closed Successfully" message is not shown

### What is the root cause of that problem?

>  We should preserve the ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM key when logging out, we can add keysToPreserve.push(ONYXKEYS.FORMS.CLOSE_ACCOUNT_FORM); below this line

@dukenv0307's proposal won't work because we don't call `clearStorageAndRedirect` function to clear Onyx data

After confirm close account, we call `CloseAccount` API. Here is the response from pusher 

<img width="395" alt="Screenshot 2023-05-15 at 17 27 35" src="https://github.com/Expensify/App/assets/113963320/a5aee215-de2b-44d3-bc82-e453081721df">

We have 3 actions: clear onyx data, merge preferredLocale and merge closeAccount

In https://github.com/Expensify/react-native-onyx/blob/0fbe0a4d077f96c4bc30b0b14359f634b271b03b/lib/Onyx.js#L1212

We perform all actions simultaneously, so we can meet race condition (clear other data -> merge closeAccount -> clear closeAccount,...)

### What changes do you think we should make in order to solve the problem?

When call Onyx.update we should perform clear action first if there is, then perform other actions (merge, set, ...)

### Result


https://github.com/Expensify/App/assets/113963320/1888d080-f157-44b1-9319-98e5a672c13e

**Comment by puneetlath** [comment] 2023-05-15 14:40
@eVoloshchak thoughts on the proposals?

**Comment by eVoloshchak** [comment] 2023-05-17 15:36
@hungvu193, @dukenv0307, I don't see `clearStorageAndRedirect` being called when closing an account. Could you double-check this, please?

**Comment by dukenv0307** [comment] 2023-05-17 15:44
That's right, It is my mistake. Agree with @tienifr's [proposal](https://github.com/Expensify/App/issues/18686#issuecomment-1547613236)

**Comment by eVoloshchak** [comment] 2023-05-17 15:50
@tienifr's [proposal](https://github.com/Expensify/App/issues/18686#issuecomment-1547613236) looks good

> We perform all actions simultaneously, so we can meet race condition (clear other data -> merge closeAccount -> clear closeAccount,...)
When call Onyx.update we should perform clear action first if there is, then perform other actions (merge, set, ...)
![image](https://github.com/Expensify/App/assets/9059945/938bdb5f-f6a8-4eef-a03a-ea32998e1c43)

I wonder if the order of actions passed from the back end matters. In this case, it makes no difference (since the `clear` action is already the first item). But if the order of actions matters and there is a case where the backend would return something like
```
1. 'merge'
2. 'clear'
3. 'set'
```

Should we disregard the order and still perform the clear action first?
I'm almost sure this doesn't matter since currently we're performing all of the actions simultaneously. 
@puneetlath, could you chime in on this please?

**Comment by hungvu193** [comment] 2023-05-17 16:04
> @hungvu193, @dukenv0307, I don't see `clearStorageAndRedirect` being called when closing an account. Could you double-check this, please?

Damn I swear it worked before 😂 , I was going to record a video to capture the result but I forgot. Anyway I didn't see `clearStorageAndRedirect` is being called now. My proposal isn't valid.

**Comment by tienifr** [comment] 2023-05-18 02:40
https://github.com/Expensify/react-native-onyx/blob/1d496b001f327c509131597faf260a81c002be77/lib/Onyx.js#L1194-L1215

I think we should change these lines to

```
    const promises = [];
    const clearPromise = Promise.resolve();
    
    _.each(data, ({onyxMethod, key, value}) => {
        switch (onyxMethod) {
            case METHOD.SET:
                promises.push(()=>set(key, value));
                break;
            case METHOD.MERGE:
                promises.push(()=>merge(key, value));
                break;
            case METHOD.MERGE_COLLECTION:
                promises.push(()=>mergeCollection(key, value));
                break;
            case METHOD.CLEAR:
                clearPromise = clear
                break;
            default:
                break;
        }
    });

      return clearPromise.then(()=>Promise.all(_.map(promises,p=>p())));

```

 @puneetlath @eVoloshchak please let me know what you think. Thanks

**Comment by puneetlath** [comment] 2023-05-18 20:03
@tienifr we were discussing in this thread, but I'm still a little unclear on the root cause. In theory when we do `promises.push(clear());` that is actually immediately calling the clear method. And then `return Promise.all(promises);` just returns when all the promises that have already been called are completed. Is that a correct understanding? 

If so, in theory, the clear/merge/merge are being called in order right? Do they happen synchronously, one after the other? Or do they happen at the same time?

**Comment by tienifr** [comment] 2023-05-19 04:48
> In theory when we do promises.push(clear()); that is actually immediately calling the clear method. And then return Promise.all(promises); just returns when all the promises that have already been called are completed

That's correct, the clear/merge/merge are being called in order, but they do not happen in the right order. 
1. clear is called first
2. wait for getAllKeys to be done
https://github.com/Expensify/react-native-onyx/blob/1d496b001f327c509131597faf260a81c002be77/lib/Onyx.js#L1051

3. while getAllKeys is not completed, start to call `merge()` (merge closeAccount data)
4. noti closeAccount with success message to subscribers 

https://github.com/Expensify/react-native-onyx/blob/1d496b001f327c509131597faf260a81c002be77/lib/Onyx.js#L871

5. wait for `Storage.setItem` to be done

https://github.com/Expensify/react-native-onyx/blob/1d496b001f327c509131597faf260a81c002be77/lib/Onyx.js#L874

6. getAllKeys (from step 2) is completed 
7. noti closeAccount without success message to subscribers (because it's cleared)

https://github.com/Expensify/react-native-onyx/blob/1d496b001f327c509131597faf260a81c002be77/lib/Onyx.js#L1097

8. ...

That why the closeAccount data doesn't have success message.

@puneetlath let me know if it's still unclear

**Comment by puneetlath** [comment] 2023-05-19 15:12
Ok got it, that does make sense. However, I still don't totally follow how this will solve it: 

```
return clearPromise.then(()=>Promise.all(_.map(promises,p=>p())));
```

Because any merge/set would have already been called before the clear, right?

**Comment by tienifr** [comment] 2023-05-21 16:59
@puneetlath 

change: promises.push(merge(key, value))

to 
promises.push(()=>merge(key, value));

If we do that, the merge/set won't be called till we perform Promise.all(_.map(promises,p=>p()))

**Comment by puneetlath** [comment] 2023-05-22 18:45
Ah got it. In that case, sounds good to me.

**Comment by tienifr** [comment] 2023-05-23 04:35
@puneetlath @eVoloshchak The PR: https://github.com/Expensify/react-native-onyx/pull/250 is ready for review

**Comment by stephanieelliott** [comment] 2023-05-24 16:56
The PR in Expensify/react-native-onyx was merged 👏

**Comment by tienifr** [comment] 2023-05-25 03:23
@eVoloshchak @puneetlath The PR on App is ready for review: https://github.com/Expensify/App/pull/19579

**Comment by stephanieelliott** [comment] 2023-05-30 17:05
PR deployed to staging but it looks like there was a regression, being discussed in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685441927670609)

**Comment by stephanieelliott** [comment] 2023-06-07 16:32
Hey @eVoloshchak can you please complete the BugZero checklist above?

**Comment by eVoloshchak** [comment] 2023-06-08 15:48
- The PR that introduced the bug has been identified. Link to the PR: N/A, this was a limitation of `react-native-onyx` and it was implemented initially

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a

-  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a simple visual bug (text label not appearing) with a complex cause. I don't think there are any additional steps that could be taken, this could have been caught during review.

**Comment by eVoloshchak** [comment] 2023-06-08 15:49
**Regression Test Proposal**

1. Navigate to Settings > Security
2. Click/tap on "Close Account", you're navigated to login screen
3. Verify that there's a message that the account was closed successfully below the email field

**Do we agree 👍 or 👎**

**Comment by stephanieelliott** [comment] 2023-06-08 22:16
LGTM! @eVoloshchak and @tienifr are paid, but leaving this open til I can create the GH for the regression test.

**Comment by stephanieelliott** [comment] 2023-06-12 14:21
Yep! Regression test here: https://github.com/Expensify/Expensify/issues/291294

**Closed by stephanieelliott** 2023-06-12 14:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
