### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Thread - Messages have a "Leave thread" option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35397] opened 2024-01-30 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat.
2. Send a message.
3. Right-click on the message

## Expected Result:
There should be no "Leave Thread" option if no thread exists.

## Actual Result:
Messages without threads have a "Leave Thread" option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8d44c6f2-bbc9-4566-a286-a6822d5483de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce5f6a37e8f18a12</li>
        <li>Upwork Job ID: 1752456002131746816</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28134907</li>
<li>paultsimura | Contributor | 28134908</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 13:11
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by sakluger** [comment] 2024-01-30 18:17
Closing for now since I can't reproduce. I asked in #QA to reopen the issue if they find consistent reproduction steps.

**Comment by kbecciv** [comment] 2024-01-30 19:06
QA team is able to reproduce it with above steps

https://github.com/Expensify/App/assets/93399543/cd85347c-b44d-4982-b47c-e2e04a047797

**Comment by sakluger** [comment] 2024-01-30 21:32
Updated the original description to focus on the fact that message without threads have a "Leave Thread" option.

**Comment by paultsimura** [comment] 2024-01-30 21:58
This has been discussed in multiple places already – it's expected behavior – similar to Slack's "do not receive notifications for this message" – it happens only if you're the author of the message.

<img width="794" alt="image" src="https://github.com/Expensify/App/assets/12595293/049508d9-6f8c-4482-a831-225c15e128f0">

https://github.com/Expensify/App/pull/27994/files#r1365082102
cc: @srikarparsi

**Comment by srikarparsi** [comment] 2024-01-31 07:29
We've come to the conclusion to remove the "Leave thread" option for all comments in the comment's overflow menu but keep the "Join thread". [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1706652655309489?thread_ts=1706637134.432169&cid=C9YU7BX5M)

**Comment by paultsimura** [comment] 2024-01-31 07:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Join Thread" option appears for comments in the context menu.

### What is the root cause of that problem?
We explicitly allow these options to appear for the actions, and this change is like an update request:

https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L274-L285

### What changes do you think we should make in order to solve the problem?
If we want to hide the "Join Thread" options for the "hover" menu completely, we can just remove this option:

https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L270-L300

Otherwise, if we want to show it only when there already is a thread, we should early return `false` in the corresponding `shouldShow` function if `!lodashGet(reportAction, 'childReportID', '0')`.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-31 08:00
@srikarparsi could you please share the context for a better understanding of the expected behavior? Contributors don't have access to the Slack link you provided

**Comment by ben-mathu** [comment] 2024-01-31 20:17
Should the comments with deleted replies show "Leave Thread"?

**Comment by ben-mathu** [comment] 2024-01-31 21:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- In chat, messages with no thread show "Leave Thread" on the context menu.

### What is the root cause of that problem?
- There is not dedicated function to check if the message has or had a thread.

### What changes do you think we should make in order to solve the problem?
- Add a check in `ReportActionsUtils` to check if a ReportAction has "children",  a thread.

### What alternative solutions did you explore? (Optional)
- I feel there are too many checks for a thread. There should be only one check for this context menu, if the message has a thread.

**Comment by srikarparsi** [comment] 2024-02-01 04:36
Hey @paultsimura, your proposal looks good, we just need to remove the leaveThread option from the overflow menu for all comments. When do you think you can get a PR out by?

**Comment by paultsimura** [comment] 2024-02-01 06:11
Thanks @srikarparsi, I can make it today

**Comment by paultsimura** [comment] 2024-02-01 17:11
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35573

**Comment by sakluger** [comment] 2024-02-15 00:53
I paid out @paultsimura.

@Ollyws could you please accept the Upwork offer and also complete the BZ checklist? Thanks!

**Comment by sakluger** [comment] 2024-02-15 21:59
Thanks! All paid out 🙌

**Closed by sakluger** 2024-02-15 21:59 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
