### ISSUE TITLE
[$250] Thread - The message "left the chat" is repeated endlessly in the deleted message thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44918] opened 2024-07-05 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4696971
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log in with account A
3. In incognito mode, log in to account B
4. Under user A, send a manual IOU to user B
5. Create a thread in this IOU
6. Send several messages in the IOU thread
7. Delete the IOU
8. Under user B, open to the deleted IOU thread
9. User B: Click on the "Join" button
10. User B: Click on the three dots in the header
11. User B: Click on "Leave"
12. Under user A, open and refresh the deleted IOU thread

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0df28678-c6e9-4bfd-b155-4fa3b2f3985e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01565b5a941ea6d86a</li>
        <li>Upwork Job ID: 1812813116893292566</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-07-05 15:23
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment] 2024-07-15 11:35
Not overdue

**Comment by s77rt** [comment] 2024-07-18 18:12
Still looking for proposals

**Comment by s77rt** [comment] 2024-07-19 18:07
Same ^

**Comment by hannojg** [comment] 2024-07-22 11:20
Hi, I am Hanno from Margelo, an expert agency and I can work on this issue.

**Comment by s77rt** [comment] 2024-07-22 11:59
@hannojg Thanks for taking this. Looking forward for your input 🚀

**Comment by hannojg** [comment] 2024-07-22 12:24
Hm, I can't reproduce on the dev branch - also the UI has changed a bit since then:

- I see no three dots button, but rather a. chevron button which opens the RHP
- I have no explicit "join" button, I can "join" by writing a message and only then I can explicitly leave the thread\


https://github.com/user-attachments/assets/33188faf-67d4-4acf-9713-70f88c0fd639

Testing on staging now …

**Comment by hannojg** [comment] 2024-07-22 12:26
Can't really reproduce on staging either 🤔 

https://github.com/user-attachments/assets/5a3bc6e8-6b63-42db-b3be-a3a9cd0ab9eb

**Comment by s77rt** [comment] 2024-07-22 23:18
I can't reproduce either. The "left the chat" message is shown once

https://github.com/user-attachments/assets/f7ea0e3b-0980-44c7-9e72-781d243f9766

**Comment by muttmuure** [comment] 2024-07-24 10:41
If it's not reproducible, let's close it.

**Closed by muttmuure** 2024-07-24 10:41 UTC
Labels: External, Daily, Help Wanted, Bug
