### ISSUE TITLE
[$250] Xero - App Crashes when navigating to Accounting page when connecting to Xero

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45566] opened 2024-07-17 07:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4729589
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Sign in with expensifail account as a new user
2. Navigate to workspace settings >More features> Accounting
3. Enable accounting
4. Go to the Accounting settings page and click on Connect to Xero
5. Enable 2FA and continue
6. The Xero site will be opened in a new tab
7. Enter the Xero credentials to log in and complete the connection (Here notice that the Xero connection isn't established)
8. Go back to staging
9. Navigate back and away from the Accounting settings page

## Expected Result:
Xero connection is established and the accounting page opens properly

## Actual Result:
App crashes when navigating to accountings page and connection to Xero is not established

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cdbd44c0-672f-4764-a285-6f1a37730e3b

[Bug6544674_1721193023389!staging.new.expensify.com-1721192917726.txt](https://github.com/user-attachments/files/16261885/Bug6544674_1721193023389.staging.new.expensify.com-1721192917726.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3aea544c5139591</li>
        <li>Upwork Job ID: 1813704314112548490</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by izarutskaya** [comment] 2024-07-17 07:33
We think this issue might be related to the #wave-control

**Comment by izarutskaya** [comment] 2024-07-17 07:33
Production

https://github.com/user-attachments/assets/c716c261-7ea1-44b5-9655-7b7c7a51efac

**Comment by grgia** [comment] 2024-07-17 10:28
Quick glance at the deploy checklist

Most likely caused by https://github.com/Expensify/App/pull/44059


Other potential culprits:

https://github.com/Expensify/App/pull/45375/files#diff-cba2d7681fcae80a49675e4cbe9fb66e66f6cc12cdb292550dcf9bff22ae5145 

https://github.com/Expensify/App/pull/44930/files

**Comment by grgia** [comment] 2024-07-17 10:28
@rushatgabhane

**Comment by mananjadhav** [comment] 2024-07-17 10:35
> https://github.com/Expensify/App/pull/45375/files#diff-cba2d7681fcae80a49675e4cbe9fb66e66f6cc12cdb292550dcf9bff22ae5145

@grgia This code doesn't touch any of the Xero or related Policy files. I think this can be excluded.

**Comment by mountiny** [comment] 2024-07-18 10:11
Merged the revert and CPing it to staging

**Comment by mountiny** [comment] 2024-07-18 10:30
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1721298585014889) on 8-5 version

**Comment by mountiny** [comment] 2024-07-18 13:33
fixed https://expensify.slack.com/archives/C9YU7BX5M/p1721298585014889

**Comment by mountiny** [comment] 2024-07-23 19:23
I believe this can be closed as we just reverted the pr

**Closed** 2024-07-24 09:40 UTC
Labels: External, Engineering, Daily, Overdue, Bug
