### ISSUE TITLE
HIGH: [UX Reliability] Fix native Android keyboard selection

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40994] opened 2024-04-25 15:38 UTC
Being discussed here: https://expensify.slack.com/archives/C05LX9D6E07/p1714055772402719?thread_ts=1713918954.937979&cid=C05LX9D6E07

**Comment by quinthar** [comment] 2024-04-25 15:39
@hurali97 Can you please flesh this issue out with a problem/solution statement? Thanks!

**Comment by hurali97** [comment] 2024-04-26 06:06
### Problem:

The user is unable to select text in the composer. See the below video:

<details>
<summary>video</summary>

https://github.com/Expensify/App/assets/47336142/68230ee1-7fcf-455b-8322-84af8f77c284

</details>

### Solution:

The issue is originating from the usage of `MarkDownTextInput` in the composer. If we replace `MarkDownTextInput` with `TextInput` from `react-native` the issue is fixed.  See the below video:

<details>
<summary>video</summary>


https://github.com/Expensify/App/assets/47336142/2393f7cf-6aaf-4d5e-b9f5-00beba062d62



</details>

The solution here is not to replace `MarkDownTextInput` but rather fix the root cause inside of this library. Folks from SWM worked on this library and they are the best fit to take this from here but in case if they don't have the bandwidth we can help narrowing down this issue and fixing it at the root.

**Comment by quinthar** [comment] 2024-04-27 21:14
Will be fixed by https://github.com/Expensify/App/issues/40890, closing this one.

**Comment by hayata-suenaga** [comment] 2024-04-30 18:53
I'll close this issue 😄

**Closed by hayata-suenaga** 2024-04-30 18:53 UTC
Labels: Reviewing, Weekly
