### ISSUE TITLE
Get started - The `Get started here` message is shown in the wrong position

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52595] opened 2024-11-14 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to an account
2. Create a workspace > add a new employee
3. Log in with the new employee account
4. Notice the get started here message is shown on the workspace chat,
5. Resize the window

## Expected Result:
The `Get started here` message is dismissed when resizing or it is should move with window and point on the right position.

## Actual Result:
The `Get started here` message is not shown in the right position when resizing the window.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e1573e5a-fe3f-445d-b080-7f0bc0d99a7d
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment] 2024-11-15 03:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When resizing browser window width, `Get started here` tooltip is put on wrong position.

### What is the root cause of that problem?
It doesn't have a feature to close the tooltip when browser window width is resized.

When resizing browser window width, the tooltip's position `left` stays. The tooltip follows compose box's position, which already moved because of resizing browser window width.

### What changes do you think we should make in order to solve the problem?
We can give a feature to close the tooltip when browser window width changed. Here the tooltip component is rendered:

https://github.com/Expensify/App/blob/b2b6e2d80e6ad3777c92b9ba1aca15c24ef8d27e/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L419-L420

Bring `windowWidth` to capture resizing width.
 Set a `initialWidth` to get initial window width. Give a react hook that gives a signal that window width is changed and pass it into the component.

```js

const {windowWidth} = useWindowDimensions();
const [isWidthUnchanged, setWidthUnchanged ]= useState(true)
const initialWidth = useRef(windowWidth)

useEffect(() => {
  if(initialWidth.current !== windowWidth) {
    setWidthUnchanged(false)
  }}, [windowWidth]);

...

<EducationalTooltip
  shouldRender={isWidthUnchanged}
...

```

And we can make `useEffect` to close the tooltip in `BaseEducationalTooltip` component that is a son of `<EducationalTooltip>`. There is already `closeTooltip()` function for this solution.

```js

useEffect(() => {
  closeTooltip();
 }, [shouldRender]);

```

So whenever resizing window width, the tooltip will be closed if the width is different to when the tooltip is initially rendered.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by huult** [comment] 2024-11-15 04:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Get started here message is shown in the wrong position

### What is the root cause of that problem?

As per the current logic, we only handle auto-closing the tooltip in case of unmounting, auto-hiding after 5 seconds, and when the modal is opened

https://github.com/Expensify/App/blob/5cd60866cf3bb8895c9eb67d69b7b2855e0ee17f/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L73-L82

https://github.com/Expensify/App/blob/5cd60866cf3bb8895c9eb67d69b7b2855e0ee17f/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L102-L106


### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to add a case where the tooltip still auto-hides if the dimensions are changed, something like this:

1. Save the previousDimensions after initializing the tooltip.
```diff
+    const {windowWidth, windowHeight} = useWindowDimensions();
+    const previousDimensions = usePrevious({windowWidth, windowHeight});
```

2. We check if the height or width has changed, and then we auto-hide the tooltip.

```diff
+    useEffect(() => {
+        if (previousDimensions.windowHeight !== windowHeight) {
+            closeTooltip?.();
+        }
+        if (previousDimensions.windowWidth !== windowWidth) {
+            closeTooltip?.();
+        }
+    }, [windowWidth, windowHeight, previousDimensions.windowHeight, previousDimensions.windowWidth, closeTooltip]);
```

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/c1ab3a7c-047c-4cb9-adaa-e8d78d0c1ad6

upload here

</details>

**Comment by mkzie2** [comment] 2024-11-15 11:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Get started here message is not shown in the right position when resizing the window.

### What is the root cause of that problem?

When `windowWidth` or `windowHeight` changed, the tooltip target bounds also changed (in this case, it's the `ReportActionCompose`) but the tooltip position is not re-computed accordingly. Specifically, `tooltipTargetWidth` and `tooltipTargetHeight` are not updated, causing `horizontalShift`, `rootWrapperLeft` and `rootWrapperTop` to be incorrect:

https://github.com/Expensify/App/blob/be303036704ad6f82b47b71e0d1018f0c7364766/src/styles/utils/generators/TooltipStyleUtils/computeHorizontalShift/index.ts#L23-L25

https://github.com/Expensify/App/blob/5c4b81299af694c63d280e6e875f497e7255e74f/src/styles/utils/generators/TooltipStyleUtils/index.ts#L197

https://github.com/Expensify/App/blob/5c4b81299af694c63d280e6e875f497e7255e74f/src/styles/utils/generators/TooltipStyleUtils/index.ts#L156-L158

### What changes do you think we should make in order to solve the problem?


We need to force a re-measurement of the tooltip's target when `windowWidth` or `windowHeight` changes.

1. So in `BaseEducationalTooltip`, check if `windowDimensions` changes to enable `shouldMeasure`:

```javascript
const {windowWidth, windowHeight} = useWindowDimensions();
const prevDimensions = usePrevious({windowWidth, windowHeight});

useEffect(() => {
    if (shouldMeasure || !shouldShow) {
        return;
    }
    if (prevDimensions.windowWidth === windowWidth && prevDimensions.windowHeight === windowHeight) {
        return;
    }
    setShouldMeasure(true);
}, [windowWidth, windowHeight, shouldMeasure, shouldShow]);
```

As a result, this effect would be trigger where `show.current` contains a method to measure the component's position:

https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L93-L96

https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L125

2. In the above effect's timeout callback, we need to `setShouldMeasure(false);` and remove the `didShow.current` condition which were used to prevent re-measurement if it was already measured the first time:

https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L89

```javascript
if (!shouldMeasure || !shouldShow) {
    return;
}
const timerID = setTimeout(() => {
    show.current?.();
    didShow.current = true;
    setShouldMeasure(false);
}, 500);
```

3. In this step, we notice that if we resized the window, the tooltip would be closed then shown again due to the `showTooltip` call inside the `show` function ref:

https://github.com/Expensify/App/blob/b9d18659ec3cd3b99de220f42164f339d2905298/src/components/Tooltip/EducationalTooltip/measureTooltipCoordinate/index.ts#L7

To fix this, introduce a new param `shouldShowAfterMeasure` to conditionally call `showTooltip` in the above callback.

Then pass `!didShow.current` as `shouldShowAfterMeasure` to the callback:

https://github.com/Expensify/App/blob/9228354caa0f3731ec7d05241fd8363c13477c5b/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L125

```javascript
show.current = () => measureTooltipCoordinate(target, updateTargetBounds, showTooltip, !didShow.current);
```

**Comment by trjExpensify** [comment] 2024-11-15 12:06
The likelihood of an employee resizing their window like this in practice is so small, I'm going to close this issue.

**Closed by trjExpensify** 2024-11-15 12:06 UTC
Labels: Daily, Bug
