### ISSUE TITLE
[$500] Login - "Magic code expired" when try to sign in via "Sign In here" on Incognito window

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37350] opened 2024-02-27 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4343102
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new INCOGNITO window and navigate to the staging link
4. Verify the "Here's your magic code" page is displayed
5. Verify there's a link to "Sign In here"
6. Click on the link to "Sign in here"

## Expected Result:
The user is successfully logged in

## Actual Result:
"Magic code expired" when try to sign in via "Sign In here" on Incognito window

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2325002c-03d4-4972-9f46-b929ef8304ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d71b0593716c5352</li>
        <li>Upwork Job ID: 1763205363155681280</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 20:58
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-02-27 20:58
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-02-29 14:11
Was able to recreate on my side as well — I believe this could be fixed on the front end, so going to apply the **External** label 👍 

Thanks @lanitochka17!

**Comment by CortneyOfstad** [comment] 2024-02-29 14:12
Asked in VIP-VSB [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1709215951624059).

**Comment by CortneyOfstad** [comment] 2024-02-29 14:54
@c3024 @lanitochka17 so the more I review this, I'm leaning towards this not being a bug, as the incognito window would not recognize the magic code, as it was requested via the regular browser. 

I wonder if instead, the issue is the language itself — not that the magic code is "expired" but something else, like invalid/not applicable/etc. I've commented on the post in VIP-VSB to get other's thoughts and will follow-up as soon as I hear back 👍

**Comment by c3024** [comment] 2024-02-29 15:49
@CortneyOfstad 

I agree. This is expected and not a bug IMO.

**Comment by CortneyOfstad** [comment] 2024-02-29 15:52
Thank you @c3024! Going to wait on word about the language aspect, and will see if this can just be closed or not 👍

**Comment by c3024** [comment] 2024-02-29 15:58
Yes, I missed that. The language can be more clear. 👍

**Comment by CortneyOfstad** [comment] 2024-03-11 18:25
Was OoO but confirmed the language does need to be cleaned up.

**Comment by CortneyOfstad** [comment] 2024-03-14 11:59
Going to adjust this to weekly, as the priority is quite low on this 👍

**Comment by mvtglobally** [comment] 2024-03-20 03:42
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-03-22 14:42
Testing this today – will follow up if I am able to get the same message as before 👍

**Comment by CortneyOfstad** [comment] 2024-03-22 19:29
I am not able to recreate this either — however having some trouble with staging as I am currently logged into Concierge under that. Will try again either later today or early Monday before I am in Concierge to test it properly, as I think that was gumming something up.

**Comment by CortneyOfstad** [comment] 2024-03-25 14:40
I am not able to recreate this anymore – the text has been changed and is more reflective of the incorrect flow, as shown below:

<img width="1348" alt="Screenshot 2024-03-25 at 9 39 11 AM" src="https://github.com/Expensify/App/assets/10926327/e31c0e5e-0d08-4849-b3f0-e5db229f9a3a">

Because of this, going to close!

**Closed by CortneyOfstad** 2024-03-25 14:40 UTC
Labels: Engineering, Daily, Internal, Overdue, Waiting for copy, Bug, Hot Pick
