### ISSUE TITLE
[$250] [HOLD for payment 2024-04-05] Workspace - One of the dropdown options configured in OD is missing from ND

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38898] opened 2024-03-24 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:**

## Action Performed:
1. Log into OD with a new expensifail account
2. OD: Create a Collect workspace with chat enabled
3. OD: Navigate to Workspace settings - Reports - Report and Invoice Fields
4. OD: Add a dropdown field with any name and "Expense Report" type
5. OD: Add 3 options under the dropdown "1" "2" and "3"
6. OD: Set "1" as the initial value
7. OD: Invite a new expensifail account to the workspace as member
8. ND: Log in as the member
9. ND: Create a manual IOU in the workspace chat
10. ND: Open the IOU

## Expected Result:
All options should be visible.

## Actual Result:
One of the dropdown option configured in OD is missing from ND. In this instance, it's "2".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0601df54-481f-4826-8295-86d7eb0a2a51

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01286e42f8805eb5ba</li>
        <li>Upwork Job ID: 1778519670656045056</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-24 19:57
We think that this bug might be related to #wave-collect - Release 1

**Comment by ahmedGaber93** [comment] 2024-03-24 23:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - One of the dropdown options configured in OD is missing from ND


### What is the root cause of that problem?
here when we filtering `disabledOptions`  we use this logic `!(value in reportField.disabledOptions))` 
https://github.com/Expensify/App/blob/00e0121fa17a7c19335a8fa10eed51c25e933d6a/src/pages/EditReportFieldPage.tsx#L109
and this the `values` and `disabledOptions`
```
values = ["1","2","3"];
disabledOptions = [false, false, false];
```
this logic is incorrect, because the keyword `in` search for the index in the array not on the value.
for example
```
console.log("1" in ["1"]) // return false because index 1 not found
console.log("0" in ["1"]) // return true because index 0 found
```
so `["1","2","3"].filter((value) => !(value in [false, false, false]));` will return ["3"]


### What changes do you think we should make in order to solve the problem?
we need to change the filter logic to be 
```
reportField.values.filter((_, i) => !reportField.disabledOptions[i])
```

### What alternative solutions did you explore? (Optional)

**Comment by aldo-expensify** [comment] 2024-03-25 19:35
I think @ahmedGaber93 is right about the problem being the usage of the `in` operator here. Testing...

**Comment by aldo-expensify** [comment] 2024-03-25 19:39
hmm I don't think we necessarily have to be consistent with the CategoryPicker, that seems to be dealing with many specific things related to categories and is more complex. I think it is fine for the design of `EditReportFieldDropdownPage` to expect that it should show all values passed in `fieldOptions`

**Comment by aldo-expensify** [comment] 2024-03-25 20:02
> As i said the `edge case` here where we had `selected `a dropdown option but later we `disable` it, then in the list we `won't be able to show` that `disabled option` as now we `don't pass` it to the `component`, this is again a regression as now we will not be able to deselect that disabled option :)

hmmmmmmm that is an interesting case, let me see...

**Comment by aldo-expensify** [comment] 2024-03-25 20:11
I tested and it doesn't seem to cause a problem. If the selected options is not within the list passed to `EditReportFieldDropdownPage`, the value is shown there anyway:


https://github.com/Expensify/App/assets/87341702/4ca03e96-62ee-4b43-93e8-ac6f6c5af6d1

**Comment by aldo-expensify** [comment] 2024-03-25 20:13
In your screenshot, the recent show 2 and 3, were any of those disabled?

**Comment by aldo-expensify** [comment] 2024-03-25 20:14
I think you are right about that there is a problem with the "Recent" options. They should be filtered down by the available (enabled) options too, right?

https://github.com/Expensify/App/blob/4caf61ad062a0e141dc11e12ee5befaed73ae185/src/pages/EditReportFieldDropdownPage.tsx#L92-L104

**Comment by aldo-expensify** [comment] 2024-03-25 20:20
I reproduced the "Recent" options bug offering me a disabled option and I fixed it [here](https://github.com/Expensify/App/pull/38958/files#r1538187047)

@GandalfGwaihir @ahmedGaber93 do you both agree with sharing the reward for fixing this? This would be 250/250? I think both helped sufficiently to split it.

**Comment by ahmedGaber93** [comment] 2024-03-25 20:22
@aldo-expensify fine with me.

**Comment by aldo-expensify** [comment] 2024-03-25 20:23
> I am having second thoughts about filtering at the prop level

Why is that? do you think there may be another bug?

**Comment by aldo-expensify** [comment] 2024-03-25 20:25
hmm maybe we should do a useMemo around `fieldOptions`, otherwise it will be a new array each time we re-render making the this [useMemo](https://github.com/Expensify/App/blob/cd7d8146b79ee04a1598a6f9b1733e6a3ec06633/src/pages/EditReportFieldDropdownPage.tsx#L60) useless

**Comment by aldo-expensify** [comment] 2024-03-25 20:31
I'm not going to add it because the page for selecting an option is not getting re-render when hovering options or scrolling, I only see it re-rendering when we select and option or type something in the top search. I don't think we will win anything from adding the `useMemo` I proposed and it is not straight-forward to implement because of how `EditReportFieldPage` is coded (with many `if`)

**Comment by aldo-expensify** [comment] 2024-03-25 21:00
@kevinksullivan added `Bug` to handle the payments for:

- $250 for @GandalfGwaihir 
- $250 for @ahmedGaber93 

both helped in finding the cause and getting to the final solution

**Comment by aldo-expensify** [comment] 2024-03-25 22:41
Removing Deploy blocker label, the issue is fixed now

**Comment by kevinksullivan** [comment] 2024-04-11 20:26
just using `External` to get the job created in upwork.

**Comment by kevinksullivan** [comment] 2024-04-11 20:30
job created and offer sent to @ahmedGaber93 . Couldn't find @GandalfGwaihir so can you let me know when you apply and I will pay this out? Thanks!

**Comment by kevinksullivan** [comment] 2024-04-11 20:47
all set

**Closed by kevinksullivan** 2024-04-11 20:47 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
