### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] IOU - Blank page after returning to IOU report from thread and deleting the other request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40087] opened 2024-04-11 08:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Create two IOUs.
4. Go to the transaction thread of the first IOU.
5. Click on the header subtitle to return to IOU report.
6. Right click on the second IOU preview > Delete request.
7. Delete the request.

## Expected Result:
App will open one report transaction view (combined IOU report).

## Actual Result:
A blank page shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9da20de7-a8c6-4eaa-a36e-2c75691555cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dc6ca492e81c98f</li>
        <li>Upwork Job ID: 1778531947093139456</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-11 08:16
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-11 08:17
Production 


https://github.com/Expensify/App/assets/115492554/96c4f3f9-04d4-40de-857c-2c1263929ff8

**Comment by youssef-lr** [comment] 2024-04-11 17:07
I'm checking a PR to confirm if it's the offending one

**Comment by youssef-lr** [comment] 2024-04-11 17:13
Confirmed it's a regression from https://github.com/Expensify/App/pull/40079 after reverting it locally, @paultsimura @shubham1206agra @MonilBhavsar can you guys take a look please? @tienifr checking your proposal meanwhile

**Comment by youssef-lr** [comment] 2024-04-11 20:50
Back to searching for the offending PR as I think that would help us know how to fix this properly.

**Comment by youssef-lr** [comment] 2024-04-11 21:00
Ok this is the offending PR https://github.com/Expensify/App/pull/39454, it seems like this is new functionality because when I revert it I don't see the previous report action highlighted. @rayane-djouah @rushatgabhane @jasperhuangg can you guys take a look please @tienifr's proposal?

**Comment by youssef-lr** [comment] 2024-04-11 21:13
It looks good to me too.

**Comment by youssef-lr** [comment] 2024-04-12 02:31
Thanks a lot @tienifr

**Comment by rushatgabhane** [comment] 2024-04-12 08:17
it's under regression period so I'll take care of it

**Comment by youssef-lr** [comment] 2024-04-15 14:42
Asking for CP.

**Comment by roryabraham** [comment] 2024-04-15 21:29
looks like the PR was CP'd to staging: https://github.com/Expensify/App/pull/40157#issuecomment-2057113421

**Comment by rushatgabhane** [comment] 2024-04-18 16:58
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by trjExpensify** [comment] 2024-04-27 12:39
👋 Let's get the checklist done, @rushatgabhane!

**Comment by rushatgabhane** [comment] 2024-04-28 17:16
All done

**Comment by youssef-lr** [comment] 2024-05-01 00:25
Not overdue.

**Comment by trjExpensify** [comment] 2024-05-01 11:24
>Determine if we should create a regression test for this bug. No

Mind being a little more descriptive on the why here, @rushatgabhane? Is one being added elsewhere for the new "ancestor" thread logic?

**Comment by rushatgabhane** [comment] 2024-05-09 05:46
@trjExpensify i was thinking the root cause is trivial. i.e. we didn't navigate to IOU report when it was deleted. 


In PR https://github.com/Expensify/App/pull/40157, we made that change so this issue won't happen again

**Comment by rushatgabhane** [comment] 2024-05-09 05:49
But yes, if we think that we should add a test, here are the regression steps -


1. Go to the app
2. Go to any chat.
3. Create two IOUs.
4. Go to the transaction thread of the first IOU.
5. Click on the header subtitle to return to IOU report.
6. Right click on the second IOU preview > Delete request.
7. Delete the request.
8. Verify that you are navigated to the other first IOU request.

**Comment by trjExpensify** [comment] 2024-05-09 10:10
>@trjExpensify i was thinking the root cause is trivial. i.e. we didn't navigate to IOU report when it was deleted.
>
>In PR https://github.com/Expensify/App/pull/40157, we made that change so this issue won't happen again

Alright, thanks for expanding on that - I don't think it's trivial if it results in a blank empty page. Looks like we [have a regression test](https://expensify.testrail.io/index.php?/cases/view/2778035&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=295816) for this which includes navigating back as the expected behaviour, so I think we're covered.

**Comment by trjExpensify** [comment] 2024-05-09 10:11
Payment summary as follows: 

- $250 to @rushatgabhane for the C+ review (go ahead and request)
- $250 to @tienifr for the fix (paid)

Closing!

**Closed by trjExpensify** 2024-05-09 10:11 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-12 19:23
$250 approved for @rushatgabhane
