### ISSUE TITLE
Web - Assign Tasks - Inconsistency in Error Message Positioning in Assign Tasks

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25573] opened 2023-08-21 10:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Assign Tasks."
2. Add a title, click "Next," and then click "Confirm Tasks." Notice that the error message is displayed alongside the Confirm Tasks button.

## Expected Result:
The error message "Please select with whom you want to share" should be displayed alongside the "Share Somewhere" section, consistent with other error messages throughout the app.

## Actual Result:
The error message "Please select with whom you want to share" is not displayed alongside the "Share Somewhere" section. It appears alongside the Confirm Tasks button, violating the expected consistency in error message placement.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** @tewodrosGirmaA

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/a29ba28d-5ee1-4e00-8a49-3c3579d2090c

https://github.com/Expensify/App/assets/115492554/caa29323-d612-47e9-b61c-9c9e852424e6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691673973297869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-08-21 11:27
I think it is not a bug, since in others places error message is displayed below input field, but here it is not an input field.

**Comment by johncschuster** [comment] 2023-08-25 21:36
Thanks @alitoshmatov! I'll go ahead and close it.

**Closed by johncschuster** 2023-08-25 21:36 UTC
Labels: Daily, Bug
