### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] One character jumps after cursor when typing fast

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39360] opened 2024-04-01 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711707948520499

## Action Performed:
1. Open any chat
2. Type fast in the composer

## Expected Result:
All the characters added should be before the cursor

## Actual Result:
One character jumps after the cursor.
NOTE: Very hard to reproduce. I had to type 2 lines to reproduce this bug

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/145badbe-8f53-4d7f-bc95-1d3ab9df3641

https://github.com/Expensify/App/assets/38435837/7393245a-684c-4976-8fc9-775e606f69e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109e66f48fc7c7130</li>
        <li>Upwork Job ID: 1775928557129052160</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-04-02 15:03
Added to the tracking issue, going to upgrade this to a high since I can reproduce pretty reliably on Desktop

**Comment by aldo-expensify** [comment] 2024-04-03 19:21
I agree with the cause being what @ZhenjaHorbach found here. In my testing, I put a debugger and I can see that `contentSelection` has the wrong values (36), while it should really have 37 which is the current text length.

<img width="610" alt="image" src="https://github.com/Expensify/App/assets/87341702/f170d496-3150-4a0e-91aa-5f70085bdbe1">

**Comment by thienlnam** [comment] 2024-04-04 16:31
Going to add @shubham1206agra here so he can get compensated here as the reviewer for this bug

**Comment by BartoszGrajdek** [comment] 2024-04-04 17:13
This should be fixed now! 😄

**Comment by kavimuru** [comment] 2024-04-05 16:24
Issue fixed. 

https://github.com/Expensify/App/assets/43996225/378fb6b5-760a-45cd-bded-8b4413a15b11


https://github.com/Expensify/App/assets/43996225/9ec24187-c83b-4f7b-81bb-9b6443ba3029

**Comment by bfitzexpensify** [comment] 2024-04-05 16:24
Great - closing.

**Comment by thienlnam** [comment] 2024-04-05 17:30
@bfitzexpensify Could we get a reviewer payment to @shubham1206agra for this issue?

**Comment by bfitzexpensify** [comment] 2024-04-05 21:29
We can - @shubham1206agra, offer sent

**Comment by c3024** [comment] 2024-04-05 21:37
@thienlnam 

Follow-up issues are being paid separately so can we make a payment issue and finish it for the review of react native live markdown for web?

**Comment by thienlnam** [comment] 2024-04-05 21:47
There's already an existing payment issue for that https://github.com/Expensify/App/issues/37387

**Comment by bfitzexpensify** [comment] 2024-04-16 13:44
@shubham1206agra please accept the Upwork job offer for https://www.upwork.com/jobs/~017cf6471b3178918c - thank you!

**Comment by bfitzexpensify** [comment] 2024-04-17 15:31
Payment complete. Closing this one out.

**Closed by bfitzexpensify** 2024-04-17 15:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
