### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] Workspace - Empty screen when transferring ownership of the workplace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43143] opened 2024-06-05 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4593414&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** applausetester+47pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
As User A:
1. Create a Workspace
2. Ad User B as a member
3. Set User B as Admin
As User B:
4. Go to created workspace
5. Transfer ownership

## Expected Result:
Success screen should be displayed

## Actual Result:
Empty screen appears with no-name button before success screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0021bd58-46b1-4850-8008-c8d77d7b6794

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cbfaae4a7b3b66e</li>
        <li>Upwork Job ID: 1799209224020053309</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102718569</li>
<li>bernhardoj | Contributor | 102718571</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment] 2024-06-05 19:39
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abzokhattab** [comment] 2024-06-05 20:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty screen when transferring ownership of the workplace
### What is the root cause of that problem?
- when clicking on the `Transfer Ownership` button, the app renders the  [WorkspaceOwnerChangeWrapperPage](https://github.com/abzokhattab/App/blob/46c5b5892a5397f17905ff25093a01f29b4149ce/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx) component which then renders the `WorkspaceOwnerChangeCheck`
- inside the `WorkspaceOwnerChangeCheck` component, the `updateDisplayTexts` gets called on the first render. 
- the problem arises in this line https://github.com/Expensify/App/blob/46c5b5892a5397f17905ff25093a01f29b4149ce/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L45-L47 where it checks if the `error` prop not equal to the policy error field
- in this case the `error` is `amountOwed` and the `changeOwnerErrors[0]` is `NoBillCard` so the function just returns causing the screen to be empty 

- also upon clicking on the empty button an error is returned from the backend stating that the current user doesn't have a billing card, so the correct behavior here is to show the card fill form 

https://github.com/Expensify/App/assets/59809993/f91f4164-bb2e-49c5-9c4f-ebd4028fa5d4


### What changes do you think we should make in order to solve the problem?

we should check if the policy error returned from the backend is nobill then render `WorkspaceOwnerPaymentCardForm`, to achieve that we need to declare these vars in the   [WorkspaceOwnerChangeWrapperPage](https://github.com/abzokhattab/App/blob/46c5b5892a5397f17905ff25093a01f29b4149ce/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx) component

```js

    const changeOwnerErrors = Object.keys(policy?.errorFields?.changeOwner ?? {});
    const isBillingCardError = changeOwnerErrors && changeOwnerErrors.length > 0 && changeOwnerErrors[0] === CONST.POLICY.OWNERSHIP_ERRORS.NO_BILLING_CARD;

```

then change [this](https://github.com/Expensify/App/blob/46c5b5892a5397f17905ff25093a01f29b4149ce/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L73) to:

```js
(error === CONST.POLICY.OWNERSHIP_ERRORS.NO_BILLING_CARD || isBillingCardError ? (
```


### POC 

https://github.com/Expensify/App/assets/59809993/d40cf9c4-769c-4446-9577-0d0d97511faa

**Comment by bernhardoj** [comment] 2024-06-06 04:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank view when going to transfer ownership page.

### What is the root cause of that problem?
When we press transfer owner, it will request a check and navigate to the check page with a default error param of `amountOwed`.
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L131-L134

After the check is done, it will check whether the error param passed to the page is the same as the error from the check that we request before.
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L44-L51

If it's not the same, we don't display anything, but if it's the same, we will display the text to explain the error.

In our case, I get a `noBillingCard` error, but it can be repro happen with any error (except `amountOwed` because this is the default value that we pass as the error). Because `noBillingCard` is not the same as `amountOwed`, nothing is displayed.

However, the app is supposed to update the error params when the check is done (in a useEffect). There is currently 2 places that do this. One in the check page itself, 
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L51-L54

and the other one is in the member details page.
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L94-L97

_This dupe logic can be cleaned up._

However, a recent change from https://github.com/Expensify/App/pull/42335 doesn't allow to perform a navigate to the same screen even if the params is different (in our case the error param).
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/libs/Navigation/linkTo/index.ts#L180-L183

So, the error param is never updated.

### What changes do you think we should make in order to solve the problem?

First of all, I'd to suggest a cleanup to the dupe error check logic. First, remove the exception of no billing card error here, we want to update any error we got
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceOwnerChangeWrapperPage.tsx#L51-L53

Why the exception is there in the first place? I believe that's because initially, no billing card has a separate page to show the error. In this [commit](https://github.com/bernhardoj/Expensify/commit/688ae7cc9da677871a415d80b4c9a76308b4b091#diff-77d95fb89b7456e2a952802101e5684a74ccebd2ac3a3ea7f162125be861a7bb), you can see that when we press transfer owner, it won't immediately navigate us to the owner change check page. Instead, it will wait for the request to done first and if it's error, it checks whether it's a no billing card error or other errors. If it's no billing card error, it will navigate to no billing card error page, otherwise it will go to WORKSPACE_OWNER_CHANGE_CHECK, which is the page that we use now for all errors.

Then, we can remove the one from the member detail page.
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L87-L97

Now, the real solution to the issue is that we need to allow to navigate to the same screen if the params are different. We can follow a similar check as we already have here.
https://github.com/Expensify/App/blob/198b47360fa6fa5bfbb81f3fb535a2fa6817e375/src/libs/Navigation/linkTo/index.ts#L75-L81

```
if (currentFocusedRoute?.name === targetFocusedRoute?.name && shallowCompare(currentFocusedRoute?.params, targetFocusedRoute?.params)) {
    return;
}
```

**Comment by eh2077** [comment] 2024-06-10 10:06
Reviewing proposals

**Comment by eh2077** [comment] 2024-06-10 14:36
This isn’t a bug with straightforward root cause and fix - it's related to subtle navigation feature and function. So, I'll need to take more time to understand the root cause.

**Comment by eh2077** [comment] 2024-06-12 16:12
I'll prioritise this tmr.

**Comment by eh2077** [comment] 2024-06-13 09:37
I think @bernhardoj 's [RCA](https://github.com/Expensify/App/issues/43143#issuecomment-2151384798) is correct and their solution to include route parameters check for SideModalNavigator also makes sense to me.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-06-13 11:47
PR is ready

cc: @eh2077

**Comment by johncschuster** [comment] 2024-06-24 15:02
@eh2077 can you address the BZ Checklist please? Thank you!

**Comment by johncschuster** [comment] 2024-06-24 15:05
I have issued payment. We're just waiting on the completion of the BZ Checklist.

**Comment by johncschuster** [comment] 2024-06-25 14:56
@eh2077 bump on this. Can you complete the BZ Checklist so we can button this one up? Thank you!

**Comment by eh2077** [comment] 2024-06-26 14:23
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42335
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42335/files#r1654967043
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes
- [x] [@eh2077] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

#### Regression test

1. Open workspace where you are admin
2. Press the owner to open the detail page
3. Press Transfer owner
4. Verify after loading, a non empty screen is shown

Do we agree 👍 or 👎

cc @johncschuster

**Comment by johncschuster** [comment] 2024-06-26 15:13
Thanks for completing that, @eh2077!

**Closed by johncschuster** 2024-06-26 15:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
