### ISSUE TITLE
[$250] [HOLD for payment 2024-10-17] Report actions pagination improvements

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#41153] opened 2024-04-27 18:20 UTC
## Problem

We currently have an issue where pagination methods (`GetNewerActions`, `GetOlderActions`) are called unconditionally even if we should know that no newer or older messages are available.

## Solution

To improve this `OpenReport`, `GetNewerActions`, `GetOlderActions` should all return pagination info. This should be stored in the `REPORT_METADATA` onyx collection.

- For `OpenReport` it should be `hasNewerActions` and `hasOlderActions`.
- For `GetNewerActions` it should be `hasNewerActions`.
- For `GetOlderActions` it should be `hasOlderActions`.

Then in `loadNewerChats` and `loadOlderChats` we should check that newer / older actions are available before loading them.

This will reduce the call to these methods significantly. For regular chats we never should have newer actions since we start loading from the start of the chat so `GetNewerActions` will never be called. If we are in a short chat, we probably loaded all messages initially so we don't need to call `GetOlderActions`. For comment linking we should still call both `GetNewerActions` and `GetOlderActions` since we are probably in the middle of a chat.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845841739039769728</li>
        <li>Upwork Job ID: 1845841739039769728</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by roryabraham** [comment] 2024-08-27 07:45
put a PR in review for this: https://github.com/Expensify/Auth/pull/12239

**Comment by janicduplessis** [comment] 2024-08-28 18:38
@roryabraham Awesome, let me know when this is merged I could work on the app integration.

**Comment by roryabraham** [comment] 2024-08-28 19:07
It's merged, should be deployed within the next 2-3 hours. I'll let you know

**Comment by roryabraham** [comment] 2024-08-28 19:09
FWIW, I made the following changes:

1. `GetOlderActions` includes a `hasOlderActions` key in the response
1. `GetNewerActions` includes a `hasNewerActions` key in the response
1. If called with an "anchor" reportActionID, `OpenReport` includes both `hasOlderActions` and `hasNewerActions`

I'll test this locally and make sure it's working. Might need to make some changes in our "middle" PHP layer to make sure the data makes it to the front-end in the response.

**Comment by roryabraham** [comment] 2024-08-28 20:21
For `GetOlderActions` and `GetNewerActions` it's an easy change. For `OpenReport`, not so much because there's a lot happening in the PHP layer and I might need to refactor some PHP functions that are used in many locations.

Alternatively, I can try to refactor `OpenReport` to be what we call 1:1:1 (or 1 user action = 1 php API call = 1 C++ Auth/DB command). That would likely take me several days. Will probably chat internally about the best path forward

**Comment by janicduplessis** [comment] 2024-08-28 20:26
> If called with an "anchor" reportActionID, OpenReport includes both hasOlderActions and hasNewerActions

I think `OpenReport` should always include `hasOlderActions` even with no anchor since for a small chat there might be no older messages to load initially.

**Comment by roryabraham** [comment] 2024-08-28 23:37
Good point, I'll work on adjusting that, as soon as I figure out what to do with the OpenReport

**Comment by roryabraham** [comment] 2024-09-02 17:25
I've spent a _lot_ of time working on this. I do just need a single PHP PR, but it involves ripping out some deprecated code that has a lot of hidden side-effects. So it's been much more challenging than it seemed like it should have been.

At this point I have only one failing test that I'm trying to wrap my head around

**Comment by roryabraham** [comment] 2024-09-13 05:00
Still stuck on that PR, but have been driving myself crazy trying to figure it out. Pushed a few changes that I think are sound, but still haven't gotten the last test passing.

**Comment by roryabraham** [comment] 2024-09-13 06:02
Finally got this PR passing. That was painful, but it's ready for review

**Comment by roryabraham** [comment] 2024-09-16 21:25
ok, the PHP PR is merged. Just waiting for it to deploy. I missed the deploy today so most likely it will hit prod on Wednesday

**Comment by roryabraham** [comment] 2024-09-19 18:49
@janicduplessis you can go ahead and work on the app part if you've got the bandwidth

**Comment by janicduplessis** [comment] 2024-09-24 16:46
I will work on this this week.

**Comment by janicduplessis** [comment] 2024-09-30 19:15
@roryabraham Should we make the name more generic so it could apply to other pagination actions in the future. Since I am reading these values in the Pagination middleware it could eventually apply to other things.

I was thinking `hasNextPage` or `hasOlderData`.

**Comment by janicduplessis** [comment] 2024-09-30 21:38
I have a draft ready https://github.com/Expensify/App/pull/49958, lmk if that looks good. Just need to do some more testing and complete checklist. Also waiting to see if we want to change the name of the fields.

**Comment by roryabraham** [comment] 2024-10-01 00:08
Actually @janicduplessis let's just proceed with `hasOlderActions` and `hasNewerActions` for now. I agree `hasNextPage` and `hasPreviousPage` would've been smart, but for now report pagination is on HOLD and I have limited time before my parental leave starts on 2024-10-11. So let's just try to get this done and in the future when we pick up report pagination we can rename the flags.

Thanks!

**Comment by roryabraham** [comment] 2024-10-04 23:36
@rlinoz pulling you in because I tagged you for review in the PR

**Comment by CortneyOfstad** [comment] 2024-10-14 15:05
@ishpaul777 — sent you an offer in Upwork, please let me know once you accept!

**Comment by CortneyOfstad** [comment] 2024-10-15 19:38
I am heading OoO (10/15 to 10/23), so going to get this reassigned so the payment can be made!

**Comment by lschurr** [comment] 2024-10-15 21:44
Payment summary:

- Contributor: @janicduplessis (no payment needed)
- Reviewer: $250 @ishpaul777 (paid in [Upwork](https://www.upwork.com/nx/wm/workroom/38707068/overview))

**Comment by lschurr** [comment] 2024-10-15 21:44
Oops I read the date wrong and paid it today. We'll just leave this open to make sure there are no regressions.

**Comment by lschurr** [comment] 2024-10-17 16:38
Closing :)

**Closed by lschurr** 2024-10-17 16:38 UTC
Labels: External, Daily, Improvement, Awaiting Payment, Bug
