### ISSUE TITLE
CRITICAL: LHN for workspace chat shows `No activity` even though the default welcome message is visible after clicking into the chat.

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#26734] opened 2023-09-04 23:50 UTC
Bug: LHN for workspace chat shows No activity even though the default welcome message is seeded and visible after clicking into the chat.

![Screenshot 2023-09-04 at 17 39 42](https://github.com/Expensify/App/assets/60117248/f273e365-7564-4dcc-82cd-280799ffb1d7)
![Screenshot 2023-09-04 at 17 40 30](https://github.com/Expensify/App/assets/60117248/0de2f9b7-947b-4c43-bff3-e528df0b0dd1)

**Comment by AmjedNazzal** [comment] 2023-09-05 09:40
@dylanexpensify is this what the bug is about? because if so it's reproducible on all platforms it seem.

<img width="1280" alt="bugnew" src="https://github.com/Expensify/App/assets/74202751/eb0ab2b9-89e2-4a04-9b3c-08c5760c4b3f">

**Comment by trjExpensify** [comment] 2023-09-05 10:12
It's not. :) You need to sign up using the staging.new.expensify.com/saastr route to see the welcome message in the OP. It doesn't seem to be appearing in the LHN preview on Android, and that's the issue.

**Comment by cristipaval** [comment] 2023-09-05 16:22
I think I found the root cause. It is from Auth and has an impact on a big query that I wouldn't change in a rush. Opening a PR and asking for more eyes to look at it.

**Comment by cristipaval** [comment] 2023-09-06 07:17
The fix is now in prod. Closing this.

**Closed by cristipaval** 2023-09-06 07:17 UTC
Labels: Daily, Task, Bug
