### ISSUE TITLE
LHN - #announce room and that workspace policy chat didn't get archived after Delete the Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12029] opened 2022-10-20 01:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
- 2 accounts are needed for the following tests, 1 Admin and 1 user
- With one of the accounts, log in, create a workspace and invite the other account to the workspace. We will refer to the invitee as the employee.
- Send a message in the all the workspace rooms (#announce and #admins) and in each workspace's chats.

1. Log in with the same workspace admin account on the main device and the employee in the secondary device
2. Navigate to a Workspace settings
3. Disable the internet connection in the device
4. Delete the workspace by click/tap on the 3 dots > Delete workspace

## Expected Result:
The employee lost access to the #announce room and that their workspace policy chat got archived.

## Actual Result:
#announce room and that workspace policy chat didn't get archived after delete the Workspace

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+101321@applause.expensifail.com
, applausetester+31622@applause.expensifail.com/Qwerty123

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196837612-a466489f-f8bc-43b5-93be-435b64b57084.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2022-10-20 21:07
@kbecciv quick clarification. For steps 2-4 are taken from the admin account, correct? 

And for the expected result

> The employee lost access to the #announce room and that their workspace policy chat got archived.

**Comment by kbecciv** [comment] 2022-10-22 18:39
@NikkiWines Yes, correct steps 2-4 are taken from admin account.
Expected results in Secondary device (Employee):
Verify that the employee lost access to the #announce room and that their workspace policy chat got archived.

Sending you TR link if its easy to follow the steps https://expensify.testrail.io/index.php?/tests/view/2894431.

**Comment by NikkiWines** [comment] 2022-10-24 08:34
@kbecciv I think the `Secondary device - Employee` steps are in TR a bit unclear. 

We cannot expect the employee to lose access to the #announce room while the admin is offline because the admin's actions won't be recorded on the server until they come back online. The tests for `Secondary device - Employee` should be performed once the admin is online.

**Comment by mvtglobally** [comment] 2022-10-24 18:41
Issue not reproducible during KI retests. (First week)

**Comment by NikkiWines** [comment] 2022-10-25 11:34
@kbecciv I don't think this is actually a bug. Closing.

**Closed by NikkiWines** 2022-10-25 11:34 UTC
Labels: Engineering, Daily
