### ISSUE TITLE
Room - When entering a "Space" while writing Room name "-" is not added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30500] opened 2023-10-27 11:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to NewDot with a High traffic account that owns a existing Workspace
2. Click on the green + button
3. Click on the "Send Message" option
4. Click the tab 'Room'
5. Type some text and hit "Space"

## Expected Result:
When entering the room name, entering a "Space" adds a "-" to the name

## Actual Result:
When entering a "Space" while writing Room name "-" is not added

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/486e28c9-14db-4dae-af65-ffa07aa4f7ce

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2023-10-27 12:28
@kowczarz would you be able to take a look at this?

**Comment by blazejkustra** [comment] 2023-10-27 12:47
Kamil is OOO, I'm on it @puneetlath 😄

**Comment by puneetlath** [comment] 2023-10-27 13:34
@BhuvaneshPatil we can make this a $250 job. If you're good with that, please share your proposal.

**Comment by puneetlath** [comment] 2023-10-27 13:48
Ah interesting. If it created that many regressions then I agree it's better to revert.

**Comment by blazejkustra** [comment] 2023-10-27 13:49
@puneetlath I agree, let's revert and Kamil will be able to fix these once he is back.

**Comment by luacmartins** [comment] 2023-10-27 18:13
We're reverting the offending PR

**Comment by luacmartins** [comment] 2023-10-27 18:59
We can close this PR since we're CPing the revert

**Closed** 2023-10-27 18:59 UTC
Labels: DeployBlockerCash, Engineering, Hourly
