### ISSUE TITLE
Web- Send money - Pay with expensify Popover is positioned in correctly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21868] opened 2023-06-29 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. Click on FAB button 
3. Send money -> Change currency to USD -> Enter amount -> Choose the user
4. Click pay with expensify button

## Expected Result: 
Popover should be placed correctly
## Actual Result: 
There is big space between Popover and the pay with expensify button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7b7ef924-f6a8-4e0b-bfed-7cfb7ef37b69

<img width="1440" alt="Screen Shot 2023-06-29 at 9 13 17 AM" src="https://github.com/Expensify/App/assets/43996225/5e2bc253-3e34-41d4-854d-a6cfc3ae5c9c">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Doston Gulmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686809386838619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-29 13:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web- Send money - Pay with expensify Popover is positioned in correctly

### What is the root cause of that problem?
We are not passing `anchorAlignment` prop to `PopoverMenu` here
https://github.com/Expensify/App/blob/b8aeec0bcf2cac06d51129f287f932ba0421ed4e/src/components/AddPaymentMethodMenu.js#L48-L53
### What changes do you think we should make in order to solve the problem?
We should pass `anchorAlignment` prop here
```javascript
anchorAlignment={{
                        horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
                        vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
                    }}
``` 
https://github.com/Expensify/App/blob/ef52c5da96ceaaca8e023a6bc7459be967dd0d19/src/components/KYCWall/BaseKYCWall.js#L135-L140

and recieve and pass it to `PopoverMenu` here in `AddPaymentMenu`

https://github.com/Expensify/App/blob/b8aeec0bcf2cac06d51129f287f932ba0421ed4e/src/components/AddPaymentMethodMenu.js#L48-L53

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-06-29 14:01
dupe of https://github.com/Expensify/App/issues/21259

**Comment by CortneyOfstad** [comment] 2023-06-29 14:11
Closing this in favor of the other GH. 

Thanks @Pujan92!

**Closed by CortneyOfstad** 2023-06-29 14:11 UTC
Labels: Daily, Bug
