### ISSUE TITLE
Invite - Search field is highlighted when leaving some spaces and clicking on any existing username below

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24398] opened 2023-08-10 23:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Go to settings > Workspaces > Any Workspace > Members > Click on Invite btn
3. Leave some spaces and click on any existing username below

## Expected Result:
Search field shouldn't be highlighted when leaving some spaces and clicking on any existing username below

## Actual Result:
 Search field is highlighted when leaving some spaces and clicking on any existing username below

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (79).webm](https://github.com/Expensify/App/assets/78819774/627be10c-9fd9-416a-be98-da969e0f86a4)

https://github.com/Expensify/App/assets/43996225/e7c49763-a159-4f32-a345-1897be95f894

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691059261001279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment] 2023-08-11 02:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invite - Search field is highlighted when leaving some spaces and clicking on any existing username below

### What is the root cause of that problem?
Selecting of option in `OptionsSelector` component automatically focuses `TextInput` and it selects all text in `TextInput`.

### What changes do you think we should make in order to solve the problem?
If `this.props.value.trim()` is empty, clear `TextInput` by calling `this.props.onChangeText('')` in OptionsSelector's [selectRow](https://github.com/Expensify/App/blob/c08d5887b18914d95e64e925bfed290fecfffc94/src/components/OptionsSelector/BaseOptionsSelector.js#L279-L302) method

### What alternative solutions did you explore? (Optional)
N/A

**Comment by daordonez11** [comment] 2023-08-11 15:06
This does not feel like an error, if you are searching and you found the person you were looking for you could do the next search and easily clean the "search" text. This seems like the desired behavior of OptionsSelector

**Comment by JmillsExpensify** [comment] 2023-08-16 13:41
Agree, I don't think this is a bug. Closing.

**Closed by JmillsExpensify** 2023-08-16 13:41 UTC
Labels: Daily, Overdue, Bug
