### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Dev:  Web - Can't click plus button after leaving a room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23881] opened 2023-07-30 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account.
2. Create a new room.
3. Leave the room.
4. Click on plus button

## Expected Result:
User can click plus button and it works as expected (show the context menu).

## Actual Result:
 User can't click plus button after leaving a room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.47-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4cebf5d1-6e04-4cf2-828c-151a6a68813a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690682725357069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017df576fd65e43186</li>
        <li>Upwork Job ID: 1686101709086126080</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-07-30 19:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
this is a regression from: https://github.com/Expensify/App/pull/23528
the `NoDropZone` component, has a full screen width and prevents any events from passing to the LHN.

it will be rendered together based on the routes here:

https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/ThreePaneView.js#L34

When we click leave room and navigate to concierge the navigation route will be present, it will just push another new page without removing the Right modal navigator. hence the descriptor will be rendered inside `NoDropZone` 
### What changes do you think we should make in order to solve the problem?

To ensure that the NoDropZone component is not rendered when navigating to concierge, we should close the Right Modal Navigator before leaving. This is because the NoDropZone component only exists within the routes of the Right Modal Navigator. for example: we can just use Navigation.goBack just before leaveRoom.
### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-07-30 19:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Can't click plus button after leaving a room
### What is the root cause of that problem?

I think this is the regression coming from this PR -> #23528.

> It also happens for threads as well, if we leave a thread we can't click anything on LHN menu.

Here we have implemented NoDrop component for RHN, but due the fact we're navigating inside the RHN when deleting a Thread/Room we're just navigating to the `CONCIERGE` screen here https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/libs/actions/Report.js#L1247 and here as well https://github.com/Expensify/App/blob/513fed987c8b6249ab3cc0d8d9c133eb4b3dcfa8/src/pages/ReportDetailsPage.js#L121.

If we observe the Navigation state we're still having the RHN in the navigation state even though we've been out of the RHN screens and the code here rendering `NoDropZone` https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/ThreePaneView.js#L55 component to the RHN assuming it's still no closed.

### What changes do you think we should make in order to solve the problem?
I feel if it's the last screen in RHN we should remove the navigation state from RHN.
For this current issue we can update the function here
https://github.com/Expensify/App/blob/24ed1bebf19539d27878ed419f7cc10ae942531f/src/libs/actions/Report.js#L1247
to dismiss the modal before navigating any further to `CONCIERGE` report.


### What alternative solutions did you explore? (Optional)
NA

**Comment by Beamanator** [comment] 2023-07-31 11:59
I couldn't reproduce this exact issue, so closing

**Comment by getusha** [comment] 2023-07-31 12:00
@Beamanator it's reproducible on `main` only.

**Comment by Beamanator** [comment] 2023-07-31 12:09
Good call y'all, sorry i got too excited to close this out

**Comment by Beamanator** [comment] 2023-07-31 12:12
Def reproducible in main :D

**Comment by Beamanator** [comment] 2023-07-31 12:20
This was fixed by @allroundexperts in https://github.com/Expensify/App/pull/23856 - the PR also fixed https://github.com/Expensify/App/issues/23885

**Comment by Beamanator** [comment] 2023-07-31 12:21
Won't close till fix is on prod & payment is complete

**Comment by joekaufmanexpensify** [comment] 2023-07-31 19:48
Sounds good, thanks for clarifying @allroundexperts! In that case, the only payment we'd need to issue here is a reporting bonus to @hungvu193.

**Comment by joekaufmanexpensify** [comment] 2023-07-31 19:49
Adding external label to create upwork job.

**Comment by joekaufmanexpensify** [comment] 2023-07-31 19:53
@hungvu193 offer sent for $250!

**Comment by gadhiyamanan** [comment] 2023-08-01 18:33
@joekaufmanexpensify i think this is not eligible for reporting bonus as this issue has same rca with https://github.com/Expensify/App/issues/23881and othe issue was reported first in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690610169591779)

**Comment by joekaufmanexpensify** [comment] 2023-08-01 20:47
@Beamanator @allroundexperts It does look to me the PR here would probably fix the other issue too (which was reported first), but curious if y'all agree?

**Comment by Beamanator** [comment] 2023-08-02 08:33
Assigning @allroundexperts since they completed this job 👍 (no C+ reviewer)

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:07
@Beamanator / @allroundexperts mind completing your portion of the BZ checklist here when you have a sec?

**Comment by Beamanator** [comment] 2023-08-09 07:35
@allroundexperts mind taking care of the checklist here? 🙏

**Comment by joekaufmanexpensify** [comment] 2023-08-11 13:08
Thanks! BZ checklist is complete.

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:01
Of course!

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:02
@gadhiyamanan offer sent for $250!

**Comment by gadhiyamanan** [comment] 2023-08-11 14:03
@joekaufmanexpensify offer accepted, thanks

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:05
@hungvu193 contract ended with no payment!

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:05
@gadhiyamanan $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:06
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-08-11 14:07
Reporting was the [only payment needed here](https://github.com/Expensify/App/issues/23881#issuecomment-1658272618). So this is now all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-08-11 14:07 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
