### ISSUE TITLE
Web - Inconsistent downloading animation

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25671] opened 2023-08-22 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any non previewable attachment like .zip
4. Hover and click on download besides attachment name
5. Observe downloading animation and tooltip text, it displays as loading as tooltip is changed to 'Downloading'
6. Now hover on attachment and click on download besides 'Add reaction'
7. Observe that for animation, it only changes color of download button to green and does not change tooltip to 'Downloading'

## Expected Result:
App should either change download icon color to green at both the locations or change it to loading and also change tooltip temporarily to downloading at both the locations of download icon

## Actual Result:
App keeps loading animation with 'Downloading' tooltip for download icon besides attachment name and color change to green and 'Download' icon besides 'Add reaction'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/27be7611-d9b5-41e3-b7db-077325c11b68

https://github.com/Expensify/App/assets/115492554/0017cb78-9855-4ec0-8018-ee486c29460c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691854798230569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-08-22 13:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistent downloading animation

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/494847af90210ae11fcae19abe692f7444f4bbb2/src/components/ContextMenuItem.js#L68-L72

When clicking the download button, triggerPressAndUpdateSuccess function will be triggered. And then, the success icon and successText are displayed while downloading

### What changes do you think we should make in order to solve the problem?
We should update the success icon is loading icon and successText is loading for consistency

### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-08-22 15:23
I think we can close this, these aren't the same pieces of UI so I don't think we have to be ultra strict on them having the exact same behavior. I don't know that there is enough space in the mini menu to add a loading spinner either. I say we close this.

**Comment by joekaufmanexpensify** [comment] 2023-08-22 15:30
Closing as no action needed here!

**Closed by joekaufmanexpensify** 2023-08-22 15:30 UTC
Labels: Daily, Bug
