### ISSUE TITLE
IOU - Pay button is visible for a moment after cancel requested amount.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12781] opened 2022-11-16 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12488

## Action Performed:
1. Launch the app
2. Log in with any account
3. Send a money request in USD while being online, e.g. $100.
4. Send a second money request in a different currency, e.g. 100 AED.
5. Go offline, cancel the request in USD
6. Go online.
7. Cancel the request in AED

## Expected Result:
Pay button is not visible for a moment after cancel requested amount.

## Actual Result:
Pay button is visible for a moment after cancel requested amount.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.28.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202238511-64437469-d74d-475e-9f69-326382ffeb6c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2022-11-17 03:21
Though cc @youssef-lr as you're in the linked PR this stemmed from.

**Comment by youssef-lr** [comment] 2022-11-17 15:09
Thanks for the ping @sophiepintoraetz - I've reverted my PR locally and I can still reproduce this, so I don't think this is a regression bug, but just something we didn't notice before. The steps to reproduce this is simply to request money while online using a different currency than the report's, then cancel the request. I may have a fix for this one, looking into it today.

**Comment by youssef-lr** [comment] 2022-11-17 15:34
I think we may need to cancel updating the IOU if the IOU's currency is different than the report's currency all together, regardless of whether or not the user is offline. 

The issue here is that say we request 100 MAD from a user, and the default report's currency is USD, that's about $11. If we cancel the 100 MAD, in the code this amount is not converted to USD, so we're subtracting 100 from 11 which becomes -$89, then the IOU manager/owner is switched here and we see the "Pay" button. Until new data comes from the backend and the IOU gets updated properly.

Since this is affecting only the online behavior, where we will always have data coming back from the backend, I'd say we can cancel making updates to the IOU locally and rely on the backend only. @JmillsExpensify what do you think?

**Comment by JmillsExpensify** [comment] 2022-11-17 17:03
Gotcha, so I think what we're essentially discovering here is that we can't reliably `Cancel` in scenarios where an IOU has multiple currencies – just like we recently discovered for `Pay`. The pickle with the "Pay" is that it's possible to accidentally pay something for an amount you didn't expect. That said, a couple of questions:

 - Isn't `Cancel` only an issue when both currencies were added online, but then one of them is canceled offline? If that's the case, I think it's the same issue as `Pay` and we should just require you to be online for the Pay button to be enabled. That gives the IOU the chance to update using the correct amounts, and thus total. So you know what you're paying. 

 - Related, if you `Cancel` offline, I thought we already agreed that if an IOU has multiple currencies that the total would not be updated offline? So maybe I'm missing why `Cancel` should also be disabled while offline?

P.S. We looked into storing currencies in the App briefly and there was a huge performance it, so I tend to agree that it's not a realistic solution for now.

**Comment by youssef-lr** [comment] 2022-11-17 17:25
Here's a recording of the bug:

https://user-images.githubusercontent.com/9680864/202515139-1d188c8a-7723-4172-839a-46ed24b58dbf.mov

**Comment by trjExpensify** [comment] 2022-11-17 17:27
I'm kind of confused. The steps in the OP are not the same as the steps in the video. Here's the flow following the video:

1. Launch the app 
2. Log in with any account 
3. Send a money request in USD while being online, e.g. $100. (no prior balance owed between either parties on the report)
4. Go offline 
5. Send a second money request in a different currency, e.g. 100 AED. (The report total doesn't update and shows pending) - ✅ correct
6. Go online, the report total updates with the value of the second request (e.g $127.23 is owed by the other user) - ✅ correct
7. Go offline again 
8. Cancel the $100 request in USD. The report total updates and shows pending. (e.g $27.23 is owed by the other user) - ✅ correct 
9. Go online again, the report total remains as $27.23 owed by the other user - ✅ correct
10. Cancel the 100 AED request online
11. The report total briefly shows you now owe $72.77 with the Pay button  - ❌ incorrect
12. Then updates (well, reverts?) to $27.23 owed   - ❌ incorrect
12. Then $0 and the report preview is removed as the balance is equal again. - ✅ correct

So the question I have is what is happening to make the report total go from $27.23 to $72.77 when cancelling a request online? Before reverting back to $27.23, before cancelling it to bring the report total to `$0`.

**Comment by youssef-lr** [comment] 2022-11-17 17:31
> The report total briefly shows you now owe $72.77 with the Pay button - ❌ incorrect

That's the code in the client (incorrectly) subtracting 100 AED from $27.23 = -$72.77

> Then updates (well, reverts?) to $27.23 owed - ❌ incorrect

Not sure what's happening here either. I didn't see this in my testing.

> Then $0 and the report preview is removed as the balance is equal again. - ✅ correct

Correct data was fetched from the backend.

**Comment by trjExpensify** [comment] 2022-11-17 17:34
>That's the code in the client (incorrectly) subtracting 100 AED from $27.23 = -$72.77

Why is it doing that? That must be a regression we introduced somewhere? 

Do we agree, this is the expectation? 

- report is $0 with 0 expenses
- userA adds $100, report total is $100 with 1 expense
- userA adds 100 AED, report total is $127.23 with 2 expenses
- userA cancels $100, report total is $27.23 with 1 expense
- userA cancels 100 AED, report total is $0 with 0 expenses

**Comment by JmillsExpensify** [comment] 2022-11-17 17:37
Can we bring this discussion to Slack instead please.

**Comment by JmillsExpensify** [comment] 2022-11-17 17:37
Let's create a thread in open source.

**Comment by sophiepintoraetz** [comment] 2022-11-21 02:44
Pulled out[ here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668998655170269)

**Comment by techievivek** [comment] 2022-11-23 08:23
I was ooo catching up now. Thanks

**Comment by techievivek** [comment] 2022-11-28 08:20
This issue seems to be solved by the PR https://github.com/Expensify/App/pull/12960
@youssef-lr Can you confirm it? So I guess we can focus on displaying the `calculating` state wherever required.

**Comment by youssef-lr** [comment] 2022-11-29 02:06
@techievivek Correct, this has been fixed and I think we can close this out and create an issue to work on the design and copy of the pending/calculating state.

**Comment by sophiepintoraetz** [comment] 2022-11-29 04:09
Happy to close this one out and open up a design ticket - just point me in the right direction - which part are we thinking about showing a loading screen? We kind of already do (when looking back on the video)
<img width="275" alt="image" src="https://user-images.githubusercontent.com/42940078/204436614-fcf1c661-eed1-4777-9cfa-5cc936b28ceb.png">

**Comment by techievivek** [comment] 2022-11-29 05:06
@sophiepintoraetz The screenshot that you have shared is when the user is offline. 
This one would be when we added a new IOU request where the currency is different from the report's currency in that case we wait for the response from the backend. And during this period of waiting, we would like to show a calculating state.

**Comment by techievivek** [comment] 2022-11-29 08:40
Closing this issue as I have created a [new issue](https://github.com/Expensify/Expensify/issues/245284) to add the calculating state for IOU requests.

**Closed by techievivek** 2022-11-29 08:40 UTC
Labels: Engineering, Daily, Bug
