### ISSUE TITLE
[$1000] Secret key disappears in the Two-factor authentication (2FA) page when the window is resized.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21407] opened 2023-06-23 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Visited the website.
2. Navigated to the Two-factor authentication page.
3. Resized the browser window.
4. Observed that the 2FA Secret key disappears.
## Expected Result: 
The 2FA key should remain visible even after resizing the window.
## Actual Result:
 The Secret key disappears in the 2FA page when the window is resized.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8d9f79fe-13a5-4fae-9ea1-1da06c98b260

https://github.com/Expensify/App/assets/43996225/25c922e7-b596-4594-87a8-125e311c43e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686992771771289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014371df527f0b8811</li>
        <li>Upwork Job ID: 1673225685809156096</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by nitin-kukreti** [comment] 2023-06-23 20:09
### Proposal
---
### Please re-state the problem that we are trying to solve in this issue.

Secret key disappears in the Two-factor authentication (2FA) page when the window is resized.

### What is the root cause of that problem?
The main cause of this problem is that we are doing clean up of 2-Factor code which is not required as I will regenrated new each time they called.

when we resize screen this code will be called? which is not required as it does not require clean up
```
 useEffect(() => {
        return () => {
            TwoFactorAuthActions.clearTwoFactorAuthData();
        };
    }, []);


```
### What changes do you think we should make in order to solve the problem?

Just remove clean up code it will automatically managed
```
 useEffect(() => {
        return () => {
          
        };
    }, []);

```
### Before  Change


[Screencast from 24-06-23 01:34:58 AM IST.webm](https://github.com/Expensify/App/assets/59364817/9743f55f-ae0b-474b-8bfa-2b91bafa3002)

### After Change
[Screencast from 24-06-23 01:37:25 AM IST.webm](https://github.com/Expensify/App/assets/59364817/25d95a6f-02cb-4ed2-8b84-c0c9d54c7507)

**Comment by nitin-kukreti** [comment] 2023-06-24 03:15
Contributor details Your Expensify account email: nitinkukreti12@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~01cab64261c95a66c5

**Comment by nitin-kukreti** [comment] 2023-06-25 08:49
Is it open ?

**Comment by nitin-kukreti** [comment] 2023-06-25 09:37
Is it open ?

**Comment by bfitzexpensify** [comment] 2023-06-26 07:04
Reproduced and moved to `External`

**Comment by bfitzexpensify** [comment] 2023-06-26 09:11
You're right @dukenv0307 - let's close this out.

**Closed by bfitzexpensify** 2023-06-26 09:11 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by Marvineekina23** [comment] 2023-06-27 09:09
4

**Comment by Marvineekina23** [comment] 2023-06-27 10:59
Your Expensify account ***@***.***


Upwork Profile Link:https://www.upwork.com/freelancers/~01a8f42304bb2cda47

**Comment by nitin-kukreti** [comment] 2023-06-28 16:28
@bfitzexpensify  when you have decided to not solve this issue then why  @kavimuru positing same issue with different name  #20611

**Comment by esh-g** [comment] 2023-06-28 16:34
@nitin-kukreti Please understand that kavimuru is just testing the bug reports from the slack channel (which you should be a part of to be a contributor) and the issue is originally reported by the reporter mentioned in the first comment of the issue. As a new contributor, please make sure you have read all the contributing guidelines and good luck with contributing!

**Comment by nitin-kukreti** [comment] 2023-06-28 16:50
@esh-g thank so much for information I thought It was intentional.

**Comment by bfitzexpensify** [comment] 2023-06-29 05:35
Thanks @esh-g.

@nitin-kukreti, if the same issue is reported twice (which has happened in this case) we close the later report since we otherwise we will be duplicating work. We still want to fix the problem, but want to keep the conversation and fix to one issue. If you would like to make a proposal to fix this, you can do so over on https://github.com/Expensify/App/issues/20611
