### ISSUE TITLE
[$16000] No "Paste" option is shown after copying to devices native clipboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10263] opened 2022-08-05 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: User has "Copied" an image to the iOS devices native clipboard
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Proceed to any chat
4. Attempt to "Paste" the copied image into the chat box

## Expected Result:
The user expects a "Paste' option to show along with the "Scan Text" option.

## Actual Result:
Only the "Scan Text" option is shown, therefore the user can not paste the copied image.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183102926-287c0d9a-9f35-4a2a-bf2d-dcbc0158a174.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01c98d54e8da336405

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment] 2022-08-05 15:23
This looks like it can be worked on externally.

**Comment by michaelhaxhiu** [comment] 2022-08-18 13:33
Doubled yesterday, so not overdue.

**Comment by michaelhaxhiu** [comment] 2022-08-25 13:11
Doubling again.

**Comment by andrewlor** [comment] 2022-09-15 20:31
# Proposal

## Problem
iOS just simply won't show the paste option when focused on a textarea, while the clipboard contains image data. I don't know if there is a better explanation other than that's just not how the OS works.

## Solution
Use a touch based event handler (so it doesn't run on desktop/web) on the textInput. In this handler, use the `navigator.clipboard` API to read the content. This triggers iOS Safari to prompt the user for permission for the website to use the clipboard, ie. the "Paste" context menu we're looking for. From here we can access the clipboard contents (even if it is an image) and reuse the existing paste handlers (`onPasteFile` and `handlePaste`).

https://github.com/Expensify/App/blob/main/src/components/Composer/index.js
```javascript
    handleTouch() {
        navigator.clipboard.read()
            .then(clipboardContents => clipboardContents[0].getType(clipboardContents[0].types[0]))
            .then((blob) => {
                if (!blob) {
                    return;
                }

                // If text, call handlePaste to reuse HTML parsing logic
                if (['text/html', 'text/plain'].includes(blob.type)) {
                    blob.text().then((data) => {
                        const dt = new DataTransfer();
                        dt.setData(blob.type, data);
                        this.handlePaste(new ClipboardEvent('paste', {clipboardData: dt}));
                    });
                    return;
                }

                // Otherwise go straight to file paste handler
                this.props.onPasteFile(new File([blob], `pasted-file.${blob.type.split('/')[1]}`, {type: blob.type}));
            })
            .catch(() => {});
    }
```
```diff
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -132,6 +132,7 @@ class Composer extends React.Component {
         };
         this.dragNDropListener = this.dragNDropListener.bind(this);
         this.paste = this.paste.bind(this);
+        this.handleTouch = this.handleTouch.bind(this);
         this.handlePaste = this.handlePaste.bind(this);
         this.handlePastedHTML = this.handlePastedHTML.bind(this);
         this.handleWheel = this.handleWheel.bind(this);
@@ -157,6 +158,7 @@ class Composer extends React.Component {
             document.addEventListener('dragenter', this.dragNDropListener);
             document.addEventListener('dragleave', this.dragNDropListener);
             document.addEventListener('drop', this.dragNDropListener);
+            this.textInput.addEventListener('touchend', this.handleTouch);
             this.textInput.addEventListener('paste', this.handlePaste);
             this.textInput.addEventListener('wheel', this.handleWheel);
         }
@@ -189,6 +191,7 @@ class Composer extends React.Component {
         document.removeEventListener('dragenter', this.dragNDropListener);
         document.removeEventListener('dragleave', this.dragNDropListener);
         document.removeEventListener('drop', this.dragNDropListener);
+        this.textInput.removeEventListener('touchend', this.handleTouch);
         this.textInput.removeEventListener('paste', this.handlePaste);
         this.textInput.removeEventListener('wheel', this.handleWheel);
     }
```

## Result

https://user-images.githubusercontent.com/8475244/190501795-4f2633b9-2d5e-4171-8fa7-c211b27c6ad3.mp4

This does still need a little bit of fine tuning with regards to the interaction with the input and when to show this extra paste prompt. For example when trying to select text already entered in the input, you have to tap multiple time because this extra paste prompt is showing instead. But it should be possible to figure out what these cases are and return early in the handler before calling the clipboard api. This is the core idea anyways.

**Comment by Santhosh-Sellavel** [comment] 2022-09-19 15:31
@andrewlor does this work for native app?

**Comment by MonilBhavsar** [comment] 2022-09-28 06:24
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2022-09-28 12:23
@andrewlor bump!

**Comment by andrewlor** [comment] 2022-09-28 14:43
Oh sorry I missed this. I'll have to check. The ios/android implementations of `Composer` look very different, so those might have an entirely different solution that we'd need to come up with.

**Comment by michaelhaxhiu** [comment] 2022-09-30 20:58
Thanks for update @andrewlor. Do you think you'd be able to have an update by early next week?

**Comment by michaelhaxhiu** [comment] 2022-10-10 17:08
Doubling job value to garner more interest.

@andrewlor are you still interested in this job?

**Comment by andrewlor** [comment] 2022-10-14 20:27
@michaelhaxhiu Sorry, having trouble coming up with something for native so far. Feel free to accept other proposals if someone else can come up with something.

**Comment by michaelhaxhiu** [comment] 2022-10-14 20:30
Thanks for giving it a try. This is open for all still, including you 👍

**Comment by michaelhaxhiu** [comment] 2022-10-25 13:11
Doubling price!

**Comment by cowboycito** [comment] 2022-10-25 15:42
@michaelhaxhiu I did some investigation and this is actually a limitation from WebKit. You can see [here](https://github.com/WebKit/webkit/blob/main/Source/WebCore/platform/ios/PasteboardIOS.mm#L439) all the file types that are "pasteable" on a WebKit input. If you actually copy and paste a PNG image, for example, it works. The problem is that the default image format on iOS is HEIC, which is not natively supported by WebKit.
With that in mind I'd like to know if making images "pasteable" on the native app is what we should focus on in this issue. If that's the case I'd be happy to propose a solution for that.
Any thoughts on this?

**Comment by Santhosh-Sellavel** [comment] 2022-10-25 16:20
We would like all the image formats possible and if HEIC is the default then we should definitely support that, I see WhatsApp does it. Hope this clarifies!

**Comment by ckrodrigues** [comment] 2022-10-25 16:22
@Santhosh-Sellavel WhatsApp does it on the mobile app, not on mobile web. On the mobile app it can be done but as far as I could understand this issue is related to mobile web.

**Comment by cowboycito** [comment] 2022-10-25 16:23
@Santhosh-Sellavel WhatsApp does it on the mobile app, not on mobile web. On the mobile app it can be done but as far as I could understand this issue is related to mobile web.

**Comment by Santhosh-Sellavel** [comment] 2022-10-25 16:29
Ah sorry, I misread that. But I believe we have a proposal for mWeb [here](https://github.com/Expensify/App/issues/10263#issuecomment-1248584623).

**Comment by michaelhaxhiu** [comment] 2022-10-28 18:25
@cowboycito were you interested in making a proposal on this one 😺 ?

**Comment by cowboycito** [comment] 2022-10-28 18:33
@michaelhaxhiu I was but according to my research there's no way to natively support what the issue specifies (since WebKit explicitly specifies only a few mime types). Given that, I think @andrewlor 's solution is the best one for now, although it causes some other issues related to long press/double tap the input. If at any moment we decide that pasting "native" iOS images (e.g.: HEIC files) on mWeb is not necessary (aka PNG, JPG... are enough), I'd be more than happy to submit a proposal to allow pasting images (pretty much any file actually) on the mobile app, and also "declare" the mobile app as a "shareable" application (in case that's not setup yet) on both Android and iOS, which would allow people to share images/files from other apps using the "share" menu.

**Comment by michaelhaxhiu** [comment] 2022-10-28 19:07
Understood! Thanks for the explanation. 

>there's no way to natively support what the issue specifies

Do you think a potential upstream repo fix could be in order here to solve this problem? We've done them in the past and I'm mainly curious what you think!

**Comment by cowboycito** [comment] 2022-10-28 20:02
@michaelhaxhiu not sure I got what you suggested. Do you mean changing WebKit's code?

**Comment by michaelhaxhiu** [comment] 2022-10-28 20:27
Yep, that's what I was suggesting. Mainly because we've had other upstream repo fixes for react libraries in the past, so just thinking if it makes sense here too to fully solve it?

**Comment by cowboycito** [comment] 2022-10-28 21:21
@michaelhaxhiu so I just did another quick research on the WebKit/HEIC topic and I believe it's not something that will happen, even if we fix the issue and open a PR on WebKit's repo. If you take a look at [this comment](https://github.com/WebKit/WebKit/pull/3731#issuecomment-1232949778) you'll see that they don't want to put proprietary file formats (which is the case of HEIC) on WebKit. With that being said, in my opinion there are 2 options for this issue: go with @andrewlor 's approach (which would also possibly require a HEIC => PNG/JPEG converter) or accept the fact that WebKit won't allow us pasting HEIC images. Both options are only applicable for mWeb, we still can make pretty much any file "pasteable" on the mobile app.

**Comment by michaelhaxhiu** [comment] 2022-10-28 21:26
That's super informative @cowboycito and helps explain the philosophy that webkit is operating on. I find HEIC files to be ridiculous and sort of hate them... they break all sorts of apps/uploads. I thought maybe still though, since it's apple backing this unique file type. Thank you for finding that contextual evidence and giving this a thoughtful take!

**Comment by bulatgab** [comment] 2022-11-01 18:34
# Proposal (Android)
Hello everyone! The challenge looked exciting and I think I've worked out a solution using RN Native Components. This would be my first contribution to Expensify 🙂

https://user-images.githubusercontent.com/18130716/199310990-f289f161-a275-4c26-a66a-dce171466d13.mp4

## Problem
RN TextInput doesn't expose API for overriding the 'paste' events. It has to be done on the native side.

## Solution (native side)
1. Follow RN docs for Android Native components:
- override ReactEditText. Handle 'Paste' option when the clipboard has image content, emit an event to the JS side
```
public class CustomEditText extends ReactEditText {
    ...
    public boolean onTextContextMenuItem(int id) {
        if (id != android.R.id.paste) {
            return super.onTextContextMenuItem(id);
        }
        ClipboardManager clipboard = (ClipboardManager) getContext().getSystemService(Context.CLIPBOARD_SERVICE);
        if (!clipboard.hasPrimaryClip() || !clipboard.getPrimaryClipDescription().hasMimeType("image/*")) {
            return super.onTextContextMenuItem(id);
        }
        emitOnPasteImageEvent(clipboard.getPrimaryClip().getItemAt(0).getUri());
        return true;
    }

    private void emitOnPasteImageEvent(Uri uri) {
        Cursor cursor = getContext().getContentResolver().query(uri, null, null, null, null);
        cursor.moveToFirst();

        int nameIndex = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
        int sizeIndex = cursor.getColumnIndex(OpenableColumns.SIZE);

        WritableMap event = Arguments.createMap();
        event.putString("uri", "file://" + CustomPathResolver.getRealPathFromURI(getContext(), uri));
        event.putDouble("size", cursor.getLong(sizeIndex));
        event.putString("name", cursor.getString(nameIndex));
        event.putString("type", getContext().getContentResolver().getType(uri));
        cursor.close();

        ((ReactContext)getContext())
                .getJSModule(RCTEventEmitter.class)
                .receiveEvent(getId(), "onPasteImage", event);
    }
}
```
- create a ViewManager (we can extend ReactTextInputManager) and register new `onPasteImage` event
- create a ReactPackage
- register the ReactPackage in MainApplication

2. One of the tricky parts is that the uri from the clipboard looks like 
```
content://com.android.chrome.FileProvider/images/screenshot/16673251374447424239374088189322.jpg
```
We have to create a temporary copy and get _its_ uri that would look like
```
/data/user/0/com.expensify.chat/cache/16673251374447424239374088189322.jpg
```
Code for this (I'm reusing `PathResolver` class from `react-native-blob-util` package that's already in the project. But this can be refactored to remove dependency)
```
public class CustomPathResolver extends PathResolver {
    public static String getRealPathFromURI(final Context context, final Uri uri) {
        try {
            InputStream attachment = context.getContentResolver().openInputStream(uri);
            if (attachment != null) {
                String filename = getContentName(context.getContentResolver(), uri);
                if (filename != null) {
                    File file = new File(context.getCacheDir(), filename);
                    FileOutputStream tmp = new FileOutputStream(file);
                    byte[] buffer = new byte[1024];
                    while (attachment.read(buffer) > 0) {
                        tmp.write(buffer);
                    }
                    tmp.close();
                    attachment.close();
                    String path = file.getAbsolutePath();
                    Log.d("Bulat", "getAbsolutePath " + path);
                    return path;
                }
            }
        } catch (Exception e) {
            ReactNativeBlobUtilUtils.emitWarningEvent(e.toString());
            return null;
        }
        return null;
    }
```

## Solution (JS side)

1. Follow RN docs for Android Native Components and create JS module
```
export default requireNativeComponent('CustomAndroidTextInput');
```

2. We now have our native component. However, RN has some JS code on top of the original `AndroidTextInput`. We need to implement it too (to mirror TextInput fully) - by copying and adapting:
- `InternalTextInput` (that would now wrap our `CustomAndroidTextInput`)
- `ExportedForwardRef` (that would wrap the previous one)

3. Eventually, in the Composer we use our new component:
```
class Composer extends React.Component {
    ...
    render() {
        return (
            <CustomTextInput
                ...
                onPasteImage={(fileLike) => {
                    this.props.onPasteFile(fileLike);
                }}
            />
        );
    }
```
The `fileLike` is a `{uri, size, name, type}` object.

Cheers!

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 18:47
Welcome @bulatgab 
Please check out our [readme](https://github.com/Expensify/App#readme) to get familiar with our repo and also our[ contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process.

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 18:53
On a quick look seems you are proposing only changes for Android we need a comprehensive solution for all platforms.

**Comment by michaelhaxhiu** [comment] 2022-11-01 20:46
@bulatgab welcome and we are excited to have you as a member of Expensify Open Source! 

Are you able to expand this proposal to apply to all affected Platforms from the GH body?

>Platform:
>
> - Web
> - iOS
> - Android
> - Desktop App
> - Mobile Web

**Comment by michaelhaxhiu** [comment] 2022-11-01 21:02
@MonilBhavsar I was chatting with Santhosh in New Expensify 1:1 and he mentioned that **maybe** we could benefit by segmenting this problem into two pieces?

- one solution for Native 
- one solution for mWeb

What do you think based on the proposals so far? We can post in slack too to get more input if unsure.

**Comment by bulatgab** [comment] 2022-11-01 22:54
Thank you for your response @Santhosh-Sellavel @michaelhaxhiu and for sharing the links!

Yes, at the moment the solution covers Android only.
I will try to prepare a fix for iOS next, hopefully, this week.
(I don't know if I can fix it for other platforms. Maybe after iOS)

**Comment by hellohublot** [comment] 2022-11-02 14:16
### Proposal

A little bit slower, someone already provided `@mattermost/react-native-paste-input` when I took the screenshot, by the way, I suggest you fork this library as `Expensify/react-native-textinput-extension`, because we have `a lot of TextInput issues`, we can modify it to solve our issues.

I can only reproduce it on [mWeb-Safari, iOS, android].

#### For mWeb-Safari
https://github.com/WebKit/WebKit/blob/d7bab9d6f7c45b99da17d78a464eac1fedff0ead/Source/WebCore/Modules/async-clipboard/Clipboard.cpp#L220-L233
https://w3c.github.io/clipboard-apis/#mandatory-data-types-x
navigator.clipboard can only read `png image`,
So I think submitting jpeg etc to `WebKit` may be rejected, 
and navigator.clipboard will cause `gesture conflicts`

So I want to show the native 'paste' event

https://github.com/WebKit/WebKit/blob/d7bab9d6f7c45b99da17d78a464eac1fedff0ead/Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm#L3584-L3592
```objective-c
static NeverDestroyed supportedTypes = [] {
    ...
    [types addObjectsFromArray:UIPasteboardTypeListImage];
    return types;
}();
```

https://github.com/WebKit/WebKit/blob/d7bab9d6f7c45b99da17d78a464eac1fedff0ead/Source/WebCore/editing/ios/EditorIOS.mm#L230-L232

```objective-c
String Editor::plainTextFromPasteboard(const PasteboardPlainText& text)
{
    auto string = text.text;

    // FIXME: It's not clear this is 100% correct since we know -[NSURL URLWithString:] does not handle
    // all the same cases we handle well in the URL code for creating an NSURL.
    if (text.isURL)
        string = WTF::userVisibleString([NSURL URLWithString:string]);

    // FIXME: WTF should offer a non-Mac-specific way to convert string to precomposed form so we can do it for all platforms.
    return [(NSString *)string precomposedStringWithCanonicalMapping];
}
```

https://github.com/WebKit/WebKit/blob/d7bab9d6f7c45b99da17d78a464eac1fedff0ead/Source/WebCore/editing/Editor.cpp#L678-L685
```c++
#if !PLATFORM(MAC) && !PLATFORM(IOS_FAMILY)
...
```

https://user-images.githubusercontent.com/20135674/199511821-2817ba38-94f4-4f78-bd85-2cabc18cbdbb.mp4

**Comment by bulatgab** [comment] 2022-11-02 14:47
The @mattermost/react-native-paste-input package is a great find 👍
(IMHO, it also opens a hybrid approach. If it is decided to minimize the use of third-party libraries and we aim at writing in-house native components, PasteInput could be used as an iOS-only solution until our own component is ready)

**Comment by Santhosh-Sellavel** [comment] 2022-11-04 13:22
This requires additional time to review, will possibly update by Monday!

**Comment by Santhosh-Sellavel** [comment] 2022-11-04 14:21
@cowboycito If you are interested in solving this one even native alone, please post your solution as we might consider solving native alone. To make that decision we need your proposal, thanks!

Cc: @MonilBhavsar @michaelhaxhiu

**Comment by cowboycito** [comment] 2022-11-04 14:55
@Santhosh-Sellavel honestly my approach would be identical to @0xmiroslav 's. So since they posted the proposal first I think we already have a strong candidate for the issue.

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 17:02
@MonilBhavsar what do we prefer, do we prefer writing in-house components or external libraries?

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 17:03
> Thank you for your response @Santhosh-Sellavel @michaelhaxhiu and for sharing the links!
> 
> Yes, at the moment the solution covers Android only. I will try to prepare a fix for iOS next, hopefully, this week. (I don't know if I can fix it for other platforms. Maybe after iOS)

@bulatgab Any update from your side?

**Comment by bulatgab** [comment] 2022-11-07 19:35
@Santhosh-Sellavel
Thank you for asking!

If Android + iOS should necessarily go together, my approach for the iOS part at the moment would be to write a native component very close to the `react-native-paste-input` iOS code.

If the Android part could be done separately that would be the preferred option for me though (I'm more experienced in Android than iOS).

**Comment by michaelhaxhiu** [comment] 2022-11-09 22:12
@MonilBhavsar We could use some input from you on this question to move forward in assessing the existing proposals. If you are stuck or want buddy checks - I think #expensify-open-source is the best place.
>@MonilBhavsar what do we prefer, do we prefer writing in-house components or external libraries?

**Comment by MonilBhavsar** [comment] 2022-11-10 10:29
I would vote for inhouse component over package, if it fixes the issue. We can go with package if implementation is complex. In this case it would be handling touched or longPress event on text input, no? Happy to discuss fors and against of using package vs custom component in this case. Please share your thoughts. 
And if we go with that package, let us make sure it follow some rules that it is actively maintained, issues are fixed regularly.

**Comment by michaelhaxhiu** [comment] 2022-11-11 13:50
Asking internally for buddy check here - https://expensify.slack.com/archives/C03U7DCU4/p1668174580005129?thread_ts=1658993183.315469&cid=C03U7DCU4

**Comment by Santhosh-Sellavel** [comment] 2022-11-14 15:53
@michaelhaxhiu any development internally?

> Asking internally for buddy check here - https://expensify.slack.com/archives/C03U7DCU4/p1668174580005129?thread_ts=1658993183.315469&cid=C03U7DCU4

**Comment by michaelhaxhiu** [comment] 2022-11-16 19:20
@MonilBhavsar is going to post and get more input, sorry on the delay. He will link that slack thread here when it's all done.

**Comment by MonilBhavsar** [comment] 2022-11-17 07:07
Posed here https://expensify.slack.com/archives/C01SKUP7QR0/p1668668846672319

**Comment by JmillsExpensify** [comment] 2022-11-17 21:34
@MonilBhavsar To help clear out the extensive backlog of /App bugs, we're putting the spotlight on all bugs older than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:

 - Decide whether any proposals currently meet our guidelines and can be approved as-is
 - For any that can't, please take this issue internal and treat it as one of your highest priorities
 - If you have any questions, don't hesitate to start a discussion in #bug-zero

Thanks everyone!

**Comment by michaelhaxhiu** [comment] 2022-11-18 15:01
Ok everyone, we've had internal discussion about this job and feel it's time to close it... Here are some notes on why:

- While the proposals provided have been a helpful attempt, this is a `New Feature` and no proposal has won yet. And we are freezing all `New Features` to focus on `Bugs`.
- We feel the best solution here would be in an upstream library fix (react native / react native web), which no one has truly proposed a full solution or pursued yet. 
- Using or forking 3rd party library may be possible, but it comes with inherent risks in terms of maintenance and reliability that we aren't willing to do.
- Sometimes we do partial payouts when a proposal is vetted heavily and selected (or even _almost selected_), but in this case I don't think we did heavy vetting or got close to selection. So I am not proposing a payout.

With this in mind, I'm going to close this GH. Thanks all for your efforts - let's focus on other existing bugs 🙏

**Closed by michaelhaxhiu** 2022-11-18 15:01 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug

**Comment by azimgd** [comment] 2022-11-21 13:25
> We feel the best solution here would be in an upstream library fix (react native / react native web), which no one has truly proposed a full solution or pursued yet.

While I'm aware that this issue is closed and you are focusing on existing bugs, I would like to let you know that I have been working on a "upstream PR" for https://github.com/expensify/react-native. PR includes `onPasteFile` prop support for both iOS and Android implemented with OBJ-C and Android respectively.

I expect to get full PR prepared and submitted by this week, therefore wanted to hear your opinion if this is something you are still interested in (given the timeline i provided). @MonilBhavsar @michaelhaxhiu

**Comment by bulatgab** [comment] 2022-11-21 16:13
(If this is really an option, I would like to apply too. It would indeed be simpler and cleaner than writing native components. I overlooked initially that we were using forks of react-native and other libs, my bad)

**Comment by MonilBhavsar** [comment] 2022-11-22 13:40
Discussing internally. Will update shortly

**Comment by azimgd** [comment] 2022-11-22 14:11
here is the draft PR for the reference: https://github.com/Expensify/react-native/pull/34/files

**Comment by azimgd** [comment] 2023-01-11 11:08
@MonilBhavsar @michaelhaxhiu bump.

**Comment by michaelhaxhiu** [comment] 2023-01-11 17:56
Hey @azimgd sorry for the delay mate. Looking into it now!

**Comment by michaelhaxhiu** [comment] 2023-01-18 17:32
Thanks for your patience here. For this particular issue, the gameplan is to do the following:

- Keep the issue closed
- No pay will be issued for this `new feature`, unless otherwise discussed... which leads to my next point:
- If anyone on the issue wants to push this fowrward, please start by putting a post in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) to get a discussion going as to whether we want to do anything (e.g. a `New Feature` proposal)

Still worth saying we appreciate your proactive mindset @azimgd and @bulatgab on checking on this 🙏
