### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Simple AA in NewDot] Handling user removed from a Control policy (in NewDot) with Advanced Approval configured

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#43885] opened 2024-06-18 06:43 UTC
Tracking issue: https://github.com/Expensify/Expensify/issues/393839

This issue is the NewDot part of https://github.com/Expensify/Expensify/issues/404210

## Action Performed:
1. Create Control workspace, make sure you can see it in NewDot
    - In OldDot, make sure the Control workspace has "Advanced Approvals" set up (on the workspace settings -> Members tab)
2. In OldDot, Add at least 2 other members (non-admin)
3. In OldDot, Set up 1 of the members (Member A) as the `submitsTo` of the other member (Member B)
4. In NewDot, as the admin, try to remove `Member A` from the workspace

## Expected Result:
1. Check if the person being removed exists in the policy's `employeeList` as an approver (listed as any member's submitsTo, forwardsTo, or overLimitForwardsTo)
    1. If YES, show the user a warning & set some optimistic data before calling `DeleteMembersFromWorkspace`:
        1. Warning copy should read:
            > Remove selected member?
            > 
            > [Selected member] is an approver in this workspace. When you remove them, we’ll replace them in the approval workflow with the workspace owner, [Workspace Owner].        
2. Optimistically also replace the removed person w/ the workspace owner, anywhere they existed in the policy `employeeList` as an approver
    3. If NO, proceed as normal with `DeleteMembersFromWorkspace`

Note: Backend Onyx updates will happen in https://github.com/Expensify/Expensify/issues/404210

Also note: In https://github.com/Expensify/App/issues/43508 we're implementing the ability for non-owner admins to **leave** workspaces so that doesn't need to be handled in this issue

cc @garrettmknight in case you'd like to be involved in this change
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf9c32f16606de5d</li>
        <li>Upwork Job ID: 1802955325447394518</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102790397</li>
<li>nkdengineer | Contributor | 102790399</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by nkdengineer** [comment] 2024-06-18 07:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Handling user removed from a Control policy (in NewDot) with Advanced Approval configured

### What is the root cause of that problem?

This is a new feature request.

### What changes do you think we should make in order to solve the problem?
> Check if the person being removed exists in the policy's employeeList as an approver (listed as any member's submitsTo, forwardsTo, or overLimitForwardsTo)

1. To check if the person being removed exists in the policy's employeeList as an approver, we can create a util like this

```
function isApproval(policy: Policy, employeeEmail: string) {
    return Object.values(policy?.employeeList ?? {}).some((employee) => employee?.submitsTo === employeeEmail || employee?.forwardsTo === employeeEmail || employee?.overLimitForwardsTo === employeeEmail)
}
```

> If YES, show the user a warning & set some optimistic data before calling DeleteMembersFromWorkspace:

2. If yes, after we confirm to call `DeleteMembersFromWorkspace` API we will show a warning modal with the text like this. Or we can show this warning when we show the confirm modal when clicking on remove member.

> Unshare with selected member?

> [Selected member] is an approver in this workspace. When you unshare this workspace with them, we’ll replace them in the approval workflow with the workspace owner, [Workspace Owner].

https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/pages/workspace/WorkspaceMembersPage.tsx#L196

> Optimistically also replace the removed person w/ the workspace owner, anywhere they existed in the policy employeeList as an approver

And then in `removeMembers` function, we will check the each member in `employeeList` if `submitsTo`, `forwardsTo`, `overLimitForwardsTo` is includes in the removed member lists we will replace this field with the owner of the workspace in `optimisticData` and restore it in `failureData`.

https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/Policy/Member.ts#L219

> If NO, proceed as normal with DeleteMembersFromWorkspace

3. If not, we don't need to change any thing and process as normal with `DeleteMembersFromWorkspace` API.
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-06-18 15:48
@akinwale when you have a chance, this PR is tied to an internal initiative. Can you review the proposal from @nkdengineer when you get a chance? Thanks!

**Comment by akinwale** [comment] 2024-06-19 01:18
We can move forward with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/43885#issuecomment-2175387030) here.

Additionally, @nkdengineer, please double-check how the member count should be updated when setting the optimistic data.

🎀👀🎀 C+ reviewed.

**Comment by Beamanator** [comment] 2024-06-19 06:36
Proposal looks great! I didn't see the "warning modal" detailed in the proposal, but we can get to that in the PR review 👍 

Also @dannymcclain I will request you help review the PR design - specifically the warning modal - once it's ready! 🙏  In the [Support Simple Additional Approvals in NewDot](https://docs.google.com/document/d/1CSRVEBmiOL1s0hk7qqZvXoiUuHoL0m_DnTKRXy4txYI/edit) design doc we shows how this warning would look in OldDot, but not NewDot 😅

**Comment by dannymcclain** [comment] 2024-06-19 13:53
@Beamanator no worries. We should use our standard confirmation dialog for this modal. It should end up looking something like this:
![image](https://github.com/Expensify/App/assets/7516624/6dc0d303-18bf-4785-a127-cc1047b1ff97)

I do think we need to tighten up the language for that modal though. In the issue description we use the language "unshare", but that language doesn't appear anywhere in the product. I think we need to stick with `remove` since that's what the action is called in the UI.

**Comment by Beamanator** [comment] 2024-06-19 14:04
Ooh nice I like that copy update, please keep that in mind with your PR @nkdengineer 🙏

**Comment by nkdengineer** [comment] 2024-06-19 14:05
Sure, got it now.

**Comment by dannymcclain** [comment] 2024-06-19 14:09
Nice! Oh also, might be worth noting that in that mockup I just stuck a random member screen behind that modal—the real one would just show up on top of whatever screen was present when you click to remove the member!

**Comment by nkdengineer** [comment] 2024-06-19 15:32
@akinwale The PR is [here](https://github.com/Expensify/App/pull/44008).

**Comment by garrettmknight** [comment] 2024-06-19 18:51
@nkdengineer I've updated the copy in the OP. Find the updated Spanish here:
>¿Eliminar miembro seleccionado? 
>
>[Selected member] es un aprobador en este espacio de trabajo. Cuando lo elimine de este espacio de trabajo, los sustituiremos en el flujo de trabajo de aprobación por el propietario del espacio de trabajo, [Workspace Owner].

**Comment by nkdengineer** [comment] 2024-06-20 08:35
I updated in my PR.

**Comment by garrettmknight** [comment] 2024-06-24 21:13
@akinwale can you prioritize this one, please?

**Comment by Beamanator** [comment] 2024-07-01 07:15
Looks like the App PR has a regression: https://github.com/Expensify/App/issues/44631

@nkdengineer please take a look as soon as you can 🙏

**Comment by garrettmknight** [comment] 2024-07-03 19:39
For my own notes - https://github.com/Expensify/App/pull/44654 is still on staging, once it hits prod we'll start the regression /payment clock again.

**Comment by trjExpensify** [comment] 2024-07-10 17:50
👋 checklist list! Confirming there was one regression here, right?

**Comment by Beamanator** [comment] 2024-07-11 08:39
Agreed, only 1

**Comment by trjExpensify** [comment] 2024-07-15 20:41
Cool, thanks for confirming. Awaiting the checklist!

**Comment by akinwale** [comment] 2024-07-16 20:58
> * [x]  [@akinwale] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure  the new feature will work correctly on production in further releases.

**Regression Test Steps**
_Preconditions:_
* Create a Control workspace in OD with applied settings to make it visible in ND
* Enable "Advanced Approvals" for the workspace (on Workspace settings -> Members tab)
* At least 2 employee members added to the workspace
* In OD, one of the members (Member A) set up as the Approves To of the other member (Member B)

1. Launch Expensify
2. Navigate to the control workspace indicated above
3. Open member page
4. Select member A and click Remove.
5. Verify that the confirm modal appears with the warning prompt [Selected member] is an approver in this workspace. When you unshare this workspace with them, we’ll replace them in the approval workflow with the workspace owner, [Workspace Owner].
6. Open the member detail page of member A
7. Click on the Remove from workspace button
8. Verify that the confirm modal appears with the same warning prompt similar to step 5
9. Click Remove
10. Verify that the optimistic data and failure data are correct
11. Verify that the user is removed from the workspace

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-07-16 20:58
@trjExpensify Checklist completed.

**Comment by trjExpensify** [comment] 2024-07-19 18:23
@garrettmknight @Beamanator - will the regression tests be added centrally for this project, or do you want me to add the one above?

**Comment by trjExpensify** [comment] 2024-07-19 18:25
Payment summary as follows: 

- $250 to @akinwale for the C+ review
- $250 to @nkdengineer for the fix

Paid you both via Upwork!

**Comment by trjExpensify** [comment] 2024-07-22 21:18
Asked [in Slack](https://github.com/Expensify/App/issues/43885#issuecomment-2239865161) about this.

**Comment by garrettmknight** [comment] 2024-07-22 21:31
Regression test will be added centrally, but I’ll double check that we’re covering that scenario tomo. I’m pretty sure we are.

**Comment by trjExpensify** [comment] 2024-07-23 13:00
Sounds good. We can close this issue when confirmed.

**Comment by garrettmknight** [comment] 2024-07-24 17:45
Confirmed, we're all set.

**Closed by garrettmknight** 2024-07-24 17:45 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
