### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Login - "Chat and split expenses" option is truncated on the onboarding modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43804] opened 2024-06-15 20:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when executing #43479
**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Log in with a new Gmail account

## Expected Result:
"Chat and split expenses" option should be fully visible.

## Actual Result:
"Chat and split expenses" option is truncated on the onboarding modal.

## Workaround:
visual
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/680b5ce8-cce2-46a7-be2d-f03d9830ac41

<img src="https://github.com/Expensify/App/assets/38435837/eadc0787-215d-42f8-bb8e-25dc6ed8f21c" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c02ce36ab64ecdf6</li>
        <li>Upwork Job ID: 1804256617422060262</li>
        <li>Last Price Increase: 2024-06-21</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102851828</li>
<li>nkdengineer | Contributor | 102851830</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by m-natarajan** [comment] 2024-06-15 20:12
@OfstadC FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-06-15 20:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The number of lines for menuitem titles is set to `1` by default
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/MenuItem.tsx#L308

This restricts the titles to only 1 line in narrow screens

### What changes do you think we should make in order to solve the problem?
We will pass number of lines for the title as 2 to make sure text gets rendered properly for smaller devices

We will add `numberOfLinesTitle: 2` here:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L91-L93


### Alternatively
We can pass this by adding a prop in MenuItemsList

**Comment by OfstadC** [comment] 2024-06-17 20:07
I'm not able to reproduce 🤔 
![2024-06-17_15-04-37 (1)](https://github.com/Expensify/App/assets/11722379/1a23c7eb-bf90-4f59-95e7-3cdc5fb04dc0)

**Comment by OfstadC** [comment] 2024-06-18 15:08
Okay - I tried on about 6 android devices, 3 of which google said had smaller screens and the only one I was able to reproduce on was Samsung S24 😅 . 
<img width="376" alt="image" src="https://github.com/Expensify/App/assets/11722379/d4260b82-422a-426a-9120-9e49e7411c57">

**Comment by OfstadC** [comment] 2024-06-20 14:01
Hi @Julesssss ! New to BZ here so just want to make sure I take the next steps. I see you self assigned, so should I add the `internal` label - or do we still want to create an external posting?

**Comment by Julesssss** [comment] 2024-06-20 14:05
Hey @OfstadC, I assigned just because I was interested in seeing the solution to the bug. So we can follow the normal process 🙂

**Comment by OfstadC** [comment] 2024-06-21 20:53
### Discussed in Slack - The solution should ensure we aren't truncating when viewing or selecting the menu item. We'd want to let any device/width use as many lines as needed

**Comment by nkdengineer** [comment] 2024-06-22 06:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Chat and split expenses" option is truncated on the onboarding modal.

### What is the root cause of that problem?
By default, the title of MenuItem will have 1 as `numberOfLinesTitle` https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/MenuItem.tsx#L320.

Therefore, when the text is long such that it should span 2 lines, it will be truncated.

### What changes do you think we should make in order to solve the problem?

> The solution should ensure we aren't truncating when viewing or selecting the menu item. We'd want to let any device/width use as many lines as needed

This is the requirement. We need to make sure the `numberOfLines` [here](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/MenuItem.tsx#L641) is not set. One way to do it is to add `numberOfLinesTitle: 0` [here](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L102) so [no truncation will occur](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/MenuItem.tsx#L641) in any circumstance.

We use the same method in other locations like in https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/ReportActionItem/MoneyReportView.tsx#L88 where no-truncation behavior is needed.

FYI any hardcoded value like `2` will not work reliably because there could be very small devices that will require 3 lines to display the item, or the copy of the title could be changed such that it needs more than 2 spaces in smaller devices.

### What alternative solutions did you explore? (Optional)
Set the default `numberOfLinesTitle` [here](https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/MenuItem.tsx#L320) to `0` (and maybe the `numberOfLinesDescription` too). Truncating texts should be a conscious decision and should only be done intentionally, not accidentally just because the default value is set that way.

**Comment by Julesssss** [comment] 2024-06-24 08:09
SOlution is simple and makes sense

**Comment by nkdengineer** [comment] 2024-06-26 02:33
I'll raise PR soon

**Comment by nkdengineer** [comment] 2024-06-26 03:42
@allgandalf this [PR](https://github.com/Expensify/App/pull/44424) is ready for review

**Comment by OfstadC** [comment] 2024-07-09 15:07
@allgandalf Could you please update this today based on the checklist? Thank you! 😃

**Comment by OfstadC** [comment] 2024-07-10 19:46
Payment Summary:

Contributor+: @allgandalf paid $250 via Upwork
Contributor: @nkdengineer  paid $250 via Upwork

**Comment by OfstadC** [comment] 2024-07-11 18:30
Leaving this open until regression testing is complete

**Comment by OfstadC** [comment] 2024-07-15 15:25
Same - waiting on regression testing

**Comment by OfstadC** [comment] 2024-07-16 16:25
I'm actually going to close this out. but I'll note here if the regression test yields anything 😄

**Closed by OfstadC** 2024-07-16 16:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
