### ISSUE TITLE
[HOLD for payment 2024-02-14] [$125] Web - Profile icon and wrench at the bottom have the same tooltips

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35728] opened 2024-02-02 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login in to New Expensify
2. Hover over Profile icon
3. Hover over wrench icon at the bottom
4. Note that the tooltips are the same

## Expected Result:
The tooltips should differ, and describe the pages to which they lead.

## Actual Result:
For both icons the tooltip is: "Settings". Even though one leads to Account Settings, and the other to Workspaces Settings.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1ffaa1de-6381-4d44-a075-f35274c46da8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011391fcb0d4fa84f7</li>
        <li>Upwork Job ID: 1753532395165429760</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28142751</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-02 21:33
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by luacmartins** [comment] 2024-02-02 21:35
Yes, it comes from the ideal nav PR. I don't think this is a blocker. Demoting and making it external so a contributor can work on it.

**Comment by Tony-MK** [comment] 2024-02-02 23:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Profile icon and wrench at the bottom have the same tooltips.

### What is the root cause of that problem?

We used the `common.settings` translation for the `tooltipText` prop in the `PressableAvatarWithIndicator` component.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/sidebar/PressableAvatarWithIndicator.js#L59-L61

It is also used in the `BottomTabBar` component, thus will display identical text in the tooltip.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L66-L67

### What changes do you think we should make in order to solve the problem?


Since the other components depend on the `PressableAvatarWithIndicator` component, the appropriate replacement `common.settings` would be  `initialSettingsPage.account`.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/languages/en.ts#L821-L822

```
tooltipText={translate('initialSettingsPage.account')}
```
### What alternative solutions did you explore? (Optional)

If it is more appropriate to display Account Settings than Account, we can then use the `initialSettingsPage.accountSettings` translation.

**Comment by twisterdotcom** [comment] 2024-02-05 13:17
@alitoshmatov this seems pretty simple. Can we get one of these moving?

**Comment by luacmartins** [comment] 2024-02-05 14:52
I think @Amarparab2024 has the right solution, since we should replace that tooltip with `Profile`. Assigning to the job.

**Comment by alitoshmatov** [comment] 2024-02-05 15:52
Looks like proposal is already selected without C+. I am assuming PR review by C+ is still required. Unassign me if review is not needed

**Comment by luacmartins** [comment] 2024-02-05 16:24
Unfortunately not, and I think we should have changed the bounty for that issue too

**Comment by twisterdotcom** [comment] 2024-02-07 12:29
@Amarparab2024 can you share your Upwork profile link please?

**Comment by twisterdotcom** [comment] 2024-02-14 09:57
@alitoshmatov I need you to accept your offer: https://www.upwork.com/nx/wm/offer/28142751
@Amarparab2024 I need you to accept your offer: https://www.upwork.com/nx/wm/offer/100905317

**Comment by twisterdotcom** [comment] 2024-02-14 22:03
Payment Summary:

- @alitoshmatov paid $125 [here](https://www.upwork.com/nx/wm/offer/28142751) - C+
- @Amarparab2024 paid $125 [here](https://www.upwork.com/nx/wm/offer/100905317) - Contributor

We do not need a Test for this.

**Closed by twisterdotcom** 2024-02-14 22:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
