### ISSUE TITLE
[Hold PR #44907] [$250] Report field - Different system message for report field edit in expense report and LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44831] opened 2024-07-04 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory around https://expensify.testrail.io/index.php?/tests/view/4695978
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has created a Text type report field from Report fields section on ND.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Click on the text field.
5. Enter text and save it.
6. Revisit the expense report.

## Expected Result:
The system message for report field edit will be consistent in expense report and LHN.

## Actual Result:
The system message for report field edit is different in expense report and LHN.
In expense report, it shows "changed Text field from undefined to x."
In LHN, it shows "modified field 'Text field'. New value is 'x' (previously '').
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/796620e5-bf65-4070-be7d-36b05e73d6fd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8549f82fbcaeb27</li>
        <li>Upwork Job ID: 1808920292412937149</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2024-07-04 17:44
We can demote this per [this thread](https://expensify.slack.com/archives/C03TQ48KC/p1720079377895369) (report fields are behind a beta).

**Comment by arosiclair** [comment] 2024-07-04 17:46
Pretty sure this can be fixed externally

**Comment by nkdengineer** [comment] 2024-07-04 19:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message for report field edit is different in expense report and LHN.
In expense report, it shows "changed Text field from undefined to x."
In LHN, it shows "modified field 'Text field'. New value is 'x' (previously '').

### What is the root cause of that problem?
In `ReportActionItem` the change field action is displayed as a message that is returned by `getMessageOfOldDotReportAction` function

https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/pages/home/report/ReportActionItem.tsx#L616-L619

For LHN, we display the subtitle as `lastMessageText`

https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/libs/SidebarUtils.ts#L337

And in `getLastMessageTextForReport`, we don't have a special case for change field action
https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/libs/OptionsListUtils.ts#L660

So the last message text is displayed as `report.lastMessageText`
https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/libs/OptionsListUtils.ts#L725

<img width="386" alt="Screenshot 2024-07-05 at 02 14 39" src="https://github.com/Expensify/App/assets/161821005/405b0efb-3792-4bc1-b14c-8f31878f14ad">

That is the inconsistent of this issue
### What changes do you think we should make in order to solve the problem?
In `getLastMessageTextForReport`, we should have a special case for old dot action as we do in `ReportActionItem` [here](https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/pages/home/report/ReportActionItem.tsx#L616-L619)

https://github.com/Expensify/App/blob/21f74e94dea122e2f8af46e1264362e0de8a8331/src/libs/OptionsListUtils.ts#L725


```
else if (ReportActionUtils.isOldDotReportAction(lastReportAction)) {
    lastMessageTextFromReport = ReportActionUtils.getMessageOfOldDotReportAction(lastReportAction);
}
```
And then in this case we will use `getMessageOfOldDotReportAction` function to get the display message.

The last action can be null or undefined, so we also need to update the condition here safely to avoid the app crashes

```
oldDotActionName === action?.actionName
```
https://github.com/Expensify/App/blob/d93e24beb21935e935cd449ed5a29934d00bbf64/src/libs/ReportActionsUtils.ts#L1214
### What alternative solutions did you explore? (Optional)


Or we can change the format of chang field action in `getMessageOfOldDotReportAction` to match with the format in `message` array of change field action.


https://github.com/Expensify/App/blob/b49d5b8dd54d040e7dd684a7d044acc203d9c949/src/libs/ReportActionsUtils.ts#L1239

**Comment by nkdengineer** [comment] 2024-07-05 13:40
> else if (ReportActionUtils.isOldDotReportAction(lastReportAction)) {
    lastMessageTextFromReport = ReportActionUtils.getMessageOfOldDotReportAction(lastReportAction);
}

@parasharrajat My proposal will fix for all old dot action.

**Comment by arosiclair** [comment] 2024-07-05 14:17
This seems to be stemming from https://github.com/Expensify/App/pull/43079 and the system messages project. The [proposal](https://github.com/Expensify/App/issues/44831#issuecomment-2209481393) LGTM for fixing last message text in the LHN. @deetergp you mind taking a look before I hire?

**Comment by trjExpensify** [comment] 2024-07-05 14:30
I agree with @parasharrajat, we should take care of this as one. @BrtqKr is working on a [draftPR](https://github.com/Expensify/App/pull/44907) for the [other issue](https://github.com/Expensify/App/issues/44817).

**Comment by BrtqKr** [comment] 2024-07-05 14:48
This could be solved with my PR, since the OldDot message condition covers CHANGEFIELD types as well

**Comment by nkdengineer** [comment] 2024-07-05 14:55
@BrtqKr My proposal also use old dot condition to cover all cases and we can also update the case context menu action in my PR.

**Comment by trjExpensify** [comment] 2024-07-08 10:57
I'd prefer we consolidate in one place, and I favour @BrtqKr's issue/PR as the original author of the PR for this project. 

> I am fine with @nkdengineer solving this issue. We can merge the context menu changes into that PR from @BrtqKr's draft PR.

**Comment by trjExpensify** [comment] 2024-07-08 18:37
Cool, holding this issue. 👍

**Comment by trjExpensify** [comment] 2024-07-10 17:46
PR we're held on is in review.

**Comment by arosiclair** [comment] 2024-07-11 16:03
Not overdue

**Comment by arosiclair** [comment] 2024-07-15 16:32
@trjExpensify should we just close this since it'll get fixed by the [other issue](https://github.com/Expensify/App/issues/44817)?

**Comment by trjExpensify** [comment] 2024-07-15 22:00
Works for me, the PR for that has been deployed.

**Closed by trjExpensify** 2024-07-15 22:00 UTC
Labels: External, Daily, Help Wanted, Bug
