### ISSUE TITLE
[$500] Web - Empty spaces before line break are not removed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27258] opened 2023-09-12 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Type some text in composer, add empty spaces& create a line break
3. Type some text on new line
4. Send the message
5. Observe the empty spaces in the first line by copying the text by selection or editing the message and removing the line break

## Expected Result:
Empty spaces before line break should be removed

## Actual Result:
 Empty spaces before line break are not removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4532c171-012c-4fad-b859-aea5485bc86b

https://github.com/Expensify/App/assets/93399543/a187de6e-95f1-4945-9301-8d6bf2253448

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694220412655639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165a04bcce244ada9</li>
        <li>Upwork Job ID: 1701603680673042432</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-09-12 18:34
@flaviadefaria Looks like I was incorrectly double assigned here by the `external` label. We are discussing fixing this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909). In the meantime, going to un-assign as this doesn't need two BZ assignees.

**Comment by ssshashank** [comment] 2023-09-12 19:44
# PROPOSAL

## Please re-state the problem that we are trying to solve in this issue.
### Web - Empty spaces before line break are not removed

### What is the root cause of that problem?
[src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L237)
Line 237 in [2163c54](https://github.com/Expensify/App/commit/2163c549de291cfdf305ade59015fda1dd34fc3f)

> trim() method in JavaScript is designed to remove leading and trailing whitespace characters, such as spaces and tabs, but it does not remove whitespace characters within the middle of a string or before line breaks (newlines). 

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L237

> And this issue I have already implemented in my chat app

```JS
socket.emit("sendMessage", {
    content: message?.replace(/\s+\n/g, "\n").trim(),
    chatID: selectedChat?._id,
});
```

### What changes do you think we should make in order to solve the problem?
> Replace line 237 with following line:

```JS
const trimmedComment = commentRef.current.replace(/\s+\n/g, '\n').trim();
```

**Comment by ssshashank** [comment] 2023-09-12 19:50
> # PROPOSAL
> ## Please re-state the problem that we are trying to solve in this issue.
> ### Web - Empty spaces before line break are not removed
> ### What is the root cause of that problem?
> [src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L237) Line 237 in [2163c54](https://github.com/Expensify/App/commit/2163c549de291cfdf305ade59015fda1dd34fc3f)
> 
> > trim() method in JavaScript is designed to remove leading and trailing whitespace characters, such as spaces and tabs, but it does not remove whitespace characters within the middle of a string or before line breaks (newlines).
> 
> https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L237
> 
> > And this issue I have already implemented in my chat app
> 
> ```js
> socket.emit("sendMessage", {
>     content: message?.replace(/\s+\n/g, "\n").trim(),
>     chatID: selectedChat?._id,
> });
> ```
> 
> ### What changes do you think we should make in order to solve the problem?
> > Replace line 237 with following line:
> 
> ```js
> const trimmedComment = commentRef.current.replace(/\s+\n/g, '\n').trim();
> ```

> Contributer Details
>
>Expensify account email:- shekharshashank97@gmail.com
>Upword Profile Link:- https://www.upwork.com/freelancers/~01e92101ac60dd2cf0

**Comment by Antasel** [comment] 2023-09-14 01:28
# Proposal
### Please re-state the problem that we are tryng to solve in this issue.
Spaces before line break are not removed

### What is the root cause of that problem?
Markdown parser's newline rule is not covering the case.

### What changes do you think we should make in order to solve the problem?
We need to add a tweak([ ]*) on newline rule's regex https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L218
after fix, will be as following:
```
            {
                name: 'newline',
                regex: /[ ]*\r?\n/g,
                replacement: '<br />',
            },
```
Along with the amendment on newline rule, we need to fix some original auto test cases to remove spaces before linebreak(`<br />`)

**Comment by flaviadefaria** [comment] 2023-09-15 10:39
@stephanieelliott  I'm going OoO for a week so assigning this to you so that you can move it forward in the meantime. I'll take it back from you once I'm online again.

**Closed** 2023-09-18 18:28 UTC
Labels: External, Daily, Help Wanted, Bug
