### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Login – Expensify changes to Hidden in LHN if login with new Gmail account and reload page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44833] opened 2024-07-04 14:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4694015
**Email or phone of affected tester (no customers):** ponikarchuks+24724@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Choose `Track and Budget Expenses` 
4. Enter your name in Onboarding modal
5. Verify Expensify and Concierge chats present in LHN
6. Reload page

## Expected Result:
Expensify and Concierge chats present in LHN

## Actual Result:
Hidden is name of Expensify and user name/Hidden as a Concierge in LHN, when login with new Gmail account and reload page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/74ca5199-e979-475a-a19d-e2f642d5340d

https://github.com/Expensify/App/assets/51066321/218fb752-8f9d-4649-997c-b784d9257d57

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac469d1b3213174d</li>
        <li>Upwork Job ID: 1810389985506651244</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103078265</li>
<li>dominictb | Contributor | 103078266</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-07-08 19:06
I'm not sure if this can be external - we'll start there.

**Comment by ahmedGaber93** [comment] 2024-07-10 08:27
Reviewing today

**Comment by ahmedGaber93** [comment] 2024-07-11 00:17
@dominictb Thanks for the proposal.
Your proposal works well, but can you please mention the code follow that display 'Hidden' based on participants with explanation if needed in your root cause?

**Comment by ahmedGaber93** [comment] 2024-07-11 05:17
@dominictb's [proposal](https://github.com/Expensify/App/issues/44833#issuecomment-2209236685) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:12
working on the PR - https://github.com/Expensify/App/pull/45369

**Comment by ahmedGaber93** [comment] 2024-07-22 09:57
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40254
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40254/files#r1686288563
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug. Yes
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to NewDot
2. Log in with a new Gmail account
3. Choose Track and Budget Expenses
4. Enter your name in Onboarding modal
5. Verify Expensify and Concierge chats present in LHN
6. Reload page
7. Verify that: Expensify and Concierge chats present in LHN with correct name instead of Hidden

 Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-07-23 19:17
Regression test - https://github.com/Expensify/Expensify/issues/414726

Payouts due on payment day:

- [ ] Contributor: $250 @dominictb (Upwork offer - https://www.upwork.com/nx/wm/workroom/37820150/overview)
- [ ] Contributor+: $250 @ahmedGaber93 (Upwork offer - https://www.upwork.com/nx/wm/workroom/37789064/overview)

**Comment by Christinadobrzyn** [comment] 2024-07-24 19:20
Payment day - payment summary here - https://github.com/Expensify/App/issues/44833#issuecomment-2246105763

Closing this as complete!

**Closed by Christinadobrzyn** 2024-07-24 19:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
