### ISSUE TITLE
[Hold for payment 2024-05-30][$250] Deleted message disappear for a moment when transistioning from offline to online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#39218] opened 2024-03-28 23:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1711665611722399?thread_ts=1711571474.268739&cid=C01GTK53T8Q

## Action Performed:

1. Go offline
2. Send a message
3. Reply to the message
4. Delete the message you sent in (2)
5. Come back online

## Expected Result:
While waiting for the network request to process deleted message should appear `strikethrough` and then `deleted message` should appear

## Actual Result:
While network request from offline to online processes, the message deleted from step 2 will disappear rather than showing [Deleted Message]. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b4b082efdd47324</li>
        <li>Upwork Job ID: 1795973516571975680</li>
        <li>Last Price Increase: 2024-05-30</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2024-03-29 01:47
Yeah if this is reproducible in both this is not a blocker.

**Comment by sonialiap** [comment] 2024-03-29 09:39
Is this a fire? Does it need to be hourly?

**Comment by sonialiap** [comment] 2024-03-29 10:02
Since this is not a blocker, moving to Daily

**Comment by FitseTLT** [comment] 2024-04-01 21:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted message disappear for a moment when transistioning from offline to online

### What is the root cause of that problem?
In here
https://github.com/Expensify/App/blob/99cc0b6f34c477dee40934b0ffb294e5dde1f58a/src/libs/actions/Report.ts#L1315-L1316
We haven't included `ADD_COMMENT` when the report action is `isThreadParentMessage` so as we created the report action offline (`ADD_COMMENT`) the `DELETE_COMMENT` of the parent message is getting canceled when going online so the `isDeletedReportAction` is being reset to `false` and as the `message.html` is empty it will disappear and not displayed
### What changes do you think we should make in order to solve the problem?

We need to add `ADD_COMMENT` for parent messages too here
https://github.com/Expensify/App/blob/99cc0b6f34c477dee40934b0ffb294e5dde1f58a/src/libs/actions/Report.ts#L1315-L1316
```
isDeletedParentAction
                        ? [WRITE_COMMANDS.ADD_COMMENT, WRITE_COMMANDS.UPDATE_COMMENT]
```
### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2024-04-03 13:23
@shubham1206agra what do you think of the above proposal?

**Comment by roryabraham** [comment] 2024-04-03 18:40
putting this on HOLD for https://github.com/Expensify/App/issues/39432, as there's a good likelihood this will be fixed over there

**Comment by bernhardoj** [comment] 2024-04-05 06:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted thread parent message disappears when go online instead of showing [Deleted message]

### What is the root cause of that problem?
In ReportActionsList, we are filtering out any action that has a pending action of DELETE.
https://github.com/Expensify/App/blob/b0a50cbaf487fa4e2da9e41c3bd912dc353af863/src/pages/home/report/ReportActionsList.tsx#L188-L194

It's not happening while offline because we include `isOffline` condition on the filter logic. The filter was first introduced in https://github.com/Expensify/App/pull/31670 and the filtered report actions were previously used only in this `useEffect`.
https://github.com/Expensify/App/blob/b0a50cbaf487fa4e2da9e41c3bd912dc353af863/src/pages/home/report/ReportActionsList.tsx#L218-L229

But after the comment linking, we add `ReportActionsUtils.shouldReportActionBeVisible` condition and use it to render the list items too. We add `ReportActionsUtils.shouldReportActionBeVisible` because the report actions from the report screen include all actions.
https://github.com/Expensify/App/blob/b0a50cbaf487fa4e2da9e41c3bd912dc353af863/src/pages/home/ReportScreen.tsx#L707
https://github.com/Expensify/App/blob/b0a50cbaf487fa4e2da9e41c3bd912dc353af863/src/libs/ReportActionsUtils.ts#L609-L619

### What changes do you think we should make in order to solve the problem?

First of all, whether we use `sortedVisibleReportActions` to render the list or not, the first filter condition is not complete
`(isOffline || reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || reportAction.errors)`

because we don't consider the case for deleted parent action (`isDeletedParentAction`).

So, my suggestion is to include `ReportActionsUtils.isDeletedParentAction(reportAction)` condition.
```diff
-(isOffline || reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || reportAction.errors)
+(isOffline || ReportActionsUtils.isDeletedParentAction(reportAction) || reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || reportAction.errors)
```

This is enough, but if we see the above condition, it's similar to `shouldReportActionBeVisible`.
https://github.com/Expensify/App/blob/b0a50cbaf487fa4e2da9e41c3bd912dc353af863/src/libs/ReportActionsUtils.ts#L500-L502

The main difference is, `shouldReportActionBeVisible` includes all action with pending action of DELETE. I'm thinking of updating `shouldReportActionBeVisible` to include pending action of DELETE only while offline so we don't need to use the first condition, but I'm not sure because `shouldReportActionBeVisible` is being used in many places and I don't know what regression would wait us.

**Comment by bernhardoj** [comment] 2024-04-05 16:43
Sure, will do that tomorrow

**Comment by bernhardoj** [comment] 2024-04-08 06:19
shouldReportActionBeVisible usage
- ReportActionsList - SAFE
- extractAttachmentsFromReport - SAFE
- SidebarUtils - SAFE
- OptionsListUtils - SAFE
- shouldReportActionBeVisibleAsLastAction - SHOULD BE SAFE
There are a lot of usages of shouldReportActionBeVisibleAsLastAction and I haven’t check them one by one, but If I read the logic, the output shouldn’t change. Why?

If we proceed to filter out a pending delete action while online in shouldReportActionBeVisible, then the output of new shouldReportActionBeVisible will differ from the current logic in the online case. 

Now, here is the logic of shouldReportActionBeVisibleAsLastAction

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/libs/ReportActionsUtils.ts#L530-L534

Notice that the logic checks for deleted action, but not deleted parent action, doesn't matter whether online or offline. Let's say we pass a report action with a pending action of DELETE while online with the new logic of shouldReportActionBeVisible. shouldReportActionBeVisible will return false, and `!(isDeletedAction(reportAction) && !isDeletedParentAction(reportAction))` will also return false.

If we use the current logic of shouldReportActionBeVisible, shouldReportActionBeVisible will return true, and `!(isDeletedAction(reportAction) && !isDeletedParentAction(reportAction))` will still return false, so the output of shouldReportActionBeVisibleAsLastAction is the same between new and current shouldReportActionBeVisible usage.

- - getLastVisibleAction
- - - ReportActionsUtils.getLastVisibleMessage
- - - - ReportUtils.getLastVisibleMessage
- - - - ReportUtils.shouldReportBeInOptionList
- - - - SidebarUtils.getOptionData
- - - - IOU.deleteMoneyRequest
- - - - IOU.deleteTrackExpense
- - - - Report.addActions
- - - - Task.deleteTask
- - - ReportUtils.getLastVisibleMessage
- - - - Report.deleteReportComment
- - - ReportUtils.getPolicyExpenseChatName
- - - IOU.deleteMoneyRequest
- - - IOU.deleteTrackExpense
- - - Report.addActions, Report.deleteReportComment, Report.editReportComment
- - - Task.deleteTask
- - getLastMessageTextForReport (for LHN/options last message)
- - doesReportHaveVisibleActions - SAFE
- - - Task.deleteTask - SAFE
- getSortedReportActionsForDisplay (if shouldIncludeInvisibleActions is false)
- - [LHNOptionsList](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/components/LHNOptionsList/LHNOptionsList.tsx#L117-L126) - NOT SURE

Even though most of them are SAFE, I have another concern. Because the new logic of shouldReportActionBeVisible depends on network status (offline/online), it means we need to pass it from the param and that requires a lot of changes. Also, how do we subscribe to network status if shouldReportActionBeVisible is used inside an Onyx callback?

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/libs/SidebarUtils.ts#L28-L42

**Comment by sonialiap** [comment] 2024-04-09 13:40
Are we still holding for https://github.com/Expensify/App/issues/39432 or are we working on this issue? Asking so that I can update the title appropriately

**Comment by iwiznia** [comment] 2024-04-11 20:36
I think so

**Comment by roryabraham** [comment] 2024-04-15 16:53
This should remain on HOLD for now

**Comment by bernhardoj** [comment] 2024-04-16 11:54
It's not related to https://github.com/Expensify/App/issues/39432, so we don't need to hold.

**Comment by roryabraham** [comment] 2024-04-18 01:09
My mistake - @shubham1206agra and @bernhardoj are correct, and I got my wires crossed confusing this with another issue.

**Comment by roryabraham** [comment] 2024-04-22 22:27
next step - waiting for @bernhardoj to open a PR

**Comment by bernhardoj** [comment] 2024-04-23 12:09
Sorry for the delay, PR is ready for review

cc: @shubham1206agra

**Comment by roryabraham** [comment] 2024-05-30 00:19
PR was [deployed to prod](https://github.com/Expensify/App/pull/40781#issuecomment-2125961341) a week ago. Ready to pay.

**Comment by sonialiap** [comment] 2024-05-31 11:12
Payment summary:

- @bernhardoj $250 - offer sent
- @shubham1206agra $250 - offer sent

**Comment by sonialiap** [comment] 2024-05-31 12:07
@shubham1206agra update :)

**Comment by sonialiap** [comment] 2024-05-31 13:56
paid ✔️

**Closed by sonialiap** 2024-05-31 13:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
