### ISSUE TITLE
[$500] Emoji picker - There is a noticeable lag with the emoji picker search input animation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33873] opened 2024-01-03 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Click on the emoji picker in the composer 
3. Observe the lag of the "Search" label input animation 

## Expected Result:
The search input label shouldn't have a noticeable lag. 

## Actual Result:
There is a noticeable lag as the search input label animates 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/16232057/bed08f3b-c9da-4913-b97e-2dab01b0a419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a89f9bc9b6b84d8</li>
        <li>Upwork Job ID: 1742577251837038592</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28084092</li>
<li>aimane-chnaif | Contributor | 28084093</li>
<li>bernhardoj | Contributor | 28088325</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2024-01-05 19:44
Commented in the linked issue, @aimane-chnaif & @bernhardoj let me know if I need to assign yah!

**Comment by trjExpensify** [comment] 2024-01-05 19:54
Cool, once @bernhardoj comments here I'll co-assign as well.

**Comment by bernhardoj** [comment] 2024-01-06 04:04
Umm, I think @aimane-chnaif missed my comment [here](https://github.com/Expensify/App/pull/33690#issuecomment-1876900946) 😅 

It shouldn't be reproducible anymore (at least from my testing).

**Comment by trjExpensify** [comment] 2024-01-08 11:24
Assigning you in the meantime to keep track of it!

**Comment by bernhardoj** [comment] 2024-01-17 17:36
This isn't reproducible anymore

**Comment by bernhardoj** [comment] 2024-01-17 17:52
The closing looks fine on your video. It closes instantly.

https://github.com/Expensify/App/assets/50919443/2e2e67e8-528d-4d78-a8c3-ad499cf6a3a3

> Label floating animation is super slow

Maybe we should update the OP to mention this one. From my testing, removing the flashlist fixes the issue which means the emoji list takes too much resources as it need to renders 1900+ emojis.

**Comment by bernhardoj** [comment] 2024-01-17 17:58
Well, it's actually hard to notice from the video because there are no ripples when clicking 😅, but I don't feel the delay when closing it.

**Comment by trjExpensify** [comment] 2024-01-17 21:00
Yep, that's noticeable for me as well. Updated the OP! Have asked @muttmuure about whether we drop this under the #newdot-performance umbrella. 

https://github.com/Expensify/App/assets/16232057/6f492b33-0729-41a0-986f-cc95f1958b72

**Comment by trjExpensify** [comment] 2024-01-29 20:12
So to clarify guys, @bernhardoj isn't fixing this issue? We need to remove the assignment and add `Help wanted` if so!

**Comment by trjExpensify** [comment] 2024-01-29 20:38
Donezo!

**Comment by trjExpensify** [comment] 2024-01-31 18:02
Don't think this needs to come internal. @muttmuure are we handing these performance issues out to a pool of specific peeps as well, perhaps?

**Comment by muttmuure** [comment] 2024-02-05 13:44
@TMisiukiewicz @adhorodyski this might be a flashlist migration bug - do you mind confirming?

**Comment by TMisiukiewicz** [comment] 2024-02-05 14:16
@muttmuure hmm I think it _might_ be related to some changes in the codebase that we made during the migration. We were refactoring the code to reduce the diff between web and mobile so there is a possibility that some resource-consuming operation was introduced there. Definitely needs further investigation.

**Comment by trjExpensify** [comment] 2024-02-05 14:48
@TMisiukiewicz, is it okay if I assign this to you to look into/distribute at Callstack if needs be? Thanks!

**Comment by gedu** [comment] 2024-02-05 16:01
I am from Callstack - expert contributor I would like to work on this

**Comment by gedu** [comment] 2024-02-06 19:18
Still looking into this, I'm doing some simplification, merging some rerenders, but still seeing some lags

**Comment by gedu** [comment] 2024-02-08 09:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When opening the Emoji picker dialog, the search emoji input gets focused and the placeholder is animated to a title. That animation is laggy.

### What is the root cause of that problem?

When the Emoji picker dialog is open there are 2 animations happening, the disableLabel and the activateLabel at the TextInput component. The first one, it is to animate from title to placeholder, and the second one is from placeholder to title. Because of those 2 animation happening in parallel, the SearchInput looks laggy.

### What changes do you think we should make in order to solve the problem?

In EmojiPickerMenu/index.js, we have to add the `forceActiveLabel`  to the TextInput component.

https://github.com/Expensify/App/assets/1676818/13e172db-dc90-42f6-a47b-3572025dfda4

@trjExpensify

**Comment by gedu** [comment] 2024-02-09 13:27
@aimane-chnaif 
You are right, I though the forceActiveLabel was just for the first frame, when I checked was working like that, but seems that it deactivate completely the placeholder state.

Yeah, I was talking internally about the amount of objects being loaded, it is almost 2k, and asked if all of them should be loaded, and they told me yes. I will check making kind of a fake pagination, will update my proposal soon

**Comment by trjExpensify** [comment] 2024-02-12 12:04
Any luck with that update, @gedu?

**Comment by gedu** [comment] 2024-02-12 14:15
@trjExpensify Yes, tried the pagination but wasn't good for the Emoji shortcut bar. So digging into the source code, found that it is based on another OSS RecyclerListView, where I found the `drawDistance` prop can help us, it reduce the amount to render the items. Now the default is 2k, so it renders all the emojis in one cycle, so setting to 300 (after some testing) found it was the most optimal number.

Proposal
Please re-state the problem that we are trying to solve in this issue.
When opening the Emoji picker dialog, the search emoji input gets focused and the placeholder is animated to a title. That animation is laggy.

What is the root cause of that problem?
FlashList tries to render certain amount of components at the end of the cycle, which by default is set to 2k. That is the amount of emojis we load. 

What changes do you think we should make in order to solve the problem?
There is a prop to change it `drawDistance`, setting it to 300 (after some tests it is a good number, 600 starts lagging and show more blank spaces, more of 800 the lag is more visible).
```
           <FlashList
                    ref={forwardedRef}
                    keyboardShouldPersistTaps="handled"
                    data={data}
                    drawDistance={300}
                    ..... />
```

https://github.com/Expensify/App/assets/1676818/4e6af6cc-f412-4f55-a3e0-6c149e78dc07

**Comment by gedu** [comment] 2024-02-14 09:09
@trjExpensify Friendly ping, wdyt about the new "proposal"?

**Comment by gedu** [comment] 2024-02-14 09:51
@aimane-chnaif could be because for native the default number is 250 and not 2k like web

**Comment by gedu** [comment] 2024-02-14 09:53
we can use 250, instead of 300 so all the platforms use the same, or we can create a config file and change the number depending on the Platform

**Comment by Beamanator** [comment] 2024-02-14 10:23
I also like @gedu 's proposal 👍  they're already assigned so please create the PR when ready! 😅

**Comment by gedu** [comment] 2024-02-14 10:33
> > we can use 250, instead of 300 so all the platforms use the same, or we can create a config file and change the number depending on the Platform
> 
> If 250 is thoroughly tested on all platforms, I agree with it without having platform config.

Cool, I will create a CONST value for it

**Comment by gedu** [comment] 2024-02-14 14:28
@aimane-chnaif @Beamanator PR created: https://github.com/Expensify/App/pull/36486

**Comment by trjExpensify** [comment] 2024-03-19 13:22
Ah, the automation didn't run for some reason. 

Payment summary as follows: 

- $500 to @aimane-chnaif for the C+ review
- @gedu is from CallStack, payment will be handled elsewhere. 

Paid you, Aimane. Closing!

**Closed by trjExpensify** 2024-03-19 13:22 UTC
Labels: Reviewing, External, Weekly, Bug
