### ISSUE TITLE
VBA - Start over button is not responding when connecting a bank account - reported by: @puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8497] opened 2022-04-05 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with expensifail account
3. Go to Settings- Performance
4. Enable the Staging Server
5. Go to any Workspace and select connect bank account - connect through the Plaid
6. Use Wells Fargo Bank account
6. User name - user_good/ pass_good
7. Select Saving account
8. Fill out all information on Company information page
9. Click Save and Continue
10. Close the modal
11. Go back to Workspace - Connect bank account
12. Click Start over button

## Expected Result:
User is taken to Connect bank account page with plaid and manual options

## Actual Result:
Start over button is not responding after didn't finish to set up VBA flow

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** v1.1.51-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161850980-e37af3d1-86a4-486a-bf5c-e039fdbcaf13.mp4

https://user-images.githubusercontent.com/43996225/161850997-f6bd970d-d6c6-4c37-8916-882790f6570e.mp4

**Upwork job link:** https://www.upwork.com/jobs/~015fed310b700cfa88

**Issue reported by:** ~Applause~ @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648737170322789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-04-06 20:58
Errors in the console when reproducing this workflow:
![Screen Shot 2022-04-06 at 4 40 11 PM](https://user-images.githubusercontent.com/7277067/162069611-d4367f93-49ec-4e29-b406-036b5f290f4f.png)

![Screen Shot 2022-04-06 at 4 55 07 PM](https://user-images.githubusercontent.com/7277067/162069619-6e4581fb-3445-4649-88b2-fe61e1ef9438.png)

**Comment by Puneet-here** [comment] 2022-04-07 10:22
Hi, I had reported this on channel https://expensify.slack.com/archives/C01GTK53T8Q/p1648737170322789

**Comment by michaelhaxhiu** [comment] 2022-04-11 21:34
Job here posted - https://www.upwork.com/jobs/~015fed310b700cfa88

**Comment by michaelhaxhiu** [comment] 2022-04-19 21:56
Price doubled to $500

**Comment by allroundexperts** [comment] 2022-04-25 16:19
Not reproducible locally. The plaid link token never gets generated. The API throws error.

**Comment by michaelhaxhiu** [comment] 2022-04-25 17:32
@allroundexperts hm interesting - you cannot reproduce the behavior in the video that's attached by @kavimuru?

**Comment by allroundexperts** [comment] 2022-04-25 17:46
No. On local host, the plaid link token api call is failing. @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2022-04-25 18:59
@allroundexperts hm something seems to be wrong with your testing steps or maybe your testing environment. I just tested it again firsthand and it's 100% reproducible.

![still a bug son](https://user-images.githubusercontent.com/13206896/165155534-5858f2de-949c-40c5-b722-6096edad993d.gif)

**Comment by allroundexperts** [comment] 2022-04-25 19:26
@michaelhaxhiu Are you testing on local host?

**Comment by allroundexperts** [comment] 2022-04-25 19:47
Seems like CORS error on localhost because plaid requests are using secure expensify url. Is there a way to proxy secure expensify requests? @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2022-04-25 19:54
@allroundexperts I'm testing on staging.expensify.com (not a local VM).

**Comment by michaelhaxhiu** [comment] 2022-04-25 19:55
I'll let @luacmartins answer that 2nd question as I'm not an expert there:
>Is there a way to proxy secure expensify requests?

**Comment by luacmartins** [comment] 2022-04-25 20:06
@allroundexperts There's some info in this [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1639068595427300?thread_ts=1639063796.422900&cid=C01GTK53T8Q). TLDR is that we currently do not have a proxy for that. I believe that testing on the Desktop app should work though.

**Comment by allroundexperts** [comment] 2022-04-25 20:27
@michaelhaxhiu @luacmartins  Plaid recently moved to OAuth for all banks. As such, the `user_good` and `pass_good` isn't valid anymore. We'll need to integrate that before moving to this bug.
https://plaid.com/docs/link/oauth/

https://user-images.githubusercontent.com/30054992/165169340-09d982c0-5040-4300-89fe-2439ff57d243.mp4

**Comment by luacmartins** [comment] 2022-04-25 21:08
@allroundexperts I believe that's because contributors hit our staging API and real credentials must be used there. There's a thread about it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1649949322758349). Since this might be a blocker for contributors, I'll make this an Internal issue. Thanks for the interest!

@michaelhaxhiu can you pay the reporting bonus and remove the Upwork job? I'm making this internal. Thank you!

**Comment by michaelhaxhiu** [comment] 2022-04-26 15:38
@Puneet-here can you please apply for the job here?  I updated the amount to $250 to pay you the reporting bonus to you when this is fixed/deployed to production.

**Comment by neil-marcellini** [comment] 2022-04-27 22:53
Was this working at one point? If so this is a regression and we should look into which PR caused it and have the C+ or internal engineer do an [RCA](https://stackoverflow.com/c/expensify/questions/12158).

**Comment by luacmartins** [comment] 2022-04-27 22:59
Yea, I believe this is a regression. I spent quite a bit of time today looking for the offending PR but got nowhere and decided to move ahead with a fix. We can add it to the RCA spreadsheet and write a RCA if we ever find the cause.

**Comment by michaelhaxhiu** [comment] 2022-04-27 23:00
@neil-marcellini great catch, I think we should try to look into it for the sake of performing an RCA (and thus not repeating this mistake again)

**Comment by michaelhaxhiu** [comment] 2022-04-27 23:00
Oh interesting @luacmartins, sounds like you tried and it wasn't worth the time! Let's take this to slack :)

**Comment by neil-marcellini** [comment] 2022-04-27 23:04
@luacmartins I could imagine it would be hard to find. It could have happened a long time ago and it could be caused by many areas in the codebase. We should try to create a process for how to search for a regression since it's not always obvious.

**Comment by michaelhaxhiu** [comment] 2022-04-27 23:12
cc'ed you both in a Slack post to discuss this further, as I think it'll apply to future RCAs too. This is a good topic to broach.

**Comment by Puneet-here** [comment] 2022-04-29 17:49
@michaelhaxhiu, I have applied to the job.

**Comment by michaelhaxhiu** [comment] 2022-04-29 18:43
@Puneet-here hired

**Comment by michaelhaxhiu** [comment] 2022-04-29 18:52
Paid.

**Comment by kbecciv** [comment] 2022-08-02 21:25
@michaelhaxhiu QA team experienced the issue with "Start over" button. It is not responding at all. Tested build is 1.1.87.8

https://user-images.githubusercontent.com/93399543/182476200-c2b4837d-cc0f-400c-9ec9-329271447a6a.mp4

**Comment by thienlnam** [comment] 2022-09-27 00:37
Another example of the Start Over button not working https://github.com/Expensify/Expensify/issues/226985#issuecomment-1258818979

**Comment by luacmartins** [comment] 2022-09-27 16:09
I'll get back to this one this week

**Comment by luacmartins** [comment] 2022-10-19 23:43
I'll take a look this week!

**Comment by luacmartins** [comment] 2022-11-02 16:50
I don't think this is an issue anymore. I couldn't reproduce on staging or locally. @kavimuru are you still able to reproduce this issue?

**Comment by joekaufmanexpensify** [comment] 2022-11-02 18:33
The start over button is also working normally for me. I tried several times and it worked each time (including on staging). 

Going to close this for now as it seems like there is no longer anything we need to fix here. Feel free to re-open if anyone is able to reproduce this, or it comes up again!

**Closed by joekaufmanexpensify** 2022-11-02 18:33 UTC
Labels: Engineering, Daily, Internal, Bug
