### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] IOS - The title field is cleared when the Confirm task button is pressed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22078] opened 2023-07-02 22:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to New Expensify on an iOS handset 
2. Click on + icon
3. Click on assign task
4. Enter title and click on next
5. Enter an assignee
6. Click on Confirm task

## Expected Result:
The title field should not be cleared

## Actual Result:
The title field is cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e61edf84-3ccd-45d7-96ca-9b3d0296135c

https://github.com/Expensify/App/assets/93399543/521188e9-515e-4c67-aafb-2ec63bf3eaba

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688216349574539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is% 3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1a312f3e2545b22</li>
        <li>Upwork Job ID: 1676161673601695744</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-07-04 11:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - The title field is cleared when the Confirm task button is pressed

### What is the root cause of that problem?
Before dismissing modal `clearOutTaskInfo()` is called, and dismissing modal is not happening instantly, that's why we can see result of `clearOutTaskInfo` function
### What changes do you think we should make in order to solve the problem?
We should call `clearOutTaskInfo` function after `dismissModal` happens
https://github.com/Expensify/App/blob/1b958b808a07fccb582ad73fa6ead06db675c6db/src/libs/actions/Task.js#L183-L185

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2023-07-06 07:27
@0xmiroslav what do you think about these two proposals ^^

**Comment by laurenreidexpensify** [comment] 2023-07-10 09:28
@0xmiroslav bump on proposal review, thanks

**Comment by robertjchen** [comment] 2023-07-17 10:12
Awaiting updated proposal w/ all occurrences where the similar issue happens per: https://github.com/Expensify/App/issues/22078#issuecomment-1637138921

**Comment by robertjchen** [comment] 2023-07-17 12:35
Thanks, let's do this 👍

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:39
Offers sent in Upwork

**Comment by robertjchen** [comment] 2023-07-21 09:48
Agreed, let's proceed with that 👍

**Comment by situchan** [comment] 2023-07-24 05:54
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1690178033848139?thread_ts=1690177499.108059&cid=C02NK2DQWUX, I'd like to take this as C+

**Comment by situchan** [comment] 2023-07-24 18:47
I read through all discussions and also agree with newest solution which fixes both issues. Going ahead PR checklist.

**Comment by situchan** [comment] 2023-07-24 21:11
I'd say https://github.com/Expensify/App/issues/23210 is not a regression from https://github.com/Expensify/App/pull/22983.
Reason: https://github.com/Expensify/App/issues/23210#issuecomment-1648604974

Also, same crash happens on Assignee modal.
Context: https://github.com/Expensify/App/issues/23210#issuecomment-1648606596

So in new [PR](https://github.com/Expensify/App/pull/23342), we're going to fix 3 issues which have different root causes:
- https://github.com/Expensify/App/issues/22078
- https://github.com/Expensify/App/issues/23210
- https://github.com/Expensify/App/issues/23294

cc: @robertjchen

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:40
reviewing payments today

**Comment by laurenreidexpensify** [comment] 2023-07-31 17:02
Ah okay so just catching up for my own understanding here! 

1. the PR for this issue also fixed https://github.com/Expensify/App/issues/23294
2. Bug reporter payment has already been handled in https://github.com/Expensify/App/issues/23294
3. The automation got confused about payment dates here, but it looks like we've only been on prod for 4 days https://github.com/Expensify/App/pull/23342#issuecomment-1654649105
4. Correct payment date is 2023-08-03

**Comment by robertjchen** [comment] 2023-08-10 14:39
Thanks for organizing all the details, we'll review this! 👀

**Comment by robertjchen** [comment] 2023-08-14 08:43
Still getting around to evaluating this, thanks for everyone's patience! 🙏

**Comment by robertjchen** [comment] 2023-08-22 07:39
Appreciate your patience, circling back to this and will respond before end of day.

**Comment by robertjchen** [comment] 2023-08-23 09:35
Okay, my analysis on the situation is:

- This bug report here in came in earlier than the one in https://github.com/Expensify/App/issues/23294 , but we did not catch the duplicate report and paid the original reporter in the other issue. That is unfortunate, but is also on us, so we should pay the reporter here:
    - `$250` to @aman-atg 

- The original PR: https://github.com/Expensify/App/pull/22983 was merged within 3 business days and [didn't cause a regression](https://github.com/Expensify/App/issues/22078#issuecomment-1648618868) (though it was mistakenly reverted under incorrect assumptions) so that's:
    - `$1000 + $500 bonus` to @dukenv0307 
    - `$1000 + $500 bonus` to C+ reviewer @0xmiroslav 

- For the fix https://github.com/Expensify/App/pull/23342 My view here is that the PR is basically a re-instatement of the original reverted changes with related causes. However, I still think a discretionary bounty should still be paid out here given the efforts and mixup:
   - https://github.com/Expensify/App/issues/23210 no additional payment per [the comment here](https://github.com/Expensify/App/issues/23210#issuecomment-1681212598) 
    - https://github.com/Expensify/App/issues/23294 this [comment](https://github.com/Expensify/App/issues/23294#issuecomment-1645060621) points out the overlap.
        - `$500 discrectionary bonus` to @dukenv0307 

cc: @laurenreidexpensify for final confirmation and next steps! 👍

**Comment by situchan** [comment] 2023-08-23 09:43
@robertjchen what about me for reviewing 2nd [PR](https://github.com/Expensify/App/pull/23342)? I took over based on https://github.com/Expensify/App/issues/22078#issuecomment-1647260102

**Comment by robertjchen** [comment] 2023-08-23 09:45
@situchan Updated my comment! 👍

**Comment by laurenreidexpensify** [comment] 2023-08-27 09:27
Payment Summary: 

- $250 - Bug Report @aman-atg  - payment issued in Upwork (original job post) 
- $1500 - Contributor - @dukenv0307 - payment issued in Upwork for job (original job post) 
- $1500 - C+ review, offer sent to @0xmiroslav in [Upwork](https://www.upwork.com/en-gb/ab/applicants/1695727233299275776/job-details) (new job post) 
- $1000 - discretionary bonus, offer sent to @dukenv0307 in Upwork (new job post)
- $1000 - discretionary bonus, offer sent to @situchan in Upwork (new job post) 

@0xmiroslav can you confirm the regression checklist steps?

**Comment by laurenreidexpensify** [comment] 2023-08-29 11:23
@0xmiroslav offer sent 👍

**Comment by laurenreidexpensify** [comment] 2023-08-29 11:29
Payments have all been issued, closing.

**Closed by laurenreidexpensify** 2023-08-29 11:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
