### ISSUE TITLE
[$250] Workflows - Back button on workspace editor reopens Workflows after adding workflow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47458] opened 2024-08-14 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Precondition:
- Workspace is under Control plan.
- Workspace has a few members.

1. Launch New Expensify app.
2. Go to workspace settings > Workflows.
3. Tap Add approval workflow.
4. Go through the setup and tap Add workflow on the confirmation page.
5. On Workflows page, tap on app back button.
6. On workspace editor page, tap on app back button.

## Expected Result:
App will return to workspace list.

## Actual Result:
App reopens Workflows page when tapping on back button on workspace editor page after adding workflow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a43ae080-dd69-48ef-9c4a-9fae59da6542

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122ee0f611f968eaa</li>
        <li>Upwork Job ID: 1824121720115141860</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by izarutskaya** [comment] 2024-08-14 20:01
We think this issue might be related to the #wave-control

**Comment by izarutskaya** [comment] 2024-08-14 20:02
Production 

https://github.com/user-attachments/assets/8f97153b-0c67-4275-8200-4aae79249421

**Comment by tgolen** [comment] 2024-08-14 20:39
This feature is behind a beta so I am removing the feature flag cc @blazejkustra @DylanDylann

**Comment by bernhardoj** [comment] 2024-08-15 03:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After submitting a new approval workflow, pressing back from the workspace reopens the workflow page again.

### What is the root cause of that problem?
When we are creating a new approval workflow, we go from selecting members step -> selecting approver step. At this point, the rhp nav stack is: [select member, select approver]. When we go next again, both screens are removed and replaced with the confirmation page.

https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L186-L188

So, the confirm page will be the only one in the RHP stack. When we submit the confirmation, the app will call goBack with a fallback to the workflow page.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsCreatePage.tsx#L47-L48

Because the confirm page is the only screen in the RHP, the confirm page will be replaced with the fallback route, so there is a duplicate workflow page in the nav stack.

This happens too if we refresh the page while on the confirm page.

### What changes do you think we should make in order to solve the problem?

We should remove the fallback route, so till be just `goBack()`.

It's the same as we did when editing the approval.
https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L53-L54

**Comment by DylanDylann** [comment] 2024-08-16 02:45
@blazejkustra it seems this relates to the navigation bug that we discussed before. Should we want to take over this one with a navigation bug [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1723654979036929?thread_ts=1723491433.389249&cid=C06ML6X0W9L)

**Comment by DylanDylann** [comment] 2024-08-16 04:00
@shubham1206agra @bernhardoj You mean that we should remove naviagte function and only use goBack, right?

**Comment by DylanDylann** [comment] 2024-08-16 04:36
> When we are creating a new approval workflow, we go from selecting members step -> selecting approver step. At this point, the rhp nav stack is: [select member, select approver]. When we go next again, both screens are removed and replaced with the confirmation page.

@tgolen @blazejkustra I believe that this bug has the same RCA as the navigation bug that we discussed in [previous PR](https://github.com/Expensify/App/pull/46798)

 @blimpich @shubham1206agra Maybe the navigation in the approval workflow feature will be updated soon and this bug will no longer reproduce. Let's wait for a thought from @blazejkustra

**Comment by blazejkustra** [comment] 2024-08-19 07:13
@DylanDylann I agree with Dylan, let's wait with this issue for now.

**Comment by isabelastisser** [comment] 2024-08-19 15:30
On hold!

**Comment by DylanDylann** [comment] 2024-08-21 08:34
Hold: https://github.com/Expensify/App/issues/47697

**Comment by blazejkustra** [comment] 2024-08-26 20:45
Should be resolved now with https://github.com/Expensify/App/pull/47845 merged

**Comment by blimpich** [comment] 2024-08-26 22:55
@shubham1206agra @bernhardoj are either of you able to reproduce the issue here?

**Comment by bernhardoj** [comment] 2024-08-27 02:49
It's not reproducible anymore.

**Comment by isabelastisser** [comment] 2024-08-28 01:36
Thanks for confirming, @bernhardoj! Closing this.

**Closed by isabelastisser** 2024-08-28 01:36 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
