### ISSUE TITLE
[$1000] Hover over email sent to conversation shows `mailto` along with email on tooltip

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21597] opened 2023-06-26 18:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat  
2. Send a valid email 
3. Hover over that email
 4. Notice on tooltip it includes `mailto` along with email
## Expected Result: 
On tooltip it should show only email that is being hovered
## Actual Result: 
On hover it includes `mailto` along with email

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (120)](https://github.com/Expensify/App/assets/43996225/1ed2cf29-fd39-425c-8397-1807be623c5f)
![Screenshot 2023-06-21 at 12 10 31 PM](https://github.com/Expensify/App/assets/43996225/c32f244f-712c-47d0-b847-b863ca8f2989)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687329774501019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d088c4f4de02ac77</li>
        <li>Upwork Job ID: 1674430172944875520</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-06-27 10:39
@kavimuru The videos are showing emojis not applying in offline mode, but this issue is about the `mailto:` appearing on hover. I think the videos are not related to the issue, right? Did they get mixed into this by accident? If yes, let's delete them from the post to prevent confusion

**Comment by kavimuru** [comment] 2023-06-27 16:54
@sonialiap My apologies. I have added correct attachments.

**Comment by sonialiap** [comment] 2023-06-29 14:50
Thanks Kavi!

**Comment by shawnborton** [comment] 2023-06-29 16:32
Yeah, this does not seem like a bug to me. We're just showing the url here in the tooltip. Let's close this.

**Comment by narefyev91** [comment] 2023-06-30 08:23
@dhairyasenjaliya @chiragxarora i agree with @shawnborton - there are different workflows - when you open a context menu - we show Copy to clipboard - which mean only copy email (if we will show mailto:test@gmail.com - this will be confusing - because mailto option needs to directly send email using any email provider).
That's why we should separate logic.
In my view - this is not a bug

**Comment by shawnborton** [comment] 2023-07-03 12:25
Okay, going to close this one out.

**Closed by shawnborton** 2023-07-03 12:25 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
