### ISSUE TITLE
[$250] [HOLD for payment 2024-10-24] QBO - Some Customer/projects values are trigger an error that disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50105] opened 2024-10-02 19:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: workspace with connected QBO integration. Classes and Customers/Projects are imported via Import tab. 'Members must tag all expenses' toggle is ON.
1. Go to workspace chat
2. Click + > Submit expense > Manual
3. Enter amount and Merchant > Submit
4. Open expense report
5. Choose Category and Classes values
6. Click on Customers/projects > choose Coke Drink Canada:Big Project or Coke Drink Canada:Test Test

## Expected Result:
Value is applied without error

## Actual Result:
An error 'Customers/Projects no longer valid' briefly appears. Sometimes an error stays until user chose another value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/81218217-f112-4926-b3eb-a523da93e15f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849320215635409078</li>
        <li>Upwork Job ID: 1849320215635409078</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-10-02 19:20
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-02 19:20
We think that this bug might be related to #wave-collect - Release 1

**Comment by kadiealexander** [comment] 2024-10-03 03:39
cc @arosiclair I know you worked on QBO recently!

**Comment by arosiclair** [comment] 2024-10-03 15:31
> cc @arosiclair I know you worked on QBO recently!

Sorry I don't have much info to give on this issue specifically. Seems like a legit bug though.

**Comment by allroundexperts** [comment] 2024-10-07 07:31
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/50105#issuecomment-2390537853) looks good to me. The RCA seems to be correct and the solution makes sense as well. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment] 2024-10-07 15:40
Looks good 👍

**Comment by allroundexperts** [comment] 2024-10-20 22:10
## Checklist
1. https://github.com/Expensify/App/pull/37461/files#r1807953238
2. https://github.com/Expensify/App/pull/37461
3. N/A
4. I think that this is really an edge case, that was specific to QBO integration. As such, we can skip the test here.

**Comment by MonilBhavsar** [comment] 2024-10-21 04:43
I think we should add the tests that uses special tag names with colon inside it, as this bug made to production unnoticed

**Comment by kadiealexander** [comment] 2024-10-24 03:59
@allroundexperts can you share test instructions that test for @MonilBhavsar's case [here](https://github.com/Expensify/App/issues/50105#issuecomment-2425571912)? Thanks!

**Comment by kadiealexander** [comment] 2024-10-24 05:39
Payouts due:

- [ ] Contributor: $250 @Nodebrute  ([offer link](https://www.upwork.com/nx/wm/offer/104567640))
- [ ] Reviewer: $250 @allroundexperts via manual request

Upwork job is [here](https://www.upwork.com/jobs/~021849320215635409078).

**Comment by kadiealexander** [comment] 2024-10-25 05:41
Reassigning to have someone raise a GH to get [these requested testing steps](https://github.com/Expensify/App/issues/50105#issuecomment-2425571912) into testrail once they're written, as I'm heading OOO!

**Comment by bfitzexpensify** [comment] 2024-10-28 18:28
Bump @allroundexperts

**Comment by allroundexperts** [comment] 2024-10-28 21:17
## Regression test

1. Create a workspace, and enable tags + categories.
2. Add a tag, and category named as "test:new:exfy".
3. Submit an expense to the workspace, and select the above create tag and category.
4. Verify that no error occurs and the expense gets submitted successfully.

Do we 👍 or 👎 ?

**Comment by bfitzexpensify** [comment] 2024-10-29 13:32
Looks good to me. Closing this one out - thanks everyone!

**Closed by bfitzexpensify** 2024-10-29 13:32 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2025-02-13 22:00
$250 approved for @allroundexperts
