### ISSUE TITLE
[$250] mWeb - chat - Quote markdown is shown differently while sending and editing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43053] opened 2024-06-04 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4594014
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter >>>>>
4. Note the message after markdown applied
5. Send the message
6. Long press the message and open edit comment

## Expected Result:
Quote markdown must be displayed same while sending and editing

## Actual Result:
Quote markdown is shown differently while sending and editing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4f71bfd-1927-481e-abca-c9cc6877911f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162cb2f380985d8c5</li>
        <li>Upwork Job ID: 1799109600952906182</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment] 2024-06-04 18:30
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-06-10 20:58
@mkhutornyi can you review the proposal above?

**Comment by garrettmknight** [comment] 2024-06-17 12:48
Still awaiting proposals.

**Comment by garrettmknight** [comment] 2024-06-17 12:48
Still awaiting proposals.

**Comment by garrettmknight** [comment] 2024-06-19 19:02
Still awaiting proposals.

**Comment by garrettmknight** [comment] 2024-06-24 20:25
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-06-28 17:52
Still awaiting proposals

**Comment by mvtglobally** [comment] 2024-07-03 15:03
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/f3e0b529-1315-46fa-925a-df06637a61fc

**Comment by garrettmknight** [comment] 2024-07-05 09:29
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-07-08 17:07
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-07-10 16:25
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-07-12 17:18
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-07-15 11:49
Still awaiting proposals

**Comment by garrettmknight** [comment] 2024-07-17 19:21
Still awaiting proposals, also dropping to weekly. I don't think this worth upping the price even if we still want to leave it open to complete.

**Comment by garrettmknight** [comment] 2024-08-05 20:34
No update, still waiting for proposals.

**Comment by mvtglobally** [comment] 2024-08-09 04:24
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment] 2024-08-09 18:00
Will test next week

**Comment by garrettmknight** [comment] 2024-08-12 10:31
Couldn't reproduce either. Closing.

**Closed by garrettmknight** 2024-08-12 10:31 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
