### ISSUE TITLE
IOU - IOU details are broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23202] opened 2023-07-19 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Click to FAB button -> Request money -> Submit a request to any user
4. Open IOU of money request

## Expected Result:
IOU details visible

## Actual Result:
IOU details are broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7b445995-2834-42ac-997e-b53028ae402f

![Bug6134528_image__138_](https://github.com/Expensify/App/assets/78819774/e3bc2a9b-b198-4a49-b23c-bb18ee075aa2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by jasperhuangg** [comment] 2023-07-19 21:38
This seems to be a dupe of https://github.com/Expensify/App/issues/23195, just manifested for IOU Reports, which are a different type of child report.

**Comment by jasperhuangg** [comment] 2023-07-19 21:43
This seems to have been caused by https://github.com/Expensify/App/pull/21406

**Comment by jasperhuangg** [comment] 2023-07-19 21:47
Can't seem to reproduce this on the latest staging build.

**Comment by jasperhuangg** [comment] 2023-07-19 21:49
spoke too soon, looks like it's reproducible, you have to wait a bit for the API request to respond.

**Comment by aldo-expensify** [comment] 2023-07-19 21:50
I'm working on reproducing too

**Comment by aldo-expensify** [comment] 2023-07-19 21:51
Reproduced: 
<img width="851" alt="image" src="https://github.com/Expensify/App/assets/87341702/8145fcd6-d367-467d-9ee3-d20d5f9c8a34">

**Comment by aldo-expensify** [comment] 2023-07-19 22:07
@jasperhuangg you were right about that PR causing the deploy blocker: https://github.com/Expensify/App/pull/21406/files#r1268723347

I'm preparing a fix.

**Comment by aldo-expensify** [comment] 2023-07-19 22:15
I need to confirm if this looks fine:

<img width="1384" alt="image" src="https://github.com/Expensify/App/assets/87341702/5b1cbc86-4ac0-4e4e-9c12-e98c4ce42197">

The list of items is at the bottom, was that changed lately? I can see that in production it looks like this:

<img width="1363" alt="image" src="https://github.com/Expensify/App/assets/87341702/9d2e006c-a4e3-482d-b94c-9baca20cd19f">

**Comment by aldo-expensify** [comment] 2023-07-19 23:01
I'll remove the `DeployBlockerCash` label once we confirm this is fixed in staging.

**Comment by aldo-expensify** [comment] 2023-07-19 23:05
Confirmed that this is working in staging now: 
<img width="1236" alt="image" src="https://github.com/Expensify/App/assets/87341702/36cecb41-6813-4c8c-b15b-f7271828de2d">

**Closed** 2023-07-19 23:05 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
