### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Dev: Android -  cursor on amount numpad bouncing between digits

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22799] opened 2023-07-13 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate through the app
2. Click on request money tab
3. Type the amount quickly

## Expected Result:
The cursor should not bounced

## Actual Result:
Cursor on amount numpad bouncing between digits

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.39.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b0ea8196-be13-4e63-86bf-37f42c5cd9b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakshixwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689165268700989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108bc58e45a52924e</li>
        <li>Upwork Job ID: 1681657434070409216</li>
        <li>Last Price Increase: 2023-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 25954008</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-07-19 13:28
These cursor issues can be be tricky, though I'm going to triage to see what solutions the community can come up with.

**Comment by robertKozik** [comment] 2023-07-19 18:17
It's on my radar, waiting for proposals!

**Comment by ygshbht** [comment] 2023-07-23 13:17
rayane-djouah's solution looks good. I also have an alternative solution

**Comment by ygshbht** [comment] 2023-07-23 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor bouncing between digits on the amount numpad in the Android application.

### What is the root cause of that problem?
The issue originates from multiple calls to the `setSelection `function when a user inputs an amount. This is especially prevalent in the following component:

https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/iou/steps/MoneyRequestAmountPage.js#L441-L455

When the user types, the `setNewAmount `function updates both the `amount `and the `selection`. However, updating `amount `seems to inadvertently trigger the `onSelectionChange `event, which results in the cursor bouncing around due to a race condition. This is especially noticeable when the user types quickly.

https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/iou/steps/MoneyRequestAmountPage.js#L304-L319

### What changes do you think we should make in order to solve the problem?
I propose to limit the invocation of `onSelectionChange `event only to when the selection is altered by the user directly (i.e., using finger gestures), and not programmatically.

This can be achieved by introducing a new state variable, `shouldUpdateSelectionNaturally`. We will set this variable to true when the user taps on the input field, and to false when they use the numeric keys. Then, we will adjust the `onSelectionChange `event handler in the following way:

```
onSelectionChange={(e) => {
    if (!shouldUpdateSelection || !shouldUpdateSelectionNaturally) {
        return;
    }
    setSelection(e.nativeEvent.selection);
}}
```
This change will ensure that the `setSelection `function is called only when the user manually alters the selection, preventing the cursor from bouncing between digits when the user types quickly. Minor adjustments can be made to ensure that the new solution works seamlessly in all platforms.

Result: 

https://github.com/Expensify/App/assets/65986357/d9313c75-5630-4e33-b36b-8f5593497f84

**Comment by robertKozik** [comment] 2023-07-24 20:47
Hi all! I'll get familiar with this issue and will come back to you to adress your proposals

**Comment by JmillsExpensify** [comment] 2023-07-24 21:55
Thank you!

**Comment by robertKozik** [comment] 2023-07-26 07:35
Hi again. Thank you all for your proposals! Both of them address the root issue of it. We are currently have selection custom handled on every input and I would keep it as it is. Due to that I'll go to with the @rayane-djouah proposal. Using debounce is common f.e. inside the `ReportActionCompose.js` so in my opinion using debounce in the amount input can be a good call too.

I would select @rayane-djouah [proposal](https://github.com/Expensify/App/issues/22799#issuecomment-1646607842)

🎀 👀 🎀 C+ reviewed

**Comment by ygshbht** [comment] 2023-07-26 08:31
Thanks, @robertKozik. I can see where you're coming from, and I agree to a great extent. Debouncing indeed is a recognized technique to handle frequent function calls and has valid uses in many situations.

However, I do have some concerns about the application of debouncing in this specific context. **My primary concern is that this issue comes into play when a user types quickly. With debouncing, it seems we're effectively slowing down user typing, instead of addressing the underlying problem.** This could also introduce a lag in user input, potentially giving an impression of a less responsive app.

Moreover, considering the asynchronous nature of JavaScript, and particularly React state updates, there's a possibility that race conditions could still occur if these asynchronous events take longer than the debounce delay. This could potentially still allow for the cursor bouncing issue to occur, albeit perhaps less frequently. And to improve this, we would need to increase the debounce time, which would, in turn, make the app feel less responsive.

**Also, in my proposal, there is no prevention of any custom selections and it does not interfere with existing functionality while solving the same problem at hand.**

Indeed, the application of debouncing in `ReportActionCompose.js` probably aims at limiting unnecessary updates and backend calls while the user is still typing. It works efficiently in that scenario because it helps reduce redundant operations. However, I believe the **BigNumberPad component scenario to be a bit different. In ReportActionCompose.js, debouncing is applied to the entire user input, which is reasonable as it pertains to a complete chunk of text. On the contrary, in the BigNumberPad component, we add one digit at a time with each state update. This implies a more granular operation, with each keystroke resulting in an individual update rather than a batched update of multiple digits at once. Rather than adding all the digits at once at the end, only the last entered digit would be added by debouncing.**

If possible, I'd love to understand more about your perspective on these points.

**Comment by robertKozik** [comment] 2023-07-26 13:55
Hi @ygshbht thank you for your message. Your argments are valid, and to be honest both proposals are good and I had hard time with deciding on one. Finally I go for the debounce one due to:
1. It's straightforward and simple for implementation as doesn't change any of existing code (only debounces it) so this solution has almost no chance of causing regression
2. I've personally checked the performance on the dev android build and I didn't felt any disturbing lags. Normally typing user won't achieve such a typing speed

But I'll appreciate another point of view as @francoisl you are already assigned.

**Comment by francoisl** [comment] 2023-07-26 23:32
Hmm yeah this is a tough one. On one hand, I do agree that using a debounce feels more like a partial bandaid that doesn't solve the root cause, but I'm also not a huge fan of introducing yet another state variable for this.

[This part of the code](https://github.com/Expensify/App/blob/173b58e64eb16/src/pages/iou/steps/MoneyRequestAmountPage.js#L315-L318) looks odd to me, in particular how we call `setSelection()` from inside `setAmount()`'s update function. Is that the reason of the race condition you were referring to, @ygshbht? If so, is there a way to instead use `useMemo` to recompute the selection once the amount has changed? Not sure that would solve the issue - just throwing out ideas here :D

**Comment by ygshbht** [comment] 2023-07-27 02:57
Thanks, @francoisl, for your perspective.

The nested structure may indeed seem odd, but I don't think that's the root of the problem here. In fact, I tried altering the structure, but the issue still persisted. It seems that the problem lies with `setAmount` here

```
 setAmount((prevAmount) => {
            setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length));
            return stripCommaFromAmount(newAmountWithoutSpaces);
 });
```

This also triggers the `onSelectionChange `event, which in turn fires `setSelection `again. I believe this creates a race condition.

https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/iou/steps/MoneyRequestAmountPage.js#L304-L319

My proposed solution is to trigger the `onSelectionChange `event only when the user alters the selection, and not when it's being changed programmatically.

![image](https://github.com/Expensify/App/assets/65986357/abb54e05-1e1b-459e-bbf7-39bdfefee95f)

**Comment by mmaleiter** [comment] 2023-07-27 09:32
@JmillsExpensify @francoisl @robertKozik imo the proposal you prefer does solve the issue. I tested it, maybe I am missing something, but with these changes the various problems, ending on the wrong position, bouncing cursor is still reproducable and also adds a new problem swalling numbers. Also imo the solution also does not address the root cause, which I assume to be the call to setSelection() in setAmount, that like @ygshbht stated, triggers onSelectionChange.
This are just me few cents I want to add here and restate my vote for @ygshbht proposal.

**Comment by francoisl** [comment] 2023-07-31 22:17
Thanks for the additional input, everyone.

@robertKozik - I still think it would be best to fix the root cause rather than just applying a quick-fix debounce, so I'd rather go with either [proposal 1](https://github.com/Expensify/App/issues/22799#issuecomment-1646839214) or [proposal 3](https://github.com/Expensify/App/issues/22799#issuecomment-1658728401). What do you think?

**Comment by mmaleiter** [comment] 2023-08-03 18:39
> 

I prefer this solution now. Because the fix has a better location. I think it might be even better placed in AmountTextInput.js.

**Comment by francoisl** [comment] 2023-08-04 18:38
Reviewed again and I agree, the advantage of @tienifr's solution is that it will prevent the same issue from happening again if we reuse `TextInputWithCurrencySymbol` somewhere else.


In the interest of making this issue move forward, let's go with your [proposal](https://github.com/Expensify/App/issues/22799#issuecomment-1658728401) @tienifr!

**Comment by sakshixwani** [comment] 2023-08-07 16:15
Contributor details Your Expensify account email: sakshixwani@gmail.com
 Upwork Profile Link: https://www.upwork.com/freelancers/~011b9f091c7f262e12

**Comment by sakshixwani** [comment] 2023-08-07 16:21
Contributor details Your Expensify account email: sakshixwani@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011b9f091c7f262e12

**Comment by sakshixwani** [comment] 2023-08-08 15:12
Dhesh

**Comment by sakshixwani** [comment] 2023-08-08 15:15
Contributor details
Your Expensify account email: sakshixwani@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011b9f091c7f262e12

**Comment by sakshixwani** [comment] 2023-08-08 15:23
Applied to the upwork job manually @JmillsExpensify

**Comment by luacmartins** [comment] 2023-08-23 16:21
@JmillsExpensify what's the latest here?

**Comment by sakshixwani** [comment] 2023-08-29 17:52
@JmillsExpensify payment is pending

**Comment by JmillsExpensify** [comment] 2023-08-30 05:47
@robertKozik Do you mind kicking off the BZ checklist above?

**Comment by robertKozik** [comment] 2023-08-30 08:54
Sure on it 👀

**Comment by robertKozik** [comment] 2023-08-30 10:37
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: I don't think we can point out one PR which introduced this behaviour - it was rather missed on the initial implamentation phase, as it's not obvious steps in reproduce
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I don't think such a visual bug need the regression test
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

**Comment by sakshixwani** [comment] 2023-09-04 03:56
@JmillsExpensify payment is pending

**Comment by JmillsExpensify** [comment] 2023-09-07 01:47
Payment summary:

 - Issue reporter: @sakshixwani $250
 - Contrbutor: @tienifr $1,000
 - Contributor+: @robertKozik does not require payment 

Payment issued for @tienifr. Contracts sent to @sakshixwani via the [Upwork job](https://www.upwork.com/jobs/~0108bc58e45a52924e).

**Comment by sakshixwani** [comment] 2023-09-07 05:00
@JmillsExpensify i have accepted the offer

**Comment by JmillsExpensify** [comment] 2023-09-11 13:57
Everyone here is now paid out so I'm closing the issue.

**Closed by JmillsExpensify** 2023-09-11 13:57 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
