### ISSUE TITLE
[$1000] Web - Inconsistency in color and position of the "Sending" button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23074] opened 2023-07-18 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Go to settings > Workspaces > Any workspace > Cards > Connect Bank Account
3. Reach 3rd step of Connect Bank Account
4. Choose "Passport" > "Get Secure Link" > Get link via Sms > Enter your phone number and click on "Send link"
5. Press the button and you can see inconsistency.

## Expected Result:
 Inconsistency in color and position of the "Sending" button

## Actual Result:
Inconsistency in color and position of the "Sending" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a7ecfb2d-9e19-4816-9508-9422d0a00bff

![Screenshot from 2023-07-16 23-58-27 (1)](https://github.com/Expensify/App/assets/93399543/d8bea8ac-4ca9-47e6-8fe9-111a44f7f53a)
[screen-capture (1).webm](https://github.com/Expensify/App/assets/93399543/39c44b2c-f71f-431e-92b5-129644118099)

https://github.com/Expensify/App/assets/93399543/63c25764-5118-4620-831d-09ec6d12a65e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689566251384389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102735880a2da3779</li>
        <li>Upwork Job ID: 1681334919514165248</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-18 16:07
Was able to recreate this, so going to get eyes on this ASAP.

**Comment by subhash131** [comment] 2023-07-18 17:51
Hey, I just saw the job opening on Upwork.
Here is my initial observations on the issues:
1. A loading animation rendred on clicking the button which is responsible for the dislocation of the button text.
2. The button is graded out on submitting the request.

solution for the above issues
1. On clicking the submit button remove the text and have only the loading spinner until the data is loaded
2. maintain the same color as before and highlight the loading animation as shown below
![image](https://github.com/Expensify/App/assets/64570322/db124fd5-9508-4809-8a66-dd0ac1dd438a)

**Comment by subhash131** [comment] 2023-07-18 18:04
Contributor details
Your Expensify account email: subhashnayak131@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8eccf0c3bc4ccd4

**Comment by subhash131** [comment] 2023-07-18 19:15
@thesahindia I think the issue is staging environment, are you maintaining any seperate repository for staging App?

**Comment by jeffmchang** [comment] 2023-07-18 22:29
![image](https://github.com/Expensify/App/assets/109321774/72958b0a-b047-471b-9680-028bcb552944)
Passport option not showing up, is this happening for anyone else?

**Comment by jeffmchang** [comment] 2023-07-18 22:31
Contributor details
Your Expensify account email: jeffjmc4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010ea920241d3b44c2?viewMode=1

**Comment by muxriddinmuqimov77** [comment] 2023-07-19 07:57
> ![image](https://user-images.githubusercontent.com/109321774/254416609-72958b0a-b047-471b-9680-028bcb552944.png) Passport option not showing up, is this happening for anyone else?

@jeffmchang Choose connect manually and reach 3rd step

**Comment by kaushiktd** [comment] 2023-07-19 08:14
### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistency in color and position of the "Sending" button

### What is the root cause of that problem?
When we click on Send Link button it uses the CSS provided by Onfido, So the loading indicator is rendered to the left side of Send Link Text and It has fixed left margin position.

### What changes do you think we should make in order to solve the problem?
We need to add override the CSS for `.onfido-sdk-ui-crossDevice-CrossDeviceLink-sending::before` class (it will add automically to button from Onfido) and need to remove the Send Link text from button.  
You need to add below CSS to [here](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css#L24).

```
.onfido-sdk-ui-crossDevice-CrossDeviceLink-sending::before {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin: auto !important;
}

.onfido-sdk-ui-crossDevice-CrossDeviceLink-btn.onfido-sdk-ui-crossDevice-CrossDeviceLink-sending {
    color: transparent !important;
}
```
 
### Video:
[Screen-record](https://drive.google.com/file/d/1Mp6jIi0x8gL6PILgDIPPkJtAjXbfn17f/view?usp=sharing)

**Comment by CortneyOfstad** [comment] 2023-07-19 14:46
@thesahindia any thoughts on the proposals above?

**Comment by daanish-shaikh** [comment] 2023-07-19 16:42
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Inconsistency in color, alignment and content of Send Link button in disabled and loading/sending state. Following ui can be found in onfido flow for adding a bank account.
Follow below steps to find the ui.
Open website
Go to settings > Workspaces > Any workspace > Cards > Connect Bank Account
Reach 3rd step of Connect Bank Account
Choose "Passport" > "Get Secure Link" > Get link via Sms > Enter your phone number and click on "Send link"

**What is the root cause of that problem?**
It is predefined by onfido-sdk-ui library and no customization is available in its init() function.

**What changes do you think we should make in order to solve the problem?**
Override `.onfido-sdk-ui-Theme-root .ods-button.-action--primary:disabled` and `.onfido-sdk-ui-crossDevice-CrossDeviceLink-sending::before` classes in index.css file.

https://github.com/Expensify/App/blob/f3219988e982f81856d2a8d6d4af9ee48e885c15/src/components/Onfido/index.css#L19-L25
Add following code at Line no. 24

```
.onfido-sdk-ui-Theme-root .ods-button.-action--primary:disabled {
background-color: #03d47da4 !important;
}
.onfido-sdk-ui-crossDevice-CrossDeviceLink-sending::before {
background-image: none !important;
content: none !important;
}
```

**Comment by situchan** [comment] 2023-07-20 11:55
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1689854072758689?thread_ts=1689852445.808529&cid=C02NK2DQWUX, I'd like to take this as C+

**Comment by kaushiktd** [comment] 2023-07-21 04:22
@CortneyOfstad I am not seeing the proposal of @situchan here and I noticed it picked up directly from Slack channel. However, Slack link is not working for me and I am willing to learn to improve my technical knowledge. Can you please post the proposal here which got selected?

**Comment by situchan** [comment] 2023-07-21 04:47
Thanks for proposals everyone.
Can you please try to find known GH in onfido sdk and if not, create new one?
Ideally, this should be fixed upstream.

**Comment by CortneyOfstad** [comment] 2023-07-21 15:27
@kaushiktd This is my first time experiencing this, but @situchan is listed as the C+ contributor which doesn't require a proposal. @thesahindia had the C+ role originally, but unssigned themselves and assigned it to @situchan (who requested to be the C+ contributor).

**Comment by CortneyOfstad** [comment] 2023-07-24 13:46
Not overdue 👍

**Comment by kaushiktd** [comment] 2023-07-24 13:48
@CortneyOfstad Can anyone become C+ contributor here? Do you know what is the eligibility for that?

> @kaushiktd This is my first time experiencing this, but @situchan is listed as the C+ contributor which doesn't require a proposal. @thesahindia had the C+ role originally, but unssigned themselves and assigned it to @situchan (who requested to be the C+ contributor).

**Comment by CortneyOfstad** [comment] 2023-07-25 17:45
@kaushiktd We do have a process to help find C+ contributors. However, I have not been apart of that process, so I'm a bit hazy on the details. I do recommend reaching out in Slack to indicate that you would be interested!

**Comment by CortneyOfstad** [comment] 2023-07-28 13:11
@situchan any proposals looking good?

**Comment by situchan** [comment] 2023-07-28 13:18
> @situchan any proposals looking good?

I proposed https://github.com/Expensify/App/issues/23074#issuecomment-1644975824 but no one answered yet.

**Comment by situchan** [comment] 2023-07-30 20:48
Expected Result is not correct in OP:

> Inconsistency in color and position of the "Sending" button

cc: @CortneyOfstad

**Comment by situchan** [comment] 2023-07-30 20:51
> Maybe asking customization on disabled primary button background color is enough.

@ginsuma it seems like there's no active GH open to fix this issue in upstream. Can you please create new issue and propose your solution?
Depending on their response, we can wait for their fix or override css ourselves.

**Comment by CortneyOfstad** [comment] 2023-08-01 19:52
I'm heading OoO until 8/14, so reassigning in the meantime for BZ to keep eyes on this 👍

**Comment by situchan** [comment] 2023-08-04 08:48
> I create a new issue https://github.com/onfido/onfido-sdk-ui/issues/2177. Please check it to see if having anything need to be correct.

@ginsuma thanks. Let's wait for their feedback

**Comment by kevinksullivan** [comment] 2023-08-04 22:23
I am also going OOO for the week so I have to reassign unfortunately.

**Comment by dylanexpensify** [comment] 2023-08-08 08:05
Reviewing this today to post update! Got stuck with travel yesterday!

**Comment by dylanexpensify** [comment] 2023-08-10 11:05
@situchan where are we at here?

**Comment by situchan** [comment] 2023-08-10 11:21
> > I create a new issue [onfido/onfido-sdk-ui#2177](https://github.com/onfido/onfido-sdk-ui/issues/2177). Please check it to see if having anything need to be correct.
> 
> @ginsuma thanks. Let's wait for their feedback

We are at this.

@ginsuma can you please bump repo owner or maintainers on that upstream issue?

**Comment by dylanexpensify** [comment] 2023-08-11 19:54
Didn't get an update today, will on Monday! @ginsuma let us know if you got them bumped!

**Comment by dylanexpensify** [comment] 2023-08-15 20:08
@situchan shall we put this on hold until we hear back?

**Comment by situchan** [comment] 2023-08-15 20:09
> @situchan shall we put this on hold until we hear back?

yes, or move to Weekly

**Comment by dylanexpensify** [comment] 2023-08-16 13:44
@ginsuma let us know what you hear!

**Comment by dylanexpensify** [comment] 2023-08-18 19:14
Sounds good - ty!

**Comment by CortneyOfstad** [comment] 2023-08-23 13:53
@ginsuma Any updates? TIA!

**Comment by dylanexpensify** [comment] 2023-08-25 11:48
@CortneyOfstad I'mma unassign now that you're back!

**Comment by CortneyOfstad** [comment] 2023-09-01 14:55
@ginsuma just checking to see if you had any updates – TIA!

**Comment by CortneyOfstad** [comment] 2023-09-08 13:33
@ginsuma any updates with this? TIA!

**Comment by CortneyOfstad** [comment] 2023-09-18 19:38
@ginsuma any updates?

**Comment by situchan** [comment] 2023-09-18 19:42
@ginsuma please check other similar issues how contributors contacted them and got support.
i.e. #14766

**Comment by CortneyOfstad** [comment] 2023-10-06 17:58
@ginsuma It shows that the last bump was aug. 10. Can you try directly assigning someone to the GH or bumping someone again?

**Comment by situchan** [comment] 2023-10-09 01:45
I started considering patch fix as there's no respond from upstream for a long time and seems like they won't be fixing this or prioritizing at all.

**Comment by MahmudjonToraqulov** [comment] 2023-10-16 11:00
Hey @situchan. Let me ask. You meant 23889 and 23074 issues. If there is valid proposal soon and PR get merged, which one will be eligible for the paymet? I think both issues are a bit different.

**Comment by situchan** [comment] 2023-10-18 13:02
Let's close this one. Context: https://github.com/Expensify/App/issues/23889#issuecomment-1768290359

**Closed** 2023-10-18 15:35 UTC
Labels: External, Engineering, Weekly, Bug
