### ISSUE TITLE
[HOLD for payment 2023-01-19] Unpin tooltip text is splitting into 2 lines

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14149] opened 2023-01-09 18:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and navigate to chat
2. Press the pin icon in the header of the chat screen
3. Hover over the pin icon again and check the tooltip text

## Expected Result:
Unpin text should be in a single line

## Actual Result:
Unpin text is splitting in 2 lines

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211381132-bc4b0d97-cf2f-4e91-8ee2-dcf8ca417a17.mov

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/211381176-e64a65bc-46a0-4a8e-a931-151661d4f32c.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673208539820589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01757fe35604e7bf17</li>
        <li>Upwork Job ID: 1612617865531674624</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by alex-mechler** [comment] 2023-01-09 18:40
@roryabraham possibly related to https://github.com/Expensify/App/pull/12168?

**Comment by alex-mechler** [comment] 2023-01-09 23:10
Confirmed its related to that PR by reverting it locally

**Comment by alex-mechler** [comment] 2023-01-10 00:21
This appears to be because of a delay in rerendering the Portal's components. If we do not set a text width in `updateTooltipTextWidth`, but read the ref's offsetWidth, we see that the offsetWidth is correct when it has not been overwritten

**Comment by alex-mechler** [comment] 2023-01-10 00:41
Okay, adding a timeout before recalculating the width of the tooltip fixes this, but I think that narrows it down to the `Portal` component not re-rendering its children fast enough

**Comment by Julesssss** [comment] 2023-01-10 15:49
Resolved and CP'd, but not deployed to prod. Removing the blocking label.

**Comment by mallenexpensify** [comment] 2023-01-20 16:24
@muttmuure can you issue payment today and also complete the checklist above, thanks

**Comment by thesahindia** [comment] 2023-01-20 16:53
Unassigning since I didn't do anything here.

**Comment by muttmuure** [comment] 2023-01-23 14:59
This was resolved internally and CP'd to prod, so no payments needed. 

Posted buddy check [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1674485918559939)

**Comment by jayeshmangwani** [comment] 2023-01-25 04:54
> This was resolved internally and CP'd to prod, so no payments needed.


@muttmuure reporting bonus is due here

**Comment by muttmuure** [comment] 2023-01-25 10:08
@jayeshmangwani oh yes, you're correct. I've invited you to apply. Thanks!

**Comment by jayeshmangwani** [comment] 2023-01-25 10:12
@muttmuure hey , price should be $250 for reporting bonus and for the job you have invited me to is $1000

**Comment by muttmuure** [comment] 2023-01-25 10:16
Should be resolved

**Comment by muttmuure** [comment] 2023-01-25 10:17
Please could you accept the offer? Thanks!

**Comment by jayeshmangwani** [comment] 2023-01-25 10:18
@muttmuure accepted, Thanks

**Comment by muttmuure** [comment] 2023-01-25 10:18
@jayeshmangwani has been paid! 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/46995600/214537841-caa1498e-9a8e-4865-81ad-2e8ae4681066.png">

Closing out

**Closed by muttmuure** 2023-01-25 10:18 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
