### ISSUE TITLE
[$250] Search - Expense shows From User B to User A when User A pays User B (pay someone)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45611] opened 2024-07-17 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with any user
3. Click + > Pay [X email]
4. Enter amount and pay the user
5. Go to Search
5. Look for the payment sent in Step 4

## Expected Result:
The expense should display "From User A to User B"

## Actual Result:
The expense displays "From User B to User A", where User B is the receiver and User A is the payer.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/28634f64-536c-4db0-bb6d-a0d565289f2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcec74253fa9dcd4</li>
        <li>Upwork Job ID: 1813632166397470742</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by lanitochka17** [comment] 2024-07-17 14:32
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-07-17 17:49
Oh yeah this is a good catch - I think it's part of Wave- Collect. I'm not sure if this needs to be internal but let's start external.

**Comment by tufcoder** [comment] 2024-07-17 20:26
## Proposal

### Please rewrite the problem we are trying to solve in this question.

The expense displays “From user B to user A”, where user B is the receiver and user A is the payer.

### What is the root cause of this problem?

The video attached to this Issue does not match the problem mentioned, but following what is written in “Action Performed” I believe I have reproduced the problem.

The `ParentNavigationSubtitle.tsx` component is rendering the content using the `translate()` function, passing the `'threads.from'` string as a parameter. 

If this is not the problem, I apologize for the misinterpretation.

### What changes do you think we should make to solve the problem?

I suggest making an addition to `threads` in the file `src/languages/en.ts` to include the `to` option.

```ts
threads: {
         to: 'To',
         ...
},
```

This way, we can use `...translate('threads.to')` in the `ParentNavigationSubtitle.tsx` component to render the content correctly.

The updated content is shown below:

![image](https://github.com/user-attachments/assets/11bd0f7f-edf8-46de-b2ea-cf972cc03168)

![image](https://github.com/user-attachments/assets/f88d2fa4-ddd6-42fa-a899-35e7c4c717f9)

**Comment by tufcoder** [comment] 2024-07-18 17:56
Please disregard my [proposal](https://github.com/Expensify/App/issues/45611#issuecomment-2234219285) because it is not in line with the problem.

**Comment by trjExpensify** [comment] 2024-07-19 11:13
@luacmartins for vis on this one.

**Comment by Christinadobrzyn** [comment] 2024-07-19 15:53
@rojiphil can you take a peek at this proposal - https://github.com/Expensify/App/issues/45611#issuecomment-2236415812

**Comment by rojiphil** [comment] 2024-07-22 09:29
Reviewing today

**Comment by luacmartins** [comment] 2024-07-22 16:44
I think @dominictb has the correct RCA, but IMO this should be fixed on the server so we send the correct values to the client.

**Comment by luacmartins** [comment] 2024-07-22 17:18
Hmm we already have similar [logic in the backend](https://github.com/Expensify/Auth/blob/f20e9154cb393a57914de8de450346449bb8b202/auth/command/Search.cpp#L253-L257), but I'm not sure that comparing just `reportType` and amounts is enough. I wonder if we also need to check if this is a `Send money` request or not. cc @mountiny do you know?

**Comment by mountiny** [comment] 2024-07-22 21:53
Yeah thats fair @luacmartins I think we could add check for the IOUDetails in message to confirm its Send money flow

**Comment by luacmartins** [comment] 2024-07-23 00:03
@mountiny so it's not enough to compare the report type and amount sign for the paid case, right? We also need to identify that the request type for `send`?

**Comment by mountiny** [comment] 2024-07-23 01:20
yeah I think that we ideally check for the type=pay && IOUDetails.size() like [here](https://github.com/Expensify/Auth/blob/5bc8f995676208a1b7924d077a7eeae4f37c2b0b/auth/lib/ReportAction.cpp#L1437) wherever we need to catch the send money flow

**Comment by luacmartins** [comment] 2024-07-26 17:02
PR in review

**Comment by Christinadobrzyn** [comment] 2024-07-29 15:49
The PR looks like it's been deployed already! Wow! I'll keep an eye out for the payment automessage

**Comment by luacmartins** [comment] 2024-07-29 16:24
This issue was worked on internally. Not sure that there's any payment due here.

**Comment by rojiphil** [comment] 2024-07-29 16:28
> Not sure if there's any payment due here.

yea... no payment for me here

**Comment by Christinadobrzyn** [comment] 2024-07-29 16:40
Oh perfect, thanks for confirming. Since there are no payments - Do you want me to just close this out now or wait for the 7-day window @luacmartins?

**Comment by luacmartins** [comment] 2024-07-29 16:41
Thanks for asking! We can close this out, since the backend PR was deployed and the issue is fixed.

**Closed by luacmartins** 2024-07-29 16:41 UTC
Labels: Reviewing, Daily, Internal, Bug
