### ISSUE TITLE
[PAYMENT MAY 29][$250] Split - Expense text is missing from the preview tile when creating split expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41010] opened 2024-04-25 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40961
## Action Performed:
1. Navigate to a group chat
2. Do a manual split there
3. Use the quick action button to do another split

## Expected Result:
Expense text should be visible

## Actual Result:
Expense text is missing from the preview tile when creating split expense. It's visible if you use the quick action button to do the same split

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6461792_1714061520908!IMG_1932](https://github.com/Expensify/App/assets/78819774/1d24dcc4-e9de-4b7f-8543-8eaaacaa3728)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb074043a26909ea</li>
        <li>Upwork Job ID: 1785399966337712128</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by s77rt** [comment] 2024-05-02 03:39
@gijoe0295 Thanks for the proposal. Your RCA makes sense. Let's align on the expected behavior and discuss the solution.

🎀 👀 🎀 The expected behavior is not clear, when creating a split should we:
1. Set the merchant to "Expense"
2. Keep the merchant empty

**Comment by s77rt** [comment] 2024-05-07 20:54
@thienlnam Can you please check https://github.com/Expensify/App/issues/41010#issuecomment-2089474223

**Comment by slafortune** [comment] 2024-05-10 15:12
@thienlnam when you get a chance can you review the assignment?

**Comment by thienlnam** [comment] 2024-05-13 19:47
Ah yes, thanks for the bump - was OOO last week

**Comment by s77rt** [comment] 2024-05-13 20:05
@thienlnam Can you please check the question on https://github.com/Expensify/App/issues/41010#issuecomment-2089474223

**Comment by thienlnam** [comment] 2024-05-13 21:21
We would want to keep the merchant empty

**Comment by s77rt** [comment] 2024-05-13 21:49
@gijoe0295 Let's just change the merchant value to `CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT `

https://github.com/Expensify/App/blob/c5bf798d0bda0b8e1a37fa763be9ae0acff7b730/src/pages/iou/request/step/IOURequestStepAmount.tsx#L204

**Comment by slafortune** [comment] 2024-05-23 22:19
This was merged yesterday - 
<img width="987" alt="image" src="https://github.com/Expensify/App/assets/11725910/3c49026a-b1b2-413b-87d8-710fc901a77d">
That would make the payment on the 29th - looks like the title didn't update.

@s77rt  - C+ Role ~ will be due $250 via [Upworks](https://www.upwork.com/nx/wm/workroom/37255995/overview)
@gijoe0295  - Contributor Role ~ will be due $250 via [Upworks](https://www.upwork.com/nx/wm/workroom/37257622/overview)

I'll be on vacation until June 4th so adding a BZ in the meantime.

**Comment by garrettmknight** [comment] 2024-05-30 14:25
**Payment Summary:**
@s77rt - C+ Role - $250 paid via upwork
@gijoe0295 - Contributor Role - $250 paid via upwork

**Comment by garrettmknight** [comment] 2024-05-30 14:25
@s77rt can you complete the checklist when you get a chance?

**Comment by s77rt** [comment] 2024-05-30 19:39
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/39413
- The offending PR has been commented on: https://github.com/Expensify/App/pull/39413#discussion_r1621325572
- A discussion in #expensify-bugs has been started: Not needed (unique bug)
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal** 


1. Click on FAB
2. Click on Split expense
3. Split the expense with an individual without specifying the merchant
4. Click on the split preview
5. Verify that the merchant field is empty
6. Click on FAB
7. Verify that the QAB reflects the split option
8. Click on the QAB
9. Verify that the split expense flow opens
10. Submit the expense
11. Click on the split preview
12. Verify that the merchant field is empty

[suggested test suite group](https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_id=309127&group_order=asc&display_deleted_cases=0)

**Comment by s77rt** [comment] 2024-05-30 19:39
@garrettmknight Done! ^

**Comment by garrettmknight** [comment] 2024-05-31 17:59
Legend, thank you!

**Closed** 2024-06-03 18:07 UTC
Labels: External, Daily, Overdue, Bug
