### ISSUE TITLE
[$1000]  Assign Task - User is unable to click "Assignee" to add assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23719] opened 2023-07-27 10:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com and create new accounts for User A, B and C
2. Using User A, create a group chat and add User B and C
3. Select "+' and select "assign task"
4. Assign task without and assignees
5. Log out out and log in with either User A and B
6. Navigate to group chat and select task
7. Click on Assignees

## Expected Result:
User is sent to page "assignees" page and can select a specific User to assign task

## Actual Result:
Clicking on "Assignees" does nothing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9dbd14ff-8cc5-49e3-bcc7-3cb1f83f2127

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127a00b1cb7d86aab</li>
        <li>Upwork Job ID: 1686504234580873216</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-27 14:03
I can't reproduce. Maybe you logged in with the different account? I mean not a task creator

**Comment by BhuvaneshPatil** [comment] 2023-07-27 16:20
is this reproducible on desktop web?

**Comment by johncschuster** [comment] 2023-07-27 16:39
@kbecciv can you answer the above questions?

**Comment by kbecciv** [comment] 2023-07-28 16:30
Hey @johncschuster! Checking, will update you shortly

**Comment by johncschuster** [comment] 2023-07-30 17:02
This behavior _might_ be expected. I'm trying to hunt down the expected behavior now.

**Comment by johncschuster** [comment] 2023-08-01 22:24
Ok, I can't find anything that would make this behavior expected. Triaging!

**Comment by johncschuster** [comment] 2023-08-02 23:34
Thanks @dukenv0307!

> There is only task creators and assignees can edit tasks

Do you know where that's written down? I'd love to confirm that so we can close the issue.

**Comment by kok-hong** [comment] 2023-08-03 10:20
Are you looking for [this comment](https://github.com/Expensify/App/issues/21762#issuecomment-1615210472)?

**Comment by thienlnam** [comment] 2023-08-03 20:18
We've updated this recently - anyone who can view the task can modify the task

**Comment by thienlnam** [comment] 2023-08-03 20:19
This should be updated now in https://github.com/Expensify/App/pull/23971

**Closed by thienlnam** 2023-08-03 20:19 UTC
Labels: External, Daily, Help Wanted, Bug
