### ISSUE TITLE
[HOLD for payment 2022-06-13] [$1000]  mWeb - Workspace - Footer message is not fully visible after removed the member from Workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8520] opened 2022-04-07 02:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)

2. Create a new workspace from an account that's on the policyExpenseChat beta (e.g @expensifail.com)
3. Add a new member to the workspace via Manage Members > Invite
4. Log-in as the member and send a message in the member's workspace chat
5. Log back in again to the admin account and remove the member from the workspace via Manage Members > Remove
6. Verify the row chat (in LHN and search bar) should display the default subtitle (workspace name)
7. Now log-in as the member again
8. Verify the row chat (in LHN and search bar) includes the workspace name
9. Verify the footer message displays the workspace

## Expected Result:
Footer message is fully visible after removed the member from Workspace

## Actual Result:
Footer message is not visible after removed the member from Workspace

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.1.52.0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):**  applausetester+033122abb@applause.expensifail.com / Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

![Bug5522790_Screenshot_20220406-214526_Chrome](https://user-images.githubusercontent.com/43996225/162108480-d1767588-e303-4fe4-9512-bedeff62a4c3.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2022-04-07 14:26
Able to reproduce the issue on dev with an account that has a lengthy email address:

![Screen Shot 2022-04-07 at 6 26 00 PM](https://user-images.githubusercontent.com/12268372/162222315-1d39a371-67a2-4436-9ec3-fe24122d35c2.png)

**Comment by thesahindia** [comment] 2022-04-07 17:52
I couldn't access policy expense chat as it is behind the beta, I tried some code tweaks but it didn't work.

**Comment by laurenreidexpensify** [comment] 2022-04-08 07:48
Am OOO next week. 

job posting here https://www.upwork.com/jobs/~0101338915fc9540cb

**Comment by devtayyab** [comment] 2022-04-10 10:27
Is it essential  to connect bank account for workspace chatting?

**Comment by Santhosh-Sellavel** [comment] 2022-04-11 15:37
> Is it essential to connect bank account for workspace chatting?

I assume it's not necessary

**Comment by Santhosh-Sellavel** [comment] 2022-04-11 16:15
@thesahindia Do you have any other archived chats? If then you can make some code tweaks to reproduce this issue.

**Comment by JmillsExpensify** [comment] 2022-04-18 21:58
Yeah, it's not necessary to have a connected bank account to use workspace chats.

**Comment by Santhosh-Sellavel** [comment] 2022-04-22 16:17
Can we double this one or wait?

cc: @JmillsExpensify @deetergp

**Comment by mallenexpensify** [comment] 2022-04-22 18:16
Doubled price to $500
https://www.upwork.com/jobs/~0101338915fc9540cb

**Comment by deetergp** [comment] 2022-04-22 18:53
Thanks for weighing in and doubling it @mallenexpensify 👍

**Comment by JmillsExpensify** [comment] 2022-04-25 01:35
Yes, thanks @mallenexpensify!

**Comment by Santhosh-Sellavel** [comment] 2022-04-29 14:47
Still looking for a proposal.

**Comment by mallenexpensify** [comment] 2022-04-29 17:04
Doubled price to $1000
https://www.upwork.com/jobs/~0101338915fc9540cb

**Comment by mallenexpensify** [comment] 2022-04-29 20:37
I like `#1`, I prefer truncating in the middle in case people use the same name for multiple emails but different domains/jobs

**Comment by Santhosh-Sellavel** [comment] 2022-04-29 20:52
Personally, do we really need to show the email there? 

Can't we just say?
"This workspace chat is no longer active because **you** are no longer a member of the Some workspace."

**Comment by thesahindia** [comment] 2022-04-30 14:24
### Proposal 

At native the email gets break to the next line the problem is only on mobile web so I propose that we should just use 
`word-break: break-word`
We can add it to the styles.js and we can use it here as `styles.breakWord`
https://github.com/Expensify/App/blob/f174c3223a1d6d0f571e5bd799441690951f078c/src/components/Banner.js#L28-L32

**Comment by Santhosh-Sellavel** [comment] 2022-04-30 17:45
@tgolen 
@thesahindia [proposal](https://github.com/Expensify/App/issues/8520#issuecomment-1113997376) looks good to me.
🎀👀🎀 C+ reviewed

But it should be `styles.breakAll`. Check the following images.

### breakWord
<img width="355" alt="Screenshot 2022-04-30 at 11 15 18 PM" src="https://user-images.githubusercontent.com/85645967/166116537-7598f0ac-89d4-4961-b62e-f7481edc184e.png">


### breakAll
<img width="384" alt="Screenshot 2022-04-30 at 11 13 22 PM" src="https://user-images.githubusercontent.com/85645967/166116497-4845c498-4ebd-4eaa-98fb-9f568615e2fc.png">

**Comment by JmillsExpensify** [comment] 2022-05-02 15:15
Ok great. I'll hire @thesahindia once we get the final word from @tgolen. Thanks all!

**Comment by tgolen** [comment] 2022-05-02 19:38
Ah cool. That looks good to me! 🟢

**Comment by thesahindia** [comment] 2022-05-02 19:45
Cool, just applied on the upwork. 
cc: @JmillsExpensify

**Comment by thesahindia** [comment] 2022-05-04 21:02
bump @JmillsExpensify (in case you missed the ping) 
Also can you assign me here?

**Comment by JmillsExpensify** [comment] 2022-05-04 21:14
Sure thing. Thanks for the reminder! Doing both now.

**Comment by JmillsExpensify** [comment] 2022-05-04 21:16
Done. @Santhosh-Sellavel Please make sure to apply as well.

**Comment by JmillsExpensify** [comment] 2022-05-10 21:15
Not immediate rush, though don't forget to apply to the Upwork job @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2022-05-12 19:54
PR arrived at the roadblock here: https://github.com/Expensify/App/pull/8878#issuecomment-1118005306

Need to explore options to solve this one!

**Comment by JmillsExpensify** [comment] 2022-05-23 15:33
Looks like we are still blocked in the linked PR, and no further discussion I can see in GH. What's the latest? I'm going to put a hold in the issue in the meantime. Thanks!

**Comment by JmillsExpensify** [comment] 2022-05-31 02:59
Discussion in the linked PR as of late last week.

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 18:14
@JmillsExpensify 

Status:
Remove the hold label here, PR got merged today. It's live on staging now.

Known issue:  -> https://github.com/Expensify/App/pull/8878#issuecomment-1118005306
This should not be treated as regression.

Mostly like we should straight away create a new issue in GH for the above and look for 

I'm going OOO, So I believe mostly my job is done here. If there are any new breakages/regression while I am away, feel free to un-assign me and add a new C+ here thanks!

cc: @deetergp

**Comment by mvtglobally** [comment] 2022-06-07 03:58
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-06-13 16:37
Regression period has passed and I'm not seeing any issues in the linked PR. Issuing payments now. Contributors - thanks so much and let me know if you have any questions following payment.

**Comment by JmillsExpensify** [comment] 2022-06-13 16:45
I'm going to go ahead and close the issue but please comment here and/or message me on Slack when you return from OOO and we'll get this closed out for you.

**Closed by JmillsExpensify** 2022-06-13 16:45 UTC
Labels: Exported, External, Engineering, Daily, Awaiting Payment

**Comment by Santhosh-Sellavel** [comment] 2022-06-15 17:09
Thanks for the invite @JmillsExpensify
