### ISSUE TITLE
[$250] Bank Account - Onfido page returns an error when go online

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49572] opened 2024-09-22 09:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2950430
**Email or phone of affected tester (no customers):** applausetester+bp0917w@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: workspace with enabled workflows. Started and followed the flow for adding a Verifying bank account using the credentials found below until you reach the Onfido screen:
Use Regions bank
Username: user_good | Password: pass_good
Account type: Plaid Saving (2nd option)
CompanyName: Expensify
CompanyTaxID: 123456789
First Name: First
Last Name: Last

1. Go to ws > workflows
2. Connect bank account > Continue setup
3. Personal info > Confirm
4. On Onfido screen: Disable the internet connection
5. Enable the internet connection
6. Repeat step 3

## Expected Result:
Onfido screen open and user can proceed the flow.

## Actual Result:
An error appears. User is navigated back to Personal info page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3546f5a4-c9fd-4f74-bf8c-fca9d1621ab8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838061398162430239</li>
        <li>Upwork Job ID: 1838061398162430239</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104084844</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by IuliiaHerets** [comment] 2024-09-22 09:18
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-09-23 03:43
Able to reproduce, @IuliiaHerets can you confirm if this happens on iOS as well?

**Comment by narefyev91** [comment] 2024-09-23 09:21
Hi, I’m Nicolay from Callstack and I would like to investigate this issue.

**Comment by jliexpensify** [comment] 2024-09-23 09:41
All yours @narefyev91

**Comment by narefyev91** [comment] 2024-09-24 14:40
@jliexpensify @hoangzinh  what i was able to find during investigation:
Before user starts onfido flow - we send API `UpdatePersonalInformationForBankAccount` and we get such response (which has onfido token):
<img width="1052" alt="Screenshot 2024-09-24 at 16 38 32" src="https://github.com/user-attachments/assets/35a20547-8271-4f95-b6c9-269b1e40d116">

After disabling/enabling internet - we have initial API call to grab all available information (which were stored before) - `OpenReimbursementAccountPage ` - and in response we get empty onfidoToken:
<img width="934" alt="Screenshot 2024-09-24 at 16 41 25" src="https://github.com/user-attachments/assets/bf5fbd1d-ada7-4612-ada6-77f9d31deb35">

That's why user got redirected to the personal screen - instead of continue working with onfido - there is no token provided
For error which is shown in pop-up - it happened inside onfido package:
`[hmmm] Onfido error - {"errorType":"exception","errorMessage":"Frame with src https://sdk.onfido.com/capture/core/14.37.1/runner.html took too long to load."} 
` 
<img width="1062" alt="Screenshot 2024-09-24 at 16 52 58" src="https://github.com/user-attachments/assets/65dfe5e5-4014-4fcc-b2d5-96d6ee1d2891">
Technically it means that we have timeout of some of the services from onfido - which probably is not working offline. We can see that in Sources tab - onfido drops some resources when i moved to offline:

https://github.com/user-attachments/assets/cb99cf59-7522-4aec-8e2c-8043c669803c

Based on all these information - we should try to fix 2 issues:
1) Token should come from API in `OpenReimbursementAccountPage` if user already set personal information
2) We should re-initiate Onfido for web - if user goes offline/online - to not waiting source from already lost onfido thread (will check how that can be possible)

Let me know wdyt guys. Thanks!

**Comment by jliexpensify** [comment] 2024-09-24 23:27
@joekaufmanexpensify dropping you into this bug GH as I think you worked on Onfido for ND? Do you mind sharing your thoughts on the above comment?

**Comment by narefyev91** [comment] 2024-09-25 13:54
Some more finding here:
We never correctly ternimate onfido flow - in this file src/components/Onfido/index.tsx:
<img width="883" alt="Screenshot 2024-09-25 at 16 00 58" src="https://github.com/user-attachments/assets/df37075e-cb8f-4417-b653-78d41a70ef53">
onfidoOut.tearDown(); - is not working at all

Also interesting thing that in 14.15.0 (current version) there is other method to terminate onfido sdk
https://documentation.onfido.com/sdk/web/14.15.0/#sdk-tear-down
<img width="416" alt="Screenshot 2024-09-25 at 16 03 05" src="https://github.com/user-attachments/assets/bfe95919-aaf5-440b-8b1d-30a99a96816a">
But when i tried to use it - it says that such method does not exists lol.
I upgrade version for 14.17.0 - which is for sure has correct tearDown function.
<img width="485" alt="Screenshot 2024-09-25 at 16 04 39" src="https://github.com/user-attachments/assets/78ab2eb6-4fed-464d-b186-c61fc76b7de7">

But it was not fixed the issue with error pop-up. But it gives correct flow to remove dead sdk thread.
Currently diving deeper - i realised that when user moves back to online what currently happened:
1) isOffline = false
2) FullPageOfflineBlockingView - return children - which is  Onfido component
3) we refetching data - BankAccounts.openReimbursementAccountPage
3) Onfido run again OnfidoSdk.init and in parallel received that onfidoToken is null
4) we drop onfidoSdk connection
5) But onfido already started some init process and waiting to execute all instruction - and just throws timeout error - that some instructions were not loaded in time

Again probably that's correct behaviour from Onfido - because if some resources are lost - they could not guaranteed that their product will work correctly.
In our situation root case - is that we lost onfidoToken after coming back from offline. 
I think that it will be a workaround to just save onfidoToken locally - when app is moved to offline and re-use it after BankAccounts.openReimbursementAccountPage will be executed.
But also will wait your suggestions here @hoangzinh @joekaufmanexpensify @jliexpensify

**Comment by joekaufmanexpensify** [comment] 2024-09-25 14:40
Yeah, Onfido is an online-only operation. It's expected that it doesn't work offline and uses pattern D. In an ideal world, I think it'd be nice to be able to land where you where in the Onfido flow if you go offline during it. But given it is an online operation with a third party service, I don't think it's a big deal if you need to restart it too. I expect the user would be understanding of that. 

If we can easily drop you where you were in the flow though after reconnecting to the internet, that sounds solid.

**Comment by joekaufmanexpensify** [comment] 2024-09-25 14:40
Unassigning as this doesn't need two BZs, but LMK if there any other Q's I can help with!

**Comment by narefyev91** [comment] 2024-09-25 15:00
> Yeah, Onfido is an online-only operation. It's expected that it doesn't work offline and uses pattern D. In an ideal world, I think it'd be nice to be able to land where you where in the Onfido flow if you go offline during it. But given it is an online operation with a third party service, I don't think it's a big deal if you need to restart it too. I expect the user would be understanding of that.
> 
> If we can easily drop you where you were in the flow though after reconnecting to the internet, that sounds solid.

Yeah - fully agree! To move back to existing flow we just need to have onfido token and we can achieve that by:
1) do not receive in **OpenReimbursementAccountPage** onfido token set - **{key: 'onfidoToken, onyxMethod: set, value: null}**
2) receive onfido token in **OpenReimbursementAccountPage** if user already filled information before.
3) store token locally and re-use it after offline - if personal information already exists in **OpenReimbursementAccountPage**.

**Comment by narefyev91** [comment] 2024-09-26 09:50
I tried to add FE fix - was able to get to onfido flow directly after move back to online, but still onfido throws error after unmount - and this part of code executed:
<img width="761" alt="Screenshot 2024-09-26 at 12 43 22" src="https://github.com/user-attachments/assets/aef71b79-852a-4d1e-921a-d74f0c30be7b">
Which clears token again. To avoid that we need to not keep in count "exception" errors - which in my view is not correct.

Again - seems like this issue should be fixed on BE side.

@hoangzinh could you please take a look on the discussion and maybe also suggest/make decision where we should try to fix that flow.
In a few words:
1) Root case - onfido token is set to null after user moves back to online.
2) that happened because OpenReimbursementAccountPage API call returns `{key: 'onfidoToken, onyxMethod: set, value: null}`.
3) fixing on FE side by just storing token locally (in ref for example) is a workaround.

**Comment by narefyev91** [comment] 2024-09-27 06:13
@hoangzinh yeah totally agree - and also needs to remove from `OpenReimbursementAccountPage ` API {key: onfidoApplicantID} as well

**Comment by narefyev91** [comment] 2024-09-27 11:01
> ah yes, agreed with that. Let me quickly links what we investigated so far
> 
> * The root cause [here](https://github.com/Expensify/App/issues/49572#issuecomment-2376478578) (More details [here](https://github.com/Expensify/App/issues/49572#issuecomment-2371508619))
> * @narefyev91 and I agreed on solution [here](https://github.com/Expensify/App/issues/49572#issuecomment-2378079675)
> * Along the way, @narefyev91 also found another [bug](https://github.com/Expensify/App/issues/49572#issuecomment-2374162361)
> 
> Do you agree @narefyev91 ^, or you have anything else to add before we proceed with an internal engineer? Thank you.

Yeah thanks for the summary! Agree with everything here

**Comment by flodnv** [comment] 2024-09-30 11:06
It seems to me like your proposal to fix this in the backend makes sense. @nkuoch can you take a look please? I see you recently modified this here: https://github.com/Expensify/Web-Expensify/commit/e787298b1da0f3192cc3333d40414755ca606c8e

**Comment by nkuoch** [comment] 2024-10-01 10:05
Creating back end fix [here](https://github.com/Expensify/Web-Expensify/pull/43732).

**Comment by nkuoch** [comment] 2024-10-01 11:42
Can you elaborate?

**Comment by nkuoch** [comment] 2024-10-02 08:56
I believe OpenReimbursementAccountPage is only called when reloading? When user completes personal info, OnfidoToken gets set with a string. If user refreshes the page or reconnects because they got disconnected on this step, OpenReimbursementAccountPage would be called and not touch OnfidoToken (and I rely on `we have a bunch of logic around onfido tokens which will be already handled if token is expired or is not correct.`) in case OnfidoToken is not correct anymore. Note that if OpenReimbursementAccountPage gets called from any other steps, OnfidoToken would get reset to null though.

**Comment by narefyev91** [comment] 2024-10-02 10:05
I think if user will re-visit onfido flow and token or application ID which were not cleaned will be incorrect - Onfido will show and error - and we will clean up it here https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/ReimbursementAccount/RequestorOnfidoStep.tsx#L49:

<img width="975" alt="Screenshot 2024-10-02 at 13 04 59" src="https://github.com/user-attachments/assets/7cb54138-1cf3-4e16-b5f3-19dcfe7b1fc2">

**Comment by nkuoch** [comment] 2024-10-07 13:55
BE fix has been deployed FYI

**Comment by nkuoch** [comment] 2024-10-10 07:29
Cool then we can close

**Closed by nkuoch** 2024-10-10 07:29 UTC
Labels: External, Daily, Bug
