### ISSUE TITLE
[$500] Workspace - Inconsistency bug: rate in track distance can be changed when offline in mobile web but not in desktop chrome

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27533] opened 2023-09-15 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot in Mweb and desktop
2. Turn offline mode on
3. Go to a workspace> reimbursement>track distance and click on rate
4. Observe that rate can be changed and saved in Mweb but not in desktop

## Expected Result:
User should be able to change and save rate in desktop platforms

## Actual Result:
 User is not abel to change and save rate in desktop

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5c442886-b66b-45a3-be7d-b9d94e0100c6

https://github.com/Expensify/App/assets/115492554/06eb0aec-25a4-4b4a-9c26-c87916a81dd4

https://github.com/Expensify/App/assets/115492554/fb0133b2-a349-4d93-b047-ef944a822773

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692780628108389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100ef9e23b58a623a</li>
        <li>Upwork Job ID: 1702689655141617664</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-09-18 19:10
Waiting for proposals here

**Comment by programmerkenzi** [comment] 2023-09-21 05:41
## Proposal

### Problem Statement
Please clarify the problem that we are addressing in this issue.

### Root Cause
The primary cause of the problem is the inability to retrieve `distanceCustomUnit` in the `saveUnitAndRate` function found in the file: `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js`.

```javascript
saveUnitAndRate(unit, rate) {
    const distanceCustomUnit = _.find(
        lodashGet(this.props, 'policy.customUnits', {}),
        (u) => u.name === CONST.CUSTOM_UNITS.NAME_DISTANCE
    );
    
    if (!distanceCustomUnit) {
        return;
    }
    // ... rest of the code
}
```

Additionally, data is not fetched in `src/pages/workspace/reimburse/WorkspaceReimburseView.js` when offline:

```javascript
useEffect(() => {
    if (props.network.isOffline) {
        return;
    }
    fetchData();
}, [props.network.isOffline, fetchData]);
```

### Proposed Solution

1. Disable the `enabledWhenOffline` option.
2. Display a tooltip to notify the user of the offline status.

```javascript
<Form
    formID={ONYXES.FORMS.WORKSPACE_RATE_AND_UNIT_FORM}
    submitButtonText={this.props.translate('common.save')}
    style={[styles.mh5, styles.flexGrow1]}
    scrollContextEnabled
    validate={this.validate}
    onSubmit={this.submit}
    // Remove: enabledWhenOffline
>
```

Note: I will provide the code for the tooltip once this proposal is accepted.

### Alternative Solutions Explored

One alternative solution I considered was to save the `offlineUpdateData`, then update the UI in `src/pages/workspace/reimburse/WorkspaceReimburseView.js`, and finally call the `saveUnitAndRate` function once back online. 

However, this approach would require significant effort to implement.

**Comment by alexpensify** [comment] 2023-09-21 18:20
@narefyev91 - when you get a chance, can you please review these proposals? Thanks!

**Comment by narefyev91** [comment] 2023-09-22 06:49
@alexpensify The main issue here - which is not really shown in QA steps - that if you never visit Track distance page (Reimbursements) during you session - and go offline - it will not reflect any changes on all platforms - which is correct - because you are offline.
If you visit that page and only after go offline - it will also work for all platforms.
Both on my tests - are we sure that we have a bug? Seems not - both logic offline/online working correctly

**Comment by narefyev91** [comment] 2023-09-22 08:52
@tsa321 I'm not really sure that it's a bug - we have 2 workflows - which working in the same manner for all platforms - if we need to change existing workflow - we need to allow user make changes in offline mode - and someone should approve those change - that's why we waiting for @alexpensify

**Comment by alexpensify** [comment] 2023-09-25 08:32
Ok, it sounds like the next step is for me to start a conversation in expensify-open-source Slack channel. Do you agree @narefyev91? Thanks!

**Comment by narefyev91** [comment] 2023-09-25 08:33
> Ok, it sounds like the next step is for me to start a conversation in expensify-open-source Slack channel. Do you agree @narefyev91? Thanks!

Agree - let's do it

**Comment by alexpensify** [comment] 2023-09-26 05:33
I've started a discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1695706390193779

**Comment by mvtglobally** [comment] 2023-09-28 03:21
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2023-09-28 07:22
Ok, @narefyev91 - could you please test too and verify if we should close? Thanks!

**Comment by narefyev91** [comment] 2023-09-28 07:41
@alexpensify not reproduced on latest main

https://github.com/Expensify/App/assets/28352309/d5e6008b-46e4-4a1c-890a-6500fbc461c2

**Comment by alexpensify** [comment] 2023-09-28 07:48
Thanks, closing since this issue has been fixed by some other update. There will be no payments since this issue was fixed elsewhere.

**Closed by alexpensify** 2023-09-28 07:48 UTC
Labels: External, Daily, Help Wanted, Bug
