### ISSUE TITLE
[HOLD #21361][$1000] Unassigned task report shows a clickable avatar which changes profile pictures each time we click it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21635] opened 2023-06-26 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB.
2. Click on assign task.
3. Enter title.
4. Click on share somewhere and choose a destination. Don't choose any assignee.
5. In the new task report, notice that after "to" an avatar is shown.
6. Click on the avatar and RHN should open up to choose assignee. Click outside and avatar changes.

## Expected Result:
Avatar shouldn't be shown. Task report should show unassigned in some way. If avatar is shown then it should not change each time we click it.

## Actual Result:
An avatar is shown and it changes each time we click it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6e98fd24-6e06-4605-a501-ccbb76824723

https://github.com/Expensify/App/assets/93399543/74ce0590-95ef-4a19-840e-23f12707dfd5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687470693318239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fbfe55dbd253e57</li>
        <li>Upwork Job ID: 1673580849344495616</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-26 21:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unassigned task report shows a clickable avatar which changes profile pictures each time we click it.

### What is the root cause of that problem?
In task report header, avatar is retrieved with `assigneeAccountID`, and `assigneeAccountID` is retrieved with `getTaskAssigneeAccountID` in `Task.js`.
https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/components/TaskHeader.js#L51-L53
Because task report is unassigned, `assigneeAccountID` should be null, but `getTaskAssigneeAccountID` does not check `childManagerEmail` is empty or not.
https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/libs/actions/Task.js#L640-L652

So incorrect account id is returned, and avatar will be set to default avatar, and that avatar will be changed each time we call `UserUtils.getAvatar`.

### What changes do you think we should make in order to solve the problem?
We should return null account id in `getTaskAssigneeAccountID` if task is not assigned.
```js
function getTaskAssigneeAccountID(taskReport) {
    if (!taskReport) {
        return null;
    }

    if (taskReport.managerID) {
        return taskReport.managerID;
    }

    const reportAction = ReportActionsUtils.getParentReportAction(taskReport);
    const childManagerEmail = lodashGet(reportAction, 'childManagerEmail', '');
+   if (childManagerEmail === '') {
+       return null;
+   }
    return PersonalDetailsUtils.getAccountIDsByLogins([childManagerEmail])[0];
}
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by kadiealexander** [comment] 2023-06-27 06:38
Just checking on the expected behaviour [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1687847867233079?thread_ts=1687753942.617509&cid=C01SKUP7QR0).

**Comment by Nikhil-Vats** [comment] 2023-06-27 07:22
The report headers are being updated for all report types in #20844. So, we can put this on hold for the time being.

cc @thienlnam

**Comment by kadiealexander** [comment] 2023-06-28 05:11
Ah yeah, it is similar. Thanks @thienlnam!

**Comment by kadiealexander** [comment] 2023-07-07 04:56
Still on hold.

**Comment by kadiealexander** [comment] 2023-07-19 07:05
This is fixed 🎉 closing as a fixed dupe of https://github.com/Expensify/App/issues/21361

**Closed by kadiealexander** 2023-07-19 07:05 UTC
Labels: External, Weekly, Overdue, Bug
