### ISSUE TITLE
[$500] Chat - Infinite loading occurs after enabling the internet

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34577] opened 2024-01-16 13:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with 2 separate accounts in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. From the main + menu, create a money request with the account logged in the secondary device
4. In the secondary device request money to the main testing device account
5. Enable the internet connection in in the main testing device, the money request request will be sent and will get a response an error.
6. Verify that the chat row in the LHN appears greyed out with a solid red dot icon
7. Click into the chat that failed to create that have a red dot
8. Verify you see an error message in-line beneath the welcome message because it failed to be created.
9. Tap/click the X on the Report no longer exists error to dismiss the error message
10. Verify the chat is deleted and removed from the LHN
11. Verify you are routed to your chat with Concierge

## Expected Result:
After enabled the internet connection in in the main testing device, the money request request will be sent and will get a response an error.

## Actual Result:
Infinite loading occurs after enabling the internet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/43d4a185-ed69-408f-98da-c46a3b291699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115b2b43553abb055</li>
        <li>Upwork Job ID: 1747315684569538560</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 28124444</li>
</ul></li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2024-01-16 15:05
Attempting to reproduce on prod...

**Comment by arosiclair** [comment] 2024-01-16 15:36
Reproduced in staging **v1.4.25-7**

<img width="1486" alt="Screenshot 2024-01-16 at 10 36 33 AM" src="https://github.com/Expensify/App/assets/6833644/db7880f8-643e-4c1d-a113-884705516b65">

**Comment by arosiclair** [comment] 2024-01-16 16:10
Nothing obvious is jumping out to me in the deploy's PR list or diff. This may be a backend issue

**Comment by arosiclair** [comment] 2024-01-16 16:29
Okay it seems the `RequestMoney` command fails and correctly sets the error for the report already existing. However, the following `OpenReport` command clears the report by setting it to `null`. This triggers the loading view since `isReportReadyForDisplay` would evaluate to `false` [here](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js#L251).

<img width="400" alt="Screenshot 2024-01-16 at 11 18 18 AM" src="https://github.com/Expensify/App/assets/6833644/25013861-0880-41b3-9aa0-44bd54ecab09">

<img width="400" alt="Screenshot 2024-01-16 at 11 19 24 AM" src="https://github.com/Expensify/App/assets/6833644/56842eb2-e435-4110-9562-9b718bd4de1a">

**Comment by arosiclair** [comment] 2024-01-16 17:46
Can't find anything in the current deploy that might have caused this. This is also an edge case so I don't think this needs to be a blocker so removing the label

**Comment by DylanDylann** [comment] 2024-01-17 12:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - Infinite loading occurs after enabling the internet
### What is the root cause of that problem?
- After turning on the network, in main device, calling "RequestMoney" returns the error "There is a previously existing chat between these users.". (It is because in secondary device, we have created the chat between two user)

- Then, in the main device, call "OpenReport" will set the current report to null so the [isReportReadyForDisplay](https://github.com/Expensify/App/blob/a8acf44090c9aab4e9af7967a79758472ada8fc3/src/pages/home/ReportScreen.js#L246-L252) is false.

- In [ReportScreen](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js), we display the "loading indicator" because the ```isReportReadyForDisplay``` is false and [shouldShowNotFoundPage](https://github.com/Expensify/App/blob/a8acf44090c9aab4e9af7967a79758472ada8fc3/src/pages/home/ReportScreen.js#L453-L464) is false (If ```shouldShowNotFoundPage``` is true, it will display the FullPageNotFoundView rather than "loading indicator":
- Additionally, ```shouldShowNotFoundPage``` is false because [wasReportAccessibleRef](https://github.com/Expensify/App/blob/a8acf44090c9aab4e9af7967a79758472ada8fc3/src/pages/home/ReportScreen.js#L178) is set to true in the below:
https://github.com/Expensify/App/blob/a8acf44090c9aab4e9af7967a79758472ada8fc3/src/pages/home/ReportScreen.js#L198-L203

### What changes do you think we should make in order to solve the problem?
- We can display the FullPageNotFoundView in this case. Do it by create a ref called ```wasReportAccessibleButNowNotRef = useRef(false)``` and update it to true in the below logic:
```
    useEffect(() => {
        if (!prevReport.reportID && wasReportAccessibleRef.current && !wasReportAccessibleButNowNotRef.current) {
            wasReportAccessibleButNowNotRef.current = true;
        }
    }, [prevReport.reportID, wasReportAccessibleRef]);
```
- Then, update the [shouldShowNotFoundPage](https://github.com/Expensify/App/blob/a8acf44090c9aab4e9af7967a79758472ada8fc3/src/pages/home/ReportScreen.js#L453-L464) to:
````diff
   const shouldShowNotFoundPage = useMemo(
        () =>
            (!wasReportAccessibleRef.current &&
                !firstRenderRef.current &&
                !report.reportID &&
                !isOptimisticDelete &&
                !reportMetadata.isLoadingInitialReportActions &&
                !isLoading &&
                !userLeavingStatus) ||
            shouldHideReport ||
+          wasReportAccessibleButNowNotRef.current,
        [report, reportMetadata, isLoading, shouldHideReport, isOptimisticDelete, userLeavingStatus],
    );
````
### What alternative solutions did you explore? (Optional)

- NA

**Comment by DylanDylann** [comment] 2024-01-18 08:10
@arosiclair When we refresh the page, it will display the FullPageNotFoundView, so I think displaying the FullPageNotFoundView is also an option

**Comment by arosiclair** [comment] 2024-01-18 16:01
> @arosiclair When we refresh the page, it will display the FullPageNotFoundView (in staging), so I think displaying the FullPageNotFoundView can also be an option

Yes that is fine after refreshing the page, but before that, the user should be able to see the error explaining why the request they made disappeared.

**Comment by mallenexpensify** [comment] 2024-01-24 03:32
@ntdiary reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by NicMendonca** [comment] 2024-01-26 21:30
@aimane-chnaif assigned you! Thanks!

**Comment by mvtglobally** [comment] 2024-01-30 04:57
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2024-01-30 07:24
@mvtglobally I still can reproduce in staging

**Comment by DylanDylann** [comment] 2024-01-30 07:59
- @arosiclair @aimane-chnaif  The RCA of this issue is that we try to create a request money to the reportID that we already had a report before, so the API ```RequestMoeny``` will encounter the error "There is a previously existing chat between these users."
- Should BE return the ```preexistingReportID``` rather than the above error in this case? Because we have a logic that handle the similar case: https://github.com/Expensify/App/blob/fe1655f0d268dcab7ec08f2743d8347f939589de/src/libs/actions/Report.ts#L1057-L1059

**Comment by arosiclair** [comment] 2024-01-30 15:12
> Should BE return the preexistingReportID rather than the above error in this case? Because we have a logic that handle the similar case:

That seems like a possible alternative, but we'd prefer to keep the original behavior. Have you looked into this yet?

> It seems that the OpenReport call is coming from the ReportActionsView [here](https://github.com/Expensify/App/blob/409dee18c397a2db866e9f1b368d41d959671fd4/src/pages/home/report/ReportActionsView.js#L113). Calling OpenReport there seems unnecessary since it's already handled in the ReportScreen. I think we should probably get rid of it, but I'm not sure.

**Comment by DylanDylann** [comment] 2024-01-30 16:30
> It seems that the OpenReport call is coming from the ReportActionsView [here](https://github.com/Expensify/App/blob/409dee18c397a2db866e9f1b368d41d959671fd4/src/pages/home/report/ReportActionsView.js#L113). Calling OpenReport there seems unnecessary since it's already handled in the ReportScreen. I think we should probably get rid of it, but I'm not sure.

I checked it but I see that at the first time the OpenReport is called, it sets the report to null

**Comment by NicMendonca** [comment] 2024-01-31 19:40
Starting leave so re-assigning!

**Comment by kadiealexander** [comment] 2024-02-06 22:04
@aimane-chnaif @arosiclair are we just waiting on proposals or is there anything more we can do to get this over the line?

**Comment by arosiclair** [comment] 2024-02-07 14:20
Yes waiting on proposals still

**Comment by arosiclair** [comment] 2024-03-12 14:00
@kadiealexander can you just do a C+ payment for @aimane-chnaif? PR was deployed a couple weeks ago. Thanks

**Comment by kadiealexander** [comment] 2024-03-14 22:21
Payouts due:

- [x] Contributor+: $500 @aimane-chnaif

Upwork job is [here](https://www.upwork.com/nx/wm/workroom/36401248/overview).

**Closed** 2024-03-14 22:22 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
