### ISSUE TITLE
[$1000] Update Concierge icon

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12264] opened 2022-10-28 18:10 UTC
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project.

**What is it:**
Replace the Concierge bell icon with a new icon

![image](https://user-images.githubusercontent.com/2319350/198704097-3751b666-f395-4001-96e0-1e8f7a23c651.png)

**Does it require a mini design doc:**
No

**Design finished:**
Maybe? 

cc @GabiHExpensify 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115bd027f7f77fe7b</li>
        <li>Upwork Job ID: 1600615237124608000</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2022-11-02 16:32
For completeness, we would like to show this new icon for Concierge only in NewDot and leave the current Concierge avatar in other platforms.

**Comment by NikkiWines** [comment] 2022-11-02 16:44
@shawnborton could you link/post the svg format of the new concierge icon?

**Comment by shawnborton** [comment] 2022-11-02 16:52
Can do! Is it better to have it with or without the roundedness?

**Comment by NikkiWines** [comment] 2022-11-02 17:00
Hmmm with roundedness for now, I think! That might change with the broader default icon application though 🤔

**Comment by NikkiWines** [comment] 2022-11-02 17:42
Actually, @shawnborton I think I can just use the one you sent earlier if that's fine by you. We'd need to add it to web-static

<details closed>
<summary>Large Concierge Icon (png)</summary>
<br>

![concierge2022](https://user-images.githubusercontent.com/16747822/199562596-1e37a911-4dd4-4d92-bddb-773c82eecce7.png)

</details>

**Comment by NikkiWines** [comment] 2022-11-02 17:46
And then for implementation, I think it's fairly simple. 


For now,  we'd just make a new const `CONCIERGE_ICON_URL: ${CLOUDFRONT_URL}/images/concierge_2022.png` in [CONST.js](https://github.com/Expensify/App/blob/78d322fdda047707cb6a5243f321183db63dd10b/src/CONST.js)
 and then we can just add the following few lines  in this [_.each statement](https://github.com/Expensify/App/blob/78d322fdda047707cb6a5243f321183db63dd10b/src/libs/OptionsListUtils.js#L109-L119): 

```Javascript
if (login == CONST.EMAIL.CONCIERGE) {
    personalDetail.avatar = CONCIERGE_ICON_URL
}
```

That way we'll only update the avatar in NewDot. Once we consolidate the icons between oldDot and newDot we can remove that code and simply update the avatar stored in concierge@expensify.com's `expensify_personalDetails` NVP.

**Comment by shawnborton** [comment] 2022-11-02 17:47
Let's use an .svg instead to it retains the crisp quality we want. 

Here you go: 
![ExpensifyConciergeIcon](https://user-images.githubusercontent.com/2319350/199563630-972da820-5341-4cb6-a226-393a6479eddd.svg)

**Comment by shawnborton** [comment] 2022-11-02 17:50
(I uploaded a new version above to fix the weird star

**Comment by NikkiWines** [comment] 2022-11-02 17:52
Oh and if we also want to update the [Help Site](https://help.expensify.com/) we'd just need to update [this icon](https://github.com/Expensify/App/blob/334b2107fe9cfa06ac7bbd26841a55509bb34486/docs/assets/images/concierge-avatar.svg). 

It looks like it's not quite the same as the current concierge icon (more blue background) so not sure if we'd want an alternative new icon as well

**Comment by mountiny** [comment] 2022-11-02 17:57
Nice solution!

**Comment by JmillsExpensify** [comment] 2022-11-02 19:11
Wow, nice progress on this in such a short amount of time @NikkiWines. This is super exciting!

**Comment by NikkiWines** [comment] 2022-11-03 11:02
Thanks everyone 😊

@shawnborton did we want to also update the [Help Site](https://help.expensify.com/) or shall we leave that concierge icon as is?

**Comment by NikkiWines** [comment] 2022-11-03 12:31
Also, it looks like we're unable to render svgs for iOS and Android apps (works fine on web, desktop, and mweb) so we'll need to use the png version of the icon. Is the one from [this comment](https://github.com/Expensify/App/issues/12264#issuecomment-1301003231) ok?

**Comment by shawnborton** [comment] 2022-11-03 13:43
We use a lot of svgs for both iOS and Android. All of our one-color icons are svgs, as well as things like room icons and default profile pictures.

**Comment by JmillsExpensify** [comment] 2022-11-03 14:33
Out of curiosity, why not update the Concierge icon on the help site as well?

**Comment by JmillsExpensify** [comment] 2022-11-03 14:33
Only reason I ask is that this new help site is exclusively focused on NewDot, where we're updating Concierge.

**Comment by shawnborton** [comment] 2022-11-03 14:35
Ah good point, is the help site baked into the App repo?

**Comment by mountiny** [comment] 2022-11-03 14:47
> is the help site baked into the App repo?

Yes

**Comment by NikkiWines** [comment] 2022-11-03 15:05
> We use a lot of svgs for both iOS and Android. All of our one-color icons are svgs, as well as things like room icons and default profile pictures.

Sorry, I was unclear here. There are two problems with svgs. For the ios app and android app specifically there's a probably using svgs from a remote resource (like cloudfront, if we pull the icon from https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2022.svg). 

If we keep the image local to the `/assets/` folder (which we definitely can do) that works better but there's a small problem with displaying svgs in full format (across all platforms), like so: 

https://user-images.githubusercontent.com/16747822/199756397-98243215-632c-414e-afa0-966fb8cd92a6.mov

Though, this same issue exists for the fallback avatars, so maybe it's ok? 

https://user-images.githubusercontent.com/16747822/199757851-fb27e608-bbbc-46cc-8229-98109d951e83.mov

**Comment by shawnborton** [comment] 2022-11-03 15:14
Oh wow, do you know why we can't show the full svg image in the attachment modal? Maybe that's a separate problem we can fix?

**Comment by NikkiWines** [comment] 2022-11-03 15:21
I believe it's a limitation of react native, we might be able to get around it by using `SvgComponent` from the `react-native-svg` library, but I personally think that's a separate issue from this one. 

As an aside, the [current icon](https://d2k5nsl2zxldvw.cloudfront.net/images/icons/concierge_2021.png) we're using for concierge is also a png. 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/16747822/199761576-9ee74efc-b215-4a45-aec1-8765c0602f4c.png">

**Comment by NikkiWines** [comment] 2022-11-03 15:22
However, since the full image view of svgs is a known issue, we could use the SVG format for now with the expectation that we'll likely ultimately try to fix the full-view issue.

**Comment by shawnborton** [comment] 2022-11-03 15:27
Cool, I think that sounds like a good plan to me! Mind posting the bug to #expensify-open-source so it gets reported and triaged in the meantime?

**Comment by JmillsExpensify** [comment] 2022-11-03 18:27
Just to come back to the help site, I do think we should implement the new icon.

**Comment by shawnborton** [comment] 2022-11-03 18:34
Yup I agree, and then we should include the help site as part of what gets all of the other core brand ingredient updates too cc @Luke9389 @grgia

**Comment by Luke9389** [comment] 2022-11-03 18:55
Interesting! I just checked out ExpensifyHelp for the first time. 
All of the styles being used in that site are totally separate from the styles we're using on the main app. I'm not sure that this qualifies as deserving it's own doc, but I also don't think we should lump it in to the Implement New Core Branding doc (sheerly bc I don't want to loose momentum by having a v2 and re-review). 

Maybe we could just make this it's own issue? I would be happy to do it. 
I don't think it violates the process at all to have an issue called "Make ExpensifyHelp Styles Match New Dot".
I'd just spin up a PR there and we'd be done pretty fast. 

What do y'all think?

**Comment by shawnborton** [comment] 2022-11-03 19:35
Spoke offline but given that the help site is part of the App repo and part of NewDot, it makes sense to include it in the doc.

**Comment by JmillsExpensify** [comment] 2022-11-03 20:10
Agree with that!

**Comment by NikkiWines** [comment] 2022-11-04 10:07
@shawnborton looking into this implementation more, I think we should the method I mentioned [here](https://github.com/Expensify/App/issues/12264#issuecomment-1301008199) using a png hosted on cloudfront. It's the simplest implementation that allows us to get this over the line with sufficient #urgency. 

To use an SVG we'll have to update the props for every location that passes a user avatar (18 files) to accept a function (the image file) and not just a URL string. The only icon that would be passing an SVG is the concierge icon. 

It would make undoing this logic once we eventually update the icon in OldDot that much more difficult to roll back. Additionally, right now we don't support uploading SVG's as profile photos in oldDot or newDot. 

Lastly, we can't even view the full-sized svg in NewDot right now, so the increase in crispness that using an SVG would provide is invisible for the moment.

**Comment by mountiny** [comment] 2022-11-04 10:33
@NikkiWines This makes a lot of sense to me. Feels like an anti-pattern to go with SVG knowing there is a bug and also that we would eventually go back to png. 

I think if we use png of high enough resolution it should be more than fine. After all most of the time users see the icon in the small avatar form and rarely they open the expanded view where the svg would be ultimately better.

All an all it does not feel like the SVG support is worth this only for Concierge avatar. We can create a `Feature request` to allow using svg as avatars for anyone to simplify stuff and then we could switch to Concierge being svg, but that does not fit to WAQ imho

**Comment by shawnborton** [comment] 2022-11-04 15:14
Okay cool, thank you @NikkiWines for spelling all of that out and I agree with you, let's do PNG for now. 

Here is an even more high res version we can use: [Expensify-ConciergeIcon.png.zip](https://github.com/Expensify/App/files/9939664/Expensify-ConciergeIcon.png.zip)

**Comment by NikkiWines** [comment] 2022-11-04 15:49
Sounds good!!

**Comment by Luke9389** [comment] 2022-11-04 19:20
@NikkiWines, are you planning on switching the Concierge icon on Expensify Help in this issue? I have a separate issue to update the styling of Expensify Help, so I could do it over there if you prefer. LMK, I haven't looked into it yet just in case you were already on it.

**Comment by NikkiWines** [comment] 2022-11-07 08:19
@Luke9389 I defer to @shawnborton for that one! I wasn't sure if we wanted to update it as part of this issue since the current concierge icon on the Help site is slightly different than the one used in NewDot.

**Comment by NikkiWines** [comment] 2022-11-08 16:40
Ok, great! I'll update it as part of this issue then.

**Comment by NikkiWines** [comment] 2022-11-08 18:47
@shawnborton would we also want to update the concierge icon used here? Do we have a single color version of the new icon yet? 

![Screen Shot 2022-11-08 at 10 46 37](https://user-images.githubusercontent.com/16747822/200649637-ff6f69cd-6261-4538-9938-bf8422d6b593.png)

**Comment by shawnborton** [comment] 2022-11-08 18:50
Yup! You could leave it as-is for now and then we can update it as part of this [GH here](https://github.com/Expensify/App/issues/12442) (cc @Luke9389), or you can update it now with the following: [concierge.svg.zip](https://github.com/Expensify/App/files/9964258/concierge.svg.zip)

**Comment by NikkiWines** [comment] 2022-11-08 18:54
Great, thanks! I think let's have that updated as part of https://github.com/Expensify/App/issues/12442 since it falls under the single color icons being updated there and not the full-color verison that's being updated here.

**Comment by shawnborton** [comment] 2022-11-08 19:06
Works for me!

**Comment by JmillsExpensify** [comment] 2022-11-11 02:26
Circling back on the SVG convo above, we're going to work on that on in https://github.com/Expensify/App/issues/12658.

**Comment by mananjadhav** [comment] 2022-12-07 04:46
@JmillsExpensify @NikkiWines Can anyone of you help me the Upwork payment here? It's hit production and completed the 7 days regression period.

**Comment by JmillsExpensify** [comment] 2022-12-07 22:16
Sure thing. Upwork job is immediately above.

**Comment by JmillsExpensify** [comment] 2022-12-07 22:18
@NikkiWines Not sure why this wasn't closed but I'm going to do so once @mananjadhav is paid out. Cool?

**Comment by NikkiWines** [comment] 2022-12-07 22:50
Yeah not sure why it didn't close, since https://github.com/Expensify/App/pull/12425 references this issue. But yes that sounds good 👍

**Comment by NikkiWines** [comment] 2022-12-07 22:50
Also weird that this issue suddenly showed up [here](https://expensify.slack.com/archives/C049HHMV9SM/p1670451442253109)...

**Comment by JmillsExpensify** [comment] 2022-12-08 02:39
Hmm, yeah that's super odd.

**Comment by JmillsExpensify** [comment] 2022-12-08 02:41
Also invitation sent for @mananjadhav. I suspect he'll accept shortly and we can close this out.

**Comment by mananjadhav** [comment] 2022-12-08 03:40
Accepted @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-12-08 03:42
Thanks, I just sent you the offer. Accept there and I'll pay you out now.

**Comment by JmillsExpensify** [comment] 2022-12-08 03:43
Alright, all paid out! Thanks ya'll, I'm closing this one.

**Closed by JmillsExpensify** 2022-12-08 03:43 UTC
Labels: Reviewing, External, Engineering, Daily, NewFeature, Design
