### ISSUE TITLE
[$1000] Workspace -User needs to tap ‘Back’ twice to return to previous screen from ‘Connect BA' offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21277] opened 2023-06-21 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify App / iOS
2. Log in with Expensifail account
3. Create or go to any workspace
4. Go to 'Settings'
5. Go OFFline
6. Go to any screen with 'Connect bank account' feature (e.q. 'Cards')
7. Tap to 'Connect bank account'
8. User moves to screen with info 'Your WS currency set to different currency then USD'
9. Tap 'Back'

## Expected Result:
User moves to previous screen

## Actual Result:
The user remained on the same screen. To go to the previous screen user needs tap 'Back' again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/17d37ed0-7b0c-43f9-ba75-17893cf0c79b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb0f281e371868b5</li>
        <li>Upwork Job ID: 1671972100571131904</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27049536</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-06-21 23:36
was able to reproduce

https://github.com/Expensify/App/assets/98560306/d6a57a50-dc57-423c-b463-e33716de0ec6

**Comment by hayata-suenaga** [comment] 2023-06-21 23:38
so weird only happens when the device is offline...

**Comment by hayata-suenaga** [comment] 2023-06-21 23:42
I edited the Action Performed section of OP because the selection of current doesn't matter for reproduction of the issue

**Comment by hayata-suenaga** [comment] 2023-06-21 23:51
the issue is also present on web

https://github.com/Expensify/App/assets/98560306/0c551aac-cfad-4998-95f5-86da1efad697

**Comment by hayata-suenaga** [comment] 2023-06-21 23:54
The bug doesn't prevent the usage of NewDot, and the problem only happens offline.

I don't believe this is a deploy blocker. Removing `DeployBlockerCash` label and assigning `bug` label.

I'll keep assigning myself for the internal engineer assignment when the proposal is accepted.

**Comment by bernhardoj** [comment] 2023-06-22 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to back twice from Connect Bank Account if we open it while offline.

### What is the root cause of that problem?
When we navigate back, the page will be re-rendered, even though technically no props/state is changed. After digging around, I found that `withPolicy` HOC triggers the rerender when we navigate back (this happens on every page). It's because the passed props here are always treated as new prop even though it contains the same value. It's like we pass an inline object to a prop.
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/pages/workspace/withPolicy.js#L95-L103

What happens when the page is re-rendered? `componentDidUpdate` is called and this part of the code is responsible to bring back the user to the same bank account page.
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L156-L171

As you can notice, we already prevent it if `currentStepRouteParam === currentStep`.
`currentStepRouteParam` is from param (`stepToOpen`), which it's initial value is an empty string.
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L202-L219
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/ROUTES.js#L21

`currentStep` is from `reimbursementAccount.achData.currentStep`. We get this from the API and fallback to `BankAccountStep`.

Because `'' !== 'BankAccountStep'`, the navigation happens and it will now navigate with `stepToOpen = new`. 
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L225-L241
That's why we can close it the 2nd time because `currentStepRouteParam` value is now `BankAccountStep`.

Next, why it doesn't happen while online?

`currentStepRouteParam` initial value is also empty. The difference is, while online we are doing an API request. When the API starts, we set `isLoading` to true which trigger `componentDidUpdate` and will execute the navigation code above. This will update `currentStepRouteParam` to `BankAccountStep`. So, when we close the page, `currentStepRouteParam === currentStep` is true and an early return happens.

-------
In summary,
If `currentStepRouteParam` is not equal to `currentStep`, we will navigate to the bank account page
while offline, `currentStepRouteParam` is empty and `currentStep` is `BankAccountStep`, navigate back will trigger above
while online, `currentStepRouteParam` is initially empty, but then updated after the API starts and now has a value of `BankAccountStep`. `currentStep` is also `BankAccountStep`. No navigation happens when going back.

### What changes do you think we should make in order to solve the problem?

Instead of empty `stepToOpen`, we can pass `new`.
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/libs/actions/ReimbursementAccount/navigation.js#L21-L23
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/libs/ReportUtils.js#L373-L375

However, I don't know if it's intended to pass an empty `stepToOpen` because the value is being used in API params.
https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/libs/actions/BankAccounts.js#L294-L300
When we open the page, it will call the API with empty `stepToOpen`.

**Comment by hayata-suenaga** [comment] 2023-06-22 20:02
This issue is reproducible. making this issue `external` cc: @adelekennedy 

@bernhardoj thank you so much for the detailed review. If you have time, can you check if [this ongoing navigation refactoring](https://github.com/Expensify/App/issues/11768) will affect your solution?

We might need to put a hold on this

**Comment by hayata-suenaga** [comment] 2023-06-22 20:04
removing @isabelastisser as @adelekennedy is already assigned to this issue

**Comment by bernhardoj** [comment] 2023-06-23 08:51
@hayata-suenaga I did more investigation and I think it won't conflict with the navigation reboot follow-up issues. I have updated my proposal putting my latest finding on the root cause.

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 20:02
@hayata-suenaga 

I think this issue is kind of a low priority maybe let's just wait for `Implement New Navigation` until then we can make this weekly.

Let's prioritize @bernhardoj's proposal when it comes off hold, what do you say?

**Comment by hayata-suenaga** [comment] 2023-06-23 20:06
@Santhosh-Sellavel sounds link a plan. Marking this as weekly 👍

**Comment by hayata-suenaga** [comment] 2023-07-03 18:58
@Santhosh-Sellavel can you check the above comment when you have time 🙇 ?

**Comment by adelekennedy** [comment] 2023-07-11 20:18
@Santhosh-Sellavel does this still need to be on [hold](https://github.com/Expensify/App/issues/21277#issuecomment-1615840536)? Or iyo could we move this forward?

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 22:04
Ah sorry guys [Hold] Made me miss this

@bernhardoj 

Can you reiterate what you are saying here,  you are referring to the same issue twice? and That's closed now!
> Okay, I found that we are going to navigate the whole page here #21218. Also, honestly, I don't know what to wait from the navigation refactor because the refactor is already done, right? So, I think we should hold on #21218 instead. I'm pretty sure the problem will be gone after the connect bank account page refactor is done, but let's just hold it in case it's not.
> 
> cc: @Santhosh-Sellavel @hayata-suenaga

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 22:08
@hayata-suenaga 

We were on hold for this

> This issue is reproducible. making this issue `external` cc: @adelekennedy
> 
> @bernhardoj thank you so much for the detailed review. If you have time, can you check if [this ongoing navigation refactoring](https://github.com/Expensify/App/issues/11768) will affect your solution?
> 
> We might need to put a hold on this cc: @Santhosh-Sellavel

And now this is complete. So we can resume this now

@bernhardoj If you have any changes proposal make it. Let me know if not required or after making changes. I will review it then, thanks!

**Comment by hayata-suenaga** [comment] 2023-07-21 16:20
@bernhardoj is this the issue you're referring to?

**Comment by hayata-suenaga** [comment] 2023-07-21 16:49
@bernhardoj sorry my mistake here is the link 😓 :https://github.com/Expensify/App/issues/22901

**Comment by Santhosh-Sellavel** [comment] 2023-07-29 00:34
Sorry for the delay. 

But this is no longer reproducible. While offline we show that, it's not allowed while offline. Is there any flow that still where we face this error @bernhardoj? let me know if I missed something

<img width="638" alt="Screenshot 2023-07-29 at 6 02 36 AM" src="https://github.com/Expensify/App/assets/85645967/33dd24cb-ddfc-4daf-bd26-d255dc670b85">

**Comment by hayata-suenaga** [comment] 2023-08-21 18:00
[The issue](https://github.com/Expensify/App/issues/11768) that was holding this issue was closed. @Santhosh-Sellavel could you check if we can remove hold and move to a solution? 🙇 🙇 🙇

**Comment by Santhosh-Sellavel** [comment] 2023-08-22 18:07
This is what I get, it doesn't look like a problem to me.

https://github.com/Expensify/App/assets/85645967/4a3901bc-0479-44c0-a4d5-e415243ceadf

**Comment by Santhosh-Sellavel** [comment] 2023-08-23 06:30
> @Santhosh-Sellavel you need to open the one that doesn't have the `/new` in the link

Can you update the link in the steps you've shared?

**Comment by Santhosh-Sellavel** [comment] 2023-08-23 16:34
How can we get a link without new?

**Comment by Santhosh-Sellavel** [comment] 2023-08-23 16:35
In any flow, will we get a link without new?

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 22:15
Still, I don't see any problem. I can't reproduce the issue anymore using this [steps](https://github.com/Expensify/App/issues/21277#issuecomment-1688649416). @hayata-suenaga Can you confirm, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 18:08
> Here is the reproduction steps Prerequisite: have a workspace with a currency set to other than USD
> 
> 1. Turn off your internet connection
> 2. Send your workspace bank account link (`staging.new.expensify.com/bank-account?policyID={your_workspace_id}`) to a chat
> 3. Click/press the link to open the bank account page. Verify you see a message that tells you to change your currency to USD.
> 4. Press the back button
> 
> Expected: the bank account page is closed Actual: you arrive at the same page
> 
> @Santhosh-Sellavel

@lanitochka17 Can you reproduce this issue now using the above steps?

**Comment by izarutskaya** [comment] 2023-08-30 22:14
@Santhosh-Sellavel When I click/press the link - I see "Hmm... it's not here" page and when I press the back button - I return to the Workspace page

https://github.com/Expensify/App/assets/115492554/9ab8d344-32f4-4315-b7c0-aa93d3b0b572

**Comment by izarutskaya** [comment] 2023-09-04 13:24
Sorry, @bernhardoj  I tested again. Yes, arrive at the same page

https://github.com/Expensify/App/assets/115492554/36faaa5f-1b33-4fc5-bc1c-f471f9c864d0

**Comment by hayata-suenaga** [comment] 2023-09-04 17:35
@bernhardoj @Santhosh-Sellavel 

do we have a proposal we can accept?

**Comment by Santhosh-Sellavel** [comment] 2023-09-04 17:37
We have no issues here, we can close this one @hayata-suenaga!

**Comment by Santhosh-Sellavel** [comment] 2023-09-05 16:15
> QA can still reproduce the issue [#21277 (comment)](https://github.com/Expensify/App/issues/21277#issuecomment-1705271767)

Sorry, I misread that.

**Comment by Santhosh-Sellavel** [comment] 2023-09-05 16:17
@adelekennedy Can you assign a new C+ here by applying an external label here, unassigning this one due to low bandwidth, thanks!

**Comment by hayata-suenaga** [comment] 2023-09-05 17:00
@ArekChr

@Santhosh-Sellavel had to un-assign themselves. Could you review the conversation so far and check if we need a fix for this one and is so, could you review proposals?

You can also ask @bernhardoj for the context as they're involved in the discussion so far

**Comment by ArekChr** [comment] 2023-09-06 07:52
@hayata-suenaga I will be available to review next week, Today I'm quite busy, and tomorrow will be at RNEU conference

**Comment by hayata-suenaga** [comment] 2023-09-12 05:40
@ArekChr please review proposals when you have time

**Comment by ArekChr** [comment] 2023-09-12 07:38
@hayata-suenaga I couldn't reproduce this issue.

https://github.com/Expensify/App/assets/24796318/d17c92b1-bcd3-4e91-be17-de708737bbf6

**Comment by ArekChr** [comment] 2023-09-12 07:46
@bernhardoj How to get workspace id?

**Comment by ArekChr** [comment] 2023-09-12 08:29
https://github.com/Expensify/App/assets/24796318/ae23815c-a88d-4f33-8889-936358c70d6e

**Comment by ArekChr** [comment] 2023-09-13 11:01
@bernhardoj I couldn't reproduce it on the latest main branch using Chrome and Safari. I produced steps 20 times with no issue mentioned in the description.

**Comment by mvtglobally** [comment] 2023-09-13 17:20
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2023-09-18 08:25
If we're unable to reproduce should we close @hayata-suenaga @ArekChr?

**Comment by hayata-suenaga** [comment] 2023-09-21 01:40
@ArekChr do we have a proposal that we can go with?

**Comment by adelekennedy** [comment] 2023-09-25 06:16
It looks like this is still reproducible, @ArekChr do you have an opinion on any of the proposals above

**Comment by hayata-suenaga** [comment] 2023-09-27 08:13
@ArekChr kindly bumping 🙇

**Comment by hayata-suenaga** [comment] 2023-09-28 00:59
bumpbed @ArekChr in the #contributor-plus channel

**Comment by adelekennedy** [comment] 2023-10-02 09:46
@hayata-suenaga will review the proposal above (please Melvin, it was the weekend!)

**Comment by hayata-suenaga** [comment] 2023-10-06 02:15
ah that's a very simple solution if we can get the ID from the Onyx data we already subscribe. Let's go with @bernhardoj 🚀

**Comment by hayata-suenaga** [comment] 2023-10-06 12:55
if the issue has been fixed, I don't think we need to create a PR for this.

@adelekennedy please check if the issue reporter needs to be paid 🙇 Otherwise this PR can be closed

**Comment by adelekennedy** [comment] 2023-10-09 15:40
This was applause internal so no payments due - @peterdbarkerUK @bernhardoj I'm going to end the contract but will not request a refund (I think the $50 doesn't require a refund here)

**Closed by adelekennedy** 2023-10-09 15:40 UTC
Labels: External, Engineering, Daily, Overdue, Bug
