### ISSUE TITLE
mWeb - Cursor is missing after adding an emoji.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11221] opened 2022-09-22 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found we executing PR** https://github.com/Expensify/App/pull/11033

## Action Performed:
1. Go to any chat
2. Verify that you can type text in the composer.
3. Open emoji picker
4. Verify that you can add emojis, and that cursor position is after emoji.

## Expected Result:
Verify that cursor position is after emoji.

## Actual Result:
Cursor is missing after adding an emoji.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.5.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191844565-18f57edd-fcae-4c13-b150-29d43b8106e6.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-09-23 17:20
This is probably being introduced here https://github.com/Expensify/App/pull/11033

**Comment by luacmartins** [comment] 2022-09-23 17:21
Actually, I can reproduce this on prod. So nvm my comment above.

**Comment by francoisl** [comment] 2022-09-27 18:40
I can't reproduce on mWeb, neither on staging nor production on an iOS simulator. And I also can't reproduce on my Android device.


https://user-images.githubusercontent.com/2229301/192608910-e243a8ca-d9a0-4b98-89a5-eca2058e33ae.mov

It looks like various discussions point to https://github.com/Expensify/App/issues/11239 / https://github.com/Expensify/App/pull/11036 being reverted, so I imagine this was possibly a side effect of that PR that was also fixed by reverting. Going to wait for the next deploy to see if it's popping up again, otherwise will close this.

**Closed** 2022-09-28 17:29 UTC
Labels: Engineering, Daily
