### ISSUE TITLE
[$500] Domain Card - User can edit the date in expenses related to the assigned domain card

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36616] opened 2024-02-15 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** tester+domaincard@applausecard.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Log in with [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com)
3. Navigate to the workspace chat for "Domain Card tests - DO NOT DELETE"
4. Verify there's a report that contains the expenses related to the assigned domain card
5. Click on the report
6. Verify you can see the individual expenses
7. Click on a individual expense
8. Verify the fields "Amount" and "Date" are not editable

## Expected Result:
Fields "Amount" and "Date" are not editable

## Actual Result:
User has access to edit the date.
(User receives an error after editing the date, but can try to do it)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b0d0005b-885b-42da-9570-5bdc070f27b0

https://github.com/Expensify/App/assets/78819774/a19bd932-cb63-4b24-a708-2d9bde3896de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010604e6d9dd675bc1</li>
        <li>Upwork Job ID: 1758194441775136768</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-15 18:20
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by FitseTLT** [comment] 2024-02-15 18:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Domain Card - User can edit the date in expenses related to the assigned domain card

### What is the root cause of that problem?
The [canEditFieldOfMoneyRequest](https://github.com/Expensify/App/blob/1c0d126ffb34e1fd103c9f6067b76af688638d47/src/libs/ReportUtils.ts#L2134-L2135) logic doesn't align with the BE requirements to allow editing 
### What changes do you think we should make in order to solve the problem?

We should add a code here
https://github.com/Expensify/App/blob/1c0d126ffb34e1fd103c9f6067b76af688638d47/src/libs/ReportUtils.ts#L2167-L2168
```
if (fieldToEdit === CONST.EDIT_REQUEST_FIELD.DATE) {
        if (TransactionUtils.isCardTransaction(transaction)) {
            return false;
        }
    }
```
or change https://github.com/Expensify/App/blob/1c0d126ffb34e1fd103c9f6067b76af688638d47/src/libs/ReportUtils.ts#L2167-L2168
to
```
    if (fieldToEdit === CONST.EDIT_REQUEST_FIELD.AMOUNT || fieldToEdit === CONST.EDIT_REQUEST_FIELD.CURRENCY || fieldToEdit === CONST.EDIT_REQUEST_FIELD.DATE) {

```
### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment] 2024-02-19 03:03
@miljakljajic Who can edit these fields? Is it that no one should edit these?

**Comment by wildan-m** [comment] 2024-02-20 09:24
Could someone add me to the "Domain Card tests - DO NOT DELETE" group? Alternatively, how can we create the domain card? Can we use a fake card for this purpose?

**Comment by brandonhenry** [comment] 2024-02-23 02:28
Is this accepting proposals?

**Comment by allroundexperts** [comment] 2024-02-23 15:38
@brandonhenry Yes. @miljakljajic Bump on the above [question](https://github.com/Expensify/App/issues/36616#issuecomment-1951612539) 😄

**Comment by miljakljajic** [comment] 2024-02-27 15:50
For non-reimbursable expenses no one should be able to edit the date or amount.

**Comment by allroundexperts** [comment] 2024-03-14 19:10
Missed this completely. Reviewing now.

**Comment by allroundexperts** [comment] 2024-03-14 19:18
Thanks for the proposals @brandonhenry and @wildan-m. @brandonhenry We don't usually add the validation when making the API call. We should disable the menu item like we are doing for other fields.

@wildan-m I see that you've proposed a small change to the proposal @FitseTLT made earlier. However, I think it is really minor and would have been caught during the PR review.

@FitseTLT [proposal](https://github.com/Expensify/App/issues/36616#issuecomment-1946888100) looks good to me. They were the first to propose the correct RCA and the fix.

🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment] 2024-03-18 03:27
Thanks for the discussion here, let's move forward with @FitseTLT 's proposal 👍

**Comment by miljakljajic** [comment] 2024-03-20 15:41
Adding to Wave Collect > Release 1

**Comment by miljakljajic** [comment] 2024-03-22 16:04
The automated offer link doesn't seem to work, keeping this here for a record when payment is due: https://www.upwork.com/nx/wm/workroom/36700816/overview

**Comment by FitseTLT** [comment] 2024-03-25 14:04
PR will be in 2 days

**Comment by robertjchen** [comment] 2024-03-27 06:20
@FitseTLT thanks, let us know when it's ready! 🙇

**Comment by FitseTLT** [comment] 2024-03-29 15:02
PR ready

**Comment by trjExpensify** [comment] 2024-04-16 12:46
@miljakljajic as a bug that doesn't block the release, I'm moving this into `Polish` on the project board.

**Comment by miljakljajic** [comment] 2024-04-16 12:49
Thank you @trjExpensify

**Comment by FitseTLT** [comment] 2024-05-02 15:18
Can we please get a new C+ here? I think @allroundexperts is busy and the pr is stuck for weeks.

**Comment by allroundexperts** [comment] 2024-05-02 15:20
@FitseTLT The checklist is already complete. Apologies for the delay here. If I'm unable to complete the review by tomorrow, we can re-assign.

**Comment by allroundexperts** [comment] 2024-05-03 08:07
@FitseTLT I reviewed this yesterday and left some comments.

**Comment by robertjchen** [comment] 2024-05-28 13:23
Looks like the associated change was deployed- closing this out unless there are any other remaining items?

**Comment by FitseTLT** [comment] 2024-05-29 11:58
@robertjchen Payment hasn't been issued yet, so please re-open it. @miljakljajic Payment is overdue, can u please process the payment, the linked [pr](https://github.com/Expensify/App/pull/39244#issuecomment-2101801929) has been deployed to production three weeks ago. Thx

**Comment by miljakljajic** [comment] 2024-06-06 10:20
paid

**Comment by allroundexperts** [comment] 2024-06-12 09:51
@miljakljajic Can we please have a payment summary here? Thanks!

**Comment by JmillsExpensify** [comment] 2024-07-09 23:04
Reopening for payment summary.

**Comment by miljakljajic** [comment] 2024-07-10 10:45
@allroundexperts is owed 500 USD for work reviewing this PR.

**Closed by miljakljajic** 2024-07-10 10:45 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-07-20 17:16
$500 approved for @allroundexperts
