### ISSUE TITLE
[Payment due now][$250] Send Invoice - Workspace Display Name Not Shown in Invoice Preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43759] opened 2024-06-14 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in with a new Gmail account
2. Create a workspace:
- Navigate to Account Settings > Workspace > Create Workspace
3. Click on the Floating Action Button (FAB) and select "Send Invoice."
4. Add an amount
5. Select a user

## Expected Result:
The First workspace display name should be shown in the invoice preview

## Actual Result:
The workspace display name is not shown in the invoice preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a9eda178-589d-47b7-85f1-e630c84a546c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01097ae7f88895b39c</li>
        <li>Upwork Job ID: 1813230329996618139</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103164810</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-14 11:23
@carlosmiceli  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by carlosmiceli** [comment] 2024-06-14 12:57
I'm not able to reproduce this in either staging or production. Asking someone else to try as well.

**Comment by Julesssss** [comment] 2024-06-14 13:00
Also can't reproduce

**Comment by lanitochka17** [comment] 2024-07-16 12:46
Issue still reproducible on the latest build 9.0.7-4
Only step 5 you need to enter an unknown user

https://github.com/user-attachments/assets/020f69f8-1806-4ae0-859b-7b82cdeec65b

**Comment by brunovjk** [comment] 2024-07-16 20:05
I also couldn't reproduce it (2024-07-16 / v9.0.7-4), did I do something wrong @lanitochka17?

https://github.com/user-attachments/assets/b0ed2da1-d360-4740-add0-65939b58b0e7


@daledah  did you do anything different to reproduce?

Thank you.

**Comment by brunovjk** [comment] 2024-07-17 11:52
Thank you @daledah. I'll try again.

**Comment by brunovjk** [comment] 2024-07-17 17:32
Strange, I still can't reproduce it consistently, but it's missing `policy_` prefix anyway. We can go with @daledah's [proposal](https://github.com/Expensify/App/issues/43759#issuecomment-2231312908)

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-07-17 18:16
Can you reproduce @carlosmiceli?

**Comment by brunovjk** [comment] 2024-07-29 12:01
[PR](https://github.com/Expensify/App/pull/45706) has been in production for 6 days, I thought about filling out the BZ Checklist, but automation is not triggered here. @carlosmiceli, could you help us out? Thank you.

**Comment by carlosmiceli** [comment] 2024-07-29 15:34
@brunovjk sure! do you mean to add the BZ label?

**Comment by brunovjk** [comment] 2024-07-30 11:31
@VictoriaExpensify [PR](https://github.com/Expensify/App/pull/45706) has been in production for 7 days now, can we process the payment here? I need to fill out the BZ checklist as well. Thank you :D

**Comment by brunovjk** [comment] 2024-08-05 11:29
The [PR](https://github.com/Expensify/App/pull/45706) has been in production for over a week, and I don't see any regressions. What are the next steps to process payment and close this issue? Thank you. @carlosmiceli @VictoriaExpensify

**Comment by carlosmiceli** [comment] 2024-08-05 14:17
I'll bring in @mallenexpensify to the conversation, my go-to pro for these kind of issues...

**Comment by mallenexpensify** [comment] 2024-08-07 00:08
Apologies @brunovjk, automation didn't work, updated labels, owner and title, @VictoriaExpensify please pay. Thx

**Comment by VictoriaExpensify** [comment] 2024-08-07 00:20
**Payment Summary:**

Contributor: @brunovjk  paid $250 via Upwork
[Upwork Job](https://www.upwork.com/ab/applicants/1813230329996618139/job-details)

@daledah - Please apply to the [Upwork job](https://www.upwork.com/jobs/~01097ae7f88895b39c) and let me know once you have so that I can pay you

So sorry for the delay @brunovjk

**Comment by brunovjk** [comment] 2024-08-07 00:25
No problem at all, I thank you all :D

**Comment by VictoriaExpensify** [comment] 2024-08-08 02:21
Hey @daledah - just a friendly bump 

 > @daledah - Please apply to the [Upwork job](https://www.upwork.com/jobs/~01097ae7f88895b39c) and let me know once you have so that I can pay you

**Comment by VictoriaExpensify** [comment] 2024-08-12 01:39
Hey @daledah can you please accept the offer in Upwork? https://www.upwork.com/nx/wm/offer/103486400

**Closed** 2024-08-12 06:14 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
