### ISSUE TITLE
[$1000] Settings - Share code - The text goes beyond the borders + error in console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18970] opened 2023-05-15 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18636

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to Settings -> Share code

## Expected Result:
The text should be within the border

## Actual Result:
The text goes beyond the borders + error in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (41)](https://github.com/Expensify/App/assets/93399543/f472914d-7b9f-4626-a98f-149bb8ae23f4)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a529909438a3942d</li>
        <li>Upwork Job ID: 1659311384090259456</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-05-16 06:26
I think that makes sense. Though if it was two names, I think we it would be okay to break the line in between the first and last name. Can you show an example like that?

**Comment by chrispader** [comment] 2023-05-16 09:46
The text ellipsizing is already implemented here: https://github.com/Expensify/App/pull/18946 

You're proposal on changing the qrCodeSize was correct. Otherwise, the `react-native-qr-code-svg` library would divide by 0, which results in `NaN`

**Comment by sonialiap** [comment] 2023-05-18 21:34
Reproducible

**Comment by dukenv0307** [comment] 2023-05-19 04:03
Can't reproduce on staging

**Comment by gadhiyamanan** [comment] 2023-05-19 04:06
We can close this issue as this is [dupe](https://github.com/Expensify/App/issues/18968)

**Comment by NikkiWines** [comment] 2023-05-19 16:25
Thanks @gadhiyamanan - this does indeed appear to be a dupe. Closing!

**Closed by NikkiWines** 2023-05-19 16:25 UTC
Labels: External, Daily, Help Wanted, Bug
