### ISSUE TITLE
[$500] Private Note - Left line/border of quoted text is not visible when hovering over it in Notes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28858] opened 2023-10-04 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.
2. Access any chat.
3. Click on the header and navigate to "Private notes."
4. Go to My note > Notes
5. Enter "> test" and save it.
6. Observe that the left line isn't visible on hovering.

## Expected Result:
The left line should remain visible when hovering

## Actual Result:
 The left line is hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d393f7d5-e16d-49b9-a80a-3b44ccb60de7

https://github.com/Expensify/App/assets/93399543/2b266b24-8eeb-4b24-add8-b7f53beb9c31

https://github.com/Expensify/App/assets/93399543/5ecc3c78-6144-47b5-a758-78f6f6ebf7a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696349601547269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4212fb13e89f5bb</li>
        <li>Upwork Job ID: 1709663891418292224</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27460002</li>
<li>ZhenjaHorbach | Contributor | 27460004</li>
<li>aman-atg | Reporter | 27460007</li>
</ul></li>
    </ul>
</details>

**Comment by dannysanchez559** [comment] 2023-10-04 20:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The left border on quoted text is not visible when hovering in Notes.

### What is the root cause of that problem?
This can be caused by a CSS styling issue. I believe it may be the `hover` attribute

### What changes do you think we should make in order to solve the problem?

make sure the `border-left` attribute in `hover` is working properly and is visible in the `hover` state

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Kunkka0822** [comment] 2023-10-04 21:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The left border on quoted text is not visible when hovering in Notes.

### What is the root cause of that problem?
The reason of this issue is that the color of left bar - blockquote is same as the hover color. - both are rgb(26, 61, 50)

### What changes do you think we should make in order to solve the problem?
We can change the color of blockquote or add hover effect for it.

Like that:
![image](https://github.com/Expensify/App/assets/101172481/0ecd39f4-126b-436d-b6ba-1fbe4ad59e06)

### What alternative solutions did you explore? (Optional)
N/A

Contributor details
Your Expensify account email: kotenkoatem2019@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/maksyml22

**Comment by shawnborton** [comment] 2023-10-05 16:33
I think we should only change the border color on :hover for the notes push rows for private notes. We should keep it the same elsewhere though.

**Comment by shawnborton** [comment] 2023-10-05 18:03
I think we should use our standard border color where ever we can, and only use this exception on hover. 

That being said, I'm actually surprised we're showing the border here: 
<img width="517" alt="CleanShot 2023-10-05 at 14 02 29@2x" src="https://github.com/Expensify/App/assets/2319350/39cfa3ea-ceb7-4c56-989c-7aa53cfdb658">

Why aren't we just rendering this as plain text? That seems odd to me that we'd show that kind of styling in a push-to-page input. cc @Expensify/design for thoughts, as well as @techievivek @JmillsExpensify @trjExpensify

**Comment by shawnborton** [comment] 2023-10-05 23:12
> I have the same thought. But I realize we're supporting markdown on various pages I.e: Welcome message, Task description...

Can you show me examples? I just don't think we should support it in the push-to-page row, especially not the block quote style.

**Comment by trjExpensify** [comment] 2023-10-05 23:51
>Why aren't we just rendering this as plain text? That seems odd to me that we'd show that kind of styling in a push-to-page input. cc https://github.com/orgs/Expensify/teams/design for thoughts, as well as @techievivek @JmillsExpensify @trjExpensify

Yeah, I'm still pretty confused with how the overall implementation of this feature ended up. I mentioned it in thread, but I think we should clean it up. I agree that markdown in push rows seems a little inconsistent. I think people should ultimately be allowed to use markdown in their notes to format them, but given the design of it, we'll likely need the "live markdown" project to show it in place when you focus the note field to re-edit/add to it.

**Comment by techievivek** [comment] 2023-10-06 03:49
Yeah, the issue is that we allow the users to write private notes in **markdown** format, so when we render it in the push-to-page pattern, it looks inconsistent as we only render plain texts there. We can go with rendering them as plain texts but then we will need another view to show the HTML-rich content.

**Comment by shawnborton** [comment] 2023-10-06 12:16
Hmm got it. Okay, maybe it's fine that we keep the markdown in the push-to-page preview but I still think we should only change the border to use the lighter color on row hover.

**Comment by shawnborton** [comment] 2023-10-16 13:23
Curious for @Expensify/design 's thoughts on [this question here](https://github.com/Expensify/App/issues/28858#issuecomment-1762747198).

I think you make a good point in that we should align on the default hover BG we use vs the BG we use when something is selected. So that being said, I do think it makes sense to use the same hover color we use in the updated LHN for all of our hoverable rows when we can. 

cc @grgia in case this might be a lil PR you want to take on as I know you've expressed interest in harmonizing this kind of design stuff.

**Comment by peterdbarkerUK** [comment] 2023-10-16 20:25
not overdue

**Comment by dubielzyk-expensify** [comment] 2023-10-16 22:17
> Curious for https://github.com/orgs/Expensify/teams/design 's thoughts on https://github.com/Expensify/App/issues/28858#issuecomment-1762747198.

I agree that I think we should update the fab menu to use the same hover color. The more subtle one is nicer imo

**Comment by shawnborton** [comment] 2023-10-17 13:22
Okay cool, let's plan for that. 

- :hover uses `highlightBG` color 
- selected or active uses `border`

**Comment by dannymcclain** [comment] 2023-10-17 13:29
That sounds good to me (even though I honestly do prefer the more in-your-face hover). Mega down for alignment though!

**Comment by grgia** [comment] 2023-10-17 14:52
> So that being said, I do think it makes sense to use the same hover color we use in the updated LHN for all of our hoverable rows when we can.
@shawnborton do you mean update all rows to use this? Could you give me an example of what you mean by this. I could definitely help with this after the 22nd if not a priority this week

**Comment by shawnborton** [comment] 2023-10-17 15:12
Probably not a priority for this week.

**Comment by shawnborton** [comment] 2023-10-18 11:37
That also would work for me. This would be a bigger global change applied everywhere, though it shouldn't be too hard to implement.

**Comment by shawnborton** [comment] 2023-10-24 13:20
Ah, I mean like if you are looking at the chats list, when I say selected or :active I am referring to the the item that is selected as the current chat. I also mean that in the sense of a row that is actively being pressed down. This shouldn't change our button states btw - I think those are all covered. This is just for the rows we have in things like the chats list, option menus, etc.

**Comment by shawnborton** [comment] 2023-10-24 17:14
Yup, that makes sense to me. I agree that on press down the border color will blend in so maybe we need to flip the border color to something else on press?

**Comment by shawnborton** [comment] 2023-10-24 17:23
Yup - hence why I am suggesting we consider switching the border color on press in that example you just shared.

**Comment by shawnborton** [comment] 2023-10-26 18:23
I think I would still update the active/pressed color but just live with the fact that the border might slightly disappear during that event.

**Comment by dubielzyk-expensify** [comment] 2023-10-31 00:53
Covering while Shawn is away. Let's use `highlightBG` for that scenario so that it differenciates the hover from the keyboard navigation 👍

**Comment by dubielzyk-expensify** [comment] 2023-10-31 09:01
Looks good to me!

**Comment by sakluger** [comment] 2024-02-05 23:15
@grgia do we still need this issue? Based on the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1701183709503619?thread_ts=1700213083.108879&cid=C01GTK53T8Q), you created a separate GH issue which I think will fix this bug.

If we close this issue, do we owe payments to anyone for work done up until now?

**Comment by sakluger** [comment] 2024-02-05 23:21
According to @grgia we can close out this issue. There was a PR merged in Oct but then reverted, so no payment is due.

**Closed by sakluger** 2024-02-05 23:21 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
