### ISSUE TITLE
[HOLD for payment 2024-12-17] [$250] No popup to open desktop app for 'Try New Expensify' link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52450] opened 2024-11-13 09:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.60-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52255
**Email or phone of affected tester (no customers):** applausetester+bp2410d@app;ause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user is logged in OD.

1. OD: Go to Settings > Account
2. Click on Credit Card Import > Import Card/Bank
3. Click on Privacy at the bottom
4. Go back to OD
5. Click on 'Try New Expensify'

## Expected Result:
User is redirected to NewDot application. Popup with suggestion to open desktop app appears.

## Actual Result:
User is redirected to NewDot application. No popup with suggestion to open desktop app.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7735fcf3-75af-4a95-92de-2760f1dfa248

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859311638145427434</li>
        <li>Upwork Job ID: 1859311638145427434</li>
        <li>Last Price Increase: 2024-11-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by bernhardoj** [comment] 2024-11-13 13:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no prompt to open in desktop app.

### What is the root cause of that problem?
When we open ND from OD, the link will have a transition path. If it's a transition URL, the prompt will be pending by `App.beginDeepLinkRedirectAfterTransition()`.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/components/DeeplinkWrapper/index.website.tsx#L19-L31

`beginDeepLinkRedirectAfterTransition` will only resolved after `signOnTransitionToFinishPromise` promise is resolved.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L501-L503

It will be resolved in `setUpPoliciesAndNavigate`.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L441-L447

`setUpPoliciesAndNavigate` is called when the AuthScreen is mounted.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L303

But as seen from the code above, the promise is only resolved if `exitTo` param is not empty. Currently, the `exitTo` param from OD is empty. `exitTo=`. So, the promise is never resolved.

### What changes do you think we should make in order to solve the problem?

Fix the OD to provide the `exitTo`

OR

I think we should set a fallback to the `exitTo` when calling `navigate`. If it's empty, we use HOME. 

https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L425

Then remove the check for `exitTo`.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L441
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L419-L421

Also, when the `exitTo` is empty, it will show infinite loading

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/27c84dfd-fa8c-4f71-a2ad-bbe05ffbf12e">

It's because when we navigate to HOME, it won't go anywhere because we are already at HOME, but the transition page is still at the nav stack.
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L441-L446

So, we need to call `Navigation.goBack` too, but only if `exitTo` is empty because when `exitTo` is available, we already popped it out from LogOutPreviousUserPage. (basically we have 2 places of handling transition)

https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/pages/LogOutPreviousUserPage.tsx#L77-L87

```
if (!isLoggingInAsNewUser) {
    Navigation.waitForProtectedRoutes()
        .then(() => {
            if (isTransitioning && !exitTo) {
                Navigation.goBack();
            }
            Navigation.navigate(exitTo);
        })
        .then(endSignOnTransition);
}
```

OR

We can immediately call `endSignOnTransition` when `exitTo` isn't available.

https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L419-L421
https://github.com/Expensify/App/blob/67d7299079a14ee9dc22c17a5174209b70e9e61c/src/libs/actions/App.ts#L441-L447

```
if (!session || !currentUrl?.includes('exitTo')) {
    endSignOnTransition();
    return;
}
```

```
if (!isLoggingInAsNewUser && exitTo) {
    Navigation.waitForProtectedRoutes()
        .then(() => {
            Navigation.navigate(exitTo);
        })
        .then(endSignOnTransition);
} else {
    endSignOnTransition();
}
```

**Comment by JmillsExpensify** [comment] 2024-11-20 19:03
Opened up to the community since we have a proposal

**Comment by JmillsExpensify** [comment] 2024-11-26 21:16
@Pujan92 proposal above when you have a moment.

**Comment by lakchote** [comment] 2024-11-28 16:22
Let's go with @bernhardoj's proposal, by calling `endSignOnTransition` when `exitTo` isn't available.

**Comment by bernhardoj** [comment] 2024-11-30 08:26
PR is ready

cc: @Pujan92

**Comment by Pujan92** [comment] 2024-12-18 10:03
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [X] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/17452/files#r1889958483

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

1. In OD, press on 'Try New Expensify'
2. Verify when the NewDot opens, there is no infinite loading and there is a popup to open on a desktop

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-12-20 20:13
Payment summary:

 - Contributor: $250 @bernhardoj via New Expensify
 - Reviewer: @Pujan92 $250 via New Expensify

**Comment by JmillsExpensify** [comment] 2024-12-20 20:13
All contributors paid via New Expensify and the payment summary is above, so I'm closing this one.

**Closed by JmillsExpensify** 2024-12-20 20:13 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-12-21 02:52
Requested in ND.

**Comment by garrettmknight** [comment] 2024-12-23 15:50
**Payment summary:**

- Contributor: $250 @bernhardoj via New Expensify
- Reviewer: @Pujan92 $250 via New Expensify

**Comment by garrettmknight** [comment] 2024-12-30 16:22
$250 approved for @Pujan92

**Comment by JmillsExpensify** [comment] 2025-01-08 17:22
$250 approved for @bernhardoj
