### ISSUE TITLE
[HOLD for payment 2022-09-15] [$500] Feature Request - Attachment- Unable to cancel the requested password for PDF file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8595] opened 2022-04-11 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Log in with any account and select any chat
3. Click on plus button
4. Select add attachment > select Document.
5. Choose any password protected PDF.
6. Put password and select Send
7. Open again the PDF attachment and click Cancel

You can use this protected PDF file to test: [password-protected.pdf](https://github.com/Expensify/App/files/8465125/password-protected.pdf)

The password is `1234`

## Expected Result:
Able to cancel the requested password for PDF file

## Actual Result:
Unable to cancel the requested password for PDF file

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.54.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/162761826-efae7e79-ef24-43e3-8600-46be6e6734f5.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause @parasharrajat 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-04-11 14:52
Added password-protected pdf file to the issue description. Note that his problem also is there as soon as you are uploading the file because we have a preview at that stage too.

**Comment by aldo-expensify** [comment] 2022-04-11 15:12
I noticed that the preview for password-protected pdf files doesn't work the same in the desktop, it just shows "Failed to load PDF file". We should have consistent behaviour.

![image](https://user-images.githubusercontent.com/87341702/162770601-6dddca16-4a6f-4420-aad5-c69ffa4bf5b1.png)

**Comment by kbecciv** [comment] 2022-04-11 15:17
@aldo-expensify We logged a separate issue for this https://github.com/Expensify/App/issues/8593

**Comment by parasharrajat** [comment] 2022-04-12 05:14
I think I reported this issue two weeks back https://expensify.slack.com/archives/C01GTK53T8Q/p1649156147168719. Are we ignoring the Slack reports?

**Comment by phivh** [comment] 2022-04-12 17:52
### Proposal

1. Due to limitations from react-pdf we need to add a custom handler for the password that suggested by the 3rd author (https://github.com/wojtekmaj/react-pdf/issues/581#issuecomment-654741296)
2. In src/components/PDFView/index.js, add a custom `onPassword` function:
```
onHandleCallback(callback, password) {
    // Cancel button handler
    if (password === null) {
        return this.props.onCancel();
    }

    callback(password);
}

onPassword(callback, reason) {
    const { PasswordResponses } = pdfjs;
    switch (reason) {
        case PasswordResponses.NEED_PASSWORD: {
            const password = prompt('Enter the password to open this PDF file.');
            this.onHandleCallback(callback, password);
            break;
        }
        case PasswordResponses.INCORRECT_PASSWORD: {
            const password = prompt('Invalid password. Please try again.');
            this.onHandleCallback(callback, password);
            break;
        }
        default:
            break;
    }
}
```

Apply to

```
<Document
   ....
    onPassword={this.onPassword}
>
   ...
</Document>
```

By applying this solution we are able to resolve issue #8593 as well.

### Demo
#### mWeb

https://user-images.githubusercontent.com/5449119/163023668-cdca5acb-299f-4661-8c5d-92c1abd62be0.mp4


#### Web

https://user-images.githubusercontent.com/5449119/163023682-110f0f48-70c5-401e-8028-69064eef03c3.mp4

**Comment by tgolen** [comment] 2022-04-12 18:01
@phivh thank you for the proposal! I am mostly on board with that, but I have a few requests:

- Can you please rename `this.onPassword` -> `this.promptForPassword`?
- Where does `pdfjs` come from in `const { PasswordResponses } = pdfjs;`?
- Where does `prompt()` come from?
- I kind of think that `onHandleCallback` feels unnecessary. Can that code be moved into `promptForPassword()` at all? I'm not quite following how it all goes

**Comment by Santhosh-Sellavel** [comment] 2022-04-12 18:06
@tgolen  🚀  fast here.

**Comment by phivh** [comment] 2022-04-13 17:21
@tgolen 

- Can you please rename this.onPassword -> this.promptForPassword?
=> it can be, will change the name when create PR
- Where does pdfjs come from in const { PasswordResponses } = pdfjs;?
=> It's from `react-pdf` module, it should call right above the class component, I just want to put it inside the function more clearly.
- Where does prompt() come from?
=> prompt() is another way to call the confirm dialog just like window.promt(). FYI https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt#example
- I kind of think that onHandleCallback feels unnecessary. Can that code be moved into promptForPassword() at all? I'm not quite following how it all goes
=> No, it is necessary to handle action `cancel` or `ok` then check the password Null or not then execute the default callback()

**Comment by Santhosh-Sellavel** [comment] 2022-04-13 19:50
@phivh 
> I kind of think that onHandleCallback feels unnecessary. Can that code be moved into promptForPassword() at all? I'm not quite following how it all goes
> => No, it is necessary to handle action cancel or ok then check the password Null or not then execute the default callback()

 I too feel `onHandleCallback` is unnecessary, we could refactor like below.

```js
promptForPassword(callback, reason) {
    const {PasswordResponses} = pdfjs;
    let password;

    if (reason == PasswordResponses.NEED_PASSWORD) {
        password = prompt('Enter the password to open this PDF file.');
    } else if (reason == PasswordResponses.INCORRECT_PASSWORD) {
        password = prompt('Invalid password. Please try again.');
    }

    if (!password) {
        return this.props.onCancel();
    }

    callback(password);
}
```

cc: @tgolen

**Comment by tgolen** [comment] 2022-04-13 21:04
OK, thanks! I agree with @Santhosh-Sellavel that it looks much better like that. 

>  It's from react-pdf module, it should call right above the class component, I just want to put it inside the function more clearly.

I'm not sure I'm following this. Is it imported from react-pdf like this?
```
import {Document, Page, pdfjs} from 'react-pdf/dist/esm/entry.webpack';
```

I think anything being imported from a module should always be at the top of the file and never inline.

> prompt() is another way to call the confirm dialog just like window.promt()

Hm, I guess that works since this is desktop/web, but are there any alternatives to using it? It's just such an ugly UX.

**Comment by phivh** [comment] 2022-04-14 17:28
Thanks @Santhosh-Sellavel , Its totally able to refactor as your suggestion.

@tgolen 
> I'm not sure I'm following this. Is it imported from react-pdf like this?
import {Document, Page, pdfjs} from 'react-pdf/dist/esm/entry.webpack';

=> Correct, we will import like this
> I think anything being imported from a module should always be at the top of the file and never inline.

=> Yea, that is a proposal, I will move on top when creating PR. Just want to put it there to show where is the `PasswordResponses` came from

> prompt() is another way to call the confirm dialog just like window.promt()
> Hm, I guess that works since this is desktop/web, but are there any alternatives to using it? It's just such an ugly UX.

=> Technically, we could create a custom popup to make the UX better but for now, to apply a bug fix we are able to use `prompt()` because this only apply desktop/web/mWeb and it also used by `react-pdf` library by default.
https://github.com/wojtekmaj/react-pdf/blob/356de607adc2af8cb284d6adbf7434e31d85f76b/src/Document.jsx#L348-L369

**Comment by tgolen** [comment] 2022-04-15 14:46
I checked with a few people on the team and we don't want to use `prompt()` for this. The UX of it is sub-par to the experience of the app and we would like to use our own form for this. Could the password form be embedded in the attachment modal?

**Comment by phivh** [comment] 2022-04-18 03:58
> I checked with a few people on the team and we don't want to use `prompt()` for this. The UX of it is sub-par to the experience of the app and we would like to use our own form for this. Could the password form be embedded in the attachment modal? 

@tgolen should we consider to change the type of this bug to feature request? If we use the password form it could affect to the UI.

**Comment by tgolen** [comment] 2022-04-19 20:22
Yeah, I think that's fine to move it to a feature request.

**Comment by kadiealexander** [comment] 2022-04-21 05:15
Placed a hold on this while we work out the UI details. @Expensify/design @tgolen any thoughts on the design elements of creating our own password form for password-protected documents?

**Comment by Santhosh-Sellavel** [comment] 2022-04-22 19:19
@tgolen from slack thread [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1650647881244619?thread_ts=1649968961.380469&cid=C02NK2DQWUX)

Can we close this one or #8593?

**Comment by tgolen** [comment] 2022-04-29 15:23
Sorry, I know this is crude, but I think this is what we want to do:

![image](https://user-images.githubusercontent.com/1228807/165974966-4cf581f3-fdd0-4004-be69-5badb6687e04.png)

**Comment by shawnborton** [comment] 2022-04-29 15:25
Okay, I can grab this one and cook something up

**Comment by parasharrajat** [comment] 2022-04-29 15:26
Note: We also need this password prompt on Android and iOS.

**Comment by shawnborton** [comment] 2022-04-29 15:59
Cool, looks like we have consensus on this approach:
![image](https://user-images.githubusercontent.com/2319350/165981110-fb21f475-4a31-4fff-a37b-e0befcc56988.png)

**Comment by kadiealexander** [comment] 2022-05-02 06:41
Yay, thanks Shawn! Taking this off hold, please get those proposals in!

**Comment by kadiealexander** [comment] 2022-05-09 05:49
Doubled the price, please get those proposals in!

**Comment by frenkield** [comment] 2022-05-10 04:21
## **Proposal**

Add a password entry form for password-protected PDF attachments. The password form is effectively part of `PDFView`. This is overall a simple solution, but requires additional plumbing to properly hide or disable the `send` button in the `AttachmentModal` component.

### Task 1 - Create PDF Password Form Component

1. Create a React component called `PDFPasswordForm` as part of the PDFView component. So `PDFPasswordForm.js` will live inside the `src/components/PDFView` folder. It could also just go in `src/components` but it's only purpose is to request a password for protected PDFs and it doesn't provide any general facilities - like password validation, for example.

2. The design of the form follows the mockups provided in this GitHub issue. This component contains a text field and a confirm button. The confirm button is disabled by default and becomes enabled if the text field contains any characters. Pressing the enter key also submits the form.

3. On the web the `PDFView` component selectively renders the `PDFPasswordForm` when `Document.onPassword()` (from 'react-pdf`) is called. See https://github.com/wojtekmaj/react-pdf for details.

4. On iOS and Android the `PDFView` component selectively renders the `PDFPasswordForm` when `PDF.onError()` (from 'react-native-pdf`) is called with the message, `Password required or incorrect password`. See https://www.npmjs.com/package/react-native-pdf for details.

5. Upon successfully loading a PDF `PDFView` calls a function from properties called `onLoad()` - or `onPDFLoaded()` - or something else if preferred.

### Task 2 - Add callback for successful PDF load

1. Change `AttachmentModal` so that the `send` button is disabled or hidden when the target file is a PDF. The filename is available in the variable `sourceURL`. This isn't the most elegant way to do this but a more elegant solution for managing the `send` button would probably require touching more components (like `ImageView`, for example.)

2. In `AttachmentModal` add an `onAttachmentLoaded()` handler that enables or displays the `send` button when it is called. For other file types this basically does nothing since the `send` button is already enabled/displayed.

3. In `AttachmentModal` add `onAttachmentLoaded` as a property on the `<AttachmentView>` markup. 

4. In `AttachmentView` pass/forward the `onAttachmentLoaded` as a property in the `<PDFView>` markup  - as `onLoad`. 

### Task 3 - Internationalization and styles

1. Add internationalization string for "this PDF is password protected..." text.

2. Add web, mobile web and native styles for `PDFPasswordForm`.

**Comment by frenkield** [comment] 2022-05-10 19:10
Thanks, @Santhosh-Sellavel. Here's a few more details.

### For Web (`PDFView/index.js`):

1. Add state to indicate that a password is required. Here I store the `react-pdf` callback function and use that as a flag to determine whether or not to render `<PDFPasswordForm>`.

2. In this example I'm not hiding the `react-pdf` `<Document>` component when the password form is displayed. I can do this by saving the submitted password and then not render `<Document>` at all. Or maybe this can just be done more simply with styles so that it's not necessary to store the submitted password. For mobile (below) it's necessary to store the password.

3. There's no invalid password handling here. I'll add that to the proposal.

```
onPassword(callback, reason) {
    this.setState({onPasswordCallback: callback});
}

onPasswordFormSubmit(password) {
    // send password to react-pdf Document component
    this.state.onPasswordCallback(password);
}

render() {

    ...

    {this.state.onPasswordCallback &&
        <PDFPasswordForm onSubmit={this.onPasswordFormSubmit}/>
    }

    <Document
        ...
        onPassword={this.onPassword}                    
        ...
    >
    ...
}
```

### For iOS and Android (`PDFView/index.native.js`):

1. Convert to React `PureComponent` so we can store some state.

2. Add state to indicate that a password is required, and for passing the password to the `react-native-pdf` PDF component.

3. There's no invalid password handling here. I'll add that to the proposal.


```
onError(error) {
    if (error.message.match(/password/i)) {
        this.setState({passwordRequired: true});
    }
}

onPasswordFormSubmit(password) {
    this.setState({password: password});
    this.setState({passwordRequired: false});
}

render() {
    ...
    <TouchableWithoutFeedback style={[styles.flex1, props.style]}>

        {passwordRequired ? (
            <PDFPasswordForm onSubmit={this.onPasswordFormSubmit} />
        ) : (

            <PDF
                ...
                onError={(error) => this.onError(error)}
                password={this.state.password}
            />)
        }

    </TouchableWithoutFeedback>
    ...
}
```

**Comment by Santhosh-Sellavel** [comment] 2022-05-15 18:16
@tgolen 
@frenkield Proposal LGTM!
🎀👀🎀 C+ reviewed

> Change AttachmentModal so that the send button is disabled or hidden when the target file is a PDF. The filename is available in the variable sourceURL. This isn't the most elegant way to do this but a nicer solution for managing the state of the send button would probably require touching more components (like ImageView, for example.)

I believe we should have option where user can enter password and view pdf while sending a password-protected pdf, also skip and just send it anyway! So no need to disable send button.

**Comment by frenkield** [comment] 2022-05-15 22:56
Thanks, @Santhosh-Sellavel.

**Comment by tgolen** [comment] 2022-05-16 15:36
Yep, I'm all fine with giving the 🟢  to move forward with the PR and the rest of the review can happen there.

**Comment by frenkield** [comment] 2022-05-17 16:02
I applied on Upwork. I'll submit the PR by Monday, May 23rd (05/23/2022) at the latest.

Thanks, Everyone!

**Comment by frenkield** [comment] 2022-05-23 03:41
Hi All. In the case where we're sending a PDF, should I add some language indicating that one can skip the password entry and just click the Send button? For example,

<img width="950" alt="pdf_password_form" src="https://user-images.githubusercontent.com/11221215/169738808-16ef1eca-85e2-4ac0-b0bd-cc0fa9f11337.png">

**Comment by kadiealexander** [comment] 2022-05-23 03:41
@Expensify/design any thoughts on the above?

**Comment by shawnborton** [comment] 2022-05-23 06:46
I think we could omit the message below, and just change the top message to say something like "This PDF is password protected. Please enter the password to view it."

**Comment by frenkield** [comment] 2022-05-23 16:25
Thanks, everyone. I'll make the changes.

**Comment by Santhosh-Sellavel** [comment] 2022-05-23 20:17
@frenkield Let us know when PR is ready!

**Comment by frenkield** [comment] 2022-05-23 20:22
I'll submit it in a few hours, @Santhosh-Sellavel.

**Comment by frenkield** [comment] 2022-05-24 00:37
@Santhosh-Sellavel, I submitted the pull request: https://github.com/Expensify/App/pull/9141

Thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 18:20
Not overdue, PR review in progress almost complete.

**Comment by Santhosh-Sellavel** [comment] 2022-06-01 19:42
Status: 
PR is almost 70-80 % complete. https://github.com/Expensify/App/pull/9141
We have one question from @shawnborton  
> Also I wanted to follow up on my previous question - where does this preview image come from exactly? <img alt="image" width="303" src="https://user-images.githubusercontent.com/2319350/171477800-31710da0-4ad5-464d-824e-4cfc78e3c3a6.png">

@kadiealexander 
@tgolen is already OOO and will be back on June 6.

I am going OOO, so I request a new C+ assignment for this one. If @parasharrajat is available let's assign them as C+ , because he has more context to this. If not then just re-apply `Exported` label here. 

I believe C+ alone can handle things until @tgolen is back, so let's keep @tgolen assigned to this one.

**Comment by parasharrajat** [comment] 2022-06-02 06:20
Sure, happy to help.

**Comment by parasharrajat** [comment] 2022-06-05 10:50
Can anyone please update the OP with the correct(final) mockups?

**Comment by parasharrajat** [comment] 2022-06-05 11:25
Started reviewing the PR. 

> ~PR is almost 70-80 % complete.~ I would say 50-60%.

**Comment by frenkield** [comment] 2022-06-05 16:04
> > ~PR is almost 70-80 % complete.~ I would say 50-60%.

My net hourly rate here is already comically low. And it appears that there are still many, many hours of work to do.

Whom do I contact in order to request more money for this project?

**Comment by kadiealexander** [comment] 2022-06-06 22:38
You can ask here! Please let me know what you feel is fair for this job and we'll discuss this internally.

**Comment by frenkield** [comment] 2022-06-07 01:20
Thanks, @kadiealexander.

This project is taking significantly longer than anticipated. I've already spent 50 hours on it and we're still only 50%-60% complete. I'd like to modify the terms of the contract as follows:

1. The total price is upped to $2000
2. There are 2 milestones: one for $500 and the second for $1500
3. The first milestone (for $500) is marked completed - and thus the $500 are released to me

If this isn't amenable to you I totally understand. In that case I'll cancel the contract and Upwork will release all escrow funds back to Expensify. I'll also close the pull request.

I apologize for the inconvenience.

**Comment by kadiealexander** [comment] 2022-06-07 02:14
Thanks @frenkield, I have taken this to the team to discuss internally and will be in touch.

**Comment by frenkield** [comment] 2022-06-07 02:16
Ok great. Thanks, @kadiealexander.

**Comment by kadiealexander** [comment] 2022-06-07 22:00
Hey @frenkield! Our team agrees with your request. I've paid the $500 milestone in Upwork and I've added a $1500 milestone to be paid after the 7 day regression period once the PR is deployed. 

Thanks for your work so far, and for communicating with us about what you feel is fair.

**Comment by frenkield** [comment] 2022-06-07 22:40
That's great news! Thanks so much, @kadiealexander. And thanks to the rest of the team as well.

**Comment by kadiealexander** [comment] 2022-06-14 02:14
@frenkield could you please share an update here for the team?

**Comment by frenkield** [comment] 2022-06-14 03:03
Hi @kadiealexander. Most everything is working. I'll add some comments/questions to the pull request tomorrow. I believe these are the only outstanding technical issues:

1. The confirm button is correctly positioned on native and android-chrome. However, the solution doesn't work adequately on ios-safari.
2. The enter key doesn't behave as desired in certain situations. I think I may need to explicitly transfer focus back to the AttachmentModel submit/close buttons after a password-protected PDF is opened.

**Comment by kadiealexander** [comment] 2022-06-14 03:15
Thanks so much @frenkield!

**Comment by parasharrajat** [comment] 2022-06-14 11:59
> However, the solution doesn't work adequately on ios-safari.

We can leave this one optionally.

**Comment by frenkield** [comment] 2022-06-14 16:03
> We can leave this one optionally.

Ok thanks, @parasharrajat. So on ios-safari the confirm button will be positioned just below the password field - the same as on web.

**Comment by parasharrajat** [comment] 2022-06-14 16:11
No, I meant say that it is fine if button is not fixed at the bottom of the screen on MWeb safari when keyboard is open. On all other devices Button will be fixed bottom and float over keyboard. But button will always be at the bottom of the screen on all platforms.

**Comment by frenkield** [comment] 2022-06-14 16:20
Ah sorry. So...
1. On ios-safari the confirm button will always be at the bottom of the screen.
2. And when the keyboard is open, the confirm button will be covered by the keyboard. So **the confirm button will not be visible when the keyboard is open on ios-safari**.

Is the the correct behavior, @parasharrajat?

**Comment by parasharrajat** [comment] 2022-06-14 16:31
Yeah.

> And when the keyboard is open, the confirm button is covered by the keyboard. So the confirm button is not visible when the keyboard is open on ios-safari.

Actually this is a challenge we are trying to solve. So it is fine you are not able to find a solution to it.

**Comment by frenkield** [comment] 2022-06-14 16:32
Ok thanks, @parasharrajat.

**Comment by frenkield** [comment] 2022-06-17 17:45
Hi All. Everything is done but there are a couple small rendering issues on Android. Hopefully I'll have these resolved by Monday.

**Comment by parasharrajat** [comment] 2022-06-20 18:54
@shawnborton It seems we discussed the design for the main scenario https://github.com/Expensify/App/issues/8595#issuecomment-1113477651 but missed the one where we are sending the attachment. On Send Attachment modal, there is another button Send. On the web, it looks fine as Confirm button is not sticky to the bottom. It stays next to the password input. But on mobileWeb and Android, what should we place the confirm button. 

Currently, PR does this :arrow_down: . When previewing the old sent PDFs, confirm button is the green and sticky bottom which looks fine. But as per the video, it does not look good while sending the PDF.

https://user-images.githubusercontent.com/11221215/174502915-dce69d5f-d532-4804-8e87-a91fd28b8b1a.mp4

**Comment by shawnborton** [comment] 2022-06-20 21:22
Hmm honestly I'm not too sure - it feels strange to have the send button docked to the bottom when the password input and confirm button are shown. Do you mind bringing this one to #expensify-open-source for more eyes and discussion?

**Comment by parasharrajat** [comment] 2022-06-21 20:39
Asked here https://expensify.slack.com/archives/C01GTK53T8Q/p1655843898715879

**Comment by parasharrajat** [comment] 2022-06-27 17:10
@frenkield You can proceed as decided on the slack thread. Let me know if you have any other questions. Thanks.

**Comment by frenkield** [comment] 2022-06-27 17:16
Ok sounds good. Thanks, @parasharrajat.

**Comment by kadiealexander** [comment] 2022-07-06 05:47
Not overdue, updates are in the PR.

**Comment by frenkield** [comment] 2022-07-12 03:33
Thanks for the information regarding the styles and translations, @parasharrajat.

I committed the requested updates related to styles and translations (as described in my previous comment). I also merged main from github.com/Expensify/App. So the code in the pull request is completely up to date.

All tasks are now complete.

**Comment by shawnborton** [comment] 2022-07-20 22:37
Apologies, I totally missed that. I just left my review!

**Comment by kadiealexander** [comment] 2022-08-01 00:27
@parasharrajat @frenkield how are we tracking with this?

**Comment by parasharrajat** [comment] 2022-08-01 02:40
PR is in review.

**Comment by shawnborton** [comment] 2022-08-09 15:27
Not overdue

**Comment by frenkield** [comment] 2022-08-09 17:12
The fade out solution looks good to me. Why is that not acceptable?

What do you want me to continue on the PR, @parasharrajat? As far as I know everything is 100% done.

**Comment by frenkield** [comment] 2022-08-09 17:21
Ah sorry! I see.

**Comment by frenkield** [comment] 2022-08-09 17:32
@parasharrajat, the fade out solution looks good to me. Why is that not acceptable?

Are there other people that don't approve of this solution? Or is it your decision?

**Comment by frenkield** [comment] 2022-08-13 21:49
Hi @kadiealexander, @parasharrajat and @shawnborton.

I need to take some time off. I'll resume working on the PR on Monday, August 22nd.

**Comment by tgolen** [comment] 2022-09-05 13:37
This was just merged today!

**Comment by kadiealexander** [comment] 2022-09-12 06:58
Just adding a note that I'm OOO until September 21st. As this is on hold I won't reassign it, but if you need a contributor manager to do anything before that point please reapply the `external` label.

**Comment by kadiealexander** [comment] 2022-09-12 06:59
Reassigning as I'm ooo for the next 9 days.

**Comment by mvtglobally** [comment] 2022-09-13 04:24
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2022-09-16 02:15
PR in product with no regressions for 7 days - paying @frenkield $1500 based on the convo [here](https://github.com/Expensify/App/issues/8595#issuecomment-1149214713). 

Since this original [Upwork job](https://www.upwork.com/ab/applicants/1513700366393270272/job-details) automatically closed. 

I made a new job posting and hired @parasharrajat for payment. 

Internal posting - https://www.upwork.com/ab/applicants/1570596159667929088/job-details
External posting- https://www.upwork.com/jobs/~010327ce806aef815b

**Comment by super-soft-dev** [comment] 2022-09-16 06:46
HI @Christinadobrzyn

I've checked this job from upwork.

As a senior React-Native developer, I'd like to work on your project.

I've checked the issue carefully, I can fix it.

Could you please allow me to join the slack?

Looking forward to hearing from you.

Best regards

**Comment by Christinadobrzyn** [comment] 2022-09-16 07:02
Hey @super-soft-dev - thanks for reaching out! This project is complete but feel free to reach out to us at contributors@expensify.com with a link to your Upwork profile and our team can add you to Slack to help with open jobs.

**Comment by super-soft-dev** [comment] 2022-09-16 07:52
ok Thanks

**Comment by Christinadobrzyn** [comment] 2022-09-19 00:26
@parasharrajat I just paid out this job $500 for the original amount and $1500 as the bonus. Please feel free to reach out with any questions! Thank you!

**Closed by Christinadobrzyn** 2022-09-19 00:26 UTC
Labels: Exported, External, Engineering, Daily, Design, Awaiting Payment
