### ISSUE TITLE
[PAYMENT 3/4][$500] iOS - IOU - The cursor appears at random locations after pasting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35420] opened 2024-01-30 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause- Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35119

## Action Performed:
1. Tap FAB - Request money
2. Type "22222"
3. Copy any single digit number "7"
4. Drag, select & try to replace last number in step 3 by pasting "7"
5. Drag, select & try to replace first number in step 3 by pasting "7"
6. Drag, select & try to replace middle number in step 3 by pasting "7"
7. Now drag, select & try to replace remaining digit by pasting "7"

## Expected Result:
It should be appearing right after the paster number.

## Actual Result:
The cursor appears at random locations after pasting.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/74b73eb6-88a4-49d5-88d0-b903b96bb502

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180563495c94b9556</li>
        <li>Upwork Job ID: 1752383457329037312</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 17:29
We think that this bug might be related to  #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-01-31 07:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pasting a number on the money request input moves the selection to the left.

### What is the root cause of that problem?
When we set a selection that is larger than the input value length, the selection will be put on the left. You can test this by having a button that will set the selection to a number that is larger than the current input value length.

In our case, when we paste something to the amount input that has a value, a whitespace is also added. This behavior is also found on this [old issue](https://github.com/Expensify/App/issues/16974#issuecomment-1509030863). So, the total length of the input is added by 1 because of the whitespace, but we strip the space from the input.
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/pages/iou/steps/MoneyRequestAmountForm.js#L143-L147

So, if the input is "2(whitespace)5", the new input state will be "25" and the value is updated before `onSelectionChange` is called, so when the selection change is called, it will try to update the selection to be 3, but the length is only 2.

Btw, to reproduce it easier, you can just type a number to the input then paste anything afterwards.
### What changes do you think we should make in order to solve the problem?

We can clamp the selection value so it doesn't set a value larger than the current input length.
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/pages/iou/steps/MoneyRequestAmountForm.js#L295-L300
```
const maxSelection = formattedAmount.length;
const start = Math.min(e.nativeEvent.selection.start, maxSelection);
const end = Math.min(e.nativeEvent.selection.end, maxSelection);
setSelection({start, end});
```

### What alternative solutions did you explore? (Optional)
We can ignore the selection change if there is any update with the amount. There is a `shouldUpdateSelection` but it's also being used for long press, so I think it's better to create a new state to temporarily ignore the selection change event and re-enable it after we ignore it.
```
const setNewAmount = useCallback(
    (newAmount) => {
        setShouldTemporaryIgnoreSelection(true);
...
onSelectionChange={() => {
    if (shouldTemporaryIgnoreSelection) {
        setShouldTemporaryIgnoreSelection(false);
        return;
    }
```

_I guess ref would be more performant_

**Comment by CortneyOfstad** [comment] 2024-02-02 18:12
@rushatgabhane any thoughts on the proposal above?

**Comment by rushatgabhane** [comment] 2024-02-05 05:56
@bernhardoj's proposal fixes the root cause https://github.com/Expensify/App/issues/35420#issuecomment-1918540352
🎀 👀 🎀

**Comment by CortneyOfstad** [comment] 2024-02-07 16:14
@bernhardoj any update on the PR? Thank you!

**Comment by bernhardoj** [comment] 2024-02-07 16:20
@CortneyOfstad I'm waiting to get assigned first

**Comment by bernhardoj** [comment] 2024-02-12 09:48
PR is ready

cc: @rushatgabhane

**Comment by CortneyOfstad** [comment] 2024-02-14 15:12
@rushatgabhane @bernhardoj any update on the PR/review? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-22 19:11
PR shows it is in staging as of 3 days ago. Will continue to keep an eye on this.

**Comment by CortneyOfstad** [comment] 2024-02-28 15:30
PR in production as of 2 days ago 👍

**Comment by CortneyOfstad** [comment] 2024-02-29 19:55
Hey @trjExpensify! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, the PR [here](https://github.com/Expensify/App/pull/36318) went into production 3 days ago. If there are no regressions, the payment is set for Monday, March 4. Payment breakdown is below:

## Payment Summary

@bernhardoj — $500 to be paid in Upwork
@rushatgabhane — $500 to be paid in NewDot

**Comment by rushatgabhane** [comment] 2024-03-01 19:22
https://staging.new.expensify.com/r/4222149771653350 money request here

**Comment by JmillsExpensify** [comment] 2024-03-01 23:42
$500 approved for @rushatgabhane based on summary above.

**Comment by trjExpensify** [comment] 2024-03-04 10:01
Paid $500 out @bernhardoj based on the payment summary [here](https://github.com/Expensify/App/issues/35420#issuecomment-1971856780). @rushatgabhane confirmed to have requested, closing.

**Closed by trjExpensify** 2024-03-04 10:01 UTC
Labels: External, Weekly, Awaiting Payment, Bug
