### ISSUE TITLE
[HOLD for payment 2024-10-29] Attachment - Extra space between download and close button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50993] opened 2024-10-17 09:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report.
3. Send an image.
4. Click on the image.

## Expected Result:
There will be no extra space between download and close button.

## Actual Result:
There is extra space between download and close button.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c046744c-1d2f-4a1a-9f24-b0511f4a8673

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by mkzie2** [comment] 2024-10-17 09:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is extra space between download and close button.

### What is the root cause of that problem?

We added `gap4` in https://github.com/Expensify/App/pull/49984:

https://github.com/Expensify/App/blob/c4f70882f836269bf2fedb6f448e20e87db1315b/src/components/HeaderWithBackButton/index.tsx#L194

### What changes do you think we should make in order to solve the problem?


Remove the `gap4` style.

**Comment by shawnborton** [comment] 2024-10-17 12:30
Hmm to me, the gap between button and icon on the Search page feels too big. I think we should just standardize on the gap we used to have in the attachment modal between close and download, and try to use that same gap everywhere for this. What was it previously?

**Comment by dannymcclain** [comment] 2024-10-17 13:42
@shawnborton That sounds good to me—I think the examples above (Workspaces & room) look _too_ close. But I agree that the search/Expenses screen could be a little tighter. We've previously decided to use an `8px` gap between horizontal button groups—can we just standardize on that everywhere?

**Comment by shawnborton** [comment] 2024-10-17 13:45
I can definitely get down with that, yup!

**Comment by SzymczakJ** [comment] 2024-10-17 14:25
I'll take care of that since I've also worked on that PR

**Comment by SzymczakJ** [comment] 2024-10-17 15:26
I've removed the change in header of AttachmentModal and all other headers that were affected by this change. Also fixed all other places**(set everything to 8px gap)** that we mentioned and that had <SearchButton /> in them. Please take a look @Expensify/design:
<img width="1328" alt="Screenshot 2024-10-17 at 16 46 48" src="https://github.com/user-attachments/assets/7602ac72-9958-4561-9447-bb25d83a0878">
<img width="1331" alt="Screenshot 2024-10-17 at 16 47 06" src="https://github.com/user-attachments/assets/cfc08753-ad0b-4db1-96e8-bea2a5ede2c7">
<img width="667" alt="Screenshot 2024-10-17 at 16 53 31" src="https://github.com/user-attachments/assets/91bbcc3f-4440-484c-b0cb-bb653fece5c5">
<img width="1331" alt="Screenshot 2024-10-17 at 17 06 59" src="https://github.com/user-attachments/assets/9bdb0604-0e10-4421-8c62-5914017d38d1">
<img width="1332" alt="Screenshot 2024-10-17 at 17 25 53" src="https://github.com/user-attachments/assets/337e5453-b834-46fb-bba1-31f3f4301698">

**Comment by dannymcclain** [comment] 2024-10-17 15:27
Personally I think that is glorious. `:chefkiss:`

**Comment by shawnborton** [comment] 2024-10-17 15:37
Same, this looks great!

**Comment by lschurr** [comment] 2024-10-28 22:38
No payment here since this was a regression from: https://github.com/Expensify/App/pull/49984

Closing.

**Closed by lschurr** 2024-10-28 22:38 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
