### ISSUE TITLE
Workspace - No "Plan type" field for upgrading or downgrading workspace on iOS

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54503] opened 2024-12-24 09:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unable to check
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** applausetester+zm79@applause.expensifail.com
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 15 Pro Max / iOS 18.2
**App Component:** Workspace Settings

## Action Performed:
1. Launch ND or hybrid app.
2. Create a workspace.
3. Go to workspace profile.

## Expected Result:
There should be a "Plan type" field for upgrading or downgrading workspace.

## Actual Result:
There is no "Plan type" field for upgrading or downgrading workspace.

This issue only happens on iOS app.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9eba6dc9-f7c8-4b19-b598-a9816bfc23eb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2024-12-24 21:02
Unable to reproduce, closing

**Closed by jasperhuangg** 2024-12-24 21:02 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
