### ISSUE TITLE
[HOLD] Restricted access - Redirection does not work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12676] opened 2022-11-11 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Navigate to each of the following links
https://staging.new.expensify.com/r/6821704960193694/details
https://staging.new.expensify.com/r/6821704960193694/participants
https://staging.new.expensify.com/r/6821704960193694/settings

## Expected Result:
You should be redirected to the concierge conversation

## Actual Result:
Redirection does not work

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App

**Version Number:** 1.2.27.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201398713-355b7ca6-5cd6-4509-84a7-9e93818b02b4.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-11-11 17:46
QA team is Failing steps in TestRail https://expensify.testrail.io/index.php?/tests/view/2936076

**Comment by mateocole** [comment] 2022-11-15 00:45
Having an engineer confirm this is something I can mark external

**Comment by alex-mechler** [comment] 2022-11-15 18:12
Yup, looks like something broke here. Since this is just routing this can go external

**Comment by peterklamka** [comment] 2022-11-15 19:06
@kbecciv I logged in my account. but I got this screen when I visit https://staging.new.expensify.com/r/6821704960193694.
so I don't think /details, /participants, /settings will work too.

![image](https://user-images.githubusercontent.com/118206313/202004281-be990d0c-1c89-48f4-ac16-8818ee6f5f19.png)

**Comment by mateocole** [comment] 2022-11-15 21:45
Job posted- https://www.upwork.com/ab/applicants/1592623071761788928/job-details

**Comment by marcaaron** [comment] 2022-11-15 23:44
@mateocole were you able to reproduce on `staging`? I tried and just see that the modal closes and I get redirected to a chat. I don't get "redirected to Concierge", but not seeing the weird messed up state that tester is reporting either.

https://user-images.githubusercontent.com/32969087/202048278-2788a81b-f02a-47e3-a33c-0782fc3fc4e7.mp4

Couple thoughts... 

- This could be a browser specific issue.
- Is getting redirected to Concierge actually the correct behavior? Could the TC (test case) be out of date?

**Comment by mollfpr** [comment] 2022-11-17 15:22
Same as @marcaaron I can't reproduce it.

I feel like this is a regression from this [PR](https://github.com/Expensify/App/pull/12089) where it should redirect to the concierge chat. But the issue https://github.com/Expensify/App/issues/11982 is not stated needs to redirect to the concierge chat.

**Comment by marcaaron** [comment] 2022-11-17 18:12
Hmm I am so confused about that PR you linked. If a chat doesn't exist in the history yet we are just redirecting randomly? Why does the report not exist? Do we try to access it from the server? I'm totally lost, but the HOC solution seems very strange to me. @Beamanator please share your thoughts here.

@kbecciv Where does the expectation that we should redirect to the Concierge chat come from? Is it an existing TC? 

@mateocole I think we need to bring this one into #bug-zero to resolve.

**Comment by kbecciv** [comment] 2022-11-18 14:50
@marcaaron Here is the TR link for Restricted access part 

https://expensify.testrail.io/index.php?/runs/view/10698&group_by=cases:section_id&group_order=asc&group_id=229067

![image](https://user-images.githubusercontent.com/93399543/202732367-980f0ca6-c1ee-4df3-82ae-af4f42d9978b.png)

**Comment by mollfpr** [comment] 2022-11-18 17:20
> If a chat doesn't exist in storage yet we are just redirecting randomly?

Yes, currently we do dismiss the modal. The expected result from this https://github.com/Expensify/App/issues/11982 is not stated redirecting to the concierge.

> Why does the report not exist?

When we try to access other account report IDs (where the current account is not part of the group/room/workspace), the report data is not available in the storage.

> Do we try to access it from the server? 

We don't fetch the targeted report ID in the `ReportDetailsPage`, `ReportParticipantsPage `, and `ReportSettingsPage `. I think we should fetch the report data where I proposed in https://github.com/Expensify/App/issues/12428#issuecomment-1310585186

> I'm totally lost, but the HOC solution seems very strange to me.

We handle the same things for the 3 pages, so I think it's okay to create a HOC for that.

cc @marcaaron @Beamanator

**Comment by marcaaron** [comment] 2022-11-18 18:45
>When we try to access other account report IDs (where the current account is not part of the group/room/workspace), the report data is not available in the storage.

This is the part that I don't get. If we don't have the report in storage then how do we know if it has been loaded or not? Maybe we are still waiting for it from the server. I'm missing the thought process around why we should redirect. Will wait for @Beamanator to chime in here with an explanation.

**Comment by mollfpr** [comment] 2022-11-19 02:24
> If we don't have the report in storage then how do we know if it has been loaded or not? Maybe we are still waiting for it from the server.

I guess it's because we not fetching the report data when opening the `ReportDetailsPage`, `ReportParticipantsPage`, and `ReportSettingsPage`.

**Comment by Beamanator** [comment] 2022-11-21 17:40
Interesting, looking back when I created [this issue](https://github.com/Expensify/App/issues/11982) I was thinking it would be best to redirect back to the home page b/c it's possible the user wouldn't have access to the specific report page they were trying to open... Though now that we're riffing I bet we could come up with a solution to figure out if the user has access (once the report data loads), then determine if we show the details on that page or redirect to home.

Either way I don't know where we came up with "redirect to the Concierge page"

And about the HOC idea, my understanding is that we went this route so we didn't have to many similar checks on many related report pages - I believe the checks were around if the report existed in Onyx or not. Maybe we can come up with a better solution to all this, our previous solution seemed good at the time though :D

**Comment by marcaaron** [comment] 2022-11-21 18:25
Gonna tag in @puneetlath on this conversation since he is the assigned BZ on [the issue that is still open](https://github.com/Expensify/App/issues/11982) and this issue is _technically_ a regression.

>I was thinking it would be best to redirect back to the home page b/c it's possible the user wouldn't have access to the specific report page they were trying to open

Is this the standard view we show when a user can't access something? cc @shawnborton to confirm

![2022-11-21_08-11-17](https://user-images.githubusercontent.com/32969087/203129283-575f56b8-f862-4f84-9798-23e5c9cb681c.png)

And when do we show those views? Is it when the user tries to load a chat they do not have stored locally or when they attempt to load a chat and fail to do so? I am not really sure because these scenarios seem possible:

**Scenario 1 - Offline with access to a chat (might have access or not)**

1. User is offline
2. User attempts to visit a chat
3. Chat is not stored locally so there's no content to display
4. What do we show them... ?

**Scenario 2 - Online but request to fetch chat was denied**

1. User is online
2. User attempts to visit a chat
3. Chat is not stored locally so there's no content to display
4. Chat fetch is attempted but user does not have access to the chat
5. What do we show them... ?

>I don't know where we came up with "redirect to the Concierge page"

Cool. Me neither. Is it possible to figure that out to make sure we're not missing context about the intended behavior here? The PR mentioned by @mollfpr caused a regression from the previous behavior - it sounds like we changed that behavior, but didn't update the Test Case (seems like nobody was aware that this was the expected behavior). So it also sounds like there might be some confusion about what the desired behavior should be here.

Ultimately, my thoughts are that whatever we do we should do it consistently and then update the TCs so that QA doesn't report regressions. Does that make sense @Beamanator?

**Comment by puneetlath** [comment] 2022-11-21 18:52
@marcaaron the [issue](https://github.com/Expensify/App/issues/11982) that I'm working on seems to be happening because we are redirecting to their policy expense chat, but they don't have a policy expense chat because they aren't on the beta. Still trying to figure out why we're re-directing to that chat in the first place.

**Comment by shawnborton** [comment] 2022-11-21 23:20
@marcaaron I think that's correct, yeah

**Comment by s77rt** [comment] 2022-11-22 12:05
What is the status on this?
Is the concierge report id supposed to be global? from my end it is 6618435619127286 and the navigation seems to work

**Comment by Beamanator** [comment] 2022-11-22 15:13
@marcaaron I think it's a great idea to figure out if / why we want to redirect users to Concierge in this scenario, OR we just open up a quick generic discussion like:

"If a user tries navigating to a report they don't have access to, what should we do?
1. Navigate them to Concierge
2. Navigate them to "Home" (or their last viewed report)
3. Show them the "Hmm... it's not here" error page"

Then we can ask a similar question for Scenario 1, probably with the same possible solutions. Once we know what we want, we could open an audit issue to make sure that works on all pages of our app, in all platforms, & we update the TC. Thoughts on that plan? I can move it forward if you want 👍

**Comment by Beamanator** [comment] 2022-11-22 15:14
@s77rt Sorry for the confusion here - first, there's no _global_ Concierge report ID. Second, we're actually still figuring out what should be done in this case (as this probably isn't technically a "bug") so I removed `Help Wanted` and put this on hold in the meantime

**Comment by marcaaron** [comment] 2022-11-22 21:01
>Thoughts on that plan? I can move it forward if you want

That sounds great, thanks!

**Comment by Beamanator** [comment] 2022-11-23 09:26
Groovy - in the meantime are we good to move forward with payment for https://github.com/Expensify/App/issues/11982? It was my fault for not updating the TC & for really not bringing the "proper solution" discussion to a wider audience, so we shouldn't delay payment to @mollfpr 
 
cc @puneetlath

**Comment by Beamanator** [comment] 2022-11-23 09:27
Oh looks like we're also discussing that PR and how it relates to [this issue](https://github.com/Expensify/App/issues/12428), but at least we won't hold on resolving this one 😅

**Comment by marcaaron** [comment] 2022-11-23 20:56
Yes to payment, but I think we should revert the PR too. The changes don't seem like something we will want long term and the issue you linked to seems to have an attached proposal that builds onto this solution instead of stepping back and doing a proper holistic solution. So I think we should clean up the mess here before we make things even more confusing.

**Comment by Beamanator** [comment] 2022-11-24 16:48
Got stuck on some other issue today, will jump back into this tomorrow - I like the idea of "not continuing a bad solution" so will look into cleaning messes tomorrow

**Comment by JmillsExpensify** [comment] 2022-12-01 19:00
What's the latest on this one?

**Comment by JmillsExpensify** [comment] 2022-12-23 17:00
Bump on my last comment from a couple of weeks ago.

**Comment by mateocole** [comment] 2023-01-25 00:19
@Beamanator is there anything holding this issue currently?

**Comment by Beamanator** [comment] 2023-01-25 16:38
Oh shoot I totally thought this was one of the ones holding on navigation reboot, sorry - I will jump into a plan for this tomorrow, may see if someone else will take it off my plate too 😅

**Comment by Beamanator** [comment] 2023-03-01 10:32
Still pretty low priority, though some higher priority projects are finishing up soon so will try to get to this one mid march

**Comment by Beamanator** [comment] 2023-05-05 16:43
On hold for some higher priority tasks

**Comment by Beamanator** [comment] 2023-07-10 10:32
Reassigning `Bug` since this "Was" on hold for navigation reboot but that went live!

@joekaufmanexpensify I think we need to reevaluate if this is still a bug / if we need to fix something here please 🙏

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:45
Sounds good, I'll take a look today!

**Comment by joekaufmanexpensify** [comment] 2023-07-10 18:42
@Beamanator I tested this, and when I try and navigate to the links in OP, I get the "Hm, it's not here" error. It seems like this is one of the expected behavior options discussed [here. ](https://github.com/Expensify/App/issues/12676#issuecomment-1323833015) And then the user has the option to redirect to the home page. 

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/54866469/e655d19e-7a36-4eba-abed-974224bed7ea">

**Comment by joekaufmanexpensify** [comment] 2023-07-10 18:45
Personally, I feel like this is fine. I don't think it'll be common that someone will be copying an actual report they don't have access to. What feels much more likely to me is that someone would copy a report they do have access to, but with a typo. 

And the existing error sufficiently communicates that they did something wrong. At which point, they'll likely realize, and correct the typo, or navigate to the home page using the button on the screen. 

If you agree, then I think we're all set to close this one!

**Comment by Beamanator** [comment] 2023-07-11 09:36
@joekaufmanexpensify  That definitely sounds legit to me!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 12:02
Cool cool. Closing as this has been fixed by the navigation reboot!

**Closed by joekaufmanexpensify** 2023-07-11 12:02 UTC
Labels: External, Engineering, Daily, Bug
