### ISSUE TITLE
Web - No Character limit when editing Merchant

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26581] opened 2023-09-02 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the Plus icon > Request money > Enter the amount> Choose a User.
2. On the next page click Show More> Click on the Merchant to edit. Notice you can't enter more than 255 characters.
3. Click on request money
4. Go to the IOU report > Click on the Merchant to edit. Notice you can enter more than 255 characters.

## Expected Result:
There is a character limit when editing the merchant

## Actual Result:
Describe what actually happened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b2e46a1-f0f9-44a4-9855-199614562e8d

https://github.com/Expensify/App/assets/93399543/d8ac28d3-e303-4037-899a-4ed23c5c57e1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693279155513149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-09-02 20:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No Character limit when editing Merchant
### What is the root cause of that problem?
there is no maxLength prop in the TextInput here
https://github.com/Expensify/App/blob/c3ec03b1b6e2a16b0ec07c335b94b2aacabee83e/src/pages/EditRequestMerchantPage.js#L56-L64
### What changes do you think we should make in order to solve the problem?
we need to set maxLength prop
```javascript
  maxLength={CONST.MERCHANT_NAME_MAX_LENGTH}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by flaviadefaria** [comment] 2023-09-04 08:39
Yep definitely a dupe so closing this.

**Closed by flaviadefaria** 2023-09-04 08:39 UTC
Labels: Daily, Bug
