### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Desktop - Unexpected error when try to select the purpose "Chat and split"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51395] opened 2024-10-24 09:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5123689
**Email or phone of affected tester (no customers):** rybkina+102324fi@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch App
2. Create a new user (gmail)
3. Select the purpose "Chat and split expenses with friends"
4. Click on "Continue"
5. Verify that the "What’s your name?" modal appears
6. Enter any names
7. Click on "Continue"

## Expected Result:
User should land to Concierge chat without issues.

## Actual Result:
"What do you want to do today?" modal appeared again and errors appeared in Concierge chat.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/510e8bf2-37a0-476b-b894-b7f0df66128a
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="1061" alt="Bug6643819_1729723484035!Screenshot_2024-10-23_at_18 34 15" src="https://github.com/user-attachments/assets/f913c474-d0bc-4c09-976a-cc804e9a58cd">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850849037204397718</li>
        <li>Upwork Job ID: 1850849037204397718</li>
        <li>Last Price Increase: 2024-10-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by IuliiaHerets** [comment] 2024-10-24 09:45
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-10-28 10:36
I can repro this reliably, and dupe reported it [here](https://expensify.slack.com/archives/C049HHMV9SM/p1729884761990519). Moving it on to get C+ eyes on this.

**Comment by DylanDylann** [comment] 2024-10-30 10:14
@NJ-2020's [proposal](https://github.com/Expensify/App/issues/51395#issuecomment-2434893769) looks good to me. Let's use "-1" value as confirmed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1729592838480029?thread_ts=1729571282.411639&cid=C01GTK53T8Q)

🎀 👀 🎀 C+ reviewed

**Comment by yuwenmemon** [comment] 2024-10-30 18:18
@sonialiap Halp

**Comment by DylanDylann** [comment] 2024-10-31 03:54
@NJ-2020 Please create a PR

**Comment by DylanDylann** [comment] 2024-11-06 03:45
@marcochavezf Already created a [PR](https://github.com/Expensify/Auth/pull/13026) on BE

**Comment by DylanDylann** [comment] 2024-11-13 09:11
@marcochavezf Could you give an update on this [PR](https://github.com/Expensify/Auth/pull/13026)?

**Comment by marcochavezf** [comment] 2024-11-13 20:29
👋🏽 The PR has been deployed to production

**Comment by DylanDylann** [comment] 2024-11-14 03:24
@NJ-2020 Could you create the PR again to fix this issue?

**Comment by DylanDylann** [comment] 2024-11-14 04:11
@NJ-2020 Could you help to point out why we can't reproduce anymore? Our previous PR was reverted

**Comment by DylanDylann** [comment] 2024-11-14 04:16
Do you mean that the BE no longer returns errors when we pass an undefined value to completedTaskReportActionID params?

**Comment by DylanDylann** [comment] 2024-11-14 04:58
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by DylanDylann** [comment] 2024-11-14 05:00
Confirmed the bug is fixed on staging

**Comment by sonialiap** [comment] 2024-11-14 12:24
@DylanDylann I see that this is linked to a deploy blocker, but seems like that was due to needing BE changes, is that correct?

**Comment by DylanDylann** [comment] 2024-11-14 12:25
@sonialiap yes. And It is done now

**Comment by sonialiap** [comment] 2024-11-19 09:24
Payment summary:
- @NJ-2020 $250 via upwork - offer sent
- @DylanDylann $250 via upwork - offer sent

**Closed** 2024-11-22 11:33 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
