### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] Split bill value reverts to NAN, and avatar is removed on removing members from workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18671] opened 2023-05-09 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open an existing workspace with members/create a workspace with members added
2. Click on '+' icon in the workspace
3. Click on 'Split bill' link
4. Enter amount & click on 'Next' button
5. Verify that all members are selected & click on 'Split' button
6. Click on 'Profile' avatar
7. Click on 'Workspaces'
8. Click the workspace where you split bill
9. Click on 'Manage members' link
10. Remove all the added members

## Expected Result: 
Split bill value shouldn't revert to NAN, and avatar shouldn't be removed
## Actual Result: 
Split bill value reverts to NAN, and avatar is removed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f1b23525-af87-402d-960d-bcc4fbbb0f7d

https://github.com/Expensify/App/assets/43996225/76f673fd-5091-4a3b-a034-e4e6af794a42

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683621419205069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109a4c307282a514a</li>
        <li>Upwork Job ID: 1656024641870311424</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-05-09 20:02
@s77rt @roryabraham, you guys might have some context on this one maybe? https://expensify.slack.com/archives/C01GTK53T8Q/p1683645094297739?thread_ts=1683638006.562349&cid=C01GTK53T8Q

**Comment by wahaha999** [comment] 2023-05-10 03:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount and multiple avatars in split bill preview incorrectly changed after removing all members.
### What is the root cause of that problem?
The root cause is an invalid condition to check whether there are multiple participants in a split billing action. The  [condition](https://github.com/allroundexperts/Expensify/blob/b7300273da1b6862dd9df75ebe0fa526bf7f2d11/src/components/ReportActionItem/IOUAction.js#L72) always  return false if all members are removed. why? This is because `props.chatReport.participants.length` is always 1. `props.chatReport.participants` contains the current participants of the workspace. So, after removing all members, the value of `props.chatReport.participants` would be just the workspace admin. From this cause, Split bill preview occurred the issues.
### What changes do you think we should make in order to solve the problem?
We just need to update the [condition](https://github.com/allroundexperts/Expensify/blob/b7300273da1b6862dd9df75ebe0fa526bf7f2d11/src/components/ReportActionItem/IOUAction.js#L72) in IOUAction.js. Getting participants from `action.originalMessage` is appropriate.

### What alternative solutions did you explore? (Optional)

#### - FYI Attached after fixed on my local
![image](https://github.com/Expensify/App/assets/74569731/a0bdc26e-6907-4876-80ce-0a328aadf5b5)

**Comment by Julesssss** [comment] 2023-05-10 07:52
This is likely related to my recent changes, I'll be happy to take this one form you @aldo-expensify if you'd like.

**Comment by trjExpensify** [comment] 2023-05-13 14:39
@slafortune, I'll take over this one from you. @eVoloshchak, can you prioritise reviewing the proposals here, please? Thanks!

**Comment by eVoloshchak** [comment] 2023-05-15 15:44
@allroundexperts's [proposal](https://github.com/Expensify/App/issues/18671#issuecomment-1540841920) looks good to me.
It was the first proposal to correctly identify the root cause and propose a fix for it. Some aspects of the updated proposal could be inspired by @olivierhabi's proposal (not saying they were), but the first complete proposal that identifies the root cause and proposes an appropriate fix - is a winning proposal

🎀👀🎀 C+ reviewed
cc: @aldo-expensify 


>If there are no remaining members in workspace, we can also not show the split bill IOUPreview altogether. I'm not sure what the expected behaviour is here.

I don't think we should hide it, it's should display the participants that we're added to split bill and the time of it's creation, no matter if they still members of the workspace. We could grey out those participants if need be, but that looks like a separate issue

**Comment by aldo-expensify** [comment] 2023-05-15 17:13
Sorry @Julesssss I missed your [message](https://github.com/Expensify/App/issues/18671#issuecomment-1541520440). I'll remove myself so there is no confusion about who is the internal engineer handling this.

**Comment by trjExpensify** [comment] 2023-05-16 18:27
Yeah, I think we do Melv. Just awaiting a 🟢 light to proceed with the PR.

**Comment by Julesssss** [comment] 2023-05-22 08:51
I sware I assigned this last week 🤦

**Comment by trjExpensify** [comment] 2023-06-05 12:38
Alrighty, it's time for payment but the checklist hasn't been completed at all. @allroundexperts & @eVoloshchak can you guys jump on that? 

In the meantime, confirming the payments due as: 

@Natnael-Guchima - $250 for the bug report
@eVoloshchak - $1,500 for C+ review & #urgency bonus 
@allroundexperts - $1,500 for the fix & #urgency bonus

**Comment by eVoloshchak** [comment] 2023-06-06 18:05
-  The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18143

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18143/files#r1220091573

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

- Determine if we should create a regression test for this bug.

-  If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by eVoloshchak** [comment] 2023-06-06 18:12
**Regression Test Proposal**

1. Open an existing workspace with members/create a workspace with members added
2. Click on '+' icon in the workspace
3. Click on 'Split bill' link
4. Enter an amount & click on 'Next' button
5. Verify that all members are selected & click on 'Split' button
6. Click on 'Profile' avatar
7. Click on 'Workspaces'
8. Click the workspace where you split bill
9. Click on 'Manage members' link
10. Remove all the added members
11. Go back to the conversation with split bill
12. Verify that split bill value isn't NAN, and avatars of user's is still visible

**Do we agree 👍 or 👎**

**Comment by trjExpensify** [comment] 2023-06-06 20:57
>2. Click on '+' icon in the workspace

Presumably you mean in the #announce room here yeah? The `Split bill` option doesn't exist in a member's workspace chat, right?

**Comment by eVoloshchak** [comment] 2023-06-06 21:53
> Presumably you mean in the #announce room here yeah? 

Yeah, I meant the announce room. Edited the comment to reflect this
> The Split bill option doesn't exist in a member's workspace chat, right?

Right, there is no Split Bill option for Workspace chats. User-created policy rooms and default rooms like #admins or #announce will always have the Split Bill option unless there are no participants at all (e.g. #admins room for a policy with only 1 admin) DM chats will have the Split Bill option only when there are at least 3 people in the chat.

**Comment by trjExpensify** [comment] 2023-06-07 22:10
Solid. Thanks! Regression test issue added [here](https://github.com/Expensify/Expensify/issues/290014).

Made the payments, closing!

**Closed by trjExpensify** 2023-06-07 22:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
