### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Users who are not assigned can update the assignor for the task and update the status of the task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21716] opened 2023-06-27 17:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 account A and B on 2 devices
2. A create a group include B and C
3. A create a task but not assign anyone
4. B go to detail a task, observed that B cannot update status task
5. B click avatar where the person is assigned
6. B assign myself
7. B click "mark as done"
## Expected Result: 
B can't assign himself and update the task
## Actual Result: 
B can assign himself and update the task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/27fdfc5c-5ede-4274-a285-c1ec1984e339

https://github.com/Expensify/App/assets/43996225/a9f5302b-d91d-4b3a-ac1c-d436f8b7283a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687614685996199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d124d13032a7005</li>
        <li>Upwork Job ID: 1676990326156591104</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-06-28 21:54
checking on expected behavior in slack before moving forward

https://expensify.slack.com/archives/C049HHMV9SM/p1687989265525919?thread_ts=1687614685.996199&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-07-06 16:23
Missed the label but this is a bug.

**Comment by mananjadhav** [comment] 2023-07-06 21:09
@namhihi237 Based on the slack conversation I think the task should be enabled for policy admins, creator(owner) and assignee. Does your proposal cover all the scenarios?

**Comment by mananjadhav** [comment] 2023-07-10 17:15
Based on the requirements @Nodebrute's proposal looks good [here](https://github.com/Expensify/App/issues/21716#issuecomment-1626860432). 

@puneetlath @kevinksullivan Wouldn't this also require a backend fix?

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-07-10 17:45
Wait for @PauloGasparSv to review and assign the job. Thanks for the patience here.

**Comment by PauloGasparSv** [comment] 2023-07-13 13:39
Thks for bumping me team, I tried to focus on some important issues during the week and totally missed this!

> @mananjadhav Could you please let me know the next steps here?
> Hey @PauloGasparSv what's the update here?
> Quick bump @PauloGasparSv.

I'm assigning @Nodebrute here : ) 


> @puneetlath @kevinksullivan Wouldn't this also require a backend fix?

I can follow up to that, will replicate this when I have some free time (or while testing the P.R. for this issue)!

**Comment by PauloGasparSv** [comment] 2023-07-13 13:41
I think some of these shouldn't have been created since I only assigned @Nodebrute so I'll hide them here : /

**Comment by PauloGasparSv** [comment] 2023-07-13 20:26
> @mananjadhav Quick question: should I disable title and description also ?

I think so because that user shouldn't be able to update the task either @Nodebrute.

We need to make sure that the "Complete/Reopen" button is always disabled too, looking at the evidence linked in this GH it looks like the button became enabled.

Can you also check if the 3 dots action menu (that also display the complete/reopen options) is showing the options as disabled?

**Comment by PauloGasparSv** [comment] 2023-07-15 12:32
Hey @kevinksullivan I'm going OOO for 2 weeks (starting on July 17th, back on July 31st) so can we re-assign this issue and the P.R. review to another engineer?

cc @Nodebrute @mananjadhav

**Comment by mananjadhav** [comment] 2023-07-15 12:45
Yes it would  be better. I’ll be done with this by tomorrow.  Can you reassign someone @PauloGasparSv ?

**Comment by mananjadhav** [comment] 2023-07-17 10:12
@kevinksullivan Can you please assign another engineer for the review please?

**Comment by mananjadhav** [comment] 2023-07-18 14:40
@kevinksullivan quick bump on the previous comment?

**Comment by kevinksullivan** [comment] 2023-07-19 13:10
Sorry @mananjadhav , was OOO. New internal engineer assigned

**Comment by mananjadhav** [comment] 2023-07-20 18:26
@Li357 Can you please check the linked PR?

**Comment by Li357** [comment] 2023-07-24 15:21
Not overdue, going through regression testing

**Comment by mananjadhav** [comment] 2023-07-29 19:00
While this is treated as a bug, I would also consider this a feature request. We discussed on the group on what the expected behavior should be and then finally added the code to handle this. I wouldn't attribute this to any PR, unless this was decided earlier which I can't find.

I think we should add a regression test for this one. @kevinksullivan we should add the Tests from the PR.  @kevinksullivan @Li357 wdyt?

**Regression Test Steps**

1. Open Expensify as User A.
2. Go to any room.
3. Click on 'Assign Task,' fill in the task details, and share it in the room.
4. Open Expensify as User B, who is not the assignee, assignor, or PolicyAdmin.
5. Go to the same room and open the task report.
6. Verify that User B cannot edit the title, description, assignee, or mark the task as completed

7. Perform steps from 4 to 6 with user C who is policy admin and verify that they're able to edit the title, description, etc.
8.Perform steps from 3 to 6 with user D with the task assigned to them and  verify that they're able to edit the title, description, etc.

**Comment by Li357** [comment] 2023-07-31 21:04
Agree, I think regression tests here would be valuable and those steps look good (I think steps 3 to 6 should be 4 to 6 for step 8?)

**Comment by mananjadhav** [comment] 2023-08-01 03:44
For step 8, it is 3 to 6, as we need to add an assignee here.

**Comment by kevinksullivan** [comment] 2023-08-01 18:53
Payment summary:

- Reporter: @namhihi237 $250
- Contributor: @Nodebrute $1,000
- C+: @mananjadhav $1,000

**Comment by JmillsExpensify** [comment] 2023-08-01 18:55
Reviewed details for @mananjadhav. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by kevinksullivan** [comment] 2023-08-01 19:52
Upwork payments done

**Closed by kevinksullivan** 2023-08-01 19:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
