### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] mWeb - Scan - Page is skewed when dragging Scan content to the right

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28689] opened 2023-10-03 08:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Scan.
3. Highlight the text in the Scan tab.
4. Drag the content to the right.

## Expected Result:
The page will not be skewed.

## Actual Result:
The page is skewed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.76-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4b820311-1461-4b0a-9e9b-88b1a87147f0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169e8ba6785ac7a07</li>
        <li>Upwork Job ID: 1709118057164894208</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 27166771</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by AmjedNazzal** [comment] 2023-10-04 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb - Scan - Page is skewed when dragging Scan content to the right

### What is the root cause of that problem?

The reason for this is with the way createMaterialTopTabNavigator is designed, when we pass multiple screens to createMaterialTopTabNavigator what it does is take these components and put them side by side like a carousel to allow for swiping, what this means is for the browsers this is just one element with bigger than screen width and so when selecting text, to the browser all text within the entire element is selectable together leading to the selection caret jumping to the next tab and causing misalignment 

### What changes do you think we should make in order to solve the problem?

We first should prevent the misalignment, we can do that by simply applying overflow clip to OnyxTabNavigator

```javascript
<OnyxTabNavigator
    style={{ overflow: 'clip' }}
```

Next we can create a manual handling of selection to not allow selection to go to the next tab, from what I could text it seem like the only tab this could happen is receiptSelector so we can make a function to handle the selection there:

```javascript
const onSelectionChange = () => {
    const selection = window.getSelection();
    const { anchorNode, anchorOffset, focusNode, focusOffset } = selection;
    
    if (textRef.current) {
        if (textRef.current.contains(focusNode)){
            setSelectionPoints({
                start: anchorOffset,
                end: focusOffset
            });
            anchorNodeRef.current = anchorNode;
            focusNodeRef.current = focusNode;
        }
        if (!textRef.current.contains(focusNode)) {
            selection.removeAllRanges();
            setTimeout(() => {
                selection.setBaseAndExtent(anchorNodeRef.current, selectionPoints.start, focusNodeRef.current, selectionPoints.end);
            }, 100);
        }
      }
}

useEffect(() => {
    document.addEventListener('selectionchange', onSelectionChange);
    return () => {
      document.removeEventListener('selectionchange', onSelectionChange);
    };
  }, [selectionPoints]);
```

By doing this we allow selection exclusivly to the element ref that we want to be selectable.

### Result

https://github.com/Expensify/App/assets/74202751/c9755ebb-4c21-4cee-bdd4-0fadb344030d

**Comment by narefyev91** [comment] 2023-10-06 08:00
Proposal from @ZhenjaHorbach looks good to me https://github.com/Expensify/App/issues/28689#issuecomment-1745614671
We should use simple fix and just disable selection for text
We already have the same behaviour here
![Screenshot 2023-10-05 at 10 41 25](https://github.com/Expensify/App/assets/28352309/ee95f585-0836-4908-bb53-97ae15c1cfc5)
🎀 👀 🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2023-10-09 14:39
Thanks for the review @narefyev91, assigned @ZhenjaHorbach

**Comment by marcochavezf** [comment] 2023-10-12 17:16
Not overdue, @ZhenjaHorbach when a PR would be ready for review?

**Comment by marcochavezf** [comment] 2023-10-12 19:38
Sure, I will try again

**Comment by anmurali** [comment] 2023-10-31 21:51
Paid @ZhenjaHorbach with urgency bonus

**Comment by anmurali** [comment] 2023-10-31 21:53
@narefyev91 can you complete the BZ checklist?

**Comment by narefyev91** [comment] 2023-11-01 08:03
- The PR that introduced the bug has been identified. Link to the PR - N/A - it was not a regression - just additional functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by marcochavezf** [comment] 2023-11-17 19:08
I think there's nothing left here, sop I will close it out but feel free to re-open it if there's still something pending.

**Closed by marcochavezf** 2023-11-17 19:08 UTC
Labels: External, Weekly, Overdue, Bug
