### ISSUE TITLE
[$500] Workspace - No space between 3 dots and admin

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32967] opened 2023-12-13 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-23
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and login with user having long username
2. Click on plus and click on start chat
3. Observe that we maintain gap between 3 dots of username and 'Add to group' button
4. Similarly, open settings->workspaces->any workspace->members
5. Observe that there is no space between 3 dots of username and admin tab

## Expected Result:
App should maintain space between 3 dots of username and admin tab on members page as we maintain on similar layout start chat page between 3 dots and 'Add to group' button

## Actual Result:
App does not maintain space between 3 dots of username and admin tab on members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc97b8e0-a37a-4dd9-8833-540797ce6e4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c7f37fb82d95dae</li>
        <li>Upwork Job ID: 1734937400008077312</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28064586</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by namhihi237** [comment] 2023-12-13 14:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to add space between 3dots and admin text
### What is the root cause of that problem?
Currently we don't have the space in the text and label
https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/components/SelectionList/UserListItem.js#L47-L48
### What changes do you think we should make in order to solve the problem?
We should add space here, I think margin 12 or 16px
https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/components/SelectionList/UserListItem.js#L47-L48
### What alternative solutions did you explore? (Optional)

**Comment by mghazanfar** [comment] 2023-12-13 14:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We see no space between ellipsis text and Admin badge.

### What is the root cause of that problem?
No proper spacing.

### What changes do you think we should make in order to solve the problem?

Applying latest CSS grid is the best practice for this with proper gap between columns.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mghazanfar** [comment] 2023-12-13 14:46
Contributor details
Your Expensify account email: <ghazanfar899@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01396a4ca84c29cfae>

**Comment by dragnoir** [comment] 2023-12-13 14:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - No space between 3 dots and admin

### What is the root cause of that problem?

Margin missing between 3 dots and admin
https://github.com/Expensify/App/blob/d6755d68444d5d8e9e2c7593c7eb3f1228a20c67/src/components/SelectionList/UserListItem.js#L21

### What changes do you think we should make in order to solve the problem?

Add Margin-right: 12px `styles.mr3` same as the margin with the profile picture

```html
<View  style={[styles.flex1, styles.flexColumn, styles.justifyContentCenter, styles.alignItemsStart, styles.optionRow, styles.mr3]}>
```
### POC
![image](https://github.com/Expensify/App/assets/12425932/9986a14e-c79f-4133-a26e-9cfe1f460f0a)

**Comment by cubuspl42** [comment] 2023-12-18 11:49
I approve the proposal by @dragnoir 

As the scope of this issue is narrow, a proposal mentioning a specific style from our stylesheet was appropriate. As I understand it, it was the first proposal to mention a correct style.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2023-12-18 12:02
@ZhenjaHorbach Personally, I agree, and I would recommend adding `ml2` during the PR review. Still, they were the first to mention `mlX`. Choosing between `ml2` and `ml3` is an aesthetic decision.

While this can never be proven, I think that it's quite likely that your proposal from `mh2` to `ml2` was done in reaction to the proposal by @dragnoir.

Considering both things, I don't think you have solid arguments for discussing the proposal selection here. I suggest not continuing it, if you don't mind

**Comment by cubuspl42** [comment] 2023-12-18 12:44
> In fact, I can say the same thing about the fact

You can, but it is not clear whether you should. It's quite difficult to pick a proposal based on the substantive value when the proposals have 10 edits and are essentially similar.

Are you really confident that your proposal is significantly better, beyond a reasonable doubt, based on something other than the fact that it's yours? In other words, if you stepped outside your perspective, don't you think that all other contributors could start a discussion the second I selected _any_ proposal?

> But I think that the correct place for fixation

The place where the fix should be applied is typically the least challenging to find.

> your decision is not entirely fair

And would be fair, if what? If I selected your proposal, and only then?

These are rhetorical questions. Please don't answer them. Please also note that suggesting that a decision by C+ or an internal engineer is "not fair" is not a good idea. At best, it will build you a bad image, at worst it could lead to an official warning.

**Comment by johncschuster** [comment] 2023-12-18 15:20
Just caught up. I see we've approved @dragnoir's proposal. I've just assigned the issue to them.

Thanks!

**Comment by dragnoir** [comment] 2023-12-18 23:41
PR will be ready in the next 24 hours.

**Comment by dragnoir** [comment] 2024-01-05 14:17
@johncschuster @cubuspl42 it's my 1st payment, when can I expect to get paid?

**Comment by cubuspl42** [comment] 2024-01-08 12:23
@dragnoir It seems the automation didn't run here, and the payment wasn't processed properly!

@johncschuster @techievivek Friendly bump!

**Comment by johncschuster** [comment] 2024-01-12 14:54
Sorry for missing this, @cubuspl42! I'll get payment issued today!

**Comment by johncschuster** [comment] 2024-01-12 21:59
@cubuspl42, I've issued payment to you.
@dragnoir, I've hired you for the job on Upwork. Once accepted, I'll get payment issued.

Thank you both for your patience!

**Comment by dragnoir** [comment] 2024-01-12 22:04
@johncschuster Accepted. Thank you

**Comment by dragnoir** [comment] 2024-01-16 07:49
@johncschuster any other steps I need to proceed for the payment to be released, pls!

**Comment by cubuspl42** [comment] 2024-01-16 10:34
@dragnoir Just to reassure you, issue handling and payments go much more smoothly with functioning automation. We just started to depend on it. Unfortunately, automation breaks once in a while.

**Comment by dragnoir** [comment] 2024-01-16 10:36
I already accepted the offer on Upwork. Also, I think 1st payment is not automatic!

**Comment by johncschuster** [comment] 2024-01-17 02:49
Payment has been issued. Thank you for your patience!

**Comment by cubuspl42** [comment] 2024-02-12 09:55
@johncschuster Thanks! I think we can just close this issue now?

**Comment by cubuspl42** [comment] 2024-04-02 08:02
@johncschuster Bump, this just needs closing

**Closed** 2024-04-08 18:40 UTC
Labels: Reviewing, External, Monthly, Bug
