### ISSUE TITLE
[HOLD for 41326][$250] Submission frequency - Selection is not highlighted and unable to navigate with keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41896] opened 2024-05-09 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Workflows.
4. Enable Delay submissions.
5. Click Submission frequency.
6. Navigate through the list with keyboard.

## Expected Result:
In Step 5, the selected option in the list will be highlighted.
In Step 6, the list should be accessible with keyboard.

## Actual Result:
In Step 5, the selected option in the list is not highlighted.
In Step 6, the list cannot be navigated with keyboard.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6ec5138-375b-4c21-823a-d57397a42c6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181e130b5874b8b3e</li>
        <li>Upwork Job ID: 1788582876252483584</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by kbecciv** [comment] 2024-05-09 12:04
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-05-09 12:04
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by samilabud** [comment] 2024-05-09 20:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Submission frequency - Selection is not highlighted and unable to navigate with keyboard

### What is the root cause of that problem?
Currently we are not using any keyboard control navigation in the [WorkspaceAutoReportingFrequencyPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx) component, we are just showing the data in a [FlatList](https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx#L145) using the next render item method:

https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx#L109-L118

### What changes do you think we should make in order to solve the problem?
We should use the most used hook for these scenarios, the [useArrowKeyFocusManager](https://github.com/Expensify/App/blob/main/src/hooks/useArrowKeyFocusManager.ts) hook. We can get the focused index of each row and with that specify in the [render item method](https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx#L109-L118) which one is selected.

To do this we should add the next code in [WorkspaceAutoReportingFrequencyPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx) component:

```
const isFocused = useIsFocused();

    const [focusedIndex] = useArrowKeyFocusManager({
        initialFocusedIndex: 1,
        maxIndex: Math.min(autoReportingFrequencyItems.length - 1, CONST.MAX_OPTIONS_SELECTOR_PAGE_LENGTH - 1),
        disabledIndexes: [],
        isActive: true,
        isFocused,
    });

    const selectFocusedOption = () => {
        const focusedOption = autoReportingFrequencyItems[focusedIndex];

        if (!focusedOption) {
            return;
        }

        onSelectAutoReportingFrequency(focusedOption);
    };
    /** Selects row when pressing Enter */
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ENTER, selectFocusedOption, {
        captureOnInputs: true,
        shouldBubble: false,
        shouldStopPropagation: true,
        isActive: isFocused,
    });
```
Also we should specify which item is selected:
```
const renderItem = ({item, index}: {item: WorkspaceAutoReportingFrequencyPageItem; index: number}) => {
        const isItemFocused = focusedIndex === index;
        return (
            <>
                <RadioListItem
                    item={item}
                    onSelectRow={() => onSelectAutoReportingFrequency(item)}
                    showTooltip={false}
                    isFocused={isItemFocused}
                />
                {isMonthlyFrequency && item.keyForList === CONST.POLICY.AUTO_REPORTING_FREQUENCIES.MONTHLY ? monthlyFrequencyDetails() : null}
            </>
        );
    };
```
Test:

https://github.com/Expensify/App/assets/5216036/fa4b6234-6a8e-4ab9-b5b3-745dd3632f25

**Comment by trjExpensify** [comment] 2024-08-08 14:30
Can we close this? The issue linked has been closed. https://github.com/Expensify/App/issues/41326

**Closed** 2024-08-08 16:27 UTC
Labels: External, Monthly, Help Wanted, Overdue, Bug
