### ISSUE TITLE
[HOLD 35626][$500] Chat - User redirected to LHN instead of chat after going back from task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35697] opened 2024-02-02 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Tap "+" > "Assign task"
4. Create a task
5. Open the task from the chat history
6. Tap the back icon

## Expected Result:
User is returned to the chat where the task was created

## Actual Result:
User is redirected to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5cfd7d76-8fa4-4940-b668-0b238b019135

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014da3b04c59616570</li>
        <li>Upwork Job ID: 1753490177126359040</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 18:42
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by neil-marcellini** [comment] 2024-02-02 18:46
I would guess that this is related to [Wave 8] Ideal nav  #33280, but I'll have to confirm. I doubt we want to revert that since it's such a large PR, so let's see if we can find the fix. Assigning external for additional help as I investigate.

**Comment by thienlnam** [comment] 2024-02-02 18:50
Looks related to all these other .goBack bugs which I believe is being handled by @adamgrzybowski https://expensify.slack.com/archives/C01GTK53T8Q/p1706830933437469?thread_ts=1706829675.205549&cid=C01GTK53T8Q

**Comment by neil-marcellini** [comment] 2024-02-02 18:56
This is already being tracked with this issue [[Wave 8] [Ideal Nav] Back navigation issues](https://github.com/Expensify/App/issues/35626), so I'm going to remove the blocker label and hold it on that issue.

**Comment by hayata-suenaga** [comment] 2024-02-02 19:03
Yes we can close this issue as the regression is already tracked 🙇

**Closed** 2024-02-02 19:51 UTC
Labels: External, Engineering, Weekly
