### ISSUE TITLE
[HOLD for payment 2024-12-25] [$500] Android - Chat - Trying to paste onyx data of #applause.expensifail.com chat app freezes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46766] opened 2024-08-03 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.9.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Long press #applause.expensifail.com and select copy onyx data
3. Open a report and try to paste it

## Expected Result:
Trying to paste onyx data of #applause.expensifail.com chat app must not freeze

## Actual Result:
Trying to paste onyx data of #applause.expensifail.com chat app freezes and shows not responding pop up box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/29bd8bfb-e1bb-4040-9050-a5d04c8696a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d242239866ebb6cc</li>
        <li>Upwork Job ID: 1822052495061109151</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103915587</li>
<li>dominictb | Contributor | 103915591</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-08-03 15:39
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-03 15:40
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-03 15:52
We think that this bug might be related to 
#wave-control

**Comment by kevinksullivan** [comment] 2024-08-09 23:28
I don't know where this fits roadmap wise, since it's just general chat troubleshooting.

**Comment by kevinksullivan** [comment] 2024-08-09 23:29
will just put external on it for now to see if it is a quick fix.

**Comment by c3024** [comment] 2024-08-10 06:50
@lanitochka17 

This works well with chats on my account. I guess this bug happens because a lot of data is pasted at once. 

Could you paste the data in a notepad and share the text file? 

Does pasting this data work well on other platforms?

**Comment by lanitochka17** [comment] 2024-08-12 12:55
@c3024 
[вставка.txt](https://github.com/user-attachments/files/16581857/default.txt)
Issue reproducible on mWeb/Safari, mWeb/Chrome, IOS 
Not reproducible in Web

**Comment by c3024** [comment] 2024-08-12 15:31
Waiting for proposals

**Comment by c3024** [comment] 2024-08-20 09:38
Waiting for proposals!

**Comment by kevinksullivan** [comment] 2024-08-24 17:24
Ah I see this is not reproducible as of late so I am going to close it.

**Comment by c3024** [comment] 2024-08-31 13:38
@kevinksullivan , this is still reproducible. Please reopen this issue. @dominictb posted a viable solution.

**Comment by Julesssss** [comment] 2024-09-11 08:21
As mentioned above, this is still reproducible. 

@c3024 could you please review [this](https://github.com/Expensify/App/issues/46766#issuecomment-2318594335) proposal, thanks.

**Comment by kevinksullivan** [comment] 2024-09-11 21:50
Looping in another BZ member as I'll be OOO

**Comment by tomekzaw** [comment] 2024-09-16 06:30
I'm not sure if skipping Markdown formatting is the right fix (it's definitely poor user performance).

Instead, can we focus on improving the performance instead of ignoring the problem?

**Comment by Julesssss** [comment] 2024-09-16 09:10
> Instead, can we focus on improving the performance instead of ignoring the problem?

Are you able to share an alternative proposal?

**Comment by tomekzaw** [comment] 2024-09-16 09:23
> Are you able to share an alternative proposal?

Not really, just wanted to suggest a different approach to this very problem, not a concrete solution.

As for the current proposal, I don't think `maxParsableTextLength` is a good solution as well. Not only this is a very specific condition (text length) but also moves the responsibility of implementing the logic to the live-markdown library. How about exposing a boolean prop `enableFormatting` from live-markdown library and moving the condition logic to E/App? This is more extendable, e.g. it will allow us to disable Markdown formatting based on the complexity of the text (e.g. how many syntax elements are there) instead of solely on text length.

**Comment by Julesssss** [comment] 2024-09-16 09:38
The ideas of using a lib prop, and moving responsibility of the cutoff point to the client are both good suggestions. 

@tomekzaw are you happy for @dominictb to merge those into his solution?

**Comment by tomekzaw** [comment] 2024-09-16 09:45
@Julesssss Sure, sounds like a plan.

**Comment by tomekzaw** [comment] 2024-09-16 09:52
@dominictb As for the prop name, maybe let's go with `enableMarkdownFormatting`? What do you think?

**Comment by tomekzaw** [comment] 2024-09-20 13:31
@dominictb I'm not sure if I understand the dillema correctly. Specifically:

> does that mean whenever there's a text change event

What is the actual question?

> `enableMarkdownFormatting` will be calculated

`enableMarkdownFormatting` is a prop that is passed from outside, it will not be calculated

> This basically means the current implementation of markdown input component will be changed dramatically. Do you think it's OK to do that?

Will it indeed?

For web implementation, it's just a matter of using `enableMarkdownFormatting` so that `globalThis.parseExpensiMarkToRanges` is not called and simply return `[]` instead.

For native implementation, it's just a matter of passing `enableMarkdownFormatting` prop to `MarkdownTextInputDecoratorView` and doing the same thing but on native side.

> The point is we need to stop the markdown formatting immediately after the text change event, hence this dilemma

What's the actual dillema?

**Comment by tomekzaw** [comment] 2024-09-23 09:26
@dominictb Thanks for your response, I see the problem now.

So if the value of `enableMarkdownFormatting` is calculated based on `value` state, then it would still format message if the text was pasted since `value` is not updated at this point yet.

The workaround in this case would be to pass a function, instead of a boolean, to `enableMarkdownFormatting`. This function would be invoked each time we need to check if we should parse the current text (no matter if it's from React state or from event handlers like `onTextChanged`). So the API would be like:
```ts
enableMarkdownFormatting: (value: string) => boolean;
```
and the usage would be:
```ts
enableMarkdownFormatting={(value) => value > 5100}
```

However, this would be problematic on Android and iOS since regular JS functions can't be run on the UI thread unless they are marked as worklets. Note that we're actually integrating worklets to live-markdown in https://github.com/Expensify/react-native-live-markdown/pull/439. This would mean that we would need two separate worklets now:
```ts
enableMarkdownFormatting: (value: string) => boolean;
parser: (value: string) => MarkdownRange[]
```

So, why don't we merge this logic into `parser` worklet? We can just `return []` at the beginning of the parser worklet if some condition is met (e.g. `value.length > 5100`).

Finally, https://github.com/Expensify/react-native-live-markdown/pull/439 is not merged yet so the classic counterpart would be to just add the following change in `parseExpensiMarkToRanges` in `parser/index.ts`?
```ts
function parseExpensiMarkToRanges(markdown: string): MarkdownRange[] {
  if (markdown.length > 5000) {
    return [];
  }
  // rest of existing code
}
```

@dominictb What do you think?

**Comment by Julesssss** [comment] 2024-09-26 08:07
PR raised

**Comment by c3024** [comment] 2024-10-09 18:15
App PR is about to be finalized, Melvin!

**Comment by tomekzaw** [comment] 2024-10-22 18:02
@dominictb That's true, there are some performance issues when typing long messages. One way would be to re-apply spans only if any change is detected. This something we'd like to address sometime in the future.

**Comment by Julesssss** [comment] 2024-11-01 12:04
Hey @dominictb, yeah it's tough because it seems there's no magic number at which performance is stable on all platforms. 

I liked the original proposal and I would be happy to do something like this: 
- Complete the original plan, using a reduced limit of 5000 (or perhaps lower)
- Then decide if we want to request improvements to `react-native-live-markdown`/`Expensimark`

> By the way I notice the live-markdown is being reverted back to 0.1.164 (while my fix is introduced in 0.1.168

@dominictb it looks like release [version](https://github.com/Expensify/react-native-live-markdown/releases/tag/0.1.179) is back up to `[0.1.179](https://github.com/Expensify/react-native-live-markdown/releases/tag/0.1.179)`

**Comment by tomekzaw** [comment] 2024-11-06 11:45
@dominictb

> given that the https://github.com/Expensify/react-native-live-markdown/pull/439 is nowhere near to merged soon

Here's the most recent update on #439: https://github.com/Expensify/App/issues/50949#issuecomment-2457241108

> could I update the parser in the react-native-live-markdown directly

Okay, let's do it.

**Comment by Julesssss** [comment] 2024-11-06 12:02
Sounds good. @c3024 are you happy with the plan?

**Comment by c3024** [comment] 2024-11-06 12:06
Yes, that sounds good!

**Comment by tomekzaw** [comment] 2024-11-13 08:36
PR https://github.com/Expensify/react-native-live-markdown/pull/542 has been merged.

**Comment by sonialiap** [comment] 2024-12-27 11:40
Payment summary:
- @c3024 $500 please complete the [checklist](https://github.com/Expensify/App/issues/46766#issuecomment-2551295052) for payment 💰 
- @dominictb $500 paid in upwork ✔️

**Comment by c3024** [comment] 2024-12-30 03:40
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No specific PR can be held responsible for this bug. Moreover, the author of the library made suggestions for the PR and reviewed it.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: This issue happens when pasting an extremely large text with formatting. No discussion was started because this is not a usual flow.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- None

### Test:


1. Go to any chat.
2. Copy the text from this [file](https://github.com/user-attachments/files/17331883/default.txt) and paste it in composer.
3. Verify that the app does not freeze and you can edit the text in the composer.

Do we agree 👍 or 👎

**Closed** 2024-12-30 12:15 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by yellowtailfan** [comment] 2025-06-03 06:43
@dominictb @c3024 While fixing #57241 we found this line https://github.com/Expensify/App/blob/2739a5f596845a4fdb726021f1c6433998333ad2/src/hooks/useHtmlPaste/index.ts#L80 from your PR #49228 caused the bug. The bug was only reproduced on Windows with Expensify running in Chrome or Firefox so it was quite specific.

The cause of the bug was:
* Copying text in Word produces a clipboard with plain text and HTML
* The HTML has a verbose header that is larger than 10K even when the body is only a few lines
* When the clipboard is pasted into Expensify, the app detects the HTML in the clip
* The call to `Parser.htmlToMarkdown()` linked above truncates the HTML to 10K before parsing
* This removes the body and the parser fails to parse the header producing raw HTML codes
* The raw HTML codes are pasted into the chat window

The truncation is important to maintain performance and fit inside the database storage limits. Our fix was to keep the truncation but move it to occur after the body text has been extracted. This means:
* Large headers are removed before truncation in a relatively quick regex operation
* The remaining body is truncated to 10K before expensive parsing into Markdown

For details please see the PR #61322.
