### ISSUE TITLE
After scrolling to the old messages and going to LHN when you navigate back the chat stays at old messages and not the most recent ones - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9236] opened 2022-05-31 04:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open mobile App/Website
2. Go chat scroll Up
3. Touch on Back arrow
4. Then go to chat again

## Expected Result:
It should refresh and scroll down to the latest messages.

## Actual Result:
It stays at the old messages unless you navigate to a different chat and come back to the first one.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.169-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/171090351-01ab7e98-1e37-4a6b-955c-e29c1b66c9aa.mp4

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651007418502999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2022-05-31 04:37
Checking in about this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1653971597968589?thread_ts=1651007418.502999&cid=C01GTK53T8Q) as I think it might be the intended behaviour.

**Comment by kadiealexander** [comment] 2022-06-02 22:27
Still discussing in Slack, not overdue.

**Comment by kadiealexander** [comment] 2022-06-07 01:41
Going to close this as I think we have consensus on this being the intended behaviour. If you think this should change @Tushu17 please submit the issue as a problem solution statement or Feature Request in Slack. :)

**Closed by kadiealexander** 2022-06-07 01:41 UTC
Labels: Weekly, Planning
