### ISSUE TITLE
[$1000] mWeb - App does not open keyboard on reload on share somewhere page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28550] opened 2023-09-30 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click assign task
3. Add any title and continue
4. Click on share somewhere
5. Reload and observe that app focuses on search but keyboard is not opened

## Expected Result:
App should open keyboard on focus on search on share somewhere page

## Actual Result:
App does not open keyboard on reload on share somewhere page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0fd52e7d-c186-4307-b224-0dc458597bdd

https://github.com/Expensify/App/assets/93399543/39e05b66-589c-4a9e-8e76-2abf105d69e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696015367950349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fb33f28776cfbe2</li>
        <li>Upwork Job ID: 1708225036348899328</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by neg-0** [comment] 2023-10-01 20:38
@rayane-djouah Where within the useEffect did you add the blur? I added it but it does not seem to have any effect on the text input.

**Comment by jjcoffee** [comment] 2023-10-02 12:18
@rayane-djouah Could you confirm if your fix works on mWeb Safari?

**Comment by dhanashree-sawant** [comment] 2023-10-05 12:05
Hi @sophiepintoraetz, sorry for the confusion, will ensure to mention that it is working fine on other platforms while raising the issue from now on.

**Comment by sophiepintoraetz** [comment] 2023-10-07 10:18
Hey @johncschuster! I just need some help babysitting this issue while I'm OOO till 17 Oct - so far, we only have one proposal for @jjcoffee to review. Otherwise, was going to bump in #open source / the agencies!

**Comment by jjcoffee** [comment] 2023-10-10 14:41
@rayane-djouah Any response on this [comment](https://github.com/Expensify/App/issues/28550#issuecomment-1742911392)?

**Comment by jjcoffee** [comment] 2023-10-11 09:29
Yeah it doesn't look like this works **anywhere** where we autofocus on inputs (which we don't do in most places for mWeb). Still waiting for proposals!

**Comment by jjcoffee** [comment] 2023-10-11 11:25
The same happens on iOS Safari by the way:

https://github.com/Expensify/App/assets/27287420/eab5ae0f-e868-40bb-9866-9a0f788e9782

**Comment by johncschuster** [comment] 2023-10-13 20:18
@jjcoffee how are you feeling about the existing proposals? I'm happy to get some more eyes on this in #expensify-open-source.

**Comment by johncschuster** [comment] 2023-10-13 20:19
Posted in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1697228371506259) for proposals

**Comment by johncschuster** [comment] 2023-10-16 20:41
@sophiepintoraetz, I posted an announcement to gather more proposals, but it hasn't really gotten anywhere. Do you feel we should increase the bounty, or shall we wait a few more days?

**Comment by dhanashree-sawant** [comment] 2023-10-17 05:57
The following issue is specifically after reload, safari has that issue even on opening the page normally.

**Comment by sophiepintoraetz** [comment] 2023-10-19 22:05
Thank you for helping me out, @johncschuster - taking this back now.

**Comment by jjcoffee** [comment] 2023-10-23 10:53
Bumped on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1698058371791489).

**Comment by jjcoffee** [comment] 2023-10-23 14:35
After testing based on our discussion [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1698058371791489), I can confirm there isn't really a fix for this as it requires user interaction first before we can programmatically open the keyboard. We're good to close this @sophiepintoraetz!

**Comment by abeebridwan** [comment] 2023-10-23 19:27
I have working on it for over two days..  I was able to blur and refocus.. however the keyboard didn't show... It seems the browser stopped from opening the keyboard without user's interaction 

However there is navigator.virtualKeyboard which is only experimental but also only available on desktop

**Comment by abeebridwan** [comment] 2023-10-23 19:30
Contributor details
Your Expensify account email: olumideuae@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/ridwanabeeb2

**Comment by sophiepintoraetz** [comment] 2023-10-23 22:02
Got it, thanks for the discussion all! Thank you @abeebridwan - looks like you just missed out - but there are plenty of issues for you to get involved with!

**Closed by sophiepintoraetz** 2023-10-23 22:02 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
