### ISSUE TITLE
Date of birth - `Fix the errors` functional is not functional

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19852] opened 2023-05-30 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/18577

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Personal details -> Date of birth
4. Select 1984-03-31
5. Change the month to February
6. Check the input field - it should contain the incorrect value of 1984-02-31
7. Press on `fix the errors

## Expected Result:
Cursor is focused on a date field with an error

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/9a2e4a34deabd1a0c80f94af7a1bfb058ea9d69c406e0eca6d1b99fef3c8b009

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-05-30 22:21
@kbecciv Can you please give an expected behaviour of the fix the errors button click?

**Comment by bogoroh** [comment] 2023-05-31 02:40
<img width="379" alt="Screenshot 2023-05-30 at 9 39 44 P@kbecciv " src="https://github.com/Expensify/App/assets/4615263/6db68f3e-ece3-466d-ac81-1fdbcd754860">


@kbecciv , So the focus actually remains on the DOB Arrows because that's where the customer left off. Here you can see that I've clicked the right arrow and my focus remains there. I believe this is working as intended.

**Comment by Julesssss** [comment] 2023-05-31 10:40
I see your point @bogoroh. Given that the input is no longer selectable I'm not sure what 'fix the errors' should do. Maybe nothing?

**Comment by Julesssss** [comment] 2023-05-31 10:44
@alexpensify we removed the input field [here](https://github.com/Expensify/App/pull/18577), so I'm not sure what the expected behaviour would be here.

**Comment by Santhosh-Sellavel** [comment] 2023-05-31 16:29
@Julesssss I've already answered here -> https://github.com/Expensify/App/issues/15290#issuecomment-1568767002

**Comment by alexpensify** [comment] 2023-05-31 21:51
Thanks @Julesssss-- tomorrow, I'll start a discussion to confirm the next steps here.

**Comment by Julesssss** [comment] 2023-06-01 07:47
> There is nothing to do here,
> Date field is the only field here and highlight with the error
We have the calendar always open, so the user can just pick the validate now.

I agree there's no real action to take, but it seems a bit weird to keep the error message clickable in that case.

**Comment by Santhosh-Sellavel** [comment] 2023-06-01 16:49
@Julesssss 
> > There is nothing to do here,
> > Date field is the only field here and highlight with the error
> > We have the calendar always open, so the user can just pick the validation now.
> 
> I agree there's no real action to take, but it seems a bit weird to keep the error message clickable in that case.

This is a kind of edge case, this pretty much happens on any form with one filed error where the fix the errors is clickable only once. After first clicking the field got a focus post that the fix the errors is unclickable. 

What we can do is remove/hide the error with refactor if needed

**Comment by alexpensify** [comment] 2023-06-01 22:59
@Julesssss with the last feedback, do you think we update the title and the original issue?

**Comment by Julesssss** [comment] 2023-06-02 08:54
Hmm, so maybe we just do nothing here. Rather than having a specific exclusion for this error.

**Comment by alexpensify** [comment] 2023-06-02 13:49
With this feedback, I'm going to close this GH. Thank you to everyone who participated in the conversation.

**Closed by alexpensify** 2023-06-02 13:49 UTC
Labels: Daily, Bug
