### ISSUE TITLE
Unread messages are shown in the LHN whenever a report data is exported to a CSV

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44698] opened 2024-07-01 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719592386443209

## Action Performed:
1. Export a report data to a CSV
2. verify the LHN
## Expected Result:
These reports should not appear unread in the LHN

## Actual Result:

- Exporting to CSV is a report action that we call a “system message”
- Recently implemented a change internally such as all “system messages” are marked as read
- Despite that, every time the team exports report data to a CSV,  LHN is showing unread reports as result of the CSV export
- We’ve confirmed that the ` lastReadTime`  was correctly set to a time later than system message for the CSV

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-06-28 at 10 38 22@2x](https://github.com/Expensify/App/assets/38435837/77053d0c-4f99-4c10-a7bf-7d9d78ec653a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-01 19:25
#44683

**Comment by hurali97** [comment] 2024-07-02 10:16
@muttmuure Please assign this to me 👋

**Comment by muttmuure** [comment] 2024-07-02 10:21
Ty!

**Comment by deetergp** [comment] 2024-07-03 16:00
@hurali97 I suspect this is related to/a duplicate of this GH https://github.com/Expensify/App/issues/44693 so I'd hold at least until that hits production and we do some testing.

**Comment by deetergp** [comment] 2024-07-10 15:57
Investigations are still ongoing with the issue this dupes. Will update here when we know more.

**Comment by puneetlath** [comment] 2024-07-16 14:14
Is this issue different than https://github.com/Expensify/App/issues/44693?

**Comment by deetergp** [comment] 2024-07-17 01:14
No, I don't think so. This is a dupe of that issue. Closing…

**Closed by deetergp** 2024-07-17 01:14 UTC
Labels: Weekly, Bug, AutoAssignerNewDotQuality
