### ISSUE TITLE
Dev: Web - Console error `Error parsing URLs: TypeError: Failed to construct 'URL': Invalid URL`

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26614] opened 2023-09-03 18:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat and enter the message `-77.com`
2. Edit the message and change the text to: `-[77.com](https://-77.com)`
3. Notice that the console error props up.

## Expected Result:
Should not show any console error

## Actual Result:
Shows console error - Url.js:46 Error parsing URLs: TypeError: Failed to construct 'URL': Invalid URL

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.62.0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-11-14 at 5 46 41 PM](https://github.com/Expensify/App/assets/12268372/e108be9c-91eb-452c-ab7d-7aca6f6a8a58)

**Expensify/Expensify Issue URL:**
**Issue reported by:** ~@narzullome~ @Natnael-Guchima reported [earlier](https://expensify.slack.com/archives/C049HHMV9SM/p1692792825436599)
**Slack conversation:** 
- https://expensify.slack.com/archives/C049HHMV9SM/p1693374389112709
- https://expensify.slack.com/archives/C049HHMV9SM/p1699915690734349?thread_ts=1699551645.734819&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fdcd111103dab09</li>
        <li>Upwork Job ID: 1701909826193559552</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MariaHCD</details>

**Comment by StevenKKC** [comment] 2023-09-05 07:59
## Proposal

### Please state again the problem we are trying to solve in this issue.
Web - Console error on #teachers-unite page

### What is the cause of this issue?
If we join #teachers-unite page, there is a Concierge wispher message as below.
![Screenshot 2023-09-05 035654](https://github.com/Expensify/App/assets/131836113/4483ea7d-b60d-4e88-8c76-662c39481a4c)

The hyperlink in `here` is `/settings/profile/display-name`, and this is an invalid url.
So when rendering hyperlink, the following code catch an error, and then display an error on console.
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Url.js#L19-L28
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Url.js#L36-L48
### What changes do you think we should make to solve the problem?
We can remove `console.error` in [this line](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Url.js#L25) and [this line](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Url.js#L45).
### What alternative solutions have you investigated? (Optional)
None.

**Comment by MariaHCD** [comment] 2023-09-11 10:01
Will take a look and see if I can reproduce this on dev tomorrow

**Comment by MariaHCD** [comment] 2023-09-13 06:34
Not super high priority since this is only on dev and the FAB -> Save the World option has been temporarily removed until we're ready to launch.

Tried to reproduce this on dev today but I think I need some additional setup to be able to call the ReferTeachersUniteVolunteer API command successfully.

**Comment by bfitzexpensify** [comment] 2023-09-13 10:36
OK, so do you think we can close this for the moment and revisit once we're ready for the STW launch @MariaHCD?

**Comment by MariaHCD** [comment] 2023-09-13 10:38
Chatting with @marcochavezf and this might be reproducible with any public room (assuming the error is produced by the link contained in the lurking whisper message). Going to test!

**Comment by MariaHCD** [comment] 2023-09-13 10:44
Okay, reproduced the console error when I created a public room in dev:

<img width="1728" alt="Screenshot 2023-09-13 at 6 42 44 PM" src="https://github.com/Expensify/App/assets/12268372/b4ac91e3-3695-487d-8347-4c1dad0c7b74">

let's fix it!

**Comment by Natnael-Guchima** [comment] 2023-09-13 13:18
Hey Guys, I have reported an issue with similar root cause earlier [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692792825436599?thread_ts=1692792825.436599&cid=C049HHMV9SM). I reported this issue on Aug 23, and this issue was reported on August 30. 

Cc: @bfitzexpensify

**Comment by MariaHCD** [comment] 2023-09-14 01:49
Thanks, @bernhardoj! Agreed that this will likely be fixed by https://github.com/Expensify/App/issues/21932

Going to put this on hold until we have the internal fix.

**Comment by mallenexpensify** [comment] 2023-09-14 09:05
>Hey Guys, I have reported an issue with similar root cause earlier [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692792825436599?thread_ts=1692792825.436599&cid=C049HHMV9SM). I reported the similar issue on Aug 23, and this issue was reported on August 30.

I was assigned to the other issue, @Natnael-Guchima is correct, I've updated the OP to reflect
<img width="592" alt="image" src="https://github.com/Expensify/App/assets/22508304/db697e06-ebb4-494c-91df-698f3b835ade">
vs
<img width="496" alt="image" src="https://github.com/Expensify/App/assets/22508304/54ae9f11-4ec2-4e6f-a184-f1b003c2e967">

Closing [other issue](https://github.com/Expensify/App/issues/27404) since this one has more progress on it.

**Comment by MariaHCD** [comment] 2023-09-18 08:30
Not overdue, still on hold for https://github.com/Expensify/App/issues/21932

**Comment by MariaHCD** [comment] 2023-09-29 09:07
We're still on hold

**Comment by bfitzexpensify** [comment] 2023-10-03 18:38
Still held

**Comment by MariaHCD** [comment] 2023-10-12 13:59
still no progress

**Comment by bfitzexpensify** [comment] 2023-10-19 21:17
https://github.com/Expensify/App/issues/21932 is now resolved. @MariaHCD this was a dev error, can you still reproduce it?

**Comment by MariaHCD** [comment] 2023-10-30 08:53
No longer reproducible on dev when creating a public room:

https://github.com/Expensify/App/assets/12268372/ba331e39-fac9-4137-af4a-eaab9f6df523

@Natnael-Guchima can you retest and check if this is still an issue?

**Comment by MariaHCD** [comment] 2023-11-07 14:24
Bump @Natnael-Guchima, if you can also confirm this is no longer reproducible. Then I believe we can proceed with the payment for reporting.

**Comment by Natnael-Guchima** [comment] 2023-11-07 14:32
It is fixed. Sorry for my late reply @MariaHCD 

<img width="1710" alt="image" src="https://github.com/Expensify/App/assets/57330233/4ebccc27-2cca-4038-9ec9-b797149fe0f7">

A link to video

https://drive.google.com/file/d/1ZKtCQMMf5C2GDvwfxk5VdI4qXLYmQmla/view?usp=sharing

**Comment by MariaHCD** [comment] 2023-11-07 15:11
Great! I believe we can now move forward with the payment for reporting, @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-11-07 15:16
Thanks for confirming @Natnael-Guchima. Offer has been sent for reporting.

**Comment by Natnael-Guchima** [comment] 2023-11-07 15:18
Accepted the offer. Thanks, @bfitzexpensify.

**Comment by bfitzexpensify** [comment] 2023-11-07 15:20
Great. All paid out - let's close this out.

**Comment by kbecciv** [comment] 2023-11-09 22:31
Reopening per comment https://expensify.slack.com/archives/C049HHMV9SM/p1699551645734819

**Comment by MariaHCD** [comment] 2023-11-10 07:48
Ah, okay, there was a BE fix for this as part of this issue. I believe whisper messages that were sent prior to the BE fix will still have invalid URLs. So looks like this console error will show up for those older messages. It shouldn't happen for newer whisper messages sent for public rooms or when referring a teacher. Closing the issue for now, fixing those older messages wouldn't be worth the effort imo.

**Comment by MariaHCD** [comment] 2023-11-14 13:52
@allroundexperts noticed that this is reproducible if any chat message has an invalid URL: https://expensify.slack.com/archives/C049HHMV9SM/p1699915690734349?thread_ts=1699551645.734819&cid=C049HHMV9SM

Updated the title and OP to reflect this and reopening this issue so we can fix it.

**Comment by abdulrahuman5196** [comment] 2023-11-16 16:11
@MariaHCD Is this issue opened for external? If so can we make the issue daily?
Not sure on the path forward from my end

**Comment by MariaHCD** [comment] 2023-11-17 14:36
@abdulrahuman5196 yes, this open for external proposals. I think @allroundexperts might already have an idea in mind based off our slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1699915706610939?thread_ts=1699551645.734819&cid=C049HHMV9SM

**Comment by abdulrahuman5196** [comment] 2023-11-20 15:42
Got it let me check the conversation

**Comment by abdulrahuman5196** [comment] 2023-11-20 15:55
I am not seeing this issue. Am I missing something?


https://github.com/Expensify/App/assets/46707890/61894715-81d8-452b-8ac5-2a3017a74fe6

**Comment by abdulrahuman5196** [comment] 2023-11-24 08:25
@kbecciv / @bfitzexpensify Kindly check on the above question? I am not seeing this issue.

**Comment by MariaHCD** [comment] 2023-11-27 06:16
@abdulrahuman5196 I'm able to see the issue once the report is reopened:

https://github.com/Expensify/App/assets/12268372/390be0b1-2900-4555-bc8d-274244d67a7f

Let me know if you're still not able to see the issue.

**Comment by abdulrahuman5196** [comment] 2023-11-27 09:32
@MariaHCD I am still getting this same response - https://github.com/Expensify/App/issues/26614#issuecomment-1819335038

When I edit the link, i don't get back a url when saving the edit.


But more-ever, even if the said comes true, should we even consider this an issue? Seems to be a super edge case to have a specific url format to repro the issue?

**Comment by MariaHCD** [comment] 2023-11-29 14:14
That's fair. I'm actually not able to reproduce the issue anymore. 

https://github.com/Expensify/App/assets/12268372/d65d1ad5-e7a4-4691-a6cb-a912e1d79c4b

I do agree that it's an edge case so I think we can close for now.

**Closed by MariaHCD** 2023-11-29 14:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
