### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Chat - Page loads infinitely instead of error page when accessing invalid link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20394] opened 2023-06-07 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Scenario 1:
1. Copy IOU link which the logged-in user does not have access to.
2. Paste it on a new tab.

Scenario 2:
1. Go to https://staging.new.expensify.com/
2. Copy a chat link.
3. Paste it on the browser.

Scenario 3:
1. Go to invalid chat link. For example, https://staging.new.expensify.com/r/1234.

## Expected Result:
Scenario 1: User lands on error page because they do not have access to the link.
Scenario 2: User is able to open the chat link.
Scenario 3: User lands on error page because they do not have access to the link.

## Actual Result:
Scenario 1: User lands on the page which loads infinitely instead of error page.
Scenario 2: User is able to open the chat link.
Scenario 3: User lands on the page which loads infinitely instead of error page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes 

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/47761cae-5243-48e1-9c3c-56571c49b35a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686035561587859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164184e82be52ad8b</li>
        <li>Upwork Job ID: 1666509686563983360</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2023-06-07 19:53
> @aldo-expensify Can you please assign me this issue as it is a regression indeed . we should assign @dukenv0307 as well.

For some reason @dukenv0307 doesn't show up in the list to assign

![image](https://github.com/Expensify/App/assets/87341702/a5c33ba6-a59a-4fa4-859b-d30e5cc1b38b)

**Comment by aldo-expensify** [comment] 2023-06-09 16:58
Merged the fix, thanks @dukenv0307 and @fedirjh !

**Comment by twisterdotcom** [comment] 2023-06-14 10:08
Going to take this from April as it's a regression from my https://github.com/Expensify/App/issues/19364

**Comment by twisterdotcom** [comment] 2023-06-21 22:54
Paid this out as a bonus to the linked https://github.com/Expensify/App/issues/19364

**Comment by aldo-expensify** [comment] 2023-07-10 17:34
Reopening since there seem to be a pending payment

**Comment by twisterdotcom** [comment] 2023-07-11 00:09
Sent the offer for this!

**Comment by twisterdotcom** [comment] 2023-07-14 11:46
Paid.

**Closed by twisterdotcom** 2023-07-14 11:46 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
