### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Send invoice - (archived) is not appended to chat and Leave option is shown when WS is deleted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41306] opened 2024-04-30 09:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace.
3. Go to FAB > Send invoice.
4. Send an invoice to any user.
5. Delete the workspace in Step 2.
6. Go to the invoice workspace chat.
7. Click 3-dot menu (might have to revisit the chat for Leave option to show up).

## Expected Result:
In Step 6, the invoice workspace chat should be appended with (archived) when the workspace is deleted.
In Step 7, there should not be a Leave option in the invoice workspace chat.

## Actual Result:
In Step 6, the invoice workspace chat is not appended with (archived) when the workspace is deleted.
In Step 7, there is a Leave option in the invoice workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ad9257a3-7f7d-4c13-b20c-08503892d32a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01399b3e5a52c47027</li>
        <li>Upwork Job ID: 1785276283373862912</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment] 2024-04-30 09:26
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-30 09:26
Production 


https://github.com/Expensify/App/assets/115492554/b9a46381-6536-4f53-82b0-fc793babacc1

**Comment by lakchote** [comment] 2024-04-30 11:53
This issue isn't critical/a blocker because of it's impact and the reproduction steps. It can be handled by external contributors.

**Comment by c3024** [comment] 2024-04-30 12:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
(archived) is not appended to the title of an archived invoice room. `Leave` option appears for an archived room.
### What is the root cause of that problem?
We are overwriting formatted name for archived room here
https://github.com/Expensify/App/blob/e0c12a57c3f96ea1df94479913e0f9a84eab358e/src/libs/ReportUtils.ts#L3118-L3128
because `isInvoiceRoom` check happens later.
`Leave` appears for all archived rooms not just merchant rooms and might be expected behaviour.
### What changes do you think we should make in order to solve the problem?
We move the archived room check below the isInvoiceRoom check.
If we want to remove `Leave` as well we can check for archived room at the beginning here and return false
https://github.com/Expensify/App/blob/e0c12a57c3f96ea1df94479913e0f9a84eab358e/src/libs/ReportUtils.ts#L5468

### What alternative solutions did you explore? (Optional)

**Comment by cristipaval** [comment] 2024-04-30 15:07
Held on https://github.com/Expensify/Expensify/issues/388870

**Comment by cristipaval** [comment] 2024-04-30 15:07
#vip-billpay related cc @danielrvidal

**Comment by danielrvidal** [comment] 2024-04-30 19:54
This looks like good clean up! Going to mark as low though as we don't need it for the release. It will be good to clean it up though!

**Comment by cristipaval** [comment] 2024-04-30 20:40
Hold because it should be fixed once the @madmax330 [PR](https://github.com/Expensify/Auth/pull/10698) gets deployed

**Comment by lschurr** [comment] 2024-05-09 19:22
The PR you mentioned is merged @cristipaval - Is this one fixed now?

**Comment by cristipaval** [comment] 2024-05-09 19:24
HOLD removed. We need to retest and check.

**Comment by rezkiy37** [comment] 2024-05-13 11:54
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by c3024** [comment] 2024-05-13 12:21
There is a [proposal here](https://github.com/Expensify/App/issues/41306#issuecomment-2085190571) that fixes this. It has been here for almost 2 weeks. 😆

**Comment by cristipaval** [comment] 2024-05-13 13:04
I think @rezkiy37 is still appropriate for working on this, given that he worked on the original PRs that implemented the invoice rooms.

**Comment by rezkiy37** [comment] 2024-05-14 08:48
Since I am an author of the original [PR](https://github.com/Expensify/App/pull/40303), I am considering the issue as a regression. I am preparing a [PR](https://github.com/Expensify/App/pull/42085), opening for review today.

**Comment by lschurr** [comment] 2024-06-10 19:25
Not overdue. Payment date is tomorrow.

**Comment by lschurr** [comment] 2024-06-11 16:22
Payment summary:

- Contributor+: $250 @mollfpr requires payment through NewDot Manual Requests
- Contributor: @rezkiy37 does not require payment (Contractor)

**Comment by mollfpr** [comment] 2024-06-11 16:36
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to 
ensure the same bug will not reach production again.

1. Create a workspace.
2. Go to the FAB > Send invoice.
3. Send an invoice to any user.
4. Delete the newly created workspace.
5. Go to the invoice room.
6. The invoice room title should be appended with (archived).
7. Click the 3-dot menu.
8. **_Verify_** that there is no Leave option shown
9. Click on the invoice report.
10. **_Verify_** that the (archived) label appears in the subtitle.
11. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-06-11 18:20
$250 approved for @mollfpr. Re-opening issue for regression test.

**Comment by lschurr** [comment] 2024-06-11 18:29
Ah, missed that, thanks!

**Comment by lschurr** [comment] 2024-06-11 18:30
Submitted request to add QA test. Closing :)

**Closed by lschurr** 2024-06-11 18:30 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
