### ISSUE TITLE
Workspace - New users invited to WS are not displayed in members list but chats are created for them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20961] opened 2023-06-17 11:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open staging.new.expensify.com
2. Go to to Workspace > Members
3. Invite a new user to workspace

## Expected Result:
Newly invited users are present in the Members list immediately after being invited.
Chats in LHN for new users are created.

## Actual Result:
New users are not displayed in the members list after being invited. The workspace chat is displayed in LHN immediately but the user is not displayed in members list right away. If the user navigates back to Workspace settings, a red dot can be seen here: 
![image](https://github.com/Expensify/App/assets/44479856/5a6d024e-53a4-4d7a-97a8-2a60f4af53cf)
This red dot is removed after the user is finally displayed in the members list. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/3498653

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/22c1333e-ed3f-47a2-9805-af7788f7fc42

**Expensify/Expensify Issue URL:**
po
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2023-06-19 14:58
@PauloGasparSv I think the issue is that there's a huge delay on members being displayed on the members list after a user without an existing account is invited. Going to edit the OC a bit as I'm able to reproduce with both public and domain controlled accounts.

**Comment by PauloGasparSv** [comment] 2023-06-19 16:37
> @PauloGasparSv I think the issue is that there's a huge delay on members being displayed on the members list after a user without an existing account is invited. Going to edit the OC a bit as I'm able to reproduce with both public and domain controlled accounts.

Makes sense, I could only replicate this by inviting a non-existing account. I think this problem is known, will test production and investigate!

**Comment by PauloGasparSv** [comment] 2023-06-19 16:50
Btw, when I replicate this in staging there is **1 difference**: The non-existing account I invited is added to the workspace member list.

Other than that everything is the same, the chat is created first then the user shows in the list a bit later + there is an error indicator in the workspace members page.

<img width="1423" alt="image" src="https://github.com/Expensify/App/assets/6564265/56ec5905-0a28-4841-91b9-29d78caeda79">

**Comment by PauloGasparSv** [comment] 2023-06-19 16:53
Still not sure but this may be related to https://github.com/Expensify/App/issues/20211 and the changes in https://github.com/Expensify/App/pull/20482 and https://github.com/Expensify/App/pull/20397

still investigating

**Comment by PauloGasparSv** [comment] 2023-06-19 18:21
Oh ok, maybe this is causing the error

![image](https://github.com/Expensify/App/assets/6564265/a51b5bf5-9e18-4cf7-8d24-16dab6f5beda)

The `type` field is being sent as `receiptUpload` (mapped [here](https://github.com/Expensify/Auth/blob/main/auth/lib/AuthToken.cpp#L26)) when I invite people to the Workspace.  I think maybe [this line](https://github.com/Expensify/Auth/blob/main/auth/command/GetRestrictedAuthToken.cpp#L114) is not returning an `accountID` and [this logic](https://github.com/Expensify/Auth/blob/main/auth/command/GetRestrictedAuthToken.cpp#L124-L130) is not populating that because of the `receiptUpload` type.

Since I can't replicate in prod or locally I'm comparing what the logic does in these diff environments.

**Comment by PauloGasparSv** [comment] 2023-06-19 18:48
Looked a bit more at the logic and I actually think it's ok for the type to be that, that type `chat` was being called specifically for concierge and not the new user! Sorry for the confusion.

Looks like the account wasn't created in time to add it to the workspace. I'm investigating where the account creation happens in that request.

**Comment by PauloGasparSv** [comment] 2023-06-19 19:11
I think I'm getting stuck here but while I was testing the problem stopped happening on staging web:

https://github.com/Expensify/App/assets/6564265/0d9d23be-77c8-4adb-ae30-1126d520adb2

I can see no errors or RBR now and the user is added to the members list correctly! This may have been fixed by somethig that was CP'd so I'll check for that.
There is one problem left thought, the member is only added after the request finishes running. I don't think that's worth a blocker thought but we can continue investigating that here.

In the meantime, @kbecciv could you please re-test this and check if it still happens to you?

**Comment by PauloGasparSv** [comment] 2023-06-19 19:15
Hid the above comment by mistake!


I think I'm getting stuck here but while I was testing the problem stopped happening on staging web:

https://github.com/Expensify/App/assets/6564265/0d9d23be-77c8-4adb-ae30-1126d520adb2

I can see no errors or RBR now and the user is added to the members list correctly! This may have been fixed by somethig that was CP'd so I'll check for that.
There is one problem left thought, the member is only added after the request finishes running. I don't think that's worth a blocker thought but we can continue investigating that here.

In the meantime, @kbecciv could you please re-test this and check if it still happens to you?

**Comment by chiragsalian** [comment] 2023-06-19 20:13
Not a blocker, looks like optimistic and failure data are just not being set properly for this flow. This shouldn't block us from deploy.

**Comment by PauloGasparSv** [comment] 2023-06-19 20:19
I'll work on this during the week and add that optimistic data, changing this to a daily.

**Comment by PauloGasparSv** [comment] 2023-06-21 22:39
Ok, I think I found where the optimisticData is not set here. This only happens to new users, I think it's because we don't know the correct `accountID` for that user + don't have their info in `addMembersToWorkspace`. 

Still need some more time on this, will work on it later down the week.

**Comment by PauloGasparSv** [comment] 2023-06-22 23:42
No updates here today, will get back to this asap

**Comment by PauloGasparSv** [comment] 2023-06-30 15:07
> Ok, I think I found where the optimisticData is not set here. This only happens to new users, I think it's because we don't know the correct accountID for that user + don't have their info in addMembersToWorkspace.

Back to this! 

No idea how to deal with this error, will double-check if that is the case. I also need to test what happens if you are offline and do this

**Comment by PauloGasparSv** [comment] 2023-07-03 20:43
Investigated this further today!

I still can't replicate this locally but it still happens in staging if:
1. You open the Workspace members list
2. Go offline
3. Invite a non-existing account
4. Go back online

[Logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%227e11272ef93c4ecb-GRU%22%20AND%20timestamp%3A%5B2023-07-03T00%3A00%20TO%202023-07-04T23%3A59%5D) for that attempt indicate that:

1. [This](https://github.com/Expensify/Web-Expensify/blob/2cc0ca8861c5d19ae5e3b09049400a78f321fe5c/lib/PolicyAPI.php#L1079) empty `isClosed` check in Web-E was successful and the error is coming from the `AuthTokenManager::getEmailToken`
2. We have 2 instances of `request authtoken type=` in those logs, first using `type=chat` then `type= receiptUpload` when it breaks
3. This may have to do with the `isClosed` check in Web-E or Auth

Still need to investigate this further!

**Comment by Christinadobrzyn** [comment] 2023-07-06 20:57
Hi @PauloGasparSv - do you think [this](https://github.com/Expensify/App/issues/22359) is related to this issue? seems similar but not 100% sure?

**Comment by PauloGasparSv** [comment] 2023-07-09 18:47
> Hi @PauloGasparSv - do you think https://github.com/Expensify/App/issues/22359 is related to this issue? seems similar but not 100% sure?

Will get back to you on that ASAP (will try doing so on Monday)

**Comment by PauloGasparSv** [comment] 2023-07-11 00:44
> Hi @PauloGasparSv - do you think https://github.com/Expensify/App/issues/22359 is related to this issue? seems similar but not 100% sure?

Hey @Christinadobrzyn just checked and replicated https://github.com/Expensify/App/issues/22359 and it really isn't related to this! 

> I can see no errors or RBR now and the user is added to the members list correctly! This may have been fixed by somethig that was CP'd so I'll check for that.

Part of the issue here was pretty similar but then it stopped happening. What I was investigating was the cause of the error thought and not the RBR not clearing

> There is one problem left thought, the member is only added after the request finishes running. I don't think that's worth a blocker thought but we can continue investigating that here.

Now I'm focused at this!

**Comment by PauloGasparSv** [comment] 2023-07-15 12:37
Hey @Christinadobrzyn I'm going OOO for 2 weeks (starting on July 17th, back on July 31st) so I won't be updating this issue until then.

Please feel free to re-assign this to another engineer!

**Comment by PauloGasparSv** [comment] 2023-07-31 18:32
I'm back from OOO, will pick this back up ASAP

**Comment by PauloGasparSv** [comment] 2023-08-02 19:50
Picked this back up right now!

I can't reproduce this locally or in staging anymore (tested on Web chrome and Safari desktop) so I believe we fixed this in another P.R. these past few weeks.

Closing this!

**Closed by PauloGasparSv** 2023-08-02 19:50 UTC
Labels: Engineering, Weekly
