### ISSUE TITLE
Changing currency closes the request Modal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26260] opened 2023-08-29 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace chat.
2. Open Request money page from + button.
3. On the amount page, click currency.
4. Notice that search is not auto focused.
5. Find a currency and select it.
6. Observe that whole page is closed.
## Expected Result: 
User should be able to select the currency and search field on currency selection page should be auto-focused,
## Actual Result: 
Selecting currency on currency selection page, closes the whole page.
Also, the search field is not auto-focused on currency selection page.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/858e8eee-9e32-47b8-96f8-019b29f42b49

https://github.com/Expensify/App/assets/43996225/81e9b56b-5428-416c-931f-fde70cc2b67d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692371427006799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-08-31 12:10
Confirmed.

**Comment by garrettmknight** [comment] 2023-08-31 12:52
I was able to reproduce - check the video to see if there's a step that looks like you're missing it.

**Comment by payal-lathidadiya** [comment] 2023-08-31 15:07
> @payal-lathidadiya Your proposal neither explains the root cause nor the solution on how it solves it.
> 
> > The search field is not auto-focused on currency selection page.
> 
> This is not expected behaviour.

Ops! understood. 
Thanks @parasharrajat for your review.

Something is really weird while debugging route navigation stacks. At times, I could find it working correctly at intermediate steps and proposed changes. 😬 

This is definitely not the correct RCA.

I'll dig into further analysis to get more insights on navigation updates.

**Comment by mountiny** [comment] 2023-08-31 20:46
dupe of https://github.com/Expensify/App/issues/25626

**Closed by mountiny** 2023-08-31 20:46 UTC
Labels: Daily, Bug
