### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] mWeb - Search icon is partially visible in help page on mobile

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26164] opened 2023-08-29 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to help web page ([help.expensify.com](http://help.expensify.com/))
2. Click on search icon to go to search page
3. Notice that search icon is partially visible

## Expected Result:
Search icon should appear normal

## Actual Result:
Search icon is partially visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v.1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0beebca4-91a2-4623-819c-c266a3219302

![Screenshot_2023-08-22-11-51-14-329_com android chrome](https://github.com/Expensify/App/assets/115492554/e67e0677-afce-4b31-9b4a-fb50dfd72280)

https://github.com/Expensify/App/assets/115492554/4bcc5f11-cc0a-41fc-9578-adc3f4e402fa

**Expensify/Expensify Issue URL:**

**Issue reported by:** @alitoshmatov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692687046963399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bd40a33e016375b</li>
        <li>Upwork Job ID: 1697230740293746688</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-09-04 12:22
Hmm - can anyone else reproduce this?

**Comment by situchan** [comment] 2023-09-04 14:19
> Hmm - can anyone else reproduce this?

I reproduced this on android chrome

**Comment by situchan** [comment] 2023-09-04 14:22
I reproduced on web as well

chrome: (not reproducible from 2nd visit until clear cache)

https://github.com/Expensify/App/assets/108292595/c03cde31-d73d-4e86-ab3f-85acc5ad0403




safari: (wrongly positioned)

https://github.com/Expensify/App/assets/108292595/b2db1fab-c2f8-44d2-b382-74442168bac8

**Comment by situchan** [comment] 2023-09-04 14:24
@ginsuma issue happens on web as well, not only mWeb

No satisfactory proposals yet

**Comment by greg-schroeder** [comment] 2023-09-08 06:17
Pending proposals

**Comment by greg-schroeder** [comment] 2023-09-11 13:51
Updated price to $500

**Comment by b4s36t4** [comment] 2023-09-11 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Search icon is partially visible in help page on mobile
### What is the root cause of that problem?

We're using custom google search elements inside docs which is handled by google's script. Inside the sidebar search input google have icons & colors.
We have customized it using CSS. 

The same way we did is replacing the `search` icon used by google with our `Expensify`'s `search` icon here https://github.com/Expensify/App/blob/5f9bb2e1d901eb6dc0110d8214e679d4d2aa6822/docs/_sass/_search-bar.scss#L198 in this declaration. 

Because of this we have a specific size icon which is causing the issue.

And 2nd thing is here we're modifying the size of svg which is causing break in search icon.

https://github.com/Expensify/App/blob/5f9bb2e1d901eb6dc0110d8214e679d4d2aa6822/docs/assets/js/main.js#L119

Recently we added google search support, I think because of that we had to do some tweaks to use our `search` icon.

### What changes do you think we should make in order to solve the problem?
We can simply remove the media query related changes, we can just simply put one width and height & viewbox. That would solve the issue.



### What alternative solutions did you explore? (Optional)
NA

> Web, well I'm not sure why web also caused this issue, 90% sure it's because of media query related issue itself. But doing the above change would 
> solve the cut-off from icon


<img width="642" alt="Screenshot 2023-09-11 at 10 09 43 PM" src="https://github.com/Expensify/App/assets/59088937/542a0425-aca3-4db8-a4cb-57d1e2c7ded6">


@situchan Requesting a review.

**Comment by greg-schroeder** [comment] 2023-09-14 14:42
Awaiting proposal review @situchan

**Comment by situchan** [comment] 2023-09-18 10:01
> 'm not sure why web also caused this issue, 90% sure it's because of media query related issue itself. But doing the above change would solve the cut-off from icon

@b4s36t4 thanks for the proposal. can you please blame git and find out when and why (to fix what?) that code was added?

**Comment by b4s36t4** [comment] 2023-09-18 10:20
@situchan This is the PR caused the issue https://github.com/Expensify/App/pull/24299

**Comment by b4s36t4** [comment] 2023-09-18 10:23
We've added google search support for docs in which the search bar was added by google's script itself but to have our custom styles we have added this css configuration but they forget to add responsive icon (which doesn't needed though). I think PR itself explains everything needed.

**Comment by situchan** [comment] 2023-09-22 10:35
reviewing

**Comment by greg-schroeder** [comment] 2023-09-25 07:18
Looks like we're still reviewing proposals

**Comment by b4s36t4** [comment] 2023-09-26 13:25
> firefox

I don't think this is needed as it's not one of our supported platform. Also you're suggesting for me? or everything :)

@situchan

**Comment by greg-schroeder** [comment] 2023-10-02 02:49
I think he's saying firefox is optional. And yes, @b4s36t4, your proposal is the one being considered here

**Comment by greg-schroeder** [comment] 2023-10-04 16:00
Were we able to test cross platform?

**Comment by b4s36t4** [comment] 2023-10-04 17:29
@situchan @greg-schroeder I think my solution is working fine.

But there's an issue the icons are different for Safari and chrome. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#browser_compatibility Except this everything is good.

**Comment by situchan** [comment] 2023-10-04 17:34
@b4s36t4 I think we can make safari icon same as google icon. They are already same on main page
<img width="809" alt="Screenshot 2023-10-04 at 11 32 49 PM" src="https://github.com/Expensify/App/assets/108292595/df709306-87ff-4601-9a9a-0568b4f933b7">
<img width="809" alt="Screenshot 2023-10-04 at 11 32 59 PM" src="https://github.com/Expensify/App/assets/108292595/6dfeb12f-47d5-451a-a0db-a2e1ecb6ce5c">

**Comment by b4s36t4** [comment] 2023-10-04 17:48
```js
function updateGoogleSearchIcon() {
    const node = document.querySelector('.gsc-search-button.gsc-search-button-v2 svg path');
    node.setAttribute(
        'd',
        'M8 1c3.9 0 7 3.1 7 7 0 1.4-.4 2.7-1.1 3.8l5.2 5.2c.6.6.6 1.5 0 2.1-.6.6-1.5.6-2.1 0l-5.2-5.2C10.7 14.6 9.4 15 8 15c-3.9 0-7-3.1-7-7s3.1-7 7-7zm0 3c2.2 0 4 1.8 4 4s-1.8 4-4 4-4-1.8-4-4 1.8-4 4-4z',
    );
}
```

This change is required to update the icon. 

cc: @situchan

**Comment by situchan** [comment] 2023-10-04 17:54
@b4s36t4 can you share screenshots on web / safari / mChrome / mSafari?

**Comment by b4s36t4** [comment] 2023-10-04 18:01
<img width="1429" alt="Screenshot 2023-10-04 at 11 30 24 PM" src="https://github.com/Expensify/App/assets/59088937/05bc4c58-17af-49ef-9cf9-ef1afa571980">
<img width="500" alt="Screenshot 2023-10-04 at 11 30 37 PM" src="https://github.com/Expensify/App/assets/59088937/754e9d92-40fb-4b8b-a4f2-999fd0c820ed">
<img width="1726" alt="Screenshot 2023-10-04 at 11 30 54 PM" src="https://github.com/Expensify/App/assets/59088937/a4f47bdf-898b-4947-9b74-89104df69628">
<img width="450" alt="Screenshot 2023-10-04 at 11 31 36 PM" src="https://github.com/Expensify/App/assets/59088937/cf873247-f4e7-4154-97f3-c46f3dd9b8e4">

**Comment by b4s36t4** [comment] 2023-10-04 18:01
@situchan Shared!

**Comment by situchan** [comment] 2023-10-10 12:16
@b4s36t4 can you share test branch? I wanna test myself before final approval

**Comment by greg-schroeder** [comment] 2023-10-13 19:13
Looks like we're still working here

**Comment by b4s36t4** [comment] 2023-10-13 19:29
@situchan here's the branch https://github.com/b4s36t4/App/tree/fix/docs-search-icon

**Comment by b4s36t4** [comment] 2023-10-13 19:29
Sorry for the delay.

**Comment by greg-schroeder** [comment] 2023-10-16 14:45
No problem - you're up @situchan!

**Comment by situchan** [comment] 2023-10-20 13:04
I will give feedback on Monday.

**Comment by greg-schroeder** [comment] 2023-10-23 10:18
Not overdue, waiting for proposal feedback today

**Comment by situchan** [comment] 2023-10-24 07:09
@b4s36t4's [proposal](https://github.com/Expensify/App/issues/26164#issuecomment-1714233607) combined with https://github.com/Expensify/App/issues/26164#issuecomment-1747370589 looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by srikarparsi** [comment] 2023-10-25 21:34
@b4s36t4's proposal looks good to me as well. I believe the upwork automation didn't kick in because the issue briefly went internal but please ping @situchan and  myself once the PR is ready.

**Comment by b4s36t4** [comment] 2023-10-30 12:55
@situchan @srikarparsi Sorry for the delay. Please checkout the PR here #30577

**Comment by greg-schroeder** [comment] 2023-11-27 21:04
All paid, job closed. 

@situchan can you complete the checklist so we can close this? Thanks!

**Comment by situchan** [comment] 2023-11-27 21:07
No need checklist as it's helpDot issue

**Comment by greg-schroeder** [comment] 2023-11-27 21:12
oh, word. okay then!

**Closed by greg-schroeder** 2023-11-27 21:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by alitoshmatov** [comment] 2023-11-29 08:39
@greg-schroeder You made a mistake by paying me 250$, I was a reporter in this issue and I should have been payed 50$

<img width="988" alt="Screenshot 2023-11-29 at 13 38 34" src="https://github.com/Expensify/App/assets/59907218/b6e9b1b9-7604-47b9-bf71-33c5be06be1f">

**Comment by situchan** [comment] 2023-11-29 09:07
@alitoshmatov I think you're eligible for previous bonus amount. I see that you reported on slack before announcement

**Comment by alitoshmatov** [comment] 2023-11-29 09:48
Understood. Thank you
