### ISSUE TITLE
[pay bug reporting bonus & close] Android - Double quotes displayed after 3 dots in notification for invite message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27663] opened 2023-09-18 11:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A on android app
2. Open the app in any other device and login with user B
3. Minimize or close android app
4. From user B, invite user A in any workspace
5. Observe in notification on user A android device that invite message has double quotes after 3 dots

## Expected Result:
 App should display 3 dots in the end of notification for large messages

## Actual Result:
App displays double quotes after 3 dots in the end of notification for workspace invite message

## Workaround:
Uknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/acbcb095-a15d-47df-ac58-3628c91d8fcc

https://github.com/Expensify/App/assets/93399543/977e6e32-2561-4c4f-bba6-a93bf3012bb0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1694364092518829
  
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017598e4fcd86f03ec</li>
        <li>Upwork Job ID: 1703737109181304832</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-09-19 02:54
Likely a dupe (or same root cause) as this issue: https://github.com/Expensify/App/issues/25982

**Comment by Julesssss** [comment] 2023-09-19 09:10
Slightly different issue to #25982. But it's almost certainly due to a large notification payload being stripped away due to size.

**Comment by Julesssss** [comment] 2023-09-19 10:24
Possibly fixed with this internal issue: https://github.com/Expensify/Web-Expensify/pull/38908

**Comment by Julesssss** [comment] 2023-09-27 02:32
I fixed this [here](https://github.com/Expensify/Web-Expensify/pull/38908). Please pay out the reported bonus now as we don't need to wait for the regression dudection. 

![Screenshot_20230927-103021](https://github.com/Expensify/App/assets/10736861/1992ca23-adcb-45d4-88d9-8616cbc41a27)

**Comment by Julesssss** [comment] 2023-09-27 02:32
Please close after the report bonus is paid

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:15
I invited @dhanashree-sawant to the job in upwork

**Comment by michaelhaxhiu** [comment] 2023-09-28 14:24
done!

**Closed by michaelhaxhiu** 2023-09-28 14:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
