### ISSUE TITLE
Creating a report field with the same name in lowercase will replace the report field name that is in uppercase.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49101] opened 2024-09-12 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726145655221189

## Action Performed:
1. Open App Go to Settings
2. Click on Workspaces -> Select any workspace
3. Go to More Features -> Enable Report Fields
4. Go to Report Fields
5. Add a new field named 'abc' (lowercase) and select any Type
6. Add a new field named 'ABC' (uppercase) and select any Type
7. Notice that the older field named 'abc' is replaced by 'ABC'.
## Expected Result:
Either the field names should be created separately, or we should prevent creating the same field name in different cases
## Actual Result:
An uppercase field name (ABC) will be replaced by the corresponding lowercase field name (abc)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e9163947-6180-45b2-af3b-1437f1d619ec

https://github.com/user-attachments/assets/7fe6bdb4-ca70-4209-a534-ac4c9d851864

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ChavdaSachin** [comment] 2024-09-12 17:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Creating a report field with the same name in lowercase will replace the report field name that is in uppercase.

### What is the root cause of that problem?
- When generating `fieldID` and `fieldKey` for Onyx Data [here](https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/libs/actions/Policy/ReportField.ts#L161)  we make use of `generateFieldID` 
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/libs/WorkspaceReportFieldUtils.ts#L66-L68
- And `generateFieldID` capitalize the name so `fieldKey` generated for `Abc` and `ABC` will be equivalent, hence replaces the old key on onyx merge.

### What changes do you think we should make in order to solve the problem?
- Change validation case such that user can’t create a report field when similar key exist in different case.
- To do so, when validating for existing value - compare existing values with new value in UpperCase .
```js
  } else if (Object.values(policy?.fieldList ?? {}).some((reportField) => reportField.name.toUpperCase() === name.toUpperCase())) {
```
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/pages/workspace/reportFields/CreateReportFieldsPage.tsx#L69

### What alternative solutions did you explore? (Optional)
- Alternatively we could remove `toUpperCase()` from `generateFieldID`
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/libs/WorkspaceReportFieldUtils.ts#L66-L68
- So now both `ABC` and `Abc` will generate different `fieldKey` and would not be merged together on Onyx Merge event.
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment] 2024-09-13 09:34
## Proposal 
[Updated](https://github.com/Expensify/App/issues/49101#issuecomment-2346823497) added additional changes required for alternate solution.

**Comment by VictoriaExpensify** [comment] 2024-09-16 03:11
I think this is expected behaviour as the report field names are essentially the same. I can't really think of a use-case where customers would need the same report field name but in lower-case and upper-case. 

Let me get some input on this

**Comment by ChavdaSachin** [comment] 2024-09-16 04:22
Then we should extend the validation to warn the user about this so they do not accidentally replace their old field. See [proposal](https://github.com/Expensify/App/issues/49101#issuecomment-2346823497)

**Comment by VictoriaExpensify** [comment] 2024-09-19 04:48
I don't think we need to do anything for this at the moment, I'm going to close it out.

**Closed by VictoriaExpensify** 2024-09-19 04:48 UTC
Labels: Daily, Overdue, Bug
