### ISSUE TITLE
[$1000] Login - Console error when navigating to the homepage

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24084] opened 2023-08-03 00:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the developers tools
2. Go to https://staging.new.expensify.com/

## Expected Result:
No console errors are shown

## Actual Result:
There is a console error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/70f227c8-01df-4e79-8bad-68dfa0921d77

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01563fccdeafd607d3</li>
        <li>Upwork Job ID: 1689311246929960960</li>
        <li>Last Price Increase: 2023-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>ahmdshrif | Contributor | 26387852</li>
</ul></li>
    </ul>
</details>

**Comment by rushatgabhane** [comment] 2023-08-03 05:50
related issue https://github.com/Expensify/App/issues/15244

**Comment by JmillsExpensify** [comment] 2023-08-09 16:22
Triaging.

**Comment by rushatgabhane** [comment] 2023-08-09 16:32
@JmillsExpensify we should add to the tracking issue i referenced https://github.com/Expensify/App/issues/15244

**Comment by JmillsExpensify** [comment] 2023-08-10 04:04
Ah cool, thanks for the clarification. I'll add it there and keep this one open for proposals.

**Comment by nileshahir286** [comment] 2023-08-10 04:41
### **Contributor details**
Your Expensify account email: nileshahir286@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0126f3665fe23ff297

### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'

![image](https://github.com/Expensify/App/assets/6794076/d9ba8a11-8d18-47a0-853f-61209c0fff4c)


**### What is the root cause of that problem?**
This error is related to Content Security Policy blocking. The external url/link given is blocked by CSP.
If the blocked resource is an inline resource, the inline resource should be moved to it's own file.

There are two ways to resolved this issue. 
**First**
If the resource(url) is external then we have to download that external file content to save it local file and changed the reference point to local file instead of external url.

**Second** 
If the blocked resource is an external file, it should be added to the policy. For example above, if we had the error message Refused to load the script 'https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://*.sardine.ai/ https://appleid.cdn-apple.com' because it violates the following directive 'script-src', we need to add " https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://*.sardine.ai/ https://appleid.cdn-apple.com" to the "script-src" directive of the policy. 

Like this ways

script-src 'self' https://polyfill.io;
style-src 'self' https://cdn.plaid.com;
style-src 'self' https://assets.onfido.com;


**### What alternative solutions did you explore? (Optional)**
I have provided both solutions above.

**Comment by lanitochka17** [comment] 2023-08-16 17:16
Issue is not reproducible with Build 1.3.54-11


https://github.com/Expensify/App/assets/78819774/60b03032-eb1b-4062-83e2-0cbd08fe5da2

**Comment by nileshahir286** [comment] 2023-08-28 10:00
Hi @MelvinBot ,
Assign it to me. I will do it.
Thanks

**Comment by mananjadhav** [comment] 2023-08-29 06:56
Okay I am able to reproduce this on staging incognito sometimes. I tried but locally I couldn't. Nevertheless, @ahmdshrif's proposal looks good to me.

Also let's add the onFido styling changes as well.

🎀 👀 🎀 C+ reviewed.

**Comment by nileshahir286** [comment] 2023-08-31 11:32
Assign it to me. I will resolve it by tomorrow.
Thanks

**Comment by Julesssss** [comment] 2023-08-31 12:14
We only just [assigned](https://github.com/Expensify/App/issues/24084#issuecomment-1697162431) this issue (2 days ago)

**Comment by mananjadhav** [comment] 2023-08-31 12:18
@nileshahir286 Also check our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to post proposals and understanding the hiring process for the issues.

**Comment by nileshahir286** [comment] 2023-08-31 12:20
I have already checked and I have submit proposal on dated 10th Aug 2023.

**Comment by nileshahir286** [comment] 2023-08-31 12:20
> ### **Contributor details**
> Your Expensify account email: [nileshahir286@gmail.com](mailto:nileshahir286@gmail.com) Upwork Profile Link: https://www.upwork.com/freelancers/~0126f3665fe23ff297
> 
> ### **Proposal**
> ### **Please re-state the problem that we are trying to solve in this issue.**
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'
> 
> ![image](https://user-images.githubusercontent.com/6794076/259623458-d9ba8a11-8d18-47a0-853f-61209c0fff4c.png)
> 
> **### What is the root cause of that problem?** This error is related to Content Security Policy blocking. The external url/link given is blocked by CSP. If the blocked resource is an inline resource, the inline resource should be moved to it's own file.
> 
> There are two ways to resolved this issue. **First** If the resource(url) is external then we have to download that external file content to save it local file and changed the reference point to local file instead of external url.
> 
> **Second** If the blocked resource is an external file, it should be added to the policy. For example above, if we had the error message Refused to load the script 'https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://_.sardine.ai/ https://appleid.cdn-apple.com' because it violates the following directive 'script-src', we need to add " https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://_.sardine.ai/ https://appleid.cdn-apple.com" to the "script-src" directive of the policy.
> 
> Like this ways
> 
> script-src 'self' https://polyfill.io; style-src 'self' https://cdn.plaid.com; style-src 'self' https://assets.onfido.com;
> 
> **### What alternative solutions did you explore? (Optional)** I have provided both solutions above.

Here it it

**Comment by mananjadhav** [comment] 2023-08-31 12:21
Yeah from the given proposals we've assigned one of them.

**Comment by mananjadhav** [comment] 2023-09-24 14:51
@ahmdshrif What's the latest on this?

**Comment by mananjadhav** [comment] 2023-10-02 14:15
> my solution will not work since there is a code override this CSP from the server side and also there is a script inject form server side which need not be inline.

@Julesssss Can we confirm this ? or should be open this for the agency? I am not sure if there exists a solution that we can do on the App.

> I am not sure if my work here will be rewarded or not but it takes effort from me to get this conclusion

@ahmdshrif I'll let @Julesssss @JmillsExpensify decide on this one.

**Comment by Julesssss** [comment] 2023-10-02 14:33
Hey @ahmdshrif. I'm a bit lost here, but is this something we could handle in the backend to make your solution work?

**Comment by JmillsExpensify** [comment] 2023-10-16 15:45
Still working through the solution details.

**Comment by JmillsExpensify** [comment] 2023-10-24 18:05
Same place as last comment.

**Comment by JmillsExpensify** [comment] 2023-11-24 17:05
@Julesssss are we going to assign someone for the backend?

**Comment by JmillsExpensify** [comment] 2023-11-29 00:03
All good. This is a monthly so not really a priority.

**Comment by Julesssss** [comment] 2023-12-21 15:29
I think we should close... Nobody will be working on this.

Reopen if anyone dissagrees

**Closed by Julesssss** 2023-12-21 15:29 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug

**Comment by mananjadhav** [comment] 2023-12-21 16:15
@Julesssss @JmillsExpensify I think we should consider some amount of payout for me and @ahmdshrif. 

We spent time on the solution, working through the PR and identifying it’s the backend issue.  

what do you folks think?

**Comment by Julesssss** [comment] 2024-01-04 09:48
I agree, not sure how much is a reasonable amount though. Perhaps 250 each?

What do you think @JmillsExpensify ?

**Comment by mananjadhav** [comment] 2024-01-04 16:03
I think it should be $500 atleast for @ahmdshrif.

**Comment by mananjadhav** [comment] 2024-01-04 16:30
Ohh Yes I totally forgot about the PR raised.

**Comment by Julesssss** [comment] 2024-01-09 14:43
I think this seems reasonable in that case: 
- @mananjadhav $250
- @ahmdshrif $750

@JmillsExpensify please review and pay out if you agree, thanks

**Comment by JmillsExpensify** [comment] 2024-01-14 08:46
That sounds reasonable to me. 

**Payment summary**
 - Issue reporter: QA
 - Contributor: @ahmdshrif $750
 - Contributor+: @mananjadhav $250

**Comment by JmillsExpensify** [comment] 2024-01-14 08:47
$250 payment approved for @mananjadhav based on comment above.

**Comment by JmillsExpensify** [comment] 2024-01-14 08:49
Offer sent to Contributor via Upwork.
