### ISSUE TITLE
[HOLD for payment 2024-04-09] [Simplified Collect][Workflows] Bank account info still displayed in Make or track payments after disconnecting

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38200] opened 2024-03-13 05:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
precondition: user created a paid policy in OD and added a bank account
1. Go to https://staging.new.expensify.com/
and log in
2. Select the paid policy workspace in the workspace switcher > Settings
3. Click on Workflow
4. Enable Make or track payments toggle
5. Select Bank account
6. Click on the Bank account option > Disconnect
## Expected Result:
The bank account information disappears, and "Connect bank account" is displayed

## Actual Result:
The bank account information is still displayed even after refreshing the page. Also, after disconnecting the bank account, toggling off/on the "Make or track payments" option, and clicking on bank account the disconnected bank account shows up.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/632be4d0-8d5f-4425-8edf-11cd7c2b9ff7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2024-03-13 05:48
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-03-13 05:50
We think this bug might be related to #wave-collect - Release  cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-03-13 14:41
This is related to the workflows project, yeah. CC: @lakchote

**Comment by luacmartins** [comment] 2024-03-13 15:15
cc @ishpaul777 since you worked on the implementation of this feature

**Comment by luacmartins** [comment] 2024-03-13 17:29
Oh we might actually handle this as part of https://github.com/Expensify/App/pull/37680, when we clean up the current VBBA keys and use the new `reimbursementAccount<policyID>` format. @nkuoch could you please confirm if changing [resetFreePlanBankAccount](https://github.com/Expensify/App/blob/main/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.js#L32-L40) to use `${ONYXKEYS.REIMBURSEMENT_ACCOUNT}${policyID}` instead of `ONYXKEYS.REIMBURSEMENT_ACCOUNT` is currently in that issue's scope?

**Comment by nkuoch** [comment] 2024-03-14 09:55
Let me take it over. I've actually decided not to use `${ONYXKEYS.REIMBURSEMENT_ACCOUNT}${policyID}` anymore. I'll give a better update in a bit.

**Comment by bfitzexpensify** [comment] 2024-04-09 15:01
@nkuoch mind taking a look at https://github.com/Expensify/App/issues/39439?

**Comment by bfitzexpensify** [comment] 2024-04-11 12:48
Offer sent @getusha

**Comment by bfitzexpensify** [comment] 2024-04-16 19:50
Payment complete. I don't think a regression test is necessary here. Let's close this out.

**Closed by bfitzexpensify** 2024-04-16 19:50 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
