### ISSUE TITLE
[$1000] Android - Task - App crashes when part of long link is used as title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22554] opened 2023-07-10 13:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21941
## Action Performed:
1. Launch New Expensify app
2. Go to + > Assign task
3. Enter the following as title
attachments/4958013852073029329/w_b699e9f99322181578af40503e25342bab52afb0.jpg?encryptedAuthToken=yGmeJ3lS696v3R71E3qM2R3%2Bbz3xDitFkHi01XVnxxAjNGjY6EyPZpst6GmjnUHaMIpq%2FPNaLHQSroea%2FS1WCjbZIQ%2BtaqO2Q%2FozByT%2Fr3G0Jq5XzrMJNbtDs6I%2F6WihHclCH4cOksOS8hBbvKvDIVJhRLI0z1K%2BwUtTkDYCdYkAHCCrQF7S7BCssB0kaM7O6DVbOQsLphIc3aouhyleQZTjufyhHux7O7ZgO925xTdWqa7NNePXTRZwPwwJF%2BmWOTktaaf1wLkHv7%2BqcEXtHsaxZKGuSYeKD3soQsFVToTUwI4rz%2F6yyipX%2F5%2F9doTqBMc5mOvW51GISWcd1dnNCZVNB4rXirsVgHahWV3IzaPnxPa%2BPeJLqyyIvbFLseB14CxHkM1PmNWIGL%2F%2FsyLF%2FA71%2FzvFgc3FN1SEvYerspiMSCTpToZPI2iqrIF4B%2FaH4Qv6%2B929Ym7kNVpxECzp2zgy0OgIKEFCrXhlR%2B%2FOcVXBKilJ89pk9Zm0lS%2F9R9iepcuRDl8OaklXTJpj45LAvF5L8F4NqcHfa25aih4B17l%2BecyFL5LeDsFr%2Bg%2FbwcR2wAgyyvjsnW3xuV8Jt%2BbUrcYDL2sQkivvRKZP7NGeS5jYyxyJ0zNrGvDlB3756yyuU05%2BnrgwKYmCq8ApLoA%2F9IrgxYg1iqJ5OmgiMXCUj5dnzwqRZ1JqEeUnmEk3giS3xL2zDozVJ4pCyeeFNlMWjP9K%2FXDBp7%2FkTy223YFz2fKqGH%2BzZIiHIArNvlm%2Fp74fxZHCtqpNTV5NNY7Kd4SbtSYmVJ2XemF%2BTcwL46ioRC6pqew0WWK4zjUIzUvkrd9jCWT0tsLabZ22hWDJL6DXNrUh631zh3qhCdys3K3bq3m%2BX1k%2Fc34b2a3VhkbT4tZ5k29cgBocZPD9RkNsMMJhvROzlH7ZtRmP2a1ccGsTSjZPF1A6Hxap6Tjku8WigYtAGHRRZO%2FSJtT1JTuCtGi4sh6j8kSo621keosFBQci6BNCtM19SSFj%2BcYzrcLqnyZG
4. Enter [dwihihdhduhwhhdwhdwihiudwhdwihihdhduhwhhdwhdwihiudwhdwihihdhd@gmail.com](mailto:dwihihdhduhwhhdwhdwihiudwhdwihihdhduhwhhdwhdwihiudwhdwihihdhd@gmail.com)
for assignee
5. Create the task
6. Repeat Step 2 to 5 with long random text as title

## Expected Result:
Task is created without issue

## Actual Result:
Step 5 - Task is not created. App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6d6633d1-11af-4b31-ba44-d8d3a5dbe96f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f538b2c63a1c7040</li>
        <li>Upwork Job ID: 1678802099600863232</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment] 2023-07-11 16:22
Wow, what a super edge case. Going to make this external, but it's gonna be weekly.

**Comment by situchan** [comment] 2023-07-11 16:30
Same root cause as https://github.com/Expensify/App/issues/21266

**Comment by mkhan9047** [comment] 2023-07-11 18:14
My approach will be like below: 

Implement Text Chunking: Modify the buildOptimisticAddCommentReportAction function to break down the input text into smaller chunks before parsing. This would be done by splitting the text into segments that fall within the regex stack limit.

Adjust Parsing Approach: Instead of parsing the entire text string in one go, parse each chunk individually. This would require adjusting the modifyTextForUrlLinks function in ExpensiMark.js to handle the chunked text.

Reconstruct the Parsed Text: After all chunks have been parsed, they would be combined back together to form the fully parsed text. This should be done in such a way that it is seamless and does not affect the format of the text.


And then testing,The solution would be thoroughly tested to ensure that it works as expected and does not introduce new issues. This would include testing with long strings of text, as well as regular-sized text to ensure normal functionality is not affected.

**Comment by mollfpr** [comment] 2023-07-13 11:54
Following the similar issue in the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1689024254320539)

**Comment by mkhan9047** [comment] 2023-07-25 02:52
I commented here with my solution and also gave my Upwork Id link and my account email. But got no reply or contract on Upwork. I can do it, I shared my solution too.

**Comment by mollfpr** [comment] 2023-07-25 05:10
@mkhan9047 You must send a proposal like https://github.com/Expensify/App/issues/22554#issuecomment-1629083833 to get the C+ review.

Please read through the [CONTRIBUTING_GUIDES](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to get a better idea of how to start contributing to this repo and what the process here.

**Comment by mkhan9047** [comment] 2023-07-25 05:11
Ok

**Comment by mollfpr** [comment] 2023-07-27 16:54
@twisterdotcom I just tested the PR for #21266, and it did fix this issue. I think we can close this.

**Comment by twisterdotcom** [comment] 2023-07-28 14:49
Okay great. Going to close!

**Closed by twisterdotcom** 2023-07-28 14:49 UTC
Labels: External, Daily, Help Wanted, Bug
