### ISSUE TITLE
When Desktop app updates then is backgrounded, chats don't load

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33024] opened 2023-12-13 21:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702503781867299

## Action Performed:

1. App is updated
2. App opens and is backgrounded (ie. another window is open on top of NewDot)

## Expected Result:
App to load, inc. LHN and a chat

## Actual Result:
App just shows the E logo and doesn't load until it's in the foreground.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2023-12-13 22:08
@TMisiukiewicz want me to assign this to you?

**Comment by TMisiukiewicz** [comment] 2023-12-14 07:04
@mallenexpensify please assign me, thanks!

**Comment by mallenexpensify** [comment] 2023-12-18 20:50
Assigned @TMisiukiewicz !
I _feel_ like I had an instance late last week where the app was backgrounded and DID load.  I'll attempt to reproduce and report back if it is loading while backgrounded.

**Comment by mallenexpensify** [comment] 2023-12-19 05:14
I just updated to Version 1.4.14-0  and the app loaded while backgrounded. 
I closed NewDot ,reopened and immediately backgrounded and the appeared to not show chats when backgrounded (I should prolly test this more though)

**Comment by TMisiukiewicz** [comment] 2023-12-19 08:41
@mallenexpensify I was not able to reproduce it yet, gonna try again today also with reopening and immediate backgrounding 👍

**Comment by TMisiukiewicz** [comment] 2023-12-19 13:47
Still cannot reproduce it in any way. However I have investigated when the splash screen is displayed and there are numerous conditions that has to be met to hide it:
-  app needs to get server's response to determine if a room is public
- navigation is ready
- user is not authenticated or the sidebar is loaded
- splash screen is visible

I assume one of them is not met in some specific situation but since I couldn't reproduce it, it's hard to point which one. In my opinion the biggest possibility is server response and loaded sidebar, however I always got correct values here.

> I closed NewDot ,reopened and immediately backgrounded and the appeared to not show chats when backgrounded (I should prolly test this more though)

@mallenexpensify did you see the green splash screen and Expensify logo in this situation, or you had skeleton loader instead of chats?

**Comment by mallenexpensify** [comment] 2023-12-19 22:32
Just closed and reopened. 
- Showed green page with icon for a while ~30 seconds
- App loaded as expected

So...I'm not experiencing the issue any more.  I did post in #expensify-bugs to see if others were though, since it used to happen to me allllll the time
https://expensify.slack.com/archives/C049HHMV9SM/p1703025068775339?thread_ts=1702503781.867299&cid=C049HHMV9SM

**Comment by TMisiukiewicz** [comment] 2023-12-20 07:26
Let's wait some time to see if it is reproducible for others then 👍

**Comment by dylanexpensify** [comment] 2023-12-20 09:29
reviewing today reproducibility!

**Comment by mallenexpensify** [comment] 2023-12-21 19:10
I think I had a weird instance this morn
- Updated desktop
- Background desktop briefly
- Put computer to sleep by dragging cursor to bottom left corner (not the same as closing lid on laptop)
- Logged back in using fingerprint
- When I finally foregrounded NewDot, it hadn't loaded, think it was just he E icon then skeleton then loaded. 

Def an edge case but dropping in here cuz I happened to see this issue in my inbox

**Comment by TMisiukiewicz** [comment] 2024-01-03 07:37
still couldn't reproduce

**Comment by mallenexpensify** [comment] 2024-01-05 00:35
Haven't had this happen for a bit and it doesn't appear others have so... gonna close

**Comment by mallenexpensify** [comment] 2024-01-18 18:15
Reopening, this just happened to me now, Desktop was background for many minutes (unsure, but at least 10?) and didn't load til I clicked it.  Pretty sure it happened yesterday too but I tested, by closing/reopening and it loaded correctly, so the bug might be specific to Desktop updating to a new version

**Comment by dylanexpensify** [comment] 2024-01-23 13:32
Oh weird, will investigate

**Comment by mallenexpensify** [comment] 2024-01-26 00:25
fwiw... gonna close again cuz I've been trying to reproduce and am unable to.  I'm _guessing_ others aren't able to either.

**Closed by mallenexpensify** 2024-01-26 00:25 UTC
Labels: Engineering, Daily, Bug
