### ISSUE TITLE
[$250] LHN -Wrong LHN recent activity message when dismiss approver role and add it again

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48744] opened 2024-09-06 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.30-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4937429&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceapprover177@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver

Steps:
1. As employee submit 2 expenses to the workspace chat
2. As Approver Hold one of the expenses and fully approve the report
3. As Owner, go to Workflows> Assign yourself as Approver
4. Verify that Workspace chat disappears from Approver's LHN
5. As Owner, go to Workflows> Assign Approver as Approver again
6. As Approver, take a look at the recent activity section in workspace chat on LHN

## Expected Result:
"Workspace approved amount" message should be present in Workspace chat on LHN as last activity

## Actual Result:
"Collaboration between Uses and Workspace chat starts here" message appears on Workspace chat LHN until open the page when message change to "Workspace approved amount"

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/681109fd-f50a-4fdf-a8ee-bd76563f023b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833162091084754423</li>
        <li>Upwork Job ID: 1833162091084754423</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by IuliiaHerets** [comment] 2024-09-06 20:36
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-09-09 15:14
Reproduced.

**Comment by trjExpensify** [comment] 2024-09-10 01:24
I think this is a pretty minor issue with removing and re-adding someone to the workspace chat. I'd vote to close it, personally.

**Comment by joekaufmanexpensify** [comment] 2024-09-10 12:11
Works for me

**Closed by joekaufmanexpensify** 2024-09-10 12:11 UTC
Labels: External, Daily, Help Wanted, Bug
