### ISSUE TITLE
 QBO - Error appears when connecting to QBO

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47435] opened 2024-08-14 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990438
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: new workspace with Accounting enabled
1. Go to Accounting
2. Connect QBO

## Expected Result:
QBO connected. Sync without errors

## Actual Result:
An error appears 'Can't connect to QuickBooks Online. ("undefined")'
User has to manually Sync connection again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5e111f85-3a67-470d-a51d-6cb2e3bbe6d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-14 15:43
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-08-14 18:52
@arosiclair any idea what the issue is here or who might know?

**Comment by sakluger** [comment] 2024-08-14 19:10
This is likely the same issue as https://github.com/Expensify/App/issues/44148, where the same thing is happening with the Xero connection. We can close this one.

**Closed by sakluger** 2024-08-14 19:10 UTC
Labels: Daily, Bug
