### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] AuthScreens reconnectApp call is passing an outdated lastUpdateIDAppliedToClient

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#32583] opened 2023-12-06 19:30 UTC
See conversation in https://expensify.slack.com/archives/C01GTK53T8Q/p1701890693827559

Steps:
- Add a comment, I can see the lastUpdateID is returned and saved in the key OnyxUpdatesLastUpdateIDAppliedToClient
- Go offline and back online
- AuthScreens reconnect code (https://github.com/Expensify/App/blob/d6c824b90dd252d0e4511ab07380cff986c49745/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L156-L162) runs
- But lastUpdateIDAppliedToClient is NOT the updated updateID we saved above

It is probably because this useEffect call https://github.com/Expensify/App/blob/d6c824b90dd252d0e4511ab07380cff986c49745/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L141 is passing [] as its dependency.
I was going to add lastUpdateIDAppliedToClient as a dependency but:
- I noticed there's a lot of other variables that we are using that are not passed to useEffect
- Not sure if there is a performance concern if I do that

I see that this behavior was introduced in this PR https://github.com/Expensify/App/pull/27764 by @barttom, so ideally they would fix it.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cbdee1256058e0a</li>
        <li>Upwork Job ID: 1732503147695874048</li>
        <li>Last Price Increase: 2023-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27989002</li>
<li>situchan | Contributor | 27989059</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-12-06 19:58
Is there any bug I can reproduce in the app because of this issue? Or just dev fix?

**Comment by iwiznia** [comment] 2023-12-06 20:02
I don't get the question, the bug is described above. We should be passing the latest updateID, but instead we are passing an old one, so we are getting updates we don't need and those updates will be bigger and bigger over time (assuming you don't reload the page or restart the app)

**Comment by barttom** [comment] 2023-12-06 20:21
Hey!
I can look into this on Friday or next week.
However, I don't think that my PR created this issue.
Before my PR, this callback was created in the `componentDidMount` event, so the first value of `lastUpdateIDAppliedToClient` has been cached. 
The whole logic has been restored with hooks, some in that case hook `useEffect` with empty dependencies to run the callback once on `componentDidMount` event. Adding  lastUpdateIDAppliedToClient to the dependencies will launch all logic from useEffect callback for every change of this dependency/

**Comment by iwiznia** [comment] 2023-12-06 20:50
Check the conversation, we've "dismissed" what that last comment is saying.

**Comment by iwiznia** [comment] 2023-12-06 20:52
Assigning @barttom so that they can look and fix this, given it was introduced in that other PR I  linked in the description.

**Comment by garrettmknight** [comment] 2023-12-29 16:32
@barttom is off for the holidays, but should be back next week.

**Comment by barttom** [comment] 2024-01-02 08:20
PR is ready for 3 weeks and waiting for review

**Comment by garrettmknight** [comment] 2024-01-26 18:52
@situchan I'll pay out once you finish the checklist. Thanks!

**Comment by situchan** [comment] 2024-01-26 19:19
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27764
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27764/files#r1468051765
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. This was not noticeable by production users. Just caught while debugging code. So no need regression test.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by garrettmknight** [comment] 2024-01-29 09:11
All paid up, closing.

**Closed by garrettmknight** 2024-01-29 09:11 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
