### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Expensify Card - On report fraud page, error does not redirect and can not be closed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49010] opened 2024-09-11 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
PreCond: User has Expensify Card set up and assigned
1. Open the New Expensify iOS app
2. Sign into a valid account
3. Go to Profile > Wallet > Expensify Card
4. Go to Report Virtual Card fraud > Deactivate Card

## Expected Result:
User expects that after the loading spinner on the button, a redirect occurs

## Actual Result:
No redirect occurs after hitting the button, the button can be hit several times. Only after exiting the page and going back will the user notice an error message. This error message can not be deleted by tapping the "X" button.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/81215eaf-c480-4e45-9de4-420b35859b17

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834534968013390587</li>
        <li>Upwork Job ID: 1834534968013390587</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103979604</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 17:34
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment] 2024-09-11 22:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Card fraud report page does not redirect back upon clicking `Deactivate Card` and error message could not be dismissed.

### What is the root cause of that problem?
- We haven't set navigation flow on clicking `Deactivate Card` button.
- Error message is hard coded to not allow user to dismiss.

### What changes do you think we should make in order to solve the problem?
- For redirecting based on whether we want to redirect to wallet or card page add....
```js
// redirect to wallet page
Navigation.goBack(ROUTES.SETTINGS_WALLET.getRoute();
```
or 
```js
// redirect to card page
Navigation.goBack(ROUTES.SETTINGS_WALLET_DOMAINCARD.getRoute(cardID)
``` 
here
https://github.com/Expensify/App/blob/ecb629d42de6ff0e1c6315193fc0b76644cf7fad/src/pages/settings/Wallet/ReportVirtualCardFraudPage.tsx#L75

- And for dismissing error revert `canDismissError` to `true` here
https://github.com/Expensify/App/blob/ecb629d42de6ff0e1c6315193fc0b76644cf7fad/src/pages/settings/Wallet/PaymentMethodList.tsx#L220

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by QasimBham** [comment] 2024-09-13 11:41
Proposal
Please re-state the problem that we are trying to solve in this issue.
No redirect occurs after hitting the button, the button can be hit several times.
Only after exiting the page and going back will the user notice an error message. This error message can not be deleted by tapping the "X" button.
Solution: 
we can redirect it to the specific user's card itself such that
Navigation.navigate(ROUTES.SETTINGS_WALLET_DOMAINCARD.getRoute(cardID));

**Comment by QasimBham** [comment] 2024-09-13 11:43
Proposal
Please re-state the problem that we are trying to solve in this issue.
"No redirect occurs after hitting the button, the button can be hit several times."


What is the root cause of that problem?
"not targeting the id to card"


What changes do you think we should make in order to solve the problem?
"we can redirect it to the specific user's card itself such that
Navigation.navigate(ROUTES.SETTINGS_WALLET_DOMAINCARD.getRoute(cardID));"


What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2024-09-16 06:38
Thanks for the proposals! @dominictb 's [Proposal](https://github.com/Expensify/App/issues/49010#issuecomment-2345118755) looks good to me. We’ll need to update the passed parameter in the `virtualCardError` value. I also agree with the part where we update the Onyx value for the card and set the errors value to null when the close icon is pressed on the Wallet screen.

**Sidenote**: I’m currently not receiving any error message when I press "Deactivate Card". @dominictb, if you can reliably reproduce this issue, please add it to the test steps in the PR.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2024-10-01 08:38
Approving again to reassign the internal engineer, as Carlos is OOO.

🎀 👀 🎀

**Comment by garrettmknight** [comment] 2024-10-08 23:11
Went to staging yesterday.

**Comment by cead22** [comment] 2024-10-21 19:11
Not overdue. Just undergoing payment process

**Comment by cead22** [comment] 2024-10-21 23:34
Not overdue. Just undergoing payment process

**Comment by garrettmknight** [comment] 2024-10-22 14:49
**Payment Summary:**
- Contributor: @dominictb $250 paid via Upwork
- Contributor+: @jayeshmangwani $250

**Closed** 2024-10-22 14:50 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-23 10:32
Confirming that the [payment summary](https://github.com/Expensify/App/issues/49010#issuecomment-2429502353) here is correct.

**Comment by garrettmknight** [comment] 2024-10-23 10:33
$250 approved for @jayeshmangwani
