### ISSUE TITLE
Missing tag violation does not disappear quickly when updating a tag

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38775] opened 2024-03-21 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708390162425549

## Action Performed:

1. On a workspace with required tags and enabled tags
2. Create manual money request without a tag
3. On the money request view, confirm you see Missing Tag violation 
4. Click on the tag row, click on an enabled tag

## Expected Result:
Missing tag should disappear instantly because we have client side logic to update the missing tag violation

## Actual Result:
Missing tag violation doesn't disappear

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c2e18c48-566e-45bf-87ef-c058478dfc45

https://github.com/Expensify/App/assets/38435837/87e4b15f-bc0c-430e-a73f-2a5bd808c31c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2024-03-21 20:59
- Discussing in this thread https://expensify.slack.com/archives/C049HHMV9SM/p1711054618216139?thread_ts=1708390162.425549&cid=C049HHMV9SM
- I think this is a duplicate of https://github.com/Expensify/App/issues/38044, so closing

**Closed by cead22** 2024-03-21 20:59 UTC
Labels: Daily, Bug
