### ISSUE TITLE
[HOLD RN Upgrade] Android - Invoice - In invoice details page, reopening amount field shows cursor at beginning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50055] opened 2024-10-02 11:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Log in with new expensifail account
3. Tap fab -- new workspace - more features - enable invoice
4. Navigate to LHN
5. Tap fab - send invoice
6. Enter an amount and tap next
7. Select a user
8. Tap next
9. Enter company name and address
10. Tap send invoice
11. Open invoice - amount
12. Reopen the amount field

## Expected Result:
In invoice details page, reopening amount field must not show cursor at beginning

## Actual Result:
In invoice details page, reopening amount field shows cursor at beginning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2521a545-b9bd-4969-b404-82170b95ef48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-02 11:58
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-03 08:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In invoice details page, reopening amount field shows cursor at beginning

### What is the root cause of that problem?
The weird bug happens by the old HOC `withOnyx` in `IOURequestStepAmount`. That causes the currency to flicker from USD to the current currency



https://github.com/user-attachments/assets/72b281ec-0320-4195-b49f-da77feecfada

https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/iou/request/step/IOURequestStepAmount.tsx#L334
### What changes do you think we should make in order to solve the problem?

Remove `withOnyx` in `IOURequestStepAmount` and use `useOnyx`. The test branch [here](https://github.com/nkdengineer/App/tree/fix/50055)

https://github.com/Expensify/App/blob/efa3274237e9da1d4fdcea10db8f04458a3105e8/src/pages/iou/request/step/IOURequestStepAmount.tsx#L334
### What alternative solutions did you explore? (Optional)

### Result


https://github.com/user-attachments/assets/205fd6c0-b888-4e0d-86e8-aea7aec3e84d

**Comment by situchan** [comment] 2024-10-03 21:53
@nkdengineer thanks for the proposal. The root cause is not clear. Please explain why this bug happens only on android.
I tested your branch and bug is still reproducible.

**Comment by nkdengineer** [comment] 2024-10-04 07:45
@situchan Can you share the video that you tested in my test branch.

**Comment by nkdengineer** [comment] 2024-10-04 08:04
> The root cause is not clear. Please explain why this bug happens only on android.

@situchan That is because the `withOnyx` is outdated and on Android, there are more delays on the other platform when we merge the Onyx data then which can affect the weird lifecycle on Android.

We can see the log here in `IOURequestStepAmount`, this component is mounted and unmounted two times when we open this page

<img width="567" alt="Screenshot 2024-10-04 at 15 03 49" src="https://github.com/user-attachments/assets/6c3bb0f7-9e79-4cfe-8bd3-64ed3230dccd">

And here is the result when we use `useOnyx`
<img width="567" alt="Screenshot 2024-10-04 at 15 03 15" src="https://github.com/user-attachments/assets/8441a593-ce0b-4ef7-a287-749db98733e7">

**Comment by QichenZhu** [comment] 2024-10-04 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Sometimes the caret in the currency amount input is initially at the beginning instead of the end.

### What is the root cause of that problem?

The native component `ReactEditText` is not initially selectable. It only becomes selectable after it is attached to window.

https://github.com/facebook/react-native/blob/699f73a6b0734fe716b01d263e9579bca38c4652/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L1053C3-L1060

```Java
public void onAttachedToWindow() {
```

```Java
  super.setTextIsSelectable(true);
```

`TextInput` component sets the selection in the code below.

https://github.com/facebook/react-native/blob/699f73a6b0734fe716b01d263e9579bca38c4652/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1104-L1132

```JSX
useLayoutEffect(() => {
```

```JSX
  viewCommands.setTextAndSelection(
```

The execution order of making it selectable and setting the selection is random. If making it selectable runs after setting the selection, the selection resets to the beginning.

To validate this, we can print logs before and after `setTextIsSelectable()`.

```Java
FLog.w(TAG, "Before: selectable = " + isTextSelectable() + " selectionStart = " + getSelectionStart() + " selectionEnd = " + getSelectionEnd());
super.setTextIsSelectable(true);
FLog.w(TAG, "After: selectable = " + isTextSelectable() + " selectionStart = " + getSelectionStart() + " selectionEnd = " + getSelectionEnd());
```

We’ll notice when this bug occurs, the selection is at the right (`Before: selectable = false selectionStart = 4 selectionEnd = 4`) then resets to the left (`After: selectable = true selectionStart = 0 selectionEnd = 0`).

This is not always reproducible and happened in my tests only about 1 out of 10 times.

### What changes do you think we should make in order to solve the problem?

We could add a patch to `node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java` to save the selection before calling `setTextIsSelectable()` and restore it afterward.

```Java
int prevSelectionStart = getSelectionStart();
int prevSelectionEnd = getSelectionEnd();
super.setTextIsSelectable(true);
setSelection(prevSelectionStart, prevSelectionEnd);
```



### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2024-10-07 21:52
@nkdengineer here's video:

https://github.com/user-attachments/assets/7551ceaf-f19e-41ea-8f89-5c96fc5de81b

@QichenZhu if it's RN bug, it should be fixed in upstream. Can you please create issue in RN?

**Comment by QichenZhu** [comment] 2024-10-08 04:06
> Can you please create issue in RN?

@situchan Sure, I'll try to make a reproducer as required by RN first.

BTW, I don’t expect them to process it quickly. For reference, the contributor from issue https://github.com/Expensify/App/issues/21219 created a PR for them over a year ago, and it's still under review.

**Comment by QichenZhu** [comment] 2024-10-08 06:36
@situchan Here's a minimal reproduction:

```JSX
import { TextInput } from 'react-native';
import { useEffect, useRef} from 'react';

export default function App() {
  const input = useRef(null);
  useEffect(() => { setTimeout(() => input.current?.focus(), 1000); }, []);
  return <TextInput ref={input} value='1.00' selection={{start: 4, end: 4}} />;
}
```

### Reproduction Steps

1. Clone the reproducer https://github.com/QichenZhu/reproducer-react-native-textinput.git

2. Build the Android app with **New Arch** enabled.

```Bash
cd ReproducerApp
yarn
yarn android
```

3. Start Metro.

```Bash
npx react-native start
```

4. Launch the app.

5. Wait a second.

**Expected result:** The caret is at the end.

**Actual result:** The caret is at the beginning.

https://github.com/user-attachments/assets/5f3094ec-f253-45ac-8438-0d0d38db5268

**Comment by situchan** [comment] 2024-10-08 18:42
@QichenZhu thanks. Let's try to fix upstream first. If it takes too long, we can consider patch.

**Comment by QichenZhu** [comment] 2024-10-10 15:53
The upstream issue https://github.com/facebook/react-native/issues/46943 is resolved and the PR https://github.com/facebook/react-native/pull/46948 is merged. It may take one or two months for the changes to be included in a release.

**Comment by sakluger** [comment] 2024-10-10 18:50
@situchan what do you think - should we move to monthly and wait for the upstream PR to be released? That's what I think we should do, since this bug isn't a huge impact to customers.

**Comment by situchan** [comment] 2024-10-14 04:50
Let's assign @QichenZhu since their upstream [PR](https://github.com/facebook/react-native/pull/46948) was merged.
And hold this for RN upgrade.
Proposal: https://github.com/Expensify/App/issues/50055#issuecomment-2393742852
🎀👀🎀 C+ reviewed

**Comment by QichenZhu** [comment] 2024-11-06 04:02
The upstream bug seems to cause new issues (#52026, possibly #51878) in our repo. Should we apply an immediate fix, or continue holding this issue?

**Comment by sakluger** [comment] 2024-11-06 19:20
@situchan what do you think we should do here? Continue holding, or find another fix?

**Comment by sakluger** [comment] 2024-11-06 19:28
@situchan do you still think we should continue holding for the upstream fix to be released, or should we try fixing immediately?

**Comment by QichenZhu** [comment] 2024-11-12 08:42
@situchan [mentioned](https://github.com/Expensify/App/issues/49448#issuecomment-2455599396) he was on parental leave. Not sure if he’s back yet. @sakluger @aldo-expensify Could you respond to the above 2 comments?

**Comment by aldo-expensify** [comment] 2024-11-13 00:23
@QichenZhu I understand that the fix you did [here](https://github.com/facebook/react-native/commit/ca0abd1b9ea164a566b39cb9090eaa75647aad5a) has not been released yet, correct?
Do we need to do a "[open a pick request](https://github.com/reactwg/react-native-releases/blob/main/docs/faq.md#how-to-open-a-pick-request)" for your fix?

**Comment by aldo-expensify** [comment] 2024-11-13 01:09
> > Do we need to do a "[open a pick request](https://github.com/reactwg/react-native-releases/blob/main/docs/faq.md#how-to-open-a-pick-request)" for your fix?
> 
> Yes, I think so if we want it included in 0.75 or 0.76, but I'm not sure how long they'll take to process it.

Requested here: https://github.com/reactwg/react-native-releases/issues/622, maybe lets give it a week and then we reassess?

**Comment by ikevin127** [comment] 2024-11-19 02:01
Coming from issue https://github.com/Expensify/App/issues/52029, it was decided to move forward with creating a patch with the fixes already merged into `react-native` because of the lengthy timeline it would take **E/App** to upgrade to the future version of `react-native` where the fixes will be available. The patch will also fix this issue, therefore I added it to the PRs **Fixed Issues** section which triggered the automation.

**Comment by aldo-expensify** [comment] 2024-11-19 02:08
I think we should close this issue... this https://github.com/Expensify/App/issues/52029 is pretty a dupe of this one (same root cause). Is anyone missing compensation for this issue or can I just close it?

**Comment by ikevin127** [comment] 2024-11-19 02:15
Compensation will be handled in https://github.com/Expensify/App/issues/52029, so I'd say we can close this one.

**Comment by sakluger** [comment] 2024-11-19 22:50
@QichenZhu we can compensate you for your work on the upstream PR. Please let me know once you've accepted the below offer.

Summarizing payment on this issue:

Contributor: @QichenZhu $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104978993

**Comment by QichenZhu** [comment] 2024-11-19 22:56
Thank you so much! Offer accepted. @sakluger

**Comment by sakluger** [comment] 2024-11-20 02:42
Of course!

I've paid out the offer, so we're good to close this issue now.

**Closed by sakluger** 2024-11-20 02:42 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by situchan** [comment] 2025-10-08 15:26
Am I eligible for compensation?
I fully reviewed proposals and 🎀 [here](https://github.com/Expensify/App/issues/50055#issuecomment-2409940436). There was no need of app PR thanks to RN upgrade.

**Comment by sakluger** [comment] 2025-10-17 18:36
Thanks! I completed the upwork payment 👍
