### ISSUE TITLE
[$500] Request Money - Search focus appear on flash and than disappear when user click change currency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27030] opened 2023-09-08 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click FAB button
3. Select Request money
4. Click on Currency

## Expected Result:
Search field should be focused so user can search for a currency

## Actual Result:
Search focus appear on flash and than disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.66-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/17e1d51e-89bf-496e-9042-60e9dd2ac7f8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c48747135456f06b</li>
        <li>Upwork Job ID: 1701054339692290048</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-09 13:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search text input is focused briefly right after the section is opened and then loses focus. 

### What is the root cause of that problem?
It seems to be a strange issue, while the same currency selector works just fine on the Split Bill tab, it does loses the focus when used on the Request Money tab. 

### What changes do you think we should make in order to solve the problem?
Forcing a focused delay seems to solve the issue, without introducing any regressions, by setting the prop  `shouldDelayFocus` to `true`. 

https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/pages/iou/IOUCurrencySelection.js#L137C22-L146

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-09-10 08:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU Currency Selection not autofocusing on the search field when the modal is opened.

### What is the root cause of that problem?
- Its focusing onto list after search field so it gets out-focused instantly.

### What changes do you think we should make in order to solve the problem?
- Solution is to add `shouldDelayFocus` prop to below code.

https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/pages/iou/IOUCurrencySelection.js#L137-L138

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by sophiepintoraetz** [comment] 2023-09-11 02:05
Able to reproduce
![2023-09-11_14-04-44 (1)](https://github.com/Expensify/App/assets/42940078/c0a9ef57-a8e8-4cab-9b92-92d07d32a89e)

**Comment by mvtglobally** [comment] 2023-09-21 03:36
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2023-09-28 03:25
Issue not reproducible during KI retests. (Second week)

**Comment by sophiepintoraetz** [comment] 2023-09-28 03:28
I think I'll close this one out if it's no longer reproducible.

**Closed by sophiepintoraetz** 2023-09-28 03:28 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
