### ISSUE TITLE
Web - Action button is 32*32 instead of 32*40

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21692] opened 2023-06-27 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21131
## Action Performed:
1. Login to NewDot
2. Go to any chat
3. Check Action button size

## Expected Result:
Action button should be 32*40

## Actual Result:
Action button is 32*32 instead of 32*40

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6108198_screenshot_02](https://github.com/Expensify/App/assets/78819774/6c617d28-4186-4399-924f-ddab93b546ab)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-06-27 15:03
Discussing in the above issue.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 15:07
We decided this is [not a bug. ](https://github.com/Expensify/App/issues/15819#issuecomment-1609694204) Closing!

**Closed by joekaufmanexpensify** 2023-06-27 15:07 UTC
Labels: Daily, Bug
