### ISSUE TITLE
LHN - LHN displays incorrect last action when editing text + attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44870] opened 2024-07-04 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695552
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Write something in the compose box
4. Send an attachment to a conversation while there is text in compose box
5. Edit a text message in a sent message
6. Note the text of the last action in LHN

## Expected Result:
After editing a message with an attachment, LHN should show text + attachment or text and "..." if the text is long

## Actual Result:
When sending text + attachment to a conversation, LHN shows text + attachment as last action, after editing the message in LHN only the attachment is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f59fe463-5d21-4d3b-85fa-e8732f3dd15d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment] 2024-07-04 19:50
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-04 19:51
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-07-10 04:31
Agree with the project. I also added the external label.

**Comment by huult** [comment] 2024-07-11 16:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Displays incorrect last action when editing text + attachment

### What is the root cause of that problem?

This issue originates from the backend. We sent optimistic data with the updated `lastMessageText`, but when calling`UpdateComment`, it has not updated yet.

<img width="748" alt="Screenshot 2024-07-11 at 23 27 44" src="https://github.com/Expensify/App/assets/20178761/656aa960-5ffb-4918-b097-2305eed47b35">

### What changes do you think we should make in order to solve the problem?

Should double check `UpdateComment` API

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2024-07-16 10:51
Thanks @huult, @JmillsExpensify It seems to be a backend issue as `updateComment` should return the correct `lastMessageText`. Can we add an internal engineer here?

<img width="1437" alt="Screenshot 2024-07-16 at 10 28 48" src="https://github.com/user-attachments/assets/86a18250-c9b6-4582-a7fa-b790d7aa053a">

**Comment by Pujan92** [comment] 2024-07-19 18:16
@JmillsExpensify We need to assign an internal engineer here.

**Comment by mvtglobally** [comment] 2024-08-03 04:08
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-08-09 04:25
Issue not reproducible during KI retests. (Second week)

**Comment by Pujan92** [comment] 2024-08-13 18:04
@JmillsExpensify This seems resolved in the backend, We can close this issue.

**Comment by mvtglobally** [comment] 2024-08-23 12:03
Issue not reproducible during KI retests. (Third week)

**Comment by JmillsExpensify** [comment] 2024-08-28 12:41
Thanks, closing!

**Closed by JmillsExpensify** 2024-08-28 12:41 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
