### ISSUE TITLE
CRITICAL: [Actionable Whispers] [$250] Converting Tracked Expense Hides All Previous ReportActions

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40265] opened 2024-04-16 02:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Create a policy expense chat
2. add messages in that chat
3. Track an expense to your self-DM
4. Categorize it (moving it to the workspace)

## Expected Result:
You should see the new moneyRequestPreview action, along with the old chats

## Actual Result:
You only see the new moneyRequestPreview action, and everything else remains "loading" or is gone from the chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/30609178/a785ffd0-c2cf-4b9f-bb6e-fe3228f82200

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e87700b7450abadb</li>
        <li>Upwork Job ID: 1780297096064262144</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2024-04-16 15:40
added to vip-vsb for self dm

**Comment by thienlnam** [comment] 2024-04-16 17:37
Yeah let's do it - we're not entirely sure what causes this yet

**Comment by james-tindal** [comment] 2024-04-16 19:49
I get no message from Concierge on submitting an expense.

**Comment by thienlnam** [comment] 2024-04-16 19:55
This is only on main right now - we just merged the actionable whisper PR

**Comment by adelekennedy** [comment] 2024-04-19 16:26
@thienlnam since this is critical and we haven't gotten any proposals should we make this internal and get an engineer assigned?

**Comment by james-tindal** [comment] 2024-04-19 17:45
I've been working on it for the past 3 days and closing in on a solution.

**Comment by quinthar** [comment] 2024-04-21 22:38
@james-tindal - Can you give an update on your progress?

**Comment by james-tindal** [comment] 2024-04-22 12:07
I expect to have a solution today.

**Comment by adelekennedy** [comment] 2024-04-22 14:56
great @james-tindal - @ntdiary will you prioritize reviewing @james-tindal solution today?

**Comment by james-tindal** [comment] 2024-04-23 00:01
I didn't mean to imply I had a working solution. I have a hack fix only. Pretty sure I'll get it finished within 24 hours, then I'll update.

**Comment by quinthar** [comment] 2024-04-23 04:13
Great, thanks!

**Comment by james-tindal** [comment] 2024-04-23 15:40
There's a comment about a relevant conversation. What do they say?
[https://expensify.slack.com/archives/C035J5C9FAP/p1705417778466539?thread_ts=1705035404.136629&cid=C035J5C9FAP](https://expensify.slack.com/archives/C035J5C9FAP/p1705417778466539?thread_ts=1705035404.136629&cid=C035J5C9FAP)

**Comment by james-tindal** [comment] 2024-04-24 02:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
All previous report actions are replaced by a loading skeleton when a tracked expense is moved to a workspace.

### What is the root cause of that problem?

The displayed actions are in a chain linked by `action.previousActionId === previousAction.id`

New action `A` is appended to the report optimistically, before the server responds. 
```js
{ id: A, previousActionId: undefined }
```
It has no previousActionId, so it breaks the chain
The server responds with an identical action `B`, only with a different id and the correct previousActionId. This is also appended to the reportActions. Now the reportActions looks like this:
```js
{ id: B, previousActionId: P }
{ id: A, previousActionId: undefined }
{ id: P, previousActionId: Q }
{ id: Q, previousActionId: R }
{ id: R, previousActionId: "0" }
```
So the chain is still broken after the server responds.


### What changes do you think we should make in order to solve the problem?

The simplest solution to the problem of all previous reportActions being hidden, is to remove the optimistic data for this API request, until I figure out how to fix it.


### What alternative solutions did you explore?

#### Keep optimistic UI and fix it.
I have written code to add the correct previousActionId to the optimistic data.
But, I have not yet figured out how to get the optimistic reportAction to delete when the server response arrives.
This results in reportActions looking like this:
```js
{ id: B, previousActionId: P }
{ id: A, previousActionId: P }
{ id: P, previousActionId: Q }
{ id: Q, previousActionId: R }
{ id: R, previousActionId: "0" }
```
The chain is still broken after the first action.

If the server returned an action with the same ID as the optimistic one, it would replace it, but because it has a different ID, it is appending instead.


#### Fixing already broken reports

1. Delete the reportActions and report from Onyx (indexedDB)
2. Refresh the page
3. App refetches the uncorrupted data from the server.

**Comment by thienlnam** [comment] 2024-04-24 20:47
I'm curious if this is resolved now - we fixed a problem where the optimistic reportPreview reportAction was not stored in the database so we essentially had 
- an optimistic reportAction
- a different real reportAction

So it kept searching for a reportAction that is not there

**Comment by james-tindal** [comment] 2024-04-24 23:01
I can no longer reproduce the bug. Can you link the pull request that fixed it?

**Comment by quinthar** [comment] 2024-04-25 01:01
Neat, can we close this?

**Closed** 2024-04-25 04:17 UTC
Labels: External, Daily, Bug

**Comment by thienlnam** [comment] 2024-04-28 22:03
> I can no longer reproduce the bug. Can you link the pull request that fixed it?

This was a back-end fix
