### ISSUE TITLE
WS-The edit icon background of a workspace becomes transparent in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37412] opened 2024-02-28 11:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to a workspace settings
2. Go offline
3. Upload an avatar for the workspace profile
4. Remove the avatar
5. Observe the background of the edit icon inside the circle
6. Compare the result with other platforms like mWeb and Web

## Expected Result:
The background of the circle inside the edit icon should be easily noticeable like in other platforms

## Actual Result:
The background of the circle inside the edit icon becomes transparent which is different from the result in other platforms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/38c83431-4ed4-43f4-a5bb-6a308c7bd8a3

![Bug6395183_1709108963617!wsavatarmweb](https://github.com/Expensify/App/assets/115492554/9f874918-6b01-4f67-86e9-b1405ca91f26)
![Bug6395183_1709109076426!Screenshot_2024-02-28_113039](https://github.com/Expensify/App/assets/115492554/eca6ff10-dd0d-422d-8e5c-9c8a65b4880e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-28 11:45
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dylanexpensify** [comment] 2024-02-29 11:06
Confirming today!

**Comment by dylanexpensify** [comment] 2024-03-06 10:39
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment] 2024-03-11 10:09
cannot reproduce - closing

**Closed by dylanexpensify** 2024-03-11 10:09 UTC
Labels: Daily, Overdue, Bug
