### ISSUE TITLE
[$500] Web - The user's email position changes after deleting a comment in an attachment's thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27472] opened 2023-09-14 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Click on Actions > Add mp4 attachment > Send
4. Reply in thread > Delete comment

## Expected Result:
The user's email should change its position only once the attachment is deleted

## Actual Result:
The user's email changes its position twice, first when the comment is deleted and then again after a few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/730af8c2-c74c-4d39-81e3-70b126ee8ff8

https://github.com/Expensify/App/assets/93399543/3a4b58c8-5e1a-47df-9442-d1adb2526d03

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694552991473059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a56b9a227351a5ac</li>
        <li>Upwork Job ID: 1702422907565584384</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-14 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user's email position changes after deleting a comment in an attachment's thread
### What is the root cause of that problem?
This because we show the [deleted message] depend on pending action, but the above margin not.

https://github.com/Expensify/App/blob/62b8e71105959aaa4392da20b251ca1fafd5ab3d/src/pages/home/report/ReportActionItemFragment.js#L120

Margin top not depending on pending action.
https://github.com/Expensify/App/blob/62b8e71105959aaa4392da20b251ca1fafd5ab3d/src/pages/home/report/ReportActionItemMessage.js#L51
### What changes do you think we should make in order to solve the problem?
We need to remove the margin top when pendingAction is delete
```javascript
const {isOffline} = useNetwork();
const isPendingDelete = !isOffline && props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE;


// <View style={[styles.chatItemMessage, !props.displayAsGroup && isAttachment ? styles.mt2 : {}, ...props.style]}>
<View style={[styles.chatItemMessage, !props.displayAsGroup && isAttachment && !isPendingDelete ? styles.mt2 : {}, ...props.style]}>
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sakluger** [comment] 2023-09-18 07:42
Thanks @bernhardoj, closing this one in favor of the other.

**Closed by sakluger** 2023-09-18 07:42 UTC
Labels: External, Daily, Help Wanted, Bug
