### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Pay-On pay money, description in preview changed to expense after few seconds

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40585] opened 2024-04-19 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap on a report
3. Enter an amount and tap next
4. Enter description
5. Tap pay elsewhere
6. Note IOU preview details

## Expected Result:
When we pay money, description or merchant must be displayed without getting altered.

## Actual Result:
When we pay money, description is shown in preview and after few seconds it is changed to "expense"(merchant)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/39a96dc4-9ccd-45e2-a7a9-ec30f3b54775

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018753cc78d651b6ba</li>
        <li>Upwork Job ID: 1785065405571158016</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment] 2024-04-19 16:16
We think this issue might be related to the #vip-vsb.

**Comment by FitseTLT** [comment] 2024-04-19 18:57
BE is setting the merchant to `Expense` for pay request type we can align it in optimistic data to align to it but I think the BE should return none same as submitting request when merchant is not set.

**Comment by bernhardoj** [comment] 2024-04-22 12:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The send money request shows merchant as Expense after a few seconds.

### What is the root cause of that problem?
When we create a new send money request, we always set the merchant to "(none)" since the user isn't allowed to set a merchant for sending money. After the request is completed, BE returns the merchant as "Expense".

This confuses the user because of the value inconsistency between FE and BE. It could be a BE issue, but maybe we intentionally change it since the user is not allowed to set a merchant for a send request.

### What changes do you think we should make in order to solve the problem?

Set the merchant value for send money optimistically to "Expense".
https://github.com/Expensify/App/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/libs/actions/IOU.ts#L4819
```
const optimisticTransaction = TransactionUtils.buildOptimisticTransaction(amount, currency, optimisticIOUReport.reportID, comment, undefined, undefined, undefined, 'Expense');
```

**Comment by kevinksullivan** [comment] 2024-04-29 21:55
Adding to vip-split.

**Comment by DylanDylann** [comment] 2024-04-30 15:12
Taking over as C+

**Comment by DylanDylann** [comment] 2024-05-02 04:47
First of all, we need to clarify the expectations for this case. When creating a new send money request, should we add the default merchant as "Expense"?

@shawnborton Could you help to give a thought from the UX perspective ?

🎀👀🎀 C+ reviewed

Also want to hear an option from the internal engineer

**Comment by trjExpensify** [comment] 2024-05-02 14:13
No context I'm afraid. I agree the default merchant `Expense` we need under the hood shouldn't take priority over a `description` entered. Only a user entered merchant should. 👍

**Comment by marcaaron** [comment] 2024-05-03 01:27
It's not clear to me yet that this is a backend issue. Sounds more like a frontend thing where we want to change the logic for what to display when we have a description vs. when we don't. 

Like, let's say there is no description... are we expecting "(none)" or "Expense"? I think it's the latter still, no?

I see @mountiny [recently updated this from "Request" to "Expense"](https://github.com/Expensify/Auth/pull/10530) so maybe they have some opinion.

**Comment by nkdengineer** [comment] 2024-05-03 08:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we pay money, description is shown in preview and after few seconds it is changed to "expense"(merchant)

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/7483d10e686e240d07d9fa3e43e89ffdfcda9cbd/src/components/ReportActionItem/ReportPreview.tsx#L231-L237

We prioritize displaying the merchant if it isn't empty. In this case, the BE return `merchant: "Expense"`, the `supportText` turn into "Expense"

### What changes do you think we should make in order to solve the problem?
If the merchant is empty or default value 
      -  If description is valuable, we will display description
      - If description is empty, we will display default merchant


```
if (formattedMerchant && formattedMerchant !== "Expense") {
            return {isSupportTextHtml: false, supportText: formattedMerchant};
        }
        if (formattedDescription ?? moneyRequestComment) {
            const parsedSubtitle = new ExpensiMark().replace(formattedDescription ?? moneyRequestComment);
            return {isSupportTextHtml: !!parsedSubtitle, supportText: parsedSubtitle ? `<muted-text>${parsedSubtitle}</muted-text>` : ''};
        }
        if (formattedMerchant === "Expense") {
            return {isSupportTextHtml: false, supportText: formattedMerchant};
        }
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-03 08:50
@DylanDylann [Updated proposal](https://github.com/Expensify/App/issues/40585#issuecomment-2092551854)

While testing my solution I see another bug, I updated proposal to add additional fix

**Comment by DylanDylann** [comment] 2024-05-03 18:09
@mountiny Could you help to check this [comment](https://github.com/Expensify/App/issues/40585#issuecomment-2092000568)?

**Comment by DylanDylann** [comment] 2024-05-08 10:23
Waiting for a confirmation from @mountiny

**Comment by kevinksullivan** [comment] 2024-05-08 19:04
@mountiny any thoughts on  the comments above?

**Comment by mountiny** [comment] 2024-05-08 20:53
Recently we have just updated the default merchant name from `Request` to `Expense` to match the changes with the split expense. 

I have tested this locally and I can confirm there is another bug @nkdengineer mentioned because I am seeing no description or merchant in the send money flow.

I think we need to:
- fix the number of the transactions
- update the default_merchant const to be `Expense` and not `Request`, this was missed in the split expense change
- Update the support_text logic to show the description if defined and the merchant if default or partial.

@marcaaron Feel free to reassign to me if you want to focus on your projects. I am happy to see this one through to the finish since I have worked on the Split Expense project

**Comment by DylanDylann** [comment] 2024-05-09 05:30
As for [this requirement](https://github.com/Expensify/App/issues/40585#issuecomment-2101429021), @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40585#issuecomment-2092551854) looks good. Let's go with them

**Comment by DylanDylann** [comment] 2024-05-09 05:30
As for [this requirement](https://github.com/Expensify/App/issues/40585#issuecomment-2101429021), @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40585#issuecomment-2092551854) looks good. Let's go with them 

🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-06-05 04:37
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA** This caused by BE changes
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**Regression Test Proposal**
1. Click on FAB button
2. Click on Pay Someone
3. Enter amount
4. Go to confirmation page
5. Enter description
6. Click "Pay Somewhere"
7. See that the description still remains and has not been changed


Do we agree 👍 or 👎

**Comment by kevinksullivan** [comment] 2024-06-13 17:35
Regression test created and payments made in upwork. All set

**Closed by kevinksullivan** 2024-06-13 17:35 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
