### ISSUE TITLE
[Performance] iOS app is very slow and unresponsive when syncing data

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9874] opened 2022-07-13 03:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. Send few messages
3. Tap between chats 

## Expected Result:
App should respond quickly 

## Actual Result:
App is very slow and unresponsive 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.78-8
**Reproducible in staging?:** need repro
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/178642366-079da14e-1c86-4c6f-827d-e2cab56163c5.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @stitesExpensify @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657574478512399
https://expensify.slack.com/archives/C01GTK53T8Q/p1657591388376929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-07-13 18:26
I am hesitant to make this `External` as performance issues can be approached in many different ways. From the video, it looks like the app is "syncing" while the slowness occurs. In my experience, network requests should not cause the UI jank we are seeing here. But we should take a shot at identifying the underlying problem before we look at proposals. I'm going to leave this as `Internal` for a bit so we can get clarity on what the real issue is. 

The "app is slow" isn't something that we can take a clear action on and there are a variety of performance initiatives already in place. Once we investigate and have a clear idea about what can be done then it makes sense to open up.

**Comment by marcaaron** [comment] 2022-07-28 16:17
Making this Daily. Just experienced this bug and the iOS app is more or less unusable for several seconds when it starts up.

**Comment by marcaaron** [comment] 2022-08-01 17:25
More recent reports of this here:

https://expensify.slack.com/archives/C01GTK53T8Q/p1659109544841589?thread_ts=1659018169.624599&cid=C01GTK53T8Q

Whatever the issue is - I think it's on production and not staging.

I will try to get iOS app set up and do some debugging today to help move this investigation along.

**Comment by marcaaron** [comment] 2022-08-02 00:30
Gonna close this for now. While the performance is not amazing [fixing this](https://github.com/Expensify/Web-Expensify/pull/34470) has improved it considerably.

**Closed by marcaaron** 2022-08-02 00:30 UTC
Labels: Engineering, Daily, Improvement, Internal
