### ISSUE TITLE
Web - Overlapping Emojis when Changing Default Skin Tone for "CoupleKiss" Emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21751] opened 2023-06-27 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and type a message.
2. Hover over the message and click "Add reaction."
3. Search for "coupleKiss" emoji in the search bar.
4. Change the default skin tone for the "coupleKiss" emoji by clicking on the hand icons at the bottom of the Emoji picker.

## Expected Result:
The emojis should not overlap when changing the default skin tone for the "coupleKiss" emoji.

## Actual Result:
Some emojis overlap when changing the default skin tone for the "coupleKiss" emoji, causing visual issues.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

- [X] Edition	Windows 10 Pro
Version	22H2
Installed on	‎8/‎16/‎2021
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Version Number:** v1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ddb26d92-42b2-46d4-9005-f186f7a54297

https://github.com/Expensify/App/assets/93399543/d099a7bf-6525-45ab-aec1-b8208c6c9737

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687688275769119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e72f32679d51f10</li>
        <li>Upwork Job ID: 1674063590840524800</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-27 22:32
I can't reproduce this on MacOS / Chrome / Safari, asking if it's still happening
<img width="929" alt="image" src="https://github.com/Expensify/App/assets/51066321/22008bc1-2e57-436b-9523-f20267f63859">

**Comment by Christinadobrzyn** [comment] 2023-06-27 22:35
I can't reproduce this on MacOS / Chrome / Safari

Asking for them to test again: https://expensify.slack.com/archives/C049HHMV9SM/p1687905235179519?thread_ts=1687688275.769119&cid=C049HHMV9SM

<img width="929" alt="image" src="https://github.com/Expensify/App/assets/51066321/8e11cd46-5375-4c3a-9058-39884b2401f6">

**Comment by tewodrosGirmaA** [comment] 2023-06-28 00:58
![image](https://github.com/Expensify/App/assets/118253010/90d57593-6944-4664-a6ae-6cd7172b0e60)
![image](https://github.com/Expensify/App/assets/118253010/003c882a-6d8c-4505-ac82-76441e2b6062)

**Comment by Christinadobrzyn** [comment] 2023-06-28 14:17
Hey @tienifr do we test on windows? 

I can't reproduce on Android, Chrome/Safari, iOS, Mac. I think that's all we test on, right?

**Comment by Christinadobrzyn** [comment] 2023-06-28 14:34
I don't think we test on Windows products at this time so I don't think this needs to be fixed but I'll add a C+ to confirm.

**Comment by Christinadobrzyn** [comment] 2023-06-30 21:06
@eVoloshchak just nudging this, should we fix this windows emoji issue? only affecting windows?

**Comment by eVoloshchak** [comment] 2023-07-02 21:02
@Christinadobrzyn, I personally think we should fix Windows, since I suspect most people access NewDot from Windows (no data to back this up, but Windows is the most popular OS). In addition to that, I remember a couple of issues in the past that were fixing Windows-specific issues. That was a while back, not sure if our policy (if there is any) has changed

**Comment by Christinadobrzyn** [comment] 2023-07-03 16:58
Asking what version of windows was used to test this so I can do some testing - https://expensify.slack.com/archives/C049HHMV9SM/p1687974216623249?thread_ts=1687688275.769119&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-07-03 18:37
I don't have any method to test this on a Windows 10 Pro - asking the team if anyone can test.

**Comment by Christinadobrzyn** [comment] 2023-07-03 21:39
It sounds like Windows PC is out of scope since we can't test on it - based on this Slack chat - https://expensify.slack.com/archives/C01SKUP7QR0/p1688409525853629

So closing this for now. feel free to reopen if we start working on Windows PC issues!

**Closed by Christinadobrzyn** 2023-07-03 21:39 UTC
Labels: Weekly, Internal, Bug
