### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] Live MD - Gray placeholder image is displayed when sending markdown image with wrong url

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49992] opened 2024-10-01 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49250
## Action Performed:
1. Navigate to any chat
2. Send an image markdown that has a URL that points to no image. (You can find the url in the attached text file)
3. Click on the image preview from chat history

## Expected Result:
Failed to load error message should be displayed in chat history
And user shouldn't be able to open the image in carousel

## Actual Result:
Gray blank image is displayed
And there is infinite loading when opening the image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6839c9d5-880e-4fb5-b830-2a9774af813d

[txt.txt](https://github.com/user-attachments/files/17210430/txt.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844118961553330610</li>
        <li>Upwork Job ID: 1844118961553330610</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104435699</li>
<li>huult | Contributor | 104435700</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-10-01 13:34
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-01 13:35
We think that this bug might be related to #Live Markdown

**Comment by huult** [comment] 2024-10-01 15:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Gray placeholder image is displayed when sending markdown image with wrong url

### What is the root cause of that problem?

As per the current logic, we only handle the thumbnail image by displaying a gray placeholder when the image fails to load.
https://github.com/Expensify/App/blob/7f0bdf08094574ee019f6b1b2470f71163d2d102/src/components/ThumbnailImage.tsx#L117

and loading forerer

### What changes do you think we should make in order to solve the problem?
We should update the error handling to match the expectations outlined in this ticket, like this:

1. Export `onLoadFailure` to props
```diff
// .src/components/ThumbnailImage.tsx#L65
  function ThumbnailImage({
    ...
+ onLoadFailure,

// .src/components/ThumbnailImage.tsx#L141
 <ImageWithSizeCalculation
    ...
- onLoadFailure={() => setFailedToLoad(true)}
+      onLoadFailure={() => {
+                        setFailedToLoad(true);
+                        onLoadFailure?.(true);
+                    }}    
```
2. Handle image load errors in ImageRender.
```diff
// src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L68
+ const [isFailedToLoad, setIsFailedToLoad] = useState(false);
   <ThumbnailImage
      ...
+    onLoadFailure={(failedToLoad) => {
+                setIsFailedToLoad(failedToLoad);
+            }}  

// src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L86
<PressableWithoutFocus
   ...
+ disabled={isFailedToLoad}   

// src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L107
+ {isFailedToLoad && (
+                                <View style={[styles.borderColorDanger]}>
+                                    <Text style={[styles.textDanger, styles.mt2]}>Failed to load the image. Please try again later.</Text>
+                                </View>
+                            )}
```

**Comment by JmillsExpensify** [comment] 2024-10-09 20:53
Opened up for proposal review.

**Comment by suneox** [comment] 2024-10-11 18:18
The [proposal](https://github.com/Expensify/App/issues/49992#issuecomment-2386373286) from @huult to handle showing the error and disabling the image modal LGTM, but we need to confirm the display of the error and the error message content in this case.


@Expensify/design Can we display an error below the image like this, or do we need a different design for this?
![Screenshot 2024-10-12 at 00 57 55](https://github.com/user-attachments/assets/785a2898-1d20-42b4-9f3e-a9de0c7d44d8)


 @JmillsExpensify  Could you please provide an error message for this scenario?

**Comment by dannymcclain** [comment] 2024-10-11 18:43
I wonder if we could just display a broken image placeholder like this? 

![CleanShot 2024-10-11 at 13 41 39@2x](https://github.com/user-attachments/assets/e1712002-2490-4d1c-a9c5-0c24bb4c7dea)

Is the error message actually going to be helpful at all? I'm just wondering if we really need to display a message at all.

**Comment by suneox** [comment] 2024-10-12 05:11
> I wonder if we could just display a broken image placeholder like this?
> 
> ![CleanShot 2024-10-11 at 13 41 39@2x](https://private-user-images.githubusercontent.com/7516624/375857649-e1712002-2490-4d1c-a9c5-0c24bb4c7dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDkxNjksIm5iZiI6MTcyODcwODg2OSwicGF0aCI6Ii83NTE2NjI0LzM3NTg1NzY0OS1lMTcxMjAwMi0yNDkwLTRkMWMtYTljNS0wYzI0YmI0YzdkZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDQ1NDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWZkNzRmMDBiNTA0MDZkNzYwYzJlZDJkYjFkYTBmYTkzMGMxNThlMTNiMDc2ZmFlN2U1OGYwNjU1YzBlOGRlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ceUKEh5UIRlh1cVVyZGVekRCTSGOdARGv8Jvr_t4OZs)
> 
> Is the error message actually going to be helpful at all? I'm just wondering if we really need to display a message at all.

Yeah, If we display a broken image, I think we can skip showing an error message.

**Comment by dannymcclain** [comment] 2024-10-14 13:32
Sounds good to me. I think that's a solid approach. cc @Expensify/design for a gut check though.

**Comment by shawnborton** [comment] 2024-10-14 19:06
I agree with that, it feels cleaner to just show the broken image with no message.

**Comment by dubielzyk-expensify** [comment] 2024-10-15 04:19
+1 to what @dannymcclain suggested 👍

**Comment by suneox** [comment] 2024-10-15 05:54
We can proceed with @huult [proposal](https://github.com/Expensify/App/issues/49992#issuecomment-2386373286)  to show a broken image and prevent open an image when it fails to load.

🎀 👀 🎀 C+ reviewed

**Comment by MarioExpensify** [comment] 2024-10-15 20:30
Assigning this to @huult , just make sure to adhere to the [proposal of displaying a "broken image"](https://github.com/Expensify/App/issues/49992#issuecomment-2407949828) and we should be good to go! Thank you @suneox

**Comment by huult** [comment] 2024-10-16 02:41
Thank you, everyone. I will create the PR within 24 hours.

**Comment by huult** [comment] 2024-10-16 10:06
@dannymcclain I couldn't find [this image](https://github.com/Expensify/App/issues/49992#issuecomment-2407949828) in the source code. Could you please send it to me?

**Comment by dannymcclain** [comment] 2024-10-16 13:49
It probably hasn't made it's way into the repo yet. Here it is:

[Image Slash.svg.zip](https://github.com/user-attachments/files/17396710/Image.Slash.svg.zip)

**Comment by suneox** [comment] 2024-10-27 16:38
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: *N/A*
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. *There isn’t an offending PR in this case, as this is part of a new UI implementation*
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by JmillsExpensify** [comment] 2024-10-30 18:45
Payment summary:

- Contributor: $250 @huult via Upwork
- Reviewer: $250 @suneox via Upwork

**Comment by JmillsExpensify** [comment] 2024-10-30 18:49
All contributors paid out. Closing.

**Closed by JmillsExpensify** 2024-10-30 18:49 UTC
Labels: External, Daily, Awaiting Payment, Bug
