### ISSUE TITLE
[$500] Chat - Square bracket does not break the link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28608] opened 2023-10-02 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send link with parameter in circular brackets eg: ([google.com/?q=test](http://google.com/?q=test))
4. Observe that app properly understands closing circular bracket and breaks the link before it
5. Now send link with parameter with square brackets
6. Observe that app does not break the link before closing squar e bracket

## Expected Result:
App should not consider brackets as part of link

## Actual Result:
App considers closing square bracket as part of link if link as parameter in it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.75-8 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/097aabde-d590-4e6c-b1da-e132f3fc1afa

https://github.com/Expensify/App/assets/115492554/b244a14a-4e04-4452-a7a5-ade8a74897ea

https://github.com/Expensify/App/assets/115492554/a6fa04b3-6be8-4cdb-92b6-13cee4c7ac6f

https://github.com/Expensify/App/assets/115492554/4ee8f555-bac9-463d-821a-e32a89fb7672

https://github.com/Expensify/App/assets/115492554/3d894bcd-9144-4c43-9901-90a507b1c3c0

https://github.com/Expensify/App/assets/115492554/73aba282-b580-47a7-bdda-51e12e51338d

https://github.com/Expensify/App/assets/115492554/d25b4edf-ef1c-4ac0-9a3f-b98c90ed1232

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696182736476879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a9cfe2e1c136177</li>
        <li>Upwork Job ID: 1708817040566304768</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by szilard-dobai** [comment] 2023-10-02 14:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Messages containing URLs with parameters that end in square brackets posted as comments do not have the brackets parsed out. When the message is sent, whomever clicks the link will be taken to a wrong address.

### What is the root cause of that problem?
After digging around in the codebase, I found the problem lived in the [expensify-common](https://github.com/Expensify/expensify-common) repo which is being used [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L1908). More precisely, in [this](https://github.com/Expensify/expensify-common/blob/main/lib/Url.js#L8) regex that's used to parse and transform plain text messages to HTML, it's escaping square brackets (i.e. allowing them to be part of the query parameter), when they shouldn't be because `[` and `]` are not allowed in URLs ([source](https://stackoverflow.com/a/1016737)) and should be %-encoded.

### What changes do you think we should make in order to solve the problem?

`URL_PARAM_REGEX` should be changed to no longer match `[` and `]`.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by szilard-dobai** [comment] 2023-10-02 14:14
Contributor details
Your Expensify account email: dobai_szilard@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012d6dbf2e31de0765

**Comment by Tony-MK** [comment] 2023-10-02 18:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Square bracket does not break the link

### What is the root cause of that problem?

The root cause of the problem the `URL_PARAM_REGEX` and `URL_FRAGMENT_REGEX` in the URL.js file, located in the expensify-common library, doesn't check the last the square brackets. Therefore, it includes the last brackets as part of the link. The constant regex variables are used to create the `URL_WEBSITE_REGEX' which is used to check for website links in comments.

https://github.com/Expensify/expensify-common/blob/ab4895807dd9a26f64bfaee80db15ee2c48a5124/lib/Url.js#L8-L9

### What changes do you think we should make in order to solve the problem?


Change the `URL_PARAM_REGEX` and `URL_FRAGMENT_REGEX` to include the square brackets. So, I believe using the Negative Lookahead (?!...) and match the square brackets characters. Therefore the `URL_PARAM_REGEX` and `URL_FRAGMENT_REGEX` should like something similar to this.

```
const URL_PARAM_REGEX = `(?:\\?${addEscapedChar('[-\\w$@.+!*()\\/,=%{}:;\\[\\]\\|_|~](?![\[\])')}*)?;

const URL_FRAGMENT_REGEX = `(?:#${addEscapedChar('[-\\w$@.+!*()[\\],=%;\\/:~](?![\[\])')}*)?`;
```

**Comment by cooldev900** [comment] 2023-10-02 19:59
@Tony-MK
Have you considered some cases involving array queries like the following ```?bar[]=1&bar[]=2```

**Comment by r3770** [comment] 2023-10-02 23:04
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
App considers closing square bracket as part of link if link as parameter in it

### What is the root cause of that problem?
Square bracket is considered to be possible param char of URL(in `URL_PARAM_REGEX` and `URL_FRAGMENT_REGEX`), but when url has it as unmatched ending square bracket, it should not be accepted as part of url.

### What changes do you think we should make in order to solve the problem?
As we can check on report video, ending parenthesis is not accepted, but square bracket is.
we have already done about ending parenthesis (https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L449C1-L466C14), so we can remove ending square bracket like it.

**Comment by Victor-Nyagudi** [comment] 2023-10-11 14:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Square bracket does not break the link

### What is the root cause of that problem?

We only have the logic to break links for one type of bracket i.e. `()` in [`ExpensiMark`](https://github.com/Expensify/expensify-common/blob/009c2ab79bf7ddeab0eea7a3a4c0d9cc4277c34b/lib/ExpensiMark.js#L458-L471).

```javascript
//...
for (let i = 0; i < url.length; i++) {
    if (url[i] === '(') {
        unmatchedOpenParentheses++;
    } else if (url[i] === ')') {
        // ...
    }
}
//...
```

That being said, this bug also occurs when a link is wrapped in curly braces i.e. `{}`. 

![expensify-link-in-brackets-tests](https://github.com/Expensify/App/assets/79470910/e24565e6-0e2a-45e5-81d2-4177d4fb8f30)

### What changes do you think we should make in order to solve the problem?


We'll first need to create some additional variables to count how many unmatched opening brackets of each type there are at [the beginning of the `while` loop](https://github.com/Expensify/expensify-common/blob/009c2ab79bf7ddeab0eea7a3a4c0d9cc4277c34b/lib/ExpensiMark.js#L456C46-L456C46). 

```javascript
let unmatchedOpeningParentheses = 0;    // Renamed this to something more meaningful
let unmatchedOpeningSquareBrackets = 0;    // Added
let unmatchedOpeningCurlyBraces = 0;    // Added
```

We'll then add some logic to deal with the two remaining types of brackets - `[]` and `{}` - inside the `for` loop of `modifyTextForUrlLinks()` method in `ExpensiMark` below [the currently existing logic handling parentheses `()`](https://github.com/Expensify/expensify-common/blob/009c2ab79bf7ddeab0eea7a3a4c0d9cc4277c34b/lib/ExpensiMark.js#L470).

```javascript
//...
for (let i = 0; i < url.length; i++) {
    // ... logic for handling parentheses
        
    if (url[i] === '[') { // <- Checking for square bracket
        unmatchedOpeningSquareBrackets++;
    } else if (url[i] === ']') {
        // Unmatched closing square bracket
        if (unmatchedOpeningSquareBrackets <= 0) {
            const numberOfCharsToRemove = url.length - i;
            match[0] = match[0].substr(0, match[0].length - numberOfCharsToRemove);
            url = url.substr(0, url.length - numberOfCharsToRemove);
            break;
    }
        unmatchedOpeningSquareBrackets--;
    }
                
   if (url[i] === '{') { // <- Checking for curly brace
       unmatchedOpeningCurlyBraces++;
   } else if (url[i] === '}') {
       // Unmatched closing curly brace
       if (unmatchedOpeningCurlyBraces <= 0) {
           const numberOfCharsToRemove = url.length - i;
           match[0] = match[0].substr(0, match[0].length - numberOfCharsToRemove);
           url = url.substr(0, url.length - numberOfCharsToRemove);
           break;
   }
       unmatchedOpeningCurlyBraces--;
   }
}
//...
```

<details>

<summary>Short demo after changes</summary>

https://github.com/Expensify/App/assets/79470910/8d63eec6-2c47-4fbd-843f-62a6e0771a92

</details>

### What alternative solutions did you explore? (Optional)

I tried a couple of times to extract the `if` statement that checks for each type of bracket into another method for better readability and organization and then call this method in the `for` loop, but this led to issues.  

```javascript
// An example method
checkBracketType(unmatchedOpeningBrackets, openingBracket, closingBracket, url, match, i) {
   if (url[i] === openingBracket) { 
       unmatchedOpeningBrackets++;
   } else if (url[i] === closingBracket) {
       // Unmatched closing bracket
       if (unmatchedOpeningBrackets <= 0) {
           const numberOfCharsToRemove = url.length - i;
           match[0] = match[0].substr(0, match[0].length - numberOfCharsToRemove);
           url = url.substr(0, url.length - numberOfCharsToRemove);
           break; // <- can't break outside of a loop
   }
       unmatchedOpeningBrackets--;
   }
}
```

The main reason for these issues is the `break` statement that can only be called directly in the `for` loop.  I also tried making this function return a `boolean` value and then use that to decide when the loop breaks, but that didn't work either. 

That's how I arrived at my current solution. Given there are only 3 types of brackets, "`()[]{}`", it should hold up okay the way it is. The solution also works with links wrapped in `<>` (feel free to test it out).

I didn't see any other way of dealing with that `break` statement in an external function.

**Comment by Victor-Nyagudi** [comment] 2023-10-13 08:52
## Proposal

[Updated](https://github.com/Expensify/App/issues/28608#issuecomment-1757812382)

As you can see from the **"What Alternative Solutions Did You Explore?"** section of my initial proposal, I was actively looking for a better way of writing my solution, so I, by no means,  stole what was suggested in this [comment](https://github.com/Expensify/App/issues/28608#issuecomment-1758595952).

It's still good thinking, nonetheless.

**Comment by Victor-Nyagudi** [comment] 2023-10-13 15:45
Friendly bump @aimane-chnaif to review our proposals.

**Comment by Victor-Nyagudi** [comment] 2023-10-16 16:32
@aimane-chnaif I'm a bit confused by your comment.

Does it mean you're investigating special characters that should be in a link? Have you started a conversation in Slack about this issue? Should we update our proposals?

Kindly clarify.

**Comment by t109ct** [comment] 2023-10-17 02:22
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Square bracket does not break the link.
### What is the root cause of that problem?
The root cause is that double quote is being allowed in Url.
but according to [RFC2396](https://datatracker.ietf.org/doc/html/rfc2396), square bracket is not allowed. instead we should use escaped form. And there are other characters other than square bracket.
![image](https://github.com/Expensify/App/assets/86615752/c332c656-98f2-4491-b4a9-380027548c32)
Furthermore, current backend uses escaped form for those characters

### What changes do you think we should make in order to solve the problem?
in [URL_PARAM_REGEX and URL_FRAGMENT_REGEX](https://github.com/Expensify/expensify-common/blob/main/lib/Url.js#L8-L9), we are expected to remove `[,],{,},|`.
```
const URL_PARAM_REGEX = `(?:\\?${addEscapedChar('[-\\w$@.+!*()\\/,=%:;_~]')}*)?`;
const URL_FRAGMENT_REGEX = `(?:#${addEscapedChar('[-\\w$@.+!*(),=%;\\/:~]')}*)?`;
```
also we need some tweaks on auto-test cases to replace those charactors with escaped form.

and we can add following test case for this issue.
```
    const testString = '[http://google.com/?q=test]\n'
    + '{http://google.com/?q=test}\n'
    + '[http://google.com/?q=test|123';
    const result = '[<a href=\"http://google.com/?q=test\" target=\"_blank\" rel=\"noreferrer noopener\">http://google.com/?q=test</a>]<br />'
    + '{<a href=\"http://google.com/?q=test\" target=\"_blank\" rel=\"noreferrer noopener\">http://google.com/?q=test</a>}<br />' +
    + '[<a href=\"http://google.com/?q=test\" target=\"_blank\" rel=\"noreferrer noopener\">http://google.com/?q=test</a>|123';

    expect(parser.replace(testString)).toBe(result);
```

**Comment by Victor-Nyagudi** [comment] 2023-10-19 06:23
@aimane-chnaif This pull request removes special characters at the end of a URL that shouldn't be there. 

- https://github.com/Expensify/expensify-common/pull/575/

It was merged two days ago, but this issue is still reproducible on current staging `v1.3.87-1` and production. 

Kindly take a look at the PR and let me know if it provides you enough [clarity](https://github.com/Expensify/App/issues/28608#issuecomment-1764821392).

I believe the issue we're dealing with here is concerned with matching brackets surrounding a link rather than what special characters are at the end of the URL, but I'd like to hear your thoughts after looking at the merged PR.

**Comment by isabelastisser** [comment] 2023-10-19 15:12
Bump @aimane-chnaif. Can you please follow up on the above? Thanks!

**Comment by isabelastisser** [comment] 2023-10-30 16:06
Hey @aimane-chnaif, are we still holding?

**Comment by Victor-Nyagudi** [comment] 2023-11-01 09:52
@aimane-chnaif The [PR](https://github.com/Expensify/expensify-common/pull/575) was merged over 2 weeks ago, and I can still reproduce the bug in dev, staging, and production.

**Comment by isabelastisser** [comment] 2023-11-02 20:02
@aimane-chnaif can you please provide an update?

**Comment by t109ct** [comment] 2023-11-06 07:53
@aimane-chnaif Did you check my [proposal](https://github.com/Expensify/App/issues/28608#issuecomment-1765552016) ?
here issue is similar to https://github.com/Expensify/App/issues/24367

**Comment by t109ct** [comment] 2023-11-06 08:16
@aimane-chnaif so in url, we should use escaped form, %7B for { and %7D for }

**Comment by Victor-Nyagudi** [comment] 2023-11-06 10:08
@aimane-chnaif I'm going to keep my proposal as-is. 

It still checks out even after testing with your [first](https://github.com/Expensify/App/issues/28608#issuecomment-1794273446) and [second](https://github.com/Expensify/App/issues/28608#issuecomment-1794375096) example. 

Kindly take a look and let me know what you think.

**Comment by isabelastisser** [comment] 2023-11-08 16:00
Hey, @aimane-chnaif, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2023-11-10 18:48
Hey, @aimane-chnaif, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2023-11-13 19:26
@aimane-chnaif, can you please confirm if we're not moving forward with the proposals above and should wait for new proposals?

**Comment by isabelastisser** [comment] 2023-11-16 17:30
@aimane-chnaif, can you please provide an update?

**Comment by isabelastisser** [comment] 2023-11-18 01:41
@aimane-chnaif, can you please provide an update? Should I reassign this issue to another C+? Thanks!

**Comment by situchan** [comment] 2023-11-20 14:08
I can take this over if @aimane-chnaif agrees

**Comment by t109ct** [comment] 2023-11-22 02:01
@situchan 
Did you check my alternative solution https://github.com/Expensify/App/issues/28608#issuecomment-1765552016 ?

Here issue is similar to https://github.com/Expensify/App/issues/24367, where you reviewed

**Comment by isabelastisser** [comment] 2023-11-29 21:32
@situchan bump

**Comment by situchan** [comment] 2023-11-29 21:32
reviewing proposals

**Comment by isabelastisser** [comment] 2023-11-30 20:34
Hey @situchan what do you think of the proposals?

**Comment by isabelastisser** [comment] 2023-12-05 19:06
Bump @situchan

**Comment by situchan** [comment] 2023-12-08 07:28
> @situchan Did you check my alternative solution [#28608 (comment)](https://github.com/Expensify/App/issues/28608#issuecomment-1765552016) ?
> 
> Here issue is similar to #24367, where you reviewed

@t109ct I think your alternative solution is similar to @Victor-Nyagudi's main solution

**Comment by situchan** [comment] 2023-12-08 07:31
Thanks for your patience. I am still testing various edge cases since this will easily cause regressions

**Comment by situchan** [comment] 2023-12-08 08:57
@t109ct did the automated tests pass after applying your `link`, `autolink` changes?

**Comment by Victor-Nyagudi** [comment] 2023-12-11 01:54
Previous C+ [said](https://github.com/Expensify/App/issues/28608#issuecomment-1794375096) we should not escape `[`, `]`. Thoughts, @situchan?

**Comment by situchan** [comment] 2023-12-11 03:16
> Previous C+ [said](https://github.com/Expensify/App/issues/28608#issuecomment-1794375096) we should not escape `[`, `]`. Thoughts, @situchan?

Agree. Need to double confirm with team. Can you also test in all other popular chat platforms?

**Comment by t109ct** [comment] 2023-12-11 03:23
@situchan @aimane-chnaif 
Now backend escapes the chars, Is it ok to have inconsistency with backend ?
![image](https://github.com/Expensify/App/assets/86615752/8dc1b0c5-2e09-4279-8096-8fd0893cc1a8)

**Comment by t109ct** [comment] 2023-12-12 07:35
> If backend escapes, then fine to escape in frontend. We had similar concern in the past regarding email and landed on matching frontend with backend even if backend logic is not perfect

@situchan 
your thoughts ?

**Comment by mountiny** [comment] 2023-12-13 08:53
I am actually thinking if we need to fix this honestly, given the current focus on new releases and features coming to the app this seems like very minor issue the user has easy workaround for.

Additionally we work on live markdown feature which would make this even easier to spot for the user

I think we can close this bug @situchan @isabelastisser

**Comment by isabelastisser** [comment] 2023-12-14 17:58
Sounds good. Closing!

**Closed by isabelastisser** 2023-12-14 17:58 UTC
Labels: Engineering, Daily, Internal, Bug
