### ISSUE TITLE
[$250] The card is flickered when deactivating

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53913] opened 2024-12-11 11:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation** (hyperlinked to channel name): [expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1733907323929729)

## Action Performed:
1. Go to expensify card
2. Issue new card
3. Click on card detail and click deactivate card

## Expected Result:
The card should be removed
## Actual Result:
The card is flickered when deactivating
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/d6c8f1d4-3c1a-474f-b2f0-8dc7546a1dc6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021867023650622164405</li>
        <li>Upwork Job ID: 1867023650622164405</li>
        <li>Last Price Increase: 2024-12-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by DylanDylann** [comment] 2024-12-11 14:34
cc @mountiny @koko57

**Comment by koko57** [comment] 2024-12-11 19:14
I can investigate this issue

**Comment by kadiealexander** [comment] 2024-12-12 01:40
Android <> iOS bug swap with @jliexpensify

**Comment by jliexpensify** [comment] 2024-12-12 01:48
@koko57 - happy to assign to you, I think it personally looks pretty minor 😅

**Comment by koko57** [comment] 2024-12-12 14:07
could repro today but with another screen flickering - after issuing one card I deactivated another one and for a split of a second I saw the Magic Code screen 🤔 

btw the video in the issue is from iOS, I also was able to repro this on the iOS, so the platforms section needs to be updated

**Comment by koko57** [comment] 2024-12-12 14:23
also, when deactivating the card afteer coming from the card list looks slightly different than deactivating when coming from the member's details page


https://github.com/user-attachments/assets/8e66674c-5751-4266-98cf-842d4acf3449


https://github.com/user-attachments/assets/b6837bd9-5175-4f4c-bff6-905140b97cbc

**Comment by koko57** [comment] 2024-12-13 15:49
still investigating

**Comment by koko57** [comment] 2024-12-16 18:53
The only difference I've found is that before navigating back to the cards list page OpenPolicyExpensifyCardsPage is sent, then after navigating OpenPolicyExpensifyCardsPage request is sent two more times (another one thing worth investigating) and then Card_Deactivate req is sent. When deactivating the card from the members page it is navigated back instantly and Card_Deactivate is triggered right away.

**Comment by koko57** [comment] 2024-12-17 14:53
as this was demoted to LOW I will come back to this one later (I really have no idea what's happening here). I will focus on another issue in CRITICAL status https://github.com/Expensify/App/issues/52932

cc @mountiny

**Comment by mountiny** [comment] 2024-12-17 23:42
I think we can close this one for now, I have checked the video again and its super minor

**Closed by mountiny** 2024-12-17 23:42 UTC
Labels: External, Daily, Overdue, Bug
