### ISSUE TITLE
[$500] Inviting someone first time mentioning email does not receive message 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30896] opened 2023-11-05 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.5
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699163020890799

## Action Performed:
1. Open NewDot
2. Create a room
3. Invite new user by mentioning the email

## Expected Result:
User should receive email message to the invited user

## Actual Result:
No email received

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135f955b9d989a1e1</li>
        <li>Upwork Job ID: 1722007006840905728</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-11-07 22:36
@johncschuster this will need to be internal. cc @jasperhuangg

**Comment by jasperhuangg** [comment] 2023-11-07 22:54
I think this is a dupe of something that @marcochavezf is already working on

https://github.com/Expensify/App/issues/30919

**Comment by johncschuster** [comment] 2023-11-10 22:21
Sweet! Thanks for the heads up, @jasperhuangg! I'll put this on hold while we wait on https://github.com/Expensify/App/issues/30919 to be deployed.

**Comment by johncschuster** [comment] 2023-11-22 22:14
Still on hold

**Comment by johncschuster** [comment] 2023-11-29 01:26
Still on hold

**Comment by johncschuster** [comment] 2023-12-04 21:54
Still on hold

**Comment by johncschuster** [comment] 2023-12-07 18:57
Still on hold. Downgrading to `Weekly` while we wait.

**Comment by johncschuster** [comment] 2023-12-15 22:19
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
This is on hold for https://github.com/Expensify/App/issues/30919
No proposals

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by lschurr** [comment] 2023-12-26 20:51
On hold.

**Comment by lschurr** [comment] 2024-01-04 18:16
On hold.

**Comment by lschurr** [comment] 2024-01-12 18:46
On hold.

**Comment by lschurr** [comment] 2024-01-22 17:10
Hold

**Comment by lschurr** [comment] 2024-01-30 20:23
On hold.

**Comment by lschurr** [comment] 2024-02-08 16:10
On hold.

**Comment by lschurr** [comment] 2024-02-16 16:45
Hold.

**Comment by lschurr** [comment] 2024-02-26 16:30
On hold.

**Comment by lschurr** [comment] 2024-03-05 16:47
On hold.

**Comment by lschurr** [comment] 2024-03-13 20:34
On hold.

**Comment by marcochavezf** [comment] 2024-03-14 16:31
https://github.com/Expensify/App/issues/30919 was completed, applying the retest-weekly label

**Comment by lschurr** [comment] 2024-03-19 17:44
Hey @marcochavezf - should this be tied to vip-vsb?

**Comment by marcochavezf** [comment] 2024-03-19 17:51
It should be fixed already, the linked issue is already closed

**Comment by lschurr** [comment] 2024-03-19 17:55
Great. Closing.

**Closed by lschurr** 2024-03-19 17:55 UTC
Labels: Engineering, Weekly, Internal, Bug, retest-weekly
