### ISSUE TITLE
Chat – Sent message chat does not appear on Search until refresh the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37989] opened 2024-03-08 16:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+gm92@applause.expensifail.com
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to FAB> Start chat> Enter email address> Complete new chat flow
3. Send some message to the newly created chat
4. Go to Search and check the search results

## Expected Result:
Newly created chat should be present on the top of the search list

## Actual Result:
Chat does not appear immediately on Search. It appears when refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/794eaa66-c923-4526-a2bb-aac8a47e733e

https://github.com/Expensify/App/assets/78819774/4abff778-51e5-4246-b5ce-1475041fb2fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-08 16:08
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-08 16:08
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by nkdengineer** [comment] 2024-03-11 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat – Sent message chat does not appear on Search until refresh the page
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/d4cacf7acf50910772ea49d41dbd3485b1e1a86f/src/libs/OptionsListUtils.ts#L1478), we get the ```accountIDs``` from ```report.visibleChatMemberAccountIDs```. In this case (open a new report) ```report.visibleChatMemberAccountIDs``` will be ```[ ]```. 
- Then in [here](https://github.com/Expensify/App/blob/d4cacf7acf50910772ea49d41dbd3485b1e1a86f/src/libs/OptionsListUtils.ts#L1510) we early return when ```accountIDs.length``` is ```0```, that leads to the new report is not contained in ```recentReports```.
### What changes do you think we should make in order to solve the problem?
- In [here](https://github.com/Expensify/App/blob/d4cacf7acf50910772ea49d41dbd3485b1e1a86f/src/libs/OptionsListUtils.ts#L1478), beside ```report.visibleChatMemberAccountIDs```, we need to consider ```report.participantAccountIDs```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by dylanexpensify** [comment] 2024-03-11 09:44
Apologies on delay here, team! Was sick all last week. Looking into this now!

**Comment by dylanexpensify** [comment] 2024-03-11 09:53
Not able to reproduce w/needing refresh, just took a second. Going to close this one.

**Closed by dylanexpensify** 2024-03-11 09:53 UTC
Labels: Daily, Bug
