### ISSUE TITLE
[$500] CRITICAL: Show Join button in header when hidden

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33577] opened 2023-12-26 00:22 UTC
**Problem:**
When you open a chat of any kind (eg, room, thread) you generally start out in the `hidden` notification frequency, meaning that you are just "previewing" the chat -- you haven't joined it, and once you leave it, you won't be notified of any updates.  The most straightforward way to join a room is to post.  However, you can also explicitly "join" -- and people often want to do so.  However, our testing suggests that people have had trouble realizing that they hadn't joined, or that it was needed.

**Solution:**
Add a `Join` button to the right side of the header when viewing a room being previewed with with `hidden` notification frequency.  This would look something like this, except with the button merely being `Join` (because this wouldn't just be shown for threads):

![Image](https://github.com/Expensify/App/assets/575186/7d1d271a-b225-43f8-8079-8fbfde3e31ad)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2c22166cbdecd2b</li>
        <li>Upwork Job ID: 1739928998230241280</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28072883</li>
<li>bernhardoj | Contributor | 28072884</li>
</ul></li>
    </ul>
</details>

**Comment by srikarparsi** [comment] 2023-12-27 08:39
Looked into this today and it seems pretty straightforward since we already have the structure setup in the [MoneyReportHeader](https://github.com/Expensify/App/blob/main/src/components/MoneyReportHeader.js#L146) for the button in the header.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/bdaa6366-9224-49c9-931f-818fadf7ce98">
<img width="586" alt="image" src="https://github.com/Expensify/App/assets/48188732/d52d0755-57a7-4190-b67b-17e6904d1e95">

We just have to use a regular button with "Join" and add similar logic from MoneyReportHeader in [HeaderView](https://github.com/Expensify/App/blob/main/src/pages/home/HeaderView.js#L286).

I'm going to make this external since it's purely frontend but will take it back up if there's no progress made by Friday so that it can be done on Monday.

**Comment by srikarparsi** [comment] 2023-12-27 22:52
Hey @abdulrahuman5196, did you have a chance to look at these proposals?

**Comment by abdulrahuman5196** [comment] 2023-12-28 00:58
# Hi, yes will look into it today

**Comment by abdulrahuman5196** [comment] 2023-12-28 17:56
Checking now

**Comment by abdulrahuman5196** [comment] 2023-12-28 18:05
Hi, This seems to be a straightforward feature request. So I think we can go with the first proposal.

But couple of curious questions.

1) What will be the offline case for this? Like would we show the join as greyed or the button being removed
2) Do we have any intimation after pressing the join button, or just the button would go away after pressing? Atleast in other places working now, we would add intimation message to the chat, but that might not be the case here as it seems.

@srikarparsi

**Comment by quinthar** [comment] 2023-12-28 22:17
If the current Join button in the overflow works offline, then this should work offline too.  If it doesn't, don't worry about it.

**Comment by quinthar** [comment] 2023-12-28 22:18
Given that, can you give an ETA for completion?

**Comment by quinthar** [comment] 2023-12-28 22:18
Given that, can you give an ETA for completion?

**Comment by bernhardoj** [comment] 2023-12-29 03:41
I think we can complete it today

cc: @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-12-29 07:20
> If the current Join button in the overflow works offline, then this should work offline too. If it doesn't, don't worry about it.

Got it. Thank you for the information.

**Comment by abdulrahuman5196** [comment] 2023-12-29 07:20
Since this is a feature request, going by with the first comment with considerable information.

@bernhardoj 's proposal here https://github.com/Expensify/App/issues/33577#issuecomment-1870083803 looks good and works well.

🎀 👀 🎀
C+ Reviewed

cc: @srikarparsi

**Comment by bernhardoj** [comment] 2023-12-29 15:39
@srikarparsi Should I work on this now?

**Comment by srikarparsi** [comment] 2023-12-29 18:20
Yes please, that would be great

**Comment by bernhardoj** [comment] 2023-12-30 04:49
PR is ready

cc: @abdulrahuman5196 

@srikarparsi I have a question [here](https://github.com/Expensify/App/pull/33791#issuecomment-1872451540)

**Comment by quinthar** [comment] 2024-01-08 01:30
What is this waiting on?  Who is this waiting on?  I see the above PR has been merged, but I don't see the button in the app.  @srikarparsi @bernhardoj -- what's up?  What's the ETA can we get this fixed -- can we fix it this week?

**Comment by bernhardoj** [comment] 2024-01-08 04:03
> but I don't see the button in the app.

May I know which report you open that you don't see the button?

If it's a thread, the leave/join button will show if the thread has at least one message (other than the thread parent).

If it's a public room, from my testing, you will be automatically joined when you open the room.

**Comment by quinthar** [comment] 2024-01-08 04:21
Why does it only show in a thread if there is at least one chat? Why
wouldn't it always show to anyone who's notification status is hidden?

**Comment by bernhardoj** [comment] 2024-01-08 04:32
I think that behavior was introduced in this [PR](https://github.com/Expensify/App/pull/27748) which was authored by @srikarparsi. I can't access the internal issue, so I don't know why we do that.

**Comment by srikarparsi** [comment] 2024-01-08 04:43
> Why does it only show in a thread if there is at least one chat? Why wouldn't it always show to anyone who's notification status is hidden?

We're fixing that behavior in this [issue](https://github.com/Expensify/App/issues/34054). Here's an [explanation](https://github.com/Expensify/App/issues/34054#issuecomment-1880181436) for why I originally thought we shouldn't be able to join/leave non-existent threads but I also agree that people should be allowed to "join" threads even if they haven't been created yet.

**Comment by quinthar** [comment] 2024-01-21 23:56
What's the latest on this?  What is preventing us from closing this GH right now?

**Comment by srikarparsi** [comment] 2024-01-22 05:31
We can close this out! There's one edge case bug [here](https://github.com/Expensify/App/issues/34649) but we can fix that in that issue. Should be done by this week at the latest.

**Comment by bernhardoj** [comment] 2024-01-22 06:54
@srikarparsi I think we are still waiting for the payment.

**Comment by abdulrahuman5196** [comment] 2024-01-22 18:33
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Feature request.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open a policy room chat
2) Send any message
3) In the message context menu, press "Unsubscribe from the thread" (you are automatically subscribed to your own message)
4) In the message context menu, press "Reply in thread"
5) In the thread chat header, verify there is a "Join" button (on web/desktop, the button is to the left of 3-dot, on mobile devices, the button is below the header title and avatar)
6) Press the "Join" button and verify it disappears
7) Press the 3-dot button and choose "Leave". You will be redirected to parent chat.

@srikarparsi Melvin seems to have not updated this bug. This issue should be up for payment now. Kindly add a BZ member regarding the same.

**Comment by srikarparsi** [comment] 2024-01-23 06:52
Ah sorry! Reopening and adding the BZ label for payment.

**Comment by srikarparsi** [comment] 2024-01-23 06:54
Hey @MitchExpensify! Do you think you could help with paying @abdulrahuman5196 and @bernhardoj for this [PR](https://github.com/Expensify/App/pull/33791) whenever you have a chance?

**Comment by abdulrahuman5196** [comment] 2024-01-30 15:12
@MitchExpensify Could you kindly process payment for this issue?

**Comment by MitchExpensify** [comment] 2024-01-30 23:55
Done! Sorry for the delay

**Closed by MitchExpensify** 2024-01-30 23:55 UTC
Labels: External, Engineering, Daily, Bug
