### ISSUE TITLE
[HOLD for payment 2023-12-29] [Paid] [$500] Web -  I accept checkbox is not aligned with errors

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27703] opened 2023-09-18 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspaces-> bank account -> connect manually
3. Click on Continue
4. Observe that I accept checkbox is not aligned with errors and red dot on the page

## Expected Result:
I accept checkbox should be aligned with errors red dot

## Actual Result:
I accept checkbox is not aligned with errors red dot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (47)](https://github.com/Expensify/App/assets/93399543/e65f74c3-063f-42bd-b1b2-011697411387)
![image (46)](https://github.com/Expensify/App/assets/93399543/49bb6696-232f-48b7-888f-4fed3ce4bbea)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694958144361539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015553e32dfe1adcdf</li>
        <li>Upwork Job ID: 1703830965747298304</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27001512</li>
<li>BhuvaneshPatil | Contributor | 27001514</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-09-18 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
I accept checkbox is not aligned with errors

### What is the root cause of that problem?
we have given `padding: 2px` style for check box, that padding pushes the checkbox a little to right and that's why we are seeing it on right.

### What changes do you think we should make in order to solve the problem?
In order to tackle this issue we shall add new prop to `CheckBoxWithLabel` component - `innerCheckBoxStyle` that we will pass to `CheckBox` component via `style` prop.
In `CheckBox` component -
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/components/Checkbox.js#L94

We need to change the order here (put styles to back)

and pass `paddingLeft: 0px` as `innerCheckBoxStyle` in `BankAccountManualStep`
<img width="857" alt="Screenshot 2023-09-18 at 11 57 19 PM" src="https://github.com/Expensify/App/assets/27822551/df1e3fab-54d2-419b-98df-fb423f8f8822">

### What alternative solutions did you explore? (Optional)

**Comment by iamkunal9** [comment] 2023-09-18 18:30
![Screenshot 2023-09-18 at 11 57 20 PM](https://github.com/Expensify/App/assets/89696700/8f91cd07-c5d2-476a-9c8c-8cfc6964587c)

>?

**Comment by iamkunal9** [comment] 2023-09-18 18:36
Contributor details
Your Expensify account email: kunalsharma0553@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0160b4a00c99ccd2c9

**Comment by fabrianibrahim** [comment] 2023-09-19 01:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
I accept checkbox is not aligned with errors red dot

### What is the root cause of that problem?
the checkbox has extra `padding: 2px` and on top of that we have too much margin left on the label wrapper style `ml3`

### What changes do you think we should make in order to solve the problem?
1. remove `padding: 2px` from `checkboxPressable`
2. change `ml3` in the `PressableWithFeedback wrapperStyle` to `ml2`

**Comment by trjExpensify** [comment] 2023-09-19 11:18
@mollfpr over to you to review!

**Comment by mollfpr** [comment] 2023-09-19 15:02
Removing the `padding: 2` doesn't feel right.

![Screenshot 2023-09-19 at 21 51 03](https://github.com/Expensify/App/assets/25520267/3c89d459-4a40-4c93-badf-32bf969f2610)

The padding is used to give a space between the checkbox and the outline.

![Screenshot 2023-09-19 at 22 01 21](https://github.com/Expensify/App/assets/25520267/65c1a50b-ca3f-4feb-a928-73b458a16d5b)

So any proposal that change the padding of the checkbox will have a regression.

**Comment by alifhaider** [comment] 2023-09-19 18:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Checkbox and Other error texts are not aligned

### What is the root cause of that problem?
For now, checkbox text has `12px marginLeft` and error checkbox has `8px marginLeft`. 
And also the checkbox has a width and height of 20px checkbox w/h, `2px` focus padding, in total `24px` but our `<DotIndicator />` icon has `20px` of width and height

### What changes do you think we should make in order to solve the problem?
We can decrease the checkbox text to `marginLeft: 8px` or increase the error text to `marginLeft: 12px` 

And, also we need to add a wrapper view to add `padding: 2px` to `<DotIndicator />` wrapper view, https://github.com/Expensify/App/blob/7b02afd9191394f3ee20e900315f8d6aa3c445c7/src/components/FormHelpMessage.js#L43-L46
By this height/width of checkbox and `Icon` will be same 24px.

Change with
```
<View style={[styles.errorIconDefault]}> //padding: 2px
                    <Icon
                        src={Expensicons.DotIndicator}
                        fill={themeColors.danger}
                    />
</View>
```

<details><summary>
[Result]
</summary>
<img width="373" alt="Screenshot 2023-09-20 at 12 38 21 AM" src="https://github.com/Expensify/App/assets/33329896/ed140f71-80e6-44d7-8012-a0d368a33e09">
</details>

### What alternative solutions did you explore? (Optional)
Adding padding to the Icon wrapper will make the `Icon` not aligned with the input field. Icon will have extra `2px padding`. Instead we can add `4px of paddingRight` to Icon wrapper view. 

Or, 
We can use `ml4` for to add this extra padding as a margin to the next element. 
https://github.com/Expensify/App/blob/7b02afd9191394f3ee20e900315f8d6aa3c445c7/src/components/FormHelpMessage.js#L48
Change `ml2` to `ml4`
<details><summary>
[Result]
</summary>
<img width="366" alt="Screenshot 2023-09-20 at 12 45 10 AM" src="https://github.com/Expensify/App/assets/33329896/8c9f2d33-35be-44a0-b07f-edf460bc0ebd">

</details>

**Comment by fabrianibrahim** [comment] 2023-09-19 22:03
> Removing the `padding: 2` doesn't feel right.
> 
> ![Screenshot 2023-09-19 at 21 51 03](https://user-images.githubusercontent.com/25520267/268998789-3c89d459-4a40-4c93-badf-32bf969f2610.jpg)
> 
> The padding is used to give a space between the checkbox and the outline.
> 
> ![Screenshot 2023-09-19 at 22 01 21](https://user-images.githubusercontent.com/25520267/269002157-65c1a50b-ca3f-4feb-a928-73b458a16d5b.jpg)
> 
> So any proposal that change the padding of the checkbox will have a regression.

An alternative would be to change the label wrapper style from ml3 to ml1

**Comment by trjExpensify** [comment] 2023-09-20 08:12
Can we get a sense check from @shawnborton or @dannymcclain on what it _should_ be?

**Comment by shawnborton** [comment] 2023-09-21 00:58
Yup, agree with Danny here. The red dots also sit slightly inside of a 20x20 bounding box, so there is a bit of negative space between the dot shape and the outer box. The outer box in this case lines up with the key line shown above.

**Comment by trjExpensify** [comment] 2023-09-21 11:20
Cool, thanks for confirming ya'll!

**Comment by mollfpr** [comment] 2023-09-22 07:50
Thanks, @dannymcclain, for the confirmation. 

@ZhenjaHorbach @fabrianibrahim Please update it to your proposal so that I can review it easily.

@alifhaider I think we are good with the text gap, and adding new padding for the dot indicator will make the text move further away. Also, from Danny's comment [here](https://github.com/Expensify/App/issues/27703#issuecomment-1727995093), the checkbox or other inputs should be sitting exactly on the yellow line, while currently, the checkbox is a few pixels far from the line.

**Comment by mollfpr** [comment] 2023-09-22 10:03
@fabrianibrahim There's no need to post a new proposal. You can update your submission and ping it for review.

**Comment by fabrianibrahim** [comment] 2023-09-22 10:09
> @fabrianibrahim There's no need to post a new proposal. You can update your submission and ping it for review.

updated proposal

**Comment by trjExpensify** [comment] 2023-09-25 11:34
@mollfpr can you review the updated proposals, please?

**Comment by mollfpr** [comment] 2023-09-25 15:05
>We did not set styles so that these elements would be on the same line

@ZhenjaHorbach Could you be more specific on the RCA? Which element is not following the other?

>the label wrapper style has too much margin left ml3

@fabrianibrahim Please be more specific on the RCA. Do you mean the `PressableWithFeedback` on the `CheckboxWithLabel` component? I didn't find your solution is working.

![Screenshot 2023-09-25 at 22 02 39](https://github.com/Expensify/App/assets/25520267/9cc99e5e-b705-40ab-867f-0e5439f4ec44)

@BhuvaneshPatil I think you got the RCA right, but the proposed solution is still not clear to me. Where `innserCheckBoxStyle` will be passed?

**Comment by BhuvaneshPatil** [comment] 2023-09-25 15:55
The reason I went with that approach is, if we add it here and it may cause regression at other places.
But if we want to change the `CheckBoxLabel` component altogether, we shall add that style to `<CheckBox/>` in `CheckBoxLabel` this.
Reason being `CheckBox` is being used as standalone component at other places as well. But `CheckBoxWithLabel` is used with forms where this issue is seen.

**Comment by mollfpr** [comment] 2023-09-25 16:21
@BhuvaneshPatil Change the style from `CheckboxWithLabel` makes sense to me. Could you update your proposal with the above suggestion? I'll give my final thought to the proposal.

**Comment by trjExpensify** [comment] 2023-09-29 10:13
@mollfpr can you review please?

**Comment by mollfpr** [comment] 2023-09-29 10:19
Sorry miss this issue! Doing the review now!

**Comment by mollfpr** [comment] 2023-10-02 14:20
The [proposal](https://github.com/Expensify/App/issues/27703#issuecomment-1724153417) from @BhuvaneshPatil looks good to me! We are adding `padding: 2px` to the checkbox to resolve the issue with the highlight outline notice it [here](https://github.com/Expensify/App/issues/27703#issuecomment-1725824308), and this issue only appears on the `CheckboxWithLabel` component.

🎀 👀 🎀 C+ reviewed!

**Comment by deetergp** [comment] 2023-10-06 16:28
My tardy review was the hold up on this one, I think it should qualify for for the speed bonus.

**Comment by trjExpensify** [comment] 2023-10-17 23:37
👋 @mollfpr checklist time, thanks!

**Comment by mollfpr** [comment] 2023-10-18 02:27
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20997

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/20997/files#r1363029235

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Go to workspaces
2. Open any workspace
3. Click on Bank Account
4. Connect manually
5. Click on text fields and then click outside (this is to show the red dot message)
6. Verify if the checkbox is aligned with the inputs
7. 👍 or 👎



@trjExpensify Could you confirm the amount I requested in NewDot for this issue? Thanks!

**Comment by trjExpensify** [comment] 2023-10-18 19:17
Doing the payment summary for Mills first: 

- $750 to @BhuvaneshPatil for the fix & #urgency bonus 
- $750 to @mollfpr for C+ & #urgency bonus 
- $50 to @dhanashree-sawant for the bug report

**Comment by JmillsExpensify** [comment] 2023-10-18 19:22
$750 payment approved for @mollfpr based on summary above.

**Comment by trjExpensify** [comment] 2023-10-18 19:25
Okay.. as for the regression test. We have one for the connect bank account flow. I think the alignment of the checkboxes on the page is likely under the umbrella of visual design that would be expected to be found within the regression test. 

That said, I'm curious if you think there's something in the PR checklist or forms.md that we could improve @mollfpr to better communicate our expectations for the checkboxContainer on forms given where this bug was introduced?

**Comment by mollfpr** [comment] 2023-10-19 14:08
> That said, I'm curious if you think there's something in the PR checklist or forms.md that we could improve

@trjExpensify It's a good point. I don't know why it's not come up to me 😅

We can have another checklist. For example:

- [ ] If the PR modifies the form input styles:
    - [ ] All the inputs inside a form should be aligned with each other

Adding it in the `FORMS.md` might be easier to miss out.

**Comment by shawnborton** [comment] 2023-10-19 15:50
I would also add to "Add the Design label so the Design team can review your changes" as well :)

**Comment by trjExpensify** [comment] 2023-10-19 23:54
Ohhhh, that's a neat idea. As this is the PR checklist for all PRs are you suggesting that for all or specific to Forms?

**Comment by shawnborton** [comment] 2023-10-20 13:21
I was suggesting to add it as a checkbox below "If the PR modifies the form input styles:"

**Comment by deetergp** [comment] 2023-10-25 07:05
Any update @mollfpr?

**Comment by trjExpensify** [comment] 2023-10-30 10:34
Yes please, @mollfpr!

**Comment by mollfpr** [comment] 2023-10-30 14:15
I'll prepare the PR soon!

**Comment by mollfpr** [comment] 2023-11-01 13:29
@trjExpensify @deetergp The checklist update is ready https://github.com/Expensify/App/pull/30699

**Comment by trjExpensify** [comment] 2023-11-01 14:55
Nice, thanks for getting that up!

**Comment by trjExpensify** [comment] 2023-11-22 02:59
@mollfpr let's get that PR checklist update PR done! Then we can close this.

**Comment by deetergp** [comment] 2024-01-03 06:14
@mollfpr Can you check complete the checklist?

**Comment by trjExpensify** [comment] 2024-01-03 10:52
No need for the second checklist for that, it was a follow-up PR to update the PR checklist. Very meta. Closing now, thanks!

**Closed by trjExpensify** 2024-01-03 10:52 UTC
Labels: External, Weekly, Awaiting Payment, Bug
