### ISSUE TITLE
Profile - Camera icon not centered on profile picture

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20947] opened 2023-06-16 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com
2. Login with any account
3. Go to Settings -> Profile
4. Pay attention to the camera icon near the avatar image

## Expected Result:
The camera icon is centered

## Actual Result:
The camera icon is not centered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6096089_image__116_](https://github.com/Expensify/App/assets/78819774/debf5fbb-f296-484c-92af-d6bd6aa22d97)

![Bug6096089_1606](https://github.com/Expensify/App/assets/78819774/5a312502-9692-428a-a7e3-4a6b007c5a63)

**Expensify/Expensify Issue URL:**

**Issue reported by:**  Applause - Internal Team

**Slack conversation:** Yes

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-16 21:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile Camera icon is not centered on profile picture

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/394a34e1fdc57181942956c9c1c460feb8202f61/src/styles/styles.js#L2738-L2742

This style makes the icon positioned bottom right

### What changes do you think we should make in order to solve the problem?

Change the above style 
```
    smallAvatarEditIcon: {
        position: 'absolute',
        left: '50%',
        top: '50%',
        translate: '-50% -50%',
    },
```

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/fe6569cb-27c1-4971-a87e-3037f2d84d70)

</details>



### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-06-17 18:59
I can reproduce but I don't know if this is a bug - I suspect it's intended to be uncentered so you can see the profile image. 

Asking the team here - https://expensify.slack.com/archives/C01SKUP7QR0/p1687028350865529

**Comment by shawnborton** [comment] 2023-06-19 11:04
I think the icon is actually centered in the icon, it's just that the camera shape itself is slightly downward inside of the icon bounding box:
<img width="551" alt="image" src="https://github.com/Expensify/App/assets/2319350/a723feb5-d5c7-42b6-982f-acff94f5710c">


So this isn't actually a bug. I think we can close this.

**Closed by shawnborton** 2023-06-19 11:04 UTC
Labels: Daily, Bug
