### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Deleted IOU offline disappears after going online if it has already been paid for by another user.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33158] opened 2023-12-15 13:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app or https://staging.new.expensify.com/
2. Log in with separate accounts in the main testing device and a secondary device
3. In the main testing device create an 2 IOU with a user
4. Disable the internet connection in the main testing device
5. On the main test device (offline), cancel one of the sent IOU
6. In the secondary device (online), mark all IOU as paid with the "Pay elsewhere" option.
7. Enable the internet connection in the main testing device
8. On the main device, delete the error "Unexpected error deleting the money request, please try again later" in the IOU report

## Expected Result:
Once the error has been removed, the primary device should display the paid IOU that failed to be removed.

## Actual Result:
Deleted IOU offline disappears after going online if it has already been paid for by another user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/365287d2-bc64-4924-b913-8054641bfa9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fed1ad1953a51e12</li>
        <li>Upwork Job ID: 1735648259511918592</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28096820</li>
<li>bernhardoj | Contributor | 28096822</li>
</ul></li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2023-12-15 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted IOU offline disappears after going online if it has already been paid for by another user
### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/main/src/libs/actions/ReportActions.ts) we only clear errors in the reportAction the pendingAction still delete
So the IOU will hide because this condition
https://github.com/Expensify/App/blob/e23eebe20262439c1eae2d5c7d826cc61652b4ba/src/components/OfflineWithFeedback.tsx#L92
### What changes do you think we should make in order to solve the problem?
We should remove the pendingAction when clear the error message too.

### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-12-15 20:07
Dupe of 26511 
Closing

**Comment by bernhardoj** [comment] 2024-01-03 13:55
@abekkala hi, can you recheck this please? The issue still happens.

**Comment by bernhardoj** [comment] 2024-01-08 15:33
@abekkala bump

**Comment by abekkala** [comment] 2024-01-11 18:54
@hoangzinh is either proposal above sufficient? Do you have feedback for them or do we need different proposals?

**Comment by bernhardoj** [comment] 2024-01-13 04:01
PR is ready

cc: @hoangzinh

**Comment by abekkala** [comment] 2024-01-24 14:37
### PAYMENTS FOR JAN 25

- Issue reported by: Applause - Internal Team
- Fix: @bernhardoj [automatic offer](https://www.upwork.com/nx/wm/offer/28096822) 
- PR Review: @hoangzinh [automatic offer](https://www.upwork.com/nx/wm/offer/28096820)

**Closed** 2024-01-25 21:04 UTC
Labels: External, Weekly, Awaiting Payment, Bug
