### ISSUE TITLE
[$1000] IOS - Chat - Screen blinks if tap "Add attachment" with keyboard up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19917] opened 2023-05-31 23:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS app
2. Open a chat with other user
3. Tap on message input field to bring the keyboard up
4. Tap on "+" icon
5. Tap on "Add attachment"

## Expected Result:
Attachments options menu smoothly appears

## Actual Result:
Screen blinks for a split second with "keyboard up" animation and after that attachments options menu appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a0f8ded8-3a2f-4f39-ad7b-67fa6964e35a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8d735057b4a5045</li>
        <li>Upwork Job ID: 1664165414738194432</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-01 07:01
Reproduced on iOS:

https://github.com/Expensify/App/assets/59587260/52bc8b68-d997-49d5-81ed-bd2adc7abb6b

**Comment by alitoshmatov** [comment] 2023-06-01 10:34
Looks like keyboard is trying to open in between of first popover closing and second opening

**Comment by priyeshshah11** [comment] 2023-06-01 17:04
@kadiealexander Duplicate of https://github.com/Expensify/App/issues/13922

**Comment by johnpaulgrg** [comment] 2023-06-01 17:22
Proposal

I have been working on this issue for a while. The problem arose due to the device registering the state of the keyboard before the modal opens. So, when the modal closed, the keyboard would reopen. Surprisingly, even dismissing the keyboard before closing the modal didn't resolve the problem, primarily because dismissing the keyboard isn't an immediate action - it takes some time to complete.

Therefore, the solution I propose is to monitor the keyboard state before opening the modal. We should only open the modal once the keyboard is fully dismissed. This can be achieved by utilising keyboard listeners. It's worth noting that providing a small delay before opening the modal can lead to inconsistent results across different devices, as the keyboard dismissal time can vary from device to device.

**Comment by thienlnam** [comment] 2023-06-01 17:24
Closing in favor of duplicate over here https://github.com/Expensify/App/issues/13922

**Closed by thienlnam** 2023-06-01 17:24 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by johnpaulgrg** [comment] 2023-06-01 17:26
Contributor details
Your Expensify account email: johnpaulgrg1996@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01adcaacd01525ec75

**Comment by johnpaulgrg** [comment] 2023-06-01 17:27
I have been working on this issue for a while. The problem arose due to the device registering the state of the keyboard before the modal opens. So, when the modal closed, the keyboard would reopen. Surprisingly, even dismissing the keyboard before closing the modal didn't resolve the problem, primarily because dismissing the keyboard isn't an immediate action - it takes some time to complete.

Therefore, the solution I propose is to monitor the keyboard state before opening the modal. We should only open the modal once the keyboard is fully dismissed. This can be achieved by utilizing keyboard listeners. It's worth noting that providing a small delay before opening the modal can lead to inconsistent results across different devices, as the keyboard dismissal time can vary from device to device.
