### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] Delay reconnect callbacks to prevent thundering herd DDOS

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46143] opened 2024-07-24 20:46 UTC
Coming from https://expensify.slack.com/archives/C05CBC62HGW/p1721844511149789

### Problem

When the site is fully offline and comes back up, App web clients DDOS the API. This "thundering herd" :zap::bison: problem occurs because (on web) App considers itself offline if Auth is not reachable. When Auth comes back online, all NewDot clients call ReconnectApp at close to the same time, leading to an artificial surge in traffic right when Auth comes back.

_Note: this does not affect iOS or Android because on those platforms there are native platform APIs for network connectivity information, and we just trust those without considering whether the server is reachable._

### Solution

Update the App network layer to separately track whether internet is reachable, and if the Expensify servers are down. If the server was down and comes back online, add a randomized delay of between 0 and 20 seconds before executing reconnect callbacks to space out the reconnect callbacks across many devices.

To do this, we'll make the following changes:

- Start separately tracking `isInternetReachable` and `isServerReachable`. We can do this by updating the [reachabilityTest](https://github.com/Expensify/App/blob/21a85523fd8bb51555925a21c58ecaba06c3b145/src/libs/NetworkConnection.ts#L113-L121) config of the @react-native-community/netinfo package such that:
    - if [http code is != 200](https://github.com/Expensify/App/blob/21a85523fd8bb51555925a21c58ecaba06c3b145/src/libs/NetworkConnection.ts#L115), internet is down and `isInternetReachable` should be set to false
    - if [jsonCode != 200](https://github.com/Expensify/App/blob/21a85523fd8bb51555925a21c58ecaba06c3b145/src/libs/NetworkConnection.ts#L119) then auth is down, and `isServerReachable` should be set to false
- `isOffline` (the Onyx field) will be updated to be `!isInternetReachable || !isServerReachable`. This is essentially equivalent to what we have today
- Then, we'll address the thundering herd. To do this, we'll update [triggerReconnectionCallbacks](https://github.com/Expensify/App/blob/21a85523fd8bb51555925a21c58ecaba06c3b145/src/libs/NetworkConnection.ts#L27-L36) to add some special handling for a new reason which we can simply call serversStandingUp. If the serversStandingUp reason is provided, then we'll add a random delay of between 0 and 20 seconds (inclusive) before executing reconnection callbacks. This means that in aggregate we'll space out the reconnection callbacks and not all clients will attempt to reconnect at the same time.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f66d59aecc97ac2</li>
        <li>Upwork Job ID: 1816608269060407566</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 103272034</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by roryabraham** [comment] 2024-07-24 20:48
Definitely don't need design support on this one

**Comment by roryabraham** [comment] 2024-07-25 18:27
@ShridharGoel the problem with making this external is that it's not clear how you'd test the server being unreachable (i.e: `Ping` responding with a non-zero jsonCode)

**Comment by roryabraham** [comment] 2024-07-25 19:20
Can you mock responses in the chrome dev tools network tab?

**Comment by wfdong** [comment] 2024-07-26 12:03
Random delay of clients' reconnection should not be the perfect solution, imagine that the amount of clients surge in future - then increase the 20 seconds to 40 seconds? Need to update server side code, e.g. add a message queue(simple FIFO should be ok) to cache the callback reconnections, even you are not using any load balancing it's still ok for the server to just store the reconnection meta data in RAM then process them in asynchronous way(e.g. use a thread pool to traverse and handle these callback reconnections later).

**Comment by roryabraham** [comment] 2024-07-29 17:52
Thanks for your feedback @wfdong. We agree that this solution won't scale forever, and are constantly working to improve the performance and reliability of our back-end. That said, we still think this change will be beneficial to our systems overall and serve us well for the foreseeable future

**Comment by allroundexperts** [comment] 2024-08-11 20:54
@roryabraham I'm not sure on how we can write a regression test for this. Do we need it? If so, can you suggest something? Thanks!

**Comment by sonialiap** [comment] 2024-08-13 08:36
Payment summary:
- @allroundexperts $250 - please request in ND
- @ShridharGoel $250 - paid in upwork ✔️

**Comment by sonialiap** [comment] 2024-08-16 08:54
@roryabraham bumping Sibtain's question about whether we need a regression test and if yes, how it should be written for this issue https://github.com/Expensify/App/issues/46143#issuecomment-2282886844

**Comment by flodnv** [comment] 2024-08-16 09:54
I don't think so, what would it be anyways?

**Comment by sonialiap** [comment] 2024-08-16 12:11
That's the question 😂 Since Flo doesn't think we need one, closing out

**Closed by sonialiap** 2024-08-16 12:11 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment, Bug

**Comment by flodnv** [comment] 2024-08-19 08:43
Ah, I forgot to mention that in the most recent downtime, I've observed that this problem is fixed for now 👍

**Comment by JmillsExpensify** [comment] 2024-10-04 11:11
$250 approved for @allroundexperts
