### ISSUE TITLE
Chat - Focus lost after choosing emoji from EmojPicker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33984] opened 2024-01-04 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Open any chat
4. Open the emoji picker
5. Choose any emoji

## Expected Result:
Focus presents in the composer

## Actual Result:
Focus lost in composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f27bd1f4-39c4-4c46-976a-2a15eac268e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-04 21:43
Production:

https://github.com/Expensify/App/assets/78819774/91cd77d2-aece-43b9-a37b-6ad19addc0dd

**Comment by DylanDylann** [comment] 2024-01-05 01:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - Focus lost after choosing emoji from EmojPicker
### What is the root cause of that problem?
- We have the logic that do not focus on the input composer if we the isPopoverOpen is true:
https://github.com/Expensify/App/blob/095161a690e0cea4cf5352b3d03212530a364fea/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L414-L422
- When we select a emoji, it will call the above focus function but at that time, isPopoverOpen is still true, that leads to the bug.
### What changes do you think we should make in order to solve the problem?
- We can add an additional param, named ```shouldForceFocus``` to the above focus function, if it is true, call the ```focusComposerWithDelay(textInputRef.current)(shouldDelay)``` without considering the ```isPopoverOpen```. Then, once the emoji is selected, call the above focus function with the shouldForceFocus is true

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Pujan92** [comment] 2024-01-06 01:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer isn't focus after selecting an emoji

### What is the root cause of that problem?
On selection of emoji we are hiding the emoji picker but do not execute the `close` method of the PopoverContext which eventually doesn't update the `isOpen` value, due to that `isPopoverOpen` remains true here and it won't focus the composer.

https://github.com/Expensify/App/blob/50f20108cc02a89932df7a96056f0aef07558c1b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L414-L422
https://github.com/Expensify/App/blob/50f20108cc02a89932df7a96056f0aef07558c1b/src/components/EmojiPicker/EmojiPicker.js#L109-L120

### What changes do you think we should make in order to solve the problem?
Use Popover context in the EmojiPicker for close method and call it inside `selectEmoji` function.
https://github.com/Expensify/App/blob/50f20108cc02a89932df7a96056f0aef07558c1b/src/components/EmojiPicker/EmojiPicker.js#L116

**Comment by situchan** [comment] 2024-01-06 01:14
@Pujan92 what's offending PR? https://github.com/Expensify/App/pull/33483 was deployed to production

**Comment by Pujan92** [comment] 2024-01-06 01:19
> @Pujan92 what's offending PR? #33483 was deployed to production

Offending PR is https://github.com/Expensify/App/pull/33483 only bt currently emoji picker by mistake in other PR is opening as modal so we are not able to reproduce at the moment. I will link that in a min.

**Comment by mvtglobally** [comment] 2024-01-07 04:45
still repro on build 1.4.22-2 

https://github.com/Expensify/App/assets/43995119/bf9f711a-d0d0-4e40-86d6-7443375ee30b

**Comment by thienlnam** [comment] 2024-01-08 07:25
Situ is handling as C+

**Comment by situchan** [comment] 2024-01-08 07:38
I agree with https://github.com/Expensify/App/issues/32970#issuecomment-1878204598.
As regression test is already done, revert is safer approach and original [issue](https://github.com/Expensify/App/issues/32970) is not that critical.
I am concerned applying patch will cause another unexpected regression.
@thienlnam what do you think?

**Comment by thienlnam** [comment] 2024-01-08 07:41
Yeah I agree, this is a worse bug than the one the PR intended to fix. I'll just get a revert up for that

**Comment by Pujan92** [comment] 2024-01-08 07:48
@situchan Don't you think calling close method is safer approach as mentioned in [proposal](https://github.com/Expensify/App/issues/33984#issuecomment-1879476323)?

**Comment by thienlnam** [comment] 2024-01-10 03:30
This blocker was fixed in the revert - adding the bug label so we can get payment issued

**Comment by sophiepintoraetz** [comment] 2024-01-10 05:33
@thienlnam - can you confirm it's just $500 to @situchan?

**Comment by thienlnam** [comment] 2024-01-10 05:34
Yes that is correct!

**Comment by DylanDylann** [comment] 2024-01-10 05:36
@thienlnam I proposed the proposal that point out the RCA and solution to revert the PR [here](https://github.com/Expensify/App/issues/33984#issuecomment-1877991807), can you help check

**Comment by thienlnam** [comment] 2024-01-10 05:39
It doesn't look like your comment mentioned the PR that caused the regression - also since we're just reverting code here we're going to have the problem resolved in that PR

**Comment by DylanDylann** [comment] 2024-01-10 05:40
@thienlnam My proposal have 2 sections:

> First, we need to remove the logic that leads to the bug byt updating the above to ...

This is revert the regression PR

And the rest is the solution that will fix the issue that the regression PR try to fix

**Comment by thienlnam** [comment] 2024-01-10 05:43
Yeah but I don't see the regression PR linked in your comment anywhere. 

Additionally, in these scenarios where we revert a recent PR we don't issue payment for just pointing out where it was caused. If we had implemented your other solution that would be a different situation, but it sounds like we decided to just go with a revert here due to other reasons as well listed [here](https://github.com/Expensify/App/issues/32970#issuecomment-1878204598)

**Comment by DylanDylann** [comment] 2024-01-10 05:45
@thienlnam 

> revert here due to other reasons as well listed https://github.com/Expensify/App/issues/32970#issuecomment-1878204598

In the comment you mentioned, the author mentioned my proposal "More info is explained on the https://github.com/Expensify/App/issues/33984#issuecomment-1877991807 there."

Can you help check

**Comment by sophiepintoraetz** [comment] 2024-01-10 06:45
Hey @DylanDylann - we have plenty of opportunities to jump in if you're looking for monetary compensation but as Jack has said, this is a revert - we have not implemented code. If we implement something, I'd keep an eye out on https://github.com/Expensify/App/issues/32970#issuecomment-1878204598.

@situchan - offer sent!

**Closed by sophiepintoraetz** 2024-01-10 06:45 UTC
Labels: Engineering, Daily, Bug

**Comment by DylanDylann** [comment] 2024-01-10 07:00
Thanks @sophiepintoraetz , @thienlnam.
