### ISSUE TITLE
[Hold for #25727][$500] Desktop - Recent chats disappeared from the LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26420] opened 2023-08-31 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Don't logged out with Account A for a while on Desktop
2. Be logged in mobile with the same account
3. Send message from Account B to Account A
4. Open the NewDot app in Desktop 

**Note:** User have unread chat is from mobile notification, but chat is gone from the LHN completely in Desktop. 

## Expected Result:
 Recent chats should be displayed in the LHN

## Actual Result:
 Recent chats disappeared from the LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-08-24 at 12 20 08 PM](https://github.com/Expensify/App/assets/93399543/2aea6760-78b6-49e8-84e3-ec35675c0104)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692904986751459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad8b9a99977a1cd2</li>
        <li>Upwork Job ID: 1699301241160323072</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-09-01 02:58
I'm a bit stumped on repro'ing this one, have reached out to Rafe in Slack for some help with it.

**Comment by kadiealexander** [comment] 2023-09-04 03:12
@rafecolton is going to try help with repro-ing this week.

**Comment by rafecolton** [comment] 2023-09-04 21:59
Looks like @danieldoglas might have figured it out [here](https://expensify.slack.com/archives/C049HHMV9SM/p1693847048569379?thread_ts=1693843397.704839&cid=C049HHMV9SM)

**Comment by kadiealexander** [comment] 2023-09-05 03:40
Ah awesome, good catch!

**Comment by danieldoglas** [comment] 2023-09-05 14:28
We still need someone to fix this, I think it can be external!

**Comment by kadiealexander** [comment] 2023-09-06 05:59
Alright, proceeding even though I can't reproduce, trusting you guys! :D

**Comment by danieldoglas** [comment] 2023-09-11 08:35
@bernhardoj do you wanna do a proposal on that? I think the point is that we need to check the message property in the report itself too, not only the report actions. If we have a message on the report, then it should also be shown in the LHN

**Comment by kadiealexander** [comment] 2023-09-12 04:11
@danieldoglas @PauloGasparSv any thoughts?

**Comment by danieldoglas** [comment] 2023-09-12 04:38
From my understanding, that comment on the slack discussion that comment is referring to means:

- If lastMessage/lastMessageHtml is empty, then the only fallback possible is `reportActionCount`. 



We can also do it differently:

- Check if reportActionCount is empty. If it's not, do what we do today
- if it is, check if the properties lastMessageHtml/lastMessage are empty. if they are, hide the chat.
- If not, show them.

Does that make sense @bernhardoj ?

**Comment by danieldoglas** [comment] 2023-09-15 05:41
The root cause for this is the same as https://github.com/Expensify/App/issues/25727, which is older. We should HOLD this issue on that PR and test again after merging it.

**Comment by peterdbarkerUK** [comment] 2023-09-15 09:39
I experienced this too, though for web rather than desktop. Some screenshots:

![image](https://github.com/Expensify/App/assets/16888060/a3e92172-0f29-49bd-af45-cc3d3d3ad50b)
<img width="523" alt="image" src="https://github.com/Expensify/App/assets/16888060/d080878e-88ac-4a9e-b9b7-7faf18c81a48">
![image](https://github.com/Expensify/App/assets/16888060/bdb6e193-7246-4dd3-a113-16a4d8e13774)
<img width="581" alt="image" src="https://github.com/Expensify/App/assets/16888060/9195d4dc-bd79-4de5-8ac9-8c70884147f9">

This is disrupting communications without warning if it fails - let's treat with urgency :)

**Comment by kadiealexander** [comment] 2023-09-18 03:37
Appreciate your screenshots, Peter! As Daniel said this is likely to be fixed with https://github.com/Expensify/App/issues/25727 so it's on hold until that's done. 😊

**Comment by kadiealexander** [comment] 2023-09-27 05:41
@peterdbarkerUK @rafecolton are you guys still experiencing this one? The related issue that should hopefully fix this is now done :)

**Comment by kadiealexander** [comment] 2023-10-06 03:34
Closing for now, please reopen if this comes back!

**Closed by kadiealexander** 2023-10-06 03:34 UTC
Labels: External, Weekly, Overdue, Bug
