### ISSUE TITLE
[$500] Chat -  App allows to open any invalid email profile details using mention URL

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28191] opened 2023-09-25 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write any user mention and send
4. Click on mention and copy the URL
5. Paste URL in compose box and remove or replace parts after 'login=' to make the email invalid eg: https://staging.new.expensify.com/details?login=abcd
6. Send the URL and click on it
7. Observe that instead of displaying 'Hmm its not here', app creates profile for invalid contact user

## Expected Result:
App should display 'Hmm its not here' page when we try to open invalid contact profile details using mention URL

## Actual Result:
App allows to open any invalid contact profile details on using mention URL structure

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/65cc0ebc-113b-41d8-9a3c-94ccb888dd1e

https://github.com/Expensify/App/assets/115492554/4a11b84b-7c15-4d55-bc42-99ea3d127d45

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695485451642119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016acedce6ab891123</li>
        <li>Upwork Job ID: 1706398446874087424</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-09-25 20:01
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Invalid logins also are displayed in details page when the url is edited
### What is the root cause of that problem?
We are not checking if the `login` parameter from url is a valid email or phone number in `DetailsPage` at
https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/DetailsPage.js#L130
to show `FullPageNotFoundView`.
### What changes do you think we should make in order to solve the problem?
We should get the login param from the url and check if it is a valid phone or email by adding 
```js
const parsedPhoneNumber = parsePhoneNumber(login);
```
and modifying this condition to the `FullPageNotFoundView` in the `DetailsPage`
```js
<FullPageNotFoundView shouldShow={_.isEmpty(login) || (!parsedPhoneNumber?.possible && !Str.isValidEmail(login))}>
```
We are using `parsePhoneNumber` and `Str.isValidEmail` separately to validate the email or phone in several pages. We might consider making a function to check both.
### What alternative solutions did you explore? (Optional)

**Comment by izarutskaya** [comment] 2023-09-25 20:02
## Proposal from @dhanashree-sawant
### Please re-state the problem that we are trying to solve in this issue.
We are solving the problem of app allowing to open profile details of invalid contact using mention result
### What is the root cause of that problem?
On `DetailsPage` we don't have any check to determine whether provided contact is valid or not
### What changes do you think we should make in order to solve the problem?
Add new boolean which will check whether contact is valid contact or not and pass it in `shouldShow` parameter of `FullPageNoFoundView` to display 'Hmm its not here' page for invalid contact on `DetailsPage`
We can do that by adding new boolean [here](https://github.com/Expensify/App/blob/f0c9bbe553f914d9135ec310f9c08aa6ae2d4577/src/pages/DetailsPage.js#L127)
```
const isValidContact = Str.isSMSLogin(details.login) || Str.isValidEmail(details.login) ? true : false;
```
Assign that boolean to `FullPageNoFoundView` `shouldShow` parameter [here](https://github.com/Expensify/App/blob/f0c9bbe553f914d9135ec310f9c08aa6ae2d4577/src/pages/DetailsPage.js#L130C1-L130C1)
```
<FullPageNotFoundView shouldShow={_.isEmpty(login) || !isValidContact}>
```
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-25 22:17
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Invalid logins also are displayed in details page when the url is edited
### What is the root cause of that problem?
We are not checking if the `login` parameter from url is a valid email or phone number in `DetailsPage` at
https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/DetailsPage.js#L130
to show `FullPageNotFoundView`.
### What changes do you think we should make in order to solve the problem?
We should get the login param from the url and check if it is a valid phone or email by adding 
```js
const parsedPhoneNumber = parsePhoneNumber(login);
```
and modifying this condition to the `FullPageNotFoundView` in the `DetailsPage`
```js
<FullPageNotFoundView shouldShow={_.isEmpty(login) || (!parsedPhoneNumber?.possible && !Str.isValidEmail(login))}>
```
We are using `parsePhoneNumber` and `Str.isValidEmail` separately to validate the email or phone in several pages. We might consider making a function to check both.
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-09-26 06:38
> `DetailPage` will be deprecated in the feature so I think we should close this now.

@dukenv0307 can you share link to that discussion?

**Comment by dhanashree-sawant** [comment] 2023-09-26 06:51
Didn't we decide to not show the page for optimistic users only?

**Comment by situchan** [comment] 2023-09-26 06:52
We're close to accountID based mention implementation, which means Details page will be deprecated soon.
So I think we can just do nothing and close this issue for now.

**Comment by johncschuster** [comment] 2023-09-26 18:03
Thanks, @situchan! In that case, I'll go ahead and close the issue. If anyone disagrees, feel free to argue your case!

**Closed by johncschuster** 2023-09-26 18:03 UTC
Labels: External, Daily, Help Wanted, Bug
