### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] Chat - Blue outline appears for a moment on + icon, selecting an option from popover menu and hit enter using keyboard Reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11433] opened 2022-09-29 18:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to a chat
2. Click on Actions
3. Press up arrow to go to send money
4. Press enter

## Expected Result:
There shouldn't be any blue outline at Plus icon at the left side of the composer

## Actual Result:
Blue outline shows up

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193110760-dad4ad0b-0b53-488c-86be-17a2245c4ab8.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663327310429239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-09-30 00:51
@Puneet-here @kavimuru , I watched both vids, where exactly is the blue line I'm looking for?

**Comment by Puneet-here** [comment] 2022-09-30 06:43
> watched both vids, where exactly is the blue line I'm looking for?

The blue outline at Plus icon at the left side of the composer

**Comment by mallenexpensify** [comment] 2022-09-30 19:44
Thanks @Puneet-here , I updated to the OP to inc. `blue outline at Plus icon at the left side of the composer`
@madmax330 , 99% sure this can be external.

**Comment by Puneet-here** [comment] 2022-09-30 19:48
Sorry for the late comment but it also happens for the fab icon. When we select an option from arrow keys and press enter

**Comment by NicMendonca** [comment] 2022-10-03 10:52
Job posting: https://www.upwork.com/jobs/~019538bb8e1b278a87

**Comment by thesahindia** [comment] 2022-10-07 14:34
@MarkCSmith, is there any reason that the blue outline only shows up  when popover menu gets closed after pressing some key?

I found that when you open a popover menu let's say call option (at top right) and press some key now when you close the popover the blue outline will be shown. You can click somewhere to close the popover menu or you can just press enter. 
For emoji button we use Pressable and when you press enter to select an emoji then the blue outline show at emoji button.

I think we should fix all the cases here.

**Comment by thesahindia** [comment] 2022-10-07 14:38
@NicMendonca, let's reassign @roryabraham here, they got unassigned accidentally.

**Comment by MarkCSmith** [comment] 2022-10-07 17:51
> is there any reason that the blue outline only shows up when popover menu gets closed after pressing some key?

In testing on iOS 15 with the web app (in Safari), my colleague and I see the blue outline if we just open and close the action menu by tapping (no keyboard involved).  When we use the emoji picker we don't see the blue focus ring at all, but that is because of the following code in `pages/home/report/ReportActionCompose.js` which returns focus to the text input field after the emoji picker modal is hidden:
```
<EmojiPickerButton
    isDisabled={isBlockedFromConcierge}
    onModalHide={() => this.focus(true)}
    onEmojiSelected={this.addEmojiToTextBox}
/>
```
But it seems that the behavior varies based on web browser and platform.  Where are you doing your testing?  Maybe the focus() implementation needs a longer delay on some platforms (currently, when `true` is passed as in the code above it delays the text input focus() call for 100 milliseconds).

> I think we should fix all the cases here.

OK, although I am not sure how to avoid the blue focus rings in browsers like Safari except by either (1) making the items not focusable, which will impair accessibility for keyboard users or (2) removing focus as in our proposal.  That means we need to handle each on a case-by-case basis.

**Comment by thesahindia** [comment] 2022-10-07 21:19
> In testing on iOS 15 with the web app (in Safari), my colleague and I see the blue outline if we just open and close the action menu by tapping (no keyboard involved).

Yeah we have a different issue for this but that's only reproducible on safari and the issue we wanna deal here is reproducible on desktop and web(all browsers).  

> Where are you doing your testing?

I am on mac and using chrome browser.

> OK, although I am not sure how to avoid the blue focus rings in browsers like Safari except by either (1) making the items not focusable, which will impair accessibility for keyboard users or (2) removing focus as in our proposal. That means we need to handle each on a case-by-case basis.

@roryabraham, any thoughts?

**Comment by roryabraham** [comment] 2022-10-07 22:18
I'm fine with handling this on a case-by-case basis and accepting the small amount of extra complexity to try and keep a semblance of accessibility, but it's also worth noting that our app is unfortunately currently almost completely unusable to visually impaired users that rely on screen readers. 😞

**Comment by thesahindia** [comment] 2022-10-10 18:29
I have to investigate this a little bit.

**Comment by MarkCSmith** [comment] 2022-10-10 19:53
> I'm fine with handling this on a case-by-case basis and accepting the small amount of extra complexity to try and keep a semblance of accessibility, but it's also worth noting that our app is unfortunately currently almost completely unusable to visually impaired users that rely on screen readers. 😞

Fair enough.  The web browser will give focus to any clicked element that has a `tabindex` attribute.   React Native Web always adds those attributes to clickable/tappable items such as `Pressable`, and my colleague and I do not know a way to prevent those attributes from being added.  Calling `blur()` as we proposed should work for the action button, emoji picker, and video chat button.  In fact, my colleague and I did a little testing and calling `blur()` in the correct places fixes the problem for each of those "buttons."

**Comment by roryabraham** [comment] 2022-10-19 06:42
Yep, sounds fine to me 👍🏼

**Comment by MarkCSmith** [comment] 2022-10-19 21:11
@roryabraham Thanks!  I applied on UpWork and I should have a PR ready on Friday, 21 October 2022.

**Comment by MarkCSmith** [comment] 2022-10-22 03:18
> @roryabraham Thanks! I applied on UpWork and I should have a PR ready on Friday, 21 October 2022.

I am sorry I am going to miss this deadline.  Hopefully I can post the PR on Monday (still working on testing and the PR template; this is my first time doing all those things).

**Comment by thesahindia** [comment] 2022-10-22 06:33
No problem. Feel free to ask questions if you get stuck on something.

**Comment by roryabraham** [comment] 2022-10-31 16:51
[PR](https://github.com/Expensify/App/pull/12090) is awaiting C+ review

**Comment by arielgreen** [comment] 2022-11-03 20:22
Hey @roryabraham , can you prioritize getting review completed today? Let's [keep the momentum up](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) to get this one closed out!

**Comment by NicMendonca** [comment] 2022-11-07 13:27
bump @roryabraham 🙏

**Comment by johncschuster** [comment] 2022-11-10 19:37
Just catching up on this! It looks like we're waiting on a final review from you, @roryabraham. Can you prioritize reviewing this PR so we can close this one out?

**Comment by roryabraham** [comment] 2022-11-12 20:48
Sorry for missing these pings and taking a while to come back around to this PR. I approved it, but there are conflicts that need to be resolved.

This is my bad - I'll be sure to keep up the urgency better once the PR is updated so that we can close this out

**Comment by MarkCSmith** [comment] 2022-11-15 16:30
> This is my bad - I'll be sure to keep up the urgency better once the PR is updated so that we can close this out

Thanks.  I updated the PR.

**Comment by roryabraham** [comment] 2022-11-19 01:46
Just waiting on production deploy + payout now

**Comment by thesahindia** [comment] 2022-11-22 08:08
Not overdue, PR is on staging.

**Comment by roryabraham** [comment] 2022-12-01 22:50
bump @johncschuster for payment + regression test considerations

**Comment by johncschuster** [comment] 2022-12-01 23:26
Working on payment now. 👍

**Comment by johncschuster** [comment] 2022-12-01 23:33
I had to recreate the job. 

@MarkCSmith and @thesahindia, can you please apply to the job, [here?](https://www.upwork.com/jobs/~01a463a776fd3c76bb) 

Thanks!

**Comment by MarkCSmith** [comment] 2022-12-02 14:58
> I had to recreate the job.
> 
> @MarkCSmith and @thesahindia, can you please apply to the job, [here?](https://www.upwork.com/jobs/~01a463a776fd3c76bb)

I will, but I must admit that this process has not been smooth as I hoped.  I would feel better if the new $1000 minimum was in effect....

**Comment by dragonboltmaster** [comment] 2022-12-02 16:33
I think the problem is in the CSS. I would add this property to the element:

`
-webkit-tap-highlight-color: transparent;
`

**Comment by roryabraham** [comment] 2022-12-05 18:29
My apologies again @MarkCSmith on the review delay that caused some conflicts to arise.

**Comment by johncschuster** [comment] 2022-12-08 22:20
Thanks for the bump, @roryabraham!

@MarkCSmith and @thesahindia have been paid!

@Puneet-here, I almost missed you. I've invited you to the [job on Upwork](https://www.upwork.com/jobs/~014264899523c0b568). Can you accept that so I can pay you for reporting the issue? Thanks!

**Comment by Puneet-here** [comment] 2022-12-09 06:06
> @Puneet-here, I almost missed you. I've invited you to the [job on Upwork](https://www.upwork.com/jobs/~014264899523c0b568). Can you accept that so I can pay you for reporting the issue? Thanks!

Applied, thanks!

**Comment by johncschuster** [comment] 2022-12-09 16:06
Thanks, @Puneet-here! Once you accept my offer in Upwork I'll get you taken care of. 👍

**Comment by Puneet-here** [comment] 2022-12-09 20:08
> Thanks, @Puneet-here! Once you accept my offer in Upwork I'll get you taken care of. 👍

Accepted!

**Comment by roryabraham** [comment] 2022-12-10 01:45
@Puneet-here I went ahead and paid out that contract on Upwork since @johncschuster is probably out for the weekend. Closing this out

**Closed by roryabraham** 2022-12-10 01:45 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by johncschuster** [comment] 2022-12-12 23:45
Thanks for taking care of that, @roryabraham!
