### ISSUE TITLE
[HOLD for payment 2023-06-15] [$1000] When clicking on Reply in thread "No activity yet" displayed briefly in LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19349] opened 2023-05-20 19:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a workspace chat (such as #announce)
2. Send a message and click on "Reply in Thread"

## Expected Result:
When clicking on "Reply in thread", the message "No activity yet" should not be displayed in the LHN
## Actual Result:
When clicking on "Reply in thread", the message "No activity yet" is displayed briefly in the LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3f21bb97-5250-4d04-99b1-316eda29ff72

https://github.com/Expensify/App/assets/43996225/8bd22358-79f1-417f-8f53-2be50990aacb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684360708416189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4c99b61a36e2397</li>
        <li>Upwork Job ID: 1663577991745347584</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-22 09:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"No activity yet" displayed for a while in LHN
### What is the root cause of that problem?
If the report is a thread within a workspace, we will show the subtitle as the second line instead of in a pill
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/components/LHNOptionsList/OptionRowLHN.js#L85
`subtitle` is returned by `getChatRoomSubtitle` function
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/SidebarUtils.js#L253
When we create a new thread, we build an `OptimisticChatReport` with `chatType` is `''`
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/actions/Report.js#L455-L467
That make  `getChatRoomSubtitle` returns `''` while `alternateText` is `report.noActivityYet`. So that "No activity yet" displayed for a while in LHN
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/ReportUtils.js#L488
But after API return data, `chatType` of new thread created above is the same parentReport. And then, with `chatType` is  different `''` `getChatRoomSubtitle` the subtitle will follow the pattern `'Workspace Name • #roomName'`.
Thus the issue occurs.
### What changes do you think we should make in order to solve the problem?
1. In `ReportActionItem`, we need to pass `reportID` into `ReportActionItemThread`
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/report/ReportActionItem.js#L312
2. When call `navigateToAndOpenChildReport` in `ReportActionItemThread`, we should pass `props.reportID` as `parentReportID` parameter:  `Report.navigateToAndOpenChildReport(props.childReportID, {}, props.reportID);`
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/report/ReportActionItemThread.js#L44
3. In `navigateToAndOpenChildReport` function we shoud get `chatType` of parentReport with `parentReportID` and then we create a `OptimisticChatReport` with this `chatType` instead of `''`
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/actions/Report.js#L458
### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment] 2023-05-30 12:29
I have reproduced this even without sending a message in the #announce room. It seems that just starting a new thread is enough to add a new item to the LHN with the verbiage "No activity yet"

**Comment by amyevans** [comment] 2023-05-30 16:07
I reproduced locally. Going to mark this as `External`.

cc @chiragsalian @grgia @stitesExpensify (threads folks) in case you have any additional context to add for this issue 😄

**Comment by qandeelabbassi** [comment] 2023-05-30 21:03
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
"No activity yet" displayed for a while in LHN

### What is the root cause of that problem?
The subtitle is being assigned using the following code:

https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/components/LHNOptionsList/OptionRowLHN.js#L85

The `optionItem.subtitle` in the above line comes from the following function which sets subtitles based on `chatType`:
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/SidebarUtils.js#L253

The problem is that while the API call is in progress the chat Report's `chatType` is empty `''`. This causes the `getChatRoomSubtitle` to return an empty string `''`. Hence the `OptionRowLHN.js#L85` returns `alternativeText` which is by default set to "No activity yet"

### What changes do you think we should make in order to solve the problem?
While the API call is in progress we could use parent report chatType so that `OptionRowLHN.js#L85` returns the actual subtitle. Here are the steps to get the parent report Id and then get its chatType while initializing newChat
1. In `ReportActionItem`, we need to pass `this.props.report.reportID` into `ReportActionItemThread` as a separate prop
   https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/report/ReportActionItem.js#L312
2. Once we have the parent report Id we will pass it to `navigateToAndOpenChildReport` call inside ReportActionItemThread's onPress callback. 
   https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/report/ReportActionItemThread.js#L44
3. In `navigateToAndOpenChildReport` function we can get parent report from allReports using parentReportID. And then we pass parent report's chatType to newChat:
   https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/actions/Report.js#L458

**Comment by qandeelabbassi** [comment] 2023-05-30 21:07
Contributor details
Your Expensify account email: qandeel@codeclever.tech
Upwork Profile Link: https://www.upwork.com/freelancers/~017a93b981a238f3ec

**Comment by abdulrahuman5196** [comment] 2023-06-02 15:11
Reviewing today

**Comment by abdulrahuman5196** [comment] 2023-06-04 19:39
@dukenv0307 Why do we consider changes in `ReportActionItemThread`, because this component itself will only be displayed when there are threads present in the message i.e an already created thread.

But the issue mentioned only happens on new thread creation. Kindly check and update the proposal accordingly.

**Comment by abdulrahuman5196** [comment] 2023-06-04 19:40
@qandeelabbassi https://github.com/Expensify/App/issues/19349#issuecomment-1569100032 this proposal is same as @dukenv0307's proposal here - https://github.com/Expensify/App/issues/19349#issuecomment-1556909085

**Comment by qandeelabbassi** [comment] 2023-06-04 20:44
@abdulrahuman5196 you are correct. Upon investigating further, the new report is being created via the context menu option in ContextMenuActions:
https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/home/report/ContextMenu/ContextMenuActions.js#L117

We only need to make changes in `Report.navigateToAndOpenChildReport` function by getting parent report from allReports (using parentReportID). And then we pass the parent report's chatType to newChat. I have updated my proposal accordingly

**Comment by abdulrahuman5196** [comment] 2023-06-05 16:19
@dukenv0307's  proposal looks good. I tested and its working for '#announce' kind of chats. And we would also need the workspace chats fix as well.

🎀👀🎀
C+ Reviewed

cc: @amyevans

**Comment by abdulrahuman5196** [comment] 2023-06-08 17:32
BugZero Checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. It is a miss during the original threads implementation.

>Determine if we should create a regression test for this bug.

yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open a workspace chat (such as #announce)
2) Send a message and click on "Reply in Thread"
3) In LHN corresponding to the new thread, it should show the `{workspace name} • {chat name}` as a subtitle.

**Comment by johncschuster** [comment] 2023-06-12 11:29
@puneetlath I think you mentioned there's a suite of tests coming for threads, right? In that case, should I create a regression test for this issue, or will ^this flow be considered?

**Comment by puneetlath** [comment] 2023-06-12 13:16
I'm not sure about threads. That would be a question for @chiragsalian or @stitesExpensify.

**Comment by johncschuster** [comment] 2023-06-13 13:48
Oh sorry! You spearheaded mentions! I got mixed up.

@chiragsalian / @stitesExpensify, what are your thoughts?

**Comment by grgia** [comment] 2023-06-14 15:33
I think we can close this. Should be solved by https://github.com/Expensify/App/issues/19205

**Comment by abdulrahuman5196** [comment] 2023-06-14 15:50
Actually the solution was pushed, we are only confirming on the regression test at this stage. If this issue shouldn't arise due to the future implementation at #19205 , we won't need regression test anyways.

**Comment by stitesExpensify** [comment] 2023-06-14 17:33
Agreed, I don't think that we need to add regressions

**Comment by chiragsalian** [comment] 2023-06-14 17:59
I think we can add a regression test that will be applicable even after georgia's code is implemented. Like so,
1. Open a workspace chat (such as #announce)
2. Send a message and click on "Reply in Thread"
3. Add a message in the thread.
4. In LHN corresponding to the new thread, it should show the {workspace name} • {chat name} as a subtitle.

**Comment by abdulrahuman5196** [comment] 2023-06-20 12:36
@johncschuster Could you kindly process the payments for this issue? It has been pending for couple of days.

**Comment by johncschuster** [comment] 2023-06-20 15:47
@abdulrahuman5196 Sorry about that! I'll work on that now.

**Comment by abdulrahuman5196** [comment] 2023-06-20 15:58
@johncschuster Thank you. Applied in the upwork.

**Comment by ayazhussain79** [comment] 2023-06-20 16:02
Applied for bug reporting

**Comment by johncschuster** [comment] 2023-06-21 14:50
Great! I've got offers out to all three of you! Please ping me when those have been accepted so I can issue payment.

Thank you!

**Comment by abdulrahuman5196** [comment] 2023-06-21 14:52
@johncschuster  accepted

**Comment by johncschuster** [comment] 2023-06-21 15:28
@ayazhussain79 Ugh... sorry. I'll see if I can fix that.

**Comment by johncschuster** [comment] 2023-06-22 14:11
Ugh, I don't think I'll ever understand Upwork's UI. I think I accidentally blocked @dukenv0307 as well. 🤦 

I'm going to spin up an issue for payment so I can get this sorted.

**Comment by abdulrahuman5196** [comment] 2023-06-22 14:31
Anything i am required to do? The old job itself is hired for me

**Comment by johncschuster** [comment] 2023-06-23 15:33
Thanks for the ping @abdulrahuman5196! Nope! I don't see anything else you need to do here. I'll get payment issue now for you.

**Comment by johncschuster** [comment] 2023-06-23 15:41
No problem!

**Comment by ayazhussain79** [comment] 2023-06-23 15:55
@johncschuster offer accepted

**Comment by johncschuster** [comment] 2023-06-26 16:23
Ok! Payment has been issued! Closing!

**Closed by johncschuster** 2023-06-26 16:23 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
