### ISSUE TITLE
Web - Workspace - Message sent from admin in the workspace chat does not appear in employee account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12015] opened 2022-10-19 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login with expensifail account
2. Create a workspace
3. Invite another member that you have access to
4. Send messages from admin to workspace chat with employee and to #announce room
5. Switch employee account

## Expected Result:
Employee account should see messages in workspace chat and in #announce room.

## Actual Result:
Workspace chat is not displayed, message is missing. Only message in #announce room is displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196813330-d650631d-4e2b-436d-8d6b-f6dc9c87801d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-10-20 13:33
I couldn't simulate this. @kbecciv can you please try again? Maybe it's related to the period we were deploying things for PHP 8.1 and it was unstable

https://user-images.githubusercontent.com/5818999/196962827-76a25f84-2c9d-4b03-a6ee-e7718ca158cb.mov

**Comment by kbecciv** [comment] 2022-10-20 16:17
@danieldoglas If user is created a workspace under expensifail account, but invited gmail account - we are facing reported issue
.
With both expensifail accounts it is different. It appears 2 workspace chats: one with the name of workspace, and the other one is with the name of added member.
Message sent to chat displayed with new member name is delivered but displayed as a chat with workspace name.
Workspace chat has only 1 member and message is not delivered.

![chats](https://user-images.githubusercontent.com/93399543/197003366-a7668432-a6b0-4201-912e-39252f01cfb0.jpg)

https://user-images.githubusercontent.com/93399543/197003370-b1a6f2d7-8363-4dd7-9e66-43df8aabfac1.mp4

**Comment by danieldoglas** [comment] 2022-10-25 11:57
This will be an internal issue. Still don't know what it is but it is probably in the API layer

**Comment by Justicea83** [comment] 2022-10-31 08:55
Could not reproduce this even using a `gmail` account

<img width="1235" alt="Screenshot 2022-10-31 at 8 54 28 AM" src="https://user-images.githubusercontent.com/26106822/198969595-f792c3e7-dab2-48d0-908d-654df10ac8e0.png">

**Comment by CortneyOfstad** [comment] 2022-11-02 11:26
Just got assigned to me yesterday melvin-bot 😑😂 Looking at this today!

**Comment by CortneyOfstad** [comment] 2022-11-03 12:07
I cannot reproduce this either under an expensicorp.com account

[2022-11-03_07-02-31 (1).gif.zip](https://github.com/Expensify/App/files/9928129/2022-11-03_07-02-31.1.gif.zip)

Can we confirm that this is still happening?

**Comment by michaelhaxhiu** [comment] 2022-11-03 17:33
Seems @Justicea83 and @CortneyOfstad are both having issues reproducing. If this can't be reproduced in the next few days, I recommend closing it. 

If you can reproduce, I recommend applying `demolition` label to get someone assigned and accountable to seeing it through.

**Comment by CortneyOfstad** [comment] 2022-11-07 13:06
@kbecciv Can we confirm if this is still being reproduced, as both Justice and I could not reproduce this ourselves.

**Comment by mvtglobally** [comment] 2022-11-09 03:40
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2022-11-10 13:53
Okay, going to close this as it is not reproducible. We can reopen if that changes, or a new proposal can be created 👍

**Closed by CortneyOfstad** 2022-11-10 13:53 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
