### ISSUE TITLE
[$250] Assign Task - When changing Assignee, the page lags when closing modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43410] opened 2024-06-10 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify App
2. Sign into a valid account (HT account is better for reproduction)
3. Create a Task and then click on the IOU
4. Change the Assignee and notice the page closing.

## Expected Result:
User expects the page to close "clean"

## Actual Result:
The page has a slight "lag/Delay" when closing, visible for a couple of seconds.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2c655493-f95d-4e0a-99f7-be2a7c0d4bba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01794355bb64abf4a9</li>
        <li>Upwork Job ID: 1800741657347973622</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103151963</li>
<li>truph01 | Contributor | 103151965</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment] 2024-06-10 17:49
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-06-12 04:07
I'll open it up to the community for proposals.

**Comment by truph01** [comment] 2024-06-12 04:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The page has a slight "lag/Delay" when closing, visible for a couple of seconds.

### What is the root cause of that problem?
After selecting the assignee in https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L182, some Onyx updates will occur that affect the JS thread. Right after that we `goBack`, so the navigation animation is affected by the Onyx updates.

### What changes do you think we should make in order to solve the problem?

Run the navigation in `InteractionManager.runAfterInteractions`

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-06-12 04:48
[Proposal](https://github.com/Expensify/App/issues/43410#issuecomment-2162088604) has been updated to add an optional change

**Comment by truph01** [comment] 2024-06-12 05:25
Proposal updated to add alternative fix

**Comment by truph01** [comment] 2024-06-17 11:56
> Can you please point as to what Onyx updates you are referring to?

@allgandalf  Appreciate the feedback! I added more details to [the proposal](https://github.com/Expensify/App/issues/43410#issuecomment-2162088604).

**Comment by MonilBhavsar** [comment] 2024-07-12 10:49
Proposal looks good!

> it's connecting to the full reports collection even though [only 1 report](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L113) from the route param is needed. We can change to connect to only that 1 report by withOnyx or useOnyx, it will also help it to be more smooth.

Did we check the impact of this change. How much is it helping? And do you mean to use selector?

**Comment by truph01** [comment] 2024-07-12 16:49
> Did we check the impact of this change. How much is it helping?

@MonilBhavsar  I checked and it doesn't help much with regards to the lagging issue in the OP, I thought it's nice to have.

> And do you mean to use selector?

I tested using both and similar result, I lean towards using `useOnyx` (if we include that change) as it's the new standard.

The main solution in `What changes do you think we should make in order to solve the problem?` is the part that makes it look smooth and the lagging is gone.

**Comment by JmillsExpensify** [comment] 2024-07-16 23:21
Working through the proposal. @MonilBhavsar thoughts on that last response?

**Comment by MonilBhavsar** [comment] 2024-07-17 07:25
Okay, thanks for clarifying. Let's move ahead and we can update to use `useOnyx`

**Comment by truph01** [comment] 2024-07-18 16:03
PR https://github.com/Expensify/App/pull/45691 can be reviewed

**Comment by mvtglobally** [comment] 2024-07-19 03:21
Issue not reproducible during KI retests. (First week)

**Comment by truph01** [comment] 2024-07-22 15:09
@allgandalf I tested it on my end, and the bug is still reproducible, but not consistently.

**Comment by truph01** [comment] 2024-07-22 21:24
@allgandalf What about your end? Can you reproduce it?

**Comment by MonilBhavsar** [comment] 2024-07-25 10:53
Sorry missed it somehow. i think we should still fix it and improve the code. I guess it will be constantly reproduced on high traffic accounts?

**Comment by MonilBhavsar** [comment] 2024-07-31 08:19
Yes! Thank you for checking

**Comment by JmillsExpensify** [comment] 2024-08-28 21:16
Payment summary: 

 - Contributor: @truph01 $250
 - Reviewer: @allgandalf $250

**Comment by JmillsExpensify** [comment] 2024-08-28 21:19
All contributors paid out. I'm going to past on creating the regression test given the scale/type of bug, so closing this out!

**Closed by JmillsExpensify** 2024-08-28 21:19 UTC
Labels: Reviewing, External, Weekly, Bug
