### ISSUE TITLE
[Bug] [$250] IOS - Profile - Uploaded picture have been rotated itself after saving.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10258] opened 2022-08-05 14:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go Setting - tap on Avatar
4. Select upload photo
5. Tap choose from gallery
6. Pick any picture and tap save

## Expected Result:
Uploaded picture have been not rotated itself after saving

## Actual Result:
Uploaded picture have been rotated itself after saving

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183095096-a228ab53-bef3-4b36-8109-e9100e823225.mp4

**Issue reported by:** Applause - Internal Team

**Upwork job link :** https://www.upwork.com/jobs/~0169e2129c15b874c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-08-05 16:58
this can be external

**Comment by vtaba-kw** [comment] 2022-08-05 17:05
@parasharrajat checking

**Comment by Tabakharniuk** [comment] 2022-08-05 17:06
@parasharrajat checking

**Comment by michaelhaxhiu** [comment] 2022-08-05 17:24
@Justicea83 if you want, I can self assign and export this right now since it's `daily` and I looked at it already :) lmk

**Comment by Justicea83** [comment] 2022-08-05 17:26
@michaelhaxhiu , I've assigned you

**Comment by michaelhaxhiu** [comment] 2022-08-05 17:40
Job exported - https://www.upwork.com/jobs/~01ed586ed99411249a

**Comment by Tabakharniuk** [comment] 2022-08-05 18:47
Does this issue reproduce on all platforms? Or only on iOS? 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/44551710/183141694-c08dcaa8-c107-4a72-925b-9692fd7cd2d2.png">

I also can't reproduce. Already retested on: 
- iOS (simulator)
- Android (Samsung s8)
- Web MacOS (chrome, safari)

Still trying...

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 19:21
Able to reproduce it on my end on an iPhone device.

**Comment by Tabakharniuk** [comment] 2022-08-05 19:32
Thank you, @Santhosh-Sellavel. Is it reproducing on other platforms?

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 19:47
@parasharrajat 
Those are live photos, normal photos which are of less size fine. 

### Live Photos
https://user-images.githubusercontent.com/85645967/183147810-91f4415f-7878-47f1-8ec8-cebd9311c2a4.MP4

### Normal Photo (less than 100 Kb this one)
https://user-images.githubusercontent.com/85645967/183149387-067594e8-173d-485d-b05b-90c803b0a226.MP4

But photos with lesser size also show a limit reached error, is that a separate issue or regression?

https://user-images.githubusercontent.com/85645967/183149894-6ad3f491-a2e0-4d88-891a-fd32d49d6f52.MOV

**Comment by Santhosh-Sellavel** [comment] 2022-08-05 20:09
The size issue might relate to this https://github.com/Expensify/App/issues/9424 where the size gets changed after picking up.

**Comment by Tabakharniuk** [comment] 2022-08-05 20:18
Good news! I've managed to reproduce the problem!

**Comment by Tabakharniuk** [comment] 2022-08-05 20:56
Upd: Turns out that the library that we are using for cropping images on ios/android (https://github.com/guhungry/react-native-photo-manipulator) has some problems with handling image orientation. What is interesting, bug only reproduces on images captured on iPhone's camera. 

I've created a draft PR. https://github.com/Tabakharniuk/react-native-image-manipulator
It's late here now, I'm going to finalize PR tomorrow morning.

**Comment by Tabakharniuk** [comment] 2022-08-05 21:35
Upd: Created PR(https://github.com/oguzhnatly/react-native-image-manipulator/pull/1)  to fix root cause in [react-native-photo-manipulator](https://github.com/guhungry/react-native-photo-manipulator)

**Comment by Tabakharniuk** [comment] 2022-08-06 12:58
Upd: Waiting for PR review https://github.com/oguzhnatly/react-native-image-manipulator/pull/1

**Comment by Beamanator** [comment] 2022-08-08 10:11
Aah wow nice work everyone!

Since this is not a regression, I'm removing `DeployBlockerCash` - though if it's an issue with another lib, shouldn't the issue be reproducible in Production? Or did we just update that lib with the bug?

One more question @Santhosh-Sellavel - were you able to reproduce if an iOS live photo was uploaded via Android? Just want to make sure we're sure the issue is only reported to occur on iOS

**Comment by Santhosh-Sellavel** [comment] 2022-08-08 16:28
@Beamanator 
> Since this is not a regression, I'm removing DeployBlockerCash - though if it's an issue with another lib, shouldn't the issue be reproducible in Production? Or did we just update that lib with the bug?

Not able to reproduce on production. And the library was included on the Orginal PR #8511.  

> One more question @Santhosh-Sellavel - were you able to reproduce if an iOS live photo was uploaded via Android? Just want to make sure we're sure the issue is only reported to occur on iOS

This case is not possible, I tried to share it became a normal image on android. It occurs only on iOS for now.

**Comment by mvtglobally** [comment] 2022-08-09 05:02
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2022-08-09 08:03
> Not able to reproduce on production. And the library was included on the Orginal PR https://github.com/Expensify/App/pull/8511.

Aah great, thanks for the link @Santhosh-Sellavel - that makes sense why it's not in production.

> This case is not possible, I tried to share it became a normal image on android. It occurs only on iOS for now.

That's great to know, thanks!

@mvtglobally did you try reproducing in staging or Production? Looks like so far @Tabakharniuk was only able to reproduce in staging.

**Comment by Beamanator** [comment] 2022-08-09 08:06
@Santhosh-Sellavel it looks like you agreed we should hire @Tabakharniuk since you upvoted this comment, right? https://github.com/Expensify/App/issues/10258#issuecomment-1207188580

**Comment by michaelhaxhiu** [comment] 2022-08-09 15:55
Awaiting a confirmation on this 👆 before I proceed

**Comment by Santhosh-Sellavel** [comment] 2022-08-09 20:53
@Beamanator 
Yeah fix looks promising, Let's hire @Tabakharniuk for it.
🎀 👀 🎀 C+ Reviewed
cc: @michaelhaxhiu

**Comment by mvtglobally** [comment] 2022-08-10 03:31
@Beamanator This issue was only repro for us in Staging, not repro in prod

**Comment by Tabakharniuk** [comment] 2022-08-10 17:25
Applied. Still waiting for a PR review to fix the issues in the library

**Comment by Tabakharniuk** [comment] 2022-08-14 11:27
There has been no update on https://github.com/oguzhnatly/react-native-image-manipulator/pull/1 for more than 9 days. Because of that I've forked the library and published it to npm([link](https://www.npmjs.com/package/react-native-image-manipulator)). Also, I've updated PR (https://github.com/Expensify/App/pull/10279). Retested on real device and now everything works fine. 

Would that be an acceptable solution? If yes, I will update the PR description and then it will be ready for review.

**Comment by Beamanator** [comment] 2022-08-15 13:21
Thanks for the update @Tabakharniuk - I think what we would prefer is to Fork the repo to be an Expensify repo, then instead of publish the package to `npm` we just use `"react-native-image-manipulator": "git+https://github.com/Expensify/react-native-image-manipulator.git#<commit-hash>"` like we already do in our `package.json`.

Also I brought this up internally and we decided it's fine to wait another week or two since this is not a super high priority bug, and we would prefer if it gets updated by the maintainer. In the meantime feel free to try to ping the maintainer a few more times, otherwise I think we can just wait 1 more week before forking and going with that route

**Comment by Santhosh-Sellavel** [comment] 2022-08-22 17:19
@Beamanator There is no review from the maintainer till now!

**Comment by Beamanator** [comment] 2022-08-24 08:17
@rafecolton would you please create a Fork of https://github.com/oguzhnatly/react-native-image-manipulator?

**Comment by rafecolton** [comment] 2022-08-24 09:40
Done!

**Comment by Beamanator** [comment] 2022-08-24 10:35
Thanks @rafecolton !

Ok @Tabakharniuk would you mind making a PR on that new repo (https://github.com/Expensify/react-native-image-manipulator) with your changes?

**Comment by Tabakharniuk** [comment] 2022-08-25 13:38
Done ✅

**Comment by Beamanator** [comment] 2022-08-27 21:56
Thanks @Tabakharniuk ! PR in the react-native-image-manipulator repo merged 👍 now can you make a PR in E/App with the updated package link? You can see how we currently do this in `package.json` where we link to other Expensify repos 👍 Let us know if you have questions!

**Comment by Tabakharniuk** [comment] 2022-09-01 13:38
Done ✅
https://github.com/Expensify/App/pull/10742 is ready for review 

cc: @Beamanator

**Comment by Beamanator** [comment] 2022-09-01 13:40
Thanks @Tabakharniuk ! I'll wait for @Santhosh-Sellavel to review first 👍

**Comment by mvtglobally** [comment] 2022-09-13 04:31
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2022-09-14 10:04
Not overdue, fix is on staging

**Comment by Beamanator** [comment] 2022-09-23 12:17
Hmm shouldn't this have made it to prod by now?

**Comment by Santhosh-Sellavel** [comment] 2022-09-23 19:28
Yeah, It's on production, verified everything looks good! This should be due for payment.
@Beamanator 

cc: @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2022-09-28 12:21
Made a new job post (last one expired), and invited @Santhosh-Sellavel and @Tabakharniuk. Respond here after you accept and I can disperse payment

**Comment by Tabakharniuk** [comment] 2022-09-29 13:25
Done!
Cc: @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2022-09-30 15:24
@Tabakharniuk is paid, just waiting for santhosh to accept so I can pay & close this GH

**Comment by Beamanator** [comment] 2022-10-05 16:08
Bump @Santhosh-Sellavel

**Comment by michaelhaxhiu** [comment] 2022-10-05 16:15
Actually, bump for me!
Santhosh accepted a few days ago and I missed it. Paying him now ✅

**Closed by michaelhaxhiu** 2022-10-05 16:15 UTC
Labels: External, Engineering, Weekly
