### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Workspace - Unable to open Workspace setting when open member chat page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43462] opened 2024-06-11 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Profile> Workspaces> Create Workspace
2. Go to Members> Invite member> Invite any email address
3. Click on invited member section to open Profile page
4. Select message user
5. Go to Profile> Workspaces
6. Click on the workspace to open settings page

## Expected Result:
Workspace settings page should open

## Actual Result:
Workspace settings page can not be open, nothing happens when click on workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8cef2c43-3b0e-413f-a64a-04c8aadf7ef2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134016f887e04d471</li>
        <li>Upwork Job ID: 1800580579719432391</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 102793761</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-06-11 17:27
How bizarre! I'm able to reproduce, moving it on.

**Comment by ahmedGaber93** [comment] 2024-06-12 16:02
Waiting on proposals

**Comment by ahmedGaber93** [comment] 2024-06-13 11:51
Waiting on proposals

**Comment by MrMuzyk** [comment] 2024-06-17 12:35
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by ahmedGaber93** [comment] 2024-06-17 14:28
@trjExpensify We can assign @MrMuzyk from callstack.

@MrMuzyk after assigning, please post your findings here daily and propose how to fix it to weigh in before creating a PR. thanks!

**Comment by MrMuzyk** [comment] 2024-06-18 11:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App not navigating user to selected screen

### What is the root cause of that problem?

In this scenario, in many of many checks before navigating user, we check if desired state is different from current state.
This is done via `getPartialStateDiff` function. Next, action from this diff is extracted and dispatched causing a navigate

https://github.com/Expensify/App/blob/b278b8f2ec103eed98215b7068c14cc8d029deea/src/libs/Navigation/linkTo/index.ts#L125-L131

In this function we are checking not only if screen name is different but also if params are different. Because that wasn't the case here - params are the same as before - user wasn't getting redirected to proper screen

https://github.com/Expensify/App/blob/b278b8f2ec103eed98215b7068c14cc8d029deea/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L70-L79

### What changes do you think we should make in order to solve the problem?


I'd remove `shallowCompare` check from the condition in line 76. If screen names are different then it's good enough reason to navigate the user already. There is no need to check for params difference as well.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ahmedGaber93** [comment] 2024-06-18 22:13
> In this function we are checking not only if screen name is different but also if params are different.

@MrMuzyk I think we need for that because in nested navigation state, params will contain screen name

**Comment by MrMuzyk** [comment] 2024-06-19 05:42
>@MrMuzyk I think we need for that because in nested navigation state, params will contain screen name

@ahmedGaber93 I don't think it matters anyway. All parts of this condition have to be true because of logical AND.

If it was the case that params would have different name but screen name stored in `.name` field of `stateTopmostFullScreen` and `templateStateTopmostFullScreen` were the same, the outcome would've been the same.

I still believe that checking only for name difference should be sufficient to navigate the user

```
     (stateTopmostFullScreen && 
         templateStateTopmostFullScreen && 
         stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name && 
         !shallowCompare(stateTopmostFullScreen.params as Record<string, unknown> | undefined, templateStateTopmostFullScreen.params as Record<string, unknown> | undefined))
```

**Comment by ahmedGaber93** [comment] 2024-06-19 11:38
@MrMuzyk I think if we remove `shallowCompare` the diff state for the example below will ignore and `ScreenC` not open
```javascript
const stateTopmostFullScreen = {
  name: 'ScreenA',
  params: {},
}

const templateStateTopmostFullScreen = {
  name: 'ScreenA',
  params: {
    screen: 'ScreenB',
    params: {
      screen: 'ScreenC',
    },
  },
}
```

**Comment by MrMuzyk** [comment] 2024-06-19 11:41
It wouldn't open anyway because `name` properties are the same which would case whole condition to return false regardless of what comes after

`&& stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name &&`

**Comment by ahmedGaber93** [comment] 2024-06-19 11:46
Yeah, that is correct true, so I think the condition should be
- if names are different, return true without check params
- if names are the same, check the params

```javascript
// stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name && !shallowCompare
stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name || !shallowCompare
```

What do you think?

**Comment by MrMuzyk** [comment] 2024-06-19 11:53
Ahh I get it now 😅 I agree - if screen name can come inside params then it would make sense to change the condition like on the line above you've posted

**Comment by ahmedGaber93** [comment] 2024-06-19 11:59
I think this part of the code affected in many places. Could you please test it through the app and update your proposal?

**Comment by MrMuzyk** [comment] 2024-06-19 12:03
Yes, will do!

**Comment by ahmedGaber93** [comment] 2024-06-19 12:25
> Can I proceed with PR then?

CC @Beamanator

**Comment by MrMuzyk** [comment] 2024-06-19 14:05
Opened a PR, tomorrow Im OOO. If anything comes up I will take care of this on friday

**Comment by ahmedGaber93** [comment] 2024-07-02 08:48
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to Account setting > Workspaces > Create Workspace
2. Go to Members > Invite member > Invite any email address
3. Click on the invited member item to open Profile page then click on message user
4. Go to Account setting > Workspaces again
5. Click on any workspace to open its settings page and Verify it open successfully

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment] 2024-07-02 18:27
Can you provide a bit more context on all the "N/As" in the checklist, please @ahmedGaber93?

**Comment by ahmedGaber93** [comment] 2024-07-03 00:51
@trjExpensify updated.

**Comment by trjExpensify** [comment] 2024-07-03 18:44
Cool, thanks. Paid!

**Closed by trjExpensify** 2024-07-03 18:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
