### ISSUE TITLE
[Hold for payment 2024-09-09][$250] Track tax - Track tax feature is still available when Taxes feature is disabled offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47421] opened 2024-08-14 13:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > More features
3. Enable Distance rates and Taxes
4. Go to Distance rates > Settings
5. Enable Track tax
6. Go offline
7. Disable Taxes in More features
8. Go to Distance rates > Settings
9. Note that Track tax switch is still enabled but locked
10. Click on any distance rate
11. Note that Tax rate and Tax reclaimable on fields are still present when Taxes is disabled

## Expected Result:
When disabling Taxes feature offline
Step 9 - Track tax switch should be disabled and locked
Step 11 - Tax rate and Tax reclaimable on fields should disappear

## Actual Result:
When disabling Taxes feature offline
Step 9 - Track tax switch is enabled and locked
Step 11 - Tax rate and Tax reclaimable on fields are still present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bb5ff826-f161-4a92-bd85-39379f58a489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125dfa57845b9c94e</li>
        <li>Upwork Job ID: 1823746280169788016</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 103626049</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by lanitochka17** [comment] 2024-08-14 13:19
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-14 13:19
We think that this bug might be related to #wave-collect - Release 2

**Comment by etCoderDysto** [comment] 2024-08-14 13:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track tax feature is still available when Taxes feature is disabled offline
### What is the root cause of that problem?
We are using `isDistanceTrackTaxEnabled` to determine if we should display tax features for 
* Tax rates 
https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L140-L142
* Tax reclaimable
https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L157-L159
* Track tax
https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L140-L142
 
When user disable tax rate in offline mode, we are not optimistialy updating `isDistanceTrackTaxEnabled (policy?.customUnits.customUnitID.customUnit?.attributes?.taxEnabled)` to false as we do for `isPolicyTrackTaxEnabled (policy?.tax?.trackingEnabled)`

### What changes do you think we should make in order to solve the problem?
We should check also for `isPolicyTrackTaxEnabled` in the above places where we are using `isDistanceTrackTaxEnabled`, since `isPolicyTrackTaxEnabled` updated optimistically. 
```javascript
 <Switch
     isOn={isDistanceTrackTaxEnabled && isPolicyTrackTaxEnabled}
```
We will do the same for tax rates, and tax reclaimable as well
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2024-08-20 18:26
@mountiny - looks like we just need a quick check from you. Can I assign this over to @etCoderDysto?

**Comment by mountiny** [comment] 2024-08-21 19:46
Assigned, thanks for your patience

**Comment by etCoderDysto** [comment] 2024-08-26 17:58
@Ollyws [PR](https://github.com/Expensify/App/pull/48017) is ready for review

**Comment by lschurr** [comment] 2024-09-09 16:15
Payment summary:

- Contributor: @etCoderDysto $250 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38181551/overview))
- Reviewer: @Ollyws $250 (please request in NewDot)

**Closed** 2024-09-09 16:15 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by garrettmknight** [comment] 2024-09-11 19:17
$250 approved for @Ollyws
