### ISSUE TITLE
VBA Onfido - No message with the instructions in Concierge chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41065] opened 2024-04-26 08:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971173
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions: Use Regions bank, First Name: First, Last Name: Last
1. Connect Plaid VBA
2. Procced to verification page
3. Click 'Yes, let's chat'

## Expected Result:
User is navigated to the conversation with Concierge.
A message with the instructions to provide the missing information appears in chat.

## Actual Result:
User is navigated to the conversation with Concierge.
No message with the instructions to provide the missing information posted in Concierge chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9218cdc8-2587-4780-a961-9277f57a8e2d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by izarutskaya** [comment] 2024-04-26 08:05
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-26 08:05
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment] 2024-04-26 11:19
I dont see any call tot he backend when that action is taken https://github.com/Expensify/App/blob/400109cb7f5166af2c984fbe870272191bc58844/src/pages/ReimbursementAccount/ConnectBankAccount/components/FinishChatCard.tsx#L44 so this would have to be coming from some previous step. I think the validation is something that might not be coming for staging users cc @nkuoch for confirmation.

I will demote as this does not seem like a blocker

**Comment by mountiny** [comment] 2024-04-26 11:20
User is navigated to the concierge chat where they can message always so I think that is fine

**Comment by nkuoch** [comment] 2024-04-26 14:07
@izarutskaya Can you double check if still don't see the message? I tested myself and faced the same issue as you but looking now, I see the message, so it's seems it was just some job or db delay?

**Comment by cristipaval** [comment] 2024-04-29 09:26
Thanks for taking it over, @nkuoch 🙇

**Comment by nkuoch** [comment] 2024-05-02 09:03
Will try again today

**Comment by nkuoch** [comment] 2024-05-06 09:16
Will try again today

**Comment by nkuoch** [comment] 2024-05-07 08:28
Couldn't reproduce on staging. Closing. Please reopen if you can reproduce.
<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/2463975/01bdc0c4-497c-4d73-867f-fdf6e6673a03">

**Closed by nkuoch** 2024-05-07 08:28 UTC
Labels: Engineering, Daily, Bug
