### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [HOLD for payment 2024-06-11] [HOLD for payment 2024-06-06] Distance rates - Default rate input is 0 instead of actual amount for newly created WS

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42780] opened 2024-05-29 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Create a new workspace.
4. Go to More features.
5. Enable Distance rates.
6. Go to Distance rates.
7. Click on the default rate.
8. Click Rate.

## Expected Result:
The rate amount input will display the actual amount (production behavior).

## Actual Result:
The rate amount input displays 0 instead of the actual amount.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2aadb164-0531-485f-a62d-0bd561aed3ae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by m-natarajan** [comment] 2024-05-29 16:31
@JmillsExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment] 2024-05-29 17:53
For the default rate `0.655`, the updated version of the function `calculateAmountLength()` returns ... 11, whereas for the rate `0.670` coming from the API when you're online, it returns 3.
`validateAmount()` is called with `amountMaxLength: 10`, which is why the function is returning false when you're offline.


<img width="1367" alt="image" src="https://github.com/Expensify/App/assets/2229301/473313cb-e3b9-4510-b173-3493defa17c2">

**Comment by ikevin127** [comment] 2024-05-29 18:09
@francoisl If this is a blocker that needs to be handled asap then I'd suggest the **revert** since the code changes of the PR are minimal, then @bernhardoj won't be time constrained to re-work the solution.

Otherwise I'd wait for their input and possible follow-up fix.

**Comment by kavimuru** [comment] 2024-05-29 19:57
Fixed in the version 77-3

https://github.com/Expensify/App/assets/43996225/9dec6bcf-b6d1-4c59-a95f-5a3ba89f7f91

**Comment by bernhardoj** [comment] 2024-05-30 03:29
@francoisl correctly pointed out the root cause, it's the old regex here.
https://github.com/Expensify/App/blob/f6aa6c20a18e2d64f3143815f5266d064ce7cb6a/src/libs/MoneyRequestUtils.ts#L48-L50

The calculation that we did is already correct, but the regex above matches the decimal separator (.) because 0.655 is 65.5 cents which still contains a dot.

The regex above is added in this [PR](https://github.com/Expensify/App/pull/16917) to prevent NaN, Infinity, and number with scientific notation (1+e26). So, I updated the regex to be more specific.

A new PR is [here](https://github.com/Expensify/App/pull/42815)

**Comment by francoisl** [comment] 2024-06-07 19:09
The final fix for this was just merged. This was for a regression that was originally handled internally, and then the author and C+ from the initial PR fixed it, so I believe no payment is required.

**Comment by francoisl** [comment] 2024-06-21 20:20
Checklist already completed [above](https://github.com/Expensify/App/issues/42780#issuecomment-2147601425) and no payments required, closing.

**Closed by francoisl** 2024-06-21 20:20 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
