### ISSUE TITLE
Chat - Concierge chat won't load when open concierge link and sign in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23968] opened 2023-07-31 22:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user should be signed out
1. Open https://staging.new.expensify.com/concierge
2. Sign In with valid account

## Expected Result:
User should be navigated on concierge chat and concierge chat should be loaded

## Actual Result:
Concierge chat won't load

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a32b3fa8-dd57-46e5-89f5-f2cfbfa43834

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-08-01 10:50
Hmm I'm seeing this on staging:

<img width="1315" alt="Screenshot 2023-08-01 at 1 49 52 PM" src="https://github.com/Expensify/App/assets/3885503/39ae0c41-c6ec-48f2-bfd9-9662a7705301">

**Comment by Beamanator** [comment] 2023-08-01 10:57
Actually the staging account I used before was a screwed up one - i tried again with a different account and it worked. I'll try again with one more account then close if i can't reproduce

**Comment by Beamanator** [comment] 2023-08-01 10:58
Yeah this worked for multiple accounts - closing

**Closed by Beamanator** 2023-08-01 10:58 UTC
Labels: DeployBlockerCash, Engineering, Hourly
