### ISSUE TITLE
[$250] Web - Attachment - Attachment tag displayed in LHN after refresh

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9539] opened 2022-06-22 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to any user and click on Plus button
4. Attach any jpg file
5. Click Send button
6. Check the Attachment tag under LHN
7. Refresh the page

## Expected Result:
Attachment tag displayed in LHN after sent the file

## Actual Result:
User's email address is displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.78.7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com / Feya87Katya
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/175114062-ba225419-5e69-42bc-a0a1-80d1a3bf8310.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-06-23 23:05
[Upwork Issue](https://www.upwork.com/jobs/~012a7d8c9f7157e5b0)

**Comment by JosueEchandiaAsto** [comment] 2022-06-24 04:24
### Proposal

### Issue

Attachment tag displayed in LHN after sent the file

### Fix
After uploading the attached file, it is updating `lastMessageText`, ignoring that it is an attached file, that is why the text is wrong.
https://github.com/Expensify/App/blob/3757142611c84d9ffc59f86c29d1cd6f3db07f01/src/libs/actions/Report.js#L554
We need to add the missing logic so that when it is an attachment it updates the text correctly.
https://github.com/Expensify/App/blob/176161450f04aa6c4d4c54962348e2df811067c7/src/libs/actions/Report.js#L555
Commit: https://github.com/Expensify/App/commit/176161450f04aa6c4d4c54962348e2df811067c7

### Result

https://user-images.githubusercontent.com/16966456/175461718-8ca90ed0-9ae5-46ee-aadd-4c8dfcdf0f39.mov

**Comment by mananjadhav** [comment] 2022-06-26 15:18
I thought this was a regression and I tried finding the root cause. It seems this happens to the current chat when the attachment is added. If we refresh then it shows up properly.

@roryabraham, @JosueEchandiaAsto's proposal looks good. 

🎀 👀 🎀 
C+ reviewed

**Comment by roryabraham** [comment] 2022-06-27 17:20
Okay, LGTM 👍 

Long-term, I would like to see some unit tests added for the title and subtitle of items in the LHN.

**Comment by MitchExpensify** [comment] 2022-06-27 19:11
Nice! Invited both @JosueEchandiaAsto & @mananjadhav to the Upwork job for eventual payment.

**Comment by JosueEchandiaAsto** [comment] 2022-06-28 18:44
PR Created 🎉 https://github.com/Expensify/App/pull/9603

**Comment by MitchExpensify** [comment] 2022-07-01 17:43
Will do! @JosueEchandiaAsto just waiting for the offer to be accepted

**Comment by mananjadhav** [comment] 2022-07-01 17:50
@roryabraham @MitchExpensify Is this eligible for C+ payout?

**Comment by JosueEchandiaAsto** [comment] 2022-07-01 18:00
@MitchExpensify, Offer accepted 👨🏻‍💻

**Comment by MitchExpensify** [comment] 2022-07-01 18:16
Thanks! Paid

**Comment by MitchExpensify** [comment] 2022-07-01 18:17
Are we good to close this out then?

**Comment by mananjadhav** [comment] 2022-07-05 09:54
> @roryabraham @MitchExpensify Is this eligible for C+ payout?

@MitchExpensify bump

**Comment by MitchExpensify** [comment] 2022-07-06 18:52
Thanks for the bump @mananjadhav ! We're chatting internally and will have an update very soon

**Comment by MitchExpensify** [comment] 2022-07-07 22:16
Paid @mananjadhav, thanks so much for your patience!

**Closed by MitchExpensify** 2022-07-07 22:16 UTC
Labels: Exported, External, Engineering, Weekly
