### ISSUE TITLE
[$250][P2P Distance] - Amount field is not grayed out when changing distance rate offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46880] opened 2024-08-06 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/40021
**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has a few distance rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense.
4. Go to transaction thread.
5. Go offline.
6. Click Rate.
7. Select a different rate.

## Expected Result:
Amount field should be grayed out because it is changed from the rate offline.

## Actual Result:
Amount field is not grayed out when changing distance rate offline.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x]MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ce70bc70-0242-408d-9492-a8ce95226763

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01199ead94cf3782d9</li>
        <li>Upwork Job ID: 1820883188663849553</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103451212</li>
<li>etCoderDysto | Contributor | 103451215</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by etCoderDysto** [comment] 2024-08-06 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount field is not grayed out when changing distance rate offline
### What is the root cause of that problem?
We are checking for amount change pending action only here
https://github.com/Expensify/App/blob/290a9d9c2c812d483b545ba1f122953e34a628d7/src/components/ReportActionItem/MoneyRequestView.tsx#L503
### What changes do you think we should make in order to solve the problem?
We should also check for tax rate change pending action too 
```
<OfflineWithFeedback pendingAction={getPendingFieldAction('amount') ?? getPendingFieldAction('customUnitRateID')}>
```
### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment] 2024-08-06 18:02
Not a blocker since the rate field is still behind a beta.

**Comment by jjcoffee** [comment] 2024-08-07 15:33
Reviewing proposals tomorrow!

**Comment by wildan-m** [comment] 2024-08-08 04:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - Amount field is not grayed out when changing distance rate offline

### What is the root cause of that problem?

In `calculateAmountForUpdatedWaypointOrRate` Dependent pending fields not added when the affected value changes

### What changes do you think we should make in order to solve the problem?

By following [this pattern](https://github.com/wildan-m/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/libs/TransactionUtils/index.ts#L294-L306). We can modify 
 `calculateAmountForUpdatedWaypointOrRate` to 

```tsx
....
        modifiedAmount: updatedAmount,
        modifiedMerchant: updatedMerchant,
        modifiedCurrency: updatedCurrency,

        pendingFields: {
            ...transaction?.pendingFields,
            ...(!lodashIsEqual(updatedAmount, transaction?.modifiedAmount ?? transaction?.amount) && { amount: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE }),
            ...(!lodashIsEqual(updatedMerchant, transaction?.modifiedMerchant ?? transaction?.merchant) && { merchant: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE }),
            ...(!lodashIsEqual(updatedCurrency, transaction?.modifiedCurrency ?? transaction?.currency) && { currency: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE })
        },
    };
```

This way we only add pending fields, if the value actually change. the pending field not only amount, it can also merchant or currency.


Then we can move / modify [this step](https://github.com/wildan-m/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/libs/actions/IOU.ts#L2443-L2446) to the step after we finished modify `updatedTransaction`.

Modify the `transactionChanges` to also include affected fields.


src/libs/actions/IOU.ts `getUpdateTrackExpenseParams` and  `getUpdateMoneyRequestParams`
```tsx
....
    // Set any "pending fields"  (ones updated while the user was offline), includes the fields that affected to have error messages in the failureData
    const allTransactionChanges = { ...transactionChanges, ...(updatedTransaction ? updatedTransaction.pendingFields : {}) }
    const pendingFields = Object.fromEntries(Object.keys(allTransactionChanges).map((key) => [key, CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE]));
    const clearedPendingFields = Object.fromEntries(Object.keys(allTransactionChanges).map((key) => [key, null]));
    const errorFields = Object.fromEntries(Object.keys(allTransactionChanges).map((key) => [key, {[DateUtils.getMicroseconds()]: Localize.translateLocal('iou.error.genericEditFailureMessage')}]));
```

[Branch draft for this solution](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/46880-dependent-fields-not-grey?expand=1)
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2024-08-08 15:05
@etCoderDysto's [proposal](https://github.com/Expensify/App/issues/46880#issuecomment-2271255759) LGTM - it's a nice and simple solution, and a pattern that we use elsewhere, e.g. here

https://github.com/Expensify/App/blob/73f97c930795b4c68512d0e25ee253f7ce7d4515/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L128

I'm not aware of any other reason to specifically set the amount field as pending as the other two proposals have, so it seems much simpler to just rely on the field that's actually changed.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by etCoderDysto** [comment] 2024-08-08 17:00
PR will be ready for review in few hours

**Comment by trjExpensify** [comment] 2024-08-09 16:03
>IMO, we shouldn't grey it out if we modify the rate afterward either – just let it remain blank. And grey it out only if the optimistic value is not blank.

I think that works! 

>WDYT @trjExpensify (tagging you 'cause we are in a similar TZ and you're familiar with the flow)?

Always feel free to tag me!

**Comment by etCoderDysto** [comment] 2024-08-11 10:54
Hi @paultsimura, amount is not blank when editing waypoint followed by editing rate. It is only blank when editing waypoints. 

https://github.com/user-attachments/assets/209a0a36-37c9-432a-87c5-9feedc00fd77

**Comment by etCoderDysto** [comment] 2024-08-11 12:50
> @etCoderDysto this should be fixed by https://github.com/Expensify/App/pull/47145, we can hold for it.

Sounds good to me. I will wait till the pr is merged to main

**Comment by jjcoffee** [comment] 2024-08-12 10:35
@RachCHopkins Can you add a hold for https://github.com/Expensify/App/pull/47145? Thanks!

**Comment by etCoderDysto** [comment] 2024-08-15 18:23
Waiting for https://github.com/Expensify/App/pull/47145 to be merged to main

**Comment by jjcoffee** [comment] 2024-08-16 09:39
> Waiting for #47145 to be merged to main

Confirming to remove the overdue label :sweat_smile:

**Comment by jjcoffee** [comment] 2024-08-19 09:51
@etCoderDysto https://github.com/Expensify/App/pull/47145 has been merged. Let's go! :rocket:

**Comment by etCoderDysto** [comment] 2024-08-19 10:07
> @etCoderDysto #47145 has been merged. Let's go! 🚀

Great! I will raise a PR soon.

**Comment by RachCHopkins** [comment] 2024-08-20 21:04
Sorry guys, missed this one - I'm a little swamped and not really watching closely unless I'm starred.

**Comment by jjcoffee** [comment] 2024-08-21 07:44
@RachCHopkins No worries, we're just waiting on a PR from @etCoderDysto here!

**Comment by etCoderDysto** [comment] 2024-08-21 10:27
@jjcoffee [PR](https://github.com/Expensify/App/pull/47779) is ready for review. Sorry for the delay.

**Comment by jjcoffee** [comment] 2024-09-04 08:44
> [!NOTE]  
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-09-06]** according to https://github.com/Expensify/App/issues/48035 prod deploy checklist, confirmed in https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.

cc @RachCHopkins

**Comment by etCoderDysto** [comment] 2024-09-06 06:15
> Note
> 
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-09-06]** according to #48035 prod deploy checklist, confirmed in https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.
> 
> cc @RachCHopkins

I think this issue is ready for payout.
cc @RachCHopkins

**Comment by jjcoffee** [comment] 2024-09-06 13:36
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40021
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40021#issuecomment-2334074417
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - more thorough testing should have caught it
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any workspace chat.
2. Submit a distance expense.
3. Go to the transaction thread.
4. Go offline.
5. Click Rate and select a different rate.
6. Verify that the amount field is greyed out.

Do we agree 👍 or 👎

**Comment by RachCHopkins** [comment] 2024-09-09 06:02
Payment Summary:

- Contributor: @etCoderDysto paid $250 via Upwork
- Contributor+: @jjcoffee paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~01199ead94cf3782d9)

**Comment by RachCHopkins** [comment] 2024-09-09 06:04
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by RachCHopkins** 2024-09-09 06:04 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
