### ISSUE TITLE
IOS/Android - Payments - Google search doesn't work in Debit card Information page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8797] opened 2022-04-27 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging
2. Navigate to Settings > Payments > Add payment method > Debit card
3. Search for an address

## Expected Result:
Google search works in Debit card Information page

## Actual Result:
Google search doesn't work in Debit card Information page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.57.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20220427-091959_New Expensify](https://user-images.githubusercontent.com/93399543/165530487-9745a8e4-a51b-4098-a568-428894f4861c.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment] 2022-04-27 13:44
I see this error on Android. 
```json
{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 223.178.211.57, with empty referer",
   "predictions" : [],
   "status" : "REQUEST_DENIED"
}
```

**Comment by Julesssss** [comment] 2022-04-27 14:03
Okay, seems to be fixed in the library that we previously forked: https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/170

**Comment by Julesssss** [comment] 2022-04-27 14:04
I think I'll just take and complete this one to get it done ASAP.

**Comment by Julesssss** [comment] 2022-05-10 17:08
No update, keeping assigned

**Comment by Julesssss** [comment] 2022-07-27 15:17
No change

**Comment by Julesssss** [comment] 2022-08-30 09:56
Still held

**Comment by Julesssss** [comment] 2022-10-04 17:14
No change here.

**Comment by puneetlath** [comment] 2022-11-02 13:14
@Julesssss I removed and re-added the Bug label to get a BZ team member assigned to help move this forward.

**Comment by MitchExpensify** [comment] 2022-11-02 23:37
Can this be made external? I'm unsure

**Comment by parasharrajat** [comment] 2022-11-03 07:50
Nope, https://github.com/Expensify/App/issues/8797#issuecomment-1111022077. 

Someone from the internal team needs to relax some restrictions on the Google console.

**Comment by Julesssss** [comment] 2022-11-08 11:33
The next step will be to assign to infra for this step: 

> This IP, site or mobile application is not authorized to use this API key. Request received from IP address 223.178.211.57, with empty referer

**Comment by Julesssss** [comment] 2022-11-08 11:40
Hey @flodnv, we believe [this error](https://github.com/Expensify/App/issues/8797#issuecomment-1111022077) requires a change to the key we're using, or perhaps a modified permission for the key we're using. Relevant [StackOverflow](https://stackoverflow.com/a/24235630/4160784)

**Comment by Julesssss** [comment] 2022-11-08 14:05
@flodnv pointed out that this is no longer occuring. @kbecciv would you mind attempting to reproduce? Thanks!

**Comment by arielgreen** [comment] 2022-11-08 23:26
@MitchExpensify can you update on the status of this one? If it's still reproducible, let's throw `Demolition` on it and get it moving forward.

**Closed** 2022-11-09 10:06 UTC
Labels: Engineering, Daily, Internal, Bug
