### ISSUE TITLE
[HOLD for Payment 2024-06-21] Flag message - "Only visible to you" disappears after flagging the whisper, and then reappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42557] opened 2024-05-23 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is invited to a workspace
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Right click on the welcome whisper message
4. Click Flag as offensive
5. Select Spam

## Expected Result:
"Only visible to you" will remain above the welcome message after flagging the whisper

## Actual Result:
Only visible to you" disappears after flagging the whisper, and then reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b01f6a0f-366c-4c3f-a181-fe0ad8436c17

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-23 20:12
@NikkiWines  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dangrous** [comment] 2024-05-23 21:10
Hm yeah looks like it might be a missed piece from that implementation. Maybe `isWhisper` is no longer returning true when it's flagged? Not sure why though - I'm happy to look into it, though, since it's my code, or we can push external?

**Comment by NikkiWines** [comment] 2024-05-23 21:15
If you want to look, I'd be happy to review your PR 🤝

**Comment by dangrous** [comment] 2024-05-23 21:38
Cool, I can self-assign this now and take a look when I'm back in on Tuesday... is that too late? I don't think this needs to be a deploy blocker, imo.

**Comment by mountiny** [comment] 2024-05-23 22:39
Given the fact the state of the app eventually gets to the correct state I dont think this has to be a blocker so removing the labels. Also assigned Daniel to follow up on this one. Thank you!

**Comment by dangrous** [comment] 2024-05-28 17:56
Okay I've figured out why - https://github.com/Expensify/App/pull/40020#issuecomment-2135820438 - but I'm not sure why that code exists in the first place. I can fix it by just deleting the check for pendingActions in `isWhisper` but need to make sure that that won't cause side effects.

**Comment by NikkiWines** [comment] 2024-06-03 17:35
Unassigning myself, since @dangrous is looking into this!

**Comment by dangrous** [comment] 2024-06-04 20:52
Bumped my question above in the associated thread. Hopefully we can get moving on this shortly!

**Comment by dangrous** [comment] 2024-06-06 16:33
Based on @ishpaul777's testing I think we can move forward with removing that check. I'll make a draft PR, and then include testing for both this issue as well as the testing steps from #40020 and we can go ahead with that for now (while we're waiting to hear back from the contributor)

**Comment by ikevin127** [comment] 2024-06-15 19:26
⚠️ Automation failed for this issue -> this should be on **[HOLD for Payment 2024-06-21]** according to yesterday's production deploy from https://github.com/Expensify/App/pull/43198#issuecomment-2168863423. I require payment here for C+ review of PR https://github.com/Expensify/App/pull/43198.

@dangrous Could you please add the HOLD to the issue's title and the `Bug` label to get a BZ team member assigned for handling payment here ?

**Comment by ikevin127** [comment] 2024-06-21 15:56
⚠️ This is missing `Awaiting payment` label which might cause payment delay!

cc @dangrous @stephanieelliott

**Comment by mallenexpensify** [comment] 2024-06-21 19:19
Assigned @ikevin127 , they reviewed the PR
- https://github.com/Expensify/App/pull/43198

@ikevin127 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0182f10ddb5995af64

**Comment by ikevin127** [comment] 2024-06-21 19:21
Accepted, thank you!

**Comment by mallenexpensify** [comment] 2024-06-21 19:27
Contributor+: @ikevin127 paid $250 via Upwork.  

Looks like we need the BZ checklist filled here, can you do so @ikevin127 ? 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment] 2024-06-21 20:51
Thanks @ikevin127 , TestRail GH created
- https://github.com/Expensify/Expensify/issues/406706

Should be all good here

**Closed by mallenexpensify** 2024-06-21 20:51 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
