### ISSUE TITLE
[$500] Category - The first item in the Category list is not highlighted by default

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37284] opened 2024-02-27 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Click + > Request money > Manual.
4. Proceed to confirmation page.
5. Click Category.

## Expected Result:
The first item in the Category list will be highlighted by default.

## Actual Result:
The first item in the Category list is not highlighted by default.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2dbe05ea-ca02-4677-9710-34a8b5aa991c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb7332a3e3d77dfe</li>
        <li>Upwork Job ID: 1762471845828468736</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 13:37
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by arosiclair** [comment] 2024-02-27 15:38
> I think we decided to not focus on any list item until arrow keys are pressed or we have search inputs.

You have a link to where that was discussed?

**Comment by arosiclair** [comment] 2024-02-27 15:51
It seems like we just updated the Category picker to include a search field and now the search field is focused by default:

| Prod | Staging |
|--------|--------|
| ![Screenshot 2024-02-27 at 10 48 39 AM](https://github.com/Expensify/App/assets/6833644/4f000837-4aa4-4124-bac6-170239992ec3) | ![Screenshot 2024-02-27 at 10 50 00 AM](https://github.com/Expensify/App/assets/6833644/267e1eee-9a20-40d4-80c4-cffc7ca4cd3b) | 

This seems fine to me

**Comment by arosiclair** [comment] 2024-02-27 17:39
Removed blocker label since this is low impact either way

**Comment by arosiclair** [comment] 2024-02-27 17:41
Since the Merchant selector and Chat participants selector also behave the same way, I'll close this as not a bug

**Closed by arosiclair** 2024-02-27 17:41 UTC
Labels: External, Engineering, Hourly, Help Wanted
