### ISSUE TITLE
Task - 'Share somewhere' subtitle appears a few seconds after user display name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23583] opened 2023-07-25 19:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Tap + icon > Assign task > Enter title > Next.
3. Select an assignee.
4. Select User B that User A has never interacted with.

## Expected Result:
'Share somewhere' subtitle appears together with the user display name.

## Actual Result:
'Share somewhere' subtitle appears a few seconds after user display name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/37e2416d-7fad-4cb4-a532-0db5b2693e02

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-07-25 22:34
@thienlnam is this one not a blocker?

**Comment by thienlnam** [comment] 2023-07-25 23:09
Nope, definitely not a blocker - I've been meaning to find the linked PR but I believe this is also from a new feature we recently added

**Comment by thienlnam** [comment] 2023-07-25 23:12
cc @chiragxarora and @eVoloshchak

**Comment by thienlnam** [comment] 2023-07-26 18:06
Thanks for investigating - yeah I think since you have to assign someone you haven't talked to before this would also be fixed from this internal issue https://github.com/Expensify/Expensify/issues/294203. Going to put this on hold and just address it there

**Comment by thienlnam** [comment] 2023-08-04 00:36
Still on hold

**Comment by thienlnam** [comment] 2023-08-24 18:48
Holding PR is merged, can we see if this is still reproducible / and if not let's close it

**Comment by johncschuster** [comment] 2023-08-25 22:01
@kbecciv can you please try reproducing the behavior to see if it persists?

**Comment by kbecciv** [comment] 2023-08-26 13:25
Hello @johncschuster! Coming back from vacation, let me check if the issue is reproducible in latest build.

**Comment by kbecciv** [comment] 2023-08-26 13:50
Unable to reproduce it on build v1.3.57-5

https://github.com/Expensify/App/assets/93399543/194e14ae-5365-48dc-9bea-0e453063dfad

**Comment by thienlnam** [comment] 2023-08-28 17:40
Awesome, applause report so closing it out now!

**Closed by thienlnam** 2023-08-28 17:40 UTC
Labels: Engineering, Daily, Overdue, Bug
