### ISSUE TITLE
[HOLD for payment 2024-04-09] [Guided Setup Stage 2] Update UI for completed tasks (Phase 1)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38772] opened 2024-03-21 20:06 UTC
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section: https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.oy52ywwcdkmx
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
- Update the UI for complete tasks

cc @barttom 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b3049006aada29e</li>
        <li>Upwork Job ID: 1770904819200360448</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by barttom** [comment] 2024-03-22 08:35
Hello! I'm Bartek from Callstack, an expert contributor group, and I would like to work on this issue.

**Comment by joekaufmanexpensify** [comment] 2024-03-25 14:18
PR WIP

**Comment by hayata-suenaga** [comment] 2024-03-27 16:53
I think I'm not needed here don't know why Melvin assigned me 😅

**Comment by cubuspl42** [comment] 2024-03-28 09:20
PR merged

**Comment by joekaufmanexpensify** [comment] 2024-04-08 14:13
@cubuspl42 could you share regression test steps (if one would be helpful for this)?

**Comment by joekaufmanexpensify** [comment] 2024-04-08 18:58
We need to make the following payments: 

- @cubuspl42 - $500 for C+ review via Upwork. 
- @barttom - no payment needed.

**Comment by joekaufmanexpensify** [comment] 2024-04-08 18:58
@cubuspl42 offer sent for $500!

**Comment by joekaufmanexpensify** [comment] 2024-04-09 14:59
@cubuspl42 all set to issue payment here as soon as we confirm whether a regression tested is needed. Though, I do see a lot of tests in the design doc, so perhaps we're going to add them all at once. CC @francoisl

**Comment by joekaufmanexpensify** [comment] 2024-04-09 20:47
Since there are a list of detailed regression tests in the design doc, I'm going to assume that we're going to add them all in testrail following the implementation (which to my understanding is the project best practice). @francoisl LMK if that is not the plan, and happy to add one individually here.

**Comment by joekaufmanexpensify** [comment] 2024-04-09 20:49
@cubuspl42 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-04-09 20:49
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-04-09 20:49
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-04-09 20:49 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment
