### ISSUE TITLE
Dev - Request money - Currency flickers between '$' and user's local currency when a new user Signs up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26058] opened 2023-08-28 07:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-up page
2. Enter email & click on 'Continue' button
3. Enter magic code
4. Click on 'Request money' button

## Expected Result:
currency shouldn't flicker between '$' and user's local currency, and it should display the user's local currency on the first visit request money page

## Actual Result:
currency flickers between '$' and the user's local currency

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d8bc16e6-fd5a-4c1e-813b-19d59af9b7b8

https://github.com/Expensify/App/assets/115492554/e95c1911-033d-49ef-9d49-eb632797933e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692169201550669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-08-29 01:20
@Gonals - tapping you to see if you can reproduce, given it's occurring in a Dev environment? let me know!

**Comment by Natnael-Guchima** [comment] 2023-08-29 05:03
This should be reprducible on staging by now @sophiepintoraetz

**Comment by sophiepintoraetz** [comment] 2023-09-01 01:29
I cannot reproduce this on staging (v1.3.61-1) - @Gonals, can you confirm whether this is happening on Dev?
![2023-09-01_13-28-12 (1)](https://github.com/Expensify/App/assets/42940078/887824ae-0de2-4328-b895-20db3bba36a2)

**Comment by Gonals** [comment] 2023-09-04 10:36
I don't see it anymore either. Closing

**Closed by Gonals** 2023-09-04 10:36 UTC
Labels: Engineering, Daily, Overdue, Bug
