### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500]  Assign task - Assign task tooltip is not displaying email and avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28626] opened 2023-10-02 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on assign task
3. Enter any title and go to next step
4. Assign the task to user with avatar and display name set and complete the assign task process
5. Hover on @ user in task message and observe that tooltip is not displaying proper email and avatar

## Expected Result:
App should display proper user details on task @user hover

## Actual Result:
 App does not display proper email and avatar on task @user hover

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-11

**Reproducible in staging?:** Yes

**Reproducible in production?:** NO

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ef709946-ae80-4e08-a46b-411a9cd29fe8

https://github.com/Expensify/App/assets/78819774/1cabfd1f-a00d-4875-82a1-2346a5eecccc

https://github.com/Expensify/App/assets/78819774/74378a53-b48f-41a6-b57c-c9eeb1ec78b5

Production

https://github.com/Expensify/App/assets/78819774/ff817b1a-b2e9-455e-99c1-59d6bceb217f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696260115370229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f1f51e85dd750ed</li>
        <li>Upwork Job ID: 1709625207880982528</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27104821</li>
<li>dhanashree-sawant | Reporter | 27104822</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-10-02 15:54
I'm not 100%, but this is possibly being fixed [here](https://github.com/Expensify/App/issues/28055)

**Comment by mountiny** [comment] 2023-10-02 15:54
I dont think this is a blocker at this point, its a minor issue but also I think it might be expected as it seems like its showing display name and I remember we wanted to update the mentions to show display name. Maybe @puneetlath could confirm

**Comment by Julesssss** [comment] 2023-10-02 15:55
Agree not a blocker

**Comment by trjExpensify** [comment] 2023-10-02 20:15
The mention display name PR is here and deployed: https://github.com/Expensify/App/pull/26877#issuecomment-1739839551

So the question for @puneetlath is whether the profile in the tooltip should contain primaryLogin as well as displayName? I think it probably should, providing it's a "known" user and that login is revealed to the viewer.

**Comment by abdulrahuman5196** [comment] 2023-10-03 08:41
> I'm not sure about this, but it might be fixed [here](https://github.com/Expensify/App/issues/28055)

This PR would not be fixing this issue.

**Comment by tgolen** [comment] 2023-10-03 14:27
I'm going to unassign myself since this is not a blocker. I would suggest moving this to be an external issue once @puneetlath weighs in on the behavior.

**Comment by trjExpensify** [comment] 2023-10-03 14:34
yuuuup! 👍

**Comment by puneetlath** [comment] 2023-10-03 17:03
Hm, yes I think this is a bug. A direct mention does seem to render the tooltip properly: 

<img width="509" alt="image" src="https://github.com/Expensify/App/assets/1371996/20bd9df8-bdb9-49bb-bd0c-70ffd852c4c0">

But the task assignee doesn't: 

<img width="327" alt="image" src="https://github.com/Expensify/App/assets/1371996/3c29ebd2-4953-4f0b-8f2e-1cc678fc7038">

Actually, I have a feeling this might have the same cause as: https://github.com/Expensify/App/issues/22293#issuecomment-1744152239

**Comment by trjExpensify** [comment] 2023-10-03 18:18
Inteeeresting. So is your preference to send it `external` for investigation or hold on #22293?

**Comment by puneetlath** [comment] 2023-10-03 18:22
I think you can set it External. That's just a theory, but could be totally off.

**Comment by abdel-h66** [comment] 2023-10-03 18:23
To me it looks like we are not using the same logic for the Task assginee mention vs the chat mention. there was some updates to the metion renderer here https://github.com/Expensify/App/issues/26306 

Also in your screenshot @puneetlath See that in the task assignee we are using the Display name, while in the mention in the text message it's the login.

**Comment by abdel-h66** [comment] 2023-10-03 18:25
By using the Task assignee login, the display becomes consistent 
```
const htmlForTaskPreview =
        taskAssignee && taskAssigneeAccountID !== 0 ? `<comment><mention-user>@${assigneeLogin}</mention-user> ${taskTitle}</comment>` : `<comment>${taskTitle}</comment>`;
```

![image](https://github.com/Expensify/App/assets/144037189/c7660a14-0186-42d2-a852-a91fd38bb959)

**Comment by ArekChr** [comment] 2023-10-05 14:04
[Proposal](https://github.com/Expensify/App/issues/28626#issuecomment-1747872928) from @dukenv0307 provides a correct solution to solve this issue, an account is missing in attributes.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by trjExpensify** [comment] 2023-10-09 17:01
@puneetlath can you [give this](https://github.com/Expensify/App/issues/28626#issuecomment-1747872928) a secondary review please to green light and move on?

**Comment by puneetlath** [comment] 2023-10-09 17:21
@dukenv0307's proposal looks good. You shouldn't even need the email address actually. You should be able to just use `<mention-user accountid="${taskAssigneeAccountID}"></mention-user>`

**Comment by ArekChr** [comment] 2023-10-16 11:59
- [x] Link to the PR: I'm unsure if should include this PR, but the feature displaying email/avatar was not designed at all in the `MentionUserRenderer` component. Here is the [PR](https://github.com/Expensify/App/issues/19089)
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by trjExpensify** [comment] 2023-10-16 17:58
> Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

Mind just elaborating on the "why?" here a touch?

**Comment by ArekChr** [comment] 2023-10-17 11:02
@trjExpensify If we don't have tests for any tooltip with username and avatar, then I suggest adding this test.

Regression test proposal.

1. Assign the task to any user.
2. Enter any title and go to the next step.
3. Assign the task to the user with an avatar and display the name set.
5. Hover on the @ user in the task message and ensure the tooltip displays the proper email and avatar.

Do we agree :+1: or :-1:

**Comment by trjExpensify** [comment] 2023-10-17 21:10
Woah, why are there so many payment holds in the title of this issue? 😅 

@ArekChr here's one of the regression tests for assigning a task. Perhaps we add it where I put it in bold below? 

<img width="540" alt="image" src="https://github.com/Expensify/App/assets/16232057/0dcad67f-b912-4be0-be0b-33252d907a57">

1. Navigate to a Group Chat
2. Click on the + in the compose box and select "Assign task"
3. Enter a a Title and a Description
4. Assign a user from the group that you have access to
5. Create the task
6. Verify you're navigated to the task "conversation"/report
7. Verify the assignee is displayed in the assignee field
8. **Verify the tooltip displays the email and avatar of the assignee**
9. Navigate back to the group conversation
10. Verify the task is displayed in the conversation history

**Comment by trjExpensify** [comment] 2023-10-23 15:32
okay, suggested that for Applause to add to the test case. Moving on to payments: 

- $50 to @dhanashree-sawant for the bug report
- $750 to @dukenv0307 for the bug fix & #urgency bonus as per [here](https://github.com/Expensify/App/issues/28626#issuecomment-1755861693).

**Closed** 2023-10-23 15:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by ArekChr** [comment] 2023-10-24 10:36
> @ArekChr here's one of the regression tests for assigning a task. Perhaps we add it where I put it in bold below?

Agree!
