### ISSUE TITLE
[$500] Android- Workspace- Unable to open workspaces that out of view after creating new workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45738] opened 2024-07-19 00:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in with an account that has several workspaces > 5 or create them
2. Navigate to the account settings > Workspaces
3. Create a new workspace
5. Return to the list of workspaces
6. Scroll down until the first 4 workspaces out of view
7. Open any workspace that in a view

## Expected Result:
User is able to open any workspace

## Actual Result:
User is unable to open workspaces that require to scroll to get accessed after creating a new workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4009452a-88cc-422d-9029-d17c6558827a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f764fe91b1e3b3b</li>
        <li>Upwork Job ID: 1814333041047712558</li>
        <li>Last Price Increase: 2024-08-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-07-19 00:25
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-19 00:25
We think that this bug might be related to #wave-collect - Release 1

**Comment by kabeer95** [comment] 2024-07-22 23:01
# Proposal
## Problem Statement
 After creating a new workspace, users are unable to open workspaces that are out of view, requiring scrolling to access them.

## Root Cause
 The root cause of this problem is that the code is not properly updating the workspace list after creating a new workspace, causing the out-of-view workspaces to become inaccessible.

##Proposed Solution 
To solve this problem, I propose updating the code to ensure that the workspace list is properly updated after creating a new workspace, allowing users to access all workspaces, including those that are out of view.

Changes To implement this solution, we need to make the following changes:

```
// Update the workspace list after creating a new workspace
public void createNewWorkspace(Workspace newWorkspace) {
    // Add the new workspace to the list
    workspaces.add(newWorkspace);
    
    // Refresh the workspace list
    workspaceListAdapter.notifyDataSetChanged();
}

// Ensure the workspace list is refreshed after creating a new workspace
public void onResume() {
    super.onResume();
    workspaceListAdapter.notifyDataSetChanged();
}

```
### Expected Result
 Users should be able to open any workspace, including those that are out of view, after creating a new workspace.

### Actual Result
 Users are unable to open workspaces that require scrolling to access after creating a new workspace.

## Alternative Solutions
Implementing a lazy loading mechanism to load workspaces only when they come into view, but this may cause performance issues.
Using a different data structure to store the workspace list, but this may require significant changes to the existing codebase.

**Comment by puneetlath** [comment] 2024-07-26 17:42
Still waiting for proposals.

**Comment by Kureev** [comment] 2024-07-30 14:28
Hi, I'm Alexey from Margelo, an expert agency and I can work on this issue.

Prev worked on:
- https://github.com/Expensify/App/issues/43612
- https://github.com/Expensify/App/pull/46173

**Comment by Kureev** [comment] 2024-07-30 17:01
I think I followed the script to the letter, but wasn't able to reproduce the behaviour:
https://github.com/user-attachments/assets/edc51521-4845-4af6-beae-246342bc62c0

**Comment by Kureev** [comment] 2024-07-30 17:09
In this case, I think I'll keep an eye on this one in the case someone will be able to reproduce.
In the meantime, I'll pick up a different issue :+1:

**Comment by puneetlath** [comment] 2024-07-30 19:15
Ok let's close it then. Thanks y'all.

**Comment by lanitochka17** [comment] 2024-08-06 17:00
Issue is still reproducible on the latest build 9.0.17-0 on Android

https://github.com/user-attachments/assets/255ba240-ac65-451c-a2a8-0205ddc0a7ff

**Comment by lanitochka17** [comment] 2024-08-07 20:51
@parasharrajat  Pixel 6 / Android 14
Samsung Galaxy S10+ / Android 12

**Comment by CyberAndrii** [comment] 2024-08-12 19:44
FYI, I can reproduce this and have a guess at what it could be. I'll test it tomorrow and let you all know.

**Comment by CyberAndrii** [comment] 2024-08-13 20:05
I think it is similar to https://github.com/facebook/react-native/issues/44643 and https://github.com/facebook/react-native/issues/36504. Using `onPressIn` or `onPressOut` [here](https://github.com/Expensify/App/blob/4496333dea008e0bd59ac3782ecd62be82483cfc/src/pages/workspace/WorkspacesListPage.tsx#L212) seems to fix it, but it isn't a valid solution in this case. I'm not sure if I'll be able to help with this any further, so feel free to have someone else take this on.

**Comment by puneetlath** [comment] 2024-08-15 17:18
@Kureev have you had a chance to look at it?

**Comment by chrispader** [comment] 2024-08-19 09:44
i'm going to take this over from @Kureev, because he is busy with other tasks right now

**Comment by chrispader** [comment] 2024-08-20 09:57
I cannot reproduce this on `main` on neither of two physical Android devices:

Samsung S10e:

https://github.com/user-attachments/assets/281c198d-57c3-4e1e-85a5-7bc5431ec787

Huawei P smart 2019:

https://github.com/user-attachments/assets/9dc63c1a-2e75-462a-a597-2e74647556a0

**Comment by chrispader** [comment] 2024-08-20 11:25
@lanitochka17 are there any more steps i need to make in order to be able to reproduce this?

**Comment by lanitochka17** [comment] 2024-08-20 16:14
@parasharrajat @chrispader  the same steps mentioned in the OP. Issue is still reproduce

https://github.com/user-attachments/assets/096fbe13-21c0-40ce-a9f1-53df0012c5b8

accounts: [applausetester+0529pm@applause.expensifail.com](mailto:applausetester+0529pm@applause.expensifail.com) (the one I tested today) and [applausetester+1407pm@applause.expensifail.com](mailto:applausetester+1407pm@applause.expensifail.com) (the one from the OP)

**Comment by chrispader** [comment] 2024-08-22 11:25
Still not reproducible on my accounts with the following devices:

- Samsung S10e (Android 12)
- Huawei P smart 2019 (Android 11)
- Samsung S21 (Android 14)

@parasharrajat @lanitochka17 is it possible to provide me a different account or one of either [applausetester+0529pm@applause.expensifail.com](mailto:applausetester+0529pm@applause.expensifail.com) or [applausetester+1407pm@applause.expensifail.com](mailto:applausetester+1407pm@applause.expensifail.com)?

**Comment by mvtglobally** [comment] 2024-08-23 12:06
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2024-08-27 19:18
Given that QA is also saying it's no longer reproducible, I'm going to go ahead and close this out. Thanks everyone.

**Closed by puneetlath** 2024-08-27 19:18 UTC
Labels: External, Daily, Overdue, Bug
