### ISSUE TITLE
Debug - There is no error message when selecting taxAmountChanged violation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53010] opened 2024-11-23 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/50745
## Action Performed:
1. Navigate to a workspace chat
2. Create a manual request with tax rate
3. Go to Settings > Troubleshoot > enable Debug mode
4. Go back to the IOU you have created on step 2
5. Open the IOU's transaction details page
6. Click on. Header > Debug > View transaction > Violations > Create > Save
7. Open the violation > click on 'name' > select taxAmountChanged > Save
8. Return to the transaction thread

## Expected Result:
Tax amount field should display violation

## Actual Result:
Tax amount field doesn't display violation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/74e0e9fa-18cd-48db-948f-becf0a42f8b6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JKobrynski</details>

**Comment by DylanDylann** [comment] 2024-11-23 16:21
cc @pac-guerreiro

**Comment by mountiny** [comment] 2024-11-25 12:35
@pac-guerreiro @DylanDylann please look into this as a regression from your PR

> The error message isn't displayed because we excluded taxAmountChanged  and taxRateChanged  [here](https://github.com/Expensify/App/blob/8c4661d85b0cfae50b6ab985a20d17c7fcad79f1/src/hooks/useViolations.ts#L53). Should we filter out two violations when we select the violation name in debug?

this is from @dukenv0307, I think @puneetlath will have better context from the linked PR too

**Comment by mountiny** [comment] 2024-11-25 12:37
also cc @fabioh8010

**Comment by pac-guerreiro** [comment] 2024-11-25 14:07
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment] 2024-11-25 20:58
@lanitochka17 @mountiny @DylanDylann @fabioh8010 

It seems that this violation is excluded in NewDot, that's why there's no message displayed:

<img width="695" alt="Screenshot 2024-11-25 at 20 57 35" src="https://github.com/user-attachments/assets/11b8593e-1ca6-40f2-944e-4aadf6211e34">

**Comment by mountiny** [comment] 2024-11-25 21:04
That would make sense to me

**Comment by puneetlath** [comment] 2024-11-25 21:27
Makes sense to me too.

**Comment by pac-guerreiro** [comment] 2024-11-25 22:47
I just opened a draft PR with the fix - https://github.com/Expensify/App/pull/53097

**Comment by pac-guerreiro** [comment] 2024-11-27 00:57
Today I added test steps and filled my checklist. I need to add screenshots / screen recordings tomorrow.

**Comment by pac-guerreiro** [comment] 2024-11-27 21:10
Just added the missing screen recordings. The PR is now ready for review 😄

This next week I'll be off, but someone from my team will take care of any feedback on this PR 😄

**Comment by JKobrynski** [comment] 2024-11-28 15:53
Hi, I'm Julian from Callstack and I'm going to work on this issue in Pedro's absence.

**Comment by DylanDylann** [comment] 2024-12-03 16:56
We already have a new PR to remove taxAmountChanged and taxRateChanged violations. I think we can close this one

**Comment by puneetlath** [comment] 2024-12-04 14:58
Ok sounds good. I've gone ahead and paid you for it since the full review was done before we decided to close.

**Closed by puneetlath** 2024-12-04 14:58 UTC
Labels: Reviewing, Engineering, Weekly
