### ISSUE TITLE
[HOLD #21219][$250] Android - Group - Inconsistency in showing group name in header in mweb & Android

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43068] opened 2024-06-04 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4593905
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open site in both mweb / Android
2. Open group chat with many members
3. Note the group name in header

## Expected Result:
There should be no Inconsistency in showing group name in header in mweb and Android

## Actual Result:
Inconsistency in showing group name in header in mweb and Android

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/88c1b9ff-9017-4607-9890-f0d15845022e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5db97bd918f3107</li>
        <li>Upwork Job ID: 1798817306448133295</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by kbecciv** [comment] 2024-06-04 20:39
We think that this bug might be related to #vip-vsb

**Comment by s77rt** [comment] 2024-06-07 16:16
@tienifr Thanks for the proposal. We don't need to set an explicit width to the container but making it flexible (grow to fit) makes sense. However your solution causes a regression where the caret is also moved

<img width="1346" alt="Screenshot 2024-06-07 at 5 04 28 PM" src="https://github.com/Expensify/App/assets/16493223/7f0fbcec-7721-4c45-8431-6094a7dbbca4">
<img width="1346" alt="Screenshot 2024-06-07 at 5 04 43 PM" src="https://github.com/Expensify/App/assets/16493223/b2ddc63a-a852-40e2-b98a-e8de0852538c">

**Comment by s77rt** [comment] 2024-06-08 09:30
@tienifr Can you elaborate on where this style should be applied? After making the text flexible (grow) the justify content styling on the container won't have any effect

**Comment by s77rt** [comment] 2024-06-10 17:11
@tienifr I believe that's an unwanted change.

**Comment by s77rt** [comment] 2024-06-11 18:52
@tienifr That solution didn't fix the problem for me. It seems that it helps in some cases but not all, e.g. try with `Abdelhafidh, admin+ctt@abdelhafidh.com, fgfdgd@azeazerr.ezaa, gefrere@rezrerezre.caea`

<img width="480" alt="Screenshot 2024-06-11 at 7 52 06 PM" src="https://github.com/Expensify/App/assets/16493223/159907f0-6b45-4d7d-baba-7945ea8969f1">

**Comment by s77rt** [comment] 2024-06-17 23:06
Still looking for proposals

**Comment by s77rt** [comment] 2024-06-20 23:19
Still looking for proposals

**Comment by s77rt** [comment] 2024-06-24 18:29
Still looking for proposals...

**Comment by s77rt** [comment] 2024-06-27 22:14
Still looking for proposals...

**Comment by s77rt** [comment] 2024-07-01 20:11
Not overdue. Still looking for proposals

**Comment by mvtglobally** [comment] 2024-07-03 14:34
Issue not reproducible during KI retests. (First week)

**Comment by deetergp** [comment] 2024-07-03 20:04
🤞 Hopefully it is the same next week. If it is let's close this.

**Comment by s77rt** [comment] 2024-07-04 18:36
Still reproducible and looking for proposals
<img width="480" alt="Screenshot 2024-07-04 at 7 36 17 PM" src="https://github.com/Expensify/App/assets/16493223/bab63070-f636-466a-bf27-52e14a05f5eb">

**Comment by s77rt** [comment] 2024-07-08 19:09
Still looking for proposals

**Comment by s77rt** [comment] 2024-07-11 16:12
Same ^

**Comment by s77rt** [comment] 2024-07-12 16:46
@Krishna2323 Thanks for the proposal. Can we apply same solution for the group name menu item and LHN? This keeps popping in many places, any idea how to solve this once and for all?

<img width="480" alt="Screenshot 2024-07-12 at 5 45 25 PM" src="https://github.com/user-attachments/assets/35c4fcf3-b058-4467-96bf-e55812dc11e1">
<img width="480" alt="Screenshot 2024-07-12 at 5 45 28 PM" src="https://github.com/user-attachments/assets/dd51f3f0-633d-4a2e-9f41-9501c14d23b8">
<img width="480" alt="Screenshot 2024-07-12 at 5 45 32 PM" src="https://github.com/user-attachments/assets/2f964b07-a5bf-4592-8f53-d83d545a26ca">

**Comment by s77rt** [comment] 2024-07-15 10:54
@Krishna2323 This seems to be a bug in RN. Maybe we can create a minimal reproducible example, open an issue and follow up with a PR

**Comment by s77rt** [comment] 2024-07-16 16:47
@Krishna2323 Do you have some links to those issues and/or a reproducible example? We should push to fix this upstream

**Comment by s77rt** [comment] 2024-07-17 19:23
@Krishna2323 This PR https://github.com/facebook/react-native/pull/41770 seems promising and it could fix this bug too

**Comment by bernhardoj** [comment] 2024-07-18 05:33
I think this kind of issue is being tracked here https://github.com/Expensify/App/issues/21219

**Comment by mvtglobally** [comment] 2024-07-19 03:20
Issue not reproducible during KI retests. (Second week)

**Comment by s77rt** [comment] 2024-07-29 18:14
@deetergp Let's put this on hold https://github.com/Expensify/App/issues/43068#issuecomment-2245932778

**Comment by deetergp** [comment] 2024-08-02 21:29
Still on hold so making this weekly for now.

**Comment by mvtglobally** [comment] 2024-08-03 04:07
Issue not reproducible during KI retests. (Third week)

**Comment by deetergp** [comment] 2024-08-05 15:56
If it hasn't been reproducible for the last three weeks, I think we can close it.

**Closed by deetergp** 2024-08-05 15:56 UTC
Labels: External, Engineering, Weekly, Help Wanted
