### ISSUE TITLE
 Date field is not properly aligned horizontally with the corresponding field names.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14567] opened 2023-01-25 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Select any workspace
2. Fill in account and routing information
3. Fill in personal and company information
4. Fill in an incorporation date and also the date of birth on the next page

## Expected Result:
Proper alignment of a date value and field name.

## Actual Result:
 It seems the date of birth and incorporation date values are out of indentation, unlike other fields on the same page.

## Workaround:
Visual

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome

**Version Number:** 1.2.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/214692418-9754545a-b4d1-4b99-a008-8a68c5cd98e7.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/214692422-2c639b47-6b76-4651-8e8f-f390d9fa8197.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/214692426-2390c5ce-5e26-4b35-a0c7-26d70e79264e.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/214692458-9741d51d-b87e-439c-8640-a61f97237426.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674632490070499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment] 2023-01-26 21:52
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by arielgreen** [comment] 2023-01-26 21:54
@kavimuru @priya-zha, the reproduction steps here are not clear; please expand.

**Closed by arielgreen** 2023-01-26 21:54 UTC
Labels: Daily, Needs Reproduction, Bug
