### ISSUE TITLE
[$250] Workspace money request preview containing a receipt is misaligned

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#29432] opened 2023-10-12 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.83-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697106057487319

## Action Performed:
Break down in numbered steps

1. Navigate to a workspace chat and request money by scanning a receipt.
2. Make another Cash request (manual) in the same report.
3. Click on the report preview (which should show (2 requests, 1 scanning) to navigate to the expense report

## Expected Result:
Report actions should be aligned vertically

## Actual Result:
The report action containing a receipt is misaligned with the rest of actions

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

![image](https://github.com/Expensify/App/assets/9680864/fd9a50d7-e1de-4e45-a7e4-9d2185e9138c)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![image](https://github.com/Expensify/App/assets/9680864/3eb7740f-efbb-40e1-8777-295fd2df6801)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbfa9d25d515c5d1</li>
        <li>Upwork Job ID: 1712445239356387328</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by youssef-lr** [comment] 2023-10-12 12:29
I think this is the faulty component

Production
![image](https://github.com/Expensify/App/assets/9680864/2ad9c8c4-075f-4129-acfc-9f7628e0fd98)

Staging
![image](https://github.com/Expensify/App/assets/9680864/8eb5cb97-1ddc-4513-afe4-69808ca46cef)

**Comment by Samueljh1** [comment] 2023-10-12 12:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace money request preview containing a receipt is misaligned

### What is the root cause of that problem?
Avatar picture is scaled incorrectly

### What changes do you think we should make in order to solve the problem?
Fix the Avatar picture styling, to ensure it is square and does not misalign the chat bubbles.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2023-10-12 12:37
@Samueljh1 and anyone making proposals, can you please link a PR from this list https://github.com/Expensify/App/issues/29417#issuecomment-1759447233 in staging which caused the regression.

What styling specifically changed and needs to be changed @Samueljh1 ?

**Comment by Pujan92** [comment] 2023-10-12 13:11
Thanks @hungvu193 , I will check it.

**Comment by youssef-lr** [comment] 2023-10-12 13:46
@Pujan92 any update please?

**Comment by Pujan92** [comment] 2023-10-12 13:47
Yes, PR will be up in 10 mins.

**Comment by Pujan92** [comment] 2023-10-12 14:07
[PR](https://github.com/Expensify/App/pull/29447) is ready for review!
cc: @jjcoffee @srikarparsi

**Comment by mountiny** [comment] 2023-10-12 18:19
<img width="492" alt="image" src="https://github.com/Expensify/App/assets/36083550/304aa043-195f-4d28-8199-15b1a8e1847f">
 fixed in staging

**Closed by mountiny** 2023-10-12 18:19 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug
