### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Not found page appear briefly after updating the first approver

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51282] opened 2024-10-22 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729573070656459

## Action Performed:
1. Create a new workspace with at least 2 members
2. Enable workflow -> enable Add approvals
3. Change the first approval
4. Click save button
## Expected Result:
 `not found page` should not display

## Actual Result:
 `not found page` is displayed briefly

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/941bbae3-7682-4bf4-9321-2bd40abff472

https://github.com/user-attachments/assets/8e14903e-2983-4bef-a2e1-fc751a049816

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851668069597317065</li>
        <li>Upwork Job ID: 1851668069597317065</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 104771833</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by DylanDylann** [comment] 2024-10-23 01:28
@JmillsExpensify I discovered this bug and have more context because I was also the main C+ on the approval workflow feature. I am happy to take this issue as C+ if it is external

 This bug is handled on removing flow on https://github.com/Expensify/App/issues/48089 and we also fix for this case where users update the first approver

**Comment by bernhardoj** [comment] 2024-10-23 02:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A not found is shown after updating the first approver.

### What is the root cause of that problem?
The not found will show if the current approval workflow isn't found.
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L92-L93

The current approval workflow finds the workflow where the approver is the same as the first approver route params.
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L87

When we open the page with the first approver of A, then update it to B, A won't be in the approver list anymore, so current approval workflow can't be found.

### What changes do you think we should make in order to solve the problem?

Instead of using navigation focused state to prevent the not found page (which is not reliable IMO), we can prevent the current approval workflow data to be updated when we are submitting the update. To do that, we need 2 new ref.
```
const isUpdatedRef = useRef(false);
const prevApprovalData = useRef({});
```

`isUpdatedRef` tells whether the user updates the data or not. `prevApprovalData` contains the previous approval workflow data.

Set `isUpdatedRef` to true when updating the data.
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L41-L55

Store the approval data to `prevApprovalData` so we can use it later and return the `prevApprovalData` if `isUpdatedRef` is true.

https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L70-L89
```
const {currentApprovalWorkflow, defaultWorkflowMembers, usedApproverEmails} = useMemo(() => {
    if (!policy || !personalDetails) {
        return {};
    }

    if (isUpdatedRef.current) {
        return prevApprovalData.current;
    }

    const defaultApprover = policy?.approver ?? policy.owner;
    const firstApprover = route.params.firstApproverEmail;
    const result = convertPolicyEmployeesToApprovalWorkflows({...});

    const approvalData = {
        defaultWorkflowMembers: result.availableMembers,
        usedApproverEmails: result.usedApproverEmails,
        currentApprovalWorkflow: result.approvalWorkflows.find((workflow) => workflow.approvers.at(0)?.email === firstApprover),
    };
    prevApprovalData.current = approvalData;
    return approvalData;
}, [personalDetails, policy, route.params.firstApproverEmail]);
```

**Comment by JmillsExpensify** [comment] 2024-10-30 16:51
Opened up to C+ for review. Please make sure to see the comment from @DylanDylann in the review process, as this bug report wouldn't exist unless he reported it.

**Comment by DylanDylann** [comment] 2024-11-04 18:10
Thanks. reviewing now

**Comment by DylanDylann** [comment] 2024-11-05 06:00
Thanks everyone.

I prefer to go with @daledah's [proposal](https://github.com/Expensify/App/issues/51282#issuecomment-2429976093) because it is simpler and their way already be used widely in other places

🎀 👀 🎀 C+ Reviewed

**Comment by DylanDylann** [comment] 2024-11-28 03:50
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by JmillsExpensify** [comment] 2024-12-03 09:21
Payment summary:

 - Contributor: $250 @daledah via Upwork
 - Reviewer: $250 @DylanDylann via Upwork

**Comment by JmillsExpensify** [comment] 2024-12-03 09:26
Regression test created and one contributor payment made.

**Comment by JmillsExpensify** [comment] 2024-12-09 09:16
All paid out.

**Closed by JmillsExpensify** 2024-12-09 09:16 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
