### ISSUE TITLE
Payment DUE[$500] Profile - Inconsistent validation error message for required field in home address

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27263] opened 2023-09-12 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to personal details
2. Click in home address
3. Address line 1 is required field, when user goes from line 1 to address line2 without entering anything , error is shown
4. Click on country, a drop down is shown
5. Don’t select any country and come back
6. Enter state and city and zip code and click save
7. Only on clicking save , it shows country is required field

## Expected Result:
When country is not selected from drop down it should show validation error

## Actual Result:
Not showing until save is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d589ec2e-6a6a-483a-a76f-f37a9599fa78

https://github.com/Expensify/App/assets/115492554/b34bc5a2-9792-481f-b970-e73c7135aaae

**Expensify/Expensify Issue URL:**

**Issue reported by:** @premsjce

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694136012916349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
Inconsistent validation error message for required field in home address

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012751697148f06172</li>
        <li>Upwork Job ID: 1701622320141500416</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by saraelsa** [comment] 2023-09-12 16:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is an inconsistency in behavior between two required fields:
- If the user blurs address line 1, a validation message is immediately displayed.
- If the user closes the country selection menu, a validation message is not immediately displayed, and is only displayed once the form is submitted.

### What is the root cause of that problem?

The `Form` component attaches certain event listeners to form elements, including `onInputChange` and `onBlur`. Depending on the configuration, validation is run for a field when the `onBlur` event fires.

The `CountryPicker` component exposes an `onInputChange` prop that is used by the `Form` component which is how it is able to pick up its value. However, it does not expose a similar `onBlur` prop that the `Form` component might use.

### What changes do you think we should make in order to solve the problem?


Create a new property, `onBlur`, in `CountryPicker`. The `hidePickerModal` method will fire `onBlur`.

### What alternative solutions did you explore? (Optional)

None.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Yrds** [comment] 2023-09-12 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There are two inconsistencies related to validation triggers on `Home address` Form:

- `Address line 1` text input required field error is shown as soon the user blur on field.
- `Country` picker is not being validated as the user closes picker, and only shows validation when user click on `submit` button.

### What is the root cause of that problem?

#### Address Line 1

- The `Address Line 1` validations is showing up on input blur because the `AddressSearch` component triggers `props.onBlur` which is calling `validate` function on `Form` component(`validate` method is called on every `onBlur` event).

#### Country picker 

- `CountryPicker` component doesn't have any trigger when user closes it(when `hidePickerModal` is called), so there's nothing to perform a validation this moment.

### What changes do you think we should make in order to solve the problem?

- As `Form` component is used in multiple pages, the `AddressSearch` component need to be modified to conditionally NOT call `onBlur`. 
- `CountryPicker` needs to trigger `onInputChange` in order to call proper validation method when user closes modal.

### What alternative solutions did you explore? (Optional)

No alternative solutions was explored.

**Comment by Yrds** [comment] 2023-09-12 18:20
Contributor details
Your Expensify account email: yrds96@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fe692a84ada2b658

**Comment by redpanda-bit** [comment] 2023-09-12 18:40
I think calling the `onBlur` prop within `CountryPicker#hidePickerModal` is the right approach.

@yrds 

> ### What changes do you think we should make in order to solve the problem?
> * As `Form` component is used in multiple pages, the `AddressSearch` component need to be modified to conditionally NOT call `onBlur`.

We want to show the error on input blur so probably would want to keep it as it is now.

> * `CountryPicker` needs to trigger `onInputChange` in order to call proper validation method when user closes modal.

I tried this solution while doing my analysis but using `onBlur` already calls the proper validation method.

**Comment by Yrds** [comment] 2023-09-12 18:44
Yes, I think you are right. Also, calling `onBlur` seems to be the default behavior of other Form components of the application.

**Comment by zanyrenney** [comment] 2023-09-15 16:38
@situchan what are your thoughts on the above please?

**Comment by tjferriss** [comment] 2023-09-18 03:34
@zanyrenney it looks like MelvinBot assigned us both. I'm going to unassign myself.

**Comment by zanyrenney** [comment] 2023-09-21 03:47
weird, okay no worries @tjferriss

**Comment by zanyrenney** [comment] 2023-09-25 09:34
bump @situchan curious for your thoughts please.

**Comment by situchan** [comment] 2023-09-26 11:35
@Expensify/design do you agree this is bug and should be fixed for consistency?

Here's simplified video:

https://github.com/Expensify/App/assets/108292595/b9d72fc8-c467-4e78-9b90-42cf62871426



Summary:
- when blur text input, form error shows
- when "blur" picker, form error doesn't show
- when click Save, both errors show

**Comment by shawnborton** [comment] 2023-09-27 01:39
Hmm honestly, I feel like we shouldn't be showing **any** of these form errors on blur - we should just wait until the user submits the entire form. Curious if @Expensify/design and @JmillsExpensify @trjExpensify agree with me here.

**Comment by situchan** [comment] 2023-09-27 03:21
Also cc: @luacmartins who is form expert

**Comment by trjExpensify** [comment] 2023-09-27 08:38
We chatted about this briefly earlier. @luacmartins @marcaaron do you have something more concrete to point to on why this approach of validating on blur was favoured initially? 

From taking a quick re-skim of the forms doc, it was perhaps down to having a consistent approach irrespective of whether there's a confirmation button or not to press for validation?

**Comment by marcaaron** [comment] 2023-09-29 04:30
**main context:** https://expensify.slack.com/archives/C020EPP9B9A/p1632857074062800

Just was proposed with unanimous support. 😄 I don't think it has to do with consistency between forms with buttons and one's without. It's just a better user experience to be told that you need to pass some value sooner than later.

That said, we might want to amend this to "only show an error when we blur AND there is a value". I generally agree with the proposal to make these errors appear on blur with consistency. Open to other thoughts on it though.

**Comment by zanyrenney** [comment] 2023-09-29 04:32
Thanks for the additional thoughts @marcaaron

**Comment by trjExpensify** [comment] 2023-09-29 05:08
>That said, we might want to amend this to "only show an error when we blur AND there is a value". 

I think this would be a good improvement. 👍 It would make the forms feel less jarring.

**Comment by saraelsa** [comment] 2023-09-29 05:12
> **main context:** https://expensify.slack.com/archives/C020EPP9B9A/p1632857074062800
> 
> Just was proposed with unanimous support. 😄 I don't think it has to do with consistency between forms with buttons and one's without. It's just a better user experience to be told that you need to pass some value sooner than later.
> 
> That said, we might want to amend this to "only show an error when we blur AND there is a value". I generally agree with the proposal to make these errors appear on blur with consistency. Open to other thoughts on it though.

I've updated my proposal's 'Alternative Solutions' section to suggest how this amendment can be implemented.

**Comment by marcaaron** [comment] 2023-09-29 08:53
Maybe can take it to #product? I don't feel super passionate, but think the current guidelines are pretty good (but obviously we are out of bounds in following them in this case).

There's a totally separate (mostly technical) argument here that any form field input passed to the Form library should have a working blur and focus methods. So, the ones here are in violation in any case because they clearly don't work.

**Comment by zanyrenney** [comment] 2023-10-02 09:30
Seems like quite a few different perspectives so took this to slack and tagged people who had been involved in the conversation. https://expensify.slack.com/archives/C03U7DCU4/p1696238990653479

**Comment by zanyrenney** [comment] 2023-10-04 11:57
Hey @situchan after discussing internally:

we want to move ahead with this fix. The underlying issue is that a Form compatible component either wasn’t designed properly or regressed i.e. it’s onBlur method doesn’t seem to work at all (or maybe is absent).

Can you ensure you review all the proposals with this in mind? Thanks!

**Comment by zanyrenney** [comment] 2023-10-10 09:55
bump @situchan please respond. If you are over capacity, please let me know and we can reassign this.

**Comment by situchan** [comment] 2023-10-10 10:07
No satisfactory proposals yet to meet the agreed behavior.

**Comment by saraelsa** [comment] 2023-10-10 12:14
> No satisfactory proposals yet to meet the agreed behavior.

From the reply

**Comment by saraelsa** [comment] 2023-10-10 12:16
> No satisfactory proposals yet to meet the agreed behavior.

From the reply history here, it seems that it's concluded that:
- the issue is because of a non-functional or absent `onBlur` event handler;
- the solution is to ensure that that method is present and functions; and,
- the desired behavior is that the field validates on blur.

[My proposal](https://github.com/Expensify/App/issues/27263#issuecomment-1716049025) addresses and resolves all of these points. I encourage you to take another look at it.

Thanks!

**Comment by zanyrenney** [comment] 2023-10-12 12:17
please re-review @saraelsa proposal?

**Comment by situchan** [comment] 2023-10-12 12:23
@saraelsa can you explain your solution in more detail?

> Create a new property, `onBlur`, in `CountryPicker`. The `hidePickerModal` method will fire `onBlur`.

When to call `onBlur`?

**Comment by saraelsa** [comment] 2023-10-12 12:49
> @saraelsa can you explain your solution in more detail?
> 
> > Create a new property, `onBlur`, in `CountryPicker`. The `hidePickerModal` method will fire `onBlur`.
> 
> When to call `onBlur`?

In the `hidePickerModal` (`CountryPicker/index.js`, line 41) function after `setIsPickerVisible(false)`.

**Comment by zanyrenney** [comment] 2023-10-16 14:29
Bump @situchan as we have more detail from the contributore with the leading proposal. Can you review please?

**Comment by situchan** [comment] 2023-10-16 14:43
If we wanna introduce `onBlur` method on any form component, the solution should be general.
So we're still waiting for proposal with comprehensive solution.

**Comment by saraelsa** [comment] 2023-10-16 22:44
The mechanism is already general: `Form` expects certain handlers to be present on form components, and one of these handlers is `onBlur`.

`CountryPicker` should have had this handler, but it doesn't, leading to an inconsistency. The solution is to add this missing handler.

As far as other form components are considered, they should already have an `onBlur` handler, and if they don't, it's an independent bug relating to those components. The general solution—attaching to the `onBlur` property of each form component—already exists in `Form`.

**Comment by situchan** [comment] 2023-10-20 13:06
@saraelsa do you mind sharing demo video?

**Comment by saraelsa** [comment] 2023-10-20 15:19
After pulling the latest changes from the repository, it appears that the structure of `CountryPicker` has been completely changed:

- A `CountrySelector` component is now used.
- It uses RHN navigation and communicates via a query parameter in the URL. There is no event from which we can call `onBlur`.

My solution is no longer valid after these changes.

I have come up with an alternative solution, but it is not as simple:

- Add the `onBlur` prop as with previous solution.
- Add an additional prop to `CountrySelector`, `isFocused`, that is to be populated with whether it is currently active or not.
- The `CountrySelector` component keeps tracked of the previous `isFocused`. When `isFocused` changes to `false` (as determined by an effect) and the previous value was `true`, `onBlur` will be called.
- The `AddressPage` will maintain state `isCountrySelectorFocused`. This is done by comparing the active route against `ROUTES.SETTINGS_PERSONAL_DETAILS_ADDRESS_COUNTRY`. I'm not sure what the best way is to do this, but in my demo I have used `useNavigation` and created an effect that attaches a listener on the navigation state.
- This is passed down to `CountrySelector`.

Here is a demo video showing the solution working: https://1drv.ms/v/s!AloXNUjpQ03Lj2bNdYl_eBY0sx5p?e=zzTRjQ

**Comment by zanyrenney** [comment] 2023-10-23 12:58
bump @situchan please review.

**Comment by situchan** [comment] 2023-10-24 07:46
I don't see any satisfactory proposal yet with holistic solution.

Example case:
The date field is definitely blurred but not showing error message until Save button is clicked which validates all form inputs.


https://github.com/Expensify/App/assets/108292595/b7c8c5d0-e1af-48e0-b265-8481a21c059d

**Comment by zanyrenney** [comment] 2023-10-26 13:18
Can we not just mirror that behaviour then? That feels like a simple proposal to me.

**Comment by zanyrenney** [comment] 2023-10-26 13:18
@situchan

**Comment by situchan** [comment] 2023-10-26 14:18
It's mirror at a first glance but not actually.
@saraelsa update on https://github.com/Expensify/App/issues/27263#issuecomment-1776693015?

**Comment by saraelsa** [comment] 2023-10-26 17:26
I checked that DatePicker and the underlying issue is completely different.

It already exposes an `onBlur` property linked to the underlying `onBlur` event of the `TextInput`. If you notice, it will validate on blur on web environments.

I tried it out on iOS, and, like in your video, it didn't validate on blur. It appears that iOS (and maybe Android—I'm having some trouble with my emulator and am currently figuring that out) does not emit `onBlur` on `TextInput` once the date picker modal is dismissed.

The solution is to update `DatePicker/index.ios.js` to call `onBlur` in the `selectDate` event handler function.

**Comment by situchan** [comment] 2023-10-29 18:41
ok, date picker can be out of scope.
@saraelsa would you mind sharing test branch?

**Comment by saraelsa** [comment] 2023-10-30 02:11
Here you go: https://github.com/saraelsa/expensify-app/tree/fix/27263

Slight changes from my description: I kept the entire logic inside `CountrySelector` rather than being split across `CountrySelector` and `AddressPage`.

**Comment by zanyrenney** [comment] 2023-11-01 14:32
bump @situchan for a review.

**Comment by saraelsa** [comment] 2023-11-01 15:45
@situchan Please also let me know if you open a new issue for the date picker so that I can create a proposal there.

**Comment by zanyrenney** [comment] 2023-11-06 18:10
bump @situchan 

also in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1699294212635109

**Comment by situchan** [comment] 2023-11-06 18:15
@saraelsa I think we're waiting for general solution. But your branch made changes to country picker only.
We should apply same to all push-to-page pickers in Form.

**Comment by saraelsa** [comment] 2023-11-06 20:48
> @saraelsa I think we're waiting for general solution. But your branch made changes to country picker only. We should apply same to all push-to-page pickers in Form.

I have updated the branch to include all pickers. Pickers included: DatePicker, StatePicker and ValuePicker.

(Note: ValuePicker is not currently included inside Form anywhere but may be included in the future.)

**Comment by zanyrenney** [comment] 2023-11-09 16:19
@situchan could you please prioritise this one or lets get another c+ ?

**Comment by situchan** [comment] 2023-11-09 16:28
@ishpaul777 @saraelsa 
We don't prioritize accessibility at the moment but once we decide to resemble focus behavior, I think it should be supported as well.
As you see, text input is blurred when tab changes

https://github.com/Expensify/App/assets/108292595/42c35547-6994-4150-befe-cdd27213eca2

**Comment by situchan** [comment] 2023-11-09 16:30
I'd like to confirm with engineer if we should go ahead or not in advance. 🎀 👀 🎀
If we decide to close as won't fix, contributors will be wasting time.

**Comment by situchan** [comment] 2023-11-09 16:41
> Showing a error only make sense as user has not selected any country and returned back to screen if user dont even intended(just passed by) to select a country showing a error does not make sense (opinion)

Kind of agree. But I still think this entire GH is mysterious behavior.
Does your proposed solution also work when deep link to country selector page and then click Back button?

**Comment by saraelsa** [comment] 2023-11-09 17:34
> @ishpaul777 @saraelsa We don't prioritize accessibility at the moment but once we decide to resemble focus behavior, I think it should be supported as well. As you see, text input is blurred when tab changes
> 
>  Screen.Recording.2023-11-09.at.10.26.59.PM.mov

@situchan My solution doesn't change any focus behavior. Do you have any feedback?

**Comment by thienlnam** [comment] 2023-11-10 09:19
I skimmed the issue, but we're determining whether we should show an error message on dropdown if you didn't select a value or not?

**Comment by situchan** [comment] 2023-11-10 09:27
> if you didn't select a value

This means that when click back button on picker push-to-page

**Comment by thienlnam** [comment] 2023-11-10 09:40
Yeah I'm not sure we need to fix this, the changes would touch a lot of flows and the current flow seems fine..

**Comment by situchan** [comment] 2023-11-10 09:41
So what we're going to achieve here is:
input focus = picker page open
input blur = picker page close

**Comment by thienlnam** [comment] 2023-11-10 10:19
Hmm, I mean we could make this change though I don't know if we always want to show an error when you go back from a picker push to page. Considering we do handle this for text inputs I guess we could also do this for dropdown / pickers.

Like you mentioned, let's have a proposal that handles all these cases then

**Comment by saraelsa** [comment] 2023-11-10 12:48
That is exactly what my solution accomplishes and I had recently implemented it for all known pickers.

@situchan Do you have any feedback on it?

https://github.com/saraelsa/expensify-app/tree/fix/27263

**Comment by zanyrenney** [comment] 2023-11-13 11:19
@situchan please can you prioritise feedback here?

**Comment by situchan** [comment] 2023-11-13 11:21
yes, on my list today

**Comment by zanyrenney** [comment] 2023-11-15 10:50
What was the latest? @situchan

**Comment by situchan** [comment] 2023-11-15 11:16
Let's try to make BaseSelector component and send events to parent component there.
The solution should be super simple. Just call onFocus on component mount, onBlur on unmount.

**Comment by situchan** [comment] 2023-11-15 11:18
I don't like anyone's solution yet

**Comment by situchan** [comment] 2023-11-15 11:21
@zanyrenney can you please remove Internal and add External again to get more experienced contributors' proposals?
This seems slipped off from their radar.

**Comment by situchan** [comment] 2023-11-15 12:55
Please also consider this case when deeplink to selector and press back button without anything selected


https://github.com/Expensify/App/assets/108292595/4ce4895d-9b21-48fa-ad36-d923ed318652

**Comment by zanyrenney** [comment] 2023-11-20 17:06
I have reapplied the labels as you requested @situchan

**Comment by situchan** [comment] 2023-11-20 17:08
> I have reapplied the labels as you requested @situchan - but it didn't assign anyone else. just you :)

Ah yes, Jack already did earlier today.

We're still waiting for solution.

**Comment by situchan** [comment] 2023-11-20 17:37
My suggestion might not be correct. You can always research for better solution.

**Comment by DylanDylann** [comment] 2023-11-21 17:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- No required field validation on no value select on new dropdowns like state (validation works on older dropdown)

### What is the root cause of that problem?
- With the ```StatePicker``` component, blurring from it does not trigger the ```onBlur``` callback function that we have handled in ```Form``` component like others input
https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/components/Form.js#L349-L356
- Because the ```setTouchedInput(inputID)``` is not called, so it will not display error.
### What changes do you think we should make in order to solve the problem?
- We need to call ```setTouchedInput(inputID)``` **manually** with this type of input by:
1. In [Form](https://github.com/Expensify/App/blob/main/src/components/Form.js) component, expose the ```formRef``` with method ```setTouchedInput``` like:
```
useImperativeHandle(ref, () => ({
    setTouchedInput
    },
  }));
```
2. In [StatePicker](https://github.com/Expensify/App/blob/main/src/components/StatePicker/index.js) component, we import the above ref, then once we click on ```MenuItem```, call the ```setTouchedInput```:
- Also we should apply this logic to others similar inputs

### What alternative solutions did you explore? (Optional)

- NA

**Comment by zanyrenney** [comment] 2023-11-27 13:36
https://expensify.slack.com/archives/C01GTK53T8Q/p1701092193003339

**Comment by situchan** [comment] 2023-11-27 13:46
@DylanDylann I got confused about your RCA. This is new feature, never implemented before. But it sounds like "Bug" happening due to current Form implementation.

**Comment by situchan** [comment] 2023-11-27 13:47
No matter which Form is used, I think this should work always

**Comment by DylanDylann** [comment] 2023-11-27 13:51
@situchan 
> No matter which Form is used, I think this should work always

Yeah. But because we are refactoring to use ```FormProvider``` so I think we just need to fix the bug in case using ```FormProvider```

**Comment by DylanDylann** [comment] 2023-11-27 13:52
@situchan 
>  I got confused about your RCA. This is new feature, never implemented before. But it sounds like "Bug" happening due to current Form implementation.

What is "this" that you are mentioning?

**Comment by situchan** [comment] 2023-11-27 15:13
What is "this" that you are mentioning?

https://github.com/Expensify/App/issues/27263

**Comment by situchan** [comment] 2023-11-27 15:21
> @situchan
> 
> > No matter which Form is used, I think this should work always
> 
> Yeah. But because we are refactoring to use `FormProvider` so I think we just need to fix the bug in case using `FormProvider`

Makes sense as we'll eventually use FormProvider for all forms

https://github.com/Expensify/App/pull/30568 was merged but still using legacy Form.
@DylanDylann you know the issue or PR that migration is being worked on?

**Comment by DylanDylann** [comment] 2023-11-27 15:31
@situchan I do not know. Just asked the internal team about it https://github.com/Expensify/App/issues/25397#issuecomment-1828059494

**Comment by DylanDylann** [comment] 2023-11-27 17:28
@situchan 
> @DylanDylann you know the issue or PR that migration is being worked on?

https://github.com/Expensify/App/issues/32064

**Comment by situchan** [comment] 2023-11-27 17:29
Nice! @zanyrenney we can hold this for #32064

**Comment by thienlnam** [comment] 2023-11-27 18:11
Good call, added the hold for that issue https://github.com/Expensify/App/issues/32064

**Comment by DylanDylann** [comment] 2023-12-15 05:29
@thienlnam PR related to 32604 is already merged

**Comment by thienlnam** [comment] 2023-12-15 19:14
So let's first
1. Check if the bug is still reproducible
2. If so, seems like we can go with the original proposal to fix the bug using FormProvider

**Comment by DylanDylann** [comment] 2023-12-15 19:16
@thienlnam Yeah, I`ve tested and can reproduce it

**Comment by DylanDylann** [comment] 2023-12-21 07:43
@situchan I think you can review the proposals now because the bug is still reproducible

**Comment by thienlnam** [comment] 2024-01-02 23:49
@situchan When you get a chance, can you review the proposals and recommend a path forward?

**Comment by DylanDylann** [comment] 2024-01-09 10:47
@situchan what do you think about my [proposal](https://github.com/Expensify/App/issues/27263#issuecomment-1821387710) based on the latest main?

**Comment by zanyrenney** [comment] 2024-01-12 10:34
bump @situchan please can you review the proposal?

**Comment by situchan** [comment] 2024-01-12 11:27
Ah forgot that hold was lifted. reviewing latest proposals

**Comment by thienlnam** [comment] 2024-01-22 08:52
@situchan Bump again here

**Comment by situchan** [comment] 2024-01-29 16:48
@DylanDylann can you please share test branch?

**Comment by DylanDylann** [comment] 2024-01-29 18:22
@situchan Here is the test branch https://github.com/Expensify/App/pull/35326

**Comment by DylanDylann** [comment] 2024-02-01 11:28
@situchan Do you have any feedback about this [one](https://github.com/Expensify/App/issues/27263#issuecomment-1915140579)?

**Comment by zanyrenney** [comment] 2024-02-08 16:36
bump @situchan

**Comment by situchan** [comment] 2024-02-08 17:02
Ah this was missing in my list. Maybe because of weekly

**Comment by DylanDylann** [comment] 2024-02-15 18:55
@situchan Any update here?

**Comment by situchan** [comment] 2024-02-15 18:57
Thanks for the bump. I will update in an hr

**Comment by situchan** [comment] 2024-02-15 20:08
@DylanDylann's [proposal](https://github.com/Expensify/App/issues/27263#issuecomment-1821387710) looks good to me

**Comment by DylanDylann** [comment] 2024-02-16 03:53
@thienlnam Please help to review when you have a chance. Thanks

**Comment by DylanDylann** [comment] 2024-02-19 10:27
Will open PR today

**Comment by DylanDylann** [comment] 2024-02-19 18:41
@situchan PR https://github.com/Expensify/App/pull/35326 is ready to review

**Comment by situchan** [comment] 2024-03-06 16:57
PR was deployed to production on Feb 28

**Comment by DylanDylann** [comment] 2024-03-12 03:07
@zanyrenney Please help to process the next step

**Comment by zanyrenney** [comment] 2024-03-18 14:05
**payment summary**

paid $500 @situchan 
paid $500 @DylanDylann

**Closed by zanyrenney** 2024-03-18 14:05 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
