### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] [Dupe detect] Not here page opens when opening distance receipt from another workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50107] opened 2024-10-02 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create two workspaces.
3. Submit a distance expense in the first workspace chat.
4. Submit the same distance expense in the second workspace chat.
5. Submit another expense to the second workspace chat (as we cannot review duplicates when there is only one expense).
6. Go to transaction thread of the second expense in Step 4.
7. Click Review duplicates.
8. Click on the second distance expense preview (to make Keep this one button appear).
9. Click browser back button.
10. Click Keep this one on the second expense preview.
11. Click on the receipt on the confirmation page.

## Expected Result:
The receipt opens without issue.

## Actual Result:
Not here page opens when opening distance receipt from another workspace in full screen.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f2522a23-24e6-40cf-a980-58a6b2f3652e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842274975898423185</li>
        <li>Upwork Job ID: 1842274975898423185</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104346977</li>
<li>nkdengineer | Contributor | 104346978</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 19:43
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-02 19:43
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-02 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not here page opens when opening distance receipt from another workspace in full screen.

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionReceiptPage.tsx#L62) we are calculating `shouldShowNotFoundPage` based on `moneyRequestReportID` and `transaction?.reportID ` and will show `NotFoundPage` when they are different

https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionReceiptPage.tsx#L62


But in case review duplicates with expsense in another workspace, it is no longer true because this transaction does not belong to the same report so `moneyRequestReportID` will calculate wrong

https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionReceiptPage.tsx#L58

### What changes do you think we should make in order to solve the problem?



1. We should add new route param like `isFromReviewDuplicates`  for route `TRANSACTION_RECEIPT` [here](https://github.com/Expensify/App/blob/312fdecca38d88add48bd6d75cb1ccb517b4eb43/src/ROUTES.ts#L1149-L1152)

```
    TRANSACTION_RECEIPT: {
        route: 'r/:reportID/transaction/:transactionID/receipt',
        getRoute: (reportID: string, transactionID: string, readonly = false, isFromReviewDuplicates = false) => `r/${reportID}/transaction/${transactionID}/receipt${readonly ? '?readonly=true' : ''}${isFromReviewDuplicates ? '?isFromReviewDuplicates=true' : ''}` as const,
    },
```

2. Use this param when calculating `shouldShowNotFoundPage` [here](https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionReceiptPage.tsx#L62)


```
    const shouldShowNotFoundPage = isTrackExpenseReport || transaction?.reportID === CONST.REPORT.SPLIT_REPORTID || isFromReviewDuplicates ? !transaction : (moneyRequestReportID ?? '-1') !== transaction?.reportID;
```

3. We can pass `isFromReviewDuplicates` from Transaction Duplicate confirmation page [here](https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionDuplicate/Confirmation.tsx#L107-L112)

https://github.com/Expensify/App/blob/c3b4a65c88c316244ca27c19ac83a12ebde1bfd7/src/pages/TransactionDuplicate/Confirmation.tsx#L107-L112

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-10-04 18:30
I can reproduce this, but not sure if dupe detection across multiple workspaces is supposed to be a thing.

**Comment by joekaufmanexpensify** [comment] 2024-10-04 18:31
[Discussing](https://expensify.slack.com/archives/C036QM0SLJK/p1728066657120449)

**Comment by joekaufmanexpensify** [comment] 2024-10-04 18:45
Confirmed this is possible, but only for the submitter. Given the submitter can view the expense when resolving dupes, feels correct they should be able to view the receipt.

**Comment by rojiphil** [comment] 2024-10-09 11:30
@nkdengineer [proposal](https://github.com/Expensify/App/issues/50107#issuecomment-2389662939) LGTM i.e. using a new route param `isFromReviewDuplicates` to prevent `shouldShowNotFoundPage` from becoming true will help resolve this issue.
🎀👀🎀 C+ reviewed

**Comment by pecanoro** [comment] 2024-10-09 21:45
Assigning @nkdengineer to the issue!

**Comment by joekaufmanexpensify** [comment] 2024-10-21 13:44
@nkdengineer @rojiphil was the regression notice above legit?

**Comment by rojiphil** [comment] 2024-10-21 13:52
> was the regression notice above legit?

Yes @joekaufmanexpensify. That is correct.

**Comment by joekaufmanexpensify** [comment] 2024-10-22 13:38
Got it. TY for confirming!

**Comment by joekaufmanexpensify** [comment] 2024-10-22 13:38
@rojiphil can you also handle the BZ checklist so we can process payment in a few days?

**Comment by rojiphil** [comment] 2024-10-24 20:36
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/42571)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/42571/files#r1815665484)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : Yes. We can
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Steps:
1. Create two workspaces.
2. Submit a distance expense in the first workspace chat.
3. Submit the same distance expense in the second workspace chat.
4. Submit another expense to the second workspace chat (as we cannot review duplicates when there is only one expense).
5. Go to transaction thread of the second expense in Step 4.
6. Click Review duplicates.
7. Click on the second distance expense preview (to make Keep this one button appear).
9. Click on the receipt on the confirmation page.
10. Verify that: The receipt opens without issue.

**Comment by rojiphil** [comment] 2024-10-24 20:37
> can you also handle the BZ checklist so we can process payment in a few days?

@joekaufmanexpensify BZ Checklist is done.

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:33
Regression test issue is [here](https://github.com/Expensify/Expensify/issues/439017).

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:34
We need to pay: 

- @nkdengineer $125 for PR via Upwork (50% penalty for regression) 
- @rojiphil $125 for C+ via Upwork (50% penalty for regression)

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:35
@nkdengineer $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:36
@rojiphil $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:36
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-10-25 15:36
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-10-25 15:36 UTC
Labels: External, Weekly, Awaiting Payment, Bug
