### ISSUE TITLE
[$1000] mWeb/Safari - The modal remains open for a few seconds before closing after returning from a chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25598] opened 2023-08-21 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to ND.
2. Go to any chat.
3. Click on "Actions."
4. Use the device's physical back button to navigate back

## Expected Result:
The modal should close before exiting the chat.

## Actual Result:
It remains open even after going back to the LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3bec2d06-213c-4da2-90b8-a1382d6a3bb0

https://github.com/Expensify/App/assets/115492554/75640898-31b8-49ed-bace-481e1c81376a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691678959149429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a166524d05bfa35</li>
        <li>Upwork Job ID: 1694001762412531712</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-21 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Menu modal remains open for a few seconds after navigating back from a chat report using the back button.

### What is the root cause of that problem?
The modal menu visibility state value remains true at the point where navigation away from the report starts. The menu eventually gets unmounted only after the LHN is displayed.

### What changes do you think we should make in order to solve the problem?
We can use the HTML5 `popstate` event to check if the browser is about to navigate away from the report. If this is the case, then we set the menu visibility flag to false before navigation completes.

```
useEffect(() => {
    const isMobileWeb = Browser.isMobileChrome() || Browser.isMobileSafari();
    const popAction = () => {
        setMenuVisibility(false);
    }
    if (isMobileWeb) {
        addEventListener('popstate', popAction);
    }
    return () => {
        if (isMobileWeb) {
            removeEventListener('popstate', popAction);
        }
    }
}, []);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by NicMendonca** [comment] 2023-08-22 15:00
reproducible 👍 

https://github.com/Expensify/App/assets/24947345/c0b3dff0-a7f0-4201-bbde-037d7c400211

**Comment by NicMendonca** [comment] 2023-08-24 17:19
@abdulrahuman5196 bump please!

**Comment by mkarkachov** [comment] 2023-08-26 05:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Menu modal remains open for a few seconds after navigating back from a chat report using the back button. Also I found that emojipicker stays opened forever after navigating back.

### What is the root cause of that problem?
Modals should be hidden before navigating back. 

### What changes do you think we should make in order to solve the problem?
Except described bug I found that emojipicker stays opened forever after navigating back and user has to close it manually. Also in IOU report "Delete request" modal remains opened for a few seconds after navigating back from a chat report using the back button.

For composer related modals I propose to add navigation listener for `beforeRemove` event something like this:

```javascript
useEffect(() => {
        const hideModalsBeforeGoBack = navigation.addListener('beforeRemove', (e) => {
            if (!isMenuVisible && !EmojiPickerAction.emojiPickerRef.current.isEmojiPickerVisible) {
                return;
            }
            e.preventDefault();
            if (EmojiPickerAction.emojiPickerRef.current.isEmojiPickerVisible) EmojiPickerAction.hideEmojiPicker();
            if (isMenuVisible) setMenuVisibility(false);
            window.history.forward();
        });
        return () => {
            hideModalsBeforeGoBack();
        };
    }, [isMenuVisible, navigation]);
``` 

I think we should prevent go to previous screen at once, 1st - close modal, 2nd click - go back. It works the same way in native apps so we should keep consistency. Also I used `window.history.forward();` to prevent changing address url. I tested this code, works fine. I will think on optimization if my proposal will be selected.

For IOU report "Delete request" modal, I can apply the same logic for `isPopupMenuVisible` variable in ThreeDotsMenu component.

### What alternative solutions did you explore? (Optional)

We can avoid preventing go to previous screen and don't keep consistency between web version and native apps.

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:12
Apologies for the delay. Will check and get back soon.

**Comment by NicMendonca** [comment] 2023-08-30 13:04
@abdulrahuman5196 bump on reviewing these proposals ^^

**Comment by abdulrahuman5196** [comment] 2023-09-04 16:03
Sorry for the delay. Will check in my morning.

**Comment by NicMendonca** [comment] 2023-09-13 21:39
bumped you @abdulrahuman5196[ in slack!](https://expensify.slack.com/archives/C02NK2DQWUX/p1694641138528319)

**Comment by abdulrahuman5196** [comment] 2023-09-14 19:21
So the suggestion from @akinwale and @mkarkachov is to close the modal from composer. The root cause mentioned is that the modal is not hidden before navigation back.

I have to confirm on the fix, but before that if the analysis is true. I would expect a fix at Modal component itself instead of each component using modal doing the fixes.

**Comment by akinwale** [comment] 2023-09-18 09:48
## Proposal
[Updated](https://github.com/Expensify/App/issues/25598#issuecomment-1686942138)

@abdulrahuman5196 I have updated my proposal based on your observations. Please let me know what you think whey you get a chance to have a look.

**Comment by NicMendonca** [comment] 2023-09-20 12:46
@abdulrahuman5196 ^ update to the proposal!

**Comment by NicMendonca** [comment] 2023-09-26 13:46
@aimane-chnaif do you have bandwidth to pick up this one? 🙏

**Comment by abdulrahuman5196** [comment] 2023-09-28 15:13
Sure @aimane-chnaif

**Comment by abdulrahuman5196** [comment] 2023-10-03 16:53
@NicMendonca The issue is not reproducible now. We can close this issue.

**Closed** 2023-10-03 18:42 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
