### ISSUE TITLE
[$250] Sign up - "Welcome to Expensify" modal not appears on a new account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40432] opened 2024-04-18 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2616817
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Create new account
2. Copy the Magic link from email and change it to staging
3. Open a new tab and navigate to the staging magic link
4. Navigate to the original tab

## Expected Result:
The user is logged in with the new account, therefore the engagement modal "Welcome to Expensify" should be displayed - [SEE THIS COMMENT FOR MODAL](https://github.com/Expensify/App/issues/40432#issuecomment-2079239631)

![image](https://github.com/Expensify/App/assets/30815269/1bc9d3a0-d132-4d63-92fa-0a3b2b8caff5)

## Actual Result:
The user is logged in with the new account but the engagement modal "Welcome to Expensify" is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/121f040a-9767-44e8-a3bb-3ae7ff4c9038

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e55bf0be53bd1320</li>
        <li>Upwork Job ID: 1785452321885933568</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-18 12:46
We think this issue might be related to the #vip-vsb.

**Comment by bernhardoj** [comment] 2024-04-18 13:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The welcome to expensify modal doesn't show.

### What is the root cause of that problem?
There are a couple of root causes of this issue. 

The modal doesn't show because the `isFirstTimeNewExpensifyUser` is undefined.
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/actions/Welcome.ts#L61-L63

First, `isOnboardingFlowStatusKnownPromise` promise is never reset. So, if it's resolved once, logging out and logging in as a new user will pass the promise immediately.

Second, `isAbleToDetermineOnboardingStatus` doesn't wait for `isFirstTimeNewExpensifyUser` data to be ready.
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/actions/Welcome.ts#L43-L44

Last, `isFirstTimeNewExpensifyUser` is returned as `false` even for a new user.

### What changes do you think we should make in order to solve the problem?

1. Reset `isOnboardingFlowStatusKnownPromise` promise and other data when signing out. We did this before but the code was removed.
```
function resetRequiredDataCheck() {
    isOnboardingFlowStatusKnownPromise = new Promise<void>((resolve) => {
        resolveOnboardingFlowStatus = resolve;
    });
    hasProvidedPersonalDetails = undefined;
    isFirstTimeNewExpensifyUser = undefined;
}
```
Call it in `Session.cleanupSession`

2. Add `isFirstTimeNewExpensifyUser` to `hasRequiredOnyxKeysBeenLoaded` array
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/actions/Welcome.ts#L44

3. Call `isAbleToDetermineOnboardingStatus({onAble: resolveOnboardingFlowStatus});` in `isFirstTimeNewExpensifyUser` onyx callback.

https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/actions/Welcome.ts#L119-L130

4. Fix in the BE to return correct `isFirstTimeNewExpensifyUser` value.

But since the comment here mentioning that `isFirstTimeNewExpensifyUser` is going to be removed, maybe we can skip 2-4.
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/actions/Welcome.ts#L60-L63

**Comment by jliexpensify** [comment] 2024-04-18 23:58
@izarutskaya to me, this doesn't seem like a bug - a Magic link is designed to allow you to sign in. @bernhardoj curious to get your thoughts, as you've given a proposal already.

**Comment by bernhardoj** [comment] 2024-04-19 07:59
@jliexpensify the welcome modal doesn't show too if the user sign up normally with magic code input.

**Comment by jliexpensify** [comment] 2024-04-19 08:53
Yep, that's what i thought - so this isn't a bug right? It's working as intended.

**Comment by bernhardoj** [comment] 2024-04-19 09:13
Hmm, I think welcome modal should be shown for new user, right?

**Comment by jliexpensify** [comment] 2024-04-19 10:05
I'm not sure if anything has changed, but let me clarify what I think the intended behaviour should be, based off the repro steps:

1. Create new account = see Welcome Modal
2. Copy the Magic Link from email = Welcome Modal should still be active, as Magic Link is not used
3. Change the URL to staging = Welcome Modal should still be active, as Magic Link is not used
4. Open a new tab and navigate to the staging Magic Link = at this point, since we've clicked on the staging Magic Link, this "validates" or "activates" the new account.
5. Navigate to the original tab = user should now be logged in, and no Welcome Modal is shown as the Magic Link has already been clicked on and their account is "activated"

So are you saying that the Modal should still be shown at step 4? What I think is the Magic Link has now been used at that step, so the Welcome Modal should be bypassed.

**Comment by bernhardoj** [comment] 2024-04-19 15:16
Hmm, maybe we are talking about a different welcome modal. The modal I'm thinking is this one,
<img width="864" alt="image" src="https://github.com/Expensify/App/assets/50919443/385e28ea-fa1c-4d0e-8489-4be267fbbf14">

I see that we are going to replace it with onboarding modal, but the root cause of the issue will still persist and potentially trigger a false alarm that the user already completes the onboarding flow even though they are not yet, but I don't know yet what would happen with that.

**Comment by jliexpensify** [comment] 2024-04-21 23:24
You're right, it's actually not very clear which `Welcome Modal` @izarutskaya is talking about. My assumption is this one, as it's the only one in the video:

![image](https://github.com/Expensify/App/assets/30815269/2a72f54b-f070-4bc7-8269-ad3f2d32f7f8)

@izarutskaya can you confirm which Welcome Modal? If it's the [Onboarding Modal](https://github.com/Expensify/App/issues/40432#issuecomment-2066788895), then we need to change this GH body and re-test, and then we can move forward.

**Comment by jliexpensify** [comment] 2024-04-23 04:44
Bump @izarutskaya

**Comment by jliexpensify** [comment] 2024-04-26 06:05
Bump @izarutskaya to address this [comment](https://github.com/Expensify/App/issues/40432#issuecomment-2068261127) - I have posted in Slack [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714111483118659).

**Comment by jliexpensify** [comment] 2024-04-29 03:24
Got it - so you're actually referring to something completely different to @bernhardoj and myself.

I'm going to loop in @Expensify/design to review this one - maybe @dubielzyk-expensify can confirm if [this](https://github.com/Expensify/App/issues/40432#issuecomment-2066788895) and [this](https://github.com/Expensify/App/issues/40432#issuecomment-2079239631) are meant to pop up with the described flow.

**Comment by dubielzyk-expensify** [comment] 2024-04-29 04:31
Interesting. I believe we're killing [this modal](https://github.com/Expensify/App/issues/40432#issuecomment-2066788895) in favor of Stage 2 Onboarding.

We will wanna make sure they see the new onboarding flow and [this new welcome modal](https://github.com/Expensify/App/issues/40432#issuecomment-2079239631).

So if I understand this bug correctly, we'll still wanna make sure they see the latest modal with the video.

cc @MitchExpensify and @Expensify/design in case they disagree

**Comment by jliexpensify** [comment] 2024-04-29 04:34
Awesome, I thought so - thanks Jon. Once we get confirmation, happy to update the GH body with the screenshot/info and get this posted Externally.

**Comment by MitchExpensify** [comment] 2024-04-30 11:03
> We will wanna make sure they see the new onboarding flow and https://github.com/Expensify/App/issues/40432#issuecomment-2079239631.

Agree this is our goal

**Comment by jliexpensify** [comment] 2024-04-30 23:34
Updated GH, assigned to `External`. @bernhardoj did you need to make adjustments to your proposal?

**Comment by bernhardoj** [comment] 2024-05-02 07:00
The root cause is already fixed in the new [onboarding modal PR](https://github.com/Expensify/App/pull/39687). I can see the onboarding modal after signing up.

**Comment by jliexpensify** [comment] 2024-05-02 07:02
Nice, thank you! I'll close this now.

**Closed** 2024-05-02 07:02 UTC
Labels: External, Daily, Help Wanted, Bug
