### ISSUE TITLE
[HOLD #22699] Chat - Mention options are not updated dynamically for display name like we update reports

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21816] opened 2023-06-28 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open the app with another device and login with user B
3. In user A, open user B report and type in user B mention
4. From user B device, change the display name
5. Observe that app updates display name in report but does not update display name in mention options

## Expected Result:
App should dynamically update display name in mention options as we do on reports page

## Actual Result:
App does not dynamically update display name in mention options as we do on reports page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/34dba06c-d54a-4043-8059-7c9e668da57d

https://github.com/Expensify/App/assets/93399543/b8118a86-2db0-489a-96e9-c6f0b42d35bb

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687871873180969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-28 21:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We don't re-calculate mentions when `personalDetails` change in `ReportActionCompose`.

This is the root cause

### What changes do you think we should make in order to solve the problem?

In `componentDidUpdate`, add the following code
```
        if (prevProps.personalDetails !== this.props.personalDetails) {
            this.calculateMentionSuggestion();
        }
```

This works as expected.

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2023-06-29 14:17
@kbecciv These seems very similar to https://github.com/Expensify/App/issues/21622. Do you feel like these can be merged together?

**Comment by CortneyOfstad** [comment] 2023-06-30 17:09
Bump @kbecciv ^^

**Comment by CortneyOfstad** [comment] 2023-06-30 19:48
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by CortneyOfstad** [comment] 2023-07-11 20:32
Not sure why this didn't get re-assigned when I reapplied the bug label 😑

**Comment by CortneyOfstad** [comment] 2023-07-11 20:32
@kbecciv These seems very similar to https://github.com/Expensify/App/issues/21622. Do you feel like these can be merged together?

**Comment by mallenexpensify** [comment] 2023-07-11 21:36
Putting on hold pending 
- https://github.com/Expensify/App/issues/22699

Feel free to remove yourself @CortneyOfstad , since it might be a while til it's addressed.

**Comment by mallenexpensify** [comment] 2023-07-18 18:21
On hold, bumped to Weekly

**Closed** 2023-10-23 12:32 UTC
Labels: Monthly
