### ISSUE TITLE
[HOLD for payment 2024-10-10] [$125] Search - App returns to Inbox after assigning task in chat report RHP in Search

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49478] opened 2024-09-19 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Send a message to any user.
3. Go to Search > Chat.
4. Click on the message sent in Step 2.
5. Assign a task in the chat.

## Expected Result:
After assigning task in chat report RHP, app will stay on the same page (same as when submitting expense).

## Actual Result:
After assigning task in chat report RHP, app opens chat in Inbox.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a0708a2f-6bbd-4bfd-a432-2693aa2426ff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838987818573589002</li>
        <li>Upwork Job ID: 1838987818573589002</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104142128</li>
<li>FitseTLT | Contributor | 104142130</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by FitseTLT** [comment] 2024-09-19 16:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - App returns to Inbox after assigning task in chat report RHP in Search

### What is the root cause of that problem?
Because we are dismissig modal here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/actions/Task.ts#L297
### What changes do you think we should make in order to solve the problem?

We need to add a param for createTaskAndNavigate shouldDismissModal or not pass false in this case here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/pages/home/report/ReportFooter.tsx#L157
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 16:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - App returns to Inbox after assigning task in chat report RHP in Search

### What is the root cause of that problem?
Because we are dismissig modal here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/actions/Task.ts#L297
### What changes do you think we should make in order to solve the problem?

We only need to dismissModal when we create from NewTaskPage but no in ReportFooter case 
We need to add a param for createTaskAndNavigate shouldDismissModal and set the default to true and pass false in this case here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/pages/home/report/ReportFooter.tsx#L157
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 16:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - App returns to Inbox after assigning task in chat report RHP in Search

### What is the root cause of that problem?
Because we are dismissig modal here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/libs/actions/Task.ts#L297
### What changes do you think we should make in order to solve the problem?

We only need to dismissModal when we create from NewTaskPage but no in ReportFooter case 
We need to add a param for createTaskAndNavigate shouldDismissModal and set the default to true and pass false in this case here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/pages/home/report/ReportFooter.tsx#L157
Then inside createTaskAndNavigate we should only dismiss if shouldDismissModal is true
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-19 16:16
[Updated](https://github.com/Expensify/App/issues/49478#issuecomment-2361433246) to only add elaborate explanation in the RCA.

**Comment by adelekennedy** [comment] 2024-09-25 16:57
whoops this got assigned to me right before my ooo - testing now

**Comment by adelekennedy** [comment] 2024-09-25 17:03
can reproduce - I'd call this a polish for our tasks

**Comment by DylanDylann** [comment] 2024-09-26 14:00
@nyomanjyotisa  ⚠️ ⚠️ ⚠️  You don't follow following rules when updating your proposal. Your updated proposal is different from your original proposal and It takes idea from another contributor. You also don't leave any additional comments to alert everyone that it has been updated:

https://github.com/Expensify/App/blob/da37289fe24c8d92cdf63da9de7320b7c3f08bca/contributingGuides/CONTRIBUTING.md?plain=1#L143

https://github.com/Expensify/App/blob/da37289fe24c8d92cdf63da9de7320b7c3f08bca/contributingGuides/CONTRIBUTING.md?plain=1#L144-L147

----------------------

@abzokhattab I will not consider your alternative proposal because that idea has been proposed by another contributor previously. Please note this rule

https://github.com/Expensify/App/blob/da37289fe24c8d92cdf63da9de7320b7c3f08bca/contributingGuides/CONTRIBUTING.md?plain=1#L143

### The *difference* should be important, meaningful or considerable.

---------------

Let's go with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/49478#issuecomment-2361433246)

🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-09-27 03:45
@FitseTLT Could you give an ETA on PR?

**Comment by FitseTLT** [comment] 2024-09-27 20:04
PR ready

**Comment by FitseTLT** [comment] 2024-10-11 17:52
@adelekennedy Payment is due here.

**Comment by adelekennedy** [comment] 2024-10-14 02:34
whoops! Late here

Payouts due:

- [ ] Contributor: $250 @DylanDylann Upwork
- [ ] Reviewer: $250 @FitseTLT Upwork

Upwork job is [here](https://www.upwork.com/nx/wm/offer/104142128).

**Closed by adelekennedy** 2024-10-14 02:34 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
