### ISSUE TITLE
[$250] Expense- New flag persists on system message after reading and navigating away

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50019] opened 2024-10-01 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** testpayment935+223@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com./
2. Log in with a new account that has no previously submitted expenses (Important).
3. Click on the FAB
4. Select Submit expense.
5. Click on the Scan tab.
6. Follow the scan expense creation flow and submit the expense.
7. Once the scan is complete, edit the Description.
8. Click the header link to return to the conversation.
9. Navigate back to the expense detail page and check for a new message notification.
10. Go to another 1:1 conversation, then return to the above expense

## Expected Result:
After navigating to new message conversation once, the new message should not exist anymore

## Actual Result:
After navigating to new message conversation once, the new message still exist.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/802f15d7-0efc-4c60-8267-bbecad9793b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841629411653798211</li>
        <li>Upwork Job ID: 1841629411653798211</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 104363182</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by IuliiaHerets** [comment] 2024-10-01 19:35
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-10-02 23:57
There's a lot of words and a lot of cursor waving here, but I'm not understanding the problem as it's laid out here.

I think what the Op is trying to say is:

Expected Result:
After returning to the expense, the most recent message should no longer appear flagged as a "new" message

Actual Result:
After returning to the expense, the most recent message is still flagged as "new" / unread.

**Comment by RachCHopkins** [comment] 2024-10-02 23:59
I can replicate this:

![image](https://github.com/user-attachments/assets/9a82d646-880b-4a2e-834c-a1b52d1354e0)

Only adding a comment in the chat thread removes the New indicator. Eyeballing it, doesn't "read" it per se.

**Comment by VickyStash** [comment] 2024-10-04 09:31
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-10-04 10:58
@RachCHopkins @ZhenjaHorbach 
I have investigated the flow and was able to reproduce the issue. But before preparing a formal proposal I want to confirm several questions:
1) Should the user see the `New` flag at all if he updated the description on his own while being on this screen:
![image](https://github.com/user-attachments/assets/5b2fb43b-242c-443d-a907-bdd62e204cec)

2) Should the `New` flag disappear right away when the user sends a comment in the chat or only when user re-enter the page then? Right now, it doesn't disappear till the user re-enters the page.

Right now:

https://github.com/user-attachments/assets/6ffb13bf-521f-42a2-8dac-4e31dd1489b5

Possible update:

https://github.com/user-attachments/assets/3b5577f2-48d6-42dc-94a3-bd22915f3d0c

**Comment by RachCHopkins** [comment] 2024-10-07 05:10
I'm not sure @VickyStash - I'll ask internally!

**Comment by mountiny** [comment] 2024-10-07 07:32
I think in normal chat what happens is that the new indicator shows up for a sec but we scroll you down which makes it disappear.

In this case though i agree we do not want you to be scrolled down as you might want to edit more properties of the expense. So the new indicator could be hidden but i am not sure how possible it is

**Comment by VickyStash** [comment] 2024-10-07 14:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The **New** indicator is shown to the user if he updated the expense **description** himself while being on the expense screen and then re-entered/reloaded the expense page.
The same behavior can also be reproduced with amount/merchant/date/category fields updates.

https://github.com/user-attachments/assets/86c2ed4f-7d35-4153-a4c0-3315c6310cc7

### What is the root cause of that problem?
The app and the API update the report `lastReadTime` during the `AddComment` API call:
![image](https://github.com/user-attachments/assets/0023842b-7799-4077-a7b3-5c462216e436)

**BUT:**
1. The app doesn't update expense report `lastReadTime` optimistically during `UpdateMoneyRequestDescription` call.
2. The API doesn't  return updated expense report `lastReadTime`during `UpdateMoneyRequestDescription` API call. It returns only child report updated `lastReadTime`, but we also need to update the expense report `lastReadTime`.

![image](https://github.com/user-attachments/assets/2cd26ea9-0521-44ad-96ad-1e6cc4d32fef)


Same for `UpdateMoneyRequestAmountAndCurrency`, `UpdateMoneyRequestMerchant`, `UpdateMoneyRequestDate` and  `UpdateMoneyRequestCategory` requests.

In the app the `report.lastReadTime` is used as [unreadMarkerTime](https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/pages/home/report/ReportActionsList.tsx#L211). Which then used in a [check if a message is unread](https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/pages/home/report/ReportActionsList.tsx#L222).

Since the expense `report.lastReadTime` wasn't updated during `UpdateMoneyRequestDescription` call, the message about the updated description is considered to be sent later than `lastReadTime` time which makes the **New** indicator to be shown.

### What changes do you think we should make in order to solve the problem?
1. FE change: Update [getUpdateMoneyRequestParams](https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/libs/actions/IOU.ts#L2471) function to [optimistically update](https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/libs/actions/IOU.ts#L2621-L2623) the report `lastReadTime`, [same way](https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/libs/actions/Report.ts#L488) as it's done for the usual comment.
2. BE change: Update `UpdateMoneyRequestDescription`API call to update the `lastReadTime` of the expense report.
Same for `UpdateMoneyRequestAmountAndCurrency`, `UpdateMoneyRequestMerchant`, `UpdateMoneyRequestDate`,  `UpdateMoneyRequestCategory` requests.

**Comment by VickyStash** [comment] 2024-10-08 07:53
@RachCHopkins @mountiny will someone be able to handle the BE side change mentioned in my proposal?

**Comment by mountiny** [comment] 2024-10-08 12:36
@rafecolton should be able to help as assigned internal engineer.

**Comment by rafecolton** [comment] 2024-10-09 05:22
Thanks for the ping. I was OOO yesterday and half of today. Making myself the issue owner so I see this tomorrow, can action it then.

**Comment by rafecolton** [comment] 2024-10-10 22:12
Proposal looks good, thanks @VickyStash! LMK when you have a PR up for the FE updates and testing instructions, and I can work on the corresponding BE updates.

**Comment by rafecolton** [comment] 2024-10-10 22:13
Looks like maybe the upwork automation failed? Trying again

**Comment by rafecolton** [comment] 2024-10-10 22:15
@RachCHopkins not sure what's up with the upwork automation - are you able to send @VickyStash the upwork offer manually?

**Comment by RachCHopkins** [comment] 2024-10-11 00:52
I think because @VickyStash is with CallStack, they don't need an Upwork offer. Please correct me if I'm wrong, Vicky!

**Comment by rafecolton** [comment] 2024-10-11 02:38
Oh nice! Didn't realize that, my bad 👌

**Comment by VickyStash** [comment] 2024-10-11 14:18
@rafecolton I've prepared the [Draft PR](https://github.com/Expensify/App/pull/50635) with a fix, but right now it fixes the issue offline only. To fix it online API updates are needed, cause right now optimistically set `lastReadTime` is overwritten by the outdated API value. Maybe it makes sense to open FE PR to the review when API updates are ready.

**Comment by rafecolton** [comment] 2024-10-11 14:33
> Maybe it makes sense to open FE PR to the review when API updates are ready.

Yes this makes sense, thanks. I see you included detailed testing steps, so I can use those in dev and let you know here when the BE changes are on staging so you can test. 

I'm going to adjust the priority of this issue to `Weekly` because I have some higher priority issues, and I don't think this issue is detrimental to the user. LMK if you disagree.

**Comment by VickyStash** [comment] 2024-10-11 14:48
@rafecolton Thank you!

**Comment by RachCHopkins** [comment] 2024-10-16 04:17
How's it coming along @rafecolton?

**Comment by rafecolton** [comment] 2024-10-22 00:46
No progress, sorry, I have been focused on some higher priority items. Feel free to ask for another volunteer in case anyone has bandwidth, otherwise I will prioritize it as soon as I can 🙏

**Comment by rafecolton** [comment] 2024-10-29 19:04
Same update as before

**Comment by VickyStash** [comment] 2024-11-25 08:16
@RachCHopkins @rafecolton kind bump here 🙂

**Comment by RachCHopkins** [comment] 2024-11-27 20:30
Sorry @VickyStash as far as I'm aware, that's what the Hot Pick label does. I'll also add a note to the most recent weekly update.

**Comment by rafecolton** [comment] 2024-12-03 01:40
It think it would be best if I removed my assignment at this time. I don't see myself being able to prioritize this any time soon.

**Comment by RachCHopkins** [comment] 2024-12-13 03:31
Only `Critical` issues are currently being called out for hot picks. No update here.

**Comment by VickyStash** [comment] 2024-12-17 16:04
The issue isn't reproduced for me anymore:

https://github.com/user-attachments/assets/ec34e147-cfe8-4676-9101-7aedf436b873

**Comment by RachCHopkins** [comment] 2024-12-18 05:02
Cool. Let's close this.

**Closed by RachCHopkins** 2024-12-18 05:02 UTC
Labels: Weekly, Internal, Bug, Hot Pick
