### ISSUE TITLE
[$500] Room - Selection list RHP does not show sliding animation while being dismissed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38665] opened 2024-03-20 11:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Start room.
3. Go to Room.
4. Click Workspace (or Who can post or Visibility).
5. Click outside the RHP.

## Expected Result:
The RHP will show sliding animation while being dismissed.

## Actual Result:
The RHP does not show sliding animation while being dismissed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7362f8aa-0619-421a-814b-a27645f8515b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a45c6aecba3aa427</li>
        <li>Upwork Job ID: 1770474516290019328</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-20 11:42
@rlinoz I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think this issue might be related to the #vip-vsb.

**Comment by rlinoz** [comment] 2024-03-20 12:04
He did, but the videos in the Authors checklist there is an animation, and in the reviewers checklist there is not, so something happened along the way.

@Krishna2323 @hoangzinh

**Comment by rlinoz** [comment] 2024-03-20 12:04
Not a deploy blocker though, so removing the label

**Comment by godofoutcasts94** [comment] 2024-03-20 12:05
I don't see this issue happening in my case on the latest main

**Comment by rlinoz** [comment] 2024-03-20 12:15
@godofoutcasts94 you have to click outside the RHP.

**Comment by godofoutcasts94** [comment] 2024-03-20 12:19
Yes i did

**Comment by Pranav2612000** [comment] 2024-03-20 12:45
@Krishna2323 This was added by you around 2 weeks back ( https://github.com/Expensify/App/commit/904316b9036ad3c7b87ae371d59354094af4a39a )
Was there a reason you used `Navigation.dismissModal` ) ?

**Comment by shahinyan11** [comment] 2024-03-20 13:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Selection list RHP does not show sliding animation while being dismissed
### What is the root cause of that problem?
The `ValueSelectorModal` opens separately in a RHP screen . And when we call [Navigation.dismissModal](https://github.com/Expensify/App/blob/0fa4d0f2a200d58af452fa6c37bdc27b7f7fe2d5/src/components/ValuePicker/index.tsx#L59C34-L59C57) in on backdrop press we the prev screen is closing with animation which will not affect to `ValueSelectorModal`
### What changes do you think we should make in order to solve the problem?
when the user clicks on the background Call hidePickerModal too. To do that we can update [this](https://github.com/Expensify/App/blob/0fa4d0f2a200d58af452fa6c37bdc27b7f7fe2d5/src/components/ValuePicker/index.tsx#L59C17-L59C58) line like below
```
onBackdropPress={()=>{
    Navigation.dismissModal()
    hidePickerModal()
}}
```

### What alternative solutions did you explore? (Optional)
Use below styles instead `margingLeft` [here](https://github.com/Expensify/App/blob/0fa4d0f2a200d58af452fa6c37bdc27b7f7fe2d5/src/styles/utils/generators/ModalStyleUtils.ts#L217C25-L217C99)
```
position: 'absolute',
right: 0,
height: '100%',
```

**Comment by CortneyOfstad** [comment] 2024-03-20 14:58
Pinged on the original PR [here](https://github.com/Expensify/App/pull/38015#issuecomment-2009776066)

**Comment by danieldoglas** [comment] 2024-03-20 15:00
This should probably be fixed by the original PR creator, since it's in the regression period. @Krishna2323

**Comment by CortneyOfstad** [comment] 2024-03-20 15:36
Confirmed with @danieldoglas and I agree that because this is within the regression period, we're assigning both @Krishna2323 (contributor) and @hoangzinh (C+) to this issue as well to get this corrected 👍

**Comment by shahinyan11** [comment] 2024-03-20 15:38
> This should probably be fixed by the original PR creator, since it's in the regression period. @Krishna2323

I am sorry but i want to ask where is it written that the regression should be fixed by the original PR creator ?

**Comment by shahinyan11** [comment] 2024-03-20 15:41
> This should probably be fixed by the original PR creator, since it's in the regression period. @Krishna2323

@hoangzinh @CortneyOfstad @Pranav2612000 @danieldoglas  I am sorry but I want to ask where is it written that the regression should be fixed by the original PR creator ? I encountered case when there was chosen the proposal of other contributor

**Comment by CortneyOfstad** [comment] 2024-04-03 15:41
@Krishna2323 indicated on the PR [here](https://github.com/Expensify/App/pull/38711#issuecomment-2034150819) they will review the feedback 👍

**Comment by CortneyOfstad** [comment] 2024-04-17 14:20
PR still in review 👍

**Comment by rlinoz** [comment] 2024-04-30 20:37
Reopening for proposals since we got to a dead end [here](https://github.com/Expensify/App/pull/38711#issuecomment-2078535974).

**Comment by CortneyOfstad** [comment] 2024-05-01 15:40
Thanks @rlinoz!

**Comment by rlinoz** [comment] 2024-05-03 19:59
waiting for proposals

**Comment by rlinoz** [comment] 2024-05-06 11:57
waiting for proposals

**Comment by shahinyan11** [comment] 2024-05-06 15:11
@rlinoz What about my proposal ?

**Comment by rlinoz** [comment] 2024-05-06 17:23
@shahinyan11 which one specifically?

**Comment by shahinyan11** [comment] 2024-05-06 18:21
@rlinoz [this](https://github.com/Expensify/App/issues/38665#issuecomment-2009519726) one

**Comment by rlinoz** [comment] 2024-05-06 18:23
The proposal only works if we delay the dismiss: https://github.com/Expensify/App/pull/38711#issuecomment-2075349697

And making it a separate screen was considered poor ROI before: https://github.com/Expensify/App/pull/38711#issuecomment-2078535974

**Comment by rlinoz** [comment] 2024-05-08 19:18
I am inclined to close this for now, since we don't want to create the new screens yet.

**Comment by CortneyOfstad** [comment] 2024-05-08 19:19
Sounds good to me @rlinoz! Closing!

**Closed by CortneyOfstad** 2024-05-08 19:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
