### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] Chat - The "Delete receipt" option appears on the receiver's side, but it fails to delete the receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29557] opened 2023-10-13 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83.10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697176987960199

## Action Performed:
1. Log in with User A.
2. Open a chat with User B.
3. Go to the Request money section.
4. Enter an amount and click "Next"
5. Click on the three-dot menu and select "Add receipt"
6. Add a file and send it.
7. Go to User B’s account.
8. Open User A's chat.
9. Navigate to the detail page of the sent request money.
10. Click on the receipt and click on the three-dot menu.
11. Click on "Delete receipt"
12. Notice that the "Delete receipt" option is displayed, but it does not delete the receipt

## Expected Result:
The "Delete receipt" option should not be displayed on the receiver's side, or if it appears, it should successfully delete the receipt

## Actual Result:
The "Delete receipt" option appears on the receiver's side, but it fails to delete the receipt

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/e998530b-2612-49d6-9026-f260aebbf8d1

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/a6a33330-33cb-4849-9314-7934ca007fdc

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/d09e37cd-6919-4f87-9c3c-92a61581f0f4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/e82f24c6-7a47-442c-9bc5-d5bc8cd12038

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/51569dc0-10ed-46ec-9df6-df45987cb016

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/02576cee-f089-4cb0-b7d3-ac232257363c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c649d226d2ed49a</li>
        <li>Upwork Job ID: 1712814865256730624</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27242474</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-10-13 12:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The "Delete receipt" option appears on the receiver's side, but it fails to delete the receipt

### What is the root cause of that problem?
- User that is not an owner transaction when trying to delete receipt will throw an error: "Cannot detach receipt from the unowned transaction"
### What changes do you think we should make in order to solve the problem?
- We need to hide the "Delete receipt" option in the above case like below:
- Update
https://github.com/Expensify/App/blob/873a250c097e717cfcadd624954f50f55f63be3c/src/components/AttachmentModal.js#L379
to
```
    if (TransactionUtils.hasReceipt(props.transaction) && !TransactionUtils.isReceiptBeingScanned(props.transaction) && ReportUtils.isOwnerReportAction(parentReportAction)) {
```
- ```ReportUtils.isOwnerReportAction(parentReportAction)``` is something like:
```
function isOwnerReportAction(reportAction) {
    return reportAction.actorAccountID === currentUserAccountID;
}
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by DylanDylann** [comment] 2023-10-13 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The "Delete receipt" option appears on the receiver's side, but it fails to delete the receipt

### What is the root cause of that problem?
- User that is not an owner transaction when trying to delete receipt will throw an error: "Cannot detach receipt from the unowned transaction"
### What changes do you think we should make in order to solve the problem?
- We need to hide the "Delete receipt" option in the above case like below:
- Update
https://github.com/Expensify/App/blob/873a250c097e717cfcadd624954f50f55f63be3c/src/components/AttachmentModal.js#L379
to
```
    if (TransactionUtils.hasReceipt(props.transaction) && !TransactionUtils.isReceiptBeingScanned(props.transaction) && ReportUtils.isOwnerReportAction(parentReportAction)) {
```
- ```ReportUtils.isOwnerReportAction(parentReportAction)``` is something like:
```
function isOwnerReportAction(reportAction) {
    return reportAction.actorAccountID === currentUserAccountID;
}
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by conorpendergrast** [comment] 2023-10-16 12:29
@narefyev91 one proposal above to review!

**Comment by narefyev91** [comment] 2023-10-16 12:31
Proposal from @DylanDylann looks good to me https://github.com/Expensify/App/issues/29557#issuecomment-1761478737
Already reviewed it on Friday - but was interrupted with some major pr
🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment] 2023-10-17 15:32
Yep, that proposal looks good 👍

**Comment by DylanDylann** [comment] 2023-10-18 03:57
@narefyev91 PR https://github.com/Expensify/App/pull/29791 is ready for review

**Comment by DylanDylann** [comment] 2023-10-23 18:15
The pull request did not get merged within 3 working days because the internal engineer delayed reviewing and merging (ref: https://github.com/Expensify/App/pull/29791#pullrequestreview-1691272639). @conorpendergrast  Are we eligible for a timeline bonus in this issue?

**Comment by NikkiWines** [comment] 2023-10-23 19:42
Yeah, @conorpendergrast this one should be eligible for the speed bonus as the merge was delayed by me being OOO

**Comment by conorpendergrast** [comment] 2023-10-25 11:08
Sounds good, thanks for confirming

**Comment by conorpendergrast** [comment] 2023-11-06 12:01
Payouts due:

- [ ] Issue Reporter: $50 @ayazhussain79 pending application to the job
- [x] Contributor: $500 + 50% urgency = $750 @DylanDylann - [Contract paid and ended](https://www.upwork.com/nx/wm/workroom/35172994/overview)
Contributor+: N/A - contractor @narefyev91 

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/29557#issuecomment-1775904880)

Upwork job is [here](https://www.upwork.com/jobs/~012c649d226d2ed49a).

**Comment by conorpendergrast** [comment] 2023-11-06 12:01
@ayazhussain79 please [apply for the Upwork job](https://www.upwork.com/jobs/~012c649d226d2ed49a) so that I can pay you for the reporter role @ $50

**Comment by conorpendergrast** [comment] 2023-11-06 12:02
@narefyev91 please complete [the C+ checklist](https://github.com/Expensify/App/issues/29557#issuecomment-1779639905)!

**Comment by narefyev91** [comment] 2023-11-06 12:04
- The PR that introduced the bug has been identified. Link to the PR - that was missing functionality, not coming from any regressions
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by conorpendergrast** [comment] 2023-11-07 20:33
@ayazhussain79 Hey! Third and final request to please [apply for the Upwork job](https://www.upwork.com/jobs/~012c649d226d2ed49a) so that I can pay you for the reporter role @ $50. I'll close this out tomorrow.

**Comment by ayazhussain79** [comment] 2023-11-07 20:50
@conorpendergrast applied, Sorry for the late

**Comment by conorpendergrast** [comment] 2023-11-07 21:28
@ayazhussain79 Sure! [offer sent now](https://www.upwork.com/nx/wm/offer/27565814)

**Comment by ayazhussain79** [comment] 2023-11-07 21:30
@conorpendergrast offer accepted, Thank you

**Comment by conorpendergrast** [comment] 2023-11-07 21:36
All paid and done. Thanks everyone!

**Closed by conorpendergrast** 2023-11-07 21:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
