### ISSUE TITLE
[PAY 7TH SEP][$250] Sign In - User navigated to deeplink conversation instead LHN when Signed out and back in

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47428] opened 2024-08-14 14:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4849362&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: User should be signed out. If using the web version, please resize the window to portrait format (mWeb).

1. Open app
2. Navigate to a deeplink that leads to a conversation with another user.
3. Sign in with a valid account that has the conversation from step 2
4. Sign Out
5. Sign In back (do not use the deeplink)

## Expected Result:
User should be navigated to LHN

## Actual Result:
When the user signed out and back in (step 5), the conversation from the deeplink in step 2 opened.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9202f0d0-4c79-4231-b890-54190005444e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf4c9f6cbc29f247</li>
        <li>Upwork Job ID: 1823967796772847704</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103625928</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by IuliiaHerets** [comment] 2024-08-14 14:52
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-14 14:52
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-08-15 03:24
@IuliiaHerets can you retest this one on v9.0.20-6? I haven't been able to repro.

**Comment by IuliiaHerets** [comment] 2024-08-15 05:03
Tester update steps a little for better understanding:
Precondition: User should be signed out. If using the web version, please resize the window to portrait format (mWeb).

1. Open app
2. Navigate to a deeplink that leads to a conversation with another user.
3. Sign in with a valid account that has the conversation from step 2
4. Sign Out
5. Sign In back (do not use the deeplink).

Issue still reproduce on his side on the iOS 9.0.20-6 build.

https://github.com/user-attachments/assets/4ea89544-b586-4b54-8ac9-8c5f55f59420

**Comment by jliexpensify** [comment] 2024-08-15 06:19
Ok, I can reproduce it on Android but not on web.

**Comment by kundan175** [comment] 2024-08-15 09:38
Hello @jliexpensify @bernhardoj @IuliiaHerets @DylanDylann @r8 

This problem started occurring for me 3 days ago. If the user is logged out and comes through deep linking, it directly redirects them in, but if they log out and then log back in, it redirects again. 

This issue happens because the linking was not cleared after being used. After using the linking, you need to remove the linking data. I have fixed this issue in your app.

**Comment by kundan175** [comment] 2024-08-15 09:42
Contributor details
Your Expensify account email: kundansingh957632@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012a2655b97a5d4b2f

**Comment by kundan175** [comment] 2024-08-15 09:44
Contributor details
Your Expensify account email: kundansingh957632@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012a2655b97a5d4b2f

**Comment by jliexpensify** [comment] 2024-08-15 09:45
Hi @kundan175 - can you please submit a proposal, like what the other contributor has done? All the details to write and submit a proposal can be found in our contributing.MD:

https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by kundan175** [comment] 2024-08-15 09:50
@jliexpensify To be honest, I didn't understand it either. This is the first time I've seen something like this in the Guides 😊.

**Comment by kundan175** [comment] 2024-08-15 09:54
@jliexpensify But I can fix this issue. In fact, I fixed a similar issue 2 days ago in this app: [Juggle NZ - Shop, Earn & Reward](https://apps.apple.com/app/juggle-nz-shop-earn-reward/id6477533835).

**Comment by jliexpensify** [comment] 2024-08-15 09:59
@kundan175 please review the Contributor .MD and write a proposal as to how you will fix the issue for review. Thanks!

**Comment by kundan175** [comment] 2024-08-15 10:04
@jliexpensify 
Problem Statement
We are trying to solve an issue where, if the user is logged out and then logs back in through deep linking, the app redirects them again by again.

Root Cause
The root cause of this problem is that the linking data was not cleared after it was used, causing the app to trigger the redirection multiple times.

Proposed Solution
To solve this problem, the linking data should be removed immediately after it is used to prevent unnecessary redirects.

Alternative Solutions Explored (Optional)
None needed at this time, as clearing the linking data is a straightforward and effective solution.

**Comment by r8** [comment] 2024-08-15 10:13
Why am I lately constantly getting mentioned in issues here?

**Comment by jliexpensify** [comment] 2024-08-20 23:22
Bumping @DylanDylann for testing/reviews please

**Comment by DylanDylann** [comment] 2024-08-21 04:52
I have worked on this, will try to complete reviewing today

**Comment by DylanDylann** [comment] 2024-08-21 07:40
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/47428#issuecomment-2290917427) looks good to me. We need to disconnect to Onyx when navigating successful

🎀 👀 🎀 C+ reviewed

**Comment by neil-marcellini** [comment] 2024-08-21 19:38
> @bernhardoj's [proposal](https://github.com/Expensify/App/issues/47428#issuecomment-2290917427) looks good to me. We need to disconnect to Onyx when navigating successful
> 
> 🎀 👀 🎀 C+ reviewed

I agree, sounds good.

**Comment by bernhardoj** [comment] 2024-08-22 01:39
PR is ready

cc: @DylanDylann

**Comment by DylanDylann** [comment] 2024-08-28 02:39
The PR is merged

**Comment by jliexpensify** [comment] 2024-09-02 22:25
Hmm automation broken - deployed to prod on 31st Aug, right?

**Comment by jliexpensify** [comment] 2024-09-02 22:27
Payment Summary

- C: @bernhardoj $250 (ND payment)
- C+: @DylanDylann $250 - is a checklist needed here?

[Upwork job](https://www.upwork.com/jobs/~01bf4c9f6cbc29f247)

**Comment by bernhardoj** [comment] 2024-09-03 03:11
> deployed to prod on 31st Aug, right?

Correct.

**Comment by DylanDylann** [comment] 2024-09-03 09:42
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Log out
2. Open staging.new.expensify.com/settings
3. Login
4. Verify you are navigated to the settings page
5. Log out
6. Login again
7. Verify you stay at LHN/Home


Do we agree 👍 or 👎

**Comment by jliexpensify** [comment] 2024-09-08 06:57
Paid and job closed.

**Closed by jliexpensify** 2024-09-08 06:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-09-08 10:27
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-09 21:11
$250 approved for @bernhardoj
