### ISSUE TITLE
[$1000]  mWeb - Composer is not visible for a while and space left between composer and keyboard when starting new chat  with new user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22102] opened 2023-07-03 12:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open app
2. Click to Fab button > New chat
3. From recent select a user that not messaged before
4. Notice that the half of composer not visible for a second and there is a space between composer and keyboard

## Expected Result:
 No space between composer and keyboard And composer always visible

## Actual Result:
 The half of composer not visible for a second and there is a space between composer and keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50d031f6-fbe4-4be4-90c7-ffbce3a40e9c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688248353096759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168f8a5f30b16df8b</li>
        <li>Upwork Job ID: 1676411214780399616</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-04 06:42
Repro:

https://github.com/Expensify/App/assets/59587260/6e2b66ef-9e72-45b5-8469-557bc2490de0

**Comment by narzullome** [comment] 2023-07-04 07:05
![telegram-cloud-photo-size-2-5269636525723863478-y](https://github.com/Expensify/App/assets/134583481/e0a1422a-5e97-4ba3-9aaa-d59d5da055cf)
@kadiealexander as I can see on ur video - The half of composer not visible for a second and there is a space between composer and keyboard

**Comment by kadiealexander** [comment] 2023-07-05 02:02
Ah okay, thank you for that screenshot!

**Comment by alitoshmatov** [comment] 2023-07-05 08:16
I think there were multiple issues, where shows app reacting slowly to keyboard openings and having some lag. But there is nothing we can do about it. I try to look for exact issues

**Comment by kadiealexander** [comment] 2023-07-10 05:42
@alitoshmatov any updates on the exact issues?

**Comment by alitoshmatov** [comment] 2023-07-10 06:05
@kadiealexander Sorry, I couldn't find exact issue. Maybe you can proceed with this. But the issue is caused by app working a bit slow at that exact moment when keyboard is opening and app layout is not able to keep up with it. I am assuming there is not much we can do.

**Comment by kadiealexander** [comment] 2023-07-12 01:40
@aimane-chnaif could you please weigh in and see if you think this is something we can fix?

**Comment by lukemorawski** [comment] 2023-07-18 11:18
hey it's Lucas from Callstack. I'm happy to start working on this issue.

**Comment by kadiealexander** [comment] 2023-07-19 03:35
Thanks for your help @lukemorawski!!

**Comment by iwiznia** [comment] 2023-07-19 17:21
I am confused, why was I assigned here? I don't see proposals approved...

**Comment by kadiealexander** [comment] 2023-07-20 04:23
This issue was picked up by Lucas from Callstack, I assigned you to oversee the PR. If that's not how we should approach issues picked up by our vendor agencies please let me know!

**Comment by iwiznia** [comment] 2023-07-21 20:10
Going on sabbatical, please reassign another engineer

**Comment by kadiealexander** [comment] 2023-07-25 02:51
@lukemorawski any updates on this one? :)

**Comment by lukemorawski** [comment] 2023-07-26 09:04
@kadiealexander I'm working on two urgent tickets right now. Will be back to this one tomorrow :)

**Comment by lukemorawski** [comment] 2023-07-27 14:58
can't reproduce that bug any more on main branch. Can any else confirm that?

**Comment by kadiealexander** [comment] 2023-07-31 03:26
Sorry for the delay @lukemorawski, I can't reproduce this anymore either. Closing as it's no longer reproducible, please feel free to reopen it if needed.

**Closed by kadiealexander** 2023-07-31 03:26 UTC
Labels: External, Engineering, Daily, Bug
