### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] IOU - Next button disabled when requesting a new distance IOU offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27895] opened 2023-09-20 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26836
## Action Performed:
1. Launch the app logged in
2. Go offline
3. Click FAB > request money
4. Select distance tab
5. Enter start and finish addresses

## Expected Result:
User should be able to click Next and there the fields amount and distance are filled as "TBD"

## Actual Result:
User should be able to click Next and there the fields amount and distance are filled as "TBD"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2f4fcdb0-20b7-4318-976d-f1aae5485193

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2023-09-21 03:25
I'll take care of this one since it's very early for Paul.

**Comment by paultsimura** [comment] 2023-09-21 07:31
@neil-marcellini thank you for taking care of the PR.

I still do not understand how my original PR affected the isOffline logic – you can see that my PR's [diff](https://github.com/Expensify/App/pull/26836/files) with latest main has not changed the `isOffline` logic for the button's `isDisabled`.

Also, from [this discussion](https://github.com/Expensify/App/pull/26836#issuecomment-1716401107) with you, this behavior seemed expected.

Could you please point me to the commit where I overwritten the change that allowed requesting in offline mode?
Or we just should have allowed the offline distance request in our PR and missed it?
Just so I could understand if that was my regression or just some requirements that we missed.

**Comment by neil-marcellini** [comment] 2023-10-02 17:21
## Regression Test Proposal

I think we should have a regression test since it's simple to test and easy to break.

1. Launch the app logged in
2. Go offline
3. Click FAB > request money
4. Select distance tab
5. Enter start and finish addresses
6. Verify you can click Next and there the fields amount and distance are filled as "TBD"

Do we agree 👍 or 👎

**Comment by kevinksullivan** [comment] 2023-10-03 23:01
@Ollyws sent you an offer for PR review

https://www.upwork.com/jobs/~015338a197d592b915

**Comment by neil-marcellini** [comment] 2023-10-06 18:08
@Ollyws you reviewed the PR and filled out the [checklist here](https://github.com/Expensify/App/pull/26836#issuecomment-1711602470)

**Comment by neil-marcellini** [comment] 2023-10-10 16:48
> @neil-marcellini Oh I see, so this is being counted as a regression of #26836, with the accompanying 50% penalty then?

Yes I think so. Let's get the payment wrapped up here please.

**Comment by paultsimura** [comment] 2023-10-10 16:54
Hey @neil-marcellini could you please check these comments?

https://github.com/Expensify/App/issues/27895#issuecomment-1729011721
https://github.com/Expensify/App/issues/27895#issuecomment-1729100868

I still don't think this was a regression, since enabling the offline flow was not on the plate of the original issue and was even clearly discussed in the PR.

However, if I'm referencing the wrong issue – please just disregard this message.

**Comment by neil-marcellini** [comment] 2023-10-13 16:34
Ok sorry about that and thanks for explaining. I see that the "regression" came from [this PR](https://github.com/Expensify/App/pull/26705). Also as you mentioned it wasn't really a regression because it was expected at that time. It's all very confusing so let's not penalize any payments.



> @neil-marcellini Ah we have already been paid for the [original issue](https://github.com/Expensify/App/issues/26537).

Ah ok great, then I'm closing this.

**Closed by neil-marcellini** 2023-10-13 16:34 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
