### ISSUE TITLE
[DEV] FAB menu items broken

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42171] opened 2024-05-14 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Main
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715715895936109

## Action Performed:
1. Launch the app 
2. Tap the plus icon

## Expected Result:
Context menu displayed without any issues
## Actual Result:
Context menu broken
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/70c1e4a1-1a43-459e-9d54-f068cf67ce9d" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2024-05-14 20:35
Currently on main only, but something we should fix before we even ship to staging

**Comment by s77rt** [comment] 2024-05-14 22:55
Thanks @ishpaul777!

**Comment by s77rt** [comment] 2024-05-14 22:59
Raised a PR https://github.com/Expensify/App/pull/42178

**Comment by Beamanator** [comment] 2024-05-15 06:54
This loooks like a small enough fix that we won't need a C+ review, thanks @ishpaul777 - I'll review shortly!

**Comment by abekkala** [comment] 2024-05-15 13:52
Looks like the only payment here will be to @s77rt for the fix
(Internal PR Review)

@Beamanator can you confirm what that payout amount is for this quick fix?

**Comment by s77rt** [comment] 2024-05-15 16:01
@abekkala No payment is required here since it was a regression from a PR that I reviewed

**Comment by s77rt** [comment] 2024-05-15 16:02
We can close this issue

**Closed** 2024-05-15 17:28 UTC
Labels: Engineering, Daily, Bug
