### ISSUE TITLE
[Performance] There’s constantly a pretty long delay between a message appearing in the LHN and that same message appearing in an individual’s chat.

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11082] opened 2022-09-19 04:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open chat with User A and send message
2. Put computer to sleep - mac
3. User A sends message
4. See new chat in LHN but not in main chat

## Expected Result:
New chat to show in main chat window 

## Actual Result:
New chat doesn't show in main chat with User A

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Desktop App

**Version Number:** 1.1.99-4
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663258735521259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment] 2022-09-21 15:38
discussion happening here https://expensify.slack.com/archives/C01GTK53T8Q/p1663690085941559

**Comment by mallenexpensify** [comment] 2022-09-21 21:14
Updated OP, @mvtglobally can you see if you can reproduce? Feel free to ping me in NewDot for testing too, I'm on til about 5pm Pacific time (another couple hours) today

**Comment by mallenexpensify** [comment] 2022-09-21 21:39
cc @marcaaron , since, I think, this is the _main_ issue for new messages not loading in the main chat window (ie. it's not related to LHN updates at all)

**Comment by marcaaron** [comment] 2022-09-22 00:21
Quick clarification on the title/description for this one... 

it says there's "constantly... a long delay between a message appearing in the LHN and that same message appearing in an individual’s chat". This would be more helpful if it reflected the exact conditions surrounding the bug + what was happening when it was experienced + the platform + the version.

@mallenexpensify you say it's the "main" issue? Why is that exactly?

Is it different from this issue -> https://github.com/Expensify/Expensify/issues/228883 ?

The reproduction steps in the description also imply the messages never appear and also mention putting the computer to sleep. What should we focus on here?

**Comment by mallenexpensify** [comment] 2022-09-23 01:59
ah.. shit, I think I had a draft open in another duplicate tab I closed.  tl,deleted: recap
- I've mostly been testing "Is it loading at all"
- I was unable to reproduce the issue this morn on Desktop
- iOS app is _acting weird_ , need to do more testing to confirm issue/s. 

> Is it different from this issue -> https://github.com/Expensify/Expensify/issues/228883 ?

It sounds like it's related, and possibly the same but I'm unsure if the reproduction steps are the same.   Recently I feel like we've had multiple issues for the same/similar bug and it's been confusing (I might be partially to blame, apologies if so).  I think, without having clean/clear reproducible steps in issues and a title that clearly states the bug being encountered, it can be tricky to differentiate.  I wonder for situations like this, if it's best to close and tag the folks affected and who reported asking them to open a new, clean issue with detailed reproduction steps if the bug is still happening.   Does that make sense @marcaaron ? (maybe I'm not phrasing it the best)

**Comment by marcaaron** [comment] 2022-09-23 17:08
>I wonder for situations like this, if it's best to close and tag the folks affected and who reported asking them to open a new, clean issue with detailed reproduction steps if the bug is still happening

Agree. And I think every bug report really needs to have as much information attached as possible and a clear title explaining what the bug is. 

Otherwise we end up with an amorphous "things are vaguely broken" issue that is impossible to do anything about.

**Comment by mallenexpensify** [comment] 2022-09-23 23:53
Dropped[ a reminder for CM team to triage ](https://expensify.slack.com/archives/C01SKUP7QR0/p1663971707009829)before posting jobs to Upwork (that wouldn't have helped this issue but it's still important) 

We can def improve the process for ensuring clean/clear details and reproducible steps. I'm going to hold off on making a handful of potential changes because the BugZero update should be coming soon and it should address them. 

Based on the reproducible steps in the OP, I think we should close this for now.  @JmillsExpensify if you're still experiencing delays when opening, can you report again in #expensify-open-source, provide details/steps and cc me? Thx

**Closed by mallenexpensify** 2022-09-23 23:53 UTC
Labels: Engineering, Daily, Overdue

**Comment by mvtglobally** [comment] 2022-09-26 05:50
@mallenexpensify i am not able to reproduce this issue. Asked team to check as well
