### ISSUE TITLE
[$500] Press highlight on a field in expense details overlaps with error message weirdly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34944] opened 2024-01-23 05:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705808584924989

## Action Performed:
Precondition : Have some violation rules for the expenses in the OD
1. Create an expense report 
2. Open the receipt to view the details
3. enter the required fields values (in this case category and tag fields)
4. Long press the category/tag field to highlight and observe

## Expected Result:
There should be no overlapping.
## Actual Result:
overlaps the error message weirdly
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/43996225/209e36c5-f75c-49c6-8a04-77be0052e4a9" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b61739c3e4f7859e</li>
        <li>Upwork Job ID: 1749662510960947200</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-23 06:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Highlighted area doesn't include the full row when there's an error message

### What is the root cause of that problem?
The highlight style doesn't grow into  full row when there's an error message.

### What changes do you think we should make in order to solve the problem?
We should update the styling to flex the highlighted area based on the content, inccluding the error message

### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2024-01-23 10:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error message out of hover frame

### What is the root cause of that problem?
Inside src/components/ReportActionItem/MoneyRequestView.js we are displaying the error message via ViolationMessages but the only hovered component is MenuItemWithTopDescription

### What changes do you think we should make in order to solve the problem?

The MenuItemWithTopDescription support displaying error via already existant props errorText.
We should pass the violation message throw it and remove ViolationMessages component.

POC:
![image](https://github.com/Expensify/App/assets/12425932/40616788-2948-4452-9ae6-d24b8a0c546c)

**Comment by luacmartins** [comment] 2024-01-23 16:18
Seems like a dupe of https://github.com/Expensify/App/issues/33527. @cead22 can you confirm if we're already fixing this?

**Comment by cead22** [comment] 2024-01-23 16:32
Yeah

**Closed by cead22** 2024-01-23 16:32 UTC
Labels: External, Daily, Help Wanted, Bug
