### ISSUE TITLE
[HOLD for payment 2022-11-18] [$250] Bug: [Android/Chrome] Not getting "copy URL to clipboard" option when long pressing on links at app download links page reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11893] opened 2022-10-16 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > About > App download links
2. Long press on any option
3. Press the back arrow and tap on "report a bug"

## Expected Result:
The "copy URL to clipboard" option should be visible

## Actual Result:
You can't see "copy URL to clipboard" option
(When I navigate to Concierge using "Report a bug" it shows up)

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196055521-0ad5d95f-8837-4220-8157-f228110864b3.mp4

https://user-images.githubusercontent.com/43996225/196055564-09131c75-08ff-4ba4-9f10-de422778f495.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665915639748169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment] 2022-10-18 17:58
I was unable to reproduce this on my iPad Chrome browser. Can you clarify what device and browser you are using?

**Comment by ntrepanier** [comment] 2022-10-18 18:56
Yep. Charged my phone and was able to reproduce on there.

**Comment by dangrous** [comment] 2022-10-18 23:54
@ntrepanier does your phone also pop up the link once you report the bug? The simulator doesn't show the copy URL popup, but also doesn't when I go to concierge (it just never shows up at all). Just getting a sense of whether this is a simulator issue or if it's another aspect of the actual bug

**Comment by dangrous** [comment] 2022-10-19 18:29
Hm, weird! May be a simulator issue then, which is annoying for testing. Still, the bug definitely exists - it's something to do with [this line](https://github.com/Expensify/App/blob/4dc7fef0ec778be71114898bdf7d56ed363bee0a/src/pages/settings/AppDownloadLinks.js#L88) and the function it calls; my guess is because it is trying to pop up a context menu in place for web that it doesn't know how to handle it on mobile. Going to put this as external and weekly for now!

**Comment by dangrous** [comment] 2022-10-24 19:31
Waiting for proposals, not overdue

**Comment by tienifr** [comment] 2022-10-27 10:34
# Proposal
## Problem
In https://github.com/Expensify/App/blob/main/src/pages/settings/AppDownloadLinks.js
we don't add `PopoverReportActionContextMenu` so the `copy URL to clipboard` can't show.
## Solution

```diff
+import PopoverReportActionContextMenu from '../home/report/ContextMenu/PopoverReportActionContextMenu';
...
            </ScrollView>
+            <PopoverReportActionContextMenu
+                            ref={ReportActionContextMenu.contextMenuRef}
+                        />
        </ScreenWrapper>
```

https://user-images.githubusercontent.com/113963320/198262309-79ad2ad5-4dea-4ba9-b3ed-8594235b9610.mp4

**Comment by ntrepanier** [comment] 2022-10-27 17:18
waiting for review @mananjadhav. Not overdue.

**Comment by mananjadhav** [comment] 2022-10-27 18:49
I went through @tienifr's proposal and it seems it'll work. 

What I don't see is the same copy to clipboard option for `Report a Bug`. I am testing this in `mWeb Safari`.

If we're adding it anyway, the above proposal looks fine.

🎀 👀 🎀 
C+ reviewed

**Comment by dangrous** [comment] 2022-10-28 00:56
This looks great @tienifr! Easy fix and seems to work well. @mananjadhav Are you saying you weren't seeing the pop up for Report a Bug? That's ideal, so I think we can move forward. If you were saying something else though, let me know.

At least for now we can definitely move forward, I'll assign you @tienifr.

**Comment by mananjadhav** [comment] 2022-10-31 03:41
> Are you saying you weren't seeing the pop up for Report a Bug? That's ideal,

@dangrous Yeah that's what I meant. @tienifr You can start with the PR.

**Comment by tienifr** [comment] 2022-10-31 03:45
@mananjadhav Could you please send the Upwork job link that I can apply to? thanks

**Comment by mananjadhav** [comment] 2022-10-31 05:31
> @mananjadhav Could you please send the Upwork job link that I can apply to? thanks

@ntrepanier Can you help with the Upwork job link please?

**Comment by mananjadhav** [comment] 2022-11-02 05:18
@ntrepanier @dangrous quick bump for the Upwork job here.

**Comment by dylanexpensify** [comment] 2022-11-02 09:04
Working on this now! Taking over for Nicole.

**Comment by dylanexpensify** [comment] 2022-11-02 09:06
upwork: https://www.upwork.com/jobs/~01566dc2f1c2e9a787

**Comment by tienifr** [comment] 2022-11-04 10:05
Hi @mananjadhav I just created PR for this issue: https://github.com/Expensify/App/pull/12463 please help to review. Thanks

**Comment by mananjadhav** [comment] 2022-11-04 11:32
Thanks @tienifr. Give me a few hours to get to the PR review and the testing.

**Comment by dylanexpensify** [comment] 2022-11-07 11:34
@mananjadhav any updates here?

**Comment by mananjadhav** [comment] 2022-11-07 11:37
@dylanexpensify Reviewed the PR, raised an exception, waiting for @tienifr to fix and update the PR

**Comment by dylanexpensify** [comment] 2022-11-17 09:13
working on list today

**Comment by mananjadhav** [comment] 2022-11-18 02:57
@dylanexpensify Is this eligible for 50% bonus 4th Nov and reviewed within 3-4 business working days.

**Comment by mananjadhav** [comment] 2022-11-21 08:05
This is due for payment. Should be process by today/tomorrow. 

cc - @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-11-21 10:49
reviewing today!

**Comment by dylanexpensify** [comment] 2022-11-22 08:22
offers sent! @mananjadhav @tienifr

**Comment by thesahindia** [comment] 2022-11-22 08:41
@dylanexpensify, I have applied to the job for reporting compensation.

**Comment by mananjadhav** [comment] 2022-11-22 08:50
applied @dylanexpensify

**Comment by dylanexpensify** [comment] 2022-11-22 12:04
@mananjadhav payment sent including bonus.

@tienifr waiting you to accept offer

**Comment by tienifr** [comment] 2022-11-28 08:18
@dylanexpensify I've accepted the offer, please proceed, thanks!

**Comment by dylanexpensify** [comment] 2022-11-28 11:15
@tienifr sent!

**Comment by dylanexpensify** [comment] 2022-11-30 08:34
@tienifr you've been paid out!

**Comment by mananjadhav** [comment] 2022-11-30 17:19
@dylanexpensify I just read that we're treating this as a bug. Shouldn't this be a feature request? It isn't that `Copy to clipboard` wasn't working. It wasn't there at the first place.

**Comment by dangrous** [comment] 2022-11-30 18:44
I think @mananjadhav is right; based on the code it looks like copying the link was only ever set up for web, and then later desktop. (The latest change that would affect this page was made 6 months ago, and it was _adding_ the macOS copy functionality.)

@dylanexpensify what do we think is the best way forward here? Just checking off the boxes and moving on?

**Comment by thesahindia** [comment] 2022-12-01 14:17
@dylanexpensify, payment is still pending for me ( I have accepted the offer)

**Comment by dylanexpensify** [comment] 2022-12-01 15:40
Ah, good catch @mananjadhav! I agree @dangrous let's check off and move forward then

**Comment by dylanexpensify** [comment] 2022-12-01 15:42
@thesahindia payment sent

**Comment by mananjadhav** [comment] 2022-12-01 18:42
@dylanexpensify Are we good to close this then?

**Comment by dylanexpensify** [comment] 2022-12-02 10:57
Yes!

**Closed by dylanexpensify** 2022-12-02 10:57 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment, Bug
