### ISSUE TITLE
[$1000] Details - In data of birth year selection keyboard area shows blank screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24397] opened 2023-08-10 23:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go staging
2. open personal details and data of birth
3.  click year selection
4.  on int keyboard is open on that time scroll the area means blank screen on keyboard area

## Expected Result:
 When keyboard closed year should be occupy the keyboard area

## Actual Result:
Showing blank screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c2feea41-ba52-44de-a4a5-e4d149c8dc34

https://github.com/Expensify/App/assets/43996225/1cdf08f3-8c50-4c94-8680-709520fe5fdb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @pradeepmdk

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691059074463359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01add3f6e75afd90f5</li>
        <li>Upwork Job ID: 1691500803327131648</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-08-14 21:16
Damnit - going to wait until I have access to an android tomorrow - Jules has one!

**Comment by sophiepintoraetz** [comment] 2023-08-15 16:23
https://github.com/Expensify/App/assets/42940078/41186025-c206-4401-a9a9-d0c990ce98e7

**Comment by shubham1206agra** [comment] 2023-08-17 09:24
> Looks like problem with `react-native-web` maybe. And if that's the case, it will not help with upgrade version. Already checked.

@sophiepintoraetz @abdulrahuman5196 I maybe have found the problem.

Android behaviour after the fix:

https://github.com/Expensify/App/assets/58412969/9991236d-07ba-44ca-9ad3-548ac6f51657

iOS safari behaviour after the fix:

https://github.com/Expensify/App/assets/58412969/80669704-9881-41f8-8c1a-7ac1bf019dce

**Comment by shubham1206agra** [comment] 2023-08-17 09:26
@abdulrahuman5196 @sophiepintoraetz Is this ideal behaviour?
If so, should I start PR upstream and put a patch here meanwhile (I will put a detailed proposal after soft approval from your side)?

**Comment by sophiepintoraetz** [comment] 2023-08-17 15:05
I think this looks good but I'll also get a 👍  from @abdulrahuman5196 too!

**Comment by shubham1206agra** [comment] 2023-08-18 08:53
> > > Looks like problem with `react-native-web` maybe. And if that's the case, it will not help with upgrade version. Already checked.It looks better. But It seems like an incorrect behaviour after the fix. As I understand, correct behaviour is when you start scrolling the list, the Virtual Keyboard should disappear. So you scrolling without keyboard. But in your fix we see Virtual Keyboard, and it close when you end scrolling.
> > 
> > @sophiepintoraetz @abdulrahuman5196 I maybe have found the problem.
> > 
> > Android behaviour after the fix:
> > 
> >  Screen.Recording.2023-08-17.at.2.49.46.PM.mov 
> > iOS safari behaviour after the fix:
> > 
> >  Screen.Recording.2023-08-17.at.2.51.57.PM.mov
> 
> It looks better. But It seems like an incorrect behaviour after the fix. As I understand, correct behaviour is when you start scrolling the list, the Virtual Keyboard should disappear. So you scrolling without keyboard (and there is more space for list items). But in your fix we see Virtual Keyboard, and it close when you end scrolling.

Yes I know that
But react-native-web doesn't support onScrollBeginDrag for now
That's why I am trying to close at the end instead.

I am looking into this. Will give an update once I get something which corrects the behaviour completely.

**Comment by sophiepintoraetz** [comment] 2023-08-21 19:49
[Bumped in slack for a review](https://expensify.slack.com/archives/C02NK2DQWUX/p1692647355005849?thread_ts=1692639370.734109&cid=C02NK2DQWUX)

**Comment by abdulrahuman5196** [comment] 2023-08-23 14:03
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-23 14:20
@sophiepintoraetz I am seeing this issue in the search page itself. Could be present throughout the app.

So it more likely an issue outside of expensify, but it is not something we can definitely say unless we have some solid root cause or fix. So we can't confirm about upstream fix before some proposal is made.

@shubham1206agra 
>I maybe have found the problem.

if you have found the root cause or fix, kindly post your proposal on root cause and solution, so that we can review.

**Comment by abdulrahuman5196** [comment] 2023-08-23 14:21
@sophiepintoraetz For now there is no proposal to review.

**Comment by abdulrahuman5196** [comment] 2023-08-28 15:32
@sophiepintoraetz Currently we don't have solid proposal. 
@shubham1206agra  mentioned to provide some updates but there is no proposal yet.

But if we want to increase the bounty we can.

**Comment by shubham1206agra** [comment] 2023-08-28 15:42
> > My proposal requires patching react-native-web. (I will post the details later).
> > But now the upgradation of react-native-web is happening. I say we will hold this issue till then.
> 
> We would need to know what is the fix actually? Without really knowing what is the fix suggested we might not be able to check this. We also need to think of what if the suggested doesn't work. So I think we can only hold if we have some information on the solution.

The fix requires some modification to the ScrollResponder System of the ScrollView component. Mostly to enable the option for the `keyboardShouldPersistTaps` prop and then set the prop to `never` for the web. (This approach fixes most things except one, i.e., long quick scroll will show the same behaviour cause the list is still scrolling and we have finished touch).

For the RNWeb, the complete implementation of ScrollView will not come before 0.21.
See https://github.com/necolas/react-native-web/issues/1592

So we have 2 options either keep open the Keyboard when scrolling in this case or do this partial fix.
The complete fix requires implementation of `onScroll(Begin|End)Drag` which will not implemented before 0.21 in RNWeb.

**Comment by sophiepintoraetz** [comment] 2023-08-30 21:06
I can drop this into the agency rooms as well to see if we can get some more proposals in, @abdulrahuman5196 (and if @shubham1206agra clarifications don't work)

**Comment by sophiepintoraetz** [comment] 2023-08-30 21:10
Dropped it into [callstack](https://expensify.slack.com/archives/C03UK30EA1Z/p1693429807053229)

**Comment by sophiepintoraetz** [comment] 2023-08-31 21:11
@abdulrahuman5196 I'm checking in with the contributors on the above linked issue, as Callstack suggested it may have caused this regression. I've asked them to confirm but maybe you can take a look as well?

**Comment by s77rt** [comment] 2023-09-01 11:06
I have checked, seems unrelated to that PR (judging from versions timeline). But I can't reproduce the bug, is it still reproducible?

**Comment by shubham1206agra** [comment] 2023-09-01 12:36
I am unable to repro this.

But it looks like the reason is some kind of race condition.
So can you please hold this issue for RNWeb upgrade PR, and finally confirm the issue repro after the merge?

**Comment by sophiepintoraetz** [comment] 2023-09-02 02:51
@shubham1206agra, can you link the upgrade PR please? @abdulrahuman5196 - do you agree with holding?

**Comment by shubham1206agra** [comment] 2023-09-02 03:21
#24482

**Comment by sophiepintoraetz** [comment] 2023-09-04 22:51
Agreed. I think we have enough details now to keep an eye on this but will close this out for now. Thanks all for the input!

**Closed by sophiepintoraetz** 2023-09-04 22:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by pradeepmdk** [comment] 2023-09-06 01:19
@sophiepintoraetz since this issue is still there https://github.com/Expensify/App/issues/26732 can we open this?

**Comment by shubham1206agra** [comment] 2023-09-06 01:23
Let's just wait for RNWeb PR to merge
