### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Chat - Unread message marker disappeared for next message if user stays in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39871] opened 2024-04-08 22:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990295
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions; Two users logged in. User A is in another chat
1. User B send message to User A
2. Chat between users marked as unread (for user A)
3. User A navigates to chat with user B
4. User B send another message

## Expected Result:

- After step 3, user A sees a new message marker with a green line above first message from user B. The new marker line is displayed over the original unread message
- After step 4, the new marker line remains, as messages come through. It won’t go away unless user switches to another chat.

## Actual Result:
After step 4, a new message marker disappeared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20727935-e75b-4bb0-9ea3-3a2bfdd14c06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cac380aa031e55a</li>
        <li>Upwork Job ID: 1792396283373867008</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by lanitochka17** [comment] 2024-04-08 22:03
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-08 22:04
We think that this bug might be related to #vip-vsp

**Comment by Christinadobrzyn** [comment] 2024-04-09 01:02
Asking qa team for some clarification on how they are getting the unread line - https://expensify.slack.com/archives/C9YU7BX5M/p1712624387659049

**Comment by Christinadobrzyn** [comment] 2024-04-10 04:08
@tienifr do you know what the issue is here? I got this second video from QA but I still think this is behaving as expected. I don't understand what we need to change here... 

https://github.com/Expensify/App/assets/51066321/fe3993c8-33f6-4185-a561-8da82a04b472

**Comment by Christinadobrzyn** [comment] 2024-04-11 02:36
Asking the Vip-vsb team for a buddy check on if this is a bug - https://expensify.slack.com/archives/C066HJM2CAZ/p1712802929200679

**Comment by Christinadobrzyn** [comment] 2024-04-12 08:10
Based on the convo in slack it sounds like the behaviour in the video is behaving as expected. 

@tienifr  I agree that we could come back to the 'unread' behaviour changes as a feature request but for the time being, this doesn't appear to be a bug so closing.

**Comment by MonilBhavsar** [comment] 2024-05-17 15:20
Commented in the thread because I feel like we should fix this

**Comment by MonilBhavsar** [comment] 2024-05-20 05:35
Thanks Christina I'm self assigning myself

**Comment by MonilBhavsar** [comment] 2024-05-20 05:35
@tienifr many things might have changed since your proposal. Do you want to take a look and share updated proposal?

**Comment by MonilBhavsar** [comment] 2024-05-21 06:41
Okay cool! Thanks for confirming. Since we're updating root logic, can we please make sure to test all cases to make sure we don't break it again


<details>
<summary>Tests
</summary>

1. Different chat open:

- Given a chat report between user A and user B, and user A and user C, and user A has chat view with user B open
- When user C sends message to user A, and user A switches to chat view with user C
- Then user A should see the new marker line above the new messages, and the new marker line should persist until userA switches to another chat view.

2. Same chat open(no unread message):

- Given a chat report between user A and user B, and user A has chat view with user B open and no unread message and no unread marker
- When user B sends message to user A
- Then user A should not see any new marker line

3. Same chat open(with unread message):

- Given a chat report between user A and user B, and user A has chat view with user B open and user A has unread messages and new marker line
- When user B sends message to user A
- Then the new marker line should persist until userA switches to another chat view.

4. Same chat open(with user scrolled up):

- Given a chat report between user A and user B, and user A has chat view with user B open and has no unread messages and no new marker line
- When user A scrolls up to the old chats and user B sends message to user A
- Then user A should see the green badge with “New Messages” and the new marker line above the new messages, and the new marker line should persist until userA switches to another chat view.

5. Redirecting to chat from email notification:

- Given a chat report between user A and user B, and user A is not active on chat or offline
- When user B sends message to user A and user A receives email notification and clicks on the link in the message
- Then user A should be redirected to the chat view with user B and see the new marker line above the new messages, and the new marker line should persist until userA switches to another chat view.

6. Marking message as unread:

- Given a chat report between user A and user B, and user A is active on a chat view with user B
- When user A marks any report as unread i.e. click on “Mark as unread”
- Then user A should see the new marker line above that message, and it won’t be removed until the user revisits the chat and switches to another chat then.

7. Deleting a message(other than unread message):

- Given a chat report between user A and user B, and user A is active on a chat view with user B, and there is an unread message and unread marker
- When user B sends a new message and deletes that message (other then the message above which there is an unread marker)
- Then there should be no effect on the new marker line and user A should see the new marker line, and it won’t be removed until the user switches to another chat or the sender deletes all new messages.

8. Deleting an unread message:

- Given a chat report between user A and user B, and user A is active on a chat view with user B, and there is an unread message and unread marker
- When user B deletes a message above which there is an unread marker
- Then user A should should not see the unread marker and the new message that was deleted

9. Marking as unread and deleting a message

- Given a chat report between user A and user B
- User A sends message to user B and marks the last sent message as unread
- User A deletes the last sent message
- Then the new marker line above last message should be removed
- Now user A, sends three messages to user B - `m1, m2, and m3` in order
- User A marks `m2` as unread
- Then New marker line should be above `m2`
- Now user A deletes `m2`
- Then new marker line should be above next message i.e `m3` in this case
</details>

**Comment by eh2077** [comment] 2024-05-22 18:07
@MonilBhavsar Thanks for sharing rich test cases. 

@tienifr 's [proposal](https://github.com/Expensify/App/issues/39871#issuecomment-2044652790) looks good. I agree with their RCA and solution. I think we can verify these tests in PR.

@MonilBhavsar All yours.

🎀👀🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment] 2024-05-28 07:52
watching https://github.com/Expensify/App/pull/42568

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:37
watching https://github.com/Expensify/App/pull/42568

**Comment by Christinadobrzyn** [comment] 2024-06-12 09:00
Payouts due:

- [ ] Contributor: $250 @tienifr (Upwork offer - https://www.upwork.com/nx/wm/workroom/37347265/overview)
- [ ] Contributor+: $250 @eh2077 (Upwork offer  - https://www.upwork.com/nx/wm/workroom/37347174/overview)

Upwork job is [here](https://www.upwork.com/jobs/~017cac380aa031e55a).

@eh2077 do we need a regression test?

**Comment by MonilBhavsar** [comment] 2024-06-12 09:26
Just a heads up! We should correct the Testrail case that was updated previously

**Comment by Christinadobrzyn** [comment] 2024-06-13 02:47
Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to [pay this out ](https://github.com/Expensify/App/issues/39871#issuecomment-2162484073) once we have the regression test

**Comment by Christinadobrzyn** [comment] 2024-06-13 02:49
@puneetlath when we have a regression test, can you please pay out based on this [payment summary](https://github.com/Expensify/App/issues/39871#issuecomment-2162484073)? 

@MonilBhavsar @eh2077 if I understand correctly, the new regression test is going to _replace_ the existing one?

**Comment by MonilBhavsar** [comment] 2024-06-13 05:46
We should correct the existing regression test with the correct expected behavior. Currently, the test is testing the incorrect behavior that marker should disappear when sending a message.

**Comment by puneetlath** [comment] 2024-06-13 19:19
@eh2077 bump on the checklist so we can pay.

**Comment by eh2077** [comment] 2024-06-14 09:55
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't think there's a specific PR responsible for it as we adjusted the expected behaviour, see [comment](https://github.com/Expensify/App/issues/39871#issuecomment-2164465702)**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes
- [x] [@eh2077] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test

1. User B send message to User A
2. Chat between users marked as unread (for user A)
3. User A navigates to chat with user B
4. User B send another message
5. Verify that after step 3, user A sees a new message marker with a green line above first message from user B. The new marker line is displayed over the original unread message
6. Verify that after step 4, the new marker line remains, as messages come through. It won’t go away unless user switches to another chat.
> [!NOTE]  
> Create or update existing regression tests as @MonilBhavsar mentioned https://github.com/Expensify/App/issues/39871#issuecomment-2164465702

Do we agree 👍 or 👎

**Comment by puneetlath** [comment] 2024-06-14 19:45
Regression test issue: https://github.com/Expensify/Expensify/issues/404987

All paid. Thanks everyone!

**Closed by puneetlath** 2024-06-14 19:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
