### ISSUE TITLE
Profile - Copy button next to email is smaller than the current button on production

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38333] opened 2024-03-14 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to any chat.
3. Tap on the chat header.

## Expected Result:
The copy button next to email will not be too small.

## Actual Result:
The copy button next to email is smaller than the current button on production.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/baf856b3-e7ce-41e7-8b96-65a330f3c0ed)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by godofoutcasts94** [comment] 2024-03-14 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - Copy button next to email is smaller than the current button on production
### What is the root cause of that problem?
Here : 
https://github.com/Expensify/App/blob/d4eaf4e2deabb6c07736b1eaefaa203cc9cf5850/src/components/ContextMenuItem.tsx#L104
The icon style defined is `small`
### What changes do you think we should make in order to solve the problem?

We need to change it to `medium`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-14 18:21
Updated [Proposal](https://github.com/Expensify/App/issues/38333#issuecomment-1998060433)

**Comment by luacmartins** [comment] 2024-03-14 18:31
This is fixed in staging already by this CP - https://github.com/Expensify/App/pull/38275

**Closed** 2024-03-14 18:31 UTC
Labels: Engineering, Hourly
