### ISSUE TITLE
[$500] WS avatar does not have any indent from the bottom edge of the header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36835] opened 2024-02-20 04:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch App
2. Navigate to any WS
3. Tap settings > Profile

## Expected Result:
WS avatar should have an indent from the bottom edge of the header

## Actual Result:
WS avatar does not have any indent from the bottom edge of the header.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Bug6385261_1708398822677!ws](https://github.com/Expensify/App/assets/43996225/b72ee5db-8d60-4111-85ef-469c77eb1286)

https://github.com/Expensify/App/assets/43996225/4e25e2e8-e33d-4253-8b85-56a0f0c334e3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c86444f0c4b200d4</li>
        <li>Upwork Job ID: 1759797554514292736</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-02-20 04:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The mtn17 value provided does not include a margin.

### What changes do you think we should make in order to solve the problem?

Change the `marginTop` of the `mtn17` style to `-78`.
```
    mtn17: {
        marginTop: -78,
    },

```

### What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment] 2024-02-20 04:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS avatar does not have any indent from the bottom edge of the header
### What is the root cause of that problem?
In the style of `WorkspaceProfilePage` i.e. here:
https://github.com/Expensify/App/blob/1806422ea2208540a89271da7026799a1ade9d69/src/pages/workspace/WorkspaceProfilePage.js#L112
In `mtn17`, we are using style as 
```
    mtn17: {
        marginTop: -68,
    },

```
### What changes do you think we should make in order to solve the problem?

We need to change it to 
```
    mtn17: {
        marginTop: -79,
    },

```
Already, working on this page, migration issue i.e. [Issue](https://github.com/Expensify/App/issues/36133). So, I can fix it in that if that's okay @puneetlath.

### Working Image
<img width="1203" alt="Screenshot 2024-02-20 at 10 16 00 AM" src="https://github.com/Expensify/App/assets/158435970/2c8be9bd-a0e5-4432-ad5f-3b8a243377f0">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2024-02-20 06:24
https://github.com/Expensify/App/pull/36426
cc: @narefyev91 @allroundexperts

**Comment by narefyev91** [comment] 2024-02-20 08:03
i will take care of it

**Comment by narefyev91** [comment] 2024-02-20 08:25
@situchan @allroundexperts ready to go https://github.com/Expensify/App/pull/36844

**Comment by puneetlath** [comment] 2024-02-21 20:40
Interesting, fair question, but this doesn't feel the same as the linked case. In this case it doesn't feel like your exact proposal was used. It was a simple fix that the original contributor raised on their own. And you didn't find the offending PR, so I don't think any compensation is due here.

**Comment by puneetlath** [comment] 2024-02-21 21:24
Closing since the PR was raised by the original C/C+ and CP'd to staging. Thanks for the quick fix!

**Closed by puneetlath** 2024-02-21 21:24 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted, Bug

**Comment by shawnborton** [comment] 2024-02-26 21:27
So we actually don't want any space below the avatar and the background image:
![CleanShot 2024-02-26 at 16 27 29@2x](https://github.com/Expensify/App/assets/2319350/1b645f46-c003-4d17-96ef-9e1b29df2660)

The problem is that in light mode, we aren't using the right background image.

**Comment by situchan** [comment] 2024-02-26 21:38
There's bug in dark mode as well. Background image is cut, not stretched gradiently to the bottom

<img width="705" alt="Screenshot 2024-02-27 at 3 37 07 AM" src="https://github.com/Expensify/App/assets/108292595/44b3b89c-ecce-41a1-9f3c-6a056703747f">

**Comment by shawnborton** [comment] 2024-02-26 21:40
Yeah, I think we need a follow up here with new images for the header area for both light and dark mode. And we need to revert this change. I also outlined a few more issues:
- The workspace name is not using the right font
- The currency row can be tapped even in read-only mode
