### ISSUE TITLE
[HOLD for payment 2024-08-01] Expense - Missing background image in the combined report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45569] opened 2024-07-17 07:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with user that has no unsettled expense.
3. Submit one manual expense (only one).
4. Click on the expense preview to go to the combined report.

## Expected Result:
There will be background image in the combined report.

## Actual Result:
There is no background image in the combined report.
This issue only happens in the combined report (one transaction view).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9141d4e8-77a6-4cd6-bb35-1e84357dd2b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment] 2024-07-17 07:41
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-07-17 07:42
Production 

https://github.com/user-attachments/assets/dac0e61f-202f-4bd1-9ecc-fd90e05b301b

**Comment by NikkiWines** [comment] 2024-07-17 15:40
I'm not seeing this behavior on staging v9.0.8-3

https://github.com/user-attachments/assets/f76689dc-899b-403f-8d48-ddbbb8d21700

**Comment by NikkiWines** [comment] 2024-07-17 17:13
Oh, yes thank you @kavimuru - i can reproduce the issue on staging now. I'm fairly confident this is due to https://github.com/Expensify/App/pull/45042/ 

It's a pretty minor bug, so I don't think it needs to be a blocker but we should spin up a follow up issue to resolve the bug. 

cc: @nkdengineer @Ollyws  @thienlnam

**Comment by nkdengineer** [comment] 2024-07-18 13:40
@NikkiWines I will create a PR tomorrow morning

**Comment by nkdengineer** [comment] 2024-07-19 05:30
@Ollyws The PR is [here](https://github.com/Expensify/App/pull/45746).

**Comment by stephanieelliott** [comment] 2024-08-02 09:42
Summarizing payment on this issue: 

 - Contributor:  @nkdengineer $250 via Upwork -- I extended the offer to you, please accept when you get a chance! https://www.upwork.com/nx/wm/offer/103368089
 - Contributor+: @nkdengineer $250 via NewDot -- Please request
 
 Upwork job is here: https://www.upwork.com/jobs/~018eb452959d186422

**Comment by nkdengineer** [comment] 2024-08-02 09:52
@stephanieelliott This issue is the regression from my PR.

**Comment by stephanieelliott** [comment] 2024-08-06 04:20
Ah ok thanks @nkdengineer! Closing this then.

**Closed by stephanieelliott** 2024-08-06 04:20 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
