### ISSUE TITLE
[$250] Bank account - Selected digit is not turned green &number entered is entered in incorrect place

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52577] opened 2024-11-14 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.62-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Go to workspace settings- enable workflow
3. Tap connect bank account - connect manually
4. Enter an incorrect magic code
5. Try to select any digit by tapping on it
6. Enter a number

## Expected Result:
Selected digit must be turned green and number entered must be entered in correct place

## Actual Result:
Selected digit is not turned green and number entered is entered in incorrect place

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4cb38890-89f9-4bf1-8ec7-1b27f27f1ff9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858629538288881697</li>
        <li>Upwork Job ID: 1858629538288881697</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

**Comment by truph01** [comment] 2024-11-14 16:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected digit is not turned green and number entered is entered in incorrect place

### What is the root cause of that problem?

We're using [GestureDetector](https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/components/MagicCodeInput.tsx#L375) in MagicCodeInput but we didn't wrap it in `GestureHandlerRootView`

Reference: https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/

We also wrapped `GestureDetector` inside `GestureHandlerRootView` in other places like [AvatarCropModal](https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/components/AvatarCropModal/AvatarCropModal.tsx#L379), ...

### What changes do you think we should make in order to solve the problem?


We should wrap `MagicCodeInput` inside `GestureHandlerRootView`, so in [here](https://github.com/Expensify/App/blob/d5a7b499d3ba2074f5ad069ed27a043d029d7036/src/components/ValidateCodeActionModal/ValidateCodeForm/BaseValidateCodeForm.tsx#L210), we can add `GestureHandlerRootView`

```
<GestureHandlerRootView
...
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by truph01** [comment] 2024-11-16 05:14
Note for C+: The link I mentioned [here](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/) suggest to use GestureHandlerRootView or gestureHandlerRootHOC, but using `gestureHandlerRootHOC` has 2 disadvantages:

1. We don't encourage using HOCs, refer: https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md
2. We're using `GestureHandlerRootView` in many places

As in the docs, they said that we should use `GestureHandlerRootView` in the root view, but we didn't do it in `BaseModal` or `PopoverWithoutOverlay`. I believe there's a reason that encourages us to use `GestureHandlerRootView` in the individual modal.

**Comment by truph01** [comment] 2024-11-21 03:28
@alitoshmatov Can you please review [my proposal](https://github.com/Expensify/App/issues/52577#issuecomment-2476860485)? Thanks

**Comment by johncschuster** [comment] 2024-11-21 22:54
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1732229604725569)

**Comment by alitoshmatov** [comment] 2024-11-26 12:08
@truph01 Thank you for your proposal, I suggest you provide more explanation on your root causes it seemed like it was just justifying your solution. I understood it after seeing @bernhardoj 's reasoning. Though your solution is correct and solves the issue.

**Comment by alitoshmatov** [comment] 2024-11-26 12:13
@bernhardoj Thank you for your proposal, your solution works, but I think it is better to just use `GestureHandlerRootView` inside modal component fixing `GestureDetector` to work in any modal

**Comment by alitoshmatov** [comment] 2024-11-26 12:14
We can go with @truph01 's [proposal](https://github.com/Expensify/App/issues/52577#issuecomment-2476860485) which solve the issue by adding `GestureHandlerRootView` inside modal

C+ reviewed 🎀 👀 🎀

**Comment by mvtglobally** [comment] 2024-11-29 04:25
Issue not reproducible during KI retests. (First week)

**Comment by truph01** [comment] 2024-11-30 02:39
@bernhardoj The docs recommend we use GestureHandlerRootView or gestureHandlerRootHOC.

> After installation, wrap your entry point with <GestureHandlerRootView> or gestureHandlerRootHOC.

But HOC is not recommend in our App.

> @truph01 proposal also doesn't handle the style break after applying GestureHandlerRootView.

If we decide to add it in `BaseValidateCodeForm`, we don't need to add styles, you can see my video in the proposal. We just need to apply `modalContainerStyle` in case we add it in BaseModal

**Comment by bernhardoj** [comment] 2024-11-30 04:05
> The docs recommend we use GestureHandlerRootView or gestureHandlerRootHOC.

I'm talking about this part of the doc: https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation#usage-with-modals-on-android

> But HOC is not recommend in our App.

This is not true.

> Hooks and HOCs
> Use hooks whenever possible, avoid using HOCs.

The docs stated to use hooks whenever possible, but GestureHandlerRootView is a View and not replaceable by a hook.

**Comment by bernhardoj** [comment] 2024-11-30 04:06
Looks like @alitoshmatov think that my proposal doesn't solve the issue globally which in fact does. Can you recheck all the conversation above? @alitoshmatov

**Comment by alitoshmatov** [comment] 2024-12-02 13:49
> Looks like @alitoshmatov think that my proposal doesn't solve the issue globally which in fact does. Can you recheck all the conversation above?

I am sorry, I think I miscommunicated there about this point.

**Comment by alitoshmatov** [comment] 2024-12-02 13:51
@bernhardoj Can we also remove all `GestureHandlerRootView` usages when applying your solution?

**Comment by bernhardoj** [comment] 2024-12-02 14:32
Yes, we should be able to do that since the HOC wraps the component with GestureHanderRootView, but it's only for Android based on the [doc](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/#usage-with-modals-on-android:~:text=To%20fix%20that%2C%20components%20need%20to%20be%20wrapped%20with%20gestureHandlerRootHOC%20(it%27s%20no%2Dop%20on%20iOS%20and%20web).).

I mentioned this in my proposal too.

> We need to wrap the modal content with a gesture handler root view. RNGH provides a HOC (gestureHandlerRootHOC ) that only wraps it on Android.

**Comment by truph01** [comment] 2024-12-03 02:49
@alitoshmatov GestureHandlerRootView also can apply in BaseModal

**Comment by bernhardoj** [comment] 2024-12-04 13:44
It was fixed in https://github.com/Expensify/App/pull/52802.

**Comment by alitoshmatov** [comment] 2024-12-07 16:08
Looks like this issue was duplicate of https://github.com/Expensify/App/issues/51293 and is resolved now

**Comment by alitoshmatov** [comment] 2024-12-10 19:58
I think we can close this issue

**Closed** 2024-12-13 22:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
