### ISSUE TITLE
[PAID] [$500] help.expensify.com is showing broken "Not found page"

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27405] opened 2023-09-14 03:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to help.expensify.com/abcd
2. Notice that there is overlapped not found text and broken image

## Expected Result:
Should show correct image and text without any overlapping

## Actual Result:
Shows overlapped text with broken image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.69-0
**Reproducible in staging?:** n/a 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/f0939489-3058-4278-b882-e99ceecab252

**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692796609530559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155f0466612861fa0</li>
        <li>Upwork Job ID: 1702163572248096768</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-09-14 03:33
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
[help.expensify.com](http://help.expensify.com/) is showing broken "Not found page"
### What is the root cause of that problem?
The image is broken because wrong image is being pointed to
https://github.com/Expensify/App/blob/867d61e237e6a4e0affaf71e6735d0cdf6969a70/docs/404.html#L5
the existing file is called [`circle-hourglass`](https://github.com/Expensify/App/blob/e7cfb99aa2847b9cdf4467deb3a56ebe258c28cb/docs/assets/images/circle-hourglass.svg#L6)
The overlapping is happening because `centered-content` class has `position: absolute`
https://github.com/Expensify/App/blob/867d61e237e6a4e0affaf71e6735d0cdf6969a70/docs/_sass/_main.scss#L566-L570
### What changes do you think we should make in order to solve the problem?
We should fix src of image to point to correct image.
I am assuming the whole page should just show `Hmm it's not here...` and when scrolled down the footer should appear, but we can clarify exact design with responsible person.
To achieve above mentioned case we just need to modify `centered-content` with something like this:
```css
    width: 100%;
    height: calc(100vh - 56px);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
```
**The result:**
<img width="1440" alt="Screenshot 2023-08-23 at 20 34 02" src="https://github.com/Expensify/App/assets/59907218/243b5ef0-f136-4181-9614-38c890c11c07">
https://github.com/Expensify/App/assets/59907218/0d86c098-4247-49fa-8b7d-4eb05f384ec2
### What alternative solutions did you explore? (Optional)

**Comment by mvtglobally** [comment] 2023-09-14 03:33
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
[help.expensify.com](http://help.expensify.com/) is showing broken "Not found page"
### What is the root cause of that problem?
The image is broken because wrong image is being pointed to
https://github.com/Expensify/App/blob/867d61e237e6a4e0affaf71e6735d0cdf6969a70/docs/404.html#L5
the existing file is called [`circle-hourglass`](https://github.com/Expensify/App/blob/e7cfb99aa2847b9cdf4467deb3a56ebe258c28cb/docs/assets/images/circle-hourglass.svg#L6)
The overlapping is happening because `centered-content` class has `position: absolute`
https://github.com/Expensify/App/blob/867d61e237e6a4e0affaf71e6735d0cdf6969a70/docs/_sass/_main.scss#L566-L570
### What changes do you think we should make in order to solve the problem?
We should fix src of image to point to correct image.
I am assuming the whole page should just show `Hmm it's not here...` and when scrolled down the footer should appear, but we can clarify exact design with responsible person.
To achieve above mentioned case we just need to modify `centered-content` with something like this:
```css
    width: 100%;
    height: calc(100vh - 56px);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
```
**The result:**
<img width="1440" alt="Screenshot 2023-08-23 at 20 34 02" src="https://github.com/Expensify/App/assets/59907218/243b5ef0-f136-4181-9614-38c890c11c07">
https://github.com/Expensify/App/assets/59907218/0d86c098-4247-49fa-8b7d-4eb05f384ec2
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment] 2023-09-15 00:13
Able to repro, will follow along.

**Comment by robertKozik** [comment] 2023-09-18 11:56
Sorry for keeping you waiting @alitoshmatov ! I assume you are the author of the proposal. I've managed to check it and it does the job. Let's proceed with it

🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment] 2023-09-19 03:09
Agreed, it looks like @alitoshmatov submitted the proposal in slack & it looks good, assigning 👍

**Comment by Beamanator** [comment] 2023-09-19 03:10
Oh I can't assign you @alitoshmatov until you comment in this issue 😬

**Comment by alitoshmatov** [comment] 2023-09-19 03:28
@Beamanator 👋

**Comment by Beamanator** [comment] 2023-09-19 03:33
Welp, I tagged jack in slack - please proceed with the PR while we get this hiring issue fixed :D

**Comment by alitoshmatov** [comment] 2023-09-20 08:17
Pr is ready - https://github.com/Expensify/App/pull/27839

**Comment by strepanier03** [comment] 2023-10-09 16:01
@alitoshmatov - I have hired you in Upwork and will pay when you accept the job. I made one contract for both reporting and contributing and will apply a bonus for the reporting job. 

Thanks!

**Comment by alitoshmatov** [comment] 2023-10-09 17:16
@strepanier03 Accepted

**Comment by alitoshmatov** [comment] 2023-10-12 09:18
@strepanier03 Friendly bump on payment

**Comment by Beamanator** [comment] 2023-10-16 11:47
Can this be closed? Or not quite yet?

**Comment by alitoshmatov** [comment] 2023-10-16 14:32
I have received payment yet

**Comment by strepanier03** [comment] 2023-10-17 00:16
@alitoshmatov - I've paid both payments and closed the contract, thanks for your patience there was a lot on my plate to get through. 

----

@Beamanator - Unless there's something I'm not aware of that means we don't need it, we're waiting on the BZ checklist responses from @robertKozik and then I can make a regression if needed and close this GH.

**Comment by robertKozik** [comment] 2023-10-17 08:17
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/12796
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/12796/files#r1361708247
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I think it's not needed here**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by strepanier03** [comment] 2023-10-17 23:41
Thank you @robertKozik - Looks like we're all set to close since no regression test is needed. 

Cheers everyone!

**Closed by strepanier03** 2023-10-17 23:41 UTC
Labels: External, Daily, Awaiting Payment, Bug
