### ISSUE TITLE
[$1000] Web - App automatically makes workspace chat read after some time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27367] opened 2023-09-13 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Notes: user B should be Web environment
1. Open the app and login with user A
2. Open the app in another app and login with user B (user B should be workspace admin of workspace in which user A is member)
3. Open settings ->workspaces->workspace with user A in it->members->remove user A
4. From user B, again add user A in the same workspace from which it was removed in step 3
5. In user A device, observe that workspace chat will be marked as unread, do not open it
6. Open new tab in user A browser and after sometime, check back on expensify tab to see that workspace chat is marked as read automatically

## Expected Result:
App should not mark any chat as read until it is opened by the user

## Actual Result:
App marks workspace chat as read automatically after sometime after user is added to a workspace

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/873d9c4b-c978-45f0-8c0c-1057bf86cdae

https://github.com/Expensify/App/assets/93399543/64612aae-3aef-4142-aff2-06a1956ab841

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694366389592829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af31ec1e8c7fc99e</li>
        <li>Upwork Job ID: 1701983446404337664</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-09-25 07:06
Not overdue.

**Comment by akamefi202** [comment] 2023-09-26 15:44
I can't reproduce this issue.

**Comment by dhanashree-sawant** [comment] 2023-09-27 05:17
We seem to have removed workspace chat feature or is it moved to beta? that part is essential in reproduction

**Comment by mvtglobally** [comment] 2023-09-28 03:20
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2023-09-28 04:35
Closing as not reproducible.

**Closed by kadiealexander** 2023-09-28 04:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
