### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Web -  Web – Personal Information– Blue border appears around “Passport” and “License” button.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23278] opened 2023-07-20 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" menu.
2. Click on "Workspaces."
3. Navigate to "Bank Account."
4. Click on "Connect bank account."
5. Proceed through all the steps until you reach the "Personal information" section (step 3 of 5).

## Expected Result:
There should be no visible blue border around the "Passport" and "License", making it consistent to other pages.

## Actual Result:
A blue border appears around the "Passport" and "License" buttons

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a6007d41-5ea8-4199-a00c-94b5bf64e212

https://github.com/Expensify/App/assets/93399543/0487b009-f9ca-4bd9-bb37-9bbe33fe2871

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689842884341259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136c5439985d07857</li>
        <li>Upwork Job ID: 1683455365164896256</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by Talha345** [comment] 2023-07-20 16:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A blue box shadow appears on Passport and License button on Hover.

### What is the root cause of that problem?

The RC is that we are using Onfido's SDK and this specific page is embedded using their SDK and the design on the buttons is not overridden correctly. 

### What changes do you think we should make in order to solve the problem?

We should add the following css to this file [here](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css#L13) to disable this behaviour for all buttons rendered by the Onfido SDK:

```
#onfido-mount button{
    box-shadow: none !important;
}
```



### What alternative solutions did you explore? (Optional)

**Comment by Talha345** [comment] 2023-07-20 18:11
> > issue. The error in the console also in

@ahmdshrif these are 2 different issues.This one is simply related to styling of buttons and has nothing to do with CSP.

**Comment by s-alves10** [comment] 2023-07-20 19:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Blue border appears when hover on Passport and License buttons

### What is the root cause of that problem?

We don't have custom styles for hovered buttons

### What changes do you think we should make in order to solve the problem?

Adding custom style to [index.css](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css)
```
#onfido-mount button:hover {
    box-shadow: none !important;
}
```

This works as expected.


### What alternative solutions did you explore? (Optional)
We can specify in more detail
```
#onfido-mount button.onfido-sdk-ui-DocumentSelector-DocumentList-option.onfido-sdk-ui-DocumentSelector-DocumentList-optionHoverDesktop:hover {
    box-shadow: none !important;
}
```

**Comment by bfitzexpensify** [comment] 2023-07-24 12:33
Not overdue, external.

**Comment by shawnborton** [comment] 2023-07-24 13:20
If we can change it, that would be great. But I am not sure if we are able to since it is coming from Onfido.

**Comment by s-alves10** [comment] 2023-07-24 13:21
It's possible for sure

**Comment by Talha345** [comment] 2023-07-24 13:37
@shawnborton @parasharrajat the buttons are coming from Onfido SDK but we are overriding the default design of the buttons.So we can override the box-shadow too.We are already doing it [here](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css#L13) as mentioned in my original proposal.

**Comment by Talha345** [comment] 2023-07-24 15:06
> @Talha345 I didn't go with your proposal because I think we should not disable the box-shadow directly on all buttons but rather to the specific states( Hover in this case).

@parasharrajat Actually, that was on purpose because otherwise we might have to deal with so many states.For example button A might have some behaviour on :hover while button B can have the same behaviour on :focus-visible, so my solution was actually 'generic' like you mentioned because like this we do not have to care about any states and it did not have any side-effects on any buttons.

**Comment by Talha345** [comment] 2023-07-24 15:28
> @Talha345 thanks for pointing out. Code sample's are only for explanation and adding `focus-visible` is probably a mistake, I only meant to remove focus on hover as i mentioned multiple times earlier like.
> 
> > We want to hide the blue outline when a button is hovered in onfido flow.
> 
> > Basically my [#23278 (comment)](https://github.com/Expensify/App/issues/23278#issuecomment-1647852068) focuses on removing the blue outline on hover from all onfido buttons
> 
> > and to fix all those we should use these styles to remove the border (on hover) from all the buttons in the onfido flow.
> 
> Also `box-shadow` alone won't remove the focus on all buttons.
> 
> cc: @parasharrajat

@huzaifa-99 Yes I know that `box-shadow` alone won't fix the problem for all buttons but again like I mentioned https://github.com/Expensify/App/issues/23278#issuecomment-1648036249 here,  the original task did not have other buttons in the scope and your solution to add ` border-color: transparent !important;` or `border: 0 !important` is correct but my point is that while working on the task one might encounter more buttons which have same behaviour but some other css property maybe is required to fix that, but that should be done in the PR itself and not every scenario should be covered in the proposal especially in cases like these when the only difference so trivial like just another css property.

In my opinion, anyone who pointed in the correct technical direction for such tasks should be chosen when the difference is so trivial.

**Comment by Talha345** [comment] 2023-07-24 15:31
> > @Talha345 thanks for pointing out. Code sample's are only for explanation and adding `focus-visible` is probably a mistake, I only meant to remove focus on hover as i mentioned multiple times earlier like.
> > > We want to hide the blue outline when a button is hovered in onfido flow.
> > 
> > 
> > > Basically my [#23278 (comment)](https://github.com/Expensify/App/issues/23278#issuecomment-1647852068) focuses on removing the blue outline on hover from all onfido buttons
> > 
> > 
> > > and to fix all those we should use these styles to remove the border (on hover) from all the buttons in the onfido flow.
> > 
> > 
> > Also `box-shadow` alone won't remove the focus on all buttons.
> > cc: @parasharrajat
> 
> @huzaifa-99 Yes I know that `box-shadow` alone won't fix the problem for all buttons but again like I mentioned [#23278 (comment)](https://github.com/Expensify/App/issues/23278#issuecomment-1648036249) here, the original task did not have other buttons in the scope and your solution to add ` border-color: transparent !important;` or `border: 0 !important` is correct but my point is that while working on the task one might encounter more buttons which have same behaviour but some other css property maybe is required to fix that, but that should be done in the PR itself and not every scenario should be covered in the proposal especially in cases like these when the only difference is so trivial and the fix is to just another css property.
> 
> In my opinion, anyone who pointed in the correct technical direction for such tasks should be chosen when the difference is so trivial.

For example, in this [issue](https://github.com/Expensify/App/issues/23067) I posted my proposal and the difference was trivial and therefore the first proposal was chosen and it totally made sense.

**Comment by Talha345** [comment] 2023-07-24 15:47
> I think your proposal aims to remove the box-shadow on all button states on the initial Onfido page, rig

Not only on the initial Onfido page but on all Onfido related pages as I mentioned in the [proposal](https://github.com/Expensify/App/issues/23278#issuecomment-1644216806) originally(see below) but I obviously did not go and check what other properties might be causing the issue for other buttons(that were not in the original task scope) as it is mentioned in the guidelines to just propose the technical solution and not the final code.

> We should add the following css to this file [here](https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css#L13) to disable this behaviour for all buttons rendered by the Onfido SDK:

**Comment by bfitzexpensify** [comment] 2023-08-10 14:40
Great, thanks @parasharrajat - test to update QA here - https://github.com/Expensify/Expensify/issues/307183.

All done here, thanks everyone!

**Closed by bfitzexpensify** 2023-08-10 14:40 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bfitzexpensify** [comment] 2023-08-10 14:53
Hm, I thought I just paid that out @huzaifa-99, let me double check

**Comment by bfitzexpensify** [comment] 2023-08-10 15:00
OK, created a new job and sent out an offer @huzaifa-99

**Comment by bfitzexpensify** [comment] 2023-08-10 15:09
Can do! Looks like https://github.com/Expensify/App/issues/23278#issuecomment-1661250660 was incorrect 😅, but thank you for pointing that out! 

Offer amended, and @usmantariq96 you should have the reporting offer too now.

**Comment by usmantariq96** [comment] 2023-08-10 15:13
@bfitzexpensify accepted.
Thanks

**Comment by JmillsExpensify** [comment] 2023-08-16 03:17
Reviewed the details for @parasharrajat. Payment approved in NewDot based on BZ summary above.
