### ISSUE TITLE
[$250] "Next" and "split" button moves a bit when navigate back

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41855] opened 2024-05-08 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715122550547929

## Action Performed:
1. Launch the app
2. Tap the fab > Split expense
3. Enter amount and Choose from contacts
4. Tap Next > Tap the back arrow
5. Tap Next again
## Expected Result:
No visual issues when navigating back and forth
## Actual Result:
After step 4 and 5 "Next" and "Split" button moves
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/29d10bfc-a168-4e55-85e2-75ae331a6ffd

https://github.com/Expensify/App/assets/38435837/2b45f179-abe9-48de-a10d-6c83254ca83e

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01419f469e7473b289</li>
        <li>Upwork Job ID: 1789073733749583872</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by bernhardoj** [comment] 2024-05-09 07:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The next and split button moves down when navigating between pages while a keyboard is open.

### What is the root cause of that problem?
The button is wrapped with FixedFooter.
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/FixedFooter.tsx#L17-L29

The confirmation page uses BaseOptionsSelector which uses FixedFooter.

In FixedFooter, we add a bottom padding if the keyboard shown state is true. When we move to the confirmation page while the keyboard is shown, both the padding-bottom from FixedFooter and the confirmation page itself are added. After the keyboard state is fully hidden, the padding-bottom from FixedFooter is gone, so the button moves down a bit.

In the money request participants page, we are using BaseSelectionList and only add the padding-bottom if the keyboard is hidden. The list footer also uses FixedFooter.
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseSelectionList.tsx#L517-L518

So, when we open/close the keyboard, you will see the button move up/down based on the keyboard state.

I believe the reason we add the padding-bottom in FixedFooter only when the keyboard is shown is because the padding-bottom in BaseSelectionList is gone when the keyboard is shown. It's to replace the removed padding-bottom so the list footer content has a padding-bottom.

Without padding-bottom (if we remove the padding-bottom logic from FixedFooter):
<img width="438" alt="image" src="https://github.com/Expensify/App/assets/50919443/4704a982-db16-49a6-aca3-78e2a56af16f">

The reason we don't apply padding-bottom in BaseSelectionList when the keyboard is shown is to [fix a small blank space above the keyboard](https://github.com/Expensify/App/pull/21048#issuecomment-1616735118). This is because of the padding bottom that we apply to the list. If we apply it (includeSafeAreaPaddingBottom) to the ScreenWrapper, the issue won't happen

### What changes do you think we should make in order to solve the problem?

Remove the padding-bottom logic based on the keyboard state from FixedFooter. Then, we will apply the padding-bottom in BaseSelectionList if there is a footer.
https://github.com/Expensify/App/blob/807c945ef8edabe86cc62f16c866aa754db8750b/src/components/SelectionList/BaseSelectionList.tsx#L518

```
(!isKeyboardShown || !!footerContent || showConfirmButton) && safeAreaPaddingBottomStyle
```

### What alternative solutions did you explore? (Optional)
Remove the safe area padding bottom from BaseSelectionList and enable includeSafeAreaPaddingBottom to every page that uses BaseSelectionList. Currently, all pages that use BaseSelectionList disables includeSafeAreaPaddingBottom to not have double padding bottom.

**Comment by alexpensify** [comment] 2024-05-10 22:54
On my testing list, I'll get to it soon.

**Comment by youssef-lr** [comment] 2024-05-10 23:10
@alexpensify I think this fits as a general improvement to the UI and not particularly tied to any project. It makes the UI looks glitchy and unpolished.

**Comment by alexpensify** [comment] 2024-05-10 23:24
Thanks, @youssef-lr, for the context! Assigning the `external` label now. 

@Ollyws please review the proposal and identify if it will fix the issue. Thanks!

**Comment by bernhardoj** [comment] 2024-05-14 05:36
PR is ready

cc: @Ollyws

**Comment by youssef-lr** [comment] 2024-05-14 06:13
@bernhardoj are you seeing this?

![image](https://github.com/Expensify/App/assets/9680864/fc580485-1823-48a5-af0f-1d7caf03d3b7)

**Comment by bernhardoj** [comment] 2024-05-14 06:14
@youssef-lr yes, I'm seeing that on `main` too.

**Comment by alexpensify** [comment] 2024-05-17 15:57
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@kevinksullivan - While I'm offline, I need help here completing the payment process after this one clears the 7-day period. Thanks!

**Comment by alexpensify** [comment] 2024-05-28 19:35
Thanks, @kevinksullivan for the help here. I'm back online and taking over again as the BZ member. Tomorrow, I'll start the payment process since it looks like automation failed in this GH.

**Comment by alexpensify** [comment] 2024-05-29 22:34
Payouts due: 2024-05-29

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @Ollyws 

Upwork job is [here](https://www.upwork.com/jobs/~01419f469e7473b289).

**Comment by alexpensify** [comment] 2024-05-29 22:39
I've paid @bernhardoj via Upwork. @Ollyws, please accept the invite and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-05-30 22:47
Awesome, and sorry for the confusion. I didn't see you listed in the SO. Closing since the final payment will happen in Chat.

**Closed by alexpensify** 2024-05-30 22:47 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 03:34
$250 approved for @Ollyws
