### ISSUE TITLE
[$1000] Duplicate message is added as a reply when a thread is created with Concierge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19982] opened 2023-06-01 16:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in with a new account
2. Go to the Concierge chat
3. Hover over the welcome message from Concierge
4. Click on "Reply in thread" icon
5. A duplicate message is automatically created 

## Expected Result:
Duplicate message is not added

## Actual Result:
Duplicate message is added automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (49)](https://github.com/Expensify/App/assets/93399543/9e9335bf-9156-481b-9d96-02bdc4613129)

https://github.com/Expensify/App/assets/93399543/7c78ad0f-7e13-4c34-8c72-d946da2e3f5d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685376443197059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112169a401d6af226</li>
        <li>Upwork Job ID: 1665799955615621120</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-01 16:56
@Christinadobrzyn Can you please check this issue https://expensify.slack.com/archives/C049HHMV9SM/p1685376970661379, I think it can be fixed with this. 
Thank you

**Comment by Christinadobrzyn** [comment] 2023-06-02 21:31
I think these might be different but I can't reproduce this duplicate message on the web or desktop - asking for more information in the Slack chat - https://expensify.slack.com/archives/C049HHMV9SM/p1685741458516499?thread_ts=1685376443.197059&cid=C049HHMV9SM

**Comment by StevenKKC** [comment] 2023-06-03 09:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Duplicate message is added as a reply when a thread is created with Concierge.

### What is the root cause of that problem?
When display the thread, will be display the parent report action by the below code.
https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/home/report/ReportActionsList.js#L120

If the thread is created with Concierge, the first report action is the thread created message. And the parent report action is just the welcome message from Concierge.
And because we just replied to the welcome message, the second report action is also the welcome message.
So duplicated message is displayed.

### What changes do you think we should make in order to solve the problem?

When display the thread, if the thread includes Concierge, then don't show the parent report action.

```
const shouldDisplayParentAction = reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.CREATED && ReportUtils.isThread(report) && !ReportUtils.chatIncludesConcierge(report);
```

### What alternative solutions did you explore? (Optional)
None

**Comment by Christinadobrzyn** [comment] 2023-06-05 19:17
I'm able to reproduce this with the steps in the OP. @kbecciv I think this is different from https://expensify.slack.com/archives/C049HHMV9SM/p1685376970661379

adding external

**Comment by abdulrahuman5196** [comment] 2023-06-07 18:15
I don't think its a duplicate message. It the standard welcome message concierge is posting on all threads created from the concierge main chat. I think this is an expected behaviour.
Kindly confirm
@yuwenmemon @Christinadobrzyn 


https://github.com/Expensify/App/assets/46707890/940eafb5-9536-477e-8137-67c66f8867ab

**Comment by abdulrahuman5196** [comment] 2023-06-09 16:51
If we think this is an issue. Then we should stop adding these welcome message on thread created from welcome. This should be fixed in backend IMO. Correct me if wrong @yuwenmemon

**Comment by abdulrahuman5196** [comment] 2023-06-12 16:52
@yuwenmemon waiting for you on this

**Comment by yuwenmemon** [comment] 2023-06-13 21:01
If the message is disappearing it seems like that would actually be a front-end thing? Have you tried reproducing using the network tab open?

**Comment by abdulrahuman5196** [comment] 2023-06-14 20:15
@yuwenmemon 

>If the message is disappearing

Not sure what you mean by disappearing?


The issue is new concierge messages are added when a thread is created from any message on parent Concierge chat.

**Comment by yuwenmemon** [comment] 2023-06-14 21:17
I see. Yes then this is most likely internal. Thanks @abdulrahuman5196!

**Comment by Christinadobrzyn** [comment] 2023-06-16 17:46
This is internal so I think this ^ doesn't apply

**Comment by Christinadobrzyn** [comment] 2023-06-20 18:43
Do we have a PR for this yet @abdulrahuman5196 or @yuwenmemon? Just checking if we can move this to `weekly` while we review the PR.

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:24
Do you we have a PR to track for this yet?

**Comment by Christinadobrzyn** [comment] 2023-06-27 18:45
@yuwenmemon or @abdulrahuman5196 can you provide an update on a PR for this or if you'd like me to move move this to weekly?

**Comment by abdulrahuman5196** [comment] 2023-06-28 04:50
@yuwenmemon would be one to answer this. I won't have access to backend information.

**Comment by yuwenmemon** [comment] 2023-06-28 23:31
The issue is not reproducible anymore. Closing!

**Closed by yuwenmemon** 2023-06-28 23:31 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by mountiny** [comment] 2023-09-21 02:55
@adeel0202 I dont see any PR linked to this, even internal, in such case we dont usually pay out for reporting as we ahevnt done anything intentional to fix this

**Comment by mountiny** [comment] 2023-09-21 06:32
I dont think @yuwenmemon fixed this with internal PR as that would be linked here. I am sorry, I could not in anything linked to this and this is a guideline we apply across the App, if there is not specific PR which would fix this issue we would know about, we wont pay out for reporting bonus as these things come and go.

**Comment by mountiny** [comment] 2023-09-21 07:48
Np
