### ISSUE TITLE
[$250] Android -Unable to change workspace currency on first try when tapping while keyboard is up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51389] opened 2024-10-24 08:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/51173
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1936@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open newDot hybrid app
2. Create a workspace
3. Go to workspace profile settings
4. Open workspace currency
5. Search for other currency for e.g "EUR"
6. Tap on the EUR currency while keyboard is up

## Expected Result:
The currency gets selected and app navigates back to workspace profile settings page

## Actual Result:
The currency does not get selected on first trial, user has to tap on the currency multiple of times

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7a3c72d1-11ee-4881-b61e-c778a1e5a58c

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852235095885144546</li>
        <li>Upwork Job ID: 1852235095885144546</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104728790</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jnowakow</details>

**Comment by ChavdaSachin** [comment] 2024-10-24 10:41
## Proposal




### Please re-state the problem that we are trying to solve in this issue.

Android -Unable to change workspace currency on first try when tapping while keyboard is up



### What is the root cause of that problem?

We do not dismiss keyboard on `WorkspaceProfileCurrencyPage` as we do on `IOURequestStepCurrency`
https://github.com/Expensify/App/blob/8e13bcc227cbc330b80bdfdb6bd6c87b232dd6d1/src/pages/workspace/WorkspaceProfileCurrencyPage.tsx#L21-L24

https://github.com/Expensify/App/blob/8e13bcc227cbc330b80bdfdb6bd6c87b232dd6d1/src/pages/iou/request/step/IOURequestStepCurrency.tsx#L57-L64


### What changes do you think we should make in order to solve the problem?

Add `Keyboard.dismiss();` here
https://github.com/Expensify/App/blob/8e13bcc227cbc330b80bdfdb6bd6c87b232dd6d1/src/pages/workspace/WorkspaceProfileCurrencyPage.tsx#L21-L24



### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Christinadobrzyn** [comment] 2024-10-25 06:25
Hybrid app so this needs to go through Internal to see if we want to fix it. Reaching out to the team to see if we can make this external since it's affecting another app.

**Comment by Christinadobrzyn** [comment] 2024-10-29 03:59
Retested this and it's only affecting the Hybrid App not the Android Standalone app. I'm thinking we can close this but I'll double-check with the team.

**Comment by trjExpensify** [comment] 2024-10-29 10:37
>it's only affecting the Hybrid App not the Android Standalone app.

HybridApp will be the primary app downloaded and used by customers, so we can't just blanket close these issues because they're seemingly only occurring on HybridApp only. 

@Julesssss @AndrewGable @mateuuszzzzz @staszekscp @war-in any thoughts on why this can't go external, given the [above RCA](https://github.com/Expensify/App/issues/51389#issuecomment-2434922955)?

**Comment by Julesssss** [comment] 2024-10-29 12:56
> Is this reproducible on New Expensify Standalone?: Y

> Retested this and it's only affecting the Hybrid App not the Android Standalone app

We should clarify with @IuliiaHerets in case this was reproducable on NewDot standalone in specific circumstances? 

But yeah, this could be worked on by the SWM team.

**Comment by Christinadobrzyn** [comment] 2024-10-30 02:57
Okay sounds good - [asking QA](https://expensify.slack.com/archives/C9YU7BX5M/p1730256854915919) to check if this is only happening on Android Hybrid App or on other apps with specific circumstances. I'll reach out to SWM based on the decision.

**Comment by Christinadobrzyn** [comment] 2024-10-31 06:54
monitoring QA testing

**Comment by Christinadobrzyn** [comment] 2024-11-01 06:24
Okay, gonna add External to see if @shubham1206agra can review this [proposal](https://github.com/Expensify/App/issues/51389#issuecomment-2434922955) or determine if we should reach out to SWM.

**Comment by Christinadobrzyn** [comment] 2024-11-04 01:59
[Reached out to SWM](https://expensify.slack.com/archives/C04878MDF34/p1730685567444349) to see if anyone has the bandwidth to take this issue.

**Comment by Christinadobrzyn** [comment] 2024-11-04 06:43
[Reached out to SWM](https://expensify.slack.com/archives/C04878MDF34/p1730685567444349) to see if anyone has the bandwidth to take this issue.

**Comment by jnowakow** [comment] 2024-11-04 08:39
Hello, I'm from Software Mansion and I'll work on this issue

**Comment by Christinadobrzyn** [comment] 2024-11-04 08:58
Awesome Thanks @jnowakow! I added you to this issue, thank you for joining us!

**Comment by jnowakow** [comment] 2024-11-04 09:57
I've build hybrid app from the newest main with newest ND main and I couldn't reproduce the problem neither on simulator nor on physical device.
I'm trying to reproduce it on other branches and in release variant

**Comment by trjExpensify** [comment] 2024-11-04 11:56
Is it specific to some Android devices/OS version or something maybe? 🤔 @mvtglobally what device and OS was the tester using above?

**Comment by jnowakow** [comment] 2024-11-04 12:06
I've check it on samsung galaxy a33 with android 14 and on LG K42 with android 12

**Comment by jnowakow** [comment] 2024-11-04 12:47
Okey, I can reproduce the bug when I'm on main in OD and commit `788939a` in ND. It's the PR that hybrid app currently is pointing to. So bumping the version of ND in hybrid app should fix the issue

**Comment by Christinadobrzyn** [comment] 2024-11-06 02:36
Oh great @jnowakow! Thanks for the investigation. 

Do you think this is resolved? I can ask QA to test again if that's the case

**Comment by jnowakow** [comment] 2024-11-06 07:37
@Christinadobrzyn yeah I think it's resolved because I couldn't reproduce it on Monday. But let QA confirm that on the latest hybrid app build. They're build once a day so latest build should have this problem solved

**Comment by Christinadobrzyn** [comment] 2024-11-07 05:24
Asking QA to test - https://expensify.slack.com/archives/C9YU7BX5M/p1730957039833679

**Comment by Christinadobrzyn** [comment] 2024-11-08 00:07
QA can't reproduce this, so I think we're good to close. 

I don't think there are any payouts due but let me know otherwise!

**Comment by mvtglobally** [comment] 2024-11-08 15:27
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-11-11 02:43
Closing as this seems to be resolved.

**Closed by Christinadobrzyn** 2024-11-11 02:43 UTC
Labels: External, Daily, Overdue, Bug
