### ISSUE TITLE
[$500] Split - Red dot for Merchant disappears after Amount is entered in failed scan split request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34389] opened 2024-01-11 19:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a Scan split request with a receipt that will fail the scanning.
3. When the scanning fails, click on the Split scan preview.
4. Note that there is a red dot next to Merchant.
5. Enter amount and save it.

## Expected Result:
The red dot next to Merchant will persist, until user manually enters a Merchant.

## Actual Result:
The red dot next to Merchant disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d49dbe66-f81e-470d-9ee0-51a076badf29

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c6967f6ee2264a2</li>
        <li>Upwork Job ID: 1745532652572520448</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-11 19:48
Should be fixed here: https://github.com/Expensify/App/issues/33876

**Comment by stephanieelliott** [comment] 2024-01-12 22:22
Yes seems like a dupe of https://github.com/Expensify/App/issues/33876

**Closed by stephanieelliott** 2024-01-12 22:22 UTC
Labels: External, Daily, Help Wanted, Bug
