### ISSUE TITLE
[$1000] Web - Deleted attachment while uploading is shown for the receiving user for a moment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22962] opened 2023-07-16 01:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with two accounts at the same time User A and user B 
2. Open a chat and send an attachment from user A to B
3. Delete the attachment while uploading
4. Keep an eye on the User B ( The receiving user ) chat just after deleting

## Expected Result:
Deleted attachments while uploading shouldn't be sent to user B ( The receiving user ), and user B shouldn't get anything in the chat.

## Actual Result:
 An attachment loading spinner  is shown for Usr B ( The receiving user ) for a moment and then gone.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 15-07-23 03_40_01.webm](https://github.com/Expensify/App/assets/93399543/b68e1a8d-1d10-4d37-92ed-d85bf5e4dbd1)

https://github.com/Expensify/App/assets/93399543/848c93cc-e1ca-43b8-b669-95880442c7cb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689381372513729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137d7fa3c9a7d3ccb</li>
        <li>Upwork Job ID: 1681078045273849856</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by s77rt** [comment] 2023-07-18 18:00
Started a discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1689703182154509

**Comment by akamefi202** [comment] 2023-07-20 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sender deleted the attachment before upload is finished. But the deleted attachment is shown once for the receiver.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/Network/SequentialQueue.js#L33
All API requests will be saved in `PersistedRequests` and they will be processed one by one.
So `attachment upload` and `attachment delete` request will be also processed in order.
As a result, the attachment will be uploaded and deleted immediately so the receiver will see it for a moment.

### What changes do you think we should make in order to solve the problem?
I guess we should be able to edit or cancel requests in queue.
So if the sender deletes the attachment before upload is finished, we need to cancel `attachment upload` request.
And the receiver won't see the deleted attachment.

> Go offline.
Send some text messages.
Delete the text messages.
Go back online.
You will notice that the same issue can be reproduced in this scenario as well. When we do add and delete actions in offline mode and go back online. Both add and delete requests will be processed.

I think we can improve messaging UX in offline status too by implementing this.

https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/actions/PersistedRequests.js#L27
There is a `remove` function but it's only used for removing a processed request.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment] 2023-07-20 15:38
Contributor details
Your Expensify account email: akamefi202@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b371ed61a241a259

**Comment by s77rt** [comment] 2023-07-20 17:32
@Nodebrute Thanks for the proposal. Your RCA is correct. The solution does not have to be from the BE, I don't think it should.

**Comment by s77rt** [comment] 2023-07-20 17:33
@akamefi202 Thanks for the proposal. Your RCA is correct. The solution makes sense but it's not clear how it can be executed. We are discussing this in Slack.

**Comment by akamefi202** [comment] 2023-07-20 18:44
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/actions/Report.js#L874-L876
I think we need to add code inside `deleteReportComment` function.

https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/Network/SequentialQueue.js#L126-L131
First, we can get the report ID of current request using `getCurrentRequest` function.
Next, we compare it with the ID of report(attachment) which the user want to delete.
If they match, this means that the user want to delete the attachment before it's uploaded.
So we need to cancel the current request.

https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/HttpUtils.js#L133-L139
Then we can cancel the current API request which is in progress using `cancelPendingRequests` function.

**Comment by s77rt** [comment] 2023-07-20 21:58
@akamefi202 `cancelPendingRequests` would cancel all pending requests and not just the add comment one.

**Comment by akamefi202** [comment] 2023-07-21 07:23
@s77rt 
https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/Network/SequentialQueue.js#L49-L53
First, I think `SequentialQueue` processes API requests one by one. It processes next request after previous one is processed or cancelled. 
So, there will only one request which is in progress at the moment.

https://github.com/Expensify/App/blob/be2c81fb1e0b27517451a6d00be097c8d3954ef6/src/libs/HttpUtils.js#L138
Next, `cancelPendingRequests` cancels that one request which is in progress now.
After that, it creates a new instance of `AbortController`. So it doesn't cancel subsequent requests automatically.

The term `cancelPendingRequests` might cause confusion but I think the function cancels only one API request which is in processing.
So we can use it to cancel `attachment upload` request that is not completed yet.

**Comment by s77rt** [comment] 2023-07-21 18:48
@akamefi202 Thanks for the update. `cancelPendingRequests` will cancel any pending request, it won't guarantee you that you are cancelling the `AddComment` request.

**Comment by s77rt** [comment] 2023-07-24 10:04
Not overdue. Bumped the slack discussion. We may end up closing this issue.

**Comment by anmurali** [comment] 2023-07-24 15:22
Seems like they clarified this can still be reproduced. Unassigning myself as I am OOO for 10 days

**Comment by isabelastisser** [comment] 2023-07-24 16:20
Confirmed in this[ discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1689703182154509) that we should close this issue.

**Closed by isabelastisser** 2023-07-24 16:20 UTC
Labels: External, Daily, Help Wanted, Bug
