### ISSUE TITLE
[$500] [MEDIUM] Referral - Referral link is incomplete and missing contact details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32292] opened 2023-11-30 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31827
## Action Performed:

1. In Safari or Chrome on Mac OSX, go to staging.new.expensify.com 
2. Create a new user account
3. Tap Search
4. Tap on the referral banner at the bottom
5. Tap Copy referral link
6. Paste the link

## Expected Result:
The referral link is complete

## Actual Result:
The referral link is incomplete. The link is missing contact details
This issue happens for some accounts but not all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/f3fdab66-45be-4b3e-bb72-e8546d445859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdb9a4da6bb420f6</li>
        <li>Upwork Job ID: 1730291484465594368</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28033535</li>
<li>tienifr | Contributor | 28135729</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by jayeshmangwani** [comment] 2023-11-30 18:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Referral link is showing empty email address when we generate referral link

### What is the root cause of that problem?
On the referral page src/pages/ReferralDetailsPage.js Page when we are generating the referral url using the `generateReferralURL` function
we are using the `account.primaryLogin` as a email address and sometimes (when a single email added as a contact method) we has empty primaryLogin value
`urlToCopy={generateReferralURL(account.primaryLogin)}`



### What changes do you think we should make in order to solve the problem?
Instead ad of the `account.primaryLogin` we should use the `session.email` or we can use the `account.primaryLogin || session.email` as a email address here
`urlToCopy={generateReferralURL(account.primaryLogin || session.email)}`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by chiItepin** [comment] 2023-12-03 18:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The email details is not being populated to the copied shareable url for users that recently joined the app

### What is the root cause of that problem?

I don't think there's a need to fix on the service side, this should be addressed on the FE app.

The root cause lies on the `ReferralDetailsPage` component.
https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/pages/ReferralDetailsPage.js#L57-L59

And how is being called below with the primaryLogin, so it's assuming it's not empty:
https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/pages/ReferralDetailsPage.js#L92-L95

### What changes do you think we should make in order to solve the problem?


We should provide the credentials stored on Onyx, these hold the credentials the new user just entered to join the app, and on top of that, we should validate whether the `primaryLogin` at the account level is not empty, if it is, then we should be able to use the `login` at the `credentials` level which holds the primary login method the user recently entered.

### What alternative solutions did you explore? (Optional)
We could retrieve a user's session email through Onyx as well

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by conorpendergrast** [comment] 2023-12-05 14:47
Are there more specific reproduction steps that you were able to work out in developing your proposals @jayeshmangwani, @tienifr or @chiItepin? I haven't been able to reproduce through the steps above, but based on @tienifr details it seems like it might be: 

1. In Safari or Chrome on Mac OSX, go to staging.new.expensify.com 
2. Create a new user account
3. Tap Search
4. Tap on the referral banner at the bottom
5. Tap Copy referral link
6. Paste the link

Is that correct?

**Comment by chiItepin** [comment] 2023-12-05 15:17
@conorpendergrast Yes, that's exactly right, it only happens for recently created accounts. This also explains why the "credentials" entity does have the "login" set in the onyx store

**Comment by situchan** [comment] 2023-12-05 16:57
Taking this over

**Comment by situchan** [comment] 2023-12-05 17:15
@jayeshmangwani's [proposal](https://github.com/Expensify/App/issues/32292#issuecomment-1834363435) looks good to me.
There was similar [issue](https://github.com/Expensify/App/issues/19366) in the past and we decided to [use session.email](https://github.com/Expensify/App/pull/28164) instead of fixing in backend.
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2023-12-06 07:18
Maybe @roryabraham has better context

**Comment by tgolen** [comment] 2023-12-07 16:35
Oof, that's a long issue. It would be great if you had a TLDR @roryabraham.

**Comment by situchan** [comment] 2023-12-13 15:49
I don't think using `session.email` is workaround.
Waiting for @roryabraham's confirmation either to use `session.email` or fix in backend.

**Comment by tgolen** [comment] 2023-12-13 16:11
Rory is still on jury duty for today and tomorrow. I think that's fine. This isn't super urgent.

**Comment by roryabraham** [comment] 2023-12-17 21:15
The back-end "fix" for that issue was implemented, it just ... didn't actually fix the issue.

Sorry if I missed this, but what precisely do we think is the root cause?

**Comment by conorpendergrast** [comment] 2023-12-18 15:34
Rory is OoO for jury duty again.

@roryabraham I'll assign you for follow-up when you're back!

**Comment by conorpendergrast** [comment] 2023-12-21 12:38
Rory is back! Assigning him for follow-up

**Comment by roryabraham** [comment] 2023-12-28 00:19
Had deja vu creating [this PR](https://github.com/Expensify/Web-Expensify/pull/40299), but verified that it fixes the issue. The [previous implementation](https://github.com/Expensify/Web-Expensify/pull/38748) of the same thing might have been accidentally removed in a bad merge resolution or something.

**Comment by mvtglobally** [comment] 2024-01-03 05:49
Issue not reproducible during KI retests. (First week)

**Comment by roryabraham** [comment] 2024-01-09 03:46
This has been fixed (confirmed during KI retests, as this issue was consistently reproducible).

**Comment by situchan** [comment] 2024-01-23 18:52
@roryabraham the bug is still reproducible. Can we reopen?

**Comment by roryabraham** [comment] 2024-01-24 08:23
Hey, sorry for missing these pings – the issue was closed so fell off my radar. Reopening this

**Comment by roryabraham** [comment] 2024-01-24 08:24
@situchan what do you recommend for next steps? @tienifr's [proposal](https://github.com/Expensify/App/issues/32292#issuecomment-1835390293) seems reasonable to me – is that it or is there still some other problem?

**Comment by situchan** [comment] 2024-01-24 08:27
Should we fix both issues?
You said first bug was fixed in backend but still reproducible and QA team reported same issue - https://github.com/Expensify/App/issues/34977

We can apply same solution in frontend as in https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js#L76

**Comment by jayeshmangwani** [comment] 2024-01-24 10:16
issue is described the missing contact details and not the wrong contact details, and in order to fix the original issue we have to add the `account.primaryLogin || session.email` code.

**Comment by situchan** [comment] 2024-01-24 10:55
> @situchan what do you recommend for next steps? @tienifr's [proposal](https://github.com/Expensify/App/issues/32292#issuecomment-1835390293) seems reasonable to me – is that it or is there still some other problem?

As seen latest comments, if we decided to fix 1st bug in frontend, whom to assign is a problem depending on whether 2nd bug is essential part of this issue or not.
If 1st bug doesn't need to be fixed in frontend, we can assign @tienifr

**Comment by conorpendergrast** [comment] 2024-01-29 11:37
It does seem like we should fix both cases (missing and wrong). 

I'm sorry, I can't see if this is a frontend or a backend fix. Who can advise on that?

**Comment by situchan** [comment] 2024-01-29 11:41
@suneox you mean that issue successfully fixed in backend for email login case? But this only happens on social login?

**Comment by conorpendergrast** [comment] 2024-01-29 17:10
Checking the right wave, through [this internal channel](https://expensify.slack.com/archives/C02MW39LT9N/p1706548232782599)

**Comment by situchan** [comment] 2024-01-29 17:59
> > you mean that issue successfully fixed in backend for email login case? But this only happens on social login?
> 
> @situchan Correct API [BeginSignIn](https://vscode.dev/github/suneox/ExpensifyApp/blob/fix/26401-scroll-on-virtual-viewport/src/libs/actions/Session/index.ts#L288) has fixed but API [SignInWithApple](https://vscode.dev/github/suneox/ExpensifyApp/blob/fix/26401-scroll-on-virtual-viewport/src/libs/actions/Session/index.ts#L305) and API [SignInWithGoogle](https://vscode.dev/github/suneox/ExpensifyApp/blob/fix/26401-scroll-on-virtual-viewport/src/libs/actions/Session/index.ts#L322) BE doesn't return `primaryLogin` for `ONYXKEYS.ACCOUNT` so we can fix at FE side when set `optimisticData`

Why not we fix them in backend as well?

**Comment by situchan** [comment] 2024-01-30 09:45
BE fix is ideal solution ofc.
@roryabraham will decide.

**Comment by roryabraham** [comment] 2024-02-01 19:53
Since this is now a wave issue, I'm going to treat it with higher priority and work on fixing it in the backend

**Comment by roryabraham** [comment] 2024-02-01 20:32
> The referral link is incomplete. The link is missing contact details

Was not able to reproduce this original issue.

**Comment by situchan** [comment] 2024-02-01 20:34
@roryabraham please login with Google using gmail account which is new to Expensify

**Comment by roryabraham** [comment] 2024-02-01 20:35
Oh, gotcha – this is part of what I missed. It needs to be a Google/Apple sign-in. I've never tested that in our local dev environment. Let me try to look into how that works...

**Comment by roryabraham** [comment] 2024-02-01 21:18
Thanks to some help from @aimane-chnaif, I was able to reproduce the Google Sign In case locally. It's a pain to reproduce it multiple times because it requires creating a new Google Account.

**Comment by roryabraham** [comment] 2024-02-01 22:13
I'll work on the back-end changes to fix Apple and Google Sign in such that they return the `primaryLogin` for the `ACCOUNT` key.

But I think @tienifr's [proposal](https://github.com/Expensify/App/issues/32292#issuecomment-1835390293) makes sense to fix this case in the front-end:

> when setting another contact method as default [here](https://github.com/Expensify/App/blob/63014263a542633621da9efd7617b5f9d0879fcc/src/libs/actions/User.js#L678), the primaryLogin is not updated in optimistic data. This causes the primaryLogin to be outdated in many different places that use it, when we update the default contact method.

Right @situchan ?

**Comment by situchan** [comment] 2024-02-01 22:15
yes, in that case (backend fix for google sign-in), @tienifr is the right contributor to be assigned

**Comment by roryabraham** [comment] 2024-02-01 22:24
@tienifr assigning you to make this change:

> Update primaryLogin to newDefaultContactMethod in optimistic data [for the SetContactMethodAsDefault API command] (and restore in failure data) when updating the default contact method

**Comment by roryabraham** [comment] 2024-02-02 01:46
> primaryLogin still not return in response for ONYXKEYS.ACCOUNT when SignInWithGoogle

Yep, back-end PR is not done yet

**Comment by roryabraham** [comment] 2024-02-05 18:16
Hmmm @suneox that does look like a pretty reasonable solution, but can we do the same thing for Apple sign-in?

**Comment by roryabraham** [comment] 2024-02-06 00:14
Back-end PR done: https://github.com/Expensify/Web-Expensify/pull/40789

**Comment by roryabraham** [comment] 2024-02-07 09:41
Back-end PR was merged but not yet deployed. It should be deployed within 24 hours

**Comment by situchan** [comment] 2024-02-09 18:47
Not overdue. Waiting for @tienifr to raise PR

**Comment by roryabraham** [comment] 2024-02-13 18:20
@tienifr you should be unblocked to raise the PR now. Let us know if you have an estimate when you'll be able to do that.

**Comment by roryabraham** [comment] 2024-03-11 17:41
looks like the PR just wasn't linked correctly or our automation wasn't working. The PR has been on prod for 2 weeks with no regressions, so we can pay it out ASAP.

**Comment by roryabraham** [comment] 2024-03-11 17:42
@miljakljajic should be $500 each to @tienifr (C) and @situchan (C+)

**Comment by miljakljajic** [comment] 2024-03-19 13:28
Extended the contract to you too @tienifr

**Closed** 2024-03-19 14:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
