### ISSUE TITLE
Hybrid App - "Try the Expensify App" option in Hybrid doesn't work after OD redirection

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#34747] opened 2024-01-18 17:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-7
**Reproducible in staging?:** Hybrid app
**Reproducible in production?:** Hybrid app
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705577844094939

## Action Performed:
1. Open the hybrid app
2. Navigate to settings > Try New Expensify
3. In a conversation, upload a receipt that will fail
4. Wait for the notification that the receipt needs attention
5. Interact with the notification - This will redirect you to the OD app
6. Navigate back to settings and click on try New Expensify again

## Expected Result:
The Try New Expensify option should work in any scenario. 

## Actual Result:
The Try New Expensify option doesn't work after interacting with the Notification.

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/b4d4ec8f-a5fa-4c76-b4e4-1a9f7beeb576

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164f32906e3eb56ea</li>
        <li>Upwork Job ID: 1748030512970407936</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by AndrewGable** [comment] 2024-01-22 17:04
Internal, we are working on this

**Comment by anmurali** [comment] 2024-01-30 23:29
Being worked on.

**Comment by anmurali** [comment] 2024-02-06 16:41
@AndrewGable - can you post a quick update for Melvin here? And switch it back to `Weekly` if that's the right cadence? Not sure why Melvin switched it back to `Daily`

**Comment by AndrewGable** [comment] 2024-02-06 17:20
Weekly for sure, it's a bug we are working on for HybridApp but haven't got to it yet. It's internal because the code is closed source.

**Comment by AndrewGable** [comment] 2024-02-15 17:35
Removed bug label for now as this ping is getting a bit much

**Comment by AndrewGable** [comment] 2024-02-29 23:33
I will double check that this still happens

**Comment by AndrewGable** [comment] 2024-03-11 19:58
Dupe of https://github.com/Expensify/App/issues/36717, being actively worked on.

**Closed by AndrewGable** 2024-03-11 19:58 UTC
Labels: Weekly, Internal, Overdue
