### ISSUE TITLE
[$500] Expense - Workspace under "To" field is highlighted after opening user avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36577] opened 2024-02-15 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount > Next.
4. Select a workspace > Next.
5. On confirmation page, click on the workspace under "To".
6. Click on the user avatar (not workspace avatar).
7. Return to confirmation page via back button on the top left.

## Expected Result:
The workspace name under "To" will not be highlighted.

## Actual Result:
The workspace name under "To" is highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ba52b88c-f125-47b3-b1b3-80caeba73266

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd38066315528994</li>
        <li>Upwork Job ID: 1758115460406108160</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-15 13:07
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by Beamanator** [comment] 2024-02-15 15:04
I agree this should be changed, but I don't think it should be a blocker

**Comment by ikevin127** [comment] 2024-02-15 15:31
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The workspace name option under "To" is highlighted after opening user avatar.

### What is the root cause of that problem?

I was not able to find an offending PR. This being said, here's what causes the option to be highlighted once user views avatar (modal opens):
- when the avatar modal is opened this causes the componentDidUpdate of the BaseOptionsSelector to run due to re-render which changes the focusedIndex from 1 to 0 (`selectedOptions.length`) here:

https://github.com/Expensify/App/blob/32648bbd01b2f1e98ff7273a92deb4c4bb10d7cb/src/components/OptionsSelector/BaseOptionsSelector.js#L163-L171

but this shouldn't happen in our case since both previous and current `selectedOptions.length`  are 0 (empty array) and focusedIndex was initialized with `1` on component mount.

### What changes do you think we should make in order to solve the problem?

Above the code block mentioned in RCA, add the following check:

```js
    if (_.isEqual(this.props.selectedOptions.length, prevProps.selectedOptions.length)) {
        return;
    }
```

just like we did above in the same componentDidUpdate by comparing previous / current sections and returning if equal.

This will return if both previous and current `selectedOptions.length` are 0 (not changed), preventing the setState to set `focusedIndex` to 0 and highlighting the option.

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/5ad6bb19-6884-4eb4-ac7c-70a834b1032d"> | <video src="https://github.com/Expensify/App/assets/56457735/3bb2d366-b470-4d04-9d42-d0a52e293cd7"> |

</details>

**Comment by ikevin127** [comment] 2024-02-15 16:12
## Updated proposal
- added offending PR and explanation of what lead to this issue

> Not reproducible on main branch, we don't allow users to open workspace details.

That's correct as currently on production we don't allow users to open workspace details and preview the avatars but since the PR https://github.com/Expensify/App/pull/35594 was merged, we don't disable the option anymore - and this issue can be observed on staging.

**Comment by Pujan92** [comment] 2024-02-15 16:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace option kept highlighted once we come back after opening the profile avatar

### What is the root cause of that problem?
It seems the problem persists after this [PR](https://github.com/Expensify/App/pull/28999) gets merged.
Reason: When we open the profile avatar it calls the api `openPublicProfilePage` and its response will update the `personalDetailsList ` onyx data which eventually regenerates the `participants` array here. Due to that `sections` prop gets changed and the execution will reach to set a new focused index part unnecessarily in `BaseOptionsSelector`.

https://github.com/Expensify/App/blob/50e07e8604d40b278c1ede2fc5c6fb78c97f1c1f/src/pages/iou/request/step/IOURequestStepConfirmation.js#L99-L106

https://github.com/Expensify/App/blob/421bbc5e319ffe906471a93917d789ed606e1a7e/src/components/OptionsSelector/BaseOptionsSelector.js#L149-L172

### What changes do you think we should make in order to solve the problem?
I believe it should be `||` here instead of `??` bcoz currently it won't check the second condition as the first will always return the boolean value which isn't null. With that change, it returns early and won't make the unnecessary api call when the `avatarURL` is available.

https://github.com/Expensify/App/blob/38c6c164c91ccc4c1a31e513301ec94436eac9b6/src/pages/settings/Profile/ProfileAvatar.tsx#L30-L34

```js
if (!ValidationUtils.isValidAccountRoute(Number(accountID)) || !!avatarURL) {
```

**Comment by ikevin127** [comment] 2024-02-16 14:48
> it returns early and won't make the unnecessary api call when the avatarURL is available.

I must mention the call is not `unnecessary` and that the 2nd proposed solution would break the avatar functionality in case the avatar is changed from another device because if we apply the solution that would mean the `OpenPublicProfilePage` won't be called anymore when `avatarURL` changes.

<details>
<summary>Proposal 2 - Solution Result Video (breaking avatar functionality)</summary>

https://github.com/Expensify/App/assets/56457735/e2a24bc6-fdb4-4cd4-981f-44a1fb3b578b

</details>

<details>
<summary>Proposal 1 - Solution Result Video</summary>

https://github.com/Expensify/App/assets/56457735/48850668-d35b-4e65-9bac-aca92ba90223

</details>

cc @Pujan92 @ntdiary

**Comment by ikevin127** [comment] 2024-02-16 15:08
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- added alternative solution which fixes the issue from `ProfileAvatar.tsx` without breaking ProfileAvatar's functionality

**Comment by ikevin127** [comment] 2024-02-20 17:25
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- updated RCA with detailed information about the specific field which causes the re-render

The re-render is caused by the fact that within `BaseOptionsSelector`, the previous and current props of `sections[0].data[0].participantsList[0].isLoading` change their boolean value when `OpenPublicProfilePage ` is called by opening the avatar preview 🙂

<details>
<summary>Video</summary>

https://github.com/Expensify/App/assets/56457735/e07f3127-d794-4bfe-987e-4e3f0a16e67f

</details>

cc @ntdiary

**Comment by ikevin127** [comment] 2024-02-21 16:43
@ntdiary How about early return when previous and current `isLoading` mentioned changes, would that satisfy ?

**Comment by ikevin127** [comment] 2024-02-22 14:02
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- changed solution according to reviewer's [#36577 (comment)](https://github.com/Expensify/App/issues/36577#issuecomment-1957092851) + detailed breakdown of how the solution works

@ntdiary Hope this one satisfies 🙂

**Comment by ikevin127** [comment] 2024-02-22 15:46
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- changed solution according to reviewer's [#36577 (comment)](https://github.com/Expensify/App/issues/36577#issuecomment-1957092851) - fixing the issue while ensuring that the code after the condition can be executed normally in any other scenarios

@ntdiary Hope this satisfies 🙂

**Comment by ikevin127** [comment] 2024-02-23 13:20
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- updated solution to satisfy latest reviewer's [#36577 (comment)](https://github.com/Expensify/App/issues/36577#issuecomment-1959744733) by disabling the focus behaviour all together leveraging existing `disableFocusOptions` prop based on:

> Actually, focusedIndex doesn't seem to be used on this confirm page, so some possible directions are: how to keep it unchanged when re-rendering, or `whether it can be disabled`, etc.


cc @ntdiary Maybe this one will satisfy 🙂

**Comment by ikevin127** [comment] 2024-02-23 14:18
> Hmm Kevin's updated proposal is essentially

Nope it's not 😅  I'm not disabling any Pressable nor changing any existing styles.
I'm using an already existing prop to **disable the focus behaviour** since as mentioned by latest reviewer's comment:

> Actually, focusedIndex doesn't seem to be used on this confirm page

which also hinted at disabling the focus behaviour if possible.

My solution is simply adding a prop (1-liner), exactly what was suggested for as possible solution since all my previous solutions were too complicated. Also your solution is pretty vague:

> We should extend our BaseGenericPressable class to account for pressable that we don't want to have a hover state.

don't you think ? Besides suggesting changing the common BaseGenericPressable's styles which has nothing to do with the RCA of our issue 🙂

**Comment by slafortune** [comment] 2024-02-26 18:17
@ntdiary is there a proposal here that will do the trick or are we still waiting on a better one?

**Comment by ikevin127** [comment] 2024-02-27 20:13
> There might be potentially better ideas.
> BTW, this issue is somewhat similar to issue https://github.com/Expensify/App/issues/37238, so I will also discuss it there. :)

This issue's root cause is related to `OpenPublicProfilePage` being called which updates `focusedIndex` because `isLoading` changes its boolean value, while the other issue's accepted RCA was pretty vague, mentioning that the sections prop changes and suggested to compare previous / current sections as a fix.

Turns out the fix PR from https://github.com/Expensify/App/issues/37238 selected proposal didn't work as expected and a regression was reported.

I think regardless of the root cause of the other issue, my latest proposed solution would fix both issues since as you mentioned above:

> Actually, `focusedIndex` doesn't seem to be used on this confirm page

To me, this looks like a straight-forward slam dunk 🏀
I'm confused as to what's the hold up w/ this one really 🤔

cc @ntdiary @dangrous

**Comment by dangrous** [comment] 2024-02-27 22:02
I just went on parental leave so I haven't been paying attention to this one haha - @slafortune do you think you could fish for an internal volunteer in Slack? I can help if needed!

**Comment by ikevin127** [comment] 2024-02-28 02:07
## Updated [proposal](https://github.com/Expensify/App/issues/36577#issuecomment-1946332354)
- improved solution by passing `selectedOptions.length <= 1` to disableFocusOptions, therefore accounting for possible regressions when it comes to a similar [issue](https://github.com/Expensify/App/issues/37238)'s solution (multiple options)

To +1 on my previous  https://github.com/Expensify/App/issues/36577#issuecomment-1967517205, this is a direct quote of @ neil-marcellini from https://github.com/Expensify/App/issues/37238#issuecomment-1968029563:

> I think we have a pretty clear problem and solution for this specific issue. There are other issues I'm sure, but let's solve those elsewhere.

My take from that is that we should handle this issue here and treat it as separate from the other similar issue - which just merged the PR that will soon arrive on staging.

I'm pretty sure our issue will still occur even after that issue's PR arrives on staging, since my proposal's RCA will still occur even though the other proposal's solution added an early return if previous - current sections are equal.

cc @ntdiary

**Comment by slafortune** [comment] 2024-02-29 21:40
@ntdiary are you able to recreate this still?

**Comment by slafortune** [comment] 2024-03-07 13:27
@ntdiary do you have an update?

**Comment by slafortune** [comment] 2024-03-08 13:36
AH - Thanks for the details and linking that @ntdiary !  I think since this is a pretty edge case and OptionsSelector is deprecated we don't really need to hold we can simply close this.

**Closed by slafortune** 2024-03-08 13:36 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
