### ISSUE TITLE
[$500] BA - Error is not cleared after coming back to Connect manually empty form.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37732] opened 2024-03-05 11:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+vd_mweb030424@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:**  Applause-Internal Team

## Action Performed:
Pre-requisite: the user must be logged in and have created a Workspace.

1. Go to Workspace > Bank account.
2. Tap on Connect manually.
3. Enter "011401533" as the Routing number.
4. Enter "0000" as the Account number.
5. Tap on Next.
6. Confirm on the double check page.
7. Verify you are taken back to the form and an error is displayed.
8. Tap on "fix the errors".
9. Verify nothing happens.
10. Tap on the back arrow.
11. Tap on Connect manually.
12. Verify that the error is still displayed.

## Expected Result:
When the error appears, tapping on "fix the errors" should focus where the error is. After coming back to the empty form, the error should not be displayed.

## Actual Result:
When the error appears, tapping on "fix the errors" does nothing. After coming back to the empty form, the error is still displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fe719191-d881-4817-ac38-4210d529f0ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011eb90ac2e3759c98</li>
        <li>Upwork Job ID: 1767861127265402880</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-05 11:27
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dragnoir** [comment] 2024-03-05 17:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error message persist when navigating back and to the screen again

### What is the root cause of that problem?

The error message on `Manual` is from a parent component `ReimbursementAccountPage` on an Onyx data.

Going back and to the screen again, does not erase or nullish the error value.

### What changes do you think we should make in order to solve the problem?

When we trigger the goBack action from the Manual add your bank account screen to the previous screen, we need to update the Onyx value of the error message.

https://github.com/Expensify/App/blob/e3b10f7da5a6935a0fe461f7acf950129d6a04f0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L377-L379

### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2024-03-06 10:45
Apologies, I've been OOO sick, but getting to this today!

**Comment by dylanexpensify** [comment] 2024-03-11 09:45
Apologies on delay here, team! Was sick all last week. Looking into this now!

**Comment by dylanexpensify** [comment] 2024-03-11 09:49
[Confirming here on placement!](https://expensify.slack.com/archives/C036QM0SLJK/p1710150552968649)

**Comment by Swor71** [comment] 2024-03-12 16:23
Opened the [PR](https://github.com/Expensify/App/pull/38148) directly as this was a follow up to a feature Callstack worked on and it's a small fix.

**Comment by dylanexpensify** [comment] 2024-03-13 10:31
thanks @Swor71!

**Comment by dylanexpensify** [comment] 2024-03-13 10:31
adding label for C+

**Comment by godofoutcasts94** [comment] 2024-03-13 12:31
> Opened the [PR](https://github.com/Expensify/App/pull/38148) directly as this was a follow up to a feature Callstack worked on and it's a small fix.

Is this issue open for proposal ? @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-03-20 11:43
@godofoutcasts94 @s77rt is correct

**Comment by roryabraham** [comment] 2024-03-21 01:16
Removing the `Help Wanted` label since we've already got a PR, which I just merged

**Comment by dylanexpensify** [comment] 2024-03-26 10:38
Wahoo!

**Comment by dylanexpensify** [comment] 2024-03-29 13:18
@s77rt mind giving an update?

**Comment by s77rt** [comment] 2024-03-29 17:37
@dylanexpensify PR hit production 3 days ago. Can you please prepend to the title `[HOLD for payment 2024-04-03]`

**Comment by dylanexpensify** [comment] 2024-04-04 12:51
Apologies, paying now!

**Comment by dylanexpensify** [comment] 2024-04-04 12:52
Payment summary:
- Contributor+: @s77rt $500

Please apply/request!

**Comment by s77rt** [comment] 2024-04-04 19:53
@dylanexpensify There is an active contract already

**Comment by dylanexpensify** [comment] 2024-04-09 08:18
Apologies, all done!

**Closed by dylanexpensify** 2024-04-09 08:18 UTC
Labels: External, Daily, Overdue, Bug
