### ISSUE TITLE
[Awaiting Payment][$1000] Web - Sometimes, after creating a new group with email and phone number as participants, only participants with email are displayed in the group chat report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22138] opened 2023-07-03 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to an account
2. Click on FAB button and select New group
3. In the contact list, select both email and phone number as participants
4. Create group and check the participants information in the group chat report

## Expected Result:
All participants should be displayed in the group chat report

## Actual Result:
Sometimes, the participants with phone numbers are not displayed until reloading the group chat report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d4c7fc63-f48d-4fd0-b7c2-d4784505be0c

https://github.com/Expensify/App/assets/93399543/223df2f6-9633-45aa-a4b7-de61bf08cd36

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688291017734929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169e2e0f2d4b094b8</li>
        <li>Upwork Job ID: 1678383611648274432</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-07-10 12:40
Can reproduce

**Comment by snwork89** [comment] 2023-07-11 10:24
i looked into issue defined here  and i found that "/api?command=OpenReport" api is used while creating a new group and also to get existing group details and according to that response group details are rendering. when we're calling openreport api while creating a new group, response from that api is wrong ,it is only returning group member details that are logged in with email only(for ref. look into onyxData array with "key: personalDetailsList").without changing backend code one possible solution is to call openreport after new group created one more time with same groupId(reportId)

**Comment by snwork89** [comment] 2023-07-11 10:28
Contributor details
Your Expensify account email: snwork89@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01576033752dd3eb7a

i already sent proposal before!!

**Comment by ishpaul777** [comment] 2023-07-11 14:47
## Proposal

### Problem
Web - Sometimes, after creating a new group with email and phone number as participants, only participants with email are displayed in the group chat report 

### Root cause 
After creating a group, only particpants with email is received from backend and set as the state. 
![image](https://github.com/Expensify/App/assets/104348397/96003114-7b96-4955-9a7e-74885dab63bc).

when the following is visibility change, it set the state including the phone number participants, Most probably it is backend issue.
Visibility.onVisibilityChange(() => {
            // If the report is not fully visible (AKA on small screen devices and LHR is open) or the report is optimistic (AKA not yet created)
            // we don't need to call openReport
            if (!getIsReportFullyVisible(this.props.isFocused) || this.props.report.isOptimisticReport) {
                return;
            }
            Report.openReport(this.props.report.reportID);
        });

### Changes
This could be handled on Client-side if we force fetch report on component mount

```JSX
 componentDidMount() {
        this.unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            // If the report is not fully visible (AKA on small screen devices and LHR is open) or the report is optimistic (AKA not yet created)
            // we don't need to call openReport
            if (!getIsReportFullyVisible(this.props.isFocused) || this.props.report.isOptimisticReport) {
                return;
            }
            Report.openReport(this.props.report.reportID);
        });

        // this.fetchReportIfNeeded();
        Report.openReport(this.props.report.reportID);
        ComposerActions.setShouldShowComposeInput(true);
    }
```
### Alternative
Investigate the root cause in backend.

**Comment by sobitneupane** [comment] 2023-07-13 07:55
@snwork89 has rightly pointed out the issue [here](https://github.com/Expensify/App/issues/22138#issuecomment-1630567737). 

> when we're calling openreport api while creating a new group, response from that api is wrong ,it is only returning group member details that are logged in with email only

Looks like the issue exists on backend. I can create a group without any issue offline. 

@anmurali Can we add an internal engineer. Looks like the issue is in api response.

**Comment by anmurali** [comment] 2023-07-19 23:03
@MonilBhavsar - any updates?

**Comment by MonilBhavsar** [comment] 2023-07-20 06:26
Sorry, no. Getting to this today

**Comment by MonilBhavsar** [comment] 2023-07-24 12:06
Working on the PR

**Comment by MonilBhavsar** [comment] 2023-08-01 06:05
This was deployed last week!

**Comment by MonilBhavsar** [comment] 2023-08-01 06:18
It was internal, so we need to pay the reporter and add regression tests @tranvantoan-qn

Tests can be - 
1. Click on `+` button > 'Group chat'
2. Add two users with email and a user with phone number login
3. Ensure that group is created and ensure the welcome message has all three participants

**Comment by anmurali** [comment] 2023-08-09 22:17
@tranvantoan-qn - Offer is [here](https://www.upwork.com/nx/wm/offer/26038049)

**Comment by tranvantoan-qn** [comment] 2023-08-09 22:21
Thank you, I've accepted the offer

**Comment by MonilBhavsar** [comment] 2023-08-14 12:13
Issue for QA created here https://github.com/Expensify/Expensify/issues/307952

**Comment by MonilBhavsar** [comment] 2023-08-14 12:14
Opened issue to add tests. We can close this now

**Closed by MonilBhavsar** 2023-08-14 12:14 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
