### ISSUE TITLE
[$500] Distance - Unable to select current location. Field return to old result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31790] opened 2023-11-23 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch App
2. Navigate FAB > Request Money > Distance
3. Select San Diego for Start and Finish
4. Go to phone settings and Disable the location settings for New Expensify
5. REturn to App: FAB > Request Money > Distance > Select San Diego for Start and Finish
6. Tap on Location popup 'While using App"
7. Tap on start and select “Use my current location”

## Expected Result:
Verify the map is automatically centered to your current location and start field is show your location

## Actual Result:
The start field isn't show your location
Issue occurred for all environments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b395079f-8708-4659-ac74-d5edcf7a6fd2

![Bug6288682_1700753957963!start](https://github.com/Expensify/App/assets/78819774/f4b4ca91-bc3e-4f7e-a5d1-899c62596081)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01917b0f634d24992f</li>
        <li>Upwork Job ID: 1727747268870176768</li>
        <li>Last Price Increase: 2023-11-23</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-23 18:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to select current location. Field return to old result
### What is the root cause of that problem?
When current location is selected `waypoint` is missing name field (`undefined`) so the address inserted before is displayed in the location field.
### What changes do you think we should make in order to solve the problem?

We should provide the name field for `waypoint` 
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-24 00:32
Dupe: https://github.com/Expensify/App/issues/30837

**Comment by anmurali** [comment] 2023-11-29 04:47
Closing based on https://github.com/Expensify/App/issues/31790#issuecomment-1825021395

**Closed by anmurali** 2023-11-29 04:47 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
