### ISSUE TITLE
Url isn't correct when you navigate to concierge from assistance page - reported by @Puneet-here 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11133] opened 2022-09-20 05:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to workspace
 2. Tap on get assistance (top right corner, first option)
 3. "Chat with concierge"
 4. Check the url
 5. Reload the page

## Expected Result:
The url should be of concierge chat and on reload it should not workspace page

## Actual Result:
The url is of the workspace and on reload it opens the workspace again

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/191175503-b0797a95-a54c-40c6-be05-f147e4c1a73b.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661530422131889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-10-19 02:09
Getting to this tomorrow

**Comment by Puneet-here** [comment] 2022-10-19 05:27
Hi @MitchExpensify, all the other issues like this are being tracked at https://github.com/Expensify/App/issues/11111 because there's a highly chance that they all will be fixed by one solution. We can add this there and close it.

**Comment by MitchExpensify** [comment] 2022-10-19 17:13
Cool, this isn't reproducible on desktop web for what it is worth

**Comment by MitchExpensify** [comment] 2022-10-19 22:19
This is not reproducible on mobile either for me - Closing

**Closed by MitchExpensify** 2022-10-19 22:19 UTC
Labels: Daily, Needs Reproduction, Bug
