### ISSUE TITLE
Android - group - In group chat, creating split expense shows unexpected error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50091] opened 2024-10-02 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app (use gmail account)
2. Create a group chat with 2 users
3. Create a manual split expense

## Expected Result:
In group chat, creating split expense must not show unexpected error

## Actual Result:
As gmail user, in group chat, creating split expense shows unexpected error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/317a342d-b118-4ad1-947b-47ef56d00d2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-02 17:41
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-10-08 00:23
@lanitochka17 in these cases, it's super helpful to have the email address of the tester and an indication of the time/date when it happened to narrow the search. I've found it, but it took me longer than necessary if I had those details. 

Participants for reference: 

<img width="298" alt="image" src="https://github.com/user-attachments/assets/cb4ed5c6-dd4c-4c45-8840-10766e558534">

```
Throw ExpException - 59714ae343639b41a22589f6b07edad1 ~~ message: '400 Invalid participant in split JSON' exceptionMessage: 'Auth CreateIOUSplit returned an error' exceptionFile: '/git/releases/expensify.com/8036ef0/lib/Auth.php' exceptionLine: '132' exceptionCode: '400'
```

[RequestID](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228cc5e92298186ed7-BOM%22)+AND+timestamp:[2024-10-02T15:01:22.510Z+TO+2024-10-02T17:01:22.510Z]&index=logs_expensify-030529)


...which looks like it's throwing [here](https://github.com/Expensify/Auth/blob/246d1313ab4a50ac578da1f060f8274317ccbea6/auth/lib/Transaction.cpp#L3938-L3941). 

.. looking at the SplitBill command request, it seems like we might have an empty email for accountID `14909571`. 

```
Processing 'SplitBill' for 'expensify.com' from '49.37.221.212' ~~ initialReferer: '<REDACTED>' browserGUID: '66fd6e11351ac' command: 'SplitBill' reportID: '1586659735003557' amount: '87797900' splits: '[{"email":"jaihanumanblog+aohdbdbsns@gmail.com","accountID":18418840,"amount":29265966,"taxAmount":0},{"email":"","accountID":14909571,"isOptimisticAccount":false,"amount":29265967,"iouReportID":"6052722910679159","chatReportID":"1368027836275448","transactionID":"7447705160371163702","reportActionID":"5478681928244891158","createdChatReportActionID":"4179653200119164763","createdIOUReportActionID":"4779679985590943370","reportPreviewReportActionID":"8388445612708174433","transactionThreadReportID":"4177248923736814","createdReportActionIDForThread":"5697035918013480567","taxAmount":0},{"email":"jaihanumanblog@gmail.com","accountID":15075387,"isOptimisticAccount":false,"amount":29265967,"iouReportID":"1764700554582682","chatReportID":"6571789036668188","transactionID":"5351388876721267404","reportActionID":"4447484852141798124","createdChatReportActionID":"4585901085599248401","createdIOUReportActionID":"1052459271737372515","reportPreviewReportActionID":"1246776162341504802","transactionThreadReportID":"8595370910338935","createdReportActionIDForThread":"2042612708939164669","taxAmount":0}]' currency: 'INR' comment: '' category: '' merchant: '(none)' created: '2024-10-02' tag: '' billable: 'false' transactionID: '3783263752286064644' reportActionID: '2538530263361927211' chatType: 'group' taxCode: '' taxAmount: '0' pusherSocketID: '776705.10521043' authToken: '<REDACTED>' referer: 'ecash' platform: 'android' api_setCookie: 'false' email: 'jaihanumanblog+aohdbdbsns@gmail.com' isFromDevEnv: 'false' appversion: '9.0.43-1' clientUpdateID: '2194246977' partnerName: 'expensify.com' HTTP_CF_BOT_SCORE: '99' HTTP_CF_JA3_HASH: 'f79b6bad2ad0641e1921aef10262856b'
```

Pulling those out of the above for ease of viewing: 

`{"email":"jaihanumanblog+aohdbdbsns@gmail.com","accountID":18418840,"`
`{"email":"","accountID":14909571,"`
`{"email":"jaihanumanblog@gmail.com","accountID":15075387`

As for the why? I'm not sure. @youssef-lr might know.

**Comment by trjExpensify** [comment] 2024-10-11 15:04
Awaiting input from, @youssef-lr.

**Comment by youssef-lr** [comment] 2024-10-11 15:19
Dupe of https://github.com/Expensify/App/issues/30140, should be fixed once account creation is moved to Auth, cc @neil-marcellini

**Closed by youssef-lr** 2024-10-11 15:19 UTC
Labels: Daily, Bug
