### ISSUE TITLE
[$2000] Web - Chat - Gaps are displayed in the chat conversation on high traffic account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8661] opened 2022-04-17 02:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. https://staging.new.expensify.com
2. Log in with High Traffic Account (applausetester+0901abb@applause.expensifail.com)
3. Search for the user more that a 100 messages including pictures and requested money (applausetester+0709abb@applause.expensifail.com)
4. Scroll messages to the top

## Expected Result:
No gaps are displayed in the chat conversation

## Actual Result:
Gaps are displayed in the chat conversation

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![emptyChat](https://user-images.githubusercontent.com/93399543/163697407-e18c4d71-8903-4aa7-9013-0b7be20798ec.png)
![speed test](https://user-images.githubusercontent.com/93399543/163697408-b04ab04a-e8c9-4cb5-bd0a-c230ae2d120c.jpg)

https://user-images.githubusercontent.com/93399543/163697414-8947c798-b2bc-4ec1-b413-ceade6ed8749.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause (Exploratory)

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2022-04-19 20:58
Hmm i cannot reproduce this. Looks like maybe a performance issue. Either way since its front end i'll begin by applying external label to get more eyes to test and diagnose this.

**Comment by laurenreidexpensify** [comment] 2022-04-22 06:59
https://www.upwork.com/jobs/~011e2392845cc20241

**Comment by mvtglobally** [comment] 2022-04-26 04:50
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment] 2022-05-03 11:02
Increasing to $500

**Comment by Santhosh-Sellavel** [comment] 2022-05-03 12:17
> Issue not reproducible during KI retests. (First week)
> 

@laurenreidexpensify

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 20:27
Able to reproduce this one,

Uploading Screen Recording 2022-05-17 at 1.55.25 AM.mov…

**Comment by laurenreidexpensify** [comment] 2022-05-17 06:15
Nice thanks @Santhosh-Sellavel. Price doubled

**Comment by laurenreidexpensify** [comment] 2022-05-26 13:55
Price Doubled

**Comment by Santhosh-Sellavel** [comment] 2022-05-26 14:52
@chiragsalian

I believe this might be related/ maybe a duplicate of https://github.com/Expensify/App/issues/7860, can we add a hold label to this issue.

cc: @laurenreidexpensify

**Comment by chiragsalian** [comment] 2022-05-26 18:14
Good catch, yeah it could be related because of item offset and sizeMap. I'll add the HOLD.

**Comment by Santhosh-Sellavel** [comment] 2022-07-10 19:18
Yes on hold

**Comment by chiragsalian** [comment] 2022-08-15 22:25
Still on HOLD, demoting to monthly until its off HOLD.

**Comment by mvtglobally** [comment] 2022-08-23 04:05
Issue not reproducible during KI retests. (First week)

**Comment by Santhosh-Sellavel** [comment] 2022-10-18 23:59
On Hold

**Comment by chiragsalian** [comment] 2022-10-19 18:41
Yes, I think it's still on HOLD for https://github.com/Expensify/App/issues/7860. Looks like a big project but we feel like it would solve the problem here with proper code vs us doing some hacky workarounds until that goes live.

**Comment by mvtglobally** [comment] 2022-11-16 02:08
Issue not reproducible during KI retests. (Second week)

**Comment by laurenreidexpensify** [comment] 2022-11-18 15:06
@chiragsalian what do you think about closing this given it's not showed up after 2 weeks of KI retests?

**Comment by chiragsalian** [comment] 2022-11-22 18:54
Yeah closing it sounds best. Feel free to reopen if it reoccurs.

**Comment by deetergp** [comment] 2022-11-30 18:36
It looks like this is back, going to re-open this one and close the dupe that @Santhosh-Sellavel pointed out.

**Comment by JalalMitali** [comment] 2022-11-30 18:45
https://github.com/Expensify/App/issues/13114#issuecomment-1331330507

**Comment by JalalMitali** [comment] 2022-11-30 20:53
**Proposal :** 
add the **disableVirtualization** prop to the **InvertedList** that is rendering report actions - messages.
keep in mind that : 
_Virtualization provides significant performance and memory optimizations, but fully unmounts react instances that are outside of the render window_ ( [reactnative.dev](https://reactnative.dev/docs/virtualizedlist))

**Comment by JalalMitali** [comment] 2022-11-30 20:57
@Santhosh-Sellavel @deetergp please check my proposal and I am sorry I couldn't attach a video Github keeps saying file is too big ( 10 seconds vid only )!

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 21:30
Disabling virtualisation is not recommended.

**Comment by laurenreidexpensify** [comment] 2022-12-05 12:15
confirming some next steps internally [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1670242488492739)

**Comment by chiragsalian** [comment] 2022-12-06 17:58
Closing issue since the original issue for this is [here](https://github.com/Expensify/App/issues/7860).

**Closed by chiragsalian** 2022-12-06 17:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
