### ISSUE TITLE
[$1000] Web - Inconsistency: Frist cell of magic code input field is marked green on Contact methods section and Sign in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22190] opened 2023-07-04 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on "profile' avatar
2. Click on 'Profile' link
3. Click on 'Contact methods' link
4. Click on 'New Contact method' button
5. Enter email & click on 'Add' button
6. Open the newly added email
7. Click on 'Verify' button

## Expected Result:
First cell magic code input field shouldn't be marked with green (i.e. they should be all red)

## Actual Result:
 First cell magic code input field is marked with green

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (14)](https://github.com/Expensify/App/assets/93399543/128ee4e7-8cb6-459e-b144-8880f8eaa9f4)

https://github.com/Expensify/App/assets/93399543/752eac2c-6b31-4632-b480-ba6d995864d6

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a492908c81284fcd</li>
        <li>Upwork Job ID: 1676401283656871936</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-07-05 01:22
I am able to reproduce and agree that the behaviour should be the same as the sign in page (i.e. all cells are red after clicking the action button)

![2023-07-05_13-20-51 (1)](https://github.com/Expensify/App/assets/42940078/6a421a1c-ced0-468b-8b46-9937480aeaf2)

**Comment by ygshbht** [comment] 2023-07-05 04:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we're trying to solve is the inconsistency in user experience where the first cell of the magic code input field remains highlighted (or focused) even when an error occurs. This happens in the 'Contact methods' section and during 'Sign in'. The expected behavior is that the input field should lose focus (blur) when an error is encountered.

### What is the root cause of that problem?
The root cause of this issue lies in how the input field retains focus even when an error is present. Currently, the 'MagicCodeInput' and 'BaseValidateCodeForm' components do not incorporate functionality to blur the input field when there's an error.

### What changes do you think we should make in order to solve the problem?
To address this issue, we need to implement functionality to blur the input field when an error is encountered. This can be achieved by adding a 'useEffect' hook in the 'MagicCodeInput' component. The hook will monitor the 'hasError' and 'errors' props, and call the 'blurMagicCodeInput' function when an error is detected:
```
useEffect(()=>{
    if (props.hasError){
        blurMagicCodeInput();
    }
},[props.hasError, props.errors])
```
In the 'BaseValidateCodeForm' component, we can pass the 'hasError' and 'errors' props to 'MagicCodeInput' or modify the existing props:
```
<MagicCodeInput
    autoComplete={props.autoComplete}
    ref={inputValidateCodeRef}
    label={props.translate('common.magicCode')}
    name="validateCode"
    value={validateCode}
    onChangeText={onTextInput}
    errorText={formError.validateCode ? props.translate(formError.validateCode) : ErrorUtils.getLatestErrorMessage(props.account)}
    hasError={formError && Object.keys(formError).length !== 0} /* new prop */
    errors={formError} /* new prop */
    onFulfill={validateAndSubmitForm}
    autoFocus
    shouldSubmitOnComplete={false}
/>
```
This solution provides a more consistent user experience by ensuring that the focus is lost from the input field when an error is present. The code can further be refactored to improve generality and maintainability.

**Comment by ygshbht** [comment] 2023-07-05 05:22
I apologize for any confusion. Let me clarify. The code you're referencing made changes in the file located at  [#"src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js"](https://github.com/Expensify/App/blob/main/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js). However, I'm proposing changes to a different file, specifically ["src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js"](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js). I understand that the similarity in file names can cause confusion, but they are two distinct files used in different scenarios within the application. Please let me know if you have any further questions.

**Comment by ygshbht** [comment] 2023-07-05 05:27
######On a side note (please feel free to ignore this for now), I observed that the input doesn't display an error when "Verify" is clicked with all six fields populated. This could be rectified by making some changes in the "MagicCodeInput" component. Here's a snippet:
```
<MagicCodeInput
    ...
    onChangeText={(...args) => {
        User.clearContactMethodErrors(props.contactMethod, 'validateLogin');
        onTextInput(...args)
    }}
    hasError={(formError && Object.keys(formError).length !== 0) || 
        Object.keys(ErrorUtils.getLatestErrorField(loginData, 'validateLogin')).length >0
    }
    ...
/>
```

**Comment by alitoshmatov** [comment] 2023-07-05 08:20
Duplicate of this - https://github.com/Expensify/App/issues/20416

**Comment by Ali-ch88** [comment] 2023-07-05 08:55
**Proposal**

1-**Please re-state the problem that we are trying to solve in this issue.**

Web - Inconsistency: Frist cell of magic code input field is marked green on Contact methods section and Sign in #22190

2-**What is the root cause of that problem?**

      When we click on the verify button, the currently selected input is focused(),
      so the styling for errors is not applied to it due to the current logic. So, the currently focused input will remain green underlined.

3-**What changes do you think we should make in order to solve the problem?**
![tt](https://github.com/Expensify/App/assets/61835503/cb2ec13c-1a39-40c8-be9b-509d716cadc7)

     We can make the currently selected input field Blur() when we submit our verification code. In that way, the error styles will be applied on it also,

4-**What alternative solutions did you explore? (Optional)**
NA

**Comment by Ali-ch88** [comment] 2023-07-05 09:00
Hi, I have the solution for this issue and also submitted the proposal above. So should I fix this issue and create the PR for this issue?

**Comment by sophiepintoraetz** [comment] 2023-07-06 03:16
Thanks @alitoshmatov for clocking the dupe! @Ali-ch88 - head over to #20416 with your proposal, the only risk is that the issue it's held on may fix the error so there may be some effort spent unnecessarily.

**Closed by sophiepintoraetz** 2023-07-06 03:16 UTC
Labels: External, Daily, Help Wanted, Bug
