### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Approver - In edit approval workflow, in offline approver selected is not greyed out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50477] opened 2024-10-08 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition:
1. Launch app
2. Tap profile icon -- workspaces -- workspace
3. Tap more features -- enable workflows -- enable add approval
4. Go offline
5. Tap approver - select a member - save

## Expected Result:
In edit approval workflow, in offline approver selected must be greyed out.

## Actual Result:
In edit approval workflow, in offline approver selected is not greyed out.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6f5d6065-22a3-4a83-8d11-32a640e5f860

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844825382815760064</li>
        <li>Upwork Job ID: 1844825382815760064</li>
        <li>Last Price Increase: 2024-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104447976</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment] 2024-10-08 19:36
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment] 2024-10-09 09:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In edit approval workflow, in offline approver selected is not greyed out

### What is the root cause of that problem?

We haven't handled the case for greying out the edit approval workflow yet

### What changes do you think we should make in order to solve the problem?

We need to wrap the component rendering `members` and `approver` with `OfflineWithFeedback`, something like this
```diff
const approvalWorkflowPendingUpdate = approvalWorkflow.pendingAction;
// .src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L136
+                        <OfflineWithFeedback pendingAction={approvalWorkflowPendingUpdate>
                            <MenuItemWithTopDescription
                             ....
                            />
+                        </OfflineWithFeedback>
```
```diff
// .src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L151
+                        <OfflineWithFeedback pendingAction={approvalWorkflowPendingUpdate}>
                            <MenuItemWithTopDescription
                             ....
                            />
+                        </OfflineWithFeedback>
```

```diff
// .src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L198
+                        <OfflineWithFeedback pendingAction={approvalWorkflowPendingUpdate}>
                            <MenuItemWithTopDescription
                             ....
                            />
+                        </OfflineWithFeedback>
```

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-10-11 08:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In edit approval workflow, in offline approver selected is not greyed out.

### What is the root cause of that problem?
We don't add `OfflineWithFeedback` here

https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L137-L139
### What changes do you think we should make in order to solve the problem?
1. When we update the workflow, we can update the `pendingFields` of each updated employee

```
updatedEmployeeList[approver.email] = {
    email: approver.email,
    forwardsTo,
    pendingAction,
    pendingFields: {
        forwardsTo: pendingAction,
    },
};
```
https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/libs/WorkflowUtils.ts#L233-L237

```
updatedEmployeeList[email] = {
    ...(updatedEmployeeList[email] ? updatedEmployeeList[email] : {email}),
    submitsTo,
    pendingAction,
    pendingFields: {
        submitsTo: pendingAction,
    },
};
```
https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/libs/WorkflowUtils.ts#L249-L253

2. Then we can return `pendingFields` here


https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/libs/WorkflowUtils.ts#L124-L127


3. We will create a function to get the `pendingAction` for each approver. For the first approver, it's pending if any member in the workflow has `pendingFields.submitsTo`. For each other approver, it's pending if the previous approver has `pendingFields.forwardsTo` because if this approver is updated the `forwardsTo` of the previous approver will be updated

```
const getApprovalPendingAction = useCallback(
    (index: number) => {
        let pendingAction: PendingAction | undefined;
        if (index === 0) {
            approvalWorkflow?.members?.forEach((member) => {
                pendingAction = pendingAction ?? member.pendingFields?.submitsTo;
            });
            return pendingAction;
        }
        const previousApprover = approvalWorkflow?.approvers.at(index - 1);
        const previousMember = approvalWorkflow?.members?.find((member) => member?.email === previousApprover?.email);
        return previousMember?.pendingFields?.forwardsTo;
    },
    [approvalWorkflow],
);
```

```
<OfflineWithFeedback pendingAction={getApprovalPendingAction(approverIndex)}>
```
https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L137-L139

### What alternative solutions did you explore? (Optional)

We can wrap `OfflineWithFeedback` for each approver with `pendingAction` is `approvalWorkflow.pendingAction`

https://github.com/Expensify/App/blob/285bde8073f84dad0ca6d63ef6ec251b10e52882/src/pages/workspace/workflows/approvals/ApprovalWorkflowEditor.tsx#L137-L139

**Comment by strepanier03** [comment] 2024-10-11 19:41
Not 100% sure about the Project since there's a shift internally and I don't think things are updated fully. It might move but for now we can work on this.

**Comment by eh2077** [comment] 2024-10-14 13:50
@nkdengineer Thanks for your proposal. Your alternative solution looks simpler and it's same as the main solution of the first proposal. Is there any drawback of the alternative solution? Or what're the advantages of your main solution?

**Comment by nkdengineer** [comment] 2024-10-14 13:56
@eh2077 With my main solution, only the changed approver will be grey out instead of all approvers as my alternative solution.

**Comment by eh2077** [comment] 2024-10-14 14:38
I think this shouldn't be a recent bug but a missing case we want to polish.

@nkdengineer 's [proposal](https://github.com/Expensify/App/issues/50477#issuecomment-2406923945) looks good to me. 

🎀👀🎀 C+ reviewed

**Comment by huult** [comment] 2024-10-14 14:42
@eh2077 Could you review my proposal?

**Comment by huult** [comment] 2024-10-14 15:00
@eh2077 , My proposal provides two solutions:

- Main solution: This will gray out all `members` and `approver`, similar to the alternative solution in the other proposal.
- Alternative solution: This will gray out only the field that was changed, similar to the main solution in the other proposal. However, my proposal provides a simpler code example and also resolves the issue.

and We need to check which of the two solutions to apply to fix this issue. If we gray out only the field that was changed, it won't be consistent with the previous behavior, as it grayed out two fields. We need to confirm this.

**Comment by huult** [comment] 2024-10-15 00:41
@eh2077 , I believe both proposals suggest the same solution, differing only in their implementation approach: my proposal checks for approver pending status in the persistent request, while the other proposal sets the pending action in the parameters. Since my proposal came first, I believe the other proposal does not align with the following point from CONTRIBUTING.md
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

Once again, I apologize if I'm wrong.

**Comment by eh2077** [comment] 2024-10-15 01:17
@huult Thanks for your comments! I did check your proposal
- The main solution to gray out all approvers are not ideal
- While the alternative solution fixes the effect, I think using low level API `PersistedRequests.getAll()` to extract pending actions isn't the best practice to solve offline UX related issues. 

 I totally feel your point about competing proposals. I think your proposal is very close to succeed - you included both a simple / straightforward method and a more thoughtful one. If I could give you an advice, I think you can explore the codebase for similar patterns / practices to compare with the solution you come up. Hope it helps, thanks.

**Comment by huult** [comment] 2024-10-15 01:39
@eh2077 , Thank you for your feedback and advice.

Would it be alright if I asked you a question?

Regarding the solution, is my proposal still correct? Is my proposal not selected because the code example change isn’t best practice and cannot be updated during the PR phase?

**Comment by flodnv** [comment] 2024-10-15 14:28
@tgolen I believe you've recently shipped this feature, so I'm reassigning this to you

**Comment by eh2077** [comment] 2024-10-16 14:21
> Is my proposal not selected because the code example change isn’t best practice and cannot be updated during the PR phase?

@huult I voted for the other proposal because I think their method is better. I could also be wrong. So, let's wait for @tgolen 's review.

**Comment by tgolen** [comment] 2024-10-16 15:32
I agree with @eh2077's reasoning for the proposal that was accepted.

**Comment by strepanier03** [comment] 2024-11-05 23:39
# HOLD FOR CHECKLIST

### Payment Summary

- [x] $250 - @nkdengineer PAID via Upwork ([contract](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/38757446))
- [ ] $250 - @eh2077 via New Expensify manual request

**Comment by strepanier03** [comment] 2024-11-05 23:40
@nkdengineer - I have paid and closed the contract for you in Upwork, thank you for continuing to be part of our community. 

@eh2077 the payment summary is ready but on hold. Once you do the checklist I'll finish up my bits and update it. I'll check in again later today.

**Comment by eh2077** [comment] 2024-11-07 16:23
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46798
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46798/files#r1832973798
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_No, as we have unit tests to cover the change._**

**Comment by strepanier03** [comment] 2024-11-07 17:53
Thanks @eh2077 - The payment summary is ready for you [here](https://github.com/Expensify/App/issues/50477#issuecomment-2458416894), feel free to request payment :)

**Closed by strepanier03** 2024-11-07 17:53 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by eh2077** [comment] 2024-11-08 01:06
Requested payment in NewDot
