### ISSUE TITLE
[HOLD C+ Payment] [$1000] Slow animation on sign in input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23137] opened 2023-07-18 21:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Focus the the sign-in input
3. Click somewhere else
## Expected Result: 
Expected that on Safari, the animation of labels is similar to speed as on Chrome.
## Actual Result: 
Slow animation on Safari

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS /Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:**  needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/77d83ffe-2114-4f0e-8ea1-da7df7e2e346

**Expensify/Expensify Issue URL:**
**Issue reported by:** @spacexdragonpie
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689595055183879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177b62cd207274e58</li>
        <li>Upwork Job ID: 1682027803637739520</li>
        <li>Last Price Increase: 2023-07-20</li>
<li>Automatic offers: </li>
<ul>
<li>dantastisk | Contributor | 25888135</li>
<li>spacexdragonpie | Reporter | 25888136</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-20 14:00
Was able to recreate this, so getting eyes on it

**Comment by b4s36t4** [comment] 2023-07-20 15:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Slow animation on sign in input
### What is the root cause of that problem?

RCA for this issue is with the background SVG we're rendering and the position of it.

If we observe the svg that is on background it is covered into whole screen whereas it should be covered fully into the scrollview only.

Not sure why having an SVG into background would interrupt animations only in safari :)

### What changes do you think we should make in order to solve the problem?

We would need to add `style` prop here https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/signin/SignInPageLayout/BackgroundImage/index.js#L25
and pass `styles.signInBackgroundDesktop` here https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/signin/SignInPageLayout/index.js#L90
would solve the issue.


### What alternative solutions did you explore? (Optional)
NA, I feel this is the only solution to this  issue.
[uu.webm](https://github.com/Expensify/App/assets/59088937/802938d7-419d-4c21-98ff-4bdfaf17a3ad)

**Comment by andreyazevedo** [comment] 2023-07-20 18:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Slow animations on the login page in the Safari web browser.

### What is the root cause of that problem?

Unoptimized SVG file being used as a background on the page.
filename: home-background--desktop.svg

### What changes do you think we should make in order to solve the problem?

 Optimize SVG file. 


https://github.com/Expensify/App/assets/4293383/2816d280-de85-4ec3-9ca8-6e73b830186e



### What alternative solutions did you explore? (Optional)

Not applicable.

**Comment by andreyazevedo** [comment] 2023-07-21 13:25
## Proposal
[Updated](https://github.com/Expensify/App/issues/23137#issuecomment-1644369733)

**Comment by CortneyOfstad** [comment] 2023-07-21 15:28
@rushatgabhane any thoughts on the proposals above?

**Comment by dantastisk** [comment] 2023-07-22 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Slow/Laggy animations on sign in page in Safari.

### What is the root cause of that problem?

home-background--desktop.svg does not have position: absolute causing a ton of unnecessary recalculations.

### What changes do you think we should make in order to solve the problem?


Styles exist for both mobile and desktop in styles.js:

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/styles/styles.js#L1136-L1148

However they are only passed to the mobile version:

src/pages/signin/SignInPageLayout/index.js:

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/signin/SignInPageLayout/index.js#L90-L94
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/signin/SignInPageLayout/index.js#L125-L130

src/pages/signin/SignInPageLayout/BackgroundImage/index.js:

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/signin/SignInPageLayout/BackgroundImage/index.js#L18C1-L29

Since the styles are the same for both platforms, I suggest merging them into one "signInBackground" in styles.js, getting rid of the style prop passed from SignInPageLayout to BackgroundImage and importing it directly from styles here. 

https://github.com/Expensify/App/assets/48072523/05d4881d-bb38-4dd0-bf10-0fda4cf5257a

**Comment by dantastisk** [comment] 2023-07-22 13:31
Contributor details
Your Expensify account email: daniel.s.brinkmann@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0156e09e08684e6201

**Comment by CortneyOfstad** [comment] 2023-07-24 13:47
@rushatgabhane Any thoughts on the proposals?

**Comment by CortneyOfstad** [comment] 2023-07-25 17:46
@rushatgabhane some more proposals to review above

**Comment by rushatgabhane** [comment] 2023-07-25 19:25
I feel like we don't have the root cause for this issue

**Comment by b4s36t4** [comment] 2023-07-25 19:29
As far as I know I have seen this issue not happening on mobile width because of the styles and the area background image is covered. But in desktop screen svg is covered with the whole screen including the non-scroll area we have at left side. And the width for the svg we have 2000px which covering more than the screen in some situations.. And I observed that there is a style object written for the desktop svg but not being used, adding it to the prop will solve the issue.

**Comment by rushatgabhane** [comment] 2023-07-25 19:31
> issue not happening on mobile width

Ohh that hints to the root cause. Thanks!

**Comment by rushatgabhane** [comment] 2023-07-25 19:44
@b4s36t4 @dantastisk thanks for your proposal. The root cause is indeed hinting to the position not being `absolute`. But why is that? Why are there `a ton of unnecessary recalculations` when position is not `absolute`?

**Comment by rushatgabhane** [comment] 2023-07-25 19:48
@andreyazevedo thanks for your proposal but it's only a small optimization. It's a different issue and you can raise a proposal for it on slack.

The root cause for this issue lies in position not being `absolute`, and causing unnecessary calculations.

**Comment by dantastisk** [comment] 2023-07-26 09:33
@rushatgabhane some of the animations cause the document flow to change and the browser will have to calculate potential changes in position/height/width etc. for all possibly affected elements. When the element is given `position: absolute` the browser knows that any changes to the element and its children can only affect itself and its children, thus saving `a ton of unnecessary recalculations`.

I am not 100% sure why we only see the lagging in safari, but I believe this is due to implementation differences in the browsers rendering engines. I have had multiple similar cases before where I only saw lag in safari. Maybe safari is simply worse at predicting which elements are affected by changes to the document flow?

Alternatively we could change the lottie animation to only use animations that don't alter the document flow like `transform`. Most of the animations are already done using `transform`, but there are some expections like the one highlighted in my attached video where display alternates between `block` and `none`. The same effect could be achieved using `opacity`, which has a lot better rendering performance as it doesn't affect the positioning of other elements.

I don't have any experience with Lottie so I don't know if this is feasible, and I would assess that changing it by hand is not an option as it would require the assistance of an engineer every time the animation is updated.

Here are some useful articles on the subject:
- [Rendering Performance](https://web.dev/rendering-performance/)
- [How to create high-performance CSS animations](https://web.dev/animations-guide/)

https://github.com/Expensify/App/assets/48072523/f7d9aacb-74d4-4580-b23f-28deed7fc30d

**Comment by dantastisk** [comment] 2023-07-26 09:39
@rushatgabhane @b4s36t4 I don't believe the width on mobile has anything do to with the issue. The only difference here is that `position: absolute` does in fact get applied on mobile.

**Comment by b4s36t4** [comment] 2023-07-26 09:40
Yes that's what it means.

**Comment by CortneyOfstad** [comment] 2023-07-28 13:10
@rushatgabhane where are we at? Any proposals looking good?

**Comment by rushatgabhane** [comment] 2023-07-28 13:22
the solution was first given by @b4s36t4 

But @dantastisk has the best explanation of the root cause https://github.com/Expensify/App/issues/23137#issuecomment-1646584710

C+ reviewed

**Comment by CortneyOfstad** [comment] 2023-07-28 16:04
Thanks! Have we decided on which one will be hired as the contributor?

**Comment by b4s36t4** [comment] 2023-07-28 19:30
@rushatgabhane which one of us getting assigned this issue?

**Comment by rushatgabhane** [comment] 2023-07-30 11:11
Sorry for being so unclear 😅

**Comment by rushatgabhane** [comment] 2023-07-30 11:12
i recommend @dantastisk's solution

c+ reviewed https://github.com/Expensify/App/issues/23137#issuecomment-1646584710
🎀 👀 🎀

**Comment by dantastisk** [comment] 2023-07-30 11:16
I will get on it first thing tomorrow!

**Comment by CortneyOfstad** [comment] 2023-07-31 13:05
Sounds good — thanks @dantastisk!

**Comment by dantastisk** [comment] 2023-08-01 09:49
I am still awaiting official assignment on this one 😊

**Comment by CortneyOfstad** [comment] 2023-08-01 19:54
I'm heading OoO until 8/14, so going to re-assign this for BZ in the meantime to keep eyes on it 👍

**Comment by rushatgabhane** [comment] 2023-08-01 20:35
we missed @joelbettner's approval for https://github.com/Expensify/App/issues/23137#issuecomment-1657111161

**Comment by rushatgabhane** [comment] 2023-08-02 04:46
@CortneyOfstad could you please unassign @dantastisk, because we still need to get approval from @joelbettner

**Comment by sophiepintoraetz** [comment] 2023-08-07 02:34
Bumping @joelbettner

**Comment by joelbettner** [comment] 2023-08-07 18:49
The proposal by @dantastisk looks good!

**Comment by dantastisk** [comment] 2023-08-08 08:01
PR ready for review: https://github.com/Expensify/App/pull/24254

**Comment by rushatgabhane** [comment] 2023-08-10 22:12
merged within 3

**Comment by CortneyOfstad** [comment] 2023-08-16 13:54
Thank you for the context @rushatgabhane!

**Comment by CortneyOfstad** [comment] 2023-08-16 13:55
Also @sophiepintoraetz — I can take this back now that I'm back from OoO — slowly making my way through all the GHs 😂 

Thanks for holding down the fort while I was out!

**Comment by CortneyOfstad** [comment] 2023-08-23 13:53
@rushatgabhane Any update on the checklist above? TIA!

**Comment by CortneyOfstad** [comment] 2023-08-24 13:20
Sounds good @rushatgabhane — payments have been confirmed and contracts closed for @spacexdragonpie and @dantastisk so they are all set!

**Comment by CortneyOfstad** [comment] 2023-08-28 11:27
@rushatgabhane Just checking to see where we're at — thanks!

**Comment by CortneyOfstad** [comment] 2023-08-31 13:10
Bump @rushatgabhane ^^^

**Comment by CortneyOfstad** [comment] 2023-09-01 14:59
@rushatgabhane Okay, if you need me to make a bump internally, just let me know 👍

**Comment by sophiepintoraetz** [comment] 2023-09-04 06:04
@CortneyOfstad - make sure you're leaving a summary to this effect and assigning @JmillsExpensify 

Payouts due:

Contributor+: $1500 @rushatgabhane 

Eligible for 50% #urgency bonus? Y

**Closed** 2023-09-05 05:10 UTC
Labels: External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:27
$1,500 payment approved for @rushatgabhane based on BZ summary.
