### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - No gap between username and ReportPreview in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22797] opened 2023-07-13 11:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App > Navigate to any chat.
2. Press + from composer > Request money > Add amount > Press Next and Press Request.
3. Notice that there is no margin between username and report preview.

## Expected Result:
There should be a top margin of 8px which is consistent with IOUPreview and attachments

## Actual Result:
There is no margin between username and ReportPreview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-12 at 4 31 03 PM](https://github.com/Expensify/App/assets/93399543/63ca0520-3c51-46da-8379-4ffdcf099049)

https://github.com/Expensify/App/assets/93399543/edd1129b-86a0-41ba-8d2e-e0dc201c53c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689160540866809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb7137f6f7800a33</li>
        <li>Upwork Job ID: 1679575096275460096</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-13 11:24
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No gap between username and ReportPreview in chat which is inconsistent with attachments, IOUPreview, etc. which have a top margin of `8px`.
### What is the root cause of that problem?
We don't have `styles.mt2` for `View` wrapper in `ReportPreview` -
https://github.com/Expensify/App/blob/d6b2d073a57d7bb40ad8aea475bd7a8be946ba24/src/components/ReportActionItem/ReportPreview.js#L107
This is inconsistent with other components like `IOUPreview` which have a top margin of `8px`. -
https://github.com/Expensify/App/blob/d6b2d073a57d7bb40ad8aea475bd7a8be946ba24/src/pages/home/report/ReportActionItem.js#L242
It is also inconsistent with attachments which also have a top margin of `8px` -
https://github.com/Expensify/App/blob/d6b2d073a57d7bb40ad8aea475bd7a8be946ba24/src/pages/home/report/ReportActionItem.js#L294
### What changes do you think we should make in order to solve the problem?
We need to add `styles.mt2` in line 107 in `ReportPreview` -
```javascript
<View style={[styles.iouPreviewBox, styles.mt2, props.isHovered ? styles.iouPreviewBoxHover : undefined]}>
```
### What alternative solutions did you explore? (Optional)
NA
Result -
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/31413407/337a1597-c015-4309-8259-0a64b2d76b9f">

**Comment by Pujan92** [comment] 2023-07-13 20:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There isn't margin for ReportPreview and username when it is the first message for that time span

### What is the root cause of that problem?
We don't have `containerStyles` prop for the `ReportPreview` and we are not providing any margin for the `ReportPreview` in the `ReportActionItem` component when it is displayAsGroup.
https://github.com/Expensify/App/blob/531dba82e00eb95d9c03533006b8ef3365a258ac/src/pages/home/report/ReportActionItem.js#L247-L254

### What changes do you think we should make in order to solve the problem?

1. Add prop `containerStyles` for the `ReportPreview` component.
`containerStyles: PropTypes.arrayOf(PropTypes.object),`

2. Pass `containerStyles` prop for the `ReportPreview` from `ReportActionItem`
`containerStyles={props.displayAsGroup ? [] : [styles.mt2]}`

3. Apply `containerStyles` for the `View` styles in the `ReportPreview` here(I prefer to add for the first option as it won't show cursor pointer for the above marginal area, with that we can do the same minor change for `IOUPreview` also)
`<View style={[styles.chatItemMessage, ...props.containerStyles]}>`
https://github.com/Expensify/App/blob/531dba82e00eb95d9c03533006b8ef3365a258ac/src/components/ReportActionItem/ReportPreview.js#L93
Or
https://github.com/Expensify/App/blob/531dba82e00eb95d9c03533006b8ef3365a258ac/src/components/ReportActionItem/ReportPreview.js#L105

**Comment by daanish-shaikh** [comment] 2023-07-14 17:27
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
No gap between username and report review in chat

### What is the root cause of that problem?
No space (margin) for TaskPreview and ReportPreview components.

### What changes do you think we should make in order to solve the problem?
Add top margin to TaskPreview and ReportPreview.

**src/styles/styles.js Line no. 3520**
```
previewMessageMargin: {
marginTop: 10,
},
```

**src/components/ReportActionItem/ReportPreview.js Line no. 93**
```
<View style={[styles.chatItemMessage, styles.previewMessageMargin]}>
```

**src/components/ReportActionItem/TaskPreview.js Line no. 74**
```
<View style={[styles.chatItemMessage, styles.previewMessageMargin]}>
```

**Comment by mollfpr** [comment] 2023-07-17 14:53
Reviewing

**Comment by Pujan92** [comment] 2023-07-20 13:58
@mollfpr [PR](https://github.com/Expensify/App/pull/23276) is ready for review!

**Comment by iwiznia** [comment] 2023-07-21 20:16
Seems this is mostly ready, so not unassigning myself, but if this does not get closed, @lschurr  please unassign and re-assign another engineer since I am going on sabbatical

**Comment by lschurr** [comment] 2023-07-31 22:48
@mollfpr could you work through the checklist and let me know if we need a regression test?

**Comment by lschurr** [comment] 2023-07-31 22:50
Payout summary:

- Bug reporter: @Nikhil-Vats $250
- Contributor: @Pujan92 $1500
- Contributor+: @mollfpr $1500

Payments will be made via Upwork on 8/2

**Comment by lschurr** [comment] 2023-08-02 16:32
Payments have been made in Upwork.

@mollfpr could you work on the checklist so we can close this one out? https://github.com/Expensify/App/issues/22797#issuecomment-1652057661

**Comment by lschurr** [comment] 2023-08-03 18:03
Added QA test request. Closing this one out!

**Closed by lschurr** 2023-08-03 18:03 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
