### ISSUE TITLE
[HOLD for payment 2023-01-31] IOS - New Room - Unable create a room when using second dash

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14137] opened 2023-01-09 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13994

## Action Performed:
1. Launch the app
2. Log i with expensifail account
3. Tap on Fub menu
4. Select New Room
5. Use two dashes in the room name field

## Expected Result:
Able to use dashes when creating a room

## Actual Result:
Unable create a room when using second dash

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native 

**Version Number:** 1.2.50.13

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211348989-3255fbd8-e0bf-46aa-9bc0-5acc5ebee17a.MP4

https://user-images.githubusercontent.com/93399543/211348996-150e896b-f1f0-4c8e-9524-bd3342a85f29.MP4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eefd02d7b3fd0024</li>
        <li>Upwork Job ID: 1615503215369134080</li>
        <li>Last Price Increase: 2023-01-18</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-01-11 22:10
interesting! so, if a room can be made with a single hyphen, a room should be made with a double hyphen. therefore, we should build out the capability to create a room with a double hyphen. 

this doesn't seem like it would affect the standard end-user experience too much, but the error messaging + capability should be consistent. 

i will work on reproducing and then go from there!

**Comment by maddylewis** [comment] 2023-01-17 15:49
@kbecciv - I wasn't able to reproduce this. I'm wondering if this has already been resolved. can you try reproducing this one again and let me know? thanks! 

https://user-images.githubusercontent.com/38016013/212945050-ea5ece6d-1cc1-406b-b565-8a8b049a9c66.mp4

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/38016013/212945026-0828f4f1-6881-4a6b-9562-71dddffc7f38.png">

**Comment by kbecciv** [comment] 2023-01-17 18:50
@maddylewis This is IOS app issue only.

**Comment by maddylewis** [comment] 2023-01-17 18:53
oh got it - thanks for clarifying. let me try to reproduce on the app.

**Comment by luacmartins** [comment] 2023-01-18 00:15
I can reproduce on iOS. I think the issue is that iOS combines `--` into `—` which is rejected by our validation.

**Comment by luacmartins** [comment] 2023-01-20 21:53
[PR up](https://github.com/Expensify/App/pull/14419)

**Comment by mollfpr** [comment] 2023-02-01 01:26
@maddylewis Could you help issue the payment here? Thanks!

**Comment by maddylewis** [comment] 2023-02-01 01:38
@mollfpr - will you apply to the job so that i can issue payment? https://www.upwork.com/jobs/~01eefd02d7b3fd0024

thanks!

**Comment by mollfpr** [comment] 2023-02-01 01:43
@maddylewis applied thanks!

**Comment by maddylewis** [comment] 2023-02-01 02:33
alrighty, i think we're all paid up on this one.

**Comment by mollfpr** [comment] 2023-02-01 02:57
@maddylewis offer accepted!

**Comment by luacmartins** [comment] 2023-02-01 18:32
@maddylewis have we handled all payments for this issue? Can we close this?

**Comment by dylanexpensify** [comment] 2023-02-02 14:53
Payment sent!!

**Closed by dylanexpensify** 2023-02-02 14:53 UTC
Labels: Reviewing, Daily, Internal, Bug
