### ISSUE TITLE
Web - Money request - Unable to delete money request when they are negative values

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25701] opened 2023-08-22 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website for two users
2. Click the + Icon from LHN for user A and user B
3. Click money request for both users
4. send money request from user A to user B
5. send a money request from user B to user A with a greater value just to make a negative request from user A
6. Go to user A and open IOU report
7. make sure the value is negative
8. try to delete the value by clicking a right click on the money request

## Expected Result:
The request should be deleted

## Actual Result:
Unexpected error deleting the money request, please try again later

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.54-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2f6c10c3-9e3b-4822-88db-7c3a08157fa7

![IMG_0404](https://github.com/Expensify/App/assets/115492554/0b85922d-fb2f-4a92-bdcc-fa3643f33ac3)

https://github.com/Expensify/App/assets/115492554/abc42d57-0fa2-49a4-86c5-985e978df23d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692110164318519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment] 2023-08-24 06:44
This might have the same root cause as https://github.com/Expensify/App/issues/24372

**Comment by tjferriss** [comment] 2023-08-24 16:37
Looks like a dupe of https://github.com/Expensify/App/issues/24372

**Closed by tjferriss** 2023-08-24 16:37 UTC
Labels: Daily, Bug
