### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] IOU-Markdown applied is displayed as text without markdown in IOU preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33340] opened 2023-12-20 10:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a 1:1 chat
3. Tap request money--- manual
4. Enter an amount and tap next
5. Enter markdown text eg *456* in description
6. Tap request
7. Tap on IOU created

## Expected Result:
Markdown applied must be displayed in IOU preview.

## Actual Result:
Markdown applied is not displayed in IOU preview. The text with markdown applied in IOU description is shown in IOU preview as text without markdown applied.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/486b4c37-f8bb-4ec7-9ec3-878305094888

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018df7a4462e491a32</li>
        <li>Upwork Job ID: 1737423428338143232</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28079603</li>
</ul></li>
    </ul>
</details>

**Comment by AxeemHaider** [comment] 2023-12-21 08:54
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue is that when Markdown is applied, it appears as plain text in the IOU preview without rendering the Markdown formatting.

### What is the root cause of that problem?
We are not checking either description is simple text or in Markdown format. We are displaying it as plain text for simple text and markdown format, that's why markdown format also shown as a plain text. As you can see here.
https://github.com/Expensify/App/blob/c09a3fead81512a4b01ccafff4c736301e0dbe89/src/components/ReportActionItem/MoneyRequestPreview.js#L331

### What changes do you think we should make in order to solve the problem?
Here is the code which is responsible to display description in IOU Preview
https://github.com/Expensify/App/blob/c09a3fead81512a4b01ccafff4c736301e0dbe89/src/components/ReportActionItem/MoneyRequestPreview.js#L330-L332

1. Firstly, we need to check whether we should display the description or not.
2. If we have to display description then we have to check is it a plain text or markdown format
3. if markdown format then parse the markdown text and convert it into `HTML` then display as HTML.
4. Otherwise it is plain text

### What alternative solutions did you explore? (Optional)
Instead of checking each component/page individually for whether it is in plain text or Markdown format, we can implement this logic inside the `Text` component. This way, it will automatically check if the input text is plain text and display it as is, or if it is in Markdown format, parse and display it as HTML. This approach eliminates the need to repeatedly write these conditions.

**Comment by Victor-Nyagudi** [comment] 2023-12-21 08:59
For reference sake, parsing description text was removed in this issue so that special characters like `<` aren't converted to `&lt`. 

- https://github.com/Expensify/App/issues/19386#issuecomment-1562946387

That was accomplished in this PR.

- https://github.com/Expensify/App/pull/19868

**Comment by AxeemHaider** [comment] 2023-12-21 09:52
Contributor details
Your Expensify account email: axeemhaider@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c39582606f6c1ae5

**Comment by AxeemHaider** [comment] 2023-12-21 10:14
@Victor-Nyagudi thanks for this reference. I test my code on my local machine and eveything is working perfectly you can see this video.
[Screencast from 2023-12-21 15-11-29.webm](https://github.com/Expensify/App/assets/27768863/898137ab-64d7-4276-9fcd-eb02569a9a28)

**Comment by greg-schroeder** [comment] 2023-12-31 10:34
Awaiting proposal review @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-01-02 13:33
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/33340#issuecomment-1864255661) LGTM 
🎀 👀 🎀

**Comment by greg-schroeder** [comment] 2024-01-03 20:26
Next up is @youssef-lr to confirm contributor assignment https://github.com/Expensify/App/issues/33340#issuecomment-1874032107

**Comment by greg-schroeder** [comment] 2024-01-26 18:49
c: @dukenv0307 - $500 - paid
c+: @rushatgabhane - $500

Rushat you can make a manual request, and then if you could complete the checklist we can close this out!

**Comment by rushatgabhane** [comment] 2024-01-26 20:44
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/19868


2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/19868#issuecomment-1912671316


3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A. because this was intentionally removed.

4. Determine if we should create a regression test for this bug. No

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again -N.A.

**Comment by rushatgabhane** [comment] 2024-01-26 20:45
Thank you! manual request here https://staging.new.expensify.com/r/8963455257501785

**Closed** 2024-01-26 21:55 UTC
Labels: External, Weekly, Awaiting Payment, Bug
