### ISSUE TITLE
IOU - Not found view is briefly shown when refreshing page while expense title RHP is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41005] opened 2024-04-25 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40704
## Action Performed:
Prerequisite: use slow 3G simulated network
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Open workspace chat
4. Create two IOUs
5. Open Expense report page
6. Click on "Title"
7. Refresh the page

## Expected Result:
Skeleton view is seen until page loads

## Actual Result:
Not found view gets displayed briefly until page fully loads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2afcf9ff-1428-4912-86eb-83086380cbad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-25 17:40
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-25 17:41
We think that this bug might be related to #vip-vsp

**Comment by deetergp** [comment] 2024-04-25 19:54
I'm not able to reproduce.

**Comment by deetergp** [comment] 2024-04-25 20:19
I also don't think this is serious enough to block on.

**Comment by deetergp** [comment] 2024-05-01 07:06
I'm going to ask around for reproduction retries tomorrow.

**Comment by deetergp** [comment] 2024-05-02 00:22
Requested a re-test [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714609198174829).

**Comment by deetergp** [comment] 2024-05-02 18:05
Thank you @kbecciv. I am going to close this one.

**Closed by deetergp** 2024-05-02 18:05 UTC
Labels: Engineering, Daily
