### ISSUE TITLE
[HOLD for payment 2024-12-09] [Xero] Prevent making an unnecessary API call if the value hasn't changed

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#53128] opened 2024-11-26 13:35 UTC
**Version Number:** `v9.0.66-7`
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** lucien+xero@expensifail.com
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @mkzie2  
**Slack conversation** (hyperlinked to channel name): NA

## Action Performed:

Prerequisite: having the browser's console open

1. Connect Xero to a Workspace
2. Go to `Advanced`
3. Click on `Map Xero Region to` (or whatever name the tracking category has)
4. Select the same value already selected

## Expected Result:
An API call isn't made if the value hasn't changed

## Actual Result:
An API call is made even though the value hasn't changed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Video</summary>

https://github.com/user-attachments/assets/fe2f016a-4321-4cdf-b461-7b2ea858a49d
  
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lakchote** [comment] 2024-11-26 13:36
@mkzie2 who reported the issue, has already a draft PR [here](https://github.com/Expensify/App/pull/53116). No new proposals needed.

**Comment by eh2077** [comment] 2024-11-26 13:57
I worked with @mkzie2 on https://github.com/Expensify/App/issues/52397 as the C+.

@lakchote Maybe you can assign me on this issue and then I'll be auto assigned to review PR https://github.com/Expensify/App/pull/53116 if @mkzie2 links this issue in the PR.

**Comment by mkzie2** [comment] 2024-11-26 14:01
> let me know once it's available for review, so I can assign the correct C+ to the issue.

@lakchote Sure.

**Comment by mkzie2** [comment] 2024-11-26 14:23
@lakchote The PR is ready. Do I need to wait to assign a C+ here before opening the PR? Or will open and choose the assigned C+ from bot?

**Comment by lakchote** [comment] 2024-11-27 16:20
Assigned you @eh2077 as the C+.

@mkzie2 it should assign @eh2077 once you put your PR under review.

**Comment by mkzie2** [comment] 2024-11-27 16:24
@eh2077 The PR is ready.

**Comment by mkzie2** [comment] 2024-12-02 04:12
@lakchote Should we handle payment here since this bug isn't related to our previous PR? If yes, please help to assign me here. Thanks.

**Comment by lakchote** [comment] 2024-12-02 07:42
> @lakchote Should we handle payment here since this bug isn't related to our previous PR? If yes, please help to assign me here. Thanks.

Yes we should handle payment here, I've assigned you.

**Comment by JmillsExpensify** [comment] 2024-12-09 11:08
Payment summary: 

 - Contributor: $250 @mkzie2 via Upwork
 - Reviewer: $250 @eh2077 via New Expensify

**Comment by JmillsExpensify** [comment] 2024-12-09 11:11
Upwork offer sent. @eh2077 do you mind completing the BZ checklist for this one and then request via New Expensify?

**Comment by JmillsExpensify** [comment] 2024-12-10 11:12
Contributor paid out, all that remains is BZ checklist and then New Expensify payment.

**Comment by eh2077** [comment] 2024-12-10 11:29
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by JmillsExpensify** [comment] 2024-12-10 16:35
Awesome thanks for both. I'm closing this one out.

**Comment by garrettmknight** [comment] 2024-12-10 16:36
**Payment summary:**

- Contributor: $250 @mkzie2 via Upwork
- Reviewer: $250 @eh2077 via New Expensify

**Closed by JmillsExpensify** 2024-12-10 16:35 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-10 17:33
$250 approved for @eh2077
