### ISSUE TITLE
[HOLD for payment 2024-12-17] Web - Workspace - Workspace tooltip does not adjust immediately after updating workspace name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53287] opened 2024-11-28 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+232803@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace settings > Profile.
4. Hover over workspace avatar under "Submit expenses using your workspace chat below:"
5. Note that the tooltip does not cover the avatars and remember the width of workspace avatar tooltip.
6. Change the workspace name to longer name (as long as possible).
7. Hover over workspace avatar under "Submit expenses using your workspace chat below:"
8. Note that the tooltip covers the avatars and the width of workspace avatar tooltip is the same as Step 5.
9. Go back to workspace list, and return to the same workspace profile.
10. Hover over workspace avatar under "Submit expenses using your workspace chat below:"
11. Note that now the tooltip does not cover the avatars and the width of workspace avatar tooltip is adjusted.

## Expected Result:
In Step 8, the workspace avatar tooltip should adjust accordingly after workspace name is updated.

## Actual Result:
In Step 8, the workspace avatar tooltip does not adjust accordingly after workspace name is updated. It covers the avatars when the new name is very longer while maintaining the same tooltip width.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4a87110-e9eb-4c91-8173-df9fc60ccc9f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by mountiny** [comment] 2024-11-28 22:59
Demoting as its minor but asking the authors of the feature to follow up, thanks

**Comment by s77rt** [comment] 2024-11-28 23:22
cc @nkdengineer

**Comment by nkdengineer** [comment] 2024-11-29 03:34
I'm here

**Comment by nkdengineer** [comment] 2024-11-29 09:30
@s77rt we have a follow up PR [here](https://github.com/Expensify/App/pull/53300)

**Comment by MitchExpensify** [comment] 2024-12-13 01:37
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment] 2024-12-13 01:38
**Payment summary:**

- $250 @s77rt requires payment through NewDot Manual Requests
- $250 @nkdengineer requires payment (Needs manual offer from BZ)

**Comment by MitchExpensify** [comment] 2024-12-13 01:39
Please complete the BZ steps here @s77rt, thanks

**Comment by s77rt** [comment] 2024-12-13 13:24
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [X] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: Not needed. This issue is a [regression](https://github.com/Expensify/App/pull/52449) and the author is aware of the cause

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    Bug requires regression test: No

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by s77rt** [comment] 2024-12-13 13:25
@MitchExpensify Please close this issue. No payment is due as it's a regression

**Closed** 2024-12-16 13:29 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
