### ISSUE TITLE
[$500] Thread - "Reply in thread" crashes the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28648] opened 2023-10-02 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to any chat & send a message
4. Hover over the message and select "Reply in chat"

## Expected Result:
User expects to be able to reply in chat

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9b6806d4-b986-40c0-bdc3-c31c5d33034f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 / Applause - Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696250210141309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e5002857849143b</li>
        <li>Upwork Job ID: 1708935828598525952</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment] 2023-10-02 21:02
This bug is fixed not able to reproduce it

**Comment by mountiny** [comment] 2023-10-02 22:46
Correct, this is fixed with the revert pr before. No reporting payment as the fix was unrelated to this report

**Closed by mountiny** 2023-10-02 22:46 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
