### ISSUE TITLE
Feature Request:  Use space to toggle check box - reported by @Santhosh-Sellavel 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8602] opened 2022-04-12 04:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem:
1. After focusing on  checkbox we can use Enter the button to toggle it. But it gets conflicted with the Enter to submit the form
2. Also, I see the Space button is a commonly used way to toggle the checkbox. Reference [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)

## Solution:
Let's make the checkbox toggle-able using Space button. 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
https://github.com/Expensify/App/issues/7523#issuecomment-1068209007
https://github.com/Expensify/App/issues/7523#issuecomment-1068548722 

https://user-images.githubusercontent.com/43995119/162877975-a57fa0b9-0538-42b9-86b6-cb22a148d07d.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648488615567699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mdneyazahmad** [comment] 2022-04-12 11:05
I addressed this here https://github.com/Expensify/App/issues/7918#issuecomment-1075009993 and pr will possibly fix this issue.

**Comment by Beamanator** [comment] 2022-04-12 17:53
Thanks for the heads up @mdneyazahmad 👍 

Since @Santhosh-Sellavel first mentioned the suggestion in a GH issue (

**Comment by pecanoro** [comment] 2022-04-12 21:32
Hmm, wasn't that part of the audit, fixing the inconsistencies? Using space was a faulty behavior, right? Anyways, yes, we should leave the other one open since it will fix more stuff. You can add him to any of the issues as the reporter so he can get paid for suggesting a more broad fix.

**Comment by Beamanator** [comment] 2022-04-13 20:20
Ok sweet so did some discussing internally ([here](https://expensify.slack.com/archives/C01SKUP7QR0/p1649865971560989)) and here's the plan:
1. Lets pay out @Santhosh-Sellavel for reporting this feature
2. We'll close this issue b/c the feature will be worked on in all of the form-audit issues ([one](https://github.com/Expensify/App/issues/7523), [two](https://github.com/Expensify/App/issues/7916), [three](https://github.com/Expensify/App/issues/7917), [four](https://github.com/Expensify/App/issues/7918))

**Comment by Beamanator** [comment] 2022-04-13 20:21
@michaelhaxhiu please take a look at the plan for this issue here: https://github.com/Expensify/App/issues/8602#issuecomment-1098449070

After making the Upwork job for this, we do not need to mark it `Exported`!

**Comment by michaelhaxhiu** [comment] 2022-04-14 01:18
@Santhosh-Sellavel can you apply for [this job](https://www.upwork.com/jobs/~01160cf41a4dffa2e2) please

**Comment by Kazuya-san** [comment] 2022-04-14 04:47
Hi,
If the issue is still unsolved I would like to work on it

**Comment by Santhosh-Sellavel** [comment] 2022-04-14 10:44
Done @michaelhaxhiu !

**Comment by Santhosh-Sellavel** [comment] 2022-04-14 10:46
@Kazuya-san this is already worked on by another contributor.

There are other [open jobs](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22) which you can work on.

**Comment by michaelhaxhiu** [comment] 2022-04-14 12:06
Paid, all done here.

**Closed by michaelhaxhiu** 2022-04-14 12:06 UTC
Labels: External, Engineering, Daily, NewFeature
