### ISSUE TITLE
[$1000] Line Height is not set in 'Change Password' page new password instruction in settings

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14129] opened 2023-01-09 02:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Open 'Security'
4. Open 'Change Password'

## Expected Result:
New password instruction should have 'line-height:18px' css as other instruction messages have in different options of settings page (example displayed in video)

## Actual Result:
ine-height is not set making the new password instruction message look more compressed then other similar instruction messages in different options of settings page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.50-13
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211234414-f56bd37a-df01-42b0-8021-ba0ee3219490.mp4

https://user-images.githubusercontent.com/43996225/211234431-2f0623a5-e2b5-491f-8873-eec601bfbc54.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673113125315509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01373620c2f80b457f</li>
        <li>Upwork Job ID: 1613609308235161600</li>
        <li>Last Price Increase: 2023-01-12</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-01-11 00:43
I will test tomorrow.

**Comment by alexpensify** [comment] 2023-01-12 01:27
Assigning to engineering an extra pair of eyes before assigning to external. I think I'm checking the right location here: 

![image](https://user-images.githubusercontent.com/8107070/211953991-6474b4ea-f482-46a1-9c4a-93e94697ba24.png)

**Comment by johnmlee101** [comment] 2023-01-12 18:48
I think the problem is with the instructions at the bottom, not necessarily the input itself.

**Comment by johnmlee101** [comment] 2023-01-12 18:49
Should be an easy fix, will mark external.

**Comment by Pujan92** [comment] 2023-01-12 18:55
**Proposal**

We can set the line height for that text.

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index a0d4ec175..c18c5ae7b 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -888,6 +888,7 @@ const styles = {
         fontFamily: fontFamily.EXP_NEUE,
         fontSize: variables.fontSizeLabel,
         color: themeColors.textSupporting,
+        lineHeight: variables.lineHeightNormal,
     },
```

**Comment by johnmlee101** [comment] 2023-01-12 19:15
Oh wait that's a great point, this will eventually be removed in the passwordless flow

**Comment by johnmlee101** [comment] 2023-01-12 19:16
@alexpensify would love your input since any changes here would not last

**Comment by alexpensify** [comment] 2023-01-12 20:32
@johnmlee101 good call, I vote to close then since it's not an urgent fix that's blocking usage. As pointed out here, once passwordless flow is live, then this section will not be needed in Expensify. Do you agree with that summary? Thanks!

**Comment by johnmlee101** [comment] 2023-01-12 20:33
Correct, let's close this out then

**Comment by johnmlee101** [comment] 2023-01-12 20:43
Sorry for the confusion, this should have been avoided as being marked as a bug since its being refactored as part of passwordless!

**Closed by johnmlee101** 2023-01-12 20:43 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by alexpensify** [comment] 2023-01-13 00:25
I closed the job in Upwork too!
