### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Add a mandatory route param to Navigation.goBack to prevent bugs

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#24291] opened 2023-08-08 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem
Calling `Navigation.goBack()` in App without a route can cause problems since it will navigate to the wrong page if the desired page to go back to is not the last page in the navigation history.

## Solution
Add a mandatory route param to Navigation.goBack so that the screen to navigate back to must be specified. Discussed in [Slack here](https://expensify.slack.com/archives/C049HHMV9SM/p1690915949087489).

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee5e103f65c1a8fa</li>
        <li>Upwork Job ID: 1688984859314130944</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 26164451</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-08-08 18:59
Dupe of #22041?

**Comment by neil-marcellini** [comment] 2023-08-08 19:01
No this is a general improvement coming from Slack. Oh lol but I do see that we're having parallel conversations.

**Comment by situchan** [comment] 2023-08-08 19:04
We're trying to fix globally in that issue.

**Comment by neil-marcellini** [comment] 2023-08-08 19:05
Ok cool then I'll close this and link to the conversation we had.

**Comment by abdulrahuman5196** [comment] 2023-08-08 19:20
@neil-marcellini I think there is a subtle difference on what is being targetted there and what we are targetting here.

1) https://github.com/Expensify/App/issues/22041 deals with how we fix all the existing `Navigation.goBack()` to have fallback routes.
2) But What I proposed was to handle future cases(since we where thinking of adding it to checklist), like even after the other fix is made there is nothing stopping contributors from making the same mistake of just using `Navigation.goBack()` . So if we make the fallback param mandatory, `Navigation.goBack(fallback)` would be only way to use the function. So if they don't want any specific screen, they can give home as fallback or they have to give some proper screen as fallback.

**Comment by neil-marcellini** [comment] 2023-08-09 17:35
Ok that sounds different enough. I'll re-open this.

**Comment by hanzalahsamana** [comment] 2023-08-09 21:58
I would love to work on this @neil-marcellini

**Comment by mananjadhav** [comment] 2023-08-10 04:17
@hanzalahsamana Please checkout our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to send out a proposal.

**Comment by hanzalahsamana** [comment] 2023-08-10 11:57
Proposal

**Please re-state the problem that we are trying to solve in this issue.**
We're dealing with a situation where using Navigation.goBack() in the App without telling where to go might cause problems. It can lead to going to the wrong place if the wanted page isn't the last one in the history.

**What is the root cause of that problem?**
The issue comes from not being clear when using Navigation.goBack(). It's like not saying where you want to go, and that can make users end up in unexpected places.

**What changes do you think we should make in order to solve the problem?**
To fix this, we should make sure everyone uses Navigation.goBack() with a clear plan. We can do this by making it necessary to say where to go when using Navigation.goBack(). This way, we avoid confusion. If someone doesn't have a specific place in mind, they can set a default spot, like the main screen.

**What alternative solutions did you explore? (Optional)**
We thought about giving extra instructions to avoid using Navigation.goBack() without saying where to go. But this might not work well since not everyone might read those instructions. The mandatory fallback idea is more reliable because it guarantees correct navigation, no matter who is using it.

I appreciate your time considering this plan. If you want to talk more about it, I'm here to help.

Best regards,
Hanzalah

**Comment by mananjadhav** [comment] 2023-08-10 16:58
Sure. Will wait for @abdulrahuman5196 to post a proposal.

**Comment by mananjadhav** [comment] 2023-08-13 12:03
Okay based on the expected behavior, @abdulrahuman5196's proposal looks good to me.

cc - @neil-marcellini 

🎀 👀 🎀 C+ reviewed.

**Comment by abdulrahuman5196** [comment] 2023-08-16 17:26
@neil-marcellini Bump on this.

**Comment by neil-marcellini** [comment] 2023-08-16 18:42
Not overdue, looking soon.

**Comment by neil-marcellini** [comment] 2023-08-16 20:45
@abdulrahuman5196's [proposal](https://github.com/Expensify/App/issues/24291#issuecomment-1676262314) looks good to me too.

**Comment by mananjadhav** [comment] 2023-08-18 16:40
@abdulrahuman5196 Any updates on this for the PR?

**Comment by sophiepintoraetz** [comment] 2023-08-21 19:48
@abdulrahuman5196 - one more bump for you here else we'll need to start considering another implementor!

**Comment by abdulrahuman5196** [comment] 2023-08-23 14:02
Apologies for the delay. I will have the PR ready before Friday. If there is more delay from my end I am fine to get an contributor to implement my proposal.

**Comment by abdulrahuman5196** [comment] 2023-08-25 18:24
> @abdulrahuman5196 I'd love to help out with this if you do not have the time, maybe we could split the bounty?

@Prince-Mendiratta Sure. I am fine with this. If its fine with you, could you create the PR?

**Comment by mananjadhav** [comment] 2023-08-25 18:45
@abdulrahuman5196 should we open this for external contributors?

cc - @sophiepintoraetz

**Comment by abdulrahuman5196** [comment] 2023-08-25 18:47
> > @abdulrahuman5196 I'd love to help out with this if you do not have the time, maybe we could split the bounty?
> 
> @Prince-Mendiratta Sure. I am fine with this. If its fine with you, could you create the PR?

@mananjadhav  @Prince-Mendiratta  already expressed dibs if I didn't get time. So I think he can do the PR, if it's ok with you all?

**Comment by abdulrahuman5196** [comment] 2023-08-27 09:35
@sophiepintoraetz @neil-marcellini @mananjadhav  Kindly check on the above and assign @Prince-Mendiratta if its fine with you all.

**Comment by sophiepintoraetz** [comment] 2023-08-28 00:44
I think we need @neil-marcellini to give the final sign off - thank you abdul for the prompt!

**Comment by mananjadhav** [comment] 2023-08-29 04:59
Agreed, I'll let @neil-marcellini give the sign-off on this one.

**Comment by sophiepintoraetz** [comment] 2023-09-04 06:12
I've bumped @neil-marcellini in new dot twice now - will escalate to slack after the holiday if we don't hear from him!

**Comment by neil-marcellini** [comment] 2023-09-04 18:25
I'm looking now sorry for the delay.

**Comment by neil-marcellini** [comment] 2023-09-04 18:27
To be clear, @Prince-Mendiratta and @abdulrahuman5196 will be splitting the payment for this issue.

**Comment by sophiepintoraetz** [comment] 2023-09-14 01:57
I've assigned him!

**Comment by mananjadhav** [comment] 2023-09-14 02:20
I am a bit unwell and I'll try to close this by tomorrow.

**Comment by sophiepintoraetz** [comment] 2023-10-01 23:56
Payouts due:

Issue Reporter: $250 N/A - Neil
Contributor: $500 @abdulrahuman5196 
Contributor: $500 @Prince-Mendiratta 
Contributor+: $1000 @mananjadhav 

Eligible for 50% #urgency bonus? N

**Comment by mananjadhav** [comment] 2023-10-02 14:18
We can treat this as a feature request, and not directly related to any specific feature here. We don't need a regression suite here as these can be covered in other features. We only changed by forcing an arg in the method call.

**Closed** 2023-10-03 06:49 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:56
$1,000 payment approved for @mananjadhav based on BZ summary.
