### ISSUE TITLE
[$1000] Web - There's no valid URL if copy pasted the URL from the public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21207] opened 2023-06-21 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a public room and then copy the share URL and paste it into an incognito window (make sure you aren't signed in before)
3. Click Sign-In at the bottom right of the page
4. Sign in with a brand new account
5. Once you're signed in, you should see a welcome message in the room. Right click on here link highlighted in blue in the welcome message and click on "Copy URL to Clipboard"
6. After it displays 'Copied', go to a new tab and paste the URL and notice that no expensify link is shown. Only settings/profile/display-name is displayed. It should have shown link with the expensify.

## Expected Result:
URL in 'here' should have displayed link with expensify on the public room

## Actual Result:
There's no valid URL if copy pasted the URL from the public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cdd86e42-44e0-4f1a-b345-0a5a28d39346

https://github.com/Expensify/App/assets/93399543/6f583c06-a21a-47db-9171-cf3937799aa5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686739902094619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019262c89449f40ce1</li>
        <li>Upwork Job ID: 1673497422829457408</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by priya-zha** [comment] 2023-06-21 14:15
NOTE: If you directly click on 'here' link using the mouse, it perfectly opens the display name page. But, if you right click the 'Copy Url' option and paste it in a new tab, then it doesn't work.

**Comment by priya-zha** [comment] 2023-06-21 15:27
@spcheema It happens on a public room and the condition is you **shouldn't** be signed in beforehand. In the 'here' part of the Concierge message, if you click it with your mouse, it works perfectly and the display name page opens up. 
But on the other hand, if you right click on 'here' and copy the URL from the 'Copy URL' button, and paste it in a new tab, it just displays "settings/profile/display-name". It should have opened up the display page with the correct expensify URL as it did in the previous case.

**Comment by sakluger** [comment] 2023-06-21 23:22
@kbecciv @priya-zha I didn't get the whisper message in the public room when I opened it while not signed in:

![image](https://github.com/Expensify/App/assets/5997400/5899189d-3eff-4cbf-90a3-45a0e73291e8)

Do I need to do anything special to get that whisper message while not signed in?

**Comment by priya-zha** [comment] 2023-06-22 08:04
@sakluger @spcheema Seems like today the whisper message has disappeared. It was shown till yesterday. Let me ask in #expensify-open-source channel

**Comment by Beamanator** [comment] 2023-06-22 08:26
I believe the fact that we had whispers for anonymous users was a bug, so now it's "fixed" - by not sending a whisper to anonymous users (cc @pecanoro )

**Comment by priya-zha** [comment] 2023-06-22 09:00
@sakluger @spcheema Seems having the whisper message for anonymous users was itself a bug that has been solved.

 Can you please try to reproduce the issue with a **new** user by signing in with any account in an incognito window (only after the user has opened the room link as anonymous).I'm still able to reproduce the bug even with a new logged-in user.

New Reproducible steps :

1. Go to staging dot on web chrome
2. Create a public room and then copy the share URL and paste it into an incognito window as an anonymous user (make sure you aren't signed in before- very important step)
3. Click on the 'Sign-in" button and it navigates you to the login page . Please enter the credentials of a new user that you haven't used before (important step)
4. Sign in to the new account and you'll be able to see the whisper message 
5. Right-click on 'here' link highlighted in blue and click on copy URL to clipboard
6. After it displays 'Copied', go to a new tab and paste the URL and notice that no expensify link is shown. Only settings/profile/display-name is displayed. It should have shown display page link with the expensify. Thus, there's no use of the link that we copied earlier.
7. But if we click on 'here' using the mouse ( instead of copying the URL and pasting it in a new tab), then the display page shows without any problem. 
8. Thus, the 'Copy URL' should also have shown the correct URL for display page instead of showing 'settings/profile/display-name'



https://github.com/Expensify/App/assets/34065075/2869ec64-af07-4720-b3c8-cba2eef943ef

**Comment by sakluger** [comment] 2023-06-27 01:00
Thanks for the updated steps, I was able to reproduce. Seems like we're copying a local link path, but should be copying the full url link.

**Comment by y4ahmad** [comment] 2023-06-27 04:37
I didn't get option to create new room, is there any specific point i have missed?

![image](https://github.com/Expensify/App/assets/25535112/a2239be3-2ed8-4513-911b-6f4bb6ab172c)

**Comment by sabhyap** [comment] 2023-06-27 04:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we try to copy the URL from public we do not get the host name appended to the string copied to clipboard. (Full URL is not copied only the path portion of the URL is copied)

### What is the root cause of that problem?

The copy to clipboard function does not do any check if the provided string is a valid URL. We can achieve this by checking the string with a Regex pattern and add any missing parts if it isn't properly written.

The issue is generate from here upon my debugging:
https://github.com/Expensify/App/blob/5f5dd023a8102ef47ac4b58e4bfe79b995cb0330/src/pages/home/report/ContextMenu/ContextMenuActions.js#L134

### What changes do you think we should make in order to solve the problem?
We can easily solve this by adding a Regex expression check and constructing a valid URL if anything is missing from the URL string.


### What alternative solutions did you explore? (Optional)

I believe any alternative solutions will be temporary and won't be any better than the original one.

**Comment by sabhyap** [comment] 2023-06-27 04:42
Contributor details
Your Expensify account email: satyaguts1@proton.me
Upwork Profile Link: https://www.upwork.com/freelancers/sabhya

**Comment by y4ahmad** [comment] 2023-06-27 04:44
Contributor details
Your Expensify account email: techbeepsinfo@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01571c7ce5c9bc4cd4

**Comment by y4ahmad** [comment] 2023-06-27 04:46
> I didn't get option to create new room, is there any specific point i have missed?
> 
> ![image](https://user-images.githubusercontent.com/25535112/249037162-a2239be3-2ed8-4513-911b-6f4bb6ab172c.png)

Any update on this?

**Comment by priya-zha** [comment] 2023-06-27 08:31
@y4ahmad Please try with a phone number account.

**Comment by s77rt** [comment] 2023-06-27 18:24
@sakluger This seems internal. Can you please confirm the same? Concierge is returning a relative path instead of an absolute path i.e. `/settings/profile/display-name` instead of `https://new.expensify.com/settings/profile/display-name`

**Comment by s77rt** [comment] 2023-06-28 13:51
@dukenv0307 I think the url should always be the production url. Even if you are in staging this won't cause a problem you will stay in staging when you click on the url due to deep linking implementation.

**Comment by s77rt** [comment] 2023-06-29 12:26
Hmm, that seems like a regression. Locally this seems to work fine

https://github.com/Expensify/App/assets/16493223/b6da046f-fb3b-4ec7-a42e-c0b27ab438f8

**Comment by sakluger** [comment] 2023-06-30 00:27
@y4ahmad you need to create a Workspace before creating a room.

@s77rt I'm not sure if this needs to be internal or not. I'm going to apply the engineering label to get one of our internal engineers to weigh in.

**Comment by sakluger** [comment] 2023-07-01 00:32
@youssef-lr could you please take a look to see if this issue should be internal or external? Thanks!

**Comment by sakluger** [comment] 2023-07-03 18:41
Friendly bump @youssef-lr

**Comment by youssef-lr** [comment] 2023-07-03 18:42
Checking now!

**Comment by youssef-lr** [comment] 2023-07-03 20:00
I think it's intentional that we don't send the full URL. If we do, it's gonna end up displayed like with a link preview and I'm not sure we want that.

<img width="962" alt="Screenshot 2023-07-03 at 20 58 17" src="https://github.com/Expensify/App/assets/9680864/0b497198-2e2e-4737-bc03-a1262f0921d7">

I also think we need to fix this to not open the link as it was an external link, it's an internal link and should just open the drawer without navigating the user to a different tab/window. We should be using our underlying navigation system to do this. 

What do you think @sakluger? I got a working solution locally I can create a PR for this so that it opens the drawer and not navigate us to a new page, if we decide to move forward with this solution.

**Comment by s77rt** [comment] 2023-07-05 20:29
@sakluger I think this is waiting for you ^

**Comment by sakluger** [comment] 2023-07-10 20:55
Sorry, I thought I had responded. I agree with @dukenv0307 - if we are going to show a hyperlink that can be copied, and a URL exists that will take the user to that page, then I think we should use the full URL for when the user copies the link.

I also like @youssef-lr's idea to treat as an internal link and open the profile in the same browser window/tab when the user clicks on the link. If that's an easy change to make, then I'm in favor of changing that as well, but we should also fix the link in case the user copies it.

**Comment by sakluger** [comment] 2023-07-11 15:52
Oh got it, thanks for clarifying, I hadn't tested again to confirm. In that case, I think we should just move forward with fixing the issue so that the link can be copied and pasted in a new browser tab.

**Comment by sakluger** [comment] 2023-07-12 16:09
@s77rt now that we've confirmed that the solution should allow users to copy that link and open in a new browser tab, do any of the current proposals fix the issue?

**Comment by youssef-lr** [comment] 2023-07-12 16:12
@sakluger  I think fixing this in the backend should work fine, i.e. sending the full URL.

**Comment by s77rt** [comment] 2023-07-12 22:36
We are working on it, Melvin

**Comment by sakluger** [comment] 2023-07-17 21:20
Sure, we can fix in the backend.

@youssef-lr I'm also curious about your concern around the link preview. Can we suppress the link preview here? It doesn't feel helpful in this context.

**Comment by s77rt** [comment] 2023-07-20 23:07
Not overdue. I think this pending a BE fix. As for the link preview concern I think we should have an option to disable that soon(?) https://github.com/Expensify/Expensify/issues/300704

**Comment by youssef-lr** [comment] 2023-07-24 16:15
I think we can simply disable link previews if the link is internal. What do you think @sakluger?

**Comment by sakluger** [comment] 2023-07-25 00:39
Sounds good to me!

**Comment by sakluger** [comment] 2023-07-27 22:11
Hey @s77rt can you remind me what we're holding this issue on?

**Comment by s77rt** [comment] 2023-07-27 22:21
@sakluger Nothing :sweat_smile: . I think we are waiting for @youssef-lr to fix the issue (change the url that Concierge send). @youssef-lr Can you please confirm the same?

**Comment by sakluger** [comment] 2023-07-27 22:59
Ah, got it! Thanks for clarifying, I think I was confused from your comment that this is "pending a BE fix". @youssef-lr are you working on disabling link previews for internal links?

**Comment by s77rt** [comment] 2023-07-31 18:34
Not overdue. @youssef-lr Any update here?

**Comment by sakluger** [comment] 2023-08-01 15:56
Looks like @youssef-lr has been out sick for the past few days, so there may be a slight delay on this one.

**Comment by sakluger** [comment] 2023-08-05 00:52
Still holding on @youssef-lr catching up from taking time off.

**Comment by sakluger** [comment] 2023-08-07 20:05
Bumped @youssef-lr via DM.

**Comment by youssef-lr** [comment] 2023-08-08 00:10
I think we should bring this up in Slack and ask for input about disabling previews for internal links @sakluger. Then we can send back the full URL for the Display Name settings page.

**Comment by sakluger** [comment] 2023-08-14 16:07
Posted in Slack: https://expensify.slack.com/archives/C02NK2DQWUX/p1692029252360049

**Comment by sakluger** [comment] 2023-08-17 17:39
After some discussion, we decided that this is a pretty minor thing and more of a feature request. We're still working out how to handle link previews in different situations, so I'm going to close this GH issue for now since it makes more sense to discuss this after we've figured out link previews.

**Closed by sakluger** 2023-08-17 17:39 UTC
Labels: Engineering, Daily, Internal, Bug
