### ISSUE TITLE
[$500] Chat - When typing on emoji search the keyboard is dismissed after typing a character

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32652] opened 2023-12-07 11:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to any chat
2. Tap on the emoji icon
3. Tap on the search field
4. Try to tap more than 1 character

## Expected Result:
The typed characters are added to the search and user can search on an emoji with more than one characters

## Actual Result:
After typing on character the keyboard is dismissed. User needs to tap on search again and type each character this way one by one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4e032b6c-f1d6-4a9e-9026-5723affd1520

https://github.com/Expensify/App/assets/115492554/e7cc856d-c498-4263-9206-a9cd49589db4

[Bug6304327_1701946927913!expen-log2.txt](https://github.com/Expensify/App/files/13599520/Bug6304327_1701946927913.expen-log2.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155143f14cdcc7ef6</li>
        <li>Upwork Job ID: 1732727287716786176</li>
        <li>Last Price Increase: 2023-12-07</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 28062291</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-12-07 12:13
Seems like regression from https://github.com/Expensify/App/pull/31899

**Comment by yuwenmemon** [comment] 2023-12-07 20:35
Fix was CP'd to staging, removing the blocker label

**Comment by dylanexpensify** [comment] 2023-12-11 07:46
Nice! @ArekChr what's the latest here?

**Comment by ArekChr** [comment] 2023-12-11 09:43
Hi @dylanexpensify, this bug has been fixed in PR: https://github.com/Expensify/App/pull/32654. I think we can close this issue.

**Comment by rlinoz** [comment] 2023-12-15 11:16
Closing since this has been fixed and I think there is no due payment.

**Comment by rlinoz** [comment] 2023-12-15 11:27
Oh I am sorry, I will reopen it.

Should you be assigned to this issue then?

**Comment by rlinoz** [comment] 2023-12-15 12:02
@dylanexpensify a PR has already fixed this issue and @aimane-chnaif did the review, but I am not sure how to proceed here.

**Comment by dylanexpensify** [comment] 2023-12-20 09:23
Aha! Amazing, sorry for delay, will work on this today!

**Comment by dylanexpensify** [comment] 2023-12-20 10:53
done!

**Closed by dylanexpensify** 2023-12-20 10:53 UTC
Labels: External, Engineering, Weekly, Bug
