### ISSUE TITLE
[HOLD for payment 2024-08-07] [$1000] Extra space around text in header of reply in thread if main message has 3 backtick code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22832] opened 2023-07-13 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send message with 3 backtick code block in it eg: hi ```hello``` test
4. Hover and click on reply in thread
5. Observe the header text, it will have extra spaces around text which was 3 backtick code block

## Expected Result:
Format of text should not affect reply in thread header text formatting

## Actual Result:
3 backtick code blocks in text adds extra space around the text in reply in thread header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9fcbc3fe-9ffc-41f8-9e6b-392f590c928f

https://github.com/Expensify/App/assets/93399543/c660f0df-1a06-48fb-8a80-2b2aa565d65b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689183843669479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cf4dbd8dbc4da67</li>
        <li>Upwork Job ID: 1684257620704722944</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26112867</li>
<li>dhanashree-sawant | Reporter | 26112869</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by eh2077** [comment] 2023-07-14 00:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Extra space around text in header of reply in thread if main message has 3 backtick code block.

### What is the root cause of that problem?

The root cause of this issue is that we format header of report thread by replacing line break of `message[0].text` with a space, see

https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/ReportUtils.js#L1125

So, there's will be an extra space added for `message[0].text`, like `hi \nhello`.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can replace `spaces+line breaks+spaces` with a single space. 

To achieve it, we can change the regex of this line

 https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/ReportUtils.js#L1125

to

```js
/\s*(\r\n|\n|\r)+\s*/gm
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by flaviadefaria** [comment] 2023-07-18 17:40
I'm discussing it in Slack [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1689676940686919) to confirm what would be the expected result.

**Comment by flaviadefaria** [comment] 2023-07-26 17:41
After discussing in Slack we agreed that intended outcome should be:
- Only the first line of the message should display on the thread title
- Markdown, if in a thread title, should display as markdown

**Comment by munsuyog** [comment] 2023-07-26 18:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem we aim to solve in this issue is related to the formatting of the reply in thread header text. When a message with a 3 backtick code block is sent, it adds extra spaces around the text in the reply in thread header.

### What is the root cause of that problem?
The root cause of the problem lies in the regular expression used to replace line breaks in the "parentReportActionMessage" variable. The current regular expression (/(\r\n|\n|\r)/gm, ' ') is replacing line breaks with spaces, which may lead to unintended formatting issues in the processed text.

### What changes do you think we should make in order to solve the problem?
To address the problem, we propose the following changes to the code in the file "App/src/libs/ReportUtils.js":
`const parentReportActionMessage = lodashGet(parentReportAction, ['message', 0, 'text'], '').trim();`
By using the trim() method, we can remove any leading or trailing whitespace, including line breaks, without replacing them with spaces. This ensures that the formatting of the message text remains intact and consistent.

### What alternative solutions did you explore? (Optional)
While the proposed solution is straightforward and effective, we could also consider an alternative approach:
`const parentReportActionMessage = lodashGet(parentReportAction, ['message', 0, 'text'], '').replace(/[\r\n]+/g, ' ');`

In this alternative solution, we use a regular expression (/[\r\n]+/g) to directly replace consecutive line breaks with a single space. This approach achieves the same result as the proposed solution but retains the use of regular expressions.

**Comment by Habben101** [comment] 2023-07-27 03:22
### Proposal  
### Please re-state the problem that we are trying to solve in this issue.  
The problem is related to the formatting of the reply in thread header text. When a message with a 3 backtick code block is sent, it adds extra spaces around the text in the reply in thread header.  
### What is the root cause of that problem?  
The root cause of the problem is in the way the 'parentReportActionMessage' is obtained and processed.
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/libs/ReportUtils.js#L1125
The code uses a regular expression to replace newline characters with spaces, but it does not handle code blocks properly, leading to extra spaces being added around the code block content.  
### What changes do you think we should make in order to solve the problem?  
As mentioned [here](https://github.com/Expensify/App/issues/22832#issuecomment-1652241374) the intended outcome should be Only the first line of the message should display on the thread title and the thread title should display as markdown if it is a md. To achive the intended outcome, we could write a function that can handle both like the following:
```javascript
function preserveCodeBlockAndGetFirst(inputContent) {
    const expensiMark = new ExpensiMark();
    const contentOutput = expensiMark.replace(inputContent);

    // Extract the first line from the HTML output
    const firstLine = contentOutput.match(/^.*?(?=<br\s*[/]?>|$)/)[0];

    // Preserve the code block content surrounded by triple backticks
    const modifiedcontentOutput = firstLine.replace(/<pre>(.*?)<\/pre>/gs, (match, codeBlockContent) => {
        return `\`\`\`${codeBlockContent}\`\`\``;
    });

    return modifiedcontentOutput;
}
``` 
Then change  `const parentReportActionMessage = lodashGet(parentReportAction, ['message', 0, 'text'], '').replace(/(\r\n|\n|\r)/gm, ' ');` 
To:
`const parentReportActionMessage = preserveCodeBlockAndGetFirst(lodashGet(parentReportAction, ['message', 0, 'text'], ''));` 

Result:

https://github.com/Expensify/App/assets/25123389/8421839f-9469-47ce-b9fa-bbcb155fb6df


https://github.com/Expensify/App/assets/25123389/346e322a-3482-42af-8f62-b2e7b06a4802

### What alternative solutions did you explore? (Optional)
NA

**Comment by sobitneupane** [comment] 2023-07-28 11:16
@flaviadefaria After going through the above proposals, I am pretty sure most of us are not clear about the expected output.

So, bo be clear on the expected output:

If we have highlighted text as the message, what will be the header.
1. `# highlighted text`
2. # highlighted text


If we have following code block as the message, what will be the header.
``` 
line1
line2
```

**Comment by munsuyog** [comment] 2023-07-28 16:33
> @flaviadefaria After going through the above proposals, I am pretty sure most of us are not clear about the expected output.
> 
> So, bo be clear on the expected output:
> 
> If we have highlighted text as the message, what will be the header.
> 1. `# highlighted text`
> 2. # highlighted text
> 
> 
> If we have following code block as the message, what will be the header.
> ``` 
> line1
> line2
> ```
1. If the message contains the following code block:

`# highlighted text`

The header of the reply in the thread will be:

`# highlighted text`

Since the code block is surrounded by backticks, it will be treated as inline code and won't be affected by the regular expression `replace(/(\r\n|\n|\r)/gm, ' ')`. The header will retain the exact formatting of the original code block, including the backticks and the '#' symbol.

2. 
If the message contains the following text:

`# highlighted text`

The header of the reply in the thread will be:

`highlighted text`

The `#` symbol at the beginning of the line is treated as a Markdown heading. When replying in a thread, the header text displays only the content of the heading without the '#' symbol. Therefore, the header will show the text "highlighted text" without the formatting of a heading.

If the message contains the following code block:
`line1
line2`

The header of the reply in the thread will be:
`line1 line2`

**Comment by flaviadefaria** [comment] 2023-07-31 08:49
Hey @sobitneupane happy to clarify so I think we're aiming to fix 2 separate things here:
1. Only the first line of the message should display on the thread title (regardless of if there's any markdown in the message)
2. If there's Markdown in a message that is in a thread title it should display as markdown


>If we have highlighted text as the message, what will be the header.

Exactly what's below though for number 2 I'd imagine we'd match the font size to the regular thread title size. 

1. `# highlighted text`
2. # highlighted text


>If we have following code block as the message, what will be the header.

The header will be line1 only.
``` 
line1
```

**Comment by sobitneupane** [comment] 2023-08-02 07:42
Just to confirm:

`# highlighted` is the markdown for highlighted text shown below. So, `# highlighted` will be displayed on header, right?
<img width="152" alt="Screenshot 2023-08-02 at 13 22 24" src="https://github.com/Expensify/App/assets/25876548/6ac8f0c7-d9f7-46fc-9ba2-97ee183ba1ad">

```
```line1 
line2```
```
is the markdown for code block shown below. So, ` ```line1``` ` will be displayed on header, right?
<img width="82" alt="Screenshot 2023-08-02 at 13 21 13" src="https://github.com/Expensify/App/assets/25876548/4571b1df-af4f-4628-912d-46eda7e2fa3c">

**Comment by eh2077** [comment] 2023-08-02 08:37
Or just display the first line without the ending backticks, like ` ```line1 `

**Comment by flaviadefaria** [comment] 2023-08-02 14:02
Hmm you're raising some good examples @sobitneupane. Let me quickly take this back to Slack as my view personally was that we didn't display markdown in the thread title but others thought differently, so I want to double-check.

**Comment by flaviadefaria** [comment] 2023-08-03 17:54
@sobitneupane I confirmed in Slack that we want the markdown to always display as markdown. Our design should be that you see the exact message in the header that you created. 

Regarding # highlighted it was mentioned that it isn’t an officially supported markdown feature. It’s actually some shortcut for doing another hidden action in the app. So we should ignore the markdown in this case. The one exception would be `# highlighted`

So going back to your examples:

1. `# highlighted` is the markdown for highlighted text shown below. 
<img width="152" alt="Screenshot 2023-08-02 at 13 22 24" src="https://github.com/Expensify/App/assets/25876548/6ac8f0c7-d9f7-46fc-9ba2-97ee183ba1ad">

On the thread header this should display as  "highlighted" without any markdown.

2. 
```
line1 
line2
```


On the thread header this should display as 
```
line1
``` 

Does this make more sense now? Any other questions?

**Comment by eh2077** [comment] 2023-08-04 00:45
@flaviadefaria Why don't we just format the thread title like what we do with LHN message? By doing so, it will be easier to implement and more convenient through the App. Will you take this into consideration?

**Comment by sobitneupane** [comment] 2023-08-04 07:16
Thanks @flaviadefaria 

Thanks for the proposals everyone.

Please do update your proposals based on this [expected output](https://github.com/Expensify/App/issues/22832#issuecomment-1664397154) and let me know.

**Comment by Habben101** [comment] 2023-08-07 01:23
@sobitneupane @flaviadefaria I've updated my [proposal](https://github.com/Expensify/App/issues/22832#issuecomment-1652853617) to reflect the [expected outcome](https://github.com/Expensify/App/issues/22832#issuecomment-1664397154). Can you please check it out?

**Comment by flaviadefaria** [comment] 2023-08-07 12:27
@sobitneupane should review @Habben101's proposal soon.

**Comment by sobitneupane** [comment] 2023-08-09 10:15
Thanks everyone for the patience.

@tienifr overall your proposal looks good to me.

Can we see some samples of thread header? As it is a new feature, I am not sure how it looks.

**Comment by flaviadefaria** [comment] 2023-08-10 09:48
We're nearly there Melvin!

**Comment by sobitneupane** [comment] 2023-08-14 11:51
Thanks @tienifr.

[Proposal](https://github.com/Expensify/App/issues/22832#issuecomment-1652795468) from @tienifr looks good to me.

Regarding [code fence](https://github.com/Expensify/App/issues/22832#issuecomment-1673980835), I think we should increase the height of header. We should also make sure everything looks good in mobile devices as well.

🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment] 2023-08-14 13:56
@tienifr Thanks for all the detailed examples in https://github.com/Expensify/App/issues/22832#issuecomment-1673980835

Let's go with your proposal 👍

**Comment by flaviadefaria** [comment] 2023-08-15 13:10
>IMO, we should render code fence as inline code in this case.

This makes sense to me.

**Comment by flaviadefaria** [comment] 2023-08-18 10:29
@mallenexpensify I'm heading OoO for a week so reassigning this to you in the meantime. Thanks!

**Comment by flaviadefaria** [comment] 2023-08-18 10:30
@tienifr I believe we're still waiting for your PR?

**Comment by mallenexpensify** [comment] 2023-09-05 02:36
Back to you @flaviadefaria as I'm off this week, thx

**Comment by sobitneupane** [comment] 2023-09-05 11:33
We are waiting for update from @tienifr in the PR.

**Comment by sobitneupane** [comment] 2023-09-18 12:42
@tienifr Please keep us updated. There is no update from last two weeks.

**Comment by flaviadefaria** [comment] 2023-09-26 10:11
3 weeks have passed, what's the latest here?

**Comment by flaviadefaria** [comment] 2023-10-12 10:49
@alexpensify I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by alexpensify** [comment] 2023-10-13 17:18
Thanks @flaviadefaria! I checked and it looks like this PR is moving forward.

**Comment by alexpensify** [comment] 2023-10-16 23:32
Daily Update: PR is under review

**Comment by alexpensify** [comment] 2023-10-18 22:00
@sobitneupane we need your help to review the PR, thanks!

**Comment by alexpensify** [comment] 2023-10-20 21:05
@sobitneupane - one more bump, we need your review here. If you are unable to help, please let me know and we will reassign the issue. If you need more time, please reply. Thanks!

**Comment by situchan** [comment] 2023-10-20 21:06
Sobit is OOO right now. Will be back next week

**Comment by alexpensify** [comment] 2023-10-20 21:07
Thanks @situchan for the update! We will wait, and leave this GH as is for now.

**Comment by alexpensify** [comment] 2023-10-23 16:05
@sobitneupane - I found the OOO message and think you are back online now. Let me know if we need to reassign this one or you will continue this review. Thanks!

**Comment by alexpensify** [comment] 2023-10-26 16:25
@sobitneupane any update here?

**Comment by alexpensify** [comment] 2023-10-30 23:47
@sobitneupane - did you get a chance to review?

**Comment by sobitneupane** [comment] 2023-11-01 06:40
@alexpensify PR is under review. I have requested few changes in here.

**Comment by alexpensify** [comment] 2023-11-01 18:34
🤦🏼 whoops, I forgot to check the PR. Thanks for the update!

**Comment by alexpensify** [comment] 2023-11-03 16:34
Daily Update: The PR is moving forward.

**Comment by alexpensify** [comment] 2023-11-07 00:18
Daily Update: PR requires an update

**Comment by alexpensify** [comment] 2023-11-15 01:40
Daily Update: Looks like the PR is still being worked to update the last points on feedback.

**Comment by alexpensify** [comment] 2023-11-16 20:44
Daily Update: There are some edits that are in the works.

**Comment by alexpensify** [comment] 2023-11-27 18:08
Catching up from being OOO, @tienifr any update on 3 and 4 mentioned in the PR?

**Comment by alexpensify** [comment] 2023-12-06 18:52
Daily Update: There is movement in the PR: https://github.com/Expensify/App/pull/24574 and I think 4 is moving forward.

**Comment by alexpensify** [comment] 2023-12-13 23:06
@tienifr how's it going here?

**Comment by alexpensify** [comment] 2023-12-18 23:50
@tienifr any update?

**Comment by alexpensify** [comment] 2023-12-20 23:59
No update, still waiting here.

**Comment by alexpensify** [comment] 2023-12-23 18:37
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by robertjchen** [comment] 2023-12-28 11:26
It looks like the PR is still in progress

**Comment by sobitneupane** [comment] 2023-12-29 05:00
@tienifr Any update?

**Comment by alexpensify** [comment] 2024-01-04 19:08
@tienifr any update here? Thank you!

**Comment by alexpensify** [comment] 2024-01-10 18:40
@tienifr any news here?

**Comment by alexpensify** [comment] 2024-01-17 18:32
@tienifr - any update on the two points?

**Comment by alexpensify** [comment] 2024-01-24 17:52
Thank you for the update!

**Comment by alexpensify** [comment] 2024-01-31 20:34
Weekly Update: PR is still in the works.

**Comment by alexpensify** [comment] 2024-02-09 18:10
@tienifr how's the PR update going?

**Comment by alexpensify** [comment] 2024-02-13 22:45
Weekly Update: Waiting for the updates from @tienifr

**Comment by sobitneupane** [comment] 2024-02-14 05:17
@tienifr Let's get this resolved asap. You are working on this issue from August. If you don't have time for this, please let us know.

**Comment by alexpensify** [comment] 2024-02-21 01:14
@tienifr - please keep us posted if you don't have time to address this PR. If no response in the next week, I will be reassigning and finding someone to work on point 4.

**Comment by alexpensify** [comment] 2024-02-27 22:35
@tienifr would it be best to split the 5th one into its own GH or can we not go live without the 5th point? Thanks for the update!

**Comment by alexpensify** [comment] 2024-02-27 23:56
Awesome, it sounds now we are waiting for the review from @sobitneupane. Thanks for the update @tienifr!

**Comment by alexpensify** [comment] 2024-03-05 22:50
@sobitneupane - any update on the required review here? Thanks!

**Comment by sobitneupane** [comment] 2024-03-07 13:22
The PR is under review. The changes look promising. I am planning not to block the PR for minor issues. We can work on the minor issues in another PR.

**Comment by alexpensify** [comment] 2024-03-12 21:53
@tienifr and @sobitneupane - we are so close to the finish line!

**Comment by robertjchen** [comment] 2024-03-18 05:54
Looks like we're almost there on the PR: https://github.com/Expensify/App/pull/24574

**Comment by robertjchen** [comment] 2024-04-01 03:32
Still in progress

**Comment by shawnborton** [comment] 2024-05-24 13:55
As I understand it, this feature request would add markup to the chat report header. I'd be curious to understand why we want to do that?

Now, I do agree with the idea of removing the markdown characters like the three ``` or > - but I feel like we should just strip that out and show plain text in the header as much as we can. It's the same reason why we just show [Attachment] in the header and not the actual image. 

Curious if others agree with me. Added discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1716558840149929?thread_ts=1689676940.686919&cid=C01SKUP7QR0).

**Comment by alexpensify** [comment] 2024-06-04 22:24
Weekly Update: I'm going to follow up in the Slack thread to confirm the next steps here.

**Comment by sobitneupane** [comment] 2024-07-16 07:17
Any update @alexpensify ?

**Comment by alexpensify** [comment] 2024-07-19 23:16
@robertjchen reopening, can we get your feedback if you agree to keep this open? Thanks!

**Comment by sobitneupane** [comment] 2024-07-23 08:18
Thanks for the proposal @tienifr.

[Proposal](https://github.com/Expensify/App/issues/22832#issuecomment-2237780057) from @tienifr looks good.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment] 2024-07-25 15:44
Waiting for @robertjchen's response on https://github.com/Expensify/App/issues/22832#issuecomment-2240595251

**Comment by robertjchen** [comment] 2024-07-26 02:42
makes sense to me- let's try that

**Comment by alexpensify** [comment] 2024-07-29 18:57
@robertjchen - thanks, we need you to approve the proposal to carry on with the next steps. Thanks!

**Comment by robertjchen** [comment] 2024-07-29 19:01
Yep, approved above! https://github.com/Expensify/App/issues/22832#issuecomment-2251858552

**Comment by alexpensify** [comment] 2024-07-29 19:20
Whoops, I missed the automation ran many months ago. Ok, @tienifr keep us posted when the PR is ready for review. Thanks!

**Comment by alexpensify** [comment] 2024-07-29 19:55
Thanks! We will wait for it to go through the automation process to production.

**Comment by alexpensify** [comment] 2024-08-07 20:34
I'm working on the payment process and will complete it tomorrow.

**Comment by alexpensify** [comment] 2024-08-11 21:56
Payouts due: 2024-08-07

- [ ] Reporter: $250 @dhanashree-sawant
- [ ] Contributor: $1000 @sobitneupane 
- [ ] Contributor+: $1000 @tienifr 

Upwork job is [here](https://www.upwork.com/jobs/~010cf4dbd8dbc4da67).

**Comment by alexpensify** [comment] 2024-08-12 19:22
Closing - I've completed the process in Upwork. @sobitneupane, please submit a request in Chat. Thanks!

**Closed by alexpensify** 2024-08-12 19:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Not a priority, Bug

**Comment by garrettmknight** [comment] 2024-09-02 17:34
$1000 approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/22832#issuecomment-2282901816).
