### ISSUE TITLE
[$500] Profile- No error message when the image is bigger that the required pixel limit

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30904] opened 2023-11-06 10:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.91-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** @

## Action Performed:
1. Open test website https://staging.new.expensify.com/
2. Open Settings
3. Click on Profile
4. Click on the avatar
5. Click on the avatar upload icon and upload an image bigger than the required pixel limit of 2048px

## Expected Result:
An error message indicating that the image is bigger than the required pixel limit.

## Actual Result:
The photo is uploaded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6253328_1698413707559!kUDQAHNkV0](https://github.com/Expensify/App/assets/115492554/8a2b96a1-d6be-436f-a8cd-c519659b0d20)

![Bug6253328_1698796742966!4000](https://github.com/Expensify/App/assets/115492554/1eb1d003-65f2-4e61-a5e1-b59128c5c18b)

https://github.com/Expensify/App/assets/115492554/8f4e71c3-c14a-42f4-a44d-9764e64f442a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120d1355064b5ee16</li>
        <li>Upwork Job ID: 1721476110933917696</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by mpiniarski** [comment] 2023-11-06 10:40
The limit contraint set in codebase is 4096, not 2048px
<img width="589" alt="image" src="https://github.com/Expensify/App/assets/11861292/f207b4bc-d123-4d98-bbd9-aa939cfaeaeb">

**Comment by jayeshmangwani** [comment] 2023-11-06 10:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No error message when the image is bigger that the required pixel

### What is the root cause of that problem?
we are using the 4096 pixel value from CONST file for width and height and on error message we are showing `Please upload an image larger than 80x80 pixels and smaller than 2048x2048 pixels.`

```
    AVATAR_MAX_WIDTH_PX: 4096,
    AVATAR_MAX_HEIGHT_PX: 4096,
```
<img width="395" alt="Screenshot 2023-11-06 at 4 11 08 PM" src="https://github.com/Expensify/App/assets/35371050/e372e39b-26c8-4e3e-881a-9039341f0705">


### What changes do you think we should make in order to solve the problem?
either we should change the `AVATAR_MAX_WIDTH_PX` and `AVATAR_MAX_HEIGHT_PX` value to 2048 or we should update the error message to `Please upload an image larger than 80x80 pixels and smaller than 4096x4096 pixels.`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mpiniarski** [comment] 2023-11-06 12:08
@parasharrajat if the change will be required, please note, that my proposal was the first to not only state the issue but also propose the solution. The proposal above mine was edited after that.

**Comment by jayeshmangwani** [comment] 2023-11-06 18:04
> Hey everyone, it is strictly against contribution guidelines to post duplicate proposals.

@parasharrajat I can see you have a thumbs down on my proposal; if the reason is duplication, then I want to say I am the first who proposed a complete solution at the time of commenting, and the other two above my comment were edited after my comment. Let me attach an image to you then you will get the idea. 
<img width="424" alt="Screenshot 2023-11-06 at 4 22 23 PM" src="https://github.com/Expensify/App/assets/35371050/20084adf-1334-417f-b13c-1181825ecafb">

**Comment by joekaufmanexpensify** [comment] 2023-11-06 21:05
Catching up on this now. @parasharrajat looking at your comment [here](https://github.com/Expensify/App/issues/30904#issuecomment-1794546420), you mean whether we want to allow images larger than 2048px? 

If so, I don't personally see a reason why we wouldn't. IMO, we can probably close this one. Doesn't feel like a bug to me.

**Comment by NisargDeveloper** [comment] 2023-11-07 01:46
Hey are you still searching for person to resolve the issue?. I can help you. Let me know if I need to post the proposal

**Comment by jayeshmangwani** [comment] 2023-11-07 09:54
@parasharrajat @joekaufmanexpensify  We can close this because 4096 pixel for max width/height was added intentionality, more context here https://github.com/Expensify/App/pull/13899#discussion_r1060133519

This issue is created because we have added the wrong resolution for this TestRail [Profile - Modify User Avatar](https://expensify.testrail.io/index.php?/cases/view/1971123) in this [issue](https://github.com/Expensify/App/issues/13006#issuecomment-1381247615), On first step we added `Save an image that is between 80px and 2048px`, so instead we should use this line`Save an image that is between 80px and 4096px`,we can update this line to TestRail and close this issue

**Comment by joekaufmanexpensify** [comment] 2023-11-07 14:35
I created an issue for applause to update this regression test. Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-11-07 14:35 UTC
Labels: External, Daily, Help Wanted, Bug
