### ISSUE TITLE
Chat - App crashes after opening image preview and tapping back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34017] opened 2024-01-05 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to the chat where you have sent the PDF file
2. Send any image
3. Tap on the image preview
4. Tap on the back button

## Expected Result:
User should be taken to the chat page without any issues

## Actual Result:
The app crashes after tapping on back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e7dd93f-42fc-4b96-84e2-40eced01371c

[Bug6332887_1704435756625!LARGE_PDF_FILE.pdf](https://github.com/Expensify/App/files/13841763/Bug6332887_1704435756625.LARGE_PDF_FILE.pdf)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-05 14:33
regression from #33561

![Simulator Screenshot - iPhone 15 - 2024-01-05 at 20 32 53](https://github.com/Expensify/App/assets/108292595/15790796-bd13-4554-9ea5-128bedba825c)

**Comment by situchan** [comment] 2024-01-05 14:37
upstream issue: https://github.com/wonday/react-native-pdf/issues/796

@aldo-expensify I suggest to downgrade pdf version for now, rather than any patch.
We can bump again once this is fixed in upstream.

**Comment by marcaaron** [comment] 2024-01-05 23:56
Let's close this as a dupe of https://github.com/Expensify/App/issues/34047

**Closed by marcaaron** 2024-01-05 23:56 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
