### ISSUE TITLE
Web - Search string in WorkspaceMembersPage is lost when moving to another page and coming back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22535] opened 2023-07-09 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on workspaces
3. Click on a workspace
4. Click on Members
5. Search for a string, click on invite.
9. Click back and find that search field is empty.

## Expected Result:
Search field should persist when navigating back to Members page from Invite page

## Actual Result:
Search field becomes empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/244f9f7c-e2fd-4cd6-94a7-b4bbf05d28d3

https://github.com/Expensify/App/assets/93399543/39e5d88c-a387-40d7-ad42-1e9e83cdcd16

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688896241730799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-09 19:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Search string is lost when clicking on Invite members from `WorkspaceMembersPage` and coming back to `WorkspaceMembersPage`
### What is the root cause of that problem?
When we are navgiating to Invite page, we are setting `searchValue` as `''` in `WorkspaceMembersPage`
```
const inviteUser = () => {
        setSearchValue('');
```
so it is lost.
### What changes do you think we should make in order to solve the problem?
We should remove the `setSearchValue` line above
### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-07-10 12:42
This feels like a dupe of https://github.com/Expensify/App/issues/22534

So I think we should just close this one out.

**Comment by isabelastisser** [comment] 2023-07-10 12:56
dupe, closing!

**Closed by isabelastisser** 2023-07-10 12:56 UTC
Labels: Daily, NewFeature, Bug
