### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] “Book a call” option is not there in Concierge.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45036] opened 2024-07-09 02:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ShridharGoel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720464131738029

## Action Performed:

1. Go to concierge chat.
2.  Click on the header to open profile page.

## Expected Result:
“Book a call” option should be there.
## Actual Result:
“Book a call” option is not there.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/503a37fa-d682-46a5-8e63-32ceeb25f78b

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b054cf89e8b9e03</li>
        <li>Upwork Job ID: 1810634822789186398</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 103045098</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment] 2024-07-09 03:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
“Book a call” option is not there.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/ProfilePage.tsx#L285-L288

The `isConcierge` condition is false. Because in the Concierge report, there are two participants (the current user and concierge) 

https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/libs/ReportUtils.ts#L1046-L1049

This condition return false
### What changes do you think we should make in order to solve the problem?
Update to `participantAccountIDs.length === 2`




### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment] 2024-07-09 11:20
@ShridharGoel yeah you have first dibs, however, can you please also link what caused this regression? Either the `isConciergeChatReport` is not used for anything very important or its been messing around with stuff for a while now

**Comment by mountiny** [comment] 2024-07-09 11:20
Sorry @nkdengineer, [ShridharGoel](https://github.com/ShridharGoel) has reported this issue in Slack and got rights for first dibs, not sure how to make this clearly signalled so you would not have to spend your time on this

**Comment by nkdengineer** [comment] 2024-07-09 11:33
@mountiny My proposal and @ShridharGoel's proposal are different. Should we wait the C+ member evaluate proposals?

**Comment by jayeshmangwani** [comment] 2024-07-09 11:37
> Should we wait the C+ member evaluate proposals?

@nkdengineer It looks like @mountiny  has already assigned issue to @ShridharGoel 🙂

**Comment by jayeshmangwani** [comment] 2024-07-09 14:31
@ShridharGoel @nkdengineer  Though a contributor has been selected for the issue, I am curious about what caused the change in the length of the report participants. Previously, it only used to contain the Concierge ID, but now it also includes the user ID.

**Comment by mountiny** [comment] 2024-07-09 14:41
@ShridharGoel can you please link to specific lines causing this issue in the PR you have provided? thanks!

Also yeah curious if we can find what changed the behaviour in how many participants per reports we send

**Comment by MitchExpensify** [comment] 2024-07-16 20:08
Reassigning while I'm leave 🙇

**Comment by jayeshmangwani** [comment] 2024-07-17 19:20
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44068
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44068#discussion_r1670957767
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open the Expensify app and log in.
2. Go to Concierge chat.
3. Click on the header to open profile page.
4. Verify that we can see "Book a call" option

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-07-26 02:05
Payment summary:

 - Contributor: @ShridharGoel $250 
 - Reviewer: @jayeshmangwani $250

**Comment by JmillsExpensify** [comment] 2024-07-26 02:09
Contributor paid via Upwork and regression test created. Closing this issue! @jayeshmangwani please submit an expense via NewDot.

**Closed** 2024-07-26 02:09 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2024-08-05 04:56
Requested as per https://github.com/Expensify/App/issues/45036#issuecomment-2251830433

**Comment by mallenexpensify** [comment] 2024-08-06 23:14
Contributor: @ShridharGoel paid $250 via Upwork
Reviewer: @jayeshmangwani owed $250 via NewDot

**Comment by JmillsExpensify** [comment] 2024-08-06 23:43
$250 approved for @jayeshmangwani
