### ISSUE TITLE
[$250] Task – App crashes when click on assignee in existing task

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49514] opened 2024-09-20 08:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4989792
**Email or phone of affected tester (no customers):** applausetester+jpcategory_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task without assignee
5. Open task details and click on assignee

## Expected Result:
Assignee list opens

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[2009.txt](https://github.com/user-attachments/files/17072517/2009.txt)

https://github.com/user-attachments/assets/47f83d83-f3db-4fed-94aa-6cf321ed526d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838194512143553982</li>
        <li>Upwork Job ID: 1838194512143553982</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104086587</li>
<li>nkdengineer | Contributor | 104086588</li>
</ul></li>
    </ul>
</details>

**Comment by huult** [comment] 2024-09-20 09:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when click on assignee in existing task

### What is the root cause of that problem?
Use 'report' before initialization
<img width="1112" alt="Screenshot 2024-09-20 at 16 00 15" src="https://github.com/user-attachments/assets/b47e0c3c-1c12-49e0-85e8-23d4befec921">

### What changes do you think we should make in order to solve the problem?
Delay using the report until the report is complete.

```diff
// .src/pages/tasks/TaskAssigneeSelectorModal.tsx#L127
+       InteractionManager.runAfterInteractions(() => {
+          requestAnimationFrame(() => {
                if (report && !ReportUtils.isTaskReport(report)) {
                    Navigation.isNavigationReady().then(() => {
                        Navigation.dismissModal(report.reportID);
                    });
                }
+           });
+        });
```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-09-20 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes

### What is the root cause of that problem?
The report is used before it's initialize


https://github.com/Expensify/App/blob/4c9a3fbac779689ec6abade55df8234b1b859e51/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L123-L129
### What changes do you think we should make in order to solve the problem?
Update this to get the report data from `reports` to check it's task report or not

```
const report: OnyxEntry<Report> = useMemo(() => {
    if (!route.params?.reportID) {
        return;
    }
    const reportOnyx = reports?.[`${ONYXKEYS.COLLECTION.REPORT}${route.params?.reportID}`];
    if (reportOnyx && !ReportUtils.isTaskReport(reportOnyx)) {
        Navigation.isNavigationReady().then(() => {
            Navigation.dismissModal(reportOnyx.reportID);
        });
    }
    return reports?.[`${ONYXKEYS.COLLECTION.REPORT}${route.params?.reportID}`];
}, [reports, route]);
```
### What alternative solutions did you explore? (Optional)

Or we can move the navigate logic to another `useEffect`

```
const report: OnyxEntry<Report> = useMemo(() => {
    if (!route.params?.reportID) {
        return;
    }
    return reports?.[`${ONYXKEYS.COLLECTION.REPORT}${route.params?.reportID}`];
}, [reports, route]);

useEffect(() => {
    if (report && !ReportUtils.isTaskReport(report)) {
        Navigation.isNavigationReady().then(() => {
            Navigation.dismissModal(report.reportID);
        });
    }
}, [report]);
```

**Comment by flodnv** [comment] 2024-09-20 09:54
Why did this just start happening upon this deploy? What PR caused this?

**Comment by nkdengineer** [comment] 2024-09-20 11:00
@flodnv Maybe it is caused by https://github.com/Expensify/App/pull/48325. I tried to revert to the latest commit in production and install node-module again and the bug didn't happen. The bug started happening when I reverted to the first different between production and staging and re-install node-module again.

<img width="1512" alt="Screenshot 2024-09-20 at 17 57 53" src="https://github.com/user-attachments/assets/820bb3b5-f30a-4fab-9675-92ca1b61a0c4">

<img width="1512" alt="Screenshot 2024-09-20 at 17 58 13" src="https://github.com/user-attachments/assets/c9141019-53c3-415f-b2f1-b08de9d74552">

**Comment by grgia** [comment] 2024-09-20 14:23
Updated https://github.com/Expensify/App/pull/49241 cc @luacmartins

**Comment by flodnv** [comment] 2024-09-23 11:11
> @flodnv Maybe it is caused by https://github.com/Expensify/App/pull/48325. I tried to revert to the latest commit in production and install node-module again and the bug didn't happen. The bug started happening when I reverted to the first different between production and staging and re-install node-module again.

Thanks @nkdengineer. @rojiphil @BrtqKr can you please check if https://github.com/Expensify/App/pull/48325 caused this?

**Comment by BrtqKr** [comment] 2024-09-23 12:25
@flodnv, I don't think this would be related. Seems like accessing report from task is making this work 

```
    const report: OnyxEntry<Report> = useMemo(() => {
        if (!route.params?.reportID) {
            return;
        }
        if (task?.report && !ReportUtils.isTaskReport(task?.report)) {
            Navigation.isNavigationReady().then(() => {
                Navigation.dismissModal(task?.report?.reportID);
            });
        }
        return reports?.[`${ONYXKEYS.COLLECTION.REPORT}${route.params?.reportID}`];
    }, [reports, route]);
```

currently, the memo is accessing itself and it seems to be the reason, why this bug is occurring, but this is quite surprising because it's been working like this for a while somehow

```
    const report: OnyxEntry<Report> = useMemo(() => {
        if (!route.params?.reportID) {
            return;
        }
        if (report && !ReportUtils.isTaskReport(report)) {
            Navigation.isNavigationReady().then(() => {
                Navigation.dismissModal(report.reportID);
            });
        }
        return reports?.[`${ONYXKEYS.COLLECTION.REPORT}${route.params?.reportID}`];
    }, [reports, route]);
```

**Comment by nkdengineer** [comment] 2024-09-23 12:32
Thanks, will raise the PR soon.

**Comment by nkdengineer** [comment] 2024-09-23 14:16
@jjcoffee The PR is [here](https://github.com/Expensify/App/pull/49604)

cc @flodnv

**Comment by flodnv** [comment] 2024-09-23 15:03
Thanks!

**Comment by alexpensify** [comment] 2024-09-23 17:22
Awesome, now we wait for this one to go to Prouduction.

**Comment by isagoico** [comment] 2024-09-23 19:39
Retest was a pass 🎉 

https://github.com/user-attachments/assets/e4cc84e2-bc26-4a48-b998-fb16cf179231

Checking it off the list.

**Comment by alexpensify** [comment] 2024-09-30 22:15
Flagging that automation failed, and it was deployed to production on 09-24.

**Comment by alexpensify** [comment] 2024-10-02 21:49
Ugh, automation failed and the payment date should have been yesterday. I'll work on the payment process tomorrow.

**Comment by jjcoffee** [comment] 2024-10-03 07:47
- The PR that introduced the bug has been identified. Link to the PR: I wasn't able to identify an offending PR
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes - if one doesn't already exist**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open any chat
2. Create a task without an assignee
3. Open task details and click on assignee
4. Verify that the assignee page appears

Do we agree 👍 or 👎

**Comment by luacmartins** [comment] 2024-10-03 13:52
I think this will be caught during regular regression tests, since we have many tests on tasks.

**Comment by alexpensify** [comment] 2024-10-04 21:55
Payouts due: 10-01-2024

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @jjcoffee 

Upwork job is [here](https://www.upwork.com/jobs/~021838194512143553982).

**Comment by alexpensify** [comment] 2024-10-04 22:18
Closing - I believe that I sent the payment via Upwork, but something looks off in Upwork. Please reply if you didn't get the payment and I'll fund the new job I sent your way. I'll return later to complete the regression test.

**Comment by jjcoffee** [comment] 2024-10-07 07:47
@alexpensify I didn't receive any payment, just the notification that the contract has ended and weirdly another about accepting an offer (I've accepted this).

**Comment by nkdengineer** [comment] 2024-10-07 15:39
@alexpensify Same for me, the job just closed without payment. I accepted the new 2nd offer though, it can be paid out there.

**Comment by alexpensify** [comment] 2024-10-07 16:45
Thanks for these updates! There is an issue an Upwork that is being investigated to address the payment process. I'm going to hold until there is a fix. Convo: https://expensify.slack.com/archives/C01GTK53T8Q/p1728319262830679

**Comment by alexpensify** [comment] 2024-10-08 18:04
@jjcoffee and @nkdengineer, our team figured out the Upwork bug, and I tried to complete the payment via another payment path in Upwork. Their support team is working on a permanent fix for the bug. I'd really appreciate it if you could confirm today's payment sent successfully under the new contract. Thanks!

**Closed by alexpensify** 2024-10-08 18:04 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by nkdengineer** [comment] 2024-10-09 01:18
@alexpensify Yes it was sent for me 💯 Thanks!

**Comment by jjcoffee** [comment] 2024-10-09 07:27
Me too, thank you!

**Comment by alexpensify** [comment] 2024-10-09 15:06
Awesome, thanks for hanging in there with me. This bug is a wild one on the Upwork side.
