### ISSUE TITLE
[On Hold App #38864] [$500] Distance - Distance is saved when editor is dismissed without saving the changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35173] opened 2024-01-25 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Distance request page in workspace chat.
2. Enter addresses and proceed to confirmation page.
3. Click Distance.
4. Edit any waypoint.
5. Click back button instead of saving it.
6. Click Distance.

## Expected Result:
The edited distance will not be saved since the editor is dismissed without hitting the save button.

## Actual Result:
The edited distance is saved when the editor is dismissed without hitting the save button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/de9eaa4c-80e6-45b9-8a39-62fc1b22e181

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016908a5fd4c8a84aa</li>
        <li>Upwork Job ID: 1750593008776929280</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28123800</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-25 18:55
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by FitseTLT** [comment] 2024-01-25 19:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance is saved when editor is dismissed without saving the changes

### What is the root cause of that problem?
Currently we save the waypoint to draft tranaction so whether or not user clicks save it will update the changes
https://github.com/Expensify/App/blob/83a7535cf5b691fc8965607327d651d10a283bd8/src/pages/iou/request/step/IOURequestStepWaypoint.js#L138-L139
### What changes do you think we should make in order to solve the problem?

In `IOURequestStepWaypoint` We should save the initial value and then we need to revert back to the initial value on unmount or back button press
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-01-26 08:05
I'm happy to take this as C+

**Comment by alexpensify** [comment] 2024-01-26 15:17
Thank you @ntdiary for this update! @DylanDylann you have been assigned, and please keep us posted on the best proposal here.

**Comment by alexpensify** [comment] 2024-01-26 15:20
Ok, looks like the automation got it wrong here. Flagging that @DylanDylann will be acting as the C+ here.

**Comment by dylanexpensify** [comment] 2024-01-26 15:51
@DylanDylann is a C+! 🎉

**Comment by greg-schroeder** [comment] 2024-01-26 20:15
I think this is more Wave 5, no @dylanexpensify? considering it's distance requests

**Comment by DylanDylann** [comment] 2024-01-29 08:12
I think we should hold this issue until https://github.com/Expensify/App/issues/34610 is done

**Comment by alexpensify** [comment] 2024-01-29 14:49
Noted, I updated this one as on hold.

**Comment by alexpensify** [comment] 2024-02-06 00:38
Weekly update: On Hold

**Comment by alexpensify** [comment] 2024-02-13 22:39
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2024-02-21 01:09
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2024-02-27 22:28
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2024-03-05 22:39
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2024-03-12 21:51
Weekly Update: Still on Hold

**Comment by alexpensify** [comment] 2024-03-19 22:20
Weekly Update: It looks like the GH we are on hold for is moving forward

**Comment by alexpensify** [comment] 2024-03-25 17:31
Thanks @dukenv0307 for the update! 

@DylanDylann can you please review the recent proposal and identify if it will fix this issue? Thanks!

**Comment by alexpensify** [comment] 2024-03-26 23:35
Moving this one back to Daily to carry on here.

**Comment by DylanDylann** [comment] 2024-03-27 07:42
This issue can be resolved [here](https://github.com/Expensify/App/pull/38911)

**Comment by DylanDylann** [comment] 2024-03-27 09:28
@alexpensify Although https://github.com/Expensify/App/issues/34610 is done, it caused a [regression](https://github.com/Expensify/App/issues/38864). After checking I see that we need to resolve this regression first, then we can process with this one

**Comment by alexpensify** [comment] 2024-03-27 20:02
Got it, thanks for flagging it. I missed the regression notice.

**Comment by alexpensify** [comment] 2024-04-02 21:53
Weekly Update: On hold for https://github.com/Expensify/App/issues/38864

**Comment by alexpensify** [comment] 2024-04-09 22:15
Weekly Update: Still on hold for https://github.com/Expensify/App/issues/38864

**Comment by DylanDylann** [comment] 2024-04-11 14:07
https://github.com/Expensify/App/pull/39144 is merged. This issue is fixed

**Comment by alexpensify** [comment] 2024-04-16 23:04
Thanks. Based on this feedback, we will close this one.

**Closed by alexpensify** 2024-04-16 23:04 UTC
Labels: External, Weekly, Help Wanted, Bug
