### ISSUE TITLE
Request money - Scroll Issue When Navigating Back to the Amount After Selecting a User and Revisiting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34285] opened 2024-01-10 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in to staging Expensify
2. FAB > Request Money
3.  Add amount
4.  Select user or workspace
5. Navigate back to the amount
6. Navigate again to the user. Observe that the page has been scrolled

## Expected Result:
The page should not scroll by itself when navigating back to the amount after selecting a user and then navigating again to the selected user."

## Actual Result:
The page scrolls by itself when navigating back to the amount after selecting a user and then navigating again to the selected user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ab4c43fa-bd18-4406-9ba8-f793b5fa5f80

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2024-01-11 04:31
I wonder if this is also fixed in https://github.com/Expensify/App/pull/34244

**Comment by situchan** [comment] 2024-01-11 04:33
> I wonder if this is also fixed in #34244

I don't think so. It's different bug. BaseInvertedFlatList is only used in report screen

**Comment by thienlnam** [comment] 2024-01-11 04:35
Actually, I can't seem the reproduce the issue on staging anymore

**Comment by situchan** [comment] 2024-01-11 04:36
I am not able to reproduce. This maybe fixed in #34267

**Comment by thienlnam** [comment] 2024-01-11 04:36
https://github.com/Expensify/App/assets/30609178/fb9844e3-85a6-444c-9e72-669369e24487

**Closed by thienlnam** 2024-01-11 04:36 UTC
Labels: DeployBlockerCash, Engineering, Hourly
