### ISSUE TITLE
Adds one more space in LHN if typed user's own email address along with a text message at front

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18539] opened 2023-05-07 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat on web chrome
2. Type in any message followed by mention @your_own_account's_email (For example: Hi. This is @youremail)
3. Send message
4. Notice that on LHN, it has added one more space before 'you'

## Expected Result:
 One more space should not be added in LHN if typed user's own email address along with a text message at front
## Actual Result:
 Adds one more space in LHN if typed user's own email address along with a text message at front

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236682675-d25d32f4-aafb-4542-bc3c-e945eb600a47.mp4

https://user-images.githubusercontent.com/43996225/236682689-d8ee35b3-6eb7-4f35-9f1c-4c58a89979ee.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683349919072659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2023-05-09 15:55
taking to the slack thread

**Comment by priya-zha** [comment] 2023-05-09 16:17
@kevinksullivan you need to have @ in front of your own email, then it will be reproduced. For example: **@your_expensify_email@gmail.com**

Can you try it once more?

Thanks

**Comment by kevinksullivan** [comment] 2023-05-11 23:12
I reproduced but still discussing what should happen in slack

https://expensify.slack.com/archives/C049HHMV9SM/p1683846735894549?thread_ts=1683349919.072659&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-05-16 00:48
bumped

https://expensify.slack.com/archives/C049HHMV9SM/p1684198102242459?thread_ts=1683349919.072659&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-05-23 18:54
No, melv. Still discussing in slack.

**Comment by kevinksullivan** [comment] 2023-05-23 19:05
closing out since this was likely fixed by https://github.com/Expensify/Web-Expensify/pull/37521 . If it is not fixed after this deploys to prod, please let me know!

**Closed by kevinksullivan** 2023-05-23 19:05 UTC
Labels: Daily, Bug
