### ISSUE TITLE
[$250] Chat-Secondary contact is displayed when primary gmail contact is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51968] opened 2024-11-04 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace
3. Tap members
4. Invite a gmail user with primary email id (who has secondary contact)
5. Go to LHN
6. Tap self DM
7. Enter @[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
and select particular user from suggestion list

## Expected Result:
Secondary contact must not be displayed when primary gmail contact is selected

## Actual Result:
Secondary contact is displayed when primary gmail contact is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/feac9d23-38b4-40e7-9080-a73c1b60c13e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854219940520198743</li>
        <li>Upwork Job ID: 1854219940520198743</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by trjExpensify** [comment] 2024-11-06 17:50
This kind of mention bug isn't really a priority right now, so I'm going to drop the price and set it as `LOW`. I was tempted to close it, but it isn't great to show someone's secondary login when you didn't select it.

**Comment by FitseTLT** [comment] 2024-11-07 21:48
Couldn't reproduce

**Comment by jjcoffee** [comment] 2024-11-12 09:37
@trjExpensify I think we need to ask for retest here.

**Comment by trjExpensify** [comment] 2024-11-13 02:42
Done! @lanitochka17 can we get a retest, please?

**Comment by lanitochka17** [comment] 2024-11-13 14:00
Issue is not reproducible on the latest build 9.0.61-0

https://github.com/user-attachments/assets/793a4af5-0020-4219-bc6e-59fefd9a6fcc

**Comment by trjExpensify** [comment] 2024-11-13 14:12
Great, closing then!

**Closed by trjExpensify** 2024-11-13 14:12 UTC
Labels: External, Weekly, Help Wanted, Bug, retest-weekly
