### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Quick action - Split expense is created in a new group chat when splitting a second time from the same group from global creation

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40745] opened 2024-04-23 02:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Manual.
3. Create manual split expense with two users.
4. Go to FAB
5. Click Split expense under Quick action.
6. Create another split expense.

## Expected Result:
The new split expense will be created in the same group chat (production behavior).

## Actual Result:
The new split expense is created in a new group chat.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/dab5aa85-bca1-4b58-adf6-a84390f6d92f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012731ac59083f0155</li>
        <li>Upwork Job ID: 1782697338779648000</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-04-23 03:00
@MonilBhavsar FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-04-23 03:01
We think this bug might be related to #vip-split

**Comment by c3024** [comment] 2024-04-23 03:08
Is this working correctly on production?

**Comment by kavimuru** [comment] 2024-04-23 03:38
On prod, the split is added to the same group chat. On staging, it is added to a new group chat.

**Comment by mountiny** [comment] 2024-04-23 09:05
@Gonals can you please have a look? Seems like we might not be saving the correct reportID to the NVP in this case

**Comment by MonilBhavsar** [comment] 2024-04-23 09:32
This does seem like a server side issue to me

**Comment by MonilBhavsar** [comment] 2024-04-23 11:48
I was wrong. QuickAction NVP seems correct, so client side issue

**Comment by nkdengineer** [comment] 2024-04-23 12:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new split expense is created in a new group chat.

### What is the root cause of that problem?
When we create split bill via QAB, we're calling `splitBillAndOpenReport` which will always create a new optimistic report because in this function, we call `createSplitsAndOnyxData` with `existingSplitChatReportID` param as empty

https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/libs/actions/IOU.ts#L3597

https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/pages/iou/request/step/IOURequestStepAmount.tsx#L186
### What changes do you think we should make in order to solve the problem?
In the case we create a split bill via QAB that means the report already exists we should call `splitBill` function which already handle this case and also navigate to the correctly report after creating.


### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-23 12:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new split expense is created in a new group chat.

### What is the root cause of that problem?
When we create split bill via QAB, we're calling `splitBillAndOpenReport` which will always create a new optimistic report because in this function, we call `createSplitsAndOnyxData` with `existingSplitChatReportID` param as empty

https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/libs/actions/IOU.ts#L3597

https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/pages/iou/request/step/IOURequestStepAmount.tsx#L186
### What changes do you think we should make in order to solve the problem?
In the case we create a split bill via QAB that means the report already exists we should call `splitBill` function as the same [here](https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L316) which already handle this case and also navigate to the correctly report after creating.


https://github.com/Expensify/App/blob/944751fcec525ece0da16a6a4efd80ad8ab4ff8c/src/pages/iou/request/step/IOURequestStepAmount.tsx#L186

We should fix the same for `IOURequestStepScan` and `IOURequestStepDistance` page
### What alternative solutions did you explore? (Optional)
NA

**Comment by Gonals** [comment] 2024-04-23 12:24
> @Gonals can you please have a look? Seems like we might not be saving the correct reportID to the NVP in this case

I noticed this bug, but it didn't have anything to do with the QAB (when I tested). It happened for non-QAB flows too 🤷 

I'll test again in a bit

**Comment by Gonals** [comment] 2024-04-23 12:29
Yep. This happens whenever you try to split again between the same group, QAB flow or not. Not a blocker

**Comment by MonilBhavsar** [comment] 2024-04-23 12:32
Thank you for looking Alberto!

@nkdengineer can you please confirm your proposal for all the split cases

**Comment by nkdengineer** [comment] 2024-04-23 15:26
> @nkdengineer can you please confirm your proposal for all the split cases

@MonilBhavsar Sure, the bug only happens when we create a split request with skipping the confirmation step (via QAB). So we only need to fix this case as I mentioned in my proposal.

**Comment by DylanDylann** [comment] 2024-04-23 15:50
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/40745#issuecomment-2072134577) looks good to me

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-04-25 05:42
@DylanDylann The PR is [here](https://github.com/Expensify/App/pull/40961).

**Comment by greg-schroeder** [comment] 2024-05-03 09:32
Payments made and job closed. @DylanDylann can you take care of the [checklist](https://github.com/Expensify/App/issues/40745#issuecomment-2080209266)? Thanks!

**Comment by DylanDylann** [comment] 2024-05-03 09:41
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39413
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39413#discussion_r1588976721
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Go to a group chat
2. Create a split bill in this group
3. Go FAB and click on quick action button
4. Create the split bill again
5. Verify that the split bill is created in the group chat above


Do we agree 👍 or 👎

**Comment by MonilBhavsar** [comment] 2024-05-06 10:52
Looks good, but we might have a regression here https://github.com/Expensify/App/pull/40961#issuecomment-2095565285

**Comment by nkdengineer** [comment] 2024-05-06 11:22
@MonilBhavsar I tested and it still works for me on the latest main.

**Comment by MonilBhavsar** [comment] 2024-05-08 13:09
>  tested and it still works for me on the latest main.

👍 We can close this after creating regression test

**Comment by greg-schroeder** [comment] 2024-05-09 05:44
Filing thing, thanks all!

**Closed by greg-schroeder** 2024-05-09 05:44 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
