### ISSUE TITLE
[$1000] Non-workspace members cannot see the correct workspace avatar

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#25869] opened 2023-08-24 17:43 UTC
If you are not a member of a workspace, yet you view a workspace #room, you see a fallback avatar instead of the custom avatar that is uploaded to the workspace.

<img width="374" alt="image" src="https://github.com/Expensify/App/assets/2319350/6e6fa97f-18ce-48fd-89ea-da7e12af0573">

Let's fix this so that all people who view a workspace can see the custom avatar, regardless if you are a member or not. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ac74c500e005abc</li>
        <li>Upwork Job ID: 1694776876261134336</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-08-24 17:48
JK, sounds like this won't be a problem for SaaStr.

**Comment by jeet-dhandha** [comment] 2023-08-24 18:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Issue is that workspace image is not shown for public rooms user which do not have access to workspace, even if custom image is set.

### What is the root cause of that problem?
- User don't have access to workspace policy and hence image is not shown.

### What changes do you think we should make in order to solve the problem?
- We can add `workspaceAvatar` key in `report` and then return it in `OpenReport`'s api response.
- Then we can use that in `getWorkspaceIcon` function of `ReportUtils.js` to get the image.

https://github.com/Expensify/App/blob/53c474356a6d3eb64012b84ed18e0cc44530a6e1/src/libs/ReportUtils.js#L920-L922

- Also in `getWorkspaceAvatar`.

https://github.com/Expensify/App/blob/53c474356a6d3eb64012b84ed18e0cc44530a6e1/src/libs/ReportUtils.js#L867-L870

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by dylanexpensify** [comment] 2023-08-25 17:32
@burczu mind reviewing proposal ^

**Comment by burczu** [comment] 2023-08-28 06:44
Hey @dylanexpensify! Sorry, I've missed this one - I'll review it today!

**Comment by burczu** [comment] 2023-08-28 09:16
@dylanexpensify - I've checked @jeet-dhandha proposal and from the code point of view I think it looks reasonable.

Unfortunately I couldn't check it myself because I have no idea how can i see the room of the workspace I'm not member of - could someone explain it to me?

Also, if we want to go with @jeet-dhandha proposal, we will need to amend API first, so I'm not sure how we handle such situations? Will we add the `Internal` label first and get back to it after the backend is ready?

**Comment by dylanexpensify** [comment] 2023-08-29 08:52
Hi @burczu! Thanks for the review! Let me check!

**Comment by dylanexpensify** [comment] 2023-08-29 11:27
@johnmlee101 mind confirming? 🙇‍♂️

**Comment by johnmlee101** [comment] 2023-08-30 20:40
Hmm, if we return `${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`, 'avatar'` from the backend in Onyx, is there any front-end changes required?

**Comment by dylanexpensify** [comment] 2023-08-31 08:59
Good point - @burczu I think John is right - mind confirming?

**Comment by jeet-dhandha** [comment] 2023-08-31 12:42
Doesn’t this mean user will have access to that policy even if user is not a member.

**Comment by johnmlee101** [comment] 2023-08-31 17:24
Workspace avatars for public rooms shouldn't be hidden, so no access to that policy is required in this case

**Comment by jeet-dhandha** [comment] 2023-08-31 18:19
@johnmlee101  
- We don't add `policy` for public rooms in the `allPolicies` for non-members of the workspace. Initially, I thought it would be okay to include avatar in the `report` but after some digging, I believe that returning 'avatar' in 'policy_${id}' should do the trick. This is because most access permission checks are based on the `role` so having `avatar` shouldn't cause any regression.

**Comment by dylanexpensify** [comment] 2023-09-04 10:17
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi!

**Comment by burczu** [comment] 2023-09-06 13:06
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by johnmlee101** [comment] 2023-09-08 03:30
I'm guessing we should migrate back over to `Internal` for this issue, I can take a look at resolving this soon

**Comment by dylanexpensify** [comment] 2023-09-11 10:28
Coming back from conference last week - updating today!

**Comment by johnmlee101** [comment] 2023-09-15 05:08
<img width="366" alt="image" src="https://github.com/Expensify/App/assets/5258036/9e2efbbe-0fcc-445f-a459-7584c686f5aa">
seems to work! you do have to load the announce room but it works

**Comment by johnmlee101** [comment] 2023-09-18 04:16
@dylanexpensify do you want to confirm and issue the report payments for this?

**Closed** 2023-09-19 15:20 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
