### ISSUE TITLE
[HOLD for payment 2024-04-05] [$125] Workspace - Categories load without loading spinner

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37904] opened 2024-03-07 16:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37457

**Version Number:** v1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ihchat4_2902_c@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: an admin account with a policyExpenseChat enabled Collect policy and another workspace.

1. Open the app
2. Login with admin account with Collect policy
3. Navigate to Workspace > Settings and select the collect policy.
4. Select the Categories page
5. Verify that you see the loading spinner

## Expected Result:
Categories load with loading spinner

## Actual Result:
Categories load without loading spinner

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/34c680d4-f39e-41e3-87de-0e92c15fe16e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01197fc8d66a9362f0</li>
        <li>Upwork Job ID: 1770919042911531008</li>
        <li>Last Price Increase: 2024-03-21</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-07 16:34
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-07 16:35
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by alexpensify** [comment] 2024-03-08 18:43
I'll test early next week and we can figure out the next steps. Thanks!

**Comment by alexpensify** [comment] 2024-03-11 23:20
No update yet, I need to test.

**Comment by alexpensify** [comment] 2024-03-13 19:20
I've started a discussion in the wave room related to Collect - https://expensify.slack.com/archives/C036QM0SLJK/p1710357619580229. I should have an update by tomorrow.

**Comment by luacmartins** [comment] 2024-03-13 19:42
This is not a bug. We only want to show the loading spinner if we have no local data.

**Comment by luacmartins** [comment] 2024-03-13 19:42
Closing this issue.

**Comment by alexpensify** [comment] 2024-03-13 19:45
Thanks @luacmartins for the update!

**Comment by luacmartins** [comment] 2024-03-21 20:34
I think we should just mirror the conditions we have for the [tags page](https://github.com/Expensify/App/blob/8dd68c3292416e8a0bcfbfbf28f2a81c1d9ad0ad/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L289-L316). This was also what we initially had for categories, but we changed it somewhere along the way.

**Comment by luacmartins** [comment] 2024-03-21 21:04
I think we should use the same solution on Categories and Tags page. I just realized that the logic in the Tags page also has a weird behavior when we delete all tags while online (it shows an empty table) until the API request finishes.

**Comment by DylanDylann** [comment] 2024-03-22 14:03
@GandalfGwaihir How can you create a collect workspace on newdot?

**Comment by DylanDylann** [comment] 2024-03-22 14:17
Please also check all other pages like Tax page, member page, Distance Rate Page,....

**Comment by luacmartins** [comment] 2024-03-22 14:28
>also @luacmartins as this is for tags pages as well, i guess the bounty can be $250 right :)

Sorry, the changes are really simple so we'll keep it at $250

**Comment by luacmartins** [comment] 2024-03-22 14:38
Yes, sorry haven't fully woken up yet. $125 I edited my message above.

**Comment by alexpensify** [comment] 2024-04-04 22:51
I confirmed the job link works here. I'll complete the payment process tomorrow. 

https://www.upwork.com/jobs/~01197fc8d66a9362f0

**Comment by alexpensify** [comment] 2024-04-05 21:20
Payouts due: 2024-04-05

- [ ] Contributor: $125 @GandalfGwaihir 
- [ ] Contributor+: $125 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~01197fc8d66a9362f0).

--- 

Closing - Everyone has been paid here

**Closed by alexpensify** 2024-04-05 21:20 UTC
Labels: External, Weekly, Awaiting Payment, Bug
