### ISSUE TITLE
[HOLD for payment 2023-07-21] [HOLD for payment 2023-07-20] New Task - Crash when choosing Assignee as phone number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22657] opened 2023-07-11 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon
3. Select Assign task option
4. Enter the title and description of the data > Next
4. Select Assignee as number phone
4. Enter title and click on next button
5. Click on Confirm task button

## Expected Result:
App doesn't crash

## Actual Result:
Crash when choosing Assignee as phone number (Web)
In IOS appears Hmm... its not here
You don't have access to this chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fa2f2fbd-c962-4a86-9b97-227634a8a491

https://github.com/Expensify/App/assets/78819774/0cbbf184-a71c-40e2-9f6a-13058334a3d7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment] 2023-07-11 18:01
I can't reproduce the issue on staging. I wonder if it's a backend issue with the account you were using specifically. Any chance you can share the email address of the account you were using so I can check backend logs please?

**Comment by francoisl** [comment] 2023-07-12 17:20
Internal logs of a crash for this [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227e5ad2d31eab02e8-MIA%22)+AND+timestamp:[2023-07-12T15:57:08.392Z+TO+2023-07-12T17:57:08.392Z]&index=logs_expensify-023271).

```
NewExpensify crash caught by error boundary - Cannot read property 'avatar' of undefined ~~ errorInfo: '{"componentStack":" in TaskView in WithCurrentUserPersonalDetails(TaskView) in Unknown in withOnyx(Component) in Unknown in Unknown in Unknown in ReportActionItem in withOnyx(Component) in Unknown in Unknown in Unknown in Unknown in Unknown
```

The stacktrace is pointing to reading a `.avatar` in TaskView... @jasperhuangg any chance this could be on [this line](https://github.com/Expensify/App/pull/20841/files#diff-a365b66ed37facba06612263b5c0751a491d1d09de2dbb61362cb70b974deb0dR116)?

**Comment by francoisl** [comment] 2023-07-12 17:59
I was able to reproduce the crash, the key is that you have to create a task with a phone number you've never interacted with before. I think the issue is the line I pointed to before, working on a fix.

**Comment by francoisl** [comment] 2023-07-13 17:04
Co-assigning @s77rt and BZ so we remember to complete payment for the PR review.

**Comment by s77rt** [comment] 2023-07-15 18:45
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/20841
- The offending PR has been commented on: https://github.com/Expensify/App/pull/20841#discussion_r1264527074
- A discussion in #expensify-bugs has been started: The bug could have been caught during testing, I don't feel a discussion is required here.
- Determine if we should create a regression test for this bug: No

**Comment by francoisl** [comment] 2023-07-21 21:32
Not sure why this got auto-labelled both Monthly and Daily, but it's ready for payment now @anmurali.

**Comment by anmurali** [comment] 2023-07-24 15:27
To confirm this was fixed by @jasperhuangg and @s77rt and @fedirjh are owed $1,000 each for PR review?

**Comment by s77rt** [comment] 2023-07-24 18:34
@anmurali This was fixed by @francoisl. @jasperhuangg and I reviewed the PR. I think I'm the only one pending payment here. I don't see where @fedirjh tag came from :sweat_smile:

**Comment by francoisl** [comment] 2023-07-27 00:10
Anu is OOO at the moment, I'm going to reapply the label to assign another BugZero member.

**Comment by slafortune** [comment] 2023-08-02 20:21
@s77rt offer sent - https://www.upwork.com/nx/wm/offer/25911954

**Comment by s77rt** [comment] 2023-08-02 23:09
@slafortune Accepted! Thanks!

**Comment by slafortune** [comment] 2023-08-03 17:44
Paid

**Closed by slafortune** 2023-08-03 17:44 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
