### ISSUE TITLE
[$250] Task - On task created, description shown as hidden

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51485] opened 2024-10-25 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with a new gmail id
3. Open self DM
4. Tap plus icon -- assign task
5. Enter title
6. Paste description - task for @[applausetester+88@applause.expensifail.com](mailto:applausetester+88@applause.expensifail.com)
point
7. Tap next
8. Tap confirm task
9. Open the task
10. Note in description, used is shown as hidden
11. Open the description
12. Note hidden is not selected
13. Paste the same content and tap save
14. Note hidden highlighted
15. Now refresh the page
16. Note a whisper message is shown below if description added after creating task.

## Expected Result:
On task created, description must not be shown as hidden

## Actual Result:
On task created, description shown as hidden. On opening description hidden not highlighted. Again saving with same description and refreshing page shows a whisper message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f8d62492-ee87-4ff9-a902-eae8fb9cb1ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851677782773395839</li>
        <li>Upwork Job ID: 1851677782773395839</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by ranli** [comment] 2024-10-31 04:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mentioned user in description shown as hidden when creating task

### What is the root cause of that problem?
The user may not exist in the system. So backend return the account payload like:
```
{
    "accountID": 18092501,
    "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_6.png",
    "firstName": "",
    "lastName": ""
}
```
The payload does not have displayName or login, so MentionUserRenderer will return 'Hidden' as the displayname by default.

https://github.com/Expensify/App/blob/aa6401de4a3c02adce2cb898eba8c58e1c92b62d/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62

### What changes do you think we should make in order to solve the problem?
Option 1: 
If we are okay to user the accountId returned from backend as the displayName, we can set the accountId as default value when getDisplayName.
```
mentionDisplayText = LocalePhoneNumber.formatPhoneNumber(user?.login ?? '') || PersonalDetailsUtils.getDisplayNameOrDefault(user, accountID.toString(), true, false);
```

Option 2:
If we want a more friendly name (e.g email address we entered), backend need to return the data first. And then base on the payload backend returned, we can modify the default value in the same place as option 1.

### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ranli** [comment] 2024-10-31 05:03
[!(renamed webm)](https://github.com/user-attachments/assets/36466e0b-2dfa-4dd4-b4ca-130c9bb8deb2)

**Comment by Anaslancer** [comment] 2024-11-02 20:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - On task created, description shown as hidden

### What is the root cause of that problem?
After creating or updating a task, the backend returns `onyxData` to process at frontend side. In this data, there is a description not including an user email when this email is unregistered in the database.
![Screenshot_6](https://github.com/user-attachments/assets/49f6c0d9-68f0-405d-88a2-25944e28abb7)
This(^^^) is the `onyxData` from frontend.
![Screenshot_7](https://github.com/user-attachments/assets/5bbc26ed-cc70-452a-8701-d5cdbe799d68)
This(^^^) is the `onyxData` from backend.

### What changes do you think we should make in order to solve the problem?
1. The backend should send the email instead null if this is unregistered. Then we do nothing on frontend side.
2. If you don't want to change the backend, I can revert the description when the email is unregistered.

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by akinwale** [comment] 2024-11-04 10:21
@abekkala This is an issue that needs to be fixed in the backend.

**Comment by abekkala** [comment] 2024-11-11 17:11
Not overdue - we'll need an internal engineer to pick this one up

**Comment by abekkala** [comment] 2024-11-14 20:04
Not overdue - we need an internal engineer to pick this one up

**Closed** 2024-11-18 16:27 UTC
Labels: Daily, Internal, Overdue, Bug, Hot Pick
