### ISSUE TITLE
Redmi Note 8 Pro - Text field with email keyboard type cursor is not visible

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13549] opened 2022-12-13 03:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and logout if logged in
2. Focus on the email text field
3. Observe there is no cursor

## Expected Result: 
cursor is visible

## Actual Result: 
cursor is not visible

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android Android (Redmi Note 8 Pro)

**Version Number:** 1.2.36-4
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207217320-d29f9957-4756-4cc2-bb5a-6bc78c9484ef.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670841591635449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2023-01-02 21:32
Not able to reproduce via the same device via browserstack `Redmi Note 8` - Closing!

<img width="366" alt="Screenshot 2023-01-02 at 1 31 21 PM" src="https://user-images.githubusercontent.com/2838819/210279292-9663ae60-a860-4664-be31-132b74d41eb4.png">

**Closed by AndrewGable** 2023-01-02 21:32 UTC
Labels: Weekly, Needs Reproduction, Bug
