### ISSUE TITLE
[HOLD for payment 2023-07-28] [HOLD for payment 2023-07-26] [$1000] IOU Report header shows back button even on large screens.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23123] opened 2023-07-18 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on staging.
2. Go to a chat, click on "+".
3. Click on request money.
4. Enter details and click on request.
5. Click on report preview to go to the new chat.
6. Notice the new IOU report chat shows back button in header.
## Expected Result: 
Back button should be shown only on small screens which is the case for all other report headers.
## Actual Result: 
Back button is shown on all screens for only IOU report headers.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8aa855e2-d388-40f3-a7d2-d4938f4122fd

![Snip - New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/43996225/5e9a89b3-7fd8-4cfd-bcca-22dfc42f4cbf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689706828844219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129d2040f88d2242e</li>
        <li>Upwork Job ID: 1681405233161469952</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-07-18 20:39
@shawnborton it looks like it's actually expected that we show a back button on both screens from [the original issue](https://github.com/Expensify/App/issues/22332)

Just wanted to double check with you that this is the expected behavior. If so we can close this out.

**Comment by Nikhil-Vats** [comment] 2023-07-18 20:40
@jasperhuangg Yes, I also noticed that. I informed this in the slack thread and @shawnborton confirmed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689708607984999?thread_ts=1689706828.844219&cid=C049HHMV9SM).

**Comment by srikarparsi** [comment] 2023-07-18 20:41
Cool, I can get a fix out pretty quick and I'll assign you to review @jasperhuangg

**Comment by jasperhuangg** [comment] 2023-07-18 20:42
Awesome, thanks @srikarparsi!

**Comment by Nikhil-Vats** [comment] 2023-07-18 20:43
@srikarparsi [My proposal above](https://github.com/Expensify/App/issues/23123#issuecomment-1640901435). 

I would be happy to do it if you want me to. Otherwise, you can go ahead and fix it. 🚀

**Comment by srikarparsi** [comment] 2023-07-18 20:46
Oh cool! Yeah that would be great, the proposal looks good. I can review and merge once you make the PR :)

**Comment by Nikhil-Vats** [comment] 2023-07-18 21:05
Creating a PR within an hour.

**Comment by jasperhuangg** [comment] 2023-07-18 21:08
@Nikhil-Vats I think @srikarparsi is already on this

**Comment by Nikhil-Vats** [comment] 2023-07-18 21:11
@jasperhuangg They assigned me [here](https://github.com/Expensify/App/issues/23123#issuecomment-1640969474).

**Comment by srikarparsi** [comment] 2023-07-18 21:12
Oh if it's within an hour it's all good, I can do it really quickly since it's a deploy blocker. Thank you though!

**Comment by Nikhil-Vats** [comment] 2023-07-18 21:14
Ok, I will do it right now.

**Comment by srikarparsi** [comment] 2023-07-18 21:17
Oh it's all good, I just created it - https://github.com/Expensify/App/pull/23133. I will ask internally to check if we can still compensate since your proposal was right.

**Comment by kbecciv** [comment] 2023-07-19 17:45
@situchan Reported the issue early here at 11:38 AM https://expensify.slack.com/archives/C049HHMV9SM/p1689694731956419 and @Nikhil-Vats reported later at 3:00 PM.
![image](https://github.com/Expensify/App/assets/93399543/361bb409-db05-46b7-bdca-613ea372190a)

![image](https://github.com/Expensify/App/assets/93399543/e51579d8-de92-4217-b4e9-51d187ada8c5)

**Comment by slafortune** [comment] 2023-07-27 21:47
@Nikhil-Vats @srikarparsi  - can you complete the checklist?

**Comment by slafortune** [comment] 2023-07-27 21:51
@Nikhil-Vats - did you end up creating the fix for this?  just trying to followup and make sure I'm getting the correct people paid.

**Comment by srikarparsi** [comment] 2023-07-28 05:31
Just completed the checklist @slafortune

**Comment by slafortune** [comment] 2023-07-28 17:19
@Nikhil-Vats It looks like the offer for the Contributor role hasn't been accepted yet, but the $250 reporting was.  I'm going to pay that at $0 to close it.  Can you accept the offer for $1000 [here](https://www.upwork.com/nx/wm/offer/25612985)?

**Comment by slafortune** [comment] 2023-07-28 17:50
- urgency bonus? YES
- External issue reporter @situchan $250
- Contributor that fixed the issue @Nikhil Vats  $1500
- Contributor+ that helped on the issue and/or PR @srikarparsi NA - internal
All paid 👍

**Closed by slafortune** 2023-07-28 17:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
