### ISSUE TITLE
[$500] Conversation - Green line does not appear when chat is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32506] opened 2023-12-05 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Log into Expensify on the main testing device as User A
3. On another device, log in to another account as User B
4. User A open conversation with User B
5. User B send some messages to User A

## Expected Result:
Green line should appear since new messages was sent

## Actual Result:
Green line does not appear when chat is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f5b172f9-5160-4f46-8e20-238f3cef18d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154028f533f92c290</li>
        <li>Upwork Job ID: 1732106247324459008</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-05 19:59
This looks like a regression from https://github.com/Expensify/App/issues/27456

**Comment by paultsimura** [comment] 2023-12-05 20:16
> You're so easy to say "regression"

My logic is the following:
- There is a clearly described expected behavior in the issue.
- The expected behavior is achieved if the linked changes are reverted.

Therefore, I assume that the offending PR is breaking the expected behavior and therefore it's a regression.

Is this logic incorrect, @aimane-chnaif?

**Comment by paultsimura** [comment] 2023-12-05 20:19
> Expected Result and Actual Result are reversed

Then this is a different talk. I usually tend to trust the Issue author with the expected behavior to be correct, therefore am "easy to say "regression".
Thank you for clarifying 🙂

**Comment by anmurali** [comment] 2023-12-13 14:51
@aimane-chnaif can we bring this chat to #expensify-bugs and clarify the expected behavior so we can either fix or close this issue?

**Comment by MonilBhavsar** [comment] 2023-12-18 20:01
Thanks for the ping. Yes, this is expected behavior. Since user A is active on a chat with user B, new marker should not appear. we can close this. I am going to create a master issue to update QA tests

**Closed by MonilBhavsar** 2023-12-18 20:01 UTC
Labels: External, Daily, Help Wanted, Bug
