### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Web - Markdown - Cursor overlaps with certain letters if quote markdown is applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42196] opened 2024-05-15 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat
3. Click on + icon > submit an expense > Manual > Enter an amount and click next
4. Open description input field
5. Write "> Hey"

## Expected Result:
The cursor doesn't overlap with the letter "y"

## Actual Result:
The cursor overlaps with the letter "Y" if quote markdown is applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ac1909a6-0f92-4658-bde4-390929ba7171

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114f52f7e90fdd65f</li>
        <li>Upwork Job ID: 1793680288067104768</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102575234</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by abekkala** [comment] 2024-05-23 16:27
Able to reproduce

**Comment by alitoshmatov** [comment] 2024-05-26 18:04
Thank you for your proposal @dominictb, why exactly cursor is overlapping when display is `inline-block`. Would setting display as block solve the issue? I mean setting padding right seems like a workaround and we are not addressing the root cause

**Comment by abekkala** [comment] 2024-05-28 14:42
@alitoshmatov can you review the above from @dominictb

**Comment by alitoshmatov** [comment] 2024-05-29 17:49
@dominictb I am still not completely convinced that this the best solution here. Even if we agreed to apply this how we would know how much padding is right one, we don't have existing merit for this. In my opinion, this point alone indicates the solution is not ideal

**Comment by alitoshmatov** [comment] 2024-05-29 17:52
Let me think and do some research about it

**Comment by alitoshmatov** [comment] 2024-06-02 19:13
> This issue appears to be minor, as the overlap is barely noticeable. Therefore, I believe it is not worth fixing!!

Yes it is small issue, but since the issue is created I think we should try to solve it

**Comment by alitoshmatov** [comment] 2024-06-02 19:13
Let's go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/42196#issuecomment-2129426015)

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2024-06-19 10:26
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34292
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34292/files#r1645879763
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by alitoshmatov** [comment] 2024-06-19 10:26
This one is ready for payment

**Comment by abekkala** [comment] 2024-06-19 19:14
Not overdue melvin! Payment is tomorrow!

**Comment by abekkala** [comment] 2024-06-20 13:09
### PAYMENT SUMMARY FOR JUNE 20

- Fix: @dominictb [$250] [Offer Link](https://www.upwork.com/nx/wm/offer/102809927)
- PR Review: @alitoshmatov [$250]  [Offer Link](https://www.upwork.com/nx/wm/offer/102575234)

**Comment by abekkala** [comment] 2024-06-20 13:10
@alitoshmatov payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2024-06-21 11:56
@dominictb if you can accept the offer in Upwork I can process payment and close this one out - thank you!

**Closed** 2024-06-24 12:34 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
