### ISSUE TITLE
[$250] Hybrid Android/iOS - Copilot - Email missing on Let's make sure it's you step

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51284] opened 2024-10-22 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49445
## Action Performed:
1. Open the app and log in
2. Navigate to the account settings > Security > Add copilot
3. Select an account
4. Select the access level and proceed to the next step
5. Confirm to add copilot

## Expected Result:
The email to which one the magic code was sent is displayed

## Actual Result:
The email to which one the magic code was sent is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4415e142-c336-4afb-a016-835dd9db51b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849735612716912049</li>
        <li>Upwork Job ID: 1849735612716912049</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-10-22 18:36
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment] 2024-10-24 20:34
Where should the email be? Can you check the testing script please @lanitochka17 ? I don't think this is a bug.

**Comment by zanyrenney** [comment] 2024-10-24 20:35
actually, going to take to channel.

**Comment by zanyrenney** [comment] 2024-10-24 20:39
https://expensify.slack.com/archives/C049HHMV9SM/p1729802357760819

**Comment by Rai7in** [comment] 2024-10-26 11:32
Hi there,

I am coming here from Upwork.
https://www.upwork.com/jobs/250-Hybrid-Android-iOS-Copilot-Email-missing-Let-make-sure-you-step-51284-Expensify_~021849735612716912049/?referrer_url_path=find_work_home

Should I post my proposal in the comments here? Or is there any specific page of forms to submit the proposal?
I have read the [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md)
It just states to submit the proposal here in the git issue comments. So I am not sure.

My upwork profile
https://www.upwork.com/freelancers/~016d4742bcd2c740f6?mp_source=share

Thanks,
Raghu

**Comment by Rai7in** [comment] 2024-10-26 11:38
Contributor details
Your Expensify account email: raghu1298@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016d4742bcd2c740f6?mp_source=share

**Comment by Rai7in** [comment] 2024-10-26 12:08
My Proposal for above issue:
As I see from the above issue, the root cause looks to be the email details are not added to the view text.
I am not sure on how the magiccode to the selected mail is sent whether through android intent or by integrating with an email sending service (like Amazon SES etc).

And the requirement to show the activity/fragment "The email to which one the magic code was sent is displayed"

1. If it is immediately after the Intent or API call, the activity/fragment can be called with the email selected to be shown on the next screen.

2. If it is need to be shown after the mail is sent successfully, then we would have to implement the email sending functionality within the app using SMTP (Simple Mail Transfer Protocol) or by integrating with an email sending service that provides APIs for sending emails and receiving delivery status, with a waiting screen transition.

- Through this we can decide to move to the next page to show  "The email to which one the magic code was sent is displayed along with the next actions" 

- or can show the error status and can take action to validate/modify the mail before trying again.

This completely depends on the requirement and how to implement.

This is my proposal for the brief information given in the above problem statement/ issue description. If more details are available. The implementation can be further optimized.

Thanks,
Raghu.

**Comment by s77rt** [comment] 2024-10-26 16:33
@Rai7in Welcome! Regarding your question you should comment just here on GitHub. Upwork is only used for payment and no discussion is done there. As for your proposal please use the proposal template as stated in contributing guide and provide a better RCA (e.g. why is the email not being added, link to the offending code or PR, etc.).

**Comment by s77rt** [comment] 2024-10-29 23:07
Still looking for proposals

**Comment by s77rt** [comment] 2024-11-04 18:29
Same ^

**Comment by dangrous** [comment] 2024-11-05 14:40
Should we maybe bump the price on this one?

**Comment by s77rt** [comment] 2024-11-05 14:46
@dangrous I think this needs to be `Internal`? It does not seem like contributors can run the hybrid app

**Comment by dangrous** [comment] 2024-11-05 21:03
I'm able to reproduce this on the staging app, but I can't get it locally yet. Not sure I can take this on, but just to call out - it seems like `account?.primaryLogin` isn't being loaded properly in android hybrid app. Dunno yet if that's on the `account` side or the `primarylogin` side. Or something else entirely!

**Comment by s77rt** [comment] 2024-11-06 08:46
Yes, that seems to be the case.

@Julesssss May know how we handle bugs in the hybrid app

**Comment by Julesssss** [comment] 2024-11-06 09:06
> @Julesssss May know how we handle bugs in the hybrid app

Yeah, for now they need to remain internal

**Comment by s77rt** [comment] 2024-11-11 16:08
Do we need to add `Hot Pick` or how can get an engineer to look into this

**Comment by s77rt** [comment] 2024-11-11 16:11
🎀 👀 🎀 Summoning 🪄🌟 🌟 ✨💫

**Comment by tgolen** [comment] 2024-11-11 16:15
For internal issues, please open a separate GH issue using this template: https://github.com/Expensify/App/issues/new?assignees=&labels=Hot+Pick%2C+Daily%2C+Internal%2C+AutoAssignerNewDotQuality&projects=&template=Internal.md

(I'm happy to be assigned to it)

**Comment by s77rt** [comment] 2024-11-14 17:43
Not overdue. Should we hold this on https://github.com/Expensify/App/issues/52499? Not sure why we needed another issue, this one should be enough as it's still a frontend issue

**Closed** 2024-11-18 16:26 UTC
Labels: Daily, Internal, Bug
