### ISSUE TITLE
[Payment due 7-25] Review duplicate - "resolved the duplicate" system message disappears after restarting app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44294] opened 2024-06-24 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses (can be manual, scan or distance)
4. Wait for "Review duplicate" button to show up in transaction thread
5. Click Review duplicate
6. Click Keep all
7. Note that "resolved the duplicate" system message shows up
8. Go to Troubleshoot > Clear cache and restart > Reset and refresh (or relogin)
9. Return to the same transaction thread in Step 7

## Expected Result:
"Resolved the duplicate" system message will remain

## Actual Result:
"Resolved the duplicate" system message disappears after restarting app/relogin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/23f23d63-5036-4e7c-9c3b-36a7b969e739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-24 18:34
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-24 18:34
We think that this bug might be related to #wave-collect - Release 2

**Comment by rlinoz** [comment] 2024-06-24 20:31
It looks like we are not sending the action back in the DismissViolation response, so it is not a FE bug, also this is a new feature and I don't think we need to block on this.

<img width="977" alt="image" src="https://github.com/Expensify/App/assets/5201282/5345de12-e20d-4cb0-8e31-3bfc2b03c0f0">

@pecanoro do you know if this is being handled somewhere else?

**Comment by pecanoro** [comment] 2024-06-24 20:32
Hmm, yeah, I don't think we create any report actions for this in the back-end

**Comment by rlinoz** [comment] 2024-06-25 14:24
@pecanoro just to be sure, I was reading the doc and we should right? If so, I think we can do that in this issue.

**Comment by rlinoz** [comment] 2024-06-27 20:46
Will check in #wave-collect later.

**Comment by pecanoro** [comment] 2024-06-28 02:31
Hmm, the problem is that this action can be taken by many people. So the submitter can dismiss it, but the admin will see it either way. I remember discussing it, but I can't remember what we agreed on.

**Comment by rlinoz** [comment] 2024-07-01 12:59
Posted on [slack](https://expensify.slack.com/archives/C036QM0SLJK/p1719838762073189)

**Comment by rlinoz** [comment] 2024-07-03 21:21
Continuing the conversation on slack.

**Comment by rlinoz** [comment] 2024-07-08 17:58
Here is the plan for this one:

- Add an ACTION_UNHOLD [here](https://github.com/Expensify/Auth/blob/0f89212bd232c924f55f4121bd11ef72982f8f9b/auth/command/DismissViolation.cpp#L114) if the accountID dismissing the violation is the submitter and a DISMISSED_VIOLATION if it is the approver
- Start checking the violationName [here](https://github.com/Expensify/Auth/blob/0f89212bd232c924f55f4121bd11ef72982f8f9b/auth/lib/ReportAction.cpp#L1345) to decide on what message we send back
- Update the DismissViolation command to accept a list of optimisticReportActionID [in Web-E](https://github.com/Expensify/Web-Expensify/blob/990e17db733f65ff84e28df76ee3f92c95bb16e8/api.php#L4145)
- Replicate the logic of which type of action to create when creating the optimistic action in the App and start sending an optimisticReportActionID when calling DismissViolation for duplicate transactions

Hopefully I will have some PRs by tomorrow EOD.

**Comment by rlinoz** [comment] 2024-07-10 19:05
Working on it!

**Comment by Christinadobrzyn** [comment] 2024-07-15 22:13
Update for Melvin - working on a PR

**Comment by Christinadobrzyn** [comment] 2024-07-16 17:55
@allroundexperts should we move this to weekly since the PR is under review?

**Comment by allroundexperts** [comment] 2024-07-17 20:27
PR got merged @Christinadobrzyn 😄

**Comment by allroundexperts** [comment] 2024-07-17 20:28
See https://github.com/Expensify/App/pull/45315

**Comment by Christinadobrzyn** [comment] 2024-07-18 17:16
Awesome! looks like it just went to production so updating the Title for the payment date and switching this to weekly for the time being.

**Comment by Christinadobrzyn** [comment] 2024-07-23 23:44
Payday is coming up so going to move this back to daily.

**Comment by Christinadobrzyn** [comment] 2024-07-26 18:08
nudge @allroundexperts

**Comment by Christinadobrzyn** [comment] 2024-07-26 22:14
nudge @allroundexperts

**Comment by allroundexperts** [comment] 2024-07-29 08:21
## Regression test
1. Open the app and Go to any workspace chat
2. Submit two same expenses (can be manual, scan or distance)
3. Wait for "Review duplicate" button to show up in transaction thread
4. Click Review duplicate and select Keep all
5. Note that "resolved the duplicate" system message shows up
6. Go to Troubleshoot > Clear cache and restart > Reset and refresh (or relogin)
7. Return to the same transaction thread in Step 5

Verify that "Resolved the duplicate" system message will remain

Do we 👍 or 👎 ?

**Comment by Christinadobrzyn** [comment] 2024-07-29 18:06
Regression test - https://github.com/Expensify/Expensify/issues/416107

Closing since @allroundexperts payment will be through NewDot. Payment summary here- https://github.com/Expensify/App/issues/44294#issuecomment-2246536034

**Closed** 2024-07-29 18:06 UTC
Labels: Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-10-04 11:08
$250 approved for @allroundexperts
