### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Brief loading circle when accessing Company Cards page

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#51333] opened 2024-10-23 13:27 UTC
# Problem 
([Discussed here](https://expensify.slack.com/archives/C06ML6X0W9L/p1729628752886809)) every time you access the `Company cards` empty-state page on the workspace, there's a brief loading circle while we render the graphic in the middle of the page. This makes the experience feel less premium, as there isn't any significant amount of data being loaded here. It also doesn't exist for the Expensify Card empty state, which is analogous to this page. 

## Company cards page 
https://github.com/user-attachments/assets/e5cb423e-5fc7-4ec9-a763-1fc4523378e4

## Expensify Card page 
https://github.com/user-attachments/assets/192b40bb-6a4c-4a9b-a677-9a511aa1326d

# Solution 
Remove this loading indicator when accessing `Company cards`. If we don't need it when accessing `Expensify Card` empty state, it shouldn't be necessary here either, as they're essentially the same page with a different graphic. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849080892463168395</li>
        <li>Upwork Job ID: 1849080892463168395</li>
        <li>Last Price Increase: 2024-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 105194260</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by joekaufmanexpensify** [comment] 2024-10-23 13:28
@waterim is taking this one. Once they comment here, we'll assign them!

**Comment by joekaufmanexpensify** [comment] 2024-10-23 13:29
@shawnborton IDT there are really any design implications to this one, as it's just polish for the loading of this page. But LMK if anything comes to mind!

**Comment by waterim** [comment] 2024-10-23 13:29
Hello Im Artem from Callstack and would like to take this one!

**Comment by shawnborton** [comment] 2024-10-23 18:27
Sounds good, yeah this one seems pretty straightforward 👍

**Comment by Christinadobrzyn** [comment] 2024-10-29 06:14
PR under works - https://github.com/Expensify/App/pull/51360

**Comment by Christinadobrzyn** [comment] 2024-11-05 08:12
PR under works - https://github.com/Expensify/App/pull/51360

**Comment by Christinadobrzyn** [comment] 2024-11-12 01:48
Monitoring PR https://github.com/Expensify/App/pull/51360

**Comment by Christinadobrzyn** [comment] 2024-11-19 05:17
moving to daily since payment is coming up. 

Payouts due:

- [ ] Reviewer: $250 @getusha (upwork offer - https://www.upwork.com/nx/wm/offer/104963518)

@getusha do we need a regression test?

**Comment by rlinoz** [comment] 2024-11-19 15:03
I agree 👍

**Comment by Christinadobrzyn** [comment] 2024-11-20 04:14
Thanks! @getusha can you please accept the Upwork offer when possible? https://www.upwork.com/nx/wm/offer/104963518

**Comment by joekaufmanexpensify** [comment] 2024-11-21 14:45
@waterim Is this supposed to be fixed? I'm still seeing the same behavior. 


https://github.com/user-attachments/assets/dbee0968-d9cc-473a-9249-dfc434f3dcd9

**Comment by joekaufmanexpensify** [comment] 2024-11-21 14:56
@waterim is this it? https://github.com/Expensify/App/pull/52615

**Comment by waterim** [comment] 2024-11-21 14:58
@joekaufmanexpensify probably, I took ticket to fix it, will update why its happening!

**Comment by Christinadobrzyn** [comment] 2024-12-02 19:04
Just checking in on this @waterim do you have an update? It looks like the PR is still being reviewed, is that correct? https://github.com/Expensify/App/pull/52615

**Comment by Christinadobrzyn** [comment] 2024-12-02 20:24
Ah thanks @waterim! So I think we can pay this out and there were no regressions, is that correct?

**Comment by Christinadobrzyn** [comment] 2024-12-03 17:00
I'm just checking on this; I still see a loading circle - is this expected? cc @waterim @getusha  This is on Mac Chrome


https://github.com/user-attachments/assets/fabea5bf-c6b8-4f9a-84e5-4d32e5a0bfc6

**Comment by waterim** [comment] 2024-12-04 00:28
@Christinadobrzyn yes, its expected behavior for an empty state when we dont have cardList, but once we have it we will not have a loading state

**Comment by Christinadobrzyn** [comment] 2024-12-04 15:33
Thanks @waterim! Do we need a regression test for this? @getusha @waterim

**Comment by waterim** [comment] 2024-12-04 15:34
Im not sure actually
Maybe @mountiny or @joekaufmanexpensify can help to answer this

**Comment by mountiny** [comment] 2024-12-04 17:33
I think we should add the regression test for this one @allgandalf. Could you please write up the regression test from the scenarios we have been discussing? I think you will be able to nail it really well

**Comment by Christinadobrzyn** [comment] 2024-12-05 20:02
Thanks @allgandalf! Regression test here - https://github.com/Expensify/Expensify/issues/450899

So what's the payment for this: 

- Contributor: @waterim is from an agency-contributor and not due payment
- Reviewer: @getusha owed $250 via NewDot
- Reviewer: @allgandalf owed $250 via NewDot/Upwork (?)

Is this accurate?

**Comment by rlinoz** [comment] 2024-12-06 15:42
I think @allgandalf is being paid in the project of this other PR https://github.com/Expensify/App/pull/52615, so only @getusha should be paid here

Correct me if I am wrong @allgandalf @mountiny

**Comment by Christinadobrzyn** [comment] 2024-12-06 18:12
Thanks @rlinoz - @getusha can you request payment through NewDot? TY!

**Comment by mountiny** [comment] 2024-12-08 23:57
Correct @allgandalf will be paid separately in one go probably this week

**Comment by Christinadobrzyn** [comment] 2024-12-09 20:05
okay sounds good. @getusha can you make sure to request payment through ND. 

Payment summary here - https://github.com/Expensify/App/issues/51333#issuecomment-2521284355

Going to close this as complete.

**Closed by Christinadobrzyn** 2024-12-09 20:05 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment

**Comment by garrettmknight** [comment] 2024-12-12 10:47
$250 approved for @getusha
