### ISSUE TITLE
Chat - Selected receipt date is changed to priviuse date

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29862] opened 2023-10-18 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to Fab menu
2. Select scan
3. Select media
4. Tap on any receipt
5. Select user
6. Tap Request
7. open receipt when it in Scanning progress
8. Change the receipt date

## Expected Result:
The selected date should be saved

## Actual Result:
Selected receipt date is changed to priviuse date

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/1ccedb48-420a-40ce-a466-4041466911bd

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/b53f2399-6552-446f-9167-9004cb145798

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/a1e02f15-8c19-47fb-9cc1-f15a961c8791

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cooldev900** [comment] 2023-10-18 14:00
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
The Date of Birth field selects a different date instead of the selected date
### What is the root cause of that problem?
It comes from this PR, https://github.com/Expensify/App/pull/29062

The root cause is that it does not take into account the difference between New Date('YYYY-MM-DD') and New Date(Year, Month, Day).
https://stackoverflow.com/questions/25865051/javascript-difference-between-new-datedatestring-vs-new-dateyear-month

https://github.com/Expensify/App/blob/9d79fd12ce8f5d1dcb8870b61a8bc4513f55c935/src/components/NewDatePicker/CalendarPicker/index.js#L208
### What changes do you think we should make in order to solve the problem?
We should use a consistent approach when handling dates.
```const isSelected = this.props.value === format(currentDate, CONST.DATE.FNS_FORMAT_STRING);```
### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-10-18 14:04
I'm not able to reproduce this

**Comment by b4s36t4** [comment] 2023-10-18 14:05
any specific steps??

**Comment by s-alves10** [comment] 2023-10-18 14:05
This is a regression of this PR https://github.com/Expensify/App/pull/29062

**Comment by tewodrosGirmaA** [comment] 2023-10-18 14:30
Hey guys, I actually reported this issue on Slack before it was posted on Github. You can find my original report at https://expensify.slack.com/archives/C049HHMV9SM/p1697608053386949?thread_ts=1697608053.386949&cid=C049HHMV9SM."

**Comment by kbecciv** [comment] 2023-10-18 14:35
@b4s36t4 Another scenario:
1. Go to Settings > Profile > Personal Details > Date of Birth
2. Click on the Date of Birth field and select a date
3. Observe that the selected date is not saved,
Expected Result: The selected date should be saved in the Date of Birth field.
Actual Result: The Date of Birth field selects a different date instead of the selected date.

https://github.com/Expensify/App/assets/93399543/08ebc5be-81a4-4917-8967-9871859c049c

**Comment by mountiny** [comment] 2023-10-18 16:51
@waterim the author is looking into this, if they cant find a solution, we can revert

**Comment by mountiny** [comment] 2023-10-18 23:44
@waterim lets focus on this testing moving ahead, although I swear this worked on our PR maybe there is some prerequisite

**Comment by mountiny** [comment] 2023-10-18 23:45
@lschurr could you please pay $50 to @tewodrosGirmaA for reporting. thanks!

**Comment by lschurr** [comment] 2023-10-19 16:29
Yep! I invited you to the job @tewodrosGirmaA - https://www.upwork.com/jobs/~017dd56ff525a2ca36

**Comment by tewodrosGirmaA** [comment] 2023-10-19 16:45
Hello @lschurr , i accepted the invitation,  Thank you 😊

**Comment by lschurr** [comment] 2023-10-19 16:51
Payment sent. Closing!

**Closed by lschurr** 2023-10-19 16:51 UTC
Labels: Engineering, Bug
