### ISSUE TITLE
[$500] Dev: Web - The profile preview header displays "Profile avatar" instead of "Profile picture"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27785] opened 2023-09-19 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings > Profile
2. Upload a picture as your profile picture
3. Click on the profile picture
4. Click "View photo"

## Expected Result:
The profile preview header should display "Profile picture" since "Avatar" is typically reserved for system pictures

## Actual Result:
The profile preview header incorrectly shows "Profile avatar" instead of "Profile picture" when viewing the uploaded picture

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**Dev 1.3.71.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dc32ec8e-22e8-4aaf-b33c-81b017c09759

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695124664035289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e666bdf8b410257</li>
        <li>Upwork Job ID: 1704134028522778624</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-09-19 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Wrong Title is shown when previewing a Profile Photo.

### What is the root cause of that problem?
- Its showing the title of `Profile avatar` instead of `Profile picture`.

- https://github.com/Expensify/App/pull/22145

Introduced in above PR.

- https://github.com/Expensify/App/pull/22145#issuecomment-1725340236 (Comment which asked to change to `Profile picture`)

### What changes do you think we should make in order to solve the problem?
- We will add translation key `profilePicture` in `en.ts` and `es.ts`

- EN - `Profile picture`
- ES - `Foto de perfil`

And we will make change in `ProfilePage`, changing `profileAvatar` to `profilePicture`.

### What alternative solutions did you explore? (Optional)
-

**Comment by lcsvcn** [comment] 2023-09-19 14:32
# Proposal
## Please re-state the problem that we are trying to solve in this issue
All - The profile preview header displays "Profile avatar" instead of "Profile picture"

## What is the root cause of that problem?
The cause of the problem is that there is no Profile Picture text in the language folder files. To solve it, we just need to add.


## What changes do you think we should make in order to solve the problem?

At src/pages/settings/Profile/ProfilePage.js:
```
    <AvatarWithImagePicker
                    (...)
                    headerTitle={props.translate('profilePage.profilePicture')}
                />
```
At en.ts:

```
  profilePage: {
       (...)
        profilePicture: 'Profile picture', 
    },
```

At es.ts:

```
 profilePage: {
        (...)
        profilePicture: 'Imagen de perfil' // or 'Foto de perfil', but it would be more close to 'Profile Photo'
    },
```
## What alternative solutions did you explore? (Optional)

**Comment by PiyushChandra17** [comment] 2023-09-19 16:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - The profile preview header displays "Profile avatar" instead of "Profile picture"

### What is the root cause of that problem?
We are using `profileAvatar` here

https://github.com/Expensify/App/blob/496943389debfb0bc0dc453da81950e28ceebad2/src/pages/settings/Profile/ProfilePage.js#L130

Perhaps this is the root cause.

### What changes do you think we should make in order to solve the problem?
We need to apply following changes:
- Add `profilePicture: Profile picture` here
https://github.com/Expensify/App/blob/496943389debfb0bc0dc453da81950e28ceebad2/src/languages/en.ts#L588

- Replace `profileAvatar` with `profilePicture` here
https://github.com/Expensify/App/blob/496943389debfb0bc0dc453da81950e28ceebad2/src/pages/settings/Profile/ProfilePage.js#L130

### What alternative solutions did you explore? (Optional)
NA

### Result:
<img width="1418" alt="pp" src="https://github.com/Expensify/App/assets/47579287/24d1f503-babb-40d4-9946-6a27c1ba6cc8">

**Comment by joekaufmanexpensify** [comment] 2023-09-20 07:44
I don't think this is a bug. Discussing [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1695195877371069?thread_ts=1695124664.035289&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2023-09-21 08:18
Closing per the Slack thread!

**Closed by joekaufmanexpensify** 2023-09-21 08:18 UTC
Labels: External, Daily, Help Wanted
