### ISSUE TITLE
Task - Even though there is a Display Name, when assigning a task, only email shows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39555] opened 2024-04-03 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+1@gmail.com nhut.nguyen+3@salto.vn
**Issue reported by:** Applause - Internal team

## Action Performed:
Pre-condition: 2 account with Display Name set done.
1. Open the app
2. Go to any chat
3. Tap on "+" and tap on Assign Task
4. Find the account second by email

## Expected Result:
If the account was set to display name, it should shows Display Name

## Actual Result:
Even though there is a Display Name when assigning a task, only email shows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fafac269-a748-4a11-bc2f-2cbdbfa7bf2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2024-04-03 21:58
Duplicate of https://github.com/Expensify/App/issues/39426
and this the new expected behavior `prioritize login over display name for all the mentions in the app including task preview` https://github.com/Expensify/App/issues/39426#issuecomment-2032929258

**Comment by strepanier03** [comment] 2024-04-15 23:37
Closing out!

**Closed by strepanier03** 2024-04-15 23:37 UTC
Labels: Daily, Overdue, Bug
