### ISSUE TITLE
Notifications-In room chat, notifications are not received instantly when set notifications to "Immediately"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49171] opened 2024-09-13 12:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4955426
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause-Internal team

## Action Performed:
1. Launch app
2. User A creates a room
3. Set notifications to immediately
4. Invite user B
5. In other device, open room chat
6. Tap header and change notifications settings to immediately
7. Send message from user A to user B in room
8. Note messages are received but notifications are not displayed

## Expected Result:
In room chat, notifications must be received immediately.

## Actual Result:
In room chat, notifications are not received immediately.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/073b6b99-3d81-4f29-9e38-127e5a79804c

https://github.com/user-attachments/assets/fa42e2f7-275a-4b22-b768-57ed6dd5f17b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2024-09-16 04:42
Android <> ios bug swap!

**Comment by jliexpensify** [comment] 2024-09-16 04:51
@izarutskaya I can't reproduce on 35-2, can you retest this and share a new video?

**Comment by jliexpensify** [comment] 2024-09-19 23:10
Still can't repro, closing.

**Closed by jliexpensify** 2024-09-19 23:10 UTC
Labels: Daily, Overdue, Bug
