### ISSUE TITLE
Workspace - Start over page is not shown when user quits bank account setup and revisits it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31212] opened 2023-11-10 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace.
3. Click Bank account.
4. Click Connect manually.
5. Proceed until Step 3 of bank account setup.
6. Close the setup by clicking outside the RHN.
7. Go to Settings > Workspaces > any workspace.
8. Click Bank account.

## Expected Result:
User will be presented with 'Continue with setup' and 'Start over' screen.

## Actual Result:
User is redirected to where the bank account setup is left off.
In order to see 'Continue with setup' and 'Start over' screen, user has to return to the first screen.
On PROD, user is presented with 'Continue with setup' and 'Start over' screen after closing the setup and revisiting bank account page.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4f8e1f97-c099-4aae-ac9e-741cfb3a3e3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2023-11-10 20:47
https://github.com/Expensify/App/pull/29166 might be related

**Comment by johnmlee101** [comment] 2023-11-10 20:51
Asked in deployer for some extra 👀

**Comment by johnmlee101** [comment] 2023-11-10 20:58
Reverted it locally and it fixes it, so marking it as a regression

**Comment by johnmlee101** [comment] 2023-11-10 21:27
Revert PR https://github.com/Expensify/App/pull/31214 will need to be CPd

**Comment by johnmlee101** [comment] 2023-11-10 22:19
fixed since the revert

**Comment by johnmlee101** [comment] 2023-11-10 22:19
https://github.com/Expensify/App/assets/5258036/cb49b22c-2c30-4910-a6d7-5b5185e1e285

**Comment by puneetlath** [comment] 2023-11-10 22:27
Great! Closing this!

**Closed by puneetlath** 2023-11-10 22:27 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
