### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Policy member can't rename the room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34950] opened 2024-01-23 07:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jasperhuangg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705942899968899

## Action Performed:
1. Create room as account A and user B is member of the workspace of the room created
2. login as user B and open the room created in step1

## Expected Result:
User B is able to edit the room name
## Actual Result:
Unable to edit
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (4) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/43996225/a0034a8a-65ae-4cea-afe8-693e4c00307d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016496a22ef9dd8599</li>
        <li>Upwork Job ID: 1749697772594622464</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28122724</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-23 07:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace member can't rename the room name.

### What is the root cause of that problem?
We currently disallow member to edit the name.
https://github.com/Expensify/App/blob/c0608977d90835b34382325732e755733c034240/src/libs/ReportUtils.ts#L4186-L4193

and only allow for workspace owner and admin (aren't they the same?).

### What changes do you think we should make in order to solve the problem?

It the user is a member of the workspace, then returns false.

**Comment by Christinadobrzyn** [comment] 2024-01-23 18:42
I agree that we should allow anyone in the room to rename the room - I think this can be external and we have some proposals to review when you have a moment @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2024-01-23 19:57
@bernhardoj 
> If the user is a member of the workspace, then returns false (instead of the long condition)

How you would check that? Can you share the changes you propose in a new comment? thanks!

@Christinadobrzyn  
Can a user with a role auditor edit roomname?

**Comment by bernhardoj** [comment] 2024-01-24 02:33
```
if (!policy) {
    return true
}

return false
```

We will just do it like this. If the policy onyx data exists, then the user is a member of the policy.

https://github.com/Expensify/App/blob/c0608977d90835b34382325732e755733c034240/src/libs/ReportUtils.ts#L4190-L4191
https://github.com/Expensify/App/blob/c0608977d90835b34382325732e755733c034240/src/libs/ReportUtils.ts#L4184-L4188

**Comment by Santhosh-Sellavel** [comment] 2024-01-24 19:47
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/34950#issuecomment-1905462075) looks good to me!

C+ Reviewed
🎀 👀 🎀

**Comment by bernhardoj** [comment] 2024-01-26 06:57
PR is ready

cc: @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 18:33
We can skip the checklist here, it was intentional earlier & we are allowing members to update now.

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: N/A
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [x]  [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2024-02-07 00:25
payment tomorrow 

Payouts due:

Contributor: $500 @bernhardoj (In Upwork - https://www.upwork.com/nx/wm/offer/28122724)
Contributor+: $500 @Santhosh-Sellavel (in NewExpensify)

**Comment by Christinadobrzyn** [comment] 2024-02-08 00:23
Payment day! 

paid out based on this payment summary - https://github.com/Expensify/App/issues/34950#issuecomment-1931014376

No regression test so I think this can be closed as complete! Thanks every one!

**Closed by Christinadobrzyn** 2024-02-08 00:23 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-10 20:40
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-02-11 13:06
$500 approved for @Santhosh-Sellavel based on summary above.
