### ISSUE TITLE
[$1000] DEV: Account appears twice when inviting new members to workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23333] opened 2023-07-21 04:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create 2 accounts
2. Start a conversation from account1 with account2 and send a message
3. Create a workspace with account1 and go to invite a new member

The account2 appears twice in the list with different default avatars
## Expected Result:
Account 2 should appear once
## Actual Result:
The account2 appears twice in the list with different default avatars
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** dev 
**Reproducible in production?:**dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (3)](https://github.com/Expensify/App/assets/43996225/b7ed43a5-3404-4603-a4c9-d50178cf6b3d)

![image (4)](https://github.com/Expensify/App/assets/43996225/dc808296-dfed-44a0-b6a9-d68ab82b5b7c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689789846240869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e19b62701e8ddac</li>
        <li>Upwork Job ID: 1683957636264329216</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-07-23 16:08
I ran out of time on Friday, I'll review soon.

**Comment by alexpensify** [comment] 2023-07-25 21:50
Assigning external to accept proposals. @Santhosh-Sellavel can you please review the one from @huzaifa-99 and see if it will resolve this issue? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 00:47
Unable to reproduce @alexpensify 

https://github.com/Expensify/App/assets/85645967/854eab46-091c-4ca6-9f29-f4c861804f07

**Comment by aldo-expensify** [comment] 2023-07-26 00:52
I can reproduce in staging... maybe there is something about the domain:

<img width="749" alt="image" src="https://github.com/Expensify/App/assets/87341702/bf304453-7c3c-4396-9af5-10e7d9b21576">

**Comment by aldo-expensify** [comment] 2023-07-26 00:59
I'm failing to reproduce in DEV, maybe it got fixed?

<img width="1012" alt="image" src="https://github.com/Expensify/App/assets/87341702/4659b0ac-34a4-4cb8-b36e-09d9d7dcf6bd">

The only problem I see is the wrong avatar, but there is already another issue related to that.

**Comment by aldo-expensify** [comment] 2023-07-26 00:59
Maybe we can HOLD until the next deploy and verify if it got fixed or not in staging.

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:22
@aldo-expensify Please validate this [proposal](https://github.com/Expensify/App/issues/23333#issuecomment-1644979408)

**Comment by aldo-expensify** [comment] 2023-07-26 01:57
> This is already dupe of https://github.com/Expensify/App/issues/21706

true, closing this.

**Closed by aldo-expensify** 2023-07-26 01:57 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug

**Comment by alexpensify** [comment] 2023-07-26 14:13
Thanks for catching @aimane-chnaif! Thank you to @Santhosh-Sellavel and @aldo-expensify for your feedback here too!

**Comment by alexpensify** [comment] 2023-07-26 14:13
I've closed the job in Upwork too!
