### ISSUE TITLE
[HOLD for payment 2024-02-05]  [$500] SignInWithShortLivedAuthToken sometimes gets called in a loop

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#33413] opened 2023-12-21 13:42 UTC
**Version Number:** all
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** everyone it seems like
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://expensify.slack.com/archives/C03TQ48KC/p1702405892791069
**Issue reported by:** Expensify
**Slack conversation:** https://expensify.slack.com/archives/C03TQ48KC/p1702405892791069

## Action Performed:
We've seen several requests in our server logs where SignInWithShortLivedAuthToken is called in what seems like a loop, example:
![image](https://github.com/Expensify/App/assets/4164921/e4a0a2dc-6380-4c20-9168-24d476151d25)

2 more internal examples here:
https://github.com/Expensify/Expensify/issues/343028
https://github.com/Expensify/Expensify/issues/345424

## Expected Result:
SignInWithShortLivedAuthToken should not be called dozens / hundreds of times in a row by the same user

## Actual Result:
.

## Workaround:
Can the user still use Expensify without this being fixed? 

Not really, it requires us to manually delete the hundreds of logins, because they make the authentication unbearably slow.

## Platforms:

Which of our officially supported platforms is this issue occurring on?

I guess all

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

See above

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127bcdf935f2ba4af</li>
        <li>Upwork Job ID: 1737830869162020864</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by FitseTLT** [comment] 2023-12-21 13:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SignInWithShortLivedAuthToken sometimes gets called in a loop

### What is the root cause of that problem?
We have called `signInWithShortLivedAuthToken` without checking account.isLoading is false
### What changes do you think we should make in order to solve the problem?

We should call `signInWithShortLivedAuthToken` after checking account.isLoading is false
https://github.com/Expensify/App/blob/2f7c2b2caa32002455165965d140230a38e3f18c/src/pages/LogOutPreviousUserPage.js#L54
### What alternative solutions did you explore? (Optional)

**Comment by AmjedNazzal** [comment] 2023-12-21 14:01
@flodnv Is there a particular action showing on your end where this loop happens? I've tried opening a WS from OD while ND is logged out and while it's logged in with a different user and I'm seeing only one `SignInWithShortLivedAuthToken` call being made
<img width="1280" alt="shortauth" src="https://github.com/Expensify/App/assets/74202751/e15a1ea2-d326-4f47-989f-63349b1ed684">

**Comment by ikevin127** [comment] 2023-12-21 14:05
# Proposal

## Please re-state the problem that we are trying to solve in this issue

`Session.signInWithShortLivedAuthToken` is being called in a loop.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/b966bd43e690a17c09adcfec15d5c98ebdbf7559/src/pages/LogInWithShortLivedAuthTokenPage.js#L61

https://github.com/Expensify/App/blob/b966bd43e690a17c09adcfec15d5c98ebdbf7559/src/pages/LogOutPreviousUserPage.js#L54

We have the 2 useEffects mentioned above and out of the 2, the first one is more likely to cause a loop of `signInWithShortLivedAuthToken` because the function is called conditionally based on the presence of `shortLivedAuthToken` and `props.account.isLoading`. If `shortLivedAuthToken` is present and `props.account.isLoading` is `false`, the function is called.

However, there is no check or condition to prevent this useEffect from running again if the state of `props.account.isLoading` changes. If something triggers a re-render with a change in `props.account.isLoading`, and the conditions for calling `signInWithShortLivedAuthToken` are met, it will result in a loop.

## What changes do you think we should make in order to solve the problem?

To prevent a potential loop in the useEffect, we need to add an additional condition to check whether `signInWithShortLivedAuthToken` has already been called to avoid redundant calls when the component re-renders due to changes in other props or state.

We can use a ref to keep track of whether the function has been already called.

**Comment by flodnv** [comment] 2023-12-21 14:36
>@flodnv Is there a particular action showing on your end where this loop happens?

Honestly I'm not sure 😬

**Comment by flodnv** [comment] 2023-12-22 08:15
@Santhosh-Sellavel please let us know what you think about the proposal 🙇

**Comment by Santhosh-Sellavel** [comment] 2023-12-25 18:17
@flodnv 
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/33413#issuecomment-1866295616) looks good to me.

**Comment by Santhosh-Sellavel** [comment] 2023-12-28 18:28
@FitseTLT's https://github.com/Expensify/App/issues/33413#issuecomment-1866295616 looks good to me.
C+ Reviewed
🎀 👀 🎀

**Comment by arosiclair** [comment] 2023-12-29 17:01
Were you able to reproduce the issue @FitseTLT? I get the feeling we are trying something without knowing if it actually works.

Also this

> redundant requests can be sent to the server if for e.g the useEffect is called repeatedly with a change of dependency.

sounds like it might be the real root cause of the problem. This effect's dependency array looks very suspicious:

https://github.com/Expensify/App/blob/2f7c2b2caa32002455165965d140230a38e3f18c/src/pages/LogOutPreviousUserPage.js#L67

This transition flow is very fragile so let's make sure we're doing this the right way.

**Comment by Santhosh-Sellavel** [comment] 2024-01-01 18:53
@kadiealexander Can we get more details about this internal issues?
https://github.com/Expensify/Expensify/issues/343028
https://github.com/Expensify/Expensify/issues/345424

**Comment by arosiclair** [comment] 2024-01-04 19:20
> @kadiealexander Can we get more details about this internal issues? [Expensify/Expensify#343028](https://github.com/Expensify/Expensify/issues/343028) [Expensify/Expensify#345424](https://github.com/Expensify/Expensify/issues/345424)

These were two instances of our users not being able to log into OldDot. Their magic code and 2FA codes would return as "invalid". The root of those problems was over a thousand login attempts being generated on their accounts from `SignInWithShortLivedAuthToken` which we had to clear out manually.

**Comment by arosiclair** [comment] 2024-01-04 19:24
bump @FitseTLT [here](https://github.com/Expensify/App/issues/33413#issuecomment-1872220807)

Also cc @roryabraham since you're on the blame for the that useEffect change for the LogOutPreviousUserPage

**Comment by roryabraham** [comment] 2024-01-05 01:25
Yeah, I agree that `useEffect` looks sus. If any of the props passed are not a stable reference that could explain why the `useEffect` could get called in an infinite loop.

**Comment by roryabraham** [comment] 2024-01-05 01:27
I actually think that @FitseTLT's proposal makes sense too, though I agree without a reproduction we're kind of just trying stuff.

**Comment by roryabraham** [comment] 2024-01-05 07:00
The `useEffect` looks like it will be fixed (or at least, less sus) in [in the TS migration PR for `LogOutPreviousUserPage`](https://github.com/Expensify/App/pull/32973/files)

**Comment by arosiclair** [comment] 2024-01-05 16:57
Cool, let's hold on that PR for now

**Comment by arosiclair** [comment] 2024-01-09 00:15
Still held

**Comment by roryabraham** [comment] 2024-01-10 19:11
Sorry, I forgot to mention in here that https://github.com/Expensify/App/pull/32973 is stalled and needs an internal volunteer to take over.

**Comment by roryabraham** [comment] 2024-01-10 19:15
Taking this off HOLD because nobody is currently working on https://github.com/Expensify/App/pull/32973

**Comment by roryabraham** [comment] 2024-01-10 19:16
Also, just TBC we don't necessarily need to HOLD this on the TS migration to fix that `useEffect`'s dependencies, it's just that TS files enforce prop destructuring, which in turn fixes the `useEffect`'s dependencies

**Comment by arosiclair** [comment] 2024-01-10 20:57
Taking a look at this. I'll try to repro and use the same dependency change that we're planning in the TS migration PR.

**Comment by arosiclair** [comment] 2024-01-11 00:01
Okay one of the root issues I see here is that LogOutPreviousUserPage is doing too many things. We originally intended it to be single purpose: logging the current user out cc @neil-marcellini

[This block](https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/LogOutPreviousUserPage.js#L57-L65) is redundant because we're already handling navigating to `exitTo` in `App.setupPoliciesAndNavigate` [here](https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/libs/actions/App.ts#L400-L409). It also doesn't call `endSignOnTransition` which is might be problematic. Once this is removed, the effect's dependency on `props` can be removed and it can just run once on mount.

I'm drafting a PR and I'm going to run some tests.

**Comment by flodnv** [comment] 2024-01-18 14:45
It seems like the problem still persists, internal details in https://github.com/Expensify/Expensify/issues/360016#issuecomment-1898616495

**Comment by FitseTLT** [comment] 2024-01-18 14:51
If there is no special case where we want to send another request while `account.isLoading` or in other words send another request before the previous sent request has received a response from the server why don't we go with my [proposal](https://github.com/Expensify/App/issues/33413#issuecomment-1866295616)] ? It will definitely solve the problem.

**Comment by arosiclair** [comment] 2024-01-18 22:26
This definitely seems to be coming from the SAML/SSO sign in flow specifically. Here's [logs coming from one of our users yesterday](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22846feed0afe07ac1-SJC%22)+AND+timestamp:[2024-01-17T15:21:43.169Z+TO+2024-01-17T17:21:43.169Z]&index=logs_expensify-026325). `SignInWithShortLivedAuthToken` was called 6 times in this case and they did log in successfully. I'll try this locally, it's going to require a bit of setup though.

**Comment by arosiclair** [comment] 2024-01-18 22:50
> If there is no special case where we want to send another request while account.isLoading or in other words send another request before the previous sent request has received a response from the server why don't we go with my https://github.com/Expensify/App/issues/33413#issuecomment-1866295616] ? It will definitely solve the problem.

It seems like you never reproduced the issue so we don't know if your proposal actually fixes it. If we have an effect running a request repeatedly, waiting for the request to finish doesn't really stop the effect from running the request again after. So no, we're not so sure that "it will definitely solve the problem". Moreover, the root problem is that these effects are running many times when they probably shouldn't and your proposal does not fix that.

**Comment by arosiclair** [comment] 2024-01-22 17:42
I setup a test environment, but was unable to test the SSO flow on iOS because of this error. There doesn't seem to be an easy fix atm. I'm attempting to do the same on Android.

<img width="200" src="https://github.com/Expensify/App/assets/6833644/5462d2ab-b807-46c4-9423-2730fabdbd03" />

**Comment by arosiclair** [comment] 2024-01-22 22:47
After lots of trying, it seems like the SAML sign-in flow is not really testable on native in dev at the moment. If there is still a bug, it seems to be from [the WebView navigation change handler](https://github.com/Expensify/App/blob/0c5db5fe676afcd288ee835369fac1620727d4aa/src/pages/signin/SAMLSignInPage/index.native.js#L37-L58) being called many times triggering multiple sign-ins. This might be due to redirects during the sign-in process which is something that we probably can't fix. 

I'm pushing some extra logging and part of @FitseTLT's original [proposal](https://github.com/Expensify/App/issues/33413#issuecomment-1866295616) and will test on staging. If/when this re-occurs we'll re-investigate.

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 18:45
@arosiclair Can you help me with the checklist here?

**Comment by arosiclair** [comment] 2024-02-05 14:02
Instead of adding regressions tests we are probably going to add rate limiting to this endpoint to prevent this in the future. Checklist should be all set @kadiealexander @Santhosh-Sellavel

**Comment by kadiealexander** [comment] 2024-02-07 05:35
Closing, please request your payment in NewDot Santhosh!

**Closed by kadiealexander** 2024-02-07 05:35 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-10 21:08
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-02-11 13:08
$500 approved for @Santhosh-Sellavel based on summary above.
