### ISSUE TITLE
[$250] Workspace - Account title is not displaying on Export out-of-pocket expenses as

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43130] opened 2024-06-05 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.79-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/42561
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to any applause.expensifail.com domain account
2. Create a new workspace
3. Connect to QBO with applausetester+qbo@applause.expensifail.com (1password)
4. Do not sync 
5. Go to Workspace > Accounting
6. Click on Export > Export company cards as > Account
7. Verify that if there is no account to select then a message "No accounts found" is displayed
8. Notice Accounts payable title is not displaying and not on header

## Expected Result:
Accounts payable should be displayed

## Actual Result:
Account title is not displaying on Export out-of-pocket expenses as

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7a1f109a-d95c-4ff0-8b0d-37f1208d9957

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef0ff96f7581526a</li>
        <li>Upwork Job ID: 1798406753219738599</li>
        <li>Last Price Increase: 2024-06-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by kbecciv** [comment] 2024-06-05 15:08
We think that this bug might be related to #wave-collect - Release 1

**Comment by kavimuru** [comment] 2024-06-05 17:18
@hayata-suenaga tagging you as per this [comment](https://expensify.slack.com/archives/C9YU7BX5M/p1717187351117029)

**Comment by kavimuru** [comment] 2024-06-05 17:19
@hayata-suenaga tagging you per [this comment](https://expensify.slack.com/archives/C9YU7BX5M/p1717187351117029)

**Comment by neil-marcellini** [comment] 2024-06-05 17:29
Looks like a frontend bug

**Comment by yuwenmemon** [comment] 2024-06-05 18:17
I can't reproduce this. What account are we using to connect to QBO here?

**Comment by kavimuru** [comment] 2024-06-05 18:52
@yuwenmemon I have updated the original post. 

1. Sign in to any applause.expensifail.com domain account
2. Create a new workspace
3. Connect to QBO with [applausetester+qbo@applause.expensifail.com](mailto:applausetester+qbo@applause.expensifail.com) (1password)
4. Do not sync
5. Go to Workspace > Accounting
6. Click on Export > Export company cards as > Account
7. Verify that if there is no account to select then a message "No accounts found" is displayed
8. Notice Accounts payable title is not displaying and not on header

**Comment by hayata-suenaga** [comment] 2024-06-05 18:54
I think this is a pusher issue. It's possible for the client to miss pusher events.

I think these pusher events are sent from the Integration Server, which we don't have reliable updates 😓

**Comment by yuwenmemon** [comment] 2024-06-05 19:15
@kavimuru How can one connect to QBO and not sync? Can you post a video of you doing that?

**Comment by hayata-suenaga** [comment] 2024-06-05 19:47
I think this is kind of same as [this one](https://expensify.slack.com/archives/C036QM0SLJK/p1717422872999129)

**Comment by kavimuru** [comment] 2024-06-05 19:55
@yuwenmemon here is the video.

https://github.com/Expensify/App/assets/43996225/8de28a6b-fb77-4a22-9a2c-527f3a426665

**Comment by yuwenmemon** [comment] 2024-06-05 21:32
Hmmm... Odd I'm still not able to reproduce 🤔 
<img width="1552" alt="Screenshot 2024-06-05 at 2 30 31 PM" src="https://github.com/Expensify/App/assets/4741899/ebf77933-ba75-4e7f-ba4f-4f819e296e0c">

Could this possibly have been related to Onyx Updates being turned off maybe?

**Comment by yuwenmemon** [comment] 2024-06-05 21:35
Anyway, regardless this does not seem to be a blocker to me as  I'm unable to reproduce on both accounts on staging, and it would most likely be due to a back-end issue anyway.

**Comment by hayata-suenaga** [comment] 2024-06-06 16:45
[Asking the QA team for retest with additional instructions](https://expensify.slack.com/archives/C9YU7BX5M/p1717692237722309)

**Comment by kbecciv** [comment] 2024-06-08 10:46
Issue is not reproducible

https://github.com/Expensify/App/assets/93399543/c709e470-c0b8-40b5-a046-4342b1ab7883

**Comment by jjcoffee** [comment] 2024-06-12 08:40
@yuwenmemon I think we can close this?

**Comment by yuwenmemon** [comment] 2024-06-12 18:52
Sweet!

**Closed by yuwenmemon** 2024-06-12 18:52 UTC
Labels: Engineering, Daily, Internal, Help Wanted
