### ISSUE TITLE
Workspace - In workspace list,1 is displayed with space in android but not in mweb

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45893] opened 2024-07-22 10:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app in both mweb and android with same account using one after plus in email accounts (eg: [applausetester+111@applause.expensifail.com](mailto:applausetester+111@applause.expensifail.com)
)
2. Tap profile -- workspaces -- workspace
3. Under Workspace name, note the number one format in the email id displayed

## Expected Result:
In workspace list, number 1 should be displayed with same spacing in android & mweb.

## Actual Result:
In workspace list, number 1 is displayed with space in android but not in mweb. Inconsistency in behaviour.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6549091_1721633169434!Screenshot_2024-07-22-12-49-38-318_com android chrome-edit](https://github.com/user-attachments/assets/e892d713-335e-4619-93e2-686a59cb7692)

![Bug6549091_1721633169427!Screenshot_2024-07-22-12-50-43-594_com expensify chat-edit](https://github.com/user-attachments/assets/ae0914c3-38ae-418d-9b42-cc322886b698)

https://github.com/user-attachments/assets/04464dcf-cfad-4469-a1f6-d689e8bbb930

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-07-22 10:47
We think this issue might be related to the  #vip-vsb

**Comment by Sparth19** [comment] 2024-07-23 06:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- In the workspace list, a workspace name containing "1" is displayed with extra space on Android but not on the mobile web (mWeb), indicating an inconsistency in behavior.

### What is the root cause of that problem?

- We are applying the labelStrong style to the workspace name as shown below:
- To apply bold styling, we need to manage different styles according to the platform, which is already handled [here](https://github.com/Expensify/App/blob/8e4dc0f032387c00e7ae4a51aff4792bdede5bfa/src/styles/utils/FontUtils/fontWeight/bold/index.ts#L3)

https://github.com/Expensify/App/blob/8e4dc0f032387c00e7ae4a51aff4792bdede5bfa/src/pages/workspace/WorkspacesListRow.tsx#L220-L225

https://github.com/Expensify/App/blob/8e4dc0f032387c00e7ae4a51aff4792bdede5bfa/src/styles/index.ts#L1370-L1375



### What changes do you think we should make in order to solve the problem?

- We need to update the style object as shown below to ensure consistency across the app and all platforms:

```
fontFamily: FontUtils.fontFamily.platform.EXP_NEUE_BOLD,
fontWeight: FontUtils.fontWeight.bold,
```

### What alternative solutions did you explore? (Optional)

### Result after changes
![Screenshot 2024-07-23 at 11 55 48 AM](https://github.com/user-attachments/assets/05ab5348-a55b-44bb-ae9d-22723f412282)
![Screenshot 2024-07-23 at 11 55 57 AM](https://github.com/user-attachments/assets/929221f1-b88b-44a9-8db7-dc7eb5b6fb76)

**Comment by zanyrenney** [comment] 2024-07-24 20:40
This seems like extreme polish and not critical given the roadmap priorities, closing.

**Closed by zanyrenney** 2024-07-24 20:40 UTC
Labels: Daily, Overdue, Bug
