### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] Web -  Task avatar not correct when sharing it in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26572] opened 2023-09-02 18:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace.
2. Create a new task
3. Select the share destination as the workspace chat of the current account.

## Expected Result:
The workspace icon at the bottom right should be correct

## Actual Result:
The workspace icon at the bottom right is invalid and only gets updated after sending a message in the task report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e63be497-8c57-4072-8897-eebd7789c0fd

https://github.com/Expensify/App/assets/93399543/ec237a65-cd57-46ac-9964-34814ded9e58

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693145642005219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e42a684a1fd73bba</li>
        <li>Upwork Job ID: 1699077008312233984</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26767060</li>
<li>esh-g | Contributor | 26767062</li>
<li>esh-g | Reporter | 26767064</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-09-02 18:19
# Proposal

by @esh-g

## Please re-state the problem we are trying to solve
Unavailable workspace avatar is seen as subscript of a task that is shared in the `ownPolicyExpenseChat`

## What is the root cause of this?
The root cause is that the `taskReport` when created optimistically, does not possess a `policyID` but it is a child of a `policyExpenseChat` so the avatar of workspace is shown but since `policyID` is `undefined`, the avatar shown is of `Unavailable Workspace` starting with `U`.
We can see in the following snippet that we are specifically handling avatar cases for `WorkspaceTaskReport`:
https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportUtils.js#L981-L984

## What changes should be made in-order to fix this?
We should add `policyID` of the parent report while building optimistic data for `taskReport` here:
https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportUtils.js#L2483-L2496
And this can be done by adding this line in the body of the function: 
```js
const policyID = lodashGet(allReports[`${ONYXKEYS.COLLECTION.REPORT}${parentReportID}`], 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE);
```

Then we can just return `policyID` as well.
PS: Here I'm using `CONST.POLICY.OWNER_EMAIL_FAKE` instead of `CONST.POLICY.OWNER_ACCOUNT_ID_FAKE` even though it says `policyID` because I saw this being used in other places as well.

## What other alternatives did you explore? (Optional)
- We can have the `buildOptimisticTaskReport()` function accept the `policyID` as an argument that can be passed while creating the task.

**Comment by kbecciv** [comment] 2023-09-02 18:19
Proposal  by: @esh-g
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693145642005219


# Proposal

by @esh-g

## Please re-state the problem we are trying to solve
Unavailable workspace avatar is seen as subscript of a task that is shared in the `ownPolicyExpenseChat`

## What is the root cause of this?
The root cause is that the `taskReport` when created optimistically, does not possess a `policyID` but it is a child of a `policyExpenseChat` so the avatar of workspace is shown but since `policyID` is `undefined`, the avatar shown is of `Unavailable Workspace` starting with `U`.
We can see in the following snippet that we are specifically handling avatar cases for `WorkspaceTaskReport`:
https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportUtils.js#L981-L984

## What changes should be made in-order to fix this?
We should add `policyID` of the parent report while building optimistic data for `taskReport` here:
https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportUtils.js#L2483-L2496
And this can be done by adding this line in the body of the function: 
```js
const policyID = lodashGet(allReports[`${ONYXKEYS.COLLECTION.REPORT}${parentReportID}`], 'policyID', CONST.POLICY.OWNER_EMAIL_FAKE);
```

Then we can just return `policyID` as well.
PS: Here I'm using `CONST.POLICY.OWNER_EMAIL_FAKE` instead of `CONST.POLICY.OWNER_ACCOUNT_ID_FAKE` even though it says `policyID` because I saw this being used in other places as well.

## What other alternatives did you explore? (Optional)
- We can have the `buildOptimisticTaskReport()` function accept the `policyID` as an argument that can be passed while creating the task.

**Comment by bfitzexpensify** [comment] 2023-09-05 15:08
Sending this external

**Comment by bfitzexpensify** [comment] 2023-09-08 11:17
@Ollyws looks like there's a proposal in https://github.com/Expensify/App/issues/26572#issuecomment-1703905503 for you to review when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-09-11 10:02
Just making a note to myself to check if this also solves https://expensify.slack.com/archives/C049HHMV9SM/p1693280387243559 once this has been resolved

**Comment by bfitzexpensify** [comment] 2023-09-13 11:47
Bump to review https://github.com/Expensify/App/issues/26572#issuecomment-1703905503 @Ollyws - thank you!

**Comment by bfitzexpensify** [comment] 2023-09-18 10:33
Another friendly bump on this one @Ollyws

**Comment by esh-g** [comment] 2023-09-19 19:06
@Ollyws Thanks for the positive review, but I would also like to ask that why shouldn't we just get the policy ID in the function body itself? Or is there some case where it would be different?

**Comment by esh-g** [comment] 2023-09-20 12:43
PR is here: https://github.com/Expensify/App/pull/27853 💫

**Comment by esh-g** [comment] 2023-09-21 09:31
@Ollyws A duplicate issue was made by @lanitochka17 here: https://github.com/Expensify/App/issues/27092 after the creation of this issue and they merged the PR before this

**Comment by esh-g** [comment] 2023-09-21 09:47
@Ollyws What do you think we should do now?

**Comment by esh-g** [comment] 2023-09-21 10:28
@Ollyws @luacmartins  I think a change can still be made to the solution applied currently, by setting the default value to `CONST.POLICY.OWNER_EMAIL_FAKE` instead of handing the case of `policyID = undefined`. I think this is how we handle the optimistic building of reports. Let me know what you think of this change as being more in line with the style of optimistic  report building and if yes, we can merge the current PR for this issue as well.

**Comment by luacmartins** [comment] 2023-09-22 00:06
@esh-g yes, let's make it consistent and use `OWNER_EMAIL_FAKE`

**Comment by esh-g** [comment] 2023-09-22 01:08
> @esh-g yes, let's make it consistent and use `OWNER_EMAIL_FAKE`

Great, I already have the changes in the PR @Ollyws

**Comment by esh-g** [comment] 2023-09-25 09:34
Is melvin bot correct? Shouldn't have today been the 3rd day? I got assigned on Thursday I think..

**Comment by luacmartins** [comment] 2023-09-26 01:59
I think so, I see the assignment on the 2023-09-20 7:52 UTC +8, which is the 2023-09-19 23:52 UTC
<img width="483" alt="Screenshot 2023-09-26 at 9 57 53 AM" src="https://github.com/Expensify/App/assets/22219519/059d604a-2732-4ee1-a03b-4c662bf5413a">

**Comment by bfitzexpensify** [comment] 2023-10-03 18:38
Moving this to daily so I see and action it on 10/5

**Comment by bfitzexpensify** [comment] 2023-10-05 17:26
Agreed. OK, payments have all been finalised, so we're good to close this out - thanks everyone!

**Closed by bfitzexpensify** 2023-10-05 17:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
