### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] [MEDIUM] "Concierge" is displayed in LHN and thread header for Concierge approval message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35660] opened 2024-02-02 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.3.45-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Employee are part of the Collect workspace.
- Schedule submit is enabled (Daily).
1. Go to workspace chat.
2. Create a distance request,
3. Go to expense report.
4. Click Submit.
5. Refresh the page.
6. Note that expense report preview in LHN.
7. Right click on the Concierge final approve message > Reply in thread.

## Expected Result:
In Step 6, the preview in LHN will show the complete message.
In Step 7, the thread header will show the complete message.

## Actual Result:
In Step 6, LHN preview shows just "Concierge".
In Step 7, the thread header shows just "Concierge" instead of complete Concierge final approve message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1a870a8d-cc9f-4001-8cce-239acd556453

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184792cdee67cc75a</li>
        <li>Upwork Job ID: 1753407551107751936</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28150317</li>
<li>FitseTLT | Contributor | 28150318</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-02 13:19
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by FitseTLT** [comment] 2024-02-02 14:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Concierge" is displayed in LHN and thread header for Concierge approval message

### What is the root cause of that problem?
Currently when we submit the lastmessage of the report is set to `message.0.text`
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/libs/actions/IOU.js#L3364-L3365
And the `alternateText` for the LHN will be set to `lastMessageText` here
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/libs/OptionsListUtils.ts#L569-L570
### What changes do you think we should make in order to solve the problem?

We have two options to solve it 
1. set the lastmessageText by iterating and joining `reportAction.message` here and of course in BE
https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/libs/actions/IOU.js#L3364-L3365
2. To change the logic we use in `OptionsListUtils.getLastMessageTextForReport` for `SUBMIT` type `lastReportAction` and set it to content of `reportAction.message` joined together.
### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2024-02-05 12:52
@akinwale can you review proposal? 🙇‍♂️

**Comment by akinwale** [comment] 2024-02-06 08:29
@FitseTLT Let's go with the solution that doesn't require a BE change.

We can move forward with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/35660#issuecomment-1923929042.

🎀👀🎀 C+ reviewed.

**Comment by dylanexpensify** [comment] 2024-02-07 10:33
Nice! @Gonals to confirm!

**Comment by Gonals** [comment] 2024-02-08 10:57
LGTM!

**Comment by FitseTLT** [comment] 2024-02-13 19:58
Will create one in 2 days

**Comment by dylanexpensify** [comment] 2024-02-20 09:41
@FitseTLT let's get it done today/tomorrow.

**Comment by FitseTLT** [comment] 2024-02-21 21:26
Will make the PR ready for review tomorrow

**Comment by dylanexpensify** [comment] 2024-02-28 08:56
PR up and in review! @akinwale what's our ETA

**Comment by dylanexpensify** [comment] 2024-03-06 11:15
PR merged, pending payout after regression period

**Comment by dylanexpensify** [comment] 2024-03-13 10:36
@akinwale can you complete checklist?

**Comment by dylanexpensify** [comment] 2024-03-13 10:36
Payment summary:
- Contributor: @FitseTLT $500
- Contributor+: @akinwale $500

Please apply/request!

**Comment by akinwale** [comment] 2024-03-13 10:39
> Payment summary:
> 
> * Contributor: @FitseTLT $500
> * Contributor+: @akinwale $500
> 
> Please apply/request!

@dylanexpensify I already accepted the automatic offer. https://www.upwork.com/nx/wm/workroom/36288112/overview

**Comment by FitseTLT** [comment] 2024-03-13 10:55
There is an already accepted offer @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-03-20 10:10
ah my apologies! Will pay that one out

**Comment by dylanexpensify** [comment] 2024-03-20 14:32
All done!

**Closed by dylanexpensify** 2024-03-20 14:32 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
