### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] DEV - Web - Console error when user try to drag and drop attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27375] opened 2023-09-13 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Drag any attachment and hover on header of chat

## Expected Result:
It should not show any console error

## Actual Result:
Console error appears (Uncaught TypeError: Cannot read properties of null (reading 'hideCreateMenu') )

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.67-0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eec39dea-2d1a-4a19-9883-523118ecc8a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694414342648769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eba922aef37e232</li>
        <li>Upwork Job ID: 1702001522393657344</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26722904</li>
<li>ishpaul777 | Contributor | 26722905</li>
<li>gadhiyamanan | Reporter | 26722906</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-13 17:12
## Proposal 
### Problem 
DEV - Web - Console error when user try to drag and drop attachment

### Root Cause 
We are initalizing the popover ref with null, and dont have a condition to return if `popoverRef.current` is  null when adding/removing dragover listner resulting in a console error when popover ref is null

### Changes
modify `SidebarScreen`
```jsx
   const onHideMenu = () => {
        if (popoverModal.current) {
            popoverModal.current.hideCreateMenu();
        }
    };

    /**
     * Method create event listener
     */
    const createDragoverListener = () => {
        document.addEventListener('dragover', onHideMenu);
    };

    /**
     * Method remove event listener.
     */
    const removeDragoverListener = () => {
        document.removeEventListener('dragover', onHideMenu);
    };
```

**Comment by ishpaul777** [comment] 2023-09-13 17:20
@0xmiroslav just pulled main and checked issue is not reproducable.

**Comment by ishpaul777** [comment] 2023-09-13 17:36
@0xmiroslav I think the issue here is even though we want to remove the eventlistner when removeDragoverListener is executed the listner never removed because we are passing anonymous while adding and removing listner.

Add a console.log in addEventListner, you will realize dragover listner is not removerd when FAB menu is closed.

```jsx
document.addEventListener('dragover', () => {
            console.log('dragover')
            popoverModal.current.hideCreateMenu()
        });
```

more info - https://stackoverflow.com/questions/10444077/javascript-removeeventlistener-not-working

**Comment by ishpaul777** [comment] 2023-09-13 17:42
The `removeDragoverListener` is meant to be executed to remove the listner isn't it ?

**Comment by ishpaul777** [comment] 2023-09-13 18:21
https://github.com/Expensify/App/assets/104348397/bef1ebae-0ea9-4a32-ad08-c9e4bb5e7aa2

**Comment by srikarparsi** [comment] 2023-09-18 00:52
Hi! Yes I do think think this should be fixed as well. Assigning you to the issue @ishpaul777

**Comment by johncschuster** [comment] 2023-10-04 21:31
Payment has been issued to everyone! Thanks!

**Comment by sonialiap** [comment] 2023-10-09 04:53
Reopening to make sure that @johncschuster sees the Q about bonus

**Comment by johncschuster** [comment] 2023-10-09 20:32
Urgency bonus has been issued to @0xmiroslav and @ishpaul777

**Closed by johncschuster** 2023-10-09 20:32 UTC
Labels: External, Daily, Awaiting Payment
