### ISSUE TITLE
Historical read reports all show as unread on sign-in (#focus mode). 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27105] opened 2023-09-10 11:22 UTC
Reproduction video. Consistently reproducible in contributorpayments@ account, which is in #focus mode. 

https://github.com/Expensify/App/assets/1127863/b7bac3d8-1ff6-46da-91ea-73dfacc0171a

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b9f2f54b3e99cd4</li>
        <li>Upwork Job ID: 1700832147552653312</li>
        <li>Last Price Increase: 2023-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by garrettmknight** [comment] 2023-09-13 09:21
@MonilBhavsar can you take a look at this?

**Comment by MonilBhavsar** [comment] 2023-09-15 03:08
This issue is very specific to this account. I got access to this account from Jason and looking at it now

**Comment by MonilBhavsar** [comment] 2023-09-15 04:02
Couple of reports that I opened and it triggered ReadNewsetAction and updated lastReadTime 3296734179110923 2324239146912458. Will reauthenticate and check if there are still returned as unread and shows bold in LHN

**Comment by MonilBhavsar** [comment] 2023-09-19 04:27
Re logged into those accounts today and looking for the specific reports that were marked as read 4 days back

**Comment by marcaaron** [comment] 2023-09-21 09:06
Working with @MonilBhavsar on this for a bit today and gonna try to summarize what we have seen so far... some things are still hazy, but this is the gist of what we are seeing.

1. Reports show up in `OpenApp`'s response without any `lastReadTime`. These are reports that we believe we have _definitely viewed_ before. Examples of this have been confirmed by both @trjExpensify and @JmillsExpensify 
2. What we saw is that these reports **have no rNVP for `lastRead_<accountID>` in the server**
3. So, to the user it looks like it's "unread" (there's no rNVP so we assume it is unread and it appears unread)
4. The user taps the report and we end up calling `OpenReport` with `null` for the `clientLastReadTime` parameter. We will hit [this code in Web-E](https://github.com/Expensify/Web-Expensify/blob/d34c6fce2039c971d15cea67f055335232ee8c3b/lib/ReportAPI.php#L4998) which will get `null` for the rNVP, **but then provide a fallback time of "now". This will be sent back to the caller via Pusher.**
5. By the time we navigate to the report the `ReportActionsList` renders and this [useEffect logic runs here](https://github.com/Expensify/App/blob/68d03fadc5737ca559f792cfc2b20b9a88d0c208/src/pages/home/report/ReportActionsList.js#L153-L159) the report is now "read" so we won't call `ReadNewestAction`. However, the report still does not have an rNVP set so it will just pop back to unread again.

**Conclusion:** We end up with a case where the report has no rNVP for a recipient, it appears as unread (correct behavior), but when they go to view it there is no possible way for them to set an rNVP for the report because the `lastRead` ends up with a value in Onyx, but never in the backend.

**Comment by marcaaron** [comment] 2023-09-21 09:24
This diff seems to fix it for me locally

```diff
@@ -4995,9 +4999,13 @@ class ReportAPI

             // Update the lastReadTime if it is new chat or lastReadTime provided by client is not up-to-date with server
             $accountID = $user->getAccountID();
-            $lastReadTime = $report->getNVP(Report::NVP_LAST_READ_TIME_PREFIX.$accountID) ?? (new DateTime('now'))->format(SQL_DATETIME_MS);
+            $lastReadTime = $report->getNVP(Report::NVP_LAST_READ_TIME_PREFIX.$accountID);
+            if ($isNewChat) {
+                $lastReadTime = (new DateTime('now'))->format(SQL_DATETIME_MS);
+            }
```

**Comment by JmillsExpensify** [comment] 2023-09-25 08:33
Linked PR is merged! Nice work.

**Comment by sakluger** [comment] 2023-09-27 03:20
@MonilBhavsar the PR was deployed to prod, we can close this issue now right?

**Comment by MonilBhavsar** [comment] 2023-09-27 03:22
Yes, we can close this!

**Comment by MonilBhavsar** [comment] 2023-10-25 17:33
This behavior is back again with different root cause. Context https://expensify.slack.com/archives/C04JD99283A/p1697568714681099
Looking into it...

**Comment by MonilBhavsar** [comment] 2023-10-25 18:13
The reports were exported by accounting team, and we created a reportAction for export action. That made report's `lastVisibleActionCreated` time greater than `lastReadTime` and hence all reports are displayed as unread.

Logs https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22ppPqVg%22)+AND+timestamp:[2023-10-24T19:40:31.248Z+TO+2023-10-24T21:40:31.248Z]&index=logs_expensify-024953

This issue is now very similar to https://github.com/Expensify/Expensify/issues/325443
Along with close/archive actions, I think we also should also not show unread if action is exported? In newDot there is no indication/system message that a report was updated(exported).

**Comment by JmillsExpensify** [comment] 2023-10-25 18:16
> Along with close/archive actions, I think we also should also not show unread if action is exported? In newDot there is no indication/system message that a report was updated(exported).

Wow that's a interesting one. I wonder if we should bring this to Slack, because it would be weird if we notify on some "system message" report actions (e.g. `$10 approved`) vs not notifying on others (e.g. `exported to NetSuite`).

**Comment by garrettmknight** [comment] 2023-12-12 17:14
@MonilBhavsar I'm not sure what's going on with this one - did you discuss in slack somewhere?

**Comment by MonilBhavsar** [comment] 2023-12-15 05:34
Not yet, I'll circle back to this soon. There are few actions - reimbursed, exported to Integration/CSV that needs to be whitelisted in newDot so that we display them. We actually push the reportAction to Onyx but is not rendered or displayed to user and that's why they are marked as unread.

**Comment by MonilBhavsar** [comment] 2023-12-29 10:33
Going to close this as a part of wave issue https://github.com/Expensify/Expensify/issues/347391

**Closed by MonilBhavsar** 2023-12-29 10:33 UTC
Labels: Daily, Internal, Bug
