### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Web - Cursor Remains as Hand Icon on Checkbox in "Paid By" Section During Split Bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28064] opened 2023-09-23 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and select "Send Message"
2. Add two emails and create a group with the two emails
3. Inside the chat, click on the plus sign and select "Split Bill"
4. Add the desired amount and click "Next"
5. Hover over email (cursor is disabled)
6. Hover over the checkbox (cursor changes to hand icon, but remains delectable)

## Expected Result:
When hovering over the checkbox in the "Paid By" section during split bill, the cursor should be disabled, just like when hovering over the associated email.

## Actual Result:
While hovering over the email, the cursor is properly disabled. However, when hovering over the checkboxes, the cursor changes to a hand icon during split bill.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52729e0f-869a-4063-8694-7243168c3c52

https://github.com/Expensify/App/assets/93399543/1d6eec3e-54f6-429c-aa36-7a95b6febe00

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695270713412089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8f7be88bc37af93</li>
        <li>Upwork Job ID: 1705585682941407232</li>
        <li>Last Price Increase: 2023-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27031408</li>
<li>esh-g | Contributor | 27031411</li>
<li>tewodrosGirmaA | Reporter | 27031412</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-09-23 14:11
# Proposal

## Please re-state the issue
Cursor is not disabled in `SelectCircle` when the option is disabled.

## What is the root cause of this issue?
The reason that the cursor is `disabled` on the rest of the row option is because we are passing the `isDisabled` prop to the `PressableWithFeedback` component wrapping the whole `OptionRow`.
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/OptionRow.js#L199

We are not passing the `isDisabled` prop to the `PressableWithFeedback` which wraps the `SelectCircle` component here:
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/OptionRow.js#L286-L292

## What changes do you think should be made to fix this problem?
We should pass the `isDisabled` prop the same way we pass it to the root `PressableWithFeedback` of the `OptionRow` as mentioned in the root cause.

**Optional:** 
We can also pass `isDisabled` prop to the `Button` element (the one which says 'split' or 'add to group' in the options) for consistency but since I don't see a case where the row with a button will be disabled, this is not required.

## What other alternative options did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-23 14:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The paid by row Pressable is disabled but hand cursor is shown on the selectRow even though it is unclickable
### What is the root cause of that problem?
We are not disabling this `Pressable`
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L286-L292
like we do here
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L199
### What changes do you think we should make in order to solve the problem?
We should use the same disabling here 
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L288
for this `Pressable` as well.
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-23 14:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The paid by row Pressable is disabled but hand cursor is shown on the selectRow even though it is unclickable
### What is the root cause of that problem?
We are not disabling this `Pressable`
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L286-L292
like we do here
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L199
### What changes do you think we should make in order to solve the problem?
We should use the same disabling here 
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L288
for this `Pressable` as well.
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-23 14:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The paid by row Pressable is disabled but hand cursor is shown on the selectRow even though it is unclickable
### What is the root cause of that problem?
We are not disabling this `Pressable`
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L286-L292
like we do here
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L199
### What changes do you think we should make in order to solve the problem?
We should use the same disabling here 
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L288
for this `Pressable` as well.
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-23 14:25
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The paid by row Pressable is disabled but hand cursor is shown on the selectRow even though it is unclickable
### What is the root cause of that problem?
We are not disabling this `Pressable`
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L286-L292
like we do here
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L199
### What changes do you think we should make in order to solve the problem?
We should use the same disabling here 
https://github.com/Expensify/App/blob/ee023d8ab36dd722a465c89bf4edff1b8e79aadf/src/components/OptionRow.js#L288
for this `Pressable` as well.
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-23 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor Remains as Hand Icon on Checkbox in "Paid By" Section During Split Bill

### What is the root cause of that problem?
We are using disable props for OptionRow
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/OptionRow.js#L199

But we don't do that for the checkbox
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/OptionRow.js#L286-L293

It causes the consistency
### What changes do you think we should make in order to solve the problem?
First, Let's see the transaction report, If we hover detail transactions, it display default cursor 
<img width="1440" alt="Screenshot 2023-09-24 at 01 46 52" src="https://github.com/Expensify/App/assets/141406735/e79cc597-bb81-472c-92e2-10b0d849da4b">

and cancelled task case: https://expensify.slack.com/archives/C049HHMV9SM/p1695024078116809?thread_ts=1694080698.301029&cid=C049HHMV9SM
In this case, we also should use the default cursor instead of disabled cursor for all option row (include checkbox) if want to disable that.

To do that: 
1. remove disable prop here
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/OptionRow.js#L199
2. add this style
```
 (!this.props.onSelectRow || this.props.isDisabled) ? styles.cursorDefault : null,
```

in 


### What alternative solutions did you explore? (Optional)

**Comment by JawadSadiq01** [comment] 2023-09-24 11:08
Hi, 

I can solve this issue, but couldn't able to locate this bug. There is only one group displaying on my screen And I also don't have much testing data.

**Request Money** option is displaying instead of **Split Money**. Please, would somebody help?

<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/174767ae-1e33-4b0f-96d7-ba4bf779ee01">

**Comment by JawadSadiq01** [comment] 2023-09-24 14:46
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Cursor Remains as Hand Icon on Checkbox in "Paid By" Section During Split Bill

**What is the root cause of that problem?**
**SelectCircle** is a re-usable common component. It's only working with one prop name as **isChecked**.  There is nothing else, that tells either its **disable** or **clickable**.

**What changes do you think we should make in order to solve the problem?**
You just have to add one more prop into **SelectCircle** that tells, either its active or disabled.

Do the followings;

**1.** You have to pass a **disable prop** with a particular name(I named that **isDisabled**) from **OptionsRow Component(line#291)**.
<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/7cf71246-ef8f-4312-88d0-e0e7e1e828ce">

**2.** Apply this **isDisable** prop inside the **SelectCircle Component**
<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/070fd19c-5ee3-4ad2-9216-f5f1adf63a77">

**3.**  Make another style object for disabledSelectCircle
<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/41377cee-31db-4986-bbbc-df547d4e9c2e">

**What alternative solutions did you explore? (Optional)**
NA

**Video Attachment**

https://github.com/Expensify/App/assets/135354140/adf46228-aa7c-4670-bb9a-738dcb18fdca

**Comment by tjferriss** [comment] 2023-09-25 01:14
@muttmuure it looks like MelvinBot assigned me after you. I'm going to un-assign myself.

**Comment by astrohunter62** [comment] 2023-09-27 04:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The cursor remains a hand icon when hovering over the checkbox in the 'Paid By' section during the Split bill process.
### What is the root cause of that problem?
In the `OptionRow` component, there's a missing pass of the 'disabled' props to the `SelectCircle` component wrapped within `PressableWithFeedback`.
### What changes do you think we should make in order to solve the problem?
We can pass the 'disabled' props to `PressableWithFeedback`.
```
<PressableWithFeedback
    onPress={() => this.props.onSelectedStatePressed(this.props.option)}
    accessibilityRole={CONST.ACCESSIBILITY_ROLE.CHECKBOX}
    accessibilityLabel={CONST.ACCESSIBILITY_ROLE.CHECKBOX}
    disabled={this.state.isDisabled}
>
    <SelectCircle isChecked={this.props.isSelected} />
</PressableWithFeedback>

```
Result:

[28064(chrome).webm](https://github.com/Expensify/App/assets/136574831/a42fbd9f-1b9c-454b-ae85-6a3761f2ddeb)

[28064(safari).webm](https://github.com/Expensify/App/assets/136574831/7bf5ec89-e630-4e1e-8e55-b31a56a3e8e0)

**Comment by muttmuure** [comment] 2023-10-04 13:51
@aimane-chnaif 3 proposals to review when you have time. Thank you!

**Comment by lakchote** [comment] 2023-10-05 05:53
@esh-g's proposal LGTM.

**Comment by esh-g** [comment] 2023-10-05 10:58
Thanks @lakchote 
Here is the PR: https://github.com/Expensify/App/pull/28850 🚀

cc @aimane-chnaif

**Comment by lakchote** [comment] 2023-10-19 13:25
@aimane-chnaif please complete the checklist in order to close the issue.

**Comment by tewodrosGirmaA** [comment] 2023-11-08 10:29
@lakchote can you please re-open the issue? I haven't received payment yet

**Comment by muttmuure** [comment] 2023-11-08 14:37
Contracts extended

**Comment by muttmuure** [comment] 2023-11-13 13:46
Bonus sent

**Comment by tewodrosGirmaA** [comment] 2023-11-13 14:13
Hello @muttmuure, I have not received payment?

**Comment by esh-g** [comment] 2023-11-13 17:44
@muttmuure I still haven't received the payment as well...

**Comment by muttmuure** [comment] 2023-11-15 18:29
Oops, sorry!

**Comment by muttmuure** [comment] 2023-11-15 18:29
Offers sent

**Comment by tewodrosGirmaA** [comment] 2023-11-15 18:46
> Offers sent

Thank you @muttmuure  I accepted the offer

**Comment by esh-g** [comment] 2023-11-16 13:54
Thanks, accepted the offer @muttmuure

**Comment by esh-g** [comment] 2023-11-20 02:38
@muttmuure Please also make sure to check the bonus... thanks

**Comment by lakchote** [comment] 2023-11-22 14:28
@muttmuure were you able to check the bonus? Thanks!

**Comment by muttmuure** [comment] 2023-11-22 18:29
$750 inc Bonus paid to @esh-g 
@tewodrosGirmaA also paid

**Closed by muttmuure** 2023-11-22 18:29 UTC
Labels: External, Daily, Awaiting Payment, Bug
