### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] [Custom Status] Add the ability to automatically clear Custom User Status

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#23138] opened 2023-07-18 22:16 UTC
# Part of the Custom Status project
Main issue: https://github.com/Expensify/App/issues/16350
Doc: https://docs.google.com/document/d/1uPS24aoRWE45piaTvr0XvrgV1lK3lSjieG3sD5ZPfQg/edit#bookmark=id.dm0yu67h9vq8
Project: https://github.com/orgs/Expensify/projects/59/views/1

# Add the ability to automatically clear Custom User Status
This will involve many new pages to set relative times, time, and date.
1. Add "Clear After" button to the status page. This will also show the clear after time after one has been set.
<img width="219" alt="2023-07-18_16-09-48" src="https://github.com/Expensify/App/assets/42391420/bf69bee6-dc40-4dac-be2c-b6af1b
<img width="223" alt="2023-07-18_16-11-31" src="https://github.com/Expensify/App/assets/42391420/3638b59d-984c-42d9-aca7-b3ee103d265d">
0f24f3">

2. The "Clear After" page. This will expand when the user selects "custom" as you can see in the second screenshot
<img width="222" alt="2023-07-18_16-10-30" src="https://github.com/Expensify/App/assets/42391420/1395ef67-da3a-4372-aa38-151ecf6f64b2">
<img width="219" alt="2023-07-18_16-11-09" src="https://github.com/Expensify/App/assets/42391420/ccbc8ec0-ca8d-45f0-9abf-f721754a5aa4">

3. The Date picker page
<img width="220" alt="2023-07-18_16-11-15" src="https://github.com/Expensify/App/assets/42391420/7232876e-a69b-4d1b-9851-e0a604f36d07">

4. The Time picker page
<img width="232" alt="2023-07-18_16-11-22" src="https://github.com/Expensify/App/assets/42391420/7cd21caa-02c8-406b-9826-233f182be25f">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b67967a538696fdd</li>
        <li>Upwork Job ID: 1724123658546638848</li>
        <li>Last Price Increase: 2023-11-13</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment] 2023-07-28 14:50
No update here, but work has started on the base PR!

**Comment by stitesExpensify** [comment] 2023-08-08 21:40
Base PR is in review!

**Comment by stitesExpensify** [comment] 2023-08-23 14:35
Almost here!

**Comment by stitesExpensify** [comment] 2023-09-26 01:04
This has been on hold with @perunt being pulled to some other projects

**Comment by jjcoffee** [comment] 2023-11-01 16:11
Copy approval: We have two error messages that show when entering an incorrect date or time:

1. `Choose today or a future date.`
2. `Enter a time one minute ahead.`

cc @stitesExpensify

**Comment by jamesdeanexpensify** [comment] 2023-11-02 17:23
These should work if there's enough space:

1. Please choose today or a future date.
2. Please choose a time at least one minute ahead.

Possible to see how those look in a mockup?

**Comment by jjcoffee** [comment] 2023-11-02 17:34
cc @perunt on the [above](https://github.com/Expensify/App/issues/23138#issuecomment-1791184894)

**Comment by perunt** [comment] 2023-11-03 08:11
It's good for English translation, what about Spanish?
I've translated your text as 
  ```
  invalidDateShouldBeFuture: 'Por favor seleccione hoy o una fecha futura.',
  invalidTimeShouldBeFuture: 'Por favor seleccione una hora al menos un minuto adelante.'  
  ```
  The old Spanish translation was
  ```
  invalidDateShouldBeFuture: 'Elige hoy o una fecha futura.',
  invalidTimeShouldBeFuture: 'Introduce un tiempo un minuto adelante.'
  ```
 @jamesdeanexpensify

**Comment by stitesExpensify** [comment] 2023-11-03 15:19
invalidTimeShouldBeFuture : Por favor elija una hora al menos un minuto en el futuro

We decided to skip the date error because it's so unlikely to happen.

**Comment by perunt** [comment] 2023-11-03 15:51
The longer translation perfectly fits, thanks!
<img width="376" alt="image" src="https://github.com/Expensify/App/assets/48593211/803de426-53c9-4adc-af27-4b22ebf1b49e">

**Comment by stitesExpensify** [comment] 2023-11-03 16:49
Correction, in both cases it should be `elije` not `elija`

**Comment by stitesExpensify** [comment] 2023-11-03 20:44
Okay there was a very long thread and the discussion ended with:

invalidDateShouldBeFuture : Por favor, elige una fecha igual o posterior a hoy
invalidTimeShouldBeFuture : Por favor, elige una hora al menos un minuto en el futuro

**Comment by stitesExpensify** [comment] 2023-11-03 20:44
cc @perunt ^

**Comment by perunt** [comment] 2023-11-04 09:59
updated
<img width="358" alt="Screenshot 2023-11-04 at 10 57 37" src="https://github.com/Expensify/App/assets/48593211/fc8fc163-ac9a-4092-b84c-96c1599a0907">

**Comment by perunt** [comment] 2023-11-13 15:36
Not overdue. As this PR is huge, @stitesExpensify gave an idea to add one more C+ contributor.

**Comment by conorpendergrast** [comment] 2023-11-24 10:50
Weird that Melvin is acting like this is overdue, even though it isn't labelled as overdue

**Comment by stitesExpensify** [comment] 2023-12-06 18:15
Doing the final review now!

**Comment by stitesExpensify** [comment] 2023-12-14 14:49
This has been merged!

**Comment by iwiznia** [comment] 2023-12-14 18:36
Context https://expensify.slack.com/archives/C01GTK53T8Q/p1702577037928319
I closed this issue https://github.com/Expensify/App/issues/33093 since it should not block, but we should add a better error message there

**Comment by conorpendergrast** [comment] 2023-12-18 14:21
@stitesExpensify @jamesdeanexpensify Do we have an external resource update for this change? We will need to update [this help page](https://help.expensify.com/articles/new-expensify/account-settings/Profile#how-to-communicate-your-current-status)

**Comment by stitesExpensify** [comment] 2023-12-18 17:42
External resource update is here https://github.com/Expensify/Expensify/issues/296265 we closed it after the previous release because we were unsure how long this would take. I'll re-open it so that the help page can be updated

**Comment by jjcoffee** [comment] 2023-12-19 07:34
Just noting that I also [reviewed](https://github.com/Expensify/App/pull/24620#issuecomment-1693312620) the PR for this. Also, the base price should be $1000 as the issue was created before [the change](https://github.com/Expensify/App/pull/24620#issuecomment-1693312620) (not to mention the PR was massive :sweat_smile:).

**Comment by allroundexperts** [comment] 2023-12-20 14:59
Can we have a payment summary here? Thanks!

**Comment by conorpendergrast** [comment] 2023-12-20 20:20
Yep, I can write that up!

**Comment by conorpendergrast** [comment] 2023-12-22 11:27
Payouts due:

Contributor: $1000 @perunt (Contractor)
- [ ] First Contributor+: $1000 @jjcoffee - [Offer](https://www.upwork.com/nx/wm/offer/100152195)
- [ ] Second Contributor+: $1000 @allroundexperts (NewDot Manual Requests)

After an internal discussion, we're arriving at $1000 as a balance between the scale of the work involved, and the two regressions.

Upwork job is [here](https://www.upwork.com/jobs/~01811bd92215fe7af4).

**Comment by jjcoffee** [comment] 2023-12-22 12:06
@conorpendergrast Accepted, thanks!

**Comment by conorpendergrast** [comment] 2023-12-22 13:24
@jjcoffee paid! 

This was a new feature so doesn't require the checklist, so I'm closing it out. Thanks!

**Closed by conorpendergrast** 2023-12-22 13:24 UTC
Labels: External, Engineering, Weekly, Help Wanted, Waiting for copy, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:50
$1,000 payment to @allroundexperts based on summary above.
