### ISSUE TITLE
[$500] Not able to invite member to admin room via mention and using invite button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33971] opened 2024-01-04 18:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704159422901759

## Action Performed:
1. Create a workspace as account A
2. Go to #admins room
3. invite a member using @user@email.com or
4. go to members

## Expected Result:
User should see "invite" button in admin room or mentioned user should get an invite

## Actual Result:
No "invite" button and user not invited with mentioning

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a00370bb-7863-4b78-81a5-518aff0ab940

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f9ce02c4a92f62f</li>
        <li>Upwork Job ID: 1742972165255376896</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by brunovjk** [comment] 2024-01-07 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users are unable to invite members to the admin room via mention or by using an invite button.

### What is the root cause of that problem?
1 - The absence of an `Invite` button in `admins room`.
2 - Inadequate handling of user mentions within `admin rooms`.

### What changes do you think we should make in order to solve the problem?
1 - As seen in `src/pages/RoomMembersPage.js`, we can add an `onPress={inviteUser} > ROUTES.ROOM_INVITE` button in `src/pages/ReportParticipantsPage.js` if the chat is a #admin chat, using the `isAdminRoom` function from 'src/libs/ReportUtils.ts' (but not the workspace).

2 - It appears there may be a check that prevents inviting participants to a chat if it's an admin chat. Additionally, inviting participants in a normal chat seems to be malfunctioning. I am still investigating this issue and will update the proposal with specific changes once I have identified the problem.

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2024-01-08 10:45
@c3024 bump for proposal review thanks

**Comment by c3024** [comment] 2024-01-11 11:46
No, I just added the detail from the Slack discussion for the contributors to clearly understand what is exactly expected. I will review the proposal.

**Comment by abzokhattab** [comment] 2024-01-11 11:48
if you invite a member inside the admin room, would they be invited as a workspace member?

**Comment by c3024** [comment] 2024-01-11 13:48
No, they should be added to the #admins room only.

**Comment by brunovjk** [comment] 2024-01-12 10:14
Sorry for the delay, I will update my proposal in the next few days.

**Comment by brunovjk** [comment] 2024-01-15 16:28
## Proposal
[Updated](https://github.com/Expensify/App/issues/33971#issuecomment-1880064339)

**Comment by c3024** [comment] 2024-01-19 10:59
This needs to be internal because this requires backend changes.

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:05
Waiting for internal engineer to pick up

**Comment by peterdbarkerUK** [comment] 2024-01-22 21:45
I just ran into this as per the title (though the OP seems to be slightly different)

1) Start a thread
2) Mention a person not in the thread room (but in the overlying room) 
3) Click the invite button

The person should be invited, but nothing happens. Selecting "do nothing" removed the dialogue (and successfully does nothing)

![2024-01-22_22-45-12 (1)](https://github.com/Expensify/App/assets/16888060/9c96ccc7-139c-442b-ad0b-477f50557177)

**Comment by iwiznia** [comment] 2024-01-26 18:28
This is no bug, this is a whole new feature. So some questions:
- Why do we want to allow this? Inviting here would be making someone an admin, which I am not sure it is completely clear
- Does this need to work on the #announce room? And if so does it mean it only needs to work for admins?
- Is this actually a priority right now? Nothing is broken really (I don't see what @peterdbarkerUK is showing, I get no whisper at all, so it's not like something is broken for the user)

IMO I think we should close this for now.

**Comment by c3024** [comment] 2024-01-26 19:56
This is where it came from

https://expensify.enterprise.slack.com/archives/C049HHMV9SM/p1704228880423879?thread_ts=1704159422.901759&cid=C049HHMV9SM

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:48
Let's get this retested this week to check if it's still a live issue

**Closed** 2024-02-20 11:32 UTC
Labels: Weekly, Internal, NewFeature, Overdue, retest-weekly
