### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500]  The attachment's close icon is not entirely clickable on the desktop app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29598] opened 2023-10-13 23:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697105723301089

## Action Performed:
1. Open any chat with an attachment
2. Click on the attachment
3. Hover over the left side of the close icon
## Expected Result: 
The close icon is entirely clickable
## Actual Result: 
The left side of the close icon is not clickable

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/0b97479c-cd7b-44ee-a712-4015be767030

https://github.com/Expensify/App/assets/38435837/dd46ea98-1aca-43ee-b146-639298fd31fc

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/14e48469-b6da-4940-a4d0-87c2926738fe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167de4cc8d1415484</li>
        <li>Upwork Job ID: 1712974320766828544</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 27337905</li>
<li>adeel0202 | Reporter | 27337908</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-10-13 23:51
Can't reproduce this one on the latest main.

**Comment by zukilover** [comment] 2023-10-14 00:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The attachment's close icon is not entirely clickable on the desktop app, precisely some left portion of the button.

### What is the root cause of that problem?
The right padding rule of the buttons wrapper creates the unclickable area for every last element inside it:
https://github.com/Expensify/App/blob/3e5f300ecdcba26f0cf43b69644f83b7686d4af9/src/components/HeaderWithBackButton/index.js#L93-L94

### What changes do you think we should make in order to solve the problem?
Replace the right padding rule with transform.

1. Remove the padding rule:

```javascript
<View style={[styles.reportOptions, styles.flexRow, styles.alignItemsCenter]}>
```

2. Add the transform rule to compensate the right padding:

Modify this style:
https://github.com/Expensify/App/blob/3e5f300ecdcba26f0cf43b69644f83b7686d4af9/src/styles/styles.ts#L871-L873

to:

```javascript
reportOptions: {
            marginLeft: 8,
            transform: [{translateX: -5}]
},
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2023-10-16 07:11
Thanks for the issue upstream attachment @Krishna2323 

I see that the issue still exists now, and the solution from @Krishna2323 [proposal](https://github.com/Expensify/App/issues/29598#issuecomment-1762464093) seems not to harm (we don't have any draggable component near the modal header). @Krishna2323 Could you update your proposed changed part to specify which component or line the changes apply? I assume it's in the `HeaderWithBackButton` component.

🎀 👀 🎀 C+ reviewed!

@johncschuster Could you help add the Engineering label? Thank you!

**Comment by johncschuster** [comment] 2023-10-18 16:57
Sure thing!

**Comment by joelbettner** [comment] 2023-10-23 21:13
@mollfpr I think the proposal from @Krishna2323 looks good. I'll assign to this issue.

**Comment by johncschuster** [comment] 2023-11-07 21:35
### Payment Summary:
The pull request got merged within 3 working days of assignment, so this job is eligible for a 50% #urgency bonus 🎉([Comment](https://github.com/Expensify/App/issues/29598#issuecomment-1777446457))

@mollfpr requires payment via Manual Request - $750
@Krishna2323 requires payment [offer](https://www.upwork.com/nx/wm/offer/27337905) (Contributor) - `PAID`
@adeel0202 requires payment [offer](https://www.upwork.com/nx/wm/offer/27337908) (Reporter) - `PAID`

**Comment by mollfpr** [comment] 2023-11-08 16:54
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't see any offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open any chat with an attachment
2. Click on the attachment
3. Hover over the of the close icon
4. Verify icon is clickable and the cursor is changed
5. 👍 or 👎

**Comment by johncschuster** [comment] 2023-11-08 18:27
Leaving this open for me to get regression test issue going

**Comment by JmillsExpensify** [comment] 2023-11-10 21:27
$750 payment approved for @mollfpr based on BZ summary above.

**Closed** 2023-11-10 22:11 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
