### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Difference between last message on LHN and task action message when canceled a task

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30437] opened 2023-10-26 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697129972953389

## Action Performed:
1. Open a chat
2. Click plus button in composer
3. Click assign task and create a task
4. Cancel the task, Observe the last message on LHN and task report differently.
## Expected Result: 

Last message on LHN and task report are the same when canceled task
## Actual Result: 
last message on LHN and task report differently.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/3348e342-c9f7-4e37-ac11-20a3a32a5ea2

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/85379956-c5eb-4fb4-b6a1-12b44ba69188

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/0109cfc4-7740-418b-b6f6-22653b9ca4ce

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/ffb749c4-ba31-4006-b285-318dec52d1a9

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/1986b9d6-2c47-428e-972e-29dc9fbf7aea

https://github.com/Expensify/App/assets/38435837/2dae94bd-686e-4f4b-86df-efeb869e1095

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/9738fa67-9f6f-4e26-a17d-e2b14f7f19d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162e3426964bd58f2</li>
        <li>Upwork Job ID: 1717528650049146880</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27513102</li>
<li>namhihi237 | Contributor | 27513103</li>
<li>namhihi237 | Reporter | 27513105</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by m-natarajan** [comment] 2023-10-26 13:09
## Proposal by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
The last message on LNH is different last message on the task report when cancel the task
### What is the root cause of that problem?
We only have the logic showing completed and reopened task in LHn here so when canceling it is taking the value from the backend and there is no translation.
https://github.com/Expensify/App/blob/3b98327273d361b2afd3617f93ca2718ab0aaf61/src/libs/SidebarUtils.js#L353-L356
In Task action in the report, we are using the function `getTaskReportActionMessage` to get the message task action
https://github.com/Expensify/App/blob/3b98327273d361b2afd3617f93ca2718ab0aaf61/src/components/ReportActionItem/TaskAction.js#L24
That's why there is a difference here.
### What changes do you think we should make in order to solve the problem?
We should add logic to show the last message on LHN when the task canceled
```js
else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
    result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.canceled')}`;
}
```
Or we can use the function `getTaskReportActionMessage` for consistency:
```js
else if (ReportActionsUtils.isTaskAction(lastAction)) {
   result.alternateText = Task.getTaskReportActionMessage(lastAction.actionName, report.reportID, false);
}
```
### What alternative solutions did you explore? (Optional)
In addition, we can update the message when canceling the task
https://github.com/Expensify/App/blob/489e1aa7a7d1dfffac590d0703712b43ec481539/src/libs/actions/Task.js#L735
Or we can update the action message on the same backend/

**Comment by DylanDylann** [comment] 2023-10-27 08:01
This bug is discovered and I posted a solution to resolve this bug [before](https://github.com/Expensify/App/issues/25633#issuecomment-1687208651)

Re-post proposal here

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Difference between last message on LHN and task action message when canceled a task

### What is the root cause of that problem?
The translation for complete task and re-open task work well in LHN because we have logic to update alternativeText in getOptionData for LHN options 

https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/SidebarUtils.js#L300-L304

But we don't have logic for the translation cancel task
### What changes do you think we should make in order to solve the problem?

1. we need to translate cancelled task in LHN 

https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/SidebarUtils.js#L300-L304

add condition: 
```
else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.canceled')}: ${report.reportName}`;
            }
```
**Optional**: 2. Update complete task, reopen task and cancel task in share destination options
In here: https://github.com/Expensify/App/blob/08b75f39d32ab5ecfa1577ebdbb79c3fb24797fb/src/libs/OptionsListUtils.js#L505
we should add 
```
if ((result.isChatRoom || result.isPolicyExpenseChat || result.isThread || result.isTaskReport)) {
            const lastAction = visibleReportActionItems[report.reportID];
            if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.RENAMED) {
                const newName = lodashGet(lastAction, 'originalMessage.newName', '');
                result.alternateText = Localize.translate(preferredLocale, 'newRoomPage.roomRenamedTo', {newName});
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKREOPENED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.reopened')}: ${report.reportName}`;
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.completed')}: ${report.reportName}`;
            } else if (lodashGet(lastAction, 'actionName', '') === CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED) {
                result.alternateText = `${Localize.translate(preferredLocale, 'task.messages.canceled')}: ${report.reportName}`;
            }
}
```
With this approach, we need to define visibleReportActionItems as we did in SidebarUtils.
We also can consider to create utils function to update alternative text to avoid duplicated code

**Comment by brianmuks** [comment] 2023-10-28 15:48
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Difference between last message on LHN and task action message when canceled a task
### What is the root cause of that problem?
When a task is deleted the backend returns `deleted` as the `alternateText` which is rendered directly here:

https://github.com/Expensify/App/blob/8da0ab14749918c72e2a4c40bcde1230c11d9334/src/components/LHNOptionsList/OptionRowLHN.js#L264

### What changes do you think we should make in order to solve the problem?
Borrowing from this concepts: 
https://github.com/Expensify/App/blob/8da0ab14749918c72e2a4c40bcde1230c11d9334/src/components/ReportActionItem/TaskPreview.js#L83
we can add one line :
```
    optionItem.alternateText = (optionItem.alternateText === 'deleted', optionItem.isTaskReport) ? translate('task.messages.canceled') : optionItem.alternateText;
```

https://github.com/Expensify/App/blob/8da0ab14749918c72e2a4c40bcde1230c11d9334/src/components/LHNOptionsList/OptionRowLHN.js#L160

What alternative solutions did you explore? (Optional)
N/A

**Comment by jjcoffee** [comment] 2023-10-30 09:30
I think we're good to go with @namhihi237's [proposal](https://github.com/Expensify/App/issues/30437#issuecomment-1781092882) here. The RCA is correct and the fix is nice and simple - I do also like the idea of using `getTaskReportActionMessage` for consistency.

@namhihi237 Please comment in this thread so that you can be assigned.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by roryabraham** [comment] 2023-11-04 00:31
Not overdue, just assigned

**Comment by roryabraham** [comment] 2023-11-13 20:39
PR merged

**Comment by jjcoffee** [comment] 2023-11-23 07:52
- The PR that introduced the bug has been identified. Link to the PR: **N/A - looks like the behaviour has always been there**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open any chat
2. Click + in composer and Assign task
3. Fill out any details to create the task
4. Cancel the task
5. Verify that the last message on LHN and task report both display the same message, `deleted task`

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-11-23 07:52
@johncschuster Checklist complete, friendly bump for payment! :bow:

**Comment by roryabraham** [comment] 2023-11-28 20:36
@johncschuster bump for payment

**Comment by johncschuster** [comment] 2023-11-29 15:31
Thanks for the pings, everyone! Working on this now.

**Comment by johncschuster** [comment] 2023-11-29 15:35
Ok folks! Payment has been issued! Thanks for your patience!

**Comment by johncschuster** [comment] 2023-11-29 15:35
(Leaving this open for me to create the Regression test issue)

**Closed** 2023-12-04 21:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
