### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Request money - Currency search does not work with head or trail space

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26375] opened 2023-08-31 09:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select request money
2. Click on currency
3. Type any currency with head or trail space

## Expected Result:
Should show currency suggestion if there is head or trail space

## Actual Result:
Currency suggestion does not work with head or trail space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/75d46416-1a0a-481c-b983-255ccbbe0dbf

https://github.com/Expensify/App/assets/115492554/849f524b-8aa3-44c6-9522-a3c32a514cc2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692593642283219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5fade09bc8f8027</li>
        <li>Upwork Job ID: 1702399813556031488</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Contributor | 26720044</li>
<li>gadhiyamanan | Reporter | 26720045</li>
</ul></li>
    </ul>
</details>

**Comment by gadhiyamanan** [comment] 2023-08-31 09:51
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
currency search does not work with head or trail space
### What is the root cause of that problem?
we are not trimming currency value while searching
### What changes do you think we should make in order to solve the problem?
trim the search value [here](https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/pages/iou/IOUCurrencySelection.js#L91)
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/pages/iou/IOUCurrencySelection.js#L91
### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2023-09-01 17:38
I'm not sure if this a bug or by design. My thoughts are if there is not supposed to be a space before the currency code, if you enter a space and begin typing, the correct result would be to not show the subsequent list underneath. However, interested to see others' thoughts on this. Going to get additional eyes.

**Comment by CortneyOfstad** [comment] 2023-09-01 17:39
@chiragsalian Interested to hear your thoughts on this — TIA!

**Comment by CortneyOfstad** [comment] 2023-09-05 14:14
Chirag was OoO for Labor Day, so not overdue 👍

**Comment by CortneyOfstad** [comment] 2023-09-08 15:44
Bump @chiragsalian ^^^ thanks!

**Comment by CortneyOfstad** [comment] 2023-09-11 15:39
Not overdue as @chiragsalian will be reviewing 👍

**Comment by chiragsalian** [comment] 2023-09-14 17:28
missed this, looking now

**Comment by chiragsalian** [comment] 2023-09-14 19:11
Yeah this looks like a minor bug to me. I think it would be a slight user experience to trim unnecessary spaces while searching. Marking this as external.

**Comment by mananjadhav** [comment] 2023-09-17 17:35
@gadhiyamanan's proposal [here](https://github.com/Expensify/App/issues/26375#issuecomment-1700725189) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by puneetlath** [comment] 2023-09-17 18:49
Seems super straightforward. Assigning @gadhiyamanan

**Comment by gadhiyamanan** [comment] 2023-09-18 07:18
@mananjadhav [PR](https://github.com/Expensify/App/pull/27644) is ready for review

**Comment by gadhiyamanan** [comment] 2023-09-19 14:32
@mananjadhav bump for PR review

**Comment by mananjadhav** [comment] 2023-10-02 14:51
I tried tracing the offending PR, I can see it existed since a long time (I think since the component creation). It went through a couple of refactors, I can't see if the trim got removed anywhere.

I also don't think we need a regression test here, considering how seldom this piece of code changed. @chiragsalian wdyt?


@CortneyOfstad Can you please post the payout summary, this is also eligible for the timeline bonus. I'll be raising my request on New Dot.

**Comment by chiragsalian** [comment] 2023-10-02 17:23
yeah imo regression testing for this is not needed.

**Comment by CortneyOfstad** [comment] 2023-10-03 14:31
Sorry was OoO yesterday, but payment breakdown is below!

- External issue reporter — **@gadhiyamanan paid $50** and contract ended in Upwork
-  Contributor that fixed the issue — **@gadhiyamanan paid $500 + 50% bonus = $750** and contract ended in Upwork
-  Contributor+ that helped on the issue and/or PR — @mananjadhav is paid in NewDot and is eligible for $750

**Comment by CortneyOfstad** [comment] 2023-10-05 17:25
Sorry @gadhiyamanan — just sent out a proposal for the additional $200. Please let me know as soon as you accept. Thank you!

**Comment by gadhiyamanan** [comment] 2023-10-05 17:30
@CortneyOfstad offer accepted, thanks

**Comment by JmillsExpensify** [comment] 2023-10-05 21:00
$750 approved for payment based on BZ summary.

**Comment by CortneyOfstad** [comment] 2023-10-09 13:40
Payments have been completed, so closing!

**Closed by CortneyOfstad** 2023-10-09 13:40 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
