### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500]  Collect admin - Admin badge is not crossed out when removing admin offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37776] opened 2024-03-05 17:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
- User is the owner of Collect workspace
- The Collect workspace has admin
1. Launch New Expensify app
2. Go to workspace settings > Collect workspace
3. Go to Members
4. Go offline
5. Select an admin
6. Tap on the dropdown > Remove member
7. Remove the admin

## Expected Result:
The admin badge will be crossed out (web behavior)

## Actual Result:
The admin badge is not crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6403092_1709659327631!web](https://github.com/Expensify/App/assets/78819774/7cea04ce-3c02-4ecb-ac02-95345408f926)

![Bug6403092_1709659327596!Android](https://github.com/Expensify/App/assets/78819774/f08161ef-9b6d-47a4-963d-292c48c9da41)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a65f30dbfbc53bd4</li>
        <li>Upwork Job ID: 1765131584509988864</li>
        <li>Last Price Increase: 2024-03-12</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 0</li>
<li>apeyada | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-05 17:55
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-05 17:55
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by askavyblr** [comment] 2024-03-06 07:59
Not reproduced it is working for Me IOS native

![IOS](https://github.com/Expensify/App/assets/125897912/f6d6a24c-14aa-460a-be76-01c06c836b7c)

**Comment by wildan-m** [comment] 2024-03-06 10:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Collect admin - Admin badge is not crossed out when removing admin offline

### What is the root cause of that problem?

The strikethrough style from OfflineWithFeedback is not applied to text in the badge.

### What changes do you think we should make in order to solve the problem?

If we want to give a badge special condition in OfflineWithFeedback, we can change `const props: StrikethroughProps`

To 
```
                const style = StyleUtils.combineStyles(child.props.style, styles.offlineFeedback.deleted, styles.userSelectNone)
                const isChildBadge = isBadge(child);
                const props: StrikethroughProps = {
                    style: isChildBadge ? undefined : style,
                    textStyle: isChildBadge ? style : undefined,
                };
```

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2024-03-08 06:33
Crossing of the `Admin` badge works fine on web but not on native. 

Substituting the `Badge` component with the returning node 
```
<View/Banner><Text>....</Text></View>
```
of `Badge` at `roleBadge` in `WorkspaceMembersPage` works correctly on native as well.

Can we identify the exact RCA for why using `Badge` affects and it affects only for native?

**Comment by agent3bood** [comment] 2024-03-09 11:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Collect admin - Admin badge is not crossed out when removing admin offline

### What is the root cause of that problem?

Each item in the members list is wrapped by `OfflineWithFeedback` which will apply the line cross through to `style` prop [here](https://github.com/Expensify/App/blob/88c66c0613490cc2d7686b0fffbcdab6e9cc55cd/src/components/OfflineWithFeedback.tsx#L114) but the `Badge` is using passing `textStyles` prop to the `Text`.
Web works because if you apply a css higher in the tree it will be applied to the children, but React Native does not do that instead it strictly apply styles to individual views.


### What changes do you think we should make in order to solve the problem?

In the `OfflineWithFeedback.applyStrikeThrough` we need to add extra checks and apply the styles correctly.

```js
    if (child.type.displayName === 'Badge') {
        props.textStyles = StyleUtils.combineStyles(child.props.textStyles, styles.offlineFeedback.deleted, styles.userSelectNone);
    }
```

This is more flexible and can accommodate adding new components that will need to be styled.

### What alternative solutions did you explore? (Optional)

Use more generic check when applying style in `OfflineWithFeedback.applyStrikeThrough`

```js
if (child.props.textStyles) {
    props.textStyles = StyleUtils.combineStyles(child.props.textStyles, styles.offlineFeedback.deleted, styles.userSelectNone);
}

```

**Comment by c3024** [comment] 2024-03-11 13:43
@mkhutornyi will takeover this issue as C+ as they worked on a similar issue and have better context.

**Comment by anmurali** [comment] 2024-03-18 23:36
Proposals are being discussed. @mkhutornyi will pick the best one shortly.

**Comment by rlinoz** [comment] 2024-03-25 13:28
Hey @mkhutornyi would you mind linking other parts of the code where we do that?

**Comment by rlinoz** [comment] 2024-03-25 14:43
So the idea is to use the same pattern and not just pass the entire styles, right?

**Comment by rlinoz** [comment] 2024-03-25 14:55
Thanks assigned @apeyada

**Comment by rlinoz** [comment] 2024-04-10 20:54
hmm I think we have a bug, @mkhutornyi was the C+ here.

Anyway, I will fill the checklist tomorrow.

**Comment by rlinoz** [comment] 2024-04-15 11:57
@mkhutornyi @apeyada if you could continue the checklist.

**Comment by rlinoz** [comment] 2024-04-18 18:16
friendly bump @mkhutornyi @apeyada

**Comment by anmurali** [comment] 2024-04-23 10:39
Still waiting on the checklist here. cc @mkhutornyi @apeyada

**Comment by rlinoz** [comment] 2024-04-25 23:56
@mkhutornyi is OOO

**Comment by rlinoz** [comment] 2024-04-29 12:20
I am moving to weekly until @mkhutornyi is back.

**Comment by anmurali** [comment] 2024-05-06 21:22
I paid @apeyada while we wait for @mkhutornyi to return and complete the checklist.

**Comment by rlinoz** [comment] 2024-05-15 19:23
Still waiting ofr @mkhutornyi

**Comment by anmurali** [comment] 2024-06-04 01:42
@mkhutornyi has been paid and tests added.

**Closed by anmurali** 2024-06-04 01:42 UTC
Labels: External, Weekly, Awaiting Payment, Bug
