### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] Offline - Can't leave public room after send message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23572] opened 2023-07-25 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 account on 2 browsers
2. A create a public room and copy share url
3. B open room url
4. B force offline
5. B send message in a room
6, B click header => leave room
7. B toggle offline => Online, Observed that the public room reappeared in LHN
## Expected Result: 
public room does not reappear in LHN does not reappear after leaving the room
## Actual Result:
 public room reappeared in LHN does not reappear after leaving the room

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9fda113b-fc3b-4187-9b8e-a4d1cd0d7f99

https://github.com/Expensify/App/assets/43996225/c3b772e6-d11d-4530-8986-9a26d856f616

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690263033683239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c85f976eb6d66e14</li>
        <li>Upwork Job ID: 1684936418739585024</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25899685</li>
<li>tienifr | Contributor | 25899689</li>
<li>namhihi237 | Reporter | 25899696</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-28 14:39
Not overdue

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:04
@mollfpr bump for review on these proposals thanks

**Comment by mollfpr** [comment] 2023-07-31 11:57
Reviewing

**Comment by laurenreidexpensify** [comment] 2023-08-01 12:51
@mollfpr can you confirm if either of the solutions are 👍

**Comment by mollfpr** [comment] 2023-08-01 16:02
Sorry for the delay, the BE changes will take longer to fix, and it's clearly set null to the report; we can do it in the E/App instead.

The [proposal](https://github.com/Expensify/App/issues/23572#issuecomment-1650558178) from @tienifr looks good to me 👍

🎀 👀 🎀 C+ reviewed!

**Comment by MariaHCD** [comment] 2023-08-10 07:16
@laurenreidexpensify, the PR was merged late because I missed assigning another engineer here before I went OOO on Aug 3rd. 

@tienifr should still be eligible for the bonus since the PR was ready for review and approved by @mollfpr within 3 working days.

**Comment by laurenreidexpensify** [comment] 2023-08-22 10:28
all payments have been issued in Upwork

@mollfpr can you please confirm checklist steps above thanks

**Comment by mollfpr** [comment] 2023-08-22 10:48
Thanks, @laurenreidexpensify I'll complete the checklist ASAP.

**Comment by mollfpr** [comment] 2023-08-23 14:46
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a one-time bug, so a regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login with any account
2. Go to a room
3. Go to Settings >> Preferences >> Force offline
4. Send a message to the room
5. Press room header >> Leave room
6. Verify that the public room disappears from LHN
7. Turn off Force offline
8. Verify that the public room won't appear again in LHN

**Closed** 2023-08-27 09:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
