### ISSUE TITLE
[$250] Search - Not here page opens when returning from Hold page when accessing from header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44208] opened 2024-06-22 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any DM.
3. Submit an expense to the user.
4. Go to Search.
5. Tap on the expense submitted in Step 3.
6. Tap on the report header.
7. Tap Hold.
8. Tap Back button.

## Expected Result:
App will return to previous page (report details page or transaction thread).

## Actual Result:
App opens not here page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a39aedad-48b0-4d78-8a01-d23977763a0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01806bc01a7212eaae</li>
        <li>Upwork Job ID: 1805263853657681677</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by m-natarajan** [comment] 2024-06-22 13:58
@rlinoz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-22 13:58
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-23 10:39
My solution [here](https://github.com/Expensify/App/issues/44203#issuecomment-2184936949) will fix this issue too.

**Comment by dylanexpensify** [comment] 2024-06-24 14:45
reviewing

**Comment by rlinoz** [comment] 2024-06-24 14:56
I can, but I think the problem here is that we are showing the hold option in a DM.

https://github.com/Expensify/App/assets/5201282/78e52359-096e-4dd4-8048-dae410c9d581

**Comment by rlinoz** [comment] 2024-06-24 14:58
We added this actions in this PR https://github.com/Expensify/App/pull/43251

cc: @cdOut @ikevin127

**Comment by rlinoz** [comment] 2024-06-24 15:35
I think we should try to fix the underlying issue which is there is no `backTo` in the HoldReasonPage when coming from the Search page. 

cc: @bernhardoj

**Comment by mountiny** [comment] 2024-06-25 12:33
Still looking for proposals, I think this is annoying UX issue but does not have to be blocker this late in the deployment cycle

**Comment by Kicu** [comment] 2024-06-25 12:42
I tried a few times with existing expense and with brand new expense but I could not reproduce this. I believe this probably is reproducible, but there _has_ to be some extra circumstances to get this as this does not always happen.

### my test

https://github.com/Expensify/App/assets/3929868/6bd96ace-17c1-46d4-ad73-5e90d567a2e2

There is one thing that I have noticed: in the reproductions that do have this bug, for @rlinoz and @m-natarajan the animation when going from `Details` -> `Hold` looks like a "back" animation, suggestion this is a POP action. Whereas on my video I cleaarly get the PUSH and I'm moving forward. This definitely feels related to the bug, but thats the extent of what I found.

Can someone give a 100% reliable way to reproduce this?

**Comment by rlinoz** [comment] 2024-06-25 13:17
This was fixed in this other PR https://github.com/Expensify/App/pull/44359/files#diff-63967b77292f23428a8509ef11c77b0e68feb3a8ddddfa0fa560c38014915eb9R78-R80, not reproducible anymore.

**Closed** 2024-06-25 13:18 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
