### ISSUE TITLE
[$500] Profile - Status dissappears before customized time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50658] opened 2024-10-11 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** anastasiiakarpenko.usa+13@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com./
2. Tap on "Settings"
3. Tap on "Profie"
4. Tap on "Status"
5. Select emoji and type "Wow"
6. In "Clear after" select time 1 hour ahead and tap "Save"
7. Tap on "Back" button at the top left corner
8. Tap on "Inbox" and return to Profile tab

## Expected Result:
The status is displayed for 1 hour after being set

## Actual Result:
The status dissapears immediately

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cf5c0b1d-2cae-48fa-9896-b92766f6732f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848860286282123001</li>
        <li>Upwork Job ID: 1848860286282123001</li>
        <li>Last Price Increase: 2024-12-17</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 104742376</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-10-11 15:11
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-10-15 21:52
Looking for a swap [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1729029117589439). Otherwise, I'll need to figure out what's up with my Browserstack so I can try to repro.

**Comment by mallenexpensify** [comment] 2024-10-22 22:54
Was able to reproduce on v9.0.52-4 
@c3024 , any idea what might be going on here? 

![IMG_9755B1C94030-1](https://github.com/user-attachments/assets/fdbff5fb-71ec-4e8f-a67c-5ef8041db486)

**Comment by c3024** [comment] 2024-10-23 04:24
This looks like a backend bug.

But, I cannot reproduce this on production, staging or dev. Looks like some backend fix was deployed.


https://github.com/user-attachments/assets/6529d321-697a-4fa5-af61-4efefa1f59ae



@lanitochka17, Can you please retest this?

Thanks!

cc: @mallenexpensify

**Comment by CyberAndrii** [comment] 2024-10-23 17:25
In the OP's video, the device's date is 7 days behind which causes the status to expire immediately. It's probably not worth fixing, but if you decide to, a potential solution might be for the FE to send its local time and the BE to account for this difference.

![image](https://github.com/user-attachments/assets/df92d0e4-3de4-4b72-b49c-dd7de2ac3daa)

![image](https://github.com/user-attachments/assets/5f0bc127-e439-4454-a142-62574c44698b)

**Comment by mallenexpensify** [comment] 2024-10-25 18:01
I'm still able to reproduce on latest staging build for IOS app, v9.0.54-1

**Comment by c3024** [comment] 2024-10-28 12:38
[This](https://github.com/Expensify/App/issues/50658#issuecomment-2432941081) makes sense. I will try to repro this with changing time zone.

**Comment by DylanDylann** [comment] 2024-11-04 04:22
@c3024 I can't reproduce the original issue. But I see a similar problem:

Step:
1. Set the local machine date to 7 previous days
2. Set status and clear after 3 minutes compared to the current time
3. Wait 3 minutes
4. The status isn't cleared

**Comment by mkzie2** [comment] 2024-11-05 11:16
I can only reproduce the issue when I manually update my local machine's time several days into the past. In such case, I think the behavior is expected: You sent a past "clear status after" date to the BE so it should clear the status immediately.

I took a look at @dominictb's [recoding](https://github.com/Expensify/App/issues/50658#issuecomment-2453823005) and seems like he did modify the time the way mentioned above.

Now only @mallenexpensify can reproduce it normally multiple times. Can you add a recording including all steps and export the Onyx state from Troubleshoot menu so I can take a look?

**Comment by mallenexpensify** [comment] 2024-11-07 00:09
Bumped to weekly , I'm back from OOO on Nov 14th, not assigning another BZ, if one is needed please add or post in #contributor-plus to ask for one to be added, thx.

**Comment by mkzie2** [comment] 2024-11-28 04:41
@mallenexpensify Can you help take a look at https://github.com/Expensify/App/issues/50658#issuecomment-2456900085?

**Comment by mallenexpensify** [comment] 2024-12-03 01:27
I'm still able to reproduce on the latest staging build for iOS app using mallen@expensify.com 
Also able to reproduce on iOS Chrome with mallen@expensifail.com account, check vid. 

Opening back up for proposals. 

https://github.com/user-attachments/assets/122f541d-5696-42ae-8d8f-fd30eaca4d1e

**Comment by mallenexpensify** [comment] 2024-12-10 22:18
Bumped up price to try to get proposals

**Comment by huult** [comment] 2024-12-12 01:24
> I can reproduce it. I can take over:

@dominictb Could you share your steps to reproduce?

**Comment by mallenexpensify** [comment] 2024-12-23 16:21
Unable to reproduce in Desktop, Chrome or Firefox.  Closing.  Comment/reopen if you're able to reproduce.  Please provide steps and vid if so

**Closed by mallenexpensify** 2024-12-23 16:21 UTC
Labels: External, Daily, Weekly, Help Wanted, Overdue, Bug, retest-weekly
