### ISSUE TITLE
Dev: Web - Incorrect Screen when Clicking CMD+K while Year Selection Modal is opened.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27160] opened 2023-09-11 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open profile, then open personal details
2. Open DOB, Select the year
3. Press CMD+K

## Expected Result:
Search page should open

## Actual Result:
YearModal is on top of searchmodal, closing year modal open Search page which is incorrect.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Yes, v1.3.67-3
**Reproducible in production?:** Yes, v1.3.66-3
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9532481b-a746-4c79-bde7-1ac626c96626

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694443603230179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5b8a53241ab3b2d</li>
        <li>Upwork Job ID: 1711342041166319616</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-09-11 16:18
@arosiclair I found a solution to this one

**Comment by roryabraham** [comment] 2023-09-11 16:58
Confirmed that this was not caused by https://github.com/Expensify/App/pull/26346

**Comment by roryabraham** [comment] 2023-09-11 17:21
Slack context: https://expensify.slack.com/archives/C07J32337/p1694450478955679

**Comment by ishpaul777** [comment] 2023-09-11 17:32
the same issue is reproduceable for StatePickerModal.

https://github.com/Expensify/App/assets/104348397/e25499cf-8c93-406e-a39a-889194eeae20

**Comment by arosiclair** [comment] 2023-09-11 19:24
Reproduced on prod **v1.3.66-3** so not a blocker. Also repro'd on staging **v1.3.67-3**

https://github.com/Expensify/App/assets/6833644/802f9b2b-0ddd-46b6-a065-eabbe8f01a37

**Comment by arosiclair** [comment] 2023-09-11 19:28
I'm not seeing any existing issues for this so getting BZ on this

**Comment by ishpaul777** [comment] 2023-09-11 19:31
@arosiclair in prod and staging the keyboard shortcuts working but on dev main the YearPicker modal not closing and is on top on search page.

**Comment by arosiclair** [comment] 2023-09-20 01:17
@michaelhaxhiu might be out. Recycling BZ label...

**Comment by arosiclair** [comment] 2023-09-20 01:18
@alexpensify can you triage this?

**Comment by alexpensify** [comment] 2023-09-20 04:09
@michaelhaxhiu is online. If Hax isn't able to review it, then I'll grab it before Thursday since I'm OOO on Friday due to work travel.

**Comment by michaelhaxhiu** [comment] 2023-09-20 14:04
What do we need here? To reproduce this or something else? @arosiclair didn't you already reproduce based on your comment [above](https://github.com/Expensify/App/issues/27160#issuecomment-1714453052)?

**Comment by arosiclair** [comment] 2023-09-21 02:58
> What do we need here? To reproduce this or something else? @arosiclair didn't you already reproduce based on your comment https://github.com/Expensify/App/issues/27160#issuecomment-1714453052?

Yeah though it's been a while so it might've changed. I'm just assuming we still need to do the BZ checklist even if we repro'd before

**Comment by arosiclair** [comment] 2023-09-26 02:46
bump @michaelhaxhiu

**Comment by ishpaul777** [comment] 2023-09-27 09:20
Issue not reproducable anymore, not sure which PR fixed the issue.

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:37
Oh my, sorry for missing your pings @arosiclair

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:37
@ishpaul777 if you can help identify the PR that fixed it, you'd be eligible for a bug bounty ($50)

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:39
Just for context, we want the PR that fixed it to be identified to ensure this is truly resolved into the future!

**Comment by ishpaul777** [comment] 2023-09-28 07:47
I think this [PR](https://github.com/Expensify/App/pull/27639) fixed the issue, I confirmed it by reverting the changes from the PR.

**Comment by michaelhaxhiu** [comment] 2023-09-28 13:55
Nice one! @arosiclair if you agree then we can pay @ishpaul777 for the bug report!

**Comment by michaelhaxhiu** [comment] 2023-09-28 13:57
(wowa sorry about the multiple assignments - melvin puked. Gonna leave this with Isa for ease! This is real close to completion)

**Comment by arosiclair** [comment] 2023-10-02 07:38
Confirmed reverting https://github.com/Expensify/App/pull/27639 re-introduces the issue 👍 @isabelastisser

**Comment by isabelastisser** [comment] 2023-10-02 18:08
hey @arosiclair, what does it mean? 😬 What are the next steps here? Is all we need to do pay @ishpaul777 https://github.com/Expensify/App/issues/27160#issuecomment-1739261710? If yes, the new bug report amount?

**Comment by arosiclair** [comment] 2023-10-03 08:57
> Is all we need to do pay @ishpaul777 [#27160 (comment)](https://github.com/Expensify/App/issues/27160#issuecomment-1739261710)? If yes, the new bug report amount?

Yes exactly. Bug report payment for @ishpaul777 would be $50 per [this comment](https://github.com/Expensify/App/issues/27160#issuecomment-1739266759)

**Comment by arosiclair** [comment] 2023-10-09 08:49
Looks like @isabelastisser is now OOO 🙃. Re-applying `Bug` so we can finally get this closed out

**Closed** 2023-10-10 14:31 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by pradeepmdk** [comment] 2023-10-12 17:20
> Can we fix this bug here? #27639 which closed this GH caused this bad regression. The regression period is over so we can't request original PR author/reviewer to fix this.
> 
> Repro step:
> 
> 1. Open FAB menu and then close
> 2. Press Cmd+K
> 3. Expects to open Search page but nothing happens (**BUG**)
> 4. Open FAB menu again and then close
> 5. Search page automatically opens this time (another **BUG**)
> 
>  Screen.Recording.2023-10-12.at.7.03.11.PM.mov 
> This is also blocking #28249
> 
> cc: @AndrewGable

@0xmiroslav i think   this is different bug https://github.com/Expensify/App/issues/29341

**Comment by pradeepmdk** [comment] 2023-10-12 17:23
and this bug from this PR https://github.com/Expensify/App/pull/29251/files they forgot to close the modal
