### ISSUE TITLE
Web - Inconsistency in Pinning IOU: Possible in LHN but Not Inside IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26550] opened 2023-09-02 11:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money."
2. Enter the desired amount and add an email address. Submit the request.
3. Go to the IOU section by double-clicking on the requested money.
4. In the Left Hand Navigation (LHN), right-click and observe that you can pin the IOU from LHN.
5. However, inside the IOU, there is no option to pin it until you delete the requested money.

## Expected Result:
 Pinning the IOU should be possible consistently both inside the IOU and in the LHN before deleting the requested money. Alternatively, the pinned IOU should appear in the LHN only after deleting the requested money to ensure consistency.

## Actual Result:
Pinning the IOU is possible in the LHN before deleting the requested money.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bdbe1630-3c74-4fc2-abe1-249ef838dcf7

https://github.com/Expensify/App/assets/93399543/0bfbbca2-247e-4755-9941-5865e06450ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692865226061699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment] 2023-09-02 11:17
# Proposal

## Please re-state the problem we are trying to solve
Able to pin a money request from LHN while there is no option to do so in the header

## What is the root cause of this problem?
There is no condition to block the pin icon for a `MoneyRequest` in `ContextMenuActions`.
It seems to be intentional to hide the pin option from this deliberate commit: https://github.com/Expensify/App/pull/22562/commits/f79fc237fa00454daaeb7cf94f08ff34373819d6
However, I don't have a strong opinion about this, so, I'll include both solutions

## What changes do you think should be made in order to solve this?
Any of the options can be chosen:
- **Hide pin option for money request:**
To hide the pin option in LHN as well, we can add a condition to `ContextMenuActions` here:
https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/pages/home/report/ContextMenu/ContextMenuActions.js#L334-L340
Add the condition `!ReportUtils.isMoneyRequest(reportID)`
```js
shouldShow: (type, reportAction, isArchivedRoom, betas, anchor, isChronosReport, reportID, isPinnedChat) =>
  type === CONTEXT_MENU_TYPES.REPORT && !isPinnedChat && !ReportUtils.isMoneyRequestReport(reportID) && !ReportUtils.isMoneyRequest(reportID),
```

- **Show pin option for money request:**
To show the pin button on the header as well, we can set the following to `true`:
https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/components/MoneyRequestHeader.js#L82

**Comment by JmillsExpensify** [comment] 2023-09-07 01:50
I'm inclined to not accept this bug report, as it's a new feature request and was known at the time we built this feature. Do you agree @trjExpensify?

**Comment by trjExpensify** [comment] 2023-09-07 10:12
I think the `Pin` option should go inside the overflow menu at the top of all pages. I.e no independent buttons for call / pin, and consistently on chat/task/expense/iou/transaction pages that are all possible to 
"keep" in your LHN. That's being worked on here I believe: https://github.com/Expensify/App/issues/22635

**Comment by JmillsExpensify** [comment] 2023-09-13 08:14
Ah yes, agreed. This is already being handled. Closing this duplicate report and feature request.

**Closed by JmillsExpensify** 2023-09-13 08:14 UTC
Labels: Daily, Overdue, Bug
