### ISSUE TITLE
[$500] BUG: Sender name is not cleared from LHN when the chat is deleted from the room reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12158] opened 2022-10-26 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any room that has no chat
2. Send a message. Observe there is your name in LHN with the message you just sent
3. Delete the message. Observe the message is no more there but the name is still there.

## Expected Result:
When the chat is a deleted, the sender name is cleared as well and the workspace name is displayed

## Actual Result:
The sender name doesn't clear and implies a blank message

## Workaround:
None

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/198138323-a91ffa11-0452-41c4-b4ca-4e4fab0be0e1.mov

https://user-images.githubusercontent.com/43996225/198138342-d49c2d73-8025-4df1-8f99-279814da365f.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666794860997529?thread_ts=1660240300.106669&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2022-10-27 12:01
https://user-images.githubusercontent.com/29386373/198278987-e8052f71-a55f-4917-9951-12de475df016.mov

**Comment by techievivek** [comment] 2022-10-31 07:47
Will investigate today.

**Comment by techievivek** [comment] 2022-11-03 04:50
I wasn't able to look into it on Monday because I was working limited hours. Going to have a look at it today.

**Comment by techievivek** [comment] 2022-11-03 12:18
@Ollyws Did you handle this case in your PR #11765 ? CCing @eVoloshchak if you have some idea as you were the c+ assigned for review.

**Comment by eVoloshchak** [comment] 2022-11-03 12:48
@techievivek 
This wasn't handled in #11765, I don't think it handles logic for chat rooms
It was present before, you can check out [this commit](https://github.com/Expensify/App/commit/a93858c9cdb73deedccb4d0150c216cf16c99300)

https://user-images.githubusercontent.com/9059945/199722943-f31df9b1-7470-4da4-97e4-e433a77d4a52.mov

**Comment by michaelhaxhiu** [comment] 2022-11-03 22:55
Hmm this doesn't have a BZ or C+ assigned. If this `external` or `internal`? Can we apply that label today based on which is best @techievivek?  Cheers!

**Comment by techievivek** [comment] 2022-11-04 11:59
@eVoloshchak @Ollyws Thanks for clearing that out. I just wanted to be sure this has not popped out from your PR.

**Comment by Santhosh-Sellavel** [comment] 2022-11-04 13:07
@flodnv @jliexpensify 
Will not be able to get this sooner so unassigning, please reassign another C+ by applying the `external` label again, thanks!

**Comment by sobitneupane** [comment] 2022-11-07 06:53
@Ollyws Thanks for your proposal.

> when the message is deleted lastActorEmail is still left in the report.

This looks like a bug.  Why don't we remove `lastActorEmail` when message is deleted? I think removing `lastActorEmail` when message is deleted is better approach to handle this issue.

**Comment by sobitneupane** [comment] 2022-11-08 06:04
Thanks for the update @Ollyws. With your proposed change, issue is solved at the senders end but not at the receivers end. We might have to make similar change for receiver as well.

https://user-images.githubusercontent.com/25876548/200487312-b89ab6a3-ac32-4ad5-a297-e6cccaf21fb1.mov

**Comment by jliexpensify** [comment] 2022-11-08 21:30
Hmmm, did I miss creating an Upworks job?

Internal - https://www.upwork.com/ab/applicants/1590094088876425216/job-details
External - https://www.upwork.com/jobs/~0116417756c759ec25

Invited @adeel0202 and @sobitneupane

**Comment by jliexpensify** [comment] 2022-11-13 22:12
Not overdue

**Comment by flodnv** [comment] 2022-11-15 14:00
Great to hear! 🙏

**Comment by jliexpensify** [comment] 2022-11-15 21:21
[Doubled!](https://expensify.slack.com/archives/C01GTK53T8Q/p1668547228298469)

**Comment by peterklamka** [comment] 2022-11-16 18:49
###Proposal


###Solution:

I added below code after SidebarUtils.js Line253
https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.js#L250-L253

`if(lastMessageText === '' || lastMessageTextFromReport === '')
        lastMessageText = report.oldPolicyName;`

###Video
https://user-images.githubusercontent.com/118206313/202266374-70c9c122-cf93-4d2b-ad5c-de3aeff11413.mp4

**Comment by sobitneupane** [comment] 2022-11-17 05:00
@Ollyws I prefer the [prior proposal](https://github.com/Expensify/App/issues/12158#issuecomment-1305499584) than the new one. The new proposal looks like a workaround. The better approach will be handle the issue in the root. The next step will be to find the function that updates onyx data when the other user deletes the message and fix the issue there.

**Comment by sobitneupane** [comment] 2022-11-17 05:02
@peterklamka Thanks for your proposal.

Your proposal might solve the issue. But we are looking for the root cause of the problem and trying to fix the issue there.

**Comment by sobitneupane** [comment] 2022-11-17 14:29
> As you can see the report data only contains lastMessageText and lastMessageHtml (no lastActorEmail)

I think It makes sense to add lastActorEmail. 

`lastActorEmail` is returned along with other attributes when there is lastMessageText.

`{"onyxMethod":"merge","key":"report_86287312","value":{"lastMessageText":"hello","lastMessageHtml":"hello","isEdited":false,"lastMessageTimestamp":1668693620,"lastActorEmail":"sobit.neupane.111@gmail.com"}}]`

But when lastMessageText is empty, `lastActorEmail` is not returned. I think we should return `lastActorEmail: ''` in this case.

`{"onyxMethod":"merge","key":"report_86287312","value":{"lastMessageText":"","lastMessageHtml":""}}]`

> (I assume) require some changes on the backend.

I agree with @Ollyws. It might require some change on the backend.

cc: @flodnv

**Comment by flodnv** [comment] 2022-11-18 08:25
@puneetlath this specific one is 3 weeks old. However since it's been suggested this could be internal, and seems like it could, I'll investigate further next week.

**Comment by flodnv** [comment] 2022-11-21 15:16
Maybe caused by https://github.com/Expensify/Web-Expensify/pull/34788

Internal PR sent. @Ollyws @sobitneupane your instinct are correct: any time we need to do any kind of data massaging in the app, it is an incorrect solution. The API should send exactly what the app needs.

**Comment by flodnv** [comment] 2022-11-24 13:14
Fix is deployed

**Comment by jliexpensify** [comment] 2022-11-24 21:33
@adeel0202 as this GH is closed, tag me when you've accepted and I'll pay the $250 - cheers!

**Comment by jliexpensify** [comment] 2022-11-25 06:26
@adeel0202 paid. Job closed on Upworks.

**Comment by jliexpensify** [comment] 2022-11-27 21:21
Re-opening for additional payment: https://expensify.slack.com/archives/C02NK2DQWUX/p1669355431418599

**Comment by jliexpensify** [comment] 2022-11-27 21:33
Pay $250 to Sobit: https://www.upwork.com/ab/applicants/1596980367791489024/job-details

**Comment by jliexpensify** [comment] 2022-11-28 03:40
Paid and job closed!

**Closed by jliexpensify** 2022-11-28 03:40 UTC
Labels: Reviewing, Engineering, Daily, Bug
