### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-18] [$500] Web – Chat - Unable to delete message using Context menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29159] opened 2023-10-10 07:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.80-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193/Applause-Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696914742812669

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. Navigate to any chat conversation.
4. Send a message.
5. Delete the message using Context menu.

## Expected Result:
The message has been deleted

## Actual Result:
Nothing happenes. The Delete button does not work.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary> 

https://github.com/Expensify/App/assets/115492554/1fcd0ff2-fe67-45df-bdfc-3500dc856743

https://github.com/Expensify/App/assets/115492554/26cc8484-26b6-4aff-8455-46ed8974afa0

[utest-dl.s3.amazonaws.com_12102_26469_432782_6231518_bugAttachment_Bug6231518_1696922056983%21log.txt_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231010T075332Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Credential=AKIAJ2U.txt](https://github.com/Expensify/App/files/12854308/utest-dl.s3.amazonaws.com_12102_26469_432782_6231518_bugAttachment_Bug6231518_1696922056983.21log.txt_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231010T075332Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz-Credential.AKIAJ2U.txt)

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ea80a76183e99f1</li>
        <li>Upwork Job ID: 1711652016993763328</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-10 08:14
Not repro in Prod


https://github.com/Expensify/App/assets/115492554/ccc3567c-54f1-486c-ac49-b2b2df26dc8a

**Comment by chamysoftware** [comment] 2023-10-10 09:57
Looks like this is the PR that caused the issue: https://github.com/Expensify/App/pull/28486/files
Confirmed this with a quick git bisect

**Comment by s-alves10** [comment] 2023-10-10 12:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to delete a message using context menu

### What is the root cause of that problem?

This is a regression of this PR https://github.com/Expensify/App/pull/28486

In the PR, we introduced the new variable `prevIsVisible` with the previous value of `props.isVisible` and add this value to the dependency array of this `useEffect`
https://github.com/Expensify/App/blob/a63f853381cd6ea680c31ee24c7c72f02e2d1513/src/components/PopoverWithoutOverlay/index.js#L30

This change makes the effect callback called twice: once when `props.isVisible` changes, once when `prevIsVisible` changes. So the `props.onModalHide` is called twice
When called first, we clear the `reportID` and call `showDeleteModal`
https://github.com/Expensify/App/blob/67a2024e11a621ab34a789f1a51b6b6a8aeed74b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L210-L217
, but at the next call, we simply clear the `reportID` because we set the `onPopoverHideActionCallback.current` to empty function at the previous call
https://github.com/Expensify/App/blob/67a2024e11a621ab34a789f1a51b6b6a8aeed74b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L216

So when the delete confirm modal is opened, the value of `reportIDRef.current` is '0'. When we tap 'Delete', `Report.deleteReportComment` function is called with reportID = 0.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We don't need to introduce `prevIsVisible`.
Remove this variable
https://github.com/Expensify/App/blob/67a2024e11a621ab34a789f1a51b6b6a8aeed74b/src/components/PopoverWithoutOverlay/index.js#L28
https://github.com/Expensify/App/blob/67a2024e11a621ab34a789f1a51b6b6a8aeed74b/src/components/PopoverWithoutOverlay/index.js#L55

Update the condition
https://github.com/Expensify/App/blob/67a2024e11a621ab34a789f1a51b6b6a8aeed74b/src/components/PopoverWithoutOverlay/index.js#L46
```
        if (!firstRenderRef.current || !props.isVisible) {
```

This works as expected and doesn't affect https://github.com/Expensify/App/issues/28241

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/fd2747ed-3613-4705-a198-c7835440ac64

</details>


### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-10-10 19:48
We should probably have one of the authors of that PR fix this issue. I'm gonna give them a few hours, but if not I'll revert the PR and they can resubmit it so we don't block the App deploy.

**Comment by jasperhuangg** [comment] 2023-10-10 19:48
cc @dukenv0307 @deetergp @parasharrajat

**Comment by jasperhuangg** [comment] 2023-10-11 01:49
Gonna revert the PR that caused this regression

**Comment by s-alves10** [comment] 2023-10-11 01:52
@jasperhuangg 

I can create a PR fixing both the original issue and this issue in 2 hrs.

**Comment by jasperhuangg** [comment] 2023-10-11 02:00
@s-alves10 Thanks. I'm confirming if our standard practice is to allow another contributor to fix these types of regressions first or if we want the original contributor who caused the regression to fix them.

**Comment by jasperhuangg** [comment] 2023-10-11 02:08
@s-alves10 go ahead!

**Comment by jasperhuangg** [comment] 2023-10-11 03:51
This was fixed on staging!

**Comment by s-alves10** [comment] 2023-10-11 04:45
I wasn't assigned to this issue

**Comment by alexpensify** [comment] 2023-10-19 21:41
Not overdue, the payment date is October 23

**Comment by alexpensify** [comment] 2023-10-20 23:16
@Ollyws - to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by alexpensify** [comment] 2023-10-23 23:05
@jasperhuangg - can I get feedback here? 

 @hungvu193 reported the issue 
 
 @s-alves10 fixed the issue. Now, did the PR create a regression or was it caused by another PR unrelated to @s-alves10 work? Thanks for clarifying!

**Comment by alexpensify** [comment] 2023-10-26 22:19
Bumping - @jasperhuangg and @nkuoch - I need feedback for the payment breakdown here. Thanks!

**Comment by alexpensify** [comment] 2023-10-27 18:43
Thanks! @parasharrajat! I'm OOO today but going to input the summary here to make sure everyone is on the same page here. I'll complete the process on Monday. 

Here is the payment summary: 

-  External issue reporter - @hungvu193 $50 
-  Contributor that fixed the issue - @s-alves10 $250 
-  Contributor+ that helped on the issue and/or PR - N/A 

Upwork Job: 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is a regression, so there is a 50% reduction to the base rate. 

--- 

@parasharrajat - I think are are paid in the other GH, but let me know if that's not the case.

**Comment by alexpensify** [comment] 2023-10-30 23:02
All requests have been sent via Upwork. Once accepted, I can complete the payment process.

**Comment by hungvu193** [comment] 2023-10-31 02:27
> All requests have been sent via Upwork. Once accepted, I can complete the payment process. 

Can you send it again please?

**Comment by alexpensify** [comment] 2023-11-01 00:29
@hungvu193 - I sent a new request in Upwork for you to review. Thanks!

**Comment by hungvu193** [comment] 2023-11-01 05:42
> @hungvu193 - I sent a new request in Upwork for you to review. Thanks! 

Accepted. Thank you.

**Comment by alexpensify** [comment] 2023-11-01 23:20
Perfect, everyone has been paid here via Upwork!

**Closed by alexpensify** 2023-11-01 23:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
