### ISSUE TITLE
[$500] IOU - When user deletes distance request, Inconsistent behaviour is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30393] opened 2023-10-25 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a Workspace chat
3. Tap plus icon near compose box to select Request money
4. Tap Distance
5. Select start and Finish waypoints
6. Tap next
7. Tap Request
8. Tap on distance request to open distance request detail page
9. Tap on 3 dots on top right and select delete receipt
10. Note it shows TBD for a second and disappears.
11. Navigate back to Workspace
12. Repeat steps from 3-Step 8
13. Tap on the receipt
14. Tap on 3 dots on top right and delete receipt
15. In distance request detail page, tap 3 dots on top right and select delete request
16. Note the distance request disappears for a second and then shown as TBD.

## Expected Result:
When user deletes distance request, it shows TBD for a second and disappears. Same distance request, if we delete receipt and then delete request, the distance request disappears for a second and then shown as TBD. There should not be Inconsistent behavior

## Actual Result:
When user deletes distance request, it shows TBD for a second and disappears. Same distance request, if we delete receipt and then delete request, the distance request disappears for a second and then shown as TBD. Inconsistent behaviour is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/4315660f-c179-43f0-b18c-0a0bd320b151

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec1bd78667e0f93b</li>
        <li>Upwork Job ID: 1720412882637504512</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-25 22:07
There is some BE issue happening on the removal of a request with a detached receipt: 
When a regular money request is deleted, the BE response contains (among others) the following Onyx operation that removes the `REPORTPREVIEW` action from the expense chat:

```json
{
    "onyxMethod": "merge",
    "key": "reportActions_6604242241623001",
    "value": {
        "6002129300854202153": null
    }
}
```

However, when a request with a detached receipt is removed, this is what comes in the BE response, meaning the action was not removed on the server:
```json
{
    "onyxMethod": "merge",
    "key": "reportActions_6604242241623001",
    "value": {
        "6002129300854202153": {
            "created": "2023-10-25 22:02:26.533"
        }
    }
}
```

First, the report preview disappears because we still have the `"6002129300854202153": null` in the optimistic data, but it's shortly replaced by the BE response for OpenReport operation.

**Comment by sonialiap** [comment] 2023-10-31 11:44
I cannot reproduce this behavior on staging. @lanitochka17 are you still running into this?

https://github.com/Expensify/App/assets/17131195/c0c71585-c592-44c1-abde-6d07ee2d2a71

**Comment by lanitochka17** [comment] 2023-10-31 15:13
Issue reproducible on latest build 1.3.93-1 ( mWeb/Chrome)


https://github.com/Expensify/App/assets/78819774/303eb929-5c51-43f4-8ff3-50297215f8ab

**Comment by sonialiap** [comment] 2023-11-03 12:09
Thanks! Moving this to external

**Comment by voidash** [comment] 2023-11-04 08:58
Hey,
I am not able to create a  Map based receipt

**Comment by voidash** [comment] 2023-11-04 09:01
Contributor details
Your Expensify account email: ashish.thapa477@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e7b4ad5ddca74cb8

**Comment by voidash** [comment] 2023-11-04 09:30
Hey,
I am not able to create a Map based receipt on Chrome on Mac
Version 119.0.6045.105 (Official Build) (arm64)

https://github.com/Expensify/App/assets/23181294/115304e4-cb8d-4ab9-9557-dc86d176c0d6

**Comment by paultsimura** [comment] 2023-11-04 09:37
@sonialiap you may want to make this internal, please check: https://github.com/Expensify/App/issues/30393#issuecomment-1780123707

**Comment by sonialiap** [comment] 2023-11-09 18:52
:salutes: adding internal label

**Comment by joelbettner** [comment] 2023-11-14 19:12
@neil-marcellini any ideas with this?

**Comment by neil-marcellini** [comment] 2023-11-14 19:40
Aha yes we decided that [here in Slack](https://expensify.slack.com/archives/C05DWUDHVK7/p1698085969376549?thread_ts=1698085763.744569&cid=C05DWUDHVK7) (internally), in relation to this issue [Distance - Unable to save distance edit after deleting receipt](https://github.com/Expensify/App/issues/29684). They have implemented backend changes to prevent that and are still working on the front end changes.

Once that issue is completed we should no longer be able to reproduce this bug, therefore we can close it now.

**Closed by neil-marcellini** 2023-11-14 19:40 UTC
Labels: External, Engineering, Daily, Internal, Bug
