### ISSUE TITLE
[$500] App missing parameter triggers backend error

### ISSUE THREAD

**Issue by tylerkaraszewski** [Expensify/App#33099] opened 2023-12-14 17:48 UTC
This issue was created: https://github.com/Expensify/Expensify/issues/349757

Because this line:
https://github.com/Expensify/App/pull/30737/files#diff-112aa19f2ab27905a9cd6ce992a483fff32792ea32ede1767f2af6e42e1e548bR130

Seems to have been triggered without a `transaction` object. Since this code was jsut introduced on staging yesterday, I'm assigning @tgolen to look.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2cd3f67471d554b</li>
        <li>Upwork Job ID: 1735678345901907968</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by blimpich** [comment] 2023-12-14 18:42
@tylerkaraszewski should we also remove the upwork posting? https://www.upwork.com/jobs/~010e76e799e61dbd1d

**Comment by tylerkaraszewski** [comment] 2023-12-14 18:49
Yes @blimpich. I don't know how to do that. Is it something you can do?

**Comment by blimpich** [comment] 2023-12-14 18:54
@tylerkaraszewski yup! Just closed it ☑️

**Comment by tgolen** [comment] 2023-12-15 15:09
I am heads down in some other stuff so I am opening this up to contributors to look into it.

**Comment by trjExpensify** [comment] 2023-12-15 15:14
Posted in C+: https://expensify.slack.com/archives/C02NK2DQWUX/p1702653244173719

**Comment by situchan** [comment] 2023-12-15 15:17
Seems like all these regressions came from same PR:
- #33098 
- #33099
- #33103

**Comment by abzokhattab** [comment] 2023-12-15 15:20
Unable to access this issue: https://github.com/Expensify/Expensify/issues/349757

**Comment by trjExpensify** [comment] 2023-12-15 15:21
One of Tyler's comments is: 

>Someone called UpdateMoneyRequestDate with no transactionID.

**Comment by situchan** [comment] 2023-12-15 15:36
This is dupe of https://github.com/Expensify/App/issues/33098.
So transactionID is missing in `UpdateMoneyRequestDate` api param when update date 2nd time in offline mode

<img width="1411" alt="bug" src="https://github.com/Expensify/App/assets/108292595/d61ef967-a6d0-47f6-abfa-045e8ccd4947">

**Comment by rushatgabhane** [comment] 2023-12-18 06:40
not sure how i can help here

**Comment by trjExpensify** [comment] 2023-12-18 12:00
So @situchan are you saying we should close this issue in favour of https://github.com/Expensify/App/issues/33098?

**Comment by situchan** [comment] 2023-12-18 12:01
> So @situchan are you saying we should close this issue in favour of #33098?

yes

**Comment by situchan** [comment] 2023-12-18 12:02
Or @tylerkaraszewski can double check before closing, as the fix is now on staging

**Comment by jasperhuangg** [comment] 2023-12-19 01:51
I re-tested these flows and they appear to be working, closing this out

**Closed by jasperhuangg** 2023-12-19 01:51 UTC
Labels: DeployBlockerCash, External, Hourly, Help Wanted, Bug
