### ISSUE TITLE
Search-Message send are not updated in real time in chats

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49175] opened 2024-09-13 13:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @1subodhpathak
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726155798962129

## Action Performed:
1. Open Chats from Search
2. Open any existing chat
3. Add a new message
4. Click the back arrow 

## Expected Result:
Added message updated in real time
## Actual Result:
Message updated only after visiting someother tab and coming back to "Chats"
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/601b2b89-76e9-45e3-ad39-c3030426eb8c

https://github.com/user-attachments/assets/e69a0a2d-f785-414a-a89d-481a768101b1

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-09-13 14:39
Hmm, I could see both sides to this one. On one hand, it seems a bit odd that if you're looking at the search page and sending a message in a chat, that you don't see it appear while sending it. 

But equally if you're in a bunch of rooms (with a lot of incoming messages) and are looking at the search page, it might be annoying to have it constantly updating while you're looking at it, rather than it just being a snapshot of when you clicked on it. 

@luacmartins is there an intended behavior here from the implementation?

**Comment by luacmartins** [comment] 2024-09-13 15:00
Currently, we receive live updates only for messages that are already on your Search page. Maybe we'll support pushing new data to the page in the future, but not at this time. We can close this one.

**Comment by joekaufmanexpensify** [comment] 2024-09-13 15:01
Sounds good. Thanks for confirming!

**Closed** 2024-09-13 15:01 UTC
Labels: Daily, Bug
