### ISSUE TITLE
[$250] Saved search - Selected saved search is no longer highlighted after changing sorting

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49227] opened 2024-09-15 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+khcategory16@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Add filters.
5. Click Save search.
6. Open the saved search.
7. Change the sorting.

## Expected Result:
The selected saved search should remain highlighted after changing sorting because the filters remain unchanged.

## Actual Result:
The selected saved search is no longer highlighted after changing sorting.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b56eefc0-ef1f-461e-b096-31cb29380cee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835414058564092667</li>
        <li>Upwork Job ID: 1835414058564092667</li>
        <li>Last Price Increase: 2024-09-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by jaydamani** [comment] 2024-09-15 21:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selected saved search is no longer highlighted after changing sorting

### What is the root cause of that problem?

when comparing the current filter with saved filter, we take hash of the search query in url which includes sort field.

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/Search/SearchTypeMenu.tsx#L107

### What changes do you think we should make in order to solve the problem?


Update [here](https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/Search/SearchTypeMenu.tsx#L107) to use queryString obtained from current filter and compare it with saved query

```js
    const [searchAdvancedFilters = {} as SearchAdvancedFiltersForm] = useOnyx(ONYXKEYS.FORMS.SEARCH_ADVANCED_FILTERS_FORM);
    const queryString = useMemo(() => SearchUtils.buildQueryStringFromFilterValues(searchAdvancedFilters) || '', [searchAdvancedFilters]);
```
```js
    focused: item.query === queryString,
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by luacmartins** [comment] 2024-09-15 22:45
I think this behavior is expected for now. Once we change anything about the saved search, it is no longer the saved search you created, so I think it's expected that we don't highlight it anymore. Especially once we add the search bar and users can specify the column and order they want to search by.

**Comment by luacmartins** [comment] 2024-09-15 22:45
Gonna close this for now.

**Closed by luacmartins** 2024-09-15 22:45 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
