### ISSUE TITLE
[HOLD for payment 2024-06-20] mWeb - Bank account - App crashes when connecting online with Plaid and trying to start over

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43598] opened 2024-06-12 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** unable to check with test credentials
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621717
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
Pre-requisite: user must have created a Workspace and have enabled Workflows. During this process, no page should be reloaded or refreshed.

1. Go to Settings > Workspaces > Workspace > Workflows.
2. Tap on "Connect bank account".
3. Tap on "Connect online with Plaid" and select Regions bank.
4. Enter testing credentials, account and continue.
5. Enter "First" and "Last" as First name and Last name.
6. Select any date of birth.
7. Once on the SSN page, tap a few times on the back arrow icon on the top left corner, until you get to the "Continue with setup" or "Start over" page.
8. Tap on Start over button and confirm.

## Expected Result:
The app should continue to work, starting over the add bank account process.

## Actual Result:
The app crashes after trying to start over the process.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/2afd732a-2559-43e2-8cdd-294b501016b2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala / @mallenexpensify</details>

**Comment by srikarparsi** [comment] 2024-06-12 19:03
I'm not able to reproduce this, @abekkala do you think you could take a look? This [SO](https://stackoverflowteams.com/c/expensify/questions/342) under step 3 has the instructions for plaid. I think it might have something to do with the testing account but still looking at other things it could be.

https://github.com/Expensify/App/assets/48188732/91c40ff2-64ef-48e6-9ec7-42e60979dad6

**Comment by abekkala** [comment] 2024-06-12 19:08
@srikarparsi I'm currently not able to access ND 😬 to attempt reproduction. I can post in slack to see if someone can try to reproduce

**Comment by srikarparsi** [comment] 2024-06-12 19:10
Sounds good thanks!

**Comment by luacmartins** [comment] 2024-06-12 19:30
This seems to happen on mWeb only. I'm trying to get into the site on mWeb but can't seem to load it in my real devices and the emulators dont seem to load plaid.

**Comment by srikarparsi** [comment] 2024-06-12 20:05
Also occurring in [prod](https://expensify.slack.com/archives/C01GTK53T8Q/p1718222604388189?thread_ts=1718216901.948689&cid=C01GTK53T8Q). Removing the deploy blocker label and I think @luacmartins has a fix for this.

**Comment by abekkala** [comment] 2024-06-20 13:14
### NO PAYMENTS NEEDED

FIX AND PR REVIEW WAS DONE INTERNAL

**Closed by abekkala** 2024-06-20 13:14 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
