### ISSUE TITLE
[Payment Due Oct 1][$250] [#fast-apis] Subscribe guides to a new presence pusher channel 

### ISSUE THREAD

**Issue by MonilBhavsar** [Expensify/App#47888] opened 2024-08-22 22:52 UTC
### Context:

Guides are agents who help new customers with onboarding.

We use Pusher to send real time updates.
We have a private user channel here https://github.com/Expensify/App/blob/f7d8e4850e729493eb8bfb52efa1a49d0d344ded/src/CONST.ts#L1154
`private-encrypted-user-accountID-<>` that is used to receive various events in real time like onyx updates, user typing and more.

### Problem

Pusher private channel is dynamic, or unique for each user as it contains an accountID.
For example: A channel name could look like `private-encrypted-user-accountID-5-b8645604fe014e82b765ca84b7df1f2e`

At the server side, if we want to know how many guides are online at the current time, then we need to make an API call to each pusher channel and see if it is occupied or not.
If we have 20 guides, then we make 20 API calls to check guide's presence, which is not efficient.

### Solution

Make guides subscribe to a presence channel - `activeGuides`
https://pusher.com/docs/channels/using_channels/presence-channels/

With this, a server only will have to make one API call to find all active guides or users subscribed to this channel.

If a user is a guide - i.e. have a `team.expensify.com` domain  and belongs to a specific policyID, then we additionally subscribe guide to the the guides presence channel.

Like the private user channel, a subscription to the channel should indicate guide's presence in the app - They should be subscribed if they login and are active, and should be unsubscribed if they sign out.

We probably have most of the code and logic for the private user channel. We need to similarly subscribe guides to the new channel.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe75f988a6386f2e</li>
        <li>Upwork Job ID: 1826754279960805798</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103739965</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by MonilBhavsar** [comment] 2024-08-23 14:07
> if user has team.expensify.com domain but does not belongs to specific workspace, should we subscribe to the presence pusher channel?

No, both conditions are required

**Comment by MonilBhavsar** [comment] 2024-08-23 14:08
Thanks for the proposals! 🚀 
@situchan could you please take a look.

**Comment by mariapeever** [comment] 2024-08-24 00:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[#fast-apis] Subscribe guides to a new presence pusher channel #47888
### What is the root cause of that problem?
Guide users are subscribed to a private encrypted user channel only and not subscribed to a presence channel ('presence-activeGuides').
### What changes do you think we should make in order to solve the problem?
If a user is a guide, i.e. their email is an expensify team email, add a Pusher subscription to a presence channel request (PusherUtils.subscribeToPresenceChannelEvent) to the subscribeToUserEvents function in User (called in AuthScreens after Pusher init).

Add a subscribeToPresenceChannelEvent function to Pusher Utils with a Pusher subscribe request. All guides are subscribed to the same presence channel. Subscription to a presence channel adds a members property to the pusher socket, which includes a members count.

https://github.com/Expensify/App/blob/a29977bb8490e231d28babac11c6dc8650d19de8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L254-L262

Add a PusherUtils.subscribeToPresenceChannelEvent request just after PusherUtils.subscribeToPrivateUserChannelEvent.
https://github.com/Expensify/App/blob/a29977bb8490e231d28babac11c6dc8650d19de8/src/libs/actions/User.ts#L660-L674
Add a subscribeToPresenceChannelEvent function just after subscribeToPrivateUserChannelEvent.
https://github.com/Expensify/App/blob/a29977bb8490e231d28babac11c6dc8650d19de8/src/libs/PusherUtils.ts#L29-L31
Include a Pusher.subscribe request in the subscribeToPresenceChannelEvent function with channel name 'presence-activeGuides'.
https://github.com/Expensify/App/blob/a29977bb8490e231d28babac11c6dc8650d19de8/src/libs/PusherUtils.ts#L48

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment] 2024-08-26 19:46
@daledah thanks. What is the benefit of introducing new ActiveGuidesEventListener? Can't we just subscribe after subscribeToUserEvents()?

**Comment by situchan** [comment] 2024-08-26 19:52
>  it will subscribe to presence channel even if user is not in any policy.

Ofc we'll check if user belongs to specific policy

**Comment by situchan** [comment] 2024-08-26 20:00
> > Ofc we'll check if user belongs to specific policy
> 
> Yeah. If we subscribe after subscribeToUserEvents(), we cannot check if user belongs to specific policy, right?

Makes sense. We may need to connect ONYXKEYS.COLLECTION.POLICY in AuthScreens

@Krishna2323 what about [this concern](https://github.com/Expensify/App/issues/47888#issuecomment-2310968947)?

**Comment by situchan** [comment] 2024-08-26 20:21
@Krishna2323 pusher init is called on AuthScreens component mount

**Comment by situchan** [comment] 2024-08-26 20:22
@daledah @Krishna2323 please test your solutions and confirm working

**Comment by MonilBhavsar** [comment] 2024-08-26 20:29
We can also make a backend return a flag - isGuide, if we think we're comprising frontend performance by connecting onyx in AuthScreens. And also, we don't load all policies upfront, so it might be that a guide is not being correctly identified as guide and hence not subscribed to pusher channel

**Comment by situchan** [comment] 2024-08-26 20:47
@MonilBhavsar `isGuide` will be added to `session` or `user`?

**Comment by MonilBhavsar** [comment] 2024-08-26 21:02
`user` sounds more approproiate

**Comment by MonilBhavsar** [comment] 2024-08-26 21:09
> We just need to check if the user belongs to at least one policy or not, so I don't think we need to load all policies. What do you think?

How would we check? I mean not all policies would be loaded in Onyx

**Comment by MonilBhavsar** [comment] 2024-08-26 21:27
> So we can check if user belongs to at least one policy based on those 20 policies, no need for all 100 policies returned.

Yes, but if the guide policy is not returned in those 20 policies, then code can go wrong, no

**Comment by MonilBhavsar** [comment] 2024-08-26 21:28
>  if we can add the flag to the session object

`user` sounds more better to me than `session`

**Comment by situchan** [comment] 2024-08-26 21:33
Looks like the solution would be to
- connect ONYKEYS.USER to AuthScreens
- subscribeToActiveGuides followed by subscribeToUserEvents if user.isGuide = true

Just need to make sure that user is fetched correctly at the time of pusher init
@Krishna2323 please confirm

**Comment by MonilBhavsar** [comment] 2024-08-26 21:39
Why subscribe to PERSONAL_DETAILS_LIST?

**Comment by situchan** [comment] 2024-08-27 09:30
@Krishna2323 are you connecting onyx inside component lifecycle?

**Comment by situchan** [comment] 2024-08-27 18:17
@Krishna2323 please share your test branch. And also test yourself

**Comment by situchan** [comment] 2024-08-27 21:47
> @situchan, my solution does not check if the pusher is initialized or no

Thanks. Was about to say that 😄

**Comment by situchan** [comment] 2024-08-27 21:51
@daledah now that all questions are answered, can you please clarify https://github.com/Expensify/App/issues/47888#issuecomment-2310955054?

**Comment by situchan** [comment] 2024-08-28 04:39
I think we can go with @daledah's [proposal](https://github.com/Expensify/App/issues/47888#issuecomment-2306017912).
@MonilBhavsar all yours

**Comment by MonilBhavsar** [comment] 2024-08-28 16:40
@daledah do we need server to provide `isGuide` or are we checking that in the frontend?

**Comment by MonilBhavsar** [comment] 2024-08-29 17:06
@daledah what do you think about this for the case when isGuide is not provided https://github.com/Expensify/App/issues/47888#issuecomment-2311129566

> Yes, but if the guide policy is not returned in those 20 policies, then code can go wrong, no

**Comment by MonilBhavsar** [comment] 2024-08-29 18:56
Sounds good! Let's do it. Let's make sure to test on an account with at least 10 policies so we can know if it really works

**Comment by MonilBhavsar** [comment] 2024-08-29 18:56
Thanks all for the proposals though!

**Comment by MonilBhavsar** [comment] 2024-08-29 18:59
The channel name is `activeGuides`

**Comment by MonilBhavsar** [comment] 2024-08-29 19:17
I think the best way to test is to write a small server side code snippet. Mostly PHP as - 

Pseudo code: 
```php
$pusher = init();
$subscribedUsers = (array) $pusher->get('/channels/'.(string) $channel.'/users');
```
You can refer to this doc - https://pusher.com/docs/channels/server_api/http-api/#presence-users

And then in newDot, signin, singout and ensure the user gets subscirbed and unsubscribed accordingly

**Comment by MonilBhavsar** [comment] 2024-09-02 22:12
I think event is only for private channels and not for presence channels 🤔

**Comment by MonilBhavsar** [comment] 2024-09-03 19:32
@daledah did you get a chance to see this, or how it is going?

**Comment by MonilBhavsar** [comment] 2024-09-04 17:49
I think that is required when we expect server to send specific events/signals and have client respond/function accordingly. but in this case, server does not really need to send any event to client. Can we make eventName  optional please?

**Comment by situchan** [comment] 2024-09-04 18:43
Not overdue

**Comment by MonilBhavsar** [comment] 2024-09-10 00:14
@daledah let us know how is it going? As mentioned above, this is one of the top priority issues

**Comment by MonilBhavsar** [comment] 2024-09-10 06:47
Yes, I can help with that. Let me know when you have the PR ready.

**Comment by situchan** [comment] 2024-09-10 08:12
Not overdue

**Comment by MonilBhavsar** [comment] 2024-09-24 19:29
Okay, this PR was deployed to production. I'll add a label to assign bug-zero team member to issue payment next week

**Comment by MonilBhavsar** [comment] 2024-09-24 19:31
@dannymcclain sorry for the ping. This was just to issue the payment :D

**Comment by trjExpensify** [comment] 2024-09-25 01:04
Wonderful!

**Comment by trjExpensify** [comment] 2024-10-04 18:07
Payment summary as follows: 

- $250 to @situchan for the C+ review
- $250 to @daledah for the fix 

@situchan I've paid you. @daledah can you send me your upwork profile, please?

**Comment by trjExpensify** [comment] 2024-10-04 18:07
(Great timing, Melv).

**Comment by situchan** [comment] 2024-10-07 06:08
@trjExpensify looks like you forgot to release payment. Contract ended but I don't see any payment 😕

**Comment by trjExpensify** [comment] 2024-10-07 23:42
@situchan paid a bonus for the amount that should have been paid due to the Upwork bug. 
@daledah sent you an offer.

**Comment by trjExpensify** [comment] 2024-10-08 12:30
@daledah paid, closing!

**Closed by trjExpensify** 2024-10-08 12:30 UTC
Labels: External, Daily, Improvement, NewFeature, Awaiting Payment
