### ISSUE TITLE
[$500]  Web – Task – New Task creation opens when use Tab key to choose the Assignee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32390] opened 2023-12-01 22:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
1. Navigate to a 1:1 conversation with a user
2. Click on the + in the compose box and select "Assign task"
3. Enter a Title and a Description
4. Press Enter to Next
5. Use Tab key go to the Assignee and press Enter
6. Go back

## Expected Result:
Assignee is selected in a previously created task

## Actual Result:
New Task creation opens when use Tab key to choose the Assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fa86ce65-cf5a-4808-b49e-46cf85c591e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5bbe671857910e4</li>
        <li>Upwork Job ID: 1730710704283930624</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-01 22:29
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
New Task creation opens when use Tab key to choose the Assignee
### What is the root cause of that problem?
The root cause is that we doesn't set disablePressOnEnter to false.
https://github.com/Expensify/App/blob/db37e46f58aceea23c0136e1bdce6e3ed9d2d90f/src/pages/tasks/NewTaskPage.js#L203
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
  N/A

**Comment by DylanDylann** [comment] 2023-12-02 01:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web – Task – New Task creation opens when use Tab key to choose the Assignee

### What is the root cause of that problem?
- Currently, in NewTaskPage, we have the FormAlertWithSubmitButton:
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/pages/tasks/NewTaskPage.js#L203-L210
- FormAlertWithSubmitButton contains the Button that will listen to the "ENTER" event:
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/Button/index.tsx#L172-L177
- That leads to the case: When we focus on any menu item such as "Assignee" and then press "ENTER", it also trigger the above ```keyboardShortcutCallback```
### What changes do you think we should make in order to solve the problem?
- Generally, we need to prevent the ```keyboardShortcutCallback``` is not triggered if we focused on any menu item, like description, assignee, share somewhere, .... We can do it based on the proposal that is approved before. 
1. For each MenuItem in [NewTaskPage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js#L203), add pass additional prop named ```keyForItem```, for example, update:
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/pages/tasks/NewTaskPage.js#L181-L182
to:
```
                            <MenuItem
                                label={assignee.displayName ? props.translate('task.assignee') : ''}
                                keyForItem={props.translate('task.assignee')}
```

2. Then pass down the above keyForItem to the [PressableWithSecondaryInteraction](https://github.com/Expensify/App/blob/main/src/components/PressableWithSecondaryInteraction/index.js) by updating:
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/PressableWithSecondaryInteraction/index.js#L100
to:
```
        <PressableWithFeedback
            testID={keyForItem}
```

3. Finally, update [validateSubmitShortcut](https://github.com/Expensify/App/blob/main/src/components/Button/validateSubmitShortcut/index.ts) to handle the case we are focusing on some menu item. We can do it by updating:
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/Button/validateSubmitShortcut/index.ts#L13-L21
to:
````diff
const validateSubmitShortcut: ValidateSubmitShortcut = (isFocused, isDisabled, isLoading, event) => {
+  const eventTarget = event?.target as HTMLElement;
+  const focusedItemKey = lodashGet(event, ['target', 'attributes', 'data-testid', 'value']);
+    if(focusedItemKey === 'Assignee') {     // Can be other items like Descripton, Share somewhere, ... 
+      return false;
+    }
    if (!isFocused || isDisabled || isLoading || eventTarget.nodeName === 'TEXTAREA') {
        return false;
    }

    event?.preventDefault();
    return true;
};
````


### What alternative solutions did you explore? (Optional)

- NA

**Comment by fzrcyc** [comment] 2023-12-02 13:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New Task creation opens when use Tab key to choose the Assignee

### What is the root cause of that problem?

When there is a Button component on the screen, regardless of whether other input controls have focused, the Button component will respond to the 'Enter' key event. The code is here.  https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/Button/index.tsx#L160

### What changes do you think we should make in order to solve the problem?

 We need to use the current focus state to determine whether a button is in focus. Based on that decide whether the button should respond to the Enter key event. In the Button Component,  sample code can be managed as follows:

 ```
   const activeElement = useActiveElement();
   const enableEnterShortcut = activeElement
    ? activeElement.role
        ? CONST.ACCESSIBILITY_ROLE.BUTTON == activeElement.role
        : true
    : true

    const isFocused = useIsFocused() && enableEnterShortcut;
```

 Additionally, I've noticed a minor issue: the role prop in MenuItem.js isn't working as intended. Code is here:
 https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/MenuItem.js#L191
The prop being used internally is actually accessibilityRole. 
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/Pressable/GenericPressable/index.tsx#L10-L20
As a result, any attempt to retrieve the role prop from all MenuItem components will return null. 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by joekaufmanexpensify** [comment] 2023-12-04 15:51
Not overdue. Going to triage today.

**Comment by joekaufmanexpensify** [comment] 2023-12-04 21:33
I don't think we need to do anything with this right now. It's a super minor edge case that anyone would ever be selecting a task assignee this way. Closing for now, and we can reevaluate if we any actual customers report this bug.

**Closed by joekaufmanexpensify** 2023-12-04 21:33 UTC
Labels: External, Daily, Help Wanted, Bug
