### ISSUE TITLE
[HOLD for payment 2024-02-09] [$2000] Chat - The message got sent but it also stayed in the compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26347] opened 2023-08-30 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Expensify app
2. Open any conversation
3. Quickly enter any text in the compose box
4. Tap the icon to send a message
5. Quickly repeat steps 3-4 several times

## Expected Result:
The compose box should be scrubbed after each click on the send message icon

## Actual Result:
The compose box doesn't have time to scrub after each click on the send icon and new text is added to the old text already sent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3f44a226-4faa-4495-96e8-219185702ea1

https://github.com/Expensify/App/assets/78819774/1f004dc6-31e4-4452-a70d-fcde3d7443a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb269a50709f3aa2</li>
        <li>Upwork Job ID: 1699460288474398720</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27043430</li>
<li>situchan | Contributor | 27503921</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-09-05 00:14
I feel like this is an age-old issue that we used to run into a LOT.  
https://github.com/Expensify/App/assets/22508304/13ddd9cc-dc69-4a57-a4fd-d4f7e358ec66

Checking on in #expensify-open-source
https://expensify.slack.com/archives/C01GTK53T8Q/p1693872831763299

**Comment by mallenexpensify** [comment] 2023-09-05 00:14
@NicMendonca  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by h0u554m** [comment] 2023-09-06 20:07
You can either wait for a brief moment (e.g., 1-2 seconds) after sending or clear the input field after clicking the button.
i don't have connects in upwork

**Comment by h0u554m** [comment] 2023-09-06 20:13
Contributor details
Your Expensify account email: houssammarrakchimk@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-06 20:14
Contributor details
Your Expensify account email: https://new.expensify.com/a/15606409
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-06 20:16
You can either implement a brief delay (e.g., 1-2 seconds) to prevent the client from clicking the button while it's sending or change the button's icon to a loading indicator to indicate that the action is in progress.

**Comment by andruxnet** [comment] 2023-09-06 21:01
When the Send button is pressed, it should get disabled to prevent unintended, multiple presses. Then, the message should be sent, and the composer box cleared. After this the Send button gets enabled again, ready for new messages.

Contributor details
Your Expensify account email: aolvera@andrux.net
Upwork Profile Link: https://www.upwork.com/freelancers/~01634d5f25c3c5b849?viewMode=1

**Comment by h0u554m** [comment] 2023-09-06 21:16
https://github.com/Expensify/App/blob/0e836df546939a9d905fee03b31879242de38a3b/src/pages/home/ReportScreen.js#L241

```

/**
 * @param {String} text
 */
const onSubmitComment = useCallback(
  (text) => {
    // Disable the function temporarily
    setSubmitDisabled(true);

    // Wait for 1 second (you can adjust the delay as needed)
    setTimeout(() => {
      // Re-enable the function
      setSubmitDisabled(false);
      
      // Now you can perform the comment submission
      Report.addComment(getReportID(route), text);
    }, 1000); // 1000 milliseconds = 1 second
  },
  [route]
);

// In your component, you can track whether submission is disabled
const [submitDisabled, setSubmitDisabled] = useState(false);

// You can conditionally disable the button based on submitDisabled
// For example:
{/* <button onClick={() => onSubmitComment('Your comment')} disabled={submitDisabled}>Submit Comment</button> */}


```

Contributor details
Your Expensify account email: https://new.expensify.com/a/15606409
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6

**Comment by mallenexpensify** [comment] 2023-09-11 05:31
Thanks @NicMendonca. @aimane-chnaif, can you review the @h0u554m 's proposal above? I'm hoping this is a new _discrete_ issue and not related to a bug from a year ago 🤞

**Comment by h0u554m** [comment] 2023-09-11 16:14
Is it new

**Comment by h0u554m** [comment] 2023-09-11 16:14
@mallenexpensify

**Comment by h0u554m** [comment] 2023-09-13 09:24
Certainly, here's a refactored version of your problem statement, root cause analysis, proposed solution, and contributor details:

**Problem Statement:**
We need to address an issue where, upon multiple rapid clicks, the message is not reset to its default empty state when sending a message.

**Root Cause Analysis:**
The problem arises due to multiple presses on the send message button in quick succession.

**Proposed Solution:**
To solve this issue, we can implement a brief delay of 1-2 seconds to prevent the client from clicking the button while the message is being sent.

**Alternative Solution Considered:**
Another alternative solution is to change the button's icon to a loading indicator to indicate that the action is in progress.

**Solution Implementation:**
You can find the code implementation for this solution at this [GitHub link](https://github.com/Expensify/App/blob/0e836df546939a9d905fee03b31879242de38a3b/src/pages/home/ReportScreen.js#L241).

Here's the refactored code for the solution:

```javascript
/**
 * @param {String} text
 */
const onSubmitComment = useCallback(
  (text) => {
    // Disable the function temporarily
    setSubmitDisabled(true);

    // Wait for 1 second (you can adjust the delay as needed)
    setTimeout(() => {
      // Re-enable the function
      setSubmitDisabled(false);
      
      // Now you can perform the comment submission
      Report.addComment(getReportID(route), text);
    }, 1000); // 1000 milliseconds = 1 second
  },
  [route]
);

// In your component, you can track whether submission is disabled
const [submitDisabled, setSubmitDisabled] = useState(false);

// You can conditionally disable the button based on submitDisabled
// For example:
{/* <button onClick={() => onSubmitComment('Your comment')} disabled={submitDisabled}>Submit Comment</button> */}
```


Contributor details
Your Expensify account email: houssammarrakchimk@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6

**Comment by h0u554m** [comment] 2023-09-13 09:24
@aimane-chnaif

**Comment by h0u554m** [comment] 2023-09-13 09:32
@aimane-chnaif can you explain more

**Comment by h0u554m** [comment] 2023-09-13 09:41
Okay 1s i will fix it

**Comment by h0u554m** [comment] 2023-09-13 09:54
**Problem Statement:**
We need to address an issue where, upon multiple rapid clicks, the message is not reset to its default empty state when sending a message.

**Root Cause Analysis:**
The root cause of the issue is multiple rapid clicks on the "send message" button. These rapid clicks can interfere with the expected behavior, preventing the message from being reset to its default empty state.

**Proposed Solution:**
disable the button when onSubmitComment is called, perform the comment submission asynchronously, handle any errors, and then re-enable the button using the try...catch...finally pattern.

**Solution Implementation:**
You can find the code implementation for this solution at this [GitHub link](https://github.com/Expensify/App/blob/0e836df546939a9d905fee03b31879242de38a3b/src/pages/home/ReportScreen.js#L241).

Here's the refactored code for the solution:

`
const onSubmitComment = useCallback(
  async (text) => {
    // Disable the function temporarily
    setSubmitDisabled(true);

    try {
      // Now you can perform the comment submission
      await Report.addComment(getReportID(route), text);
      
      // Comment submitted successfully, you can add any success handling here if needed
    } catch (error) {
      // Handle any errors here
      console.error("Comment submission error:", error);
    } finally {
      // Re-enable the function
      setSubmitDisabled(false);
    }
  },
  [route]
);
`


**Contributor Details:**
- Expensify Account Email: [Your Expensify account email](https://new.expensify.com/a/15606409)
- Upwork Profile Link: [Your Upwork Profile Link](https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6)

**Comment by h0u554m** [comment] 2023-09-13 09:56
@aimane-chnaif  i think that better what is your opinion please

**Comment by mallenexpensify** [comment] 2023-09-19 09:11
@aimane-chnaif can you review @h0u554m 's updated proposal and provide feedback?
https://github.com/Expensify/App/issues/26347#issuecomment-1717316009

**Comment by andruxnet** [comment] 2023-09-20 04:28
## Proposal
[Updated](https://github.com/Expensify/App/issues/26347#issuecomment-1709112190)

**Comment by h0u554m** [comment] 2023-09-20 12:04
**Problem Statement:**
We need to address an issue where, upon multiple rapid clicks, the message is not reset to its default empty state when sending a message.

**Root Cause:**
The root cause of this problem stems from the inefficiency of the existing compose box clearing process. It fails to execute quickly enough to match the pace of rapid, successive input and sending of messages. As a result, the compose box clearance process lags behind, leading to the unintended overlap of old and new message text

**Proposed Solution:**
disable the button when onSubmitComment is called, perform the comment submission asynchronously, handle any errors, and then re-enable the button using the try...catch...finally pattern.

**Solution Implementation:**
You can find the code implementation for this solution at this [GitHub link](https://github.com/Expensify/App/blob/0e836df546939a9d905fee03b31879242de38a3b/src/pages/home/ReportScreen.js#L241).

Here's the refactored code for the solution:


```

const onSubmitComment = useCallback(
  async (text) => {
    // Disable the function temporarily
    setSubmitDisabled(true);

    try {
      // Now you can perform the comment submission
      await Report.addComment(getReportID(route), text);
      
      // Comment submitted successfully, you can add any success handling here if needed
    } catch (error) {
      // Handle any errors here
      console.error("Comment submission error:", error);
    } finally {
      // Re-enable the function
      setSubmitDisabled(false);
    }
  },
  [route]
);

```



**Contributor Details:**
- Expensify Account Email: [Your Expensify account email](https://new.expensify.com/a/15606409)
- Upwork Profile Link: [Your Upwork Profile Link](https://www.upwork.com/en-gb/freelancers/~01d68a22e5d906bca6)

**Comment by andruxnet** [comment] 2023-09-21 05:14
## Proposal
[Updated](https://github.com/Expensify/App/issues/26347#issuecomment-1709112190)

Dag deeper into the code so hopefully my assessment is more accurate now.

**Comment by mallenexpensify** [comment] 2023-09-25 08:15
Doubled to get more 👀 and proposals

**Comment by mallenexpensify** [comment] 2023-10-02 17:08
@aimane-chnaif do you have a physical Android device you can test this on? I was unable to reproduce on v1.3.75-12 iOS native app

**Comment by mallenexpensify** [comment] 2023-10-02 19:35
Bumped to $2000 and made external to see if we can get proposals THIS week. If not, I'll bring it back internal and try to rally an engineer to help

**Comment by andruxnet** [comment] 2023-10-03 05:20
## Proposal
[Updated](https://github.com/Expensify/App/issues/26347#issuecomment-1709112190)

Hopefully my solution is acceptable.

**Comment by andruxnet** [comment] 2023-10-04 15:28
@aimane-chnaif Understood. Thanks for reviewing the proposal.

Just one thing, even though my solution doesn't fix the actual root cause, it does prevent the problem caused by that root cause from happening, and produces the expected result as requested in the body of the issue as:

> ### Expected Result:
> The compose box should be scrubbed after each click on the send message icon

Just a thought. It might be worth giving it a try before discarding it.

Cheers.

**Comment by hurali97** [comment] 2023-10-05 12:24
Proposal: Refactor ReportActionCompose and ComposeWithSuggestions for smooth message sending behaviour

<hr />
<br />

**Problem:**
There is not one root cause of this issue but multiple. Following is the list which are the cause of the issue in composer, with first one having the highest participation in the root cause.

1.  `Report.addComment(getReportID(route), text)` halts the main thread and due to which when user types in quickly and send a message and then continue typing, some parts of the message will still be in the input or the input won’t get cleared because of thread throttling.

2. Re-rendering `ReportActionCompose` and it’s children is not ideal here. `isCommentEmpty` is that state value which we can move around, more details in Solution.

3. draft related call `saveReportComment` is really expensive. This call is made when user starts to type and when hits the send button.

4. When click on send button, whole `ReportActionCompose` and it’s children gets re-rendered. Not ideal here as this is just an input based component and can probably live without a re-render.

5. With each key stroke `ComposeWithSuggestions` re-renders due to `setValue` and `setSelection`.

<hr />
<br />

**Solution:**

1. Investigation in process on how to make `addComment` call more performant. ⌛ 

2. Move state for `isCommentEmpty` to a separate component, which will include `SendButton` and `ComposeWithSuggestions`
    - This is essential to avoid re-rendering `ReportActionCompose` directly and it’s children

3. Move draft related onyx calls when tapped on Send button to onClear
    - Especially `saveReportComment` since it takes a lot of time from setting the state til the re-render
    - Also, we have to analyse why `saveReportComment` is taking a lot of time since it also hinders the toggling of Send button disable status. ( This is partially fixed by https://github.com/Expensify/App/pull/28469 )
    - If you'll comment out `saveReportComment`, with the above PR change the toggle becomes really fast. 

4. When click on send button, whole `ReportActionCompose` and it’s children gets re-rendered.
    - In theory, there’s no need to re-render Compose because it’s not displaying any report messages, so ideally only the list should re-render

5. With each key stroke `ComposeWithSuggestions` re-renders due to setValue and setSelection. There are a couple of ways to reduce that.
    - Move `setValue` to the `Composer` directly and selection as well and let it handle everything and re-render itself. Which means removing `setValue` and `setSelection` from Parent and moving to `Composer`.
    - There are places where we need `value` and we can use ref for that.
    - Or we can just move the `selection` state to `Composer`, since it also has `selection` state internally, so we can combine them.
    - Since child components like `Suggestions` and `SilentCommentUpdater` uses `value`, we can add a debounce to `setValue` and refactor the above point.


In the attached videos, I have commented `Report.addComment` for both before and after. In after, I have applied only a couple of fixes from within the list.

<details>
<summary>Before</summary>

https://github.com/Expensify/App/assets/47336142/88f09ffe-3d37-4d7d-b6d7-129089df1b23

</details>

<details>
<summary>After</summary>

https://github.com/Expensify/App/assets/47336142/f809eb21-3e98-4317-a64a-ea985631959b

</details>

**Comment by mountiny** [comment] 2023-10-05 17:28
@kacper-mikolajczak can you please comment on this issue too.

Thanks everyone for the proposals, this was a tough issue and Callstack did a deep dive and identified some of the issues closer to root cause, if not the root cause itself (its a combination really).

**Comment by jeet-dhandha** [comment] 2023-10-05 18:01
Can I dig deeper in this one ?

**Comment by mountiny** [comment] 2023-10-05 18:28
@jeet-dhandha I believe Callstack engineers will start a PR soon so you can but this job is assigned to them

**Comment by kacper-mikolajczak** [comment] 2023-10-05 18:38
@mountiny I am present 👍

**Comment by mallenexpensify** [comment] 2023-10-10 00:46
@kacper-mikolajczak to help set expectations, do you know when you might have a proposal ready to review? It sounds like this might be a complex fix

**Comment by kacper-mikolajczak** [comment] 2023-10-10 07:45
Hi @mallenexpensify, I am continuing the work Hur started with [this proposal](https://github.com/Expensify/App/issues/26347#issuecomment-1748791267). I am currently double checking with my own measurments and finding the best suited implementation of solutions suggested in his proposal 👍 

Do you think we need a brand new proposal, or can I based my work on Hur's one? Thanks!

**Comment by mallenexpensify** [comment] 2023-10-11 02:37
Thanks for the update @kacper-mikolajczak !

**Comment by kacper-mikolajczak** [comment] 2023-10-13 17:46
Hi team! 

Down below I present current state of the improvements. All changes are available in the PR https://github.com/Expensify/App/pull/29561.

### Updates

1. memoized `useDebounce` callback to prevent re-rendering 🧹 
2. `personalDetails` is now passed as a prop to `Suggestion` component through context instead of triggering `withOnyx` HOC for that on each key stroke. This enabled us to reduce rendering times when typing in the `Composer` from **~80ms** to **~3ms** on iOS simulator 🏎️ 
3. removed `withReportCommentDrafts` HOC dependency from `OptionRowLHNData` component, that caused entire LHN list to be re-rendered when draft is being saved. With this improvement we avoid heavy calculation that is represented in the recording as a single spike in profiling trace. This needs to be further discussed if HOC is safe to be removed, so let's move this discussion into PR 👍

### Results

Before

https://github.com/Expensify/App/assets/62747088/ee83ffe9-3ac6-4232-9821-95c722082320

After

https://github.com/Expensify/App/assets/62747088/807d2d18-9c99-4be0-b544-fc9a5678fdca

Let me know what you think about those improvements. It is still work in progress and I suspect there is more to be done in that matter 🔧  Have a nice weekend! 👋 

CC @mallenexpensify

**Comment by kacper-mikolajczak** [comment] 2023-10-16 09:55
Hi @mallenexpensify, 

with these changes we aim to solve parts of the issues brought up in original @hurali97's proposal.

In order not to lose the velocity, we decided that I will continue to work on implementation of aforementioned improvements and @hurali97 will focus on rest of the original proposal.

Existing PR will be merged separately and we will add more to it as we explore new findings 👍 

Let me know what you think, thanks!

**Comment by mallenexpensify** [comment] 2023-10-16 19:22
Thanks @kacper-mikolajczak , doesn't that mean there's be two PRs for this one issue? I don't foresee a problem, outside of some automation we have that might create some posts and such.  If needed, we could break this into two issues, but it doesn't seem like that's necessary

**Comment by kacper-mikolajczak** [comment] 2023-10-17 08:10
@mallenexpensify That's right, there is going to be two PRs, so we can work in parallel. We can split the issues if that makes more sense, let me know what you think 👍

**Comment by mountiny** [comment] 2023-11-27 14:52
PR  is in review

**Comment by mallenexpensify** [comment] 2024-01-24 01:04
PR hit production forevvvver ago and I missed it cuz the `Reviewing` label wasn't removed and `Overdue` wasn't added. 
https://github.com/Expensify/App/pull/29561#issuecomment-1805969919

First... sorry 😿 
Second... I see both @situchan and @aimane-chnaif assigned here and they were both hired for the job.  Which is C+ and how much is due?  I accidentally paid each $2000.   

Contributor+: @situchan paid $2000 via Upwork
Contributor+: @aimane-chnaif paid $2000 via Upwork.

**Comment by mountiny** [comment] 2024-01-24 01:16
I think its not done yet we still have this pr https://github.com/Expensify/App/pull/30168

**Comment by mountiny** [comment] 2024-01-31 16:23
Second PR got merged

**Comment by mallenexpensify** [comment] 2024-02-09 23:29
@mountiny, both @situchan and @aimane-chnaif [have been paid $2k](https://github.com/Expensify/App/issues/26347#issuecomment-1907176787), Is that correct? 

What regression tests do we need for this??!?!

**Comment by mountiny** [comment] 2024-02-14 14:37
Not sure what are the best regression steps for this. I think its one of those we would raise over time if it comes back

Has there been reliable reproduction steps?

**Comment by mallenexpensify** [comment] 2024-02-18 19:17
@situchan and @aimane-chnaif , from [above,](https://github.com/Expensify/App/issues/26347#issuecomment-1907176787) can you confirm this is correct?
> Contributor+: @situchan paid $2000 via Upwork
> Contributor+: @aimane-chnaif paid $2000 via Upwork.

I'm unaware of reliable reproduction steps.  @hurali97 @kacper-mikolajczak @aimane-chnaif @situchan , any of you know?

**Comment by mallenexpensify** [comment] 2024-02-20 23:37
TestRail GH created - https://github.com/Expensify/Expensify/issues/371196 

> Not exactly sure about the amount.

I'm going to leave as-is then and close this. Comment/reopen if you disagree.

**Closed by mallenexpensify** 2024-02-20 23:37 UTC
Labels: External, Weekly, Awaiting Payment, Bug
