### ISSUE TITLE
Buttons with 'PressableWithFeedback' - cursor changes to disabled on 4th click

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#19137] opened 2023-05-17 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to add bank account modal
2. Select the manual option and enter test credentials 
3. Click the submit button multiple times quickly without filling the inputs.

## Expected Result:
Cursor should not change to disabled 

## Actual Result:
Cursor changes to disabled after the 4th click. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.15-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes (but after the second click)

**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/44479856/fc7b841f-1d69-4333-968d-125bfd9428e2

![image](https://github.com/Expensify/App/assets/44479856/49472be6-dd44-4999-94cb-ac05664dd878)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Issue found and failing step 3 of this PR - https://github.com/Expensify/App/pull/18865

**Comment by roryabraham** [comment] 2023-05-17 20:14
I think this is expected. Basically:

1. By default, a button is disabled when you click it until its callback completes
1. After a button enters the disabled state, the disabled cursor should not show until after the button has been in the disabled state for > 1 second.

So in this case, since the button is actually disabled, the disabled cursor should appear after 1 second.

**Comment by roryabraham** [comment] 2023-05-17 20:19
Interestingly, I'm also not able to reproduce this (after testing w/ plaid, not manual bankaccount + routing numbers)

**Comment by roryabraham** [comment] 2023-05-17 20:23
Okay, I've finally managed to reproduce this. I do think this is essentially expected though. It only happens rarely, I think when the UI is locked up waiting for `InteractionsManager` to finish handling the last interaction. Going to close this.

**Closed by roryabraham** 2023-05-17 20:23 UTC
Labels: Daily, Bug
