### ISSUE TITLE
[HOLD for payment 2024-10-29] [HOLD for payment 2024-10-25] Invoice - Merchant and date options not displayed on confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51078] opened 2024-10-18 09:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50.6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5095136
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the hybrid app (or normal NewDot app) and log in
2. Create a workspace if needed
3. Navigate to workspace settings > More features
4. Enable the Invoice feature
5. Navigate to the LHN
6. Tap FAB > Invoice
7. Enter the amount and select the user you want to send an invoice
8. Proceed to the confirmation screen

## Expected Result:
The Merchant and date options are displayed on the confirmation page

## Actual Result:
The Merchant and date options are missing on the confirmation page

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f4ff4ddd-a879-4abb-baa8-11b8abf40b0d

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by IuliiaHerets** [comment] 2024-10-18 09:43
We think that this bug might be related to #vip-bills

**Comment by mkzie2** [comment] 2024-10-18 10:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Merchant and date options are missing on the confirmation page

### What is the root cause of that problem?

We fallback to `selectedTab` when first start the IOU flow:

https://github.com/Expensify/App/blob/7cd46a7b0b7ba7045f119fc1f48dd7e292033896/src/pages/iou/request/IOURequestStartPage.tsx#L61

But in case of invoice, pay or send, we do not use tab navigator. For those IOU types, the request type is always `manual`.

### What changes do you think we should make in order to solve the problem?


Rewrite the request type logic:

```javascript
transaction?.iouRequestType ?? (iouType !== CONST.IOU.TYPE.SEND && iouType !== CONST.IOU.TYPE.PAY && iouType !== CONST.IOU.TYPE.INVOICE ? selectedTab : 'manual')
```

**Comment by Beamanator** [comment] 2024-10-18 10:32
Hmm @mkzie2 I'm not seeing the map displayed like you are, and I checked that my iPhone does have location permission granted 🤔

**Comment by Beamanator** [comment] 2024-10-18 10:43
Oh now I see it - if you select distance first, then go to the send invoice page, i do see the map 👍

**Comment by mkzie2** [comment] 2024-10-18 10:43
Reproducible steps:

1. FAB >> Submit expense >> Distance
2. Close the RHP
3. FAB >> Send invoice
4. Complete the invoice flow
5. In confirmation page, a map shows with default location (which is Expensify headquarter); missing Merchant and Date field

@Beamanator Can you try

**Comment by Beamanator** [comment] 2024-10-18 10:44
@mkzie2 as before, do you think you can help figure out the PR which caused this bug? I really appreciate the work you've been doing helping solve blockers recently 🙏

**Comment by mkzie2** [comment] 2024-10-18 10:46
This one https://github.com/Expensify/App/pull/51040. What a coincidence that we were working on it ytd 😄

**Comment by Beamanator** [comment] 2024-10-18 10:50
cc @bernhardoj & @rayane-djouah  as the author & C+ of https://github.com/Expensify/App/pull/51040 -

**Comment by Beamanator** [comment] 2024-10-18 10:54
BTW @mkzie2 you should get compensated for the fix, assuming we go with your fix 🙏 👍

**Comment by bernhardoj** [comment] 2024-10-18 11:28
PR is up

**Comment by dylanexpensify** [comment] 2024-10-18 13:02
Hey @sakluger! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by Beamanator** [comment] 2024-10-18 13:16
CPing soon

**Comment by bernhardoj** [comment] 2024-10-18 15:02
Fixed in staging.

https://github.com/user-attachments/assets/6351b033-2e2a-44f7-9c76-6e9310729cb9

**Comment by Beamanator** [comment] 2024-10-18 15:06
woohoo! thanks!

**Comment by Beamanator** [comment] 2024-10-20 14:59
@sakluger i believe we should pay out @mkzie2 for the solution & finding the offending PR, can you please confirm before we close this out?

**Comment by sakluger** [comment] 2024-10-25 22:23
Just to confirm, @rayane-djouah and @bernhardoj are being paid on https://github.com/Expensify/App/issues/50098, right?

**Comment by sakluger** [comment] 2024-10-25 22:27
Summarizing payment on this issue:

Contributor: @mkzie2 $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104597365

**Comment by bernhardoj** [comment] 2024-10-26 02:54
@sakluger yes

**Comment by sakluger** [comment] 2024-10-28 16:57
I sent an email to @mkzie2 to remind them to accept the Upwork payment.

**Comment by mkzie2** [comment] 2024-10-28 19:34
@sakluger Done 🙏

**Comment by sakluger** [comment] 2024-10-28 23:43
Thank you! We're all done here.

**Closed by sakluger** 2024-10-28 23:43 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
