### ISSUE TITLE
[$1000] [HOLD WAQ] Implement skin tone shade for composite emojis

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13818] opened 2022-12-23 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Choose emoji picker
2. Choose dark skin tone or shades or dark skin tone.

## Expected Result:
Proper skin tone should be applied to applicable emojis

## Actual Result:
Certain emojis marked in the pics are not having darker shade emojis

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="370" alt="Screenshot 2022-12-22 at 7 08 03 PM" src="https://user-images.githubusercontent.com/43996225/209339666-e1baa6b3-0dbc-4231-83de-35b6409fbe19.png">

<img width="515" alt="Screenshot 2022-12-22 at 7 07 36 PM" src="https://user-images.githubusercontent.com/43996225/209339668-d9b4ff0e-30bb-4710-9aa8-302bfe3925e5.png">

<img width="947" alt="Screenshot (137)" src="https://user-images.githubusercontent.com/43996225/209339695-fcb31a23-d112-480d-8e3a-d7771fd7ab25.png">

<img width="962" alt="Screenshot (136)" src="https://user-images.githubusercontent.com/43996225/209339696-9ed567ab-be26-4a3e-a3b8-45ed8d6257fa.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @abdulrahuman5196
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671716674530379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139150506f1d78e5c</li>
        <li>Upwork Job ID: 1612535055522168832</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2022-12-23 15:36
Make sure to follow the [Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1671716674530379) before triaging.

**Comment by sonialiap** [comment] 2022-12-30 14:57
Agreed, this is a new feature, not a bug.

**Comment by marcaaron** [comment] 2022-12-30 21:36
Going to just leave this as a back burner task for me to get to whenever we are ready to take it off HOLD. If I don't feel like working on it whenever the HOLD comes off then I will kick it to `External`.

**Comment by stitesExpensify** [comment] 2023-01-06 20:36
This can be off hold now IMO since we took all other WAQ emoji issues off hold

**Comment by abdulrahuman5196** [comment] 2023-01-09 19:58
I have already added proposal as part of the original bug report in slack - https://expensify.slack.com/archives/C049HHMV9SM/p1671716760354049?thread_ts=1671716674.530379&cid=C049HHMV9SM


<img width="1113" alt="Screenshot 2022-12-22 at 7 15 12 PM" src="https://user-images.githubusercontent.com/46707890/211396763-a6d3fd09-2f5d-483c-97b6-d95852fff815.png">

**Comment by getusha** [comment] 2023-01-09 20:04
Slack
<img width="457" alt="Screenshot 2023-01-09 at 12 03 07 PM" src="https://user-images.githubusercontent.com/75031127/211397524-46f24df3-0afe-40de-b19f-700a787b7ca1.png">

Reason
https://blog.emojipedia.org/why-there-arent-black-family-emojis/

The issue is there's no emoji set currently with this shade

**Comment by stitesExpensify** [comment] 2023-01-09 20:53
Ah, so you're saying there literally just isn't unicode for these emojis?

**Comment by getusha** [comment] 2023-01-09 21:02
@stitesExpensify Yes

**Comment by stitesExpensify** [comment] 2023-01-09 22:50
In that case we should just close this issue then. Thanks for the clarification!

**Comment by abdulrahuman5196** [comment] 2023-01-10 12:13
I have posted issue in 2 places, one is the family icon list and the other is the 'handshake' icon.

For handshake icon we can still fix.

Current behaviour
<img width="515" alt="209339668-d9b4ff0e-30bb-4710-9aa8-302bfe3925e5" src="https://user-images.githubusercontent.com/46707890/211547415-401ae1c5-1595-44d6-b8c9-99c8266777b3.png">



Working video for handshake with my code change
Code Diff
```diff
--- a/assets/emojis.js
+++ b/assets/emojis.js
@@ -2259,6 +2259,13 @@ const emojis = [
             'meeting',
             'shake',
         ],
+        types: [
+            '🤝🏿',
+            '🤝🏾',
+            '🤝🏽',
+            '🤝🏼',
+            '🤝🏻',
+        ],
     },
```


https://user-images.githubusercontent.com/46707890/211547063-deb80639-b025-48b7-b582-607bb14a7d9c.mov

**Comment by stitesExpensify** [comment] 2023-01-10 19:43
@abdulrahuman5196 is that the only remaining emoji that _should_ have options but doesn't?

**Comment by abdulrahuman5196** [comment] 2023-01-10 20:13
@stitesExpensify  yes

**Comment by stitesExpensify** [comment] 2023-01-10 23:50
@abdulrahuman5196 was an issue ever made from your slack posts regarding that emoji? If so let's use that one, if not I can create a new one

**Comment by abdulrahuman5196** [comment] 2023-01-11 03:17
@stitesExpensify No. Separate issue wasn't created. We can create a new one.

**Comment by abdulrahuman5196** [comment] 2023-01-12 08:19
Gentle Bump  @stitesExpensify

**Comment by stitesExpensify** [comment] 2023-01-13 21:45
@abdulrahuman5196 new issue is here https://github.com/Expensify/App/issues/14302

**Comment by abdulrahuman5196** [comment] 2023-01-13 21:50
Thank you @stitesExpensify . Posted the proposal on the new issue also as requested.

**Comment by mallenexpensify** [comment] 2023-02-03 00:06
@stitesExpensify @Santhosh-Sellavel 
My emoji skin color is updating, am I doing something _wrong_?
Vid - https://www.screencast.com/t/mPq0jDlVSfF 

Happening on web and desktop, both staging v1.2.64-0

**Comment by garrettmknight** [comment] 2023-02-03 11:38
@mallenexpensify I don't think this is the right issue - the only thing that got fixed here was the handshake emoji. Otherwise, the ✋ emoji isn't 'composite'. Mind posting in #expensify-bugs?

**Closed by garrettmknight** 2023-02-03 11:38 UTC
Labels: External, Engineering, Daily, NewFeature, Help Wanted, Overdue
