### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] IOS - Unable to send message after copying 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24147] opened 2023-08-04 03:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. send any message 
3. Copy message to clipboard 
4. paste and try to send 

## Expected Result:
User should be able to send a message 

## Actual Result:
User is unable to send a message

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [X] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/a1fcc3d8-4107-4eef-b429-ddbbed7f08ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178ff1caa2420bb2c</li>
        <li>Upwork Job ID: 1687566252792942592</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2023-08-04 07:12
Reproducible on physical iOS device

**Comment by lukemorawski** [comment] 2023-08-04 09:05
taking a look at this

**Comment by slafortune** [comment] 2023-08-04 20:48
Any update on this @lukemorawski ?

**Comment by kodcuserkan** [comment] 2023-08-04 22:19
Any updates here?

**Comment by eruqul1111** [comment] 2023-08-04 22:45
Hi

**Comment by pradeepmdk** [comment] 2023-08-04 23:26
### Proposal
Please re-state the problem that we are trying to solve in this issue.
IOS - Unable to send a message after copying

### What is the root cause of that problem?
This is a known issue with React Native's TextInput on set multiline, particularly on iOS. 

What changes do you think we should make in order to solve the problem?

we need to do a patch fix 
https://github.com/facebook/react-native/issues/37784
https://github.com/facebook/react-native/commit/0c9c57a9f73294414d92428c5d2472dc1e1e5e96

**Comment by advantiss425** [comment] 2023-08-05 03:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - Unable to send a message after copying.
### What is the root cause of that problem?
onChangeText callback function is called when the text input's text changes by only keyboard tapping in iOS.
### What changes do you think we should make in order to solve the problem?
Use onChange instead of onChangeText.

Happy weekend!

**Comment by kodcuserkan** [comment] 2023-08-05 06:59
Contributor details
Your Expensify account email: akmanserkan65@gmail.com 
Upwork Profile Link: https://www.upwork.com/workwith/serkanakman

**Comment by kodcuserkan** [comment] 2023-08-05 07:13
Contributor details
Your Expensify account email: akmanserkan65@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~01f1b1dcb71241f67c

**Comment by kodcuserkan** [comment] 2023-08-05 10:25
Hi

**Comment by rushatgabhane** [comment] 2023-08-05 18:29
I see proposals are saying that the RCA is a react-native bug. 

If so, can we please find an existing react native issue (or create if it doesn't exist).
And post a proposal to fix the issue in react-native

**Comment by pradeepmdk** [comment] 2023-08-06 01:08
@rushatgabhane I already updated in my proposal https://github.com/Expensify/App/issues/24147#issuecomment-1666270497

**Comment by rushatgabhane** [comment] 2023-08-06 02:53
> we need do a patch fix

we don't do that. we need to fix the issue upstream

**Comment by pradeepmdk** [comment] 2023-08-06 03:47
@rushatgabhane then we need to update our react-native version.  because this issue has already been fixed in the  0.72.2
https://github.com/facebook/react-native/blob/v0.72.2/packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m?#L257

**Comment by rushatgabhane** [comment] 2023-08-06 05:04
Awesome! We're on `v0.72.1`
@roryabraham is there work being done to upgrade to `v0.72.2`

**Comment by bojjakaseenadhreddy** [comment] 2023-08-06 09:34
Contributor details
Your Expensify account email: kaseenadh111@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0152eb4cd0298bbbd4

**Comment by LambdaLarkk** [comment] 2023-08-06 21:57
I would like to work on this

**Comment by MonilBhavsar** [comment] 2023-08-07 06:35
Discussing the next steps here https://expensify.slack.com/archives/C07J32337/p1691136923784939

**Comment by pradeepmdk** [comment] 2023-08-07 06:38
> Discussing the next steps here https://expensify.slack.com/archives/C07J32337/p1691136923784939

@MonilBhavsar i am not able to open this link

**Comment by MonilBhavsar** [comment] 2023-08-07 07:41
> we don't do that. we need to fix the issue upstream

@rushatgabhane we think we should patch the rn fix as it created multiple blockers, and can update the version later on. Any specific reason why we should not do that.

**Comment by mananjadhav** [comment] 2023-08-07 07:52
I also think we should do a patch and close it. We might not have deploy blocker but upgrading RN version will be time consuming.

**Comment by mananjadhav** [comment] 2023-08-07 10:15
Thanks for the PR @pradeepmdk. I am still waiting for @MonilBhavsar to officially assign the issue to you. Will then review the PR.

**Comment by pradeepmdk** [comment] 2023-08-07 10:18
@mananjadhav Thank you.  Based on slack conversion I am creating this PR
https://expensify.slack.com/archives/C01GTK53T8Q/p1691377395570339

**Comment by mananjadhav** [comment] 2023-08-07 10:23
Thanks, just went through the conv.

**Comment by MonilBhavsar** [comment] 2023-08-07 12:10
Requested CP https://expensify.slack.com/archives/C07J32337/p1691410125205379

**Comment by pradeepmdk** [comment] 2023-08-07 12:17
can I get the contract to my Upwork ID.

**Comment by Beamanator** [comment] 2023-08-07 14:26
PR in staging, @MonilBhavsar confirmed it's working! No longer a blocker 👍

**Comment by pradeepmdk** [comment] 2023-08-07 19:39
> 📣 @pradeepmdk You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~0178ff1caa2420bb2c) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

I applied the job in upwork.

**Comment by mananjadhav** [comment] 2023-08-10 13:41
@slafortune Can you please help with hiring @pradeepmdk on Upwork?

**Comment by pradeepmdk** [comment] 2023-08-15 20:00
@slafortune any update for me

**Comment by mananjadhav** [comment] 2023-08-16 04:59
This was more of a bug due to RN dependency, but I think could've got through this when upgrading the RN version? Considering this was deploy blocker, we did catch this in QA, and hence I feel we don't need any regression tests here.

@slafortune Can you please add the payment summary here? and also hire @pradeepmdk on Upwork?

**Comment by slafortune** [comment] 2023-08-16 15:13
External issue reporter - applause, no payment needed
 Contributor that fixed the issue - @pradeepmdk, $1500
 Contributor+ that helped on the issue and/or PR - @mananjadhav $1500

🎉  Speed bonus given - @pradeepmdk got assigned: 2023-08-07 12:02:14 Z / when the PR got merged: 2023-08-07 12:03:47 UTC

**Comment by mananjadhav** [comment] 2023-08-16 15:44
@pradeepmdk Offer is sent out for $1000 for the contract amount, and $500 will be paid out as the bonus during the payout.

**Comment by slafortune** [comment] 2023-08-16 16:01
Thanks! Yes, I'll leave it open - just wanted to verify you had requested that 👍

**Comment by JmillsExpensify** [comment] 2023-08-17 02:38
Reviewed the details for @mananjadhav. This is approved for payment in NewDot based on the BZ summary above.

**Comment by mananjadhav** [comment] 2023-08-22 13:58
Can we close this? @slafortune

**Closed** 2023-08-22 21:08 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
