### ISSUE TITLE
Android - Room - Unexpected quantity of letters when inputting room name in capital letters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13463] opened 2022-12-09 00:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Android app and login
2. Create a room
3. Got to room setting to change it's name
4. Select "Capital letter only" mode and input a new name

## Expected Result:
Name should be correctly input

## Actual Result:
Unexpected quantity of letters when inputting room name in capital letters

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.37.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/206597527-3f4a03fb-c5ef-4840-ae7c-eff64e45693b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2022-12-10 17:07
The issue is on RN.
https://github.com/facebook/react-native/issues/27449

There is a posted workaround and a possible PR that may fix it but it's still a draft.

Given that room feature is still in beta, perhaps we should do nothing for now.

**Comment by sketchydroide** [comment] 2022-12-12 09:37
I think s77rt might be right, also this is an old bug on RN (2019), not sure why they have not tried to fix it yet

**Comment by sketchydroide** [comment] 2022-12-12 17:04
I wonder if someone with an android test what happens in Android Whatsapp?

**Comment by sketchydroide** [comment] 2022-12-13 15:51
Asked @Julesssss for some help to test here, and in Whatsapp this does not happen, therefor I think we should keep this open, and try to see if there is a fix for it.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-14 03:30
`Proposal`

As it is known bug in React Native for android and there is no actual fix for it at the moment. We can use a workaround  to fix the problem by `keyboardType={"visible-password"}`  and by turning `autoCorrect={none}` in index.android.js.

               <TextInput
                ref={this.props.forwardedRef}
                disabled={this.props.disabled}
                label={this.props.translate('newRoomPage.roomName')}
                prefixCharacter={CONST.POLICY.ROOM_PREFIX}
                placeholder={this.props.translate('newRoomPage.social')}
                onChange={this.setModifiedRoomName}
                value={this.props.value.substring(1)} // Since the room name always starts with a prefix, we omit the first character to avoid displaying it twice.
                errorText={this.props.errorText}
                autoCapitalize="none"
                maxLength={CONST.REPORT.MAX_ROOM_NAME_LENGTH}
                autoCorrect={none}
                keyboardType={"visible-password"}
            />

`After Fix` 

https://user-images.githubusercontent.com/81307212/207496591-319cda56-8b53-4e54-ae3e-04aa2d1bb265.mp4

@sketchydroide Is there any reason we are restricting user from using capital letters in Room Name ? As on WhatsApp for instance for Group Name they don't restrict user from entering capital letters that's why this doesn't happen there we are forcing room name to be lowercase.

`Whatsapp for reference :-`

https://user-images.githubusercontent.com/81307212/207497924-12105c71-13a1-43a1-a53e-68744dde601e.mp4

**Comment by sketchydroide** [comment] 2022-12-14 12:46
I think the idea was to do something like slack does, and to not allow capital letter in the room/channel name.

**Comment by sketchydroide** [comment] 2022-12-14 13:04
I think I understand the underlying issue here, because there is a feedback loop using the onChange to reset the text as lowercase. I think this creates an issue where it's trying to set the new text on top of the old one and creates copies.
No idea if we can fix this localy like it was mentioned here before.
But I think we should at least remove the `autoCapitalize="none"`, as it's not doing anything we are doing the calitalization with code anyway.

**Comment by s77rt** [comment] 2022-12-14 13:17
@sketchydroide What about the use of style `textTransform: 'uppercase'`? Won't this also recreate the bug? (not tested)
I think we should find out why using `keyboardType="visible-password"` works

**Comment by s77rt** [comment] 2022-12-14 13:30
@sketchydroide I'm aware of that and I appreciate your concern

**Comment by sketchydroide** [comment] 2022-12-15 12:31
keyboardType="visible-password" seems to work for this case, so building a PR for this, I'm also removing autoCapitalize="none" as I feel it's confusing, as it does nothing, the onChange does.

**Comment by sketchydroide** [comment] 2022-12-16 11:08
G has been Merged, we can start the payment for the C+ @johncschuster 🙇🏼

**Comment by sketchydroide** [comment] 2022-12-19 16:15
no update, waiting on payment still I think

**Comment by sketchydroide** [comment] 2022-12-27 10:45
This fix is now in prod, the only thing missing is payments.
@johncschuster not sure if you are arounf to help with that :)

**Comment by sketchydroide** [comment] 2022-12-29 12:15
bump @johncschuster seems OOO will probably wait for next week

**Comment by sketchydroide** [comment] 2023-01-02 10:44
John still OOO today, maybe tomorrow

**Comment by sketchydroide** [comment] 2023-01-05 11:29
@johncschuster bump

**Comment by sketchydroide** [comment] 2023-01-05 11:30
change the title since it's awayting payment

**Comment by johncschuster** [comment] 2023-01-06 16:08
@sketchydroide thanks for the bumps! I'm finally getting caught up from being OOO. I'll get the payment issued in just a moment.

**Comment by johncschuster** [comment] 2023-01-06 16:18
@thesahindia can you apply for the Upwork job when you get the chance?

https://www.upwork.com/jobs/~012a221d0f9589cf03

**Comment by JmillsExpensify** [comment] 2023-01-06 19:50
Added the `reviewing` label so that this issue isn't our WAQ-focused list.

**Comment by johncschuster** [comment] 2023-01-06 21:02
@thesahindia, I've accepted your proposal in Upwork. Can you accept the offer? Once you've done that, I'll get the payment issued.

**Comment by thesahindia** [comment] 2023-01-06 21:05
@johncschuster accepted, thanks!

**Comment by johncschuster** [comment] 2023-01-06 21:07
Paid! 🎉

**Closed** 2023-01-09 10:44 UTC
Labels: Reviewing, Daily, Awaiting Payment, Bug
