### ISSUE TITLE
[$500] Lenguage - Device language preference doesn't take effect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34248] opened 2024-01-10 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Change the browser's language preference
2. Navigate to sign up page (https://staging.new.expensify.com/)

## Expected Result:
Site language should be changed to Spanish

## Actual Result:
Site language is English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c120a3f9-e070-4e02-a6dc-b1eabc9aa095

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a79bfd0a9d947de</li>
        <li>Upwork Job ID: 1745109608264826880</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2024-01-10 15:56
# Proposal

## Root cause
We are not using the `GetUserLanguage` method to fetch default language, we only use it for apple locale script.

## Solution
We should use the `GetUserLanguage` method

**Comment by shubham1206agra** [comment] 2024-01-10 16:10
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Language - Device language preference doesn't take effect

### What is the root cause of that problem?

This is happening as we are not listening to language changes in language in SignInPage.

### What changes do you think we should make in order to solve the problem?

We can use listener provided by `react-native-localize`

POC:

```js
RNLocalize.addEventListener('change', () => {
    App.setLocale(getDevicePreferredLocale());
});
```

### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment] 2024-01-10 17:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Language - Device language preference doesn't take effect


### What is the root cause of that problem?
Currently we are always getting `preferredLocale` from Onyx, even though the preferred language is changed, `preferredLocale` has already been set and has a value so it will not update `preferredLocale` in Onyx 
https://github.com/Expensify/App/blob/f15ed75b0b4133a8c02617d20a09e29d72825a4d/src/pages/signin/SignInPage.js#L159-L164
### What changes do you think we should make in order to solve the problem?
In my opinion, when we need to distinguish between prioritizing the language taken from the device or prioritizing the language that the user has previously set.

For example: When initially opening the page, the machine language is `en`, then `preferredLocale` is also `en`. Then if the user changes the device language to `es`, `preferredLocale` will update accordingly. But in case the user has actively changed the language, we should prioritize keeping the user's chosen language instead of updating according to the device language.

So we can add an `IntendSetLocate` key in Onyx to determine where the preferred language will come from when loading this page: 
```js
   IntendSetLocate: {
        key: ONYXKEYS.INTEND_SET_LOCATE
    }
```
At the `setLocale` function, we add an `intend` variable with the default value true, to determine whether this function is called by default or by user action to update `INTEND_SET_LOCATE`. 
```js
    if (intend) {
        Onyx.merge(ONYXKEYS.DEFAULT_LOCALE, true);
    }
```

Here we will check to see if it was an intentional set from the previous user and will skip updating the `preferredLocale` [ [here(https://github.com/Expensify/App/blob/f15ed75b0b4133a8c02617d20a09e29d72825a4d/src/pages/signin/SignInPage.js#L159C1-L165C1)
```js
    useEffect(() => {
        if (preferredLocale && intendSetLocate) {
            return;
        }
        App.setLocale(Localize.getDevicePreferredLocale(), false);
    }, [preferredLocale, intendSetLocate]);
```

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2024-01-10 18:07
Updated proposal.

Added alternative solution.

**Comment by sakluger** [comment] 2024-01-11 19:42
I don't think we supposed this feature, and if that's the case, then it's not a bug. I've asked in Slack for confirmation.

**Comment by sakluger** [comment] 2024-01-12 00:29
Confirmed that this was never a feature we built, so this is a feature request as opposed to a bug. Closing for now.

**Closed by sakluger** 2024-01-12 00:29 UTC
Labels: External, Daily, Help Wanted, Bug
