### ISSUE TITLE
[HOLD #21518][$1000] Web - Blank Pages Displayed After Splitting Bill and Returning from Concierge Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23895] opened 2023-07-30 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign, select "Split Bill", add the desired number, click "Next", choose email, and click "Split Bill".
2. The split money appears in the composer. Click on the money.
3. Click on the three dots in the top left corner, then select "Delete" The app redirects you to the Concierge page.
4. Go back, and observe that a blank page is displayed.

## Expected Result:
The app should not show blank pages after returning from the Concierge page following a split bill.

## Actual Result:
After returning from Concierge following a split bill, the app displays blank pages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/579295f0-23ef-4a90-8a18-e226adcf5a3d

https://github.com/Expensify/App/assets/93399543/ca75e456-f3f5-4a67-ac49-2d4c25b28ab5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690622954068189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5608dd0a0136fdb</li>
        <li>Upwork Job ID: 1689058798459588608</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26076517</li>
<li>tewodrosGirmaA | Reporter | 26076519</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-31 05:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Blank page displayed when splitting bill, deleting the money request, and going back

### What is the root cause of that problem?

When deleting a money request, we call `DeleteMoneyRequest` API call and navigate to the iou or chat report here
https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/libs/actions/IOU.js#L965-L977

In the case `shouldDeleteIOUReport` is true, we only go back once and navigate to chat report.
But if we create split bill and go to the transaction report, the navigation looks like
```
    chat report -> iou report -> money request report
```
Now that we go back and navigate to chat report, the current navigation stack would look like
```
    chat report -> iou report -> chat report
```

If we go back, navigation would go to iou report, but this was already deleted and empty page appears
This is the root cause

### What changes do you think we should make in order to solve the problem?

In the case `shouldDeleteIOUReport` is true, we have to go back to the `chat report` and navigate
In order to do this, create an utility function `getReportIdInStack(depth = 0)` in [Navigation.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/Navigation.js)

```
const getReportIdInStack = (depth = 0) => {
    const state = navigationRef.getState();
    console.log(state.routes);
    let reportCount = 0;
    for (let i = state.routes.length - 1; i >= 0; i --) {
        const route = state.routes[i];
        if (route.name === 'CentralPaneNavigator') {
            if (depth === reportCount) {
                return route.params.params.reportID;
            }
            reportCount ++;
        } else {
            return '';
        }
    }

    return '';
}
```

And go back twice if we need to go back once more in `deleteMoneyRequest` function
```
    if (shouldDeleteIOUReport) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        const previousReportId = Navigation.getReportIdInStack(1);
        Navigation.goBack();
        if (previousReportId === reportAction.originalMessage.IOUReportID.toString()) {
            Navigation.goBack();
        }
        Navigation.navigate(ROUTES.getReportRoute(iouReport.chatReportID));
    }
```

This works perfect

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-08-01 21:47
I'll test soon

**Comment by alexpensify** [comment] 2023-08-04 00:01
@allroundexperts - can I get your feedback here? https://github.com/Expensify/App/issues/22964 is about when you click into the IOU. Will the fix for that one address the Delete button which also appears to be taking you to the Concierge chat? Thanks for checking if the upcoming fix address this one too.

**Comment by alexpensify** [comment] 2023-08-05 00:12
Got it, thank you for confirming this isn't a duplicate! I'll test to confirm if I get the blank page then.

**Comment by alexpensify** [comment] 2023-08-06 17:03
Still on my test list

**Comment by alexpensify** [comment] 2023-08-08 23:46
I was able to replicate it, and I marked it as `External`. I did notice a JS snippet in the process. 

![image](https://github.com/Expensify/App/assets/8107070/c22a8662-d411-4ca9-9f13-3de34968ce5f)

**Comment by alexpensify** [comment] 2023-08-10 16:58
@mananjadhav - when you get a chance, can you please review the recent proposal? Thanks!

**Comment by mananjadhav** [comment] 2023-08-11 12:49
Thanks for the bump @alexpensify. @tienifr's proposal looks good to me.

I think setting optimistic data is a better design, but I will let internal engineer confirm if we want to take `Navigation` approach.

🎀 👀 🎀 C+ reviewed.

**Comment by deetergp** [comment] 2023-08-11 21:12
If that's what we are already doing with reportAction, let's go ahead and do the same with IOUs. @tienifr's solution looks good to me too.

**Comment by deetergp** [comment] 2023-08-15 23:48
Sorry, @tienifr I agreed with you yesterday — in my head — where it does you absolutely no good. 😅 I'll put a hold on this one till #21518 is merged.

**Comment by alexpensify** [comment] 2023-08-21 18:01
Weekly Update: Still on hold for https://github.com/Expensify/App/issues/21518

**Comment by alexpensify** [comment] 2023-08-23 17:57
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-08-28 23:07
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-08-28 23:07
Also, moving this to a weekly.

**Comment by alexpensify** [comment] 2023-08-30 21:29
Weekly Update: On Hold

**Comment by alexpensify** [comment] 2023-09-06 22:12
Weekly update: Should be in production soon.

**Comment by alexpensify** [comment] 2023-09-12 22:33
Weekly Update: some conflicts are being reviewed

**Comment by alexpensify** [comment] 2023-09-20 04:52
Weekly Update: still waiting for a conflict update

**Comment by alexpensify** [comment] 2023-09-26 09:10
Weekly Update: By next week, we should be clear to move forward here!

**Comment by alexpensify** [comment] 2023-10-03 23:25
@tienifr and @mananjadhav - can one of y'all test to identify if this is still an issue? The other PR was just moved to payment stages, so all clear here.

**Comment by alexpensify** [comment] 2023-10-04 22:26
Ok with this news, I'm going to close it out.

**Comment by alexpensify** [comment] 2023-10-04 22:26
Thank you!

**Closed by alexpensify** 2023-10-04 22:26 UTC
Labels: External, Weekly, Bug

**Comment by mananjadhav** [comment] 2023-10-06 17:30
Agreed with @tienifr here. Bump @alexpensify @deetergp.

**Comment by alexpensify** [comment] 2023-10-06 17:50
There have been a few updates to the partial payment process. I need to ask a few questions and would like your opinions - @tienifr and @mananjadhav :

1. What compensation do you think is the percent due here for the work input here - 0, 25, 50, OR 100%?
2. Reasoning why has been shared https://github.com/Expensify/App/issues/23895#issuecomment-1751144412 

Thanks!

**Comment by alexpensify** [comment] 2023-10-18 00:27
@mananjadhav we need your feedback here, please reply with the percent. Thanks!

**Comment by mananjadhav** [comment] 2023-10-30 11:30
Thanks for the tag @tienifr. I missed this because the issue was closed. Based on the linked discussions I also feel it should be 100%.

**Comment by alexpensify** [comment] 2023-10-30 22:43
Thanks, I will work on the process this week.

**Comment by alexpensify** [comment] 2023-11-03 15:58
Here is the payment summary: 

-  External issue reporter @tewodrosGirmaA $250 
-  Contributor that fixed the issue @tienifr $1000
-  Contributor+ that helped on the issue and/or PR @mananjadhav $1000

Upwork Job: https://www.upwork.com/jobs/~01c5608dd0a0136fdb

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is no urgency bonus. Payments have been sent out to those who receive payments there.

**Comment by JmillsExpensify** [comment] 2023-11-03 21:29
$1,000 payment approved for @mananjadhav based on comment above.
