### ISSUE TITLE
[HOLD for payment 2023-12-11] [$500] Workspace - When going to "Announcement" room on Specific account, app crashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30381] opened 2023-10-25 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the New expensify app or access staging.new.expensify.com
2. Sign into this specific account [emilio.utest@gmail.com](mailto:emilio.utest@gmail.com)

3. Click on Profile > Workspace > Click any workspace
4. Click on the 3 dot menu in the top right > Go to #announce room

## Expected Result:
User expects to go to the Announce room with no issues (The admin room redirect works fine)

## Actual Result:
The app crashes every time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

  

https://github.com/Expensify/App/assets/78819774/d343244d-995f-41e1-bb85-678c0e9a6bbc

[logs.txt](https://github.com/Expensify/App/files/13169678/logs.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca71bfccfd7e64d4</li>
        <li>Upwork Job ID: 1717256298451300352</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>sourcecodedeveloper | Contributor | 27547013</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by alitoshmatov** [comment] 2023-10-25 20:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

<img width="655" alt="Screenshot 2023-10-26 at 01 25 12" src="https://github.com/Expensify/App/assets/59907218/09094d66-fb29-4e58-a820-79fdff29b1ad">

Based on the logs I am assuming `#announce` room is not found in the following lines:
https://github.com/Expensify/App/blob/8fdbc4e4428567316e8906b1b3d958a9ab80be05/src/pages/workspace/WorkspaceInitialPage.js#L118-L119

Since I cannot access this account I don't know why exactly `#announce` room is not found

### What changes do you think we should make in order to solve the problem?
Considering this is an edge case, I would suggest applying some checks so that we will navigate to the room only if it exists:
```       
            if(room){
                Navigation.dismissModal(room.reportID);
            }
``` 


### What alternative solutions did you explore? (Optional)
We can also try to identify why the announce room is absent, but it requires access to the exact account

**Comment by pradeepmdk** [comment] 2023-10-26 00:50
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

When going to "Announcement" room on Specific account, app crashes
### What is the root cause of that problem?
[logs.txt](https://github.com/Expensify/App/files/13171854/logs.txt)

i am not able to reproduce in my account so problem is `room` is undefined.
https://github.com/Expensify/App/blob/6c220e6a3da6de3bd5cf3dec342d623fa9b187c7/src/pages/workspace/WorkspaceInitialPage.js#L120-L126

### What changes do you think we should make in order to solve the problem?

we should update like this 
```javascript
const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type && !ReportUtils.isThread(report)) || {};
```

**Comment by sourcecodedeveloper** [comment] 2023-10-26 22:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app is unable to navigate to workspace rooms. User is shown the rooms but upon navigation the app crashes.

### What is the root cause of that problem?
Report data is not being loaded properly upon signing in and upon navigating to either the announce or admin room the app crashs.

The const threeDotsMenuItems is hardcoded
https://github.com/Expensify/App/blob/546f27e2d0dfdad89c6f3be107f753dad8439462/src/pages/workspace/WorkspaceInitialPage.js#L182
The expectation is that the announce room and the admin room do have reportIds but the expectation fails when the callback goToRooms is invoked.


### What changes do you think we should make in order to solve the problem?
Instead of adding null check for room in the goToRooms callback, the rooms having undefined reportIds can be excluded from the const threeDotsMenuItems.

```
const availableRooms = _.filter(props.reports, (report) => (report && report.reportID != undefined && report.policyID === policy.id && (report.chatType === CONST.REPORT.CHAT_TYPE.POLICY_ADMINS || report.chatType === CONST.REPORT.CHAT_TYPE.POLICY_ANNOUNCE)));

let threeDotsMenuItems = [
    {
        icon: Expensicons.Trashcan,
        text: props.translate('workspace.common.delete'),            
        onSelected: () => setIsDeleteModalOpen(true),
    },
];
availableRooms.forEach(room => {
    threeDotsMenuItems.push({
        icon: Expensicons.Hashtag,
        text: props.translate('workspace.common.goToRoom', {roomName: room.chatType === CONST.REPORT.CHAT_TYPE.POLICY_ADMINS ? CONST.REPORT.WORKSPACE_CHAT_ROOMS.ADMINS : CONST.REPORT.WORKSPACE_CHAT_ROOMS.ANNOUNCE}),
        onSelected: () => goToRoom(room.chatType),
    });
});

```
Video attached

[video](https://github.com/Expensify/App/assets/141340971/3a7be1aa-de0e-4f06-886c-c5d961da9211)

**Comment by sourcecodedeveloper** [comment] 2023-10-30 08:56
@allroundexperts Thanks for accepting the proposal.

**Comment by sourcecodedeveloper** [comment] 2023-10-30 09:40
@allroundexperts you may need to add or remove labels to generate an offer link (https://github.com/Expensify/App/issues/26530#issuecomment-1766799121)

**Comment by sourcecodedeveloper** [comment] 2023-11-01 12:14
@allroundexperts [PR](https://github.com/Expensify/App/pull/30678) is ready for review.

**Comment by sourcecodedeveloper** [comment] 2023-11-01 12:26
@allroundexperts waiting for go ahead.

**Comment by sourcecodedeveloper** [comment] 2023-11-06 08:01
@marcochavezf must have been swamped, please take some time and finish assigning the issue.

**Comment by marcochavezf** [comment] 2023-11-06 20:06
Hi guys, thanks for the patience here, I agree with @allroundexperts, assigning @sourcecodedeveloper 🚀

**Comment by sourcecodedeveloper** [comment] 2023-11-06 20:24
@marcochavezf thanks

**Comment by sourcecodedeveloper** [comment] 2023-12-11 14:15
@mountiny @allroundexperts The issue has been deployed to production since last month but the automation did not assign someone to release payment. Please review.

**Comment by anmurali** [comment] 2023-12-14 17:45
[The offer](https://www.upwork.com/nx/wm/offer/27547013) to you says it's been paid. I am closing this. Pls reopen if you're not seeing the payment.

**Closed by anmurali** 2023-12-14 17:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by allroundexperts** [comment] 2023-12-19 11:23
## Checklist
1. https://github.com/Expensify/App/pull/19295
2. https://github.com/Expensify/App/pull/19295/files#r1431268485
3. A Slack discussion is not needed here since there isn't anything missing in the checklist which could have prevented this.
4. A regression test would be helpful here.

## Regression test
1. Throttle the network requests to 'Slow 3G'.
2. Login to any account
3. Click on Profile > Workspace > Click any workspace.

While the chats are being loaded:
Click the three dot menu in the top and verify that the option to go to `announce` and `admin` do not appear.

After the chats are loaded:
Click the three dot menu in the top and verify that the option to go to `announce` and `admin` do appear and work fine.

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment] 2024-01-24 23:55
$500 payment to @allroundexperts based on comment above.
