### ISSUE TITLE
Composer - Email is not turned to a clickable link, and GitHub link is not parsed to number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36253] opened 2024-02-09 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause _ internal
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35837

## Action Performed:

Part 1 (Email):
1. Open a chat
2. Enter email address in composer ([test@gmail.com](mailto:test@gmail.com))
3. Hover over the email & try to click the link

Part 2 (GitHub):
1. Open a chat
2. Enter a GitHub link in the composer (https://github.com/Expensify/App/pull/34292)

## Expected Result:
* Email should turn to clickable malito link
* Github link should turn to number clickable link (#34292)

## Actual Result:
* Email doesn't turn to clickable malito link
* Github link doesn't turn to number clickable link (#34292)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dd02a12e-fd2f-478f-8e9e-54e352f38008

https://github.com/Expensify/App/assets/93399543/5a9c5663-0471-468c-b24c-077db5b512ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-09 15:49
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Skalakid** [comment] 2024-02-09 17:30
Hi, thanks for reporting a bug. Links inside live markdown text input shouldn't be clickable. Also links from GitHub shouldn't be shortened into numbers. We pasted wrong test cases into PR description, I will correct them

cc @tomekzaw

**Comment by dangrous** [comment] 2024-02-09 17:42
@Skalakid does that mean we can close this issue - i.e. not a bug?

Thanks!

**Closed** 2024-02-09 18:26 UTC
Labels: DeployBlockerCash, Engineering, Hourly
