### ISSUE TITLE
[$250] Chat - The system redirected to the Concierge chat after clicking on the "X" for closing error message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12638] opened 2022-11-10 15:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and login
2. Disable the internet connection in the device
3. Click on the green + button -> Click on the "New Chat" option
4. Create a new chat with an invalid phone number (5555555555555)
5. Verify the user is navigated to the conversation
6. Enable the internet connection and wait for a few seconds
7. Verify that a red dot appears next to the conversation in the LHN indicating something went wrong with the chat creation
8. Click on the X for closing error message

## Expected Result:
The system should be navigated you away from the conversation

## Actual Result:
The system redirected to the Concierge chat after clicking on the "X" for closing error message

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.26.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/201129647-b80cd265-089c-4c6e-baf7-cb08a35c2a32.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-11-10 16:57
<b>Proposal</b>
https://github.com/Expensify/App/blob/c2e4ab25a9b2b7d47004d7b323116f32c181a189/src/pages/home/report/ReportActionItemCreated.js#L46
Currently we always go to `Concierge` chat after press Close.
<b>Solution</b>
To navigate away from this conversation, we need to check the error then decide to go to Concierge or goBack in `ReportActionItemCreated.js`.
```diff
From eecbb5d9300b7d023c745e19d61970b405665ea1 Mon Sep 17 00:00:00 2001
From: Hans <visaocuoitroi193@gmail.com>
Date: Thu, 10 Nov 2022 23:55:51 +0700
Subject: [PATCH] add action close

---
 src/libs/actions/Report.js                       |  7 +++++++
 src/pages/home/report/ReportActionItemCreated.js | 16 ++++++++++++++--
 2 files changed, 21 insertions(+), 2 deletions(-)

diff --git a/src/libs/actions/Report.js b/src/libs/actions/Report.js
index ee240ac8c..f88ca9167 100644
--- a/src/libs/actions/Report.js
+++ b/src/libs/actions/Report.js
@@ -1313,6 +1313,12 @@ function navigateToConciergeChatAndDeleteReport(reportID) {
     Onyx.set(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, null);
 }
 
+function goBackAndDeleteReport(reportID) {
+    Navigation.goBack();
+    Onyx.set(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, null);
+    Onyx.set(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`, null);
+}
+
 /**
  * @param {Object} policyRoomReport
  * @param {Number} policyRoomReport.reportID
@@ -1555,4 +1561,5 @@ export {
     clearIOUError,
     getMaxSequenceNumber,
     subscribeToNewActionEvent,
+    goBackAndDeleteReport,
 };
diff --git a/src/pages/home/report/ReportActionItemCreated.js b/src/pages/home/report/ReportActionItemCreated.js
index e62bbb99e..1fdbc2b41 100644
--- a/src/pages/home/report/ReportActionItemCreated.js
+++ b/src/pages/home/report/ReportActionItemCreated.js
@@ -12,6 +12,7 @@ import styles from '../../../styles/styles';
 import OfflineWithFeedback from '../../../components/OfflineWithFeedback';
 import * as Report from '../../../libs/actions/Report';
 import reportPropTypes from '../../reportPropTypes';
+import Navigation from '../../../libs/Navigation/Navigation';
 
 const propTypes = {
     /** The id of the report */
@@ -38,12 +39,23 @@ const defaultProps = {
 const ReportActionItemCreated = (props) => {
     const isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(props.report);
     const icons = ReportUtils.getIcons(props.report, props.personalDetails, props.policies);
+    const error = lodashGet(props.report, 'errorFields.addWorkspaceRoom') || lodashGet(props.report, 'errorFields.createChat');
+
+    const onClose = () => {
+        if (error.includes('I couldn\'t validate the phone number')) {
+            Report.goBackAndDeleteReport(props.report.reportID);
+        } else {
+            Report.navigateToConciergeChatAndDeleteReport(
+                props.report.reportID,
+            );
+        }
+    };
     return (
         <OfflineWithFeedback
             pendingAction={lodashGet(props.report, 'pendingFields.addWorkspaceRoom') || lodashGet(props.report, 'pendingFields.createChat')}
-            errors={lodashGet(props.report, 'errorFields.addWorkspaceRoom') || lodashGet(props.report, 'errorFields.createChat')}
+            errors={error}
             errorRowStyles={styles.addWorkspaceRoomErrorRow}
-            onClose={() => Report.navigateToConciergeChatAndDeleteReport(props.report.reportID)}
+            onClose={onClose}
         >
             <View
                 accessibilityLabel="Chat welcome message"
-- 
2.31.0


```

**Comment by mananjadhav** [comment] 2022-11-21 04:20
@bondydaa @flaviadefaria I am not sure if that is a bug here? Because assume I am on the first chat on a fresh account then where do we redirect? What if I have two subsequent chats with errors in the offline mode? After I enable the internet, should I go back twice?

Can we please get some clarity on the expected behavior?

> The system should be navigated you away from the conversation

Navigate away from the conversion, but where? and let's specify for all scenarios.


@hungvu193 I'll review the proposal once I am aware what is the expected result.

**Comment by bondydaa** [comment] 2022-11-21 21:36
oh shoot Brandon is OOO this week. Going to gut check here with the rest of the team but this definitely seems more like a product change/feature request vs a bug since it's very clear why we're being redirected to the concierge chat: b/c it's coded that way.

**Comment by bondydaa** [comment] 2022-11-21 21:39
opened a thread here https://expensify.slack.com/archives/C01GTK53T8Q/p1669066748519699

**Comment by s77rt** [comment] 2022-11-22 10:07
in favour of closing.

**Comment by bondydaa** [comment] 2022-11-22 15:29
Got some feedback from @aldo-expensify and we both agree we can close this. We can change this later on if we want but for now this is the expected result.

@kbecciv can you make sure any test cases for this flow have something that states this is expected? maybe like "ensure after closing RBR you are directed to the concierge chat",

**Closed by bondydaa** 2022-11-22 15:29 UTC
Labels: External, Daily, Help Wanted, Bug
