### ISSUE TITLE
Web - Login - Blank page is displayed after log in with High traffic account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10216] opened 2022-08-02 21:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with HT (High Traffic) account

## Expected Result:
Chats are loaded without any issue

## Actual Result:
Blank page is displayed after log in

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.87-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** applausetester+ihchat4@applause.expensifail.com /Yulia1986Gerets

emilio.utest+304@gmail.com / Emilio98

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/182480027-82df42d2-0601-4791-81ef-821611620724.mp4

![Bug5673309_Screenshot_2022-08-03_004224](https://user-images.githubusercontent.com/43996225/182480046-3c861ad8-8905-4b1d-b2af-1ce4b90bb1d4.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment] 2022-08-03 10:06
@luacmartins can you take a look? Not sure if this can be external

**Comment by luacmartins** [comment] 2022-08-03 15:58
Yup, I'll investigate

**Comment by luacmartins** [comment] 2022-08-08 14:32
This is related to the performance issues we are having with high traffic accounts - https://github.com/Expensify/Expensify/issues/219425

The chats are loading fine, but it takes a while for the component tree to be rendered and the UI displayed. I'm gonna close this issue in favor of the one mentioned above since it has more context in it. We are also investigating this in #fireroom-08-03-22

**Comment by kbecciv** [comment] 2022-09-14 13:39
QA team have been experienced the same behavior for HT account with build 1.2.0.0 
Credentials used: applausetester+0901abb@applause.expensifail.com/Feya86Katya

https://user-images.githubusercontent.com/93399543/190169671-0295afdb-861f-473f-8326-98bb58b6169d.mp4

**Comment by luacmartins** [comment] 2022-09-14 18:24
I'll investigate this tomorrow

**Comment by luacmartins** [comment] 2022-09-19 14:21
I'll investigate this sometime this week

**Comment by luacmartins** [comment] 2022-09-20 15:41
@kavimuru can we add this to the weekly KIs?

**Comment by luacmartins** [comment] 2022-09-29 17:33
We might have more clues in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1664403290649159). cc @tgolen

**Comment by tgolen** [comment] 2022-09-29 20:11
I think [the change to Onyx.merge](https://github.com/Expensify/react-native-onyx/pull/186) is going to have a real impact on this, so I'm kind of waiting for that to be merged and rolled out before investigating further.

**Comment by luacmartins** [comment] 2022-10-11 17:36
Changes to Onyx.merge were merged and released on v1.0.19, but App is still on v.1.017. I put up a [PR](https://github.com/Expensify/App/pull/11723) to update onyx in App. We should try to reproduce this issue again once App is updated.

**Comment by luacmartins** [comment] 2022-10-19 23:43
Gonna try to reproduce this again since we updated Onyx to the latest version

**Comment by luacmartins** [comment] 2022-10-28 17:45
I've been focused on the Split Bill API refactor, so no updates yet.

**Comment by puneetlath** [comment] 2022-11-02 17:30
@luacmartins I removed and re-added the bug label to get a BZ team member added who can help move this forward.

**Comment by luacmartins** [comment] 2022-11-02 23:16
@JmillsExpensify I'll try to work on this in the next few days. 

FYI I'm going ooo from Nov 9 - Nov 22. I'm trying to wrap up the bigger issues I'm working on and switch to issues that I can finish before I go ooo.

**Comment by JmillsExpensify** [comment] 2022-11-03 04:28
Sounds like a plan for the time being!

**Comment by luacmartins** [comment] 2022-11-03 15:48
Actually, I just realized that this is a duplicate of https://github.com/Expensify/App/issues/11011. I'll close this issue in favor of the https://github.com/Expensify/App/issues/11011 since that one has more context in it. I'll try to investigate it as well.

**Closed by luacmartins** 2022-11-03 15:48 UTC
Labels: Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2022-11-03 18:25
Gotcha, we've found several duplicates today. Less is better, thanks!
