### ISSUE TITLE
[PAID] [$125] Report fields - List values field does not show the content in alphabetical order

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47039] opened 2024-08-08 08:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
This issue was found when executing this PR  https://github.com/Expensify/App/pull/46382
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields.
3. Click Add field.
4. Select List from Type.
5. Click List values.
6. Click Add value.
7. Add a few list values randomly.
8. Click back button.

## Expected Result:
List values field will show the content in alphabetical order.

## Actual Result:
List values field does not show the content in alphabetical order, which is not consistent with the list in List values page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b299c387-82fe-45f6-995b-35daa00b26f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164fa6c8455234523</li>
        <li>Upwork Job ID: 1821472046215029241</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103445958</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment] 2024-08-08 08:25
We think that this bug might be related to #wave-control

**Comment by BhuvaneshPatil** [comment] 2024-08-08 08:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - List values field does not show the content in alphabetical order

### What is the root cause of that problem?
We are directly showing list values in order we get from ONYX.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L75-L83


### What changes do you think we should make in order to solve the problem?
We shall add sort method on list values. We shall convert it to lowercase while comparing.
```ts
const finalVal = [].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))
```
or
```ts
const finalVal = [].sort(localCompare)
```


https://github.com/user-attachments/assets/c76a4873-cc34-4873-9953-b493a453b782


### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-08-08 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - List values field does not show the content in alphabetical order

### What is the root cause of that problem?
We are directly showing list values in order we get from ONYX.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L50


### What changes do you think we should make in order to solve the problem?
We shall add sort method on list values. We shall convert it to lowercase while comparing.
```ts
const listValues = Object.values(policy?.fieldList?.[reportFieldKey]?.values ?? {}).sort(localeCompare);
```


https://github.com/user-attachments/assets/c76a4873-cc34-4873-9953-b493a453b782


### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2024-08-08 09:04
@paultsimura is this a regression if the alphabetical sorting was added in that PR?

**Comment by BhuvaneshPatil** [comment] 2024-08-08 09:23
@paultsimura Here is what I think about excluding disabled values, when user clicks on the list values he is clicking with intent of getting list of all values (including disabled as well) but in case of selecting values, disabled values should not be shown

**Comment by Tony-MK** [comment] 2024-08-08 09:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report fields - List values field does not show the content in alphabetical order

### What is the root cause of that problem?

The root cause of the problem is that we are not sorting the list values according to the 

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L50

Unlike the `ReportFieldsListValuesPage` illustrated below, the report fields are ordered alphabetically.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L105

### What changes do you think we should make in order to solve the problem?


Let's sort `listValues` like below using `localeCompare`.

```
const listValues = Object.values(policy?.fieldList?.[reportFieldKey]?.values ?? {}).sort((a, b) => localeCompare(a, b));
```

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-08-08 10:22
@grgia I can take over the issue as I worked on the report fields project, feel free to reassign me

I think we should let @Krishna2323 and @shubham1206agra handle this as a follow up to our PR

**Comment by mountiny** [comment] 2024-08-08 10:24
This is an extra requirement so I would say $125 as an add on to the @Krishna2323 work

**Comment by grgia** [comment] 2024-08-09 17:39
Assigning @mountiny

**Comment by mountiny** [comment] 2024-08-10 05:22
@Krishna2323 What is your ETA for the PR you reckon

**Comment by strepanier03** [comment] 2024-08-27 19:42
Today is the 27th so payment isn't late, handling this as normal.

**Comment by strepanier03** [comment] 2024-08-27 19:53
### Payment summary

- $125 -  @Krishna2323 PAID via Upwork ([contract](https://www.upwork.com/nx/wm/workroom/38210588/overview?nav_dir=pop))
- $125 - @shubham1206agra via Upwork ([offer](https://www.upwork.com/nx/wm/offer/103708372))

**Comment by strepanier03** [comment] 2024-08-27 23:00
Offer sent to @shubham1206agra is pending still so I'll check again in the morning.

**Comment by strepanier03** [comment] 2024-08-28 19:16
Thanks @shubham1206agra - I have paid the contract and closed it.

**Closed by strepanier03** 2024-08-28 19:16 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
