### ISSUE TITLE
[$1000] Web -  Composer is hidden & RBR is displayed on LHN when navigating from oldDot to newDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22769] opened 2023-07-12 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging newDot app
2. Open an existing chat
3. Click on 'Actions' icon > click on 'Assign task' link > Add task title > click on 'next' button > click on Confirm task
4. Open staging oldDot app
5. Sign in with the same account that you have signed in on newDot app
6. Click on 'Chat icon' located on left, bottom corner

## Expected Result:
Composer shouldn't be hidden on the task report thread, and RBR shouldn't be displayed on the corresponding item on LHN

## Actual Result:
 Composer is hidden on the task report thread, and RBR is displayed on the corresponding item on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e30868cd-f8b6-46a8-8ca8-0923648d7364

https://github.com/Expensify/App/assets/93399543/5daa215c-3608-46a2-8725-57be6b4ea6be

https://github.com/Expensify/App/assets/93399543/f8f0c84d-ae94-415c-a059-82498d901dfc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689150445119939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcb9ab1940eaa3ea</li>
        <li>Upwork Job ID: 1679315597462216704</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-13 02:23
Repro'd:

https://github.com/Expensify/App/assets/59587260/56f14ee4-5859-4ad3-8cde-97282175382d

**Comment by snwork89** [comment] 2023-07-13 10:02
Which branch i should use to debug oldDot ?

**Comment by snwork89** [comment] 2023-07-14 06:00
i think when we're navigating to report screen from /inbox page it's creating issue,/inbox page is only available in oldDot.

**Comment by mwmsh** [comment] 2023-07-14 18:14
I could not reproduce this. It works fine for me on Chrome/MacOS.

**Comment by hannojg** [comment] 2023-07-17 06:15
Can you please try if the content starts appearing when you resize the browser the window?

**Comment by ShogunFire** [comment] 2023-07-18 00:52
I reproduce but I am not sure what this is doing or supposed to do, is old dot also on github ?

**Comment by kadiealexander** [comment] 2023-07-19 05:57
@ShogunFire olddot is www.expensify.com. The codebase is not publicly available.

@narefyev91 do you think the eventual solution will need to edit OldDot? If so we should make this internal.

**Comment by ShogunFire** [comment] 2023-07-19 06:00
It looks like it's either a modif on old dot or a modif in the backend so yes I think it's internal

**Comment by kadiealexander** [comment] 2023-07-19 06:02
Sorry @thesahindia, we already have a C+ assigned :)

**Comment by madmax330** [comment] 2023-07-24 06:26
Assigning @thienlnam since this is related to tasks

**Comment by thienlnam** [comment] 2023-07-24 21:52
Appears to be related to https://github.com/Expensify/App/issues/23444

**Comment by kadiealexander** [comment] 2023-07-25 03:14
@thienlnam could this be related to tasks accessed via a link? For #23444 it seems to happen when opening a link to a task, where this happens when we click through from OldDot.

**Comment by thienlnam** [comment] 2023-07-25 17:22
Turns out the are the same bug, and are caused by clicking from OldDot to newdot

**Comment by kadiealexander** [comment] 2023-07-26 05:09
@dukenv0307 I know you submitted a proposal on #23444, did you want to have another crack at a proposal for this?

**Comment by kadiealexander** [comment] 2023-07-26 05:18
@thienlnam do you think this needs to be an internal fix now that we know the root cause?

**Comment by thienlnam** [comment] 2023-07-26 18:09
I don't think we know what the root cause internally yet - someone internal will have to investigate to see what the issue is

**Comment by kadiealexander** [comment] 2023-07-31 03:26
Not overdue.

**Comment by thienlnam** [comment] 2023-08-04 00:35
Haven't had the time to look into it

**Comment by kadiealexander** [comment] 2023-08-14 01:38
@thienlnam any thoughts on this one?

**Comment by kadiealexander** [comment] 2023-08-31 06:41
@thienlnam any thoughts on this one?

**Comment by thienlnam** [comment] 2023-08-31 23:43
Ah sorry didn't have the chance to take a look last week. This week I'm busy with deliverables so going to prioritize those

**Comment by kadiealexander** [comment] 2023-09-12 05:33
Still low priority!

**Comment by kadiealexander** [comment] 2023-09-21 07:16
Not overdue.

**Comment by thienlnam** [comment] 2023-09-30 09:44
I'm going to close this - it's a low priority bug and involves going from OldDot to newDot so not a common flow at all. Feel free to re-open if you feel differently

**Closed by thienlnam** 2023-09-30 09:44 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
