### ISSUE TITLE
[HOLD for payment 2023-09-27] [$250] Migrate PressableWithSecondaryInteraction/index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16192] opened 2023-03-20 08:42 UTC
### Filenames
- [ ] [src/components/PressableWithSecondaryInteraction/index.js](https://github.com/Expensify/App/blob/main/src/components/PressableWithSecondaryInteraction/index.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153701f0a1ebdfe82</li>
        <li>Upwork Job ID: 1691869303041654784</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-06 10:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate index.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should refactor https://github.com/Expensify/App/blob/main/src/components/PressableWithSecondaryInteraction/index.js to be functional component

### What alternative solutions did you explore?

**Comment by olexyt** [comment] 2023-07-07 14:06
I can work on this issue.

**Comment by Vishrut19** [comment] 2023-07-10 20:38
Can I work on this?

**Comment by mkhutornyi** [comment] 2023-07-12 09:50
I'd like to work on this.

**Comment by BeeMargarida** [comment] 2023-08-14 14:54
Hi, I'm Ana from Callstack - expert contributor group - and I would like to take a look at this issue 👋

**Comment by marcaaron** [comment] 2023-08-16 17:48
Assigned.

**Comment by alexxxwork** [comment] 2023-08-16 17:48
Dibs

**Comment by studentofcoding** [comment] 2023-08-16 19:10
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Migrate index.native.js to the function component

## What changes do you think we should make in order to solve the problem?
The refactored code can be seen here @marcaaron

https://github.com/studentofcoding/Expensify-App/blob/733b4e2a3b5e29b50c0d23ef3dd52accc62adf19/src/components/PressableWithSecondaryInteraction/index.js#L1-L79

**Comment by Umesh-Bhati** [comment] 2023-09-05 15:50
can I work on this issue?

**Comment by Umesh-Bhati** [comment] 2023-09-05 15:52
Contributor details
Your Expensify account email: umeshbhati193@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by BeeMargarida** [comment] 2023-09-11 08:41
PR updated with main, ready for merge

**Comment by isabelastisser** [comment] 2023-09-27 18:39
I need clarification from the team here before I can process the payment, what's the amount that @0xmiroslav needs to be paid for the C+ review for this `newfeature` issue? @marcaaron 

The C+ was assigned on Aug 16 but the PR was merged on Sept 16 because of a [merge freeze](https://github.com/Expensify/App/pull/25398#issuecomment-1703355202). Do `newfeature` issues qualify for urgency bonus? Thanks!

**Comment by isabelastisser** [comment] 2023-09-27 18:59
@0xmiroslav what's your profile in Upwork?

**Closed** 2023-09-27 19:31 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment
