### ISSUE TITLE
[$250] IOU - "0" is not recognized as text in field.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10930] opened 2022-09-09 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Select any user
3. Tap in "+" icon and select Request payment,.
4. Insert any value in BNP then select any user available from list.
5. On the field "What's it for?" insert "0".
6. Tap "Request. 'value' " button

## Expected Result:
Zero should be identified as valid text in "What's it for?" field.

## Actual Result:
No "What's it for?" comment is displayed in the

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.99.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189413416-edf84791-a9c5-41ba-a1b5-61e5fcd8dec5.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2022-09-12 08:27
I was able to replicate it and started a conversation [here](https://expensify.slack.com/archives/C03TQ48KC/p1662970664620939) to make sure it's not intentional. I am currently looking into how we handle that input

**Comment by grgia** [comment] 2022-09-21 07:43
Haven't gotten to look at this

**Comment by grgia** [comment] 2022-10-05 15:42
Will triage today!

**Comment by Santhosh-Sellavel** [comment] 2022-10-06 17:14
@AndrewGable Seems this should be internal, as comment `0` has been sent without any issues but received messages missed out on that.

### Split with a comment as "0"
<img width="716" alt="Screenshot 2022-10-06 at 10 41 51 PM" src="https://user-images.githubusercontent.com/85645967/194376563-15957389-3824-4f72-b5df-134ae07a082a.png">

### Split with a comment as "1"
<img width="730" alt="Screenshot 2022-10-06 at 10 42 06 PM" src="https://user-images.githubusercontent.com/85645967/194376570-438c4856-0b25-4a93-9f81-06e0248357d1.png">

**Comment by pecanoro** [comment] 2022-10-07 20:26
The cause of this is probably the same one as this one https://github.com/Expensify/App/issues/11366

**Comment by pecanoro** [comment] 2022-10-07 20:48
Same cause but a different place, I know where the bug is so I am going to assign myself to fix it since the problem is Web again.

**Comment by pecanoro** [comment] 2022-10-07 20:50
Removing everyone since I will fix it internally.

**Comment by pecanoro** [comment] 2022-10-21 14:56
This has already been fixed, so closing!

**Closed by pecanoro** 2022-10-21 14:56 UTC
Labels: Reviewing, Engineering, Daily, Improvement, Bug
