### ISSUE TITLE
[HybridApp] Open New Expensify `/travel` when clicking on the HybridApp `Trips` tab

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#47734] opened 2024-08-20 17:37 UTC
## Problem

We have a temporary fix in place for the new Travel feature but it has some limitations:

<img src='https://github.com/user-attachments/assets/de33fa7f-cf56-4302-8c40-842507eb0058' width='250' />

## Solution

1. When a user clicks on `Travel` tab, redirect the user to New Expensify `/travel` via the `navigateToNewDot` function
    1. If the user was using Expensify Classic, we should not set their `tryNewDot.classicRedirect` NVP
3. When a user clicks on `Book Travel` in New Expensify we should open the browser as we do today, but we should take them back to Expensify Classic in the background.

The intention here is to not take the user back to New Expensify once they return back to the Expensify app.
 

<details><summary>Issue Owner</summary>Current Issue Owner: @mateuuszzzzz</details>

**Comment by AndrewGable** [comment] 2024-08-20 19:31
cc @mateuuszzzzz @staszekscp @war-in - Here is a polish issue that can be worked on once we finish all other release items

**Comment by twisterdotcom** [comment] 2024-09-10 22:15
Same as above. Will downgrade to `Monthly` for now.

**Comment by twisterdotcom** [comment] 2024-09-19 23:06
Wow, I thought I had made this Monthly.

**Comment by AndrewGable** [comment] 2024-09-20 15:23
Bumping @mateuuszzzzz @staszekscp @war-in to see if anyone wants this one!

**Comment by mateuuszzzzz** [comment] 2024-09-23 09:45
Hi! I'm gonna handle that one 👍

**Comment by mateuuszzzzz** [comment] 2024-09-23 14:38
I prepared PRs they're in draft mode. I need to test Android tomorrow and then I should be able to move it to "ready for a review"

**Comment by mateuuszzzzz** [comment] 2024-09-26 12:49
Hi,  have and update. I would like to postpone this PR until we unify the process for booting React Native on both platforms. Currently, on iOS, the app boots on startup, which leads to platform-specific implementations to ensure compatibility on iOS. This issue also affects the current PR.

**Comment by AndrewGable** [comment] 2024-09-26 15:21
Sounds good!

**Comment by mateuuszzzzz** [comment] 2024-09-27 13:53
We managed to change how we boot RN on iOS and it works without any crashes 🎉 I presume I will continue work on this issue on Monday/Tuesday

**Comment by mateuuszzzzz** [comment] 2024-10-02 15:13
I managed to fix all remaining issues in the [blocking PR](https://github.com/Expensify/Mobile-Expensify/pull/13159/files#diff-6620577a26ed205881aa3230d3b8b304efa02928a9a412ad799fb627e54e4978). I will continue work on Travel PR on Thursday 👍

**Comment by AndrewGable** [comment] 2024-10-21 17:27
We reverted these PRs due to the linked deploy blockers, let's make sure to address them before trying to merge this again. Thanks!

**Comment by AndrewGable** [comment] 2024-10-21 19:52
Also one thing I noticed, on the OldApp side of things we never renamed **Trips** to **Travel**, it'd be great to do that in this next round of PRs.

**Comment by twisterdotcom** [comment] 2024-10-22 09:12
Payment Summary:

- @mateuuszzzzz **does not** require payment (Contractor)

**Comment by AndrewGable** [comment] 2024-10-22 18:07
https://github.com/Expensify/App/issues/47734#issuecomment-2427314920

**Comment by mateuuszzzzz** [comment] 2024-10-28 12:42
Hi! I have an update

I prepared two PRs that should also fixes previous issues.

[OldDot](https://github.com/Expensify/Mobile-Expensify/pull/13245), [NewDot](https://github.com/Expensify/App/pull/51327)

**Comment by twisterdotcom** [comment] 2024-10-30 10:13
Looks like we're just waiting for these two PRs right? Don't wanna close this yet.

**Comment by trjExpensify** [comment] 2024-11-01 14:13
Confirmed with Brandon [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1730248951538589?thread_ts=1730220361.804309&cid=C05S5EV2JTX) that this is the expectation on the OldApp side: 

- When not on the `spotnanaTravel` beta: Clicking the Travel tab on OldApp doesn’t redirect to NewDot, it opens the OldApp Trips page.
- When on the `spotnanaTravel` beta: Clicking the Travel tab redirects to NewDot’s book travel flow.

**Comment by mateuuszzzzz** [comment] 2024-11-04 14:53
Hi, I had to take a day off due to a cold I’ll continue working on the PR tomorrow

**Comment by trjExpensify** [comment] 2024-11-05 14:43
Wahoo, and glad you're feeling better! Is it ready for a re-review?

**Closed** 2024-11-05 21:43 UTC
Labels: Reviewing, Daily, NewFeature

**Comment by situchan** [comment] 2025-10-01 10:46
C+ Payment is remaining. @twisterdotcom can you please reopen and move to `Daily`? Thanks
