### ISSUE TITLE
[HOLD for payment 2024-07-22] [$250] Search - "Scanning" appears in Description field when expense is scanning

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44596] opened 2024-06-28 09:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/44190
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Account has no expenses (or has expenses with no merchant).

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a scan expense.
4. While the expense is scanning, go to Search.

## Expected Result:
"Scanning" will not appear in Description field because "Scanning" is not in Description field in transaction thread.

## Actual Result:
"Scanning" appears in Description field when "Scanning" is not in Description field in transaction thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/47f64d27-fb12-4337-90e8-d77511cb2764

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed996315e0843cef</li>
        <li>Upwork Job ID: 1815474885633659701</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment] 2024-06-28 09:01
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-28 09:01
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-06-28 09:01
Production 
![image](https://github.com/Expensify/App/assets/115492554/4f0e393f-f56b-4a0f-b64e-dd0240ec7a2c)

**Comment by etCoderDysto** [comment] 2024-06-28 09:03
Investigating! This seems to come from a PR I have worked on https://github.com/Expensify/App/pull/44190

**Comment by cristipaval** [comment] 2024-06-28 09:19
Thanks @etCoderDysto! Assigning you to it

**Comment by cristipaval** [comment] 2024-06-28 09:20
@mollfpr, added you as the C+, given that you reviewed the [offending PR](https://github.com/Expensify/App/pull/44190)

**Comment by Julesssss** [comment] 2024-06-28 10:16
Hey @etCoderDysto & @cristipaval, can you please tag me on the fix PR? I want to cherry-pick this and use it to test something.

**Comment by etCoderDysto** [comment] 2024-06-28 10:18
Sure! @Julesssss

**Comment by etCoderDysto** [comment] 2024-06-28 11:04
@mollfpr @cristipaval 
[PR](https://github.com/Expensify/App/pull/44605) is ready for review.

**Comment by etCoderDysto** [comment] 2024-06-28 11:05
@mollfpr @cristipaval 
[PR](https://github.com/Expensify/App/pull/44605) is ready for review.

**Comment by luacmartins** [comment] 2024-06-28 15:14
I don't think this needs to be a blocker. So I'll remove the labels

**Comment by etCoderDysto** [comment] 2024-07-22 19:48
We can close this. It has been over a week since the pr is deployed to production.

**Comment by luacmartins** [comment] 2024-07-22 19:51
Oh I think automation failed here and we still need to process the payment. Updating the issue

**Comment by etCoderDysto** [comment] 2024-07-22 20:31
> Oh I think automation failed here and we still need to process the payment. Updating the issue

I don't think there are any payments to be made here. This issue was a regression from my PR. And I and C+ fixed the issue.

**Comment by luacmartins** [comment] 2024-07-22 21:02
Ah I see, then yes we're good to close since that'll be handled in the original issue. Thank you!

**Closed by luacmartins** 2024-07-22 21:02 UTC
Labels: External, Engineering, Monthly, Awaiting Payment, Bug
