### ISSUE TITLE
[$250] [HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Android - Scan - Camera shutter sound still goes off despite device and app sound profile

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39241] opened 2024-03-29 14:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition
- Device sound mode is silent and app sound is disabled
1. Launch New Expensify app
2. Go to FAB > Request money > Scan
3. Take a photo

## Expected Result:
There will be no camera shutter sound in app when the device is in silent mode (iOS app behavior)

## Actual Result:
The camera shutter sound still goes off when device is in silent mode and app sound is disabled. The shutter sound is also very loud compared to iOS app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9006cdcf-29dc-4747-bb02-f5e0889f2244

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014944bc05e2176f43</li>
        <li>Upwork Job ID: 1785436799448760320</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

**Comment by johnmlee101** [comment] 2024-03-29 14:51
I think its due to https://github.com/Expensify/App/issues/39241

**Comment by johnmlee101** [comment] 2024-03-29 14:51
I think its due to https://github.com/Expensify/App/pull/37483

**Comment by johnmlee101** [comment] 2024-03-29 14:52
cc @mrousavy

**Comment by mrousavy** [comment] 2024-03-29 15:09
Ok gotcha - I'll see if this can be reproduced in ShadowLens

**Comment by johnmlee101** [comment] 2024-03-29 17:08
Let me know when you have an update!

**Comment by johnmlee101** [comment] 2024-04-01 15:26
I have read and reviewed this Design Doc!

**Comment by marcaaron** [comment] 2024-04-01 21:28
CP'd the revert. Asked for a re-test [here](https://expensify.slack.com/archives/C9YU7BX5M/p1712006866085039)

**Comment by kavimuru** [comment] 2024-04-01 23:11
Issue is not repro anymore.

Uploading Repro_39241.mp4…

**Comment by mrousavy** [comment] 2024-04-02 09:59
Hey! Sorry for the regression.

Two things:

1. I just fixed this on the VisionCamera V4 Beta branch ([21220c](https://github.com/mrousavy/react-native-vision-camera/pull/2623/commits/86c0f863ff7cb7548bbb60b6fa191baeb021220c)) by not playing the shutter sound when the device is in SILENT or VIBRATE mode.
2. We can also additionally disable `enableShutterSound` in the `takePhoto(...)` options when the Expensify app is configured to mute all sounds. How do I get that prop from state/preferences? I can quickly add that.

**Comment by johnmlee101** [comment] 2024-04-17 15:32
Closing this out

**Comment by c3024** [comment] 2024-04-23 12:52
@johnmlee101 

I reviewed the PR #39400. Could you reopen this and pay? Thanks.

**Comment by johnmlee101** [comment] 2024-04-23 15:35
adding a bugzero member!

**Comment by kevinksullivan** [comment] 2024-04-30 22:33
Hi @c3024 can you apply to the job above and let me know when you've done so? I am not sure what your name/handle is in upwork. Thanks! Also, what are you expecting this price to be?

**Comment by c3024** [comment] 2024-05-01 04:19
@kevinksullivan Thanks. Applied for the job. $250 is good. 

Here is my Upwork profile as well for info
https://www.upwork.com/freelancers/~0105555e2f227dbf47

**Comment by kevinksullivan** [comment] 2024-05-09 21:27
offer sent back to ya @c3024 . Let me know when you accept and we can get this wrapped up. Feel free to slack me to @kevin and I can knock this out quickly.

**Comment by kevinksullivan** [comment] 2024-05-10 21:40
All set

**Closed by kevinksullivan** 2024-05-10 21:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
