### ISSUE TITLE
[HOLD 19119][$1000] Offline - Infinite loading in case of Send a money to the user you have never chatted before

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19318] opened 2023-05-19 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Send a money to the user you have never chatted before with settled up elsewhere
## Expected Result:
Greyed out IOU should be displayed
## Actual Result:
Infinite loading
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/161efbbe-4111-413a-b255-d3e03dba1229

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c9cbd6bae33acb1</li>
        <li>Upwork Job ID: 1660205816623935488</li>
        <li>Last Price Increase: 2023-05-21</li>
    </ul>
</details>

**Comment by tienifr** [comment] 2023-05-22 04:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite loading when sending money to another user that never chats before.

### What is the root cause of that problem?
There're 2 reports that are of concern when sending money:
1. Regular chat report between 2 users
2. IOU report 

In `getSendMoneyParams` here https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/actions/IOU.js#L993, we're only constructing these optimistic report actions data for the IOU report:
   - The IOU report action
   - Chat created action (if it's a new chat)
But we're not adding any optimistic report action for the regular chat report. There's no report actions in the regular chat report so it will show infinite loading as per this line: https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/ReportScreen.js#L232.

### What changes do you think we should make in order to solve the problem?

We need to add these optimistic report actions for the Regular chat as well:
   - The IOU report action (The one that says "Settled up ${amount} elsewhere)
   - Chat created action (if it's a new chat)

### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment] 2023-05-22 07:37
Still receiving proposals! Nice!

**Comment by sophiepintoraetz** [comment] 2023-05-22 09:14
Hmm, I feel like these proposals could also factor in this issue [here](https://github.com/Expensify/App/issues/19317)?

**Comment by dylanexpensify** [comment] 2023-05-22 17:56
[I'm heading OOO tomorrow](https://expensify.slack.com/archives/C01SKUP7QR0/p1684776773511559) for about a week so adding another BZ member while I'm away to help keep the train moving! 🚂  Thanks @bfitzexpensify!!

**Comment by tienifr** [comment] 2023-05-25 09:58
> There's another issue where if we send money from A to B, when online the Pusher is pushing the report preview in the main chat between A and B Settled up ... elsewhere, but the sender is B, this is not correct since the sender should be A. This should be fixed in the back-end.

@fedirjh sorry for the confusion, the update I meant was not from Pusher, but more correctly the `OpenReport` API which will return the new `Created chat` and `Report preview` report actions generated from BE side. 

> but the sender is B, this is not correct since the sender should be A. 

About this, `Report preview` report action returned has wrong `actorEmail`. 

> This should be fixed in the back-end.

The fix in BE I meant is to accept the reportActionIDs that are optimistically generated in front-end for both  `Created chat` and `Report preview` report.

> The last time I got this issue: BE returned another IOU message when I went online, and the UI looked weird as it had 2 IOU messages.

The issue @hoangzinh mentioned is the same back-end issue that I referred to there, once applying that BE fix then we should be good, the `actorEmail` will be correct since it's the same as the one used in the optimistic 'REPORTPREVIEW' report action

**Comment by MonilBhavsar** [comment] 2023-05-26 05:37
Great discussion here. I'm catching up on this.
Seems like the backend returns the different reportID, but should considered optimistically generated reportID on frontend while offline, correct?

**Comment by tienifr** [comment] 2023-05-26 05:44
@MonilBhavsar currently the BE generates ID on its own, the BE should instead use the optimistic report action IDs generated in the front-end side.

**Comment by tienifr** [comment] 2023-05-26 06:40
> @tienifr Why action has wrong actorEmail ? this is a send money request , so the requestor should be the one who receives the money not the one who sends it , am I missing something ?

@fedirjh  Let's see the case currently in staging where User A sends money to User B:
1. It shows like this in the DM with user B, as a report preview
<img width="234" alt="Screenshot 2023-05-26 at 13 31 12" src="https://github.com/Expensify/App/assets/113963320/bafc5ffe-c10f-4777-bc9d-7268424c7948">

2. And shows like this in the created IOU report
<img width="523" alt="Screenshot 2023-05-26 at 13 33 13" src="https://github.com/Expensify/App/assets/113963320/cfd0bfe3-9eba-4dc4-846f-d9e8633f2884">

The content of the message is "${payer} settled up ${amount} elsewhere", that means the payer settled up the money, as can also be seen in the code in here https://github.com/Expensify/App/blob/5f14eeeac20d08a511caf85ce99e56d1a06b8993/src/components/ReportActionItem/ReportPreview.js#L123.

So the `actorEmail` of that message needs to be the payer (User A), not the payee (User B). When I see the `1` above I read that "User B settled up 470 elsewhere", which is incorrect since User A is the one that settled up the money, User B is the one receiving the money. In `2` it shows correctly.

> the requestor should be the one who receives the money

@fedirjh if it reads "... received ${amount} elsewhere" then I agree with you on this, but in this case the message is about payer settling up the amount.

**Comment by tienifr** [comment] 2023-05-26 08:13
> What can I see , no matter what the request is, if user A made the request then the message is displayed as user B. So I think that’s expected.

@fedirjh which request do you mean? For example when user A initiate requesting money and split bill (and send money message in the IOU report), the message always displays as user A. It's only for `Send money` report preview that it displays as user B. So I see it as an anomaly, not the norm. Unless I'm missing something here.

<img width="474" alt="Screenshot 2023-05-26 at 15 09 30" src="https://github.com/Expensify/App/assets/113963320/1851c450-5d6a-4414-88fd-3f7da4d25fb3">

**Comment by tienifr** [comment] 2023-05-26 08:18
@fedirjh  Here's more specifics (user A initiated the request):

| Case  | Location | Message displays as |
| ------------- | ------------- | ------------- |
| Request money  | Main report  | User A  |
| Request money  | IOU report  |  User A  |
| Send money  | Main report  | **User B**  |
| Send money  | IOU report  |  User A  |
| Split bill  | Main report  |  User A  |

**Comment by tienifr** [comment] 2023-05-26 08:31
@fedirjh anyway, I agree with you that probably should be handled separately from this issue 👍. For this issue perhaps we can keep the current `actionEmail`, add the 2 optimistic report actions as mentioned initially, fix the BE and move forward with this.

**Comment by tienifr** [comment] 2023-05-29 06:28
@fedirjh hi I'm back from weekends, will post an update soon 🙇

**Comment by bfitzexpensify** [comment] 2023-06-01 12:28
@MonilBhavsar thoughts on https://github.com/Expensify/App/issues/19318#issuecomment-1567395523?

**Comment by MonilBhavsar** [comment] 2023-06-01 12:32
Sorry, I'll take a look and get back here

**Comment by MonilBhavsar** [comment] 2023-06-06 06:29
Sorry, had another priority issues. Looking now

**Comment by luacmartins** [comment] 2023-06-08 16:59
This could be due to the fact that the only reportAction that exists in the chat report at that point is the reportPreview action and it's still not being added optimistically. If that's the case, yes https://github.com/Expensify/Expensify/issues/284588 should address that.

**Comment by MonilBhavsar** [comment] 2023-06-09 06:13
Yes it is and [this](https://github.com/Expensify/App/issues/19119) is the issue for frontend, so I think we should hold this issue on the frontend issue instead. cc @mountiny

**Comment by mountiny** [comment] 2023-06-12 16:20
Yep I agree this should wait for the implementation from Cristi

**Comment by dylanexpensify** [comment] 2023-06-28 09:23
@cristipaval @mountiny any update here?

**Comment by cristipaval** [comment] 2023-06-28 10:05
I'm making [the PR](https://github.com/Expensify/App/pull/21578) ready for review today.

**Comment by dylanexpensify** [comment] 2023-07-07 08:36
amazing, @cristipaval any updates?

**Comment by cristipaval** [comment] 2023-07-07 20:44
the PR is still in review, almost there

**Comment by JmillsExpensify** [comment] 2023-07-12 16:00
We deprecated `send money`. Are ya'll sure we should still move forward with this PR?

**Comment by dylanexpensify** [comment] 2023-07-17 09:11
Ah great shout @JmillsExpensify - @cristipaval mind weighing in? I think we should actually hold on this PR

**Comment by cristipaval** [comment] 2023-07-22 21:39
[The PR](https://github.com/Expensify/App/pull/21578) that this issue is held on was deployed. The thing is that the issue can't be reproduced anymore anyway, since the Send Money flow is disabled.

**Comment by dylanexpensify** [comment] 2023-07-26 07:50
Interesting - so not reproducible because of it being disabled, but not necessarily meaning it doesn't still exist?

**Comment by cristipaval** [comment] 2023-07-26 17:36
This should be fixed by [my PR](https://github.com/Expensify/App/pull/21578). I would close this issue for now, I'm sure we'll retest the entire Send money feature if we'll enable it again. Thoughts?

**Closed** 2023-08-04 12:10 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
