### ISSUE TITLE
[Needs reproducing][$1000] DEV: Console error appears when entering the title of task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22528] opened 2023-07-09 05:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to FAB > Assign task
2. Enter any title
## Expected Result: 
Console error shouldn't appear when entering the title of task
## Actual Result: 
Console error appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 06-07-2023 12_05_17.webm](https://github.com/Expensify/App/assets/43996225/466ae510-e448-4237-9fad-761997b4dcc3)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688443093641289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112e92ae4665bc582</li>
        <li>Upwork Job ID: 1678995838570291200</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-09 05:32
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console error appears when entering the title of task
### What is the root cause of that problem?
`props.task.title` is `undefined` when the first time we open assign task. And after we enter the title, title is changed from `undefined` to a defined value. That is why the console error appears.
https://github.com/Expensify/App/blob/917c344649d1fe8101de0f58a4554f3f5dee8666/src/pages/tasks/NewTaskDetailsPage.js#L39
### What changes do you think we should make in order to solve the problem?
We should change default value of `taskTitle` state to `props.task.title || ''` to make it is a defined value when the first time we open assign task.
https://github.com/Expensify/App/blob/917c344649d1fe8101de0f58a4554f3f5dee8666/src/pages/tasks/NewTaskDetailsPage.js#L39
```
const [taskTitle, setTaskTitle] = useState(props.task.title || '');
```
### What alternative solutions did you explore? (Optional)

**Comment by gadhiyamanan** [comment] 2023-07-09 06:21
Dupe of https://github.com/Expensify/App/issues/22169

**Comment by kadiealexander** [comment] 2023-07-11 08:00
@dukenv0307 I'm having trouble reproducing this in my dev environment, could you please take a look at the testing steps?

https://github.com/Expensify/App/assets/59587260/09de443d-c714-4aed-b5d6-6f9054dc80f5

**Comment by kadiealexander** [comment] 2023-07-11 08:11
I'm still not able to reproduce your console error after reloading:

https://github.com/Expensify/App/assets/59587260/0c934427-7b01-4d77-9b4e-5b99f51ca8e8

When was the last time you updated your local repo?

**Comment by multijump** [comment] 2023-07-11 10:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error appears when entering the title of task

### What is the root cause of that problem?
`props.task`'s default value is `{}` so when load assign task modal, `props.task.title` will be the `undefined`.
Then it causes the console error.
This is the RC.

### What changes do you think we should make in order to solve the problem?

We must check `props.task.title` is `undefined` or not.
Even though we set the default value as `''` in [here](https://github.com/Expensify/App/blob/38890e2e3c32b52dad11a7dfc09494924519946b/src/pages/tasks/NewTaskDetailsPage.js#L40), it reset in [useEffect](https://github.com/Expensify/App/blob/38890e2e3c32b52dad11a7dfc09494924519946b/src/pages/tasks/NewTaskDetailsPage.js#L44)
So we need to set default value in useEffect like this.
```
    useEffect(() => {
        setTaskTitle(props.task.title || '');
        setTaskDescription(props.task.description || '');
    }, [props.task]);
```

### What alternative solutions did you explore? (Optional)
We can define default value of `props.task`.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by kadiealexander** [comment] 2023-07-12 05:12
Repro'd:

https://github.com/Expensify/App/assets/59587260/f1a94341-7bf8-44af-a3cd-55ed148452a7

**Comment by situchan** [comment] 2023-07-12 05:18
Might be fixed globally in #22589

**Comment by sobitneupane** [comment] 2023-07-12 07:15
@mollfpr This issue will probably be handled in [this PR](https://github.com/Expensify/App/pull/22589).

**Comment by mollfpr** [comment] 2023-07-12 09:16
Thanks for the head up @sobitneupane 

@kadiealexander Let's HOLD this until the PR hit production.

**Comment by hannojg** [comment] 2023-07-14 13:07
I can confirm that this issue will be fixed by the mentioned PR.

**Comment by mollfpr** [comment] 2023-07-17 14:54
Waiting for @kadiealexander to update the title

**Comment by kadiealexander** [comment] 2023-07-20 03:01
Apologies team, I was OOO.

**Comment by kadiealexander** [comment] 2023-07-31 05:49
Still on hold.

**Comment by hannojg** [comment] 2023-08-02 06:38
The fix is on staging, can we please retest @mollfpr @kadiealexander

**Comment by mollfpr** [comment] 2023-08-09 15:06
Sorry for the delay 🙏

It is not reproducible on the latest main.

https://github.com/Expensify/App/assets/25520267/6aa4fe88-9705-436d-a071-296a91cbeffd

**Comment by kadiealexander** [comment] 2023-08-11 05:34
Thanks for testing @mollfpr!! Closing as this was fixed elsewhere.

**Closed by kadiealexander** 2023-08-11 05:34 UTC
Labels: External, Daily, Needs Reproduction, Bug
