### ISSUE TITLE
After signing in, my chats list was totally blank and then look how far up and to the right the FAB is

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9744] opened 2022-07-06 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open app after some time 
2. login 

## Expected Result:
user should see LHN and chats 

## Actual Result:
After signing in, my chats list was totally blank and then look how far up and to the right the FAB is. I had to force close the app and relaunch to get my chat list to populate.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Desktop App

**Version Number:** 1.1.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img src="https://user-images.githubusercontent.com/43995119/177592117-59020c4e-7bbb-4d79-9867-553e8eec3296.png" width="40%" height="40%">
<img width="1203" alt="image - 2022-07-06T115126 776" src="https://user-images.githubusercontent.com/43995119/177592121-b196e970-6528-455a-bd56-cdb757744244.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657042083988489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2022-07-06 16:16
@Beamanator sorry, spellcheck. Corrected

**Comment by Beamanator** [comment] 2022-07-06 16:17
Aah ok thanks :D I posted in the original thread to see if anyone can reproduce - if not, i'm not sure how I'll move forward with this 😅

**Comment by mvtglobally** [comment] 2022-07-06 16:18
@Beamanator we were not able to repro on quite a few of the devices. We will keep an eye on it today as well.

**Comment by Beamanator** [comment] 2022-07-07 12:54
Thanks for testing! 🙏 we can keep this open a few days to see if anyone can reproduce, maybe we'll have to close if not

**Comment by Beamanator** [comment] 2022-07-11 15:19
Gunna make this `Weekly` and will add `Needs Reproduction`

**Comment by Beamanator** [comment] 2022-07-25 11:02
Thinking we can close this since it hasn't been reproduced lately

**Comment by shawnborton** [comment] 2022-07-25 14:53
I think that's fair, we can close and I'll reopen if I see it again.

**Closed by shawnborton** 2022-07-25 14:53 UTC
Labels: Engineering, Weekly, Needs Reproduction
