### ISSUE TITLE
CVP BUG: As a new user, getting a long loading after submitting the first receipt

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53096] opened 2024-11-25 22:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_quality](https://expensify.slack.com/archives/C05CBC62HGW/p1732314749713549)

## Action Performed:

1. Signup for a new account
2. Submitted (scan) a receipt and sent it to another user
3. Click continue 

## Expected Result:
The receipt displayed instantly

## Actual Result:
Could see the receipt had already been scanned in the room preview in LHN
But when tried to go into the DM, it continued not to load.
This happened again when tried to go to the selfDM.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/b49de7d4-002d-429e-8519-1cb4053b4004

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment] 2024-12-02 22:13
I will need to seek out someone that can repro this one

**Comment by muttmuure** [comment] 2024-12-03 14:03
Asked for a profile trace for the issue so we can see what is failing to load

**Comment by chiragsalian** [comment] 2024-12-05 22:58
Not overdue, waiting for reproduction.

**Comment by muttmuure** [comment] 2024-12-10 12:35
```
[App] 2024-11-22T22:26:04.806Z - [info] [Onyx] Failed to save to storage. Error: DataCloneError: Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.. onyxMethod: m ~~ parameters: '' userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Mobile/15E148 Safari/604.1'
```

**Comment by johncschuster** [comment] 2024-12-16 23:11
@chiragsalian, it looks like Matt was able to get a profile trace. Is there anything else needed here?

**Comment by chiragsalian** [comment] 2024-12-17 23:48
I dont see a profile trace? Where is it? If you mean [this](https://github.com/Expensify/App/issues/53096#issuecomment-2531519214) that's not a profile trace. Thats just a log.

A profile trace would look like this, (this is just me refreshing the App locally and creating a profile trace)
[profiling-data.12-17-2024.15-40-04.json](https://github.com/user-attachments/files/18172533/profiling-data.12-17-2024.15-40-04.json)

That said, maybe the log is an error which is why the action is perhaps not completing and looks like its infinitely loading for the user. Let me know if you guys are able to consistently reproduce.

Additionally, looking at the error,
```
[App] 2024-11-22T22:26:04.806Z - [info] [Onyx] Failed to save to storage. Error: DataCloneError: Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.. onyxMethod: m ~~ parameters: '' userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Mobile/15E148 Safari/604.1'
```
I suspect if the issue is reproducible, then it should be reproducible on safari as well. That would make testing this a bit easier vs testing on ios. Let me know if you guys can reproduce.

Finally, I can create a profile trace for this issue if needed. But it's better to first check if there is an actual error or issue here before working on the trace.

**Comment by chiragsalian** [comment] 2024-12-27 19:18
Daniel retested and couldnt reproduce the issue - [slack](https://expensify.slack.com/archives/C05LX9D6E07/p1735325382356029?thread_ts=1733234565.335599&cid=C05LX9D6E07)
I just retested and couldn't reproduce it either. Gonna close this now for #focus. Feel free to reopen if someone can reproduce or we get more data on this.

**Closed by chiragsalian** 2024-12-27 19:18 UTC
Labels: Weekly, Needs Reproduction, Overdue, Bug, AutoAssignerNewDotQuality
