### ISSUE TITLE
[$500] Expense - Preview shows 0.00 when receipt currency is different from workspace currency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34064] opened 2024-01-05 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a scan request with a receipt which has different currency from the workspace default currency
3. Stay in the workspace chat and wait until the scanning is complete

## Expected Result:
The expense preview shows the correct amount when the scanning is complete

## Actual Result:
When the scanning is complete, the expense preview shows 0.00, while LHN preview has no issue displaying the amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6333473_1704485173645!E_receipt_](https://github.com/Expensify/App/assets/78819774/7b448b27-a231-474e-9852-3973ad4eddbf)

https://github.com/Expensify/App/assets/78819774/55b1d799-db21-4b7b-b34a-fb26a72a8765

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01487b67fb3f39c5a0</li>
        <li>Upwork Job ID: 1743372007763001344</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28106113</li>
<li>bernhardoj | Contributor | 28106114</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-06 01:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `getDisplayAmount` in the `ReportPreview` is returning '0.00' because `totalDisplaySpend` is zero and the `REPORTPREVIEW` action does not update the `message` once the receipt has completed scanning. 

However, the chat report's last message will be updated. That is why the LHN and Money Request Header components are updated.

https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/components/ReportActionItem/ReportPreview.js#L196-L203

### What changes do you think we should make in order to solve the problem?


Hence, we can use the `OptionsListUtils.getLastMessageTextForReport` function if the `props.action.message` is not updated yet.

```
function getAmountFromMessage(actionMessage){
 let displayAmount = '';
 const splits = actionMessage.split(' ');
  for (let i = 0; i < splits.length; i++) {
    if (/\d/.test(splits[i])) {
        displayAmount = splits[i];
    }
  }
 return displayAmount
}
....
return (
 getAmountFromMessage(lodashGet(props.action, ['message', 0, 'text'], '')) ||
 getAmountFromMessage(OptionsListUtils.getLastMessageTextForReport(props.chatReport))
)
```

Furthermore, we should probably optimize and improve the `for` loop which is currently implemented in the codebase. Using `_.filter()`

**Comment by aim-salam** [comment] 2024-01-06 02:35
.

**Comment by bernhardoj** [comment] 2024-01-06 06:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we do a scan request, the amount preview shows 0. This happens even if we have the same currency as workspace.

### What is the root cause of that problem?
The amount will show based on `getDisplayAmount` function.
https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/components/ReportActionItem/ReportPreview.js#L180-L204

It will show the amount if `totalDisplaySpend` > 0, otherwise, it will take the amount from the report action message. However, the report action message amount is 0.
<img width="262" alt="image" src="https://github.com/Expensify/App/assets/50919443/c448cde8-4f05-4f27-b75d-e43110d5eeca">

And the `totalDisplaySpend` is 0 too. When we reopen the report or open the associated IOU report, we will get the correct amount.

I think the report action message amount is 0 is already obvious that this is a BE problem. But why `totalDisplaySpend` is 0? We get the `totalDisplaySpend` from `getMoneyRequestSpendBreakdown`. It will return a non 0 `totalDisplaySpend` ONLY if `nonReimbursableSpend` + `totalSpend` is not 0.
https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1728-L1742

If we check the amount of both `nonReimbursableSpend` and `totalSpend`, we can see that the amount cancel out each other.
<img width="220" alt="image" src="https://github.com/Expensify/App/assets/50919443/2ac8288d-7bdd-4505-951d-9bfdbc9cb172">

Thus, we return a 0 `totalDisplaySpend`.
https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1745-L1749

But if we reopen the report or open the IOU report, the BE will returns a 0 `nonReimbursableSpend`.
<img width="199" alt="image" src="https://github.com/Expensify/App/assets/50919443/6a0775b6-5b9c-4141-9e68-240d58173623">

But why LHN's last message show the correct amount?
<img width="249" alt="image" src="https://github.com/Expensify/App/assets/50919443/63a5ce03-b09f-460e-9988-3fed6d3ef77e">

It's because the last message doesn't use `getMoneyRequestSpendBreakdown` logic and just gets the money request total amount.
https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L2095
https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1693-L1713

### What changes do you think we should make in order to solve the problem?

If we look at this [PR commit](https://github.com/Expensify/App/pull/29566/files#diff-90dbf92cac79a4d1c6199362686c19700554305c62fbbeadcaa509c3abe7e5a9L114-L143), we previously show the total amount.

I think ideally we should fix this on the BE, but in case we want to have the same behavior as LHN's last message, we can fallback to the amount total

```
const total = ReportUtils.getMoneyRequestReimbursableTotal(props.iouReport);

if (totalDisplaySpend || total) {
    return CurrencyUtils.convertToDisplayString(totalDisplaySpend || total, props.iouReport.currency);
}
(or do the fallback inside getMoneyRequestSpendBreakdown by replacing 0 with getMoneyRequestReimbursableTotal)
```

But with this fallback, we can potentially show the wrong amount when the `totalDisplaySpend` is indeed 0 (that is the case where both `nonReimbursableSpend` and `totalSpend` really cancel out each other, not because of a bug). In that case, perhaps we can update the last message logic to use `getMoneyRequestSpendBreakdown` and get the `totalDisplaySpend` so we can have consistent behavior.

**Comment by miljakljajic** [comment] 2024-01-08 16:46
@cubuspl42 some proposals ready for review when you are!

**Comment by cubuspl42** [comment] 2024-01-09 10:07
🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-01-09 10:09
@tgolen Would you take a look at the investigations by @Tony-MK and @bernhardoj?

**Comment by bernhardoj** [comment] 2024-01-10 03:10
> Ideally, let's fix this in the backend. Can you please detail what BE changes you expect would fix this?

I think there are 2 BE fixes we can do, but fixing the first one is already enough.

When we create the scan request
1. We don't have `nonReimburseableTotal` and `total` yet
2. The report preview action message is "A owes 0.0"

First, after the money request scan is completed, the RequestMoney API response will give us `nonReimburseableTotal` and `total` of 0, but we will get a Pusher response that gives us a positive `nonReimburseableTotal` and negative `total` with the same number (e.g., 2000 and -2000). Both amounts cancel out each other and we will get `totalDisplaySpend` of 0 based on this [logic](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1728-L1749).

But only after we open the IOU report, the OpenReport API response will give us 0 `nonReimburseableTotal` with the amount of `total` unchanged (-2000 in our example).

Second, after the money request scan is completed, the RequestMoney API response will still give us the same action message, that is "A owes 0.0" instead of "A owes 20.0". Only after reopening the chat report will give us the correct action message.

So, for the first one, I don't really know which response we rely on, whether it's the Pusher or the RequestMoney API but I expect it will give us the correct `nonReimburseableTotal` and `total` just like when we open the IOU report.

For the second one, I expect the RequestMoney API to give us the updated action message without the user needing to reopen the report.

> The LHN and the preview should be using the same logic. Can you please detail what the consistent logic should be and how both places will display the same amount?

For the preview, we get the amount from [ReportUtils.getMoneyRequestSpendBreakdown](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1715), but for LHN last message, we get the amount from [ReportUtils.getMoneyRequestReimbursableTotal](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/ReportUtils.ts#L1693).

They both will return the money request report `total`, but `ReportUtils.getMoneyRequestSpendBreakdown` will return 0 if `nonReimburseableTotal` + `total` = 0 (which is true initially because of the bug above). I'm not really sure which logic to follow though, but it's either:
1. We use `ReportUtils.getMoneyRequestSpendBreakdown` for LHN last message or
2. Update `ReportUtils.getMoneyRequestSpendBreakdown` to return the `total` instead of 0 even though `nonReimburseableTotal` + `total` = 0 or
3. Leave `ReportUtils.getMoneyRequestSpendBreakdown` and in ReportPreview, fall back to `ReportUtils.getMoneyRequestReimbursableTotal`

**Comment by cubuspl42** [comment] 2024-01-10 09:37
@tgolen 

Maybe I'll explain why I summoned you without proper proposal selection. As it appeared that the issue is mostly (or even only) solvable on the backend, I thought this might be taken off the external path.

**Comment by miljakljajic** [comment] 2024-01-10 14:33
@tgolen do you think this can be worked on by someone from our open source team, or will we need to find an internal engineer?

**Comment by tgolen** [comment] 2024-01-10 16:44
@miljakljajic I think we need to do two fixes. One for the backend, and one for the frontend, and they can both be done in parallel.

@bernhardoj Thanks for the breakdown. It sounds like this will need to be the backend fix:

- Ensure the API response for RequestMoney and the Pusher event both have the same data for `nonReimburseableTotal` and `total` (it appears like the pusher data is correct)
- Ensure the OpenReport response also returns the same data
- Ensure the API response for RequestMoney has the right action message which is `A owes 20` and not `A owes 0`

@luacmartins I think you are pretty close to these backend fixes. What do you think about them and could you do that fix?

Then, in parallel, @bernhardoj can unify the LHN and message logic using option 1: `use ReportUtils.getMoneyRequestSpendBreakdown for LHN last message`.

**Comment by bernhardoj** [comment] 2024-01-10 17:11
> Ensure the API response for RequestMoney and the Pusher event both have the same data for nonReimburseableTotal and total (it appears like the pusher data is correct)

Both RequestMoney and the Pusher give the wrong data. Only OpenReport (of the IOU report) gives the correct data. `nonReimburseableTotal` should be 0 and `total` should be the negative value.

**Comment by tgolen** [comment] 2024-01-10 17:16
Thanks for clarifying 👍  I will update my previous comment.

**Comment by tgolen** [comment] 2024-01-11 15:25
Can you link to the fix for the total, so that we know when it is deployed and we can retest this?

I wouldn't mind you looking into the reportAction one as well.

**Comment by tgolen** [comment] 2024-01-11 15:26
@bernhardoj Are you OK with working on the frontend fix in parallel?

**Comment by luacmartins** [comment] 2024-01-11 15:41
Ok, gonna assign myself to look into the reportAction issue too

**Comment by bernhardoj** [comment] 2024-01-11 16:03
@tgolen yep, I'm okay with that

> This is the [PR](https://github.com/Expensify/Auth/pull/9629) fixing the total. It was deployed already, so we could test it again.

From my testing, `nonReimburseableTotal` and `total` are still 0 from the RequestMoney response and the pusher now sends `total` as null.
<img width="343" alt="Screenshot 2024-01-12 at 00 01 52" src="https://github.com/Expensify/App/assets/50919443/c0532279-f04d-45d5-9831-a871004e16f0">

**Comment by luacmartins** [comment] 2024-01-12 21:12
@bernhardoj oh I just read your [previous comment](https://github.com/Expensify/App/issues/34064#issuecomment-1885261127) again and realized you said `RequestMoney`. My PR fixed the flow for `UpdateMoneyRequestAmountAndCurrency` for [this issue](https://github.com/Expensify/App/issues/33733). 

That being said, the $0 `nonReimbursableTotal` and `total` in the `RequestMoney` response is correct, no? When you make the scan request the total is indeed $0 and it's only updated to $20 once the request is done scanning, which should come in the Pusher update only.

**Comment by bernhardoj** [comment] 2024-01-13 04:29
@luacmartins Ah, you're right, I thought RequestMoney would return a response when the scan is complete, which means RequestMoney is correct, and the Pusher one needs fixing.

**Comment by luacmartins** [comment] 2024-01-15 15:49
I created a [PR](https://github.com/Expensify/Auth/pull/9657) to fix the report total in the Smartscan pusher event. I'm not sure what frontend work is needed here, but yes we should wait on that.

**Comment by tgolen** [comment] 2024-01-17 14:48
Sorry @bernhardoj I didn't realize you hadn't been assigned. I've assigned you now and you can start on the FE change.

**Comment by bernhardoj** [comment] 2024-01-18 10:09
Looks like the pusher is fixed.

Btw, the FE PR to use the same logic is ready

**Comment by cubuspl42** [comment] 2024-01-23 10:21
There's some misunderstanding going on here. It appears that we don't know how to reproduce the issue after the backend fix. This makes it questionable whether there's any frontend fix needed at all.

@bernhardoj Could you sum up what the issue **is** after the backend fixes? Are we left with some technical debt / duplicated frontend utils that cannot be directly expressed as a user-perceived scenario, or what?

If there's no problem at all, I would vote to close the issue, compensating @bernhardoj at least partially for his investigation an analysis.

If there's a problem worth fixing (even if it's now a technical one), we should be on the same page.

If we have a strong feeling that there _might_ be a scenario that triggers user-perceived issue, we should try to find it.

**Comment by bernhardoj** [comment] 2024-01-23 11:01
> Could you sum up what the issue is after the backend fixes? Are we left with some technical debt / duplicated frontend utils that cannot be directly expressed as a user-perceived scenario, or what?

After the BE is fixed, we actually don't need any FE changes for the OP repro steps, but I'm under the assumption that we want to update the last message and preview amount to use the same logic (for consistency) with the fact that the last message shows a different amount when the BE issue persists.
<img width="905" alt="image" src="https://github.com/Expensify/App/assets/50919443/ab75252d-dc09-4997-be4b-dd8414145058">

BE and FE issues are basically different, with the FE issue only noticeable when the BE issue persists.

**Comment by cubuspl42** [comment] 2024-01-23 12:54
@tgolen @luacmartins However I always personally favor all efforts to make the code cleaner, more consistent and better in general, we'd need an approval to go forward here.

The fact is that the issue, as described, is **not reproducible**.

**Comment by luacmartins** [comment] 2024-01-23 16:24
@bernhardoj I'm removing getMoneyRequestReimbursableTotal in [this PR](https://github.com/Expensify/App/pull/34909), so I think we'd solve the consistency issue there.

**Comment by luacmartins** [comment] 2024-01-23 16:24
I think we can close this issue, since it's no longer reproducible.

**Comment by tgolen** [comment] 2024-01-23 16:41
OK, looks like https://github.com/Expensify/App/pull/34909 should cover the inconsistent frontend logic, so I agree with closing this.

**Comment by cubuspl42** [comment] 2024-01-24 08:47
@luacmartins @tgolen Please confirm whether you consider @bernhardoj not entitled for 25%/50% compensation. He investigated the issue pointed the exact place in the backend which needs fixing.

**Comment by tgolen** [comment] 2024-01-24 16:38
Thank you for asking. I agree @bernhardoj should be partially compensated at 50%, so reopening this. @miljakljajic can you assist with this payment, please?

**Comment by miljakljajic** [comment] 2024-03-22 16:00
Paying now - missed this one

**Comment by miljakljajic** [comment] 2024-03-22 16:01
Paid!

**Closed by miljakljajic** 2024-03-22 16:01 UTC
Labels: Reviewing, External, Monthly, Bug
