### ISSUE TITLE
[HOLD for Payment 2024-08-26] Accessing one expense reports from `search` opening transaction view instead of report view

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45408] opened 2024-07-15 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.06-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721024057246389

## Action Performed:
1. As a submitter submit a report with one expense to the workspace
2. Go to search  and click on the expense created in step 1

## Expected Result:
clicking on any expense in the Search page where the expense is the only expense on a report opens up the report view instead of the transaction view

-  Here is thinking on why we should show the report view when viewing a single expense on a one-expense report:
-  we get a much more consistent experience with workspace chat rooms - in the attached video, see the difference when you view an expense from the workspace chat vs when you view it from Search
-  we limit user exposure to our multiple levels of navigation hierarchy when it comes to the Workspace chat > Report > Expense relationship. This way if someone views the expense from Search and leaves a comment, we are only showing the report thread in their Inbox LHN
-  we expose the actual action button a user might want to take on the expense. For example, it's weird if the Search page is going to eventually show a "Submit" button on the expense row, yet you wouldn't be able to see that same button on the expense once you open it - you'd have to navigate one level up to the report (which most users will have no idea why that's even a thing) to see those report action buttons
- still think it makes sense to show the transaction view when you are trying to view an individual transaction from a grouped batch. But I do think the above change would make a much better experience for the majority of cases where it's a one-expense report.
## Actual Result:
Expenses on one-expense reports accessed from the `Search` > Expenses page open up the transaction view instead of the report view

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b1a8a14e-ee73-43bb-97f7-2975c20c54d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by luacmartins** [comment] 2024-07-15 17:04
@tienifr I'm not sure that your solution will work because we might not have the report or reportActions available in Onyx given that the Search API only returns data in the `snapshot_` key. I think we'll need to work on a solution on the backend.

**Comment by luacmartins** [comment] 2024-07-15 17:34
@tienifr thanks for the updated proposal. Can't we just use the reportID if `isOneTransactionThreadReport = true`?

**Comment by luacmartins** [comment] 2024-07-18 21:09
No updates yet. Focused on other Search issues atm.

**Comment by luacmartins** [comment] 2024-07-23 23:55
No updates yet. Focused on other Search issues atm.

**Comment by luacmartins** [comment] 2024-07-26 19:52
Got a couple of PRs up

**Comment by muttmuure** [comment] 2024-07-29 12:54
Not overdue

**Comment by luacmartins** [comment] 2024-08-06 07:03
Gonna reassign C+ as per [this comment](https://expensify.slack.com/archives/C02NK2DQWUX/p1721843446947239)

**Comment by muttmuure** [comment] 2024-08-28 20:46
I've invited you to apply to this job: https://www.upwork.com/jobs/~01b7e6d6058445ffef

**Comment by muttmuure** [comment] 2024-08-30 17:40
Paid

**Comment by luacmartins** [comment] 2024-09-16 01:09
Reopening this issue since it seems like the problem is back

**Comment by luacmartins** [comment] 2024-09-16 05:48
PR in review

**Closed** 2024-09-24 01:01 UTC
Labels: Reviewing, Weekly, Internal, Awaiting Payment, Bug
