### ISSUE TITLE
[HOLD for payment 2023-09-29] [$2000] Web - user not able to save last enable date of birth

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24266] opened 2023-08-08 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set the Date & Time on your Mac to `India Standard Time`
a. On Mac > System Settings > General > Date & Time
b. Enable "set time and date automatically" & Disable "Set time zone automatically using your current location"
c. Choose New Delhi - India as your "Closest City"
d. Disable "set time and date automatically"

2. Sign into https://staging.new.expensify.com/settings on the Chrome browser
3. Click the Profile icon (settings) > Profile > Personal details > Date of birth
4. Select the most recent available date
5. Notice date error

## Expected Result:
user should able to save enable date

## Actual Result:
error appears on select latest enable date

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/62597452-cca4-42c9-9a41-6b49594a38bd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan & @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691498421013379 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011fd6c960bd909251</li>
        <li>Upwork Job ID: 1689782476244590592</li>
        <li>Last Price Increase: 2023-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26685187</li>
<li>gadhiyamanan | Reporter | 26685188</li>
</ul></li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-08-08 13:37
I wasn't able to reproduce, Not sure if this is account specific. Since its potential blocker, please double check

**Comment by gadhiyamanan** [comment] 2023-08-08 13:52
Try with new user if not able to reproduce

**Comment by Pujan92** [comment] 2023-08-08 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to select the max date 

### What is the root cause of that problem?
Here we have the difference in time which causes this condition to be falsy.

https://github.com/Expensify/App/blob/dd21a0b017b73487efc6d3796a09dd9a50c473a4/src/libs/ValidationUtils.js#L224

### What changes do you think we should make in order to solve the problem?
We need to add `startOfDay` for the testDate also to compare the dates correctly.

`const testDate = startOfDay(new Date(date));`
https://github.com/Expensify/App/blob/dd21a0b017b73487efc6d3796a09dd9a50c473a4/src/libs/ValidationUtils.js#L220

**Comment by Christinadobrzyn** [comment] 2023-08-08 15:53
I can't reproduce either - asking for more guidance in the Slack thread - https://expensify.slack.com/archives/C049HHMV9SM/p1691509966704559?thread_ts=1691498421.013379&cid=C049HHMV9SM

**Comment by puneetlath** [comment] 2023-08-08 16:08
I don't think this needs to be a deploy blocker as it only affects users who are exactly 5 years old. Removing the label.

**Comment by Pujan92** [comment] 2023-08-08 20:44
> I can't reproduce either - asking for more guidance in the Slack thread - 

@Christinadobrzyn It can be reproducible for the GMT+__(something) timezones. for GMT-__ it won't be reproducible as it(current code) considers previous day for it.

**Comment by Pujan92** [comment] 2023-08-09 11:45
For Mac these are the steps to update timezone and set any GMT+ city.

1. Select "System Preferences" from the Apple menu.
2. Under the "Date and Time" option, click on "Time Zone."
3. Deselect the "Set Time Zone Automatically Using Current Location" and update the city manually.

https://github.com/Expensify/App/assets/14358475/ddef3739-3fe6-4b50-87bb-442d320fa2c2

**Comment by Christinadobrzyn** [comment] 2023-08-10 23:36
Thanks @Pujan92! I can reproduce this with those [additional steps](https://github.com/Expensify/App/issues/24266#issuecomment-1671174600). Updated the steps in the OP and added an External label

**Comment by Pujan92** [comment] 2023-08-17 21:01
> Still waiting on proposals

@Christinadobrzyn proposals are available, seems review is pending..

**Comment by Christinadobrzyn** [comment] 2023-08-17 21:31
Ah sorry! thanks for clarifying!

**Comment by Pujan92** [comment] 2023-08-18 10:58
I doubt whether we should handle this case or not where dependency will be the system timezone. One way is to setinterval of 1 sec and checks the timezone but isn't seem an optimal option.

**Comment by blazejkustra** [comment] 2023-08-18 14:31
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Selecting last enabled date of birth throws an error for some time zones

### What is the root cause of that problem?
`getAgeRequirementError` was recently updated. `currentDate` was changed to start of the day [here](https://github.com/software-mansion-labs/expensify-app-fork/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/ValidationUtils.js#L217):

```js
const currentDate = startOfDay(new Date());
```

so `currentDate` is at 00:00 GMT. `testDate` takes the corresponding zone time [here](https://github.com/software-mansion-labs/expensify-app-fork/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/ValidationUtils.js#L220) +05:30
```js
const testDate = new Date(date);
```

This makes the condition to be falsy [here](https://github.com/software-mansion-labs/expensify-app-fork/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/ValidationUtils.js#L224).

### What changes do you think we should make in order to solve the problem?
Rewrite `getAgeRequirementError` [function](https://github.com/software-mansion-labs/expensify-app-fork/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/ValidationUtils.js#L216-L231) so that it is time zone neutral.

After:
```js
function getAgeRequirementError(date, minimumAge, maximumAge) {
    const currentDate = startOfDay(new Date());
    const testDate = parse(date, CONST.DATE.FNS_FORMAT_STRING, currentDate);

    if (!isValid(testDate)) {
        return 'common.error.dateInvalid';
    }

    const maximalDate = subYears(currentDate, minimumAge);
    const minimalDate = subYears(currentDate, maximumAge);

    if (isWithinInterval(testDate, {start: minimalDate, end: maximalDate})) {
        return '';
    }

    if (isSameDay(testDate, maximalDate) || isAfter(testDate, maximalDate)) {
        return ['privatePersonalDetails.error.dateShouldBeBefore', {dateString: format(maximalDate, CONST.DATE.FNS_FORMAT_STRING)}];
    }

    return ['privatePersonalDetails.error.dateShouldBeAfter', {dateString: format(minimalDate, CONST.DATE.FNS_FORMAT_STRING)}];
}
```

☝️ By using parse, we parse the date string directly into a `Date` object without converting the time to the local time zone. That's because this method only uses the Year, Month, and Day from the string and disregards the time zone. Stripping the time of the date also helps because it allows you to compare just the date part and ensures that the comparison is not skewed due to differences in time values. As a result, the output Date object is in local time but represents midnight (start of the day) of the date specified in the string, making timezone difference insignificant if we're considering the whole day.

### Tests

Tested in on various time zones across the [globe](https://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png):

```js
console.log('2018-08-17:', getAgeRequirementError('2018-08-17', 5, 150));
console.log('2018-08-18:', getAgeRequirementError('2018-08-18', 5, 150));
console.log('2018-08-19:', getAgeRequirementError('2018-08-19', 5, 150)); // throws
console.log('invalid:', getAgeRequirementError('invalid', 5, 150)); // throws
console.log('1873-08-17:', getAgeRequirementError('1873-08-17', 5, 150)); // throws
console.log('1873-08-18:', getAgeRequirementError('1873-08-18', 5, 150));
console.log('1873-08-19:', getAgeRequirementError('1873-08-19', 5, 150));
```

**Comment by blazejkustra** [comment] 2023-08-21 10:53
@0xmiroslav Actually I did more than that, I refactored the whole function so that it is more readable, but yes the most important change that fixes the bug is that line. 

> We usually avoid code diff in proposal

Oh sorry, didn't know about that 🤔 Is this written somewhere in the contributing guidelines?

**Comment by blazejkustra** [comment] 2023-08-21 10:56
> What's the difference from @Pujan92's proposal? `const testDate = startOfDay(new Date(date));`

Is it a question regarding my proposal? @0xmiroslav

**Comment by blazejkustra** [comment] 2023-08-21 13:44
I believe @Pujan92 proposal partially doesn't work, I tested it on `Honolulu` timezone (it was 3:41AM 21-08-2023). Basically it doesn't work the other way around (it allows 2018-08-22 while it should be forbidden).

```ts
2018-08-20:
2018-08-21:
2018-08-22:
invalid: common.error.dateInvalid
1873-08-20: [
  'privatePersonalDetails.error.dateShouldBeAfter',
  { dateString: '1873-08-21' }
]
1873-08-21: [
  'privatePersonalDetails.error.dateShouldBeAfter',
  { dateString: '1873-08-21' }
]
1873-08-22:
```

cc @0xmiroslav

**Comment by Pujan92** [comment] 2023-08-22 13:10
I mean for this we are not allowed to select the next date as those are disabled so considering that my solution works but still  `parse` makes/sets the time in more correct way.

**Comment by cubuspl42** [comment] 2023-08-24 17:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selecting the last enabled date of birth results in an error for some time zones.

### What is the root cause of that problem?

We're involving the `now()` ("get current time") operation multiple times.

In `DateOfBirthPage`:

https://github.com/Expensify/App/blob/06b40f601419b768bf7e3791ba33a1b0c22fc004/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L84-L85

In `ValidationUtils`:

https://github.com/Expensify/App/blob/0b62ee512014744feda1c7fd4516ad3ed6ed4d0a/src/libs/ValidationUtils.js#L235

Time flows (it doesn't stop) so these timestamps **will** be different. In consequence, the last valid date becomes invalid.

### What changes do you think we should make in order to solve the problem?

Re-organize the validation logic so we call "get current time" operation once.

```js
/**
 * Build a validator which ensures that given date is in a specified range of years before now.
 *
 * @returns {Object}
 */
function buildAgeRequirementValidator() {
    const currentDate = startOfDay(new Date());
    const maxDate = subYears(currentDate, CONST.DATE_BIRTH.MIN_AGE);
    const minDate = subYears(currentDate, CONST.DATE_BIRTH.MAX_AGE);

    return ({
        /**
         * @property {Date}
         */
        minDate: minDate,

        /**
         * @property {Date}
         */
        maxDate: maxDate,

        /**
         * Validate that given date is in a specified range of years before now.
         *
         * @param {String} date
         * @returns {String|Array}
         */
        getError(date) {
            // Validation logic, same as before
        },
    });
}
```

Usage:

```js
function DateOfBirthPage({translate, privatePersonalDetails}) {
    // ...

    const validator = useRef(ValidationUtils.buildAgeRequirementValidator())

    const validate = useCallback((values) => {
        // ...
        
        const dateError = validator.getError(values.dob);

        // ...
    }, []);

    // ...

    return (
        <ScreenWrapper includeSafeAreaPaddingBottom={false}>
            // ...
            <Form
                // ...
            >
                <NewDatePicker
                    // ...
                    minDate={validator.minDate}
                    maxDate={validator.maxDate}
                />
            </Form>
        </ScreenWrapper>
    );
}
```

### What alternative solutions did you explore? (Optional)

Completely removing the validation logic, as it's not a security feature (**right?**) and as we control which dates are present in the picker, I'm still not sure when the mentioned errors can organically ocur; but I might be missing some case.

Switching to proper date/time types like [js-joda](https://js-joda.github.io/js-joda/) would help with reasoning about time, but wouldn't solve the issue completely. Still, I would recommend considering that.

**Comment by cubuspl42** [comment] 2023-08-24 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selecting the last enabled date of birth results in an error for some time zones.

### What is the root cause of that problem?

We're performing calculations on JavaScript's `Date` objects, which is not what we want to do semantically. `Date` object represents a timestamp in a particular timezone, while we want to operate on dates. In consequence, the code is bug-prone and difficult to reason about.

Additionally, we're invoking the "get current time" operation multiple times, which adds up to the uncertainty.

### What changes do you think we should make in order to solve the problem?

Suggest starting a project to replace the [kind-of-deprecated `Moment.js`](https://momentjs.com/docs/#/-project-status/) library with [`js-joda`](https://js-joda.github.io/js-joda/). There are only 20 imports from `moment` and 48 actual usages of `moment(...)` in Expensify.

`js-joda` might not be the most popular Moment.js alternative, but in my experience, it's the best one.

Switch the relevant logic, including the `NewDatePicker`, to [`LocalDate`](https://js-joda.github.io/js-joda/manual/LocalDate.html).

The conversion might have a relatively big diff, but I don't expect conceptual challenges. It should be quite straightforward and I have experience with a similar migration. Long-term, the benefit will be huge. 

The tricky part might be replacing [`moment.tz.guess`](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) from `moment-timezone` with an equivalent, but [the standard alternative](https://caniuse.com/internationalization) has >96% browser support.

**Comment by Christinadobrzyn** [comment] 2023-08-24 20:22
How're we looking with proposals @0xmiroslav do you want to see more?

**Comment by blazejkustra** [comment] 2023-08-27 14:08
@cubuspl42 Migration from `Moment` to `date-fns` is already ongoing [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1684312385467959), so it's unlikely to replace `Moment` with `js-joda`.

**Comment by cubuspl42** [comment] 2023-08-27 15:10
@blazejkustra Thanks for pointing that out, I wasn't aware of that effort. A bit sad we went with `date-fns`, but by quickly scanning the decision process it seems that popularity was one of the most important factors.

**Comment by Christinadobrzyn** [comment] 2023-08-28 21:24
@0xmiroslav feel free to leave an update on the proposal review when you have a moment!

**Comment by blazejkustra** [comment] 2023-08-30 07:14
@0xmiroslav The [PR](https://github.com/Expensify/App/pull/26271) is ready for review!

**Comment by blazejkustra** [comment] 2023-08-30 10:15
Sorry @0xmiroslav, closing the PR for now.

**Comment by Christinadobrzyn** [comment] 2023-09-12 21:02
hey @madmax330 can you review this proposal - https://github.com/Expensify/App/issues/24266#issuecomment-1697249243

**Comment by madmax330** [comment] 2023-09-13 13:01
@Gonals is not on parental leave 😄

**Comment by Gonals** [comment] 2023-09-15 02:13
Hahaha, I was! Not anymore!

**Comment by blazejkustra** [comment] 2023-09-15 07:18
@0xmiroslav The [PR](https://github.com/Expensify/App/pull/26271) is ready for review!

**Comment by Christinadobrzyn** [comment] 2023-09-29 19:25
@0xmiroslav is there a regression for this? Let me know and I'll pay this out

Payouts will be:

Issue Reporter: $50 @gadhiyamanan
Contributor: $500 @blazejkustra (contractor)
Contributor+: $500 @0xmiroslav 

Eligible for 50% #urgency bonus? N - looks like PR was created Aug 30th and merged Sept 18th

Upwork job is [here](https://www.upwork.com/jobs/~011fd6c960bd909251).

**Comment by Christinadobrzyn** [comment] 2023-09-29 20:58
@gadhiyamanan it looks like you might need to accept the offer - https://www.upwork.com/jobs/~011fd6c960bd909251
@0xmiroslav let me know how you'd like to be paid. Is this your new profile? https://www.upwork.com/nx/wm/offer/26685187

**Comment by gadhiyamanan** [comment] 2023-09-30 02:16
@Christinadobrzyn offer accepted, thanks!

**Comment by Gonals** [comment] 2023-10-02 08:23
All done here?

**Comment by Christinadobrzyn** [comment] 2023-10-03 19:42
Sorry for the delay here - 

@gadhiyamanan I've paid you in Upwork. 

@0xmiroslav thanks for the [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1693875311397449?thread_ts=1691559426.466079&cid=C01SKUP7QR0) link it sounds like your Upwork account has been restored and we're paying you directly. 

What is the Upwork link for your restored account so I can pay you through Upwork for this? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-03 22:18
Okay sounds good! Closing for now @0xmiroslav please let me know if you need any help with payment in the future.

**Closed by Christinadobrzyn** 2023-10-03 22:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
