### ISSUE TITLE
[$250] Expenses moved in OldDot to a new Report is routed to a different approver

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44939] opened 2024-07-07 11:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719536902555519

## Action Performed:
Submitter has a default workspace set to A
1. Create a workspace B
2. Invite submitter to workspace B
3. As a submitter submit an expense report to workspace B in NewDot
4. As a submitter login to OldDot
5. Unsubmit the report created in step 3
6. Move the expense to a new report 
## Expected Result:
Report is moved to workspace B and routed to another approver
## Actual Result:
Report is moved to workspace A and has to manually change 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f6a516bd-db20-4c36-8492-b3530a2f62ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190b440ad1bbb5263</li>
        <li>Upwork Job ID: 1811114900053337429</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2024-07-09 00:48
I was assigned over the weekend, I'll review it soon.

**Comment by alexpensify** [comment] 2024-07-10 19:03
Still on my testing radar

**Comment by alexpensify** [comment] 2024-07-10 19:07
Open for proposals here

**Comment by alexpensify** [comment] 2024-07-15 18:44
Still waiting for proposals here

**Comment by alexpensify** [comment] 2024-07-17 00:18
Open for proposals

**Comment by alexpensify** [comment] 2024-07-19 23:16
Waiting for proposals

**Comment by alexpensify** [comment] 2024-07-25 00:05
@hoangzinh - are you suggesting this one should be internal? Thanks!

**Comment by alexpensify** [comment] 2024-07-26 22:07
Thanks, I've updated the GH tags.

**Comment by trjExpensify** [comment] 2024-07-29 12:40
@jliexpensify can you confirm this bug report and reproduce it? It's pretty difficult to follow from the OP. I also don't get [this comment](https://expensify.slack.com/archives/C049HHMV9SM/p1719538078253219?thread_ts=1719536902.555519&cid=C049HHMV9SM). 

>On New.Dot: we “default” to submitting expenses to the ND Test Workspace

We don't. You select the workspace to submit an expense to when creating the expense in the `Submit expense` flow.

**Comment by jliexpensify** [comment] 2024-07-30 00:34
@trjExpensify I think there's been some confusion here: this GH should not have been created (cc @m-natarajan)

I indicated [here](https://expensify.slack.com/archives/C049HHMV9SM/p1719537890619889?thread_ts=1719536902.555519&cid=C049HHMV9SM) that the reason was that the Report defaulted to an Old.Dot workspace, so this wasn't an actual bug in the end.

>You select the workspace to submit an expense to when creating the expense in the Submit expense flow.

Re-reading the thread, I didn't word this very well: you're correct that you choose the workspace to submit to, what I meant here is that "we" (i.e. employees) default to submitting expenses on the `Test` workspace. Sorry for the confusion!

@alexpensify we can close this.

**Comment by alexpensify** [comment] 2024-07-31 22:05
Thanks for the update-- closing!

**Closed by alexpensify** 2024-07-31 22:05 UTC
Labels: Weekly, Internal, Help Wanted, Bug, Hot Pick
