### ISSUE TITLE
[$250] Chat - Specific "not found page" link crashes the app

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52866] opened 2024-11-21 08:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a new account
3. Send this link in composer after onboarding flow: [www.staging.new.expensify.com/r/6272828282](http://www.staging.new.expensify.com/r/6272828282)

## Expected Result:
User expects to get a page not found message

## Actual Result:
The first time around, the app crashes, after reloading from crash, it displays the correct page not found

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/61a900b1-a104-4e7c-bd6b-695fdcc35827
 
[2111.txt](https://github.com/user-attachments/files/17843836/2111.txt)
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861021052919519904</li>
        <li>Upwork Job ID: 1861021052919519904</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-11-21 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The first time around, the app crashes, after reloading from crash, it displays the correct page not found

### What is the root cause of that problem?

<img width="813" alt="Screenshot 2024-11-21 at 16 16 11" src="https://github.com/user-attachments/assets/ceb03d02-3f6f-4610-a2a2-a46a7b41e96a">

We have Onyx error when changing key from `undefined` to ''

### What changes do you think we should make in order to solve the problem?


We should fallback as '-1' [here](https://github.com/Expensify/App/blob/376f9f08755b0555cf3666c5a880542af57c7da1/src/pages/home/ReportScreen.tsx#L172)
```
  reportID: reportOnyx.reportID ?? '-1',
```
https://github.com/Expensify/App/blob/376f9f08755b0555cf3666c5a880542af57c7da1/src/pages/home/ReportScreen.tsx#L172



### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-11-22 21:13
@nkuoch thoughts here?

**Comment by sobitneupane** [comment] 2024-11-26 11:41
I was unable to reproduce the issue.

@nkdengineer, were you able to reproduce the issue?

**Comment by sobitneupane** [comment] 2024-12-02 12:02
@nkdengineer Bump https://github.com/Expensify/App/issues/52866#issuecomment-2500449089

**Comment by adelekennedy** [comment] 2024-12-03 00:07
I'm also not able to reproduce it now - I think we are good to close this one unless @nkdengineer you can reproduce?

**Comment by nkdengineer** [comment] 2024-12-03 09:14
@sobitneupane It's fixed.

**Comment by sobitneupane** [comment] 2024-12-06 07:07
@adelekennedy Good to close.

**Closed** 2024-12-06 08:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
