### ISSUE TITLE
[$1000] Dev - Pressing on ‘fix the errors’ on validation forms throw error message 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13909] opened 2022-12-30 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. Navigate to Settings > Any workspace > Connect bank account > Connect Manually > Press Save&Continue without any data
3. Will show please “fix the errors”  press on ‘fix the error’ > Notice in console it show error’s

## Expected Result:
Pressing “fix the error” should not show any console error/warning

## Actual Result:
Pressing “fix the error” shows console error/warning
 ’Uncaught TypeError: Cannot read properties of undefined (reading ‘left’) '  on web and on native platforms it shows ’ref.measureLayout must be called with a node handle or a ref to a native component`

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.45-0
**Reproducible in staging?:** Y (tested in web)
**Reproducible in production?:** y (tested in web)
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![native]()
<img width="1440" alt="web" src="https://user-images.githubusercontent.com/43996225/210092823-921a10ee-5172-4c1a-86db-5affacb8e061.png">

<img width="960" alt="1" src="https://user-images.githubusercontent.com/43996225/210093291-fb060021-e95e-4280-99a5-7a6a2450b77d.png">

<img src="https://user-images.githubusercontent.com/43996225/210092815-a5c05bed-d5e9-4fdb-8343-813e098b4856.png" width="40%" height="40%">
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhairyasenjaliya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672390562408519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147ce5eb30fa3ad88</li>
        <li>Upwork Job ID: 1609834450585026560</li>
        <li>Last Price Increase: 2023-01-02</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-01-02 08:50
Was able to reproduce.

**Comment by hungvu193** [comment] 2023-01-02 09:03
<b>Proposal</b>
This causes by the function ` this.form.scrollTo` inside `onFixTheErrorsLinkPressed` return undefinded.
<b>Solution</b>
Remove the block of code:
```javascript
                                // We substract 10 to scroll slightly above the input
                                if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
                                    focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
                                }
```
or add the check if the `this.form.scrollTo` is a function.

```diff
+ if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function' && typeof this.form.scrollTo === 'function') {
focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
}
```

**Comment by dhairyasenjaliya** [comment] 2023-01-02 09:20
**Proposal**

- Here for the web we are not getting `this.form.scrollTo` index due to that we are receiving an undefined warning we need to add more validation to check if `form.scrollTo` has a valid scroll index based on that we are moving screen with the keyboard open 

- IMO we need to use `_.isFunction` to check & valid `form.scrollTo` this is already being used in many places 

- Also need to change `typeof focusInput.measureLayout === 'function'` to -> `_.isFunction(focusInput.measureLayout)`

**Changes**
```diff
+  if (focusInput.measureLayout && _.isFunction(focusInput.measureLayout) && _.isFunction(this.form.scrollTo)) {
     focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
 }
```

**Result**

https://user-images.githubusercontent.com/47522946/210212706-89e5e3bc-42d9-4587-9c6a-67a5868ba7ec.mov

**Comment by allroundexperts** [comment] 2023-01-02 10:21
## Proposal

The error occurs due to `this.form.scrollTo` being undefined. However, we need to investigate why this is undefined. None of the above proposals try to find and ultimately fix this.

### Issue
`this.form` returns reference to the class `ScrollViewWithContext` instead of the `ScrollView` component itself. As seen here:
https://github.com/Expensify/App/blob/main/src/components/ScrollViewWithContext.js#L41-L42

Thus we need to use `scrollViewRef` property of the class component `ScrollViewWithContext`.

### Fix
We need to change the following:
```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index f3f4a5a0c..9f743cc73 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -275,7 +275,7 @@ class Form extends React.Component {
 
                                 // We substract 10 to scroll slightly above the input
                                 if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
-                                    focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
+                                    focusInput.measureLayout(this.form.scrollViewRef.current, (x, y) => this.form.scrollViewRef.current.scrollTo({y: y - 10, animated: false}));
                                 }
                             }}
                             containerStyles={[styles.mh0, styles.mt5, styles.flex1]}

```

**Comment by ali-thowfeek** [comment] 2023-01-02 10:33
## Issue
`this.form` does not refer to the actual relative node, which is the underlying `ScrollView`

## Proposal
pass down / forward the  `ref` properly to `ScrollViewWithContext` component

```
    render() {
        return (
            <ScrollView
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...this.props}
                ref={this.props.innerRef}
```

```
export default React.forwardRef((props, ref) => <ScrollViewWithContext innerRef={ref} {...props}/>);
```

**Comment by bernhardoj** [comment] 2023-01-02 10:54
### **Proposal**

We already wrap the view with ScrollViewWithContext, but we didn't consume the provided value. So, what we need to do is to wrap it again with the consumer to receive the scroll view ref.

```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index f3f4a5a0c..c5b76c721 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -10,7 +10,7 @@ import * as FormActions from '../libs/actions/FormActions';
 import * as ErrorUtils from '../libs/ErrorUtils';
 import styles from '../styles/styles';
 import FormAlertWithSubmitButton from './FormAlertWithSubmitButton';
-import ScrollViewWithContext from './ScrollViewWithContext';
+import ScrollViewWithContext, { ScrollContext } from './ScrollViewWithContext';
 
 const propTypes = {
     /** A unique Onyx key identifying the form */
@@ -256,34 +256,39 @@ class Form extends React.Component {
                     keyboardShouldPersistTaps="handled"
                     ref={el => this.form = el}
                 >
-                    <View style={[this.props.style]}>
-                        {this.childrenWrapperWithProps(this.props.children)}
-                        {this.props.isSubmitButtonVisible && (
-                        <FormAlertWithSubmitButton
-                            buttonText={this.props.submitButtonText}
-                            isAlertVisible={_.size(this.state.errors) > 0 || Boolean(this.getErrorMessage()) || !_.isEmpty(this.props.formState.errorFields)}
-                            isLoading={this.props.formState.isLoading}
-                            message={_.isEmpty(this.props.formState.errorFields) ? this.getErrorMessage() : null}
-                            onSubmit={this.submit}
-                            onFixTheErrorsLinkPressed={() => {
-                                const errors = !_.isEmpty(this.state.errors) ? this.state.errors : this.props.formState.errorFields;
-                                const focusKey = _.find(_.keys(this.inputRefs), key => _.keys(errors).includes(key));
-                                const focusInput = this.inputRefs[focusKey];
-                                if (focusInput.focus && typeof focusInput.focus === 'function') {
-                                    focusInput.focus();
-                                }
-
-                                // We substract 10 to scroll slightly above the input
-                                if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
-                                    focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
-                                }
-                            }}
-                            containerStyles={[styles.mh0, styles.mt5, styles.flex1]}
-                            enabledWhenOffline={this.props.enabledWhenOffline}
-                            isDangerousAction={this.props.isDangerousAction}
-                        />
+                    <ScrollContext.Consumer>
+                        {({scrollViewRef}) => (
+                            <View style={[this.props.style]}>
+                                {this.childrenWrapperWithProps(this.props.children)}
+                                {this.props.isSubmitButtonVisible && (
+                                <FormAlertWithSubmitButton
+                                    buttonText={this.props.submitButtonText}
+                                    isAlertVisible={_.size(this.state.errors) > 0 || Boolean(this.getErrorMessage()) || !_.isEmpty(this.props.formState.errorFields)}
+                                    isLoading={this.props.formState.isLoading}
+                                    message={_.isEmpty(this.props.formState.errorFields) ? this.getErrorMessage() : null}
+                                    onSubmit={this.submit}
+                                    onFixTheErrorsLinkPressed={() => {
+                                        const errors = !_.isEmpty(this.state.errors) ? this.state.errors : this.props.formState.errorFields;
+                                        const focusKey = _.find(_.keys(this.inputRefs), key => _.keys(errors).includes(key));
+                                        const focusInput = this.inputRefs[focusKey];
+                                        if (focusInput.focus && typeof focusInput.focus === 'function') {
+                                            focusInput.focus();
+                                        }
+
+                                        // We substract 10 to scroll slightly above the input
+                                        if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
+                                            focusInput.measureLayout(scrollViewRef.current, (x, y) => scrollViewRef.current.scrollTo({y: y - 10, animated: false}));
+                                        }
+                                    }}
+                                    containerStyles={[styles.mh0, styles.mt5, styles.flex1]}
+                                    enabledWhenOffline={this.props.enabledWhenOffline}
+                                    isDangerousAction={this.props.isDangerousAction}
+                                />
+                                )}
+                            </View>
                         )}
-                    </View>
+                    </ScrollContext.Consumer>
                 </ScrollViewWithContext>
             </>
         );

```

**Comment by dhairyasenjaliya** [comment] 2023-01-02 10:54
@allroundexperts your ultimate fix will definitely fail on the native platform since you're suggesting to take value directly from `scrollViewRef` which will be different (x,y) values than the actual `this.form(x,y)` results in regression on the native platform will create jump effect on every click and on second click the from will stuck on top 



https://user-images.githubusercontent.com/47522946/210221831-19c9f4c6-f849-4574-a798-b2035f039ea7.mp4

**Comment by allroundexperts** [comment] 2023-01-02 16:54
@dhairyasenjaliya I'm not sure if this regression was ever fixed correctly. Even on native, `this.form` points to `ref` of the class component. When supplying it to `measureLayout`, we're getting this error:
<img width="378" alt="Screenshot 2023-01-02 at 9 50 35 PM" src="https://user-images.githubusercontent.com/30054992/210259699-340672a1-cbc6-4de5-8386-98c495b3c442.png">
As such, the `this.form.scrollTo` is undefined on native as well. Would be better to remove this functionality entirely since this is not available on any platform.

**Comment by ali-thowfeek** [comment] 2023-01-02 20:30
@allroundexperts 
As per the doc of `<ScrollViewWithContext />`:
```
<ScrollViewWithContext /> can be used as a direct replacement for <ScrollView />
```
So its `ref` was supposed to have `measureLayout` and `scrollTo` functions.

But the issue is that the `ref` is not forwarded to the underlying `ScrollView`. So right now the `ref` is bound to the wrapping component itself, which obviously doesn't have `measureLayout` or `scrollTo` causing the issue.

**Comment by fedirjh** [comment] 2023-01-02 20:57
### Proposal

I agree with @ali-thowfeek approach , the root cause is that the ref used isn't forwarded , and based on this comment https://github.com/Expensify/App/issues/11391#issuecomment-1339790828 , I think it is wise to use the ref provided by `ScrollViewWithContext` , after all the `ScrollContext` utility is to provide a ref that can be used by other children .
Here is an implementation in [/src/components/Picker/index.js](https://github.com/Expensify/App/blob/12fad4146b71a199e96d040e93b72cea4c719bd5/src/components/Picker/index.js#L196) that uses the provided ref `this.context.scrollViewRef`

https://github.com/Expensify/App/blob/12fad4146b71a199e96d040e93b72cea4c719bd5/src/components/Picker/index.js#L196-L198

We can use same implementation for the Form.js

```diff
diff --git a/src/components/Form.js b/src/components/Form.js
index f3f4a5a0cf..c8d77412b4 100644
--- a/src/components/Form.js
+++ b/src/components/Form.js
@@ -10,7 +10,7 @@ import * as FormActions from '../libs/actions/FormActions';
 import * as ErrorUtils from '../libs/ErrorUtils';
 import styles from '../styles/styles';
 import FormAlertWithSubmitButton from './FormAlertWithSubmitButton';
-import ScrollViewWithContext from './ScrollViewWithContext';
+import ScrollViewWithContext, {ScrollContext} from './ScrollViewWithContext';
 
 const propTypes = {
     /** A unique Onyx key identifying the form */
@@ -254,7 +254,6 @@ class Form extends React.Component {
                     style={[styles.w100, styles.flex1]}
                     contentContainerStyle={styles.flexGrow1}
                     keyboardShouldPersistTaps="handled"
-                    ref={el => this.form = el}
                 >
                     <View style={[this.props.style]}>
                         {this.childrenWrapperWithProps(this.props.children)}
@@ -273,9 +272,9 @@ class Form extends React.Component {
                                     focusInput.focus();
                                 }
 
-                                // We substract 10 to scroll slightly above the input
-                                if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function') {
-                                    focusInput.measureLayout(this.form, (x, y) => this.form.scrollTo({y: y - 10, animated: false}));
+                                // We subtract 10 to scroll slightly above the input
+                                if (focusInput.measureLayout && typeof focusInput.measureLayout === 'function' && this.context && this.context.scrollViewRef) {
+                                    focusInput.measureLayout(this.context.scrollViewRef, (x, y) => this.context.scrollViewRef.scrollTo({y: y - 10, animated: false}));
                                 }
                             }}
                             containerStyles={[styles.mh0, styles.mt5, styles.flex1]}
@@ -292,6 +291,7 @@ class Form extends React.Component {
 
 Form.propTypes = propTypes;
 Form.defaultProps = defaultProps;
+Form.contextType = ScrollContext;
 
 export default compose(
     withLocalize,
```

**Comment by thesahindia** [comment] 2023-01-03 11:11
Sorry for the delay, I will look into this in a few hours.

**Comment by ali-thowfeek** [comment] 2023-01-03 14:37
### Proposal 2
Guys, as far I looked `<ScrollViewWithContext>` would only make sense when there is a `<Picker>` component as a child. If not we could simply swap it to a `<ScrollView>` which I believe would give us a performance boost because `<ScrollViewWithContext>` uses a `Provider` and it has a state `contentOffsetY` as the Provider value which is constantly updated `onScroll`. Which ultimately would re-render on each update  as per the React [documentation](https://reactjs.org/docs/context.html#contextprovider):

> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes. The propagation from Provider to its descendant consumers (including [.contextType](https://reactjs.org/docs/context.html#classcontexttype) and [useContext](https://reactjs.org/docs/hooks-reference.html#usecontext)) is not subject to the shouldComponentUpdate method, so the consumer is updated even when an ancestor component skips an update.

So I propose that we have a Prop on `<Form>` as `useScrollViewWithContext` and use the appropriate component: `<ScrollViewWithContext>` or `<ScrollView>` depending on its value. And we could set `useScrollViewWithContext` default to be `false` also.

Also this would fix the issue with `scrollToOverflowEnabled` on iOS.

what do you think @fedirjh ?

**Comment by aldo-expensify** [comment] 2023-01-03 15:00
Just coming back from OOO.

I introduced that bit of code (measureLayout) here: https://github.com/Expensify/App/pull/13499 when trying to redo something another reverted PR did.

Thanks for the investigation so far. I'll make this internal meanwhile to catch up with the conversation and decide what to do next.

**Comment by thesahindia** [comment] 2023-01-03 15:02
@aldo-expensify, actually it is a regression from https://github.com/Expensify/App/pull/13514

**Comment by ali-thowfeek** [comment] 2023-01-03 15:10
@thesahindia I beg to differ 🤷‍♂️ as my proposal does exactly that.

**Comment by thesahindia** [comment] 2023-01-03 15:24
I don't think I understand how that will address the expected results. Does your second proposal also uses the code from the first proposal?
Just a note that this issue is now internal, so it's not open for proposal anymore.

**Comment by ali-thowfeek** [comment] 2023-01-03 15:29
Well, technically i posted my 2nd proposal before it was made internal 😀.

**Comment by ali-thowfeek** [comment] 2023-01-03 15:32
@thesahindia  And to elaborate on my 2nd: i proposed that we should pass in a prop called `useScrollViewWithContext` to the `Form` component so that if its false, we will use either `ScrollView`, true then `ScrollViewWithContext` which does solve both the problems. We will be passing `useScrollViewWithContext={true}` when there is a <Picker> component within the children. I hope this clears it out for you. What do you think?

**Comment by thesahindia** [comment] 2023-01-03 16:03
Still not seeing how it will address the expected results. If we use `ScrollView` in the `Form` component and there is a picker in the children, then it will be covered when you tap on it (`ScrollViewWithContext` is needed to handle that)
If we use `ScrollViewWithContext` in the `Form` (which we are using right now) the current issue will still exist. Makes sense?

**Comment by ali-thowfeek** [comment] 2023-01-03 16:10
> Still not seeing how it will address the expected results. If we use `ScrollView` in the `Form` component and there is a picker in the children, then it will be covered when you tap on it (`ScrollViewWithContext` is needed to handle that)
> If we use `ScrollViewWithContext` in the `Form` (which we are using right now) the current issue will still exist. Makes sense? 
> 

@thesahindia well, that is why i proposed to have a prop, which we will be passing depending on the children. Basically the value we pass into the prop will decide which component to use. Shall I post the code how it should be implemented? I still don't see a problem with this though. But I could be wrong 😃

**Comment by ali-thowfeek** [comment] 2023-01-03 17:40
@thesahindia 
I don't wanna drag this on.. so i'll update the code what I meant here. I hope its clear. Actually its my fault, I should have been more clearer 😞

**Form.js**
``` diff
    render() {
+        const Scroll = this.props.useScrollViewWithContext ? ScrollViewWithContext : ScrollView;

        return (
            <>
-               <ScrollViewWithContext
+               <Scroll
                    style={[styles.w100, styles.flex1]}
                    contentContainerStyle={styles.flexGrow1}
                    keyboardShouldPersistTaps="handled"
+                   scrollToOverflowEnabled={this.props.useScrollViewWithContext}
                    ref={el => this.form = el}
                >
                ...
                ...
                ...
-               </ScrollViewWithContext>
+              </Scroll>
```
**ScrollViewWithContext.js**
``` diff
        render() {
        return (
            <ScrollView
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...this.props}
-                ref={this.scrollViewRef}
+                ref={this.props.innerRef || this.scrollViewRef}
                onScroll={this.setContextScrollPosition}
                scrollEventThrottle={this.props.scrollEventThrottle || MIN_SMOOTH_SCROLL_EVENT_THROTTLE}
                scrollToOverflowEnabled
            >
                <ScrollContext.Provider
                    value={{
-                        scrollViewRef: this.scrollViewRef,
+                        scrollViewRef: this.props.innerRef || this.scrollViewRef,
                        contentOffsetY: this.state.contentOffsetY,
                    }}
                >
```
``` diff
- export default ScrollViewWithContext;
+ export default React.forwardRef((props, ref) => <ScrollViewWithContext innerRef={ref} {...props}/>);
```

As there is currently only one place `ScrollViewWithContext` is actually utilised here:
https://github.com/Expensify/App/blob/12fad4146b71a199e96d040e93b72cea4c719bd5/src/components/Picker/index.js#L196-L198
We will pass this prop to the encompassing `Form` component of the above:
``` diff
<Form
+    useScrollViewWithContext
    ....
    ....
    >
```
And in other instances we will simply leave it as it is. Hope this clears it up.

**Comment by ali-thowfeek** [comment] 2023-01-03 18:56
@thesahindia 
Yep. I see the problem now. In a form like this we need both 🤯 I totally agree my solution wouldn't work in this case

**Comment by aldo-expensify** [comment] 2023-01-06 21:14
Sorry I haven't been able to get back to this. I'll have to leave it for Monday.

**Comment by aldo-expensify** [comment] 2023-01-10 00:00
No updates again, I'll try tomorrow 😢

**Comment by aldo-expensify** [comment] 2023-01-10 22:24
@thesahindia why is [this proposal](https://github.com/Expensify/App/issues/13909#issuecomment-1368811645) downvoted? It seems to fix the issue, draft PR: https://github.com/Expensify/App/pull/14209

Regarding this comment: https://github.com/Expensify/App/issues/13909#issuecomment-1368838061 , I wouldn't say that the [this proposal](https://github.com/Expensify/App/issues/13909#issuecomment-1368811645)  causes that regression because that is the behaviour we had before the PR https://github.com/Expensify/App/pull/13514 broke this. That behaviour is fine IMO.

From reading further proposals, this one also seems to be fixing the reference issue, but in a better way? https://github.com/Expensify/App/issues/13909#issuecomment-1368819171 I say a better way because I understand that then we can use the ref on `ScrollViewWithContext` the same way we would with `ScrollView`.

I understand the possible performance issues mentioned here https://github.com/Expensify/App/issues/13909#issuecomment-1369841204 but maybe we should measure and see if it is a real problem before doing anything.



Anyway, there is a lot of information here and thanks a lot for all the discussion/investigation done so far!. I'll come back to it tomorrow because it is the end of my day.

**Comment by thesahindia** [comment] 2023-01-11 21:06
> Regarding this comment: https://github.com/Expensify/App/issues/13909#issuecomment-1368838061 , I wouldn't say that https://github.com/Expensify/App/issues/13909#issuecomment-1368811645 causes that regression because that is the behaviour we had before the PR https://github.com/Expensify/App/pull/13514 broke this.

No this behaviour wasn't present before https://github.com/Expensify/App/pull/13514 

This is the result we get after using the solution suggested at https://github.com/Expensify/App/issues/13909#issuecomment-1368811645 -

https://user-images.githubusercontent.com/83179295/211917338-e6cfea51-ad43-4acf-bd05-bcb965cde43f.mov

**Comment by thesahindia** [comment] 2023-01-11 21:20
> this one also seems to be fixing the reference issue, but in a better way? https://github.com/Expensify/App/issues/13909#issuecomment-1368819171 I say a better way because I understand that then we can use the ref on ScrollViewWithContext the same way we would with ScrollView.

We will get error on ios when we tap on the picker (if it's at bottom)
I added some top margin to repro this


https://user-images.githubusercontent.com/83179295/211919533-87ae7b68-a3d1-45d7-9636-b3590d0cdb79.mov

**Comment by aldo-expensify** [comment] 2023-01-12 13:18
> > Regarding this comment: [#13909 (comment)](https://github.com/Expensify/App/issues/13909#issuecomment-1368838061) , I wouldn't say that [#13909 (comment)](https://github.com/Expensify/App/issues/13909#issuecomment-1368811645) causes that regression because that is the behaviour we had before the PR #13514 broke this.
> 
> No this behaviour wasn't present before #13514
> 
> This is the result we get after using the solution suggested at [#13909 (comment)](https://github.com/Expensify/App/issues/13909#issuecomment-1368811645) -
> 
>  Screen.Recording.2023-01-12.at.2.31.13.AM.mov

Ahh, I see it now in IOS, thanks!

**Comment by aldo-expensify** [comment] 2023-01-12 19:01
> I think we can let [chrispader](https://github.com/chrispader) handle the regression from that PR if we are still figuring out the solution for it. The regression period was still active on that PR.

Sounds like a good idea to me. @chrispader do you mind helping with this investigation?

**Comment by aldo-expensify** [comment] 2023-01-18 21:12
DM's @chrispader in slack to see if we can get some help from him. Otherwise, tomorrow I'll start having a look at this again

**Comment by chrispader** [comment] 2023-01-19 09:43
# Proposal

The ref to `ScrollViewWithContext` was not forwarded to `ScrollView`, which is why the error `Uncaught TypeError: Cannot read properties of undefined (reading ‘left’)` shows up.

# Proposal

**ScrollViewWithContext.js:**
```diff
@@ -22,7 +22,7 @@ class ScrollViewWithContext extends React.Component {
         this.state = {
             contentOffsetY: 0,
         };
-        this.scrollViewRef = React.createRef(null);
+        this.scrollViewRef = this.props.innerRef || this.React.createRef(null);
 
         this.setContextScrollPosition = this.setContextScrollPosition.bind(this);
     }
@@ -58,7 +58,11 @@ class ScrollViewWithContext extends React.Component {
 }
 ScrollViewWithContext.propTypes = propTypes;
 
-export default ScrollViewWithContext;
+export default React.forwardRef((props, ref) => (
+    // eslint-disable-next-line react/jsx-props-no-spreading
+    <ScrollViewWithContext {...props} innerRef={ref} />
+));
+
 export {
     ScrollContext,
 };
```

**Comment by chrispader** [comment] 2023-01-19 11:08
Turns out that (either some pages have changed since i implemented this feature or) i missed some pages that have `<StatePicker />` or `<LocalePicker />` components instead of the regular `<Picker />`.

I think these changes also fit pretty well into a PR on this regression, so i'd just add those fixes too

**Comment by chrispader** [comment] 2023-01-19 11:55
> By default, scrollToOverflowEnabled should be false. This is useful, when there's a picker at the very bottom of the page. In this case, scrollToOverflowEnabled on the ScrollView should be set to true, otherwise scrolling to the picker won't work.

Here's a comparison on that: (i added some extra space between the picker and the rest of the form to illustrate this)

`scrollToOverflowEnabled` set to `false`:

https://user-images.githubusercontent.com/20173411/213435878-b871b3cb-3b79-4f3d-a280-9b047f618c81.mp4

`scrollToOverflowEnabled` set to `true`:

https://user-images.githubusercontent.com/20173411/213435955-4732d16c-d2dd-4033-b2ab-5cbf21aa2a0d.mp4

**Comment by bfitzexpensify** [comment] 2023-02-07 05:43
Appreciate the reminder @thesahindia! Strange that the bot didn't highlight this as being pushed to prod. 

Upwork job had expired so I've sent new offers out to yourself and @dhairyasenjaliya

**Comment by bfitzexpensify** [comment] 2023-02-07 23:51
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@thesahindia / @aldo-expensify] The PR that introduced the bug has been identified. Link to the PR:
 [@thesahindia / @aldo-expensify] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@thesahindia / @aldo-expensify] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@bfitzexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by bfitzexpensify** [comment] 2023-02-09 00:18
>A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

Agreed. Thank you for the other links @thesahindia!

Checklist complete, closing issue

**Closed by bfitzexpensify** 2023-02-09 00:18 UTC
Labels: Daily, Internal, Bug
