### ISSUE TITLE
Second user is disappeared when chosing first one

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23685] opened 2023-07-26 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and click on search
2. Find two users that has nearly the same username. (first one ...@gmail.com, second one should be the same but should be ...@gmail.co   )
3. Write something to both of them and choose any message as "mark as unread"
4. Click on plus icon > New group
5. Here you can see the users as contacts. And choose one of them and the other one will be disappeared.

## Expected Result: 
Second user shouldn't get disappeared when choosing first one
## Actual Result: 
Second user is disappeared when choosing first one

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (37).webm](https://github.com/Expensify/App/assets/43996225/706e6afd-7c95-4842-8541-4a4815b1a9f3)

https://github.com/Expensify/App/assets/43996225/15f47607-ad74-4e2c-8cc4-8de64515fb2d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690261604160939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-07-26 20:08
Dupe of https://github.com/Expensify/App/issues/23503

**Closed by garrettmknight** 2023-07-26 20:08 UTC
Labels: Daily, Bug

**Comment by muxriddinmuqimov77** [comment] 2023-07-27 06:11
> Dupe of #23503

@garrettmknight  Do you think the root cause is the same?

**Comment by garrettmknight** [comment] 2023-07-27 07:57
Yep, feel free to test after that issue goes to staging though.
