### ISSUE TITLE
[Hold for payment 2023-07-05][$1000] copy to clipboard tooltip is missing in Contact methods

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21074] opened 2023-06-19 19:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Profile > Contact methods
2. hover on clipboard icon
## Expected Result: 
should show copy to clipboard tooltip
## Actual Result: 
does not show copy to clipboard tooltip

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/239e7e63-d265-4509-84f9-b9f7c72957da

https://github.com/Expensify/App/assets/43996225/85e0f75b-ab34-49ae-a768-2bd29ac4449e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686567859832639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014363b93cc961b40f</li>
        <li>Upwork Job ID: 1671204270043312128</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-20 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip doesn't show in the contact method copy text to clipboard.

### What is the root cause of that problem?
CopyTextToClipboard uses PressableWithDelayToggle. In PressableWithDelayToggle, we have a Tooltip that wraps a React.Fragment.
https://github.com/Expensify/App/blob/f0c663126a625d7964e724a171ed3854ed84b519/src/components/PressableWithDelayToggle.js#L90-L128

Why doesn't it work? Tooltip internally uses Hoverable. To make Hoverable work, the children should be able to accept both the `onMouseEnter` and `onMouseLeave` props, which is not the case for React.Fragment. React.Fragment only accepts `key` props.

### What changes do you think we should make in order to solve the problem?

1. Remove the fragment
2. Switch Tooltip and PressableView position
3. Additionally, remove containerStyles from Tooltip

**Comment by zanyrenney** [comment] 2023-06-20 17:11
Yep fair, i can reproduce and this seems like a sensible addition to contact methods. though should it only apply to email addresses or also to phone numbers seeing as both will be available as contact methods?

**Comment by kevinleerongordon** [comment] 2023-06-20 18:12
Here is my suggestion:

To fix the issue where the copy to clipboard tooltip is not displaying, you can try the following steps:

Verify Tooltip Configuration: Ensure that the text prop provided to the Tooltip component contains the appropriate value for the copy to clipboard functionality. Double-check that props.tooltipTextChecked and props.tooltipText are correctly set.

Check Button State: Confirm that the isDelayButtonStateComplete prop is correctly indicating the state of the button. If this prop is not being set or evaluated correctly, it may impact the display of the tooltip.

Review Icon Configuration: Make sure that props.iconChecked and props.icon are set correctly and that the icons are being rendered conditionally based on the button state.

Inspect Component Styling: Check if there are any conflicting or overriding styles applied to the Tooltip component or its parent components. Ensure that the containerStyles prop provided to the Tooltip component is not interfering with the tooltip's visibility.

Verify Accessibility Properties: Double-check the accessibility properties such as focusable and accessibilityLabel provided to the Pressable component. These properties should accurately reflect the button's functionality and state.

<PressableView style={[styles.flexRow, ...props.styles]} onPress={updatePressState}>
  <Tooltip containerStyles={[styles.flexRow]} text={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText}>
    <>
      <Text suppressHighlighting style={props.textStyles}>
        {props.isDelayButtonStateComplete && props.textChecked ? props.textChecked : props.text}&nbsp;
      </Text>
      <Pressable ref={props.innerRef} focusable accessibilityLabel={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText} onPress={updatePressState}>
        {({ hovered, pressed }) => (
          <>
            {props.icon && (
              <Icon
                src={props.isDelayButtonStateComplete ? props.iconChecked : props.icon}
                fill={StyleUtils.getIconFillColor(getButtonState(hovered, pressed, props.isDelayButtonStateComplete))}
                style={props.iconStyles}
                width={variables.iconSizeSmall}
                height={variables.iconSizeSmall}
              />
            )}
          </>
        )}
      </Pressable>
    </>
  </Tooltip>
</PressableView>

**Comment by staticGuru** [comment] 2023-06-20 18:47
@MelvinBot 

I can able to replicate the issues and I find the reason for this issue.

**Issue:**
 Can't able to see the tooltip on the copy to clipboard in the contact methods sections.
 
 **Reason for the issues**
Actually, Tooltip components can only support single children only. So, here both the text component and icon component are hidden in the tooltip's position.

**Fixes**
Here, I fix the issues in the following ways:
I treat the children component as the whole text with `<span> `tag.
```
<span>
<-- text component -->
<-- icon component -->
</span>
```
**Issues fixes link**
https://www.loom.com/share/b614241ddc2c436dbbb093da7eeb16e6?sid=d9ecce4e-31e1-4cf2-a434-3f8d0904c961




**Contributor details**
Your Expensify account email: vigneshguru274@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010f381f7a58a7ba26

**Comment by staticGuru** [comment] 2023-06-20 18:49
**Contributor details**
Your Expensify account email:vigneshguru274@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010f381f7a58a7ba26

**Comment by devhd9** [comment] 2023-06-20 19:51
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
 Copy to clipboard tooltip is missing in Contact methods.

**What is the root cause of that problem?**
CopyTextToClipboard uses PressableWithDelayToggle. In PressableWithDelayToggle, we have a Tooltip that wraps a react fragment(<></>). Tooltip component uses Hoverable. To make Hoverable work, the children should be able to accept both the onMouseEnter and onMouseLeave props. Since we are using Fragment, props cannot be passed except key prop.

```
<PressableView 
     style={[styles.flexRow, ...props.styles]} 
     onPress={updatePressState} 
 > 
     <Tooltip 
         containerStyles={[styles.flexRow]} 
         text={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText} 
     > 
         <> 
             <Text 
                 suppressHighlighting 
                 style={props.textStyles} 
             > 
                 {props.isDelayButtonStateComplete && props.textChecked ? props.textChecked : props.text} 
                 &nbsp; 
             </Text> 
             <Pressable 
                 ref={props.innerRef} 
                 focusable 
                 accessibilityLabel={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText} 
                 onPress={updatePressState} 
             > 
                 {({hovered, pressed}) => ( 
                     <> 
                         {props.icon && ( 
                             <Icon 
                                 src={props.isDelayButtonStateComplete ? props.iconChecked : props.icon} 
                                 fill={StyleUtils.getIconFillColor(getButtonState(hovered, pressed, props.isDelayButtonStateComplete))} 
                                 style={props.iconStyles} 
                                 width={variables.iconSizeSmall} 
                                 height={variables.iconSizeSmall} 
                             /> 
                         )} 
                     </> 
                 )} 
             </Pressable> 
         </> 
     </Tooltip> 
 </PressableView>
 ```

**What changes do you think we should make in order to solve the problem?**
We can simply use Text component instead of Fragment.

```
<PressableView 
     style={[styles.flexRow, ...props.styles]} 
     onPress={updatePressState} 
 > 
     <Tooltip 
         containerStyles={[styles.flexRow]} 
         text={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText} 
     > 
         <Text> 
             <Text 
                 suppressHighlighting 
                 style={props.textStyles} 
             > 
                 {props.isDelayButtonStateComplete && props.textChecked ? props.textChecked : props.text} 
                 &nbsp; 
             </Text> 
             <Pressable 
                 ref={props.innerRef} 
                 focusable 
                 accessibilityLabel={props.isDelayButtonStateComplete ? props.tooltipTextChecked : props.tooltipText} 
                 onPress={updatePressState} 
             > 
                 {({hovered, pressed}) => ( 
                     <> 
                         {props.icon && ( 
                             <Icon 
                                 src={props.isDelayButtonStateComplete ? props.iconChecked : props.icon} 
                                 fill={StyleUtils.getIconFillColor(getButtonState(hovered, pressed, props.isDelayButtonStateComplete))} 
                                 style={props.iconStyles} 
                                 width={variables.iconSizeSmall} 
                                 height={variables.iconSizeSmall} 
                             /> 
                         )} 
                     </> 
                 )} 
             </Pressable> 
         <Text/> 
     </Tooltip> 
 </PressableView>
 ```

**Comment by devhd9** [comment] 2023-06-20 19:53
Your Expensify account email: hetdesai068@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014f4ef0d1f901cc35

**Comment by devhd9** [comment] 2023-06-20 20:09
Contributor details
Your Expensify account email: hetdesai068@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014f4ef0d1f901cc35

**Comment by narefyev91** [comment] 2023-06-21 11:53
Proposal of @chiragxarora https://github.com/Expensify/App/issues/21074#issuecomment-1597649518 looks good for me - it's correctly indicate the issue - and mostly suggesting to have the same structure of component which we have before inside CopyTextToClipboard
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by bondydaa** [comment] 2023-06-23 20:33
sounds good!

**Comment by bondydaa** [comment] 2023-06-28 22:32
ah i think there was an extra space in the PR when linking the issue
<img width="808" alt="image" src="https://github.com/Expensify/App/assets/4073354/b6d63f8a-44b6-464c-af29-a1c13c9d0561">

**Comment by bondydaa** [comment] 2023-06-28 22:35
trying to figure out what we need to do here, @zanyrenney do you know? can we retrigger any of the automation now that I fixed the link?

**Comment by gadhiyamanan** [comment] 2023-06-29 14:15
@chiragxarora if you change the linking in PR, it won't make any difference as it is already in production. we have to update it manually.

**Comment by bondydaa** [comment] 2023-06-29 14:58
okay i believe all that happens is we add the `[hold]` to the title, add the `awaiting payment` label so i just manually did those things. zany will send payment next week assuming no regressions.

**Comment by zanyrenney** [comment] 2023-07-10 10:52
Hey @chiragxarora I don't see that you applied for the job on Upwork as was requested in [this comment](https://github.com/Expensify/App/issues/21074#issuecomment-1604918068). I am manually sending you an invite.

Also invited the reporter - [Manan Gadhiya](https://github.com/gadhiyamanan). 

I believe @narefyev91 is paid outside Upwork! Let me know if I've gotten any of that wrong!

**Comment by zanyrenney** [comment] 2023-07-10 10:54
Thank you!

**Comment by gadhiyamanan** [comment] 2023-07-10 10:54
@zanyrenney applied, thanks!

**Comment by zanyrenney** [comment] 2023-07-10 10:55
Thanks both! Just getting this error when trying to move forward on Upwork: 
<img width="570" alt="2023-07-10_11-54-36" src="https://github.com/Expensify/App/assets/56830058/30849b4a-20f9-4af0-8f3a-711e9d4cf883">

Hang tight whilst i figure it out, please!

**Comment by zanyrenney** [comment] 2023-07-11 09:48
@bondydaa please can you un-assign and then re-assign @chiragxarora as I keep getting this error and I think it might be due to the automation as @chiragxarora said.

Thanks!

**Comment by bondydaa** [comment] 2023-07-12 21:51
hmm sorry why does it matter who unassigns/re-assigns? pretty sure zany could have and it would have worked just fine too.

**Comment by zanyrenney** [comment] 2023-07-14 09:23
Paid for Manan and Chirag, other contributor paid outside GH so we are all set here, closing!

**Closed by zanyrenney** 2023-07-14 09:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
