### ISSUE TITLE
Login-Login with Spanish language for gmail user shows Spanish content briefly only

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49265] opened 2024-09-16 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Set site to spanish
3. Login with new expensifail account
4. Note the site header text ( inbox )and all details are in Spanish
5. Tap profile icon and sign out
6. Note Login page remains in Spanish
7. Login with new gmail account
8. Note initially header text inbox is displayed in Spanish and then changed to English
9. Tap profile icon and tap sign out
10. Note login page is in English

## Expected Result:
Login with Spanish language, content should not change to English and in Spanish app must be displayed.

## Actual Result:
Login with Spanish language for gmail user shows Spanish content briefly & changes to English but for expensifail users content remains in Spanish.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/2ea37ae7-9632-4364-bb7d-c4ad533996fe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2024-09-18 15:21
So the reproduction steps are missing the fact that the default settings for language are set in the account. So the initial default is english, which will override the browser settings. 

Because of this, it is not a bug and I am closing. Thanks!

**Closed by CortneyOfstad** 2024-09-18 15:21 UTC
Labels: Daily, Bug
