### ISSUE TITLE
DEV : Clicking task completed checkbox multiple times shows error on LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21762] opened 2023-06-27 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
precondition :  Tested on Dev v1.3.32-5
1.  On user A,  go to '+" -> new group
2. pick members including user B and others -> next
3.  go to just created group page
4. go to '+' inside group page -> assign task -> add name
5. leave the assignee and share to default.
6. Now on task page, mark as complete.
7. On user B, go to created group page ( not task)
8. Notice that there's a task created chat with tickmark/check box and a reply chat
9.  IMPORTANT STEP, to go reply chat -> task page and exit from there. Repeat step 7.
10. Now click on checkbox multiple times and notice on LHN, ( task chat with red dot appears and disappears)
## Expected Result: 
Since we can't mark the task as complete from invited or secondary user ( those who haven't created task, but are the members of the task), check box should be made disabled on group chat .
OR,
task chat with red dot should bot appear/disappeat from LHN
## Actual Result: 
Clicking task completed checkbox multiple times shows error on LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Dev v1.3.32-5
**Reproducible in production?:** Dev v1.3.32-5
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7e2c4b34-5c66-4b71-b0ca-9966e6d2c3ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687781637575339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-06-28 05:34
I would suggest we hold this issue or close it as we are redesigning task details page.
https://github.com/Expensify/App/issues/19330

**Comment by ashimsharma10** [comment] 2023-06-28 07:11
@jeet-dhandha please notice, it's not about the task details page. Rather it's about the checkbox

**Comment by lschurr** [comment] 2023-06-28 15:54
Hey @stitesExpensify - Assigned Eng for another pair of eyes. Do you think this needs to be put on hold or closed or is there something to fix?

**Comment by lschurr** [comment] 2023-06-30 20:33
Hiya @stitesExpensify - any chance you could take a peek at this one? I'll also bump the Slack thread for more eyes.

**Comment by stitesExpensify** [comment] 2023-06-30 20:48
Sorry to tag you twice in one day @thienlnam but this is also task related. From the looks of the video, the task completed message either isn't being broadcast to the other clients, or the frontend isn't handling it properly. If it's just the front end we can add the external label, but if we aren't pushing the update out then this needs to be internal

**Comment by thienlnam** [comment] 2023-06-30 21:27
We can probably close this - the problem is the person who is completing the task doesn't have permission so the command is failing. We're working on adding better error notifications in here https://github.com/Expensify/App/issues/21579 so this should not be a confusing flow anymore

**Comment by lschurr** [comment] 2023-07-03 15:29
Cool, going to close.

**Closed by lschurr** 2023-07-03 15:29 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
