### ISSUE TITLE
[HOLD for payment 2023-10-31] [$500] Chat - The New Line Marker does not appear for unread first message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29173] opened 2023-10-10 11:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696727757953619

## Action Performed:
1. Send a message to User A, with no previous chat history with the sender.
2. Go to User A and notice the LHN is highlighted
3. Open the chat. Notice there is no New Line marker

## Expected Result:
The New Line Marker appears for unread message

## Actual Result:
The New Line Marker does not appear for unread first message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/46805bcd-d471-4488-811d-70e5c2a14d0c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/882fec3f-d4b4-4b7d-9e0e-01730fa0f3d9

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/53f9e428-677d-416e-861f-6850a5cb13a0

</details> 

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/06c127db-7f2a-4ee6-99ec-a31c02ff6776

</details> crashed

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/780ed87f-3449-46e6-b462-7407ce5c155f

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/1a28fb10-bba4-47c5-9405-659e60f9148c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc658e3dfbf9bd3b</li>
        <li>Upwork Job ID: 1711711928838750208</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>chamysoftware | Contributor | 27163409</li>
<li>daveSeife | Reporter | 27163410</li>
</ul></li>
    </ul>
</details>

**Comment by chamysoftware** [comment] 2023-10-10 14:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When userA receives a message from userB for the first time, the new message marker is missing.

### What is the root cause of that problem?
We're checking if the report action is unread based on the report's last read time here
https://github.com/Expensify/App/blob/424786bae6b461e12d2f738be185374dc6866710/src/pages/home/report/ReportActionsList.js#L99-L101

But the last read time is undefined for a new report (new message coming from a new sender).


### What changes do you think we should make in order to solve the problem?
We need to handle this case in the above function. We need to consider it as a new message in case if the report's `lastReadTime` is undefined

```
  100 function isMessageUnread(message, lastReadTime) {
+ 101    if (!lastReadTime) {
+ 102       return Boolean(!isCreatedAction(message));
+ 103    }
+ 104 
  105    return Boolean(message && lastReadTime && message.created && lastReadTime < message.created);
  106 }
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by srikarparsi** [comment] 2023-10-12 16:30
Cool, looks good to me as well

**Comment by JmillsExpensify** [comment] 2023-10-17 20:59
Still working through the PR

**Comment by JmillsExpensify** [comment] 2023-10-24 22:48
@narefyev91 mind kicking off the BZ checklist? In the meantime, payment summary as follows:

 - Issue reporter: @daveSeife $50
 - Contributor: @chamysoftware $500

**Comment by narefyev91** [comment] 2023-10-25 06:46
- The PR that introduced the bug has been identified. Link to the PR - it was not a regression - just missing functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by JmillsExpensify** [comment] 2023-11-01 15:23
Thanks for that! I'll get started on the payments now.

**Comment by JmillsExpensify** [comment] 2023-11-01 15:25
Everyone should be paid out now! Closing since no regression test is required.

**Closed by JmillsExpensify** 2023-11-01 15:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
