### ISSUE TITLE
[$250] Expense - Missing spacing between currency and amount in unapprove system message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44975] opened 2024-07-08 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- "Add approval" is enable in Workflow settings
- Admin is the approver
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to transaction thread
5. Click Approve
6. Click on the report header
7. Click Unapprove

## Expected Result:
The amount in the unapprove system message will have a space between the currency and amount

## Actual Result:
The amount in the unapprove system message does not have a space between the currency and amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8ab3e8c6-3c6c-434d-9b6e-82d0708294b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01791cd2da764f51cc</li>
        <li>Upwork Job ID: 1810328690048713566</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment] 2024-07-08 14:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-07-08 14:23
@MariaHCD  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-07-08 14:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing spacing between currency and amount in unapprove system message

### What is the root cause of that problem?
We have incorrect copy in the app

### What changes do you think we should make in order to solve the problem?
We should fix the copy here:
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/languages/en.ts#L3394

and here:
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/languages/es.ts#L3439

**Comment by MariaHCD** [comment] 2024-07-08 14:57
Not able to reproduce the issue on dev:

<img width="940" alt="Screenshot 2024-07-08 at 3 56 51 PM" 
src="https://github.com/Expensify/App/assets/12268372/ec189b97-9656-496a-81e3-19d561a90c1f">

Will try with the MYR currency

**Comment by Julesssss** [comment] 2024-07-08 15:03
Oops sorry @MariaHCD please ignore that ^

**Comment by Julesssss** [comment] 2024-07-08 15:04
I'm going to check it off the list regardless as it is a new feature, and a minor issue.

**Comment by MariaHCD** [comment] 2024-07-08 15:06
Sure, I was just about to say this doesn't need to block the deploy

**Comment by MariaHCD** [comment] 2024-07-08 15:10
Able to reproduce with MYR

<img width="470" alt="Screenshot 2024-07-08 at 4 05 39 PM" src="https://github.com/Expensify/App/assets/12268372/130e520c-f2e0-441b-a1e0-c1f71389d21a">

<img width="862" alt="Screenshot 2024-07-08 at 4 09 24 PM" src="https://github.com/Expensify/App/assets/12268372/a2999879-4fed-49ca-9bef-5314e1d07ca5">

Looks like the backend might be storing it incorrectly?

cc: @Beamanator do you have any context on the unapproved report action?

**Comment by Beamanator** [comment] 2024-07-09 14:30
Ooh that's interesting... I did just add this kind of stuff to the backend for the Unapproved report action, but I wonder if this is a bug in `Currency::format`? For that specific currency? Is MYR different than RM? What's RM?

**Comment by MariaHCD** [comment] 2024-07-09 14:39
From a quick search: 

> RM is the abbreviation for the Malaysian Ringgit, and MYR is the currency code.

So possible it's because of something with this specific currency

**Comment by zulsadiq** [comment] 2024-07-09 14:52
RM is the currency symbol so there is no space, because with £ or $ you don't need a space. Due to this line:

`unapproved ${currency}${amount}`

I'm wondering if it should be showing RM also for the initial approved message too?

I can submit a proposal to fix this if you can confirm the behaviour?

**Comment by zulsadiq** [comment] 2024-07-09 14:56
Contributor details
Your Expensify account email: zulfus@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01078c2aff6a1baa79?mp_source=share

**Comment by Beamanator** [comment] 2024-07-10 07:14
@MariaHCD let me know if you want me to take over this one, it looks like it won't be too hard to debug, I'd start by looking at what we store in the DB for the Approved report action, compare to Unapproved, and check the difference

**Comment by MariaHCD** [comment] 2024-07-10 12:56
Go for it, @Beamanator :) Thanks

**Comment by Beamanator** [comment] 2024-07-11 11:44
Ok so I created the request in MYR but my workspace default currency is `EGP` and I'm even seeing this with EGP!

<img width="1175" alt="Screenshot 2024-07-11 at 2 44 08 PM" src="https://github.com/Expensify/App/assets/3885503/81e4f4fb-ff50-4d02-9bb7-c37c6c2302eb">

**Comment by Beamanator** [comment] 2024-07-11 11:45
Also, it's pretty obvious that the currency doesn't match the amount in Unapprove 😅

**Comment by Beamanator** [comment] 2024-07-12 15:13
Hmm I gotta get back to this Monday, didn't have enough time today

**Comment by Beamanator** [comment] 2024-07-15 09:55
OOO today lawl will check tomorrow

**Comment by Beamanator** [comment] 2024-07-18 23:09
Ok I'm figuring out we somehow have this `\u00a0` "non-breaking space" in the Approved report actions' `message`, and no space in `originalMessage` 🤔

**Comment by Beamanator** [comment] 2024-07-18 23:45
Huh so when i sign out / in, it actually shows up correctly always 🙃

**Comment by Beamanator** [comment] 2024-07-19 00:40
bringing to slack - https://expensify.slack.com/archives/C03TQ48KC/p1721347465767429

**Comment by Beamanator** [comment] 2024-07-22 23:54
Waiting for thoughts in slack

**Comment by Beamanator** [comment] 2024-07-25 19:28
Merged!

**Comment by Beamanator** [comment] 2024-07-29 16:12
Auth PR deployed 4 days ago ([here](https://github.com/Expensify/Auth/pull/11720#issuecomment-2251605124)) - let's retest this now 🙏

**Comment by Beamanator** [comment] 2024-07-30 18:35
PR was deployed - @lanitochka17 can you please retest when you have a chance? 🙏

**Closed** 2024-07-31 18:37 UTC
Labels: Engineering, Daily, Internal, Bug
