### ISSUE TITLE
[$500]  Expense - "Submit" button appears for a moment and then disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34855] opened 2024-01-20 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace and added a member as employee, both of them being Expensifail accounts.
1. Go to https://staging.new.expensify.com/
2. Log in as the employee
3. Navigate to workspace chat
4. Create a money request

## Expected Result:
The "Submit" button is displayed and remains

## Actual Result:
"Submit" button appears for a moment and then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b39c355-5f23-4b47-a9c6-6e673ea5c366

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c7fe376ba6c0559</li>
        <li>Upwork Job ID: 1748760886681640960</li>
        <li>Last Price Increase: 2024-01-20</li>
    </ul>
</details>

**Comment by JeremyCroff** [comment] 2024-01-20 18:14
Do you have reference for me on how to get a VBA for test accounts so that I can reproduce this issue?

**Comment by subhampanja2** [comment] 2024-01-20 23:16
I checked the code, and found submit button disappearing due to by default policy get selected. 
And it's triggering the submit (status 1 and state 1) on initial payment request. 

If we need that submit button we need status 0 state 0

I don't have any idea about policy settings in Expensify. 

If anyone can help me how to change policy setting that will be appreciated.

**Comment by subhampanja2** [comment] 2024-01-20 23:27
Contributor details
Your Expensify account email: subhampanja28@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b33de8e7ea463064

**Comment by s-alves10** [comment] 2024-01-22 09:00
I can't reproduce this issue

**Comment by sophiepintoraetz** [comment] 2024-01-25 02:32
Thanks for confirming - closing.

**Closed by sophiepintoraetz** 2024-01-25 02:32 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
