### ISSUE TITLE
Request money - Console error shows up when opening request money page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25683] opened 2023-08-22 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24301
## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money

## Expected Result:
There is no console error

## Actual Result:
Console error shows up when opening request money page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/13350e79-9a44-4fe1-bfbc-c3b0b0ed7b6a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-22 14:26
Isn't this a wrong permission issue of mapbox sdk?

**Comment by tgolen** [comment] 2023-08-22 14:52
@hayata-suenaga Is this something you are aware of and working on?

**Comment by hayata-suenaga** [comment] 2023-08-22 14:56
@tgolen I believe once [this Web-E PR](https://github.com/Expensify/Web-Expensify/pull/38574) is deployed to production, the issue will be resolved.

**Comment by tgolen** [comment] 2023-08-22 14:59
OK, thank you. Is the plan to CP that to production, or let this stay a deploy blocker in NewDot until it's deployed?

**Comment by hayata-suenaga** [comment] 2023-08-22 15:02
Although the error messages are logged out, I don't think this is a deploy blocker. All error messages are related to the map's styling information not being able to be fetched. It just affect the Map's styling (it uses default style vs. Expensify style). But the issue will be fixed in the next deployment anyway.

@tgolen do you think we can remove `DeployBlocker` label?

**Comment by tgolen** [comment] 2023-08-22 16:35
Yeah, as long as functionality isn't affected I think it's fine. I'll close this out since the issue is resolved already.

**Closed by tgolen** 2023-08-22 16:35 UTC
Labels: DeployBlockerCash, Engineering, Hourly
