### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] [CVP] OD Navigation - Login - Multiple loading screens and animations are visible after a new user signs up

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#50182] opened 2024-10-03 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Version Number:** 9.0.44-0

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5043992&group_by=cases:section_id&group_id=327504&group_order=asc

**Email or phone of affected tester (no customers):** New User
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** Applause - Internal team

## Action Performed:
1. Navigate to https://staging.expensify.com/
2. Tap on "Organize my own expenses"
3. Input an email address that doesn't have an account yet
4. Tap on the "Get Started" button
5. Tap on the "Join" button

## Expected Result:
A single loading animation or a logo should be displayed after the user taps on "Get Started", right until the onboarding shows.

## Actual Result:
After new user taps on "Get Started", the "Join" button has to be tapped. White screen is showed, Expensify logo is visible for a short time, small "E" logo with the green background is visible for a short time, "Launching Expensify" is visible for a short time, loading spinner is visible for a short time

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ef20bbb2-b9ff-4bf7-82b1-c494ab523196

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

___

This was found when executing the newly added flows for CVP https://github.com/Expensify/Expensify/issues/412920. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843207040930164854</li>
        <li>Upwork Job ID: 1843207040930164854</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-10-04 06:55
I can't get this welcome page to load. I'll test on Monday

**Comment by Christinadobrzyn** [comment] 2024-10-07 08:29
Okay I can reproduce this. I think this can be external and let's get design on this to get an idea of what we should be showing.

**Comment by trjExpensify** [comment] 2024-10-07 19:39
CVP issues go in f1! 👍

**Comment by waterim** [comment] 2024-10-07 21:43
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by Christinadobrzyn** [comment] 2024-10-08 03:34
Hi @waterim - sounds great! I added you to the issue

**Comment by waterim** [comment] 2024-10-08 22:32
To be clear Im not sure that the expected result is a real expected result

> After new user taps on "Get Started", the "Join" button has to be tapped. White screen is showed, Expensify logo is visible for a short time, small "E" logo with the green background is visible for a short time, "Launching Expensify" is visible for a short time, loading spinner is visible for a short time

Actual result looks quite okay excepted of the one blink page:
1. the "Join" button has to be tapped - its needed for a verification if user exists or not, if its a new user "Join appears"
2. White screen is just a transition between 2 different pages in 2 different apps (from oldDot to newDot)
3. Expensify logo is a loading state for, but can't reproduce this one, only have a white screen after the join and after E logo
4. E Logo is a correct one as a loader for newDot
5. "Launching Expensify, your session is expired" - this one looks like a bug and from what I can see the response is **undefined** for the first call (actually in the network there is only one call and it has a response)
<img width="502" alt="image" src="https://github.com/user-attachments/assets/fda2a1d2-d26f-4dd6-b130-87df448edc5e">


And here after we got an undefined we are setting `signedInWithShortLivedAuthToken: null` 
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/7de9a67e-5e40-4ea9-8dce-762d05512c86">

And after we are getting a correct response with all the data, but because we had an **signedInWithShortLivedAuthToken as null** for a second we have this "session is expired" for a moment.
<img width="498" alt="image" src="https://github.com/user-attachments/assets/a185ef48-9f8b-43fd-a11b-b036d95290a3">
6. loading spinner is a correct state when we've got a new data for the **SignInWithShortLivedAuthToken**

It looks like a backend issue as we are getting an undefined for a moment after a call and all other steps are looking fine from a perspective we are making a transition from oldDot to a newDot, and we cant do this with one loader because different websites are rendering

**Comment by carlosmiceli** [comment] 2024-10-08 22:47
@waterim Hi, coming here to shed some light on what we want to fix in App 🙏 

Basically, the issue here is that we shouldn't see this screen after signing up (everything else to improve happens in the BE, I'll work on that):

<img width="293" alt="Screenshot 2024-10-08 at 7 45 44 PM" src="https://github.com/user-attachments/assets/488b3b8c-b3e9-46de-b80d-7ab5765e16cb">

Can you help us realize what's triggering that? Not sure if the fix is here or in the BE yet though.

**Comment by carlosmiceli** [comment] 2024-10-08 22:49
@waterim Oh, just read your comment, I'll look into in the BE and report back if we need to fix anything here. Thank you! 💪

**Comment by carlosmiceli** [comment] 2024-10-12 22:12
PR for adding a splash screen to replace the first white screen is ready: https://github.com/Expensify/Web-Expensify/pull/43944

Need to wait for Web-Static deployment to confirm the icon is showing up properly and we can wrap it up.

Moving to the auth issue next.

**Comment by carlosmiceli** [comment] 2024-10-14 00:05
@waterim can you help me check something? As I'm seeing, we're sending the shortLivedAuthToken from the BE successfully, but the issue seems to be that `isLoading` continues to be false and therefore it doesn't pass [this check](https://github.com/Expensify/App/blob/7a8e43e3f1bf0be2e2a1b4827b573d42e02b26ce/src/pages/LogInWithShortLivedAuthTokenPage.tsx#L39).

We don't send the `SignInWithShortLivedAuthToken` request twice, right? If it was `null`, how does it get it a second time? also, `route` already seems to have all the necessary information?
<img width="696" alt="Screenshot 2024-10-13 at 9 03 32 PM" src="https://github.com/user-attachments/assets/664b70a9-2483-467a-bc64-0b69fd19db7c">

Is it possible there's some logic to update in `getShortLivedLoginParams` that explains why it does this? Or if not, can you help me see what is it exactly that's missing from the response that would end up in `isLoading` as false?

I'm a bit new to this part of the App so let me know if I'm way off, but I'm not finding yet an issue in the BE (though there may be one, troubleshooting this even made me discover a [duplicate](https://github.com/Expensify/Web-Expensify/pull/43948) account status call).

**Comment by carlosmiceli** [comment] 2024-10-15 21:25
Small bump @waterim 🙏

**Comment by waterim** [comment] 2024-10-16 18:31
@carlosmiceli 
Okay, thank you, I see

Thats an issue with getShortLivedLoginParams function, it was updated to set **signedInWithShortLivedAuthToken: true** to run **App.openApp** and after setting **signedInWithShortLivedAuthToken: null** to ensure the user is logged out on refresh, don't know what was a point of this

>    If the user is signing in with a different account from the current app, should not pass the auto-generated login as it may be tied to the old account.
>     scene 1: the user is transitioning to newDot from a different account on oldDot.
>     scene 2: the user is transitioning to desktop app from a different account on web app.

This is the comment from there why it was added.
Im not sure we need to change it as it can brake these 2 scenarios with switching to new accounts

**Comment by carlosmiceli** [comment] 2024-10-16 19:11
@waterim interesting... but we confirm that this is a FE issue, right?

**Comment by waterim** [comment] 2024-10-16 19:23
@carlosmiceli yes, sorry for pinging you with a backend, but looks like its an FE issue, I thought its a **failureData**, but it was a **finallyData** and this blink is needed to be sure that new account will be rendered from the beginning, without showing an old data(as far as I know)

**Comment by carlosmiceli** [comment] 2024-10-16 21:03
That's no prob! Do you feel like you can take it and propose a solution? I think @blazejkustra can also give us a hand/hint here since he worked on that function in the past. 🙏

**Comment by waterim** [comment] 2024-10-17 16:47
@carlosmiceli Yes, I can try to figure it out and will be great if @blazejkustra can give us some information about this part

**Comment by carlosmiceli** [comment] 2024-10-17 18:07
@waterim that's great, thank you! Let's not to wait on @blazejkustra though in case he's too busy or OOO, but I'm sure he'll give us some insights if he has some time :)

Let me know if there's anything I can help with in the meantime!

**Comment by blazejkustra** [comment] 2024-10-21 13:00
@carlosmiceli Sorry, but I was OOO last week 😄 

> I think @blazejkustra can also give us a hand/hint here since he worked on that function in the past. 🙏

Hmm, I don't remember working on these functions 🤔 It's possible that I'm in the git blame because I migrated the file to Typescript.

**Comment by carlosmiceli** [comment] 2024-10-21 15:50
@blazejkustra Ah got it. @waterim how are things looking?

**Comment by waterim** [comment] 2024-10-21 16:53
@carlosmiceli continuing on this, no updates for now

**Comment by waterim** [comment] 2024-10-21 20:05
@carlosmiceli Do you have an idea how I can access the olddot dev environment to navigate to dev new dot?
Because its very hard to find a way to fix it without testing it actually in the dev env of the newDot

**Comment by carlosmiceli** [comment] 2024-10-21 21:27
Mmm, I'm 99% sure that there's no way to do that, right @trjExpensify? If the issue is in ND but you absolutely need to have access to OD, then maybe I should grab the ND side of this issue as well, but I'll let Tom confirm!

**Comment by carlosmiceli** [comment] 2024-10-21 23:54
Yeah, good call! @waterim Just asked and if you can confirm that this can't be done without access to OD, then I'll have to grab it because there's no way to provide access there for the moment.

**Comment by waterim** [comment] 2024-10-22 12:40
From my side it looks like impossible to test it properly, I tried to debug just with staging, but can't log anything or test without redirecting to a local newDot, but from my side it looks like we don't want to set `signedInWithShortLivedAuthToken: null` as this one is causing this "session is expired" and playing with Onyx data for this specific case can be a good solution imo, but cant test to prove this solution unfortunately :(

**Comment by carlosmiceli** [comment] 2024-10-22 15:28
Right, that's a bummer! No worries, I'll grab it and will let you know how it goes and if you can help out as well 🙏 
Thank you!

**Comment by carlosmiceli** [comment] 2024-10-24 04:57
Didn't get to this yet, should be able to work on it tomorrow.

**Comment by carlosmiceli** [comment] 2024-10-25 18:19
The fix ended up being a lot simpler, we needed to use `account` from Onyx, not as a prop: https://github.com/Expensify/App/pull/51450

**Comment by Christinadobrzyn** [comment] 2024-10-29 01:59
PR in the works! @carlosmiceli can we move this to weekly while the PR is being worked on?

**Comment by carlosmiceli** [comment] 2024-10-29 02:01
Sorry, what needs to be worked on? All PR fixes have been merged for this.

**Comment by carlosmiceli** [comment] 2024-10-29 02:01
But yes, we can move this to weekly until it's closed!

**Comment by Christinadobrzyn** [comment] 2024-10-29 02:27
Oh perfect! Sorry I meant move to weekly while the PR is going into production. Thanks!

**Comment by eh2077** [comment] 2024-11-04 14:24
C+ wasn't involved in this task, so no payment needed here and unassigning myself

**Comment by Christinadobrzyn** [comment] 2024-11-05 08:32
Do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-11-12 02:24
@carlosmiceli do you think we should create a regression test or anything for this?

**Closed** 2024-11-12 02:39 UTC
Labels: Weekly, Internal, Design, Awaiting Payment, Bug
