### ISSUE TITLE
[HOLD for payment 2021-12-06] Request a call modal - Update phone number requirements and instructions. 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5945] opened 2021-10-19 13:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the Concierge conversation 
2. Click on the phone icon on top right

## Expected Result:
There should be clear instructions on how to enter a phone number. (Country code, format, etc). Also, the phone number displayed should be the Expensify number (the one user to call customers). Please check @mallenexpensify proposed improvements on notes section. 

## Actual Result:
Instructions are focused on phone numbers which country code and the phone number displayed is not from Expensify. 

## Workaround:
None Needed. 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.8-0
 **Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Improvements from @mallenexpensify: 

- The example phone number that's misaligned shows you should enter +1 at the beginning but it's not necessary for US numbers.  We should update number in the box to remove +1 .
- The number that should be shown in the box should be updated to 2109400803 , a number we actually call from.
- The red error text also states you need to include a country code which you don't if you're in the US (which I'm guessing is ~90% of our calls).  Can we update it to "Please enter a phone number. If you're outside the US please include your country code, eg. +44 7782 339811" (which is an actual number we call from in the UK)

![image](https://user-images.githubusercontent.com/44479856/137924371-37783a69-880f-481a-829e-63cebb96f7fe.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1634498711397400

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2021-10-19 23:28
Issue LGTM, should be an easy fix for our external contributors.

**Comment by chiragsalian** [comment] 2021-10-20 20:50
Proposal LGTM, i think you forgot to account to correct the misalignment so can you update your proposal to account for this.

> The same message is used for other phone number input error messages too, should it be the same on other pages or let alone this page.

Yup, it should be the same on all other pages i.e., you can just update `noPhoneNumber` so that its reflected everywhere. One note though, once you make the changes please test some of the other places where the copy has been updated so that styles are not broken since the updated text is longer.

> Should we change here also anything?

Sure yes. I think `That doesn’t look like a valid phone number. Please enter a valid phone number. If you're outside the US please include your country code, eg. +44 7782 339811`. Not sure if that's too long. I'll let @mallenexpensify chime in. Matt once decided can you ask #espanol for Spanish copies of this and "Please enter a phone number. If you're outside the US please include your country code, eg. +44 7782 339811". Asking you since I'll be OOO for a few days.

**Comment by chiragsalian** [comment] 2021-11-01 19:07
In our code we don't allow characters like brackets, dash etc
So the only valid US numbers are,
> 5627286666
> 15627286666
> +15627286666

**Comment by mallenexpensify** [comment] 2021-11-01 20:54
> Please enter a valid phone number without brackets or dashes. If you're outside the US please include your country code, eg. +44 7782 339811

I think the above will do for now.

**Comment by chiragsalian** [comment] 2021-11-01 21:52
oh also spaces will throw an error, so the example phone number should be `+447782339811`. You can modify the created PR to allow spaces in phone number as well. Should be a very easy fix to trim them out when needed via code.

Asking for spanish copy.

**Comment by chiragsalian** [comment] 2021-11-01 21:56
A nice future update would be to split the phone number into international code and phone number. Then the international code can be intelligently filled based on their location. They can modify it if they wish but it would be nice to see it be smart and auto-filled.

**Comment by mallenexpensify** [comment] 2021-11-02 16:28
I like that idea Chirag but not sure how it'd best work in practice with us using one box for both email and phone. This is what's on NewDot now. 
![image](https://user-images.githubusercontent.com/22508304/139905899-1b1f2ab9-9239-45e1-b97c-fe173e5cf697.png)

**Comment by chiragsalian** [comment] 2021-11-02 16:53
English copy,
> Please enter a valid phone number without brackets or dashes. If you're outside the US please include your country code, eg. +447782339811

Spanish copy,
> Por favor, introduce un número de teléfono válido sin paréntesis o guiones. Si reside fuera de Estados Unidos, por favor incluye el prefijo internacional. P. ej. +447782339811

So you should be all set to create the PR right @Santhosh-Sellavel or is there any pending question on your end?

**Comment by chiragsalian** [comment] 2021-11-02 16:56
Ah true, I forget we have just one box. Well maybe someday we'll split it like oldDot,
![image](https://user-images.githubusercontent.com/14356145/139910381-2e06c49d-c5a6-40da-bf37-6150f1a911c4.png)

and then perhaps we could implement that logic.

**Comment by Santhosh-Sellavel** [comment] 2021-11-02 17:41
@chiragsalian 

The following changes needed to be done in PR right?

1. We need to update the placeholder `2109400803` here, 
https://github.com/Expensify/App/blob/7f3153ac0e20a17a4db9d032851246d051ffad8a/src/pages/RequestCallPage.js#L208

2.  Update following error messages to new messages given [here](https://github.com/Expensify/App/issues/5945#issuecomment-957941428)
- https://github.com/Expensify/App/blob/7f3153ac0e20a17a4db9d032851246d051ffad8a/src/languages/en.js#L471
- https://github.com/Expensify/App/blob/7f3153ac0e20a17a4db9d032851246d051ffad8a/src/languages/en.js#L472

3. Additionally, as you mentioned in [comment.](https://github.com/Expensify/App/issues/5945#issuecomment-956684968)
> You can modify the created PR to allow spaces in phone numbers as well. Should be a very easy fix to trim them out when needed via code.
For the Request call page box alone or for what other fields?
Do we really need this change? Why would we need a space here?

**Comment by chiragsalian** [comment] 2021-11-02 18:48
1 and 2 are correct. 3 is not needed. I meant that for the follow-up issue MattAllen created and it looks like he updated the follow-up issue title to reflect the same.

You just need to address your points 1 and 2 for this issue 🙂

**Comment by Christinadobrzyn** [comment] 2021-11-11 01:42
not overdue - working on a proposal

**Comment by Christinadobrzyn** [comment] 2021-11-22 04:24
Looks like the PR is under review - moving forward with this fix!

**Comment by botify** [comment] 2021-11-29 18:26
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.1.16-10 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/6178


If no regressions arise, payment will be issued on 2021-12-06. :confetti_ball:

**Comment by Christinadobrzyn** [comment] 2021-12-07 05:01
Paid @Santhosh-Sellavel in Upwork - closing this job

**Closed by Christinadobrzyn** 2021-12-07 05:01 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly, Awaiting Payment
