### ISSUE TITLE
Monthly statement dialogue is empty

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9670] opened 2022-07-01 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Check the monthly statement display

## Expected Result:
Statement should include the info 

## Actual Result:
Monthly statement is blank 

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://user-images.githubusercontent.com/43995119/176926428-82b6b95f-71af-4cc6-abd0-1b703a26d058.jpeg)
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1655382758188599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2022-07-05 08:49
Looking into this. Looks like the issue occurs only on desktop.

**Comment by thienlnam** [comment] 2022-07-06 16:53
Closing since this is a duplicate of this https://github.com/Expensify/App/issues/9713

**Closed by thienlnam** 2022-07-06 16:53 UTC
Labels: Engineering, Weekly
