### ISSUE TITLE
[$250] Room - # room from room description is highlighted when edit description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42678] opened 2024-05-27 22:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a93@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Start creating a room
2. On room description add text `this room is to send cute cat memes` > Create room
3. Verify you navigate to room page
4. Click on description and edit the text ("This #room is to send cute cat memes edited")> Save
5. Take a note of description section on room conversation page

## Expected Result:
There should be no highlighted words when edit description

## Actual Result:
#room word from room description becomes highlighted when edit description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0293f3d-b3da-428e-b4ed-36a6e2de0683

<img width="1273" alt="image" src="https://github.com/Expensify/App/assets/51066321/504310ca-b6c7-43c8-9b9c-379d6c81ba67">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d22835d6951d7024</li>
        <li>Upwork Job ID: 1795289072448532480</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment] 2024-05-28 03:04
I wonder if a better solution for product consistency is to throw the same error as shows when creating a new room

<img width="385" alt="image" src="https://github.com/Expensify/App/assets/51066321/e042b1f7-634a-4049-9765-fc92f7bffbab">

Error message is: `Room names can only include lowercase letters, numbers and hyphens.`

**Comment by nkdengineer** [comment] 2024-05-28 03:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
I believe the OP expected result is not correct. It's expected that the `room` will be highlighted because it's a policy room, and in policy rooms we support report mentions.

The real problem here is that when creating a room with `#room` in description, it does not highlight, but when editing, it does.

### What is the root cause of that problem?
When adding a room [here](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/Report.ts#L1994), we forgot to parse the room description, like we did [when updating the description](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/Report.ts#L1912)

### What changes do you think we should make in order to solve the problem?

We need to parse the `description` when adding a report too.

- Modify `getParsedComment` to accept a 3rd param `report`, if it exists, use it [here](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/ReportUtils.ts#L3396) in place of `getReport`. Because when the report is optimistic, it's not there for the `getReport` to get yet, so we need to pass it in directly.

- In https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/Report.ts#L1996, add
```
const parsedDescription = ReportUtils.getParsedComment(policyReport.description ?? '', {reportID: policyReport.reportID}, policyReport);
```

- Use the `parsedDescription` as the `description` in `optimisticData`.

### What alternative solutions did you explore? (Optional)
NA

**Comment by getusha** [comment] 2024-05-28 11:28
@GandalfGwaihir isn't the purpose of this [PR](https://github.com/Expensify/App/pull/40685), to prevent `#room` from being parsed?

**Comment by nkdengineer** [comment] 2024-05-28 16:35
@getusha The purpose of the PR is to prevent report mention (eg #room) from being parsed for **non-policy reports** (eg. DM, ...). For policy reports report mention should still work/be parsed.

**Comment by nkdengineer** [comment] 2024-05-29 02:19
> this was intended to be specific to comments we post in chat I assume(chats in policy).

Not only comments but anything in the report too, including description. Normally for description and comment of the same report we always support the same set of markdowns.

**Comment by Christinadobrzyn** [comment] 2024-05-30 02:23
I'm just double-checking the expected behaviour for this - https://expensify.slack.com/archives/C066HJM2CAZ/p1717035618513299

**Comment by Christinadobrzyn** [comment] 2024-05-31 02:35
Based on the team discussion - I think we only need to fix the actionable whisper - confirming before we continue - https://expensify.slack.com/archives/C066HJM2CAZ/p1717122819898099?thread_ts=1717035618.513299&cid=C066HJM2CAZ

**Comment by Christinadobrzyn** [comment] 2024-05-31 06:50
Based on the team discussion - I think we only need to fix the actionable whisper - confirming before we continue - https://expensify.slack.com/archives/C066HJM2CAZ/p1717122819898099?thread_ts=1717035618.513299&cid=C066HJM2CAZ

**Comment by getusha** [comment] 2024-06-03 08:55
>The actionable whisper was a backend bug, which is fixed now, deployed yesterday I think.
Regarding the issue, I think there is nothing to be done there,  we just need to start highlighting report mentions in the description when creating a room, but I believe we can do that in a different issue so things don't get confused.

@Christinadobrzyn i think we can close this? https://expensify.slack.com/archives/C066HJM2CAZ/p1717160228281969?thread_ts=1717035618.513299&cid=C066HJM2CAZ

**Comment by Christinadobrzyn** [comment] 2024-06-04 01:51
Yes @getusha - good call. We'll close. Thanks!

**Closed by Christinadobrzyn** 2024-06-04 01:51 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by nkdengineer** [comment] 2024-06-04 11:42
> we just need to start highlighting report mentions in the description when creating a room, but I believe we can do that in a different issue so things don't get confused.

@Christinadobrzyn @getusha I identified this bug in [my proposal](https://github.com/Expensify/App/issues/42678#issuecomment-2134290501). I think we can modify the OP to fix this issue here, because it's related to the original issue.

What do you think?

If not we can create another GH issue and link it here, then I can repost my proposal there.

**Comment by nkdengineer** [comment] 2024-06-06 08:49
@Christinadobrzyn Quick bump on https://github.com/Expensify/App/issues/42678#issuecomment-2147321304, thanks 🙇
