### ISSUE TITLE
[HOLD for payment 2023-10-09] [HOLD for payment 2023-09-29] [$500] Web - Inconsistency bug: App does not translate copy to clipboard text for requested (works fine for owes)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27114] opened 2023-09-10 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and complete request money flow using any amount and any user
3. Change language to spanish
4. Open report to which we have requested money in step 2
5. Copy IOU message of request money and paste anywhere to observe that it is translated correctly
6. Click on IOU message and click on copy to clipboard on similar IOU message
7. Paste and observe that it is not translated

## Expected Result:
App should translate IOU message copy to clipboard text for 'requested' message as we do for similar IOU parent message

## Actual Result:
App does not translate IOU message copy to clipboard text for 'requested' message IOU which we find on click of request money IOU in main report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/94fe0e49-7a91-4c18-b712-502903164e9e

https://github.com/Expensify/App/assets/93399543/7a3b1a88-07d9-47d4-9012-6acf2391eab6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693925728595269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment] 2023-09-10 20:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
copy clipboard text for requested is not translated according to preferences.
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/fd043aadab021653217df15df90e0585437faa8e/src/libs/ReportUtils.js#L2023-L2040

We have hard coded text which will not be translated dynamically depending on the user language selection. 
### What changes do you think we should make in order to solve the problem?


Such texts should be put inside `en.js` and `es.js` and should be used using ` Localize.translateLocal`, for example we should move the following to en.js & es.js and make it a function to accept required arguments to use like `payerOwesAmount`

https://github.com/Expensify/App/blob/fd043aadab021653217df15df90e0585437faa8e/src/libs/ReportUtils.js#L2028

https://github.com/Expensify/App/blob/1400608f7cc6537fd03fe7987d6d59bc6c7da56d/src/languages/en.ts#L512 

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-09-10 20:39
The root cause looks like a dupe of https://github.com/Expensify/App/issues/26664

Should be fixed with this proposal: https://github.com/Expensify/App/issues/26664#issuecomment-1710569401

**Comment by narefyev91** [comment] 2023-09-11 07:24
Proposal from @getusha looks good to me https://github.com/Expensify/App/issues/27114#issuecomment-1712926814
Correctly identified the root case and steps to fix looks good
🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment] 2023-09-11 07:35
@narefyev91 this proposal will not fix the translation issue dynamically – it will persist the message with the language that was set at the moment of IOU request creation – please see the broader issue with copying the IOU to the clipboard: https://github.com/Expensify/App/issues/26664

This my proposal should fix the issue dynamically (with copying in the locale that's chosen for the user at the moment, not only during creation): https://github.com/Expensify/App/issues/26664#issuecomment-1710569401

**Comment by narefyev91** [comment] 2023-09-11 07:41
> @narefyev91 this proposal will not fix the translation issue dynamically – it will persist the message with the language that was set at the moment of IOU request creation – please see the broader issue with copying the IOU to the clipboard: #26664
> 
> This my proposal should fix the issue dynamically (with copying in the locale that's chosen for the user at the moment, not only during creation): [#26664 (comment)](https://github.com/Expensify/App/issues/26664#issuecomment-1710569401)

Hey @paultsimura ! Proposal indicates the root case and add logic for pick translation from languages file instead of applying it as it is now. All code changes should be discussed in PR

**Comment by paultsimura** [comment] 2023-09-11 07:50
@narefyev91 of course, I did not want to dive deep into code changes.
I just wanted to highlight that the selected proposal does not solve the issue.
You can ask @getusha to check their approach: first, create the IOU, then change the user's locale and try to copy text to clipboard – the localization won't work.

**Comment by getusha** [comment] 2023-09-11 07:57
@paultsimura it's obvious after we change the hard coded values to dynamic in `en.js` and `es.js` to replace it in all places which the hard coded value is used. and i don't see why it will not work.

**Comment by conorpendergrast** [comment] 2023-09-11 08:17
@maddylewis Looks like we both got assigned. Unassigning myself as I'm going on parental leave!

**Comment by paultsimura** [comment] 2023-09-11 08:25
@getusha sometimes obvious things are not that obvious. I'm not trying to steal your bounty, moreover my issue was closed as a dupe.
Just please try the steps I've mentioned, and you'll see what I'm talking about.

**Comment by getusha** [comment] 2023-09-11 08:52
@paultsimura i understand your concern but as i mentioned the localization will be used every place where it should be wherever the Money Request action exists.

https://github.com/Expensify/App/assets/75031127/e1198c89-a242-4904-a779-d90970509c6b

**Comment by roryabraham** [comment] 2023-09-11 09:07
@getusha The only places where `ReportUtils.getIOUReportActionMessage` are used is when we're building optimistic IOU actions. We don't want to send localized text to the back-end because our other codebases are not internationalized.

Furthermore it's not dynamic as others have said. I think @rayane-djouah's proposal looks good.

**Comment by roryabraham** [comment] 2023-09-11 09:37
ok, let's see if this works...

**Comment by getusha** [comment] 2023-09-11 09:38
>@getusha The only places where ReportUtils.getIOUReportActionMessage are used is when we're building optimistic IOU actions. We don't want to send localized text to the back-end because our other codebases are not internationalized.

@roryabraham I haven't realized the backend is not internationalized, thanks for the clarification. after converting it to dynamic text it should be used inside ContextMenuActions 👍

**Comment by funny2code** [comment] 2023-09-11 16:31
Hi Hiring Team! My name is Dejan Bukovcic.
I am interested in this project. I sent already an email for joining to the channel to contributors@expensify.com.

**Comment by funny2code** [comment] 2023-09-11 16:39
Contributor details
Your Expensify account email: dejanbuk.dev@gmail.com
Upwork Profile Link: https://new.expensify.com/a/15645588

**Comment by funny2code** [comment] 2023-09-11 16:39
Contributor details
Your Expensify account email: [dejanbuk.dev@gmail.com](mailto:dejanbuk.dev@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018db8c60ae1459528

**Comment by funny2code** [comment] 2023-09-11 16:43
Contributor details
Your Expensify account email: dejanbuk.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018db8c60ae1459528

**Comment by pecanoro** [comment] 2023-09-12 04:17
It seems this issue was a duplicated of https://github.com/Expensify/App/issues/26621 since both had the same root cause.

**Comment by narefyev91** [comment] 2023-09-12 06:45
@pecanoro well seems we should close this one - and wait when BE will support localisation (https://github.com/Expensify/App/issues/26621#issuecomment-1715050617)  cc @roryabraham

**Comment by roryabraham** [comment] 2023-09-12 07:27
@pecanoro let me know if you feel strongly that we do not proceed with the [accepted proposal](https://github.com/Expensify/App/issues/27114#issuecomment-1712931879) to fix this issue in the front-end.

**Comment by narefyev91** [comment] 2023-09-12 13:13
Waiting for final decision from @pecanoro to start review process

**Comment by maddylewis** [comment] 2023-10-02 13:45
@roryabraham - did this bug fix cause a regression? https://github.com/Expensify/App/issues/27114#issuecomment-1727720702

just want to confirm while i process payment / if it should be reduced by 50% for the contributor and C+ assigned to the issue.

**Comment by maddylewis** [comment] 2023-10-02 13:47
## Payments
- [ ] Reporting bonus: @dhanashree-sawant ($50 via Upwork)
- [ ] Contributor: @rayane-djouah ($500 or $250 if regression - via Upwork)
- [ ] C+: @narefyev91 ($500 or $250 if regression - via Upwork)

**Comment by maddylewis** [comment] 2023-10-02 13:47
@narefyev91 - will you review this checklist when you have a chance? thanks! https://github.com/Expensify/App/issues/27114#issuecomment-1731409151

**Comment by mananjadhav** [comment] 2023-10-10 10:42
@maddylewis Can you please post the payment summary here so that I can request the payout?

**Comment by maddylewis** [comment] 2023-10-12 14:17
yes! i will process payments / post an updated payment summary before EOD!

**Comment by maddylewis** [comment] 2023-10-13 18:38
### Payments
- [ ] @narefyev91 does not require payment (Contractor)
- [ ] @dhanashree-sawant requires payment ($50 reporting bonus via Upwork)
- [ ] @rayane-djouah requires payment (Contributor - $500 via Upwork)
- [ ] @mananjadhav (C+ - $500 via NewDot)

**Comment by maddylewis** [comment] 2023-10-13 18:39
@narefyev91 - will you please review/fill out this checklist when you have a chance? thanks! https://github.com/Expensify/App/issues/27114#issuecomment-1743431105

**Comment by maddylewis** [comment] 2023-10-13 18:46
offers sent to @dhanashree-sawant and @rayane-djouah

**Comment by JmillsExpensify** [comment] 2023-10-13 19:59
$500 payment approved for @mananjadhav based on BZ summary.

**Comment by narefyev91** [comment] 2023-10-16 08:09
- The PR that introduced the bug has been identified. Link to the PR - current PR is more for missing functionality rather than regression fix
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Closed** 2023-10-16 19:39 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
