### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Chat - Not update frequently used emoji when pasting emoji into composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21786] opened 2023-06-28 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enter :smile: in composer
2. Notice that it is converted to emoji and updated frequently used emoji
3. Paste a emoji to compose
4. Open emoji picker and notice this

## Expected Result:
App should update frequent used emoji when pasting a emoji into composer

## Actual Result:
App doesn't update frequent used emoji when pasting a emoji into composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  1.3.31-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f9878c06-82a1-41d3-affb-18914aa896a6

https://github.com/Expensify/App/assets/93399543/785c7782-1742-4d47-9ba4-0591ccb9ae6f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687744968139979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183125281d2c3d055</li>
        <li>Upwork Job ID: 1674388658583044096</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-06-29 12:05
Agreed that we should be updating the list of Frequently Used emojis for any emoji used, whether via the picker or paste.

**Comment by bfitzexpensify** [comment] 2023-06-29 12:19
@dukenv0307 did you mark your comment https://github.com/Expensify/App/issues/21786#issuecomment-1612421841 as off-topic? Trying to determine whether that's a legit proposal or not.

**Comment by bfitzexpensify** [comment] 2023-06-29 13:07
Interesting, so this might be tricky from a technical perspective. I just tested in Slack and it doesn't update the most frequently used when pasting the emoji in from elsewhere. 

The behaviour does work on iOS - I tested copying different emojis that weren't in the frequently used list from Notes into WhatsApp, FB Messenger, iMessage and Instagram messaging, and each time the frequently used list updated after pasting in the emoji and sending it. But that seems like an OS thing rather than an app thing - the emoji picker there carries across apps, rather than being app-specific.

@parasharrajat do you have an Android you can test the same on? I can test if not but it will take me a little longer to set up and sign into these apps to test. 

Since iOS does do this somehow, I think we can leave this open to see if we can get any proposals that will be able to solve for it. If not, it's not a major thing and we can just close it out.

**Comment by jeet-dhandha** [comment] 2023-06-29 13:22
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Pasted emojis in compser is not counted in frequently used emojis.

### What is the root cause of that problem?
- There's no such implementation in the code to get emojis if they are pasted in composer. As they are in unicode format and thus we cannot use `replaceEmojis` directly.

### What changes do you think we should make in order to solve the problem?
- First we will create a map of all the emojis and their corresponding object.

```js
const emojiMap = {
  "😀": {
    name: "grinning",
    code: "😀",
    keywords: ["smile", "happy", "grinning", "face", "grin"],
  },
  // ... rest emojis (this is made using `emojis.js`)
}
```

- Create a function `getEmojiCodeFromText` which will take unicode as input and return the emoji object from the map, in file `EmojiUtils.js`.

<details>
<summary>Code Changes:</summary>

```js
import emojiMap from "../assets/emojiMap";

... rest code

function getEmojiCodeFromText(text) {
    // For example, replace "Some comment with emoji 👉"
    const emojis = [];
    const added = {};
    if(!text || typeof text !== "string") { return emojis; }
    const arr = [...text];
    for (let i = 0; i < arr.length; i++) {
        const character = arr[i];
        if(emojiMap[character] && added[character] !== true) {
            added[character] = true;
            emojis.push(emojiMap[character]);
        }
    }
    return emojis;
}
```
</details>

- Now use `getEmojiCodeFromText` function in `replaceEmojis` function to get the emojis from the text.

<details>
<summary>Code Changes:</summary>

```diff
function replaceEmojis(text, preferredSkinTone = CONST.EMOJI_DEFAULT_SKIN_TONE) {
    let newText = text;
-   const emojis = [];
+   const emojis = [...getEmojiCodeFromText(text)];
    const emojiData = text.match(CONST.REGEX.EMOJI_NAME);
    if (!emojiData || emojiData.length === 0) {
        return {text: newText, emojis};
    }
```
</details>

- Finally use `replaceEmojis` function and update frequetly used emojis in `Composer`'s paste function.
<details>
<summary>Code Changes</summary>

```diff
    paste(text) {
        try {
            document.execCommand('insertText', false, text);
            this.updateNumberOfLines();

+           const {emojis = []} = EmojiUtils.replaceEmojis(text, this.props.preferredSkinTone);
+           if (!_.isEmpty(emojis)) {
+               User.updateFrequentlyUsedEmojis(EmojiUtils.getFrequentlyUsedEmojis(emojis));
+           }

            // Pointer will go out of sight when a large paragraph is pasted on the web. Refocusing the input keeps the cursor in view.
            this.textInput.blur();
            this.textInput.focus();
            // eslint-disable-next-line no-empty
        } catch (e) {}
    }
```

</details>

- After Changes
<details>
<summary>Output</summary>

https://github.com/Expensify/App/assets/78416198/864c6179-ccef-4e71-8d5e-25050bc8e3f6

</details>

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment] 2023-06-29 15:51
@bfitzexpensify @parasharrajat - Any updates on my proposal ?

**Comment by jeet-dhandha** [comment] 2023-07-01 02:30
Updated PROPOSAL : https://github.com/Expensify/App/issues/21786#issuecomment-1613176046

**Comment by jeet-dhandha** [comment] 2023-07-01 02:40
@parasharrajat 

> Do you mind explaining all the scenarios where an emoji can be used in a composer and explaining what will be the outcome of all?
Emoji can be added by:
- Pasting Text
- Adding using Composer's emoji button.
- Could have been in draft before this change.

> How will you handle emoji face tones?

Upto my knowledge we are just rendering them as different skin tone. But storing them in suggestion is based on the `base code` only.

PS: I updated the proposal and also optimised the function to not loop through each text, instead use regex to get all the emojis and also use set to remove duplicates.

**Comment by jeet-dhandha** [comment] 2023-07-03 17:12
@parasharrajat Any thoughts on the above answer.

**Comment by bfitzexpensify** [comment] 2023-07-07 12:28
@parasharrajat reminder to check https://github.com/Expensify/App/issues/21786#issuecomment-1615382576 when you get a moment - thanks!

**Comment by ShogunFire** [comment] 2023-07-09 23:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we paste emojis they are not added to the frequently used emojis

### What is the root cause of that problem?

We are not currently handling emojis that are pasted

### What changes do you think we should make in order to solve the problem?

In replaceEmojis before replacing the text by emojis here:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/libs/EmojiUtils.js#L279

we can add the already existing emojis to the array that we return like this:

```
_.forEach(allEmojis, (item) => {
    if(text.includes(item.code)){
        emojis.push({
            name: item.name,
            code: item.code,
            types: item.types,
        });
    }
});
```
allEmojis being declared like this:
`import {default as allEmojis}  from '../../assets/emojis/common';`

Then they will be added to the frequent emojis here: 
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/home/report/ReportActionCompose.js#L756

Result: 

https://github.com/Expensify/App/assets/19537677/71877a94-c950-43e1-9bf0-239edf53625a



### What alternative solutions did you explore? (Optional)

For more clarity we could put this code in another function and then merge the two arrays before updating the frequent emojis

**Comment by bfitzexpensify** [comment] 2023-07-13 15:54
@parasharrajat looks like we have the updated proposal from @jeet-dhandha and also a proposal from @ShogunFire ready for review when you get a chance

**Comment by bfitzexpensify** [comment] 2023-07-17 09:30
@parasharrajat reminder to have a look here today when you get a chance, thank you!

**Comment by ShogunFire** [comment] 2023-07-18 18:24
Sorry I don't really have time right now and I don't know if that would change reviewers choice. But I don't see why that shouldn't work

**Comment by jeet-dhandha** [comment] 2023-07-18 19:02
@parasharrajat I found two places where we will need to make the change:
1. ReportActionCompose.js
https://github.com/Expensify/App/blob/96d077cfd7894c9f148049b85957bbc5652a6e0a/src/pages/home/report/ReportActionCompose.js#L790-L798
2. ReportActionItemMessageEdit.js
https://github.com/Expensify/App/blob/96d077cfd7894c9f148049b85957bbc5652a6e0a/src/pages/home/report/ReportActionItemMessageEdit.js#L163-L170

**Comment by jeet-dhandha** [comment] 2023-07-18 19:10
Also can we go with creating this common function such that there's not much change in the above given files.

- Common Function
```js
function replaceAndExtractEmojis(text, preferredSkinTone = CONST.EMOJI_DEFAULT_SKIN_TONE, lang = CONST.LOCALES.DEFAULT) {
    const {text: newDraft = '', emojis = []} = replaceEmojis(text, preferredSkinTone, lang);

    return {
        text: newDraft,
        emojis: emojis.concat(getEmojiCodeFromText(text)),
    };
}
```

- ReportActionCompose.js

```diff
const {text: newComment = '', emojis = []} = 
-  EmojiUtils.replaceEmojis(comment, this.props.preferredSkinTone, this.props.preferredLocale);
+  EmojiUtils.replaceAndExtractEmojis(comment, this.props.preferredSkinTone, this.props.preferredLocale);
```

- ReportActionItemMessageEdit.js

```diff
const {text: newDraft = '', emojis = []} = 
-  EmojiUtils.replaceEmojis(newDraftInput, props.preferredSkinTone, props.preferredLocale);
+  EmojiUtils.replaceAndExtractEmojis(newDraftInput, props.preferredSkinTone, props.preferredLocale);
```

**Comment by jeet-dhandha** [comment] 2023-07-18 19:11
Also a question  - Do we count frequently used emojis from Title's or Descriptions of Task or any other inputs ?

**Comment by ShogunFire** [comment] 2023-07-18 21:20
Weird but ok...

**Comment by jeet-dhandha** [comment] 2023-07-19 06:58
Then above changes should suffice.

**Comment by jeet-dhandha** [comment] 2023-07-19 09:05
Does this code looks good: https://github.com/Expensify/App/pull/23153

**Comment by jeet-dhandha** [comment] 2023-07-19 18:24
@parasharrajat Waiting for you to confirm.

**Comment by jeet-dhandha** [comment] 2023-07-19 18:34
That's Cool 😎👍

**Comment by jeet-dhandha** [comment] 2023-07-19 20:30
@parasharrajat  Ready for Review: https://github.com/Expensify/App/pull/23153

**Comment by jeet-dhandha** [comment] 2023-07-25 14:13
@parasharrajat Have tried using a new user or not ?

**Comment by jeet-dhandha** [comment] 2023-07-25 16:57
Good work. Will fix and update you.

**Comment by jeet-dhandha** [comment] 2023-07-25 20:35
@parasharrajat Do you have knowledge on ZWJ Emoji Sequences ?

**Comment by jeet-dhandha** [comment] 2023-07-25 20:54
I have resolved the issue we had it was because of that. https://unicode.org/Public/emoji/15.0/emoji-zwj-sequences.txt You can check this link for that.

**Comment by jeet-dhandha** [comment] 2023-07-25 20:54
Now it should work for you.

**Comment by jeet-dhandha** [comment] 2023-07-25 20:55
Some links for refenrences:
- http://unicode.org/emoji/charts/emoji-zwj-sequences.html
- https://emojipedia.org/emoji-zwj-sequence/
- https://blog.emojipedia.org/emoji-zwj-sequences-three-letters-many-possibilities/

**Comment by bfitzexpensify** [comment] 2023-08-11 10:13
@parasharrajat a reminder to review https://github.com/Expensify/App/pull/23153#issuecomment-1666044387 - thank you!

**Comment by bfitzexpensify** [comment] 2023-08-22 12:21
@parasharrajat how are we looking here?

**Comment by bfitzexpensify** [comment] 2023-09-05 09:35
Payment summary: 

Reporting: @chiragxarora - offer sent via Upwork
Contributor: @jeet-dhandha - $1000 paid out via Upwork ✅ 
C+: @parasharrajat to be paid $1000 via manual request

**Comment by bfitzexpensify** [comment] 2023-09-06 14:05
Reminder to complete the BZ checklist when you get a chance @parasharrajat

**Comment by bfitzexpensify** [comment] 2023-09-07 09:28
Looks good to me! Regression steps proposed in https://github.com/Expensify/Expensify/issues/314764. Think we're all done here - thanks everyone!

**Closed by bfitzexpensify** 2023-09-07 09:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 09:40
$1,000 payment for @mananjadhav approved based on BZ summary.
