### ISSUE TITLE
[$500] Get $250 - Invalid Invite link URL for users signed in with Login with Google icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34977] opened 2024-01-23 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34360

## Action Performed:
1. Go to staging.new.expensify.com signed out
2. Click on the Google icon on the start of the page
3. Click on your avatar > Share code > Get 250
4. Click on 'Copy invite link'

## Expected Result:
Α URL with the invite link is shown that has the logged in email

## Actual Result:
A URL with just the invite page without any mention of logged in user, when the user is logged using the Google's SSO and not a magic link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/126291c7-af4d-44bf-9add-d034d2916cce

https://github.com/Expensify/App/assets/93399543/4589f401-aa5c-4595-abd9-cd51c733665e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb51369a85f79a26</li>
        <li>Upwork Job ID: 1749840021441060864</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-23 17:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Get $250 - Invalid Invite link URL for users signed in with Login with Google icon

### What is the root cause of that problem?
When we login with google account is not populated with `primaryLogin` so it will not be added in the link 
### What changes do you think we should make in order to solve the problem?

We should have a fallback of `credentials.login`
```
account.primaryLogin || credentials.login
```
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-23 18:50
Dupe of #32292. We should reopen #32292 as it has full context

**Comment by mallenexpensify** [comment] 2024-01-24 03:25
@cubuspl42 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by situchan** [comment] 2024-01-24 03:26
@mallenexpensify can you please reopen https://github.com/Expensify/App/issues/32292 and close this one? It's dupe

**Comment by cubuspl42** [comment] 2024-01-25 11:16
It indeed looks like a dupe! I'll unassign myself in such a case. If the decision is changed, please re-assign me.

**Comment by alexpensify** [comment] 2024-01-25 15:04
Thanks for the feedback-- I'm going to close this issue.

**Closed by alexpensify** 2024-01-25 15:04 UTC
Labels: External, Daily, Help Wanted, Bug
