### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] IOU - mWeb - User trying to upload receipt by quickly tapping capture button shows error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50083] opened 2024-10-02 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to DM.
3. Submit an expense.
4. Go to transaction thread.
5. Tap Add receipt modal.
6. Quickly tap capture button many times before the camera is initiated.

## Expected Result:
User trying to upload receipt by quickly tapping capture button must able to upload receipt.

## Actual Result:
User trying to upload receipt by quickly tapping capture button shows error "The receipt didn't upload.Download the file or dismiss this error and lose it."

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f2b02586-3b46-41d7-8eb7-0140ba0d7f2b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841557091803230884</li>
        <li>Upwork Job ID: 1841557091803230884</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>QichenZhu | Contributor | 104415140</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by marcochavezf** [comment] 2024-10-02 19:13
This is a frontend issue, making it external to get more 👀

**Comment by marcochavezf** [comment] 2024-10-02 19:53
I cannot reproduce this error consistently in staging. Also, I don't think this specific behavior on mweb should be considered a blocker, but it still needs a fix

**Comment by Christinadobrzyn** [comment] 2024-10-07 03:42
hi @fedirjh can you review this [proposal](https://github.com/Expensify/App/issues/50083#issuecomment-2390815004)? TY!

**Comment by marcochavezf** [comment] 2024-10-07 23:52
Not overdue waiting for C+ review and/or more proposals

**Comment by Christinadobrzyn** [comment] 2024-10-09 07:33
@fedirjh can you provide an update on this? Thanks!

**Comment by marcochavezf** [comment] 2024-10-14 17:59
Thanks for the review @fedirjh, assigning @QichenZhu 🚀

**Comment by QichenZhu** [comment] 2024-10-15 05:46
@fedirjh This is marked as mWeb only, but I got an error pop-up when testing on Android, and the app crashed on iOS.

Android | iOS
-- | --
<video src="https://github.com/user-attachments/assets/f83ba152-aa21-43a0-b16a-669f409d0b29" /> | <video src="https://github.com/user-attachments/assets/bab5e3b5-5121-43a2-9026-73ee5a567e0a" />

Do you think it should be handled in a separate issue?

cc @marcochavezf @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2024-10-15 06:52
I think we can just include it in this issue if it's the same issue on a different device. Does that sound good, @fedirjh?

**Comment by QichenZhu** [comment] 2024-10-15 10:26
I think the issue on Native platforms is a separate issue. Previously, we had an issue #36520, where double tapping the shutter caused an error. It was fixed by #38320 for the new money request workflow but not for the edit request workflow, so it appears here now.

**Comment by QichenZhu** [comment] 2024-10-15 12:04
## Proposal
[Updated](https://github.com/Expensify/App/issues/50083#issuecomment-2390815004)

Added the root cause and solution for the native platform issue.

**Comment by Christinadobrzyn** [comment] 2024-10-16 05:03
@fedirjh can you please review and let us know what you think is best, should these be fixed together or separate?

**Comment by marcochavezf** [comment] 2024-10-18 18:19
@QichenZhu thanks for bringing this up, the solution for native LGTM. We can address any other issue in the PR

**Comment by Christinadobrzyn** [comment] 2024-10-29 06:38
Just checking in on this, I think we're working on a PR, is that right @QichenZhu?

**Comment by QichenZhu** [comment] 2024-10-29 06:46
@Christinadobrzyn The PR https://github.com/Expensify/App/pull/50770 has been merged and deployed to staging.

**Comment by Christinadobrzyn** [comment] 2024-11-05 03:02
Payouts due:

- [ ] Contributor: $250 @QichenZhu (Upwork offer - https://www.upwork.com/nx/wm/offer/104415140)
- [ ] Reviewer: $250 @fedirjh (payment through NewDot)

@fedirjh do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-11-06 03:03
Awesome! payment day is today. 

Regression test https://github.com/Expensify/Expensify/issues/442076

@fedirjh can you please request payment through ND?

**Comment by Christinadobrzyn** [comment] 2024-11-07 05:26
DMd @fedirjh to request payment. Going to close this as complete since that's all that's outstanding.

**Closed by Christinadobrzyn** 2024-11-07 05:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-10 12:20
$250 approved for @fedirjh
