### ISSUE TITLE
[$500] Send money - Pay elsewhere appears for second on send money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29311] opened 2023-10-11 13:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Click on FAB and select send money
2. Enter amount and select user
3. Send money

## Expected Result:
It should not show Pay elsewhere button

## Actual Result:
Pay elsewhere appears for second 

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

  

https://github.com/Expensify/App/assets/93399543/f9906108-1a3a-4f5d-943d-96957585e28

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/eb11cdb4-e6bf-4d46-97ad-6b820ed0e173

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/3a454917-ba69-4370-9429-7009c2b3fb1a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a173aceb-65ac-4ee1-a142-e892f110c7fe

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

  

https://github.com/Expensify/App/assets/93399543/71377a7d-a788-4c80-87de-dab62f924670

https://github.com/Expensify/App/assets/93399543/3ad5c465-84cc-472c-b927-0ab2afad5c0a

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/2653c304-a115-401c-91f8-f4e5133ee3e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a35d1f8510e892f</li>
        <li>Upwork Job ID: 1712095218580516864</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-11 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send money - Pay elsewhere appears for second on send money

### What is the root cause of that problem?
When sending money optimistic data should show that this payment is already completed, but it is not doing that. That is why initially `Pay elsewhere` button occurs until response is received from backend which sets report status as paid.
<img width="380" alt="Screenshot 2023-10-11 at 22 06 31" src="https://github.com/Expensify/App/assets/59907218/0c05d5d2-7cbd-4fc8-be89-1652509f0c1f">

I think send money logic was different before, paying to send money request was separate action than creating send money itself. That is why we have this problem.
### What changes do you think we should make in order to solve the problem?
We should update optimistic data here to include `statusNum=4` 
https://github.com/Expensify/App/blob/6dfb3c7fea3cc43dcefa1f7f790f8bfd58511b93/src/libs/actions/IOU.js#L1916
`statusNum` corresponds to payment status and is checked here to show Settlement button
https://github.com/Expensify/App/blob/e1368c07b6572c7d0fed64dd15374909f57a2089/src/components/ReportActionItem/ReportPreview.js#L173-L175


### What alternative solutions did you explore? (Optional)

**Comment by AmjedNazzal** [comment] 2023-10-11 17:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Send money - Pay elsewhere appears for second on send money

### What is the root cause of that problem?

When we are using IOU.sendMoneyElsewhere, we are getting optimisticData from getSendMoneyParams which returns optemisticData that doesn't include statusNum in it, so when we are checking isSettled inside ReportUtils.isSettled we are expecting report.statusNum to be initially ready and have REPORT.STATUS.REIMBURSED as it's value to decide that it indeed is settled but it will not be as we are not writing it in sendMoneyElsewhere

https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/libs/ReportUtils.js#L277-L286

### What changes do you think we should make in order to solve the problem?

Since sendMoneyElsewhere will always mean that the user is sending money elsewhere it will be always settles so we can include that in the optemisticData to make sure it's readily available, we can do that by passing statusNum to getSendMoneyParams and adding it there to the optimisticIOUReportData

```javascript
function sendMoneyElsewhere(report, amount, currency, comment, managerID, recipient) {
    const statusNum =  CONST.REPORT.STATUS.REIMBURSED;
    const {params, optimisticData, successData, failureData} = getSendMoneyParams(report, amount, currency, comment, CONST.IOU.PAYMENT_TYPE.ELSEWHERE, managerID, recipient, statusNum);
```

```javascript
const optimisticIOUReportData = {
    onyxMethod: Onyx.METHOD.SET,
    key: `${ONYXKEYS.COLLECTION.REPORT}${optimisticIOUReport.reportID}`,
    value: {
        ...optimisticIOUReport,
        lastMessageText: optimisticIOUReportAction.message[0].text,
        lastMessageHtml: optimisticIOUReportAction.message[0].html,
        statusNum: statusNum,
    },
};
```

### Result

https://github.com/Expensify/App/assets/74202751/7e030cec-ab5c-4ab9-b13d-a428362ed1e5

**Comment by zanyrenney** [comment] 2023-10-16 14:10
I also can't reproduce, so based off that and the linked issue above, closing!

**Closed by zanyrenney** 2023-10-16 14:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
