### ISSUE TITLE
[HOLD for payment 2024-09-21][$250] [Search v2.2] Keep status scroll position and update label sizes

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47640] opened 2024-08-19 15:45 UTC
Coming from [this PR](https://github.com/Expensify/App/pull/47181), we need to address these comments:

- [Status scroll](https://github.com/Expensify/App/pull/47181#issuecomment-2293743158)
- [Label font size](https://github.com/Expensify/App/pull/47181#issuecomment-2293826351)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833233716363835239</li>
        <li>Upwork Job ID: 1833233716363835239</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by FitseTLT** [comment] 2024-08-19 16:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Keep status scroll position and update label sizes

### What is the root cause of that problem?
Button height we have set it to 42 px here
https://github.com/Expensify/App/blob/bc69605e44c6b1214a127a0e7b829005c30e125e/src/pages/Search/SearchStatusMenuNarrow.tsx#L72-L73
The text and icon size not set to proper value

https://github.com/Expensify/App/blob/bc69605e44c6b1214a127a0e7b829005c30e125e/src/pages/Search/SearchStatusMenuNarrow.tsx#L79-L90
### What changes do you think we should make in order to solve the problem?

We should set values based on this [comment](https://github.com/Expensify/App/pull/47181#issuecomment-2293743158)
icon sizes
```
   width={variables.iconSizeSmall}
                                height={variables.iconSizeSmall}
                            />
```
text size to ` styles.fontSizeLabel` and button Height to 40 px [here](https://github.com/Expensify/App/blob/bc69605e44c6b1214a127a0e7b829005c30e125e/src/pages/Search/SearchStatusMenuNarrow.tsx#L72-L73)
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-19 16:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. The status scroll position isn't saved
2. The label size of Expense dropdown button isn't correct

### What is the root cause of that problem?

1. When we click on status option, we open a new page and then `SearchStatusBar` is mounted again which makes the scroll position reset.


2. The font size of Expense dropdown button isn't correct because it has the default font-size

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L78

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L82

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L88


### What changes do you think we should make in order to solve the problem?
1. To save the scroll position we can do the same way as we do in `InitialSettingPage` by using `ScrollOffsetContext` to store the scroll offset. The route we pass to `saveScrollOffset` will be `ROUTES.SEARCH_CENTRAL_PANE.route` because we should use this for all search queries

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/settings/InitialSettingsPage.tsx#L457

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/settings/InitialSettingsPage.tsx#L473

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/settings/InitialSettingsPage.tsx#L468

2. Update the font-size of the Expense button here by adding `small` prop for the icon and `styles.fontSizeLabel` for the title

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L78

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L82

https://github.com/Expensify/App/blob/9334352afe9257d689cf983f41090c971a27d722/src/pages/Search/SearchTypeMenuNarrow.tsx#L88
### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2024-08-20 03:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to fix 2 things.
1. Update the Expense label and icon size
2. Keep the scroll position fo the search type when selecting the type

### What is the root cause of that problem?
When we select the search type, for example Paid, the page loading which only renders the header and loading skeleton,
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/components/Search/index.tsx#L195-L206

which means the SearchStatusBar is unmounted.
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/components/Search/index.tsx#L314-L329

and when the loading is completed, a new SearchStatusBar instance is mounted.

For the styling issue, it's just we don't apply the correct styling.

### What changes do you think we should make in order to solve the problem?

To keep the SearchStatusBar mounted even when loading, we need to add SearchStatusBar when loading too.
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/components/Search/index.tsx#L195-L203

```
<SearchPageHeader />
<SearchStatusBar />
<SearchRowSkeleton />
```

Just like we did with empty view too.
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/components/Search/index.tsx#L220-L233

This way, the component tree for the header and status bar stays the same which prevents it from being unmounted.

```
|
|-Header
|-StatusBar
|-Skeleton/EmptyView/SelectionList
```

For the Expenses button style issue, the button height is actually 42 instead of 40. We can update the pressable and view height here to 40.
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/pages/Search/SearchTypeMenuNarrow.tsx#L67-L76

And to make the icon 16px, we need to pass `small` or `medium` and `hasText` props to the `Icon`. And for the text, we need to pass `styles.fontSizeLabel` style so the font size is 13px.
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/pages/Search/SearchTypeMenuNarrow.tsx#L78-L91

Alternatively, we can replace the pressable with `ButtonWithDropdownMenu`. So, we can replace
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/pages/Search/SearchTypeMenuNarrow.tsx#L67-L103

with

```
<ButtonWithDropdownMenu
    onPress={() => null}
    shouldAlwaysShowDropdownMenu
    buttonSize={CONST.DROPDOWN_BUTTON_SIZE.MEDIUM}
    options={popoverMenuItems}
    isSplitButton={false}
    icon={menuIcon}
    style={[styles.ph5]}
    wrapperStyle={styles.flex1}
/>
```

**Comment by bernhardoj** [comment] 2024-08-20 11:24
Updated my [proposal](https://github.com/Expensify/App/issues/47640#issuecomment-2297913211) to scroll to the selected status bar.

**Comment by luacmartins** [comment] 2024-08-29 15:14
I think we can remove the hold on this one. We don't strictly need to wait on the skeleton PR.

**Comment by nkdengineer** [comment] 2024-09-02 15:20
@rayane-djouah The first bug is fixed. For the second bug, `tabSelectorButtonHeight` has height is `42px`, is this expected?

**Comment by shawnborton** [comment] 2024-09-09 13:48
Yeah, that makes sense to fix that where the tabs aren't in view on refresh.

**Comment by dannymcclain** [comment] 2024-09-09 13:50
Can you explain what's happening at the beginning of the last video? I agree that it's nice to scroll the selected tab into view on load/reload, but in your second video it looks like the tabs have some kind of paging or auto-scrolling while just looking through them. Am I just mistaken?

**Comment by dannymcclain** [comment] 2024-09-09 15:06
Yes that's what I was talking about!

>I was just doing horizontal scrolling with my touchpad using two fingers

Awesome. No concerns from me then.

**Comment by luacmartins** [comment] 2024-09-23 00:33
Payment due

**Comment by bernhardoj** [comment] 2024-09-23 04:26
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-23 07:11
@mallenexpensify can I get a payment summary?

**Comment by mallenexpensify** [comment] 2024-09-23 15:41
Contributor: @bernhardoj owed $250 via Upwork
Contributor+: @rayane-djouah owed $250 via NewDot

@bernhardoj  can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021833233716363835239

@rayane-djouah plz complete the BZ checklist. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bernhardoj** [comment] 2024-09-23 15:51
@mallenexpensify I've requested the payment via ND.

**Comment by JmillsExpensify** [comment] 2024-09-23 19:06
$250 approved for @bernhardoj

**Comment by mallenexpensify** [comment] 2024-09-23 22:14
@rayane-djouah can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021833233716363835239

Sorry, I thought I 'hired' you earlier, not just invited you. 

Test case created
- https://github.com/Expensify/Expensify/issues/430448

**Comment by mallenexpensify** [comment] 2024-09-23 22:20
Thanks @rayane-djouah , you're paid, payment comment updated above.

**Closed by mallenexpensify** 2024-09-23 22:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
