### ISSUE TITLE
[HOLD for payment 2023-09-29] Find a better solution for removing visibilityListeners when changing the visible reports

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#27502] opened 2023-09-15 08:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

While navigating through the app, we're adding all components to the navigation stack. When using Web or Desktop, both of which show LHN and the ReportPage simultaneously, we never unmount the components from a previous report when navigating to a new one.

That is a problem because all reports have an event listener attached to them related to the app visibility, so every time a user leaves the application and go back to it, we do a `OpenReport` call. That means that for all reports in the history, we would do one `OpenReport` call.

We've removed the `OpenReport` call after discussing it [here](https://expensify.slack.com/archives/C05LX9D6E07/p1694749244763619), but that is not removing the listener, it's just checking inside the listener if we should really call the function.

One possible way to solve this is to have a function related to the FreezeWrapper, that every time we freeze a screen in the stack, it removes the listener, but other solutions might be explored.

## Action Performed:
Break down in numbered steps
- on Desktop, navigate through several reports
- Minimize the application and open it again
- Check the network table

## Expected Result:
Describe what you think should've happened
- Only one call to OpenReport was done

## Actual Result:
Describe what actually happened
- Several calls to OpenReport are done

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by staszekscp** [comment] 2023-09-15 08:55
Hi! I'll work on this issue :)

**Comment by danieldoglas** [comment] 2023-09-15 08:56
@mallenexpensify I'll remove you from this one since we don't need to manage contributors for now!

**Comment by staszekscp** [comment] 2023-09-18 06:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Fix removal logic of `visibilityListeners` on web and desktop.

### What is the root cause of that problem?

Currently on web and desktop there is an issue with setting multiple event listeners for report visibility - it is related to the fact that reports were not being unmounted at all, so the cleanup function that was supposed to remove listeners was not called.

### What changes do you think we should make in order to solve the problem?

Move the logic of setting `visibilityListeners` to a separate `useEffect` hook that would operate on `isFocused` logic provided by `react-navigation`. This way we will make sure that the report that is currently focused is actually sending the correct event - namely it is actually visible.

### What alternative solutions did you explore? (Optional)

Attaching the logic to `FreezeWrapper`, but it would require many more changes in the codebase, and it is not a clean the cleanest solution anyway

**Comment by adamgrzybowski** [comment] 2023-09-18 09:34
👁️ 👁️

**Comment by mallenexpensify** [comment] 2023-10-04 23:14
Contributor+: @parasharrajat is due $500

Regression Test isn't needed so closing!

**Closed by mallenexpensify** 2023-10-04 23:14 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:48
$500 payment approved for @parasharrajat based on BZ summary.
