### ISSUE TITLE
Loader is appeared for a short time when clicking on an image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24458] opened 2023-08-11 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and any chat that has image in it (if not send any image).
2. Click on the image and open it. You can see a loader for a short time at the beginning of loading
## Expected Result: 
Loader shouldn't be appeared for a short time when clicking on an image
## Actual Result: 
Loader is appeared for a short time when clicking on an image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
https://expensify.slack.com/archives/C049HHMV9SM/p1691058127041499
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1691058127041499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DrLoopFall** [comment] 2023-08-12 13:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The loading indicator is shown for a very short time when viewing an image.

### What is the root cause of that problem?

When the image is displayed from the cache, it takes a few milliseconds to load, during that time the `FullscreenLoadingIndicator` is displayed for a quick frame.

### What changes do you think we should make in order to solve the problem?

The ideal solution would be to delay the `FullscreenLoadingIndicator` for a few milliseconds like 50ms, so the `FullscreenLoadingIndicator` wouldn't flash if the load time is negligible.

**Comment by neonbhai** [comment] 2023-08-12 14:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loader is appeared for a short time when clicking on an image

### What is the root cause of that problem?
The `imageView` component is missing a delay logic in the image loading functions:

We need to add custom logic to show isLoading indicator if the loading time is more than `200ms` (Ref [here](https://medium.com/@kaleemkhan/what-is-the-ideal-waiting-time-before-you-show-loading-indicator-cf094528faec))
If times smaller than this should not show loading indicator here.

### What changes do you think we should make in order to solve the problem?
We will be adding a timeOut of 200ms on the `imageLoadingStart()` function here that will delay the setting of `isLoading` prop. We will abort the setting of `isLoading` prop (using an if condition) if image has loaded by the time `setTimeOut` runs.

The default value of `isLoading` will be set to false, as we are optimistic about the image loading in under 200ms

### What alternative solutions did you explore? (Optional)
xx

**Comment by trjExpensify** [comment] 2023-08-14 10:11
Oh hm, we haven't solved image caching just yet. There's an initiative in development, but it's temporarily paused as we await another project to complete surrounding a server migration. 

@Beamanator @kidroca can I get a quick second opinion from you before I close this out?

**Comment by DrLoopFall** [comment] 2023-08-14 16:55
Hi @kidroca,

As the delay is negligible for human perception, the user won't notice anything, also there's no risk of displaying the modal without the loader or the image because there's a transition (of 300ms) for showing the modal and the delay is consumed in this transition time.

I've added a video of the result, we can clearly see in this video, only two frames (on my system at 60fps) in transition are displayed before the image loads, so by using a small delay we can prevent the displaying the loader during this time.

https://github.com/Expensify/App/assets/120749263/4f26c782-cee8-4c6a-b1c5-65c65155d3ed

Frame-by-frame screenshots:
![](https://github.com/Expensify/App/assets/120749263/9186686e-d045-4298-b9f5-cf7ecff70a14)
![](https://github.com/Expensify/App/assets/120749263/2085b8ad-645e-443e-9ac6-f08d7a8c81e4)
![](https://github.com/Expensify/App/assets/120749263/fd5ff503-bbf3-4e49-a033-587f977cfeda)

**Comment by DrLoopFall** [comment] 2023-08-14 18:11
For reference, here's a video of **first load** with the 50ms delay, here we can see as the time delay is negligible, we can see the loader in an instant as it's very hard for human eyes to perceive this delay.


https://github.com/Expensify/App/assets/120749263/c813d785-b101-4b10-8793-e49ffb85ebb9

**Comment by kidroca** [comment] 2023-08-15 10:04
@DrLoopFall,

Thank you for the video examples. They clearly illustrate the loader's behavior in your environment. A few considerations:

1. **Dev vs. Production**: Your samples come from `localhost` and a dev build. The dev environment is populated with unoptimized debug-friendly code, leading to slower render cycles and a perceived slowdown in transitions. Here's how the interaction looks on our production site, where the transition, even with a brief loader appearance, feels smoother:

     https://github.com/Expensify/App/assets/12156624/e7ca1ea5-4e17-4937-8ff5-06aebeb7efe2

2. **Time-based Solutions**: Relying on timeouts can be fragile. Currently, the 300ms transition time conveniently covers our delay. However, what if the transition time changes in the future? A style update might inadvertently necessitate a functional adjustment elsewhere.

3. **A Lower-Level Approach**: I suggest addressing this at the component level. The `react-native Image` component supports a loading indicator: [https://reactnative.dev/docs/image#loadingindicatorsource](https://reactnative.dev/docs/image#loadingindicatorsource). Instead of managing loading in our custom `ImageView`, we should leverage this. By delegating the loading decision to the `Image` component, which has the context of cache and image load status, we can more effectively handle when to show the loader. Currently we always start with a loader which seems to be causing the present hiccup, while the native image component would simply render the image and not start witht the fallback content, when the image is cached.

**Comment by DrLoopFall** [comment] 2023-08-15 17:12
I think https://reactnative.dev/docs/image#loadingindicatorsource only supports displaying an image, we can't render custom components(`FullscreenLoadingIndicator`), so I think we can't use it.

Also, there's [Image.querycache](https://reactnative.dev/docs/image#querycache), which we can use, it works on native platforms, but on the web for the first load(after a refresh), it always returns the file is not cached even if it's cached by the browser.

**Comment by trjExpensify** [comment] 2023-08-21 11:51
Thanks for the discussion here, all! 

>Here's how the interaction looks on our production site, where the transition, even with a brief loader appearance, feels smoother:

I tend to agree with this sentiment. Should we close this out? CC: @Beamanator as well

**Comment by Beamanator** [comment] 2023-08-22 09:07
> I think https://reactnative.dev/docs/image#loadingindicatorsource only supports displaying an image, we can't render custom components(`FullscreenLoadingIndicator`), so I think we can't use it.

Maybe that would be fine, if it solves our "Currently we always start with a loader which seems to be causing the present hiccup" problem? It would be nice to see what this looks like and get Design's approval / rejection of that idea

@trjExpensify I thinkkk @kidroca is recommending we do make a change here so I don't think we should close this out quite yet

**Comment by kidroca** [comment] 2023-08-22 09:31
Thanks for chiming in @Beamanator,

I don't lean strongly on making a change here; in fact, I'd rather we do nothing at this point or risk introducing unneeded complexity.

What I pointed out earlier might work for images, but I believe we'd have the same problem for PDFs. The PDF component probably has a similar field to manage loading natively, but is it worth addressing a minor cosmetic issue?

I think the Attachment carousel should have an overhaul project at some point to make it up to date with modern attachment galleries, and that's the place I think we should address the loading experience.

**Comment by trjExpensify** [comment] 2023-08-23 12:24
>I don't lean strongly on making a change here; in fact, I'd rather we do nothing at this point or risk introducing unneeded complexity.

+1. 

>I think the Attachment carousel should have an overhaul project at some point to make it up to date with modern attachment galleries, and that's the place I think we should address the loading experience.

Yeah, I think that kind of improvement should be considered adjacent to this issue.

**Comment by trjExpensify** [comment] 2023-08-30 13:31
Okay, I'm back from OoO. Seems like we're in agreement with the do nothing approach. If someone wants to raise more broader wholesale improvements to the attachment carousel, do so in slack. Thanks everyone!

**Closed by trjExpensify** 2023-08-30 13:31 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
