### ISSUE TITLE
[HOLD for payment 2024-05-08] [Simplified Collect][CLEAN UP][LOW] Standardize on Workspace wrapper

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37898] opened 2024-03-07 15:10 UTC
### Problem 
Coming from [here](https://github.com/Expensify/App/pull/37621#discussion_r1515780864), we have a few wrappers we use in Workspace pages, i.e. `WorkspacePageWithSections`, `AdminPolicyAccessOrNotFoundWrapper` and `PaidPolicyAccessOrNotFoundWrapper`. We should standardize on using a single one for all our pages.

Those wrappers also break the not-found views.

Going to e.g. [https://staging.new.expensify.com/workspace/dssaddssdaads/categories`](https://staging.new.expensify.com/workspace/dssaddssdaads/categories%60) we see duplicated not found (that's what is the scope of the other issue) and after pressing the back button we see another ones...

### Why is this important
DRYs code and makes it more maintainable

### Solution
Investigate how to combine them and update all usages.

cc @kosmydel 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-03-13 04:44
Added a weekly here since this is low and in the polish bucket.

**Comment by luacmartins** [comment] 2024-03-13 05:49
Polish item

**Comment by kosmydel** [comment] 2024-03-21 09:42
A new wrapper `FeatureEnabledAccessOrNotFoundWrapper.tsx` emerged in [this PR](https://github.com/Expensify/App/pull/37902).

I've consulted it internally, and someone from SWM will take care of this issue.

**Comment by BrtqKr** [comment] 2024-03-21 09:48
Hey, I'm an engineer from SWM, I'll be taking over this issue 👋

**Comment by luacmartins** [comment] 2024-03-21 20:24
Nice! Excited for this one! @BrtqKr would you mind sharing the general approach you're thinking of taking before we dive deep into the code?

**Comment by BrtqKr** [comment] 2024-03-25 11:50
@luacmartins the code is literally identical in most of those wrappers, so the idea is to:

1. Merge `AdminPolicyAccessOrNotFoundWrapper` and `PaidPolicyAccessOrNotFoundWrapper` into a single `AccessOrNotFoundWrapper`. `AccessOrNotFoundWrapper`  will receive `accessVariants` array prop, which will be mapped into a proper function for determining whether the not found page should be displayed, something like this to be more exact:

```
const POLICY_ACCESS_VARIANTS = {
    PAID: (policy: OnyxEntry<OnyxTypes.Policy>) => !PolicyUtils.isPaidGroupPolicy(policy) || !policy?.isPolicyExpenseChatEnabled,
    ADMIN: (policy: OnyxEntry<OnyxTypes.Policy>) => !PolicyUtils.isPolicyAdmin(policy),
} as const satisfies Record<string, (policy: OnyxTypes.Policy) => boolean>;
```

2.  Merge the the existing `FeatureEnabledAccessOrNotFoundWrapper` with the previously mentioned wrappers, based on the optional featureName param - we just check whether the feature is enabled and add it to the other conditions. And the other difference is a fallback page being displayed - for now that would be `NotFoundPage` for the standard conditions and `FullPageNotFoundView` if this is based on a feature flag.

**Comment by luacmartins** [comment] 2024-03-25 16:49
Sounds good. Could we add `FeatureEnabledAccessOrNotFoundWrapper` as a predicate to the `POLICY_ACCESS_VARIANTS` as well? Maybe each entry could be an object with a specific fallback page too so it can handle future changes without updating the wrapper itself, something like:

```
const POLICY_ACCESS_VARIANTS = {
    PAID: {
predicate: (policy: OnyxEntry<OnyxTypes.Policy>) => !PolicyUtils.isPaidGroupPolicy(policy) || !policy?.isPolicyExpenseChatEnabled,
fallback: NotFoundPage
},
 ...
```

**Comment by hayata-suenaga** [comment] 2024-03-27 04:55
hello hello 👋 

There are some PRs that add another set of new screens that should be limited to non-admin users.

Depending on when the unified wrapper that is suggested here is ready, we might use that one or create temporary wrappers. I'd appreciate it if you could share the rough ETA for it if you could, @BrtqKr 🙇

**Comment by BrtqKr** [comment] 2024-03-28 09:37
@hayata-suenaga, we'll be sending a PR with those changes this evening at the latest

**Comment by hayata-suenaga** [comment] 2024-03-28 15:58
I forgot to update here, but we're reassessing our approach to protecting routes (i.e., restricting screen access to certain users).

We started developing a pattern where a wrapper screen is created for each protected screen to check if the user has the necessary permissions to access it or not. Based on the user's access level, either the requested screen is displayed or the "not-found" page is displayed.

I understand that this GH ticket is to standardize this pattern and create a unified wrapper component.

However, after internal discussions, our engineers have decided to adjust our strategy. Instead of implementing access logic at the component level, we now prefer to do so in the navigation layer. React Navigation allows for the conditional rendering of screens within a navigator. We will use this feature to implement protected routes. This approach is recommended in [the React Navigation documentation](https://reactnavigation.org/docs/auth-flow/).

**Comment by hayata-suenaga** [comment] 2024-03-28 16:09
Our plan is to confirm that the conditional rendering approach does indeed work with our current codebase by using this pattern in the newly added accounting-related screens. If the approach is confirmed to be effective, we will replace the currently implemented wrappers with conditional rendering inside navigators.

**Comment by hayata-suenaga** [comment] 2024-03-28 16:11
While the conditional rendering is being tested, please cease work on this GitHub ticket and avoid introducing any new wrappers. 🙇

**Comment by hayata-suenaga** [comment] 2024-04-08 17:27
Update: We're delaying the potential refactoring that I mentioned in [this comment](https://github.com/Expensify/App/issues/37898#issuecomment-2025563876) as we faced some issues with the proposed pattern.

I'll further update here if there is a new development in the proposed refactoring.

**Comment by luacmartins** [comment] 2024-04-08 20:15
@hayata-suenaga can @BrtqKr continue to explore that solution in parallel?

**Comment by hayata-suenaga** [comment] 2024-04-08 23:56
> @hayata-suenaga can @BrtqKr continue to explore that solution in parallel?

Yes I think so 😄 I apologize that I held your work 🙇 @BrtqKr, you can resume working on this

**Comment by luacmartins** [comment] 2024-04-17 20:25
@BrtqKr did you get a chance to look into this again?

**Comment by BrtqKr** [comment] 2024-04-18 07:54
@luacmartins I'll finish the live markdown-related thing I'm working on right now and I'll take a look at this this evening. This shouldn't be much, but I might need to adjust the things I've done so far.

**Comment by BrtqKr** [comment] 2024-04-22 10:25
> Sounds good. Could we add `FeatureEnabledAccessOrNotFoundWrapper` as a predicate to the `POLICY_ACCESS_VARIANTS` as well? Maybe each entry could be an object with a specific fallback page too so it can handle future changes without updating the wrapper itself, something like:
> 
> ```
> const POLICY_ACCESS_VARIANTS = {
>     PAID: {
>          predicate: (policy: OnyxEntry<OnyxTypes.Policy>) => !PolicyUtils.isPaidGroupPolicy(policy) || !policy?.isPolicyExpenseChatEnabled,
>          fallback: NotFoundPage
>     },
>     ...
> }
> ```

In general, this was unnecessarily increasing complexity, so I ended up treating feature flags as a separate case. Overall, the main problem is the fact that those conditions can happen simultaneously, so we would need to somehow determine which one of them is more important. There might be different cases with a different priority, so I'd just make the feature flag the more important variant since it was able to cover all existing cases and there have been a lot of them.

**Comment by BrtqKr** [comment] 2024-05-14 07:36
It was merged some time ago  https://github.com/Expensify/App/pull/40598, not sure why Melvin is still mentioning us. Would you mind closing this issue, or is there anything left to do?

**Comment by luacmartins** [comment] 2024-05-14 22:37
It seems like we need to payout C+ @ahmedGaber93 for the PR review.

**Comment by JmillsExpensify** [comment] 2024-05-19 18:04
Payment summary: @ahmedGaber93 $500 for pr review and testing.

**Comment by JmillsExpensify** [comment] 2024-05-19 18:06
Offer sent via Upwork

**Comment by JmillsExpensify** [comment] 2024-05-19 18:19
Offer paid out, so closing out this issue.

**Closed by JmillsExpensify** 2024-05-19 18:19 UTC
Labels: Daily, Awaiting Payment, Bug
