### ISSUE TITLE
[$1000] Bug: Not seeing expand button after reaching third row in ios reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11844] opened 2022-10-14 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app in iOS
2. Navigate to a chat
3. Fill first two rows and add few more characters to reach the third row

## Expected Result:
Expand button should be shown

## Actual Result:
Expand button doesn't show up, unless you press enter to reach the third row or type few characters in the third row

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.15-2
**Reproducible in staging?:** y
**Reproducible in production?:** y

https://user-images.githubusercontent.com/43996225/195874466-588e767f-417a-4b30-9878-e079b75a5bcd.MP4

https://user-images.githubusercontent.com/43996225/195874500-975c922a-efdf-40ec-abf0-26e3338569a9.mov

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665694070058889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2022-10-14 23:48
Reproduced, can't find any other issues for this same bug.

**Comment by tylerkaraszewski** [comment] 2022-10-17 09:43
So, this does seem to be a "bug" here: https://github.com/Expensify/App/blob/main/src/components/Composer/index.js#L374

It's about as trivial a bug as I can think of, since the expand button shows up a few extra keystroke later anyway. I'll mark it external since it's clearly a display only bug.

**Comment by lschurr** [comment] 2022-10-17 15:23
Posted job. 

https://www.upwork.com/ab/applicants/1582029232576475136/job-details
https://www.upwork.com/jobs/~01ed68566e162a7e9b

**Comment by tienifr** [comment] 2022-10-18 13:53
#Proposal
##Problem
On iOS function `onContentSizeChange` returns incorrect height when we use paddingHorizontal. I believe it's the problem of React Native.
Pls check the evidence:

https://user-images.githubusercontent.com/113963320/196440389-7ae3ec93-87b7-4c5d-b2c5-6b29a3fad449.mp4

##Solution
in https://github.com/Expensify/App/blob/main/src/components/Composer/index.ios.js
we'll override `paddingHorizontal:0` in iOS and wrap `RNTextInput` with `View` within `style.ph8` to archive paddingHorizontal:8 as original. I also need to remove `style` in `propsToPass`, if not our style will be overrided

```diff
        this.state = {
-           propStyles: StyleSheet.flatten(this.props.style),
+           propStyles: StyleSheet.flatten([...this.props.style, styles.ph0]),
        };
```

```diff
-        const propsToPass = _.omit(this.props, 'selection');
+        const propsToPass = _.omit(this.props, 'selection','style');

        return (
+           <View style={styles.ph2}>
             <RNTextInput
                autoComplete="off"
                placeholderTextColor={themeColors.placeholderText}
                ref={el => this.textInput = el}
                maxHeight={this.props.isComposerFullSize ? '100%' : CONST.COMPOSER_MAX_HEIGHT}
                onContentSizeChange={e => ComposerUtils.updateNumberOfLines(this.props, e)}
                rejectResponderTermination={false}
                textAlignVertical="center"
                style={this.state.propStyles}
                /* eslint-disable-next-line react/jsx-props-no-spreading */
                {...propsToPass}
                editable={!this.props.isDisabled}
            />
+        </View>
```

https://user-images.githubusercontent.com/113963320/196441769-d94f48d4-cada-40a1-ae52-a1793b55ba12.mp4

**Comment by lschurr** [comment] 2022-10-18 19:18
Looks like a proposal has been added for review @parasharrajat

**Comment by parasharrajat** [comment] 2022-10-18 19:25
@tienifr's proposal sounds legit. But they mentioned that this is an issue with RN. Should we try to fix it upstream on RN? @lschurr

**Comment by puneetlath** [comment] 2022-10-18 19:34
I think we should create a PR for it both in our RN fork and upstream.

**Comment by parasharrajat** [comment] 2022-10-18 19:43
Ok, @tienifr Let's try to find a solution to fix it upstream on RN.

**Comment by tienifr** [comment] 2022-10-19 11:12
ok, sure

**Comment by parasharrajat** [comment] 2022-10-19 17:20
If this issue exists on Native iOS, then we can apply the workaround. Otherwise, a fix in RN is preferred.

**Comment by tienifr** [comment] 2022-10-20 08:03
@parasharrajat yes, It just happens on Native iOS. What do you think about my solution above?

https://user-images.githubusercontent.com/113963320/196891413-eee254e2-91f2-44c9-9691-089a0fb41af0.mp4

**Comment by parasharrajat** [comment] 2022-10-20 11:30
The video does not show the native iOS app. It is still RN. I meant to say to try it on Native iOS app.

**Comment by lschurr** [comment] 2022-10-24 16:32
Hi @parasharrajat - are we waiting for a new proposal on this one?

**Comment by parasharrajat** [comment] 2022-10-24 17:43
Yes, as per https://github.com/Expensify/App/issues/11844#issuecomment-1282906897, I am waiting for a fix on RN.

**Comment by lschurr** [comment] 2022-10-31 23:10
Price doubled.

**Comment by lschurr** [comment] 2022-11-09 15:21
Price doubled to $1000 - https://www.upwork.com/jobs/~01ed68566e162a7e9b

**Comment by fedirjh** [comment] 2022-11-15 22:40
## Proposal

### Problem 

there is certainly some problem with `onContentSizeChange` , these are some issue that I faced during testing this : 

- https://github.com/facebook/react-native/issues/22638 , `onContentSizeChange` will not fire after the first line (2nd ..)
- https://github.com/facebook/react-native/issues/15326 , the padding is included in the contentSize

those issue are present from a long time without a fix https://github.com/facebook/react-native/issues/22638#issuecomment-479058908 , and I don't think anyone will spend time to fix on RN

### Solution 

Alternatively we can use `onLayout` instead and get `height` on layout changes , if you accept this proposal then we either have to apply this change for android too or create separate `updateNumberOfLines` for iOS

Note : same changes apply to android if we choose to switch on android too

https://github.com/Expensify/App/blob/210903a959089e0512665029a5d143bb94e1da46/src/components/Composer/index.ios.js#L106
```diff
-                onContentSizeChange={e => ComposerUtils.updateNumberOfLines(this.props, e)}
+                onLayout={e => ComposerUtils.updateNumberOfLines(this.props, e)}
```

Changes to `updateNumberOfLines`

https://github.com/Expensify/App/blob/210903a959089e0512665029a5d143bb94e1da46/src/libs/ComposerUtils/index.native.js#L27
```diff
-      const inputHeight = lodashGet(e, 'nativeEvent.contentSize.height', null);
+      const inputHeight = lodashGet(e, 'nativeEvent.layout.height', null);
```

### Tests

### IOS

https://user-images.githubusercontent.com/36869046/202035767-ca7d93a1-62fd-4c0a-bd28-cca270ec6b9d.mp4

### Android

[Android.webm](https://user-images.githubusercontent.com/36869046/202039520-4fd78043-4934-496e-bf0e-4f448fd3bb78.webm)

**Comment by lschurr** [comment] 2022-11-18 15:39
@parasharrajat - Do you have an update on this one?

**Comment by parasharrajat** [comment] 2022-11-18 20:27
Oh, I missed this issue. Thanks for the ping. Taking a look.

**Comment by lschurr** [comment] 2022-11-21 15:51
Sorry for another ping - do you have an update @parasharrajat?

**Comment by parasharrajat** [comment] 2022-11-21 15:52
Thanks for the ping. Checking now...

**Comment by fedirjh** [comment] 2022-11-22 15:43
@parasharrajat any update ?

**Comment by parasharrajat** [comment] 2022-11-22 16:13
Didn't get the time to complete it yesterday. But going through the docs and etc... You will have it in a few minutes.

**Comment by parasharrajat** [comment] 2022-11-22 16:23
Ok, I checked. It seems pretty straightforward as the proposal https://github.com/Expensify/App/issues/11844#issuecomment-1282429283. 

But we earlier decided to solve this on RN. 

> and I don't think anyone will spend time to fix on RN

That's why we are happy to compensate to fix an issue for the community. 

Anyways, let me open a new discussion and see if we want to go with either of the solutions.

**Comment by parasharrajat** [comment] 2022-11-22 23:29
The discussion is leading towards a solution that fixes this issue in RN core. Also, anyone is able to prove that this is issue with iOS platform not with RN, then we may rethink to solve it here.

**Comment by lschurr** [comment] 2022-11-23 16:28
So this should remain on hold?

**Comment by parasharrajat** [comment] 2022-11-23 17:06
Not on Hold, but active for proposals.

**Comment by tjferriss** [comment] 2022-11-23 18:28
Reviewing the issue based on the [weekly bug update chore](https://stackoverflow.com/c/expensify/questions/8208):

@puneetlath  this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:
- Decide whether any proposals currently meet our guidelines and can be approved as-is
- For any that can't, please take this issue internal and treat it as one of your highest priorities
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by trjExpensify** [comment] 2022-11-23 19:06
We've chatted about this one [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669138992254909) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669134887902079). Let's close it and fix it upstream in RN. 👍 

To Rajat's point, this still stands. Bring it up in a Slack thread if that's the case! 

>anyone is able to prove that this is issue with iOS platform not with RN, then we may rethink to solve it here

**Closed by trjExpensify** 2022-11-23 19:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by situchan** [comment] 2023-03-03 15:46
@kbecciv https://github.com/Expensify/App/issues/15639 you just created is duplicated with this one.
Also related to https://github.com/Expensify/App/issues/14369
