### ISSUE TITLE
Web - Public room - Main chat view flickers when returning from thread and hovering over chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31119] opened 2023-11-09 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out if logged in.
2. Navigate to https://staging.new.expensify.com/r/2376199970894587.
3. Click on the thread.
4. Click on the browser back button to return to the main chat.
5. Hover over the main chat.

## Expected Result:
The main chat does not flicker.

## Actual Result:
The main chat flickers.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5d540659-2faa-4c85-9f30-bab7d0c08701

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2023-11-09 14:15
Investigating.

**Comment by s-alves10** [comment] 2023-11-09 16:35
This is a regression from the PR https://github.com/Expensify/App/pull/28793
I think @perunt have more context on this

**Comment by perunt** [comment] 2023-11-09 16:42
it looks like we lost the entire comment with the thread. 
could you please do some records with the Network tab?

**Comment by youssef-lr** [comment] 2023-11-09 16:57
Removing blocker as this isn't a major bug

**Comment by youssef-lr** [comment] 2023-11-09 17:03
@perunt I slowed down the video and it seems like when we navigate back the page scrolls up and down quickly

**Comment by youssef-lr** [comment] 2023-11-13 19:33
PR causing this issue was reverted. Closing!

**Closed by youssef-lr** 2023-11-13 19:33 UTC
Labels: Engineering, Daily, Overdue
