### ISSUE TITLE
New Room- Characters appear/disappear when using a special characters (e.g.: + or &)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13042] opened 2022-11-25 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12899

## Action Performed:
1. Launch the app
2. Login with any account
3. Click green circle button
4. Create room
5. In the room name type: "test123"
6. Put the cursor just after the word "test"
7. Type a space
8. Verify that the result is "test_123" and that the cursor is right after the underscore and not in the end
10. Type a special char (e.g.: + or &)

## Expected Result:
Characters are temporarily appearing and disappearing when using a special characteristics(e.g.: + or &) after space

## Actual Result:
Characters are temporarily appearing and disappearing when using a special characteristics(e.g.: + or &) after space
In IOS app when typing a special characteristics its briefly visible.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.31.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203989818-027cad8f-7b16-45a2-9ac4-f787a4243f48.MP4

https://user-images.githubusercontent.com/93399543/203989823-8ceb8ba6-44ac-4be7-affc-1c48aa561af7.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2022-11-25 13:07
I won't say this is a bug, the text input is being changed and depending on the device speed you may or may need see the change happening (refereed to shaking in the GH body)

**Comment by sophiepintoraetz** [comment] 2022-11-29 00:39
Came in over the weekend - will look at this tomorrow.

**Comment by marcaaron** [comment] 2022-11-30 00:20
Yeah can we maybe clarify what "shaking" means in this context? It looks like those characters are being overwritten (though I haven't confirmed this). Which is against our form guidelines as stated here:

![Image](https://user-images.githubusercontent.com/32969087/204677107-e5e30c3d-599f-4bc6-a30f-7573176b68a1.png)

https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#modifying-user-input-on-change

**Comment by sophiepintoraetz** [comment] 2022-12-02 02:11
Ack have not had time to replicate this!

**Comment by sophiepintoraetz** [comment] 2022-12-05 04:56
Hmm, I went to go replicate this but maybe @marcaaron you can help me:

I've tried installing both versions of the app (current and 1.2.31.7) but I do not have the `# New Room` option show - do you know if there is a regional variance or why wouldn't this show for me?
![image](https://user-images.githubusercontent.com/42940078/205551414-df6e76d3-9c3f-41e6-a479-b07d84479053.png)

**Comment by sophiepintoraetz** [comment] 2022-12-05 05:08
@kbecciv - by shaking, do you mean that the special character temporarily appears and then disappears? If so, I think I have successfully reproduced this on iOS on v1.2.36.1

https://user-images.githubusercontent.com/42940078/205553890-2a6f9bd3-9b53-416b-ac9e-5c3d894eda68.mov

**Comment by kbecciv** [comment] 2022-12-05 23:29
@sophiepintoraetz Yes, correct - I meant that the special character temporarily appears and then disappears.

**Comment by sophiepintoraetz** [comment] 2022-12-20 22:20
Max is OOO

**Comment by bondydaa** [comment] 2022-12-26 16:50
I think max is coming back tomorrow from OOO but I can probably also help out if needed

I think we should solve this by heeding what Marc called out here: https://github.com/Expensify/App/issues/13042#issuecomment-1331486842 and completely remove the automatic editing of the user's input and have some front side validation on submit (and backend validation too in case that doesn't already exist)

**Comment by JmillsExpensify** [comment] 2022-12-26 19:04
This issue recently hit 30 days, which is how it ended up on my radar. Here's two cents:

 - I don't think this issue should hold up WAQ, as it's for a beta feature that has no set launch date
 - Further, I think we should associated this with the form refactor given that it violates our stipulated behavior
 
 As for the solution, I agree that this should instead have front-end validation so that information isn't removed after being added. But again, I don't think this is a bug that should block the roadmap, nor should any other bug related to beta features that we have no plans to introduce for months and months from now. 

Feel free to fix it, but again, I'm throwing 'HOLD WAQ' in the title in the meantime.

**Comment by madmax330** [comment] 2022-12-30 08:40
on hold

**Comment by madmax330** [comment] 2023-01-09 08:37
on hold

**Comment by JmillsExpensify** [comment] 2023-01-12 05:43
Removed the WAQ hold for continuity.

**Comment by madmax330** [comment] 2023-01-12 07:34
I think for this issue we want the same solution as here: https://github.com/Expensify/App/issues/13676#issuecomment-1379815101

It's the same problem of the special characters being trimmed out. So we should just leave them and show an error

**Comment by trjExpensify** [comment] 2023-01-12 11:54
Doesn't seem like this isn't an issue anymore. I can't reproduce it on iOS `v1.2.50-14` at least, we're following the correct Forms pattern.

https://user-images.githubusercontent.com/16232057/212060137-f414957c-f91f-402a-ac3e-957f8f35656f.MP4

**Comment by sophiepintoraetz** [comment] 2023-01-13 02:59
Yeah, I'm also not able to reproduce this so closing and adding reproduction steps needed.

**Closed** 2023-01-13 02:59 UTC
Labels: Engineering, Weekly, Needs Reproduction, Bug
