### ISSUE TITLE
[$250] When requesting money from a new user "Hidden" appears after few seconds 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40030] opened 2024-04-10 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @TMisiukiewicz 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1712736509774009

## Action Performed:
1. Open app
2. Click on FAB green button 
3. Request money and enter an email address which does not have expensify account
4. Observe the header

## Expected Result:
Should either stay with the email address or Hidden

## Actual Result:
it displays the e-mail first, and after getting a response from the API it changes it to "Hidden". After refreshing, the "Hidden" is still visible for a moment and then it changes back to e-mail.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/77d463c7-2e74-4f98-b51a-92761ffb55cc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fc8fc39ef1652aa</li>
        <li>Upwork Job ID: 1780905656370585600</li>
        <li>Last Price Increase: 2024-05-02</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2024-04-18 10:26
@TMisiukiewicz is this something you had a proposal for already?

**Comment by TMisiukiewicz** [comment] 2024-04-18 10:30
@muttmuure no, I haven't been working on this, I just reported it

**Comment by shahinyan11** [comment] 2024-04-19 14:18
Can anyone clarify please if the `email address` or `hidden` should always be visible ?

**Comment by muttmuure** [comment] 2024-04-23 18:24
You should see the email you just entered

**Comment by muttmuure** [comment] 2024-04-26 10:39
Still waiting for proposals

**Comment by muttmuure** [comment] 2024-04-29 17:02
Still waiting for proposals

**Comment by muttmuure** [comment] 2024-05-01 14:27
Waiting for proposals

**Comment by dominictb** [comment] 2024-05-06 03:03
This should be BE issue. When FE makes IOU request, the API response from BE includes the onyx updates for `personalDetailList`, but the update value doesn't include the `email` value for `email address which does not have expensify account`.

**Comment by neil-marcellini** [comment] 2024-05-06 22:01
I'm working on something related and I came across this issue, so I will fix it.

**Comment by neil-marcellini** [comment] 2024-05-06 22:03
Removing C+ since I don't think they will be needed for this backend issue.

**Comment by neil-marcellini** [comment] 2024-05-14 18:48
The PR is still under review, but should be merged this week.

**Comment by neil-marcellini** [comment] 2024-05-21 19:35
The PRs were merged last week, but still haven't been deployed to production due to backend chaos.

**Comment by mvtglobally** [comment] 2024-06-10 12:33
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-06-12 10:11
Looks like this is done, good work Neil!

**Closed by muttmuure** 2024-06-12 10:11 UTC
Labels: Reviewing, External, Weekly, Internal, Help Wanted, Bug
