### ISSUE TITLE
Request money wrong convert USD to VNĐ currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24510] opened 2023-08-13 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with new user
2. Click + on compose => Request money
2. Select currency VND
3. Input 1 => next => request
4. Click + on compose => Request money
5. Select currency USD
6. Input 1 => next => request
7. Observe that the total amount is wrong
## Expected Result: 
Amount displayed correctly when converting from USD to VND
## Actual Result: 
Amount displayed incorrectly when converting from USD to VND

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Needs reproduction (Requires vnd as default currency)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4dcf559f-a8de-485d-b1a4-212b04a85aeb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691233790219149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-08-13 22:56
This is dupe I think https://github.com/Expensify/App/issues/24086

**Comment by Victor-Nyagudi** [comment] 2023-08-14 06:15
Yes, this is similar to https://github.com/Expensify/App/issues/24086 which is currently being worked on internally by @aldo-expensify . 

In fact, this was previously reported with a similar title: https://github.com/Expensify/App/issues/19792

There's also another currently open currency issue: https://github.com/Expensify/App/issues/23235

**Comment by aldo-expensify** [comment] 2023-08-14 23:55
Thanks @Victor-Nyagudi and @ShogunFire , yes it is a dupe of https://github.com/Expensify/App/issues/24086 with different currency.

I reproduced in `main` by creating a workspace with currency VND, and then creating a money request for 1 VND and then 1 USD.

I tested and  can confirm that the PR https://github.com/Expensify/App/pull/24175 is fixing this

**Closed by aldo-expensify** 2023-08-14 23:55 UTC
Labels: Daily, Needs Reproduction, Bug
