### ISSUE TITLE
Category settings - The background changes if you refresh the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37569] opened 2024-02-29 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature , No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Login as an admin of a collect policy
3. Navigate to Workspace Settings > Collect Workspace > Categories > Settings
4. Reload the page

## Expected Result:
The background not changes

## Actual Result:
The background changes to chat page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/4dcb078d-b334-4642-b728-bb413b274ff5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2024-02-29 21:23
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by situchan** [comment] 2024-02-29 21:30
Looks like dupe of https://github.com/Expensify/App/issues/37505

**Comment by ikevin127** [comment] 2024-02-29 22:05
^ which was closed in favour of https://github.com/Expensify/App/issues/37517.

I already posted [a proposal](https://github.com/Expensify/App/issues/37517#issuecomment-1971607298) there detailing the RCA / solution.

If this is a real deploy blocker and needs to be handled ASAP, my proposal can be applied here - I'll be happy w/ half the bounty from this one in case it helps ✌️

Otherwise if not a blocker I'm willing to handle this one too, based on the same proposal from https://github.com/Expensify/App/issues/37517.

**Comment by puneetlath** [comment] 2024-02-29 22:20
Going to demote from deploy blocker since I don't think this affects real users yet.

**Comment by luacmartins** [comment] 2024-02-29 22:20
This is a dupe of https://github.com/Expensify/App/issues/37517. Closing

**Closed by luacmartins** 2024-02-29 22:20 UTC
Labels: Engineering, Daily, Bug
