### ISSUE TITLE
[HOLD for payment 2024-09-16] [$125] Advanced approvals - Left and right side of the empty state image is cut off

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48531] opened 2024-09-04 09:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Workflows.
3. Enable Add approvals.
4. Click on the existing approval workflow.
5. Click Additional approver.

## Expected Result:
The empty state image will not be cut off.

## Actual Result:
The left and right side of the empty state image is cut off.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<img width="361" alt="Bug6592373_1725411670665!ss" src="https://github.com/user-attachments/assets/203af09e-a248-4ebe-8e41-817532a7b7f8">

https://github.com/user-attachments/assets/c053726e-334c-42d6-b625-1c611dc10b12

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b31f1fa567915230</li>
        <li>Upwork Job ID: 1831311067019688732</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103814857</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment] 2024-09-04 09:07
We think that this bug might be related to #wave-control

**Comment by bernhardoj** [comment] 2024-09-04 09:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The approver empty state icon is cut off.

### What is the root cause of that problem?
The icon width is bigger (144) than the width that we set to the view (136).
https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L235-L243

Also, we don't set the content fit prop, so the image/icon is cut off.

### What changes do you think we should make in order to solve the problem?

First, set the content fit to `contain`.
```
contentFitImage='contain'
```

Then, we can keep the current size, 136, or increase it to 144.

**Comment by mountiny** [comment] 2024-09-04 15:30
Adding @DylanDylann as a C+ from the offending PR

**Comment by bernhardoj** [comment] 2024-09-04 15:49
PR is ready

**Comment by DylanDylann** [comment] 2024-09-16 04:02
@slafortune let's pay @bernhardoj only and close this one. The checklist is no need here.

**Comment by mountiny** [comment] 2024-09-16 11:24
$125 to @bernhardoj

**Comment by bernhardoj** [comment] 2024-09-16 15:46
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-16 21:14
$125 approved for @bernhardoj

**Comment by DylanDylann** [comment] 2024-09-17 02:35
@slafortune @mountiny Let's close this issue

**Closed** 2024-09-17 09:47 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
