### ISSUE TITLE
[$250] Web - Attachment - "Worker was terminated" console error when closing a PDF

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47810] opened 2024-08-21 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4880362&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new Gmail account
3. Navigate to FAB - Start chat
4. Start a 1:1 DM with any account
5. Upload a small PDF (included)
6. Upload a large PDF (included)
7. Open the large PDF
8. Close the large PDF
9. Open the small PDF
10. Close the small PDF

## Expected Result:
I should be able to close the PDF without a console error.

## Actual Result:
"Worker was terminated" console error when closing a PDF after opening and closing a different, larger PDF. Sometimes I get the console error when closing an image attachment too.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a40d7e8b-9033-4c4b-b1fb-87277c1e0827

[Bug6578472_1724261778945!Small_PDF.pdf](https://github.com/user-attachments/files/16697347/Bug6578472_1724261778945.Small_PDF.pdf)
[Bug6578472_1724261778936!Large_PDF.pdf](https://github.com/user-attachments/files/16697349/Bug6578472_1724261778936.Large_PDF.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5b10381ea8600ab</li>
        <li>Upwork Job ID: 1827398804771215994</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103709560</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment] 2024-08-21 18:46
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-08-21 21:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Worker was terminated" console error shows up when closing a PDF view while it is still loading.

### What is the root cause of that problem?

This error occurs because `loadingTask.destroy()` is not working correctly, as explained in https://github.com/mozilla/pdf.js/issues/11595.

We previously fixed this issue in https://github.com/Expensify/App/issues/31209, but it has reappeared since. The reason is that [the previous fix](https://github.com/Expensify/App/blob/f12c1fff5f5344efb20cc48e2805e766c6b5523d/patches/react-pdf%2B7.7.3.patch) patches the `node_modules/react-pdf/dist/esm/Document.js` file, but the app now uses `node_modules/react-pdf/dist/cjs/Document.js`.

![image](https://github.com/user-attachments/assets/c5c58741-477e-4934-9636-14cc32d58ad2)

### What changes do you think we should make in order to solve the problem?

In addition to the `esm/Document.js` file, we need to apply the same fix to `cjs/Document.js`.

Updated [`react-pdf+7.7.3.patch`](https://github.com/Expensify/App/blob/f12c1fff5f5344efb20cc48e2805e766c6b5523d/patches/react-pdf%2B7.7.3.patch) file will be:

```diff
diff --git a/node_modules/react-pdf/dist/cjs/Document.js b/node_modules/react-pdf/dist/cjs/Document.js
index 9bb0398..032d898 100644
--- a/node_modules/react-pdf/dist/cjs/Document.js
+++ b/node_modules/react-pdf/dist/cjs/Document.js
@@ -289,6 +289,7 @@ const Document = (0, react_1.forwardRef)(function Document(_a, ref) {
             pdfDispatch({ type: 'REJECT', error });
         });
         return () => {
+            loadingTask._worker.destroy();
             loadingTask.destroy();
         };
     }
diff --git a/node_modules/react-pdf/dist/esm/Document.js b/node_modules/react-pdf/dist/esm/Document.js
index b1c5a81..569769e 100644
--- a/node_modules/react-pdf/dist/esm/Document.js
+++ b/node_modules/react-pdf/dist/esm/Document.js
@@ -261,6 +261,7 @@ const Document = forwardRef(function Document(_a, ref) {
             pdfDispatch({ type: 'REJECT', error });
         });
         return () => {
+            loadingTask._worker.destroy();
             loadingTask.destroy();
         };
     }

```

**Comment by thienlnam** [comment] 2024-08-27 17:17
Ideally we can upgrade this version so we can remove the amount of patches we use. In the previous issue, it looks like we considered that but didn't due to a re-render issue in v7. Has that been solved since then? It's been a year https://github.com/Expensify/App/issues/31209#issuecomment-1807957023

**Comment by CyberAndrii** [comment] 2024-08-27 20:08
@thienlnam We're currently using v7.7.3, so most likely we already have a workaround for the re-rendering issue. I agree it would be a good idea to update to the latest version (v9), but it [still doesn't have a fix](https://github.com/wojtekmaj/react-pdf/issues/1062) for the 'Worker was terminated' error. I can probably submit a PR for them, and we would be able to upgrade after it's released.

**Comment by thienlnam** [comment] 2024-08-27 21:03
Thanks for the context - agree with patching for this issue since it's not resolved in the latest yet. 

However, I'm going to create another issue to remove the patches so we reduce the technical debt when we upgrade RN versions - if you'd like to submit an upstream PR for that issue that would be appreciated!

**Comment by thienlnam** [comment] 2024-08-27 21:07
@CyberAndrii Here's the issue if you're interested in doing that https://github.com/Expensify/App/issues/48124

**Comment by CyberAndrii** [comment] 2024-08-27 21:35
Thanks! I'll submit a PR for this issue tomorrow and then look into fixing it in the upstream repo.

**Comment by kevinksullivan** [comment] 2024-09-10 19:40
Paid @paultsimura , offer sent to @CyberAndrii . Let me know when you accept!

**Comment by CyberAndrii** [comment] 2024-09-11 06:04
@kevinksullivan Accepted the offer

**Comment by kevinksullivan** [comment] 2024-09-11 17:31
all set

**Closed by kevinksullivan** 2024-09-11 17:31 UTC
Labels: Reviewing, External, Weekly, Bug
