### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Dev - Home address - AddressPage (and many more) – Missing displayName prop leads to console error (testID undefined)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28334] opened 2023-09-27 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the profile popup via LHN
2. Click the profile image icon to open up profile settings
3. Click 'Personal details'
4. Click 'Home address'

## Expected Result:
The testID property for the page should be assigned a valid value.

## Actual Result:
The testID property is undefined. As a result, end-to-end testing is compromised, due to many pages missing testIDs.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.74-0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6f2c889c-5d56-4df5-8b67-beb6e22e3b15

https://github.com/Expensify/App/assets/93399543/c8df92f8-208d-4665-9fa1-1f029280a485

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samueljh1
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695735346255799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010af2a5f37c5f7f2f</li>
        <li>Upwork Job ID: 1707080289779253248</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>samueljh1 | Reporter | 27506510</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by ikevin127** [comment] 2023-09-27 17:28
# Proposal
## Please re-state the problem that we are trying to solve in this issue
The testID property is undefined. As a result, end-to-end testing is compromised, due to many pages missing testIDs.

## What is the root cause of that problem?
The testID property is undefined for multiple pages and due to it being a required prop we get the reported console errors.

## What changes do you think we should make in order to solve the problem?
Add testID's to all the pages which require it.

## What alternative solutions did you explore? (Optional)
N/A

**Comment by HardikChoudhary24** [comment] 2023-09-27 17:44
### Proposal
### Please re-state the problem that we are trying to solve in this issue
-  AddressPage (and many more) – Missing displayName prop leads to console error (testID undefined)

## What is the root cause of that problem?

- The root cause of this issue is the absence of ```testID ={AddressPage.displayName}```  where ```AddressPage.displayName="AddressPage"``` for the AddressPage and similarly for other pages. 

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L132-L132

### What changes do you think we should make in order to solve the problem?

- To address this problem, we can resolve it by simply adding  ```testID ={AddressPage.displayName}```  and setting ```AddressPage.displayName="AddressPage"``` for each components missing the testID prop.
This will solve the issue perfectly.

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by HardikChoudhary24** [comment] 2023-09-27 17:52
> > ### Proposal
> > ### Please re-state the problem that we are trying to solve in this issue
> > 
> > * AddressPage (and many more) – Missing displayName prop leads to console error (testID undefined)
> > 
> > ## What is the root cause of that problem?
> > 
> > * The root cause of this issue is the absence of `testID ={AddressPage.displayName}`  where `AddressPage.displayName="AddressPage"` for the AddressPage and similarly for other pages.
> > 
> > https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L132-L132
> > 
> > ### What changes do you think we should make in order to solve the problem?
> > 
> > * To address this problem, we can resolve it by simply adding  `testID ={AddressPage.displayName}`  and setting `AddressPage.displayName="AddressPage"` for each components missing the testID prop.
> >   This will solve the issue perfectly.
> > 
> > **What alternative solutions did you explore? (Optional)** N/A
> 
> Check main branch)

Yes, I have Updated my proposal.

**Comment by Samueljh1** [comment] 2023-09-28 20:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The testID property for the affected pages (e.g., AddressPage) should be assigned a valid value, but it is instead undefined for many pages.
### What is the root cause of that problem?
Some pages have missing definitions for the displayName prop, which is commonly used to set the testID prop.
### What changes do you think we should make in order to solve the problem?
Add a definition for XXXPage.displayName for all pages using a ScreenWrapper, to ensure testID is not undefined.
### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2023-09-29 09:31
Sorry, I caused this bug. I think to fix it we should remove the lint rule that prevents setting `displayName` on class components, and instead enforce that all components have a displayName set.

**Comment by roryabraham** [comment] 2023-10-04 02:08
Assigning myself since I caused all these console errors in https://github.com/Expensify/App/pull/27978

**Comment by roryabraham** [comment] 2023-10-04 02:10
As stated above, I want to see a proposal for this issue which fixes it by:

1. Removing the custom lint rule from eslint-config-expensify that prevents setting `displayName` on class components
1. Adding a new lint rule that requires all React components to have their `displayName` property set.

**Comment by sobitneupane** [comment] 2023-10-04 08:19
@Samueljh1 I don't think this issue is reproducible any longer. Please let us know if the issue is still existent.

**Comment by sobitneupane** [comment] 2023-10-04 08:28
We haven't received any proposal that meets [the expectation](https://github.com/Expensify/App/issues/28334#issuecomment-1746020988).

**Comment by ikevin127** [comment] 2023-10-04 08:49
Updated my [proposal](https://github.com/Expensify/App/issues/28334#issuecomment-1737807744).
Of course it will require me to add the **displayName** for all those 77 components that are missing it.

**Comment by roryabraham** [comment] 2023-10-04 10:11
@ikevin127 the video looks good so I assigned you, but I'm a bit confused about one thing:

- from [the docs](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md#ignoretranspilername-default-false), `ignoreTranspilerName` defaults to `false` and the setting it to `true` seems to be what makes the `displayName` property required. Are the docs wrong or did you mean to include `ignoreTranspilerName=true` in your proposal? Or am I missing something?
- Please also create a follow-up PR in [eslint-config-expensify](https://github.com/Expensify/eslint-config-expensify) to remove the unused custom rule once it's no longer used in this codebase.

Thanks!

**Comment by roryabraham** [comment] 2023-10-04 10:12
Or if `ignoreTranspilerName` should indeed be false, I think that should be the default according to the docs, so we don't need to specify it.

**Comment by ikevin127** [comment] 2023-10-04 10:33
@roryabraham Indeed the `ignoreTranspilerName` is false by default according to the docs so it is not needed, will remove it.

PR's will be ready for review today.

**Comment by ikevin127** [comment] 2023-10-04 13:45
@sobitneupane PR https://github.com/Expensify/App/pull/28813 is ready for review.
Also for **eslint-config-expensify** PR https://github.com/Expensify/eslint-config-expensify/pull/76 is ready for review.

**Comment by Samueljh1** [comment] 2023-10-10 10:32
@roryabraham I applied to the job as a reporter but it has not been accepted. What is the process for this? Thanks.

**Comment by sobitneupane** [comment] 2023-10-13 18:10
I will be OOO next week. @mananjadhav will take over the issue.

**Comment by mananjadhav** [comment] 2023-10-13 18:10
Taking this over as C+ as per [note](https://expensify.slack.com/archives/C02NK2DQWUX/p1697220252914989).

**Comment by roryabraham** [comment] 2023-11-03 15:27
@garrettmknight we were missing a BZ assignee here, my fault! let's issue payments for this issue. Thanks!

**Comment by situchan** [comment] 2023-11-03 15:31
There was [regression](https://github.com/Expensify/App/issues/30373) fixed in https://github.com/Expensify/App/pull/30397

**Comment by garrettmknight** [comment] 2023-11-03 15:32
I can help out

**Comment by garrettmknight** [comment] 2023-11-03 16:42
@ikevin127 can you apply to [this job posting in Upwork](https://www.upwork.com/en-gb/ab/applicants/1720467603459784704/job-details) so I can pay you out?

**Comment by garrettmknight** [comment] 2023-11-03 16:44
@Samueljh1 can you accept [this offer](https://www.upwork.com/en-gb/nx/wm/offer/27506510) so I can pay you out?

**Comment by garrettmknight** [comment] 2023-11-03 16:44
Summary of payments:
- Urgency bonus: No
- Regression penalty: Yes
- Reporter: @Samueljh1 $50 
- Contributor: @ikevin127 $250
- Reviewer: @mananjadhav $250

**Comment by JmillsExpensify** [comment] 2023-11-03 21:30
$250 payment approved for @mananjadhav based on comment above.

**Comment by Samueljh1** [comment] 2023-11-04 03:29
> @Samueljh1 can you accept [this offer](https://www.upwork.com/en-gb/nx/wm/offer/27506510) so I can pay you out? 
> 
> 

Done, thanks

**Comment by garrettmknight** [comment] 2023-11-06 16:29
Everyone's paid - closing.

**Closed by garrettmknight** 2023-11-06 16:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
