### ISSUE TITLE
[HOLD for payment 2023-09-07] [$2000] Make it easier to delete waypionts

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25901] opened 2023-08-24 21:48 UTC
On the waypoint editor, add the following flow: Dot menu icon -> menu pop up -> delete confirmation

Please refer to this comment for screenshots of the final design that should be achieved.

The following video demonstrates the current situation. You don't have a way to delete a waypoint (you can save a waypoint while the text input is empty to delete that waypoint, but it's not clear for the user that they can do so).

https://github.com/Expensify/App/assets/98560306/9884c800-6bdd-4226-91e6-d613e97148fa
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd2d29975258985d</li>
        <li>Upwork Job ID: 1695146647097401344</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>Nikhil-Vats | Contributor | 26332832</li>
</ul></li>
    </ul>
</details>

**Comment by iwint** [comment] 2023-08-25 07:16
Hello @hayata-suenaga , This makes sense and I would like to contribute to it , Can you assign this task to me ?

**Comment by jeet-dhandha** [comment] 2023-08-25 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- There is no way to remove a unwanted stop from waypoints.

### What is the root cause of that problem?
- We don't have any UI element to remove a stop from waypoints.

### What changes do you think we should make in order to solve the problem?
- We can add a `(-)` minus circle icon instead of showing the `Expensicons.DotIndicator` icon.
- We will also apply icon theme as `theme.danger`. To notify user that this is a remove icon.
- Then we can make that icon pressable in `MenuItem.js` so that we can call `removeWaypoint` function.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by hayata-suenaga** [comment] 2023-08-25 17:41
updating comments...

**Comment by hayata-suenaga** [comment] 2023-08-25 18:43
This is what we want to have.

<img width="150" alt="Screenshot 2023-08-25 at 11 39 33 AM" src="https://github.com/Expensify/App/assets/98560306/40657758-0ad6-4fce-97e9-92eac69c71b4">

Clicking the dot icon should display this kind of menu (with just "Delete" option)-> confirmation flow

"Delete receipt" should be "Delete waypoint"

<img width="300" alt="Screenshot 2023-08-25 at 11 41 56 AM" src="https://github.com/Expensify/App/assets/98560306/54152638-7d0f-4d3d-ac93-95b6cdd3a072">

**Comment by hayata-suenaga** [comment] 2023-08-25 18:50
doubled the payout

**Comment by ishpaul777** [comment] 2023-08-25 18:51
can i work on this ?

**Comment by hayata-suenaga** [comment] 2023-08-25 18:54
### A proposal with the most details on how to implement this new flow will be selected

**Comment by b4s36t4** [comment] 2023-08-25 19:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make it easier to delete waypionts
### What is the root cause of that problem?
No RC, feature.

### What changes do you think we should make in order to solve the problem?
1. Introducing the three dot menu here https://github.com/Expensify/App/blob/f48a2085d2e22bc011c4028fce56413d088b7896/src/pages/iou/WaypointEditor.js#L116 in this component.

2. Register `Delete Waypoint` option using `threedotmenuitems`, on click would be starting the `Confirmation` flow.

2. Using `ConfirmModal` in side `WayPointEditor.js`

3. on click of  confirm calling `onConfirm` function will be deleting waypoint data using `TransactionUtils`.

4. Once deletion Navigating user to back.
    - Dismiss the modal(close)
    - Navigation.goBack would take the user to back



### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-08-25 19:16
@allroundexperts @hayata-suenaga Updated my proposal a bit.

Also a small demo of my implementation(might not cover all things, though).


https://github.com/Expensify/App/assets/59088937/dd343091-f1cd-4bff-9be9-540c6c927ec9

**Comment by b4s36t4** [comment] 2023-08-25 19:32
@Nikhil-Vats I don't feel right about your opinions. You can have your proposal very well formatted with all the details but please don't mention what is not in the others proposals. CP will decide the proposal depends on many things.

Also

> Almost, all the code needed is added exactly in my proposal so I can create a PR within 12 hours.

I feel odd about this statement everyone here can do it with 2-3hrs, I have full working PR just right away with me :).

Hope I'm not making others uncomfortable here or no offense. Just trying for the equal opportunity here.

Thanks Hope you guys understand my point. :)

**Comment by hayata-suenaga** [comment] 2023-08-25 20:20
> on click of confirm calling onConfirm function will be deleting waypoint data using TransactionUtils.

This is from @b4s36t4's proposal. I couldn't find any method in `TransactionUtils` what we can use to delete waypoints. I think this is a very important point.

I'll go with @Nikhil-Vats 's proposal. Great work everyone for coming with proposals this first 🎉

**Comment by jeet-dhandha** [comment] 2023-08-25 20:20
@allroundexperts I have a doubt before assigning this to someone.

**Comment by hayata-suenaga** [comment] 2023-08-25 20:21
I forgot to assign myself before opening this issue external sorry for the notification noise Nikki 🙇

**Comment by b4s36t4** [comment] 2023-08-25 20:22
@hayata-suenaga I think having every point here doesn't make sense. Every proposal got one thing missed even his proposal also has so many flaws you can see his edits.

**Comment by b4s36t4** [comment] 2023-08-25 20:23
I feel the point to make what would be ponits we're going to do would make sense, not the function which we're going to use is kind of seems odd for me.

**Comment by jeet-dhandha** [comment] 2023-08-25 20:24
As per @hayata-suenaga the requirement was updated late and thus not giving me the time to give a proper proposal. Also everyone would have given almost the same proposal after requirements were given. As initially i thought this was an open issue where you can give your own UI ideas.

**Comment by b4s36t4** [comment] 2023-08-25 20:25
> We should also have this prop to make the popover look seamless in desktop too.
> threeDotsAnchorPosition={styles.threeDotsPopoverOffset(windowWidth)}
> We should add withWindowDimensions HOC for the above thing to work.

No body mentioned this point which could mess up the flow, although contributor will see this only while recording video.

**Comment by jeet-dhandha** [comment] 2023-08-25 20:25
What i want is to at least a chance to provide a proposal, before assigning this to other. Can you give me that ? @hayata-suenaga @allroundexperts

**Comment by jeet-dhandha** [comment] 2023-08-25 20:50
## Proposal
[Updated](https://github.com/Expensify/App/issues/25901#issuecomment-1693677158)

**Comment by jeet-dhandha** [comment] 2023-08-25 20:55
I'm going AFK for now since it's around 2:30 AM, and I really need some sleep. I'll be back in about 8-10 hours, so feel free to let me know if you need anything in the meantime. I'll make sure to catch up on any updates when I wake up. Thanks for your understanding!

**Comment by carlosalmonte04** [comment] 2023-08-25 20:56
Collaborate and split the money 🙂.

**Comment by jeet-dhandha** [comment] 2023-08-28 20:14
> ## Proposal
> [Updated](https://github.com/Expensify/App/issues/25901#issuecomment-1693677158)
> 
> @hayata-suenaga

@hayata-suenaga Friendly reminder on checking above message.

**Comment by hayata-suenaga** [comment] 2023-08-28 20:18
@jeet-dhandha The PR for this issue has been merged. If you suspect regression or bug, please report them. But otherwise, the issue has been solved 🙇

**Comment by jeet-dhandha** [comment] 2023-08-28 20:20
@hayata-suenaga doesn't this feel like you wanted @Nikhil-Vats to explicitly solve the issue, instead of looking at my solution as i was the one who initially suggested a solution and also updated solution for better User Experience.

**Comment by jeet-dhandha** [comment] 2023-08-28 20:22
As i have already asked for a re-review of proposal still no one answered. I didn't knew things were done this way here.

CC: @allroundexperts @shawnborton @laurenreidexpensify

**Comment by hayata-suenaga** [comment] 2023-08-28 20:27
@jeet-dhandha please don't tag every single person here 🙇

**Comment by jeet-dhandha** [comment] 2023-08-28 20:29
Just tell me what are you supposed to do as a reviewer ?

**Comment by b4s36t4** [comment] 2023-08-28 20:32
Hey, Jeet. I know how you're feeling but I was there too. But understand this a kind of feature request and the assignment depends on multiple levels. I hope you understand try other bugs as well bro :) two 1000$ bugs sum up to 2000$ as well ;).

**Comment by jeet-dhandha** [comment] 2023-08-28 20:35
@b4s36t4 Let me give you an example:
You and a person are at a restaurant where the person knows the owner so even if you ordered first then also the owner will prepare the food for the person instead of you. 

(And thats the summary here.)

**Comment by jeet-dhandha** [comment] 2023-08-28 20:39
@allroundexperts I know you want to say something so please say it instead of just reacting with emoji.

**Comment by b4s36t4** [comment] 2023-08-28 20:40
@jeet-dhandha Have a look at the comments.. I almost got assigned Just one spelling mistake instead of `Transaction` I put up `TransactionUtil` which got me rejected even though everything is correct. It's an experience to go forward and learn from it.. Just be fast and accurate.

**Comment by jeet-dhandha** [comment] 2023-08-28 20:42
You weren't rejected because of that. Here other reviewers don't reject proposal bcoz of silly mistakes like that. They look at the thorough explanation instead of code as the want a solution/way we are gonna solve the issue and not the code.

**Comment by jeet-dhandha** [comment] 2023-08-28 20:43
I haven't seen any reviewer giving rejection for silly mistake of spelling.

**Comment by b4s36t4** [comment] 2023-08-28 20:46
@allroundexperts I think it's not u.. I think it's hayata maybe 😅

**Comment by b4s36t4** [comment] 2023-08-28 20:47
Yep, I know 👍🏽 .

**Comment by jeet-dhandha** [comment] 2023-08-28 20:53
> As per @hayata-suenaga the requirement was updated late and thus not giving me the time to give a proper proposal. Also everyone would have given almost the same proposal after requirements were given. As initially i thought this was an open issue where you can give your own UI ideas.
> 
> What i want is to at least a chance to provide a proposal, before assigning this to other. Can you give me that ? @hayata-suenaga @allroundexperts

@allroundexperts So is it okay to not listen to a contributors request, like i had asked above ?

**Comment by puneetlath** [comment] 2023-08-28 20:56
I don't think this is a productive conversation, so I'm going to lock it for now. Let's all take some time and we can come back to it tomorrow with cooler heads. 

@jeet-dhandha as I mentioned in Slack, feel free to email contributors@expensify.com if you'd like to make a complaint.

**Comment by hayata-suenaga** [comment] 2023-09-01 17:18
> @hayata-suenaga I apologise for my previous behaviour.

No problem

> Also i would love to know one thing if you are open to it then only. Like what was wrong in my proposal if you can tell me that.

We'd really love to give feedback to each proposal as we know how much effort contributors are putting to draft those. However, we simply don't have time to do so.

The most important part of internal engineer's job is to push features in a very fast manner. And we appreciate contributors' help with us in doing so 🙇

**Comment by jeet-dhandha** [comment] 2023-09-01 17:26
> > @hayata-suenaga I apologise for my previous behaviour.
> 
> No problem
> 
> > Also i would love to know one thing if you are open to it then only. Like what was wrong in my proposal if you can tell me that.
> 
> We'd really love to give feedback to each proposal as we know how much effort contributors are putting to draft those. However, we simply don't have time to do so.
> 
> The most important part of internal engineer's job is to push features in a very fast manner. And we appreciate contributors' help with us in doing so 🙇

I understand that and that’s why whenever you have time to review and comment on my proposal please do that, i will appreciate that.

**Comment by laurenreidexpensify** [comment] 2023-09-20 14:59
Sorry folks, I completely dropped the ball on this one. Reviewing for payment summary now.

**Comment by laurenreidexpensify** [comment] 2023-09-20 15:03
Payment summary:

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @Nikhil-Vats - $2000, payment issued in Upwork 
-  Contributor+ that helped on the issue and/or PR - @allroundexperts - $2000, please request in newdot

Thanks everyone!

**Comment by laurenreidexpensify** [comment] 2023-09-20 16:44
@Nikhil-Vats can you link the timestamp confirmation message? Thanks!

**Comment by laurenreidexpensify** [comment] 2023-09-20 16:57
Thanks for confirming - sorry, there were a lot of off topic comments to review here!

External issue reporter - N/A
Contributor that fixed the issue - @Nikhil-Vats - $2000 + $1000 bonus, payment issued in Upwork
Contributor+ that helped on the issue and/or PR - @allroundexperts - $2000 + $1000 bonus, please request in newdot

**Closed** 2023-09-20 16:58 UTC
Labels: External, Weekly, Design, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-10-05 12:45
$3,000 payment for @allroundexperts approved based on BZ summary.
