### ISSUE TITLE
Dev: Web - Workspace- Personal information (step 3 of 5) Not going to the next step when entered number for First name , Last name and city

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20944] opened 2023-06-16 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to settings > workspace >Bank account > connect manually
3. Fill the form until step 3
4. Enter number for First name , Last name and city 

## Expected Result:
User proceed to the next step

## Actual Result:
User stays in Step 3

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c7c21cc-1f35-4aea-9ad0-bde1b8a8eecd

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686391710577659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018267fd61dd0e018e</li>
        <li>Upwork Job ID: 1670788729626402816</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-17 08:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Workspace- Personal information (step 3 of 5) Not going to the next step when entering number for First name, Last name, and city
### What is the root cause of that problem?
The backend is sending an error when only the number is entered in `firstName` or `lastName`
<img width="1031" alt="Screenshot 2023-06-17 at 1 42 57 PM" src="https://github.com/Expensify/App/assets/59907218/a6c0c7c4-641b-4517-a449-604f7ec2dcf8">

### What changes do you think we should make in order to solve the problem?
We should make sure that it is expected behavior not to accept only numbers in `firstName` and `lastName`. If yes we should add validation for these fields to check if they are only numbers or not. We can use something like this: 
```javascript
/^\d+$/.test(str)
``` 
We can also add checks for special characters if needed. 
### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-06-19 06:54
Hey @grgia - I can't test in dev, can you let me know if this is reproducible? ty!

**Comment by grgia** [comment] 2023-06-19 13:29
yes, this is reproducible

**Comment by narefyev91** [comment] 2023-06-19 14:27
@grgia @bfitzexpensify Hey guys! I would like to clarify - if we send this information for API - and API return an error - should we show that error and highlight fields which cause it?

**Comment by bfitzexpensify** [comment] 2023-06-20 07:29
Hey @narefyev91 - yes, we should show the error and indicate which fields are incorrect

**Comment by narefyev91** [comment] 2023-06-20 08:44
> Hey @narefyev91 - yes, we should show the error and indicate which fields are incorrect

Hey @bfitzexpensify! Thanks for the reply - one more thing to clarify - do we need local check instead of sending to API not valid fields? I think that this makes more sense

**Comment by narefyev91** [comment] 2023-06-20 16:42
Changes should be done on BE side - based on the discussion in slack https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227da2e3285a1a0332-AMD%22)+AND+timestamp:[2023-06-20T08:11:58.612Z+TO+2023-06-20T10:11:58.612Z]&index=logs_expensify-022893
API should return something similar as we have for empty fields:
`{"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"first_name":["can't be blank"],"last_name":["can't be blank"]}}} `

**Comment by bfitzexpensify** [comment] 2023-06-21 05:42
OK @grgia can you handle the BE changes or should I run the eng auto-assigner again?

**Comment by grgia** [comment] 2023-06-21 09:17
@narefyev91 can you link the discussion in slack?

**Comment by narefyev91** [comment] 2023-06-21 09:20
@grgia https://expensify.slack.com/archives/C02NK2DQWUX/p1687245299888519

**Comment by grgia** [comment] 2023-06-21 10:29
@narefyev91 thank you! Made internal, I should be able to look at this EOW or by early next week

**Comment by grgia** [comment] 2023-06-26 14:24
Haven't gotten to this yet

**Comment by grgia** [comment] 2023-06-29 11:39
Still haven't

**Comment by grgia** [comment] 2023-07-14 13:55
I've hit my hours for this week, so I'm going to try to prioritize getting a PR up for this one on Monday.

**Comment by grgia** [comment] 2023-07-18 14:18
Working on this

**Comment by grgia** [comment] 2023-07-27 11:33
I had to put this on the back burner this week

**Comment by grgia** [comment] 2023-08-02 07:41
Going to try and work on this before EOW, if I can't, I'll post a summary of the next steps and look for a volunteer since I'm OOO next week.

**Comment by grgia** [comment] 2023-08-03 14:59
Looking for volunteers before going OOO next week - https://expensify.slack.com/archives/C03TQ48KC/p1691074750730509

**Comment by grgia** [comment] 2023-08-16 15:20
Back from OOO, will likely try to find a volunteer still for this one

**Comment by grgia** [comment] 2023-08-28 09:34
not prioritizing currently

**Comment by grgia** [comment] 2023-09-14 10:23
^

**Comment by grgia** [comment] 2023-11-06 17:01
^

**Comment by grgia** [comment] 2023-12-13 16:59
^

**Comment by grgia** [comment] 2024-01-17 00:03
not a priority currently

**Comment by bfitzexpensify** [comment] 2024-03-15 12:21
@grgia I think we can just close this - the action taken to produce it (entering numbers as first and last name) doesn't seem like something someone would ever do. Do you agree?

**Comment by bfitzexpensify** [comment] 2024-03-15 12:24
Fortune favours the bold, I'm gonna close this

**Closed by bfitzexpensify** 2024-03-15 12:24 UTC
Labels: Engineering, Monthly, Internal, Bug
