### ISSUE TITLE
[$500] Web - Email - Error email received and message isn't sent to Chat,if user replies the email with "quote"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32490] opened 2023-12-05 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify as account A
2. As account A , send a message to an Account B that must be a main email address without the +. This will trigger an email notification to this account
3. After sometime passed, check the main account email inbox and open the mail with this name "Chat between <A> and <B>"
4. Reply the email to answer the other user with "Quote" used
5. Verify the message you sent via email is displayed for both accounts

## Expected Result:
Message is sent to Chat if user replies the email with "quote"

## Actual Result:
'Unable to add comment or attachment' email received and message is not sent to Chat, if user replies the email with "quote"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6301969_1701790335195!email_quote](https://github.com/Expensify/App/assets/78819774/2f834a39-fee7-4e1f-bbde-263ca259a46d)

https://github.com/Expensify/App/assets/78819774/2861f4be-ec9b-4daf-bf08-09044ba9cb78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c2e6a87cf76ec4a</li>
        <li>Upwork Job ID: 1732062336227663872</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by ArekChr** [comment] 2023-12-12 08:05
No overdue, waiting for proposals.

**Comment by ArekChr** [comment] 2023-12-18 09:11
Hey @peterdbarkerUK, I've left the c+team and joined Waves. Could you assign a new c+ to handle this issue?

**Comment by situchan** [comment] 2023-12-18 09:27
@peterdbarkerUK I can take over, though no proposals yet

**Comment by peterdbarkerUK** [comment] 2023-12-27 12:53
Hmm, this feels like intended behaviour to prevent email threads from being included in chat. Given the propensity of email users to reply to things like this:

```
> Your question
My answer
```

This is something worth resolving. I see it more as a feature though. Ideally there would be an exception for primary reply, though I don't know how we'd do it. Raised in [slack](https://expensify.slack.com/archives/C066HJM2CAZ/p1703681599894559).

**Comment by peterdbarkerUK** [comment] 2024-01-10 11:14
We discussed in slack, and this is indeed intended behaviour.

**Closed by peterdbarkerUK** 2024-01-10 11:14 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
