### ISSUE TITLE
[Paid] [$500]  Expense - Red dot for WS chat in LHN remains when admin pays a Scan request with no merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33998] opened 2024-01-05 01:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** Y 
**Reproducible in Production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat as workspace member
2. Create a Scan request
3. Go to details page of the request
4. Click Amount > enter amount > Save
5. As admin, pay the request

## Expected Result:
The red dot in LHN for the workspace chat will be dismissed from member view

## Actual Result:
The red dot in LHN for the workspace chat is not dismissed from member view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/698f18b2-cf8d-4d00-832e-647f781466e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdd2abc895c5a2d0</li>
        <li>Upwork Job ID: 1743086417081118720</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28089727</li>
<li>dukenv0307 | Contributor | 28089728</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by bernhardoj** [comment] 2024-01-05 04:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After we paid a scan request with an error, the red dot didn't go away from the LHN item, but it went away from the report preview.

### What is the root cause of that problem?
If we compare it with the report preview, we show the red dot if the request has an error and is not settled yet.
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/components/ReportActionItem/ReportPreview.js#L291-L296

But for the LHN, we only check if it has errors (the 3rd if, line 366).
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/libs/SidebarUtils.ts#L294
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/libs/OptionsListUtils.js#L356-L368

If you notice, for other cases, we already added the settled check.

### What changes do you think we should make in order to solve the problem?

Add the `!ReportUtils.isSettled(report.reportID)` check in the if.
```
else if (ReportUtils.hasSmartscanError(_.values(reportActions)) && !ReportUtils.isSettled(report.reportID)) {
```

**Comment by c3024** [comment] 2024-01-05 10:49
@dukenv0307 's [proposal here](https://github.com/Expensify/App/issues/33998#issuecomment-1878088906) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by mountiny** [comment] 2024-01-08 23:50
Go ahead please

**Comment by strepanier03** [comment] 2024-01-26 22:33
Dang, another one where the automation didn't work to move this over to Daily. I'll work on this now.

**Comment by strepanier03** [comment] 2024-01-26 23:05
@c3024 - Can you complete the checklist, I jumped the gun and paid this out because I had it confused with another GH I was paying. 

Thanks!

**Comment by c3024** [comment] 2024-01-27 13:19
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR:https://github.com/Expensify/App/commit/da0fe2b089bb31c487dfe2ff3859fd778d7a3bc7
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:https://github.com/Expensify/App/commit/da0fe2b089bb31c487dfe2ff3859fd778d7a3bc7#r137904357
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because catching this bug does not appear to be feasible earlier. 
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test. (https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
## Regression Test 
1. Create a workspace and invite some users to workspace
2. As an employee of the workspace, go to the policy expense chat
3. Create a scan money request
4. Go to request detail page
5. Click Amount > enter amount > Save. Do not edit any other fields
6. As admin, pay this request
7.  Verify that the red dot disappears from the policy expense chat in LHN for the employee

👍 or 👎 

> * [x]  [@strepanier03] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by strepanier03** [comment] 2024-01-30 03:42
Thanks! Doing the reg test GH now and then I'll close.

**Comment by strepanier03** [comment] 2024-01-30 03:52
GH is made, ready to close. Thanks everyone!

**Closed by strepanier03** 2024-01-30 03:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
