### ISSUE TITLE
[HOLD for payment 2022-12-15] [$500]  iOS -  When hard-press username to open tooltip and navigate to same user detail tooltip remains open - reported by dhairyasenjaliya

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9973] opened 2022-07-19 04:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Press and hold to any username until copy clipboard appears
3. Press on to that same username while clipboard open 
4. User detail page opens with clipboard remains open in same position

## Expected Result:
clipboard should closed since we navigate to user detail

## Actual Result:
clipboard appear in same position

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.85-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/179662083-28d31c90-7686-4181-9eea-96aa9969e248.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @dhairyasenjaliya
**Slack conversation:** [
](https://expensify.slack.com/archives/C01GTK53T8Q/p1656682996487299)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-07-29 16:30
I will look into it next week

**Comment by sketchydroide** [comment] 2022-08-08 13:47
will do it this week

**Comment by mateocole** [comment] 2022-08-14 06:53
feel free to assign back to me once this is looked into

**Comment by sketchydroide** [comment] 2022-08-24 13:11
I've got deployer duties this week, and with clear daily releases I don't have time for this GH, hopefully next week 🤞🏼

**Comment by sketchydroide** [comment] 2022-09-06 11:05
Will try to look at this in this week

**Comment by sketchydroide** [comment] 2022-09-15 14:34
on my top list of things to look at now

**Comment by sketchydroide** [comment] 2022-09-16 14:47
So what I think is happening is that this [entire area is pressable](https://github.com/Expensify/App/blob/b7ad9f84169a438c48f24da716e77d1c3ce5a587/src/pages/home/HeaderView.js#L113-L162), including the tooltip and will take you to the details page.
But because you are also touching the tooltip you will not dismiss it. (it's likely although I did not test it, that you are copying the email at the same time you are opening the detials page)

**Comment by sketchydroide** [comment] 2022-09-16 15:07
also demoting this to monthly, this is a bit of an edge case and not all that important, just a bit weird looking think

**Comment by Julesssss** [comment] 2022-09-20 08:52
It looks like a ReactNative|iOS issue to me, I would expect to see other reports from people facing this issue.

**Comment by sketchydroide** [comment] 2022-10-19 10:05
looking today to see if there is any other peolpe complaining, or if we could update the library.
Another Solution is making this an external and see if someone knows more about this.

**Comment by puneetlath** [comment] 2022-11-02 17:32
@sketchydroide I removed and re-added the bug label to get a BZ team member added who can help move this forward.

**Comment by arielgreen** [comment] 2022-11-07 19:52
https://www.upwork.com/jobs/~0176085f228534d198

**Comment by sketchydroide** [comment] 2022-11-09 14:43
not sure why it would add you @luacmartins since I can already handle the External?

**Comment by sketchydroide** [comment] 2022-11-14 10:53
@arielgreen maybe we can increase the price?

**Comment by mananjadhav** [comment] 2022-11-14 11:25
Also @arielgreen @sketchydroide Can we update the title and GH body to replace ~clipboard~ with **tooltip** ? It's a bit confusing to understand the issue.

**Comment by arielgreen** [comment] 2022-11-16 19:36
@mananjadhav done.

Increased price.

**Comment by JmillsExpensify** [comment] 2022-11-17 21:33
@sketchydroide To help clear out the extensive backlog of /App bugs, we're putting the spotlight on all bugs older than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:

 - Decide whether any proposals currently meet our guidelines and can be approved as-is
 - For any that can't, please take this issue internal and treat it as one of your highest priorities
 - If you have any questions, don't hesitate to start a discussion in #bug-zero

Thanks everyone!

**Comment by JmillsExpensify** [comment] 2022-11-17 21:33
@sketchydroide Adding that for your specific case you should treat IOU refactor higher. But then this is the next one after that.

**Comment by dylanexpensify** [comment] 2022-11-22 11:55
Coming from [this](https://expensify.slack.com/archives/C01SKUP7QR0/p1669075981370149?thread_ts=1669034215.991529&cid=C01SKUP7QR0) comment, and no current proposal out, let's move this one internally

**Comment by arielgreen** [comment] 2022-11-22 22:24
Thanks @dylanexpensify 

@sketchydroide do you have an ETA for when you'll be able to take a look at this?

**Comment by sketchydroide** [comment] 2022-11-25 13:32
No not really, the API refactors take most of my time atm.
Bu it all honesty I think this is more of a React issue or a library issue than something we can easily fix.
Like I mentioned before it seems that the tooltip is pressable, and it shouldn't be

**Comment by eVoloshchak** [comment] 2022-11-25 18:54
`Copy` tooltip is not the [Tooltip.js](https://github.com/Expensify/App/tree/main/src/components/Tooltip) component, it's actually iOS's native **Cut/Copy/Paste** menu, but since it's just text, all you can do is **Copy**.
It looks worse on Android: you see the menu only after navigating to `User Details` and you can't dismiss the menu by pressing outside of it, you have to select an option.


https://user-images.githubusercontent.com/9059945/204039742-22a7d8a8-fab8-4358-8ef8-ece7a5b758d2.mp4

This is due to username having [selectable](https://reactnative.dev/docs/text#selectable) prop set to `true`
https://github.com/Expensify/App/blob/77e5843c6a928b135b993166c073841b21610781/src/pages/home/report/ReportActionItemFragment.js#L147
We can't control or show/dismiss these native menus as far as I know. And on web nothing happens if you long press, it just registers it as normal single tap (I think there is no `selectable` prop for text on web)

A simple solution would be setting `selectable` to `false`, then it would just open the standard [popover](https://github.com/Expensify/App/blob/cc88c777dd7229091df73b3a3755a1bb9654daa5/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js)


https://user-images.githubusercontent.com/9059945/204041903-31bbebdf-a37b-4a72-855d-873cd63343be.mov

**Comment by JmillsExpensify** [comment] 2022-11-26 16:16
Ah that's a clever solution. @sketchydroide @mananjadhav can you two comment if you agree? If so, then we can have @eVoloshchak lead next steps, as this bug is inexcusably old and we need to align on next steps, implement them, and move on. Let's agree on the path forward and put it in motion.

**Comment by mananjadhav** [comment] 2022-11-27 06:35
I agree with @eVoloshchak's findings and yeah disabling the select should work fine. 

I would recommend @eVoloshchak to check if it causes any issues with the mWeb? I know we want to show our context menu everywhere.

When we have selectable false, and do a long press, it selects a text somewhere in the parent/siblings with the Select highlight. But I think having selectable disabled for our item fragments should work fine. 

@sketchydroide Your thoughts?

🎀 👀 🎀 
C+ reviewed

**Comment by eVoloshchak** [comment] 2022-11-27 21:13
> I would recommend @eVoloshchak to check if it causes any issues with the mWeb? I know we want to show our context menu everywhere.

Tested mWeb Safari/Crome, both are unaffected by this change, they currently work as expected

**Comment by sketchydroide** [comment] 2022-11-29 12:33
that is a smart solution, I like it, and it makes behaviour more uniform, let's do this

**Comment by mananjadhav** [comment] 2022-11-29 18:47
@sketchydroide Assignment didn't add a `Assigned job` comment on GH.

@eVoloshchak Can you start with the PR?

**Comment by eVoloshchak** [comment] 2022-11-29 19:10
> @eVoloshchak Can you start with the PR?

Sure thing, will open the PR tomorrow

**Comment by mvtglobally** [comment] 2022-11-30 05:07
Issue not reproducible during KI retests. (First week)

**Comment by sketchydroide** [comment] 2022-11-30 15:40
@eVoloshchak are you opening the PR today? :)

**Comment by eVoloshchak** [comment] 2022-11-30 16:48
> @eVoloshchak are you opening the PR today? :)

Yup, working on it, will be ready in an hour

**Comment by eVoloshchak** [comment] 2022-11-30 18:27
PR is open

**Comment by mananjadhav** [comment] 2022-11-30 19:11
@aimane-chnaif Thanks for the comment, but do we have a specific need for `selectable` to be true? We're anyway relying on the context menu for our copy needs. Hence I think we should be good with current accepted solution.

**Comment by mananjadhav** [comment] 2022-11-30 19:19
I did. I'll get some feedback from @sketchydroide @arielgreen on this one. I don't mind having `canUseTouchScreen` as well.


@sketchydroide do we want to disable selectable only for apps? and not web?

**Comment by mananjadhav** [comment] 2022-12-01 07:08
@JmillsExpensify if you would also want to chime in?

**Comment by mananjadhav** [comment] 2022-12-01 18:37
@sketchydroide did you get a chance to look at the previous comments?

**Comment by sketchydroide** [comment] 2022-12-01 18:50
I don't see a specific reason for the need to be selectable. 
We can copy specific messages and we can copy the info from the user  info page.

@JmillsExpensify let me know if you disagree because there is some level of UX involved and I don't know if this affects WAQ

But I think going with @eVoloshchak solution works

**Comment by sketchydroide** [comment] 2022-12-01 18:51
Also we want to have the same behaviour in all platforms so I think we should keep the same for both web and mobile

**Comment by JmillsExpensify** [comment] 2022-12-01 20:09
Yeah I think that last point is the most critical, and why we don't need this to be selectable.

**Comment by sketchydroide** [comment] 2022-12-02 10:29
cool I think we are sticking with @eVoloshchak solution, thanks for stating your concerns @aimane-chnaif :)

**Comment by mananjadhav** [comment] 2022-12-02 10:31
Was just about to comment on the thread that, the PR is already C+ reviewed.

**Comment by sketchydroide** [comment] 2022-12-02 10:33
yeah was just going over it right now :D

**Comment by sketchydroide** [comment] 2022-12-02 11:05
the solution has been merged

**Comment by mananjadhav** [comment] 2022-12-13 03:54
I couldn't track any PR that got the bug. This is anyway a native tooltip showing up in the UI, so I don't think we have any regression PR here. @sketchydroide what do you think?

---

@arielgreen @sketchydroide @JmillsExpensify This issue is very old and had been old for quite a few weeks, and by the time it opened, it should've been doubled. The reason I am asking is, how do we set the amount for this one?  Should it be 500$ as per title or 1K$ as per the new bug bounty? Also this might be eligible for 50% bonus.

**Comment by sketchydroide** [comment] 2022-12-13 12:19
Yeah I don't see how this could have been a regression, it was just the way the tooltip behaved, this would be an upstream problem from the beggining.
The fix was to not use the tooltip. And use another soltuion instead.
As for the prices I have no idea, I think @JmillsExpensify would be the best person to decide here.

**Comment by arielgreen** [comment] 2022-12-15 23:41
Thanks for raising this @mananjadhav. I've reviewed the issue, and the timeline. 

This was originally held up internally. The timeline once it was posted is as follows:
11/7 - job [posted to Upwork](https://github.com/Expensify/App/issues/9973#issuecomment-1306109387)
11/16 - price [increased](https://github.com/Expensify/App/issues/9973#issuecomment-1317568236)
11/27 - [proposal approved](https://github.com/Expensify/App/issues/9973#issuecomment-1328181731)
11/29 - @mananjadhav [noticed](https://github.com/Expensify/App/issues/9973#issuecomment-1331132453) the comment didn't trigger and @eVoloshchak accepted, so we start the bonus clock.
11/30 - [PR raised](https://github.com/Expensify/App/pull/13204)
12/2 - PR approved by @sketchydroide 

This is eligible for the 50% bonus since it was merged within 3 bus days. I also think it's fair in this case to bump up the price to $1k since it should have been done prior to proposal being accepted.

Reporting bonus: $250 to @dhairyasenjaliya 
Issue bounty: $1000+50% = $1500 to @eVoloshchak 
C+ = $1500 to @mananjadhav 

Issuing payment now!

**Comment by arielgreen** [comment] 2022-12-15 23:45
Offers sent @dhairyasenjaliya @eVoloshchak @mananjadhav, please accept

**Comment by arielgreen** [comment] 2022-12-16 19:20
Excellent, all three payments have been issued.

**Closed by arielgreen** 2022-12-16 19:20 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug
