### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-21] [HOLD for payment 2023-06-19] Web - New Group - Wrong user details page opens on clicking at display names

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20583] opened 2023-06-12 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on fab icon
2. Create a new group
3. Refresh the page
4. Click on each display name and check if the user details are correct

## Expected Result:
Correct user details should open

## Actual Result:
The user details aren't of the clicked user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/318b4266-3ecb-4734-8c55-3b54874f6bf1

https://github.com/Expensify/App/assets/93399543/fbd0850f-0e27-44f3-bf69-8d229db119bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here

**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1686560410530529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a5aeee05bd7da3a</li>
        <li>Upwork Job ID: 1671541422809731072</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-06-12 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong user details page opens on clicking at display names

### What is the root cause of that problem?
The root cause of this problem is that, the accountIDs and the participant emails are not matched in correct order.
This is the screen shot of accountIDs and their emails in `ReportScreen`
![image](https://github.com/Expensify/App/assets/27822551/19f50355-6fd2-457b-97ed-e2b629ca3925)

And here are the details of those users - 
![Control-V(10)](https://github.com/Expensify/App/assets/27822551/cf6a9940-a0d1-4a2d-aa5c-37ecef41e01c)


If we pay close attention for first two users in the first picture IDs are interchanged, That's why opening the user details were taking on wrong page.
This is the issue video - 

https://github.com/Expensify/App/assets/27822551/4eae5e30-8a1f-4fdc-8839-5c30e011e955

Here we are using index to navigate - 
https://github.com/Expensify/App/blob/297e5aa46582fb2681dc9e5e64a075c5da8dcdd7/src/components/ReportWelcomeText.js#L94-L112


### What changes do you think we should make in order to solve the problem?
Instead of using index we can create the object, that will map the participant emails to their accountID
We can use `personalDetails` for that, this will ensure we are navigating with proper accountID each time.

### What alternative solutions did you explore? (Optional)
None

**Comment by PauloGasparSv** [comment] 2023-06-12 17:32
I think I may use @BhuvaneshPatil solution but implement it myself! 

I'm checking if `personalDetails` will always have the `accountID`, if that's not the case we can also search for the participant's actual index searching the email from `displayNamesWithTooltips` in `participants`. I like the proposed solution much better than doing this but it's an alternative : )

**Comment by PauloGasparSv** [comment] 2023-06-12 17:37
Note: Also test what happens if an account has a `displayName`

**Comment by PauloGasparSv** [comment] 2023-06-12 17:48
Using `personalDetails` works fine when accounts have a Display Name but not so much for SMS based accounts, I'm thinking of a way to make that work : ) (it has to do with the `login` param and how each object/list is generating theirs)

<img src="https://github.com/Expensify/App/assets/6564265/e91d0d3e-5cc2-4c69-8720-1966ddfb8192" width="400">
<img src="https://github.com/Expensify/App/assets/6564265/5e1d2080-28b7-47ea-b1cc-c692ac44ae76" width="400">

**Comment by PauloGasparSv** [comment] 2023-06-12 18:15
hey @johncschuster can you give me a hand in this blocker/regression? 

I used @BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/20583#issuecomment-1587358251) to create the fix P.R. so should there be compensation here?

**Comment by BhuvaneshPatil** [comment] 2023-06-12 18:17
thank you for mention @PauloGasparSv , appreciate it.

**Comment by PauloGasparSv** [comment] 2023-06-12 18:25
I think it was introduced in https:/github.com/Expensify/App/pull/20144 @aimane-chnaif

**Comment by BhuvaneshPatil** [comment] 2023-06-12 18:26
Yes, previously it was using 
```
ROUTES.getDetailsRoute(participants[index]))
```
for onPress handler

**Comment by AndrewGable** [comment] 2023-06-13 16:23
CP-ed to staging, removing deploy blocker label.

**Comment by PauloGasparSv** [comment] 2023-06-13 18:58
Bump @johncschuster on [this](https://github.com/Expensify/App/issues/20583#issuecomment-1587839095) to help with compensation here!

**Comment by johncschuster** [comment] 2023-06-21 15:32
@BhuvaneshPatil and @aimane-chnaif, can you apply to the Upwork job I just created above?

**Comment by BhuvaneshPatil** [comment] 2023-06-21 16:05
Applied

**Comment by johncschuster** [comment] 2023-06-22 13:53
Thanks! @aimane-chnaif, I've invited you on Upwork as well. Can you accept that invite when you get the chance?

**Comment by Puneet-here** [comment] 2023-06-22 19:22
@johncschuster, I have also applied to the job. I am reporter on this.

**Comment by johncschuster** [comment] 2023-06-23 16:04
Perfect! Thanks, @Puneet-here!

**Comment by johncschuster** [comment] 2023-06-23 16:07
I've sent offers to you both, @aimane-chnaif and @Puneet-here. Please ping me when you've accepted!

**Comment by PauloGasparSv** [comment] 2023-06-26 13:54
This is not overdue but we still need to fill the bugzero [checklist](https://github.com/Expensify/App/issues/20583#issuecomment-1591979812) so bump @aimane-chnaif : )

**Comment by johncschuster** [comment] 2023-06-26 17:20
Payment has been issued to everyone 🎉

**Comment by johncschuster** [comment] 2023-06-27 11:52
I think we can close this one out

**Closed by johncschuster** 2023-06-27 11:52 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
