### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Web -  2 requests appears for few seconds on click of pay elsewhere button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26767] opened 2023-09-05 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to chat with userB
2. Click on + icon and select request money option
3. Enter amount and click on request button
4. From userB, click on pay elsewhere button

## Expected Result:
It should not show 2 requests

## Actual Result:
Requests appears for few seconds on click of pay elsewhere button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c5d9c7aa-6eef-4da1-b991-a13e2a572182

https://github.com/Expensify/App/assets/93399543/afdc7ba2-0058-463c-a517-c4b6884996f3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693897414969169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef8c662a1041de0d</li>
        <li>Upwork Job ID: 1699362909149663232</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26670765</li>
<li>gadhiyamanan | Reporter | 26670766</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-09-05 14:27
@gadhiyamanan whats the 50units request in the LHN, that should not be there? How did it happen to show up?

I agree not a blocker

**Comment by s-alves10** [comment] 2023-09-05 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

2 requests appears for a few seconds on click pay-elsewhere button

### What is the root cause of that problem?

This is a regression of [this PR](https://github.com/Expensify/App/pull/26603)

When we pay the money request, [payMoneyRequest](https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/libs/actions/IOU.js#L1748) function is called

In [getPayMoneyRequestParams](https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/libs/actions/IOU.js#L1523) in this function, we get optimistic report preview action from [ReportUtils.updateReportPreview](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L2266)

As you can see below, this function increases the `childMoneyRequestCount` by one as if we create a new money request
https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/libs/ReportUtils.js#L2284

This is the root cause

### What changes do you think we should make in order to solve the problem?

We should not increase the `childMoneyRequestCount` of report preview action for pay request.

1. Add the parameter named `requestIncrease` to the `updateReportPreview` function
```
function updateReportPreview(iouReport, reportPreviewAction, requestIncrease = 1, comment = '', transaction = undefined) {
    ... ...
        childMoneyRequestCount: reportPreviewAction.childMoneyRequestCount + requestIncrease,
}
```

2. Add this parameter to all the function call
https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/libs/actions/IOU.js#L451
```
        reportPreviewAction = ReportUtils.updateReportPreview(iouReport, reportPreviewAction, 1, comment, optimisticTransaction);
```

https://github.com/Expensify/App/blob/b9c48328903b583ebfeb1f02d1e2110d25c42a2e/src/libs/actions/IOU.js#L1536
```
    const optimisticReportPreviewAction = ReportUtils.updateReportPreview(iouReport, ReportActionsUtils.getReportPreviewAction(chatReport.reportID, iouReport.reportID), 0);
```

This works as expected

<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by gadhiyamanan** [comment] 2023-09-05 14:32
@mountiny message appears even if only one  money requested
https://github.com/Expensify/App/assets/54790231/7f3206ca-7d97-4176-bc7c-8efdd632b03d

**Comment by eVoloshchak** [comment] 2023-09-11 07:33
Reviewing this today, apologies for the delay

**Comment by eVoloshchak** [comment] 2023-09-11 19:00
I agree with @s-alves10's [assessment](https://github.com/Expensify/App/issues/26767#issuecomment-1706737988) of the root cause
Instead of adding a `requestIncrease` param that is a number, I think we can add a boolean instead. There isn't a case where we need to increase the request count by 2 or more, so having a boolean would be more readable 
But that can be ironed out during the PR stage, the general direction of the proposal looks good to me

🎀👀🎀 C+ reviewed!

**Comment by mallenexpensify** [comment] 2023-09-14 08:19
No sure how I got unassigned, @deetergp can you review the above plz?

**Comment by deetergp** [comment] 2023-09-14 09:58
I agree with you about the boolean @eVoloshchak — can't think of a situation where we'd need to increment more than 1. Let's go with @s-alves10's solution.

**Comment by s-alves10** [comment] 2023-09-14 12:39
@eVoloshchak 

[PR](https://github.com/Expensify/App/pull/27435) is ready for review

**Comment by mallenexpensify** [comment] 2023-09-29 16:15
@gadhiyamanan and @s-alves10 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ef8c662a1041de0d

@eVoloshchak plz fill out the checklst steps, not sure why it didn't auto-post here

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

-  The PR that introduced the bug has been identified. Link to the PR:
-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
-  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
-   Determine if we should create a regression test for this bug.
-  If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
-  [@mallenexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
-

**Comment by gadhiyamanan** [comment] 2023-09-29 16:21
@mallenexpensify applied, thanks!

**Comment by s-alves10** [comment] 2023-09-29 16:23
@mallenexpensify 
Accepted the offer. Thanks

**Comment by eVoloshchak** [comment] 2023-09-30 08:15
> This is a regression of https://github.com/Expensify/App/pull/26603

@s-alves10, could you elaborate on this more, please? I'm not too sure this is the PR that caused this, I think it was https://github.com/Expensify/App/pull/23651, but would appreciate it if you expand on why you think it was https://github.com/Expensify/App/pull/26603

**Comment by s-alves10** [comment] 2023-10-02 12:30
@eVoloshchak 

Yes, you're right. I was wrong

**Comment by eVoloshchak** [comment] 2023-10-02 13:22
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23651
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23651/files#r1342685354ё
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, there isn't much we could do besides automated testing
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No
This isn't very impactful, but it's related to core functionality and fairly easy to test, so I think regression test is worth adding

**Comment by eVoloshchak** [comment] 2023-10-02 13:24
**Regression Test Proposal**

1. Open the App and log in with any account (user A)
2. Go to chat with user B
3. Send a money request to user B
4. From user B, click on `Pay elsewhere`
5. Verify that there is only one request, a second request doesn't appear for a brief period of time

**Do we agree 👍 or 👎**

**Comment by mallenexpensify** [comment] 2023-10-03 18:57
Issue reporter: @gadhiyamanan paid $50 via Upwork
Contributor: @s-alves10 paid $750 via Upwork, includes urgency bonus
Contributor+: @eVoloshchak is due $750 via NewDot 

Thanks @eVoloshchak for test steps - https://github.com/Expensify/Expensify/issues/322548

**Closed by mallenexpensify** 2023-10-03 18:57 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by eVoloshchak** [comment] 2023-10-04 15:06
Requested the payment via NewDot
I did that a couple of days ago, but can't see the payment request after signing out and signing back in, so re-requesting. 
Please verify there isn't a duplicate payment request

**Comment by JmillsExpensify** [comment] 2023-10-05 20:50
$750 payment approved for @eVoloshchak based on BZ summary.
