### ISSUE TITLE
[HOLD for payment 2023-09-06] [$2000] IOS -  Application Not Responding after adding built-in emoji from Keyboard and NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21540] opened 2023-06-25 19:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Tap the chat field to load the iOS built-in keyboard
3. Tap the emoji icon on the iOS built-in keyboard
4. **Quickly** tap on many emojis : Notice they fill in the chat field (don't send the chat)
6. Then tap the NewDot emoji icon on the chat field
7. Tap on any NewDot emoji : notice the app doesn't respond or add to the chat field
8. Try sending the message or touch any where on screen

## Expected Result:
App should add the emojis to the chat field and send the message 

## Actual Result:
Application Not Responding

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/51066321/9934d28d-7107-4997-9b4a-36f2f78b44c5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687205953132519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013295df289a5037fc</li>
        <li>Upwork Job ID: 1673779604035960832</li>
        <li>Last Price Increase: 2023-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>ShogunFire | Contributor | 26265168</li>
<li>tranvantoan-qn | Reporter | 26265171</li>
</ul></li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-06-25 19:06
2. Insert built-in emoji of keyboard
3. Insert NewDot’s Emoji

The word **NewDot’s Emoji** may cause confusion so I will explain it more:

These 2 steps mean we need to use both **emoji of the keyboard** and **emoji added in our app - Expensify**

**Comment by tranvantoan-qn** [comment] 2023-06-26 06:33
This is the console log I got when connecting with XCode - the issue happened at about `13:27`
[Xcode-log.txt](https://github.com/Expensify/App/files/11865121/Xcode-log.txt)

**Comment by Christinadobrzyn** [comment] 2023-06-26 20:33
I can't reproduce - asking for more information in Slack - https://expensify.slack.com/archives/C049HHMV9SM/p1687811366675009?thread_ts=1687205953.132519&cid=C049HHMV9SM

**Comment by tranvantoan-qn** [comment] 2023-06-27 02:07
@Christinadobrzyn 
**I tested on 2 devices:**
**iOS 14.2**: It happened just after 1 or 2 messages (the one on attached video)

**iOS 16.2**: It happened after 5 or 6 message

Can you give it more try? And maybe using a combination of texts and emojis in the message could help reproduce it easier?

**Comment by Christinadobrzyn** [comment] 2023-06-27 19:44
Okay, I can reproduce it - it seems like the issue is dependent on entering a lot of emojis from the iOS keyboard. I updated the OP and the video. adding an external label.

**Comment by Christinadobrzyn** [comment] 2023-06-28 13:55
Yes only iOS - I couldn't reproduce on Android

**Comment by Christinadobrzyn** [comment] 2023-07-07 21:43
waiting for proposals!

**Comment by ShogunFire** [comment] 2023-07-08 16:41
I have a slightly different way of freezing the app which doesn't involve the ios keyboard:
1. click on our emojis picker button
2. click on a lot of emojis quickly
3. do step 1 and 2 until it freezes

https://github.com/Expensify/App/assets/19537677/5796697b-a8b3-4f81-aee5-d50931289177

I don't know if it's related but I also have a warning when I click emojis:
![image](https://github.com/Expensify/App/assets/19537677/83505f39-5b39-4352-b5bb-e93db904a0fa)

**Comment by shubham1206agra** [comment] 2023-07-08 17:49
> I don't know if it's related but I also have a warning when I click emojis: ![image](https://user-images.githubusercontent.com/19537677/251987590-83505f39-5b39-4352-b5bb-e93db904a0fa.png)

I have already found the bug for the same. I will patch this whenever possible.

**Comment by shubham1206agra** [comment] 2023-07-09 09:27
> This warning is already reported as a bug on GH and is currently being solved. That might be the cause of this bug. I think that might solve this.

Nope
It just creates another warning.

` WARN  Warning: Overriding previous layout animation with new one before the first began:
<RCTLayoutAnimationGroup: 0x6000023b4120; creatingLayoutAnimation: <RCTLayoutAnimation: 0x600002ecf680; duration: 0.050000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; updatingLayoutAnimation: <RCTLayoutAnimation: 0x600002ecc680; duration: 0.050000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>; deletingLayoutAnimation: <RCTLayoutAnimation: 0x600002ecc880; duration: 0.050000; delay: 0.000000; property: opacity; springDamping: 0.000000; initialVelocity: 0.000000; animationType: 4;>> -> <RCTLayoutAnimationGroup: 0x600002041260; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x600002e39b00; duration: 0.250000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)>.
`

**Comment by ShogunFire** [comment] 2023-07-09 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we click quickly on emojis on ios, the app freeze

### What is the root cause of that problem?

It happens when we have two animations at the same time.
I haven't found out why it only happens when we click on emojis quickly but the animation that is making the app crashes is this one: https://github.com/allroundexperts/Expensify/blob/58f663a2ff05bd06be3dd9a438cad8ad86d3ac68/src/pages/home/report/ReportActionCompose.js#L294

Which happens when selection changes.
I think the other one is the KeyboardAvoidingView one KeyboardAvoidingView.

### What changes do you think we should make in order to solve the problem?

This animation was first added for suggestion emojis but as @s77rt had said [here](https://github.com/Expensify/App/pull/18842/files#r1221635741) this line is now useless and can be removed

### What alternative solutions did you explore? (Optional)
We could verify that an animation is not already running before configuring the next one

I tried to verify if quickly clicking emojis was running addEmojiToTextBox multiple time here https://github.com/allroundexperts/Expensify/blob/58f663a2ff05bd06be3dd9a438cad8ad86d3ac68/src/pages/home/report/ReportActionCompose.js#L1151 that would explain why it only happens when we click quickly  since the animation happens when selection changes but it doesn't look like it's the case.

**Comment by shubham1206agra** [comment] 2023-07-09 14:45
@ShogunFire Sorry, but I don't think so that this solution works. I have tried it and it gives this warning instead.

` WARN  Warning: Overriding previous layout animation with new one before the first began:
<RCTLayoutAnimationGroup: 0x600002fa43c0; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x6000024d0480; duration: 0.250000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)> -> (null).
`

**Comment by shubham1206agra** [comment] 2023-07-09 14:46
I am already working on the fix and will send a proposal once I verified the solution.

**Comment by ShogunFire** [comment] 2023-07-09 14:53
@shubham1206agra I don't know about the warning but it solves the issue for me, I also added another fix to my proposal

**Comment by tranvantoan-qn** [comment] 2023-07-10 09:01
Hi guys,
After multiple attempts to reproduce the issue by **selecting/changing emoji quickly**, it became evident that the un-intended user interface (UI) element  UITransitionView - was blocking user input, leading to the feeling that the application was not responding.

Look at the following analysis for more details:

 - **When the emoji picker modal is NOT showing**: There is **only 1 UITransitionView** element and the user can interact with the UI normally.
![1-View-Normal](https://github.com/Expensify/App/assets/10254571/cf7a5847-c734-4f64-82e0-c4c14840f33e)


 - **When the emoji picker modal is showing**: There is **2nd UITransitionView** element displayed on top of the first one which  allows the user to select emojis
![2 views - NORMAL](https://github.com/Expensify/App/assets/10254571/ae6c885e-56cb-4998-ab14-75c404311547)

 - **After selecting emoji**: The **2nd UITransitionView** should be cleared/destroyed to allow the application to accept other user input. However, this view somehow persists and blocks the entire user interface.
![2 views - ERROR](https://github.com/Expensify/App/assets/10254571/92e83089-a354-46ad-b725-367fedb2c8b6)


Although I haven't yet found the solution, I believe that clearing or destroying the second UITransitionView will resolve this issue.

If you find my analysis reasonable, you can use it as a basis for further investigation.

**Comment by Christinadobrzyn** [comment] 2023-07-10 21:03
@parasharrajat can you review these proposals when you have some time? Thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:36
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're receiving and reviewing proposals.

**Comment by ShogunFire** [comment] 2023-07-15 14:42
Hello @parasharrajat what do you think of my proposal ? It solves the bug and is a easy fix to do.

**Comment by alexpensify** [comment] 2023-07-16 17:29
There are a few proposals here under review, any news @parasharrajat? Thank you!

**Comment by ShogunFire** [comment] 2023-07-17 18:01
> @ShogunFire Also, it is not clear from your proposal why the mentioned changes fix this issue and how?

The bug happens when there are two animations happening at the same time so if we remove one, that fix the bug

>  It will be great to define the effect of your changes on the existing functionality as well.

There is no effect on the existing functionality, I think this animation was supposed to show the suggestions by changing opacity but there is another animation for the suggestions that does like this:


https://github.com/Expensify/App/assets/19537677/103f6a8a-f913-44f7-a4af-135d19081b4c

I will try to improve the root cause

**Comment by ShogunFire** [comment] 2023-07-17 18:41
I found out that we already had a similar issue, they also thought of removing the LayoutAnimation but decided to go another way. Here is the link of the proposal that was chosen. Is it enough for the root cause ? It was enough at the time:
https://github.com/Expensify/App/issues/16591#issuecomment-1516643711

**Comment by s77rt** [comment] 2023-07-18 18:52
We are removing that `LayoutAnimation` here https://github.com/Expensify/App/pull/20888.

**Comment by ShogunFire** [comment] 2023-07-18 19:20
Awesome

**Comment by ShogunFire** [comment] 2023-07-19 12:16
Removing the animation is enough to fix this issue. 

For the weird transition with the keyboard, I think this is discussed in this issue: https://github.com/Expensify/App/issues/22052

**Comment by alexpensify** [comment] 2023-07-20 21:13
Thanks for flagging @parasharrajat. Stepping in to help @Christinadobrzyn and I've moved this to Weekly and put it on HOLD.

**Comment by alexpensify** [comment] 2023-08-01 21:29
@Christinadobrzyn - I think you are back online, can you want to grab this one back from me? Thank you!

**Comment by Christinadobrzyn** [comment] 2023-08-11 20:56
On hold for https://github.com/Expensify/App/pull/20888

**Comment by Christinadobrzyn** [comment] 2023-08-18 21:53
On hold for https://github.com/Expensify/App/pull/20888

**Comment by ShogunFire** [comment] 2023-08-22 11:35
They still haven't merged because it didn't solve their issue completely, I asked them if they are going to merge anyways

**Comment by ShogunFire** [comment] 2023-08-22 13:59
In that case @parasharrajat @Christinadobrzyn maybe I can do a PR with that fix

**Comment by Christinadobrzyn** [comment] 2023-09-05 20:27
@parasharrajat do you think we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2023-09-08 03:13
Hey @parasharrajat just checking before paying this out - do you think we need a regression test?

**Comment by hayata-suenaga** [comment] 2023-09-11 02:38
I agree with @parasharrajat 's regression tests

**Comment by Christinadobrzyn** [comment] 2023-09-12 21:15
Awesome thanks @parasharrajat 

Regression Test GH: https://github.com/Expensify/Expensify/issues/316248

Payouts due:

Issue Reporter: $250 @tranvantoan-qn - paid in Upwork
Contributor: $2000 + $1000 bonus @ShogunFire - paid in Upwork
Contributor+: $2000 + $1000 bonus @parasharrajat - paid through NewExpensify

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/21540#issuecomment-1691876606

Upwork job is [here](https://www.upwork.com/jobs/~013295df289a5037fc).

**Closed** 2023-09-12 21:16 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-21 09:50
$3,000 payment approved for @parasharrajat based on BZ summary.
