### ISSUE TITLE
Android - Video Attachment shows Link Preview for OldDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22933] opened 2023-07-15 11:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to App
2. Open any chat
3. Send an mp4 video as attachment.
4. Once the attachment is sent, link preview appears with link to OldDot.

## Expected Result:
 No link preview should appear for mp4 videos.

## Actual Result:
Link preview appears with link to OldDot.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/831031bc-a0da-403a-b020-bf3dd946c69a

https://github.com/Expensify/App/assets/93399543/d06fd778-5c75-4b5b-bcb2-38dd7d343bd6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689338090641839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Talha345** [comment] 2023-07-16 00:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When an mp4 attachment is sent in any chat ,a link preview to oldDot is shown.

### What is the root cause of that problem?
 
Since attachments are being stored and served via oldDot `props.action.linkMetadata` is available and it shows the link preview to the oldDot.

https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionItem.js#L347-L351

### What changes do you think we should make in order to solve the problem?


This should be handled on the backend and checked if the link is an attachment which can be easily checked because attachment links have the format `https://www.expensify.com/chat-attachments/4394150321175956513/w_7cc37f35a8be2bfdeacbb54c9c851fd1d2997e79.mp4` and contain `https://www.expensify.com/chat-attachments/` and linkMetadata should not be sent in this case.


### What alternative solutions did you explore? (Optional)

If the team wants to handle this on the frontend, this [const](https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionItem.js#L279) should be converted to `let isAttachment = false;` and initalized [here](https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionItem.js#L224) and [this line](https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionItem.js#L347) should be modified like:

`{!isHidden && !isAttachment && !_.isEmpty(props.action.linkMetadata)`

**Comment by StevenKKC** [comment] 2023-07-17 06:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video Attachment shows Link Preview for OldDot.

### What is the root cause of that problem?
For video attachment, report action have a message like below.
`<a href=\"https://www.expensify.com/chat-attachments/2687969988479401278/w_2785bfac52cf0546baa2ce84fff817380202cda2.mov\" data-expensify-source=\"https://www.expensify.com/chat-attachments/2687969988479401278/w_2785bfac52cf0546baa2ce84fff817380202cda2.mov\">iOS-Safari.mov</a>`

This is a valid url, so the `ReportActionsUtils.extractLinksFromMessageHtml` will returns a url, and then  `ExpandURLPreview` API will be called.
https://github.com/Expensify/App/blob/78f8a702512bf8ae91d2fe29e834e8e0c05ae786/src/pages/home/report/ReportActionItem.js#L144-L152
So the url preview is displayed for video attachment.

### What changes do you think we should make in order to solve the problem?
We should add checking if url is a video file or not.
```js
-   if (_.isEqual(downloadedPreviews.current, urls) || props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
+   if (_.isEqual(downloadedPreviews.current, urls) || props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || FileUtils.getFileType(urls[0]) === CONST.ATTACHMENT_FILE_TYPE.VIDEO) {
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by twisterdotcom** [comment] 2023-07-17 11:46
I think we should close this given we're building video playback anyway: https://github.com/Expensify/App/issues/20471

**Closed by twisterdotcom** 2023-07-17 11:46 UTC
Labels: Daily, Bug
