### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Chat - Wrong sub avatar for split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29614] opened 2023-10-14 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697216946635739

## Action Performed:
1. Open the app and login with user A
2. Open the app in another device and login with user B
3. From user A, invite user B in any workspace
4. From user B, click on green plus and click on request money
5. Enter any amount and continue
6. Click on split button besides workspace report used in step 3 and complete further process
7. From user A, open workspace chat created after inviting user B to a workspace
8. From user A, in workspace chat, observe the split bill avatar, it displays default profile sub avatar and on hover on it, it displays same user tooltip (It should display workspace square avatar as it does on production)

## Expected Result:
 App should display workspace profile in split message as sub avatar

## Actual Result:
App displays default profile image avatar of same user in split message

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/db9f25c6-8288-4e32-9671-9f93164893f7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/b6165d08-2240-40cc-ad43-24f6a5cf86fb

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/92368c32-53f6-4b8a-a401-347c389bf26e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/0f709996-b8f5-4949-bb0d-a734b7b53c50

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/644ebd7a-02a2-478e-bfb2-f65ab343948c

https://github.com/Expensify/App/assets/93399543/dd2440a3-b625-44fe-a8e5-476709e0b790

https://github.com/Expensify/App/assets/93399543/26dc0c6a-4d4f-4e3f-a8a6-099b32e14c24

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/867d9f12-274a-4625-85d6-c0b376833b18

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1fdbe3efd12338f</li>
        <li>Upwork Job ID: 1713231723488018432</li>
        <li>Last Price Increase: 2023-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27291697</li>
<li>dhanashree-sawant | Reporter | 27291698</li>
</ul></li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-10-15 00:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Wrong sub avatar for split bill

### What is the root cause of that problem?

The problem is inside the `ReportActionItemSingle` component when the condition below is `false`.
```
const isWorkspaceActor = ReportUtils.isPolicyExpenseChat(props.report) && (!actorAccountID || displayAllActors);
```

To retrieve the Workspace's icon (AKA "**secondaryAvatar**") for this kind of Report chat ("**policyExpenseChat**"), is used the method `getIcons` from the `ReportUtils` as you can see in the image below:

![image](https://github.com/Expensify/App/assets/698363/d6b0e511-effb-4a19-b92e-a43a2538dc1b)

The method `getIcons` returns a tuple with the icons whose positions depend on the Report type.

When the Report type is `expense` then the position **Zero** will have the member icon, and the position **One** will have the workspace icon, otherwise the position **Zero** will have the workspace icon, and the position **One** member icon.

```
function getIcons(report, personalDetails, defaultIcon = null, defaultName = '', defaultAccountID = -1, policy = undefined) {
    ...
    if (isPolicyExpenseChat(report) || isExpenseReport(report)) {
        const workspaceIcon = getWorkspaceIcon(report, policy);
        const memberIcon = {
            source: UserUtils.getAvatar(lodashGet(personalDetails, [report.ownerAccountID, 'avatar']), report.ownerAccountID),
            id: report.ownerAccountID,
            type: CONST.ICON_TYPE_AVATAR,
            name: lodashGet(personalDetails, [report.ownerAccountID, 'displayName'], ''),
            fallbackIcon: lodashGet(personalDetails, [report.ownerAccountID, 'fallbackIcon']),
        };
        return isExpenseReport(report) ? [memberIcon, workspaceIcon] : [workspaceIcon, memberIcon];
    }
    ...
}
```

In the `ReportActionItemSingle` component, to know which position has the `secondaryAvatar` is checked if the `isOwnPolicyExpenseChat` property in the Report has the value `true`, if yes, it gets the position **Zero**, otherwise, the position **One**. (as you can see in the first image)

The problem is that the `ReportActionItemSingle` component uses the position **One** where there is the `memberIcon` object because the `isOwnPolicyExpenseChat` property in the Report has the value `false`.

### What changes do you think we should make in order to solve the problem?

To get the correct position in the tuple, we should add a condition to use the position **Zero** if the `isOwnPolicyExpenseChat` property in the Report has the value `true` (current logic) **or** if this Report is a policy Expense chat.

### What alternative solutions did you explore? (Optional)

I tried to understand why the `getIcons` methods should return a tuple with different values for the index related to the Report's type, but there are many locals that use this method and change this piece of code to return always the same values in the same position without tests is a change that I thought could bring other issues.

**Fix evidence:**

https://github.com/Expensify/App/assets/698363/252b856d-e53e-4d38-8924-6f2e793d9e7f

**Comment by Tony-MK** [comment] 2023-10-15 03:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong sub avatar for split bill

### What is the root cause of that problem?

The root cause of the problem is that the `secondaryAvatar` variable is the `memberIcon` instead of being the `workspaceIcon` after the spilt action occurs.

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/home/report/ReportActionItemSingle.js#L129

After the spilt action is created, the `isExpenseReport` function outputs `false` when the first report action, the money request, is passed through it. Since, `report.action.isOwnPolicyExpenseChat` is `false` for user A, it will select the second icon item in the output array from `getIcons` function which is the `memberIcon`.

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/libs/ReportUtils.js#L1113-L1122

### What changes do you think we should make in order to solve the problem?


Since we need to get the `workspaceIcon` instead of the `memberIcon` from the icons array, I believe that adding other condition for checking if the report is the not an expense report. 

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/home/report/ReportActionItemSingle.js#L129

Therefore, changing the above line of code to something similar to the one below should allow the `workspaceIcon` can be selected for `secondaryAvatar`.

`secondaryAvatar = ReportUtils.getIcons(props.report, {})[props.action.isOwnPolicyExpenseChat || !ReportUtils.isExpenseReport(props.report) ? 0 : 1];`

**Comment by JmillsExpensify** [comment] 2023-10-17 21:06
@cubuspl42 thoughts on the proposals so far?

**Comment by cubuspl42** [comment] 2023-10-18 07:58
@Tony-MK Isn't your proposal essentially equivalent to the earlier one?

**Comment by Tony-MK** [comment] 2023-10-18 11:38
@cubuspl42 Thanks for reviewing my proposal. I believe my proposal has the same RCA as the one before. The difference is the solution. The added condition in my proposal checks if the report is not an expense report. Unlike the previous proposal, I suggest using the negation of the output from the `ReportUtils.isExpenseReport` function. While, the previous proposal checks if the Report is a policy Expense chat.

**Comment by cubuspl42** [comment] 2023-10-19 10:11
@wlegolas Do you maybe have a Git branch with the code you used to test your idea?

**Comment by wlegolas** [comment] 2023-10-19 13:40
Hi @cubuspl42 yes I already have. That video I created using my branch.

**Comment by wlegolas** [comment] 2023-10-19 15:09
Sure @cubuspl42, here is the link with the changes I did to fix this issue.

https://github.com/Expensify/App/compare/main...wlegolas:ExpensifyApp:bugfix/issue-29614

If you have any questions or suggestions, please let me know.

**Comment by wlegolas** [comment] 2023-10-20 00:43
Hi @cubuspl42 I updated my branch with a Unit Test to validate this issue.

![image](https://github.com/Expensify/App/assets/698363/b7093820-98ae-4c24-8451-81d169cdea4e)

You can see the changes in this link: https://github.com/Expensify/App/compare/main...wlegolas:ExpensifyApp:bugfix/issue-29614

**Comment by cubuspl42** [comment] 2023-10-20 08:40
@wlegolas

Your root cause analysis sounds solid and I appreciate the efforts to add tests!

We can move forward with the proposal by @wlegolas

C+ reviewed 🎀 👀 🎀

**Comment by wlegolas** [comment] 2023-10-20 09:05
Hi @cubuspl42 thank you for your feedback about my proposal and the tests.

I'll post today the PR with these changes and I'll let you know when the PR is available for review.

**Comment by wlegolas** [comment] 2023-10-20 10:55
Hi @cubuspl42 I opened the PR: https://github.com/Expensify/App/pull/30068

If you have any questions or suggestions, feel free to ask me.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:52
PR review in progress

**Comment by wlegolas** [comment] 2023-10-26 21:35
Hi @JmillsExpensify.

I didn't receive the offer for this job in my Upwork account, could you help me, please?

**Comment by techievivek** [comment] 2023-11-06 10:56
@JmillsExpensify It looks like @wlegolas hasn't received an upwork offer https://github.com/Expensify/App/issues/29614#issuecomment-1781927656, can you please take a look into it.

**Comment by cubuspl42** [comment] 2023-11-06 11:42
- The PR that introduced the bug has been identified. Link to the PR:
    -  N/A; As I understand this, this bug is more of an unimplemented case than a regression
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Open the app and login with user A
    - Open the app on another device and login with user B
    - From user A, invite user B to any workspace
    - From user B, click on green plus and click on request money
    - Enter any amount and continue
    - Press the "Split" button beside the workspace name, press "Add to split" and confirm the split summary
    - From user A, open workspace chat was created after inviting user B to a workspace
    - [ ] From user A, in workspace chat, observe the secondary (small) avatar, ensure that the initial letter is from the workspace name, and when hovering, ensure that the tooltip shows the workspace name.

**Comment by JmillsExpensify** [comment] 2023-11-08 16:56
Thanks for closing the loop on that regression test. I'll get it added.

**Comment by JmillsExpensify** [comment] 2023-11-08 17:02
Payment issue: 
 - Issue reporter: @dhanashree-sawant $50 
 - Contributor: @cubuspl42 $500
 - Contributor+: @wlegolas $500

**Comment by wlegolas** [comment] 2023-11-08 22:30
Hi @JmillsExpensify 

I asked in this comment https://github.com/Expensify/App/issues/29614#issuecomment-1781927656 that I haven't received an Upwork offer.

When I started this fix, I followed the instructions in this comment https://github.com/Expensify/App/issues/29614#issuecomment-1772323420 and applied to the [Upwork job](https://www.upwork.com/jobs/~01d1fdbe3efd12338f), but I don't know just applying to this job is enough.

Could you please help me understand if there is something else that I or you need to do?

**Comment by techievivek** [comment] 2023-11-13 10:46
@JmillsExpensify It looks like @wlegolas hasn't received an offer yet. Can you please take a look and help them with the next step, thanks.

**Comment by wlegolas** [comment] 2023-11-14 22:26
Hi @JmillsExpensify if I need to do something from my said, please let me know.

I followed the instructions in this comment https://github.com/Expensify/App/issues/29614#issuecomment-1772323420 applying to this job in Upwork, I don't know if can help you.

**Comment by techievivek** [comment] 2023-11-22 05:10
Gentle bump @JmillsExpensify ^

**Comment by JmillsExpensify** [comment] 2023-11-24 17:45
Sorry missed the notifications. Jumping in to resolve payments now!

**Comment by JmillsExpensify** [comment] 2023-11-24 17:52
Contributors with contracts paid out. @wlegolas if you're online at the moment, please accept the offer in Upwork and I'll make sure it's processed. Thank you!

**Comment by wlegolas** [comment] 2023-11-24 19:59
Hi @JmillsExpensify I accepted the offer.

Thank you so much.

**Comment by JmillsExpensify** [comment] 2023-11-24 20:09
All paid out and the regression test has been created. Closing this one out!

**Closed by JmillsExpensify** 2023-11-24 20:09 UTC
Labels: External, Daily, Awaiting Payment, Bug
