### ISSUE TITLE
Web - Profile - DEV: console error on adding Contact methods offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25575] opened 2023-08-21 11:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go offline
2. go to Settings > Profile > Contact methods
3. Add 2 contact method which is already existed
4. switch to online

## Expected Result:
should not show console error

## Actual Result:
console error appears ([Onyx] Onyx.set() called after Onyx.merge() for key: loginList. It is recommended to use set() or merge() not both.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cdf2aa26-a053-482a-9a7c-bc630b096992

https://github.com/Expensify/App/assets/115492554/ad2cd875-763c-4ff1-9ecd-c81be5eae712

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691676768775229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f95d30595edd29d</li>
        <li>Upwork Job ID: 1694478160924987392</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-21 12:04
This looks like a backend issue. `ReconnectApp` API returns the data like below
![image](https://github.com/Expensify/App/assets/126839717/d3f3f15b-4f1e-4737-8179-ecc5708aad93)

**Comment by sakluger** [comment] 2023-08-21 17:03
@vitHoracek do you mind taking a peek into this one? I know you're pretty familiar with Onyx errors.

**Comment by mountiny** [comment] 2023-08-21 17:11
@s-alves10 what do we use no when its optimistically added? Do we use set there?

**Comment by s-alves10** [comment] 2023-08-21 17:13
We use merge

**Comment by mountiny** [comment] 2023-08-21 17:14
So we could just use Merge on the reconnect, I assume

**Comment by sakluger** [comment] 2023-08-23 20:53
@mountiny do we need to assign a BE engineer on this one?

**Comment by mountiny** [comment] 2023-08-23 22:34
Yeah lets make this internal, I think we need to make sure we use correct Onyx method when deleting the contact method

**Comment by flodnv** [comment] 2023-08-25 09:25
I read the conversation above a few times and I'm a bit lost. 

> when deleting the contact method

@mountiny what does deleting the contact method have to do with anything in this issue? 😕

**Comment by mountiny** [comment] 2023-08-25 10:43
@flodnv checking again, there is no deleting here, I assumed that because there it Onyx::set used _somewhere_

Checking API, we use onyx merge which is correct https://github.com/Expensify/Web-Expensify/blob/5f2fa3923b789f1d4322b042faad80a9d9671fd5/lib/UserAPI.php#L1020 I ma not sure where the onyx set is coming from in this flow but that is probably the bug

**Comment by sakluger** [comment] 2023-09-05 18:03
@mountiny @flodnv what's the latest here?

**Comment by flodnv** [comment] 2023-09-11 05:49
No update, I was ooo and this seems benign.

**Comment by flodnv** [comment] 2023-09-11 09:13
This seems less important than current strategic priorities I'm working on. LMK if I'm wrong.

**Comment by flodnv** [comment] 2023-09-27 06:40
I am unable to reproduce this in production. Are you able to @gadhiyamanan @izarutskaya @sakluger ?

**Comment by gadhiyamanan** [comment] 2023-09-27 14:01
still able to reproduce this in production

https://github.com/Expensify/App/assets/54790231/42e1301a-d34e-44ac-bb41-dbfb11710ac9

**Comment by flodnv** [comment] 2023-09-29 05:57
Welp, I tried again, and still can't reproduce:


https://github.com/Expensify/App/assets/4164921/ba21b10d-7d1e-46ab-878b-0175c3eec541


How about you @sobitneupane @izarutskaya @sakluger @s-alves10, are you able to reproduce?

**Comment by sobitneupane** [comment] 2023-10-02 07:29
I was able to replicate the issue on latest dev and production as well.
<img width="358" alt="Screenshot 2023-10-02 at 13 11 59" src="https://github.com/Expensify/App/assets/25876548/2c9b73a6-c665-47e6-acf3-852065255132">

**Comment by izarutskaya** [comment] 2023-10-06 19:56
Not reproduced with build 1.3.79-3

https://github.com/Expensify/App/assets/115492554/a490142a-b131-4c69-9856-afe8ffce0984

**Comment by flodnv** [comment] 2023-10-09 09:06
@sakluger what about you? 😄 I suspect this might've something to do with the account itself, can you reproduce on a brand new account @gadhiyamanan ?

**Comment by gadhiyamanan** [comment] 2023-10-09 09:18
Able to reproduce with brand new account

**Comment by sakluger** [comment] 2023-10-19 16:54
What is the actual issue here? Are either of those contacts not added successfully after going back online? is this console error causing any performance issues or problems that a user would notice?

If not, I suggest we just close this issue and focus on bugs that are degrading the user's experience.

**Comment by flodnv** [comment] 2023-10-20 12:24
Agreed, I don't think there's any user impact?

**Comment by sakluger** [comment] 2023-10-23 20:20
Okay, thanks for confirming, let's close 👍

**Closed by sakluger** 2023-10-23 20:20 UTC
Labels: Engineering, Weekly, Internal, Bug
