### ISSUE TITLE
[$250] Composer - mWeb - Composer is not focused when returning to a chat with drafts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47163] opened 2024-08-09 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4842675
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat
2. Type a message in the composer
3. Navigate to another chat
4. Navigate back to the chat in step 1

## Expected Result:
The composer is focused and the cursor is at the end of the draft message

## Actual Result:
The composer is not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0a77c301-24bc-410b-9b87-f13f4462d176

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc0de3be0df7797d</li>
        <li>Upwork Job ID: 1823333045930339549</li>
        <li>Last Price Increase: 2024-08-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-08-09 13:34
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-09 13:34
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isogit123** [comment] 2024-08-09 23:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The Composer is not focused when opening a chat with a draft. The issue happens in the Android Chrome browser too.

### What is the root cause of that problem?
We have disabled the Composer autofocus when using a mobile device whether the Composer has a draft or not. As we can see in the following code snippet:
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L285-L291
`shouldFocusInputOnScreenFocus` is set to false when using a mobile device, which is set in the following code:
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L200-L201
The `canFocusInputOnScreenFocus` method returns false if we are using a mobile device.

### What changes do you think we should make in order to solve the problem?
In the following code:
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L285-L291
add ` || value` at line 290 so we autofocus the Composer if it has a draft.

Here is a POC after applying the solution:

https://github.com/user-attachments/assets/9310165c-4f5f-434b-b8f3-58954abeb20e



**Contributor details:**
Your Expensify account email: [aboutabl6@gmail.com](mailto:aboutabl6@gmail.com)
Upwork Profile Link: https://www.upwork.com/fl/islama33

**Comment by isogit123** [comment] 2024-08-13 05:08
> @isogit123 Please follow the contributor guidelines when you update the proposal:
> 
> > If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:

Thanks for mentioning that. I will do it next time.

**Comment by sonialiap** [comment] 2024-08-16 13:18
@jliexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for @getusha to review proposals

**Comment by getusha** [comment] 2024-08-18 07:27
Looks by design to me,
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L198-L199

**Comment by jliexpensify** [comment] 2024-08-19 00:43
Thanks @getusha - lets close this then. We're also de-prioritising VSB issues atm.

**Closed by jliexpensify** 2024-08-19 00:43 UTC
Labels: External, Daily, Help Wanted, Bug
