### ISSUE TITLE
[$500] mWeb/Chrome - Distance-In offline, distance request details page loading infinitely.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35087] opened 2024-01-24 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34604
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go offline
3. Tap on Workspace chat which has distance request created
4. Tap on distance request to open distance request details page

## Expected Result:
In offline, distance request details page must be displayed without loading

## Actual Result:
In offline, distance request details page loading infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/878bd4aa-e457-4bee-a6f2-43e1b429fe79

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed39265b86a00161</li>
        <li>Upwork Job ID: 1750223436772130816</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2024-01-25 05:43
Bringing the proposal from [here](https://github.com/Expensify/App/issues/32658#issuecomment-1869488988)
### What is the root cause of that problem?

As there is a purposeful reduction in data sent from BE in OpenApp, linked reports are not guaranteed to be present. This adversely impacts the offline experience. This is the root cause. 

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can ensure that the displayed reports in LHN are fetched at the app launch along with all linked reports up to a single level depth.  
More specifically, we can leverage `optionListItems` [here](https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/pages/home/sidebar/SidebarLinksData.js#L107) and ensure that all these reports are fetched once at app launch. Additionally, we can look for `childReportID` in Report Actions of these reports which is a good indicator of linked reports, and fetch them. 

We can implement a side effect [here](https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/pages/home/sidebar/SidebarLinksData.js#L107) which looks something like this to solve the problem:

    const fetchedReportIDsRef = useRef([]);
    useEffect(() => {
        const arrayChildReportIDs = [];
        optionListItems.forEach((reportID) => {
            const reportActions = allReportActions[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`];
            const childReportIDs = _.filter(_.pluck(reportActions, 'childReportID'),(childReportID) => childReportID);
            if(childReportIDs.length > 0) {
                arrayChildReportIDs.push(childReportIDs);
            } 
        });
        const allRecentReportIDs = _.union(optionListItems, ...arrayChildReportIDs);
        if(currentReportID) {
            allRecentReportIDs.push(currentReportID);
        }

        const unfetchedReportIDs = _.difference(allRecentReportIDs, fetchedReportIDsRef.current);
        unfetchedReportIDs.forEach((reportID) => {
            if(!reportID) {
                return;
            }
            Report.reconnect(reportID);
            fetchedReportIDsRef.current.push(reportID);
        });        
    }, [currentReportID, optionListItems, chatReports, betas, policies, priorityMode, allReportActions]);  

Additionally, we also need to include `childReportID` in `reportActionsSelector` [here](https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/pages/home/sidebar/SidebarLinksData.js#L220)

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-01-25 10:08
> As there is a purposeful reduction in data sent from BE in OpenApp, the report actions for a displayed report in LHN need not be present. This would bring about interesting scenarios in offline cases.
> 
> 1. If the user is `offline` at this moment, the report screen will keep showing the loading status for the chat report. But, when online, the chat report actions would be fetched via `openReport` if the user clicks on the report in LHN.
> 2. Now, if the user goes `offline` after fetching the chat report, a similar loading status will be shown for the IOU report when clicked.
> 3. The same situation will repeat for the transaction report as well.
> 
> When offline, is showing a loading status in each of the above three cases intentional?

@sophiepintoraetz @parasharrajat 
Can you please help clarify the above query as mentioned in my [proposal](https://github.com/Expensify/App/issues/35087#issuecomment-1909394507)?
Also, what would be the expected behaviour here?

**Comment by johncschuster** [comment] 2024-02-05 23:35
@parasharrajat, did you get a chance to look at the above proposal?

**Comment by johncschuster** [comment] 2024-02-08 21:36
@mananjadhav is taking over C+ review while Rajat is away

**Comment by mananjadhav** [comment] 2024-02-08 21:42
Just took over going through the issue history, and the linked issue discussion where the proposal was originally posted.

**Comment by mananjadhav** [comment] 2024-02-14 03:59
@lanitochka17 @rojiphil Can you confirm if this is reproducible in all platforms? I can see only Android mWeb marked? If it's specific platform, then I am wondering how can backend have impact on one platform only?

**Comment by lanitochka17** [comment] 2024-02-14 17:20
Issue is not reproducible on the latest build 1.4.41-4


https://github.com/Expensify/App/assets/78819774/aacb03b8-1913-457d-b4df-f6f417e2e7c7

**Comment by johncschuster** [comment] 2024-02-16 23:07
I've applied the retest-weekly label. If we find this behavior is no longer present on the next retest, I think we can close it.

**Comment by johncschuster** [comment] 2024-02-26 22:01
This issue has the retest label applied. Coming from [this process](https://stackoverflowteams.com/c/expensify/questions/18717/18718#18718), it looks like Applause will re-test by Friday and comment with their results on Monday.

**Comment by johncschuster** [comment] 2024-02-26 22:02
That said, this should have been tested this previous Friday and the results should be posted today-ish. @Expensify/applause, did this issue get retested in the last batch? If not, can you please add it? Thank you!

**Comment by mvtglobally** [comment] 2024-02-27 14:59
@johncschuster Updating results right now. Give me a couple minutes. Working on it

**Comment by mvtglobally** [comment] 2024-02-27 16:15
Issue is reproducible during KI retests.

**Comment by neil-marcellini** [comment] 2024-03-01 03:27
I took a look and I was able to reproduce the bug as described by the test steps. Are we sure that it's specific to distance requests? Does it happen for manual or scan requests with the same steps?

Please assign me once it's time to review a proposal.

**Comment by johncschuster** [comment] 2024-03-01 16:09
@Expensify/applause 

> Are we sure that it's specific to distance requests? Does it happen for manual or scan requests with the same steps?

**Comment by johncschuster** [comment] 2024-03-05 22:34
@lanitochka17 / @Expensify/applause 

> Are we sure that it's specific to distance requests? Does it happen for manual or scan requests with the same steps?

Can you please confirm this?

**Comment by johncschuster** [comment] 2024-03-11 21:15
@lanitochka17 / @applausebot bump on this! 

> Are we sure that it's specific to distance requests? Does it happen for manual or scan requests with the same steps?

Can you please confirm?

**Comment by johncschuster** [comment] 2024-03-14 21:03
Bumped in the QA channel

**Comment by kavimuru** [comment] 2024-03-15 15:34
@johncschuster not able to reproduce this bug now. 

https://github.com/Expensify/App/assets/43996225/214f2f0a-47c0-42ae-9d7c-1c55a7f83486


https://github.com/Expensify/App/assets/43996225/3f7e9d34-ddf5-4531-a2a7-f18fa6749d4c

**Comment by johncschuster** [comment] 2024-03-15 20:51
Great! In that case, I'm going to go ahead and close it. Thanks, @kavimuru!

**Closed by johncschuster** 2024-03-15 20:51 UTC
Labels: Engineering, Daily, Internal, Bug
