### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] HIGH: Improve formatting of People in this workspace can find your room message

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32614] opened 2023-12-07 03:49 UTC
**Problem:**
The `People in this workspace can find your room` message here is visually disconnected from the visibility selector:

![Image](https://github.com/Expensify/App/assets/575186/10c40c75-67b8-493e-9c08-eb5c49204d4d)

**Solution:**
Redesign this field to be more like the "priority mode" selector, where the messages are in the selections themselves:

![Image](https://github.com/Expensify/App/assets/575186/5a6a371f-da9b-4da9-8e4b-85348fa86960)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123449fd9ddb566ea</li>
        <li>Upwork Job ID: 1734735737424388096</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28071605</li>
<li>esh-g | Contributor | 28071606</li>
</ul></li>
    </ul>
</details>

**Comment by quinthar** [comment] 2023-12-11 20:03
@shawnborton coming through with a great mockup:

![image](https://github.com/Expensify/App/assets/575186/9af14df1-e86a-4618-95ef-92598f047f18)

**Comment by quinthar** [comment] 2023-12-11 20:03
@mallenexpensify I see you assigned yourself; can you clean this up and get a contributor on it?

**Comment by esh-g** [comment] 2023-12-12 09:21
# Proposal

## Please re-state the problem we are trying to solve
The People in this workspace can find your room message here is visually disconnected from the visibility selector

## What changes should be made to fix this?
We already pass a description to the `ValuePicker` with the item prop from the `WorkspaceNewRoomPage.js` we just need to use it as `alternateText` in the `ValueSelectorModal`, so that it can be passed into the `SectionList` properly here:
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/components/ValuePicker/ValueSelectorModal.js#L43-L45
This can be done by adding a property to the object like this:
```js
{alternateText: item.description}
```
We can also possibly rename the description to `alternateText` in `WorkspaceNewRoomPage.js` as well.

**Result**

<img width="373" alt="Screenshot 2023-12-12 at 2 40 20 PM" src="https://github.com/Expensify/App/assets/77237602/477680fe-b1f1-4b20-82bf-52eeec4b03d4">

### **Additional changes (Optional)**
I also noticed some additional changes can be done to mimic the [design provided here](https://github.com/Expensify/App/issues/32614#issuecomment-1850797464) more closely
- Make the title of every item bold like in the design
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/components/SelectionList/BaseListItem.js#L92
We can modify this to be bold every time `alternateText` is provided like this:
```js
(isUserItem || item.isSelected) || item.alternateText ? styles.sidebarLinkTextBold : null,
```

- We can also possibly add some margin between the title and the `alternateText` if it exists to make it look better, since all titles are bold by adding this style:
```js
item.alternateText ? styles.mb1 : null,
```

- We can also possibly make the supporting text smaller.

**Result**
<img width="373" alt="Screenshot 2023-12-12 at 2 50 04 PM" src="https://github.com/Expensify/App/assets/77237602/5dfd9b32-9a11-4871-aa68-e5520e9f0441">

The **additional changes** section provides some optional changes that we can make or not depending on the design requirements.

**Comment by mallenexpensify** [comment] 2023-12-13 00:44
@s77rt please review @esh-g 's proposal above, thx

**Comment by s77rt** [comment] 2023-12-13 03:08
@esh-g Thanks for the proposal. Your RCA is correct and the suggested solution looks good but it's incomplete as you didn't cover the first point, the `People in this workspace can find your room` message is still detached from the value picker. I'm not sure if this is a blocker or not.

@shawnborton is it mandatory to keep the 3rd line (description line) the value picker, do you think it would be better if we remove it?

<img width="372" alt="Screenshot 2023-12-13 at 4 03 55 AM" src="https://github.com/Expensify/App/assets/16493223/d6a36f37-aefe-4023-ba57-689510fdfa40">
<img width="372" alt="Screenshot 2023-12-13 at 4 04 00 AM" src="https://github.com/Expensify/App/assets/16493223/42d77ad2-48e2-48d1-92fe-81976e4e7798">

**Comment by s77rt** [comment] 2023-12-13 03:17
@tienifr Thanks for the proposal. The suggested solution looks good. Adding a new prop to `MenuItem` for the 3rd line makes sense here but I'm not totally sure if that 3rd line is still needed. Asked above ^

**Comment by esh-g** [comment] 2023-12-13 10:21
@s77rt I only copied the design provided in the design, it doesn't look like any changes were made to the position of the text...

**Comment by sourcecodedeveloper** [comment] 2023-12-13 10:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The visibility selector of the Room section of start chat has disconnected description text that shows under the 
selected visibility.

### What is the root cause of that problem?
The disconnected description of visibility (workspace, public, private) is being seperately in Text element. The 3rd  description line is not needed and can be removed.

https://github.com/Expensify/App/blob/9f00f67484d8da1ccf568d19b3b615f245671978/src/pages/workspace/WorkspaceNewRoomPage.js#L299

To put the description in the selection, the BaseListItem uses has an alternateText prop which can be used to display description of visibility selector. The valueSelectorModal can pass alternateText prop when setting sectionsData.

https://github.com/Expensify/App/blob/9f00f67484d8da1ccf568d19b3b615f245671978/src/components/ValuePicker/ValueSelectorModal.js#L44

```
useEffect(() => {
        const itemsData = _.map(items, (item) => ({value: item.value, alternateText: item.description, keyForList: item.value, text: item.label, isSelected: item === selectedItem}));
        setSectionsData(itemsData);
    }, [items, selectedItem]);
```

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2023-12-13 10:28
@s77rt I have tried to keep the proposal simple and remove the 3rd (description line) and also keep the visibility selector description match with priority mode.

**Comment by s77rt** [comment] 2023-12-13 15:42
@esh-g The description text is supposed to be a part of the picker. Highlighting the picker should cover the description text.

**Comment by s77rt** [comment] 2023-12-13 15:43
@sourcecodedeveloper Thanks for the proposal. Unfortunately it's a dupe.

**Comment by esh-g** [comment] 2023-12-13 16:33
@s77rt I have modified my [proposal](https://github.com/Expensify/App/issues/32614#issuecomment-1851610628) to accommodate the requirement. I have figured out a solution **without needing to add an additional prop!** to the `MenuItem`. Could you please once review the result video attached and the first point of the additional changes section?
Thanks

https://github.com/Expensify/App/assets/77237602/d67fc0ab-159e-403d-8c56-5476e99feb40

**Comment by s77rt** [comment] 2023-12-13 17:29
@esh-g Thanks for the update. The solution looks much better now. Let's get this fixed 🚀 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/32614#issuecomment-1851610628)

**Comment by esh-g** [comment] 2023-12-14 05:25
@tienifr I think it's pretty important to know whether a new prop will be added or a previous one reused...

**Comment by mallenexpensify** [comment] 2023-12-15 16:45
@robertjchen please review the proposal above
https://github.com/Expensify/App/issues/32614#issuecomment-1851610628

@shawnborton can you answer this [question from above ](https://github.com/Expensify/App/issues/32614#issuecomment-1853196858)too plz? 
> is it mandatory to keep the 3rd line (description line) the value picker, do you think it would be better if we remove it?

Regarding the issue with two proposals as a first step I (the BZ, not an engineer) would start with this from [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Note%3A%20Before%20submitting%20a%20proposal%20on%20an%20issue%2C%20be%20sure%20to%20read%20any%20other%20existing%20proposals.%20ALL%20NEW%20PROPOSALS%20MUST%20BE%20DIFFERENT%20FROM%20EXISTING%20PROPOSALS.%20The%20difference%20should%20be%20important%2C%20meaningful%20or%20considerable.)
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

@tienifr would you say "The difference should be important, meaningful or considerable."  ?

**Comment by shawnborton** [comment] 2023-12-18 17:01
> is it mandatory to keep the 3rd line (description line) the value picker, do you think it would be better if we remove it?

Let's make it look just like this mockup:
![image](https://github.com/Expensify/App/assets/2319350/7bb13012-eb9d-4415-a4bd-850f14ad927f)


Also, it looks like the font size for the description under the select list items is not correct. Why aren't we reusing the same style we already have in place for focus/priority mode?

**Comment by shawnborton** [comment] 2023-12-18 17:02
Also, I think we need to update so that even inactive list items are in bold and our normal text color.

**Comment by esh-g** [comment] 2023-12-18 17:35
@shawnborton It is the same component we are using for the focus/priority mode. Is [this video](https://github.com/Expensify/App/issues/32614#issuecomment-1854272349) correct in the design? It has the title for non-active items bold. Could you please point out any design inconsistencies in the video?

**Comment by shawnborton** [comment] 2023-12-18 18:13
The feedback I have for that is that:
- the titles of all select list options should be bold and in our normal text color
- the subtitle/description text for all select list options should use our 13px font size (label) and our textSupporting color

We should make those changes globally to all of these select list options. cc @Expensify/design for the gut check

**Comment by dannymcclain** [comment] 2023-12-18 18:36
That sounds right to me @shawnborton.

**Comment by esh-g** [comment] 2023-12-19 03:47
- Title for all normal list items is bold (as proposed in my proposal)

- We are using the 13px textSupporting style already for the value picker
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/components/SelectionList/BaseListItem.js#L92

So, I would say that lines up with the expectations cc @robertjchen

**Comment by shawnborton** [comment] 2023-12-19 13:48
I think we should do this for all list selections. cc @thiagobrez and @cristipaval - do you know if maybe we just missed this during implementation? It looks like the list options for generic select lists don't quite match what we had mocked up.

**Comment by mallenexpensify** [comment] 2023-12-23 18:24
Re: hiring of the contributor. From [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) 
> Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

I'm unsure if this is clear cut, unfortunately.   I think it's up to the discretion of @s77rt , based on our process for which they think is _better_.  I'm off this coming week (as well as most others) then will chime back in.

**Comment by s77rt** [comment] 2023-12-24 10:14
@tienifr to be fair and to address https://github.com/Expensify/App/issues/32614#issuecomment-1859503674 I think the timeline is as follow:
1. @esh-g Fixed the missing alternateText in ValueSelectorModal
2. You added to that solution moving the "People in this workspace can find your room" message to the MenuItem component using a new prop
3. @esh-g added to your solution that we can move the message without using a new prop but an existing one 

The 2->3 change is indeed not important and not a critical factor for proposal selection. But the 1->2 change is also not much valuable as it's pretty obvious since adding a text line to a component is pretty straightforward.

Even if we went with the 1st proposal from @esh-g we won't miss a thing. For that reasoning I think it's fair to go with @esh-g's proposal

I hope that clarifies it. If you think I'm missing something here please create a Slack thread and tag me there. Let's keep GH for proposals only. I would really appreciate your collaboration here.

**Comment by s77rt** [comment] 2023-12-27 15:44
Waiting on design input

**Comment by quinthar** [comment] 2023-12-28 01:10
I'm sorry for my confusion; @s77rt what exactly are you waiting on?  Can you please list and number your questions so we don't miss them?

**Comment by esh-g** [comment] 2023-12-28 01:22
I think we already got the design input here: https://github.com/Expensify/App/issues/32614#issuecomment-1862792477 we just need to wait for @robertjchen's approval

**Comment by s77rt** [comment] 2023-12-28 01:33
@quinthar I'm not waiting on the design input myself. @shawnborton is suggesting to change the current selection list design to match the mock up (the mock up that was originally designed for the selection list in general and not just the one above for the visibility selector). This is not a blocker though. We are waiting for @robertjchen review on https://github.com/Expensify/App/issues/32614#issuecomment-1854416404.

**Comment by robertjchen** [comment] 2023-12-28 13:12
Appreciate all the discussion here @tienifr @esh-g @s77rt  ! 🙇 Having reviewed everything that has transpired, I'm inclined to agree with @s77rt 's conclusion here: https://github.com/Expensify/App/issues/32614#issuecomment-1868481620 

Given that the follow-on changes and feedback to @esh-g 's proposal were not critical for proposal selection, their initial proposal would've qualified. Let's move forward here 👍

**Comment by esh-g** [comment] 2023-12-28 17:37
Thanks for assigning me! The PR is here: https://github.com/Expensify/App/pull/33717#issuecomment-1871369253

cc @s77rt

**Comment by quinthar** [comment] 2023-12-30 23:29
Hi!  I'm curious what this is waiting on?

**Comment by s77rt** [comment] 2023-12-30 23:34
@quinthar We have a PR already but we need figma design to get the exact spacing. Also there is one change that we need to get a confirmation on, changing the label font size is global and will change the one in Flag list:



| BEFORE | AFTER  |
|--------|------------|
|   <img width="375" alt="293314302-1bf24570-dd62-4a02-97ec-1937ac515d43" src="https://github.com/Expensify/App/assets/16493223/f39a0087-e344-4170-9737-b5a807b7093e">     |     <img width="375" alt="293381691-d401bca7-9dfb-4ea6-8e10-e700657cdfcc" src="https://github.com/Expensify/App/assets/16493223/c32a6bef-3fac-43f2-9c4c-a471c13e1e54">       |

**Comment by quinthar** [comment] 2023-12-30 23:44
@s77rt can you stick with the original spacing?  If you do that, does that answer all your questions, so you can merge this?

**Comment by quinthar** [comment] 2023-12-30 23:45
Actually I'll comment in the other thread.

**Comment by mallenexpensify** [comment] 2024-01-17 19:08
Checked on iOS and everything looks good/correct. 

> ⚠️ Looks like this issue was linked to a Deploy Blocker https://github.com/Expensify/App/issues/34644

I'm assuming this is **not** related to a deploy blocker and that payment is due now.  Please comment if you disagree and I'll wait a day to issue payment.

**Comment by mallenexpensify** [comment] 2024-01-17 20:16
Contributor: @esh-g paid $500 via Upwork
Contributor+: @s77rt paid $500 via Upwork

@s77rt it looks like the bug zero checklist didn't auto-post, can you fill this out plz?
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:


- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by s77rt** [comment] 2024-01-17 21:28
- The PR that introduced the bug has been identified: The detached view was that way since the first implementation https://github.com/Expensify/App/pull/7876 and the label font size is a regression from https://github.com/Expensify/App/pull/32532
- The offending PR has been commented on: First PR: n/a. Second PR: https://github.com/Expensify/App/pull/32532#discussion_r1456489923
- A discussion in #expensify-bugs has been started: I don't think this is needed. The first PR did nothing wrong. The second PR the bug could have been prevented during testing phase
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal** 

Test 1

1. Click on the '+' FAB.
2. Click on 'Start chat'
3. Select the '#Room' tab
4. Hover the Visibility menu item
5. Verify that the visibility description text e.g. 'People in your workspace can find this room' is part of the hovered item
6. Click on the Visibility menu item
7. Verify that all of the options's titles are in bold


Test 2

1. Go to Settings > Workspaces > any workspace > Members and click Invite
2. Verify that the font size of the second line (email line) of each option is smaller than that of the first line (full name line)
3. Go to Settings > Preferences > Priority mode
4. Verify that the font size of the second line of each option is smaller than that of the first line

**Comment by s77rt** [comment] 2024-01-17 21:29
@mallenexpensify ^

**Comment by mallenexpensify** [comment] 2024-01-19 21:34
Thanks @s77rt regression test update [here](https://github.com/Expensify/Expensify/issues/362184)

**Closed by mallenexpensify** 2024-01-19 21:34 UTC
Labels: External, Weekly, Awaiting Payment
