### ISSUE TITLE
[HOLD for payment 2023-11-29] [HOLD for payment 2023-11-27] IOU - App is crashed after request money and clicking on IOU detail

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31407] opened 2023-11-15 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Request money
4. Click on IOU detail

## Expected Result:
App is not crashed after request money and clicking on IOU detail

## Actual Result:
App is crashed after request money and clicking on IOU detail

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20dbe818-70b6-44f7-bc94-4f1491d5e36c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-11-16 02:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- App is crashed after request money and clicking on IOU detail

### What is the root cause of that problem?
- We did not imported the Permission file so when calling ```Permissions.canUseViolations()```, it will lead to the bug.
### What changes do you think we should make in order to solve the problem?
- Add ```import Permissions from '@libs/Permissions';``` to the file that calls ```Permissions.canUseViolations()```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by s-alves10** [comment] 2023-11-16 05:19
Looks like a regression of this PR https://github.com/Expensify/App/pull/31029

**Comment by roryabraham** [comment] 2023-11-16 20:25
Fix verified on staging

**Comment by isabelastisser** [comment] 2023-11-29 18:49
Hey @MonilBhavsar, it looks like @Ollyws worked on this[ PR](https://github.com/Expensify/App/pull/31420), can you please clarify if a payment is needed for Olly and how much? I don't see an Upwork offer linked to the issue. Thanks!

**Comment by MonilBhavsar** [comment] 2023-11-29 18:53
No, it was done by Rajat. No payment is required here. We can simply close this issue.

**Closed by MonilBhavsar** 2023-11-29 18:53 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
