### ISSUE TITLE
[HOLD for payment 2024-02-05] [HOLD for payment 2024-02-01] Workspace - Workspace section loads infinitely after returning from Connect bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35071] opened 2024-01-24 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace default currency is not USD
1. Go to workspace settings
2. Go to Cards
3. Click Connect bank account
4. Click back button

## Expected Result:
Page loads without issue

## Actual Result:
Page loads infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67b98208-f0b8-41ce-9ab4-90479887f21d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cristipaval** [comment] 2024-01-24 20:00
It seems to be a regression of [this PR](https://github.com/Expensify/App/pull/34391)

**Comment by cristipaval** [comment] 2024-01-24 20:23
Opened a [PR](https://github.com/Expensify/App/pull/35098) with a fix

**Comment by cristipaval** [comment] 2024-01-24 21:30
> Oops. Didn't notice that. Thanks @cristipaval . ~But I see that `shouldShowLoading` was already true before that PR. 🤔~ Got it now.

Thanks @parasharrajat, for teaching me some Typescript to get the PR quickly ready for merge 🙇

**Comment by aldo-expensify** [comment] 2024-01-24 21:52
Merged!

**Comment by cristipaval** [comment] 2024-02-02 20:50
@JmillsExpensify I added the `Bug` label to have a BZ member.

This is a regression. I fixed it and @parasharrajat reviewed it. He's also the C+ for [the PR](https://github.com/Expensify/App/pull/34391) that introduced the regression. I don't know if any payment is due in this case 👀

**Comment by cristipaval** [comment] 2024-02-05 09:56
Asked internally [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1707126946067809) about the above

**Comment by cristipaval** [comment] 2024-02-05 10:15
Thanks @parasharrajat! Thanks again for quickly jumping into helping me fix it 🙇

**Closed by cristipaval** 2024-02-05 10:15 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
