### ISSUE TITLE
[$500] Help - No proper data fetching about the selected item ,Icon not loading and error message not properly shown.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28335] opened 2023-09-27 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login and go to settings.
2. Open help.
3. Tap on search icon and type "others" and search.
4. Now open any one of the data from the List.

## Expected Result:
Proper data should be there according to the selected Item, Icon  should be visible and error message must be proper.

## Actual Result:
No Data shown it says "Didn't find what you looking for?", icon is missing and error message is not shown proper.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e39d0647-a6b7-4486-b7bf-d16dfc784913

[screen-capture (9).webm](https://github.com/Expensify/App/assets/115492554/ea5bf553-3568-4077-9291-084ced33466f)

https://github.com/Expensify/App/assets/115492554/f24ee84d-9c59-4042-93af-fa096e2c04a6

![issue](https://github.com/Expensify/App/assets/115492554/a739e8cb-b267-4bdf-babf-f5c434883737)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @nileshahir286

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695739026514179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae48be67ef26da5d</li>
        <li>Upwork Job ID: 1707086943653638144</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-09-27 19:43
I believe this is internal, go to google.com and search "expensify everything about chat" and you would get a result with the following url "https://help.expensify.com/articles/other/Everything-About-Chat#gsc.tab=0" but in reality the new url should be "https://help.expensify.com/articles/new-expensify/getting-started/chat/Everything-About-Chat#gsc.tab=0" which means google is yet to crawl the new structure of the website. maybe someone should update the sitemaps in Google Search Console.

**Comment by stephanieelliott** [comment] 2023-09-29 06:47
Oh, actually this is a dupe of https://github.com/Expensify/App/issues/27405

**Closed by stephanieelliott** 2023-09-29 06:47 UTC
Labels: Daily, Internal, Help Wanted, Bug
