### ISSUE TITLE
[$500] Distance - "No results found" appears in a separate modal when there is no address history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33918] opened 2024-01-04 00:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: The app has no recent destination history
1. Go to workspace chat > + > Request money > Distance
2. Tap Start
3. Enter a space
4. Enter an address and save it
5. Tap Finish
6. Enter a space

## Expected Result:
Regardless of the presence of recent destination history, "No results found" is present in the same modal as "Use current location"

## Actual Result:
When there is no recent destination history (Step 3), "No results found" is present in a separate modal
When there is (Step 6), it appears in the same modal as "Use current location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c101012f-19a2-4783-89e2-35ece4cfcb34

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155e9889d404e91b1</li>
        <li>Upwork Job ID: 1742712339035541504</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2024-01-04 01:09
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
"No results found" appears in a separate modal when there is no address history.
### What is the root cause of that problem?
The root cause is that we didn't consider if the input value has only spaces here.
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/components/AddressSearch/index.js#L392-L398
### What changes do you think we should make in order to solve the problem?
We need to validate if the input value has only spaces

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by namhihi237** [comment] 2024-01-04 01:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Show not found when input the space
### What is the root cause of that problem?
We do not trim the search value before
### What changes do you think we should make in order to solve the problem?
We should use trim the search value

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-01-04 04:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The no result found view is separated from the "Use current location" button.

### What is the root cause of that problem?
The "Use current location" button is rendered in `inbetweenCompo` here
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/components/AddressSearch/index.js#L537-L548

and based on the doc `inbetweenCompo` renders a view between the search input and the list result (in this case, no result found)
> Insert a ReactNode in between the search bar and the search results Flatlist

We currently render "Use current location" button in 2 places, one in the header component and the other on is `inbetweenCompo`.
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/components/AddressSearch/index.js#L370-L382

The header component will be shown only if the list is filled by the predefined places. If the list has empty predefined places, we render the "Use current location" with `inbetweenCompo`.

So, we can't remove `inbetweenCompo`. Another condition to show "Use current location" button is `shouldShowCurrentLocationButton`.

`shouldShowCurrentLocationButton` will stay true as long as the trimmed input is empty.
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/components/AddressSearch/index.js#L191

However, google places autocomplete will still do the request even when we input just space and so far we have no control over it, and eventually we will get no result found. Because `shouldShowCurrentLocationButton` is still true and we get "no result found", both "Use current location" button (`inbetweenCompo`) and the list result are shown separately.

### What changes do you think we should make in order to solve the problem?

Update `shouldShowCurrentLocationButton` condition by removing the trim so it's align with the google places autocomplete behavior.

### What alternative solutions did you explore? (Optional)
Update google places autocomplete upstream by 
1. Trimming the string so it won't do a request if the input is empty.
2. Only show the list if the trimmed string is not empty.

**Comment by aim-salam** [comment] 2024-01-04 05:11
.

**Comment by paultsimura** [comment] 2024-01-04 09:10
There has already been an issue for this with an approved proposal that included an upstream fix coordinated with the google-places-autocomplete author: https://github.com/Expensify/App/issues/31626#issuecomment-1821060237.

It was closed as "not important". Therefore, if the issue is relevant, https://github.com/Expensify/App/issues/31626 should be reopened.
cc: @alitoshmatov @arosiclair @miljakljajic

**Comment by paultsimura** [comment] 2024-01-04 11:34
> the issue here is with the how no results is displayed

The root issue here is that the "No results found" appears when a blank search request is entered, while it should not be displayed for such requests – that's exactly what https://github.com/Expensify/App/issues/31626 was about

**Comment by shubham1206agra** [comment] 2024-01-04 13:28
@paultsimura You can post the same proposal here also. I don't think anyone has proposed the same solution yet.

**Comment by twisterdotcom** [comment] 2024-01-08 13:59
I agree here, we can close this out the same as https://github.com/Expensify/App/issues/31626#issuecomment-1829928865

**Closed by twisterdotcom** 2024-01-08 13:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
