### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17]  Category - Disabled parent category is not grayed out in the list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44869] opened 2024-07-04 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4695701
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has these categories set up - Parent and Parent: Child
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense with Parent as category
4. Go to workspace settings > Categories
5. Disable the Parent category
6. Go to transaction thread of the expense in Step 3
7. Click Category

## Expected Result:
Both "Parent" category at the top of the list and in the list (the one with child category) will be grayed out because it is disabled

## Actual Result:
The "Parent" category is grayed out at the top of the list, but not grayed out in the list (the one with child category)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/55708829-e648-4af0-8550-12c33ad793b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-04 19:44
@chiragsalian  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-04 19:45
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-07-05 09:45
Looking at the bug, I think we can demote, the expense view is correctly flagging the category as disabled and the list also has this right for the top category so we do not have to CP this fix imho

**Comment by chiragsalian** [comment] 2024-07-05 17:09
Cool sounds good, since it is still a regression let's tackle this soon. Setting priority to daily.

**Comment by kadiealexander** [comment] 2024-07-22 21:41
Closing as no payment needed here.

**Closed by kadiealexander** 2024-07-22 21:41 UTC
Labels: Engineering, Daily, Awaiting Payment
