### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Track Tax] Distance tax - Tax amount is zero when distance rate with non-zero tax rate is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42802] opened 2024-05-29 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42342
## Action Performed:
Precondition:
- Track Tax distance is enabled on Old Dot.
- Workspace has a few distance rates and tax rates.
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Open submit distance expense flow
4. Proceed to distance expense confirmation page
5. Click Distance rate
6. Select a distance rate that has non-zero tax rate
7. Note that tax amount is updated after selecting a distance rate
8. Submit the expense
9. Go to transaction thread

## Expected Result:
The tax amount in the transaction thread will follow the amount based on the distance rate, which is the same amount on confirmation page

## Actual Result:
The tax amount in the transaction thread changes to 0.00 after the expense is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
</details> 

https://github.com/Expensify/App/assets/78819774/31e1b677-ba73-4add-b448-381dad008f25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment] 2024-05-29 20:47
@chiragsalian  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-29 20:49
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment] 2024-05-30 13:58
Looking...

**Comment by MonilBhavsar** [comment] 2024-05-30 15:09
I'm not able to reproduce this issue. @lanitochka17 could you please help to retest

**Comment by kbecciv** [comment] 2024-05-30 15:38
Issue is reproducible, please try to wait until  Distance is no longer pending.

https://github.com/Expensify/App/assets/93399543/551faa43-2cfe-4b94-8dd4-624e60b957b0

**Comment by MonilBhavsar** [comment] 2024-05-30 16:00
I also have same suspicion. Unfortuanately my requests are getting timed out, so I haven't been able to confirm https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%2288bfe11aba9489fc-BOM%22%20AND%20timestamp%3A%5B2024-05-30T00%3A00%20TO%202024-05-31T23%3A59%5D

But there is no new code deployed to staging, so it's not a Web-E blocker

**Comment by MonilBhavsar** [comment] 2024-05-30 16:09
Finally succeeded.

I am still not able to reproduce, I waited till the distance was populated

Recording https://drive.google.com/file/d/1j8ZTxJzLTdoguUEzflSZPBagw4FYBZxw/view?usp=sharing

Anyways, this should not block deploy and can be treated as a bug, if reproducible. I'll assign myself and look

**Comment by MonilBhavsar** [comment] 2024-05-31 11:09
Retried again and still no dice

**Comment by MonilBhavsar** [comment] 2024-05-31 11:19
Tom is helping to check if it's a real bug

**Comment by trjExpensify** [comment] 2024-05-31 11:35
1. I have selected the Standard tax rate for distance expenses:

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/d1838a75-d1a8-4e05-aef4-8d3da529a602">

2. The default tax rate for expenses in the workspace currency is the EC rate here: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/2785db7e-0f9c-454c-bd0c-788f392fcf0f">

3. The distance expense is using the workspace default rate and not the tax rate set for distance expenses:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/d008cae9-5658-417a-9b02-fc1a470b1be7">

So I think the bug is that we're using the workspace default tax rate and not the tax rate set for the distance rate. 👍

**Comment by MonilBhavsar** [comment] 2024-06-03 15:50
Will start working tomorrow

**Comment by trjExpensify** [comment] 2024-06-20 14:17
👋 can we confirm on this deploy blocker being a regression for this issue? https://github.com/Expensify/App/issues/42802#issuecomment-2152771576

**Comment by hungvu193** [comment] 2024-06-20 14:28
No. I think @MonilBhavsar already commented on the DB here:

https://github.com/Expensify/App/issues/43171#issuecomment-2152896117

That DB was caused by another PR.

**Comment by MonilBhavsar** [comment] 2024-06-20 14:43
Yes, it was not a regression from this PR

**Comment by trjExpensify** [comment] 2024-06-20 19:07
Great! Payment summary as follows:

- $250 to @hungvu193 for the C+ review 

Offer sent!

**Comment by hungvu193** [comment] 2024-06-21 01:49
> Great! Payment summary as follows:
> 
> * $250 to @hungvu193 for the C+ review
> 
> Offer sent!

Thanks Tom. I've just accepted!

**Comment by trjExpensify** [comment] 2024-06-21 14:02
Paid, closing!

**Closed by trjExpensify** 2024-06-21 14:02 UTC
Labels: Engineering, Daily, Awaiting Payment
