### ISSUE TITLE
[Guided Setup] [CVP] Add animated tooltip to GBR from Concierge/ExpensifyDM when a user first signs in.

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#42218] opened 2024-05-15 20:47 UTC
Problem: When users sign up for NewDot on mobile, they are dropped into the chat list and have a lot of options to click. We have invested in onboarding to give the users instructions on what to do based on their intentions. We currently put in a GBR but even that leaves it up to chance they might not click the GBR and learn how to use the app. If we do not make it very clear what to do next upon sign-up, we risk the chance of converting the user. 

Solution: For new users on NewDot who sign up via mobile, add an animated tool tip so it is very clear what to do next. It would look like this:

![CleanShot 2024-05-14 at 07 34 29](https://github.com/Expensify/App/assets/2364487/78876325-a8ad-4ae9-9f8c-0ae7fd6cd48f)

For note, web does not need to do this because we open up and show the LHN AND have the chat open already. 

Original discussion here: https://expensify.slack.com/archives/C03TBKRSB/p1715806228356299?thread_ts=1715040142.903759&cid=C03TBKRSB

cc @anmurali @dubielzyk-expensify @trjExpensify 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018075b7c8b5ef5a84</li>
        <li>Upwork Job ID: 1793677041663877120</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102451041</li>
<li>tienifr | Contributor | 102451045</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by jamesdeanexpensify** [comment] 2024-05-15 21:56
Would love to make the tool tip shorter, just `Get started here!`

**Comment by trjExpensify** [comment] 2024-05-15 23:06
Awesome! We're implementing the bones of this educational tooltip component for mobile in [this PR](https://github.com/Expensify/App/pull/40066) for the quick action, so hopefully it can be reusable very easily for this purpose. CC: @tienifr

**Comment by dubielzyk-expensify** [comment] 2024-05-16 00:20
> Would love to make the tool tip shorter, just Get started here!

Yes please!

> so hopefully it can be reusable very easily for this purpose.

Yeah that was my hope too. I've added some clarifying questions to ensure we can at least adjust the positioning as that'll be different for this issue

**Comment by danielrvidal** [comment] 2024-05-23 16:14
@tienifr the copy and issue is not ready for you to work on. Taking it off hold/planning. 

English: 
> Get started here!

Spanish:
>Comience aquí

**Comment by trjExpensify** [comment] 2024-05-23 16:50
Going to assign this to @tienifr and take off the `Help wanted` label as it'll be a follow-up to https://github.com/Expensify/App/pull/40066

Let's still get a proposal for it reviewed by @dukenv0307 when the time is right, but let's please complete the OG PR as a priority. 👍

**Comment by trjExpensify** [comment] 2024-05-24 14:13
Perfect, thanks. Assigned!

**Comment by danielrvidal** [comment] 2024-05-28 23:32
Hey team, any update on when we think we'll get to this one?

**Comment by danielrvidal** [comment] 2024-05-31 03:32
@dukenv0307 @tienifr what is the update on this one?

**Comment by danielrvidal** [comment] 2024-05-31 23:14
Got it, makes sense. Thank you for the update!

**Comment by danielrvidal** [comment] 2024-06-04 03:46
Just noting that we're still waiting on @tienifr to finished the issue linked early so we're holding.

**Comment by danielrvidal** [comment] 2024-06-05 03:35
Not sure why Melvin is freaking out here. We're still on hold.

**Comment by danielrvidal** [comment] 2024-06-10 12:02
@tienifr is still [working on the QAB tooltip](https://github.com/Expensify/App/pull/40066), so we're still holding until that is done.

**Comment by danielrvidal** [comment] 2024-06-19 22:25
Woo! @tienifr I saw the other tooltip merge yesterday, so sounds like we should be able to work on this one next?

**Comment by trjExpensify** [comment] 2024-06-20 14:11
Removing the hold from the title!

**Comment by danielrvidal** [comment] 2024-06-21 17:49
Awesome, thank you!

**Comment by danielrvidal** [comment] 2024-06-25 23:46
@tienifr it looks like you are woirking on this in the PR listed above. Let us know if you run into any issues. 

Also, @trjExpensify and @anmurali were talking and I believe this should be treated as CRITICAL. I'm guessing you are already prioritizing but please let me know if you have any question.

**Comment by trjExpensify** [comment] 2024-06-26 12:55
Might be worth bringing that to Slack @tienifr and tagging a few people you think would be good to provide input on what might be wrong. 👍

**Comment by trjExpensify** [comment] 2024-07-01 10:14
Did you do that, @tienifr? Can you link the thread here.

**Comment by trjExpensify** [comment] 2024-07-01 19:22
Putting this back on Daily. @tienifr please provide an update [on this](https://github.com/Expensify/App/issues/42218#issuecomment-2199761591).

**Comment by trjExpensify** [comment] 2024-07-03 10:08
Bump again here, @tienifr. This is a deliverable for our next deadline on July 22nd. We want to get this in place in good time, can you prioritise moving the draftPR into review today? Thanks!

**Comment by trjExpensify** [comment] 2024-07-03 10:09
Well you couldn't get better timing, ey! https://expensify.slack.com/archives/C01GTK53T8Q/p1720001303477089

**Comment by danielrvidal** [comment] 2024-07-09 00:38
It looks like @tienifr is still working on the solution here: https://expensify.slack.com/archives/C01GTK53T8Q/p1720455400941889?thread_ts=1720001303.477089&cid=C01GTK53T8Q

@roryabraham just gave him somewhere to research, but we're still waiting on the solution so it's still a WIP.

**Comment by trjExpensify** [comment] 2024-07-11 11:15
@Expensify/design question for yah above on this green light bulb. 

I see we didn't add that to the QAB educational tooltip ([mocks in the OP here](https://github.com/Expensify/App/issues/38054)), so do we for sure want it here? If so, can we get it to @tienifr and let's add it on the QAB tooltip as well.

**Comment by shawnborton** [comment] 2024-07-11 12:04
Hmm good find, curious what @dubielzyk-expensify might be thinking here - I do like including it for the QAB tooltip personally, it does look quite nice when it's there.

**Comment by trjExpensify** [comment] 2024-07-11 12:21
Yeah, sorry if that wasn't clear, I like it as well. Just noticed we don't have it on the QAB tooltip, so wanted to be sure you guys do want it, and we should add it in all places.

**Comment by dannymcclain** [comment] 2024-07-11 13:15
>Yeah, that would be my vote - use it and be consistent everywhere 👍

Yeah I like the idea of using it everywhere. It's a nice little detail!

**Comment by trjExpensify** [comment] 2024-07-11 13:35
Great! Anyone know where that icon is so @tienifr can use it?

**Comment by dannymcclain** [comment] 2024-07-11 14:38
I see it here: `App/assets/images/emojiCategoryIcons/light-bulb.svg`

Is it ok to use from that directory or should we also add it to `App/assets/images` (which is where all of our regular UI icons live)?

**Comment by trjExpensify** [comment] 2024-07-11 14:46
Oh but that one looks different than the icon in the tooltip... 

![image](https://github.com/Expensify/App/assets/16232057/4761e984-ab16-4b16-bbee-7fe3fc89622e)

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/16232057/b0f92c27-3319-4b42-b32b-cc0beaee7770">

**Comment by trjExpensify** [comment] 2024-07-11 14:48
Sorry, I was in the wrong place! https://github.com/Expensify/App/blob/main/assets/images/emojiCategoryIcons/light-bulb.svg

**Comment by shawnborton** [comment] 2024-07-11 14:59
I have no idea where the icon _should_ be placed... I don't think there's a great reason why it ended up in the emojiCategory folder, we were probably just trying to organize things or something?

**Comment by dannymcclain** [comment] 2024-07-11 15:06
It's used as a category icon in the emoji picker (which is why I think it's in the emojiCategory) folder. So that makes sense, I just don't know if it's cool to use it from there for other places. 🤷‍♂️ I'll let the engineers weigh in on that.

**Comment by dubielzyk-expensify** [comment] 2024-07-12 00:48
I've had a few versions tossing around with and without icon. I could see icon being a optional prop, but happy to use it and be consistent everywhere 👍

**Comment by danielrvidal** [comment] 2024-07-12 19:58
So does that give @tienifr everything he needs?

**Comment by danielrvidal** [comment] 2024-07-16 04:19
@tienifr can you please provide an update on this one?

**Comment by trjExpensify** [comment] 2024-07-19 10:42
@dukenv0307 I'm assigning you to the draftPR so you can participate. We would very much appreciate the focus on getting this over the line. It's dragging out. Thanks!

**Comment by danielrvidal** [comment] 2024-07-22 20:47
@trjExpensify[ bumped the draftPR](https://github.com/Expensify/App/pull/44277) one today for @tienifr so we're still making progress.

**Comment by trjExpensify** [comment] 2024-07-24 18:35
Putting this back on daily.

**Comment by quinthar** [comment] 2024-07-26 03:23
Saw this way above:
> For note, web does not need to do this because we open up and show the LHN AND have the chat open already.
This should work on mobile web, but maybe not on desktop.

**Comment by francoisl** [comment] 2024-08-01 22:44
> @danielrvidal Can we use Onyx's `nvp_isFirstTimeNewExpensifyUser` to indicate first-time sign up users? I tried with a completely new email but the BE still returns `nvp_isFirstTimeNewExpensifyUser` as false.

@tienifr You can use that NVP. The wrong value you get might be due to a rerender because of Strict Mode in dev. `OpenApp` gets called twice, which causes the NVP to be set to `false`. Try following https://expensify.slack.com/archives/C01GTK53T8Q/p1720173674628659 to test with strict mode disabled.

**Comment by trjExpensify** [comment] 2024-08-09 15:19
I can repro that as well on staging, FWIW: 

https://github.com/user-attachments/assets/840f90d2-52a6-450d-9b7f-8467abb132ad

**Comment by francoisl** [comment] 2024-08-13 01:32
I can repro on staging as well, looks like it's being updated to `false` by `GetMissingOnyxMessages`. The way this NVP is updated in the backend is not ideal at the moment, though I don't have a great solution for you in mind at the moment. I'm asking around internally to see if there's a more reliable way to make this work.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7251972c-d4c8-4c65-8950-d33bf28080ce">

**Comment by francoisl** [comment] 2024-08-16 00:46
Hi @dukenv0307, we have an internal tracking issue for a backend fix, though there's no movement on it just yet. I should be able to get to it ~next week if no one else can pick it up by then.

**Comment by trjExpensify** [comment] 2024-08-26 12:26
@marcaaron is working on it, hopefully in the next couple of days it'll be ready.

**Comment by trjExpensify** [comment] 2024-08-28 12:41
Copying these BE blockers over for my tracking: 

https://github.com/Expensify/Auth/pull/12236 - merged, awaiting a deploy
https://github.com/Expensify/Web-Expensify/pull/43274 - held on auth above.

**Comment by trjExpensify** [comment] 2024-08-30 14:30
Web is merged, awaiting a deploy.

**Comment by trjExpensify** [comment] 2024-09-02 23:02
We're still waiting on today's Web deploy to get this to staging. Our Web deployer is on PST this week, so likely to go out before end of day on the US west coast. 👍

**Comment by trjExpensify** [comment] 2024-09-04 11:19
Web PR is on staging.

**Comment by marcaaron** [comment] 2024-09-05 01:37
Changes should be live on production now.

**Comment by mallenexpensify** [comment] 2024-10-14 18:05
Contributor: @tienifr owed $250 via NewDot
Contributor+: @dukenv0307 paid $250 via Upwork

Do we want a regression test here?

**Comment by mallenexpensify** [comment] 2024-10-14 18:20
There's a test case here https://expensify.testrail.io/index.php?/cases/view/3272232
![image](https://github.com/user-attachments/assets/c772e558-36ee-4c7a-b2bf-c7f46040a616)

Closing this out.  Thanks @dukenv0307 and @tienifr , sorry payment took a bit (automation _should_ be working correctly now)

**Closed by mallenexpensify** 2024-10-14 18:20 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by danielrvidal** [comment] 2024-10-14 18:21
Thanks @mallenexpensify!

**Comment by garrettmknight** [comment] 2024-10-23 09:37
$250 approved for @tienifr
