### ISSUE TITLE
Invoice - Missing tag is shown briefly for invoice when must tag for all expense enabled

### ISSUE THREAD

**Issue by vincdargento** [Expensify/App#54212] opened 2024-12-16 20:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935+796@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10 / Chrome, Samsung s10/ Chrome
**App Component:** Chat Report View

## Action Performed:
Prerequires: Create WS and enable Invoice and Tag - have at least 2 tags and enable "members must tag all expense"

1. Navigate to https://staging.new.expensify.com
2. FAB> Send invoice and finish the flow
3. Navigate to invoice detail page

## Expected Result:
Missing Tag should not be shown

## Actual Result:
Missing Tag shown briefly

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2d0cbb56-becb-4b57-a42e-fda08828e0f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-12-16 20:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
nvoice - Missing tag is shown briefly for invoice when must tag for all expense enabled

### What is the root cause of that problem?
This is because we set violations for invoices optimistically
https://github.com/Expensify/App/blob/476f3979f1ae6b89eee5b853f7368603d50403b0/src/libs/actions/IOU.ts#L1051-L1059
but the backend resets the violations so it disappears
### What changes do you think we should make in order to solve the problem?

We should not set violations optimistically for invoices to align with the BE
```
    if (violationsOnyxData && !ReportUtils.isInvoiceReport(iou.report)) {

```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-12-17 05:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing Tag shown briefly

### What is the root cause of that problem?
We have two problems

1. The tag option isn't displayed in the confirmation step but it's displayed in `MoneyRequestView`. The RCA is `isPolicyExpenseChat` [here](https://github.com/Expensify/App/blob/d86024e6688326b5c3040a3c752e0b00265389de/src/components/MoneyRequestConfirmationListFooter.tsx#L226) is `false` for send invoice since we don't set `isPolicyExpenseChat` as `true` for sender participant [here](https://github.com/Expensify/App/blob/d86024e6688326b5c3040a3c752e0b00265389de/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L126-L128)

2. the missing tag/category is displayed briefly after creating a send invoice. The RCA is we set the violation in optimistic data here but after the API is complete, the backend clears this violation.

https://github.com/Expensify/App/blob/d86024e6688326b5c3040a3c752e0b00265389de/src/libs/actions/IOU.ts#L1457

https://github.com/user-attachments/assets/5d5e96b5-307a-4f00-b4d9-33587e47e4f4


### What changes do you think we should make in order to solve the problem?
1. For problem 1, we should set `isPolicyExpenseChat` as `true` for sender participant here. 

Optional: We can also hide the required label for tag/category and not auto-populate tag/category on the confirmation page if the request is a send invoice

https://github.com/Expensify/App/blob/d86024e6688326b5c3040a3c752e0b00265389de/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L126-L128

2. For problem 2, since the backend doesn't return the violation for send invoice, we can remove the logic set optimistic violation here

https://github.com/Expensify/App/blob/d86024e6688326b5c3040a3c752e0b00265389de/src/libs/actions/IOU.ts#L1452-L1473

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


We can create a test for problem 2 with `buildOnyxDataForInvoice` function and verify that no violation is added in optimistic data
### What alternative solutions did you explore? (Optional)



**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by anmurali** [comment] 2024-12-31 23:11
This is a BE issue and we're still working on the bill pay VIP, and this is not a mainline flow for any customer. So I am closing it for now as not a priority.

**Closed by anmurali** 2024-12-31 23:11 UTC
Labels: Daily, Overdue, Bug
