### ISSUE TITLE
#announce workspace appears to the user without any notification and as read.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23204] opened 2023-07-19 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings then workspaces and create a new workspace
2. Click members > then click invite > choose User B to invite
3. Click Next > then Invite
4. Login as user B and find the #announce workspace he was just invited to inside the LHN.
## Expected Result: 
#announce room should appear for user B as unread and he got Notified that something new has been added to his LHN, and he is now a member of a new workspace. Just like what happens if he is added as a new chat or added as a group member.
Another scenario: is not to add  #announce workspace to user B LHN unless it had some messages inside it. I suggest this scenario because once the #announce has some messages inside it, it appears unread as expected.
## Actual Result:
 #announce workspace appears for user B as read and he doesn't get anything to notify him that something added to his LHN and that he has been invited to a workspace.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Screencast from 18-07-23 01_00_37.webm](https://github.com/Expensify/App/assets/43996225/5af6edd0-9dc4-40ac-a048-7c9a66e85ec7)

https://github.com/Expensify/App/assets/43996225/b0211775-19f2-4bb4-a9a6-9d23645317e7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689634166791039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hannojg** [comment] 2023-07-20 05:50
This could be a regression from my PR:

- https://github.com/Expensify/App/pull/21406

looking into it!

**Comment by hannojg** [comment] 2023-07-20 09:30
Taking my comment back, this issue is more of a feature request than a bug / regression

**Comment by michaelhaxhiu** [comment] 2023-07-21 00:55
Hmm maybe we should close this since it's a feature request. This started as a bug and we need to propose a feature it seems.

**Closed by michaelhaxhiu** 2023-07-21 00:55 UTC
Labels: Daily, Bug
