### ISSUE TITLE
Pasting content broken when editing a comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23281] opened 2023-07-20 15:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Type a message, hit send
2. Mouse over the message you just sent, click edit
3. Try to paste a link or any other message
## Expected Result: 
The pasted content appears in the message being edited
## Actual Result: 
The pasted content incorrectly appears in the chat input

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a1bdd0e2-69ff-456f-acb4-0549524b2d98

https://github.com/Expensify/App/assets/43996225/6da5f1b2-21c0-4aaa-83fa-b5f25c141c0e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689739937250569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-07-20 15:41
Dupe of https://github.com/Expensify/App/issues/22803

**Comment by JmillsExpensify** [comment] 2023-07-20 15:48
Oh cool, yes you're right. Thanks! Closing this one.

**Closed by JmillsExpensify** 2023-07-20 15:48 UTC
Labels: Daily, Bug
