### ISSUE TITLE
[$250] Web - Reimburse expenses - Offline save changes are not reflected immediately

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11845] opened 2022-10-14 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings->Workspace-Reimburse expenses
4. Kill the internet connection
5. Change the parameters for Rate and Unit
6. Turn on the internet connection

## Expected Result:
Offline save changes should be reflected immediately

## Actual Result:
It flashes to old values for a second, then the value remains unchanged

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195884587-59e3ffd2-5b75-4ae7-9523-1d882369c9a4.mp4

https://user-images.githubusercontent.com/43996225/199235434-c854c6ae-e6d3-4d55-b6ca-012903b0a7de.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2022-10-17 17:22
Shall investigate today

**Comment by chiragsalian** [comment] 2022-10-17 23:26
I can reproduce the issue on staging but not on dev. From the network request it looks like the issue is something related to persisted requests and may not necessarily be an issue with the code around rate and unit. Either way, I'm thinking of waiting to see if the next deploy just solves this issue. Demoting it to weekly till then.

**Comment by chiragsalian** [comment] 2022-10-26 18:15
I retested and it looks like its not an issue anymore. Can you retest and confirm @kbecciv?

**Comment by kbecciv** [comment] 2022-10-26 20:26
@puneetlath Checking, will update you shortly

**Comment by kavimuru** [comment] 2022-10-29 22:12
@chiragsalian It flashes to old values for a second, then the value remains unchanged. Please check this video.

https://user-images.githubusercontent.com/43996225/198854259-e9e48603-dae1-4992-a5ee-e75809ac5b4a.mp4

**Comment by kavimuru** [comment] 2022-11-01 12:46
@chiragsalian I have edited the steps, as per this new issue.

**Comment by chiragsalian** [comment] 2022-11-01 19:47
Sounds good. I'm like 90% sure the problem is front end and it might be an issue with how PersistedRequests and reconnectApp works. Either way, adding the appropriate labels for people to investigate.

**Comment by MitchExpensify** [comment] 2022-11-02 01:45
[Upwork Job](https://www.upwork.com/jobs/~01618cd009075d331c)

**Comment by tienifr** [comment] 2022-11-02 04:57
## Proposal

### Problem
Currently, in offline mode when the user edits the init rate and clicks save, this action will add in networkRequestQueue and will be called back if back online.
When comeback online, firstly api?command=OpenWorkspaceReimburseView will be called to refresh data (old data) and then api?command= UpdateWorkspaceCustomUnitRate to update Workspace Custom Unit Rate. So when saving changes in offline are not reflected immediately

### Solution
In Expensify/App/src/libs/actions/Policy.js
we'll change the read method to the write method to add api?command= OpenWorkspaceReimburseView to SequentialQueue to call synchronous

```diff
- API.read('OpenWorkspaceReimburseView', {policyID});
+ API.write('OpenWorkspaceReimburseView', {policyID});
```

Before

https://user-images.githubusercontent.com/113963320/199398261-26de8af4-c1d0-466c-a46f-aae8c5b29be5.mp4


After

https://user-images.githubusercontent.com/113963320/199398308-e96e5cf1-7b68-4095-96c6-c6fed77d02b7.mp4

**Comment by parasharrajat** [comment] 2022-11-05 01:43
I think we prioritized write operations before Reading in some PR. So this should be fixed by that.

I will discuss this on slack on Monday(when the team is active).

**Comment by jasperhuangg** [comment] 2022-11-07 16:51
This issue is solved by https://github.com/Expensify/App/pull/12219, closing

**Closed by jasperhuangg** 2022-11-07 16:51 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
