### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Unable to Upload PDF & JPEG files that contains a space in the file title

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22219] opened 2023-07-04 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. click plus button on the composer and upload a Password Protected PDF attachment with a space in the title (example below)
3. Observe the error, then dismiss the error
4. now attach a regular PDF that has a space in the title (example below)
5. Observe the error, then dismiss the error
6. now attach a PNG file that has a space in the title
7. Observe the error again

## Expected Result: 
able to upload file attachments that contain a space in the file name 

## Actual Result: 
Unexpected error while posting the comment.

"Unexpected error while posting the comment, please try again later. Invalid file attachment"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `1.3.37-2`
**Reproducible in staging?:** y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2078320f-e372-4894-bfa8-53420e987f1a

https://github.com/Expensify/App/assets/43996225/444b206e-b9c8-4a5d-8539-2af3c9855ea1

https://github.com/Expensify/App/assets/16232057/7cfb740b-f444-4038-9f63-427e06ff0b74

[DATTARAM_SAWANT_AADHAR_CARD 1_.pdf](https://github.com/Expensify/App/files/11970293/DATTARAM_SAWANT_AADHAR_CARD.1_.pdf)

[Example With Space.pdf](https://github.com/Expensify/App/files/11970311/Example.With.Space.pdf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688495589932239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc241c0a0b2ba919</li>
        <li>Upwork Job ID: 1676993011268341760</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by marcochavezf** [comment] 2023-07-05 00:49
I can't reproduce the issue with the provided pdf on both staging and dev (latest main):

<img width="1104" alt="Screenshot 2023-07-04 at 18 48 24" src="https://github.com/Expensify/App/assets/6829422/e0b12bf7-7153-4b3e-a4e7-cab01c8a8ed1">

<img width="888" alt="Screenshot 2023-07-04 at 18 48 30" src="https://github.com/Expensify/App/assets/6829422/51eb532b-5fe0-4c9d-8406-f6206f93151a">

**Comment by trjExpensify** [comment] 2023-07-05 10:15
Me neither on staging mac chrome:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/3fce09d9-7a10-407a-8777-03497c9f8447">

Let's take this to the thread, I've noticed a couple of things from the video: 

1. It's windows not mac
2. the preview of the PDF is different than the one supplied 

I don't think this is a deploy blocker.

**Comment by Julesssss** [comment] 2023-07-05 13:26
Thanks both. I'm also unable to reproduce so I'm downgrading it from being an App release blocker. Also would be happy to just close it, based on the outcome of the thread discussions.

**Comment by trjExpensify** [comment] 2023-07-05 17:15
Cool, sounds good. I've asked the contributor to retry once and supply that PDF before I close it out.

**Comment by kavimuru** [comment] 2023-07-06 01:58
@trjExpensify This is happening to me inconsistently. One more contributor reproduced [here](https://expensify.slack.com/archives/C049HHMV9SM/p1688554855872859)

**Comment by dhanashree-sawant** [comment] 2023-07-06 03:28
@trjExpensify, @Julesssss, I was able to recreate it consistently if I used password protected PDF with space in name and sent the PDF in offline mode. I was able to reproduce on mac too using it. Maybe this info can help.

**Comment by trjExpensify** [comment] 2023-07-06 16:07
Requesting the file in slack to try and then include here!

**Comment by trjExpensify** [comment] 2023-07-06 16:20
Okay, that'll do it! Either online or offline I get the same results with a password protected PDF which includes a space in the title. 

<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/16232057/7b1390a1-0c03-4d76-80db-3e1b60a33018">

**Comment by trjExpensify** [comment] 2023-07-06 16:34
Okay, I can repro this with multiple file types that contain spaces in the name.

https://github.com/Expensify/App/assets/16232057/7cfb740b-f444-4038-9f63-427e06ff0b74

**Comment by multijump** [comment] 2023-07-06 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to Upload PDF & JPEG files that contains a space in the file title

### What is the root cause of that problem?
When upload file(with spaces in filename), these spaces in filename replaced with `_`.
And then upload to backend and backend return error `Invalid file attachment`.
This replacement was the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

We must leave these spaces in filename.
When file drop and upload, this error doesn't cause even though filename has some spaces because didn't replace spaces in that case.
But when `Add Attach` in `Action` for uploading file, replace the space to `_` in filename and backend returned error.
So we can fix this issue to leave the spaces in filename.

### What alternative solutions did you explore? (Optional)
May need to change in backend side.

**Comment by alitoshmatov** [comment] 2023-07-08 08:49
Originally posted here - https://github.com/Expensify/App/issues/22341

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Attachment upload is not working
### What is the root cause of that problem?
Cleaning up file name is not handled correctly, for example here, when creating a new instance of `File` we are not supplying options(third) argument here, which contains `type` and `lastModified` [fields](https://developer.mozilla.org/en-US/docs/Web/API/File/File)

https://github.com/Expensify/App/blob/6c30d95a267aa4eeb5fe3af16090acbcd2f9d1fc/src/components/AttachmentPicker/index.js#L40-L47

The resulting instance does not have type, thus backend is resulting in error. Below you can see before and after state of file, when mentioned action is applied.
<img width="609" alt="Screenshot 2023-07-06 at 2 31 09 PM" src="https://github.com/Expensify/App/assets/59907218/87e1adb1-0e1f-45eb-93d3-5f27d510d439">
This is issue is not present when dragging file because we are not performing this action there
### What changes do you think we should make in order to solve the problem?
We should provide file `type` and `lastModified`(optional) in the options field, [here](https://github.com/Expensify/App/blob/6c30d95a267aa4eeb5fe3af16090acbcd2f9d1fc/src/components/AttachmentPicker/index.js#L43):
```javascript
file = new File([file], cleanName, {type: file.type, lastModified: file.lastModified});
```
Also we should perform the same when attachment is dragged in, I think here:
https://github.com/Expensify/App/blob/15e547e3bceeb7bfe693f78fc8b90fdc28b1b32f/src/pages/home/report/ReportActionCompose.js#L1092-L1094
And here when file is copy pasted:
https://github.com/Expensify/App/blob/76a7fcebb94498a2a1e9bc1bb2ac256cb9fa6f3d/src/components/Composer/index.js#L300

Also we can do this action right before sending attachment to [backend] or (https://github.com/Expensify/App/blob/a88967f1a432dc347e0df408faf4ce407e84d2ff/src/libs/actions/Report.js#L336-L338) showing it in [modal](https://github.com/Expensify/App/blob/5b3be9ae1a7da4daf437b0bec6a1010cee7adfae/src/components/AttachmentModal.js#L206). I think this would be the best approach here and eliminates duplicate code
### What alternative solutions did you explore? (Optional)

**Comment by kashn11** [comment] 2023-07-08 16:58
Proposal
Please re-state the problem that we are trying to solve in this issue.
Attachment upload is not working when using file with special characters

What is the root cause of that problem?
The issue stems from AttachmentPicker function that get the file and clean it's name while it clean name and add create new file with new clean name the type of file isn't automatically inferred, which is why we're seeing that the file's type is being lost.

What changes do you think we should make in order to solve the problem?
To fix this issue we need to manually specify type of file in the third agrugment of File function
`if (file.name !== cleanName) { file = new File([file], cleanName,{type:file.type}); }`

What alternative solutions did you explore? (Optional)


**KYI**
It will also fix the issue on profile picture upload when try to upload svg and it show error
For reference here is the slack chat link
https://expensify.slack.com/archives/C049HHMV9SM/p1688813511739019

**Comment by nainwalsanju** [comment] 2023-07-08 19:26
### Proposal
---------------------------------------------------------------------------------------------------------------------------------------------
**Please re-state the problem that we are trying to solve in this issue.**
_Issue: Unable to Upload PDF & JPEG files that contain a space in the file title_

This issue is caused by the AttachmentPicker function, which cleans the file name but fails to preserve the file's type. As a result, files with spaces in their names are being uploaded with the incorrect Content-Type as octet-stream. 

To address this problem, I propose making the following changes in the code:

```javascript
if (file.name !== cleanName) {
  file = new File([file], cleanName, { type: file.type });
}
```

By explicitly specifying the file type in the third argument of the File function, we ensure that the correct type is maintained even after cleaning the file name.

I believe this change will resolve the issue and allow proper uploading of PDF and JPEG files with spaces in their titles.

**Suggestion**
1. Modify the code to explicitly block other file types:
```javascript
function isFileTypeAcceptable(file) {
  const acceptableTypes = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'application/csv',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'image/jpeg',
    'image/png',
    'image/gif',
    'text/plain',
    'text/html',
    'application/xml',
    'text/xml',
    'application/json',
    'application/zip',
    'audio/mpeg',
    'video/mp4',
    'application/javascript'
  ];

  return acceptableTypes.includes(file.type);
}


if (file && isFileTypeAcceptable(file)) {
  const cleanName = FileUtils.cleanFileName(file.name);
  if (file.name !== cleanName) {
    file = new File([file], cleanName, { type: file.type });
  }

  file.uri = URL.createObjectURL(file);
  onPicked.current(file);
}
```
Please let me know if you would like me to proceed with implementing the suggested changes.

**Comment by kmwamasali** [comment] 2023-07-10 07:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to Upload PDF & JPEG files that contains a space in the file title

### What is the root cause of that problem?
The root of the problem is in the `AttachmentPicker` which runs a file name check when the desired upload file is selected.
During this check, the original file name is compared against the _**cleaned**_  file name which fails since the spaces in the file name have been removed.  Therefore a new file is referenced/created since the names don't match.
https://github.com/Expensify/App/blob/9c70f342d311831f226adee6f797285341d75cfc/src/components/AttachmentPicker/index.js#L37-L44

### What changes do you think we should make in order to solve the problem?
We can skip the name check and let the up-loader read the file as is
`if (file.name !== cleanName && !file.name.includes(' ')) `

### Result

https://github.com/Expensify/App/assets/13502241/dd952e7c-b2c5-4df8-8eb6-57ffe93bd470

**Comment by pecanoro** [comment] 2023-07-10 20:20
This issue already had a CME before the automation kicked in, unassigning myself and leaving it to @marcochavezf

**Comment by marcochavezf** [comment] 2023-07-11 17:01
Thanks for the review @fedirjh, assigning @alitoshmatov 🚀

**Comment by alitoshmatov** [comment] 2023-07-11 19:08
PR ready - https://github.com/Expensify/App/pull/22672

**Comment by alitoshmatov** [comment] 2023-07-11 19:11
> 📣 @alitoshmatov 🎉 An offer has been automatically sent to your Upwork account for the Contributor role 🎉 Thanks for contributing to the Expensify app!

Looks like I didn't receive an offer in upwork, is there something I should do?

**Comment by daveSeife** [comment] 2023-07-11 20:24
> 📣 @daveSeife 🎉 An offer has been automatically sent to your Upwork account for the Reporter role 🎉 Thanks for contributing to the Expensify app!
> 
> [Upwork job](https://www.upwork.com/jobs/~01dc241c0a0b2ba919)

Accepted the offer, Thanks

**Comment by trjExpensify** [comment] 2023-07-17 17:57
We've still got the regression period to wait out, but @fedirjh can you confirm there was a regression from the PR that fixed this?

**Comment by trjExpensify** [comment] 2023-07-18 23:36
Cool, thanks! Let's get to the checklist when you're ready :)

**Comment by trjExpensify** [comment] 2023-07-24 12:32
Bump on the checklist, @fedirjh! 

In the meantime, confirming these are the payments due to send the offers:

- No #urgency bonus to consider due to the regression.
- $500 to @alitoshmatov for the fix, reduced by 50% because of the regression. 
- $500 to @fedirjh for C+, reduced by 50% because of the regression. 
- $250 to @daveSeife for the bug report

**Comment by trjExpensify** [comment] 2023-07-25 14:07
Cool, that works for me! 

Settled up with everyone, closing. Thanks!

**Closed by trjExpensify** 2023-07-25 14:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
