### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Name of the Expensify user is not centered in the profile detail view

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45346] opened 2024-07-12 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720777243552389

## Action Performed:
1. Open Expensify chat report
2. Click on the header to see the details
## Expected Result:
"Expensify" name should be centered like "Chronos"
## Actual Result:
The name for the Expensify user is not centered in the details view
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-12 at 11 40 50@2x](https://github.com/user-attachments/assets/8f8177e2-df88-4b46-b25b-c54f2e40f96a)
![CleanShot 2024-07-12 at 11 40 07@2x](https://github.com/user-attachments/assets/98596106-e870-4ab1-bfce-449b7a2bf33f)
![Snip - (56) New Expensify - Google Chrome](https://github.com/user-attachments/assets/ba9629bd-bfe6-440e-b71d-3a80a87ca082)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d58bde936bd4c0a6</li>
        <li>Upwork Job ID: 1812986703312855628</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103218448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by Tony-MK** [comment] 2024-07-12 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When the header of the report is clicked the app navigates to the report details page through the [`navigateToDetailsPage`](https://github.com/Expensify/App/blob/ec196638296045a64ced8baed6e4ba358c70f902/src/libs/ReportUtils.ts#L3539) function.

Instead of the profile page since the `CONST.ACCOUNT_ID.NOTIFICATIONS` account id is part of the `CONST.RESTRICTED_ACCOUNT_IDS` in the profile page.

https://github.com/Expensify/App/blob/ec196638296045a64ced8baed6e4ba358c70f902/src/pages/ProfilePage.tsx#L148

The report detail page does not align the title to the center while the profile page does.

https://github.com/Expensify/App/blob/ec196638296045a64ced8baed6e4ba358c70f902/src/pages/ReportDetailsPage.tsx#L573-L580

### What changes do you think we should make in order to solve the problem?


We should include the `styles.alignItemsCenter` for the `nameSectionGroupWorkspace` with the condition that the account id is the main participant to be displayed and is `CONST.ACCOUNT_ID.NOTIFICATIONS` or chat is a system chat, `isSystemChat`.

https://github.com/Expensify/App/blob/ec196638296045a64ced8baed6e4ba358c70f902/src/pages/ReportDetailsPage.tsx#L580

We could change the line of code above with the one below for the `isSystemChat` solution option.

```
 <View style={[styles.flex1, !shouldDisableRename && styles.mt3, isSystemChat && styles.alignItemsCenter]}>
```
### What alternative solutions did you explore? (Optional)

Create a different section like `nameSectionGroupWorkspace` and `nameSectionTitleField` to align the titles to the center for chats with the `CONST.ACCOUNT_ID.NOTIFICATIONS` account id, unlike other reports where it is aligned to the left.

![Centered Result](https://github.com/user-attachments/assets/705aa9ad-c18b-4433-b713-10aa39dfbcc9)

**Comment by nkdengineer** [comment] 2024-07-15 07:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
In `ReportDetailPage`, the report name is not aligned

https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/pages/ReportDetailsPage.tsx#L585-L591
### What changes do you think we should make in order to solve the problem?
This bug happens for all reports that are not DM and the report name can not be edited.
If the report name cannot be edited we should add `titleContainerStyle` prop with style `styles.alignItemsCenter` to `MenuItemWithTopDescription`. This change will also work when the report has the description.

```
titleContainerStyle={shouldDisableRename && styles.alignItemsCenter}
```

https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/pages/ReportDetailsPage.tsx#L585-L591

And add style `styles.mw100` here to avoid the title overflowing.
https://github.com/Expensify/App/blob/39463bdccefd9017b3f4beea889e57e58ad5644e/src/components/MenuItem.tsx#L656

### What alternative solutions did you explore? (Optional)
NA

https://github.com/user-attachments/assets/a2fde19f-61a0-4f01-aaf9-6484a278af8f


### Result

**Comment by nkdengineer** [comment] 2024-07-22 09:57
Just a note here. For the expense report, we will render it in another section. For other cases like thread, admin room, and public room, ... it displays the same as system chat and I think there is no reason that we do not centralize these report names if we center the system chat name.

<img width="1512" alt="Screenshot 2024-07-22 at 16 54 18" src="https://github.com/user-attachments/assets/92aa96af-3dd3-4ac4-8de5-f963546bd209">

**Comment by shawnborton** [comment] 2024-07-22 11:09
Yeah, just chiming in to say that if the room name is not editable, we should be centering it in all cases. CC @Expensify/design for the gut check there

**Comment by dannymcclain** [comment] 2024-07-22 14:34
Agree—that's what we had previously talked about and decided.

**Comment by strepanier03** [comment] 2024-08-02 15:59
### Payment Summary

- [ ]  $250 - @fedirjh via New Expensify manual request
- [x]  $250 - @nkdengineer via Upwork ([contract](https://www.upwork.com/nx/wm/workroom/37889364/overview?nav_dir=pop))

@JmillsExpensify payment request incoming.

**Comment by JmillsExpensify** [comment] 2024-08-02 18:57
$250 approved for @fedirjh. Going to close this once since regression issue is added and all payments approved. @fedirjh Please submit an expense in New Expensify when you get a chance!

**Closed by JmillsExpensify** 2024-08-02 18:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
