### ISSUE TITLE
Code blocks do not show as bold when the user uses three Backticks

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14100] opened 2023-01-06 23:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open any chat
2. start message with # and add space ,add a code block using three Backtick

## Expected Result:
 should show bold text

## Actual Result:
text are not bold (with single Backtick text shows as bold)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2. 50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211117180-d924e6e2-c47c-443a-a1ac-806c4dfebee3.mov

https://user-images.githubusercontent.com/43996225/211117191-05e46919-3ecc-413a-b144-e45c4f6f6166.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672998135151449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190debddc32639398</li>
        <li>Upwork Job ID: 1615046524662788096</li>
        <li>Last Price Increase: 2023-01-16</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-01-16 17:37
Oh yeah I can replicate this

**Comment by muttmuure** [comment] 2023-01-16 18:01
I think this is external, personally

**Comment by s77rt** [comment] 2023-01-16 21:24
I think this should internal.

Sending 
```
# ```test```
```

Is parsed and transmitted correctly as:
```
<h1><pre>test</pre></h1>
```

However when we get the pusher notification the transmitted message is malformed as:
```
<h1></h1><pre>test</pre>
```

**Comment by NikkiWines** [comment] 2023-01-19 01:42
Haven't had a chance to look into this yet but will check tomorrow to confirm @s77rt's comment

**Comment by NikkiWines** [comment] 2023-01-20 18:19
Yep, looks like we modify this in our internal `sanitizeAndValidateComment()` function [here](https://github.com/Expensify/Web-Expensify/blob/ef1c14938a8c239c91c6442af888029ad2ec3bc1/lib/ReportUtils.php#L1660-L1680) cc: @yuwenmemon as you last modified that logic 

![image](https://user-images.githubusercontent.com/16747822/213776648-2565f047-87d3-44ad-a822-dd6e6230150b.png)

**Comment by muttmuure** [comment] 2023-01-23 14:54
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2023-01-23 19:06
@muttmuure please remove Help Wanted Label!

**Comment by yuwenmemon** [comment] 2023-01-25 19:33
@francoisl is taking this over. Because he is a hero among men.

**Comment by francoisl** [comment] 2023-01-25 23:53
It looks like the root issue is that putting a `<pre>` block inside an `<h1>` block is not valid according to the HTML specs. 
You can test the following snippet on the [W3 validator](https://validator.w3.org/nu/#textarea):

```html
<h1>H1 text<pre>pre</pre> rest of H1</h1>
```
and it shows an error
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/2229301/214718209-4532dd48-1403-486f-99c3-83d4c0bdcf6e.png">

Our backend uses the HTMLPurifier lib, which cleans up the HTML input and reorganizes the tags to make them valid ([example](http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty.Predicate%5D=colgroup%3A%0D%0Ath%3A%0D%0Atd%3A%0D%0Aiframe%3Asrc%0D%0A&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BNull_HTML.Allowed%5D=1&filter%5BNull_HTML.Doctype%5D=1&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Ch1%3EH1+text%3Cpre%3Epre%3C%2Fpre%3E+rest+of+H1%3C%2Fh1%3E&submit=Submit)). I looked at the HTMLPurifier docs and I don't see a way to disable this behavior (and even if there was a way, I don't know if we'd want to disable that setting).

I think our options are:

- Not parse the triple backticks into a `<pre>` block if we're inside a header. This is what we already do with quotations (`>`). It would look like this:
    <img width="335" alt="image" src="https://user-images.githubusercontent.com/2229301/214719618-d060ecfa-2961-42f5-bc3c-4643fe3c45b9.png">

- Instead of converting `#` to an `<h1>` block, use a different HTML like `<span>` or `<div>`, which would be stylized to have bigger font.

**Comment by francoisl** [comment] 2023-02-11 01:03
Haven't had time to work on this recently, hoping to get back to it soonish.

**Comment by muttmuure** [comment] 2023-02-14 20:03
https://expensify.slack.com/archives/C01GTK53T8Q/p1676373597239839

I think we should close this and create a new issue different reproduction steps - the unexpected behaviour is that the bold appears then disappears from the code block. Codeblocks shouldn't be bolded

**Comment by muttmuure** [comment] 2023-02-15 16:58
Tagged @kavimuru here with next steps: https://expensify.slack.com/archives/C049HHMV9SM/p1676480283232819?thread_ts=1672998135.151449&cid=C049HHMV9SM

**Closed by muttmuure** 2023-02-15 16:58 UTC
Labels: Daily, Internal, Bug
