### ISSUE TITLE
[$250] Mention - @expensify.sms is copied along with phone number when copied to clipboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38187] opened 2024-03-12 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37559
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a text with phone number mention
4. Right click on the message > Copy to clipboard
5. Paste the content in the composer

## Expected Result:
@expensify.sms will not be copied along with phone number

## Actual Result:
@expensify.sms is copied along with phone number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1a12bd14-5e67-4dd5-81d9-f3c955c775d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5f15c665b86efd4</li>
        <li>Upwork Job ID: 1772750767801118720</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-12 21:45
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-12 21:46
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by nkdengineer** [comment] 2024-03-13 03:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Mention - @expensify.sms is copied along with phone number when copied to clipboard
### What is the root cause of that problem?
- We are using the bellow logic to get the copy text in case of this bug:
```
function getReportActionMessageText(reportAction: OnyxEntry<ReportAction> | EmptyObject): string {
    return reportAction?.message?.reduce((acc, curr) => `${acc}${curr.text}`, '') ?? '';
}
```
### What changes do you think we should make in order to solve the problem?
- We can use the same way that we use to display that action

### What alternative solutions did you explore? (Optional)
- NA

**Comment by greg-schroeder** [comment] 2024-03-25 11:20
Apologies, I was OOO last week. I'll take a look at this shortly

**Comment by greg-schroeder** [comment] 2024-03-26 22:21
Adding to #vip-vsb as this is chat-related, and I'm pretty sure this is very simple.

**Comment by Ozeias01Nunes** [comment] 2024-03-27 22:09
**My solution**

I will debug the process of copying text to the clipboard to see which text is being selected for copying.

If the unwanted text is in the selected data, I will remove it, leaving only the desired variable that corresponds to the phone number.

If this separation of variables for copying only the phone number is not possible, I will use regular expressions to select and later copy only the phone number.

**Comment by Ozeias01Nunes** [comment] 2024-03-27 22:12
Contributor details
Your Expensify account email: ozeias01nunes@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0131a29d57cf560448

**Comment by Ozeias01Nunes** [comment] 2024-03-27 22:13
**My solution**

I will debug the process of copying text to the clipboard to see which text is being selected for copying.

If the unwanted text is in the selected data, I will remove it, leaving only the desired variable that corresponds to the phone number.

If this separation of variables for copying only the phone number is not possible, I will use regular expressions to select and later copy only the phone number.

**Comment by Ozeias01Nunes** [comment] 2024-03-28 05:22
**Solution**

I created a check for the type of action and whether the text of the selected message ends with the SMS domain. If this happens, I replace the domain with an empty string.

**Screen recording demonstrating expected operation.**
[Screencast from 2024-03-28 02-09-14.webm](https://github.com/Expensify/App/assets/20213409/47ecc39d-a3f1-46d5-ba2d-7a3c58f86a57)


**Screenshot of solution code.**
![2024-03-28_02-10](https://github.com/Expensify/App/assets/20213409/4b4c3cab-b6cc-4eaa-ab26-81f439327fb7)

**Comment by Ozeias01Nunes** [comment] 2024-03-28 05:55
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
@expensify.sms is copied along with phone number when copied to clipboard

### What is the root cause of that problem?
We set the html message received without checking if it is the @expensfiy.sms domain

### What changes do you think we should make in order to solve the problem?
I created a check for the type of action and whether the text of the selected message ends with the SMS domain. If this happens, I replace the domain with an empty string.

**Screen recording demonstrating expected operation.**

https://github.com/Expensify/App/assets/20213409/df238560-a061-4c8c-8bb1-62203da3e611

**Screenshot of solution code.**
![2024-03-28_02-10](https://github.com/Expensify/App/assets/20213409/75e87c9f-a1cc-47a1-91a0-d916b10656e1)

**Code**
`} else if (reportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && messageText && messageText.endsWith(CONST.SMS.DOMAIN)) {
                    setClipboardMessage(messageText.replace(CONST.SMS.DOMAIN, ''));
                } `

**Comment by alitoshmatov** [comment] 2024-04-01 20:08
@nkdengineer Thank you for your proposal, It seems like you overcomplicated your approach, can't we just get text inside `mention-user` tag and remove sms domain addition with `Str.removeSmsDomain`?

**Comment by alitoshmatov** [comment] 2024-04-01 20:11
@Ozeias01Nunes Thank you for your proposal, I think you are not approaching this problem right, for example your solution is only works when user number is only text in comment

**Comment by alitoshmatov** [comment] 2024-04-01 20:38
@GandalfGwaihir I see, but still it is not valid solution as state:

- Also it has a drawback which is that it is removing sms domain from whole text, for example if user just enters @expensify.sms it will disappear

**Comment by nkdengineer** [comment] 2024-04-02 00:43
@GandalfGwaihir Your main proposal and my alternative solution is different. Your proposal will use removeSmsDomain in here:
https://github.com/Expensify/App/blob/91d7eb22b3cf0e690271a1313bf8016d03cb3ef7/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L345

My proposal will use removeSmsDomain in here:
https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L346

**Comment by nkdengineer** [comment] 2024-04-02 00:53
@alitoshmatov I updated my proposal based on [comment](https://github.com/Expensify/App/issues/38187#issuecomment-2030472999)

**Comment by Ozeias01Nunes** [comment] 2024-04-02 16:25
@alitoshmatov I updated my proposal based on [comment](https://github.com/Expensify/App/issues/38187#issuecomment-2024458705).

**Comment by alitoshmatov** [comment] 2024-04-02 18:28
@nkdengineer 's [proposal](https://github.com/Expensify/App/issues/38187#issuecomment-1993276218) looks good which suggests to remove sms domain from texts inside user mention tags

C+ reviewed 🎀 👀 🎀

**Comment by greg-schroeder** [comment] 2024-04-05 21:34
Bump @youssef-lr to confirm contributor selection: https://github.com/Expensify/App/issues/38187#issuecomment-2032772742

**Comment by greg-schroeder** [comment] 2024-04-08 22:00
Friendly bump @youssef-lr

**Comment by greg-schroeder** [comment] 2024-04-15 02:45
Linked PR in review, just awaiting @youssef-lr's review next!

**Comment by youssef-lr** [comment] 2024-04-15 14:49
Merged!

**Comment by alitoshmatov** [comment] 2024-05-01 05:17
The pr went into production on 22nd of April, so payment is long overdue

**Comment by greg-schroeder** [comment] 2024-05-09 05:16
Hmm. I'm not sure why the automation keeps failing, but I'll process this now.

**Comment by nkdengineer** [comment] 2024-05-09 17:30
@greg-schroeder Thank you 🙇 I've applied to the job

**Comment by greg-schroeder** [comment] 2024-05-09 22:38
Thanks! Will pay you now. 👍

**Closed by greg-schroeder** 2024-05-09 22:38 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by nkdengineer** [comment] 2024-05-10 18:59
@greg-schroeder I accepted the offer!

**Comment by greg-schroeder** [comment] 2024-05-10 20:45
Okay, paid!
