### ISSUE TITLE
[HOLD] Web - Inconsistent avatar on mention list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22409] opened 2023-07-07 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed in
2. Open an existing chat with account B
3. Copy account B's email address
4. Write '@' in composer followed by account B's email address
5. Observe user B's avatar on mention list
6. Copy account A's email address
7. Write '@' in composer followed by account A's email address

## Expected Result:
Avatar on the mention list should be consistent with user's avatar

## Actual Result:
Avatar on mention list is not consistent with user's avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9daaa5fd-ffbb-4bc2-9874-e1b6eb8ad550

https://github.com/Expensify/App/assets/93399543/354a8c40-5f04-4a06-88b5-490a052533f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688672489195859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Natnael-Guchima** [comment] 2023-07-07 14:21
@s-alves10 seems to be different issue. On the issue you have linked the avatar is not being displayed at all, and this one the avatar is displayed but it is not consistent with the profile avatar. And stpes of reproduction seems to look different too.

**Comment by sophiepintoraetz** [comment] 2023-07-11 12:44
Hopefully getting this today!

**Comment by s-alves10** [comment] 2023-07-11 12:46
> @s-alves10 seems to be different issue. On the issue you have linked the avatar is not being displayed at all, and this one the avatar is displayed but it is not consistent with the profile avatar. And stpes of reproduction seems to look different too.

I think the root causes are the same and this will be solved once https://github.com/Expensify/App/issues/22194 is solved

**Comment by sophiepintoraetz** [comment] 2023-07-12 12:40
I actually agree with @s-alves10 - there is possible overlap based on Alex's comment [here](https://github.com/Expensify/App/issues/22194#issuecomment-1623290937). I've [clarified](https://github.com/Expensify/App/issues/22194#issuecomment-1632456926) so we'll see! And @Natnael-Guchima even if the steps are different, the end result is the same so it's worth checking.

**Comment by Natnael-Guchima** [comment] 2023-07-12 12:43
I agree @sophiepintoraetz. We can hold or close this issue and see if the other GH can fix the problem.

**Comment by sophiepintoraetz** [comment] 2023-07-13 16:31
Putting this on hold.

**Comment by sophiepintoraetz** [comment] 2023-07-24 06:25
@Natnael-Guchima - can you confirm whether you are still running into an issue here now that the holding issue's PR has merged?

**Comment by Natnael-Guchima** [comment] 2023-07-24 06:46
@sophiepintoraetz Yes, I am still running into the issue. But I think we might need someone to confirm if displaying a different avatar on mention list is not an expected behavior. 
[Screencast from 2023-07-24 09-42-31.webm](https://github.com/Expensify/App/assets/57330233/b27a0906-4c05-4f60-83a7-77011cf7826f)

**Comment by sophiepintoraetz** [comment] 2023-08-02 01:31
Hmm - will look into this when I have some time.

**Comment by sophiepintoraetz** [comment] 2023-08-11 08:33
Yikes, still have not had time!

**Comment by sophiepintoraetz** [comment] 2023-08-29 03:27
I'm not able to reproduce this
<img width="676" alt="image" src="https://github.com/Expensify/App/assets/42940078/9162f8ee-2a88-4357-8e50-5bc2e0870f1d">

**Closed by sophiepintoraetz** 2023-08-29 03:27 UTC
Labels: Weekly, Needs Reproduction, Overdue, Bug
