### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] Android/iOS - Chat and the FAB menu options open on the chat page when tapping both in quick succession.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11229] opened 2022-09-23 00:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App and login
2. From the LHN home screen, tap on any chat row and quickly tap on the green `+` icon (FAB)

## Expected Result:
Only the chat should open as it was the first tap.

## Actual Result:
Chat and FAB menu open at the same time

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android
- iOS 

**Version Number:** v1.2.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:**Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

Android: 
<img src="https://user-images.githubusercontent.com/43996225/191874266-96b0676c-faa0-483d-a69f-92edc5c05a53.png" width="40%" height="40%">
https://user-images.githubusercontent.com/43996225/191874271-d3bcc36c-d4d0-4898-8a4c-61a254d43849.mp4

iOS: 
![IMG_8500](https://user-images.githubusercontent.com/16232057/191973944-b66956fd-19b4-4759-a756-4091560151da.PNG)

**Upwork URL:** https://www.upwork.com/jobs/~0159458d877f5bc785
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2022-09-23 09:51
Looks like a good External issue, maybe we can prevent opening the FAB / prevent having it clickable if the route includes a report ID? Just an idea

**Comment by trjExpensify** [comment] 2022-09-23 13:45
>1. Launch App and login as HT account

What does HT stand for and will a contributor who gets this issue understand that abbreviation and be able to log-in to a "HT account"? 

>Only the FAB should be open as last tap or only Chat page should open

The expected results are ambiguous. It would need to be either of these things, and we should provide guidance on which one we want it to be. IMO, the last tap should be the action we take. So the chat page wouldn't open, only the global create menu would. @Beamanator, what are your thoughts there? I kinda' think this issue goes away as the app becomes more performant when navigating. As in, you won't have time to move your thumb and click the FAB. 

>Where is this issue occurring?
>
>Android

Did we try reproducing on iOS? I can actually reproduce it there, so going to update the OP: 

![IMG_8500](https://user-images.githubusercontent.com/16232057/191972129-4556d6ca-cb31-473b-8d56-28005f4cef88.PNG)

>Looks like a good External issue, maybe we can prevent opening the FAB / prevent having it clickable if the route includes a report ID?

@Beamanator but on web/desktop it's expected that you can open the global create menu while currently on a chat report, will that proposal not cause problems on those platforms?

**Comment by Beamanator** [comment] 2022-09-23 14:45
Sooo good point, HT is "High Traffic" which I think is a bit difficult to test as a contributor, but actually I'm even reproducing **easily** on Android w/ a non-HT account, so I'll remove that from the OP & title

> IMO, the last tap should be the action we take. So the chat page wouldn't open, only the global create menu would. @Beamanator, what are your thoughts there?

Interesting, I was thinking the first action we take 🤔  Should we bring this to Slack for a wider discussion?

> I kinda' think this issue goes away as the app becomes more performant when navigating. As in, you won't have time to move your thumb and click the FAB.

That's possible, but it would be pretty easy to tap a report & touch the FAB in VERY quick succession, so I still think it would be good to address this for now & later

And thanks for reproducing on iOS! It's fine to have proposals that will be for only 2 platforms, as long as we make sure there's no regressions on web / desktop :D

**Comment by jeet-dhandha** [comment] 2022-09-26 00:53
### Proposal 
1. For this we can simply navigate user back to `HOME` screen if he accidentally presses on the FAB menu.

### Code:

<img width="1023" alt="Screenshot 2022-09-26 at 6 22 15 AM" src="https://user-images.githubusercontent.com/78416198/192174212-c179d8c5-b362-4227-b311-0583dc42e62b.png">

### Fixed Video:

https://user-images.githubusercontent.com/78416198/192174264-62510594-a28d-4699-8cd8-29038fffa2c4.mov

**Comment by Beamanator** [comment] 2022-09-26 10:59
Awaiting proposal review, not overdue

**Comment by trjExpensify** [comment] 2022-09-26 11:12
Job on Upwork here: https://www.upwork.com/jobs/~019fb94172f17c76bc

**Comment by chauchausoup** [comment] 2022-09-28 16:14
I just found that the issue is replicating in few other places too.
- search box + LHN
- settings avatar + LHN

**Comment by trjExpensify** [comment] 2022-09-29 11:13
I'm not sure I understand fully, @chauchausoup. Can you post us some screenshots/vids? 🤔

**Comment by trjExpensify** [comment] 2022-09-29 11:13
In the meantime, @parasharrajat @Beamanator are we waiting on something for feedback on this current proposal? https://github.com/Expensify/App/issues/11229#issuecomment-1257333888

**Comment by trjExpensify** [comment] 2022-09-29 14:47
Ah, yeah. The OP didn't get updated.

**Comment by jeet-dhandha** [comment] 2022-09-30 09:11
> I do not get the expected result. What should be done to fix this? @trjExpensify
> 
> > Only the FAB should be open as the last tap or only the Chat page should open
> 
> Both statements are contradicting each other. IMO, the first trigger action should take priority which is the chat opening action in our case. (try any native app and try to click two actions simultaneously, the one that is clicked first takes priority).
> 
> But the proposal [#11229 (comment)](https://github.com/Expensify/App/issues/11229#issuecomment-1257333888) is not matching any of them.

@parasharrajat To give you simple explanation try calling two function one after each other and both should get executed.

```
// Like below. Both Action will execute and chate screen plus fab menu should get opened.
navigateToChate();
openFABMenu();
```

**Comment by jeet-dhandha** [comment] 2022-09-30 09:21
If you are still not able to understand the please do ping here. 👍

**Comment by jeet-dhandha** [comment] 2022-09-30 10:29
### Update Proposal :
Used a More optimised Approch.
CODE PR : https://github.com/jeet-dhandha/Expensify-App/pull/2/files.

### Explanation:
**Case 1 :** 
- Detail : Pressed on a report from list and within few milliseconds pressed on FAB menu. (Both are FAB menu and Report Message Screen is opened).
- Solution : I have set a value `blockFABPress: true` in state which updates to `false` after timeout of `300` by which the screen would have navigated succesfully. And the `blockFABPress` disables FAB press action.

**Case 2 :** 
- Detail : Pressed on FAB menu and within few milliseconds pressed on a report from list. (Both are FAB menu and Report Message Screen is opened).
- Solution : I have passed a prop `blockedReportPress` in `SidebarLinks` and value is `this.state.isCreateMenuActive`, as isCreateMenuActive is true when FAB menu is opened up. So the `blockedReportPress` disables Report Press action.

Fixed Video:

https://user-images.githubusercontent.com/78416198/193250897-147f5f00-4e99-46fa-bd78-305edea28906.mov

**Comment by jeet-dhandha** [comment] 2022-10-04 18:34
@trjExpensify Does my above proposal looks good ?

**Comment by parasharrajat** [comment] 2022-10-04 18:41
I will review it by tommorrow.

**Comment by trjExpensify** [comment] 2022-10-04 19:20
From a UI standpoint, the video looks good to me!

**Comment by parasharrajat** [comment] 2022-10-06 16:26
Reviewing in 20 minutes

**Comment by Beamanator** [comment] 2022-10-07 09:08
Hmm good points all around. Honestly I don't think this is a big problem for the user either way - if they click on a chat row & FAB at nearly the same time, they can't expect one to work and not the other, right? They obviously accidentally clicked one and will be ok fixing their click (assuming it doesn't go where they wanted)

In this case I call upon the @Expensify/design team for ideas!

**Comment by trjExpensify** [comment] 2022-10-07 13:04
In normal use with a speedy app, I think it will be incredibly unlikely that you can quickly tap both of these with the same thumb before the first action is registered. 

Nevertheless, I've been testing using two thumbs to quickly tap multiple pieces of UI on a few native apps (i.e WhatsApp, Twitter etc) and they all ignore the final action. I think we're right to stick with this: 

>The first action should take priority

**Comment by michelle-thompson** [comment] 2022-10-07 16:56
Yeah, I agree with the first action taking priority.

**Comment by trjExpensify** [comment] 2022-10-12 17:23
Okay so given we're aligned there, how are we feeling about @jeet-dhandha's proposal?

**Comment by parasharrajat** [comment] 2022-10-13 16:10
@trjExpensify Last update was https://github.com/Expensify/App/issues/11229#issuecomment-1270688154.

**Comment by trjExpensify** [comment] 2022-10-13 16:36
Got it, meaning, despite the clarifications on the intended behaviour we're still not sure on that approach to fixing it.

If we like the approach @aimane-chnaif has put forward, we should close the other issue and fix it as one.

**Comment by Beamanator** [comment] 2022-10-17 11:39
@parasharrajat can you please give an update for this when you have a chance today?

**Comment by parasharrajat** [comment] 2022-10-17 20:41
The proposal makes sense to me. But I am curious about point 2 `conditional showCreateMenu() call`. 

How the `isFocused` or `isDrawerOpen` flag is changed before the screen is really open. :thinking: ?

**Comment by parasharrajat** [comment] 2022-10-17 21:44
It seems like when we first click on the FAB and then on the chat row. the FAB menu is not closed automatically unless the chat is fully loaded. it works completely fine for the reverse scenario.


https://user-images.githubusercontent.com/24370807/196289416-1db14f83-766a-49b9-ba03-5ea10168edba.mp4

**Comment by trjExpensify** [comment] 2022-10-20 19:36
@aimane-chnaif can you come back to Rajat on this? https://github.com/Expensify/App/issues/11229#issuecomment-1281470155

**Comment by Beamanator** [comment] 2022-10-24 09:06
@parasharrajat will review updated proposal soon 👍

**Comment by parasharrajat** [comment] 2022-10-26 16:29
Thanks for the updated proposal. Working on other priorities. Expect a delayed response.

**Comment by Beamanator** [comment] 2022-10-31 15:03
A bit overdue, @parasharrajat do you want to assign another C+ to review this?

**Comment by parasharrajat** [comment] 2022-10-31 15:12
I thought, I already did. Forgot to leave a comment on Saturday. Will re-review it in 2 hours.

**Comment by Beamanator** [comment] 2022-10-31 15:16
Aah ok no worries, thanks 👍

**Comment by parasharrajat** [comment] 2022-10-31 22:19
> opening other pages from shortcut key after FAB menu is open (web, desktop)
Result: FAB menu keeps open. don't open any other pages

@aimane-chnaif This is not intended. I am sure the user would prefer the shortcut to work even if FAB is opened. In that case, FAB should be closed. But I think there is some issue for it https://github.com/Expensify/App/issues/10009.

**Comment by parasharrajat** [comment] 2022-11-01 10:19
Ok, Thanks for clarifying.

**Comment by parasharrajat** [comment] 2022-11-01 11:36
@aimane-chnaif  It seems a lot has changed since your proposal. Can you please update your proposal according to the latest code on the main?

**Comment by trjExpensify** [comment] 2022-11-03 22:13
How we looking here, ready to move to a PR?

**Comment by Beamanator** [comment] 2022-11-07 08:35
@parasharrajat can you give an update on proposal reviews?

**Comment by parasharrajat** [comment] 2022-11-07 15:20
Looking into the diff and share the update asap.

**Comment by trjExpensify** [comment] 2022-11-07 16:05
Thanks!

**Comment by parasharrajat** [comment] 2022-11-07 19:41
Reviewed and discussing something one-to-one.

**Comment by Beamanator** [comment] 2022-11-10 14:05
Discussed a few things 1:1, I think we're ready to move forward reviewing proposals right @parasharrajat ?

**Comment by parasharrajat** [comment] 2022-11-10 14:21
Yeah, give me like 2 hours. Not started working yet.

**Comment by parasharrajat** [comment] 2022-11-10 18:36
Ok, we decided to move with this solution for now. There are a few things that should be improved in the proposal. 

1. Move `componentDidUpdate` conditions into a function and break the condition into smaller ones and comment about each check over them. 
2. Rest there are some naming concerns but we will tackle those in PR. 

@aimane-chnaif [proposal 1](https://github.com/Expensify/App/issues/11229#issuecomment-1277318160) + [proposal 2 ](https://github.com/Expensify/App/issues/11229#issuecomment-1286861407) looks good. 

cc: @Beamanator 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by trjExpensify** [comment] 2022-11-10 18:55
Cool, so the "we" in this I presume means it's approved by @Beamanator as well at this point yeah? Let me know, and I'll get going on the job offer.

**Comment by Beamanator** [comment] 2022-11-10 19:03
Agree with @parasharrajat 👍  And yes, your spidey-senses were correct @trjExpensify 😉

**Comment by trjExpensify** [comment] 2022-11-10 19:11
Cool, so the job is [here](https://www.upwork.com/jobs/~01b928d306b8cb15bd) and I've sent you the offer @aimane-chnaif, and @parasharrajat for C+. 

Look forward to the PR! 🚀

**Comment by trjExpensify** [comment] 2022-11-14 11:51
Morning, Melv. PR is up, awaiting a review from @parasharrajat! 🎉

**Comment by trjExpensify** [comment] 2022-11-21 14:07
Hit staging, awaiting a prod deploy to start the timer.

**Comment by trjExpensify** [comment] 2022-11-21 14:26
Yep, we'll combine the payment for the two. [Here's the job](https://www.upwork.com/jobs/~0159458d877f5bc785) to accept the offer on (@parasharrajat as well). 

I'm going to close the other issue out.

**Comment by mvtglobally** [comment] 2022-11-22 20:48
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-11-29 11:47
Settled up [these contracts](https://github.com/Expensify/App/issues/11229#issuecomment-1322209914), so we're all square here. 🎉 

>we probably should add some regression test for this though

I don't think it's worth adding one for an edge case that in practice is incredibly hard to reproduce. Unless the app is very, very slow, you don't get the chance to tap both a chat row and the FAB in quick succession unless you force it using two thumbs or something.

Going to close this out, but let me know if you disagree.

**Closed by trjExpensify** 2022-11-29 11:47 UTC
Labels: Reviewing, External, Engineering, Daily, Design, Awaiting Payment, Bug

**Comment by parasharrajat** [comment] 2022-11-29 14:53
@trjExpensify Based on https://github.com/Expensify/App/issues/11229#issuecomment-1322209914, I should be eligible for the bonus as well.

**Comment by trjExpensify** [comment] 2022-11-29 15:45
You were hired and paid on both of those linked jobs above, no?

**Comment by parasharrajat** [comment] 2022-11-29 15:47
Yeah, found it. Thanks.
