### ISSUE TITLE
LHN - Chat with draft message and pending request doesn't jump to the top of the LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13063] opened 2022-11-26 23:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12761

## Action Performed:
Preconditions: Some chats with pending money requests are present in the LHN for User
1. Open the app and sign in
2. Pin a chat that's not at the top of your LHN to the top. It should appear there and stay there upon refresh/log out log back in.
3. Verify that it appears at the top of the LHN
4. Start writing a draft comment in a different chat with the pending money request
5. Verify that the chat jumps to the top of the LHN (but below the pinned chat)

## Expected Result:
Chat jumps to the top of the LHN (but below the pinned chat)

## Actual Result:
Chat with draft message and pending request doesn't jump to the top of the LHN

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.32.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204112601-72122018-910c-4af4-9e91-ebaf35e8d5d1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01aaf83e461b602c57
- Upwork Job ID: 1597558699941490688

**Comment by isabelastisser** [comment] 2022-11-29 11:51
Not overdue.

**Comment by bernhardoj** [comment] 2022-11-29 13:58
### **Proposal**
Agree with @allroundexperts. But I was thinking that maybe we want to put the draft report at the top between the others outstanding IOU. In that case, we need to do further sort to the outstanding IOU reports as below.

```diff
-outstandingIOUReports = _.sortBy(outstandingIOUReports, 'iouReportAmount').reverse();
+outstandingIOUReports = _(outstandingIOUReports).chain().sortBy('iouReportAmount').sortBy('hasDraft').reverse().value();
```

**Result**

**Comment by marcaaron** [comment] 2022-11-29 18:21
Confused about this one. Is it the expected behavior? Having a chat row "jump" while you are typing seems a bit distracting. Not entirely sure we need to fix this and curious if we can just "Do Nothing" here.

**Comment by bernhardoj** [comment] 2022-11-30 01:06
Currently, when we type a message on a normal report (not with an outstanding IOU), it will also jumps to the top.

**Comment by isabelastisser** [comment] 2022-12-02 10:24
Not overdue.

**Comment by isabelastisser** [comment] 2022-12-02 10:25
@mananjadhav , can you please review the proposals above? Thanks!

**Comment by mananjadhav** [comment] 2022-12-02 10:34
Thanks for the ping @isabelastisser. I went through the proposals. But I am not sure of the expected outcome here.

@marcaaron We pushed the draft messages to the top. Do we know if we have a priority of the order, such that drafts on the top, then outstanding IOU chats and then others? or we could have draft messages in between the outstanding IOU chats?

**Comment by Beamanator** [comment] 2022-12-02 11:43
It looks like the current sorting logic we have is outlined here: https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.js/#L109-L118

> // The LHN is split into five distinct groups, and each group is sorted a little differently. The groups will ALWAYS be in this order:
// 1. Pinned - Always sorted by reportDisplayName
// 2. Outstanding IOUs - Always sorted by iouReportAmount with the largest amounts at the top of the group
// 3. Drafts - Always sorted by reportDisplayName
// 4. Non-archived reports
//      - Sorted by lastActionCreated in default (most recent) view mode
//      - Sorted by reportDisplayName in GSD (focus) view mode
// 5. Archived reports
//      - Sorted by lastActionCreated in default (most recent) view mode
//      - Sorted by reportDisplayName in GSD (focus) view mode

In the OP you can see that the second point explains how IOUs are sorted - `largest amounts at the top of the group`. So I think this is not an issue.

@kbecciv did you report this bug due to some TestRail steps that mentioned a different order of chats is desired?

**Comment by Beamanator** [comment] 2022-12-02 11:44
(removed `Help Wanted` label & unassigned C+ since we don't need to fix anything here - will keep it open just to see if we need to update our test cases)

**Comment by isabelastisser** [comment] 2022-12-02 13:25
@Beamanator Can I add the _Internal_ label and switch the frequency to _Weekly_?

**Comment by Beamanator** [comment] 2022-12-02 15:23
yes and yes sounds good!

**Comment by Beamanator** [comment] 2022-12-06 08:35
Aah now I see the linked PR, thanks for pointing that out 🙏 

It looks like the test steps in the PR (https://github.com/Expensify/App/pull/12761) didn't take into account that chats w/ drafts SHOULD NOT jump up above chats w/out drafts **IFF** the chat w/out drafts has an IOU that's higher

@kbecciv do we have any TestRail steps involving chat sort order right now? If so, can you please link them here? If not, I'll write some new test cases :D

**Comment by isabelastisser** [comment] 2022-12-14 20:09
Not overdue.

**Comment by Beamanator** [comment] 2022-12-15 11:44
Thanks @kbecciv ! 

Ok I also found this test case: [LHN - Draft message in conversation (Online / Offline)](https://expensify.testrail.io/index.php?/tests/view/2977678&group_by=cases:section_id&group_order=asc&group_id=229062) which has these notes at the top:

> Note: Order of LHN by priority is Pinned, IOU and draft messages last

So Maybe we can add that note to the top of [LHN - Pinned / Unpinned conversations](https://expensify.testrail.io/index.php?/tests/view/2977674&group_by=cases:section_id&group_order=asc&group_id=229062) as well?

I'll go ahead and make this change, then close this one out

**Comment by Beamanator** [comment] 2022-12-15 11:45
Added, so now we have this:

<img width="661" alt="Screen Shot 2022-12-15 at 1 45 01 PM" src="https://user-images.githubusercontent.com/3885503/207851154-5783b3d2-fc60-4eb2-9175-3b14e919c99c.png">

**Closed by Beamanator** 2022-12-15 11:45 UTC
Labels: Weekly, Internal, Bug
