### ISSUE TITLE
[PAID] mWeb - Top bar color is different

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28263] opened 2023-09-26 13:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon
2. Check the top bar color

## Expected Result:
Top bar color should not be different

## Actual Result:
Top bar color is different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![IMG_6641 (1)](https://github.com/Expensify/App/assets/93399543/ae613823-ca19-4b33-a540-4c4a31e6a514)
![D2EFCF1F-3ACE-4BB6-B6EE-86761C50416F](https://github.com/Expensify/App/assets/93399543/e73e1251-f0a0-4497-8e09-535a2ea12dac)

https://github.com/Expensify/App/assets/93399543/145b0993-34b5-469f-9818-41b6101a0d12

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695724265178069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-09-26 13:50
This is a regression of [this PR](https://github.com/Expensify/App/pull/27920)

**Comment by ishpaul777** [comment] 2023-09-26 14:19
## Proposal 
### Problem

mWeb - Top bar color is different

### Root Cause
I dont this is a regression, the color changing was intentionally changed to sidebar color which is `darkHighlightBackground` Changing the color of the overlay across the App was in the scope of PR. We have been guided to not to touch `darkHighlightBackground` -[here](https://github.com/Expensify/App/issues/27353#issuecomment-1728645416)

### Changes 
We can replace the color [here](url) to the overlay color instead of sidebar

**Comment by situchan** [comment] 2023-09-26 15:00
This should have been covered in https://github.com/Expensify/App/pull/27920.
Was there any discussion about status bar color mismatch?

**Comment by ishpaul777** [comment] 2023-09-26 16:15
No, there was no discussion.

**Comment by jasperhuangg** [comment] 2023-09-27 00:20
Normally for these types of regressions we let the contributor who introduced the regression fix it. I commented on the PR raising the issue.

No need to block deploy on this, since it's such a minor display bug.

**Comment by s77rt** [comment] 2023-09-27 00:36
@ishpaul777 We need to fix this app wide and not limited to the sidebar. e.g. if you got to a chat and press the plus grey button a modal will appear and the status bar color won't much. Can you please update your proposal addressing this?

**Comment by ishpaul777** [comment] 2023-09-27 07:46
@s77rt The changes suggested will also changes the statusbar color app wide to overlay color. (#1A3D32)

<img width="612" alt="Screenshot 2023-09-27 at 1 15 54 PM" src="https://github.com/Expensify/App/assets/104348397/4b6a97b5-538b-4f79-b367-71e8e973c367">

**Comment by s77rt** [comment] 2023-09-27 20:36
@ishpaul777 Please raise a PR and have the opacity applied to match the overlay color

**Comment by dangrous** [comment] 2023-09-28 07:06
Just wanted to ping @Expensify/design here just to double check - but the status bar should match the overlay color and opacity, right?

**Comment by ishpaul777** [comment] 2023-09-28 12:20
@s77rt We can't set the opacity for theme color directly, even if we hardcode the opacity to `0.72` the browser completely ignores the opacity that why we have `getThemeBackgroundColor` utility to have `rgb` color value thats close to the overlay background color.

**Comment by s77rt** [comment] 2023-09-28 15:26
@ishpaul777 In that case I don't see a reason to modify the `<Modal />`. We can just adjust the value in `getThemeBackgroundColor`

https://github.com/Expensify/App/blob/bfda42deb3180835877c8b650188a5acf8c4dbc9/src/styles/StyleUtils.ts#L684

and remove the `themeColors.modalBackdrop` variable.

**Comment by ishpaul777** [comment] 2023-09-28 16:23
Yep we can do that, raising a PR in few minutes.

**Comment by jasperhuangg** [comment] 2023-10-12 18:37
Assigning `Bug` to handle payment cc @strepanier03

**Comment by strepanier03** [comment] 2023-10-12 23:11
Thanks, @jasperhuangg - I'll work on this now since it's two days past the payment date. I'll have an update soon.

**Comment by strepanier03** [comment] 2023-10-12 23:15
@jasperhuangg - Quick question here. I see that the PR was submitted by @ishpaul777 but they aren't listed as the contributor [here](https://github.com/Expensify/App/issues/28263#issuecomment-1745234266), not are they assigned to this GH. 

I don't want to shortchange them and not pay when we should. Do you have any context into why they aren't listed as needing payment? Was there some special circumstances here that I'm missing?

**Comment by s77rt** [comment] 2023-10-13 02:20
@strepanier03 No payment is due here except for the bug reporter

**Comment by stitesExpensify** [comment] 2023-10-16 18:17
@strepanier03 can we get this paid out so that we can close the issue please? 😄

**Comment by strepanier03** [comment] 2023-10-16 18:58
Sure thing @stitesExpensify - I had a question about payment that's resolved now, and it's my Monday so I'm only just getting back online from the weekend.

**Comment by strepanier03** [comment] 2023-10-16 19:02
@gadhiyamanan - I've hired you to the job, please accept as soon as you can and I'll keep an eye out for it so I can pay.

**Comment by gadhiyamanan** [comment] 2023-10-16 19:03
@strepanier03 offer accepted, thanks!

**Comment by strepanier03** [comment] 2023-10-17 00:18
Thank you @gadhiyamanan - I've paid you via Upwork and closed the contract. Closing this now.

**Closed by strepanier03** 2023-10-17 00:18 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
