### ISSUE TITLE
[HOLD #31594][$500] mWeb/Safari - The conversation list gets hidden after adding an emoji

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32217] opened 2023-11-29 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new user conversation
3. send couple messages
4. Select one and select edit option
5. Add emoji to the message and save it

## Expected Result:
The conversation list should be visible after adding an emoji reaction

## Actual Result:
The conversation list gets hidden after adding an emoji reaction

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/84311c34-e0c2-4607-93b3-f276df37fd83

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174b86e813d8a3d26</li>
        <li>Upwork Job ID: 1729937120215465984</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 20:45
@lanitochka17 

I'm a little confused)
Does the video really correspond to the bug?

**Comment by lanitochka17** [comment] 2023-11-29 20:50
@sorry. Hello 
I added a new video 

https://github.com/Expensify/App/assets/78819774/84311c34-e0c2-4607-93b3-f276df37fd83

**Comment by barros001** [comment] 2023-11-30 02:54
I did some digging and wanted to share my findings. I'm not gonna write a proposal as I believe the fix is a little complex here and I'm don't think I'll have the bandwidth to handle it in the next week or so. But I still wanted to share my thoughts anyways.

This seems to be a regression caused by https://github.com/Expensify/App/pull/27190.

More specifically, the following two lines:

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L418-L418
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L434

Basically when the edit composer is focused, the main composer is hidden, and when it blurs, the main composer is shown again. This is an attempt to not show main composer while we're editing a message, but using blur causes all sorts of issues on mWeb. Here's a video showing a few examples (Safari Desktop scaled down to mobile size - not a common scenario but this illustrate that there ARE issues, even if they don't manifest the same way on real mobile web):

https://github.com/Expensify/App/assets/765936/f8cf0100-d377-40c2-a08a-a218c24bc39c

On mobile web, when edit composer is focused, main composer will disappear. But whenever you click anywhere, it will blur and main composer will show again. That includes when you click on the emoji picker. It will first blur, and show the main composer. You have to click again for it to show (On proper mobile web this does not manifest the same way, but looking at the console you can see onyx updating the `shouldShowComposeInput` key, so it's still interacting with the main composer)

Also, if you are on edit and click the X, it will close the edit composer and the main composer is not shown. This is because once you hit X, the component is removed before the input blurs (does not happen on mobile web on phone, but still illustrates that there is a problem here).

Back to the scrolling problem, because of this weird interaction between edit composer and main composer, when the edit closes the scrolling gets out of whack. Could not pinpoint the exact reason, but moving the `setShouldShowComposeInputKeyboardAware(true);` call out of `onBlur` and into `deleteDraft` solves the problem.

I don't think the showing/hidding of main composer should be handled on focus/blur events. Rather it should be based on the present/absence of an edit composer. Basically, if there's one or more edit composers, then we hide it. Once there's none left, we show it again. This would be managed a few layers above `ReportActionItemMessageEdit.js` otherwise one edit wouldn't be aware of others.

I'm making the following assumptions here which I'm not 100% sure is correct:

* On mobile, we do not want to show the main composer when we're editing a message. period. Even if we focus outside of it. (btw, issue https://github.com/Expensify/App/issues/23908 seems to be about not showing composer when edit is present, but I can still do it. Just go on mobile web, edit two messages, and dismiss the one that's focused. The other will still be there and composer will show. Unless this is expected as the other edit is not focused, but to me this is just added complexity for little benefit).
* We want to be able to edit multiple messages at once (which to me sounds strange, I'd rather only allow one edit, meaning if you edit another message the previous edit gets dismissed).

This does not address the exact root cause of the scroll issue, but to me this is deeper than just that. There are problems on how edit interacts with main composer and that needs to be addressed, and when done, the scroll problem will very likely be solved as well (as it did on my simplified test).

**Comment by ikevin127** [comment] 2023-11-30 14:59
# Proposal

## Please re-state the problem that we are trying to solve in this issue

When adding an emoji by editing a comment and then saving it, the report scroll jumps up causing the conversation to become hidden.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/9bbb8ece72cd1c46bf7788a169c0b5c03d9bb6f6/src/pages/home/report/ReportActionItemMessageEdit.js#L299-L306

In the code block above we have logic for scrolling to the latest comment upon editing but this does not account for editing a message that is at an index different than 0, which is the case with this issue because we're editing a previous comment that's higher in the report.

The fact that we don't account for `props.index !== 0` to scroll to the message, and also the fact that after editing and saving message the app sometimes toggles list refresh, any of these two or each separately, will make the scroll jump up and hide part of the conversation.

## What changes do you think we should make in order to solve the problem?

Since the expected behaviour isn't clear as to where we want to position the scroll with regards to the just edited comment, here's what I propose:

My solution relies on using react native's flatlist [`scrollToIndex()`](https://reactnative.dev/docs/flatlist#scrolltoindex) method's `viewPosition` prop in our existing implementation of `useReportScrollManager()` -> `scrollToIndex()` so that we can pass one of the 3 values `0`, `0.5` or `1` to scroll the view focusing the edited comment according to the following schema:

<details>
<summary>viewPosition - Values schema</summary>

```
// viewPosition: 0
+--------------------------------+
|          Viewable Area          |
+--------------------------------+
|                                |
|                                |
|                                |
|                                |
|                                |
|                                |
| +-----------------------------+|
|   edited comment index         |
| +-----------------------------+|
+--------------------------------+

// viewPosition: 0.5
+--------------------------------+
|          Viewable Area          |
+--------------------------------+
|                                |
|                                |
|                                |
| +-----------------------------+|
|   edited comment index         |
| +-----------------------------+|
|                                |
|                                |
|                                |
+--------------------------------+

// viewPosition: 1
+--------------------------------+
|          Viewable Area          |
+--------------------------------+
| +-----------------------------+|
|   edited comment index         |
| +-----------------------------+|
|                                |
|                                |
|                                |
|                                |
|                                |
|                                |
+--------------------------------+
```

</details>

The idea is that if we do:
- `viewPosition: 0` - this will scroll the view such that edited comment is the last in the scrolled view (latest message of report will likely be hidden lower in scroll view)
- `viewPosition: 0.5` - this will scroll the view such that edited comment is in the middle the view (latest message of report will likely be hidden lower in scroll view)
- `viewPosition: 1` - this will scroll the view such that edited comment is at the top of the view (latest message of report will likely be seen if there's not a lot of of messages between last and edited comments OR will likely be hidden lower in scroll view if there are a lot of messages between the last and the edited message)

Say in this case if we decide to go with the `viewPosition: 1` value, the result can be observed below.


 ### Videos

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/56457735/49f37095-b4f1-42dd-8ca0-591e6c899dcb

</details>

**Comment by sakluger** [comment] 2023-12-04 19:49
This looks very similar to https://github.com/Expensify/App/issues/31594, I wonder if it's the same root cause.

@hoangzinh do you think this issue is the same root cause as https://github.com/Expensify/App/issues/31594 (which you're the C+ on)? If so, I'll close this as a duplicate.

**Comment by sakluger** [comment] 2023-12-06 18:54
Sounds good, we'll hold for https://github.com/Expensify/App/issues/31594 so we can verify if the other fix fixes this as well.

**Comment by sakluger** [comment] 2023-12-15 17:40
We've made some changes to our bug prioritization processes. Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves (i.e. roadmap initiatives), so I'm closing this out. We will re-address once the waves are completed. If you think that this bug is related to one of our roadmap projects, please open a discussion in #expensify-open-source in Slack.

**Closed by sakluger** 2023-12-15 17:40 UTC
Labels: External, Weekly, Overdue, Bug
