### ISSUE TITLE
Report view header is missing skeleton while app is loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49520] opened 2024-09-20 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to Account settings > Troubleshoot > Clear reset and restart.
4. Click Reset and refresh.
5. Go back to Inbox.
6. Compare the header on the report view on staging and production while app is loading.

## Expected Result:
The report view header will have skeleton while app is loading (production behavior).

## Actual Result:
The report view header is missing skeleton while app is loading.
The issue is more obvious when the window is not in full screen mode (Mac).

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1440" alt="Bug6609800_1726826572137!desktop_full_screen" src="https://github.com/user-attachments/assets/0d744c44-c9d3-4f99-8039-68ded4e03ca7">
<img width="1191" alt="Bug6609800_1726826341561!desktop" src="https://github.com/user-attachments/assets/0928cfa0-3c06-4726-af0a-66eb4ac0bea0">
<img width="1440" alt="Bug6609800_1726826154969!Screenshot_2024-09-20_at_17 53 30" src="https://github.com/user-attachments/assets/b8625af9-7478-462a-bd03-a5e4745bf0cc">

https://github.com/user-attachments/assets/3d1d3484-3916-44e1-ae0c-cb689a3317dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2024-09-20 11:48
| Environment | Screenshot |
|-------------|------------|
| Staging     | <img width="600" alt="Screenshot 2024-09-20 at 12 46 20 PM" src="https://github.com/user-attachments/assets/69c5f81b-3df3-4ba3-8cef-94a1d4a9adae"> |
| Production  | <img width="600" alt="Screenshot 2024-09-20 at 12 46 18 PM" src="https://github.com/user-attachments/assets/7be0ac0a-32a7-490e-8663-334f39bd193b"> |

**Comment by grgia** [comment] 2024-09-20 12:08
Confirmed with test revert it was caused by https://github.com/Expensify/App/issues/49056

**Comment by BhuvaneshPatil** [comment] 2024-09-20 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report view header is missing skeleton while app is loading

### What is the root cause of that problem?
In the mentioned PR https://github.com/Expensify/App/pull/49056, we modified this lines
https://github.com/Expensify/App/blob/c666296588dd7628d14b1e7d6b8e2602537a97e7/src/pages/home/ReportScreen.tsx#L285-L305

It makes header view null and it doesn't appear. Because `report` is null when app is loading. 

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/c666296588dd7628d14b1e7d6b8e2602537a97e7/src/pages/home/ReportScreen.tsx#L730

We can modify this line as 
```tsx
{headerView??<ReportHeaderSkeletonView/>}
```
So in case we don't have `headerView` it will show skeleton

Result - 

https://github.com/user-attachments/assets/5421519a-6219-47e6-8012-2bc22471cea9



### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2024-09-20 14:00
thank you @BhuvaneshPatil, I'm going to ask @daledah raise the PR as this bug is a regression from https://github.com/Expensify/App/pull/49056

**Comment by BhuvaneshPatil** [comment] 2024-09-20 14:03
No worries. I hope the changes suggested maybe of use for resolving the bug. Thanks.

**Closed** 2024-12-11 09:20 UTC
Labels: Reviewing, Engineering, Monthly, Bug
