### ISSUE TITLE
[$1000] Workspace - User name is not updated dynamically in Workspace Invite Member page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22175] opened 2023-07-04 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21700
## Action Performed:
1. Go to staging.new.expensify.com
2. As User A, go to Settings > Workspace > Members > Invite > Enter User B's address > Select User B
3. As User B, change profile name

## Expected Result:
B's name is changed correctly in A

## Actual Result:
B's name is not updated in A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7957439c-f216-4008-8879-16720d135ce1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd1d83c4be8598f1</li>
        <li>Upwork Job ID: 1677065936447025152</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-04 16:54
This isn't reproducible.

**Comment by sonialiap** [comment] 2023-07-06 21:24
I can reproduce. Triaging to external 

https://github.com/Expensify/App/assets/17131195/85fb96f9-1d38-4ec4-96c5-be9860c033f4

**Comment by mollfpr** [comment] 2023-07-10 03:39
I couldn't reproduce this with the OP step. @sonialiap I couldn't access your video attachment to see the step.

https://github.com/Expensify/App/assets/25520267/1f68a89e-ead3-4dbe-aa27-77a04470b492

**Comment by sonialiap** [comment] 2023-07-13 14:02
I can't reproduce any longer. I'm guessing this was fixed by another PR

https://github.com/Expensify/App/assets/17131195/339aee1b-881e-40bf-9e74-7368ae398d21

**Closed by sonialiap** 2023-07-13 14:02 UTC
Labels: External, Daily, Help Wanted, Bug
