### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Emoji picker - Highlight is removed from emoji when scrolling up with up key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36883] opened 2024-02-20 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4168711
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open emoji picker
2. Press down key till the first two rows of 'Smileys & Emotions' emoji section is hidden
3. Then press up key till you reach the first two rows that were hidden from view

## Expected Result:
Highlight should be applied on emoji that the user has navigated too

## Actual Result:
Highlight is not applied on emoji that the user has navigated too

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cb0142e7-6c11-43c5-8db8-2035d3043830

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2c7f05245fc734a</li>
        <li>Upwork Job ID: 1760053354078916608</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-20 14:01
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by kbecciv** [comment] 2024-02-20 14:02
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mananjadhav** [comment] 2024-02-21 00:33
@Krishna2323 I did not understand what you mean by `Result  Use flatListRef.scrollToIndex({index, animated: true});`. But overall your proposal looks good. I tested and it worked fine.

🎀 👀 🎀 C+ reviewed.

**Comment by Pujan92** [comment] 2024-02-21 19:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Highlighted emoji isn't scrolled when we go up

### What is the root cause of that problem?
Earlier with the `FlatList` it was working as `scrollPaddingTop` added to the style of it in [this PR](https://github.com/Expensify/App/pull/26633) at [this place](https://github.com/Expensify/App/pull/26633/files#diff-67118ceda8cb66e4c6e8367afc02904c8a06f92ac5cb6e9e0a52a0c26433695fR536-R537). 
After migrating to the `FlashList` it isn't working as that style(`scrollPaddingTop`) has been given to the parent View instead of `FlashList`. [PR](https://github.com/Expensify/App/pull/31479) cc: @TMisiukiewicz 

https://github.com/Expensify/App/blob/786b7abfeb8ffa8a7a7a691c642d332e05fa2db9/src/components/EmojiPicker/EmojiPickerMenu/index.js#L337-L342

https://github.com/Expensify/App/blob/786b7abfeb8ffa8a7a7a691c642d332e05fa2db9/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.js#L129-L130

### What changes do you think we should make in order to solve the problem?
By looking at the `FlashList` repo it seems passing `style` won't work directly as fixed styles(`style: { minHeight: 1, minWidth: 1 },`) [set for it](https://github.com/Shopify/flash-list/blob/7ff0fa56731cc5043f8d055f4315a1e81589015b/src/FlashList.tsx#L338-L364).
We can override the style prop with `overrideProps` which isn't recommended as per the [doc](https://shopify.github.io/flash-list/docs/usage#overrideprops) but I am only seeing that option at the moment. Remove `scrollPaddingTop` from the `listWrapperStyle`.

```js
overrideProps={{
    style: {
        minHeight: 1, 
        minWidth: 1,
        scrollPaddingTop: isFiltered ? 0 : CONST.EMOJI_PICKER_ITEM_HEIGHT
    }
}}
``` 

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/cbddfa7c-9b9c-452e-88be-4b320fe693ad

</details>

**Comment by puneetlath** [comment] 2024-02-28 14:56
Ok let's go with option 2.

**Comment by puneetlath** [comment] 2024-03-18 19:53
Moving to monthly for https://github.com/Expensify/App/issues/36883#issuecomment-1998756425

**Comment by puneetlath** [comment] 2024-04-17 17:15
Sent offer here: https://www.upwork.com/nx/wm/offer/101910104

Please ping me on this issue when you've accepted.

**Comment by puneetlath** [comment] 2024-04-18 15:32
All paid.

**Closed by puneetlath** 2024-04-18 15:32 UTC
Labels: External, Monthly, Awaiting Payment, Bug
