### ISSUE TITLE
Context menu not updating immediately after deleting an original thread comment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21632] opened 2023-06-26 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Post a comment
2. Hover over the comment and click on reply in thread
3. Go back to the previous originating chat and delete the comment
4. Hover over the [Deleted message] comment
5. Reload the page and do step 4 again

## Expected Result:
 Context menu should update to show only Reply in thread and mark as unread options immediately

## Actual Result:
Context menu doesn't update immediately unless user manually reloads the page or switches chat and comes back to the previous chat again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ab4bfcfa-c614-4455-9be4-19a1be68ea6b

https://github.com/Expensify/App/assets/93399543/148c4587-6c42-48cb-a638-409886f6d40f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687462733210969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-06-26 21:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Context menu not updating immediately after deleting an original thread comment

### What is the root cause of that problem?
For the deleteComment optimisticReportActions we are updating the `message` field with `isDeletedParentAction` here.
https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/libs/actions/Report.js#L836-L849

But from [this PR ](https://github.com/Expensify/App/pull/20460/files) we are validating the field `originalMessage.isDeletedParentAction` which seems to be a issue here.
https://github.com/Expensify/App/blob/67561d81bd95681e47dab14261349eb6eaad384d/src/libs/ReportActionsUtils.js#L434-L436

### What changes do you think we should make in order to solve the problem?
We should check the `message[0].isDeletedParentAction` which we are setting for the optimisticData.
`return lodashGet(reportAction, 'message[0].isDeletedParentAction', false);`

**Comment by mallenexpensify** [comment] 2023-06-30 00:48
This issue was reported 6/22 at noon
<img width="422" alt="image" src="https://github.com/Expensify/App/assets/22508304/bd62542d-5aa6-4084-a6ce-53f6e285f76f">

Other is from 6/13, so putting this on hold, pending that. 
- https://github.com/Expensify/App/issues/21103

Thanks @hungvu193 for linking the other issue

**Comment by mallenexpensify** [comment] 2023-07-11 23:54
- #21103

The above is still being worked on

**Comment by mallenexpensify** [comment] 2023-07-26 00:50
Off hold, the PR for the below hit production. 
- https://github.com/Expensify/App/issues/21103

I'm unable to reproduce, I don't get a `[Deleted Message]` comment after deleting. 
@Nathan-Mulugeta, can you try to reproduce?  and post a vid if you're able to? Thx

<img width="679" alt="image" src="https://github.com/Expensify/App/assets/22508304/28129044-b80e-4387-b2af-6a236f2eb668">

**Comment by Nathan-Mulugeta** [comment] 2023-07-26 07:45
Yes @mallenexpensify, it has been fixed by [this PR](https://github.com/Expensify/App/pull/22956). I also can't reproduce this issue anymore. I have a question though, since the PR that fixed this issue was created and merged last week which was after this issue's creation, does that make me eligible for the reporting bonus?

**Comment by mallenexpensify** [comment] 2023-08-01 22:20
@Nathan-Mulugeta , unfortunately not because the other bug report came first and someone was compensated for that. 
<img width="825" alt="image" src="https://github.com/Expensify/App/assets/22508304/4587229b-4074-4037-b717-b0ab7da46147">

<img width="404" alt="image" src="https://github.com/Expensify/App/assets/22508304/fd8ed952-effd-4dac-a839-c1a3d5dad70d">

**Closed by mallenexpensify** 2023-08-01 22:20 UTC
Labels: Weekly
