### ISSUE TITLE
[$500] mweb/Chrome - Login - Top portion of login page disappears when highlighting email in login field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32387] opened 2023-12-01 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to login page
2. Enter invalid address by pasting email address twice
3. Hit Continue
4. Highlight the email address

## Expected Result:
The page will not misalign when highlighting the email address when there is error message

## Actual Result:
The top portion of login page disappears when highlighting email field with error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/47694db5-7cbf-4142-ab84-d968da9fed22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ccd96e1a0303b27</li>
        <li>Upwork Job ID: 1730708926060453888</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment] 2023-12-02 08:00
Can't reproduce.

**Comment by saqlainrasheed** [comment] 2023-12-02 14:39
Issue:
Presently, on the Android web browser (Chrome), the top section of the login screen shifts to the left when extensive text is entered into the input field and subsequently selected.

Core Problem:
This problem arises from conflicting layout issues between the width of the background SVGs and the wrapper element encompassing both the form and background image.

Solution:
To address this issue, a quick and effective solution involves removing the overFlow: 'hidden' style from the scrollview, which acts as a wrapper for these elements.

Second Solution (More Time-Consuming):
Alternatively, a lengthier but more comprehensive approach is to reconsider the layout architecture to prevent this bug from occurring.

**Comment by cubuspl42** [comment] 2023-12-05 11:26
@saqlainrasheed I'm having a bad feeling about this... Have you extensively tested the solution, on all platforms, including iOS Safari? Just removing the `overflow: hidden` in a "well, it probably wasn't needed!" style sounds like a receipe for regressions ☹️

**Comment by isabelastisser** [comment] 2023-12-07 17:19
Hey @saqlainrasheed can you please follow up on the question above? Thanks!

**Comment by saqlainrasheed** [comment] 2023-12-08 11:08
@cubuspl42 Well you are right I didn't check this on Safari initially and playing with `overflow: hidden` can really mess things up on other platforms.

**Comment by isabelastisser** [comment] 2023-12-11 14:31
@cubuspl42, are we still waiting for proposals?

**Comment by Victor-Nyagudi** [comment] 2023-12-11 15:09
I investigated this briefly and here's what I found. 

You don't have to try logging in to reproduce the bug. You just need to have a long email that goes a fair ways outside the bounds of the input, scroll horizontally to the start of the input, then highlight the word that's clipped.

Android highlights the text from its beginning that's visible in the text input to its end that's clipped to the right of the input.  This scrolls the page to the left making it look like the top portion of the login page disappears. 

 The scrolling doesn't happen when just a few words are outside of the input's bounds.
 
 Removing `overflow: hidden` may have worked on Android because there would no longer be a need to scroll since the content is always visible (the default `overflow` value).
 
That being said, I tried giving the background image a `maxWidth: 100%` which prevented the 'top portion from disappearing', but this changed the way it looked during log in (regression). 
 
I didn't come up with a solution, but maybe this could provide some more insight to someone else who may want to tackle this issue.

**Comment by cubuspl42** [comment] 2023-12-11 17:59
> @cubuspl42, are we still waiting for proposals?

The author of the single proposal agreed that their solution introduces regression. So yeah.

**Comment by isabelastisser** [comment] 2023-12-11 18:00
Thanks @cubuspl42!

Waiting for proposals.

**Comment by isabelastisser** [comment] 2023-12-14 18:13
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-12-15 17:46
I'm reviewing this again now, and I believe this is primarily an edge case for long and invalid emails. I will confirm in Slack if this needs to be fixed now or can be closed.

**Comment by mallenexpensify** [comment] 2023-12-15 17:56
@Victor-Nyagudi thanks for the recap above, super helpful!

**Comment by isabelastisser** [comment] 2023-12-15 18:02
We've decided to close this one for now.

**Closed by isabelastisser** 2023-12-15 18:02 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by Victor-Nyagudi** [comment] 2023-12-15 18:30
No problem, @mallenexpensify .
