### ISSUE TITLE
[$1000] [mweb-Android] click on back button of device navigates to payments page instead of setting page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20681] opened 2023-06-13 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to `settings`> `payments`
2. click on `add payment method` button
3. select `bank account` option
4. click on :heavy_multiplication_x: button (this should bring you back to the `payments` page)
5. press **the physical back button of device** (this should bring you back to the `settings` page)

**Note on step 5:** if you click the the back caret icon, the app will navigate back to the `settings` page as expected. To reproduce this behavior, you need to make sure you are clicking the physical back button on the device.

## Expected Result: 
should navigate to settings page
## Actual Result: 
navigates to payments page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4f086d21-2566-493a-af28-264a38d62645

https://github.com/Expensify/App/assets/43996225/444fef15-dee6-4550-8fde-db5e7d1571e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686163312643879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cf84038380781c3</li>
        <li>Upwork Job ID: 1671163486872637440</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-06-14 10:55
I don't think that's correct, @c3024. After clicking 'X' on the Plaid popup, you should be back on the payments page. Clicking back should bring you to the previous page, which should be the settings page.

I've updated the repro steps to make that a bit clearer.

**Comment by johncschuster** [comment] 2023-06-20 14:36
Calm down, Melvin. I just triaged the issue.

**Comment by johncschuster** [comment] 2023-06-22 13:48
@hoangzinh I get where you're coming from, but I think the 'X' would simply close the modal, which should bring us back to the last thing we saw before the modal, right?

Your suggestion is more like a redirect, isn't it?

**Comment by johncschuster** [comment] 2023-06-26 17:13
@eVoloshchak can you take a look at the above proposal when you get a moment?

**Comment by rain2o** [comment] 2023-06-28 16:42
I suspect this is impacted by #20620. It's possible this is solved by #21067, though I haven't tested it to be sure.

**Comment by ygshbht** [comment] 2023-06-29 10:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the navigation path **/settings > /payments > /add-personal-bank-account**, when a user presses the device's back button once, the app correctly redirects to the /payments page. However, on pressing the back button a second time, it is expected to navigate back to /settings, but instead, it stays on the /payments page.

### What is the root cause of that problem?
I've concluded from extensive examination that the Plaid integration is introducing some unforeseen changes to the browser's history stack. The expected stack sequence should be **[/settings, /payments, /add-personal-bank-account]**, but due to the Plaid integration, an extra **/add-personal-bank-account** entry gets inserted, transforming the stack to **[/settings, /payments, /add-personal-bank-account, /add-personal-bank-account]**.

This extra entry seems to be confusing react-navigation during the execution of **Navigation.goBack()**, causing the system to interpret the extra **/add-personal-bank-account** entry as a **/payments** route. Hence, the second press of the back button, instead of taking the user back to **/settings**, stays on the **/payments** page.

### What changes do you think we should make in order to solve the problem?
A simple, straightforward, and efficient solution involves adjusting the back navigation operation to skip over the unintentional duplicate entry. When exiting Plaid, we can use **history.go(-2);** in a web environment to move back two steps directly in the history stack. For a native environment, the standard **Navigation.goBack()** function would suffice. Here is the proposed implementation:

```
onExitPlaid={()=>{
    if (thisIsABrowser){
        history.go(-2);
    } else {
        Navigation.goBack();
    }
}}
```
This correction should align the application's behavior with the user's expectations. Furthermore, if you believe in achieving better code organization and separation of concerns, you could abstract this direct interaction with the browser's history into a separate utility or service.

**Comment by johncschuster** [comment] 2023-06-29 11:54
@Nodebrute 

> I tested this on the Android app. There too Back button navigates to the payment page. Do we want the same navigation flow on all platforms?

Good question. I think we would want a consistent flow across all platforms.

I'm curious – what is it about the physical back button that is different than the back button in software? Are they not sending the same exact command?

**Comment by eVoloshchak** [comment] 2023-07-05 15:59
Huh, this is an age-old Android issue with the difference between the back button in Browser vs in Native 

> Native back button on Android calls goBack action from react-navigation while the browser uses the browser history API, which will normally navigate you to the last visited url

This needs to be addressed in a more universal way to resolve this throughout the app, similar issues are present on other pages

**Comment by eVoloshchak** [comment] 2023-07-05 16:11
> We are triggering [here](https://github.com/Expensify/App/blob/main/src/pages/AddPersonalBankAccountPage.js#L123C33-L123C44) Navigation.goBack(). This will get trigger whenever user exit plaid page. No matter what he choose ✖️ button or device back button result will be same of both actions.
If we want to user to go to settings page we can change [this](https://github.com/Expensify/App/blob/main/src/pages/AddPersonalBankAccountPage.js#L123C33-L123C44) to Navigation.navigate(ROUTES.SETTINGS)

I don't think that's correct, we shouldn't navigate to the settings page. After closing the modal user should be on the payments page

**Comment by ygshbht** [comment] 2023-07-05 18:51
@eVoloshchak 
I appreciate your response and the opportunity to further clarify my solution. To address your concern about Plaid changing their library and potentially adding more screens, I've devised a more dynamic approach.

Here's a modified version of the onExitPlaid function which accounts for the number of URLs Plaid may add:

```
onExitPlaid={(() => {
    if (true) { // If we're running in a browser environment

        // This variable will track the automatic page back navigation done by the browser 
        // when the user clicks the browser's back button from the Plaid interface
        // Please note: you can ignore this variable and the 'popstate' event listener 
        // if you are only trying to replicate/understand the issue exactly as per the actions to reproduce or the attached video.
        let automaticRemovalOfExtraUrl = 0; 

        // 'popstate' event is fired whenever the active history entry changes, including when the user clicks the browser's back button
        const popstateHandler = function() {
            automaticRemovalOfExtraUrl += 1;
        }
    
        // Set up the 'popstate' event listener
        window.addEventListener('popstate', popstateHandler);

        // Record the current length of the history
        const currentLength = history.length;
        
        return (e) => {
            // Calculate the number of extra URLs added by Plaid
            let extraUrls = history.length - currentLength;

            // Navigate back by the number calculated as: 
            // (1 + number of extra URLs added by Plaid - automatic page back navigations done by the browser)
            // This ensures that we always navigate back to the correct page irrespective of the number of URLs added by Plaid 
            // or whether the back button of the browser was clicked
            history.go(- (1 + extraUrls - automaticRemovalOfExtraUrl));

            // Clean up: remove the 'popstate' event listener
            window.removeEventListener('popstate', popstateHandler); 
        }
    } else {
        return Navigation.goBack; 
    }
})()}
```

You can test this implementation to verify its effectiveness. It considers the number of URLs Plaid might add, allowing the back navigation to adjust dynamically.

However, I wholeheartedly agree that if a more generic, less specific solution is found, it should be pursued. This approach represents a viable solution, but I welcome any alternatives that could better address the issue. Please feel free to share any additional insights or feedback.

**Comment by adamgrzybowski** [comment] 2023-07-06 14:05
Where should be the user after actions below?
1. Go to settings > payments
2. Click on add payment method button
3. Select bank account option and wait for plaid to load
4. Press the physical back button of device (this should bring you back to the settings page)

The solution above takes me to the settings page and it feels like it should be the payments page right?

But I think it's the right direction. We have to somehow re-align the history in the browser with the history in the react-navigation

**Comment by ygshbht** [comment] 2023-07-06 15:07
I'd have to admit mine's not a very powerful solution. I didn't initially expect onExitPlaid to run when you press the browser's back button making the code to work only for the scenerio when the user goes back using plaid's X button and then navigates using the browser's/ device's back button. If you exit plaid using the device's/ browser's back button, onExitPlaid={Navigation.goBack} is enough

**Comment by ygshbht** [comment] 2023-07-06 17:14
While the previous solution provides a more dynamic approach to navigation, it does have certain limitations. Given the current setup, it doesn't seem straightforward to discern whether the onExitPlaid function was triggered due to a user clicking the 'X' button on the Plaid interface, or due to user's navigation using the browser's or device's back button.

To handle this, an alternative solution could be to create a new navigation stack within the onExitPlaid function. This would involve explicitly navigating to each required screen. Here's a potential implementation:

```
onExitPlaid={(() => {
    if (true) { // If we're running in a browser environment
        return () => {
            // Creating a new navigation stack that leads to the desired screen
            Navigation.navigate('Homepage');
            Navigation.navigate('Settings');
            Navigation.navigate('Payments');
            Navigation.navigate('AddBankPayment');

            // Go back to the payments screen from the 'AddBankPayment' screen
            Navigation.goBack('Payments');
        }
    } else {
        return Navigation.goBack 
    }
})()}

```
This solution ensures that we're always arriving at the intended screen, regardless of how the onExitPlaid function is triggered.

**Comment by johncschuster** [comment] 2023-07-07 20:53
Not overdue, Melvin. We're still working this one out.

**Comment by johncschuster** [comment] 2023-07-10 15:10
@Nodebrute 

> When we press the ✖️ (close) button, where should we navigate?
Clicking ✖️ on the Plaid modal should return you to the `payments` page

> When we press the back button, where should we navigate?
That depends. If you have just been returned to the `payments` page from clicking the ✖️ , I would expect the `back` button to send you to the page previous to the `payments` page, which should be the `settings` page.

**Comment by eVoloshchak** [comment] 2023-07-10 17:11
@ygshbht, thanks for keeping the investigation going!

> To handle this, an alternative solution could be to create a new navigation stack within the onExitPlaid function
> A modified version of the onExitPlaid function which accounts for the number of URLs Plaid may add

While those are working solutions, both are working around the problem, I agree with the following:
> If a more generic, less specific solution is found, it should be pursued.

Ideally, we want to resolve the issue with "Plaid integration introducing some unforeseen changes to the browser's history stack" 
If that is a bug, can we report it to the Plaid team?

**Comment by ygshbht** [comment] 2023-07-10 19:20
@eVoloshchak Indeed, I believe the issue originates from the Plaid integration, which appears to be causing modifications to the browser's history stack. This behavior may or may not be considered a bug by Plaid's team. However, it would certainly be beneficial to raise this issue with them, as these alterations to the history stack seem to occur within their package.

**Comment by johncschuster** [comment] 2023-07-12 20:20
Hmm... I'm confused. I thought I made this issue Internal and assigned an engineer. 🤔 

Spinning the wheel again

**Comment by ygshbht** [comment] 2023-07-14 00:20
@eVoloshchak  Absolutely, I'm happy to provide anything that can help debug the app. You can find the repository [here](https://github.com/ygshbht/plaid-history-addition). To start the Node.js backend, use the command **./start.sh** from within the `/node` directory. For the frontend, navigate to the `/frontend` directory and run **npm start**.

Lastly, don't forget to set your **PLAID_CLIENT_ID** and **PLAID_SECRET** variables in the .env file within the `/node` directory. This step is essential for the application to function correctly.

https://github.com/Expensify/App/assets/65986357/b66410d4-b56e-4321-818f-2dee9a6be4ad

**Comment by srikarparsi** [comment] 2023-07-17 08:40
Thanks @ygshbht and @eVoloshchak! Will take a look into this tomorrow and update the issue.

**Comment by johncschuster** [comment] 2023-07-19 21:39
How's this going @srikarparsi?

**Comment by srikarparsi** [comment] 2023-07-20 03:37
Hey @johncschuster! I got caught up in other issues the last two days but will make this a priority for tomorrow and leave an update.

**Comment by srikarparsi** [comment] 2023-07-21 08:25
I agree, we should definitely submit a bug report to Plaid rather than creating a workaround for their issue. Thanks for this reproducible example @ygshbht! I see a [similar issue](https://github.com/plaid/react-plaid-link/issues/301) that's already open in their repository but I'll ask internally to see if we have any connections with Plaid we can go through to get this fixed.

**Comment by srikarparsi** [comment] 2023-07-21 08:40
Messaged plaid in our channel [here](https://expensify.slack.com/archives/CCQJP89RV/p1689928793556129)

**Comment by srikarparsi** [comment] 2023-07-24 20:33
Plaid send they'll get back to us [early this week](https://expensify.slack.com/archives/CCQJP89RV/p1689960927575689?thread_ts=1689928793.556129&cid=CCQJP89RV). I'll try reaching out again on Wednesday if we don't hear back.

**Comment by eVoloshchak** [comment] 2023-07-25 15:15
@srikarparsi, thanks for keeping the ball rolling on this one!

**Comment by srikarparsi** [comment] 2023-07-26 00:21
They've escalated to [engineering](https://expensify.slack.com/archives/CCQJP89RV/p1690313984693849?thread_ts=1689928793.556129&cid=CCQJP89RV) so they should start working on a fix soon. I'll message again early next week if we don't hear back.

**Comment by johncschuster** [comment] 2023-07-30 17:38
Thanks @srikarparsi!

**Comment by srikarparsi** [comment] 2023-08-02 18:17
check up: https://expensify.slack.com/archives/CCQJP89RV/p1691000228916339?thread_ts=1689928793.556129&cid=CCQJP89RV

**Comment by johncschuster** [comment] 2023-08-02 23:20
Awesome. Thanks for the update!

**Comment by srikarparsi** [comment] 2023-08-03 17:41
They said a fix should be in place but it doesn't seem to be. Sent a message following up: https://expensify.slack.com/archives/CCQJP89RV/p1691084404394809?thread_ts=1689928793.556129&cid=CCQJP89RV

**Comment by srikarparsi** [comment] 2023-08-08 22:27
The [fix has been deployed](https://expensify.slack.com/archives/CCQJP89RV/p1691518810719149?thread_ts=1689928793.556129&cid=CCQJP89RV) and it works. If there are no payments to be made, this issue should be good to close out @johncschuster
https://github.com/Expensify/App/assets/48188732/d0d69021-a7ff-4e43-a5b4-57fb96ba137d

**Comment by srikarparsi** [comment] 2023-08-14 16:34
Hey @johncschuster! Just wanted to bump this

**Comment by johncschuster** [comment] 2023-08-14 17:42
Hey hey! I think my status in NewDot was incorrect – I'm not OOO. I'm catching up now!

**Comment by srikarparsi** [comment] 2023-08-18 23:31
Hey @johncschuster! Just wanted to bump this for payment :)

**Comment by johncschuster** [comment] 2023-08-25 21:28
Derp! I'm sorry for missing this! Catching up now.

**Comment by johncschuster** [comment] 2023-08-25 21:32
Ok! It looks like this is good to close out. Closing!

**Closed by johncschuster** 2023-08-25 21:32 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by gadhiyamanan** [comment] 2023-08-26 01:54
Payment is pending here
cc: @johncschuster @srikarparsi

**Comment by johncschuster** [comment] 2023-08-28 14:46
Payment has been issued! (Thanks for the callout, @mananjadhav!)
