### ISSUE TITLE
Web - Expense request avatar is broken in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23821] opened 2023-07-28 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A with policyExpenseChat beta permission
2. Create workspace if not exist
3. Invite user B to workspace
4. Login user B on another device
5. On B, Go to invited A's workspace chat
6. Request money
7. click ReportPreview to go to expense report
8. click IOUPreview to go to expense request
9. Observe highlighted row in LHN

## Expected Result:
 Avatar is not broken

## Actual Result:
Avatar is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8086ed37-55a7-4d0b-995c-a8d6ee3ea441

https://github.com/Expensify/App/assets/93399543/4a252a3c-cba3-4243-bf24-6a0413089d74

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690545428804849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-07-29 13:03
@situchan How can I get account with policyExpenseChat beta permission?
I was overriding the Permissions.canUseAllBetas function to return true in my local, but when opening any workspace chat it return 304.
Do I need to have this permission in backend also?
cc @bernhardoj

**Comment by ahmedGaber93** [comment] 2023-07-29 13:34
@bernhardoj
Thanks for help.
But how can I get this permission in backend?

**Comment by situchan** [comment] 2023-07-29 22:46
@ahmedGaber93 please request permission in slack. You need to provide emails to be added to beta.

**Comment by ahmedGaber93** [comment] 2023-07-29 22:52
Thanks for help @situchan.
I have request permission in slack.

**Comment by situchan** [comment] 2023-07-31 16:26
@stephanieelliott can I C+ review this if possible? As I found the root cause and solution while reporting this bug.

**Comment by Christinadobrzyn** [comment] 2023-07-31 21:42
Hey @situchan do you think this issue will be fixed with the root cause you found? https://github.com/Expensify/App/issues/23847

**Comment by situchan** [comment] 2023-08-01 01:26
> This issue seems similar to #23847 - it looks like it's going to be fixed with #23815 - I asked the engineers in 23815 if they agree

@Christinadobrzyn No, it's different issue. #23815 was deployed to staging 6 hrs ago but broken avatar issue is still reproducible.

<img width="1087" alt="Screenshot 2023-08-01 at 7 25 36 AM" src="https://github.com/Expensify/App/assets/108292595/482ad0b3-55a9-4302-b833-9c9f501a85aa">

**Comment by rezkiy37** [comment] 2023-08-01 11:18
> This issue seems similar to #23847 - it looks like it's going to be fixed with #23815 - I asked the engineers in 23815 if they agree

FYI: https://github.com/Expensify/App/pull/23815#issuecomment-1660110273

**Comment by Christinadobrzyn** [comment] 2023-08-01 19:40
thanks for confirming @rezkiy37! Closing this as it's confirmed to be fixed with  https://github.com/Expensify/App/pull/23815#issuecomment-1660110273

@situchan feel free to reach out in the Expensify-Bugs room if you find any regressions

**Comment by Christinadobrzyn** [comment] 2023-08-01 20:45
Hey @rezkiy37, can you double-check this issue will be fixed? @situchan believes to think the issue still exists after the merge. 

Sorry for all the confusion @stephanieelliott - tried to save you some time!

**Comment by rezkiy37** [comment] 2023-08-01 20:50
Hi, @situchan! Could you please take a look at this comment where I attached examples. The second video associated with this issue. Do I still have the bug there?

https://github.com/Expensify/App/pull/23815#issuecomment-1660110273

**Comment by situchan** [comment] 2023-08-01 20:51
@rezkiy37 you can test on staging right now

**Comment by situchan** [comment] 2023-08-01 20:53
@rezkiy37 I checked your video. It's IOU request (in DM). The issue is in expense request (in workspace chat).
Is it clear now?

**Comment by stephanieelliott** [comment] 2023-08-01 22:18
Appreciate you, thanks @Christinadobrzyn! 💕

**Comment by rezkiy37** [comment] 2023-08-02 09:38
@situchan, I've tried to reproduce it one more time on the staging. Everything looks good. Avatars are circles.


https://github.com/Expensify/App/assets/57314631/bbd06521-99d4-475b-9137-a5d506236718

**Comment by situchan** [comment] 2023-08-02 10:07
Ah it's merged 12 hrs ago. So @rezkiy37 it's not your PR but Georgia's PR which fixed this issue.

**Closed** 2023-08-03 08:03 UTC
Labels: Daily, Bug
