### ISSUE TITLE
[HOLD for payment 2024-03-07] [LOW] [P2P] [$500] IOU-Add a contact to request money and tap back button, contact added to split.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32912] opened 2023-12-12 11:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Enter an amount
5. Tap next
6. Select a contact
7. Tap app's back button

## Expected Result:
When add a contact to request money and tap back button, contact must not be added to split.

## Actual Result:
When add a contact to request money and tap back button, contact added to split.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/34e33a73-a935-4ce0-9102-195fd162b75d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce8011451da4f3dc</li>
        <li>Upwork Job ID: 1734532115895476224</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28044286</li>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-12 11:31
We are not clearing participants list when coming back
```js
/**
 * @param {String} transactionID
 * @param {Object[]} participants
 */
function setMoneyRequestParticipants_temporaryForRefactor(transactionID, participants) {
    Onyx.merge(`${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transactionID}`, {participants});
}
```
There are some problems with the current logic of participants page
I will get back to this after some time. There are some other problems too

**Comment by Julesssss** [comment] 2023-12-12 11:42
Please prioritise this once you finish the C+ reviews, thank you!

**Comment by shubham1206agra** [comment] 2023-12-12 12:10
@dukenv0307 Do you have a solution right now?
If so, @Julesssss please assign @dukenv0307

**Comment by shubham1206agra** [comment] 2023-12-12 12:16
Can you post the video @bernhardoj?

**Comment by shubham1206agra** [comment] 2023-12-12 12:39
@Julesssss Can you assign @dukenv0307 here?

**Comment by shubham1206agra** [comment] 2023-12-12 13:21
@parasharrajat Are you here? Can you take the call here for the assignment? 
My preference would be @bernhardoj's proposal due to the reasons mentioned above.

**Comment by shubham1206agra** [comment] 2023-12-12 15:53
<img width="1512" alt="Screenshot 2023-12-12 at 9 22 31 PM" src="https://github.com/Expensify/App/assets/58412969/d62db6eb-5fb6-4d05-a964-2e71487e77c6">

I got this

**Comment by Julesssss** [comment] 2023-12-12 15:54
As this is urgent, I'd assign this to whomever is available first. 

@bernhardoj @dukenv0307 please comment when you are available to work on this

**Comment by Julesssss** [comment] 2023-12-12 15:57
Excellent, thank you

**Comment by luacmartins** [comment] 2023-12-12 19:20
I can't reproduce either, but I think that we should show the green dot in the workspace chat. It shows up if you navigate back to it.

**Comment by tgolen** [comment] 2023-12-12 20:27
Hey all, sorry I am late to this party. The intention of the refactor was to base decisions like "is this a split or is it a request" off of the URL path. I believe it's still possible to do this. I think a better solution might be this:

- When the back button is pressed
- Is it a request or split (as specified by the URL)
- If it's a split, leave the participants alone
- If it's a request, clear the participants

Does this sound more ideal? I was really trying to have a lot of "flags" everywhere, and while some of the weren't avoidable, I'd like to try and keep them to a minimum if we can.

**Comment by luacmartins** [comment] 2023-12-12 20:29
@bernhardoj can you check the above?

**Comment by luacmartins** [comment] 2023-12-12 22:48
We're gonna fix this internally with the approach @tgolen laid out above. Closing the current PR.

**Comment by Julesssss** [comment] 2023-12-13 09:34
> The PR not only deals with the participants but also some other things
> - Change the title to Split on adding a user to split participants.
> - Allow user to split with 1 participant
> - On staging, if we split with 1 person, it will make a full money request. So if we split 10$, it will do a 10$ request.
> - While on prod, if we split 10$ with 1 person, it will request 5$ to the person.

Thanks for sharing. Just to check, are these related to any issue? (there are so many at the moment that I'm finding it difficult to keep track). 

If they are, please share them. If not we should first verify these are all the expected behaviour, and can then resolve them.

**Comment by shubham1206agra** [comment] 2023-12-13 09:47
@bernhardoj I think @tgolen is hesistent to use isSplitRequest variable to be set inside transaction. So can you please provide an updated plan keeping in mind the requirement?

**Comment by tgolen** [comment] 2023-12-13 23:06
I'm sorry, I can't follow that proposal at all. There is too much code and that's why we request that code doesn't get put into proposals.

**Comment by tgolen** [comment] 2023-12-13 23:06
Generally speaking I think we should:

- have the URL reflect if it's a split or not
- only have it be a split if there is more than 1 person (that's the definition of a split)

**Comment by trjExpensify** [comment] 2023-12-15 00:02
👋 Coming from [here](https://github.com/Expensify/App/issues/33014), via this [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1702592709725159) of an internal bug report. 

It should totally be possible to split with just one other person, can we fix what changed that please?

**Comment by trjExpensify** [comment] 2023-12-15 11:25
There's [this one already](https://github.com/Expensify/App/issues/33014#issuecomment-1855149452) that looks like it was closed in favour of it being fixed with the solution being proposed here. 

@tgolen, what do you think? @bernhardoj is correct that you can and should be able to split with one other person.

**Comment by situchan** [comment] 2023-12-15 11:30
Dedicated issue created: https://github.com/Expensify/App/issues/33068
cc: @joekaufmanexpensify

**Comment by tgolen** [comment] 2023-12-20 20:09
Can you please point me to the proposal you want to accept and I will evaluate it fresh? I cannot follow what's happening in these comments or the previous proposals.

**Comment by kadiealexander** [comment] 2023-12-20 20:45
Melvin you muppet, @conorpendergrast is the BugZero team member!

**Comment by tgolen** [comment] 2023-12-21 15:33
Thanks, that proposal looks fine 👍

**Comment by trjExpensify** [comment] 2024-01-17 17:40
👋 Changed this back to `Weekly`, the ability to split a bill with someone is broken. It's repeatedly causing confusion as people click `Split` and it proceeds to request and not to the split confirmation screen. 

The PR is going stale, @bernhardoj @parasharrajat can we get it over the finish line please? Thanks!

Also, dropping it into the split VIP GH project for tracking. CC: @GabiHExpensify

**Comment by conorpendergrast** [comment] 2024-01-31 12:37
What's the status here?

**Comment by bernhardoj** [comment] 2024-01-31 12:38
@parasharrajat is still testing the PR.

**Comment by tgolen** [comment] 2024-02-14 16:21
There have been no updates to this issue or the PR for two weeks. What needs to happen to get this finished with some urgency @bernhardoj @parasharrajat?

**Comment by bernhardoj** [comment] 2024-02-14 16:53
Still waiting on @parasharrajat review. I just merged with main btw.

**Comment by tgolen** [comment] 2024-02-15 15:55
OK, thank you. I've pinged them on Slack as well to try to get some movement on this.

**Comment by tgolen** [comment] 2024-02-21 16:35
Pinging them [in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1708012496053649) again.

**Comment by MitchExpensify** [comment] 2024-02-26 18:37
@akinwale has volunteered to take over here 🙇

**Comment by MitchExpensify** [comment] 2024-02-27 19:23
@youssef-lr Are we ready to merge here?

**Comment by youssef-lr** [comment] 2024-02-28 02:51
Reviewing now!

**Comment by youssef-lr** [comment] 2024-02-28 03:03
Code LGTM, but I found a bug.

**Comment by MitchExpensify** [comment] 2024-03-02 02:11
Reminder set to pay

**Comment by MitchExpensify** [comment] 2024-03-09 18:03
*Payment summary:*

C+: $500 @situchan (Upwork) 
C: $500 @akinwale (Upwork)

Paid and contracts ended

**Comment by MitchExpensify** [comment] 2024-03-19 20:15
I mistook my payment to Bernhard for a payment to Situ - Very sorry for that slip up @situchan. To correct it I have sent you an offer here https://www.upwork.com/nx/wm/offer/101471671

**Comment by situchan** [comment] 2024-03-19 20:16
Accepted thanks

**Comment by MitchExpensify** [comment] 2024-03-19 20:17
Paid and contract ended, thanks!

**Closed by MitchExpensify** 2024-03-19 20:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
