### ISSUE TITLE
[HOLD for payment 2024-03-11] [HOLD for payment 2024-03-07] [$500] iOS - Attachment - PDF files aren't cached and flashes once while loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32232] opened 2023-11-29 22:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Upload a larger PDF (10-20MB) to any conversation
4. Open the PDF
5. Go back to the chat
6. Open the same PDF again

## Expected Result:
PDF files should be cached and no flashing once while loading

## Actual Result:
PDF files aren't cached and flashes once while loading. They are downloaded every time a request is made

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/50db3de2-2871-4834-86dd-b6b35cfd83a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa9414036934592a</li>
        <li>Upwork Job ID: 1729988103538311168</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27965277</li>
<li>tienifr | Contributor | 27965278</li>
</ul></li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 23:26
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
## What is the root cause of that problem?
## What changes do you think we should make in order to solve the problem?

Add this line like 

`source={{uri: this.props.sourceURL, cache: true}}`

## What alternative solutions did you explore? (Optional)
NA

**Comment by giltron** [comment] 2023-11-30 03:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

PDF files are not cached and are re-downloaded everytime.

### What is the root cause of that problem?

The use of the react-native-pdf module is not using the caching options

### What changes do you think we should make in order to solve the problem?

There are 4 items to address it reasonably and completely.


1. Add the  `cache: true`  in the source parameter as per react-native-pdf documentation.  Note this will keep the files indefinitely without any further configuration.

```
 source={{uri: this.props.sourceURL, cache: true }}
```

2. **If** we need  to address security of attachments staying on device after user logs out or different user logs in (note: user would need to physical device access) then the following can be done: (Note: PDFs downloaded go into the CacheDir as configured in react-native-pdf):

```
 source={{uri: this.props.sourceURL, cache: true, cacheFileName: cacheFileName}}
```

Where cacheFileName is specified by taking the original filename (or id) and prepending the sanitized user's id to it.  This way we can easily clean any files not of the current user later by scanning the all files in the CacheDir on Login/Logout  with [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util) `RNFetchBlob.fs.lstat `

3.  As per the [source parameter specified react-native-pdf](https://github.com/wonday/react-native-pdf/blob/5df5a1b0bfb5cea129eb9e1f9a610166c3b94bf1/README.md?plain=1#L321-L330):

We also should a _reasonable expiration time_ to avoid the Apps storage from growing too large.  For example 3 days which is 259200 seconds.

```
const expirationPDFTime =  259200; 
```

```
 source={{uri: this.props.sourceURL, cache: true, cacheFileName: cacheFileName, expiration: expirationPDFTime }}
```


4.  We can also optionally add a generic method to cull the CacheDir if it reaches past a certain size.   This can be down on login/logout or on a lengthy interval.

It will be similar to 3 but will involve  checking the size of  CacheDir folder using`RNFetchBlob.fs.readDir` (or  `RNFetchBlob.fs.lstat` and summing the file sizes ) and removing the oldest cached pdfs past an size threshold.


### What alternative solutions did you explore? (Optional)

N/A

**Comment by getusha** [comment] 2023-12-01 05:55
@tienifr how are we going to delete the cache after the user logs out? could you share a code snippet?

**Comment by getusha** [comment] 2023-12-05 07:21
The more detailed [proposal](https://github.com/Expensify/App/issues/32232#issuecomment-1832971963), from @tienifr looks good to me. it makes sense to use the unlink function from `react-native-fs` to clear cache as we are using it already, we should open a discussion on slack to determine what the best expiration interval is.

🎀👀🎀 C+ reviewed!

**Comment by MonilBhavsar** [comment] 2023-12-05 07:49
Sounds good. Do we have caching in web? why it is only reproducible on iOS native

**Comment by MonilBhavsar** [comment] 2023-12-05 11:18
Thanks! wanted to ensure, it's the browser only and we're not using any specific mechanism.

**Comment by MonilBhavsar** [comment] 2023-12-07 12:09
@tienifr any update on the PR?

**Comment by getusha** [comment] 2024-01-01 13:56
Working on the PR on specific cases, @tienifr will update soon.

**Comment by garrettmknight** [comment] 2024-01-24 15:16
PR is ready for review, still moving forward.

**Comment by garrettmknight** [comment] 2024-02-14 19:16
PR is still in progress.

**Comment by getusha** [comment] 2024-03-11 10:53
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: **This is a new feature**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **Yes**
 [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open any chat
2. Upload a large PDF file (15-20MB)
3. Open the PDF
4. Go back to the chat
5. Open the same PDF again
6. Verify that the PDF loads quickly

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment] 2024-03-11 19:27
Paid up at 50% based on the regression, closing!

**Closed by garrettmknight** 2024-03-11 19:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
