### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Start chat - App shows data from User A after logging out of User A and logging in with User B

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39710] opened 2024-04-05 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory around https://expensify.testrail.io/index.php?/tests/view/4476067
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account A and B are under the same private domain, and they share the same list of contacts.
- Account A and B have different set of Recent contacts in Start chat list.
1. Close and open incognito mode again for a fresh session.
2. Go to staging.new.expensify.com
3. Log in as Account A.
4. Go to FAB > Start chat > Chat.
5. Note that list of five contacts in Recent section.
6. Log out and log in as Account B.
7. Go to FAB > Start chat > Chat.
8. Note that Account B has the exact same list of five contacts in Recent section as Account A.
9. Close and open incognito mode.
10. Repeat Step 6 and 7 for Account B.

## Expected Result:
When user logs out and logs in with another account, the Recent section list will follow the data from the logged-in account.

## Actual Result:
When user logs out from Account A and logs in with Account B, the Recent section list still shows the data from Account A.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/88148a79-aa20-46bc-80a2-7e4213422ec8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e820a2af95c4423e</li>
        <li>Upwork Job ID: 1776276873995067392</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by kbecciv** [comment] 2024-04-05 12:54
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-04-05 13:09
I think this does not have to be a blocker

@kbecciv @kavimuru does the account B not know the recents accounts it shows?

**Comment by kavimuru** [comment] 2024-04-05 14:17
@mountiny Logged in with old account with recent contacts, then logged out and sign up with a completely new account. The contact list with old account still shows up for new account.


https://github.com/Expensify/App/assets/43996225/5ca3b525-5472-4161-bf5c-6dc9d07f54fa

**Comment by mountiny** [comment] 2024-04-05 15:53
Referring to this PR https://github.com/Expensify/App/pull/38207

**Comment by mountiny** [comment] 2024-04-05 15:54
Increasing to $500 since its a blocker, author of the PR is out for the day and its quite annoying bug as you could potentially see someone else's contacts cached

**Comment by bernhardoj** [comment] 2024-04-05 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report data is from another user is still cached even after logging out which makes it possible for other user that log in will see it.

### What is the root cause of that problem?
We have `OptionsListContextProvider` that will load the report list (and update it when it's updated) and cache it.

https://github.com/Expensify/App/blob/b10893a2a541a81112bb2a3d22647a9d7eaac94d/src/components/OptionListContextProvider.tsx#L39-L112

The provider is put in App.tsx which means the state (cache) is persisted even after we log out.
https://github.com/Expensify/App/blob/b10893a2a541a81112bb2a3d22647a9d7eaac94d/src/App.tsx#L86

### What changes do you think we should make in order to solve the problem?

Move the provider `OptionsListContextProvider` from App.tsx to AuthScreens. This way, when the user is logged out, the context provider is destroyed.

### What alternative solutions did you explore? (Optional)
Use `useSession` hook and clear both `reports` and `personalDetails` and also set `areOptionsInitialized` to false whenever the user logged out by checking the session auth token.
```
useEffect(() => {
    if (!session.authToken) {
        setOptions({reports: [], personalDetails: []});
        areOptionsInitialized.current = false;
    }
}, [session.authToken]);
```

**Comment by jasperhuangg** [comment] 2024-04-05 16:55
@bernhardoj your proposal makes sense to me, let's try to implement it quickly!

**Comment by bernhardoj** [comment] 2024-04-05 16:57
@jasperhuangg can you confirm if we are going with my main solution? (moving the provider)

**Comment by jasperhuangg** [comment] 2024-04-05 17:02
Ah yes, sorry. I think moving the component makes the most sense since it's a component associated with authenticated users. Thanks for checking.

**Comment by bernhardoj** [comment] 2024-04-05 17:13
Great, thanks for the confirmation. PR is ready.

**Comment by kavimuru** [comment] 2024-04-07 23:57
@mountiny Bug is fixed in all the platforms but Desktop. Desktop does not have the correct build version.

https://platform.applause.com/services/links/v1/external/4f3f83c90fa54dbe7ff4691984edde71edefd6da9e238ea3414d49eab3cf4534
https://platform.applause.com/services/links/v1/external/a08ef70d6c97c6d745314b5b2ef9786c0b9fb23b6be3c2c2bb255007e15b446d

https://platform.applause.com/services/links/v1/external/72ebf3a8b4239a38df20870a8e42f0e536209ed2d8b8831a2c2edb630a6fcfcd
https://platform.applause.com/services/links/v1/external/0bd5c0575b1498f4e4996700b6114144d631289b290a5ff431c4054cbeb4ef00

**Comment by mountiny** [comment] 2024-04-08 20:58
Thanks @kbecciv it was repro because the desktop build failed before

@puneetlath this will be ready for payment $500 to @bernhardoj and to @paultsimura

**Comment by puneetlath** [comment] 2024-04-08 22:55
Sorry, to clarify, you're saying I should pay them now? Or on April 15th?

**Comment by puneetlath** [comment] 2024-04-15 20:31
All paid. Thanks everyone!

**Closed by puneetlath** 2024-04-15 20:31 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
