### ISSUE TITLE
pinned chat appears as unpinned on reopen account after closing account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19336] opened 2023-05-20 11:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. pinned some chats
3. close the account
4. reopen the account

## Expected Result: 
pinned chat remains as it is
## Actual Result: 
pinned chats show as unpinned

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/636ee5aa-c99d-43ee-8a37-c90deaf6ad5b

https://github.com/Expensify/App/assets/43996225/5654c4fb-eda3-43c0-9a52-c843573143b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684321249933199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-05-22 13:07
I'm also [checking in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1684760755420069?thread_ts=1684321249.933199&cid=C049HHMV9SM) to see if this is definitely a bug. I'm not totally sure we would expect pinned chats to remain after closing and reopening a user account

**Comment by conorpendergrast** [comment] 2023-05-23 10:37
Discussed [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1684760755420069?thread_ts=1684321249.933199&cid=C049HHMV9SM) that this is **not a bug**, and we do not expect to retain starred chats after an account is closed and reopened. Closing this, thanks!

**Closed by conorpendergrast** 2023-05-23 10:37 UTC
Labels: Daily, Bug
