### ISSUE TITLE
[$500] Private Notes - The strikethrough line of the link is displaying in white on the Private Notes page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28859] opened 2023-10-04 20:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.
2. Open any chat
3. Click on the header and go to Private notes
4. Go to My note > Notes
5. Add "`https://xyz.com/`" and save
6. Notice that the strikethrough line appears in white

## Expected Result:
The strikethrough line should have the same colour as the link.

## Actual Result:
The strikethrough line appears in white

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (4)](https://github.com/Expensify/App/assets/93399543/aff22ff3-01a7-44b5-9966-ebbc6133f3b3)
![Screenshot 2023-10-03 at 10 19 20 PM](https://github.com/Expensify/App/assets/93399543/9c45b2ff-2c8e-495f-8f18-a2f91dad09cd)
![safari](https://github.com/Expensify/App/assets/93399543/53cbd152-9fcb-4be2-8e07-40c2ca758bc9)
![Screenshot 2023-10-03 at 10 16 53 PM](https://github.com/Expensify/App/assets/93399543/858f4044-89aa-40aa-8002-3adf270ccbd4)
![Screenshot 2023-10-03 at 10 11 34 PM](https://github.com/Expensify/App/assets/93399543/b7252cfd-5e25-4c3d-b9b7-875d806a6a54)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696349734344339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maxconnectAbhi** [comment] 2023-10-05 04:30
# Proposal

## Please re-state the problem that we are trying to solve in this issue
The strikethrough line of the link is displaying in white

## What is the root cause of that problem?
We don't use wrapper for links for MenuItem component.


The main problem that we don’t use <comment> tag for HTML in MenuItem now(This tag allows us to use special styles and features like bold font for links )

## What changes do you think we should make in order to solve the problem?
Need to make a <comment> wrapper around MenuItem title
(<comment> tag add special styles for links )

## What alternative solutions did you explore? (Optional)
NA

**Comment by maxconnectAbhi** [comment] 2023-10-05 05:55
# Proposal

## Please re-state the problem that we are trying to solve in this issue
The strikethrough line of the link is displaying in white

## What is the root cause of that problem?
Currently we are not using any wrapper for html links in MenuItem component.

## What changes do you think we should make in order to solve the problem?
Need to make a `<comment>` wrapper around MenuItem title like `convertToLTR(props.title);`
(`<comment>` tag add special styles for links )

## What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment] 2023-10-05 07:55
This will be handled in https://github.com/Expensify/App/issues/27812 where we'll be wrapping with `<comment>` tags.

**Comment by greg-schroeder** [comment] 2023-10-05 09:24
@jjcoffee any objection to just closing this in that case?

**Comment by jjcoffee** [comment] 2023-10-05 09:52
@greg-schroeder Happy to close!

**Closed** 2023-10-05 09:52 UTC
Labels: External, Daily, Help Wanted, Bug
