### ISSUE TITLE
[$250] Tag - Disabled "Region" not shown in confirmation page but displayed after creating expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45889] opened 2024-07-22 10:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751882
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: Admin -Have a workplace with tags enabled. Have a member invited as employee.
In old dot, upload dependant tags. ( Make sure to enable multiple level tags and uptick independent tags)
1. Launch app
2. Login as admin
3. Tap profile icon -- workspaces -- workspace
4. Tap tag - Region
5. Tap Name selector and disable all tags using above caret dropdown
6. In mweb, login as employee
7. Open workspace chat
8. Tap plus icon -- submit expense
9. Enter an amount and tap next
10. Enter merchant
11. Tap show more
12. Note "Region" field not displayed
13. Tap Submit
14. Open the newly created expense
15. Note "Region" option displayed

## Expected Result:
Disabled "Region" tag is not shown in confirmation page and so must not be displayed after creating distance.

## Actual Result:
Disabled "Region" tag is not shown in confirmation page but displayed after creating distance.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0a4fca84-b856-49ec-baeb-000fa4c5c90a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4446baaccd96a5f</li>
        <li>Upwork Job ID: 1821192541013893497</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103495103</li>
<li>FitseTLT | Contributor | 103495104</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by izarutskaya** [comment] 2024-07-22 10:27
We think this issue might be related to the  #vip-vsb

**Comment by FitseTLT** [comment] 2024-07-22 11:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Disabled "Region" not shown in confirmation page but displayed after creating expense

### What is the root cause of that problem?
We are not checking if there are enabled tags before displaying in `MoneyRequestView`.
### What changes do you think we should make in order to solve the problem?

We need to include a check we use in confirmation page like here
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-22 12:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Disabled "Region" not shown in confirmation page but displayed after creating expense

### What is the root cause of that problem?
We are not checking if there are enabled tags before displaying in `MoneyRequestView` as we do in confirmation
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449

### What changes do you think we should make in order to solve the problem?

We need to include a check we use in confirmation page like here
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449
We should first determine `shouldShowTag` by changing
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/ReportActionItem/MoneyRequestView.tsx#L363-L364
```
 const isMultilevelTags = useMemo(() => PolicyUtils.isMultiLevelTags(policyTagList), [policyTagList]);

    const tagList = policyTagLists.map(({name, orderWeight, tags}, index) => {
        const shouldShow = shouldShowTag && (!isMultilevelTags || OptionsListUtils.hasEnabledOptions(tags));

```
and only display the specific tag menu when the tag has an enabled tags otherwise return `null`
************
But if the transaction had a tag selected with the disabled tag type we might need to display the menu but disable the interactiveness, in that case we can disable interactiveness when `TransactionUtils.getTagForDisplay(transaction, index)` isEmpty and update the `shouldShowTag` so that it is true it is non empty
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-22 12:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Disabled "Region" not shown in confirmation page but displayed after creating expense

### What is the root cause of that problem?
We are not checking if there are enabled tags before displaying in `MoneyRequestView` as we do in confirmation
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449

### What changes do you think we should make in order to solve the problem?

We need to include a check we use in confirmation page like here
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449
We should first determine `shouldShowTag` by changing
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/ReportActionItem/MoneyRequestView.tsx#L363-L364
```
 const isMultilevelTags = useMemo(() => PolicyUtils.isMultiLevelTags(policyTagList), [policyTagList]);

    const tagList = policyTagLists.map(({name, orderWeight, tags}, index) => {
        const shouldShow = shouldShowTag && (!isMultilevelTags || OptionsListUtils.hasEnabledOptions(tags));

```
and only display the specific tag menu when the tag has an enabled tags otherwise return `null`
************
But if the transaction had a tag selected with the disabled multi-level tag type we might need to display the menu but disable the interactiveness, in that case we can disable interactiveness when `TransactionUtils.getTagForDisplay(transaction, index)` isEmpty and update the `shouldShowTag` so that it is true if it (transactionTag on the specific multi-level tag) is non empty
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-22 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - Disabled "Region" not shown in confirmation page but displayed after creating expense

### What is the root cause of that problem?
We are not checking if there are enabled tags before displaying in `MoneyRequestView` as we do in confirmation
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449

### What changes do you think we should make in order to solve the problem?

We need to include a check we use in confirmation page like here
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/MoneyRequestConfirmationListFooter.tsx#L448-L449
We should first determine `shouldShow` tag by changing
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/components/ReportActionItem/MoneyRequestView.tsx#L363-L364
```
 const isMultilevelTags = useMemo(() => PolicyUtils.isMultiLevelTags(policyTagList), [policyTagList]);

    const tagList = policyTagLists.map(({name, orderWeight, tags}, index) => {
        const shouldShow = shouldShowTag && (!isMultilevelTags || OptionsListUtils.hasEnabledOptions(tags));

```
and only display the specific tag menu when the tag has an enabled tags otherwise return `null`
************
But if the transaction had a tag selected with the disabled multi-level tag type we might need to display the menu but disable the interactiveness, in that case we can disable interactiveness when `TransactionUtils.getTagForDisplay(transaction, index)` isEmpty and update the `shouldShow` so that it is true if it (transactionTag on the specific multi-level tag) is non empty
```
        const shouldShow = shouldShowTag && (!isMultilevelTags || OptionsListUtils.hasEnabledOptions(tags) || !isEmpty(TransactionUtils.getTagForDisplay(transaction, index)));

```
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-08-07 14:31
Added to wave-collect as polish and opening up for reviews.

**Comment by trjExpensify** [comment] 2024-08-08 16:46
Looking at the OP, this issue confused me initially. The tester has configured **dependent multi-tags** on OldDot. We don't officially support that or manual configuration of multi-tags on NewDot collect. 

I was worried we were just going to hack solutions to fix bugs for dependent multi-tags and this should be in a #wave-control doc down the line to properly support them on that plan or something.

A more appropriate test for what's supported on collect in NewDot would be to: 

- Connect QBO 
- Import two levels of coding as tags
- Confirm they both show up on the confirmation page when submitting an expense on that workspace
- Disable all of the values on one of the imported tag lists
- Confirm the disabled level doesn't show on the confirmation page 
- Confirm the disabled level doesn't show on the created expense

Seems like we still have this bug, so it's not limited to handling dependent multi-tags, so that's good:

https://github.com/user-attachments/assets/d89fed92-ede0-43c2-b835-c190eee71e63

>I don't think we should make the field non-interactive in this case. We may want to allow the user to remove the tag value one last time

I agree with this. If there's a value selected, we shouldn't disable it or not show it. If they do deselect the selected value, then we can not show it. 👍

**Comment by JmillsExpensify** [comment] 2024-09-06 14:21
Payment summary:

 - Contributor: @FitseTLT $250
 - Reviewer: @paultsimura $250

**Comment by FitseTLT** [comment] 2024-10-11 17:49
@JmillsExpensify I think we can close this issue. 👍

**Comment by JmillsExpensify** [comment] 2024-10-14 08:40
Thanks, closing this one out.

**Closed by JmillsExpensify** 2024-10-14 08:40 UTC
Labels: Reviewing, External, Monthly, Bug
