### ISSUE TITLE
Web - Workspace settings - Unable to open Accounting page, loading spinner and error in console

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45766] opened 2024-07-19 12:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+ihchat4_1907_22@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Go to Account settings -> Workspace
4. Open any WS or create a new one
5. More future -> Enable Accounting
6. Open the Accounting page

## Expected Result:
Accounting page opens without any error

## Actual Result:
Unable to open Accounting page, loading spinner and error in console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ba0174df-4f5f-4616-a74c-bc413d4b477b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-19 12:32
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-19 12:33
We think that this bug might be related to #wave-collect - Release 1

**Comment by tsa321** [comment] 2024-07-19 16:55
Back end issue, the returned onyxData from `OpenPolicyAccountingPage`:

![ss-1](https://github.com/user-attachments/assets/722ffce5-77d2-40d8-a679-4a996482efa2)

The error is from here:

https://github.com/Expensify/App/blob/808b7c8bf9bd4e97fe8c4b0fbf373c9de8b5e9eb/src/libs/Middleware/HandleUnusedOptimisticID.ts#L21

**Comment by alexpensify** [comment] 2024-07-19 17:24
@thienlnam - Since this is a backend issue, should it be internal or external? Thanks for the update!

**Comment by aldo-expensify** [comment] 2024-07-19 17:30
> Back end issue, the returned onyxData from `OpenPolicyAccountingPage`:
> 
> ![ss-1](https://private-user-images.githubusercontent.com/114975543/350484660-722ffce5-77d2-40d8-a679-4a996482efa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTAyMDYsIm5iZiI6MTcyMTQwOTkwNiwicGF0aCI6Ii8xMTQ5NzU1NDMvMzUwNDg0NjYwLTcyMmZmY2U1LTc3ZDItNDBkOC1hNjc5LTRhOTk2NDgyZWZhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNzI1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmQyOGVmMjNhZTJjY2FmYWQ3YjAxNDYyNjRhYjI5MzI1NDU4YjZmNmI4MzYwZmRmMzJmZjI4NjJlMjE1Yjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MuXKyRoCj2ZELViQVSip8j4G4tJ1gFgxQD6EohmFGfk)


I think that is expected from the backend response, in the testing steps we don't get to the point where we connect to QBO (or any other integrations) so it is expected that `connections` is `null`

**Comment by aldo-expensify** [comment] 2024-07-19 17:31
This is not necessarily a backend problem, needs to be investigated first

**Comment by aldo-expensify** [comment] 2024-07-19 17:34
Doesn't seem to be a deploy blocker, I can reproduce in production:

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/e8109f25-08e5-4dcd-86c4-9b5bd34c7a58">

**Comment by aldo-expensify** [comment] 2024-07-19 17:34
Maybe it is some change in Auth? since it is happening in `staging` and `production`?

**Comment by tsa321** [comment] 2024-07-19 17:40
@aldo-expensify there is `onyxpdate` inside `onyxupdate`.

**Comment by aldo-expensify** [comment] 2024-07-19 17:47
ooh, that is a good catch, thanks, I'll look into that

**Comment by aldo-expensify** [comment] 2024-07-19 17:58
PR up: https://github.com/Expensify/Web-Expensify/pull/42819

**Comment by alexpensify** [comment] 2024-07-19 23:13
Thanks for the swift action @aldo-expensify!

**Comment by alexpensify** [comment] 2024-07-22 19:27
Keeping this one closed, no action is required on the BZ side and there is no payment. Everything was handled internally.

**Comment by alexpensify** [comment] 2024-07-25 23:39
@aldo-expensify - is this notice an error or do we need to come up with a plan to address it? Thanks!

**Comment by aldo-expensify** [comment] 2024-07-26 20:33
I believe this is being addressed in the GH issue where this was mentioned.

**Closed by aldo-expensify** 2024-07-26 20:33 UTC
Labels: Reviewing, Daily, Internal, Bug, DeployBlocker

**Comment by alexpensify** [comment] 2024-07-26 22:07
Thanks!
