### ISSUE TITLE
Contact Methods - Clicking Add button after writing the secondary contact does not take you to the next Step.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21486] opened 2023-06-24 11:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the Avatar
2. Go to Profile then Contact Methods
3. Click On New Contact Method
4. Enter your new contact and press Add.
5. Notice that clicking Add button does not take you to the next step but takes you back.

## Expected Result:
Clicking Add Button should take you to the next step with is to enter the magic code sent

## Actual Result:
Clicking Add Button takes you back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c9caa2c1-b281-4dac-b7b8-72d4e9e63ab8

https://github.com/Expensify/App/assets/93399543/cfde974e-69ab-493e-8a46-eaf06c5fb81f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686951685144829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2023-06-26 12:36
Just an additional note here - when you do add the contact you see this in your contact methods afterwards, but cannot click or cancel these, and `testingfornewdot@gmail.com` is a real email address that never received this email - 
<img width="412" alt="2023-06-26_13-32-52" src="https://github.com/Expensify/App/assets/62073721/339a6cc7-d6fb-4b63-80da-3e42e929d9aa">

**Comment by shawnborton** [comment] 2023-06-26 12:57
Hmm just for clarification - @Beamanator @cristipaval can you confirm if this is actually how we built this feature? If so, this isn't a bug and rather this would be a suggested improvement. But from what I can tell, this seems to be working as intended from the design doc.

**Comment by Beamanator** [comment] 2023-06-26 13:20
@shawnborton agreed - this is working how we built it

I see @kbecciv mentioned "Probably a new feature rather than bug" in Slack - I'm not sure we should have created the issue automatically 😅

**Comment by laurenreidexpensify** [comment] 2023-06-27 08:01
@Beamanator @cristipaval so good to close?

**Comment by Beamanator** [comment] 2023-06-27 08:04
Yes I'd say good to close

**Comment by Beamanator** [comment] 2023-06-28 09:47
Removing labels i think are not relevant

@laurenreidexpensify I wonder if we should make sure this test step is in Test Rail before closing? I am relatively sure @cristipaval  and I got most of these flows added to Test Rail but there's def a chance we missed any - but hopefully if we add them to test rail we won't accidentally consider them bugs in the future :D

**Comment by laurenreidexpensify** [comment] 2023-06-28 12:12
@Beamanator done!

**Closed by laurenreidexpensify** 2023-06-28 12:12 UTC
Labels: Daily, Bug
