### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] LHN popover - Desktop: 'Mark as unread' action for top chat has blank area to highlight

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44928] opened 2024-07-05 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

**Issue found when excuting PR** https://github.com/Expensify/App/pull/44519
## Action Performed:
Precondition: user is logged in desktop application.
1. LHN > top chat
2. Right mouse button click to display popover
3. Move cursor to 'Mark as unread' option and around it

## Expected Result:
When cursor cross edge between Pin/Unpin action and Mark as unread, the last on is highlighted

## Actual Result:
When cursor cross edge between Pin/Unpin action and Mark as unread, the last on is highlighted only if cursor pointed on text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1f1ca1c7-1841-430e-8920-8134a38858cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8144a4f008be2ea</li>
        <li>Upwork Job ID: 1810711799577959200</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103052551</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by bernhardoj** [comment] 2024-07-06 06:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The mark as unread action item isn't clickable when it's at the top of the screen.

### What is the root cause of that problem?
On the desktop, we have a drag area to mark that the element is draggable.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/web/index.html#L42-L46

In our case, the top bar area is draggable.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L41-L44

When the mark as unread action item is within the draggable area, the item won't receive a mouse event anymore. We already have a CSS as shown above to always disable the draggable of a pressable if it's the children of a draggable area, but in our case, the pressable is inside a popover.

This also happens to report context menu items.

### What changes do you think we should make in order to solve the problem?

Make the popover to be not draggable. We can apply `dataSet={{dragArea: false}}` to the popover container view.
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/src/components/PopoverWithoutOverlay/index.tsx#L121-L127

This will apply for all popover, but if we only want for the LHN and report context menu, then we can apply it to `PopoverReportActionContextMenu`.

_we can optionally do this for BaseModal too_

OR

Set all pressable to be non-draggable
https://github.com/Expensify/App/blob/c5eafd33463b2ba4c0ce2eb0c48261f66b085dc7/web/index.html#L45-L48

**Comment by trjExpensify** [comment] 2024-07-08 18:33
@fedirjh, looks like this is coming from https://github.com/Expensify/App/pull/44519 as a regression. Can you review the above please, and then we should assign the same peeps (you and Bernhard) to fix/review it.

**Comment by trjExpensify** [comment] 2024-07-09 16:44
Oh hm, the checklist that PR is closed, so it's on prod I believe. The automation probably failed.

**Comment by situchan** [comment] 2024-07-09 17:58
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/44928#issuecomment-2211683975) looks good to me.
I am fine to apply for only popover container view to avoid unexpected regressions.
🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-07-10 06:01
PR is ready

cc: @situchan

**Comment by bernhardoj** [comment] 2024-07-24 15:13
Payment is due today. Requested in ND.

**Comment by trjExpensify** [comment] 2024-07-24 17:25
Checklist time, @situchan.

**Comment by situchan** [comment] 2024-07-24 18:40
This is not regression but newly caught bug.

As desktop-only and minor bug, I don't think this is worth adding to regression test.

**Comment by trjExpensify** [comment] 2024-07-24 18:43
>This is not regression but newly caught bug.

What does that mean? 😅

**Comment by situchan** [comment] 2024-07-24 18:44
No offending PR I mean 😄

**Comment by trjExpensify** [comment] 2024-07-24 18:50
You're saying this bug has been there since we implemented this popover? 😕

**Comment by trjExpensify** [comment] 2024-07-24 18:54
Got it, so that's the offending PR isn't it?

**Comment by trjExpensify** [comment] 2024-07-24 18:57
Payment summary as follows: 

- $250 to @bernhardoj for the fix (requested via NewDot)
- $250 to @situchan for the review (paid via Upwork!)

Paid, closing!

**Closed by trjExpensify** 2024-07-24 18:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-26 00:42
$250 approved for @bernhardoj
