### ISSUE TITLE
[$500] mWeb-Conversation- Green line is shown creating request money in DM but not shown while split money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29376] opened 2023-10-11 20:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap on any 1:1 report
3. Tap plus icon and select request money
4. Enter amount and complete the request flow
5. Tap on IOU request created
6. Tap on header from link
7. Note the green line above IOU request created
8. Navigate back to LHN
9. Tap any group chat
10. Tap plus icon and select split bill
11. Enter an amount and complete split money
12. Tap on split money transaction
13. Navigate back to split money created page

## Expected Result:
A green line is shown on creating request money in DM but not shown while creating split money in group page and there should not be this inconsistent behaviour.

## Actual Result:
A green line is shown on creating request money in DM but not shown while creating split money in group page inconsistently.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/926b0277-6c33-464b-9566-5aacfde2719d

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd10227ee3f8eac1</li>
        <li>Upwork Job ID: 1712197891396800512</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

**Comment by teneeto** [comment] 2023-10-12 06:34
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by MonilBhavsar** [comment] 2023-10-13 06:30
Thanks! Following this and looking

**Comment by teneeto** [comment] 2023-10-13 08:52
Hi @MonilBhavsar, are you looking into this? or just following the progress 😉

**Comment by strepanier03** [comment] 2023-10-16 22:00
Finished testing, sorry for the delay on that. 

I'll let @MonilBhavsar weigh in, I'm not sure the plan there.

**Comment by teneeto** [comment] 2023-10-17 07:58
I'll drop a proposal on this, hopefully today

**Comment by MonilBhavsar** [comment] 2023-10-17 10:48
Teeneto sorry for confusion, If you have proposal, please share. Happy to manage the issue

**Comment by MonilBhavsar** [comment] 2023-10-19 12:48
Waiting for proposals here

**Comment by teneeto** [comment] 2023-10-20 04:24
Hi Monil, Apologies for the delay, There's just a little more check i need to do before posting a proposal here. I'll keep you posted as soon as I can. Thnaks

**Comment by MonilBhavsar** [comment] 2023-10-20 06:48
Thank you for the update!

**Comment by MonilBhavsar** [comment] 2023-10-23 08:16
Same, awaiting proposal

**Comment by teneeto** [comment] 2023-10-25 06:36
Hi Monil, again apologies, for the time delay on this, had to understand a few things about the flow with @gedu

**Comment by teneeto** [comment] 2023-10-25 06:43
@MonilBhavsar Before I drop a proposal here, there are two possible solutions to enforce consistency;
From the expected result of this issue, it isn't clear if we should allow `new` (the Unread Marker Indicator) for both `request money` and `split bill` or we should remove it?

**Comment by MonilBhavsar** [comment] 2023-10-25 06:47
The marker appearing while requesting money on the user who is requesting the money looks like a bug and we should remove it.
User creating an action/message should not see the marker

**Comment by MonilBhavsar** [comment] 2023-10-27 17:36
We're waiting for proposal here
@teneeto you might also want to confirm that the root cause of the issue is different from the issue that this PR fixes https://github.com/Expensify/App/pull/29860

**Comment by MonilBhavsar** [comment] 2023-10-30 12:37
Same^

**Comment by Santhosh-Sellavel** [comment] 2023-11-01 14:51
Waiting for proposal

**Comment by teneeto** [comment] 2023-11-02 09:33
Hey, I'm still working on this with help from @gedu.

**Comment by MonilBhavsar** [comment] 2023-11-03 14:47
Thanks! Feel free to post any questions here. Happy to help

**Comment by MonilBhavsar** [comment] 2023-11-06 09:28
Flagged over weekend, but awaiting proposal

**Comment by teneeto** [comment] 2023-11-08 10:10
Hi @MonilBhavsar, This needed some critical thoughts and considerations from my part and assistance from colleagues (@roksanaz and @gedu ) as well - really didn't seem to be a big deal at first, but have finally taken a lot of time, Apologies.

Here is my Findings so far - basically chopping from @roksanaz 😉!
I think there's not enough data to distinguish if the last request was made by the logged in person or the other person. The thing here is `Split Bill` and `Request Money` use distinct Previews and really not same since `request money` is more thread-like.
When you `Request Money`, you have all requests in a summary (report review) and each request isn't really displayed as a separate message, hence the inconsistency.
![Screenshot 2023-11-06 at 16 56 08](https://github.com/Expensify/App/assets/22779249/8f97599a-63ab-4cae-b436-17672d7ebf65)
_The summary message (kind of a thread thing, marked red on the screenshot) is a report review_

**Comment by MonilBhavsar** [comment] 2023-11-09 09:06
That's a great question!

> Don't show green line for report review at all

I don't think we should do this as Request Money is one of the core feature of the App and we want user to be notified or aware of new transaction is associated with IOU report

> Add the information about last IOU's author's on the BE side, so that FE can consume it and add a new condition to the shouldDisplayNewMarker method, something like:

I like this approach. I can look into this today and add that property 👍 

Thanks for looking!

**Comment by teneeto** [comment] 2023-11-09 10:20
Thank you @MonilBhavsar

**Comment by strepanier03** [comment] 2023-11-13 18:05
All good Melvin, things are moving forward.

**Comment by teneeto** [comment] 2023-11-15 08:59
Hi @MonilBhavsar, just a warm follow-up here. 😉

**Comment by MonilBhavsar** [comment] 2023-11-17 10:41
We discussed approach [internally](https://expensify.slack.com/archives/C03TQ48KC/p1700144165990249) and I hope to get this live by early next week

**Comment by MonilBhavsar** [comment] 2023-11-17 12:00
Adding Reviewing label as we need two PR's to be deployed in order

**Comment by teneeto** [comment] 2023-11-20 09:43
> internally

Ayye, nice... Although the link didn't work for me.

**Comment by MonilBhavsar** [comment] 2023-11-27 13:01
PR should be on staging tonight and we'll be able to test this proposal https://github.com/Expensify/App/issues/29376#issuecomment-1801509543

**Comment by MonilBhavsar** [comment] 2023-11-28 05:18
@teneeto On staging app, for money preview actions, you should be able to view `childLastActorAccountID` property in Onyx DB

**Comment by teneeto** [comment] 2023-11-28 08:32
Nice let me check and try it out, nice work @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-11-28 11:34
Awesome, thanks!! 😄 Let me know how it goes and If I could help

**Comment by MonilBhavsar** [comment] 2023-12-28 11:14
We can close this.  @Santhosh-Sellavel needs to be paid for C+ review. Are you paid through newDot?

**Comment by Santhosh-Sellavel** [comment] 2024-01-10 17:35
@strepanier03  Can I get a payment summary message?

**Comment by strepanier03** [comment] 2024-02-12 20:05
Payment Summary:

- C+ - @Santhosh-Sellavel = $500 via Manual Requests.

**Comment by strepanier03** [comment] 2024-02-12 20:07
Closing now. Thanks @Santhosh-Sellavel

**Closed by strepanier03** 2024-02-12 20:07 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-05-22 17:45
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-05-31 04:28
$50o approved for @Santhosh-Sellavel
