### ISSUE TITLE
[$250] [Held requests] Markdown isn't applied to the "Hold" message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37015] opened 2024-02-21 13:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Create an IOU in a chat
2. Put it on hold
3. Format the reason with markdowns

## Expected Result:
Markdown should be applied.

## Actual Result:
Markdown isn't applied to the "Hold" message.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6386836_1708519840035!img_1393](https://github.com/Expensify/App/assets/43996225/248693fb-f1aa-41d0-a21d-bf52b84eae1f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f83ef4d2ad62f49</li>
        <li>Upwork Job ID: 1760293330198360064</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-02-21 14:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Markdown isn't applied to the "Hold" message
### What is the root cause of that problem?
We do not pars hold comment
### What changes do you think we should make in order to solve the problem?
Update [comment](https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/libs/ReportUtils.ts#L3530C67-L3530C74)  with `getParsedComment(comment)`

### What alternative solutions did you explore? (Optional)

**Comment by flodnv** [comment] 2024-02-21 14:24
@BartoszGrajdek @MonilBhavsar @robertjchen I see you in https://github.com/Expensify/App/pull/33897, can you please have a look here?

**Comment by shahinyan11** [comment] 2024-02-21 14:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
1. Update the comment [here](https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/libs/ReportUtils.ts#L3530C67-L3530C74) and [here](https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/libs/actions/IOU.ts#L4004C13-L4004C20) with `getParsedComment(comment)`
2.  There need updates in backbend too . The hold action will not contain `html` key in `messages` and `originalMessage`
![Screenshot 2024-02-21 at 18 41 19](https://github.com/Expensify/App/assets/46921547/8d60a5d7-df9f-49d5-9c88-5e06c588ccbd)

### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2024-02-21 14:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On hold message not shown as HTML

### What is the root cause of that problem?

The message from description for HOLD reason is saved as simple string

### What changes do you think we should make in order to solve the problem?

There's 2 main areas that needs to be fixed.

### 1 - use ReportUtils.getParsedComment(comment) 
We need to save the message as parsed before passed to Onyx here
https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/libs/ReportUtils.ts#L3530

### 2- Use `<RenderHTML>` not `<Text>`

After adding the `ReportUtils.getParsedComment(comment)`  the UI will display the markdown as it it is, something like `<em> text </em>`, so we need to use RenderHTML component here
https://github.com/Expensify/App/blob/20ca041595e76cdd289977e55b2af3fbb9618868/src/pages/home/report/ReportActionItemFragment.tsx#L135-L144

**Comment by shahinyan11** [comment] 2024-02-21 15:15
## Proposal
[Updated](https://github.com/Expensify/App/issues/37015#issuecomment-1956809399)

**Comment by robertjchen** [comment] 2024-02-21 20:05
On hold, pending the splitting of the message in  #36979

**Comment by MonilBhavsar** [comment] 2024-02-26 11:54
Looks like Robert has got this issue

**Comment by abekkala** [comment] 2024-03-06 20:22
Not overdue, on hold.  Robert is working on this https://github.com/Expensify/App/issues/36979

**Comment by abekkala** [comment] 2024-03-15 19:00
not overdue - Robert is still working on this: https://github.com/Expensify/App/issues/36979#issuecomment-1999128350

**Comment by robertjchen** [comment] 2024-03-25 16:23
Off hold! 👍 Note that the hold message is now an independent message

**Comment by robertjchen** [comment] 2024-03-27 06:15
cc: @hoangzinh for proposal review, thanks!! 🙇

**Comment by shahinyan11** [comment] 2024-03-27 11:31
@dragnoir there are significant differences in our proposals . And, as you can see, in my proposal there is no mention of the `<RenderHTML>` component. I suggested using `RenderCommentHTML`

**Comment by robertjchen** [comment] 2024-03-28 06:13
Hm, the backend logs report that the `comment` field is missing when calling the `HoldRequest` API comand. Can you please try again on a fresh request with a comment when holding? 🤔

**Comment by robertjchen** [comment] 2024-04-01 02:42
Good question, I'll update the backend to return `HOLDCOMMENT` as well for consistency 🤔

**Comment by robertjchen** [comment] 2024-04-01 09:43
Actually, let's change the frontend to the `ADDCOMMENT` for now as there are many considerations on the backend 👍

**Comment by robertjchen** [comment] 2024-04-01 15:45
Thanks for the review, the backend change should be going out later today so we can proceed here 👍

**Comment by abekkala** [comment] 2024-04-08 13:33
Fix: @dragnoir 
PR Review: @hoangzinh 

PR not merged yet

**Comment by trjExpensify** [comment] 2024-05-21 20:26
I'm suggesting we close this issue, to reflect where we've landed in the PR. https://github.com/Expensify/App/issues/40408#issuecomment-2123384330 - any thoughts, comment there. CC: @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-05-21 21:29
Yes, agreed. Let's close.

**Comment by trjExpensify** [comment] 2024-05-21 23:08
Cool, thanks ya'll!

**Closed by trjExpensify** 2024-05-21 23:08 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
