### ISSUE TITLE
[HOLD for payment 2024-01-17] Web – Chat – Edit mode doesn’t open when Press ArrowUp in DM if delete message using keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33118] opened 2023-12-14 21:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Intenral Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to the conversation between user A and B in both devices
4. Send two messages to user B
5. As user A press ArrowUp in the DM. Verify that the last message user A sent in the chat enters edit mode
6. Delete all the text while editing the comment and press Enter
7. Press ArrowUp in the DM

## Expected Result:
The first message sent in step 4 enters edit mode

## Actual Result:
Focus is losted. Nothing happenes. Last message edit mode doesn’t open when Press ArrowUp in the DM if delete the previous message using keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c49d0ffc-531e-487f-a537-3b22628a08a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-12-14 23:27
This is regression from #32474
@tylerkaraszewski if we end up reverting approach, feel free to merge #33133 since it's straight revert

**Comment by Julesssss** [comment] 2023-12-15 09:04
I can reproduce but this is only occuring on web/desktop and is a minor issue. Removing blocker label

**Comment by situchan** [comment] 2023-12-15 10:04
@s-alves10 can you please handle this as regression?

**Comment by s-alves10** [comment] 2023-12-15 10:06
@situchan Yes, I'll

**Comment by MonilBhavsar** [comment] 2023-12-15 11:09
@s-alves10 thanks! If you don't mind, should I assign this issue to you?

**Comment by s-alves10** [comment] 2023-12-15 11:37
yes

**Comment by s-alves10** [comment] 2023-12-15 11:57
@dukenv0307 

> This is regression from this PR #32474 which makes composer doesn't re-focus after deleting the message

What do you think is the root cause of not-focusing? Can you make it more clear?

**Comment by s-alves10** [comment] 2023-12-15 13:47
@MonilBhavsar 

PR is ready for review https://github.com/Expensify/App/pull/33162

**Comment by situchan** [comment] 2024-01-17 12:57
Please assign me here for [PR](https://github.com/Expensify/App/pull/33162) review

**Comment by MonilBhavsar** [comment] 2024-01-17 13:16
There was a suspicion that PR linked to this issue has caused a regression https://github.com/Expensify/App/issues/34419
@s-alves10 @situchan anyone of you can please confirm, thank you!

**Comment by situchan** [comment] 2024-01-17 13:32
> There was a suspicion that PR linked to this issue has caused a regression #34419 @s-alves10 @situchan anyone of you can please confirm, thank you!

Straight revert failing so not able to confirm. But I don't think so as [this](https://github.com/Expensify/App/pull/33162/files#r1441649964) was the actual fix and other codes are just revert of previous PR.

**Comment by jliexpensify** [comment] 2024-01-17 22:05
@MonilBhavsar @tylerkaraszewski just to confirm, there's no regression here right?

Here's a payment summary for everyone's review:

- Contributor: @s-alves10 $500
- C+: @situchan

**Comment by situchan** [comment] 2024-01-18 03:43
> are you meant to be hired or are you just reviewing the PR?

This is follow-up of https://github.com/Expensify/App/issues/31637.
The work is done already and I reviewed 2nd [PR](https://github.com/Expensify/App/pull/33162).
@s-alves10's was already fully paid [here](https://github.com/Expensify/App/issues/31637#issuecomment-1895753806) for the work of first [PR](https://github.com/Expensify/App/pull/32474).

**Comment by jliexpensify** [comment] 2024-01-18 04:39
Oh hmm...so to clarify: I don't need to pay anyone?

**Comment by situchan** [comment] 2024-01-18 04:40
I am still eligible based on `I was not involved in first PR which caused this regression`

**Comment by jliexpensify** [comment] 2024-01-18 04:46
Thanks for clearing this up, I will withdraw the offer for Sangar and hire you @situchan

**Comment by jliexpensify** [comment] 2024-01-18 05:29
Paid and job closed.

**Closed** 2024-01-18 05:29 UTC
Labels: Engineering, Daily, Awaiting Payment
