### ISSUE TITLE
[$250] [HOLD for payment 2024-08-19] [Search v2.1] [App] Create Currency filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46031] opened 2024-07-23 15:13 UTC
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Currency filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight / @sonialiap</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01779f92052196d8af</li>
        <li>Upwork Job ID: 1826031089726034388</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103610903</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by garrettmknight** [comment] 2024-07-24 19:56
@sonialiap will pick this back up when I'm back from OOO, thanks for your help in the meantime!

**Comment by WojtekBoman** [comment] 2024-07-30 15:29
@sonialiap I was focused on fixing all the issues in the Create Search Results page issue , now I'm starting to work on that :)

**Comment by garrettmknight** [comment] 2024-08-07 09:45
@sonialiap just a note that I'll pick this one back up!

**Comment by garrettmknight** [comment] 2024-08-13 16:47
@luacmartins I didn't notice any currency specific filter test in the manual tests for this project. Did I miss them or should we add a regression test here?

**Comment by luacmartins** [comment] 2024-08-13 17:50
This feature is still WIP, so we'll add them as part of the project wrap up.

**Comment by garrettmknight** [comment] 2024-08-14 09:17
Cool - closing then!

**Comment by ikevin127** [comment] 2024-08-20 18:32
@garrettmknight I just checked Upwork and looks like I wasn't paid for [reviewing](https://github.com/Expensify/App/pull/46566#issuecomment-2266037225) the PR for this issue.

**Comment by garrettmknight** [comment] 2024-08-20 22:58
Let's fix that.

**Comment by garrettmknight** [comment] 2024-08-20 22:59
Accept the offer and I'll pay!

**Comment by ikevin127** [comment] 2024-08-20 23:01
Offer accepted, thanks Garrett 💯

**Comment by ikevin127** [comment] 2024-08-21 17:59
@garrettmknight Offer accepted ✅

**Comment by garrettmknight** [comment] 2024-08-21 21:16
Sweet - all paid up!

**Closed by garrettmknight** 2024-08-21 21:16 UTC
Labels: External, Daily, NewFeature
