### ISSUE TITLE
[$250] Close Account - Secondary device is not redirected to the Sign in page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50271] opened 2024-10-04 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5039450
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: It's needed to have almost two devices open, logged in to the same account.
In the Main device:
1. Go to Settings > Security > Close Account
2. Fill out the form, then click/tap "Close Account"

## Expected Result:
In the Secondary device:
The app is automatically redirected to the Sign in page.

## Actual Result:
In the Secondary device:
The app is not automatically redirected to the Sign in page
The app is redirected to the Sign in page when the user performs any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/48111058-4c1b-47cb-9f30-ede7d3eec868

https://github.com/user-attachments/assets/07c38c95-230a-4f3e-90fc-5bd199631684

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843395990235798003</li>
        <li>Upwork Job ID: 1843395990235798003</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-10-04 19:48
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-10-07 21:00
Can replicate. Is this some kind of regression? I had to update my app to introduce this bug.

**Comment by truph01** [comment] 2024-10-08 09:07
I think it is BE bug. After closing account in device A, there is no pusher message sent to device B.

**Comment by rezkiy37** [comment] 2024-10-09 09:18
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-10-09 11:47
I've investigated the problem and analyzed the network and logs. I can confirm that the **Pusher** did not inform the second device once I closed the account on the first device. So it requires some improvement on the backend side. However, the app does not handle the `407` status code, or the session expiration by the **Pusher** now. We can add one more new event type ([Pusher/EventType.ts](https://github.com/Expensify/App/blob/main/src/libs/Pusher/EventType.ts)) and integrate a subscription on the newly added event type.

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/1de7f457-9db4-4675-8d08-943bae4bc500

</p>
</details>

**Comment by RachCHopkins** [comment] 2024-10-14 04:51
@rushatgabhane is this Internal?

**Comment by rezkiy37** [comment] 2024-10-14 09:02
Yes, it is. https://github.com/Expensify/App/issues/50271#issuecomment-2402097853

**Comment by RachCHopkins** [comment] 2024-10-16 04:24
Thanks @rezkiy37 for confirming!!

**Comment by RachCHopkins** [comment] 2024-10-16 20:33
Not overdue, Internal.

**Comment by RachCHopkins** [comment] 2024-10-29 05:02
Internal - will follow up tomorrow

**Comment by RachCHopkins** [comment] 2024-10-30 03:23
Ok, going by @muttmuure's rubric [here](https://expensify.slack.com/archives/C05LX9D6E07/p1730121010343569?thread_ts=1729777525.733069&cid=C05LX9D6E07) I would venture that this is at the Low end of the Medium priority.

Matt, given that this is an odd behaviour for people closing accounts, (i.e. not people opening new accounts and becoming customers), do you think we should close this? Surely anyone who closed their account is not going to care that their secondary device took a beat to log out.

**Comment by RachCHopkins** [comment] 2024-11-11 22:51
Ok closing this due to lask of interest in fixing.

**Closed by RachCHopkins** 2024-11-11 22:51 UTC
Labels: Weekly, Internal, Overdue, Bug, Hot Pick
