### ISSUE TITLE
[$250] [HOLD for payment 2024-09-23] [Search v2.3] - App crashes after saving search with user and clear cache and restart

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49249] opened 2024-09-16 09:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+dfjdfer@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search > Chats.
3. Click Filters.
4. Click From.
5. Select any user.
6. Click Save search.
7. Go to Account settings > Troubleshoot > Clear cache and restart.
8. Click Reset and refresh.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[1609.txt](https://github.com/user-attachments/files/17011078/1609.txt)

https://github.com/user-attachments/assets/ddab9d9c-85f0-4e3a-8b99-888458817580

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838824379471456613</li>
        <li>Upwork Job ID: 1838824379471456613</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 09:55
We think that this bug might be related to #wave-control

**Comment by nkdengineer** [comment] 2024-09-16 10:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes.

### What is the root cause of that problem?
`personalDetails` is `undefined` after we reset cache and restart.


https://github.com/Expensify/App/blob/b00b9bc8afaa0c359ff7526f4990e81866e8499d/src/libs/SearchUtils.ts#L702


### What changes do you think we should make in order to solve the problem?
Safely get the data here

```
return PersonalDetailsUtils.createDisplayName(personalDetails?.[filter]?.login ?? '', personalDetails[filter]); 

```
https://github.com/Expensify/App/blob/b00b9bc8afaa0c359ff7526f4990e81866e8499d/src/libs/SearchUtils.ts#L702

Or we can set the default value of `personalDetails` as empty object.
### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment] 2024-09-16 10:13
It might be related to this PR https://github.com/Expensify/App/pull/48566

**Comment by techievivek** [comment] 2024-09-16 10:21
I’ll assign this to @lakchote, as it’s related to the search feature. He can decide whether to pass this to external or handle all these minor bugs in a single PR.

**Comment by lakchote** [comment] 2024-09-16 10:35
@nkdengineer can you work on this quickly?

**Comment by huult** [comment] 2024-09-16 10:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes after saving search with user and clear cache and restart

### What is the root cause of that problem?

`personalDetails` returns `undefined` due to the data being cleared in storage.
https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/components/Search/SearchPageHeader.tsx#L132-L132
and error occurs when getting data at [this line](https://github.com/Expensify/App/blob/main/src/libs/SearchUtils.ts#L702).
https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/libs/SearchUtils.ts#L702

### What changes do you think we should make in order to solve the problem?

We set the value `EMPTY_OBJECT` for `personalDetails`.

```diff
// .src/components/Search/SearchPageHeader.tsx#L132
- const personalDetails = usePersonalDetails();
+ const personalDetails = usePersonalDetails() || CONST.EMPTY_OBJECT;
```

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-09-16 10:48
@lakchote Sure.

**Comment by ChavdaSachin** [comment] 2024-09-16 10:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- App crashes after saving search with user and clear cache and restart

### What is the root cause of that problem?
- `cardList` passed here is emptyObject after clearing cache and restart
https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/libs/SearchUtils.ts#L700-L711
- and we are not making use of optional chaining for `cardList`

### What changes do you think we should make in order to solve the problem?
- Make use of optional chaining while reading data from `cardList`
```js
        return cardList?.[filter].bank;
```
https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/libs/SearchUtils.ts#L705


### What alternative solutions did you explore? (Optional)

**Comment by ChavdaSachin** [comment] 2024-09-16 10:55
@lakchote I am afraid @nkdengineer's RCA is wrong for the matter please take I look at my [proposal](https://github.com/Expensify/App/issues/49249#issuecomment-2352588375) I have checked my solution solves the problem.

**Comment by nkdengineer** [comment] 2024-09-16 11:00
Here is the crash log. cc @lakchote 

https://github.com/user-attachments/assets/b1936fc2-2ea4-458b-9f2f-3e61f99b2efd

**Comment by lakchote** [comment] 2024-09-16 11:01
@nkdengineer can you post a video on how your solution fixes it?

**Comment by nkdengineer** [comment] 2024-09-16 11:04
@lakchote The result here.

https://github.com/user-attachments/assets/0aa6c961-c091-4055-81ab-d61b9c7878f5

**Comment by lakchote** [comment] 2024-09-16 11:05
Assigning you @nkdengineer since you were the first to suggest this solution. Please raise a PR as soon as possible, thanks!

**Comment by nkdengineer** [comment] 2024-09-16 11:06
@lakchote The PR is [here](https://github.com/Expensify/App/pull/49258).

**Comment by lakchote** [comment] 2024-09-16 12:50
It isn't a blocker anymore see:
https://github.com/Expensify/App/pull/49258#issuecomment-2352770665

**Comment by techievivek** [comment] 2024-09-17 06:06
Oops, I was supposed to unassign myself but I unassigned Kadie. Going to add Kadie as BZ member on the GH.

**Comment by lakchote** [comment] 2024-10-01 07:48
Bump for payment @kadiealexander

**Comment by kadiealexander** [comment] 2024-10-03 01:08
Let me know when you've accepted it please.

**Comment by DylanDylann** [comment] 2024-10-04 04:10
@lakchote @kadiealexander I reviewed the [PR](https://github.com/Expensify/App/pull/49258). Please assign me to this issue and also help to process payment for me. Thanks

**Comment by nkdengineer** [comment] 2024-10-04 14:52
> Let me know when you've accepted it please.

@kadiealexander I just accepted 👍

**Comment by DylanDylann** [comment] 2024-10-07 02:52
@kadiealexander could you also kindly take care of the payment for me? since I've already reviewed the PR. Thanks so much! 🙏

cc @lakchote

**Comment by kadiealexander** [comment] 2024-10-07 21:05
@DylanDylann please apply via

**Comment by DylanDylann** [comment] 2024-10-08 08:31
@kadiealexander I accepted 👍

**Closed** 2024-10-08 22:27 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
