### ISSUE TITLE
Mac OS-  cannot use cmd+shift+v shortcut to paste

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23830] opened 2023-07-28 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. copy some text to your clipboard from slack for example
2. go to new dot and try to paste with cmd+shift+v
## Expected Result:
contents of clipboard should paste without any formatting
## Actual Result:
nothing is pasted
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/caf87fc1-4a2f-41b9-9dab-42aeeb856847

https://github.com/Expensify/App/assets/43996225/4d362aa0-5b10-41ea-bc7a-b55190ab8393

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bondydaa 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690472500500579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-29 07:03
Dupe of https://github.com/Expensify/App/issues/23567

**Comment by twisterdotcom** [comment] 2023-07-31 08:27
Closing as a duplicate: https://github.com/Expensify/App/issues/23830#issuecomment-1656580574

**Closed by twisterdotcom** 2023-07-31 08:27 UTC
Labels: Daily, Overdue, Bug

**Comment by bondydaa** [comment] 2023-08-03 17:21
oh whoopsies thanks Ted!
