### ISSUE TITLE
[QBO] "must categorize all expenses" toggle is off and Tags are not imported

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41844] opened 2024-05-08 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**Found when validating PR :** https://github.com/Expensify/App/pull/41513
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Log into New Expensify using an account that is on the accounting beta list

1. Go to categories page. Check that you see default categories
2. Go to More Features page > Enable Tags feature
3. Go to Tags page. Check that you see nothing
4. Create a tag. Make sure you see the newly created tag.
5. Go to workspace settings page -> More Features -> Enable Accounting
6. Go to Accounting page -> Connect to QBO
7. Go to the Categories page and check that you see the imported categories > Click Settings button the categories page
8. Go to to the Accounting page -> Import
9. Go to the Tags

## Expected Result:
Step 7. "must categorize all expenses" toggle is on
Step 8. Customers (or locations or classes) are imported as tags
Step 9. You see some tags (you should not see the tag you created before)

## Actual Result:
Step 7. "must categorize all expenses" toggle is off and locked
Step 8. Customers (or locations or classes) are Not imported
Step 9. You see the tag you created on step 4

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1c873506-e062-4cd5-ac14-bf12b3d2cded

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-08 13:00
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by youssef-lr** [comment] 2024-05-08 21:14
cc @hayata-suenaga @aldo-expensify, is this a blocker? taking a look at the code it seems expected here that the toggle will be disable if we're connected to an accounting system https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/workspace/categories/WorkspaceCategoriesSettingsPage.tsx#L51

**Comment by marcaaron** [comment] 2024-05-08 21:36
I think the QBO stuff is behind a beta, no? Let's remove the blocker.

**Comment by hayata-suenaga** [comment] 2024-05-09 16:10
I tried to reproduce the three issues reported here, but I couldn't.

> Step 7. "must categorize all expenses" toggle is off and locked

The toggle is on and locked as expected.
<img width="200" alt="Screenshot 2024-05-09 at 8 55 07 AM" src="https://github.com/Expensify/App/assets/98560306/857be234-1adf-4481-b776-fce62611c773">

> Step 8. Customers (or locations or classes) are Not imported

The classes and customers are imported as expected.
<img width="200" alt="Screenshot 2024-05-09 at 8 59 15 AM" src="https://github.com/Expensify/App/assets/98560306/2f5103d8-b3c3-4e71-94af-8172294bec2c">

> Step 9. You see the tag you created on step 4

I couldn't see the tag I manually created after connecting to accounting software
<img width="200" alt="Screenshot 2024-05-09 at 9 02 12 AM" src="https://github.com/Expensify/App/assets/98560306/d1bafdd6-e7ff-4cc7-a507-569c5f39435d">

<img width="200" alt="Screenshot 2024-05-09 at 9 08 01 AM" src="https://github.com/Expensify/App/assets/98560306/f89cf32c-2cdc-4f6f-952c-b1e126e7e797">

**Comment by kavimuru** [comment] 2024-05-09 19:37
The bug is partly fixed. The toggle part is still repro ('Members must categorize all spend' toggle still off and locked)

https://github.com/Expensify/App/assets/43996225/d661a78e-4add-4f7e-a588-a4a741376530

**Comment by hayata-suenaga** [comment] 2024-05-09 22:50
@kavimuru 

I just realized that when you click Settings button on the Tags page, the Not-Found page is displayed for a while. Is this issue being tracked somewhere else?

<img width="1024" alt="Screenshot 2024-05-09 at 3 49 06 PM" src="https://github.com/Expensify/App/assets/98560306/57f66ba5-b5cb-4477-b889-543e03182fbe">

**Comment by trjExpensify** [comment] 2024-05-10 16:06
On Tags import:

1. Support for MultiTags import isn't done yet and I think that's probably messing up importing and displaying the tag lists imported: https://github.com/Expensify/App/pull/41351
2. The `Tags` menu item isn't appearing in the LHN when you connect to QBO, but it should be because `Customers` and `Classes` are imported by default. @hayata-suenaga @aldo-expensify I feel like I've asked about this in a number of places really, but it would be good to nail down where it's being taken care.  

As for the required categories toggle, I can't repro that: 

![Image](https://github.com/Expensify/App/assets/16232057/3bf7dd9e-58b6-4178-b87c-4ccb99fd8f92)

**Comment by hayata-suenaga** [comment] 2024-05-10 18:33
> The Tags menu item isn't appearing in the LHN when you connect to QBO, but it should be because Customers and Classes are imported by default. @hayata-suenaga @aldo-expensify I feel like I've asked about this in a number of places really, but it would be good to nail down where it's being taken care.

@aldo-expensify, could you confirm that, [in this issue](https://github.com/Expensify/Expensify/issues/390731), you accounted for the situation when the default configuration already satisfies the condition below:

> [DONE] When the admin choose to import Classes, Customers/Projects, or Locations, enable the Tags feature on the backend so that these entities can be imported as tags to New Expensify.

**Comment by hayata-suenaga** [comment] 2024-05-10 18:38
For [the bug](https://github.com/Expensify/App/issues/41844#issuecomment-2103566771) (somewhat unrelated) I found while reproducing the original issue, [the issue is apparently hard to reproduce.](https://expensify.slack.com/archives/C9YU7BX5M/p1715355326552549?thread_ts=1715295102.850659&cid=C9YU7BX5M)

It might have been the result of the backend fire this week. Please let me know if you encounter this issue (Not found page briefly displayed after a while) again.

**Comment by aldo-expensify** [comment] 2024-05-10 18:51
>> The Tags menu item isn't appearing in the LHN when you connect to QBO, but it should be because Customers and Classes are imported by default. @hayata-suenaga @aldo-expensify I feel like I've asked about this in a number of places really, but it would be good to nail down where it's being taken care.

> @aldo-expensify, could you confirm that, https://github.com/Expensify/Expensify/issues/390731, you accounted for the situation when the default configuration already satisfies the condition below:

ohh, I think initial case was not covered because I added that logic to the Auth command `UpdatePolicyConnectionConfiguration`, and that command is not used until the user start changing settings manually.

I think we can fix this here: https://github.com/Expensify/Web-Expensify/pull/41908

**Comment by aldo-expensify** [comment] 2024-05-10 19:43
Testing again, I don't see that "Customers and Classes are imported by default". Do we need to correct our defaults?

<img width="482" alt="image" src="https://github.com/Expensify/App/assets/87341702/3fb3d489-953e-43e7-8884-ab3343a5a191">

**Comment by trjExpensify** [comment] 2024-05-13 13:01
>We do enable Classes. Customer/Projects and Locations to be imported by default.

Just to confirm on this.. in OldDot, we enable `Classes` & `Customer/Projects` by default, but not `Locations`. We should maintain that consistency, is that what you're saying?

**Comment by trjExpensify** [comment] 2024-05-13 13:01
>I think we can fix this here: https://github.com/Expensify/Web-Expensify/pull/41908

Also, nice! Looking forward to getting that one fixed 👍

**Comment by aldo-expensify** [comment] 2024-05-13 17:58
> > We do enable Classes. Customer/Projects and Locations to be imported by default.
> 
> Just to confirm on this.. in OldDot, we enable `Classes` & `Customer/Projects` by default, but not `Locations`. We should maintain that consistency, is that what you're saying?

Yes, I made a mistake, `Locations` is not enabled by default

**Comment by trjExpensify** [comment] 2024-05-14 09:47
Sounds good!

**Comment by youssef-lr** [comment] 2024-05-15 01:35
Not overude. A fix has been merged

**Comment by jliexpensify** [comment] 2024-05-19 22:43
Looks like this was deployed, @youssef-lr should we close this, or did you want Applause to re-test?

**Comment by youssef-lr** [comment] 2024-05-20 07:57
@jliexpensify it's only been deployed to staging, we can close once it hits production.

**Comment by jliexpensify** [comment] 2024-05-20 09:21
Ah yes, you're correct - apologies!

**Comment by jliexpensify** [comment] 2024-05-22 22:41
This one just hit production, so closing it out!

**Closed by jliexpensify** 2024-05-22 22:41 UTC
Labels: Engineering, Daily, Overdue, Bug
