### ISSUE TITLE
Wrapping Text inside Tooltip or Pressable make the text vertically misaligned on native - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9242] opened 2022-05-31 04:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to ReportWelcomText.js file
2. Wrap the Text inside Tooltip or Pressable
https://github.com/Expensify/App/blob/ffe26f9e95753823dbcce9900dc73644d97fa89a/src/components/ReportWelcomeText.js#L122-L124
3. Open a chat with someone and check the welcome message

## Expected Result:
It shouldn't get misaligned

## Actual Result:
It gets misaligned

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 
**Reproducible in staging?:** need repro 
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Simulator Screen Shot - iPhone 13 - 2022-04-28 at 00 03 17](https://user-images.githubusercontent.com/43995119/171092216-7f996d42-0f73-48bd-80d8-2b171e6e6d47.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651084914620279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment] 2022-05-31 13:41
@chiragsalian, do we wanna fix this for pressable as we already handled the case for tooltip?

**Comment by sakluger** [comment] 2022-06-01 20:35
I can't reproduce this by starting a new group chat on mobile:

![image](https://user-images.githubusercontent.com/5997400/171496642-62ecc1ee-6b3e-4d10-adcd-3d58db46ca88.png)


@mvtglobally when would this scenario happen in real life?

**Comment by chiragsalian** [comment] 2022-06-02 17:35
I'm also unable to reproduce on dev, staging or production.
I don't get the action steps nor why would we need to do that, if we modify code there is a high chance things won't work as expected. If there is a reason to modify the code then the place where the code is modified should address fixing this alignment. 

> do we wanna fix this for pressable as we already handled the case for tooltip?

@Tushu17, for my understanding whats the benefit on `Pressable onPress={()` versus `Text onPress={()`?

**Comment by Tushu17** [comment] 2022-06-03 08:29
In a PR earlier we were facing problem when we tried wrapping the text inside pressable or tooltip so you asked us([here](https://github.com/Expensify/App/pull/8409#issuecomment-1108926383)) to report it on slack but we have already found a solution and wrapping text inside tooltlip works fine so I don't think we need it.

**Comment by chiragsalian** [comment] 2022-06-07 22:40
Ah cool cool, yeah i think when you earlier mentioned it i thought it was a bug on staging/prod. Since a solution was found we don't need this issue and we can close it out, correct?

**Comment by sakluger** [comment] 2022-06-08 20:44
Yeah I'm going to close. @mvtglobally could you please reopen if we still need it and let us know what still needs to be fixed? Thanks!

**Closed by sakluger** 2022-06-08 20:44 UTC
Labels: Daily, Needs Reproduction, Overdue
