### ISSUE TITLE
[HOLD #20908] [$1000] Dev: Android - When returning from a thread to the main chat and clicking on the back button, the thread message is opened again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21214] opened 2023-06-21 14:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Click on "Reply in thread"
4. Click on "From user1"
5. Return to the main chat
6. Click on the back button from main chat

## Expected Result:
Clicking the back button from the main chat should navigate back to the main page

## Actual Result:
When returning from a thread to the main chat and clicking on the back button, the thread message is opened again instead of going back to the main page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.27-6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5cf16182-d2e1-4b00-92af-997370d28f21

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686745578325549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d085ef1fee5c5db</li>
        <li>Upwork Job ID: 1673308483340644352</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-06-22 12:03
So watching the video, I'm not sure if this is actually a bug. When clicking on "From Progress" (the name of the chat) in the header, it would make sense to bring you back to that chat. 

I guess I don't see how this is a bug, as it looks like it is working as intended.

**Comment by ayazhussain79** [comment] 2023-06-22 12:16
When you want to go to chat history you need to press back button 3,4 times to go there.
When you click on the "From" link you will go to the main chat then when you press the back button from the main chat you should go to the chat history.

**Comment by CortneyOfstad** [comment] 2023-06-26 12:33
Oooh! Sorry for the confusion on my part! I was able to recreate this on my end, and experienced the additional 3-4 clicks to get back to the full chat list. 

Going to get eyes on this!

**Comment by Julesssss** [comment] 2023-06-26 12:45
I agree this seems like a navigation hierachy bug. On Android wqe should not be able to infinatley add pages to our hierachy. Tapping 'From progress' should pop the current page, not add a new one to the stack

**Comment by Julesssss** [comment] 2023-06-29 09:08
Not overdue. we're awaiting proposals.

**Comment by CortneyOfstad** [comment] 2023-06-29 12:28
Not overdue, still waiting for proposals

**Comment by CortneyOfstad** [comment] 2023-06-30 19:37
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by Julesssss** [comment] 2023-07-03 07:33
@CortneyOfstad maybe we should think about doubling the bounty here?

**Comment by Julesssss** [comment] 2023-07-05 08:04
@abdulrahuman5196 please take a look at this proposal. It looks good to me

**Comment by abdulrahuman5196** [comment] 2023-07-05 17:24
@Nodebrute From this proposal here https://github.com/Expensify/App/issues/21214#issuecomment-1620664217,

Its only fixing button press on the navigation header. But if we use the hardware back button the issue still exists.

cc: @Julesssss

**Comment by mountiny** [comment] 2023-07-06 03:13
@WoLewicki @adamgrzybowski could you check the proposal from @Nodebrute?

I believe we want to avoid making that navigate method too bloated and complicated. If there would be some easier way how to solve this that would be great.

**Comment by Julesssss** [comment] 2023-07-06 10:47
> This means that no matter how deep we are in the stack, we will always be redirected to the main screen. 

I don't think this is quite the expected behaviour. We still want a multi-level navigational hierachy, so pressing back from a thread should take you up one level to the chat, rather than up 2 levels to the LHN.

`LHN > Chat > Thread > Expense`
1 > 2 > 3 > 4

`back` 
1 > 2 > 3

`back`
1 > 2

`back`
1

**Comment by adamgrzybowski** [comment] 2023-07-06 12:27
Hey, let's clarify the expected behavior.

Currently, we are pushing every chat even if it is already on the stack.

e.g. imagine chats with deeplinks 
`A -> B -> A`
In that case, the stack should be A, B, A
Same for clicking `A -> B -> A` on the sidebar. 

But for threads, we want to go back to the chat if it's already on the stack. So it would be 

`A -> Athread - the "from" button >  A`
And now there should be only A on the stack?

What if the chat under the "from" is more than one back away from the thread screen?

e.g. `A -> B -> Athread - the “from” button >` and what now? Should we go to pop all the way to A or just push another A?

Also, what if the user opened a thread first 
`Athread - the "from" button > A`
Maybe in that case we should do a replace so the user can't go back to the thread by pressing the browser back button

**Comment by Julesssss** [comment] 2023-07-06 12:30
Ah yeah good point, deep linking is the special case here.

**Comment by adamgrzybowski** [comment] 2023-07-06 12:39
So essentially I think that what is happening now is expected general behavior for chats but if we want to deal with threads in some specific way to improve UX we can do it. 

However, I would avoid doing it by adding more ifs in the `navigate` function if it's only for threads. There is no reason to create additional dependency on the structure of the app if not necessary.

**Comment by abdulrahuman5196** [comment] 2023-07-06 13:21
@adamgrzybowski Just thinking out load.,
What if, In case of "From A" header pressed in thread, Maybe we can pop the threadA screen from the stack if the previous screen is A?

If A-> threadA -> A it will become A
if A -> B -> threadA -> A there won't be any change. same for different combination.

It seems to be pretty annoying experience IMO when we use the From header and try to return back to the LHN.

**Comment by mountiny** [comment] 2023-07-06 20:50
I agree with the behaviour suggested by @WoLewicki and @adamgrzybowski

**Comment by Julesssss** [comment] 2023-07-07 09:33
> But for threads, we want to go back to the chat if it's already on the stack. So it would be

I think we're on the same page here, but just to be sure does the following align with this statement? 

- If the user's path was `LHN > Chat > Thread`, after pressing back their nav stack would now be `LHN > Chat`
- If they had deep-linked to the thread via `LHN > Chat > ThreadA > ThreadB`, after pressing back their new nav stack would be `LHN > Chat > ThreadA`

**Comment by mountiny** [comment] 2023-07-07 23:05
Maybe we should bring this to slack with some examples in the app, its hard to exactly imagine thee just in text like this

**Comment by mountiny** [comment] 2023-07-08 23:06
I think this sounds good to me, if Jules agree we could go ahead with this i guess.

I will let you guys handle this now, tag me if needed thanks for discussion 🙏

**Comment by WoLewicki** [comment] 2023-07-10 14:07
Hmm I mean we could do a `reset` action then probably, but it often ends up with some weird behaviors of browser back/forward buttons. Still, we can try that solution. 

On the other hand, the `replace` action is more predictable from the navigation's point of view and we already push all chats on the stack, so you can navigate between 2 reports all the time and have them pushed many many times on your stack.

**Comment by Julesssss** [comment] 2023-07-10 14:39
It almost sounds like we're limited here by React Navigation functionality here. Is that correct, or am I reading too much into the `reset` vs `replace` actions?  

I'm mostly speaking for native Android navigation here, but resetting/clearing the navigation stack is more aligned with native mobile navigation IMO. The resoning being that deep links should [simulate manual navigation](https://developer.android.com/guide/navigation/principles#deep-link). 

> When deep linking to a destination within your app’s task, any existing back stack for your app’s task is removed and replaced with the deep-linked back stack.

So tapping 'Chat with' is essentially starting a new flow where the user went from LHN to the chat. This guarentees that flows 2 and 3 (from [this comment](https://github.com/Expensify/App/issues/21214#issuecomment-1628919148)) are identical. Deep links have a consistent outcome regardless of the entry point: 'back' to get to the LHN, then another 'back' to exit the app (assuming the deep link is to a thread).

**Comment by Julesssss** [comment] 2023-07-10 14:49
I think we need to align on the desired behaviour before committing to any changes

**Comment by WoLewicki** [comment] 2023-07-10 14:51
> It almost sounds like we're limited here by React Navigation functionality here. Is that correct, or am I reading too much into the reset vs replace actions?

Yeah, it is buggy when trying to integrate some more sophisticated actions with the browser history unfortunately 😞 

> So tapping 'Chat with' is essentially starting a new flow where the user went from LHN to the chat. This guarentees that flows 2 and 3 (from https://github.com/Expensify/App/issues/21214#issuecomment-1628919148) are identical. Deep links have a consistent outcome regardless of the entry point: 'back' to get to the LHN, then another 'back' to exit the app (assuming the deep link is to a thread).

I can agree with that. I am only afraid that web users can be a bit surprised that their whole navigation history will be dropped when clicking the "from" button on a thread, but if it will be consistent across all the cases then it is ok I guess.

**Comment by Julesssss** [comment] 2023-07-10 15:03
@WoLewicki would you say we have to make a cross-platform choice here? Is it possible to have alternate mobile/browser behaviour? Or are we forced to make trade-offs?

**Comment by abdulrahuman5196** [comment] 2023-07-10 15:46
@WoLewicki / @Julesssss Could we create a slack thread to discuss the desired behaviour? The discussion is making this GH noisy and will be tough to look back.

**Comment by mountiny** [comment] 2023-07-10 16:11
> would you say we have to make a cross-platform choice here? Is it possible to have alternate mobile/browser behaviour? Or are we forced to make trade-offs?

We need to make a cross-platform solution, that has been one of the pillars of the project and the architecture we chose and a point re-affirmed in many.... many pre-designs so I would focus on a solution which works cross-platform here. We cannot base this on Android native behaviour.

@abdulrahuman5196 would you be bale to start this Slack thread please?

**Comment by abdulrahuman5196** [comment] 2023-07-10 16:35
Created a slack thread here - https://expensify.slack.com/archives/C01GTK53T8Q/p1689006868827759

We could have the conversation there and come back here once we have a confirmation. 🤝

**Comment by abdulrahuman5196** [comment] 2023-07-12 20:31
Still discussing on slack

**Comment by abdulrahuman5196** [comment] 2023-07-17 10:03
Still in slack

**Comment by Julesssss** [comment] 2023-07-18 07:46
Still investigating

**Comment by Julesssss** [comment] 2023-07-24 07:45
Latest [update](https://expensify.slack.com/archives/C01GTK53T8Q/p1689290603077579?thread_ts=1689006868.827759&cid=C01GTK53T8Q) in Slack: 

> SWM is looking into options how to work with the browser history stack better I believe

**Comment by michaelhaxhiu** [comment] 2023-07-26 20:38
held GH = adding `weekly`

**Comment by michaelhaxhiu** [comment] 2023-08-04 14:36
Note: I'm preparing to go OOO for ~2 weeks, and need a BZ buddy to oversee this while I'm gone. This is on "Hold" right now, but I want to make sure we have coverage in case it gets movement. I'll take it over when I return from OOO if it's not complete.

Thanks in advance @isabelastisser!

**Comment by Julesssss** [comment] 2023-08-07 10:57
Conversation seems to have stalled

**Comment by Julesssss** [comment] 2023-08-11 08:20
Bumped the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1691741995358109?thread_ts=1689006868.827759&cid=C01GTK53T8Q) to see if we have made progress with the browser history stack.

**Comment by isabelastisser** [comment] 2023-08-14 17:00
Not overdue, internal and no updates.

**Comment by Julesssss** [comment] 2023-08-20 20:12
No update

**Comment by abdulrahuman5196** [comment] 2023-08-23 13:52
We need to re-test this issue in staging if its reprodicible as per latest update

**Comment by isabelastisser** [comment] 2023-08-28 17:29
@Julesssss, what are the next steps here? If this issue can no longer be reproduced, should we close it?

**Comment by Julesssss** [comment] 2023-08-29 10:03
Yep, lets close

**Closed by Julesssss** 2023-08-29 10:03 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by ayazhussain79** [comment] 2023-08-29 10:41
@isabelastisser @Julesssss am i eligible for reporting bonus?

**Comment by Julesssss** [comment] 2023-08-29 12:04
Hi @ayazhussain79, not in this case as we didn't fix it. 

But if you believe we did actually fix this please point us to the PR and we can do that.
