### ISSUE TITLE
[HOLD for payment 2023-10-10] Web - Private note -  Private notes closed when clicking save button after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28011] opened 2023-09-22 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any group chat from LHN if there is a group chat and then go to step 7. If there is no group chat, go to Step 3
3. Click the + icon from LHN
4. Click Send message
5. Add users by clicking Add to group
6. Click Create group
7. Click the header from the group chat and open detail RHN
8. Click on the user from the group members
9. Click Private notes
10. Click my notes
11. Click Notes
12. Add some value and Click save
13. Do step 11 again
14. Reload the page
15. Click the save button
16. Observe the result

## Expected Result:
When clicking save the value should be saved and goes to Notes RHN

## Actual Result:
When clicking the save button the RHN gets closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-10
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f6a08d69-7e50-40e0-907d-41ebcfef97a1

https://github.com/Expensify/App/assets/93399543/943175d0-b017-42df-931e-1ccf3817f2f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695206404845639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017083ab1bb282119f</li>
        <li>Upwork Job ID: 1705205888707555328</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26881269</li>
<li>BhuvaneshPatil | Contributor | 26881270</li>
<li>misgana96 | Reporter | 26881274</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-09-22 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private note - Private notes closed when clicking save button after refreshing the page

### What is the root cause of that problem?
After refreshing, the  navigation stack clears, and we go default HOME route
https://github.com/Expensify/App/blob/7bebfd3c777705760e915355cbf7600bb693bd4c/src/pages/PrivateNotes/PrivateNotesEditPage.js#L94

### What changes do you think we should make in order to solve the problem?
HOME routes is being used as fallback here, we can use
`getPrivateNotesViewRoute` function and use instead of `ROUTES.HOME`.

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-09-25 01:57
@mallenexpensify going to unassign here as I was the duplicate assignee here, and this doesn't need two BZ assignees. LMK if there's anything I can help with!

**Comment by mallenexpensify** [comment] 2023-09-26 09:20
@ntdiary please review @BhuvaneshPatil 's proposal above
https://github.com/Expensify/App/issues/28011#issuecomment-1731401481

**Comment by techievivek** [comment] 2023-09-26 10:31
@BhuvaneshPatil Do we usually add the fallback param explicitly when we call `goBack`? I missed it in original implementation and wasn't aware that it's a thing.

**Comment by BhuvaneshPatil** [comment] 2023-09-26 14:06
Where do we show the private notes, is it related only to user accounts or other places as well

**Comment by BhuvaneshPatil** [comment] 2023-09-26 17:30
@ntdiary  raised the PR, donno why it didn't added you automatically.

**Comment by BhuvaneshPatil** [comment] 2023-09-27 09:40
Yes, I think for workspace list page, we shall keep fallback route as HOME.

**Comment by BhuvaneshPatil** [comment] 2023-09-27 12:24
@techievivek 
Shall we keep the HOME as fallback route for Private Notes list page because we can go to that route through many possibilities.

**Comment by mallenexpensify** [comment] 2023-10-02 16:38
@techievivek , when you have a moment (he might be traveling right now)

**Comment by mallenexpensify** [comment] 2023-10-11 02:01
@BhuvaneshPatil I think that's fair, espec since [Melv says 3 days ](https://github.com/Expensify/App/issues/28011#issuecomment-1742444386) ¯\_(ツ)_/¯

Issue reporter: @misgana96 paid $50 via Upwork
Contributor: @BhuvaneshPatil  paid $750 via Upwork, inc. 50% urgency bonus
Contributor+: @ntdiary due $750 via Upwork. 

@ntdiary can you please accept the job and reply here once you have?  Can you also fill out the BZ checklist above? Thx
https://www.upwork.com/jobs/~017083ab1bb282119f

**Comment by mallenexpensify** [comment] 2023-10-11 03:02
Thanks @ntdiary , I updated[ the post above](https://github.com/Expensify/App/issues/28011#issuecomment-1756616821) to denote you're paid. 
Closing!  Thanks for the help!

**Closed by mallenexpensify** 2023-10-11 03:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
