### ISSUE TITLE
LHN– New chat with draft message reappears when refresh page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45781] opened 2024-07-19 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB> Start chat> Add email address of user you have no previous comunication with> Complete the chat creating flow process
2. Type any message into chat composer but don't send the message
3. Navigate to other chat and verify that drafted chat from step 2 disappears
4. Refresh the page
5. Take a look at LHN chats

## Expected Result:
Chat with draft message shoud not appear

## Actual Result:
New chat with draft message disappears when user switch to other chat and reappears when refresh page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ed2d539b-2fbe-4101-b663-eb897435958f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-19 14:20
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-19 14:20
We think that this bug might be related to #vip-vsp

**Comment by tsa321** [comment] 2024-07-19 16:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - New chat with draft message dissappears after navigate to other chat


### What is the root cause of that problem?
Here:

https://github.com/Expensify/App/blob/567627d3598df57f66e28e41d52e930687fbd226/src/libs/SidebarUtils.ts#L139-L142

The new chat has notification hidden and `shouldOverrideHidden` should consider if the report has draft.

so we should add check on the report draft.

### What changes do you think needed to solve this issue?

we should change the shouldOverrideHidden into:

`const shouldOverrideHidden = hasErrorsOtherThanFailedReceipt || isFocused || isSystemChat || report.isPinned || hasValidDraftComment(report?.reportID ?? '-1');`
`

**Comment by tsa321** [comment] 2024-07-20 00:33
I misread the expected result. I thought the expected result was to prevent the chat from disappearing from LHN.If the expected result changes to "the new chat with draft shouldn't disappear," here is my [proposal](https://github.com/Expensify/App/issues/45781#issuecomment-2239522287).

**Comment by OfstadC** [comment] 2024-07-22 20:40
I'm not able to reproduce - my draft remains after a refresh

**Comment by OfstadC** [comment] 2024-07-22 20:41
Oh - wait you're saying it disappears - not that the draft disappears. I think this would be expected if not pinned? Or do drafts get pinned automatically - going to dig more...

**Comment by OfstadC** [comment] 2024-07-23 16:18
Since VIP VSB is on hold and this is likely a polish - I think we can close this for now.

**Closed by OfstadC** 2024-07-23 16:18 UTC
Labels: Daily, Bug
