### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] Collect approver - Settling up bank account message is not copied via Copy to clipboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34989] opened 2024-01-23 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211927
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace on Old Dot
- Admin has a verified bank account set up on Old Dot
- Employee does not have a bank account set up
1. [Employee] Request money from the workspace chat
2. [Admin] Approve the request
3. [Employee] Click on the expense preview to go to expense report
4. [Employee] Right click on the settling up bank account message > Copy to clipboard
5. [Employee] Paste the content

## Expected Result:
The "settling up bank account" message is copied via Copy to clipboard

## Actual Result:
The "settling up bank account" message is not copied via Copy to clipboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/26c78826-8762-48a4-90de-12d99269db33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180d89c40563c1127</li>
        <li>Upwork Job ID: 1749875151051063296</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 28122433</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 19:23
We think that this bug might be related to #wave7. 
CC @RachCHopkins

**Comment by FitseTLT** [comment] 2024-01-23 20:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Collect approver - Settling up bank account message is not copied via Copy to clipboard

### What is the root cause of that problem?
We don't have a logic handling for `REIMBURSEMENTQUEUED` in here
https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L378-L380
### What changes do you think we should make in order to solve the problem?

We need to add a condition that will handle for `REIMBURSEMENTQUEUED` case and set the clipboard to the same message that we are displaying in the `ReportActionItem` here
https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/pages/home/report/ReportActionItem.js#L395-L409

### What alternative solutions did you explore? (Optional)

**Comment by eVoloshchak** [comment] 2024-01-24 23:39
@dukenv0307, correct me if I'm wrong, but your proposal is an extension of @FitseTLT's proposal, they share the same general idea
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/34989#issuecomment-1906898111) looks good to me!

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2024-01-29 11:14
Not overdue, PR is being drafted by @FitseTLT

**Comment by CortneyOfstad** [comment] 2024-01-31 16:10
@FitseTLT any update on the PR draft? Thanks!

**Comment by FitseTLT** [comment] 2024-01-31 18:25
Will make PR ready for review in 2 days

**Comment by CortneyOfstad** [comment] 2024-02-05 14:55
@FitseTLT any update? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-07 16:34
@FitseTLT bump ^^^ thanks!

**Comment by FitseTLT** [comment] 2024-02-07 20:37
@CortneyOfstad sorry 🙏  for not keeping my promise. PR is ready for review.

**Comment by CortneyOfstad** [comment] 2024-02-07 20:38
@eVoloshchak PR is ready for your eyes! TIA!

**Comment by CortneyOfstad** [comment] 2024-02-14 15:05
@eVoloshchak @FitseTLT an update on the PR/review?

Also, @RachCHopkins they believe this fits into #Wave7 — can you confirm? Thanks!

**Comment by eVoloshchak** [comment] 2024-02-15 19:54
No update, [waiting](https://github.com/Expensify/App/pull/36070#pullrequestreview-1871965028) for a response from @FitseTLT 
PR is done and working, we need to finish up the PR author checklist

**Comment by eVoloshchak** [comment] 2024-02-20 15:03
No update, looks like @FitseTLT is not around

**Comment by FitseTLT** [comment] 2024-02-20 15:39
> No update, looks like @FitseTLT is not around

Sorry for the delayed response @eVoloshchak will update PR shortly and notify u

**Comment by CortneyOfstad** [comment] 2024-02-22 19:07
@eVoloshchak an update on the PR review? It looks like @FitseTLT bumped you a few hours ago. Do you think you can provide an update by EOD today? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-23 18:21
Bump @eVoloshchak ^^^ Thanks!

**Comment by eVoloshchak** [comment] 2024-02-26 01:06
Left a comment on the PR, apologies for the delay folks

**Comment by FitseTLT** [comment] 2024-02-27 17:22
@eVoloshchak bump on the response I gave on the PR. If you still having trouble setting up please forward it and I can give more details 👍

**Comment by CortneyOfstad** [comment] 2024-02-28 15:12
@eVoloshchak looks like @FitseTLT bumped you on the PR [here](https://github.com/Expensify/App/pull/36070) 👍

**Comment by CortneyOfstad** [comment] 2024-03-11 17:04
@eVoloshchak can you please complete the checklist above? Thanks!

**Comment by eVoloshchak** [comment] 2024-03-13 14:22
- The PR that introduced the bug has been identified. Link to the PR: unable to pinpoint a PR that has caused the bug, this is a bit of logic that wasn't implemented initially 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this was missed since it is an edge case (see [precondition](https://github.com/Expensify/App/issues/34989#issue-2096826232)), a regression test will be sufficient

**Comment by francoisl** [comment] 2024-03-14 01:25
I opened an issue to create the regression tests, so feel free to issue the payments and then close this @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2024-03-14 12:17
Sounds good @francoisl! Payment has already been issued, with the payment summary listed [here](https://github.com/Expensify/App/issues/34989#issuecomment-1988971152), so we're good to close!

**Closed by CortneyOfstad** 2024-03-14 12:17 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-18 14:34
$500 approved for @eVoloshchak based on [this summary](https://github.com/Expensify/App/issues/34989#issuecomment-1988971152).
