### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - Admin of a workspace is selected and the remove button is activated by Pressing the space key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22413] opened 2023-07-07 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting
2. Workspace
3. Navigate to members
4. Click on the admin check box and then press the space key.
Notice that Admin of a workspace is selected and the remove Button is activated

## Expected Result:
 Can't select Admin of a workspace

## Actual Result:
Admin of a workspace is selected and the remove Button is activated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3146e828-4de2-47ae-8d49-2fd07a2ad718

https://github.com/Expensify/App/assets/93399543/6df29c70-1ea7-40fe-87c6-3780a338f613

https://github.com/Expensify/App/assets/93399543/3b9cf629-94b0-42b1-b9d6-36417f094231

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688674750643479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fb70565a6eaf9ee</li>
        <li>Upwork Job ID: 1678356671465074688</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment] 2023-07-07 13:26
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Workspace Admin can be selected and Remove Button enabled by Pressing the space key

### What is the root cause of that problem?
When we click checkbox for admin row and press spacebar, it will toggle `onPress` event for the checkbox from line 321 as shown in code below.
https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L318-L323

Here we disabled checkbox at line 319 so user will not able to check via mouse, but it will trigger `onPress` via spacebar so it will toggle admin user also. This is the root cause of the problem.

### What changes do you think we should make in order to solve the problem?
We have to update `onPress` at line 321 as shown below. 
i.e. If checkbox not disabled then call `toggleUser()`  otherwise not.
```javascript
 <Checkbox
      disabled={disabled}
      isChecked={isChecked}
      //onPress={() => toggleUser(item.accountID, item.pendingAction)}   // *** OLD Code
      onPress={() => !disabled && toggleUser(item.accountID, item.pendingAction)}   // *** Updated Code
      accessibilityLabel={item.displayName}
  />
```
It will solve the issue as shown in result video.

**Note:** We can adjust/optimize onPress logic during pr if need.

**Additional suggestion:** 
We can also update onPress for PressableWithFeedback  at line 309 [here](https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L309 ) and `onSelectRow ` at line 341 [here](https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L341)  But 309 and 341 not affected by spacebar so this is not required. We can just update onPress for checkbox.

### What alternative solutions did you explore? (Optional)
We can create `toggleUserHandler` as shown below  
`const toggleUserHandler = () => !disabled && toggleUser(item.accountID, item.pendingAction);`

Replace [line 309](https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L309) with `onPress={toggleUserHandler}`
 
and replace [line 321](https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L321) with `onPress={toggleUserHandler}`

Replace  [line 341](https://github.com/Expensify/App/blob/776ea5dd2587dce9796c0233a074113ffeb01938/src/pages/workspace/WorkspaceMembersPage.js#L341)  with `onSelectRow={toggleUserHandler}`

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/7823358/8d9ece11-6ed1-41fb-9394-9e19e4e6e7b6

</details>

**Comment by Pujan92** [comment] 2023-07-07 13:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the Workspace members page admin can be selectable with a space key for the removal

### What is the root cause of that problem?
Within `Checkbox` component which uses `GenericPressable` component we are not returning early for `onKeyPressHandler` for disabled state which we are doing for `onPressHandler`. This seems to be the cause for the issue.

https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L88-L114 

### What changes do you think we should make in order to solve the problem?
We can retrun early when the component is disabled and won't allow executing `onPressHandler` for `onKeyPressHandler` space key.

```
     const onKeyPressHandler = useCallback(
        (event) => {
            if (isDisabled) {
                return;
            }
            if (event.key !== 'Enter') {
                return;
            }
            onPressHandler(event);
        },
        [onPressHandler, isDisabled],
    );
```    

### What alternative solutions did you explore? (Optional)
We can only execute `handleSpaceKey` when it is not disabled within Checkbox component.
`onKeyDown={!props.disabled ? handleSpaceKey : undefined}`
https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/src/components/Checkbox.js#L81

**Comment by b4s36t4** [comment] 2023-07-07 17:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Admin of a workspace is selected and the remove button is activated by Pressing the space key
### What is the root cause of that problem?

Root cause of this issue is that we have a `onKeyUp` handler which will listen to events and call `onPress` if it's `Space` event. If we observe the underlying component `GenericPressable` is having a handler for `onKeyPress`. But in the `CheckBox` Component we're giving a `onKeyUp` handler which not relevant. And there's no propType Definition for `onKeyPress` as well which means it's an unintended behaviour. 

### What changes do you think we should make in order to solve the problem?

Update the propKey here https://github.com/Expensify/App/blob/9d736922d7d7c6d9386f3b7be04b9871c7bdfa57/src/components/Checkbox.js#L83 to `onKeyPress`.



### What alternative solutions did you explore? (Optional)

Maybe handle the `onKeyUp` event in underlying `GenericPressable` component. But I think `onKeyPress` should work in most cases unless we're doing different on `onKeyUP` and `onKeyDown`. So sticking to the `onKeyPress` prop should be good enough.

**Comment by anmurali** [comment] 2023-07-10 10:53
Reproduced on staging in Chrome/ Mac

**Comment by anmurali** [comment] 2023-07-14 10:47
@eVoloshchak can you review the proposals here and pick one?

**Comment by eVoloshchak** [comment] 2023-07-14 12:42
@PrashantMangukiya's [proposal](https://github.com/Expensify/App/issues/22413#issuecomment-1625414379) will work, but only for this specific page, I think we should strive for a more universal approach

 @Pujan92 , I don't think your [approach](https://github.com/Expensify/App/issues/22413#issuecomment-1625455323) will resolve the issue.  There is no need to add `isDisabled` check to `onKeyPressHandler`, since the same check is already performed in
 https://github.com/Expensify/App/blob/ed21fdaaf90f458f7a063eaeb346bff61bac133e/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L142
 
 @bernhardoj's [proposal](https://github.com/Expensify/App/issues/22413#issuecomment-1625701475) looks good to me!
 >In my opinion, it's not very reliable to pass undefined to every possible callback available in Pressable. We can easily miss it, like in this issue
 
 I think it's ok to have a separate method/logic for each callback. There is a finite number of callbacks for Pressable, there won't be a bunch of new ones, and that will allow us to have a more flexible logic if we need to
 
 🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2023-07-14 12:45
@b4s36t4, thanks for the [proposal](https://github.com/Expensify/App/issues/22413#issuecomment-1625736516)!

> The onkeypress event is deprecated.
It is not fired for all keys (like ALT, CTRL, SHIFT, ESC) in all browsers.
To detect if the user presses a key, always use the `onkeydown` event. It works for all keys.

**Comment by eVoloshchak** [comment] 2023-07-26 18:57
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20257
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20257/files#r1275368556
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here, this should have been caught during the review

**Comment by eVoloshchak** [comment] 2023-07-26 18:58
**Regression Test Proposal**

1. Go to setting -> Workspace
2. Navigate to members
3. Click on the admin check box and then press the space key.
4. Verify the admin checkbox isn't selected

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-07-26 18:59
Requested the payment via NewDot

**Comment by JmillsExpensify** [comment] 2023-07-27 04:02
@anmurali Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @eVoloshchak's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by JmillsExpensify** [comment] 2023-07-31 20:38
Reached our via DM

**Comment by anmurali** [comment] 2023-08-01 18:06
- [ ] Reported @davesife $250
- [ ] Contributor @bernhardoj $1000 + $500 (speed bonus)
- [ ] Contributor + @eVoloshchak $1000 + $500 (speed bonus)

**Comment by JmillsExpensify** [comment] 2023-08-01 18:46
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by bondydaa** [comment] 2023-08-07 17:53
i think waiting for payment still @JmillsExpensify @anmurali ?

**Comment by JmillsExpensify** [comment] 2023-08-08 04:20
No for NewDot, we're good on that front. 🙌🏼

**Comment by anmurali** [comment] 2023-08-09 22:04
@bernhardoj - upwork.com/nx/wm/offer/26037915
You need to accept the offer and then I can pay and close this.

**Comment by anmurali** [comment] 2023-08-15 14:17
Paid.

**Closed by anmurali** 2023-08-15 14:17 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
