### ISSUE TITLE
[$500] Web – Assign Task - An error occurs when both User A and User B press the "Mark as done" button simultaneously

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27570] opened 2023-09-15 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any chat labeled "Assign Task" between User A and User B. (The task was created by User A.)
2.	Click "Mark as done" and "Mark as incomplete" from User A. Observe that it works correctly
3.	Click "Mark as done" and "Mark as incomplete" from User B. Observe that it also works correctly
4.	Ensure that the "Mark as done" option is present in the header for each user
5.	Simultaneously press the "Mark as done" button from both User A and User B
6.	An error message appears on User B's system, stating, "You do not have permission to perform the requested action.

## Expected Result:
 The error should not appear and the task should be closed regardless of which user performs the action

## Actual Result:
 An error message appears on User B's system, stating, "You do not have permission to perform the requested action."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1469e0d9-b530-4225-8a23-add1aa71144d

https://github.com/Expensify/App/assets/78819774/ca2bcf83-1cca-4840-8779-28ad810dd71c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694588501046099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129a7b3f4233c245f</li>
        <li>Upwork Job ID: 1702820221863018496</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27120400</li>
</ul></li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-09-16 07:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In assign task when 2 users simulatenously complete task then 1 of 2 users gets an unwanted error.

### What is the root cause of that problem?
Root cause is that we are hard coding error message here:
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/actions/Task.js#L264-L272

This is not considering other reasons of error and have just 1 hard coded case of permissions issue which is not in this specific case. 

### What changes do you think we should make in order to solve the problem?
We need to add error handling for task errors and show error that is tailored to the problem that happened which in this case is e.g. "User 1 has already completed task.", "User 2 has already reopened task". 

This needs to be done via a utility method that must find appropriate error message based on various conditions. Currently we can add 2 cases:

1. Some other user already reopened task
2. Some other user already completed task

Text needs to be added in language files for showing various error messages in multiple languages.

### What alternative solutions did you explore? (Optional)
Just simply remove this:
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/actions/Task.js#L264-L272
That will stop showing error messages for tasks api call.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ayazalavi** [comment] 2023-09-16 13:31
### Proposal 
[Updated](https://github.com/Expensify/App/issues/27570#issuecomment-1722163106)

**Comment by imranaalam** [comment] 2023-09-16 15:03
---

**Problem Statement:**
When two users simultaneously attempt to mark a task as done, one of them encounters an error message, "You do not have permission to perform the requested action."

**Root Cause:**
The system doesn't handle concurrent task state modifications gracefully, leading to misleading error responses when race conditions emerge.

**Proposed Solution:**
**Intelligent Error Handling Using Task State Locking and Enhanced Onyx Messaging:**

1. **Backend Task State Locking**:
    - Use a short-term locking mechanism to handle task state changes.
    - If another user tries to modify the task during this lock, return an appropriate concurrency error code.
    
2. **Enhanced Onyx Error Management on the Frontend**:
    - Incorporate specific error codes to provide clearer feedback.
    - Update the Onyx store with user-friendly error messages based on the error code received.

**Implementation:**

**Backend**:

```javascript
if (task.isLocked()) {
    return { success: false, errorCode: 'CONCURRENCY_ISSUE', message: 'Another user is currently updating the task. Please try again in a moment.' };
}
task.lock();
// Carry out the task state modification
task.unlock();
```

**Frontend**:

```javascript
function changeTaskState(taskID) {
    API.ChangeTaskState(taskID)
        .then((response) => {
            if (response.errorCode === 'CONCURRENCY_ISSUE') {
                Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${taskID}`, {
                    errors: {
                        concurrencyIssue: "Another user is updating this task. Kindly wait a moment."
                    }
                });
            } else if (!response.success) {
                // Manage other potential errors
            }
        });
}
```

Incorporate enhanced error messages in `App/src/languages/en.ts`:

```javascript
task: {
    // ... existing keys
    messages: {
        // ... existing messages
        concurrencyIssue: "Another user is updating this task. Kindly wait a moment.",
        completingError: "Unable to finalize the task as completed. Please retry shortly.",
        reopeningError: "Unable to revert the task. Please try again after a while."
    }
}
```

**Advantages**:
- Efficiently handles race conditions using a backend locking mechanism.
- Delivers clearer feedback to users through enhanced Onyx error messaging, improving UX.
- Centralizes error messages with Onyx, streamlining error management.

**Disadvantages**:
- The locking mechanism can introduce a minor delay in processing task updates.
- Requires frontend and backend modifications to manage and display the new error messages.

**Alternative Solution:**
**Optimistic UI Updates with Timestamp-based Validation and Onyx Messaging**:
- Assume success on the frontend (optimistically) when a user tries to change the task state.
- Use timestamps to determine the most recent task state change on the backend.
- If there's a conflict, return a specific error code.
- Display a more descriptive error message using Onyx on the frontend.

**Advantages**:
- Provides an immediate response, enhancing user experience.
- Reduces the chance of race conditions using timestamp validation.

**Disadvantages**:
- Potential for race conditions if timestamps are identical, though very unlikely.
- Users might still experience rejection messages, but they will be more descriptive.

**Comment by michaelhaxhiu** [comment] 2023-09-20 18:17
This was marked `External` prematurely, and I'm just getting caught up now. I just tested on my local accountant this is reproducible so we should indeed fix it. 

@sobitneupane inviting your input on the proposals above.

**Comment by sobitneupane** [comment] 2023-09-25 07:38
@michaelhaxhiu It is better to handle this issue internally. I think it's possible that we may need to make some adjustments to the backend in order to address the issue.

**Comment by ayazalavi** [comment] 2023-09-25 13:25
@sobitneupane @michaelhaxhiu in the frontend showing simple error message in case of a failure should be enough as per my thinking. Handling it in the backend with semaphores and other simultaneous access jargon can make things more complicated and will cause more errors. Simply showing message unable to mark completed/reopen should be enough. @michaelhaxhiu what do you think?

**Comment by michaelhaxhiu** [comment] 2023-09-27 14:44
I'm going to apply the `Engineering` label to get an internal engineers input. @sobitneupane is saying this may be best resolved internally [here](https://github.com/Expensify/App/issues/27570#issuecomment-1733090309), but we have some existing proposals that can resolve it in the front end. 

What do we think?

**Comment by Julesssss** [comment] 2023-09-28 03:24
This feels more like an improvement than resolving a bug.

I think a backend change would be ideal, but a front-end fix is the better solution for us. There's no chance we'll be able to prioritise the backend changes this year.

**Comment by michaelhaxhiu** [comment] 2023-09-28 12:18
Thanks for your input! @sobitneupane let's review the front end suggestions that were provided please.

**Comment by Julesssss** [comment] 2023-10-02 09:04
I think this is the next step: 

>  @sobitneupane let's review the front end suggestions that were provided please.

**Comment by sobitneupane** [comment] 2023-10-03 14:46
Thanks @Julesssss.

@dukenv0307 Would you mind explaining the conditions used in the codeblock?

Would the proposed change affect the case where the user does not have permission to perform the action? We would like to show an error if that is the case.

**Comment by ayazalavi** [comment] 2023-10-03 15:33
> Would the proposed change affect the case where the user does not have permission to perform the action? We would like to show an error if that is the case.

If user doesn't have permission then it will be 404 page that will be thrown to the user or lets say someone removes the task then it should be removed in real time from other users.

**Comment by MitchExpensify** [comment] 2023-10-06 20:21
Bump @sobitneupane

**Comment by sobitneupane** [comment] 2023-10-09 11:46
Sorry for the delay.

I will try to review the proposals before EOD tomorrow (NPT).

**Comment by sobitneupane** [comment] 2023-10-10 09:40
Thanks for the update @dukenv0307.

[Proposal](https://github.com/Expensify/App/issues/27570#issuecomment-1722149581) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by neil-marcellini** [comment] 2023-10-13 17:20
I reviewed the PR and I'm not sure that the current proposal is the right solution. I think we should fix it on the backend as I [mentioned here](https://github.com/Expensify/App/pull/29259#pullrequestreview-1676978417).

**Comment by ayazalavi** [comment] 2023-10-16 08:32
@jules, my proposal is straightforward; we can address the issue by adding a permissions error alongside showing marking/unmarking errors. This should resolve the problem.

**Comment by Julesssss** [comment] 2023-10-17 07:51
Assigning to @neil-marcellini as discussed here: https://github.com/Expensify/App/pull/29259#issuecomment-1764952775

**Comment by neil-marcellini** [comment] 2023-10-18 17:56
Rodrigo is taking over for me to implement the backend change.

**Comment by sobitneupane** [comment] 2023-10-27 12:32
@ayazalavi It is decided to fix the issue in the backend. It is no longer available for new proposals.

**Comment by MitchExpensify** [comment] 2023-10-28 23:00
So we are suggesting showing one action, `marked as complete`, as taken by two people? I'm not sure that's ideal but curious what @neil-marcellini thinks too

**Comment by MitchExpensify** [comment] 2023-11-01 18:14
> In the end only one person actually completed the task, since we don't save a new completed action for a task that was already completed, that is why I think this is ok.

Just to be sure, you think showing the task that one person actually completed to two people as completed by both of them to be OK?

**Comment by rlinoz** [comment] 2023-11-02 10:03
Oh no sorry, I think we should show only one completed message by the correct person, and that is what we are actually doing, showing only one complete action for this situation.

I guess the screenshot I took made things a little bit confusing, but we fixed that screenshot in the [backend PR](https://github.com/Expensify/Web-Expensify/pull/39339).

If two people complete a task simultaneously we are erasing the completed message from the person that didn't actually complete it.

**Comment by MitchExpensify** [comment] 2023-11-03 23:20
Awesome!

**Comment by rlinoz** [comment] 2023-11-27 14:20
I think we can close this issue, but I am not sure whether payment is due or not.

@MitchExpensify

**Comment by MitchExpensify** [comment] 2023-11-28 19:22
**Payment summary:**

- [usmantariq96](https://github.com/usmantariq96) Reporter: $50, Upwork
- C+ @sobitneupane - Clarification, did you end up reviewing the proposal that was ultimately used here seeing as it was a backend change?

**Comment by sobitneupane** [comment] 2023-11-29 09:15
@MitchExpensify A proposal was selected and while implementing the [PR](https://github.com/Expensify/App/pull/29259), it was decided that the issue would be best solved on the backend. So, we ended of closing the PR without merging.

**Comment by MitchExpensify** [comment] 2023-12-05 20:28
That seems fair, can you both please apply to this job for payment? https://www.upwork.com/jobs/~01314f533571a41c4f

**Comment by MitchExpensify** [comment] 2023-12-05 20:29
And same for you [usmantariq96](https://github.com/usmantariq96), thanks!

**Comment by usmantariq96** [comment] 2023-12-06 03:35
@MitchExpensify link is not opening at my end.

Can you please send me direct message please.
My Upwork Profile link: https://www.upwork.com/freelancers/~0162e9ec0b876900fb

Thanks

**Comment by usmantariq96** [comment] 2023-12-06 03:42
@MitchExpensify applied for the job 
thanks

**Comment by sobitneupane** [comment] 2023-12-08 08:48
@MitchExpensify I will request payment on newDot once you post the payment summary.

**Comment by MitchExpensify** [comment] 2023-12-11 23:23
Updated the payment summary - https://github.com/Expensify/App/issues/27570#issuecomment-1830528327

**Comment by MitchExpensify** [comment] 2023-12-11 23:27
Do we need to add a regression test here @sobitneupane ?

**Comment by sobitneupane** [comment] 2023-12-15 09:29
**Regression Test Proposal**

1. Create a task from User A assigning it to User B.
2. Ensure that the "Mark as done" option is present in the header for each user
3. Simultaneously press the "Mark as done" button from both User A and User B
4. Verify that the app works fine and no error is displayed
5. Ensure that the task is marked as Done
6. Simultaneously press the green box to re-open the task from both User A and User B
7. Verify that the app works fine and no error is displayed
8. Simultaneously press Cancel the task from both User A and User B
9. Verify that the app works fine and no error is displayed

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-12-15 09:52
https://github.com/Expensify/App/issues/27570#issuecomment-1830528327

Requested payment on newDot.

**Closed** 2023-12-15 21:50 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug

**Comment by JmillsExpensify** [comment] 2023-12-15 23:14
$500 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/27570#issuecomment-1830528327).
