### ISSUE TITLE
[HOLD for payment 2024-08-13] [HOLD for payment 2024-08-09] [Search] Cleanups from #44820

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#44916] opened 2024-07-05 15:10 UTC
From PR: https://github.com/Expensify/App/pull/44820

1. We should maintain the list of selected items when switching from mobile to desktop layout.

https://github.com/Expensify/App/assets/29673073/628ddbee-16cd-47d4-962d-5bae756034dd

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by rushatgabhane** [comment] 2024-07-05 15:11
cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-07-05 15:43
Super edge case, popping in polish.

**Comment by puneetlath** [comment] 2024-07-05 15:52
@rushatgabhane are you handling this?

**Comment by rushatgabhane** [comment] 2024-07-05 16:03
yeah i can so that @filip-solecki can do priority stuff

**Comment by rushatgabhane** [comment] 2024-07-08 02:29
not overdue

**Comment by filip-solecki** [comment] 2024-07-08 11:33
FYI @Kicu is working on adding SearchContext, what should make it a lot easier to keep selected items while resizing - the PR is [here](https://github.com/Expensify/App/pull/41725)

**Comment by Kicu** [comment] 2024-07-08 12:02
hey thanks @filip-solecki for pointing this issue to me 🚀 
Yes - together with @luacmartins we came to the conclusion that we have to drill too many props through `listItem`s for `SelectionList`. Since I need a bit of search contextual data to make api calls (in a few different components), I decided to introduce SearchContext in the mentioned PR.

It would be best to wait a bit with this task until my PR is finished and merged. I expect it will take max 1-2 more days.
Cheers

**Comment by luacmartins** [comment] 2024-07-10 19:07
@rushatgabhane [this PR](https://github.com/Expensify/App/pull/41725) is merged and you can now use the SearchContext

**Comment by puneetlath** [comment] 2024-07-16 17:36
@rushatgabhane how's it going?

**Comment by luacmartins** [comment] 2024-07-18 21:06
Bump @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-07-21 22:48
working on this

**Comment by rushatgabhane** [comment] 2024-07-23 01:30
@puneetlath im not close to a solution. I moved `setIsMobileSelectionModeActive` to context to keep the header consistent when switching between desktop/mobile. But I haven't been able to move the selectedReports and get selectedTransactions yet  

@filip-solecki could you please take over this for implementation?

**Comment by filip-solecki** [comment] 2024-07-23 04:17
Sure, I can take it but closer to the EOW (maybe tomorrow or on Thursday I guess)

**Comment by puneetlath** [comment] 2024-07-26 18:29
Were you able to take a look @filip-solecki?

**Comment by filip-solecki** [comment] 2024-07-29 04:35
Yes, I started working on this on Thursday but on Friday there were merged two conflincting PRs so I had to refactor my solution and I hope today I'll prepare the PR

**Comment by puneetlath** [comment] 2024-08-12 16:27
@rushatgabhane friendly reminder about the checklist so we can pay tomorrow.

**Comment by puneetlath** [comment] 2024-08-14 14:50
@rushatgabhane bump!

**Comment by puneetlath** [comment] 2024-08-19 21:17
@rushatgabhane bump again. Would love to close this out.

**Comment by rushatgabhane** [comment] 2024-08-21 20:47
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by puneetlath** [comment] 2024-08-21 20:55
Regression test issue: https://github.com/Expensify/Expensify/issues/422390

Payment summary [above](https://github.com/Expensify/App/issues/44916#issuecomment-2286822212) is correct. Please request on NewDot. Thanks!

**Closed by puneetlath** 2024-08-21 20:55 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-22 09:07
$250 approved for @rushatgabhane
