### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Split - User can select or unselect members on comfirmation page when splitting bill from FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32867] opened 2023-12-11 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Click FAB > Request money
3. Enter amount > Next
4. Click Split next to a few users that have prior chat (important)
5. Click Next

## Expected Result:
User will not be given the choice to select and unselect bill split participants on the confirmation page when it is created from FAB (PROD behavior)

## Actual Result:
User is able select and unselect bill split participants on the confirmation page when it is created from FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e24e1b00-e348-4c57-b70a-989fb287a5b6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157740199e6470999</li>
        <li>Upwork Job ID: 1734327112370180096</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28040213</li>
<li>shubham1206agra | Contributor | 28040214</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-12-11 21:33
@lanitochka17 I'm not quite following what the issue is from watching the video - I don't see any participants being edited from the confirmation page

**Comment by thienlnam** [comment] 2023-12-11 21:35
Ah tested it locally and I see the issue now
![Screenshot 2023-12-11 at 1 35 13 PM](https://github.com/Expensify/App/assets/30609178/46b41f4b-4c3b-4a62-94fa-815c667b9b29)

**Comment by lanitochka17** [comment] 2023-12-11 21:37
@thienlnam TestRail https://expensify.testrail.io/index.php?/tests/view/4057459

**Comment by thienlnam** [comment] 2023-12-11 21:37
Looks like it likely was caused by https://github.com/Expensify/App/pull/28618

**Comment by thienlnam** [comment] 2023-12-11 21:39
We ideally don't want to revert this huge PR - if we can have it fixed externally that would be a much better outcome

**Comment by abzokhattab** [comment] 2023-12-11 22:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can modify participants list when  splitting bill using FAB
### What is the root cause of that problem?
The following condition in the confirmation page decides whether the user is allowed to modify the participant's selections or not :


https://github.com/Expensify/App/blob/968f39f0a2c6e7305e46f7d5a8a546407689cc10/src/pages/iou/request/step/IOURequestStepConfirmation.js#L329

the `reportID` is fetched from the `params.reportID` and here the new link that the user is routed to when clicking on FAB -> Request Money:

`https://dev.new.expensify.com:8082/create/request/start/1/1437418385097478/manual`

 
so in the new implementation of the money request, the url will **always** contain the report ID: 


however here is the old one: `https://new.expensify.com/request/new/manual`


so in the old implementation the `param.reportID` will be null in this case and thus the user wont be able to modify the list


### What changes do you think we should make in order to solve the problem?

so the solution for this problem would be to introduce a new `param` in the url: `disallowModifyParticipants` and this param should be added to the url whenever the user clicks on FAB -> Request Money and then it will be utilized in the confirmation page to determine whether users can modify the list. This approach minimizes code changes and avoids potential breaking changes.

**Comment by luacmartins** [comment] 2023-12-12 00:34
We're adding isFromGlobalCreate param [here](https://github.com/Expensify/App/pull/32878/files), which I think can be used here too

**Comment by c3024** [comment] 2023-12-12 01:24
@abzokhattab could you update your proposal with `isFromGlobalCreate`?

**Comment by shubham1206agra** [comment] 2023-12-12 01:48
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Split - User can select or unselect members on comfirmation page when splitting bill from FAB

### What is the root cause of that problem?

In `IOURequestStepConfirmation`

https://github.com/Expensify/App/blob/968f39f0a2c6e7305e46f7d5a8a546407689cc10/src/pages/iou/request/step/IOURequestStepConfirmation.js#L329

This condition is being used to allow modifying the participant's list, but this condition will always be evaluated to true now as all requests have report ID due to recent refactoring.

But in the old implementation, the `param.reportID` was null in the given case and due to this, the user wasn't able to modify the list.

### What changes do you think we should make in order to solve the problem?

Use `isFromGlobalCreate` which is being created in https://github.com/Expensify/App/pull/32878, and modify the condition to

```js
canModifyParticipants={!transaction.isFromGlobalCreate} 
```

**Comment by abzokhattab** [comment] 2023-12-12 02:05
>  @abzokhattab could you update your proposal with isFromGlobalCreate?


updated ..  here is the poc :

pr can be raised in the next half an hour  

https://github.com/Expensify/App/assets/59809993/6a8c892b-488d-42a8-8cdd-9465ed7ffc91

**Comment by c3024** [comment] 2023-12-12 02:10
[This issue] is also pending. These being a deploy blockers I think @shubham1206agra can raise PR quickly.

[Proposal](https://github.com/Expensify/App/issues/32867#issuecomment-1851173919) by @shubham1206agra looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by shubham1206agra** [comment] 2023-12-12 03:28
@thienlnam Can you do the assignment here?

**Comment by shubham1206agra** [comment] 2023-12-12 12:41
@c3024 PR is ready

**Comment by Julesssss** [comment] 2023-12-12 16:08
I'm going to Cp this now

**Comment by puneetlath** [comment] 2023-12-12 17:29
Confirmed this is fixed.

**Comment by Julesssss** [comment] 2023-12-12 17:30
Thank you!

**Comment by slafortune** [comment] 2023-12-28 15:32
Self-assigned to payout C and C+ - Done!

**Closed by slafortune** 2023-12-28 15:32 UTC
Labels: External, Engineering, Daily, Awaiting Payment
