### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] workspace participant details link work even after participant is removed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19994] opened 2023-06-01 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

Create a workspace with two users. (Note that user B should have at least 1 workspace in which user B is workspace admin and user A is member)

1. Open the app and login with user A
2. Open the app on another device and login with user B 
3. From user A device, open #announce of workspace in which user B is admin
4. Click on #announce in header
5. Click on members
6. Click on any member to open its details page
7. Grab the URL from the details page
8. From user B, open settings->workspaces->workspace used in step 3-> Members-> Select member used in step 6-> Remove the member
9. On user A device, reload the participant details page and observe that even though that participant is removed, we can still access the details page with workspace participant link
## Expected Result: 
App should either redirect us to concierge or provide 'Hmm... its not here' page as the user is no longer participant of the workspace and we should not be able to access the user using workspace participant link
## Actual Result: 
App allows us to access user detail using the same workspace participant link even though the user is no longer a participant
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2ff2277e-f34e-4e92-91e1-c5045547a06a

https://github.com/Expensify/App/assets/43996225/62131966-8b8d-4401-94c8-e97fcb830fc9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685443509473159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5a1a7388d0204d8</li>
        <li>Upwork Job ID: 1666146735024664576</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-06-06 17:55
OK I understand the problem

**Comment by muttmuure** [comment] 2023-06-06 18:02
Wow these steps are really confusing

**Comment by muttmuure** [comment] 2023-06-08 15:20
@will0225 can you please follow the [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) or confirm that you're part of an agency Expensify has a relationship with?

**Comment by will0225** [comment] 2023-06-08 15:21
yes, I already confirmed with guidelines and want to work on team.

**Comment by will0225** [comment] 2023-06-08 15:22
What is wrong with me?

**Comment by muttmuure** [comment] 2023-06-08 15:27
We shouldn't be troubleshooting your setup issues in a bug issue, please can you head to #expensify-open-source and share the context there instead.

**Comment by will0225** [comment] 2023-06-08 15:29
Firstly, I want to be member of slack channel. I already sent email to be invited into slack.
But I did not get that invite email yet.

**Comment by mollfpr** [comment] 2023-06-08 15:31
Sorry guys for the delay!

The proposal from @dukenv0307 looks good to me! The participant page is linked from the report page, and we can use `withReportOrNotFound` HOC for this case, it will return the `NotFoundPage`.

🎀 👀 🎀 C+ reviewed!

**Comment by muttmuure** [comment] 2023-06-08 15:32
[dukenv0307](https://github.com/dukenv0307) you are free to start your PR with Jack and Luthfi reviewing

**Comment by muttmuure** [comment] 2023-06-08 15:33
@will0225 sit tight and you'll get invited into the Slack channel, in the meantime, I recommend reviewing and following the guidelines so you can get the next issue you feel ready to work on.

**Comment by will0225** [comment] 2023-06-08 15:37
For now, Which issue should I review?

**Comment by thienlnam** [comment] 2023-06-08 15:42
@will0225 Please give this a read https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md and wait until you get invited to the slack room if you've already reached out. Once that happens, you can post your setup issues there but otherwise these GH issues are meant for conversation related to the issue

**Comment by thienlnam** [comment] 2023-06-09 14:40
> Just want to clarify the expected behavior when we open a link with the format "a/:accountID" with a accountID that doesn't or not in contact list of the user. Actually, it display an avatar with hidden as the image below. So it is expected or it should display page not found.

This is expected (we're working on hiding any sensitive information if you're not in their contact list) but you should still see the avatar

**Comment by muttmuure** [comment] 2023-06-21 09:22
@thienlnam are we discussing expected behavior in #expensify-open-source somewhere?

https://github.com/Expensify/App/pull/20497

**Comment by muttmuure** [comment] 2023-06-21 09:25
Ah found it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686936942938439)

**Comment by muttmuure** [comment] 2023-06-21 09:28
I think we almost have a fix for this, and the scope is still narrow which is good. @mollfpr @thienlnam do you mind reviewing @dukenv0307's proposed changes [here](https://github.com/Expensify/App/pull/20497#issuecomment-1599323700)?

**Comment by muttmuure** [comment] 2023-06-21 10:36
Does it need to be after sign-out-sign-in? Could we do it after refresh?

**Comment by mollfpr** [comment] 2023-06-22 15:15
@dukenv0307 Yes, but that makes this issue persist.

**Comment by mollfpr** [comment] 2023-06-22 15:42
> App should either redirect us to concierge or provide 'Hmm... its not here' page as the user is no longer participant of the workspace and we should not be able to access the user using workspace participant link

@dukenv0307 The OP expected result is missing from the current PR.

**Comment by mollfpr** [comment] 2023-06-22 15:59
I can't entirely agree with that. The reason we have the details is from the workspace member. After the user is removed, there's no relation between them anymore. Also, this will be a bug if we re-sign in the detail is hidden because we don't have the user details as they are not within the workspace.

**Comment by muttmuure** [comment] 2023-07-10 12:37
@mollfpr think you can take a look at @dukenv0307's comment this week?

**Comment by muttmuure** [comment] 2023-07-10 12:47
OK great! Sounds like we're just waiting for deployment

**Comment by mollfpr** [comment] 2023-07-20 17:11
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. There will be a follow-up PR for the backend fix. The E/App fix is to unify the route for profile page.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step can covered this.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the app and sign in with an account that has a workspace
2. Open #announce of workspace
4. Click on #announce in the header
5. Click on members
6. Click on any member to open its profile page
7. **Verify** that the URL is `/a/:accountID` instead of `/r/:reportID/participants/a/:accountID`

For Web/mWeb
1. Do the above step and copy the URL from the profile page
2. Sign out and paste the URL
3. Sign in with the previous account
4. **Verify** it's opened the profile page and shows the loading indicator
5. **Verify** the user details are not displayed as _Hidden_

**Comment by mollfpr** [comment] 2023-07-21 17:36
Friendly bump @muttmuure

**Comment by muttmuure** [comment] 2023-07-26 06:50
Catching up from ooo

**Comment by muttmuure** [comment] 2023-07-27 12:58
@mollfpr @dukenv0307 @dhanashree-sawant all invited to the job

**Comment by mollfpr** [comment] 2023-07-27 12:59
@muttmuure Applied, thank you!

**Comment by dhanashree-sawant** [comment] 2023-07-27 13:19
Thanks @muttmuure, Invite accepted

**Comment by mollfpr** [comment] 2023-07-31 05:12
Friendly bump @muttmuure

**Comment by mollfpr** [comment] 2023-08-02 10:03
@muttmuure Accepted, thank you!

**Comment by mollfpr** [comment] 2023-08-07 17:25
Friendly bump @muttmuure to help complete the issue.

**Comment by muttmuure** [comment] 2023-08-09 20:34
Everyone has been paid

**Closed by muttmuure** 2023-08-09 20:34 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug, Upwork Automation
