### ISSUE TITLE
[$500] iOS - Chat - 'Hmm its not here' page glitches on opening without access conversation

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36411] opened 2024-02-13 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open any chat
3. Send link of chat you don't have access to eg: https://staging.new.expensify.com/r/1234
4. Observe that 'Hmm its not here' page glitches i.e. 'Hmm its not here' text stays in place but image and 'You don't have access to this chat' text slides down

## Expected Result:
'Hmm its not here' page should not glitch on opening non authorized chat

## Actual Result:
'Hmm its not here' page glitches on opening non authorized chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/56ca3c05-992c-4fd3-acbc-528664838b1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a21cace63ee69074</li>
        <li>Upwork Job ID: 1757389808519114752</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-13 13:07
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by situchan** [comment] 2024-02-15 17:16
Proposals are in review.
Also open for more proposals.

**Comment by anmurali** [comment] 2024-02-16 15:14
Rotated the label since I will be OOO till 29th! I can take it back when I return!

**Comment by situchan** [comment] 2024-02-20 16:08
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/36411#issuecomment-1941989052) looks good to me.
🎀 👀 🎀 C+ reviewed


https://github.com/Expensify/App/assets/108292595/3d4abce2-bf08-417e-b1de-2597ecd97819

**Comment by bernhardoj** [comment] 2024-02-21 07:08
PR is ready

cc: @situchan

**Comment by situchan** [comment] 2024-03-06 16:38
PR was deployed to production on Feb 28

**Comment by JmillsExpensify** [comment] 2024-03-22 18:26
Circling back on payments. Summary:

 - Contributor: @bernhardoj $500 
 - Contributor+: @situchan $500

**Comment by JmillsExpensify** [comment] 2024-03-22 18:26
In the meantime, @situchan what about the BZ checklist?

**Comment by situchan** [comment] 2024-03-22 19:01
No regression. This existed for long time.
This is not worth adding regression test as minor UI glitch only on iOS, not affecting users.

**Comment by JmillsExpensify** [comment] 2024-03-22 20:43
All contributors paid out and no regression test. I'm closing this issue!

**Closed by JmillsExpensify** 2024-03-22 20:43 UTC
Labels: Reviewing, External, Weekly, Bug
