### ISSUE TITLE
Feature Request: Insert a space after an emoji is selected 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11100] opened 2022-09-19 05:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem: 
When sending messages and including an emoji, after you've selected the emoji and continue to type your message, a space isn't added so it looks like :woo-homer:this.

## Solution: 
By default, add a space after :ralph: so that the user can continue to type without having to add another space
Context/Examples/Screenshots/Notes: The space after :milhouse: is default in Slack so many people are used to it being added.  We're also working on allowing the ability to type emoji names ([GH](https://github.com/Expensify/App/issues/4324)), ala :granpa: and the space after :granpa: is also default in Slack and what people are used to.

## Action Performed:
1. Navigate to any chat 
2. send emoji 

## Expected Result:
User should see space after an emoji is selected 

## Actual Result:
When sending messages and including an emoji, after you've selected the emoji and continue to type your message, a space isn't added so it looks like :woo-homer:this.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.1-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662746279291419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2022-09-19 06:26
**Proposal:**
We can insert space after an emoji in `addEmojiToTextBox(emoji)` function.
https://github.com/Expensify/App/blob/3335b188ce86ba413f4098f6905926e737870ce3/src/pages/home/report/ReportActionCompose.js#L312-L325
```diff
    addEmojiToTextBox(emoji) {
+        const emojiWithSpace = emoji + ' '
        const newComment = this.comment.slice(0, this.state.selection.start)
+            + emojiWithSpace + this.comment.slice(this.state.selection.end, this.comment.length);
        const newComment = this.comment.slice(0, this.state.selection.start)
-            + emoji + this.comment.slice(this.state.selection.end, this.comment.length);
        this.textInput.setNativeProps({
            text: newComment,
        });
        this.setState(prevState => ({
            selection: {
-                start: prevState.selection.start + emoji.length,
-                end: prevState.selection.start + emoji.length,
+                start: prevState.selection.start + emojiWithSpace.length,
+                end: prevState.selection.start + emojiWithSpace.length,
            },
        }));
        this.updateComment(newComment);
    }
```

**Comment by sonialiap** [comment] 2022-09-19 14:22
The suggestion sounds good to me 👍

**Comment by jasperhuangg** [comment] 2022-09-21 19:56
@sobitneupane thanks for the timely proposal! I think @grgia already had some changes locally so she went ahead and made a PR.

**Comment by mallenexpensify** [comment] 2022-09-21 23:34
Oooooh, this might be one of those rare (first time I've seen it) situations where a proposal was submitted before the `External` label was added and we decided to fix internally. @grgia: 
1. Is that correct?
2. For the fix, did you use/reference code that @sobitneupane proposed?  

[Per our CONTRIBUTING.md
](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Note%3A%20Issues%20that%20have%20not%20had%20the%20External%20label%20applied)> Note: Issues that have not had the External label applied have not yet been approved for implementation. This means, if you propose a solution to an issue without the External label (which you are allowed to do) it is possible that the issue will be fixed internally. If the External label has not yet been applied, Expensify has the right to use your proposal to fix said issue, without providing compensation for your solution. This process covers the very rare instance where we need or want to fix an issue internally.

**Comment by grgia** [comment] 2022-09-22 06:23
Ah yes, I'm sorry! There was no label so I assumed I could fix it

**Comment by mallenexpensify** [comment] 2022-09-23 01:03
@grgia For the fix, did you use/reference code that @sobitneupane proposed?
I/we need to decide if they're due compensation

**Comment by mallenexpensify** [comment] 2022-09-29 21:03
Chatted with @grgia, she's new to the team and was unaware of our process. Technically, per our CONTRIBUTING.md, since the proposal was submitted before the `Help Wanted` label was added, we _could_ use details from the proposal without compensating @sobitneupane .   @grgia mentioned she did reference the code provided so, for this edge case, we will compensate @sobitneupane . @sobitneupane please monitor the issue and PR until the PR is deployed to production, provide help if/where needed.  Compensation will be issues 7 days after the PR has been deployed to production, assuming there are no regressions. 

@sobitneupane , please apply here https://www.upwork.com/jobs/~0106db93cef35496f5 and confirm in this issue once you have.

**Comment by sobitneupane** [comment] 2022-09-30 01:08
Applied.

**Comment by mallenexpensify** [comment] 2022-10-04 23:21
@sobitneupane , hired, please let me know when you accept and I'll pay

**Comment by sobitneupane** [comment] 2022-10-05 10:32
@mallenexpensify I am getting error while trying to accept your offer.

<img width="500" alt="Screen Shot 2022-10-05 at 16 14 26" src="https://user-images.githubusercontent.com/25876548/194040083-1a6964bc-04fd-4bbe-8492-33f730664591.png">

**Comment by sobitneupane** [comment] 2022-10-06 02:38
No luck. Unable to accept offer for this job. I was able to accept offer for other jobs though.

**Comment by mallenexpensify** [comment] 2022-10-06 22:00
How about this one @sobitneupane https://www.upwork.com/jobs/~014ab10dacdb6c00ad

**Comment by mallenexpensify** [comment] 2022-10-07 23:56
You're welcome @sobitneupane .  You're paid and both Upwork jobs are closed.

**Closed by mallenexpensify** 2022-10-07 23:56 UTC
Labels: Reviewing, Engineering, Weekly, NewFeature
