### ISSUE TITLE
[HOLD for payment 2024-10-17] Web - Saved search - Tooltip reappears after it disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49873] opened 2024-09-27 22:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y 
**Reproducible in prodaction?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account
3. Go to Search
4. Click Filters
5. Add some filters
6. Click Save search
7. Note that tooltip appears on the saved search
8. Click 3-dot menu > Rename
9. Rename the search and save it

## Expected Result:
The tooltip should not reappear after it disappears

## Actual Result:
The tooltip reappears after it disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a205ff48-0b16-4b01-a1d3-37ffa83fc9e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment] 2024-09-27 22:04
We think that this bug might be related to #wave-control

**Comment by blimpich** [comment] 2024-09-27 22:45
@Krishna2323 since this is a deploy block you need to identify what caused the regression in the first place. I don't consider the proposal complete without that.

**Comment by blimpich** [comment] 2024-09-27 23:10
In order for me to mark this as external I would want (A) the original contributor and C+ to not be reachable (B) the original PR for some reason shouldn't be reverted because it'll cause more problems then it'll solve and (C) the problem is urgent enough that I don't want to wait for the original contributor to get around to it.

For this issue A is true but B and C are not. I think this problem is minor enough that we can demote it and make it follow up work for people who worked on the PR who caused the regression. Not worth reverting over a slightly buggy tooltip IMO.

cc: @luacmartins @daledah @dukenv0307

**Comment by luacmartins** [comment] 2024-09-30 13:27
>Should we dismiss the tooltip forever when users open the modal when the tooltip is open

IMO we should do this.

**Comment by VictoriaExpensify** [comment] 2024-10-18 00:18
Hey @daledah and @dukenv0307 - I've sent you both offers in Upwork, can you please accept these and I'll organise payment?

@dukenv0307 could you also please complete the checklist? Thank you!

**Comment by VictoriaExpensify** [comment] 2024-10-21 01:00
TestRail issue created - https://github.com/Expensify/Expensify/issues/437475

**Comment by VictoriaExpensify** [comment] 2024-10-21 01:03
@dukenv0307 and @daledah - still waiting for you to accept offers 🙏 https://www.upwork.com/ab/applicants/1847068669603673881/pending

**Comment by VictoriaExpensify** [comment] 2024-10-24 02:15
Ah I missed that comment. Thanks @dukenv0307

**Comment by tgolen** [comment] 2024-10-24 16:44
@dukenv0307 I see your answers to the BZ Checklist, but I think there was a PR that was identified as the culprit. Should that be mentioned in the Checklist?

**Comment by VictoriaExpensify** [comment] 2024-10-29 00:39
So just to check, do I need to process payment here or not. Based on [this comment](https://github.com/Expensify/App/issues/49873#issuecomment-2380260496), I think not?

**Comment by VictoriaExpensify** [comment] 2024-10-30 05:35
Ok closing this out since it doesn't look like I need to do anything more here. Thanks @dukenv0307

**Closed by VictoriaExpensify** 2024-10-30 05:35 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
