### ISSUE TITLE
Distance - 404 error appears in console after creating distance request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33985] opened 2024-01-04 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -  Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Click + > Request money > Distance
3. Create a distance request

## Expected Result:
There will be no console error after creating distance request

## Actual Result:
404 error shows up after creating distance request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3335c82d-977d-456d-9a85-57787ffb7383

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2024-01-04 23:25
I tested it myself and it also appears to try to fetch the same URL

**Comment by thienlnam** [comment] 2024-01-04 23:26
https://staging.expensify.com/1b96fa279dcd8a80ee9f.png?encryptedAuthToken=<authtoken>

**Comment by thienlnam** [comment] 2024-01-04 23:40
It's not causing any issues - but it kind of looks similar to an issue pointed back here https://github.com/Expensify/App/issues/30319

**Comment by thienlnam** [comment] 2024-01-05 03:05
Okay, looks like that URL is for the optimistic receipt - the generic receipt image
`import ReceiptGeneric from '@assets/images/receipt-generic.png';`

Going to see where this is hosted

**Comment by bernhardoj** [comment] 2024-01-05 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The receipt image can't be found for distance requests.

### What is the root cause of that problem?
When we create a new distance request, we set a local asset image as the optimistic receipt image.
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/libs/actions/IOU.js#L870-L873

And the `isLocalFile` condition here doesn't consider the case of the web local asset.
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/libs/ReceiptUtils.ts#L69-L70

So, `isLocalFile` is always false.

If `isLocalFile` is false, we will try to load the image as if it's a remote image.
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/components/ReportActionItem/ReportActionItemImage.js#L64-L73

### What changes do you think we should make in order to solve the problem?

Add a new condition to `isLocalFile` to check for the local file.
```
const isLocalFile = ... || path === ReceiptGeneric;
```

**Comment by situchan** [comment] 2024-01-05 05:43
This is another regression from https://github.com/Expensify/App/pull/33946
cc: @namhihi237

**Comment by namhihi237** [comment] 2024-01-05 06:47
I can not reproduce it on a local, anyone can reproduce it.

**Comment by namhihi237** [comment] 2024-01-05 06:55
Seem this issue only reproduce on the remote server.

**Comment by namhihi237** [comment] 2024-01-05 07:48
Do we use right the domain host for image `staging.expensify.com` when i update to `staging.new.expensify.com`, it works

**Comment by mvtglobally** [comment] 2024-01-07 04:48
Still repro on build 1.4.22-2 


https://github.com/Expensify/App/assets/43995119/389ba213-3e3c-42a3-bb59-1c078a1b0882

**Comment by thienlnam** [comment] 2024-01-08 02:31
We're handling this regression in this PR https://github.com/Expensify/App/pull/34030

**Comment by thienlnam** [comment] 2024-01-08 06:36
Verified this is fixed on staging now

**Closed by thienlnam** 2024-01-08 06:36 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
