### ISSUE TITLE
Couldn't complete task until task page is visited

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26318] opened 2023-08-30 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace & add 3 accounts in announce room
2. From account A, assign a task to account B
3. Complete task from account B using checkbox in announce room
4. Observe you can complete/reopen task using checkbox if you are assignee
5. From account C try to complete/reopen task using checkbox
6. Observe you can't complete/reopen task until you visit task page
## Expected Result: 
Users in announce room should be able to complete/reopen task using checkbox without visiting task page.
## Actual Result: 
Users in announce room aren't able to complete/reopen task using checkbox without visiting task page.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b8109b1c-654a-4b9f-8668-7281b4e639a9

https://github.com/Expensify/App/assets/43996225/8b423d82-23ac-468e-a7f1-5eaa1b05db1e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692601727170219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment] 2023-08-31 05:46
Based on the Design Doc I think this might be intended behaviour. Asked in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1693460576960649?thread_ts=1692601727.170219&cid=C049HHMV9SM).

**Comment by thienlnam** [comment] 2023-08-31 17:02
Dupe of https://github.com/Expensify/App/issues/24169

**Closed by thienlnam** 2023-08-31 17:02 UTC
Labels: Daily, Bug
