### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Dupe detect-Incorrect total amount in the expense report, preview & LHN after deleting offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46449] opened 2024-07-29 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses
4. Click on the expense preview in main chat
5. Click on the first expense (important)
6. Go offline
7. Click Review duplicates
8. Click Keep this one on the second expense (important)
9. Click Confirm on the confirmation page
10. Check the total amount in the expense report and also the expense preview in the main chat and LHN

## Expected Result:
The total amount in the expense report, and expense preview in the main chat and LHN will update correctly

## Actual Result:
In the expense report, the total is 0.00
In the main chat, the expense preview is the sum of two expenses, including the deleted one
In the LHN, the preview for the main chat is 0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fcf48351-f53e-4254-8821-29f6e95994bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bae72e20bb144f65</li>
        <li>Upwork Job ID: 1818041683906527046</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103331326</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad / @muttmuure</details>

**Comment by lanitochka17** [comment] 2024-07-29 21:12
We think that this bug might be related to #wave-collect - Release 2

**Comment by roryabraham** [comment] 2024-07-29 21:48
definitely front-end since it's only for optimistic state

**Comment by roryabraham** [comment] 2024-07-29 21:51
confirmed that dupe detection is still behind a beta so demoting this.

**Comment by bernhardoj** [comment] 2024-07-30 05:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Total amount is incorrect when resolving duplicated transactions.

### What is the root cause of that problem?
When merging duplicates, we subtract the current report amount from all the duplicated transaction amounts.
https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/libs/actions/IOU.ts#L7679-L7692

However, the duplicated transaction array has duplicated items. When we have transactions 1 and 2, open the 1st transaction thread, and press Keep this one on the 2nd transaction, the duplicated transaction array will be [1, 1].

That's because the array contains the duplicates and also the `reviewingTransactionID`.
https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L282-L283

`reviewingTransactionID` is the transaction that we are currently reviewing. From the OP steps, we open transaction 1 and press Review duplicates, so the `reviewingTransactionID` is 1. `duplicates` contains the duplicated list of transactions. For example, transaction 1 duplicates list is [2], while transaction 2 duplicates list is [1]. Combined, we get [1, 1].

### What changes do you think we should make in order to solve the problem?

Instead of combining `reviewingTransactionID` and `duplicates`, we can just use `duplicates`.
```
const allTransactionIDsDuplicates = duplicates;
```

### What alternative solutions did you explore? (Optional)
Remove duplicated items from the array.
```
Array.from(new Set(allTransactionIDsDuplicates))
```

**Comment by akinwale** [comment] 2024-07-30 19:19
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/46449#issuecomment-2257481619) works here.

🎀👀🎀 C+ reviewed.

**Comment by roryabraham** [comment] 2024-07-30 19:33
weird, I wrote this code and I recall it working as expected when I tested it. Maybe I made a mistake or something else changed since then. Anyways, LGTM 👍🏼

**Comment by bernhardoj** [comment] 2024-07-31 05:44
PR is ready

cc: @akinwale

**Comment by CortneyOfstad** [comment] 2024-07-31 15:00
@muttmuure I am heading OoO until Tuesday (Aug. 6) so reassigning to keep eyes on this in the meantime — thanks!

**Comment by akinwale** [comment] 2024-08-14 05:37
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This was a regression from https://github.com/Expensify/App/pull/42503. [Comment](https://github.com/Expensify/App/pull/42503#issuecomment-2287889060).

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
* Launch Expensify
* Open a workspace chat report
* Submit two similar expenses (same amount, currency and merchant)
* Click on the expense preview in the main chat report
* Click on the first expense
* Go offline
* Click **Review duplicates**
* Click **Keep this one** on the second expense
* Click Confirm on the confirmation page
* Navigate back to the expense report
* Verify that the total amount is the same as the selected expense amount
* Navigate back to the main chat report
* Verify that the report preview amount is the same as the selected expense amount
* Navigate back to LHN (on mobile)
* Verify that the total amount in the LHN for the last message is the same as the selected expense amount

Do we agree 👍 or 👎?

**Comment by CortneyOfstad** [comment] 2024-08-14 21:54
## Payment Summary 

@bernhardoj -- to be paid $250 via NewDot
@akinwale -- paid $250 via Upwork

Regression test [here](https://github.com/Expensify/Expensify/issues/420486)

**Closed by CortneyOfstad** 2024-08-14 21:54 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-08-15 02:46
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-21 10:59
$250 approved for @bernhardoj
