### ISSUE TITLE
[$500] Dev:  Sign in banner for anonymous user don't have a highlighted green background color

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29058] opened 2023-10-07 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a public room AS user "A". Copy link to room.
2. Log out of app and open the link.

## Expected Result:
Sign in banner has a highlighted green background color

## Actual Result:
Sign in banner has dark green background color

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.78.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6e83f4b9-45c5-495f-b6f0-5dd3fb966e9c

![Screenshot_2023-10-08-02-01-46-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Expensify/App/assets/93399543/4ebb5585-0d3c-45c4-9a1b-f808dfbc7f22)
![Screenshot 2023-10-07 at 3 31 51 PM](https://github.com/Expensify/App/assets/93399543/d9d647b9-c503-40a6-874e-7015567fa114)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696672828432169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01215e33c324cbc768</li>
        <li>Upwork Job ID: 1710758391110152192</li>
        <li>Last Price Increase: 2023-10-07</li>
    </ul>
</details>

**Comment by maxconnectAbhi** [comment] 2023-10-08 04:56
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Sign in banner for anonymous user don't have a highlighted green background color


## What is the root cause of that problem?
` backgroundColor: theme.sidebar, `

## What changes do you think we should make in order to solve the problem?
` backgroundColor: theme. highlightBG, `

## What alternative solutions did you explore? (Optional)
NA

**Comment by kbecciv** [comment] 2023-10-10 14:51
Added bug label

**Comment by Pujan92** [comment] 2023-10-10 17:52
This is raised [here](https://github.com/Expensify/App/pull/28323#issuecomment-1755522727) and will be fixed there

**Comment by Pujan92** [comment] 2023-10-10 18:13
Basically, it's a regression from https://github.com/Expensify/App/pull/28277 so the author may fix this but as I was working on the same part I just made the fix based on the @shawnborton comment. I believe you will get a reporting bonus in that case.

**Comment by shawnborton** [comment] 2023-10-10 18:28
Should there be a reporting bonus here? This just seems like a regression from @adamgrzybowski's PR that needs to be fixed (cc @hayata-suenaga )

**Comment by hayata-suenaga** [comment] 2023-10-11 14:15
Everyone who posted proposals, I really appreciate your help. We're looking forward to working with you in the next issue 🚀

**Comment by twisterdotcom** [comment] 2023-10-12 17:03
Great okay, will just pay $250 to @ishpaul777.

**Comment by twisterdotcom** [comment] 2023-10-12 17:07
https://www.upwork.com/nx/wm/offer/27164055

**Comment by twisterdotcom** [comment] 2023-10-12 17:12
Ahhh, you're right! Thanks for correcting me!

**Comment by twisterdotcom** [comment] 2023-10-12 17:13
https://www.upwork.com/nx/wm/offer/27164192

**Comment by twisterdotcom** [comment] 2023-10-12 21:34
Paid!

**Closed by twisterdotcom** 2023-10-12 21:34 UTC
Labels: Daily, Bug
