### ISSUE TITLE
[$1000] Dev - excessive increase in Heap size indicating a major memory leak

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26010] opened 2023-08-26 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the app in Dev
2. Open chrome devtools and wait until the app is fully loaded
3. In devtools navigate to memory tab and take a Heap snapshot
4. Continuously switch between two small or empty reports back and forth for a while
5. Take a second Heap snapshot and notice the heap size
6. Repeat the process switching back and forth again between the same two reports for a while
7. Take a third Heap snapshot and notice the size still increasing even though it's the same two reports
## Expected Result: 
Heap memory should remain relatively stable when switching back and forth between the same two reports. This is indicative of effective memory management and garbage collection.
## Actual Result: 
There's a notable increase in the heap size with repeated actions, leading to degraded performance and even occasional crashes. This suggests a significant memory leak.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d8124dae-76be-4610-b445-a23a0d370ea4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AmjedNazzal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692349529815459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019948e426cdb9307a</li>
        <li>Upwork Job ID: 1696485214651981824</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-08-29 11:29
Reproducible 
<img width="226" alt="image" src="https://github.com/Expensify/App/assets/17131195/0be8c596-13f5-4fbc-b696-cf09d39d4eee">

**Comment by AJV009** [comment] 2023-09-01 07:25
Its probably JS debugging stuff like storing logs and things, since this doesn't happen on Prod, should this be a bug? I mean yeah someone can surely take a look at this but it's not a prod-affecting bug, right?

**Comment by AmjedNazzal** [comment] 2023-09-01 07:55
@AJV009 I would say someone should take care of this yes, this is making working on dev very difficult to the point that yesterday after using the app for a while it was taking almost 8GB of RAM which is insane. this is not normal at all.

**Comment by shubham1206agra** [comment] 2023-09-01 09:51
@AJV009 This is repro on prod also

**Comment by shubham1206agra** [comment] 2023-09-01 09:52
<img width="1512" alt="Screenshot 2023-09-01 at 3 22 05 PM" src="https://github.com/Expensify/App/assets/58412969/e8475443-b420-4f5b-b67a-9c96eb731f2e">

**Comment by sonialiap** [comment] 2023-09-01 11:31
Not overdue

**Comment by AJV009** [comment] 2023-09-01 11:52
@shubham1206agra I did try it on prod too.
My observations were: It was automatically getting cleared on prod (not on dev)
Appreciate that you found the root cause. 
Your test data isn't enough for prod. Look carefully and wait for a few seconds, the sizes go up and also come down. I tested for quite some time trying to push it beyond 300 MB but then the garbage collection or whatever was responsible was working fine.
I assume a fix for this involves rewriting or maybe modifying the way variables or listeners are being created/executed?

**Comment by shubham1206agra** [comment] 2023-09-01 12:01
No I waited for some time before taking snapshot

**Comment by shubham1206agra** [comment] 2023-09-01 12:03
Let me just open the tab for 10 minutes and see the heap size

**Comment by shubham1206agra** [comment] 2023-09-01 12:15
See snapshot 3 and current heap size

**Comment by shubham1206agra** [comment] 2023-09-01 13:15
@AmjedNazzal Can you point out the PR? Or what kind of PR was that?

**Comment by sonialiap** [comment] 2023-09-06 13:12
Sounds like we know what the issue is, is that right? Please submit proposals so that we can get this fixed!

**Comment by sonialiap** [comment] 2023-09-12 06:13
@narefyev91 is it correct that we're still looking for proposals?

**Comment by narefyev91** [comment] 2023-09-12 06:36
> @narefyev91 is it correct that we're still looking for proposals?

Yup - waiting for some proposal here

**Comment by ewanmellor** [comment] 2023-09-16 04:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Major memory leak, causing performance issues. Possibly only on dev (though comments above disagree).

### What is the root cause of that problem?

I think I have found the root cause of at least one problem. In `@expensify/react-native-web` there is a `ModalPortal` component that creates an empty div to use as the portal for the modal when it opens. These are not getting cleaned up, so the DOM is growing with every switch between reports. I added some debugging code to pass the modal ID through to `ModalPortal` so that I could see what's going on, and you can see that these are not going away. I'm getting 3 of these with every switch so they grow quickly.

<img width="435" alt="Screenshot 2023-09-15 at 9 32 47 PM" src="https://github.com/Expensify/App/assets/894011/aba925c2-c1f2-4987-bbb3-331b440ffb33">

The reason it's so memory hungry is there are a lot of React event handlers and FiberNodes hanging off these (at least in dev). I see those when comparing sequential memory snapshots.

At the React component level we seem to be recycling `ModalPortal` instances correctly, which is surprising. I don't know why the `ModalPortal` cleanup `useEffect` is not running when the `ModalPortal` component instance is deallocated. That needs digging into.

### What changes do you think we should make in order to solve the problem?

I don't have code changes ready to go yet. I will need to dig into why the cleanup effects are not running, and that will take some time. I'm looking for approval to go ahead with this first.

Of course, this might only be one leak out of many, and I can't guarantee that this is the only leak. It does look like big one though.

**Comment by narefyev91** [comment] 2023-09-18 07:53
Agree with @ewanmellor - investigation maybe a much more deeper here - but in any case fixing portals will make app faster
🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment] 2023-09-19 07:34
Interesting find! Looking forward to the results of the investigation.

**Comment by ewanmellor** [comment] 2023-09-20 20:54
@robertjchen OK, so the thing I was chasing turns out to be pretty fundamental to the whole app.

Inside `CentralPaneNavigator` we use `FreezeWrapper` > `Freeze` from react-freeze > `Suspense` from React 17. This means that when we navigate forward, the screens further back in the nav stack are frozen in the sense they don't receive event updates, but they're otherwise preserved, so all the memory for them remains allocated. For a rich view like `ReportScreen` this can mean 10s or even 100s of MB of memory for every one.

When you switch between items in the LHN, you're moving forward in nav history, so even toggling back and forth between two items allocates new screens every time. In general, simply navigating around the app without using the browser back button is costing huge amounts of memory for every nav. This memory does get released if you use the browser history to go back, but it's not surprising that devs are seeing crashes during ordinary use.

Specifically for `ModalPortal` as mentioned above, the problem is that the modals are instantiated by their host page (e.g. a lot of things have a `ConfirmModal` attached to some functionality) and so as long as all the pages are on the nav stack, so are all their modal portals. There are DOM elements for each of these because `ModalPortal` allocates a div behind the scenes, and so all of these remain in the DOM until the user navigates back using the browser history.

I don't really have a good way to proceed from here. It seems that the app fundamentally is deliberately trying to keep all this memory allocated. The question is really whether you think you can afford that. 10s-100s of MB per LHN click seems insanely expensive and very likely to keep biting people. We could certainly reduce the cost of `ModalPortal` specifically (why do they need to exist when the modal is not open?) but I think that's probably scratching around the edges of a larger issue.

**Comment by robertjchen** [comment] 2023-09-21 04:23
@ewanmellor great investigation! Maybe let's take this back to Slack to discuss with the broader team on how we'll move forward from here  🤔

**Comment by ewanmellor** [comment] 2023-09-21 04:28
@robertjchen I'm new to this project (only joined Slack on Monday). Can you lead that discussion?

**Comment by robertjchen** [comment] 2023-09-22 07:12
yesss, I'll start a thread and drop the link here

**Comment by robertjchen** [comment] 2023-09-25 10:44
Starting the discussion sometime this week

**Comment by sonialiap** [comment] 2023-10-02 04:51
@robertjchen did you get a change to start the discussion? If yes, could you link to it so that I can follow along and help move the discussion/resolution of this issue?

**Comment by sonialiap** [comment] 2023-10-09 04:05
@robertjchen I know you've been busy with other issues but could we get an update on this? If you're swamped, maybe you can find someone to take over this issue for you? Not an engineer but sounds like this memory leak is causing issues for contributors so it would be good to get fixed

**Comment by robertjchen** [comment] 2023-10-10 02:44
Yep sorry! Let me kick things off in #expensify-open-source and in internal channels. Will hand this off to those who are more familiar with the low-level aspects 👍

**Comment by robertjchen** [comment] 2023-10-11 04:13
Let me clean up the above comments, as more people will be participating in the discussion here soon

**Comment by robertjchen** [comment] 2023-10-11 04:28
Discussion here! https://expensify.slack.com/archives/C01GTK53T8Q/p1696998420646989

**Comment by robertjchen** [comment] 2023-10-12 06:49
Thanks for the investigation and analysis here, it sounds like we'll be addressing this specifically in the issue here: https://github.com/Expensify/App/issues/27651

To avoid duplication and confusion, I'll close this one out and maybe we can continue the conversation there? 🙏

**Closed by robertjchen** 2023-10-12 06:49 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by AmjedNazzal** [comment] 2023-10-12 07:03
@robertjchen do I get the bug report pay? I've reported this a long time ago before the bounty amounts were changed.
