### ISSUE TITLE
[HOLD for payment 2024-11-18] [HOLD for payment 2024-11-14] Invoices - Company website field does not show the website when it is auto populated

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52097] opened 2024-11-06 09:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+sjdosjdsod@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with Expensifail account.
3. Create a new workspace.
4. Go to workspace settings > More features.
5. Enable Invoices.
6. Go to Invoices.
7. Click Company website.

## Expected Result:
Company website field should show the website because the company website is auto populated in Step 7.

## Actual Result:
Company website field does not show the website when the company website is auto populated in Step 7.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/57c281f7-5ef1-4946-9cfa-9e1aa54cd90b
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by cristipaval** [comment] 2024-11-06 11:35
> I will fix this one as it came from my PR.

Thanks @Krishna2323! @ahmedGaber93 is the C+ of the offending PR, correct?

**Comment by ahmedGaber93** [comment] 2024-11-06 12:31
> what do you think we should do here? Should we remove the default value, or should we also display it on MenuItemWithTopDescription?

I think populate the website here for consistent is not the good decision and we should remove it.

**Comment by Julesssss** [comment] 2024-11-06 13:03
Thanks for fixing. In the meantime I am removing blocker label as it's a minor issue with a new flow.

**Comment by cristipaval** [comment] 2024-11-06 14:37
Thanks @Julesssss!

**Comment by Julesssss** [comment] 2024-11-07 09:48
Fixed here: https://github.com/Expensify/App/pull/52155

**Comment by sakluger** [comment] 2024-11-12 01:29
Since this is a regression from https://github.com/Expensify/App/pull/51545, I don't think any payment is due. Please correct me if I'm wrong.

**Comment by ahmedGaber93** [comment] 2024-11-12 02:24
This is correct

**Comment by sakluger** [comment] 2024-11-14 20:59
Perfect, thanks! We're good to close the issue then.

**Closed by sakluger** 2024-11-14 20:59 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
