### ISSUE TITLE
[HOLD][$250] Send invoice - Unable to dismiss error after editing the amount of paid invoice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43577] opened 2024-06-12 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Send invoice to User B
3. [User A and B] Go to invoice thread
4. [User B] Pay the invoice
5. [User A] Quickly change the amount
6. [User A] Dismiss the error under the amount edit system message

## Expected Result:
User A will be able to dismiss the error under the amount edit system message

## Actual Result:
User A is unable to dismiss the error under the amount edit system message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2fee6c73-3c74-48b4-9a5f-00a8d0b11f48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ab97d06171fcfe0</li>
        <li>Upwork Job ID: 1801113320162208595</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 102939661</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by lanitochka17** [comment] 2024-06-12 14:30
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 14:31
We think that this bug might be related to #vip-bills

**Comment by kadiealexander** [comment] 2024-06-17 05:52
@getusha bump, please review.

**Comment by getusha** [comment] 2024-06-17 10:04
>@getusha Thanks for your feedback. I don't think it's a regression from https://github.com/Expensify/App/pull/37875. The problem is for the combine report we have both iou report actions and transaction thread report actions but we always pass the report.reportID when we clear the report action error. As such, the error cannot be deleted when we dismiss the system message that is a report action of transaction thread report.

@dominictb we have to understand where this issue came from, i tried to see commit history and it looked like it always has been like that. can we investigate about that?

**Comment by getusha** [comment] 2024-06-18 12:47
@dominictb thanks, i'll check it! could you share a branch so i can test your solution?

**Comment by getusha** [comment] 2024-06-25 16:05
@kadiealexander, @ZhenjaHorbach will handle this a C+

**Comment by kadiealexander** [comment] 2024-07-01 07:46
@ZhenjaHorbach any update on reviewing the proposals?

**Comment by MariaHCD** [comment] 2024-07-16 18:37
Hmm, I don't have the most context on the SendInvoice API command. @cristipaval would you mind taking a look here?

I can take a closer look tomorrow.

**Comment by cristipaval** [comment] 2024-07-17 12:12
yes, I do agree that this is a BE issue as per [this proposal](https://github.com/Expensify/App/issues/43577#issuecomment-2164405961). I can take it over, @MariaHCD if you're busy with other staff.

**Comment by cristipaval** [comment] 2024-07-19 20:58
Held on https://github.com/Expensify/App/issues/43797

**Comment by cristipaval** [comment] 2024-07-19 20:59
> @cristipaval As per [my proposal](https://github.com/Expensify/App/issues/43577#issuecomment-2164405961), we still need FE change to add another param to `SendInvoice` API. Since the C+ also approved my proposal [here](https://github.com/Expensify/App/issues/43577#issuecomment-2221210580), can you please assign me here, and then I can handle the FE change once the BE change is complete?

This issue has the same root cause as [this one](https://github.com/Expensify/App/issues/43797), and we already have a contributor who proposed a more complete [solution](https://github.com/Expensify/App/issues/43797#issuecomment-2181500127).

**Comment by cristipaval** [comment] 2024-07-29 12:58
Still held

**Comment by cristipaval** [comment] 2024-08-07 10:27
still held

**Comment by cristipaval** [comment] 2024-08-16 10:26
We're actively working on the issue that this one is held on

**Comment by cristipaval** [comment] 2024-08-26 09:51
[The PR](https://github.com/Expensify/App/pull/46001) fixing the issue that this one is held on has been merged. Waiting for it to get deployed.

**Comment by cristipaval** [comment] 2024-08-27 10:04
This issue can be retested in staging

**Comment by ZhenjaHorbach** [comment] 2024-09-10 21:23
@cristipaval @kadiealexander 
I can't reproduce 
Let's close this issue !

**Closed** 2024-09-17 22:39 UTC
Labels: Weekly, Internal, Overdue, Bug
