### ISSUE TITLE
[HOLD for payment 2023-06-02] Wrong tooltip in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19091] opened 2023-05-17 00:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a thread from a message that it is not yours
2. Post a comment if you want
3. Hover the avatar in the header.
4. Pay attention to the tooltip.

## Expected Result: 
Tooltip should be from the original commenter
## Actual Result: 
Tooltip is from the person that started the thread?

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14-14
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/98489c14-d928-4dde-893b-bb616b3f701e

![Monosnap New Expensify 2023-05-16 18-01-47](https://github.com/Expensify/App/assets/43996225/ede1b16a-ecfd-43ea-bf9e-1df31482f83f)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @pecanoro 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684252966967399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01124fd79eccfcd109</li>
        <li>Upwork Job ID: 1658736362692325376</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by eric-delynn** [comment] 2023-05-17 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After create a thread from a message that it is not mine and hover the avatar in the header, tooltip is not correct.
### What is the root cause of that problem?
As I checked [MultiAvatars component](https://github.com/Expensify/App/blob/main/src/components/MultipleAvatars.js),
Tooltip shows always `props.avatarTooltips` if icons's length is 1.
### What changes do you think we should make in order to solve the problem?
As I checked [getIcons function](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js), it returns one icon if report is thread.
So I will add `isThread` field on `result` object like this:
https://prnt.sc/k-lxH5GDYMuv
And I will update tooltip on line 69 of [MultiAvatars component](https://github.com/Expensify/App/blob/main/src/components/MultipleAvatars.js) like this:
`<Tooltip text={props.avatarTooltips[props.icons[0].isThread ? 1 : 0]}>`
It works perfectly.
Please check this short video.
https://www.loom.com/share/5e5ec7717dc849119cd01883a7861e9e
### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2023-05-17 07:35
@eric-delynn, thank you for the proposal! Due to an internal deadline, I'll be taking this bug internally. 

Some feedback on your proposal, because we use a specific shape for passing icon data throughout the app, we don't want to add a flag for such a specific case. It seems that the root cause is actually that we are passing in an incorrect avatarTooltips object.

Thanks again and please check out our other bugs with the `Help Wanted` Label [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+NOT+Hold+in%3Atitle+sort%3Acreated-desc+label%3ABug)!

**Comment by s77rt** [comment] 2023-05-24 23:39
Not overdue. [PR](https://github.com/Expensify/App/pull/19104) has been merged.

**Comment by MitchExpensify** [comment] 2023-05-29 20:45
Set cal reminder to pay on the 2nd

**Comment by MitchExpensify** [comment] 2023-06-06 10:50
Whoops! Thanks for the bump and sorry for the delay. My tried and tested Cal reminder failed me! 😆 

Paid and contract ended - Closing as no new testing steps required as deemed [here](https://github.com/Expensify/App/issues/19091#issuecomment-1564698997)

**Closed by MitchExpensify** 2023-06-06 10:50 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
