### ISSUE TITLE
New Search - Header changes from Expensify/Search to Expenses when opening an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41759] opened 2024-05-07 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Troubleshoot
3. Tap Navigate next to New Search Page
4. Note that the header shows Expensify / Search
5. Tap on any expense

## Expected Result:
The header in Search page should remain consistent when opening an expense from it

## Actual Result:
The header in Search page changes to Expenses when opening an expense from it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/250dbe28-2c2a-44c5-8299-5c94fb4168f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-07 13:00
@danieldoglas  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-07 13:00
We think that this bug might be related to #vip-vsp

**Comment by danieldoglas** [comment] 2024-05-07 13:02
@grgia can you take a look into this one?

**Comment by grgia** [comment] 2024-05-07 13:04
Not a bug, the "header" in the search results is the To -> From pattern

**Comment by grgia** [comment] 2024-05-07 13:05
Closing

**Closed by grgia** 2024-05-07 13:05 UTC
Labels: DeployBlockerCash, Engineering, Hourly
