### ISSUE TITLE
[$500] Web - Attachment Remains in LHN When Sending Distance Request After Attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27041] opened 2023-09-08 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the "+" icon.
2. Select "Request money" and then choose "distance."
3. Choose the starting and finishing points.
4. Click the "Next" button to proceed.
5. Select a workspace room and send the request.
6. Attach a file and send it.
7. After sending the attachment, request distance again.
8. Observe that the LHN still displays the attachment.
9. Send a message and delete it.
10. Check the LHN.

## Expected Result:
The attachment "[Attachment]" should not appear in the LHN when sending a distance request after attaching a file.

## Actual Result:
The attachment "[Attachment]" is still shown in the LHN when sending a distance request after attaching a file.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bdc478e4-dd37-4732-919b-7abadf2b3bf0

https://github.com/Expensify/App/assets/93399543/9e0a29c2-eb80-44f8-b964-4684b308bdb2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693836149442659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189e5a71b18ef01d6</li>
        <li>Upwork Job ID: 1700180547022577664</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-08 16:15
this is fixed here https://github.com/Expensify/App/issues/24246

**Comment by trjExpensify** [comment] 2023-09-08 16:18
Yeah, dupe with the same root cause. Closing!

**Closed by trjExpensify** 2023-09-08 16:18 UTC
Labels: External, Daily, Help Wanted, Bug
