### ISSUE TITLE
[HOLD for payment 2023-11-22] [$1000] Settings - Help -  Not auto focusing on search field for Help page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27158] opened 2023-09-11 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login and then open Settings.
2. Open help.
3. Tap on search icon.

## Expected Result:
When user tap on search icon it opens search tab but not focusing on Search field, keyboard should open on android/ios devices.

## Actual Result:
When user tap on search icon ,Search field should be focused, keyboard should open on android/ios devices.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (4).webm](https://github.com/Expensify/App/assets/93399543/9bdab5da-1161-4574-9510-4429bd4aaa58)

https://github.com/Expensify/App/assets/93399543/5c5bfb61-7673-43d8-8d18-584c29067989

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Harshizonnet
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694070713281919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01884263b0de13d0a5</li>
        <li>Upwork Job ID: 1701248465382961152</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27657496</li>
<li>getusha | Contributor | 27657498</li>
<li>Harshizonnet | Reporter | 27657499</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-09-11 15:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search field not auto focused when opening side bar on help page
### What is the root cause of that problem?

In

https://github.com/Expensify/App/blob/1ae51cc025881f517451acf70d7ea383a0ed395f/docs/assets/js/main.js#L102-L116

We are not focusing the search field when we open the sidebar, inside `openSidebar` function.


### What changes do you think we should make in order to solve the problem?


We should select the search field and focus the input when openSidebar is triggered, using:
```js
document.getElementById('gsc-i-id1').focus()
```
### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment] 2023-09-13 19:33
melvin double assigned. im unassigning myself since i was the second assignee!!

**Comment by anmurali** [comment] 2023-09-27 02:05
This is worth fixing!

**Comment by anmurali** [comment] 2023-09-27 02:05
@aimane-chnaif can you pls review those proposals posted?

**Comment by anmurali** [comment] 2023-10-04 01:19
@aimane-chnaif can you pls review those proposals posted?

**Comment by getusha** [comment] 2023-10-04 14:53
@aimane-chnaif could you share a video? its working for me

https://github.com/Expensify/App/assets/75031127/108168ff-d64b-4c22-ab0d-6c8582bfbed4

**Comment by getusha** [comment] 2023-10-05 15:10
> Works on Safari though

@aimane-chnaif that's strange, i will check on other browsers i tested on chrome.

**Comment by anmurali** [comment] 2023-10-24 21:54
@aimane-chnaif - should we raise the price to $1000?

**Comment by anmurali** [comment] 2023-11-01 03:55
Raised the price. Let's see if we get better proposals.

**Comment by 5war00p** [comment] 2023-11-01 07:57
I see the messed up input field like this:

https://github.com/Expensify/App/assets/57614947/0fd5a8fa-99aa-4e24-b604-dace9d51d212

Did anyone noticed? both on local and [new.expensify.app](https://new.expensify.com/)

**Comment by 5war00p** [comment] 2023-11-02 06:18
@aimane-chnaif can you share your chrome version?

**Comment by 5war00p** [comment] 2023-11-02 06:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search Input field not auto focusing for when sidebar expands

### What is the root cause of that problem?
As the element loads before and we are showing that later (conditionally by opening sidebar), we need to focus manually.

### What changes do you think we should make in order to solve the problem?

We need to call the `.focus()` on the input element like below:
```
document.getElementById('gsc-i-id1').focus()
```
but there is a known bug in chrome that sometimes it wont focus due to tabIndex value.
References:
- https://bugs.chromium.org/p/chromium/issues/detail?id=467043
- https://gist.github.com/TakayoshiKochi/0f658e372a1d382523bd

So I guess setting up tabIndex like below should work:
```
    // Add required into the search input
    const searchInput = document.getElementById('gsc-i-id1');
    searchInput.setAttribute('required', '');
    searchInput.tabIndex = 0;
```

### What alternative solutions did you explore? (Optional)

Alternatively, as focus sometimes won't work because input element not fully loaded. So doing this will actually add a delay:
```
    setTimeout(() => {
        document.getElementById("gsc-i-id1").focus();
    }, 0);
```

**Comment by 5war00p** [comment] 2023-11-02 07:18
Working Attachments:

- Brave Browser:
![Kapture 2023-11-02 at 12 41 56](https://github.com/Expensify/App/assets/57614947/2c192dad-e797-4fa4-ae83-4d498927c61e)

- Chrome Browser:
![Kapture 2023-11-02 at 12 45 10](https://github.com/Expensify/App/assets/57614947/871c79ab-c812-48ae-a806-eb5029efa3c3)

- Safari Browser:
![Kapture 2023-11-02 at 12 47 23](https://github.com/Expensify/App/assets/57614947/4b2583ca-c723-4253-b1c9-7a3310737de3)

**Comment by 5war00p** [comment] 2023-11-02 07:19
> @5war00p None of your solutions work for me

Hey @aimane-chnaif , can you share full screen recording with code and the webpage? Also, I will try installing same of your version of chrome.

**Comment by 5war00p** [comment] 2023-11-02 07:28
One thing is add the focusing line to the start of the function. Also share me where did you added `tabindex`.
The other thing is you code looks outdated, I'm currently in sync with main. May be you can give your branch or fork so that I can checkout from there.

**Comment by 5war00p** [comment] 2023-11-02 07:37
Can you checkout to my branch and test it: `5war00p:auto-focus-input-in-help`?

**Comment by 5war00p** [comment] 2023-11-02 07:50
Yes, thats correct, tabIndex or setTimeout are just a wrappers to make sure element focuses. I couldn't find your chrome version on internet may be send me your chrome app.

**Comment by 5war00p** [comment] 2023-11-02 07:54
Also try on different chrome profile.

**Comment by b4s36t4** [comment] 2023-11-02 07:56
> Another interesting thing is that it works on localhost:4000 even on same chrome browser. But still not work on 127.0.0.1:4000

I tried both, but it's working.

**Comment by 5war00p** [comment] 2023-11-02 07:57
@aimane-chnaif Looks like something messed with your chrome, try restarting once using `chrome://restart`

**Comment by robertjchen** [comment] 2023-11-06 15:22
Thanks, agreed- let's just run with @getusha 's original proposal: https://github.com/Expensify/App/issues/27158#issuecomment-1714072642

**Comment by getusha** [comment] 2023-11-08 00:45
@aimane-chnaif the [PR](https://github.com/Expensify/App/pull/31039) is ready!

**Comment by Harshizonnet** [comment] 2023-11-11 05:16
> @robertjchen Haven't received the offer on upwork, i think we need to apply the `External` label and reassign

Me too.

**Comment by rushatgabhane** [comment] 2023-11-14 06:18
Posting here 

Hi, could we please revert the changes in https://github.com/Expensify/App/pull/31039
My [PR](https://github.com/Expensify/App/pull/31290) to fix this was merged 10 mins before.

Also, this is a part of helpdot project. (no seperate issue based pay here)

https://github.com/Expensify/App/blob/2c7062b917a2d31b709691166633f171dd1fce8c/docs/assets/js/main.js#L104-L112

**Comment by rushatgabhane** [comment] 2023-11-14 06:30
Yeah that sounds fair! 

To move things forward, @getusha could you please confirm if you'll be creating a revert PR 🙇

**Comment by rushatgabhane** [comment] 2023-11-14 06:32
duplicate issues and effort happen in a large project. it's understandable :)

**Comment by anmurali** [comment] 2023-12-06 02:09
All done.

**Closed by anmurali** 2023-12-06 02:09 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
