### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Wrong validation message when sending invoice 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49286] opened 2024-09-16 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726459401827979

## Action Performed:
1. Click green (+) button
2. Send invoice
3. Enter $200
4. Choose recipient
5. Fill in company name (Dubby Co)
6. Fill in company website (www.dubbyco.com)
## Expected Result:
Expected www.dubbyco.com to be a valid website address
## Actual Result:
Gives error saying "Please enter a valid website using lowercase characters"
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/0767a4d7-0299-4c3a-a5e9-ef6ad18e1e82

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/4344065d-2b4c-4a91-9631-8b74a128f25a

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835835067982464212</li>
        <li>Upwork Job ID: 1835835067982464212</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104377926</li>
<li>Krishna2323 | Contributor | 104377928</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by nkdengineer** [comment] 2024-09-16 17:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong validation message when sending invoice

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/3c6526d79ddefc71b18c07139ce02f02d3543b8d/src/libs/ValidationUtils.ts#L236-L243), we are considering that a valid website must include `http/https/ftp` in the URL, so a website like [www.example.com](http://www.example.com/) would be an invalid website.

### What changes do you think we should make in order to solve the problem?


We should use a new regex here.
```
    const regex = /^(https?:\/\/)?(www\.)[a-zA-Z0-9-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$/;
```

with regex above, `https://www.example.com`, `http://example.com`, `www.example.com` is valid website
`example.com`, `example` is invalid website

### What alternative solutions did you explore? (Optional)

**Comment by bikramiter** [comment] 2024-09-17 11:52
https://github.com/Expensify/App/blob/3c6526d79ddefc71b18c07139ce02f02d3543b8d/src/libs/ValidationUtils.ts#L236-L243

Note: As mentioned in the comment, this might need the corresponding scheme handling on the backend as well.

**Comment by ahmedGaber93** [comment] 2024-09-17 13:03
>  this might need the corresponding scheme handling on the backend as well.

I think it should be done in FE side, not BE.

**Comment by ahmedGaber93** [comment] 2024-09-18 06:23
Based on the issue [Slack conversation](https://expensify.slack.com/archives/C049HHMV9SM/p1726459401827979), We have three possible options to fix this issue:
1. allow user to type URL without `https://` and add it in behalf of the user before sending to BE
2. keep the current validation and just displaying the correct error message `e.g. url must start with https://`
3. add a default value `https://` prefix on the input like this

![Screenshot 2024-09-17 at 11 20 10 PM](https://github.com/user-attachments/assets/8b29d3d1-3256-46c5-a9b1-c6f37a2cc062)


Just to confirm, the expected result is option one? @kadiealexander @dubielzyk-expensify

**Comment by dubielzyk-expensify** [comment] 2024-09-19 03:48
My personal take is 1 and 3 should be done here, but I dunno the technical or security implications of 1. I'd at least say 3 should be done.

Keen to hear what @trjExpensify @JmillsExpensify @Expensify/design thinks

**Comment by shawnborton** [comment] 2024-09-19 04:23
Yeah that makes sense to me. Or even just do 2 and 3 might be easy without needing back end changes?

**Comment by dubielzyk-expensify** [comment] 2024-09-19 05:16
Yeah that also works. Feels a bit inelegant that we don't validate it properly though, but perhaps it's the right priority at this time 👍

**Comment by ahmedGaber93** [comment] 2024-09-19 06:58
I think We can use option one without any backend change, we will allow the user to type `www.dubbyco.com` and send the complete format `https://www.dubbyco.com` to the backend. 

We already have a function for adding the missing `https://` protocol in frontend [sanitizeURL](https://github.com/Expensify/expensify-common/blob/1713f28214f0e7176c4fd13433fb0ea15491ebf9/lib/str.js#L1049)

**Comment by nkdengineer** [comment] 2024-09-19 08:22
[updated proposal](https://github.com/Expensify/App/issues/49286#issuecomment-2353514187) following this comment [here](https://github.com/Expensify/App/issues/49286#issuecomment-2360146626)

**Comment by dubielzyk-expensify** [comment] 2024-09-19 10:06
Sure. Let's go with option 1 and 3 then unless @shawnborton thinks otherwise. If it's all front-end stuff then chuck the prefix in and validate it to be a URL 🫰

**Comment by ahmedGaber93** [comment] 2024-09-19 10:37
@dubielzyk-expensify the option 3 is already used on company website on bank account steps, but it has [two cases](https://github.com/Expensify/App/blob/37bf6b2fef128786dfcd83257a56f56c0cd1eb3d/src/libs/BankAccountUtils.ts#L5-L7)

A. if user email is not on private domain, the default value will be prefix `https://`     
B. if user email is on private domain, the default value will be generated email `https://www.privatedomain.com` 

Should we use the same UX behavior here for consistency or just use case A? And if we will use the both cases, should we also add default value for company name like case B (if user email is on private domain, company name default value will be `privatedomain`)?

**Comment by shawnborton** [comment] 2024-09-19 12:38
I'm down with a combo of 1 and 3. As for the latest question... I feel like the default value of https:// would be enough?

**Comment by ahmedGaber93** [comment] 2024-09-19 13:29
Thanks, that's great.

**Comment by trjExpensify** [comment] 2024-09-19 15:42
I'm not sure I'm following the 1 and 3 combo really. If we do 3, `https://` is prefixed in the field and can't be removed, so wouldn't doing 3 only be enough?

If @ahmedGaber93 is saying in the bank account flow we populate your private domain email address into the field already, that kinda' makes sense to copy/paste over here in the invoice flow.

**Comment by ahmedGaber93** [comment] 2024-09-19 22:42
> If we do 3, `https://` is prefixed in the field and can't be removed, so wouldn't doing 3 only be enough?

@trjExpensify `https://` can be removed by the user. It's a default value for the input. and this is the way we used in bank account flow

**Comment by trjExpensify** [comment] 2024-09-19 23:02
>@trjExpensify https:// can be removed by the user. It's a default value for the input. and this is the way we used in bank account flow

Oh right, that seems silly doesn't it if we require it?

**Comment by ahmedGaber93** [comment] 2024-09-19 23:05
Yeah, I am not sure if it required or not. But maybe we need to allow the user to remove it and type other scheme like `http://`

**Comment by ahmedGaber93** [comment] 2024-09-19 23:08
@Krishna2323 Yes, `prefixCharacter="https://"` also can be another possible option

**Comment by dubielzyk-expensify** [comment] 2024-09-19 23:15
I'm okay with only doing 3 👍

**Comment by shawnborton** [comment] 2024-09-20 05:44
Works for me too!

**Comment by ahmedGaber93** [comment] 2024-09-20 12:06
Ok, but the `https://` prefix will be removable or not? It is removable in current bank account flow

**Comment by dubielzyk-expensify** [comment] 2024-09-23 07:15
I think we should still technically make it removable if we also allow `http://`. Will also make it easier to copy a link if users prefer to do that.

**Comment by ahmedGaber93** [comment] 2024-09-23 10:49
Ok, I will summarize the expected behavior from discussion to be clear for contributors
1. Add a removable `https://` prefix [link](https://github.com/Expensify/App/issues/49286#issuecomment-2362357983)
2. If user email is on a private domain, populate a default value from this domain [link paragraph 2](https://github.com/Expensify/App/issues/49286#issuecomment-2361377677)

This behavior is exactly like the bank account flow.

**Comment by joekaufmanexpensify** [comment] 2024-09-23 19:54
Noting I came across this same issue and reported it [here](https://expensify.slack.com/archives/C049HHMV9SM/p1727116678974129). But we're not proceeding as I see we're fixing it here!

**Comment by ahmedGaber93** [comment] 2024-09-24 04:37
@Krishna2323 Your proposal looks to have what we need to move forward, but can you update your proposal to clean the unnecessary points and make it match this expected behavior https://github.com/Expensify/App/issues/49286?notification_referrer_id=NT_kwDOAnOXjrQxMjQyOTk3MjU3Mjo0MTEyOTg3MA#issuecomment-2367859204

![Screenshot 2024-09-23 at 9 30 51 PM](https://github.com/user-attachments/assets/2db0eefd-1151-4da9-8ce9-f4e9f41c680d)

**Comment by ahmedGaber93** [comment] 2024-09-25 07:54
@Krishna2323 's [proposal](https://github.com/Expensify/App/issues/49286#issuecomment-2353617400) LGTM!

🎀 👀 🎀 C+ reviewed.

**Comment by marcaaron** [comment] 2024-09-25 20:02
>allow user to type URL without https:// and add it in behalf of the user before sending to BE

How would we know that the website uses https?

I'm not really follower why we require `https://` at all? It doesn't seem like it would be necessary.

**Comment by ahmedGaber93** [comment] 2024-09-26 08:03
> > allow user to type URL without https:// and add it in behalf of the user before sending to BE
How would we know that the website uses https?

@marcaaron This was one of the possible options, but we didn't decide to use it. We have chosen the option 3 "add a default value `https://` prefix on the input like this"

![Screenshot 2024-09-17 at 11 20 10 PM](https://github.com/user-attachments/assets/8b29d3d1-3256-46c5-a9b1-c6f37a2cc062)


This default value `https://` is removable, so user able to remove it and type `http://`. We already have the same behavior on bank account flow.

**Comment by ahmedGaber93** [comment] 2024-09-30 18:07
@marcaaron What do you think https://github.com/Expensify/App/issues/49286#issuecomment-2376220885 ?

**Comment by ahmedGaber93** [comment] 2024-10-03 19:58
@marcaaron What do you think https://github.com/Expensify/App/issues/49286#issuecomment-2376220885 ?

**Comment by marcaaron** [comment] 2024-10-08 00:54
>This was one of the possible options, but we didn't decide to use it

Can you expand on this a bit?

>This default value https:// is removable, so user able to remove it and type http://. We already have the same behavior on bank account flow.

OK, but why not accept anything that remotely looks like a website?

**Comment by ahmedGaber93** [comment] 2024-10-08 12:18
> Can you expand on this a bit?

We have three possible option [here](https://github.com/Expensify/App/issues/49286#issuecomment-2357604009), and on this issue discussion we decide to use option 1.

> OK, but why not accept anything that remotely looks like a website?

In this case, we need to format it before send it to backend, because current [backend validation](https://github.com/Expensify/App/blob/3c6526d79ddefc71b18c07139ce02f02d3543b8d/src/libs/ValidationUtils.ts#L236-L239) do that, and if we allow user to type `www.domain.com` and sent it to backend as `https://www.domain.com` there is a small error chance that the link starts with `http` not `https`

@marcaaron what do you think?

**Comment by marcaaron** [comment] 2024-10-09 00:53
I think I disagree with showing `https://` at all? It just doesn't make sense since a website could use `http://` and it's also acceptable to the current backend implementation. I think we should try to take whatever input the user passes here and save it with the least amount of friction as possible.

current backend php code for reference:

```php
$hasValidScheme = preg_match('/^(https?|ftp):\/\//', $website);
```

If there's no valid scheme we can append `http://` before sending to the API and that should be fine.

@shawnborton @dubielzyk-expensify does that sound good to you guys or am I missing something?

**Comment by dubielzyk-expensify** [comment] 2024-10-09 02:26
I don't mind too much about what we do as long as we allow for people entering without the `http://` and `https://` cause I think it's pretty common for people to just write `www.theirwebsite.com` so as long we don't throw an error for that, I'm okay.

**Comment by ahmedGaber93** [comment] 2024-10-09 13:20
@Krishna2323 I think add new parameter to [sanitizeURL](https://github.com/Expensify/expensify-common/blob/925233f5b953dfbc45af2caef08db221c61b26ae/lib/str.ts#L976-L984) is better than create new one
```diff
-sanitizeURL(url: string): string {
+sanitizeURL(url: string, defaultScheme = 'https'): string {

-const website = match[3] ? match[2] : `https://${match[2]}`;
+const website = match[3] ? match[2] : `${defaultScheme}://${match[2]}`;
```

also for the validation, we can keep the current [validation](https://github.com/Expensify/App/blob/6c8211166e3b570a8947f6ff07a35973ecbcffb8/src/libs/ValidationUtils.ts#L236-L243) and use the sanitized URL `isValidWebsite(sanitizeURL(values.companyWebsite, 'http'))`

**Comment by ahmedGaber93** [comment] 2024-10-09 13:44
I think keeping every function do its job is more clean.

**Comment by ahmedGaber93** [comment] 2024-10-09 13:54
@Krishna2323 [alternative proposal option 2](https://github.com/Expensify/App/issues/49286#issuecomment-2353617400) LGTM! with edit suggestion here https://github.com/Expensify/App/issues/49286#issuecomment-2402332956.

@marcaaron should we do this change also in business website on bank account flow (current like image [here](https://github.com/Expensify/App/issues/49286#issuecomment-2376220885))?

**Comment by marcaaron** [comment] 2024-10-11 18:47
Nice, let's do it! 🙇

**Comment by marcaaron** [comment] 2024-10-16 22:12
Reviewing.

**Comment by ahmedGaber93** [comment] 2024-10-27 06:27
@Krishna2323 bump for the Expensify/App PR

**Comment by davidcardoza** [comment] 2024-10-28 18:19
Waht's the latest here? @caitlinwhite1 reported the same issue today - https://expensify.slack.com/archives/C05LX9D6E07/p1730139071302859

**Comment by ahmedGaber93** [comment] 2024-10-28 18:21
PR in progress

**Comment by kadiealexander** [comment] 2024-11-15 03:01
Payouts due:

- [x] Contributor: $250 @Krishna2323 [automatic offer](https://www.upwork.com/nx/wm/offer/104377928)
- [ ] Reviewer: $250 @ahmedGaber93 [automatic offer](https://www.upwork.com/nx/wm/offer/104377926)

Upwork job is [here](https://www.upwork.com/jobs/~021835835067982464212).

**Comment by kadiealexander** [comment] 2024-11-15 03:01
@ahmedGaber93 please action the [checklist](https://github.com/Expensify/App/issues/49286#issuecomment-2462155820), thanks!

**Comment by ahmedGaber93** [comment] 2024-11-15 12:03
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: New feature

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A. It is a new feature, we didn't support company website without `https` before

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition: you should have at latest one workspace has enabled "Invoices" feature
1. Go to Settings > workspaces > any workspace > More features 
2. Enable Invoices

### Test:


1. Click green (+) button
2. Send invoice
3. Enter $200
4. Choose recipient
5. Fill in company name
6. Fill in company website with a URL without `https://` e.g. `www.dubbyco.com`
7. Verify the entered website is displayed as valid and can be saved

Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment] 2024-11-15 12:06
> @ahmedGaber93 please action the https://github.com/Expensify/App/issues/49286#issuecomment-2462155820, thanks!

@kadiealexander Done!

**Comment by ahmedGaber93** [comment] 2024-11-19 09:12
@kadiealexander [checklist](https://github.com/Expensify/App/issues/49286#issuecomment-2478667364) is completed. Could you please issue the payment and close the issue?

**Comment by ahmedGaber93** [comment] 2024-11-25 11:16
Bump @kadiealexander on [slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1732533327370269) to complete the payment and close this.

**Comment by kadiealexander** [comment] 2024-11-26 06:05
https://github.com/Expensify/Expensify/issues/447811

**Closed** 2024-11-26 06:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
