### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Android - Room - Whisper displays 1 mention when 2 mentions are send in specific way

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46299] opened 2024-07-26 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4768836
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Enter #4856₹&_#7553 and sent the message
4. Note whisper for 2 mentions are shown
5. Enter #gh4h_+&&&-#ehhh & send the message
6. Note whisper for only one mention is shown

## Expected Result:
Whisper must display 2 mention when 2 mentions are send

## Actual Result:
Whisper displays 1 mention when 2 mentions are send in specific way.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/30d757d7-8725-47c1-9b9e-6119fba632f2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01903b4afb9ff494db</li>
        <li>Upwork Job ID: 1827453197366571253</li>
        <li>Last Price Increase: 2024-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104095172</li>
<li>NJ-2020 | Contributor | 104095173</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by lanitochka17** [comment] 2024-07-26 13:32
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-26 13:32
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment] 2024-08-01 23:23
@lanitochka17 does this happen with other combinations of room references? I'm sort of confused because both strings are just one line with no spaces, so I am not sure what is supposed to happen here.

**Comment by kevinksullivan** [comment] 2024-08-09 23:35
Bump @lanitochka17

**Comment by lanitochka17** [comment] 2024-08-12 13:31
@kevinksullivan According steps in TR https://expensify.testrail.io/index.php?/tests/view/4768836 step 5 is fail when create whisper with new room.
Expected resault: Verify an actionable whisper asking the user if they want to create the room is triggered.

**Comment by Mohamed-iyed-ta** [comment] 2024-08-27 06:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Whisper displays 1 mention when 2 mentions are send in specific way.
### What is the root cause of that problem?
the issue is in [this regular expression](https://github.com/Expensify/expensify-common/blob/d11466167bc562447d2dfdad624145040153efae/lib/ExpensiMark.ts#L301). It restricts the characters after the # to lowercase letters (\p{Ll}), digits (0-9), and hyphens (-) (eg: this group`(#[\p{Ll}0-9-]{1,80})`). This causes it to stop matching when it encounters characters like _, + or &.
### What changes do you think we should make in order to solve the problem?
i included those characters (_, +, &) into the old regular expression, so it becomes:
```
(?<![^ \n*~_])(#[\p{Ll}0-9_+\-&]{1,80})(?![^<]*(?:<\/pre>|<\/code>|<\/a>))
```

### What alternative solutions did you explore? (Optional)

Result:
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/225ebeca-391c-4903-830c-4088c7a3da03">

the "#gh4h_+&&&-" is matched.

**Comment by Mohamed-iyed-ta** [comment] 2024-08-27 06:24
Contributor details
Your Expensify account email: morteprhimi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e11da7d5ef514a1c

**Comment by NJ-2020** [comment] 2024-08-27 07:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room - Whisper displays 1 mention when 2 mentions are send in specific way
### What is the root cause of that problem?
When we type `#gh4h_+&&&-#ehhh` we mention 2 user by splitting with minus `-`, but in our expensify-common we do not include the `-` minus we only include the underscore `_`
https://github.com/Expensify/expensify-common/blob/d11466167bc562447d2dfdad624145040153efae/lib/ExpensiMark.ts#L298-L303

So when we add the comment the reportComment params is not correct
![Screenshot 2024-08-27 at 00 20 57](https://github.com/user-attachments/assets/c761d1dd-f3f6-4efa-b588-76c6239e7142)
### What changes do you think we should make in order to solve the problem?
We can add minus `-` to the regex
From:
`/(?<![^ \n*~_])(#[\p{Ll}0-9-]{1,80})(?![^<]*(?:<\/pre>|<\/code>|<\/a>))/gimu`
To:
`/(?<![^ \n*~_-])(#[\p{Ll}0-9-]{1,80})(?![^<]*(?:<\/pre>|<\/code>|<\/a>))/gimu`
### What alternative solutions did you explore? (Optional)

**Comment by Mohamed-iyed-ta** [comment] 2024-08-27 07:47
## Proposal
[Updated](https://github.com/Expensify/App/issues/46299#issuecomment-2311666631)

**Comment by Mohamed-iyed-ta** [comment] 2024-08-27 08:35
Contributor details
Your Expensify account email: [morteprhimi@gmail.com](mailto:morteprhimi@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e11da7d5ef514a1c

**Comment by Mohamed-iyed-ta** [comment] 2024-08-27 09:53
Contributor details
Your Expensify account email: mohamediyedrhimita@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e11da7d5ef514a1c

**Comment by NJ-2020** [comment] 2024-08-27 13:38
@rojiphil Note that @Mohamed-iyed-ta added the alternative solution after my proposal has been send

**Comment by rojiphil** [comment] 2024-08-29 19:07
Well! This seems tricky to handle. If the expectation from message `#gh4h_+&&&-#ehhh` is to identify `#gh4h` and `#ehhh`, then would it not be fair to expect the same output for another message  `#4856₹&#7553`?
So, it seems like while the specific issue here can be resolved by adding `-` to negative lookbehind, maybe we need to find a holistic solution to this problem. 
Tagging @rlinoz to weigh-in here on the expected output due to involvement in the mentions-v2 [here](https://github.com/Expensify/App/issues/39538)

**Comment by rojiphil** [comment] 2024-09-03 12:38
> Well! This seems tricky to handle. If the expectation from message `#gh4h_+&&&-#ehhh` is to identify `#gh4h` and `#ehhh`, then would it not be fair to expect the same output for another message `#4856₹&#7553`?

@kevinksullivan I just noticed that @rlinoz is OOO this week. 
Meanwhile, what do you think of the expected behavior for the above-mentioned comment?

**Comment by kevinksullivan** [comment] 2024-09-11 22:06
> With that said I think the regex might get too complicated and I would be down to only highlight the first room name in a word as well, so in #4856₹&_#7553 we would not highlight #7553

this logic works for me too. Going to loop in another BZ as I'm also going OOO

**Comment by slafortune** [comment] 2024-09-18 16:38
Now that there has been clarification - @rojiphil, is there a proposal that can be accepted/updated?

**Comment by slafortune** [comment] 2024-09-23 15:53
@rojiphil checking on an update?

**Comment by rojiphil** [comment] 2024-09-23 19:40
> With that said I think the regex might get too complicated

In that case, we can keep this simple and use @NJ-2020 [proposal](https://github.com/Expensify/App/issues/46299#issuecomment-2311775536) as that was the first proposal to resolve this issue by adding `-` to negative lookbehind. 
🎀👀🎀 C+ reviewed

**Comment by NJ-2020** [comment] 2024-09-24 09:16
PR ready
cc: @rojiphil

**Comment by Beamanator** [comment] 2024-09-30 21:02
PR still in review 👍

**Comment by mvtglobally** [comment] 2024-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2024-10-10 17:34
probably can close this out if there's 1 more week of not reproducing?

**Comment by NJ-2020** [comment] 2024-10-14 05:50
Issue still reproducible

![Screenshot 2024-10-13 at 22 49 37](https://github.com/user-attachments/assets/4cde0315-5a50-45cc-9cea-f3ac1a1fa42e)

**Comment by rojiphil** [comment] 2024-10-14 14:55
> probably can close this out if there's 1 more week of not reproducing?

@Beamanator @OfstadC I think we can leave this open as the PR is actively worked upon [here](https://github.com/Expensify/expensify-common/pull/804)

**Comment by Beamanator** [comment] 2024-10-17 09:06
Oh wow thanks @rojiphil - removing `Needs Reproduction` 👍

**Comment by rojiphil** [comment] 2024-10-17 18:38
@NJ-2020 Does [this](https://github.com/Expensify/expensify-common/pull/804#issuecomment-2412957497) sound like the next steps?

**Comment by NJ-2020** [comment] 2024-10-18 03:41
@rojiphil Yes

For react-native-live-markdown here's the [PR](https://github.com/Expensify/react-native-live-markdown/pull/521)
For the main repo `App` i will create as soon as possible when the above one get merged

**Comment by NJ-2020** [comment] 2024-10-18 07:12
[PR](https://github.com/Expensify/react-native-live-markdown/pull/521) got merged, waiting for new release

**Comment by NJ-2020** [comment] 2024-10-18 08:38
[PR](https://github.com/Expensify/App/pull/51073) ready for review

cc: @rojiphil

**Comment by OfstadC** [comment] 2024-11-05 22:14
@rojiphil please finish BZ checklist so I can issue payment on 11/11 😄

**Comment by rojiphil** [comment] 2024-11-11 16:08
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    [Link to comment](https://github.com/Expensify/expensify-common/pull/680/files#r1836895999):

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required. The existing checklist is good enough to capture such issues.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:


### Test:
1. Navigate to any chat e.g. a workspace chat.
2. Enter the message `#4856₹&_#7553` in composer and verify that only `#4856` is highlighted.
3. Send the message and verify that the Concierge message mentions only `#4856` for room creation.
4. Repeat Steps (2) and (3) and verify the expected result:
a. Message: `#gh4h_+&&&-#ehhh`, Expected Result: Only `#gh4h`
b. Message: `#4856₹& #7553`, Expected Result: `#4856`  and `#7553`
c. Message: `#4856₹&`
`#7553`, Expected Result: `#4856`  and `#7553`
d. Message: `#4856₹&*#7553`, Expected Result: Only `#4856`
e. Message: `#4856₹&~#7553`, Expected Result: Only `#4856`
f. Message: `#4856₹& *#7553`, Expected Result: `#4856`  and `#7553`
g. Message: `#4856₹& ~#7553`, Expected Result: `#4856`  and `#7553`
h. Message: `#4856₹&`
`*#7553`, Expected Result: `#4856`  and `#7553`
i. Message: `#4856₹&`
`~#7553`, Expected Result: `#4856`  and `#7553`
j. Message: `#4856₹&`
`_#7553`, Expected Result: `#4856`  and `#7553`
k. Message: `#4856₹&`
`-#7553`, Expected Result: Only `#4856`
l. Message: `#room-name123`, Expected Result: `#room-name123`
m. Message: `https://abc.com/abc#qwer`, Expected Result: Nothing is highlighted

Do we agree 👍 or 👎

**Comment by OfstadC** [comment] 2024-11-11 18:33
https://github.com/Expensify/Expensify/issues/443327

**Closed** 2024-11-11 18:41 UTC
Labels: External, Weekly, Awaiting Payment, Bug
