### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] App triggers text to link even while save changes on edit message even when no changes is done

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29225] opened 2023-10-10 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1696945742113089
## Action Performed:
1. Open the app
2. Open any report
3. Send any link
4. Edit link and remove circular bracket with text in it and save (if needed, we can also remove square brackets)
5. Again edit and save without making any changes
6. Observe that even though no changes are done, app converts text to link
## Expected Result: 
App should not perform any changes to edit message if message before save and after save is same
## Actual Result: 
App converts text to link even when there is no change in edit message

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/49763bd1-4b11-42b7-b642-5a7d26b33cd5

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/f3acd5a0-aae8-47e6-bfdd-eabd905d7a80

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/f2970146-0618-4436-b2e8-2fafb6c3755f

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/fa8782c5-ff29-45a7-a6cb-cfb23b173590

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/3d67d9af-0931-4b5f-8b80-ec53e0da8b31

https://github.com/Expensify/App/assets/38435837/69a2c4e9-c022-4772-9cde-c215119f94ba

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/32021b6c-370a-4c21-8d29-08d44386563f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c71d9095a2d85a78</li>
        <li>Upwork Job ID: 1711828833297678336</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Contributor | 27147950</li>
<li>dhanashree-sawant | Reporter | 27147951</li>
</ul></li>
    </ul>
</details>

**Comment by offroader** [comment] 2023-10-11 10:13
@parasharrajat this issue means when you open edit input and save without any changes. Can you confirm that this is expected? 
See demo video (current behavior):
https://github.com/Expensify/App/assets/1447323/193c362a-a774-4fa9-aa6f-5b14195e4115
After my suggested changes:
https://github.com/Expensify/App/assets/1447323/b10845d0-786b-4e17-aa89-413bc6d07a9b
So if you edit comment it will autolink again.

**Comment by eh2077** [comment] 2023-10-11 10:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App triggers text to link even while save changes on edit message even when no changes is done.

### What is the root cause of that problem?

The root cause of this issue is that we call method `Report.editReportComment` to save draft without checking if the draft is changed from the very initial draft, `parser.htmlToMarkdown(lodashGet(props.action, 'message[0].html')).trim()`, or not, see [here](https://github.com/Expensify/App/blob/7c0451831d56745f2c294a72bc9e37afc27bdc33/src/pages/home/report/ReportActionItemMessageEdit.js#L280).

### What changes do you think we should make in order to solve the problem?

To fix this issue, we only save draft when it's different from the initial draft, `parser.htmlToMarkdown(lodashGet(props.action, 'message[0].html')).trim()`. We can change this [line](https://github.com/Expensify/App/blob/7c0451831d56745f2c294a72bc9e37afc27bdc33/src/pages/home/report/ReportActionItemMessageEdit.js#L280) to

```js
        const parser = new ExpensiMark();
        if (trimmedNewDraft !== parser.htmlToMarkdown(lodashGet(props.action, 'message[0].html')).trim()) {
            Report.editReportComment(props.reportID, props.action, trimmedNewDraft);
        }
```

### What alternative solutions did you explore? (Optional)

We can also add condition 

```js
trimmedNewDraft === parser.htmlToMarkdown(lodashGet(props.action, 'message[0].html')).trim()
```

in method `Report.editReportComment` to skip saving the draft, like [here](https://github.com/Expensify/App/blob/7c0451831d56745f2c294a72bc9e37afc27bdc33/src/libs/actions/Report.js#L1211). I prefer the main solution as it avoids unnecessary text processing and is closer to the draft update function.

**Comment by eh2077** [comment] 2023-10-11 10:21
> This is expected behavior as per #13551. It should have to be detected while comparing regression steps #13551.
> 
> cc: @m-natarajan Do we not check issues against existing regression steps before exporting? If, not. This is something that we should propose into the process.

@parasharrajat I also think it's an edge case of the issue you linked. It makes more sense not to change the comment if nothing changed.

**Comment by offroader** [comment] 2023-10-11 12:35
Got it. Thanks for the clarification @parasharrajat

**Comment by eh2077** [comment] 2023-10-11 13:23
> I was checking the QA steps on https://github.com/Expensify/App/pull/13551 and the behaviour matches exactly. Did I miss anything?

@parasharrajat There's no such step to cover case of this issue, saving draft without making changes, in their QA steps. So I think this is a legit bug.

**Comment by eh2077** [comment] 2023-10-12 05:19
@parasharrajat The PR https://github.com/Expensify/App/pull/29418 is ready for review, thanks.

**Comment by zanyrenney** [comment] 2023-10-27 13:02
@parasharrajat does not require payment (Eligible for Manual Requests) owed $500
@eh2077 requires payment [offer](https://www.upwork.com/nx/wm/offer/27147950) (Contributor) - paid $500
@dhanashree-sawant requires payment [offer](https://www.upwork.com/nx/wm/offer/27147951) (Reporter) paid $50

https://github.com/Expensify/App/issues/29225#issuecomment-1769170072 merged in 4 days, no bonus

Paid out, closing!

**Comment by eh2077** [comment] 2023-10-27 13:16
@zanyrenney Thanks for checking the payment! 

I think bonus is applicable because @parasharrajat had reviewed and approved PR with 3 days and the internal engineer late merged the PR without additional review comments in the PR https://github.com/Expensify/App/pull/29418#pullrequestreview-1674103175.

**Comment by JmillsExpensify** [comment] 2024-04-08 03:06
$500 approved for @parasharrajat

**Comment by JmillsExpensify** [comment] 2024-04-08 03:06
Also, I don't believe we have an regression test for this issue so re-opening.

**Comment by zanyrenney** [comment] 2024-04-11 10:12
Regression test created.

**Closed by zanyrenney** 2024-04-11 10:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
