### ISSUE TITLE
[HOLD for payment 2023-07-14] Web-  A Green 'Yes, Continues' button is shown when closing an account.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22257] opened 2023-07-05 11:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on Security and then choose Close Account
3. Write your default contact method and click on Close Account.
4. Notice that "Closing your account cannot be undone" message pops up with a Green 'Yes, Continues' button.

## Expected Result:
A Red 'Yes, Continues' button is shown

## Actual Result:
A Green 'Yes, Continues' button is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a2ec0d78-b01d-4f93-bb81-3de74d2cc4d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688188374632229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-07-05 11:30
Ah nice, thanks for the context @parasharrajat! How long do you think it will take for the PR to be merged? This will help inform if I assign an engineer here!

**Comment by s-alves10** [comment] 2023-07-05 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Green "Yes,Continue" button instead of red button when closing an account

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/4f9f42842bc35cc8314d5888bd9c2cca864135a2/src/pages/settings/Security/CloseAccountPage.js#L111-L120

There is no danger props here. This is the root cause

### What changes do you think we should make in order to solve the problem?

Add danger props to the `ConfirmModal` component

This works as expected.


### What alternative solutions did you explore? (Optional)

**Comment by dylanexpensify** [comment] 2023-07-05 12:54
this is intentional!

**Comment by bondydaa** [comment] 2023-07-05 13:40
not sure this should have been closed, I merged the PR. sorry for missing this while doing the refactor.

**Comment by dylanexpensify** [comment] 2023-07-05 15:03
Oh wow, sorry, yes agree - this shouldn't have been - my fault!

**Comment by dylanexpensify** [comment] 2023-07-17 09:18
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-07-20 08:37
@parasharrajat any payments needed here?

**Comment by dylanexpensify** [comment] 2023-07-24 08:31
@daveSeife mind applying [here](https://www.upwork.com/jobs/~0124aa28048e3ebc98)?

@parasharrajat we're discussing rewards for preventing duplicates, but currently nothing in stone! TY though! LMK if you think this should require payment though

**Comment by avalonprod** [comment] 2023-07-24 08:48
Hi, I understand your problem and I know how to solve this problem.
1) Create a unique class with prefix RED or Delete
2) Write styles for this class background-color: #fb642a
3) Test
4) Send for testing and comment on corrections.
5) Executed and delivered.

Thanks. Roman

**Comment by avalonprod** [comment] 2023-07-24 08:58
Contributor details
Your Expensify account email: abramenkoroman22@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/roman2022

**Comment by daveSeife** [comment] 2023-07-24 11:24
@dylanexpensify I have applied. Thank You!

**Comment by dylanexpensify** [comment] 2023-07-25 14:50
Sounds good!

**Comment by dylanexpensify** [comment] 2023-07-25 14:51
@daveSeife sent offer, @parasharrajat mind applying?

**Comment by dylanexpensify** [comment] 2023-07-25 17:41
payment sorted, closing out

**Closed by dylanexpensify** 2023-07-25 17:41 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 23:25
Reviewed details for @parasharrajat. This is accurate based on the agreement from @dylanexpensify above, as the Business Reviewer. This is approved for payment in NewDot.
