### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Mentions results are displayed with half height on click of add attachment 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#18992] opened 2023-05-16 03:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write @ to open mention results
4. Click on plus and click 'add attachment' and observe that mention results close and reopen to display in half the height for few seconds untill attachment selection window is not open

## Expected Result:
App should not display mention results on add attachment as it does not for emoji suggestions

## Actual Result:
App displays mention results in half the height on add attachment click

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**1.3.13-4 
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/9513b1f6-9f93-4b5d-85dd-367e6a10f621

![image - 2023-05-15T232239 703](https://github.com/Expensify/App/assets/43995119/f2d5b3bb-6428-4211-a1ac-d6e32ffd346c)

https://github.com/Expensify/App/assets/43995119/9c7ada33-128a-450e-a7ac-805c1d397606

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684069576237329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016704c5d525d79faa</li>
        <li>Upwork Job ID: 1658817764217602048</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-16 03:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mention suggestions list flickers when the file picker is being opened for adding attachments.

### What is the root cause of that problem?

The reason for this is we are not taking care of this case explicitly like we do for the emoji suggestions list. In the code shown below (Line 982), we explicitly block the emoji suggestions list from being opened if the file picker is opened.

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/home/report/ReportActionCompose.js#L978-L988

### What changes do you think we should make in order to solve the problem?


Similarly (the method above) this has to be done for the mention suggestions list using a `shouldBlockMentionCalc` state variable.

### What alternative solutions did you explore? (Optional)
None.

**Comment by dukenv0307** [comment] 2023-05-16 10:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention results flickers while opened the add attachments.
### What is the root cause of that problem?
We are focusing on the composer again when the attachment menu item is selected. 

### What changes do you think we should make in order to solve the problem?
Do same thing like this [PR for emoji suggestion](https://github.com/Expensify/App/pull/18227) 

### What alternative solutions did you explore? (Optional)

**Comment by pecanoro** [comment] 2023-05-19 08:50
@0xmiroslav Could you review the proposals when you have some time? Thank you!

**Comment by s-alves10** [comment] 2023-05-20 09:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention suggestions are displayed with half height when click add attachement.

### What is the root cause of that problem?

This issue is because the composer is refocused after the add attachment menu is clicked.

### What changes do you think we should make in order to solve the problem?

We have 2 suggestions now: emoji and mention.
When we click the `+` button, suggestions are reset. After add-attachment is clicked, we prevent calculation of emoji suggestions here: line 466~469

https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/pages/home/report/ReportActionCompose.js#L461-L469

We can move this code to here to prevent calculation of both emoji and mention suggestions.

https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/pages/home/report/ReportActionCompose.js#L280-L285

Of course, we may need to rename state variable `shouldBlockEmojiCalc` and `setShouldBlockEmojiCalcToFalse` method properly.

The final code would look like

```
    onSelectionChange(e) {
        LayoutAnimation.configureNext(LayoutAnimation.create(50, LayoutAnimation.Types.easeInEaseOut, LayoutAnimation.Properties.opacity));
        this.setState({selection: e.nativeEvent.selection});

        if (this.state.shouldBlockSuggestionsCalc) {
            this.setState({shouldBlockSuggestionsCalc: false});
            return;
        }
        this.calculateEmojiSuggestion();
        this.calculateMentionSuggestion();
    }
```

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/d119fde8-d528-4350-a824-6ab08e79afac



</details>

### What alternative solutions did you explore? (Optional)

**Comment by pecanoro** [comment] 2023-05-22 08:08
@0xmiroslav Friendly bump on my message [here](https://github.com/Expensify/App/issues/18992#issuecomment-1554250718).

**Comment by s-alves10** [comment] 2023-05-23 14:17
@0xmiroslav 
Thank you for your feedback.
I suggested to use one state variable to manage suggestions calculation.
This is more efficient than introducing one more variable as you mentioned.

**Comment by therealsujitk** [comment] 2023-06-03 00:47
Not overdue, PR already merged.

**Comment by therealsujitk** [comment] 2023-06-12 13:26
@anmurali this issue is ready for payment. I was wondering if a bonus can be considered for this issue even though the PR was merged late since it was technically C+ reviewed by @0xmiroslav on day 2? Thanks.

**Comment by pecanoro** [comment] 2023-06-12 14:17
@therealsujitk Can you elaborate a bit more why do you think the bonus should apply? Even though May 29th was a federal holiday in the US that we don't take into account, @0xmiroslav didn't approve until May 31th and the PR was created on May 24th. There were a couple of discussions about if there were bugs with the solution or not in between.

**Comment by therealsujitk** [comment] 2023-06-12 17:59
@pecanoro can you confirm if a bonus is applicable? PR was merged in 6 business days (including the 3 day hold).

**Comment by pecanoro** [comment] 2023-06-14 20:28
Ok, we can make an exception since the hold was on me while I went ooo for a couple of days. @anmurali can you handle payment (with a bonus), please?

**Comment by anmurali** [comment] 2023-06-21 01:03
Sent offers

**Comment by dhanashree-sawant** [comment] 2023-06-21 03:47
Hi @anmurali, I haven't recieved offer for reporting bonus, can you check once you are available?

**Comment by pecanoro** [comment] 2023-06-23 20:54
@anmurali Can you double check everything has been sent?

**Comment by anmurali** [comment] 2023-06-26 17:36
@dhanashree-sawant - sent you an offer as well.

**Comment by anmurali** [comment] 2023-06-26 19:18
Done, everyone is paid.

**Closed by anmurali** 2023-06-26 19:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
