### ISSUE TITLE
[HOLD for payment 2024-01-05] [HOLD for payment 2024-01-04] Android - Chat - User suggestions list is not displayed when entering @ in compose

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33675] opened 2023-12-27 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Open a group chat
3. Enter @

## Expected Result:
When user enters @, user suggestion list must be displayed.

## Actual Result:
When user enters @, user suggestion list is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b7ba365c-ea2f-49e2-bfa8-5955cf6a945b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-12-27 21:36
Issue is not reproducible in production

https://github.com/Expensify/App/assets/93399543/9854093b-3223-4bfe-ab3c-bb71f2531005

**Comment by neil-marcellini** [comment] 2023-12-27 21:46
I'll check if I can reproduce on Android staging, and then look into the root cause.

**Comment by situchan** [comment] 2023-12-27 21:51
Confirmed that https://github.com/Expensify/App/pull/32297 caused regression

**Comment by neil-marcellini** [comment] 2023-12-27 21:53
Ok great thanks, I'll put up a revert PR.

**Comment by neil-marcellini** [comment] 2023-12-27 21:56
@situchan would you please post a video proving that it's fixed on native android?

**Comment by neil-marcellini** [comment] 2023-12-27 22:14
PR is merged and I have a [CP request here](https://expensify.slack.com/archives/C07J32337/p1703715167283549), so all done for now.

**Comment by neil-marcellini** [comment] 2023-12-28 19:03
The PR was CPed so it's fixed and I think I can close this

**Comment by situchan** [comment] 2024-01-04 05:59
C+ review payment is pending here

**Comment by situchan** [comment] 2024-01-29 18:27
@neil-marcellini can you please check ^?

**Comment by AndrewGable** [comment] 2024-03-22 21:26
@trjExpensify - Can you pay this one out? Thanks

**Comment by trjExpensify** [comment] 2024-03-25 12:21
Can confirm payment summary as follows: 

- $500 to @situchan for the C+ review. 

@situchan I've sent you [an offer](https://www.upwork.com/nx/wm/offer/101563908) on Upwork.

**Comment by trjExpensify** [comment] 2024-03-25 12:21
Reopening until this is confirmed paid.

**Comment by trjExpensify** [comment] 2024-03-25 15:17
Paid, @situchan!

**Closed by trjExpensify** 2024-03-25 15:17 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
