### ISSUE TITLE
[$1000] Chat - Scrolling is not smooth

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13114] opened 2022-11-29 01:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app and login as HT account
2. Navigate to a 1:1 chat that has a lot of messages in the conversation history
3. Scroll to the top of the conversation

## Expected Result:
Scrolling should be smooth

## Actual Result:
Scrolling is not smooth and the chat sometimes disappears.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204414566-6f1cd8e8-6d29-449f-9887-d756daa3cc45.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01153060f301af2ca9
- Upwork Job ID: 1597653380629020672

**Comment by CortneyOfstad** [comment] 2022-11-29 13:21
Was able to recreate this on my side, but not sure if I should use **External** or **Internal** labels. Going to ask _Engineering_ per the SO [here](https://stackoverflow.com/c/expensify/questions/14418).

**Comment by deetergp** [comment] 2022-11-29 18:06
This definitely seems like it could be external.

**Comment by JalalMitali** [comment] 2022-11-29 21:24
as far as I know this is simply happening because the chat message ( in the case of HT accounts ) is very long, longer than any usual  chat message so my _proposal_ would be to check the length of the message if it's too long let's just load parts of it I believe that's doable!

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 15:42
This is a dupe of this https://github.com/Expensify/App/issues/8661

**Closed** 2022-11-30 18:36 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
