### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Tag - Tag selected from another workspace is still preserved when switching workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33067] opened 2023-12-14 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace A has a set of tags A.
- Workspace B has a set of tags B.

1. Click FAB > Request money > Distance.
2. Enter start and finish point.
3. Select Workspace A.
4. Click Tag and select another tag.
5. Click on the back button.
6. Select Workspace B.

## Expected Result:
The tag field in the confirmation page will reset when switching workspace.

## Actual Result:
The tag selected from Workspace A is still preserved when Workspace B is selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/435fd468-81bc-4b7b-8e18-d53b2715243a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194acf0b0a5cd5e3a</li>
        <li>Upwork Job ID: 1735307898523672576</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28061731</li>
<li>FitseTLT | Contributor | 28061732</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-14 14:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag selected from another workspace is still preserved when switching workspace

### What is the root cause of that problem?
We are not resetting the tag on workspace change 
### What changes do you think we should make in order to solve the problem?

We should reset `iou.tag` and `iou.category` when user changes workspace.
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-12-14 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tag selected from Workspace A is still preserved when Workspace B is selected.

### What is the root cause of that problem?
when re-select the participant we don't re-set tag and category
### What changes do you think we should make in order to solve the problem?
We need to reset` transactionsDraft_1 .tag` and `transactionsDraft_1.category` when user re-select participant 

### What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment] 2023-12-14 15:07
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/33067#issuecomment-1855974499) LGTM! With the caveat that we probably don't want to reset tags and category if the user doesn't select a different workspace (i.e. just going back and forth between without changing the workspace).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by DylanDylann** [comment] 2023-12-14 15:10
@jjcoffee 
> We should reset iou.tag and iou.category

It seems we don't use `iou` field any more

**Comment by DylanDylann** [comment] 2023-12-14 15:11
@FitseTLT's original proposal is invalid

**Comment by jjcoffee** [comment] 2023-12-14 15:17
@DylanDylann Looking at the edit history, @FitseTLT's proposal contained the relevant code snippets before yours did so I'm not inclined to agree that there's been any funny business on @FitseTLT's part!

![image](https://github.com/Expensify/App/assets/27287420/e433a897-c501-4d0b-883c-3801401de79e)

**Comment by FitseTLT** [comment] 2023-12-14 15:18
> We need to reset transactionsDraft_1.tag and transactionsDraft_1.category when user re-select participant by calling

@DylanDylann this is not even the correct proposal because we shouldn't reset when the participant is not different from the previously selected one that's what @jjcoffee is mentioning in his review and also about my proposal I just commented a draft propsal first with the basic idea and cleaned it doesn't mean I copied from U.

**Comment by DylanDylann** [comment] 2023-12-14 15:19
@jjcoffee My proposal is the first one that suggests using 
```
           IOU.resetMoneyRequestCategory_temporaryForRefactor(transactionID);
            IOU.resetMoneyRequestTag_temporaryForRefactor(transactionID);
```

@FitseTLT's original proposal, he suggests resetting iou.tag and iou.category. It is wrong

**Comment by DylanDylann** [comment] 2023-12-14 15:28
@FitseTLT I think we should prioritize making a correct proposal and testing well first. My proposal has been posted after your proposal 2 minutes but It is correct and I tested it well. I don't think we encourage creating a sketchy, inaccurate proposal quickly and then editing that proposal. It will cause confusion for reviewer

**Comment by FitseTLT** [comment] 2023-12-14 15:32
@DylanDylann U did the same thing You first commented `transactionsDraft_1 .tag` and then updated it to ` IOU.resetMoneyRequestTag_temporaryForRefactor(` so you are doing the same thing but additionally the point of the review is we should reset only when we change different workspace.
>With the caveat that we probably don't want to reset tags and category if the user doesn't select a different workspace

**Comment by DylanDylann** [comment] 2023-12-14 15:33
I edited my proposal to make it clearer but my original proposal is correct. Reset `transactionsDraft_1 .tag` is that `IOU.resetMoneyRequestTag_temporaryForRefactor` function will do

**Comment by FitseTLT** [comment] 2023-12-14 15:39
Both alternative solutions I gave U didn't. I still think I proposed the best solution let the other's (reviewers) do their job 👍

**Comment by jjcoffee** [comment] 2023-12-14 15:47
@DylanDylann Ah I'd actually missed that `resetMoneyRequestCategory_temporaryForRefactor` resets the **draft** value in Onyx. In that case I agree that your proposal is the first to include the correct function call, however it's still lacking in detail, i.e. where should this change should be applied, so I think @FitseTLT's proposal still works for me. cc @blimpich

**Comment by FitseTLT** [comment] 2023-12-14 18:14
@jjcoffee Just to bring some attention to my alternative solution because before the recent refactor of the request flow we used to reset tag and category whenever we navigate to confirmation page. To give u some background we introduced the resetting on this [pr](https://github.com/Expensify/App/pull/27936) (but resetting on mount of the confirmation page) and then we  changed the resetting to happen when we navigate to the confirmation page to deal with this [issue](https://github.com/Expensify/App/issues/30682#issuecomment-1788928520) 👍 So if we don't have a specific reason to change this previous behaviour we might need to stick to it.
cc @blimpich

**Comment by blimpich** [comment] 2023-12-14 20:42
@FitseTLT @DylanDylann thank you both for your time and effort spent on this issue. I understand it can be frustrating to not have a proposal chosen, but please remain courteous throughout the proposal and review process. We try our best to be as fair as possible and I'm sure @jjcoffee tried their best to do that in this situation. Practicing inclusivity in our communication is also part of the [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md), and is a requirement for contributing. _Please_ keep that in mind when commenting.

That being said, because of the similarity in timing and proposals I'm going to go with @FitseTLT's proposal. I agree with @jjcoffee that detail is the deciding factor. @DylanDylann if you would like I can spend time trying to find another issue for you to work on.

**Comment by jjcoffee** [comment] 2023-12-15 10:37
@FitseTLT  I'm not sure I fully understand what you're proposing, but if you're talking about **always** resetting when navigating to the confirmation page vs. only when the participant is changed, I don't feel too strongly about the latter. 

Once you navigate back to the participants page, the selection is reset anyway so it wouldn't be too jarring if tapping the same workspace would reset the tag (it's not quite the "back and forth" style UX I [alluded](https://github.com/Expensify/App/issues/33067#issuecomment-1856022191) to!). So, I'm fine to go with that if it works better for you!

**Comment by jjcoffee** [comment] 2023-12-18 11:56
@FitseTLT Don't forget to let us know when we can expect a PR.

**Comment by FitseTLT** [comment] 2023-12-18 12:47
PR ready

**Comment by alexpensify** [comment] 2023-12-18 23:46
Awesome, great to see we are making progress here!

**Comment by alexpensify** [comment] 2023-12-20 23:56
It looks like we need to wait for automation here.

**Comment by alexpensify** [comment] 2023-12-23 03:21
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue @FitseTLT $500
-  Contributor+ that helped on the issue and/or PR @jjcoffee $500 

Upwork Job: https://www.upwork.com/jobs/~0194acf0b0a5cd5e3a

Extra Notes regarding payment: Heads up, I'm OOO until January 4, but I will log in on Friday, December 29 to complete this payment process pending no regression. I've confirmed that @jjcoffee and @FitseTLT are a pending hire, so all set here for the payment date. 

@jjcoffee please complete the checklist when you can, thanks!

**Comment by alexpensify** [comment] 2023-12-29 18:31
Closing - Thank you everyone for your patience here. I've completed the payment process in Upwork and closed this job. 

Happy New Year!

@jjcoffee - please complete the checklist when you get a chance, thanks!

**Closed by alexpensify** 2023-12-29 18:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
