### ISSUE TITLE
[HOLD for payment 2023-10-05] [HOLD for payment 2023-10-02] [$500] Android - App crashes when opening Settings > Wallet

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28057] opened 2023-09-23 07:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Android App
2. Login with any account
3. Go to Settings > Wallet

## Expected Result:
Settings > Wallet opens correctly

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 11.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c979964a-b205-47f0-ac37-938ff1fe6f70

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima /Applause-Internal Team

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695364840745219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139cc3c5c00612428</li>
        <li>Upwork Job ID: 1705775981192208384</li>
        <li>Last Price Increase: 2023-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26842492</li>
<li>pradeepmdk | Contributor | 26842494</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-23 07:48
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

App crashes when opening Settings > Wallet
### What is the root cause of that problem?

![Screenshot 2023-09-23 at 1 15 12 PM](https://github.com/Expensify/App/assets/16595846/fd13a40c-da6f-4f70-beaa-7c3d7a5edbf8)
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/settings/Wallet/WalletPage/BaseWalletPage.js#L351
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/settings/Wallet/WalletPage/BaseWalletPage.js#L453
https://reactnative.dev/docs/view#testid
`displayName`  should be string

### What changes do you think we should make in order to solve the problem?

change to 
`BaseWalletPage.displayName = 'BaseWalletPage';`

**Comment by MitchExpensify** [comment] 2023-09-24 02:47
Reproduced

**Comment by situchan** [comment] 2023-09-24 03:42
@pradeepmdk's [proposal](https://github.com/Expensify/App/issues/28057#issuecomment-1732245485) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by amyevans** [comment] 2023-09-24 14:02
@pradeepmdk this is a deploy blocker so ideally we can get the PR merged within the next ~12 hours. Let me know if that doesn't work for you and we can take it over internally. Thanks!

**Comment by pradeepmdk** [comment] 2023-09-24 14:03
@amyevans sure I will raise the pr in few hours

**Comment by amyevans** [comment] 2023-09-24 14:10
Great, thank you!

**Comment by amyevans** [comment] 2023-09-25 04:54
Retested on staging and looks good ✅

Removing the blocker label and dropping this to Weekly to process payments

**Comment by MitchExpensify** [comment] 2023-09-26 04:37
Added a reminder to pay on the 2nd, please take a look at the BZ steps above when you get a chance @situchan

**Comment by situchan** [comment] 2023-09-26 05:22
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22412
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22412/files#r1336638246
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by Applause team so no need further regression test.

**Comment by MitchExpensify** [comment] 2023-09-29 23:10
**Payment Summary:**

C: $750 @pradeepmdk  ([Upwork](https://www.upwork.com/jobs/~0139cc3c5c00612428))
C+: $750 @situchan ([Upwork](https://www.upwork.com/jobs/~0139cc3c5c00612428))

**Comment by Natnael-Guchima** [comment] 2023-09-30 05:33
@MitchExpensify I haven't been paid for reporting bonus yet.

**Comment by MitchExpensify** [comment] 2023-10-02 19:46
Updated @Natnael-Guchima, thanks!

**Comment by MitchExpensify** [comment] 2023-10-02 19:48
Mind applying to the job here as a next step @Natnael-Guchima https://www.upwork.com/jobs/~0139cc3c5c00612428

Thanks

**Comment by MitchExpensify** [comment] 2023-10-02 19:51
Paid @pradeepmdk & @situchan 👍 

Waiting on @Natnael-Guchima and will close once paid

**Comment by Natnael-Guchima** [comment] 2023-10-03 03:58
@MitchExpensify I have applied to the job. Thanks!

**Comment by MitchExpensify** [comment] 2023-10-03 22:41
Offer sent! Thanks

**Comment by Natnael-Guchima** [comment] 2023-10-04 04:38
Accepted the offer. Thanks!

**Comment by MitchExpensify** [comment] 2023-10-05 20:48
Paid, closing!

**Closed by MitchExpensify** 2023-10-05 20:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
