### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] Tax - Not here page opens when clicking currency in tax amount in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40123] opened 2024-04-11 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39562
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has tax enabled
3. Create a manual request with tax
4. Go to transaction thread
5. Click Tax amount
6. Click on the currency

## Expected Result:
If the currency for tax amount is not supposed to be accessible in transaction thread, the currency should not be clickable (production behavior)

## Actual Result:
The currency in tax amount in transaction thread is clickable, and it leads to not here page instead of currency list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a02e0a8-a3fa-4085-8a50-6d7de8f860b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015297f4039458a835</li>
        <li>Upwork Job ID: 1778496247330332672</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-11 15:25
@NikkiWines  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-11 15:26
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-04-11 15:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency in tax amount in transaction thread is clickable, and it leads to not here page instead of currency list

### What is the root cause of that problem?
We use the `IOURequestTaxAmountPage` for edit flow now but we always pass the action as `create` here

https://github.croom/Expensify/App/blob/8f90c2567f020ed924a96593244727aace9a7d72/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L109
### What changes do you think we should make in order to solve the problem?

We should use `action` in `route` prop here instead of always passing `create`

```
 Navigation.navigate(
    ROUTES.MONEY_REQUEST_STEP_CURRENCY.getRoute(action, iouType, transactionID, reportID, backTo ? 'confirm' : '', Navigation.getActiveRouteWithoutParams()),
);
```

https://github.croom/Expensify/App/blob/8f90c2567f020ed924a96593244727aace9a7d72/src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx#L109

### What alternative solutions did you explore? (Optional)
NA

**Comment by NikkiWines** [comment] 2024-04-11 19:23
Thanks for investigating @nkdengineer. Since we don't want the currency to be editable for the tax field, let's go with your alternate solution.

**Comment by nkdengineer** [comment] 2024-04-12 05:45
@mollfpr The PR is ready.

**Comment by thienlnam** [comment] 2024-04-16 19:12
Should be fixed

**Comment by puneetlath** [comment] 2024-04-17 21:34
So is there anything we need to do here or can we just close?

**Comment by thienlnam** [comment] 2024-04-17 21:39
We'll need to do a payment to @nkdengineer / @mollfpr for the [fix](https://github.com/Expensify/App/pull/40159)

**Comment by puneetlath** [comment] 2024-04-23 13:50
@mollfpr reminder about the checklist so we can pay in 2 days.

**Comment by puneetlath** [comment] 2024-04-25 18:04
@nkdengineer sent you an offer: https://www.upwork.com/nx/wm/offer/102031741. Please ping me on this issue when you've accepted. 

@mollfpr waiting on checklist for you.

**Comment by puneetlath** [comment] 2024-04-26 21:24
Ok @nkdengineer has been paid. 

@mollfpr still waiting on the checklist for you.

**Comment by mollfpr** [comment] 2024-04-29 19:12
Sorry for the delay 🙏

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

>[@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to the workspace chat that has tax-enabled
2. Create a manual request with tax
3. Go to the transaction thread
4. Click Tax amount
5. Click on the currency
6. Verify that: the currency should not be clickable
7. 👍 or 👎

**Comment by puneetlath** [comment] 2024-04-29 20:30
Regression test issue here: https://github.com/Expensify/Expensify/issues/391684

Payment Summary: 

@mollfpr requires payment through NewDot Manual Requests - C+ - $250
@nkdengineer paid through upwork - C - $250 

@mollfpr please request on NewDot.

**Closed by puneetlath** 2024-04-29 20:30 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-30 23:17
$250 approved for @mollfpr
