### ISSUE TITLE
[$1000] Chat - New message does not show up in offline chat view after receiving it online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21000] opened 2023-06-19 00:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
as User A.
2. Disable internet connection.
3. As User B on web, send a message to User A.
4. As User A on mweb, reconnect network.
5. After the new message appears (bold) in LHN on mweb, disconnect network.
6. Tap on the chat with new message.

## Expected Result:
The new message shows up in chat view

## Actual Result:
The new message does not show up in chat view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9bf8f2d7-82f8-41f3-8f2d-061d9e677921

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d943e8e6aa6f356</li>
        <li>Upwork Job ID: 1671397287786196992</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-19 06:50
Reassigning as I'm heading OOO!

**Comment by s-alves10** [comment] 2023-06-21 15:32
This happens on small screen devices.

`ReconnectApp` API returns report data including lastMessageText, so the text in LHN is updated. But the API doesn't return report actions data and so report actions are not updated unless we call `OpenReport` API in online mode.

This is the root cause and I'm not sure if this is a bug. Anyway, I think it should be fixed in the backend

**Comment by abdulrahuman5196** [comment] 2023-06-21 21:58
The analysis by @s-alves10 here is correct - https://github.com/Expensify/App/issues/21000#issuecomment-1601064095

But I don't think we can say backend should fix it. @greg-schroeder  What would be the expected behaviour here?  Showing loading view or some intimation?

we would not be able to preload all the messages before user going to chat page since there could be 100s of unread messages hypothetically.

**Comment by s-alves10** [comment] 2023-06-21 22:00
@abdulrahuman5196 
Of course, we can call OpenReport api manually for updated reports in the frontend

**Comment by greg-schroeder** [comment] 2023-06-22 01:28
@abdulrahuman5196 that's a good point. I don't actually know if this a bug... I'm trying to think of what is the best approach. I mean, as a user, I'm not sure I would necessarily even expect the chat to show the new message given that I'm offline and the app shows me that explicitly.

**Comment by greg-schroeder** [comment] 2023-06-22 01:33
Started a conversation here: https://expensify.slack.com/archives/C01GTK53T8Q/p1687397601399389

**Comment by greg-schroeder** [comment] 2023-06-23 01:42
From @puneetlath in the thread linked above:

>it kinda sounds like it might be a back-end bug. They should in theory have gotten a pusher update with that message if they are seeing it in their LHN
>
>when you open a given report. we load the last 50 responses. But also while you are online, pusher will update you with new messages as you receive them. So in theory, the fact that they had that message in their LHN means they got a pusher update, which means they should also have the message locally already

**Comment by greg-schroeder** [comment] 2023-06-26 18:07
Per team discussion we're going to close this!

**Closed by greg-schroeder** 2023-06-26 18:07 UTC
Labels: External, Daily, Help Wanted, Bug
