### ISSUE TITLE
[$1000] Web - Tooltip position keeps on shifting for long user names on request money details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23784] opened 2023-07-28 10:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on request money
3. Enter any amount and continue
4. Select user with long user name
5. On details page, hover on username, observe current tooltip position
6. Change amount of change description text and again hover on username, observe that for same user, tooltip position is now changed

## Expected Result:
App should display tooltip constantly at center of username on request money details page as it does on search page

## Actual Result:
Tooltip position changes when we change amount or description and is not at center of username on request money details page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/207a86e7-41d6-4053-b887-00ff2fe69b9d

https://github.com/Expensify/App/assets/93399543/7f95a6f4-ba4a-468a-a0d8-436eb86e6983

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690428525912479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133c32537626b0505</li>
        <li>Upwork Job ID: 1685946951677566976</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25876640</li>
<li>bernhardoj | Contributor | 25876641</li>
<li>dhanashree-sawant | Reporter | 25876644</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-07-28 12:51
The issue is caused by `getTooltipShiftX` not working as expected 
https://github.com/Expensify/App/blob/ddc19e004211ce4282c2c28b08dafadd84a62cc5/src/components/DisplayNames/index.js#L49

Here you can see the inconsistent outputs it is generating
<img width="1440" alt="Screenshot 2023-07-28 at 5 49 30 PM" src="https://github.com/Expensify/App/assets/59907218/ff16ee4f-d516-4d69-bc20-8459f2608b6f">

**Comment by laurenreidexpensify** [comment] 2023-07-31 09:34
not overdue, added to upwork

**Comment by s77rt** [comment] 2023-07-31 22:57
@spcheema Thanks for the proposal. Your RCA does not seem accurate enough, I don't see how the display name container is related to changing the amount. Also `onLayout` returns different values but it has nothing to do with the element being visible or not, the callback just seems to fire during animation.

**Comment by s77rt** [comment] 2023-08-01 08:47
@bernhardoj Thanks for the proposal. Your RCA is correct, this is solely dependent on the `onLayout` being called too early. Using `getBoundingClientRect` to get the correct value just before rendering the tooltip (instead of using the _stale_ value that was calculated on mount) looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/23784#issuecomment-1656713393)

**Comment by laurenreidexpensify** [comment] 2023-08-18 12:59
https://github.com/Expensify/App/pull/23990 - this was deployed to prod on 9 august - I am working on payment now

**Comment by laurenreidexpensify** [comment] 2023-08-18 13:18
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@s77rt] The PR that introduced the bug has been identified. Link to the PR:
 [@s77rt] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@s77rt] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@s77rt]  Determine if we should create a regression test for this bug.
 [@s77rt] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md?rgh-link-date=2023-07-27T21%3A27%3A31Z) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 [@laurenreidexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by laurenreidexpensify** [comment] 2023-08-18 13:25
Payment Summary: 

- [ ] External issue reporter - @dhanashree-sawant, paid in Upwork $250 
- [ ]  Contributor that fixed the issue - @bernhardoj, paid in Upwork $1000 + 3 day bonus $500 = $1500
- [ ]  Contributor+ that helped on the issue and/or PR - @s77rt,  paid in Upwork $1000 + 3 day bonus $500 = $1500

**Comment by laurenreidexpensify** [comment] 2023-08-18 13:25
@s77rt please complete the regression checklist above and then we can close this out. Thanks

**Comment by s77rt** [comment] 2023-08-18 13:38
- The PR that introduced the bug has been identified: This existed since day one https://github.com/Expensify/App/pull/1632
- The offending PR has been commented on: I can't comment as the PR is locked
- A discussion in #expensify-bugs has been started: Not needed. Not much to discuss
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment] 2023-08-18 13:38
@laurenreidexpensify ^

**Closed** 2023-08-21 09:16 UTC
Labels: Reviewing, External, Daily, Bug
