### ISSUE TITLE
Create regression test for #49260

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#50727] opened 2024-10-14 14:42 UTC
Coming from: https://github.com/Expensify/App/issues/49260

**Prerequisites:**
- Create a WS and add two employees to it.

1. Open NewExpensify app.
2. Log in with a WS admin account.
3. Go to the account settings.
4. Go to the Troubleshoot menu.
5. Click on `Clear cache and restart` to clear the cache.
6. Go back to the LHN Inbox.
7. Verify that members' room names should be updated and display the room name in LHN after the cache is deleted, instead of showing default `Chat Report` name.

**Comment by isagoico** [comment] 2024-10-15 20:28
@m-natarajan Looks like a good candidate for Edge case

**Comment by isagoico** [comment] 2024-11-01 15:23
Going to close this one as low value since the troubleshooting tools don't have the priority to be included in the regression suite. Please reopen if you disagree.

**Closed by isagoico** 2024-11-01 15:23 UTC
Labels: Weekly, Task
