### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Workspace -Workspace avatar turn to default when invited admin try to delete the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46344] opened 2024-07-27 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a750@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. User A creates workspace with custom Avatar and invite User B as member
2. User A promotes User B as admin
3. As User B delete the workspace

## Expected Result:
Workspace should remain custom avatar when admin tries to delete

## Actual Result:
Workspace avatar turn to default when invited admin tries to delete the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ff5a60be-e776-4bef-ae75-0ec293598956

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121268c92b5fca0cf</li>
        <li>Upwork Job ID: 1818882687051192738</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment] 2024-07-27 01:36
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-27 01:36
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-07-27 03:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS avatar turns to default when the admin try to delete the workspace but failed.

### What is the root cause of that problem?
There are 2 issues here. When we delete the WS, we optimistically clear the avatar.
https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/libs/actions/Policy/Policy.ts#L247-L252

But we never revert the avatar (or other data) when it fails.

Second, the delete action can only be performed by the owner, but we show the delete button for all admins.
https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/pages/workspace/WorkspaceProfilePage.tsx#L86
https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/pages/workspace/WorkspaceProfilePage.tsx#L264-L280

### What changes do you think we should make in order to solve the problem?

1. Add failureData to revert back the workspace avatar
2. Show the delete button or owner only.
```
const isOwner = PolicyUtils.isPolicyOwner(policy, session.accountID);
{isOwner && // delete button}
```

**Comment by jayeshmangwani** [comment] 2024-08-01 11:09
Thanks for the above proposals. 

@bernhardoj 's [Suggestion](https://github.com/Expensify/App/issues/46344#issuecomment-2253727076) of adding failureData to deleteWorkspace looks good to me. I also agree that we should change the button visibility to only be available to the owners of the policy.


🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-08-02 05:23
PR is ready

cc: @jayeshmangwani

**Comment by jayeshmangwani** [comment] 2024-08-13 20:34
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: **I don't think any specific PR directly caused this bug. We didn't consider the need to restore the avatar in case of a failure when implementing the workspace deletion feature.**
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal

**Prerequisite: User B invites User A to a workspace and assigns them as an admin.**

1. As User A, open the workspace list page.
2. Press the 3-dot button on the workspace.
3. Verify that there is no "Delete" button.
4. Open the workspace profile page.
5. Verify that there is no "Delete" button.


Do we agree 👍 or 👎

**Comment by bernhardoj** [comment] 2024-08-15 02:44
Requested in ND.

**Comment by strepanier03** [comment] 2024-08-15 16:50
summary [here](https://github.com/Expensify/App/issues/46344#issuecomment-2289494710).

**Comment by jayeshmangwani** [comment] 2024-08-15 18:13
Requested on ND as per https://github.com/Expensify/App/issues/46344#issuecomment-2289494710

**Comment by strepanier03** [comment] 2024-08-15 20:51
Great! Since you've both requested and Jason has been assigned and pinged I'm going to close this. Reopen if you need any assistance with this in the future.

**Closed by strepanier03** 2024-08-15 20:51 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 10:56
$250 approved for @jayeshmangwani

**Comment by JmillsExpensify** [comment] 2024-08-21 10:58
$250 approved for @bernhardoj
