### ISSUE TITLE
[$250]  Save the world - Principals whisper message in #teachers-unite shows the teacher as "Hidden"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43846] opened 2024-06-17 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635818&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Navigate to Account settings - Save the world - I know a teacher
4. Input anything for the name fields, and an expensifail email address to the email field
5. Click on the "Let's do this!" button

## Expected Result:
The principal added the teacher with a full name and email address so the name or at least, the email address should be shown

## Actual Result:
Principals whisper message from Expensify.org Admin in #teachers-unite shows the teacher as "Hidden"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6322a374-d95b-4276-a80b-7e4300f54f3d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106b42c9c00ea9afa</li>
        <li>Upwork Job ID: 1803768783432548906</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by lanitochka17** [comment] 2024-06-17 15:25
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment] 2024-06-18 09:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Save the world - Principals whisper a message in #teachers-unite shows the teacher as "Hidden"

### What is the root cause of that problem?

The main root cause of the problem is that when the teacher is referred, the [`referTeachersUniteVolunteer`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L42) function is called to send the data the backend without saving the `personalDetails` in the onyx.

However, unlike the [`addSchoolPrincipal`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L70) function, the [`referTeachersUniteVolunteer`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L42) function doesn't optimistically add the `personalDetails` of the referred teacher in the onyx.

Furthermore, the response from the backend in the report action only includes `<mention-user accountID=\"17571571\"\/>` in the message without sending back the `personalDetails` like below. 

![Screenshot 2024-06-18 at 12 35 40](https://github.com/Expensify/App/assets/22982173/7eb0a69f-556a-4596-b630-7634b73ba6ed)

Therefore, when the `accountID` is not found in the `personalDetails`, it shows "Hidden".

Only, when the `OpenReport` API is called is when the `personalDetails` of the referred teacher is synced with the onyx. 

### What changes do you think we should make to solve the problem?


We should make the [`referTeachersUniteVolunteer`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L42) function consistent with the [`addSchoolPrincipal`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L70) function by optimistically adding the referred teacher's `personalDetails` in the onyx.

This will also improve the offline experience when a teacher is being referred when the user is offline.

Therefore, the `optimisticData`, `successData`, and `failureData` should look like the [`addSchoolPrincipal`](https://github.com/Expensify/App/blob/9ec57c03f64e56271b2b507064fa72323463c560/src/libs/actions/TeachersUnite.ts#L70) function, mainly the `personalDetails` to avoid the new `accountID` from showing "Hidden", since the user's data it is not found in the `personalDetails`.

**Comment by greg-schroeder** [comment] 2024-06-25 23:28
Bump on proposal review @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-06-25 23:40
I like @Tony-MK's proposal https://github.com/Expensify/App/issues/43846#issuecomment-2175692058

**Comment by muttmuure** [comment] 2024-06-27 09:41
This is not a #newdot-quality bug - the feature is not unreliable, slow or performing redundant or unexpected API calls, it just doesn't work as designed

**Comment by greg-schroeder** [comment] 2024-07-03 19:49
@youssef-lr can you confirm the contributor assignment here?

**Comment by greg-schroeder** [comment] 2024-07-03 19:49
I believe that is this one: https://github.com/Expensify/App/issues/43846#issuecomment-2190208844

**Comment by youssef-lr** [comment] 2024-07-08 12:50
I'm not sure how I completely missed the bumps in this issue, apologies!

**Comment by rushatgabhane** [comment] 2024-07-08 19:45
@Tony-MK how's it going? Could you please attach a PR

**Comment by Tony-MK** [comment] 2024-07-09 04:11
@rushatgabhane, It is going great.

How about you?

Could you give me a few hours to finish up the PR?

Thanks.

**Comment by greg-schroeder** [comment] 2024-07-09 11:52
PR is underway

**Comment by rushatgabhane** [comment] 2024-07-13 02:05
@youssef-lr @Tony-MK has updated their proposal - https://github.com/Expensify/App/issues/43846#issuecomment-2175692058


Calling openReport sounds unnecessary to me. 
@youssef-lr this should be fixed in backend, right? 

Backend should send the missing personal details data via pusher after refer pusher api call.

What do you think?

**Comment by greg-schroeder** [comment] 2024-07-16 22:10
@youssef-lr can you confirm if this is in fact a BE/internal issue based on the above comment?

**Comment by youssef-lr** [comment] 2024-07-17 15:40
Checking this one today @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-08-14 10:34
Bump @youssef-lr

**Comment by greg-schroeder** [comment] 2024-08-27 05:28
Bump @youssef-lr

**Comment by youssef-lr** [comment] 2024-08-30 20:13
Yeah I can still reproduce this, I think it's weird because I believe that if you invite someone to the platform they should be known to you. I'll find some time to investigate this next week. 

<img width="1414" alt="Screenshot 2024-08-30 at 21 12 40" src="https://github.com/user-attachments/assets/c2ce4a49-bd13-4705-a1f6-d4b8e7b1167f">

**Comment by greg-schroeder** [comment] 2024-09-09 06:23
All right, thanks for letting me know @youssef-lr

**Comment by greg-schroeder** [comment] 2024-09-17 00:53
Any thoughts on where this one should go next @youssef-lr ?

**Comment by greg-schroeder** [comment] 2024-09-27 19:33
Bump @youssef-lr

**Comment by youssef-lr** [comment] 2024-09-27 19:35
I'm really not sure I can prioritise this any time soon. Have we confirmed this is still reproducible?

**Comment by greg-schroeder** [comment] 2024-10-01 01:46
I'm closing this as #vip-vsb is now on hold/closed for now.

**Closed by greg-schroeder** 2024-10-01 01:46 UTC
Labels: Reviewing, External, Weekly, Bug
