### ISSUE TITLE
[HOLD FOR PAYMENT - 2024-03-03] IOU-Billable option is shown in send money confirmation page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37489] opened 2024-02-29 12:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a 1:1 report
3. Tap plus icon near compose
4. Tap send money
5. Enter an amount
6. Tap next

## Expected Result:
Billable option must not be shown in send money confirmation page.

## Actual Result:
Billable option is shown in send money confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a0404fee-ccfc-4dab-b37f-57bea58bb30e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by izarutskaya** [comment] 2024-02-29 12:23
@Julesssss I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-bills.

**Comment by situchan** [comment] 2024-02-29 16:02
regression from https://github.com/Expensify/App/pull/34168
cc: @kubabutkiewicz @hoangzinh

**Comment by puneetlath** [comment] 2024-02-29 17:05
FYI, this is likely fixed by [this revert](https://github.com/Expensify/App/pull/37529). Will have QA re-test once it is CP'd.

**Comment by puneetlath** [comment] 2024-02-29 18:55
Looks like the revert fixed this.

**Closed by puneetlath** 2024-02-29 18:55 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
