### ISSUE TITLE
[HOLD 16078] Web - Emoji options/mention options are dismissed on scroll

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21866] opened 2023-06-29 13:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type in large message to enable scroll
4. Type @email/phone for mention or :emoji_name for suggestion
5. Scroll in compose box and observe that cursor is focused at the end of text but mention/emoji suggestion options are closed

## Expected Result:
App should not close emoji suggestion/mention options if focus is still on it

## Actual Result:
 App closes emoji suggestion/mention options on scroll in compose box even though focus is still at the end of text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fc3ec783-308c-4b6a-91e8-f9d3f5570308

https://github.com/Expensify/App/assets/93399543/22fb621e-a774-4471-b299-ad7c06990024

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687946592585669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment] 2023-06-29 13:54
This seems intentional and not a bug.
cc @MonilBhavsar

**Comment by dylanexpensify** [comment] 2023-06-30 10:09
posted in slack clarifying about this flow

**Comment by dylanexpensify** [comment] 2023-07-03 08:49
reviewing today and posting next steps!

**Comment by MonilBhavsar** [comment] 2023-07-03 10:41
> This seems intentional and not a bug.
cc @MonilBhavsar

Sorry, could you please mention the context here?

**Comment by dylanexpensify** [comment] 2023-07-04 11:16
Hmm, I think we would keep the option menu open. @MonilBhavsar would you agree??

**Comment by MonilBhavsar** [comment] 2023-07-04 11:32
I think current implementation is fine considering the suggestion modal is different element.
We can also go with the implementation like in slack - the modal stays open and overlays the compose box and scroll functionality is disabled while modal is open.

And, in this issue - https://github.com/Expensify/App/issues/16078 we're updating suggestion modals to work inline. So, I think we should keep it on HOLD for that issue.

**Comment by MonilBhavsar** [comment] 2023-07-04 11:36
We're also dealing with this issue  - https://github.com/Expensify/App/issues/15934 where the expected behavior is almost opposite. In that issue, modal stays open after sending the message and we want to close it 😅 
We can find the solution that works for both cases

**Comment by dylanexpensify** [comment] 2023-07-10 09:39
@MonilBhavsar just gut checking! 🙇‍♂️

**Comment by MonilBhavsar** [comment] 2023-07-10 09:56
Yep, can be on HOLD and weekly.

**Comment by MonilBhavsar** [comment] 2023-07-10 09:59
> I think https://github.com/Expensify/App/issues/15934 is something different. There, we're sending the message. Here though, we are not sending the message but just scrolling.

@allroundexperts agree, but I think technically they are same - We want to keep/remove focus on the suggestion modal while we're scrolling.

> The behaviour here is also inconsistent. If you scroll the chat report, you'll notice that the menu remains open. But if you scroll the composer, the menu closes. I think we should either close the menu when scrolling anywhere or just show it regardless of the scroll. Second option makes more sense to me.

Hmm, To fix both issues and have consistency. I think we should simply disable scrolling when suggestion modal is open. Said other way, suggestion modal element and scroll should not be active or be able to have focus at the same time.

**Comment by dylanexpensify** [comment] 2023-07-12 08:48
On hold

**Comment by dylanexpensify** [comment] 2023-07-20 20:39
on hold

**Comment by dylanexpensify** [comment] 2023-07-31 09:02
Hold

**Comment by dylanexpensify** [comment] 2023-08-10 10:24
On hold! @MonilBhavsar any idea when we can remove the hold here?

**Comment by dylanexpensify** [comment] 2023-08-18 19:17
hold!

**Comment by dylanexpensify** [comment] 2023-08-25 11:56
holddddd

**Comment by MonilBhavsar** [comment] 2023-08-25 13:38
@dylanexpensify updated the title to reflect the parent issue

**Comment by dylanexpensify** [comment] 2023-09-04 10:10
perfect, still hold

**Comment by dylanexpensify** [comment] 2023-09-13 09:18
Reviewing!

**Comment by dylanexpensify** [comment] 2023-09-20 08:48
@MonilBhavsar any updates? 🙇‍♂️ ❤️

**Comment by dylanexpensify** [comment] 2023-10-02 13:19
bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-10-02 13:25
Sorry, missed previous comment.
We're still holding this issue https://github.com/Expensify/App/issues/15934 on https://github.com/Expensify/App/issues/16078
So, this issue should be on HOLD for https://github.com/Expensify/App/issues/16078. We're waiting for reviews from react-native maintainers

**Comment by dylanexpensify** [comment] 2023-10-10 14:26
still on hold

**Comment by dylanexpensify** [comment] 2023-10-24 22:58
same ^

**Comment by dylanexpensify** [comment] 2023-11-07 10:16
holding

**Comment by dylanexpensify** [comment] 2023-11-14 10:15
same

**Comment by dylanexpensify** [comment] 2023-11-22 09:39
holding

**Comment by dylanexpensify** [comment] 2023-12-05 19:45
same

**Comment by dylanexpensify** [comment] 2023-12-11 08:11
can still repro, but I don't think this is worth fixing now

**Closed by dylanexpensify** 2023-12-11 08:11 UTC
Labels: Weekly, Bug
