### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Public room - User avatar for thread in LHN shows default avatar instead of custom avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34153] opened 2024-01-09 15:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a public room as a user with custom avatar
2. Send a message and also send a reply in thread
3. Navigate to the public room as anonymous user
4. Click on the thread

## Expected Result:
The user avatar for the thread in LHN shows the correct custom avatar

## Actual Result:
The user avatar for thread in LHN shows default avatar instead of custom avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6336783_1704813005005!Screenshot_2024-01-09_at_22 50 07](https://github.com/Expensify/App/assets/78819774/c9639f06-6d41-4b3c-9e2c-cbe741876675)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01519563f8852a0b41</li>
        <li>Upwork Job ID: 1744740796561666048</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28101650</li>
<li>bernhardoj | Contributor | 28101651</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-09 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User avatar for public room thread shows the default avatar instead of the custom avatar.

### What is the root cause of that problem?
In LHNOptionsList component, we only take the minimum personal details object based on the report participant.
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/LHNOptionsList/LHNOptionsList.js#L121-L123

However, for an anonymous user, every report has an empty participant. So, we pass empty personal details to `OptionRowLHNData`. When we are trying to get the author avatar (parentReportAction.actorAccountID) of a thread,
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/libs/ReportUtils.ts#L1373-L1384

we get the default avatar because the personal detail is empty.

### What changes do you think we should make in order to solve the problem?

Anonymous user can only access public room and it's thread. Public room avatar doesn't have a problem because it's a workspace avatar, so we just need to handle the missing personal detail object of the thread author. To fix it, we can include the parentReportAction.actorAccountID to the LHNOptionsList minimum personal details here.
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/LHNOptionsList/LHNOptionsList.js#L121-L123

```
itemParentReportAction.actorAccountID
```

**Comment by ikevin127** [comment] 2024-01-09 16:40
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The thread actor LHN avatar shows default avatar to anonymous user instead of the thread actor's custom avatar.

## What is the root cause of that problem?

When visiting a thread as an anonymous user the parent report's `actorAccountID` is not added to the `participants` array in `LHNOptionsList.js`. This causes `UserUtils.getDefaultAvatar(cleanAccountID)` to return `FallbackAvatar`.

## What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/8925a89e4af1c60bc58c310635c67756ce216a03/src/components/LHNOptionsList/LHNOptionsList.js#L121

First off in the line above replace the `ReportUtils.getParticipantsIDs()` deprecated method with `ReportUtils.getVisibleMemberIDs()` then perform the following changes:
- add a second optional argument named `parentReportAction` to the `ReportUtils.getVisibleMemberIDs()` function
- pass `itemParentReportAction` as the second argument
- within `ReportUtils.getVisibleMemberIDs()` add an if that checks: `(isThread(report) && isAnonymousUser && !_.isEmpty(parentReportAction))` and if `true` add the `parentReportAction.actorAccountID` to the `visibleChatMemberAccountIDs` array

the if makes sure that when the report is a thread, user is anonymous and passed argument `parentReportAction` is not empty and contains `actorAccountID` then we do a final check to make sure the `actorAccountID` is not already part of the `visibleChatMemberAccountIDs` array and if not - we add it.

## Screenshots

<details>
<summary>MacOS: Chrome</summary>

<img width="768" alt="Screenshot 2024-01-09 at 18 37 14" src="https://github.com/Expensify/App/assets/56457735/450d3002-dce3-4e12-bcd6-84d4672186a7">

</details>

**Comment by s77rt** [comment] 2024-01-10 18:29
@bernhardoj Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34153#issuecomment-1883289929)

**Comment by s77rt** [comment] 2024-01-10 18:29
@dukenv0307 Thanks for the proposal but it's unfortunately a dupe.

**Comment by s77rt** [comment] 2024-01-10 18:30
@ikevin127 Thanks for the proposal. I think it's a dupe as well.

**Comment by s77rt** [comment] 2024-01-14 23:30
Not overdue. @cristipaval https://github.com/Expensify/App/issues/34153#issuecomment-1885400053

**Comment by dylanexpensify** [comment] 2024-01-17 09:34
Merged! Huzzah!

**Comment by s77rt** [comment] 2024-01-22 00:47
- The PR that introduced the bug has been identified: I think the PR that introduced the bug is internal. It's the one that made the BE return empty `participantAccountIDs` for public rooms (that you don't own)
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: I don't think we need this here
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Create a public room if you don't have one
2. Send a message in the room as a user with a custom avatar
3. Create a thread from that message
4. Sign out and open the public room as an anonymous user
5. Open the thread
6. On the LHN, verify the thread avatar shows the custom avatar of the user that owns the thread message

**Comment by dylanexpensify** [comment] 2024-01-23 13:21
two more days!

**Comment by dylanexpensify** [comment] 2024-01-29 11:53
done

**Closed by dylanexpensify** 2024-01-29 11:53 UTC
Labels: External, Weekly, Awaiting Payment, Bug
