### ISSUE TITLE
[HOLD for #21696]Tooltip not shown in workspace invite page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21726] opened 2023-06-27 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new workspace and go to members (can be of existing workspace)
2. Hove on person in the list

## Expected Result: 
Tooltip should be shown as it's shown on other lists
## Actual Result: 
Tooltip not shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c98bf813-1655-491b-9747-c64cc6e5d160

https://github.com/Expensify/App/assets/43996225/e8a42c8c-4fa9-44f9-b07e-a773f1758305

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687628052221969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-06-27 19:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip not shown in workspace invite page.

### What is the root cause of that problem?
In workspace invite page, account is displayed using below code.
https://github.com/Expensify/App/blob/5f5dd023a8102ef47ac4b58e4bfe79b995cb0330/src/pages/workspace/WorkspaceInvitePage.js#L285-L301
There is not `showTitleTooltip` `props`, so tooltip is not shown.

### What changes do you think we should make in order to solve the problem?
We can add `showTitleTooltip` `props`.
```js
<OptionsSelector
        contentContainerStyles={[styles.flexGrow1, styles.flexShrink0, styles.flexBasisAuto]}
        listContainerStyles={[styles.flexGrow1, styles.flexShrink1, styles.flexBasis0]}
        canSelectMultipleOptions
        sections={sections}
        selectedOptions={this.state.selectedOptions}
        value={this.state.searchTerm}
        shouldShowOptions={OptionsListUtils.isPersonalDetailsReady(this.props.personalDetails)}
        onSelectRow={this.toggleOption}
        onChangeText={this.updateOptionsWithSearchTerm}
        onConfirmSelection={this.inviteUser}
        headerMessage={headerMessage}
        hideSectionHeaders
        boldStyle
        showTitleTooltip
        shouldFocusOnSelectRow={!Browser.isMobile()}
        textInputLabel={this.props.translate('optionsSelector.nameEmailOrPhoneNumber')}
    />
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by BhuvaneshPatil** [comment] 2023-06-27 20:10
I checked with this PR https://github.com/Expensify/App/pull/21696 - The issue will be fixed.
The bug was reported 3 days ago on slack.

**Comment by kadiealexander** [comment] 2023-06-28 06:10
Thanks @BhuvaneshPatil!!

**Comment by BhuvaneshPatil** [comment] 2023-06-30 07:22
@kadiealexander PR mentioned above got merged, I verified with pulling main branch. It's solved the bug.

**Comment by kadiealexander** [comment] 2023-07-03 02:48
I think technically the original bug reporter gets paid for this one, since they reported it [back on June 13th](https://expensify.slack.com/archives/C049HHMV9SM/p1686629969783219) :)

Closing this since the bug is solved!

**Closed by kadiealexander** 2023-07-03 02:48 UTC
Labels: Daily, Overdue, Bug

**Comment by BhuvaneshPatil** [comment] 2023-07-03 03:58
@kadiealexander
The root cause was same, bug was different

**Comment by BhuvaneshPatil** [comment] 2023-07-07 18:29
@kadiealexander Friendly bump.
