### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Capitalization in email search causing duplicate email in member invite preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21599] opened 2023-06-26 18:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace in settings and navigate to the member section to invite new members.
2. Search for a member by capitalizing the first letter of their email and marking it.
3. Search for the same email with all lowercase letters and notice that it appears as a duplicate. Mark it as well.
4. Add the marked emails to the members and notice that only the email with all lowercase letters is invited, while the capitalized email is not invited, causing confusion for users
## Expected Result:
 When searching for an email, capitalization should not affect the search results, and duplicate emails should not appear in the member invite preview.
## Actual Result: 
When searching for an email by capitalizing the first letter and marking it, and then searching for the same email with all lowercase letters, the email appears as a duplicate in the member invite preview. Only the email with all lowercase letters is invited, causing confusion for users

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (37).webm](https://github.com/Expensify/App/assets/43996225/339bb3ee-0bc7-4c6e-9be5-c552882d9ec3)

https://github.com/Expensify/App/assets/43996225/bd66d642-76aa-4686-9085-65e7e8eab8c5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687338486243019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ccc4dfa896d2e90</li>
        <li>Upwork Job ID: 1673472018851819520</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-06-26 18:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Capitalization in email search causing duplicate email in member invite preview.

### What is the root cause of that problem?

The root cause of this issue is that when the search value is a legal email to invite

1. We don't convert it to lowercase for `userToInvite.login`, see the [snippet](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L777-L802) to construct `userToInvite`, and 
2. We do case sensitive comparing when determining `hasUnselectedUserToInvite`, see [snippet](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L153-L155) 

So, we're able to search and select multiple emails, like, `safds@gmail.com`,  `Safds@gmail.com` and  `sAfds@gmail.com` , which are same because email is case insensitive. 

### What changes do you think we should make in order to solve the problem?

According to the RCA above and the fact that email is case insensitive, I think we can fix this issue from the [snippet](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L777-L802) to construct `userToInvite`. 

To achieve it, we can add a variable `userLoginToInvite` which is lowercase of `searchValue`

```js
const userLoginToInvite = searchValue.toLowerCase();
```

after this line

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L778

and replace all usages of `searchValue` to `userLoginToInvite` within the [snippet](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L777-L802) to construct `userToInvite`. The key replacement is this line 

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L791

to avoid searching and selecting duplicates. While replacing all usages within the [snippet](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L777-L802) will be helpful to avoid confusion from UX. For example, if we start searching `Asfs@gmail.com`, then there'll be an optional email `Asfs@gmail.com` with capital letter to invite. But after invited, the backend will convert the email to lowercase `asfs@gmail.com` from the Workspace members list page.

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/02877b45-038b-45a7-b5d5-61dab21f55ab
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kevinksullivan** [comment] 2023-06-26 23:22
reproduced 
<img width="414" alt="image" src="https://github.com/Expensify/App/assets/22508290/2c4dfdf1-69cf-4124-aea6-27a905bb237b">

**Comment by sobitneupane** [comment] 2023-06-30 08:01
@eh2077 Thanks for your proposal.

How about converting `searchInputValue` to lower case at the beginning of `getOptions()` function (if we decide to make all searches case insensitive)? Why did you propose to convert in down the function? Is there any unwanted behavior if we do it in the beginning?

**Comment by eh2077** [comment] 2023-06-30 08:51
@sobitneupane Thanks for reviewing proposal!

> How about converting `searchInputValue` to lower case at the [beginning](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L619) of `getOptions()` function (if we decide to make all searches case insensitive)? 

That's a great point. I think we can convert `searchInputValue` to lower case at the beginning of `getOptions()` function.
I checked the usages of `searchValue` in the `getOptions()` function and confirmed that lower case of `searchValue` won’t break following usages in the function
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L731
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L752
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L760
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L820

In method [isSearchStringMatch](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L538), we also do case insensitive matching.

> Why did you propose to convert in down the function? Is there any unwanted behavior if we do it in the beginning?

I think I overlooked these lines
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/OptionsListUtils.js#L820-L825
I thought that case matters when ordering at the first glance of the condition and the comments. But, actually, it'll be safe to convert `searchInputValue` to lower case at the beginning of `getOptions()` function.

**Comment by eh2077** [comment] 2023-06-30 17:16
### Proposal
[Updated](https://github.com/Expensify/App/issues/21599#issuecomment-1608007743) to convert `searchInputValue` to lower case at the beginning of `getOptions()` function.

cc @sobitneupane

**Comment by sobitneupane** [comment] 2023-07-03 12:18
[Proposal](https://github.com/Expensify/App/issues/21599#issuecomment-1608007743) from @eh2077 looks good to me. Since we are doing case insensitive matching, I don't think converting the `searchInputValue` to lowercase will have any unwanted impact.


🎀 👀 🎀 C+ reviewed

**Comment by eh2077** [comment] 2023-07-04 05:43
There's a deploy blocker https://github.com/Expensify/App/issues/22123 blocks the testing of this PR. I'm going to revert that [issue PR](https://github.com/Expensify/App/pull/21700#pullrequestreview-1511446993) or apply the [on-going fix](https://github.com/Expensify/App/pull/22132) to continue test PR for this issue.

cc @sobitneupane

**Comment by tewodrosGirmaA** [comment] 2023-07-04 05:47
Hi, @eh2077. can I apply to Upwork?

**Comment by eh2077** [comment] 2023-07-04 05:57
@tewodrosGirmaA I think you should apply it for the report bonus. It looks like the team changed workflow recently. Yes, the message is a little bit confusing. I think it doesn’t mean the assignment on Github issue but for Upwork.

**Comment by sobitneupane** [comment] 2023-07-04 10:50
@eh2077 Let's hold the PR for now. Since it's a deploy blocker, the issue should be solved by EOD. We can continue with the PR once the related PR get's merged.

**Comment by eh2077** [comment] 2023-07-04 12:17
@sobitneupane The PR https://github.com/Expensify/App/pull/22168 is ready as the [blocker](https://github.com/Expensify/App/pull/22132) has been merged.

**Comment by tewodrosGirmaA** [comment] 2023-07-08 04:29
@sobitneupane , when i check again This issue does not happen anymore in Desctop  web , now it exists on Android![Screenshot_20230707_225459_New Expensify.jpg](https://github.com/Expensify/App/assets/118253010/6731881e-8fcf-46c8-916d-27d9dd2ea96f)

**Comment by eh2077** [comment] 2023-07-08 05:41
@tewodrosGirmaA The fix is only on staging for now. You can get the automation info from the PR.

**Comment by kevinksullivan** [comment] 2023-07-10 17:22
This is awaiting payment after regression period ends, right? It's no longer in review?

**Comment by sobitneupane** [comment] 2023-07-24 14:38
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

I could not locate the exact PR. This could have been created by the change in backend as well.

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1690209472452549
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-07-24 14:39
**Regression Test Proposal**

1. Go to Settings => Workspaces => Select a Workspace => Members => Invite new members
2. Search email abc@gmail.com and select it
3. Search email Abc@gmail.com
4. Verify that email abc@gmail.com remain selected and there's not new email option like Abc@gmail.com

Do we agree 👍 or 👎

**Comment by eh2077** [comment] 2023-07-24 15:18
@kevinksullivan Accepted offer, thanks!

**Comment by sobitneupane** [comment] 2023-07-24 16:32
Payment Requested on newDot.

**Comment by kevinksullivan** [comment] 2023-07-24 19:21
Ah sorry @sobitneupane . I'll withdraw the offer on upwork.

**Comment by eh2077** [comment] 2023-07-27 10:10
Bump @kevinksullivan

**Comment by JmillsExpensify** [comment] 2023-07-27 23:47
@kevinksullivan Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @sobitneupane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by kevinksullivan** [comment] 2023-07-27 23:51
Payout summary:

- Issue reporter: @tewodrosGirmaA $250
- Contributor: @eh2077 $1,500 (merge bonus)
- Contributor+ : @sobitneupane $1,500 (merge bonus)

**Comment by JmillsExpensify** [comment] 2023-07-27 23:51
Reviewed details for @sobitneupane. This is accurate based on summary from Business Reviewer and approved for payment in NewDot.

**Closed** 2023-07-28 23:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
