### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Web - Cursor Changes to Text Cursor Instead of Hand Cursor for Long Private Messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27881] opened 2023-09-20 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and select "send message"
2. Add email and click on the header to access private notes
3. Select "My Notes" and add a long note
4. Go back and observe that the cursor has changed to a text cursor instead of a hand cursor

## Expected Result:
The cursor should remain as a hand cursor for long private messages.

## Actual Result:
The cursor changes to a text cursor for long private messages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-19T222850.192.webm](https://github.com/Expensify/App/assets/93399543/12626281-688f-4c4a-97fa-e7fa38190759)

https://github.com/Expensify/App/assets/93399543/0ed21657-80f0-4b77-8767-23f9a07f6a59

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695186909696099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01901da2d28d6828fb</li>
        <li>Upwork Job ID: 1704567536968368128</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-20 19:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor changes to a text cursor instead of the pointer cursor for private notes with long text.

### What is the root cause of that problem?
In PrivateNotesViewPage, the `MenuItemWithTopDescription` which is used to display the note has the `shouldRenderAsHTML` prop set. This prop triggers a check for rendering the title in the `MenuItem` with this block of code:
```
<View style={styles.chatItemMessage}>
    <RenderHTML html={getProcessedTitle} />
</View>
```

styles.chatItemMessage contains `...cursor.cursorAuto` which causes the I-beam cursor to be used for the text.

### What changes do you think we should make in order to solve the problem?
**Solution 1**
Remove shouldRenderAsHTML prop from PrivateNotesViewPage.

**Solution 2**
Change the style in MenuItem from styles.chatItemMessage to a different style that uses cursorPointer.

### What alternative solutions did you explore? (Optional)
None.

**Comment by jscardona12** [comment] 2023-09-20 19:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Cursor Changes to Text Cursor Instead of Hand Cursor for Long Private Messages
### What is the root cause of that problem?
Hi the root cause is in the styles 
https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/styles/styles.js#L1654-L1663
the 'cursor: auto' on texts is cursor.
### What changes do you think we should make in order to solve the problem?
Add to styles `style={[styles.chatItemMessage, ...cursor.cursorUnset]`, cursor: 'unset' on 
https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/components/MenuItem.js#L259C37-L259C37
### What alternative solutions did you explore? (Optional)

**Comment by ArdaSeremet** [comment] 2023-09-20 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Cursor Changes to Text Cursor Instead of Hand Cursor for Long Private Messages

### What is the root cause of that problem?
The CSS properties of chat item message box (chatItemMessage) contains (cursor: auto) property which lets the browser automatically attach a cursor to elements. chatItemMessage is used for private message items.

### What changes do you think we should make in order to solve the problem?

The first idea that comes to mind is to simply remove cursorAuto property from chatItemMessage box. However, this might cause unexpected behavior for other elements that use chatItemMessage property. The best kind of solution is to eliminate this problem only for MenuItem component. This can be done by excluding cursorAuto property from the style associated with MenuItem component.

**Comment by ArdaSeremet** [comment] 2023-09-20 19:31
Contributor details
Your Expensify account email: ardacoding@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f678e8a316578aae

**Comment by c3024** [comment] 2023-09-20 20:12
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Auto cursor shown when hovered over text in private note
### What is the root cause of that problem?
For private notes we pass prop `shouldRenderAsHTML` and here
https://github.com/Expensify/App/blob/d00a4d6b76a34538d0a93551100582ab5404c96c/src/components/MenuItem.js#L259
the text is wrapped with `View` with style `chatItemMessage` which has cursor style auto.
### What changes do you think we should make in order to solve the problem?
We will just use
```js
<RenderHTML html={getProcessedTitle} />
``` 
for both native and others simply removing the `isNative` conditional and remove `View` wrapped around `RenderHTML`
Since this `RenderHTML` in `MenuItem` is only used for private notes, we can safely make this change.
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment] 2023-09-20 20:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Auto cursor shown when hovered over text in private note
### What is the root cause of that problem?
For private notes we pass prop `shouldRenderAsHTML` and here
https://github.com/Expensify/App/blob/d00a4d6b76a34538d0a93551100582ab5404c96c/src/components/MenuItem.js#L259
the text is wrapped with `View` with style `chatItemMessage` which has cursor style auto.
### What changes do you think we should make in order to solve the problem?
We will just use
```js
<RenderHTML html={getProcessedTitle} />
``` 
for both native and others simply removing the `isNative` conditional and remove `View` wrapped around `RenderHTML`
Since this `RenderHTML` in `MenuItem` is only used for private notes, we can safely make this change.
### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-09-25 04:19
Removing my assignment because we don't need two BZs on the issue and Kadie was assigned first

**Comment by narefyev91** [comment] 2023-09-25 06:59
@fedirjh should we close this one in case potential fixed was merged here https://github.com/Expensify/App/pull/27769

**Comment by kadiealexander** [comment] 2023-10-05 05:29
Thanks @fedirjh, lets close.

**Comment by tewodrosGirmaA** [comment] 2023-10-05 05:36
@kadiealexander I didn't get payment

**Comment by tewodrosGirmaA** [comment] 2023-10-05 05:58
Hello, @kadiealexander I was wondering if I am eligible for payment even though my issue is marked as "Awaiting Payment" and I have not yet received any payment. The issue has been closed and I would appreciate any clarification on this matter. Thank you.

**Comment by kadiealexander** [comment] 2023-10-05 06:00
Please apply here: https://www.upwork.com/jobs/~01901da2d28d6828fb

**Closed** 2023-10-19 00:01 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Awaiting Payment, Bug
