### ISSUE TITLE
[$1000]  Login - "Incorrect magic code..." message is not translated in Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23081] opened 2023-07-18 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Sign in page
2. Enter any Expensify account
3. Fill-in incorrect magic codes
4. Scroll to bottom and change to Spanish language

## Expected Result:
"Incorrect magic code. Please try again or request a new code." message should be displayed in Spanish language

## Actual Result:
Even the app language is changed to Spanish - the message "Incorrect magic code. Please try again or request a new code." is still displayed in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/22b84b5d-ff98-46ae-8327-ef42d1ed3f0d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e1220542398ee6e</li>
        <li>Upwork Job ID: 1683951951539818496</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-07-20 22:10
@hungvu193 this seems like a similar issue as [this one](https://github.com/Expensify/App/issues/22665) - I think this is essentially a dupe

**Comment by adelekennedy** [comment] 2023-07-25 21:30
reproduced! From above this is likely internal but adding the external label so the C+ makes the final call

**Comment by robertKozik** [comment] 2023-07-31 09:44
Sorry for overdue @adelekennedy, missed that one. Yeah I agree that this issue should be internal, as backend should return proper translation key for this error. It cannot be solved only on FE side

**Comment by cristipaval** [comment] 2023-08-01 17:30
I'll have a look tomorrow at this one to check if it is internal.

**Comment by cristipaval** [comment] 2023-08-02 16:55
The issue happens because we do not have internationalization in the backend yet and that error comes from the backend. Closing this issue for now, it will be fixed when we'll support i18n in the backend.

**Closed by cristipaval** 2023-08-02 16:55 UTC
Labels: External, Engineering, Daily, Internal, Help Wanted, Bug

**Comment by ishpaul777** [comment] 2023-08-02 17:08
Sending a translation key from backend  and having a corresponding translation to key in dictionaries will resolve the issue in the mean time.
