### ISSUE TITLE
[$500] Chat -  Hmm its not here displayed on map image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29605] opened 2023-10-14 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697192437355139

## Action Performed:
Action Performed:
1. Open the app
2. Open any report which has distance request message in it or raise one and open that report
3. Click on distance request message, it should open page with pay button in header
4. Send any image in it
5. Open the sent image in preview by clicking on it
6. Click on previous arrow and observe that it displays map for sometime and after it displays Hmm its not here

## Expected Result:
 App should either not display map image in preview or display it without error

## Actual Result:
App displays Hmm its not here on map image in attachment preview when accessing the image by navigating from another image

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/ea3cfb42-0e13-4256-a3ee-5ce2dbd32c3a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/93399543/c56c693e-e2d5-4f6b-80a6-250ff74ef74a

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/115f8099-4af4-4f2d-880c-7b846cd79a7a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/da1268eb-17d5-4772-8708-4d628789adf4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/095a28be-d0b7-4958-a30c-95fbc70e36e7

https://github.com/Expensify/App/assets/93399543/0b9d5d64-3574-4553-aa0d-b3821fdf0cd8

https://github.com/Expensify/App/assets/93399543/153d490c-09f9-4f83-8738-44092fa65b63

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/5875dd7e-7616-4d0f-88b5-d859f8cf25e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc9adefd366e0b5b</li>
        <li>Upwork Job ID: 1713200291476987904</li>
        <li>Last Price Increase: 2023-10-14</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-10-14 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In an Expense report with a receipt, the map is considered as an Attachment and viewing it causes `Hmm its not here` to be shown

### What is the root cause of that problem?
The distance receipt attachment(or any receipt for that matter) is attached to its own chat report. But when viewing the attachments of the parent expense report, those receipts are considered part of it. 

Coming from this check here
https://github.com/Expensify/App/blob/dc1ff84f31ec04206a13489b62f065798e38d7fd/src/components/Attachments/AttachmentCarousel/extractAttachmentsFromReport.js#L48

This will return URLs that are of type  `/receipt ` which are only accessible from the parent report. 
Exmaple: 
Expense `report ID = 7912337812520815`

We get the following attachments 

`r/7912337812520815/attachment?source=/chat-attachments/3179016481252166829/w_10b395181b117114c949bf123f30187c010dab65.png`

`r/7912337812520815/attachment?source=/receipts/w_2d351cf5c9f1c61c66bf3780c4a68342bbeb1a3d.png
`

But the receipt resource is only available from the context of actual chat report ID, which is `reportID=8768068978200431`

### What changes do you think we should make in order to solve the problem?
We can enforce the above check by making sure we are the chat report is type of chat s follow 

`if (ReportActionsUtils.isMoneyRequestAction(action) && report.type === CONST.REPORT.TYPE.CHAT) {`

This will ignore all the receipts from being included as attachments in the expense reports. Then those receipts can be viewed separately, by clicking the chat report related to the money request. 

### What alternative solutions did you explore? (Optional)
If we want to make attachment or receipts accessible from other reports, we might need to introduce a new URL parameter that explicitly sets the `reportID` in the URL, 
let's take the above example again. in this case the `extractAttachmentsFromReport`  should return 

`r/7912337812520815/attachment?source=/chat-attachments/3179016481252166829/w_10b395181b117114c949bf123f30187c010dab65.png&reportID=7912337812520815`

`r/7912337812520815/attachment?source=/receipts/w_2d351cf5c9f1c61c66bf3780c4a68342bbeb1a3d.png&reportID=8768068978200431
`

N/A

**Comment by paultsimura** [comment] 2023-10-16 17:35
It might be worth waiting for https://github.com/Expensify/App/pull/28640 to be merged first. The Receipt + Attachments combinations are pretty unstable before that issue is resolved.

**Comment by miljakljajic** [comment] 2023-10-17 14:23
I think this is worth closing for now and then re-opening if it's still occurring when fix image receipt is merged.

**Closed by miljakljajic** 2023-10-17 14:23 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
