### ISSUE TITLE
[HOLD for payment 2023-09-07] [HOLD for payment 2023-09-06] [$1000]  Attachment- Uploading PDF displays error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26193] opened 2023-08-29 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap plus icon to add attachment
4. Select a pdf file

## Expected Result:
The user must able to see preview and send pdf file

## Actual Result:
The user was shown error message after selecting a pdf file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd40a282-1439-4b51-b058-e939415a23c4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6f875237866634b</li>
        <li>Upwork Job ID: 1696592406863446016</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by hannojg** [comment] 2023-08-29 12:35
Do we have a stack trace for this?

**Comment by pradeepmdk** [comment] 2023-08-29 13:24
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Attachment- Uploading PDF displays error

### What is the root cause of that problem?
 NewExpensify crash caught by error boundary - Cannot read property 'onPinchGestureChange' of null 
https://github.com/Expensify/App/blob/3f9f1e6e2ce91468a536755f8d5830a2f77d7eaa/src/components/Attachments/AttachmentView/AttachmentViewPdf/index.native.js#L11

from this pr https://github.com/Expensify/App/pull/25529/files
### What changes do you think we should make in order to solve the problem?


we need check attachmentCarouselPagerContext is there or not
```javascript
   useEffect(() => {
        if(attachmentCarouselPagerContext) {
            attachmentCarouselPagerContext.onPinchGestureChange(false);
        }        
        // eslint-disable-next-line react-hooks/exhaustive-deps -- we just want to call this function when component is mounted
    }, [attachmentCarouselPagerContext]);
```

**Comment by Li357** [comment] 2023-08-29 13:33
@pradeepmdk That looks reasonable, can you show a video of the fix working? Since this is a deploy blocker, we want to fix this fast!

**Comment by pradeepmdk** [comment] 2023-08-29 13:37
https://github.com/Expensify/App/assets/16595846/0107aff9-0b6e-48db-a709-ee03e4c8180c

**Comment by Li357** [comment] 2023-08-29 15:18
@aimane-chnaif @tienifr has gone offline and we want to keep this blocker fix moving. @pradeepmdk can you raise a PR?

**Comment by pradeepmdk** [comment] 2023-08-29 15:19
sure @Li357 i am ready

**Comment by pradeepmdk** [comment] 2023-08-29 15:25
@aimane-chnaif  PR is ready https://github.com/Expensify/App/pull/26218/files

**Comment by pradeepmdk** [comment] 2023-08-29 18:13
@luacmartins I think we need to make it external so that the bot will create upwork tasks.

**Comment by pradeepmdk** [comment] 2023-08-29 18:23
@Li357 can you update the payment as well so that maybe i will get the work contract.

**Comment by MitchExpensify** [comment] 2023-09-06 16:07
**Payment summary:**

Reporting: NA
C: @pradeepmdk: $1500 (Upwork)
C+: @aimane-chnaif: $1500 (Upwork)

@luacmartins Was there a regression here just to be sure? Seems not but double checking

**Comment by MitchExpensify** [comment] 2023-09-07 10:37
Ok cool, thanks for confirming. Let's get the BZ steps squared away @aimane-chnaif  - Issuing payment now

**Comment by MitchExpensify** [comment] 2023-09-07 10:42
Invited you to the job @aimane-chnaif 

Please apply to the job for payment, thank you! @pradeepmdk https://www.upwork.com/jobs/~01b6f875237866634b

**Comment by pradeepmdk** [comment] 2023-09-07 10:45
@MitchExpensify  can you invite me as well https://www.upwork.com/freelancers/~0146d771ed1c776acb

**Comment by pradeepmdk** [comment] 2023-09-07 11:02
@MitchExpensify Thank you!! accepted..

**Comment by MitchExpensify** [comment] 2023-09-07 12:14
Paid and contract ended. Next step - BZ steps cc @aimane-chnaif

**Comment by luacmartins** [comment] 2023-09-11 13:13
@aimane-chnaif could you complete the BZ checklist please?

**Comment by luacmartins** [comment] 2023-09-12 01:38
I think we're all done here, right? Gonna close the issue, let me know if we're missing anything.

**Closed by luacmartins** 2023-09-12 01:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by luacmartins** [comment] 2023-09-12 03:13
@MitchExpensify can you please check on that?

**Comment by MitchExpensify** [comment] 2023-09-12 14:54
Oops, sorry about that. Not sure how that payment was missed - Fixed! @aimane-chnaif  cc @luacmartins
