### ISSUE TITLE
Web- Personal details - Once selected year of birth cannot be changed again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24315] opened 2023-08-09 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on Avatar> Profile> Personal details> Date of birth
3. Select any Date, Month and Year
4. Click on "Save" button
5. Navigate back by hitting the "Back" button
6. Click on Date of birth
7. Select any Year different from Step 3
8. Click on "Save" button

## Expected Result:
New input should be updated and displayed in Date of birth section

## Actual Result:
Once selected year of birth cannot be changed again. Date of birth section displays the previously entered Date

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d06e6d7d-3d55-49f7-a541-b547edeb60e2

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-08-09 13:42
It looks like this is a case of confusing UX, and not necessarily a bug. The year picker simply changes the current year for the date picker, and the user still has to select a day from the picker to actually update the date of birth.

**Comment by aditygrg2** [comment] 2023-08-09 13:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The state is not changing on only changing variables like year and month.

### What is the root cause of that problem?

There is no state updation for variables year and month. Only when a particular date is selected, a state is updated.

### What changes do you think we should make in order to solve the problem?

We can simply add a state on changing year [here](https://github.com/Expensify/App/blob/9a6b4a875b3a04c6b414a9971527cc17ffa4bb28/src/components/NewDatePicker/CalendarPicker/index.js#L80), and for months [here]( https://github.com/Expensify/App/blob/9a6b4a875b3a04c6b414a9971527cc17ffa4bb28/src/components/NewDatePicker/CalendarPicker/index.js#L111C24-L111C24) and [here](https://github.com/Expensify/App/blob/9a6b4a875b3a04c6b414a9971527cc17ffa4bb28/src/components/NewDatePicker/CalendarPicker/index.js#L118)

To handle edge cases, for example, Feb have only 28 days most of the times, and 29 days once in 4 years, the states can handle itself by selecting last values, so if March have 31 days, selecting Feb will automatically set state to 28/29. Similarly we can think of edge cases in year too.

### What alternative solutions did you explore? 

N/A

This might be an issue UX wise, as user sometimes select incorrect year only and changing year then does not change state. But maybe we might not need states in month, which can be removed.

**Comment by Habben101** [comment] 2023-08-09 14:40
### Proposal  
### Please re-state the problem that we are trying to solve in this issue.  
Unable to change the selected year of birth once it has been initially selected. The date of birth section displays the previously entered date, and the year selection appears to be locked after the initial selection.  

### What changes do you think we should make in order to solve the problem?
The issue arises from how the onYearSelected function is managing the state updates. The state might not be getting fully updated to reflect the new year selection, leading to incorrect rendering and preventing users from changing the year again.  

### What changes do you think we should make in order to solve the problem?
we need to ensure that the `onYearSelected` function correctly updates both the `currentDateView` and the `years` array in the state. Here's what needs to be changed:

- In the `onYearSelected` Function:
Modify the `onYearSelected` function to update both the `currentDateView` and the years array. Ensure that the `isSelected` property of the years is correctly updated for the newly selected year.
- In the `setState` Call:
We can use the callback version of `setState` to ensure that the `onSelected` function is triggered after the state has been fully updated. This ensures that the correct date with the newly selected year is passed to the `onSelected` function.

So, we could change the [onYearSelected](https://github.com/Expensify/App/blob/a457069f2b71003bcd4998d5702660063dc9d37e/src/components/NewDatePicker/CalendarPicker/index.js#L80C1-L93C6) function to this:

```javascript
onYearSelected(year) {
     this.setState((prevState) => {
        const newCurrentDateView = moment(prevState.currentDateView).set('year', year).toDate();

        const updatedYears = prevState.years.map((item) => ({
            ...item,
            isSelected: item.value === newCurrentDateView.getFullYear(),
         }));

         return {
             currentDateView: newCurrentDateView,
             years: updatedYears,
             isYearPickerVisible: false,
         };
      }, () => {
          this.props.onSelected(moment(this.state.currentDateView).format('YYYY-MM-DD'));
    });
 }
``` 
Result:

https://github.com/Expensify/App/assets/25123389/06d5b9e4-f257-4ced-bdf4-7643c3b42e0f

### What alternative solutions did you explore?  
NA

**Comment by alexpensify** [comment] 2023-08-11 23:58
I've tested and agree with @akinwale 

>It looks like this is a case of confusing UX, and not necessarily a bug. The year picker simply changes the current year for the date picker, and the user still has to select a day from the picker to actually update the date of birth.

If you change the year, then you need to select the date again. The original date selected does not edit when you change the year. For example, 1979-08-01 does not edit to the new year selected like 1982-08-01. 

![2023-08-11_16-56-10](https://github.com/Expensify/App/assets/8107070/43bc5fa8-c992-4fb3-a4b3-d5a245c090db)

I'll need to continue reviewing this one to see if this is on purpose or I should close this GH.

**Comment by alexpensify** [comment] 2023-08-14 21:53
I've started a discussion here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1692049999219919

**Comment by alexpensify** [comment] 2023-08-15 00:54
Thanks for flagging!

**Closed** 2023-08-15 00:55 UTC
Labels: Daily, Bug
