### ISSUE TITLE
Clicking on the expired sign-in link should navigate users to the magic code page instead of the login page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24031] opened 2023-08-02 03:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: 
- The app is logged out.
- There is an expired sign-in link in the email inbox. 

1. Open the email inbox.
2. Click on any expired sign-in link.
3. The app opens, and observe that the message "Incorrect magic code. Please try again or request a new code" is displayed on the login page.

## Expected Result:
- Clicking on the expired sign-in link should navigate users to the magic code page instead of the login page.
- OR, The error message should be changed to something more helpful, Eg: "Sign-in link is expired."

## Actual Result:
The message "Incorrect magic code. Please try again or request a new code" is displayed on the login page, which is confusing.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [ ] Android / Chrome
- [X] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/d1c15ce1-2da0-4592-a3e0-86fe2c97b300

Uploading Record_2023-08-01-23-43-53_4f9154176b47c00da84e32064abf1c48.mp4…

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690784822780409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2023-08-02 12:28
Agreed, this is not a bug. Closing this out.

**Closed by bfitzexpensify** 2023-08-02 12:28 UTC
Labels: Daily, Bug
