### ISSUE TITLE
Invite new members to workspace text-input is not focused - Reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10587] opened 2022-08-26 04:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on use icon to open setting page.
2. Click on workspace > manage members > invite .

## Expected Result:
Search field of invite new members should be focused.

## Actual Result:
Search field is not focused

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186821068-9b6fcc6f-6ed6-4ff4-84cd-d82045253453.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661437929132899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by varshamb** [comment] 2022-08-26 15:23
### Proposal

In workspaceinvite page Autofocus for OptionsSelector is false. Making it true will fix this issue.

**Comment by neil-marcellini** [comment] 2022-08-26 18:08
Re-opening because the Slack discussion is ongoing and there's some good points there.

**Comment by neil-marcellini** [comment] 2022-08-26 18:11
I think this would be a good external issue, but we should hold on implementation until we decide what to do in Slack.

**Comment by zanyrenney** [comment] 2022-10-18 19:19
@neil-marcellini it looks like we landed on doing nothing for now. Please can you confirm your thoughts as you said hold until we decide in slack... Thanks!

**Comment by zanyrenney** [comment] 2022-10-18 19:19
oops! didn't mean to close with that comment.

**Comment by neil-marcellini** [comment] 2022-10-18 23:35
I don't think we have talked about it anymore since then. I don't see anything from a quick Slack search. We could close this or make it Monthly again.

**Comment by mountiny** [comment] 2022-10-19 17:57
Checked in with Zany on this one, it is an old issue and not reproducible in staging/prod anymore so we are good to close it 🎉

**Comment by zanyrenney** [comment] 2022-10-19 17:57
Asked Vit to doublecheck on Dev as I don't have access.

**Closed by mountiny** 2022-10-19 17:57 UTC
Labels: Engineering, Daily, Planning

**Comment by varshamb** [comment] 2022-10-20 02:52
This is still reproducible in staging and prod so I think this should not be closed.

## Prod Web

https://user-images.githubusercontent.com/111683206/196844431-3078abf0-10a2-4070-9aeb-f50c3525fe44.mov

### Consider my Proposal: https://github.com/Expensify/App/issues/10587#issuecomment-1228632033

cc: @neil-marcellini @zanyrenney

**Comment by aneequeahmad** [comment] 2022-10-20 02:56
This is reproducible on latest staging and production 


https://user-images.githubusercontent.com/36359331/196845383-7842c480-7c71-46ca-b3de-a6f3918ca86d.mov

**Comment by neil-marcellini** [comment] 2022-10-20 16:49
Ok let me summarize the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1661437929132899) a bit. We agree that this is a bug because users should be able to start typing immediately, and users on desktop / web like to do this especially. The problem is that this page looks really bad on mobile devices with a smaller screen height, so we removed the auto focus in this issue. Here's [the issue](https://github.com/Expensify/App/issues/7675) for that.

Here's how it looks on a smaller mobile device
<img src=https://user-images.githubusercontent.com/26260477/197009534-8a22c522-de14-449c-825d-dde95acd67fc.png  width=300px>

It looks fine on iPhone 13
<img src=https://user-images.githubusercontent.com/26260477/197009333-69acc905-66d7-4c82-8aff-77bd0a01514b.png  width=300px>

The conclusion of the thread is that we need to rethink / re-design this page. Let's start that process now @Expensify/design. If we are planning to refactor this page in another issue, then we can hold this issue on it. @JmillsExpensify do you know if we already have plans to redesign the workspace invite page?

**Comment by neil-marcellini** [comment] 2022-10-20 16:57
Hahaha uh oh, no Melvin, @rushatgabhane is C+.

**Comment by JmillsExpensify** [comment] 2022-10-20 17:45
>@JmillsExpensify do you know if we already have plans to redesign the workspace invite page? 

No plans to re-imagine the workspace invite page, though come to think of it, that personal invite message should almost certainly be converted to push-to-page.

**Comment by mountiny** [comment] 2022-10-20 17:54
Here is the design issue https://github.com/Expensify/App/issues/11795

**Comment by JmillsExpensify** [comment] 2022-10-20 18:01
@rushatgabhane Answering you in the linked [main] issue.

**Comment by zanyrenney** [comment] 2022-10-31 12:52
On hold for this still: https://github.com/Expensify/App/issues/11795

**Comment by mountiny** [comment] 2022-10-31 14:38
I think we can make such on HOLD issue monthly, the linked issue wont be fixed in a week I assume.

**Comment by zanyrenney** [comment] 2022-12-02 09:42
on hold.

**Comment by zanyrenney** [comment] 2023-02-06 18:57
hold still.

**Comment by neil-marcellini** [comment] 2023-03-10 01:05
Ditto

**Comment by neil-marcellini** [comment] 2023-04-10 16:09
Holding still

**Comment by neil-marcellini** [comment] 2023-05-15 23:16
#11795 is being actively worked on, we're still holding here.

**Comment by neil-marcellini** [comment] 2023-06-16 22:28
Same update

**Comment by neil-marcellini** [comment] 2023-07-18 22:14
Still on hold, but there's progress on the issue.

**Comment by zanyrenney** [comment] 2023-09-21 10:32
Still on hold, latest is here- https://github.com/Expensify/App/issues/11795

**Comment by neil-marcellini** [comment] 2023-10-10 19:41
@zanyrenney This had already been fixed. It was brought to my attention in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1696866263933259?thread_ts=1696681734.478929&cid=C049HHMV9SM), and after testing it I can confirm it's fixed.
https://github.com/Expensify/App/assets/26260477/af4aaa50-83d4-4b24-a158-29d7b82e78e1

**Comment by zanyrenney** [comment] 2023-10-11 08:52
As per @neil-marcellini comment above, and the fix being handled elsewhere, closing this one out!

**Comment by aneequeahmad** [comment] 2023-10-11 08:55
@zanyrenney i think reporting bonus payment is yet to be paid for this issue.

**Comment by aneequeahmad** [comment] 2023-11-23 23:42
@zanyrenney any update on the payment?

**Comment by aneequeahmad** [comment] 2024-02-07 07:58
@zanyrenney Just a friendly reminder. Bug reporter payment is still pending for this issue.
