### ISSUE TITLE
LHN - LHN becomes empty after setting preference to focus mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34258] opened 2024-01-10 16:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat and go back to LHN
2. Go to settings > Preferences > change priority mode to focus
3. Go back and observe the LHN

## Expected Result:
The LHN should show one chat which was previously open

## Actual Result:
LHN becomes empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a760dd9-30a4-4a72-a279-3c4dc735ad8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2024-01-10 16:29
It looks that there is no chat to be displayed in focus mode

**Comment by bondydaa** [comment] 2024-01-10 17:00
yeah if there are no unread chats then i don't think anything should be showing up in the LHN

**Comment by bernhardoj** [comment] 2024-01-10 17:01
This only happens on an account without a concierge chat. Concierge chat should be shown by default

**Comment by situchan** [comment] 2024-01-10 17:01
what's the production behavior then?

**Comment by bondydaa** [comment] 2024-01-10 17:28
okay discussed the bug here https://expensify.slack.com/archives/C049HHMV9SM/p1704906122169579 and sounds like yes we agree this is a bug.

The LHN should should the last chat you opened if there are no other unread messages.

**Comment by bondydaa** [comment] 2024-01-10 17:33
I can confirm on web v1.4.24-0 doesn't do this and properly shows the last chat in opened in the LHN so seems like it might be something specific to mobile code.

**Comment by bondydaa** [comment] 2024-01-10 18:24
We've opened an internal fire room b/c others are reporting similar-ish behavior here even on `1.4.23-2` (desktop) where chats in the LHN are disappearing. Not even just in #focus mode either.

**Comment by bondydaa** [comment] 2024-01-10 19:58
There is a good chance this is fixed by a back end revert that we are going to deploy shortly.

Once the deploy is done, I'll bump the issue and see about having it re-tested to confirm.

**Comment by bondydaa** [comment] 2024-01-10 20:48
@lanitochka17 can you retest this again and see if it's still reproducible? the backend deploy has finished and so it should be fixed 🙏

**Comment by thienlnam** [comment] 2024-01-11 04:46
I am unable to reproduce on staging!

**Closed by thienlnam** 2024-01-11 04:46 UTC
Labels: DeployBlockerCash, Engineering, Hourly
