### ISSUE TITLE
New Chat - "Recents" contacts are NOT correctly ordered by the latest messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13072] opened 2022-11-27 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with any account which have a lot of contacts
3. Go to New Chat or New Group
4. Verify there are 5 conversations displayed in "Recents" and that they are correctly ordered by the latest message

## Expected Result:
Contacts should be correctly ordered by the latest messages in the "Recent" section

## Actual Result:
"Recents" contacts are NOT correctly ordered by the latest messages

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Desktop App
- Mobile Web

**Version Number:** 1.2.32.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (2)](https://user-images.githubusercontent.com/93399543/204156224-6c5ba989-b376-4f67-b83b-0e9637801606.png)

https://user-images.githubusercontent.com/93399543/204156226-0712533d-ca38-44c0-9d4b-e3b0f802ae98.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2022-11-27 19:55
Unable to reproduce from my side

**Comment by mountiny** [comment] 2022-11-28 09:18
I also cannot reproduce after a fresh sign in in production or in staging 🤷  
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/36083550/204239739-b417c713-21b3-44a9-a474-a5616f84a373.png">

**Comment by mvtglobally** [comment] 2022-11-28 17:08
asking team to double check

**Comment by luacmartins** [comment] 2022-11-28 17:34
@mvtglobally were you able to reproduce the issue?

**Comment by mvtglobally** [comment] 2022-11-28 17:45
@luacmartins Team is still able to repro with High traffic account 


https://user-images.githubusercontent.com/43995119/204345595-dbadf895-cbd8-4610-b63f-51b06bc033f2.mp4

**Comment by mountiny** [comment] 2022-11-28 17:53
This would have to be related to [this PR](https://github.com/Expensify/App/pull/12761), however, with the migration there, I am not sure if reverting would be best option. 

Given the nature of this bug and the fact the PR is part of a broader initiative to fix way worse issue, I would vote for treating this as Bug but not as a deploy blocker

**Comment by luacmartins** [comment] 2022-11-28 19:28
Fix [here](https://github.com/Expensify/App/pull/13093)

**Comment by luacmartins** [comment] 2022-11-28 20:10
Closing this issue since the PR was merged!

**Closed by luacmartins** 2022-11-28 20:10 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
