### ISSUE TITLE
[$500] Request Money – Edited fields are not saved grayed out on the distance report page Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32511] opened 2023-12-05 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to a distance request details conversation or create it
4. Disable the internet connection
5. On the distance report page select the Amount, Description or Date fields
6. Edit some of the fields
7. Select save

## Expected Result:
Edited fields are grayed out on the distance report page Offline

## Actual Result:
Edited fields are not saved grayed out on the distance report page Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ac5a1cc2-b4c4-4231-b25e-5ff5869def87

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181753718dd096504</li>
        <li>Upwork Job ID: 1732115829983993856</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28033443</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-05 19:23
This is a regression from https://github.com/Expensify/App/issues/30290
As opposed to [my proposal](https://github.com/Expensify/App/issues/30290#issuecomment-1777934203) of recalculating the modified waypoints, it was decided to just use the `SET` operation for updating the transaction.
This now results in overwriting the pending fields with only the ones from the last offline modification.

**Comment by paultsimura** [comment] 2023-12-06 08:04
> I don't think this is a regression from #30290. Using the SET method is correct to update transactions

It is a correct method, otherwise, it wouldn't have been approved by the C+ in the first place.
However, it doesn't change the fact that this issue is caused by the linked PR, which technically means this is a regression, and the linked issue is still in the regression period, which means the author would have to fix it as a follow-up.

**Comment by mountiny** [comment] 2023-12-11 12:02
@situchan please proceed with the proposal review

**Comment by situchan** [comment] 2023-12-12 16:14
reviewing proposals

**Comment by paultsimura** [comment] 2023-12-13 07:46
Just in case, I updated the original comment with more details of why this is a regression: https://github.com/Expensify/App/issues/32511#issuecomment-1841477842

**Comment by situchan** [comment] 2023-12-18 03:19
The [PR](https://github.com/Expensify/App/pull/31340) fixing https://github.com/Expensify/App/issues/30290 was reverted.

**Comment by paultsimura** [comment] 2023-12-18 10:53
After the revert, this issue is not reproducible anymore.
@situchan should we handle the proper fix of https://github.com/Expensify/App/issues/30290 here as suggested in https://github.com/Expensify/App/issues/33098#issuecomment-1858086997?

**Comment by situchan** [comment] 2023-12-18 10:57
I am not sure which GH is the best to handle. Maybe https://github.com/Expensify/App/issues/30290 which is original?

**Comment by situchan** [comment] 2023-12-18 10:57
@mountiny what do you think?

**Comment by mountiny** [comment] 2023-12-18 14:30
@situchan sorry just to make sure I understand, the og issue here is fixed but there is another issue which is not logged? if we had to revert some PR then I think the changes should be handled in the issue the reverted PR was linked to

**Comment by situchan** [comment] 2023-12-18 14:39
This issue is regression and the offending PR is reverted so not reproducible anymore.
I think we can close this

**Comment by mountiny** [comment] 2023-12-18 15:18
I see ok I think that if this is the case we should just close this issue which is not reproducible and just make sure that whenever the next attempt on fixing the original issue will be done, we need to test for this bug.

But I dont think we should keep this open especially since its not repro

**Closed by mountiny** 2023-12-18 15:18 UTC
Labels: External, Daily, Help Wanted, Bug
