### ISSUE TITLE
Thread - "Report no longer exists" when sending message in thread as invited user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39333] opened 2024-03-31 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat with two users
4. Send a message in group chat
5. Right click on message > Reply in thread
6. Invite another user to the thread via mention
7. As the invited user, navigate to the thread
8. Send a message to the thread
9. Dismiss the error
10. Refresh the thread as group creator and invited thread member

## Expected Result:
In Step 8, the invited member should be able to send a message to thread without error

## Actual Result:
In Step 8, "Report no longer exists" when sending message in thread as invited user when the thread comes from a group chat.
After refreshing the page, the message is sent and appears for both group creator and invited member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83e3cf64-6400-44f4-92e2-9f3b1d077bad

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2024-04-01 15:36
I verified I can reproduce in staging. Here are logs for the AddComment request with the error: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2286d99c70b9678f9f-BOS%22)+AND+timestamp:[2024-04-01T14:28:51.871Z+TO+2024-04-01T16:28:51.871Z]&index=logs_expensify-027594

Since it's related to Group Chats, going to hand it off to @marcaaron 🙇

**Comment by marcaaron** [comment] 2024-04-01 17:37
>Invite another user to the thread via mention

🤔 this is not really supported yet

**Comment by marcaaron** [comment] 2024-04-01 17:41
Or maybe it should be?! I tried to do this on a DM and it worked 🤔

**Comment by marcaaron** [comment] 2024-04-01 17:49
>Reproducible in production?: N

This is not really true. I tried to leave a comment on a thread in a DM and it does not work on production.

**Comment by marcaaron** [comment] 2024-04-01 17:49
Gonna stay assigned for now but this feels more `New Feature` than `Bug` to me.

**Comment by marcaaron** [comment] 2024-04-01 21:35
More context about why the Deploy Blocker label was removed can be found [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1712005980413999).

**Comment by marcaaron** [comment] 2024-04-02 22:58
Ok, so based on that thread the expected behavior for this is gonna be:

- People should be able to invite other people to DM or Group Chat threads.
- If that happens we should treat this the same way as we do a “private” workspace room. Namely, the invited member can only see the parent report action and only the ancestry of threads that they are a member of.
- They should be able to invite other people to these threads freely regardless of membership in the top level chat.

I'm going to close this out and create an Expensify/Expensify issue since this will require some backend changes.

**Closed by marcaaron** 2024-04-02 22:58 UTC
Labels: Engineering, Daily, Planning

**Comment by marcaaron** [comment] 2024-04-02 23:03
Moved to https://github.com/Expensify/Expensify/issues/384761
