### ISSUE TITLE
[$2000] Not able to react with emojis in new split money report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19495] opened 2023-05-23 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. Click on + icon and click on `Split bill`
3. Enter any amount, ie. $55  
4. Select any user then click the `Next` button at the box at the bottom
5. Click the `Split` box at the bottom on the next screen.
6. Click on the money report (box) and it navigates you to a new page with header split money
7. Now try to react with emojis on the report and notice that nothing happens

## Expected Result:
Should be able to react with emojis in new split money report
## Actual Result:
Not able to react with emojis in new split money report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/273e1bf6-5660-46bd-81b8-96d9ae9bb849

https://github.com/Expensify/App/assets/43996225/d820c115-ec1b-4555-80d2-25c5fff69e49

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684666768039049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01349d3928ce6c274d</li>
        <li>Upwork Job ID: 1664749442102345728</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by VitaliiP-0205** [comment] 2023-05-24 04:42
I could not reproduce this issue. I am able to react with emojis in new split money report.
Is this really bug?

**Comment by VitaliiP-0205** [comment] 2023-05-24 05:14
Reproduced this issue.

**Comment by priya-zha** [comment] 2023-05-24 07:50
If you refresh the page, the emoji appears. But from a user perspective, IMO no user is going to refresh the page or move to another tab and come back again. A user should be able to see the emoji instantly in a similar way how it behaves in a normal chat. The problem is only with the split money report in a new split money page where emoji doesn't appear instantly.

**Comment by mallenexpensify** [comment] 2023-05-25 02:23
Checking [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684981268475359?thread_ts=1684666768.039049&cid=C049HHMV9SM)
> I've seen multiple emoji-related bug reports the past week, are we collecting these somewhere or fixing them individually?

**Comment by mallenexpensify** [comment] 2023-05-31 02:39
Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684982151682259?thread_ts=1684666768.039049&cid=C049HHMV9SM)
> Fixing individually. It seems to me like the switch to threads is making us not return the proper data, so there is a good chance that a backend fix will be required

@cristipaval , I'm guessing this can be external, do you agree?

**Comment by mallenexpensify** [comment] 2023-06-02 21:43
🤞 it can be `External` :|
Seems like it

**Comment by mallenexpensify** [comment] 2023-06-06 01:51
Doubled price as we're ~2 weeks old, hopefully that'll help draw in propsals

**Comment by cubuspl42** [comment] 2023-06-07 14:59
But also here:

> 1. Go to staging dot on web chrome

It's repeated twice that this affects staging. Has anything changed? Was it reverted from staging maybe?

**Comment by cubuspl42** [comment] 2023-06-07 15:02
I just repeated the steps on the tip of the `main` branch and my results are the same as I presented in the video.

**Comment by mallenexpensify** [comment] 2023-06-09 18:58
Closing this as the functionality appears to have changed. When you click the 'split box'
<img width="422" alt="image" src="https://github.com/Expensify/App/assets/22508304/963557d6-c75f-4e52-a95f-9ae629488f65">

it doesn't open a new report, it opens a popup modal. 

https://github.com/Expensify/App/assets/22508304/9c06ffe8-6991-494e-a2f0-f72964fc7a48

And there's no way (nor need) at action with emoji there. 

Please comment if I'm missing something

**Closed by mallenexpensify** 2023-06-09 18:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
