### ISSUE TITLE
[HOLD for payment 2023-08-08] Split bill - App crashed when delete split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23824] opened 2023-07-28 20:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Create split bill
3. Long press on request
4. Tap on 'Delete request"

## Expected Result:
The request should be delete.

## Actual Result:
App crashed when delete split bill.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/10872bea-2bd9-40ca-b653-599153b94a9a

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-07-29 01:10
Seems related -> https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/e8357e4aff4d3d4b1bf39478a981997d?time=last-seven-days&versions=1.3.45-8%20(1001034508);1.3.46-0%20(1001034600);1.3.46-1%20(1001034601)&sessionEventKey=64C1D1B6003700015C31403A37B96EE1_1838760527596780186

**Comment by Beamanator** [comment] 2023-07-31 10:31
May be related to: https://github.com/Expensify/Expensify/issues/304096

**Comment by mountiny** [comment] 2023-07-31 11:02
cc @luacmartins I am not sure if we have tested this flow well

**Comment by Beamanator** [comment] 2023-07-31 11:05
I'm seeing this in web when I try to delete a split:

<img width="845" alt="Screenshot 2023-07-31 at 2 05 00 PM" src="https://github.com/Expensify/App/assets/3885503/9f34445f-e84c-4874-b72b-9bb553d455e9">

**Comment by Beamanator** [comment] 2023-07-31 11:05
@mountiny can you find the PR that may have caused this?

**Comment by mountiny** [comment] 2023-07-31 11:07
https://github.com/Expensify/App/pull/19095 

I dont think we should revert though, I think we should just disable the option on split action before we figure this out

**Comment by Beamanator** [comment] 2023-07-31 11:07
Ok can you take over finding a good solution for this one? 🙏

**Comment by Beamanator** [comment] 2023-07-31 11:39
Idk why melvin thought this should be weekly lol

**Comment by situchan** [comment] 2023-07-31 11:40
https://github.com/Expensify/App/blob/8cdb506e97e8382f4bc55b0f48784f576fbb2789/src/libs/actions/IOU.js#L775
The crash happens on this line because `originalMessage.IOUReportID` doesn't exist in split report action
Based on https://github.com/Expensify/App/pull/19095/files#diff-16a590a45460a9abf1e402441b50e3cb2659ee3da203ca30a2fa4ce3f9411957L253-R253, I think the issue existed before https://github.com/Expensify/App/pull/19095. And enabling delete money request feature just revealed this.

**Comment by mountiny** [comment] 2023-07-31 11:49
correct, I think we just forgot about this case.

**Comment by mountiny** [comment] 2023-07-31 11:50
@Beamanator thats an automation for when PR is raised and marked as ready for a review.

**Comment by Beamanator** [comment] 2023-07-31 12:00
Thanks @mountiny :D

So do we think this can be easily "fixed"? Or should we just disabled deleting splits for now

**Comment by mountiny** [comment] 2023-07-31 13:12
disabled for now, I am not sure the auth command is build for this

**Comment by Beamanator** [comment] 2023-07-31 16:26
Perfecto - PR merged, CPing to staging

**Comment by Beamanator** [comment] 2023-07-31 17:08
Confirmed working in web & iOS staging - marking not a blocker!

Also assigning `Bug` to get C+ paid!

**Comment by mountiny** [comment] 2023-08-01 12:05
$1000 to @Ollyws for internal review

**Comment by mountiny** [comment] 2023-08-06 18:23
$1000 for @Ollyws for internal review.

**Comment by greg-schroeder** [comment] 2023-08-08 05:29
Offer sent to @Ollyws

**Comment by greg-schroeder** [comment] 2023-08-08 05:30
Don't think the checklist will be super necessary here personally. Going to close this now that offer is sent! will pay as soon as accepted

**Closed by greg-schroeder** 2023-08-08 05:30 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by greg-schroeder** [comment] 2023-08-15 17:34
Oh, wow, sorry, sending now @Ollyws

**Comment by tranvantoan-qn** [comment] 2023-08-17 13:05
@mountiny I apologize for bringing up this matter once more.

Did we solely disable the "Delete" option on the main Request?

I'm still experiencing the same crash, albeit in a slightly different manner.

Whenever a split request is initiated, it also generates a sub-report for each participant, allowing me to delete each request. Unfortunately, this leads to a crash when in Offline mode.

```
TypeError: Cannot read properties of null (reading 'reportID')
    at main-426150f61736a9bd57d7.bundle.js:1:3040782
    at vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:16283362
    at Xt (vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:16282859)
    at Function.qt (vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:16283340)
    at Object.P (main-426150f61736a9bd57d7.bundle.js:1:3040751)
    at Object.m (main-426150f61736a9bd57d7.bundle.js:1:1269288)
    at jn (main-426150f61736a9bd57d7.bundle.js:1:1470777)
    at fA (vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:9865482)
    at Bs (vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:9922584)
    at bl (vendors-3db7fcdc0b1c4dcfe55f.bundle.js:1:9911745)
```
