### ISSUE TITLE
Workspace-App crashes on back navigation from new workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52875] opened 2024-11-21 10:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+tw5535353533@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign up for a new account and Click on the FAB button.
2. Use the FAB button to Create a new workspace.
3. Navigate back by first clicking the website's back button, followed by the browser's back button.

## Expected Result:
The app should function normally without crashing.

## Actual Result:
The app crashes after navigating back as described.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/34bee8b1-f82b-45b5-afc0-a5453e3f517d

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2024-11-21 13:56
Checking!

**Comment by youssef-lr** [comment] 2024-11-21 19:17
I can't reproduce, I think this error happened because the app failed to fully load. You can see in the recording that Concierge chat was failing to load.

**Comment by isabelastisser** [comment] 2024-11-22 17:47
Closing!

**Closed by isabelastisser** 2024-11-22 17:47 UTC
Labels: Engineering, Daily, Bug
