### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Expensify card - Card limit is auto-set to specific amount after edit

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50686] opened 2024-10-12 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3272217
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: expensifail account with workspace. Expensify card feature is enabled. VBA added.

1. Go to Workspace > Expensify card
2. Click '+ Issue card'
3. Set a limit to > 22,222,222 (e.g. 99,999,999)
4. Save the card
5. Open added card > Card limit
6. Click save without changing anything

## Expected Result:
Card limit stays the same as on step 3

## Actual Result:
Card limit is auto-set to 21,474,836.47

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/31c9c9ca-2e4f-4bf1-88df-b70f9270d4f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846167119339260206</li>
        <li>Upwork Job ID: 1846167119339260206</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 104453418</li>
<li>nkdengineer | Contributor | 104453422</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-10-12 18:20
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment] 2024-10-12 18:20
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-12 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Card limit is auto-set to 21,474,836.47

### What is the root cause of that problem?

The number `2,147,483,647` is the maximum positive value for a 32-bit signed binary integer, and we use this as limit with API `UpdateExpensifyCardLimit`  and it doesn't happen with the API `CreateExpensifyCard`

### What changes do you think we should make in order to solve the problem?


we should add a limit on the front end with a value less than `21,474,836.47` to be consistent with the back end in both edit and create case

Simply we can add props `amountMaxLength` to this [InputWrapper](https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx#L128-L134)

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx#L128-L134

Or we can add the new validation for this input to set max value [here](https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx#L94) and will throw error when it exceeds the limit

### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2024-11-04 16:02
@nkdengineer or @mkhutornyi Can you please see about filling out that checklist? I think it was a small bug that it pinged me. I'll have to keep an eye on it.

**Comment by tgolen** [comment] 2024-11-08 16:19
bump @nkdengineer @mkhutornyi

**Comment by sonialiap** [comment] 2024-11-11 21:04
Payment summary:
- @mkhutornyi please complete the [checklist](https://github.com/Expensify/App/issues/50686#issuecomment-2454845931). $250 via upwork upon completion of the checklist 
- @nkdengineer $250 paid via upwork ✔️

**Comment by sonialiap** [comment] 2024-11-19 11:59
@mkhutornyi bumping for the checklist https://github.com/Expensify/App/issues/50686#issuecomment-2454845931

**Comment by sonialiap** [comment] 2024-11-22 11:46
@mkhutornyi bumping for the checklist https://github.com/Expensify/App/issues/50686#issuecomment-2454845931

**Comment by sonialiap** [comment] 2024-11-22 11:47
@mkhutornyi bumping for the checklist https://github.com/Expensify/App/issues/50686#issuecomment-2454845931. Payment will be released once the checklist is completed

**Comment by sonialiap** [comment] 2024-11-25 12:24
[From this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1730324940828559) looks like @mkhutornyi is OOO indefinitely. I'm releasing payment

@nkdengineer could you help with the [checklist](https://github.com/Expensify/App/issues/50686#issuecomment-2454845931) for this one so that we can close it out?

**Comment by sonialiap** [comment] 2024-11-26 13:01
boop for melvin

**Comment by sonialiap** [comment] 2024-12-11 09:04
@nkdengineer could you help with the [checklist](https://github.com/Expensify/App/issues/50686#issuecomment-2454845931) for this issue?

**Comment by sonialiap** [comment] 2024-12-13 10:52
Thank you @nkdengineer !

**Closed by sonialiap** 2024-12-13 10:52 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by sonialiap** [comment] 2024-12-23 14:23
@nkdengineer would you be able to help with the https://github.com/Expensify/App/issues/50686#issuecomment-2454845931 for this issue so that we can close it out?
