### ISSUE TITLE
Please create regression test for #41762

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#44071] opened 2024-06-20 11:21 UTC
**Regression Test Proposal**
Open the app and press the FAB -> Split expense.
Enter the amount and select a few users.
Double tap on the amount to highlight it.
Enter one digit.
Verify that the cursor appears after the first digit.

https://github.com/Expensify/App/issues/41762

**Comment by isagoico** [comment] 2024-06-25 15:56
Going to treat this one as an edge case since I think this is a specific flow to reproduce the problem. I'll add this to our issue [list](https://docs.google.com/spreadsheets/d/1VTQKn9t9xNMbrhD46OIf3fJGmpH4Gmi42jXjQgmtBoY/edit#gid=0) that will be tested on a monthly basis.

For more context on edge cases, please check this [thread](https://expensify.slack.com/archives/C9YU7BX5M/p1682431765823119).
Closing the issue - please reopen if needed.

**Closed by isagoico** 2024-06-25 15:56 UTC
Labels: Weekly
