### ISSUE TITLE
[$250] Accounting tab appears then disappears after selecting an integration during onboarding

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50637] opened 2024-10-11 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sdjsdudsiuhi@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up with a new Gmail account
3. Select Manage my team's expenses on onboarding modal
4. Select employee amount > Next
5. Choose any integration > Next
6. Complete the onborading
7. Go to workspace settings

## Expected Result:
Accounting tab will not appear and disappear

## Actual Result:
Accounting tab appears then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ffcd907c-b369-4e3e-8b96-e855e540cf9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844716640793633414</li>
        <li>Upwork Job ID: 1844716640793633414</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by nkuoch** [comment] 2024-10-11 12:27
I don't think this needs to be a blocker, so removing the labels, but yes let's find someone to work on it!

**Comment by NJ-2020** [comment] 2024-10-11 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Accounting tab appears then disappears after selecting an integration during onboarding
### What is the root cause of that problem?
Right here when we complete the onboarding we set the `areConnectionsEnabled` to true:
https://github.com/Expensify/App/blob/abdfb7233e040a61d1e4433e202a8b644c7455f4/src/libs/actions/Report.ts#L3647-L3677
### What changes do you think we should make in order to solve the problem?
We should remove this code
https://github.com/Expensify/App/blob/abdfb7233e040a61d1e4433e202a8b644c7455f4/src/libs/actions/Report.ts#L3647-L3677

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-10-11 19:19
Oh we forgot to send the policy id cc @nkdengineer. Please raise a PR for this since it's a regression

@marcaaron regarding https://github.com/Expensify/App/pull/49161#discussion_r1765675105, what's the param that we should use to send the policy id over?

**Comment by s77rt** [comment] 2024-10-11 19:19
@allroundexperts I'd like to handle this being a "regression" from https://github.com/Expensify/App/pull/49161

**Comment by nkdengineer** [comment] 2024-10-11 19:23
> @marcaaron regarding https://github.com/Expensify/App/pull/49161#discussion_r1765675105, what's the param that we should use to send the policy id over?

@s77rt I will raise the PR when we confirm this. Or we can do this in the second PR of the new feature when the task translation is confirmed.

**Comment by marcaaron** [comment] 2024-10-11 19:49
Should be `policyID`.

**Comment by marcaaron** [comment] 2024-10-11 19:49
>Or we can do this in the second PR of the new feature when the task translation is confirmed.

That sounds fine to me!

**Comment by marcaaron** [comment] 2024-10-11 19:50
@nkuoch I will take this over as it's related to something I missed when working with these guys.

**Comment by marcaaron** [comment] 2024-10-11 20:31
Hey @twilight294 I'd suggest bringing that up in Slack or shooting an email over to `contributors@expensify.com`. Typically, when something is a regression it's the responsibility of the person who implemented the PR. I appreciate the help and can provide [this document](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions) to you review. And will also say that there are always exceptions. But I can't personally provide any guarantees right now.

**Comment by s77rt** [comment] 2024-10-14 15:40
Not overdue. Will be fixed in next PR

**Comment by s77rt** [comment] 2024-10-17 15:32
@nkdengineer is working on it. It should be part of a PR related to https://github.com/Expensify/App/issues/48745

**Comment by s77rt** [comment] 2024-10-22 18:26
Being fixed in https://github.com/Expensify/App/pull/51070

**Comment by s77rt** [comment] 2024-11-04 18:22
This is fixed now. Can be closed

**Closed** 2024-11-04 19:23 UTC
Labels: Reviewing, External, Engineering, Daily
