### ISSUE TITLE
[HOLD for payment 2024-07-25] [$500] Web - Expense - Blue border selection on back icon RHP after hitting enter on BNP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43662] opened 2024-06-13 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Go to + > Submit expense > Manual
4. Enter amount
5. Hit Enter

## Expected Result:
The back icon on RHP will not have blue border selection

## Actual Result:
The back icon on RHP has blue border selection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cd5b4495-0c04-40dd-bac9-1c8018391d49

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018358d1ec7f51e120</li>
        <li>Upwork Job ID: 1801251133562170195</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 102988636</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-06-13 13:48
@danieldoglas  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-13 13:48
We think that this bug might be related to #vip-vsp

**Comment by danieldoglas** [comment] 2024-06-13 13:50
Not a deploy blocker related to web, removing the label

**Comment by gawandeabhishek** [comment] 2024-06-13 16:11
To address this issue, we can use the .that-element:focus { outline: none; } CSS class. This rule removes the default focus outline that appears on elements when they are focused. This can enhance the visual appearance and usability of the element, especially in cases where the default browser outline is intrusive or unnecessary.

**Comment by tsa321** [comment] 2024-06-14 01:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Expense - Blue border selection on back icon RHP after hitting enter on BNP

### What is the root cause of that problem?

The `Money_Request_Step_Participants` screen isn't included in 

https://github.com/Expensify/App/blob/2a641d98760dfdc1a2ebe9b958787c9cfacb02c2/src/components/FocusTrap/SCREENS_WITH_AUTOFOCUS.ts#L4

which will make focusTrap to focus the first element of the screen:

https://github.com/Expensify/App/blob/2a641d98760dfdc1a2ebe9b958787c9cfacb02c2/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L52-L55

### What changes do you think we should make in order to solve the problem?

include `SCREENS.MONEY_REQUEST.STEP_PARTICIPANTS` in `SCREENS_WITH_AUTOFOCUS`. 
And if we need to disable the auto focus on all money request screen we can use `...    ...Object.values(SCREENS.MONEY_REQUEST)`

**Comment by s77rt** [comment] 2024-06-14 02:30
@gawandeabhishek Please checkout the contributing guide https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by s77rt** [comment] 2024-06-14 02:44
@tsa321 Thanks for the proposal. Your RCA is correct. The solution works but I assume this bug exists in many places and we will face it again when a new screen is added. Can we explore a global solution here that will also prevent this bug from occurring?

**Comment by tsa321** [comment] 2024-06-14 02:59
@s77rt do we need to set the auto focus from `FocusTrap`? How about disable the initialFocus of FocusTrap. 
We return false in `initialFocus` for all screens.

**Comment by s77rt** [comment] 2024-06-14 17:25
@tsa321 This will keep the element outside of the focus trap still focused e.g. in the report screen we can even use the arrow keys.


https://github.com/Expensify/App/assets/16493223/621eea65-99cd-43ed-ba45-c8c46994b664

**Comment by tsa321** [comment] 2024-06-15 02:38
@s77rt To fix the issue, I have tried to blur the the active element by adding onActivate property into FocusTrap. The callback will be executed before focustrap is activated. The callback is  `() => document.activeElement.blur();`. but this doesn't work.  
The code that work for me is to move the focus to other element that doesn't receive keydown event:
```javascript
onActivate: () => document.querySelector('[tabindex="0"]').focus()
```
This could fix that issue.

**Comment by s77rt** [comment] 2024-06-15 15:17
@tsa321 After opening the RHP there should be focus ring on the RHP first element


https://github.com/Expensify/App/assets/16493223/2b10f449-86ba-4863-a10d-c124f38e198c

**Comment by tsa321** [comment] 2024-06-18 13:57
@s77rt I can defer the blue outline appearance, so we can remove the `initialFocus` property.
in `FocusTrapForScreen`, we set a ref to the children with:
`const screenRef = useRef(null);`
 then add screenRef in children:
 `const childElement = React.cloneElement(children, {ref: screenRef});`

then set `onActivate` with:
```javascript
onActivate: () => {
    const firstTabElement = screenRef?.current?.querySelector('[tabindex="0"]');
    if (firstTabElement) {
        const elementBoxShadow = firstTabElement.style.boxShadow;
        firstTabElement.style.boxShadow = "none";
        setTimeout(() => {
            firstTabElement.style.boxShadow = elementBoxShadow;
        }, 1000);
    }
},
```
then change the returned children with childElement

**Comment by s77rt** [comment] 2024-06-18 21:32
@tsa321 This is looking too workaround-ish. So far it may be best to either disable initial focus or enable it for all (as long as we get rid of the `SCREENS_WITH_AUTOFOCUS` list). But for now let's see if we can find other solutions

**Comment by danieldoglas** [comment] 2024-06-27 10:52
Raising the proposal value so we can get more proposals.

**Comment by s77rt** [comment] 2024-06-27 22:14
Still looking for proposals

**Comment by s77rt** [comment] 2024-06-29 20:41
@suneox The blue border issue could occur in many cases. Can you look into a global solution? (a solution that fixes the problem for all screens) so we can remove and avoid maintaining the `SCREENS_WITH_AUTOFOCUS` list.

**Comment by s77rt** [comment] 2024-06-30 15:21
@suneox Instead of looking for inputs with attributes. Can we:
1. Get the active focused element
2. If that element is within the focus trap container, skip the focus trap auto focus

**Comment by s77rt** [comment] 2024-07-01 10:22
@suneox We are almost there. But let's do the following:
1. Instead of adding a new config option let's just use `initialFocus` and pass the containers (`state.containers`)
2. We need to delay the focus to account for the screen transition and the auto focus delay (300ms). For that we already have a config option `delayInitialFocus` but we need to add a new option to specify the delay duration.

Please update your proposal accordingly

**Comment by s77rt** [comment] 2024-07-01 20:09
@suneox Overall looks good to me but do we need the `buttonHasEnterListener` check?

**Comment by s77rt** [comment] 2024-07-02 10:00
@suneox I don't see the problem here. If you navigate to a page via keyboard the first element should be focused (for easy keyboard accessibility). The only time we avoid this is if we already have a focused element.

**Comment by s77rt** [comment] 2024-07-02 11:05
@suneox For this one can we just make the button focused?

**Comment by s77rt** [comment] 2024-07-02 16:26
@suneox Sounds good

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/43662#issuecomment-2198089476)

**Comment by danieldoglas** [comment] 2024-07-04 14:00
assigned @suneox

**Comment by s77rt** [comment] 2024-07-05 21:42
Not overdue. Waiting on the PR

**Comment by joekaufmanexpensify** [comment] 2024-07-25 20:31
All set to issue payment. We need to pay: 

- @suneox - $500 for PR via Upwork. 
- @s77rt - $500 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-07-25 20:32
@suneox $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-07-25 20:32
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-07-25 20:33
All that's left is for @s77rt to request their $500 via NewDot. Going to close this one since it's otherwise all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-07-25 20:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by s77rt** [comment] 2024-07-26 01:03
@joekaufmanexpensify This should be $250 for causing a regression https://github.com/Expensify/App/issues/45571

**Comment by JmillsExpensify** [comment] 2024-07-26 02:13
@joekaufmanexpensify mind updating the payment summary above?

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:26
Ah okay got it. I don't see that there was a post to the issue about the deploy blocker/regression previously, which is why it was not previously noted in the payment summary. 

Updated [payment summary](https://github.com/Expensify/App/issues/43662#issuecomment-2251344641) to note that both parties are actually due $250 here because of the regression.

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:29
I need to request a $250 refund from @suneox via Upwork. Getting an insufficient permissions error in upwork requesting a refund. Updating my permissions via [this SO](https://stackoverflowteams.com/c/expensify/questions/14940) to allow processing refunds.

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:40
All good!I haven't requested it yet. Will let you know once I do!

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:49
Ah, perfect. TY! I see it processed on my end.

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:50
Okay, now all that's left is to process $250 payment to @s77rt. Payment summary [here](https://github.com/Expensify/App/issues/43662#issuecomment-2251344641).

**Comment by JmillsExpensify** [comment] 2024-07-26 17:11
$250 approved for @s77rt
