### ISSUE TITLE
[$500] Web - LHN - New workspace option disappear for few seconds when switching from offline to online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20198] opened 2023-06-05 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. delete All workspace if already created
2. Click on + icon to open options
3. Go to offline
4. Go back to online

## Expected Result:

Anytime there are no workspaces stored in Onyx, let's show the `New Workspace` option, it doesn't matter if the user is online or offline. So we need to change the check we're executing to consult Onyx instead of checking if you're online or syncing.

Also, if we remove the option, we need to adjust the popup height.

## Actual Result:
New workspace option disappear for few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/35287241-87e5-48c9-bcfe-066f6fa7888b

https://github.com/Expensify/App/assets/93399543/9ce1c7d3-6435-4ccb-8d92-92869b8aca64

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan
 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685777468247679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b47074fb0087cc4a</li>
        <li>Upwork Job ID: 1666545539781529600</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-06-07 20:40
Added the external label.

**Comment by danieldoglas** [comment] 2023-06-07 20:44
@flaviadefaria as @bernhardoj mentioned above, this is an expected behavior - cc @roryabraham 

Maybe we should work in a better way to do that instead of just making it disappear? We might need to discuss what to do here before receiving proposals

**Comment by flaviadefaria** [comment] 2023-06-07 20:56
Ah, @bernhardoj's comment was clear to me. Sounds good! Should I or you start this discussion or should we wait for @roryabraham to chime in?

**Comment by danieldoglas** [comment] 2023-06-07 21:22
I think we can start the discussion @flaviadefaria!

**Comment by Thierry378** [comment] 2023-06-07 23:13
I think that error appears because of FOUC or Synchronize.
Could you give a change that I can discuss more?

**Comment by Thierry378** [comment] 2023-06-07 23:38
Contributor details
Your Expensify account email: <buithierry378@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/thierrybui>

**Comment by Thierry378** [comment] 2023-06-07 23:47
Contributor details
Your Expensify account email: [buithierry378@gmail.com](mailto:buithierry378@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~019a5f96bc6c6391b9

**Comment by Thierry378** [comment] 2023-06-07 23:48
Contributor details
Your Expensify account email: <buithierry378@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~019a5f96bc6c6391b9>

**Comment by Thierry378** [comment] 2023-06-08 00:03
Contributor details
Your Expensify account email: buithierry378@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019a5f96bc6c6391b9

**Comment by Thierry378** [comment] 2023-06-08 15:23
Hello dear.
Thank you for your email.
I tried to login to this slack channel.
But I cannot login. I don't know the reason.
The error message says that my email was not invited yet.
Could you check the invitation status again please?
Best regards.

**Comment by danieldoglas** [comment] 2023-06-12 20:41
Still in discussion

**Comment by Thierry378** [comment] 2023-06-12 20:43
hi

**Comment by danieldoglas** [comment] 2023-06-16 12:35
After internal discussion, it was decided to lower the bounty for this issue. Expected behavior was updated, so adding `Help Wanted` again.

**Comment by danieldoglas** [comment] 2023-06-16 12:36
Also, following the new guideline, I'm removing myself from this issue. When it's a proposal is accepted, please add the comment to assign a new engineer.

**Comment by Thierry378** [comment] 2023-06-16 12:41
I agree your budget.
how can I contribute my effort in your project?
please let me know.
As full-stack developer, I have rich experience with git and any language.
I hope we will contact soon.

**Comment by flaviadefaria** [comment] 2023-06-16 13:12
@Thierry378 if you have any issues please send an email or ask in the Slack channels only a post to this GH if you have a proposal.

**Comment by flaviadefaria** [comment] 2023-06-19 11:48
@eVoloshchak any good proposals so far?

**Comment by flaviadefaria** [comment] 2023-06-21 11:45
@eVoloshchak any thoughts on the proposal/comments above?

**Comment by eVoloshchak** [comment] 2023-06-21 12:15
Reviewing proposals today

**Comment by eVoloshchak** [comment] 2023-06-21 20:12
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/20198#issuecomment-1578122015) resolves the first half of the issue, we indeed just need to remove `this.props.isLoading `check
However, both proposals aren't addressing the following requirement:
> if we add/remove the option, we need to adjust the popup height



https://github.com/Expensify/App/assets/9059945/480bda1d-da16-438d-8495-7edc6464780c

**Comment by flaviadefaria** [comment] 2023-06-23 20:41
It seems like we're still waiting for a proposal that solves all issues.

**Comment by flaviadefaria** [comment] 2023-06-26 12:30
@eVoloshchak what are your thoughts on the proposal above?

**Comment by flaviadefaria** [comment] 2023-06-27 11:06
@eVoloshchak given how old this issue is can you help prioritize it? I appreciate your help here!

**Comment by flaviadefaria** [comment] 2023-06-28 15:42
Cool re-adding the engineering label.

**Comment by Beamanator** [comment] 2023-06-29 10:49
Hmm looks like @bernhardoj referenced this issue where we agreed this isn't necessary to fix since we're planning to deprecate the "New workspace" menu item from the global create menu: https://github.com/Expensify/App/issues/16868#issuecomment-1504455432

Do we agree this is the same discussion? If so, let's close this out?

cc @JmillsExpensify @roryabraham since y'all were on the linked issue where we decided to close out this convo

**Comment by flaviadefaria** [comment] 2023-06-30 11:18
Cool I'll close this out. @JmillsExpensify @roryabraham please reopen if you disagree.

**Closed by flaviadefaria** 2023-06-30 11:18 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by Thierry378** [comment] 2023-07-18 19:27
.....................................

Thierry would like to stay in touch on LinkedIn.

Thierry bui
Trustworthy & Sincerity IT Engineer
Phuket, Thailand

View profile https://www.linkedin.com/comm/in/thierry-bui-1444a8277?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-1fvki0%7Elk8osnyj%7E5f-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BoDoFrhhESIWzESfn38kwoA%3D%3D

Confirm that you know Thierry https://www.linkedin.com/e/v2?e=1fvki0-lk8osnyj-5f&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BoDoFrhhESIWzESfn38kwoA%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=2rQ5KbED&invitationId=7087150945481994240


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=1fvki0-lk8osnyj-5f&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQEibS48mEE-JgAAAYlqeSNQ6efoysLth3Qq9CuunXmBnlG7zStHDECYhu7nmi8aFnQ9UmVzfq78cO7G_HQhhi6O2SaU1_9hD_4P625RacpEX6vW2WyUQkkvgchff9Jp7UVIKNcQHoOV45PeG_GHYnIDo3WOujhDug&eid=1fvki0-lk8osnyj-5f

Help: https://www.linkedin.com/e/v2?e=1fvki0-lk8osnyj-5f&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BoDoFrhhESIWzESfn38kwoA%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2023 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Bui378** [comment] 2023-07-25 18:48
Hi ,

Alain would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=1fvki0-lkinhf6r-j0&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BkWhz23KfQB%2BfX6nXpadcQA%3D%3D&t=suwj&ek=email_first_guest_reminder_03&li=20&m=hero&ts=accept_text

View Alain’s profile: https://www.linkedin.com/comm/in/alain-bui?trk=eml-email_first_guest_reminder_03-hero-2-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-2-prof%7Ename-null-1fvki0%7Elkinhf6r%7Ej0-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BkWhz23KfQB%2BfX6nXpadcQA%3D%3D



.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=1fvki0-lkinhf6r-j0&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=17&m=unsub&ts=unsub&loid=AQECQ7xE_HnBmwAAAYmOYecASp0sJKwGKgJWlLOjnC6WtHxUItunMJMXw2WvWNFQyLhUvT4KbKDlzdh82w9CXGN9Rjvf5JWlv9-hacl0khGgvSQa2dcRNTGrEh_RjIW0eqKZ2-6-FZRUhr0Ia_ai3WkOG71rlQyEc2emmw&eid=1fvki0-lkinhf6r-j0

Help: https://www.linkedin.com/e/v2?e=1fvki0-lkinhf6r-j0&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3BkWhz23KfQB%2BfX6nXpadcQA%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=16&m=footer&ts=help&articleId=67


 LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2023 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
