### ISSUE TITLE
Web - Task - The message entry field in a task disappears when the focus is removed from the tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23675] opened 2023-07-26 18:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Navigate to a Group Chat
3. Click on the + in the compose box
4. Select "Assign task"
5. Enter a Title and a Description
6. Do not assign any group member
7. Create the task
8. Take the focus off the tab (go to another chat room, open a new tab)
9. Go back to the created task

## Expected Result:
The message entry field in a task should not disappear when you remove focus from the tab.

## Actual Result:
The message entry field in a task disappears when the focus is removed from the tab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/958eb81b-0020-4739-887b-fc37f56673d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by manan-upadhyay** [comment] 2023-07-26 18:45
If the input is not rendered conditionally, this issue might be caused by the height of the container and content overflow issue. In the first case, the render conditions needs to be checked, else we might just need to update some CSS

**Comment by manan-upadhyay** [comment] 2023-07-26 18:49
Contributor details
Your Expensify account email: upadhyaymanan01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0122e0ed8ca6eca7fa

**Comment by francoisl** [comment] 2023-07-26 19:11
> this issue might be caused by the height of the container and content overflow issue.

@manan-upadhyay to clarify, are you saying there's already a known issue with content overflow?


Anyway, I'm unable to reproduce the issue on staging and dev, are you?

https://github.com/Expensify/App/assets/2229301/785fedd3-e55b-43d1-b29c-49e427319c84

**Comment by marcaaron** [comment] 2023-07-26 20:07
FWIW - I also can't repro this one.

**Comment by francoisl** [comment] 2023-08-01 22:07
Still can't reproduce, now on v1.3.48. Going to close this, feel free to reopen if you're sure there's still an issue.

**Closed by francoisl** 2023-08-01 22:07 UTC
Labels: Engineering, Daily, Overdue
