### ISSUE TITLE
[HOLD for #32413][$500] Expense report title is too far away from avatar in page header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32417] opened 2023-12-03 15:49 UTC
- HELD on https://github.com/Expensify/App/issues/32413

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701391579217569

## Action Performed:
Go to an expense report

## Expected Result: 
The expense report title and small subtext (From...) should be just 12px away from the room avatar

## Actual Result: 
The expense report title and small subtext (From...) are too far to the right of the avatar in the page header compared to other chats (DMs, rooms, etc)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (52) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/2492e6c0-2909-4cee-ba8a-087a1f6fa458)

![CleanShot 2023-11-30 at 19 46 17@2x](https://github.com/Expensify/App/assets/38435837/b99d8df8-b1e9-4c4c-8495-d5a3e9a740d5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01420f85f91e69170f</li>
        <li>Upwork Job ID: 1731339996183658496</li>
        <li>Last Price Increase: 2023-12-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28014682</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-03 16:16
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Expense report title is too far away from avatar in page header

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/AvatarWithDisplayName.js#L135

### What changes do you think we should make in order to solve the problem?
need to update like this
<View style={[styles.flex1, styles.flexColumn]} />

**Comment by shubham1206agra** [comment] 2023-12-04 01:36
This seems to be fixed when I apply https://github.com/Expensify/App/issues/32413#issuecomment-1837561113

<img width="1137" alt="Screenshot 2023-12-04 at 7 05 37 AM" src="https://github.com/Expensify/App/assets/58412969/4150864a-98ae-4199-80fb-3b792f7a5bc8">

**Comment by kaushiktd** [comment] 2023-12-05 07:53
### Please re-state the problem that we are trying to solve in this issue.
Expense report title is too far away from avatar in page header

### What is the root cause of that problem?
`shouldShowSubscriptAvatar` && !isExpenseRequest ? styles.ml4 : {}
 when the condition is true the style which is ml4: Sets the margin-left to 16 units.

### What changes do you think we should make in order to solve the problem?
ml0: Sets the margin-left to 0 units.
ml1: Sets the margin-left to 4 units.
ml2: Sets the margin-left to 8 units.
ml3: Sets the margin-left to 12 units.
ml4: Sets the margin-left to 16 units.

If you want to set the expense report title and small subtext (From...) should be just 12px away from the room avatar.
then we have to use 'styles.ml3'.
but I want to suggest you should use 'styles.ml1' which sets right margin

Image:
![image](https://github.com/Expensify/App/assets/43398804/b8ca99db-213a-4ae3-81f4-b0d2b9e10f7c)

**Comment by robertKozik** [comment] 2023-12-05 10:44
@johncschuster could you reassign the C+ here, I have more priority task on my plate right now

**Comment by situchan** [comment] 2023-12-05 10:54
I can take this

**Comment by johncschuster** [comment] 2023-12-08 21:39
@situchan, I've assigned you the C+ role, but Melvin tagged you for the contributor. Just making a note in case Melvin doesn't correctly assign the contributor down the line.

**Comment by situchan** [comment] 2023-12-11 17:25
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/32417#issuecomment-1837526386) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2023-12-11 17:39
@situchan Can you please put this on hold for https://github.com/Expensify/App/issues/32413

**Comment by situchan** [comment] 2023-12-11 17:41
@shubham1206agra will there be any conflict?

**Comment by shubham1206agra** [comment] 2023-12-11 17:42
Actually this seems to be fixed with that issue too as a side effect

**Comment by arosiclair** [comment] 2023-12-12 15:40
> Actually this seems to be fixed with that issue too as a side effect

Alright let's hold this and wait for that fix to go out. Then just verify that this issue is also fixed.

**Comment by arosiclair** [comment] 2023-12-15 16:53
PR is out: https://github.com/Expensify/App/pull/33042

**Comment by johncschuster** [comment] 2023-12-18 15:42
@greg-schroeder I'm OOO starting Monday, December 18 (today) through Tuesday, January 2.

**Current status:**
We've just put this issue on hold to see if https://github.com/Expensify/App/pull/33042 resolves it.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by greg-schroeder** [comment] 2023-12-19 03:16
Linked PR is going through final reviews

**Comment by greg-schroeder** [comment] 2023-12-21 19:08
Deployed to staging

**Comment by arosiclair** [comment] 2023-12-27 14:33
[PR is deployed in **v1.4.15-5**](https://github.com/Expensify/App/pull/33042#issuecomment-1867253142) and it's looking good:

<img width="1396" alt="Screenshot 2023-12-27 at 9 33 02 AM" src="https://github.com/Expensify/App/assets/6833644/867990a2-1e4a-4c4c-87df-afc6400d6df8">

This should be all set

**Closed by arosiclair** 2023-12-27 14:33 UTC
Labels: External, Daily, Overdue, Bug
