### ISSUE TITLE
[$500]  IOU - Application crashes when trying to create IOU on a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28196] opened 2023-09-25 20:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in under a new account @applause.expensifail.com
3. Tap on FAB.
4. Select Request Money
5. Enter any amount
6. Tap the Next button
7. Select any two members in Split
8. Tap Add to split

## Expected Result:
There should be no program crashes when creating an IOU

## Actual Result:
When creating a split bill, it crashes immediately after trying to click on the "Add to split" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ff19eac2-9d79-4022-9600-3148ff012a22

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019545d0a73bae509f</li>
        <li>Upwork Job ID: 1706717835057606656</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by chiragsalian** [comment] 2023-09-26 00:47
I tested on staging and it seemed to work fine for me. Can you retest @lanitochka17?
Also in your step 2 you mention,
>  Log in under a new account @applause.expensifail.com

Does it matter to use `applause.expensifail.com`, asking because i used gmail and it seemed to work fine for me.

**Comment by sakluger** [comment] 2023-09-26 03:53
Asked in the #QA channel in Slack (https://expensify.slack.com/archives/C9YU7BX5M/p1695700402659299)

**Comment by isagoico** [comment] 2023-09-26 07:58
Updated the Platforms so they reflect the confirmed reproductions. So far the issue is confirmed to happen in iOS, Android and iOS/Safari. 
<img src="https://github.com/Expensify/App/assets/44479856/66d428db-8c0f-4f9d-9f9c-3e512ec63652" width="40%"> <img src="https://github.com/Expensify/App/assets/44479856/9f7dc274-be34-457c-9cd0-de4efe07a079" width="40%">

Also, was able to reproduce the issue in production iOS (both native and mWeb) so we should be good to remove the deploy blocker.

**Comment by sakluger** [comment] 2023-09-26 08:00
I removed the deploy blocker and switched to a daily. @chiragsalian do you want to work on this or should we make it external?

**Comment by chiragsalian** [comment] 2023-09-26 17:10
external 🙂

**Comment by situchan** [comment] 2023-09-27 05:22
Dupe of https://github.com/Expensify/App/issues/28182 and already fixed

**Comment by amyevans** [comment] 2023-09-30 22:39
This was fixed!

**Closed by amyevans** 2023-09-30 22:39 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
