### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] Web - "Yes start over" option in connect bank account page is not working when connecting with google login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27526] opened 2023-09-15 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Make sure you have Workspace created and your bank account formulated .
1. ( IMPORTANT) Login via Google Auth.
2. Settings -> workspaces
3. Select any workspace -> Bank account
4. If it shows an update to USD, change the account to USD.
5. Now on the Connect bank account page, select Start over
6. On the popup select start over/

## Expected Result:
App runs smoothly, start over option should reset the previously set bank details.

## Actual Result:
"Yes start over" option in connect bank account page is not working when connecting with google login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/56b1301f-497b-403e-a71d-f61a94d5cfb8

https://github.com/Expensify/App/assets/93399543/66d91b58-fa88-4093-a9bd-8cdb69b6234f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694674481770019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b642fdf41a547a16</li>
        <li>Upwork Job ID: 1702670853573509120</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27104783</li>
<li>ashimsharma10 | Reporter | 27104788</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-09-20 07:06
@situchan could you please take a look at the proposal above?

**Comment by situchan** [comment] 2023-09-25 10:38
reviewing today

**Comment by sakluger** [comment] 2023-09-28 07:08
@situchan seems like you have other priorities at the moment, reassigning C+ to keep things moving forward here.

**Comment by sakluger** [comment] 2023-09-28 07:09
@abdulrahuman5196 could you please take a look at the above proposal as soon as you have a chance? Thanks!

**Comment by situchan** [comment] 2023-09-28 07:32
sorry, was about to update today. @abdulrahuman5196 will be busy catching up his issues after back from OOO.

**Comment by situchan** [comment] 2023-09-28 07:32
@zukilover's root cause is correct and solution also makes sense.
But I'd like to confirm with engineer if we should send `login` in `credentials` data from backend.
🎀 👀 🎀

- normal email login

<img width="374" alt="Screenshot 2023-09-28 at 1 30 00 PM" src="https://github.com/Expensify/App/assets/108292595/cbd98571-9bbe-4121-bbea-e44327c00a5d">

- google login

<img width="361" alt="Screenshot 2023-09-28 at 1 30 10 PM" src="https://github.com/Expensify/App/assets/108292595/8b16a266-7d94-451b-8478-fb178a9479d4">

**Comment by abdulrahuman5196** [comment] 2023-09-28 07:52
No worries. Seems already @situchan approved a proposal. I am unassigning myself. Let me know if any help is required, would be happy to help.

**Comment by neil-marcellini** [comment] 2023-10-02 16:35
I'll review soon

**Comment by neil-marcellini** [comment] 2023-10-02 20:59
I think I also like @zukilover's [proposal](https://github.com/Expensify/App/issues/27526#issuecomment-1721333258) but I'm going to double check with @marcochavezf who worked on the SignInWithGoogle API to see if we should return the login.

**Comment by neil-marcellini** [comment] 2023-10-04 15:49
Assigning it to Marco as he requested. He'll look into fixing it on the backend.

**Comment by sakluger** [comment] 2023-10-05 06:00
Sorry @hoangzinh, I forgot to add @situchan back as the C+, I removed you and re-added @situchan.

Also switched to Internal. @marcochavezf feel free to re-add the external label if we need any external help in addition to your backend changes.

**Comment by situchan** [comment] 2023-10-08 09:48
@marcochavezf `credentials.login` was used in many places with normal email login logic.
So I'm afraid adding social login email to `credentials.login` would cause unexpected behaviors (i.e. social login is treated as normal login).
Personally, I am fine using `session.email` to close this issue.

**Comment by marcochavezf** [comment] 2023-10-09 17:17
Yeah, I think that also makes sense because 1) that's the only way to differentiate at the moment if it's a social login or normal login, and 2) it seems this is the only case where we're checking `credentials.login`. We'd also need to check if this issue doesn't happen with accounts that use only phone numbers as login method.

**Comment by zukilover** [comment] 2023-10-10 04:59
PR will be ready in 3 hours.

**Comment by sakluger** [comment] 2023-10-23 18:32
@zukilover I sent you an offer through Upwork, once you accept I can complete payment.

@situchan could you please complete the BZ checklist today? Thanks!

**Comment by situchan** [comment] 2023-10-23 18:44
No regression but it would have been better to test this flow while implementing google sign-in.

### Regression Test Proposal
1. Sign in with Google or Apple.
2. Go to Settings -> workspaces
3. Select any workspace -> Bank account
4. Set up bank account details, then go back and Start over
5. On the popup select Start over
6. Verify that it reset the previously set bank details and allow user to start over.

**Comment by sakluger** [comment] 2023-10-23 21:09
Thanks @situchan, those steps look good!

**Comment by sakluger** [comment] 2023-10-24 21:11
Hi @zukilover - I see that you accepted the contract and accepted a modification to include the speed bonus. Please note that the initial offer is always for the base amount, then we add the speed bonus as a bonus if eligible. I'll accept your change request this time. 👍

**Comment by sakluger** [comment] 2023-10-24 21:12
All done, thanks everyone!

**Closed by sakluger** 2023-10-24 21:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
