### ISSUE TITLE
 Account validation - Close Window button is non-functional

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29734] opened 2023-10-17 00:02 UTC
## Expected Result:
The 'close window' button on the success page should be functional. The page should close smoothly, and the user should be redirected to the Expensify inbox page

## Actual Result:
The 'close window' button on the success page isn't functional, no further action is observed when user clicks on it

## Action Performed:
1. Navigate to staging.expensify.com
2. On the email field - enter a new email
3. Click join button
4. Log out of the account
Validate account:
1. In the email field enter the same email
2. Verify you're asked for a magic code
3. Navigate to your inbox, copy the Magic link and change it to staging
4. In success page, click on ''Close Window'' button

## Workaround:
Unknown

## Notes/Photos/Videos:

https://github.com/Expensify/App/assets/78819774/4e2afb8f-6b13-4e56-8877-4b7f9a90b8ab

Tester login credentials -

**Comment by dangrous** [comment] 2023-10-17 19:52
Okay so I'm 99% certain this is an artifact of testing. Because the URL was typed in manually (to direct it to staging vs. prod), rather than clicking on a link, it has no "parent" and so cannot be closed by JavaScript. Unfortunately, this doesn't seem to be something we can make a workaround for - but it's also something that's going to be pretty uncommon - almost no one will go to that page without just clicking the link.

@lanitochka17 can you confirm that this doesn't happen on production if you click on the link from the email? If so I think we can close out.

Also this should be in the Expensify/Expensify repo not Expensify/App - if we are going to keep it open we should move it there.

**Comment by dangrous** [comment] 2023-10-17 19:54
One more question - is this a new bug, or is it instead a new test? If I'm right, this should basically always happen - but if it only just started then maybe there's something else going on.

**Comment by kbecciv** [comment] 2023-11-02 14:44
@dangrous This issue is related to the Login TC in TestRail, which was recently added to the Regression run. 
https://expensify.testrail.io/index.php?/runs/view/18896&group_by=cases:section_id&group_order=asc&group_id=288239

**Comment by dangrous** [comment] 2023-11-02 18:17
hi! @lanitochka17 let us know when you can about the above - thank you!

**Comment by dangrous** [comment] 2023-11-02 19:11
Okay got it, thank you! So if it's a new test and it wasn't doing something else before, I think we're okay to close this - the reason it's happening is that it's a manual paste/modification of the URL from the magic link email, and so the browser won't allow it to close itself. Not much we can do about this, as far as I'm aware!

**Closed by dangrous** 2023-11-02 19:11 UTC
Labels: Engineering, Weekly, Improvement
