### ISSUE TITLE
[HOLD for payment 2024-10-25] [Hold for Payment 2024-10-23][$125] Web - Blue border appears on a radio button when pressing a keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49501] opened 2024-09-19 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nl619@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign in using an expensifail account
2. Create a workspace
3. Start adding a bank account via plaid
4. On "choose an account" page select a radio button that is not currently selected
5. Press the space bar on your keyboard

## Expected Result:
No blue border is visible

## Actual Result:
Blue border gets shown on the radio button

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/94393bc3-b499-4707-b9b2-9500703f85dd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839026052320413685</li>
        <li>Upwork Job ID: 1839026052320413685</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC / @abekkala</details>

**Comment by IuliiaHerets** [comment] 2024-09-19 21:10
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-09-24 05:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A blue outline appear in the radio button when using keyboard.

### What is the root cause of that problem?
It's expected that the blue outline will show when using a keyboard, but I think the issue here is with the styling of the outline. Instead of circle, the outline is a square. We have similar issue like this before in https://github.com/Expensify/App/issues/32400 on a different page/component.

In our case, the border style of the radio button is applied to the View inside the pressable.
https://github.com/Expensify/App/blob/a7a408fb0e6a01ebbe52831e468a8e3d310e4dbd/src/components/RadioButton.tsx#L31-L40

So, when we focus on the pressable, the square outline is shown because it's not styled to be a circle.

### What changes do you think we should make in order to solve the problem?

We can move the whole style from the View to the pressable and just remove the View. This will fix the issue with the RadioButton component. 

However, I still see this issue with another component, specifically in the start chat page.
<img width="372" alt="image" src="https://github.com/user-attachments/assets/d42ce3c5-bd07-4aa2-8551-e5eac9bad363">

It was previously fixed in https://github.com/Expensify/App/issues/32400, but the page doesn't use OptionRow component anymore, so we need to re-fix it using the same solution from https://github.com/Expensify/App/pull/35028. We can even go further by creating a new component called SelectCircleButton to make the fix DRY.

**Comment by abekkala** [comment] 2024-09-25 19:36
@ntdiary we already have a couple proposals for review! 🎉

**Comment by dubielzyk-expensify** [comment] 2024-09-27 00:51
Yeah agree. This is standard accessibility practise from what I'm aware of, so I'm fine with the blue border

**Comment by abekkala** [comment] 2024-09-27 15:17
ah ok - so if design is fine with the blue border I'll close this one!

**Comment by bernhardoj** [comment] 2024-09-28 04:24
@abekkala I think we agreed that the blue border is expected, but maybe we want to change it from square to circle.

Before:
<img width="389" alt="image" src="https://github.com/user-attachments/assets/d9d3afa7-cd64-47f6-85f0-31a364f6020d">

After:
<img width="394" alt="image" src="https://github.com/user-attachments/assets/df8c40c9-b959-4e0c-91f8-eefd3bdd971b">


We previously fixed this kind of issue in https://github.com/Expensify/App/issues/32400

cc: @dannymcclain @dubielzyk-expensify

**Comment by dubielzyk-expensify** [comment] 2024-09-30 00:25
Yeah the Before looks a bit weird there. If we could fix that, that would be nice

**Comment by dannymcclain** [comment] 2024-09-30 13:41
I agree—the after in your post looks _much_ better.

**Comment by bernhardoj** [comment] 2024-10-04 11:51
@abekkala hi, can you check the comments above, please?

**Comment by abekkala** [comment] 2024-10-09 14:04
Reopening so that this change can be made (square to circle)

**Comment by abekkala** [comment] 2024-10-10 14:13
Removed bug label as this is more of a design fix and does not need to be linked to a project

**Comment by abekkala** [comment] 2024-10-11 14:45
@OfstadC I'm going ooo until Oct 20 - assigning a BZ buddy to look over this until I return. 

### STATUS: @ntdiary has just selected a proposal for fix. @luacmartins will review to confirm. 

Removed Bug label again as this is not linked to a project, just a design fix

**Comment by luacmartins** [comment] 2024-10-11 16:55
Agree with https://github.com/Expensify/App/issues/49501#issuecomment-2407392372. Let's keep the components separate for now.

**Comment by bernhardoj** [comment] 2024-10-12 13:41
PR is ready

cc: @ntdiary

**Comment by abekkala** [comment] 2024-10-21 12:52
I'm back from ooo - unassigning @OfstadC

**Comment by abekkala** [comment] 2024-10-21 12:54
### PAYMENT SUMMARY FOR OCT 25

- Fix: @bernhardoj [$125, if no regressions]
- PR Review: @ntdiary  [$125, if no regressions]
Please complete checklist

**Comment by abekkala** [comment] 2024-10-21 12:55
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@ntdiary] The PR that introduced the bug has been identified. Link to the PR:
- [ ]   [@ntdiary] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]   [@ntdiary] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]   [@ntdiary] Determine if we should create a regression test for this bug.
 [@ntdiary] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]   [@abekkala] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bernhardoj** [comment] 2024-10-21 14:45
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-25 11:42
$125 approved for @bernhardoj

**Comment by abekkala** [comment] 2024-10-25 13:20
Closing as last cont. payment will be for @ntdiary [$125] via NewDot

**Closed by abekkala** 2024-10-25 13:20 UTC
Labels: External, Weekly, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-10-28 11:00
$125 approved for @ntdiary
