### ISSUE TITLE
[$500]  Desktop - The upper left "Apple icons" have a faint tinted line through them

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29162] opened 2023-10-10 08:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.80-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N, this is a new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Open the New Expensify Desktop app
2. Sign into a valid account
3. Observe the top left corner

## Expected Result:
User expects that there is no overlapping and items are spaced evenly

## Actual Result:
There is a very faint green line running through the Desktop Apple icons in the upper left corner. Also, these icons are very closely displayed to the users avatar image and when there is an error message (Red dot) on the users profile, they almost overlap.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

![Bug6231461_1696915877805!Zoomed_in_screenshot](https://github.com/Expensify/App/assets/115492554/368e9a8d-f0d7-4e56-9de7-1844a5943c75)
<img width="1440" alt="Bug6231461_1696915877827!Desktop_apple_icons_slightly_overlap_with_fading_effect" src="https://github.com/Expensify/App/assets/115492554/59968b10-229a-4dd0-818f-120dc31b253c">
<img width="1440" alt="Bug6231461_1696915877794!How_it_displays_when_there_is_an_error_icon" src="https://github.com/Expensify/App/assets/115492554/b58dd973-33fe-47be-bd42-67ef1d2d0fad">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121122693d769b021</li>
        <li>Upwork Job ID: 1711662396186996736</li>
        <li>Last Price Increase: 2023-10-10</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-10-10 09:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - The upper left "Apple icons" have a faint tinted line through them
### What is the root cause of that problem?

We have introduced a new global navigation in which we added a new sidebar screen which is causing this issue. Previosuly we used to have Expensify Logo and same bg color for entire LHN. 

But due to recent changes we have different color for new sidebar screen and also replaced logo with some text and user's avatar.

### What changes do you think we should make in order to solve the problem?

We need to increase the header gap for electron. Right now it's 12px which is serving it's purpose but to accomodate new look we need to increase the height maybe (26px?)

https://github.com/Expensify/App/blob/d916effd3ffb2f29adcd3cfad1e314f210a23efa/src/CONST.ts#L885


> 26px gap
<img width="560" alt="Screenshot 2023-10-10 at 2 44 53 PM" src="https://github.com/Expensify/App/assets/59088937/53f47221-f6c0-48ef-b22c-2f229b12f7f0">

### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-10-10 09:16
@shawnborton can you check this as it might be related to design issue.

**Comment by abdulrahuman5196** [comment] 2023-10-10 11:05
> This maybe not a deploy blocker and handled in #29057? cc: @hayata-suenaga

Kindly do let me know if we don't need to take this issue separately. The above proposal seems good(Need to test still though.)

**Comment by madmax330** [comment] 2023-10-10 16:47
Cool so we can close this @shawnborton  or should I assign @adamgrzybowski ?

**Comment by shawnborton** [comment] 2023-10-10 16:54
Let's first confirm with @hayata-suenaga - I'm not sure what our plan is for consolidating design bugs for the hybrid web project.

**Comment by jasperhuangg** [comment] 2023-10-10 20:38
Gonna take the `Deploy Blocker` label off if this is a known followup

**Comment by trjExpensify** [comment] 2023-10-10 22:48
I asked @stitesExpensify if he knew [here](https://expensify.slack.com/archives/C05NM77EUTS/p1696963761667819), but I think we'll have to wait for @hayata-suenaga to confirm the plan for these design followups.

**Comment by hayata-suenaga** [comment] 2023-10-11 05:37
This issue is consolidated to [this issue](https://github.com/Expensify/App/issues/29057). This issue was reported by Applause, so no payment is necessary for bug report.

**Closed by hayata-suenaga** 2023-10-11 05:37 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by kosmydel** [comment] 2023-10-12 10:40
Hey, some questions related to design here:

I'm considering the following options:
1. Increase padding on the desktop (I believe that `27px` will have even paddings from the top and bottom) and change the background color of the header gap (screen).
2. Or maybe increase padding for the avatar. Downside: Avatar will no longer align with the other items at the top ("Chats" text, Search loop, etc.).

Here is what the first option looks like:
![Screenshot 2023-10-12 at 12 39 49](https://github.com/Expensify/App/assets/104823336/6ee4dd0c-42ac-4a12-96b7-6ad0fb293801)

We also have to take into consideration that the Avatar displays a popup when is hovered:
![Screenshot 2023-10-12 at 12 40 01](https://github.com/Expensify/App/assets/104823336/43e05eb7-1fb1-4aeb-b942-0b1a7dc02488)


Which option is the preferred one?

cc @shawnborton, @hayata-suenaga

**Comment by shawnborton** [comment] 2023-10-12 12:52
[Discussing here in Slack](https://expensify.slack.com/archives/C05NM77EUTS/p1697112873910809)
