### ISSUE TITLE
[HOLD for payment 2024-02-19] [$250] Remove MoneyRequestDescriptionPage.js and copy any changes since Nov 27 into IOURequestStepDescription.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34609] opened 2024-01-16 20:50 UTC
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `MoneyRequestDescriptionPage`
**New Component** `IOURequestStepDescription`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b522902265a76e3</li>
        <li>Upwork Job ID: 1747632811433705472</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28120097</li>
<li>DylanDylann | Contributor | 28120098</li>
</ul></li>
    </ul>
</details>

**Comment by KrAbhas** [comment] 2024-01-16 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove MoneyRequestDescriptionPage.js and copy any changes since Nov 27 into IOURequestStepCategory.js

### What is the root cause of that problem?

Refactoring  of MoneyRequestDescriptionPage

### What changes do you think we should make in order

We will be deleting the component here:

**Comment by njmulsqb** [comment] 2024-01-17 01:38
I would love to take this!

**Comment by DylanDylann** [comment] 2024-01-17 04:15
## Proposal
     
### Please re-state the problem that we are trying to solve in this issue.
Remove MoneyRequestDescriptionPage.js and copy any changes since Nov 27 into IOURequestStepDescription.js 

### What is the root cause of that problem?
Remove deprecated component 

### What changes do you think we should make in order to solve the problem?
1. Remove MoneyRequestDescriptionPage component and all traces like


https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L99

https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L432

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L273-L276

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/SCREENS.ts#L144

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/libs/Navigation/types.ts#L204-L209

2. For new component IOURequestStepDescription

In here
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L342-L346
We need to use the new :action param (instead of being hard-coded with "create") like we did here

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L362-L366

3. Copy changes since 27 Nov to new components based on list commit here: https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestDescriptionPage.js

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2024-01-17 18:26
Borrowing the comments from @tgolen from other GHs related to this project: 

## Thank you, everyone, for the energy here, but please follow the contributor guidelines. If you are interested in this one, then please submit a proposal for the changes that are important here. After, it will go through a review process.

**Comment by s77rt** [comment] 2024-01-18 14:22
Discussing on slack https://expensify.slack.com/archives/C02NK2DQWUX/p1705538986244869

**Comment by alexpensify** [comment] 2024-01-19 19:43
@DylanDylann - Tim shared some feedback in this 🧵 here: 

 https://expensify.slack.com/archives/C02NK2DQWUX/p1705538986244869
 
 Please review and update your proposal if you are still interested in this one. Thanks!

**Comment by s77rt** [comment] 2024-01-19 21:08
Quoting from the above discussion (since it's internal) the points that should be taken into consideration 

1. Where else do the routes need updated (when it's navigating to the edit view)
2. What (if any) logic needs updated for isEditing
3. setMoneyRequestDescription_temporaryForRefactor needs to be updated to have an isDraft param that's based on the new "action" route param
4. The Old Component not only needs to be removed, but it needs "replaced" with the New Component. This replacement isn't covered

**Comment by DylanDylann** [comment] 2024-01-20 04:16
@s77rt 

https://github.com/Expensify/App/assets/141406735/1f23eb39-0a59-48a4-91c2-bd612ed1c670

1. Currently, MoneyRequestDescriptionPage (old component) is no longer used anywhere 
2. We have another component EditRequestDescriptionPage to handle editing description

**Comment by s77rt** [comment] 2024-01-21 16:10
@DylanDylann We are looking to have all the IOU description logic being update from one place. `EditRequestDescriptionPage` should also get replaced with `IOURequestStepDescription`. 

Currently `setMoneyRequestDescription_temporaryForRefactor` will only update the transaction draft values but that should be the case only when creating a new request. If we are editing the request we should update transaction itself for that we need to add a new param `isDraft`.

Can you please look into that further and update your proposal?

PS: We should also copy recent changes (if any) from EditRequestDescriptionPage to IOURequestStepDescription

**Comment by DylanDylann** [comment] 2024-01-23 07:23
> We are looking to have all the IOU description logic being update from one place. EditRequestDescriptionPage should also get replaced with IOURequestStepDescription.

@s77rt It is a new point to me because I haven't seen it in the OP. So, we only use 1 component `IOURequestStep...` instead of `EditRequest...Page` and `MoneyRequest...Page` in all these IOU pages like Description, Distance, Merchant, Tag, Category, Date, ... And using action params from URL to detect if it is create or edit page

So I think we should update the OP in these issue for more clear

cc @tgolen

**Comment by DylanDylann** [comment] 2024-01-23 18:48
@s77rt [Updated proposal](https://github.com/Expensify/App/issues/34609#issuecomment-1894910002)

**Comment by s77rt** [comment] 2024-01-23 21:15
@KrAbhas Unfortunately your proposal is not complete.

**Comment by s77rt** [comment] 2024-01-23 21:15
@njmulsqb @AnshuAgarwal24 Please follow the proposal template

**Comment by s77rt** [comment] 2024-01-23 21:25
@DylanDylann Thanks for the update

> We shouldn't remove EditRequestDescriptionPage because we still use it for Edit Split Flow

Why would that be a problem? Can't we use that same component for the split flow?

**Comment by brunovjk** [comment] 2024-01-23 21:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This belongs to [Wave 5 cleanup](https://github.com/Expensify/App/issues/29107)
Phase 2 is all about removing the original components and any of the duplicated efforts.

### What is the root cause of that problem?
Replace `MoneyRequest...Page` (Create) and `EditRequest...Page`(edit) to `IOURequestStep...`. **This new component will handle both the create and edit flow based on `action` param**.

### What changes do you think we should make in order to solve the problem?

> 1. Look at the history of the Old Component
> 2. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes

1. Transfer modifications made after November 27th to create new components, following the list of commits provided here: https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestDescriptionPage.js

> 3. Replace all uses of the Old Component with the New Component
> 4. Remove all traces of Old Component

2. There is no use of the component other than `ModalStackNavigators`. We can remove the `MoneyRequestDescriptionPage` component along with:
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L99

3. The new component (STEP_DESCRIPTION) has it [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L400), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L129) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L346-L350) already configured, we must **remove** `DESCRIPTION` from the same places:
https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L432
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L144
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L277-L280

> 5. Be sure to update all routes and navigation to use the new :action param (instead of being hard-coded with "create")

4. Update https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/libs/Navigation/types.ts#L204-L209
to
    ```
        [SCREENS.MONEY_REQUEST.STEP_DESCRIPTION]: {
            iouType: string;
            transactionID: string;
            reportID: string;
            backTo: string;
        };
    ```
5. Update
https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/ROUTES.ts#L346-L350
to
    ```
        MONEY_REQUEST_STEP_DESCRIPTION: { 
            route: ':action/:iouType/description/:transactionID/:reportID', 
            getRoute: (action: ValueOf<typeof CONST.IOU.ACTION>, iouType: ValueOf<typeof CONST.IOU.TYPE>, transactionID: string, reportID: string, backTo = '') => 
                getUrlWithBackToParam(`${action}/${iouType}/description/${transactionID}/${reportID}`, backTo), 
    }, 
    ```
6. Update
https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L698
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_DESCRIPTION.getRoute(CONST.IOU.ACTION.CREATE, iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()));
    ```
> 6. Update any logic like isEditing to use the new action param from the route

7. We need to create new variable `const isDraft = action === CONST.IOU.ACTION.CREATE` (we will get action from route) in `IOURequestStepDescription.js` and pass it to `setMoneyRequestDescription_temporaryForRefactor` as a new param:
    ```
        route: {
            params: {action, transactionID, backTo},
        },
    ...
    const isDraft = action === CONST.IOU.ACTION.CREATE;
    ...
        Navigation.goBack(isDraft && backTo || ROUTES.HOME);
    ...
    const updateComment = (value) => {
        IOU.setMoneyRequestDescription_temporaryForRefactor(transactionID, value.moneyRequestComment, isDraft);
        navigateBack();
    };
    ```

8. In `setMoneyRequestDescription_temporaryForRefactor` we will save the new description to `draft_transaction` if `isDraft` is true else we will save it to the transaction:
    ```
    ...
     * @param {Boolean} isDraft - Indicates whether it's a draft or not
     */
    function setMoneyRequestDescription_temporaryForRefactor(transactionID, description, isDraft) {
        const key = isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION;
        Onyx.merge(`${key}${transactionID}`, { description });
    }
    ```

9. Update
https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/ReportActionItem/MoneyRequestView.js#L289
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_DESCRIPTION.getRoute(CONST.IOU.ACTION.EDIT, CONST.IOU.TYPE.REQUEST, transaction.transactionID, report.reportID, Navigation.getActiveRouteWithoutParams()))
    ```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by brunovjk** [comment] 2024-01-23 22:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This belongs to [Wave 5 cleanup](https://github.com/Expensify/App/issues/29107)
Phase 2 is all about removing the original components and any of the duplicated efforts.

### What is the root cause of that problem?
Replace `MoneyRequest...Page` (Create) and `EditRequest...Page`(edit) to `IOURequestStep...`. **This new component will handle both the create and edit flow based on `action` param**.

### What changes do you think we should make in order to solve the problem?

> 1. Look at the history of the Old Component
> 2. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes

1. Transfer modifications made after November 27th to create new components, following the list of commits provided here: https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestDescriptionPage.js

> 3. Replace all uses of the Old Component with the New Component
> 4. Remove all traces of Old Component

2. There is no use of the component other than `ModalStackNavigators`. We can remove the `MoneyRequestDescriptionPage` component along with:
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L99

3. The new component (STEP_DESCRIPTION) has it [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L400), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L129) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L346-L350) already configured, we must **remove** `DESCRIPTION` from the same places:
https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L432
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L144
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L277-L280

> 5. Be sure to update all routes and navigation to use the new :action param (instead of being hard-coded with "create")

4. Update https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/libs/Navigation/types.ts#L204-L209
to
    ```
        [SCREENS.MONEY_REQUEST.STEP_DESCRIPTION]: {
            iouType: string;
            transactionID: string;
            reportID: string;
            backTo: string;
        };
    ```
5. Update
https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/ROUTES.ts#L346-L350
to
    ```
        MONEY_REQUEST_STEP_DESCRIPTION: { 
            route: ':action/:iouType/description/:transactionID/:reportID', 
            getRoute: (action: ValueOf<typeof CONST.IOU.ACTION>, iouType: ValueOf<typeof CONST.IOU.TYPE>, transactionID: string, reportID: string, backTo = '') => 
                getUrlWithBackToParam(`${action}/${iouType}/description/${transactionID}/${reportID}`, backTo), 
    }, 
    ```
6. Update
https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L698
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_DESCRIPTION.getRoute(CONST.IOU.ACTION.CREATE, iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()));
    ```
> 6. Update any logic like isEditing to use the new action param from the route

7. In IOURequestStepDescription.js, create a new constant, `isDraft` based on the condition `action === CONST.IOU.ACTION.CREATE` obtained from the route. Pass this variable as a new parameter when calling `setMoneyRequestDescription_temporaryForRefactor`:
    ```
        route: {
            params: {action, transactionID, backTo},
        },
    ...
    const isDraft = action === CONST.IOU.ACTION.CREATE;
    ...
        Navigation.goBack(isDraft && backTo || ROUTES.HOME);
    ...
    const updateComment = (value) => {
        IOU.setMoneyRequestDescription_temporaryForRefactor(transactionID, value.moneyRequestComment, isDraft);
        navigateBack();
    };
    ```

8. In `setMoneyRequestDescription_temporaryForRefactor` we will save the new description to `draft_transaction` if `isDraft` is true else we will save it to the transaction:
    ```
    ...
     * @param {Boolean} isDraft - Indicates whether it's a draft or not
     */
    function setMoneyRequestDescription_temporaryForRefactor(transactionID, description, isDraft) {
        const key = isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION;
        Onyx.merge(`${key}${transactionID}`, { description });
    }
    ```

9. Update
https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/ReportActionItem/MoneyRequestView.js#L289
to
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_DESCRIPTION.getRoute(CONST.IOU.ACTION.EDIT, CONST.IOU.TYPE.REQUEST, transaction.transactionID, report.reportID, Navigation.getActiveRouteWithoutParams()))
    ```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by brunovjk** [comment] 2024-01-23 22:22
@s77rt and @DylanDylann, I was influenced by your discussion, both here and on slack, to do the part of replacing `EditRequestDescriptionPage to IOURequestStepDescription`

**Comment by DylanDylann** [comment] 2024-01-24 16:40
@s77rt [Updated proposal](https://github.com/Expensify/App/issues/34609#issuecomment-1894910002) to use new component for editing split flow

**Comment by brunovjk** [comment] 2024-01-24 17:02
## Proposal
[Updated](https://github.com/Expensify/App/issues/34609#issuecomment-1907016673)

The `isEditing` part I updated following [discussions ](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949)

**Comment by s77rt** [comment] 2024-01-24 18:34
@brunovjk Thanks for the proposal. I think your proposal is similar to @DylanDylann's. I don't see significant difference

**Comment by s77rt** [comment] 2024-01-24 18:36
@DylanDylann Thanks for the update. I think the proposal is clear enough to move into the PR.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34609#issuecomment-1894910002)

**Comment by brunovjk** [comment] 2024-01-24 19:03
> @brunovjk Thanks for the proposal. I think your proposal is similar to @DylanDylann's. I don't see significant difference

Indeed, I updated my proposal after your discussion, is it ok right? I think that any proposal that didn't, would be incomplete. I appreciate the review :D

**Comment by deetergp** [comment] 2024-01-24 19:50
I agree with @s77rt's assessment. Let's go with @DylanDylann's proposal.

**Comment by DylanDylann** [comment] 2024-01-25 12:12
@s77rt The PR is ready for review

**Comment by alexpensify** [comment] 2024-01-26 18:32
Awesome, we are moving forward here.

**Comment by alexpensify** [comment] 2024-02-02 22:21
Weekly update: PR is in review

**Comment by alexpensify** [comment] 2024-02-09 18:06
@DylanDylann and @s77rt - can we confirm if this issue caused this regression or if it's a false alarm? Thanks!

**Comment by s77rt** [comment] 2024-02-09 18:11
@alexpensify Yes I have commented on that issue https://github.com/Expensify/App/issues/36175#issuecomment-1935229980

**Comment by alexpensify** [comment] 2024-02-09 18:12
My bad, I missed that comment. Thanks for flagging!

**Comment by s77rt** [comment] 2024-02-13 00:14
Checklist ^ does not apply here. This is a feature request (code refactor) and not a bug.

**Comment by alexpensify** [comment] 2024-02-15 23:21
Flagging that I will be OOO on Monday, but will complete the payment process on Tuesday, February 20.

**Comment by alexpensify** [comment] 2024-02-20 22:29
Payment summary is here: https://github.com/Expensify/App/issues/34609#issuecomment-1938720523

Everyone has been paid via Upwork.

**Comment by s77rt** [comment] 2024-02-20 22:30
@alexpensify Payment here should be $125 for the [regression](https://github.com/Expensify/App/issues/34609#issuecomment-1935142910). I have refunded $125

**Comment by alexpensify** [comment] 2024-02-20 22:32
Thanks for your honesty! I missed the regression notice and saw it after I hit send in Upwork. All actions are complete here, closing!

**Closed by alexpensify** 2024-02-20 22:32 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by alexpensify** [comment] 2024-03-11 15:00
@s77rt - I believe that the regression was already addressed in another GH. Was today's notice an error? Thanks!

**Comment by s77rt** [comment] 2024-03-11 15:01
Yes the above notice is a false positive

**Comment by alexpensify** [comment] 2024-03-11 15:02
Thanks!

**Comment by DylanDylann** [comment] 2024-03-11 15:31
Let's ignore it. It is only a reference
