### ISSUE TITLE
Request money - black color are showing in list of distances

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25964] opened 2023-08-25 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on "+" button
2. Go to request money
3. Then select disctance
4. Add some stops if not added(add until list is scrollable)

## Expected Result:
There should not have any color box

## Actual Result:
There is black color box at bottom of the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/24f68946-2429-4f77-8180-a1ae9d137aed

https://github.com/Expensify/App/assets/78819774/c841b791-18f0-4b89-8c69-1334f07de21b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692097397299669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-08-25 18:22
Dupe of https://github.com/Expensify/App/issues/24447

**Comment by dylanexpensify** [comment] 2023-08-28 11:09
updating today!

**Closed** 2023-08-28 16:34 UTC
Labels: Daily, Bug
