### ISSUE TITLE
Desktop - Keyboard arrow keys doesn't work on New chat/Send money/Request money flow @Tushu17

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9517] opened 2022-06-21 19:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop/Website
2. Open fab menu :green-plus-button: > New chat
3. Press Down/Up keys.

## Expected Result:
User should be able to choose a contact using arrow keys.

## Actual Result:
Nothing happens.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** V1.1.78-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/174879868-495bb634-3057-4966-a537-af34db0b454c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Tushu17 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2022-06-23 02:09
I'm going to take your word for it that you are in fact pressing the arrow keys when nothing happens in the video 😆

**Comment by luacmartins** [comment] 2022-06-23 13:48
Maybe a regression from https://github.com/Expensify/App/pull/9473? @JosueEchandiaAsto @rushatgabhane

**Comment by JosueEchandiaAsto** [comment] 2022-06-23 14:18
@luacmartins 
Remove the change made in https://github.com/Expensify/App/pull/9473, this change is not associated, and only modifies the emojis menu. However we can replicate the logic of the emojis menu, to listen for arrow events and according to it remove or assign the focus on the contact list and the search bar.

https://user-images.githubusercontent.com/16966456/175319939-c6aefce8-98ae-4525-b02a-9e3bf437a760.mov

If I remove the focus from the search field, scrolling works with the arrow keys

https://user-images.githubusercontent.com/16966456/175321104-44ffb906-c5c3-4bba-8931-04e529219df5.mov

**Comment by rushatgabhane** [comment] 2022-06-23 16:12
@JosueEchandiaAsto thanks for the investigation!

@luacmartins #9473 isn't on production yet. 
This issue is a duplicate of https://github.com/Expensify/App/issues/7648. We can safey close this!

**Closed** 2022-06-24 08:56 UTC
Labels: Engineering, Weekly, Improvement
