### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - UserB can access the room "Welcome message" page and update it without permission

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22013] opened 2023-07-01 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to userA's account
2. Go to the "New room" section
3. Enter a room name and select userA's workspace
4. Set the visibility to "Public"
5. Click on "Create room"
6. Go to the room details.
7. Go to Share code >  Copy the URL to the clipboard
8. Return to the room details
9. Navigate to Settings > Welcome message
10. Open a different browser and login to userB's account
11. Join the room by pasting the room URL
12. Now copy the “Welcome message” page URL from userA account
13. Paste it on userB’s browser
14. Update the "Welcome message"
15. Now copy the room URL from userA's account
16. Paste the URL in another browser

## Expected Result:
UserB should be unable to access the "Welcome message" page and should not be able to modify it

## Actual Result:
UserB can access the "Welcome message" page and update it without permission

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/22effdf5-271a-423f-9876-1a94881ee50a

https://github.com/Expensify/App/assets/93399543/5c4e9b8e-6c24-4083-adbc-6aa183c64850

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688069999157569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112e180fbc88a066d</li>
        <li>Upwork Job ID: 1676001917057400832</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-07-01 12:06
# Proposal

## Please re-state the problem
Unauthorized users are able to edit the welcome message of the workspace room.

## What is the root cause of that problem?
The root cause is that there are no checks in place either on the backend or the front-end if the user has access to the workspace as an admin.

## What changes do you think we should make to solve this problem?
On the front-end, we should prevent the user from accessing the `welcomeMessage` page if the user is not an admin of the workspace.

First we need to add the `withOnyx` HOC to access the `policy` in `ReportWelcomeMessagePage.js`:
```js
withOnyx({
    policy: {
        key: ({report}) => `${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`
    }
}),
```

Here are the possible approaches:
1. We can navigate the user back if they are not an admin.
2. We can show the not found page if they are an admin.

**Option 1**
We can add a `userEffect` hook to check if the user is admin and if they not, just navigate them back like this:
```js
useEffect(() => {
      if (PolicyUtils.isPolicyAdmin(props.policy)) {
          return;
      }
      Navigation.goBack();
  }, [props.policy]);
```

**Option 2**
We are already using `FullPageNotFoundView` and we can add an additional condition for that as follows:
```js
const shouldHide = _.isEmpty(props.report) || !PolicyUtils.isPolicyAdmin(props.policy);
```

We should also do this for settings like `who can post` and `room name`.
Currently, we allow the user to see the edit room name page, but there is an error as soon as we try to change the name from the backend. I believe we should add this backend functionality to all other settings also while adding the front-end safeguards proposed above.

## What other approach did you explore

**Comment by puneetlath** [comment] 2023-07-03 22:56
Interesting. I agree that we need to restrict this from both the front-end and back-end.

**Comment by puneetlath** [comment] 2023-07-06 23:11
@mollfpr thoughts on the proposal?

**Comment by mollfpr** [comment] 2023-07-07 14:36
Reviewing now!

**Comment by esh-g** [comment] 2023-07-08 05:21
Just a note that we are trying to move away from HOCs with the typescript migration as mentioned here: https://expensify.slack.com/archives/C01GTK53T8Q/p1688768735041469?thread_ts=1688768338.846769&channel=C01GTK53T8Q&message_ts=1688768735.041469

**Comment by mollfpr** [comment] 2023-07-10 15:05
Thanks for the proposal guys!

The HOC seems tempting and can do the conditional rendering. But this is pretty simple checking, and I am okay with doing it on each component page. As mentioned before by @esh-g, we are trying to move away from HOCs, and migrating to typescript will give us a headache 😅

So the [proposal](https://github.com/Expensify/App/issues/22013#issuecomment-1615874424) from @esh-g looks good. I think showing the not found page seems good. Also, we should update the `RoomNamePage` and `WriteCapabilityPage`.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-07-10 15:44
Well played @hungvu193 👍

**Comment by esh-g** [comment] 2023-07-10 18:07
@mollfpr I think `WriteCapabilityPage` was also fixed in this PR: https://github.com/Expensify/App/pull/21857

**Comment by mollfpr** [comment] 2023-07-10 18:13
I think `ReportUtils.isAdminRoom(props.report)` differs from `PolicyUtils.isPolicyAdmin`. I also test the `who-can-post` URL on a non-admin account, and it's still open.

**Comment by esh-g** [comment] 2023-07-10 18:16
@mollfpr Okay, I think teh PR was just on the `#Admins` channel to make sure it is not editable to all members can post... I had a misunderstanding.

**Comment by puneetlath** [comment] 2023-07-11 18:32
@grgia thoughts on the proposal?

**Comment by grgia** [comment] 2023-07-13 12:33
I apologize for the delay, looking now!

**Comment by esh-g** [comment] 2023-07-13 17:07
Thanks for assigning me! 🚀
Here is the PR: https://github.com/Expensify/App/pull/22820
cc @mollfpr

**Comment by puneetlath** [comment] 2023-07-24 16:38
Looks like everyone has had contracts sent. 

@mollfpr friendly reminder on the checklist.

**Comment by puneetlath** [comment] 2023-07-27 21:28
Issue reporter: @ayazhussain79 $250
Contributor: @esh-g $1500 (including bonus)
C+: @mollfpr $1500 (including bonus)

I've paid the first two. @mollfpr just waiting on the checklist for you.

**Comment by mollfpr** [comment] 2023-07-31 05:10
Sorry, I swear I already complete the checklist of the issues near the payment date 😅

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18662
https://github.com/Expensify/App/pull/21857

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18662/files#r1278793008
https://github.com/Expensify/App/pull/21857/files#r1278797201

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Test Setup**

1. From account A, create a new workspace.
2. Invite account B.
3. Create a workspace from account B.

Therefore, B is an admin in workspace B and not workspace A.

We need to prepare a chat with deep links to the correct page for testing. This setup can be done once on web, and then can be tested on other platforms with the same account.

✅ The page will open
❌ The not found page will be open
_Please look at the 'Test Setup (Web)' in the screenshots section to ensure steps are followed correctly._

1. We first need to copy the reportID of #announce of workspace A and workspace B then also #admin of workspace B. This can be done by opening the room and copying the number in the URL localhost:8080/r/[reportID].

2. [#announce B] means the reportID of the #announce room of workspace B. The same format applies for all other reportIDs copied.

3. Go to any chat on account B.

4. Add a comment 'Welcome message as admin' and add a link like this: https://staging.new.expensify.com/r/[#announce B]/welcomeMessage ✅

5. Add another comment 'Welcome message not as admin' and add a link like this: https://staging.new.expensify.com/r/[#announce A]/welcomeMessage. ❌

6. Add another comment 'Who can post (in #admin)' and add this a link like this: https://staging.new.expensify.com/r/[#admin B]/settings-who-can-post. ❌

7. Add another comment 'Who can post (as admin)' and add a link like this: https://staging.new.expensify.com/r/[#announce B]/settings/who-can-post. ✅

8. Add another comment 'Who can post (not as admin)' and add a link like this: https://staging.new.expensify.com/r/[#announce A]/settings/who-can-post. ❌

9. Click on each link and verify that it opens correctly according to ✅ and ❌.

**Comment by puneetlath** [comment] 2023-07-31 21:52
Great, thanks. Paid!

**Closed by puneetlath** 2023-07-31 21:52 UTC
Labels: External, Weekly, Awaiting Payment, Bug
