### ISSUE TITLE
Web - Selected category of emoji is not displayed as active

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21900] opened 2023-06-29 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a chat
3. Click 'Add reaction'
4. Change the emoji category

## Expected Result:
The selected category of emoji should have a background like the one when you hover it, so that it is different from the unselected ones.

## Actual Result:
No change

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[emoji active category (1).webm](https://github.com/Expensify/App/assets/93399543/184b6032-021d-47b4-bcfb-5895c4a22ea6)

https://github.com/Expensify/App/assets/93399543/b6613806-d932-4449-97db-9fe0d62debe1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kassahun-asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687980318975729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kassahun-asefa** [comment] 2023-06-29 21:09
hello

**Comment by kassahun-asefa** [comment] 2023-06-29 21:12
Contributor details
Your Expensify account email: temari.habtamu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e9c1bf271216783f

**Comment by ninjaoshima** [comment] 2023-06-30 06:19
Can I work in here?

**Comment by bahaturky** [comment] 2023-06-30 08:27
Contributor details
Your Expensify account email: bahaturkyilmaz@gmail.com
Upwork Profile Link: [https://www.upwork.com/freelancers/~019b21091f9fb69960](https://www.upwork.com/freelancers/~019b21091f9fb69960)

**Comment by bahaturky** [comment] 2023-06-30 08:30
Contributor details
Your Expensify account email: bahaturkyilmaz@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019b21091f9fb69960

**Comment by bahaturky** [comment] 2023-06-30 08:32
Please assign this task to me

**Comment by sakluger** [comment] 2023-07-03 18:48
This is not a bug, it is a feature request. Clicking those categories doesn't filter the list or take you to a different page or tab, it just scrolls you to the correct header - in other words, those category icons are more like anchor links. Changing the color of the background doesn't make sense since you can just scroll up or down to move to another category.

**Closed by sakluger** 2023-07-03 18:48 UTC
Labels: Daily, Overdue, Bug
