### ISSUE TITLE
Commenting on any child report does not surface the report as unread in the LHN

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#44491] opened 2024-06-26 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Staging/web `v9.0.2-0`
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** tgolen@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** [here](https://expensify.slack.com/archives/C05LX9D6E07/p1719418895977499)

## Action Performed:
1. Have an expense report submitted to someone
2. While active and online in newdot, have the other person comment on the report in newdot

## Expected Result:
I should see the chat appear in my LHN as unread

## Actual Result:
I don't get any notifications and no chat appears in my LHN

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @puneetlath @danieldoglas

**Comment by tgolen** [comment] 2024-06-26 18:58
The problem has been tracked down to code not properly calculating the `notificationPreference` in the report object in the Onyx update of the messages. 

That is happening [here](https://github.com/Expensify/Web-Expensify/blob/6e9b5917bbaede6d00cdd2f6001ff71e1b4baaa5/lib/ReportUtils.php#L3579) in PHP, or [here](https://github.com/Expensify/Auth/blob/main/auth/lib/Report.cpp#L9015) in Auth

@jasperhuangg would you have any ideas as to why this might be failing to give the proper notification preference? See [here](https://expensify.slack.com/archives/C05LX9D6E07/p1719418895977499) for full context.

**Comment by alexpensify** [comment] 2024-06-26 21:10
@tgolen - should we mark this as an Internal Hot Pick or wait for Jasper's feedback?

**Comment by jasperhuangg** [comment] 2024-06-27 18:58
@tgolen Hmm not that I'm familiar with–I just ported over structureReportsForOnyx from PHP but I doubt the issue is from that function–I commented in the Slack thread:

> > That is happening [here](https://github.com/Expensify/Web-Expensify/blob/6e9b5917bbaede6d00cdd2f6001ff71e1b4baaa5/lib/ReportUtils.php#L3579) in PHP, or [here](https://github.com/Expensify/Auth/blob/main/auth/lib/Report.cpp#L9015) in Auth

> All that structureReportsForOnyx does is take a report summary from GetChats and format it for Onyx–so I think the problem would either be coming from how we’re calling GetChats or from within GetChats itself.

**Comment by alexpensify** [comment] 2024-06-28 17:58
@tgolen - should I add the Hot Pick label here?

**Comment by jasperhuangg** [comment] 2024-06-28 19:41
@alexpensify I think adding `Hot Pick` is good here.

**Comment by jasperhuangg** [comment] 2024-06-28 19:42
I updated the issue title to include all child reports since @puneetlath and I were able to reproduce this issue with regular chat threads too.

**Comment by alexpensify** [comment] 2024-06-28 21:55
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period. 

I'll try to check in a few times. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-07-01 13:46
No update, waiting for help here

**Comment by alexpensify** [comment] 2024-07-04 23:16
Still waiting for help here.

**Comment by alexpensify** [comment] 2024-07-08 17:50
No update, waiting for help.

**Comment by alexpensify** [comment] 2024-07-10 17:36
No update, still a Hot Pick.

**Comment by mvtglobally** [comment] 2024-07-11 03:46
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment] 2024-07-12 22:40
Since this isn't appearing in recent tests, I think we should close. I'll review more and confirm.

**Comment by jasperhuangg** [comment] 2024-07-15 17:59
Asked about retesting it again [here](https://expensify.slack.com/archives/C05LX9D6E07/p1721065980016239?thread_ts=1719418895.977499&cid=C05LX9D6E07), I'll close if I can't reproduce

**Comment by jasperhuangg** [comment] 2024-07-16 17:44
Can't reproduce, closing

**Closed by jasperhuangg** 2024-07-16 17:44 UTC
Labels: Daily, Internal, Bug, Hot Pick
