### ISSUE TITLE
[$500] Android - Status - Custom time put background and bring foreground, time input is not auto focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35120] opened 2024-01-25 01:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap profile
4. Tap status
5. Tap clear after
6. Tap custom ---- Time
7. Note, time input is auto focused and cursor is shown
8. Put app to background
9. Slide to other window
10. Now bring the app foreground
11. Note, time input is not auto focused and cursor is not shown

## Expected Result:
In Custom time page, putting app background and bringing foreground, time input must be auto focused, cursor must be shown

## Actual Result:
In Custom time page, putting app background and bringing foreground, time input is not auto focused, cursor is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b06e2df6-7057-404c-8493-9531be7a8e97

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016511e3903d059ac7</li>
        <li>Upwork Job ID: 1750327321087582208</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28133247</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-01-25 02:02
Miss on https://github.com/Expensify/App/pull/34712?

**Comment by jeremy-croff** [comment] 2024-01-25 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The focus on the time picker gets lost when switching tabs on a native app.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/components/TextInput/index.native.tsx#L20
We leverage Keyboard.dismiss() which comes with a side effect of also dismissing focus. https://reactnative.dev/docs/keyboard#dismiss

### What changes do you think we should make in order to solve the problem?
React native has a newer prop https://reactnative.dev/docs/textinput#showsoftinputonfocus that can be utilized to hide the keyboard without losing focus . We can implement this for the Timepicker component and pass it through to the Text component.

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 16:55
Sorry couldn't get to this, sooner 

I'm unavailable next week, Please assign a new C+ Issue here, proposals are ready for review.

cc: @slafortune

**Comment by situchan** [comment] 2024-01-28 03:45
I can take over

**Comment by slafortune** [comment] 2024-01-31 20:03
Sorry for my delay!  Assigned you now @situchan

**Comment by slafortune** [comment] 2024-02-05 18:14
@situchan will you get a chance to review that proposals today or tomorrow?

**Comment by situchan** [comment] 2024-02-08 11:27
@Krishna2323 yes that makes sense. Can we apply that solution to only the inputs that don't shwo hardware keyboard? (amount input, time input) So the the case when custom numpad shows

**Comment by situchan** [comment] 2024-02-08 11:31
yes but I am checking possibility without introducing new prop

**Comment by situchan** [comment] 2024-02-08 15:39
I don't see straightforward way without introducing new prop. I think that's fine.

**Comment by situchan** [comment] 2024-02-08 15:39
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/35120#issuecomment-1913457762) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2024-02-08 16:53
This seems to be working just fine on v1.4.38. Can you double check?

**Comment by situchan** [comment] 2024-02-08 17:05
I just retested. Still reproducible on android

**Comment by pecanoro** [comment] 2024-02-08 17:43
Yes, you can't see the cursor but it is still focused, as soon as I type a number, it gets inserted in the right place so I think we can just close this since t's super minor.

**Closed** 2024-02-08 17:44 UTC
Labels: External, Daily, Bug

**Comment by situchan** [comment] 2024-02-08 18:08
Actually it gets inserted in wrong place.

@pecanoro please check this weird behavior:

https://github.com/Expensify/App/assets/108292595/16049173-0467-468e-895d-6c10cf4a2f5a

**Comment by pecanoro** [comment] 2024-02-08 20:41
I still think it's super minor and we should focus on bigger issues.
