### ISSUE TITLE
[HOLD] [$500] FAB - Save the world - Public Room #teachers-unite 's name is editable after adding " I am teacher"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26689] opened 2023-09-04 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note : Follow the steps sequentially
1. Fab -> save the world -> I know a teacher
2. Enter name and email
3. Go to #teachers-unite room details ->settings-> room name
Notice that it's un - editable.
4. Now again go to fab button -> I am a teacher ( not I know a teacher this time) .
5. Enter details
6. Now repeat step 3, but notice #teachers-unite room name is editable.

## Expected Result:
Public Room #teachers-unite 's name should not be editable after adding " I am teacher" .
if any user can edit  room's name it would be problem in authenticity. like one day the room displays as something and other day some other thing.

## Actual Result:
Public Room #teachers-unite 's name is editable after adding " I am teacher"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/51a44f54-22de-4bf3-b161-dbb8a5765968

https://github.com/Expensify/App/assets/115492554/3bac8bff-660a-4146-9f84-5039aa402e2d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693402157846629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adbd5db85be8c4f1</li>
        <li>Upwork Job ID: 1699179095998455808</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-09-04 16:34
Issue is not reproducible in Production

https://github.com/Expensify/App/assets/115492554/570bcdc4-ebd6-45cb-b502-d054d977227b

**Comment by ashimsharma10** [comment] 2023-09-04 16:37
@izarutskaya Please go through the slack post. And yeah it was occurred in DEV latest-main

**Comment by ashimsharma10** [comment] 2023-09-04 16:58
HAve reproduce this issue in Prod too. its weird, I thought I checked it before and didn't happen. Apologies for that.

https://github.com/Expensify/App/assets/43598308/95819b2b-04d1-4a82-b3ac-e820ea827ac7

**Comment by garrettmknight** [comment] 2023-09-04 17:12
Reproduced on prod, that's a weird one.

**Comment by izarutskaya** [comment] 2023-09-04 17:58
Now I can't use the option "I'm a teacher", I see the "Update your email address" page 
Staging - build v1.3.63-0
Production - v1.3.62-4

https://github.com/Expensify/App/assets/115492554/397c8853-29e9-4cb8-8a4c-38ca175374bb

**Comment by pecanoro** [comment] 2023-09-04 18:34
Hmm, I can't reproduce with the same steps:

![image](https://github.com/Expensify/App/assets/6474442/2a77929d-720a-4a9c-9201-58efe435eef6)

**Comment by pecanoro** [comment] 2023-09-04 18:36
Oh wait, that is the workspace. Hmm, but i don't get added to any public room

**Comment by ashimsharma10** [comment] 2023-09-04 18:42
> Oh wait, that is the workspace. Hmm, but i don't get added to any public room

Have you reproduced? 
Being added to rooms is a different issue. I think u mixed it up . 😂

**Comment by pecanoro** [comment] 2023-09-04 18:51
Still can't reproduce:

![image](https://github.com/Expensify/App/assets/6474442/1206a48b-c51c-4c35-b92c-74b4d45cac79)

**Comment by pecanoro** [comment] 2023-09-04 19:02
Asked internally to see if someone else can

**Comment by ashimsharma10** [comment] 2023-09-04 19:09
@pecanoro, 
Step 1 and 2 are important. 
First go to " I know a teacher" -> fill details and,
Go to " I am a teacher" -> and then only check the room # teacher-unite

**Comment by pecanoro** [comment] 2023-09-04 19:27
Yes, I followed those steps, still I can't reproduce it

**Comment by johnmlee101** [comment] 2023-09-04 19:44
I cannot reproduce

**Comment by pecanoro** [comment] 2023-09-04 19:52
@ashimsharma10 Please make sure you can still reproduce in the last version (v1.3.63-0). I am going to close since no one can reproduce it.

**Comment by ashimsharma10** [comment] 2023-09-04 20:19
@pecanoro @johnmlee101  Please look at this. 
Video contains two new accounts 1.  staging ( v1.3.63-0) and 2. prod(v1.3.62-4). 

https://github.com/Expensify/App/assets/43598308/ad1c5f44-c568-4b15-8216-b8d281141013

**Comment by ashimsharma10** [comment] 2023-09-04 20:33
@pecanoro @johnmlee101 Please look at this.
Video contains two new accounts 1. staging ( v1.3.63-0) and 2. prod(v1.3.62-4).

https://github.com/Expensify/App/assets/43598308/5f5f7be3-cb46-4ccb-8d61-c724052f7ee5


https://github.com/Expensify/App/assets/43598308/f0e39838-047a-41ff-8baa-d5f61d2df2ce

**Comment by johnmlee101** [comment] 2023-09-04 20:54
Is there a prerequisite beta that might be giving different results? I created a new expensifail account for this, but wondering if maybe that's captured on a beta? @pecanoro did you also use expensifail?

**Comment by ashimsharma10** [comment] 2023-09-04 21:03
@johnmlee101 can u please record the video? 
I'm pretty sure . Some steps are missed.

Cause I did reproduced in chrome/safari and desktop in all prod, staging, DEV ( all  lastest versions)

**Comment by garrettmknight** [comment] 2023-09-05 08:12
Tested on v1.3.63-0 and I can still repro with these steps:
1. sign up
2. save the world > I know a teacher > fill out
3. save the world > I'm a teacher > fill out
4. go to the TU workspace room (not the one created by 'I'm a teacher') > settings > room name is editable

https://github.com/Expensify/App/assets/1529980/a82cf7c3-03b2-489a-9617-9c2a5451cc8a

**Comment by mountiny** [comment] 2023-09-05 18:05
Reproduced in prod so not a blocker

**Comment by pecanoro** [comment] 2023-09-05 21:45
This is why I could not reproduce it, it's happening due to optimistic data, as soon as it gets the right one, the field is not editable, so if you take a couple of seconds to open it, it will be the right one.

https://github.com/Expensify/App/assets/6474442/18cadd45-cbfb-4c33-99bf-36b0c998b556

**Comment by pecanoro** [comment] 2023-09-05 21:53
@youssef-lr @marcochavezf Tagging here you both so you can check the weird behavior at the end of the video. I think it could be external but not so sure.

**Comment by pecanoro** [comment] 2023-09-06 00:05
Got it! Yeah, there was something pretty odd going on here.

**Comment by pecanoro** [comment] 2023-09-06 02:30
Hmm, are you sure it's the back-end? It seems to return the right data. I feel it's happening before on the front-end and not after:

![image](https://github.com/Expensify/App/assets/6474442/e26af056-347d-49d7-9d03-6a5b01abc2f9)

**Comment by youssef-lr** [comment] 2023-09-08 02:43
@pecanoro sorry this is something we missed in the PR review, we were setting the policy owner incorrectly which made this [condition](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L3331) fail. I'm OOO currently can you take over the PR please?

**Comment by youssef-lr** [comment] 2023-09-08 02:47
@allroundexperts I'm not sure, the command returns the correct policy owner

<img width="600" alt="Screenshot 2023-09-08 at 03 46 56" src="https://github.com/Expensify/App/assets/9680864/269fd406-049a-487d-9b59-82d842855ca2">

**Comment by pecanoro** [comment] 2023-09-08 02:55
@youssef-lr Sure! I can take care!

**Comment by ashimsharma10** [comment] 2023-09-09 12:28
I think we should hold this. 
( as save the world option is not in latest builds)

**Comment by youssef-lr** [comment] 2023-09-11 02:23
Agreed.

**Comment by garrettmknight** [comment] 2023-10-11 20:15
@youssef-lr what are we holding on so I can keep an eye on this one?

**Comment by garrettmknight** [comment] 2023-10-11 20:17
Taking off reviewing so KSV2 pings us if this goes overdue in the meantime.

**Comment by youssef-lr** [comment] 2023-10-11 20:20
I think this was fixed? I'll double check tomorrow.

**Comment by garrettmknight** [comment] 2023-10-16 16:15
@youssef-lr did you get around to testing this one?

**Comment by pecanoro** [comment] 2023-10-25 14:50
@youssef-lr Friendly bump so we can close it or not 😄

**Comment by youssef-lr** [comment] 2023-10-25 15:27
@garrettmknight Sorry completely missed your ping!

@pecanoro  looks like this is fixed. 

<img width="433" alt="Screenshot 2023-10-25 at 19 24 57" src="https://github.com/Expensify/App/assets/9680864/3304a3c4-4101-4c68-95c9-f4e9e8c3c193">

I came across another bug though while testing this,  as a new user to the workspace after signing up as a teacher, I'm able to add/remove members from the public room

<img width="380" alt="Screenshot 2023-10-25 at 19 26 07" src="https://github.com/Expensify/App/assets/9680864/722687e0-8153-4b4b-a2ef-07af9054a84a">

**Comment by pecanoro** [comment] 2023-10-26 19:23
@youssef-lr Ohh that is a fun one, I would post in #expensi-bugs so it gets a new bug report and so new proposals.

@garrettmknight Can you just pay @ashimsharma10 the reporting bonus and then we can simply close this one?

**Comment by garrettmknight** [comment] 2023-10-26 19:29
@ashimsharma10 offer sent - accept and I'll pay.

Offer for my reference: https://www.upwork.com/en-gb/ab/applicants/1717624073224028160/suggested

**Comment by pecanoro** [comment] 2023-11-06 16:47
Closing since payment has been handled!

**Closed by pecanoro** 2023-11-06 16:47 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
