### ISSUE TITLE
[$250] QBO UK - Menu in "Export out-of-pocket expenses as" is blank before the connection syncs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45202] opened 2024-07-10 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706870
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition
QBO UK connection is established in the workspace
The connection is not synced yet
1. Navigate to workspace settings > Accounting
2. Click on Export >Export out-of-pocket expenses as
3. Observe the second menu in the setting

## Expected Result:
The item field in the setting is not empty and has the title of "Accounts payable"

## Actual Result:
The second item which is "Accounts payable" only appears when syncing is complete and is blank before syncing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5c1dcbd0-df51-4502-9fd4-0caab2e793fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b2c93b291a15c58</li>
        <li>Upwork Job ID: 1811856308645344493</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment] 2024-07-10 19:15
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sobitneupane** [comment] 2024-07-17 08:21
I could not reproduce the issue. Is there any specific steps to reproduce the issue?

**Comment by sobitneupane** [comment] 2024-07-17 08:57
I just added QBO account and tested the issue.

> The connection is not synced yet

How can I achieve the connection is not synced yet state?

**Comment by abekkala** [comment] 2024-07-19 15:45
@sobitneupane can you address the above from @tienifr

**Comment by sobitneupane** [comment] 2024-07-22 09:07
Thanks for the proposals.

[Proposal](https://github.com/Expensify/App/issues/45202#issuecomment-2226870212) from @tienifr looks good.

🎀👀🎀 C+ reviewed

**Comment by puneetlath** [comment] 2024-07-22 15:18
>But maybe BE does not set it when connecting QBO. This issue is reported in https://github.com/Expensify/App/pull/41638#issuecomment-2142893013.

Is this something that needs to be fixed on the back-end?

**Comment by puneetlath** [comment] 2024-07-22 15:36
@aldo-expensify @hayata-suenaga do you have an opinion on that ^?

**Comment by aldo-expensify** [comment] 2024-07-22 22:44
> > I wouldn't implement some FE fix that shows some inputs as selected when the configuration in onyx really doesn't have them selected,
> 
> My solution does not do that. It just hide this [component](https://github.com/Expensify/App/blob/3e164ed8c44dfc1da284195ee387c5f6cad9a66d/src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx#L74-L83) if `reimbursableExpensesExportDestination` is `undefined`.

ahh, I misunderstood that.

> > that would make bugs hard to see later and doesn't add much values besides deceiving the user

> The solution does not make the bug hard to see because, in future, if we do not see this [component](https://github.com/Expensify/App/blob/3e164ed8c44dfc1da284195ee387c5f6cad9a66d/src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx#L74-L83), we know that we have the problem in BE, and we can fix it in BE without affecting user's experience.

 don't see much value in hiding the input when this happens, I think we should just focus in the root cause and fix that.

**Comment by aldo-expensify** [comment] 2024-07-23 01:15
> @aldo-expensify
> 
> * I agree we just need to fix in BE size. But when this [component](https://github.com/Expensify/App/blob/3e164ed8c44dfc1da284195ee387c5f6cad9a66d/src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseConfigurationPage.tsx#L64-L72), in this case maybe the `reimbursableExpensesExportDestination` is not set. Can you help confirm the expected behavior in that case?

I think is not valid for `reimbursableExpensesExportDestination` to be unset, so there is no expected behaviour for me

**Comment by trjExpensify** [comment] 2024-07-29 12:22
This issue doesn't seem isolated to the specific config mentioned in the OP. See how pretty much none of the data is there because something happened with the connection sync: 

![Image](https://github.com/user-attachments/assets/13e98029-f266-45b5-9954-702efb8da23f)

[This PR](https://github.com/Expensify/App/pull/45041.) merged recently, I wonder if it's helped. The proposal is [here](https://github.com/Expensify/App/issues/44225#issuecomment-2196376399) for ref.

**Comment by aldo-expensify** [comment] 2024-08-02 18:54
> https://github.com/Expensify/App/pull/45041 merged recently, I wonder if it's helped. The proposal is https://github.com/Expensify/App/issues/44225#issuecomment-2196376399 for ref.

Maybe!, I think we should test if this is still reproducible. Was it easy to reproduce before? or very random?

**Comment by trjExpensify** [comment] 2024-08-05 09:18
Added the retest-weekly label to have Applause retest to try and reproduce.

**Comment by mvtglobally** [comment] 2024-08-09 04:32
Issue is reproducible during KI retests, when you go to "Export >Export out-of-pocket expenses as" before QBO sync

https://github.com/user-attachments/assets/3314c65d-912b-461f-978a-23846531b40b

**Comment by dannymcclain** [comment] 2024-08-09 14:20
Yeah I'm pretty sure we decided to wait to show all that stuff until the connection has finished syncing for the first time.

Example from NetSuite design doc:
![image](https://github.com/user-attachments/assets/f3fd0817-2b9d-448d-80ec-bd2e6daafbfe)

**Comment by trjExpensify** [comment] 2024-08-09 14:23
Okay cool, so I think we could use this issue to implement that? I suspect that's frontend, but maybe @aldo-expensify can confirm.

**Comment by aldo-expensify** [comment] 2024-08-09 16:58
I'm not sure of what type of solution was implemented to have that, do we know who worked on that?

**Comment by trjExpensify** [comment] 2024-08-09 17:31
@hungvu193 @rushatgabhane @mananjadhav might know!

**Comment by hungvu193** [comment] 2024-08-12 08:48
I didn't implement that logic but I think we're using the same logic for all 4 connections so far:

https://github.com/Expensify/App/blob/334c270ade52030a9468afa0ed506036a8ede1a8/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L439

**Comment by trjExpensify** [comment] 2024-08-13 01:48
Ah, that's helpful. Following the blame it was @mananjadhav, I believe.

**Comment by trjExpensify** [comment] 2024-08-15 17:48
So @aldo-expensify @hungvu193 @mananjadhav can this be external then?

**Comment by aldo-expensify** [comment] 2024-08-15 18:15
I'm a bit confused because the code @hungvu193 pointed out is supposed to apply to all types of connections, so that can't be what fixed the problem for other connections, or can it be?

**Comment by trjExpensify** [comment] 2024-08-15 18:22
Good question, I don't know. @mananjadhav would be great for you to chime in here, please. Thanks!

**Comment by abekkala** [comment] 2024-08-20 13:32
@mananjadhav can you review this please and provide your input?

**Comment by mananjadhav** [comment] 2024-08-20 15:08
Sorry this didn't show up in K2. I'll check this in a while.

**Comment by mananjadhav** [comment] 2024-08-20 18:13
Just went through the whole conversation. So when we did start the development we weren't hiding any menu options. With [this PR](https://github.com/Expensify/App/pull/45583), I implemented hiding the extra menu items (ie Netsuite Subsidiary and Xero Organization names).  But IIRC when the initial sync isn't finished we don't show up and it worked as expected [here](https://github.com/Expensify/App/issues/45202#issuecomment-2278061183).

Now there are two questions I have here:

1. When we say `before sync` here, did we check `isEmptyObject(policy?.connections)` is true?
2. @tienifr's video [here](https://github.com/Expensify/App/issues/45202#issuecomment-2232921350), the QBO connection shows successful with the last sync timestamp. So it does seem to be BE sync issue?

**Comment by trjExpensify** [comment] 2024-09-09 15:23
Did @yuwenmemon's PR fix this, or is there more to do? (A.K.A - why is this still open? 😄).

**Comment by yuwenmemon** [comment] 2024-09-09 18:00
Yeah I think we can close

**Closed by yuwenmemon** 2024-09-09 18:00 UTC
Labels: Reviewing, Weekly, Internal, Bug

**Comment by trjExpensify** [comment] 2024-09-10 10:31
Oh, sorry @sobitneupane. I missed that was an /App PR. 

Payment summary as follows: 

- $250 to @sobitneupane for the PR review

Go ahead and request on NewDot!

**Comment by garrettmknight** [comment] 2024-10-23 09:39
$250 approved for @sobitneupane
