### ISSUE TITLE
[Hold for payment 2024-08-26] [$250] iOS - Chat - App crashes when adding a space at the end of hyperlink text while editing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45623] opened 2024-07-17 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4732111
**Issue reported by:**Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send message with any hyperlink, e.g. link.com
4. Edit the message
5. Try to add space at the end of link.com text part of hyperlink

## Expected Result:
Space should be appended at the end of hyperlink text

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/55da63de-a72a-44f0-82ec-56cb714a9ee4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01765448d1b685d840</li>
        <li>Upwork Job ID: 1813943785653464004</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103339219</li>
<li>dominictb | Contributor | 103353044</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment] 2024-07-17 17:37
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-17 17:37
We think that this bug might be related to #vip-vsp

**Comment by twisterdotcom** [comment] 2024-07-18 14:27
Is odd. Going to put this in live markdown though.

**Comment by twisterdotcom** [comment] 2024-07-18 15:21
No, on Android it isn't an issue, although it never saves the extra space.

**Comment by twisterdotcom** [comment] 2024-07-23 12:40
The reason I made it weekly is that it's a very niche flow. We can make it daily, but I don't think it will necessarily help it get done quicker.

**Comment by tomekzaw** [comment] 2024-07-31 06:02
@dominictb's root cause analysis from https://github.com/Expensify/App/issues/45623#issuecomment-2247727495 is correct.

In order to get rid of the crash itself, we'll need to remove the following line in `react-native-live-markdown`: https://github.com/Expensify/react-native-live-markdown/blob/main/parser/index.ts#L273

However, the formatting will be still incorrect (e.g. no bold here):
<img width="484" alt="Screenshot 2024-07-31 at 07 59 44" src="https://github.com/user-attachments/assets/c15488d8-355b-4888-893c-85ba0040282a">

So we'll also need to find a way to preserve original whitespace when converting Markdown to HTML in `expensify-common` here: https://github.com/Expensify/expensify-common/blob/bd29e1c7a6ae4955cd39e35de586a1cd6fbadeaa/lib/ExpensiMark.ts#L262

**Comment by tomekzaw** [comment] 2024-07-31 07:15
@dominictb If we trim Markdown `[link ](link.com)`, we get the following HTML: `<a href="link.com">link</a>`

Then, when we convert HTML `<a href="link.com">link</a>`, we get the following Markdown: `[link](link.com)`.

We lost the space during this process. Currently, Live Markdown parser relies on the fact that the whitespace is preserved.

**Comment by tomekzaw** [comment] 2024-07-31 07:44
I don't know

**Comment by twisterdotcom** [comment] 2024-07-31 11:01
@tomekzaw or @dominictb - want me to assign you two to this as well?

**Comment by tomekzaw** [comment] 2024-07-31 11:16
I think this can be made external as this is not caused by `react-native-live-markdown` – instead this needs to be addressed in `expensify-common`.

**Comment by twisterdotcom** [comment] 2024-07-31 21:08
Do we need to assign @dominictb then? Confused how this will be fixed.

**Comment by DylanDylann** [comment] 2024-08-01 08:17
@tomekzaw Thanks for your support

@dominictb Let's remove the console and make a change on `Expensify-common` to address this bug as mentioned in your [proposal](https://github.com/Expensify/App/issues/45623#issuecomment-2247727495)

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-08-05 05:26
@dominictb Could you provide an ETA for the PR?

**Comment by tomekzaw** [comment] 2024-08-05 08:58
We can trim spaces only if `shouldKeepRawInput` option is set to `true`.

**Comment by DylanDylann** [comment] 2024-08-05 09:27
@tomekzaw Could you please provide more detailed information about your point? Thanks.

**Comment by DylanDylann** [comment] 2024-08-05 09:47
@tomekzaw Thanks so much

@dominictb Please ping me when the change is ready

**Comment by DylanDylann** [comment] 2024-08-05 10:24
@Gonals [This PR](https://github.com/Expensify/expensify-common/pull/773) is ready for review

**Comment by DylanDylann** [comment] 2024-08-08 02:53
Not overdue. Reviewing PR

**Comment by tomekzaw** [comment] 2024-08-09 12:22
https://github.com/Expensify/react-native-live-markdown/pull/449 has just been merged

**Comment by muttmuure** [comment] 2024-08-15 09:47
I can't get the auto-assigner to kick in, but I've pinged @mountiny

**Comment by twisterdotcom** [comment] 2024-08-21 16:44
Is this for https://github.com/Expensify/App/pull/47199#issuecomment-2296965475? This was deployed to prod 2 days ago, so we should add `[Hold for payment 2024-08-26]` right?

**Comment by twisterdotcom** [comment] 2024-08-26 21:17
I am OOO and will be back for payment on Thurs.

**Comment by DylanDylann** [comment] 2024-09-10 07:46
@twisterdotcom Kindly bump on payment

**Comment by twisterdotcom** [comment] 2024-09-10 21:32
Sorry this slipped through the cracks. Payment Summary:

- @DylanDylann paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103339219) (C+)
- @dominictb paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103353044) (Contributor)

**Closed by twisterdotcom** 2024-09-10 21:32 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
