### ISSUE TITLE
[$250] Invoice - Receiver can send and pay their own invoice when receiver is also workspace admin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47174] opened 2024-08-09 14:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Invite User B to workspace and promote User B to admin.
3. [User A] Send an invoice to User B from the same workspace in Step 2.
4. [User B] Go to invoice room.
5. [User B] Click + > Send invoice.
6. [User B] Send an invoice in the same workspace chat as invoice receiver.
7. [User B] Note that User B can send and pay their own invoice. Error will show up if User B pays their own invoice as business for the second time.

## Expected Result:
User B (invoice receiver and also admin of the workspace) should not be able to pay the invoice that User B sends.

## Actual Result:
User B (invoice receiver and also admin of the workspace) is able to pay the invoice that User B sends.
When User B pays their own invoice as business for the second time, error shows up.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/58fd96d7-77ff-4297-9b9f-15a6758806a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01267eba2b7c7cce57</li>
        <li>Upwork Job ID: 1825637731328105082</li>
        <li>Last Price Increase: 2024-11-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment] 2024-08-09 15:00
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment] 2024-08-09 15:00
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment] 2024-08-10 12:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receiver can send and pay their own invoice when receiver is also workspace admin.
### What is the root cause of that problem?
We are not checking if the user is the sender or not.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/MoneyReportHeader.tsx#L112

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/ReportActionItem/ReportPreview.tsx#L300

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/libs/actions/IOU.ts#L6796-L6841
### What changes do you think we should make in order to solve the problem?
Checking for the user is the sender can help resolve this issue.


### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment] 2024-08-12 19:10
Reviewing now

**Comment by OfstadC** [comment] 2024-08-14 19:28
Sorry - I haven't been able to set this up to test it - will figure this out by EOD

**Comment by OfstadC** [comment] 2024-08-16 20:04
This is [expected behavior](https://expensify.slack.com/archives/CSL3XBCCR/p1723761648194729?thread_ts=1723750346.569799&cid=CSL3XBCCR). If the submitter is an admin, they'll have the option to pay.

**Comment by OfstadC** [comment] 2024-08-19 20:55
We're actually going to fix this

**Comment by OfstadC** [comment] 2024-08-21 20:16
Looks like we have one proposal so far for review 😃

**Comment by OfstadC** [comment] 2024-08-26 19:33
@shubham1206agra Can you review the listed proposals? Thank you!

**Comment by OfstadC** [comment] 2024-08-27 18:12
@shubham1206agra if you can update by EOD please 🙏 - Thank you 😃

**Comment by OfstadC** [comment] 2024-08-28 12:31
Asked [here](https://expensify.slack.com/archives/C9YU7BX5M/p1724848276890089) 😃

**Comment by kavimuru** [comment] 2024-08-28 14:27
There are 2 bugs here. 
Bug 1: User B (invoice receiver and also admin of the workspace) is able to pay the invoice that User B sends.
Bug 2: When User B pays their own invoice as business for the second time, error shows up.
Now only can repro Bug 1

https://github.com/user-attachments/assets/f1e0fe86-aebd-43c2-9440-811f323af229

**Comment by OfstadC** [comment] 2024-09-03 13:14
Yes @shubham1206agra we don't want the invoice sender to be able to pay their own invoice 😃

**Comment by MuaazArshad** [comment] 2024-09-03 13:58
@shubham1206agra We also have my proposal https://github.com/Expensify/App/issues/47174#issuecomment-2281454348 .

**Comment by MuaazArshad** [comment] 2024-09-03 16:36
### Proposal Updated

- Added Details
- Added both possible solutions

**Comment by MuaazArshad** [comment] 2024-09-03 16:39
@daledah with due respect your condition 
```
if (managerID !== userAccountID) {
            return false;
        }
```
is quite the opposite.
The function should return false when the user is the manager.`managerID === userAccountID`

**Comment by MuaazArshad** [comment] 2024-09-05 16:18
@shubham1206agra bump!

**Comment by OfstadC** [comment] 2024-09-09 13:01
@shubham1206agra Could you update by EOD? Thank you! 😃

**Comment by MuaazArshad** [comment] 2024-09-10 15:13
> Sorry, but both proposals are wrong. I will bump on Slack for more proposals.

My proposal works perfectly. It allows the admin to pay the invoice and prevents users from paying their own invoice.

**Comment by MuaazArshad** [comment] 2024-09-12 15:28
@shubham1206agra bump!

**Comment by OfstadC** [comment] 2024-09-18 14:28
CC @davidcardoza incase you can assist with this question - https://github.com/Expensify/App/issues/47174#issuecomment-2352859330

**Comment by davidcardoza** [comment] 2024-09-24 17:02
Sorry I am not entirely clear what the question is. Can you please restate the problem?

**Comment by trjExpensify** [comment] 2024-09-24 23:14
I totally missed these pings for some reason as well, my bad. Same boat as Doza, I don't really understand what we're doing in this issue or what the problem is.

**Comment by davidcardoza** [comment] 2024-09-26 01:34
I think I am following, referencing the OP the problem seems to be this:

>User B (invoice receiver and also admin of the workspace) is able to pay the invoice that User B sends.

In short, users can currently pay their own invoices, which we should prevent. Let’s lock this down by hiding the "Pay" button in the IOU preview from the invoice sender.

**Comment by MuaazArshad** [comment] 2024-10-01 16:58
@shubham1206agra bump!

**Comment by davidcardoza** [comment] 2024-10-02 04:53
In your example you stated "[User A] Send an invoice to User B from the same workspace in Step 2." So in this case User A sent an invoice, so they shouldn't be able to pay their invoice. Perhaps you can record a new flow of this issue occurring to help us better conceptualize the workflow. That would be helpful.

**Comment by OfstadC** [comment] 2024-10-04 13:14
I've asked Applause [here](https://expensify.slack.com/archives/C9YU7BX5M/p1728047681214399)

**Comment by m-natarajan** [comment] 2024-10-04 13:49
In step 7:
 [User B] Note that User B can send and pay their own invoice. - Able to reproduce this still
 Error will show up if User B pays their own invoice as business for the second time. - Not reproduced now.
Video:

https://github.com/user-attachments/assets/57098024-631f-4f6c-b661-958889f0ff5b

**Comment by OfstadC** [comment] 2024-10-08 13:56
Any further update @shubham1206agra ? 😃

**Comment by OfstadC** [comment] 2024-10-10 18:17
Bump @shubham1206agra

**Comment by MuaazArshad** [comment] 2024-10-21 15:29
Bump @shubham1206agra @OfstadC

**Comment by OfstadC** [comment] 2024-10-22 17:21
We don't want anyone to be able to pay their **own** invoice. ([Slack convo](https://expensify.slack.com/archives/CSL3XBCCR/p1723750346569799))

**Comment by OfstadC** [comment] 2024-10-30 13:54
I think I might be confused about where we are stuck here 😅

**Comment by davidcardoza** [comment] 2024-11-01 15:01
@Shubham Agrawal From what I’m seeing, it seems that we should restrict a user from paying invoices they send within the same workspace to prevent confusion or errors. Let me know if that aligns with your understanding or if there’s anything further to clarify!

**Comment by davidcardoza** [comment] 2024-11-05 03:17
Yes we should fix that and open up the ability to pay an invoice to other admins in the invoice room.

**Comment by davidcardoza** [comment] 2024-11-06 00:56
@madmax330 moving this to internal, let me know if you think it can be handled with an external contributor still.

**Comment by OfstadC** [comment] 2024-11-07 22:52
Thanks for all your help here @davidcardoza !

**Comment by davidcardoza** [comment] 2024-11-07 23:54
@cristipaval I feel like this actually might be more of a cleanup item for invoicing v1. What do you think?

**Comment by cristipaval** [comment] 2024-11-08 12:05
I'm not sure I understand the problem here. I'll comment on the reproducing steps and I need someone to confirm please.

> 1. Go to staging.new.expensify.com
> 2. [User A] Invite User B to workspace and promote User B to admin.
> 3. [User A] Send an invoice to User B from the same workspace in Step 2.

Ok, so now we have a b2c invoice room, where User B is an individual receiver. This is what we expect so there is no issue here.

> 4. [User B] Go to invoice room.
> 5. [User B] Click + > Send invoice.
> 6. [User B] Send an invoice in the same workspace chat as the invoice receiver.

Ok, the company still can invoice the admin as an individual, I see no problem here.

> 7. [User B] Note that User B can send and pay their own invoice. Error will show up if User B pays their own invoice as business for the second time.

The individual receiver (who happens to be an admin of the sender) can pay the invoice as an individual. I still see no problem. 
Now, if they want to pay as a business, the backend throws because we can't have a B2B invoice room where both the sender and receiver are the same company. Which is expected.

**Comment by cristipaval** [comment] 2024-11-13 07:42
@shubham1206agra, what do you think about my comment from above?

**Comment by cristipaval** [comment] 2024-11-15 08:27
Oh, I see in the bug's screen recording that userB could upgrade the invoice room, and as a result, the workspace became both the sender and the receiver of the invoices, which shouldn't be allowed.

I just opened an [Auth PR](https://github.com/Expensify/Auth/pull/13180) to fix that.

**Comment by cristipaval** [comment] 2024-11-18 09:48
We're waiting for the [Auth PR](https://github.com/Expensify/Auth/pull/13180) to hit staging before continuing on this.

**Comment by cristipaval** [comment] 2024-11-18 09:50
Not overdue, Melv.

**Comment by cristipaval** [comment] 2024-11-22 09:19
The backend is fixed. @shubham1206agra Could you please check whether there is any other work needed on the front-end?

**Comment by cristipaval** [comment] 2024-11-22 11:06
@shubham1206agra thanks for checking!
[This](https://github.com/Expensify/App/issues/47174#issuecomment-2464595419) is the expected behaviour.

**Comment by Beamanator** [comment] 2024-11-25 13:27
Very possibly! Let's ask @cristipaval since he was involved in the PRs for this issue

**Comment by OfstadC** [comment] 2024-12-02 13:41
Was out for the Holiday - working on this today. 

This one has been ongoing for quite awhile and @shubham1206agra helped keep pushing this one forward/investigating. So I think $250 is still valid here. But please note here if you disagree. 

I'll issue offer/payment this afternoon if no concerns.

**Comment by OfstadC** [comment] 2024-12-02 19:03
Payment Summary:

- @shubham1206agra [paid](https://www.upwork.com/nx/wm/workroom/39138896/overview) $250 via Upwork

**Closed** 2024-12-04 14:03 UTC
Labels: Daily, Internal, Help Wanted, Bug
