### ISSUE TITLE
Web - Popover menu is displayed over 'Drop to upload' overlay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26553] opened 2023-09-02 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Right-click on of the sent message & verify that popover menu is opened
3. Drag an image to the report section

## Expected Result:
Popover menu should close when 'Drop to upload' overlay is displayed

## Actual Result:
Popover menu remains opened after 'Drop to upload' overlay is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4b7ffbe8-baa8-4541-8077-ab023d96e36b

https://github.com/Expensify/App/assets/93399543/f52046e5-0b95-4eb7-a361-4404773feb70

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693203912703329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment] 2023-09-02 18:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Popover menu is displayed over 'Drop to upload' overlay

### What is the root cause of that problem?
We are not closing the Popover when a file is dragging over hiding under the overlay might resolve this issue but there's another issue that is when a file is dragover on popver Drop Ui wont appear at all


https://github.com/Expensify/App/assets/104348397/a68a5e73-8030-43be-9061-c638bb8864df

### What changes do you think we should make in order to solve the problem?
To resolve the issue, we need to close popover when a file is dragging over.
Add this to [ReportActionItem](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js)
```JSX
 const {isDraggingOver} = useContext(DragAndDropContext);
 useEffect(() => {
        if (isDraggingOver) {
            ReportActionContextMenu.hideContextMenu();
        }
    }, [isDraggingOver]);
```

**Comment by conorpendergrast** [comment] 2023-09-04 10:14
I reproduced this now.

![image](https://github.com/Expensify/App/assets/5802477/595c28dd-183f-4a16-8b98-10baf4b2955e)


![image](https://github.com/Expensify/App/assets/5802477/7c1d3ceb-3c08-4b83-a506-44fe58c45893)

**Comment by conorpendergrast** [comment] 2023-09-04 10:18
@Natnael-Guchima do you have any thing to reference that shows that this is a bug, rather than by-design? If so, please add that here and I'll reopen to review that!

**Closed by conorpendergrast** 2023-09-04 10:18 UTC
Labels: Daily, Bug

**Comment by ishpaul777** [comment] 2023-09-04 10:28
@conorpendergrast Slack dont accept a drop if a popover is open.In my humble opinion, the current behaviour looks odd. As it partially accepts drop if a popover is open.
https://github.com/Expensify/App/assets/104348397/a68a5e73-8030-43be-9061-c638bb8864df
