### ISSUE TITLE
[$500] Not found is shown when deeplinking to expense details

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#37083] opened 2024-02-22 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**v1.4.43-11
**Reproducible in staging?:**y
**Reproducible in production?:**y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:**

## Action Performed:
Break down in numbered steps
1. Having account A and B send a money request from A to B
2. With account A, open the expense details and copy the URL
3. Paste the URL in a fresh new window and sign in with account A again

## Expected Result:
Describe what you think should've happened
Expense details page should load

## Actual Result:
Describe what actually happened
A not found view is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Reloading the page works

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16493223/db09a1a1-3bd6-456b-a5f3-976c4856b47a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01715c671a688b4a3b</li>
        <li>Upwork Job ID: 1760748556818485248</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @deetergp</details>

**Comment by shahinyan11** [comment] 2024-02-22 14:02
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
The `OpenReport` is called before the `subscribeToUserEvents` function and so that we receive the report data in response but the `Onyx` data is not updated.
**Let me explain the above statement:**
[Here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/actions/OnyxUpdates.ts#L137C1-L139C6) we are disabling update client data if `lastUpdateIDAppliedToClient` is `false`
The `last update id` is set in the `subscribeToUserEvents` function on [this](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/actions/User.ts#L604C13-L604C40) line . And the `subscribeToUserEvents` function is called in two places ( [here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L86C13-L86C42) and [here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L186) ) . It turns out that the `subscribeToUserEvents` function needs to be called before any endpoint which should update client data (In our case `OpenReport`).
### What changes do you think we should make in order to solve the problem?
1. Add the `lastUpdateIDAppliedToClient` key  in [withOnyx](https://github.com/Expensify/App/blob/2fc1d5385d3d13f0aae11e0329870a57929dd564/src/pages/home/ReportScreen.js#L605C5-L605C13)
```
lastUpdateIDAppliedToClient: {
    key: ONYXKEYS.ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT,
},
```
2. Add check `&& lastUpdateIDAppliedToClient` in [this](https://github.com/Expensify/App/blob/2fc1d5385d3d13f0aae11e0329870a57929dd564/src/pages/home/ReportScreen.js#L497C14-L503C35) condition
```
(!wasReportAccessibleRef.current &&
      !firstRenderRef.current &&
      !report.reportID &&
      !isOptimisticDelete &&
      !reportMetadata.isLoadingInitialReportActions &&
      !isLoading &&
      !userLeavingStatus &&
      lastUpdateIDAppliedToClient) ||
```
3. Add new `useEffect` in ReportScreen
```
useEffect(()=>{
  fetchReportIfNeeded();
}, [lastUpdateIDAppliedToClient])
```
### What alternative solutions did you explore? (Optional) (edited)

**Comment by shahinyan11** [comment] 2024-02-22 14:09
> But if you could extract the part that makes sense to this one.

Now I'll add the extracted version here to make it easier to understand

**Comment by shahinyan11** [comment] 2024-02-22 14:09
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Not found is shown when deeplinking to expense details
### What is the root cause of that problem?
The `OpenReport` is called before the `subscribeToUserEvents` function and so that we receive the report data in response but the `Onyx` data is not updated.
**Let me explain the above statement:**
[Here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/actions/OnyxUpdates.ts#L137C1-L139C6) we are disabling update client data if `lastUpdateIDAppliedToClient` is `false`
The `last update id` is set in the `subscribeToUserEvents` function on [this](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/actions/User.ts#L604C13-L604C40) line . And the `subscribeToUserEvents` function is called in two places ( [here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L86C13-L86C42) and [here](https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L186) ) . It turns out that the `subscribeToUserEvents` function needs to be called before any endpoint which should update client data (In our case `OpenReport`).
### What changes do you think we should make in order to solve the problem?
1. Add the `lastUpdateIDAppliedToClient` key  in [withOnyx](https://github.com/Expensify/App/blob/2fc1d5385d3d13f0aae11e0329870a57929dd564/src/pages/home/ReportScreen.js#L605C5-L605C13)
```
lastUpdateIDAppliedToClient: {
    key: ONYXKEYS.ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT,
},
```
2. Add check `&& lastUpdateIDAppliedToClient` in [this](https://github.com/Expensify/App/blob/2fc1d5385d3d13f0aae11e0329870a57929dd564/src/pages/home/ReportScreen.js#L497C14-L503C35) condition
```
(!wasReportAccessibleRef.current &&
      !firstRenderRef.current &&
      !report.reportID &&
      !isOptimisticDelete &&
      !reportMetadata.isLoadingInitialReportActions &&
      !isLoading &&
      !userLeavingStatus &&
      lastUpdateIDAppliedToClient) ||
```
3. Add new `useEffect` in ReportScreen
```
useEffect(()=>{
  fetchReportIfNeeded();
}, [lastUpdateIDAppliedToClient])
```
### What alternative solutions did you explore? (Optional) (edited)

**Comment by paultsimura** [comment] 2024-02-23 00:05
Hey @s77rt, would you like to take this one over as a C+ since you've worked on the original issue?🙏 
I really want to wrap up my ongoing Contributor PRs this week before fully emerging into the C+ role.

**Comment by s77rt** [comment] 2024-02-23 02:48
@paultsimura Sure!  Taking this as C+

**Comment by s77rt** [comment] 2024-02-23 03:32
@shahinyan11 Thanks for the proposal. The RCA seems incomplete. I have some questions/concerns:
1. If `lastUpdateIDAppliedToClient` is `false` then `doesClientNeedToBeUpdated` will be `true` and this will make our `SaveResponseInOnyx` middleware defer the updates and not just ignore them [^1]. The updates are eventually applied by `OnyxUpdateManager` [^2]. Why are we still not seeing the report in Onyx?
2. The report updates come from the `OpenReport` http response. What does the pusher events (and `subscribeToUserEvents` function) have to do here?



[^1]: https://github.com/Expensify/App/blob/72bdedb226d0813a68e2b8caa909194064ed92a9/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L45
[^2]: https://github.com/Expensify/App/blob/72bdedb226d0813a68e2b8caa909194064ed92a9/src/libs/actions/OnyxUpdateManager.ts#L87-L93

**Comment by bernhardoj** [comment] 2024-02-23 06:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page is shown when open transaction thread report after login

### What is the root cause of that problem?
Summary: The onyx data from the OpenReport request isn't applied because the data is considered outdated.

When we open (deeplink) a report after login, there are 2 requests are made, OpenApp and OpenReport. OpenApp is a read request, so both requests are run in parallel. When the OpenReport request finishes first, `OnyxUpdates.doesClientNeedToBeUpdated` will return true 

https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L45

because `lastUpdateIDAppliedToClient` doesn't exist yet, the OpenReport **response** is saved to `ONYX_UPDATES_FROM_SERVER`.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdates.ts#L136-L139

_if OpenApp finishes first, this issue won't happen_

This will trigger a ReconnectApp request.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdateManager.ts#L59-L75

ReconnectApp will return a `lastUpdateID` and the response will be applied immediately (`requestsToIgnoreLastUpdateID` contains ReconnectApp & OpenApp)
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L42

After it's done, the saved OpenReport response is processed.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdateManager.ts#L87-L88

However, the OpenReport `lastUpdateID` is smaller than the `lastUpdateIDAppliedToClient` (that is updated from ReconnectApp `lastUpdateID`)
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdates.ts#L81-L85

so the response data is ignored.

### What changes do you think we should make in order to solve the problem?

I think ideally we should wait for the OpenApp request to be finished first before doing the OpenReport request because ReconnectApp doesn't return all report that a user has.

To achieve that, first we need to change the OpenApp API from READ to WRITE, just like [we did for ReconnectApp](https://github.com/Expensify/App/pull/12125), so it's processed sequentially.

However, this isn't enough because OpenApp is called after a promise and onyx connection which delays the call.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L210-L216
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L149-L158 

To solve this, we can follow a similar pattern of the promise here
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L80-L87

```
let resolveIsOpenAppCalledPromise: () => void;
const isOpenAppCalled = new Promise<void>((resolve) => {
    resolveIsOpenAppCalledPromise = resolve;
});

function waitForOpenApp() {
    return isOpenAppCalled;
}
```

Then, we will resolve the promise once the OpenApp/ReconnectApp api is pushed to the queue
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L214-L215
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L242-L243

_why ReconnectApp too? because [ReconnectApp will be called instead of OpenApp if we already logged in previously](https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L194-L198)_

Or we can resolve the promise immediately when the `ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT` exists.

```
Onyx.connect({
    key: ONYXKEYS.ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT,
    callback: (val) => {
        if (val) resolveIsOpenAppCalledPromise();
    },
});
```

Then, we will wait for the promise here:
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/Report.ts#L724-L727

```
App.waitForOpenApp(() => // open report request)
```

**Comment by rlinoz** [comment] 2024-02-23 14:08
Oh, that wasn't my intention, just switching the C+ per this [comment](https://github.com/Expensify/App/issues/37083#issuecomment-1960661906)

**Comment by s77rt** [comment] 2024-02-23 18:51
@bernhardoj Thanks for the proposal. Your RCA is correct. Regarding the solution:

> To achieve that, first we need to change the OpenApp API from READ to WRITE, just like https://github.com/Expensify/App/pull/12125, so it's processed sequentially.

After doing that, will the `OpenReport` request wait for the `OpenApp` to finish if the `OpenReport` request type is `makeRequestWithSideEffects` and not `read`?

**Comment by s77rt** [comment] 2024-02-24 11:58
@bernhardoj If we deeplink into a report the `OpenReport` request type would be `makeRequestWithSideEffects` thus it won't wait for `OpenApp`

https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/Report.ts#L719-L727

**Comment by bernhardoj** [comment] 2024-02-24 13:01
Yes, that would be intentional since `isFromDeepLink` is only true when we open the report while logged out (to open the public room). If we wait, then we won't be able to open a public room.

**Comment by s77rt** [comment] 2024-02-24 18:04
@bernhardoj In that case you suggestion solution shouldn't work as we won't wait for `OpenApp` after all.

**Comment by bernhardoj** [comment] 2024-02-26 05:40
We don't need to wait for OpenApp (or specifically `lastUpdateIDAppliedToClient`) when opening a public room because it's not a WRITE request, so `doesClientNeedToBeUpdated` will always be false. 
https://github.com/Expensify/App/blob/89d5689978d3a50c86ae9c9da00dcff875eb9220/src/libs/actions/OnyxUpdates.ts#L130-L134
https://github.com/Expensify/App/blob/89d5689978d3a50c86ae9c9da00dcff875eb9220/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L42

**Comment by shahinyan11** [comment] 2024-02-26 16:28
> @shahinyan11 Thanks for the proposal. The RCA seems incomplete. I have some questions/concerns:
> 
> 1. If `lastUpdateIDAppliedToClient` is `false` then `doesClientNeedToBeUpdated` will be `true` and this will make our `SaveResponseInOnyx` middleware defer the updates and not just ignore them [1](#user-content-fn-1-ab5f677ffa79e9c5376d42e54e882f76). The updates are eventually applied by `OnyxUpdateManager` [2](#user-content-fn-2-ab5f677ffa79e9c5376d42e54e882f76). Why are we still not seeing the report in Onyx?
> 2. The report updates come from the `OpenReport` http response. What does the pusher events (and `subscribeToUserEvents` function) have to do here?

Sorry. I mixed up some files and went the wrong way

**Comment by shahinyan11** [comment] 2024-02-26 16:28
## Proposal
[Updated](https://github.com/Expensify/App/issues/37083#issuecomment-1959529602)

**Comment by s77rt** [comment] 2024-02-26 18:00
@bernhardoj That's not entirely true and contradicts with your RCA. `OpenReport` does return `previousUpdateID` (treated as a WRITE request). In this case we need to wait for `OpenApp` otherwise the onyx update will be just ignored.

I have noticed that `OpenReport` sometimes return `previousUpdateID` and sometimes it does not. I see we have a chance of fixing this in the BE.

**Comment by s77rt** [comment] 2024-02-26 18:00
@shahinyan11 Thanks for the update. The RCA makes sense but the suggested solutions are workarounds.

**Comment by s77rt** [comment] 2024-02-26 18:06
🎀 👀 🎀 C+ reviewed

This could be internal. Can you please check when or what are the cases where `OpenReport` would return `previousUpdateID` in its response? 

It seems that if we remove `previousUpdateID` from the server's response we could fix the bug as `doesClientNeedToBeUpdated` will be `false` in this case.

https://github.com/Expensify/App/blob/87eeb99d93568a96decb59aeba1025516a61d58f/src/libs/actions/OnyxUpdates.ts#L130-L134

**Comment by s77rt** [comment] 2024-02-26 18:10
@deetergp Adding to the above ^  I _think_ `OpenReport` should return `previousUpdateID` only if we are creating a new report. In our case here we are not, we are accessing a report that already exists, thus `previousUpdateID` should not be a part of the response.

**Comment by bernhardoj** [comment] 2024-02-27 03:25
@s77rt can you try again checking the response? I don't see `previousReportID` when opening a public room while logged out.

<img width="540" alt="image" src="https://github.com/Expensify/App/assets/50919443/c93bd41d-2f8c-4133-a045-af0342e0c6a5">

**Comment by garrettmknight** [comment] 2024-02-29 19:29
@deetergp can you help confirm if this needs to be internal via [this comment](https://github.com/Expensify/App/issues/37083#issuecomment-1964805887) when you get a chance?

**Comment by deetergp** [comment] 2024-03-01 20:00
@s77rt Getting rid of `previousUpdateID` is a non-starter. It's part of our Reliable Updates initiative and is only going to show up in more places as we move where we send onyx updates from our PHP layer, further back into our C++ layer.

**Comment by s77rt** [comment] 2024-03-02 18:55
@deetergp I'm not suggesting the removal of `previousUpdateID` as whole. According to this comment https://github.com/Expensify/App/blob/87eeb99d93568a96decb59aeba1025516a61d58f/src/libs/actions/OnyxUpdates.ts#L131 that field should only be present if the request is a write request. `OpenReport` command can act as both a write and a read request, write request if creating a new report and a read request otherwise.

Example 1: Response when reading an existing report
<img width="859" alt="Screenshot 2024-03-02 at 7 35 51 PM" src="https://github.com/Expensify/App/assets/16493223/46ead463-f5b0-486b-9192-d42fa143c5c7">

Example 2: Response when creating a new report (chat with a user you have not chatted with before, etc.)
<img width="859" alt="Screenshot 2024-03-02 at 7 38 40 PM" src="https://github.com/Expensify/App/assets/16493223/18cd8012-5f34-4514-9209-9a9435be2f3b">


The problem is that we are encountering a case where we are **reading** an existing report (the money request report) yet get the `previousUpdateID` field which is unexpected. What I'm asking for is to check why is that field present i.e. why is the request treated as a **write** request?

**Comment by Julesssss** [comment] 2024-03-05 14:52
Hey @deetergp, it seems possible that [this](https://github.com/Expensify/App/issues/37756) newly raised bug is a dupe of this issue, would you agree?

**Comment by garrettmknight** [comment] 2024-03-05 19:25
@tienifr nice catch - agreed that this is a dupe of https://github.com/Expensify/App/issues/34528. @shahinyan11 please add your proposal there if you'd still like to put it forward.

**Closed by garrettmknight** 2024-03-05 19:25 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
