### ISSUE TITLE
[$500] mWeb-Compose- Copy to clipboard the text with markdown&paste in composer, markdown not shown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28701] opened 2023-10-03 09:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on any report which contains message (text+markdown like # or*)
3. Long press the message and tap edit comment
4. Note the markdown (#) and text is shown in edit compose box
5. Tap close button
6. Long press the(text+markdown)message and tap copy to clipboard
7. Paste the message in the compose box

## Expected Result:
Copy to clipboard the text with markdown(#) & pasting it in the compose box, both markdown (#) and text must be shown.

## Actual Result:
Copy to clipboard the text with markdown(#) & pasting it in the compose box, markdown is not shown, only text is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e1066de4-9617-44b1-aa24-22f5d36b9dcb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016116512afb48aa0d</li>
        <li>Upwork Job ID: 1710438482925531136</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by Talha345** [comment] 2023-10-03 19:32
This is not a bug because we are not copying the mark down source code just the text.For e.g you can copy any of the text above in the issue report template above and paste it anywhere.Only the text will be copied and not the markdown code.

**Comment by strepanier03** [comment] 2023-10-04 17:49
I think we should retain the formatting of copied text, so the background markdown should be copied IMO. I raised [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1696441733128259) for consensus.

**Comment by strepanier03** [comment] 2023-10-06 23:35
Moving this forward to help generate more consensus on the convo started [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1696441733128259).

**Comment by Talha345** [comment] 2023-10-09 12:26
@parasharrajat I read your comment on Slack but could not understand it properly.Can you please explain what should be the expected behaviour in your opinion?

**Comment by Talha345** [comment] 2023-10-09 16:56
> I was trying to bring back a few past conclusions but I don't remember the whole discussion so it was just a summary. But we have to worry about the following important things. 
> 
> 1. On the Web, we have to support two paste methods.
>     i. Paste  (with HTML)
>     ii. Paste and match style.  (only the text part).
> 

@parasharrajat Just to clarify, so you mean when a user copies a text and tries to paste it back in the chat,there should be 2 options given,one to only paste the text only and other to paste the text along with the markdown code?

**Comment by Talha345** [comment] 2023-10-10 12:09
@strepanier03 Just checked this on production and this bug does not exist on production anymore.

**Comment by strepanier03** [comment] 2023-10-12 23:36
Thank you for the heads up @Talha345 - I'll test again as well.

**Comment by strepanier03** [comment] 2023-10-20 20:19
Got it, closing now and we can reopen if needed in the future.

**Closed by strepanier03** 2023-10-20 20:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
