### ISSUE TITLE
[HOLD for payment 2024-12-17] [HOLD for facebook/react-native#46411[$250] iOS - Chat - Composer not auto scrolled to the bottom when editing message with 10 line breaks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48122] opened 2024-08-27 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4895266
**Email or phone of affected tester (no customers):**  applausetester+ak827@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Navigate to a DM
3. Send a message with 10 line breaks
4. Edit the message

## Expected Result:
Compose box should be auto scrolled to the bottom of the message, the end of the message should be visible.
Cursor should be placed at the end of the message

## Actual Result:
Compose box is not auto scrolled to the end of the message, 6th is the last line visible to the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b88133ed-09cc-4e08-9944-01fc889c14ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c809bc476538a5ae</li>
        <li>Upwork Job ID: 1828571296040895701</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104134700</li>
<li>dominictb | Contributor | 104134702</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment] 2024-08-27 20:37
Production:

https://github.com/user-attachments/assets/6c7611c7-712d-4811-843e-fea58714c94d

**Comment by deetergp** [comment] 2024-08-27 23:12
Nothing in the deploy checklist jumps out at me as the cause of this. But I also think it isn't significant enough to block on, so I am going to remove the blocker label, set to Daily, and make it External.

**Comment by bigshoesdev** [comment] 2024-08-28 02:51
I will use a combination of ref and the setNativeProps method to programmatically set the cursor position.

**Comment by NJ-2020** [comment] 2024-08-28 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Chat - Composer not auto scrolled to the bottom when editing message with 10 line breaks
### What is the root cause of that problem?
We do not wrap the compose text input inside the ScrollView and we do not auto scroll to the end inside the input
### What changes do you think we should make in order to solve the problem?
We can wrap the compose input inside the ScrollView and link the ScrollView to useRef and invoke the scrollEnd function 
`scrollViewRef.current?.scrollToEnd({ animated: true })`

### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment] 2024-09-04 23:03
Not overdue - @dominictb is working on a PR

**Comment by trjExpensify** [comment] 2024-09-10 01:04
This is just a pure chat bug, moving to #vip-vsb.

**Comment by deetergp** [comment] 2024-09-10 18:22
Since this is an upstream bug and out of our control, I'm going to demote it to weekly and check back at that cadence.

**Comment by deetergp** [comment] 2024-11-18 20:23
Well, it's not fixed yet in our application, so I don't think we can should be closing this one out yet.

**Comment by VictoriaExpensify** [comment] 2024-11-28 02:35
Not overdue

**Comment by deetergp** [comment] 2024-12-20 18:40
Hey @shubham1206agra 👋 @VictoriaExpensify was OOO this week but will be back on Monday and will process payment then.

**Comment by VictoriaExpensify** [comment] 2024-12-22 21:02
@shubham1206agra 's offer had expired and I couldn't reissue it under the old job posting as that has also expired. So I have created a new job posting and issued you both new offers @shubham1206agra and @dominictb - can you please accept these so I can process your payments?

**Comment by VictoriaExpensify** [comment] 2024-12-31 00:34
Job posting - https://www.upwork.com/ab/applicants/1870936775495338411/hired

**Comment by VictoriaExpensify** [comment] 2024-12-31 00:36
Payment summary:

Contributor: @dominictb paid $250 via Upwork
C+: @shubham1206agra paid $250 via Upwork

**Closed by VictoriaExpensify** 2024-12-31 00:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
