### ISSUE TITLE
[HOLD for payment 2024-04-25] Taxes - id_TAX_EXEMPT appears in the list when there are more than 8 tax rates

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39825] opened 2024-04-08 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Collect workspace has more than 8 tax rates
- Tax exempt (0%) is the workspace currency default
1. Go to staging.new.expensify.com
2. Go to Collect workspace chat
3. Start manual request flow
4. In confrimation page, click Show more > Taxes

## Expected Result:
The selected default tax exempt will appear on top

## Actual Result:
id_TAX_EXEMPT appears at the top of the list. This issue only occurs when there are more than 8 tax rates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ff52b4f8-6d8e-44a0-9b4a-0fb553a47249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-08 14:01
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-04-08 14:02
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment] 2024-04-08 15:04
@SzymczakJ @jjcoffee are you able to take a look at this?

**Comment by srikarparsi** [comment] 2024-04-08 18:12
Working on testing if reverting the TS migration fixes the issue

**Comment by srikarparsi** [comment] 2024-04-08 18:54
Able to reproduce on latest main:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/2adde5e3-541b-4cfd-918a-c62664db6184">

Trying to roll back TS migration and test again.

**Comment by srikarparsi** [comment] 2024-04-08 19:16
Hey @luacmartins and @MonilBhavsar, saw that you demoted this [tax issue](https://github.com/Expensify/App/issues/39838#issuecomment-2043248551) since it's coming from a new [feature](https://github.com/Expensify/App/pull/33927). This one seems very related as the code that's causing the discrepancy is [selectedTaxRate](https://github.com/Expensify/App/blob/1b6c99317492ad9e68518837df2bc59afd720556/src/pages/iou/request/step/IOURequestStepTaxRatePage.tsx#L51). Should we demote this one as well?

I'm currently working on trying to revert the [TS Migration PR](https://github.com/Expensify/App/pull/39059) in case it's related to that but am not able to do it on Web so trying to do it locally. But wanted to ask in the meantime.

**Comment by srikarparsi** [comment] 2024-04-08 19:39
Figured out a fix [here](https://github.com/Expensify/App/pull/39857)

**Comment by srikarparsi** [comment] 2024-04-08 22:12
Still looking at this, I've been having VM problems so it's taking a little longer. Thought I had resolved them but still occurring.

**Comment by srikarparsi** [comment] 2024-04-08 22:34
I narrowed it down to this [sections](https://github.com/Expensify/App/blob/7e78bdb05805b296d4d3c9fb782b80be89bf4911/src/components/TaxPicker.tsx#L63) variable. When printed, it has id_TAX_EXEMPT as it's own sections and the remaining taxes in a different section.

I also found that when you select a different tax value and then the default tax exempt one, the bug no longer exists. So maybe it's something to do with a different id?

**Comment by srikarparsi** [comment] 2024-04-08 22:38
The bug also doesn't exist for less than 8 tax rates because of this block [here](https://github.com/Expensify/App/blob/7e78bdb05805b296d4d3c9fb782b80be89bf4911/src/libs/OptionsListUtils.ts#L1389)

**Comment by teneeto** [comment] 2024-04-09 07:09
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take care of this issue.

**Comment by teneeto** [comment] 2024-04-09 07:15
This issue is currently handled in this PR: https://github.com/Expensify/App/pull/39723

**Comment by srikarparsi** [comment] 2024-04-09 07:18
Ah cool, see that you had a similar fix 

`const moneyRequestSelectedTaxRate = transaction?.taxRate?.keyForList || (taxRates && TransactionUtils.getDefaultTaxName(taxRates));`

Assigning you to the issue

**Comment by MonilBhavsar** [comment] 2024-04-09 07:21
Demoting this issue from blocker, as we need to have atleast 8 tax options and it's a specific case.

**Comment by teneeto** [comment] 2024-04-09 11:13
PR is merged

**Comment by puneetlath** [comment] 2024-04-26 14:50
Payment summary: 
- Reviewer: @allroundexperts owed $250 via NewDot


Thanks everyone!

**Closed by puneetlath** 2024-04-26 14:50 UTC
Labels: Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-06-17 19:51
$250 approved for @allroundexperts
