### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] mWeb/safari - Emoji-  Previous row with emoji is not displayed when adding emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11462] opened 2022-09-30 01:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report
3. Click on emoji icon on composer
4. Fill the entire row with emojis

## Expected Result:
All lines with emojis must be visible in emoji icon on composter

## Actual Result:
If a row is filled with emojies and I add another one, the previous row with emojies is not visible.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Safari

**Version Number:** 1.2.10.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193171491-71578e42-459f-4617-b121-1a308e47887a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2022-09-30 16:22
> If a row is filled with emojies and I add another one, the previous row with emojies is not visible.

This is just because there is not enough space on the current line and it needs to put it on a new line right? Not sure if I'm missing something but that seems like correct functionality 

cc @kbecciv

**Comment by thesahindia** [comment] 2022-09-30 16:51
@thienlnam, I think the composer should expand.

**Comment by thienlnam** [comment] 2022-09-30 16:52
Ah gotcha, yeah I think you're right - this can likely be solved externally

**Comment by adelekennedy** [comment] 2022-09-30 20:12
[internal](https://www.upwork.com/ab/applicants/1575941424736378880/job-details)
[external](https://www.upwork.com/jobs/~01a0289fcc77afb96b)

**Comment by mollfpr** [comment] 2022-10-01 17:26
### Proposal

**Root cause**
When adding the emoji from the picker, the composer is not updating the `numberOfLines` of the input. the `onChange` is not triggered when adding an emoji.

**Solution**
1. Adding new props to the composer component `shouldUpdateNumberOfLines` and `onUpdateNumberOfLines`. These props are used to trigger the update number of lines function.
2. Add new state to `ReportActionCompose` and `ReportActionItemMessageEdit`. `textInputShouldUpdateNumberOfLines` is pass to the composer component, update the value after adding an emoji and after updating the number of lines of the input.

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 37c951ca8..1c7a4e9ff 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -35,9 +35,13 @@ const propTypes = {
     /** If the input should clear, it actually gets intercepted instead of .clear() */
     shouldClear: PropTypes.bool,

+    shouldUpdateNumberOfLines: PropTypes.bool,
+
     /** When the input has cleared whoever owns this input should know about it */
     onClear: PropTypes.func,

+    onUpdateNumberOfLines: PropTypes.func,
+
     /** Callback to fire when a file has being dragged over the text input & report body */
     onDragOver: PropTypes.func,

@@ -81,7 +85,9 @@ const defaultProps = {
     maxLines: -1,
     onPasteFile: () => {},
     shouldClear: false,
+    shouldUpdateNumberOfLines: false,
     onClear: () => {},
+    onUpdateNumberOfLines: () => {},
     style: null,
     onDragEnter: () => {},
     onDragOver: () => {},
@@ -169,7 +175,7 @@ class Composer extends React.Component {
             this.setState({numberOfLines: 1});
             this.props.onClear();
         }
-        if (prevProps.defaultValue !== this.props.defaultValue
+        if ((!prevProps.shouldUpdateNumberOfLines && this.props.shouldUpdateNumberOfLines) || prevProps.defaultValue !== this.props.defaultValue
             || prevProps.isComposerFullSize !== this.props.isComposerFullSize) {
             this.updateNumberOfLines();
         }
@@ -360,6 +366,7 @@ class Composer extends React.Component {
             this.setState({
                 numberOfLines,
             });
+            this.props.onUpdateNumberOfLines();
         });
     }

```

```diff
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index 4977d8cdd..56fae5f9c 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -135,6 +135,7 @@ class ReportActionCompose extends React.Component {
             isFocused: this.shouldFocusInputOnScreenFocus,
             isFullComposerAvailable: props.isComposerFullSize,
             textInputShouldClear: false,
+            textInputShouldUpdateNumberOfLines: false,
             isCommentEmpty: props.comment.length === 0,
             isMenuVisible: false,
             selection: {
@@ -216,6 +217,10 @@ class ReportActionCompose extends React.Component {
         this.setState({textInputShouldClear: shouldClear});
     }

+    setTextInputShouldUpdateNumberOfLines(shouldNumberOfLines) {
+        this.setState({textInputShouldUpdateNumberOfLines: shouldNumberOfLines});
+    }
+
     /**
      * Updates the visibility state of the menu
      *
@@ -326,6 +331,7 @@ class ReportActionCompose extends React.Component {
             },
         }));
         this.updateComment(newComment);
+        this.setTextInputShouldUpdateNumberOfLines(true);
     }

     /**
@@ -637,7 +643,9 @@ class ReportActionCompose extends React.Component {
                                         onBlur={() => this.setIsFocused(false)}
                                         onPasteFile={displayFileInModal}
                                         shouldClear={this.state.textInputShouldClear}
+                                        shouldUpdateNumberOfLines={this.state.textInputShouldUpdateNumberOfLines}
                                         onClear={() => this.setTextInputShouldClear(false)}
+                                        onUpdateNumberOfLines={() => this.setTextInputShouldUpdateNumberOfLines(false)}
                                         isDisabled={isComposeDisabled || isBlockedFromConcierge}
                                         selection={this.state.selection}
                                         onSelectionChange={this.onSelectionChange}
```

```diff
diff --git a/src/pages/home/report/ReportActionItemMessageEdit.js b/src/pages/home/report/ReportActionItemMessageEdit.js
index 49a442e9b..8587f78a9 100644
--- a/src/pages/home/report/ReportActionItemMessageEdit.js
+++ b/src/pages/home/report/ReportActionItemMessageEdit.js
@@ -74,6 +74,7 @@ class ReportActionItemMessageEdit extends React.Component {

         this.state = {
             draft: draftMessage,
+            textInputShouldUpdateNumberOfLines: false,
             selection: {
                 start: draftMessage.length,
                 end: draftMessage.length,
@@ -90,6 +91,10 @@ class ReportActionItemMessageEdit extends React.Component {
         this.setState({selection: e.nativeEvent.selection});
     }

+    setTextInputShouldUpdateNumberOfLines(shouldNumberOfLines) {
+        this.setState({textInputShouldUpdateNumberOfLines: shouldNumberOfLines});
+    }
+
     /**
      * Update the value of the draft in Onyx
      *
@@ -165,6 +170,7 @@ class ReportActionItemMessageEdit extends React.Component {
             },
         }));
         this.updateDraft(newComment);
+        this.setTextInputShouldUpdateNumberOfLines(true);
     }

     /**
@@ -197,6 +203,8 @@ class ReportActionItemMessageEdit extends React.Component {
                         }}
                         onChangeText={this.updateDraft} // Debounced saveDraftComment
                         onKeyPress={this.triggerSaveOrCancel}
+                        onUpdateNumberOfLines={() => this.setTextInputShouldUpdateNumberOfLines(false)}
+                        shouldUpdateNumberOfLines={this.state.textInputShouldUpdateNumberOfLines}
                         value={this.state.draft}
                         maxLines={16} // This is the same that slack has
                         style={[styles.textInputCompose, styles.flex4, styles.editInputComposeSpacing]}
```

**Result**


https://user-images.githubusercontent.com/25520267/193421059-3d4d781b-8d30-4874-9482-3ecc3a7ea9b8.mov


https://user-images.githubusercontent.com/25520267/193421064-aac239fe-3e97-44b3-a42e-a1d063210436.mov

**Comment by thesahindia** [comment] 2022-10-05 12:27
@mollfpr, I don't think we would require that many changes. I believe this can be done without adding a new state and `onUpdateNumberOfLines`. Please see if you can update the proposal with a better approach.

Waiting for better proposal.

**Comment by thesahindia** [comment] 2022-10-07 14:08
@adelekennedy,  Should we double to get more 👀

**Comment by mollfpr** [comment] 2022-10-07 16:42
### Updated proposal
Since we migrate from `setNativeProps` and use controlled input. We can remove the `onChange` to update the number of lines and use the controlled props value to call `this.updateNumberOfLines()`.

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 37c951ca8..4bbc69104 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -169,7 +169,8 @@ class Composer extends React.Component {
             this.setState({numberOfLines: 1});
             this.props.onClear();
         }
-        if (prevProps.defaultValue !== this.props.defaultValue
+        if (prevProps.value !== this.props.value
+            || prevProps.defaultValue !== this.props.defaultValue
             || prevProps.isComposerFullSize !== this.props.isComposerFullSize) {
             this.updateNumberOfLines();
         }
@@ -373,9 +374,6 @@ class Composer extends React.Component {
                 placeholderTextColor={themeColors.placeholderText}
                 ref={el => this.textInput = el}
                 selection={this.state.selection}
-                onChange={() => {
-                    this.updateNumberOfLines();
-                }}
                 onSelectionChange={this.onSelectionChange}
                 numberOfLines={this.state.numberOfLines}
                 style={propStyles}
```


https://user-images.githubusercontent.com/25520267/194604591-d318206c-452f-4b87-b9e3-f07b687c6cdf.mov


https://user-images.githubusercontent.com/25520267/194604623-731debdd-bb03-4404-b8f1-255020ffaf92.mov

**Comment by Puneet-here** [comment] 2022-10-07 18:05
### Proposal

The problem is that we use `updateNumberOfLines` for updating the lines at onChange but when we add an emoji we add it to the value and the value is passed to the composer so onChange doesn't work in that case. https://github.com/Expensify/App/blob/d7651e06fbb5d5807aba85b7b72dc9c6b96a9a4f/src/components/Composer/index.js#L376-L378 

https://github.com/Expensify/App/blob/d7651e06fbb5d5807aba85b7b72dc9c6b96a9a4f/src/components/Composer/index.js#L172

We need to check if new value is different from the prev value 
```js
 if (prevProps.value !== this.props.value 
     || prevProps.defaultValue !== this.props.defaultValue 
     || prevProps.isComposerFullSize !== this.props.isComposerFullSize) { 
     this.updateNumberOfLines(); 
} 
``` 
If we don't remove updateNumberOfLines from onChange the function will be called twice but if we remove it then the lines won't update in the case where we don't pass value to composer so I suggest that we check if this.props.value exists if it exists we will just return; else we will call updateNumberOfLines
we can add the logic to a different method and pass it to the onChange or we can do it directly in the onChange like this 
```js
               onChange={() => {
                    if(this.props.value){
                        return;
                    }
                    this.updateNumberOfLines();
                }}
```

https://github.com/Expensify/App/blob/d7651e06fbb5d5807aba85b7b72dc9c6b96a9a4f/src/components/Composer/index.js#L376-L378 

My proposal is same as @mollfpr but it also deals with the case when we doesn't pass value to the composer for example the composer at stories(the lines won't update there if we don't use remove onChange) and search input at emoji picker(we don't need to update the lines here but maybe in the future there can be cases where we use composer without passing value)

**Comment by adelekennedy** [comment] 2022-10-07 19:26
@thesahindia we're at that time! happy to double if we think we need more proposals

**Comment by thesahindia** [comment] 2022-10-07 22:03
I think the proposals above will do the job, so no need to double. I will review them in the morning (it's 3 a.m. for me right now 😶‍🌫️)

**Comment by thesahindia** [comment] 2022-10-08 19:55
Both the proposals are using the same approach to handle this but @Puneet-here's proposal also fixes a case which @mollfpr didn't include in their proposal. 

We call `updateNumberOfLines` at onChange for updating lines and we can call it at `componentDidUpdate` when value changes. The only problem will be in the case where we don't get any value from the parent @Puneet-here's proposal deals with it, so I feel it's a complete proposal.

C+ reviewed 🎀👀🎀

cc: @thienlnam for the final decision.

**Comment by mollfpr** [comment] 2022-10-09 01:58
I think the `Composer` meant to be controlled input so will have the props `value`. 

The other components that use `Composer` but not using multiline is emoji search input and I’m not understand we use `Composer` input than regular TextInput but the `updateNumberOfLines` is no use because it’s not multiline and I don’t think we will have the search input as multiline 🤔

**Comment by Puneet-here** [comment] 2022-10-09 09:44
> My proposal is same as @mollfpr but it also deals with the case when we doesn't pass value to the composer for example the composer at stories (the lines won't update there if we don't use use onChange to update lines)  and search input at emoji picker(we don't need to update the lines here but maybe in the future there can be cases where we use composer without passing value)

As I said here. the value prop isn't required, It will be a problem when we use composer without passing value in future (example for a page where we want multiline text input that increases in size)

**Comment by thienlnam** [comment] 2022-10-10 01:57
Thank you both for the great proposals, as mentioned @Puneet-here here has a more inclusive solution to the problem.

**Comment by mvtglobally** [comment] 2022-10-18 11:28
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2022-10-24 15:59
hired @Puneet-here @thesahindia

**Comment by Puneet-here** [comment] 2022-10-24 16:01
Accepted. Thanks!

**Comment by mvtglobally** [comment] 2022-10-24 18:36
Issue not reproducible during KI retests. (Second week)

**Closed** 2022-10-24 20:21 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
