### ISSUE TITLE
Invite member - App freezes for some seconds when opening Invite member list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#54489] opened 2024-12-24 00:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+909608@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is logged in with Expensifail account (many contacts)
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members
3. Click Invite members

## Expected Result:
Member list will open instantly (production behavior)

## Actual Result:
App freezes for some seconds when opening Invite member list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/32a684db-e5e9-472a-9e19-13bec4155294

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2024-12-24 20:32
Dupe of https://github.com/Expensify/App/issues/54529

**Closed by youssef-lr** 2024-12-24 20:32 UTC
Labels: DeployBlockerCash, Engineering, Hourly
