### ISSUE TITLE
An error occurs when attempting to attach a .PSD file in chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19989] opened 2023-06-01 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings,
2. Create a workspace,
3. Try to send a large file or a file with a PSD extension,(I tested it using a  file with a PSD extension. The same issue will occur if you try with other file types also)
4. Attempt to delete the attachment, and
5. An error message is displayed: "Unexpected error while posting the comment", "please try again later. We were unable to process this file", and "Auth UpdateReportComment returned an error."

## Expected Result:
When attempting to delete an attachment while sending it, the attachment should be successfully deleted

## Actual Result:
An error occurs when attempting to delete the attachment while sending it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (50).webm](https://github.com/Expensify/App/assets/93399543/4581fa6c-7dab-4fd6-bda8-4b62a0dcdf3e)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685375476950409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5517139f49544d2</li>
        <li>Upwork Job ID: 1664707196858548224</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-02 00:02
@kbecciv - for recent GH's that you've been creating, I have noticed you are not marking the platform checkboxes. Could you please do this? It is part of the issue.

**Comment by jliexpensify** [comment] 2023-06-02 01:10
This doesn't occur when deleting an attachment, it's because we currently cannot process a Photoshop file in New Expensify:

![image](https://github.com/Expensify/App/assets/30815269/ae97930e-56f2-446f-b263-4c1eae24e8f4)

**Comment by kbecciv** [comment] 2023-06-02 01:12
@jliexpensify Sure, will do!

**Comment by jliexpensify** [comment] 2023-06-02 01:16
Asking internally if we even want to process .PSD - https://expensify.slack.com/archives/C01SKUP7QR0/p1685668577085699

**Comment by youssef-lr** [comment] 2023-06-02 18:55
@mananjadhav Removing your assignment as this is gonna require a backend fix.

**Comment by jliexpensify** [comment] 2023-06-02 22:34
Thanks @youssef-lr , since this is a bug, I will need to pay $250 to @tewodrosGirmaA

**Comment by jliexpensify** [comment] 2023-06-04 22:56
@tewodrosGirmaA could you share your Upworks profile?

**Comment by tewodrosGirmaA** [comment] 2023-06-05 07:21
Thanks, @jliexpensify! Here's my Upwork profile: https://www.upwork.com/freelancers/~0142af0eda23e59363

**Comment by jliexpensify** [comment] 2023-06-05 07:27
Invite sent @tewodrosGirmaA

**Comment by tewodrosGirmaA** [comment] 2023-06-05 07:36
Hi, @jliexpensify, I accept it.

**Comment by tewodrosGirmaA** [comment] 2023-06-05 07:54
my contribution detail: 
my Expensify account email is:- isaacashenafi23@gmail.com (I use multiple accounts, but this is my main one), and                        my Upwork profile can be found at https://www.upwork.com/freelancers/~0142af0eda23e59363

**Comment by jliexpensify** [comment] 2023-06-06 01:45
@youssef-lr once I pay out the reporting bonus, can we close this GH? Or would you prefer to leave it open?

**Comment by youssef-lr** [comment] 2023-06-06 01:47
I think we can keep it open until the fix is on production.

**Comment by jliexpensify** [comment] 2023-06-08 22:52
Not overdue. @tewodrosGirmaA you have been paid and the job has been closed on Upworks.

**Comment by tewodrosGirmaA** [comment] 2023-06-09 04:37
@jliexpensify Thank You

**Comment by jliexpensify** [comment] 2023-06-19 04:08
Tested again today, still running into issues:

![image](https://github.com/Expensify/App/assets/30815269/77e62ea1-050e-451a-b878-062672a02d4c)

@youssef-lr could you link the PR here? Thanks!

**Comment by youssef-lr** [comment] 2023-06-21 20:16
Working on the PR today.

**Comment by youssef-lr** [comment] 2023-06-21 20:22
Working on the PR today.

**Comment by jliexpensify** [comment] 2023-06-24 04:19
Not overdue

**Comment by jliexpensify** [comment] 2023-06-26 21:43
No overdue

**Comment by jliexpensify** [comment] 2023-06-30 01:19
Bump @youssef-lr - can you link the PR?

**Comment by youssef-lr** [comment] 2023-07-05 17:49
PR on its way.

**Comment by jliexpensify** [comment] 2023-07-14 06:07
Not overdue!

**Comment by youssef-lr** [comment] 2023-07-14 22:51
Fix is live in production and can't reproduce this anymore. Clsoing!

**Closed by youssef-lr** 2023-07-14 22:51 UTC
Labels: Engineering, Weekly, Internal, Bug
