### ISSUE TITLE
[PAY 29/04] [$250] Remove deprecated `ReportActionUtils.getAllReportActions()` method

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#39091] opened 2024-03-27 18:56 UTC
This is coming from https://github.com/Expensify/App/issues/27262. You can read the issue description there to get the context behind the problem being solved and the mess being cleaned up.

# Problem
`ReportActionUtils.getAllReportActions()` is called from several view components and other action files which is an anti-pattern.

## Why this is important to fix
It maintains a more pure and exact flow of data through the react application. If the view is using report action data, then it needs to subscribe to the data in Onyx so that it's guaranteed that the data will never be stale or out-of-date.

# Solution
- Use `withOnyx()` to load the data in view components
- Use `Onyx.connect()` to load the data in other action files
- Remove the usage of `ReportUtils.getAllReportActions()` or at least prevent it from being exported by adding a test to https://github.com/Expensify/App/blob/main/tests/actions/EnforceActionExportRestrictions.ts
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01944da5c2a9fee46a</li>
        <li>Upwork Job ID: 1773061588854910976</li>
        <li>Last Price Increase: 2024-04-17</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>godofoutcasts94 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by godofoutcasts94** [comment] 2024-03-27 19:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Remove deprecated `ReportActionUtils.getAllReportActions()` method
### What is the root cause of that problem?
We have `ReportActionUtils.getAllReportActions()` in our codebase
### What changes do you think we should make in order to solve the problem?

we need to remove it `ReportActionUtils.getAllReportActions()`.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-27 19:25
Updated [Proposal](https://github.com/Expensify/App/issues/39091#issuecomment-2023786037)

**Comment by EzraEllette** [comment] 2024-03-27 19:25
## Proposed Solution:
1. Mark `getAllReportActions` as deprecated similarly to `getParentReport`
2. Remove export and add test.
3. Modify action files and view components to use `Onyx`.

**Comment by EzraEllette** [comment] 2024-03-27 19:27
Contributor details
Your Expensify account email: ezrasellette@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015fecd86e270cefef?mp_source=share

**Comment by godofoutcasts94** [comment] 2024-03-28 17:47
Updated [Proposal](https://github.com/Expensify/App/issues/39091#issuecomment-2023786037) with test step as well

**Comment by tgolen** [comment] 2024-04-04 16:30
@godofoutcasts94 Are you able to get a PR started for this?

**Comment by EzraEllette** [comment] 2024-04-04 16:31
@tgolen If there is a deadline you need to meet, I can deliver a PR by EOD.

**Comment by godofoutcasts94** [comment] 2024-04-04 16:33
Yes definitely today I will do it, I will start a draft PR. Actually, I was out somewhere I will start today itself.

**Comment by tgolen** [comment] 2024-04-04 16:36
There is no deadline for this. I was just seeing that it's a `daily` and hasn't had any updates in a few days so I am trying to push this forward. Generally, you should do one thing at a time and finish what you start before moving onto something else.

**Comment by godofoutcasts94** [comment] 2024-04-05 14:47
Added Draft [PR](https://github.com/Expensify/App/pull/39722)

**Comment by bfitzexpensify** [comment] 2024-04-09 15:08
Unassigned @godofoutcasts94

@Ollyws, which of the other proposals should we move forward with?

**Comment by EzraEllette** [comment] 2024-04-09 16:07
I'm still available to do this. Here is an updated proposal that follows the proposal standard:


## What is the root cause of that problem?
ReportActionUtils.getAllReportActions() is called from several view components and other action files which is an anti-pattern.

## What changes do you think we should make in order to solve the problem?
- Use `withOnyx()` to load the data in view components
- Use `Onyx.connect()` to load the data in other action files
- Remove the usage of `ReportUtils.getAllReportActions()` or at least prevent it from being exported by adding a test to https://github.com/Expensify/App/blob/main/tests/actions/EnforceActionExportRestrictions.ts

**Comment by EzraEllette** [comment] 2024-04-10 21:46
https://github.com/Expensify/App/pull/40046

**Comment by tgolen** [comment] 2024-04-17 17:36
I'm OK bumping it up to $250. Thanks for asking

**Comment by EzraEllette** [comment] 2024-04-18 21:53
Thanks!

**Comment by EzraEllette** [comment] 2024-04-24 03:10
Can someone trigger the bot to send me an offer on upwork?

**Comment by tgolen** [comment] 2024-04-24 11:36
Is the offer up here still valid? https://github.com/Expensify/App/issues/39091#issuecomment-2047561049

**Comment by EzraEllette** [comment] 2024-04-24 12:34
I already applied to that job. I wonder if it is still assigned to godofoutcasts?

**Comment by bfitzexpensify** [comment] 2024-04-25 01:49
I've hired you on Upwork @EzraEllette. 

Looks like the PR was deployed to prod two days ago. 

Updating this to daily and updating the title to reflect the payout date.

**Comment by bfitzexpensify** [comment] 2024-04-30 19:22
All done here.

**Closed by bfitzexpensify** 2024-04-30 19:22 UTC
Labels: Reviewing, External, Daily, Bug
