### ISSUE TITLE
[$500] [Distance] - Request money does not work with email & phone number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27070] opened 2023-09-08 21:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to + > request money > distance > choose start and end point > next
2. Observe it says name, email and phone number
3. Attempt to add an email. Verify you cannot create a request money report
4. Attempt to change the amount. Verify that you are unable to.
5. Attempt to add a phone number. Verify you cannot create a request money report

## Expected Result:
Since email and phone number are said to be accepted, request money reports should be created using both.

## Actual Result:
Email and phone number does not have reimbursement detail and hence, a report cannot be created but mentioning email and phone number can be misleading

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fdf8a1f3-096b-4652-b2f2-dae20b210519

https://github.com/Expensify/App/assets/93399543/621d8e52-358c-45dd-9d04-3346be289017

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693872152503239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01784d0162b22d689f</li>
        <li>Upwork Job ID: 1700253362770354176</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-11 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money does not work with email & phone number
### What is the root cause of that problem?
We already disable `includeP2P` in `getRequestOptions` which mean we can't send request to normal users.
https://github.com/Expensify/App/blob/f896f71a1ce00320a2ba029e44396d4e29b88223/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L92-L93
But in OptionsListUtils.js, we still send `userToInvite` while includeP2P = false, and send it base on `canInviteUser` only
https://github.com/Expensify/App/blob/f896f71a1ce00320a2ba029e44396d4e29b88223/src/libs/OptionsListUtils.js#L1044

### What changes do you think we should make in order to solve the problem?
We need to prevent send `userToInvite` when `includeP2P` is false [here](https://github.com/Expensify/App/blob/f896f71a1ce00320a2ba029e44396d4e29b88223/src/libs/OptionsListUtils.js#L1044).

```javascript
// userToInvite: canInviteUser ? userToInvite : null,
userToInvite: includeP2P && canInviteUser ? userToInvite : null,
```
### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment] 2023-09-11 14:24
hm, it looks like melv assigned sasha to this one first so i am going to un-assign myself from this one.

**Comment by sakluger** [comment] 2023-09-11 21:04
I think the issue here is that when you send a distance request to an email instead of to a workspace, there is no mileage rate set up. I'm going to post this in Slack to see if we've considered this case already.

**Comment by sakluger** [comment] 2023-09-11 23:32
This is a known limitation that we haven't built yet. I'm closing this in favor of https://github.com/Expensify/App/issues/23291 which is where we're building the functionality.

**Closed by sakluger** 2023-09-11 23:32 UTC
Labels: External, Daily, Help Wanted, Bug
