### ISSUE TITLE
[$500]  'Hmm its not here' displayed when refreshing expensify classic page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38865] opened 2024-03-23 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** shussain+web@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37955
## Action Performed:
1. Navigate to Settings - Switch to Expensify Classic
2. Choose any option
3. Click on the Next button
4. Verify input is auto-focused
5. Now refresh page

## Expected Result:
'Hmm its not here' should not be displayed when refreshing expensify classic page

## Actual Result:
'Hmm its not here' displayed when refreshing expensify classic page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5236a71e-9003-4167-a4b3-1c2c60c7d114

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c71608c41784a351</li>
        <li>Upwork Job ID: 1772068230275534848</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment] 2024-03-23 13:45
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by roryabraham** [comment] 2024-03-25 01:10
updated https://github.com/Expensify/App/pull/38856, this will be partially fixed by it. You'll no longer see `Hmmm its not here` but you will still see the account settings change to a report on refresh, which is unexpected. More changes would also be needed to fix this the rest of the way. Making this external

**Comment by roryabraham** [comment] 2024-03-25 01:13
assigning myself since this appears to be a bug in the exit survey, which I built. @GandalfGwaihir's proposal LGTM and tests well 👍🏼

**Comment by roryabraham** [comment] 2024-04-12 18:04
PR was merged through some mysterious GitHub anomaly - there was no internal GH approver and @MonilBhavsar claims he did not merge the PR 😕 

Anyways, there was an [bug reported](https://github.com/Expensify/App/pull/38856) on the PR, but I think it was fixed in https://github.com/Expensify/App/pull/38856.

So I want to do some extra testing but I think we're done here

**Comment by roryabraham** [comment] 2024-04-12 18:06
That bug is still reproducible, but it's separate from this one. We can proceed with payment here since this is fixed

**Comment by adelekennedy** [comment] 2024-04-12 18:16
Payment sent!

**Comment by adelekennedy** [comment] 2024-04-12 18:16
Does this GH need to be kept open @roryabraham?

**Closed by adelekennedy** 2024-04-12 18:16 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by roryabraham** [comment] 2024-04-15 20:35
reported bug the other bug: https://expensify.slack.com/archives/C049HHMV9SM/p1713213269308389

**Comment by roryabraham** [comment] 2024-04-15 21:47
Posted a link to your proposal in the slack thread where the bug was reported
