### ISSUE TITLE
All - Profile - Timezone selection is lost after saving the settings in the Profile menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27791] opened 2023-09-19 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a New Expensify app
2. Log in with @applause.expensifail.com account
3. Navigate to settings/profile/timezone
4. Turn off automatic location determination
5. Navigate to the Timezone list
6. Select different zones 3 times in turn and memorize the last one
7. Return to the Profile tab

## Expected Result:
The timezone selection is applied and does not change after saving the settings and returning to the Profile tab

## Actual Result:
Timezone selection is lost after saving the settings and returning to the Profile tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-7

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3fcb656f-ea07-4aa4-9741-e9a6eb280872

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2023-09-19 15:10
Not repro in Prod

https://github.com/Expensify/App/assets/115492554/f38bdd67-e32c-4df5-bda0-12fe43741463

**Comment by thienlnam** [comment] 2023-09-20 06:53
I don't think this is a blocker - I can't seem to reproduce, maybe it was just updating the timezone multiple times and the response updating the value?

**Comment by neil-marcellini** [comment] 2023-09-22 02:33
I'm going to un-assign since @abekkala needs to test reproduction and we'll likely close this. If C+ approves a proposal later you can re-assign me.

**Comment by abekkala** [comment] 2023-09-25 06:20
I was not able to reproduce

**Closed by abekkala** 2023-09-25 06:20 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
