### ISSUE TITLE
[$1000] Dev - "Pay with Expensify" button style is broken

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13687] opened 2022-12-19 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with account that has payWithExpensify, expensifyWallet beta enabled or able to pay via PayPal
2. Tap FAB menu -> Send money
3. Select currency as USD
4. Input any amount
5. Select any contact

## Expected Result: 
No white border around arrow on "Pay with Expensify" button

## Actual Result: 
There's white border around arrow on "Pay with Expensify" button

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.41-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![1](https://user-images.githubusercontent.com/43996225/208450607-e9aada25-27d1-4118-81f0-7dc2eab6703a.png)
![2](https://user-images.githubusercontent.com/43996225/208450613-e85f4b0e-f944-472c-ae23-3f59c682b561.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671442540501379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2c7bdef927162e8</li>
        <li>Upwork Job ID: 1604912631198826496</li>
        <li>Last Price Increase: 2022-12-19</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2022-12-19 16:15
What I'm seeing is slightly different. I see a white line between the button and the down arrow (on staging web, staging desktop, and iOS). 

<img width="353" alt="Screenshot 2022-12-19 at 11 12 10 AM" src="https://user-images.githubusercontent.com/1371996/208470228-a38bf900-decd-451e-8ed1-45e28353faca.png">

@Expensify/design can you confirm whether what I'm seeing is correct or a bug?

**Comment by grgia** [comment] 2022-12-19 17:53
Looks like it was caused by this PR https://github.com/Expensify/App/pull/13377

**Comment by grgia** [comment] 2022-12-19 18:15
https://user-images.githubusercontent.com/38015950/208491316-feec2d18-4efe-42e0-a0f2-a339d6edd2f6.mov

cc @shawnborton @marcaaron 
I have a [fix](https://github.com/Expensify/App/pull/13697) to ignore the rounded border styles for this type of button so the other buttons are unaffected. Any thoughts on what this should look like or is this okay for this button?

**Comment by grgia** [comment] 2022-12-19 18:55
I have a fix up for this, but I am opening this up to external so that @0xmiroslav can comment. Note: because this is a deploy blocker, I will be implementing the solution for this myself, but external suggestions used will be compensated for.

**Comment by grgia** [comment] 2022-12-19 19:31
@0xmiroslav Thank you, I do prefer this method! I have posted a PR using your suggestions that I am testing to get merged today. Because I am using your solution, we will make sure you get compensated for it.
cc @flaviadefaria

**Comment by s77rt** [comment] 2022-12-19 20:17
### Proposal
```diff
diff --git a/src/components/Button.js b/src/components/Button.js
index d14d6db5b3..281ee65860 100644
--- a/src/components/Button.js
+++ b/src/components/Button.js
@@ -257,6 +257,8 @@ class Button extends Component {
                     this.props.isDisabled ? {...styles.cursorDisabled, ...styles.noSelect} : {},
                     ...StyleUtils.parseStyleAsArray(this.props.style),
                     styles.buttonContainer,
+                    this.props.shouldRemoveRightBorderRadius ? styles.noRightBorderRadius : undefined,
+                    this.props.shouldRemoveLeftBorderRadius ? styles.noLeftBorderRadius : undefined,
                 ]}
                 nativeID={this.props.nativeID}
             >
@@ -277,8 +279,6 @@ class Button extends Component {
                                 (this.props.isDisabled && !this.props.danger && !this.props.success) ? styles.buttonDisable : undefined,
                                 (this.props.success && activeAndHovered) ? styles.buttonSuccessHovered : undefined,
                                 (this.props.danger && activeAndHovered) ? styles.buttonDangerHovered : undefined,
-                                this.props.shouldRemoveRightBorderRadius ? styles.noRightBorderRadius : undefined,
-                                this.props.shouldRemoveLeftBorderRadius ? styles.noLeftBorderRadius : undefined,
                                 ...this.props.innerStyles,
                             ]}
                         >
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 27195c89ac..6438357733 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -343,16 +343,15 @@ const styles = {
     },
 
     button: {
-        backgroundColor: themeColors.buttonDefaultBG,
-        borderRadius: variables.buttonBorderRadius,
         height: variables.componentSizeLarge,
         justifyContent: 'center',
         ...spacing.ph3,
     },
 
     buttonContainer: {
-        padding: 1,
+        backgroundColor: themeColors.buttonDefaultBG,
         borderRadius: variables.buttonBorderRadius,
+        overflow: 'hidden',
     },
 
     buttonText: {
@@ -368,32 +367,26 @@ const styles = {
     },
 
     buttonSmall: {
-        borderRadius: variables.buttonBorderRadius,
         height: variables.componentSizeSmall,
         paddingTop: 4,
         paddingHorizontal: 14,
         paddingBottom: 4,
-        backgroundColor: themeColors.buttonDefaultBG,
     },
 
     buttonMedium: {
-        borderRadius: variables.buttonBorderRadius,
         height: variables.componentSizeNormal,
         paddingTop: 12,
         paddingRight: 16,
         paddingBottom: 12,
         paddingLeft: 16,
-        backgroundColor: themeColors.buttonDefaultBG,
     },
 
     buttonLarge: {
-        borderRadius: variables.buttonBorderRadius,
         height: variables.componentSizeLarge,
         paddingTop: 8,
         paddingRight: 10,
         paddingBottom: 8,
         paddingLeft: 18,
-        backgroundColor: themeColors.buttonDefaultBG,
     },
 
     buttonSmallText: {
diff --git a/web/index.html b/web/index.html
index d7074a03d3..a208a7c9f9 100644
--- a/web/index.html
+++ b/web/index.html
@@ -35,11 +35,11 @@
         }
         :focus-visible {
             outline: 0;
-            box-shadow: inset 0px 0px 0px 1px #5AB0FF;
+            box-shadow: 0px 0px 0px 1px #5AB0FF;
         }
         :focus[data-focusvisible-polyfill] {
             outline: 0;
-            box-shadow: inset 0px 0px 0px 1px #5AB0FF;
+            box-shadow: 0px 0px 0px 1px #5AB0FF;
         }
         input:focus-visible, input:focus[data-focusvisible-polyfill],
         select:focus-visible, select:focus[data-focusvisible-polyfill]  {
```

*Sorry I'm a little late, i stated working on this before dropping the `Help Wanted` label*

### Details
- There is no need to apply the same style twice
- I have moved the border logic to the button container
- I have moved some duplicated styles to the button container
- I have changed the box-shadow to be `outset` not `inset` because `box-shadow` is replacing the `outline` prop
- I have removed the weird hack of setting `padding` to `1`

**Comment by s77rt** [comment] 2022-12-19 20:37
Heads up!

If you are going to apply my proposal above, first apply this css fix:
```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 27195c89ac..a21ac19f4d 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -466,7 +466,7 @@ const styles = {
     },
 
     buttonCTA: {
-        paddingVertical: 6,
+        marginVertical: 6,
         ...spacing.mh4,
     },
```

**Comment by s77rt** [comment] 2022-12-19 20:41
@grgia I think proposals gets reviewed by 2 reviewers. @0xmiroslav has not been assigned yet, besides I think my proposal is cleaner and global.

cc @mollfpr

**Comment by grgia** [comment] 2022-12-19 20:49
@s77rt this is a deploy blocker, so I will be finishing this internally. Because @0xmiroslav was assisting in the original thread and posted a solution first, we decided to compensate for their suggestions.

**Comment by s77rt** [comment] 2022-12-19 21:06
@grgia If an issue is internal it should be internal for everybody. It does not make sense to make an issue internal in GH but not on slack.

@0xmiroslav This is due to the use of overflow hidden (and the use of outset box-shadow)

**Comment by puneetlath** [comment] 2022-12-19 21:18
Hey @s77rt, you'll notice that the `Help Wanted` label was removed before you started posting on this issue. We tend to move more quickly with Deploy Blockers and I understand that can be confusing, but please try not to get frustrated. 

We appreciate your eagerness to contribute, so please feel free make proposals on [any of the issues](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22) that currently have the `Help Wanted` label on them. We add new issues every day so there is plenty of work to go around.

**Comment by shawnborton** [comment] 2022-12-19 22:12
I wonder if we should make the left border use the same color as the appBG as well? No worries if that's not really part of the issue though.

**Comment by flaviadefaria** [comment] 2022-12-23 21:42
As a note, I'm going to be OOO from Dec 23rd to January 9th. In case this needs to be paid before the week of January 9th then please reassign.

**Comment by mallenexpensify** [comment] 2023-01-03 19:13
@mollfpr who is due payment here and how much? 
I'm helping out Flavia who's out til next week.

**Comment by mollfpr** [comment] 2023-01-03 20:42
@mallenexpensify I did not review any proposals or PR so I’m not eligible for payment here.

**Comment by mallenexpensify** [comment] 2023-01-03 22:23
Thanks @0xmiroslav and @mollfpr 
PR - https://github.com/Expensify/App/pull/13697 
Compensation for @0xmiroslav is $1000, our base level for jobs, plus $250 for reporting (as they said above, ha) = $1250

@0xmiroslav can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01e2c7bdef927162e8

**Comment by mallenexpensify** [comment] 2023-01-03 22:42
Checking on regression test steps https://expensify.slack.com/archives/C01SKUP7QR0/p1672785670352739

**Comment by mallenexpensify** [comment] 2023-01-04 20:23
^ TestRail steps added, once @0xmiroslav accepts offer I'll pay then close

**Comment by mallenexpensify** [comment] 2023-01-12 01:04
@0xmiroslav paid, thanks! Closing

**Closed by mallenexpensify** 2023-01-12 01:04 UTC
Labels: Reviewing, Engineering, Daily, Internal, Needs Reproduction, Bug
