### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Delay in Accessing Thread After Deleting Parent Message Offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42194] opened 2024-05-15 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1, Open any chat and compose a message.
2, Reply to a message within the chat.
3, Go offline and delete the parent message.
4, Go back online.
5, Exit the thread by clicking the header.
6, Click on the reply notification and observe the delay in entering the thread.

## Expected Result:
Immediate access to the thread upon clicking the reply notification when online

## Actual Result:
When deleting the parent message offline and re-entering the thread online, there is a delay in accessing the thread.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/09a9f7b9-d56c-43d5-90b9-dda82fa4c47c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6c2f1d8999823b2</li>
        <li>Upwork Job ID: 1790744138062864384</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by m-natarajan** [comment] 2024-05-15 13:23
@stephanieelliott FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-15 13:23
We think that this bug might be related to #vip-vsb

**Comment by lakchote** [comment] 2024-05-15 14:00
Not a blocker (as it isn't related to a faulty API command), and can be worked on by external contributors.

Putting the correct labels.

**Comment by rakhaxor** [comment] 2024-05-15 14:30
Can I try solving it or is it already assigned to somebody else and I can't work on it anymore?

**Comment by Julesssss** [comment] 2024-05-15 14:31
We don't yet have a contributor assigned @rakhaxor

**Comment by rakhaxor** [comment] 2024-05-15 14:32
Thanks for the quick response @Julesssss, Let me try fixing it quickly.

**Comment by bernhardoj** [comment] 2024-05-15 14:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The deleted thread parent message isn't interactable for a while after deleting it.

### What is the root cause of that problem?
We set pointer events to none when it has a pending action of delete.
https://github.com/Expensify/App/blob/1ee5d03fc9c7530b2e1729a1a6feb8172115d1cf/src/pages/home/report/ReportActionItem.tsx#L937

This is to prevent the user from doing anything with the message because we are deleting it. But if we delete the parent thread message, it will show [Deleted message] instead of being removed from the chat list, so it will still be interactable.

This is reproducible after my PR [here](https://github.com/Expensify/App/pull/40781). It's not a regression. Previously, the [Deleted message] doesn't show at all when the message has a delete pending action (this bug happen after the comment linking which I explained on my [proposal there](https://github.com/Expensify/App/issues/39218#issuecomment-2039017457), so before comment linking, this issue happens too). 

The site currently has an issue, so the delete action never completes, maybe that's why it's noticeable now by QA.

### What changes do you think we should make in order to solve the problem?

Only apply the pointer event none if it's a delete pending action and not a deleted parent action.
```
style={[action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && !ReportActionsUtils.isMessageDeleted(action) ? styles.pointerEventsNone : styles.pointerEventsAuto]}
```

_`ReportActionsUtils.isMessageDeleted` checks for deleted parent action, idk why it's named that way_

**Comment by lakchote** [comment] 2024-05-16 09:05
Thank you @bernhardoj for your proposal and the thorough explanations. 

@Ollyws could you review the proposal please?

**Comment by lakchote** [comment] 2024-05-17 08:09
@bernhardoj's proposal LGTM too.

All yours @Julesssss

**Comment by bernhardoj** [comment] 2024-05-17 11:50
PR is ready

cc: @Ollyws

**Comment by stephanieelliott** [comment] 2024-05-21 23:54
PR has been approved, just waiting on merge.

**Comment by stephanieelliott** [comment] 2024-05-29 07:34
Same as last week, just waiting on merge.

**Comment by stephanieelliott** [comment] 2024-06-11 21:00
PR was merged to main, should be on staging with next deploy.

**Comment by JmillsExpensify** [comment] 2024-06-20 16:23
@stephanieelliott payment summary when you get a chance.

**Comment by stephanieelliott** [comment] 2024-06-20 21:49
QA Test created: https://github.com/Expensify/Expensify/issues/406456

Summarizing payment on this issue: 

 - Contributor: @bernhardoj $250 via Upwork - PAID 
 - Contributor+:  @Ollyws $250 via Upwork - I can't find you in Upwork, can you please apply to the job so we can pay you out? https://www.upwork.com/jobs/~01f6c2f1d8999823b2
 
 Upwork job is here: https://www.upwork.com/jobs/~01f6c2f1d8999823b2

**Comment by JmillsExpensify** [comment] 2024-06-21 18:04
$250 approved for @Ollyws

**Comment by stephanieelliott** [comment] 2024-06-25 00:34
All paid!

**Closed by stephanieelliott** 2024-06-25 00:34 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
