### ISSUE TITLE
[HOLD for #415000] [$250] Room - Endless skeleton loader when a new account logs in after navigating to a public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46105] opened 2024-07-24 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Chrome in incognito
2. Navigate to https://staging.new.expensify.com/r/2091104345528462
3. Click on the "Sign in" button at the bottom right corner
4. Log in with a new Gmail account

## Expected Result:
I should be able to log in and use that app using the public room login page

## Actual Result:
Endless skeleton loader when a new account logs in after navigating to a public room. I'm unable to to use the app, Doesn't affect existing accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3a07bd7c-b334-49cd-92b5-27c753d92fb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d012835d9c734be</li>
        <li>Upwork Job ID: 1816876606789741584</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-07-24 12:45
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-24 12:45
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment] 2024-07-26 16:41
triaged, adding external.

**Comment by c3024** [comment] 2024-07-30 02:12
Waiting for proposals.

**Comment by jaydamani** [comment] 2024-07-31 04:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Endless loading when you signup using LHN from public report
### What is the root cause of that problem?

The SequetialQueue for API requests is paused in two ways and OpenApp request is stuck in the queue so it keeps loading endlessly.
The queue is paused from: 

https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/Middleware/SaveResponseInOnyx.ts#L38C1-L44C12

In above code,
- [saveUpdateInformation](https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/actions/OnyxUpdates.ts#L140) pauses the queue synchronously but it also updates `ONYX_UPDATES_FROM_SERVER` which triggers [handleOnyxUpdateGap](https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/actions/OnyxUpdateManager/index.ts#L70C1-L80C6) This unpauses the queue when App is loading (OpenApp is not completed). Both pause and unpause happen synchronously
-  But the field [shouldPauseQueue](https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/Middleware/SaveResponseInOnyx.ts#L43C13-L43C29) pauses the queue asynchronously after the above steps are done. This time there is no check to unpause if the app is loading. Due to this the app gets stuck.

### What changes do you think we should make in order to solve the problem?

Remove the [shouldPauseQueue](https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/Middleware/SaveResponseInOnyx.ts#L43C13-L43C29) field as it is no longer required because [saveUpdateInformation](https://github.com/Expensify/App/blob/3c9c7b016ca2c801d5eac49f869eeeda76437ba7/src/libs/actions/OnyxUpdates.ts#L140) already handles pausing the queue when needed.

### What alternative solutions did you explore? (Optional)
Update below to only pause if the app is not loading.

https://github.com/Expensify/App/blob/eced1703e3b2ca1d7374b583fbc0a82b68381f85/src/libs/Network/SequentialQueue.ts#L89

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jaydamani** [comment] 2024-07-31 04:18
[Fix code link](https://github.com/Expensify/App/issues/46105#issuecomment-2259606163)

**Comment by Zakpak0** [comment] 2024-07-31 04:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
We're trying to resolve the skeleton loader that will not dismiss when an anonymous user logs in from the RHP.
### What is the root cause of that problem?
**isLoadingApp** never resolves to true after the login flow.
This is because on
```typescript
        if (!isAnonymousUser) {
            // Signing in RHP is only for anonymous users
            Navigation.isNavigationReady().then(() => Navigation.dismissModal());
            App.openApp();
        }
```
we call the openApp function. Which calls **getOnyxDataForOpenOrReconnect** with **isOpenApp** set to true and sets **isLoadingApp** true in onyx.
```typescript
/**
 * Fetches data needed for app initialization
 */
function openApp() {
}
```
### What changes do you think we should make in order to solve the problem?
The app is already initialized, so we should call **reconnectApp** instead. This won't put the entire app into loading state, and instead just fetch the reconnection data.

```typescript
        if (!isAnonymousUser) {
            // Signing in RHP is only for anonymous users
            Navigation.isNavigationReady().then(() => Navigation.dismissModal());
            App.reconnectApp();
        }
```

```typescript
/**
 * Fetches data when the app reconnects to the network
 * @param [updateIDFrom] the ID of the Onyx update that we want to start fetching from
 */
function reconnectApp(updateIDFrom: OnyxEntry<number> = 0) {
}
```
[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2346105) is a test branch with my changes
### What alternative solutions did you explore? (Optional)
N/A

**Comment by zanyrenney** [comment] 2024-08-02 17:06
@c3024 please can you review the proposal above, there are a few and we need to make progress here?

**Comment by zanyrenney** [comment] 2024-08-05 10:01
We are waiting to review the proposals above.  bump @c3024 please can you prioritise this?

**Comment by c3024** [comment] 2024-08-05 13:13
Thanks for the bump @zanyrenney. I looked into the proposals. This was caused by #42820 and that PR did not fix the bug it was supposed to. So, this might need to be held for #41500. I need a bit more time to confirm. Thanks!

**Comment by zanyrenney** [comment] 2024-08-05 14:04
nice, thank you for clarifying! @c3024

**Comment by c3024** [comment] 2024-08-07 12:00
@zanyrenney I think this should be held for #41500.

**Comment by c3024** [comment] 2024-08-13 08:05
@zanyrenney IMHO this should be [held](https://github.com/Expensify/App/issues/46105#issuecomment-2273302367) for #41500.

**Comment by zanyrenney** [comment] 2024-08-14 17:26
NICE, I'VE CHANGED THIS TO A WEEKLY ISSUE. AND I'VE UPDATED THE TITLE TO SHOW IT IS ON HOLD FOR THAT OTHER ISSUE ABOVE. THANK YOU @c3024

**Comment by zanyrenney** [comment] 2024-08-14 17:26
oops, did not mean to do caps 😓

**Comment by jaydamani** [comment] 2024-08-26 07:31
https://github.com/Expensify/App/issues/41500 seems to be stale so can we resolve this without it?

**Comment by zanyrenney** [comment] 2024-08-30 11:54
bump @c3024 what do you think about resolving without the held issue?

**Comment by c3024** [comment] 2024-09-01 05:32
There seems to be an issue with logging in from the RHP. 


https://github.com/user-attachments/assets/793051ac-1fe1-4429-8c8c-e485cf989aa4


I will investigate and update.

**Comment by zanyrenney** [comment] 2024-09-19 18:31
did you get any more detail here?

**Comment by c3024** [comment] 2024-09-20 13:28
Checking now. Will update.

**Comment by c3024** [comment] 2024-09-23 15:14
`openApp` addition in PR #42820 and simultaneous backend changes caused the present bug. That change is not needed anymore because we now have the code for showing onboarding modal when we open a deeplink (i.e. for public rooms also) here

https://github.com/Expensify/App/blob/8e5fc88fc10c75d2caa9980fc4fc61f0cab74a29/src/libs/actions/Report.ts#L2697

This code was not there when #42820 was merged. I think we can revert that code added in #42840 here so that this issue can be fixed.

**Comment by c3024** [comment] 2024-10-29 11:31
@zanyrenney 

This is not reproducible anymore. This can be closed.

**Closed** 2024-11-22 14:51 UTC
Labels: External, Monthly, Help Wanted, Bug
