### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Animation glitches on CTRL+shift+K shortcut after CTRL+K

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20621] opened 2023-06-12 20:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Press CTRL+K to open search
3. Press CTRL+shift+K to open new group menu and observe that app pushes whole content to left and search menu is partially visible for few seconds creating glitched animation
## Expected Result: 
Animation between keyboard shortcuts should be clean as it is when we press CTRL+K after CTRL+shift+K
## Actual Result: 
Animation glitches when we press CTRL+shift+K after CTRL+K
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7874c5ad-7a6e-42c4-aa3a-4adfb6a552d7

https://github.com/Expensify/App/assets/43996225/fc74b66b-d17c-4c53-bff7-dfd0f7a3b424

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686136012478009
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d07caa1456efda56</li>
        <li>Upwork Job ID: 1668365752332894208</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by Thanos30** [comment] 2023-06-12 22:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Using consecutive alternations between CTRL+SHIFT+K and CTRL+K breaks the animation of the Right Modal. Also noticed that the order doesn't matter, you can start with either CTRL+K or CTRL+SHIFT+K  , as long as you use both and then try to repeat it will the animation. TLDR it breaks on A - B - A pattern.

### What is the root cause of that problem?

The root cause of the problem is the Navigation type. I logged the Navigation types while trying to reproduce the issue and these were the logs:

- CTRL+K -> action.type went from NAVIGATE to PUSH
- CTRL+SHIFT+K -> action type remained NAVIGATE
- CTRL+K -> action type remained NAVIGATE

While the action type was supposed to change to REPLACE, it remained as NAVIGATE, and the NAVIGATE type leads to that strange animation on the transition of the 2 shortcuts. The reason this happens is because this scenario doesn't meet the requirements for the below part of the navigation code to be triggered, located in `linkTo.js`:

```
  // If this action is navigating to the RightModalNavigator and the last route on the root navigator is also RightModalNavigator
            // then we want to replace the current RHP state with new one
        } else if (type === 'UP') {
            action.type = 'REPLACE';
```

As you can see, we only expect to do that when we call the navigation with the type being 'UP', which is used on native navigation stuff.


### What changes do you think we should make in order to solve the problem?

We can create another case for our scenario here, and also check if the type is for example 'SHORTCUT' so we can make our action type into REPLACE and have a smooth transition.

Video of solution:


https://github.com/Expensify/App/assets/32620770/1c286cbd-9bd0-4c25-9e3f-a5bffa58b6e9

**Comment by mountiny** [comment] 2023-06-12 23:20
@WoLewicki @adamgrzybowski could you review the proposals on this issue please cc @abdulrahuman5196

**Comment by Thanos30** [comment] 2023-06-13 12:38
@WoLewicki This is more or less in my proposal, we would check if `RHP` is already open to use `REPLACE` and discard the animation, unless I understood what you said incorrectly.

**Comment by WoLewicki** [comment] 2023-06-13 14:50
Yeah, it just depends how would you like to check if there is RHP already. Ideally it would be checked in e.g. `linkTo.js` or `Navigation.js` and based on the states produced.

**Comment by WoLewicki** [comment] 2023-06-13 15:21
Yeah, but we can navigate inside one of the flows in `RHP`, so we have to check if we would navigate at the top level of it with the newest action.

**Comment by Thanos30** [comment] 2023-06-13 16:28
Alright that's a fair point, had to go out for a moment, will check that once I am back

**Comment by Thanos30** [comment] 2023-06-13 18:43
@WoLewicki I noticed now that via the state ( ` const state = getStateFromPath(path);` ) we can check the depth of the route, where we can see if we are going on an inner level or top level.

**Comment by mountiny** [comment] 2023-06-14 14:38
@Thanos30 have you been able to accommodate the feedback to your proposal?

**Comment by Thanos30** [comment] 2023-06-14 15:14
> @Thanos30 have you been able to accommodate the feedback to your proposal?

I believe so, yeah, I am just waiting for a confirmation on my latest comment concerning the depth of the route, to determine if we are heading to top level or inner level

**Comment by abdulrahuman5196** [comment] 2023-06-18 19:19
Hi contributors, Thank you for the proposals. I got the idea of what the proposals are trying to do. But I will have to test it little bit extensively since it involves navigation and might affect other un-touched components as well. So I will test the proposals and let you know on the analysis in a day. 

Just a note, if the root cause about new right root pages with animations clashing with each other is correct. I would also align with the comment here https://github.com/Expensify/App/issues/20621#issuecomment-1589215494 on to replace the existing right modal only when we have a different right modal page already shown and on other cases it should show up with animations as current experience.

**Comment by WoLewicki** [comment] 2023-06-19 10:45
@Thanos30 in `linkTo.js`, when calling `getStateFromPath(path)`, it will give you the new state based on the `path` applied, so it has no information about the current state. Also, calling `root.getState()` will give you the whole current state, before the navigation happens. Based on this information, I think it should be easy to resolve if we are changing the route at the top level of RHP, or does it happen e.g. inside one of the RHP flows already. Could you test it and confirm that it is true? Also, do you need more help with implementing the needed changes?

**Comment by WoLewicki** [comment] 2023-06-19 13:17
I believe that making more generic solutions is better since this is a buggy behavior right now and it would be better to fix the root of the problem. Maybe in future there will be some flows where you can navigate from inside RHP into another flow.

**Comment by Thanos30** [comment] 2023-06-19 13:19
Got it, I agree with you. I could adjust my solution to what you said using the current state and the future state and check with that.

**Comment by WoLewicki** [comment] 2023-06-19 13:34
Great, thanks 🚀

**Comment by WoLewicki** [comment] 2023-06-19 14:39
cc @mountiny

**Comment by Thanos30** [comment] 2023-06-19 14:42
@mountiny I did not update my proposal, we discussed the additions I should make to it and how I should approach the task. I can prepare an update for you if you want in a an hour once I am back home.

**Comment by mountiny** [comment] 2023-06-19 14:58
@Thanos30 that would be ideal, thanks

**Comment by abdulrahuman5196** [comment] 2023-06-19 15:13
Sure. @Thanos30  Kindly ping once the solution is updated so that we can verify.

**Comment by Thanos30** [comment] 2023-06-19 17:35
@WoLewicki @abdulrahuman5196 @mountiny Proposal is updated, thank you all!

**Comment by abdulrahuman5196** [comment] 2023-06-19 18:39
@mountiny  It seems SWM(@adamgrzybowski ) is handling it part of https://github.com/Expensify/App/pull/21067
And I have been assigned as reviewer for that PR. 
Should we proceed in the same path and remove this issue from external and I continue to review that PR?

**Comment by mountiny** [comment] 2023-06-19 20:26
thanks. this project has been led by SWM and their work is now to polish as many bugs from the navigation refactor as possible.

@Thanos30 I will offer you 25% of the bounty as is quite standard price in case someone has helpe us with the solution. I hope $250 works for you.

@adamgrzybowski @WoLewicki Thanks for raising a PR with the fix

**Comment by Thanos30** [comment] 2023-06-19 20:38
@mountiny Of course, it's okay. Thank you for the compensation even if I wasn't assigned the job. 🙏 

Should I apply for the job or will you create a new one?

**Comment by mountiny** [comment] 2023-06-19 20:40
@Thanos30 We will handle that once the PR is merged and deployed with all the other compensations if that work. Thanks for contributing and feel free to have a look at some other `Help Wanted` issues

**Comment by Thanos30** [comment] 2023-06-19 20:45
Thank you @mountiny , on my way to hopefully apply for a C+ spot in the future 😄

**Comment by abdulrahuman5196** [comment] 2023-06-28 04:52
This issue is in PR review Melvin.

**Comment by mountiny** [comment] 2023-07-06 01:41
PR merged will need one quick follow up

**Comment by abdulrahuman5196** [comment] 2023-07-17 09:34
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This issue was caused after the navigation refractor and fixed as part navigation refractor followups. So we can't point a single PR for this issue.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Press CTRL+K to open search
2) Press CTRL+shift+K
3) New group panel should open smoothly without any shakes/glitches.

**Comment by abdulrahuman5196** [comment] 2023-07-17 09:35
@adelekennedy 
BZ checklist is complete here https://github.com/Expensify/App/issues/20621#issuecomment-1637691341

Payment processing is pending on this issue.

**Comment by adelekennedy** [comment] 2023-07-17 15:53
@abdulrahuman5196 thank you! Processing payment now

**Comment by mountiny** [comment] 2023-07-20 13:29
$250 for @Thanos30 for help with the proposal
$1000 to @abdulrahuman5196 
$250 to @dhanashree-sawant

Thanks for paying this out @adelekennedy

**Comment by abdulrahuman5196** [comment] 2023-07-20 13:33
Actually payment hasn't been processed yet.

**Comment by adelekennedy** [comment] 2023-07-20 21:39
@Thanos30 @abdulrahuman5196 @dhanashree-sawant please apply here: https://www.upwork.com/jobs/~01848cfeb779ada330

**Comment by abdulrahuman5196** [comment] 2023-07-20 21:41
Applied @adelekennedy

**Comment by Thanos30** [comment] 2023-07-20 21:53
Same here @adelekennedy , Thanks 🙏

**Comment by dhanashree-sawant** [comment] 2023-07-21 05:30
Thanks @adelekennedy, I have also applied to the job.

**Comment by adelekennedy** [comment] 2023-07-24 02:37
Just pending @dhanashree-sawant payment

**Comment by dhanashree-sawant** [comment] 2023-07-24 03:48
Thanks @adelekennedy, offer accepted.

**Comment by adelekennedy** [comment] 2023-07-24 18:45
Done!

**Closed by adelekennedy** 2023-07-24 18:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
