### ISSUE TITLE
Split - When creating a Split expense the user is shown as Hidden

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51003] opened 2024-10-17 10:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5093942
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify app
2. Log in with a new HT account
3. Create a WS
4. Navigate to the WS room
5. Navigate + Menu - Submit expense - Manual
6. Create an expense
7. Navigate + Menu - Split expense - Manual
8. Enter the amount - Next

## Expected Result:
The user should not be displayed as Hidden when creating a split expense

## Actual Result:
After creating an expense in a new WS, when creating a Split expense the user is shown as Hidden

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3d97274c-552a-4e48-b59e-66aea5e2989c
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-17 10:52
We think that this bug might be related to #wave-collect - Release 1

**Comment by lakchote** [comment] 2024-10-17 12:53
Found the culprit https://github.com/Expensify/App/pull/47370

cc @jasperhuangg @parasharrajat @Krishna2323

**Comment by lakchote** [comment] 2024-10-17 13:48
Asked for a CP [here](https://expensify.slack.com/archives/C07J32337/p1729171374404689)

**Comment by lakchote** [comment] 2024-10-17 15:30
> @lakchote thanks for the revert and sorry for the regression :(

No worries, edge cases happen!

**Comment by lanitochka17** [comment] 2024-10-17 17:31
The issue is still reproducible
 

https://github.com/user-attachments/assets/d00babd0-fbe2-443d-88df-20a6d0846d7a

**Comment by rojiphil** [comment] 2024-10-18 03:41
I think this should also get fixed with the latest CP fix [here](https://github.com/Expensify/App/pull/51040#issuecomment-2420592586)
cc @lakchote @lanitochka17

**Comment by lakchote** [comment] 2024-10-18 05:19
Not reproducible on staging now, yes.

**Comment by lakchote** [comment] 2024-10-18 05:57
@Krishna2323 sorry for reverting your PR it looks like some edge case induced me in error.

https://github.com/user-attachments/assets/13b793cd-3eba-4e32-8621-88248e7952ce

As you can see in the video, there is Concierge shown as the participant instead of the user, while checking out your branch.

**Comment by neil-marcellini** [comment] 2024-10-18 18:06
> @Krishna2323 sorry for reverting your PR it looks like some edge case induced me in error.

@lakchote does that mean that we can re-apply this PR? https://github.com/Expensify/App/pull/47370

**Comment by lakchote** [comment] 2024-10-21 08:17
> > @Krishna2323 sorry for reverting your PR it looks like some edge case induced me in error.
> 
> @lakchote does that mean that we can re-apply this PR? #47370

Yes, we should. I've created an un-revert [PR](https://github.com/Expensify/App/pull/51156).

**Comment by mallenexpensify** [comment] 2024-10-22 00:24
K, sounds like we agree we should close this so.. I'm closing. Comment/reopen if you disagree

**Closed** 2024-10-22 06:42 UTC
Labels: Reviewing, Engineering, Weekly, Bug
