### ISSUE TITLE
[$1000] keyboard does not disappear when user tap on flag as offensive option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20314] opened 2023-06-06 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. click on composer to open keyboard
2. click on message which you received from other user
3. choose flag as offensive option
## Expected Result: 
should hide the keyboard on flag as offensive option page
## Actual Result: 
keyboard does not hide

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f61f8e82-1f5e-4169-a435-537b04f747a2

https://github.com/Expensify/App/assets/43996225/57c70537-952f-4c2d-995a-42cebeab5312

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685603563452209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01904186905c128b82</li>
        <li>Upwork Job ID: 1666200822849568768</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-06-06 21:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
keyboard does not disappear when user tap on flag as offensive option
### What is the root cause of that problem?
ther is no Keyboard.dismiss() call after tap on flag as offensive option.
### What changes do you think we should make in order to solve the problem?
call Keyboard.dismiss() after tap on flag as offensive option. [here](https://github.com/Expensify/App/blob/351056286bbab7372831a4522651eacfea4c5cc9/src/pages/home/report/ContextMenu/ContextMenuActions.js#L306)

### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2023-06-06 21:49
I reproduced this. Pretty simple fix.

**Comment by greg-schroeder** [comment] 2023-06-06 21:51
@abdulrahuman5196 there's a proposal [here](https://github.com/Expensify/App/issues/20314#issuecomment-1579484287) ready for review already. This is a pretty simple one so I assume that's the way to go.

**Comment by ahmedGaber93** [comment] 2023-06-06 22:05
After some test, I found my proposal root case is not accurate, so I delete it and trying to check it again.

**Comment by qasimkhan23** [comment] 2023-06-07 06:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard does not hide if you select an option of "Flag as offensive" on the received message
### What is the root cause of that problem?
In the ContextMenuActions we have not added a condition if the keyboard is opened so we can dismiss, hence if the keyboard is opened it remains open.
https://github.com/Expensify/App/blob/5e5dc7efa0f8f3bc75e88ea194ebe435d3d67617/src/pages/home/report/ContextMenu/ContextMenuActions.js#L306-L312

### What changes do you think we should make in order to solve the problem?
There are two solutions we can apply to solve this

1. We can dismiss the keyboards directly onPress if keyboard is open it will be closed.
2. We can make use of a hook to store a value of a state if the keyboard is open only than we will dismiss the keyboard.

Solution 1

```
 onPress: (closePopover, {reportID, reportAction}) => {
        
            Keyboard.dismiss();
            if (closePopover) {
                hideContextMenu(false, () => Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID)));
            }

            Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID));
        },
```
Solution 2
```
const [isKeyboardVisible, setKeyboardVisible] = useState(false);

 useEffect(() => {
    const keyboardDidShowListener = Keyboard.addListener(
      'keyboardDidShow',
      () => {
        setKeyboardVisible(true); // or some other action
      }
    );
    const keyboardDidHideListener = Keyboard.addListener(
      'keyboardDidHide',
      () => {
        setKeyboardVisible(false); // or some other action
      }
    );

    return () => {
      keyboardDidHideListener.remove();
      keyboardDidShowListener.remove();
    };
  }, []);
```
```
onPress: (closePopover, {reportID, reportAction}) => {
        
           if(isKeyboardVisible){
            Keyboard.dismiss();
           }
            if (closePopover) {
                hideContextMenu(false, () => Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID)));
            }

            Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID));
        },
```

### What alternative solutions did you explore? (Optional)
None

**Comment by qasimkhan23** [comment] 2023-06-07 07:02
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Keyboard does not hide if you select an option of "Flag as offensive" on the received message
> 
> ### What is the root cause of that problem?
> In the ContextMenuActions we have not added a condition if the keyboard is opened so we can dismiss, hence if the keyboard is opened it remains open.
> 
> https://github.com/Expensify/App/blob/5e5dc7efa0f8f3bc75e88ea194ebe435d3d67617/src/pages/home/report/ContextMenu/ContextMenuActions.js#L306-L312
> 
> ### What changes do you think we should make in order to solve the problem?
> There are two solutions we can apply to solve this
> 
> 1. We can dismiss the keyboards directly onPress if keyboard is open it will be closed.
> 2. We can make use of a hook to store a value of a state if the keyboard is open only than we will dismiss the keyboard.
> 
> Solution 1
> 
> ```
>  onPress: (closePopover, {reportID, reportAction}) => {
>         
>             Keyboard.dismiss();
>             if (closePopover) {
>                 hideContextMenu(false, () => Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID)));
>             }
> 
>             Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID));
>         },
> ```
> 
> Solution 2
> 
> ```
> const [isKeyboardVisible, setKeyboardVisible] = useState(false);
> 
>  useEffect(() => {
>     const keyboardDidShowListener = Keyboard.addListener(
>       'keyboardDidShow',
>       () => {
>         setKeyboardVisible(true); // or some other action
>       }
>     );
>     const keyboardDidHideListener = Keyboard.addListener(
>       'keyboardDidHide',
>       () => {
>         setKeyboardVisible(false); // or some other action
>       }
>     );
> 
>     return () => {
>       keyboardDidHideListener.remove();
>       keyboardDidShowListener.remove();
>     };
>   }, []);
> ```
> 
> ```
> onPress: (closePopover, {reportID, reportAction}) => {
>         
>            if(isKeyboardVisible){
>             Keyboard.dismiss();
>            }
>             if (closePopover) {
>                 hideContextMenu(false, () => Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID)));
>             }
> 
>             Navigation.navigate(ROUTES.getFlagCommentRoute(reportID, reportAction.reportActionID));
>         },
> ```
> 
> Since we are using Class base components we can also add property "isKeyboardVisible" in contextAction.renderContent payload
> 
> https://github.com/Expensify/App/blob/b77cf55dd6793cbbf76e985ea46b8825c2e923a4/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L93-L110
> 
> ```
>   constructor(props) {
>         super(props);
>         this.wrapperStyle = getReportActionContextMenuStyles(this.props.isMini, this.props.isSmallScreenWidth);
> 
>         this.state = {
>             shouldKeepOpen: false,
>             isKeyboardVisible :false
>         };
>         this.keyboardWillShow=null
>         this.keyboardWillHide = null
>     }
>     componentDidMount() {
>            this.keyboardWillShow = Keyboard.addListener('keyboardWillShow', ()=>{this.setState({isKeyboardVisible:true})});
>            this.keyboardWillHide = Keyboard.addListener('keyboardWillHide', ()=>{this.setState({isKeyboardVisible:false})});
>       }
>     
>       componentWillUnmount() {
>            this.keyboardWillShow?.remove();
>            this.keyboardWillHide?.remove();
>       }
> ```
> 
> ```
>  const payload = {
>                             reportAction: this.props.reportAction,
>                             reportID: this.props.reportID,
>                             draftMessage: this.props.draftMessage,
>                             selection: this.props.selection,
>                             close: () => this.setState({shouldKeepOpen: false}),
>                             openContextMenu: () => this.setState({shouldKeepOpen: true}),
>                             interceptAnonymousUser,
>                             isKeyboardVisible
>                         };
> 
>                         if (contextAction.renderContent) {
>                             // make sure that renderContent isn't mixed with unsupported props
>                             if (__DEV__ && (contextAction.text != null || contextAction.icon != null)) {
>                                 throw new Error('Dev error: renderContent() and text/icon cannot be used together.');
>                             }
> 
>                             return contextAction.renderContent(closePopup, payload);
>                         }
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> None

Updated, added solution for class base components

**Comment by dinithij** [comment] 2023-06-08 06:49
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
The Keyboard is not hidden after navigating by selecting the option `Flag as offensive` of a received message.

## What is the root cause of that problem?
In the current `Navigation.js` -> `openDrawer` function, `Keyboard.dismiss()` has already been performed, yet the Keyboard is not closing after navigating to `FlagCommentPage`. The reason is that the current focused textInputRef's Keyboard component is not accessible in `Navigation.js`.

If we try to dismiss the keyboard in the `FlagCommentPage.js` once the page is loaded or else inside the `ContextMenueAction.js` -> `OnPress` event, it will give the same behaviour where the Keyboard dismiss won't work as expected. 

## What changes do you think we should make in order to solve the problem?
In `ReportActionItem.js`, we trigger `showPopover` event to get the composer, which contains the `Flag as offensive` option.

Inside `showPopover`, before calling the `setIsContextMenuActive ` function, `Keyboard.dismiss()` can be performed to solve this issue.

```rb
const showPopover = useCallback(
        (event) => {
            // Block menu on the message being Edited or if the report action item has errors
            if (props.draftMessage || !_.isEmpty(props.action.errors)) {
                return;
            }

            setIsContextMenuActive(true);

            const selection = SelectionScraper.getCurrentSelection();
            ReportActionContextMenu.showContextMenu(
                ContextMenuActions.CONTEXT_MENU_TYPES.REPORT_ACTION,
                event,
                selection,
                popoverAnchorRef,
                props.report.reportID,
                props.action,
                props.draftMessage,
                () => {},
                toggleContextMenuFromActiveReportAction,
                ReportUtils.isArchivedRoom(props.report),
                ReportUtils.chatIncludesChronos(props.report),
            );
        },
        [props.draftMessage, props.action, props.report, toggleContextMenuFromActiveReportAction],
    );
```

Note: Since the textInputRef is available here, the Keyboard dismissal can be done at this point.

## What alternative solutions did you explore? (Optional) 
None

**Comment by dinithij** [comment] 2023-06-08 07:02
Contributor details
Your Expensify account email: dinithijaywork@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0185e7de771a4f8429

**Comment by qasimkhan23** [comment] 2023-06-08 07:29
@dinithij the keyboard is already getting hidden underneath when the popover is displayed, you can have a look at the video attached to this issue, also if the user will close the popover without navigating, the keyboard will be there which will be a better user experience, it will only get dismissed when the user will navigate to other screen.

**Comment by dinithij** [comment] 2023-06-09 10:08
## Proposal
[Updated](https://github.com/Expensify/App/issues/20314#issuecomment-1581984334)

**Comment by dinithij** [comment] 2023-06-09 10:13
@qasimkhan23 Updated the proposal with a new fix. Now the keyboard will be dismissed only when navigated to the `Flag as offensive` page. The keyboard is there after selecting another option or closing the popover.

**Comment by greg-schroeder** [comment] 2023-06-09 14:00
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-06-09 14:01
Will review before EOD

**Comment by greg-schroeder** [comment] 2023-06-09 15:28
Hmm. I definitely reproduced it on Tuesday. I'm trying again now on the staging app build

**Comment by greg-schroeder** [comment] 2023-06-09 15:30
Well, now I see a different bug:

1. go to any chat
2. click on composer to open keyboard
3. long press on message you received from other user
4. notice that the context menu opens briefly and then closes

**Comment by abdulrahuman5196** [comment] 2023-06-09 17:00
@dinithij Even it it was reported on a previous version, we should check in latest version if its still reproducible. Since other fixes also could have fixed the mentioned issue. 
Or is it something that rarely occures? 

@greg-schroeder  I am testing in 1.3.25-8 in the app store release and iphone 12 and I don't find any issue.

**Comment by greg-schroeder** [comment] 2023-06-09 17:39
Okay, trying again on the new build

**Comment by greg-schroeder** [comment] 2023-06-09 17:40
I'm not really sure how or where, but I think the most recent build doesn't include either the one listed in the OP or the one I found [here](https://github.com/Expensify/App/issues/20314#issuecomment-1584772186)

iphone 12 v1.3.26-0

**Comment by gadhiyamanan** [comment] 2023-06-10 12:30
with the latest version keyboard shows for a second on flag as offensive option

https://github.com/Expensify/App/assets/54790231/0c232cfd-ac4d-4a44-8e3b-a346b12d2f6a

**Comment by abdulrahuman5196** [comment] 2023-06-12 13:58
@gadhiyamanan  I am not sure if its bug. But anyways @greg-schroeder  could you confirm on this?
But anyways this is not the one this issue initially tried to solve.

**Comment by greg-schroeder** [comment] 2023-06-12 18:35
I don't really see that as a bug, as the keyboard is dismissed pretty quickly. At any rate, it's not the bug that was brought up here - I'd take that to #expensify-open-source in Slack to report it separately. I'm going to close this issue out.

**Closed by greg-schroeder** 2023-06-12 18:35 UTC
Labels: External, Daily, Help Wanted, Bug
