### ISSUE TITLE
[$500] When user didnt validate account, password cant be set in NewDot 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11427] opened 2022-09-29 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create account in Old dot 
2. Click on Free plan inbox card 
3. Navigate to Settings > Security > change password 
4. try to set password 

## Expected Result:
User  should be able to change or set password or option message to validate emails should be displayed 

## Actual Result:
I am on an unvalidated account (no password set) but when I go to try to change my password, I get this error: New password must be different than your old password

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="373" alt="image - 2022-09-29T132432 072" src="https://user-images.githubusercontent.com/43995119/193100799-c9df49b9-2281-4f12-9f56-ef72f06b06ed.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663891860480599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-30 08:00
The user can't change/set a password for unvalidated account the api we have in the code base needs current password or validateCode to set a password so I think when user clicks on change password we should show a screen, asking the user to check their email and visit the magic link to set password because we already have sent them the magic link. 

We can use account.validated to show that screen. This key won't be available if the account is unvalidated.

**Comment by shawnborton** [comment] 2022-09-30 15:06
Yeah I agree with that approach @Puneet-here.

**Comment by luacmartins** [comment] 2022-10-03 18:59
I agree with the approach. @shawnborton do we have any mocks for the screen we should display in this case?

**Comment by shawnborton** [comment] 2022-10-03 21:05
I think something simple like this would work?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2319350/193682418-cb4eef54-4d13-4eb7-8fc5-6af8f33e1636.png">

**Comment by luacmartins** [comment] 2022-10-03 22:37
That works! Thanks @shawnborton! I'll make this an external issue.

**Comment by luacmartins** [comment] 2022-10-03 22:39
lol there's something weird going on with the auto-assigner. I don't think it should have assigned @puneetlath, because of [this comment](https://github.com/Expensify/App/issues/11427#issuecomment-1266144736)

**Comment by puneetlath** [comment] 2022-10-04 22:40
Ah, I think it's because I'm on both the CM and CME teams. So it's assigning me to create the Upwork job. 

External Upwork job: https://www.upwork.com/jobs/~01fde17c934fb9885d
Internal Upwork job: https://www.upwork.com/ab/applicants/1577428358718816256/job-details

**Comment by luacmartins** [comment] 2022-10-04 22:52
AH good point @puneetlath!

**Comment by puneetlath** [comment] 2022-10-07 17:49
Still waiting for proposals.

**Comment by shawnborton** [comment] 2022-10-10 14:13
Not overdue

**Comment by puneetlath** [comment] 2022-10-10 15:39
Updated to $500.

**Comment by tienifr** [comment] 2022-10-11 13:25
### Proposal

### Problem
This issue is from `PasswordPage.js`
When render the content of password page now we just check `props.account.success` is not empty to render `PasswordConfirmationScreen` when user successfully change password or form to edit password when user open this page

[App/PasswordPage.js at dfb5bca05a5b12e62ec86520819fd5a4ac66e405 · Expensify/App](https://github.com/Expensify/App/blob/dfb5bca05a5b12e62ec86520819fd5a4ac66e405/src/pages/settings/PasswordPage.js#L155-L165)

So with user who is not validated login (login from [Expensiy.com](http://expensify.com/), where password had not required to set ) `account.success `in normal will be empty and we render the form to edit password

=> It seem not logically unreasonable when user did not set password can change the password

### Solution
We have a field to check whether user set their password or not is `props.user.validated`

I will follow design in ticket to add the text remind user to validated account and the button to resend the validation link to their email (use new component  ResendValidationPage) by add logic in render of password page when user account is not validate.
This mean `when props.user.validated` is false I will render the text and button to resend link and when user set their password to validate account parallel with props.user.validated is set to true and the form to reset password will be render

Code change : [tienifr/App: Pull Request 8](https://github.com/tienifr/App/pull/8)

Change demo : 
https://user-images.githubusercontent.com/113963320/195102460-1e0aab12-5de6-4499-8062-f7bcc933df8a.mp4

**Comment by Puneet-here** [comment] 2022-10-11 14:58
I think we wanna use push to page here, pressing the resend validation link button should show resend validation form that we already use at our app, this way we can also reuse the same component.

**Comment by tienifr** [comment] 2022-10-12 08:28
Thanks for the reiview @Puneet-here @shawnborton @rushatgabhane. I have some update to code change in proposal please check 

## Updated Proposal

### Solution

Cause this problem occur in web only, ( in mobile when we click eye icon the text input not be out focus ) so that I will fix logic of onBlur function in `NewPasswordForm.js`, will check if we click outside the component wrapping the input and eye icon, the state will be reset

Code change : https://github.com/tienifr/App/pull/8

Change demo : 
[video demo password page 3.webm](https://user-images.githubusercontent.com/113963320/195291593-4af95811-c78e-4ebe-b15e-eb1361dbf647.webm)

**Comment by shawnborton** [comment] 2022-10-12 16:55
Thanks for sharing. Generally looks good but it looks like you are not using the correct amount of padding around the content:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2319350/195403051-b91fc793-30b7-49e2-8c6a-538491206397.png">


Check other containers to see the correct padding, it should be more like 20px on left/right/bottom.

**Comment by tienifr** [comment] 2022-10-13 04:00
@shawnborton Thanks for your review. I have fixed the padding and code to match your provided design, but I can not find the icon like you, now I see the `Mail` icon which seem best match with it. Can you show me where I can see the icon in design, or we can use `Mail` icon in this situation ? 

Code change: [tienifr/App: Pull Request 8](https://github.com/tienifr/App/pull/8)

Video demo: [video demo match design.webm](https://user-images.githubusercontent.com/113963320/195496100-180ba600-d506-4d41-a94c-3be2c216c8c8.webm)

**Comment by shawnborton** [comment] 2022-10-13 15:51
Nice, thanks for putting that together. I think the mail icon you used works just fine, so no worries there. 

For this screen here:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2319350/195644693-20ba8ba3-bc56-4ff8-855f-a4fda6bf22d3.png">

I don't think we need the "Back" text since we have the back arrow in the top left of the modal. And then the green "Resend" button should match the full width style from the previous screen. 

Either way, I think we can probably move forward with awarding the job? cc @puneetlath

**Comment by puneetlath** [comment] 2022-10-13 19:52
Sounds good to me. @luacmartins you're the CME on this one, so your call!

**Comment by luacmartins** [comment] 2022-10-13 20:11
I agree. @tienifr [proposal](https://github.com/Expensify/App/issues/11427#issuecomment-1275786664) looks good, but we should account for [this style](https://github.com/Expensify/App/issues/11427#issuecomment-1277829883) change.

**Comment by tienifr** [comment] 2022-10-14 09:39
@shawnborton thanks for your comment. I have some update to design change 

1) To hide the back button in `ResendValidationForm` I have added to it the props `shouldHideBackButton` and we will render back button if this props is false 
2) In order to make a green resend link button match the full width style from the previous screen, I add `styles.flex1` for this button and set medium props of it to false 

Please help me check again to confirm this implementation is approved

Code change: https://github.com/tienifr/App/pull/8 

Video demo: 
[video demo for change.webm](https://user-images.githubusercontent.com/113963320/195812653-b1ae4a21-fab7-4016-9674-c593c3e0106c.webm)

**Comment by shawnborton** [comment] 2022-10-14 14:49
Awesome, thanks for the update!

After reviewing this again, I actually think we can just remove the "Resend link" button from this final screen, as you can simply just go back one step to access the Resend Button from the screen before. Thoughts? Otherwise it feels strange that you might end up in a infinite loop of these buttons.

**Comment by tienifr** [comment] 2022-10-15 04:28
@luacmartins  I applied to the job, thanks. The PR will be ready by Oct 17

**Comment by tienifr** [comment] 2022-10-17 04:29
@shawnborton Thanks for the update. I think new approach is good. I have updated the code change for it please check again and tell me if you have some comment 

Code change:  [tienifr/App: Pull Request 8](https://github.com/tienifr/App/pull/8)

Video demo:  [demo change.webm](https://user-images.githubusercontent.com/113963320/196089537-25c7f3cd-c728-41fe-8392-b8ba5428e6ab.webm)

**Comment by shawnborton** [comment] 2022-10-17 16:03
Hey @tienifr - I am having trouble getting your video to work. Mind re-uploading so I can review?

**Comment by tienifr** [comment] 2022-10-18 00:30
Hi @rushatgabhane and @shawnborton. Sorry about some issue of my latest comment. I have some update for my proposal please check again 

## Updated Proposal

### Solution

1) We have a field to check whether user set their password or not using props.user.validated. 
I will follow design in ticket to add the text remind user to validated account and the button to resend the validation link to their email by add logic in render of password page when user account is not validate. 
This mean when `props.user.validated` is false I will render the text and button to resend link and when user set their password to validate account parallel with `props.user.validated` is set to true and the form to reset password will be render 

2) To use the `ResendValidationForm` component when user click button Resend validation link in design, I add a new state `shouldShowResendValidationLinkForm` defautly set to false to render the [design](https://github.com/Expensify/App/issues/11427#issuecomment-1266048342) component  and when use click button I will set it to true to render `ResendValidationForm`, update the Onyx.credential.login to use this props in `ResendValidationForm` and call function `resendValidationLink` to send link to their email 

3) To follow [this style change](https://github.com/Expensify/App/issues/11427#issuecomment-1279112253) I have pass a new props `shouldHideButton` for `ResendValidationForm` to hide all the back and resend link button   


Code change : [tienifr/App: Pull Request 8](https://github.com/tienifr/App/pull/8)

Change demo : 
[change demo latest.webm](https://user-images.githubusercontent.com/113963320/196307561-71bfabdc-8b43-4c29-a331-8cc392a37482.webm)

**Comment by shawnborton** [comment] 2022-10-18 14:35
Thanks for the updated video! I think that makes sense to me. I see that you are re-using the component from the login screen, which I think is fine. But at the same time, I don't know that we need to include the avatar + email inside of the rightDocked modal. So perhaps we could take that part out if it's easy? Otherwise happy to keep it there so we just reuse the component.

**Comment by tienifr** [comment] 2022-10-19 02:55
@shawnborton  Sure can, but I think we should keep it there to make our code clearer (just reuse the component). Please let me know what you think so I can make the PR. Thanks

**Comment by shawnborton** [comment] 2022-10-19 13:31
Thinking back on this, I think it would make sense to remove the avatar + username but keep the text below it. So let's proceed like that - thanks!

**Comment by tienifr** [comment] 2022-10-19 18:27
@shawnborton Thanks for your comment. I changed the PR https://github.com/tienifr/App/pull/8.

https://user-images.githubusercontent.com/113963320/196773324-382d665e-4f67-423b-b947-0a35cfae3e35.mp4

@rushatgabhane because we're still discussing, I just want to ensure everything is ok before I create the PR on E/App repo.
Pls help me check the PR https://github.com/tienifr/App/pull/8.

As https://github.com/Expensify/App/issues/11427#issuecomment-1277829883
In `src/pages/settings/ResendValidationLinkScreen.js`
I'll create a new screen for `resendValidationLink` form with route as `settings/security/password/resendValidationLink`

In `src/pages/settings/PasswordPage.js`, we have 3 components: PasswordConfirmationScreen (when user change password successfully), EditPasswordScreen (when user is validated), UnauthenticatedUser(when user is invalid).
In order to avoid nested-ternary I want to place them in a new file: `src/pages/settings/EditPasswordScreen.js`, `src/pages/settings/UnauthenticatedUser.js`, `src/pages/settings/PasswordConfirmationScreen`. 

In `src/pages/signin/ResendValidationForm.js` I added `shouldHideButton` and `shouldHideUserInfo` to hide button and avatar + email in `ResendValidationLinkScreen`

**Comment by shawnborton** [comment] 2022-10-19 18:31
Video looks good, thanks!

**Comment by tienifr** [comment] 2022-10-20 06:05
@rushatgabhane @shawnborton  I just created PR for this issue, please help to check:https://github.com/Expensify/App/pull/12032

**Comment by shmaxey** [comment] 2022-10-26 15:13
Thanks, @luacmartins! I agree with reusing that copy - watching the thread in Slack (thanks for posting!).

**Comment by luacmartins** [comment] 2022-10-27 17:25
I just confirmed that if we have an unvalidated email account, we send the validation message via email. So I think that we should reuse [this copy](https://github.com/Expensify/App/blob/07fc7d7fb6569b8705e50144a1e32fa3a941d1ba/src/languages/en.js#L273), but change the end to `email`, so it reads:
```
The email has not yet been validated. Click the button to resend the validation link via email.
```

We also have the case where the account was created with a phone number, and we should reuse [this copy](https://github.com/Expensify/App/blob/7b946f631a8333aaf57fb489aa08ffc493bc39fe/src/languages/en.js#L273).
 
@shmaxey does that make sense?

**Comment by shmaxey** [comment] 2022-10-27 17:38
Yep, agree!

**Comment by luacmartins** [comment] 2022-10-27 18:03
@rushatgabhane @tienifr please use the copy as described in [this comment ](https://github.com/Expensify/App/issues/11427#issuecomment-1293843676)

**Comment by luacmartins** [comment] 2022-10-31 14:47
PR in review!

**Comment by arielgreen** [comment] 2022-11-03 20:17
Hey @luacmartins @rushatgabhane, can you prioritize getting any changes or reviews completed today? Let's keep the momentum up to get this one closed out! cc @puneetlath

**Comment by luacmartins** [comment] 2022-11-04 01:46
I left a preliminary review, since there were quite a few things to fix.

**Comment by puneetlath** [comment] 2022-11-08 14:21
@tienifr is your PR ready for another round of review yet? If not, can you please provide an estimate on when it will be?

**Comment by tienifr** [comment] 2022-11-08 14:27
@puneetlath yes, it's ready

**Comment by luacmartins** [comment] 2022-11-08 23:34
@tienifr coming from [this Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1667850311631759), we are  moving to a passwordless design for the App. This issue/PR are no longer needed!

@puneetlath let's make sure that we compensate @tienifr and @rushatgabhane for the work on the PR before closing this issue!

**Comment by puneetlath** [comment] 2022-11-10 14:22
Sounds good. @tienifr @rushatgabhane sent you both hiring offers in upwork.

**Comment by puneetlath** [comment] 2022-11-11 15:02
All paid. Thanks everyone!

**Closed by puneetlath** 2022-11-11 15:02 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
