### ISSUE TITLE
[$1000] App crash on click of thread created from Welcome message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21680] opened 2023-06-27 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA, go to Settings > Workspaces
2. click on New workspace button
3. go to the #announce room and send a message
4. click on the room header
5. go to Settings > Welcome message
6. add any message and click on the save button
7. go to Settings > Workspaces >Members > Invite
8. invite userB
9. from userB, go to #announce
10. hover over welcome message > click reply in thread option > send a message in thread
11. from userA, observe the thread appears initially as `[Deleted message]` in the LHN.
12. Click on the thread's LHN row while in that state.

## Expected Result: 
App should not crash when clicking the thread

## Actual Result: 
App crashes when click the thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13dd381d-8eac-43ef-af3e-8673877fe7ec

**Console error**
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/718421a8-6397-4f08-8f8b-de1206061ffd">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687271550225839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01352d0a7b677d7fd7</li>
        <li>Upwork Job ID: 1674784281453809664</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-06-30 13:25
I can't reproduce this one, it works correctly on the latest staging: `v1.3.35-4`. Closing the issue out! 

https://github.com/Expensify/App/assets/16232057/ae07f803-d77c-4740-abf3-e87aa0336ea0

**Comment by trjExpensify** [comment] 2023-06-30 14:17
Okay, I was able to repro this in the end. Updated the steps. You need to click on the LHN row when it's appearing as `[Deleted message]`. 

https://github.com/Expensify/App/assets/16232057/fec7aa45-eb59-49c3-ada0-21858b4dff6f

**Comment by Swor71** [comment] 2023-07-03 10:24
Hey, I'm Marcin from Callstack - expert contributor group - I'd like to take a look at this issue

**Comment by trjExpensify** [comment] 2023-07-03 12:42
Yep, let's do it @Swor71!

**Comment by trjExpensify** [comment] 2023-07-05 22:25
How are you looking @Swor71?

**Comment by Swor71** [comment] 2023-07-06 08:41
hey, so far I've been investigating the issue, I have one lead, which I'm currently exploring further, it just takes time to reproduce this behaviour as you know.

**Comment by Swor71** [comment] 2023-07-06 14:44
for some reason after pulling latest changes, I cannot reproduce this anymore. Tested several times on different and new accounts. The app doesn't crash when pressing on the reply msg. @trjExpensify would you mind testing this again with the latest changes from main, if you have a moment, please?

**Comment by trjExpensify** [comment] 2023-07-06 15:44
Hm, same.. I can't seem to reproduce the crash anymore either on the latest staging:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/559b05fa-6832-4005-bf7f-db802a089e46">

We do still have that `[Deleted message]` row temporarily for the thread that seems strange, but there's an [issue for that here it seems](https://github.com/Expensify/App/issues/22255).

Do you think we just close this out then? @gadhiyamanan you're welcome to try and reproduce it if you want!

**Comment by gadhiyamanan** [comment] 2023-07-06 16:36
@trjExpensify App has not crashed on [Delete message] but still profile pic is missing in LHN

**Comment by trjExpensify** [comment] 2023-07-06 16:40
Yep, which wouldn't you say is more closely tied to the other issue with `[Deleted message]` right?

**Closed** 2023-07-10 10:12 UTC
Labels: External, Daily, Overdue, Bug
