### ISSUE TITLE
[$500] Web - Login - Original tab page blinks when add expired magic code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31600] opened 2023-11-21 00:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. On the log in screen, enter email address
3. Navigate to the email inbox and open the validate email and copy the link
4. Modify the last portion of the link by a character, change to staging and paste it to another tab
5. Navigate to the original tab

## Expected Result:
User should navigate to the original tab and no errors or blinking page should be visible

## Actual Result:
Original tab page blinks when add expired magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/03c71287-7ed8-4133-8d6a-77c3fd5fbd01

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013535f35e646fe39f</li>
        <li>Upwork Job ID: 1726758985370157056</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-11-21 09:47
I am unable to reproduce this on macOS Chrome.

**Comment by kadiealexander** [comment] 2023-11-27 03:10
I also can't reproduce this, we have replaced this with very intentional behaviour:

https://github.com/Expensify/App/assets/59587260/54048388-888e-4cc3-8165-d7c0f4d30460

Closing for now, please reopen if this changes.

**Closed by kadiealexander** 2023-11-27 03:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
