### ISSUE TITLE
[$500] [Remove Free Workspace Creation] Update Welcome Message on NewDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#37152] opened 2024-02-23 16:51 UTC
- Held on https://github.com/Expensify/App/issues/37149 so that the new notifications are in place on the server
- Held on https://github.com/Expensify/App/issues/37151 so that all collect policies created in NewDot are accessible in NewDot

Update the `workspace.inviteMessage.welcomeNote` translation key in `en.ts` and `es.ts` to be:

```
#[senders display name] ([senders login]) invited you to Expensify
Hi there -

To join "[workspace name]", [click here](link) to start tracking your expenses!

They also added the message:
[Input message]

Additionally, here is the workspace description:
[Input description]
```

- The first line of the message must be proceeded with the "#" so that it utilizes the backend functionality for custom subject lines (eg. the first line of the message gets parsed out and used as the subject for email notifications)
- The "[Input message]" part of the message template is what currently exists in `workspace.inviteMessage.welcomeNote`
- The template will need some new variables:
  - Senders display name and login
  - Workspace description
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0b03e2c9b6c2e93</li>
        <li>Upwork Job ID: 1762127177147461632</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-02-28 14:21
reviewing

**Comment by bfitzexpensify** [comment] 2024-03-04 01:10
Still held on https://github.com/Expensify/App/issues/37151 and https://github.com/Expensify/App/issues/37149

**Comment by bfitzexpensify** [comment] 2024-03-06 00:41
https://github.com/Expensify/App/issues/37151 and https://github.com/Expensify/App/issues/37149 were deployed to prod yesterday, so you can proceed with proposal review @situchan!

**Comment by trjExpensify** [comment] 2024-03-06 10:51
@situchan will you be able to complete the proposal review today?

**Comment by situchan** [comment] 2024-03-06 11:09
yes, please remove HOLD from title.

**Comment by trjExpensify** [comment] 2024-03-06 11:44
Yep, I've asked to confirm on that in Slack in the project channel here before I do: https://expensify.slack.com/archives/C036QM0SLJK/p1709723299888989

**Comment by tgolen** [comment] 2024-03-06 15:07
I've taken it off HOLD.

**Comment by situchan** [comment] 2024-03-06 15:30
This is feature request but not dib issue.
I recommend @dukenv0307 since they provided the most accurate solution than others.
Proposal: https://github.com/Expensify/App/issues/37152#issuecomment-1964336610
🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2024-03-07 22:29
@dukenv0307 can we get an ETA on this PR please? Thanks!

**Comment by DylanDylann** [comment] 2024-03-30 05:31
I can take over this issue as a C+ reviewer because @situchan is OOO in April

**Comment by mallenexpensify** [comment] 2024-04-01 16:32
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by youssef-lr** [comment] 2024-04-10 00:02
@dukenv0307 any update on the PR?

**Comment by trjExpensify** [comment] 2024-04-16 14:42
Done!

**Comment by trjExpensify** [comment] 2024-04-29 12:11
@bfitzexpensify can you take care of prepping this issue for payment?

**Comment by bfitzexpensify** [comment] 2024-05-02 13:09
Payment complete. 

This wasn't really a bug, and I don't see a need for a specific regression test for this. Closing this out.

**Closed by bfitzexpensify** 2024-05-02 13:09 UTC
Labels: Reviewing, External, Daily, Improvement, Bug
