### ISSUE TITLE
[$1000] Mac / Safari - Verifiying Phone Number Screen Is Not Visible Correctly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22795] opened 2023-07-13 11:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login To App
2. Go To Settings
3. Go To Profile
4. Go To Contact Method
5. Add Phone Number
6. Click To Verify Phone Number By Entering Magic Code
## Expected Result: 
Enter Magic Code Screen Should Be Displayed Instantly
## Actual Result: 
Only Enter Magic Code Screen Is Displayed And After Some Time It Is Fully Displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Need reproduction ( not able to reproduce by applause)
**Reproducible in production?:**  Need reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/47500f38-5710-4abd-9273-7431a22df33a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @syedsaroshfarrukhdot
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1687302970520169
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140ee9b5100d37828</li>
        <li>Upwork Job ID: 1681414448900300800</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-07-19 15:19
Not overdue, Melvin. This just got posted.

**Comment by b4s36t4** [comment] 2023-07-19 15:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mac / Safari - Verifiying Phone Number Screen Is Not Visible Correctly
### What is the root cause of that problem?

RCA for animation to break is the focus reason, since the page includes an input and we're focusing it before the animation completes.

### What changes do you think we should make in order to solve the problem?
Adding focus to the magic code Input fields only after completion of transition is the solution here which can be done by introducing new state like `shouldFocus` and pass it to the component here
https://github.com/Expensify/App/blob/f2259369ed001c77cd6670a8416217f431eb523a/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L246 

Also we should disable disable `autoFocus` to false in the component.

And use that `shouldFocus` prop inside https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/settings/Profile/Contacts/ValidateCodeForm/BaseValidateCodeForm.js#L69 and use 
`useEffect` to focus the input ref using the below code.
```jsx
useEffect(() => {
    if(!props.shouldFocus) return;
    inputValidateCodeRef.current.focus()
},[props.shouldFocus])
```
### What alternative solutions did you explore? (Optional)
Passing `shouldDelayFocus` into the `ValidateCodeForm` here 
https://github.com/Expensify/App/blob/f2259369ed001c77cd6670a8416217f431eb523a/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L246  works as well

**Comment by mollfpr** [comment] 2023-07-20 16:31
I couldn't reproduce it on `v1.3.43-3` DEV.

https://github.com/Expensify/App/assets/25520267/22cbb669-edac-4d7e-a04f-c22e9cab69e2

**Comment by johncschuster** [comment] 2023-07-24 17:49
@syedsaroshfarrukhdot are you still able to reproduce the behavior? If so, can you please review @mollfpr's attempt above and help clarify the reproduction steps you've taken?

**Comment by johncschuster** [comment] 2023-07-26 21:23
@syedsaroshfarrukhdot bump!

**Comment by syedsaroshfarrukhdot** [comment] 2023-07-31 21:31
@johncschuster Sorry about late response i am currently traveling. Just going to test it again on latest version and update here if it is reproducible or not in latest version in an hour or so.

**Comment by johncschuster** [comment] 2023-07-31 22:33
Sounds good! Thanks!

**Comment by johncschuster** [comment] 2023-08-01 22:47
@syedsaroshfarrukhdot did you get a chance to test it again?

**Comment by syedsaroshfarrukhdot** [comment] 2023-08-02 18:45
@johncschuster unable to test it on latest build as when trying to add phone n umber as secondary login. This error appears.

![Screenshot 2023-08-02 at 11 43 27 PM](https://github.com/Expensify/App/assets/81307212/d55e397f-c138-43e2-a140-cf984485d563)

It seems secondary logins are disabled for now.

**Comment by johncschuster** [comment] 2023-08-02 23:48
> It seems secondary logins are disabled for now.

Is that true? When did we do that?

**Comment by johncschuster** [comment] 2023-08-03 21:50
@mollfpr looks like we're in danger of breaking WAQ. What do you think we need to do to get this back on track?

**Comment by mollfpr** [comment] 2023-08-05 07:43
>unable to test it on latest build as when trying to add phone n umber as secondary login. This error appears.

@syedsaroshfarrukhdot You should try with a phone number not used as an active account.

Still unable to reproduce the issue.


https://github.com/Expensify/App/assets/25520267/0312c859-7f7d-4f5c-adf0-f7cbddbb02bb

**Comment by johncschuster** [comment] 2023-08-09 19:39
@syedsaroshfarrukhdot did you get a chance to test this using @mollfpr's suggestion above?

**Comment by syedsaroshfarrukhdot** [comment] 2023-08-09 20:37
@johncschuster Yes, just tested it again not able to reproduced. So we can close out the issue.

**Comment by johncschuster** [comment] 2023-08-14 22:04
@mollfpr are we good to close this one out?

**Comment by mvtglobally** [comment] 2023-08-16 20:38
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2023-08-21 13:34
@johncschuster Yup, we are good to close this.

**Closed** 2023-08-25 21:49 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Overdue, Bug
