### ISSUE TITLE
[HOLD for payment 2024-02-09] [$125] Split - Error message for merchant required is displayed on failed split in group DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34914] opened 2024-01-22 19:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211016
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Re-requisite: user must have created a group and created a Split bill that will fail
1. Go to group DM
2. Click on the Split bill preview (the one that failed)
3. Scroll down to Merchant field

## Expected Result:
Error message for merchant required should not appear, since merchant is not a requirement outside workspace expense

## Actual Result:
Error message for merchant required is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ac465591-c9bd-43ee-9dab-c934db68952d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c87576e15c9b6373</li>
        <li>Upwork Job ID: 1749514046195736576</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28120335</li>
<li>paultsimura | Contributor | 28120336</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-22 19:28
We think that this bug might be related to  [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by paultsimura** [comment] 2024-01-22 19:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Merchant Required error is shown for split requests outside of an Expense report.

### What is the root cause of that problem?
We do not properly check for the `isPolicyExpenseChat` while showing the merchant error here:

https://github.com/Expensify/App/blob/61c7e0bcddac907b50e3600ff651655c5eb8d2e1/src/components/MoneyRequestConfirmationList.js#L714-L715

### What changes do you think we should make in order to solve the problem?

We should display this error only if the report belongs to the policyExpenseChat:

```js
brickRoadIndicator={props.isPolicyExpenseChat && shouldDisplayFieldError && TransactionUtils.isMerchantMissing(transaction) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : ''}
error={props.isPolicyExpenseChat && (shouldDisplayMerchantError || (shouldDisplayFieldError && TransactionUtils.isMerchantMissing(transaction))) ? translate('common.error.enterMerchant') : ''}
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-23 15:08
@youssef-lr wouldn't it be fair to make the bounty for this one equal to the other almost identical issue – https://github.com/Expensify/App/issues/33876? What's the difference between these 2 issues?

**Comment by s77rt** [comment] 2024-01-23 23:50
@paultsimura Thanks for the proposal. Your RCA is correct. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34914#issuecomment-1904684518)

**Comment by paultsimura** [comment] 2024-01-24 22:34
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35112

**Comment by Christinadobrzyn** [comment] 2024-02-01 23:33
Gonna move this to weekly while the PR is reviewed. Feel free to let me know if you'd prefer it stay daily.

**Comment by s77rt** [comment] 2024-02-05 02:20
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29064
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29064#discussion_r1477581987
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Seeing that this came from a regression test, we may not need another one

**Comment by Christinadobrzyn** [comment] 2024-02-07 00:27
Payouts due:

Contributor: $125 @paultsimura  (in Upwork - https://www.upwork.com/nx/wm/offer/28120336)
Contributor+: $125 @s77rt (in Upwork - https://www.upwork.com/nx/wm/offer/28120335)

**Comment by Christinadobrzyn** [comment] 2024-02-12 18:40
Sorry for the delay - paid out based on this payment summary - https://github.com/Expensify/App/issues/34914#issuecomment-1931015902

It sounds like we [don't need a regression test for this](https://github.com/Expensify/App/issues/34914#issuecomment-1926108161), correct @s77rt? If that's the case, I'll close this out. Thanks!

**Comment by s77rt** [comment] 2024-02-12 19:04
@Christinadobrzyn Yes we can close this

**Closed** 2024-02-12 20:14 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug
