### ISSUE TITLE
[HOLD for payment 2023-06-23] [HOLD for payment 2023-06-21] Not able to sign up with a new account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20676] opened 2023-06-13 13:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out if already signed in
2. Enter a new email that is not registered with Expensify
3. Click Continue
## Expected Result: 
Enter the magic code should be displayed
## Actual Result: 
Unlink account message is displayed, and can't even unlink

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/01b01b5d-73c1-48b2-803e-2cd32d3b3c4f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686589249160379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-06-13 13:47
Tested with production API and got the same result so this is App related regression

**Comment by mountiny** [comment] 2023-06-13 14:05
Gonna take this one on, this Pr has introduced this regression https://github.com/Expensify/App/pull/19498 I have confirmed locally by reverting the changes.

**Comment by Pujan92** [comment] 2023-06-13 14:22
I think we need to validate first `account.primaryLogin` availability here, as for a new user we are getting the `primaryLogin` with the empty string in the onyx response. 
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/pages/signin/SignInPage.js#L69

Seems the same we were doing earlier
https://github.com/Expensify/App/pull/19498/files#diff-c5a5c5593f21966821ea88d4630dd1c2b31bc851de5a3634f5d41ac8604d84abL79

**Comment by mountiny** [comment] 2023-06-13 14:35
@Pujan92 I tried that but it on its own hasnt resolved the bug for me so there must be more

**Comment by Pujan92** [comment] 2023-06-13 14:40
@mountiny I tried with [this](https://github.com/Expensify/App/pull/19498/files#r1228235126) and seems it is working(where empty `account.primaryLogin` value is considered as a true for `isPrimaryLogin`).

**Comment by mountiny** [comment] 2023-06-13 16:32
@Pujan92 @huzaifa-99 For urgency reasons and the fact this PR is large and the flow is super important I went ahead with the revert to unblock this.

Please comment on the original PR/ issue with proopsals how to solve this, I am sure we can reward you if your solution is indeed correct.

**Comment by mountiny** [comment] 2023-06-19 09:14
This was a straight revert.

Only payment is $250 due to @adeel0202

**Comment by dylanexpensify** [comment] 2023-06-19 10:18
Nice, @adeel0202 mind applying [here](https://www.upwork.com/jobs/~016ad9197c83efe03e)!

**Comment by dylanexpensify** [comment] 2023-06-19 10:50
Offer sent!

**Comment by dylanexpensify** [comment] 2023-06-19 10:55
Payment sent, closing this one out

**Closed by dylanexpensify** 2023-06-19 10:55 UTC
Labels: DeployBlockerCash, Engineering, Weekly, Awaiting Payment, Bug

**Comment by luacmartins** [comment] 2023-06-19 15:33
Thanks for the help!
