### ISSUE TITLE
Search - Second saved search name order with an edited filter differs

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49223] opened 2024-09-15 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in with a Gmail account with a lot of expenses
2. Click on "Search"
3. Click on "Filters"
4. Click on "Merchant"
5. Type "a" and click on the "Save" button
6. Click on "Save search"
7. Click on "Filters"
8. Click on "Merchant"
9. Replace "a" with "b"
10. Click on "Save search"

## Expected Result:
The name order should be "type status merchant" to match the original one.

## Actual Result:
Second saved search name order with an edited filter differs from the original one. It's displayed as: "merchant type status".

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/020b0fed-d706-4fd2-8f5a-0e3148e13cff

![Bug6604102_1726380933968!Capture](https://github.com/user-attachments/assets/c3e84b7b-6ccc-4817-8e79-3ee386990237)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-15 13:47
We think that this bug might be related to #wave-collect - Release 1

**Comment by huult** [comment] 2024-09-15 16:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Second saved search name order with an edited filter differs

### What is the root cause of that problem?

The values of `TYPE` and `STATUS` are set after the remaining values, such as Merchant.

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/SearchUtils.ts#L674-L675


### What changes do you think we should make in order to solve the problem?

We should set the values of `TYPE` and `STATUS` before the remaining filter keys.

Move `filtersForm[FILTER_KEYS.TYPE] = queryJSON.type;` and  `filtersForm[FILTER_KEYS.STATUS] = queryJSON.status; ` from [L674](https://github.com/Expensify/App/blob/main/src/libs/SearchUtils.ts#L674) to [L635](https://github.com/Expensify/App/blob/main/src/libs/SearchUtils.ts#L635) so that `TYPE` and `STATUS` are set before the remaining keys

### What alternative solutions did you explore? (Optional)

we will update the filter name and input query before saving the search

```diff
// .src/libs/actions/Search.ts#L55
function saveSearch({queryJSON, name}: {queryJSON: SearchQueryJSON; name?: string}) {
-  const saveSearchName = name ?? queryJSON?.inputQuery ?? '';
+    let saveSearchName = '';
+    if (name) {
+        saveSearchName = name;
+    } else if (queryJSON?.inputQuery) {
+       const name = SearchUtils.getSearchHeaderTitle(queryJSON);
+                saveSearchName = name;
+    }

-    const jsonQuery = JSON.stringify(queryJSON);
+    const jsonQuery = JSON.stringify({...queryJSON, inputQuery: SearchUtils.getSearchHeaderTitle(queryJSON)});

    API.write(WRITE_COMMANDS.SAVE_SEARCH, {jsonQuery, name: saveSearchName});
}

```

<summary>
<details>POC

https://github.com/user-attachments/assets/4df0b799-22b7-49e0-ab3e-21a077d19bf1

</details>
</summary>

**Comment by luacmartins** [comment] 2024-09-15 22:42
This is not a blocker. We sort those based on the order in which they were created. We can close this for now and reopen if we decide to sort them alphabetically.

**Closed** 2024-09-15 22:43 UTC
Labels: Engineering, Daily, Bug

**Comment by huult** [comment] 2024-09-16 02:39
Note: in this ticket, if we don't update the filter name on the left side, we will have an issue with inconsistent filter names, as shown in the image below.
<img width="1705" alt="Screenshot 2024-09-16 at 09 35 43" src="https://github.com/user-attachments/assets/1c6c9db3-97d3-4401-9935-e6baa1778aa3">
