### ISSUE TITLE
[HOLD for payment 2024-06-03] [$125] Web - Split scan - Excessive header space in split menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42210] opened 2024-05-15 19:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:

1. Go to https://42057.pr-testing.expensify.com/
2. Go to any chat.
3. Go to + > Split expense.
4. Split a scan expense.
5. Click on the split preview.

## Expected Result:
There will be no excessive space in the split header.

## Actual Result:
There is excessive space in the split header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![330498684-8c5d696b-f3b7-49f0-a191-310d79c3be21](https://github.com/Expensify/App/assets/43996225/90ac8b7c-39c7-4050-950e-5030422c91f5)

https://github.com/Expensify/App/assets/43996225/2cc5da7f-e7c9-4411-a2f6-c3b70a931382

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb522a9c968afba5</li>
        <li>Upwork Job ID: 1791118490892976128</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by pecanoro** [comment] 2024-05-15 21:38
I think it's coming from this big PR: https://github.com/Expensify/App/pull/40785

**Comment by pecanoro** [comment] 2024-05-15 22:07
The problem is that the whole MoneyRequestConfirmationList is now `flex: 1 1 0%` instead of `flex: 1 1 auto` as before, but not sure how to fix it.

**Comment by pecanoro** [comment] 2024-05-15 22:11
Nvm, found a fix, creating a PR

**Comment by pecanoro** [comment] 2024-05-15 22:17
I am going to assign Rushat for review since he was the original reviewer of the PR that caused the regression

**Comment by pecanoro** [comment] 2024-05-16 14:46
@MrMuzyk I managed to fix this on all platforms but native here (https://github.com/Expensify/App/pull/42231), not sure why it does not work on native platforms. We merged the fix either way to unblock the deploy, but assigning this to you since we need to fix this asap for native!

**Comment by pecanoro** [comment] 2024-05-16 14:48
Actually, it might be faster to open it up for contributors and see if someone has a solution for native.

**Comment by nkdengineer** [comment] 2024-05-16 15:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is excessive space in the split header.

### What is the root cause of that problem?
We didn't set flex style correctly.

### What changes do you think we should make in order to solve the problem?

We'll need to pass a variable to control the `flexGrow1` [here](https://github.com/Expensify/App/blob/5c619c7d244c0f94aec962258c57a922c01fecbd/src/components/MoneyRequestHeaderStatusBar.tsx#L31), and do not apply that flexGrow1 when using MoneyRequestHeaderStatusBar in SplitBillDetailsPage. There might be other minor style adjustments.

Or instead of this, we can just wrap <MoneyRequestHeaderStatusBar /> inside a View

### What alternative solutions did you explore? (Optional)
NA

**Comment by pecanoro** [comment] 2024-05-16 15:39
That style has been there for a while though and it didn't break until we deployed https://github.com/Expensify/App/pull/40785 🤔  But if that fixes the problem for all platforms and it doesn't break anything else, let's go ahead

**Comment by nkdengineer** [comment] 2024-05-17 04:02
@pecanoro this [PR](https://github.com/Expensify/App/pull/42329) is ready for preview

**Comment by MrMuzyk** [comment] 2024-05-17 07:31
Sorry if I was a bit slow to react, didn't get notification for some reason 😓 Looks like @nkdengineer PR fixes the issue on native. Web works fine too

**Comment by RickDeb2004** [comment] 2024-05-17 19:21
@MrMuzyk @rushatgabhane should I try this issue, but it seems that issue is resolved

**Comment by rushatgabhane** [comment] 2024-05-20 16:42
PR approved

**Comment by rushatgabhane** [comment] 2024-05-30 22:10
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41643


2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41643#pullrequestreview-2089446405


3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. No because it was caught by QA and will come up easily when split flow is tested

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by rushatgabhane** [comment] 2024-05-30 22:11
@isabelastisser could you please attach payment summary for this issue thank you 🙇

**Comment by isabelastisser** [comment] 2024-05-31 15:29
Payment summary:

@rushatgabhane requires payment through NewDot Manual Requests. $125 C+ review `PENDING`
@nkdengineer requires payment. $125 Contributor. I sent you the offer in Upwork now: https://www.upwork.com/ab/applicants/1791118490892976128/job-details

**Comment by nkdengineer** [comment] 2024-05-31 16:08
@isabelastisser I accepted the offer, thanks 🙇

**Comment by JmillsExpensify** [comment] 2024-05-31 17:41
$125 approved for @rushatgabhane

**Comment by isabelastisser** [comment] 2024-06-03 18:34
All set!

**Closed by isabelastisser** 2024-06-03 18:34 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
