### ISSUE TITLE
Inconsistent Distance Update When Editing Waypoints in Self DM and Workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42764] opened 2024-05-29 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature for self DM 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Reproducible in gmail.com account 
1, Go to Self DM > Plus Sign.
2, Track Expense > Select Distance > Select Start and End Points.
3, Go to Track Expense Detail > Edit Waypoint. Notice the distance live updates without clicking save, but it doesn't save when you go back.
4,Go to Workspace Chat > Plus Sign > Distance > Select Start and End Points.
5, Complete the flow > Edit the Waypoint. Notice the distance does not live update.

## Expected Result:
When editing waypoints while tracking expenses in Self DM, the distance should update only when clicking save, consistent with the Workspace chat behavior.

## Actual Result:
In Self DM, editing the distance live updates without clicking save, but the change isn't saved. In Workspace chat, the distance updates only after clicking save, causing inconsistency.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c32e609a-9fa1-4f89-8410-ebe14ccd6d75

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2024-05-29 15:34
It seems like the API is returning the wrong values. The payload seems correct, but somehow it's returning a distance with an incorrect decimal.
![Screenshot 2024-05-29 at 9 34 01 AM](https://github.com/Expensify/App/assets/22219519/e10d56e2-bfc4-4454-a0e4-d371f63c7537)

**Comment by amyevans** [comment] 2024-05-29 17:37
Hmm I am not able to reproduce this bug on `main` or on staging, the behavior between the self DM and workspace chat is consistent (in both cases the distance live updates immediately, but it reverts to the prior value - not saving - if you exit out without saving).

Granted there is some weirdness going on with the units not matching between the "live update" version and the "saved" version as Carlos mentioned, but I don't think that's the point of this bug report.

The ability to edit distance for tracked expenses is new - introduced in https://github.com/Expensify/App/pull/41633, cc @neil-marcellini in case you have any input, but a.) I don't think this needs to block deploy and b.) I can't reproduce so perhaps we can end up closing. @stephanieelliott could you give it a try?

**Comment by amyevans** [comment] 2024-05-29 17:38
Vids for reference -

Workspace chat

https://github.com/Expensify/App/assets/7277067/ed5963a0-8e16-4b8b-af5a-8e9f4216dbc3


DM chat

https://github.com/Expensify/App/assets/7277067/5ac8b78b-6d55-4c60-b3e8-c82a277b48af

**Comment by kavimuru** [comment] 2024-05-29 20:58
Issue fixed in the version 1.4.77-3

https://github.com/Expensify/App/assets/43996225/4e120435-6c3d-4552-a35f-46f458c39b97

**Comment by amyevans** [comment] 2024-05-29 21:00
Thanks, closing!

**Closed by amyevans** 2024-05-29 21:00 UTC
Labels: Engineering, Daily, Bug
