### ISSUE TITLE
[$500] IOU -"Please enter a correct merchant" message in flash after entering Merchant value

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34293] opened 2024-01-10 20:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to staging.new.expensify.com as Employee of workspace
2. Go to Workspace chat
3. Click on "+" > Request money
4. Enter amount & click Request button
5. Verify that "Please add a correct merchant" error message appear
6. Add a value in Merchant field & click Save

## Expected Result:
Error message should not appear on Final confirmation page

## Actual Result:
"Please enter a correct merchant" error message can be seen in flash on Final confirmation page after entering Merchant value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dc76b28e-cc6a-47ad-b9cf-c762956c8900

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f39187234ec2cef5</li>
        <li>Upwork Job ID: 1745186718314524672</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-10 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU -"Please enter a correct merchant" message in flash after entering Merchant value
### What is the root cause of that problem?
- Clicking on save button will do the below:
```
   const updateMerchant = (value) => {
        IOU.setMoneyRequestMerchant_temporaryForRefactor(transactionID, value.moneyRequestMerchant);
        navigateBack();
    };

```
- So, when the ```        IOU.setMoneyRequestMerchant_temporaryForRefactor(transactionID, value.moneyRequestMerchant);``` is not successful, ``` navigateBack();``` is called that lead to the bug
### What changes do you think we should make in order to solve the problem?
 -Need to make sure the Onyx is updated successfully before navigateBack().
- We can do it by create the promise

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by aim-salam** [comment] 2024-01-11 00:04
.

**Comment by mallenexpensify** [comment] 2024-01-12 23:09
To ensure I understand the bug right, this is the flash we're talking about, right?
<img width="369" alt="image" src="https://github.com/Expensify/App/assets/22508304/557584fe-b520-4e04-a564-aa4d8b4ef409">

**Comment by DylanDylann** [comment] 2024-01-12 23:11
@mallenexpensify I think so, too

**Comment by mallenexpensify** [comment] 2024-01-16 01:15
Sorry y'all, I'm going to close this one, we're hyper-focusing on bugs that affect our near-term roadmap and this tiny one doesn't fit well with those projects.  Comment/reopen if needed/wanted.

**Closed by mallenexpensify** 2024-01-16 01:15 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
