### ISSUE TITLE
Dev: Web - While inviting recent contact/phone number in workspace, two of them are added

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21957] opened 2023-06-30 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to '+' -> settings -> create new workspace
2. Go to members -> invite
3. IMPORTANT STEP, click on phone numbers only ( Add recent number)
4. Click invite
5. Notice that two numbers are shown.

## Expected Result:
Members list should display only one contact number.

## Actual Result:
While inviting recent contact/phone number in workspace, two of them are added.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV v1.3.32-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2e5d3574-6b76-4364-bc83-e05d559266df

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688037769941769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-06-30 15:47
Nope, dupe of https://github.com/Expensify/App/issues/21706 actually! (just like https://github.com/Expensify/App/issues/21782)

**Closed by conorpendergrast** 2023-06-30 15:47 UTC
Labels: Daily, Needs Reproduction, Bug
