### ISSUE TITLE
[Hold for #8595] [$500] mweb/safari - Attachment- Some part of the page is visible from previous action when opened the protected PDF file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8597] opened 2022-04-11 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-contrition: Send protected PDF file to user B

1. Go to https://staging.new.expensify.com
2. Log in with user B 
3. Open protected PDF file - put password
4. Close the protected PDF file 
5. Open protected PDF file  again

## Expected Result:
Current open page should not have any other page visible from previous action

## Actual Result:
Some part of the page is visible from previous action when opened the protected PDF file

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (safari)

**Version Number:** 1.1.54.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/162765908-face87f5-0e6b-41bc-9627-4b14e86a850d.MP4

![Image from iOS](https://user-images.githubusercontent.com/93399543/162765919-6b2a621c-ca52-4760-a419-abe975d137ec.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment] 2022-04-13 13:20
Job post: https://www.upwork.com/jobs/~01f375a847afba4391

**Comment by NicMendonca** [comment] 2022-04-21 13:15
doubled: https://www.upwork.com/jobs/~01f375a847afba4391

**Comment by parasharrajat** [comment] 2022-04-21 13:48
Again, this issue could be resolved in one of the other issues where we are creating the Custom UI for the password. Didn't find it. So I suggest to hold it till that is done.

**Comment by rushatgabhane** [comment] 2022-04-24 21:57
Sorry, I can't help here. I'm gonna unassign myself because I have school stuff going on 👨‍🏫

**Comment by NicMendonca** [comment] 2022-05-04 18:13
^ still on hold

**Comment by NicMendonca** [comment] 2022-05-12 14:03
@roryabraham @parasharrajat  is this still on hold?

**Comment by parasharrajat** [comment] 2022-05-12 14:15
Yeah its on hold for https://github.com/Expensify/App/issues/8595.

**Comment by NicMendonca** [comment] 2022-05-24 20:55
Still on hold, but that GH ☝️ is making progress

**Comment by roryabraham** [comment] 2022-06-02 18:13
Still on hold

**Comment by NicMendonca** [comment] 2022-06-15 19:32
Still on hold

**Comment by roryabraham** [comment] 2022-06-23 20:45
Still on hold

**Comment by NicMendonca** [comment] 2022-07-04 10:35
@roryabraham I am going OOO so going to re-assign in case this gets off hold while I am still out.

**Comment by jliexpensify** [comment] 2022-07-14 07:46
Still on hold

**Comment by roryabraham** [comment] 2022-07-25 16:07
Still on hold

**Comment by jliexpensify** [comment] 2022-08-03 05:45
I've had to take some unexpected time off, so assigning to Kadie (my leave buddy) to manage!

**Comment by roryabraham** [comment] 2022-08-12 17:20
Still on hold

**Comment by kadiealexander** [comment] 2022-08-22 11:20
Still on hold.

**Comment by mvtglobally** [comment] 2022-08-30 15:18
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-09-06 02:53
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment] 2022-09-13 04:24
Issue not reproducible during KI retests. (Third week) 
@roryabraham @kadiealexander  Ok to close?

**Comment by mvtglobally** [comment] 2022-09-20 05:00
Issue not reproducible during KI retests. (Forth week) Closing (Reopen if you think otherwise)

**Closed by mvtglobally** 2022-09-20 05:00 UTC
Labels: Exported, External, Engineering, Monthly, Help Wanted
