### ISSUE TITLE
[$500]  Wallet - The add payment button is located not at the bottom, but in the middle of page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29802] opened 2023-10-17 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Wallet -> Add Payment method -> Complete adding BA method
4. Click on just added BA method
5. Notice that the add payment button is located not at the bottom, but in the middle of the page, under the added BA

## Expected Result:
The add payment button is located at the bottom of page

## Actual Result:
The add payment button is located not at the bottom, but in the middle of page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/c5fcc66a-9496-4bd1-8f21-004ed2bea4fc

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bb2da831f812c7e</li>
        <li>Upwork Job ID: 1714333542644563968</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-10-18 17:35
I agree it looks expected. I will confirm today!

**Comment by joekaufmanexpensify** [comment] 2023-10-18 19:59
Yep, confirmed in the design doc this is expected. When the payments page is in the empty state, add payment method button is at the bottom. When a bank account is added, we begin showing the bank accounts tile, and the add bank account button is moved up into the tile. 

So makes sense to me that when the only bank account is deleted, we'd get rid of the tile, and go back to the empty state.

**Comment by joekaufmanexpensify** [comment] 2023-10-18 19:59
Closing as this is not a bug!

**Closed by joekaufmanexpensify** 2023-10-18 19:59 UTC
Labels: External, Daily, Help Wanted, Bug
