### ISSUE TITLE
[$500] [HOLD for payment 2023-10-27] EmojiPicker popover in Status picker is not toggle popover

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29093] opened 2023-10-09 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre condition: Make sure you have Beta for status feature
1. Navigate to Profile -> Status -> Set Status
2. Click on emoji Picker.
3. Click again on emoji picker

## Expected Result:
Popover should be closed on second click.

## Actual Result:
Popover not closed on second click.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - not testable 
- [ ] Android / Chrome - - not testable 
- [ ] iOS / native - not testable 
- [ ] iOS / Safari - - not testable 
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop 

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7453ee43-b4e1-431b-8a6b-2c94d69b9cdf

https://github.com/Expensify/App/assets/93399543/ec017d2b-bd25-4f6f-b655-292d0448226e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696762051949939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1a8adcfec621295</li>
        <li>Upwork Job ID: 1719655045440290816</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by eVoloshchak** [comment] 2023-10-16 09:09
The fix is quite straightforward, this isn't a bug per se, just a functionality that wasn't implemented in the first place
@ishpaul777's [proposal](https://github.com/Expensify/App/issues/29093#issuecomment-1753123064) looks good to me 

🎀👀🎀 C+ reviewed!

**Comment by MonilBhavsar** [comment] 2023-10-16 09:32
Also, happening on stag. Not on dev only.

**Comment by eVoloshchak** [comment] 2023-10-27 14:05
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23267, I wouldn't call it a regression, but rather a case that was missed/not planned
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23267/files#r1374624293
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a fairly simple case that was simply missed, I don't think an additional discussion is needed

**Comment by eVoloshchak** [comment] 2023-10-27 14:22
**Regression Test Proposal**

Web|Desktop
1. Login with an account that's added to `customStatus` beta
1. Navigate to Profile -> Status -> Set Status
2. Click on Emojipicker button, verify the emojipicker popover is opened
3. Click on Emojipicker button while emojipicker popover is open, verify the popover closes.

**Do we agree 👍 or 👎**

**Comment by MonilBhavsar** [comment] 2023-10-27 17:11
@greg-schroeder could you please help to - 
1. Issue payment to participants - https://github.com/Expensify/App/issues/29093#issuecomment-1773383747
2. Add regression tests - https://github.com/Expensify/App/issues/29093#issuecomment-1783004742

Thanks!

**Comment by perunt** [comment] 2023-10-30 07:26
By the way, this part was a bit changed in[ this pr](https://github.com/Expensify/App/pull/24620). I mean, this screen was moved and combined with 'Clear after page'

**Comment by MonilBhavsar** [comment] 2023-10-30 12:36
@perunt thanks for the heads up! Doesn't look like the function we updated here was changed. Anyways, please test this case so we don't break it. Thanks!

**Comment by MonilBhavsar** [comment] 2023-10-30 12:36
And, waiting for payment here https://github.com/Expensify/App/issues/29093#issuecomment-1783246879

**Comment by greg-schroeder** [comment] 2023-11-01 03:30
Hey, I'll take care of the payments now, sorry was OOO when this was assigned to me

**Comment by greg-schroeder** [comment] 2023-11-01 09:58
Created a job in UW

**Comment by eVoloshchak** [comment] 2023-11-01 10:19
@greg-schroeder, since I request payments via NewDot, could you post a payment summary here? Thanks in advance

**Comment by greg-schroeder** [comment] 2023-11-01 10:45
Was this issue merged in time to be eligible for the speed bonus? yes
Were their any regressions? no

Payment summary:

Reporter: $50
Contributor: $750
C+: $750

go ahead and make a manul request @eVoloshchak

**Comment by greg-schroeder** [comment] 2023-11-01 10:46
Sent offer to @ishpaul777 and filed regression test

**Closed by greg-schroeder** 2023-11-01 10:46 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-01 20:01
$750 payment approved based on [this summary](https://github.com/Expensify/App/issues/29093#issuecomment-1788749262).

**Comment by greg-schroeder** [comment] 2023-11-07 08:52
paid @ishpaul777
