### ISSUE TITLE
[HOLD for payment 2024-08-26][$250] Report title is incorrect for IOU grouped expenses in search page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45414] opened 2024-07-15 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721056962485279

## Action Performed:
Have IOU between 2 users
1. Open app and go to search > shared page
2. Verify the title for "IOU expenses"
3. Click on the report and see the title
## Expected Result:
Report title should match when viewing the grouped expenses and actually open up the report
## Actual Result:
The report title used for the grouped expenses differs from what you see once you actually open up the report
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-15 at 17 23 00@2x](https://github.com/user-attachments/assets/c76f0dde-5006-4d13-8eb8-a35100abffb3)
![CleanShot 2024-07-15 at 17 21 55@2x](https://github.com/user-attachments/assets/18e8f5d0-2c07-4da3-b24d-8b1130b76fca)
![Snip - (2) New Expensify - Google Chrome](https://github.com/user-attachments/assets/f9529551-0fe5-4ab6-8e67-63944a7ba9b1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b7fa06f0e22986d</li>
        <li>Upwork Job ID: 1816886957940631192</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103415918</li>
<li>nkdengineer | Contributor | 103430472</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2024-07-15 20:06
cc @luacmartins in case you want to be assigned here

**Comment by nkdengineer** [comment] 2024-07-16 05:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report title used for the grouped expenses differs from what you see once you actually open up the report

### What is the root cause of that problem?
The iou report has `reportName` as `IOU` and we use this to display as the report title for iou grouped. While in header or report detail page we're using `getReportName` function to display the report title.

<img width="1512" alt="Screenshot 2024-07-16 at 12 25 49" src="https://github.com/user-attachments/assets/e6e690f7-39f6-4175-b398-f8bb1b15eb9a">

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/SearchUtils.ts#L172
### What changes do you think we should make in order to solve the problem?
We should get the report name of the report item via `ReportUtils.getReportName` function. To do that we should 

1. Subscribe report and policy collection in `SearchUtils`

```
let allPolicies: OnyxCollection<OnyxTypes.Policy>;
Onyx.connect({
    key: ONYXKEYS.COLLECTION.POLICY,
    waitForCollectionCallback: true,
    callback: (value) => (allPolicies = value),
});
```

```
const allReports = ReportConnection.getAllReports();
```
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/SearchUtils.ts#L165

2. Get the report and policy of `reportItem` based on `reportItem.reportID` and `reportItem.policy`

```
const report = allReports?.[reportKey];
const policy = allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${reportItem.policyID || -1}`]
```

https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/SearchUtils.ts#L162

3. Use `getReportName` function to get the report name and use it here

```
const reportName = ReportUtils.getReportName(report, policy);
reportIDToTransactions[reportKey] = {
    ...reportItem,
    keyForList: reportItem.reportID,
    reportName,
    from: data.personalDetailsList?.[reportItem.accountID],
    to,
    transactions,
};
```
https://github.com/Expensify/App/blob/7d58aa6694f8ef6eb298c35526a154f7e374fdd6/src/libs/SearchUtils.ts#L172

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-07-16 15:23
@nkdengineer we can't reliably use `ReportUtils.getReportName` because the policy and report data might not be readily available in Onyx for Search results. We need to compute the reportName in the server.

**Comment by luacmartins** [comment] 2024-07-22 21:30
No updates yet.

**Comment by luacmartins** [comment] 2024-07-26 17:22
This is a tricky one. We don't save the IOU reportName in the DB, we just save `IOU` and we compute it in the frontend as mentioned in the previous proposals. The issue is that because we can't rely on Onyx having the reports/policies returned by Search, we can't directly use the method. We also don't return the full report/policy object in Search so we can't run the same logic on Search data.

I think we need to implement a new simplified function to get the IOU report name, relying only on data available in Search

**Comment by nkdengineer** [comment] 2024-07-26 18:09
Updated proposal https://github.com/Expensify/App/issues/45414#issuecomment-2230067269

- Add new main solution

**Comment by nkdengineer** [comment] 2024-07-26 18:12
@luacmartins I just updated my proposal that will only use the data in search and the data that is returned in `OpenApp` API to get the report name of the money request report. What do you think about the required BE change and the solution?

**Comment by luacmartins** [comment] 2024-07-26 19:54
>and the data that is returned in OpenApp API to get the report name of the money request report

We can't rely on this since Search could return reports not returned by OpenApp. The solution needs to use only data from Search.

**Comment by nkdengineer** [comment] 2024-07-26 22:49
@luacmartins My solution will only use search data and policy data, will not use the report data.

**Comment by luacmartins** [comment] 2024-07-29 14:47
>search data and policy data

What do you mean by policy data? That's also included in the search results, so we should use what we have in Search.

**Comment by nkdengineer** [comment] 2024-07-29 16:06
@luacmartins Thanks, I checked and see it now in Search data. The policy and personal detail we can use the search data.

About these field that I needed in my proposal, does that makes sense and can we investigate this from BE side?


1. `hasTitleReportField`
2. `oldPolicyName`
3. `stateNum`
4. `statusNum`
5. `hasNonReimbursableTransactions`
6. `isWaitingOnBankAccount`
7.  `ownerAccountID`

**Comment by getusha** [comment] 2024-07-29 20:44
Not overdue

**Comment by luacmartins** [comment] 2024-08-05 07:46
I'm not sure if we should be adding those fields to the search response yet, since that's a lot of additional logic. We might need to discuss the solution further.

**Comment by nkdengineer** [comment] 2024-08-05 07:54
@luacmartins These fields are necessary for expense report when the title field is not enabled. If we only want a solution for iou report, we don't need this. The iou report only has two cases: `manager owns ...` and `manager paid ...`

**Comment by luacmartins** [comment] 2024-08-05 07:57
I think we can go with a solution for iou reports only for now. We seem to save the expense report title in the DB, so hopefully those are in sync with the frontend.

**Comment by nkdengineer** [comment] 2024-08-05 07:59
Let me update my proposal.

**Comment by nkdengineer** [comment] 2024-08-05 08:26
@luacmartins I updated my [proposal](https://github.com/Expensify/App/issues/45414#issuecomment-2230067269)

**Comment by luacmartins** [comment] 2024-08-06 06:52
Thanks! @getusha could you take a look at the proposal please?

**Comment by getusha** [comment] 2024-08-06 11:07
@DylanDylann will take over, reassigning due to low bandwidth

**Comment by DylanDylann** [comment] 2024-08-06 12:35
@nkdengineer How you can verify this point 
> The iou report only has two cases: manager owns ... and manager paid ... 

I see an exception case when we request a scan request
<img width="1512" alt="Screenshot 2024-08-06 at 19 34 36" src="https://github.com/user-attachments/assets/864fd6f0-5052-431f-98c5-7976021a8ece">

**Comment by nkdengineer** [comment] 2024-08-06 13:45
@DylanDylann We're fixing the report name of the iou report. The image that you mentioned is the report name of the transaction thread report.

**Comment by nkdengineer** [comment] 2024-08-06 13:47
> The iou report only has two cases: manager owns ... and manager paid ...

I'm following the case in `getMoneyRequestReportName` and we only have these cases for the iou report.

**Comment by DylanDylann** [comment] 2024-08-06 14:04
> The image that you mentioned is the report name of the transaction thread report.

Ahh, my bad

**Comment by DylanDylann** [comment] 2024-08-06 16:19
https://github.com/Expensify/App/blob/aae2e0164bf0aa3d1f672618ff78f3b166126fdc/src/libs/ReportUtils.ts#L2702-L2706

@nkdengineer How about this case?

**Comment by nkdengineer** [comment] 2024-08-06 16:37
@DylanDylann I don't think p2p transactions will have no reimbursable transaction.

@luacmartins Can you please confirm, thanks.

**Comment by luacmartins** [comment] 2024-08-07 08:02
Agreed, all P2P transactions are reimbursable only

**Comment by DylanDylann** [comment] 2024-08-07 08:33
@nyomanjyotisa  As explained [here](https://github.com/Expensify/App/issues/45414#issuecomment-2253177270), we should only the search data  (snapshot_)in the search page

@nkdengineer's [proposal](https://github.com/Expensify/App/issues/45414#issuecomment-2230067269) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-08-08 04:52
@DylanDylann The PR is [here](https://github.com/Expensify/App/pull/47029).

**Comment by luacmartins** [comment] 2024-08-27 00:10
PR was deployed to prod on Aug 19

**Comment by VictoriaExpensify** [comment] 2024-08-27 03:39
[Payment summary:](https://www.upwork.com/jobs/~010b7fa06f0e22986d)
Contributor: @nkdengineer paid $250 via [Upwork](https://www.upwork.com/jobs/~010b7fa06f0e22986d)
Contributor+: @DylanDylann paid $250 via [Upwork](https://www.upwork.com/jobs/~010b7fa06f0e22986d)

Thanks for your work on this issue!

**Closed by VictoriaExpensify** 2024-08-27 03:39 UTC
Labels: External, Daily, Internal, Awaiting Payment, Bug
