### ISSUE TITLE
App considers number emojis as part of link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26632] opened 2023-09-04 02:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Copy the link of report
4. Open another report and paste in it
5. In place of last digit, use equivalent number emoji i.e. if last digit is 1 in link, in emoji picker, search 1 and use emoji which has 1 in square background
6. Send the message and observe that app considers emoji as part of link
## Expected Result: 
App should not consider any emoji as part of link
## Actual Result: 
App considers number emojis as part of link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5915954f-e02f-4d68-b781-6ee4bd7e5994

https://github.com/Expensify/App/assets/43996225/3dedb963-e4f9-479e-a409-f505abe62471

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692637594208169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment] 2023-09-04 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App considers number emojis as part of link 

### What is the root cause of that problem?

Our issue here lies in ExpensiMark, in specific it lies in URL_PATH_REGEX which is a regex used to decide the returned link of MARKDOWN_URL_REGEX.

The issue with the regex that is URL_PATH_REGEX is \w which is is matching any word character (a-z, A-Z, 0-9, and underscore) and that's causing the issue here because number emojis are structured as follows:

1. The actual number represented in the emoji which is a regular ASCII character.
2. Variation Selector-16" (VS-16) which looks like this "U+FE0F"
3. Combining Enclosing Keycap which looks like this "U+20E3"

In combination, javascript for example will understand the 1 emojis as "\u0031\uFE0F\u20E3" with u0031 being the number 1 and as far as javascript is concerned these are 3 seperate items so it will take the first one and use it as it's an actual number which will be considered a match for \w.

### What changes do you think we should make in order to solve the problem?

What we should do here is use Negative Lookahead (?!...) and include the unicode that is used in number emojis which will be something like this (?!\\ufe0f\\u20e3]) which is telling javascript that if it sees a digit followed by these specific unicode characters that are used in emojis then it should not match \w

```javascript
const URL_PATH_REGEX = `(?:${addEscapedChar('[.,=(+$!*]')}?\\/${addEscapedChar('[-\\w$@.+!*:(),=%~](?![\\ufe0f\\u20e3])')}*${addEscapedChar('[-\\w~@:%](?![\\ufe0f\\u20e3])')}|\\/)*`;
```

### Result

https://github.com/Expensify/App/assets/74202751/93fccc7b-e2de-4e4b-b940-08389e375d4d

**Comment by zanyrenney** [comment] 2023-09-04 16:10
have asked a question in the channel

**Comment by zanyrenney** [comment] 2023-09-05 13:35
As this is a super niche edge case, and not a user-reported error. I am going to close this bug report. There is no real workflow where a user would make take this action of deleting part of a link and replacing the link with an emoji of the letter in the link.

**Closed by zanyrenney** 2023-09-05 13:35 UTC
Labels: Daily, Bug
