### ISSUE TITLE
[Payment due 30/8][$250] Migrate ThreeDotsMenu/index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16209] opened 2023-03-20 08:45 UTC
### Filenames
- [ ] [src/components/ThreeDotsMenu/index.js](https://github.com/Expensify/App/blob/main/src/components/ThreeDotsMenu/index.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc503ac4e0afb293</li>
        <li>Upwork Job ID: 1685093542058012672</li>
        <li>Last Price Increase: 2023-07-29</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-06 11:08
I'd love to work on this.

**Comment by dayana7204** [comment] 2023-06-27 19:29
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment] 2023-07-07 14:34
I would like to work on this issue.

**Comment by olexyt** [comment] 2023-07-07 14:47
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:12
I'm able to work on this if needed!

**Comment by adityaaa-r** [comment] 2023-07-29 02:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `ThreeDotsMenu/index.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by lelouchB** [comment] 2023-07-29 04:20
Contributor details
Your Expensify account email: ashusingh15673@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011277782388b06ca8


# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate the class component in `ThreeDotsMenu/index.js` to a functional component


### What is the root cause of that problem?
Class based component to Functional based component

### What changes do you think we should make in order to solve the problem?
    

- Turn the class into a function.   
- Use props directly, no need for this.props.
- For each state in the class, use useState in the function.
- Change this.state.variable to the variable from useState.
- Change this.setState({variable: value}) to the setter function from useState.
- Switch React.createRef() to useRef().
- Use useEffect hooks instead of lifecycle methods (if any).
- Test everything to make sure it still works.

 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment] 2023-07-29 04:21
I would love to work on this issue

**Comment by alexxxwork** [comment] 2023-07-29 04:21
I would love to work on this issue

**Comment by AxibAli** [comment] 2023-07-29 04:21
> I am ready to work on this ticket. :)

can I do this

**Comment by lelouchB** [comment] 2023-07-29 04:23
Contributor details
Your Expensify account email: [ashusingh15673@gmail.com](mailto:ashusingh15673@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~011277782388b06ca8

**Comment by lelouchB** [comment] 2023-07-29 04:24
```
Contributor details
Your Expensify account email: [ashusingh15673@gmail.com](mailto:ashusingh15673@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~011277782388b06ca8
````

**Comment by lelouchB** [comment] 2023-07-29 04:24
Contributor details
Your Expensify account email: ashusingh15673@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011277782388b06ca8

**Comment by reinesarchisorte** [comment] 2023-07-29 04:28
Can I work this one?

**Comment by priyankrawat** [comment] 2023-07-29 04:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/ThreeDotsMenu/index.js](https://github.com/Expensify/App/blob/main/src/components/ThreeDotsMenu/index.js) to the function component.

### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.

### What changes do you think we should make in order to solve the problem?
1. Convert the class components to function components.
2. Replace state management with React hooks, such as useState.
3. Replace lifecycle methods with appropriate hooks, if necessary.
4. Remove any unnecessary instance variables (this.someVar) and use hooks like useRef if needed.
5. Remove componentDidUpdate, componentDidMount, componentWillUnmount, etc., and handle side effects with hooks like useEffect.
6. Update any references to this.props to use the props parameter directly in function components.
7. Remove propTypes and defaultProps declarations and handle them at the call sites or with TypeScript, if applicable.
8. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Shampinon** [comment] 2023-07-29 04:53
Proporsal

```
export const ThreeDotsMeny = (props) => {
  const buttonRef = useRef();
  
  const [isPopuMenuVisible, setPopupMenuVisibility] = useState(false);
  const hidePopoverMenu = useCallback(() => setPopupMenuVisibility(false), []);
  const showPopoverMenu= useCallback(() => setPopupMenuVisibility(true), []);

  return (
            <>
                <View>
                    <Tooltip text={props.translate(props.iconTooltip)}>
                        <PressableWithoutFeedback
                            onPress={() => {
                                showPopoverMenu();
                                if (props.onIconPress) {
                                    props.onIconPress();
                                }
                            }}
                            ref={buttonRef}
                            style={[styles.touchableButtonImage, ....props.iconStyles]}
                            accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                            accessibilityLabel={props.translate(props.iconTooltip)}
                        >
                            <Icon
                                src={props.icon}
                                fill={props.iconFill}
                            />
                        </PressableWithoutFeedback>
                    </Tooltip>
                </View>
                <PopoverMenu
                    onClose={hidePopoverMenu}
                    isVisible={isPopupMenuVisible}
                    anchorPosition={props.anchorPosition}
                    anchorAlignment={props.anchorAlignment}
                    onItemSelected={hidePopoverMenu}
                    menuItems={props.menuItems}
                />
            </>
        );  
}
```

Also we can remove buttonRef since it isn't used in original file

**Comment by ishpaul777** [comment] 2023-07-29 06:07
Would love to work on this

**Comment by nileshahir286** [comment] 2023-07-29 07:24
I need to use the useState hook to manage the state, and the useRef hook to handle the button reference

constants outside the function component :
const propTypes = {
  
};

const defaultProps = {
 
};

I use the useState hook to manage state, and I don't need to bind methods. Instead, I can define functions as regular functions within the functional component

Methods like componentDidMount or componentWillUnmount. For function components, i would use the useEffect hook instead. 	

 The JSX code inside the render() method is directly placed inside the function component.
In your code you access props using this.props.    In function components, I directly use the props object that is passed as a parameter to the function component.

useState for state management and useEffect for handling lifecycle methods. Other than that, the logic remains the same.

**Comment by nileshahir286** [comment] 2023-07-29 07:28
**Proposal**

I need to use the useState hook to manage the state, and the useRef hook to handle the button reference

constants outside the function component :
const propTypes = {
  
};

const defaultProps = {
 
};

I use the useState hook to manage state, and I don't need to bind methods. Instead, I can define functions as regular functions within the functional component

Methods like componentDidMount or componentWillUnmount. For function components, i would use the useEffect hook instead. 	

 The JSX code inside the render() method is directly placed inside the function component.
In your code you access props using this.props.    In function components, I directly use the props object that is passed as a parameter to the function component.

useState for state management and useEffect for handling lifecycle methods. Other than that, the logic remains the same.

Above is my explanation. So go through it and do let me know. So I can post proposal on Upwork.

Thanks
Nilesh

**Comment by Amubasshir** [comment] 2023-07-29 17:54
**Proposal**
My Expensify Account Email : mubasshir1107@gmail.com
My Upwork Profile : https://www.upwork.com/freelancers/~0150a88664353f6900
Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/ThreeDotsMenu/index.js] to the function component.
What changes do you think we should make in order to solve the problem?
import React, {Component,useState} from 'react';
import {View} from 'react-native';
import PropTypes from 'prop-types';
import _ from 'underscore';
import Icon from '../Icon';
import PopoverMenu from '../PopoverMenu';
import styles from '../../styles/styles';
import withLocalize, {withLocalizePropTypes} from '../withLocalize';
import Tooltip from '../Tooltip';
import * as Expensicons from '../Icon/Expensicons';
import ThreeDotsMenuItemPropTypes from './ThreeDotsMenuItemPropTypes';
import CONST from '../../CONST';
import PressableWithoutFeedback from '../Pressable/PressableWithoutFeedback';
export default function App({translate,iconTooltip,onIconPress,iconStyles,icon,iconFill,menuItems,anchorAlignment,anchorPosition    }) {

const  [isPopupMenuVisible,setIsPopupMenuVisible] = useState({isPopupMenuVisible: false})
let  [button,setButton] = useState(false)
// {isPopupMenuVisible: true}
const hidePopoverMenu = () =>{
  setIsPopupMenuVisible({isPopupMenuVisible: false})
  setButton(null)
}
const showPopoverMenu = () =>{
  setIsPopupMenuVisible({isPopupMenuVisible: true})
  setButton(null)
}


  return (
    <div className="App">
     
     <>
  <View>
                    <Tooltip text={translate(iconTooltip)}>
                        <PressableWithoutFeedback
                            onPress={() => {
                                showPopoverMenu();
                                if (onIconPress) {
                                    onIconPress();
                                }
                            }}
                            ref={(el) => (button = el)}
                            style={[styles.touchableButtonImage, iconStyles]}
                            accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                            accessibilityLabel={translate(iconTooltip)}
                        >
                            <Icon
                                src={icon}
                                fill={iconFill}
                            />
                        </PressableWithoutFeedback>
                    </Tooltip>
                </View>
                <PopoverMenu
                    onClose={hidePopoverMenu}
                    isVisible={isPopupMenuVisible}
                    anchorPosition={anchorPosition}
                    anchorAlignment={anchorAlignment}
                    onItemSelected={hidePopoverMenu}
                    menuItems={menuItems}
                />
            </>
    </div>
  );
}
I have done the convertion of the code. So please go through the code and let me know so that I can send proposal on Upwork.
Thanks.

**Comment by nileshahir286** [comment] 2023-07-31 12:38
Hi @MelvinBot 
I have follow your instructions already. Check my proposal.
Thanks
Nilesh

**Comment by nileshahir286** [comment] 2023-07-31 12:40
> My Expensify Account Email : [nileshahir286@gmail.com](mailto:nileshahir286@gmail.com) My Upwork Profile : https://www.upwork.com/freelancers/~0126f3665fe23ff297?s=996364627857502209
> 
> **Proposal**
> 
> I need to use the useState hook to manage the state, and the useRef hook to handle the button reference
> 
> constants outside the function component : const propTypes = {
> 
> };
> 
> const defaultProps = {
> 
> };
> 
> I use the useState hook to manage state, and I don't need to bind methods. Instead, I can define functions as regular functions within the functional component
> 
> Methods like componentDidMount or componentWillUnmount. For function components, i would use the useEffect hook instead.
> 
> The JSX code inside the render() method is directly placed inside the function component. In your code you access props using this.props. In function components, I directly use the props object that is passed as a parameter to the function component.
> 
> useState for state management and useEffect for handling lifecycle methods. Other than that, the logic remains the same.
> 
> Above is my explanation. So go through it and do let me know. So I can post proposal on Upwork.
> 
> **I have already convert the code.**
> 
> Thanks Nilesh

Here is my Proposal
Thanks

**Comment by adityaaa-r** [comment] 2023-07-31 12:47
@Santhosh-Sellavel gently bump here.

**Comment by Santhosh-Sellavel** [comment] 2023-07-31 17:34
Left a comment [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1690824771304289) for volunteers to take over

**Comment by adityaaa-r** [comment] 2023-08-01 02:05
but @rayane-djouah you got to work on a similar task [this one](https://github.com/Expensify/App/issues/16219#issuecomment-1659038780). this is not assigned yet and the other one is merged. all this is due to delay from C+, but that should not do injustice to other contributors.

**Comment by adityaaa-r** [comment] 2023-08-01 02:12
Thank you @allroundexperts ! The PR will be ready in few hours.

**Comment by bondydaa** [comment] 2023-08-02 22:31
oh sorry! this got hidden on my dashboard b/c of the reviewing label so I didn't realize I was blocking here (just another reason to wait for the PR til you're assigned 😉)

**Comment by nileshahir286** [comment] 2023-08-17 03:32
Hey,
Can you assign me this stuff? 
I can do it today and generate the PR.

Thanks
Nilesh

**Comment by bondydaa** [comment] 2023-08-30 21:06
@kadiealexander can you handle getting this paid out https://github.com/Expensify/App/issues/16209#issuecomment-1681556325

**Comment by kadiealexander** [comment] 2023-08-31 00:35
Payouts due:

Contributor: $250 @adityaaa-r
Contributor+: $250 @allroundexperts

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://github.com/Expensify/App/issues/16209#issuecomment-1681556325).

**Comment by kadiealexander** [comment] 2023-08-31 00:40
@adityaaa-r could you please apply [here](https://www.upwork.com/jobs/~01e7b569deba9d346c)? I'm not able to find your Upwork profile to send you a contract. Thanks!

**Comment by sullyAL** [comment] 2023-08-31 01:48
Contributor details
Your Expensify account email: vulajsv@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/sully

**Comment by sullyAL** [comment] 2023-08-31 02:00
Proposal

Convert class names into functional names
Example "class Form extend React.Component" to "function Form"

Check state management and life cycles and carefully undersatnd the component
Thoroughly test the new functional component before submiting the code

**Comment by kadiealexander** [comment] 2023-08-31 04:30
@sullyAL Thanks for taking the time to put a proposal together for this! Sorry if it wasn't clear, but we are only looking for proposals on issues with the `Help Wanted` label [here](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Help+Wanted%22). Please take a look at those and feel free to submit a proposal if you think you can fix anything.

**Comment by kadiealexander** [comment] 2023-08-31 05:25
Thanks @adityaaa-r! Let me know when you've accepted the contract I sent across.

**Comment by heyFahad** [comment] 2023-08-31 11:20
Contributor details
Your Expensify account email: Fahad_Javed008@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01604e3bea5d2959e5

**Comment by pranavmappoli** [comment] 2023-08-31 20:39
Contributor details
Your Expensify account email: [pranavmappoli@gmail.com](mailto:pranavmappoli@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01a31facdaca69896a

**Comment by pranavmappoli** [comment] 2023-08-31 20:46
Contributor details
Your Expensify account email: pranavmappoli@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a31facdaca69896a

**Comment by kadiealexander** [comment] 2023-09-01 01:26
Payouts due:

Contributor: $250 @adityaaa-r
Contributor+: $250 @allroundexperts

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~01e7b569deba9d346c).

**Comment by kadiealexander** [comment] 2023-09-01 01:27
@allroundexperts are you being paid in Upwork or NewDot?

**Comment by JmillsExpensify** [comment] 2023-09-01 02:49
Reviewed the details for @allroundexperts. $250 payment approved via NewDot based on BZ summary.

**Closed** 2023-09-01 03:20 UTC
Labels: Reviewing, External, Engineering, Daily, NewFeature
