### ISSUE TITLE
[HOLD for payment 2023-11-30] Chat not loading after redirection from OldDot

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#31498] opened 2023-11-17 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.0-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Context
We're testing a feature to redirect users that sign up on Expensify Classic (OldDot) to New Expensify. Sometimes, upon being redirected to NewDot, the app doesn't fully load, and the chat view shows the loading animation.

## Action Performed:
1. Open [staging.expensify.com](http://staging.expensify.com/)
2. Click on "Email" > enter any email address from a public domain that +classicredirect (that's what enables the redirection for now, while we test). For example: `your.name+classiredirect123@gmail.com` > click Next > Join
3. At that point you'll be redirected to NewDot, and the app should load on the Concierge chat. Sometimes, the Concierge chat doesn't get displayed

The issue doesn't always happen (maybe 1 in 10 times in my personal experience), so you might have to test multiple times in a row with different accounts.

## Expected Result:
The Concierge chat should be displayed.

## Actual Result:
The Concierge chat is not displayed, there's a loading animation in the chat view instead.

## Platforms:
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/2229301/6b258ef2-d860-4b15-891b-66b87386b5b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by koko57** [comment] 2023-11-17 18:09
I can help with this issue 🙂

**Comment by danielrvidal** [comment] 2023-11-18 03:57
@koko57 let us know how we can help diagnose! We're trying to get this one cleared asap.

**Comment by roryabraham** [comment] 2023-11-19 16:02
The problem appears to be [`LogOutPreviousUserPage`](https://github.com/Expensify/App/blob/main/src/pages/LogOutPreviousUserPage.js). If the user wasn't already signed in with a different account, and the page is missing the `shouldForceLogin` route param, it will just display a spinner forever. Unless I'm missing something this seems like the problem?

**Comment by roryabraham** [comment] 2023-11-19 16:06
There are two places in OldDot PHP where this redirection happens AFAICT:

- [for new users](https://github.com/Expensify/Web-Expensify/blob/4efe6a67862dd94f17341b72e02d369ce736e1c4/lib/Authentication.php#L493-L499)
- [here](https://github.com/Expensify/Web-Expensify/blob/4efe6a67862dd94f17341b72e02d369ce736e1c4/lib/Authentication.php#L493-L499)

And in neither case is `shouldForceLogin` included in the URL

**Comment by roryabraham** [comment] 2023-11-19 16:11
This is very consistently reproducible for me if you sign in as a new user on OldDot without being signed in to an account on NewDot

**Comment by roryabraham** [comment] 2023-11-19 16:41
Ok, I think I've figured out the race condition at play here...

### "Happy" path (haven't observed yet)
1. Redirect from OldDot
1. `PublicScreens` mounts.
1. `LoginWithShortLivedAuthToken` page renders: https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/Navigation/AppNavigator/PublicScreens.js#L23-L27
1. [Session.signInWithShortLivedAuthToken](https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/LogInWithShortLivedAuthTokenPage.js#L61) happens
1. Sign in completes and `LoginWithShortLivedAuthToken` page renders again, the `useEffect` runs, and [exitTo](https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/LogInWithShortLivedAuthTokenPage.js#L71-L76) navigation happens. _Note:_ I think there are potentially _multiple_ reasons this might not happen:
    - As soon as sign-in completes, the `PublicScreens` will unmount and `AuthScreens` will mount. I think that consistently happens before `LoginWithShortLivedAuthToken` re-renders, because it's further up the tree
    - There's nothing in the `props.route` that will change as a result of calling `Session.signInWithShortLivedAuthToken`. So even if the component re-renders, [the `useEffect` won't](https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/LogInWithShortLivedAuthTokenPage.js#L79)
    
### What actually happens 100% of the time AFAICT
1. Redirect from OldDot
1. `PublicScreens` mounts
1. `LoginWithShortLivedAuthToken` page renders: https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/Navigation/AppNavigator/PublicScreens.js#L23-L27
1. [Session.signInWithShortLivedAuthToken](https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/LogInWithShortLivedAuthTokenPage.js#L61) happens
1. `PublicScreens` unmounts and `AuthScreens` mounts.
1. `LogOutPreviousUserPage` renders
    1. [this redundant call to `Session.signOutAndRedirectToSignIn()` never happens (which, we don't want it to happen anyways...)
    1. [`shouldForceLogin`](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/LogOutPreviousUserPage.js#L40) is false.
    1. So literally nothing else happens and we get an infinite spinner

**Comment by roryabraham** [comment] 2023-11-19 17:48
Quick and dirty fix: https://github.com/Expensify/App/pull/31522

However, I think that some work to clean up and simplify this flow would be valuable. We can have only one transition page that works if a user is:

1. Already signed in
1. Signed in to the wrong account
1. Provided an `exitTo`, or not
1. etc...

and then we could create E2E tests for all those flows. I noticed a number of redundancies and seemingly unnecessary complexities while looking through this code.

**Comment by quinthar** [comment] 2023-11-19 19:10
If this issue only happens when you're already signed in, I think this isn't a blocker

**Comment by koko57** [comment] 2023-11-20 10:27
tried to reproduce the bug many times (with changing the network throttling, being logged in as another user or logged out) but I couldn't reproduce it even once. 

I think Rory's right - the user is stuck on LogOutPreviousUserPage.

**Comment by koko57** [comment] 2023-11-20 13:44
@roryabraham in what scenarios shouldForceLogin is sent with the URL?

**Comment by roryabraham** [comment] 2023-11-21 00:28
All that's left here is C+ payment

**Comment by roryabraham** [comment] 2023-12-09 02:23
Friendly bump to process payment here @kevinksullivan

**Comment by kevinksullivan** [comment] 2023-12-11 21:10
Ah it's just @allroundexperts , so summarizing payment:

- @allroundexperts : $750

**Comment by allroundexperts** [comment] 2023-12-11 23:49
@kevinksullivan I think it should be $500.

**Comment by kevinksullivan** [comment] 2023-12-12 03:09
Thanks @allroundexperts , I'll let you submit the request and close this out.

**Closed** 2023-12-12 03:10 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:59
$500 payment to @allroundexperts based on summary above.
