### ISSUE TITLE
Chats are showing wrong current time of the user chatting with 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43438] opened 2024-06-10 22:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @RachCHopkins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717991929286819

## Action Performed:
Precondition : user A and user B are in different timezones

1. User A sent a message to user B
2. Observe the timestamp of the chat as user B

## Expected Result:
Should show the time of user A
## Actual Result:
Showing the user B time in PST, after switching to another chat and coming back shows correct time
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![2024-06-10_15-54-22](https://github.com/Expensify/App/assets/38435837/53b0cae3-26a5-421d-9fd0-cdadf2ed27fd)

![Screenshot 2024-06-10 at 12 14 34 PM](https://github.com/Expensify/App/assets/38435837/4a9334fb-4872-457b-97cd-ec79381906c0)

![Screenshot 2024-06-10 at 12 11 29 PM](https://github.com/Expensify/App/assets/38435837/d78de7c5-a428-48f7-8101-acb76b1b2eac)

https://github.com/Expensify/App/assets/38435837/704383d5-7675-4437-8f99-d4d4291d346d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2024-06-11 00:57
I'm not able to reliably reproduce, nor is @luacmartins from [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1718060721981099?thread_ts=1718058891.229099&cid=C01GTK53T8Q).

**Comment by RachCHopkins** [comment] 2024-06-11 01:00
@NikkiWines I'm finding for me the Social keeps switching to PST. I wonder if changing your timezone for a week might surface it?

**Comment by NikkiWines** [comment] 2024-06-11 01:04
@RachCHopkins is this happening on staging only or staging and production?

**Comment by NikkiWines** [comment] 2024-06-11 03:00
Not a deploy blocker - reproducible on [prod](https://expensify.enterprise.slack.com/archives/C049HHMV9SM/p1718072977562929?thread_ts=1717991929.286819&channel=C049HHMV9SM&message_ts=1718072977.562929)

**Comment by bernhardoj** [comment] 2024-06-11 07:16
The pusher always sends the LA timezone data to the user when receiving the message.
<img width="517" alt="image" src="https://github.com/Expensify/App/assets/50919443/2c6d1535-3106-4402-a6e9-09f746592527">

**Comment by tgolen** [comment] 2024-06-12 15:06
I see it coming from the response to `AddComment`, so I think this is a backend issue.

![image](https://github.com/Expensify/App/assets/1228807/98dbfe61-43d8-4e94-b4d6-99a3932a4229)

I'm not sure exactly what it takes to reproduce it, but I've had it happen twice today. If I go into my settings, the timezone is correct for me, and then when I return to the chat, the timestamps are correct again.

After a little bit of chatting, the timestamps then revert to PST.

**Comment by NikkiWines** [comment] 2024-06-14 07:32
Fairly certain this issue is a dupe of https://github.com/Expensify/App/issues/43032, which shows almost identical behavior. I think we should close this one out in favor of that one. 

cc: @MonilBhavsar since you've been able to reproduce this bug.

**Comment by MonilBhavsar** [comment] 2024-06-14 10:10
Feel free to. There are three issues now, I'll go ahead and remove "Needs reproduction" label on the other issue 😆

**Closed** 2024-06-14 16:47 UTC
Labels: Engineering, Daily, Bug
