### ISSUE TITLE
[$1000] Workspace - WS Image return to default after updated offline but updated on second device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22177] opened 2023-07-04 14:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a Workspace settings
2. Disable the internet connection in the device
3. Upload new avatar
4. Go back online

## Expected Result:
Verify the avatar is not grayed out anymore & that it updates in all pages and chats.
Verify the avatar is updated on the secondary device logged in to the same account

## Actual Result:
WS Image return to default after updated offline but updated on second device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3266c1cc-cabb-48b4-9a92-005e124ec536

<img width="1369" alt="Bug6116006_image" src="https://github.com/Expensify/App/assets/78819774/3ece4941-2721-4da3-a4a4-8c000c2a4966">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed3f28edfb08f57c</li>
        <li>Upwork Job ID: 1676259807370477568</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-04 16:00
I can repro this one on the latest staging:

https://github.com/Expensify/App/assets/16232057/bb2b5398-62ae-410e-9cfb-1cfe168f310b

**Comment by Kacppian** [comment] 2023-07-04 19:25
## Please re-state the problem that we are trying to solve in this issue.

WS Image return to default after updated offline but updated on second device

## What is the root cause of that problem?

I've noticed that it doesn't matter if the workspace avatar is being uploaded during offline or online network modes. The avatar doesn't get updated either way. 

This is happening because the API hit for `UpdateWorkspaceAvatar` does get a 200 in response with the correct avatar url, it's subsequently overridden by the response from `api?command=ReconnectApp` which sets the avatar url to an empty string. This causes the Avatar component to render the default avatar for the WS.

I don't think `UpdateWorkspaceAvatar` is actually updating the image anywhere because upon refresh ( on browser ), the avatar is again reverted to the default avatar.

https://github.com/Expensify/App/assets/14990078/17c2d4f4-2202-43d4-a154-feabbf1e8761

<img width="1511" alt="expensify-log" src="https://github.com/Expensify/App/assets/14990078/7831018f-06fe-4db9-ac3d-8217afd86cb3">


## What changes do you think we should make in order to solve the problem?

Either `UpdateWorkspaceAvatar` isn't storing the image anywhere but it's emitting update events with the right information or the policy data that is getting fetched isn't honoring `UpdateWorkspaceAvatar`.

**Comment by erhanyasar** [comment] 2023-07-04 21:07
Hey @MelvinBot,

Can you tell me which issues are not assigned to someone?

Contributor details
Your Expensify account email: mail@erhanyasar.com.tr
Upwork Profile Link: https://www.upwork.com/freelancers/~0113c56b211f019303

**Comment by trjExpensify** [comment] 2023-07-05 11:48
@erhanyasar - anything with the `help wanted` label in the repo is open to proposals! :)

**Comment by s-alves10** [comment] 2023-07-05 11:53
This is the backend issue. After upload the new workspace avatar, getting the workspace data returns empty avatar

**Comment by Kacppian** [comment] 2023-07-05 13:13
@trjExpensify is this something that will be marked as internal then? since the issue is with the backend. Asking because it's my first time here so still figuring stuff out.

**Comment by erhanyasar** [comment] 2023-07-05 13:32
> @erhanyasar - anything with the `help wanted` label in the repo is open to proposals! :)

I asked bacause there was assigned people for almost all of the issues listed as help wanted.

**Comment by Kacppian** [comment] 2023-07-05 13:50
hmm, it's still happening at https://staging.new.expensify.com/ Could you list down the steps you're taking to reproduce this?

**Comment by trjExpensify** [comment] 2023-07-05 14:18
>I asked bacause there was assigned people for almost all of the issues listed as help wanted.

Ah, gotcha. The two people assigned right away is a member of the Expensify team and a member of our ContributorPlus team that will conduct the proposal reviews. Simply put, if the `help wanted` label is on the issue feel free to put in a proposal! Only once we've chosen a proposal and assigned a Contributor will the label be removed. :) 

>@trjExpensify is this something that will be marked as internal then? since the issue is with the backend. Asking because it's my first time here so still figuring stuff out.

I'd love to have that confirmed first before it goes internal as a backend issue.

**Comment by Christinadobrzyn** [comment] 2023-07-05 17:48
Hey @thesahindia could you double-check this GH and see if it will be resolved with this fix?https://github.com/Expensify/App/issues/22241

**Comment by trjExpensify** [comment] 2023-07-10 10:37
@thesahindia what are the next steps here? Did you retest, and what steps did you follow/do you have a screen recording?

**Closed** 2023-07-10 11:25 UTC
Labels: External, Daily, Help Wanted, Bug
