### ISSUE TITLE
[Awaiting Payment][$1000] Web - The error doesn't clear immediately after reloading the contact method verify page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23813] opened 2023-07-28 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to setting > profile > contact method
2. Click on add contact method
3. Add a new contact method
4. Click on this contact method to verify
5. Enter a random magic code to make the error appears
6. Reload the page and notice the error

## Expected Result:
The error should clear immediately after reloading the page

## Actual Result:
The error doesn't clear immediately

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 28-07-2023 18_05_23.webm](https://github.com/Expensify/App/assets/93399543/25fa6122-918c-4e93-9eec-682e9f2b3187)

https://github.com/Expensify/App/assets/93399543/b422eafd-cb89-48a6-93ba-7d0c3ed4fa3f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690542294914639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140f90e5805b83227</li>
        <li>Upwork Job ID: 1684997840572416000</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>WikusKriek | Contributor | 26183374</li>
<li>dukenv0307 | Reporter | 26183376</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-28 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error doesn't clear immediately after reloading the contact method verify page.

### What is the root cause of that problem?
The error message is stored in `loginList` `onyx` data.
But when reloading the contact method verify page, these data does not clear.
Therefore the error is still shown.
### What changes do you think we should make in order to solve the problem?
We should clear `loginList` `onyx` data in `componentDidUpdate` in `ContactMethodDetailsPage`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by garrettmknight** [comment] 2023-07-28 18:42
Confirmed error on staging

**Comment by mananjadhav** [comment] 2023-07-28 21:01
Thanks for the proposal @StevenKKC.  I get that the proposal works, and the RCA is also correct. But I am going to have to confirm if we're okay to clear these messages.


🎀 👀 🎀 C+ reviewed.

**Comment by DreamSoft0888** [comment] 2023-07-29 03:31
Hello, everyone!
I am the professional web/mobile app developer who have full experience 8 years.
How can I join this project dev team?
Regards.

Janitha!

**Comment by DreamSoft0888** [comment] 2023-07-29 03:35
Contributor details
My expensify account email: janithaamaradasa0888@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015084d5d2f275fda4

**Comment by rahatcse5bu** [comment] 2023-07-29 05:45
Contributor details
Your Expensify account email: rahat.cse5.bu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015e503612775150e8

**Comment by DreamSoft0888** [comment] 2023-07-29 09:49
Contributor details
Your Expensify account email: janithaamaradasa0888@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015084d5d2f275fda4

**Comment by codewithwaheed** [comment] 2023-07-29 12:32
Contributor details
Your Expensify account email: ahmadwaheed359@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018273a94f8b5612b2

**Comment by fitrahfm** [comment] 2023-07-29 13:30
Contributor details
Your Expensify account email: [fitrahmunir@outlook.com](fitrahmunir@outlook.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01371a1db1c89368c1

**Comment by fitrahfm** [comment] 2023-07-29 13:33
Contributor details
Your Expensify account email: fitrahmunir@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01371a1db1c89368c1

**Comment by djabdou** [comment] 2023-07-29 22:05
Contributor details
Your Expensify account email: elkrim226@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dd4198edd7453dc0

**Comment by vikasg603** [comment] 2023-07-30 19:58
Contributor details
Your Expensify account email: [vikasg603@gmail.com](mailto:vikasg603@gmail.com)
Upwork Profile Link:
https://www.upwork.com/fl/~01f7dc9882e7ca6768

**Comment by vikasg603** [comment] 2023-07-30 19:59
Contributor details
Your Expensify account email: vikasg603@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01f7dc9882e7ca6768

**Comment by vikasg603** [comment] 2023-07-30 20:01
Contributor details
Your Expensify account email: vikasg603@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/vikasg603

**Comment by mananjadhav** [comment] 2023-07-30 20:26
@johnmlee101 We can either clear all or just the validate code input and based on that choose one of the proposals. Can you confirm the expected behavior?

**Comment by garrettmknight** [comment] 2023-08-02 20:31
@johnmlee101 can you confirm expected behavior [here](https://github.com/Expensify/App/issues/23813#issuecomment-1657260146)?

**Comment by johnmlee101** [comment] 2023-08-04 16:04
Let's only clear the validate code field @mananjadhav, I feel like thats safer than clearing all fields.

**Comment by garrettmknight** [comment] 2023-08-07 16:44
@mananjadhav since we've confirmed, are we hiring @StevenKKC for this one?

**Comment by garrettmknight** [comment] 2023-08-10 09:37
@mananjadhav Any thoughts on these proposals? It's been a few weeks since we've moved the needle here.

**Comment by mananjadhav** [comment] 2023-08-10 09:49
thanks for the bump @garrettmknight. I had reviewed this earlier so it was off my radar. Checking through the last messages I am in a bit of a tight spot. Most proposals mention the correct RCA and similar solutions.

But based on the [confirmation](https://github.com/Expensify/App/issues/23813#issuecomment-1665853659) I am going to choose @WikusKriek's proposal [here](https://github.com/Expensify/App/issues/23813#issuecomment-1665676235), because it has the most recent updated proposal with the correct behavior. (considering useEffect).

I understand that earlier when the issue was, it would've been a class component, but considering we had enough time to revise the proposals, I am going to still select the one which considers the function component.

cc - @johnmlee101 .

**Comment by mananjadhav** [comment] 2023-08-13 11:45
I still feel we should be doing this in `BaseValidateCodeForm`, unless it causes any regression.

**Comment by mananjadhav** [comment] 2023-08-13 18:05
@WikusKriek I would strongly advise against creating the PRs for the issues that aren't officially assigned to you. Please wait for the GH issue to be assigned to you to work on the PR. Thanks for the patience.

**Comment by mananjadhav** [comment] 2023-08-16 04:50
Thanks for understanding. @johnmlee101 Quick bump.

**Comment by mananjadhav** [comment] 2023-08-25 18:21
This was deployed on production 2 days, but the title wasn't updated.

**Comment by garrettmknight** [comment] 2023-09-04 10:08
Oops, yep, let me process now.

**Comment by garrettmknight** [comment] 2023-09-04 10:13
**Summary of payments for this issue:**

- #urgency bonus? Yes
- Reporter: @dukenv0307 - $250 paid via Upwork
- Contirbutor: @WikusKriek - $1500 paid via Upwork
- Contributor+: @mananjadhav - $1500

Upwork job: https://www.upwork.com/jobs/~0129c8265c6b7e57ae

**Comment by JmillsExpensify** [comment] 2023-09-10 11:27
$1,500 payment approved via NewDot based on BZ summary.

**Comment by mananjadhav** [comment] 2023-09-12 17:32
@JmillsExpensify @garrettmknight We're good to close this one?

**Comment by garrettmknight** [comment] 2023-09-14 11:35
@mananjadhav can you complete the checklist?

**Comment by mananjadhav** [comment] 2023-09-17 16:59
I can't attribute this to a specific offending PR. We are not clearing the code is something that we have had since `BaseValidationCodeForm` component was created. It's a base component, where we've fixed the change.  Hence I don't think we would have the issue again. This is the reason, I don't think we need a regression test for this one.

**Comment by garrettmknight** [comment] 2023-09-21 08:44
Thanks, we can close now.

**Closed by garrettmknight** 2023-09-21 08:44 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
