### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] Chat - Pressing Tab closes emoji picker on Desktop or moves focus to the composer on Web

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31098] opened 2023-11-09 08:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop App
2. Login with any account
3. Go to any chat
4. Open emoji picker
5. Press 'Tab' key

## Expected Result:
Focus moves to the next item -> from 'Search' field to ‘Frequently Used’ icon

## Actual Result:
Pressing Tab closes emoji picker on Desktop or moves focus to the composer on Web (Safari)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/b2b2aff5-1228-4513-ba6b-886ae731fd96

https://github.com/Expensify/App/assets/115492554/9794e901-01af-4ec6-96ca-213334c55a93

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016146f3b3888a9471</li>
        <li>Upwork Job ID: 1722537804750688256</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27591485</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by blazejkustra** [comment] 2023-11-09 09:32
Looking into it as it was caused by TS Pressable migration.

**Comment by blazejkustra** [comment] 2023-11-09 11:12
> Regression from #30777. All pressable `tabIndex` is -1 which does not allow us to navigate with TAB key.
> 
> https://github.com/Expensify/App/blob/5a940953038fcecb7a963dcd7585fca185cc5b49/src/components/Pressable/GenericPressable/index.tsx#L13
> 
> Both `accessible` and `focusable` are undefined. Previously, `accessible` default value is `true`.

Actually it isn't a regression from Pressable migration PR. I verified this when I reverted Pressable migration on the newest main. I think [RN-web upgrade](https://github.com/Expensify/App/pull/24482/commits/f4f44ae190084df7d4ff5ee60074d81a4777573e) caused the regression.

**Comment by blazejkustra** [comment] 2023-11-09 11:16
That being said I think the [proposal](https://github.com/Expensify/App/issues/31098#issuecomment-1803456275) proposed by @tienifr seems to fix it!

**Comment by mountiny** [comment] 2023-11-09 11:28
Ideally also verify it by reverting the PR. @tienifr Are you able to create the PR quickly?

**Comment by mountiny** [comment] 2023-11-09 11:29
Please go ahead!

**Comment by mountiny** [comment] 2023-11-09 13:35
Asking for a CP

**Comment by mountiny** [comment] 2023-11-09 14:26
Fixed only payment to @tienifr for the fix, $500

**Comment by mountiny** [comment] 2023-11-15 08:26
@tienifr Can you please handle the checklist?

**Comment by mountiny** [comment] 2023-11-15 12:12
The offending PR was identified as the RNW upgrade https://github.com/Expensify/App/pull/24482/commits/f4f44ae190084df7d4ff5ee60074d81a4777573e, it changed someexpected behavioru, it was  auge lift and big upgrade which had lots of small regressions we are aware of. No need to start discussion.

No regression test required imho, its an edge case.

@isabelastisser should bre ready to be paid

**Comment by situchan** [comment] 2023-11-17 15:01
There are some flags that the PR caused these regressions: #31203, #31488

**Comment by isabelastisser** [comment] 2023-11-27 17:33
@tienifr, I just made the payment in Upwork. All set!

**Closed by isabelastisser** 2023-11-27 17:33 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug
