### ISSUE TITLE
Dialog close button's tooltip appears behind the modal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14179] opened 2023-01-10 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Press CMD + I to open shortcuts modal.
2. Hover over the modal close button.

## Expected Result:
The tooltip should appear above the dialog

## Actual Result:
The tooltip appears below the dialog.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211583060-d00e3952-1153-4f1e-8cd4-bde9a3bf6854.mov
<img width="1440" alt="Screen Shot 2023-01-10 at 9 47 38 AM" src="https://user-images.githubusercontent.com/43996225/211583500-25e408cd-0752-4e14-b823-fe62ee445f32.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priyeshshah11
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1673265634674769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2023-01-11 18:34
I'm not able to reproduce this one. I'm on Chrome, staging, v1.2.52-4. 
<img width="801" alt="Screen Shot 2023-01-11 at 10 32 39 AM" src="https://user-images.githubusercontent.com/8292562/211889293-1203233c-6906-4c82-a58f-3c3cb8fbc38e.png">

**Comment by luacmartins** [comment] 2023-01-18 00:18
I'm also unable to reproduce.

**Comment by tjferriss** [comment] 2023-01-18 06:35
@priyeshshah11 are you still able to reproduce this or should we close it?

**Comment by luacmartins** [comment] 2023-01-18 15:52
@priyeshshah11 confirmed that it was fixed, most likely by [this PR](https://github.com/Expensify/App/pull/14048). Closing.

**Closed by luacmartins** 2023-01-18 15:52 UTC
Labels: Daily, Needs Reproduction, Bug
