### ISSUE TITLE
BUG: LHN is showing HTML tags for messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11955] opened 2022-10-18 02:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to a DM
2. Type several words
3. Press shift + return on your keyboard to start a new line
4. Type several more words

## Expected Result:
No HTML characters in the LHN

## Actual Result:
The message looks normal in the chat window, but in the left hand navigation you see the HTML

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.17-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![File](https://user-images.githubusercontent.com/43996225/196325421-202e3831-7b5b-4c68-9c06-300d6a54da33.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665793255116619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-10-18 19:59
Going to take this one from you @muttmuure as I'm going to re-test now.

**Comment by JmillsExpensify** [comment] 2022-10-18 20:01
Hmmm, this is super odd. I'm not sure if this was a fluke, but I'm unable to reproduce this issue on 1.2.17-4. Closing but I'll re-open if I notice it shows up again.

**Closed by JmillsExpensify** 2022-10-18 20:01 UTC
Labels: Daily, Needs Reproduction
