### ISSUE TITLE
Warning presented when starting Metro dev server

### ISSUE THREAD

**Issue by szymonrybczak** [Expensify/App#49155] opened 2024-09-13 08:53 UTC
### Problem

Currently when starting a development server with `npm start` a warning is produced:
```
❯ npm start

> new.expensify@9.0.31-12 start
> npx react-native start

warn =================================================================================================
warn From React Native 0.73, your project's Metro config should extend '@react-native/metro-config'
warn or it will fail to build. Please copy the template at:
warn https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn This warning will be removed in future (https://github.com/facebook/metro/issues/1018).
warn =================================================================================================
info Welcome to React Native v0.75
info Starting dev server on port 8081...

                        ▒▒▓▓▓▓▒▒
                     ▒▓▓▓▒▒░░▒▒▓▓▓▒
                  ▒▓▓▓▓░░░▒▒▒▒░░░▓▓▓▓▒
                 ▓▓▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▓▓
                 ▓▓░░░░░▒▓▓▓▓▓▓▒░░░░░▓▓
                 ▓▓░░▓▓▒░░░▒▒░░░▒▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▒▒▒▒▓▓▓▓▒░░▓▓
                 ▓▓░░▓▓▓▓▓▓▓▓▓▓▓▓▓▒░░▓▓
                 ▓▓▒░░▒▒▓▓▓▓▓▓▓▓▒░░░▒▓▓
                  ▒▓▓▓▒░░░▒▓▓▒░░░▒▓▓▓▒
                     ▒▓▓▓▒░░░░▒▓▓▓▒
                        ▒▒▓▓▓▓▒▒


                Welcome to Metro v0.80.3
              Fast - Scalable - Integrated
```

It’s because current config uses `getDefaultConfig` function `expo/metro-config` which doesn’t assign `__REACT_NATIVE_METRO_CONFIG_LOADED` property on `global` object which is then checked inside `@react-native/community-cli-plugin` package, [if not presented the warning is produced](https://github.com/facebook/react-native/blob/6243a33978b358a2a37bf9fc2f2b995adb03b8d6/packages/community-cli-plugin/src/utils/loadMetroConfig.js#L97-L110). 

### Solution

Suggested solution from Metro team is to use a `getDefaultConfg` function from `@react-native/metro-config` package to extend the config which provides default values for Metro config. 

Diff to solve this issue inside `metro.config.js` file:

```diff
@@ -1,10 +1,13 @@
-const {getDefaultConfig} = require('expo/metro-config');
+const {getDefaultConfig: getExpoDefaultConfig} = require('expo/metro-config');
+const {getDefaultConfig: getReactNativeDefaultConfig} = require('@react-native/metro-config');
+
 const {mergeConfig} = require('@react-native/metro-config');
 const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;
 const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts;
 require('dotenv').config();

-const defaultConfig = getDefaultConfig(__dirname);
+const defaultConfig = getReactNativeDefaultConfig(__dirname);
+const expoConfig = getExpoDefaultConfig(__dirname);

 const isE2ETesting = process.env.E2E_TESTING === 'true';
 const e2eSourceExts = ['e2e.js', 'e2e.ts', 'e2e.tsx'];
@@ -23,4 +26,4 @@ const config = {
     },
 };

-module.exports = mergeConfig(defaultConfig, config);
+module.exports = mergeConfig(defaultConfig, expoConfig, config);
```

Provided solution also keeps values and properties from default config from `expo/metro-config` package. By merging them in relevant order we keep the same behavior with proper config creation.

**Comment by mountiny** [comment] 2024-09-13 09:17
This is mainly to improve developer experience so I think it's worth it to make this change if everything else will remain working the same

**Comment by szymonrybczak** [comment] 2024-09-13 09:38
FYI I checked how Metro Config changes after applying proposed diff and there's only one object added related to TerminalReporter and rest properties and values stays the same, so IMO it shouldn't affect anyone.

**Comment by mananjadhav** [comment] 2024-09-13 10:40
@mountiny This looks like a no QA PR, should I just approve it and you'll take it forward? or do you want me to work on the checklist for this one.

**Comment by mountiny** [comment] 2024-09-13 21:00
@mananjadhav Agreed no need for Qa thanks!

**Comment by mountiny** [comment] 2024-09-13 21:25
PR merged, and no payment or regression testing is required, so we are going to close this. The main purpose of the change is improvement to developer experience

**Closed by mountiny** 2024-09-13 21:25 UTC
Labels: Reviewing, Weekly, Bug
