### ISSUE TITLE
[HOLD for payment 2024-12-03] [Company cards] Navigate to some other existing feed after removing one

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#52886] opened 2024-11-21 11:27 UTC
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1732116549221049?thread_ts=1732108983.281759&cid=C06ML6X0W9L)

When user has 2 or more company card feeds and we remove one of them, make sure to navigate them and show them some other feed right after the removal. No particular order, just take the first one in the domain_member object

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by mountiny** [comment] 2024-11-21 11:28
No need for b0

**Comment by VickyStash** [comment] 2024-11-21 14:12
The [PR](https://github.com/Expensify/App/pull/52893) is opened for the review.

**Comment by DylanDylann** [comment] 2024-12-03 09:38
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mountiny** [comment] 2024-12-03 11:20
@DylanDylann can you please add comments or link prs in all the checklist sections?

**Comment by DylanDylann** [comment] 2024-12-03 11:24
@mountiny 

> [Contributor] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

About this point, this is not a bug, when implementing this feature we already missed from the design doc

**Comment by mountiny** [comment] 2024-12-03 11:38
Ok, nice feel free to leave such quick note in the checklist in future

**Comment by mountiny** [comment] 2024-12-03 11:38
@bfitzexpensify lets please add this regression test

**Comment by bfitzexpensify** [comment] 2024-12-03 21:59
Regression steps proposed. @DylanDylann offer sent for payment.

**Comment by DylanDylann** [comment] 2024-12-04 02:33
No need payment here. Let's close this issue

**Closed** 2024-12-04 12:31 UTC
Labels: Daily, Awaiting Payment, Bug
