### ISSUE TITLE
[$1000] Inconsistency when showing user profile when clicking from assignee task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23324] opened 2023-07-21 01:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat with new user not chat before
2. Click + in composer
3. Assign task
4. Enter title => Next
5. Assign task for user above => Confirm
6. Go to the chat report with this user
7. Click header, observed that the email is not showing
8.  Dismiss the modal and click into the email assignee on the task preview
9.  observed that the email is showing
## Expected Result:
 In step 9 will not show email when user not chat before (Expected behavior has been verified [here](https://github.com/Expensify/App/issues/23324#issuecomment-1648291208))
## Actual Result: 
Step 9 is show email when the user does not chat before

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3c9b4439-caf9-48f3-a65d-2e5e00ece61b

https://github.com/Expensify/App/assets/43996225/220e7169-f70a-435b-8a80-9e75fe6e6049

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689767608945819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127e383c694e14d1d</li>
        <li>Upwork Job ID: 1683525402211966976</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-21 03:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a task is assigned to a user with whom no prior chat has occurred, their email address is not displayed upon clicking the chat header. However, the email is shown when it is clicked on the task preview.

### What is the root cause of that problem?
The inconsistency occurs because the email address is fetched in the `ProfilePage `using this line of code: `const login = lodashGet(details, 'login', '');`. At times, however, this 'login' field isn't populated initially and the 'displayName' field contains the email address instead.

### What changes do you think we should make in order to solve the problem?
To fix this, the condition could be modified to fetch the email address from either the `login` or `displayName` field, whichever is available. Here's how it can be done:

`const login = lodashGet(details, 'login', '') || lodashGet(details, 'displayName', '');
`
By using this modified condition, the email address will be displayed correctly and consistently.

**Comment by johncschuster** [comment] 2023-07-21 20:41
Asked a clarifying question in the Slack thread [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689767608945819).

**Comment by johncschuster** [comment] 2023-07-24 17:11
Thanks for the clarifying comments in Slack!

From this comment https://github.com/Expensify/App/issues/22192#issuecomment-1643736327 from `@Beamanator`

```
The email NOT showing up in this case was by design - if you don't "know" the user, you won't get their login in the returned personal details

cc `@puneetlath` as we both worked on this project

I believe we should :donothing: here

`@lanitochka17` when you created this issue, you mentioned Slack conversation: Yes but you didn't link a slack convo
```

**Comment by daordonez11** [comment] 2023-07-25 14:04
@allroundexperts This issue would be a dupe of https://github.com/Expensify/App/issues/22074 same root cause. We are waiting for some definitions in backend and it is currently being worked by Aldo!

cc @johncschuster

**Comment by luacmartins** [comment] 2023-07-25 16:39
I think this is intended since we typed the user's email and thus know it. That's different from the case where we don't type the email and don't know the user. I think we can close this issue.

**Closed by luacmartins** 2023-07-25 16:39 UTC
Labels: External, Daily, Help Wanted, Bug
