### ISSUE TITLE
[$250] Chat - Text in compose box blends with background when theme was changed in device settings

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39348] opened 2024-04-01 10:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+omq23@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user should be Signed In and "Use Device Settings" option should be selected for theme option in Preferences

Web, Desktop and mWeb steps:

1. Open https://staging.new.expensify.com/

2. Open any chat
3. Navigate to device settings and change the theme to the opposite color
4. Navigate back to browser or app
5. Write any text in compose box

iOS steps:
1. Open https://staging.new.expensify.com/

2. Open any chat
3. Write any text in the compose box
4. Navigate to device settings and change the theme to the opposite color
5. Navigate back to app

## Expected Result:
Text should be properly displayed in compose box.

## Actual Result:
The text in the compose box retains its original color despite changes to the background color. Consequently, it blends with the background when the device theme is switched to the opposite color.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6ebf4449-e7a1-4ca3-9881-5f747cbc64ae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5c49154255020bb</li>
        <li>Upwork Job ID: 1776299979557351424</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-01 10:59
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-01 10:59
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-01 11:01
Production 


https://github.com/Expensify/App/assets/115492554/c798f720-6e0b-41a7-9954-6ee9b4ffb099

**Comment by nkdengineer** [comment] 2024-04-01 12:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text in the compose box retains its original color despite changes to the background color. Consequently, it blends with the background when the device theme is switched to the opposite color.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/react-native-live-markdown/blob/d8205aa0bf6d922cbf0aea9eaa210b6375187ddc/src/MarkdownTextInput.web.tsx#L255), we forgot to put `flattenedStyle.color` to the dependency list.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/react-native-live-markdown/blob/d8205aa0bf6d922cbf0aea9eaa210b6375187ddc/src/MarkdownTextInput.web.tsx#L255), put `flattenedStyle.color` to the dependency list.

### What alternative solutions did you explore? (Optional)
NA

**Comment by MariaHCD** [comment] 2024-04-01 13:20
Reassigning C+ for urgency: https://expensify.slack.com/archives/C02NK2DQWUX/p1711977525194839?thread_ts=1711977461.265819&cid=C02NK2DQWUX

**Comment by MariaHCD** [comment] 2024-04-01 13:36
Looks like this one can't be external since it pertains to the react-native-live-markdown repo

https://expensify.slack.com/archives/C02NK2DQWUX/p1711978269008509?thread_ts=1711977461.265819&cid=C02NK2DQWUX

**Comment by nkdengineer** [comment] 2024-04-01 14:30
> @nkdengineer We have not yet allowed external contributors to commit to the react-native-live-markdown.

@shubham1206agra Could you link to a discussion in GH/Slack which states this, or an official doc saying so (and the reason why it's decided as such if there is one)?

Thanks

**Comment by nkdengineer** [comment] 2024-04-01 15:01
@shubham1206agra No issue, I can ask again in the #expensify-open-source channel. 

But earlier it seems my Slack access was accidentally removed, I've requested to access again via email, but so far no response yet.

@MariaHCD Could you help to ask someone that handles Slack invites, to extend an invite to me again? My email is nkdengineer@gmail.com

Appreciate it!

**Comment by marcaaron** [comment] 2024-04-01 22:01
Bump everyone in this thread. What's the resolution here? I'm not sure based on the context left. Thanks!

**Comment by MariaHCD** [comment] 2024-04-02 04:30
We've brought this to the attention of SWM since it looks like the fix is needed in the react-native-live-markdown repo.

I reported the same in the #react-native-live-markdown channel as well: https://expensify.slack.com/archives/C06BDSWLDPB/p1712032135082779

Essentially, I think this shouldn't block the app deploy and can be included in the tracking issue: https://github.com/Expensify/App/issues/36071

**Comment by thienlnam** [comment] 2024-04-02 14:50
Added as a MED in the tracking issue

**Comment by MariaHCD** [comment] 2024-04-04 05:46
Going to reassign this one to @thienlnam and @BartoszGrajdek

**Comment by BartoszGrajdek** [comment] 2024-04-04 08:00
Hi! I'm Bartosz from SWM, let me take a look into it 👀

**Comment by thienlnam** [comment] 2024-04-05 17:25
Opening this to external contributors!

**Comment by nkdengineer** [comment] 2024-04-05 17:41
@hoangzinh FYI I already got [a proposal](https://github.com/Expensify/App/issues/39348#issuecomment-2029718951) above

**Comment by tomekzaw** [comment] 2024-04-05 23:06
The change described in the [proposal](https://github.com/Expensify/App/issues/39348#issuecomment-2029718951) has been independently applied in https://github.com/Expensify/react-native-live-markdown/pull/261 which has already been merged and released in `react-native-live-markdown@0.1.37` (currently the App uses `0.1.38`).

It seems like this bugs is already fixed on current main (please confirm) and we can close the issue.

**Comment by nkdengineer** [comment] 2024-04-08 11:37
> Based on this comment https://github.com/Expensify/App/issues/39348#issuecomment-2029838019, The react-native-live-markdown repo hasn't opened for external contributors yet. @thienlnam Is this issue still open for external contributors?

@hoangzinh Based on [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1712339365958949?thread_ts=1712314280.061879&cid=C01GTK53T8Q), we've started to open up the `react-native-live-markdown` issues to external contributors, including this one.

**Comment by nkdengineer** [comment] 2024-04-08 12:22
> Based on this comment https://github.com/Expensify/App/issues/39348#issuecomment-2029838019, The react-native-live-markdown repo hasn't opened for external contributors yet. @thienlnam Is this issue still open for external contributors?

I think @thienlnam can help confirm here.

**Comment by tomekzaw** [comment] 2024-04-08 15:05
I was able to reproduce the issue in Live Markdown example app, working on a fix for iOS native right now.

**Comment by tomekzaw** [comment] 2024-04-08 16:24
Found the root cause, fix incoming

**Comment by thienlnam** [comment] 2024-04-08 21:19
Sorry for the confusion - I have opened up some issues related this externally, but seems like @tomekzaw is already working on this and the fix requires changes in the original repo so I will be assigning to him

**Comment by tomekzaw** [comment] 2024-04-08 21:47
Should be fixed with https://github.com/Expensify/react-native-live-markdown/pull/269.

I will submit a PR with version bump soon.

**Comment by tomekzaw** [comment] 2024-04-08 22:11
Should be fixed with https://github.com/Expensify/App/pull/39872.

**Comment by BartoszGrajdek** [comment] 2024-05-13 12:01
@thienlnam can we get this tested & closed?

**Comment by mallenexpensify** [comment] 2024-05-21 01:20
Added @anmurali back as BZ (not sure if they're needed though, we just need BZs added to all bugs, in case they are).

**Comment by mvtglobally** [comment] 2024-05-22 04:42
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-05-23 00:03
Closing, also unable to repro (and.. now I'm in dark mode!)
<img width="351" alt="image" src="https://github.com/Expensify/App/assets/22508304/d03e1767-bf4b-49b2-a462-f4f7eb595af4">

**Closed by mallenexpensify** 2024-05-23 00:03 UTC
Labels: Engineering, Monthly, Bug, retest-weekly
