### ISSUE TITLE
[HOLD for payment 2024-04-29] IOS - Search - Extra padding below Referral banner in Search list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36038] opened 2024-02-07 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-38.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app.
2. Open search list.
3. Focus on the search field.

## Expected Result:
There is no extra padding below Referral banner in Search list.

## Actual Result:
There is extra padding below Referral banner in Search list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b4843316-f5e6-40cd-bd34-0fc30a2f3846

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by kbecciv** [comment] 2024-02-07 15:41
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by luacmartins** [comment] 2024-02-07 17:05
@lukemorawski are you able to work on a fix for this?

**Comment by luacmartins** [comment] 2024-02-07 17:06
I don't think we need to block deploy on this

**Comment by lukemorawski** [comment] 2024-02-08 09:46
@luacmartins no worries, will tackle that!

**Comment by lukemorawski** [comment] 2024-02-13 16:42
still working on that. It's actually more trickier than it look and I have found more related bugs to it. I'll hopefully drop a fix to it tomorrow.

**Comment by luacmartins** [comment] 2024-02-19 18:05
We have a draft PR up.

**Comment by lukemorawski** [comment] 2024-02-20 11:38
@luacmartins PR is open

**Comment by Julesssss** [comment] 2024-02-22 13:54
Assigning @abdulrahuman5196 based on [this comment](https://expensify.slack.com/archives/C02NK2DQWUX/p1708607683163729)

**Comment by luacmartins** [comment] 2024-04-24 14:45
Updated the issue. We had a [regression](https://github.com/Expensify/App/issues/40827) caused by that PR, could you please take a look?

**Comment by garrettmknight** [comment] 2024-04-29 10:05
Same [here](https://github.com/Expensify/App/issues/36038)

**Comment by johncschuster** [comment] 2024-05-09 21:35
Thanks for your patience, everyone! I've needed to make sense of the payments here since there was a regression and a different C+ reviewer. Here's what I've got:

Contributor: @lukemorawski - to be paid $250 ($500-50% regression deduction)
Contributor+ that reviewed offending PR: @rushatgabhane - to be paid $250 ($500-50% regression deduction)
Contributor+ that reviewed the final PR: @abdulrahuman5196 - $500

@luacmartins do you agree with that assessment?

**Comment by johncschuster** [comment] 2024-05-10 18:07
Ok, I was chatting with @luacmartins to unwind some confusion. I had misunderstood [this comment](https://github.com/Expensify/App/issues/36038#issuecomment-1932349054) and thought the regression came from there.

This was the original PR: https://github.com/Expensify/App/pull/38039
Reviewed by: abdulrahuman5196
Created regression

This is the fix PR: https://github.com/Expensify/App/pull/40912
Reviewed by: mollfpr

With that in mind, here's the updated payment summary:

Contributor: @lukemorawski - to be paid $250 ($500-50% regression deduction)
Contributor+ that reviewed offending PR: @abdulrahuman5196 - to be paid $250 ($500-50% regression deduction)
Contributor+ that reviewed the final PR: @mollfpr - $500

**Comment by johncschuster** [comment] 2024-05-13 20:07
@abdulrahuman5196 I've invited you to the job in Upwork [here](https://www.upwork.com/nx/wm/offer/102292483), can you accept that?

@lukemorawski, can you either send me your Upwork profile so I can extend the job, or can you apply to the job using [this link](https://www.upwork.com/jobs/~010a8be35fa70e77ae)? Thanks!

**Comment by johncschuster** [comment] 2024-05-14 16:12
Bumped @abdulrahuman5196 in Slack to accept the offer 👍

**Comment by johncschuster** [comment] 2024-05-14 17:10
Payment through Upwork has been issued to @abdulrahuman5196 🎉 

@mollfpr - please refer to [this comment](https://github.com/Expensify/App/issues/36038#issuecomment-2105055795) for your Manual Request.

**Closed** 2024-05-14 17:11 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-19 13:50
$500 approved for @mollfpr
