### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Android - Emoji selected from emoji picker can't be deleted from emoji picker

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27189] opened 2023-09-11 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Add :+1: reaction from anywhere
2. Press & hold the message to open context menu
3. Click on add emoji icon to open emoji picker
4. Select :+1: from the emoji picker
5. Observe emoji has not been removed.

## Expected Result:
 The emoji should be removed.

## Actual Result:
The emoji is not be removed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/74cf78ec-fba3-4c7d-8300-842e16190783

https://github.com/Expensify/App/assets/115492554/cb04a355-0f71-4e82-9db2-1f0453ef76ca

https://github.com/Expensify/App/assets/115492554/76df7852-7791-4ed0-88de-23fd28b7a366

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693333231497369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d573b7341ac1e471</li>
        <li>Upwork Job ID: 1701313561020780544</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26726638</li>
<li>krishna2323 | Reporter | 26726639</li>
</ul></li>
    </ul>
</details>

**Comment by burczu** [comment] 2023-09-14 11:27
I've just reviewed both proposals and I think we should choose [the one](https://github.com/Expensify/App/issues/27189#issuecomment-1715514653) from @dukenv0307 - their explanation why we shouldn't pass `emojiReactions` as a prop of `AddReactionBubble` sounds reasonable to me.

🎀 👀 🎀 C+ reviewed

**Comment by stitesExpensify** [comment] 2023-09-18 06:49
Not overdue 😡

**Comment by tjferriss** [comment] 2023-09-25 06:52
Payment Summary:

- Reporter: @Krishna2323 $250
- Contributor: @dukenv0307 $750 (includes 50% speed bonus)
- Contractor: @burczu NA

**Comment by burczu** [comment] 2023-09-26 07:54
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: Didn't find - it looks like it worked this way from the beginning.
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [ ]  [@burczu] Determine if we should create a regression test for this bug.
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@tjferriss / @anmurali] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by tjferriss** [comment] 2023-10-02 22:10
@dukenv0307 @Krishna2323 have been paid via Upworks.

**Closed by tjferriss** 2023-10-02 22:10 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
