### ISSUE TITLE
Web - Login - Copy pasting same incorrect magic code does not display error on login page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25400] opened 2023-08-17 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If logged in then logout
3. Enter any email and continue
4. Copy wrong code and paste, observe that it triggers error without any button or enter click
5. Copy same code, focus on first digit and again paste, observe that now app removes the error even though it is same incorrect code

## Expected Result:
App should display error everytime we paste wrong magic code

## Actual Result:
App removes the error and display no error if we again paste the same wrong magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b43ec6d3-5577-4df5-b002-d96250768947

https://github.com/Expensify/App/assets/115492554/5808e900-74c2-4623-aa51-475f304fe982

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691315996872279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-08-17 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we copy the same text after an error, the error disapears

### What is the root cause of that problem?

In BaseValidateCodeForm when the text changes in  onTextInput we clear the errors. But since the value hasn't change, the hook for validation is not triggered in MagicCodeInput

### What changes do you think we should make in order to solve the problem?

Verify that the text really has changed before clearing the errors in onTextInput 

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-08-21 00:40
@dhanashree-sawant could you please test this on the latest staging version (v1.3.55-7)? I could repro this on production but not on the latest staging version, so I want to check that we've fixed it.

**Comment by ShogunFire** [comment] 2023-08-21 01:39
I can't reproduce either

**Comment by dhanashree-sawant** [comment] 2023-08-21 06:35
Yes unable to reproduce now

**Comment by kadiealexander** [comment] 2023-08-21 06:40
Cool, thanks @dhanashree-sawant and @ShogunFire! Closing as fixed.

**Closed by kadiealexander** 2023-08-21 06:40 UTC
Labels: Daily, Needs Reproduction, Bug
