### ISSUE TITLE
[$250] Android - Attempt to edit a comment crashes the app - Reported by @adeel0202

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11301] opened 2022-09-26 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Send a message
3. Long press the message
4. Press Edit comment

## Expected Result:
Able to edit the comment

## Actual Result:
app crashes 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.7-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192384528-b33630a7-6079-41c8-9282-ee3d4b055e1b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664224827873869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adeel0202** [comment] 2022-09-27 05:30
Hi @marcaaron, I think I'm eligible for the reporting bonus here.

**Comment by adeel0202** [comment] 2022-09-28 19:06
> Hi @marcaaron, I think I'm eligible for the reporting bonus here.

bump @marcaaron

**Comment by marcaaron** [comment] 2022-09-28 21:58
I'm not entirely sure. You will have to ask in Slack about this. 

Thanks so much for reporting!

**Comment by mountiny** [comment] 2022-09-29 17:26
Sorry for the ping, @dylanexpensify Can you please pay @adeel0202 out a reporting bonus for this issue? Thank you very much!

**Comment by adeel0202** [comment] 2022-09-29 17:32
Thank you @mountiny :)

**Comment by mountiny** [comment] 2022-09-29 17:57
@dylanexpensify Can you additionally also pay out $250 to @aimane-chnaif for their help with finding the root cause for this deploy blocker and acting so fast for urgent issue? Thank you very much

Slack thread for context https://expensify.slack.com/archives/C01GTK53T8Q/p1664224827873869

**Comment by mountiny** [comment] 2022-10-03 08:44
Dylan is OOO, asking someone to handle the payments, thank you for patience

**Comment by michaelhaxhiu** [comment] 2022-10-03 12:18
Stepping in to help move this to completion.

Upwork job - https://www.upwork.com/jobs/~01dfc0368aadcc8d4f

@aimane-chnaif and @adeel0202 please accept my job invite in Upwork, you both should've received an email.

**Comment by adeel0202** [comment] 2022-10-03 12:20
Accepted, thanks.

**Comment by michaelhaxhiu** [comment] 2022-10-03 13:30
@adeel0202 is paid ✅ 

Just waiting on @aimane-chnaif next ⏳

**Comment by michaelhaxhiu** [comment] 2022-10-03 15:58
Both paid, closing.

**Closed by michaelhaxhiu** 2022-10-03 15:58 UTC
Labels: External, Engineering, Daily
