### ISSUE TITLE
[Hold #31411] [$500] Scan - None not displayed in merchant while offline & after adding amount & going online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32552] opened 2023-12-06 10:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/31897

**Version Number:** 1.4.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the app and log in
2. Disable internet connection
3. Tap FAB > Request Money > Scan
4. Select a receipt and a user
5. Complete the request
6. Navigate to the transaction chat
7. Enter the amount
8. Enable internet connection

## Expected Result:
"None" is displayed in the Merchant field while offline and after adding amount and going online, the red dot is shown

## Actual Result:
"Request" is displayed in the Merchant field offline and after adding the amount and returning online, the red dot is not shown unlike in the online flow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f3a292fc-65a0-4aab-a1f8-ffc5c587844d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c62fdfd300d1084</li>
        <li>Upwork Job ID: 1732346017160351744</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-06 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We do not set the (none) merchant value optimistically when placing the scan money request.

### What changes do you think we should make in order to solve the problem?
When creating an optimistic transaction, we should check if it's a scan transaction, and if so – set "none" instead of the default "Request" in the merchant (using constants and polishing the code a bit, but the idea is understandable):

```js
merchant: merchant || (!!receipt?.state ? '(none)' : CONST.TRANSACTION.DEFAULT_MERCHANT),
```

https://github.com/Expensify/App/blob/030cfe1da1293c388667cd6444b11e75e9a9e5a8/src/libs/TransactionUtils.ts#L69



### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2023-12-06 11:35
@mountiny given the changes you're making, is this issue going to be obsolete?

**Comment by cead22** [comment] 2023-12-06 17:37
> But I suppose it will be fixed in #31411 – asked to confirm [here](https://github.com/Expensify/App/issues/31411#issuecomment-1843243579). If it's true, we may want to hold this issue until that one is done.

I replied in the linked issue, but sharing here for visibility: we're in the process of updating the RequestMoney end point to accept and use the new parameters transactionThreadReportID and createdReportActionIDForThread. 

If this is the only cause of the issue, I suggest adding a hold until that's done

**Comment by paultsimura** [comment] 2023-12-06 17:41
> If this is the only cause of the issue

It's not the root cause, but it's causing some trouble with testing the offline-online transition. The issue will still require fixing and the proposals are relevant.

**Comment by trjExpensify** [comment] 2023-12-08 11:43
Cool, so do we want to hold and ask for proposals after that or continue with soliciting proposals in the meantime and then hold the imp on that?

**Comment by mountiny** [comment] 2023-12-08 13:23
I think we can hold for the changes linked above and then check if the issue is still the same and choose proposals.

**Comment by trjExpensify** [comment] 2023-12-11 10:36
Cool, done!

**Comment by trjExpensify** [comment] 2023-12-20 11:16
Still held.

**Comment by trjExpensify** [comment] 2024-01-03 10:46
Still held on https://github.com/Expensify/App/issues/31411

**Comment by trjExpensify** [comment] 2024-01-12 00:30
No change, Melvy boy!

**Comment by trjExpensify** [comment] 2024-01-31 01:24
Still held, PR should be [coming soon](https://github.com/Expensify/App/issues/31411#issuecomment-1917762820)!

**Comment by trjExpensify** [comment] 2024-02-09 10:20
No change!

**Comment by trjExpensify** [comment] 2024-02-19 12:01
@fedirjh I think the PR we're held on is [this](https://github.com/Expensify/App/pull/35449), right?

**Comment by trjExpensify** [comment] 2024-02-19 20:56
Sounds good!

**Comment by trjExpensify** [comment] 2024-03-01 15:14
I don't think this is a valid bug anymore. 

- The merchant is blank while receipt scanning is in progress 
- When you enter an amount the receipt scanning stops
- a merchant is a required field on a workspace, so the RBR is added and a field error shows on the merchant field
- the amount field is populated with the value you entered and no field error appears. 

Going to close it out!

**Closed by trjExpensify** 2024-03-01 15:14 UTC
Labels: External, Weekly, Help Wanted, Bug
