### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Android - if you go offline, create a manual request and upload a receipt, and go online, the receipt disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38224] opened 2024-03-13 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Upload the PDF receipt
3. Open the PDF receipt preview. It will show the local PDF file
4. Go online
5. Wait for a few seconds (~20-30 seconds) until the upload completes. It will try to show the uploaded remote PDF file
6. But fails, so you will see Failed to load PDF
## Expected Result:
When user taps receipt, the pdf file must be displayed without any error

## Actual Result:
When you come back online, the receipt disappears or generates an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a18ee4c6-f69a-42f6-963d-5e37d98e4177

![default-file-icon (12)](https://github.com/Expensify/App/assets/78819774/ed5b2458-b181-435f-b4d4-918b5cafa268)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9ecdd65c6fb75a2</li>
        <li>Upwork Job ID: 1768536207787233280</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-13 13:04
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-03-13 14:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Failed to load PDF shows while previewing a recently uploaded PDF as a receipt.

### What is the root cause of that problem?
When we first preview the PDF receipt, it's still a local file. `isAuthTokenRequired` is false in this case. When the API to add the receipt completes, the receipt source is updated to the remote file. This will update both `source` and `isAuthTokenRequired` props.
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/pages/TransactionReceiptPage.tsx#L49-L51

Then, we pass it to the attachment view.
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/components/AttachmentModal.tsx#L548-L552

The problem is, the source is coming from the source state
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/components/AttachmentModal.tsx#L416

which is updated every time the `source` props is updated.
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/components/AttachmentModal.tsx#L408-L410

So, the `isAuthTokenRequired` is already true, but the source is still local file because the state is not updated yet. That's why the error appears.

<img width="376" alt="Screenshot 2024-03-13 at 22 22 15" src="https://github.com/Expensify/App/assets/50919443/c146f865-ea8a-418d-b0c8-89ddfd60f854">

### What changes do you think we should make in order to solve the problem?

Instead of passing the `isAuthTokenRequired` props, we can pass `isAuthTokenRequiredState` which is also updated every time the props change.
https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/components/AttachmentModal.tsx#L412-L414

### What alternative solutions did you explore? (Optional)
Prioritize the source props instead of source state

https://github.com/Expensify/App/blob/fa6bcc0da0554067dc1169a802b28e796dbf1d8d/src/components/AttachmentModal.tsx#L416

```
const sourceForAttachmentView = source || sourceState;
```

**Comment by jliexpensify** [comment] 2024-03-14 10:48
PDF attachments are working perfectly for me on v1.4.51-3 (Pixel 3a)

@lanitochka17 Please re-test this

**Comment by jliexpensify** [comment] 2024-03-14 10:48
@bernhardoj also if you could retest and share a video, that would be great too!

**Comment by bernhardoj** [comment] 2024-03-14 11:06
Sure, here is the video.

https://github.com/Expensify/App/assets/50919443/0aa1c711-d20b-466e-a882-3cfc7bd7ca1a

You can use any PDF and please try to open the preview right after you upload it. This way, you will see the PDF preview of the local file. After the API completes, BE will return the remote file of the PDF and the app fails to switch to the remote file preview.

**Comment by jliexpensify** [comment] 2024-03-14 11:16
Hmm that's not what I'm seeing on a real device, on the newest version of production. Do you have a physical device for testing this one?

**Comment by bernhardoj** [comment] 2024-03-14 12:07
Same.

https://github.com/Expensify/App/assets/50919443/6203f600-4eaf-43c8-84b5-381a00fc60ed

Just to make sure, you are previewing the PDF receipt right? (not the regular chat attachment)

**Comment by jliexpensify** [comment] 2024-03-14 22:53
@lanitochka17 - you say this:

>9. Upload a pdf (below attached)

But there's no PDF in the GH?

@bernhardoj - are you using any random PDF? Because I am, so just wondering if it's a specific to a PDF?

**Comment by francoisl** [comment] 2024-03-14 23:01
I can't repro either on a Pixel 6 (app v 1.4.52-5), tested with 2 different random PDFs.

**Comment by jliexpensify** [comment] 2024-03-14 23:03
At this point, after discussing with @francoisl I am inclined to close this. @lanitochka17 please confirm if this issue is occurring with a specific PDF. @bernhardoj - same with you: if you can share your PDF, I can re-test.

**Comment by bernhardoj** [comment] 2024-03-15 03:44
I can reproduce it with any PDF. Here is one of them that I use.

[Bug6410895_1710238613342.Receipt_example.pdf](https://github.com/Expensify/App/files/14610406/Bug6410895_1710238613342.Receipt_example.pdf)

Based on my root cause, it would be great if you could try to slow down your connection so it takes longer to complete the upload or maybe you can try uploading a bigger PDF file like below.
[10840-001.pdf](https://github.com/Expensify/App/files/14610453/10840-001.pdf)

Or I think the easiest way to reproduce it is by going offline (I can reproduce it by this way too).
1. Go offline
2. Upload the PDF receipt
3. Open the PDF receipt preview. It will show the local PDF file
4. Go online
5. Wait for a few seconds until the upload completes. It will try to show the uploaded remote PDF file
6. But fails, so you will see Failed to load PDF

**Comment by jliexpensify** [comment] 2024-03-15 05:50
Hmm, I'm honestly not convinced that this is an actual issue - how likely are people going to be uploading PDF's over 10MB? Users will be uploading receipts, bills and invoices - at most, 1 or 2MB.

I also tried with a 20MB PDF btw - uploaded fine and didn't get the error.

>Or I think the easiest way to reproduce it is by going offline (I can reproduce it by this way too).

I also tested this. No issues.

What version are you on? I'm on 51-3.

**Comment by bernhardoj** [comment] 2024-03-15 06:10
> What version are you on? I'm on 51-3.

I was testing on the dev (52-0). Just re-tested it on prod app (51-3, from play store) and still able to reproduce it with 12kb PDF

https://github.com/Expensify/App/assets/50919443/ac739ff6-eed6-45b0-b2dd-39c298483f14


> how likely are people going to be uploading PDF's over 10MB?

Not sure, but that's just an example so you can reproduce it easier, but looks like you are still having trouble to reproduce it.

Would you mind sharing the recording of you performing the steps (the offline one)? Maybe I can help spot if there is a wrong step because I can easily reproduce it.

**Comment by jliexpensify** [comment] 2024-03-15 06:34
@bernhardoj I'm doing exactly what you're doing, except not waiting 15-20 seconds. I went back and reviewed @lanitochka17's original video, there's a delay of ~5 seconds.

So that's maybe why @francoisl and I can't reproduce, we're not waiting for extended periods of time.

I have another question: if you upload the PDF and go back (I guess you can wait a second or 2), then click back on the image, does the error generate? In my testing, it doesn't.

I'm not trying to be difficult here, but I honestly think this behaviour of uploading a large PDF and waiting 20 seconds isn't how the average person will use New Expensify.

**Comment by bernhardoj** [comment] 2024-03-15 06:41
> if you upload the PDF and go back (I guess you can wait a second or 2), then click back on the image, does the error generate? In my testing, it doesn't.

The number here really depends on how fast the upload completes. If you open the PDF after the upload completes, then you won't see the issue.

> uploading a large PDF

Any size is reproducible as shown in my previous video [here](https://github.com/Expensify/App/issues/38224#issuecomment-1999005329)

> waiting 20 seconds isn't how the average person will use New Expensify.

I think it would be a disruptive experience if the user is scrolling through the PDF and then Failed to load PDF suddenly pops up because the upload just completes.

**Comment by jliexpensify** [comment] 2024-03-15 07:13
>The number here really depends on how fast the upload completes. 

Sorry, I'm not an engineer so bear with me here! So you're essentially saying that in your video, the file size is so large, it is taking 20 seconds to properly upload? And then a failed error gets generated and that is the point that the upload is finished?

In my testing (and I assume Franc's as well), we are uploading and maybe waiting a couple of seconds to see the error, then going back. So that's what I would consider average user behaviour (not uploading and waiting 20 seconds).

>I think it would be a disruptive experience if the user is scrolling through the PDF and then Failed to load PDF suddenly pops up because the upload just completes.

I agree - this is definitely disruptive. 

AND GOOD NEWS. I have FINALLY managed to repro this, after spending way too much time on this issue. An more accurate set of repro steps would be to wait 5-10 seconds (and scroll down the PDF, if it's multi-page, to reach the last page).

**Comment by bernhardoj** [comment] 2024-03-15 08:59
> So you're essentially saying that in your video, the file size is so large, it is taking 20 seconds to properly upload?

I actually use a small-size PDF on the latest video, I guess it takes 20 seconds because it's trying to reconnect first after going from offline to online.

> And then a failed error gets generated and that is the point that the upload is finished?

Yes

> AND GOOD NEWS. I have FINALLY managed to repro this,

Nice 🥳.

**Comment by lanitochka17** [comment] 2024-03-15 15:18
Issue is not reproducible on the latest build 1.4.53-1


https://github.com/Expensify/App/assets/78819774/0922356d-e5ac-48be-ba2a-b8f8d6e753b9

**Comment by jliexpensify** [comment] 2024-03-16 01:31
![image](https://github.com/Expensify/App/assets/30815269/8c353884-ab7f-4c9d-a783-8212752c5149)

**Comment by jliexpensify** [comment] 2024-03-16 01:33
![image](https://github.com/Expensify/App/assets/30815269/c1fa0843-8631-4972-a927-03a326dc3d20)

**Comment by bernhardoj** [comment] 2024-03-16 03:45
@jliexpensify it's still reproducible in 1.4.53-1 😄 

https://github.com/Expensify/App/assets/50919443/24aebf77-b3e4-48e2-b33a-43bc263799e0


@lanitochka17 can you try with the offline steps [here](https://github.com/Expensify/App/issues/38224#issuecomment-1998885612)?

**Comment by jliexpensify** [comment] 2024-03-17 23:09
@bernhardoj I can repro on Android, the receipt disappears completely for me when I come back online. Feel free to adjust your proposal!

**Comment by jliexpensify** [comment] 2024-03-18 02:38
^ GH auto-assigner was broken this morning, so just testing It's fixed now!

**Comment by cubuspl42** [comment] 2024-03-18 09:31
I approve the proposal by @bernhardoj

C+ reviewed 🎀 👀 🎀

**Comment by NikkiWines** [comment] 2024-03-19 01:04
Nice, agreed! 👍

**Comment by jliexpensify** [comment] 2024-03-19 08:05
Hello @kadiealexander - headed OOO, so assigning for a buddy here.

- PR is currently being worked on by @bernhardoj 
- You may need to pay this one when I'm gone

- If no regressions:

PAYMENT SUMMARY

- C: @bernhardoj $500
- C+: @cubuspl42 $500
[Upwork job](https://www.upwork.com/jobs/~01a9ecdd65c6fb75a2)

**Comment by bernhardoj** [comment] 2024-03-19 08:06
PR is ready

cc: @cubuspl42

**Comment by jliexpensify** [comment] 2024-03-31 22:24
Back, removing Kadie!

**Comment by cubuspl42** [comment] 2024-04-05 09:14
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - Create a manual request.
  - Open the request transaction thread.
  - Switch to offline mode.
  - Add a PDF receipt.
  - Click on the receipt preview to open the attachment page.
  - Return to online mode.
  - Wait for a few seconds until the attachment reloads.
  - Ensure the PDF receipt is properly displayed, and not the "Failed to load PDF" message.

**Comment by jliexpensify** [comment] 2024-04-05 09:39
Dammit Upworks closed the job. 

PAYMENT SUMMARY

- C: @bernhardoj $500
- C+: @cubuspl42 $500

[NEW Upwork job](https://www.upwork.com/jobs/~011da78601ce5a78df) - please accept!

**Comment by jliexpensify** [comment] 2024-04-08 00:09
Bump @cubuspl42 to accept so I can pay everyone please.

**Comment by cubuspl42** [comment] 2024-04-08 08:55
@jliexpensify Accepted 👍

**Comment by jliexpensify** [comment] 2024-04-08 09:19
Paid and job closed!

**Closed by jliexpensify** 2024-04-08 09:19 UTC
Labels: External, Weekly, Awaiting Payment, Bug
