### ISSUE TITLE
IOU - Settled payments are showing with infinite loading, looks normal after opened.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12999] opened 2022-11-24 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to any chat where you have settled payments
4. Scroll your conversation and check your settled payment

## Expected Result:
Settled payments are not showing with infinite loading.

## Actual Result:
Settled payments are showing with infinite loading, looks normal after opened.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Web
- mWeb

**Version Number:** 1.2.31.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203818032-914b7402-8771-45c9-b1f3-4bd9c1ca798e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-24 17:10
The loading spinner eventually goes away for me. That being said, I noticed that the `reportIOUs_` value returned in the OpenApp command is empty and we have several calls to `Get$rvl= reportStuff` being triggered. Perhaps this has to do with the IOUReport key refactors @Gonals?

![Screenshot 2022-11-24 at 9 50 42 AM](https://user-images.githubusercontent.com/22219519/203837574-b51a4ee8-6478-4112-8e93-7d83ee772145.png)

**Comment by luacmartins** [comment] 2022-11-24 22:56
I was able to reproduce this. Looking into a fix

**Comment by luacmartins** [comment] 2022-11-25 00:08
I'm looking into this but haven't figured out the cause yet.

**Comment by luacmartins** [comment] 2022-11-25 00:27
I can't reproduce anymore 😕  Asked for more eyes [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669335345066749)

**Comment by Gonals** [comment] 2022-11-25 11:57
Hmmm. Maybe some old stuff that needed to refresh? I can't seem to reproduce it

**Comment by Julesssss** [comment] 2022-11-25 12:05
Unable to reproduce, I'm going to close this until we have reproducible steps

![Screenshot_20221125-120207](https://user-images.githubusercontent.com/10736861/203982435-06256e84-d5b9-474c-b320-ade69d22f8ec.png)

**Closed by Julesssss** 2022-11-25 12:05 UTC
Labels: DeployBlockerCash, Engineering, Hourly
