### ISSUE TITLE
 iOS/Android - "Workspace" displayed in Send from field when sending invoice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47572] opened 2024-08-16 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/47288
## Action Performed:
precondition: user has created at least one collect policy, and set the individual workspace as a default policy in OD
1. Open the app and log in
2. Tap FAB > Send invoice
3. Enter amount and select a user
4. Proceed to the confirmation screen

## Expected Result:
The collect workspace is displayed in the Send from field

## Actual Result:
The "Workspace" and workspace placeholder avatar is displayed in the Send from field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0153a789-024f-41ca-819e-d0927c3f9633

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-16 15:54
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rojiphil** [comment] 2024-08-19 07:18
@lanitochka17 I cannot reproduce this on Android and iOS native as demonstrated in the videos below. Can you please check what I am missing here?

https://github.com/user-attachments/assets/c8040a31-adca-42a4-922e-91da695ce877


https://github.com/user-attachments/assets/d70342dc-65a9-405f-b3b6-9fb0432b4694

**Comment by joekaufmanexpensify** [comment] 2024-08-19 14:09
Not overdue, will review today

**Comment by joekaufmanexpensify** [comment] 2024-08-19 15:13
Not reproducible for me either. 

https://github.com/user-attachments/assets/cb9d2d4c-6e65-4089-a901-134538379ce3

**Comment by joekaufmanexpensify** [comment] 2024-08-19 15:13
Closing as this doesn't appear to be consistently reproducible.

**Closed by joekaufmanexpensify** 2024-08-19 15:13 UTC
Labels: Daily, Bug
