### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250]  Group details – Avatar is not grayed out in a group chat when change it Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41770] opened 2024-05-07 14:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40884
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any group chat.
4. Click on the header > Members.
5. Go offline.
6. Click on the avatar
7. Change the avatar.
8. Go back to group chat

## Expected Result:
The avatar is grayed out

## Actual Result:
Avatar is not grayed out in a group chat, it’s grayed out only in group details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/10514f4d-296e-40cd-a327-6449801f724e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e747d57e97f1ec95</li>
        <li>Upwork Job ID: 1788797815120121856</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-05-07 14:54
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-05-08 06:17
I think this is pretty minor so I think we can probably close without action. 

@s77rt can you take a peek at this since you worked on the PR https://github.com/Expensify/App/pull/40884 and let us know if this is important to fix?

**Comment by s77rt** [comment] 2024-05-08 06:28
I agree this is minor. Fixing this should be straightforward but I'm not sure if it's something we want. cc @shawnborton do you have a preference here?

**Comment by shawnborton** [comment] 2024-05-08 12:27
But cc @marcaaron - don't we already have an issue open to address this one?

**Comment by s77rt** [comment] 2024-05-08 19:01
@nexarvo Can you please comment here so you can be assigned to complete the 2 tasks:
1. Make avatar grayed out on reports
2. Exclude the change avatar button from being grayed out

**Comment by Christinadobrzyn** [comment] 2024-05-10 05:11
I added the external label, so the assignment is fair, but @eh2077 - @s77rt has been working on this so far. Would you be okay with @s77rt taking this? OR @s77rt, let us know the next steps for @eh2077. TY!

**Comment by s77rt** [comment] 2024-05-10 20:04
Since this is a regression or more like unfinished work, @nexarvo and I should handle this. This does not require payment since it's a part of https://github.com/Expensify/App/issues/39983

**Comment by Christinadobrzyn** [comment] 2024-05-13 01:49
okay, I added @s77rt and @nexarvo to this - thank you!

**Comment by Christinadobrzyn** [comment] 2024-05-21 07:34
working on PR - https://github.com/Expensify/App/pull/42088

**Comment by Christinadobrzyn** [comment] 2024-05-28 06:13
monitoring PR https://github.com/Expensify/App/pull/42088

**Comment by s77rt** [comment] 2024-06-03 18:37
- The PR that introduced the bug has been identified: Not a regression, more like a feature request
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: No

**Comment by Christinadobrzyn** [comment] 2024-06-05 08:00
Payouts due:

- [ ] Contributor: $250 @nexarvo (Upwork offer - https://www.upwork.com/nx/wm/offer/102603093)
- [ ] Contributor+: $250 @s77rt (upwork offer - https://www.upwork.com/nx/wm/offer/102603103)

Upwork job is [here](https://www.upwork.com/jobs/~01e747d57e97f1ec95).

@s77rt @nexarvo let me know if either of you are paid through NewDot. Thanks!

**Comment by s77rt** [comment] 2024-06-05 10:53
@Christinadobrzyn No payment is due here. This is handled in https://github.com/Expensify/App/issues/39983. We can close this issue

**Comment by Christinadobrzyn** [comment] 2024-06-06 06:50
Ah thank you for the heads up @s77rt - Closing.

**Closed by Christinadobrzyn** 2024-06-06 06:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
