### ISSUE TITLE
[Hold for Payment: 2022-12-09] [$250] LHN - Opening <EXPENSIFY_URL>/concierge, system redirected to LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12776] opened 2022-11-16 15:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR** https://github.com/Expensify/App/pull/12588

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Minimize the window
3. Open <EXPENSIFY_URL>/concierge

## Expected Result:
The concierge chat should be displayed 

## Actual Result:
The system redirected to LNH when opening <EXPENSIFY_URL>/concierge

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.28.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202226529-253f3232-bcec-4073-a876-e0981ba4084e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2022-11-17 09:46
Upwork: https://www.upwork.com/jobs/~013d413cd690798c5c

**Comment by flodnv** [comment] 2022-11-17 13:55
This is very strange, as it worked in https://github.com/Expensify/App/pull/12588 (which was fixing https://github.com/Expensify/App/issues/11892). To me, this isn't as much a regression as it should've been a deploy blocker -- that PR should not have been marked as passing tests, as tests were not passing. Why was this not a deploy blocker @kbecciv ?

**Comment by flodnv** [comment] 2022-11-17 13:56
Oh I see: https://github.com/Expensify/App/issues/12753#issuecomment-1318185342
As per my above message, I disagree with what you said there @roryabraham

**Comment by flodnv** [comment] 2022-11-17 13:56
cc @Ollyws maybe you can take a look^ ?

**Comment by tlerias** [comment] 2022-11-18 19:38
## The Problem
This is happening because `/concierge` redirects to the concierge route with the report ID. When the redirect happens, by default the drawer is open on small screens. [You can see the code that does this here.](https://github.com/Expensify/App/blob/main/src/libs/Navigation/Navigation.js#L88-L92)
This shows the redirect in the URL:
[!](http://g.recordit.co/0zuYFzKvRO.gif)

# The Proposed Solution
I propose fixing this by adding this code to the [ReportScreen Page](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js#L128-L135) `componentDidMount`
```
if (ReportUtils.isConciergeChatReport(this.props.report) && this.props.isSmallScreenWidth) {
            Navigation.closeDrawer();
        }
```

By putting it in the `componentDidMount` it will not do this check on every rerender, forcing the LHN Drawer to be closed all the time. It will only run this code when the page has been mounted.

Looking forward to your thoughts on this solution.

**Comment by bernhardoj** [comment] 2022-11-19 10:47
### **Proposal**

**Problem**
Actually, this issue also happens on native when we open the deep link (<EXPENSIFY_URL>/concierge) from another app while the Expensify app is closed. It will throw a development-only error below.
![327797](https://user-images.githubusercontent.com/50919443/202845358-71d37977-8c22-469c-844d-b0fd3395dc6f.jpg)
ReportScreen should be the one that handles the routes, but the navigator could not find it as it is not available. After doing some investigation, it turns out that when we are trying to navigate to concierge chat on launch, `MainDrawerNavigator` (which contains ReportScreen) is not ready/mounted yet. Then why the old code can handle it?

It is already mentioned the PR that caused the issue [here](https://github.com/Expensify/App/issues/12776#issuecomment-1318693079) specifically at this [line](https://github.com/Expensify/App/pull/12157/files#diff-dee473482f17c430c462f98d9335ed3f4eea15f0e9ff8117a183f49117edebeaL29-R28). The new code changes call `Report.navigateToConciergeChat()` which will open concierge chat immediately, compared to the old code that calls `Report.fetchOrCreateChatReport()` which will do an api request before doing the navigation, so there is some delay for the drawer navigator to be ready.

**Solution**
We can wait for the drawer navigator to be ready first, then do the navigation action.
```diff
const ConciergePage = (props) => {
    if (_.has(props.session, 'authToken')) {
-       Report.navigateToConciergeChat();
+       Navigation.isDrawerReady().then(() => {
+           Report.navigateToConciergeChat();
+       });
    } else {
        Navigation.navigate();
    }

    return <FullScreenLoadingIndicator />;
};
```

**Result**

https://user-images.githubusercontent.com/50919443/202846777-1b215b3b-80b6-47be-b485-e7a5c24662af.mp4


https://user-images.githubusercontent.com/50919443/202846873-344d88c9-1430-4dd8-bfb4-0fc805837fa6.mov

**Comment by tlerias** [comment] 2022-11-19 13:59
@bernhardoj this feels like a different bug to me. You should report it so you get bug reporting $$ too 😉you may have to wrap your solution in an ‘useEffect’ but I didn’t try investigating your code so I could be wrong.

**Comment by tlerias** [comment] 2022-11-19 14:13
@bernhardoj (i deleted my last comment because I meant to take back the second part of my comment that mentioned something about a useEffect but that was wrong).

This feels like a different bug to me. You should report it so you get reporting $ too 😉.

**Comment by s77rt** [comment] 2022-11-22 09:09
### Proposal
```diff
diff --git a/src/libs/actions/App.js b/src/libs/actions/App.js
index 1faeae4bb..97cc46f16 100644
--- a/src/libs/actions/App.js
+++ b/src/libs/actions/App.js
@@ -115,6 +115,7 @@ function openApp() {
     const connectionID = Onyx.connect({
         key: ONYXKEYS.COLLECTION.POLICY,
         waitForCollectionCallback: true,
+        initWithStoredValues: false,
         callback: (policies) => {
             Onyx.disconnect(connectionID);
             API.read('OpenApp', {policyIDList: getNonOptimisticPolicyIDs(policies)}, {
diff --git a/src/pages/ConciergePage.js b/src/pages/ConciergePage.js
index 1793f651d..fc8fc8712 100644
--- a/src/pages/ConciergePage.js
+++ b/src/pages/ConciergePage.js
@@ -24,10 +24,12 @@ const propTypes = {
  *     - Else re-route to the login page
  */
 const ConciergePage = (props) => {
-    if (_.has(props.session, 'authToken')) {
-        Report.navigateToConciergeChat();
-    } else {
-        Navigation.navigate();
+    if (props.isLoadingReportData === false) {
+        if (_.has(props.session, 'authToken')) {
+            Report.navigateToConciergeChat();
+        } else {
+            Navigation.navigate();
+        }
     }
 
     return <FullScreenLoadingIndicator />;
@@ -40,4 +42,7 @@ export default withOnyx({
     session: {
         key: ONYXKEYS.SESSION,
     },
+    isLoadingReportData: {
+        key: ONYXKEYS.IS_LOADING_REPORT_DATA,
+    },
 })(ConciergePage);
```

### Details
Before explaining my proposal, I will explain why it was working. It was working because we were always making a call to the API `CreateChatReport` and before that we call `OpenApp`. The navigation to the concierge chat was done in the callback of `CreateChatReport` and since API calls are sequential we were always navigation to the concierge chat after `OpenApp` is done. Now with the recent changes we are no longer calling `CreateChatReport` and we navigate immediately even before the `OpenApp` call is done.

With that being said, the fix is rather simple and by just checking the value of `isLoadingReportData` if it's `false` (`OpenApp` is done with success) then we can proceed with the navigation.

I have also set `initWithStoredValues` to `false` so we don't get the value initially set to `false` (the result from the last session).

**Comment by s77rt** [comment] 2022-11-22 21:31
### Proposal (Updated)
```diff
diff --git a/src/libs/actions/App.js b/src/libs/actions/App.js
index 1faeae4bb..db1a8c711 100644
--- a/src/libs/actions/App.js
+++ b/src/libs/actions/App.js
@@ -111,6 +111,8 @@ AppState.addEventListener('change', (nextAppState) => {
  * Fetches data needed for app initialization
  */
 function openApp() {
+    // Discard locally stored IS_LOADING_REPORT_DATA value
+    Onyx.set(ONYXKEYS.IS_LOADING_REPORT_DATA, null);
     // We need a fresh connection/callback here to make sure that the list of policyIDs that is sent to OpenApp is the most updated list from Onyx
     const connectionID = Onyx.connect({
         key: ONYXKEYS.COLLECTION.POLICY,
diff --git a/src/pages/ConciergePage.js b/src/pages/ConciergePage.js
index 1793f651d..fc8fc8712 100644
--- a/src/pages/ConciergePage.js
+++ b/src/pages/ConciergePage.js
@@ -24,10 +24,12 @@ const propTypes = {
  *     - Else re-route to the login page
  */
 const ConciergePage = (props) => {
-    if (_.has(props.session, 'authToken')) {
-        Report.navigateToConciergeChat();
-    } else {
-        Navigation.navigate();
+    if (props.isLoadingReportData === false) {
+        if (_.has(props.session, 'authToken')) {
+            Report.navigateToConciergeChat();
+        } else {
+            Navigation.navigate();
+        }
     }
 
     return <FullScreenLoadingIndicator />;
@@ -40,4 +42,7 @@ export default withOnyx({
     session: {
         key: ONYXKEYS.SESSION,
     },
+    isLoadingReportData: {
+        key: ONYXKEYS.IS_LOADING_REPORT_DATA,
+    },
 })(ConciergePage);
```

### Details
Discard locally stored `IS_LOADING_REPORT_DATA` value just before opening the app instead of setting `initWithStoredValues` to `false`

___

@rushatgabhane I have based my research on a random old version I guess it was 1.2.25-0
https://github.com/Expensify/App/blob/f6c5d0b44801ecbc766e7f7d98418a3df8b55e1d/src/pages/ConciergePage.js#L27-L35
calls `fetchOrCreateChatReport` which calls `CreateChatReport`

https://github.com/Expensify/App/blob/f6c5d0b44801ecbc766e7f7d98418a3df8b55e1d/src/libs/actions/Report.js#L492-L523

where in it's call back we finally navigate
https://github.com/Expensify/App/blob/f6c5d0b44801ecbc766e7f7d98418a3df8b55e1d/src/libs/actions/Report.js#L516

With the current code we directly navigate to the page:
https://github.com/Expensify/App/blob/0efa4206d8000e6a94423cf10ac4bcf2c44c034b/src/pages/ConciergePage.js#L26-L34

The PR that caused the issue is as stated by @Ollyws https://github.com/Expensify/App/pull/12157
But as I said this is more like a hidden bug than a regression,

**Comment by bernhardoj** [comment] 2022-11-23 04:24
@rushatgabhane may I know why my proposal is hacky? I would assume it is hacky if I use something like `setTimeout` which is not reliable.

**Comment by tlerias** [comment] 2022-11-23 17:04
@bernhardoj @rushatgabhane will your proposal fix this on web/mobile web small screens? Where this issue was originally reported?

**Comment by bernhardoj** [comment] 2022-11-24 02:17
> Sorry @bernhardoj, i got wrapped up in other proposals.
> 
> Your proposal isn't a hack.

No worries. Thanks for the clarification.



> @bernhardoj @rushatgabhane will your proposal fix this on web/mobile web small screens? This is where this issue was originally reported, not native.

Yes, it will fix on all platforms.

**Comment by dylanexpensify** [comment] 2022-11-28 09:58
Back from Thanksgiving break, reviewing today!

**Comment by dylanexpensify** [comment] 2022-11-28 10:09
@rushatgabhane can we get a 👍 or 👎 on the proposal today?

**Comment by stitesExpensify** [comment] 2022-11-28 20:58
I like @bernhardoj proposal! Let's go ahead and get him hired!

**Comment by bernhardoj** [comment] 2022-11-29 01:08
Applied. I will open the PR today or tomorrow.

**Comment by bernhardoj** [comment] 2022-11-29 10:31
I have opened the PR.

There is 1 checklist left, which is to test on Desktop. Do we have any way to open a deep link on desktop?

@rushatgabhane @stitesExpensify

**Comment by bernhardoj** [comment] 2022-11-29 11:20
It works. Thanks a lot! @Ollyws

Updated my PR.

**Comment by dylanexpensify** [comment] 2022-12-01 16:02
@rushatgabhane where are we with reviewing the PR? Remember, within 3 days = 50% bonus!

**Comment by stitesExpensify** [comment] 2022-12-01 16:22
The PR is already merged 😄 We're just waiting for the deploy now

**Comment by dylanexpensify** [comment] 2022-12-01 16:23
ah hahah nice! Best answer

**Comment by dylanexpensify** [comment] 2022-12-05 09:50
Not overdue - should this have populated the payment date header @stitesExpensify?

**Comment by dylanexpensify** [comment] 2022-12-08 14:04
payment tomorrow!

**Comment by dylanexpensify** [comment] 2022-12-09 16:54
@bernhardoj offer sent!

**Comment by bernhardoj** [comment] 2022-12-09 17:05
@dylanexpensify I see the offer amount hasn't include the bonus. Should I accept the offer first? Sorry, this is my first time receiving an offer with bonus 😅

**Comment by dylanexpensify** [comment] 2022-12-12 11:12
no worries @bernhardoj! accept the offer and I'll include the bonus when paying out! 😄

**Comment by bernhardoj** [comment] 2022-12-12 14:25
Accepted. Thanks for the answer!

**Comment by dylanexpensify** [comment] 2022-12-13 08:47
@bernhardoj payment (w/bonus) sent!
@rushatgabhane sent offer!

**Comment by dylanexpensify** [comment] 2022-12-14 15:41
paid out

**Closed by dylanexpensify** 2022-12-14 15:41 UTC
Labels: External, Daily, Bug
