### ISSUE TITLE
[$250] Expense report-Submit & approve button not disappear until page refreshed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48463] opened 2024-09-03 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validation PR:** https://github.com/Expensify/App/pull/48362
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: log into OD as an admin, create a control policy, enable workspace chats, select "Advanced Approvals", invite 3 members (non-admin): 2 approvers and 1 submitter, set the approval flow as submitter submits to approver 1
1. Log into ND as submitter
2. Navigate to the workspace chat
3. Submit one manual expense
4. Open the report and click on the "Submit" button
5. As admin, change the the submitter's submitsTo to approver 2 in OD
6. Log into ND as approver 1
7. Opened the submitted report
8. Click on the "Approve" button

## Expected Result:
The 'Submit" button disappears immediately for the submitter (step 4) and the "Approve" button disappears for the approver (step 8)

## Actual Result:
The "Submit" and "Approve" button do not disappear until the page is refreshed or it is clicked on the second time (the "Approve" button)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fbe312ce-13f0-4ca2-b847-90377f45606f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efec68070b933fc3</li>
        <li>Upwork Job ID: 1831071506567798044</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104649054</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: </details>

**Comment by izarutskaya** [comment] 2024-09-03 12:12
We think this issue might be related to the #wave-control

**Comment by izarutskaya** [comment] 2024-09-03 12:14
Production 

https://github.com/user-attachments/assets/22cd9b0c-8fcf-4a91-a157-6a32110a047f


https://github.com/user-attachments/assets/226b3376-227d-489b-b719-69b05e0ddb4e

**Comment by srikarparsi** [comment] 2024-09-03 18:57
Looked into this and I think this might be a problem with manually submitting reports. I verified this by:

1. Creating a workspace
2. Setting the submit frequency to manual
3. Creating an expense
4. Submitting the expense
5. Seeing the submit button re-appear

https://github.com/user-attachments/assets/5f94e465-37f8-4c63-8a2c-e0edc2ef4563

**Comment by srikarparsi** [comment] 2024-09-03 18:58
I don't think this is a backend bug because the SubmitReport response is the same on staging and production.

**Comment by srikarparsi** [comment] 2024-09-03 20:03
I think [this](https://github.com/Expensify/App/pull/48421) could be a possible culprit

**Comment by situchan** [comment] 2024-09-03 20:05
> I think [this](https://github.com/Expensify/App/pull/48421) could be a possible culprit

No, that PR didn't hit staging yet

**Comment by srikarparsi** [comment] 2024-09-03 20:07
Ah you're right thanks

**Comment by srikarparsi** [comment] 2024-09-03 20:34
Hm, I'm not able to reproduce [this](https://github.com/Expensify/App/issues/48463#issuecomment-2327209548) in the latest dev.

https://github.com/user-attachments/assets/0396d84c-ea8b-419d-ada7-756d4b8aba57

**Comment by srikarparsi** [comment] 2024-09-03 20:47
Still debugging on dev but going to add the external label to see if we can speed things up

**Comment by srikarparsi** [comment] 2024-09-03 20:54
Hmm, actually this might be backend. After the SubmitReport call, we do a GetMissingOnyxUpdates which is setting the status of the report back to 0 which is re-rendering the submit button. For some reason, this only happens in staging and not production:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/75e7948d-eaed-44b2-9163-840689b28d75">

**Comment by srikarparsi** [comment] 2024-09-03 21:01
Seeing some flickering behavior on production as well occasionally:

https://github.com/user-attachments/assets/be7404be-37e0-494e-b88a-6a703d57338a

**Comment by srikarparsi** [comment] 2024-09-03 21:06
Yeah actually I'm able to reproduce this on production pretty reliably:

https://github.com/user-attachments/assets/46ba12dd-5a7f-4599-8611-c33c5b216457

I think this is a larger problem with the SettlementButton. Since this is occurring on production as well, I think we can demote this from a DeployBlocker, what do you think @roryabraham?

**Comment by roryabraham** [comment] 2024-09-03 21:26
Yep, agreed that since it's reproducible on prod we can demote this

**Comment by nkdengineer** [comment] 2024-09-04 04:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Submit" and "Approve" button do not disappear until the page is refreshed or it is clicked on the second time (the "Approve" button)

### What is the root cause of that problem?
> The "Submit" and "Approve" button do not disappear until the page is refreshed or it is clicked on the second time (the "Approve" button)

- The submit button still appears because after `SubmitReport` API is complete the `GetMissingOnyxMessage` API is called that returns the data of the expense report with `stateNum` and `statusNum` as `0`.


- When we submit an expense report, the manager of the expense report is the approver 1 then when we change the approver the manager is still approver 1 then the `canApproveIOU` function returns `true` because it only covers the case submit and approve mode, it doesn't cover the case advance approve.


https://github.com/Expensify/App/blob/3e5da7810fdc48ce391db3ed3aa7dab86a59c490/src/libs/actions/IOU.ts#L6815-L6823
### What changes do you think we should make in order to solve the problem?
- For the submit button, we should fix it from BE side

- For the approve button, we should update `canApproveIOU` to cover the case advance approve mode then for this case the `submitTo` of the `ownerAccountID` of expense report can approve the report

```
const isControlOnAdvancedApprovalMode = PolicyUtils.isControlOnAdvancedApprovalMode(policy);
if (isControlOnAdvancedApprovalMode) {
    const ownerAccountID = iouReport?.ownerAccountID ?? '-1';
    const employee = policy?.employeeList?.[ownerAccountID];
    return employee?.submitsTo === currentUserEmail;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment] 2024-09-09 12:42
@nkdengineer Thanks for your proposal.

> The submit button still appears because after SubmitReport API is complete the GetMissingOnyxMessage API is called that returns the data of the expense report with stateNum and statusNum as 0.

Can you elaborate on this part? What's the current behaviour of the API that causes the bug? And what the expected behaviour should be for the API? So, it'll be easier for the internal engineering team to look into the issue.

**Comment by nkdengineer** [comment] 2024-09-09 14:53
> Can you elaborate on this part? What's the current behaviour of the API that causes the bug? And what the expected behaviour should be for the API?

The `SubmitReport` API returns the correct data  with `stateNum` and `statusNum` as `1`. After that `GetMissingOnyxMessage ` API is called that returns `stateNum` and `statusNum` as `0` which causing the first bug.

**Comment by eh2077** [comment] 2024-09-10 16:08
I agreed with @nkdengineer 's investigation. Let's go with their [proposal](https://github.com/Expensify/App/issues/48463#issuecomment-2327866925).

@srikarparsi Please help with the backend part and all yours!

🎀👀🎀 C+ reviewed

**Comment by srikarparsi** [comment] 2024-09-10 19:55
Hey @slafortune! My K2 is pretty full right now and since this is a backend issue I don't think I'll have time for it this week or next week. Do you think you could check if this fits into a wave/vip so that someone with bandwidth can maybe work on it? This is the [SO](https://stackoverflowteams.com/c/expensify/questions/18578) for that I believe.

**Comment by nkdengineer** [comment] 2024-09-13 04:04
@slafortune We also need the front-end change in this issue as I mentioned in my [proposal](https://github.com/Expensify/App/issues/48463#issuecomment-2327866925). We can do it separately since the front-end bug doesn't require the BE change.

**Comment by trjExpensify** [comment] 2024-09-13 17:06
>Precondition: log into OD as an admin, create a control policy,

Moving to the #wave-control project.

**Comment by eh2077** [comment] 2024-09-15 15:42
Not overdue, we're waiting for the backend fix

**Comment by eh2077** [comment] 2024-09-18 11:33
> Not overdue, we're waiting for the backend fix

Not overdue. Same^

**Comment by eh2077** [comment] 2024-09-24 12:25
> > Not overdue, we're waiting for the backend fix
> 
> Not overdue. Same^

Same^

**Comment by eh2077** [comment] 2024-10-01 14:44
> > > Not overdue, we're waiting for the backend fix
> > 
> > 
> > Not overdue. Same^
> 
> Same^

Same^

@slafortune Can you help to ask an internal engineer to pick up this? Or maybe we can demote it to weekly

**Comment by eh2077** [comment] 2024-10-07 13:08
@slafortune Can you ask an internal engineer to hot pick this one for the backend fix?

**Comment by eh2077** [comment] 2024-10-11 15:21
Not overdue, we're still waiting for hot pick

**Comment by eh2077** [comment] 2024-10-15 15:32
Bumped in slack https://expensify.slack.com/archives/C01GTK53T8Q/p1728660271578649

**Comment by nkdengineer** [comment] 2024-10-15 15:34
@eh2077 Another thing, we have two problems in this issue and the frontend bug doesn't depend on the BE change then can you add a C+ review comment here again then we can move forward with the frontend bug.

**Comment by eh2077** [comment] 2024-10-16 14:24
> @eh2077 Another thing, we have two problems in this issue and the frontend bug doesn't depend on the BE change then can you add a C+ review comment here again then we can move forward with the frontend bug.

@nkdengineer Thanks for your comment. Can you check if the frontend bug is still reproducible? If so, then I think we can move forward with the frontend bug and handle the backend issue separately

**Comment by slafortune** [comment] 2024-10-16 22:35
Since the GH does have the Hotpick tag, it is seen for an engineer to pick up.  Once you've tested if this is reproducible, I can post it to a room to have the status updated to something appropriate 👍

**Comment by mvtglobally** [comment] 2024-10-19 03:48
Issue not reproducible during KI retests. (First week)

**Comment by eh2077** [comment] 2024-10-20 16:00
> Issue not reproducible during KI retests. (First week)

Not overdue

**Comment by nkdengineer** [comment] 2024-10-21 09:27
@eh2077 The BE bug is no longer reproducible. I can still reproduce the FE bug.

**Comment by slafortune** [comment] 2024-10-22 20:32
Sounds like I can remove the hotpick and internal tags - is there a FE fix in the works?

**Comment by slafortune** [comment] 2024-10-23 18:04
@eh2077 is there a fix here that can be assigned?

**Comment by eh2077** [comment] 2024-10-24 15:39
@nkdengineer Thanks for your proposal!

I also managed to reproduce the frontend bug. I think we can go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/48463#issuecomment-2327866925) to fix it.

🎀👀🎀 C+ reviewed

**Comment by slafortune** [comment] 2024-10-29 16:20
Hey @NikkiWines - does the recommended proposal look like a go?

**Comment by NikkiWines** [comment] 2024-10-29 17:51
Oops, sorry - missed this one somehow. Agreed that @nkdengineer's proposal to fix the FE bug is good 👍

**Comment by nkdengineer** [comment] 2024-10-31 16:02
@eh2077 We have a problem after we submit the report to approver 1 and change the `submitsTo` to approver 2. If approver 2 clicks on the approver button, BE returns the error.

**Comment by NikkiWines** [comment] 2024-11-01 20:04
PR is in the works, @nkdengineer do you need further clarification on [this comment](https://github.com/Expensify/App/issues/48463#issuecomment-2450251794)?

**Comment by eh2077** [comment] 2024-11-04 15:26
> @eh2077 We have a problem after we submit the report to approver 1 and change the `submitsTo` to approver 2. If approver 2 clicks on the approver button, BE returns the error.

@nkdengineer Does the backend error block testing your PR? If so, can you share the detail reproduction steps? Then we can we ask help from @NikkiWines

**Comment by NikkiWines** [comment] 2024-11-05 00:42
^^ in the works

**Comment by nkdengineer** [comment] 2024-11-11 10:43
> @nkdengineer Does the backend error block testing your PR? If so, can you share the detail reproduction steps? Then we can we ask help from @NikkiWines

The problem is when I display the approve button for the approver 2 with the original step of the bug, the approver 2 cannot approve the expense report.

**Comment by eh2077** [comment] 2024-11-11 16:50
@nkdengineer Do you mean after step 5, `As admin, change the the submitter's submitsTo to approver 2 in OD`, you can't approve the expense if login as approver 2?

**Comment by NikkiWines** [comment] 2024-11-15 16:47
@nkdengineer can you respond to @eh2077 [here](https://github.com/Expensify/App/issues/48463#issuecomment-2468621688) please 🙇

**Comment by nkdengineer** [comment] 2024-11-15 17:23
> Do you mean after step 5, As admin, change the the submitter's submitsTo to approver 2 in OD, you can't approve the expense if login as approver 2?

@eh2077 Yes, that's correct.

**Comment by eh2077** [comment] 2024-11-19 13:57
> Do you mean the report when approver1 clicks Approve is then sent to the "new" approver to approve as well? If so, I'm not aware of that historical logic. 

@trjExpensify Yes, you can check the above video from 0:50 to 1:05

**Comment by trjExpensify** [comment] 2024-11-19 22:41
Nice, thanks! I'm confused what we're doing with this issue then? The OP is pretty unclear really. It sounds like it was created from this PR, but the expected results still confuse me when looking at [that PRs test steps](https://github.com/Expensify/App/pull/48362). 

It sounds like we expect this: 

1. After someone manually submits a report, the submit button should disappear for them right away. It's submitted. 
2. If the report is submitted AND THEN the approver is changed.
   a. Approver1 should still see the GBR on the expense report and the approve button
   b. Approver 1 should be able to click that button to approve the report
   c. Approver2 does not see the GBR nor the approve button. 

Does that sound right to you? CC: @Beamanator @marcochavezf from the linked PR as well.

**Comment by trjExpensify** [comment] 2024-11-20 14:20
>I could be wrong, but I think Approver 1 doesn't see GBR on the expense report at first (when they're in the submitter's approval chain) b/c they should see GBR on the policy chat report instead.
>
>Once Approver 1 is swapped with Approver 2, Approver 1 should see the GBR on the expense report b/c they no longer have access to the policy chat & shouldn't see the policy chat in the LHN

Ah yes, great clarification. 👍

**Comment by Beamanator** [comment] 2024-11-20 14:34
Thanks! 🙏  Curious if there's anything else I'm needed for here? Happy to help, don't want y'all to be waiting on me

**Comment by eh2077** [comment] 2024-11-24 15:13
> Nice, thanks! I'm confused what we're doing with this issue then? The OP is pretty unclear really. It sounds like it was created from this PR, but the expected results still confuse me when looking at [that PRs test steps](https://github.com/Expensify/App/pull/48362).
> 
> It sounds like we expect this:
> 
> 1. After someone manually submits a report, the submit button should disappear for them right away. It's submitted.
> 2. If the report is submitted AND THEN the approver is changed.
>    a. Approver1 should not see the GBR on the workspace chat (they've been removed), they should instead see the GBR on the expense report and the approve button
>    b. Approver 1 should be able to click that button to approve the report
>    c. Approver2 does not see the GBR nor the approve button.
> 


@trjExpensify Thanks for driving clarity! 

@Beamanator @NikkiWines I think we'll have to fix 2c from backend because, after performing 2b, the approver2 is able to see the approve button. See the video from 0:50 to 1:05 of this https://github.com/Expensify/App/issues/48463#issuecomment-2483687769

**Comment by Beamanator** [comment] 2024-11-25 20:44
I'm pretty sure what @trjExpensify was saying was that, after step 2, all of a, b, and c should be true. But after 2.b happens, it sounds likely that 2.c should be true, right?

**Comment by trjExpensify** [comment] 2024-11-25 23:46
Perhaps you could write out numbered steps on this particular concern with where it might not be working as expected, @eh2077?

**Comment by eh2077** [comment] 2024-11-26 14:07
Precondition: log into OD as an admin, create a control policy, enable workspace chats, select "Advanced Approvals", invite 3 members (non-admin): 2 approvers and 1 submitter, set the approval flow as submitter submits to approver 1

1. Log into ND as submitter
2. Navigate to the workspace chat
3. Submit one manual expense
4. Open the report and click on the "Submit" button
5. As admin, change the the submitter's submitsTo to approver 2 in OD

========== Check `Approve` button existence of expenses from two approvers ==========

6. Log into ND as approver 1 and open the submitted report
7. The `Approve` button is still available for approver 1, which is expected according to [2.a](https://github.com/Expensify/App/issues/48463#issuecomment-2486899153)
8. Log into ND as approver 2 and open the expense report
9. There's no `Approve` button to approve the expense, which is expected according to [2.c](https://github.com/Expensify/App/issues/48463#issuecomment-2486899153)

========== Check the workflow of approving ==========

10. Log into ND as approver 1 and open the expense report
11. The approver 1 clicks the `Approve` button and is able to approve the expense, which is expected according to [2.b](https://github.com/Expensify/App/issues/48463#issuecomment-2486899153)
12. The expense is submitted to approver 2. **_Is this expected?_**
13. Log into ND as approver 2 and open the expense report
14. The approver 2 clicks the `Approve` button and is able to approve the expense. **_Is this expected?_**
15. The expense is approved without error and the status is changed to `Waiting for an admin to pay expense(s)`. **_Is this expected?_**


https://github.com/user-attachments/assets/58212f47-4923-4a78-8147-f21cf341a5de

@trjExpensify @Beamanator Please help to confirm the expected behaviours of highlighting steps, thanks! See the video from `0:50` to `1:05`

**Comment by trjExpensify** [comment] 2024-11-28 14:29
>As far as I know, YES all of those are expected because AFTER approver 1 approves the report (in step 11), we look at the submitter's current approval chain (which at that step, only includes approver 2) - and since approver 2 hasn't approved yet, they become next on the list to approve the report 👍

Interesting. That's the behaviour on OldDot as well? Do you have the code to link for ref? I asked @NikkiWines about that above, and neither of us could confirm that's the case.

>Do you mean the report when approver1 clicks Approve is then sent to the "new" approver to approve as well? If so, I'm not aware of that historical logic. I would have assumed this report would go to the approvesTo || overLimitForwardsTo set for approver1. Any new reports get submitted to the new approver, or if the report is rejected and resubmitted. @NikkiWines I had a rummage for this one in the code, but couldn't find it to confirm/deny.

> Agreed with @trjExpensify - I just checked the flow on oldDot and for reports that are 'in progress' (i.e. going through the approval process), we don't seem to update the approver to the newly set one. The updated approver only applies if the report is rejected & resubmitted or if a new report is made.

**Comment by Beamanator** [comment] 2024-11-29 18:45
> Do you mean the report when approver1 clicks Approve is then sent to the "new" approver to approve as well? If so, I'm not aware of that historical logic. I would have assumed this report would go to the approvesTo || overLimitForwardsTo set for approver1.

I know I USED TO think that way 😅  then I did a decent amount of testing and found that not to be the case, I thinkkkkk I explained in slack somewhere... it's all related to [this "conclusion" i posted](https://expensify.slack.com/archives/C06ML6X0W9L/p1729756475651949)

**Comment by Beamanator** [comment] 2024-11-29 18:47
So the points are:
1. If a report already has a manager & they get removed from the approval chain, we stop caring about the current manager's approval chain, and we purely care about "who is next to approve in the submitter's **current / new** approval chain"

**Comment by Beamanator** [comment] 2024-11-29 18:49
In [ReportUtils::buildApprovalChain](https://github.com/Expensify/Web-Expensify/blob/bd36b8556e41710526328edceff7c05a4787b7fb/lib/ReportUtils.php#L90) (this is the OldDot approval-chain building... NewDot does it all in Auth) you can see that the current report **manager** is never inserted into the chain, we ONLY insert:
1. `$ruleApprovers` (category / tag approvers)
2. The approvalChain built from the policy's `submitsTo` -> `forwardsTo` -> ...

**Comment by eh2077** [comment] 2024-12-02 09:13
Not overdue, discussion is ongoing

**Comment by trjExpensify** [comment] 2024-12-02 11:54
> In [ReportUtils::buildApprovalChain](https://github.com/Expensify/Web-Expensify/blob/bd36b8556e41710526328edceff7c05a4787b7fb/lib/ReportUtils.php#L90) (this is the OldDot approval-chain building... NewDot does it all in Auth) you can see that the current report **manager** is never inserted into the chain, we ONLY insert:
> 
> 1. `$ruleApprovers` (category / tag approvers)
> 2. The approvalChain built from the policy's `submitsTo` -> `forwardsTo` -> ...

Great stuff! So I agree we can close this issue then. :)

**Comment by slafortune** [comment] 2024-12-03 21:16
Thanks all!  Those details are super helpful

**Closed by slafortune** 2024-12-03 21:16 UTC
Labels: External, Engineering, Daily, Bug

**Comment by nkdengineer** [comment] 2024-12-16 08:24
@slafortune Should I have compensation for this issue since it was assigned and I spent a lot of effort following this issue and worked on the PR [here](https://github.com/Expensify/App/pull/51713) before we decided to close this as expected? This is a similar [case](https://github.com/Expensify/App/issues/49544#issuecomment-2445590271).

**Comment by nkdengineer** [comment] 2024-12-24 09:06
@slafortune friendly bump here

**Comment by slafortune** [comment] 2025-05-08 16:28
Sorry I've not done this!  https://www.upwork.com/nx/wm/offer/107230785
