### ISSUE TITLE
[$500] IOS -  The Chat report displays the wrong Latest Sender's name in LHN after logging in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26609] opened 2023-09-03 16:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

PRECONDITION: The user has joined a public group chat with a long chat history. For Example:
  
    - Bob-testing: https://staging.new.expensify.com/r/5593084223054221
1. Log in to the account that has joined a public/group chat with a long chat history.
2. On the LHN: check the name of the Latest Sender displayed.
3. Open the chat to view chat's details.
4. Verify the actual sender who sent the Last Message in the chat.
5. Compare the Sender's name from step #4 with the name obtained in step #2.
6. Observe that the latest sender's name is different.

## Expected Result:
The latest sender's name should match between step #4 and #2

## Actual Result:
The latest sender's name is different.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b182771-c6c3-41bb-8148-87a2c048ebc2

![wrong-sender-name](https://github.com/Expensify/App/assets/93399543/83a653fa-2216-4608-91ea-83851c616fde)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1693213921747209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd85da703f1b3f23</li>
        <li>Upwork Job ID: 1699155042104852480</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-09-05 20:18
Applying the external label

**Comment by slafortune** [comment] 2023-09-08 17:22
Still waiting on proposals.

Assigning a new BZ member, I am out on sabbatical

**Comment by isabelastisser** [comment] 2023-09-11 17:23
Not overdue; waiting on proposals!

**Comment by isabelastisser** [comment] 2023-09-12 19:37
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-09-15 15:17
Still waiting for proposals.

**Comment by tranvantoan-qn** [comment] 2023-09-19 10:12
For more information, there are instances where the issue has been reported:
- https://expensify.slack.com/archives/C049HHMV9SM/p1687647652432809
- https://github.com/Expensify/App/issues/21510#issue-1773237327

**Comment by isabelastisser** [comment] 2023-09-20 15:55
Thanks! @ArekChr can you still reproduce this issue?

**Comment by tranvantoan-qn** [comment] 2023-09-20 16:05
@isabelastisser 
Yes, it's still happening, please look at the attached image:
<img width="959" alt="Untitled" src="https://github.com/Expensify/App/assets/10254571/86ad7975-b151-4fb5-af66-afd3d3a80059">

**Comment by isabelastisser** [comment] 2023-09-20 20:36
Thanks! Waiting for proposals.

**Comment by mvtglobally** [comment] 2023-09-28 03:18
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2023-09-28 14:34
Not overdue.

**Comment by mvtglobally** [comment] 2023-10-05 03:05
Issue not reproducible during KI retests. (Second week)

**Comment by tranvantoan-qn** [comment] 2023-10-05 03:21
Don't know how you reproduced it, but it is still happening as always

The issue will happen AFTER logging in and accessing the chat room first time, so we need:
1. Logout the app
2. Login again
3. Check the last sender's name showing on the chat
4. Click on the chat to view details, and compare the name with #3.
5. 
![Proof 1](https://github.com/Expensify/App/assets/10254571/f1445da0-eb3d-4a42-8998-670279bafba4)
![Proof 2](https://github.com/Expensify/App/assets/10254571/5d232628-50ac-4c51-8761-32bc9406589e)

**Comment by tranvantoan-qn** [comment] 2023-10-05 13:05
Yes. It is still happening as I explained here 
https://github.com/Expensify/App/issues/26609#issuecomment-1747975327

**Comment by MrMuzyk** [comment] 2023-10-10 10:44
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2023-10-10 12:08
@tranvantoan-qn 
Hey, I've managed to reproduce something similar but I'm not sure what the correct outcome here should be as the scenario is a bit more complex.

https://github.com/Expensify/App/assets/23487612/5cac4240-6a48-4233-84d0-a5395a51a0bb

After logging in, as the latest message in the chat, I see last sender from the message that is only visible to me and message text from the chat that was last message visible to everyone participating. What should be the proper behaviour here?

Should messages only visible to me be ignored and not displayed as the last message and we should display latest message visible to everyone with the correct sender OR we should display message only visible to me with the correct sender?

**Comment by tranvantoan-qn** [comment] 2023-10-10 16:10
@MrMuzyk Mr
I don't know if we need to show the "only visible to you" message on the main page (on Desktop, we call it LHN - Left Hand Navigator) - as this should be confirmed by Expensify's team member

But in my opinion, there is no problem if we show it as long as the sender's name and the message is the same between the main page and the details page. So in this case:
- **For you**: It would show `Bob Ladue: testing 1 2 3; can I....`
- **For me** (and maybe others who didn't get the message  "only visible to you"): It would show `applausetester+kh0101@applause.com: 2`

**Comment by mvtglobally** [comment] 2023-10-12 03:48
Issue not reproducible during KI retests. (Third week)

**Comment by isabelastisser** [comment] 2023-10-16 20:37
@MrMuzyk @mvtglobally can this still be reproduced? Should we close it?

**Comment by MrMuzyk** [comment] 2023-10-17 10:08
@isabelastisser I believe it is still reproducible. Gonna post my proposal below

**Comment by MrMuzyk** [comment] 2023-10-17 10:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user logs in and looks at the report on the LFH no Latest Sender is displayed or Latest Sender that is displayed is incorrect. Once user clicks and opens the report then additional info is fetched and from now on till logout Latest Sender will be displayed correctly for such report.

### What is the root cause of that problem?
Latest Sender detailed info is not provided together with the report details. In ONYX under `report_${reportID}` entry the only relevant data to display Lastest Sender with the last message is `lastMessageText`. `lastActorAccountID ` is also provided but it’s not enough to display the name. In codebase inside SidebarUtils.js lib there is an attempt to retrieve display name for Latest Sender - https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.js#L321
In majority of our cases it’s empty as there are no details for the ID provided in report object (`lastActorAccountID`) and sometimes it comes incorrect due to the fact that sometimes messages visible only to logged in user are treated as latest message and sometimes not.

### What changes do you think we should make in order to solve the problem?

I believe a proper solution to this issues would be to provide another field in the report object saved in ONYX under `report_${reportID}`. Apart from `lastMessageText` new field should be added, for example: `lastActorDisplayName`, that would contain the display name of Latest Sender. This would allow us to consistently and correctly display the name of the Latest Sender.

### What alternative solutions did you explore?
I was looking for a way to fetch the missing data myself as ID of the user we want to get the display name for is provided but I didn’t succeed. I couldn’t find a method that would allow me to fetch detailed data of the user based on the provided ID. On top of that this wouldn’t be recommended way to fix that issue because it would require introducing another API call as missing details are not present in ONYX at this point and would have to be fetched.

**Comment by isabelastisser** [comment] 2023-10-17 15:52
thanks @MrMuzyk ! @aimane-chnaif can you please review it? Thanks!

**Comment by isabelastisser** [comment] 2023-10-19 16:03
Bump @aimane-chnaif

**Comment by tranvantoan-qn** [comment] 2023-10-19 16:51
I haven't seen the issue like that, and the public rooms I've joined are:
- **Scaling New Heights 2023 - #activityfeed**: https://staging.new.expensify.com/r/5303403427249671 
- **Scaling New Heights 2023 - #bobs-testing**:  https://new.expensify.com/r/5593084223054221

**Comment by tranvantoan-qn** [comment] 2023-10-19 17:10
Yes, I tried with completely new account. 
- Can you see the joined room on account B?
- If you logged out on B and re-login, can you still see that room?
![4C935480-B9D2-4B87-937E-DC47F58F993E](https://github.com/Expensify/App/assets/10254571/ab75e57c-b62c-4217-a000-2dba18e23859)

**Comment by MrMuzyk** [comment] 2023-10-25 10:16
Hey, I’ve started work on some wave6 features that are high-priority and someone else from Callstack will take over this issue

**Comment by tranvantoan-qn** [comment] 2023-10-25 13:11
@kbecciv @aimane-chnaif 

According to [this conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1696265713396809) I've missed

Can you help me to remove the link `https://staging.new.expensify.com/r/5303403427249671` from the [ Issue description](https://github.com/Expensify/App/issues/26609#issue-1879151495) 

@MrMuzyk Please note that we don't need to send a new message to the rooms in order to reproduce the issue.

**Comment by isabelastisser** [comment] 2023-10-25 16:29
Hey @tranvantoan-qn , I've removed the link!

@MrMuzyk, can you please assign the new contributor who will replace you?

**Comment by barttom** [comment] 2023-10-27 06:11
@isabelastisser Hi! I'm Bartek from Callstack and I want to take over this issue, please assign me :)

**Comment by isabelastisser** [comment] 2023-10-30 16:05
hey @barttom, any updates?

**Comment by barttom** [comment] 2023-10-30 18:22
I agree with the proposal from @MrMuzyk. Looks like we waiting for reviewing proposal by @aimane-chnaif.

**Comment by thienlnam** [comment] 2023-10-31 22:13
Ah interesting, so you might not have the personal details of the last actor accountID and so it just falls back to the most recent visible action? 

If we added the key lastActorDisplayName, that would essentially be the fallback if don't have that accountID in your personal details right because otherwise it would pull the actual display name or email.

I don't really like the idea of adding another key to determine which name to show considering it's only applicable for certain users, and then there's always the question of which display name to use - from the lastReportAction or the report and keeping those in sync we'd probably have to make a decent amount of onyx optimistic updates

I'm leaning towards the second solution since that seems to be how we handle these other scenarios where we don't have personal details for a user. 

Though curious if ya'll agree (@puneetlath / @Beamanator)

**Comment by puneetlath** [comment] 2023-11-01 18:07
Ah interesting. So we get the personalDetails in the openReport command, but since that hasn't been called yet it can be wrong. I agree with just not showing a display name in the case where we don't have it.

**Comment by puneetlath** [comment] 2023-11-01 20:51
Yeah, we'll need to handle that on the back-end.

**Comment by isabelastisser** [comment] 2023-11-30 20:54
Offers sent in Upwork. All set!

**Closed by isabelastisser** 2023-11-30 20:54 UTC
Labels: Reviewing, Engineering, Daily, Monthly, Internal, Bug
