### ISSUE TITLE
[$500] [MEDIUM] Tag - Notification shows "tag" instead of custom name for tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35401] opened 2024-01-30 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34482
## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace
- The Collect workspace has custom name for Tag
1. [Employee] Go to workspace chat
2. [Employee] Create a manual expense with tag
3. [Employee] Navigate to request details page
4. {Employee] Click tag and select a different tag
5. [Admin} Note that the notification shows "tag" instead of custom name for tag

## Expected Result:
The notification will show custom name for tag instead of the default tag name (Tag)

## Actual Result:
The notification shows default tag name (Tag). On Android and iOS app, it shows "changed the request" with no details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32d2c01e-b207-4858-a9a3-af54963e9d2f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016118ce4a2a30a489</li>
        <li>Upwork Job ID: 1752326219551039488</li>
        <li>Last Price Increase: 2024-02-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-30 13:43
We think that this bug might be related to #wave. 
CC @zanyrenney

**Comment by cead22** [comment] 2024-01-30 13:58
Given this is push notification, I bet this is a back end issue that needs to be fixed internally

**Comment by johncschuster** [comment] 2024-02-02 22:21
Thanks for grabbing it, @cead22!

**Comment by johncschuster** [comment] 2024-02-06 23:00
Bumping to keep Melvin at bay. How's it going @cead22?

**Comment by cead22** [comment] 2024-02-07 01:53
Sorry I'm still a bit behind and haven't gotten to this, but it's on my list

**Comment by cead22** [comment] 2024-02-10 00:38
@johncschuster I think External and Help Wanted are the labels to apply to get this through the normal bug process, but correct me if I'm wrong

**Comment by jcdiprose** [comment] 2024-02-10 17:48
@ishpaul777 I cannot replicate the issue. I cannot see the A B C D option or even the tag option. If the instructions could be revised that would help

**Comment by jcdiprose** [comment] 2024-02-10 18:37
Getting error creating a new workspace @ https://dev.new.expensify.com:8082/settings/workspaces

**Comment by Tony-MK** [comment] 2024-02-10 19:59
Hi 👋 , @jcdiprose. 

A B C D is the custom tag name.

The notification messages are supposed to be constructed from a template such as: 
`change the {customOrTagName} to {newTagValue} (previously "{newTagValue}")`

In this example, we want to replace the **tag** word with the custom tag name, **A B C D**.

#### Expected Result
changed the **A B C D** to "Saturn" (previously "Jupiter")

#### Actual Result
changed the **tag** to "Saturn" (previously "Jupiter")

I hope this helps. 🤔 
Since I believe you are new, I don't mind you asking me questions on Slack.

@ishpaul777, Can you confirm? 🙏

**Comment by jcdiprose** [comment] 2024-02-10 20:03
Thanks, @Tony-MK What's your name on slack? I have a couple of questions

**Comment by Tony-MK** [comment] 2024-02-11 02:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tag - Notification shows "tag" instead of custom name for tag

### What is the root cause of that problem?

The [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  from the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) since not all reports have the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  property.

https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044

Hence, the [`policyTags`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L104)  record was not found in `ONYXKEYS.COLLECTION.POLICY_TAGS` to get the [`policyTagListName`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L105)  and defaults to using to normal `common.tag` value.

https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103-L106

### What changes do you think we should make in order to solve the problem?


We can improve the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) so that an appropriate value to [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) is found, even if the report does not directly possess the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) property. 

Therefore, we find the parent report with a value for [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  but only if the report is a policy expense chat.

```
const report = getReport(reportID);
return (report?.isPolicyExpenseChat ?  getRootParentReport(report) : report)?.policyID; 
```

### What alternative solutions did you explore? (Optional)

To avoid regressions in other segments of the app which are prone to the mentioned changes to the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) function, we get the root IOU report action to use `reportAction.orginialMessage.IOUTransactionID` with `iouReportID` as the argument for the `ReportUtils.getReportPolicyID` function.

This is because every iou report, which belongs to a workspace, has the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  property. 

Therefore, the changes to the [`getForReportAction`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L99) function over [here](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) should similar to the code snippet below.

```
const iouReportID = getRootReportAction(reportAction)?.originalMessage.IOUTransactionID ;
const policyID = ReportUtils.getReportPolicyID(iouReportID || reportID) ?? '';
```

**Comment by Tony-MK** [comment] 2024-02-11 02:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tag - Notification shows "tag" instead of custom name for tag

### What is the root cause of that problem?

The [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  from the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) since not all reports have the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  property.

https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044

Hence, the [`policyTags`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L104)  record was not found in `ONYXKEYS.COLLECTION.POLICY_TAGS` to get the [`policyTagListName`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L105)  and defaults to using to normal `common.tag` value.

https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103-L106

### What changes do you think we should make in order to solve the problem?


We can improve the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) so that an appropriate value to [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) is found, even if the report does not directly possess the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) property. 

Therefore, we find the parent report with a value for [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  but only if the report is a policy expense chat.

```
const report = getReport(reportID);
return (report?.isPolicyExpenseChat ?  getRootParentReport(report) : report)?.policyID; 
```

### What alternative solutions did you explore? (Optional)

To avoid regressions in other segments of the app which are prone to the mentioned changes to the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) function, we get the root IOU report action to use `reportAction.orginialMessage.IOUTransactionID` with `iouReportID` as the argument for the [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L4042-L4044) function.

This is because every iou report, which belongs to a workspace, has the [`policyID`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103)  property. 

Therefore, the changes to the [`getForReportAction`](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L99) function over [here](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ModifiedExpenseMessage.ts#L103) should similar to the code snippet below.

```
const iouReportID = getRootReportAction(reportAction)?.originalMessage.IOUTransactionID ;
const policyID = ReportUtils.getReportPolicyID(iouReportID || reportID) ?? '';
```

**Comment by brandonhenry** [comment] 2024-02-19 16:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The notification for a modified expense in a workspace displays the default word "tag" instead of the custom name for the tag defined in the workspace settings.

### What is the root cause of that problem?
The root cause of the issue is that the notification message generation logic does not correctly handle custom tag names. Instead of using the custom name defined in the policy tags, it defaults to using the generic term "tag." This results in the notification displaying "tag" instead of the custom tag name.

https://github.com/Expensify/App/blob/3a95869505bf5165a039eb416d026d4f6d603c99/src/libs/ModifiedExpenseMessage.ts#L196

The line results in "tag" on ios and Android because for some reason, the PolicyUtils doesn't return the proper tag name. 

This led me to the actual cause which is `PolicyUtils.getTagListName`. This function relies on the index of a tag passed in to provide the proper tagList name. 

This is likely failing due to the ordering of list changing. I think we should not rely on index to get the tagListName

### What changes do you think we should make in order to solve the problem?

1. Update the `getTagListName` function to accept a tag key instead of an index:

```javascript
function getTagListName(policyTagList: OnyxEntry<PolicyTagList>, tagKey: string): string {
    if (isEmptyObject(policyTagList)) {
        return '';
    }

    return policyTagList?.[tagKey]?.name ?? '';
}
```

2. Update the `hasModifiedTag` block to use the tag key directly:

```javascript
if (hasModifiedTag) {
    const policyTags = allPolicyTags?.[`${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`] ?? {};
    const transactionTag = reportActionOriginalMessage?.tag ?? '';
    const oldTransactionTag = reportActionOriginalMessage?.oldTag ?? '';
    const splittedTag = transactionTag.split(CONST.COLON);
    const splittedOldTag = oldTransactionTag.split(CONST.COLON);
    const localizedTagListName = Localize.translateLocal('common.tag');

    splittedTag.forEach((newTag, index) => {
        const oldTag = splittedOldTag[index] ?? '';
        const tagKey = `tag_${index}`;

        if (newTag !== oldTag) {
            const policyTagListName = PolicyUtils.getTagListName(policyTags, tagKey) || localizedTagListName;

            buildMessageFragmentForValue(
                PolicyUtils.getCleanedTagName(newTag),
                PolicyUtils.getCleanedTagName(oldTag),
                policyTagListName,
                true,
                setFragments,
                removalFragments,
                changeFragments,
                policyTagListName === localizedTagListName,
            );
        }
    });
}
```

This change uses the tag key directly, which eliminates the reliance on the order of the keys in the `policyTags` object. I believe this will fix the issue

**Comment by Victor-Nyagudi** [comment] 2024-02-21 12:27
How can I enable notifications on DEV or even staging? 

Based on this [Slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1679911233567859?thread_ts=1679694340.177299&cid=C01GTK53T8Q), it seems contributors aren't able to test iOS notifications. 

Come to think of it, I've never received notifications on Android Dev, only the production  app. Ditto for the web and desktop app even though I have them enabled.

**Comment by cead22** [comment] 2024-02-21 18:55
@Victor-Nyagudi this is a local browser notification, so I imagine you should be able to allow notifications in chrome to tests this

**Comment by Victor-Nyagudi** [comment] 2024-02-21 18:58
I have them all on "allow" in site settings, but I don't get anything.

Any idea how I could troubleshoot this, @cead22 ?

What actions usually trigger a notification? Maybe I'm looking for them in the wrong places.

**Comment by cead22** [comment] 2024-02-21 21:09
@Victor-Nyagudi can you ask in #expensify-open-source? I don't know the answer but I bet others do, and that way we bothnlearn

**Comment by Victor-Nyagudi** [comment] 2024-02-22 07:23
I actually tried [Slack](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1708433875382409?thread_ts=1708433875.382409&cid=C01GTK53T8Q) first before asking here.

Didn't get much traction.

**Comment by Tony-MK** [comment] 2024-02-24 02:40
Has anyone had luck enabling web notifications?

Well, I found out that this specific issue is not reproducible.

However, the backend does not synchronize the tags when the ``Use multiple levels of tags`` gets disabled and the tag is changed.


Some previous modified expense actions text is `changed the request`.


![](https://github.com/Expensify/App/assets/22982173/c2ed6375-bbbc-42e5-87b6-c8c6c339a6c6)

**Comment by Tony-MK** [comment] 2024-02-24 02:42
Has anyone had luck enabling web notifications?

Well, I found out that this specific issue is not reproducible.

However, the backend does not synchronize the tags when the ``Use multiple levels of tags`` gets disabled and the tag is changed.

After some investigation, it appears this should be an issue with the notification at the backend.

A frontend issue I noticed is that the previous modified expense actions text is `changed the request`.

https://github.com/Expensify/App/assets/22982173/c2ed6375-bbbc-42e5-87b6-c8c6c339a6c6

**Comment by Tony-MK** [comment] 2024-02-24 02:43
Has anyone had luck enabling web notifications?

Well, I found out that this specific issue is not reproducible.

However, the backend does not synchronize the tags when the ``Use multiple levels of tags`` gets disabled and the tag is changed.

After some investigation, it appears this should be an issue with the notification at the backend.

A frontend issue I noticed is that the previous modified expense actions text is `changed the request`.

![Screenshot](https://github.com/Expensify/App/assets/22982173/c2ed6375-bbbc-42e5-87b6-c8c6c339a6c6)

**Comment by Tony-MK** [comment] 2024-02-25 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The root cause is that the app does not have a realistic `report` but uses a half-realistic one that does not have `policyID`.

![OnyxDB](https://github.com/Expensify/App/assets/22982173/f5fbbc37-9c08-4a36-a590-2049f2815e62)

Therefore, the value of the `policyID` is an empty string since [`ReportUtils.getReportPolicyID`](https://github.com/Expensify/App/blob/5eed6322bd2e559c684481e8bc0122b0825779e7/src/libs/ModifiedExpenseMessage.ts#L105) function returns nothing.

https://github.com/Expensify/App/blob/5eed6322bd2e559c684481e8bc0122b0825779e7/src/libs/ModifiedExpenseMessage.ts#L104-L105

![Debug](https://github.com/Expensify/App/assets/22982173/9f3a1473-33a6-49b4-b105-c7cd573bcddc)

### What changes do you think we should make in order to solve the problem?


If the realistic report is not found from the front end, we can use `makeRequestWithSideEffects` to fetch the realistic report. Then, push the `MODIFIED_EXPENSE` report action notification.
 
### What alternative solutions did you explore? (Optional)

**Option A:**

From the backend, send the necessary `report` attributes like `policyID` or the whole `report` data as part of the notification of the `MODIFIED_EXPENSE` report action.

**Option B:**

We can try and get the parent action of the report and use it to recursively get the parent report and check if the report is a workspace by looking for `policyID`.

***Note:*** Perhaps we need to include policy-related items that are not saved and affect the `MODIFIED_EXPENSE` push notification.

**Comment by cead22** [comment] 2024-02-26 20:35
Still evaluating proposals

**Comment by johncschuster** [comment] 2024-02-29 23:12
Thanks for letting us know, @ishpaul777, and thanks for taking it on, @mkhutornyi!

**Comment by Tony-MK** [comment] 2024-03-04 20:30
@mkhutornyi, Could you please give me some feedback on my [proposal](https://github.com/Expensify/App/issues/35401#issuecomment-1962775933).

Thank you.

**Comment by johncschuster** [comment] 2024-03-14 21:04
Bumped again in Slack

**Closed** 2024-03-19 18:42 UTC
Labels: Engineering, Daily, Internal, Bug
