### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Unable to change the digit before decimal point in IOU

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27029] opened 2023-09-08 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money with the decimal amount to another user. (Click on Request money > Enter amount & Click on Next button > Select User& Click on Request button)
2. Click on the amount in IOU.
3. Move the cursor before the decimal point.
3. Try to press the backspace key.
Expected Result: The user should be able to change the digit if this is the only number before decimal point
Actual Result: The user not able to change/delete the digit if this is the only number before decimal point

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0077d45f-02b4-4889-ba45-a048a83dca00

**Expensify/Expensify Issue URL:**
**Issue reported by:** @oleksandr-pantsyr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692640033454539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011137458c0195caf3</li>
        <li>Upwork Job ID: 1701124994025054208</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 26933703</li>
<li>oleksandr-pantsyr | Reporter | 26933705</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-08 14:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to change the digit before decimal point in IOU when removing digits before the decimal point.

### What is the root cause of that problem?
Values without a digit before the decimal point are considered invalid based on the regex in MoneyRequestUtils.

### What changes do you think we should make in order to solve the problem?
Update the regex.


### What alternative solutions did you explore? (Optional)

**Comment by ishpaul777** [comment] 2023-09-08 15:11
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unable to change the digit before decimal point in IOU when removing digits before the decimal point.

### What is the root cause of that problem?
if there is no digit before the decimal point no new amount is set and delete digit is ignored are considered invalid based on the regex in [MoneyRequestUtils](https://github.com/Expensify/App/blob/main/src/libs/MoneyRequestUtils.js) which looks intentional.

### What changes do you think we should make in order to solve the problem?
UPDATE addLeadingZero function, so 
 - if amount has a leading "." and no digit before decimal point, add a zero
 - if amount has a leading zero and a digit before decimal point, remove the leading zero

```
function addLeadingZero(amount) {
    //  if amount has a leading . and no digit before decimal point, add a zero
    if (amount.split('.')[0].length === 0 && amount[0] === '.') {
        return `0${amount}`;
    }
    // if amount has a leading zero and a digit before decimal point, remove the leading zero
    if (amount.split('.')[0].length > 1 && amount[0] === '0' && amount[1] !== '.') {
        return amount.slice(1);
    }

    return amount === '.' ? '0.' : amount;
}
```

**Comment by adelekennedy** [comment] 2023-09-11 06:45
reproduced!

**Comment by akinwale** [comment] 2023-09-11 07:53
> I think that this is not a bug - we not allowing to have "." as a first symbol in the input - because decimal must have main part before dot. Even when you try to click on dot in empty field - it will automatically add 0 and result will be "0. cc @adelekennedy

This behaviour still results in a poor user experience, especially on mobile, because the user has to tap to move the cursor to be able to be able to update the whole number part. I think the `addLeadingZero` method was implemented to prevent users from entering just a decimal separator in the amount field.

If an amount gets submitted like ".01", this gets automatically fixed to "0.01" on the confirmation page before the user sends the request, so starting with the decimal separator in the input field would not be an issue.

**Comment by adelekennedy** [comment] 2023-09-13 09:13
Agree -I think this is still poor performance and something we should update

**Comment by narefyev91** [comment] 2023-09-13 09:17
Ok in that case we can move with @akinwale proposal https://github.com/Expensify/App/issues/27029#issuecomment-1711782380
🎀 👀 🎀 C+ reviewed

**Comment by ishpaul777** [comment] 2023-09-13 09:30
@narefyev91 If chnages from selected proposal applied user will be able to remove "0" before "." and there are digits after decimal while we currently explictly adding 0 when "." is added, Can you take a look at my proposal I belive the UX with proposed changes is slightly better

**Comment by akinwale** [comment] 2023-09-13 09:34
> 

This makes 

> @narefyev91 If chnages from selected proposal applied user will be able to remove "0" before "." and there are digits after decimal while we currently explictly adding 0 when "." is added, Can you take a look at my proposal I belive the UX with proposed changes is slightly better

This approach makes sense for a fixed-format input, but in the current implementation, the amount input is a free-form input. In this case, if a user deletes a digit, they would expect it to be removed from the input, not replaced with another value.

**Comment by narefyev91** [comment] 2023-09-13 09:35
> @narefyev91 If chnages from selected proposal applied user will be able to remove "0" before "." and there are digits after decimal while we currently explictly adding 0 when "." is added, Can you take a look at my proposal I belive the UX with proposed changes is slightly better

Hey! Yup i checked your proposal - and if we allow user to remove a number before dot - we expect that it will be nothing - rather than having again 0

**Comment by ishpaul777** [comment] 2023-09-13 10:03
Thanks for clarification of expected, I just checked applying the changes it also dont let you delete digit after the ".", I believe the selected proposal is incomplete and can cause regression, I updated the propsal to cover the edge case along with the expected behaviour.

> we expect that it will be nothing - rather than having again 0

https://github.com/Expensify/App/assets/104348397/763fcae0-c94f-4a91-80e8-000690f26ce5

**Comment by narefyev91** [comment] 2023-09-13 11:35
> Thanks for clarification of expected behaviour, I just checked applying the changes it also dont let you delete digit after the ".", I believe the selected proposal is incomplete and can cause regression, I updated the propsal to cover the edge case along with the expected behaviour. @narefyev91
> 
> > we expect that it will be nothing - rather than having again 0
> 
>  Screen.Recording.2023-09-13.at.3.15.10.PM.mov

Thank you for you clarification - in any case - the root case of the problem was identified by @akinwale - any other code changes / places where it should be applied should be discussed inside raised PR

**Comment by ishpaul777** [comment] 2023-09-13 11:46
> We look for the earliest provided, best proposed solution that addresses the job.
According to docs i believe the best proposed solution is selected, not the proposal with correct root cause, please correct me if i am wrong?

**Comment by akinwale** [comment] 2023-09-13 11:49
> > We look for the earliest provided, best proposed solution that addresses the job.
> 
> According to docs i believe the best proposed solution is selected, not the proposal with correct root cause, please correct me if i am wrong?

A proposal was already selected and then you changed your proposal after the selection was made, building off of the selected proposal.

**Comment by akinwale** [comment] 2023-09-13 11:49
> > We look for the earliest provided, best proposed solution that addresses the job.
> 
> According to docs i believe the best proposed solution is selected, not the proposal with correct root cause, please correct me if i am wrong?

A proposal was already selected and then you changed your proposal after the selection was made, building off of the selected proposal.

**Comment by narefyev91** [comment] 2023-09-13 14:36
No worries guys - last word we will get from @MonilBhavsar

**Comment by adelekennedy** [comment] 2023-09-18 08:59
@MonilBhavsar can you take a look at the proposals above and @narefyev91 recommendation?

**Comment by MonilBhavsar** [comment] 2023-09-20 06:52
Looking!

**Comment by MonilBhavsar** [comment] 2023-09-20 07:09
Hmm, so we don't allow amount to start with decimal or said other way the amount should start with a digit.
Now, when we remove digits before decimal we are not allowing it. So that does seem like a weird UX. I think if it's one digit before decimal and user tries to remove it. We should display zero there. For example: If $2.18 is entered and user wants to remove `2`, the new amount will be displayed as $0.18. @adelekennedy do you agree with this?


@narefyev91 looks like the accepted proposal is not working as above. We don't allow the amount to start with decimal point, I think we should keep that behaviour.

**Comment by ishpaul777** [comment] 2023-09-20 07:26
Hii @MonilBhavsar 👋, can you check my [proposal](https://github.com/Expensify/App/issues/27029#issuecomment-1711826542), before the current update in the edit history

**Comment by narefyev91** [comment] 2023-09-20 08:55
@MonilBhavsar i think here we get a little more clarification initially
<img width="952" alt="Screenshot 2023-09-20 at 11 47 15" src="https://github.com/Expensify/App/assets/28352309/82f385c5-80ef-4437-a539-4a0e037f454d">

And decision should be - which way to follow - either .01, or 0.01 - after removing a last digit before decimal separator. And based on the final decision we can assign right contributor for this fix
- with .01 - @akinwale 
- with 0.01 - @ishpaul777 
For me personally looks strange - that when you remove last digit - you get 0.00 - and cursor stays after the first 0 - like 0|.00 - expectation here - that if i will click on any number will be 01|.00 - and not 1.00 - but maybe my feelings are wrong :-)

**Comment by narefyev91** [comment] 2023-09-21 07:03
Friendly bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-09-21 07:30
> For me personally looks strange - that when you remove last digit - you get 0.00 - and cursor stays after the first 0 - like 0|.00 - expectation here - that if i will click on any number will be 01|.00 - and not 1.00 - but maybe my feelings are wrong :-)

We do similar when we have no input, right?
I would vote for `0.01` because by default also, if you simply enter `.`, we add a zero before it, because we don't want amount to start with zero
Would also like to hear thoughts from @adelekennedy 

<img width="295" alt="Screenshot 2023-09-21 at 3 28 17 PM" src="https://github.com/Expensify/App/assets/32012005/d1d652e1-3d7d-4ef7-8d21-1a9b54cd0327">

**Comment by adelekennedy** [comment] 2023-09-25 07:41
agree with you @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-09-27 06:03
Thanks Adele!
@narefyev91 then I think we go with @ishpaul777's proposal? Is that in edit history? If so, could you please update it to latest?

**Comment by narefyev91** [comment] 2023-09-27 06:11
> Thanks Adele! @narefyev91 then I think we go with @ishpaul777's proposal? Is that in edit history? If so, could you please update it to latest?

Done - we are good to go

**Comment by ishpaul777** [comment] 2023-09-29 10:54
Missed the assignment notification, I am on it now.

**Comment by MonilBhavsar** [comment] 2023-10-09 08:57
> would that be eligible for bounus?
Apologies. The review was delayed because of me, else would have made in bonus timeline. cc @adelekennedy

**Comment by adelekennedy** [comment] 2023-10-09 15:30
Noted that speed bonus will apply for this job

**Comment by MonilBhavsar** [comment] 2023-10-18 06:58
@narefyev91 could you please take a look at the checklist. We're good to issue payment here and close this!

**Comment by narefyev91** [comment] 2023-10-18 06:59
- The PR that introduced the bug has been identified. Link to the PR - it was fully new functionality
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by adelekennedy** [comment] 2023-10-18 16:31
### Payouts due:

Reporter: $50 @oleksandr-pantsyr
Contributor: $750 @ishpaul777 

Eligible for 50% #urgency bonus? [Y](https://github.com/Expensify/App/issues/27029#issuecomment-1752593960)

Upwork job is [here](https://www.upwork.com/jobs/~011137458c0195caf3).

**Comment by adelekennedy** [comment] 2023-10-18 16:32
All payments have been made! I think we're good to close

**Closed by adelekennedy** 2023-10-18 16:32 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
