### ISSUE TITLE
[hold for payment 2024-04-29] [$500] [Held requests] System message for hold request shows a comma as reason

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38583] opened 2024-03-19 13:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Request money from any user.
3. Navigate to request details page.
4. Click 3-dot menu > Hold request.
5. Add a reason and save it.

## Expected Result:
The system message for hold request will show the entered reason.

## Actual Result:
The system message for hold request briefly shows the entered reason, then it changes to a comma.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a788cbbb-e058-4e53-b26b-a58292d03cbe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b056a4fad087d390</li>
        <li>Upwork Job ID: 1770105583965515776</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-19 13:30
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-19 13:30
We think that this bug might be related to #wave-collect - Release 1

**Comment by shahinyan11** [comment] 2024-03-19 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold request - System message for hold request shows a comma as reason
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/home/report/ReportActionItem.tsx#L520) we take wrong index from `action.message` . The index `1` always is coma
### What changes do you think we should make in order to solve the problem?
Take the index `3` instead `1` [here](https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/home/report/ReportActionItem.tsx#L520C119-L520C120)
```
translate('iou.heldRequest', {comment: action.message?.[3]?.text ?? ''})
```

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-03-19 15:10
Def seems like a bug.

**Comment by nkdengineer** [comment] 2024-03-19 15:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message for hold request briefly shows the entered reason, then it changes to a comma.

### What is the root cause of that problem?


The optimistic data of hold action is different from the data that is returned by server


<img width="379" alt="Screenshot 2024-03-19 at 22 22 38" src="https://github.com/Expensify/App/assets/161821005/107afdff-c8af-4935-a4a9-1e1131bd8642">


https://github.com/Expensify/App/blob/014557cad29ee8061efdf4cd799584f030e6b398/src/libs/ReportUtils.ts#L3690-L3695

And we're displaying the comment base on optimistic data
https://github.com/Expensify/App/blob/4ac5d6c349bfea568480149cf0197f104a202ab0/src/pages/home/report/ReportActionItem.tsx#L519-L520

So after the hold API is complete, the comment is replaced by `,`
### What changes do you think we should make in order to solve the problem?
We should sync the data that in optimisticData with the data that is returned by server like this
```
message: [
    {
        type: CONST.REPORT.MESSAGE.TYPE.TEXT,
        style: 'normal',
        text: Localize.translateLocal('iou.heldRequest', {comment}),
    },
    {
        type: CONST.REPORT.MESSAGE.TYPE.COMMENT,
        text: `, `,
    },
    {
        type: CONST.REPORT.MESSAGE.TYPE.COMMENT,
        text: `saying`,
    },
    {
        type: CONST.REPORT.MESSAGE.TYPE.COMMENT,
        text: comment,
    },
],
```
https://github.com/Expensify/App/blob/014557cad29ee8061efdf4cd799584f030e6b398/src/libs/ReportUtils.ts#L3690-L3695

And then here we will get the comment of hold action through the fourth element of message array `action.message?.[3].text ?? ''`
https://github.com/Expensify/App/blob/4ac5d6c349bfea568480149cf0197f104a202ab0/src/pages/home/report/ReportActionItem.tsx#L519-L520

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment] 2024-03-20 20:55
@mkhutornyi thoughts on proposals?

**Comment by joekaufmanexpensify** [comment] 2024-03-22 15:56
bump @mkhutornyi when you have a sec

**Comment by neil-marcellini** [comment] 2024-03-25 13:57
> I agree with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/38583#issuecomment-2007503401) to make optimistic data and server data always consistent. 🎀 👀 🎀 C+ reviewed

I also agree. After making the data consistent I think that we should **also** implement the alternate solution when getting the hold comment, so that it's more robust against breaking changes in the future.

**Comment by nkdengineer** [comment] 2024-03-26 06:21
@mkhutornyi The PR is [here](https://github.com/Expensify/App/pull/38980).

@neil-marcellini Can you please add `Reviewing` label manually? I missed add the link issue before `Ready for review`. Thank you.

**Comment by mallenexpensify** [comment] 2024-03-27 21:32
@mkhutornyi is unexpectedly going to be OOO for a while, @thesahindia , can you please take over as C+ here? If it doesn't work for you, please post in #contributor-plus

**Comment by joekaufmanexpensify** [comment] 2024-04-22 13:47
PR on staging

**Comment by joekaufmanexpensify** [comment] 2024-04-29 20:20
[Discussing](https://expensify.slack.com/archives/C01SKUP7QR0/p1714422020174389) payment next steps, since original C+ went OOO unexpectedly.

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:14
We discussed in slack, and we landed on 50/50 split for both C+, since @mkhutornyi reviewed proposals, and @thesahindia reviewed the PR.

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:14
That means we need to pay: 

- @mkhutornyi - $250 for C+ proposal review via Upwork. 
- @thesahindia - $250 for C+ PR review via NewDot. 
- @nkdengineer - $500 for PR via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:17
OG upwork job is closed, so made a new one: https://www.upwork.com/jobs/~01c5d794e2115e005d

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:19
@nkdengineer offer sent for $500!

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:19
@mkhutornyi offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2024-04-30 16:19
@thesahindia please request $250 via NewDot and confirm here once complete

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:08
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-05-07 14:56
@nkdengineer $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-05-13 14:25
Sounds good. Payment summary is [here](https://github.com/Expensify/App/issues/38583#issuecomment-2085829441). Payments outstanding still are @thesahindia's (which he needs to request). 

@mkhutornyi's payment is also outstanding. I see in slack they've been out for over a month, and we're not sure when they'll be back, so going to close this for now. @mkhutornyi once you're back, please comment here, and I will re-open this issue to send your payment for this issue!

**Closed by joekaufmanexpensify** 2024-05-13 14:25 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-31 04:17
$250 approved for @thesahindia

**Comment by mallenexpensify** [comment] 2024-06-06 00:08
@mkhutornyi is back, I paid them $250 via Upwork, the contract was still open.
