### ISSUE TITLE
Dev: Money owes preview background color is not changing on hover.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22582] opened 2023-07-10 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App > Navigate to any chat.
2. Press + from composer > Request money > Add amount > Press Next and Press Request.
3. We can see the Money Owed Preview message in chat, and now Do hover over to the Owed Preview.

## Expected Result:
On Hover over the money owes preview message background color of the preview should be changed like the same happens when we hover over on preview on the money details page.

## Actual Result:
There is no hover effect happening when hovering over the money owes preview so that the background color of the preview and hover color overlap.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.38-4
 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f46d1cf3-0369-4b44-a882-9d6a4686b94e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688983671141219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by esh-g** [comment] 2023-07-10 18:38
# Proposal

## Please re-state the issue
Money owe preview background color is not changing on hover

## What is the root cause of that problem?
There is no hover style to highlight the preview box which is present in split preview.

## What changes do you think we should make in order to solve this problem?
We should just add the hover styles so that the box is highlighted on hover in the following line:
https://github.com/Expensify/App/blob/eb1db9ef16b6f4a84b4a268d87fc7f9ee6654df1/src/components/ReportActionItem/ReportPreview.js#L107
```js
<View style={[styles.iouPreviewBox, props.isHovered ? styles.iouPreviewBoxHover : undefined]}>
```
Just like we do here:
https://github.com/Expensify/App/blob/0711784854917e4f56101b1af35f0f3db1decfc8/src/components/ReportActionItem/MoneyRequestAction.js#L151

## What other alternative approaches did you explore?
N/A

**Comment by Nikhil-Vats** [comment] 2023-07-10 18:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money ReportPreview's background color does not change on hover.

### What is the root cause of that problem?
When we are rendering `ReportPreview` in `ReportActionItem`, we pass `isHovered` prop -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/pages/home/report/ReportActionItem.js#L247-L254

But there is no such prop in `ReportPreview` so we don't add hover background color based on the hover state.
### What changes do you think we should make in order to solve the problem?
There is no use of `isHovered` prop in `ReportPreview` so we don't need to pass it, instead we should add a new prop `containerStyles` in `ReportPreview` and based on `hover` state in `ReportActionItem`, we should add hover background color -

```javascript
<ReportPreview
    iouReportID={ReportActionsUtils.getIOUReportIDFromReportActionPreview(props.action)}
    chatReportID={props.report.reportID}
    action={props.action}
    containerStyles={[hovered ? styles.iouPreviewBoxHover : undefined]}
    contextMenuAnchor={popoverAnchorRef}
    checkIfContextMenuActive={toggleContextMenuFromActiveReportAction}
/>
```

Then in `ReportPreview`, we need to change line 109 to use new `containerStyles` prop -
```javascript
<View style={[styles.iouPreviewBox, ...props.containerStyles]}>
```

P.S. - We can also keep the type of `containerStyles` prop as an object rather than an array.

This is consistent with what we are doing for `IOUPreview`. In `ReportActionItem`, we render `MoneyRequestAction` and pass it `isHovered` prop, and in `MoneyRequestAction` based on `isHovered`, we pass `containerStyles` to `IOUPreview` -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/ReportActionItem/MoneyRequestAction.js#L142-L153

We do pass `isHovered` too in line 152 but that is used in `IOUPreview` only for `MultipleAvatars` component styling which is not used in `ReportPreview` so we don't need `isHovered` in `ReportPreview`.

<details>
<summary>
I noticed one more margin issue in `ReportPreview`. See screenshot -
</summary>

Notice that there is margin before image and before `IOUPreview` in chat but for `ReportPreview` (last message) there is no margin and it is right below the user name.
<img width="730" alt="Screenshot 2023-07-10 at 9 03 00 PM" src="https://github.com/Expensify/App/assets/31413407/c17c731d-e3ac-406e-bee1-af41fc52c1b0">

To fix this, we can either also pass `styles.mt2` in `containerStyles` from `ReportActionItem` or we can directly use `styles.mt2` in `ReportPreview` which are also used for image and `IOUPreview`.

</details>

### What alternative solutions did you explore? (Optional)
Alternatively, we can pass `isHovered` to `ReportPreview` and then based on it we can add hover background styles in `ReportPreview` itself.

Result -

https://github.com/Expensify/App/assets/31413407/dcc23bc7-0021-400f-b1a3-1ad4a0ea25bb

**Comment by Nikhil-Vats** [comment] 2023-07-10 18:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money ReportPreview's background color does not change on hover.

### What is the root cause of that problem?
When we are rendering `ReportPreview` in `ReportActionItem`, we pass `isHovered` prop -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/pages/home/report/ReportActionItem.js#L247-L254

But there is no such prop in `ReportPreview` so we don't add hover background color based on the hover state.
### What changes do you think we should make in order to solve the problem?
There is no use of `isHovered` prop in `ReportPreview` so we don't need to pass it, instead we should add a new prop `containerStyles` in `ReportPreview` and based on `hover` state in `ReportActionItem`, we should add hover background color -

```javascript
<ReportPreview
    iouReportID={ReportActionsUtils.getIOUReportIDFromReportActionPreview(props.action)}
    chatReportID={props.report.reportID}
    action={props.action}
    containerStyles={[hovered ? styles.iouPreviewBoxHover : undefined]}
    contextMenuAnchor={popoverAnchorRef}
    checkIfContextMenuActive={toggleContextMenuFromActiveReportAction}
/>
```

Then in `ReportPreview`, we need to change line 109 to use new `containerStyles` prop -
```javascript
<View style={[styles.iouPreviewBox, ...props.containerStyles]}>
```

P.S. - We can also keep the type of `containerStyles` prop as an object rather than an array.

This is consistent with what we are doing for `IOUPreview`. In `ReportActionItem`, we render `MoneyRequestAction` and pass it `isHovered` prop, and in `MoneyRequestAction` based on `isHovered`, we pass `containerStyles` to `IOUPreview` -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/ReportActionItem/MoneyRequestAction.js#L142-L153

We do pass `isHovered` too in line 152 but that is used in `IOUPreview` only for `MultipleAvatars` component styling which is not used in `ReportPreview` so we don't need `isHovered` in `ReportPreview`.

<details>
<summary>
I noticed one more margin issue in `ReportPreview`. See screenshot -
</summary>

Notice that there is margin before image and before `IOUPreview` in chat but for `ReportPreview` (last message) there is no margin and it is right below the user name.
<img width="730" alt="Screenshot 2023-07-10 at 9 03 00 PM" src="https://github.com/Expensify/App/assets/31413407/c17c731d-e3ac-406e-bee1-af41fc52c1b0">

To fix this, we can either also pass `styles.mt2` in `containerStyles` from `ReportActionItem` or we can directly use `styles.mt2` in `ReportPreview` which are also used for image and `IOUPreview`.

</details>

### What alternative solutions did you explore? (Optional)
Alternatively, we can pass `isHovered` to `ReportPreview` and then based on it we can add hover background styles in `ReportPreview` itself.

Result -

https://github.com/Expensify/App/assets/31413407/dcc23bc7-0021-400f-b1a3-1ad4a0ea25bb

**Comment by Nikhil-Vats** [comment] 2023-07-10 18:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request Money ReportPreview's background color does not change on hover.

### What is the root cause of that problem?
When we are rendering `ReportPreview` in `ReportActionItem`, we pass `isHovered` prop -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/pages/home/report/ReportActionItem.js#L247-L254

But there is no such prop in `ReportPreview` so we don't add hover background color based on the hover state.
### What changes do you think we should make in order to solve the problem?
There is no use of `isHovered` prop in `ReportPreview` so we don't need to pass it, instead we should add a new prop `containerStyles` in `ReportPreview` and based on `hover` state in `ReportActionItem`, we should add hover background color -

```javascript
<ReportPreview
    iouReportID={ReportActionsUtils.getIOUReportIDFromReportActionPreview(props.action)}
    chatReportID={props.report.reportID}
    action={props.action}
    containerStyles={[hovered ? styles.iouPreviewBoxHover : undefined]}
    contextMenuAnchor={popoverAnchorRef}
    checkIfContextMenuActive={toggleContextMenuFromActiveReportAction}
/>
```

Then in `ReportPreview`, we need to change line 109 to use new `containerStyles` prop -
```javascript
<View style={[styles.iouPreviewBox, ...props.containerStyles]}>
```

P.S. - We can also keep the type of `containerStyles` prop as an object rather than an array.

This is consistent with what we are doing for `IOUPreview`. In `ReportActionItem`, we render `MoneyRequestAction` and pass it `isHovered` prop, and in `MoneyRequestAction` based on `isHovered`, we pass `containerStyles` to `IOUPreview` -
https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/ReportActionItem/MoneyRequestAction.js#L142-L153

We do pass `isHovered` too in line 152 but that is used in `IOUPreview` only for `MultipleAvatars` component styling which is not used in `ReportPreview` so we don't need `isHovered` in `ReportPreview`.

<details>
<summary>
I noticed one more margin issue in `ReportPreview`. See screenshot -
</summary>

Notice that there is margin before image and before `IOUPreview` in chat but for `ReportPreview` (last message) there is no margin and it is right below the user name.
<img width="730" alt="Screenshot 2023-07-10 at 9 03 00 PM" src="https://github.com/Expensify/App/assets/31413407/c17c731d-e3ac-406e-bee1-af41fc52c1b0">

To fix this, we can either also pass `styles.mt2` in `containerStyles` from `ReportActionItem` or we can directly use `styles.mt2` in `ReportPreview` which are also used for image and `IOUPreview`.

</details>

### What alternative solutions did you explore? (Optional)
Alternatively, we can pass `isHovered` to `ReportPreview` and then based on it we can add hover background styles in `ReportPreview` itself.

Result -

https://github.com/Expensify/App/assets/31413407/dcc23bc7-0021-400f-b1a3-1ad4a0ea25bb

**Comment by jayeshmangwani** [comment] 2023-07-12 10:20
This issue was solved yesterday in this [PR](https://github.com/Expensify/App/pull/22626); we can close this issue

**Comment by jayeshmangwani** [comment] 2023-07-12 10:20
@kevinksullivan This issue was solved yesterday in this PR; we can close this issue

**Closed** 2023-07-12 22:16 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by jayeshmangwani** [comment] 2023-07-13 06:58
@kevinksullivan Can you please confirm if I am eligible for reporting bonus here, the issue was reported before the PR created

**Comment by kevinksullivan** [comment] 2023-07-13 21:32
If the issue was solved elsewhere then we don't pay reporting bonus

**Comment by jayeshmangwani** [comment] 2023-07-13 21:41
Yes, I understand that, but I was confirming because this issue was created before this [issue](https://github.com/Expensify/App/issues/22625) which solves that current issue in this [PR](https://github.com/Expensify/App/pull/22626). Thanks!
