### ISSUE TITLE
[$500] Chat - Focus is lost when start chat with the Secondary login of the account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34775] opened 2024-01-19 00:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app.
2. Log in with the account that has the conversation with the user that has 2 logins
3. Click on FAB
4. Click on New Chat
5. Search for the Secondary login of the account
6. Verify you're redirected to the conversation with the primary login email

## Expected Result:
Focus is not lost when start chat with the Secondary login of the account after redirection to the conversation with the primary login email

## Actual Result:
Focus is lost when start chat with the Secondary login of the account after redirection to the conversation with the primary login email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b5e099e5-2d7b-4788-9eab-a4e76add4e84

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-19 00:40
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by bfitzexpensify** [comment] 2024-01-19 22:44
>I believe though the experience is a bid off here as it loads one chat and then switches to another one, which is confusing. Ideally we would go straight to the correct report without the confusing transition.

I think this makes sense since. For it to go immediately to the other chat might be confusing if you didn't know there was a primary login - that would feel like it had just gone to the wrong chat. The 'journey' of being sent to a chat with the contact details that the user has entered for it to then go to the 'correct' chat feel correct. I think the performance of that generally (I.e. how long it takes) could be improved, but that's a general performance issue, rather than a specific behaviour we need to change. 

Given the focus behaviour is also working as intended, I'm going to close this out.

**Closed by bfitzexpensify** 2024-01-19 22:44 UTC
Labels: External, Daily, Help Wanted, Bug
