### ISSUE TITLE
mWeb - Expense - Renamed the report system message is shown incorrectly.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53820] opened 2024-12-10 09:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a workspace chat
3. Create a expense
4. Open the expense

## Expected Result:
Renamed the report system message must not be shown.

## Actual Result:
Renamed the report system message is shown incorrectly.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b96ac34b-bf14-4b05-95db-8a309b479f38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-12-10 09:33
Production 

https://github.com/user-attachments/assets/5766d058-1ec8-4885-8da5-8e3bee848e68

**Comment by jliexpensify** [comment] 2024-12-10 09:44
@IuliiaHerets is this an actual Deploy Blocker, or did you accidentally use the label?

**Comment by IuliiaHerets** [comment] 2024-12-10 13:22
@jliexpensify No, I added the label on purpose. Issue was reproduced in stg and prod with staging server off, issue was not repro with SS on.
QA team can still repro this issue 

https://github.com/user-attachments/assets/0b23eb7c-ab35-44c3-bead-0080938c7107

**Comment by jliexpensify** [comment] 2024-12-10 23:38
Clarifying if this is a true deploy blocker [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1733873898035659?thread_ts=1733869850.465989&cid=C01SKUP7QR0)

**Comment by jliexpensify** [comment] 2024-12-10 23:46
Hi @francoisl - Applause seems to think this is a deploy blocker, but I don't think it is (and I can't repro). Puneet advised applying both labels [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1733872623898149?thread_ts=1733869850.465989&cid=C01SKUP7QR0).

**Comment by francoisl** [comment] 2024-12-11 00:16
I can repro on Web on staging, looking now. Not sure if it's a backend or NewDot blocker yet, let's keep both labels for now.

**Comment by francoisl** [comment] 2024-12-11 00:27
This is a backend bug caused by https://github.com/Expensify/Web-Expensify/pull/44662/, removing the NewDot blocker label.

**Comment by deetergp** [comment] 2024-12-11 18:09
I think the revert of https://github.com/Expensify/Web-Expensify/pull/44662 worked and we're good to remove the blocker label.

https://github.com/user-attachments/assets/da7db0e1-480d-451d-8cb4-b53a0fc97e2d

**Comment by deetergp** [comment] 2024-12-11 18:10
Asked Applause for a retest here https://expensify.slack.com/archives/C9YU7BX5M/p1733940322271419?thread_ts=1733940210.713079&cid=C9YU7BX5M

**Comment by francoisl** [comment] 2024-12-11 18:12
We cherry-picked a backend fix https://github.com/Expensify/Web-Expensify/pull/44733. Both Scott and I confirmed the regression is no longer on staging, removing the blocker label.

**Comment by mvtglobally** [comment] 2024-12-12 14:28
Not reproducible https://github.com/user-attachments/assets/6abac4a3-59a5-4641-b3b5-017a2f02a20c

**Comment by jliexpensify** [comment] 2024-12-12 23:13
Awesome, are we good to close this @francoisl @deetergp ?

**Comment by deetergp** [comment] 2024-12-13 22:33
Looks that way @jliexpensify. Closing!

**Closed by deetergp** 2024-12-13 22:33 UTC
Labels: Reviewing, Engineering, Daily, Bug
