### ISSUE TITLE
[$2000] Android app - Navigating to conversation via link twitches current chat left and right

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19914] opened 2023-05-31 23:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Using Android m/Web, login to NewDot with account  A and open any DM. Copy the report url from the address bar (like https://staging.new.expensify.com/r/1242891003534332)
2. Paste it in any external app (Slack or Telegram)
3. Log in with same account (account A) in android app
4. In the android app, open any other chat (not the one you opened in step 1)
5. Go back to the external app and tap link you pasted in external app
6. Observe the chat twitching left and right

## Expected Result:
Chat from step should be opened without any visual issues.

## Actual Result:
Current chat (from step 3) twitches left and right before opening required chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.21.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba68bc5b-bfd7-4765-a761-a60204695ab5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107d17ae1d8678cbc</li>
        <li>Upwork Job ID: 1664398864826523648</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-01 18:41
I need some clarification on the steps in the OP - in my testing, I'm getting this screen after copying the chat link from an external source. 

![image](https://github.com/Expensify/App/assets/51066321/959ee107-58cc-4e8a-bf08-516d908245b7)

**Comment by Christinadobrzyn** [comment] 2023-06-01 19:41
Browserstack doesn't have any external app that meets the "Slack or Telegram" step so I can't test this. Asking if anyone with an Android could grab this - https://expensify.slack.com/archives/C01SKUP7QR0/p1685648330412259

**Comment by strepanier03** [comment] 2023-06-01 21:08
I was able to test and recreate this using a Google Pixel 6 Pro. I updated the repro steps to make them a little more clear as well. This is good to move forward I think @Christinadobrzyn.

**Comment by Christinadobrzyn** [comment] 2023-06-01 22:29
TY @strepanier03! 

I can't find any other GHs related to this - adding the external label.

**Comment by Christinadobrzyn** [comment] 2023-06-05 17:51
not overdue - collecting proposals

**Comment by Christinadobrzyn** [comment] 2023-06-07 20:45
waiting on proposals

**Comment by Christinadobrzyn** [comment] 2023-06-12 18:14
Thanks @WikusKriek - Asking QA to test this again. https://expensify.slack.com/archives/C9YU7BX5M/p1686593669248009

**Comment by DanutGavrus** [comment] 2023-06-13 10:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating to conversation via link does not open the new chat if one is already opened.

### What is the root cause of that problem?
This is what happens now if the app is opened in background and we try to open a chat from a deep link:
1) In `Expensify.js` we call `Linking.addEventListener('url', (state) => Report.openReportFromDeepLink(state.url, isAuthenticated));`;
2) In `Report.js` we call `Navigation.navigate(ROUTES.getReportRoute(reportID));`;
3) In `Navigation.js` we call `linkTo(navigationRef.current, route, type);`;
4) In `linkTo.js` we call:
```
if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && getTopmostReportId(root.getState()) !== getTopmostReportId(state)) {
            action.type = 'PUSH';
```
##### Now, here is the problem  
Both `getTopmostReportId(root.getState())` and `getTopmostReportId(state)` return the __same report id__, so we never set `action.type = 'PUSH'`, so we never navigate to the new route.  
##### Why does this happen?  
`getTopmostReportId(state)` returns the reportId from the URL, which is the new report ID where we need to navigate to. But, when coming from a deep link, the `NavigationContainer` has the _new state inserted automatically_ as this is it's default behavior(one may check this as `onStateChange` callback is automatically triggered when the app gets reopened from the deep link).

I think this is also what happens in [20624](https://github.com/Expensify/App/issues/20624).

### What changes do you think we should make in order to solve the problem?
1) As everything starts from `openReportFromDeepLink`, we may pass an optional parameter set to false by default, in order to let `linkTo` know when we come from a deep link.
2) We know `getTopmostReportId(root.getState())` will return the same reportId when coming from a deep link, so we need another way to get the last visible reportId. I have some options in mind such as:
2.1. Either, when `onStateChange` gets called, in `updateSavedNavigationStateAndLogRoute` we may also save the `previousState`;
2.2. Or, add an event listener for when app goes to background on native, same as we already have the one from when it comes back active. Inside it, save `lastReportId` which is going to be the current opened report id if any, or null/undefined otherwise.
2.3 I may think of other ways to get the topmost report id inside `linkTo` if previous 2 versions are not the best, let me know.
3) Now, inside `linkTo`, we may update the `if`, such that when coming from a deep link, will use another way to get the topmost report id instead of `getTopmostReportId(root.getState())`.

### What alternative solutions did you explore?
If we don't want to add and pass a new parameter when coming from a deep link, we may completely move from using `getTopmostReportId(root.getState())` to always saving a report id in a context when opening a report, and resetting it when closing one, which will be used here. `linkTo.js` would look like:
```
if (action.payload.name === NAVIGATORS.CENTRAL_PANE_NAVIGATOR && topmostReportId !== getTopmostReportId(state)) {
            action.type = 'PUSH';
```

**Comment by Christinadobrzyn** [comment] 2023-06-13 20:56
Looks like this issue can no longer be reproduced by QA this issue exists - https://github.com/Expensify/App/issues/20624

Closing this without action.

**Closed by Christinadobrzyn** 2023-06-13 20:56 UTC
Labels: External, Daily, Help Wanted, Bug
