### ISSUE TITLE
[$250] Profile - After the user's address is saved, Address Line 2 is added to Address Line 1

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45765] opened 2024-07-19 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4738169
**Email or phone of affected tester (no customers):** applausetester+071824dr032@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Login with any account
3. Go to Settings > Profile > Private > Address
4. Add any address in Address Line 1, Line 2 and in other fields
5. Save address
6. Open saved address

## Expected Result:
All address fields are saved correctly

## Actual Result:
Contents of Address Line 2 was added to the end of Address Line 1. Field "Address Line 2" is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0cd75c38-e92e-44b3-8f36-5d504f9a45c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015086577f7d57dabf</li>
        <li>Upwork Job ID: 1817941170058231435</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103594215</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-19 12:25
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-19 12:25
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-07-19 12:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - After the user's address is saved, Address Line 2 is added to Address Line 1
### What is the root cause of that problem?
We are saving both street and street2 in `street` separating with new line
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/libs/PersonalDetailsUtils.ts#L214-L215
But we are not extracting street2 properly here
https://github.com/Expensify/App/blob/b8b99d0a994e3ccf8b91564df0f92a7c440aa6c7/src/pages/AddressPage.tsx#L31-L32

### What changes do you think we should make in order to solve the problem?

We can start saving them separately by creating `street2` prop `privatePersonalDetails?.address` and then we can displaying them easily by accessing the props 
or we can also extract the street2 by assigning the string after newline to street2 like
```
const {street: bothStreets} = address ?? {};
    const streetArr = bothStreets?.split('/n');
    const street = bothStreets?.split('/n')?.[0];
    const street2 = bothStreets?.split('/n')[1];
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-19 12:49
[Updated](https://github.com/Expensify/App/issues/45765#issuecomment-2239049642) to fix a typo `\n` to `/n`

**Comment by JmillsExpensify** [comment] 2024-07-29 15:11
Adding this to wave-collect since it's about private addresses, which is used for the bank/reimbursement flow. I'm also opening up to the community.

**Comment by marcochavezf** [comment] 2024-08-06 00:30
Hi, I'm still analyzing the backend API, seems it expects the street data in one field, but I will confirm tomorrow

**Comment by marcochavezf** [comment] 2024-08-07 00:42
Sorry, no update. I got caught up with some other priorities today

**Comment by trjExpensify** [comment] 2024-08-08 14:52
As we move new sign-ups into NewDot and release the Expensify Card project in the coming weeks, fixing this bug in setting a private address is going to be more visible and troublesome. Moving it up into high value polish for September.

**Comment by marcochavezf** [comment] 2024-08-12 18:42
Checking it out today again

**Comment by trjExpensify** [comment] 2024-08-15 00:43
Did you check it out, @marcochavezf?

**Comment by marcochavezf** [comment] 2024-08-15 21:35
Hi @thesahindia, I verified we're intentionally appending these values in the backend into one field, so let's handle the split in the frontend

**Comment by marcochavezf** [comment] 2024-08-19 21:46
I agree with @thesahindia's decision, assigning @nyomanjyotisa

**Comment by marcochavezf** [comment] 2024-08-23 14:22
Not overdue, [PR](https://github.com/Expensify/App/pull/47709) is WIP

**Comment by JmillsExpensify** [comment] 2024-10-02 17:23
Payment summary: 

 - Contributor: $250 @nyomanjyotisa 
 - Reviewer: $250 @thesahindia

**Comment by garrettmknight** [comment] 2024-10-08 18:26
$250 approved for @thesahindia

**Comment by JmillsExpensify** [comment] 2024-10-09 17:45
All contributors paid out, so closing.

**Closed by JmillsExpensify** 2024-10-09 17:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
