### ISSUE TITLE
[HOLD for payment 2024-05-03] [$250] [Search v1] Rename Search page to Chat Finder

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39885] opened 2024-04-09 00:22 UTC
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.l7zs7ubp0bp8)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e0d8316fc2a903a</li>
        <li>Upwork Job ID: 1780007703811551232</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2024-04-15 22:37
@adamgrzybowski @WojtekBoman could you please comment on this issue so I can get it assigned to you

**Comment by alitoshmatov** [comment] 2024-04-15 22:45
@luacmartins Can you grant access to me to the doc

**Comment by luacmartins** [comment] 2024-04-17 15:25
@Expensify/marketing could you take a look at this one? We're introducing a new search page, so the current search page will need to be renamed. I suggested to use `Find`, but would love your opinion. For reference, this is the page

![322549716-5a542893-c493-4213-8420-c3f80f8cdafd](https://github.com/Expensify/App/assets/22219519/98d454f4-2098-4755-8ff2-2ef9b61fc46b)

**Comment by luacmartins** [comment] 2024-04-17 15:26
@NickTooker could you please take a look at [this comment](https://github.com/Expensify/App/issues/39885#issuecomment-2061540861) and let me know the new name we wanna use for that header?

**Comment by luacmartins** [comment] 2024-04-22 15:04
Bump @NickTooker

**Comment by jamesdeanexpensify** [comment] 2024-04-22 18:51
I mentioned this elsewhere, but do you mind bringing this up for discussion in #marketing? It feels like a slightly bigger change that we should all ensure we're aligned on.

**Comment by luacmartins** [comment] 2024-04-22 21:08
Cool, we decided to go with `Find`

**Comment by lschurr** [comment] 2024-05-02 21:54
Looks like we won't actually need any payments on this one. I'll close tomorrow to wait out the regression period anyway.

**Comment by lschurr** [comment] 2024-05-03 15:21
Closing this one out :)

**Comment by alitoshmatov** [comment] 2024-05-05 17:45
@lschurr I require a payment here since I reviewed https://github.com/Expensify/App/pull/40728 PR

**Comment by lschurr** [comment] 2024-05-06 16:07
Sorry about that @alitoshmatov - I just sent the offer here: https://www.upwork.com/nx/wm/offer/102187135

**Comment by lschurr** [comment] 2024-05-06 16:14
Great, all set!

**Closed by lschurr** 2024-05-06 16:14 UTC
Labels: External, Weekly, NewFeature, Awaiting Payment
