### ISSUE TITLE
IOU - Billable no longer valid violation is not displayed under the field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36481] opened 2024-02-14 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312606
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: as an employee of a workspace, create an expense with Billable option toggled on.
1. As the admin of the workspace on OD, set "Re-bill expenses to clients" to Disabled.
2. As the employee on ND, go to the details page of the created expense.

## Expected Result:
Billable no longer valid violation should be displayed under the field.

## Actual Result:
Billable no longer valid violation is displayed on the right side and the toggle button is moved to the middle.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/e43e4aa9-fb29-49cf-8c8c-aaa735ba0d68)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-14 14:13
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by pecanoro** [comment] 2024-02-14 16:44
@kbecciv On production, does it show under the button or it doesn't show at all?

**Comment by amyevans** [comment] 2024-02-14 16:47
@cead22 @trevor-coleman is this an expected change?

**Comment by trevor-coleman** [comment] 2024-02-14 16:57
No it should be underneath. Moving it outside that view should fix it.

**Comment by amyevans** [comment] 2024-02-14 17:07
@trevor-coleman Got it, thanks! could you open a PR to fix please?

**Comment by pecanoro** [comment] 2024-02-14 17:13
I need to check if this a regression for a PR or it was introduced by a new feature

**Comment by amyevans** [comment] 2024-02-14 17:17
@pecanoro it's from https://github.com/Expensify/App/pull/34303

**Comment by pecanoro** [comment] 2024-02-14 17:46
@amyevans Thank you! So it was a regression from that PR. As she mentioned, @trevor-coleman can you fix it since it was your PR or should we find a volunteer?

**Comment by pecanoro** [comment] 2024-02-14 17:49
@trevor-coleman Cool, thank you so much!

**Comment by trevor-coleman** [comment] 2024-02-14 18:24
Because of the difference between web and native, just moving the messages below wasn't working, so I ended up leaving the violation messages where they are adding override props to the container and text styles that let me put them where they needed to be.

Android:
![CleanShot 2024-02-14 at 13 24 30@2x](https://github.com/Expensify/App/assets/22041394/c59d9178-789a-47e5-89d6-fcf057674666)

Web:
![CleanShot 2024-02-14 at 13 24 51@2x](https://github.com/Expensify/App/assets/22041394/3df3860e-941f-48d6-be06-528ad539bc22)

**Comment by trevor-coleman** [comment] 2024-02-14 18:47
ok PR is complete: https://github.com/Expensify/App/pull/36533

**Comment by pecanoro** [comment] 2024-02-14 22:04
Either way, since it's just visual and it does not break things completely, I am going to remove the deploy blocker and we can merge it tomorrow. @cead22 Do you agree?

**Comment by pecanoro** [comment] 2024-02-29 15:22
Issue for payment created, gonna closed this one

**Closed by pecanoro** 2024-02-29 15:22 UTC
Labels: Reviewing, Engineering, Weekly
