### ISSUE TITLE
Sign in – Blank page opens when login via magic link and click on Just sign in here

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47053] opened 2024-08-08 10:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4834115
**Email or phone of affected tester (no customers):** applausetester+jp_48824@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Sign in page enter new Expensify email
3. Open email and copy Magic link
4. In Incognito tab navigate via Magic link changed to staging
5. Click on Just sign in here link

## Expected Result:
User is logged in

## Actual Result:
Blank page opens

## Workaround:
Anknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/09859e5b-a53e-4622-98f4-078de4bf7e63

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-08 10:18
We think that this bug might be related to #vip-vsb

**Comment by danieldoglas** [comment] 2024-08-08 11:30
@iwiznia and I were not able to simulate this error.

@IuliiaHerets can you please retest this and rewrite the reproduction steps if you can still see it happening?

Thanks

**Comment by dangrous** [comment] 2024-08-08 13:15
if this turns out to be a bug it might be due to https://github.com/Expensify/App/pull/46623 since seems related?

**Comment by danieldoglas** [comment] 2024-08-21 19:05
Closing this. We were not able to simulate, and this flow is being worked on another issues already.

**Closed by danieldoglas** 2024-08-21 19:05 UTC
Labels: Engineering, Weekly, Overdue, Bug
