### ISSUE TITLE
[HOLD for payment 2023-11-02] [$2000] IOU : Inconsistent behavior when long pressing the back button in Android app vs mWeb 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23300] opened 2023-07-20 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB on Chrome mobile
2. Click Reqeust Money/ Split Bill
3. Enter amount more than 3 digits (e.g 6323)
4. Hold the back key "<"

## Expected Result: 
Last digit is removed and cursor is still at last place like Android app
## Actual Result: 
Last digit is removed but cursor is in front of last character

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/97e50faa-fe0e-485e-aa9f-055266662742

https://github.com/Expensify/App/assets/43996225/dd064c2c-a3ff-4e05-a436-854e29cbe978

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ygshbht
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689740152146159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186b5465f1e6964a7</li>
        <li>Upwork Job ID: 1684547845836894208</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27293534</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-20 19:15
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Inconsistent cursor behavior when a user long-presses the back button on the 'Split Bill/Request Money' page between Android app and mobile web.
### What is the root cause of that problem?
React's state management involves batching state updates for performance optimization, and in the current implementation, the `setSelection `function in `setNewAmount `  (`MoneyRequestAmountPage `component) function seems to be getting called more than once. This leads to unpredictable cursor behavior due to the asynchronous nature of state updates in React.
### What changes do you think we should make in order to solve the problem?
The solution focuses on preventing multiple invocations of `setSelection `within `setAmount`. We introduce a flag `hasSelectionBeenSet `that allows `setSelection `to be called only once, thereby aligning cursor behavior across different platforms.
Original code block:
```
const setNewAmount = (newAmount) => {
    const newAmountWithoutSpaces = stripSpacesFromAmount(newAmount);
    if (!validateAmount(newAmountWithoutSpaces)) {
        setAmount((prevAmount) => prevAmount);
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
    setAmount((prevAmount) => {
        setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length));
        return stripCommaFromAmount(newAmountWithoutSpaces);
    });
};
```
Modified code block:
```
const setNewAmount = (newAmount) => {
    const newAmountWithoutSpaces = stripSpacesFromAmount(newAmount);
    if (!validateAmount(newAmountWithoutSpaces)) {
        setAmount((prevAmount) => prevAmount);
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
    let hasSelectionBeenSet = false;
    setAmount((prevAmount) => {
        if (!hasSelectionBeenSet) {
            setSelection((prevSelection) => {
                hasSelectionBeenSet = true;
                return getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length);
            });
        }
        return stripCommaFromAmount(newAmountWithoutSpaces);
    });
};

**Comment by ygshbht** [comment] 2023-07-20 19:56
Thanks Kavi. 
___
To add more details
https://github.com/Expensify/App/blob/df6d03bef398d101a7340351603b937a4b23b59f/src/pages/iou/steps/MoneyRequestAmountPage.js#L291-L306

Working solution:
https://github.com/Expensify/App/assets/65986357/a50b6971-39c7-44eb-bece-6b2ffde67114

**Comment by ygshbht** [comment] 2023-07-23 12:55
### Regarding the alternate solution: 
You could also club amount and selection in one state variable as they are almost always updated together
So the new modification instead of this
```
let hasSelectionBeenSet = false;
setAmount((prevAmount) => {
    if (!hasSelectionBeenSet) {
        setSelection((prevSelection) => {
            hasSelectionBeenSet = true;
            return getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length);
        });
    }
    return stripCommaFromAmount(newAmountWithoutSpaces);
});
```
can be:
```
setAmountAndSelection(({amount, selection})=>{
    return { amount:stripCommaFromAmount(newAmountWithoutSpaces),
        selection: getNewSelection(selection, amount.length, newAmountWithoutSpaces.length)
    }
})
```

**Comment by michaelhaxhiu** [comment] 2023-07-27 12:55
Passing to `External`

**Comment by michaelhaxhiu** [comment] 2023-08-02 21:16
How's review coming @abdulrahuman5196 🐰 ?

**Comment by abdulrahuman5196** [comment] 2023-08-03 16:41
Will check in my morning. Was working on WAQ crossed issues and deploy blockers.

**Comment by ygshbht** [comment] 2023-08-04 15:53
Hi, I am open to any questions or clarifications on my proposal https://github.com/Expensify/App/issues/23300#issuecomment-1644464026 or alternative solutions https://github.com/Expensify/App/issues/23300#issuecomment-1646833780 or any discussion @abdulrahuman5196 @michaelhaxhiu  @garrettmknight

**Comment by abdulrahuman5196** [comment] 2023-08-06 19:07
@ygshbht I am unable to understand the root cause provided on the proposal - https://github.com/Expensify/App/issues/23300#issuecomment-1644464026

>React's state management involves batching state updates for performance optimization, and in the current implementation, the setSelection function in setNewAmount (MoneyRequestAmountPage component) function seems to be getting called more than once. This leads to unpredictable cursor behavior due to the asynchronous nature of state updates in React.

>React's state management involves batching state updates for performance optimization

Can you provide information on this?

> the setSelection function in setNewAmount (MoneyRequestAmountPage component) function seems to be getting called more than once

Why does calling this function more than once causes inconsistency? Why this function should be called only one?


Not just the above questions. Could you kindly provide more clear and rigid information on root cause?


And kindly have all the information in one proposal comment(this is also the proposal guidelines.). Post a proposal comment here and add all your information to the same.

**Comment by ygshbht** [comment] 2023-08-06 20:13
@abdulrahuman5196 

> And kindly have all the information in one proposal comment(this is also the proposal guidelines.). Post a proposal comment here and add all your information to the same.

I can't modify the proposal as it is written by kavimuru, however i have merged the following 2 comments into one. 


> Why does calling this function more than once causes inconsistency? Why this function should be called only one?

https://github.com/Expensify/App/blob/1c8f9353f1d3d4a14c0e9c23a5f5299aec36f17f/src/pages/iou/steps/MoneyRequestAmountForm.js#L134-L137

https://github.com/Expensify/App/blob/1c8f9353f1d3d4a14c0e9c23a5f5299aec36f17f/src/pages/iou/steps/MoneyRequestAmountForm.js#L51-L54


In the context of pressing the back button, calling `setSelection `is designed to adjust the cursor's position based on the current change. Specifically, the `getNewSelection `function will move the cursor back by one step, which is the expected behavior. However, due to the current arrangement in the code, `setSelection `gets invoked twice in quick succession. **This results in the cursor's position being adjusted twice, effectively moving it back by two steps instead of one. This unintended double adjustment is causing the inconsistency in cursor position that we are observing.**

> Not just the above questions. Could you kindly provide more clear and rigid information on root cause?

In our original implementation, we had a nested state update. Specifically, inside our `setAmount `state update, we were calling another state update function, `setSelection`. This is problematic due to the asynchronous nature of React's state updates.

When we call `setAmount`, it schedules a state update. Before this update is processed and the component is re-rendered, we're also calling `setSelection`, effectively scheduling another state update. Given that these updates are asynchronous, the exact timing and sequence of their processing can overlap or vary. This can lead to unexpected behaviors, such as our `setSelection `being invoked multiple times in quick succession.

In the context of our application, this meant that the cursor's position was being adjusted more than once, leading to the inconsistency observed.

The solution, as demonstrated in the modified code, was to introduce a mechanism (`hasSelectionBeenSet `flag) to ensure that `setSelection `is invoked only once per change, avoiding the complications introduced by the nested state updates.

https://github.com/facebook/react/issues/8132#issuecomment-257088287
https://github.com/facebook/react/issues/8132#issuecomment-334169842

**Comment by s-alves10** [comment] 2023-08-07 02:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsisten behavior when long pressing the back button in Android app and mWeb

### What is the root cause of that problem?

In strict mode, React will call the updater function twice instead of once. If the updater function is pure, this shouldn't affect your logic. This is a behavior for development and helps us avoid accident impure updaters. Please refer https://react.dev/reference/react/useState#my-initializer-or-updater-function-runs-twice

Please check the below code
https://github.com/Expensify/App/blob/21146e534492fc21811b5bac0718e0f1e8ffbfd4/src/pages/iou/steps/MoneyRequestAmountForm.js#L134-L137

As you can see, our updater function(for `setCurrentAmount`) isn't pure. It calls other state updater(`setSelection`) in it. So twice calling the updater function would have unexpected effect to the component.

This is the root cause of this issue

### What changes do you think we should make in order to solve the problem?

We need to make the updater function pure or pass the next state directly

```
        setSelection(getNewSelection(selection, currentAmount.length, newAmountWithoutSpaces.length));
        setCurrentAmount(MoneyRequestUtils.stripCommaFromAmount(newAmountWithoutSpaces));
```

or

```
        setSelection((prevSelection) => getNewSelection(prevSelection, currentAmount.length, newAmountWithoutSpaces.length));
        setCurrentAmount(MoneyRequestUtils.stripCommaFromAmount(newAmountWithoutSpaces));
```

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:35
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:52
@ygshbht I tried out this https://github.com/Expensify/App/issues/23300#issuecomment-1644464026 solution and its causing issues for me 


https://github.com/Expensify/App/assets/46707890/b1d17bed-cff6-4b2b-9443-9ecf6ac1b98b


Can you put all your proposal in a single comment as per the guideline? You can submit a new proposal comment in your name with all the information

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:58
On @s-alves10 's proposal here https://github.com/Expensify/App/issues/23300#issuecomment-1667075869
I don't think we directly convert the functions as mentioned in the proposed changes. I think the prevSelection have some role to play in the cursor position computation. If we change as per the proposal it is causing the below issue.


https://github.com/Expensify/App/assets/46707890/a2e2209f-d3b9-42f1-bed1-21891040a465

**Comment by abdulrahuman5196** [comment] 2023-08-13 14:58
@garrettmknight Currently we don't have any working proposal

**Comment by ygshbht** [comment] 2023-08-13 15:15
Original Proposal: 
https://github.com/Expensify/App/issues/23300#issuecomment-1644464026
https://github.com/Expensify/App/issues/23300#issuecomment-1644517120
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Inconsistent cursor behavior when a user long-presses the back button on the 'Split Bill/Request Money' page between Android app and mobile web.

### What is the root cause of that problem?
React's state management involves batching state updates for performance optimization, and in the current implementation, the `setSelection `function in `setNewAmount ` (`MoneyRequestAmountPage `component) function seems to be getting called more than once. This leads to unpredictable cursor behavior due to the asynchronous nature of state updates in React.

### What changes do you think we should make in order to solve the problem?
The solution focuses on preventing multiple invocations of `setSelection `within `setAmount`. We introduce a flag `hasSelectionBeenSet `that allows `setSelection `to be called only once, thereby aligning cursor behavior across different platforms. Original code block:

```
const setNewAmount = (newAmount) => {
    const newAmountWithoutSpaces = stripSpacesFromAmount(newAmount);
    if (!validateAmount(newAmountWithoutSpaces)) {
        setAmount((prevAmount) => prevAmount);
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
    setAmount((prevAmount) => {
        setSelection((prevSelection) => getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length));
        return stripCommaFromAmount(newAmountWithoutSpaces);
    });
};
```

Modified code block:

```
const setNewAmount = (newAmount) => {
    const newAmountWithoutSpaces = stripSpacesFromAmount(newAmount);
    if (!validateAmount(newAmountWithoutSpaces)) {
        setAmount((prevAmount) => prevAmount);
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
    let hasSelectionBeenSet = false;
    setAmount((prevAmount) => {
        if (!hasSelectionBeenSet) {
            setSelection((prevSelection) => {
                hasSelectionBeenSet = true;
                return getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length);
            });
        }
        return stripCommaFromAmount(newAmountWithoutSpaces);
    });
};
```
___
To add more details
https://github.com/Expensify/App/blob/df6d03bef398d101a7340351603b937a4b23b59f/src/pages/iou/steps/MoneyRequestAmountPage.js#L291-L306

### What alternative solutions did you explore? (Optional)
A bit more complex solution involves moving **setSelection** out of **setAmount** and doing some restructuring to acheive the same result

Working solution:

https://github.com/Expensify/App/assets/65986357/a50b6971-39c7-44eb-bece-6b2ffde67114

<hr/>

### Regarding the alternate solution: 
You could also club amount and selection in one state variable as they are almost always updated together
So the new modification instead of this
```
let hasSelectionBeenSet = false;
setAmount((prevAmount) => {
    if (!hasSelectionBeenSet) {
        setSelection((prevSelection) => {
            hasSelectionBeenSet = true;
            return getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length);
        });
    }
    return stripCommaFromAmount(newAmountWithoutSpaces);
});
```
can be:
```
setAmountAndSelection(({amount, selection})=>{
    return { amount:stripCommaFromAmount(newAmountWithoutSpaces),
        selection: getNewSelection(selection, amount.length, newAmountWithoutSpaces.length)
    }
})
```

**Comment by ygshbht** [comment] 2023-08-13 15:19
> @ygshbht I tried out this [#23300 (comment)](https://github.com/Expensify/App/issues/23300#issuecomment-1644464026) solution and its causing issues for me
> 
>  az_recorder_20230813_202032.mp4 
> Can you put all your proposal in a single comment as per the guideline? You can submit a new proposal comment in your name with all the information

@abdulrahuman5196  What is the code you are using as I am unable to see the issue. 

After the update to `MoneyRequestAmountForm.js`, the new code should look like: 
```
const setNewAmount = (newAmount) => {
    // Remove spaces from the newAmount value because Safari on iOS adds spaces 
    // when pasting a copied value
    // More info: https://github.com/Expensify/App/issues/16974
    const newAmountWithoutSpaces = MoneyRequestUtils.stripSpacesFromAmount(newAmount);

    // Use a shallow copy of selection to trigger setSelection
    // More info: https://github.com/Expensify/App/issues/16385
    if (!MoneyRequestUtils.validateAmount(newAmountWithoutSpaces)) {
        setCurrentAmount((prevAmount) => prevAmount);
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }

    let hasSelectionBeenSet = false;
    setCurrentAmount((prevAmount) => {
        if (!hasSelectionBeenSet) {
            setSelection((prevSelection) => {
                hasSelectionBeenSet = true;
                return getNewSelection(prevSelection, prevAmount.length, newAmountWithoutSpaces.length);
            });
        }
        return MoneyRequestUtils.stripCommaFromAmount(newAmountWithoutSpaces);
    });
};

```
This is the original solution. [Alternate solution](https://github.com/Expensify/App/issues/23300#issuecomment-1644517120) can be modified similarly based on the changes happened to the page since the proposal was submitted

**Comment by s-alves10** [comment] 2023-08-13 23:14
@abdulrahuman5196 

Please explain the drawback of my proposal in words. I didn't understand the video. Thanks

**Comment by s-alves10** [comment] 2023-08-14 03:06
> If we change as per the proposal it is causing the below issue.

@abdulrahuman5196 

This issue is not related to my proposal. Please check https://expensify.slack.com/archives/C049HHMV9SM/p1691982118109469

**Comment by ygshbht** [comment] 2023-08-14 06:40
@abdulrahuman5196 I've also attached code for Alternate Solution. Please feel free to replace this with your existing file and test
[MoneyRequestAmountForm.txt](https://github.com/Expensify/App/files/12332043/MoneyRequestAmountForm.txt)

**Comment by abdulrahuman5196** [comment] 2023-08-18 18:06
I need to check on the latest proposal updates. Will review in my morning

**Comment by garrettmknight** [comment] 2023-08-22 14:47
@abdulrahuman5196 please review this one too.

**Comment by abdulrahuman5196** [comment] 2023-08-23 17:38
I am testing this out. Will need to re-verify if the mentioned issues are present in main as well and not related to this proposal. Will update here in sometime.

**Comment by ygshbht** [comment] 2023-08-23 17:40
I can also confirm that It is not related to this issue or proposals.

**Comment by ygshbht** [comment] 2023-08-25 14:54
I'd like to mention that in the [alternate solution](https://github.com/Expensify/App/issues/23300#issuecomment-1676389278) that I propose, the code gets the `prevSelection `value from the `setState `function like it currently does, so there's no potential issues here.

**Comment by abdulrahuman5196** [comment] 2023-08-29 17:46
I am seeing couple more inconsistent issues with the back button. But mostly present in main as well. I will try to see if something should be fixed alongside this or should we fix only the issue mentioned using either of the above proposals.

**Comment by michaelhaxhiu** [comment] 2023-08-29 22:45
Sounds good @abdulrahuman5196 let us know what you think is ideal to proceed (e.g. individual one-off fix or group a series issue to fix).

**Comment by abdulrahuman5196** [comment] 2023-09-11 16:29
I will take this as one off issue. Re-tested both the solutions(by @ygshbht and @s-alves10 ) and both are working. IMO both are relatively same concept on high level.

Anyways, I was going through the docs shared by @s-alves10 
>This is a behavior for development and helps us avoid accident impure updaters. Please refer https://react.dev/reference/react/useState#my-initializer-or-updater-function-runs-twice

This behaviour mentioned as a development only on react website `This development-only behavior helps you [keep components pure.](https://react.dev/learn/keeping-components-pure) React uses the result of one of the calls, and ignores the result of the other call. As long as your component, initializer, and updater functions are pure`

Any idea why this issue seen in our prod as well?

**Comment by s-alves10** [comment] 2023-09-12 12:08
## Proposal
[Updated](https://github.com/Expensify/App/issues/23300#issuecomment-1667075869)

@abdulrahuman5196 
I updated my proposal, mainly the root cause section.

**Comment by abdulrahuman5196** [comment] 2023-09-15 17:27
Need to re-verify rootcause, will cover over weekend

**Comment by garrettmknight** [comment] 2023-09-19 11:14
@abdulrahuman5196 did you get to verify the root cause?

**Comment by michaelhaxhiu** [comment] 2023-09-20 15:03
Friendly bump 🙏  let's get this moving if we can since the proposals are primed and simply needing the "go ahead" (or some tweaking until they are ready to go ahead!)

**Comment by abdulrahuman5196** [comment] 2023-09-26 15:11
Just Got back from OOO https://expensify.slack.com/archives/C02NK2DQWUX/p1695704044348249?thread_ts=1695402170.354519&cid=C02NK2DQWUX


Will complete this out sooner.

**Comment by abdulrahuman5196** [comment] 2023-09-27 10:57
@s-alves10 your last solution was working. I am not able to understand the new updated change? 

> The problem is in that the updater of setSelection is called with the latest value of selection. We can fix this by not using the updater

I don't understand this. Could you explain what you mean by this?

**Comment by abdulrahuman5196** [comment] 2023-09-28 06:15
>The problem is in that the updater of setSelection is called with the latest value of selection. We can fix this by not using the updater

@s-alves10 I am not able to understand this? Could you provide more information on this?

**Comment by s-alves10** [comment] 2023-09-28 06:37
@abdulrahuman5196 

> Inside `onLongPress` handler, the updater function is called twice, that is, the updater of `setCurrentAmount` runs twice with the same value. React would take any one result as a next state.
This doesn't affect the next state of the `currentAmount` state because this updater is called with the same `prevAmount` parameter and its result would be the same.

I think you understood this. The point is that _**React calls the updater function twice with the same parameter**_

But this is not the case for `setSelection`.
We call `setSelection` inside `setCurrentAmount` updater function. The updater of `setSelection` is called twice because `setCurrentAmount` updater is called twice. This is a normal state update.
This is same as the case below. `increaseTwice` function would increase the `count` value by 2 because `prevCount` is the latest value
```
const [count, setCount] = useState(0);

const increaseTwice = () => {
  setCount(prevCount => prevCount + 1);
  setCount(prevCount => prevCount + 1);
}
```

I hope this makes sense

**Comment by abdulrahuman5196** [comment] 2023-09-28 06:42
@s-alves10 I understood the point of saying the call was made twice(which we had previously verified as well). But I didn't understand the changes mentioned to fix.

**Comment by s-alves10** [comment] 2023-09-28 06:45
@abdulrahuman5196 

The below code would increase the count by one because `setCount` won't update the count value immediately.
```
const increaseTwice = () => {
  setCount(count + 1);
  setCount(count + 1);
}
```

**Comment by s-alves10** [comment] 2023-09-28 11:27
@abdulrahuman5196 

As you can see https://react.dev/reference/react/useState#my-initializer-or-updater-function-runs-twice, we shouldn't place any code with side effect in a updater function. This issue is an example of updater function with side effect. We should remove this.

**Comment by michaelhaxhiu** [comment] 2023-09-28 13:34
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday). 

**Next steps:**
- Sherpa this forward with @abdulrahuman5196
- If no viable proposals, it may be wise to increase the bounty
- Then at the end we'll pay the contributors who helped get this across the line.

**Comment by abdulrahuman5196** [comment] 2023-09-29 15:19
I still don't understand the mention. I will re-test again, if not will create a slack thread tomorrow morning to speed up the progress.

**Comment by s-alves10** [comment] 2023-09-29 15:24
@abdulrahuman5196 

```
setCount(count + 1);
setCount(count => count + 1);
```
You mean you don't understand the difference between above two calls?

**Comment by abdulrahuman5196** [comment] 2023-10-01 07:44
Reviewing again now

**Comment by abdulrahuman5196** [comment] 2023-10-01 07:58
@s-alves10 I got what you mean. But I am not super inclined. Hypothetically I think there could be a possibility where `setCount(count + 1);` called twice could also increment the count to +2 if the count got updated before the 2nd setCount call. And mostly we are not solving the issues of `setSelection` being called twice.


But I actually liked your previous approach as in the below screenshot. Not sure why that solution was removed from your end. There has been some modifications to the`setNewAmount`, could you kindly recheck if that solution is still working and add it as solution 1 and 2 in your proposal?

<img width="604" alt="Screenshot 2023-10-01 at 1 25 26 PM" src="https://github.com/Expensify/App/assets/46707890/5e7c2810-113b-49dc-a8fb-ac47846a15e0">

**Comment by s-alves10** [comment] 2023-10-02 09:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/23300#issuecomment-1667075869)

**Comment by laurenreidexpensify** [comment] 2023-10-03 12:42
Still waiting for a suitable proposal

**Comment by abdulrahuman5196** [comment] 2023-10-03 14:56
@s-alves10 The proposed change is regressing in ios native. I am seeing this issue  on back long press but not observing the same in main.

For First solution:


https://github.com/Expensify/App/assets/46707890/67048de2-2ff5-4093-8a21-b4b23d7ffa76



For second solution also occasionally in ios native the cursor is jumping one number before.

**Comment by s-alves10** [comment] 2023-10-03 15:51
@abdulrahuman5196 

> For second solution also occasionally in ios native the cursor is jumping one number before.

This happens on the main as well

**Comment by abdulrahuman5196** [comment] 2023-10-03 16:48
> @abdulrahuman5196
> 
> > For second solution also occasionally in ios native the cursor is jumping one number before.
> 
> This happens on the main as well

Not sure on this. Anyways, we are solving the same issue in chrome mobile. Shouldn't it fix on ios native as well?

**Comment by s-alves10** [comment] 2023-10-03 16:55
@abdulrahuman5196 

> For second solution also occasionally in ios native the cursor is jumping one number before.

This is not related to the suggested change. And yes, ideally it would be good to solve this issue as well. This looks like have a different RCA

I'm investigating

**Comment by s-alves10** [comment] 2023-10-04 02:21
## Proposal
[Updated](https://github.com/Expensify/App/issues/23300#issuecomment-1667075869)

@abdulrahuman5196 

Updated proposal works perfect on all platforms. Will you take a look again?

**Comment by abdulrahuman5196** [comment] 2023-10-04 07:10
Thank you will re-test tonight

**Comment by abdulrahuman5196** [comment] 2023-10-04 17:06
Reviewing again

**Comment by abdulrahuman5196** [comment] 2023-10-04 17:38
@s-alves10 Your latest solution was already provided as an alternative solution by @ygshbht here https://github.com/Expensify/App/issues/23300#issuecomment-1676389278

**Comment by s-alves10** [comment] 2023-10-04 18:17
@abdulrahuman5196 

> This updates prevent the double call from changing the selection twice and fix the issue due to the inconsistency of amount and selection.

My proposal is based on the root cause of the original issue and the newly found issue(amount and selection inconsistency)

**Comment by abdulrahuman5196** [comment] 2023-10-05 09:38
Got it. Could be a false positive then

**Comment by abdulrahuman5196** [comment] 2023-10-06 12:32
Still working on review. Will provide update before Morning

**Comment by laurenreidexpensify** [comment] 2023-10-09 09:04
@abdulrahuman5196 have you completed the review yet? thanks

**Comment by ygshbht** [comment] 2023-10-09 10:12
@abdulrahuman5196 
Your worry is understandable. However, I'd like to mention that grouping related state variables is a standard practise in React. 
[More on react docs](https://legacy.reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables)

**Comment by laurenreidexpensify** [comment] 2023-10-11 09:07
@abdulrahuman5196 have put a call out to expert groups 👍

**Comment by koko57** [comment] 2023-10-11 12:06
Hi! I'm Agata from Callstack 🙂 Maybe I can help?

**Comment by koko57** [comment] 2023-10-12 16:09
I did some investigation here - the root cause is correct it's because the setSelection inside setCurrentAmount runs twice on the web (it doesn't on native) and the issue is not limited to Android - it affects iOS Safari as well. I even enabled BigPadNumber on the web and it also happens there.

Both solutions (the one from @ygshbht and the second from @s-alves10) are working for me, to be honest, I haven't found any regressions. At this moment I'm slightly inclined towards @s-alves10 solution to merge these values and set the state only once as we mostly set them together. Let me review both solutions once again tomorrow. I'll also think of any alternative solution to this issue.

**Comment by abdulrahuman5196** [comment] 2023-10-13 06:31
Thank you for the insights @koko57 . I wasn't inclined on that due to concept of merging 2 state values into 1 to solve this particular issue otherwise which the states would have been separate logically. But if we don't see any alternative solutions to this issue, I am ok to go with the proposal of merging 2 states into one. Do let us know once you have more information on the same.

**Comment by koko57** [comment] 2023-10-13 14:31
@abdulrahuman5196 I consulted with my team and they advised not to go with @s-alves10 solution and merge the state values as we do not always change them both - like in onSelectionChange. Everytime we would need to change the state we would have to pay attention if we do it correctly. They were more in favor of @ygshbht solution because it's easier to implement and with a proper comment it would be more readable. However, I tested both solutions once again and found a problem with @ygshbht solution - after long pressing the backspace and then trying to change the cursor's position the onSelectionChange is not triggered and the selection is not updated. 

https://github.com/Expensify/App/assets/28020445/1af492a5-fadc-4a05-94c1-902f7de93af1

It happens only in Android Chrome - iOS Safari works fine. It also happens the same way and only on Android without the fix.
I'll try to check why it's happening on Monday, I will also try to find another solution, but as you @abdulrahuman5196 mentioned - if it won't be possible to find another working fix, then we can go with @s-alves10 proposal.

**Comment by ygshbht** [comment] 2023-10-13 14:44
> after long pressing the backspace and then trying to change the cursor's position the onSelectionChange is not triggered and the selection is not updated.

@koko57 I think that's a problem with different root cause which is also present when you merge the state variables together

There was more discussion here https://github.com/Expensify/App/issues/23300#issuecomment-1676385062 https://github.com/Expensify/App/issues/23300#issuecomment-1676604304

**Comment by s-alves10** [comment] 2023-10-13 15:05
@koko57 

Thank you for your effort and explanation
Please check https://github.com/Expensify/App/issues/23300#issuecomment-1745152986 as well. We need to consider all the platforms

Below is my question
> Everytime we would need to change the state we would have to pay attention if we do it correctly.

Is this so important? I think we can do this easily like `setSize({...size, width: newWidth})`. Please teach me if I missed something
Thank you in advance

**Comment by abdulrahuman5196** [comment] 2023-10-16 14:27
It was only weekend meanwhile melvin. We are waiting on updates from @koko57

**Comment by koko57** [comment] 2023-10-16 18:52
@abdulrahuman5196 sorry, I had to take care of my other issue, I didn't have time to work on this issue today. I'll get back to it tomorrow

**Comment by koko57** [comment] 2023-10-17 12:08
@abdulrahuman5196 I don't have a better idea to solve this problem - let's go with @ygshbht solution 🙂

**Comment by s-alves10** [comment] 2023-10-17 12:10
@koko57 
Can you please check https://github.com/Expensify/App/issues/23300#issuecomment-1761672541?

**Comment by koko57** [comment] 2023-10-17 12:26
@s-alves10 I've mentioned that both - yours and @ygshbht solution have the same problem with the cursor that seems to be a different problem than the one we want to solve here. So in terms of this, there's no winner here. 
My team and I would rather go with @ygshbht solution because it's easier to implement, more readable and there is less risk that someone can break this logic when making changes to updating the merged state in the future. If we always changed both state values, I guess, I would hesitate more between those two solutions. Here, I think, we should go with the simpler one. 

@ygshbht if your proposal will be approved by C+ Team and you will start working on the PR, please add a comment explaining why we need this part of the code.

**Comment by s-alves10** [comment] 2023-10-17 12:31
@koko57 

Please don't take me wrong. I just wanted to know what the downsides of merging state are. As a big fan of react.js, I'm asking you the technical question. Can you leave the answer here for the question?

**Comment by ygshbht** [comment] 2023-10-17 12:40
@koko57 Sure, I will!

**Comment by s-alves10** [comment] 2023-10-17 13:25
@koko57 @abdulrahuman5196 

Yes. I think we can use merged state without any side effects by using state updates like `setSize({...size, width: newWidth})`.

Merging state is needed especially when multiple states should be updated simultaneously
In our case, you can notice that the cursor flickers when the amount is updated(on native platforms). That's because `amount` and `selection` are not updated at the same time and the component is re-rendered multiple times with half-finished states.(Need to consider that state updates are not always batched even in react 18).

https://github.com/Expensify/App/assets/126839717/e5ded92e-dc14-4001-afd5-717a28a850ff

This is one reason that I suggested the merging of state. I think we need to care about this

Anyway, I respect the decision of you and C+ team.
Thank you

PS: If I was wrong, please kindly leave comments

**Comment by koko57** [comment] 2023-10-17 15:38
@s-alves10 I also thought so about the rerenders, but I've checked both solutions (on native iOS and Android and on web) and there was no difference in the renders count between them.

**Comment by s-alves10** [comment] 2023-10-17 15:44
@koko57 `setNewAmount` function is called in the `setInterval` callback when long-pressing back button. You know, state updates in a timer are not batched obviously. Please check the visual effect(cursor flickering) on ios native

**Comment by abdulrahuman5196** [comment] 2023-10-18 14:51
@koko57 Thank you for the analysis and guidance. Since we don't have any better solutions to go through, I am fine with the suggestion to go with @ygshbht 's proposal here. 

Regarding the concern of @s-alves10 on combining state variables, **I am not so much against it**. But still, the idea of combining state variables was proposed as an alternative solution on @ygshbht 's proposal first(At the time we were still looking for better solutions so we didn't approve). So even if we were to choose the combining of states, it would still go to @ygshbht 

So I would leave it to the internal engineer to confirm if we would go with the main proposal or the alternate proposal of @ygshbht combining 2 state variables.

**Comment by abdulrahuman5196** [comment] 2023-10-18 14:58
@ygshbht 's proposal here https://github.com/Expensify/App/issues/23300#issuecomment-1676389278 looks good and works well. We can either choose the main proposal(suggested by expert group as well) or we can go with the alternative proposal of combining states.

🎀 👀 🎀
C+ Reviewed

**Comment by laurenreidexpensify** [comment] 2023-10-20 10:51
@madmax330 bump for review ^^

**Comment by ygshbht** [comment] 2023-10-20 12:43
I'll have the PR ready in a day! Job is no longer available on Upwork.

**Comment by ygshbht** [comment] 2023-10-20 14:16
@abdulrahuman5196 The [PR](https://github.com/Expensify/App/pull/30082) is ready for review

**Comment by abdulrahuman5196** [comment] 2023-10-25 15:28
>Will the job be eligible for bonus? PR was created within hours of assignment and C+ approved the changes within 2 days.

This would be yes similar to other issues IMO.

**Comment by abdulrahuman5196** [comment] 2023-10-31 09:37
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the behaviour for long time.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Click FAB on Chrome mobile
2) Click Reqeust Money/ Split Bill
3) Enter amount more than 3 digits (e.g 6323)
4) Hold the back key "<"
5) Verify that last digit is removed and cursor is still at last place

**Comment by laurenreidexpensify** [comment] 2023-11-03 10:23
Payment Summary: 

- External issue reporter @ygshbht $250 - please apply to job in Upwork 
- Contributor that fixed the issue @ygshbht $2000 + $1000 bonus - please apply to job in Upwork 
- Contributor+ that helped on the issue and/or PR @abdulrahuman5196 - $2000 + $1000 bonus - payment issued in Upwork

**Comment by laurenreidexpensify** [comment] 2023-11-03 10:31
@ygshbht please accept job in Upwork - https://www.upwork.com/en-gb/jobs/~0175ccda3750737e98

**Comment by ygshbht** [comment] 2023-11-03 10:47
Thanks. Accepted!

**Closed** 2023-11-03 10:53 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
