### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Expense - Inconsistency in dismissing report details RHP when deleting expense with comments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44336] opened 2024-06-24 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-10
**Reproducible in staging?:** Y 
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to any user with no unsettled expense
3. Go to transaction thread and add some comments
4. Click on the report header > Delete expense > Delete it
5. Note that report details RHP closes
6. Submit two expenses to any user
7. Go to transaction thread of any of the submitted expense
8. Add some comments
9. Click on the report header > Delete expense > Delete it
10. Note that report details RHP does not close

## Expected Result:
When deleting expense with comments in the combined report or transaction thread, the behavior of report details RHP (close or not close) should be the same

## Actual Result:
In Step 5, when deleting expense with comments in the combined report, report details RHP closes
In Step 10, when deleting expense with comments in the transaction thread, report details RHP does not close

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9fcd36d0-5fed-46a0-88fe-f69265f15402

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129ce6e9afec28c89</li>
        <li>Upwork Job ID: 1805348927110425747</li>
        <li>Last Price Increase: 2024-07-01</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102947141</li>
<li>bernhardoj | Contributor | 102947144</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment] 2024-06-24 20:46
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rojiphil** [comment] 2024-06-25 07:34
@nyomanjyotisa Where are you suggesting to make the change? In `deleteTrackExpense` or `deleteMoneyRequest`?

**Comment by bernhardoj** [comment] 2024-06-25 07:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency of behavior when deleting an expense with comments from report details page.

### What is the root cause of that problem?
When we submit a single expense, open the expense report, and add some comments, deleting the expense will also delete the transaction thread.
workspace chat report -> expense report (some comments) -> transaction thread (no comment)

If the transaction thread is going to be deleted, then it will return the route to the expense report,
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/libs/actions/IOU.ts#L5571-L5574

which we use here, thus the details page is closed (or replaced to be specific):
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/pages/ReportDetailsPage.tsx#L632-L637

However, that shouldn't happen. If we see this condition once again,
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/libs/actions/IOU.ts#L5571-L5574

we can notice that `isSingleTransactionView` should be true. We currently always pass it as true, but it should only be true if the report is a transaction thread. We can see that we already define `isSingleTransactionView` in the details page component, but we don't use it in this case.
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/pages/ReportDetailsPage.tsx#L124

### What changes do you think we should make in order to solve the problem?

Pass `isSingleTransactionView` instead of `true`.
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/pages/ReportDetailsPage.tsx#L551-L555

_If we want to close the RHP when deleting the expense, then we should call `Navigation.dismissModal`_

**Comment by nyomanjyotisa** [comment] 2024-06-25 08:04
> @nyomanjyotisa Where are you suggesting to make the change? In `deleteTrackExpense` or `deleteMoneyRequest`?

@rojiphil in `deleteMoneyRequest`

**Comment by rojiphil** [comment] 2024-06-25 09:10
Thanks all for your proposals.

The correct RCA is that while deletion of an expense from transaction thread report without comments would return the iou report for navigation, deletion of an expense from transaction thread report with comments would not return the transaction thread report for navigation which caused this issue.

@dominictb [proposal](https://github.com/Expensify/App/issues/44336#issuecomment-2187947885) suggest calling `Navigation.goBack` in `OnModalHide` but this is not required as this will be unnecessarily called in the case of deletion the task. 

@nyomanjyotisa suggest returning back the transaction thread report id for navigation when it is not supposed to be deleted. This will also dismiss the report details view
@nyomanjyotisa [proposal](https://github.com/Expensify/App/issues/44336#issuecomment-2187999037) LGTM
🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-06-25 09:15
@rojiphil what about my proposal

**Comment by rojiphil** [comment] 2024-06-25 09:48
@bernhardoj Sorry. I missed mentioning feedback about your proposal. 
Passing  `isSingleTransactionView` instead of `true` would not solve the problem. Right? Or did I miss something here?

**Comment by bernhardoj** [comment] 2024-06-25 10:28
The current behavior is:
- Deleting an expense from the transaction thread doesn't close the RHP
- Deleting an expense from the one-transaction IOU report closes the RHP

By passing `isSingleTransactionView`, both cases won't close the RHP.

Using the selected solution will cause a double transaction thread in the nav stack.


https://github.com/Expensify/App/assets/50919443/daf02041-3a58-4533-ae2c-23b99b3ed97e

**Comment by mountiny** [comment] 2024-06-25 10:46
I am demoting this as it's quite an edge case, and the solutions are not super straightforward, so @rojiphil, please make sure to validate them thoroughly, I dont think its worth to rush the fix for this and CP it.

**Comment by rojiphil** [comment] 2024-06-25 11:47
> Using the selected solution will cause a double transaction thread in the nav stack.

@bernhardoj Ah! That’s a good catch. Thanks.
Can you please add further code details to your proposal regarding how this would be addressed?

**Comment by bernhardoj** [comment] 2024-06-25 12:10
That's the issue when applying the selected solution, not mine.

**Comment by lschurr** [comment] 2024-06-28 18:55
What's next here @rojiphil?

**Comment by jasperhuangg** [comment] 2024-06-28 19:49
Not overdue! Just waiting on a response from @rojiphil on [this](https://github.com/Expensify/App/issues/44336#issuecomment-2188584017) 🙇

**Comment by lschurr** [comment] 2024-07-01 16:28
Bump @rojiphil

**Comment by jasperhuangg** [comment] 2024-07-01 17:45
Looked over @bernhardoj's proposal and it makes sense to me. Gonna go ahead and assign them to keep this issue moving.

**Comment by rojiphil** [comment] 2024-07-01 17:55
> Looked over @bernhardoj's proposal and it makes sense to me. Gonna go ahead and assign them to keep this issue moving.

Thanks @jasperhuangg. And `dismissModal` would avoid double transaction thread report in nav stack.
Also sorry for the delay in response here.

**Comment by bernhardoj** [comment] 2024-07-02 06:45
@jasperhuangg @rojiphil Just want to clarify one thing, are we fine to always close the details page when deleting the expense? Or only close it when the expense report is also deleted?

**Comment by rojiphil** [comment] 2024-07-02 08:14
> Just want to clarify one thing, are we fine to always close the details page when deleting the expense? Or only close it when the expense report is also deleted?

As per the expected behavior, yes, we always need to close the details page when deleting the expense. But do you see any good reason to close it only when the expense report is deleted?

**Comment by bernhardoj** [comment] 2024-07-02 08:35
The expected result actually says either close or not close, but they should be the same. It makes sense that we close the details page when the expense report detail is deleted too because the report is deleted so nothing to show, but I don't see the reason yet why we want to close it when the report is not deleted (we only delete the transaction).

**Comment by rojiphil** [comment] 2024-07-03 13:39
> I don't see the reason yet why we want to close it when the report is not deleted (we only delete the transaction).

Well I think it's debatable as it may not be required to show the Report details page on deletion of the expense. 

Let's see what the @Expensify/design team thinks.
Once we delete an expense in the Report Details page of the Transaction Thread Report, should we close or keep Report Details page? 
Here is a test video demonstrating this.

https://github.com/Expensify/App/assets/3004659/c1841dd7-4afb-4f05-9dcc-890a038e8d56

**Comment by dannymcclain** [comment] 2024-07-03 13:45
Hmm, curious for what the other designers think, but it feels a little weird to me to keep the RHP open.

**Comment by shawnborton** [comment] 2024-07-03 14:45
Agree, I would think we would close the RHP once the delete action is taken.

**Comment by bernhardoj** [comment] 2024-07-03 15:55
Thanks for the confirmation! PR is ready

cc: @rojiphil

**Comment by dubielzyk-expensify** [comment] 2024-07-03 23:27
+1 to what Danny and Shawn said

**Comment by jasperhuangg** [comment] 2024-07-16 18:31
^ Issue isn't actually a deploy blocker because the expected behavior of the integration test has changed. I'm leaving the issue open to see if we need to update the integration test.

Otherwise everyone involved here can ignore!

**Comment by lschurr** [comment] 2024-07-24 16:00
@rojiphil - please accept [the offer in Upwork](https://www.upwork.com/nx/wm/offer/102947141) so that we can finalize payments.

@bernhardoj - Are you paid via Upwork still or should this be a manual request in NewDot?

**Comment by rojiphil** [comment] 2024-07-24 16:11
> please accept [the offer in Upwork](https://www.upwork.com/nx/wm/offer/102947141) so that we can finalize payments.

@lschurr Accepted offer. Thanks.

**Comment by bernhardoj** [comment] 2024-07-24 16:23
@lschurr I'll request in NewDot. Thanks!

**Comment by lschurr** [comment] 2024-07-24 16:39
Payment summary:

- Contributor: $250 @bernhardoj (to be paid in NewDot)
- Reviewer: $250 @rojiphil (paid in Upwork)

**Closed by lschurr** 2024-07-24 16:39 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-26 00:42
$250 approved for @bernhardoj
