### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Login - Two error messages appear simultaneously

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32559] opened 2023-12-06 11:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Enter a random incorrect phone number (I use 6786478646)
3. Tap Continue
4. Notice that an error message appears (The provided phone number belongs to a landline or VoIP, please use your email address instead)
5. Delete latest digit

## Expected Result:
Only one error message displayed

## Actual Result:
Two error messages appear simultaneously for a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6303062_1701861953655!Screenshot_2023-12-05-23-30-30-73_99c04817c0de5652397fc8b56c3b3817](https://github.com/Expensify/App/assets/115492554/278489fd-4ae9-4d50-bb3e-d44e13c7f26d)

https://github.com/Expensify/App/assets/115492554/6233e844-2a8f-4ab3-b271-e7a53e5ad61a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017dead7572ed3bc76</li>
        <li>Upwork Job ID: 1732367308152152064</li>
        <li>Last Price Increase: 2023-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28041559</li>
<li>paultsimura | Contributor | 28041560</li>
</ul></li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-06 12:06
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Login - Two error messages appear simultaneously

## What is the root cause of that problem?

The main problem is that we use 2 fields for errors

https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/pages/signin/LoginForm/BaseLoginForm.js#L272

https://github.com/Expensify/App/blob/bbe73efdfab056d5ab6d864941fc3da44ec1c084/src/pages/signin/LoginForm/BaseLoginForm.js#L295

## What changes do you think we should make in order to solve the problem?

I think the best way to fix this is
Transfer the logic of one error message to another
So that the error display uses only one component

## What alternative solutions did you explore? (Optional)
NA

**Comment by rojiphil** [comment] 2023-12-07 06:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Two error messages appear simultaneously for a short time when we edit the phone/email input field after an unsuccessful signin attempt using invalid phone/email.

### What is the root cause of that problem?

Upon failed sign-in attempt using invalid phone/email, the server error text gets displayed. Now, on editing the phone/email input field, we set the `login` variable and also perform validation [here](https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/pages/signin/LoginForm/BaseLoginForm.js#L143C1-L146C14). However, this is done even before the session account messages are cleared [here](https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/pages/signin/LoginForm/BaseLoginForm.js#L148C1-L150C14). As the input sanity check occurs first with an error, this gets rendered even before the session error messages are cleared and rendered. This is the root cause of the problem

### What changes do you think we should make in order to solve the problem?

We can change the order and bring `Session.clearAccountMessages` first to solve this problem like this:

```
            if (props.account.errors || props.account.message) {
                Session.clearAccountMessages();
            }

            setLogin(text);
            if (firstBlurred.current) {
                console.log("Validate OnTextInput");
                validate(text);
            }
```

We may also want to set the input and validate after account closure message [here](https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/pages/signin/LoginForm/BaseLoginForm.js#L152C1-L155C14) so that both the messages are not shown for a short while. 

### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment] 2023-12-08 21:37
@cubuspl42 what do you think about the proposals above?

**Comment by cubuspl42** [comment] 2023-12-11 16:48
From the provided proposals, I find the one by @ZhenjaHorbach the most convincing

C+ reviewed 🎀 👀 🎀

**Comment by paultsimura** [comment] 2023-12-11 16:52
@cubuspl42 I thought the same before finding https://github.com/Expensify/App/pull/14627 – the selected proposal is basically straight reverting that PR. Maybe it's worth asking the author of that PR whether it's still relevant to split the server & form errors?

**Comment by cubuspl42** [comment] 2023-12-11 17:13
You're right; I missed this. It's important. I have to reconsider.

**Comment by cubuspl42** [comment] 2023-12-11 17:25
After reconsideration, I must agree with @paultsimura that the proposal by @ZhenjaHorbach directly conflicts with a direction established by the PR https://github.com/Expensify/App/pull/14627 from an internal engineer.

In such a situation, we should go with @paultsimura

During the PR implementation, we can discuss whether we can introduce a local discriminated union like `EffectiveError`, to achieve at least _some_ "source of truth" unification.

C+ reviewed 🎀 👀 🎀 (again)

**Comment by lakchote** [comment] 2023-12-12 09:35
@paultsimura's proposal LGTM 👍!

**Comment by paultsimura** [comment] 2023-12-12 20:11
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/32944

**Comment by luacmartins** [comment] 2023-12-14 17:09
Left a comment in Slack, but I think this is the expected behavior.

**Comment by cubuspl42** [comment] 2023-12-15 09:56
@luacmartins It's not possible that the whole behavior as present in the video is expected.

**Comment by paultsimura** [comment] 2023-12-15 10:04
@cubuspl42 there was further discussion [in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1702465027956659), we've agreed that it's not an expected behavior.

**Comment by johncschuster** [comment] 2023-12-15 22:00
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
The issue has been assigned. We're just waiting on a PR.

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by paultsimura** [comment] 2023-12-16 00:02
@johncschuster the PR has been merged already.
Also, I'm not sure if it was intentional, but you self-assigned this issue after the OOO message (instead of, probably, unassigning).

**Comment by cubuspl42** [comment] 2023-12-18 10:46
> **Current status:** The issue has been assigned. We're just waiting on a PR.

Like Pavlo said, we're nearly done here. The state of this issue should be "hold on payment" soon.

**Comment by joekaufmanexpensify** [comment] 2023-12-18 15:18
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-12-21 16:50
Per [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1703082403934039), payment may be delayed a few days here because of the holidays. @cubuspl42 if you have time over the next week to handle the BZ checklist too, that'd be great!

**Comment by cubuspl42** [comment] 2023-12-27 13:58
- The PR that introduced the bug has been identified. Link to the PR:
    - It's difficult or impossible to point to specific frontend PRs when backend errors are involved 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Go to the "Sign-in" page
    - Enter an incorrect phone number (e.g. 6786478646)
    - Press "Continue"
    - Notice that an error message appears ("The provided phone number belongs to a landline or VoIP, please use your email address instead")
    - Delete the last digit
      - Verify that the error is instantly changed to the "Please enter a valid phone number" without displaying 2 errors at the same time

**Comment by joekaufmanexpensify** [comment] 2024-01-01 17:35
TY! I've been OOO for the holidays, but will take care of the remaining steps here and issue payment tomorrow.

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:12
BZ checklist is complete. IMO, this is a pretty niche error, so no regression test is needed.

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:12
All set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:13
We need to issue the following payments: 

- @paultsimura - $500 for PR. Paid via Upwork. 
- @cubuspl42 - $500 for C+. Paid via upwork.

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:15
@paultsimura $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:15
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-01-02 15:15
This one's all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-01-02 15:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
