### ISSUE TITLE
[HOLD for payment 2023-08-24] [$1000] Workspace - The border radius of the workspace icon and the overlay are not the same

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24069] opened 2023-08-02 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisite: have more than 4 workspaces (at least one with custom image)
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
    page
2. Open settings
3. Take a look at the workspaces (the one with custom image)

## Expected Result:
Workspaces visually should look the same

## Actual Result:
Workspace with custom image has an extra empty space next to the image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x]  MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6150748_Capture](https://github.com/Expensify/App/assets/78819774/62e780af-8293-4311-9b73-b5e39111a370)
![Bug6150748_iMarkup_20230802_165454](https://github.com/Expensify/App/assets/78819774/2177a9a6-0b57-415e-8390-661d0bb5d82e)
![Bug6150748_iMarkup_20230802_165432](https://github.com/Expensify/App/assets/78819774/bd6a1a87-3777-4cc7-a096-64a152286181)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186b5853447bf36a7</li>
        <li>Upwork Job ID: 1686843318689447936</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2023-08-02 20:38
hmm I suspect https://github.com/Expensify/App/pull/23707 cc @bernhardoj @danieldoglas @thesahindia

**Comment by bondydaa** [comment] 2023-08-02 20:42
able to reproduce on `main` 
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/4073354/cf241a4b-41c5-4dab-ad20-3c70123e05e4">

going to revert https://github.com/Expensify/App/pull/23707 locally and see if it fixes it.

**Comment by bondydaa** [comment] 2023-08-02 20:47
yep that fixes it 
<img width="410" alt="image" src="https://github.com/Expensify/App/assets/4073354/e431f212-c149-4a9f-8a9e-5f3155fc2557">

**Comment by bondydaa** [comment] 2023-08-02 20:50
I don't think we need to revert the PR though. This is pretty minor IMO and only really shows itself if you have multiple workspaces and a custom image uploaded AND that workspace is not the first one in the row 
<img width="406" alt="image" src="https://github.com/Expensify/App/assets/4073354/a037c7b6-caca-4c86-a640-3a0eac6ce8b9">

**Comment by bondydaa** [comment] 2023-08-02 20:54
thread here discussing this https://expensify.slack.com/archives/C01GTK53T8Q/p1691008185925749

but I think we can remove blocker and let this go through external bug process.

**Comment by situchan** [comment] 2023-08-02 21:02
As this was found within regression period, @bernhardoj would be fixing this.

**Comment by bondydaa** [comment] 2023-08-02 21:19
ah yeah sorry whoops I wasn't fully aware of the correct process for these types of regressions. updating the labels and linking it to the OG issue so they can fix it.

**Comment by danieldoglas** [comment] 2023-08-11 01:14
This issue should not have a payment linked to it since it's connected to https://github.com/Expensify/App/issues/23426

**Comment by joekaufmanexpensify** [comment] 2023-08-14 13:15
Yep, makes sense. @abdulrahuman5196 I'm going to remove you from this one, since you didn't review the PR to fix the regression.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:26
Since this was fixing a regression, I don't think any payment is due to @bernhardoj or @thesahindia . And there was no reporter here, which means no payment overall.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 13:27
@bernhardoj / @bondydaa could you complete the checklist here when you have a sec? TY!

**Comment by joekaufmanexpensify** [comment] 2023-08-22 20:44
Cool, thanks! Since there's no payment/BZ checklist needed for this issue, going to close this one, as it's all set. Thanks everyone!

**Closed by joekaufmanexpensify** 2023-08-22 20:44 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
