### ISSUE TITLE
[$1000] Workspace - CMD+ENTER does not work when inviting new members to WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25878] opened 2023-08-24 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com on Chrome or Safari or open Desktop App
2. Login with Expensifail account
3. Go to existing or create new workspace
4. Go to Settings > Workspace > Members > Invite
5. Select some new members using arrow keys of keyboard and press ENTER
6. Press CMD+ENTER to go to the next page

## Expected Result:
User can go to the next page using CMD+ENTER

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.57-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/585771bc-b3e4-4c4e-b37c-fd0f17f33034

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a1186aeecdfe466</li>
        <li>Upwork Job ID: 1694821304249151488</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-24 19:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- After selecting workspace members not able to navigate to next screen using `cmd+enter`

### What is the root cause of that problem?
- We don't have any implementation for `cmd+enter` in `WorkspaceInvitePage` component.

### What changes do you think we should make in order to solve the problem?
- We can take `cmd+enter` implementation from `BaseSelectionList` component. We will make use of useEffect and pass `inviteUser` function as a dependency. So whenever `inviteUser` function changes we will update the `cmd+enter` implementation.

<details>
<summary>Code for CTRLEnter</summary>

```js
useEffect(() => {
    const CTRLEnterConfig = CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER;
    let unsubscribeCTRLEnter = KeyboardShortcut.subscribe(
        CTRLEnterConfig.shortcutKey,
        () => {
            inviteUser();
        },
        CTRLEnterConfig.descriptionKey,
        CTRLEnterConfig.modifiers,
        true,
    );
    return () => {
        unsubscribeCTRLEnter && unsubscribeCTRLEnter();
    };
}, [inviteUser]);
```
</details>

- Another issue which arise was that in next screen if i pressed `cmd+enter` it selected the next user and added it to selected users list.
To fix this we can use ref and set it to `true` when navigating to next screen.

<details>
<summary>Code for Fix</summary>

```diff
const inviteUser = () => {
-       if (!validate()) {
+       if (!validate() || navigated.current) {
+           navigated.current = false;
            return;
        }

        const invitedEmailsToAccountIDs = {};
        _.each(selectedOptions, (option) => {
            const login = option.login || '';
            const accountID = lodashGet(option, 'accountID', '');
            if (!login.toLowerCase().trim() || !accountID) {
                return;
            }
            invitedEmailsToAccountIDs[login] = Number(accountID);
        });
        Policy.setWorkspaceInviteMembersDraft(props.route.params.policyID, invitedEmailsToAccountIDs);
        Navigation.navigate(ROUTES.getWorkspaceInviteMessageRoute(props.route.params.policyID));
+       navigated.current = true;
    };
```
</details>

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by roryabraham** [comment] 2023-08-24 19:08
Shouldn't we use the `useKeyboardShortcut` hook?

**Comment by jeet-dhandha** [comment] 2023-08-24 19:13
Let me check @roryabraham

**Comment by jeet-dhandha** [comment] 2023-08-24 19:16
Yes it works and also i don't have to handle the issue i mentioned above.

**Comment by jeet-dhandha** [comment] 2023-08-24 19:18
## Proposal [UPDATED] => (https://github.com/Expensify/App/issues/25878#issuecomment-1692253137)

### Please re-state the problem that we are trying to solve in this issue.
- After selecting workspace members not able to navigate to next screen using `cmd+enter`

### What is the root cause of that problem?
- We don't have any implementation for `cmd+enter` in `WorkspaceInvitePage` component.

### What changes do you think we should make in order to solve the problem?
- We can use `useKeyboardShortcut` like below and it should do the trick.

```js
useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, inviteUser);
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by stitesExpensify** [comment] 2023-08-24 19:23
What PR caused this bug?

**Comment by jeet-dhandha** [comment] 2023-08-24 19:37
@stitesExpensify No PR has caused this bug. As CMD+ENTER is handled in `OptionsSelector` by default and in `SelectionList` its not implemented, which is currently being used in `WorkspaceInvitePage` page.

**Comment by Pujan92** [comment] 2023-08-24 20:13
I am seeing Enter is selecting the item, do we also need to support Ctrl+Enter here?

**Comment by stitesExpensify** [comment] 2023-08-24 20:57
In that case, this is not a regression right? It is new functionality?

**Comment by jeet-dhandha** [comment] 2023-08-24 21:01
Yes its a new functionality.

**Comment by roryabraham** [comment] 2023-08-24 23:26
> No PR has caused this bug. As CMD+ENTER is handled in OptionsSelector by default and in SelectionList its not implemented, which is currently being used in WorkspaceInvitePage page ... its a new functionality

I respectfully disagree. This is not new functionality because it works on production. It is 100% a regression, almost certainly caused by https://github.com/Expensify/App/pull/22622

**Comment by Pujan92** [comment] 2023-08-25 02:41
> > No PR has caused this bug. As CMD+ENTER is handled in OptionsSelector by default and in SelectionList its not implemented, which is currently being used in WorkspaceInvitePage page ... its a new functionality
> 
> I respectfully disagree. This is not new functionality because it works on production. It is 100% a regression, almost certainly caused by #22622

@roryabraham I think Ctrl+Enter is working for both production and dev. Cmd+Enter isn't working in production.

**Comment by jeet-dhandha** [comment] 2023-08-25 04:32
@roryabraham Please point out the line where CTRL_ENTER implementation was removed in this PR https://github.com/Expensify/App/pull/22622.  As then only we can count it as a Regression.

**Comment by b4s36t4** [comment] 2023-08-25 07:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This is a regression from PR #22622

Previously we have `OptionsSelector` as the component to render the list of contacts, in which have the listeners for both `ENTER` and `CTRL_ENTER` which serves different purpose.

After the refactor we never had any event listener of `CTRL_ENTER` in `SelectionList` component which was the issue here.

https://github.com/Expensify/App/blob/53c474356a6d3eb64012b84ed18e0cc44530a6e1/src/components/OptionsSelector/BaseOptionsSelector.js#L66-L99

https://github.com/Expensify/App/blob/b38181a2d567cc3cbb5b426f0585db4286747fa6/src/components/SelectionList/BaseSelectionList.js#L290

### What is the root cause of that problem?
Changes we need to do.

1. Introduce a new boolean variable to weather render the footer or not like here https://github.com/Expensify/App/blob/53c474356a6d3eb64012b84ed18e0cc44530a6e1/src/components/OptionsSelector/BaseOptionsSelector.js#L304 to not conflict with the `Next` Button we have in the screen and use here to conditionally render https://github.com/Expensify/App/blob/b38181a2d567cc3cbb5b426f0585db4286747fa6/src/components/SelectionList/BaseSelectionList.js#L383-L397

2. Pass `inviteUser` as `onConfirm` Prop in the `WorkSpaceInvitePage` to `SelectionList` component.
3. Register a listener to listen for `CTRL_ENTER` commands and do the needful work.

```jsx

const onCtrlEnter = () => {
    // Do Confirm
    if (canSelectMultiple) {
        if (onConfirm) {
            onConfirm();
        }
        return;
    }

    // Select the focused option
    selectFocusedOption();
};

useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, onCtrlEnter, 
{captureOnInputs: true, shouldBubble: () => !flattenedSections.allOptions[focusedIndex]});
```

> Mostly replicating what we have in `BaseOptionsSelector` for `CTRL_ENTER` command.

### What changes do you think we should make in order to solve the problem?
NA

**Comment by burczu** [comment] 2023-08-25 09:01
@jeet-dhandha First of all, if you want to update your proposal you should not add a new comment, instead you should update the previous one and then add a new comment with such content:

```
## Proposal
[Updated](link to proposal)
```

Reference [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by Pujan92** [comment] 2023-08-25 14:33
> 3. Register a listener to listen for `CTRL_ENTER` commands and do the needful work.
> 
> ```js
> const onCtrlEnter = () => {
>     // Do Confirm
>     if (canSelectMultiple) {
>         if (onConfirm) {
>             onConfirm();
>         }
>         return;
>     }
> 
>     // Select the focused option
>     selectFocusedOption();
> };
> 
> useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, onCtrlEnter, 
> {captureOnInputs: true, shouldBubble: () => !flattenedSections.allOptions[focusedIndex]});
> ```

@b4s36t4 I was thinking the same(only diff for me is to set the default func for onConfirm) but have you faced that the function executes twice for `Cmd+Enter`?

https://github.com/Expensify/App/assets/14358475/a8849626-602e-473e-8165-b1554d68eb7d

**Comment by jeet-dhandha** [comment] 2023-08-25 16:35
@roryabraham - @stitesExpensify 
What will happen to those who provided proposal's ?
- As i can see @thiagobrez is gonna help with fixes... https://expensify.slack.com/archives/C01GTK53T8Q/p1692952886670059

**Comment by jeet-dhandha** [comment] 2023-08-25 16:38
As in past i know that regression are mostly fixed by the one who caused them and there is no payout for it too.

**Comment by mountiny** [comment] 2023-08-25 19:37
Confirmed this is fixed in staging, no report bonus so closing

**Closed by mountiny** 2023-08-25 19:37 UTC
Labels: External, Engineering, Daily
