### ISSUE TITLE
[New architecture] Upgrade `react-native-camera-roll`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35986] opened 2024-02-07 10:03 UTC
We need to upgrade this library in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R77).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293338290529

**Comment by BartoszGrajdek** [comment] 2024-02-07 10:39
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment] 2024-02-07 18:28
New feat, not a bug. Recategorizing.

**Comment by roryabraham** [comment] 2024-02-07 18:30
@zanyrenney for context, this task was just forked off of the larger initiative to enable the new React Native Architecture in E/App so we can make a series of more bite-sized changes. SWM will handle this.

**Comment by BartoszGrajdek** [comment] 2024-02-08 12:02
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment] 2024-03-01 16:14
@BartoszGrajdek the PR(s) for this were reverted, so we need to redo it.

**Comment by situchan** [comment] 2024-03-01 16:20
> @BartoszGrajdek the PR(s) for this were reverted, so we need to redo it.

redoing here https://github.com/Expensify/App/pull/37316

**Comment by jasperhuangg** [comment] 2024-03-01 18:57
Not overdue!

**Comment by jasperhuangg** [comment] 2024-03-19 17:57
Hey @situchan @BartoszGrajdek what's the latest on this? Are we good to close this out? It looks like the PR redoing things was merged and deployed to production a while ago

**Comment by situchan** [comment] 2024-03-19 17:59
Looks like @mollfpr's payment is pending if not paid elsewhere.
Payment summary: https://github.com/Expensify/App/issues/35986#issuecomment-1949077392

**Comment by jasperhuangg** [comment] 2024-04-09 17:23
@roryabraham Can you confirm if we're good to pay out @thesahindia?

**Comment by roryabraham** [comment] 2024-04-15 19:56
yes, for sure we can complete payment for @thesahindia's review of https://github.com/Expensify/App/pull/36154 then close this out

**Comment by roryabraham** [comment] 2024-04-15 19:57
since the request is going through NewDot, I'm going to close this GitHub issue

**Closed by roryabraham** 2024-04-15 19:57 UTC
Labels: Weekly, NewFeature

**Comment by JmillsExpensify** [comment] 2024-04-30 23:11
$250 approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/35986#issuecomment-1949077392).
