### ISSUE TITLE
[$250] "Approve" button appears even if the report has a violation on it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50479] opened 2024-10-08 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728406913463479

## Action Performed:
1. Submit an expense report with violation
2. Sign in as a approver
## Expected Result:
Should not see a "approve" button since receipt has a violation
## Actual Result:
"Approve" button with GBR appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-10-08 at 1 01 13 PM](https://github.com/user-attachments/assets/412e7ead-e2d5-4eda-86ab-63773ae08f2f)
![Snip - (3) New Expensify - Google Chrome](https://github.com/user-attachments/assets/83d046f2-c961-48e6-af1f-2499e5ac95d1)

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845657010504568512</li>
        <li>Upwork Job ID: 1845657010504568512</li>
        <li>Last Price Increase: 2024-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104460235</li>
<li>abzokhattab | Contributor | 104460238</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by ChavdaSachin** [comment] 2024-10-08 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Approve" button appears even if the report has a violation on it

### What is the root cause of that problem?
We do not check for Violations to display or disable approve button. 
https://github.com/Expensify/App/blob/c1fa2fd46df31e6780e90c0f45769a7b55244473/src/components/ReportActionItem/ReportPreview.tsx#L334-L336
https://github.com/Expensify/App/blob/f30b745af74edac7e1321246afe137bc94d14cdf/src/components/MoneyReportHeader.tsx#L126-L128

### What changes do you think we should make in order to solve the problem?
Add violation check for approve button same as submit button here.
https://github.com/Expensify/App/blob/c1fa2fd46df31e6780e90c0f45769a7b55244473/src/components/ReportActionItem/ReportPreview.tsx#L182
Append `&& !showRTERViolationMessage` here(based of if we want to hide or disable the button)
https://github.com/Expensify/App/blob/c1fa2fd46df31e6780e90c0f45769a7b55244473/src/components/ReportActionItem/ReportPreview.tsx#L334-L336
And Append `&& !hasAllPendingRTERViolations` here(based of if we want to hide or disable the button)
https://github.com/Expensify/App/blob/f30b745af74edac7e1321246afe137bc94d14cdf/src/components/MoneyReportHeader.tsx#L126-L128


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment] 2024-10-08 20:24
[Updated proposal](https://github.com/Expensify/App/issues/50479#issuecomment-2400723113)
added important info in Note section

**Comment by ChavdaSachin** [comment] 2024-10-15 16:44
@hoangzinh I agree we could make changes to `canApproveIOU` function if we only want to make changes to approve button and still let user submit without any restriction.
Curious, do we want to only prevent approvals? or should we prevent submissions as well?

**Comment by Gonals** [comment] 2024-10-17 09:53
> > Curious, do we want to only prevent approvals? or should we prevent submissions as well?
> 
> It's a good call. I will let @Gonals decide on it but in my opinion, because we haven't had an issue with the "submit" button so I think it's fine with the current violation checking for that button 👀 (I'm unsure besides [RTERViolation](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/ReportActionItem/ReportPreview.tsx#L175), do we have any violations that can occur before a requester submit an expense)

Agreed 👍

**Comment by ChavdaSachin** [comment] 2024-10-17 09:56
One more point I missed to inform - the date violation shown in video does not fall under RTERViolations.

**Comment by DylanDylann** [comment] 2024-11-26 05:29
@hoangzinh @Gonals Coming from https://github.com/Expensify/App/issues/52650, with this change, we can't approve/pay hold transactions (partial approve/pay). Is this expected?

**Comment by DylanDylann** [comment] 2024-11-26 12:10
@hoangzinh Hold action will cause violation

**Comment by nkdengineer** [comment] 2024-11-26 16:15
I think it's not expected because we can still approve/pay partially/fully if some transactions are held.

**Comment by mountiny** [comment] 2024-11-27 22:07
Discussing [here](https://expensify.slack.com/archives/C049HHMV9SM/p1732745214338899?thread_ts=1728406913.463479&cid=C049HHMV9SM) unfortunately this issue was created and jumped the gun, the expected behaviour was not agreed on and we should not hide the button just like that. I will revert the changes and we should discuss what change we really want here cc @garrettmknight

**Comment by adelekennedy** [comment] 2024-12-18 01:14
I think we want to close here - but payment is still due

**Comment by adelekennedy** [comment] 2024-12-20 21:58
Upwork payments made - closing

**Closed by adelekennedy** 2024-12-20 21:58 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
