### ISSUE TITLE
Android - Edited emoji messages are clipped and disappearing in Android

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20083] opened 2023-06-02 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in android
2. Go to any chat
3. Send a message consisting only emojis
4. Edit the message
5. Notice the top part of emojis are cut off

## Expected Result:
Message should be displayed in full

## Actual Result:
Top part of the message is clipped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Mobile_Android](https://github.com/Expensify/App/assets/93399543/397eb1fe-2149-4813-8ce8-8c725bb0492d)

https://github.com/Expensify/App/assets/93399543/05dc7a2e-573e-40fe-9f96-3e747d1c05f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @pubudu-ranasinghe
 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684774574460639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by priya-zha** [comment] 2023-06-03 03:41
Dupe of https://github.com/Expensify/App/issues/19605

**Comment by pubudu-ranasinghe** [comment] 2023-06-03 04:06
@priya-zha I reported this bug on May 22nd. Not sure which came first

https://expensify.slack.com/archives/C049HHMV9SM/p1684775756347189

**Comment by priya-zha** [comment] 2023-06-03 04:23
@pubudu-ranasinghe Yes, seems like according to the slack conversation, you have reported this issue first. But according to the GH issue, 19605 was created first. @laurenreidexpensify Can you please check it once. If @pubudu-ranasinghe is the initial reporter, the initial reporter name should be updated on the other issue. Thanks.

**Comment by laurenreidexpensify** [comment] 2023-06-05 09:52
So actually when I reproduce this one I'm getting another behaviour too:

If I have three lines of emojis and go to edit line 2, the entire line disappears 🤔

**Comment by laurenreidexpensify** [comment] 2023-06-05 09:56
Yeah I agree in this case that @pubudu-ranasinghe should get the bounty as they created the issue first. I will close this issue and update on the other issue. Thanks

**Closed by laurenreidexpensify** 2023-06-05 09:56 UTC
Labels: Daily, Bug

**Comment by priya-zha** [comment] 2023-06-05 09:58
Agreed. Thanks.
