### ISSUE TITLE
[$500] Currency list is empty when trying to enter manually while the receipt is scanning

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39022] opened 2024-03-26 22:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.56-1
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Tes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1711375359459619

## Action Performed:

1. Log in with an account on the expensify.com domain (ex: emailaddress@expensify.com)
2. Navigate to a workspace chat
3. Tap grey plus button
4. Choose Request money
5. Scan receipt, save
6. Tap into the expense while the receipt is scanning
7. Tap the amount row
8. Try to change the currency

### NOTE: 
This seems to only occur to users logging in with an expensify.com email address. If you are interested in working on this bug we will provide Onyx data and an expensify.com test account. 

## Expected Result: 
It’s possible to see/change currencies

## Actual Result: 
No currencies are visible

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/89441f8b-af49-41a5-9732-4315cf9a706c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019673dbcd358643b4</li>
        <li>Upwork Job ID: 1773009348580683776</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2024-03-27 15:29
Going ahead and marking this as external. The currency selector seems completely broken. 

@stephanieelliott @akinwale let's make sure we add regression tests at the end of this. It shouldn't be possible to have this happen on prod.

**Comment by JmillsExpensify** [comment] 2024-03-27 15:33
Agree with Puneet. I also realized this morning that I think this issue might originate from a cross currency issue, where the user's default currency is different than the policy currency. Please see [this Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1711375359459619) for more videos.

**Comment by stephanieelliott** [comment] 2024-03-28 21:29
Seems like this is isolated to expensify.com email addresses. I was able to consistently repro on my expensify.com account, but could not repro on gmail.com or expensifail.com. 

I played around with cross currencies, but that didn't seem to have an effect on the currency selector. Specifically, I set my personal workspace to EUR and created a request on a USD workspace and was still able to use the currency selector from a gmail.com account, but not an expensify.com account.

**Comment by stephanieelliott** [comment] 2024-04-03 01:46
Waiting for some proposals on this one

**Comment by trjExpensify** [comment] 2024-04-04 18:35
So strange if this only impacts expensify.com. 🤔

**Comment by stephanieelliott** [comment] 2024-04-08 22:17
I'm still only able to repro this on my expensify.com account, not on any other domains (expensifail, gmail, etc.). Given that its only affecting us internally on one platform I am not going to prioritize it but please comment if you feel differently!

**Comment by stephanieelliott** [comment] 2024-04-09 19:43
OK, @puneetlath does this seem like it can be fixed externally, or does it need to be kept internal? 

 If having an `expensify.com` test account is the only thing keeping it internal it seems silly to block external eng from working on it -- I suppose we could create a test account if one doesn't exist already. Not sure whether back end changes are needed on this so wanted to confirm that first before figuring out a test account.

**Comment by puneetlath** [comment] 2024-04-10 16:03
>OK, @puneetlath does this seem like it can be fixed externally, or does it need to be kept internal?

Not sure! It could be a front-end issue that only we're experiencing for some reason. We could provide onyx data to an external contributor to help them try and figure it out.

**Comment by stephanieelliott** [comment] 2024-04-10 19:32
Ok, cool! I added a note to the issue body about the onyx data, and we'll work under the assumption that this can be fixed externally and will leave the labels as-is. Considering [this discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1712766606854439?thread_ts=1712663027.657479&cid=C01SKUP7QR0) we'll wait for an external contributor to pick this up for now rather than pulling in an expert contrib.

**Comment by mvtglobally** [comment] 2024-04-12 05:35
Issue not reproducible during KI retests. (First week)

**Comment by stephanieelliott** [comment] 2024-04-15 21:55
Waiting for proposals, see [previous comment](https://github.com/Expensify/App/issues/39022#issuecomment-2048294015) for context

**Comment by stephanieelliott** [comment] 2024-04-18 13:41
Waiting for proposals, see https://github.com/Expensify/App/issues/39022#issuecomment-2048294015 for context

**Comment by mvtglobally** [comment] 2024-04-18 16:04
Issue not reproducible during KI retests. (Second week)

**Comment by stephanieelliott** [comment] 2024-04-23 03:34
Waiting for proposals, see https://github.com/Expensify/App/issues/39022#issuecomment-2048294015 for context.

Reapplid the `Bug` label to get another BZ member on this while I am OOO til May 2 which I guess is you @puneetlath! I'll pick this back up when I return but please keep an eye for any movement!

**Comment by mvtglobally** [comment] 2024-04-29 03:13
Issue not reproducible during KI retests. (Third week)

**Comment by puneetlath** [comment] 2024-04-29 17:52
I bet this is actually the same issue as https://github.com/Expensify/App/issues/39455 and it's happening because OpenApp is failing and we aren't getting the currency list. Closing in favor of that issue.

**Closed by puneetlath** 2024-04-29 17:52 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
