### ISSUE TITLE
[$500] iOS - Request Money - No autofocus blink cursor shown after navigating from Scan or Distance

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28062] opened 2023-09-23 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open and log in to app
2. Go to FAB button, request money(Go to Scan or Distance tab, if not already)
3. Go back to LHN and request money again
4. Select Manual tab after page opens on Scan or Distance

## Expected Result:
Amount input should be autofocused and there should be a blinking cursor

## Actual Result:
There is no blinking cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari/ Chrome
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/daa09e2e-c10c-4b3f-b41f-697946b786cf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2f37bccd3b72da4</li>
        <li>Upwork Job ID: 1706334638260056064</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-09-25 15:48
Not overdue, waiting for proposals.

**Comment by isabelastisser** [comment] 2023-09-28 14:35
Not overdue!

**Comment by Talha345** [comment] 2023-10-02 14:49
@isabelastisser Unable to reproduce this issue!

**Comment by isabelastisser** [comment] 2023-10-02 15:44
Thanks @Talha345 and @mollfpr! Closing this now.

**Closed by isabelastisser** 2023-10-02 15:44 UTC
Labels: External, Daily, Help Wanted, Bug
