### ISSUE TITLE
[$500] Android – The splash screen flickering when opening the New Expensify app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38501] opened 2024-03-18 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app.
2. Kill the app and launch it again

## Expected Result:
The splash screen loading without flickering when opening the New Expensify app

## Actual Result:
The splash screen flickering when opening the New Expensify app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/78c64fb7-4d49-4a69-8278-04fabedf623b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01885118131e1618ea</li>
        <li>Upwork Job ID: 1770317729841348608</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by iammudassirali** [comment] 2024-03-20 05:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand involves the splash screen flickering when opening the New Expensify app on Android devices. This flickering effect disrupts the user experience and can be visually unpleasant.

### What is the root cause of that problem?
The root cause of this problem likely lies in the initialization process of the splash screen. It appears that there may be inconsistencies or delays in loading the necessary resources, leading to the flickering effect.

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we should investigate the loading sequence and performance optimizations related to the splash screen. This may involve optimizing resource loading, reducing dependencies, or adjusting the timing of UI rendering to ensure smooth transitions.

### What alternative solutions did you explore? (Optional)
An alternative approach could involve implementing a more streamlined splash screen design that minimizes resource-intensive operations. Additionally, we could explore caching strategies or preloading techniques to improve loading times and reduce flickering.

By addressing the root cause and optimizing the splash screen loading process, we can ensure a seamless and visually appealing experience for users when opening the New Expensify app on Android devices.

Please let me know if you need further assistance or if there are any additional details I can provide.

Best regards,
**Mudassir Ali**

**Comment by ikevin127** [comment] 2024-03-21 18:55
Not able to reproduce!

I tried both on a real android device (OnePlus 7T) and emulator, both locally (dev) with latest main and also used adhoc build of recent main (18h ago) from [here](https://github.com/Expensify/App/pull/38710#issuecomment-2011979371), also tried both regular account and HT account. No dice reproducing this 🤔

**Comment by ikevin127** [comment] 2024-03-23 10:34
@Ollyws +1️⃣

To even achieve the precondition you gotta have Android 14 installed + GBoard keyboard which gives you the option to save credentials for a certain app and use the keyboard autofill functionality.

I have a lead regarding the RCA here and I'm still looking into it, will try and come up with a proposal later today.

**Comment by kadiealexander** [comment] 2024-03-26 04:32
Reached out to Applause to get this tested again.

**Comment by kbecciv** [comment] 2024-03-26 12:37
Issue is reproducible

https://github.com/Expensify/App/assets/93399543/f4202da9-9f21-41af-8345-9b9bc58d759e

**Comment by kadiealexander** [comment] 2024-04-02 05:29
Unable to repro in testflight, have asked a colleague to try repro.

**Comment by jliexpensify** [comment] 2024-04-02 05:49
Tried a few different ways on Pixel 3a (v1.4.58-4) and can't replicate the video in the issue. I see a slight flicker when the splash screen finishes loading, but it's more of a flickering from loading to chats, so not like this issue.

**Comment by kadiealexander** [comment] 2024-04-02 05:55
I think I'm going to close this issue as it's not blocking a core flow, and it's not reliably reproducible. Please reopen if you disagree!

**Closed by kadiealexander** 2024-04-02 05:55 UTC
Labels: External, Daily, Help Wanted, Bug
