### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Chat - Mentioning a user in new offline conversation displays user picker transparent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27036] opened 2023-09-08 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Turn off the connection
3. Click FAB icon and select/start new chat
4. Type @

## Expected Result:
The suggestion list shows custom avatars for users that have them

## Actual Result:
The suggestion list is shown transparent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dac275b3-5907-4ec7-9830-ed5c1408b83c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ab2a548d85f3dca</li>
        <li>Upwork Job ID: 1700212174202789888</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-09 23:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mention suggestions displays in a transparent popup in new offline conversation

### What is the root cause of that problem?

In [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ReportActionCompose.js), [OfflineWithFeedback](https://github.com/Expensify/App/blob/main/src/components/OfflineWithFeedback.js) component wraps all the children. `OfflineWithFeedback` component has opacity(0.5) in offline state for pending report.
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/styles/styles.js#L2965

Suggestions are children of this component and so opacity is applied to suggestions as well.
This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to use `React.createPortal` to avoid opacity inheritance.
As you can see below, we have already this function in `AutoCompleteSuggestions` component
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/AutoCompleteSuggestions/index.js#L58

We changed the `parentContainerRef` props to `measureParentContainer` props in [this PR](https://github.com/Expensify/App/pull/25758) but this change was applied only to `propTypes` and parent components. Those changes were not applied to `AutoCompleteSuggestions` component itself.

In order to fix this, the following replacements are needed
https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/AutoCompleteSuggestions/index.js#L17
```
function AutoCompleteSuggestions({measureParentContainer, ...props}) {
```

https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/AutoCompleteSuggestions/index.js#L39-L44
```
    React.useEffect(() => {
        if (!measureParentContainer) {
            return;
        }
        measureParentContainer((x, y, w) => setContainerState({left: x, bottom: windowHeight - y, width: w}));
    }, [measureParentContainer, windowHeight, windowWidth]);
```

https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/AutoCompleteSuggestions/index.native.js#L5
```
function AutoCompleteSuggestions({measureParentContainer, ...props}) {
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/5df32761-63cd-4a11-8093-da1c5c1f6692


</details>


### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-09-11 15:16
@rushatgabhane could you review the proposals here?

**Comment by lschurr** [comment] 2023-09-15 15:06
Shoot, I missed this. Adding Eng now.

**Comment by lschurr** [comment] 2023-09-18 08:19
Bump @techievivek

**Comment by s-alves10** [comment] 2023-09-18 14:55
@rushatgabhane 

May I ask you a question? I have found that my solution won't work on native platforms. As you know, we can't use portal for native platforms

Looks like we need other ways for natives

**Comment by lschurr** [comment] 2023-10-09 17:29
@rushatgabhane could you complete the checklist for this one?

**Comment by lschurr** [comment] 2023-10-09 17:31
Payment summary:

- Bug reporter: Applause (no payment needed)
- Contributor: @s-alves10 $500
- Contributor+: @rushatgabhane $500

**Comment by lschurr** [comment] 2023-10-09 17:33
@s-alves10 could you accept the offer in Upwork (https://www.upwork.com/nx/wm/offer/26729370)

**Comment by s-alves10** [comment] 2023-10-09 17:37
@lschurr 

Accepted. Thanks

**Comment by lschurr** [comment] 2023-10-13 15:24
Waiting on the checklist.

**Comment by techievivek** [comment] 2023-10-16 10:51
Gentle bump @rushatgabhane to complete the above checklist.

**Comment by lschurr** [comment] 2023-10-18 15:30
Are you still working on that checklist @rushatgabhane or are we good to close this one?

**Closed** 2023-10-23 15:20 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
