### ISSUE TITLE
Contact methods - Not here page opens after adding existing contact and dismissing error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48450] opened 2024-09-03 09:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://github.com/Expensify/App/pull/48320
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Go to Profile > Contact methods.
4. Click New contact method.
5. Enter an existing email > Next.
6. Enter magic code > Next.
7. Click on the added existing email.
8. Click X button.

## Expected Result:
App will return to the previous page after dismissing the error.

## Actual Result:
Not here page opens after adding existing contact and dismissing error.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bc613b9d-f777-4828-af6c-15515511bad6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01263340c168620229</li>
        <li>Upwork Job ID: 1830946896292368627</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by MariaHCD** [comment] 2024-09-03 10:45
This looks like a regression from https://github.com/Expensify/App/pull/48320

@hungvu193 @mollfpr can you handle the fix for this since we're still in the regression period.

**Comment by MariaHCD** [comment] 2024-09-03 10:47
Oh, actually from this comment, we already identified this bug before merging: https://github.com/Expensify/App/pull/48320#pullrequestreview-2276120479

> @getusha Could you look into the fixing the navigation when the user removes the optimistic login? The page goes to not found page because the contact method is in the URL. I think we need to redirect to the contact method list page

**Comment by MariaHCD** [comment] 2024-09-03 10:47
@getusha Let's fix this as a follow up improvement :)

**Comment by hungvu193** [comment] 2024-09-03 10:48
> This looks like a regression from https://github.com/Expensify/App/pull/48320
> 
> 
> 
> @hungvu193 @mollfpr can you handle the fix for this since we're still in the regression period.

Please assign me and @getusha. We will handle this one

**Comment by mountiny** [comment] 2024-09-15 23:11
I think so yes

**Closed by mountiny** 2024-09-15 23:11 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
