### ISSUE TITLE
[HOLD for payment 2024-01-25] [HOLD for payment 2024-01-24] [$250]  Android - The center photo is blank in edit avatar page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34500] opened 2024-01-15 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile
2. Tap on the avatar
3. Upload any photo

## Expected Result:
The center photo is visible in edit avatar page

## Actual Result:
The center photo is blank in edit avatar page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/10c2f81e-95ca-4557-a2da-f9b303807888

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bd04ea8566e3d10</li>
        <li>Upwork Job ID: 1746941371136151552</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28102515</li>
<li>s-alves10 | Contributor | 28102516</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @conorpendergrast</details>

**Comment by neil-marcellini** [comment] 2024-01-15 15:32
I have to stop and drive for 1h, I'll get to this as soon as I'm back.

**Comment by s-alves10** [comment] 2024-01-15 17:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Center circle image is filled with app background color instead of transparent in the avatar crop modal.

### What is the root cause of that problem?

We use `fill` props in `ImageCropView` as you can see below
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/components/AvatarCropModal/ImageCropView.js#L93

This is the root cause

### What changes do you think we should make in order to solve the problem?

Simply removing fill props would solve the issue

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/7e950653-05d3-4ce6-a118-67bdeb53a5a1)

</details>

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-15 17:23
@s-alves10 do you know which PR caused this?

**Comment by s-alves10** [comment] 2024-01-15 17:25
@situchan I think this is reproducible in production as well. Can you take a look?

**Comment by s-alves10** [comment] 2024-01-15 17:25
@situchan I think this is reproducible in production as well. Can you take a look?

**Comment by situchan** [comment] 2024-01-15 17:28
At least not happening on playstore app (v1.4.24-8)

**Comment by situchan** [comment] 2024-01-15 17:45
> @situchan Can you check if this is coming from RN upgrade?

I have no way to check quickly since android build takes time.
Removing `fill` works well but asked [here](https://github.com/Expensify/App/pull/33607/files#r1452634498) for confirmation

**Comment by shubham1206agra** [comment] 2024-01-15 17:48
I am the author there. We cannot remove fill there actually. But I am confused why fill will cause this problem.

**Comment by s-alves10** [comment] 2024-01-15 17:49
@shubham1206agra Why do you think we should not remove fill? Can you please explain a bit?

Also please check this issue https://github.com/expo/expo/issues/21530#issuecomment-1836283564
cc @situchan

**Comment by shubham1206agra** [comment] 2024-01-15 17:50
@s-alves10 See https://github.com/Expensify/App/pull/33607/files#r1452637167

**Comment by shubham1206agra** [comment] 2024-01-15 17:55
If you confirm the root cause to be RN upgrade, best solution would be to downgrade `expo-image`.

**Comment by Pujan92** [comment] 2024-01-15 17:57
I am not able to reproduce it.
Version - v1.4.25-2 Develop

![Screenshot_1705341317](https://github.com/Expensify/App/assets/14358475/07237e4e-424c-404e-a76d-9bf63e2b6523)

**Comment by situchan** [comment] 2024-01-15 17:57
@Pujan92 this is android-only bug

**Comment by Pujan92** [comment] 2024-01-15 17:59
> @Pujan92 this is android-only bug

Tested & shared android emulator SS only.

**Comment by situchan** [comment] 2024-01-15 18:00
I understand the concern of mask background color in light theme after removing `fill` but at least this should unblock the deploy.
If @neil-marcellini agrees, I am inclined to do that.

<img width="380" alt="Screenshot 2024-01-15 at 11 58 44 PM" src="https://github.com/Expensify/App/assets/108292595/bd20ae4f-2b19-47f1-8383-87aef2a04ebe">
<img width="380" alt="Screenshot 2024-01-15 at 11 58 55 PM" src="https://github.com/Expensify/App/assets/108292595/111d6ded-6728-48c5-a770-73aadf500437">

**Comment by shubham1206agra** [comment] 2024-01-15 18:01
@situchan Would you like to test this solution https://github.com/expo/expo/issues/23407#issuecomment-1747772206?

**Comment by shubham1206agra** [comment] 2024-01-15 18:06
@situchan Probably this is the solution https://github.com/expo/expo/pull/26323.

**Comment by situchan** [comment] 2024-01-15 18:12
If Expo team takes care of those issues and they will be fixed in upcoming expo version, I am fine with temporary solution for now with `// TODO: remove` comment.

**Comment by neil-marcellini** [comment] 2024-01-15 18:15
> @situchan Probably this is the solution [expo/expo#26323](https://github.com/expo/expo/pull/26323).

Could one of you please test and verify that this is the solution which works for light and dark mode? Would you also please update your proposal and include a root cause explanation?

**Comment by shubham1206agra** [comment] 2024-01-15 18:19
> > @situchan Probably this is the solution [expo/expo#26323](https://github.com/expo/expo/pull/26323).
> 
> Could one of you please test and verify that this is the solution which works for light and dark mode? Would you also please update your proposal and include a root cause explanation?

I am not sure right now about this.

> If Expo team takes care of those issues and they will be fixed in upcoming expo version, I am fine with temporary solution for now with `// TODO: remove` comment.

@neil-marcellini I think we should do this right now. Comment the fill line and add TODO for the time.

**Comment by neil-marcellini** [comment] 2024-01-15 18:22
Ok, I'm fine with commenting out the fill as suggested in [this proposal](https://github.com/Expensify/App/issues/34500#issuecomment-1892548562), but I'm still confused about the root cause. What introduced the bug? I assumed it worked when the fill prop was first added? Is there a PR we can revert?

**Comment by situchan** [comment] 2024-01-15 18:23
I think this is regression from expo-image version bump.
We already had tons of similar issues when expo-image was first introduced. All (or most) of them were fixed by removing `fill` prop.

**Comment by neil-marcellini** [comment] 2024-01-15 18:26
Ok, I'm going to assign @s-alves10 then. Thanks!

**Comment by neil-marcellini** [comment] 2024-01-15 19:35
@s-alves10 please let me know when you have a PR ready

**Comment by s-alves10** [comment] 2024-01-15 19:37
@neil-marcellini Almost done. I am facing some issues in ios build now and trying to solve

**Comment by s-alves10** [comment] 2024-01-15 20:16
@situchan I'm facing an ios build issue. Can you please check https://expensify.slack.com/archives/C01GTK53T8Q/p1705348573543579?

**Comment by mountiny** [comment] 2024-01-16 11:33
@s-alves10 @situchan Can you confirm this is fixed on the latest Android staging? I dont have android device

**Comment by situchan** [comment] 2024-01-16 11:34
Please share android staging apk. Android is the only platform we don't have access for staging build.

**Comment by mountiny** [comment] 2024-01-16 14:13
@situchan confirmed the fix on android

**Comment by neil-marcellini** [comment] 2024-01-29 18:17
@conorpendergrast would you please handle payment here?

**Comment by conorpendergrast** [comment] 2024-01-29 21:10
Gladly!

**Comment by conorpendergrast** [comment] 2024-01-29 21:12
Payouts due:

- [ ] Contributor: $250 @s-alves10 - [Contract](https://www.upwork.com/nx/wm/workroom/36059135/overview)
- [ ] Contributor+: $250 @situchan - [Contract](https://www.upwork.com/nx/wm/workroom/36043153/overview)

Upwork job is [here](https://www.upwork.com/jobs/~013bd04ea8566e3d10).

**Comment by conorpendergrast** [comment] 2024-01-29 21:18
This was caught in a regression test by Applause, but I don't see that we have a clear idea of where this regression happened. 

@situchan thoughts?

**Comment by situchan** [comment] 2024-01-29 21:28
This came from expo-image upgrade. It was upstream issue which couldn't be handled by us.
The issue won't likely to be happen in the future once we settle the expo version which fixes all these image related issues.

**Comment by conorpendergrast** [comment] 2024-01-29 22:02
Alright, sounds good. Closing out, thanks!

**Closed by conorpendergrast** 2024-01-29 22:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment
