### ISSUE TITLE
Request money - web and app do not get updated simultaneously on money request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22816] opened 2023-07-13 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Search for a email on new Expensify app
2. Open the chat
3. Tap on money request and request the amount
4. Now go to chrome and open the website staging.new.expensify.com

## Expected Result:
The same data (money request) should be updated on the web too for the same account

## Actual Result:
The web shows inconsistency as no data of money request is updated here

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/38400c7c-99ac-4598-a385-b81de87a4c9a

https://github.com/Expensify/App/assets/93399543/c19a9347-ebc6-4d0e-9144-a8a8f963f7be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakshixwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689175023465339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-07-18 17:30
Here's a side by side showing the same account in the app and in web. You can see that four money request show in app but are missing from web (the ones with the red and dark blue avatars). But there are two money requests showing both places (light blue avatars):

<img width="1152" alt="Untitled" src="https://github.com/Expensify/App/assets/5997400/2a529c0f-8b48-410d-ad2e-00dcc12382d8">

I'm not sure what the difference is between the ones that show and the ones that don't.

**Comment by sakshixwani** [comment] 2023-07-18 18:21
This bug was actually a bug as it was reproduced by applause team as well, but it's not occurring now so maybe this got fixed due to any other PR. 
So am I eligible for reporting bonus?

**Comment by sakluger** [comment] 2023-07-20 23:22
Hey @sakshixwani - thanks for confirming that it's fixed. If this issue was fixed in another issue, that means that this issue (or another similar issue with the same root cause) would have already been reported earlier, so we wouldn't pay out for that.

**Closed by sakluger** 2023-07-20 23:22 UTC
Labels: Daily, Overdue, Bug

**Comment by sakshixwani** [comment] 2023-08-08 15:13
Hu
