### ISSUE TITLE
Jerky animation when swiping back from transaction thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43498] opened 2024-06-11 15:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718060219976609
## Action Performed:
1. Create a money request to a workspace chat
2. Navigate to the transaction thread
3. Swipe right to go back to the parent chat

## Expected Result:
Animation is smooth and not jerky
## Actual Result:
Animation is jerky. 
NOTE : It is hard to reproduce. Depends on how fast and far we swipe

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
Try swiping until the point marked in the screenshot 

<img src="https://github.com/Expensify/App/assets/38435837/744757cd-f2bd-404b-a1de-840cd8a5676b" width="40%" height="40%">

https://github.com/Expensify/App/assets/38435837/613ad621-402e-429d-8aee-aa9c4407ed88

https://github.com/Expensify/App/assets/38435837/d5573843-ba09-4375-95c8-9e2fa3597f26

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2024-06-12 17:14
I have not been able to recreate either, as it was smooth for me each time:

https://github.com/Expensify/App/assets/10926327/f375823f-c800-463b-97f5-94821f43c9f0

I am going to put `retest weekly` on this to see if they can recreate more consistently 👍

**Comment by CortneyOfstad** [comment] 2024-06-17 17:49
Not overdue — waiting to see if this can be recreated via QA

**Comment by CortneyOfstad** [comment] 2024-06-19 19:17
Not overdue as we're still waiting for this to be tested by QA

**Comment by mvtglobally** [comment] 2024-06-20 14:22
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-06-25 15:21
I also am still not able to reproduce, so going to close this!

**Closed by CortneyOfstad** 2024-06-25 15:21 UTC
Labels: Daily, Overdue, Bug, retest-weekly
