### ISSUE TITLE
[$500] Unread message received as soon as signed up for new account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33812] opened 2024-01-01 00:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703804718154029
## Action Performed:
1. Sign up for a new account
2. Check the inbox

## Expected Result:
unread message summary only come after having been unread for >10 min.

## Actual Result:
Received as soon as signed up for new account and even before validating the account.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - Expensify Chat between Concierge and mnata utest+3112mn@gmail com -](https://github.com/Expensify/App/assets/38435837/94536883-e315-46e7-964f-5b0d07058b0d)

![image (3)](https://github.com/Expensify/App/assets/38435837/10b31556-b4cb-41a5-ad48-06b48c9ac50b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b78af7164162d4c4</li>
        <li>Upwork Job ID: 1741613970025455616</li>
        <li>Last Price Increase: 2024-01-01</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-01 00:18
This is a backend issue and should be handled internally.

**Comment by Christinadobrzyn** [comment] 2024-01-02 18:25
I think this can be part of VIP-VSB - adding that as a project. I agree, I think this needs to be internal - updating the labels.

**Comment by Christinadobrzyn** [comment] 2024-01-03 19:21
Adding eng label to review this and see if it needs to state internal.

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:07
I'm going to be ooo for a week so adding a teammate to monitor this while I'm gone.

**Comment by muttmuure** [comment] 2024-01-15 16:45
Is this definitely a problem? I'm not sure I understand why we would change this

**Comment by muttmuure** [comment] 2024-01-15 16:45
Oh it's because of the 10 minute activity

**Comment by muttmuure** [comment] 2024-01-15 16:46
Still, I'm not convinced it's actually a problem - so I would vote to close this in favor of higher priorities.

**Comment by puneetlath** [comment] 2024-01-15 17:39
I think perhaps we aren't waiting 10 min for any messages. Not just the first one. For example this one: 

<img width="1195" alt="image" src="https://github.com/Expensify/App/assets/1371996/d5b2f650-fc70-4b74-a8e5-943d6f828f2d">
<img width="344" alt="image" src="https://github.com/Expensify/App/assets/1371996/299b8a7c-c48c-4e50-8dbf-d64b375cfcbc">

**Comment by muttmuure** [comment] 2024-01-17 18:34
Oh I see - I wonder what changed that? Reliable updates?

**Comment by puneetlath** [comment] 2024-01-17 18:49
I'm not sure! It shouldn't be that, but anything is possible.

**Comment by deetergp** [comment] 2024-01-19 20:39
I'm not able to reproduce this locally… The only notification that is queued throughout the process is the magic sign-in. Am I holding it wrong?

**Comment by muttmuure** [comment] 2024-01-22 13:58
Did you receive Concierge messages at all?

**Comment by deetergp** [comment] 2024-01-22 22:56
Locally, all I got was the magic sign-in notification. But I just tested it on prod and did immediately get the chat notification before I plugged in the magic sign in key. Will keep fiddling with it to try to make it happen locally.

**Comment by deetergp** [comment] 2024-01-25 01:09
Apparently we have a beta that let's us disable the offline activity notifications for larger customers, and all betas are enabled by default in local dev.

**Comment by Christinadobrzyn** [comment] 2024-01-29 20:36
working on the proposal/troubleshooting the issue

**Comment by deetergp** [comment] 2024-01-31 00:09
This behavior appears to be intentional and not a bug https://github.com/Expensify/Web-Expensify/blob/eb6a76f365bdbae37f6cdd8cdb6a9c2261053f67/lib/ReportUtils.php#L2577-L2581

That block was last changed [here](https://github.com/Expensify/Web-Expensify/pull/39984) back in December but it appears that the notify immediately portion has been around for a while.

Do we still want to change it?

**Comment by Christinadobrzyn** [comment] 2024-02-01 00:19
It does seem a little odd to get a message so quickly to signing up with a new account but since the current behaviour is expected maybe we should either table this to focus on other jobs? Or make this a monthly low-priority internal project? 

Happy to bring this convo/question to the team if you think that would be good?

**Comment by deetergp** [comment] 2024-02-01 20:05
@puneetlath @muttmuure Any thoughts about this being needing to change what appears to be intended functionality?

**Comment by deetergp** [comment] 2024-02-01 20:38
@Christinadobrzyn I'm on the fence about it for sure, but agree that it probably isn't the most important thing. Let's let Matt & Puneet chime in and I'll demote it to Weekly for the time being.

**Comment by muttmuure** [comment] 2024-02-05 16:22
I am inclined to say this isn't tied to any wave, and is actually somewhat beneficial since it demos the email summaries to a new user on NewDot.

**Comment by muttmuure** [comment] 2024-02-05 16:23
Please reopen if you disagree.

**Closed by muttmuure** 2024-02-05 16:23 UTC
Labels: Engineering, Daily, Internal, Bug
