### ISSUE TITLE
[HOLD for payment 2024-01-26] Status - Tooltip Not Displayed Upon Clicking Chevron in the Status Section

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33683] opened 2023-12-28 00:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Sign in to staging Expensify
2, Navigate to Settings > Profile > Status
3, Hover over the message icon or down the chevron icon. Note the tooltip displaying "Emoji" pops up
4, Click the down chevron to open the emoji section
5, Click again to close the emoji section
6, Hover over the message icon or down chevron and observe that the tooltip is not displayed

## Expected Result:
When the down chevron is clicked again to close the modal, the tooltip should be displayed upon hovering over the down chevron

## Actual Result:
When we click the down chevron again to close the modal, the tooltip does not appear when hovering over the down chevron

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eea55856-f7d9-4faf-8faf-3ed3b01fda89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-12-28 01:10
Not worth blocking the deploy over.

**Comment by shubham1206agra** [comment] 2023-12-28 03:57
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Status - Tooltip Not Displayed Upon Clicking Chevron in the Status Section

### What is the root cause of that problem?

Offending PR - https://github.com/Expensify/App/pull/33537

This is happening due to we are making wrong thing as null (instead of element, we are making whole ref as null) on closing the EmojiPicker, due to which we are not closing the EmojiPicker properly, and `isOpen` in PopoverContext remains `true` in this case.

### What changes do you think we should make in order to solve the problem?

Use `getEmojiPopoverAnchor().current = null;` instead of `emojiPopoverAnchorRef.current = null;` in `hideEmojiPicker` method.

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2023-12-28 06:17
As this is coming from my PR, I have opened a new [PR](https://github.com/Expensify/App/pull/33690) to fix this. The issue explanation is [here](https://github.com/Expensify/App/pull/33690#issuecomment-1870860197).

**Comment by peterdbarkerUK** [comment] 2024-01-31 11:17
PR is deployed and rolling fine - as it is a fix to a previous PR that was also implemented by @bernhardoj and reviewed by @aimane-chnaif, I believe no payment is necessary here. Correct?

**Closed** 2024-02-03 00:18 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
