### ISSUE TITLE
[HOLD for payment 2023-06-21] mWeb - Workspaces are not immediately displayed when transitioning from OD to ND

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20275] opened 2023-06-06 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to OD and log in with an account that has a existing workspace
2. Click on Create a company for free

## Expected Result:
The user is redirected to the Workspaces list in NewDot and all existing workspaces are displayed

## Actual Result:
The user is redirected to NewDot Create a Workspace screen but the existing workspaces are not displayed immediately, it takes >10 seconds to load 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4

**Reproducible in staging?:** Yes 
**Reproducible in production?:** No - New flow introduced in this PR https://github.com/Expensify/App/pull/20112

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/44479856/9e582b61-ba04-401b-8cc3-27ae87307b8f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2023-06-06 16:15
@francoisl @srikarparsi assigning you since it looks like it coming from this PR https://github.com/Expensify/App/pull/20112#issuecomment-1578994733

**Comment by francoisl** [comment] 2023-06-06 17:14
Yeah, this is also how it works on production. The delay is indeed probably because the app has to load workspaces data. As an improvement, we can look into keeping the loading indicator visible while the data is loading, but it's not a blocker / regression.


Production | Staging
--- | ---
<video src="https://github.com/Expensify/App/assets/2229301/fa29d8fb-1726-44f2-a5bf-bdc6f9d8e47c"/> | <video src="https://github.com/Expensify/App/assets/2229301/e358e19b-eadd-488d-a74a-c4227b154f1f" />

**Comment by kevinksullivan** [comment] 2023-06-09 01:22
@francoisl is this a broader performance issue? Should we be tackling it here?

**Comment by francoisl** [comment] 2023-06-09 18:31
This is just a "visual" issue if you will, we're showing the wrong state of the workspaces list page while data is still loading. I'll handle internally.

**Comment by mollfpr** [comment] 2023-06-12 16:26
@francoisl @kevinksullivan Could you assign the issue to me since I got assigned to the PR? Thanks!

**Comment by kevinksullivan** [comment] 2023-06-16 14:27
@mollfpr offer sent

https://www.upwork.com/jobs/~01147597d87da7cb51

**Comment by mollfpr** [comment] 2023-06-21 17:17
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is a visual improvement while transitioning.

>  [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>  [@mollfpr] Determine if we should create a regression test for this bug.

Yes!

> [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**_Only available for web/mWeb_**

1. Make sure you're signed out of NewDot
2. On OldDOt, sign in to an account that has at least 1 existing workspace
3. After entering your magic code / OTP, tap on "Set up my company for free"
4. **Verify** A new tab opens to NewDot, and you get automatically signed in
5. **Verify** you do not see the "Create a new workspace" view for a brief moment before your existing workspaces get listed
6. 👍 or 👎

**Comment by francoisl** [comment] 2023-06-21 18:11
👍  but small correction, this flow only happens on mobile web – not web, so the regression steps also only apply to mobile web.

**Comment by mollfpr** [comment] 2023-06-21 18:14
Updated the test proposal. Thanks for the correction @francoisl 👍

**Comment by francoisl** [comment] 2023-06-26 17:50
Internal issue for regression testing opened [here](https://github.com/Expensify/Expensify/issues/295030). @kevinksullivan can you take care of payment so we can close this please?

**Comment by kevinksullivan** [comment] 2023-06-26 23:16
All set

**Closed by kevinksullivan** 2023-06-26 23:16 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
