### ISSUE TITLE
[$250] New draft reports and additional expenses added to a draft report will not mark a workspace chat unread

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49184] opened 2024-09-13 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1725978630280069?thread_ts=1725864497.268339&cid=C06ML6X0W9L

## Action Performed:

1. Create a workspace
2. Invite a submitter and approver
3. Enable approvals setting approver
4. Enable Delay submissions
5. As the approver, navigate to the submitter's workspace chat and mark as read if it's unread + navigate to another chat
6. Create an expense as the submitter

## Expected Result:
The Submitter's workspace chat is not unread when they create a new draft report.

## Actual Result:
The submitter's workspace chat is marked unread when they create a new draft report.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834641825011202120</li>
        <li>Upwork Job ID: 1834641825011202120</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by FitseTLT** [comment] 2024-09-13 17:33
@garrettmknight Can you upload a vid? It isn't clear. I see it gets unread for the first expense the submitter creates but for the second expense of course it doesn't get unread as for the second expense a report action will only be created for the iou report; not to the workspace chat because until the report is submitted the expenses will be inserted in to the same expense report.

**Comment by sandipanghos** [comment] 2024-09-14 14:41
@garrettmknight @FitseTLT can you confirm if as per the business the expense on  draft report should be in read state?

**Comment by puneetlath** [comment] 2024-09-16 20:00
I would think this probably also needs a back-end update. That we'll need to update how this works optimistically, but also from the back-end.

**Comment by FitseTLT** [comment] 2024-09-16 20:11
@puneetlath I need an answer [here](https://github.com/Expensify/App/issues/49184#issuecomment-2349588596) as it can potentially be a [dupe](https://github.com/Expensify/App/issues/37315).

**Comment by garrettmknight** [comment] 2024-09-20 13:17
Just confirmed that additional expenses don't mark unread, it's just new draft reports. Updating OP.

**Comment by FitseTLT** [comment] 2024-09-20 19:22
The expected result is illogical our current behaviour is the correct one because users should be informed, by marking the workspace chat unread, that there is a new draft report.

**Comment by VictoriaExpensify** [comment] 2024-09-24 05:29
@FitseTLT I think the issue is that the Workspace chat should be shown as Unread when there is new information/messages the user is not aware of. As the creator of the expense, the submitter's workspace chat does not need to be marked as unread because there is nothing they need to be notified of.

@garrettmknight please correct me if I have that wrong

**Comment by VictoriaExpensify** [comment] 2024-09-24 05:30
Not overdue

**Comment by FitseTLT** [comment] 2024-09-24 19:17
> @FitseTLT I think the issue is that the Workspace chat should be shown as Unread when there is new information/messages the user is not aware of. As the creator of the expense, the submitter's workspace chat does not need to be marked as unread because there is nothing they need to be notified of.
> 
> @garrettmknight please correct me if I have that wrong

@VictoriaExpensify It is confusing. From the OP, it seems the expected result is from the approver's side and what I am opposing is making the workspace chat as read from the approver's side. But if the OP is for the submitter's side it is the current behaviour of the app as it will open the workspace chat when you submit the expense it is not unread.
I think it would be very helpful if we can upload a video in the OP. @garrettmknight

**Comment by JKobrynski** [comment] 2024-10-08 08:14
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment] 2024-10-10 12:10
I wanted to confirm one thing, what do you mean by "chat is not unread"? I followed the reproduction steps, and this is what I am seeing 

![Screenshot 2024-10-10 at 11 08 56](https://github.com/user-attachments/assets/37217db5-bbac-4238-a24c-0c6bd24cef62)

The chat name (it's the submitter's email) is in bold font, but there is no green dot next to it that would indicate there is something to read. Is that the issue?

**Comment by JKobrynski** [comment] 2024-10-11 12:54
The reason this happens is because even though there is a draft "comment" (expense) in the report, the `reportDraftComment_<id>` Onyx key is empty. I will continue my investigation to find out why that's the case. It might be a missing backend update, but I will have to confirm it.

**Comment by jasperhuangg** [comment] 2024-10-11 17:41
>  I think this issue will get swallowed up by the proposed changes to the unread summary handling and what not. Do you want to take this over? close it and handle it elsewhere? or provide more direction on what we want to do in this issue, so it's not conflicting the plan?

I think we probably just shouldn't tackle this right now since it seems like whatever we do here could wind up getting undone by the expense submission notification improvements project.

**Closed by jasperhuangg** 2024-10-11 17:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
