### ISSUE TITLE
[HOLD for payment 2023-11-09] [$1000] Setup sorted import aliases

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20531] opened 2023-06-09 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from [this slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1686294390822009), this issue is just a DX / code beautification thing, and thus should be treated an non-urgent / low priority.

### Problem
When writing code for the new Expensify app, our goal is to provide developers with a positive coding experience, enhancing their joy and productivity.
The most commonly used development tool is Visual Studio Code (VSCode). However, VSCode often struggles to suggest imports for custom Expensify components. As a result, developers have to manually type the import path. Since the components they are working on are often nested in various folders, they have to guess the number of directories they need to go up to import the desired component ("Do I need to go up three directories like ../../../ or just two?"). This unnecessary cognitive load distracts developers from their actual tasks. Furthermore, the cluttered import paths are difficult to read and comprehend (see the first picture).

### Solution

Take a look at the second picture and let your heart decide which version appears cleaner to you. The proposed solution is called import alias.
We can configure the bundlers to use "shortcuts" to directories when resolving imports. Additionally, we can instruct ESLint to prioritize the use of these shorter import aliases, ensuring automatic detection during development.
Next time you need to use an Expensify component, such as <Avatar />, you can simply import it swiftly using the following syntax:
import Avatar from "@components/Avatar"
(Future note: once we integrate typescript VSCode should be able to resolve all import paths, and thus it will suggest us to import the component from @components/Avatar )

|Before|After|
|---|---|
|![image](https://github.com/Expensify/App/assets/47436092/8ab6dbbb-e92e-4e6d-824c-0b105ed8aa4a)|![image](https://github.com/Expensify/App/assets/47436092/576d7b17-d2fc-4273-b6f9-8bd8ed258a01)|

Furthermore, let's setup an (auto-fixable by Prettier) sort-imports lint rule, to make it look like this:

![image](https://github.com/Expensify/App/assets/47436092/281c4b87-bc04-4ad5-8667-874412573ddf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1a5b3c310973924</li>
        <li>Upwork Job ID: 1697273497918955520</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26446972</li>
<li>b4s36t4 | Contributor | 26446976</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-09 17:06
This is more of a developer-experience optimization, not really a new feature.

**Comment by hannojg** [comment] 2023-06-09 17:20
👋

**Comment by roryabraham** [comment] 2023-06-29 02:41
:givplz:

**Comment by hannojg** [comment] 2023-08-31 12:42
@roryabraham can we reopen this issue?

**Comment by hannojg** [comment] 2023-08-31 12:59
(I am fine with someone else picking up this issue!)

**Comment by talhatahir** [comment] 2023-08-31 13:12
Contributor details
Your Expensify account email: talha.artefakt@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015846522c20c0484f

**Comment by talhatahir** [comment] 2023-08-31 13:13
@hannojg Can you please assign this to me.

**Comment by talhatahir** [comment] 2023-08-31 13:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enhance developer experience by using import aliases where the relative paths exceed a certain limit.

### What is the root cause of that problem?
There are no import aliases defined in tsconfig.json or jsconfig.json

What changes do you think we should make in order to solve the problem?
Would need to add aliases for `tsconfig.json` and babel. Might need to add it for `jsconfig.json` too since the code is not fully migrated to typescript.

Once done: 
BEFORE :
`import * as Expensicons from '../../../../components/Icon/Expensicons';`

AFTER:
`import * as Expensicons from '@components/Icon/Expensicons';`

**Comment by b4s36t4** [comment] 2023-08-31 13:48
If this is up, I would love to give it a go.

We're not fully typescript repo yet, but even after we don't have to do.

To solve this issue all we need to do is add a `resolve` section in webpack config.

Reference related to my proposal -> https://webpack.js.org/configuration/resolve/ for alias config.
https://github.com/trivago/prettier-plugin-sort-imports - For import sorting as per description.

Although this isn't a strigt forward proposal, I want you to guys to consider this as same, please.!

**Comment by situchan** [comment] 2023-08-31 14:22
For contributors: can you please also add solution for this to your proposals?

<img width="745" alt="sort" src="https://github.com/Expensify/App/assets/108292595/99440660-9ee9-487a-8273-3d76d6f10605">

**Comment by b4s36t4** [comment] 2023-08-31 14:24
> https://github.com/trivago/prettier-plugin-sort-imports - For import sorting as per description.

```json
"importOrder": ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
  ```
These 3 keys are useful for solve the above one.

@situchan

**Comment by situchan** [comment] 2023-08-31 14:24
And each import should be linkable to the correct file on Cmd+Click

**Comment by b4s36t4** [comment] 2023-08-31 14:47
https://github.com/Expensify/App/assets/59088937/6827b34c-b5d1-4a47-ba4a-fd28bc09f075


https://github.com/Expensify/App/assets/59088937/42447bb4-e145-4435-9b99-94259aac9702


@situchan demo videos for the web bundling & Intellisense both are working perfect.

The above demo uses webpack resolve options, but we're using babel https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/config/webpack/webpack.common.js#L123

This way I don't think we need two configs one in babel and webpack. We can simply do it in babel.config.js alias section where we use module resolver plugin.

**Comment by b4s36t4** [comment] 2023-08-31 14:47
Hope you're the C+ 😅 sorry for the ping.

**Comment by situchan** [comment] 2023-08-31 14:51
yeah I am not C+ yet on this GH 😄, though interested and would like to review this one

**Comment by b4s36t4** [comment] 2023-08-31 15:14
<img width="1146" alt="Screenshot 2023-08-31 at 8 44 05 PM" src="https://github.com/Expensify/App/assets/59088937/64b23d8d-4a87-4132-a573-10c9a9bac147">

Demo of sorting imports & the update config.

```json
module.exports = {
    tabWidth: 4,
    singleQuote: true,
    trailingComma: 'all',
    bracketSpacing: false,
    arrowParens: 'always',
    printWidth: 190,
    singleAttributePerLine: true,
    importOrder: ['^@components/(.*)$', '^[./]'],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
    plugins: ['@trivago/prettier-plugin-sort-imports'],
};
```

**Comment by pradeepmdk** [comment] 2023-08-31 15:30
@situchan @hannojg 
For my proposal  https://github.com/Expensify/App/issues/20531#issuecomment-1701007323 

for redirecting to a specific file
https://github.com/Expensify/App/assets/16595846/8303ab8f-583a-4909-a86e-211c7b226a78
for autosuggestion
https://github.com/Expensify/App/assets/16595846/fcbd1575-036a-4359-bfcd-7b9f2fd4491f

**Comment by roryabraham** [comment] 2023-08-31 15:44
Making this external with @situchan as C+ and myself as CME. This is a lower priority issue and don't want it to distract too much from more important roadmap issues, so I made it Weekly instead of Daily for now. This will be a nice QOL improvement and should be fun to implement 👍🏼

**Comment by talhatahir** [comment] 2023-08-31 15:55
@roryabraham Would be nice next time if the person who brings up the issue to light to get an opportunity to work on the fix.

**Comment by b4s36t4** [comment] 2023-08-31 15:58
@talhatahir Yea You'll get preference but only when your proposal is solid and better than others. But I don't see you have given your best with your proposal nor the questions asked by C+.

This is my opinion though 🙂.

**Comment by talhatahir** [comment] 2023-08-31 16:02
@b4s36t4 I believe that these two should be done separately ( prettier sort-import lint rules & adding aliases) The risk of causing conflicts will be high in this PR (especially for the code author) And doing it in a single PR is not a great strategy.

**Comment by roryabraham** [comment] 2023-08-31 16:44
> Would be nice next time if the person who brings up the issue to light to get an opportunity to work on the fix.

sorry if this wasn't clear – this issue is open for proposals. @situchan and myself will review those proposals.

**Comment by roryabraham** [comment] 2023-08-31 16:48
As @b4s36t4 alluded to, in general we award the job to the first proposal of sufficient quality to give us confidence in the solution.

**Comment by b4s36t4** [comment] 2023-08-31 16:50
Thanks @roryabraham. Since you're here I request you to review my proposal 😅.

**Comment by roryabraham** [comment] 2023-08-31 16:54
So far, it seems like most of the pieces are in place from multiple different contributors, but in my opinion there's currently no proposal that [uses our proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) _and_ includes sufficient clarity + detail for:

1. Import aliases
1. Sorted imports
1. A rollout plan for both changes.

Also, I want to set expectations here that due to the ongoing [merge freeze](https://expensify.slack.com/archives/C01GTK53T8Q/p1693347701566439) we will not be merging any code related to this DX improvement until the merge freeze is lifted.

**Comment by pradeepmdk** [comment] 2023-09-01 01:23
Updated Proposal https://github.com/Expensify/App/issues/20531#issuecomment-1701007323

Thanks!

**Comment by roryabraham** [comment] 2023-09-01 07:52
Thanks for the proposals, at this point I'm going to go with the proposal I think provides better detail and clarity. Thanks @b4s36t4!

FWIW the one piece of feedback I have is that we don't want to cause too much disruption for other developers by asking them to HOLD anything for this. Instead, let's go with this plan:

> If we're not ok with one merge for all the alias we can rollout things gradually

When we merge the first PR we can let people know about the changes and tell them that using import aliases is an option. Then we can migrate everything in a few smaller PRs, resolving conflicts as we go.

For the 2nd part (sorting imports), since we can just run prettier and have it auto-format everything for us, we can do all the changes in a single PR. We'll just want to make sure that PR is completely up-to-date with main before we merge it, and right afterwards we'll announce the change and tell everyone to merge main in their PR to avoid prettier errors on main.

**Comment by roryabraham** [comment] 2023-09-01 07:52
Since there are two tasks here and will be several PRs involved, I think it's fair to raise the bounty here to $1000

**Comment by b4s36t4** [comment] 2023-09-01 07:56
Understood @roryabraham. Thanks.!

**Comment by b4s36t4** [comment] 2023-09-01 08:28
@situchan I think we're waiting for the merge freeze to lift.

**Comment by talhatahir** [comment] 2023-09-01 20:23
All the best @b4s36t4! I got caught up with something important and did not update my proposal. I hope you would do a fine job!

**Comment by b4s36t4** [comment] 2023-09-03 14:02
@roryabraham @situchan Raised a PR here #26605.

PR includes the config for module alias and a single file which uses the update module alias to make sure alias are working.

**Comment by situchan** [comment] 2023-09-04 07:45
Let's still hold this for merge freeze. I will review PR after conference is over as it won't be merged before that.

**Comment by situchan** [comment] 2023-09-10 17:27
We started working on PR as merge freeze will likely to be over tomorrow.

**Comment by b4s36t4** [comment] 2023-10-04 11:24
PR is in review.

**Comment by bfitzexpensify** [comment] 2023-11-07 14:18
Deployed to prod on 11/2, assuming no regressions, payment will be due on 11/9

**Comment by bfitzexpensify** [comment] 2023-11-09 18:00
Payments complete. Given this was a developer QOL thing, I figure we likely don't need the BZ checklist here - is that correct @situchan?

**Comment by situchan** [comment] 2023-11-09 18:03
@roryabraham should penalty still be applied here given the efforts made? This issue was specific than others. So not bug, not urgent and had to wait merge until no conflict and folks are online

**Comment by roryabraham** [comment] 2023-11-11 22:52
I don't think that there was a regression here, so I don't think there should be any penalty. Even if there _was_ a regression, I would be in support of waiving any penalty in light of the logistical challenges of doing a PR that touches so many files.

**Comment by situchan** [comment] 2023-11-12 02:52
There was not regression but I think @bfitzexpensify applied because of not being merged in 9 days

**Comment by bfitzexpensify** [comment] 2023-11-13 16:03
Yeah, the Upwork job automatically updates after 9 days. 

The reasoning to not apply a penalty is reasonable to me. I've just sent bonus amounts of $500 to you both @situchan and @b4s36t4 

I think we can close this one out

**Closed by bfitzexpensify** 2023-11-13 16:03 UTC
Labels: External, Daily, Task, Awaiting Payment
