### ISSUE TITLE
 Profile - Status timeout briefly changed to "Never" when saving it as "Today"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53046] opened 2024-11-24 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5260055&group_by=cases:section_id&group_order=asc&group_id=229064
**Email or phone of affected tester (no customers):** ibellicotest+36@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Profile" and select "Status"
4. Select any emoji and write any message.
5. On "Clear After" select "Today"
6. Tap on "Save"
7. Verify that when the status is saved, timeout is not changed.

## Expected Result:
When the user selects "Today" as timeout and save the status, timeout should remain the same and not be changed.

## Actual Result:
When the user saves a status and selects "Today" in "Clear After", timeout is briefly changed to "Never" after tapping "Save"

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6674881_1732463698497!Status](https://github.com/user-attachments/assets/5592f8ba-a2d9-4494-9c9b-2fc5b18e11d1)

https://github.com/user-attachments/assets/b0771db4-c5ca-45f0-95d6-b3d2659e3f86
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by me-ZaidAli** [comment] 2024-11-24 22:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Clear after" option gets set to "never" when we set the profile status 

### What is the root cause of that problem?
`User.clearDraftCustomStatus();` in the `updateStatus` method since it sets `clearAfter: ''`
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L108

### What changes do you think we should make in order to solve the problem?
Remove this line in `StatusPage` file since it's setting `clearAfter:  ''` which leads to `Never` showing up 
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L108

we don't need to call it in the function since it's already getting called over here in the useEffect's return callback
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L135-L144

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by CyberAndrii** [comment] 2024-11-24 22:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Status timeout briefly changed to "Never" when saving it as "Today"

### What is the root cause of that problem?

When the "Save" button is clicked, it first clears the draft status and only then navigates back to the previous screen.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L103-L111

### What changes do you think we should make in order to solve the problem?

To resolve this, we can ensure that the `User.clearDraftCustomStatus();` call is executed only after the modal has fully closed.

```diff
             User.updateCustomStatus({
                 text: statusText,
                 emojiCode: !emojiCode && statusText ? initialEmoji : emojiCode,
                 clearAfter: clearAfterTime !== CONST.CUSTOM_STATUS_TYPES.NEVER ? clearAfterTime : '',
             });
-            User.clearDraftCustomStatus();
             navigateBackToPreviousScreenTask.current = InteractionManager.runAfterInteractions(() => {
                 navigateBackToPreviousScreen();
+                Navigation.isNavigationReady().then(() => {
+                    User.clearDraftCustomStatus();
+                });
             });
```

**Comment by CyberAndrii** [comment] 2024-11-24 23:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Status timeout briefly changed to "Never" when saving it as "Today"

### What is the root cause of that problem?

When the "Save" button is clicked, it first clears the draft status and only then navigates back to the previous screen.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L103-L111

### What changes do you think we should make in order to solve the problem?

To resolve this, we need to delay the `User.clearDraftCustomStatus();` call until the modal has fully closed.

```diff
             User.updateCustomStatus({
                 text: statusText,
                 emojiCode: !emojiCode && statusText ? initialEmoji : emojiCode,
                 clearAfter: clearAfterTime !== CONST.CUSTOM_STATUS_TYPES.NEVER ? clearAfterTime : '',
             });
-            User.clearDraftCustomStatus();
             navigateBackToPreviousScreenTask.current = InteractionManager.runAfterInteractions(() => {
                 navigateBackToPreviousScreen();
+                Navigation.isNavigationReady().then(() => {
+                    User.clearDraftCustomStatus();
+                });
             });
```

**Comment by mkzie2** [comment] 2024-11-25 03:10
Dupe of https://github.com/Expensify/App/issues/50170

**Closed** 2024-11-25 21:25 UTC
Labels: Daily, Bug
