### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] Offline mode: Crash after deleting Split Bill request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25481] opened 2023-08-18 13:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to any account.
2. Turn OFF the network connection to switch to OFFLINE mode.
3. Create a Split Bill request with two other users.
4. This will generate two sub-reports: report A and report B >> Click on report A to view its details.
5. Hover over the report and select the Delete option >> report A will be deleted.
6. Click on report B >> Observation: The app CRASHES.

## Expected Result:
App should not crash

## Actual Result:
App Crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/468c2e32-5ef0-499c-a4bb-652085a118e5

https://github.com/Expensify/App/assets/115492554/677b458c-c71e-47b5-9139-77b5d738a1e2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tranvantoan-qn

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692279822439699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e588feb8af6feae9</li>
        <li>Upwork Job ID: 1692566105949474816</li>
        <li>Last Price Increase: 2023-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>pradeepmdk | Contributor | 26243141</li>
<li>tranvantoan-qn | Reporter | 26243145</li>
</ul></li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-08-18 14:33
**FYI**: This crash happens on platforms, not only Android as the specified in the issue Title

**Comment by pradeepmdk** [comment] 2023-08-18 14:48
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Offline mode: Crash after deleting Split Bill request 
### What is the root cause of that problem?
in offline after deleting transaction its updated to null because its completed removed from onyx
![Screenshot 2023-08-18 at 8 13 52 PM](https://github.com/Expensify/App/assets/16595846/661719c8-c39b-4717-8660-e6a068246749)
![Screenshot 2023-08-18 at 8 18 19 PM](https://github.com/Expensify/App/assets/16595846/5e4152e7-6cad-48ef-9a8e-710bd1b28574)

https://github.com/Expensify/App/blob/main/src/libs/TransactionUtils.js?#L196

```javascript
function getAllReportTransactions(reportID) {
    return _.filter(allTransactions, (transaction) => transaction.reportID === reportID);
}
``` 

### What changes do you think we should make in order to solve the problem?
we need to check its null or not
```javascript
function getAllReportTransactions(reportID) {
    return _.filter(allTransactions, (transaction) => transaction && transaction.reportID === reportID);
}
``` 

### result

**Comment by MitchExpensify** [comment] 2023-08-18 15:41
Having trouble reproducing this on a virtual device via Browserstack 
<img width="483" alt="image" src="https://github.com/Expensify/App/assets/36425901/7d34d16d-db9e-49ed-bd2d-53584ac9b1c6">

**Comment by pradeepmdk** [comment] 2023-08-18 15:42
@MitchExpensify  you can verify on the web also. because its not a platform specfic

**Comment by MitchExpensify** [comment] 2023-08-18 15:42
Ok awesome, trying that now @pradeepmdk !

**Comment by tranvantoan-qn** [comment] 2023-08-18 15:50
On mobile, for the crash to occur, we will need to return to the LHN and then navigate to other reports, as demonstrated here:

https://github.com/Expensify/App/assets/10254571/3a1b0bfc-54bc-4789-a55a-e3fe4776a3b2

**Comment by MitchExpensify** [comment] 2023-08-18 15:55
Reproduced!

**Comment by Pujan92** [comment] 2023-08-18 17:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Crash after deleting split bill in offline mode

### What is the root cause of that problem?
For the deletion of money request we set the value `null` within the optimistic data for that specific transaction. After that whenever we try to fetch all transactions for any report below condition(accessing reportID of null) get fails to execute and crashes the app.
https://github.com/Expensify/App/blob/dd2c98b839b0aa85f4ffa3bc6f230cf1d499183d/src/libs/actions/IOU.js#L1113

### What changes do you think we should make in order to solve the problem?
Instead of setting `null`, we can set an empty object `{}` for the optimistic data and `null` has been received in the api success response onyx data. With that accessing reportID on null won't occur and the app won't get crashed.
`value: {}`

**Comment by johnmlee101** [comment] 2023-08-18 21:46
I like the simplicity of your proposal @Pujan92 . I see that @pradeepmdk you edited your post with the same solution _after_ the proposal by @Pujan92 so I'm going to go with this solution!

**Comment by johnmlee101** [comment] 2023-08-18 21:47
I'll confirm one last time to see

**Comment by pradeepmdk** [comment] 2023-08-18 21:51
@johnmlee101 I added this  initially  
```javascript
 const optimistic data = [ 
     { 
         onyxMethod: Onyx.METHOD.SET, 
         key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, 
         value: null, 
``` 
forgot to save this on the solution you can check my edit history.

**Comment by johnmlee101** [comment] 2023-08-18 22:37
I see your edit at 1:57pm ET on your post and @Pujan92 's post was 1:18pm ET. So he had the solution out initially.

**Comment by pradeepmdk** [comment] 2023-08-18 22:42
@johnmlee101 sorry, that is my mistake I keep it open in the preview mode and forgot to commit. in the emergency went out. 
once back I saw it in preview mode. so at the time, I did not see him post.

**Comment by pradeepmdk** [comment] 2023-08-19 05:29
@johnmlee101 can you check my solution

**Comment by Pujan92** [comment] 2023-08-19 13:18
As @marcaaron reacted with 👎 for my proposal, I agree that it isn't the proper RCA and solution. 

**Issue**
1) When there is an add money request pending and if we delete the other money request it will crash the app due to trying to access `reportID` on null. Offline mode is needed to make the requests pending. 
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/ReportActionItem/MoneyRequestAction.js#L132-L135
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/IOUUtils.js#L77-L78
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/TransactionUtils.js#L195-L196

2) When we set value `null` for the onyx key it should remove the key from the storage.
https://github.com/Expensify/react-native-onyx/blob/79bfb5ef713e288fea8827cb4efe0d677177a525/lib/Onyx.js#L937-L939

But inside the remove function of onyx we notify the subscribers with the changed value if we have set the callback and waitForCollectionCallback.
https://github.com/Expensify/react-native-onyx/blob/79bfb5ef713e288fea8827cb4efe0d677177a525/lib/Onyx.js#L508-L515
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/TransactionUtils.js#L11-L20

3) With this it will first update the subscriber by passing that null value entry with the callback execution and then it will remove the key from the storage. Meanwhile, we are calling the `getAllReportTransactions` and it tries to operate null transaction before it gets removed from storage.

**Solution**
We can filter out the null values for the transactions in the Onyx callback we set in the `TransactionUtils.js` file.
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/TransactionUtils.js#L11-L20
```
allTransactions = _.filter(val, (transaction => transaction));
```

Above are my observations. Kindly review it @johnmlee101 @marcaaron

**Comment by pradeepmdk** [comment] 2023-08-20 16:29
@johnmlee101 @marcaaron  proposal updated https://github.com/Expensify/App/issues/25481#issuecomment-1684031967

**Comment by mountiny** [comment] 2023-08-21 13:58
We should use `null` values when deleting, thats probably why there were 👎

**Comment by Pujan92** [comment] 2023-08-21 14:06
Yes @mountiny, I agree and that's why I have made a new [proposal](https://github.com/Expensify/App/issues/25481#issuecomment-1684942138) by digging more into the issue. Even I also reacted with :-1: considering the same reason later wards 😅

**Comment by pradeepmdk** [comment] 2023-08-21 14:13
@mountiny  @johnmlee101 can check my proposal I have  PR for  this issue  https://github.com/Expensify/App/issues/25481#issuecomment-1684031967

**Comment by pradeepmdk** [comment] 2023-08-21 14:58
@mountiny we need to update this as well 
```javascript
IOUUtils.isIOUReportPendingCurrencyConversion(props.iouReport);

```

**Comment by roryabraham** [comment] 2023-08-21 17:18
I'm a bit confused why doing this:

```
{
    onyxMethod: Onyx.METHOD.SET,
    key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`,
    value: null,
},
```

is resulting in `null` being included in `allTransactions` [here](https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/libs/TransactionUtils.js#L10-L20). I'd say that's the _real_ root cause for this issue. However, I just adding a null-safe accessor is fine for now because this is a deploy blocker.

**Comment by Pujan92** [comment] 2023-08-21 17:27
@roryabraham  As per my observation it is due to notify the subscribers with the changed values before updating the storage.
https://github.com/Expensify/react-native-onyx/blob/79bfb5ef713e288fea8827cb4efe0d677177a525/lib/Onyx.js#L508-L515

**Comment by roryabraham** [comment] 2023-08-21 18:32
Created PR for this: https://github.com/Expensify/App/pull/25610

we can discuss payments for this after, but because this is a deploy blocker it should never have been marked as `External`

**Comment by pradeepmdk** [comment] 2023-08-21 18:38
@roryabraham   PR is ready to review

**Comment by roryabraham** [comment] 2023-08-21 18:53
@pradeepmdk PR is missing screenshots / screen recordings on all platforms. Please complete those ASAP so we can resolve this urgent issue

**Comment by pradeepmdk** [comment] 2023-08-21 19:20
@roryabraham need some more time pod is falling checking on that

**Comment by pradeepmdk** [comment] 2023-08-21 19:32
@roryabraham can we try adhoc build

**Comment by roryabraham** [comment] 2023-08-21 21:27
@MitchExpensify removing @ArekChr since they have not commented on this issue and did not review the PR before we merged it. So no C+ payment due here

**Comment by MitchExpensify** [comment] 2023-08-21 21:29
**Payment summary**:

Reporting - $250 via Upwork to @tranvantoan-qn 
Contirbutor - $1000 via Upwork to @pradeepmdk

**Comment by marcaaron** [comment] 2023-08-22 02:29
>is resulting in null being included in allTransactions [here](https://github.com/Expensify/App/blob/4a7558cdfea721e58675b2e1d1f9ba25a2fd9e31/src/libs/TransactionUtils.js#L10-L20). I'd say that's the real root cause for this issue

Hmm actually - I think @roryabraham you are suggesting something like:

**Given this setup:**

- A subscriber to a collection key with `waitForCollectionCallback: true`

**When this happens:**

-  A collection member key is set to `null`

**We would expect this:**

- The subscriber to get the new complete collection with any `null` values removed

If so, that makes sense to me and does sound like the real root cause. We should fix it in Onyx?

**Comment by pradeepmdk** [comment] 2023-08-22 02:41
@marcaaron Yes, if we fixed it in Onyx that is the best solution here

**Comment by roryabraham** [comment] 2023-08-22 05:27
Agree @marcaaron that's the real root cause and we should fix it in Onyx. Didn't do that today because I wanted to get the deploy out as quickly as possible, but I made a follow-up issue here: https://github.com/Expensify/react-native-onyx/issues/310

**Comment by marcaaron** [comment] 2023-08-22 21:04
No, we cannot do this. At least for now, it's the only way a subscriber can know that some data has been removed.

**Comment by MitchExpensify** [comment] 2023-08-29 00:37
Paid and contracts ended https://github.com/Expensify/App/issues/25481#issuecomment-1687070257

**Comment by MitchExpensify** [comment] 2023-08-29 00:38
Bump BZ steps https://github.com/Expensify/App/issues/25481#issuecomment-1687090365

**Comment by roryabraham** [comment] 2023-09-01 08:04
I checked off my pieces in the BZ checklist. The main takeaway here is that the root cause was actually a bug in Onyx, and I'm working on fixing that in https://github.com/Expensify/react-native-onyx/pull/311

**Comment by MitchExpensify** [comment] 2023-09-01 18:42
Thanks @roryabraham! Looks like this can be closed in that case

**Closed by MitchExpensify** 2023-09-01 18:42 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
