### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Auth DeletePolicy error is misaligned

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21143] opened 2023-06-20 17:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open workspaces
3. Select any workspace and delete it

## Expected Result:
If Auth DeletePolicy error is triggered, it should be aligned with workspace avatars as we normally do for other errors
## Actual Result:
Auth DeletePolicy error is not aligned with workspace avatars

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/feada14c-3388-470c-9a08-3a8772cbda64)
![image (3)](https://github.com/Expensify/App/assets/43996225/5f22d457-effd-4cb7-9b21-bd07abca8f5f)

https://github.com/Expensify/App/assets/43996225/c4f305c9-408d-4722-8e41-0bf4abee79e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1686578487180049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae4f5bbe870cdf89</li>
        <li>Upwork Job ID: 1671580913028014080</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-06-20 17:54
## Proposal
Auth DeletePolicy error is misaligned
### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The error padding left in not the same as the item padding left.
Error padding left:
https://github.com/Expensify/App/blob/332d2c96e1f0b4bbcdd85859868b6d7b3047d76a/src/styles/styles.js#L2832-L2835

Item padding left:
https://github.com/Expensify/App/blob/332d2c96e1f0b4bbcdd85859868b6d7b3047d76a/src/styles/styles.js#L1299

### What changes do you think we should make in order to solve the problem?
Apply the same padding left for both Error and Item
```javascript
 menuItemErrorPadding: { 
     paddingLeft: 20, 
     paddingRight: 20, 
 }, 
```

![Screenshot 2023-06-19 at 11 25 26 PM](https://github.com/Expensify/App/assets/41129870/7b4f183c-d28f-4035-98e6-710961dbf4e0)




### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-06-20 23:03
I would like to suggest to not get this aligned as this looks more like a error message now rather then when aligned, where it will look more like a workspace.

**Comment by Beamanator** [comment] 2023-06-21 07:52
Maybe @shawnborton can help confirm how we want those to look - and @dukenv0307 it looks like you forced errors to appear in Onyx, right? Maybe you can add some dummy text to each of those screenshots too?

**Comment by shawnborton** [comment] 2023-06-21 12:04
I'm confused, why are we not showing an error message next to the red dot?

**Comment by shawnborton** [comment] 2023-06-21 12:12
Thank you!

**Comment by shawnborton** [comment] 2023-06-21 17:13
I think the cleanest thing to do might be to do just `Padding Horizontal 20px` from your ideas. But I guess it depends, if that error message is already wrapped inside a view that has 20px padding, then we wouldn't need any extra. Let me know if that makes sense.

**Comment by shawnborton** [comment] 2023-06-21 17:27
I disagree with that. I think we're going to run into too many different cases of trying to align the red dot up with the icon above it - for example, there are different sizes when there is an avatar from a chat message, vs an icon from an option row, etc. So I think the cleanest thing to do is follow the padding that the view has if it's say 20px, and if there is no view padding, then we use 20px.

**Comment by wahaha999** [comment] 2023-06-21 21:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue

Auth DeletePolicy error message is misaligned.

### What is the root cause of that problem?

Because padding of two adjacent elements (menu item and error) are different.

##### MenuItem

```javascript
popoverMenuItem: {
    flexDirection: 'row',
    borderRadius: 0,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'space-between',
    width: '100%',
},
```

##### Error message

```javascript
menuItemErrorPadding: {
    paddingLeft: 44,
    paddingRight: 20,
},
```

### What changes do you think we should make in order to solve the problem?

We should update menuItemErrorPadding in [styles.js](https://github.com/Expensify/App/blob/9e8a151b908447f3d79261ddb0f62d10c19b5c6e/src/styles/styles.js#L2835)

```
menuItemErrorPadding: {
    paddingLeft: 20,
    paddingRight: 20,
},
```

This style update will not affect into another components because the style is not used by other components excepted the component.

### What alternative solutions did you explore? (Optional)
In advanced, this solution need so many updates.
I interpreted in perspective of [@shawnborton 's comment](https://github.com/Expensify/App/issues/21143#issuecomment-1601286593). It's hard for padding of error to follow the padding of the view such as MenuItem due to the structure of [OfflineWithFeedback component](https://github.com/Expensify/App/blob/main/src/components/OfflineWithFeedback.js) is not allow it like below now.

```
<View style={props.style}>
    {!hideChildren && (
        <View
            style={[needsOpacity ? styles.offlineFeedback.pending : {}, props.contentContainerStyle]}
            needsOffscreenAlphaCompositing={shouldRenderOffscreen ? needsOpacity && props.needsOffscreenAlphaCompositing : undefined}
        >
            {children}
        </View>
    )}
    {props.shouldShowErrorMessages && hasErrors && (
        <View style={StyleUtils.combineStyles(styles.offlineFeedback.error, props.errorRowStyles)}>
            <DotIndicatorMessage
                style={[styles.flex1]}
                messages={props.errors}
                type="error"
            />
            <Tooltip text={props.translate('common.close')}>
                <PressableWithoutFeedback
                    onPress={props.onClose}
                    style={[styles.touchableButtonImage]}
                    accessibilityRole="button"
                    accessibilityLabel={props.translate('common.close')}
                >
                    <Icon src={Expensicons.Close} />
                </PressableWithoutFeedback>
            </Tooltip>
        </View>
    )}
</View>
```
ex,  `MenuItem` is `children` and error message is `DotIndicatorMessage` component.

Eventually solution is to manipulate style for padding in `OfflineWithFeedback` component and, not to use `errorRowStyles` and padding in the children component such as MenuItem. so basically it will looks like this.

##### [WorkspacesListPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacesListPage.js)
```
<OfflineWithFeedback
    key={`${keyTitle}_${index}`}
    pendingAction={item.pendingAction}
    style={styles.ph4}
    onClose={item.dismissError}
    errors={["Auth DeletePolicy error is misaligned"]}
>
    <MenuItem
        title={keyTitle}
        icon={item.icon}
        iconType={CONST.ICON_TYPE_WORKSPACE}
        onPress={item.action}
        iconStyles={item.iconStyles}
        iconFill={item.iconFill}
        shouldShowRightIcon
        badgeText={this.getWalletBalance(isPaymentItem)}
        fallbackIcon={item.fallbackIcon}
        brickRoadIndicator={item.brickRoadIndicator}
        disabled={item.disabled}
    />
</OfflineWithFeedback>
```

##### [OfflineWithFeedback component](https://github.com/Expensify/App/blob/main/src/components/OfflineWithFeedback.js)
```
<View style={props.style}>
    {!hideChildren && (
        <View
            style={[needsOpacity ? styles.offlineFeedback.pending : {}, props.contentContainerStyle]}
            needsOffscreenAlphaCompositing={shouldRenderOffscreen ? needsOpacity && props.needsOffscreenAlphaCompositing : undefined}
        >
            {children}
        </View>
    )}
    {props.shouldShowErrorMessages && hasErrors && (
        <View style={StyleUtils.combineStyles(styles.offlineFeedback.error)}>
            <DotIndicatorMessage
                style={[styles.flex1]}
                messages={props.errors}
                type="error"
            />
            <Tooltip text={props.translate('common.close')}>
                <PressableWithoutFeedback
                    onPress={props.onClose}
                    style={[styles.touchableButtonImage]}
                    accessibilityRole="button"
                    accessibilityLabel={props.translate('common.close')}
                >
                    <Icon src={Expensicons.Close} />
                </PressableWithoutFeedback>
            </Tooltip>
        </View>
    )}
</View>
```

##### [styles.js](https://github.com/Expensify/App/blob/9e8a151b908447f3d79261ddb0f62d10c19b5c6e/src/styles/styles.js#L2835)
```
popoverMenuItem: {
    flexDirection: 'row',
    borderRadius: 0,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'space-between',
    width: '100%',
},
```

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 19:44
I think the first proposal is straightforward so let's hire them, other proposals are redundant. Thanks, everyone for the proposals and discussion!

@wahaha999 About your alternative proposal, I really don't see why we need it. If your proposal solves or improves any issues and multiple components that are not being reported please start a thread in the Expensify Slack channel with a list of Problems and how your solution addresses them, thanks!

C+ Reviewed
🎀 👀 🎀

**Comment by ahmedGaber93** [comment] 2023-06-23 07:56
@Santhosh-Sellavel we can also fix any similar reported/non-reported issue not included in this issue report in one PR with same My proposal concept.
My proposal concept is:
> Apply the same visual padding/margin for both Error and Item.

And any other similar issues like this issue #20420 and [my proposal](https://github.com/Expensify/App/issues/20420#issuecomment-1581658859) there and others, we can cover it in one PR.

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 19:34
@ahmedGaber93 @dukenv0307 
Sorry for the confusion here, I think both are valid proposals in their own way. I'm not sure whom to pick here. Are you guys interested in working together on this one and sharing the job fee, so we can get this done sooner?

cc: @madmax330 What do you say?

 I'll let you make the final call here, thanks!

**Comment by ahmedGaber93** [comment] 2023-06-23 20:54
> Are you guys interested in working together on this one and sharing the job fee

@Santhosh-Sellavel for me, no problem, I agree.

**Comment by madmax330** [comment] 2023-06-26 10:32
Alright I will assign you both. Thanksk @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 16:13
Thanks @madmax330!

@dukenv0307 & @ahmedGaber93 
One of you should implement and the other one should help to review/test fill the checklist. Please decide on that and get started soon, thanks!

**Comment by ahmedGaber93** [comment] 2023-06-27 00:18
Thanks @Santhosh-Sellavel I will create the PR soon, and ask @dukenv0307 for review and test

**Comment by ahmedGaber93** [comment] 2023-06-27 06:05
> We can display error on WorkspaceInitialPage be these step:

    1. Do to any workspace (ID: 123456)
    2. Delete this workspace
    3. GO to again this workspace after removing it by accessing this URL: /workspace/123456

@dukenv0307 
I can't show the error by these steps, it displays "Hmm... it's not here".

**Comment by ahmedGaber93** [comment] 2023-06-27 07:19
@Santhosh-Sellavel @dukenv0307 [PR](https://github.com/Expensify/App/pull/21662) is ready for review.

**Comment by maddylewis** [comment] 2023-06-27 17:25
**Making note of payments just for my own organization:**
- [ ] Reporting bonus - @dhairyasenjaliya ($250)
- [ ] Contributor - @dukenv0307 ($500)
- [ ] Contributor - @ahmedGaber93 ($500)
- [ ] C+ - @Santhosh-Sellavel

**Comment by dhanashree-sawant** [comment] 2023-06-27 17:45
Hi @maddylewis, I think you meant @dhanashree-sawant for reporting bonus 😅

**Comment by Santhosh-Sellavel** [comment] 2023-07-03 15:04
@madmax330 
I think this should be considered for a speed bonus, as it's been ready for merge [4 days ago](https://github.com/Expensify/App/pull/21662#pullrequestreview-1506211927). Thanks!

cc: @maddylewis

**Comment by maddylewis** [comment] 2023-07-05 13:15
@dhanashree-sawant - ah, sorry about that! https://github.com/Expensify/App/issues/21143#issuecomment-1609962297

updated!!

**Comment by maddylewis** [comment] 2023-07-05 13:16
@Santhosh-Sellavel - i updated the total payouts for the contributors to $750 - https://github.com/Expensify/App/issues/21143#issuecomment-1609939334

if that works, I'll get the payments sent. thanks!

**Comment by maddylewis** [comment] 2023-07-10 20:52
payment due soon / switching to daily

**Comment by maddylewis** [comment] 2023-07-14 00:13
ill process payment tomorrow!

**Comment by maddylewis** [comment] 2023-07-14 14:02
@Santhosh-Sellavel - let me know the status of the BZ checklist https://github.com/Expensify/App/issues/21143#issuecomment-1622148429

**Comment by maddylewis** [comment] 2023-07-14 14:02
offers sent

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 19:52
@maddylewis I will collect via ND, so cancel my offer. Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 20:05
@maddylewis Bonus for me is not included [here](https://github.com/Expensify/App/issues/21143#issuecomment-1609939334).

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 20:10
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: N/A
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@maddylewis] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@madmax330 I think this would have been intentionally added, now we updating consistently across the pages. So this is not a regression. We can skip regression tests too here as this is a minor UI polish!

Let me know if you differ on any of the above, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 21:48
Requested payment on ND

**Comment by maddylewis** [comment] 2023-07-17 13:31
i believe all payments have been processed either via Upwork or NewDot - closing!

**Closed by maddylewis** 2023-07-17 13:31 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-18 18:01
Approved $750 on ND to Santhosh

**Comment by maddylewis** [comment] 2023-07-18 18:36
Maddy LewisToday at 2:35 PMah yep, my bad. i included the bonus amount in the Contributors' payments but not the C+'s payment - https://github.com/Expensify/App/issues/21143#issuecomment-1609939334

can confirm his payment should be $1500 👍🏼
