### ISSUE TITLE
Android  - Import category - User cannot import this specific csv file , error is displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48713] opened 2024-09-06 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Go to workspace- categories - 3dot- import categories
3. Upload tag file attached below
4. Change all possible options and try to import file

## Expected Result:
User cannot import this specific csv file , error must not be displayed

## Actual Result:
User cannot import this specific csv file , error is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/713ef0f6-590a-43b6-9cb2-db6c06a6a678

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-09-06 13:33
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment] 2024-09-09 03:01
Android <> ios bug swap

**Comment by jliexpensify** [comment] 2024-09-09 03:24
@lanitochka17 please provide the CSV, thanks.

**Comment by jliexpensify** [comment] 2024-09-12 09:46
Bump @lanitochka17 - can you provide the CSV?

**Comment by jliexpensify** [comment] 2024-09-16 01:56
No CSV given, closing this out because I can't repro.

**Comment by lanitochka17** [comment] 2024-09-23 13:29
Sorry for the late reply, I was on vacation until September 23
Here is the CSV file 
[Over 500 tags (2).csv](https://github.com/user-attachments/files/17098319/Over.500.tags.2.csv)

**Comment by jliexpensify** [comment] 2024-09-25 22:52
Error is `Oops! A required field (enabled) hasn't been mapped`

@lanitochka17 this isn't a bug. Your CSV only has 1 column - New.Dot requires both `name` and `Enabled` to be mapped, so this is working as intended.

**Closed by jliexpensify** 2024-09-25 22:52 UTC
Labels: Daily, Overdue, Bug
