### ISSUE TITLE
[$250]  Search - search query has the type set to "expenses" instead of "chats"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52774] opened 2024-11-19 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5240921
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New expensify desktop app
2. send some messages in a conversation, eg: Hello
3. Use the search function on the top right corner of the chat to look for one specific message, eg: Hello
4. Press enter

## Expected Result:
The search query has "type" set to "chats"

## Actual Result:
The search query has the "type" set to "expenses

## Workaround:
Unknowm

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/53a55f3a-6825-46c3-a59b-7bcb408f9666

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861481632682368032</li>
        <li>Upwork Job ID: 1861481632682368032</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by FitseTLT** [comment] 2024-11-19 15:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - search query has the type set to "expenses" instead of "chats"

### What is the root cause of that problem?
When the type is not given in the query the parser will default to `expense` type
https://github.com/Expensify/App/blob/14ca237ef392a3493336aa4fdf4a0d4529039972/src/libs/SearchQueryUtils.ts#L267
### What changes do you think we should make in order to solve the problem?

We can provide the default type as chat when the type: field is not provided in the query
```
        const result = searchParser.parse(query.includes('type:') ? query : ' type:chat '.concat(query)) as SearchQueryJSON;

```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-11-19 16:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search query has the "type" set to "expenses

### What is the root cause of that problem?

in case there is no type then we are setting type default to "expense" [here](https://github.com/Expensify/App/blob/e8ac6d4cb04e39728ba1ed89207985bfae0db76b/src/libs/SearchParser/searchParser.js#L1278)

https://github.com/Expensify/App/blob/e8ac6d4cb04e39728ba1ed89207985bfae0db76b/src/libs/SearchParser/searchParser.js#L1278

### What changes do you think we should make in order to solve the problem?


In case we are in inbox then i think when user click on search it should have `type: chat` at the beginning

We should add the default value [here](https://github.com/Expensify/App/blob/e8ac6d4cb04e39728ba1ed89207985bfae0db76b/src/components/Search/SearchRouter/SearchRouter.tsx#L63) when we have `contextualReportID`

```
  const [textInputValue, debouncedInputValue, setTextInputValue] = useDebouncedState(contextualReportID ? 'type: chat ' : '', 500);
```

https://github.com/Expensify/App/blob/e8ac6d4cb04e39728ba1ed89207985bfae0db76b/src/components/Search/SearchRouter/SearchRouter.tsx#L63)

### What alternative solutions did you explore? (Optional)

We can update type default "expense" to "chat" [here](https://github.com/Expensify/App/blob/e8ac6d4cb04e39728ba1ed89207985bfae0db76b/src/libs/SearchParser/searchParser.js#L1278)
NA

**Comment by nkdengineer** [comment] 2024-11-29 08:31
> @nkdengineer Are you suggesting we detect the report type from contextualReportID and filter search results from that?

@Ollyws yes, we can base on the value of `contextualReportID` to determine what the type is here.

**Comment by Kicu** [comment] 2024-12-02 15:26
@luacmartins FYI please double check if the expectation in the issue makes sense

**Comment by luacmartins** [comment] 2024-12-02 17:49
This is expected. The default behaviour is `Expenses`. Closing.

**Closed by luacmartins** 2024-12-02 17:49 UTC
Labels: External, Daily, Help Wanted, Bug
