### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] Still can access to Tag page when request money to DM 1:1 chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37207] opened 2024-02-26 15:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-15
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708850630563619

## Action Performed:
1. Request money
2. Enter amount
3. Select DM 1:1 chat
4. Click on description page
5. In the URL, change description to category or tag/1
(on native app or desktop app, using deeplink)

## Expected Result: 
Should display Not Found Page

## Actual Result: 
Empty category/tag page display

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/96a6901c-ed31-4786-b67b-02037f883404

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/38435837/05c65112-ae31-46b6-b268-2cc964996bdc

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d915d40b791c907</li>
        <li>Upwork Job ID: 1762132134901731328</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-02-26 15:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Still can access to Tag page when request money to DM 1:1 chat

### What is the root cause of that problem?
In IOURequestStepTag we don't pass shouldShowNotFoundPage props to `StepScreenWrapper`

### What changes do you think we should make in order to solve the problem?
In IOURequestStepTag we should pass shouldShowNotFoundPage props to `StepScreenWrapper`

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2024-02-28 16:09
Could you review this one @mkhutornyi?

**Comment by DylanDylann** [comment] 2024-02-28 16:26
@mkhutornyi  For more information, recently we have 2 PRs:
- Issue 1 https://github.com/Expensify/App/issues/34606 : Remove old category page and migrate logic to IOURequestStepCategory
- Issue 2 https://github.com/Expensify/App/issues/34612 : Remove old category page and migrate logic to IOURequestStepTag

In issue 1, I am a C+ contributor and I see that the contributor forgot to migrate the logic to display Not Found Page [here](https://github.com/Expensify/App/pull/35458/files#r1494411479). Then the contributor fixed it and currently the logic in the category is correct. After that, I saw that the same problem still happens on the Tag Page. It is the reason why I report this bug



https://github.com/Expensify/App/pull/35458/files#r1494411479

**Comment by DylanDylann** [comment] 2024-02-28 16:38
@mkhutornyi Because this PR is deployed to staging, the behavior on category page is correct

> The remaining bug to fix is make tag page same as category page when not found

Yes, we only need to fix this bug on Tag Page

**Comment by jasperhuangg** [comment] 2024-03-04 18:47
I agree that @DylanDylann's proposal looks good and they should be assigned to this issue!

**Comment by DylanDylann** [comment] 2024-03-05 14:06
@mkhutornyi The PR is ready for review: https://github.com/Expensify/App/pull/37747

**Comment by lschurr** [comment] 2024-03-14 18:58
Could you work on the checklist for this one @mkhutornyi?

**Comment by lschurr** [comment] 2024-03-18 18:19
Payment summary:

- Contributor: @DylanDylann $500 (paid in Upwork)
- Contributor+: @mkhutornyi $500 (paid in Upwork)

**Closed by lschurr** 2024-03-18 18:19 UTC
Labels: External, Daily, Awaiting Payment, Bug
