### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] New Chat - Recents list option for a new chat shows incorrect username and avatar after avatar update

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19684] opened 2023-05-26 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login
2. Click FAB > New Chat, observe the list of Recents
3. Create a money request with one of recents accounts
4. Change avatar
5. Click on chat from step 3 - > then thread - > then IOU preview
6. Click FAB - > New chat

## Expected Result:
Recent options should be correctly displayed

## Actual Result:
Incorrect account name (IOU hat instead of account) and incorrect avatar (Your account avatar instead another user)
Repro rate 4/5

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/01f4f080cb32f535f3067b29ba1bc19ae61a3de975bf5efdb867461b6c43820d

https://platform.applause.com/services/links/v1/external/7e6b0c2b2d2fb95e02014ca913465e9d17dc05868c0899d631013161dbf3bf6c

https://platform.applause.com/services/links/v1/external/e5b82e0ad05530e5bfc7eeb0e12b1c879da07f855846014a703571c85cc1f53f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team, and @Nathan-Mulugeta [via Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1684400092434069?thread_ts=1684400092.434069&cid=C049HHMV9SM) (https://github.com/Expensify/App/issues/19370)

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ca2c9c058213c2a</li>
        <li>Upwork Job ID: 1669361161957789696</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-05-29 16:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Recent list option for a new chat shows incorrect username and avatar after avatar update

### What is the root cause of that problem?
Recent list option for a new chat is get using `getOptions` function in OptionsListUtils.js, and `getOption` call `createOption` function.

In `createOption` function, the username and the avatar are fetched separately using `ReportUtils.getReportName` and `ReportUtils.getIcons`.

In `getReportName` function, will return getMoneyRequestReportName(report) for the IOU report. But this is not the username we expect, so the username will be incorrect.

And when call `getIcons` function, because does not pass isPayer parameter, and isPayer's default value is false, so `getIcons` returns the avatar for the user whose email equal to IOUReport's `ownerEmail`, that is the current login user's email. 
But we should get recent user's avatar for a new chat, so return owner email would cause avatar incorrect. The correct avatar for the IOUReport is the avatar for the user whose email is IOUReport's `manageEmail`, we would return the avatar for the IOUReport's `managerEmail` in `getIcons` function.

### What changes do you think we should make in order to solve the problem?

To get the correct username, add `isGetParticipantName` parameter with default value false to `getReportName` function.
And change below code block.
```
function getReportName(report, isGetParticipantName = false) {
...
    if (formattedName && !isGetParticipantName) {
        return formattedName;
    }
...
}
```
And in `createOption` function, call `reportName = ReportUtils.getReportName(report, true);`.

To get the correct avatar, we can simply pass `isPayer` with true value to `getIcons` function.

`result.icons = ReportUtils.getIcons(report, personalDetails, UserUtils.getAvatar(personalDetail.avatar, personalDetail.login), result.isIOUReport);`

### What alternative solutions did you explore? (Optional)
None.

**Comment by conorpendergrast** [comment] 2023-05-30 09:13
@kbecciv I haven't been able to reproduce this; is there a more specific set of steps that you can add to help here?

**Comment by conorpendergrast** [comment] 2023-05-31 13:50
Bump on those reproduction step here!

**Comment by conorpendergrast** [comment] 2023-06-06 14:57
I'm really sorry, I've tried about seven times to reproduce this and still haven't been able to do this!

**Comment by StevenKKC** [comment] 2023-06-07 19:59
@conorpendergrast Sorry for late. I can reproduce this issue.

https://github.com/Expensify/App/assets/131836113/47609e2b-3619-4cbf-a8d1-c9ea29c85516

As you can see in the video, wildevemail+3@gmail.com account name and avatar is changed.

Reproduction steps as follows.
1. Login
2. Click FAB, observe the list of Recents
3. Create a money request with one of the account that is not in the Recents.
4. Click on chat from step 3 -> then IOU preview
5. Click FAB -> New chat, observe the list of Recents

**Comment by StevenKKC** [comment] 2023-06-13 09:49
@conorpendergrast Could you please check my above comment?

**Comment by conorpendergrast** [comment] 2023-06-15 11:40
So bizarre, I still haven't been able to reproduce this after 2 more tests! 

@StevenKKC given your proposal, have you been able to reproduce this?

**Comment by StevenKKC** [comment] 2023-06-15 13:06
@conorpendergrast I'm still able to reproduce.
![Annotation 2023-06-15 090009](https://github.com/Expensify/App/assets/131836113/b3b5ea5f-bb21-4b5a-a8af-43b17882bfa9)

I'll check the reproduction steps.

**Comment by StevenKKC** [comment] 2023-06-15 13:36
@conorpendergrast Updated reproduction steps.

1. Login
2. Click FAB, observe the list of Recents
3. Create a money request with one of the account.
4. Click on chat from step 3, and then click IOU preview, and then send a message
5. Click FAB -> New chat, observe the list of Recents


https://github.com/Expensify/App/assets/131836113/922b25d0-2888-4b3f-a883-ce4d44014eb4

**Comment by conorpendergrast** [comment] 2023-06-15 15:06
Ohhhh yes, I see it! The key step that was missing was this: 
> Click on chat from step 3, and then click IOU preview, and then send a message

What this does is change the "Recent" interaction from the 1:1 DM, to the IOU chat between the two users

**Comment by conorpendergrast** [comment] 2023-06-15 15:07
Thanks @StevenKKC that was exactly what I wasn't seeing

**Comment by Nathan-Mulugeta** [comment] 2023-06-15 15:16
Hey guys, I wanted to let you know that I originally reported this issue on slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684400092434069?thread_ts=1684400092.434069&cid=C049HHMV9SM). cc:@conorpendergrast

**Comment by conorpendergrast** [comment] 2023-06-16 14:40
@Nathan-Mulugeta Oh yeah, I see that was documented [here](https://github.com/Expensify/App/issues/19370). Updating the OP!

**Comment by StevenKKC** [comment] 2023-06-16 15:26
> @StevenKKC You root cause analysis doesn’t looks correct for me.

@fedirjh Could you please tell me what is wrong?

**Comment by StevenKKC** [comment] 2023-06-16 16:45
@fedirjh I think money request threads should be searchable. 
After User A request money to User B, I think User B should be included in contacts list for new chat, even if there is no direct report between them.

**Comment by StevenKKC** [comment] 2023-06-16 17:01
@fedirjh Please check search and new group page.
![search](https://github.com/Expensify/App/assets/131836113/e99cd2c7-cbc7-45c4-b4bb-c18d6642dc82)
![newgroup](https://github.com/Expensify/App/assets/131836113/6fa6c14f-ac4f-4d9d-9b28-6953fdc8c586)

Money request threads are included for Search and new group page. Do you think these should not be included? If so, I would change RCA.

**Comment by luacmartins** [comment] 2023-06-16 18:29
That sounds correct to me. I think iou/expense reports and threads should only be available in search pages. @trjExpensify @JmillsExpensify can you please confirm?

**Comment by StevenKKC** [comment] 2023-06-16 20:30
@fedirjh Updated proposal. (https://github.com/Expensify/App/issues/19684#issuecomment-1567348198)

@luacmartins @fedirjh 
Could you please confirm that the money request threads is available or not for task share page?

**Comment by bernhardoj** [comment] 2023-06-18 09:18
Copying over my proposal from the closed issue here https://github.com/Expensify/App/issues/19370

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After doing a money request, when we search for a user, the new chat, search, new group, etc. list will show the money request report and exclude the user that we request the money to.

### What is the root cause of that problem?
The new chat list shows the 5 most recent report and all user, except the user that is already shown in the most recent by checking the `login` property.

Every money request will create a new report (assuming we don't have one) and it's also included in the list and the `login` attribute is the same as the `login` of the user we requested the money to. So, for example we request money to user A. First, the money request report will be included in the most recent and the `login` is added to the exclude list. 
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L680-L683

Then, when we are trying to include the user into the list, we will skip if the user `login` is in the exclude list.
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L688-L692

So, we can only see the money request report in the new chat, but not the user report. This is the first issue of all.

The second issue is, the money request report should be searchable in Search Page only. Removing the report from other page will resolve the first issue in those pages, but not with search page.

### What changes do you think we should make in order to solve the problem?

I guess we don't care about the first issue here, so I'm taking only the 2nd part of my proposal here.

We can exclude money request report from the list just for some pages. We can do the same thing like this where we will pass `includeMoneyRequest` to true for search page and false for new group, new chat, money request participants, etc.:
https://github.com/Expensify/App/blob/bee8fd3e1634fa11761435ef405a3d3efd654b07/src/libs/OptionsListUtils.js#L833-L846
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L593-L609

https://github.com/Expensify/App/assets/50919443/50f0a65a-0eeb-492f-a7ff-9cdc44226688

**Comment by trjExpensify** [comment] 2023-06-19 10:40
> I think iou/expense reports and threads should only be available in search pages. @trjExpensify @JmillsExpensify can you please confirm?

Yeah, you shouldn't be able to start a new chat or new group with an iou/expenseReport or a request itself.

**Comment by StevenKKC** [comment] 2023-06-19 10:52
@fedirjh Excluding money request report from the list can be done without additional parameters, as described in my proposal (https://github.com/Expensify/App/issues/19684#issuecomment-1567348198).

**Comment by AndrewGable** [comment] 2023-06-21 22:14
Not sure why there are so many of us assigned here, but added @bernhardoj

**Comment by bernhardoj** [comment] 2023-06-22 05:07
PR is ready for review

cc: @fedirjh

**Comment by conorpendergrast** [comment] 2023-06-22 13:35
@AndrewGable you were assigned because the process to assign the engineer was changed, so I've unassigned you now!

**Comment by conorpendergrast** [comment] 2023-07-06 09:56
Looks like I missed hiring people for this, so I'll do that so we can get everyone paid

**Comment by conorpendergrast** [comment] 2023-07-06 10:01
All offers sent, and I'll pay them as they are accepted (plus the 50% urgency bonus for @fedirjh and @bernhardoj)

**Comment by conorpendergrast** [comment] 2023-07-06 15:28
Sounds solid to me, I agree. I've created this regression test request: https://github.com/Expensify/Expensify/issues/297694

All done, thanks everyone

**Closed by conorpendergrast** 2023-07-06 15:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
