### ISSUE TITLE
[Hold for #50796] [$250] Contact method - User returned to enter new email step after backgrounding app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51275] opened 2024-10-22 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49445
## Action Performed:
1. Open the app and log in
2. Navigate to the account settings > Profile > Contact method
3. Tap the New contact method button
4. Enter an email that will be used as a secondary login and proceed to the magic code step
5. Background the app
6. Open the app again

## Expected Result:
User lands back on the magic code step

## Actual Result:
User is returned to the enter email step

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/52ffdae4-590e-401e-af4d-48f9f0189125

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848841356939319972</li>
        <li>Upwork Job ID: 1848841356939319972</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-10-22 17:05
Production:

https://github.com/user-attachments/assets/8b5f784e-3a17-45cc-be94-83a2766a3bcd

**Comment by srikarparsi** [comment] 2024-10-22 18:54
Related [PR](https://github.com/Expensify/App/pull/49445)

**Comment by srikarparsi** [comment] 2024-10-22 21:34
Nice, agreed, also able to reproduce this on production

**Comment by srikarparsi** [comment] 2024-10-22 21:38
Going to make this external since it doesn't stem from this [PR](https://github.com/Expensify/App/pull/49445)

**Comment by bernhardoj** [comment] 2024-10-23 01:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is brought back to the email contact field page after backgrounding the app and returning to the app.

### What is the root cause of that problem?
When we return back to the app, we can see that a loading is shown. The loading comes from `AccessOrNotFoundWrapper`, so the modal is unmounted which closes it.
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/settings/Profile/Contacts/NewContactMethodPage.tsx#L120-L121

It loads every time a reconnect is called because it sets `isLoadingReportData` to true.
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L163-L165
https://github.com/Expensify/App/blob/faf48fcaaf9bb1a8dca6e997e3e1a85606a97ace/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L138

Because the page isn't related to a workspace page at all (and we don't pass the policyID), the policy object is always empty.

### What changes do you think we should make in order to solve the problem?

The purpose of `AccessOrNotFoundWrapper` is to [prevent the user from accessing the page from a deep link](https://github.com/Expensify/App/issues/50063#issuecomment-2388882389:~:text=In%20addition%20to%20both%20of%20the%20above%20options%20%2D%20wrap%20NewContactMethodPage%20with%20AccessOrNotFoundWrapper%20to%20avoid%20copilot%20using%20deep%20link%20to%20access%20the%20page.). However, AccessOrNotFoundWrapper is designed for workspace related pages. The usual pattern to show the not found page is by using `FullPageNotFoundView`.

So, the solution is to replace `AccessOrNotFoundWrapper` with `FullPageNotFoundView`
```
<FullPageNotFoundView shouldShow={isActingAsDelegate}>
```

**Comment by kadiealexander** [comment] 2024-10-25 05:28
Reassigning this to a new BugZero team member as I'm going OOO for two weeks. Happy to take it back when I'm back!

**Comment by srikarparsi** [comment] 2024-10-25 17:00
> so issue will be solved along with https://github.com/Expensify/App/issues/50796

Oh nice, do you think you can confirm @Julesssss? And I can put this on hold for that issue if that is the case.

**Comment by Julesssss** [comment] 2024-10-28 09:36
Yeah, lets put this on hold @srikarparsi

**Comment by sonialiap** [comment] 2024-10-28 11:06
Put on hold and moved to weekly

**Comment by sonialiap** [comment] 2024-11-11 16:46
Still on hold for https://github.com/Expensify/App/issues/50796 which is in progress

**Comment by sonialiap** [comment] 2024-11-20 10:15
Still on hold for https://github.com/Expensify/App/issues/50796

**Comment by kadiealexander** [comment] 2024-11-29 01:11
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1732842503817589)

**Closed** 2024-12-01 20:22 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
