### ISSUE TITLE
[$500] Avatar - Default icon Avatar turns complete grey when searching for a new user offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35123] opened 2024-01-25 02:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Turn off internet connection
4. Click on "Search" and scroll down results until you find an user with a default icon
5. Start chat with this user
6. Turn the internet connection back on

## Expected Result:
User expects that once the internet connection is back on, they can see the users profile pic (If there is one)

## Actual Result:
User sees a completely grey icon, even if the user does in fact have a profile pic

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c552359b-e01c-46d5-8431-a51224cf6dd7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011edf7db8b660b8e3</li>
        <li>Upwork Job ID: 1750349018314211328</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2024-01-25 06:19
Not able to reproduce in production

**Comment by ikevin127** [comment] 2024-01-28 01:04
Wasn't able to repro the issue following the actions performed 😞 everything works as expected (tested on local dev).

<details>
<summary> 📽 Video</summary>

https://github.com/Expensify/App/assets/56457735/c51fc47e-89b9-4a05-82bf-8c717f34daf1

</details>

I found a very similar issue while trying to reproduce this one, for which I have a proposal below the issue description 😁

## ☑ Action Performed:
1. Sign up into a new account.
2. Add a profile picture then Logout.
3. Sign into an existing account.
4. Click on "Search" and input the new account's email (with profile pic).
5. Turn off internet connection.
6. Start chat with this user.
7. Turn the internet connection back on.

## → Expected Result:
User expects that once the internet connection is back on, they can see the users profile pic both in the chat header and below in the chat report above the "Say hello!" greeting.

## ⚠ Actual Result:
User sees the stale default avatar above the "Say hello!" greeting, while seeing the actual profile picture in the chat report header.

# 📜 Proposal

### Please re-state the problem that we are trying to solve in this issue

User sees the default avatar above the "Say hello!" greeting, while seeing the actual profile picture in the chat report header.

### What is the root cause of that problem?

The `ReportActionItemCreated.tsx` component uses `memo` but we don't check the equality of the `personalDetails` prop and this causes the chat report picture source to not update when the one from the header updates.

This happens because the memo currently prevents the re-rendering & updating of the personalDetails prop when this updates in onyx as a result of coming back online.

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/pages/home/report/ReportActionItemCreated.tsx#L51

### What changes do you think we should make in order to solve the problem?

In order for the chat report picture source to update when we come back online we have to add an additional check to the `memo`'s propsAreEqual callback function:
- `lodashIsEqual(prevProps.personalDetails, nextProps.personalDetails)`

this ensures than when personalDetails prevProps and nextProps differ the `propsAreEqual` returns false which prompts the component re-render therefore updating the chat profile picture at the same time with the one from the header 🎉

### 📽 Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/4228084b-8cc0-45d1-a386-9f65b7ad8cd4"> | <video src="https://github.com/Expensify/App/assets/56457735/7b85aa20-b682-4d5e-a191-80eef22d0449"> |

</details>

**Comment by isabelastisser** [comment] 2024-01-29 15:08
@akinwale, are you able to reproduce this? If yes, can you please review the proposal above? Thanks!

**Comment by ikevin127** [comment] 2024-01-30 18:05
The bug found and mentioned above was posted here https://github.com/Expensify/App/issues/35378 recently.

The reviewer asked for that issue to be closed after I mentioned this one there, as it will be handled here by my proposal if we decide to move forward with the issue found.

cc @akinwale @isabelastisser

**Comment by isabelastisser** [comment] 2024-01-31 19:21
Bump @akinwale

**Comment by akinwale** [comment] 2024-02-01 15:17
@isabelastisser We can either:
1. Proceed with @ikevin127's [proposal](https://github.com/Expensify/App/issues/35123#issuecomment-1913394765) here, since the reported bug is quite similar, but the OP needs to be updated with the reproduction steps, or
2. Create a new issue which will be handled separately, and close this one.

Please let me know what you think.

**Comment by isabelastisser** [comment] 2024-02-02 03:41
Thanks for the update and for sharing the context, @akinwale! I think we should create a new issue to reflect the update. @lanitochka17 can you please do this? Then please assign me, @akinwale as the C+ and @ikevin127 as the contributor. Please let me know if this possible, thanks!

**Comment by ikevin127** [comment] 2024-02-02 11:46
@mkhutornyi Thanks for mentioning, must've been the big PR merged recently. I can confirm that both issues are solved - not reproducible aymore 🚀

<details>
<summary>MacOS: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/56457735/e1933c1b-abb3-48bb-99d7-24ff70648c70

</details>

cc @isabelastisser @akinwale

**Comment by isabelastisser** [comment] 2024-02-05 13:32
Thanks, team! Closing.

**Comment by kbecciv** [comment] 2024-02-20 14:43
QA team is able to reproduce the issue on build 1.4.43.0

https://github.com/Expensify/App/assets/93399543/dcd9cf24-947e-4260-acbb-de0e419409c1

**Comment by isabelastisser** [comment] 2024-02-22 15:57
Hey @akinwale, let's move forward with @ikevin127 proposal above. Do you agree?

**Comment by akinwale** [comment] 2024-02-22 16:01
@ikevin127 Are you able to reproduce the original issue?

**Comment by ikevin127** [comment] 2024-02-22 16:13
Cannot reproduce.

<details>
<summary>MacOS: Chrome - User with default avatar</summary>

https://github.com/Expensify/App/assets/56457735/7d3a8ebc-336e-45bc-bb74-b44c44784433

</details>

<details>
<summary>MacOS: Chrome - User without default avatar</summary>

https://github.com/Expensify/App/assets/56457735/babbfa78-9f58-4aab-a21d-ff5d0838da50

</details>

**Comment by akinwale** [comment] 2024-02-23 17:42
> @akinwale should we close this?

I think we need to confirm the exact steps to reproduce from QA, since this was initially closed and then reopened.

**Comment by isabelastisser** [comment] 2024-02-26 18:17
Hey @akinwale, are these steps insufficient?

Access staging.new.expensify.com
Sign into a valid account
Turn off internet connection
Click on "Search" and scroll down results until you find an user with a default icon
Start chat with this user
Turn the internet connection back on


Can you please clarify who should provide the exact steps? Thanks!

**Comment by isabelastisser** [comment] 2024-02-27 21:34
Bump @akinwale

**Comment by isabelastisser** [comment] 2024-02-29 20:21
I DM'd @akinwale for an update.

**Comment by akinwale** [comment] 2024-03-01 06:41
I'll try to reproduce this today.

**Comment by akinwale** [comment] 2024-03-02 13:26
@isabelastisser I was unable to reproduce the issue. Tested with a high-traffic account. I also thought it may be possible that this could be specific to the actual user profile that is being tested with, but that doesn't seem to be the case.

https://github.com/Expensify/App/assets/4160319/2f3d2340-46d3-4875-b30d-8d6d8630963f

**Comment by akinwale** [comment] 2024-03-02 13:27
Is it possible that the tester's Internet connection may be blocking the domain (or subdomain) for default avatars?

**Comment by isabelastisser** [comment] 2024-03-04 21:23
I will test tomorrow.

**Comment by isabelastisser** [comment] 2024-03-07 20:57
I'm unable to reproduce this. Closing!

**Closed by isabelastisser** 2024-03-07 20:57 UTC
Labels: Daily, Internal, Overdue, Bug
