### ISSUE TITLE
[HOLD][$2000] Connect Bank Account- Infinite spinner or blank page for app appears after back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14362] opened 2023-01-17 16:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log i with expensifail account
3. Go to Setting - WS - Connect Bank Account
4. Go offline
5. Select Plaid option
6. Back online

## Expected Result:
Infinite spinner or blank page for app is not appear after back online

## Actual Result:
Infinite spinner or blank page for app appears after back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari

**Version Number:** 1.2.55.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212961702-f1e84e08-02d2-4d91-bd85-e5ef0f05400a.mp4

https://user-images.githubusercontent.com/93399543/212961715-6f100ec4-3fd6-42bd-ae89-d30627c32d52.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01225bad74fa616f9b</li>
        <li>Upwork Job ID: 1617347865539796992</li>
        <li>Last Price Increase: 2023-01-30</li>
    </ul>
</details>

**Comment by mateocole** [comment] 2023-01-18 03:03
Going to have an engineer look at this.

**Comment by danieldoglas** [comment] 2023-01-23 02:25
This looks like something we can solve with external contributors. Adding `External` flag.

**Comment by s77rt** [comment] 2023-01-23 13:00
Well at least the app won't let you continue if you are offline. Should we still fix this issue though?
I think it may be related to `react-native-plaid-link-sdk`

**Comment by s77rt** [comment] 2023-01-23 13:24
I can't reproduce on mWeb (Android / Chrome). It seems hard to reproduce reliably.

**Comment by devJesseNorris** [comment] 2023-01-23 14:13
Hello In my opinion, If your team write the clean code, this problem can be easily solved.
Let' s discuss more detail requirements if you are interested in me.

**Comment by danieldoglas** [comment] 2023-01-23 14:19
> Well at least the app won't let you continue if you are offline. Should we still fix this issue though?

Yes. If you regain access to the internet, the page should reload and show the component. We have offline checks to do that.

**Comment by danieldoglas** [comment] 2023-01-23 14:22
> Hello In my opinion, If your team write the clean code, this problem can be easily solved. Let's discuss more detail requirements if you are interested in me.

@devJesseNorris  Please read our [contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) guidelines if you want to contribute.

**Comment by richard-here** [comment] 2023-01-25 03:21
I'm not able to reproduce issue this on Android Chrome.

**Comment by situchan** [comment] 2023-01-25 05:29
This is not reproducible on all envs (dev/staging/production), all platforms.
Might have been fixed in #13236

**Comment by mananjadhav** [comment] 2023-01-26 00:39
@kbecciv the version mentioned in the GH issue is `v1.2.55.0`, whereas the current version is v1.2.59-1. Can you please confirm if you're still able to reproduce this ?

**Comment by kbecciv** [comment] 2023-01-27 15:20
@mananjadhav Checking, update you shortly

**Comment by kbecciv** [comment] 2023-01-27 15:25
@mananjadhav Unable to reproduce the issue with build 1.2.60.0


https://user-images.githubusercontent.com/93399543/215123128-7b8b65b4-5ab0-4b13-a1f7-b8fc4ae400a9.mp4


https://user-images.githubusercontent.com/93399543/215123130-7c0abd1b-f126-46f4-b1c0-076d88543fbd.mp4

**Comment by danieldoglas** [comment] 2023-01-30 16:32
Leaving this on HOLD, let's test it once more and if it doesn't happen, let's close.

**Comment by danieldoglas** [comment] 2023-02-07 14:43
@kbecciv Are you still unable to simulate this?

**Comment by kbecciv** [comment] 2023-02-09 15:59
@danieldoglas Checking again, update you shortly.

**Comment by danieldoglas** [comment] 2023-02-09 23:09
Hm. I've tried that on Chrome iOS and Chrome Android (simulator) and was not able to simulate it in staging. 

I'll look for internal guidance on what to do in this case.

**Closed** 2023-02-22 13:03 UTC
Labels: External, Engineering, Weekly, Needs Reproduction, Help Wanted, Overdue, Bug
