### ISSUE TITLE
The app crashed when an employee requested money for the second time from the admin

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31833] opened 2023-11-24 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30582

## Action Performed:
1. Go to staging.new.expensify.com
2. Create 2 accounts, one will be used as employee and second as an admin
3. Request 1:1 money as employee from the admin
4. Do second request 1:1 money as employee from the admin

## Expected Result:
No crash when r employee request money from the admin

## Actual Result:
App is crashed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc1fc63a-1d99-4aed-8779-5dc515ef7bc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-11-24 19:24
I could not reproduce this on staging. It might have been fixed by https://github.com/Expensify/App/pull/31817. @kbecciv can you please retest on latest staging v1.4.3-3?

**Comment by aldo-expensify** [comment] 2023-11-24 19:39
I does look like the same

**Comment by luacmartins** [comment] 2023-11-24 20:01
Agreed. Just waiting for confirmation from Applause before we can remove the blocker and close

**Comment by kavimuru** [comment] 2023-11-24 22:46
@luacmartins Not able to reproduce by the tester in the latest version 1.4.3-5


https://github.com/Expensify/App/assets/43996225/20f0e38f-f108-45c4-84f4-fbb62ce42cb2

**Comment by luacmartins** [comment] 2023-11-24 22:47
Thank you! Gonna remove the blocker label and close the issue!

**Closed by luacmartins** 2023-11-24 22:47 UTC
Labels: DeployBlockerCash, Engineering, Hourly
