### ISSUE TITLE
[HOLD #41846][$250] Task - Fallback avatar does not update after creating task unless chat header is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40991] opened 2024-04-25 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Assign task
3. Create a task and assign it to a new user
4. Click on the mention in task preview in the main chat
5. Note that the avatar is the colorful one instead of fallback avatar
6. Click on the chat header

## Expected Result:
After the task is created, the fallback avatar should automatically update to the colorful one

## Actual Result:
After the task is created, the fallback avatar does not update until the chat header is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d22196df-be8d-4356-8e56-f3996db1c417

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b7c5310d8438f94</li>
        <li>Upwork Job ID: 1783569498465652736</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-25 15:15
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-25 15:15
We think that this bug might be related to #vip-vsp

**Comment by rlinoz** [comment] 2024-04-25 18:11
Oh, actually the participants of the report are not being updated

<img width="515" alt="image" src="https://github.com/Expensify/App/assets/5201282/f0bbd201-c92c-4b9e-9da0-9a879531c291">

<img width="890" alt="image" src="https://github.com/Expensify/App/assets/5201282/99da687c-feb2-4398-b584-3912fdbecab8">


What is weird is that we have the log lines for the set

<img width="998" alt="image" src="https://github.com/Expensify/App/assets/5201282/7a59591f-8db1-407b-b359-d752d219b685">

**Comment by rlinoz** [comment] 2024-04-25 18:50
Ok, this is happening in prod as well, it just got evident because of how we are handling avatars now.

What we got from `CreateTask` in prod
<img width="761" alt="image" src="https://github.com/Expensify/App/assets/5201282/6ecc7150-660f-4852-be81-258ead3b6841">

The report after `CreateTask` is done, see that the participants are not updated with the `CreateTask` response
<img width="818" alt="image" src="https://github.com/Expensify/App/assets/5201282/5d0b37db-1d38-4504-9202-0f399de5ed88">

**Comment by rlinoz** [comment] 2024-04-25 18:50
Removing the deploy blocker label because of the above.

**Comment by greg-schroeder** [comment] 2024-05-01 22:11
Same as above

**Comment by fitd-tech** [comment] 2024-05-02 00:15
I've spent a good amount of time trying to debug this issue and I seem to have hit a wall, but maybe I can get further if someone sees what the issue is here.

@rlinoz Thanks for your comments above! I can trace the Onyx update for the task all the way to this flush function use for writing to Onyx:

https://github.com/Expensify/App/blob/a69e99e0640e4377a1a258414e50862a76381c7c/src/libs/actions/QueuedOnyxUpdates.ts#L16-L20

The SET update is included in the array of updates passed to `Onyx.update()`, but is never reflected in the OnyxDB. As @rlinoz noted, the `participants` values are shown in the logs in the SET update. 

I would hesitate to blame this on the internals of `react-native-onyx` - I think it's much more likely something is happening within the FE that can be fixed. Maybe a value is being mutated unexpectedly before the update? Maybe there is something that has to be called after the Onyx update that I'm not aware of? Maybe the data is bad?

I haven't confirmed 100% that adding the correct `participants` to the task report will solve the main issue, but I think it's the right path.

**Comment by rlinoz** [comment] 2024-05-06 18:18
>I haven't confirmed 100% that adding the correct participants to the task report will solve the main issue, but I think it's the right path.

If I am not mistaken the fallback avatar is shown because we don't have the personal details of the participant, once we update the participant we start having the personal detail and can show the correct avatar.

**Comment by rlinoz** [comment] 2024-05-08 19:17
I think because the fallback avatar PR was reverted this is not reproducible anymore, which makes things harder to test and come up with proposals.

Maybe we HOLD on that issue?

**Comment by Kicu** [comment] 2024-05-09 07:24
@rlinoz FYI I'm working on returning the original PR that got reverted here: https://github.com/Expensify/App/pull/41846 - you might find this relevant.

That being said I don't have any solution for this specific problem as my PR only deals with _how_ we calculate the correct avatar to display, but it tries to rely 100% on data from backend/onyx when using `details.avatar` and it simplifies displaying FallbackAvatar.
I didn't touch any api calls or onyx logic other than removing computing of default avatar on the FE side. 

@s77rt fyi

**Comment by greg-schroeder** [comment] 2024-05-10 23:35
Okay so do you think we should hold @rlinoz?

**Comment by rlinoz** [comment] 2024-05-13 11:46
Yep, holding on https://github.com/Expensify/App/pull/41846

**Comment by mvtglobally** [comment] 2024-05-13 14:14
Issue not reproducible during KI retests. (First week)

**Comment by rlinoz** [comment] 2024-05-15 19:23
Moving to weekly since this is on hold.

**Comment by greg-schroeder** [comment] 2024-05-22 00:21
PR we're held on is still going through review

**Comment by rlinoz** [comment] 2024-05-30 20:14
PR is deployed in staging, let me retest this.

**Comment by rlinoz** [comment] 2024-05-30 20:21
Can't repro anymore, avatar is being updated after the `CreateTask` call is done, so closing.

**Closed by rlinoz** 2024-05-30 20:21 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
