### ISSUE TITLE
[$250]  Chat - Error message reappears after sending another message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44824] opened 2024-07-04 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4693768
**Email or phone of affected tester (no customers):** vdargentotest+web070324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat.
2. Send a corrupted PDF file (there is one attached to this report).
3. Verify an error message appears.
5. Dismiss the error message by clicking on the "x" icon.
6. Send another message.
7. Verify the error message that was already dismissed reappears.

## Expected Result:
The error message should not reappear.

## Actual Result:
The error message reappears after sending another message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e2c8ced5-859b-43af-93d5-fb7991919527

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167c1b57ade6a9fb4</li>
        <li>Upwork Job ID: 1810456336736930787</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103158918</li>
<li>nyomanjyotisa | Contributor | 103158919</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by izarutskaya** [comment] 2024-07-04 13:07
We think this issue might be related to the  #vip-vsb

**Comment by VictoriaExpensify** [comment] 2024-07-05 00:31
I haven't had a chance to look at this, will come back to it on Monday

**Comment by VictoriaExpensify** [comment] 2024-07-08 23:32
I agree this is an issue and it should be fixed. Also agree that this is best suited to VSB

**Comment by alitoshmatov** [comment] 2024-07-09 20:21
Thank you for your proposal @nyomanjyotisa . Can you expand on your RCA, why exactly having action data in failure data is causing this, I mean failure data is applied when request fails which is happening instantly when error is shown, then we are removing report action with error in https://github.com/expensify/app/blob/1f7c785753747a84b84c859cbdf4503447fc7bac/src/libs/actions/ReportActions.ts#L80

Moreover this piece of code was there for a long time and why now it is causing this?

**Comment by amunim** [comment] 2024-07-13 08:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error messages re-appear

### What is the root cause of that problem?

`queuedOnyxUpdates` is not cleared if an error is thrown, this makes it stay in cache and apply again once we try to send a new message.
https://github.com/Expensify/App/blob/fef8ef8c30e69b1807c9ec958e744dbc37816597/src/libs/actions/QueuedOnyxUpdates.ts#L16-L20

### What changes do you think we should make in order to solve the problem?

We add a catch clause like
```
    .catch(err => {
        console.error(err);
        queuedOnyxUpdates = [];
    });
```
**or**
![image](https://github.com/user-attachments/assets/aea5a034-9e10-409b-8ee2-d8fed365cc69)

we check if the error is failed to execute 'put' on 'IDBObjectStore', then suppress the error, and splice only that, else throw again (a moderator can with experience in the project can answer)

### What alternative solutions did you explore? (Optional)

**Comment by amunim** [comment] 2024-07-13 08:34
Contributor details
Your Expensify account email: abdulmunim2005@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016f42c0501a199670

**Comment by VictoriaExpensify** [comment] 2024-07-16 07:00
@alitoshmatov - what are your thoughts on @nyomanjyotisa [updated proposal](https://github.com/Expensify/App/issues/44824#issuecomment-2212327374)?

**Comment by alitoshmatov** [comment] 2024-07-17 16:31
That makes sense @nyomanjyotisa 

We can go with @nyomanjyotisa 's [proposal](https://github.com/Expensify/App/issues/44824#issuecomment-2212327374)

C+ reviewed 🎀 👀 🎀

**Comment by cead22** [comment] 2024-08-06 20:14
The PR was closed because the issue got fixed elsewhere. That said, contributors should still receive payement.  @VictoriaExpensify can you handle that please?

**Comment by mallenexpensify** [comment] 2024-08-06 23:21
@VictoriaExpensify both @nyomanjyotisa and @alitoshmatov are due compensation here.  Per the [internal SO](https://stackoverflowteams.com/c/expensify/questions/8590)
> If a contributor has been hired for a job and we decide to close the job before it is successfully completed, full payment is due for C+ and the contributor. One caveat here might be if the hired contributor wasn't working on their PR with urgency. If you're unsure, post in #bug-zero.

**Comment by ahmedGaber93** [comment] 2024-08-19 20:47
We have the same issue after uploading workspace avatar here https://github.com/Expensify/App/issues/47150.  Is it should fix here? Asking because we have an accepted proposal here, but nothing there.
@cead22 @alitoshmatov @nyomanjyotisa

**Comment by alitoshmatov** [comment] 2024-08-27 19:20
It does look like both are similar, not sure if our solution would have solved this though. @nyomanjyotisa Can you look into https://github.com/Expensify/App/issues/47150 issue

**Comment by ahmedGaber93** [comment] 2024-09-02 11:08
@nyomanjyotisa bump https://github.com/Expensify/App/issues/44824#issuecomment-2313333813

**Comment by alitoshmatov** [comment] 2024-09-03 17:32
https://github.com/Expensify/App/issues/47150#issuecomment-2325352019 They decided to handle the issue there. 

Next step for this issue is to handle payment and close the issue

cc: @VictoriaExpensify

**Comment by mallenexpensify** [comment] 2024-09-04 21:46
@VictoriaExpensify plz pay both @alitoshmatov and @nyomanjyotisa since @nyomanjyotisa was hired and raised a PR, only for the bug to fixed _magically_  (right?)  Carlos commented [here too](https://github.com/Expensify/App/pull/45621#issuecomment-2272066383)

**Comment by VictoriaExpensify** [comment] 2024-09-11 00:39
**Payment Summary:**
Contributor: @nyomanjyotisa paid $250 via Upwork
Contributor+: @alitoshmatov paid $250 via Upwork

[Upwork Job](https://www.upwork.com/ab/applicants/1810456336736930787/hired)

**Closed by VictoriaExpensify** 2024-09-11 00:39 UTC
Labels: Reviewing, External, Monthly, Bug
