### ISSUE TITLE
[$250] mWeb - chat-After deleting mark us unread msg, new green line shown in new msg sent.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47735] opened 2024-08-20 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a chat
3. Send a message
4. Long press the message and select mark as unread
5. Now long press the message and delete the message
6. Send a new message now

## Expected Result:
Mark as unread &delete a message, after that if we send a new message, new message green line must not be shown above

## Actual Result:
Mark as unread &delete a message, after that if we send a new message, new message green line is shown above

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/23997c7d-8907-4c27-8ad7-09dc09f2cacc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb6fb45334b2068a</li>
        <li>Upwork Job ID: 1828326431288711476</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103784660</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-20 17:39
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-20 17:40
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment] 2024-08-21 09:42
/## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are not updating unread marker time when the last unread report action deleted

### What changes do you think we should make in order to solve the problem?

We can update unread marker time when some of the report actions deleted, we can add new condition to indicate some report action deleted add this condition: `mostRecentReportActionCreated >= prevMostRecentReportActionCreated`

Change [this code](https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L277-L291) to:

```tsx
    const mostRecentReportActionCreated = sortedVisibleReportActions[0]?.created ?? '';
    const prevMostRecentReportActionCreated = usePrevious(mostRecentReportActionCreated);
    useEffect(() => {
    
        if (unreadMarkerReportActionID) {
            return;
        }
    
    
        if (mostRecentReportActionCreated <= unreadMarkerTime && mostRecentReportActionCreated >= prevMostRecentReportActionCreated) {
            return;
        }
    
        setUnreadMarkerTime(mostRecentReportActionCreated);
        setMessageManuallyMarkedUnread(0);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bernhardoj** [comment] 2024-08-21 11:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unread line indicator shows again after deleting the unread message and add a message.

### What is the root cause of that problem?
When we marked a message as unread, we set the `unreadMarkerTime` state to the message created time - 1.
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L255-L259

which will trigger the recalculation of the unread report action ID.
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L224-L250

When we delete the message, the `unreadMarkerTime` state stays the same. So, when a new message is added, the `unreadMarkerTime` will still be smaller than the new message created time, thus, the new message is considered unread.

### What changes do you think we should make in order to solve the problem?

We need to update the `unreadMarkerTime` whenever the report action is deleted. We already have this `useEffect` that updates the `unreadMarkerTime` to the latest report action, only if there is no current unread report action (which means the report is read) AND if the latest report action created is bigger than the current unread marker time, which means the current logic only covers updating the unread marker time when adding a new message.

https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L277-L291

We can expand this by covering both delete and add cases by removing this condition (or changing the condition to strictly equal so we won't call the set state if the value is the same).
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L283-L285

This way, if a report is read, adding a new message or deleting the last message will update the unread marker time to the latest report action.

As a note, when we delete the last unread message, the `unreadMarkerReportActionID` is empty, so the effect above will work.

**Comment by alexpensify** [comment] 2024-08-22 22:29
I'll add this to my task list to test

**Comment by alexpensify** [comment] 2024-08-27 07:00
@c3024 - when you get a chance, please review the proposals and determine whether one will fix this issue. Thanks! 

--- 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by c3024** [comment] 2024-08-31 07:50
Thank you all for your proposals.

I think we should set `setUnreadMarkerTime` and `setMessageManuallyMarkedUnread` without necessarily waiting to send another message. Therefore, resetting `messageManuallyMarkedUnread` in the `scrollToBottomForCurrentUserAction` does not seem to be the best choice, as suggested [here](https://github.com/Expensify/App/issues/47735#issuecomment-2299778672).

The change in the `useEffect` as suggested in the other solutions looks correct to me. Simply removing this check here
https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/pages/home/report/ReportActionsList.tsx#L283-L285
is not appropriate because it was deliberately added [here](https://github.com/Expensify/App/commit/716cd0995af4aba8585051f23995803b92814bdb) to minimize state changes.

Both solutions suggested [here](https://github.com/Expensify/App/issues/47735#issuecomment-2301619030) and [here](https://github.com/Expensify/App/issues/47735#issuecomment-2301806953) fix the issue correctly and are somewhat equivalent because for a read report, the `unreadMarkerTime` is essentially the same as `prevMostRecentReportActionCreated`.

Since the solution by @bernhardoj appears simpler to me, I think we can go with his solution [here](https://github.com/Expensify/App/issues/47735#issuecomment-2301806953) of strictly equal comparison of `mostRecentReportActionCreated` and `unreadMarkerTime`.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment] 2024-09-03 06:35
PR is ready

cc: @c3024

**Comment by alexpensify** [comment] 2024-09-03 23:12
Catching up from being OOO, I see the PR is waiting to go to production.

**Comment by c3024** [comment] 2024-09-08 14:35
Automation failed here. PR Deployed to production on 6-Sep. Should be on HOLD till 13-Sep or 14-Sep for payment.

cc: @alexpensify

**Comment by alexpensify** [comment] 2024-09-13 15:38
Payouts due: 2024-09-12

- [ ] Contributor: $250 @bernhardoj - please submit a request in Chat. Thanks! 
- [ ] Contributor+: $250 @c3024 - Paying via Upwork

Upwork job is [here](https://www.upwork.com/jobs/~01fb6fb45334b2068a).

**Comment by alexpensify** [comment] 2024-09-13 15:45
Closing - I've completed the process in Upwork.

**Comment by bernhardoj** [comment] 2024-09-13 15:45
Requested in ND.

**Closed by alexpensify** 2024-09-13 15:45 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-09-16 21:12
$250 approved for @bernhardoj
