### ISSUE TITLE
[$1000] [HOLD for payment 2023-05-23] [Manual Requests] Fix participants on the IOUConfirmation page in the case when an admin requests money from the workspace

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#18708] opened 2023-05-10 10:59 UTC
Coming from https://github.com/Expensify/App/pull/18215#issuecomment-1541909985

When admin requests money from their workspace as a employee, all the other members of the workspace are shown as participants on the confirmation page when the request is being made

**Repro steps**

1. Create a workspace as userA (the admin).
2. Invite userB
3. Navigate to your own workspace chat as userA
4. Tap `+` > `Request Money` > enter an amount > next
5. Observe that the list of participants displayed underneath `To` are %workspaceName% & userB on the confirmation screen. 

Note: The bug **only** occurs when the admin of the workspace requests money in their own workspace chat. In the above example, if userB requested money in their own workspaceChat, then the `To` would only show the %workspaceName% as is expected: 

![image](https://github.com/Expensify/App/assets/16232057/36d1a7d8-a002-4350-b911-7d7615e8de35)

cc @luacmartins @Julesssss 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f72dca339218ee5</li>
        <li>Upwork Job ID: 1661757492474519552</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by s77rt** [comment] 2023-05-10 11:01
> When admin requests money from their workspace as a employee, they are shown as a participant in the IOU preview same as the workspace which is incorrect.


Just a clarification, the admin is not shown as participant, the other members are.

**Comment by mountiny** [comment] 2023-05-10 11:26
Assinged @trjExpensify for payments and @s77rt to fix this

**Comment by trjExpensify** [comment] 2023-05-10 11:26
Dope! @s77rt to confirm, are these the repro steps?

1. Create a workspace as userA (the admin).
2. Invite userB 
3. As userA request money in your own workspace chat
4. Click on the IOUPreview in the chat
5. Observe that the list of participants underneath `To:` are WorkspaceName & userB

Also, the bug **only** occurs when the admin of the workspace requests money in their workspace chat. In the above example, if userB requested money in their own workspaceChat, would a list of all workspace members appear underneath the `To` as well?

**Comment by s77rt** [comment] 2023-05-10 11:37
@tjferriss Yes, correct, but not need to finish the request process you can see that the participant list is incorrect at the confirmation step.

As userB the participants list only contains the workspace (no other members) which is the expected behaviour.

Checking now, will post more info asap

**Comment by trjExpensify** [comment] 2023-05-10 12:04
Poor TJ man, always getting pinged for @trjExpensify. 😅 😂 

>Yes, correct, but not need to finish the request process you can see that the participant list is incorrect at the confirmation step.

Ah okay, got it. I've updated the steps and added them to the OP for posterity.

**Comment by trjExpensify** [comment] 2023-05-10 12:05
>The screenshot doesn't align with the issue.

Yeah, the title of this issue is also wrong. Look at the video it's on the IOUConfirmation screen https://github.com/Expensify/App/pull/18215#issuecomment-1541909985

**Comment by trjExpensify** [comment] 2023-05-10 13:54
>Checking now, will post more info asap

Any luck @s77rt? (If there's a slack thread somewhere for this I missed, feel free to point me to it).

**Comment by s77rt** [comment] 2023-05-10 13:54
a sec.. writing :grin:

**Comment by s77rt** [comment] 2023-05-10 14:14
## Problem
- The issue is only reproducible on admin account because we create policy expense chats only for the admin. I'm not sure if this is intended or not. cc @bondydaa since you worked on https://github.com/Expensify/App/pull/16764.
- We get many participants on admin due to the above note. And also because we are not filtering the reports properly on [`getPolicyExpenseReportOptions`](https://github.com/Expensify/App/blob/e48e87574f4b45e0823e9c714cadcf99151a4241/src/libs/OptionsListUtils.js#L102). But I'm not sure why we are filtering the `policyExpenseReports` in the first place. Why don't we just verify the passed report itself. Is there any cases where this function would return an array with more than 1 report? cc @cristipaval since you worked on https://github.com/Expensify/App/pull/17132.


## Solution
I think the straightforward solution is to filter the report based on `isOwnPolicyExpenseChat` to differentiate between the workspace report and the other policy expense reports.



<details>

<summary>diff (may change based on point 2)</summary>

```diff
diff --git a/src/libs/OptionsListUtils.js b/src/libs/OptionsListUtils.js
index 83a0b53b40..6dceeb3308 100644
--- a/src/libs/OptionsListUtils.js
+++ b/src/libs/OptionsListUtils.js
@@ -100,26 +100,21 @@ Onyx.connect({
  * @returns {Array}
  */
 function getPolicyExpenseReportOptions(report) {
-    if (!ReportUtils.isPolicyExpenseChat(report)) {
-        return [];
-    }
-    const filteredPolicyExpenseReports = _.filter(policyExpenseReports, (policyExpenseReport) => policyExpenseReport.policyID === report.policyID);
-    return _.map(filteredPolicyExpenseReports, (expenseReport) => {
-        const policyExpenseChatAvatarSource = ReportUtils.getWorkspaceAvatar(expenseReport);
-        return {
-            ...expenseReport,
-            keyForList: expenseReport.policyID,
-            text: expenseReport.displayName,
+    return [
+        {
+            ...report,
+            keyForList: report.policyID,
+            text: report.displayName,
             alternateText: Localize.translateLocal('workspace.common.workspace'),
             icons: [
                 {
-                    source: policyExpenseChatAvatarSource,
-                    name: expenseReport.displayName,
+                    source: ReportUtils.getWorkspaceAvatar(report),
+                    name: report.displayName,
                     type: CONST.ICON_TYPE_WORKSPACE,
                 },
             ],
-        };
-    });
+        },
+    ];
 }
 
 /**
diff --git a/src/pages/iou/MoneyRequestModal.js b/src/pages/iou/MoneyRequestModal.js
index b1bfb9f1ff..abee99e4e9 100644
--- a/src/pages/iou/MoneyRequestModal.js
+++ b/src/pages/iou/MoneyRequestModal.js
@@ -111,7 +111,7 @@ const MoneyRequestModal = (props) => {
     const [previousStepIndex, setPreviousStepIndex] = useState(-1);
     const [currentStepIndex, setCurrentStepIndex] = useState(0);
     const [selectedOptions, setSelectedOptions] = useState(
-        ReportUtils.isPolicyExpenseChat(props.report)
+        ReportUtils.isPolicyExpenseChat(props.report) && props.report.isOwnPolicyExpenseChat
             ? OptionsListUtils.getPolicyExpenseReportOptions(props.report)
             : OptionsListUtils.getParticipantsOptions(props.report, props.personalDetails),
     );
```
</details>

**Comment by trjExpensify** [comment] 2023-05-10 14:35
>because we create policy expense chats only for the admin

Are you saying that a policyExpenseChat ("Workspace chat") doesn't get created for anyone other than an admin on the workspace? 🤔 I would find that very strange if it was the case. Every member of a workspace should have a workspace chat.

**Comment by mountiny** [comment] 2023-05-10 15:02
> The issue is only reproducible on admin account because we create policy expense chats only for the admin. I'm not sure if this is intended or not.

They are created, maybe the optimistic part does not work smoothly but they are being created for sure

<img width="1194" alt="image" src="https://github.com/Expensify/App/assets/36083550/e705814b-33fa-410e-b7b1-677ecb8e5c8d">


I dont think your solution is ideal in this case, the problem is that the getPolicyExpenseReportOptions returns all the options for the user and its intended for the use in the Participants selection view. But we also use the results in [here](https://github.com/Expensify/App/blob/46390d6355272188cafb8e7e879bce112ba9817a/src/pages/iou/MoneyRequestModal.js#L387) for the confirmation page and we check if the user is not same. Its honestly a bit confusing as its set to the state

I think there is an easier fix, making PR

**Comment by s77rt** [comment] 2023-05-10 16:02
@trjExpensify @mountiny I'm not referring to the _main_ workspace chat. This is created for all. I'm referring to the other member-2-member policy chats. The ones with avatar of workspace visible under member avatars. Those only exist for the admin.

![Screenshot from 2023-05-10 16-58-11](https://github.com/Expensify/App/assets/16493223/5bdb1b97-0209-4942-86ea-f3eac1ba11dc)

**Comment by trjExpensify** [comment] 2023-05-10 17:08
Ah, I see. That's still a `policyExpenseChat` workspace chat, it just has a different title for the admin, as it's not their own. 👍 

@mountiny put a PR up with the fix for this, do you want to take a look through that?

**Comment by s77rt** [comment] 2023-05-10 17:17
@trjExpensify Right, but for members there seems to be only one `policyExpenseChat`. The PR looks good, just discussing some more details in Slack. Will get to that asap.


Hey I tagged you correctly twice in a row. That's an achievement :sweat_smile: :tada:

**Comment by s77rt** [comment] 2023-05-17 12:05
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/17132
- The offending PR has been commented on: https://github.com/Expensify/App/pull/17132#issuecomment-1551263212
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1684325139874209
- Determine if we should create a regression test for this bug: No

**Comment by trjExpensify** [comment] 2023-05-25 15:35
Alrighty, @s77rt sent you an offer [on this job](https://www.upwork.com/jobs/~019f72dca339218ee5) for $1,000 for the C+ review.

**Comment by s77rt** [comment] 2023-05-25 16:29
I'm not sure if I am eligible for payment here as I didn't get to finish the reviewer checklist.

**Comment by mountiny** [comment] 2023-05-25 17:13
I think we can do a partial $250 because there was no checklist but you have helped. Does that work?

**Comment by s77rt** [comment] 2023-05-25 17:16
Sounds good!

**Comment by s77rt** [comment] 2023-05-25 17:20
@trjExpensify Can you please adjust the offer?

**Comment by trjExpensify** [comment] 2023-05-25 17:32
Yep, done!

**Comment by s77rt** [comment] 2023-05-25 17:33
@trjExpensify Accepted! Thanks!

**Comment by trjExpensify** [comment] 2023-05-25 17:34
Settled up!

**Closed by trjExpensify** 2023-05-25 17:34 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
