### ISSUE TITLE
[$500]  Distance - Searching for valid addresses does not return any result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34726] opened 2024-01-18 13:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Distance
2. Click Start
3. Enter a valid address (88 kearny street)

## Expected Result:
The search returns relevant results

## Actual Result:
The search does not return any results. It shows "No results found"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f205156d-f35b-4e13-bde8-ac53a78e4596

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e55869855913665e</li>
        <li>Upwork Job ID: 1747978396462637056</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 13:45
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by abzokhattab** [comment] 2024-01-18 14:43
https://github.com/Expensify/App/blob/c5f84b6a5c744e020fbb467f085931ce81534c37/src/components/AddressSearch/index.tsx#L298-L301


## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Searching for valid addresses does not return any result
### What is the root cause of that problem?

here no result is shown whenever the user is not typing

https://github.com/Expensify/App/blob/c5f84b6a5c744e020fbb467f085931ce81534c37/src/components/AddressSearch/index.tsx#L298-L301


however the problem is that if the user stops typing and doesnt blur or change the focus .. the isTyping stays as true. causing the noresult to show 

 
### What changes do you think we should make in order to solve the problem?


1. either we can remove the `!isTyping` from the condition above 
2. or we use  timeout to set the the isTyping to false after some time we define:

like this:


Add a new state to keep track of the typing timeout reference:

```js
const [typingTimeout, setTypingTimeout] = useState(null);
```

Update the onInputChange function inside the textInputProps of the GooglePlacesAutocomplete component. You'll clear the previous timeout (if any) and set a new timeout every time the user types something. If the user stops typing, the timeout function will set isTyping to false after the delay:

```js
onInputChange: (text: string) => {
    setSearchValue(text);
    setIsTyping(true);

    // Clear the previous timeout
    if (typingTimeout) {
        clearTimeout(typingTimeout);
    }

    // Set a new timeout
    const newTimeout = setTimeout(() => {
        setIsTyping(false);
    }, 1500); // 1500ms delay, adjust as needed
    setTypingTimeout(newTimeout);

    if (inputID) {
        onInputChange?.(text);
    } else {
        onInputChange({street: text});
    }

    if (!text && !predefinedPlaces.length) {
        setDisplayListViewBorder(false);
    }
},
```

**Comment by bernhardoj** [comment] 2024-01-18 14:48
Looks like an internal issue
<img width="697" alt="image" src="https://github.com/Expensify/App/assets/50919443/087ed3de-6afd-40c2-9f73-bdb891b08142">

```
"This IP, site or mobile application is not authorized to use this API key. Request received from IP address x.x.x.x, with empty referer"
```

Sometimes works, sometimes not.

**Comment by kadiealexander** [comment] 2024-01-23 03:25
Thanks for the context @bernhardoj! Making this internal.

**Comment by kadiealexander** [comment] 2024-01-23 23:12
@parasharrajat our process has changed! @dylanexpensify will review this in time and assign it a priority, and an engineer from his project will look into it.

**Comment by mvtglobally** [comment] 2024-01-30 04:58
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2024-02-02 03:05
@parasharrajat any updates here?

**Comment by Gonals** [comment] 2024-02-06 12:11
I have not been able to reproduce this in prod, staging, or dev. Seem like we weren't able to reproduce it during KI retests either, so this seems to have been fixed. Closing.

**Closed by Gonals** 2024-02-06 12:11 UTC
Labels: Daily, Internal, Help Wanted, Bug, Hot Pick, retest-weekly
