### ISSUE TITLE
[HOLD for payment 2024-10-14] [HOLD for payment 2024-10-11] Track expense - "Just track it" is present from actionable whisper options which causes error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50048] opened 2024-10-02 11:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+sd34@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense.
4. Click Submit it to someone from the actionable whisper.
5. Click Just track it (don’t submit it).
6. Click Track expense.

## Expected Result:
In Step 5, the option "Just track it (don’t submit it)" should not be present when submitting track expense to someone.

## Actual Result:
In Step 5, the option "Just track it (don’t submit it)" is present when submitting track expense to someone.
When selecting the option, it ends up tracking the expense again to self DM and this leads to infinite loading and RBR in LHN.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4c57bab3-52a9-482c-a6e7-f8b397cce2bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by nkdengineer** [comment] 2024-10-02 11:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 5, the option "Just track it (don’t submit it)" is present when submitting track expense to someone.
When selecting the option, it ends up tracking the expense again to self DM and this leads to infinite loading and RBR in LHN.

### What is the root cause of that problem?
We only not showing this option if the `reportID` is the selfDM report

https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L79


### What changes do you think we should make in order to solve the problem?
We should add the check `IOUUtils.isMovingTransactionFromTrackExpense` to prevent showing this option if we're moving transaction from track expense

```
const shouldDisplayTrackExpenseButton = !!selfDMReportID || IOUUtils.isMovingTransactionFromTrackExpense(action);
```

https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L79

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-10-02 11:33
Regression from https://github.com/Expensify/App/pull/49007

**Comment by mjasikowski** [comment] 2024-10-02 13:26
Confirmed to be under `combinedTrackSubmit` beta, therefore not blocking

**Comment by mjasikowski** [comment] 2024-10-02 13:29
Assigning @fedirjh as the original C+
@fabioh8010 can you leave a comment here so I can assign this issue to you as well?

**Comment by grgia** [comment] 2024-10-02 14:40
I can take this one @mjasikowski 

Offending line is here - 
https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L79

We can first this with this PR to prevent ever showing the button to anyone not on the beta https://github.com/Expensify/App/pull/50068

But we should really have @fabioh8010 take this as a follow up to prevent showing it if you don't click to this screen from the create menu

**Comment by grgia** [comment] 2024-10-02 14:46
Update, I fixed it in my PR, I'll add @fabioh8010 as a reviewer

**Comment by fabioh8010** [comment] 2024-10-02 15:08
Reviewed from my side and approved!

**Comment by isabelastisser** [comment] 2024-10-15 13:40
I was OOO yesterday. I will review this today!

**Comment by isabelastisser** [comment] 2024-10-15 20:13
I believe the payment summary above is incorrect. I see that @grgia assigned @fabioh8010 to review the PR, so payment should be made to @fabioh8010 only. 

@grgia @fabioh8010, please confirm before I can make the payment. Thanks!

**Comment by fabioh8010** [comment] 2024-10-16 07:27
@isabelastisser I'm a contractor from an expert agency (Callstack), so no payment is required 🙂

**Comment by isabelastisser** [comment] 2024-10-16 17:09
Got it, thanks! We are all set then.

**Closed by isabelastisser** 2024-10-16 17:09 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
