### ISSUE TITLE
[$500] Web - Not found page display briefly when we access the `PrivateNotesListPage` via deeplink

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27704] opened 2023-09-18 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Click on the header of the admin room > private notes
3. Copy the URL
4. Logout and sign in with the URL again

## Expected Result:
Not found page shouldn't display briefly

## Actual Result:
Not found page display briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** yes
**Reproducible in production?:**  new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d2fa0c15-876b-40fd-9a30-9dc03bf25f74

https://github.com/Expensify/App/assets/93399543/0842a9cb-9ce2-4497-ac0b-246ddcac9117

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694962751826829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e6deeec4e90fc66</li>
        <li>Upwork Job ID: 1703840373970780160</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reporter | 27179554</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-18 18:37
Proposal by: @dukenv0307
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694962751826829

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Not found page display briefly when we access the `PrivateNotesListPage` via deep link
### What is the root cause of that problem?
When we access it via deep link, the report needs to load from `openApp` API. So the not found page displays briefly before the `openApp` API is complete
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesListPage.js#L122
### What changes do you think we should make in order to solve the problem?
We should subscribe `isLoadingReportData` from Onyx and update the condition to display the loading page while the report is loading. We also should move the `FullScreenLoadingIndicator` outside to make sure it will not display after the not found page is displayed
```
const shouldShowLoading = (isLoadingReportData && _.isEmpty(report.reportID)) || (report.isLoadingPrivateNotes && _.isEmpty(lodashGet(report, 'privateNotes', {})));
    const shouldShowNotFound = !shouldShowLoading && (_.isEmpty(report.reportID) || (network.isOffline && _.isEmpty(lodashGet(report, 'privateNotes', {}))));
if (shouldShowLoading) {
    return (
        <FullScreenLoadingIndicator />
    )
}
return (
    <ScreenWrapper includeSafeAreaPaddingBottom={false}>
        <FullPageNotFoundView
            shouldShow={shouldShowNotFound}
            onBackButtonPress={() => Navigation.goBack()}
        >
            <HeaderWithBackButton
                title={translate('privateNotes.title')}
                shouldShowBackButton
                onCloseButtonPress={() => Navigation.dismissModal()}
                onBackButtonPress={() => Navigation.goBack(ROUTES.getReportDetailsRoute(report.reportID))}
            />
            {_.map(privateNotes, (item, index) => getMenuItem(item, index))}
        </FullPageNotFoundView>
    </ScreenWrapper>
);
```
With `PrivateNotesEditPage` and `PrivateNotesViewPage`, because we don't need to call any API in this page, we can use `withReportIDOrNotFound` to display loading page as well
### What alternative solutions did you explore? (Optional)
NA
### Result
[Screencast from 17-09-2023 22:14:43.webm](https://github.com/Expensify/App/assets/129500732/c13364ae-227c-4939-a715-4c33403f3273)

**Comment by salonikumawat28** [comment] 2023-09-19 12:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page display briefly when we access the `PrivateNotesListPage` via deeplink

### What is the root cause of that problem?
To show `NotFoundView`, we rely on condition:
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesListPage.js#L122
and it returns `true` for few millis because  `report.reportID` is not present for time being as the report data is not yet fetched.

### What changes do you think we should make in order to solve the problem?
#### Solution Analysis
Before jumping to solution, here is the solution analysis:
There are three interesting scenarios for `LoadingIndicator` and `NotFoundView` pages here:
1. We are trying to load notes of a report which is already loaded in the client - 
a. Fetch notes data and show loading icon until notes are fetched.
b. If notes fetch successful, and notes are not empty, show the notes list.
c. If notes fetch successful and notes are empty, show notes list with empty data.
d. If notes fetch was unsuccessful (like network is offline), show `NotFoundView`
2. We are trying to load notes of an invalid report id - In this case we don't want to fetch notes before report data is fetched because notes for invalid report id is returned as empty with a valid 200 response. So we should do following:
a. Until report data is fetched, show loading icon.
b. As report data fails to load because report id was invalid, show `NotFoundView`.
3. We are trying to load notes of an valid report which is not yet present in client - Since we don't know whether the report is valid or not, we still need to wait for report data to be fetched before fetching notes:
a. Until report data is fetched, show loading icon.
b. If report data fails to load, show `NotFoundView`.
c. If report data is successful, then fetch notes data and show loading icon until notes are fetched.
d. If notes fetch successful, and notes are not empty, show the notes list.
e. If notes fetch successful and notes are empty, show notes list with empty data.
f. If notes fetch was unsuccessful (like network is offline), show `NotFoundView`

Point 3 covers all other points.

#### Solution
We should use `withReportOrNotFound` for `PrivateNotesListPage` similar to what we use for other `Report` subpages like `ReportSettingsPage`. This ensures that we wait for report data to be fetched before fetching notes. This ensures that report is valid before fetching notes.

``` js
export default compose(
    withLocalize,
    withReportOrNotFound,
    withOnyx({
        report: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${route.params.reportID.toString()}`,
        },
        session: {
            key: ONYXKEYS.SESSION,
        },
        personalDetailsList: {
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
        },
    }),
    withNetwork(),
)(PrivateNotesListPage);
``` 
After applying the solution, here are the videos of different scenarios:
Valid report with notes:

https://github.com/Expensify/App/assets/72411385/f62930b9-6957-486b-a7cb-54369ed20a8a

Invalid report:

https://github.com/Expensify/App/assets/72411385/3707bf86-f6e3-473f-8909-d87b1e99afdc

Valid report without notes:

https://github.com/Expensify/App/assets/72411385/029306d5-3330-49e5-ab72-86f5878f85bd

### What alternative solutions did you explore? (Optional)
#### Solution exploration 1
Instead of using `report.reportId` in `PrivateNotesListPage`, use `route.params.reportId` as `report.reportId` will be empty until report data is fetched. Problem with this approach is that notes will fetch with a reportId which might be invalid. Currently BE returns valid 200 response with empty notes for an invalid reportId. Because of this problem, we will end up showing empty list in the UI instead of NotFoundView for invalid report. For invalid, `report.reportId` is also never set and thus out useEffect hook will also not get called once the report data fetch fails.

#### Solution exploration 2
Follow below pattern
```
Set default value of `isLoadingReportData` to true -> report data is fetched -> `report.reportID` change -> useEffect hook -> fetch notes data -> `isLoadingReportData` to false
```

This allows showing `loading` icon instead of `NotFoundView` right from the start. The problem with this approach is that if reportId is invalid then `report.reportId` is never changed and thus we never set `isLoadingReportData` to false and thus loading icon will appear infinitely.

**Comment by ArekChr** [comment] 2023-09-22 10:15
@salonikumawat28 In your solution when opening the "My Notes" deep link there is "NotFoundView" shown

**Comment by ArekChr** [comment] 2023-09-22 10:20
@dukenv0307 We always trying to follow the pattern to avoid early returns with `FullScreenLoadingIndicator`. Could you update your proposal and include this component inside children?
Also, your proposal doesn't resolve the problem at all, as the not found page is shown briefly.

**Comment by salonikumawat28** [comment] 2023-09-22 15:27
@ArekChr Updated [Proposal](https://github.com/Expensify/App/issues/27704#issuecomment-1725449322)

The issue in `PrivateNotesEditPage` and `PrivateNotesViewPage` is little different from `PrivateNotesListPage`. In case of `PrivateNotesListPage`, we were making API call to get private note data but we are not doing that in others. As OpenReport doesn't fetch private notes, deep link fails for them as there is no API call to fetch private notes.

I have updated the proposal including fix for `PrivateNotesEditPage` and `PrivateNotesViewPage` as well but I feel these two should be taken in a separate issue as the root cause for both of them are different. Please check my proposal for details.

**Comment by abekkala** [comment] 2023-09-25 06:17
@ArekChr have you reviewed the proposals and/or have comments on them?

**Comment by abekkala** [comment] 2023-10-02 16:30
@ArekChr can you please address this? 

Have you reviewed the proposals?

**Comment by abekkala** [comment] 2023-10-03 20:41
@ArekChr can you let me know if you're able to review the proposals above?

**Comment by ArekChr** [comment] 2023-10-04 12:33
> const [privateNote, setPrivateNote] = useState(lodashGet(report, ['privateNotes', route.params.accountID, 'note'], ''));

@salonikumawat28, I believe we may not require an additional state for storing private notes; it might be possible to calculate this on every render.

**Comment by salonikumawat28** [comment] 2023-10-04 15:24
# Proposal
Updated [proposal](https://github.com/Expensify/App/issues/27704#issuecomment-1725449322)

@ArekChr You are right. We don't need the additional state for private note. Corrected proposal. Tested the fix again after correctionl

**Comment by ArekChr** [comment] 2023-10-05 14:53
@dukenv0307 I couldn't test your solution as didn't find an HOC called `withReportIDOrNotFound`, it seems we never had this HOC

**Comment by salonikumawat28** [comment] 2023-10-09 06:57
@ArekChr What do you think of my updated proposal?

**Comment by abekkala** [comment] 2023-10-09 14:09
@ArekChr what do you think of the proposal? Is it sufficient? Do I need to pull someone else in to get this moved forward?

**Comment by ArekChr** [comment] 2023-10-10 11:59
@abekkala Both proposals look good to me, however, I'm inclined to choose the one from @dukenv0307. He has worked on private notes previously and was the first to pinpoint the problem.

**Comment by salonikumawat28** [comment] 2023-10-10 12:53
@ArekChr Few points in favour of my solution:
1. I checked @dukenv0307 solution and it doesn't work in all cases. I added the comment regarding this earlier here: https://github.com/Expensify/App/issues/27704#issuecomment-1725478724

The correct change should be what I proposed:
```
shouldShow={report.isLoadingPrivateNotes === false && network.isOffline && _.isEmpty(lodashGet(report, 'privateNotes', {}))}
```

2. The issue in `PrivateNotesViewPage` is different than in `PrivateNotesListPage` as you can see in my proposal which was not suggested by @dukenv0307

**Comment by abekkala** [comment] 2023-10-10 14:30
@ArekChr can you address the comment above and once you choose a proposal please take the correct steps/formatting in your comment when making your selection? 

You need to note the proposal along with the emoji's - this ensures that an engineer is assigned and can review your pick for the chosen proposal.

<img width="588" alt="Screenshot 2023-10-10 at 9 28 53 AM" src="https://github.com/Expensify/App/assets/11966460/a8c3d978-0aa3-4734-9026-841f97283d85">

**Comment by ArekChr** [comment] 2023-10-11 09:23
After testing both proposals and giving a deeper look, the [solution](https://github.com/Expensify/App/issues/27704#issuecomment-1725449322) from @salonikumawat28 does cover more edge cases effectively, which is a definite plus. I agree we should make another API call in `PrivateNotesListPage` as if it's opened via a deep link, private notes are not fetched from the backend. I'm choosing to go with your proposal.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by MonilBhavsar** [comment] 2023-10-11 13:01
Proposal looks good to me. Just concerned about getting privateNotes from two different API calls which seems like violation of 1:1:1 Action:API:Command rule. @techievivek since you worked on this, could you please tell if it is expected that notes are loaded in OpenReport API call and if we can prevent API call - `GetReportPrivateNote`. 

> PrivateNotesViewPage page never makes API Read call to get private notes: GetReportPrivateNote. So, even if we have report data from OpenReport API read call, we don't have private notes in it. So in addition to withReportOrNotFound, we need to make API call to fetch private notes if not present in existing report.

**Comment by techievivek** [comment] 2023-10-11 13:44
>Proposal looks good to me. Just concerned about getting privateNotes from two different API calls which seems like violation of 1:1:1 Action:API:Command rule

If I understand the proposal correctly, it seems that @salonikumawat28 will only be using the `GetReportPrivateNote` command. The important thing to note is that this command will now also be called from the view page. So, I believe we're good here. @salonikumawat28, could you kindly double-check that for us? Thank you.

**Comment by MonilBhavsar** [comment] 2023-10-11 13:56
Thank you! that sounds good to me 👍 
Also, we have a useEffect with reportID dependency. May be we can use it

**Comment by MonilBhavsar** [comment] 2023-10-12 09:04
Thanks for clarifying! I agree with the proposal and using HOC sounds better to avoid code deduplication. @techievivek did we think of this while planning, or any reason we should not do it?

**Comment by techievivek** [comment] 2023-10-13 12:57
@MonilBhavsar 
> did we think of this while planning, or any reason we should not do it?

We didn't talk in detail about the optimizations for these related pages, but it looks like we can do it now, so let's go for it. 🚀

**Comment by MonilBhavsar** [comment] 2023-10-13 13:05
> I think the addition case the is added in @salonikumawat28 is out of scope of this issue. I think it should be handled as a separate bug.

@dukenv0307 It ensures the same issue doesn't happen on multiple similar pages and I think it's not considered out of the scope of the issue.

> We didn't talk in detail about the optimizations for these related pages, but it looks like we can do it now, so let's go for it. 🚀

Thanks! Sounds good to me 👍

**Comment by salonikumawat28** [comment] 2023-10-13 13:55
> 📣 @salonikumawat28 You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~010e6deeec4e90fc66) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

Applied for job in upwork. PR will be ready for review within 1 day.

**Comment by salonikumawat28** [comment] 2023-10-15 03:01
@ArekChr @MonilBhavsar I have raised the PR: #29636
As discussed, I have created HOC `withReportAndPrivateNotesOrNotFound` for this.

**Comment by salonikumawat28** [comment] 2023-10-15 03:15
@ArekChr @MonilBhavsar 
I request reevaluation of compensation of this issue. Here are the points in favour of this reevaluation:
1. We fixing the raised issue for `PrivateNotesListPage`.
2. In addition, we have extended the fix for similar pages like `PrivateNotesViewPage` and `PrivateNotesEditPage` as well.
2. The fix in `PrivateNotesViewPage` was not similar to fix of raised `PrivateNotesListPage` issue as in `PrivateNotesViewPage`, we had to call `GetReportPrivateNote` in addition.
3. To optimize private notes and reduce code duplicity, we created HOC `withReportAndPrivateNotesOrNotFound`. Not only useEffect code duplicity, we were able to remove `page not found view` and `loading indicator view` logic from individual components as well because of the HOC.
4. `Not found view` was not consistent across list, view, edit pages of private notes. We have made it consistent.
5. Additionally, in testing we found the offline mode behaviour to not be consistent for list, view and edit pages. We have now made the consistent behaviour for offline mode for list, view and edit pages.

What are your thoughts on this reevaluation request?

**Comment by salonikumawat28** [comment] 2023-10-20 13:48
@ArekChr Do you know who can help with the reevaluation request as asked above?

**Comment by abekkala** [comment] 2023-10-31 15:52
@ArekChr @MonilBhavsar do you have any comments on the message from @salonikumawat28

**Comment by ArekChr** [comment] 2023-11-06 10:28
@MonilBhavsar, @abekkala, I agree with the reevaluation. The extra work done on `PrivateNotesViewPage` and `PrivateNotesEditPage` was not part of the original plan and has helped a lot. The new HOC is also a good improvement. I've checked everything, and it looks good.

**Comment by MonilBhavsar** [comment] 2023-11-06 19:57
PR was merged! 🚀 
Agree with ArekChr's message above and for reevaluation 👍

**Comment by salonikumawat28** [comment] 2023-11-06 20:21
> @ArekChr @MonilBhavsar I request reevaluation of compensation of this issue. Here are the points in favour of this reevaluation:
> 
> 1. As expected, we are fixing the raised issue for `PrivateNotesListPage`.
> 2. In addition, we have extended the fix for similar pages like `PrivateNotesViewPage` and `PrivateNotesEditPage` as well.
> 3. The fix in `PrivateNotesViewPage` was not similar to fix of raised `PrivateNotesListPage` issue as in `PrivateNotesViewPage`, we had to call `GetReportPrivateNote` in addition.
> 4. To optimize private notes and reduce code duplicity, we created HOC `withReportAndPrivateNotesOrNotFound`. Not only useEffect code duplicity, we were able to remove `page not found view` and `loading indicator view` logic from individual components as well because of the HOC.
> 5. `Not found view` was not consistent across list, view, edit pages of private notes. We have made it consistent.
> 6. Additionally, in testing we found the offline mode behaviour to not be consistent for list, view and edit pages. We have now made the consistent behaviour for offline mode for list, view and edit pages.
> 
> What are your thoughts on this reevaluation request?

> @ArekChr @MonilBhavsar I request reevaluation of compensation of this issue. Here are the points in favour of this reevaluation:
> 
> 1. As expected, we are fixing the raised issue for `PrivateNotesListPage`.
> 2. In addition, we have extended the fix for similar pages like `PrivateNotesViewPage` and `PrivateNotesEditPage` as well.
> 3. The fix in `PrivateNotesViewPage` was not similar to fix of raised `PrivateNotesListPage` issue as in `PrivateNotesViewPage`, we had to call `GetReportPrivateNote` in addition.
> 4. To optimize private notes and reduce code duplicity, we created HOC `withReportAndPrivateNotesOrNotFound`. Not only useEffect code duplicity, we were able to remove `page not found view` and `loading indicator view` logic from individual components as well because of the HOC.
> 5. `Not found view` was not consistent across list, view, edit pages of private notes. We have made it consistent.
> 6. Additionally, in testing we found the offline mode behaviour to not be consistent for list, view and edit pages. We have now made the consistent behaviour for offline mode for list, view and edit pages.
> 
> What are your thoughts on this reevaluation request?


@MonilBhavsar Thanks for merging the PR and agreeing with the reevaluation request. @abekkala Will be you reevaluating the amount?

@MonilBhavsar Because of above reasons and multiple merge conflicts, our timeline for PR was exceeded and as per rules, the contract is in danger of termination. In addition, even though the issue was assigned to me, I didn't receive the upwork offer for it till now. Given these reasons, is it possible to get a exception and still receive the contact amount?

**Comment by salonikumawat28** [comment] 2023-11-07 20:19
Above deploy blocker is now removed and no longer a deploy blocker. In addition, the issue is unrelated to this pull request's changes.

**Comment by salonikumawat28** [comment] 2023-11-07 20:19
> @MonilBhavsar Because of above reasons and multiple merge conflicts, our timeline for PR was exceeded and as per rules, the contract is in danger of termination. In addition, even though the issue was assigned to me, I didn't receive the upwork offer for it till now. Given these reasons, is it possible to get a exception and still receive the contact amount?

@MonilBhavsar Any thoughts on this?

**Comment by MonilBhavsar** [comment] 2023-11-08 05:54
I support this reasoning. PR was actively being worked on, we did increase the scope and revewing and addressing comments back and forth took some time. cc @abekkala

**Comment by salonikumawat28** [comment] 2023-11-11 07:04
@abekkala Since PR is deployed to prod, can you help in looking at reevaluation request and relaxing timeline request (which is approved by Monil and Arkadiusz in above comments)?

**Comment by salonikumawat28** [comment] 2023-11-17 05:41
@abekkala Can you help with the above comment?

**Comment by salonikumawat28** [comment] 2023-11-19 13:18
@ArekChr @MonilBhavsar Is there anyone else who can help here as there's no response from @abekkala ?

**Comment by abekkala** [comment] 2023-11-22 15:41
Yes, this was discussed with @MonilBhavsar 

I don't see that the issue was auto-updated by melvin with payment date


When I review the GH it looks like payouts will be to: 
- salonikumawat28 $500 - contributor who fixed
- ArekChr - $500 PR Review
- dukenv0307 $50 - Bug Reporter

**Comment by salonikumawat28** [comment] 2023-11-22 19:18
@abekkala As @MonilBhavsar and @ArekChr also agreed that given the additional efforts, this issue should be reevaluated for the payment, can you help with that?

**Comment by salonikumawat28** [comment] 2023-11-22 19:21
> PR was merged! 🚀 Agree with ArekChr's message above and for reevaluation 👍

@abekkala Check here for @MonilBhavsar comment agreeing for reevaluation.

**Comment by abekkala** [comment] 2023-11-30 21:15
Yes, I'm discussing the payment with Monil.

**Comment by abekkala** [comment] 2023-12-01 17:51
@salonikumawat28 @ArekChr offer has been updated to $750.

Would you like me to send that in Upwork now?

**Comment by abekkala** [comment] 2023-12-04 21:33
lol - yeah, I noticed that after that he is part of CS

**Comment by abekkala** [comment] 2023-12-04 21:42
Issue reported by: @dukenv0307 [$50] paid and contract ended - thank you! 🎉 
Fix: @salonikumawat28  [$750] [offer](https://www.upwork.com/nx/wm/offer/27958140)
PR Review: @ArekChr [CS - no payment in Upwork]

**Comment by salonikumawat28** [comment] 2023-12-05 03:58
@abekkala thanks for the offer. Accepted offer and requested payment.

Can you help me by giving a review in upwork in addition to releasing payment? Review will help me in building my profile. Thanks for the help.

**Comment by abekkala** [comment] 2023-12-06 20:27
@salonikumawat28 yes, reviews are always done once we process payment and end contract. 🎉

**Closed** 2023-12-06 20:28 UTC
Labels: Reviewing, External, Weekly

**Comment by salonikumawat28** [comment] 2023-12-07 03:26
@abekkala Thanks for the review and payment 🎉
