### ISSUE TITLE
Pressing the delete button multiple times while deleting a workspace shows an error reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11436] opened 2022-09-29 18:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any workspace
2. Press the Delete Workspace option
3. Press the Delete button multiple times

## Expected Result:
Workspace deletes without any error

## Actual Result:
Workspace deletes and an error is displayed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.9-0

**Reproducible in staging?:** Needs reproduction

**Reproducible in production?:** Needs reproduction

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193112904-3623a2cc-30fc-4e30-af69-ab0396446f10.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1663352362885379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adeel0202** [comment] 2022-10-18 18:55
There is a change in the bug. Now pressing the delete button multiple times shows a red dot on avatar.
cc: @kavimuru 

https://user-images.githubusercontent.com/13783842/196519262-dafee962-bb8a-466d-86eb-8b413c6e824f.mp4

**Comment by tjferriss** [comment] 2022-10-20 21:44
I was not able to reproduce this bug on the mobile app (v1.2.15-3). I was able to successfully delete the workspace. Asked for a follow up in the Slack thread.

**Comment by adeel0202** [comment] 2022-10-21 17:01
I'm not able to reproduce this bug anymore.

**Comment by tjferriss** [comment] 2022-10-21 22:17
Closing as the bug appears to be fixed now.

**Closed by tjferriss** 2022-10-21 22:17 UTC
Labels: Daily, Needs Reproduction, Bug
