### ISSUE TITLE
[HOLD for payment 2023-09-12] [HOLD for payment 2023-09-11] [$1000]  IOU - Currency edit in confirmation page causes missing header and wrong redirection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26586] opened 2023-09-02 23:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26520
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Enter an amount > Select a payer
3. On confirmation page, click on the Amount
4. Edit the amount only > Click Next
5. On the confirmation page, click on the Amount again
6. Change the currency
7. Click Next

## Expected Result:
In Step 6, Amount header does not disappear
In Step 7, user is redirected to the confirmation page

## Actual Result:
In Step 6, Amount header disappears
In Step 7, user is redirected to the payer selection page. This is a different behavior observed in Step 4 when user is redirected to the confirmation page when the amount is changed

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money
3. Enter an amount
4. Change the currency

## Expected Result:
The amount is preserved and does not change

## Actual Result:
The amount is not preserved and it changes to zero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c6c4b202-6dba-4f2a-8a31-113c072902f2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010711a82a596d6dcc</li>
        <li>Upwork Job ID: 1698168980758937600</li>
        <li>Last Price Increase: 2023-09-03</li>
    </ul>
</details>

**Comment by napster125** [comment] 2023-09-03 01:53
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
https://github.com/Expensify/App/commit/470c54a37f80f4b9782b3d48b55394cd107d4d2a caused regression.
https://github.com/Expensify/App/blob/e088539f32561dca5e0490300bd9e5684cd54d04/src/pages/iou/IOUCurrencySelection.js#L87
In this code snippet, the goBack function with true as the second parameter replaces the modal without considering the previous state. This leads to unexpected behavior, such as the issue we've encountered and the resetting of text input.
### What changes do you think we should make in order to solve the problem?
We should use `Navigation.navigate` function instead of `goBack` function.
```
Navigation.navigate(`${props.route.params.backTo}?currency=${option.currencyCode}`);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by shubham1206agra** [comment] 2023-09-03 01:56
@marcaaron If you have no problem, we should combine this with https://github.com/Expensify/App/issues/26587

**Comment by hayata-suenaga** [comment] 2023-09-03 02:59
This was probably caused by Wave 5 PRs. We need to solve this my Monday and it's weekend.

I gonna make this external to get immediate proposals and PRs

**Comment by hayata-suenaga** [comment] 2023-09-03 03:04
Combined with https://github.com/Expensify/App/issues/26587

**Comment by napster125** [comment] 2023-09-03 03:07
@hayata-suenaga could you please take a look [here](https://github.com/Expensify/App/issues/26586#issuecomment-1703984887)? I can make PR ASAP.

**Comment by hayata-suenaga** [comment] 2023-09-03 03:16
@napster125 could you kindly post a video showing navigation still works after your changes and then we can proceed with your PR

**Comment by napster125** [comment] 2023-09-03 03:17
of course!
https://github.com/Expensify/App/assets/136437976/7ccd8524-46a2-469b-a057-19d827325574

**Comment by hayata-suenaga** [comment] 2023-09-03 03:17
@napster125 

also do you think [this one](https://github.com/Expensify/App/issues/26588) is also somehow related to this issue?

**Comment by napster125** [comment] 2023-09-03 03:18
No, I have seen this issue but I think it's not triggering pressOnEnter. But I'm not sure why.

**Comment by napster125** [comment] 2023-09-03 03:20
@hayata-suenaga Also, I think it was happening before.

**Comment by hayata-suenaga** [comment] 2023-09-03 03:21
@napster125 perfect! thank you for the video

I remember that the particular commit you linked was aded to solve an issue with the following flow:

workspace chat -> request money -> distance request -> add Start and Finish -> Next -> edit the amount -> save -> correctly taken back to the previous screen

can you also test this flow little quick with your change and link the video 🙇 🙇 🙇

**Comment by shubham1206agra** [comment] 2023-09-03 03:28
@hayata-suenaga I am unable to edit the amount on the confirmation page. Is this intentional?

**Comment by napster125** [comment] 2023-09-03 03:29
@hayata-suenaga me too, I can't reproduce such flow.

**Comment by hayata-suenaga** [comment] 2023-09-03 04:39
> @hayata-suenaga I am unable to edit the amount on the confirmation page. Is this intentional?

checkout right now...

**Comment by hayata-suenaga** [comment] 2023-09-03 04:41
I'm looking forward to your PR @napster125 🚀

**Comment by napster125** [comment] 2023-09-03 08:49
@hayata-suenaga I have applied on Upwork. My Upwork profile url is https://www.upwork.com/freelancers/~01212c68bbcaede4db.

**Comment by mountiny** [comment] 2023-09-03 09:03
@napster125 Do you have the PR ready? I can make it right now and you could do a review and checlist? Are you available to do that in coming hours?

**Comment by mountiny** [comment] 2023-09-03 09:03
@napster125 Whats you Slack handle?

**Comment by napster125** [comment] 2023-09-03 09:04
I have just make a commit and am making the PR. And my slack name is Pluto.

**Comment by mountiny** [comment] 2023-09-03 09:07
Thanks, awaiting your PR, please post it in the Slack thread once raised https://expensify.slack.com/archives/C01GTK53T8Q/p1693731985567709?thread_ts=1693696719.158669&cid=C01GTK53T8Q

**Comment by mountiny** [comment] 2023-09-03 13:41
This is fixed in staging

**Comment by sophiepintoraetz** [comment] 2023-09-04 06:20
Providing there's no regressions, I'm correct in saying that $1500 is due to @napster125?

**Comment by mountiny** [comment] 2023-09-04 09:13
@sophiepintoraetz thats right and that should be the only payment here, thanks!

**Comment by sophiepintoraetz** [comment] 2023-09-04 23:40
Offer sent - I'll release payment on 11 Sep

**Comment by sophiepintoraetz** [comment] 2023-09-22 03:42
Actually, I'm going to close this one out and create a new one with the appropriate issue, seeing as payment is the only thing left here.

**Closed by sophiepintoraetz** 2023-09-22 03:42 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment
