### ISSUE TITLE
[$500] IOU - In request money, all contacts below are displayed only after few seconds

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30137] opened 2023-10-21 21:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap request money---manual
3. Enter an amount
4. Tap next and observe contacts below

## Expected Result:
In request money, in contacts selection page, all contacts in contacts section below must be displayed immediately without delay

## Actual Result:
In request money, in contacts selection page, the contacts below are displayed only after few seconds. Below in contacts section, only 2 contacts are shown and only after few seconds all contacts are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/0923c4e2-9c30-49f5-86ff-5b58663ec860

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bc9faaeaf508c70</li>
        <li>Upwork Job ID: 1715849601111867392</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-10-23 22:09
I'm unable to reproduce this. Opening of contacts is quick for me on android native. 

https://github.com/Expensify/App/assets/54866469/53c590c1-ec03-4006-8e22-6e7b33893a59

**Comment by joekaufmanexpensify** [comment] 2023-10-23 22:10
Closing as this isn't consistently reproducible!

**Closed by joekaufmanexpensify** 2023-10-23 22:10 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by joekaufmanexpensify** [comment] 2023-10-31 15:19
Got it. I still don't think this warrants doing anything. There's no impact to the user experience here. We just aren't showing all of the contacts in the brief moment before the android keyboard opens. If you close the keyboard, you can still see all contacts.
