### ISSUE TITLE
BUG: "You appear to be offline" shows when I'm online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11677] opened 2022-10-07 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Closed computer yesterday.
2. Opened computer today, I'm online with fast and dependable internet.
3. Opened NewDot. I think I had quit it yesterday
4. "You appear to be offline" is showing, LHN not loading and chats are sending

## Expected Result:
Should show as online

## Actual Result:
Shows I'm offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.12-2
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** [appear offline .txt](https://github.com/Expensify/App/files/9736916/appear.offline.txt)
**Notes/Photos/Videos:** 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/43996225/194638278-683a92b6-c0ff-4cb7-a72b-6ff11a3d070c.png">

https://user-images.githubusercontent.com/43996225/194638279-b10e5e88-29f8-470f-bd1f-15d0289f1385.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665078854089259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-10-07 20:45
@MonilBhavsar , will you see if you're able to reproduce?  We might want to add `Needs Reproduction` label but, with this happening twice, I'd like to avoid it going into the 'needs repro' abyss and not getting addressed.

**Comment by MonilBhavsar** [comment] 2022-10-10 09:21
I'm not able to reproduce the issue.
May be the app went in inactive state and it is causing the issue.

Thanks for attaching the logs. From the logs, it looks like we tried checking for connection but `isInternetReachable` stayed false.

> Log.js:55 [info] [NetworkConnection] NetInfo state change - {"isInternetReachable":false,"isConnected":false,"type":"none","details":null}
> Log.js:55 [info] [NetworkConnection] listenForReconnect called - ""

**Comment by mallenexpensify** [comment] 2022-10-10 21:39
Added `Needs Reproduction` label and unassigned ya @MonilBhavsar .   Thanks for checking the logs, not sure what else can/should be done about this now

**Comment by MonilBhavsar** [comment] 2022-10-11 05:45
Seems like pretty edge case. We can track and see if someone else experiences this.
The video where offline status is false on the Login page _might_ be related to this [issue](https://github.com/Expensify/App/issues/10524). cc @grgia

**Comment by hannojg** [comment] 2022-10-17 14:52
Hey guys, currently experiencing this as well. Just wanted to let you know, can, later on, help track down what goes wrong. Its across all browser

**Comment by hannojg** [comment] 2022-10-17 14:55
<img width="1279" alt="Screenshot 2022-10-17 at 4 55 32 PM" src="https://user-images.githubusercontent.com/16821682/196210791-f2865d09-c78e-4598-96cd-649f2fa3f4b9.png">

I think its related to some CORS stuff

**Comment by tjferriss** [comment] 2022-10-20 21:30
I was not able to reproduce. Asked for clarification on next steps in the Slack thread.

**Comment by tjferriss** [comment] 2022-10-21 22:06
I looked for this issue this morning and was again unable to reproduce.

Action Performed:
Closed computer yesterday.
Opened computer today, I'm online with fast and dependable internet.
Opened NewDot on web

Results:
Everything appeared to be working as expected.

@hannojg @kavimuru can you both confirm the testing steps and see if you're still able to reproduce?

**Comment by tjferriss** [comment] 2022-10-25 20:40
Friendly bump here. If we're unable to reproduce this then I suggest we close it out.

**Comment by tjferriss** [comment] 2022-10-28 23:04
Ok I'm going to close this out. Please reopen if you can reproduce.

**Closed by tjferriss** 2022-10-28 23:04 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
