### ISSUE TITLE
[$500] Chat - The chat shakes when you swipe down

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31586] opened 2023-11-20 21:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Open a conversation with a lot of one word messages and some emojis in a chat
4. Swipe up and down

## Expected Result:
The swiping should be smooth

## Actual Result:
The chat shakes when you swipe down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/78819774/1cccc603-e68f-40f0-8032-1f6fdade31b1

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a404d0c8e8de3687</li>
        <li>Upwork Job ID: 1726717224301903872</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-11-21 00:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - The chat shakes when you swipe down

### What is the root cause of that problem?
During scrolling  every time when the scroll indicator is approaching to the bottom there called  `Report.getNewerActions ` i which changes `isLoadingNewerReportActions`  prop . And in `ReportActionsList` component adds or removes ` paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT`  to the container  [in this part of code] (https://github.com/Expensify/App/blob/db37e46f58aceea23c0136e1bdce6e3ed9d2d90f/src/pages/home/report/ReportActionsList.js#L399C1-L402C7) so that the content moves up and the loader becomes visible .  Is the main cause of shaking of the content

### What changes do you think we should make in order to solve the problem?
I suggest to remove this part of code and always set  `paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT` 

### What alternative solutions did you explore? (Optional)
Alternatively we can  fix  [throttle](https://github.com/Expensify/App/blob/db37e46f58aceea23c0136e1bdce6e3ed9d2d90f/src/pages/home/report/ReportActionsView.js#L201C1-L223C21) function in `ReportActionsView` component  because at now it is not works as expected . It  is wrapped in `useMemo` which has deeps which changes after every cal of this function and the throttle function re-defines again .  And after that increase the throttle time to not re-render content so many time in some interval

**Comment by brunovjk** [comment] 2023-11-21 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem involves noticeable shaking in the chat view when engaging in specific actions, like opening multiline text in edit mode and scrolling up.

### What is the root cause of that problem?
The root cause is traced to real-time adjustments in the container style within the `ReportActionsList` component. These adjustments correlate with changes in the `isLoadingNewerReportActions` prop, specifically the addition or removal of `paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT`.

The shaking occurs during scrolling, particularly when the scroll indicator approaches the bottom, triggering the `Report.getNewerActions` function.

The same root cause
https://github.com/Expensify/App/issues/31609

### What changes do you think we should make in order to solve the problem?
In my perspective, this may not be a bug but rather a design decision. Three potential options for handling the loading circle's appearance are:

1- Current Behavior: Allow the content to move up and down as it does currently.
2 - Fixed Space for Loading Circle: Create a designated space for the loading circle, ensuring it appears and disappears without affecting existing content.
3 - Scroll Height Increase: Maintain the content in its current position while extending the overall height of the message scroll. Place the loading circle at the bottom, visible when users scroll to the very end.

### What alternative solutions did you explore? (Optional)
As an alternative, we could replace the loading circle with a Linear Progress Indicator, taking the place of the existing padding. This avoids height adjustments and provides a continuous indication of the loading process.

**Comment by sophiepintoraetz** [comment] 2023-11-28 03:56
@sobitneupane - can you take a look at the proposals, please?

**Comment by sobitneupane** [comment] 2023-11-29 07:20
Thanks for the proposal @shahinyan11 

> I suggest removing this part of the code and setting the paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT always

I don't think we can do that. If we always set  `paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT`, won't we have unwanted padding when Activity Indicator is hidden?

I don't think even increasing throttle solves the issue completely.

**Comment by sobitneupane** [comment] 2023-11-29 07:24
Thanks for the proposal @brunovjk 

@brunovjk Can you please add more details on 3rd method in your proposal.

Regarding "Create a designated space for the loading circle, ensuring it appears and disappears without affecting existing content.", It might create unwanted padding when Activity Indicator is hidden resulting bad user experience as discussed [here](https://github.com/Expensify/App/issues/31586#issuecomment-1831344806).

**Comment by shahinyan11** [comment] 2023-11-29 08:09
> I don't think we can do that. If we always set `paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT`, won't we have unwanted padding when Activity Indicator is hidden?

What I mean is that the display loader should not change the height of the content. I thought that the padding was small and would not look ugly.
I can an offer to move loader to top or make it absolute or something else. But if you don't like it. I think that firstly a design solution is needed and after that development. Because there is no way to do it without changing the design.


> I don't think even increasing throttle solves the issue completely.

Еhis will not solve the problem completely. this just helps so that it doesn’t happen again several times within a second

**Comment by shahinyan11** [comment] 2023-11-29 10:05
## Proposal
[Updated](https://github.com/Expensify/App/issues/31586#issuecomment-1820003195)

I changed old two ways as alternative and added one new solution

**Comment by shahinyan11** [comment] 2023-11-29 10:08
I changed old two ways as alternative and added one new solution

**Comment by sophiepintoraetz** [comment] 2023-12-04 04:09
Waiting for feedback from @sobitneupane

**Comment by brunovjk** [comment] 2023-12-04 11:51
Sorry for the delay @sobitneupane, I understand, I had the same concerns about solution 2, great that you confirmed it.

I'm going to do some tests now on solution 3 and get back to you with details as soon as possible.

Thanks.

**Comment by brunovjk** [comment] 2023-12-05 00:20
Finishing testing my proposal Melvin, I will post it soon

**Comment by shahinyan11** [comment] 2023-12-05 07:29
@sobitneupane Could you please take a look at my updated proposal and give some feedback

**Comment by sobitneupane** [comment] 2023-12-05 08:06
Thanks for the update @shahinyan11. I was waiting for @brunovjk's update. I will review your proposal asap. Thank you for the patience.

**Comment by brunovjk** [comment] 2023-12-05 19:52
> @brunovjk Can you please add more details on 3rd method in your proposal.

 @sobitneupane after testing the "Scroll Height Increase" option, it was observed that the issue persisted, and the chat shaking was merely transferred to the scrollbar, making the user experience less favorable. Upon further investigation, the problem was traced to the `onStartReachedThreshold` value in the `ReportActionsList` component.

**Comment by brunovjk** [comment] 2023-12-07 17:44
I tried to reproduce now, and it seems that not even the `circle loading` is appearing.

**Comment by shahinyan11** [comment] 2023-12-08 07:03
> Will review the proposal by EOD.

@sobitneupane  when to expect updates from you

**Comment by sobitneupane** [comment] 2023-12-08 07:51
@shahinyan11 I was reviewing the proposals. But looks like the issue is no longer reproducible.

**Comment by shahinyan11** [comment] 2023-12-08 08:04
@sobitneupane  and what steps did you take ? Or should we do something ?

**Comment by shahinyan11** [comment] 2023-12-08 08:21
@sobitneupane The behavior changed due to adding following code `|| hasNewestReportAction`  in condition in [this](https://github.com/Expensify/App/blob/0a8ad473e71c18adb3d299f0562057177de09e2a/src/pages/home/report/ReportActionsView.js#L204C1-L204C120) condition .

**Comment by sobitneupane** [comment] 2023-12-08 08:27
The change was introduced by [this PR](https://github.com/Expensify/App/pull/32124). And the issue is no longer reproducible. I don't think any action is required in the issue.

**Comment by sobitneupane** [comment] 2023-12-08 08:58
@shahinyan11 I think we should close the issue for now. We can always reopen the issue if the problem resurfaces.

cc: @sophiepintoraetz

**Comment by brunovjk** [comment] 2023-12-08 10:11
@sobitneupane, I don't know if we should close it, as the issue is no longer reproduced with the initial steps, but the way it is getting worse, now the loadng does not appear at all. Maybe create another issue?

**Comment by sophiepintoraetz** [comment] 2023-12-12 01:39
Ah, I missed [this comment](https://github.com/Expensify/App/issues/31586#issuecomment-1846795411) from being OOO, agreed.

**Closed by sophiepintoraetz** 2023-12-12 01:39 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
