### ISSUE TITLE
[HOLD for payment 2024-09-04][Search v2.1][Web-E] Deprecate old Search params

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45029] opened 2024-07-08 23:10 UTC
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.evfozsjoejn) of the design doc.

Holding on:
- [x] https://github.com/Expensify/App/pull/46481

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by luacmartins** [comment] 2024-07-23 23:56
Still on hold

**Comment by luacmartins** [comment] 2024-07-30 20:10
Not yet, the holding PR is still in draft

**Comment by slafortune** [comment] 2024-08-13 20:04
Just in case - adding another BZ - I'll be out until 8/21 and will check in on this then.

**Comment by Christinadobrzyn** [comment] 2024-08-20 21:25
looks like the [PR](https://github.com/Expensify/App/pull/46481) is in production - should we pay out the C+ for the review? @luacmartins

**Comment by luacmartins** [comment] 2024-08-20 21:29
That PR is not related to this issue. I still haven't worked on this one.

**Comment by luacmartins** [comment] 2024-08-20 21:29
Since this is all internal, I'll unassign you from this issue.

**Comment by brunovjk** [comment] 2024-09-03 11:52
@luacmartins I reviewed the [PR](https://github.com/Expensify/App/pull/47759), which has now been in [production for a week](https://github.com/Expensify/App/pull/47759#issuecomment-2311253531). However, I wasn't assigned to the issue or involved in the proposal review. Should I be assigned to this issue for compensation, or given the simple nature of the PR, can we close the issue and move on? Thank you.

**Comment by luacmartins** [comment] 2024-09-03 20:00
@brunovjk I updated the issue to make sure we process payment for the [PR review](https://github.com/Expensify/App/pull/47759). Thanks for raising this!

**Comment by brunovjk** [comment] 2024-09-03 20:09
Thank you @luacmartins 🙏

**Comment by brunovjk** [comment] 2024-09-03 20:46
Thank you @luacmartins 🙏

**Comment by strepanier03** [comment] 2024-09-03 22:50
Sent an [offer](https://www.upwork.com/nx/wm/offer/103804703) to @brunovjk - I'll check tomorrow to issue payment.

**Comment by strepanier03** [comment] 2024-09-03 22:51
### Payment summary

- [ ] $250 - @brunovjk via Upwork ([offer](https://www.upwork.com/nx/wm/offer/103804703))

**Comment by brunovjk** [comment] 2024-09-04 10:40
**Regression Test Proposal**

- Open the search page.
- Select "Transactions."
- Open your browser console.
- Click on "Download."
- Verify that the API request to `ExportSearchToCSV` includes `jsonQuery` in the payload.

Do we agree? 👍 or 👎

**Comment by luacmartins** [comment] 2024-09-04 16:58
No need to add the steps above, we're covering them as part of the project wrap up.

**Comment by strepanier03** [comment] 2024-09-04 17:17
Thanks @luacmartins, was just going to close the GH and saw you took care of that too, appreciate it!

**Comment by strepanier03** [comment] 2024-09-04 17:19
All right, I've paid and closed the contract and this is ready to be closed as well. Thanks everyone!

**Closed by strepanier03** 2024-09-04 17:19 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment
