### ISSUE TITLE
Reimburse expenses - Error continues to appear when changing the rate after it was modified

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12451] opened 2022-11-03 21:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12162 

## Action Performed:
1. Navigate to any existing workspace on device A > Reimburse expenses. Go offline.
2. Switch to device B. Sign into the same account, and navigate to the same workspace > Reimburse expenses.
3. Edit the Rate input
4. Observe it shows in the pending state
5. Switch back to device A. Make sure you're still offline. Edit the same rate field.
6. Go back online on device A
7. Observe the unit field fails to update because the workspace was modified while you were offline, displaying the RBR and error message
8. Attempt to update the rate field again while online.

## Expected Result:
You are able to modify the field and no errors show.

## Actual Result:
Error continues to appear when changing the rate after it was modified offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Desktop App
- Mobile Web

**Version Number:** 1.2.23.7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199835238-84dfcab6-2090-4b5f-8d53-44f2d11e99be.mp4

https://user-images.githubusercontent.com/93399543/199844891-327d1fb6-81c2-4940-b1d4-a8ec9d296a2e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2022-11-03 23:41
This was my PR so I can investigate. Seems something changed between when I tested it locally and when it was deployed.

**Comment by jasperhuangg** [comment] 2022-11-03 23:56
Hmm, looking at the issue it's probably best to wait for https://github.com/Expensify/App/pull/12219 to be merged + deployed first so we can be more sure of what the issue is. I think the offline client may seem to have the wrong value after coming back online because the order of writes and reads is incorrect.

This happened for me locally, but after pulling the changes from https://github.com/Expensify/App/pull/12219 that seemed to fix things since it ensures read requests run last.

I did notice a separate issue while having those changes checked out, but I think I know how to rectify it and can open a separate web PR.

**Comment by trjExpensify** [comment] 2022-11-04 00:35
Sheesh, fun one! Okay cool, so we should mark this as `internal` right?

**Comment by jasperhuangg** [comment] 2022-11-04 17:30
sure, I can QA both PRs since I have the most context about what to look out for

**Comment by trjExpensify** [comment] 2022-11-08 14:39
#12219 has merged, so #35433 should come off hold imminently.

**Comment by mvtglobally** [comment] 2022-11-09 03:45
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-11-09 11:01
https://github.com/Expensify/App/pull/12219 is on staging. #35433 is reviewed, and should come off hold imminently after the prod deploy.

**Comment by jasperhuangg** [comment] 2022-11-15 16:41
https://github.com/Expensify/Web-Expensify/pull/35433 was just deployed to prod an hour ago. Testing this out again

**Comment by jasperhuangg** [comment] 2022-11-15 19:24
Hmm it seems like now I can't even get the error to appear, strangely the API just accepts the new updates from the client that was offline. Perhaps something has changed since https://github.com/Expensify/Web-Expensify/pull/35433 was being deployed, I'll investigate.

https://user-images.githubusercontent.com/31285285/202007556-a0e1739a-b025-4424-85c4-7e67cb764718.mov

**Comment by mvtglobally** [comment] 2022-11-16 02:23
Issue not reproducible during KI retests. (Second week)

**Comment by jasperhuangg** [comment] 2022-11-17 20:16
Seems like a PR definitely went out that broke the error displaying, it was working for me on dev, but then I pulled `main` on App and it broke.

**Comment by kbecciv** [comment] 2022-11-24 23:47
Issue is reproduced today with build 1.2.31.7

https://user-images.githubusercontent.com/93399543/203875418-df7a6532-000a-4647-9872-9335078dbcc8.mp4

**Comment by jasperhuangg** [comment] 2022-11-28 16:34
Taking a look into this one today!

**Comment by jasperhuangg** [comment] 2022-11-28 17:32
@kbecciv it seems to actually be working as expected when I tested it on `v1.2.32-1` 

https://user-images.githubusercontent.com/31285285/204342904-64537b21-1da0-4385-8b3e-9f99706de728.mov

The final values on both clients are correct. Don't mind the replay effect, that's tackled in https://github.com/Expensify/App/issues/12775. Subsequent updates to the values also work.

For these types of issues that require two clients to be used, can you please provide both clients in the screen recording? It's not clear to me what the values were set to on the other client, and therefore it's hard to verify whether the behavior of the offline client is correct. Thanks!

**Closed** 2022-11-28 17:34 UTC
Labels: Engineering, Daily, Internal, Bug
