### ISSUE TITLE
[$1000] iOS/Android App: The 'here' link to open the Display name page does not take you anywhere.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21932] opened 2023-06-30 03:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Scan the QR code of any PUBLIC room with your camera
2. After being taken to the public room, You will receive a message from the Concierge: ‘Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name. If you'd like to add a different display name, open the Display Name page 'here'.
3. Now try clicking the 'here' link. Notice that it does not take you anywhere
## Expected Result:
The 'here' link takes you to the Display Name page
## Actual Result:
The 'here' link does not take you to the Display Name page.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/567f83e9-d11b-475d-a469-c565bcfa6451

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687813299792699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f73163a7e21d167</li>
        <li>Upwork Job ID: 1675889843813896192</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-30 10:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS: The 'here' link to open the Display name page does not take you anywhere

### What is the root cause of that problem?
This is happening because this link is treated as an external link since it url is `/settings/profile/display-name` and our current logic is not recognising this as internal link.

<img width="441" alt="Screenshot 2023-06-30 at 3 09 49 PM" src="https://github.com/Expensify/App/assets/59907218/23bc836c-d695-4efa-9eec-21f43f0be360">

### What changes do you think we should make in order to solve the problem?

We can add logic to handle links starting with `/` as internal 

https://github.com/Expensify/App/blob/b8aeec0bcf2cac06d51129f287f932ba0421ed4e/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L29-L33

### What alternative solutions did you explore? (Optional)
 Backend should send this link as `https://new.expensify.com/settings/profile/display-name` with expensify base url

**Comment by lschurr** [comment] 2023-06-30 18:56
Bumped the Slack thread since I can't reproduce this.

**Comment by daveSeife** [comment] 2023-06-30 23:54
HI @lschurr, I think you are not getting a message from the Concierge because you already have a Display name. Can you please try scanning having an account with no display name?

**Comment by lschurr** [comment] 2023-07-05 17:49
Hi @MonilBhavsar - are you able to take a look at this and confirm whether this should be Internal?

**Comment by lschurr** [comment] 2023-07-07 20:22
Bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-07-10 09:23
Sorry, looking today

**Comment by MonilBhavsar** [comment] 2023-07-10 10:29
Sorry, I am not able to reproduce the issue


https://github.com/Expensify/App/assets/32012005/73ae50d8-cd7c-48b5-9c8d-99bc08e89ff2

**Comment by daveSeife** [comment] 2023-07-10 11:29
Hi @MonilBhavsar this is an iOS issue. It works fine in web.

**Comment by alitoshmatov** [comment] 2023-07-10 12:12
@MonilBhavsar I think even on the web it should not open new tab

**Comment by MonilBhavsar** [comment] 2023-07-14 11:02
> this is an iOS issue. It works fine in web.

Thanks! i'll verify now

> I think even on the web it should not open new tab

Agree. We're sending relative path from server and hence it opens in new tab, I think 🤔

**Comment by alitoshmatov** [comment] 2023-07-14 11:11
> Agree. We're sending relative path from server and hence it opens in new tab, I think 🤔

You are right, the path is `/settings/profile/display-name` right now, [solution](https://github.com/Expensify/App/issues/21932#issuecomment-1614445981) is either add base url in backend, or add a logic to treat relative paths as internal

**Comment by MonilBhavsar** [comment] 2023-07-14 11:15
> Thanks! i'll verify now

Yeah, I am able to reproduce mentioned issue on iOS

> You are right, the path is /settings/profile/display-name right now, https://github.com/Expensify/App/issues/21932#issuecomment-1614445981 is either add base url in backend, or add a logic to treat relative paths as internal

Thanks! that makes sense. The URL is returned from very lower level, so I guess it's not possible to differentiate there between staging/prod/dev and add base URL accordingly. I'll discuss internally and update here

**Comment by MonilBhavsar** [comment] 2023-07-14 11:32
Have asked here internally for thoughts https://expensify.slack.com/archives/C03TQ48KC/p1689334356137519

**Comment by MonilBhavsar** [comment] 2023-07-17 08:47
Gonna get some thoughts from more people before proceeding to fix.

**Comment by lschurr** [comment] 2023-07-24 15:10
Added Internal.

**Comment by lschurr** [comment] 2023-07-27 20:20
Bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-07-28 13:09
I discussed this fix with Flo over the call. I have got the plan ready and will be working on the fix. Meanwhile, it will be good to know that why the redirection in iOS is not happening. @alitoshmatov any idea on this?
If we can fix it on client side, we would want to prefer that way

**Comment by MonilBhavsar** [comment] 2023-07-31 11:58
> I think iOS is not able to determine the URL scheme thus it does not handle that URL

Yes, this. Just wanted to know more of a root cause that why this issue is specifically happening for iOS

**Comment by alitoshmatov** [comment] 2023-08-02 06:46
@MonilBhavsar Sorry for late response. As mentioned [here](https://github.com/Expensify/App/issues/21932#issuecomment-1655767493) this is happening because native apps do not recognise relative path as url since they don't have base url. This is not happening only in ios, in android also the same is happening:

https://github.com/Expensify/App/assets/59907218/56259798-15b8-4da1-ae18-9cf90d6e132e

**Comment by lschurr** [comment] 2023-08-02 20:27
@parasharrajat @MonilBhavsar - should we assign @alitoshmatov to this?

**Comment by MonilBhavsar** [comment] 2023-08-07 10:50
WIP

**Comment by lschurr** [comment] 2023-08-09 20:26
Any updates @MonilBhavsar?

**Comment by lschurr** [comment] 2023-08-30 14:16
Hi @MonilBhavsar - what's the latest here? Are we still waiting on this PR? https://github.com/Expensify/Auth/pull/8497

**Comment by flaviadefaria** [comment] 2023-09-04 10:03
@MonilBhavsar do you have an update here?

**Comment by lschurr** [comment] 2023-09-06 17:52
Taking this back from you @flaviadefaria (thanks!) - any update on this one @MonilBhavsar?

**Comment by lschurr** [comment] 2023-09-18 07:44
Any update on this one @MonilBhavsar?

**Comment by MonilBhavsar** [comment] 2023-09-25 22:50
Sorry, this is slipping away. Have been focussed on customer's issue and waves. I'll circle back and fix this up

**Comment by MonilBhavsar** [comment] 2023-10-18 05:45
Sorry for delay, this is fixed now. Looks all internal. So we can close this

**Closed by MonilBhavsar** 2023-10-18 05:45 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by daveSeife** [comment] 2023-10-18 12:38
@MonilBhavsar @lschurr payment has not been made for the reporter
