### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Split - A new group is formed when splitting bill with a few members in the group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32855] opened 2023-12-11 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat with many members
3. Click + > Split bill
4. Unselect a few members and create the bill split
Note that a new group is formed

## Expected Result:
The bill split is created in the same group chat

## Actual Result:
A new group is formed in which the bill split is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ea4258f3-f34b-4533-a89b-95c0825e0e79

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecb31d068a616959</li>
        <li>Upwork Job ID: 1734322113712480256</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28050164</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-12-11 20:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new group is formed when splitting bil with a few members in a group 
### What is the root cause of that problem?

in the split we pass the `report` argument as the `tag` https://github.com/Expensify/App/blob/968f39f0a2c6e7305e46f7d5a8a546407689cc10/src/pages/iou/request/step/IOURequestStepConfirmation.js#L215-L225

```
        IOU.splitBill(
                    selectedParticipants,
                    currentUserPersonalDetails.login,
                    currentUserPersonalDetails.accountID,
                    transaction.amount,
                    trimmedComment,
                    transaction.currency,
                    transaction.category,
                    report.reportID,
                );
```


### What changes do you think we should make in order to solve the problem?

we should change it to 
```js
        IOU.splitBill(
                    selectedParticipants,
                    currentUserPersonalDetails.login,
                    currentUserPersonalDetails.accountID,
                    transaction.amount,
                    trimmedComment,
                    transaction.currency,
                    transaction.category,
                    transaction.tag,
                    report.reportID,
                );
```

**Comment by situchan** [comment] 2023-12-11 20:43
@abzokhattab's proposal looks good to me. We recently added merchant so this should be correct fix:
```
        IOU.splitBill(
                    selectedParticipants,
                    currentUserPersonalDetails.login,
                    currentUserPersonalDetails.accountID,
                    transaction.amount,
                    trimmedComment,
                    transaction.currency,
                    transaction.category,
                    transaction.tag,
                    report.reportID,
                    transaction.merchant,
                );
```

**Comment by tgolen** [comment] 2023-12-11 21:20
@situchan is correct, the merchant field needs added too. Thanks for grabbing this one!

**Comment by youssef-lr** [comment] 2023-12-11 21:32
@tgolen I was fixing this one here https://github.com/Expensify/App/pull/30721, I had to copy the update to the new file as I was changing the old one

**Comment by tgolen** [comment] 2023-12-11 21:34
OK, thanks. Since this is a deploy blocker, I think we'll need a PR just for this fix.

**Comment by youssef-lr** [comment] 2023-12-11 21:42
Sounds good!

**Comment by abzokhattab** [comment] 2023-12-12 04:13
The PR is ready

**Comment by Julesssss** [comment] 2023-12-12 12:02
Starting CP

**Comment by adelekennedy** [comment] 2023-12-12 17:50
Testing

**Comment by adelekennedy** [comment] 2023-12-12 17:53
Just tested - when I unselect members from the split no new group is formed. The split remains in the same group chat
<img width="1140" alt="Screenshot 2023-12-12 at 9 52 53 AM" src="https://github.com/Expensify/App/assets/60450566/547dc16d-ca2d-42b4-b056-49238830d00e">

**Comment by shubham1206agra** [comment] 2023-12-13 06:33
Please assign me here as reviewer

**Comment by sophiepintoraetz** [comment] 2023-12-20 02:04
@shubham1206agra - please can you accept the offer? I will pay once you have completed the BZ checklist.
@abzokhattab - offer is in your inbox

**Comment by abzokhattab** [comment] 2023-12-20 08:03
Thanks @sophiepintoraetz, I have accepted the offer

**Comment by shubham1206agra** [comment] 2023-12-20 14:46
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1432806472
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as we already caught this in deploy testing
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@sophiepintoraetz] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sophiepintoraetz** [comment] 2023-12-21 04:17
Both paid, thanks!

**Closed by sophiepintoraetz** 2023-12-21 04:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
