### ISSUE TITLE
Conversation - Reaction tooltip does not update when other user has removed the emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23746] opened 2023-07-27 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat as user A.
3. Add the same reaction to the message that has been reacted by User B.
4. Long press on the reacted emojj.
5. As User B, remove the reacted emoji.

## Expected Result:
The tooltip will update the reaction list.

## Actual Result:
The tooltip does not update the reaction list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-1
**Reproducible in staging?:** y
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5e2d6497-67f1-4a57-be5c-cf2e8cc0b8ca

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-27 16:11
Adding Deploy Blocker label, because  it shows undefined on emoji reaction tooltip

**Comment by Santhosh-Sellavel** [comment] 2023-07-27 16:27
Does not looks like a Deploy blocker to me. @puneetlath

**Comment by Santhosh-Sellavel** [comment] 2023-07-27 16:28
> Regression from: #23371

@hungvu193 Can you please explain how this is a regression from the linked PR?

**Comment by puneetlath** [comment] 2023-07-27 16:49
I don't think this needs to be a deploy blocker given that on production it shows `0:undefined`. So we're not regressing at least. So I'm going to remove the deploy blocker label.

**Comment by ayazhussain79** [comment] 2023-07-27 16:55
@puneetlath can you please check that i have already reported that bug and @StevenKKC mentioned it will be fixed in this [PR](https://github.com/Expensify/App/pull/23371) but it is still reproducible 
https://github.com/Expensify/App/pull/23371

**Comment by Nathan-Mulugeta** [comment] 2023-07-27 19:49
Hey @puneetlath , I think I originally have reported this issue [here](https://expensify.slack.com/archives/C049HHMV9SM/p1690396271150109?thread_ts=1690396271.150109&cid=C049HHMV9SM)

**Comment by ayazhussain79** [comment] 2023-07-27 20:09
I reported root case of this bug 7 days ago https://expensify.slack.com/archives/C049HHMV9SM/p1689857009202199?thread_ts=1689857009.202199&cid=C049HHMV9SM

**Comment by CortneyOfstad** [comment] 2023-07-28 18:31
I agree that this is a duplicate of https://github.com/Expensify/App/issues/23308 that @ayazhussain79 reported 8 days ago. Going to close this one in favor of that one 👍

**Closed** 2023-07-28 18:31 UTC
Labels: Daily, Bug
