### ISSUE TITLE
Web – Inconsistency in the placement of the downward arrow icon in relation to "New Message" and "Show More" buttons

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26670] opened 2023-09-04 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any chat window.
2.	Mark the latest message as unread and scroll to the top.
3.	Observe that the "New Message" button with a downward arrow is positioned on the left.
4.	Click on the FAB (Floating Action Button) marked by a plus sign.
5.	Choose the "Request Money" option from the menu.
6.	Enter the desired amount and click the "Next" button.
7.	Select the user with whom the money request will be initiated.
8.	Notice that the "Show More" option is displayed with a downward arrow on the right side.

## Expected Result:
Consistency should be maintained across all sections, deciding whether the arrow should appear on the left or right side.

## Actual Result:
There is an inconsistency in the placement of the downward arrow icon, with it being positioned on the left for "New Message" and on the right for "Show More".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/12e8b523-7c6b-4bfc-a582-71d54191c591

https://github.com/Expensify/App/assets/115492554/2164175c-3ff4-42a2-a41f-1eb0e092f246

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692774963958649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-09-04 16:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Inconsistency in the placement of the downward arrow icon in relation to "New Message" and "Show More" buttons

### What is the root cause of that problem?

In `New messages` Button we placed the downward arrow on the left side of the `New messages` text.

https://github.com/Expensify/App/blob/c805b6747bb29aea038f9f8ec1831a16f643f688/src/pages/home/report/FloatingMessageCounter/index.js#L62-L84

But In `Show More` Button we placed the downward arrow on the right side of the `Show more` text.

https://github.com/Expensify/App/blob/c805b6747bb29aea038f9f8ec1831a16f643f688/src/components/Button/index.js#L228-L250

This is the root cause of this problem.

### What changes do you think we should make in order to solve the problem?

We can change the code [here](https://github.com/Expensify/App/blob/c805b6747bb29aea038f9f8ec1831a16f643f688/src/pages/home/report/FloatingMessageCounter/index.js#L64):

```js
      <Button
          success
          small
          onPress={props.onClick}
          text={translate('newMessages')}
          shouldShowRightIcon
          iconRight={Expensicons.DownArrow}
          iconFill={themeColors.icon}
          style={styles.mh0}
      />
```

### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment] 2023-09-05 02:40
I can reproduce but I'm not sure if this is something we want to fix/what the right side is
<img width="1122" alt="image" src="https://github.com/Expensify/App/assets/42940078/86c78066-76af-4278-b06f-3746665ab18a">

**Comment by sophiepintoraetz** [comment] 2023-09-05 02:43
Asking [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1693881809686459) and bumping this to weekly as this is not a priority.

**Comment by sophiepintoraetz** [comment] 2023-09-13 09:35
CLosing as not a bug.

**Closed by sophiepintoraetz** 2023-09-13 09:35 UTC
Labels: Weekly, Overdue, Bug
