### ISSUE TITLE
[HOLD on #23780 & #23780] Web - Routing number field doesn't give an error util user type something into Account number field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23789] opened 2023-07-28 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings
2. Click on Workkspaces > Bank Account (It takes us to Connect bank account Step 1 of 5)
3. Type something to first field and get the cursor to second one. Here first input doesn't give us error till we start typing on the second field.

## Expected Result:
Routing number field should't give an error whenever user focus out of it

## Actual Result:
Routing number field doesn't give an error util user type something into Account number field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (56).webm](https://github.com/Expensify/App/assets/93399543/c4eb3c22-7c8e-45c5-8db7-9ea5176bdc24)

https://github.com/Expensify/App/assets/93399543/bb324459-519b-4557-a6a0-26077d15dd58

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690519501033259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-28 12:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Routing number field doesn't show an error until user types something in account number

### What is the root cause of that problem?

Here is our validation logic when blur event occurs.
As you can see, if the last validated values are the same as the current values, we don't validate again though touchedInputs flag changes.

When a user types in routing number field, validation is done and the form values is stored in `lastValidatedValues.current`. On blur event, we set touched flag for the routing number and try to validate but the form values didn't change. That's why validation isn't done.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to touchedInputs flags as well for checking if we should validate again.
Replace the above code with the following code
```
        // To prevent server errors from being cleared inadvertently, we only run validation on blur if any form values have changed since the last validation/submit
        const shouldValidate = !_.isEqual(inputValues, lastValidatedValues.current) || !touchedInputs.current[inputID];
        setTouchedInput(inputID);
        if (shouldValidate) {
            onValidate(inputValues);
        }
```

This works as expected
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-07-28 13:12
Seems regression from https://github.com/Expensify/App/pull/23306

**Comment by joh42** [comment] 2023-07-28 17:16
Also just to be clear, this issue is a duplicate of https://github.com/Expensify/App/issues/23743, which was created roughly 12 hours before this issue was reported in Slack.

**Comment by joh42** [comment] 2023-08-02 17:50
The [PR](https://github.com/Expensify/App/pull/23780) fixing this regression has been deployed to staging now @twisterdotcom 

https://github.com/Expensify/App/assets/138504087/988206eb-8401-42c0-8f70-254b1e8c5cc3

Again, this issue was a dupe of https://github.com/Expensify/App/issues/23743

**Comment by twisterdotcom** [comment] 2023-08-07 16:35
Thanks @joh42. closing this now.

**Closed by twisterdotcom** 2023-08-07 16:35 UTC
Labels: Weekly, Overdue, Bug
