### ISSUE TITLE
[HOLD for payment 2023-11-01] [HOLD for payment 2023-10-13] [$500] Web - The order of avatars on the header sometimes matches the avatars on chat view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28048] opened 2023-09-22 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/25416

## Action Performed:
Precondition: Logged into new dot.
1. Create a group chat.
2. Observe the order of avatars on the header and the order of avatars on the chat view.

## Expected Result:
The order should match.

## Actual Result:
The order sometimes matches or doesn't match.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c8f34fa1-29f2-457b-adc6-c737ea1e2183

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e20b778de4f7c770</li>
        <li>Upwork Job ID: 1706233303056359424</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26875267</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-23 04:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In a group chat, the order of participants in the header is not sorted the same way as the avatars in the chat view.

### What is the root cause of that problem?
In ReportUtils, the `getDisplayNamesWithTooltips` implementation which is used in the header view does not apply any sorting to the display names returned. `getIconsForParticipants` however does apply a sort to the avatars returned.

### What changes do you think we should make in order to solve the problem?
Apply the logic for sorting used in `getIconsForParticipants` to `getDisplayNamesWithTooltips`. Also add a flag parameter, `shouldSort` to `getDisplayNamesWithTooltips` which indicates whether or not the returned names should be sorted.


### What alternative solutions did you explore? (Optional)
None.

**Comment by mountiny** [comment] 2023-09-25 08:39
cc @cead22 @mananjadhav @honnamkuan seems like this was found coming from your PR, potential regression

**Comment by akinwale** [comment] 2023-09-25 08:47
@mountiny It looks like the names in the header were not being sorted prior, and based on the issue history at https://github.com/Expensify/App/issues/23364, the selected proposal is fixing an existing sorting implementation, so it's safe to assume that it's probably not a regression since the names in the header were never a consideration in the first place.

**Comment by cead22** [comment] 2023-09-25 08:55
> Apply the same logic for sorting used in `getIconsForParticipants` to `getDisplayNamesWithTooltips`

👍 . I don't think we need the optional parameter, in fact, I imagine we don't want the optional parameter since that will allow us to sort things differently, right?

**Comment by mountiny** [comment] 2023-09-25 09:04
Thanks for confirming, I have admitedly not gone through the linked issue, just coming off the QA linking it at the header.

**Comment by akinwale** [comment] 2023-09-25 09:12
> > Apply the same logic for sorting used in `getIconsForParticipants` to `getDisplayNamesWithTooltips`
> 
> 👍 . I don't think we need the optional parameter, in fact, I imagine we don't want the optional parameter since that will allow us to sort things differently, right?

Well, I was assuming since `getDisplayNamesWithTooltips` is also used in the LHN, performance might take a hit having to sort  for all open reports, especially for users with a lot of reports. I have not specifically measured this, however.

**Comment by akinwale** [comment] 2023-09-26 05:20
@allroundexperts My [PR](https://github.com/Expensify/App/pull/28218) is ready for review. Thanks.

**Comment by stitesExpensify** [comment] 2023-10-05 23:47
@akinwale can you create a PR with your proposed fix please and link it here?

**Comment by akinwale** [comment] 2023-10-06 09:32
@stitesExpensify I've created a follow-up [PR](https://github.com/Expensify/App/pull/28991). I would like to get some more eyes on the `isGroupChat` method for additional insight, if possible. Thanks.

cc @allroundexperts

**Comment by miljakljajic** [comment] 2023-10-20 09:13
What are the next steps for this one?

**Comment by akinwale** [comment] 2023-10-20 09:17
> What are the next steps for this one?

Currently waiting for feedback on the [second PR](https://github.com/Expensify/App/pull/28991).

**Comment by miljakljajic** [comment] 2023-10-20 09:19
@allroundexperts can you review when you have a chance?

**Comment by miljakljajic** [comment] 2023-11-02 16:05
@akinwale offer sent!

**Comment by akinwale** [comment] 2023-11-02 16:17
> @akinwale offer sent!

Accepted. Thanks!

**Comment by miljakljajic** [comment] 2023-11-02 16:24
Paid! Closing.

**Closed by miljakljajic** 2023-11-02 16:24 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by miljakljajic** [comment] 2023-11-02 17:18
@allroundexperts I skipped you for payment based on this [comment](https://github.com/Expensify/App/issues/28048#issuecomment-1779641264):

>@allroundexperts does not require payment (Eligible for Manual Requests)

Is that a mistake?

**Comment by miljakljajic** [comment] 2023-11-02 17:26
Ah @allroundexperts I totally misunderstood that message. Thank you and sorry! 

Payment Summary:

@allroundexperts eligible for $500 based on their work as the C+ reviewing the PR.
