### ISSUE TITLE
[$500] Expense  - Submit button only changes color after visiting expense details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33954] opened 2024-01-04 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12.1
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33030

## Action Performed:
Precondition:
User is an employee of Collect workspace on Old Dot.
Schedule submit is disabled.
1. Go to workspace chat as employee.
2. Click + > Request money > Manual.
3. Create a manual request.
4. As Admin, enable Schedule submit on Old Dot.
5. As employee, refresh the workspace chat (might require several times).
6. Note that the green dot disappears but the Submit button does not change to gray colour.
7. Go to the expense details page and return to the main chat.
8. Now the Submit button changes color after returning from expense details page.
9. As Admin, disable Schedule submit.
10. As employee, repeat Step 5 - 7.
11. Note that the Submit button does not change to green until after returning from expense details page.

## Expected Result:
Submit button should not change color after visiting expense details page

## Actual Result:
Submit button only changes color after visiting expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/18c3cc44-e905-43c8-97ef-9ccea52ad5c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ba1a15cebf0f32e</li>
        <li>Upwork Job ID: 1744484517121257472</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2024-01-04 15:57
@mountiny looks like this came up while testing your PR. Any ideas?

**Comment by mountiny** [comment] 2024-01-04 16:15
I can handle this one, its not a blocker since this is a new functionlity in the flow and we just need to listen to the policy scheduled submit property change to rerender

**Comment by mountiny** [comment] 2024-01-05 19:12
havent got around

**Comment by mountiny** [comment] 2024-01-08 12:11
@waterim will tackle it, can you please comment so i can assign you?

**Comment by waterim** [comment] 2024-01-08 12:13
Hey, Im Artem from Callstack and would like to take this one

**Comment by waterim** [comment] 2024-01-10 00:48
Okay, this issue is probably with updating data in policy from pusher.
This issue is a little bit random, because sometimes it works for 10 times, sometimes it can brake just in a first try 10 times in a row.

I made the scheduled submit as "Enabled"
<img width="370" alt="image" src="https://github.com/Expensify/App/assets/39777589/51cb61c1-fffa-4c3e-bc58-0733e2a61ac5">
But data in policy(from where we are getting **isHarvestingEnabled**) is wrong for some reason 
<img width="1352" alt="image" src="https://github.com/Expensify/App/assets/39777589/382e2633-f7e6-47a5-bd6d-0c7c700ebb76">

@mountiny 
"think we just need to subscribe the report preview component to the policy change so it rerenders when the pusher update changing the scheduled submit settings comes in"
Rerender is happening each time policy.isHarvestingEnabled is changing, but the value is not changing for some reason.

But again, this issue is not consistent, sometimes I can't even reproduce it for 20 times in a row, sometimes otherwise I can for 20 times in a row

**Comment by mountiny** [comment] 2024-01-10 11:39
@waterim interesting, so to confirm you can see the data being reliably (always) sent from the pusher but onyx sometimes does not update it? 

Is there maybe some other data sent that would cause some kind of a race condition and reverting the update?

**Comment by waterim** [comment] 2024-01-10 12:24
@mountiny yes, data is coming each time I change the switch on the old dot, but onyx sometimes randomly doesn’t update

as I can see no revert data is coming for isHarvesting

**Comment by mountiny** [comment] 2024-01-10 12:46
@waterim would you be able to debug the onyx not updating case?

**Comment by waterim** [comment] 2024-01-10 12:47
Trying to find the reason

**Comment by waterim** [comment] 2024-01-10 15:13
Damn, cant reproduce for half an hour :D

**Comment by waterim** [comment] 2024-01-10 17:29
https://github.com/Expensify/App/assets/39777589/8a10fa61-1504-42ec-959a-6f0fd30940ab

**Comment by mountiny** [comment] 2024-01-10 18:52
Thanks for digging, I will close this as it does not seem specific to this flow if anything its general onyx issue

**Closed by mountiny** 2024-01-10 18:52 UTC
Labels: External, Engineering, Daily
