### ISSUE TITLE
DEV: Link within Concierge conversation open page not found

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20166] opened 2023-06-05 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisites: Account must be created via dev
1. Go to Concierge chat
2. Click on any link within Concierge conversation

## Expected Result:
 It should open corresponding page.

## Actual Result:
It shows page not found.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d3a05c4-9bd6-4703-930c-d28dce17bd45

**Expensify/Expensify Issue URL:**

**Issue reported by:** @PrashantMangukiya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685015247082279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2023-06-06 09:28
I'd say not a bug, the links open correctly in Old Expensify DEV when my VM is running. I don't think it matters if non-internal devs are able to open links in the DEV environment since these links will work in both staging and production

**Comment by laurenreidexpensify** [comment] 2023-06-06 15:04
Speaking to @grgia and @puneetlath this is intentional and not a bug -  if someone without a dev environment opens a dev url and it doesn’t work that seems like the correct outcome. Closing.

**Closed by laurenreidexpensify** 2023-06-06 15:04 UTC
Labels: Daily, Needs Reproduction, Bug
