### ISSUE TITLE
Workspace - No Admin room is created after creating a workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46982] opened 2024-08-07 15:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bezawitgebremichael+101102@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Navigate to inbox and observe that no admin room is created
4. Go back to workspace settings page and add a member
5. Go to inbox
6. Observe admin room is created

## Expected Result:
Admin room should be created when creating a workspace

## Actual Result:
Admin room doesn't get created after creating a workspace and it only gets visible on LHN when a member is added in the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bb8f4c82-b1d2-4729-a7a3-33e8bd3975ff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![Bug6554594_1722077893960!Screenshot_1](https://github.com/user-attachments/assets/8ad748e5-1bb0-413c-b503-edda270bfbfd)

**Comment by izarutskaya** [comment] 2024-08-07 15:46
We think this issue might be related to the #collect project.

**Comment by codewaseem** [comment] 2024-08-07 22:50
Hi @izarutskaya ,

I think it's not a bug. This is new behavior based on the requirements from #36236 merged recently by this PR: #45048.

**Comment by adelekennedy** [comment] 2024-08-08 06:05
Agree - I don't think this is a bug

**Closed by adelekennedy** 2024-08-08 06:05 UTC
Labels: Daily, Bug
