### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] [ECARD TRANSACTIONS] `Pay elsewhere` button is missing the reimbursable total

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34620] opened 2024-01-16 22:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705442420036949?thread_ts=1705442308.576449&cid=C05DWUDHVK7

## Action Performed:
1. Create a free workspace and set it as your default
2. Add a manual request
3. Tap into the report 
4. Select the payment option dropdwown

## Expected Result:
Both `Pay with Expensify` and `Pay elsewhere` buttons should include the reimbursable total you are paying in the button copy

## Actual Result:
`Pay elsewhere` does not include this total

![image](https://github.com/Expensify/App/assets/22508290/a8a29031-881c-4008-82a1-1eee31bef460)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5409827a7bf0019</li>
        <li>Upwork Job ID: 1748141602955698176</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28110702</li>
<li>esh-g | Contributor | 28110704</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2024-01-19 06:57
@esh-g 's [proposal here](https://github.com/Expensify/App/issues/34620#issuecomment-1895716952) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment] 2024-02-18 11:54
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #22484 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22484/files#r1493748140
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not started because this has been appearing this way but now it is preferred to add amount in the `Pay elsewhere` as well.
* [x]  [@c3024] Determine if we should create a regression test for this bug. No, I think this is not a significant bug that meaningfully affects user experience adversely.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by jliexpensify** [comment] 2024-02-21 02:18
Just catching up - I will need to create a new Upworks job as the old one was closed.

**Comment by jliexpensify** [comment] 2024-02-21 02:25
Payment Summary

- Contributor: @esh-g $500
- C+: @c3024 $500

[New Upworks Job](https://www.upwork.com/jobs/~014670ec79c0b26236)

**Comment by c3024** [comment] 2024-02-21 02:29
Offer accepted!

**Comment by jliexpensify** [comment] 2024-02-21 03:58
Paid and job closed!

**Closed by jliexpensify** 2024-02-21 03:58 UTC
Labels: External, Daily, Awaiting Payment, Bug
