### ISSUE TITLE
[$500] Web-Task-Assignee page keeps on loading on refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32935] opened 2023-12-12 16:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click 1:1 chat
3. Click plus icon --- assign task
4. Enter title & description
5. Click next
6. Click Assignee and wait till it loads completely
7. Click browser refresh button

## Expected Result:
The assignee page must display contacts and must not load infinitely on refreshing the page

## Actual Result:
The assignee page keeps on loading on refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1240a7cb-94bb-41ed-a2c2-25ac26f775ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b79b79e8a7600de</li>
        <li>Upwork Job ID: 1734615988564508672</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by rdvntpl** [comment] 2023-12-12 17:28
It works fine.

https://github.com/Expensify/App/assets/15113737/7c8cdda3-7d27-4b30-9f16-f2e8b10c32b5

**Comment by rdvntpl** [comment] 2023-12-12 17:33
Contributor details
Your Expensify account email: rdvn.tpl.11@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d965eec08009bbc9

**Comment by Berndy** [comment] 2023-12-12 17:47
I was about to submit the same proposal as @DylanDylann, this solves the issue. However I did have some troubles reproducing the issue at the start as well. First it worked fine, then applying throttling caused the issue and when removing the throttle it worked fine again. Then all of a sudden it completely stopped working in staged and locally. I'm a bit concerned there might be some underlying state issue that stops the navigation event from firing?

**Comment by kbirulia** [comment] 2023-12-12 17:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

-  Web-Task-Assignee page keeps on loading on refreshing the page


### What is the root cause of that problem?

- listener is not catch navigation if we just loaded page:
<img width="889" alt="Screenshot 2023-12-12 at 18 51 48" src="https://github.com/Expensify/App/assets/22476665/74b85fd4-7923-4c31-90e1-3888441f6917">

### What changes do you think we should make in order to solve the problem?


- We need to check if it is the first route, then we don't need to wait for transition
<img width="839" alt="Screenshot 2023-12-12 at 18 55 19" src="https://github.com/Expensify/App/assets/22476665/f46b64f0-0c11-449d-81e0-160b4a2b3c3d">


### What alternative solutions did you explore? (Optional)

**Comment by Berndy** [comment] 2023-12-12 17:57
Contributor details
Your Expensify account email: berndytest1234@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e90533510f1c3728

**Comment by shadman17** [comment] 2023-12-13 07:42
Contributor details
Your Expensify account email: shadman.wasif@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015b26e1f746f5d79d

**Comment by mollfpr** [comment] 2023-12-18 16:50
I think this issue also reproduces in `TaskShareDestinationSelectorModal`, so the solution should be global enough to resolve it on other pages.

---

@kbirulia What is the reason for checking the first route?

---

@bernhardoj I think I'm inclined to have the global solution instead of updating it in every component.

**Comment by DylanDylann** [comment] 2023-12-18 16:56
@mollfpr As I mentioned in my proposal (**alternative solution** section), we already had the util function to get the ```isScreenTransitionEnded```

**Comment by situchan** [comment] 2023-12-18 17:02
We can close this as dupe of https://github.com/Expensify/App/issues/22508 which is re-opened and has same root cause

**Comment by kbirulia** [comment] 2023-12-19 17:10
I figure out another solution. ScreenWrapper listen only for transitionEnd to display content. As I mentioned before it doesn't happen if we  loaded content first time.

1.  I would suggest to set  didScreenTransitionEnd as true for initial. 
2. Listen for transitionStart to set it false.
3. We need also do it in useLayoutEffect instead of useEffect, so we can properly catch transitionStart

**Comment by greg-schroeder** [comment] 2023-12-21 19:08
discussed in slack and I think we're closing in favor of https://github.com/Expensify/App/issues/32935#issuecomment-1861068563

**Closed by greg-schroeder** 2023-12-21 19:08 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
