### ISSUE TITLE
 Workspace - Blue focus is shown when changing workspace name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31725] opened 2023-11-22 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to settings
2. Workspace
3. Go to an existing workspace or create one
4. Click on the workspace name to go to the settings. (Don't go to the settings by clicking on 'Settings')
5. Change the name and Click the Enter Key on the Key Board to Save. (Don't click on the 'save' button to save.)

## Expected Result:
The name changes and no Blue focus is shown on the Workspace Name

## Actual Result:
The name changes and Blue focus is shown on the Workspace Name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d2877265-7290-4df4-8af4-321934fbf6cf

![Bug6286965_1700650339036!image](https://github.com/Expensify/App/assets/78819774/18255318-3e0b-4f8b-9245-66bc0e36aed7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-11-22 17:06
Production: 

https://github.com/Expensify/App/assets/78819774/23a9fc14-71b4-4e3b-a10c-fe6531824395

**Comment by arosiclair** [comment] 2023-11-22 17:42
Thanks @dukenv0307 you're alternative solution makes sense to me but I'm not very familiar and could use a second opinion from those on that focus trap PR. 

@kosmydel @blazejkustra @roryabraham what do you guys think? Does it make sense to disable this focus trap by default?

**Comment by luacmartins** [comment] 2023-11-22 19:21
I think the option above makes sense. @dukenv0307 are you available to work on a PR to fix all instances of this bug?

**Comment by luacmartins** [comment] 2023-11-22 19:27
Actually, we'll just revert the original PR since it introduced other blockers.

**Comment by luacmartins** [comment] 2023-11-22 19:56
The issue is resolved when I revert that PR

**Comment by arosiclair** [comment] 2023-11-22 20:20
Agree with reverting the PR if that fixes it. We can try pushing that PR through again later after resolving the issue. Should I raise the PR or are you on it @luacmartins?

**Comment by luacmartins** [comment] 2023-11-22 20:25
I think @kosmydel should work on v3 of that PR and fix this issue

**Comment by luacmartins** [comment] 2023-11-22 20:26
Offending PR was reverted. Removing blocker label.

**Comment by arosiclair** [comment] 2023-11-22 23:11
This should be all set

**Closed by arosiclair** 2023-11-22 23:11 UTC
Labels: Engineering, Daily
