### ISSUE TITLE
Profile - Growl is missing "Your profile has been saved successfully" when saved the changes.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10215] opened 2022-08-02 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to profile sections and make any changes
4. Click Save button

## Expected Result:
The message "Your profile has been saved successfully" should be present

## Actual Result:
Growl is missing "Your profile has been saved successfully" when saved the changes.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182472786-6fda4dd2-6351-47c6-9f35-cfdd07a846ae.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-08-02 22:10
Hm, I'm looking into this a little bit, and because of our refactoring, the growl was intended to be removed. However, there are some problems with the submit button on this form:

What I am seeing is...

- Edit name
- Click on save
- button becomes disabled
- API request is successful
- button remains disabled
- Edit name again
- button is still disabled
- click on the button
- API request is successful

So... a couple of things.

1. The button should be enabled again after the request is successful
2. Clicking on a disabled button should not allow the form to be submitted

**Comment by tgolen** [comment] 2022-08-02 22:50
I reached out to a few people in Slack to see if they can provide insight to the functionality, so I am waiting to hear back from that. If I don't hear anything tomorrow, let's consider reverting the user settings profile change.

cc @marcaaron @yuwenmemon

**Comment by Beamanator** [comment] 2022-08-03 09:07
Oofda this was probably my change, I'll look into it now

**Comment by Beamanator** [comment] 2022-08-03 09:48
Looks like the problem is with the button styling, not button being disabled - the button is somehow a bit grayed out after editing, saving, and editing again - but it's not actually disabled (via `isButtonDisabled`)

Completely disabled: Opacity 0.5
Slight gray styling: Opacity 0.827092 (this changes somehow!!)
Normal button: Opacity 1

**Comment by Beamanator** [comment] 2022-08-03 10:22
Something interesting I'm seeing: When we have the old `PersonalDetails.setPersonalDetails` code, dimming & un-dimming (via `OpacityView`) finishes:

<img width="277" alt="Screen Shot 2022-08-03 at 12 20 39 PM" src="https://user-images.githubusercontent.com/3885503/182585282-d0d0b030-54ee-4e90-952c-a2bbd5279b15.png">

However, when we use my updated code (`PersonalDetails.updateProfile`), dimming and undimming **DOESN'T finish**:

<img width="270" alt="Screen Shot 2022-08-03 at 12 22 04 PM" src="https://user-images.githubusercontent.com/3885503/182585584-9a265c3f-0f0c-466c-a5f0-526d30131779.png">

I believe this is due to the fact that we're now immediately changing the Onyx state after clicking the button, so the animation in `OpacityView` doesn't have time to finish undimming the button (making it full opacity)

**Comment by Beamanator** [comment] 2022-08-03 10:24
I got the ^ "finished dimming / undimming" logs by adding console logs here:

![Screen Shot 2022-08-03 at 12 23 16 PM](https://user-images.githubusercontent.com/3885503/182585871-bc898fda-632f-4f39-95a1-116e50121e18.png)

**Comment by Beamanator** [comment] 2022-08-03 10:53
Closing this in favor of https://github.com/Expensify/App/issues/10230, also I don't think this is a Deploy blocker since it's just an opacity issue

**Closed by Beamanator** 2022-08-03 10:53 UTC
Labels: DeployBlockerCash, Engineering, Hourly
