### ISSUE TITLE
[$500] IOU - "Save" button is shown before the "Delete" popup appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33473] opened 2023-12-22 00:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Do a "Distance" request with stops
3. Delete one of the stops

## Expected Result:
The "Save" button shouldn't be visible while deleting a stop

## Actual Result:
The "Save" button is displayed simultaneously with other buttons

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0079611c-e38f-4e15-bf03-f2128b6482e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018490ade582580d49</li>
        <li>Upwork Job ID: 1737994498107367424</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by rushatgabhane** [comment] 2023-12-22 05:14
do nothing because i don't think this is an issue

**Comment by Aaslan01** [comment] 2023-12-22 19:55
Please re-state the problem that we are trying to solve in this issue.
IOU - "Save" button is shown before the "Delete" popup appears

What is the root cause of that problem?
First of all, this isn’t the issue, it's the component's hide and show time, you hide the first popup and the mean time popup another, this is the Delay of Components.

What changes do you think we should make in order to solve the problem?
I think you using RBSheet in the App so I would go for the first open 2nd Sheet, and behind with serTimeOut we will close the 1st sheet.

What alternative solutions did you explore? (Optional)
(Must Work) with props showSaveButton we can handle it in one way or another but it will work,

**Comment by Aaslan01** [comment] 2023-12-24 07:52
Contributor details
Your Expensify account email: alisher.cs625@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018a6da599ca8c9fae

**Comment by peterdbarkerUK** [comment] 2023-12-27 12:31
Yeah I think this is working as intended - the save button does get blocked when the deletion confirmation box comes up. It feels like a step too many to hit a 3 dot menu, select delete from a list of one, and then. confirm the deletion, but that's not a bug. 

Closing, please LMK if you disagree!

**Closed by peterdbarkerUK** 2023-12-27 12:31 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
