### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500]  IOU – The receipt route image is blank after adding a stop in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34287] opened 2024-01-10 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as the employee
3. Navigate to a distance request details conversation
4. Disable the internet connection
5. Click on the distance item
6. Add a new stop to the route and save
7. Navigate to the report conversation

## Expected Result:
After adding a stop in offline mode, the receipt route image should be pending, and the distance and amount should show as TBD

## Actual Result:
The receipt route image is blank after adding a stop in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/48efd4c5-bc00-4b48-888a-d55c881a5534

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164c29443ff05e829</li>
        <li>Upwork Job ID: 1745155412648595456</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28101450</li>
<li>paultsimura | Contributor | 28101451</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-10 18:53
This is a dupe of https://github.com/Expensify/App/issues/34049 – a regression from https://github.com/Expensify/App/pull/33586

**Comment by paultsimura** [comment] 2024-01-10 19:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The pending distance request receipt is blank.

### What is the root cause of that problem?
This started happening https://github.com/Expensify/App/pull/33586 where we tried to define the local files instead of returning `isLocalFile: true` for all the receipts that didn't match the early-return criteria.

This is because after a distance request is modified, we are waiting for the BE response to generate a new map snapshot to be used as a thumbnail here. So we are using a receipt URL that does not yet exist.

### What changes do you think we should make in order to solve the problem?
We already check the Distance transaction to not be pending here:

https://github.com/Expensify/App/blob/d9e75d5b1eab9525d83facd34370a4fe21bee374/src/libs/ReceiptUtils.ts#L40-L53

We just need to add another check for the cases when the Distance request has a pending waypoint (the opposite check):

```js
if (Object.hasOwn(transaction?.pendingFields ?? {}, 'waypoints')) {
    return {thumbnail: null, image: ReceiptGeneric, isLocalFile: true};
}
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-10 19:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The pending distance request receipt is blank.

### What is the root cause of that problem?
This started happening https://github.com/Expensify/App/pull/33586 where we tried to define the local files instead of returning `isLocalFile: true` for all the receipts that didn't match the early-return criteria.

This particular issue is happening because after a distance request is modified, we are waiting for the BE response to generate a new map snapshot to be used as a thumbnail here, and we optimistically use the URL of an image that still has to be generated on the BE, as a receipt. It looks like a normal image URL, not a local file.

### What changes do you think we should make in order to solve the problem?
This pending distance request case is quite unique. For this, we already check the Distance transaction to not be pending (not have pending waypoints) here:

https://github.com/Expensify/App/blob/d9e75d5b1eab9525d83facd34370a4fe21bee374/src/libs/ReceiptUtils.ts#L40-L53

We just need to add another check for the cases when the Distance request has a pending waypoint (the opposite check) and not wait until the final return, which will now return `isLocalFile: false` instead of `true`.

```js
    if (Object.hasOwn(transaction?.pendingFields ?? {}, 'waypoints')) {
        return {thumbnail: null, image: ReceiptGeneric, isLocalFile: true};
    } else {
        if (hasEReceipt) {
            return {thumbnail: null, image: ROUTES.ERECEIPT.getRoute(transaction.transactionID), transaction};
        }

        // For local files, we won't have a thumbnail yet
        if (isReceiptImage && (path.startsWith('blob:') || path.startsWith('file:'))) {
            return {thumbnail: null, image: path, isLocalFile: true};
        }

        if (isReceiptImage) {
            return {thumbnail: `${path}.1024.jpg`, image: path};
        }
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-01-10 20:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The receipt route image is blank after adding a stop in offline mode

### What is the root cause of that problem?
When we update the waypoints we are not resetting the receipt on the transaction in onyx so it still exists so although in 
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/libs/ReceiptUtils.ts#L68-L70 
we are returning the `ReceiptGeneric` thumbnail `isLocalFile` is not set to true as `path` is found from `transaction?.receipt?.source` which is not local so it will try to load it but fails as we are offline 
### What changes do you think we should make in order to solve the problem?

The right solution is to reset receipt of the transaction on saving waypoint in onyx b/c it is obsolate as we do for routes as in here
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/libs/actions/Transaction.ts#L73-L79
```
receipt: {source: null},
filename: null,
```

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2024-01-13 12:32
@paultsimura's [proposal](https://github.com/Expensify/App/issues/34287#issuecomment-1885558827) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by paultsimura** [comment] 2024-01-16 20:19
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34604

**Comment by kadiealexander** [comment] 2024-02-02 02:31
@shubham1206agra don't forget about the checklist please!

**Comment by kadiealexander** [comment] 2024-02-02 03:02
Payouts due:

- [x] Contributor: $500 @paultsimura
- [ ] Contributor+: $500 @shubham1206agra

Upwork job is [here](https://www.upwork.com/jobs/~0164c29443ff05e829).

**Comment by shubham1206agra** [comment] 2024-02-02 03:18
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34030
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34030/files#r1475473396
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2024-02-02 06:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
