### ISSUE TITLE
[$1000] Web - After refreshing the Tab deleted messages re-appear

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21532] opened 2023-06-25 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send any message in the chat
2. Create a thread and send another message in the thread
3. Delete the main and thread message
4. Delete again the massage that shows deleted massage it vanishes
5. Refresh the tab the deleted message re-appears

## Expected Result:
If the deleted message vanishes it won't appear after refreshing the tab

## Actual Result:
 Deleted message vanish after deleting it but after refreshing the tab it appears again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v 1.3.26
**Reproducible in staging?:** y
**Reproducible in production?:**y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ce9f6e4b-2aea-48ff-9f0a-4b54dd335447

https://github.com/Expensify/App/assets/93399543/44c8492a-fbf2-472b-9400-a5e041b4a928

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MohsinAliTanvir
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687162197242079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163a2201d3f4a2131</li>
        <li>Upwork Job ID: 1673914628605444096</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-06-28 04:41
Alright, I'm able to reproduce this bug. I think I agree with the contributor above that you shouldn't have the option to delete in the comment action menu after first deleting. That why we you take that action a second time is does nothing (which is the correct behavior). Opening this up for the community.

**Comment by situchan** [comment] 2023-06-28 04:45
Dupe of #21103

**Comment by s77rt** [comment] 2023-06-28 19:28
@JmillsExpensify Looks like a dupe; Can we close this?

**Comment by s77rt** [comment] 2023-06-30 20:50
@JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-03 22:32
Not overdue. @JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-07 23:06
Not overdue. @JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-10 10:50
@JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-12 17:42
Not overdue. @JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-15 18:17
@JmillsExpensify ^

**Comment by s77rt** [comment] 2023-07-16 22:37
We don't need a PR here Melvin, we will just close the issue.

**Comment by s77rt** [comment] 2023-07-19 22:23
Not overdue. @JmillsExpensify

**Comment by s77rt** [comment] 2023-07-23 21:49
@JmillsExpensify Let's close this

**Comment by JmillsExpensify** [comment] 2023-07-24 23:24
Apologies, catching up on a backlog. Closing this out.

**Closed by JmillsExpensify** 2023-07-24 23:24 UTC
Labels: Engineering, Daily, Internal, Bug
