### ISSUE TITLE
[HOLD for Payment 2024-08-26] [$250] Subscription - Subscription page changes to not here page while signing out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46735] opened 2024-08-02 15:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has at least one workspace (so Subscription tab will show up)
1. Go to staging.new.expensify.com
2. Go to Account settings > Subscription
3. Sign out while on Subscription screen

## Expected Result:
Subscription page will not change to not here page while signing out

## Actual Result:
Subscription page changes to not here page while signing out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a9e63496-a08b-4bf4-b6c1-2ca66763efcc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e94c4a46033756a</li>
        <li>Upwork Job ID: 1820555883332358994</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 103422107</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-08-02 15:54
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-02 15:54
We think that this bug might be related to #wave-collect - Release 2

**Comment by Tony-MK** [comment] 2024-08-04 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subscription - Subscription page changes to not here page while signing out

### What is the root cause of that problem?

The root cause of the problem is that the session is deleted from the Onyx when signing out hence, the `ownerPolicies` becomes empty.

https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/hooks/useSubscriptionPlan.ts#L21-L23

Therefore, the `useSubscriptionPlan` hook will be called again and a null `subscriptionPlan` to render the `NotFoundPage`.

https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/pages/settings/Subscription/SubscriptionSettingsPage.tsx#L30-L32

### What changes do you think we should make in order to solve the problem?


Let's give the `subscriptionPlan` a state so the `SubscriptionSettingsPage` will not render `NotFoundPage` on its second attempt when signing out.

```
const subscriptionPlan = useState(useSubscriptionPlan());
```

https://github.com/user-attachments/assets/ac148b02-163c-44de-ba51-c06b2cdb0d10

**Comment by garrettmknight** [comment] 2024-08-27 10:30
**Payment Summary:**
- Contributor: @cretadn22 $250 paid via Upwork
- Reviewer: @parasharrajat $250

**Comment by garrettmknight** [comment] 2024-08-30 15:13
Closing - @parasharrajat request payment when you're ready.

**Closed by garrettmknight** 2024-08-30 15:13 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 12:00
$250 approved for @parasharrajat
