### ISSUE TITLE
[$250] [HOLD for payment 2024-07-17] [HOLD for payment 2024-07-10] Workspace - Inconsistent delete modal display and brief error when deleting a user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44631] opened 2024-06-28 16:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** shussain+chrome1@applausemail.com
**Issue reported by:** Applause - Internal Team

**issue found when executing PR** https://github.com/Expensify/App/pull/44008
## Action Performed:
Precondition:
Create Control workspace in OldDot, make sure you can see it in NewDot
In OldDot, make sure the Control workspace has "Advanced Approvals" set up (on the workspace settings -> Members tab)
In OldDot, Add at least 2 other members (non-admin)
In OldDot, Set up 1 of the members (Member A) as the submitsTo of the other member (Member B)

in NewDot
1. Go to the control WS created above
2. Open member page
3. Select user A and click on remove
4. Verify that the confirm modal appears with the warning prompt [Selected member] is an approver in this workspace. When you unshare this workspace with them, we'll replace them in the approval workflow with the workspace owner, [Workspace Owner].
5. Open the member detail page of member A
6. Click on Remove from workspace button
7. Verify that the confirm modal appears with the same warning prompt in the step 4
8. Click on remove
9. Verify that the user is removed from the WS

## Expected Result:
The delete modal should consistently display the same user identifier (either "Username" or "Email") on both the list member page and the detail page. No error should appear when deleting a user

## Actual Result:
Inconsistent delete modal display and brief error when deleting a user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b91344c2-bed5-4d73-ac26-e22e15ffced8

https://github.com/Expensify/App/assets/78819774/343d77d6-12de-4eb8-a90a-5e6f1eb8314f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be201c5b6d5fc51e</li>
        <li>Upwork Job ID: 1811099866306463912</li>
        <li>Last Price Increase: 2024-07-10</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2024-06-29 00:06
@lanitochka17 Your video links are both broken - can you please re-upload?

**Comment by Beamanator** [comment] 2024-07-01 07:14
Not a web-e blocker, looks like this is caused by https://github.com/Expensify/App/pull/44008

**Comment by Beamanator** [comment] 2024-07-01 07:15
@nkdengineer it looks like your PR isn't working perfectly in a few conditions, can you please take a look at this?

**Comment by nkdengineer** [comment] 2024-07-01 07:18
It's fixed by @yuwenmemon

**Comment by Beamanator** [comment] 2024-07-01 07:19
oh i should have looked at linked PRs 😅

**Comment by ikevin127** [comment] 2024-07-04 04:20
I'm the only one requiring payment here for C+ review of PR: https://github.com/Expensify/App/pull/44654#issuecomment-2197796335.

**Comment by ikevin127** [comment] 2024-07-08 21:28
I'm the only one requiring payment here for C+ review of PR: https://github.com/Expensify/App/pull/44654#issuecomment-2197796335.

@yuwenmemon When you get a chance, mind adding the `Bug` label to this issue for payment ?

**Comment by ikevin127** [comment] 2024-07-10 16:21
@greg-schroeder Payment is due today (10th) as this was deployed to production manually in 9.0.3-7 ([reference](https://github.com/Expensify/App/issues/44631#issuecomment-2207097779)).

**Comment by greg-schroeder** [comment] 2024-07-10 18:10
Sent you an offer @ikevin127

**Comment by ikevin127** [comment] 2024-07-10 18:12
@greg-schroeder Accepted, thank you!

**Comment by greg-schroeder** [comment] 2024-07-11 11:44
Paid

**Closed by greg-schroeder** 2024-07-11 11:44 UTC
Labels: Reviewing, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
