### ISSUE TITLE
[$500] iOS - After disabling internet connection, Concierge chat renames to concierge@expensify.com

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37268] opened 2024-02-27 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+vd_022624@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.

1. On workspace selector, select a workspace.
2. On LHN page, disable the internet connection.

## Expected Result:
Concierge chat name should remain as Expensify Concierge.

## Actual Result:
Concierge chat is renamed as [concierge@expensify.com](mailto:concierge@expensify.com)
after disabling the internet connection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/15aaffb7-8a76-40eb-813a-851b722f2875

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a341057de4ee9c8</li>
        <li>Upwork Job ID: 1762424586667995136</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by pecanoro** [comment] 2024-02-27 18:52
We could not reproduce on an actual device, I am going to try the emulator

**Comment by puneetlath** [comment] 2024-02-27 19:27
I'm also not able to reproduce. Going to go ahead and close this out. Reopen if you disagree!

**Closed by puneetlath** 2024-02-27 19:27 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
