### ISSUE TITLE
[$500] Android-IOU-In distance request, selecting category and tapping request amount shows error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28693] opened 2023-10-03 08:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Tap Distance
5. Select Start and Finish way points
6. Tap Next
7. Select any Workspace
8. Select any category
9. Tap request amount

## Expected Result:
In distance request, selecting category and tapping request amount must not show error " Invalid amount".

## Actual Result:
In distance request, selecting category and tapping request amount shows error " Invalid amount".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.76-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/480ef496-6443-4221-9e2b-3312ebfe9f02

https://github.com/Expensify/App/assets/115492554/c7c6ddcc-1c98-4467-8d12-c31295d7335a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178bf7f32f5d628a7</li>
        <li>Upwork Job ID: 1709127163679703040</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-03 08:44
Not repro in Prod

https://github.com/Expensify/App/assets/115492554/7b3a681e-87d2-4b25-a6e8-e9d4f38f931f

**Comment by mountiny** [comment] 2023-10-03 08:47
This is not a blocker because its behind beta

**Comment by mountiny** [comment] 2023-10-03 08:48
@rezkiy37 @waterim can you please have a look?

**Comment by rezkiy37** [comment] 2023-10-03 08:57
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment] 2023-10-03 11:16
I've tried to reproduce on the latest `main`. This is not reproducible. Moreover, [verified](https://github.com/Expensify/App/issues/28693#issuecomment-1744502709) that on prod it also does not exist. 


https://github.com/Expensify/App/assets/57314631/3b7cee11-188a-4b99-bbc4-bc29571db927

**Comment by aldo-expensify** [comment] 2023-10-03 15:59
This may be a duplicate of https://github.com/Expensify/App/issues/28721

I'm working on another issue related to distance request here: https://github.com/Expensify/App/issues/28721#issuecomment-1745235196

**Comment by rezkiy37** [comment] 2023-10-04 09:10
Can we close the issue?

**Closed** 2023-10-04 14:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
