### ISSUE TITLE
IOU - Chat row with a red dot in LHN is not grayed out when money request fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31639] opened 2023-11-21 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. [User A] Go offline.
3. [User A] Request money from User B and stay in the chat with User B.
4. [User B] Request the same amount of money from User A.
5. [User A] Go online.

## Expected Result:
The chat row in LHN is grayed out when the red dot appears next to it.

## Actual Result:
The chat row in LHN is not grayed out when the red dot appears next to it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cf402ff4-b38f-406f-9226-3fd784a288d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-11-21 15:54
Issue is not reproducible on production

https://github.com/Expensify/App/assets/93399543/12456790-53b4-4325-8842-90e836d06179

**Comment by luacmartins** [comment] 2023-11-21 21:02
Demoting to NAB given [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1700582501649309)

**Comment by bondydaa** [comment] 2023-11-21 22:45
I think we can close this out since as best we can tell this is how it's supposed to work now. I'll follow up on the issue linked to the other PR to make sure regressions are updated.

**Closed by bondydaa** 2023-11-21 22:45 UTC
Labels: Engineering, Daily
