### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Deleting workspace in connect bank account provides update currency error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21604] opened 2023-06-26 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app in another device and login with user A (device 2)
3. In device 1, open settings->workspaces->any workspace->Bank account->Connect manually->Complete step 1 (eg data: routing= 210021002, acc no = 1234) > DO NOT CLICK SAVE
4. From device 2, open settings->workspaces->open workspace opened in step 3->Click on 3 dots and delete the workspace
5. Observe the error in device 1

## Expected Result: 
App should display 'Hmm its not here' page when workspace is deleted
## Actual Result: 
App displays error: 

"Oops! It appears that your workspace currency is set to a different currency than USD. To proceed, please set it to USD and try again"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.3.2-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3fc8e7ef-78d3-4baa-903b-352fbc51c118

https://github.com/Expensify/App/assets/43996225/95662a07-50bc-4ee9-be25-e7252d209695

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687340354605359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7395caefe5a942e</li>
        <li>Upwork Job ID: 1673414242053304320</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-26 18:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleting workspace from second tab gives update currency error in first tab

### What is the root cause of that problem?
In the `ReimbursementAccountPage` we are not checking whether policy is available or not and based on that we are not showing any not found page.

### What changes do you think we should make in order to solve the problem?
We should validate the policy and if it is empty we should return early with the notFound page(we can use more props of FullPageNotFoundView for more customization).
https://github.com/Expensify/App/blob/a77d74ba7bb6d998e52b81e24f482123e96e7222/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L333C1-L333C1
```       
       if(_.isEmpty(this.props.policy)) {
            return (
                <FullPageNotFoundView shouldShow />
            )
        }
```

**Comment by Christinadobrzyn** [comment] 2023-06-26 19:33
I can reproduce - adding engineering and External

**Comment by Pujan92** [comment] 2023-06-28 16:08
@fedirjh @grgia [PR](https://github.com/Expensify/App/pull/21819) is ready for review!

**Comment by Christinadobrzyn** [comment] 2023-06-30 05:25
Hired in Upwork: 
Internal job posting: https://www.upwork.com/ab/applicants/1673414242053304320/job-details
External job posting: https://www.upwork.com/jobs/~01b7395caefe5a942e

@dhanashree-sawant as reporter
@Pujan92 as contributor
@fedirjh as C+

**Comment by Christinadobrzyn** [comment] 2023-07-10 23:16
Do we need a regression test for this? @fedirjh?

**Comment by Christinadobrzyn** [comment] 2023-07-11 23:19
Paid! in Upwork with a bonus based on https://github.com/Expensify/App/issues/21604#issuecomment-1614146150

Closed job in Upwork and closing this GH.

**Closed by Christinadobrzyn** 2023-07-11 23:19 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
