### ISSUE TITLE
[HOLD for payment 2023-12-26] [$500] Dev: Web - Console error in modal route navigation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31487] opened 2023-11-17 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.4.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700217148936209

## Action Performed:
1. Go to NewDot
2. Log in with any account
3. Navigate to any modal route

## Expected Result:
No console error in modal route navigation

## Actual Result:
Console error in modal route navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-11-17 at 3 32 09 PM](https://github.com/Expensify/App/assets/93399543/9d178555-2fc4-4405-8030-1ebe33a005a6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb7a8b97975fcd6d</li>
        <li>Upwork Job ID: 1725501903376543744</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27849866</li>
<li>dukenv0307 | Contributor | 27849868</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-11-18 07:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- We are getting console error for BackHandler on web.

### What is the root cause of that problem?
- We are getting console error due to use of `useNavigation` hook as it uses `useBackButton` hook internally. 
- And `useBackButton` hook uses `BackHandler` which is not available in web.
- So we need to disable `useBackButton` hook on web.

### What changes do you think we should make in order to solve the problem?
- We can add below code at eod in our `@react-navigation+native+6.1.6.patch` file to disable `useBackButton` hook on web.
```
diff --git a/node_modules/@react-navigation/native/lib/module/useBackButton.js b/node_modules/@react-navigation/native/lib/module/useBackButton.js
index e016a69a1..1903b148a 100644
--- a/node_modules/@react-navigation/native/lib/module/useBackButton.js
+++ b/node_modules/@react-navigation/native/lib/module/useBackButton.js
@@ -1,6 +1,7 @@
 import * as React from 'react';
-import { BackHandler } from 'react-native';
+import { BackHandler, Platform } from 'react-native';
 export default function useBackButton(ref) {
+  if(Platform.OS === 'web') return;
   React.useEffect(() => {
     const subscription = BackHandler.addEventListener('hardwareBackPress', () => {
       const navigation = ref.current;
\ No newline at end of file
```
- One enchancement we can do is update my patch to use code from `react-native-modal+13.0.1.patch` which adds a `escape` key handler for web.
- https://github.com/Expensify/App/blob/91ef64083723d1ef98351f6f0e6eafeea6950117/patches/react-native-modal%2B13.0.1.patch#L35-L38

### What alternative solutions did you explore? (Optional)
- We can upgrade our package to latest 6.x version. But it will probably require changes in our patches and codebase.

**Comment by bfitzexpensify** [comment] 2023-11-20 22:09
Adding engineering just to confirm this is reproducible since it's a dev error.

**Comment by arosiclair** [comment] 2023-11-21 15:46
@bfitzexpensify I reproduced 👍 

<img width="1912" alt="Screenshot 2023-11-21 at 10 45 55 AM" src="https://github.com/Expensify/App/assets/6833644/7bb36603-886c-40c6-8257-6932df670d52">

**Comment by bfitzexpensify** [comment] 2023-11-21 15:48
Great. @ntdiary, looks like we've got a few proposals ready for review.

**Comment by abdullahbinahmed** [comment] 2023-11-22 06:33
## Proposal
from: @abdullahbinahmed 
### Please re-state the problem that we are trying to solve in this issue.
Backhandler is not supported for the web and is being called by React Modal so we are getting the error on the Web in console.
### What is the root cause of that problem?
BackHandler is imported in web code but is not part of the react-native-web API (0.19) anymore.
### What changes do you think we should make in order to solve the problem?
Backhandler is not present for web code as mentioned above so if the website is being accessed by the user from the web interface, we should detect it and not call backhandler for it.
This issue has been raised in react-navigation repo [here ](https://github.com/react-navigation/react-navigation/issues/11316)
So my solution is the solution that have been tested and merged in the main branch by the developer of react-navigation.
```
import type {
  NavigationContainerRef,
  ParamListBase,
} from '@react-navigation/core';
import * as React from 'react';
import { BackHandler, Platform } from 'react-native';

export default function useBackButton(
  ref: React.RefObject<NavigationContainerRef<ParamListBase>>
) {
  const handleEscape = (event) => {
    if (event.key === 'Escape') {
      const navigation = ref.current;
      if (navigation && navigation.canGoBack()) {
        navigation.goBack();
      }
    }
  };
  if (Platform.OS === 'web') {
    document?.body?.addEventListener?.('keyup', handleEscape);
    return () => {
      document?.body?.removeEventListener?.('keyup', handleEscape);
    };
  }
  React.useEffect(() => {
    const subscription = BackHandler.addEventListener(
      'hardwareBackPress',
      () => {
        const navigation = ref.current;

        if (navigation == null) {
          return false;
        }

        if (navigation.canGoBack()) {
          navigation.goBack();

          return true;
        }

        return false;
      }
    );

    return () => subscription?.remove?.();
  }, [ref]);
}
```
The patch would be created as a solution as follows:
```
--- node_modules/@react-navigation/native/src/useBackButton.tsx	2023-11-22 10:59:35.340000000 +0500
+++ test.js	2023-11-22 11:17:35.370000000 +0500
@@ -3,11 +3,25 @@
   ParamListBase,
 } from '@react-navigation/core';
 import * as React from 'react';
-import { BackHandler } from 'react-native';
+import { BackHandler, Platform } from 'react-native';
 
 export default function useBackButton(
   ref: React.RefObject<NavigationContainerRef<ParamListBase>>
 ) {
+  const handleEscape = (event) => {
+    if (event.key === 'Escape') {
+      const navigation = ref.current;
+      if (navigation && navigation.canGoBack()) {
+        navigation.goBack();
+      }
+    }
+  };
+  if (Platform.OS === 'web') {
+    document?.body?.addEventListener?.('keyup', handleEscape);
+    return () => {
+      document?.body?.removeEventListener?.('keyup', handleEscape);
+    };
+  }
   React.useEffect(() => {
     const subscription = BackHandler.addEventListener(
       'hardwareBackPress',
@@ -28,6 +42,6 @@
       }
     );
 
-    return () => subscription.remove();
+    return () => subscription?.remove?.();
   }, [ref]);
 }
```
The idea behind the solution is we only add the listeners when users tries to go back. This way we can make sure that the listener is added as late as possible. This will make sure that our handler will run first when back button is pressed.

### What alternative solutions did you explore? (Optional)
We cannot update the version of the package as this fix is not included in a version release yet so we have to create a patch file for this issue.

**Comment by abdullahbinahmed** [comment] 2023-11-22 06:39
Contributor details
Your Expensify account email: smabdullah.binahmed@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/smabdullahahmed

**Comment by arosiclair** [comment] 2023-11-22 15:12
> Hi, @arosiclair, is this the error you see when opening the app or refreshing the app?

Yes that error shows immediately after opening the app.

> we had a similar issue https://github.com/Expensify/App/issues/31120 before, and the final decision was to close that issue and wait for the upgrade.

Okay it sounds like we should upgrade. The version linked in that issue was [an alpha release](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%407.0.0-alpha.5). Has that been put in any stable release?

**Comment by arosiclair** [comment] 2023-11-27 15:37
Okay looks like that is @dukenv0307's original [proposal](https://github.com/Expensify/App/issues/31487#issuecomment-1816416294). Let's go ahead and upgrade that package.

**Comment by bfitzexpensify** [comment] 2023-12-26 20:06
Payments finalised, @ntdiary please complete the BZ checklist when you get a moment - thanks!

**Comment by bfitzexpensify** [comment] 2023-12-27 14:02
Thanks @ntdiary, agreed - let's close this out

**Closed by bfitzexpensify** 2023-12-27 14:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
