### ISSUE TITLE
[HOLD for payment 2024-08-07] [HOLD] [$1000] ReportActionContextMenu not closing properly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23959] opened 2023-07-31 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND
2. Hover on any chat for report action context menu
3. Press Add reaction
4. Now press `CTRL+K` 
5. Press the back arrow to close the search (RHP)
6. Now check the report action context menu after closing modal
## Expected Result: 
Report action context menu should be hidden, and be shown only on hovering
## Actual Result: 
Report action context menu gets stuck

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/be611be0-6900-438e-b88c-eb1b6b31347f

https://github.com/Expensify/App/assets/43996225/cdd035a1-892a-4edb-b17c-480c4b25215e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690723766793679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c8f7f084556466f</li>
        <li>Upwork Job ID: 1687252626772779008</li>
        <li>Last Price Increase: 2024-07-07</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26013711</li>
<li>shubham1206agra | Reporter | 26013714</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy / @adelekennedy</details>

**Comment by vadymbokatov** [comment] 2023-07-31 22:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ReportActionContextmenu not closing properly when mini emoji picker is opening.
### What is the root cause of that problem?
When press openpicker button on mini report action context menu, it keeps context menu to open.
https://github.com/Expensify/App/blob/3706f0becc425b818244f48b922e1337ffbbb5a2/src/pages/home/report/ContextMenu/ContextMenuActions.js#L66-L77
### What changes do you think we should make in order to solve the problem?

I think, to close context menu when press openpicker is the best option.
```
if (isMini) { 
     return ( 
         <MiniQuickEmojiReactions 
             key="MiniQuickEmojiReactions" 
             onEmojiSelected={toggleEmojiAndCloseMenu} 
             onEmojiPickerClosed={closeContextMenu} 
             reportActionID={reportAction.reportActionID} 
             reportAction={reportAction} 
         /> 
     ); 
 }
```
### What alternative solutions did you explore? (Optional)

**Comment by jfquevedol2198** [comment] 2023-07-31 22:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ReportActionContextMenu not closing properly

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/components/EmojiPicker/EmojiPicker.js#L71-L77
In `EmojiPicker`, `hideEmojiPicker` action is not calling `onModalHide`

### What changes do you think we should make in order to solve the problem?
Need to call `onModalHide` before initializing it.
```javascript
    const hideEmojiPicker = (isNavigating) => {
        onModalHide.current();
        if (isNavigating) {
            onModalHide.current = () => {};
        }
        emojiPopoverAnchor.current = null;
        setIsEmojiPickerVisible(false);
    };
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by adelekennedy** [comment] 2023-08-02 22:08
Trying to reproduce on chrome staging (v1.3.49-1) or prod (v1.3.48-5) and I'm not getting the same result - the ra context menu doesn't reappear. I think this may have been fixed. checking in Slack

**Comment by jfquevedol2198** [comment] 2023-08-02 22:23
@adelekennedy I can see this on ND
<img width="1271" alt="image" src="https://github.com/Expensify/App/assets/137529618/1d679033-6879-45da-af00-dc62be34ee13">

**Comment by adelekennedy** [comment] 2023-08-04 00:02
moving this forward!

**Comment by studentofcoding** [comment] 2023-08-04 05:54
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

ReportActionContextMenu not closing properly

## What is the root cause of that problem?
This `hideEmojiPicker` function not covering the case when what to do when being overlapped by Navigating, therefore this condition should be added.

https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/components/EmojiPicker/EmojiPicker.js#L66-L77

Lines 71 to 77 in [024d210](https://github.com/Expensify/App/commit/024d210bc0b5a0454b62a72de60057af67cdd045)

## What changes do you think we should make in order to solve the problem?
Need to check the status of onModulaHide.current and init that.
```
const hideEmojiPicker = (isNavigating) => {
        if (isNavigating) {
            if (onModalHide.current) onModalHide.current(); // This is the condition to handle the case
            onModalHide.current = () => {};
        }
        emojiPopoverAnchor.current = null;
        setIsEmojiPickerVisible(false);
    };
```

## What alternative solutions did you explore? (Optional)
N/A

## Result
https://www.loom.com/share/6f506f43b8e04c57ae5da5a979c1df2e?sid=034af9be-bf27-490c-81f6-4a19184fa3c1

**Comment by nileshahir286** [comment] 2023-08-04 06:08
Contributor details
Your Expensify account email: [nileshahir286@gmail.com](mailto:nileshahir286@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0126f3665fe23ff297

### **Proposal**
### **Please re-state the problem that we are trying to solve in this issue.**
Report Context Menu should be closed, now it's stuck after close the modal.

### **What is the root cause of that problem?**
Report Context Menu should only be show when hover on icon.

### **What changes do you think we should make in order to solve the problem?**
When you press CTRL+K, at that time the context menu should hide.

**Comment by nileshahir286** [comment] 2023-08-04 06:10
> ⚠️ Missing/invalid email or upwork profile link. Please make sure you add both your Expensify email and Upwork profile link in the format specified.

Already include Upwork profile as well as Expensify email id.

**Comment by adelekennedy** [comment] 2023-08-07 19:05
pending review on the updated proposal

**Comment by robertKozik** [comment] 2023-08-07 22:05
I'll review it as the first thing tomorrow 👌🏼

**Comment by robertKozik** [comment] 2023-08-08 11:29
Hi, thank you all for your proposals. I'll try to address them all:

1) @studentofcoding / @jfquevedol2198 - both of your proposals suggest triggering the `onModalHide` function before clearing it. I think it could cause lots of regression problems. Basically, this trigger renders the entire `if` statement irrelevant in my eyes.
https://github.com/Expensify/App/blob/012d604753e6ed2f97736d47b28486f813995165/src/components/EmojiPicker/EmojiPicker.js#L72-L74
2) @nileshahir286 - I think your proposal is too general to be taken under consideration.
3) @bernhardoj - I think your proposal is well-suited to be chosen. I really like the idea of passing the `isNavigating` state to decide on the behavior of `onHide` using the callback function. I believe it's the most flexible solution and can be future-proof. I agree with you that your second alternative solution would be the go-to, as it could allow us to eliminate the need for delaying focus. However, it appears that we might have to wait a considerable time until your PRs are merged upstream, and then the versions of these libraries would have to be updated within this repository as well. In my opinion, we should address this bug more promptly, but let's see what CME will think about it.

With that said, I believe we should choose the @bernhardoj proposal and push it forward.

Selected Proposal: [Proposal](https://github.com/Expensify/App/issues/23959#issuecomment-1659988961)
Author of proposal: @bernhardoj

**Comment by puneetlath** [comment] 2023-08-08 17:15
I like the idea of going with the ideal solution that includes the upstream fixes. This doesn't seem like such an urgent bug to me, so I'd rather take our time and go with the ideal approach.

**Comment by puneetlath** [comment] 2023-08-08 17:16
@robertKozik is there anyone from SWM that might be able to help us get some traction on the upstream PRs?

**Comment by robertKozik** [comment] 2023-08-11 07:45
@puneetlath shared on internal slack channel

**Comment by WoLewicki** [comment] 2023-08-11 15:05
Hey, I tested the changes and commented on the PR for `react-native`: https://github.com/facebook/react-native/pull/38336#discussion_r1291452892, hopefully we can move it forward 🚀

**Comment by robertKozik** [comment] 2023-08-21 14:21
@puneetlath Can we put this issue on hold as we are waiting for upstream PRs?

**Comment by puneetlath** [comment] 2023-08-21 15:01
Yes, absolutely. Which exact PRs are we putting this on hold for. Let's make sure we have a list so we know when to take this off hold.

**Comment by puneetlath** [comment] 2023-08-22 18:29
Thanks @bernhardoj. @adelekennedy can we please put this on hold for those?

**Comment by adelekennedy** [comment] 2023-09-21 10:48
no update

**Comment by puneetlath** [comment] 2023-10-04 14:48
Still on hold for upstream.

**Comment by adelekennedy** [comment] 2023-10-13 18:36
I think we're still on hold here

**Comment by adelekennedy** [comment] 2023-10-24 00:48
Still holding here!

**Comment by adelekennedy** [comment] 2023-11-09 18:38
woof - we're just holding on this still until they update the PR, should we downgrade this to monthly?

**Comment by shubham1206agra** [comment] 2023-11-20 15:22
@adelekennedy Should we go towards a workaround solution which @bernhardoj previously proposed?

**Comment by puneetlath** [comment] 2023-11-22 18:09
Can you remind me what the workaround is? We should evaluate whether the bug is bad enough to justify a workaround.

**Comment by robertKozik** [comment] 2023-11-23 10:59
I think we are talking about the `Alternative 1` from [there](https://github.com/Expensify/App/issues/23959#issuecomment-1659988961).

**Comment by robertKozik** [comment] 2023-11-23 14:21
I don't think that the bug is that bad to prove patch to be reasonable. In my eyes this bug requires very specific setup and is not that easy to reproduce frequently for normal users

**Comment by adelekennedy** [comment] 2023-12-04 16:35
@robertKozik @puneetlath any thoughts one the patch conversation?

**Comment by shubham1206agra** [comment] 2023-12-13 15:47
@puneetlath Can I get reporting bonus in that case?

**Comment by shubham1206agra** [comment] 2023-12-18 15:50
@puneetlath @robertKozik Since RNWeb version of this issue is already merged. So can we fix this issue for web platforms as a partial fix?

**Comment by bernhardoj** [comment] 2023-12-28 07:47
The new PR is in review.

**Comment by adelekennedy** [comment] 2024-01-05 20:54
New PR is in review, looks like it may take a bit more time

**Comment by adelekennedy** [comment] 2024-01-15 16:38
new pr was last reviewed 5 hours ago

**Comment by bernhardoj** [comment] 2024-01-17 03:33
The PR is merged. Now waiting for it to get into a new RN release.

**Comment by shubham1206agra** [comment] 2024-01-17 10:38
I will be taking over here as @robertKozik is no longer C+.
Slack https://expensify.slack.com/archives/C02NK2DQWUX/p1705449256141069

**Comment by shubham1206agra** [comment] 2024-01-17 10:39
@bernhardoj Would you work on this on draft PR as a headstart?

**Comment by bernhardoj** [comment] 2024-01-17 11:49
@shubham1206agra I think I will wait until all upstream PR is done. We still need to update `react-native-modal` too to use `onDismiss`.

**Comment by shubham1206agra** [comment] 2024-01-17 11:50
Do you have a upstream PR for that?

**Comment by bernhardoj** [comment] 2024-01-17 12:03
Not yet, we need the RN PR to be released first which probably happens in 0.74 because it contains a breaking change (the breaking change log was added by the RN reviewer).

<img width="493" alt="image" src="https://github.com/Expensify/App/assets/50919443/82fae5d0-4739-4e8f-a315-57ffc1ed7df6">

The [RN release discussion](https://github.com/reactwg/react-native-releases/discussions) doesn't contain the 0.74 yet, so it might take a while.

**Comment by bernhardoj** [comment] 2024-01-23 05:48
The PR was [reverted because of an internal issue](https://www.github.com/facebook/react-native/pull/42014#issuecomment-1903857964). The team will try to come up with a plan to split the PR into smaller chunks (and probably fewer changes).

**Comment by adelekennedy** [comment] 2024-01-31 18:50
still pending update [here](https://github.com/facebook/react-native/pull/42014#issuecomment-1903857964)

**Comment by adelekennedy** [comment] 2024-02-09 19:20
@bernhardoj @robertKozik just checking here - I see this PR is now closed but it looks like @bernhardoj you still are looking for updates, at this point are we just waiting for @cipolleschi to respond?

**Comment by bernhardoj** [comment] 2024-02-10 01:56
@adelekennedy correct, I will try to bump it next week if we don't get a reply

**Comment by bernhardoj** [comment] 2024-02-16 10:15
Bumped the PR

**Comment by bernhardoj** [comment] 2024-02-22 13:32
Hey guys, here is the latest update:

Just as a reminder, what we are trying to achieve is adding an `onDismiss` support for Android, and fixing `onDismiss` isn't firing on iOS (Fabric only).

Last month, the PR was merged but was reverted due to Meta's internal issues where they have some code that [expects the Android to not fire the `onDismiss` event](https://www.github.com/facebook/react-native/pull/42014#issuecomment-1903857964).

The reviewer then managed to land the fix for iOS (with minimal changes) based on the PR. What is left is the Android part.

The reviewer then suggest this:
> 1. We create a PR in the [discussion-and-proposal repo](https://github.com/react-native-community/discussions-and-proposals) and we get the buy in from various people, including internal people, to make this happens in Android.
> 2. While we wait for the above, you can create a component based on `<Modal>` with the fix. Something like `<EXPModal>` and include that component as a dependency of Expensify. Even better if, rather than copying and pasting the code, you manage to have a component that extends the native classes of Modal so that when we push some improvements, your component benefits from them too.

But it's not possible (it's actually possible but more complex) to create a custom native component that extends the react-native Modal and use it because we use `react-native-modal`. So, I ask the reviewer whether using a patch-package is a viable options or not and [he agrees with it](https://github.com/facebook/react-native/pull/42014#issuecomment-1954603433).

The question is, do we want to pursue that plan? The patch will include the Android files (3) changes from the upstream PR and removing some platform checks in [`react-native/Modal.js`](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Modal/Modal.js), so it works for all platforms.

Having this fixed allow us to also fix properly these other related issues (that is caused by delaying the input focus):
- https://github.com/Expensify/App/issues/19558
- https://github.com/Expensify/App/issues/29610 (the issue already has a PR that only delaying the input focus on native)
- https://github.com/Expensify/App/issues/36829 (this can also be solved with focus trap, the issue is closed waiting for the focus trap PR)

and we don't need to delay the input focus anymore when closing a modal.

@shubham1206agra @puneetlath

**Comment by adelekennedy** [comment] 2024-03-01 19:47
@bernhardoj did you post this in Slack? I might have missed it!

**Comment by bernhardoj** [comment] 2024-03-02 01:40
@adelekennedy oh sorry, I actually changed my mind and still drafting the react native proposal. I will let you know here once I publish the proposal. If there is no movement on the proposal for a while, then I will reconsider asking for a patch in Slack.

**Comment by bernhardoj** [comment] 2024-03-04 03:21
Published the react native proposal [here](https://www.github.com/react-native-community/discussions-and-proposals/pull/769)

**Comment by adelekennedy** [comment] 2024-03-13 22:37
@bernhardoj it looks like we're still paused here until the rn proposal gets traction is that correct?

**Comment by bernhardoj** [comment] 2024-03-14 02:38
@adelekennedy yes, correct.

**Comment by adelekennedy** [comment] 2024-05-28 16:38
we're still held on the react-native conversation, @bernhardoj it's been a month and no response there yet. What's the appropriate way to get them to respond to us?

**Comment by bernhardoj** [comment] 2024-05-29 06:53
@adelekennedy Hmm, I'm not sure what we should do to get their attention. I think they would get interested with it if the many of the community vote for it too, but as you can read from this [comment](https://github.com/react-native-community/discussions-and-proposals/pull/769#:~:text=as%20we%20already%20have%20apps%20out%20in%20the%20wild%20abusing%20this%20lack%20of%20implementation), they are aware that many apps out there already use some workaround with the modal issue. 

It's not a new issue btw (the lack of dismiss event on Android), it's been there I guess since the react native is built, so I doubt we will get an update sooner or later.

Going with a patch approach will make it hard to maintain since we need to patch the react-native and react-native-modal library and considering there are no attention to the react-native proposal and react-native-modal repo been inactive, we might need to maintain the patch forever.

IMO, the best path forward for now is to go with my main solution that is previously approved by @robertKozik
<img width="895" alt="image" src="https://github.com/Expensify/App/assets/50919443/938a6e95-f64b-48f8-bbc0-fb25f5c5b92b">

cc: @puneetlath @shubham1206agra

**Comment by puneetlath** [comment] 2024-05-30 22:22
Would you mind re-explaining that solution? I have forgotten all the context.

**Comment by bernhardoj** [comment] 2024-05-31 05:26
Sure. 

_Issue brief explanation_
The issue we have here is that if `isNavigating` is true, we "don't call" the `onModalHide`. `isNavigating` is currently set to true every time we close the modal using shortcut.
https://github.com/Expensify/App/blob/5699ae382505ed0d962e6170320a367e41e7858c/src/components/EmojiPicker/EmojiPicker.tsx#L109-L112

This is useful for a case like composer that will focus the input after the emoji picker is closed, but we don't want that to happen when we use a shortcut to navigate to the search page for example.
https://github.com/Expensify/App/blob/5699ae382505ed0d962e6170320a367e41e7858c/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L487

But this affects other components too that need the `onModalHide` to be called. (`onEmojiPickerClosed` is called in `onModalHide`)
https://github.com/Expensify/App/blob/5699ae382505ed0d962e6170320a367e41e7858c/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L146-L149

Solution
The solution is:
1. Always call the `onModalHide`.
2. Pass the `isNavigating` value to `onModalHide`
3. Let each component decide what to do with the `isNavigating` value, for example, composer won't call the focus function if `isNavigating` is true.
```
onModalHide={(isNavigating) => {
    if (isNavigating) return;
    this.focus(true);
}}
```

**Comment by bernhardoj** [comment] 2024-06-13 13:50
@puneetlath so, what do you think?

**Comment by mallenexpensify** [comment] 2024-06-19 01:09
@puneetlath 👀 above plz.

**Comment by puneetlath** [comment] 2024-07-01 21:38
Sorry for the delay. I re-added the External label in order to get a C+. @ishpaul777 what do you think of [the proposal](https://github.com/Expensify/App/issues/23959#issuecomment-2141255880)?

**Comment by puneetlath** [comment] 2024-07-02 13:55
Ah, my apologies.

**Comment by bernhardoj** [comment] 2024-07-04 15:12
@shubham1206agra Here is the test branch: https://github.com/bernhardoj/Expensify/tree/fix/23959-mini-context-menu-doesnt-close

There is an additional change needed, that is removing the freeze capture here. This causes the hover state to not update.
https://github.com/Expensify/App/blob/6ac95e4c7fdf555b7ba8c9365fb522305d239dc2/src/pages/home/report/ReportActionItem.tsx#L878-L879

It was added at https://github.com/Expensify/App/pull/41859. @waterim May I know what [bug is it with the report preview](https://github.com/Expensify/App/pull/41859#issuecomment-2118012926)? Is it that the message isn't highlighted while the payment option popover is shown?

Btw, looks like the price is reduced from the original when the external label is re-applied.

cc: @puneetlath

**Comment by bernhardoj** [comment] 2024-07-08 06:06
Waiting @waterim confirmation on https://github.com/Expensify/App/issues/23959#issuecomment-2209208181

**Comment by adelekennedy** [comment] 2024-07-11 01:35
bump on the above @waterim

**Comment by waterim** [comment] 2024-07-11 13:50
@bernhardoj sorry for a late answer, didnt get any notifications from this issue. 
Yes, the bug was with message, it was not highlighted while popover is open!

**Comment by bernhardoj** [comment] 2024-07-12 07:39
@waterim thanks for the confirmation!

Updated my [proposal](https://github.com/Expensify/App/issues/23959#issuecomment-1659988961) and test branch.

**Comment by puneetlath** [comment] 2024-07-15 13:19
@shubham1206agra what's next here?

**Comment by puneetlath** [comment] 2024-07-18 18:07
How's it going @shubham1206agra?

**Comment by mallenexpensify** [comment] 2024-07-22 17:24
Made @shubham1206agra the issue owner (unsure why they weren't already) 
👀 plz @shubham1206agra .  From [Vit last week](https://expensify.slack.com/archives/C02NK2DQWUX/p1721431105941059?thread_ts=1720776985.381979&cid=C02NK2DQWUX)
>  I can confirm that the first video is how its expected to work

[The first vid](https://expensify.slack.com/archives/C02NK2DQWUX/p1720777007091619?thread_ts=1720776985.381979&cid=C02NK2DQWUX) is `Before the PR`.  (not sure where that puts us here, just trying to help move this along. )

**Comment by bernhardoj** [comment] 2024-07-22 17:35
> [The first vid](https://expensify.slack.com/archives/C02NK2DQWUX/p1720777007091619?thread_ts=1720776985.381979&cid=C02NK2DQWUX) is Before the PR

I don't know what is this about, but is it about highlighting the action when the payment method popover is shown? If yes, is the decision to highlight or not? Asking for a confirmation

_I'll open the PR tomorrow_

**Comment by bernhardoj** [comment] 2024-07-23 04:11
PR is ready

@shubham1206agra bump on the above question so I can adjust the code if needed. Thanks!

**Comment by bernhardoj** [comment] 2024-08-01 02:22
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment] 2024-08-01 14:44
Oh no, I already ended the UW contract.

**Comment by adelekennedy** [comment] 2024-08-08 06:45
@bernhardoj I sent you a new offer: https://www.upwork.com/nx/enterprise-homepage/?offerRid=103444727&nav_dir=replace&teamUid=all_teams&tab=hire

**Comment by adelekennedy** [comment] 2024-08-08 06:47
@shubham1206agra I also had to send you a new offer (I ended the $250 automatic offer without adding the additional 1k)

**Comment by bernhardoj** [comment] 2024-08-08 07:18
@adelekennedy accepted the new offer

**Comment by adelekennedy** [comment] 2024-08-08 20:25
Payments made!

**Closed by adelekennedy** 2024-08-08 20:25 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
