### ISSUE TITLE
[$250] Clicking on any of the unapproved expenses shows the most recent one or wrong one

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41676] opened 2024-05-06 14:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714906349634039

## Action Performed:
1. Scan few receipts as employee
2. Click on one of the unapproved expense
## Expected Result:
Should open the expense clicked
## Actual Result:
Opening wrong or the most recent one
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/73013392-5641-4eea-90e1-44c55276c506

https://github.com/Expensify/App/assets/38435837/9706b5ce-5d46-4e87-86ba-a8ad641d67ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01118e9e4dba07131b</li>
        <li>Upwork Job ID: 1787719675315605504</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by GoodWork0903** [comment] 2024-05-07 08:50
Hello, How are you?
I am from Upwork
As I see, It is simple bug.
I will fix it for 3 hours.
Thank you for your attention.
Best regards

**Comment by GoodWork0903** [comment] 2024-05-07 08:54
Contributor details
My Expensify account email : solomon21century@outlook.com
Upwork Profile : https://www.upwork.com/freelancers/~01a27ebc4cfff91f79
Thank you for your attention.

**Comment by GoodWork0903** [comment] 2024-05-07 09:15
Should I send proposal in Upwrok?

**Comment by kadiealexander** [comment] 2024-05-14 02:40
@GoodWork0903 please post your proposal here using [the proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) as per our [contributing guidelines.](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by kadiealexander** [comment] 2024-05-14 02:43
@GoodWork0903 please post your proposal here using [the proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) as per our [contributing guidelines.](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by GoodWork0903** [comment] 2024-05-14 05:46
Your issue is very simple.
I am confident in my ability to fix this issue perfectly.

Your issue seems like react-router issue.
you can see it 
![Errorpng](https://github.com/Expensify/App/assets/156428677/ea0a1f7c-4c2e-46e5-98f2-52a647b9355d)
![Errorpng](https://github.com/Expensify/App/assets/156428677/01b166fa-55d7-4419-897f-539865a6a623)

Please let me know your thoughts

**Comment by kadiealexander** [comment] 2024-05-14 06:28
@GoodWork0903 please use the template I linked to submit your proposal. Thanks!

**Comment by GoodWork0903** [comment] 2024-05-14 06:55
Proposal
Please re-state the problem that we are trying to solve in this issue.

You are trying to like this.
When you click second image, It has to redirect second image, not first image.

What is the root cause of that problem?

I think that the problem is router and router navigation.

What changes do you think we should make in order to solve the problem?

First, I have to review how to get that url and I have to change react navigation function.


![Uploading Errorpng.png…]()

**Comment by kadiealexander** [comment] 2024-05-17 05:03
Still seeking proposals! 🎉

**Comment by rojiphil** [comment] 2024-05-20 18:26
Awaiting proposals

**Comment by mvtglobally** [comment] 2024-05-22 04:33
Issue not reproducible during KI retests. (First week)

**Comment by kadiealexander** [comment] 2024-05-22 04:39
Asked @jliexpensify if it's reproducible for him [here](https://expensify.slack.com/archives/C049HHMV9SM/p1716352775668729?thread_ts=1714906349.634039&cid=C049HHMV9SM).

**Comment by kadiealexander** [comment] 2024-05-22 04:41
Closing as not reproducible!

**Closed by kadiealexander** 2024-05-22 04:41 UTC
Labels: External, Daily, Help Wanted, Bug
