### ISSUE TITLE
Report fields - Wrong message is displayed on report fields confirmation modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45696] opened 2024-07-18 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N /A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Report fields should be enabled and there should be no created report fields
1. Navigate to workspace settings page
2. Click on More features > try to disable Report fields

## Expected Result:
'Text and date fields will be deleted, and lists will be disabled.' message shouldn't be displayed on confirmation modal since user didn't create any report fields

## Actual Result:
'Text and date fields will be deleted, and lists will be disabled.' message is displayed on confirmation modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/15394755-2805-4f3e-9922-bd76621d278e

<img width="377" alt="image" src="https://github.com/user-attachments/assets/378b2be7-4b24-474f-948d-e4af290ec39e">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-18 16:24
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-07-18 17:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong message is displayed on report fields confirmation modal
### What is the root cause of that problem?
We are not checking if any report field is added before displaying the modal here
https://github.com/Expensify/App/blob/2e2c2bf31c6076a48ac4f01742775eb6e1222e4c/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L218
### What changes do you think we should make in order to solve the problem?
* Check if any report field is added to the policy 
```javascript

                const {text_title, ...reportFields} = policy?.fieldList ?? {};
                const areReportFieldsEmpty = isEmpty(reportFields);
````
* Disable reportFields feature and return before `setIsReportFieldsWarningModalOpen(true);` if `areReportFieldsEmpty === true`
```Javascrip
if (areReportFieldsEmpty) {
                    Policy.enablePolicyReportFields(policyID, false);
                    return;
                }
                setIsReportFieldsWarningModalOpen(true);
 ```

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-07-19 17:24
I can reproduce but I don't know if this is a a bug or a New Feature. 

I _think_ currently in product we show these warning popups even if nothing is going to be affected by disabling the feature (for example, they haven't used Report Fields but we still tell them what will be disabled when they disable report fields)

I'll reach out to the team to see if this is a bug or a feature request.

**Comment by Christinadobrzyn** [comment] 2024-07-19 17:35
Asking in wave-collect if we want to disable this message as I think it's a new feature and getting thoughts from the design team

https://expensify.slack.com/archives/C036QM0SLJK/p1721410229671169

**Comment by Christinadobrzyn** [comment] 2024-07-19 19:40
This is part of Wave-control but we don't have a tag for that wave yet. 

Also, sounds like this is behaving as expected - closing. Feel free to bring this to a team as a feature request if you'd like!

**Closed by Christinadobrzyn** 2024-07-19 19:40 UTC
Labels: Daily, Bug
