### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500]  Chat - The HTML code of the avatar is copied when copying the login name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29921] opened 2023-10-18 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with HT account
3. Navigate to any conversation with the user
4. Copy the login in the title of the conversation by highlighting the text from right to left and moving the mouse cursor over the avatar a little.
5. Paste the copied login into the login box on the main login page, you can go incognito.

Steps 2:
1. Open https://staging.new.expensify.com/
2. Log in with HT account
3. Navigate to the conversation with the user with whom you have correspondence history
4. Click the login in the conversation header
5. Triple-click the email address in the Email field in RHP.
6. Copy the highlighted text
7. Paste the text into the Compose Box

## Expected Result:
When copying an account login through the conversation header, the avatar HTML code should not be copied to the buffer

## Actual Result:
When copying the account login through the conversation header, the HTML code of the avatar is placed in the buffer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/02296432-f2c2-48d4-9c5c-c46ab86a05d9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbaee99371cf5444</li>
        <li>Upwork Job ID: 1714763515875631104</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by ashuvssut** [comment] 2023-10-18 23:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 

### Root cause 
Here's a **Video with voiceover** explaining the Root cause
> Please unmute the audio in the following video

https://github.com/Expensify/App/assets/60546840/72195ec2-3790-4c31-8c48-9d2cbabc7806


 
 
 
This issue is caused when 

### My solution that fixes this issue:-

**Comment by ashuvssut** [comment] 2023-10-19 07:09
Along with this current issue, the following issues could be fixed by using @bernhardoj 's [solution](https://github.com/Expensify/App/issues/24399#issuecomment-1674374807):-

https://github.com/Expensify/App/issues/24399

https://github.com/Expensify/App/issues/27723

https://github.com/Expensify/App/issues/29793


We just need to add these 3 lines in SelectionScraper/index.js
```
const replaceNodes = (dom, isChildOfEditorElement) => {
    let domName = dom.name;
    let domChildren;
    const domAttribs = {};
    let data;

+   if (dom.type === 'style') {
+      return {};
+   }
```

**Comment by shamerKill** [comment] 2023-10-20 05:47
You can use the `shadow` tag in HTML to block it.
Determine whether to enable `shadow` tags on the web client.

https://github.com/Expensify/App/assets/25978360/372674f6-657c-4109-8436-31e309f9e84d

**Comment by shamerKill** [comment] 2023-10-20 05:52
Contributor details
Your Expensify account email: konglinlin9@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01862f4789afd10ee6

**Comment by shamerKill** [comment] 2023-10-20 06:30
Isn't it the simplest way to create tags only for browsers by judging the platform.

**Comment by shamerKill** [comment] 2023-10-20 06:30
> Interesting. why are we enforcing HTML selection for these elements?

Isn't it the simplest way to create tags only for browsers by judging the platform.

**Comment by shamerKill** [comment] 2023-10-20 06:39
```
import React from 'react';
import {Platform} from 'react-native';

function Shadow (props) {
    const isWeb = Platform.OS === 'web';
    if (isWeb) {
        return <shadow>{props.children}</shadow>
    } else {
        return props.children;
    }
}

export default Shadow;
```

**Comment by shamerKill** [comment] 2023-10-20 07:09
> > Interesting. why are we enforcing HTML selection for these elements?
> 
> Isn't it the simplest way to create tags only for browsers by judging the platform.

We just need to wrap it up.

``` javascript
import React from 'react';
import {Platform} from 'react-native';

function Shadow (props) {
    const isWeb = Platform.OS === 'web';
    if (isWeb) {
        return <shadow>{props.children}</shadow>
    } else {
        return props.children;
    }
}

export default Shadow;
```

**Comment by johnmlee101** [comment] 2023-10-26 19:52
Looks good!

**Comment by bfitzexpensify** [comment] 2023-11-09 18:22
Payment summary: 

Contributor: @bernhardoj to be paid $500 via Upwork
C+: @parasharrajat to be paid $500 via manual request

**Closed** 2023-11-13 17:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
