### ISSUE TITLE
[HOLD for payment 2024-10-04][PAY][$250] Empty space below the "Next" button when we open the page, and the button does not keep its position above the keyboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48468] opened 2024-09-03 12:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725318514200989

## Action Performed:

1. Open the app and log in
2. Navigate to settings > Switch to Expensify Classic
3. Select any reason and proceed to the next screen

## Expected Result:
The next button should be correctly positioned above the keyboard
## Actual Result:
Empty space below the "Next" button when we open the page, and the button does not keep its position above the keyboard
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/fec90ee3-b08c-4ca2-94a7-6093befc7eee

https://github.com/user-attachments/assets/a981f569-e099-46a4-90b5-1cd26a0eb507

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832067388388096796</li>
        <li>Upwork Job ID: 1832067388388096796</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103992082</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by FitseTLT** [comment] 2024-09-03 13:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Empty space below the "Next" button when we open the page, and the button does not keep its position above the keyboard

### What is the root cause of that problem?
Haven't set shouldEnableMaxHeight here
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L100
### What changes do you think we should make in order to solve the problem?

enable max height
```
            shouldEnableMaxHeight

```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-09-03 13:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are lot of empty spaces below the button in exit survey response page.

### What is the root cause of that problem?
When the keyboard is shown, we don't resize the page height. We have a `shouldEnableMaxHeight` prop to do it, but we aren't using it for the exit survey page.
https://github.com/Expensify/App/blob/5db0996d52d9c59a8570538a4601dffbca70395c/src/components/ScreenWrapper.tsx#L155

https://github.com/Expensify/App/blob/5db0996d52d9c59a8570538a4601dffbca70395c/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L121-L122

### What changes do you think we should make in order to solve the problem?

Enable the max height by passing the `shouldEnableMaxHeight` prop to the page ScreenWrapper.
https://github.com/Expensify/App/blob/5db0996d52d9c59a8570538a4601dffbca70395c/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L121-L122

We can apply the same solution to any page that has the same issue.

**Comment by suneox** [comment] 2024-09-03 17:05
This issue seems related to the virtual viewport on mWeb, which I resolved several months ago.

**Comment by DylanDylann** [comment] 2024-09-10 01:33
On my list today

**Comment by DylanDylann** [comment] 2024-09-10 04:58
@bernhardoj Is there any difference between your proposal and @FitseTLT's proposal?

**Comment by DylanDylann** [comment] 2024-09-10 04:59
@FitseTLT 
> We can also make same fixes in other exit survey page (or other pages) with the same problem
 
@bernhardoj 
> We can apply the same solution to any page that has the same issue.

 
Which page has the same issue?

**Comment by DylanDylann** [comment] 2024-09-10 05:01
@FitseTLT Please follow the rule

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/contributingGuides/CONTRIBUTING.md?plain=1#L103-L110

**Comment by FitseTLT** [comment] 2024-09-10 09:38
> @FitseTLT Please follow the rule
> 
> https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/contributingGuides/CONTRIBUTING.md?plain=1#L103-L110

@DylanDylann I only made a minor change and a minor note to check for similar problems and fix in PR phase that's why I didn't notify for update

**Comment by bernhardoj** [comment] 2024-09-10 14:52
> @bernhardoj Is there any difference between your proposal and @FitseTLT's proposal?

None, proposals are posted almost at the same time (1ms difference)
https://api.github.com/repos/Expensify/App/issues/comments/2326480424
https://api.github.com/repos/Expensify/App/issues/comments/2326480465

> Which page has the same issue?

I write this in case there is other cases found when working on the PR, but I just found that it happens in the console page too.

> We can apply the same solution to any page that has the same issue.


https://github.com/user-attachments/assets/005a9a48-18bf-424e-a270-8cc326b70b14

**Comment by FitseTLT** [comment] 2024-09-10 15:19
>@FitseTLT

>We can also make same fixes in other exit survey page (or other pages) with the same problem

@DylanDylann I just wrote this to indicate we can fix similar problems in other pages in PR phase, for instance, with a short researching I found similar problem in Report Participants page but we will find more cases in PR phase 


https://github.com/user-attachments/assets/740b15a2-6ec3-4390-ba89-83f092921c4a

I have proposed the same solution first @DylanDylann there is no reason to select the second proposal.

@roryabraham please consider reviewing the decision above I have stated the same solution first and equally indicated more cases to be dealt with (as ReportParticipantsPage) but the reviewer is chosing the second proposal. Thx

**Comment by kevinksullivan** [comment] 2024-09-11 21:31
Waiting on the internal stamp of approval. I am going OOO so I'm looping in another member of BZ

**Comment by roryabraham** [comment] 2024-09-13 06:06
thanks everyone, just seeing this but it's late for me. I'll review tomorrow

**Comment by FitseTLT** [comment] 2024-09-13 12:27
> I don't see the same problem in Report Participants page as you mentioned

@DylanDylann  The problem occurs when there is a text input in the page and to achieve that you need to have > 8 participants as indicated in my video.

**Comment by roryabraham** [comment] 2024-09-16 21:37
I agree with @DylanDylann's evaluation (though, none of the proposals really explain the root cause, only that it's a known thing and we have a prop to fix it. Both RCAs are just repeating the solution).

**Comment by DylanDylann** [comment] 2024-09-18 07:06
Waiting for PR

**Comment by puneetlath** [comment] 2024-09-18 15:20
@bernhardoj do you have an ETA?

**Comment by bernhardoj** [comment] 2024-09-18 15:55
Sorry, I was sick. PR is now ready

cc: @DylanDylann

**Comment by roryabraham** [comment] 2024-10-04 23:51
PR was deployed to prod `2024-09-27`, so it's ready to pay.

**Comment by puneetlath** [comment] 2024-10-06 13:43
@DylanDylann can you complete the checklist?

**Comment by DylanDylann** [comment] 2024-10-06 16:41
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Open Settings > Switch to Expensify Classic
2. Select any reason and proceed to the next screen
3. Focus on the input field and verify the button is positioned above the keyboard
4. Now, open Settings > Troubleshoot
5. Enable Client side logging
6. Press View debug console
7. Focus on the input field and verify the button is positioned above the keyboard


Do we agree 👍 or 👎

**Comment by puneetlath** [comment] 2024-10-06 19:33
Great, thanks. 

Payment summary: 
- C - $250 - @bernhardoj - to be paid via NewDot
- C+ - 250 - @DylanDylann - paid via Upwork

Thanks everyone!

**Closed by puneetlath** 2024-10-06 19:33 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-10-07 04:28
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-10-07 07:17
$250 approved for @bernhardoj
