### ISSUE TITLE
[HOLD for payment 2023-11-01] [$125] Save the world -  Thank you for referring your friend whisper message can be flagged

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26696] opened 2023-09-04 17:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot click on + icon and select save world
2. Select i know a teacher and fill the fields and click lets do this
3. Once taken to the teachers unite room observe that a whisper message from concierge with a thank you... Note is sent
4. Long press the message and observe there is a flag as offensive option is present

## Expected Result:
Flag as offensive should not be shown for whisper messages

## Actual Result:
Flag as offensive option is there

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/afdc3be2-5028-4782-84ae-bb599cd25938

https://github.com/Expensify/App/assets/93399543/9e76eabd-026f-435a-9a21-e6cd6c1db10b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693459768004849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01849355c1ec953b4e</li>
        <li>Upwork Job ID: 1699126418995933184</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by StevenKKC** [comment] 2023-09-04 17:47
## Proposal

### Please state again the problem we are trying to solve in this issue.
Save the world - Thank you for referring your friend whisper message can be flagged.

### What is the cause of this issue?
We are checking whether report action can be flagged as below.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/pages/home/report/ContextMenu/ContextMenuActions.js#L365-L371
"Thank you for referring your friend whisper message ..." report action has `8340048` `actorAccountID`, and `8340048` is `Expensify.org Admin`.
![Screenshot 2023-09-04 133948](https://github.com/Expensify/App/assets/131836113/52244418-d645-414f-ad15-247409e77e6d)
![Screenshot 2023-09-04 133906](https://github.com/Expensify/App/assets/131836113/8b113a91-690d-434f-910f-6e393a4c6fdd)

But we are not checking this `actorAccountID`.

### What changes do you think we should make to solve the problem?
We should add checking report action's `actorAccountID` is same with `8340048`.
```js
    (reportAction.actorAccountID !== CONST.ACCOUNT_ID.CONCIERGE && reportAction.actorAccountID !== 8340048)
```
I think we can define `CONST.ACCOUNT_ID.ADMIN` as `8340048`.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/CONST.ts#L889
### What alternative solutions have you investigated? (Optional)
None.

**Comment by sakluger** [comment] 2023-09-05 18:24
I tested and found that other Concierge whisper messages (and Concierge messages in general) do not have this option.

**Comment by youssef-lr** [comment] 2023-09-21 07:01
I will get to this tomorrow.

**Comment by youssef-lr** [comment] 2023-09-26 09:36
Haven't managed to get to this yet, I will have time for it this week.

**Comment by youssef-lr** [comment] 2023-09-28 12:36
@pecanoro @marcochavezf I remember there was a discussion about this issue on Slack but I can't find it. What was the outcome of the discussion generally when it comes to flagging whispers?

**Comment by youssef-lr** [comment] 2023-10-19 15:57
Am I missing something here or is this as simple as checking if the report action is a whisper then don't allow it to be flagged? All whispers come from "us" so I can't imaging a scenario where a whisper would be flagged?

**Comment by SofoniasN** [comment] 2023-11-03 04:38
@youssef-lr  slight bump

**Comment by pecanoro** [comment] 2023-11-03 14:26
I have no idea why Stef unassigned the BugZero person in this issue haha Reassigning @sakluger so it can be paid since he was the [original](https://github.com/Expensify/App/issues/26696#issuecomment-1707107628) BZ member in the issue.

**Comment by SofoniasN** [comment] 2023-11-03 17:45
@sakluger No need to assign me, just bumping for a payment!

**Comment by sakluger** [comment] 2023-11-03 17:46
Sometimes when you assign one person and change labels, it screws with the other assignments, that's probably what happened here. Thanks @pecanoro for reassigning me.

@SofoniasN I mistakenly thought you were the contributor, then realized you were the reporter and unassigned you. Sorry for the mixup! I'm recreating an Upwork job now since the old one expired.

**Comment by SofoniasN** [comment] 2023-11-03 17:51
@sakluger now worries!

**Comment by sakluger** [comment] 2023-11-03 17:55
@SofoniasN I sent you an offer on job https://www.upwork.com/jobs/~015d6b047a6e4d4953. It's for $250 because that was the reporting rate when you reported it back on Aug 30. Please let me know once you've accepted.

**Comment by SofoniasN** [comment] 2023-11-03 18:00
@sakluger offer accepted, Thank you.

**Comment by sakluger** [comment] 2023-11-03 18:13
Paid, thanks!

**Closed by sakluger** 2023-11-03 18:13 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
