### ISSUE TITLE
[$250] On using arrow keys, Both emoji picker and Chat history is scrolling simultaneously - reported by @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9413] opened 2022-06-13 04:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Desktop Website
2. Go to Chat > Send a Message > Edit Message
3. Open Emoji picker in edit message, then press Down and Up key on keyboard.

## Expected Result:
It should only scroll the emoji picker.

## Actual Result:
Both emoji picker and Chat history is scrolling simultaneously.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.75-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/173279915-a601ec39-f3df-4100-b87e-3f2677753df8.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1653420332180529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2022-06-14 15:20
I can replicate in web app 👍

**Comment by JosueEchandiaAsto** [comment] 2022-06-15 17:15
### Proposal

### Issue
Both emoji picker and Chat history is scrolling simultaneously.

### Fix
When keyBoardEvent in EmojiPickerMenu capture a 'Arrow' event in needed a `preventDefault();`

https://github.com/JosueEchandiaAsto/App/blob/e98cf8e67fbfaa53e1e523f8503700b57412a158/src/components/EmojiPicker/EmojiPickerMenu/index.js#L136-L143

Commit: https://github.com/Expensify/App/compare/main...JosueEchandiaAsto:Fix-Issue-9413

### Result
https://user-images.githubusercontent.com/16966456/173886713-a766cd81-81e8-4f27-b804-49bff932d375.mov

**Comment by rushatgabhane** [comment] 2022-06-16 00:56
@luacmartins I like @JosueEchandiaAsto's [proposal](https://github.com/Expensify/App/issues/9413#issuecomment-1156732163). Cause is explained and I can't think of anything that can go wrong.

🎀 👀 🎀 C+ reviewed

**Comment by luacmartins** [comment] 2022-06-16 13:08
Agreed! @JosueEchandiaAsto your proposal looks good!

**Comment by arielgreen** [comment] 2022-06-16 18:18
Great, @JosueEchandiaAsto @rushatgabhane @Tushu17 please check your Upwork notifications

**Comment by rushatgabhane** [comment] 2022-07-18 20:11
@arielgreen let's close this out

**Comment by neil-marcellini** [comment] 2022-08-04 22:20
This has caused a regression https://github.com/Expensify/App/issues/10182

**Comment by Tushu17** [comment] 2022-09-06 11:24
@arielgreen Payment is still pending on this issue.

**Comment by Tushu17** [comment] 2022-09-13 16:57
>  Payment is still pending on this issue.

bump @luacmartins @arielgreen

**Comment by luacmartins** [comment] 2022-09-14 14:30
@Tushu17 thanks for the bump! @arielgreen seems to be ooo, so I'll reassign this issue so we can process the payment asap.

**Comment by luacmartins** [comment] 2022-09-14 14:31
@trjExpensify could you please pay the reporting bonus to @Tushu17? Thank you!

**Comment by trjExpensify** [comment] 2022-09-14 17:49
Hm, I think @arielgreen is around today actually. Why doesn't the issue have the payment date in the title? 🤔

**Comment by arielgreen** [comment] 2022-09-14 20:28
Paid!

@rushatgabhane @JosueEchandiaAsto @Tushu17 I also added a bonus for the inconvenience of the late payment. Apologies for the delay in payment here!

@luacmartins let's be sure we're not closing issues till all payments have been completed.

**Closed by arielgreen** 2022-09-14 20:28 UTC
Labels: Reviewing, Exported, External, Engineering, Daily

**Comment by luacmartins** [comment] 2022-09-14 21:04
>@luacmartins let's be sure we're not closing issues till all payments have been completed.

Oops my bad! I'll make sure this is done next time!
