### ISSUE TITLE
[$1000] Misleading right-click on email linked to URL

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18912] opened 2023-05-14 12:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send an email linked to a URL (e.g. [[test@google.com](mailto:test@google.com)]([google.com](http://google.com/)) )
3. Right click on the message

## Expected Result : 
Since the message is an email with a link, the message should be "Copy URL to Clipboard", and after selecting the menu, the URL is copied
## Actual Result : 
The message is "Copy Email to Clipboard", but after selecting the menu, the URL is copied - this is confusing for the user.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0ba0d283-e1cd-46c6-bc99-dad5f2b92792

https://github.com/Expensify/App/assets/43996225/4869975f-5981-460b-aa4e-a1d5e3bbc91e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684029611911239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185cc75d081384f04</li>
        <li>Upwork Job ID: 1657974195145203712</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-05-14 17:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Right-click menu on email linked to URL shows `Copy email to clipboard`.

### What is the root cause of that problem?

The root cause of this issue is that we determine the type of context menu by `props.displayName` of `BaseAnchorForCommentsOnly` here

https://github.com/allroundexperts/Expensify/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L53

and `props.displayName` is the text of anchor tag see here

https://github.com/allroundexperts/Expensify/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L24

which is buggy because 

1. A normal link can also has an email address as the text, like `[test@gmail.com](https://google.com)`
2. An email can also has normal text as the text, like `[this is an email](test@gmail.com)`

A markdown link

```
[test@gmail.com](https://google.com)
```

is rendered as anchor tag

```html
<a href="https://google.com" dir="auto" rel="noreferrer noopener" target="_blank" role="link" class="css-text-1rynq56" data-testid="a" style="color: rgb(90, 176, 255); font-size: 15px; text-align: left; font-family: ExpensifyNeue-Regular, &quot;Segoe UI Emoji&quot;, &quot;Noto Color Emoji&quot;; line-height: 20px; text-decoration-line: underline; text-decoration-color: rgb(90, 176, 255); user-select: text;">test@gmail.com</a>
```

So, the value of `props.displayName` for `BaseAnchorForCommentsOnly` is `test@gmail.com` and method `Str.isValidEmailMarkdown` returns true here

https://github.com/allroundexperts/Expensify/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L53

That's why right-click menu on email linked to URL shows `Copy email to clipboard`.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can check if the `href` property of anchor tag is started with `mailto:` to determine it's an email address. Note that we format anchor tag for email in ExpensiMark.js, see [here](https://github.com/Expensify/expensify-common/blob/e7e765d47eeafbeac588bbf88044d91bf680437d/lib/ExpensiMark.js#L98) and [here](https://github.com/Expensify/expensify-common/blob/e7e765d47eeafbeac588bbf88044d91bf680437d/lib/ExpensiMark.js#L139).

We improve the checking condition here 

https://github.com/allroundexperts/Expensify/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L53

to

```js
props.href.startsWith('mailto:') ? ContextMenuActions.CONTEXT_MENU_TYPES.EMAIL : ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
```

Below are useful test cases to verify the solution

```
[test@gmail.com](https://google.com)
```

```
[this is an email](test@gmail.com)
```

```
[test@gmail.com](https://test.com/mailto:)
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by jliexpensify** [comment] 2023-05-15 01:13
This isn't typical behaviour I've seen, so asking here: https://expensify.slack.com/archives/C049HHMV9SM/p1684113182168159?thread_ts=1684029611.911239&cid=C049HHMV9SM

**Comment by gabrialva** [comment] 2023-05-15 10:46
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Right-click menu on email linked to URL shows Copy email to clipboard.

**What is the root cause of that problem?**
The root cause of this issue is that the markup-check module in App/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js

![image](https://github.com/Expensify/App/assets/132295224/6fe9b751-1420-4140-9014-d818bd6808e4)

isValidEmailMarkdown function of node_modules/expensify-common/str.js was not written against all possible use cases.
![image](https://github.com/Expensify/App/assets/132295224/2cc25a45-5480-4393-8687-42381d7e4506)

This common function checks only if the props.displayName is either Email or Hyperlink, so needs to be improved so that it will display Copy URL to clipboard for email with hyperlinks messages.

What changes do you think we should make in order to solve the problem?
To fix this issue, we can give a minor tweak to the current code like this.

![image](https://github.com/Expensify/App/assets/132295224/eb303abc-e7ea-4cec-bb1d-eda67cd46e0e)

What alternative solutions did you explore? (Optional)
We can show two options like Copy URL to clipboard and Copy Email to clipboard at the same time when right-clicking.

**Comment by jasperhuangg** [comment] 2023-05-15 21:10
@fedirjh Have you had a chance to review these proposals? I like @allroundexperts proposal, but want a second opinion.

**Comment by eh2077** [comment] 2023-05-16 06:06
@fedirjh I think @allroundexperts 's proposal is not perfect enough to address test case like
```
[test@gmail.com](https://test.com/mailto:)
```
Can I have your feedback about my [proposal](https://github.com/Expensify/App/issues/18912#issuecomment-1546959257)?

**Comment by dukenv0307** [comment] 2023-05-16 07:27
@fedirjh @jasperhuangg  I believe there're multiple cases that the selected proposal will fail at:
1. `[test@gmail.com](https://test.com/mailto:)`
2. `[test@gmail.com](anotherEmail@gmail.com)` 
(In both cases it will show "Copy email" here while the correct one to show is "Copy link")

Also I think the proposals are not the same solutions, I'd appreciate a more thorough reviews here. I believe for small issues, the completeness of the proposal matters.

**Comment by DanutGavrus** [comment] 2023-05-16 13:22
@fedirjh Changes described [here](https://github.com/Expensify/App/issues/18912#issuecomment-1547750001) are different from detecting if href is a mail link, but provide a different fix than what was originally requested. I was also thinking of the option to let the user see "Copy email" and actually copy the email as the link may easily be pressed and opened, while the email has to be manually copied, but this is also a different fix.  

If you want to go with checking if href is a mail link, you may go with the one you intend, just making sure you saw these options.

**Comment by dukenv0307** [comment] 2023-05-17 03:07
> I see that all proposals have the same concept which is detect if the href is a mail link

@fedirjh hi just checking, did you see the alternative solution in [here](https://github.com/Expensify/App/issues/18912#issuecomment-1547654876)?, it detects the href is a mail link **and** also the href must match the `displayName` to make sure it's the `auto-email`. I'm not sure why it's considered the same since detecting mail link is only one part of it.

**Comment by dukenv0307** [comment] 2023-05-17 03:39
@fedirjh hmm just to confirm with you.

Currently
```
[test](email@gmail.com)
[test@gmail.com](email@gmail.com)
```
will currently both render as links, not as is, we're accepting emails in the href part of the `link`. You're saying that's not correct and they should instead be rendered as is, with emails becoming auto-emails right?

I'm not sure if it's expected that way since what we're doing is consistent with how Github does it.

**Comment by dukenv0307** [comment] 2023-05-17 08:38
@fedirjh I think it's not a bug, it's intentional, there's even test cases to cover it in `expensify-common`, see here https://github.com/Expensify/expensify-common/blob/879df466155918ec0e0a6b36176af4211302b184/__tests__/ExpensiMark-HTML-test.js#L483

Unless we have made a change of mind somewhere along the way.

**Comment by dukenv0307** [comment] 2023-05-18 02:44
> @fedirjh hi just checking, did you see the alternative solution in https://github.com/Expensify/App/issues/18912#issuecomment-1547654876?, it detects the href is a mail link and also the href must match the displayName to make sure it's the auto-email. I'm not sure why it's considered the same since detecting mail link is only one part of it.

@fedirjh Given that it's a not a separate bug, do you think my proposal actually fixes the issue in a broader scope, rather than being the same as the selected proposal?

**Comment by eh2077** [comment] 2023-05-18 03:00
@fedirjh If you're going to conduct another round of reviewing proposals, I really hope you would review @dukenv0307 's proposal and my [proposal](https://github.com/Expensify/App/issues/18912#issuecomment-1546959257) together because there's only a slight difference between them. The only difference is that I think email link like
```
Please [email us](concierge@expensify.com) if you have any questions
```
should show `Copy email to clipboard` as well.

@dukenv0307 Thank you for the great discussion above!

**Comment by dukenv0307** [comment] 2023-05-18 06:12
> We also shouldn't assume all anchors that starts with `mailto:` as emails, because if we add an email using `link` markdown like `[email](test@gmail.com)`, it is still a link, not an email (as confirmed [here](https://github.com/Expensify/App/issues/15620#issuecomment-1472289500)) and when copying, the user will copy the `mailto:...` link signature.

@fedirjh @eh2077 I've mentioned it in my proposal already. In @eh2077 's scenario 
```
Please [email us](concierge@expensify.com) if you have any questions
```
It should show as `Copy URL to Clipboard`, not as @eh2077 suggested. That case has been discussed before in [here](https://github.com/Expensify/App/issues/15620#issuecomment-1472289500) and that was the agreement.

**Comment by eh2077** [comment] 2023-05-18 10:36
@fedirjh @dukenv0307 
As we pass property `href` to format the value to save in clipboard, see here
https://github.com/Expensify/App/blob/a5c47370e4367f652e3e0ccc4568e212abcd88f3/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L52-L57
 and here
https://github.com/Expensify/App/blob/a5c47370e4367f652e3e0ccc4568e212abcd88f3/src/pages/home/report/ContextMenu/ContextMenuActions.js#L142-L148
, so we actually don't need to care much about what the text part looks like. IMO, what we need to fix here is to make right-click message prompt what's exactly to copy, email or url.

So, as long as an anchor tag is linked to an email address, the right-click message should show `Copy email to clipboard`. For example following anchor tags(after rendering)
```
Please [email us](concierge@expensify.com) if you have any questions
[test@gmail.com](anotherEmail@gmail.com)
```
Both should show message `Copy email to clipboard`.

See demo video 


https://github.com/Expensify/App/assets/117511920/90636407-b114-4fcb-bd0e-154d8cebaf57


I think we can also let the product team to decide what the expected behaviour should be.

**Comment by dukenv0307** [comment] 2023-05-18 10:41
@eh2077 it was discussed before [here](https://github.com/Expensify/App/issues/15620#issuecomment-1472289500) already and it was agreed that in such case it will copy link, not email. If you'd like another round of discussion I'd suggest to make a feature request on Slack.

**Comment by jasperhuangg** [comment] 2023-05-25 01:30
Apologies, missed this. I agree we should go with that proposal, assigning!

**Comment by jliexpensify** [comment] 2023-05-26 04:23
Everyone's been hired

**Comment by jliexpensify** [comment] 2023-06-07 22:18
Paying today. PR merged after 5 days, so no bonus.

**Comment by jliexpensify** [comment] 2023-06-07 22:40
Everyone has been paid. @fedirjh and @allroundexperts - could you complete the checklist please?

**Comment by eh2077** [comment] 2023-06-07 23:02
@jliexpensify Am I eligible for a report bonus for pointing out a related issue about `copy email`? It's been fixed, see PR comment https://github.com/Expensify/App/pull/19599#discussion_r1206353620 and my [proposal](https://github.com/Expensify/App/issues/18912#issuecomment-1546959257).  

@fedirjh Would you like to share your thoughts on this? I think you would have full context about what I mentioned as you made a great summary of previous discussions here https://github.com/Expensify/App/issues/18912#issuecomment-1553771372

cc @jasperhuangg

**Comment by jliexpensify** [comment] 2023-06-08 23:31
@eh2077 is there a separate reporting GH that was raised that you can link me to?

**Comment by jliexpensify** [comment] 2023-06-09 00:35
Was there a bug-reporting GH that you can link me to?

**Comment by eh2077** [comment] 2023-06-09 00:51
> @jliexpensify Am I eligible for a report bonus for pointing out a related issue about `copy email`? It's been fixed, see PR comment [#19599 (comment)](https://github.com/Expensify/App/pull/19599#discussion_r1206353620) and my [proposal](https://github.com/Expensify/App/issues/18912#issuecomment-1546959257).
> 

@jliexpensify I didn’t file another bug report about it because I was thinking to fix it together in this issue at the beginning. I also mentioned in the slack thread when we first discussed reproduction of the bug, see https://expensify.slack.com/archives/C049HHMV9SM/p1684113923020359?thread_ts=1684029611.911239&cid=C049HHMV9SM. 
I hope the links I included and @fedirjh 's last comment will be helpful for you to evaluate the case, thank you!

**Comment by jliexpensify** [comment] 2023-06-09 02:00
Thanks for the context, I'm not sure of the process here so I'll surface this internally and get back to you.

**Comment by jliexpensify** [comment] 2023-06-13 06:15
Apologies, I was OOO yesterday, checking the thead now.

**Comment by jliexpensify** [comment] 2023-06-13 06:22
@eh2077 - unfortunately we won't be paying you a reporting bonus here: we'll only pay a bug reporter this bonus if they have initially reported it and it's on a GH. This is our process and it's not something we can deviate from, for fairness. We do appreciate your contributions here and that you've gone above and beyond to help us discover additional issues that were fixed.

In the future, I would encourage you to raise a separate bug report for a GH to be created, this will ensure you'll get the reporting bonus (if applicable).

**Closed by jliexpensify** 2023-06-13 06:22 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
