### ISSUE TITLE
[$500] Web - (inconsistency) chat head disappears from LHN on request money, scan receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27028] opened 2023-09-08 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to fab button -> request money -> scan receipts
2. Choose a file
3. Notice that two new chat heads appear in LHN
4. Click on  them respectively and notice one of them disappears.

## Expected Result:
Chat heads should not disappear on doing scan receipts.
Such behaviour doesn't occur in manual money request.

## Actual Result:
Chat head disappears from LHN on request money, scan receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a1c5a9f3-0a47-465d-825f-8b3f16814c23

https://github.com/Expensify/App/assets/93399543/3199c356-6b02-46f3-b7d0-8933b8942e82

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693822940498749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ff3b52774fa3da3</li>
        <li>Upwork Job ID: 1700151042645573632</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-09-08 16:34
I think dupe of https://github.com/Expensify/App/issues/25770

**Comment by dylanexpensify** [comment] 2023-09-13 09:17
Reviewing!

**Comment by dylanexpensify** [comment] 2023-09-19 07:55
agree

**Closed by dylanexpensify** 2023-09-19 07:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
