### ISSUE TITLE
[$250] Split expense - qa.guide is included in a split expense from an announce room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42140] opened 2024-05-14 09:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to announce room > Click on + icon inside the compose box
4. Click on split expense
5. Enter an amount and click on next

## Expected Result:
qa.guide becomes excluded in the split

## Actual Result:
qa.guide is included in the split expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/31fb5f2a-75ef-467f-8980-8e3ec2bfd173

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0d7293f591a8751</li>
        <li>Upwork Job ID: 1791030117382258688</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-05-14 09:32
We think this issue might be related to the #vip-split.

**Comment by DylanDylann** [comment] 2024-05-17 06:32
@tienifr's [proposal](https://github.com/Expensify/App/issues/42140#issuecomment-2114705687) looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment] 2024-05-17 11:26
Flo is on a half day today and OOO on Monday, so ETA for review is Tues 21st earliest

**Comment by flodnv** [comment] 2024-05-21 20:11
Can someone clarify why this is a bug? I don't get it. What's wrong with the behavior and why do we want to stop it? 😕

**Comment by flodnv** [comment] 2024-05-22 21:08
Hm, it kinda makes sense, @laurenreidexpensify do you also think this reasoning applies to "split"?

**Comment by flodnv** [comment] 2024-05-23 15:55
Right, but I am wondering for example if there's a use case for someone@notexpensify.com to want/need to split with employee@expensify.com. What do you think @laurenreidexpensify ?

**Comment by laurenreidexpensify** [comment] 2024-05-23 18:17
I'm sorry I haven't had a chance to review this in depth today but have pinned it to look at first thing tomorrow and add a better summary of recommendation.

**Comment by laurenreidexpensify** [comment] 2024-05-24 15:48
> I am wondering for example if there's a use case for [someone@notexpensify.com](https://www.expensify.com/_support/?supportEmail=someone%40notexpensify.com&comment=better%20supportal%20issue%20nubmer%3A%2042140&location=_support/) to want/need to split with [employee@expensify.com](https://www.expensify.com/_support/?supportEmail=employee%40expensify.com&comment=better%20supportal%20issue%20nubmer%3A%2042140&location=_support/). W

Yeah that is definitely the case when we are testing split on the beta, where people are very likely using their Expensify accounts with their friends who are using @notexpensify.com accounts. 

This is a weird case of when corporate accounts overlap with consumer accounts....

**Comment by laurenreidexpensify** [comment] 2024-05-24 15:50
Overall I think this a reasonable polish [LOW] priority ?

**Comment by flodnv** [comment] 2024-05-24 16:17
Sure, but first it seems like we need to agree with the wider team what we actually want to accomplish. I can maybe get behind the case of never wanting to split with `@team.expensify.com`, but I am not convinced that we should prevent lauren@gmail.com from splitting with florent@expensify.com

**Comment by flodnv** [comment] 2024-05-27 16:10
I am confused: I tried to reproduce and failed. When I create a workspace, I am the only member of the #announce room (which is what I expected). How do you create a workspace and simultaneously have qa.guide be a part of the #announce room?

**Comment by laurenreidexpensify** [comment] 2024-05-29 13:59
I'm trying to reproduce this issue now and not able to reproduce with an @expensify.com email account. I'm going to close this issue because:

- It's not widely reproducible - there is likely something missing in the repro steps and it's hard to repro from an @expensify.com account
- There is an assumption that customers will find this confusing, but that is a bridge we will cross later 
- writing a condition to include / exclude a subset of domains from being part of a specific split scenario seems like an unnecessary addition to split flow at this point
- we can reopen if / when users report it as being an issue

**Closed by laurenreidexpensify** 2024-05-29 13:59 UTC
Labels: External, Daily, Help Wanted, Bug
