### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Web - Thread report and LHN title still visible after thread parent message being flagged as Intimidation or Bullying

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21890] opened 2023-06-29 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. From account B reply to the message in thread
3. From account B go back to the original report and flag the message as Intimidation or Bullying
4) Go back to the thread and notice the thread title still being visible in LHN and thread report

## Expected Result:
LHN title and thread report title should display "Message Hidden" while the parent message of the thread has MODERATOR_DECISION of PENDING_HIDE or HIDDEN

## Actual Result:
LHN title and thread report title are still visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/745df3ab-f261-4924-919f-f7b677ed6dcd

https://github.com/Expensify/App/assets/93399543/88431331-8b9c-4a28-92f3-92eec2f08990

**Expensify/Expensify Issue URL:**
**Issue reported by:** Amjed Nazzal
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687962396495309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a0825ff8c5c6ab6</li>
        <li>Upwork Job ID: 1674891685053624320</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-29 18:51
## Proposal
AmjedNazzal on GH
### Please re-state the problem that we are trying to solve in this issue.
Thread report and LHN title still visible after thread parent message being flagged as Intimidation or Bullying
### What is the root cause of that problem?
The text used for the titles of OptionRowLHN is retrieved from ReportUtils.getReportName which isn't handling the case where the parent message has been reported as Intimidation/Bullying or has been hidden.
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/libs/SidebarUtils.js#L372-L374
### What changes do you think we should make in order to solve the problem?
We could firstly add a new entry to parentReportAction and for example call it hiddenMessage and give it a value similar to deletedMessage.
We then can then add a check in ReportUtils.getReportName that would return hiddenMessage if the parentReport has MODERATOR_DECISION_PENDING_HIDE or MODERATOR_DECISION_HIDDEN.
```javascript
if (
    lodashGet(parentReportAction, 'message[0].moderationDecisions[0].decision') === CONST.MODERATION.MODERATOR_DECISION_PENDING_HIDE ||
    lodashGet(parentReportAction, 'message[0].moderationDecisions[0].decision') === CONST.MODERATION.MODERATOR_DECISION_HIDDEN
) {
    return Localize.translateLocal('parentReportAction.hiddenMessage');
}
```
### Result
https://github.com/Expensify/App/assets/74202751/d3d75b2d-98d7-4668-994e-7a09670438cd

**Comment by joekaufmanexpensify** [comment] 2023-06-30 21:23
I can reproduce. We decided to split this off from https://github.com/Expensify/App/issues/21497#issuecomment-1611409927 . Seems like expected behavior here is: 

>Intimidation/Bullying: The message will show as [Hidden]. You can still access the replies. The thread can be seen in LHN but titled [Hidden]

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:06
Not overdue. Waiting for proposals

**Comment by AmjedNazzal** [comment] 2023-07-03 16:55
@joekaufmanexpensify There is my proposal by the way posted by kbecciv :)

**Comment by dangrous** [comment] 2023-07-06 13:58
Whoops, nope, never did that. Would be great to handle it here!

**Comment by joekaufmanexpensify** [comment] 2023-07-06 17:51
Works for me!

**Comment by AmjedNazzal** [comment] 2023-07-06 19:30
@joekaufmanexpensify is it going to be like an internal fix? or is my proposal going to be reviewed?

**Comment by joekaufmanexpensify** [comment] 2023-07-06 19:32
I'm thinking we'll review your proposal, right @thesahindia ?

**Comment by shawnborton** [comment] 2023-07-07 14:02
I'm not too sure here, @dangrous since you worked on moderation, what do you think?

**Comment by dangrous** [comment] 2023-07-07 19:22
Behavior is certainly fine by me! Only question would be the specific copy we use. Not to suggest a ping of yet another person, but have we had marketing take a look at it? `[Hidden message]` (note the **lowercase** message) probably works fine and follows the `[Deleted message]` pattern, but would be good to double check.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:59
Sounds good! Adding marketing label to get copy input. Here's a summary of the issue, if you're assigned:

If a message is reported as being intimidation for bullying, we currently hide the message in the chat, and give the option to reveal its contents. However, if the reported message has a thread report beneath it, we still show the reported message's contents in the thread report title in LHN, and then in the thread header if you click into the thread report. 

In this issue, we're proposing that when a message reported for bullying/intimidation has a thread beneath it, that we'll hide the reported message in LHN, and then the thread report's header. We're proposing that we do this with the following copy `[Hidden message]`. 

We're thinking this makes sense, as it follows a similar pattern to how we handle a thread's parent message being deleted (`Deleted message`), though curious if you agree?

**Comment by NickTooker** [comment] 2023-07-10 23:31
@joekaufmanexpensify I agree with your thought process and the brief copy. Let me know if I missed anything or if you need anything else!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:46
Cool cool, thanks Nick!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 18:48
>can we also get the spanish version of Message hidden so we can add it to es.js as well?

@AmjedNazzal I am looking into this and will report back!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 19:33
Translation is `[Mensaje oculto]`

**Comment by AmjedNazzal** [comment] 2023-07-11 19:35
@joekaufmanexpensify Thank you!

**Comment by joekaufmanexpensify** [comment] 2023-07-12 18:51
Proposal pending internal approval

**Comment by jasperhuangg** [comment] 2023-07-12 19:01
@AmjedNazzal's proposal makes sense to me! Seems like a good decision to reuse the existing logic for deleted parent actions for hidden ones. Assigning them!

cc @dangrous @thienlnam just so you're aware of this change

**Comment by AmjedNazzal** [comment] 2023-07-12 20:21
Thank you! offer accepted and PR is ready for review @thesahindia @jasperhuangg

**Comment by AmjedNazzal** [comment] 2023-07-14 16:30
@joekaufmanexpensify Is there something wrong with Melvin? Doesn't seem like it recognized the PR being merged within 3 days even through it has even been deployed to staging

**Comment by joekaufmanexpensify** [comment] 2023-07-14 18:50
Hm, yeah could be. Regardless, we'll issue bonus as the PR was merged in less than 72 hours, independent of whether the automated message is working.

**Comment by AmjedNazzal** [comment] 2023-07-24 18:32
@joekaufmanexpensify Friendly nudge regarding payment :)

**Comment by joekaufmanexpensify** [comment] 2023-07-24 18:36
Thanks! Yep we just need to complete the BZ checklist before we can send payment. @thesahindia mind completing your portion?

**Comment by joekaufmanexpensify** [comment] 2023-07-24 19:56
Okay, this one qualifies for a speed bonus, so we need to make the following payments:

- @AmjedNazzal - $1,750 ($1000 for PR + $500 speed bonus + $250 reporting bonus). 
- @thesahindia $1,500 ($1000 for C+ review, and $500 speed bonus).

**Comment by joekaufmanexpensify** [comment] 2023-07-24 19:58
@AmjedNazzal you're already hired, so we'll issue payment as soon as the BZ checklist is complete.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 19:58
@thesahindia once the BZ checklist is complete, please submit a payment request, and comment on the issue once you've done that!

**Comment by joekaufmanexpensify** [comment] 2023-07-25 17:07
Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:32
BZ checklist is complete.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:37
@AmjedNazzal $1,750 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:37
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:38
@thesahindia could you please request $1,500 and comment here once complete?

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:38
Note: payment summary message is [here. ](https://github.com/Expensify/App/issues/21890#issuecomment-1648520781)

**Comment by joekaufmanexpensify** [comment] 2023-07-26 22:05
All good. Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-28 12:38
@thesahindia did you have a chance to request payment here yet?

**Comment by sonialiap** [comment] 2023-07-28 14:49
I can reproduce the issue still 

https://github.com/Expensify/App/assets/17131195/c21b8108-482a-45a0-8f67-e9ad746bdcdd

**Comment by joekaufmanexpensify** [comment] 2023-07-31 20:50
@sonialiap are you still able to reproduce this now? I just tested on my end, and it seemed to work. Though, I had to click into the thread after reporting the message before the title updated to `Hidden message`. 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/54866469/e863d1d6-e1d6-46f7-9f48-26cecb781198">

**Comment by joekaufmanexpensify** [comment] 2023-08-01 20:37
Still figuring this out

**Comment by joekaufmanexpensify** [comment] 2023-08-02 17:55
Okay, I tested this again, and it's working for me. So going to close this out. @sonialiap LMK if you see this not working again, and happy to look into it more.

**Comment by joekaufmanexpensify** [comment] 2023-08-02 17:57
Please note that @thesahindia still needs to request payment, but [advised](https://github.com/Expensify/App/issues/21890#issuecomment-1656090329) we can close this in the interim, and he'll request payment once the issue with his bank account is resolved. 

Here's the summary of payments for when we pay this in NewDot: 

- @AmjedNazzal - $1,750 ($1000 for PR + $500 speed bonus + $250 reporting bonus). Paid via Upwork. 
- @thesahindia $1,500 ($1000 for C+ review, and $500 speed bonus). Still needs to be paid via NewDot.

**Closed by joekaufmanexpensify** 2023-08-02 17:57 UTC
Labels: External, Daily, Waiting for copy, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:26
Reviewed the details for @thesahindia. $1,500 approved for payment in NewDot based on the BZ summary above.
