### ISSUE TITLE
Chat - Back button brings to thread chat instead of LHN after clicking parent chat link in header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20851] opened 2023-06-15 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20484

## Action Performed:
1. Login to NewDot
2. Open chat
3. Send message
4. Create a thread
5. Tap parent link in the header
6. Parent chat is displayed
7. Tap back button

## Expected Result:
LHN should be displayed

## Actual Result:
Thread chat is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c3eb8d37-068b-44ec-a229-49f21a4fc3bd

https://github.com/Expensify/App/assets/78819774/7793764f-acc2-4654-a8ef-dc2ef6cf90c5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2023-06-15 21:10
I'm pretty sure this is not a blocker, back button by design takes you to the previous screen. If your thread was the previous screen then it would take you to the thread. By design it would work the same on any mobile screen.

I'll ask around and confirm if people want the behavior to be different.

**Comment by chiragsalian** [comment] 2023-06-15 21:26
Verified with @JmillsExpensify, this is by design. The back button goes to the previous screen in the stack. Closing since this is a non-issue.

**Closed by chiragsalian** 2023-06-15 21:26 UTC
Labels: DeployBlockerCash, Engineering, Hourly
