### ISSUE TITLE
[Hold for payment 2022-12-06 $1000] Create a way to check for updates on the desktop app

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11817] opened 2022-10-13 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Click on the NewExpensify system menu

## Expected Result:
If there is an update available, you should see a "Update New Expensify" menu item. If there's no update available (at least that the app is currently aware of), then there should be a "Check for updates" menu item.

## Actual Result:
If there is an update available, there is a "Update New Expensify" menu item. If there's no update available, then that menu item is disabled.

## Workaround:
Close the desktop app and reopen it – that will trigger a check for updates.

## Platform:
Where is this issue occurring?

- Desktop App

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~013a69f9cbfc1e9cad
- Upwork Job ID: 1597485689278185472

**Comment by kidroca** [comment] 2022-10-13 19:21
Oh, this one is super easy, give it here please!

**Comment by kidroca** [comment] 2022-11-07 08:27
Ops, sorry forgot about this one, will submit a PR today

**Comment by kidroca** [comment] 2022-11-09 19:43
`Waiting for Copy` 

Hey guys can you review the sample screenshots and video in the PR and if you like it please provide the actual texts you'd like to appear in these dialogs
- https://github.com/Expensify/App/pull/12607 (see Desktop screenshots and attachments)

**Comment by pecanoro** [comment] 2022-11-09 20:52
@danielrvidal Can you check @kidroca PR and review the copy in the screenshots to make sure it's fine and we don't need to change it?

**Comment by roryabraham** [comment] 2022-11-09 21:45
For a bit more context @danielrvidal, right now if an update is available we'll show a modal with:

- title: "Update app"
- content: "A new version of this app is available.
Update now or restart the app at a later time to download the latest changes."
- submit button: "Update app"
- cancel button: "Cancel"

What we need now is to decide what to show the user if we check for an update and one is not available. Here's my rough draft for you:

- title: "New Expensify is up to date!"
- content: "There's no update available right now."
- submit button: "Check again"
- cancel button: "Okay"

**Comment by danielrvidal** [comment] 2022-11-10 03:31
@roryabraham that looks a little different than the video in @kidroca linked video but I assume that is okay. I think the text you highlighted above looks great so am 👍 to that!

**Comment by kidroca** [comment] 2022-11-10 17:20
@roryabraham 
What you're sharing is for when an update was downloaded and we inform the user that they can apply it
> * content: "A new version of this app is available.
>   Update now or restart the app at a later time to download the latest changes."
> * submit button: "Update app"
> * cancel button: "Cancel"

This content does not make sense for "Check for Update", because the update is still being downloaded - we just give quick feedback whether update exist (and we immediately start downloading it)

1. User selects "Check for Update" 
2. We make a quick check and inform the user of the result - there are 3 cases 
- Update available -> we tell the user update is available and being downloaded 
- Update not available -> text for when update is not available
- Update check failed -> generic error text (check might fail for various reasons - no internet, update server not responding)

---

The first time I used "check for updates" it took 5 minutes to download the update
It would be weird to press "check for updates" and only get feedback 5 minutes after, so I added this dialog to present immediate feedback - let users know update is being downloaded and they'll get the same notification an update is ready as with automatic updates

**Comment by kidroca** [comment] 2022-11-14 10:49
@roryabraham @danielrvidal sorry guys, there seems to be some misunderstanding 

@roryabraham shared for context what we show right now - when the app is ready to update 

What we need here though is something different:

The user checks for update using the system menu 
Shortly after we present a dialog with the result. 
There are 3 cases:
- **update available** -> we print a text that update is being downloaded this very moment (but not yet completed), when the download finishes the user would be notified the update is ready to be installed - what Rory shared
- **update not available** -> we print a text that at them moment update is not available (probably because the user is already on the latest version)
- **update check failed** -> a message that would be shown in case of an error - network or bad server response

I need approved texts for the 3 cases listed above.

To make this simple, let's just make this an informative dialog with just one "OK" button that closes the dialog 
_(If people want to re-check they can just do another check from the system menu)_

**Comment by kidroca** [comment] 2022-11-14 18:27
@danielrvidal 
> If those are correct, in the second screen, is there next step to try to update again?

There would be a menu entry here, allowing users to check for updates manually whenever they want:
![image](https://user-images.githubusercontent.com/12156624/201737172-66eab947-cecb-4874-9a44-62afc4240aa5.png)

Can people just use the menu again if the want to check for update again? 
_Adding a "Check again" button to the dialog would only allow people to spam the update server with requests, they can still do that through the system menu if they desire_ 

_(If you think otherwise, I can add a "Check again" button, just approve a label text)_

BTW the 2nd screenshot here https://github.com/Expensify/App/issues/11817#issuecomment-1314039418 is when we **failed** to communicate with the server or it returned an error 
There's a separate case for when server responded that there's no update right now
Here's a screenshot for that:

![image](https://user-images.githubusercontent.com/12156624/201736922-6ab4795a-5112-4bcd-ad70-3b0f3125d7f4.png)

_(There would be just one OK (or Close) button)_

I've described the 3 possible cases we need copy for here: https://github.com/Expensify/App/issues/11817#issuecomment-1313468239

**Comment by danielrvidal** [comment] 2022-11-14 22:49
@kidroca I think this should cover them all! Can you let me know if anything I wrote looks off for the cases you were highlighting. 

**Update Available**
The new version will be available shortly. We’ll notify you when we’re ready to update. 
[Sounds good]

**Update Not Available**
There is no update available as of now! Check again at a later time. 
[Okay] 

**Update Check Failed**
We couldn’t look for an update. Please check again in a bit to look for an update! 
[Okay]

**Comment by kidroca** [comment] 2022-11-15 10:14
@danielrvidal 
If you don't mind, for the 3rd case, I'd shorten the text like so:
`We couldn’t look for an update. Please check again in a bit!`
instead of
`We couldn’t look for an update. Please check again in a bit to look for an update!`

**Comment by danielrvidal** [comment] 2022-11-16 20:04
Yup, good update! Please go with yours!

**Comment by kidroca** [comment] 2022-11-21 08:16
PR is still under review

**Comment by kidroca** [comment] 2022-11-25 09:22
Ooops - PR was merged 2 days ago
 - https://github.com/Expensify/App/pull/12607

_I thought merges are detected automatically and a bot comment is posted on the issue?_

**Comment by roryabraham** [comment] 2022-11-29 07:00
Marking External to handle C+ payment

**Comment by trjExpensify** [comment] 2022-11-29 11:01
Cool, once this hits prod the +7 days hold for awaiting payment should get added.

**Comment by commanderz** [comment] 2022-11-29 14:23
this solved in tutorial 
https://www.electronjs.org/docs/latest/tutorial/updates

**Comment by roryabraham** [comment] 2022-11-29 20:44
@commanderz we've already merged a solution to this issue

**Comment by trjExpensify** [comment] 2022-12-06 00:05
What's the dealio here? This is only on staging is it? https://github.com/Expensify/App/pull/12607#issuecomment-1325812452

**Comment by trjExpensify** [comment] 2022-12-08 21:53
Oh, I see. The automation just didn't run. Thanks for updating the title, @luacmartins. Sent offers out on this job for the following payouts:

- @Santhosh-Sellavel $1000 for C+
- @kidroca $1000 for the fix

Please accept guys and I'll settle up.

**Comment by luacmartins** [comment] 2022-12-08 21:57
I could swear I had left a comment about the automated message failing, must have missed this one 😓

**Comment by Santhosh-Sellavel** [comment] 2022-12-08 22:05
@luacmartins You left it on PR [here](https://github.com/Expensify/App/pull/12607#issuecomment-1339731603)

**Comment by luacmartins** [comment] 2022-12-08 22:06
Ah thanks @Santhosh-Sellavel! I'm not that crazy yet 😄

**Comment by trjExpensify** [comment] 2022-12-08 22:32
@Santhosh-Sellavel - paid! 

>I'm not that crazy yet 😄

Debatable 🤪

**Comment by kidroca** [comment] 2022-12-09 13:57
Hey @trjExpensify, you can cancel my payout, because I already tracked and receive payment through my hourly contract 

I was invited to take this ticket - when I'm selected for something without a proposal I track the spent time under the hourly

BTW this ticket was not a bug, but a feature/improvement

**Comment by trjExpensify** [comment] 2022-12-09 14:11
Oh, you were invited to this one. Got it! 

We're all set here then, closing 👍

**Closed by trjExpensify** 2022-12-09 14:11 UTC
Labels: Reviewing, External, Engineering, Daily, NewFeature
