### ISSUE TITLE
[HOLD][$250] Send invoices - Date notification not copied when invoice date is changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43571] opened 2024-06-12 13:49 UTC
Held on https://github.com/Expensify/App/issues/43797

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB > Send invoice
2. Add amount, select user and workspace
3. Add merchant and send the invoice
4. Go to invoice details and change the date
5. Notice the notification appears. Attempt to copy it, but it doesn't work

## Expected Result:
The date notification should be copied when the invoice date is changed

## Actual Result:
After sending the invoice, changing the date triggers a notification. However, attempting to copy the notification fails

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8b92eb63-e714-47da-a547-21bc0303d970

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111e39bcf78303fbe</li>
        <li>Upwork Job ID: 1803213787847433243</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102904588</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-06-12 13:49
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-06-18 23:44
Testing now.

**Comment by strepanier03** [comment] 2024-06-18 23:49
Confirmed reproducible on mac Chrome.

**Comment by truph01** [comment] 2024-06-19 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attempting to copy the notification fails

### What is the root cause of that problem?
When creating an invoice, in https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/actions/IOU.ts#L3560, the params `createdIOUReportActionID` and `reportActionID` (IOU action id) are not sent to back-end to use as real report action ids.

So the back-end is creating new IOU action id and send back to front-end. This makes the Invoice has 2 IOUs, so the `transactionThreadReportID` [here](https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/ReportUtils.ts#L6042) is undefined.

Because of that, the `originalReportID` [here](https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/pages/home/report/ReportActionItem.tsx#L216) is incorrect, it will be the iou report id while it must be the `transactionThreadReportID`

Next, the `reportAction` [here](https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L131) will be empty (we try to get the modified expense report action from the IOU report which is not found, because `originalReportID` is wrong above)

So the copying doesn't work because `reportAction` is empty.

### What changes do you think we should make in order to solve the problem?

When creating an invoice, in https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/actions/IOU.ts#L3560, the params `createdIOUReportActionID` and `reportActionID` (IOU action id) should be sent to back-end.

Those can be returned from the `getSendInvoiceInformation` https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/actions/IOU.ts#L1852
```
createdIOUReportActionID: optimisticCreatedActionForIOUReport.reportActionID,
reportActionID: iouAction.reportActionID,
```

The back-end should be updated to make sure to support those params, and use them as the real action ids. If not mistaken, at the moment it's supporting `createdIOUReportActionID` but not `reportActionID`

### What alternative solutions did you explore? (Optional)
In https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/ReportUtils.ts#L6042, use the `reportActions` after applying `getContinuousReportActionChain` so that it will get the correct chain of report actions. This is same method as of [ReportScreen](https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/pages/home/ReportScreen.tsx#L261)

**Comment by getusha** [comment] 2024-06-25 16:06
@strepanier03 Reassigning this due to low bandwidth @c3024 will takeover

**Comment by c3024** [comment] 2024-06-28 06:00
Not overdue @MelvinBot

**Comment by c3024** [comment] 2024-06-28 17:09
The RCA in @truph01's proposal makes sense to me. The context menu actions are displayed correctly, and the report action is successfully copied to the clipboard when the invoice is sent offline. However, when the backend response is received, there are duplicated report actions with different IDs. Therefore, I agree with the proposed solution to send both `createdIOUReportActionID` and `reportActionID` to the backend, accompanied by the necessary backend changes.

🎀 👀 🎀 C+ Reviewed

**Comment by stitesExpensify** [comment] 2024-07-01 22:04
No update, I need to look into this more since there are backend changes proposed

**Comment by stitesExpensify** [comment] 2024-07-09 18:05
@cristipaval do you have the ability to look into this since it is part of vip-billpay? I am super focused on travel and it looks like this is not just a front-end change

**Comment by cristipaval** [comment] 2024-07-09 20:24
yes, I can take it over

**Comment by tsa321** [comment] 2024-07-15 13:46
@c3024 @cristipaval If we want to handle the similar errors in Front End based on [this message](https://expensify.slack.com/archives/C01GTK53T8Q/p1720533672162139?thread_ts=1720533146.376329&cid=C01GTK53T8Q), we could remove the optimistic created report actions (and optimistic IOU report action) after the API request completed. Similar to my [proposal](https://github.com/Expensify/App/issues/43797#issuecomment-2173688182) in other issue.

**Comment by c3024** [comment] 2024-07-18 02:17
@rayane-djouah yes, you are right. Both issues will be fixed by the same changes.

**Comment by c3024** [comment] 2024-07-18 02:18
@tsa321 Removing the optimistic report actions in success data does not look a correct pattern to me. Is there anywhere in the repo that we do this?

**Comment by cristipaval** [comment] 2024-07-29 13:01
Ok, so we are holding on to this issue for https://github.com/Expensify/App/issues/43797. Correct?

**Comment by c3024** [comment] 2024-07-29 13:09
Oh, it looks like that issue was already assigned. I thought that issue was held and this was moving. 😆

Yes, this issue can be held. PR for #43797 should fix this.

**Comment by cristipaval** [comment] 2024-08-07 10:27
Still held

**Comment by cristipaval** [comment] 2024-08-16 10:27
We're actively working on the issue that this one is held on

**Comment by cristipaval** [comment] 2024-08-26 09:51
[The PR](https://github.com/Expensify/App/pull/46001) fixing the issue that this one is held on has been merged. Waiting for it to get deployed.

**Comment by cristipaval** [comment] 2024-08-27 10:05
This issue can be retested in staging.

**Comment by strepanier03** [comment] 2024-09-03 18:09
Testing now.

**Comment by strepanier03** [comment] 2024-09-03 18:11
This is no longer reproducible. When following the testing steps on staging it's working as expected.

**Comment by strepanier03** [comment] 2024-09-03 18:16
I think we can close this out now since it's no longer needed. Please reopen if you disagree.

**Closed by strepanier03** 2024-09-03 18:16 UTC
Labels: External, Weekly, Bug
