### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Settings - On Share Code page number is not displayed in formatted as we displayed on other pages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20931] opened 2023-06-16 19:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND (with number login)
2. Navigate to settings
3. Navigate to share code screen
4. Notice subtitle on QR view shows phone number with email extension (not formatted as we can see on setting page)

## Expected Result:
Phone number should be formatted as we can see on profile page

## Actual Result:
Phone number is not formatted as we does on other pages like (profile page ,account close page )

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Simulator Screenshot - iPhone 14 - 2023-05-22 at 12 26 35](https://github.com/Expensify/App/assets/93399543/559c905d-a847-4f50-a39f-a60532355a64)

![Simulator Screenshot - iPhone 14 - 2023-05-22 at 12 26 39](https://github.com/Expensify/App/assets/93399543/26433c26-cb1b-46aa-a816-472a0e2fb93d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhairyasenjaliya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684739607316259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6e5878ab0553a59</li>
        <li>Upwork Job ID: 1671639469433528320</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-06-18 15:50
This one is on my test list

**Comment by alexpensify** [comment] 2023-06-20 22:28
I'll be testing soon!

**Comment by alexpensify** [comment] 2023-06-21 22:01
I've reviewed the Slack convo and will be assigning it to `External` since this one is not a dupe.

**Comment by wysohn** [comment] 2023-06-22 03:14
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
email isn't properly formatted in Share Code page as it does in Initial Settings page

## What is the root cause of that problem?
`props.session.email` is being used directly without going through formatPhoneNumber

## What changes do you think should make in order to solve the problem?
Replace

https://github.com/Expensify/App/blob/e6c4b4e2f0bf9f42e57bebdd7720ee776ab6c93a/src/pages/ShareCodePage.js#L68

to

```
subtitle={isReport ? subtitle : this.props.formatPhoneNumber(this.props.session.email)}
```

---

And is it supposed to be only for internal employees? Not sure why it's up in the Upwork then

**Comment by wysohn** [comment] 2023-06-22 03:17
Contributor details
Your Expensify account email: wysohn2012@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016a986842f84635e0

**Comment by nikhiln** [comment] 2023-06-22 03:17
### Proposal
-----

### Please re-state the problem that we are trying to solve in this issue.
Settings - Share code barcode - phone number is not formatted with valid format (uses email formatting instead of the regular phone number formatting being used across the app)

### What is the root cause of that problem?
The [ShareCodePage](https://github.com/Expensify/App/blob/main/src/pages/ShareCodePage.js#L68) component is trying to use the email available on the session without checking if its the phone number being used as primary method instead of email.

### What changes do you think we should make in order to solve the problem?
It seems that we are calling the formatPhoneNumber method everywhere and missing to use that on specific page (e.g. like this component causes this kind of display bug. Instead of that, we are simply expose the displayedUserName field with already formatted value (email or phone - based on the authentication type) from `withCurrentUserPersonalDetails` component itself and start using that everywhere


### What alternative solutions did you explore? (Optional)
NA

**Comment by nikhiln** [comment] 2023-06-22 03:19
Contributor details
Your Expensify account email: nikhil.navadiya@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0128e76e442a99847c

**Comment by alexpensify** [comment] 2023-06-22 18:33
@fedirjh - when you get a chance, can you review the proposals to identify if they will work to resolve the problem? Thank you!

**Comment by alexpensify** [comment] 2023-06-26 03:58
@fedirjh - based on this feedback, do you think we should close or start a discussion?

**Comment by alexpensify** [comment] 2023-06-29 22:24
Reassigning another `bug` team member, I'm going OOO until Monday, July 10, and will take it back then if it's not closed by then. 

Required action from the 🐛 team: Make sure the proposal process is moving forward, so we can get this one assigned out to fix.

**Comment by MonilBhavsar** [comment] 2023-07-05 12:19
@dhairyasenjaliya feel free to open a PR

**Comment by MonilBhavsar** [comment] 2023-07-05 14:39
Merged PR. Thanks all for the quick work!

**Comment by sakluger** [comment] 2023-07-05 17:48
So fast! Nice work everyone.

**Comment by alexpensify** [comment] 2023-07-10 21:11
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

Prepare for payment

**Comment by alexpensify** [comment] 2023-07-13 21:24
Preparing for payment, I think there should be a bonus here. 

Also, @fedirjh can you please complete the checklist: https://github.com/Expensify/App/issues/20931#issuecomment-1625187080

Thanks!

**Comment by alexpensify** [comment] 2023-07-14 21:12
Alright, @dhairyasenjaliya and @fedirjh, I've prepared the payments via Upwork. Please confirm you received it and I can close this GH out after I create the regression test. Thank you!

**Comment by alexpensify** [comment] 2023-07-16 16:49
Thank you and great work! I've closed the job in Upwork, created the regression test, and am going to close this GH now.

**Closed by alexpensify** 2023-07-16 16:49 UTC
Labels: External, Daily, Awaiting Payment, Bug
