### ISSUE TITLE
[$500] Entering certain diacritics such as à, á, â in the composer is broken (iOS Simulator)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36203] opened 2024-02-09 02:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @francoisl 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707435603099939

## Action Performed:

1. Open any chat
2. In the composer, type Option+`, then a

## Expected result: 
 à is entered in the composer
## Actual result: 
`a is entered in the chat
Same goes with Option+e , then letter, e.g. ´a is entered instead of á

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011af575af2fe9ca45</li>
        <li>Upwork Job ID: 1755783765816233984</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-02-09 12:44
👋 As a native romanian I can confirm that these diacritic characters work if pasted / written directly in the composer using native keyboard (or native keyboard shortcut extensions):

<img width="348" alt="Screenshot 2024-02-09 at 14 35 29" src="https://github.com/Expensify/App/assets/56457735/e2150ac2-7b2a-4979-8486-d81021668419">

I never encountered any apps in which I had to write a certain combination of characters which then were parsed to my native diacritics like: `ă`, `â`, `î`, `ș`, `ț`, french ones like `à`, `è`, `ù`, or german ones: `ä`, `ö`, `ü`, `ß`.

If we're expecting character combinations like `´a` to be parsed as `á` then I think that would be a new feature, though a pretty confusing one 👀 since there are so many language diacritics that would have to come up w/ character combinations for.

Unless this used to work at a certain point (by design) and it doesn't work anymore.

**Comment by francoisl** [comment] 2024-02-09 18:14
> written directly in the composer using native keyboard

Ah yes I think that's the difference, I'm using a Macbook with a US English keyboard, which doesn't have any keys with accents.

To clarify, this is not an Expensify-specific feature, it's a [native way](https://support.apple.com/guide/mac-help/enter-characters-with-accent-marks-on-mac-mh27474/mac) to enter accents on MacOS, and so far I haven't seen any app where this didn't work.

The other way is to long-press on a key like `a`, and it opens a small modal with the variations of the letter you can choose from, but I don't think anyone in their right mind uses that regularly 😄

<img width="275" alt="image" src="https://github.com/Expensify/App/assets/2229301/a4be3357-e44d-4fcb-b1ba-23fddc7861ec">

**Comment by francoisl** [comment] 2024-02-09 18:20
Btw, forgot to mention but this is most likely due to https://github.com/Expensify/App/pull/35837.

**Comment by jeremy-croff** [comment] 2024-02-09 19:53
> Btw, forgot to mention but this is most likely due to #35837.

Cannot reproduce anymore, I believe that was the culprit and had been reverted.

**Comment by tomekzaw** [comment] 2024-02-12 11:39
A similar issue also occurs on iOS simulator. The diacritics are correctly applied but the leading backtick is not removed.

Using `RNTextInput` (without Live Markdown Preview):

https://github.com/Expensify/App/assets/20516055/6b15b81f-967f-463f-8613-332491028c46

Using `MarkdownTextInput` (with Live Markdown Preview):

https://github.com/Expensify/App/assets/20516055/e76c7774-059e-48ae-b515-9505d5ccd5f7

**Comment by tomekzaw** [comment] 2024-02-12 13:38
This issue is reproducible in Live Markdown example app, reported as https://github.com/Expensify/react-native-live-markdown/issues/181.

**Comment by greg-schroeder** [comment] 2024-02-12 21:43
Okay - should we create a new issue or just change this one to focus on the iOS case?

**Comment by tomekzaw** [comment] 2024-02-13 13:53
The behavior on native iOS will be fixed in https://github.com/Expensify/react-native-live-markdown/pull/182.

**Comment by francoisl** [comment] 2024-02-13 19:36
@tomekzaw to clarify, will that PR only fix native iOS? Cause the issue was also happening on web & desktop. Either way it's fine, we can keep this issue open to remember to also fix other platforms.

**Comment by tomekzaw** [comment] 2024-02-13 22:41
@francoisl That's correct, this PR only fixes native iOS. We're still investigating the issue on web.

**Comment by greg-schroeder** [comment] 2024-02-16 05:29
>Cause the issue was also happening on web & desktop. Either way it's fine, we can keep this issue open to remember to also fix other platforms.

All right - but I thought web was fixed by the revert of https://github.com/Expensify/App/pull/35837? @francoisl

**Comment by tomekzaw** [comment] 2024-02-19 15:40
That's correct, web was fixed by reverting #35837, but we still need to fix the problem before we re-land this PR, that's why this issue is still open.

For native, the issue is not reproducible on real iOS device (only simulators) so it's not a big deal. Anyways, it will be fixed in https://github.com/Expensify/react-native-live-markdown/pull/182 which needs to be backported to the E/App in a follow-up PR.

@thienlnam I think we might want to submit another issue (for native) so we can track its progress separately from web.

**Comment by greg-schroeder** [comment] 2024-02-19 21:49
Got it, thanks for the context @tomekzaw

**Comment by thienlnam** [comment] 2024-02-20 20:03
Created a separate web version for us to track here https://github.com/Expensify/App/issues/36942

We can close this issue once we resolve this for mobile

**Comment by mvtglobally** [comment] 2024-02-21 02:23
Issue not reproducible during KI retests. (First week)

**Comment by tomekzaw** [comment] 2024-02-26 16:27
Working on it

**Comment by greg-schroeder** [comment] 2024-03-02 00:33
Thoughts on a timeline for this one @tomekzaw? Just want to make sure I'm on the same page <3

**Comment by tomekzaw** [comment] 2024-03-02 16:17
@greg-schroeder Since this issue happens only on iOS simulators, we decided to deprioritize this and focus on the analogous issue happening on web first. Once we fix it for web, I will continue working on this issue.

**Comment by thienlnam** [comment] 2024-03-05 19:15
Updating the priority - this does not impact any real devices

**Comment by greg-schroeder** [comment] 2024-03-26 04:29
Closing this per team discussion

**Closed by greg-schroeder** 2024-03-26 04:29 UTC
Labels: Engineering, Monthly, Internal, Bug
