### ISSUE TITLE
[$1000] Web - Owed information is wrong when sending money request between accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22197] opened 2023-07-04 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to account A and Account B on different devices
2. From account A: send Money request to account B, with "amount = X"
3. From account B: send Money request to account A, with SAME "amount = X "
Observer that: these 2 request will be marked as paid automatically
4. From account B: send ANOTHER money request to A, with "amount = Y"
5. Check the request information

## Expected Result:
The request information should say “A owes Y”
- The “Pay elsewhere button” is displayed on account A

## Actual Result:
The request information shows “B owes Y”
- The “Pay elsewhere button” is displayed on account B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d4001c21-24ad-44b8-86f9-4b49ff618132

https://github.com/Expensify/App/assets/93399543/5558c72d-275b-4d9d-aef6-5402db96c2e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** ToanSel
QA Engineer - Github: @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688446357913299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1a2f08520a2ebd5</li>
        <li>Upwork Job ID: 1678605892035735552</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-04 17:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The text `${payer} owes ${amount}` is confusing when looking from the requestor's perspective.

### What is the root cause of that problem?
- The text is confusing because it is written from the perspective of the payer, not the requestor.

### What changes do you think we should make in order to solve the problem?
- The text should be written from the perspective of the requestor. Like `You owe ${amount}`.
- For the payer, the text should be same `${payer} owes ${amount}`.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by mallenexpensify** [comment] 2023-07-11 03:23
Was able to reproduce, thinking/hoping this can be External

**Comment by StevenKKC** [comment] 2023-07-11 17:34
I am unable to reproduce the issue on latest dev. [This PR](https://github.com/Expensify/App/pull/20900) seems to have already fixed the issue.

**Comment by mallenexpensify** [comment] 2023-07-11 23:30
Also unable to reproduce so closing, amount owed is now showing correctly. comment if you disagree 
<img width="381" alt="image" src="https://github.com/Expensify/App/assets/22508304/89704bd6-4b52-4bc4-84d0-b95e45bbc83c">

**Comment by tranvantoan-qn** [comment] 2023-07-12 00:59
@mallenexpensify 
I tried to verify it on main, but it seems like when **A sends a request money to B**, the amount with be paid automatically.?
(so I couldn't perform the same set of steps to reproduce it)

https://github.com/Expensify/App/assets/10254571/6f55b436-8a14-4fba-b2ce-ed4a52b202a0

**Comment by tranvantoan-qn** [comment] 2023-07-12 01:20
@mallenexpensify 
Clear cache helps fix the "auto-paid" issue above, but the issue is still happening after **step 4** as mentioned in **Action Performed**. 

Please check the attached image - in which I added a details explanation. Let me know if I can help to reproduce it

![image](https://github.com/Expensify/App/assets/10254571/e4c6702b-3ca5-4546-a574-e6d3d655b7b4)


https://github.com/Expensify/App/assets/10254571/74f35572-3805-46be-8c02-f551a716f261

**Comment by tranvantoan-qn** [comment] 2023-07-12 14:29
@mallenexpensify 
Hope that you can consider 2 things:
- The issue doesn't seem to be completely fixed as it's still occurring. 
- Am I eligible for a reporting bonus? My report was valid and initially had no connection with this [PR](https://github.com/Expensify/App/pull/20900)

Thank you!

**Comment by mallenexpensify** [comment] 2023-07-14 22:20
@tranvantoan-qn I tried to repro again a couple times between two accounts, back and forth, with no luck. 
For the bug reporting bonus, since @kbecciv was able to reproduce, it appears it was a valid bug.  I looked around to try to find the PR that fixed it, d you know @tranvantoan-qn or @aimane-chnaif ?

**Comment by tranvantoan-qn** [comment] 2023-07-15 00:13
@mallenexpensify When I was helping to test this PR and it looks like it fixed this issue somehow:
https://github.com/Expensify/App/pull/20821/

**Comment by mallenexpensify** [comment] 2023-07-17 20:55
Checking in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1689627262480169?thread_ts=1688446357.913299&cid=C049HHMV9SM

I'd like to know what PR fixed this before deciding on potential payment for the reporting bonus.

**Comment by mallenexpensify** [comment] 2023-07-18 15:17
Thanks @tranvantoan-qn .   So... it seems like we had this
- https://github.com/Expensify/App/issues/20486

Which then lead to this
- https://github.com/Expensify/App/issues/22332

The PR for the above was
- https://github.com/Expensify/App/pull/22484

And... somewhere along the line the bug presented itself then was fixed somewhere/how. 
Does that sound right @tranvantoan-qn ?

**Comment by mallenexpensify** [comment] 2023-07-19 14:17
Thanks @tranvantoan-qn .  @aimane-chnaif can you review and provide feedback?  Normally, in order to be compensated for reporting a bug that was fixed elsewhere, it's the contributor's responsibility to prove their report was before the one that was associated with the PR that fixed the issue.  But... we're uncertain what that PR is, so it's hard to know.

**Comment by mallenexpensify** [comment] 2023-07-26 03:29
Checking [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1690342052908249).  @tranvantoan-qn , we don't have a process to pay without proof so this is a bit tricky.

**Comment by tranvantoan-qn** [comment] 2023-07-26 03:43
Yes, I understand. But I've seen some exceptions when everyone initially agrees that the bug report is invalid
https://github.com/Expensify/App/issues/21158
https://github.com/Expensify/App/issues/21996

So I hope my cases be considered too (

**Comment by mallenexpensify** [comment] 2023-08-01 00:04
@tranvantoan-qn can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ac3ffaa7bc12de84

You reported a valid bug that was reproducible and now it's not, and no one can identify where/how it was fixed, I asked for help/ 👀 multiple times too.

**Comment by tranvantoan-qn** [comment] 2023-08-01 00:10
@mallenexpensify 
Thank you! I've accepted the offer

**Comment by mallenexpensify** [comment] 2023-08-23 14:07
@mvtglobally can you do one more test to see if this is reproducible? If not, can you please close?  Thx

**Comment by mallenexpensify** [comment] 2023-08-30 01:35
Issue reporter: @tranvantoan-qn paid $250 via Upwork
 
Closing, as mentioned above, this was a valid bug when it was reported and we were unable to determine what fixed it, so compensation was due

**Closed by mallenexpensify** 2023-08-30 01:35 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
