### ISSUE TITLE
[HOLD for payment 2023-02-01] [Hold #13501] Connect Bank Account - Endless loading is shown when navigate to Connect Bank Account 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#13166] opened 2022-11-29 23:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with your testing account
3. Navigate to Setting - Workspace - Workspaces
4. Create an OPEN bank account (this state means the bank account is ready for reimbursement):

- Add Bank Account (On new dot enable Settings > Preferences > Use Secure staging server to hit our staging secure sandbox):

    - Click "Log into your bank"

    - Plaid modal - Choose Wells Fargo (use Bank of America if Wells Fargo is not available)

    - Plaid modal - User Id: user_good

    - Plaid modal - Password: pass_good

    - Plaid modal - Submit

    - Plaid modal - If they request a verification code via mobile sms, enter: credential_good when required

    - Choose an account: Plaid Saving11122XXXXXX111

    - Save & Continue

- Company Information (Enter anything unless specified):

    - Legal Business Name: Alberta Bobbeth Charleson

    - Company website: Enter any valid formatted website

    - Tax ID number: 123456789 ~(any nine digits)~ must be 123456789

    - Industry classification code: 123456 (any six digits)

    - Confirm company is not on list of restricted businesses

- Requestor Information (Enter anything unless specified)

    - First name: Alberta

    - Second name: Charleson

    - Toggle confirmation you are authorized to use company bank account

    - Save & Continue (Note: You will receive an error asking to "Please verify you name and date of birth". Hit "Save & Continue" again without changing any inputs.)

- Onfido (skipped)

- Beneficial Owners

    - Toggle terms and conditions

    - Toggle confirmation that the information provided is true and accurate
   

## Expected Result:
You should see the message "You're all set!" under Connect Bank Account Page

## Actual Result:
Once the modal closes, you're back at New Dot with an infinite loading spinner. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.33-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Internal Team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-11-29 23:08
Please see https://github.com/Expensify/App/issues/12670 for more commentary.

**Comment by JmillsExpensify** [comment] 2022-11-29 23:09
@ctkochan22 I went ahead and proactively assigned you.

**Comment by Luke9389** [comment] 2022-11-30 01:01
Making a quick correction on the description, the TaxID _has to be 123456789_. 

Context: https://expensify.slack.com/archives/C03TQ48KC/p1669423123408509

**Comment by JmillsExpensify** [comment] 2022-11-30 03:36
Thank you! 🙌🏼 Also @Luke9389 apologies if you were taking this one instead. That part is up to ya'll!

**Comment by ctkochan22** [comment] 2022-11-30 04:55
@JmillsExpensify Having a small family emergency that I mentioned earlier this week, so I'm not sure if I can get to this this week

**Comment by nkuoch** [comment] 2022-11-30 13:59
Stealing it from you then @ctkochan22 :)

**Comment by nkuoch** [comment] 2022-12-05 11:27
I couldn't actually reproduce it myself, but hopeful that https://github.com/Expensify/App/pull/13236/files#diff-d8218c24eeebd8e3101efe3934ab8a4478d9bd34f3c8570b58b2fb8f43f31559R71 might fix it

**Comment by kbecciv** [comment] 2022-12-05 23:33
1. Issue is reproduced on any accounts.
2.  username and password kbecciv+1031abb2@gmail.com/Feya86Katya

**Comment by nkuoch** [comment] 2022-12-06 10:10
@kbecciv can you share all the details on how you reproduce it? (like device, browser, credentials, etc..), and record a video of what you're doing?

I'm not getting any infinite loading when trying to reproduce it from your account.

I signed into https://staging.new.expensify.com/ in chrome with [kbecciv+1031abb2@gmail.com](https://www.expensify.com/_support/?supportEmail=kbecciv%2B1031abb2%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2013166&location=_support/)/Feya86Katya

Then went through the flow, and ended up on this step:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/2463975/205881225-d5071c0e-9c5c-429e-80f5-5cc53cbded39.png">


https://user-images.githubusercontent.com/2463975/205881463-b6ceb01b-2fd7-484e-86af-2f9ab0471d83.mp4

**Comment by ctkochan22** [comment] 2022-12-06 17:15
@kbecciv I also can't reproduce

**Comment by kbecciv** [comment] 2022-12-07 21:19
@nkuoch Please check the video in comment https://github.com/Expensify/App/issues/12670#issuecomment-1327724729
Used credentials: kbecciv+1031abb2@gmail.com/Feya86Katya
Web - Chrome browser
IOS app - iPhone 8/14.2

**Comment by laurenreidexpensify** [comment] 2022-12-28 15:15
This is hold on https://github.com/Expensify/App/pull/13501

**Comment by laurenreidexpensify** [comment] 2023-01-11 12:11
Still held on 
- #13501

**Comment by laurenreidexpensify** [comment] 2023-01-30 11:04
@Christinadobrzyn can you handle the payment for C+ review from Santhosh + regression test pls, am still OOO thanks

**Comment by Santhosh-Sellavel** [comment] 2023-01-30 12:46
There is no amount due, I just did some initial review post that I didn't continue as the review would need internal engineers to test this one, thanks!

**Comment by Christinadobrzyn** [comment] 2023-01-31 00:35
Catching up, as Santosh mentioned, it looks like internal eng/QA were the only ones working on this so I don't see any external payment. @nkuoch can you let me know if that's incorrect? I'll work on the regression test.

**Comment by nkuoch** [comment] 2023-01-31 14:36
Correct

**Comment by Christinadobrzyn** [comment] 2023-02-01 01:34
Regression test buddy check - https://expensify.slack.com/archives/C01SKUP7QR0/p1675215255219549

**Comment by Christinadobrzyn** [comment] 2023-02-02 02:06
- Looks like this can be closed as the issue can't be reproduced and it's been in prod for over 7 days. 
- Since there wasn't a C+, no external reporter, and no contributor, there are no external payments for this job
- Closing please feel free to reopen if needed.

**Closed by Christinadobrzyn** 2023-02-02 02:06 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
