### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-05] Category - Blank Category RHP appears when navigating to 1:1 IOU details with /edit/category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28079] opened 2023-09-23 18:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27459
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any 1:1 IOU details page
3. Add /edit/category to the end of the URL
4. Navigate to the modified link
Note that it shows a blank RHP with Category header when Category is not available for 1:1 IOU

## Expected Result:
RHP with not here message will show up

## Actual Result:
A blank RHP with Category header shows up when Category is not available for 1:1 IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1f36d242-8d66-4a28-b42b-b2b96477f097

Production:

https://github.com/Expensify/App/assets/78819774/6bbb5fca-adc4-42e6-9777-1e9c8cff833c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment] 2023-09-23 18:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 App crash when going to /edit/category page

### What is the root cause of that problem?
This issue is regression from [this PR](https://github.com/Expensify/App/pull/27518). In this PR we still use iou propsalthough this prop is removed in [the PR](https://github.com/Expensify/App/pull/27459)

### What changes do you think we should make in order to solve the problem?
We should use selectedCategory instead of iou.category 

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-23 18:44
because this is deploy blocker, I can raise a quick PR with fully testing immediately

**Comment by puneetlath** [comment] 2023-09-24 05:55
I don't think this is a deploy blocker since it requires you to navigate to a URL directly, which a user is unlikely to do. 

@johncschuster @chiragsalian I'm going to take this over for y'all since it relates to wave6.

**Comment by puneetlath** [comment] 2023-09-24 05:55
@waterim @rezkiy37 does one of y'all want to take this?

**Comment by BhuvaneshPatil** [comment] 2023-09-24 06:20
For me the app is failing

https://github.com/Expensify/App/assets/27822551/4624d5e7-4e24-468d-b545-ecc7df3d3ea4


## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As mentioned in issue we are not categories, but while reproducing offline on dev, app crashed for me.
This happened for workspace request as well

### What is the root cause of that problem?
The error here is that, `iou` is being used in `CategoryPicker`, but it is not defined anywhere and we using `category` of that variable which is not defined.
<img width="361" alt="Screenshot 2023-09-24 at 11 46 43 AM" src="https://github.com/Expensify/App/assets/27822551/1867bf4e-7950-4725-9afc-140daeb29a31">

### What changes do you think we should make in order to solve the problem?
My guess here is that we wanted to get IOU from onyx but we are not doing that. To add this
- Add new prop `iou` in `CategoryPicker` (also define that prop `categoryPickerPropTypes`)
- And get the IOU from onyx using `withOnyx`
- adding to this, we shall use `lodashget` to retrieve the properties

### What alternative solutions did you explore? (Optional)

**Comment by rezkiy37** [comment] 2023-09-25 09:28
> @waterim @rezkiy37 does one of y'all want to take this?

Yes, I do.

**Comment by rezkiy37** [comment] 2023-09-25 09:28
Hello, I am Mykhailo from Callstack. I would like to work on this issue.

**Comment by rezkiy37** [comment] 2023-09-25 16:27
Preparing a draft PR - https://github.com/Expensify/App/pull/28165. In a scope of this issue:
- Improving a handling for showing edit categories and tags pages. 
- A small fix of markup for **FullPageNotFoundView** of **EditRequestPage**.
- A minor fix propTypes error of **EditRequestTagPage**.

Having an internal review today.

**Comment by situchan** [comment] 2023-09-25 16:39
@puneetlath can I get assigned here as I fixed part of this GH which was deploy blocker?

**Comment by rezkiy37** [comment] 2023-09-25 17:15
Guys, I've found a problem with a main page content behind RHP. It is already was before. Basically, the app does not show a proper report under behind. I thought that the bug occurs only when we have 2+ tabs, but it is reproducible even with 1 tab. Do we already know about and have an issue?


https://github.com/Expensify/App/assets/57314631/ce331904-c926-4490-91a7-60501f295b1b

**Comment by situchan** [comment] 2023-09-25 17:17
@rezkiy37 what do you mean "tab"?

**Comment by rezkiy37** [comment] 2023-09-25 17:19
> @rezkiy37 what do you mean "tab"?

I meant browser tabs. Kind of when we have in a browser 2+ tabs with the app, it shares a storage. However, the bug occurs even with one tab of the app.

**Comment by situchan** [comment] 2023-09-25 17:23
> > @rezkiy37 what do you mean "tab"?
> 
> I meant browser tabs. Kind of when we have in a browser 2+ tabs with the app, it shares a storage. However, the bug occurs even with one tab of the app.

Correct. You can use Case 2 of QA step in [this PR](https://github.com/Expensify/App/pull/28091).

**Comment by rezkiy37** [comment] 2023-09-29 08:48
The PR - https://github.com/Expensify/App/pull/28165 - is still waiting for review.

**Comment by situchan** [comment] 2023-10-08 14:44
BZ Checklist:

- 1st bug (crash)
This came from 2 PRs which merged simultaneously into main. This is rare case but sometimes happens.
So I'd just say "everyone make sure to pull from main & retest just before merge" and no need regression test.

- 2nd bug (blank page)
This was caught during development of category feature.
As category is still in beta, I think it's early yet to add regression test. And this happened only when browser url is edited manually which is edge case.

**Comment by puneetlath** [comment] 2023-10-11 19:34
@situchan sent you an offer: https://www.upwork.com/nx/wm/offer/27148100

**Comment by situchan** [comment] 2023-10-11 19:43
Not sure how compensation applies here.
First bug fix was requested in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1695531854852179) so I volunteered and raised PR
2nd bug: normal C+ review

**Comment by puneetlath** [comment] 2023-10-11 19:45
Ah, I didn't realize there were two PRs here. I'll update the offer.

**Comment by puneetlath** [comment] 2023-10-11 19:46
Ok updated and paid. Thanks!

**Closed by puneetlath** 2023-10-11 19:46 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
