### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] When overlay modal is open, ESC should close only such modal - attachement or keyboard shortcuts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20615] opened 2023-06-12 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus
3. Click on new room and create new room with any name and workspace and visibility
4. Open settings
5. Click on about
6. Click on View keyboard shortcuts
7. Press ESC to close the popup
## Expected Result:

App should remain in the RHP, only overlay modal is closed.

## Actual Result:

App closes both: the modal and the RHP

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/36e83a56-bcf2-4fc1-9ea4-d2e996832dd5

https://github.com/Expensify/App/assets/43996225/285f0df1-87a5-46ed-86b3-7e5687ef92ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686129642937669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01297649c94dd64e33</li>
        <li>Upwork Job ID: 1668345653092429824</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-12 20:20
@mountiny this is not reproducible on main.

**Comment by petromoldovan** [comment] 2023-06-12 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When seeing the Keyboard shortcuts modal and clicking ESC, user is redirected to the last visited route.

### What is the root cause of that problem?
Key inout event listener is in this modal is registed with the `shouldBubble` parameter set to `true`. It means that when this event is executed, the next in a stack event is executed as well. 

See the last `true` flag in the subscribe method:
https://github.com/Expensify/App/blob/28ad1da059270b91f5fada7bff24cf72f676e11f/src/components/KeyboardShortcutsModal.js#L84-L97

### What changes do you think we should make in order to solve the problem?
I will remove the `shouldBubble` flag from the subscriber function like so:
```
const closeShortcutEscapeModalConfig = CONST.KEYBOARD_SHORTCUTS.ESCAPE;
this.subscribedOpenModalShortcuts.push(
    KeyboardShortcut.subscribe(
        closeShortcutEscapeModalConfig.shortcutKey,
        () => {
            ModalActions.close();
            KeyboardShortcutsActions.hideKeyboardShortcutModal();
        },
        closeShortcutEscapeModalConfig.descriptionKey,
        closeShortcutEscapeModalConfig.modifiers,
        true
    ),
);
```

Result:

https://github.com/Expensify/App/assets/15109844/1da96642-fc7a-4451-b97b-c6ac90e732a5




### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment] 2023-06-12 23:25
Thanks for the proposals

The react-freeze is required to ensure the browser history works as expected on web when you click back, we have decided in the predesign we will always push new pages to simplify the logic behind navigation and limit bugs stemming from it

@WoLewicki @adamgrzybowski can you please here review these proposals cc @aimane-chnaif

**Comment by mountiny** [comment] 2023-06-16 09:22
I believe this PR https://github.com/Expensify/App/pull/20815 fixed this issue.

@aimane-chnaif can you repro in main?

**Comment by mountiny** [comment] 2023-06-16 10:39
> On main, Esc closes all modals, so RHP as well.

This is still kinda discussed. I think when it comes to overlay modals, ESC should only close it but RHP should stay

**Comment by mountiny** [comment] 2023-06-19 12:53
Checking if this is still reproducible

**Comment by mountiny** [comment] 2023-06-19 21:30
@aimane-chnaif @petromoldovan @allroundexperts I have update the issue body.

The expected behaviour with overlay modals like attachment modal or the keyboard shortcut modal  is that only the modals should be closed when ESC is pressed. It seems like the keypress propagates down to the navigation and it closes the RHP too but that should not be the case if the modal is open.

cc @adamgrzybowski @WoLewicki

**Comment by mountiny** [comment] 2023-06-20 15:26
@WoLewicki has originally worked on the refactor so their task now is to fix any follow ups, assigning him to this issue as PR is up and ready.

**Comment by WoLewicki** [comment] 2023-06-20 16:36
Commenting :rocket:

**Comment by mountiny** [comment] 2023-06-20 19:22
PR got merged.

**Comment by mountiny** [comment] 2023-07-04 19:03
@mallenexpensify No regression test needs to be added here I think, its been follow up to the navigation refactor.

Payments please:

@dhanashree-sawant $250
@aimane-chnaif $1000

**Comment by dylanexpensify** [comment] 2023-07-07 08:14
I'll tackle this one today! @dhanashree-sawant and @aimane-chnaif can you apply via the link [here](https://github.com/Expensify/App/issues/20615#issuecomment-1587985790)? 🙇‍♂️

**Comment by dhanashree-sawant** [comment] 2023-07-07 08:21
Thanks @dylanexpensify, if possible, can you invite me to the job?

**Comment by dylanexpensify** [comment] 2023-07-07 13:50
@dhanashree-sawant invited!

**Comment by dylanexpensify** [comment] 2023-07-07 13:50
Bump @aimane-chnaif 🙇‍♂️

**Comment by dhanashree-sawant** [comment] 2023-07-07 13:53
Many thanks @dylanexpensify ! I have accepted the invite

**Comment by dylanexpensify** [comment] 2023-07-07 17:08
offer sent!

**Comment by dylanexpensify** [comment] 2023-07-10 09:37
@aimane-chnaif are you being paid in newDot?

**Comment by mallenexpensify** [comment] 2023-07-12 01:34
@aimane-chnaif paid, closing!

**Closed by mallenexpensify** 2023-07-12 01:34 UTC
Labels: External, Daily, Awaiting Payment, Bug
