### ISSUE TITLE
[$1000] Web - New Group - Focus not taken to search bar when focused on first/last result and press UP/DN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22856] opened 2023-07-14 00:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions: user has already opened the test URL and logged in an account with a lot of active conversations.

1. Click on the green "+" icon on the home screen
2. Click "New Group"
3. Use the arrow keys to traverse the list of results

## Expected Result:
There should be a notable difference in expected behavior between this page and the New Chat Page in that the search bar is one of the focusable elements
When focused on the first / last result and press ArrowUp / ArrowDown the focus should be taken to the search bar. None of the list elements should be highlighted

## Actual Result:
There is no notable difference in actual behavior between this page and the New Chat Page in that the search bar is not one of the focusable elements
When focused on the first / last result and press ArrowUp / ArrowDown the focus is not taken to the search bar. An element of the list is always highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.5
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

https://expensify.testrail.io/index.php?/tests/view/3526979

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/92d79350-ced7-495a-bdaf-dd9c1d046cf4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017eb5a64464db0ef7</li>
        <li>Upwork Job ID: 1679799300293820416</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 25994732</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-14 00:55
I think we need to confirm if this is really the expected behavior.

**Comment by conorpendergrast** [comment] 2023-07-14 10:18
@s-alves10 I agree

**Comment by conorpendergrast** [comment] 2023-07-14 10:25
Ah, easy. From our regression testing suite ([linked above](https://expensify.testrail.io/index.php?/tests/view/3526979)):  

> Verify when focused on the last result and press ArrowDown the focus is taken to the search bar. None of the list elements should be highlighted.
> Verify when focused on the first result and press ArrowUp the focus is taken to the search bar. None of the elements should be highlighted.

<img width="1159" alt="image" src="https://github.com/Expensify/App/assets/5802477/67908fb8-b0d6-4374-9d1b-84bf1cc46349">

**Comment by ishpaul777** [comment] 2023-07-14 11:27
> label [Jul 14, 2023](#event-9820455712)

Is this the expected behavior throughout the application when using the search and option list? ex.- on pages like the workspace members invite page, new chat, and new group.
Also correct me in case I got it wrong, The search input is automatically focused when we are on any of these pages until intentionally unfocused. So, let's say we are on the last list item and press the arrow key down. Are we then focused on the search input again? And if we press the down key again, is the expected behavior to focus on the first list item while the search bar is unfocused?

**Comment by alitoshmatov** [comment] 2023-07-14 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - New Group - Focus not taken to search bar when focused on first/last result and press UP/DN
### What is the root cause of that problem?
We are not handling this logic in the app

### What changes do you think we should make in order to solve the problem?
We need to keep track of focus state of input here 
https://github.com/Expensify/App/blob/804b5be014d8b733ec3f1729d4d18b72bc013ab5/src/components/OptionsSelector/BaseOptionsSelector.js#L295
We can introduce new state variable called `isTextInputFocused` and set it true and false in `onFocus` and `onBlur` of element.

Then in this function we should add some logic to check if we are in the last element and going to the first one or we are in the first element and going to the last one, which means we are pressing down in the last item or pressing up in the first item.
https://github.com/Expensify/App/blob/804b5be014d8b733ec3f1729d4d18b72bc013ab5/src/components/OptionsSelector/BaseOptionsSelector.js#L224-L226
Then we should check if text input is focused if yes we do nothing, and app behaves normally as it does now.
If text input is not focused, then we can focus the text input like this: 
```javascript
if (
            ((this.state.focusedIndex === this.state.allOptions.length - 1 && index === 0) || (this.state.focusedIndex === 0 && index === this.state.allOptions.length - 1)) &&
            this.state.isTextInputFocused === false
        ) {
            this.textInput.focus();
        }
``` 
This way the text input gets focused. I see that always one item is focused in option selector, that is way we can do one of the following:
1. When pressed down on the last element we can focus text input and change focused option the first one
2. We can leave the focused item in the last one but focus the text input
3. We can focus the text input and lose focus for options by setting `focusedIndex` to -1

### What alternative solutions did you explore? (Optional)

**Comment by snwork89** [comment] 2023-07-14 11:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When focused on the first / last result and press ArrowUp / ArrowDown the focus should be taken to the search bar. None of the list elements should be highlighted.

### What is the root cause of that problem?
In ArrowKeyFocusManager pressing downArrow on last element , upArrow on first element these cases are not handled to focus on textinput(searchbox)

### What changes do you think we should make in order to solve the problem?

- creating new method focusTextInput ,this method first focus the textInput and set focusedIndex to -1 because when textinput is focused no element should be focused on list. 
- passing focusTextInput as props and call as per below.
 onDownArrowKey
    if(this.props.focusTextInput &&this.props.focusedIndex==this.props.maxIndex){
            this.props.focusTextInput();
            return;
        }
onUpArrowKey
    if(this.props.focusTextInput && this.props.focusedIndex==0){
            this.props.focusTextInput();
            return;
        }





### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by himanshuragi456** [comment] 2023-07-14 12:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When focused on the First or Last result moving UP/DOWN should add focus to the search input instead of moving to TOP/BOTTOM of the list.

hidden issue: search input is not losing focus when the focus is on any result.

### What is the root cause of that problem?

The unhandled focus of search input, need to re-think how the focus should flow.

### What changes do you think we should make in order to solve the problem?

- consider the search input as a part of the result list, i.e. Only one of all can have focus at a time(focusing on any result should remove focus from the search input).

### What alternative solutions did you explore? (Optional)

NO

**Comment by himanshuragi456** [comment] 2023-07-14 12:07
Contributor details
Your Expensify account email: hirehimanshuragi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01386406c17131aa96

**Comment by ishpaul777** [comment] 2023-07-14 12:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- When focused on the First or Last result moving UP/DOWN should add focus to the search input instead of moving to TOP/BOTTOM of the list.

What is the root cause of that problem?
The Case  to focus on searchbar when on the first / last result and press ArrowUp / ArrowDown is not handled

What changes do you think we should make in order to solve the problem?
We need to modfify updateFocusedIndex
```
 updateFocusedIndex(index) {
        // if current focussed index is last index this.textInput.focus() then setcurrent focussed index to -1
        // if current focus index is -1 set it to zero
        // else 
        this.setState({focusedIndex: index}, () => this.scrollToIndex(index));
}
```

What alternative solutions did you explore? (Optional)
NO

**Comment by mehvash-Khan** [comment] 2023-07-16 21:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that input search bar remains focused when arrow key is being used to traverse through all the elements
 including last and first element. The search bar should only be focused when arrow key up is used when current is first element and arrow key down is used when current is last element. For the rest of the elements/groups, search bar should be blurred.

### What is the root cause of that problem?
The search bar is not considered as part of the items being traversed through the focused index.

### What changes do you think we should make in order to solve the problem?
Pass an additional prop `startIndex` to the component `ArrowKeyFocusManager`. This prop will help the component get the start index for the list. We will pass value of `startIndex` prop  to -1. To make sure that this additional prop does not affect any other functionality of component, we will set its default value to `0`.

In `onArrowUpKey()` we can change the comparison from `this.props.focusedIndex > 0` to `this.props.focusedIndex > this.props.startIndex` and similarly in `onArrowDownKey()` we can set the focused index to be `this.props.startIndex` instead of `0` when the current focused element is the last one.

Now props `startIndex` is passed with value `-1`. This would lead to the expected behaviour i.e whenever our current element is 1st in the list and user presses up key, our focused index is `-1`. Similar is the case when current element is the last element and user presses arrow down key. The focused index being `-1` represents the input search bar being focused as shown below.

Finally we will need to make minor update in function ` updateFocusedIndex(index)`. Please refer below code

```js
 updateFocusedIndex(index) {
        if(index === -1)
            this.textInput.focus();
        else
            this.textInput.blur();
        this.setState({focusedIndex: index}, () => this.scrollToIndex(index === -1 ? 0 : index));
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-07-18 17:40
Is there something to suggest that this case isn't correct? In general I think that we can rely on the test cases being an accurate representation of the expected behaviour

**Comment by himanshuragi456** [comment] 2023-07-19 00:17
https://github.com/Expensify/App/issues/10705#issuecomment-1237751307
I believe this should be the Expected behavior because as a user someone would prefer to have just one active state, instead of different states for input and results. It will only create confusion for the user.
@aimane-chnaif @conorpendergrast

**Comment by himanshuragi456** [comment] 2023-07-21 06:09
@conorpendergrast @aimane-chnaif how can we discuss and proceed with this issue? It's been quite delayed

**Comment by conorpendergrast** [comment] 2023-07-21 12:42
I'll bring this to Slack today to discuss if we still want the same behaviour as in the regression test

**Comment by conorpendergrast** [comment] 2023-07-21 15:45
Here we go: https://expensify.slack.com/archives/C01GTK53T8Q/p1689954073865489

**Comment by conorpendergrast** [comment] 2023-07-26 13:51
Still discussing [via Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689954073865489)

**Comment by conorpendergrast** [comment] 2023-07-31 08:58
@aimane-chnaif From discussing [via Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689954073865489), we agreed that we can fix to match the regression test [as I proposed here](https://github.com/Expensify/App/issues/22856#issuecomment-1635652183).

**Comment by conorpendergrast** [comment] 2023-07-31 08:58
Sorry it took me a while to get that back here!

**Comment by conorpendergrast** [comment] 2023-08-03 11:59
@aimane-chnaif No review? :Sadpanda:

**Comment by mehvash-Khan** [comment] 2023-08-05 18:27
Hi @aimane-chnaif ,

Did you get a chance to review my [proposal](https://github.com/Expensify/App/issues/22856#issuecomment-1637195740)?

**Comment by conorpendergrast** [comment] 2023-08-07 18:44
From internal channel, reassigning to @situchan as C+

**Comment by situchan** [comment] 2023-08-09 11:50
@himanshuragi456 thanks for your proposal. Your provided solution is not enough to handle all possible cases.

To contributors: please share demo video of Search, New group, Timezone pages which represent single selection, multiple selection, radio selection.
Review cases:
- initial selection - should be only search
- manually focus on input while focusing any result
- blur input and then press arrow keys
- press arrow keys when focused on first/last result (OP)
- press arrow keys when no result
- automatic scroll to initially selected result (Timezone page only)

**Comment by situchan** [comment] 2023-08-09 12:14
yes, I expect those behaviors

**Comment by ishpaul777** [comment] 2023-08-09 13:18
## Proposal 
[updated](https://github.com/Expensify/App/issues/22856#issuecomment-1635785816)

**Comment by ishpaul777** [comment] 2023-08-09 13:28
so you are saying i copied @himanshuragi456

**Comment by situchan** [comment] 2023-08-10 07:01
@himanshuragi456 thanks for updated proposal. So you are considering search input index as -1, right?
And from your last video for `automatic scroll to initially selected result (Timezone page only)`, both search input and result item are still highlighted.

**Comment by situchan** [comment] 2023-08-10 07:11
I was expecting this:

<img width="372" alt="Screenshot 2023-08-10 at 1 10 00 PM" src="https://github.com/Expensify/App/assets/108292595/dae87f58-e937-417a-8c55-6204fa7e2ae5">

**Comment by situchan** [comment] 2023-08-14 04:03
@himanshuragi456 there's still case where both search input is focused and result item is highlighted.


https://github.com/Expensify/App/assets/108292595/6ebd79c5-c96f-4166-95c1-e5a972f4ecc5

**Comment by situchan** [comment] 2023-08-14 04:10
> @situchan fixing now, where should I keep focus in this case? on the result or on search? I think it should be on result

If we fix the root cause, the issue will be gone. If you go to another tab and come back, you will see result item is unhighlighted and search is still focused. So I vote to focus on search for now which is current behavior.
And we'll improve this in https://github.com/Expensify/App/issues/22812 after this issue is fixed.

**Comment by situchan** [comment] 2023-08-14 04:11
Note that search focus status keeps same. So if focused, focus but if not focused, no need to focus

**Comment by situchan** [comment] 2023-08-14 04:28
@himanshuragi456 please explain solution with plain English as in contributing guideline.
You can propose something like this:
_Consider the search input as a part of the result list by setting search index to -1, i.e. Only one of all can have focus at a time(focusing on any result should remove focus from the search input)
When arrow index reaches last result (first result) and press down (up) again, focus on input, otherwise blur input
..._

Can you update your proposal to avoid code diff?

**Comment by situchan** [comment] 2023-08-14 04:47
@himanshuragi456's [updated proposal](https://github.com/Expensify/App/issues/22856#issuecomment-1635767653) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment] 2023-08-15 17:58
Hey sorry, I know I'm coming into this late, but this really doesn't feel like a bug to me. I think the current behavior where it loops around to the front/back of the list feels more correct. You can always keep typing in the input, even while using the arrow keys to scroll, so focusing the input feels weird to me. Slack and Discord also work the way NewDot currently does. 

Are we sure we should change this behavior?

**Comment by situchan** [comment] 2023-08-15 17:59
@puneetlath can you please chime in [this discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1689954073865489)?

**Comment by conorpendergrast** [comment] 2023-08-16 09:06
We're going to HOLD this based on [further discussion in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692134281664219?thread_ts=1689954073.865489&cid=C01GTK53T8Q), and likely close it out.

**Comment by conorpendergrast** [comment] 2023-08-16 09:11
Internal compensation discussion [started here](https://expensify.slack.com/archives/C01SKUP7QR0/p1692177026202559). Before I close this out, I'll need to create an issue to change the regression test

**Comment by conorpendergrast** [comment] 2023-08-21 19:27
From [that internal thread,](https://expensify.slack.com/archives/C01SKUP7QR0/p1692177026202559) we agreed on partial compensation. The typical rate for that is at 25% of job rate. Here, that will be 25% of the $1000, for @himanshuragi456.

**Comment by conorpendergrast** [comment] 2023-08-21 19:28
@himanshuragi456 Could you please apply to [this job](https://www.upwork.com/jobs/~017eb5a64464db0ef7) for that?

**Comment by situchan** [comment] 2023-08-21 19:56
Is it applied to C+ as well?

**Comment by conorpendergrast** [comment] 2023-08-22 08:04
@situchan In this case, the impression I had was that you hadn't invested quite as much effort here. Can you confirm if that's the correct or an incorrect impression? 

@himanshuragi456 Thank you!

**Comment by situchan** [comment] 2023-08-22 08:21
It took efforts for me to review & test proposals and it already [reached](https://github.com/Expensify/App/issues/22856#issuecomment-1676670639) C+ approval stage.

Similar case: https://github.com/Expensify/App/issues/23201#issuecomment-1686640754. That console error fix was even much simpler than this one.

**Comment by conorpendergrast** [comment] 2023-08-25 12:59
@himanshuragi456 Yes - requirements will sometimes change (eg: we'll revise the behaviour we expect, or decide that something is not worth fixing given other constraints). In those limited circumstances, we'll pay a portion of the bounty (typically 25%). 

@situchan That's a fair point, thank you for the context. I'll pay 25% to you too, to match that. 

I'll pay those out once the offers are accepted.

**Comment by conorpendergrast** [comment] 2023-08-25 13:17
Regression test update issue created: https://github.com/Expensify/Expensify/issues/311312

**Comment by conorpendergrast** [comment] 2023-08-25 19:39
Payouts due:

Issue Reporter: N/A - applause

- [ ] Contributor: $250 @himanshuragi456 
- [x] Contributor+: $250 @situchan 

Eligible for 50% #urgency bonus? No - N/A

Upwork job is [here](https://www.upwork.com/jobs/~017eb5a64464db0ef7).

**Comment by conorpendergrast** [comment] 2023-08-25 19:42
All done here, thank you everyone - I appreciate your understanding as we moved to get to the right solution for today.

**Closed by conorpendergrast** 2023-08-25 19:42 UTC
Labels: Daily, Bug
