### ISSUE TITLE
[$500] Web - Workspace - User does not navigates to Admin room when create new Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32842] opened 2023-12-11 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Login with an account with no workspace
3. Create a workspace via the FAB button

## Expected Result:
User should be navigated to the #admins room

## Actual Result:
User does not navigates to Admin room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cf845c54-6234-47ec-a5af-f63601ed8262

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc9b8851006df053</li>
        <li>Upwork Job ID: 1734267218774921216</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28121336</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2023-12-11 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace - User does not navigates to Admin room when create new Workspace

### What is the root cause of that problem?
There is not navigation to admins room after clicking New Workspace

### What changes do you think we should make in order to solve the problem?
We should add navigation to admin in `createWorkspaceWithPolicyDraftAndNavigateToIt` method

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2023-12-13 21:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand revolves around users not being directed to the Admin room upon creating a new workspace.

### What is the root cause of that problem?
The crux of the matter lies in the absence of redirection logic after crafting a workspace on the [WorkspaceInitialPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInitialPage.js#L126). The critical sequence involves drafting, navigating to the initial workspace page, and finalizing the workspace creation. The absence to redirect to the #admins room is at the heart of the problem.

### What changes do you think we should make in order to solve the problem?
I suggest we start by modifying the [savePolicyDraftByNewWorkspace](https://github.com/Expensify/App/blob/main/src/libs/actions/App.ts#L365) function in `App.ts`. The adjustment involves aligning it with the existing behavior in the [createWorkspace](https://github.com/Expensify/App/blob/main/src/libs/actions/Policy.js#L1153) function in `Policy.js`, ensuring a consistent approach to obtaining the `adminsChatReportID` after workspace creation.
```
function savePolicyDraftByNewWorkspace(policyID?: string, policyName?: string, policyOwnerEmail = '', makeMeAdmin = false) {
    return Policy.createWorkspace(policyOwnerEmail, makeMeAdmin, policyName, policyID);
}
```

Furthermore, in the `WorkspaceInitialPage.js` component, a delay is introduced after calling [App.savePolicyDraftByNewWorkspace](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInitialPage.js#L126) before navigating to the Admins Room. This delay ensures the user has adequate time to witness the workspace creation before redirection.
```
...
const policyDraftId = lodashGet(props.policyDraft, 'id', null);
if (!policyDraftId) {
    return;
}
const adminsChatReportID = App.savePolicyDraftByNewWorkspace(props.policyDraft.id, props.policyDraft.name, '', props.policyDraft.makeMeAdmin);

// After a small delay, navigate to Admins Room
setTimeout(() => {
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(adminsChatReportID));
}, 2000); // Adjust the delay time as needed
```

POC

https://github.com/Expensify/App/assets/95647348/0a124b33-a44e-4c1e-b386-22798bb2f4f6

### What alternative solutions did you explore? (Optional)
An alternative route involves integrating navigation directly to the `#admins` room after [createDraftInitialWorkspace](https://github.com/Expensify/App/blob/main/src/libs/actions/App.ts#L343). This approach bypasses the intermediary step through `WorkspaceInitialPage`, simplifying the process.
```
function createWorkspaceWithPolicyDraftAndNavigateToIt(policyOwnerEmail = '', policyName = '', transitionFromOldDot = false, makeMeAdmin = false) {
...
    const adminsChatReportID = savePolicyDraftByNewWorkspace(policyID, policyName, '', makeMeAdmin);

    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(adminsChatReportID));
...
}
```
https://github.com/Expensify/App/assets/95647348/d259de91-0b3b-4f53-b196-af2d6b8af7b0

Note:I believe it would be a better approach if we can redirect to Workspace Welcome page instead of `#AdminChat`.

**Comment by allstarsmen** [comment] 2023-12-18 02:50
@conorpendergrast @thesahindia I don't think this is a bug.

Based on [this comment in issue 28573](https://github.com/Expensify/App/pull/28573#issuecomment-1778978323), this is an expected behavior.

**Comment by conorpendergrast** [comment] 2023-12-19 21:17
@kbecciv did this come from a specific regression test? If so, could you link to that? Otherwise, I agree that this isn't expected behaviour. I'll close for now, but am open to correction!

**Comment by kbecciv** [comment] 2023-12-20 18:52
@conorpendergrast This came from TR here https://expensify.testrail.io/index.php?/tests/view/4055660

**Comment by conorpendergrast** [comment] 2024-01-08 16:25
Sorry, I'm back from OoO now. 
I've checked the following:

- The TestRail case: https://expensify.testrail.io/index.php?/tests/view/4055660
- Our request to create that test https://github.com/Expensify/Expensify/issues/304920
- The issue that request comes from: https://github.com/Expensify/App/issues/21408


The case is: 

1. Login with an account with no workspace (or delete all workspaces)
2. Create a workspace via the FAB button
3. Web/Desktop - Verify the workspace settings are open in the right hand modal
4. Web/Desktop - Verify the user is navigated to the #admins room (with the RHM open)
5. Mobile - Verify the #admin room is not displayed
6. Mobile - Verify the user is navigated to the Workspace settings

Importantly, in step 4, the RHM is the one references in step 3 (That should be in the foreground, while the chat is in the background and out of focus). 

Assuming that this is still reproducible, this is indeed a bug to be fixed. I'll check reproduction steps next today!

**Comment by conorpendergrast** [comment] 2024-01-08 20:22
Ok, I've confirmed this and reproduced now via a test account (20303b@conorpendergrast.com). The failed step was indeed that the workspace admins chat wasn't opened in the background (when the RHP opened the workspace's settings). 

I think we should indeed fix this. It has been open a while, but that was due to my being OoO. So I'll keep this external with help wanted

<img width="1419" alt="image" src="https://github.com/Expensify/App/assets/5802477/7aa15ae8-f1e8-4e81-82e7-80beb6685a8e">

**Comment by conorpendergrast** [comment] 2024-01-08 20:30
[Checking](https://expensify.slack.com/archives/C036QM0SLJK/p1704745801270219) (internal channel) which wave to add this to

**Comment by conorpendergrast** [comment] 2024-01-17 13:13
Bumping my question in Slack

**Comment by zanyrenney** [comment] 2024-01-17 13:18
apologies about the silence here @conorpendergrast - appreciate the bump.

**Comment by conorpendergrast** [comment] 2024-01-19 20:24
@thesahindia Oh, oops, I just spotted that there are two proposals above to review!

**Comment by brunovjk** [comment] 2024-01-22 20:00
Hi @conorpendergrast, any feedback on my [proposal](https://github.com/Expensify/App/issues/32842#issuecomment-1854754547)? Thanks.

**Comment by conorpendergrast** [comment] 2024-01-25 11:40
[Checking](https://expensify.slack.com/archives/C02NK2DQWUX/p1706182847987539)!

**Comment by conorpendergrast** [comment] 2024-01-25 11:41
Assigning @DylanDylann as C+, so adding the labels back

**Comment by shahinyan11** [comment] 2024-01-25 18:44
@conorpendergrast Should I expect feedback about my proposal or no ?

**Comment by conorpendergrast** [comment] 2024-01-25 20:14
@shahinyan11 Yeah; @DylanDylann has taken over as Contributor+. First task is to review all proposals!

**Comment by DylanDylann** [comment] 2024-01-26 04:21
@conorpendergrast Thanks for clearing the step [here](https://github.com/Expensify/App/issues/32842#issuecomment-1881411091) In step 1
> Login with an account with no workspace (or delete all workspaces)
You mean that we only should navigate to the admin room in the background if the user creates **the first** workspace, right?
In case, the current account has some workspaces and the user creates one more workspace. Do we want to navigate to the admin room in the background?

**Comment by shahinyan11** [comment] 2024-01-26 07:25
## Proposal
[Updated](link to proposal)

**Comment by conorpendergrast** [comment] 2024-01-26 09:58
@DylanDylann That's a great clarifying question. Thinking through it again, I think that creating any workspace should navigate to that new workspace's room in the background (not just a first workspace). I'll check my thinking on that in the wave's Slack channel, and will come back to confirm the correct behaviour

**Comment by conorpendergrast** [comment] 2024-01-26 10:27
Ah, I forgot that we're overhauling the new workspace flow entirely at the moment. So, this is not worth fixing! Closing out, thanks very much for your time everyone!

**Closed by conorpendergrast** 2024-01-26 10:27 UTC
Labels: External, Daily, Help Wanted, Bug
