### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] Web - 2FA - Authentication code value is not accepted when put Space and than correct it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35947] opened 2024-02-06 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User should have 2-FA enabled

1.Log in to staging.new.expensify.com
2. Enter email address from precondition
3. Navigate to email and locate the magic link - change to staging if needed
4. Open an new tab and navigate to the staging link
5. Verify the 2FA required page is displayed
6. Navigate back to the original tab
7. Click on "Use recovery code" to change to "Use 2 factor authentication code"
8. Enter authentication code with space at the beginning
9. Click Sign in
10. Error message will appear
11. Erase the space
12. Click Sign in

## Expected Result:
Error should dismiss and user should successfully log in

## Actual Result:
Error message reappears and user can not log in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/216372e9-8dba-475c-8f37-2ab9f23c12e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d55723e0e20585e</li>
        <li>Upwork Job ID: 1754943906473668608</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2024-02-07 11:06
@GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/35947#issuecomment-1930611212) Looks good to me, trimming the value makes sense.
🎀 👀 🎀 C+ Reviewed!

**Comment by getusha** [comment] 2024-02-07 13:55
@neonbhai after removing `maxLength` how can we ensure we allow the right length for the input.

**Comment by getusha** [comment] 2024-02-08 17:25
thanks everyone! The [proposal](https://github.com/Expensify/App/issues/35947#issuecomment-1930627652) from @neonbhai looks good to me the RCA is correct and the solution works. it would be great if we could have a condition to check the trimmed length of the value and set it accordingly in `onTextInput` if possible @neonbhai 

🎀 👀 🎀 C+ Reviewed!

**Comment by puneetlath** [comment] 2024-02-14 17:02
@neonbhai how's it going?

**Comment by getusha** [comment] 2024-02-20 08:49
@neonbhai any issues i can help with?

**Comment by puneetlath** [comment] 2024-03-22 15:49
@getusha friendly reminder about the checklist so that we can pay on Monday.

**Comment by puneetlath** [comment] 2024-03-25 15:03
@neonbhai has been paid. Still waiting on the checklist for @getusha

**Comment by getusha** [comment] 2024-03-25 15:12
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23390/
- [x] [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23390/files#r1537753571
- [x] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- [x] [@getusha] Determine if we should create a regression test for this bug. **No, seems like a very minor bug and i don't think we need we need a regression test for it.**
- [x] [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/a**

**Comment by getusha** [comment] 2024-03-25 15:13
@puneetlath apologies, I forgot about the checklist despite your reminder. 😄

**Comment by puneetlath** [comment] 2024-03-25 16:51
No worries! Thanks for taking care of it. 

It looks like it didn't auto-offer you for some reason. Offer is here: https://www.upwork.com/nx/wm/offer/101569210

Please ping me on the issue when you've accepted

**Comment by getusha** [comment] 2024-03-25 16:55
@puneetlath accepted.

**Comment by puneetlath** [comment] 2024-03-25 16:57
All paid. Thanks everyone!

**Closed by puneetlath** 2024-03-25 16:57 UTC
Labels: External, Weekly, Awaiting Payment, Bug
