### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Workspace name in Distance request flow is wrong color

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33976] opened 2024-01-04 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.22-0
**Reproducible in staging?:**  yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704218630440349

## Action Performed:
Create a distance request, send it to a workspace

## Expected Result:
The workspace name under the "To" label should use our standard text color.

## Actual Result:
The workspace name under the "To" field uses our supporting text color

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-04 at 1 29 55 PM](https://github.com/Expensify/App/assets/38435837/ec0bb16b-0424-4a28-8814-3d7bb1ea4a1f)

![IMG_8478](https://github.com/Expensify/App/assets/38435837/7ad63166-64d7-408b-ac8f-4b746991937c)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015105603136672151</li>
        <li>Upwork Job ID: 1742979127739854848</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28130781</li>
<li>Tony-MK | Contributor | 28130782</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2024-01-04 19:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace name in Distance request flow is wrong color 
### What is the root cause of that problem?
Because that workspace is disabled [here](https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L441)
So Workspace name in Distance request flow is wrong color 
### What changes do you think we should make in order to solve the problem?
Option1: We can make `isDisabled` as false for workspace.
Option2: we can keep `isDisabled` as true for workspace and only change disable color of workspace as default text color
### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2024-01-04 20:28
.

**Comment by Tony-MK** [comment] 2024-01-04 20:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The workspace name in the Distance request flow is the wrong color

### What is the root cause of that problem?

The following condition is true because the `participant.accountID` is zero.

https://github.com/Expensify/App/blob/5b0ceb25e746e9d7f2952cad8c6fa367b3638489/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L441


Therefore, the `OptionRow` component applies the `isDisbaled` style to the `displayNameStyle`. Hence, any workspace will look different from the rest of the items on the menu.

https://github.com/Expensify/App/blob/5b0ceb25e746e9d7f2952cad8c6fa367b3638489/src/components/OptionRow.tsx#L131

### What changes do you think we should make in order to solve the problem?


Just like how `IOURequestStepConfirmatio` uses the value of `participant.isPolicyExpenseChat` to get the `policyExpenseChat`, we should replicate it in `MoneyTemporaryForRefactorRequestConfirmationList` for consistency.

https://github.com/Expensify/App/blob/5b0ceb25e746e9d7f2952cad8c6fa367b3638489/src/pages/iou/request/step/IOURequestStepConfirmation.js#L138

Therefore, we can change the line to bring the issue to something similar to the code below.

```
isDisabled: !participant.isPolicyExpenseChat && ReportUtils.isOptimisticPersonalDetail(participant.accountID)
```


### What alternative solutions did you explore? (Optional)

We could also use the prop `isPolicyExpenseChat`,  instead of using `!participant.isPolicyExpenseChat`. It is already passed to the `MoneyTemporaryForRefactorRequestConfirmationList` component by `IOURequestStepConfirmation`


** Result **
![Result](https://github.com/Expensify/App/assets/22982173/a64fc5c1-6083-41eb-806d-9b12097bfd42)

**Comment by shawnborton** [comment] 2024-01-05 08:27
Yeah, something to consider is that I don't think we need to make the workspace name appear disabled.

**Comment by Tony-MK** [comment] 2024-01-08 15:08
@ntdiary Thanks for reviewing my proposal. 

I have seen your good comments on my proposal but have not accepted it. 

Is there anything I to add or change to my proposal? 

Thanks

**Comment by Tony-MK** [comment] 2024-01-08 16:17
@ntdiary Thanks for reviewing my proposal. I have updated my proposal. Kindly, have a look.

**Comment by Tony-MK** [comment] 2024-01-10 01:54
Thanks for reviewing my proposal and also for the feedback, @ntdiary. 

I have retested and updated my [proposal](https://github.com/Expensify/App/issues/33976#issuecomment-1877719712) based on your comments from https://github.com/Expensify/App/issues/33976#issuecomment-1881122160. 

It works like a charm. Thank you. 😄

**Comment by JmillsExpensify** [comment] 2024-01-14 09:14
Proposals and on-going discussion still in progress.

**Comment by Tony-MK** [comment] 2024-01-20 00:16
Hey @ntdiary, I updated my [proposal](https://github.com/Expensify/App/issues/33976#issuecomment-1877719712) to try to solve the back button issue. 

However, I would appreciate it if you could answer these two questions.

1) Did you suggest removing the `shouldNavigateToTopMostReport` prop from the `HeaderWithBackButton` component and handling it from the `ReportDetailsPage` and `FlagCommentPage`?

2) When a user tries to make a new money request, should the app navigate the user to the previous money request or delete it and create a new one?

**Comment by Tony-MK** [comment] 2024-01-20 00:17
Hey @ntdiary, I updated my [proposal](https://github.com/Expensify/App/issues/33976#issuecomment-1877719712) to solve the back button issue. 

However, I would appreciate it if you could answer these two questions.

1) Are you suggesting removing the `shouldNavigateToTopMostReport` prop from the `HeaderWithBackButton` component and handling it from the `ReportDetailsPage` and `FlagCommentPage`?

2) When a user tries to make a new money request, should the app navigate the user to the previous money request or delete it and create a new one?

**Comment by JmillsExpensify** [comment] 2024-01-24 03:21
Still discussing proposals

**Comment by Tony-MK** [comment] 2024-01-24 22:30
> @Tony-MK, nope, I'm just considering removing this line of code because it has a higher priority, it would prevent us from navigating back to the confirmation page:

I updated the proposal to determine whether the `backTo` route parameter is available and sets `shouldNavigateToTopMostReport` to `false`. 

> I'm not exactly sure how this problem might impact the solution. Could you provide further clarification?



This is because if the user navigates the workspace `ReportDetailsPage` he/she can still press the "+" button and create another split or money request. 

How will we handle this case? 

Should we navigate the user back to the `MoneyTemporaryForRefactorRequestConfirmationList`?.

Is that clear? 🤔 

If this is not clear enough, I can provide a video demonstration?

**Comment by Tony-MK** [comment] 2024-01-24 22:31
> @Tony-MK, nope, I'm just considering removing this line of code because it has a higher priority, it would prevent us from navigating back to the confirmation page:

@ntdiary, I updated the proposal to determine whether the `backTo` route parameter is available and sets `shouldNavigateToTopMostReport` to `false`. 

> I'm not exactly sure how this problem might impact the solution. Could you provide further clarification?



This is because if the user navigates the workspace `ReportDetailsPage` he/she can still press the "+" button and create another split or money request. 

How will we handle this case? 

Should we navigate the user back to the `MoneyTemporaryForRefactorRequestConfirmationList`?

Is that clear? 🤔 

If this is not clear enough, I can provide a video demonstration.

**Comment by Tony-MK** [comment] 2024-01-26 00:28
My apologies, @ntdiary, I misunderstood.

Do you think this is a reasonable fix?

```
shouldNavigateToTopMostReport={!props.route.params.backTo}
onBackButtonPress={() => {
 Navigation.goBack(props.route.params.backTo, !props.route.params.backTo)}
}
```

Also, instead of doing the above change in the `ReportDetailsPage`,  should we change the `HeaderWithBackButton` because it will prioritize the `backTo` over `shouldNavigateToTopMostReport`, hence regressions in different scenarios are unlikely.

**Comment by Tony-MK** [comment] 2024-01-26 00:36
> In my expectation, the return behavior for the workspace detail page and the personal detail page should be similar. Not sure why they can still click the + button, so it would be great if you could also provide a video demonstration. 😂

My apologies, @ntdiary. I think I misunderstood something.

> We also need remove this line of code as well, because it also prevent us from returning to the confirmation list page after clicking the back button.

Do you think this is a reasonable change for `ReportDetailsPage`?

```
const backTo = props.route.params.backTo;
...
shouldNavigateToTopMostReport={!backTo}
onBackButtonPress={() => {Navigation.goBack(backTo, Boolean(backTo))}}
```

Should we change the `HeaderWithBackButton` because it will prioritize the `backTo` over `shouldNavigateToTopMostReport`, hence regressions in different scenarios will be less likely?


**Result**

https://github.com/Expensify/App/assets/22982173/3a1f4cb8-8a0e-484c-91da-91f7f5e9a59e

**Comment by dangrous** [comment] 2024-02-01 16:38
stop melvin

**Comment by Tony-MK** [comment] 2024-02-04 21:11
Hey, @ntdiary, the [PR](https://github.com/Expensify/App/pull/35594) is now ready to review.
Please let me know if you have any questions regarding this.
Thank you.

**Comment by Tony-MK** [comment] 2024-02-04 21:11
Hey, @ntdiary, the [PR](https://github.com/Expensify/App/pull/35594) is now ready to review.
Please let me know if you have any questions.
Thank you.

**Comment by dangrous** [comment] 2024-02-09 15:22
How are we looking on this one @Tony-MK @ntdiary ? Looks like one outstanding question and a merge conflict now. Can we get this ready for final review / merge on Monday or Tuesday? Thanks!

**Comment by Tony-MK** [comment] 2024-02-11 19:15
@dangrous, I believe we can finalize it before Tuesday. 👍

**Comment by JmillsExpensify** [comment] 2024-02-26 16:26
Alright, so circling back on this one. Payment summary as follows:

- Contributor: @Tony-MK $500
- Contributor+: @ntdiary $500 

I'm not seeing any issues with regressions, so @ntdiary please fill out the BZ checklist above and we can get this checklist closed out.

**Comment by dangrous** [comment] 2024-02-27 22:36
Even though it's small I think it's pretty quick to check, it would just be adding a line confirming the color to whatever existing test creates the workflow. I think it's worth adding!

If you want to do a  quick test, I'm sure QA can roll it in to what they already have and simplify

**Comment by JmillsExpensify** [comment] 2024-03-02 17:38
@ntdiary Let's use the Slack thread to align on next steps, I just commented there. I'm going to close this issue for now, though I can re-open if you need to be paid via Upwork.

**Closed by JmillsExpensify** 2024-03-02 17:38 UTC
Labels: External, Daily, Awaiting Payment, Bug
