### ISSUE TITLE
[$500] Web - LHN - Conversation order is changed when clicking through chats

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32767] opened 2023-12-08 23:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account that has many conversations
3. Create a workspace and add 10 members
4. Navigate to the #announce room
5. Do a split bill with all of the members
6. Navigate to the LHN
7. Click through all of your conversations

## Expected Result:
Conversation order should remain the same

## Actual Result:
Conversation order is changed when clicking through chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bca5c6cc-10ac-4508-b706-4d7a145dbf61

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168c661fa4f3428f0</li>
        <li>Upwork Job ID: 1733271569928404992</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by abeebridwan** [comment] 2023-12-08 23:49
Where do I get an expensifail account plz

**Comment by jliexpensify** [comment] 2023-12-10 23:10
@abeebridwan I don't think you can, `expensifail` is an internal Expensify testing domain that only certain groups have access to.

Anyway, I can repro this on my own Expensifail account on Staging 1.4.10.1, but it only jumped once for me.

**Comment by jliexpensify** [comment] 2023-12-13 21:18
Still awaiting proposals. @narefyev91 just wondering, do you have an expensifail account/access to expensifail credentials?

**Comment by narefyev91** [comment] 2023-12-14 09:11
Hey @jliexpensify ! I think i do not have such account

**Comment by jliexpensify** [comment] 2023-12-14 23:10
Thanks for confirming @narefyev91 - I'm just querying internally if this is something we'd want to fix: https://expensify.slack.com/archives/C01SKUP7QR0/p1702595386396689

**Comment by jliexpensify** [comment] 2023-12-17 21:39
@narefyev91 I haven't gotten an answer yet, but given it only seems to affect `expensifail.com` accounts, I'm not sure if this is going to be fixed as part of our roadmap priorities.

@lanitochka17 @narefyev91 can either of you repro on a normal account? I can't accurately repro this one - let me know!

**Comment by narefyev91** [comment] 2023-12-18 10:01
@jliexpensify sure on it - will try on lates main

**Comment by jliexpensify** [comment] 2023-12-19 01:11
Sure, I'm thinking if it can be repro-ed on a non-Expensifail account, we should fix it. If not, then lets close!

**Comment by narefyev91** [comment] 2023-12-19 15:26
@jliexpensify after some test - i see this behaviour - which seems for me that here is not a bug at all
When we split bill for all participants - after api call - participants will be put right after announcement room name in left panel. Clicking on each of them - move them to top of the page (after not read messages and pinned items)
like this:
<img width="375" alt="Screenshot 2023-12-19 at 17 25 06" src="https://github.com/Expensify/App/assets/28352309/3b86c068-da63-4f79-9d6a-2faaf457114a">

https://github.com/Expensify/App/assets/28352309/216662a5-4a9f-4a04-801b-b0bf0e3c3b07


https://github.com/Expensify/App/assets/28352309/bf0d65d7-1226-41bb-902b-f3c86b23e486

**Comment by jliexpensify** [comment] 2023-12-27 03:31
@narefyev91 thanks so much for your thorough investigation here - if it's intended, then lets close this one!

**Closed by jliexpensify** 2023-12-27 03:31 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
