### ISSUE TITLE
[$1000] Android - Workspace - User is returned to 'Hmm... it's not here' page from workspace chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26881] opened 2023-09-06 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app from the deep link staging.new.expensify.com/r/saastr
2. Log in with a new account.
3. Swipe back to return to LHN.

## Expected Result:
User is returned to LHN.

## Actual Result:
User is returned to 'Hmm... it's not here' page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5370f07a-06f7-45e1-be1b-17f2a30681cc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148a4f4b16e9811e6</li>
        <li>Upwork Job ID: 1699443740675543040</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-09-06 17:19
@abdulrahuman5196 not a blocker, but would be good to get it merged tomorrow

**Comment by abdulrahuman5196** [comment] 2023-09-06 18:42
It seems even in the video, NotFound page comes first then comes the Saastr page.

On @dukenv0307 's proposal here, it doesn't have information on why the NotFound page comes and stays in navigation on the first place, which I would like to investigate. The proposal targets to fix not showing the page on back press.

@bernhardoj You root cause is good. But the navigation is `FORCED_UP` type so it will replace the NotFound page right? So it should end up like `Navigation stack: [LHN, Demo chat (SAASTR)]` this?


>Navigation.navigate(ROUTES.SAASTR, CONST.NAVIGATION.TYPE.FORCED_UP); 

And I am unable to understand the solution properly.

Kindly do let me know if I am missing something

**Comment by rojiphil** [comment] 2023-09-07 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is returned to ‘Hmm… Its not here’ page from workspace chat when app is launched via deep link staging.new.expensify.com/r/saastr and swiped back.

### What is the root cause of that problem?
The root cause of the problem is that when the code reaches [at this location](https://github.com/Expensify/App/blob/46e6e202029924025148f6db6be2b378fd3e96e9/src/libs/actions/DemoActions.js#L22) the demo chat is the immediately previous one in navigation stack which has no chat page. And, hence the problem. 

### What changes do you think we should make in order to solve the problem?

To solve the problem, we need to replace the demo chat with the demo workspace chat report. We can do this using FORCED_UP by [replacing the code here](https://github.com/Expensify/App/blob/46e6e202029924025148f6db6be2b378fd3e96e9/src/libs/actions/DemoActions.js#L22) like this:

`Navigation.navigate(ROUTES.getReportRoute(demoWorkspaceChatReportID),CONST.NAVIGATION.TYPE.FORCED_UP);`

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-09-07 09:04
> @abdulrahuman5196 The NotFoundPage comes first because the URL of the sbe and saastr report is incorrect. The URL '/r/sbe' is the URL of the ReportScreen so it knows `sbe` is the reportID and then not found page appears because the reportID is invalid.

Got it. @dukenv0307 I understand this. But I would like to fix the issue of NotFoundPage itself. Like NotFound page itself should not become visible at first place.

**Comment by abdulrahuman5196** [comment] 2023-09-07 09:05
@bernhardoj 
With your proposal I am only seeing NotFoundPage view, 

>We still have the not found report in the stack because doing a deep link to a report screen will https://github.com/Expensify/App/issues/23441. So, the first not found page is replaced by demo chat and the second one is appended to the stack at the top.

We already have a PR for that issue. I tried your proposal alongside with its fix. But still I am seeing this issue.

**Comment by abdulrahuman5196** [comment] 2023-09-07 09:09
> Yes, that's supposed to be the expected result. When the user goes to r/saastr, a not found page will be shown. The correct demo page is /saastr or /sbe.
> 
> Currently, it pushes both not found and demo chat.

Sorry I don't understand this. Could you provide more information. @bernhardoj

**Comment by abdulrahuman5196** [comment] 2023-09-07 09:18
Got it @dukenv0307 Thank you. 

I was under the impression, deeplink urls ending with `/saastr` is always valid one. I could be wrong as well. 

@mountiny  Could you kindly clarify this? Int the video we have one  NotFoundPage followed by the saastr page opening for `r/saastr` url

**Comment by rojiphil** [comment] 2023-09-07 10:24
## Proposal

[Updated](https://github.com/Expensify/App/issues/26881#issuecomment-1709500433) 
@abdulrahuman5196 Thanks for your feedback. Have updated proposal with a safety condition as we want to replace only when the route includes `/r/saastr` or `/r/sbe`

**Comment by mountiny** [comment] 2023-09-07 10:52
@abdulrahuman5196 no the `r/sbe` is invalid route and that is not supported, is this entire issue based on this wrong testing assumption? 😢 does this not occur when navigating to `/sbe`? If so we dont have to do anything. Sorry this was not caught earlier

**Comment by mountiny** [comment] 2023-09-07 10:53
@mvtglobally @izarutskaya @kavimuru the links for the conferences do not have the `r/` in it, not sure if your team tested it with those links. should be only /sbe or /saastr

**Comment by mountiny** [comment] 2023-09-07 11:58
These links will be removed after the conferences and they wont be used so i am hesitant if this is needed, basically this is a wrong link noone would normally encounter from QR code or from a link shared somewhere, we dont have to care about this.

**Comment by mountiny** [comment] 2023-09-07 11:58
I am sorry for wasting your time on this one, this was missed on QA and my side that I havent checked the report better, sorry

**Closed by mountiny** 2023-09-07 11:58 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by izarutskaya** [comment] 2023-09-07 12:12
@mountiny  The problem was discovered while executing PR https://github.com/Expensify/App/pull/26844

**Comment by mountiny** [comment] 2023-09-07 17:37
<img width="640" alt="image" src="https://github.com/Expensify/App/assets/36083550/26499364-5754-4674-ac88-2e45207a0b66">

I see that the qa steps mention /sbe and /saastr routes but that probably should could have been made clearer with a full route.
