### ISSUE TITLE
[$1000]  Web - Magic code of one email works for another

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22336] opened 2023-07-06 11:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open New Dot
2. Login
3. Add emailOne as first secondary login and don't verify it yet.
4. Add emailTwo as second secondary login and don't verify it yet
5. Request magic code for emailOne but don't input it yet
6. Request magic code for emailTwo but don't input it yet
7. Go back to magic code screen for emailOne
8. Enter the magic code received in emailOne for this emailOne. It does not work.
9. Enter the magic code received in emailTwo for this emailOne. It works.

## Expected Result:
Either emailOne magic code should work for emailOne or both emailOne and emailTwo codes should not work and a new code should generate and should work for emailOne

## Actual Result:
emailTwo secret code works for verifying emailOne

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.36-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/db57373c-19a8-4b9d-8c9c-e4d6242efb09

https://github.com/Expensify/App/assets/93399543/73544087-d05d-4740-ba74-82480793d738

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688521454709009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177eb06e86cea7910</li>
        <li>Upwork Job ID: 1678577957895008256</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-06 16:44
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Last received code is only usable for One of the two added contact method.

### What is the root cause of that problem?
- The code is probably not mapped to added contact method in DB.

### What changes do you think we should make in order to solve the problem?
- Create a mapping between code and added contact method in DB.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by stephanieelliott** [comment] 2023-07-11 01:33
Tested and was able to repro the issue. However, I _think_ this will need to be fixed by someone internally?  Adding the `External` label to get a C+ on here to check me on that, thanks @allroundexperts!

**Comment by stephanieelliott** [comment] 2023-07-11 01:37
Thanks for the gut check @c3024! Ok, switching this to internal then,

**Comment by stephanieelliott** [comment] 2023-07-13 07:25
Just realized the `Internal` label didn't assign an internal engineer, added now!

**Comment by mountiny** [comment] 2023-07-18 10:40
Maybe @NikkiWines or @johnmlee101 would be interested given the knowledge in the domain

**Comment by johnmlee101** [comment] 2023-07-18 17:08
@kbecciv in your reproducible step video I do not see the issue occurring, and seems like a different flow than was reported by @c3024 ?

**Comment by johnmlee101** [comment] 2023-07-18 17:24
This might not be internal. Basically the UI thinks the login was validated for the other email, but in the database we verified the correct login associated with the correct code. If we don't have this information properly in the UI, I bet we can change the backend to return which login was properly validated

**Comment by johnmlee101** [comment] 2023-07-18 17:29
My proposal and I'll fix this now, is that we return the email that was validated in the call itself. Then we'll use that for onyx/local updates.

**Comment by johnmlee101** [comment] 2023-07-18 17:34
Actually talking to @NikkiWines I'm going to go with this option
```
Pass in the desired email in our backend, check if it matches with the validateCode and throw if it doesn't like the validateCode is bad
```

**Comment by stephanieelliott** [comment] 2023-07-24 20:02
This is being handled internally, one PR is merged and the other is still being reviewed

**Comment by stephanieelliott** [comment] 2023-07-28 22:07
second PR to fix this was just taken off hold: https://github.com/Expensify/Web-Expensify/pull/38212

**Comment by stephanieelliott** [comment] 2023-08-04 06:16
PR is reviewed, waiting for merge

**Comment by stephanieelliott** [comment] 2023-08-07 17:52
https://github.com/Expensify/Web-Expensify/pull/38212 was merged on 8/4. Seems like only payment due is for reporting. 

@c3024 I couldn't find you on Upwork, can you please propose to the job when you get a chance? https://www.upwork.com/jobs/~0177eb06e86cea7910

**Comment by stephanieelliott** [comment] 2023-08-14 13:59
All paid!

**Closed by stephanieelliott** 2023-08-14 13:59 UTC
Labels: Engineering, Daily, Internal, Bug
