### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Web - Chat - Inconsistent parsing upon wrapping mentioning message with link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19997] opened 2023-06-01 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send this message to a chat : [@concierge@expensify.com](https://google.com/)
3. Send this message to a chat : [*@concierge@expensify.com*](https://google.com/)

## Expected Result:
 Both message should consistently either changed into link or mention

## Actual Result:
While mentioning message without styling turned onto URL, mentioning message with styling turned onto mention-like message, but when clicked turned to be URL as well, and could cause confusion for the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/971470bc-86ed-47f8-9615-945ff3bee0cf

https://github.com/Expensify/App/assets/93399543/2409628e-85e7-4497-aabb-5e5a37dde9c4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685404731770449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01934ef45479ce0794</li>
        <li>Upwork Job ID: 1668225766110015488</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-06-02 01:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent parsing upon wrapping mentioning message with link. For example

```md
[@test@gmail.com](google.com)
```

is rendered as user mention but input 

```
[*@test@gmail.com*](google.com)
```

is rendered as user mention. Both cases shouldn't render user mention.

### What is the root cause of that problem?

First, we apply [markdown-link-to-html](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L70-L85) rule to the input

```md
[*@test@gmail.com*](google.com)
```

and output following html converting bold syntax of the link text at the same time inside method [modifyTextForUrlLinks](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L456)

```html
<a href="https://google.com" target="_blank" rel="noreferrer noopener"><strong>@test@gmail.com</strong></a>
```

Second, the [userMentioins-to-html](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L104-L120) rule is unexpectedly applied to the output anchor tag above.

So the root cause is that the [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L113) of user mention 

```js
new RegExp(`[\`.a-zA-Z]?@+${CONST.REG_EXP.EMAIL_PART}(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))`, 'gm'),
```

matches `@test@gmail.com` inside the text of anchor tag

```html
<a href="https://google.com" target="_blank" rel="noreferrer noopener"><strong>@test@gmail.com</strong></a>
```

We have a negative lookahead group, the ending group `(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))`, that possibly skip to match the user mention `@test@gmail.com` inside the anchor tag.

The ending negative lookahead group `(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))`  doesn't match string

```html
<strong>@test@gmail.com</strong></a>
```

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/7ab4a4c7-4641-4fac-89d8-cbac749a15ed">

So, the ending negative lookahead group can't skip to match the user mention `@test@gmail.com` wrapped by `strong` tag inside the anchor tag.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can improve the ending negative lookahead group `(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))` of the [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L113) of user mention to skip `<strong>` , `<em>`, `<del>` and `code` tags inside the `<a>` tag. 

We can use a new ending negative lookahead group 

```js
(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))
```

where includes two alternative subgroups inside it, `((?:(?!<a).)+)?<\\/a>` and `[^<]*(<\\/pre>|<\\/code>)`.

The first alternative group `((?:(?!<a).)+)?<\\/a>` is responsible to fix this issue. It works as follows

1. If we find substring `<a` before substring `</a>`, then we assume that the matched user mention is not inside `<a>` tag
2. If we find substring `</a>` before substring `<a`, then we assume that the matched user mention is inside `<a>` tag and skip this match

See regex test screenshot 

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/e5fe5b3f-7076-415b-9c54-cee2c02bb7c9">

So the new [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L113) of user mention will be

```js
new RegExp(`[\`.a-zA-Z]?@+${CONST.REG_EXP.EMAIL_PART}(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`, 'gm'),
```

By doing so, input

```
[*@test@gmail.com*](google.com)
```

is translated into html not rendering user mention syntax

```html
<a href="https://google.com" target="_blank" rel="noreferrer noopener"><strong>@test@gmail.com</strong></a>
```

and won't break existing unit test cases of Expensify-common lib.

The [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L95) of `@here` rule have similar issue, so we can apply same fix to it as well.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by s-alves10** [comment] 2023-06-02 06:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User mention inside a link is parsed inconsistently.
For example: 
[@concierge@expensify.com](https://google.com/)
[_@concierge@expensify.com_](https://google.com/)

### What is the root cause of that problem?

As you can see below, user mention cannot be parsed when it's inside any html tag.
```
    regex: new RegExp(`[\`.a-zA-Z]?@+${CONST.REG_EXP.EMAIL_PART}(?![^<]*(<\\/pre>|<\\/code>|<\\/a>))`, 'gm'),
```

The main reason of this issue is that we parse link before parsing user mentions


### What changes do you think we should make in order to solve the problem?

We can solve the issue by simply changing the rule order.

Put the user mention rule and here mention rule before the email rule

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/5c91bce5-c47d-43cb-96fb-e6ff4ab29932


</details>


### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-06-02 20:08
I wasn't able to reproduce
![2023-06-02_14-49-36 (1)](https://github.com/Expensify/App/assets/11966460/3dbec8b0-2b51-4cb7-a214-2415abfa0e7f)

**Comment by abekkala** [comment] 2023-06-02 20:09
I even tried copy/paste for `@concierge@expensify.com` and `_@concierge@expensify.com_`
And did not have the same outcome as the issue states

**Comment by s-alves10** [comment] 2023-06-02 20:13
> I even tried copy/paste for `@concierge@expensify.com` and `_@concierge@expensify.com_` And did not have the same outcome as the issue states

You need to try with 
`[@concierge@expensify.com](https://google.com/)`
`[_@concierge@expensify.com_](https://google.com/)`

**Comment by eh2077** [comment] 2023-06-04 01:20
Hi @abekkala , I think the reproduction steps is not clear enough. We should use underscore `_` to wrap the text part of the link to reproduce it. For example we can use below input 
```
[@concierge@expensify.com](https://google.com/)

Only wrap the text part of link
[_@concierge@expensify.com_](https://google.com/)
```
to duplicate it, see demo video 


https://github.com/Expensify/App/assets/117511920/db9225d8-4a7f-4016-9d4f-135ed9e020cd

**Comment by eh2077** [comment] 2023-06-07 14:44
@abekkala I can still reproduce it. I think we should reopen this issue.

I would also cc @puneetlath as you're most familiar with the mention feature.

**Comment by puneetlath** [comment] 2023-06-08 14:36
Hm, yes if it's still a bug then let's fix.

**Comment by s-alves10** [comment] 2023-06-12 17:55
## Proposal
[Updated](https://github.com/Expensify/App/issues/19997#issuecomment-1573237303)

**Comment by s77rt** [comment] 2023-06-12 21:23
@s-alves10 Thanks for the proposal. You RCA is not really correct, if it was this issue wouldn't even exist but I see you updated your proposal recently so I assume the RCA is outdated. As for the fix I guess it would work but it's better not to match the regex at all rather matching and rejecting, or even better avoid any regex changes by altering the order of rules if possible (same note given above).

**Comment by s-alves10** [comment] 2023-06-12 23:53
@s77rt 
Yes, I suggested as follows at first

```
We can solve the issue by simply changing the rule order.
Put the user mention rule and here mention rule before the email rule
```

But I thought mention-user parsing has some problems and needs to be fixed. In addition, changing rule order may have other issues. That's why I changed the solution.

**Comment by s77rt** [comment] 2023-06-13 18:28
@s-alves10 Thanks for the update. I have checked the order of rules. The correct order should be:
1. Link
2. Mentions
3. Bold/Italic/Strikethrough 

This is actually the current order already, except that the link rule calls `modifyTextForUrlLinks` which applies bold/italic/strikethrough rules and cause the mentions rule to mismatch.

**Comment by s77rt** [comment] 2023-06-13 18:34
@eh2077 Thanks for the follow up. I have provided some info regarding the order of rules above. I think it's indeed safer and easier to follow the same approach we did with `autolink` and that is to alter mentions regex as you suggested. Let's go with that.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @johnmlee101

**Comment by eh2077** [comment] 2023-06-14 11:36
@s77rt @johnmlee101 The PR https://github.com/Expensify/expensify-common/pull/549 for expensify-common repo is ready. Please help to review it when you get time, thanks.

**Comment by s77rt** [comment] 2023-06-21 23:16
Not overdue. PR is merged and waiting for deployment.

**Comment by eh2077** [comment] 2023-06-22 00:18
> Not overdue. PR is merged and waiting for deployment.

@s77rt The PR has been deployed to the production because it occasionally shared the same commit with the other PR https://github.com/Expensify/App/pull/20769. @johnmlee101 pointed it out here https://github.com/Expensify/App/pull/20767#issuecomment-1593404453. 

So, actually, the payment date of this issue should be same as issue https://github.com/Expensify/App/issues/20111.

Sorry for the confusion caused!

cc @abekkala @johnmlee101

**Comment by s77rt** [comment] 2023-06-22 00:21
Oh right, so we have to track this one manually

**Comment by abekkala** [comment] 2023-06-23 15:17
### PAYMENTS TO BE MADE JUNE 28

- Issue reported by: @kerupuksambel [$250]
- Selected Proposal for fix: @eh2077 [$1000] + [$500 PR bonus]
- C+ Review: @s77rt  [$1000] + [$500 PR bonus]

**Comment by abekkala** [comment] 2023-06-28 16:19
@kerupuksambel @eh2077 @s77rt - contract payment offers have been sent!

**Comment by eh2077** [comment] 2023-06-28 16:34
@abekkala  Accepted. Thank you!

**Comment by abekkala** [comment] 2023-06-28 17:20
@eh2077 payment sent and contract ended - thank you! 🎉

**Comment by s77rt** [comment] 2023-06-28 17:56
@abekkala Accepted!

**Comment by abekkala** [comment] 2023-06-28 18:00
@s77rt payment sent and contract ended - thank you! 🎉

**Comment by kerupuksambel** [comment] 2023-06-28 19:23
> @kerupuksambel @eh2077 @s77rt - contract payment offers have been sent!

Accepted! @abekkala

**Comment by abekkala** [comment] 2023-06-28 20:42
@kerupuksambel payment sent and contract ended - thank you! 🎉

Closing

**Closed by abekkala** 2023-06-28 20:42 UTC
Labels: Reviewing, External, Daily, Bug
