### ISSUE TITLE
Workspace - Workspace doesn't appear in invited account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13158] opened 2022-11-29 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login with new gmail accounts on 2 devices
2. On device 1 create a workspace
3. On device 1 invite to workspace an account that is on device 2
4. On device 2 verify user can immediately see the Workspace in it's account

## Expected Result:
On device 2 user should be able to immediately see the Workspace in it's account

## Actual Result:
On device 2 user doesn't see the Workspace in it's account, only #announce chat of this workspace

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.33.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204640877-20e5b84e-6228-4897-9586-ac7e53c5359d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-11-29 20:33
QA team is failing step in TR for Admin / New User Section step 4. On the main testing device - Verify new member can immediately see the Workspace in their account.

https://expensify.testrail.io/index.php?/tests/view/2969249

![image](https://user-images.githubusercontent.com/93399543/204641399-7eb6644e-a23d-4352-b9cd-4dc8dc6c1220.png)

**Comment by lschurr** [comment] 2022-11-29 21:55
I tested and confirmed that I only see the #announce room when invited to a workspace:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/33293730/204656810-c26db9f0-c7de-455b-846b-f9207e0b4a24.png">

What else is a workspace user supposed to see?

**Comment by jasperhuangg** [comment] 2022-11-30 15:13
Woah this has to be a regression, taking a look

**Comment by jasperhuangg** [comment] 2022-11-30 15:18
So it looks like this is actually by design 😅 

[Here](https://github.com/Expensify/App/blob/1527fdcf443713bb058e6e76504006d74f6b1aa8/src/pages/workspace/WorkspacesListPage.js#L118-L119) we filter out listing any workspaces that the user isn't an admin for. In other words, users can only access workspace settings for the workspaces they're an admin for, which makes sense.

I guess it's kinda like policy settings in OldDot. Closing...

**Closed by jasperhuangg** 2022-11-30 15:18 UTC
Labels: Engineering, Daily, Bug

**Comment by lschurr** [comment] 2022-11-30 18:04
Yep, that's what I was thinking. Thanks @jasperhuangg!
