### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] mWeb- Login - Error message appear on original tab when navigate from "Magic code expired" page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33637] opened 2023-12-27 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. On the log in screen, enter a new account email
3. Navigate to the email inbox and open the validate email and copy the link
4. Modify the last portion of the link by a character
5. Verify you're redirected the "Magic code expired" page
6. Navigate to the original login tab

## Expected Result:
There should be no error messages on the login page

## Actual Result:
"Auth Authenticate returned an error" message appear for a second on original tab when navigate from "Magic code expired" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/07630a47-3410-4c44-aa86-727fda89addb

![Bug6326464_1703630998616!image__2_](https://github.com/Expensify/App/assets/78819774/226528f5-4f12-4497-bd15-be1c902c8692)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e24ce791ae307499</li>
        <li>Upwork Job ID: 1739822234402959360</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28104854</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-12-29 15:12
@lanitochka17 I don't really get this.  Why would anyone "Modify the last portion of the link by a character" ?  I'm not sure this is something we need to account for.

**Comment by slafortune** [comment] 2024-01-03 15:11
@mananjadhav will you be able to get to this or are you waiting on more proposals?

**Comment by mananjadhav** [comment] 2024-01-04 13:54
@tienifr I reviewed the proposal, but I am not sure if we implement the code based on tab. Do you have a reference of the code where we're implementing tab specific checks/conditions?

**Comment by mananjadhav** [comment] 2024-01-09 17:21
Still waiting on response of the previous proposals. Open to others as well.

**Comment by slafortune** [comment] 2024-01-12 19:27
@tienifr can you provide an update to https://github.com/Expensify/App/issues/33637#issuecomment-1877131713

**Comment by sourcecodedeveloper** [comment] 2024-01-13 20:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigate to staging.new.expensify.com, instead of entering the magic code, copy the provided link and modify the accountID in the link by character, and open the link in new tab. Notice the "magic code expired" page, open the original tab and notice the error message "Auth authenticate returned an error " or "Incorrect magic code. Please try again or request a new code."

### What is the root cause of that problem?
The signin link has accountID in the first parameter. When signing in using link, 
the 'SigninUserWithLink' api is used as opposed to 'SigninUser' which is used when entering magic code.
When the accountID is provided in the route, the signInWithValidateCode is called
https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/pages/ValidateLoginPage/index.website.js#L72

The accountId is invalid and api call SigninUserWithLink returns error "Auth authenticate returned an error " or "Incorrect magic code. Please try again or request a new code."

The error is actually returned in the "magic code expired" tab but because the error is not cleared, the error is also shown in any other open tabs.

### What changes do you think we should make in order to solve the problem?

I would add useEffect in index.website and listen for changes to accountID, autoAuthState and props.account.errors.
 
https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/pages/ValidateLoginPage/index.website.js#L72

    useEffect(() => {

        if(accountID && props.session.autoAuthState === CONST.AUTO_AUTH_STATE.FAILED && !_.isEmpty(props.account.errors))
        {
            Session.clearAccountMessages();
        }
    }, [accountID, props.session.autoAuthState, props.account.errors])

The accountID is important because accountID is only provided when signing using signin link. Without the accountID, the error message would be cleared for when using invalid magic code, the only time error needs to be cleared is when using signin link with accountID.

Also the accountid is obtained from the signin link entered in the url, 
https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/pages/ValidateLoginPage/index.website.js#L53



### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-01-16 19:33
I think @tienifr's original proposal with work. I got a bit confused by mixing the current proposal and the alternative proposals.

🎀 👀 🎀 C+ reviewed.

**Comment by sourcecodedeveloper** [comment] 2024-01-16 20:17
@mananjadhav I mentioned in [proposal](https://github.com/Expensify/App/issues/33637#issuecomment-1890754235), the accountID would need to be checked for when signing in using signinlink, simply calling Session.clearAccountMessages() would also clear error message when typing invalid magic code. I suggest to ask them to provide video poc of proposal.

**Comment by slafortune** [comment] 2024-01-31 16:26
@mananjadhav When you get a chance can you complete the above checklist for NewDot payment to proceed

**Comment by mananjadhav** [comment] 2024-01-31 16:47
I don't think we did consider the case of different tab when building the magic code and I can't seem to pinpoint a specific PR where this could've been handled.  Considering this is not a very general use-case I don't think we need a regression test step either. 

@slafortune I think we're good to close this one out. Can you please post the payout summary so that I can raise a request?

**Comment by mananjadhav** [comment] 2024-02-02 03:41
@slafortune quick bump on the payment summary.

**Comment by slafortune** [comment] 2024-02-02 18:47
- [ ] @mananjadhav is due $500 paid via NewDot
- [ ] @tienifr has been paid $500 paid via Upworks

**Closed by slafortune** 2024-02-02 18:47 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-02-02 18:56
$500 approved for @mananjadhav based on summary above.
