### ISSUE TITLE
[$500] Dev: Web - When the user goes back to reselect a workspace, a blank option is appearing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27593] opened 2023-09-16 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Click on FAB > Request Money > Distance
3. Fill Start and End address > Next
4. Select any option > Go Back

## Expected Result:
Same options will be available as before

## Actual Result:
A blank option is also present among others

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1b8617df-663b-451f-8cc6-1eadfc2a71cc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694785480277979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dcb76ff55d14f8b</li>
        <li>Upwork Job ID: 1703117949219422208</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 18:49
This is a duplicate of https://github.com/Expensify/App/issues/27510.

**Comment by MuzanEDM** [comment] 2023-09-16 22:04
This is a duplicate of https://github.com/Expensify/App/issues/27510.

**Comment by saranshbalyan-1234** [comment] 2023-09-17 19:47
Contributor details
Your Expensify account email: saranshbalyan123@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01123e26044968b11d

**Comment by s77rt** [comment] 2023-09-18 10:41
@strepanier03 Let's close this as a dupe.

**Comment by strepanier03** [comment] 2023-09-18 20:52
Thank you, will close this out!

**Closed by strepanier03** 2023-09-18 20:52 UTC
Labels: External, Daily, Help Wanted

**Comment by MuzanEDM** [comment] 2023-10-26 08:47
Good.
