### ISSUE TITLE
[$1000] Keyboard controls are disabled to select a word from the compose box to copy and paste

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14346] opened 2023-01-17 00:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Write some text in the compose box
3. long press on a word to select that one word and double tap to open the selection bars to select full text and copy or paste

## Expected Result:
Able to select text if I  long press on a word and it will show the selection bars, and then I can drag those bars to the left and right and then choose to copy and paste content

## Actual Result:
Little selection bar does not appear and can't copy or paste

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.55-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212783061-6b0206be-3c7a-42a6-b2e7-ddda1b243683.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673894817686509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127bc0dedff29a2b7</li>
        <li>Upwork Job ID: 1618721032261423104</li>
        <li>Last Price Increase: 2023-01-26</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-01-18 06:07
I was not able to reproduce the bug. The selection bar appeared and I was able to use it.

<img width="380" alt="Screen Shot 2023-01-17 at 10 07 21 PM" src="https://user-images.githubusercontent.com/8292562/213097148-ecde7593-e55d-42ca-97e9-248863c0502a.png">

**Comment by tjferriss** [comment] 2023-01-20 18:49
@quinthar are you still able to reproduce this one?

**Comment by tjferriss** [comment] 2023-01-24 19:40
I just tested again, still not able to reproduce this. I'm using BrowserStack to test the android app. @quinthar @kavimuru are you able to reproduce?

<img width="307" alt="Screen Shot 2023-01-24 at 11 39 12 AM" src="https://user-images.githubusercontent.com/8292562/214391922-3ac9d358-9206-46c0-a1b5-7729c45f49ca.png">

**Comment by kavimuru** [comment] 2023-01-25 16:04
@tjferriss I can still able to reproduce

<img src="https://user-images.githubusercontent.com/43996225/214613490-1b1d4f88-6fc2-4b94-9258-64b8ab943b4c.jpg" width="40%" height="40%">

**Comment by tjferriss** [comment] 2023-01-26 21:22
From @quinthar in Slack...

> Yes, this is still reliably reproducible for me.  It feels like something is almost interrupting the keyboard controls from appearing.  I'll try to explain:
> - Open a chat
> - Type something like this is a test
> - Long-tap on a -- it highlights just that word, but with no controls
> - While a is selected, long-tap on test -- the keyboard controls (including the bookend sliders) appear
> - Slide the right bookend to select a test -- but when I let go (or even before that), the sliders and keyboard controls disappear
> So they appear and disappear kind of erratically

I also just tried with a different device in BrowserStack and I was able to get a similar result.

**Comment by amyevans** [comment] 2023-01-30 15:57
Thanks @bernhardoj, yes this looks like a duplicate of https://github.com/Expensify/App/issues/8349 so going to close this in favor of that issue. There's a PR pending to fix it.

**Closed by amyevans** 2023-01-30 15:57 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
