### ISSUE TITLE
[$1000] IOU amount position glitches when opening IOU report chat for first time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24461] opened 2023-08-11 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Click on + icon and select request money
3. Enter an amount and click next
4. Select an account with whom you dont have prior money request history and enter next
5. Go to chat with the requested account and click on the IOU box
6. Observe that the amount first appears at the top of the screen before jumping to the bottom of the screen

 
## Expected Result: 
Amount position should not glitch
## Actual Result: 
The amount position jumps to its right place after a few seconds

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e42088e3-ae41-4b2b-b462-93faea3fb889

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691085140246529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fee18dadcae45f9f</li>
        <li>Upwork Job ID: 1691584269269925888</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-08-14 15:16
Will try to reproduce today.

**Comment by lschurr** [comment] 2023-08-14 22:10
Hm, I'm not seeing the jump when testing. It is always at the bottom for me. Will ask in Slack if anyone else can reproduce.

**Comment by lschurr** [comment] 2023-08-15 22:55
@mananjadhav could you double check this one and make sure you're able to reproduce?

**Comment by mananjadhav** [comment] 2023-08-16 16:15
I have tried on Android emulator and an Android tablet for multiple different accounts and currencies. I couldn't reproduce this.

https://github.com/Expensify/App/assets/3069065/cfc7725b-5b24-4c5e-b4ed-cff7b5cf3d70

**Comment by SofoniasN** [comment] 2023-08-16 18:08
Android phone, TCL is the phone brand

**Comment by lschurr** [comment] 2023-08-18 18:33
Hm, @mananjadhav what do you think of this? Should we close?

**Comment by lschurr** [comment] 2023-08-21 15:02
Bump @mananjadhav for your thoughts on this one.

**Comment by mananjadhav** [comment] 2023-08-22 13:59
I don't know. I've tried this further on another device, and I couldn't reproduce it. I think we can post on slack and if unable to get proper reproduction steps, then best to just close it?

**Comment by lschurr** [comment] 2023-08-25 15:16
Going to close.

**Closed by lschurr** 2023-08-25 15:16 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
