### ISSUE TITLE
[$250]  Deleting failed smartscan expense put workspace chat into weird state.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40203] opened 2024-04-13 13:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712855834212319

## Action Performed:

1. in Account 1, submit two expenses, and have one where smartscan fails.
2. In account 2, approve the report with the two expenses (since one had smartscan fail, this should hold back the second one).
3. In account 1, delete the expense where smartscan failed.
4. This puts the workspace chat in a weird state where history cannot be accessed (in both accounts). 

## Expected Result:
No weird things should be observed

## Actual Result:
This puts the workspace chat in a weird state where history cannot be accessed (in both accounts). 
We're calling openReport in an infinite loop.

## Workaround:
unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/75deffdd-2b6b-4c7b-b717-ac0b48f5a176

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b4f1c4133a2240c</li>
        <li>Upwork Job ID: 1779770498711244800</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2024-04-18 04:21
Not overdue, waiting on proposals

**Comment by kadiealexander** [comment] 2024-04-23 04:42
I have asked for a retest for this issue to see if it's still reproducible.

**Comment by kadiealexander** [comment] 2024-04-29 05:38
https://expensify.slack.com/archives/C9YU7BX5M/p1714368662879459

**Comment by kbecciv** [comment] 2024-04-29 17:21
Unable to reproduce it, build 1.4.67.0, asking here  -> https://expensify.slack.com/archives/C049HHMV9SM/p1714402638617059?thread_ts=1712855834.212319&cid=C049HHMV9SM

https://github.com/Expensify/App/assets/93399543/34d9db48-e0e9-4ab4-a327-5235036bffca

**Comment by kadiealexander** [comment] 2024-05-02 03:03
[Closing as not reproducible](https://expensify.slack.com/archives/C049HHMV9SM/p1714420504991839?thread_ts=1712855834.212319&cid=C049HHMV9SM)

**Closed by kadiealexander** 2024-05-02 03:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
