### ISSUE TITLE
[Hold for payment 2024-02-12] [$1500] Implement a new navigator for the Ideal Nav overhaul

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#32689] opened 2023-12-07 17:27 UTC
Implement the new navigation system for the Ideal Nav project.

The detailed requirements for the new navigation structure are stipulated in [this design doc](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg).

@adamgrzybowski from Software Mansion will do the implementation work. We will keep track of the progress using this issue.

[Potential new requirement that hasn't made it to the design doc yet.](https://expensify.slack.com/archives/C036QM0SLJK/p1701975105241769)

## Child issues
- #32939
- #32940
- #32941

**Comment by adamgrzybowski** [comment] 2023-12-07 17:28
👋

**Comment by adamgrzybowski** [comment] 2023-12-12 10:36
Hey @hayata-suenaga this issue seems quite general. We divided our work on the structure of navigation into three separate task

Left hand navigator - @WojtekBoman 
Full screen settings page - @kosmydel 
Bottom tab navigator - @adamgrzybowski 

Maybe we could create these issues to track progress more accurately?

**Comment by hayata-suenaga** [comment] 2023-12-12 18:04
Is @kosmydel working on the full screen settings page for the account for workspace or both?

**Comment by hayata-suenaga** [comment] 2023-12-13 01:05
I am assigning myself to this tracking issue for three navigation-related issues.

@adamgrzybowski if you need a feature branch to which to merge navigation-related branches, please use https://github.com/Expensify/App/tree/ideal-nav that Vit created.

**Comment by s77rt** [comment] 2024-01-08 23:01
@hayata-suenaga Can you assign me here?

**Comment by hayata-suenaga** [comment] 2024-01-29 18:43
the feature branch is very close to be merged

**Comment by s77rt** [comment] 2024-02-07 18:11
@hayata-suenaga Can you please assign a BZ member for payment processing?

**Comment by hayata-suenaga** [comment] 2024-02-08 19:24
An expert agency engineer authored the PR, so the only payment we need is for C+.

@lschurr The PR @s77rt (C+) reviewed was super huge. They deserve at least twice the usual payment. I'd say 3x.

**Comment by lschurr** [comment] 2024-02-09 00:14
Sounds good @hayata-suenaga! Can you link me to the specific PR so I can see when it's merged for payment?

**Comment by hayata-suenaga** [comment] 2024-02-09 16:26
ah sorry about that

[here is the PR](https://github.com/Expensify/App/pull/33280)

**Comment by lschurr** [comment] 2024-02-09 16:48
Thanks! Looks like it was deployed to prod on Feb 5th, so we'll pay on Feb 12th.

**Comment by hayata-suenaga** [comment] 2024-02-09 17:13
by the way, there are multiple regressions that stemmed from the PR, but all these regressions were expected. They should not reduce the payout to @s77rt

**Comment by s77rt** [comment] 2024-02-09 17:16
Thank you! But I'm good with the standard $500. No counting those regression is enough

**Comment by lschurr** [comment] 2024-02-09 19:08
We discussed internally and decided $1500 is a fair price for the amount of work you put into this one @s77rt :)

**Comment by lschurr** [comment] 2024-02-09 19:11
Sent offer in Upwork: https://www.upwork.com/nx/wm/offer/100843971

**Comment by s77rt** [comment] 2024-02-09 19:29
Accepted! Thank you!

**Comment by lschurr** [comment] 2024-02-12 17:02
Paid in Upwork :)

**Closed by lschurr** 2024-02-12 17:02 UTC
Labels: Engineering, Daily, NewFeature, Overdue, Awaiting Payment, Bug

**Comment by hayata-suenaga** [comment] 2024-02-13 17:00
thank you so much and great work @s77rt !
