### ISSUE TITLE
Backgrounding - iOS app flashes white when backgrounding on older device models

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40938] opened 2024-04-24 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre Cond: iPhone Device is set to "Dark" and "Use Device Theme" is set in Expensify Settings
1. Open the New Expensify Beta app
2. Sign into a valid account
3. Background the app and open any other app (For example: Timer, Whatsapp, Safari, etc.)
4. Return to the Expensify app

## Expected Result:
User expects the app to continue in dark theme when navigating back and forth

## Actual Result:
The app flashes white when returning from background
EXTRA: This issue seems specific to older phone models, was able to reproduce on an iPhone XR / 17.3 and on an iPhone 7 / 15.8.2

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c23b800f-9dda-4ae8-9dd6-b807760d7a96

https://github.com/Expensify/App/assets/78819774/d36fafce-d49e-45b3-b545-7f9c242ce04d

[log.txt](https://github.com/Expensify/App/files/15099805/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-24 20:04
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-04-24 21:30
I can't reproduce this. Even still, it seems like in the above videos, you need to be switching between the apps repeatedly to have this happen. Even if it was reproducible, not sure it feels worth prioritizing to me. Closing.

**Closed by joekaufmanexpensify** 2024-04-24 21:30 UTC
Labels: Daily, Bug
