### ISSUE TITLE
[HOLD for payment 2023-05-23] [$1000] [Manual Requests] Ensure correct amount is displayed in the IOUPreview

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#18749] opened 2023-05-10 21:36 UTC
Coming from [this comment](https://github.com/Expensify/App/pull/18537#issuecomment-1542400151), transaction amounts for Expense reports are stored as negative values in the database, so we need to invert the sign from negative to positive and vice-versa. 

This is because there are instances where you can get a credit back on your card, or you enter a negative expense to “offset” future expenses. So in theory, the total of your expenseReport could be a negative.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a4895d6068712f5</li>
        <li>Upwork Job ID: 1656413205162098688</li>
        <li>Last Price Increase: 2023-05-10</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-05-10 21:59
@mollfpr it might be clear from the body but just noting this applies only for the expense reports, not for the IOU reports

**Comment by mollfpr** [comment] 2023-05-11 06:21
@mountiny Yes, this only happen on the expense reports.

**Comment by trjExpensify** [comment] 2023-05-11 11:17
Dope, are you good with a PR for this one @mollfpr?

**Comment by mollfpr** [comment] 2023-05-11 11:19
@trjExpensify Yup! Will clean up my tasks on the proposals review and then raise a PR for this.

**Comment by trjExpensify** [comment] 2023-05-11 11:21
Neat, thanks!

**Comment by mollfpr** [comment] 2023-05-11 15:08
https://github.com/Expensify/App/blob/5df596f1be385c9767aef239fd24a6d2fd7771e7/src/libs/actions/IOU.js#L79

> transaction amounts for Expense reports are stored as negative values in the database

@luacmartins in building an optimistic expense report based on the above comment, should we subtract the amount rather than increase it?

We have this glitch in the expense report
https://github.com/Expensify/App/assets/25520267/e331f22c-f54c-4e85-aae0-7bdcc3c691eb

**Comment by luacmartins** [comment] 2023-05-11 15:25
Yes, we should do that

**Comment by luacmartins** [comment] 2023-05-15 13:29
PR merged

**Comment by mollfpr** [comment] 2023-05-23 16:45
> [@mollfpr / @sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr / @sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@mollfpr / @sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a bug. This issue is another work for https://github.com/Expensify/App/pull/18537.

> [@mollfpr / @sobitneupane] Determine if we should create a regression test for this bug.
> [@mollfpr / @sobitneupane] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Propose regression step.

1. Go to the workspace report
2. Request money using the action menu item
3. Put any amount
4. Submit the requested money
5. **Verify** that the IOU preview is shown with a positive amount
6. **Verify** that the amount on the Expense report that just added in LHN has a positive amount
7. Navigate to the Expense report that just added
8. **Verify** that the report header shows a positive amount
9. Back to the workspace report and do request money again
10. **Verify** again step 5, 6, and 8
11. 👍 or 👎

**Comment by mollfpr** [comment] 2023-05-23 16:53
Make sense to me!

**Comment by trjExpensify** [comment] 2023-05-25 15:31
Alrighty, time to settle up here. Sorry for the delay, as I get back from EC3. 

I've sent the following offers on [this job](https://www.upwork.com/jobs/~013a4895d6068712f5): 

@mollfpr - $1,500 for the fix & #urgency bonus 
@sobitneupane - $1,500 for C+ & #urgency bonus

**Comment by trjExpensify** [comment] 2023-05-25 16:02
Settled up with @mollfpr. Awaiting @sobitneupane!

**Comment by sobitneupane** [comment] 2023-05-25 16:50
@trjExpensify I didn't review the PR. So, no payment for me.

**Comment by trjExpensify** [comment] 2023-05-25 17:33
Ah cool, got it. Thanks! Closing this out then. 👍

**Closed by trjExpensify** 2023-05-25 17:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
