### ISSUE TITLE
Web - Blank space appears after deleting a deleted message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22140] opened 2023-07-03 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to a chat with a user
3. Send a message
4. Now click on reply thread icon so that a thread page appears
5. Now delete the message comment so that 'deleted message' appears
6. Now again delete the 'deleted message' and notice a blank gap is seen
7. You need to refresh the page to see the 'deleted message' again

## Expected Result:
Blank space should not appear after deleting a deleted message

## Actual Result:
Blank space appears after deleting a deleted message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cbc00828-dc6c-4c40-a9bf-15f0757509c8

https://github.com/Expensify/App/assets/93399543/15defa6b-ff28-44fd-bfc2-9a330b66f082

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688305766388839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-03 22:10
The second delete API returns the below data
![image](https://github.com/Expensify/App/assets/126839717/ef7f2b98-2026-40f7-b650-41f51215d85a)

This is the root cause and should be fixed in the backend

**Comment by sakluger** [comment] 2023-07-05 23:18
Based on [this other GH issue's comment](https://github.com/Expensify/App/issues/21103#issuecomment-1602592739):

> For expected behavior, once you delete a parent thread message, we should immediately change the comment actions menu to show only "reply in thread" and "mark Unread", which is what is shows once you leave the chat and come back.

Once we fix that behavior, it will be impossible to delete the message a second time, and so this but will become impossible to reproduce at that point. Because of that, I'm going to close this issue.

**Closed by sakluger** 2023-07-05 23:18 UTC
Labels: Daily, Bug
