### ISSUE TITLE
[$1000]  Context menu hides on click of reveal message or hide message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20532] opened 2023-06-09 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA , send any message to userB
2. from userB, mark that message as offensive
3. click on reveal message or hide message option
## Expected Result: 
Context menu should not hide on click of reveal message or hide message
## Actual Result: 
Context menu hides on click of reveal message or hide message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ec5311b8-e671-45d9-ab6c-4f14a1d3f5eb

https://github.com/Expensify/App/assets/43996225/68bcda3c-34e4-4fa8-8d96-c6751e64988f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685974173855139
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123ee093f8d7b9ffe</li>
        <li>Upwork Job ID: 1668727146272120832</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-06-10 04:05
Same root cause with this https://github.com/Expensify/App/issues/16519

**Comment by adelekennedy** [comment] 2023-06-13 21:05
I'm able to reproduce but the context menu will pop back up if I navigate up from the concierge message

**Comment by s77rt** [comment] 2023-06-14 18:12
@dukenv0307 Thanks for the proposal. I'm afraid that we may not need to do anything here. This issue will be fixed once https://github.com/Expensify/App/pull/20561 is merged.

**Comment by s77rt** [comment] 2023-06-14 18:12
@bernhardoj Thanks!

**Comment by s77rt** [comment] 2023-06-14 18:13
@adelekennedy Let's close this.

**Closed** 2023-06-14 19:31 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by s77rt** [comment] 2023-06-15 11:35
@getusha I think that applies only to issues that have different root causes, it does not seem to be the case here.
