### ISSUE TITLE
[HOLD for payment 2023-06-29] Web - Split Bill - Money request confirmation list stays highlighted after press

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20585] opened 2023-06-12 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a group chat
2. Start a Split Bill and proceed until the confirmation page
3. Unchecks the items in the list

## Expected Result:
The item is not highlighted if we don't hover it or is not focused

## Actual Result:
The item stays highlighted after press and also the first item that is not clickable is highlighted if we click it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/062ce13b-eda9-41a0-8725-6b645a56e9a4

https://github.com/Expensify/App/assets/93399543/22f1a4f8-18f9-4d6c-8e60-14d1cf20ef55

**Expensify/Expensify Issue URL:**

**Issue reported by:** @bernhardoj

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686202285251059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110ed1d7d5b0b56cb</li>
        <li>Upwork Job ID: 1670152822418042880</li>
        <li>Last Price Increase: 2023-06-17</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-12 21:08
I can reproduce but I don't see why this is a bug - asking for more information https://expensify.slack.com/archives/C049HHMV9SM/p1686604097827569?thread_ts=1686202285.251059&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-06-13 19:15
Reached out here for some help - https://github.com/Expensify/App/pull/19612#issuecomment-1589882706

**Comment by Skalakid** [comment] 2023-06-14 14:43
@bernhardoj @Christinadobrzyn I reverted my changes for testing and still, I got the same bug (even in PRs merged before #19612). However, I think I know where is the problem. It is caused because of not disabling focusing in this list. I will write the proposal

**Comment by bernhardoj** [comment] 2023-06-14 15:13
Hmm, that's strange. I removed `focusStyle` and the issue is gone. To have us in the same page, the first row should not be highlighted (ss taken from video above).
<img width="624" alt="Screenshot 2023-06-14 at 23 11 19" src="https://github.com/Expensify/App/assets/50919443/1e510cd0-2dd7-42e4-b71f-107a4890d33f">

**Comment by Skalakid** [comment] 2023-06-14 15:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The money request confirmation list stays highlighted after press

### What is the root cause of that problem?

There are two root causes of this problem. The first one is that we don't disable focusing on this list. The second one is that we have two places that specify focus styles for `PressableWithFeedback`

### What changes do you think we should make in order to solve the problem?


We should pass the `disableFocusOptions` prop to the `<OptionsList>` component. This is the parent component of the user list where the bug exists. By passing this option the `optionIsFocused`  prop in `OptionRow` will be always false. 
After we change this, we should remove focus styles from the `style` prop in `PressableWithFeedback` because we can just use `focusStyle` prop. 
Next, we should make `focusStyle` disabled when `optionIsFocused` is false, so we can change it to `this.props.optionIsFocused ? styles.sidebarLinkActive : null}`.

After we do these changes, the issue should be fixed, however we will have to fix again this [issue](https://github.com/Expensify/App/pull/19612#issuecomment-1569876479). To do this we should change a little bit `PressableWithFeedback` structure and move the styles from `OpacityView` to the parent component `GenericPressable`. These changes will resolve both issues



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Skalakid** [comment] 2023-06-14 15:20
> Hmm, that's strange. I removed `focusStyle` and the issue is gone. To have us in the same page, the first row should not be highlighted (ss taken from video above). 

Hmm maybe I misunderstand something, I thought that after we select/unselect something nothing should be highlighted. So last clicked element should be on focus?

**Comment by Skalakid** [comment] 2023-06-14 15:45
Oh okay, now I think I understand, we want to focus last unselected element to enable the user to select it by clicking enter but the other highlight is wrong. Hmm, I tested it and its really buggy so I thought that we don't want this 😅 


https://github.com/Expensify/App/assets/39538890/c14e6071-bd07-4c3a-a117-0ff4181f712c

**Comment by bernhardoj** [comment] 2023-06-14 16:02
I guess that's another bug to be solved haha. I think we should focus on the wrong highlight here.

**Comment by Skalakid** [comment] 2023-06-15 13:10
Okay, so to fix this issue we have to move styles in `PressableWithFeedback` to the parent component, to not break this fix. Also, we need to remove `focusStyles` prop in `OptionRow` because focused element is different then highlighted element (the last unselected item)

**Comment by Skalakid** [comment] 2023-06-15 13:21
The bug with switching between items using arrows and enter button occurs after you change the focused item using the `tab` button. The `focusedIndex` from `ArrowKeyFocusManager` is not changing so we have two different items "focused"

**Comment by abekkala** [comment] 2023-06-16 19:11
Holding this one based on this comment: https://github.com/Expensify/App/issues/19766#issuecomment-1595163834

**Comment by abekkala** [comment] 2023-06-16 19:18
Nope, placed Hold on the wrong issue title. my bad

**Comment by Christinadobrzyn** [comment] 2023-06-17 19:35
Thanks @Skalakid! I'm going to add an engineer to this just to make sure I'm getting everything. Sounds like we'll fix this with https://github.com/Expensify/App/pull/20838

I added @bernhardoj as the C+ since you've already been discussed in this issue and an engineer for tracking. Let me know if there's anything else I need to do at this time!

**Comment by techievivek** [comment] 2023-06-19 06:53
Looks like @Skalakid is working on this issue. The assigned engineer on the PR is @Julesssss, and the assigned C+ is @s77rt, so I will fix the assignments here to keep everything in sync.

**Comment by s77rt** [comment] 2023-06-23 11:10
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/19612
- The offending PR has been commented on: https://github.com/Expensify/App/pull/19612#discussion_r1239679476
- A discussion in #expensify-bugs has been started: I doubt we have much to discuss, this could have been caught during testing
- Determine if we should create a regression test for this bug: No

**Comment by Christinadobrzyn** [comment] 2023-06-30 18:44
Looks like no regressions - paying this out - 

I think this is a regression of another bug, right so I would only pay the reporter? If that's not the case, will you please let me know if there's a speed bonus for this?

@Julesssss @s77rt

**Comment by s77rt** [comment] 2023-06-30 19:08
> This is a regression, right so I would only pay the reporter? If that's not the case, will you please let me know if there's a speed bonus for this?

Not a regression that was caught during regression period (i.e. not a regression from something that we worked on recently) so I think we should pay everyone here. No bonus though.

**Comment by Christinadobrzyn** [comment] 2023-06-30 21:40
Thanks @s77rt!

Here's the Upwork job posting: 

Internal: https://www.upwork.com/ab/applicants/1670152822418042880/job-details
External: https://www.upwork.com/jobs/~0110ed1d7d5b0b56cb

@s77rt as C+
@bernhardoj as reporter

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:38
Paid out based on https://github.com/Expensify/App/issues/20585#issuecomment-1615219217

Closing

**Closed by Christinadobrzyn** 2023-07-03 17:38 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
