### ISSUE TITLE
[HOLD on Auth#12130] [$250] [Xero] The newly selected exporter is changed after few seconds

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44398] opened 2024-06-25 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4663222
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace-- accounting
3. Tap export
4. Tap preferred exporter
5. Select the unchecked workspace admin

## Expected Result:
The newly selected exporter must not be changed after few seconds

## Actual Result:
The newly selected exporter is changed after few seconds

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3dca792e-0b12-47fd-9e54-f736f3bb77ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a35684251cade3f</li>
        <li>Upwork Job ID: 1808167463826946733</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment] 2024-06-25 14:58
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by diegohosilver** [comment] 2024-07-07 22:24
This is happening on desktop web as well 

https://github.com/Expensify/App/assets/20136219/39f21c9c-df3c-4421-94ba-c14e483010b4

**Comment by drminh2807** [comment] 2024-07-08 07:58
I can't change the exporter. It reverted back to the previous after a few seconds

https://github.com/Expensify/App/assets/12546908/8289101a-b884-460e-8eab-df0a39e52aa0

**Comment by drminh2807** [comment] 2024-07-09 02:19
Contributor details
Your Expensify account email: drminh2807@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0147ffcb350b578b95

**Comment by HTown2369** [comment] 2024-07-09 22:38
I believe this is a BE issue, because after changing the preferred exporter the console logs show an API request being made with the appropriate arguments, and a successful response from the server. However a few seconds after receiving the successful response, Pusher sends multiple events including an update to the preferred exporter, but the update Pusher delivers still has the old account set as the preferred exporter.

https://github.com/Expensify/App/assets/100219291/7c6a90fa-ec3e-4f49-8965-5a706acedab5

**Comment by HTown2369** [comment] 2024-07-09 22:41
Contributor details
Your Expensify account email: hredzic01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01929686b8d6175591

**Comment by diegohosilver** [comment] 2024-07-10 13:33
> This is happening on desktop web as well. (For some reason, the playback is not working correctly for me. If you are seeing the same problem download the video to watch the evidence)
> 
>  web.evidence.s.mp4

I also think this is a backend issue. All options in the Export menu present the same behavior except for *Purchase bill status*, which gets reverted only when another option is changed. 

![chrome_7ALo0WfWtj](https://github.com/Expensify/App/assets/20136219/5556e8ab-7b5f-477c-b8a6-eb71fd45b10d)

**Comment by miljakljajic** [comment] 2024-07-10 15:00
I can switch this to internal

**Comment by trjExpensify** [comment] 2024-08-08 21:18
Just a reminder to have `Internal` issues put in `Hot picks` to be surfaced for volunteers. Retested this one and it's still reproducible. 

https://github.com/user-attachments/assets/2328aa55-f425-4e77-8ae2-59c1e50c763c

CC: @aldo-expensify @lakchote @NikkiWines @francoisl for any thoughts!

**Comment by danielrvidal** [comment] 2024-08-19 13:11
@NikkiWines were you by chance picking this one up? I wasn't sure but we're going to be asking people to pick the hot picks up so I wasn't sure.

**Comment by NikkiWines** [comment] 2024-08-19 13:33
Ah no, sorry - I added the `reviewing` label here on accident, but I'm not working on this issue currently and  don't have the bandwidth to pick it up. The hotpick label should still apply.

**Comment by yuwenmemon** [comment] 2024-08-19 20:31
Also fixed with: https://github.com/Expensify/Auth/pull/12130

**Comment by garrettmknight** [comment] 2024-08-20 14:19
@miljakljajic mind keeping an eye on that Auth PR and retesting when it's deployed?

**Comment by mvtglobally** [comment] 2024-08-23 12:05
Issue not reproducible during KI retests. (First week)

**Comment by yuwenmemon** [comment] 2024-08-26 17:05
Yes

**Closed by yuwenmemon** 2024-08-26 17:05 UTC
Labels: Reviewing, Daily, Internal, Bug, Hot Pick
