### ISSUE TITLE
[$1000] Growl shows up on adding/deleting paypal account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13209] opened 2022-11-30 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Payments
2. Click add payment method > PayPal.me
3. Enter a user name
4. Press save

## Expected Result: 
The growl shouldn't show up

## Actual Result: 
The growl is still available

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204893035-4f43c6c9-82c6-450e-b9e6-4c89af02b642.mov

https://user-images.githubusercontent.com/43996225/204893052-259ca9bc-2acf-46d4-9955-b73fbade9bbc.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669765941027919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0128a643266df63294
- Upwork Job ID: 1598092514284437504

**Comment by Puneet-here** [comment] 2022-11-30 19:44
### Proposal
Remove the lines below
https://github.com/Expensify/App/blob/435c4b93e9e46f3d45b3913a1e30d8c2f2c107bb/src/pages/settings/Payments/AddPayPalMePage.js#L43
https://github.com/Expensify/App/blob/435c4b93e9e46f3d45b3913a1e30d8c2f2c107bb/src/libs/actions/User.js#L299
We also need to remove the message copy from en and es.js and we can also remove the copies of previous growls that we have removed
https://github.com/Expensify/App/blob/435c4b93e9e46f3d45b3913a1e30d8c2f2c107bb/src/languages/en.js#L407

**Comment by conorpendergrast** [comment] 2022-11-30 23:10
Checking if this is a bug [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1669849552617089?thread_ts=1669765941.027919&cid=C049HHMV9SM), and then will triage accordingly.

**Comment by conorpendergrast** [comment] 2022-11-30 23:11
This is not a bug, but should still be done 👍

**Comment by conorpendergrast** [comment] 2022-11-30 23:18
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [x] **The "bug" is actually a bug**: It's... [not actually a bug](https://expensify.slack.com/archives/C049HHMV9SM/p1669849774841279?thread_ts=1669765941.027919&cid=C049HHMV9SM). We should still do it! 
- [] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: [Nope](https://github.com/Expensify/App/issues?q=is%3Aissue+NOT+bugbot+NOT+QA+growl+is%3Aopen)
- [x] **The bug is reproducible, following the reproduction steps:** Yep! 
- [x] **If you’re unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: N/A
- [x] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** yep, looks good
- [X] **The GH was created by an Expensify employee or a QA tester:** Yep! 
- [X] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** Yep! 
- [X] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:** Done, external!

**Comment by conorpendergrast** [comment] 2022-11-30 23:19
Or to @aimane-chnaif to review [the proposal](https://github.com/Expensify/App/issues/13209#issuecomment-1332657784)

**Comment by conorpendergrast** [comment] 2022-12-01 06:57
Actually, rather than doing this piecemeal, we're going to remove them all via [this internal issue](https://github.com/Expensify/App/issues/13229). Closing for now!

**Closed by conorpendergrast** 2022-12-01 06:57 UTC
Labels: External, Daily, Help Wanted, Bug
