### ISSUE TITLE
[$1000]  Group chat - No whisper with email-only members and LHN preview shows concierge email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21421] opened 2023-06-23 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new..expensify.com
2. Go to + > Create group
3. Select a few members with email address
4. Create the group
5. Go to + > Create group
6. Select a few members with email address and phone number
7. Refresh the page

## Expected Result:
In Step 4, concierge whisper should show up
In Step 6 - 7, the LHN preview should show 'This is the beginning of your chat with...'

## Actual Result:
In Step 4, concierge whisper does not show up. This only occurs when the group is created with members with email address only.
In Step 6 - 7, the LHN preview shows concierge email - [concierge@expensify.com](mailto:concierge@expensify.com;)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/000552bd-f488-42d4-abc2-d98161acf7e1

https://github.com/Expensify/App/assets/78819774/20cc01f6-5c8f-49c1-975d-0d49ebaa595a

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da71fccd80415b9f</li>
        <li>Upwork Job ID: 1673792352484556800</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-06-26 03:52
I'm catching up from my half day, I'll review soon.

**Comment by alexpensify** [comment] 2023-06-27 20:36
Assigning `External` I confirm this is a bug. 

With a phone number account: 
![2023-06-27_13-33-59](https://github.com/Expensify/App/assets/8107070/f56d7638-d697-4067-8cb7-f846712bf591)

With emails only: 
![2023-06-27_13-33-47](https://github.com/Expensify/App/assets/8107070/6d87ce59-8672-4edc-9b63-3057bab830f2)

**Comment by pasyukevich** [comment] 2023-06-28 10:14
Hi,
I am from Callstack - an expert contributor group
I start to investigate this issue

**Comment by pasyukevich** [comment] 2023-06-28 16:18
I'm not able to reproduce on local and stage. 
<img width="1509" alt="image" src="https://github.com/Expensify/App/assets/23215729/0f0cb688-56df-4127-aafa-d92507afe5a8">

**Comment by alexpensify** [comment] 2023-06-28 23:17
@pasyukevich can you please confirm that one of the accounts you included is a cell phone number account? The key here is step # 6, "Select a few members with an email address and phone number".

**Comment by pasyukevich** [comment] 2023-06-29 11:45
@alexpensify I confirm that I checked this scenario too and it's also not reproduced.

**Comment by alexpensify** [comment] 2023-06-29 22:42
Reassigning another bug team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛 team: I've run out of time and haven't tested this one **_AGAIN_**. This needs another round of testing to confirm if it's a bug. I was able to reproduce it two days ago but if it's no longer an issue then let's close it out. Thank you!

**Comment by sonialiap** [comment] 2023-07-03 14:34
I can replicate both described behaviors on staging:
- No whisper when creating a group with 3 emails
- Yes whisper when creating a group with 2 emails and 1 phone number

**Comment by pasyukevich** [comment] 2023-07-05 11:47
Rechecked. I found that this bug has floating behavior. 
Sometimes it's constantly replicating, and then not. 

Yesterday reproduced on stage and locally, today I'm not able to reproduce on any env. 

Can this issue relate to the BE side? 

For me looks like that on the FE part items are just rendering and there is no logic related to the user with a phone number that can affect normal flow.

**Comment by pasyukevich** [comment] 2023-07-05 12:40
https://github.com/Expensify/App/assets/23215729/975997f6-a9cc-423c-9dab-5689669641bf

**Comment by sonialiap** [comment] 2023-07-06 15:31
@mollfpr do we need an internal engineer to check if this is a bedrock related error?

**Comment by mollfpr** [comment] 2023-07-10 15:13
Checking in.

**Comment by mollfpr** [comment] 2023-07-10 15:35
I can't reproduce it in DEV, and I am only able to reproduce it once in staging. If it's still an issue, I believe this will be a fix on the backend.

**Comment by alexpensify** [comment] 2023-07-10 21:18
Alright, removing the other 🐛 team member. I'm back online and see that this is our current state: 

@mollfpr do you fee like we should close this one out?

**Comment by mollfpr** [comment] 2023-07-12 14:41
@alexpensify I feel so. We don't have a consistent step to reproduce the issue.

**Comment by alexpensify** [comment] 2023-07-13 21:37
Ok, taking action and closing this one. Thank you!

**Closed** 2023-07-13 21:37 UTC
Labels: External, Daily, Help Wanted, Bug
