### ISSUE TITLE
[HOLD for payment 2024-07-24] Expense - "Unapprove" option exists on Manually reimbursed reports, on Collect policy with Instant Submit, Submit & Close

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45009] opened 2024-07-08 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Add approval settings in Workflow is disabled (submit and close mode).

1. Go to staging.new.expensify.com
2. Go to workspace chat as admin.
3. Submit an expense.
4. Go to transaction thread.
5. Go offline.
6. Pay elsewhere the report.
7. Click on the report header.
8. Note that there is no "Unapprove" option.
9. Go online.

## Expected Result:
There should be no "Unapprove" option after returning online because there is no approver.
On Old Dot, there is no "Unapprove" option for paid expense when the mode is Submit and close.

## Actual Result:
"Unapprove" option reappears after returning online when there is no approver.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bed80797-075b-4b3e-87b0-72aab9fdf892

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment] 2024-07-08 20:44
@JmillsExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-08 20:44
We think this issue might be related to the #collect project.

**Comment by thienlnam** [comment] 2024-07-08 20:53
Looks like this came from https://github.com/Expensify/App/pull/44229 where we added the Unapprove feature

cc @rushatgabhane @Beamanator

**Comment by thienlnam** [comment] 2024-07-08 20:55
Don't think this needs to be a deploy blocker since this is an edge case scenario

**Comment by JmillsExpensify** [comment] 2024-07-10 04:38
Added to wave-control in the meantime.

**Comment by Beamanator** [comment] 2024-07-11 10:57
A few notes when reproducing:
1. I don't believe we need the "Go offline then online" steps, I can reproduce in dev while doing everything online

**Comment by Beamanator** [comment] 2024-07-11 11:36
brought to slack: https://expensify.slack.com/archives/C036QM0SLJK/p1720697773830479

**Comment by garrettmknight** [comment] 2024-07-11 17:59
Following up from the slack conversation, we want to effectively hide `Unapprove` from all paid reports. Separately, paid reports should have the 'Cancel payment' option but that wasn't showing. We're fixing that elsewhere.

**Comment by Beamanator** [comment] 2024-07-12 13:37
PR up ^ - @rushatgabhane can you please review since you worked on the original App PR that this helps fix? :D

**Comment by rushatgabhane** [comment] 2024-07-12 14:04
yes ofcourse

**Comment by garrettmknight** [comment] 2024-07-12 17:26
**EOW Update:**
- We caught a bug for showing Unapproved [here](https://github.com/Expensify/App/issues/45009) - Alex is figuring out how to fix now that we’ve got consensus on the expected behavior.
- [Show warning modal if Report has been exported to connected accounting integration](https://github.com/Expensify/App/issues/44884) is still held on the accounting connections issue, but the Auth PR is merged so hopefully we’ll be able to take this off hold next week!

**Comment by Beamanator** [comment] 2024-07-12 19:05
@garrettmknight it loooks like that update was supposed to go on the main tracking issue? :D

**Comment by Beamanator** [comment] 2024-07-16 13:44
PR is in staging 👍

**Comment by JmillsExpensify** [comment] 2024-07-26 02:04
Payment summary above is correct. @rushatgabhane please fill out checklist and submit an expense in NewDot.

**Closed** 2024-07-26 02:04 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by rushatgabhane** [comment] 2024-07-26 02:08
1. The PR that introduced the bug has been identified. Link to the PR: This was my misunderstanding.

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

          1. Go to a collect workspace that has approvals ON
          2. Create a few manual requests
          3. Submit the report (this may happen automatically if the workspace is on instant submit)
          4. Have the admin approve the report
          5. As admin, Click on the report header - verify you see the "Unapprove" button
          6. Mark the report as "paid elsewhere"
          7. Click back on the report header - verify you DO NOT see the "Unapprove" button

**Comment by mallenexpensify** [comment] 2024-07-26 17:02
Contributor+: @rushatgabhane due $250 via NewDot 

TestRail GH
- https://github.com/Expensify/Expensify/issues/415660

**Comment by JmillsExpensify** [comment] 2024-07-29 23:19
$250 approved for @rushatgabhane
