### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web - Auto navigation back to user contacts when magic code is incorrect full filled and network is offline then online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23346] opened 2023-07-21 11:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login any account
2. Go to Settings -> Profile -> Contact method
3. Click "New contact method" button -> Fill in any email that is not Expensify account yet
4. Click on the secondary login that just added to verify it
5. Fill in incorrect magic codes
6. Go offline then online

## Expected Result:
It should stay in the validate secondary login after go online

## Actual Result:
 It navigates back to the user contacts page automatically although magic codes are incorrect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c5561bd6-d18b-4993-84ed-e12db969665d

https://github.com/Expensify/App/assets/93399543/04d69770-fd67-4471-8f60-917b0f75a1dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689868296938909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2d16d4070455f05</li>
        <li>Upwork Job ID: 1684763564552568832</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26569429</li>
<li>hoangzinh | Contributor | 26569430</li>
<li>hoangzinh | Reporter | 26569431</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-07-28 03:12
I can reproduce and can't find a dupe - I think this is unexpected behavior, but I think i've seen similar issues

**Comment by adelekennedy** [comment] 2023-07-31 21:52
@aimane-chnaif two proposals above!

**Comment by adelekennedy** [comment] 2023-08-07 18:58
pending proposal reviews

**Comment by adelekennedy** [comment] 2023-08-10 16:23
I don't want to adjust the bounty on this until the proposals above have been reviewed

**Comment by adelekennedy** [comment] 2023-08-15 16:27
pending proposal review

**Comment by adelekennedy** [comment] 2023-08-18 21:39
@aimane-chnaif bump on the review above!

**Comment by adelekennedy** [comment] 2023-08-21 17:47
pending review

**Comment by adelekennedy** [comment] 2023-08-25 19:26
@aimane-chnaif can review the updated proposals above early next week or provide an eta on when you'll be able to review?

**Comment by adelekennedy** [comment] 2023-08-30 21:44
@aimane-chnaif will you review the proposals this week?

**Comment by adelekennedy** [comment] 2023-09-04 18:38
@aimane-chnaif any thoughts?

**Comment by adelekennedy** [comment] 2023-09-21 12:15
Payouts due:

Contributor: $1250 @hoangzinh (reporting bonus + contributor)
Contributor+: $1000 @aimane-chnaif 

Eligible for 50% #urgency bonus? **Y**

Upwork job is [here](https://www.upwork.com/ab/applicants/1684763564552568832/hired).

**Comment by yuwenmemon** [comment] 2023-09-25 03:59
@adelekennedy can we close this out?

**Comment by adelekennedy** [comment] 2023-09-25 07:03
I just checked the Upwork job and it looks like everyone is paid out

**Closed by adelekennedy** 2023-09-25 07:03 UTC
Labels: External, Daily, Awaiting Payment, Bug
