### ISSUE TITLE
The report preview is not removed when request is made offline and becomes stale

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26264] opened 2023-08-29 22:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as User A and User B in front of you at the same time.
2. As User A Go offline
3. As User A requests Money from User B ( make sure it works by avoiding the bugs around the IOU feature Now )
4. As User B open the chat and request money from User A.
5. Now back to User A and go online.

## Expected Result: - 
There is only one report preview for both User A and User B

## Actual Result: 
User A has two report previews, the second one is the correct one but the first one is the stale report preview which needs to be removed with pusher update when this collision happens. Its linking to the previously optimistically created report which is stale and no longer valid.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/77763699/abe3e7cf-5f93-468b-9186-15dbcf697fff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692590693071889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d18debe98d8308dd</li>
        <li>Upwork Job ID: 1699073811659808768</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26983423</li>
<li>Ahmed-Abdella | Reporter | 26983426</li>
</ul></li>
    </ul>
</details>

**Comment by Ahmed-Abdella** [comment] 2023-08-29 22:40
Important notice:
The behavior here differs based on whether User B's request is smaller or larger than User A's.
1. If user B's request is smaller It behaves exactly like the report steps and results. The first money request is not calculated (see the first video in the report)

2. If user B's request is larger, the money amount will be calculated, but there are bugs such as the first money request from user A while offline resulting in a broken link that opens a "page not found" error.

**So, To reproduce all the bugs related to this issue, request a smaller amount as User B.**

**Comment by isabelastisser** [comment] 2023-08-30 21:37
I'm heading OOO now and will be back on Sept 5; I will reapply the Bug label but leave myself assigned in case I need to action this once I'm back. Thanks!

Summary: I haven't touched this issue yet, so all the triage steps are pending.

**Comment by mollfpr** [comment] 2023-09-11 16:49
No new proposals.

**Comment by michaelhaxhiu** [comment] 2023-09-11 19:34
Doubling price since this isn't moving, and also noticing it's not assigned to me (oopsie!) haha hope that's at least a lil helpful isa

**Comment by michaelhaxhiu** [comment] 2023-09-12 10:28
lol we did double melvin ^

**Comment by isabelastisser** [comment] 2023-09-13 17:51
Not overdue, we doubled the payment price. Waiting for proposals!

**Comment by mollfpr** [comment] 2023-09-18 14:05
No new proposals.

**Comment by isabelastisser** [comment] 2023-09-20 20:35
Hey @mollfpr, can we still reproduce this?

**Comment by Ahmed-Abdella** [comment] 2023-09-20 23:31
@isabelastisser I checked it and it is still reproducible

**Comment by isabelastisser** [comment] 2023-09-25 15:02
Still waiting for proposals!

**Comment by isabelastisser** [comment] 2023-09-25 15:08
I posted for discussion [here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1695654464965259)

**Comment by barttom** [comment] 2023-09-26 10:40
Hello!
I'm Bartek from Callstack - an expert contributor group and I would like to work on this one.
I'll send the proposal soon.

**Comment by isabelastisser** [comment] 2023-09-26 13:38
@barttom thanks!! I just assigned you to the issue.

**Comment by barttom** [comment] 2023-09-27 14:30
I'm still debugging this one, cannot reproduce all bugs.
However, realize some weird behavior, please check the video. 
I'm wondering why in the scenario when: the first user who was offline and requested more money from the second user -  needed to pay after getting a connection.

In the same scenario, when both users were online, the second user needed to pay a difference 
is it another bug?

**Comment by isabelastisser** [comment] 2023-09-27 19:02
Thanks @barttom. I'm not sure! @mollfpr, can you please review the comment above to clarify? Thanks!

**Comment by barttom** [comment] 2023-09-28 07:07
@mollfpr I want to precise expected result.
I've checked scenario for the online status for both users and looks like requests updates instead of sending one by one.
So maybe should be like this: request created on offline status should be updated instead of sent to the user B. Now it redirects to nowhere.

https://github.com/Expensify/App/assets/7682108/767865b7-3292-4eee-9961-b30552c5eab7

https://github.com/Expensify/App/assets/7682108/a3915908-e7c9-4bc2-94da-cf2a36cb3668

**Comment by mollfpr** [comment] 2023-09-28 13:48
>I've checked scenario for the online status for both users and looks like requests updates instead of sending one by one.

This is the correct behavior.

>So maybe should be like this: request created on offline status should be updated instead of sent to the user B. Now it redirects to nowhere.

Yes, it should be updated the existing IOU report from the BE. The problem is the IOU reportID from offline does not exist because it's created optimistically and doesn't match with returned IOU data from the API response. This only happen if currently the user doesn't have existing transaction going on.


The other issue I found weird is that user B who requested more amount than user A is the one who has the pay button.

![Screenshot 2023-09-28 at 20 37 58](https://github.com/Expensify/App/assets/25520267/3a146546-a9e4-4f36-8be9-2d77f599d415)

>The first money request ( requested by Offline User A ) should be sent to User B.

I also think the expected result in this issue is not clear enough. All the request money is placed in one IOU, and as we do the test, both requests of money are sent.

**Comment by mollfpr** [comment] 2023-09-28 14:04
Here's the actual result from the issue description, I made in number list so it will be easy to point each of them.

1. User B didn't receive the first money request (requested by Offline User A) after requesting one.
2. The message of The first money request ( requested by Offline User A ) still appear for User A but Not User B
3. The second money request from User B can be paid by User A without considering the first request.
4. If User A paid the second request, The message of the first request would appear with anonymous avatar and no particpant name.

The **_first_** issue is not an actual issue; it's expected since we only made one IOU report for the existing transaction. We can ignore this.

The **_second_** and **_fourth_** issues can be fixed if the report action from the offline request money is removed after we get the response from the API.

I can't understand the _**third**_ issue.

**Comment by Ahmed-Abdella** [comment] 2023-09-29 01:38
> I can't understand the _**third**_ issue.

@mollfpr I am referring to what happened in the scenario below 

- if user A requested 10 while offline
- User B requested 4
- then User A back online

User B is the one who should be given the option to pay 6 since User A requested 10 and user B requested 4.

However the actual result is that  > User A can pay without the first request being calculated. While he shouldn't have the option to pay because User B is the one who should pay

that is what I meant by "The second money request from User B can be paid by User A without considering the first request." 

- the first request is not calculated and the second request can be paid by user A

I hope I was able to clarify this. Sorry if I couldn't find a good way to explain it. :smile: 

However, I believe the calculation has changed. I will create a new screen recording with the updated result.

**Comment by Ahmed-Abdella** [comment] 2023-09-29 02:36
How the calculation should be for the video below (Expected result)
- User A requested 10 while offline
- User B requested 4
- User B back online

Now user B is the one who should have the option to pay 6


UPDATED ACTUAL RESULT

After User A back online

- The first request  ( 10 ) message appears for User A without the name of the user who owes. it should be "User B owes:".  And by clicking on the message you open a room with infinite loading 
UI skeleton

- The Two requests now is shown for User B, But it shows that User A is the one who owes (the User who should pay 6) while it should be User B

Now reload the page for User A

- The Two requests now is shown for User A, But it shows that User A is the one who owes (the User who should pay 6) while it should be User B

[Screencast from 29-09-23 05:08:30.webm](https://github.com/Expensify/App/assets/77763699/3a1c2a04-1026-4355-b38a-e64c94b52361)

**Comment by waterim** [comment] 2023-10-02 13:44
Hello, Im Artem from Callstack - expert group
@barttom is OOO for 2 weeks and Im taking this over

**Comment by mollfpr** [comment] 2023-10-02 14:11
Thanks @waterim! Let me know if you have questions about the issue!

**Comment by isabelastisser** [comment] 2023-10-02 16:31
@waterim @mollfpr what are the next steps here? Thanks!

**Comment by mollfpr** [comment] 2023-10-02 16:35
@isabelastisser We can assign this to @waterim to prevent someone from posting a proposal here.

**Comment by Ahmed-Abdella** [comment] 2023-10-02 17:08
@isabelastisser  Should I accept this offer. And if yes, could you plz check if this should be at 250$ or not, it was reported (30 Aug 1AM) for me, For you it could be (29 Aug),But in general it was reported before rate changes. So please verify if it should be 50$ or 250$? Thank you.

**Comment by mollfpr** [comment] 2023-10-04 15:49
@isabelastisser We need someone from the internal engineer to answer the above question; I don't have the answer regarding the backend response.

**Comment by mollfpr** [comment] 2023-10-09 18:12
@isabelastisser Can you pull someone from the internal engineer here? Thanks!

**Comment by mollfpr** [comment] 2023-10-16 07:12
Friendly bump @isabelastisser

**Comment by isabelastisser** [comment] 2023-10-18 16:29
Assigning engineering to help with the questions above!

**Comment by bondydaa** [comment] 2023-10-18 19:52
any debit in the system is recorded as a negative number so that's why it's coming back as `-1000` and that is expected. 

positive numbers mean a credit.

@thienlnam @mountiny @luacmartins I think ya'll were involved in manual requests and hopefully have more insight here 🙏  Can you chime in more on and confirm that in the code we send values as positives when requesting money from someone even though in the backend we store everything as a negative?

**Comment by luacmartins** [comment] 2023-10-18 19:56
AFAIK transaction amounts on IOU reports are stored as positive values and transactions amounts on expense reports are stored as negative

**Comment by mountiny** [comment] 2023-10-19 00:00
1. Expnse report ransactions are opposite sign so if you request $1 it will be -100 amount in the transactions table
2. however for IOU reports the "polarity" depends on who is owner of the report, if you request $10, the amount will be positive 1000
3. When your friend however request back from you $5, that particular transaction will be negative (-500) so the total is a sum of all the amounts hence $5. The owner of the IOU report is the one who is owed  and whose requests should be positive.

**Comment by waterim** [comment] 2023-10-19 14:18
@mountiny Get it, but as you can see from my screenshots, response from requestMoney API has -1000, thats why it shows to the offline user that he needs to pay, thats why Im not sure that it is a frontend bug here

**Comment by mountiny** [comment] 2023-10-19 23:04
Looking at the OP, this sounds to me like we are not handling the collision of the ids well as well as the clean up, this used to work, but there must have been some regression.

Basically when userA creates the money request offline, they create a new optimistci report with new reportID. This is not in server though since they are offline.

Then userB actually creates a new IOU report which will have different reportID. The request from userA then collides with the one from userB as its trying to create a new IOU report between these two users even if it already existed.

We have to ensure in the backend that we are gracefully adding the request to the userB created IOU report, letting the PHP know so we can pass clean up onyx update which will remove the iouReport data we set optimistically

**Comment by isabelastisser** [comment] 2023-10-23 16:06
Not overdue.

**Comment by bondydaa** [comment] 2023-10-24 21:29
i'm dropping this to weekly since it's been open since August and clearly doesn't need daily updates. Going to un-assign myself as well since that was just from engineering label.

**Comment by isabelastisser** [comment] 2023-11-02 19:52
I'm not sure what are the next steps here, can someone please clarify? Thanks! Is anyone working on this, should this be closed?

**Comment by isabelastisser** [comment] 2023-11-13 19:25
@vitHoracek @barttom @mollfpr @waterim I'm still trying to figure out what are the next steps here. Can someone please clarify? Thanks! Is anyone working on this? Should this be closed?

**Comment by mountiny** [comment] 2023-11-27 21:16
@isabelastisser @kavimuru is this still reproducible error?

**Comment by isabelastisser** [comment] 2023-11-27 21:23
I can no longer reproduce this, can you @kavimuru @barttom @waterim ?

**Comment by Ahmed-Abdella** [comment] 2023-11-27 23:39
Hi @isabelastisser, the calculation of the requests works fine nowm, but there is still an issue here and it is reproducible if you request a smaller money as user B this message appear

![Screenshot 2023-11-28 at 1 24 15 AM](https://github.com/Expensify/App/assets/77763699/5aff0d39-dbb2-4be2-b65f-84dba7af3b97)

and Clicking  it open a "Hmm... it's not here" page

**just make sure to request a smaller amount as UserB**


https://github.com/Expensify/App/assets/77763699/abe3e7cf-5f93-468b-9186-15dbcf697fff

**Comment by mountiny** [comment] 2023-11-28 11:15
Seems like the original issue in the OP is resolved then, the offline request got correctly linked to the appropriate IOU report.

What I think its happening here with the `TBD` report preview is that we had the optimistic IOU report and the report preview and when the request was made online, this became stale as the data from user B is canonical, saved in the database. 

This should be internal and the solution is to make sure we send pusher update which deleted the reportAction of the stale report preview in this case.

**Comment by mountiny** [comment] 2023-11-28 11:19
@isabelastisser I have updated the issue title and body to reflect whats going on, can you label the issue with Engineering to get internal engineer assigned?

**Comment by danieldoglas** [comment] 2023-12-11 15:05
Still didn't have the time to look into this one.

**Comment by danieldoglas** [comment] 2023-12-22 04:27
I'll be OOO starting this Friday, and will tackle this when I'm back

**Comment by isabelastisser** [comment] 2024-01-02 17:55
Not overdue.

**Comment by isabelastisser** [comment] 2024-01-11 18:54
No updates.

**Comment by isabelastisser** [comment] 2024-01-22 11:21
No updates.

**Comment by isabelastisser** [comment] 2024-01-30 17:33
Any updates @danieldoglas ?

**Comment by danieldoglas** [comment] 2024-01-31 20:32
@isabelastisser I haven't really worked on this yet, but based on our new rules, we should find a wave and fit it into the wave now. Considering that it's related to requests I think it should fit into wave5. And it should probably enter the priority system of that wave.

Can you please post it there?

Thanks!

**Comment by isabelastisser** [comment] 2024-02-02 01:15
Yes, thanks for the heads up @danieldoglas! :)

**Comment by isabelastisser** [comment] 2024-02-02 01:26
Asking [here.](https://expensify.slack.com/archives/C05DWUDHVK7/p1706837147837799)

**Comment by isabelastisser** [comment] 2024-02-13 17:40
Bumped the question in Slack. https://expensify.slack.com/archives/C05DWUDHVK7/p1707845988509359

**Comment by youssef-lr** [comment] 2024-02-13 19:16
I think this was fixed [here](https://github.com/Expensify/Web-Expensify/pull/40608). Reproduction steps look the same.

**Comment by isabelastisser** [comment] 2024-02-13 19:36
Thanks for the heads up, @youssef-lr! Closing this.

**Closed by isabelastisser** 2024-02-13 19:36 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by Ahmed-Abdella** [comment] 2024-03-12 11:30
Hey, @isabelastisser, Sorry but shouldn't this be eligable for reprting bonus?

**Comment by mountiny** [comment] 2024-03-12 15:20
Discussed in slack, no reporting bonus
