### ISSUE TITLE
Workspace - Tooltip is miising on hover in invite members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25895] opened 2023-08-24 20:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces >members
2. Click on invite button
3. Hover on profile pic off

## Expected Result:
Should show tooltip with name or email

## Actual Result:
Does not show tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/8d111e6d-50da-4716-b85e-06aeb20b4117

https://github.com/Expensify/App/assets/78819774/7782ec30-90bb-4fb8-8dcb-c96354945712

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Manan Gadhiya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692776872885369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2023-08-24 21:52
Asking here about opinions: https://expensify.slack.com/archives/C01GTK53T8Q/p1692913823483759
I think we should just close this, the old behaviour was useless.

**Comment by aldo-expensify** [comment] 2023-08-25 05:39
@rushatgabhane agreed, I didn't think of that. And yes, that PR is my suspect too hehe

**Comment by s-alves10** [comment] 2023-08-25 13:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tooltip isn't shown on hover avatar in invite members page

### What is the root cause of that problem?

We don't have tooltip for avatar in the newly refactored `SelectionList` in [this PR](https://github.com/Expensify/App/pull/22622)

Please check the below code
https://github.com/Expensify/App/blob/4362fe76cee9450becc3f9f6de520955c94f8a71/src/components/SelectionList/CheckboxListItem.js#L42-L49

### What changes do you think we should make in order to solve the problem?

We need to wrap the avatar with the [UserDetailsTooltip](https://github.com/Expensify/App/blob/main/src/components/UserDetailsTooltip/index.web.js)
```
        {Boolean(item.avatar) && (
            <UserDetailsTooltip
                accountID={item.accountID}
                icon={item.avatar}
                fallbackUserDetails={{
                    displayName: props.icons[1].name,
                    avatar: props.icons[1].avatar,
                }}
            >
                <View>
                    <Avatar
                        containerStyles={styles.pl5}
                        source={lodashGet(item, 'avatar.source', '')}
                        name={lodashGet(item, 'avatar.name', item.text)}
                        type={lodashGet(item, 'avatar.type', CONST.ICON_TYPE_AVATAR)}
                    />
                </View>
            </UserDetailsTooltip>
        )}
```

This works fine as expected

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-08-25 15:04
@thiagobrez will cover this one too https://expensify.slack.com/archives/C01GTK53T8Q/p1692975527845569?thread_ts=1692952886.670059&cid=C01GTK53T8Q

**Comment by mountiny** [comment] 2023-08-25 15:09
I think this does not have to be a deploy blocker, its minor issue

**Comment by mountiny** [comment] 2023-08-25 15:09
But @thiagobrez will still address it as an author of the PR which caused the regression just to be clear :D

**Comment by aldo-expensify** [comment] 2023-08-25 19:48
Thanks @vitHoracek !

**Comment by aldo-expensify** [comment] 2023-08-25 19:49
Lol, that is fake Vit

**Comment by thiagobrez** [comment] 2023-08-28 15:22
Update: PR being reviewed internally

**Comment by thiagobrez** [comment] 2023-08-28 17:11
PR is ready to review here: https://github.com/Expensify/App/pull/26091

**Comment by thiagobrez** [comment] 2023-09-21 10:33
I believe this should be closed, as it was deployed to prod 3 days ago

**Closed** 2023-11-20 13:09 UTC
Labels: Reviewing, Engineering, Monthly, Bug
