### ISSUE TITLE
Android - Settings - After savings the profile settings, the edited cells remains highlighted

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9015] opened 2022-05-14 10:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in app
2. Open any account
3. Navigate to settings by clicking on the user avatar over LHN
4. Click on Profile
5. Click on “Preferred Pronouns”
6. Select any of the options.
7. Select any of the available timezones.

## Expected Result:
After pressing the Save button, there should be no selected cells

## Actual Result:
After saving the settings by clicking on the Save button - 2 cells highlighted in blue

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/168422466-09d8d288-f881-4545-a828-30fe13ad9da3.jpg" width="40%">

https://user-images.githubusercontent.com/43996225/168422470-fd06fc97-9e27-4177-9383-8fd68454b02e.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-05-15 23:01
Not sure if this is worth fixing, tbh

**Comment by roryabraham** [comment] 2022-05-18 02:02
@kavimuru looks like @parasharrajat is saying that the fix for this issue was deployed to production today. Can you please retest on staging and production?

**Comment by isagoico** [comment] 2022-05-23 18:58
Issue is not reproducible anymore 🎉Closing

https://user-images.githubusercontent.com/44479856/169887938-4dc3c288-8851-4a4b-9fb4-9c62b94585ec.mp4

**Closed by isagoico** 2022-05-23 18:58 UTC
Labels: Reviewing, Engineering, Daily
