### ISSUE TITLE
Dev: When creating an offline task, the assignee disappears upon returning online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22611] opened 2023-07-11 03:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and go offline
2. Go to the "Assign task" section
3. Enter a title and description for the task
4. Select an assignee for the task and create it
5. Click on the description and make edits
6. Return back online after editing the description
7. Upon returning online, observe that the previously selected assignee is no longer associated with the task
## Expected Result: 
The assignee selected during the creation of an offline task should persist and remain intact when returning to an online state
## Actual Result: 
When creating an offline task, the assignee disappears upon returning online

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fa2ca2cf-3ebe-402d-ba58-b54268dc0e72

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689019736670219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-11 08:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating an offline task and editing the task title or description, the assignee disappears upon returning online.

### What is the root cause of that problem?
When creating an offline task, the optimistic task report data will be saved to `Onyx`.
https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/libs/actions/Task.js#L46-L47
https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/libs/ReportUtils.js#L1890-L1903
The optimistic task report does not have `managerEmail`.

When editing the task title or description, `Task.editTaskAndNavigate` will be called, and `assignee` parameter is empty.
https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/pages/tasks/TaskDescriptionPage.js#L46
`EditTask` API's parameter is generated as below.
https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/libs/actions/Task.js#L397-L409
Since the task report's `managerEmail` is empty and `assignee` is also empty, so the API's `assignee` parameter is empty.

Therefore, after return to online mode, `EidtTask` API request only have `managerID`, and does not have `managerEmail` parameter, and BE responds the task report that have empty `managerEmail` and 0 `managerID`.
![Screenshot 2023-07-11 042448](https://github.com/Expensify/App/assets/131836113/38ad0ec3-ddb4-411f-b260-683337e1a523)

So the assignee disappears upon returning online.

### What changes do you think we should make in order to solve the problem?
We should add `managerEmail` into the optimistic task report when creating task.

We can add `assignee` parameter to `ReportUtils.buildOptimisticTaskReport` function.
```js
-   function buildOptimisticTaskReport(ownerEmail, ownerAccountID, assigneeAccountID = 0, parentReportID, title, description) {
+   function buildOptimisticTaskReport(ownerEmail, ownerAccountID, assignee = '', assigneeAccountID = 0, parentReportID, title, description) {
        return {
            reportID: generateReportID(),
            reportName: title,
            description,
            ownerEmail,
            ownerAccountID,
+           managerEmail: assignee,
            managerID: assigneeAccountID,
            type: CONST.REPORT.TYPE.TASK,
            parentReportID,
            stateNum: CONST.REPORT.STATE_NUM.OPEN,
            statusNum: CONST.REPORT.STATUS.OPEN,
        };
    }
```

And we should pass `assignee` to `ReportUtils.buildOptimisticTaskReport` in [this line](https://github.com/Expensify/App/blob/e299de5cf3db15f40e2aeafd5060810a28464d64/src/libs/actions/Task.js#L47).
```js
-   const optimisticTaskReport = ReportUtils.buildOptimisticTaskReport(currentUserEmail, currentUserAccountID, assigneeAccountID, parentReportID, title, description);
+   const optimisticTaskReport = ReportUtils.buildOptimisticTaskReport(currentUserEmail, currentUserAccountID, assignee, assigneeAccountID, parentReportID, title, description);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by johncschuster** [comment] 2023-07-11 17:48
@ayazhussain79 did you mean to say

> Now reproducible on staging

or was that meant to say, "**not** reproducible on staging"?

**Comment by ayazhussain79** [comment] 2023-07-11 18:01
@johncschuster PR was not on staging that's why i write dev, now PR is on staging so you can reproduce it

**Comment by ayazhussain79** [comment] 2023-07-11 18:04
It's regression of this [PR](https://github.com/Expensify/App/pull/20841)

**Comment by johncschuster** [comment] 2023-07-13 12:59
Got it. Thanks for surfacing that!

cc @jasperhuangg

**Comment by johncschuster** [comment] 2023-07-17 14:53
I pinged Jasper so we can chat through how we'll handle the regression. He's unwell at the moment, so I'll keep Melvin happy until Jasper's back to 100%.

**Comment by jasperhuangg** [comment] 2023-07-24 18:17
This doesn't appear to be happening still, we fixed this in an old PR. Closing

**Closed by jasperhuangg** 2023-07-24 18:17 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by ayazhussain79** [comment] 2023-07-24 18:23
@jasperhuangg I'm not eligible for reporting bonus as it is 2 weeks old bug
