### ISSUE TITLE
Web - App Crashes when reloading after editing the Merchant

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26181] opened 2023-08-29 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money from user A
2. Go the report
3. Click on the Merchant to edit
4. Clear the field and click on Save
Notice 'removed the merchant (previously "Request")' message appears
5. Refresh the page

## Expected Result:
The app does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f99358ed-8157-4dc3-a36b-e28a8597bbff

https://github.com/Expensify/App/assets/93399543/8e18e9c3-6be8-494f-aa5f-fea7cabea6d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693277798912359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-08-29 11:38
Merchant cannot be empty thats backend restriction, we probably need to add a validation here

**Comment by Pujan92** [comment] 2023-08-29 11:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't set empty the merchant field 

### What is the root cause of that problem?
We don't have any validation to not allow empty value for merchant.

### What changes do you think we should make in order to solve the problem?
Add `validate` function and pass it to the the `Form` by setting the `merchant` as a required field.

```
const validate = (values) => {
        const requiredFields = ['merchant'];
        const errors = ValidationUtils.getFieldRequiredErrors(values, requiredFields);
        return errors;
    }
```

**Comment by MariaHCD** [comment] 2023-08-29 12:02
cc: @koko57 Please let us know what you find, thanks!

**Comment by koko57** [comment] 2023-08-29 12:49
@MariaHCD I couldn't reproduce it locally, I managed to reproduce it on staging so it's hard for me to tell what the RC is. I think that if we don't want to change the merchant to the empty string, the solution @Pujan92 proposes should work here

**Comment by Pujan92** [comment] 2023-08-29 12:59
I am able to reproduce the crash locally also due to incorrect orders bcoz whenever we refresh the money request report we won't get `pendingFields` in the api onyx response which causes the issue(accessing undefined of pendingFields).

**Comment by MariaHCD** [comment] 2023-08-29 13:03
That makes sense, thanks @Pujan92.

One thing about your proposal:

> Reason for a crash might be: Conditions are in the wrong order for all the fields here. First, we need to check for pendingAction availability in the transaction and then check for specific child fields.

Do you mean we first need to check for `pendingFields` in the `transaction` before trying to fetch any child fields?

**Comment by MariaHCD** [comment] 2023-08-29 13:16
Okay, I was finally able to reproduce the issue on staging and saw the console error:

![Screenshot 2023-08-29 at 5 13 51 PM](https://github.com/Expensify/App/assets/12268372/c2a7d4be-4f15-4ced-bec1-d3bd87aa9a0b)

https://github.com/Expensify/App/assets/12268372/b3a17751-4e2f-4021-b619-4ba36c63998b

**Comment by pradeepmdk** [comment] 2023-08-29 14:14
@koko57 looks like same https://github.com/Expensify/App/issues/26204

**Comment by Pujan92** [comment] 2023-08-29 14:15
I think reconnetApp api returns reportActions in the wrong structure. Needs to be an object but receiving array.

<img width="1272" alt="Screenshot 2023-08-29 at 19 43 57" src="https://github.com/Expensify/App/assets/14358475/e0173e00-23dc-49a9-bd32-5bcf38c70871">

**Comment by koko57** [comment] 2023-08-29 14:32
@parasharrajat I could reproduce it locally on main when I switched to using staging server

**Comment by koko57** [comment] 2023-08-29 14:33
and yeah, I agree with @Pujan92 that it should be checked on the BE

**Comment by Pujan92** [comment] 2023-08-29 14:41
> I can not reproduce this issue on the main. I also think that merchant is removable otherwise why would we show removed?

Even if we try to Save by clearing the input, it passes the previousValue(not the empty value) and returns some error message in response(`Call to a member function getDisplayInformation() on null`).
https://github.com/Expensify/App/blob/4675db5348e305daca320f91066476344191d8d2/src/libs/TransactionUtils.js#L211-L213
I think we are showing based on the optimistic onyx data.


https://github.com/Expensify/App/assets/14358475/ad1f638d-92cd-418b-8b9f-f62904410b21

**Comment by MariaHCD** [comment] 2023-08-29 14:56
> I think reconnetApp api returns reportActions in the wrong structure. Needs to be an object but receiving array.

👀 Interesting, looking if something changed on the backend.

![Screenshot 2023-08-29 at 6 55 34 PM](https://github.com/Expensify/App/assets/12268372/f36c0944-9178-465d-bb79-0748ad8df99e)

**Comment by MariaHCD** [comment] 2023-08-29 15:15
Regarding the format of the report actions, I am checking this internal PR: https://github.com/Expensify/Web-Expensify/pull/38626

**Comment by luacmartins** [comment] 2023-08-29 20:10
Fix here - https://github.com/Expensify/Web-Expensify/pull/38665. This is not an App blocker, so gonna remove the label.

**Comment by chiragsalian** [comment] 2023-08-29 20:55
Resolved on staging with a web-E CP. Closing issue. If it persists feel free to reopen.

**Comment by Pujan92** [comment] 2023-08-30 03:26
@chiragsalian aren't we supposed to fix the validation part of the merchant here?

**Comment by daveSeife** [comment] 2023-08-30 07:02
@chiragsalian I can repro the issue in the latest build. Reverting this https://github.com/Expensify/App/pull/25675 might have resolved the issue. 

Am I eligible for reporting bones?

**Comment by mountiny** [comment] 2023-08-31 08:11
@daveSeife Yes

$250

**Comment by mountiny** [comment] 2023-08-31 09:19
Created a PR which will not allow empty merchants

**Comment by mountiny** [comment] 2023-08-31 21:19
@trjExpensify I think we can already pay out the reporting bonus $250, the crash is fixed now

**Comment by trjExpensify** [comment] 2023-09-01 10:52
Okay, perfect. @daveSeife I've sent you an offer.

**Comment by daveSeife** [comment] 2023-09-01 10:58
@trjExpensify Accepted the offer. Thank You!

**Comment by trjExpensify** [comment] 2023-09-01 11:09
Perfect, paid!

**Closed by trjExpensify** 2023-09-01 11:09 UTC
Labels: Reviewing, Engineering, Weekly, Bug
