### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34852] opened 2024-01-20 15:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Create a new WS
4. Navigate to the WS settings
5. Click the Members tab
6. Invite a user with a VOIP or landline
7. If required, delete the add Members error message
8. Return to the WS settings menu

## Expected Result:
After removing the error of adding a member to WS, the red dot should disappear

## Actual Result:
After removing the error of adding a member to WS, the red dot remains in the RHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c37873d6-c304-4338-aeaf-7ae680ae72ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015688669ede8e962b</li>
        <li>Upwork Job ID: 1748730789626449920</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-20 15:35
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by bernhardoj** [comment] 2024-01-20 15:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a member that will gives an error, the member is hidden from the list.

### What is the root cause of that problem?
The member will not be included in the list if the personal detail is missing.
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/workspace/WorkspaceMembersPage.js#L318-L321

When we add a new member, we will add a new optimistic personal detail.
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L95-L138

And we add a `finallyData` that will be merged whether it fails or success to clear the optimistic personal detail. When fail, we lost the optimistic personal detail, thus the member is hidden.

### What changes do you think we should make in order to solve the problem?

Don't use. finally data to clear the optimistic personal detail, but use success data

**Comment by Tony-MK** [comment] 2024-01-22 00:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### What is the root cause of that problem?

The purpose for `finallyData` is to cleanup the `newPersonalDetailsOnyxData` set in the `${ONYXKEYS.COLLECTION.PERSONAL_DETAILS_LIST}` collection, because the backend will set realistic data needed for each new member and might cause double `personalDetails` .

The `addMembersToWorkspace` function creates the `optimisticMembersState` and  `failureMembersState` in the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L110-L114
When a user is not found, the `onyxData` response is an empty array but the `failureMembersState` is set while the `personalDetails` is deleted. 

Hence, `failureMemberState` is not deleted because it expected to be deleted in the `OfflineFeedback`'s `onClose` function. 

### What changes do you think we should make in order to solve the problem?

Amend the `failureMembersState` to make sure that  `errors` is not created and the `pendingAction` and `optimisticMembersState` is deleted from the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection when the `AddMembersToWorkspace` repsonse arrives.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L399

Therefore, the line above should similiar to the on below.

`failureMembersState[accountID] = null;`

**Comment by Tony-MK** [comment] 2024-01-22 00:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### What is the root cause of that problem?

The purpose of `finallyData` is to clean up the `newPersonalDetailsOnyxData` set in the `${ONYXKEYS.COLLECTION.PERSONAL_DETAILS_LIST}` collection, because the backend will set realistic data needed for each new member and might cause double `personalDetails` .

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L110-L114

The `addMembersToWorkspace` function creates the `optimisticMembersState` and  `failureMembersState` in the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection. 

![response](https://github.com/Expensify/App/assets/22982173/3aff13da-7298-433a-8255-413ae40ba94b)

When a user is not found, the `onyxData` response is an empty array but the `failureMembersState` is set while the `personalDetails` is deleted. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L662-L664

Hence, `failureMemberState` is not deleted because it is expected to be deleted by the `OfflineFeedback`'s `onClose` function when the admin dismisses the error. 

### What changes do you think we should make in order to solve the problem?

Amend the `failureMembersState` to make sure that  `errors` are not created and the `pendingAction` and `optimisticMembersState` are deleted from the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection when the response to the `AddMembersToWorkspace` endpoint arrives.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L601

Therefore, we should change the line above to be similar to the one below.

`failureMembersState[accountID] = null;`

*Result*

https://github.com/Expensify/App/assets/22982173/a7eb25c9-2e1b-41f3-a22b-4893404a286b

**Comment by Tony-MK** [comment] 2024-01-22 01:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### What is the root cause of that problem?

The purpose of `finallyData` is to clean up the `newPersonalDetailsOnyxData` set in the `${ONYXKEYS.COLLECTION.PERSONAL_DETAILS_LIST}` collection because it might cause double `personalDetails` to be stored since the backend will either set nothing or new realistic data required for each new member.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L110-L114

The `addMembersToWorkspace` function creates the `optimisticMembersState` and  `failureMembersState` in the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection. 

![response](https://github.com/Expensify/App/assets/22982173/3aff13da-7298-433a-8255-413ae40ba94b)

When a single member is non-existent, the `onyxData` response is an empty array, but the `failureMembersState` is set while the `personalDetails` is deleted. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L662-L664

Hence, `failureMemberState` is not deleted because it is expected to be deleted by the `OfflineFeedback`'s `onClose` function when the admin dismisses the error. 

### What changes do you think we should make in order to solve the problem?

Amend the `failureMembersState` to make sure that  `errors` are not created and the `pendingAction` and `optimisticMembersState` are deleted from the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection when the response to the `AddMembersToWorkspace` endpoint arrives.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L601

Therefore, we should change the line above to be similar to the one below.

`failureMembersState[accountID] = null;`

***Result***

https://github.com/Expensify/App/assets/22982173/a7eb25c9-2e1b-41f3-a22b-4893404a286b

*Note*

I am amused that this is the correct solution since when testing the `AddMembersToWorkspace` endpoint by inviting a combination of existent and non-existent members in one request, the backend returned the same `404` response. 

Hence, could I get confirmation of this behavior to rule out this solution?

**Comment by Tony-MK** [comment] 2024-01-22 01:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### What is the root cause of that problem?

The purpose of `finallyData` is to clean up the `newPersonalDetailsOnyxData` set in the `${ONYXKEYS.COLLECTION.PERSONAL_DETAILS_LIST}` collection because it might cause double `personalDetails` to be stored since the backend will either set nothing or new realistic data required for each new member.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L110-L114

The `addMembersToWorkspace` function creates the `optimisticMembersState` and  `failureMembersState` in the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection. 

![response](https://github.com/Expensify/App/assets/22982173/3aff13da-7298-433a-8255-413ae40ba94b)

When a single member is non-existent, the `onyxData` response is an empty array, but the `failureMembersState` is set while the `personalDetails` is deleted. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L662-L664

Hence, `failureMemberState` is not deleted because it is expected to be deleted by the `OfflineFeedback`'s `onClose` function when the admin dismisses the error. 

### What changes do you think we should make in order to solve the problem?

Amend the `failureMembersState` to make sure that  `errors` are not created and the `pendingAction` and `optimisticMembersState` are deleted from the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection when the response to the `AddMembersToWorkspace` endpoint arrives.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L601

Therefore, we should change the line above to be similar to the one below.

`failureMembersState[accountID] = null;`

***Result***

https://github.com/Expensify/App/assets/22982173/a7eb25c9-2e1b-41f3-a22b-4893404a286b

*Note*

I am theorizing that this is the correct solution since when testing the `AddMembersToWorkspace` endpoint by inviting a combination of existent and non-existent members in one request, the backend returned the same `404` response. 

Hence, could I get confirmation of this behavior to rule out this solution?

**Comment by Tony-MK** [comment] 2024-01-22 01:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members - After removing the error of adding a member to WS, the red dot remains in the RHN

### What is the root cause of that problem?

The purpose of `finallyData` is to clean up the `newPersonalDetailsOnyxData` set in the `${ONYXKEYS.COLLECTION.PERSONAL_DETAILS_LIST}` collection because it might cause double `personalDetails` to be stored since the backend will either set nothing or new realistic data required for each new member.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/PersonalDetailsUtils.ts#L110-L114

The `addMembersToWorkspace` function creates the `optimisticMembersState` and  `failureMembersState` in the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection. 

![response](https://github.com/Expensify/App/assets/22982173/3aff13da-7298-433a-8255-413ae40ba94b)

When a single member is non-existent, the `onyxData` response is an empty array, but the `failureMembersState` is set while the `personalDetails` is deleted. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L662-L664

Hence, `failureMemberState` is not deleted because it is expected to be deleted by the `OfflineFeedback`'s `onClose` function when the admin dismisses the error. 

### What changes do you think we should make in order to solve the problem?

Amend the `failureMembersState` to make sure that  `errors` are not created and the `pendingAction`, from the `optimisticMembersState`, is erased from the `${ONYXKEYS.COLLECTION.POLICY_MEMBERS}${policyID}` collection once the response from the `AddMembersToWorkspace` endpoint arrives.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Policy.ts#L617-L619

Therefore, we should change the line above to be similar to the one below.

`failureMembersState[accountID] = null;`

***Result***

https://github.com/Expensify/App/assets/22982173/a7eb25c9-2e1b-41f3-a22b-4893404a286b

*Note*

I am theorizing that this is the correct solution since when testing the `AddMembersToWorkspace` endpoint by inviting a combination of existent and non-existent members in one request, the backend returned the same `404` response. 

Hence, could I get confirmation of this behavior to rule out this solution?

**Comment by rushatgabhane** [comment] 2024-01-24 19:04
Isn't the issue that the error message isn't shown? So you can't dismiss it.

**Comment by bernhardoj** [comment] 2024-01-25 02:39
@rushatgabhane the member itself isn't shown, so the error message too.

**Comment by mvtglobally** [comment] 2024-01-30 04:59
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-01-31 11:08
Trying to reproduce now

**Comment by muttmuure** [comment] 2024-02-05 16:55
Unable to reproduce this

**Comment by bernhardoj** [comment] 2024-02-05 17:22
It's still reproducible. Notice the failed member is removed from the list but the red dot on the members menu is still showing.

https://github.com/Expensify/App/assets/50919443/d5d21ebd-7e38-4a6b-ae78-0852c9cda9f6

**Comment by bernhardoj** [comment] 2024-02-09 16:52
@muttmuure hi, can you please check the comment above? Thanks!

**Comment by muttmuure** [comment] 2024-02-21 14:02
Will test now - thanks for the bump!

**Comment by bernhardoj** [comment] 2024-02-21 14:07
You can test with this VOIP number +18183305299 (or another VOIP number)

**Comment by muttmuure** [comment] 2024-02-21 14:32
Aren't we meant to invite non-existent accounts to Expensify using this option? That seems to be the unexpected outcome here, not that there is an RBR that doesn't disappear

**Comment by muttmuure** [comment] 2024-02-21 15:02
OK after chatting with Tom he has pointed out that we do not create accounts for VOIP numbers or landlines

**Comment by muttmuure** [comment] 2024-02-21 15:02
When I tested this before with an email address, I couldn't reproduce it

**Comment by muttmuure** [comment] 2024-02-21 15:06
@rushatgabhane as C+ can you confirm if we are serving this detailed error from the server anywhere in the code? 

![image](https://github.com/Expensify/App/assets/46995600/accc4c84-5334-4faf-9f35-00b13670e059)

**Comment by muttmuure** [comment] 2024-02-21 15:06
`The provided phone number belongs to a landline or VoIP, please use your email address instead.`

**Comment by bernhardoj** [comment] 2024-02-22 08:28
That error message is coming from the BE. We are showing it on the sign in page.
<img width="343" alt="image" src="https://github.com/Expensify/App/assets/50919443/bd78de38-3d2e-4653-88fd-a328d7b9381c">

If we want to show a similar message, then the BE should return the correct data, but the issue we have here is that the fail-to-add member is hidden, so we can't read the error message even if the BE returns it. After we fix this, the error will look like this:

<img width="722" alt="image" src="https://github.com/Expensify/App/assets/50919443/1f722ddf-cd24-4705-a8ba-d345445df956">

When I look at the BE response, it gives a message property of the specific error message, but the error message data should be put inside `onyxData` which I'm not sure is possible because BE needs the optimistic account ID.
<img width="512" alt="image" src="https://github.com/Expensify/App/assets/50919443/afca30ce-46b7-4371-a68e-12616f0e3a60">

We can focus on fixing the hidden member here and let the internal team discuss (on a separate issue) how to show the more specific error message.

**Comment by trjExpensify** [comment] 2024-02-22 11:41
Yeah, I agree showing an error is better than not showing an error at all. It would be good to improve that message though, as it's super generic and doesn't explain _why_ there's a problem. Not passionate if that comes as a follow-up, but we should look into doing it.

**Comment by muttmuure** [comment] 2024-02-23 17:53
Agreed

**Comment by mvtglobally** [comment] 2024-02-27 15:49
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-02-28 17:12
@mvtglobally can you clarify what bug you're testing? Is it the RBR not disappearing when you add a VOIP or Landline number?

**Comment by rushatgabhane** [comment] 2024-03-01 19:20
> We can focus on fixing the hidden member here and let the internal team discuss (on a separate issue) how to show the more specific error message.

🎀 👀 🎀 let's hire @bernhardoj to show the hidden member on error

**Comment by grgia** [comment] 2024-03-04 19:00
> Issue not reproducible during KI retests. (First week)
@rushatgabhane @muttmuure @mvtglobally could you first confirm if this is no longer reproducible?

**Comment by mvtglobally** [comment] 2024-03-05 04:48
Issue not reproducible during KI retests. (Second week)

**Comment by bernhardoj** [comment] 2024-03-05 05:05
I can still reproduce it. Please use this number +18003569377

https://github.com/Expensify/App/assets/50919443/865674b9-6b4e-4eb9-b33b-e1353d5fe878

**Comment by grgia** [comment] 2024-03-07 11:00
confirmed, assigning @bernhardoj

**Comment by bernhardoj** [comment] 2024-03-07 14:23
PR is ready

cc: @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-03-26 13:47
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2024-03-26 13:52
@muttmuure could you please attach payment summary, thank you 🙇

**Comment by muttmuure** [comment] 2024-03-27 10:52
$500 for @rushatgabhane as C+ 
$500 for @bernhardoj as C

**Comment by JmillsExpensify** [comment] 2024-03-27 15:12
$500 approved for @rushatgabhane

**Comment by bernhardoj** [comment] 2024-04-02 10:17
@muttmuure hi, I think I haven't received the payment yet. As mentioned by melvin [here](https://github.com/Expensify/App/issues/34852#issuecomment-1983267048), the previous offer has an error, but I haven't received a manual offer yet. Can you please recheck it, please?

**Comment by muttmuure** [comment] 2024-04-02 10:26
Can you see this offer? https://www.upwork.com/nx/wm/offer/101695651

**Comment by bernhardoj** [comment] 2024-04-02 10:26
Yes, I can see that one and accepted it.

**Comment by muttmuure** [comment] 2024-04-02 10:40
All paid up!

**Comment by bernhardoj** [comment] 2024-04-02 10:40
Thanks!

**Closed by muttmuure** 2024-04-02 10:40 UTC
Labels: External, Daily, Needs Reproduction, Awaiting Payment, Bug
