### ISSUE TITLE
An error appears when try to issue card for a new user on private domain

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51265] opened 2024-10-22 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50489
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: workspace with enabled Expensify card feature. Bank account is added via Expensify card.

1. Navigate to Workspace settings - Members
2. Invite a member (with private domain email), that doesn't have an account yet
3. Navigate to Workspace settings - Expensify Card
4. Click on the "Issue new card" button
5. Select the new member
6. Select "Physical card
7. Add the card with any limit type, limit and name
8. Click Issue card

## Expected Result:
Card is added.
In workspace chat with a member the message would show 'issued ${assignee} an Expensify Card! The card will be shipped once shipping details are added.'

## Actual Result:
An error appears 'Oops... something went wrong and your request could not be completed. Please try again later.'

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9a33a67a-d0e1-4b51-bc70-6dc301eca908

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-22 15:49
We think that this bug might be related to #wave-collect - Release 2

**Comment by joekaufmanexpensify** [comment] 2024-10-22 18:17
Setting up a test workspace feed using the Plaid test account so I can test this.

**Comment by joekaufmanexpensify** [comment] 2024-10-22 18:26
I could not reproduce this bug at all. Not sure if you see any issue @AndrewGable ?

https://github.com/user-attachments/assets/ab3b1452-83d0-4a27-9f60-3e892c3fabcb

**Comment by AndrewGable** [comment] 2024-10-22 21:22
Cannot reproduce either.

https://github.com/user-attachments/assets/92b1da0c-e082-4cea-9a12-83cf0389a276

**Comment by joekaufmanexpensify** [comment] 2024-10-22 21:49
@IuliiaHerets are you still able to reproduce this?

**Comment by joekaufmanexpensify** [comment] 2024-10-22 22:11
Demoting to daily while we figure this one out.

**Comment by mountiny** [comment] 2024-10-23 03:41
Taking over, it is expected that the account has to be validated if we want to issue them a card.

I am working with @koko57 to handle this flow better from uz perspective and give the admin better error message

**Comment by joekaufmanexpensify** [comment] 2024-10-23 15:18
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-10-24 12:20
Still in progress

**Comment by mountiny** [comment] 2024-10-29 09:21
I have started a pr when travelling on the weekend here, I need to test it and clean it up before it go for a review, hopefully I can do that by tomorrow https://github.com/Expensify/Web-Expensify/pull/44156

**Comment by joekaufmanexpensify** [comment] 2024-10-30 13:51
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-10-31 13:38
PR still in progress

**Comment by mountiny** [comment] 2024-11-04 23:00
I will try to prioritize it

**Comment by joekaufmanexpensify** [comment] 2024-11-05 17:02
TY!

**Comment by mountiny** [comment] 2024-11-06 00:34
PR is ready for a review

**Comment by joekaufmanexpensify** [comment] 2024-11-06 13:07
Thanks Vit!

**Comment by mountiny** [comment] 2024-11-08 16:23
Still going to follow up with handling the errors for physical cards

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:22
Great. TY!

**Comment by mountiny** [comment] 2024-11-11 17:30
PR is in review

**Comment by joekaufmanexpensify** [comment] 2024-11-18 16:39
@mountiny I see your PR is on prod and I think this one is all set now. Closing for now, but LMK if anything else is needed!

**Closed by joekaufmanexpensify** 2024-11-18 16:39 UTC
Labels: Reviewing, Engineering, Weekly, Bug
