### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] [Search v2.1] Web - Search - App returns to Inbox after closing receipt view in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49887] opened 2024-09-28 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense with receipt
4. Go to Search
5. Click on the expense submitted in Step 3
6. Click on the receipt
7. Click X button

## Expected Result:
App will return to search page with transaction thread RHP open

## Actual Result:
App returns to transaction thread in Inbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bfab707e-d287-4c25-bd04-bf07fdb540cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840734855215732913</li>
        <li>Upwork Job ID: 1840734855215732913</li>
        <li>Last Price Increase: 2024-09-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-09-28 14:59
We think that this bug might be related to #wave-control

**Comment by rijusougata13** [comment] 2024-09-28 22:52
Why can't we just do `Navigation.goBack();`? We dont need any complexity here, just need to go back to previous screen only.

**Comment by sumairq** [comment] 2024-09-28 23:02
## Proposal
Please re-state the problem that we are trying to solve in this issue.
App returns to Inbox after closing receipt view in Search

### What is the root cause of that problem?
We are dismissing modal here whereas we just need to close the open reciept.

[App/src/pages/TransactionReceiptPage.tsx](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/pages/TransactionReceiptPage.tsx#L61-L63)

Lines 61 to 63 in [71db3f1](https://github.com/Expensify/App/commit/71db3f19691069182447b6b1b9fff62ec93be86c)

 onModalClose={() => { 
     Navigation.dismissModal(report?.reportID ?? '-1'); 
 }} 
### What changes do you think we should make in order to solve the problem?
We should use  Navigation.goBack instead. We can do something like this

  Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(report?.reportID ?? '-1'));
[App/src/pages/TransactionReceiptPage.tsx](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/pages/TransactionReceiptPage.tsx#L61-L63)

Lines 61 to 63 in [71db3f1](https://github.com/Expensify/App/commit/71db3f19691069182447b6b1b9fff62ec93be86c)
```
 onModalClose={() => { 
     Navigation.goBack(); 
 }} 
 ```
 ## What alternative solutions did you explore? (Optional)

**Comment by Kicu** [comment] 2024-09-30 09:14
hey, I work for an expert agency and I would like to work on this issue. I have a lot of context since I worked on search a lot.

**Comment by Kicu** [comment] 2024-09-30 09:15
@luacmartins you can assigne me, I have a bit of time while waiting on other open Search PRs to merge

**Comment by luacmartins** [comment] 2024-09-30 12:45
Demoting to NAB.

**Comment by Kicu** [comment] 2024-09-30 13:48
PR ready https://github.com/Expensify/App/pull/49915. I have not used any of the proposed suggestions, simply using `goBack` might've break some existing cases.

**Comment by zanyrenney** [comment] 2024-10-14 13:55
bump @rayane-djouah can you apply to the job please? https://www.upwork.com/jobs/~021840734855215732913

**Comment by zanyrenney** [comment] 2024-10-14 14:33
### Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~021840734855215732913)
- Contributor: @Kicu is from an agency-contributor and not due payment - ✅ 
- ROLE: @rayane-djouah paid $(AMOUNT) via Upwork (LINK) paid $250 via upwork ✅

**Closed by zanyrenney** 2024-10-14 14:33 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
