### ISSUE TITLE
Web- Room - Unnecessary Line is added on pressing Enter while Room creation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19771] opened 2023-05-29 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to New Dot on Desktop/Web
2. Click FAB button -> New Room
3. Type room name
4. Select Workspace name
5. Press Enter to create room

## Expected Result:
The room gets created and the composer should be focused with hint text

## Actual Result:
An unintended line break is added.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/674b2c7c-d433-466d-9c2f-2b1039f96a63

https://github.com/Expensify/App/assets/93399543/bc5873d6-86cb-4d95-bedf-3a0abb37c285

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Santhosh-Sellavel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685035831925699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-05-29 22:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New line addition after creation of room using keyboard Enter.

### What is the root cause of that problem?

The Enter key has not been handled in the room name input field. Hence it is being propagated to the composer input as a new line.

### What changes do you think we should make in order to solve the problem?

Handling the enter key in the room name input field will solve this issue. Adding this function - 

```javascript
    // Handling Enter key press
    handleEnterPress(e) {
        if (e.key === CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey) {
            e.preventDefault();
        }
    }
``` 
and passing this prop to TextInput - `onKeyPress={this.handleEnterPress}` in this file - `src/components/RoomNameInput/index.js`.

### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-05-31 02:12
Given that the reproduction steps entail hitting enter for reproduction and we've very publicly said that keyboard-related bugs are not a focus, I'm closing.

**Closed by JmillsExpensify** 2023-05-31 02:12 UTC
Labels: Daily, Bug
