### ISSUE TITLE
[$1000] Pronouns loses focus on reload, select and reopen pronouns page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23032] opened 2023-07-17 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open Profile
4. Open Pronouns
5. Reload
6. Change pronouns value
7. Reopen Pronouns and observe that now app does not focus on pronouns search field
8. Similarly, open timezone page from settings->profile->timezone->timezone
9. Reload
10. Change timezone value and reopen to observe that now app does not focus on timezone search field too

## Expected Result: 
 App should focus on pronouns/timezone search field whenever we open pronouns page or timezone page

## Actual Result: 
App does not focus on pronouns/timezone search field if we open pronouns/timezone, reload, change value and reopen pronouns/timezone page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-3
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b7e9c6a0-fa1b-42a9-826b-762988518cd4

https://github.com/Expensify/App/assets/43996225/5b9e96ab-f467-43ac-a833-9fa83ac31c31

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689574508646579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d14df444b7a139c</li>
        <li>Upwork Job ID: 1682494280971427840</li>
        <li>Last Price Increase: 2023-08-11</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-17 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that the Pronouns page does not automatically focus on the Pronouns search field after a user opens the page, reloads, changes the pronouns value, and then reopens the Pronouns page.

### What is the root cause of that problem?
The root cause of the issue is that the Pronouns search field does not have the autoFocus property set to true in the TextInput component within the BaseSelectionListRadio component. This causes the input to not automatically gain focus when the Pronouns page is reopened, especially after the sequence of actions detailed in the problem description.

### What changes do you think we should make in order to solve the problem?
To solve the problem, we should pass the autoFocus property with the value of true to the TextInput component inside the BaseSelectionListRadio component (src\components\SelectionListRadio\BaseSelectionListRadio.js). This will make the Pronouns search field automatically gain focus whenever the Pronouns page is opened. This solution aligns with the expected behavior. However, if there are additional nuances or complex dependencies in the current implementation, a deeper investigation and potential adjustments to the proposed solution may be necessary.

**Comment by johncschuster** [comment] 2023-07-19 15:07
I'm not really sure if the focus should return to the input field upon reload. Asking in [Slack.](https://expensify.slack.com/archives/C01SKUP7QR0/p1689779189326209)

**Comment by johncschuster** [comment] 2023-07-20 13:53
I've had a chat in Slack about this, and I don't think focus should return to the input field when the page is refreshed. That said, if there are other instances within the app in which focus _does_ return to an input field after refresh, we can get parity, but I'll need some examples of that behavior first.

**Comment by johncschuster** [comment] 2023-07-21 20:54
Ok, I think @dhanashree-sawant has made a good point for keeping this issue open (citing @Ollyws above). I'm going to reopen and get it going.

**Comment by StanislavLavrenchuk** [comment] 2023-07-24 12:35
https://github.com/Expensify/App/assets/139998585/e6092127-8e33-4dc5-901a-9909b3ce4017

##  Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Pronounce page, selected text does not auto focused after refresh.

### What is the root cause of that problem?
after reload Pronounce page, once update the pronounce,  the function calling navigation.navigate().
And then the pronounce page does not rerender from profile page.

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/libs/actions/PersonalDetails.js#L122-L140
need to change 
 Navigation.goBack(ROUTES.SETTINGS_PROFILE);

**Comment by johncschuster** [comment] 2023-07-26 21:23
@fedirjh what do you think of the above?

**Comment by ygshbht** [comment] 2023-07-30 19:01
@fedirjh Not able to reproduce now :(

**Comment by kavimuru** [comment] 2023-07-31 12:17
@fedirjh Reproduction steps are modified now. Could you check?

**Comment by johncschuster** [comment] 2023-07-31 22:32
Thanks for updating the repro steps @kavimuru! Can you try reproducing the behavior on staging to see if it persists? Thanks!

**Comment by mvtglobally** [comment] 2023-08-02 16:46
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2023-08-03 21:49
Bumping while we wait on additional KI retests to run.

**Comment by johncschuster** [comment] 2023-08-07 21:29
I _think_ we need to wait on another round of tests to see if this behavior persists.

**Comment by johncschuster** [comment] 2023-08-14 18:37
@mvtglobally can you test to see if this behavior persists?

**Comment by mvtglobally** [comment] 2023-08-14 22:03
@johncschuster we are not able to repro 

https://github.com/Expensify/App/assets/43995119/b3ae23e2-44dc-40c6-ba4d-7eb4f609c83e

**Comment by johncschuster** [comment] 2023-08-15 20:29
Great! In that case, let's close this one up!

**Closed** 2023-08-15 20:29 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
