### ISSUE TITLE
[Bug] [$250] iOS - LHN - New message does not appear in the chat list preview after enable the internet connection

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10762] opened 2022-09-01 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and login with any account, let's call it device A
2. Stay in LHN
3. Disable your internet connection on the device
4. On another device (can be any), send a message to the account logged in device A
5. Enable the internet connection

## Expected Result:
The new message should show in the chat list preview (sidebar on the left)

## Actual Result:
The new message that was sent while the user was offline does not appear in the chat list preview (sidebar on the left)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187995717-7a1fd297-ffc3-4c9d-ae6c-f1b725e7f274.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01f4c7055be7b7b054

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2022-09-07 15:53
@srikarparsi mybad for the delay, will post this now.

**Comment by michaelhaxhiu** [comment] 2022-09-07 16:12
Posted to upwork.

**Comment by Santhosh-Sellavel** [comment] 2022-09-07 16:33
@michaelhaxhiu accidentally got me unassigned too

**Comment by mvtglobally** [comment] 2022-09-13 04:36
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment] 2022-09-15 14:27
UGH, I swear this unassignment thing is a GH bug 😠

**Comment by michaelhaxhiu** [comment] 2022-09-15 14:28
@srikarparsi Do you think this bug report falls into "offline first" or no? We are supposed to hold the line on any offline first improvements, until that functionality is formally released. This feels close to that, but I'm not 100% sure

**Comment by michaelhaxhiu** [comment] 2022-09-19 20:25
cc @JmillsExpensify I'd love your input too, actually. 

I've seen 3 or 4 bug reports concerning elements of New Expensify that basically are an extension of Offline First. But given our internal agenda concerning that feature set, should we be accepting proposals/fixes from contributors that relate to offline mode (or not yet)? 

We've been closing issues that relate to offline mode thus far. So the real question is do we hold the line or open it back up?

**Comment by mvtglobally** [comment] 2022-09-20 05:08
Issue not reproducible during KI retests. (Second week)

**Comment by srikarparsi** [comment] 2022-09-20 05:51
sorry @michaelhaxhiu forgot to respond to this but I do think we could classify this as offline first functionality. 

I don't know about the larger-scale question of holding the line or opening it back up though. I feel like we should fix it since even though we don't have as many users on new dot as old dot, it might be the small bugs that are causing people to keep using email to respond to new dot messages but this seems like something that has been discussed before @JmillsExpensify

**Comment by marcaaron** [comment] 2022-09-21 16:52
>should we be accepting proposals/fixes from contributors that relate to offline mode (or not yet)

It depends on the issue. If it's something that looks related to UI then they can work on it. If it's something that seems related to authentication or an API issue then it has to be internal. If you aren't sure make it internal. 

I think this is what the Engineering Triage step is for...

**Comment by michaelhaxhiu** [comment] 2022-09-22 17:23
Thanks for clarifying Marc! 

> If it's something that seems related to authentication or an API issue then it has to be internal. If you aren't sure make it internal.

cc @srikarparsi lmk what you think. Do you think this relates to the above? Just want to make sure it has the right labels

**Comment by srikarparsi** [comment] 2022-09-26 05:30
I'm actually not too sure about this one as I haven't worked on API refactors. It does look like an API issue though so I would say we should mark it internal but @marcaaron, do you think you could take a second look at this?

**Comment by mvtglobally** [comment] 2022-09-27 05:13
Issue not reproducible during KI retests. (Third week) Are we ok to close this or anyone can still repro?

**Comment by marcaaron** [comment] 2022-09-28 22:19
I have a feeling this was related to the authentication issues we identified and fixed [here](https://github.com/Expensify/App/pull/11151).

Let's close and see if it happens again.

**Closed by marcaaron** 2022-09-28 22:19 UTC
Labels: Exported, External, Engineering, Weekly
