### ISSUE TITLE
[HOLD for payment 2023-06-28] [$250] Migrate Checkbox.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16123] opened 2023-03-20 08:30 UTC
### Filenames
- [ ] [src/components/Checkbox.js](https://github.com/Expensify/App/blob/main/src/components/Checkbox.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by kuluruvineeth** [comment] 2023-04-29 12:56
Proposal


Please re-state the problem that we are trying to solve in this issue.

-> Class Component Migration for Checkbox Component

What is the root cause of that problem?

-> class components are more verbose and harder to reason about than functional components.

What changes do you think we should make in order to solve the problem?

-> In the function component I would  use the useState hook to create a state value isFocused.
-> And two functions onFocus and onBlur to update the state value. 
-> And also refactor two callback functions handleSpaceKey and firePressHandlerOnClick to handle keydown and click events respectively. 
-> Finally Modify the firePressHandlerOnClick function to use the useState hook to update the isFocused state value.

What alternative solutions did you explore? (Optional)

**Comment by marcaaron** [comment] 2023-05-01 22:13
@kuluruvineeth Please stop spamming the issues in this repo. You are free to comment on things that have the `Help Wanted` label on them.

**Comment by kuluruvineeth** [comment] 2023-05-02 00:38
@marcaaron my apologies, i was not aware that this issues were internal i learnt the same just a while ago. I shall make sure it won't happen again thanks.

**Comment by marcaaron** [comment] 2023-05-02 02:02
Yeah, there's not really any good reason to spam a bunch of issues with similar comments in any case. If you are not sure about something ask in Slack and we are happy to provide assistance there, thanks!

**Comment by marcaaron** [comment] 2023-06-02 17:53
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by NikkiWines** [comment] 2023-06-03 01:10
Nice, I'll push up a PR for this first thing monday

**Comment by NikkiWines** [comment] 2023-06-06 03:33
PR is up, working on testing

**Comment by olexyt** [comment] 2023-06-07 16:10
I love to work on this issue

**Comment by NikkiWines** [comment] 2023-06-16 21:25
PR has been merged

**Comment by NikkiWines** [comment] 2023-06-29 22:29
oh hmm looks like we need a BZ member to issue payment to @aimane-chnaif for reviewing https://github.com/Expensify/App/pull/20193 - adding the appropriate label now

**Comment by NikkiWines** [comment] 2023-06-29 23:06
@greg-schroeder kindly volunteered to help out here 🙇

**Comment by greg-schroeder** [comment] 2023-06-29 23:16
created a job https://www.upwork.com/jobs/~014cc74cd0980ecb9b

sent you an offer for reviewing this @aimane-chnaif

**Comment by greg-schroeder** [comment] 2023-06-30 07:25
Pending acceptance and then we can close

**Closed** 2023-07-03 11:52 UTC
Labels: Engineering, Daily, Improvement, Overdue, Awaiting Payment
