### ISSUE TITLE
mWeb/Safari - Chat - Smart banner disappear in Workspace and New Chat/New Group/New Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10453] opened 2022-08-18 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in mWeb Safari
2. Ensure the smart banner is shown on all pages in the app

## Expected Result:
The smart banner is shown on all pages in the app

## Actual Result:
Smart banner disappear in Workspace and New Chat/New Group/New Room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.14

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/185471246-1c8cb70c-63d0-4e36-85d2-db44705ef97c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team 

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-08-19 16:49
Closing since this is a duplicate of https://github.com/Expensify/App/issues/8791

**Closed by amyevans** 2022-08-19 16:49 UTC
Labels: Engineering, Daily
