### ISSUE TITLE
Member - The search bar is not cleared after going to the new member invitation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33195] opened 2023-12-15 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Navigate to the settings of the existing WS
3. Navigate to "Members"
4. In the search bar, type any email account
5. Tap on "Invite"

## Expected Result:
After navigating to the new member invitation page, the search bar should clear from the data entered on the members page

## Actual Result:
After going to the page of inviting new members, the search bar is not cleared from the data entered on the members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec707ff0-a35c-41cd-988a-58831c26dacf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment] 2023-12-15 22:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The search bar is not cleared after going to the new member invitation page
### What is the root cause of that problem?
The initial value for the input search is fetched from the previous page here:  https://github.com/Expensify/App/blob/addfa8860ac031bd4c3a98c563e124cc3a95154c/src/pages/workspace/WorkspaceInvitePage.js#L78-L81

### What changes do you think we should make in order to solve the problem?


remove this useEffect solves the issue

**Comment by isabelastisser** [comment] 2023-12-20 16:06
Thanks for the insight, closing this!

**Closed by isabelastisser** 2023-12-20 16:06 UTC
Labels: External, Daily, Help Wanted, Bug
