### ISSUE TITLE
[HOLD for payment 2023-08-17] [HOLD for payment 2023-08-16] Attachments - Unable to upload pdf file due to "Something went wrong" error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24275] opened 2023-08-08 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the testing app in iOS
2. Go to any chat
3. Tap on the + button and select Add attachment
4. Tap on Choose document and select any pdf file

## Expected Result:
Preview of the file to be displayed

## Actual Result:
Something went wrong screen blocker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/17ee6c74-0d38-4190-83cc-3a826fe219b9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment] 2023-08-08 17:15
@mkhutornyi is right I think - @Julesssss do you have time to look at this to see if you can figure anything out? I'll keep checking too but looks like you'll be more familiar

**Comment by Julesssss** [comment] 2023-08-09 09:01
Sorry all I was out for the day at that point.

**Comment by Julesssss** [comment] 2023-08-09 09:14
> Hi, I [reported](https://expensify.slack.com/archives/C049HHMV9SM/p1691419644347639) this the day before this issue gets created. Will I get the reporting bonus?

I think so, it looks like you reported this 1 day earlier.

**Comment by dangrous** [comment] 2023-08-09 16:42
Added a BZ to handle the bug reporter and C+ payment when we're ready!

**Comment by dangrous** [comment] 2023-08-21 21:14
@Santhosh-Sellavel I handled the comment, below, since it was pretty internal anyway.

PR: https://github.com/Expensify/App/pull/20798
Comment: https://github.com/Expensify/App/pull/20798/files#r1300649636

Do you want to start the discussion in Slack?

We don't need a regression test because this was already caught by our existing tests.

Then we should be good to pay @bernhardoj for reporting, and @Santhosh-Sellavel for C+ review.

Thanks!

**Comment by dangrous** [comment] 2023-08-25 15:39
@Santhosh-Sellavel can you start the Slack discussion for this, and then we can pay and close out? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:08
@dangrous Can you assign a new BZ seems @mallenexpensify  is OOO

**Comment by mountiny** [comment] 2023-08-25 20:13
@Santhosh-Sellavel could you please double check if this is not re-introduced on `main`?

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 21:06
@mountiny It's working fine on the main!

https://github.com/Expensify/App/assets/85645967/3a9d96b1-83cb-45ad-978c-19c575452ac7

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 19:22
> @dangrous Can you assign a new BZ seems @mallenexpensify is OOO

bump!

**Comment by strepanier03** [comment] 2023-08-30 22:51
I'm going to work on payment for this and will have an update in a little bit.

**Comment by strepanier03** [comment] 2023-08-30 23:24
@bernhardoj - I have hired you to a reporting job via Upwork. I'll take another look tomorrow when I log back on.

@Santhosh-Sellavel - I was on sabbatical so missed the manual requests payment going live, I'm still figuring that out but I'll do my best to get it done asap.

**Comment by strepanier03** [comment] 2023-08-30 23:28
@Santhosh-Sellavel - Did you already request payment via Newdot? If not, can you do that? That should make a GH for payment for you with manual requests.

**Comment by Santhosh-Sellavel** [comment] 2023-08-31 01:37
@strepanier03 Can you add a payment summary comment. So I can request on ND

**Comment by mountiny** [comment] 2023-08-31 07:54
It was just failing on one adhoc build, all good, thanks!

**Comment by strepanier03** [comment] 2023-09-01 00:31
@Santhosh-Sellavel - My apologies, I didn't realize that is what you were waiting for. In our SO instructions the request comes before the summary step so we were both waiting on the other. 

----

Summarizing payouts for this issue:

Issue reporter: @bernhardoj - Paid $250 via Upwork - Contract ended and feedback left.

Contributor: N/A - internal PR

Contributor+: @Santhosh-Sellavel - $1000 to be paid via Manual Requests.

(if applicable: Upwork job is linked [here](https://www.upwork.com/freelance-jobs/apply/1000-Web-Room-Visibility-subtitle-wrong-for-public-room-20127-Expensify_~01005cb0382b9b4e71/).)

**Comment by strepanier03** [comment] 2023-09-01 00:32
@Santhosh-Sellavel - Once you send the request I'll assign to Jason for payment.

**Comment by Santhosh-Sellavel** [comment] 2023-09-01 15:52
Requested on ND

**Comment by JmillsExpensify** [comment] 2023-09-01 22:55
Reviewed the details for @Santhosh-Sellavel. $1,000 payment approved via NewDot based on BZ summary.

**Comment by strepanier03** [comment] 2023-09-01 23:28
Got, thanks @JmillsExpensify! 

I will close this now, but if it needs to be reopened for any reason please comment and @ mention me so I can review.

**Closed by strepanier03** 2023-09-01 23:28 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
