### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] Web - Distance rates - Offline indicator is present in distance rate RHP

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41331] opened 2024-04-30 13:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace.
3. Go to Distance rates.
4. Click on any distance rate.
5. Go offline.

## Expected Result:
Offline indicator will not be present in distance rate RHP.

## Actual Result:
Offline indicator is present in distance rate RHP.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/e308810b-5c6a-45af-a63f-7a362aece092

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108e73546587156bc</li>
        <li>Upwork Job ID: 1790581946829164544</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by m-natarajan** [comment] 2024-04-30 13:38
@JmillsExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Nodebrute** [comment] 2024-04-30 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Distance rates - Offline indicator is present in distance rate RHP
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2a1c2cb16b9b5234ad05518be46d95d6bcaa2f56/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L103
### What changes do you think we should make in order to solve the problem?

Remove   `shouldShowOfflineIndicatorInWideScreen`
https://github.com/Expensify/App/blob/2a1c2cb16b9b5234ad05518be46d95d6bcaa2f56/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L103
### What alternative solutions did you explore? (Optional)

**Comment by cretadn22** [comment] 2024-05-01 04:54
I am interesting on this issue

**Comment by cretadn22** [comment] 2024-05-01 04:56
Contributor details
Your Expensify account email: cretadn22@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01af96c76db71b99d9

**Comment by cretadn22** [comment] 2024-05-01 05:02
Contributor details
Your Expensify account email: cretadn22@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01af96c76db71b99d9

**Comment by JmillsExpensify** [comment] 2024-05-15 03:16
Opening up for proposals

**Comment by MrMuzyk** [comment] 2024-05-15 07:55
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by Nodebrute** [comment] 2024-05-15 07:57
@MrMuzyk I have already submitted a proposal

**Comment by MrMuzyk** [comment] 2024-05-15 08:03
Oh ok, seems like I've also missed that 😅 If your proposal works then I happy to leave it to you 😄

**Comment by carlosmiceli** [comment] 2024-05-15 19:59
Proposal sounds good!

**Comment by carlosmiceli** [comment] 2024-05-28 20:10
What's the status of this? I'm a bit confused as to what has to happen next or if there's anything left from me to do to advance this issue... cc @Ollyws @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-06-05 05:26
Payments due tomorrow. @Ollyws did you want to get us kicked off with the checklist?

**Comment by JmillsExpensify** [comment] 2024-06-06 15:12
Contributor paid out and C+ is paid via NewDot. I'm going to close this one out!

**Closed by JmillsExpensify** 2024-06-06 15:12 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by laurenreidexpensify** [comment] 2024-06-06 16:12
Payment summary:

Contributor: $250 @Nodebrute paid via upwork
Contributor+: $250 @Ollyws paid via newdot

**Comment by JmillsExpensify** [comment] 2024-06-06 16:20
$250 approved for @Ollyws

**Comment by JmillsExpensify** [comment] 2024-06-07 05:10
Regression test created!
