### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Replies count doesn't update on a task shared in group.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23920] opened 2023-07-31 13:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task
2. Select a assignee
3. Select a group to share
4. Go to the group and update the task using checkbox (replies count updates)
5. Go to assignee report and update the task using checkbox (replies count doesn't updates)
## Expected Result: 
The replies count should update in both the group and assignee report.
## Actual Result: 
The replies count updates in the group but not in assignee report.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4a558b70-a7d5-497d-a462-7b63b8c1100e

https://github.com/Expensify/App/assets/43996225/79f8fc6b-9e4c-4b6f-ba08-e73105625cf4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690705764414639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bbb12e93147362e</li>
        <li>Upwork Job ID: 1686236770866049024</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25923313</li>
<li>s-alves10 | Contributor | 25923314</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-08-01 03:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Replies count doesn't update on a task shared in group.
### What is the root cause of that problem?
When we complete or reopen task, we are calling `completeTask` and `reopenTask` of `Task.js`
In these function, we are increasing `childVisibleActionCount` of `action`.
In the reopen case:
https://github.com/Expensify/App/blob/3324ea72cdabc84ba69e01bed8c56208a86b8e1f/src/libs/actions/Task.js#L339
https://github.com/Expensify/App/blob/3324ea72cdabc84ba69e01bed8c56208a86b8e1f/src/libs/ReportUtils.js#L1528-L1543
To update `childVisibleActionCount` of `action`, we got parentReportAction from task.
This is only action of shared channel.
so only shared channel reply is increased and direct channel reply is not increased(only updated after refresh)
### What changes do you think we should make in order to solve the problem?
We need to `childVisibleActionCount` of 2 actions(shared channels action and direct channel action).
In my test case, actions ids are `6032435466773608246` and `6281777622256522668`.
We can send this as parameter to update.
### What alternative solutions did you explore? (Optional)
We can get origin 2 actions on update function.

**Comment by JmillsExpensify** [comment] 2023-08-01 04:45
Hmmm, I agree that minimally we should be treating the history reportAction the same for the room and DM cases. I'll triage.

**Comment by s-alves10** [comment] 2023-08-01 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Replies count doesn't update on a task shared in group when we update the task in assignee report

### What is the root cause of that problem?

When we create a task, we set the `parentReportID` of the newly created task report to the `shareDestination` reportID
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/tasks/NewTaskPage.js#L99

And we create the new comment in `shareDestination` report and set the `parentReportActionID` of the task to the reportActionID of the new comment
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/libs/actions/Task.js#L69-L70

When we update(reopen or complete) a task using the checkbox, `reopenTask`/`completeTask` function in `Task.js` are called.

Let's take a look at the completeTask function [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/libs/actions/Task.js#L210)
After we set optimistic data for the task report and actions, we create the optimistic data for parent report action
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/libs/actions/Task.js#L263

If we update the task in `shareDestination` report, all works fine because parentReportAction is updated as well here.
But this is not the case when we update the task in `assignee` report. The current action of the `assignee` report isn't updated.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We should update the assignee parent action when we update the task in `assignee` report. It would be better if we can update two parent actions(one in `shareDestination` and one in `assignee`, of course, when they are different)

_**Solution 1**_

1. Pass the additional parameters to the `reopenTask`/`completeTask` functions: `reportID`, `reportActionID` in `TaskPreview`

If the current action is `assignee` task action, 
```
        const isAssigneeTaskAction = props.taskReport.parentReportActionID !== props.action.reportActionID;
        const reportID = isAssigneeTaskAction ? props.reportID : undefined;
        const reportActionID = isAssigneeTaskAction ? props.action.reportActionID : undefined;
```

```
        onPress={() => {
            if (isTaskCompleted) {
                Task.reopenTask(props.taskReportID, taskTitle, reportID, reportActionID);
            } else {
                Task.completeTask(props.taskReportID, taskTitle, reportID, reportActionID);
            }
        }}
```

Add reportID props to the `TaskPreview` component in ReportActionItem
https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/pages/home/report/ReportActionItem.js#L287

```
        reportID={props.report.reportID}
```

2. Add the new parameters `reportID` and `reportActionID`
```
    function completeTask(taskReportID, taskTitle, reportID, reportActionID)
    ...

    function reopenTask(taskReportID, taskTitle, reportID, reportActionID)
```

If `reportID` or `reportActionID` are `undefined`, do nothing

If not, create the optimistic data same as `optimisticParentReportData` created [here](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/libs/actions/Task.js#L263) except `reportID` and `reportActionID`
```
    const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(taskReportID, completedTaskReportAction.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);
    if (!_.isEmpty(optimisticParentReportData)) {
        optimisticData.push(optimisticParentReportData);
        if (reportID && reportActionID) {
            const optimisticDataForAssigneeReportAction = {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
                value: {
                    [reportActionID]: _.values(optimisticParentReportData.value)[0],
                },
            }
            optimisticData.push(optimisticDataForAssigneeReportAction);
        }
    }
```

_**Solution 2**_

We can always create the optmistic data for two parent report actions(in `assignee` and `shareDestination` report) as follows
1. Add the following line to the [buildOptimisticTaskCommentReportAction](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/libs/ReportUtils.js#L1555)
```
    reportAction.reportAction.participantAccountIDs = [taskAssigneeAccountID];
```

The backend returns this data. This is for offline mode

2. Pass taskReport instead of taskReportID to `reopenTask`/`completeTask` in [TaskPreview](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/components/ReportActionItem/TaskPreview.js#L90-L94) and [TaskView](https://github.com/Expensify/App/blob/cb8aac115eb2c0130dcab208cccb60ba6f21fa77/src/components/ReportActionItem/TaskView.js#L76)

3. Add the utility function `getParentReportActionForTask` in REportActionsUtils.js

```
function getParentReportActionForTask(taskReportID, reportID) {
    return _.find(
        allReportActions[reportID],
        (reportAction) => reportAction && `${reportAction.childReportID}` === `${taskReportID}` && reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT,
    );
}
```

This is the function to find the reportAction with childReportID = taskReportID in reportActions of report(reportID)

4. Update the `reopenTask`/`completeTask` function as follows
- Rename the first argument from `taskReportID` to `taskReport` and add the first line

```
    const taskReportID = taskReport.reportID;
```

- We can get reportID and reportActionID of the parent action of the task in `assignee` report.

```
    const assigneeChatReportID = lodashGet(ReportUtils.getChatByParticipants(taskReport.participantAccountIDs), 'reportID');
    const parentReportAction = ReportActionsUtils.getParentReportActionForTask(taskReportID, assigneeChatReportID);
```

Now that we get reportID and reportActionID, we can create optmisticData from them as solution 1.

The entire code would look like

```
    // Update optimistic data for parent report action
    const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(taskReportID, completedTaskReportAction.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);
    if (!_.isEmpty(optimisticParentReportData)) {
        optimisticData.push(optimisticParentReportData);
        const assigneeChatReportID = lodashGet(ReportUtils.getChatByParticipants(taskReport.participantAccountIDs), 'reportID');
        if (assigneeChatReportID && `${assigneeChatReportID}` !== `${taskReport.parentReportID}`) {
            const parentReportAction = ReportActionsUtils.getParentReportActionForTask(taskReportID, assigneeChatReportID);
            if (parentReportAction) {
                optimisticData.push({
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${assigneeChatReportID}`,
                    value: {
                        [parentReportAction.reportActionID]: _.values(optimisticParentReportData.value)[0],
                    },
                });
                failureData.push({
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${assigneeChatReportID}`,
                    value: {
                        [parentReportAction.reportActionID]: {
                            errors: ErrorUtils.getMicroSecondOnyxError('task.messages.error'),
                        },
                    },
                });
            }
        }
    }
```

These solutions works well. I prefer the 2nd solution

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/3dbca5e2-3083-4244-ac89-02bbbc4d47b8

</details>

### What alternative solutions did you explore? (Optional)
We can consider the multiple parentReportID and parentReportActionID. In this case, I think the backend should be updated as well

**Comment by s77rt** [comment] 2023-08-02 09:29
@yh-0218 Thanks for the proposal. Your RCA makes sense and the solution as well but it's not well explained. Can you please explain how we will get the 2 report action ids (share report action id is already stored in parentReportActionID but what about the assignee?)

**Comment by s77rt** [comment] 2023-08-02 10:52
@s-alves10 Thanks for the proposal. Your RCA makes sense. I don't think solution 1 will work correctly as if we add a reply in the share report it should be reflected in the assignee report as well (and not just the vice-versa way). Solution 2 seems like it will do the job but I'm not sure about the idea of having to iterate through the report actions to find the correct child.

I think there may be a bigger problem, we have two report actions claiming to be the parent of the same report.
- ShareReport have a reportAction that links to TaskReport as it's child 
- AssigneeReport also have a reportAction that links to the same child :exclamation: :question: 
- The parent of TaskReport is ShareReport. 

Or:

- reportActionA: My child is report123
- reportActionB: My child is report123
- report123: My parent is ReportActionA

**Comment by s77rt** [comment] 2023-08-02 10:59
Discussing in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1690973855809149

**Comment by s77rt** [comment] 2023-08-02 23:26
From the slack discussion the [highlighted problem](https://github.com/Expensify/App/issues/23920#issuecomment-1661991818) seems to be a known limitation. Searching for the "fake" parent actions is the way to go.
1. The real parent action is stored in task report
2. The "fake" parent action (currently only one) is somewhere in the assignee report we will have to filter the report actions based on `childReportID` - We will also need to find the assignee report

@s-alves10 s 2nd solution for doing the above looks good.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/23920#issuecomment-1659889416)

**Comment by s-alves10** [comment] 2023-08-04 22:03
@s77rt 

Can you take look at the [PR](https://github.com/Expensify/App/pull/24110) again?

**Comment by s77rt** [comment] 2023-08-04 23:21
@s-alves10 Sure working on it

**Comment by s77rt** [comment] 2023-08-13 00:43
- The PR that introduced the bug has been identified: This existed since day one https://github.com/Expensify/App/pull/18806 and https://github.com/Expensify/App/pull/20014
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18806#discussion_r1292575868 and https://github.com/Expensify/App/pull/20014#discussion_r1292575885
- A discussion in #expensify-bugs has been started: Not a regression, more like a missed unimplemented case
- Determine if we should create a regression test for this bug: No

**Comment by techievivek** [comment] 2023-08-16 08:55
> Hello, do you think that could be a regression ? https://github.com/Expensify/App/issues/24532

Yeah, that looks like a backend bug and not something related to changes that were done here.

**Comment by techievivek** [comment] 2023-08-16 08:57
> can you pls send a offer on Upwork for reporter role, I have applied a week ago but haven't got the offer yet.

@JmillsExpensify Can you take a look into it? Thanks.

**Comment by techievivek** [comment] 2023-08-24 10:13
Gentle bump @JmillsExpensify  ^

**Comment by s-alves10** [comment] 2023-08-31 08:56
@JmillsExpensify 

Will you let me know when I can get paid?

**Comment by techievivek** [comment] 2023-09-11 10:47
Not overdue, I have just DMed Jason to finish the payment here. Sorry for the delay.

**Comment by JmillsExpensify** [comment] 2023-09-13 09:51
Sorry ya'll, I'm not coming back to this issue for payments/summary.

**Comment by JmillsExpensify** [comment] 2023-09-13 09:56
Payment summary:

 - Issue reporter: @Krishna2323 $250 (pre-September 1)
 - Contributor: @s-alves10 $1,500 (incl. urgency bonus)
 - Contributor+: @s77rt $1,500 (incl. urgency bonus)

@Krishna2323 I believe you applied to the Upwork but for the wrong amount. @s-alves10 and @s77rt offers just sent.

**Comment by JmillsExpensify** [comment] 2023-09-13 10:07
Just hired you.

**Comment by JmillsExpensify** [comment] 2023-09-13 10:11
Paid

**Comment by s-alves10** [comment] 2023-09-13 10:23
@JmillsExpensify 

Accepted

**Comment by s77rt** [comment] 2023-09-13 15:24
@JmillsExpensify Accepted! Thanks!

**Comment by JmillsExpensify** [comment] 2023-09-15 09:18
Everyone should be paid out at this point! Closing.

**Closed by JmillsExpensify** 2023-09-15 09:18 UTC
Labels: External, Weekly, Awaiting Payment, Bug
