### ISSUE TITLE
Newly created workspace not showing in Request Money Participant Selector.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40505] opened 2024-04-18 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713185937683679

## Action Performed:
1.open participant selector.
2. close it and create a workspace from workspace switcher 
3. Check if newly create wokrspace shows in participant selector
## Expected Result:
Newly create workspace shows in Participant Selector.
## Actual Result:
Newly create workspace not shows in Participant Selector.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/18c0de32-4f2d-488a-8afc-b096092a2da0

https://github.com/Expensify/App/assets/38435837/5dffc21f-66a1-4431-9168-4790afbdb584

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2024-04-22 16:30
Closing as dupe of https://github.com/Expensify/App/issues/40406

**Closed by MitchExpensify** 2024-04-22 16:30 UTC
Labels: Daily, Overdue, Bug
