### ISSUE TITLE
[HOLD #34473] After switching accounts, some chats from old account show upon launch then in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36804] opened 2024-02-19 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708356217921739

## Action Performed:
1. Log in to mallen@expensifail.com
2. Log out and log in to mallen@expensify.com

## Expected Result:
After immediately signing in, for only [mallen@expensify.com](mailto:mallen@expensify.com) chats to show in LHN.
Also after the initial load, for only [mallen@expensify.com](mailto:mallen@expensify.com) chats to show in LHN

## Actual Result:
[mallen@expensifail.com](mailto:mallen@expensifail.com) chats show in LHN. Many during initial load, 2 showed as static after initial load, once clicked on they stopped showing in LHN (I saw loading page for both cuz I didn't have access to the report via my [mallen@expensify.com](mailto:mallen@expensify.com) account.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

Initial load, right after signing in with [mallen@expensify.com](mailto:mallen@expensify.com). All of these appear to be [mallen@expensifail.com](mailto:mallen@expensifail.com) chats.
![image (6)](https://github.com/Expensify/App/assets/38435837/30e7e809-7885-4efc-a577-a882ba23a3aa)

After initial load, these two chats still show as static until I click them, then they disappear.
![image (7)](https://github.com/Expensify/App/assets/38435837/40108288-1620-4c0c-a7c8-71d3007608eb)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2024-02-19 22:15
@bfitzexpensify likely a dupe of https://github.com/Expensify/App/issues/34473
If you believe so, you can close this one.  Otherwise, can leave on hold.

**Comment by bfitzexpensify** [comment] 2024-02-28 22:00
Agreed that this seems a dupe - closing.

**Closed by bfitzexpensify** 2024-02-28 22:00 UTC
Labels: Weekly, Needs Reproduction, Overdue, Bug
