### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500] mWeb - Chat - If user tries to download 2 files, only the last one selected is downloaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35189] opened 2024-01-25 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4226855
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have sent 2 files in a chat
1. Go to the chat where you sent the two files
2. Tap the download button next to a file name
3. Before the first file is downloaded, press the download button of the second file

## Expected Result:
Both files should be downloaded

## Actual Result:
Only the last file selected is downloaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3045aae7-27fc-442c-af86-b427e0cd19cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b82a15e899c7d8da</li>
        <li>Upwork Job ID: 1750625005966385152</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 28142488</li>
<li>wildan-m | Contributor | 28142489</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by wildan-m** [comment] 2024-01-27 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb-Safari-ios- Chat - If a user tries to download 2 files, only the last one selected is downloaded

### What is the root cause of that problem?

Clicking multiple download links almost simultaneously may be interpreted as an attempt to download multiple files concurrently.

While most desktop browsers seamlessly manage this, mobile browsers tend to be more stringent.

Mobile Chrome employs a mechanism that enables the simultaneous download of multiple files by prompting the user for permission. However, in the case of Mobile Safari, one must individually tap the download dialog for each file.

When endeavoring to click multiple download links in Safari, the browser will cancel the loading of the previous file, opting instead for the most recently tapped link if a previous download is still in progress.

### What changes do you think we should make in order to solve the problem?
We are attempting to open the direct download link in a new tab in the event of a failure. Unfortunately, this approach encounters issues when the download confirmation dialog is triggered.

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/fileDownload/index.ts#L46

To address this issue, we can add a new parameter to the `fileDownload` function, named `shouldOpenExternalLink`. This parameter will intentionally open the download link in a new tab.

```
const fileDownload: FileDownload = (url, fileName, successMessage = '', shouldOpenExternalLink = false) => {
    const resolvedUrl = tryResolveUrlFromApiRoot(url);
    if (shouldOpenExternalLink || (!resolvedUrl.startsWith(ApiUtils.getApiRoot()) && !CONST.ATTACHMENT_LOCAL_URL_PREFIX.some((prefix) => resolvedUrl.startsWith(prefix)))) {
        // Different origin URLs might pose a CORS issue during direct downloads.
        // Opening in a new tab avoids this limitation, letting the browser handle the download.
        Link.openExternalLink(url);
        return Promise.resolve();
    }
```
To implement this, we will set the `shouldOpenExternalLink` parameter in the `BaseAnchorForAttachmentsOnly` component when it originates from Mobile Safari (`Browser.isMobileSafari()`).

```
                <PressableWithoutFeedback
                    style={style}
                    onPress={() => {
                        if (isDownloading) {
                            return;
                        }
                        Download.setDownload(sourceID, true);
                        fileDownload(sourceURLWithAuth, displayName, '', Browser.isMobileSafari()).then(() => Download.setDownload(sourceID, false));
                    }}

```

[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/35189-multi-downloads-external-link?expand=1)
### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-01-27 16:28
[Proposal Updated](https://github.com/Expensify/App/issues/35189#issuecomment-1913188877)

Add an alternative solution by disabling download links when any download is in process

**Comment by lschurr** [comment] 2024-02-01 17:02
I'm not sure @ishpaul777 - Could you start a conversation in Slack?

**Comment by wildan-m** [comment] 2024-02-02 14:39
@ishpaul777, @lschurr It appears that the first solution is favored.

**Comment by wildan-m** [comment] 2024-02-06 03:25
@ishpaul777 I've encountered a similar situation on desktop platforms. While there isn't an inherent mechanism for handling downloads, the desktop environment, unlike Safari on iOS, offers more flexibility. To address this, I suggest incorporating a library known as "electron-dl." This library proves beneficial in seamlessly managing multiple download processes on desktop applications.

We can modify `desktop/main.js` to 

```
const {autoUpdater} = require('electron-updater');
const log = require('electron-log');
const {machineId} = require('node-machine-id');
const ELECTRON_EVENTS = require('./ELECTRON_EVENTS');
const checkForUpdates = require('../src/libs/checkForUpdates');
const CONFIG = require('../src/CONFIG').default;
const CONST = require('../src/CONST').default;
const Localize = require('../src/libs/Localize');
const electronDl = require('electron-dl');
const port = process.env.PORT || 8082;
const {DESKTOP_SHORTCUT_ACCELERATOR, LOCALES} = CONST;

// Setup google api key in process environment, we are setting it this way intentionally. It is required by the
// geolocation api (window.navigator.geolocation.getCurrentPosition) to work on desktop.
// Source: https://github.com/electron/electron/blob/98cd16d336f512406eee3565be1cead86514db7b/docs/api/environment-variables.md#google_api_key
process.env.GOOGLE_API_KEY = CONFIG.GOOGLE_GEOLOCATION_API_KEY;

app.setName('New Expensify');

electronDl();
```

Are you okay with that?

**Comment by lschurr** [comment] 2024-02-07 16:46
@ishpaul777 could you review?

**Comment by techievivek** [comment] 2024-02-08 06:41
@ishpaul777 

I believe if we want to introduce a new library, we should seek consensus from the engineers on the app deploy team. We can open an issue for them and allow them to review it. IMO, the package seems to receive updates, although not regularly, and it is a small package, so we could potentially maintain it ourselves in the future.

Regarding the proposal, I had a question about the following statement:

> Clicking multiple download links almost simultaneously may be interpreted as an attempt to download multiple files concurrently.

Could we address this issue by listening for the download click and scheduling the downloads after a 2-3 second delay using setTimeout? This way, the browser wouldn't detect it as a concurrent download attempt. Did you try this approach, @wildan-m?

**Comment by wildan-m** [comment] 2024-02-08 06:54
@techievivek, I attempted the suggested approach, but it necessitates a delay of approximately 5000 ms to achieve a level of reliability. When I mention "reliable enough," it implies that even with this delay, there is still a chance of failure, as per my testing.

Additionally, I explored the implementation of a queue mechanism using promises. However, this approach proved ineffective in ensuring the successful execution of subsequent downloads.

**Comment by techievivek** [comment] 2024-02-08 11:54
@wildan-m, I see. Thanks for the context. I would then suggest just creating a new GH proposing the usage of the new library and letting the team assess it.

**Comment by wildan-m** [comment] 2024-02-11 16:08
@ishpaul777 @techievivek I've created a request post.

https://github.com/Expensify/App/issues/36305

Shall we wait for a response or proceed to create the pull request for the mobile Safari case in the meantime?

**Comment by wildan-m** [comment] 2024-02-11 16:09
it's auto closed, so we have to post it in slack first, right?

**Comment by wildan-m** [comment] 2024-02-11 16:39
@ishpaul777, @techievivek just a heads up: when using `electron-dl`, if we want to keep the "save as" dialog (instead of direct download to the default directory), we need to include a queue mechanism. Otherwise, the issue will persist. I've successfully added a queue with the following code:

```
                class DownloadQueue extends Array {
                    constructor(...args) {
                        super(...args);
                    }
                    push(item) {
                        const len = super.push(item);
                        if (this.length === 1) {
                            this.download(item);
                        }
                        return len;
                    }
                    shift() {
                        const item = super.shift();
                        if (this.length > 0) {
                            this.download(this[0]);
                        }
                        return item;
                    }
                    download(item) {
                        item.options.onCompleted = () => {
                            this.shift();
                        };

                        item.options.onCancel = item.options.onCompleted;

                        electronDl.download(item.win, item.url, item.options);
                    }
                }
```

The snippet modified from https://github.com/sindresorhus/electron-dl/issues/37#issuecomment-951626649

**Comment by techievivek** [comment] 2024-02-12 04:12
I've reopened the GH, and Andrew will review it shortly. My suggestion would be to wait for the team to review the request, and then we can proceed accordingly based on their feedback.

**Comment by lschurr** [comment] 2024-02-14 16:47
Any update @techievivek?

**Comment by techievivek** [comment] 2024-02-15 04:26
We have created a GH for the app deployment team to evaluate the request to add the new library that was suggested as part of the proposal. That might take some time since the team needs to have a discussion.

**Comment by lschurr** [comment] 2024-02-21 16:37
Should this GH be on hold @ishpaul777 @techievivek?

**Comment by AndrewGable** [comment] 2024-02-22 14:56
Discussing here: https://expensify.slack.com/archives/C03TQ48KC/p1708541023332899

**Comment by wildan-m** [comment] 2024-02-22 15:19
@AndrewGable I can't access it, please inform me once the decision has been made

**Comment by techievivek** [comment] 2024-02-22 15:24
@wildan-m 
We've decided against adding a new package. Primarily because it's small, poorly maintained, and lacks any secret sauce that would be challenging to implement ourselves. So, let's replicate the logic in our codebase and utilize that instead. If there are any complications we can talk through it, thanks.

**Comment by wildan-m** [comment] 2024-02-23 02:08
@ishpaul777 Sure, [my proposal updated](https://github.com/Expensify/App/issues/35189#issuecomment-1913188877) with desktop solution.

**Comment by wildan-m** [comment] 2024-02-23 14:19
@ishpaul777 @techievivek [the PR](https://github.com/Expensify/App/pull/37131) is ready for review.

**Comment by allroundexperts** [comment] 2024-05-01 07:31
Got occupied with existing issues. On my list for today.

**Comment by allroundexperts** [comment] 2024-05-16 18:07
This is still under review Melv. I'm actively checking it.

**Comment by techievivek** [comment] 2024-05-20 04:29
Thanks @allroundexperts for the update.

**Comment by lschurr** [comment] 2024-06-06 18:24
I will add the payment summary later today and get this paid out.

**Comment by mallenexpensify** [comment] 2024-06-06 19:13
@ishpaul777 and @allroundexperts , this is a weird one cuz it took a while and @ishpaul777 went out and @allroundexperts took over (but... then @ishpaul777 helped review the PR). What do you two propose is fair for compensation for you two here?

**Comment by lschurr** [comment] 2024-06-06 19:30
Thanks @ishpaul777!

**Comment by lschurr** [comment] 2024-06-06 19:33
Payment summary:

- Contributor: $500 @wildan-m (paid in Upwork)
- Contributor+: $500 @allroundexperts (to be requested in Newdot)

**Comment by lschurr** [comment] 2024-06-06 19:33
Closing :)

**Closed by lschurr** 2024-06-06 19:33 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-20 17:17
$500 approved for @allroundexperts
