### ISSUE TITLE
mWeb/Safari - Workspace - New workspace is not created after tap on "Set up my company for free"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13275] opened 2022-12-02 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a existing account
3. Navigate to the OldDot page (staging.expensify.com)
4. Verify there's several options to log in (Email, phone number, Google, Apple)
5. Tap on the Email option and log in as the same user you logged in in NewDot
6. Verify there are 3 options (Set up my company for free, Scan receipts & submit expenses, Split bills & chat with friends)
7. Tap on "Set up my company for free"
8. Verify you're redirected to NewDot
9. Tap on the back button to view the workspaces list and Verify 1 New Workspace has been created

## Expected Result:
New workspace is created after tap on "Set up my company for free"

## Actual Result:
New workspace is not created after tap on "Set up my company for free"

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Safari

**Version Number:** 1.2.35.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205350853-1cf7c3a1-4cb2-45ac-a945-098a05acd38c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2022-12-02 18:03
Transition issues can't be worked on by contributors so this is internal. Steps are a bit confusing but from what I understand, you 

1. logged into NewDot
2. logged into OldDot 
3. Clicked the setup link
4. NewDot opened but no new workspace was created.

I'll take a look and try to repro

**Comment by pecanoro** [comment] 2022-12-03 00:00
I am pretty sure the cause here is the same as https://github.com/Expensify/App/issues/13026, so you can reassign if you want since I think I know how to fix it.

**Comment by sophiepintoraetz** [comment] 2022-12-05 08:23
Didn't get a chance to repro today - aiming for tomorrow!

**Comment by arosiclair** [comment] 2022-12-05 15:36
> I am pretty sure the cause here is the same as https://github.com/Expensify/App/issues/13026, so you can reassign if you want since I think I know how to fix it.

I think these are separate issues. I just commented on yours.

**Comment by sophiepintoraetz** [comment] 2022-12-07 06:15
Ah, good context - I tried this yesterday on the same version (v1.2.36-2) but couldn't reproduced but wanted to double-check myself I was following the steps correctly. I'm unable to try again today (power went out on the street as I settled in to try) so will come back to this tomorrow

>To get the "Welcome to Expensify!" screen on OldDot I needed to create a new account in NewDot before visiting OldDot for the first time.

I think I got this by trying from an incognito browser.

**Comment by sophiepintoraetz** [comment] 2022-12-08 05:04
Okay, I'm not able to replicate this either - a new workspace is create for me too. @kbecciv - I'm pretty sure I'm following your steps to the letter but can you check my video and let me know if I've missed something?
[workspace test.mp4.zip](https://github.com/Expensify/App/files/10182247/workspace.test.mp4.zip)

**Comment by arosiclair** [comment] 2022-12-12 20:58
Since we're both unable to reproduce I think we can just close this out. QA can reopen if the issue occurs again on their end

**Closed by arosiclair** 2022-12-12 20:58 UTC
Labels: Daily, Internal, Overdue, Bug
