### ISSUE TITLE
[$500] Tag - No search field when there are more than 9 tags in the tag list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36859] opened 2024-02-20 10:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/35541

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has more than 9 tags.

1. Navigate to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Request money > Manual.
4. Enter amount > Next.
5. Click Show more.
6. Click Tag.

## Expected Result:
There will be a search field above tag list because there are more than 9 tags.

## Actual Result:
There is no search field above tag list when there are more than 9 tags.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a6d3db18-18ac-45d9-9f78-db9dc931476c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ce6942105099a0b</li>
        <li>Upwork Job ID: 1759888738434629632</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-20 10:33
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by rezkiy37** [comment] 2024-02-20 16:25
I am an author of a broken PR. However, I see that there is already a work in progress. If you need any help from me, please let me know.

**Comment by rezkiy37** [comment] 2024-02-20 16:26
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue, because I am an author of a broken [PR](https://github.com/Expensify/App/pull/34983). It is still a regression period.

**Comment by rezkiy37** [comment] 2024-02-20 17:29
Also, I have to mention that our threshold is 8 items to should a search bar and sections. So, users need 8 tags at least, not 9.

**Comment by rezkiy37** [comment] 2024-02-20 17:32
A draft PR has been opened. Going to open for a public review soon.

**Comment by Beamanator** [comment] 2024-02-21 10:00
@rezkiy37 is your PR ready for review yet? 🙏 

Also @allroundexperts I'll assign you here & in the PR since you were the C+ for https://github.com/Expensify/App/pull/34983

**Comment by Beamanator** [comment] 2024-02-21 12:14
PR merged! I'll start a convo in slack to see if we want to CP this or if we're planning to :donothing: due to the deploy freeze

**Comment by Beamanator** [comment] 2024-02-22 11:18
@tienifr honestly good question, the fix is insanely small and, while you did also propose the correct fix, I think it's only worth a payout if @rezkiy37 used your proposed solution to guide his fix

**Comment by Beamanator** [comment] 2024-02-22 11:19
Removing deploy blocker label since fix is now in staging

**Comment by rezkiy37** [comment] 2024-02-22 11:22
> ...I think it's only worth a payout if @rezkiy37 used your proposed solution to guide his fix

Yeah, the proposal helped me to fix the bug.

**Comment by Beamanator** [comment] 2024-02-22 11:32
Noice, then ya i think it does make sense for @tienifr to get some bonus for the help - cc @kevinksullivan , the payment pro in this issue

**Comment by kevinksullivan** [comment] 2024-02-22 19:09
Just to clarify, @tienifr should be getting paid the same as others for the help, or a fractional "bonus"?

**Comment by kevinksullivan** [comment] 2024-03-01 20:27
Payout summary:
- @allroundexperts $500
- @tienifr $125 (bonus for assisting with proposal)

@tienifr offer sent, let me know when you accept.

**Comment by JmillsExpensify** [comment] 2024-03-12 02:44
$500 approved for @allroundexperts based on summary.

**Comment by kevinksullivan** [comment] 2024-04-10 16:00
all set

**Closed by kevinksullivan** 2024-04-10 16:00 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
