### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000]  Assign Task - Description field line is displaced and moves up when typed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21280] opened 2023-06-21 23:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20689
## Action Performed:
1. Open http://staging.new.expensify.com/
2. Click on FAB menu / + actions in chat
3. Click on "Assign task"
4. Click on Description field
5. Type a letter

## Expected Result:
Description field line remains at the same place all the time

## Actual Result:
Description field line moves up when user types something

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img width="1440" alt="Bug6102069_Screenshot_2023-06-22_at_02 32 13" src="https://github.com/Expensify/App/assets/78819774/2693eb8c-f044-4209-a232-1be3f641cd7d">

https://github.com/Expensify/App/assets/78819774/74874b9c-c47f-42a3-b483-56cbddf689e5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @bernhardoj

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f2dca07ce0d7ce9</li>
        <li>Upwork Job ID: 1673920053781938176</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-06-22 01:30
## This is a Safari Browser Issue
- As we can see in `chrome` we are getting height as its already collapsed at initial render.
<img width="956" alt="Screenshot 2023-06-22 at 6 50 44 AM" src="https://github.com/Expensify/App/assets/78416198/f44d144e-c421-4a2f-b294-2a33e69d306a">

- But in `safari` it is set to `maxHeight`
<img width="1120" alt="Screenshot 2023-06-22 at 6 50 36 AM" src="https://github.com/Expensify/App/assets/78416198/0c3f9995-2fe7-4654-ad7f-450895cfcacf">

**Comment by jeet-dhandha** [comment] 2023-06-22 01:32
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- The problem is that when we are opening Assign Task modal in Safari browser, the description box collapses as we start typing in it.

### What is root cause of that problem?
- The main issue is that the height of Description Input is already set to `maxHeight minus some extra height params like padding` and when we are typing in it, it collapses as it is recalculatting TextInput height due to `autoGrowHeight(multiline)` property.

### What Changes do you think we should make in order to solve the problem?
Affected File Code: 

- We should update `StyleUtils.js` file's `getAutoGrowHeightInputStyle` function to set `height` to `textInputHeight` by default if the browser is Safari.

```diff
    function getAutoGrowHeightInputStyle(textInputHeight, maxHeight) {
    if (textInputHeight > maxHeight) {
        return {
            ...styles.pr0,
            ...styles.overflowAuto,
        };
    }

+   let height = maxHeight - styles.textInputMultilineContainer.paddingTop - styles.textInputContainer.borderBottomWidth;
+   if(Browser.getBrowser() === CONST.BROWSER.SAFARI) {
+       height = textInputHeight;
+   }
+
    return {
        ...styles.pr0,
        ...styles.overflowHidden,
        // maxHeight is not of the input only but the of the whole input container
        // which also includes the top padding and bottom border
-       height: maxHeight - styles.textInputMultilineContainer.paddingTop - styles.textInputContainer.borderBottomWidth,
+       height,
    };
}
```

Fixed:

https://github.com/Expensify/App/assets/78416198/1e334897-e291-4ed1-bd2e-668ff5ab3bd1

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by bernhardoj** [comment] 2023-06-22 09:45
Hi, I reported this issue 5 days ago here https://expensify.slack.com/archives/C049HHMV9SM/p1686997207642659. Will I get credited as the reporter?

**Comment by manjesh-yadav** [comment] 2023-06-25 11:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Description field height changed, when typed
### What is the root cause of that problem?

When we implement auto-grow text input, we use a hidden `<Text>` component to calculate the component's height to grow `<TextInput>` because the `<TextInput>` component doesn't support auto-grow.

We calculate height and width for input when React fired a `NativeEvent` called `onLayout` when our hidden  `<Text>` component rendered 

- The problem comes with Safari web browser (also in the Desktop application) when initially component is rendered with no value React is not able to fire `NativeEvent`
- And we are not able to calculate the height  of the hidden `<Text>`  component 
- Then our `<TextInput>` component render with max height CSS only


  





### What changes do you think we should make in order to solve the problem?

We just need a value in our hidden `<Text>` component  to fire `onLayout` event

It will work when we set a `placeholder` or if we have any `state value`, if we do not have a placeholder or state then just an **Empty string** will work, and later it will change with the `state value`

File: [App/src/components/TextInput/BaseTextInput.js](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/TextInput/BaseTextInput.js#L374-L392)
```diff
-      {this.state.value || this.props.placeholder}
+    {this.state.value || this.props.placeholder || ' '}


```

**Comment by JmillsExpensify** [comment] 2023-06-28 05:03
Agreed that this is a bug and I can reproduce it. I'm opening this one up for the community.

**Comment by narefyev91** [comment] 2023-06-28 11:52
Proposal from @kushu7 makes sense to me - we need to have the same workflow for both growing input vertically and horizontally - based on that adding 0 to initial state variable should fix a problem globally as well https://github.com/Expensify/App/issues/21280#issuecomment-1608105679
🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment] 2023-06-28 22:33
I believe this would have been fixed by https://github.com/Expensify/App/issues/20836. Is that not the case?

**Comment by thienlnam** [comment] 2023-06-28 23:52
Coolio, thanks!

**Comment by JmillsExpensify** [comment] 2023-07-13 22:53
It looks like this PR is ready for payment though @narefyev91 can you please get us kicked off with the BugZero checklist? Additionally, can either you or @thienlnam confirm that this PR is eligible for the 50% bonus. I'm not seeing an automated confirmation above. Checking the PR though, it looks like it is.

**Comment by narefyev91** [comment] 2023-07-14 06:41
- The PR that introduced the bug has been identified. Link to the PR - it was not a regression here - it's mostly code improvement after a fully re-writing BaseTextInput component
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - no needs any additional actions

**Comment by narefyev91** [comment] 2023-07-14 06:42
> * Fixed 21280 textinput autogrow height #21850

Seems so - issue was fixed during 1.5 - 2 days

**Comment by narefyev91** [comment] 2023-07-14 06:42
> It looks like this PR is ready for payment though @narefyev91 can you please get us kicked off with the BugZero checklist? Additionally, can either you or @thienlnam confirm that this PR is eligible for the 50% bonus. I'm not seeing an automated confirmation above. Checking the PR though, it looks like it is.

Seems so - issue was fixed during 1.5 - 2 days

**Comment by JmillsExpensify** [comment] 2023-07-14 23:15
Great thanks!

**Comment by JmillsExpensify** [comment] 2023-07-14 23:18
Alright, circling back on payments, I think we are done. Here's where we ended up:

 - Contributor: @kushu7 $1,500 (including 50% bonus)
 - Contributor+: @narefyev91 $1,500 (including 50% bonus)
 
 @narefyev91 please make sure that this is on our Callstack invoice. Otherwise, I'm closing this one out! 🙌🏼

**Closed by JmillsExpensify** 2023-07-14 23:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
