### ISSUE TITLE
autofocus not working if user open new task page using url

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20000] opened 2023-06-01 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open browser
2. paste new task url (https://staging.new.expensify.com/new/task/details)
## Expected Result: 
should auto focus title same as when user select Assign task option from FAB
## Actual Result: 
auto focus does not work

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c5229419-a728-4131-970a-4f4a0d110c74

https://github.com/Expensify/App/assets/43996225/52f1ddb7-27f7-4224-9c1c-6fdfee8831fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685451580697849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sethraj14** [comment] 2023-06-01 21:14
@kavimuru @gadhiyamanan Not reproducible on MacOS Chrome/Brave.

**Comment by gadhiyamanan** [comment] 2023-06-02 06:06
@sethraj14 can you share a video

**Comment by esh-g** [comment] 2023-06-02 06:18
https://github.com/Expensify/App/assets/77237602/c5f4bd02-daea-4106-9d0c-0bafde3d56e9

Not able to reproduce locally

**Comment by gadhiyamanan** [comment] 2023-06-02 06:24
@esh-g strange I am able to reproduce it locally with latest version(v1.3.22-1)

https://github.com/Expensify/App/assets/54790231/2f7cdae5-9fb2-48c3-b562-eb7da3fee0d6

**Comment by alitoshmatov** [comment] 2023-06-02 06:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
autofocus not working if user open new task page using url 
### What is the root cause of that problem?
We are not autoFocusing in initial render
### What changes do you think we should make in order to solve the problem?
We should set `autoFocus` prop in `TextInput`, here
https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/pages/tasks/NewTaskDetailsPage.js#L79-L83

### What alternative solutions did you explore? (Optional)

**Comment by sethraj14** [comment] 2023-06-02 06:52
@gadhiyamanan @esh-g already posted the video. This issue is not reproducible on our end.

**Comment by gadhiyamanan** [comment] 2023-06-02 07:24
@sethraj14 @esh-g in which version have you tested because me and testing team  able to reproduce https://github.com/Expensify/App/issues/20000#issuecomment-1573217964 https://github.com/Expensify/App/issues/20000#issue-1737031468

**Comment by esh-g** [comment] 2023-06-02 07:33
v1.3.22-1 same as you
<img width="348" alt="Screenshot 2023-06-02 at 1 03 08 PM" src="https://github.com/Expensify/App/assets/77237602/19ddb171-f991-49f5-910e-e4e011dff619">

**Comment by mallenexpensify** [comment] 2023-06-06 02:41
Unable to reproduce on v1.3.24-4, staging, Chrome.  Going to leave open since we're having mixed results for reproducing

https://github.com/Expensify/App/assets/22508304/7e14552b-1f02-4ec0-91e3-07dacd56ca0a

**Comment by mallenexpensify** [comment] 2023-06-09 00:25
Closing since I wasn't able to reproduce a few days ago nor now.  Comment if you disagree
<img width="447" alt="image" src="https://github.com/Expensify/App/assets/22508304/1de2d833-817a-4803-8765-17f2370d840f">

**Closed by mallenexpensify** 2023-06-09 00:25 UTC
Labels: Daily, Overdue, Bug
