### ISSUE TITLE
[HOLD][$500] Chat - "1 new message" badge does not disappear even after message is deleted by the sender

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8467] opened 2022-04-04 15:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from the web to the app
2. On the app, confirm that a new message arrived
3. On the web, delete the message

## Expected Result:
If the message was deleted, the "1 new message" notification should disappear.

## Actual Result:
After a message was deleted, the "1 new message" notification is still there.

## Workaround:
User has to relaunch the app or refresh the web

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.49-1 (1.1.49-1)

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5514972_4](https://user-images.githubusercontent.com/43996225/161576234-05c634d9-748a-4261-b9ac-360d50033f56.png)

https://user-images.githubusercontent.com/43996225/161576246-c38aeac3-a8c5-4ff3-955d-512e5f793db8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause (Exploratory)

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment] 2022-04-05 21:20
https://www.upwork.com/jobs/~01ab73f49ccf173b02

**Comment by Beamanator** [comment] 2022-04-14 22:45
Guess this can be doubled @arielgreen ? :D

**Comment by arielgreen** [comment] 2022-04-19 18:53
Price increased

**Comment by tgolen** [comment] 2022-04-20 22:51
I spent about 2.5 hours debugging this and I am completely lost. @parasharrajat it looks like you were someone that most recently touched [this code](https://github.com/Expensify/App/blob/971566b861796914c7080ac68064a0b1f266cfce/src/pages/home/report/ReportActionsView.js#L440-L448) so maybe you have some ideas.

There is the reports `unreadActionCount` that is stored in Onyx, then there is the `getDeletedCommentsCount()` function, and then a `localUnreadActionCount` and it just doesn't make sense how any of them work together.

I think what needs to happen is that when a message is deleted, the `unreadActionCount` in Onyx should decrease by 1. This should then cause the `ReportActionsView` to update in order to calculate a new (and correct) `localUnreadActionCount`.

However, what is happening is that when a message is deleted, the `unreadActionCount` in Onyx is always `0` for the currently visible chat, so the value in Onyx can't be decreased anymore and always remains at `0`. The behavior is different if you are NOT looking at the chat. In that case, then `unreadActionCount` always increases and decreases like you would expect it to.

Is this making any sense?

cc @marcaaron because I know we've talked about some of the problems with unread message counts.

**Comment by tgolen** [comment] 2022-04-20 22:53
Ultimately, it feels to me like the problem is that `localUnreadActionCount` is separate and different from `unreadActionCount` in Onyx. If instead, everything referred to the `unreadActionCount` in Onyx as the source of truth, then that seems like it would work much easier.

**Comment by marcaaron** [comment] 2022-04-21 01:08
Putting a hold on this and removing the External label. IMO issues dealing with "unreads" need to wait until this logic is improved holistically. See my WN post [here](https://expensify.slack.com/archives/CC7NECV4L/p1648745342332069).

**Comment by marcaaron** [comment] 2022-04-21 01:50
>Ultimately, it feels to me like the problem is that localUnreadActionCount is separate and different from unreadActionCount in Onyx. If instead, everything referred to the unreadActionCount in Onyx as the source of truth, then that seems like it would work much easier.

Agree this is a big part of the confusion. Also just having separate concepts like "unread marker badge" and "unread count" makes it hard to tell what the difference is between:

- floating unread message counter badge
- new line indicator
- unread action count
- last read action
- etc...

Would love a solution where the server is the ultimate source of truth here. All the logic to calculate based on number of actions and number of deleted actions seems like it needs a general re-thinking.

**Comment by parasharrajat** [comment] 2022-04-21 12:06
`localUnreadActionCount` is different from the unreadActionCount. It was necessary to keep the local count of unread messages when the user is active on the report. 

As soon as a new message is received for an active report. it will be marked read(at least when this feature was built) thus `unreadActionCount` will reset.  There have been many changes to the code since then. 

The overall thought is the same as Marc. We need to simplify this logic. `unreadActionCount` is not always correct due to which a lot of code is added to fix the unread count.

> I think what needs to happen is that when a message is deleted, the unreadActionCount in Onyx should decrease by 1.

No, it can't be. Users can delete an old message whose seq number is before the unread messages. So the current logic is 
- getUnreadCount - (get the deleted messages between the last Unread message sq and the latestsq).

**Comment by tgolen** [comment] 2022-04-21 14:20
> No, it can't be. Users can delete an old message whose seq number is before the unread messages.

Ah yes, you're right. It would only decrease the unread count if the deleted message was in the group of the unread ones.

@marcaaron how do you think we should move forward with this? I am kind of thinking that we place this on HOLD until we have a plan for refactoring the unread message counts. It seems like adding another hack on top of existing code at this stage would be a mistake.

**Comment by marcaaron** [comment] 2022-04-21 16:58
>adding another hack on top of existing code at this stage would be a mistake

Agree. This is at the top of my priority list to look into once the network improvements are made.

**Comment by Beamanator** [comment] 2022-05-02 12:09
On hold, will be picked up once Marc has time - removing `Exported` since it's an `Internal` job for now, and unassigning

**Comment by arielgreen** [comment] 2022-05-10 23:54
Removed from Upwork, unassigning myself

**Comment by Justicea83** [comment] 2022-05-23 09:31
removing my assignment since we still haven't improved the unread message logic yet!

**Comment by Beamanator** [comment] 2022-08-29 08:25
I thinkkkk we still want to do this even though it's not top priority at the moment (maybe it should be this week) so i'll reopen

**Comment by marcaaron** [comment] 2022-08-29 09:15
I'm prioritizing the unread indicators changes this week. Once they are merged we can come back and see if this is still an issue. Though in reality we are deprecating the "counting badge" in favor of a simple badge that doesn't count so unsure if this is still a problem.

**Comment by marcaaron** [comment] 2022-09-21 05:52
Seeing as we have now fully deprecated the "New messages" counter badge (it does not show a count anymore) this should no longer be an issue.

**Closed by marcaaron** 2022-09-21 05:52 UTC
Labels: Engineering, Monthly, Internal, Planning, Not a priority
