### ISSUE TITLE
[$500] Android - Attachment - A long image is severely compressed when added to a conversation.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33348] opened 2023-12-20 12:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites:
File for example https://drive.google.com/file/d/18-C7XPRHJbb91kJ2U3l5T-rjf8h1y-sT/view?usp=share_link

Steps:
1. Open New Expensify app
2. Log in under any account
3. Navigate to any conversation
4. Click on Compose Box - Add attachment
5. Add the file from the example
6. Zoom in on the preview image
7. Send image
8. Open the sent image and zoom in

## Expected Result:
When adding a long image to a conversation, it should not compress and the text should remain readable.

## Actual Result:
When adding a long image to a conversation, the image is severely compressed and the text is unreadable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c521d180-48f8-44bb-8459-4b6bef48c169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc17ff80e622aa44</li>
        <li>Upwork Job ID: 1742964789111771136</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-12-20 12:53
Not reproducible in production

https://github.com/Expensify/App/assets/93399543/b25b8d06-2d19-4a2e-92b7-4cdb7c108c2c

**Comment by jasperhuangg** [comment] 2023-12-21 01:32
doesn't need to be a blocker

**Comment by Beamanator** [comment] 2023-12-22 08:37
Innnteresting, i wonder if it's related to https://github.com/Expensify/Web-Expensify/pull/40183

**Comment by zanyrenney** [comment] 2023-12-22 13:24
just a note that i'm OOO until 5th Jan, if this needs BZ management or help or payout, please expect a delay until then. if its urgent, reapply the BZ label - thanks!

**Comment by Beamanator** [comment] 2023-12-27 18:51
Still only working part time ish for the holidays, this doesn't seem like a priority since it's still working, just compressing long images a bit so won't focus on this for a bit

**Comment by Beamanator** [comment] 2024-01-04 17:42
making external to try to get some help since this is a lower priority for me

**Comment by zanyrenney** [comment] 2024-01-08 11:54
@hoangzinh what do you think of the latest comment from @jamil-zaitouny ? Please review and get back to us :)

**Comment by zanyrenney** [comment] 2024-01-11 11:32
Sure thing!

**Comment by zanyrenney** [comment] 2024-01-11 11:35
Can't repdroduce on iOS device.

**Comment by zanyrenney** [comment] 2024-01-11 11:35
I don't have a phyical Andriod device so will have to test on a simulator.... hold on!

**Comment by zanyrenney** [comment] 2024-01-11 11:43
no reproducible on browserstack, closing!

**Closed by zanyrenney** 2024-01-11 11:43 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
