### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - On back button press navigates to Confirm task screen instead of hide modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21200] opened 2023-06-21 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + icon and choose Assign task option
2. Enter title and click on Next button
3. Click on Assign and select any Assign
4. Click on confirm task button
5. Go to task thread
6. Click on Assign
7. Click on back button

## Expected Result:
It should hide the modal on click of back button

## Actual Result:
on back button press navigates to Confirm task

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/da835c55-6b6c-4ae4-973b-c74d1ef429f8

https://github.com/Expensify/App/assets/93399543/208e5360-9199-4187-97fb-ff64973240c9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686738116807699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cb24f67bd54c980</li>
        <li>Upwork Job ID: 1671909296462548992</li>
        <li>Last Price Increase: 2023-07-27</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 25886169</li>
<li>gadhiyamanan | Reporter | 25886171</li>
</ul></li>
    </ul>
</details>

**Comment by gadhiyamanan** [comment] 2023-06-21 13:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
on back button press navigates to Confirm task screen instead of hide modal
### What is the root cause of that problem?
 onBackButtonPress we are navigating to  "NEW_TASK" screen instead back 
 https://github.com/Expensify/App/blob/c2059ef9b01b9bd27e1c7e691ba6fdc71a926de3/src/pages/tasks/TaskAssigneeSelectorModal.js#L179-L182
### What changes do you think we should make in order to solve the problem?
we can remove onBackButtonPress from below code because as default it will be navigated to back
https://github.com/Expensify/App/blob/c2059ef9b01b9bd27e1c7e691ba6fdc71a926de3/src/pages/tasks/TaskAssigneeSelectorModal.js#L179-L182


### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-06-21 13:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On back button press navigates to Confirm task screen instead of hide modal

### What is the root cause of that problem?
In this [PR](https://github.com/Expensify/App/commit/123f88908ac4d1ae3cc1cc2054ff39c8d184cf6a) this navigation updation took place where on the back we are navigating `ROUTES.NEW_TASK` from the Assignee Selection page. This is causing the issue and it will take user to New Task page all the time.

### What changes do you think we should make in order to solve the problem?
It seems this navigation part added bcoz if the user refresh on assignee selection page and then click on back it will take the user to the New Task page but for already assigned task we should not want to be land on New Task page. So we need to navigate based on the params(if report id is available then just go back or else for new task part navigate to new task page)

https://github.com/Expensify/App/blob/0b7455fa832b53eccb99ca23c70e131b3464fb1d/src/pages/tasks/TaskAssigneeSelectorModal.js#L181

Need to update the condition to 
```
onBackButtonPress={() => props.route.params.reportID ? Navigation.goBack() : Navigation.goBack(ROUTES.NEW_TASK)}
```

**Comment by isabelastisser** [comment] 2023-06-23 19:52
I will be OOO until July 5, so assigning another team member. [SO](https://stackoverflowteams.com/c/expensify/questions/883) for reference.

**Comment by dylanexpensify** [comment] 2023-06-26 17:46
Didn't get to today, but will tackle tomorrow!

**Comment by dylanexpensify** [comment] 2023-06-29 07:03
@eVoloshchak can we get reviews on proposals today??

**Comment by eVoloshchak** [comment] 2023-06-29 07:05
@dylanexpensify, reviewing this today

**Comment by eVoloshchak** [comment] 2023-06-29 16:38
@daraksha-dk, your [proposal](https://github.com/Expensify/App/issues/21200#issuecomment-1600800947) would break the normal behavior, where you can go back to the previous screen, but the modal is closed

 @gadhiyamanan, your [proposal](https://github.com/Expensify/App/issues/21200#issuecomment-1600812532) would also casue an issue  @Pujan92 has described [here](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032) (i.e. incorrect navigation after page refresh)
 
 @Pujan92's [proposal](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032) looks good to me
 We need to create a separate method for this, since `Navigation.goBack(ROUTES.NEW_TASK)` is used for all pages inside `tasks`, not just for this one.
 
 🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment] 2023-07-03 08:47
reviewing today and posting next steps!

**Comment by jeet-dhandha** [comment] 2023-07-05 16:40
PROPOSAL:  https://github.com/Expensify/App/issues/22012#issuecomment-1616008937
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> - Back Press of Assignee Change screen is navigating to `NEW_TASK` route instead of previous route.
> 
> ### What is the root cause of that problem?
> - Root cause is the default path NEW_TASK in `Navigation.goBack` function.
> ```js
> <HeaderWithBackButton
>     title={props.translate('newTaskPage.assignee')}
>     onBackButtonPress={() =>  Navigation.goBack(ROUTES.NEW_TASK)}
> />
> ```
> 
> ### What changes do you think we should make in order to solve the problem?
> - If we are navigating from edit task then we should pass `null` as argument in `Navigation.goBack`  function, which will navigate it back to previous path.
> 
> ```js
> const isEditing = props.task.report.reportID === props.route.params.reportID;
> 
> ...rest code
> 
> <HeaderWithBackButton
>     title={props.translate('newTaskPage.assignee')}
>     onBackButtonPress={() =>  Navigation.goBack(isEditing ? null : ROUTES.NEW_TASK)}
> />
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> - N/A

**Comment by isabelastisser** [comment] 2023-07-06 01:57
I'm back. Thanks @dylanexpensify!

@eVoloshchak, can you please review the proposals above? Thanks!

**Comment by isabelastisser** [comment] 2023-07-06 15:40
@eVoloshchak bump to review the proposals above.

**Comment by eVoloshchak** [comment] 2023-07-06 17:04
@isabelastisser, I've posted a review [here](https://github.com/Expensify/App/issues/21200#issuecomment-1613508370), waiting for @dylanexpensify's opinion

**Comment by jeet-dhandha** [comment] 2023-07-06 17:05
@eVoloshchak https://github.com/Expensify/App/issues/21200#issuecomment-1622116812 - Last review if possible.

**Comment by isabelastisser** [comment] 2023-07-10 10:13
@eVoloshchak, how do you think we should proceed here?

**Comment by eVoloshchak** [comment] 2023-07-10 21:48
> Last review if possible

@jeet-dhandha, your approach is quite similar to @Pujan92's [proposal](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032), the only difference is how we distinguish between create/edit mode

**Comment by eVoloshchak** [comment] 2023-07-10 21:49
> how do you think we should proceed here?

@isabelastisser, I can't reproduce this anymore

https://github.com/Expensify/App/assets/9059945/1a6bc5b6-abf7-4110-b816-b4657b1cf015

**Comment by isabelastisser** [comment] 2023-07-11 09:39
@eVoloshchak, thanks for the info; I will process the payment to the issue reporter and your partial payment for reviewing the proposals, then close the issue.

**Comment by isabelastisser** [comment] 2023-07-11 09:44
All set, closing!

**Comment by Pujan92** [comment] 2023-07-11 10:23
@eVoloshchak @isabelastisser I am still able to reproduce for the below use case.

1.  Open task report
2. Fab icon -> Assign task
3. Close the modal -> click on assigne to open assignee page
4. Go back

https://github.com/Expensify/App/assets/14358475/32cecc8e-4fdb-4aee-b5e9-c22105a5afbb

**Comment by Pujan92** [comment] 2023-07-11 10:32
cc: @jasperhuangg as he added the condition for it. Do you think this [proposal](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032) will solve above [issue](https://github.com/Expensify/App/issues/21200#issuecomment-1630566092) (Instead of `isExistingTaskReport` use route params to decide back navigation)?

https://github.com/Expensify/App/pull/20841/files#diff-7222ad8495df7dcb3a991b88dc01ef79a912db9feb63051074604bf229c9f007L181

**Comment by Pujan92** [comment] 2023-07-12 13:00
@isabelastisser @eVoloshchak can you plz check on [this](https://github.com/Expensify/App/issues/21200#issuecomment-1630566092) and reopen if needed

**Comment by eVoloshchak** [comment] 2023-07-26 18:28
@Pujan92, can reproduce this using your [steps](https://github.com/Expensify/App/issues/21200#issuecomment-1630566092), this is interesting

@kbecciv, could you please check if you can reproduce using [these steps](https://github.com/Expensify/App/issues/21200#issuecomment-1630566092) and reopen if needed? Thanks!

**Comment by jasperhuangg** [comment] 2023-07-26 18:32
If we can reproduce this and end up reopening it, I think @Pujan92's proposal [here](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032) should solve the issue

**Comment by kbecciv** [comment] 2023-07-27 11:26
Able to reproduce it

https://github.com/Expensify/App/assets/93399543/3200889d-bc50-4f7e-a89d-5b550ba64a40

**Comment by eVoloshchak** [comment] 2023-07-31 15:48
Thanks for the confirmation!
In that case, I think we can move forward with @Pujan92's proposal [here](https://github.com/Expensify/App/issues/21200#issuecomment-1600841032)

**Comment by Pujan92** [comment] 2023-07-31 16:47
@eVoloshchak Thanks, I think reviewed stamp is required to assign it to the internal engineer.

**Comment by isabelastisser** [comment] 2023-08-01 18:05
@Pujan92, I assigned you now. You can start working on this now, thanks!

**Comment by pecanoro** [comment] 2023-08-18 09:00
@eVoloshchak Can you complete the list so we can proceed with the payment?

@isabelastisser All yours to handle payments!

**Comment by isabelastisser** [comment] 2023-08-18 17:58
Payment summary:

- Issue reported by @gadhiyamanan $250 - previously paid in Upwork.
- C+ review: @eVoloshchak $1000. New dot payment
- Approved proposal: @Pujan92  $1000

**Comment by isabelastisser** [comment] 2023-08-18 17:59
@eVoloshchak please complete the checklist when you have a chance, thanks!

**Comment by eVoloshchak** [comment] 2023-08-22 11:25
- The PR that introduced the bug has been identified. Link to the PR: that's the way it was implemented initially in https://github.com/Expensify/App/pull/17992, 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this is a typical bug with modal navigation
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
This has a very low impact, doesn't break the UX, a regression test isn't necessary I think

**Comment by JmillsExpensify** [comment] 2023-08-24 05:40
Reviewed the details for @eVoloshchak. $1,000 approved for payment via NewDot based on BZ summary.

**Comment by isabelastisser** [comment] 2023-08-24 17:09
- All the payments were processed.
- A regression test is not needed.

We are all set here.

**Closed by isabelastisser** 2023-08-24 17:09 UTC
Labels: External, Weekly, Awaiting Payment, Bug
