### ISSUE TITLE
[Collect approvers] [$500] Expense - Report submission and approval messages only come through after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34065] opened 2024-01-05 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of a Collect workspace on Old Dot
1. [Old Dot] Create a report with expense
2. [New Dot] Log in with the same account
3. [New Dot] Open the expense report from workspace chat
4. [Old Dot] Submit the report
5. [Old Dot] Approve the report
6. [Old Dot] Mark the report as reimbursement
7. [New Dot] Go to main chat and then click on the preview to return to report

## Expected Result:
On New Dot, the system message for report submission and approval will appear in the expense report without refreshing the page

## Actual Result:
On New Dot, the system message for report submission and approval only appear in the expense report after refreshing the page. While the reimbursement message appears without issue and without having to refresh the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f901f33a-0fbd-421d-b387-db169d91c0f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137e8422a18862fdd</li>
        <li>Upwork Job ID: 1743372915513012224</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28095067</li>
</ul></li>
    </ul>
</details>

**Comment by getusha** [comment] 2024-01-08 19:10
Still waiting for proposals

**Comment by waterim** [comment] 2024-01-10 17:52
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by waterim** [comment] 2024-01-11 14:17
I don't have a submit button on OldDot:
This is from video:
<img width="179" alt="image" src="https://github.com/Expensify/App/assets/39777589/32a2cd20-560d-44e8-98d9-40c717a966df">

This is mine:
<img width="330" alt="image" src="https://github.com/Expensify/App/assets/39777589/e994ed5e-0c0d-431d-a982-bb6780d70668">

I have a questions
 Am I doing something wrong here that I don't have it?

From my perspective everything is working fine with system messages
<img width="755" alt="image" src="https://github.com/Expensify/App/assets/39777589/0b1bfac6-733d-4428-a1ee-9f7ca3aa3185">

**Comment by waterim** [comment] 2024-01-11 14:59
After my investigation I found an issue that pusher is not sending a "reportComment" event, it updates the state, but not sending a message. 
<img width="451" alt="image" src="https://github.com/Expensify/App/assets/39777589/6d43d089-0651-4781-be03-a474bcb1a350">

At the same time for REIMBURSED pushed is updating state and also sends a reportComment event.
<img width="543" alt="image" src="https://github.com/Expensify/App/assets/39777589/a7703877-3eda-49df-a544-01bea3e6fb9a">

Looks like a backend issue.

**Comment by bondydaa** [comment] 2024-01-15 20:34
assigning to Marco per https://expensify.slack.com/archives/C02MW39LT9N/p1705350401639809

**Comment by marcochavezf** [comment] 2024-01-17 23:46
No update, focused on another wave7 issue

**Comment by marcochavezf** [comment] 2024-01-19 01:36
No update, I will continue with this one after wrapping up the other one

**Comment by marcochavezf** [comment] 2024-01-20 00:01
Working on it

**Comment by NicMendonca** [comment] 2024-01-23 21:00
@marcochavezf any update here?

**Comment by marcochavezf** [comment] 2024-01-24 20:44
Still working on it, aiming to raise up a PR today

**Comment by marcochavezf** [comment] 2024-01-25 16:48
Still working on it, I found another issue with report submission

**Comment by marcochavezf** [comment] 2024-01-29 18:03
The first PR was merged, still working on the tests for the second PR

**Comment by marcochavezf** [comment] 2024-01-30 19:53
Completing the automated test today

**Comment by marcochavezf** [comment] 2024-01-31 01:58
PRs up for the approval from OldDot:
- https://github.com/Expensify/Auth/pull/9746
- https://github.com/Expensify/Web-Expensify/pull/40729

**Comment by NicMendonca** [comment] 2024-01-31 19:39
Starting leave so re-assigning!

**Comment by marcochavezf** [comment] 2024-02-05 16:24
PRs up to send all report data after approval [here](https://github.com/Expensify/App/issues/34065#issuecomment-1918230429)

**Comment by greg-schroeder** [comment] 2024-02-06 01:09
Nice, thanks @marcochavezf

**Comment by marcochavezf** [comment] 2024-02-12 17:38
[PR](https://github.com/Expensify/Auth/pull/9746) deployed to production

**Comment by marcochavezf** [comment] 2024-02-15 21:59
I will add the `retest-weekly` to ensure it passes QA

**Comment by mvtglobally** [comment] 2024-02-27 16:18
Issue is reproducible during KI retests.

**Comment by greg-schroeder** [comment] 2024-04-05 21:30
@marcochavezf can you help me understand where this issue is at? Should this be closed as the PR was deployed a while ago...

**Comment by marcochavezf** [comment] 2024-04-07 23:23
Hmm seems there's still an [issue](https://github.com/Expensify/App/issues/34065#issuecomment-1966928461) here. I will move it to weekly (since it's a polish issue) to check it out accordingly

**Comment by greg-schroeder** [comment] 2024-04-15 02:42
Okay, thanks!

**Comment by trjExpensify** [comment] 2024-04-30 13:55
Is this still a bug? It hasn't been retested since Feb, and I can't recall the refresh on some recent testing. Let's clarify if it's still a bug, and what conditions exactly we need to replicate.

**Comment by greg-schroeder** [comment] 2024-05-01 22:06
Asking for retest

**Comment by marcochavezf** [comment] 2024-05-02 18:33
I was able to reproduce the approval message from OldDot, working on a fix

**Comment by marcochavezf** [comment] 2024-05-02 18:50
[PR](https://github.com/Expensify/Auth/pull/10767) up

**Comment by greg-schroeder** [comment] 2024-05-09 05:08
PR was just deployed

**Comment by greg-schroeder** [comment] 2024-05-13 12:20
Automation didn't work - seems this can be closed as no external folks worked on this.

**Closed by greg-schroeder** 2024-05-13 12:20 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug, retest-weekly
