### ISSUE TITLE
[$1000] Web - Assignee name and avatar is not dynamically updating after renaming from account B

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22293] opened 2023-07-05 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open two new accounts (account A and account B)
2. Go to account B and copy the email
3. Go to account A and click on FAB > assign task > give a title > click next
4. Click on assignee and paste the copied email and select it
5. Go to account B and click on settings > name > rename it
6. Click on the profile picture and give it a profile picture

## Expected Result:
Both assignee and share somewhere avatar and name should dynamically update after renaming from account B

## Actual Result:
Only share somewhere gets updated and assignee doesn't update dynamically.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/03455a6f-5037-4243-86f1-94b3452376d0

https://github.com/Expensify/App/assets/93399543/f544288c-db02-46f2-a218-499cc70f57e1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688449071046279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138dda630214da2a7</li>
        <li>Upwork Job ID: 1677356023664472064</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-07-07 16:36
Looks good!

**Comment by BhuvaneshPatil** [comment] 2023-07-07 16:42
I tried pulling the main branch, this is not reproducible on main

**Comment by sakluger** [comment] 2023-07-10 21:39
Heads up, I just closed a related issue with the same root cause: https://github.com/Expensify/App/issues/22481. It's the same behavior, but on a different page (the task assignee contact list). Let's make sure that the fix here also fixes that other page.

**Comment by Swor71** [comment] 2023-07-11 11:48
> Heads up, I just closed a related issue with the same root cause: #22481. It's the same behavior, but on a different page (the task assignee contact list). Let's make sure that the fix here also fixes that other page.

has the root cause been identified or just the behaviour?

**Comment by sakluger** [comment] 2023-07-11 21:01
@Swor71 just the behavior, but the issue is the same, so I still think we should try to investigate both and fix together.

**Comment by slafortune** [comment] 2023-07-12 18:41
Great!  Assigning you @Swor71 !

**Comment by Swor71** [comment] 2023-07-17 08:42
not overdue. I found the root cause and I am working on a proposal.

**Comment by slafortune** [comment] 2023-07-19 20:26
@Swor71 is this on your radar?

**Comment by Swor71** [comment] 2023-07-20 08:43
@slafortune hey, yes I am aware of this, unfortunately this seems a bit more entangled than I originally thought. I might actually reach out in slack to discuss this further.

**Comment by Swor71** [comment] 2023-07-24 11:22
the issue and some suggested solutions are currently in an internal discussion

**Comment by Swor71** [comment] 2023-07-25 14:19
the proposal is in an internal discussion

**Comment by Swor71** [comment] 2023-07-26 14:49
## Proposal
Please re-state the problem that we are trying to solve in this issue.
During the process of assigning a task to a user, if that assignee’s name changes, it is not reflected in the UI. This happens for new users only.

### What is the root cause of that problem?
I believe the root cause for this issue is the whole process of creating an optimistic user account (`userToInvite` in `optionsListUtils`) when doing a ‘look up’ while assigning the task. From the `optimisticAccountID` a lot of other entries are spawned like report’s `participantAccountIDs`, icon/avatar, task’s `assigneeAccountID` among others. The `assigneeAccountID` in `task` (Onyx) is not the correct id for the account we’re assigning the task to, and it is never changed. Additionally, the `personalDetailsList` entry created from `userToInvite` is not cleaned up.

### What changes do you think we should make in order to solve the problem?
The quick fix is to reassign the task’s `assigneeAccountID` as well as report’s `participantAccountIDs` to the correct ID for a given account. This should be done in `NewTaskPage` component.

In my opinion, however, the better fix would be to address the ‘fake’ look up as that is the root of the problem. If the look up worked as an actual feature, we’d already have the correct id and every following action of creating the report, setting correct avatar, task’s assignee id, participant account ids and else, would work as intended. To my mind, creating the incorrect optimistic account and sprouting the above from it only to patch it a moment later feels wrong. Not to mention the odd UX for looking up an account, only to see a random avatar being created, assigned and then flipped to the correct one when data arrives from the pusher.

**Comment by slafortune** [comment] 2023-07-26 20:39
@eVoloshchak can we move forward with this?

**Comment by Swor71** [comment] 2023-07-28 14:54
Just wanted to inform you that I will be OOO for the next two weeks due to planned holidays. One of my colleagues from Callstack will pick this one up. I have pushed my changes for the quick fix since the proper fix needs discussion on the part of Expensify team.

**Comment by slafortune** [comment] 2023-07-31 13:57
Checking on this - https://expensify.slack.com/archives/C02NK2DQWUX/p1690811805490969

**Comment by eVoloshchak** [comment] 2023-07-31 14:21
@Swor71, thank you for such a thorough investigation!

> In my opinion, however, the better fix would be to address the ‘fake’ look up as that is the root of the problem. If the look up worked as an actual feature, we’d already have the correct id and every following action of creating the report, setting correct avatar, task’s assignee id, participant account ids and else, would work as intended. To my mind, creating the incorrect optimistic account and sprouting the above from it only to patch it a moment later feels wrong.

I totally agree with this. I'm not sure if we need to apply a [quick fix](https://github.com/Expensify/App/pull/23795) for this, since we're technically working around a bigger problem as you've described.  Let's fix the actual root cause instead, that will also ensure we don't have the same problem on other pages/flows

**Comment by arthurmfgtab** [comment] 2023-08-01 15:31
Hey all, I'll be taking this over for the time being until @Swor71 is back from ooo

**Comment by slafortune** [comment] 2023-08-02 20:24
I've assigned you to the GH now @arthurmfgtab  - I'll update the tags again.  It would great to get this one resolved 👍

**Comment by arthurmfgtab** [comment] 2023-08-07 17:16
Still getting up to speed on Marcin's solution..

**Comment by arthurmfgtab** [comment] 2023-08-10 08:31
Update: we have a draft PR that we're discussing internally. It follows Marcin's [proposal](https://github.com/Expensify/App/issues/22293#issuecomment-1651969348) but it's not fully ready yet.

**Comment by arthurmfgtab** [comment] 2023-08-10 15:14
@slafortune We have this [draft PR](https://github.com/Expensify/App/pull/23795) that uses the solution discussed in the [proposal](https://github.com/Expensify/App/issues/22293#issuecomment-1651969348). 
The solution requires that Pusher sends a complete response to user 1 when user 2 updates his/her name. Right now only `firstName`, `lastName` and `displayName` are being send, but we also need `login` (containing the user's email). 

Do you think we could talk to the backend folks to include that extra info on the response?


![](https://files.slack.com/files-pri/T02P6RS2ZK7-F05M927HPV0/screenshot_2023-08-10_at_17.06.17.png)

**Comment by arthurmfgtab** [comment] 2023-08-14 09:05
@eVoloshchak @slafortune could you guys take a quick look at the comment above? :)

**Comment by arthurmfgtab** [comment] 2023-08-16 11:37
Not oversue, waiting for @eVoloshchak and @slafortune answers

**Comment by slafortune** [comment] 2023-08-18 14:24
Thanks for calling this out @arthurmfgtab - I'll defer to @eVoloshchak on [this](https://github.com/Expensify/App/issues/22293#issuecomment-1673421245), they will be best to answer this.

**Comment by slafortune** [comment] 2023-08-18 15:29
Getting an internal engineer assigned (Melvin must have missed that at some point) to help answer and push this forward.

**Comment by NikkiWines** [comment] 2023-08-18 17:49
@arthurmfgtab just to confirm, you want to include the `login` in the response from the API when the user modifies their display name (which ends up calling `UpdateDisplayName`), right?

**Comment by arthurmfgtab** [comment] 2023-08-22 07:16
@NikkiWines correct!

**Comment by NikkiWines** [comment] 2023-08-25 18:09
PR is up + approved, should be deployed to prod early next week

**Comment by arthurmfgtab** [comment] 2023-08-29 08:46
Hey all, I'll look into this today

**Comment by puneetlath** [comment] 2023-08-29 17:38
Hi! Sorry, I'm coming into this way late, but would someone mind explaining to me why we need the login in order to be able to update the avatar/display name of the task assignee? I would think that having the accountID should be enough, but I'd love to understand better why that isn't the case. Thanks in advance!

**Comment by arthurmfgtab** [comment] 2023-08-31 16:25
Hey @slafortune , 2 things I noticed today as I was working on this

1. "login" doesn't seem to be on production yet (see image below)
![Screenshot 2023-08-31 at 17 18 54](https://github.com/Expensify/App/assets/55854142/2a704d28-a433-45bb-9e0c-6536f5eb1224)

2. Did we remove the "fake lookup" feature? (showing an account regardless of whether that account really exists on the backend), (see video below)

https://github.com/Expensify/App/assets/55854142/026bf524-d938-47b9-9f66-224a9465651e

**Comment by puneetlath** [comment] 2023-08-31 20:48
Thanks for the link @arthurmfgtab. I would think that what should happen is: 

1. We use the optimisticID in all the various place while creating the task 
2. The server returns all the Onyx data with the correct optimisticID
3. in the successData for the API call, we clear out the data that we set using the optimisticID

Can we do that? That should make it so that we don't need the login field but still get the task pointed to the correct account.

**Comment by arthurmfgtab** [comment] 2023-09-05 17:25
@puneetlath thanks for the suggestion and sorry about the delay on replying ya

About the steps you proposed: from my understanding your solution requires that the optimisticID and the ID of the actual user created on the backend (that will be then sent to the frontend by pusher) are the same, correct? 

If so, that's the whole point of the ticket. We need a field that's shared by both objects (the local one created on the frontend and the real one on the backend) so we can use that field to merge the right objects.

Does that make sense?

**Comment by puneetlath** [comment] 2023-09-05 20:25
Ah, that's not quite what I was suggesting. I was suggesting that it's fine if the accountIDs are different. So the flow would be: 

1. I create task and assign it to "unknown@gmail.com"
2. Since I don't yet "know" that email within Expensify, we optimistically assign the task to accountID1234
3. So now we have taskID=1 assigned to optimistic accountID=1234
4. The API returns taskID=1 assigned to real accountID=5678 along with public personal details for account 5678 (doesn't include email)
5. SuccessData clears out optimistic user 1234

Would that not work? Is it because tasks currently use mentions for showing who is assigned and mentions are login-baed instead of accountID-based?

**Comment by slafortune** [comment] 2023-09-08 16:45
@arthurmfgtab thoughts on this?

Also, I'm out on sabbatical so adding a new BZ member.

**Comment by jliexpensify** [comment] 2023-09-12 00:33
Bumping @arthurmfgtab to address Puneet's comment [here](https://github.com/Expensify/App/issues/22293#issuecomment-1707263194)

**Comment by arthurmfgtab** [comment] 2023-09-12 09:05
Hey team, I'll look into this today

**Comment by jliexpensify** [comment] 2023-09-14 07:15
@arthurmfgtab just a friendly bump to move this one along cheers!

**Comment by arthurmfgtab** [comment] 2023-09-14 08:02
Hey @jliexpensify , sorry about this, I'll test Puneet's idea and give a feedback

**Comment by jliexpensify** [comment] 2023-09-18 00:45
Bump @arthurmfgtab - how are you going? Let's move this one along!

**Comment by arthurmfgtab** [comment] 2023-09-21 13:13
Hey @puneetlath , about your suggestion [here](https://github.com/Expensify/App/issues/22293#issuecomment-1707263194)

So, basically, as soon as the api returns the real user data we start "pointing" to it and delete the optimistic one (user 1234), instead of replacing the optimistic object with the real data, correct?

If so, I don't see how we would know which object to delete as soon as the real one is pushed to the frontend because, as far as I can see, the objects don't share any value:

![image](https://github.com/Expensify/App/assets/55854142/711661c7-6e07-4032-b24a-e9d24f14133d)

**Comment by arthurmfgtab** [comment] 2023-09-21 13:16
@puneetlath I dropped a message to you on Slack so we can try to syncronously talk about this and try to find a solution together :)

**Comment by arthurmfgtab** [comment] 2023-09-21 13:21
Also, @jliexpensify , do you have insight on the #2 question [here](https://github.com/Expensify/App/issues/22293#issuecomment-1701367641)? Just want to confirm whether something has changed because I used to be able to assign tasks to fake emails but now I can't 🤔

https://github.com/Expensify/App/assets/55854142/5bbe9374-0da4-40c9-bafa-fb10130a2e9a

**Comment by arthurmfgtab** [comment] 2023-09-21 13:24
I'll be ooo tomorrow but I'm getting back to this on Monday

**Comment by jliexpensify** [comment] 2023-09-22 02:34
@arthurmfgtab yeah, it looks like a change was made a month ago here: https://github.com/Expensify/App/pull/25806

**Comment by puneetlath** [comment] 2023-09-26 08:02
Any thoughts @arthurmfgtab?

**Comment by arthurmfgtab** [comment] 2023-09-26 08:44
taking a look at [this](https://github.com/Expensify/App/pull/25806), will share my thoughts in a few

**Comment by jliexpensify** [comment] 2023-10-03 04:17
@arthurmfgtab any updates?

**Comment by arthurmfgtab** [comment] 2023-10-04 09:55
@jliexpensify I tested the feature and indeed the "fake look up" was removed, which I think solves our issue because the assignee name and avatar not being changed was a problem for "local users" (the ones with fake data that would eventually be overwritten by an object with the proper user data). 

If, for instance, account A adds someone to a workspace and, while holding on the "Assign Task" action, the account B changes his/her information those are properly updated on the account A's screen, so it's working fine I think:


https://github.com/Expensify/App/assets/55854142/26f5c47c-f899-414e-b2ac-b723c90e14aa

**Comment by arthurmfgtab** [comment] 2023-10-04 20:37
@puneetlath , I'm sorry, do what exactly? 😄

**Comment by jliexpensify** [comment] 2023-10-09 23:27
Bumping @puneetlath here - this [comment](https://github.com/Expensify/App/issues/22293#issuecomment-1746534683) sounds like the issue is fixed?

**Comment by jliexpensify** [comment] 2023-10-16 00:13
Waiting on Puneet - [comment](https://github.com/Expensify/App/issues/22293#issuecomment-1754055655)

**Comment by jliexpensify** [comment] 2023-10-19 02:24
Not overdue

**Comment by jliexpensify** [comment] 2023-10-24 04:31
Bumping @puneetlath to [confirm](https://github.com/Expensify/App/issues/22293#issuecomment-1746534683) that we can close this issue.

**Comment by puneetlath** [comment] 2023-10-25 23:59
Sorry for the delay! Sounds like we can indeed close the issue as long as everything is working as expected!

**Comment by jliexpensify** [comment] 2023-10-26 00:08
Thanks Puneet - I'll just need to pay out the reporter first.

PAYMENT SUMMARY

- BUG REPORTER: @Nathan-Mulugeta $250

[NEW UPWORKS JOB](https://www.upwork.com/jobs/~0164c851ca388a4eda)

**Comment by yashchaddha** [comment] 2023-10-26 00:11
Hello all! I would like to contribute to this issue, can i be assigned?

**Comment by yashchaddha** [comment] 2023-10-26 00:15
Contributor details
Your Expensify account email: yash.chaddha1997@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/chaddhayash

**Comment by yashchaddha** [comment] 2023-10-26 00:16
Hello all! I would like to contribute to this issue, can i be assigned on this one?

**Comment by jliexpensify** [comment] 2023-10-26 00:28
@yashchaddha sorry, this issue is about to be closed.

**Comment by yashchaddha** [comment] 2023-10-26 01:02
Oh Okay no problem @jliexpensify , saw it today on upwork, hence applied for it.

Thankyou

**Comment by jliexpensify** [comment] 2023-10-26 01:05
Ah sorry for the confusion - I created an issue to pay out the bug reporter. Just waiting for him to accept and it'll be closed out!

**Comment by yashchaddha** [comment] 2023-10-26 01:06
No problem @jliexpensify

**Comment by Nathan-Mulugeta** [comment] 2023-10-26 04:51
Offer accepted @jliexpensify

**Comment by jliexpensify** [comment] 2023-10-26 04:57
Paid and job closed!

**Closed by jliexpensify** 2023-10-26 04:57 UTC
Labels: External, Engineering, Daily, Bug
