### ISSUE TITLE
[$500] Android - Task - Cursor position does not stay put when scrolling through long task description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31794] opened 2023-11-23 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to + > Assign task.
3. Enter title.
4. Enter a long description.
5. Scroll up the description.

## Expected Result:
The cursor position will not change as user only scrolls through the description instead of repositioning the cursor.

## Actual Result:
The cursor position follows wherever user scrolls in the description.
On other platforms (web, mweb, desktop and iOS app), the cursor position remains when scrolling through the description.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/eb1f55f0-a039-4f15-982d-63e43fc3b53d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bebae2cbd98034b6</li>
        <li>Upwork Job ID: 1727779879883001856</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by MoatazBadawy** [comment] 2023-11-23 23:58
We can set up a listener to save cursor position before the layout is updated. And Set up another one to restore cursor position after the layout is updated.

All the code will be used Included with the Edittext class.

**Comment by promisingcoder** [comment] 2023-11-24 00:08
Problem Statement:
The cursor in the TextInput component within the Composer loses its position when the user scrolls on Android devices.

Root Cause Analysis:
One potential cause is that the ScrollView containing the TextInput might be affecting the focus state of the input, or gesture handlers could be resetting the cursor position inadvertently.

Proposed Solution Example:
Here's an example of how you might modify the ScrollView and gesture handling within the Composer component to address the issue:

jsx



import React, { useRef, useState } from 'react';
import { ScrollView, TextInput, View, Keyboard } from 'react-native';

// ... other imports and setup ...

function Composer(props) {
    // ... existing state and refs ...

    // Ref for the ScrollView
    const scrollViewRef = useRef(null);

    // Handler for when the TextInput is focused
    const handleInputFocus = () => {
        // Ensure the ScrollView doesn't scroll, which can disrupt the TextInput's focus
        if (scrollViewRef.current) {
            scrollViewRef.current.setNativeProps({ scrollEnabled: false });
        }
    };

    // Handler for when the TextInput loses focus
    const handleInputBlur = () => {
        // Re-enable scrolling when the TextInput is not focused
        if (scrollViewRef.current) {
            scrollViewRef.current.setNativeProps({ scrollEnabled: true });
        }
    };

    // ... other handlers and logic ...

    return (
        <ScrollView
            ref={scrollViewRef}
            keyboardShouldPersistTaps="handled"
            // ... other ScrollView props ...
        >
            <View>
                {/* ... other components ... */}
                <TextInput
                    // ... existing TextInput props ...
                    onFocus={handleInputFocus}
                    onBlur={handleInputBlur}
                />
                {/* ... other components ... */}
            </View>
        </ScrollView>
    );
}

// ... rest of the component, propTypes, defaultProps, etc. ...

export default Composer;
In this example, the ScrollView has been given a ref so that its scrolling can be programmatically disabled when the TextInput is focused. This prevents the ScrollView from moving and potentially disrupting the cursor position. The keyboardShouldPersistTaps="handled" prop ensures that taps on the ScrollView when the keyboard is open do not dismiss the keyboard, which could also move the cursor.

Result:
With these changes, the TextInput should maintain its cursor position when the user interacts with other parts of the screen or when the ScrollView is touched. This solution assumes that the cursor issue is related to the ScrollView and gesture handling; if the problem persists, further investigation would be needed to identify other potential causes.

**Comment by promisingcoder** [comment] 2023-11-24 00:11
Problem Statement:
The cursor in the TextInput component within the Composer loses its position when the user scrolls on Android devices.

Root Cause Analysis:
One potential cause is that the ScrollView containing the TextInput might be affecting the focus state of the input, or gesture handlers could be resetting the cursor position inadvertently.

Proposed Solution :
Here's an example of how I  might modify the ScrollView and gesture handling within the Composer component to address the issue:

jsx



import React, { useRef, useState } from 'react';
import { ScrollView, TextInput, View, Keyboard } from 'react-native';

// ... other imports and setup ...

function Composer(props) {
    // ... existing state and refs ...

    // Ref for the ScrollView
    const scrollViewRef = useRef(null);

    // Handler for when the TextInput is focused
    const handleInputFocus = () => {
        // Ensure the ScrollView doesn't scroll, which can disrupt the TextInput's focus
        if (scrollViewRef.current) {
            scrollViewRef.current.setNativeProps({ scrollEnabled: false });
        }
    };

    // Handler for when the TextInput loses focus
    const handleInputBlur = () => {
        // Re-enable scrolling when the TextInput is not focused
        if (scrollViewRef.current) {
            scrollViewRef.current.setNativeProps({ scrollEnabled: true });
        }
    };

    // ... other handlers and logic ...

    return (
        <ScrollView
            ref={scrollViewRef}
            keyboardShouldPersistTaps="handled"
            // ... other ScrollView props ...
        >
            <View>
                {/* ... other components ... */}
                <TextInput
                    // ... existing TextInput props ...
                    onFocus={handleInputFocus}
                    onBlur={handleInputBlur}
                />
                {/* ... other components ... */}
            </View>
        </ScrollView>
    );
}

// ... rest of the component, propTypes, defaultProps, etc. ...

export default Composer;
In this , the ScrollView has been given a ref so that its scrolling can be programmatically disabled when the TextInput is focused. This prevents the ScrollView from moving and potentially disrupting the cursor position. The keyboardShouldPersistTaps="handled" prop ensures that taps on the ScrollView when the keyboard is open do not dismiss the keyboard, which could also move the cursor.

Result:
With these changes, the TextInput should maintain its cursor position when the user interacts with other parts of the screen or when the ScrollView is touched. This solution assumes that the cursor issue is related to the ScrollView and gesture handling; if the problem persists, further investigation would be needed to identify other potential causes.

**Comment by promisingcoder** [comment] 2023-11-24 00:13
Contributor details
Your Expensify account email: y95554393@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01169c49d59fd10b60

**Comment by MoatazBadawy** [comment] 2023-11-24 00:32
We can set up a listener to save cursor position before the layout is updated. And Set up another one to restore cursor position after the layout is updated.

All the code will be used Included with the Edittext class.

Contributor details
Your Expensify account email:
moataz.egy101@gmail.com
Upwork Profile Link:
https://www.upwork.com/freelancers/~01dfed707657fe25e7

**Comment by promisingcoder** [comment] 2023-11-24 00:36
Problem Statement:
Users have reported that the cursor within the TextInput component of the Composer does not stay fixed while scrolling on Android devices in the Expensify app.

Root Cause:
The root cause may involve the ScrollView that contains the TextInput component. It could be altering the focus state of the input or causing the cursor to reset due to scroll events. Additionally, gesture handlers within the app might be inadvertently affecting the cursor position.

Proposed Solution:
To mitigate this issue, I suggest modifying the ScrollView and gesture handling within the Composer component. The ScrollView should have a ref assigned to it, allowing for programmatic control over its scrolling capability. When the TextInput is focused, scrolling should be disabled to prevent any movement that could disrupt the cursor position. Conversely, when the TextInput loses focus, scrolling should be re-enabled. The keyboardShouldPersistTaps prop should be set to "handled" to ensure that tapping outside the TextInput while the keyboard is open does not dismiss the keyboard and affect the cursor.

Alternative Solutions:
As an optional step, other solutions that were explored include optimizing the state and prop management within the Composer component to prevent unnecessary re-renders, as well as updating the React Native framework to the latest stable version to take advantage of improvements to the TextInput component.

By implementing these changes, we aim to provide a stable and consistent cursor position within the TextInput component, improving the user experience on Android devices. Further testing will be conducted to ensure the effectiveness of the solution and to identify any additional improvements that may be required.

**Comment by promisingcoder** [comment] 2023-11-24 00:37
I just don't know how to write an effective proposal that fits the guidlines so I am going to leave the above two

**Comment by getusha** [comment] 2023-11-27 18:57
as @bernhardoj mentioned similar issue was closed before https://github.com/Expensify/App/issues/28940
@muttmuure i think we can close this one.

**Closed** 2023-12-01 12:20 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
