### ISSUE TITLE
[$250] Attachment – Cursor moves to beginning of password in PDF protected file when click on eye

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44599] opened 2024-06-28 09:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4678543
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Click on + and Add attachment
5. Select PDF protected file (do not click send)
6. Click on Enter the password
7. Enter text and click on the Eye to make your text visible

## Expected Result:
Cursor is at the end of the password in PDF protected file when click on the eye

## Actual Result:
Cursor moves to the beginning of the password in PDF protected file when click on the eye

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/218ff6e5-5c1c-4ba0-ab6e-f2d73bc951c3

PDf file 
[Password_protected_Test12345.pdf](https://github.com/user-attachments/files/16027367/Password_protected_Test12345.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb95943a6e16733e</li>
        <li>Upwork Job ID: 1806640970628869277</li>
        <li>Last Price Increase: 2024-06-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by izarutskaya** [comment] 2024-06-28 09:27
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-28 09:27
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-06-28 09:28
Production 

https://github.com/Expensify/App/assets/115492554/60ebe132-9bf6-403a-b3e3-1f25bb0a4fed

**Comment by Julesssss** [comment] 2024-06-28 10:01
Definitely not a blocker. I'm not sure we should even fix this to be honest.

**Comment by grogou** [comment] 2024-06-28 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicking on the eye icon in a PDF protected file, the cursor moves to the beginning of the password field.
### What is the root cause of that problem?
The root cause is `passwordHidden` state change that triggers `secureTextEntry` prop change.
### What changes do you think we should make in order to solve the problem?
We need to remember cursor position in `BaseTextInput` component  and `setSelectionRange` when  `togglePasswordVisibility` called.

**Comment by joekaufmanexpensify** [comment] 2024-06-28 15:21
Agreed with @Julesssss. The #vip-vsb project has been paused, so this doesn't feel worth prioritizing right now. This is a very niche bug. I'd be surprised if many/any customers experience this, and even if they do, there isn't really much impact. 

Going to close this for now, and we can revisit when/if we ever receive feedback from customers about this.

**Closed by joekaufmanexpensify** 2024-06-28 15:21 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
