### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Categorizing - Page blinks after selecting a category during categorization

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46063] opened 2024-07-23 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has no workspace
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Click Categorize it from the actionable whisper
5. Select any category

## Expected Result:
Page will not blink after selecting a category during categorization

## Actual Result:
Page blinks after selecting a category during categorization

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1f79d773-5c40-43e7-8b17-9bbcb368239e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f7b8664b135266</li>
        <li>Upwork Job ID: 1815855751043659627</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103288936</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-23 18:39
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment] 2024-07-23 19:34
The flicker is barely noticeable, not sure it's worth blocking on this.

There's also [this open issue](https://github.com/Expensify/App/issues/45834) about the chat view flickering - not sure it's related but could be.

**Comment by bernhardoj** [comment] 2024-07-24 03:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The page blinks when selecting category in categorize track expense flow.

### What is the root cause of that problem?
When we don't have a workspace and trying to categorize an expense, it will open a category page first. Selecting a category will:
1. Go back
2. Navigate to confirmation page

https://github.com/Expensify/App/blob/2bb1d002b9dfa7045a5ddbcb7ee99d4ae207948d/src/pages/iou/request/step/IOURequestStepCategory.tsx#L147-L151

We go back to close the category selector page. But because the category page is last RHP page at the moment, going back means closing the RHP modal. Then, it's followed by a navigation to a confirmation page, which is an RHP too, so both RHP overlay "conflicting" each other.

### What changes do you think we should make in order to solve the problem?

Instead of performing a go back and navigate action, we can just replace it with a REPLACE action, which will replace the category page with the confirmation page.
```
Navigation.goBack(ROUTES.MONEY_REQUEST_STEP_CONFIRMATION.getRoute(action, iouType, transactionID, report?.reportID ?? '-1'), true);
```
Using `goBack` with `forceFallback` to true will do a REPLACE action.

**Comment by bernhardoj** [comment] 2024-07-24 04:33
Hmm, can you explain more in what thing should we improve? There is 2 navigation action happen in this issue, are you suggesting that if there is a 'back' action followed by a 'navigate' action, then the navigation manager should convert them to 'replace' automatically instead of the developer needs to do it?

**Comment by eh2077** [comment] 2024-07-24 06:37
> are you suggesting that if there is a 'back' action followed by a 'navigate' action, then the navigation manager should convert them to 'replace' automatically instead of the developer needs to do it?

I think so. Does it make sense to you?

**Comment by bernhardoj** [comment] 2024-07-24 10:31
> I think so. Does it make sense to you?

One idea is to implement a batching mechanism for the `Navigation` lib, but I don't think we should always "convert" a goBack followed by navigate to a replace because if we have [A,B,C] in the stack and we use replace C -> A, then it will be [A,B,A]. We need to use goBack + navigate here so the C is popped by goBack and navigate will go to A popping all the screen along the way.

So, we need to apply it conditionally and I have updated my [proposal](https://github.com/Expensify/App/issues/46063#issuecomment-2246770239) for that case.

**Comment by roryabraham** [comment] 2024-07-26 01:17
> I don't think we should always "convert" a goBack followed by navigate to a replace because if we have [A,B,C] in the stack and we use replace C -> A, then it will be [A,B,A]

I don't think that would happen with @dominictb's proposal, because his proposal only converts "goBack + navigate" with "replace" in the case where the current screen is the only one in the RHP.

Or am I missing something?

**Comment by bernhardoj** [comment] 2024-07-26 03:14
> because his proposal only converts "goBack + navigate" with "replace" in the case where the current screen is the only one in the RHP

Yes, which is why we can't always convert "goBack + navigate" with "replace".

**Comment by eh2077** [comment] 2024-07-26 16:18
I'd say it's not that easy for me to select one of the two proposals above
- @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/46063#issuecomment-2246770239) was first - with correct RCA and a viable solution. During discussion, they came up a reusable solution though I believe we'll also get to it in PR.
- @dominictb 's [proposal](https://github.com/Expensify/App/issues/46063#issuecomment-2247149234) was posted later (during the discussion on the first proposal) and provides a more completed solution - they discussed detail differences of `go back and navigate` and `replace`.

--- 

If I have to choose one, then I'd vote for @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/46063#issuecomment-2246770239) because I think the correct RCA is important to understand the issue and reach a solution.

@roryabraham All yours.

🎀👀🎀 C+ reviewed

**Comment by roryabraham** [comment] 2024-07-27 07:30
Well this is a tough call, because both proposals are good and multiple contributors brought value to the issue:

- @bernhardoj was first to post the root cause
- @eh2077 provided feedback on the proposal
- @dominictb was first to create a generalized solution (building off of the root cause and the feedback that was posted)
- @bernhardoj iterated on his proposal _after_ @dominictb's proposal was posted (definitely a substantive edit, though it's not clear to me that the previous solution would've caused a regression)
- The final solutions (at the time I'm writing this) are not _exactly_ the same. @dominictb's conditionally uses replace if the screen is the first in the RHP. @bernhardoj conditionally uses replace if the screen is the first in the current navigator. This could mean that @bernhardoj's solution works in LHP or other modals, and not just the RHP. Though it's not clear if we have any use-cases where that would come into play in the app today.

I hope you both can appreciate that I feel like there's no clear answer for which proposal to select; I'm not a perfect judge, and I have to just do my best to consider what's most fair and best for the end-result. In this case I'm going to select @bernhardoj's proposal.

Thank you all for working together to come to a good solution. 🙇🏼

**Comment by bernhardoj** [comment] 2024-07-27 13:55
Thanks! 🙇 
PR is ready.

cc: @eh2077

**Comment by eh2077** [comment] 2024-08-07 14:44
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't think there's a PR that's responsible for this.**_ It's an edge use case we want to polish.
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: No
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes, it's actually a new feature we added though it's an edge case

### Regression test

Precondition:
- Account has no workspace

1. Go to self DM
2. Track a manual expense
3. Click Categorize it from the actionable whisper
4. Select any category
5. Verify the confirmation page opens without any blink
6. Press the Category field to edit it
7. Change to a different category
8. Press the back button
9. Verify the confirmation page closes

**Comment by jliexpensify** [comment] 2024-08-08 03:06
Payment Summary

- C: @bernhardoj $250 (New.Dot payment)
- C+: @eh2077 $250 [Upwork job](https://www.upwork.com/jobs/~01f0f7b8664b135266)

**Comment by bernhardoj** [comment] 2024-08-09 01:41
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-09 16:23
$250 approved for @bernhardoj

**Comment by jliexpensify** [comment] 2024-08-12 10:26
Apologies for the delay @eh2077 - paid and job closed!

**Closed by jliexpensify** 2024-08-12 10:26 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
