### ISSUE TITLE
[$1000] Web - Show error when numbers entered in debit card holder name field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23175] opened 2023-07-19 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to payments > debit card
2. Enter a numeric string in name's place eg: 111111
3. Fill the remaining details and hit enter

## Expected Result:
There should be an error on name field

## Actual Result:
No error on name field, `111111` passes the form validation

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dbc836aa-a606-4c75-9fa0-ca5c5961d784

**Expensify/Expensify Issue URL:**
**Issue reported by:** https://expensify.slack.com/archives/C049HHMV9SM/p1688813568570969
**Slack conversation:** @chiragxarora

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cce6a5c4931cb3b</li>
        <li>Upwork Job ID: 1683521297890430976</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>chiragxarora | Contributor | 25763253</li>
</ul></li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-07-24 16:55
Confirmed in slack that the expected behavior is to error when numbers are entered into name field. Triaging to external

**Comment by rushatgabhane** [comment] 2023-07-25 19:57
> And we can add a length condition using quantifiers too

let's not do anything with length because it is out of scope of this issue.

**Comment by rushatgabhane** [comment] 2023-07-25 20:04
> ^(?=.*[a-zA-ZÀ-ÿ])[a-zA-ZÀ-ÿ0-9 ]

oh lol, never would have thought about supporting latin letter too.
While we're at it, could we support the z latin letters too please `ž`?

@chiragxarora

**Comment by rushatgabhane** [comment] 2023-07-25 20:06
But we can talk about it in the PR, @chiragxarora please comment on the issue so a CE can assign you to this issue if they agree with your proposal.

https://github.com/Expensify/App/issues/23175#issuecomment-1642204650
C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2023-07-25 20:13
your proposal looks good

**Comment by robertjchen** [comment] 2023-07-26 12:36
These get printed on physically-issued cards, so I'll need to confirm if the character set is supported when printing 🤔

**Comment by robertjchen** [comment] 2023-07-26 12:45
thanks, but this depends on the card vendor- we don't use the same one Amazon does 😄

**Comment by robertjchen** [comment] 2023-07-26 12:46
Based on the documentation from our vendor, we should be good to go here 👍

**Comment by StefStavri** [comment] 2023-07-27 13:19
Hi @chiragxarora , lets keep it simple and go with:

`Name can only include letters.`

Thanks

**Comment by StefStavri** [comment] 2023-07-27 15:03
Hey

The second scenario is also invalid and we do not want to allow numbers in the name field.

**Comment by robertjchen** [comment] 2023-08-09 19:18
Looks like this went out on production, what are the next steps here?

**Comment by sonialiap** [comment] 2023-08-25 10:50
Sorry for the delay, just got back from OOO, working through the payments now!

**Comment by sonialiap** [comment] 2023-08-25 10:58
Payments:
[No time bonus](https://github.com/Expensify/App/issues/23175#issuecomment-1664068670)
- @chiragxarora report + fix $1250 (paid in upwork)
- @rushatgabhane review $1000 (please request in newdot)

**Closed** 2023-08-25 10:59 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by sonialiap** [comment] 2023-08-25 12:12
I agree, time bonus is applicable because the merge delay was on our end, the C+ approval was within 3 business days
I've [updated my comment](https://github.com/Expensify/App/issues/23175#issuecomment-1693179120) to show correct numbers

@chiragxarora offer sent for the bonus
@rushatgabhane please request $1500 for this issue

**Comment by JmillsExpensify** [comment] 2023-10-05 20:15
$1,500 payment approved for @rushatgabhane based on BZ summary.
