### ISSUE TITLE
[HOLD][$250]  Task - App scrolls to the top after returning from task report when there is IOU & task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40085] opened 2024-04-11 07:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new chat (no chat history).
3. Create an IOU request.
4. Create a task.
5. Click on the task.
6. Click on the header subtitle in task report.

## Expected Result:
App will adjust the chat to show the highlighted task.

## Actual Result:
App scrolls up to the top and it is not revealing the task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/09784a92-859c-4f92-9514-c6c2474d1927

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7000bd5e3685039</li>
        <li>Upwork Job ID: 1778383845658161152</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-11 07:56
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-11 07:56
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-11 07:57
Production 


https://github.com/Expensify/App/assets/115492554/ac71c808-3fe7-48a0-8eb8-6e74f2f1439a

**Comment by techievivek** [comment] 2024-04-11 08:50
Taking a look.

**Comment by techievivek** [comment] 2024-04-11 10:20
Ok, I am able to reproduce this bug. Seems like we have updated the URL signature when we click on the link in task view page.

**Comment by techievivek** [comment] 2024-04-11 10:21
It now has reportActionID as well?

**Comment by techievivek** [comment] 2024-04-11 11:25
Going to add external label.

**Comment by MingyangJin** [comment] 2024-04-12 01:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is the scrolling logic of report Item is not correct in certain cases such as when it's linked from an action item.
### What is the root cause of that problem?
The logic here (line 313) is incorrectly return instead of scrolling to the desired item
https://github.com/Expensify/App/blob/fa2bfb29dbcdc84c369c77cfcadda0a8a7a577e7/src/pages/home/report/ReportActionsList.tsx#L311-L319
### What changes do you think we should make in order to solve the problem?
We should find the matched item (if there's any) so that it's automatically scrolled to the matched item.
https://github.com/Expensify/App/blob/fa2bfb29dbcdc84c369c77cfcadda0a8a7a577e7/src/pages/home/report/ReportActionsList.tsx#L311-L319

### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by MingyangJin** [comment] 2024-04-12 01:08
Contributor details
Your Expensify account email: jinmingyang94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0180847d570f9ce9d4

**Comment by MingyangJin** [comment] 2024-04-12 01:11
Contributor details
Your Expensify account email: [jinmingyang94@gmail.com](mailto:jinmingyang94@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0180847d570f9ce9d4

**Comment by MingyangJin** [comment] 2024-04-12 01:12
Contributor details
Your Expensify account email: jinmingyang94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0180847d570f9ce9d4

**Comment by shahinyan11** [comment] 2024-04-12 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - App scrolls to the top after returning from task report when there is IOU & task
### What is the root cause of that problem?
Lets call the new chat as `A` report and the task as `B` report.
When we navigate to `B` report from  `A` the `A` report  does not removed from navigation stack and continues re-render related updating `Onyx` 
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/b59ae94dbbfac2d3b5da8df5c4dc6fbdb7785c6b/src/pages/home/ReportScreen.tsx#L253C13-L253C43) like following `if (!sortedAllReportActions.length || !isFocused)`  will solve the problem 

### What alternative solutions did you explore? (Optional)

**Comment by QichenZhu** [comment] 2024-04-12 16:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After returning from a task report, the app sometimes scrolls to the top if the task was positioned at the bottom.

### What is the root cause of that problem?
The app fails to identify the task as the first visible subview when it's positioned at the bottom of the scroll view.

https://github.com/Expensify/App/blob/0665fa4fc6f9edc70c91728277374de7021b49a4/src/components/FlatList/index.tsx#L80-L85

During the bug, both the `subviewOffset` and `scrollOffset` are `0`. The loop mistakenly considers the next view (`$footer`), which is positioned above the task, as the first visible subview.

In the subsequent code, the app adjusts the scroll offset based on the `$footer`'s previous and new position, now at the top of the `InvertedFlatList`.

https://github.com/Expensify/App/blob/0665fa4fc6f9edc70c91728277374de7021b49a4/src/components/FlatList/index.tsx#L103-L107

### What changes do you think we should make in order to solve the problem?
To handle cases where both the `subviewOffset` and `scrollOffset` are `0`, a possible fix is changing the operator from `>` to `>=`. I have tested it locally.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by QichenZhu** [comment] 2024-04-13 09:36
Contributor details
Your Expensify account email: zhuqc9@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0179e125e16ec756de

**Comment by lschurr** [comment] 2024-04-15 15:26
Looks like we have some proposals that need review. Can you take care of that @shubham1206agra?

**Comment by shahinyan11** [comment] 2024-04-16 09:22
> @shahinyan11 Can you tell me what do you want to update?

@shubham1206agra Oh I am sorry. I updated proposal and added change the change that I would introduce

**Comment by QichenZhu** [comment] 2024-04-17 22:54
It seems that this bug isn't reproducible on the latest main branch. However, the underlying cause of the bug I mentioned in my [proposal](https://github.com/Expensify/App/issues/40085#issuecomment-2052086764) still exists. Although it no longer causes the screen to scroll to the top, it now causes the screen to scroll to the second last message after hovering the mouse over it.

https://github.com/Expensify/App/assets/57348009/76d46881-9938-45d6-87ed-1f1737624f56

**Comment by lschurr** [comment] 2024-04-18 16:02
Can you take another look @shubham1206agra?

**Comment by lschurr** [comment] 2024-04-19 14:59
Bumping this @shubham1206agra

**Comment by QichenZhu** [comment] 2024-04-19 17:08
> @QichenZhu Can you address why this was fixed by your solution?

@shubham1206agra In the `prepareForMaintainVisibleContentPosition` function, when a subview is at the very bottom, touching the bottom edge, it's not considered visible, as shown on the left side of the image below. Only when a subview is positioned above the bottom, even by just 1 pixel, it's considered visible.

My solution is to regard both cases as visible, since I can't see a reason why not. This allows the function to correctly find the first visible subview.

<img width="1060" alt="Screenshot 2024-04-20 at 4 47 21 AM" src="https://github.com/Expensify/App/assets/57348009/117b8ca1-ee71-42bf-a2b4-129eab5f2f33">

**Comment by techievivek** [comment] 2024-04-22 04:12
Holding it for now, @perunt, can you please comment on this GH so I can assign the GH to you? Thanks.

**Comment by perunt** [comment] 2024-04-22 09:05
Hey guys! I'm back. 
I would be happy to pick it up right after the `inline `autosuggestion` task.

**Comment by lschurr** [comment] 2024-04-24 19:16
Assigned to you @perunt :)

**Comment by lschurr** [comment] 2024-04-26 23:31
I think we're still holding on this one - Is that correct @perunt?

**Comment by lschurr** [comment] 2024-05-06 14:59
On hold

**Comment by lschurr** [comment] 2024-05-14 20:03
On hold.

**Comment by lschurr** [comment] 2024-05-24 15:37
Hold.

**Comment by lschurr** [comment] 2024-06-03 15:11
Hold

**Comment by lschurr** [comment] 2024-06-11 22:26
On hold.

**Comment by lschurr** [comment] 2024-06-20 20:24
On hold.

**Comment by lschurr** [comment] 2024-07-01 15:35
On hold.

**Comment by lschurr** [comment] 2024-07-09 19:38
On hold

**Comment by lschurr** [comment] 2024-07-18 21:35
Hold

**Comment by techievivek** [comment] 2024-07-29 12:23
@perunt do you have any updates for this GH? Shall we still HOLD this?

**Comment by perunt** [comment] 2024-07-30 13:19
hey guys! Thanks for mentioning me
I've fixed a similar bug recently. Can we retest it?
What I have now:

https://github.com/user-attachments/assets/daf50432-f526-40a8-b564-a6995da23413

**Comment by techievivek** [comment] 2024-07-30 13:39
Requested a re-test here https://expensify.slack.com/archives/C9YU7BX5M/p1722346767146919, thanks.

**Comment by m-natarajan** [comment] 2024-07-30 15:32
Not reproducible by the tester.

https://github.com/user-attachments/assets/03cf1e04-4012-4026-83e5-5feebf7fca54

**Comment by techievivek** [comment] 2024-07-30 16:03
Thanks for confirming, going to close this now.

**Closed by techievivek** 2024-07-30 16:03 UTC
Labels: External, Engineering, Weekly, Bug
