### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Pressing enter key on the Description page adds the user to the Who was There page.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19450] opened 2023-05-23 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open App
2. Press FAB > New group > add more than two users > Press Create group
3. Go to the created group
4. Press + from composer > Split bill > Add amount > deselect one or two users from `Who was there?` list.
5. Press Description and add description and press enter
6. Observe the `Who was there?` list

## Expected Result:
Pressing enter on the Description page should not have to select the user on `Who was there?` list.
## Actual Result:
Pressing enter on the Description page is adding a user to `Who was there?` list.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/936f4df9-7d83-4f84-9232-9f4cba4aee94

https://github.com/Expensify/App/assets/43996225/08f093b1-7a2f-4cee-97f9-6c3caf71c37e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684511132545629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea1ea807e254fd18</li>
        <li>Upwork Job ID: 1661337679625768960</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-05-23 19:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter key on the Description page adds the user to the Who was There list

### What is the root cause of that problem?
Issue is happening because we have a listener on the [BaseOptionsSelector](https://github.com/Expensify/App/blob/main/src/components/OptionsSelector/BaseOptionsSelector.js) component that listens enter(`enterConfig.shortcutKey`) key press,

https://github.com/Expensify/App/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/components/OptionsSelector/BaseOptionsSelector.js#L56-L58

And when we navigate to the next screen then BaseOptionsSelector is not focused and it still listens to the enter press event

### What changes do you think we should make in order to solve the problem?
On BaseOptionsSelector Component we need to  add `withNavigationFocus` and then here on lister `unsubscribeEnter` we need to add a condition that if screen is not focused then do nothing and return early

https://github.com/Expensify/App/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/components/OptionsSelector/BaseOptionsSelector.js#L60-L62

need to adjust conditions like this

`if (!focusedOption || !this.props.isFocused)`

**note: This same issue is happening at the Workspace member page, Go to any workspace > Manage members > Invite > Select few users > Press Next then on Add message page press enter It will add 1 extra user than you have selected**

<details>
  <summary>Result</summary>
  

https://github.com/Expensify/App/assets/35371050/d9512215-bbad-4af1-a643-b270461ac8aa


</details>



### What alternative solutions did you explore? (Optional)
none

**Comment by sonialiap** [comment] 2023-05-24 11:45
Reproducible 👍 

I found that pressing `return/enter` checks the box on one previously unchecked user in the `who was there` list. But if I click `save`, user is not added

**Comment by Santhosh-Sellavel** [comment] 2023-05-25 21:35
[Proposal](https://github.com/Expensify/App/issues/19450#issuecomment-1559997907) looks good to me seems straight forward, let me know your thoughts @arosiclair

**Comment by sonialiap** [comment] 2023-05-29 13:17
@arosiclair looks like we got a proposal, what do you think?

**Comment by arosiclair** [comment] 2023-05-30 14:30
Sorry was OOO. Proposal LGTM too!

**Comment by jayeshmangwani** [comment] 2023-05-30 16:09
[PR](https://github.com/Expensify/App/pull/19824) is ready for review
@arosiclair @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-06-12 19:15
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/16919
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/16919#issuecomment-1587931411
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Should have been caught based on checklist, while testing/reviewing
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug.
> * [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@sonialiap] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2023-06-12 19:17
### Regression Test Steps

1. Open the App
2. Press FAB > New group > add more than two users > Press Create group
3. Go to the created group
4. Press + from composer > Split bill > Add amount > deselect one or two users from Who was there? list.
5. Press Description and add a description and press enter
6. Verify the selection user remain unchanged. i.e. only one user is selected as it was after step 4.

👍 or 👎

**Comment by sonialiap** [comment] 2023-06-15 15:40
Nice, thanks for the regression steps Santhosh. Working on issuing payments now

**Comment by sonialiap** [comment] 2023-06-15 15:47
@jayeshmangwani offer sent for reporting issue + fix (bonus will be added for fast fix)
@Santhosh-Sellavel offer set for for review (bonus will be added for fast fix)

**Comment by jayeshmangwani** [comment] 2023-06-15 17:30
@sonialiap Offer accepted, thanks

**Comment by sonialiap** [comment] 2023-06-16 09:21
Both payments completed, regression test issue opened. Closing ✅

**Closed by sonialiap** 2023-06-16 09:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
