### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] connect to Quickbooks Dekstop on OldDot, the admin room in newdot shows incomplete system messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47830] opened 2024-08-22 02:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724242725049269

## Action Performed:
1. Login with same account in OD and ND
2. Go to workspace in OD
3. Connect to  Quickbooks Dekstop
4. Go to # admin room of the same workspace
## Expected Result:
There shouldn't be any incomplete message
## Actual Result:
“removed the connection to message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_0925](https://github.com/user-attachments/assets/607322e2-098f-479a-aa06-e37c6755d9ff)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833242408324478296</li>
        <li>Upwork Job ID: 1833242408324478296</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 104119799</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2024-09-04 14:45
@bfitzexpensify confirming this is a bug, yeah?

**Comment by bfitzexpensify** [comment] 2024-09-04 14:52
Yeah, I agree with the expected vs actual result differing, and this therefore being a bug

**Comment by trjExpensify** [comment] 2024-09-10 01:12
Support for QBD is being built in #wave-control, moving.

**Comment by abdulrahuman5196** [comment] 2024-09-16 16:02
Hi, Will check in my morning

**Comment by abdulrahuman5196** [comment] 2024-09-23 16:18
Checking now

**Comment by abdulrahuman5196** [comment] 2024-09-24 17:55
Hi @dylanexpensify I am having my plate full at the moment and I don't want to delay this issue. Kindly reassign the label for a different C+. Unassigning myself.

**Comment by DylanDylann** [comment] 2024-09-25 01:45
I am happy to take over this issue as C+ contributor

**Comment by dylanexpensify** [comment] 2024-09-25 10:07
TY @DylanDylann!

**Comment by DylanDylann** [comment] 2024-09-25 10:53
@daledah Why doesn't this bug happen when disconnecting the connection on the new dot?

**Comment by DylanDylann** [comment] 2024-09-26 14:50
@daledah's [proposal](https://github.com/Expensify/App/issues/47830#issuecomment-2303576684) looks good to me. Please add translation to the message in the PR phase.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-09-27 08:32
@daledah Let's use : "Conexión eliminada a"

I will ask someone to confirm on Slack

**Comment by dylanexpensify** [comment] 2024-10-04 09:40
Coming up!

**Comment by dylanexpensify** [comment] 2024-10-07 12:22
Coming up!

**Comment by dylanexpensify** [comment] 2024-10-14 14:21
Payment summary:

Contributor: @daledah $250 
Contributor+: @DylanDylann $250 

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-10-14 14:23
@daledah please apply!

**Comment by dylanexpensify** [comment] 2024-10-14 14:23
@DylanDylann paid!

**Comment by dylanexpensify** [comment] 2024-10-16 18:32
@daledah offer sent!

**Comment by DylanDylann** [comment] 2024-10-17 02:22
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **This change seem like a new feature, not a bug*
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. Login with the same account in OD and ND
2. Go to workspace in OD
3. Connect to Quickbooks Dekstop
4. In OD, disconnect from Quickbooks Desktop
5. In ND, navigate to WS #admins chat
6. Verify that: The Report Action Item, Sidebar Text shows the correct message
7. Right click on the message, click "Copy to Clipboard" and paste.
8. Verify that: Pasted text shows the correct message

Do we agree 👍 or 👎

**Comment by dylanexpensify** [comment] 2024-10-17 17:25
Done!

**Closed by dylanexpensify** 2024-10-17 17:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
