### ISSUE TITLE
[$250] Chat - After tapping space key multiple times, tapping cross button doesn't remove text entered

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53355] opened 2024-12-01 12:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0. 69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Enter any text filling 1st line (if entered text in 2nd line -delete it)
3. Keeping cursor at end of first line, tap space key multiple times
4. Tap cross ❌ close button
5. Note last character is not removed
6. Tap multiple times, cross ❌ button
7. Note note user can remove characters entered

## Expected Result:
After tapping space key multiple times, tapping cross button must remove entered characters on first tap.

## Actual Result:
After tapping space key multiple times, tapping cross button doesn't remove entered characters on first tap.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ee05861b-c7ef-48f4-b7f8-a42036b01016
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863346169204872247</li>
        <li>Upwork Job ID: 1863346169204872247</li>
        <li>Last Price Increase: 2024-12-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by jliexpensify** [comment] 2024-12-01 22:15
I can repro in 69-1 Android Chrome (Pixel 7)

**Comment by mananjadhav** [comment] 2024-12-02 22:42
Checking the code and proposal from @M00rish. But a quick question, the file you've linked is `web/MarkdownTextInput.css`. It might work on web or mobile web.  How does that translate to Android native?

Also tagging @Expensify/design if we'd be keen on updating this to `break-spaces;`

**Comment by shawnborton** [comment] 2024-12-03 00:43
Hmm that seems reasonable to me, but can we check how other applications (WhatsApp, Slack, etc) handle this scenario as well? Just want to get a quick gut check on what is expected.

**Comment by jliexpensify** [comment] 2024-12-03 01:12
WhatsApp - first tap = full stop. Multiple taps = multiple spaces

Slack - multiple taps = multiple spaces (no full stop)

**Comment by shawnborton** [comment] 2024-12-03 13:35
I just checked Slack and it seems like Slack behaves the same way our app currently does regarding spaces. 

Is there actually a good use case where we want to allow this kind of behavior? Or should we just close this out?

**Comment by mananjadhav** [comment] 2024-12-04 18:41
> WhatsApp - first tap = full stop. Multiple taps = multiple spaces

It is an edge case but yeah I checked a few apps on iOS. All of them have this ^ behavior for me. Whatsapp, Slack, etc.

**Comment by jliexpensify** [comment] 2024-12-04 22:32
@shawnborton @mananjadhav I personally think that Whatsapp behaviour makes the most sense: I think the bug here is that ND effectively "bricks" the chat when tapping multiple spaces which isn't ideal.

**Comment by mananjadhav** [comment] 2024-12-05 12:12
> @shawnborton @mananjadhav I personally think that Whatsapp behaviour makes the most sense: I think the bug here is that ND effectively "bricks" the chat when tapping multiple spaces which isn't ideal.

@jliexpensify I think you mean `WhatsApp - first tap = full stop. Multiple taps = multiple spaces` right? I agree as well. @shawnborton wdyt?

**Comment by shawnborton** [comment] 2024-12-05 20:12
Hmm this is what I am seeing on WhatsApp desktop at least:

https://github.com/user-attachments/assets/be4d0ff9-f8cf-42fa-a539-ea64a9ab06d4

Which seems to be the same thing that we have, based on the video above. So again, part of me thinks we just close this out and do nothing here. cc @Expensify/design for further thoughts though!

**Comment by mananjadhav** [comment] 2024-12-05 20:18
I think the issue is more on the mobile platforms.

**Comment by shawnborton** [comment] 2024-12-05 20:26
Why though? I would think we'd want this to behave the same everywhere?

**Comment by dannymcclain** [comment] 2024-12-05 20:26
I'm seeing the exact same behavior in Slack as well (on mobile). So I think I'm also leaning towards just closing this one out.


https://github.com/user-attachments/assets/96d55e50-8b78-4fb5-9826-b8398b536666


https://github.com/user-attachments/assets/dd5d34e0-790e-4683-af01-f2143d9f0c45

**Comment by mananjadhav** [comment] 2024-12-05 20:30
> Why though? I would think we'd want this to behave the same everywhere?

I am not 100% sure but AFAIK it's because on mobile devices we have an auto-correct which will try to correct the typed word and add a period.

**Comment by shawnborton** [comment] 2024-12-05 20:33
I don't think that's what the original bug is reporting though. 

Either way, @jliexpensify I would say we should go ahead and close this out. Let's see if @dubielzyk-expensify has any strong feelings but my hunch is that we can just :donothing: here.

**Comment by jliexpensify** [comment] 2024-12-05 22:21
Thanks Shawn and Danny for weighing in! Let's just close this out.

**Closed by jliexpensify** 2024-12-05 22:21 UTC
Labels: External, Daily, Help Wanted, Bug
