### ISSUE TITLE
[C+ checklist needs completion] [$1000] Upon checking the task checkbox, the reply is only displayed in the first task report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25548] opened 2023-08-20 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group chat and add userB and a other user.
2. Navigate to the "Assign task" section of group chat.
3. Create a task by providing a title.
4. Click on the "Assignee" field and select "UserB."
5. Reopen the "Assignee" field and choose a different user.
6. Once again, select "UserB" in the "Assignee" field.
7. Go to "UserB's" chat.
8. Multiple tasks will be visible.
9. Check the task checkbox.
10. Observation "1: reply" is only visible in the first task report.
11. Now refresh the page to see others
## Expected Result: 
The reply should be visible in all task reports when the task checkbox is checked and should not require to refresh the page
## Actual Result: 
Upon checking the task checkbox, the reply is only displayed in the first task report. To view the reply in other task reports, the page needs to be refreshed
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/26825ac7-0d06-4874-a94b-624fe7daa83f

https://github.com/Expensify/App/assets/43996225/b11a12c2-311a-4100-9984-569d71fad317

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazHussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691620197248549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111e3d81ac091a630</li>
        <li>Upwork Job ID: 1694248696382259200</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-08-20 18:13
# Proposal

## Please re-state the problem
Upon checking the task checkbox, the reply is only displayed in the first task report

## What is the root cause of this problem?
The root cause is that when opening and closing a task, we update the parent `reportActions` for that task. In the current code, we only consider for two parent `reportActions`:
- Share destination `reportAction` of task
- Assignee report `reportAction` of task

But in this case, we are seeing that assignee report has more than one parent `reportActions` therefore, we need some code to update all the parent `reportActions` as well.
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/actions/Task.js#L272-L281

In fact, this recent PR: https://github.com/Expensify/App/pull/24110, had added the updation for `assignee` report, but this PR failed to include the case of there existing more than one parent `reportActions`.

## What changes do you think we should make to solve this problem?
So we just need to include the multiple parent report actions and we can do that as follows:
1. We need to change the function `getParentReportActionInReport` to `getParentReportActionsInReport` to include all the parent report actions instead of just one. So, we can just change the `_.find()` to `_.filter()` And since this function was also just introduced in the fore-mentioned PR, there is only a single invocation of this function, so other areas will not be affected.
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/ReportActionsUtils.js#L136-L138 
Like this:
```js
function getParentReportActionsInReport(childReportID, parentReportID) {
    return _.filter(allReportActions[parentReportID], (reportAction) => reportAction && `${reportAction.childReportID}` === `${childReportID}`);
}
```


2. We need to change the function `getTaskParentReportActionIDInAssigneeReport` to `getTaskParentReportActionIDsInAssigneeReport`. So, instead of just getting `reportActionID` of the `parentReportAction`, we can map the `parentReportActions` and get the `reportActionID` of each `reportAction`. Then, we can return an array for `reportActionIDs` instead of just `reportActionID`.
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/ReportUtils.js#L2946-L2961
Like this:
```js
function getTaskParentReportActionIDsInAssigneeReport(taskReport) {
    const assigneeChatReportID = lodashGet(getChatByParticipants(isTaskAssignee(taskReport) ? [taskReport.ownerAccountID] : [taskReport.managerID]), 'reportID');
    if (!assigneeChatReportID || assigneeChatReportID === taskReport.parentReportID) {
        return {};
    }

    const clonedParentReportActionIDs = _.map(ReportActionsUtils.getParentReportActionsInReport(taskReport.reportID, assigneeChatReportID), (a) => lodashGet(a, 'reportActionID'));
    if (!clonedParentReportActionIDs) {
        return {};
    }

    return {
        reportID: assigneeChatReportID,
        reportActionIDs: clonedParentReportActionIDs,
    };
}
```

3. Now, we can change the `Task.js` function `completeTask` to manage the array of `parentReportIDs`:
https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/libs/actions/Task.js#L281-L293
Like this:
```js
const assigneeReportActions = ReportUtils.getTaskParentReportActionIDsInAssigneeReport(taskReport);
    if (!_.isEmpty(assigneeReportActions)) {
        for (const reportActionID of assigneeReportActions.reportActionIDs) {
            const optimisticDataForClonedParentReportAction = ReportUtils.getOptimisticDataForParentReportAction(
                taskReportID,
                completedTaskReportAction.created,
                CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
                assigneeReportActions.reportID,
                reportActionID,
            );
            if (!_.isEmpty(optimisticDataForClonedParentReportAction)) {
                optimisticData.push(optimisticDataForClonedParentReportAction);
            }
        }
    }
```
The same logic can be applied for `reopenTask` function as well. 

**Note:** This is just a general guide for the approach, for things like the return type of `getTaskParentReportActionIDsInAssigneeReport`, we can either return a structure like:
```js
[{reportID: 123, reportActionID: 000}, {reportID: 123, reportActionID: 111}];
```
But since `reportID` is the same in each element, I chose to go with:
```js
{reportID: 123, reportActionIDs: [000, 111]}
```
But the choice can be either way!

## What alternatives did you explore? (Optional)

**Comment by greg-schroeder** [comment] 2023-08-23 07:22
This is not overdue Melv

**Comment by HassanNaqvi1999** [comment] 2023-08-23 13:45
I think I've figured it out, just need to verify it @MelvinBot. Will take a couple of mins

**Comment by HassanNaqvi1999** [comment] 2023-08-23 14:05
assign me melv

**Comment by greg-schroeder** [comment] 2023-08-25 15:20
Proposal review underway

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 15:36
@greg-schroeder I will not be able to get this until Monday feel free to resign if urgent, thanks!

**Comment by greg-schroeder** [comment] 2023-08-28 10:10
That's okay, let's just take care of it ASAP this week!

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 21:16
Thanks, @greg-schroeder.

I've checked @esh-g's proposal should do the job, but will confirm again after more investigation, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 21:44
@thienlnam is this a valid bug?

**Comment by thienlnam** [comment] 2023-08-29 21:51
Yeah this looks valid - minor inconsistency but can be fixed.

Though we should also check if the count is updated when someone else adds a comment in the task report on the second linked task. So basically

1. Follow the steps in actioned performed
2. Have a different user comment in that task
3. See if the count is updated when viewing all chats like that

If that works, then we can progress with this but otherwise might be a BE issue as well

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 19:14
@thienlnam I'm confused here as to why we are adding two different messages for the same task in a chat?

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 19:16
Also, it doesn't make sense to update all the threads. IMO Updating the latest thread should be enough

**Comment by thienlnam** [comment] 2023-08-30 20:44
> @thienlnam I'm confused here, why we are adding two different messages for the same task in a chat.

When you're assigned a task, you get a task message indicating that you were assigned to a task.
Suppose in a scenario like this
1. You are assigned a task
2. You end up going OOO so the task is reassigned to someone else to take care of it while you're gone
3. You come back and get re-assigned the task

In this specific scenario, it might look odd that the two task messages are right above each other but typically you'd have other conversation in that chat and so when you get assigned again, the task view will get shown to you.

> Also, it doesn't make sense to update all the threads. IMO Updating the latest thread should be enough

All the threads should be linked to the exact same report and so should all have the same information. This should be happening already

**Comment by Santhosh-Sellavel** [comment] 2023-09-04 01:04
@esh-g Can you share the code for `isTaskAssignee`?

**Comment by esh-g** [comment] 2023-09-04 04:12
@Santhosh-Sellavel `isTaskAssignee` method was renamed to `isReportManager` recently. But upon, further checking, I am noticing that the backend seems to no longer recognise opening and reopening task as a reply to the task report. Please check once..

https://github.com/Expensify/App/assets/77237602/440c3c8f-0b7d-4c92-8d8b-0024f1e3d8cb

**Comment by esh-g** [comment] 2023-09-04 04:20
Here is an issue that was reported about this: https://expensify.slack.com/archives/C049HHMV9SM/p1693143382082049

**Comment by greg-schroeder** [comment] 2023-09-05 21:09
Yes, doing

**Comment by eVoloshchak** [comment] 2023-09-10 14:55
Reviewing proposals shortly, need to get up to speed with all the discussion

**Comment by greg-schroeder** [comment] 2023-09-12 14:18
Thanks @eVoloshchak!

**Comment by eVoloshchak** [comment] 2023-09-14 16:35
@esh-g's [proposal](https://github.com/Expensify/App/issues/25548#issuecomment-1685357377) looks good to me, I think we can proceed with the PR

> Though we should also check if the count is updated when someone else adds a comment in the task report on the second linked task. If that works, then we can progress with this but otherwise might be a BE issue as well

Looks like it was decided [here](https://github.com/Expensify/App/issues/21761#issuecomment-1715754739) to ignore issues with live updating
> IIRC, there had been a discussion about not really considering these "live updating" issues bugs in Slack.

@thienlnam, that applies to [this](https://github.com/Expensify/App/issues/25548#issuecomment-1698193080) comment too, is that correct?


🎀👀🎀 C+ reviewed!

**Comment by flodnv** [comment] 2023-09-15 02:21
@thienlnam assigning you since you're involved since it's related to tasks

**Comment by esh-g** [comment] 2023-09-18 09:30
Waiting for assignment... I have the branch made

**Comment by greg-schroeder** [comment] 2023-09-18 10:42
@thienlnam do you want to approve https://github.com/Expensify/App/issues/25548#issuecomment-1719784298?

**Comment by thienlnam** [comment] 2023-09-22 03:42
The proposal looks good, but also seems like it is a FE solution. This might be fine - but if you sign back out and log back in do you see the replies on both task reports? Just want to make sure this solution doesn't just solve it for Onyx but also will persist

**Comment by esh-g** [comment] 2023-09-22 12:39
@thienlnam You don't even need to sign out.. If you check the video attachment closely, we can see it gets updated for every task even on reloading the page. So, this is taking effect on the backend as well.

**Comment by thienlnam** [comment] 2023-09-25 02:04
Yes, but signing out clears the onyx data locally so we can verify that the reply is fetched on a fresh log in. I'll go ahead and assign as we can verify this in the PR as well

**Comment by greg-schroeder** [comment] 2023-09-25 07:18
Thanks @thienlnam

**Comment by esh-g** [comment] 2023-09-25 10:28
@thienlnam I tested this and yes you seem to be correct... Back-end does remove the replies for a task when signing in again. Sorry I misunderstood earlier. So, this might need some back-end work as well...

**Comment by esh-g** [comment] 2023-09-25 10:45
@thienlnam Upon further inspection, I don't think that the closing/reopening of a task is actually adding a reply on the backend of any task. This issue was first reported when opening/closing was counted as a reply but it seems we don't do that anymore... So, I think the best approach would be to just remove the logic that adds the reply in `assignee` report. Since, you already assigned me, I going with this approach in the PR... Please let me know if you agree.

https://github.com/Expensify/App/assets/77237602/eb40086f-c94f-416f-b0b6-566a068cef96

cc @eVoloshchak

**Comment by esh-g** [comment] 2023-09-25 11:00
@eVoloshchak I have updated my [proposal](https://github.com/Expensify/App/issues/25548#issuecomment-1685357377) to reflect the changes mentioned [here](https://github.com/Expensify/App/issues/25548#issuecomment-1733416885). Please let me know your thoughts so that I can raise the PR as soon as possible.. 😇

**Comment by esh-g** [comment] 2023-09-26 13:55
Gentle bump @eVoloshchak I am already assigned so, I hope we can get this done quickly.. Thanks

**Comment by eVoloshchak** [comment] 2023-09-26 19:46
@esh-g, I agree with the updated approach, let's spin up the PR!

**Comment by esh-g** [comment] 2023-09-27 01:30
Great @eVoloshchak, I have marked the [PR](https://github.com/Expensify/App/pull/28128) ready for review!

**Comment by thienlnam** [comment] 2023-09-27 02:10
> I don't think that the closing/reopening of a task is actually adding a reply on the backend of any task

Are you proposing removing the message entirely? There is definitely a reportAction that is added when a task is completed or mark as incompleted

Let's take a step back for a second

**Comment by thienlnam** [comment] 2023-09-27 02:16
<img width="1135" alt="Screenshot 2023-09-27 at 10 15 35 AM" src="https://github.com/Expensify/App/assets/30609178/2f81aeff-22f7-4efa-99d1-0b658bbf117b">

I just tested this in production and it works as intended - the system messages exist and persist even if you log out / log back in

**Comment by greg-schroeder** [comment] 2023-09-27 05:20
Hmmm. So what should be the next step here?

**Comment by thienlnam** [comment] 2023-09-27 06:48
We should be re-evaluating a proposal that address the issue without removing the system messages

**Comment by esh-g** [comment] 2023-09-27 09:40
@thienlnam I'm not saying that the system messages don't exist.. I'm saying that they are not counted as a reply to the task

**Comment by esh-g** [comment] 2023-09-27 11:06
@thienlnam Please see the video here of the app after applying the solution. You can see that the system messages are present they just aren't counted as replies. Even if you go to the share destination and not the assignee report and then close/reopen a task, the message is not added as a reply. Let me know if you see any concerns in the video:

https://github.com/Expensify/App/assets/77237602/ee9c0eef-3ffc-4919-8e66-d99f9b13107d

**PS:** I once again apologise for not following the proposal but I went ahead with the PR after @eVoloshchak [approval](https://github.com/Expensify/App/issues/25548#issuecomment-1736185454).

**Comment by esh-g** [comment] 2023-09-27 11:14
@thienlnam Here is the current behaviour on `staging` in the video. You can see that if we go to the share destination(#admins in this case) we don't get a reply added after closing/re-opening, but when we go to assignee report, then only one reply is added for closing it once and successive opening/closing is not counted.

https://github.com/Expensify/App/assets/77237602/26d28ac4-fc58-4748-b4b6-62df1afcf846

**Comment by esh-g** [comment] 2023-09-27 11:25
@thienlnam You can see here that when we close/open the task, the system `reportAction` is added to the `taskReport` but the `reportAction` of the task itself is not edited and the `childVisibleActionCount` field is not incremented. This means that we don't want to include the system messages as replies. Only when an actual person comments in the `taskReport` does a reply get added.

<img width="457" alt="Screenshot 2023-09-27 at 4 49 51 PM" src="https://github.com/Expensify/App/assets/77237602/678911ea-666d-48bd-88ef-feeee43c5611">

In this image, 2 replies are added because a real person has sent a message, despite the task being reopened/closed multiple times.

**Comment by thienlnam** [comment] 2023-09-28 02:25
Okay, I see what you are saying now - yes in that case I agree with not counting the system messages as replies

**Comment by greg-schroeder** [comment] 2023-10-12 16:35
next up is c+ checklist

**Comment by ayazhussain79** [comment] 2023-10-12 16:38
@greg-schroeder offer accepted, Thank you

**Comment by eVoloshchak** [comment] 2023-10-16 08:52
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24110
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24110/files#r1360318107
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this is just an edge case (re-assigning a task to another person) that was missed during a review
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No_
This was mainly resolved on the back-end (we don't count re-assigning a task as a reply), so the only issue that was left (and fixed) on FE is all parent reports not being marked as completed when you complete the task. This isn't a common case and is not impactful (the user can still use the app), I think a regression test is not needed in this case

**Comment by greg-schroeder** [comment] 2023-10-16 14:44
Thanks @eVoloshchak

**Closed by greg-schroeder** 2023-10-16 14:44 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-16 18:45
$1,000 payment approved for @eVoloshchak based on [this summary](https://github.com/Expensify/App/issues/25548#issuecomment-1759971286).
