### ISSUE TITLE
Chat - Chat Page does not scroll to the bottom when receiving new message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34279] opened 2024-01-10 18:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in on account A on web
2. Sign in on account B on another device
3. Account A and B should have previous conversation which is scrollable on the chat page
4. While chat is open on account A on web and is scrolled to the bottom send a message to account A from account B
5. Observe the chat page on account A

## Expected Result:
The chat page should scroll down to the bottom to show the newly received comment

## Actual Result:
The chat stays at the same position after new messages arrive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8f87f7cf-0e51-4f94-a1f8-8f487b5717b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2024-01-10 18:22
Seems like same root cause as https://github.com/Expensify/App/issues/34240

**Comment by roryabraham** [comment] 2024-01-10 18:23
agree, should be fixed by https://github.com/Expensify/App/pull/34244

**Comment by marcaaron** [comment] 2024-01-11 22:12
Think this one can be closed out now.

**Closed by marcaaron** 2024-01-11 22:12 UTC
Labels: Engineering, Hourly
