### ISSUE TITLE
[HOLD for payment 2023-06-19] [HOLD for payment 2023-06-15] [$1000] Chat - Context menu (long tap on message) does not open when the keyboard is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20422] opened 2023-06-07 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS App or iPad app and login with any account
2. Go to any chat
3. Focus to input field to open keyboard
4. Scroll chat and long tap to any message

## Expected Result:
Сontext menu opens.
Keyboard closed.

## Actual Result:
Context menu does not open when keyboard open.
Keyboard does not close.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.3

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f7794a28-3c79-4d8c-a9c6-986c8c855b90

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team & [syedsaroshfarrukhdot](https://github.com/syedsaroshfarrukhdot)

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197a7315599dfaf41</li>
        <li>Upwork Job ID: 1666596829203070976</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-08 03:42
I'm taking this over because @amyevans is OOO

**Comment by roryabraham** [comment] 2023-06-08 03:43
Removing the `Help Wanted` label for now because this is a deploy blocker, needs to be resolved ASAP

**Comment by roryabraham** [comment] 2023-06-08 04:12
I believe [this](https://github.com/Expensify/App/blob/d1ddc7c1d373cf69dff7e0d3fc3eb96c6eb2d4c4/src/components/LHNOptionsList/OptionRowLHN.js#L60C1-L62) is out problem line

**Comment by roryabraham** [comment] 2023-06-08 04:22
Ok, so there's something causing the LHN to re-render when the popover modal opens, even if it's not visible.

**Comment by situchan** [comment] 2023-06-08 04:22
I noticed performance issue in latest main.
`OptionRowLHN` component is mounted every time report action context menu is opened on mobile.

**Comment by roryabraham** [comment] 2023-06-08 04:42
Yeah, I discovered that too. I do have a fix incoming but maybe there could be a more generic fix possible that would also address that performance concern.

**Comment by roryabraham** [comment] 2023-06-08 04:52
Draft PR to fix this: https://github.com/Expensify/App/pull/20442

**Comment by situchan** [comment] 2023-06-08 04:54
These symptoms are useful to find the exact root cause.

Case 1:
- focus on composer
- keyboard shows
- long-press message
- keyboard closes
- `OptionRowLHN` re-mounts

Case 2:
- focus on composer
- keyboard shows
- click header to open report detail page
- click back button to go back to Report screen
- `OptionRowLHN` re-mounts

Important note: `OptionRowLHN` is not `re-mounted` without these steps: (keyboard is hidden)
- focus on composer
- keyboard shows

So this performance issue is related to keyboard visibility or composer focus change.

https://github.com/Expensify/App/assets/108292595/01d28b10-a507-4b63-984c-ae5fccc52066

**Comment by roryabraham** [comment] 2023-06-08 04:59
I found a [potential fix](https://github.com/Expensify/App/pull/20442), but I don't think it necessarily addresses the root cause.

**Comment by roryabraham** [comment] 2023-06-08 05:19
Indeed, the root cause does seem to be that, only when the software keyboard is open, showing the `ReportActionContextMenu` causes items in the `LHNOptionsList` `FlatList` to remount. The `LHNOptionsList` itself does not remount, so this may be something happening inside `FlatList`.

**Comment by situchan** [comment] 2023-06-08 05:20
https://github.com/Expensify/App/blob/78aa3bab34b305f9f3aa818ce501c6f133881200/src/components/LHNOptionsList/LHNOptionsList.js#L104
I confirmed this line re-mounts `renderItem` of `FlatList` whenever keyboard visibility changes from visible to invisible.
This was hidden bug before and revealed after navigation refactor which broke freeze behavior in LHN. I noticed LHN is never frozen when open any other pages.

**Comment by roryabraham** [comment] 2023-06-08 05:22
> navigation refactor which broke freeze behavior in LHN. I noticed LHN is never frozen when open any other pages.

I think this is intentional. The current and previous page are never frozen. The previous page (LHN is this case) is not frozen so that it renders immediately when the current page is dismissed.

**Comment by situchan** [comment] 2023-06-08 05:23
If it's intentional, why Freeze wrapper not completely removed here?
https://github.com/Expensify/App/blob/78aa3bab34b305f9f3aa818ce501c6f133881200/src/pages/home/sidebar/SidebarScreen/index.native.js#L9

**Comment by situchan** [comment] 2023-06-08 05:33
> I found a [potential fix](https://github.com/Expensify/App/pull/20442), but I don't think it necessarily addresses the root cause.

Though it doesn't fix the main root cause of performance issue, I think this is good solution, as it's another optimization to prevent unnecessary call of hiding any irrelevant context menu.
If there's way to check if currently open context menu type is `ContextMenuActions.CONTEXT_MENU_TYPES.REPORT`, it may not need navigation focus listener.

**Comment by roryabraham** [comment] 2023-06-08 05:46
I kind of think that the root problem is that it's a bad idea to put state or side effects in `VirtualizedList` items, because we don't have a lot of control for when those items mount and unmount. After all, the way `VirtualizedList` works is by keeping only a subset of the items mounted at any given time.

**Comment by roryabraham** [comment] 2023-06-08 06:17
PR is ready for review

**Comment by roryabraham** [comment] 2023-06-08 08:06
So that PR works, but I'm actually working on what I think will end up being a better solution, because it will:

1. Not cause a regression in the edge case where you have the `Pin` / `Unpin` menu open and then change the pinned status of that report from another device.
1. Cleans up the implementation of the `Pin` / `Unpin` menu by separating it from the `ReportActionContextMenu` and creating a separate `LHNContextMenu`.

**Comment by mountiny** [comment] 2023-06-08 12:42
Making this daily, PR has been merged and its being CPed to staging, we can create a better implementation as a polish

**Comment by syedsaroshfarrukhdot** [comment] 2023-06-08 12:51
I reported this issue(deploy blocke) before hitting main somehow for it github issue wasn't created.

https://expensify.slack.com/archives/C049HHMV9SM/p1686106979154279?thread_ts=1686106979.154279&cid=C049HHMV9SM

**Comment by syedsaroshfarrukhdot** [comment] 2023-06-09 22:35
@roryabraham @mountiny am I eligible for reporting bonus here ?

**Comment by mountiny** [comment] 2023-06-12 22:53
I bealive you should be

**Comment by Christinadobrzyn** [comment] 2023-06-13 21:28
Hired in Upwork
Internal job: https://www.upwork.com/ab/applicants/1666596829203070976/job-details
External job: https://www.upwork.com/jobs/~0197a7315599dfaf41

Reporter @syedsaroshfarrukhdot 
C+ @parasharrajat 

Is there anyone else to hire for this? Looks like the PR was created by @roryabraham and not an external contributor

**Comment by Christinadobrzyn** [comment] 2023-06-15 19:45
Looks like we're now paying this on [HOLD for payment 2023-06-19] - got a few days

**Comment by Christinadobrzyn** [comment] 2023-06-20 22:33
Ready for payment - 

Is there a speed bonus for this? I can't tell in the PR @parasharrajat 

Also, do we need a regression test?

**Comment by Christinadobrzyn** [comment] 2023-06-21 20:40
Ah okay, thanks! Speed bonus doesn't apply to internal jobs. I'll pay this out!

**Comment by Christinadobrzyn** [comment] 2023-06-26 22:59
I think we still need a regression on this, @parasharrajat or @roryabraham?

**Comment by roryabraham** [comment] 2023-06-29 22:57
Proposed regression test steps:

1. Go to any chat
1. Focus the message input field to open keyboard
1. Scroll chat and long tap to any message
1. **Verify** that the keyboard closes and the context menu opens.

I believe this can go in the [Message Action menu - Other scenarios (multiline, emojis and markdown)](https://expensify.testrail.io/index.php?/cases/view/1977394) test suite.

**Comment by Christinadobrzyn** [comment] 2023-06-30 18:48
Awesome thanks Rory! Submitted the regression test - https://github.com/Expensify/Expensify/issues/296227

**Closed by Christinadobrzyn** 2023-06-30 18:48 UTC
Labels: Engineering, Daily
