### ISSUE TITLE
[$1000] ESC key focuses the input field in emoji picker before closing it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18559] opened 2023-05-07 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open emoji picker
2. remove focus by clicking outside
3. now press ESC

## Expected results: 
should close the emoji picker
## Actual results: 
re-focuses the search field before closing it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236695744-2313c10a-5621-4318-94b2-c7237716c416.mp4

https://user-images.githubusercontent.com/43996225/236695749-d75dbf0b-9511-4c5e-96ef-18f9c4f5402c.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683389168956379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd478505a855a06d</li>
        <li>Upwork Job ID: 1655819951666835456</li>
        <li>Last Price Increase: 2023-05-09</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-08 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ESC key focuses the input field in emoji picker before closing it
### What is the root cause of that problem?
We allow typing in the search box if any key is pressed. But we don't prevent some special keys like command, esc, option, control,...
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/components/EmojiPicker/EmojiPickerMenu/index.js#L181-L190
### What changes do you think we should make in order to solve the problem?
We should check if the pressed key is a special key (length > 1) we will prevent focusing the input like this
 
```
// if the key pressed is non-character keys like Enter, Shift, ... do not focus
        if (keyBoardEvent.key.length > 1) {
            return;
        }
if (this.searchInput && !this.searchInput.isFocused()) {
                this.setState({selectTextOnFocus: false});
                this.searchInput.focus();
.....
```

### What alternative solutions did you explore? (Optional)

**Comment by michaelhaxhiu** [comment] 2023-05-08 16:56
Re-assigning because I'm headed OOO this week (starting this evening) and need to clear my plate.

**Comment by kadiealexander** [comment] 2023-05-09 06:19
Reproduced on the desktop web app:

https://user-images.githubusercontent.com/59587260/237010631-e76e08b9-61eb-4852-be97-033c67fe940d.mp4

**Comment by dukenv0307** [comment] 2023-05-09 07:09
## PROPOSAL
[updated](https://github.com/Expensify/App/issues/18559#issuecomment-1538385726)

**Comment by qsstudioprince** [comment] 2023-05-09 12:43
**Please re-state the problem that we are trying to solve in this issue.**
Pressing the ESC key in the Emoji menu (when search bar is not focused) focuses the search bar before closing.
**What is the root cause of that problem?**
The final if statement in keyDownHandler, triggers the search input to focus as the if statement only checks if search input is not focused.
**What changes do you think we should make in order to solve the problem?**
When the ESC key is pressed, it should simply execute the default behaviour and close the menu without having to execute any of the actions inside keyDownHandler.
We should add a if statement at the beginning of the handler to check if ESC is pressed and return from the function without executing any of the other if statements.
`
this.keyDownHandler = (keyBoardEvent) => {
            if (keyBoardEvent.key === 'Escape') {
                return;
            }
....
}
`
What alternative solutions did you explore? (Optional)
I explored the other proposals mentioned above which works as well. However, I feel there is no need to go through all the if statements if ESC is pressed.

**Comment by qsstudioprince** [comment] 2023-05-09 12:48
Contributor details
Your Expensify account email: prince@qsstudio.co
Upwork Profile Link: https://www.upwork.com/freelancers/~014fb8412d7c83935a

**Comment by qsstudioprince** [comment] 2023-05-09 12:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the ESC key in the Emoji menu (when search bar is not focused) focuses the search bar before closing.

### What is the root cause of that problem?
The final if statement in keyDownHandler, triggers the search input to focus as the if statement only checks if search input is not focused.

### What changes do you think we should make in order to solve the problem?
When the ESC key is pressed, it should simply execute the default behaviour and close the menu without having to execute any of the actions inside keyDownHandler.
We should add a if statement at the beginning of the handler to check if ESC is pressed and return from the function without executing any of the other if statements.
`this.keyDownHandler = (keyBoardEvent) => { if (keyBoardEvent.key === 'Escape') { return; } .... }`

### What alternative solutions did you explore? (Optional)
I explored the other proposals mentioned above which works as well. However, I feel there is no need to go through all the if statements if ESC is pressed.

**Comment by chiragxarora** [comment] 2023-05-09 16:12
I'm very sure this is introduced with a recent merge since at the time of reporting, it was not present in production. I mentioned it in the bug report too but I think that was missed while creating issue.
[original bug report](https://expensify.slack.com/archives/C049HHMV9SM/p1683389168956379)

**Comment by dukenv0307** [comment] 2023-05-12 15:28
@thesahindia [This PR](https://github.com/Expensify/App/pull/18425) causes this bug. 
**Before:** We always subscribe the ESC key to close modal 
<img width="1440" alt="Screenshot 2023-05-12 at 22 19 46" src="https://github.com/Expensify/App/assets/129500732/067c6d80-2dbb-4912-99b6-2b894c795c7c">
So that, the modal is closed before the key down listener is triggered here https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/components/EmojiPicker/EmojiPickerMenu/index.js#L181-L190
--> this bug doesn't happen 

**Now:** After [This PR](https://github.com/Expensify/App/pull/18425) is merged, we only subscribe ESC key when `this.props.isShortcutsModalOpen === true`. So in this bug, the app doesn't subscribe ESC key and then this code is triggered before the modal closed
https://github.com/Expensify/App/blob/ab9171f953603bb8e4e061f5582a4b7cab3d4a43/src/components/EmojiPicker/EmojiPickerMenu/index.js#L181-L190

**Comment by dukenv0307** [comment] 2023-05-12 15:34
So IMO, the RCA is we don't prevent subscribing the special key in the emoji search input (It's unnecessary)

In the main composer, we also don't focus if  a key is pressed in combination with Meta, Control or Alt or If the key pressed is non-character keys like Enter, Shift (see [this PR](https://github.com/Expensify/App/pull/17360))

**Comment by techievivek** [comment] 2023-05-12 15:59
I am not sure if this is worth fixing because it seems to close the emoji picker just fine.

**Closed by techievivek** 2023-05-12 15:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by dukenv0307** [comment] 2023-05-15 04:01
@techievivek I just created [new bug on Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1684122938118289) to catch [this bug](https://github.com/Expensify/App/issues/18559#issuecomment-1545967864)
