### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Track - Missing "Delete expense" in report details page when expense is tracked in self DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44334] opened 2024-06-24 20:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Track expense > Manual
4. Track an expense
5. Go to transaction thread
6. Click on the chat header
7. Note that "Delete expense" is present in report details page
8. Go to self DM.
9. Track an expense
10. Go to transaction thread
11. Click on the chat header

## Expected Result:
"Delete expense" will be present in report details page when expense is tracked in self DM

## Actual Result:
"Delete expense" is not present in report details page when expense is tracked in self DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/11508ec9-699f-4b79-a096-18531d1e4f03

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb4860cbcf9ab40f</li>
        <li>Upwork Job ID: 1806787222801178404</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102950333</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by lanitochka17** [comment] 2024-06-24 20:26
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-24 20:28
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-06-25 06:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing delete expense option in self DM track expense report details page.

### What is the root cause of that problem?
The condition to show the delete expense is shown as below:
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/pages/ReportDetailsPage.tsx#L190-L191

The condition that fails in self DM track is `ReportUtils.canAddOrDeleteTransactions(moneyRequestReport)` and `ReportUtils.isTrackExpenseReport(transactionThreadReport)`. `transactionThreadReport` is from the one-transaction report thread.
https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/pages/ReportDetailsPage.tsx#L95-L100

For self DM track, `transactionThreadReport` is undefined because it's not a one-transaction report and `moneyRequestReport` (the parent report) is a self DM report, so `canAddOrDeleteTransactions` returns false. 

### What changes do you think we should make in order to solve the problem?

The `ReportUtils.isTrackExpenseReport` condition is copied from the MoneyRequestHeader and it's added to show the delete expense option for self DM track expense, so using `transactionThreadReport` doesn't make sense.

Instead, we should check if it's a self DM track or not with below condition:
`const isSelfDMTrack = ReportUtils.isTrackExpenseReport(report) && ReportUtils.isSelfDM(parentReport);`
So, the condition will be:
```
const canDeleteRequest = isActionOwner && (ReportUtils.canAddOrDeleteTransactions(moneyRequestReport) || isSelfDMTrack) && !isDeletedParentAction;
```

This is the same solution with my proposal [here](https://github.com/Expensify/App/issues/43591#issuecomment-2165024711) but on a different component and case.

**Comment by jayeshmangwani** [comment] 2024-07-01 07:08
I agree with @bernhardoj 's [Proposal](https://github.com/Expensify/App/issues/44334#issuecomment-2188094975) to check the isSelfDM condition for the canDeleteRequest check. LGTM 🚀 

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment] 2024-07-01 08:30
@dominictb I see that your comment has been marked as outdated. Is there anything I can help with regarding the selected proposal?

**Comment by jayeshmangwani** [comment] 2024-07-01 08:34
Thanks for the understanding!

**Comment by bernhardoj** [comment] 2024-07-02 05:10
PR is ready

cc: @jayeshmangwani

**Comment by bernhardoj** [comment] 2024-07-10 12:40
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment] 2024-07-16 02:06
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/44334#issuecomment-2220190146) (07-17)

**Comment by sakluger** [comment] 2024-07-16 21:36
Thanks @bernhardoj! I'll complete payments tomorrow.

@jayeshmangwani could you please complete the BZ checklist?

**Comment by bernhardoj** [comment] 2024-07-17 02:53
I requested in ND.

**Comment by jayeshmangwani** [comment] 2024-07-17 18:52
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43251
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43251#discussion_r1681577192
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


## Regression Test Proposal

1. Open self DM.
2. Track a new expense.
3. Open the track expense report.
4. Press the header.
5. Verify that there is a "Delete expense" option.

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment] 2024-07-18 14:26
@sakluger hi, I have requested the payment in ND (not paid yet). Can/should I refund the upwork so I get paid in ND?

**Comment by sakluger** [comment] 2024-07-18 14:28
@bernhardoj, I'm sorry - I missed your comment about requesting in NewDot. Let me find out if it's possible to reverse the Upwork payment.

**Comment by sakluger** [comment] 2024-07-18 15:29
Hi @bernhardoj - I requested a refund in Upwork. Can you please confirm the refund and let me know once you have done so?

**Comment by bernhardoj** [comment] 2024-07-18 15:34
@sakluger I have issued the refund

**Comment by sakluger** [comment] 2024-07-18 16:15
Summarizing payment on this issue:

Contributor: @bernhardoj $250, please request on NewDot
Contributor+: @jayeshmangwani $250, please request on Newdot

**Closed by sakluger** 2024-07-18 16:15 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-19 02:19
$250 approved for @bernhardoj

**Comment by jayeshmangwani** [comment] 2024-07-25 04:55
Requested $250

**Comment by JmillsExpensify** [comment] 2024-07-25 15:19
$250 approved for @jayeshmangwani
