### ISSUE TITLE
[HOLD for payment 2023-12-28] [Theme Switching] 🐛 - Animation on 2FA confirmation has a dark background when light theme applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33116] opened 2023-12-14 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: set the light theme in the app
1. Open the app and log in
2. Tap Settings > Security > Two-factor authentication
3. Set up Two-factor authentication

## Expected Result:
The animation on the confirmation screen has a light background

## Actual Result:
The animation has a black background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/24924abb-046d-4a2c-a75f-11ce8c3382da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2023-12-14 22:01
same root cause as https://github.com/Expensify/App/issues/33106
removing the deploy blocker label

**Comment by stitesExpensify** [comment] 2023-12-14 22:02
cool, thanks!

**Comment by grgia** [comment] 2023-12-14 23:50
Gonna take this one if that's alright @stitesExpensify

**Comment by grgia** [comment] 2024-01-02 23:11
@peterdbarkerUK could you help ensure that @rushatgabhane is paid $500 C+ review for the review of https://github.com/Expensify/App/pull/33189

**Comment by rushatgabhane** [comment] 2024-01-03 08:10
Payment handled here https://github.com/Expensify/App/pull/33189#issuecomment-1874173603

**Comment by grgia** [comment] 2024-01-05 18:50
Closing as complete!

**Closed by grgia** 2024-01-05 18:50 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
