### ISSUE TITLE
[HOLD for TestRail] [$2000] Web - Request - App crashes after user splits bills & requests money & then signs out for specific account 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18979] opened 2023-05-15 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Sign into a valid account
3. Go to FAB menu & split bill with several user (User will be redirected to a DM)
4. Split bill within the same DM (I excluded one user)
5. Go to the FAB menu & request money to any user
6. Click on the IOU arrow within the DM with the user that was requested
7. Sign out of the account

## Expected Result:
User expects to sign out with no issues

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** [emilio.utest@gmail.com](mailto:emilio.utest@gmail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/21e46d2b-c3f5-4b7c-b510-876f6becd76b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ec428eb4024725b</li>
        <li>Upwork Job ID: 1659231896255647744</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-05-15 21:52
Looking into this

**Comment by jasperhuangg** [comment] 2023-05-15 22:19
Unable to reproduce. Going to remove the deploy blocker label and add `Needs Reproduction`. No need to block deploy here.

https://github.com/Expensify/App/assets/31285285/c5866795-8fee-4928-8f9a-46de7a0844ee

**Comment by kbecciv** [comment] 2023-05-15 22:44
I was Only able to reproduce with this [emilio.utest@gmail.com](mailto:emilio.utest@gmail.com) specific account

**Comment by jasperhuangg** [comment] 2023-05-16 18:17
@kbecciv Is there any chance you could DM the login information of this account to me so I could poke around with it?

**Comment by kbecciv** [comment] 2023-05-16 23:40
@jasperhuangg I need to ask tester to share the magic code for this account.

**Comment by mvtglobally** [comment] 2023-05-18 04:28
@jasperhuangg potentially related I am getting crash when settling with a different account mvtutest@gmail.com 

https://github.com/Expensify/App/assets/43995119/653c2574-23d6-4f36-b8b3-a9cb9a3ded48

**Comment by jasperhuangg** [comment] 2023-05-18 20:18
Still waiting on proposals, not overdue

**Comment by Thanos30** [comment] 2023-05-23 00:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

I am gonna simplify the issue. The prior steps are not needed, the issue happens when you sign out while in the IOU Preview of the Money Request. It is also happening on production. I will also attach a recording of how to reproduce the issue below since I saw some confusion above.

### What is the root cause of that problem?
If you pay attention to the Console tab when it crashes, it shows an error on the ParticipantLocalTime.js file.
Basically, the root cause of this problem is that after the Sign out click, a new report triggers with the details of the current user, which leads this specific condition to become true in the ReportActionComposer:

```
const shouldShowReportRecipientLocalTime = ReportUtils.canShowReportRecipientLocalTime(this.props.personalDetails, this.props.report) && !this.props.isComposerFullSize;

```
While the above condition returns true, there is not a recipient, which leads to the participant prop sent over to the ParticipantLocalTime component to be undefined, and therefore crash the app when we try to load it in the below code:

```
{shouldShowReportRecipientLocalTime && <ParticipantLocalTime participant={reportRecipient} />}

```


### What changes do you think we should make in order to solve the problem?

The best overall solution is to make sure we actually have a recipientParticipant before we call the ParticipantLocalTime.
So the above code should be:

```
{shouldShowReportRecipientLocalTime && reportRecipient && <ParticipantLocalTime participant={reportRecipient} />}

```

This solves the problem.


### Quick way to reproduce the issue:

https://github.com/Expensify/App/assets/32620770/fe70220a-b119-4d05-89d3-15beaf628c7a

**Comment by jasperhuangg** [comment] 2023-05-25 07:43
Good stuff @Thanos30, nice job explaining the root of the problem clearly. You've been assigned!

**Comment by Thanos30** [comment] 2023-05-25 12:48
Thank you @jasperhuangg , I sent a proposal on Upwork, I will have the PR ready by tonight!

**Comment by twisterdotcom** [comment] 2023-05-30 22:53
Just waiting on a merge from @jasperhuangg: https://github.com/Expensify/App/pull/19650#issuecomment-1568514017

**Comment by jasperhuangg** [comment] 2023-06-01 06:56
@twisterdotcom It's on staging now!

**Comment by twisterdotcom** [comment] 2023-06-06 23:54
Offers sent for $2k. I think I'm correct that there's no bonus here right?

**Comment by Thanos30** [comment] 2023-06-07 08:46
Hey @twisterdotcom , thank you for the offer.

I think I am eligible for the bonus, I made the PR the same day I was assigned the job, and with a change we discussed, it was ready the following day. 

Also, I believe the PR was merged  within the time limit, since I was told that 29th of May is a global day off.

Correct me if I'm wrong though

**Comment by Thanos30** [comment] 2023-06-09 17:04
Much appreciated @twisterdotcom.

**Comment by twisterdotcom** [comment] 2023-06-12 10:13
Bump @rushatgabhane on the question about testing? We need these steps completing: https://github.com/Expensify/App/issues/18979#issuecomment-1573405387

**Comment by twisterdotcom** [comment] 2023-06-14 10:18
Okay, nothing from @rushatgabhane or @jasperhuangg. Going to close.

**Closed by twisterdotcom** 2023-06-14 10:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
