### ISSUE TITLE
[$500] FAB - Menu icon doesn't change color when hovered over "New workspace" in FAB menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33747] opened 2023-12-29 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Hover over the "New Workspace" option in FAB menu

## Expected Result:
"New workspace" logo icon should change to black color in light theme & to white in dark theme when hovered over the option

## Actual Result:
"New workspace" logo icon doesn't change color when hovered over the menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6328100_1703819592407!Screenshot__18_](https://github.com/Expensify/App/assets/115492554/1e9194bd-46ac-4333-a6ba-d3a949185745)

![Bug6328100_1703819592403!Screenshot__19_](https://github.com/Expensify/App/assets/115492554/c0f2a1e4-f697-48fc-a808-581eb1703afe)

https://github.com/Expensify/App/assets/115492554/d2df22a0-a94b-4509-8cec-2ac6265e3d98

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01817cdb0a4cd143cf</li>
        <li>Upwork Job ID: 1740687208616701952</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28076897</li>
<li>aswin-s | Contributor | 28076898</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2023-12-29 11:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New workspace icon on FAB menu is not changing its color on hover.

### What is the root cause of that problem?

It seems like the intension is to keep the icon as such as `displayInDefaultIconColor: true` is set for this icon. Also the SVG used for this icon has fill color defined in it which prevents the fill from being modified programatically.


### What changes do you think we should make in order to solve the problem?

If we infact want to change the icon color on hover `displayInDefaultIconColor: true` should be removed from the icon for newWorkspace. Also the svg should be modified to remove the fill Color and use `currentColor` for building icon.

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" x="0" y="0" version="1.1" viewBox="0 0 40 40" style="enable-background:new 0 0 40 40" xml:space="preserve"><style type="text/css">.st0{}.st1{fill-rule:evenodd;clip-rule:evenodd;fill:currentColor}.st2{fill:#fed607;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}</style><path d="M20,0L20,0c11,0,20,9,20,20l0,0c0,11-9,20-20,20l0,0C9,40,0,31,0,20l0,0C0,9,9,0,20,0z" class="st0"/><path d="M13,12.8c0-1,0.8-1.8,1.8-1.8h10.5c1,0,1.8,0.8,1.8,1.8v14.5c0,1-0.8,1.8-1.8,1.8H22v-3.2	c0-0.4-0.4-0.8-0.8-0.8h-2.4c-0.4,0-0.8,0.4-0.8,0.8V29h-3.2c-1,0-1.8-0.8-1.8-1.8V12.8z M16.9,13c-0.6,0-1,0.4-1,1s0.4,1,1,1h6.2	c0.6,0,1-0.4,1-1s-0.4-1-1-1H16.9z M15.9,18c0-0.6,0.4-1,1-1h6.2c0.6,0,1,0.4,1,1s-0.4,1-1,1h-6.2C16.3,19,15.9,18.6,15.9,18z M16.9,21c-0.6,0-1,0.4-1,1s0.4,1,1,1h6.2c0.6,0,1-0.4,1-1s-0.4-1-1-1H16.9z" class="st1"/><path d="M28.8,5.8C28.8,5.7,28.7,5.7,28.8,5.8c-0.6-1-2-1-2.6,0l0,0l0,0l-0.9,1.7l-2.1,0.3l0,0l0,0	c-1.1,0.1-1.8,1.5-0.8,2.4l0,0l1.5,1.3l-0.3,1.8v0c-0.1,0.6,0.2,1.1,0.6,1.4c0.4,0.3,1,0.3,1.5,0.1c0,0,0,0,0,0l1.9-0.9l1.9,0.9	c0,0,0,0,0,0c0,0,0,0,0,0c0.5,0.2,1.1,0.2,1.5-0.1c0.4-0.3,0.7-0.8,0.6-1.4v0l-0.3-1.8l1.5-1.3l0,0c1-0.9,0.3-2.3-0.8-2.4l0,0	l-2.1-0.3L28.8,5.8z" class="st2"/></svg>

``` 

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by sofi-a** [comment] 2023-12-31 07:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "New workspace" menu icon under the FAB menu doesn't change colors when hovered on.
### What is the root cause of that problem?
It looks like the icon was intentionally made to not change colors as the ```displayInDefaultIconColor``` property is set to ```true``` [here](https://github.com/Expensify/App/blob/065aff13468c88bf584c4b7d776c6c543a337dd4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L218).

### What changes do you think we should make to solve the problem?
Removing the ```displayInDefaultIconColor``` property is not enough in this case because the [new-workspace](https://github.com/Expensify/App/blob/staging/assets/images/new-workspace.svg) icon is more complex than all the other menu icons under the FAB menu, which are transparent and take on the background of their container. My solution is to create a react component version of the icon to maximize the ease of customization.

```jsx
import React, { useEffect, useState } from 'react';
import useThemePreference from '@hooks/useThemePreference';

const colors = {
    background: '#03d47c0',
    building: '#fff',
    star: '#fed607',
    starStroke: '#03d47c',
}

function NewWorkspaceIcon(props) {
    const themePreference = useThemePreference();
    const [backgroundColor, setBackgroundColor] = useState(colors.background);
    const [buildingColor, setBuildingColor] = useState(colors.building);
    const [starStrokeColor, setStarStrokeColor] = useState(colors.starStroke);

    const resetColors = () => {
        setBackgroundColor(colors.background);
        setBuildingColor(colors.building);
        setStarStrokeColor(colors.starStroke);
    };

    useEffect(() => {
        if (props.hovered === 'true') {
            if (props.fill) {
                setBackgroundColor(props.fill);
                setStarStrokeColor(props.fill);
            }

            if (themePreference === 'dark') setBuildingColor('#000');
        } else resetColors();
    }, [props.hovered]);

    return (
        <svg
            x="0"
            y="0"
            version="1.1"
            viewBox="0 0 40 40"
            enableBackground="new 0 0 40 40"
            xmlSpace="preserve"
            {...props}
        >
            {/* Background */}
            <path
                d="M20,0L20,0c11,0,20,9,20,20l0,0c0,11-9,20-20,20l0,0C9,40,0,31,0,20l0,0C0,9,9,0,20,0z"
                fill={backgroundColor}
            />

            {/* Building */}
            <path
                d="M13,12.8c0-1,0.8-1.8,1.8-1.8h10.5c1,0,1.8,0.8,1.8,1.8v14.5c0,1-0.8,1.8-1.8,1.8H22v-3.2	c0-0.4-0.4-0.8-0.8-0.8h-2.4c-0.4,0-0.8,0.4-0.8,0.8V29h-3.2c-1,0-1.8-0.8-1.8-1.8V12.8z M16.9,13c-0.6,0-1,0.4-1,1s0.4,1,1,1h6.2	c0.6,0,1-0.4,1-1s-0.4-1-1-1H16.9z M15.9,18c0-0.6,0.4-1,1-1h6.2c0.6,0,1,0.4,1,1s-0.4,1-1,1h-6.2C16.3,19,15.9,18.6,15.9,18z M16.9,21c-0.6,0-1,0.4-1,1s0.4,1,1,1h6.2c0.6,0,1-0.4,1-1s-0.4-1-1-1H16.9z"
                fillRule="evenodd"
                clipRule="evenodd"
                fill={buildingColor}
            />

            {/* Star */}
            <path
                d="M28.8,5.8C28.8,5.7,28.7,5.7,28.8,5.8c-0.6-1-2-1-2.6,0l0,0l0,0l-0.9,1.7l-2.1,0.3l0,0l0,0	c-1.1,0.1-1.8,1.5-0.8,2.4l0,0l1.5,1.3l-0.3,1.8v0c-0.1,0.6,0.2,1.1,0.6,1.4c0.4,0.3,1,0.3,1.5,0.1c0,0,0,0,0,0l1.9-0.9l1.9,0.9	c0,0,0,0,0,0c0,0,0,0,0,0c0.5,0.2,1.1,0.2,1.5-0.1c0.4-0.3,0.7-0.8,0.6-1.4v0l-0.3-1.8l1.5-1.3l0,0c1-0.9,0.3-2.3-0.8-2.4l0,0	l-2.1-0.3L28.8,5.8z"
                fill={colors.star}
                stroke={starStrokeColor}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
            />
        </svg>
    )
}

export default NewWorkspaceIcon;
```

**All color customization logic is encapsulated in this component ensuring that we don't have to change how the [MenuItem](https://github.com/Expensify/App/blob/staging/src/components/MenuItem.tsx) component works or the alter svg. This is important to avoid affecting other parts of the platform.**

Import the new icon in [FloatingActionButtonAndPopover]( https://github.com/Expensify/App/blob/staging/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js).

```js
import NewWorkspaceIcon from './NewWorkspaceIcon';
```

Then replace the reference to [Expensicons.NewWorkspace](https://github.com/Expensify/App/blob/065aff13468c88bf584c4b7d776c6c543a337dd4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L220C1-L221C1) with the new icon. The ```displayInDefaultIconColor``` property should either be removed or set to ```false```.

The new menu item object should look something like this.
```js
{
    contentFit: 'contain',
    icon: NewWorkspaceIcon,
    iconWidth: 46,
...
```
#### Result

https://github.com/Expensify/App/assets/31987492/0dd62fd4-552b-45b3-a138-2e7fc6a04eb1

### What alternative solutions did you explore? (Optional)
N/A

**Comment by getusha** [comment] 2024-01-01 13:53
the [proposal](https://github.com/Expensify/App/issues/33747#issuecomment-1871957429) from @aswin-s looks good to me, seems like an issue we experienced before on other icons.
🎀 👀 🎀 C+ Reviewed!

**Comment by sofi-a** [comment] 2024-01-02 03:23
@getusha The color of the building in the icon in dark mode is currently white. @aswin-s's proposal would make it black even when it's not hovered on. Is that desired?

<img width="503" alt="Screenshot 2024-01-02 at 06 19 11" src="https://github.com/Expensify/App/assets/31987492/56430f2e-a1ee-4c37-a274-166db653a2b4">

**Screenshot from staging**
<img width="354" alt="Screenshot 2024-01-02 at 06 12 23" src="https://github.com/Expensify/App/assets/31987492/92857508-1dd9-43ef-b337-05124f37db4c">

**Comment by aswin-s** [comment] 2024-01-02 03:32
@sofi-a @getusha I simply used the fill style for other icons like request money.  If we want to retain building color as white for both dark and light mode, `currentColor` in SVG could be set accordingly. It's just an implementation detail.

![image](https://github.com/Expensify/App/assets/6880914/a76a4cb3-d37a-41a3-8bac-a755e93b3a0e)

**Comment by Pujan92** [comment] 2024-01-04 09:54
Just sharing my opinion that we also have the stroke width around the star and that color matches with the background color, isn't @sofi-a's proposal more accurate as we are also doing the same for Lounge Icon [here](https://github.com/Expensify/App/blob/main/src/components/Icon/svgs/LoungeAccessIcon.tsx)

**Comment by aswin-s** [comment] 2024-01-04 10:28
@Pujan92 `Expensicons.LoungeAccess` icon is throwing error on UserProfile Page.  I guess it is not used at the moment.

![image](https://github.com/Expensify/App/assets/6880914/bedbb95f-5a70-467e-8232-e4104e29ca4e)

Try removing `props.user.hasLoungeAccess ` conditional and load the page on a native device. 

The MenuItem component passes the icon prop down to `ImageSVG` component, which uses `expo-image` library to display the SVG file. It cannot accept a react component as mentioned in @sofi-a 's proposal. That's also the reason why UserProfile page crash if you try to enable the Lounge Access menu item.

**Comment by Pujan92** [comment] 2024-01-04 12:31
I got your point that it will crash at the moment after expo-image changes, to solve we can render conditionally considering whether src is a function or not which won't render in expo image if it is a function. 
Maybe the design team can help here about omitting the stroke around the star is fine or not @shawnborton 

| Current  | With selected proposal |
| ------------- | ------------- |
| <img width="120" alt="Screenshot 2024-01-04 at 17 59 08" src="https://github.com/Expensify/App/assets/14358475/ce8f39d0-dc71-4dc2-9781-987cce4e68c8"> | <img width="152" alt="Screenshot 2024-01-04 at 17 58 09" src="https://github.com/Expensify/App/assets/14358475/9bfe2bf2-4673-489f-a352-1dd1d12e5d17"> |

**Comment by aswin-s** [comment] 2024-01-04 13:28
@Pujan92 I never had the intension to remove the stroke around the star and I didn't mention anything like that in the proposal. Just that when I made the fix I accidentally dropped the stroke. I've fixed that now in the PR. Thanks for noticing.

This is how it looks now.

|Normal State| Hovered State|
|---|---| 
| <img src="https://github.com/Expensify/App/assets/6880914/311f3e63-30bc-4ecd-94b8-90c52e11b34f" width="400"/> | <img src="https://github.com/Expensify/App/assets/6880914/77f3f54d-20b6-4207-b018-490e21ad8f8e" width="400" /> |

**Comment by shawnborton** [comment] 2024-01-04 13:30
Part of me thinks we should keep the green BG on this particular item on hover, it feels a bit more special than the other items and almost like we want to specifically promote the green BG here as a new item to discover. What do you think @dannymcclain @dubielzyk-expensify ?

**Comment by shawnborton** [comment] 2024-01-04 13:30
As far as the stroke goes, we want to keep it there, but we can recreate the svg to not actually have a stroke line and just subtract that outline from the building shape. Is that what you need?

**Comment by aswin-s** [comment] 2024-01-04 13:37
> As far as the stroke goes, we want to keep it there, but we can recreate the svg to not actually have a stroke line and just subtract that outline from the building shape. Is that what you need?

@shawnborton That's how it is achieved right now.  So we wouldn't be needing another SVG file unless you feel something is missing with the current view. And there is no plan to remove the stroke. 

![image](https://github.com/Expensify/App/assets/6880914/3f0df8b6-7b67-4763-9f00-c95b13696aff)

**Comment by shawnborton** [comment] 2024-01-04 13:38
Ah okay, so what exactly is the bug then or what do you need the design team's input on?

**Comment by aswin-s** [comment] 2024-01-04 13:41
> Ah okay, so what exactly is the bug then or what do you need the design team's input on?

In the first implementation I accidentally missed the stroke. So @Pujan92 thought it was on purpose and pinged the design team to check whether it is okay to remove the stroke. I've clarified above that it was never the intention and just a mistake. Hope that clears all the confusion.

**Comment by shawnborton** [comment] 2024-01-04 13:45
Got it, sounds good! Let's not remove the stroke.

**Comment by dannymcclain** [comment] 2024-01-04 14:12
> Part of me thinks we should keep the green BG on this particular item on hover, it feels a bit more special than the other items and almost like we want to specifically promote the green BG here as a new item to discover.

I tend to agree. I don't really see this is as a bug—more of a choice. The "new workspace" icon feels intentionally different from the rest (and it's also the only item with a description, which further makes it feel special), and the _row_ still gets a hover state, so I don't really see the need to change the icon for this one.

BUT if y'all feel really strongly that we _do_ need to change it, I won't stand in the way!

**Comment by sofi-a** [comment] 2024-01-08 20:25
Thanks @Pujan92. I've updated my proposal according to your [comment](https://github.com/Expensify/App/issues/33747#issuecomment-1877023690) under the compatibility section. With the changes, we should be able to use svg react components in native platforms. @bfitzexpensify @shawnborton @dannymcclain what do you guys think?

**Comment by shawnborton** [comment] 2024-01-16 16:26
So this one isn't actually a bug - can we just close the issue out? cc @MariaHCD @bfitzexpensify

**Comment by MariaHCD** [comment] 2024-01-17 07:27
Thanks for the input on the design her!  I agree that this is not a bug.

**Comment by aswin-s** [comment] 2024-01-17 10:02
@MariaHCD Considerable effort was put into the PR to make it work seamlessly against both web and native platforms. The expected outcome on both themes were detailed out in [the proposal](https://github.com/Expensify/App/issues/33747#issuecomment-1871957429) itself. Still it got assigned and PR was raised 2 weeks ago. Is there a policy regarding how to compensate contributors on issues which gets closed after assigning and PR was raised?

**Comment by getusha** [comment] 2024-01-24 10:27
@MariaHCD I think partial compensation makes sense, since there was time spent on the PR before deciding to close this out.

**Comment by MariaHCD** [comment] 2024-01-24 15:31
Okay, that's fair. I'd like @bfitzexpensify's input but what partial compensation here do you think is fair in this case, @aswin-s?

**Comment by aswin-s** [comment] 2024-01-24 23:07
@MariaHCD I leave the decision to you. That's why I was checking if there is a process already in place for such scenarios.

**Comment by MariaHCD** [comment] 2024-01-29 07:41
Referencing the internal [SO](https://stackoverflowteams.com/c/expensify/questions/8719) and [this doc](https://docs.google.com/document/d/1t9KDPiEJmTEIVpo7hUsAGqdDdazIHY2A6znewEf5S4s/edit#heading=h.198et3u52rxj): Considering the effort/time spent on the PR and on testing as well as the C+'s time in reviewing the proposals here and reviewing the PR, I think 25% partial payment to both is fair. Thoughts, @bfitzexpensify?

**Comment by getusha** [comment] 2024-02-05 20:50
bump @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2024-02-05 21:24
>Referencing the internal [SO](https://stackoverflowteams.com/c/expensify/questions/15279) and [this doc](https://docs.google.com/document/d/1t9KDPiEJmTEIVpo7hUsAGqdDdazIHY2A6znewEf5S4s/edit#heading=h.198et3u52rxj): Considering the effort/time spent on the PR and on testing as well as the C+'s time in reviewing the proposals here and reviewing the PR, I think 25% partial payment to both is fair. Thoughts, @bfitzexpensify?

I agree, 25% seems fair. Payments complete.

**Closed by bfitzexpensify** 2024-02-05 21:24 UTC
Labels: Reviewing, External, Weekly, Bug
