### ISSUE TITLE
[$500] mWeb/Chrome - Chat – Deleted message appears briefly when navigate via IOU link after re-login.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33144] opened 2023-12-15 09:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. As account A, create an IOU with account B.
3. Navigate to the IOU details page and copy the URL.
4. Log out.
5. Log in with the same account or account B and navigate to the copied URL.

## Expected Result:
IOU link opens.

## Actual Result:
Deleted message appears briefly in a chat when navigate via IOU link after re-login.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1962d579-a011-4e89-ac41-d5c02e3e029b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bcca99fc0ffe3ae</li>
        <li>Upwork Job ID: 1735598780619743232</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-15 11:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Delete message] shows in the money request detail header after login.
### What is the root cause of that problem?
Report actions is slowly loaded than reports.
Transaction title should returned here
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/libs/ReportUtils.ts#L2262-L2262
But returned here because parentReportAction is empty
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/libs/ReportUtils.ts#L2276
### What changes do you think we should make in order to solve the problem?
We need to check all actions is loaded before returning.
```
       const allReportActions = ReportActionsUtils.getAllReportActions(report.reportID);
        if(!parentReportActionMessage && isEmptyObject(parentReportAction)) {
            return '';
        }
```
We need to add this code before return delete title.
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/libs/ReportUtils.ts#L2276

when we return '', header will be shown as loading.
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/85ead226-841b-4c0a-994e-3c3272d8c322

**Comment by yh-0218** [comment] 2023-12-18 22:29
I got ```const allReportActions = ReportActionsUtils.getAllReportActions(report.reportID);```
When we get `props.report` value on `HeaderView`, `allReportActions` of `ReportActionsUtils` is {} during very short time.
This time is long on Android(because android is slow).
so we get return value here.
https://github.com/Expensify/App/blob/648c000bcc1d4299032a806e217b83f324be1f7e/src/libs/ReportUtils.ts#L2276

Because of `ParentReportAction` is {}, we get deleted message.
So during `allReportActions` is {} (very short time), I returned '' value.
when `title` is '', `HeaderView` is on loading status.
When `allReportActions` has value, then we can get correct title.

@fedirjh

**Comment by yh-0218** [comment] 2023-12-18 22:32
https://github.com/Expensify/App/blob/648c000bcc1d4299032a806e217b83f324be1f7e/src/libs/ReportUtils.ts#L2259
We get `parentReportAction` to get title, but above code is available when `allReportActions` of `ReportActionsUtils` has value.
So I checked that value.

**Comment by yh-0218** [comment] 2023-12-19 08:15
```js
const allReportActions = ReportActionsUtils.getAllReportActions(report.reportID);
if(!parentReportActionMessage && isEmptyObject(allReportActions)) {
    return '';
}
```
Sorry @fedirjh 
My mistake to create proposal.
We need to check allReportActions is empty.

**Comment by NicMendonca** [comment] 2023-12-22 17:20
@fedirjh proposals for you! ^

**Comment by bernhardoj** [comment] 2023-12-30 07:48
@fedirjh you mean you still didn't see the skeleton after applying the solution? If yes, I don't know if it gonna help but can you try to subscribe to the parentReportActions onyx?
```
parentReportActions: {
    key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report?.parentReportID}`,
    canEvict: false,
},
```
Then, you can do this to get the specific parent report action.
```
const parentReportAction = props.parentReportActions[`${props.report.parentReportActionID}`];
```

_theoritically, you should see the skeleton without the above code, but we still need to apply the above code at the end_
_The code I wrote in the proposal is just to make it simple._

**Comment by bernhardoj** [comment] 2024-01-03 03:29
>  I suspect it could fail in the case of a deleted parent report action, which would result in the skeleton being displayed indefinitely

From my testing, if the parent action is deleted, the action still exists, only the message is deleted.

Here is how the action object looks on a normal thread
<img width="364" alt="image" src="https://github.com/Expensify/App/assets/50919443/965bf9fd-6984-4f66-863d-7bcf2896661d">

Here is how the action object looks on a transaction (IOU) thread
<img width="361" alt="image" src="https://github.com/Expensify/App/assets/50919443/1eb3caf3-af57-4af6-884e-d71765bfd423">

**Comment by yh-0218** [comment] 2024-01-03 05:30
@fedirjh I think this is good way.
```js
if(report?.parentReportID && report?.parentReportActionID && isEmptyObject(parentReportAction)) {
    return '';
}
```

**Comment by NicMendonca** [comment] 2024-01-04 21:05
> Navigate to the IOU details page and copy the URL.
> Log out
> Log in with the same account or account B and navigate to the copied URL

^ I am not sure how common of a practice this is going to be for end-users. 

So with that, I am going to close this based on this -- https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859

Since this is not directly related to a roadmap feature. 

Appreciate the discussion so far!

**Closed by NicMendonca** 2024-01-04 21:05 UTC
Labels: External, Daily, Help Wanted, Bug
