### ISSUE TITLE
404 page-Clicking on "Go back to home page" link and the back icon does nothing

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38119] opened 2024-03-12 09:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36767

**Version Number:** v1.4.50-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to OldDot and open the settings for the Collect/Control policy (create one first if needed)
2. In the JS console with the policy open, run:
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();
3. Create an open expense report (but do not add expenses to it)
4. Comment on it
5. In NewDot, open the report
6. Click on the title of the report
7. After "Hmm... it's not here" Page shows up click on "Go back to home page" link or the back icon at the top

## Expected Result:
The modal should close and take user to the home page or previous page

## Actual Result:
Clicking on "Go back to home page" link or the back icon at the top does nothing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/603d1328-40c1-4188-af51-6aae8cd1a217

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-12 09:37
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nkdengineer** [comment] 2024-03-12 10:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on "Go back to home page" link or the back icon at the top does nothing

### What is the root cause of that problem?
We pass `onBackButtonPress` and `onLinkPress` as do nothing which cause nothing happens when we click on `backButton` or `Go back to home page`

https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/EditReportFieldPage.tsx#L58-L59

### What changes do you think we should make in order to solve the problem?
We can remove these props and use default behavior of back button and link press of `NotFoundPage`. Or we can back the the page that we want to go back that can be confirmed by internal team.

https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/EditReportFieldPage.tsx#L58-L59

### What alternative solutions did you explore? (Optional)
NA

**Comment by dragnoir** [comment] 2024-03-12 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Editing the policy title, leads to Hmm... it's not here

### What is the root cause of that problem?

Better than just fixing the back button, let's fix the real issue.

On `EditReportFieldPage.tsx`, here
https://github.com/Expensify/App/blob/c039ff7421afb6eade7bb6107d80908564cc792a/src/pages/EditReportFieldPage.tsx#L46

**Issue:** We are seeking for one item from the `policyReportFields` array and that's turns back `undefined`

**Reason:**
We are geeting the `fieldID` from the root, in case for the title it's `text_title`

`https://dev.new.expensify.com:8082/w/6FFCDE4B6EE37E96/r/2246600089564140/edit/policyField/6FFCDE4B6EE37E96/text_title`

and if we log the  `policyReportFields` we will get:

// pic

So, we are calling for a row from `policyReportFields` with the wrong key.

### What changes do you think we should make in order to solve the problem?

We need to get the wright key for the `reportField`

We can create a quick function to get the right key:

```js
const fieldID = route.params.fieldID;

    let matchingKey = null; // Initialize as null; will store the matching key if found.

    // Iterate over the policyReportFields object to find a match.
    for (const key in policyReportFields) {
        if (policyReportFields.hasOwnProperty(key)) {
                matchingKey = key; // Found the matching key.
                break; // Exit the loop once a match is found.
            }
        }
    }
```

and the assign it here:

```diff
- const reportField = report?.reportFields?.[route.params.fieldID] ?? policyReportFields?.[fieldID];
+ const reportField = report?.reportFields?.[route.params.fieldID] ?? policyReportFields?.[matchingKey];
```

### What alternative solutions did you explore? (Optional)

We can also fix the `fieldID` on the route from the `MoneyReportView`
https://github.com/Expensify/App/blob/0dc2151378a3fdb4328cb3e0f1e5eb2dbc8e1e7c/src/components/ReportActionItem/MoneyReportView.tsx#L86-L89

**Comment by sakluger** [comment] 2024-03-14 19:10
I agree with @dragnoir that the real issue is that editing a report title causes the `Hmm...it's not here` error, rather than the back button not working. Before moving forward with this issue, I've [asked in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1710443410737989) whether we've built the ability to edit report titles in NewDot yet.

**Comment by sakluger** [comment] 2024-03-14 20:00
This is already getting fixed here: https://github.com/Expensify/App/issues/36170

**Closed by sakluger** 2024-03-14 20:00 UTC
Labels: Daily, Bug
