### ISSUE TITLE
[HOLD for payment 2024-02-20] [$250] [Wave 8] [Ideal Nav] Workspace Switcher Icon: Missing tool tip and wrong icon color

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35618] opened 2024-02-02 00:34 UTC
## Action Performed:
1. On a browser, hover over the Workspace Switcher icon (the avatar-like icon at the top-left color of the new Left Hand Pane (see the video).

## Expected Result:
There should be a tooltip that displays `Choose a workspace`.
Only the background of the chevron icon should change, not the fill color of the chevron icon.

Please also read Shawn (our designer)'s additional comment [here](https://github.com/Expensify/App/issues/35618#issuecomment-1924152753)

## Actual Result:
The tooltip doesn't appear.
The fill color of the chevron icon on hover changes on hover..

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/98560306/77efe29e-a48a-442a-adef-57db3de62c89

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01566d00a9005cba1a</li>
        <li>Upwork Job ID: 1753450501284016128</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28141432</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2024-02-02 15:53
Also, want to clarify that for the small button over the workspace icon, just the button BG should be changing, not the icon color. We should be following our default button styles here.

**Comment by shawnborton** [comment] 2024-02-02 16:15
Hmm I would think the tool tip should actually say "Choose a workspace" since tapping this element takes you to that flow of the app. cc @trjExpensify @Expensify/design for a gut check there though.

**Comment by dannymcclain** [comment] 2024-02-02 16:20
> Hmm I would think the tool tip should actually say "Choose a workspace"

Totally agree.

**Comment by trjExpensify** [comment] 2024-02-02 17:48
Yup, I also agree with that.

**Comment by hayata-suenaga** [comment] 2024-02-04 05:19
@thesahindia please review proposals when you have time 🙇

**Comment by hayata-suenaga** [comment] 2024-02-04 22:49
sorry I apparently clicked a wrong button and caused everyone to be unassigned 😓 

@lakchote I'll keep assigning myself to this issue. I don't know whey Melvin assign you 🤷

**Comment by Christinadobrzyn** [comment] 2024-02-20 15:18
hi! Sorry I'm ooo sick today - I'll follow up on this tomorrow

**Comment by Christinadobrzyn** [comment] 2024-02-21 21:43
Payment summary

Contributor: $250 @dukenv0307 (paid in Upwork - https://www.upwork.com/nx/wm/offer/28141432)
Contributor+: $250 @thesahindia (in NewDot)

Eligible for 50% #urgency bonus? NA

Do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-02-22 15:38
awesome! thanks for confirming @thesahindia

This is paid out based on this payment summary - https://github.com/Expensify/App/issues/35618#issuecomment-1958018855

Closing - feel free to reach out with any questions!

**Closed by Christinadobrzyn** 2024-02-22 15:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-08 03:26
$250 approved for @thesahindia
