### ISSUE TITLE
[HOLD for payment 2024-02-07] [HOLD for payment 2024-02-07] [$500][Wave 9][Low] Mweb - BA - When user selects "State", the drop down list gets scrolled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32305] opened 2023-11-30 21:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3.  Tap Workspaces
4. Tap on a Workspace
5. Tap Bank account
6. Tap connect manually
7. Enter all fields and tap next
8. Select a state
9. Tap on state again and select any other state from the list

## Expected Result:
When user selects "State", the drop down list must not be scrolled

## Actual Result:
When user selects "State", the drop down list gets scrolled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ecf2ae5d-99f8-4eca-b0c7-8ba6bce5b69b

<img width="377" alt="2023-12-11_12-23-08" src="https://github.com/Expensify/App/assets/51066321/4c18ed45-8611-439d-bf59-ebfc3694ff8b">
<img width="325" alt="2023-12-11_12-22-51" src="https://github.com/Expensify/App/assets/51066321/cc5d62ad-1eba-4d0f-a853-e4015de09e32">
<img width="352" alt="2023-12-11_12-23-22" src="https://github.com/Expensify/App/assets/51066321/00474724-bf40-485b-ad0d-7af8d4ef8f8c">
<img width="369" alt="2023-12-11_12-23-36" src="https://github.com/Expensify/App/assets/51066321/fe0c037c-5b25-4891-bea8-9066a2634105">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6d7a0421d65ccee</li>
        <li>Upwork Job ID: 1730336841339785216</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by junsupark94** [comment] 2023-11-30 22:03
I don't understand the issue since there is no drop down menu for selecting state. In the video, the scrolling occurs due to the user scrolling up, right?

**Comment by SSRV25** [comment] 2023-12-01 03:59
I don't think this is a bug or problem as it is useful as of UX perspective.

**Comment by Christinadobrzyn** [comment] 2023-12-04 21:55
I agree, I don't think this is a bug - there's a search at the top of the page when selecting a state so the user could search for a different state if they don't see it in the drop-down. Why would it help to have the list start over once you've selected a state? Closing without action.

**Comment by Christinadobrzyn** [comment] 2023-12-05 16:52
Hi @bernhardoj thanks for the information. I'm still not sure what the bug is. Here's the video of what I see. 

Maybe the "issue" is that there are states listed above the one selected? 

https://github.com/Expensify/App/assets/51066321/20be13ba-ad52-4087-970a-4605ee3e013e

Where do you see a country selection that I can test?

**Comment by Christinadobrzyn** [comment] 2023-12-11 16:35
Ah okay, I do see that it looks like the state scroll to the top once a state is selected - thanks for pointing that out @bernhardoj 

However, I don't think that is something we need to focus on fixing. Do you see any reason why that would impact the use of the product? It's really hard to even notice and I don't think it deters from the functionality but I'm not an engineer so maybe it's doing something else on the backend? 

@eVoloshchak or @bernhardoj why should this be fixed?

**Comment by Christinadobrzyn** [comment] 2023-12-11 19:26
Okay sounds good - asking the team for their thoughts!

**Comment by Christinadobrzyn** [comment] 2023-12-12 18:04
I think this could be part of Wave 6 so I'm just checking with the team to see what our workflow should be to associate the bug with a wave - https://expensify.slack.com/archives/C01SKUP7QR0/p1702404266022039?thread_ts=1701355181.491179&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2023-12-13 00:25
Hi @greg-schroeder! I added this to the Wave 6 project because I think the issue could be addressed with those changes. I think this is a low-priority fix (as it's very difficult to catch the issue from the user side) but it is still a UX issue. Let me know your thoughts. Thank you!!

**Comment by Christinadobrzyn** [comment] 2023-12-14 00:41
Based on this convo in Slack about this bug - I'm moving this from Wave 6 to Wave 9 - https://expensify.slack.com/archives/C01SKUP7QR0/p1702490762698629?thread_ts=1702322692.823169&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2023-12-14 20:20
Added this GH to be evaluated as part of Wave 9 - asking the team if this should be moved to weekly - https://expensify.slack.com/archives/C01SKUP7QR0/p1702585175582119?thread_ts=1702341886.807759&cid=C01SKUP7QR0

**Comment by Christinadobrzyn** [comment] 2023-12-16 17:38
nope - keeping this daily

**Comment by Christinadobrzyn** [comment] 2023-12-19 23:20
I think we're good to review these proposals @eVoloshchak! let me know if you want to see more!

**Comment by Christinadobrzyn** [comment] 2023-12-21 21:59
@eVoloshchak can you review the provided proposals and let me know if you'd like to see more?

**Comment by eVoloshchak** [comment] 2023-12-22 20:56
@bernhardoj, I can still reproduce the issue when testing your [proposal](https://github.com/Expensify/App/issues/32305#issuecomment-1835456666), could you double-check that please?

https://github.com/Expensify/App/assets/9059945/120b8b9b-fc97-476b-bfdc-2ee7380b7f87

**Comment by Christinadobrzyn** [comment] 2024-01-03 01:00
It looks like we're discussing proposals. 

@eVoloshchak not sure if you have a chance to look at this - https://github.com/Expensify/App/issues/32305#issuecomment-1868195001

**Comment by eVoloshchak** [comment] 2024-01-03 21:45
@neonbhai's [proposal](https://github.com/Expensify/App/issues/32305#issuecomment-1868110091) looks good to me. 
There's no need to scroll the list on selection if user can select only a single item

🎀👀🎀 C+ reviewed!

**Comment by rlinoz** [comment] 2024-01-04 20:44
Should we make this its own property, like `scrollToTopOnSelect` or something?

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:34
I'm going ooo this week so going to add a buddy to this to monitor. 

Status - we're reviewing - https://github.com/Expensify/App/issues/32305#issuecomment-1876012164

**Comment by rlinoz** [comment] 2024-01-09 16:50
Thinking we might want this behavior at some point for multi select lists. https://github.com/Expensify/App/issues/32305#issuecomment-1877735649

@eVoloshchak @neonbhai

**Comment by eVoloshchak** [comment] 2024-01-11 17:40
> Should we make this its own property, like scrollToTopOnSelect or something?

@rlinoz, yeah, I think it's a good suggestion

**Comment by rlinoz** [comment] 2024-01-12 18:08
Thanks all, assigning @neonbhai!

**Comment by rlinoz** [comment] 2024-01-30 14:20
The solution here did caused a regression and got reverted as pointed out [here](https://github.com/Expensify/App/issues/35374#issuecomment-1916660717).

@neonbhai @eVoloshchak

**Comment by eVoloshchak** [comment] 2024-02-03 23:07
@neonbhai, looks like this has caused a regression (https://github.com/Expensify/App/issues/35374)
How can we resolve it and fix this issue?

**Comment by eVoloshchak** [comment] 2024-02-08 13:34
> One thing that seems to work is that Pushing State Selector to a Page

Those 3 bugs look pretty bad, so if can resolve those while resolving this issue - that would be great. 
But I think first we need to figure out **_why_** Pushing State Selector to a Page does resolve our issue

We need to know the root cause of this. Applying a workaround would work in this case, but the bug could potentially come back in case we refactor those pages (use different navigation lib, use modals, etc.) in the future
cc: @neonbhai

**Comment by Christinadobrzyn** [comment] 2024-02-12 23:23
just checking in here, are we working on a regression? Or can I pay this out?

**Comment by rlinoz** [comment] 2024-02-15 13:37
Hey @neonbhai were you able to move forward with this?

**Comment by rlinoz** [comment] 2024-02-19 12:12
Bumping ^
@neonbhai

**Comment by rlinoz** [comment] 2024-02-21 16:28
Can't reproduce in staging either.

**Comment by Christinadobrzyn** [comment] 2024-02-21 23:21
Ah okay, if it's not reproducible, I assume that means we can pay this out? 

Here's the payment summary [here](https://github.com/Expensify/App/issues/32305#issuecomment-1932247080) - it notes the 50% regression penalty - let me know if there's something different with that. 

Also does this need a regression test @eVoloshchak?

**Comment by eVoloshchak** [comment] 2024-02-26 01:03
> Ah okay, if it's not reproducible, I assume that means we can pay this out?

@Christinadobrzyn, this was fixed, but not by [this PR](https://github.com/Expensify/App/pull/34485) (since it was reverted)
I don't think we're eligible for any payment in this case

**Comment by Christinadobrzyn** [comment] 2024-02-26 22:15
Ah okay, thank you for confirming @eVoloshchak! I will close this but let me know if I'm missing anything!

**Closed by Christinadobrzyn** 2024-02-26 22:15 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
