### ISSUE TITLE
[HOLD for payment 2024-05-20] [$125] Workspace - Impossible to change workspace currency

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39435] opened 2024-04-02 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: User is logged in ND.  We should try to change name of already existing workspaces only.
1. Go to workspace profile.
2. Click on 'Default currency' > select any another currency

## Expected Result:
Workspace currency is changed to newly selected.

## Actual Result:
Workspace currency is not changed to newly selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f775e5a0-f920-4410-9612-5e8af89ddf97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d779d698f27e25f6</li>
        <li>Upwork Job ID: 1775310934472347648</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by izarutskaya** [comment] 2024-04-02 20:09
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-02 20:09
We think this issue might be related to the #collect project.

**Comment by abzokhattab** [comment] 2024-04-02 20:29
I think its related to this issue:

https://github.com/Expensify/App/issues/38928

**Comment by marcochavezf** [comment] 2024-04-02 23:54
Seems this can be fixed externally

**Comment by abzokhattab** [comment] 2024-04-02 23:59
i am no longer able to reproduce it on main .. is it still reproducible?

**Comment by hungvu193** [comment] 2024-04-03 03:07
Issue is reproducible on latest main.

https://github.com/Expensify/App/assets/16502320/3f122358-5f45-4fd9-a18b-e75bc53014e8

**Comment by abzokhattab** [comment] 2024-04-03 04:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is unable to change non-collect workspaces currency 
### What is the root cause of that problem?
 
the workspaces currency cannot be changed because in the `updateGeneralSettings` function we return if the `customUnitID` is `undefined` which is the case for all workspaces that are not "collect" workspace
https://github.com/Expensify/App/blob/3ca25eeccbfe4cef6c3ab4837ea05b42f96c9955/src/libs/actions/Policy.ts#L1510

### What changes do you think we should make in order to solve the problem?


we need to change the condition above to either we can remove the `|| !customUnitID` check completely:

```js
    if (!policy)
```

or we can keep it but check that the current workspace has an `outputCurrency` property:

```js
    if (!policy || (!customUnitID && !policy?.outputCurrency)) {
```

then to fix the typescript error in the optimistic, success and failure data we need to make sure that the `customUnitID` var is not undefined before modifying the `customUnits` property

1. change [this](https://github.com/Expensify/App/blob/3ca25eeccbfe4cef6c3ab4837ea05b42f96c9955/src/libs/actions/Policy.ts#L1556-L1561) to: 
```js
    ...(customUnitID && {
                    customUnits: {
                        [customUnitID]: {
                            ...distanceUnit,
                            rates: optimisticRates,
                        },
                    },
                }),
```
2. and [here](https://github.com/Expensify/App/blob/3ca25eeccbfe4cef6c3ab4837ea05b42f96c9955/src/libs/actions/Policy.ts#L1572-L1577) to: 
```js
               ...(customUnitID && {
                    customUnits: {
                        [customUnitID]: {
                            rates: finallyRates,
                        },
                    },
                }),
```
3. also [here](https://github.com/Expensify/App/blob/3ca25eeccbfe4cef6c3ab4837ea05b42f96c9955/src/libs/actions/Policy.ts#L1590-L1594) to:
```js
                ...(customUnitID && {
                    customUnits: {
                        [customUnitID]: {rates: finallyRates},
                    },
                })
```

**Comment by abzokhattab** [comment] 2024-04-03 04:12
@hungvu193 Correct. The issue occurs with workspaces that are not of the collect type.

**Comment by nkdengineer** [comment] 2024-04-03 04:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace - Impossible to change workspace currency
### What is the root cause of that problem?
- When we update the currency, [this logic](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Policy.ts#L1510) can return ```true``` because of ```customUnitID``` can be ```undefined```
### What changes do you think we should make in order to solve the problem?
- We can remove the ```!customUnitID``` in [this condition](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Policy.ts#L1510) 
- Then, we need to call:
```
     Policy.openPolicyDistanceRatesPage(policyID);
```
once we visit the workspace currency picker screen (/settings/workspaces/policyID/profile/currency)
- Then, we need to handle the offline mode. In this case, need to update [this](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Policy.ts#L1557), [this](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Policy.ts#L1574) and [this](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Policy.ts#L1591) to just apply these change if ```customUnitID``` is not ```undefined```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by abzokhattab** [comment] 2024-04-03 05:22
Updated the RCA in [my proposal](https://github.com/Expensify/App/issues/39435#issuecomment-2033492044), the solution is the same though.

**Comment by alitoshmatov** [comment] 2024-04-29 08:05
This was fixed in follow up [PR](https://github.com/Expensify/App/pull/39484). We can close this

**Comment by abzokhattab** [comment] 2024-04-29 20:09
> If we end up using solution from the proposals, lets pay $125 for their help.

I see that the changes are the same as in my proposal. just reminding you about the bounty as @mountiny stated. thanks

**Comment by abzokhattab** [comment] 2024-05-14 22:00
Kind reminder on this

**Comment by mountiny** [comment] 2024-05-20 20:06
$125 to @abzokhattab for their help cc @kadiealexander

**Comment by kadiealexander** [comment] 2024-05-21 05:11
Payouts due:

- [ ] Contributor: $125 @abzokhattab ([offer](https://www.upwork.com/nx/wm/offer/102397109))

Upwork job is [here](https://www.upwork.com/ab/applicants/1775310934472347648/job-details).

**Closed** 2024-05-23 01:00 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
