### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Not able to share logs to own self DM from "Debug console"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38147] opened 2024-03-12 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-5
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710208120099339

## Action Performed:
1. Open app
2. Go to settings > about> troubleshoot
3. Toggle client side logging> view debug console
4. Click share logs

## Expected Result:
User should be able to share to own DM to access in desktop

## Actual Result:
Does not give the option in the list

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a4547b06-8b43-4a81-a9c7-4184b83ec502

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e74b76766270067</li>
        <li>Upwork Job ID: 1767616215332700160</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by CortneyOfstad** [comment] 2024-03-12 17:12
Was able to recreate — believe this falls under VIP-VSB 👍

**Comment by CortneyOfstad** [comment] 2024-03-12 17:14
Asked [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1710263660575719)

**Comment by CortneyOfstad** [comment] 2024-03-12 18:18
Alright, David confirmed it is under VIP-VSB – going to have the priority be low, as the logs can be downloaded or sent into an admin channel as workarounds.

**Comment by agent3bood** [comment] 2024-03-12 19:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not able to share logs to own self DM from "Debug console"

### What is the root cause of that problem?

This is a two parts issue.

First we need to set `includeSelfDM: true` in this [function call](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.ts#L1753) to pass this [condition](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.ts#L1490).

Second we need to remove `{login: currentUserLogin}` from [here](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.ts#L1549)

### What changes do you think we should make in order to solve the problem?

As explained in the root cause section.

### What alternative solutions did you explore? (Optional)
n/a

<img width="401" alt="Screenshot 2024-03-12 at 22 29 47" src="https://github.com/Expensify/App/assets/771902/f19f5504-58de-4073-98a3-8f0ff0efa4b4">

**Comment by CortneyOfstad** [comment] 2024-03-15 16:19
> I believe enabling the option to send logs to threads as well, would be beneficial. since the user might want to organize the logs in a single thread instead of cluttering the main chat.

I **LOVE** this idea. I think it makes it much cleaner from a user perspective as well, helping to keep the chat organized without having giant blocks of texts. Great suggestion @abzokhattab!

@mkhutornyi Would love to get your input on this as well!

**Comment by CortneyOfstad** [comment] 2024-03-18 15:12
Continuing to wait on a response from Vivek and Tomaz and the question [here](https://github.com/Expensify/App/pull/36337/files#r1526981210). If we don't hear anything by EOD, going to bump 👍

**Comment by CortneyOfstad** [comment] 2024-03-20 15:26
They were bumped 2 hours ago, so waiting to hear to see if any conversations were had in regards to sharing logs in threads. Will continue to monitor 👍

**Comment by CortneyOfstad** [comment] 2024-04-05 14:14
@abzokhattab sent you an offer [here](https://www.upwork.com/nx/wm/offer/101747468)
@mkhutornyi sent you an offer [here](https://www.upwork.com/nx/wm/offer/101747502)

Please let me know once you both accept. 

Also @mkhutornyi please have the checklist above completed by EOD today — thanks!

**Comment by abzokhattab** [comment] 2024-04-05 16:19
Thank you! Just accepted the offer

**Comment by CortneyOfstad** [comment] 2024-04-08 17:32
@mkhutornyi looks like you haven't accepted the offer yet. Can you do that when you have a chance and let me know here? Thanks!

**Comment by CortneyOfstad** [comment] 2024-04-09 18:30
Bump @mkhutornyi ^^^

**Comment by CortneyOfstad** [comment] 2024-04-10 16:50
It shows that @mkhutornyi is out sick, so going to keep this open until they are back 👍

**Comment by CortneyOfstad** [comment] 2024-04-15 13:27
According to Slack @mkhutornyi is still sick, so continuing to keep this open 👍

**Comment by CortneyOfstad** [comment] 2024-04-24 14:15
@mkhutornyi — just checking to see if you're back? Thanks!

**Comment by CortneyOfstad** [comment] 2024-05-01 15:35
@mkhutornyi going to close this, feel free to reopen when you're back — hope all is well!

**Comment by mallenexpensify** [comment] 2024-06-06 00:01
@mkhutornyi is back! can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019b60b595b681eb92

@CortneyOfstad can you finish off payment once it's ready?

**Comment by CortneyOfstad** [comment] 2024-06-06 15:03
Welcome back @mkhutornyi!

**Comment by CortneyOfstad** [comment] 2024-06-07 15:17
## Payment Summary

@mkhutornyi — paid $500 via Upwork 
@abzokhattab — paid $500 via Upwork

**Closed by CortneyOfstad** 2024-06-07 15:17 UTC
Labels: External, Weekly, Awaiting Payment, Bug
