### ISSUE TITLE
[$250] Unresponsive 'Copy to Clipboard' Button for mentions

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42318] opened 2024-05-16 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1, Create a workspace and navigate to announcements.
2, Write "@" and select a mention (gmail alias accounts like xxx+1@gmail.com)
3, Reply to the mention.
4, Hover over the mention and attempt to click the "Copy to Clipboard" button.
5, Observe that the button is unresponsive.

## Expected Result:
The "Copy to Clipboard" button should respond when clicked after replying to a mentioned email.

## Actual Result:
The "Copy to Clipboard" button is unresponsive after replying to a mentioned email.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f6d90b61-b5a4-478f-aa9f-9ffc7310e8a9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4e1e6b437b0be1d</li>
        <li>Upwork Job ID: 1802759594328107652</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by m-natarajan** [comment] 2024-05-16 19:55
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-05-16 19:55
We think that this bug might be related to #vip-vsb

**Comment by ahmedGaber93** [comment] 2024-05-16 22:52
I think this is may be fixed here https://github.com/Expensify/App/issues/42161

**Comment by garrettmknight** [comment] 2024-05-17 16:36
Let's hold for that then.

**Comment by garrettmknight** [comment] 2024-05-20 18:11
Still holding on https://github.com/Expensify/App/issues/42161

**Comment by garrettmknight** [comment] 2024-05-22 19:38
Still holding on https://github.com/Expensify/App/issues/42161

**Comment by garrettmknight** [comment] 2024-05-28 19:42
Still holding on https://github.com/Expensify/App/issues/42161

**Comment by garrettmknight** [comment] 2024-06-03 18:53
Still holding on https://github.com/Expensify/App/issues/42161

**Comment by garrettmknight** [comment] 2024-06-12 20:07
Taking off hold and moving to daily to test.

**Comment by garrettmknight** [comment] 2024-06-17 17:45
Reproduced

**Comment by ikevin127** [comment] 2024-06-20 18:12
Looking for proposals.

**Comment by ikevin127** [comment] 2024-06-20 23:38
@garrettmknight I tried reproducing and I can't -> it works as expected on my side. Can you request a re-test of this and close it if not reproducible ?

**Comment by ikevin127** [comment] 2024-06-22 01:15
I cannot reproduce -> it works as expected on my side. I think the reason why there are no proposals so far is because contributors are not able to reproduce either.

Can we request a retest of this and close if not reproducible ?

| MacOS: Chrome |
| ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/be6a8f29-d733-4e30-9f61-ff3c7d030f75"> |

cc @garrettmknight

**Comment by ikevin127** [comment] 2024-06-24 18:45
I cannot reproduce -> it works as expected on my side. I think the reason why there are no proposals so far is because contributors are not able to reproduce either.

Can we request a retest of this and close if not reproducible ?

| MacOS: Chrome |
| ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/be6a8f29-d733-4e30-9f61-ff3c7d030f75"> |

cc @garrettmknight

**Comment by garrettmknight** [comment] 2024-06-24 19:25
Can't reproduce any longer - thanks for giving it a test @ikevin127

**Closed by garrettmknight** 2024-06-24 19:25 UTC
Labels: External, Daily, Help Wanted, Bug
