### ISSUE TITLE
[$500]  Request Money - Request money screen opens again on click of Next button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28129] opened 2023-09-25 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon
2. Select Request money option
3. Enter amount click on Next button
4. Select user
5. Click Add to Split
6. Click on back icon and go to Request money page
7. Edit amount and click on Next button

## Expected Result:
It should navigate to user selection screen

## Actual Result:
It navigates to Request money page with a 0 value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/84ed5d07-21b6-4f08-a6e7-1ab83c5eaa64

https://github.com/Expensify/App/assets/93399543/04b8b152-81e8-4d6a-9c2a-87693fa77c66

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695407645834009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bcacd63e5609ce5</li>
        <li>Upwork Job ID: 1706561388369063936</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-25 14:25
This isn't a deploy blocker anymore. I can reproduce it on NewDot.

**Comment by cristipaval** [comment] 2023-09-25 23:14
This is also reproducible in production

**Comment by peterdbarkerUK** [comment] 2023-09-26 06:44
Initial report [here](https://github.com/Expensify/App/issues/28129)

Subsequent report (generating this issue) [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695633108632789)

**Comment by cristipaval** [comment] 2023-09-28 16:09
@0xmiroslav are we still waiting for other proposals?

**Comment by paultsimura** [comment] 2023-09-30 12:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Coming back to the "Money request" page from the confirmation page reopens the screen on "Next" button.

### What is the root cause of that problem?
This indeed is a regression from https://github.com/Expensify/App/pull/27797.

#### The reason is the following:

When a participant option contains a reportID, we attach this reportID to IOU in onyx:

https://github.com/Expensify/App/blob/52f0e3c9ec9ab5c87993672661095f81253bc00d/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L67-L72

This reflects the behavior when the IOU request is initiated from a report, not FAB.

However, when we initiate the IOU request from a report, the route already contains the report ID (e.g. http://localhost:8082/request/new/6534842407219860/manual), while if we create the IOU request from FAB, the route contains no report ID (http://localhost:8082/request/new/manual).

So the faulty FAB flow in this issue is the following:

1. User initiates an IOU request with the following fresh IOU in Onyx:
<img width="650" alt="image" src="https://github.com/Expensify/App/assets/12595293/a9899105-5e2c-4def-be9b-46bf29d7d285">

2. Proceed to select a participant and click next. At this point, the `IOU` is updated with the new ID:
<img width="650" alt="image" src="https://github.com/Expensify/App/assets/12595293/254eef0f-15af-4e0a-a428-d57af723bde2">

3. Navigate back two times to the initial "Request Money" page. `IOU` stays the same – it contains the updated ID with `reportID` attached:
<img width="650" alt="image" src="https://github.com/Expensify/App/assets/12595293/6e4e7d5c-f7c6-48ef-a805-d8c74bc26c65">

4. Click "Next" which executes `IOU.navigateToNextPage(iou, iouType, report)`:
https://github.com/Expensify/App/blob/52f0e3c9ec9ab5c87993672661095f81253bc00d/src/pages/iou/steps/NewRequestAmountPage.js#L150

Inside this function, we have a conflict between a route `reportID` param (which is absent in `http://localhost:8082/request/new/participants/`) and the IOU reportID which is still appended with the reportID (attaching it as a screenshot to see the values from debugger):

<img width="750" alt="image" src="https://github.com/Expensify/App/assets/12595293/8d7da6f5-6378-4ca4-8ba7-7dbd49240a1f">

So we reset the IOU report and go back to the "Request money" page.

### What changes do you think we should make in order to solve the problem?

Similar to setting the IOU.setMoneyRequestId on moving forward from MoneyRequestParticipantsPage, we should revert it on coming back as we have no use of this report identifier on the "Initiate money request" page:

```diff
    const navigateBack = (forceFallback = false) => {
+       IOU.setMoneyRequestId(iouType.current);
        Navigation.goBack(ROUTES.MONEY_REQUEST.getRoute(iouType.current, reportID.current), forceFallback);
    };
```

### What alternative solutions did you explore? (Optional)

**Comment by cristipaval** [comment] 2023-10-02 09:47
bump @0xmiroslav

**Comment by paultsimura** [comment] 2023-10-03 17:57
> Please check this video

Good catch, thanks @0xmiroslav. What is the expected behavior for the manual URL change though: should we preserve the previously entered amount, or should we reset it?

**Comment by peterdbarkerUK** [comment] 2023-10-06 09:58
Agreed we should hold for the https://github.com/Expensify/App/issues/26538 refactor

**Comment by cristipaval** [comment] 2023-10-16 14:19
Still on hold.

**Comment by cristipaval** [comment] 2023-10-25 14:33
No update.

**Comment by peterdbarkerUK** [comment] 2023-11-03 17:24
PR should be out today!

**Comment by peterdbarkerUK** [comment] 2023-11-03 17:24
(For what we're holding on, not this)

**Comment by peterdbarkerUK** [comment] 2023-11-14 15:45
Still under review/testing

**Comment by peterdbarkerUK** [comment] 2023-11-24 14:30
I *think* https://github.com/Expensify/App/issues/26538 is now fully merged.

**Comment by paultsimura** [comment] 2023-11-25 11:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Coming back to the "Money request" page from the confirmation page reopens the screen on "Next" button.

### What is the root cause of that problem?
When navigating from the `MoneyRequestParticipantsPage` to `MoneyRequestConfirmPage`, we change the `IOU.id` using `IOU.setMoneyRequestId` here:

https://github.com/Expensify/App/blob/87c1967dcbd2727042cd087d911e22f9de0cdc17/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L88-L93

In case of a split operation, the `iou.id` will become `split`. Then, coming back, we do not reset the `iou.id` back to `request`.

When navigating back to the `NewRequestAmountPage` and proceeding to `MoneyRequestParticipantsPage`, we use this function for navigation:

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/pages/iou/steps/NewRequestAmountPage.js#L131-L142

As a result, when calculating `const shouldReset = iou.id !== moneyRequestID`, we compare `request` and `split`, so we force the IOU reset and navigate back to the initial page:

https://github.com/Expensify/App/blob/296fc6512c31f09c89b7e0b784db4f82ee360170/src/libs/actions/IOU.js#L2934-L2942

### What changes do you think we should make in order to solve the problem?
When on the `MoneyRequestParticipantsPage`, we don't actually care about the `iou.id` being `split` or `request`, as the URL param is `request` in both cases.

I suggest that we reset the `iou.id` to match the `iouType` (the URL param) when we navigate to the `MoneyRequestParticipantsPage`. For this, add a hook in `MoneyRequestParticipantsPage`:

```js
    useFocusEffect(
        useCallback(() => {
            IOU.setMoneyRequestId(iouType);
        }, [iouType])
    )
```

This hook will trigger once we navigate to the page. The simple `useEffect` with empty dependencies won't work since the component isn't unmounted on navigation between steps, only on the modal dismiss.

Also, we should add an extra check on the `MoneyRequestConfirmPage` to make sure the hook that handles the iou.id change is working only when we are actually on the `MoneyRequestConfirmPage`, because if we navigate back from it – the component will remain – and the hook will be triggered when the `iou.id` is changed:

```diff
+   const isFocused = useIsFocused();

    useEffect(() => {
+       if (!isFocused) {
+           return;
+       }

        // ID in Onyx could change by initiating a new request in a separate browser tab or completing a request
        if (!isDistanceRequest && prevMoneyRequestId.current !== props.iou.id) {
        ...
```

https://github.com/Expensify/App/blob/87c1967dcbd2727042cd087d911e22f9de0cdc17/src/pages/iou/steps/MoneyRequestConfirmPage.js#L114-L138

### What alternative solutions did you explore? (Optional)
My initial idea was to reset the iou.id when navigating back from the `MoneyRequestConfirmPage`, but as @0xmiroslav pointed out, this won't cover the case when we navigate using the in-browser navigation.

**Comment by paultsimura** [comment] 2023-11-25 13:27
@peterdbarkerUK indeed, the PR we were holding for is now merged. The issue still remains, just with a slightly different root cause.

**Comment by FitseTLT** [comment] 2023-11-28 19:56
Isn't this [duplicate](https://github.com/Expensify/App/issues/30060)??

**Comment by paultsimura** [comment] 2023-11-28 20:14
> Isn't this [duplicate](https://github.com/Expensify/App/issues/30060)??

Seems like. But that issue was opened on Oct 10, while this – on Sep 25. According to the rules, that one should be closed in favor of this.

**Comment by cristipaval** [comment] 2023-11-29 13:40
This one needs C+ review, correct?

**Comment by cristipaval** [comment] 2023-12-04 13:18
friendly bump @0xmiroslav

**Comment by cristipaval** [comment] 2023-12-07 18:24
bumped @0xmiroslav on Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1701973438850959)

**Comment by cristipaval** [comment] 2023-12-08 21:05
alright, thank you @0xmiroslav!

**Closed by cristipaval** 2023-12-08 21:05 UTC
Labels: External, Daily, Help Wanted, Bug
