### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-02] Android - Private notes - Code block creates empty lines below it in the note preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27802] opened 2023-09-19 17:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat > chat header > Private note > My note
3. Create multiple lines
4. Add a code block markdown in the middle
5. Save it

## Expected Result:
The code block does not create empty lines below it in the note preview

## Actual Result:
The code block creates empty lines below it in the note preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/93c5ccef-766d-4dd5-8fa3-65a1eeca24a5

https://github.com/Expensify/App/assets/78819774/7df17097-090c-4d96-b55f-be2299141cb9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-09-19 18:18
Being Fixed here:
- https://github.com/Expensify/App/pull/27769

**Comment by maddylewis** [comment] 2023-09-20 18:33
@jasperhuangg - i don't think any BZ action is required, but lmk if you need me to do something for this one!

**Comment by maddylewis** [comment] 2023-10-02 14:07
no payments are required for this issue (internal). 

@jasperhuangg - do you need to do anything with this checklist? https://github.com/Expensify/App/issues/27802#issuecomment-1733282072

and, if there are no regressions, can i close this bb out?

**Comment by garrettmknight** [comment] 2023-10-11 20:07
@burczu mentioned that https://github.com/Expensify/App/issues/28623 looks like a regressions from this PR. @jeet-dhandha can you take a look and fix?

**Comment by jeet-dhandha** [comment] 2023-10-11 23:58
@garrettmknight can you re-test the latest `main` for above mentioned issue ? As it should be fix in the PR just above ur comment.

**Comment by jeet-dhandha** [comment] 2023-10-11 23:58
Also issue is mentioned there too.

**Comment by maddylewis** [comment] 2023-10-25 16:17
@jasperhuangg - is this fixed? can i close?

**Comment by jasperhuangg** [comment] 2023-10-25 16:32
It looks like @jeet-dhandha submitted a PR, and @burczu was the reviewer.

I'm not sure if they've been paid out yet.

**Closed** 2023-11-08 23:06 UTC
Labels: Engineering, Weekly, Overdue, Awaiting Payment, Bug
