### ISSUE TITLE
[$500] Web - Scroll speed has dramatically reduced in NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31402] opened 2023-11-15 19:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699742883368309

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Open any chat conversation
4. Scroll the content using two-finger drag

## Expected Result:
Scroll speed should be the same as in Slack

## Actual Result:
Scroll speed has dramatically reduced in NewDot

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8b05be6b-f6c8-4156-8bed-9301c26e43ba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df590e04409cd112</li>
        <li>Upwork Job ID: 1724876585592717312</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by kakajann** [comment] 2023-11-15 20:51
Just to make sure... Do you want a momentum scroll?

**Comment by kakajann** [comment] 2023-11-15 21:03
Contributor details
Your Expensify account email: kakajanxxx@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0170cd9e3e2cc5613d

**Comment by rushatgabhane** [comment] 2023-11-20 04:05
> After research, I came to the conclusion that the main problem is using the inverted  property for FlatList
Apparently due to the fact that our elements are inverted, this affects the scrolling speed of the list

@ZhenjaHorbach the inverted prop was there from the beginning. However this bug is very recent. So the suggested root cause shouldn't be correct.
Could you please dive deeper into the root cause and explain it in detail.

**Comment by kaushiktd** [comment] 2023-11-20 11:26
### Please re-state the problem that we are trying to solve in this issue.
Web - Scroll speed has dramatically reduced in NewDot

### What is the root cause of that problem?
Optimize the `handleScroll` function within the `InvertedFlatList` component by simplifying the timeout and event handling mechanisms

### What changes do you think we should make in order to solve the problem?
filePath:- https://github.com/Expensify/App/blob/main/src/components/InvertedFlatList/index.js#L82
Removed the condition that checks for `lastScrollEvent.current` and the associated timestamp comparison. This simplification avoids unnecessary complexity by directly setting the `scrollEndTimeout` whenever a scroll event occurs.
Consolidated the timeout logic to call `onScrollEnd` directly after the specified duration (250 milliseconds in this example). Adjust the timeout duration as needed based on your requirements for detecting the end of scrolling.
```
const handleScroll = (event) => {
  onScroll(event);

  if (scrollEndTimeout.current) {
    clearTimeout(scrollEndTimeout.current);
  }

  scrollEndTimeout.current = setTimeout(() => {
    onScrollEnd();
  }, 250); // Adjust the timeout duration if needed
};
```


### Video:-
https://drive.google.com/file/d/1wPzTbIqzeAXdUsMXc6vrUOAwvtCs_5nu/view?usp=sharing

**Comment by rushatgabhane** [comment] 2023-11-21 20:37
https://github.com/Expensify/App/issues/31402#issuecomment-1814988967

PR that caused the issue - https://github.com/Expensify/App/pull/24482
Line that caused the issue - https://github.com/Expensify/App/blob/main/patches/react-native-web%2B0.19.9%2B002%2Bfix-mvcp.patch#L89



C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2023-11-21 20:42
@joelbettner how do we proceed? is it as simple as removing 0.5 from this line?

https://github.com/Expensify/App/blob/main/patches/react-native-web%2B0.19.9%2B002%2Bfix-mvcp.patch#L89

**Comment by getusha** [comment] 2023-11-23 19:11
@rushatgabhane could you check my comment here? https://github.com/Expensify/App/pull/24482#discussion_r1401169575

**Comment by JmillsExpensify** [comment] 2023-11-24 19:47
Still discussing approach

**Comment by JmillsExpensify** [comment] 2023-11-29 00:23
@joelbettner mind weighing in so that we can move to the PR stage?

**Comment by JmillsExpensify** [comment] 2023-12-06 01:52
@joelbettner bump on that last question? I'm also going to reach out to you over chat to make sure you've seen this.

**Comment by joelbettner** [comment] 2023-12-06 05:20
Hey all...

I'm actually not so sure that this is a bug or something we want to fix. The scroll speed, honestly seems fine to me. If we don't have to change the code from the react native patch...I think we should leave that alone.

@JmillsExpensify I tested this and didn't really notice the scroll speed being an issue. What do you think?

**Comment by joelbettner** [comment] 2023-12-11 19:19
Hearing no objections, I'm going to close this issue. Reopen it if you disagree.

**Closed by joelbettner** 2023-12-11 19:19 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
