### ISSUE TITLE
Bank acount  - Infinite loading & BA account page does not load after user is back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36478] opened 2024-02-14 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4311372&group_by=cases:section_id&group_order=asc&group_id=283225
**Email or phone of affected tester (no customers):** applausetester+ck1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Click bottom right wrench settings icon
4. Click New Workspace button
5. Disable the internet connection in device
6. Select Bank account option in WS settings
7. Select Connect online with Plaid (Note : Message appears that this feature is only available when online)
8. Enable the internet connection

## Expected Result:
User redirected to connect plaid bank flow once the internet is back

## Actual Result:
Infinite loading & BA account page does not load after user is back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8fdfb07b-0e60-4abd-ad47-79f16363e174

https://github.com/Expensify/App/assets/78819774/977d7a2a-d1ae-4692-b69b-37e757e1161f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2024-02-14 14:10
Noted in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1707919815149159?thread_ts=1707829954.739589&cid=C01GTK53T8Q

**Comment by mountiny** [comment] 2024-02-14 14:16
Dupe of https://github.com/Expensify/App/issues/36479

**Closed by mountiny** 2024-02-14 14:16 UTC
Labels: DeployBlockerCash, Engineering, Hourly
