### ISSUE TITLE
[$500] IOU- When replacing receipt and downloading it, previous receipt with new receipt name is downloaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33363] opened 2023-12-20 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to IOU request details that has a receipt
2. Click on the receipt
3. Click 3-dot menu > Replace
4. Upload another receipt
5. After the upload is complete, download the receipt

## Expected Result:
The latest receipt will be downloaded

## Actual Result:
The previous receipt is downloaded, while the receipt file name is the name of the latest receipt
On Android and iOS app, it downloads the previous receipt (file name is not affected/not relevant) after replacing the receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9832528f-9c30-42c3-a343-7921ac46c0dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113378cba031fc595</li>
        <li>Upwork Job ID: 1737485735446364160</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28077368</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by namhihi237** [comment] 2023-12-20 15:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The link source download does not update when replace the image
### What is the root cause of that problem?
Currently, when the source changes we don't update in the `threeDotsMenuItems`.
### What changes do you think we should make in order to solve the problem?
We should add the `source` into dependence 
### What alternative solutions did you explore? (Optional)

**Comment by vikssevishnu** [comment] 2023-12-20 15:07
I am trying to access the issue details using the link "https://stackoverflow.com/c/expensify/questions/14418" but i am getting you do not have access. Can you help on it ?

**Comment by vikssevishnu** [comment] 2023-12-20 15:11
Contributor details
Your Expensify account email: vishnu.vikas19@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a59961216a1ee633?viewMode=1

**Comment by situchan** [comment] 2023-12-20 15:51
This is regression from #32647 which fixes #31105 (confirmed by reverting locally)
It's still within regression period

**Comment by shubham1206agra** [comment] 2023-12-20 16:04
In that case, @dukenv0307 please create a quick PR for this

**Comment by alexpensify** [comment] 2023-12-20 23:59
@abdulrahuman5196 should we close these GHs in favor of what @situchan mentioned above or move forward with the proposal review?

**Comment by alexpensify** [comment] 2023-12-23 18:32
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by abdulrahuman5196** [comment] 2024-01-02 17:49
> @abdulrahuman5196 should we close these GHs in favor of what @situchan mentioned above or move forward with the proposal review?

@alexpensify We can close this issue, given the PR was merged. This was a regression fix.

**Comment by alexpensify** [comment] 2024-01-03 17:22
👍🏼 - closing

**Closed by alexpensify** 2024-01-03 17:22 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by alexpensify** [comment] 2024-01-09 01:08
@shubham1206agra - can you please identify if this PR triggered the deploy blocker or if there is another reason for this update? Thanks!

**Comment by shubham1206agra** [comment] 2024-01-09 03:12
Oh it's a false alert actually

**Comment by alexpensify** [comment] 2024-01-09 16:11
@shubham1206agra - can you please share more context as to why the alert is wrong? It will be helpful to have it recorded. Thanks!

**Comment by shubham1206agra** [comment] 2024-01-09 16:14
@alexpensify https://github.com/Expensify/App/pull/33586 is the offending PR. Some contributor marked this by mistake as this issue is already deployed to production.

**Comment by alexpensify** [comment] 2024-01-09 16:15
Thank you! I will continue the process to prepare for the payment date.

**Comment by alexpensify** [comment] 2024-01-11 21:30
Based on the 👎🏼 here https://github.com/Expensify/App/issues/33363#issuecomment-1874209603 and the note here https://github.com/Expensify/App/issues/33363#issuecomment-1874348862, there is no payment action here since this issue was handled in other GH.
