### ISSUE TITLE
[HOLD $1000] Date picker doesn’t show after focus on another field and press Fix the error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14529] opened 2023-01-24 23:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Settings -> Workspaces => Connect Bank Account Manually => Enter invalid information for only Date of birth at step 3.
2. Now press Save & Continue, an error will show up, focus on SSN field (or any field), scroll down and press Fix the error, scroll up and press the Date picker.
3. Notice that Date picker is not responding.

## Expected Result:
Date picker should show up at the bottom and respond to click

## Actual Result:
Nothing happened after pressing Date picker field.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.58-2
**Reproducible in staging?:** y
**Reproducible in production?:** could not check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/214443204-595bd497-a7c1-4390-87fa-c2d14aa20baa.MP4

https://user-images.githubusercontent.com/43996225/214443300-b67529bf-df10-4b8e-8714-5f18a3cdaa03.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674326036607849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c59fc18f15ea7403</li>
        <li>Upwork Job ID: 1618921611535593472</li>
        <li>Last Price Increase: 2023-02-03</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-01-25 02:03
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by greg-schroeder** [comment] 2023-01-25 02:08
Not sure about the reproduction steps, asked in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1674612502037579?thread_ts=1674326036.607849&cid=C049HHMV9SM

**Comment by greg-schroeder** [comment] 2023-01-27 10:39
Okay, got a bit more detail about the reproduction and also adjusted the OP a little bit

**Comment by s77rt** [comment] 2023-01-27 11:27
Should be on hold in favor of https://github.com/Expensify/App/issues/14322

**Comment by marcaaron** [comment] 2023-01-27 21:15
I'm pretty confused actually. In both of the example videos I don't see this happening:

>Nothing happened after pressing Date picker field.

The date picker is unresponsive when the user tried to interact with it?

Can someone post a better video that clearly shows this behavior?

**Comment by marcaaron** [comment] 2023-01-27 21:20
@s77rt I'm reluctant to put this on HOLD as it's not clear when exactly those design improvements would be made to this particular flow.

**Comment by s77rt** [comment] 2023-01-27 21:33
@marcaaron 

#### Actual Result

https://user-images.githubusercontent.com/16493223/215204671-8c719c71-b8f3-45f2-8cd7-be0dbaebe4e1.mp4




#### Expected Result

https://user-images.githubusercontent.com/16493223/215204696-96b3d932-3315-4610-9637-f9ce95827c28.mp4

**Comment by marcaaron** [comment] 2023-01-27 21:52
So the issue is that the menu doesn't open but the field gets focus? I'm still not sure because the description of the issue says:

>Nothing happened after pressing Date picker field.

I don't see the date picker field getting "pressed"

**Comment by s77rt** [comment] 2023-01-27 22:14
@marcaaron Ah my bad, I got it wrong, it's a bug.

If you click on fix the errors while focusing on another input and this takes you to the date picker, the date picker won't actually get focused (date picker won't show up) and even if you try to click on it, it won't show up either.
You will have to focus on another element first then you will be able to open date picker.




https://user-images.githubusercontent.com/16493223/215214698-25f62dc7-4fff-4caf-97cd-2221370a8236.mp4

**Comment by marcaaron** [comment] 2023-01-30 19:58
@fedirjh I would suggest organizing your proposal like this:

- Some clear explanation of the **root cause**.
- Solution in text (English) and **how it addresses the root cause**.
- Please do not provide code diffs and use pseudocode if necessary.

Thanks!

**Comment by s77rt** [comment] 2023-01-30 21:50
@marcaaron Shouldn't we put this on hold instead?

**Comment by marcaaron** [comment] 2023-01-30 23:35
>To Show Date picker at the bottom , we should to add a focus handler that will trigger this.showPicker (this is missing in the actual code) . However when TextInput prop editable is set to false, then the focus event is disabled

Sorry, this still sounds like a solution. Can you try to explain what the **problem** is without saying how to fix it at all?

**Comment by marcaaron** [comment] 2023-01-31 01:38
>The date picker isn't focusable

Can you be more specific here? The date picker on iOS and Android both have `TextInput`. Are you saying we can't focus that? There is an `onFocus` event [here](https://reactnative.dev/docs/0.70/textinput#onfocus).

>The 2nd part even if we add focus handler to show datepicker it will never work.

Why will it never work?

>Edit : the Form uses the focus event to focus errored inputs . Datepicker isn't focusable that's the issue here.

Sorry, I don't understand what you mean at all. Can you try saying it another way?

**Comment by mdneyazahmad** [comment] 2023-01-31 08:31
## Proposal

When editable property is not set on TextInput. This will not be focused, and onPressOut (BaseTextInput) will not be called by tapping. We can do the following to replace editable property.

https://github.com/Expensify/App/blob/f624d828408543e64422c18a5156ec3e493c0253/src/components/DatePicker/index.ios.js#L94

https://github.com/Expensify/App/blob/f624d828408543e64422c18a5156ec3e493c0253/src/components/TextInput/BaseTextInput.js#L299

```diff
- editable={false}
+ readOnly
+ caretHidden
```

This does not stop focusing on the TextInput, and onPressOut will be called that in turn will show the date picker.


https://user-images.githubusercontent.com/77761491/215706972-08b0b108-b143-4219-b56d-99cd96faacd1.mp4

Note: I have changed the border colour to make it clearly see the focused state.

BUG: I will also raise an issue here. If an input is having error. It does not have different outline colour to differentiate the focused state. Like this


https://user-images.githubusercontent.com/77761491/215708325-a6fc33ce-6663-4619-a6a8-f3168221159c.mov

**Comment by marcaaron** [comment] 2023-01-31 17:25
Maybe I am missing something obvious. But I have a few thoughts:

- the `focus()` method can be whatever we want it to be on the `DatePicker` component. it doesn't need to have anything to do with the `TextInput` at all. It's just a method that we could implement to show the `DatePicker`.
- I'm not sure anyone has addressed why tapping on the field after tapping on "Fix the errors" has "no effect" it seems like there was a suggestion that this is broken. I have not seen anyone mention this in their proposals to fix the problem.

So, can someone please clarify what exactly we are fixing in this issue?

@parasharrajat I would suggest to not review any of the current proposals until there is a consensus about _what_ we are fixing and a clear explanation of the root cause. I'm going to go through and hide them so it's easier for us to focus on that.

**Comment by marcaaron** [comment] 2023-02-03 19:55
Gonna put this issue on HOLD until we can clarify what the bug actually is. I don't agree with the doubling that just happened above since so far we have just been trying to establish **what _exactly_ we are fixing**.

**Comment by marcaaron** [comment] 2023-02-03 19:57
Actually I'm going to kick this one back to Slack. If there are 2 bugs lets report them separately and restart the conversation here.

**Closed by marcaaron** 2023-02-03 19:57 UTC
Labels: External, Daily, Help Wanted, Bug
