### ISSUE TITLE
[HOLD for payment 2024-07-17][$250] Fallback avatar- The background of fallback avatar has the same color as selection highlight

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39909] opened 2024-04-09 09:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/38674
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Go offline.
4. Type @ and search for user that shows the fallback avatar in offline mode.
5. Use keyboard key to highlight the selection.

## Expected Result:
The background of the fallback avatar should be visible when the user with fallback avatar is highlighted in the suggestion list.

## Actual Result:
The background of the fallback avatar has the color as the selection highlight, so the background appears invisible when it is highlighted. This issue occurs in both light and dark mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/97cf8ee3-7ee4-4dbb-bafb-f5277f0472df

<img width="1440" alt="Bug6443096_1712637992472!Screenshot_2024-04-09_at_12 40 27" src="https://github.com/Expensify/App/assets/115492554/82b8e7ce-1b07-44f3-adb0-3d2abcd821ba">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d901ad4a12b6e9e</li>
        <li>Upwork Job ID: 1777661865535434752</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
<li>eh2077 | Contributor | 102899881</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by izarutskaya** [comment] 2024-04-09 09:58
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-09 09:58
Production 


https://github.com/Expensify/App/assets/115492554/d5f08276-b24a-4ad0-b75d-d66805cd0b63

**Comment by Beamanator** [comment] 2024-04-09 11:35
cc @grgia - since you're the author of https://github.com/Expensify/App/pull/38674 - do you agree with the proposal above to fix this deploy blocker? Do you want to take over this issue? Looks like a quick fix

**Comment by grgia** [comment] 2024-04-09 11:36
Yeah! Exactly what I was going to suggest. All yours @tienifr, but removing the blocker label

**Comment by Santhosh-Sellavel** [comment] 2024-04-21 17:13
@grgia Assign me issue for tracking payment

**Comment by kevinksullivan** [comment] 2024-04-30 21:08
It seems we're still having this issue here

https://github.com/Expensify/App/issues/40992

Should we tackle the fix in this GH?

**Comment by Santhosh-Sellavel** [comment] 2024-05-01 19:31
@tienifr please check

**Comment by kevinksullivan** [comment] 2024-05-09 21:19
@grgia @tienifr bumping this

https://github.com/Expensify/App/issues/39909#issuecomment-2087325422

**Comment by grgia** [comment] 2024-05-22 08:10
I think we will update the fallback icon color but let's have design confirm @tienifr.

cc @Expensify/design could you confirm if we should update the row highlight color here?

**Comment by shawnborton** [comment] 2024-05-23 09:04
I agree we want this to match the change we previously made for fall back avatars.

**Comment by shawnborton** [comment] 2024-06-03 09:30
I think we settled on using `buttonHoveredBG` for fallback avatar BG color. Does that sound right @Expensify/design? I see it coming from this PR at least: https://github.com/Expensify/App/pull/39950/files

**Comment by shawnborton** [comment] 2024-06-03 09:30
But... we already merged that PR, so maybe this bug is fixed?

**Comment by shawnborton** [comment] 2024-06-03 09:38
Are you sure? I feel like our row highlight color is working as expected. I think we need new screenshots given that the original screenshots were from April 9 and before your change was merged. I have a feeling this one can just be closed now.

**Comment by shawnborton** [comment] 2024-06-03 09:43
Got it, thanks for confirming. I think the idea is that the :active row color should use the same color as our border color, which is product400. Can you try that and see how it goes?

**Comment by shawnborton** [comment] 2024-06-03 09:49
Cool, I think that one looks correct to me.

**Comment by dannymcclain** [comment] 2024-06-03 13:20
>Cool, I think that one looks correct to me.

Same.

**Comment by abekkala** [comment] 2024-06-11 18:50
@Santhosh-Sellavel can you please review the PR above?

**Comment by abekkala** [comment] 2024-06-25 15:08
@Santhosh-Sellavel please review asap

**Comment by abekkala** [comment] 2024-06-26 18:39
https://expensify.slack.com/archives/C02NK2DQWUX/p1719427131013149

**Comment by iCodePrograms** [comment] 2024-06-26 22:38
Hi guys, found this post on Upwork. I see we have a possible solution given for the task already. Let me know if it not solved
A free advice if it helps: Whenever dealing with icons in particular, in case of dynamically created background colors(or different colors in different pages) have borders of the opposite spectrum so it never blends with the background.

**Comment by eh2077** [comment] 2024-06-26 23:21
@abekkala I can help with this as C+ if @Santhosh-Sellavel won't be available soon.

Cc @shawnborton

**Comment by abekkala** [comment] 2024-06-27 12:48
I've assigned you for review @eh2077

**Comment by eh2077** [comment] 2024-06-27 13:31
@abekkala Sorry, I just found that @rushatgabhane already reviewed the PR https://github.com/Expensify/App/pull/43077#issuecomment-2192417925. So I'm going to unassign myself from this.

**Comment by abekkala** [comment] 2024-07-10 15:09
### PAYMENT SUMMARY FOR JULY 17

- Fix: @tienifr [$250, if no regressions] payment via NewDot
- PR Review: @rushatgabhane  [$250, if no regressions] payment via NewDot

**Comment by abekkala** [comment] 2024-07-16 14:08
### PAYMENT SUMMARY FOR JULY 22

- Fix: @tienifr [$250, if no regressions] payment via NewDot
- PR Review: @rushatgabhane [$250, if no regressions] payment via NewDot

**Comment by abekkala** [comment] 2024-07-18 14:01
This was not a regression - ready for payment!

**Comment by abekkala** [comment] 2024-07-18 14:04
### PAYMENT SUMMARY FOR JULY 17

- Fix: @tienifr [$250, if no regressions] payment via NewDot
- PR Review: @rushatgabhane [$250, if no regressions] payment via NewDot
@rushatgabhane can you complete the checklist?

**Comment by abekkala** [comment] 2024-07-19 15:43
@rushatgabhane can you please complete the checklist above?

**Closed** 2024-07-22 15:28 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-22 16:28
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment] 2024-07-25 02:12
$250 approved for @tienifr
