### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Add payment method popover has wrong position

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26070] opened 2023-08-28 11:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On A, request money from B
2. On B, go to IOU report
3. On report header, click pay button and then click arrow button
4. Observe popover positions
## Expected Result: 
Popover should show below button
## Actual Result: 
Popover overlaps with button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/acf45e6a-e4e6-4173-8157-66d9a23c0d3d

https://github.com/Expensify/App/assets/43996225/27685809-7172-493c-a8e9-49f52651a633

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692363288571469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a94242021f694c9e</li>
        <li>Upwork Job ID: 1697388288553955328</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26993215</li>
<li>Nikhil-Vats | Contributor | 26993216</li>
<li>aimane-chnaif | Reporter | 26993217</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-08-28 16:04
## Proposal

### Please state again the problem we are trying to solve in this issue.
Add payment method popover has wrong position.

### What is the cause of this issue?
We does not pass `anchorAlignment` to `PopoverMenu` in `AddPaymentMethodMenu`.

And after redesign money request report, calculating anchor position in `getAnchorPosition` does not updated.

### What changes do you think we should make to solve the problem?
First, we should pass `anchorAlignment` to `KYCWall`, `AddPaymentMethodMenu` and `PopoverMenu`.
* In `SettlementButton.js`
```js
	<KYCWall
    ...
+       anchorAlignment={this.props.anchorAlignment}
	>
```
* In `BaseKYCWall.js`
```js
	<AddPaymentMethodMenu
    ...
+       anchorAlignment={this.props.anchorAlignment}
	>
* In `AddPaymentMethodMenu.js`
```js
	<PopoverMenu
    ...
+       anchorAlignment={this.props.anchorAlignment}
	>
Second, we should update anchor position calculating in `getAnchorPosition` function.
We can modify calculating like drop down menu as below.
```js
    getAnchorPosition(domRect) {
        return {
            anchorPositionVertical: this.props.anchorAlignment.vertical === CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP
                ? domRect.top + domRect.height + CONST.MODAL.POPOVER_MENU_PADDING
                : domRect.top - CONST.MODAL.POPOVER_MENU_PADDING,
            anchorPositionHorizontal: domRect.left + domRect.width,
        };
    }
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by alexpensify** [comment] 2023-08-30 01:25
I'm catching up from being OOO, I will test soon.

**Comment by alexpensify** [comment] 2023-08-31 23:18
@aimane-chnaif - let's solve this bug! I've assigned the issue to you.

**Comment by alexpensify** [comment] 2023-09-04 23:06
@aimane-chnaif - When you get a chance, can you look at the proposals to identify if one will fix this issue? Thanks!

**Comment by alexpensify** [comment] 2023-09-06 21:33
@aimane-chnaif - any update here?

**Comment by Pujan92** [comment] 2023-09-07 16:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Popover for the transfer balance opens on incorrect place

### What is the root cause of that problem?
Default vertical `anchorAlignment` is bottom which means it won't open below the passed anchor. And we are not passing `anchorAlignment` values from `BaseKYCWall` component.

https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/KYCWall/BaseKYCWall.js#L137-L145

### What changes do you think we should make in order to solve the problem?

1. Pass `anchorAlignment` in `AddPaymentMethodMenu` by setting the vertical field to `TOP` and also add props in `AddPaymentMethodMenu` to receive which will eventually pass it to the `PopoverMenu`.

```
 anchorAlignment={{
      horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
      vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP, // we assume that popover menu opens below the anchor, anchor is at TOP
 }}
```
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/KYCWall/BaseKYCWall.js#L137-L145

2. Now we need to correct the `anchorPosition` for the `anchorPositionVertical` and that needs to be the bottom of the anchor ref + 6px for some space between menuitem and popver.
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/KYCWall/BaseKYCWall.js#L67

```
anchorPositionVertical: domRect.bottom + 6,
```

3. Inside the MenuItem we have different elements and on click of those it won't open the popover below the MenuItem instead it opens below the clicked target(for eg. menuItem text, icons). To fix we need to pass the MenuItem ref for clickedElementLocation instead of clicked target ref.

```
const clickedElementLocation = getClickedTargetLocation(this.anchorRef.current);
```
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/KYCWall/BaseKYCWall.js#L113

https://github.com/Expensify/App/assets/14358475/24d3c444-14d2-41ce-b3b3-1921c1f9f126

- We need to make a dynamic prop called `popoverPlacement` inside `SettlementButton` and expect it from the parent as the same component we are using to show the popover either top(`ReportPreview`) or bottom(transfer balance and `MoneyReportHeader`).

**Comment by alexpensify** [comment] 2023-09-11 22:17
@aimane-chnaif have you been able to review the recent proposals? Thanks!

**Comment by alexpensify** [comment] 2023-09-20 14:22
@aimane-chnaif - any feedback here from your research?

**Comment by StevenKKC** [comment] 2023-09-20 18:50
@aimane-chnaif I have missed `popoverPlacement`.

**Comment by alexpensify** [comment] 2023-09-25 08:24
@aimane-chnaif - what's the next step here? It looks like @StevenKKC replied to your question.

**Comment by alexpensify** [comment] 2023-09-27 08:06
@aimane-chnaif - we need your feedback to continue forward. Thanks!

**Comment by alexpensify** [comment] 2023-09-29 06:04
@aimane-chnaif - any update here?

**Comment by alexpensify** [comment] 2023-10-04 22:19
Awesome, looks like the PR is ready for review.

**Comment by alexpensify** [comment] 2023-10-17 14:08
I will work on the payment process today

**Comment by alexpensify** [comment] 2023-10-18 00:38
Here is the payment summary: 

-  External issue reporter @aimane-chnaif $50
-  Contributor that fixed the issue @Nikhil-Vats $1000
-  Contributor+ that helped on the issue and/or PR @aimane-chnaif $1000

Upwork Job: https://www.upwork.com/jobs/~01a94242021f694c9e

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: https://github.com/Expensify/App/issues/26070#issuecomment-1749480156 there is an urgency bonus and no regression. I'm going to factor these into the final payments.

**Comment by alexpensify** [comment] 2023-10-18 21:57
Alright, @aimane-chnaif you've been paid via Upwork for reporting and C+. Please complete the checklist, thanks! I want to close this GH asap.

**Closed** 2023-10-19 16:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
