### ISSUE TITLE
IOS - Attachment inconsistency for Photo/Video

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23435] opened 2023-07-23 19:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + button -> Click Add attachment
3. It shows only take photo option

## Expected Result:
 It should allow capture and record photo or video

## Actual Result:
It only allow to capture photo

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ffa9b995-d578-4cdd-9c26-8e03a5f135c1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689949453779089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment] 2023-07-23 19:17
Same behaviour for Android and the text says Take photo, is it really a bug ?

**Comment by ygshbht** [comment] 2023-07-24 09:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is an inconsistency in the attachment functionality for Photo/ Video on native mobile devices. Currently, when a user attempts to add an attachment, they are only presented with the **Take Photo** option. The expected result is that users should be able to capture and record both photos and videos.

### What is the root cause of that problem?
The `AttachmentPicker` component in `ReportActionCompose` is not supplied with the `type` prop, and by default, this prop is set to `mixed` which supports both video and image types. However, this default behavior may not be supported on some  devices, which results in the observed issue.

https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/home/report/ReportActionCompose.js#L1013-L1017

### What changes do you think we should make in order to solve the problem?
We could consider refining the implementation to account for potential unsupported cases. This would involve adjusting the `type` prop depending on whether the user intends to upload an image or a video, while incorporating a fallback mechanism. The `getImagePickerOptions` function could be modified to include this fallback as follows:

https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/components/AttachmentPicker/index.native.js#L46-L53

```
function getImagePickerOptions(type) {
    // If the type is image, set mediaType as 'photo', 
    // if it's video, set mediaType as 'video', 
    // else for any other types or in the absence of type, set it to 'mixed'
    const mediaType = type === CONST.ATTACHMENT_PICKER_TYPE.IMAGE ? 'photo' : type === CONST.ATTACHMENT_PICKER_TYPE.VIDEO ? 'video' : 'mixed';
    return {
        mediaType,
        ...imagePickerOptions,
    };
}
```

Corresponding changes can be made at other places. This way, when a user wants to upload a video, we pass `video` as the type prop, and the `getImagePickerOptions` function will accordingly set the mediaType as 'video'. Similarly, when the user wants to upload a photo, `photo` will be set as the mediaType. This change should ensure that the attachment picker operates consistently across different devices.

**Comment by adelekennedy** [comment] 2023-07-25 21:15
Agree that this is a new feature, so from the SO:
>BZ triages, and verifies that this is in fact something that solves a problem, that we want to implement it, and whether it's a simple change.
If this NewFeature comes from internal person and it was already agreed on in Slack thread, you might skip over the WN post. Use your judgement and feel free to discuss this with the person who proposed the change in terms of how "big" the new feature is. Not every new feature requires WN post.

1. From there, it's up to BZ if they want to push the feature forward, so they can either:
2. Write WN post and own the project.
3. Search for volunteers.
4. Un-assign to the pool, so it's ready to be picked up if/when someone wants to implement it.

**Comment by adelekennedy** [comment] 2023-07-25 21:20
This is not a bug, def a new feature - I don't think this is a priority at the moment so following the SO I'm going to unassign

**Closed** 2023-07-25 21:20 UTC
Labels: Daily, NewFeature, Bug
