### ISSUE TITLE
[$500] LHN - First line and second line of the message are visible on LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35596] opened 2024-02-01 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4262578&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with the following account - [applausetester+multiline@applause.expensifail.com](mailto:applausetester+multiline@applause.expensifail.com)
2. Once logged in navigate to each of the conversations available (multiline+1 to multiline+9) and check LHN
3. Verify each of the multiline preview messages are displayed correctly in the LHN, only the first line of the message should be visible

## Expected Result:
Only the first line of the message should be visible on LHN

## Actual Result:
First line and second line of the message are visible on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/6d34f32b-fc8e-45b5-8da6-5ee6c461e075)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be20407fd253f3da</li>
        <li>Upwork Job ID: 1753175258047799296</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-02 13:03
This is intentional behavior that aligns with other social media apps; when the last message has text with line breaks it will be joined with space and displayed on the last message preview.

**Comment by puneetlath** [comment] 2024-02-02 22:23
Hmm, I agree. I think this is the intentional behavior. 

@kbecciv is the expected behavior from a regression test?

**Comment by puneetlath** [comment] 2024-02-13 21:55
Ok, seems like a legit bug then. @kbecciv would you mind confirming if you're still seeing the issue?

**Comment by kbecciv** [comment] 2024-02-14 16:22
@puneetlath Checking

**Comment by kbecciv** [comment] 2024-02-14 17:16
Issue is still reproducible
![image (7)](https://github.com/Expensify/App/assets/93399543/bfb76287-0a78-4021-8d1c-88dfbf300455)

**Comment by godofoutcasts94** [comment] 2024-02-14 17:48
Can't login using this account - [applausetester+multiline@applause.expensifail.com](mailto:applausetester+multiline@applause.expensifail.com)

**Comment by puneetlath** [comment] 2024-02-14 20:09
You don't need to be able to log in. You can see in the screenshot what the message is like.

**Comment by godofoutcasts94** [comment] 2024-02-14 20:10
okay, thanks for updating

**Comment by akinwale** [comment] 2024-02-19 10:39
We can move forward with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/35596#issuecomment-1923244586) here.

@dukenv0307 Please compare the performance difference between splitting the string and using a substring from the start index to the first newline and implement whichever approach is faster.

🎀👀🎀 C+ reviewed.

**Comment by puneetlath** [comment] 2024-02-20 20:12
Hmm, so the proposal makes sense, but why did this start happening all of a sudden? Do we know why this was working before and now isn't?

**Comment by puneetlath** [comment] 2024-02-28 14:59
Sorry for the delay. Let's go ahead.

**Comment by puneetlath** [comment] 2024-02-29 16:08
@dukenv0307 is working on it. @dukenv0307 do you have an ETA?

**Comment by puneetlath** [comment] 2024-08-07 19:53
Asking for a re-test to see if this is still occurring.

**Comment by m-natarajan** [comment] 2024-08-09 00:38
Still reproducible 
![image (2)](https://github.com/user-attachments/assets/c811ad3a-a017-4c62-95b5-c57f638bd8fd)

**Comment by puneetlath** [comment] 2024-09-11 15:29
Will try to get to it at some point, but it's really not high priority.

**Comment by puneetlath** [comment] 2024-10-06 13:33
I'm going to close this as I don't think this is a priority right now with #vip-vsb being closed. Comment or reopen if you disagree!

**Comment by akinwale** [comment] 2024-10-08 09:44
@puneetlath This would be eligible for compensation since a PR was created and we went through the review process.

**Comment by puneetlath** [comment] 2024-10-09 15:57
Fair enough. I've paid out the contracts. Thanks y'all.

**Closed by puneetlath** 2024-10-09 15:57 UTC
Labels: Engineering, Monthly, Bug, retest-weekly
