### ISSUE TITLE
[HOLD VBBA refactor] [$500] Web – Add bank account modal is displayed briefly with 2 options if bank account has been added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34919] opened 2024-01-22 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a Workspace and Add bank account
4. Navigate to Settings / Workspace / Cards / Workspace / Bank account

## Expected Result:
Directed to a page with the header Connect bank account and the option to disconnect your bank account

## Actual Result:
Add bank account modal is displayed briefly with 2 options if bank account has been added. Then directed to a page with the header Connect bank account and the option to disconnect your bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7cd136a1-a550-4e8e-bd68-86271e52d657

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182f628dafbfb1237</li>
        <li>Upwork Job ID: 1749519924811567104</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-22 22:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web – Add bank account modal is displayed briefly with 2 options if bank account has been added
### What is the root cause of that problem?
- In [ReimbursementAccountPage](https://github.com/Expensify/App/blob/b1c49db1c71a5a844661227fef56aa008f8782d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js), we use the [currentStep](https://github.com/Expensify/App/blob/b1c49db1c71a5a844661227fef56aa008f8782d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L252) to know what we should display, and in this case, when the page is mounted, ```reimbursementAccount``` is just ```isLoading: false```, so the ```reimbursementAccount.achData.currentStep``` is ```undefined```, that leads to the ```currentStep``` is ```CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT``` by default, so it will display the bank account step by default:
https://github.com/Expensify/App/blob/b1c49db1c71a5a844661227fef56aa008f8782d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L471-L473

- Additionally, refer to [react-native-onyx docs](https://github.com/Expensify/react-native-onyx):
> withOnyx() will delay the rendering of the wrapped component until all keys/entities have been fetched and passed to the component

- In this case, the ```reimbursementAccount``` is ```{isLoading: false}``` initially, so we cannot delay the page until  ```reimbursementAccount.achData.currentStep``` is not ```undefined```
### What changes do you think we should make in order to solve the problem?
- We can display the loading indicator when the ```reimbursementAccount.achData.currentStep``` is ```undefined```.
- Do it by updating:
https://github.com/Expensify/App/blob/b1c49db1c71a5a844661227fef56aa008f8782d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L400
to:
```
  const isLoading = (isLoadingApp || account.isLoading || reimbursementAccount.isLoading || !reimbursementAccount.achData.currentStep) && (!plaidCurrentEvent || plaidCurrentEvent === CONST.BANK_ACCOUNT.PLAID.EVENTS_NAME.EXIT);
```
or just add the condition below in [here](https://github.com/Expensify/App/blob/b1c49db1c71a5a844661227fef56aa008f8782d0/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L470):
```
    if(!reimbursementAccount.achData.currentStep){
        return null
    }
```
### What alternative solutions did you explore? (Optional)

- NA

**Comment by adelekennedy** [comment] 2024-01-25 05:18
@Santhosh-Sellavel a few proposals to review!

**Comment by mountiny** [comment] 2024-01-25 14:34
On hold

**Comment by Santhosh-Sellavel** [comment] 2024-01-25 15:30
Thanks for clearing that up!

**Comment by Santhosh-Sellavel** [comment] 2024-01-27 16:58
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @adelekennedy

**Comment by Christinadobrzyn** [comment] 2024-02-13 17:34
Hey @Santhosh-Sellavel do you think [GH issue](https://github.com/Expensify/App/issues/36376) will be resolved with this job? (can we consolidate https://github.com/Expensify/App/issues/36376 into this one?)

**Comment by Santhosh-Sellavel** [comment] 2024-02-13 21:38
@Christinadobrzyn Lets put that on hold too.

**Comment by adelekennedy** [comment] 2024-03-18 19:48
still on hold

**Comment by bernhardoj** [comment] 2024-04-01 05:41
I think we can unhold this?

**Comment by nkdengineer** [comment] 2024-04-02 11:10
Coming from https://github.com/Expensify/App/issues/39319 which has the same root cause.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add bank account modal is displayed briefly with 2 options if bank account has been added. Then directed to a page with the header Connect bank account and the option to disconnect your bank account

### What is the root cause of that problem?
This PR https://github.com/Expensify/App/pull/29260 leads to the reimbursement account being cleared whenever `ReimbursementAccountPage` unmounted, leading to the reimbursement account data being loss and it shows as if there was no reimbursement account (briefly) in other pages like Travel page.

### What changes do you think we should make in order to solve the problem?

1. Change [this](https://github.com/Expensify/App/blob/ae57f45cad870931ffa26bb28373682b74b0e1ec/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L282) to 
```
BankAccounts.clearPlaid();
```
We should not clear the reimbursement account fully, we can just clear the Plaid data that is generated when we attempt the connection. This will make sure that the `isLoading` [here](https://github.com/Expensify/App/blob/ae57f45cad870931ffa26bb28373682b74b0e1ec/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L418) could be `true`, otherwise it will always be `false` because the `plaidCurrentEvent` value after the BA connection will be `HANDOFF`.

Without this step, there won't be any loading indicator when coming to the `ReimbursementAccountPage` again after BA connection, in web.

2. Use another approach to make sure we always show loading screen when coming to the `ReimbursementAccountPage` (which is what the [offending PR](https://github.com/Expensify/App/pull/29260) intended to do).

We can set a local `isReimbursementAccountLoading` state, which defaults to `true`, only if the `reimbursementAccount.isLoading` turns from `true` to `false` (which means the reimbursement account has been loaded), we'll set `isReimbursementAccountLoading` to `false`

```
const [isReimbursementAccountLoading, setIsReimbursementAccountLoading] = useState(true);

const prevIsReimbursementAccountLoading = usePrevious(reimbursementAccount.isLoading);
useEffect(() => {
    if (prevIsReimbursementAccountLoading && !reimbursementAccount.isLoading) {
        setIsReimbursementAccountLoading(false);
    }
}, [prevIsReimbursementAccountLoading, reimbursementAccount.isLoading]);
```

Then in [here](https://github.com/Expensify/App/blob/5cdfbb74c7ceedef868acabd6cd7bb7dfe060281/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L418), use `isReimbursementAccountLoading` instead of `reimbursementAccount.isLoading`

### What alternative solutions did you explore? (Optional)
In addition to the 1st solution part, we can potentially revert the whole [offending PR](https://github.com/Expensify/App/pull/29260).

An alternative to step 2 is to still use `reimbursementAccount.isLoading`, but set `initWithStoredValues` to `false`, and set the default value of `isLoading` to `true`, so that it will always be `true` initially. But we'll also need to fix the existing Onyx bug where `initWithStoredValues` is not working.

**Comment by adelekennedy** [comment] 2024-04-02 17:19
I actually think we should close this one given our [new standards](https://github.com/Expensify/Expensify/issues/381537) - this is a bug but isn't very disruptive

**Closed by adelekennedy** 2024-04-02 17:19 UTC
Labels: External, Monthly, Help Wanted, Bug
