### ISSUE TITLE
[$250] "submit your first expense" tooltip on the Concierge chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49737] opened 2024-09-25 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727097420501849

## Action Performed:

1. Create an account on OldDot: ownerA
2. Create a Control policy on OldDot in the ownerA account
3. Invite employeeB to the policy as a non-admin
4. Sign into employeeB on OldDot and submit an expense report to the policy
5. Sign into NewDot as employeeB

## Expected Result:
No "Submit your first expense"  tool tip from Concierge as the user already submitted expense
## Actual Result:
Submit your first expense tool tip displayed. This tooltip is only supposed to be shown on workspace chats
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (5)](https://github.com/user-attachments/assets/ee52c01f-cd4a-476a-8d4f-0247d63d8aa9)

![Full Screen #14](https://github.com/user-attachments/assets/ce8fa5d2-a36e-4173-b1dc-1b2ddc68c4e0)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841101161006845013</li>
        <li>Upwork Job ID: 1841101161006845013</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2024-09-25 20:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- "Submit your first expense" tooltip is shown despite having expenses submitted already 


### What is the root cause of that problem?

- We're relying on `ONYXKEYS.NVP_WORKSPACE_TOOLTIP` (workspaceTooltip.shouldShow) to decide whether to show the tooltip or not.
- When the expenses are submitted via OldDot, I think this NVP is not updated. Hence I feel this needs to be fixed on the BE.


### What changes do you think we should make in order to solve the problem?

- Fix this on the BE so that the user gets the updated `workspaceTooltip.shouldShow` value.


### What alternative solutions did you explore? (Optional)

- We add a util to check if the user has any expenses reports. If yes, then we set `shouldShowEducationalTooltip` as false

**Comment by NJ-2020** [comment] 2024-09-26 02:38
Duplicate issue #49566

**Comment by situchan** [comment] 2024-10-01 20:08
I think this issue has 2 bugs:
- tooltip still shows after user already submitted expense on OD - seems [backend bug](https://github.com/Expensify/App/issues/49737#issuecomment-2375233974)
- for new user, tooltip shows on concierge chat, instead of workspace chat - dupe of https://github.com/Expensify/App/issues/49566

🎀👀🎀

**Comment by garrettmknight** [comment] 2024-10-08 18:36
I think this is a good inconsistency to make sure we're fixing since it's a first experience with NewDot from the user. I like adding a new check here.

**Comment by garrettmknight** [comment] 2024-10-08 18:37
I think this is a good inconsistency to make sure we're fixing since it's a first experience with NewDot from the user. I like adding a new check here.

**Comment by garrettmknight** [comment] 2024-10-11 00:18
Waiting for a volunteer

**Comment by garrettmknight** [comment] 2024-10-15 01:00
Still waiting for a volunteer.

**Comment by garrettmknight** [comment] 2024-10-15 01:02
Ah, this is a dupe of https://github.com/Expensify/App/issues/49566

**Closed by garrettmknight** 2024-10-15 01:02 UTC
Labels: Daily, Internal, Bug, Hot Pick
