### ISSUE TITLE
[HOLD for payment 2023-08-10] [$2000] 'Date' section is not grayed out and the cursor does not change on the IOU report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22742] opened 2023-07-12 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request Money from any user
2. Go to the IOU report
Notice that the Amount and Description are grayed out But not the 'Date' section. And the cursor does not change.

## Expected Result:
The 'Date' section is grayed out and the cursor changes

## Actual Result:
The 'Date' section is not grayed out and the cursor does not change on the IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3abfe833-28c0-4e8b-9812-cc71110069c4

https://github.com/Expensify/App/assets/93399543/b97bf00b-ad81-4806-a981-1ea9f6b26dbe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689115720723609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184afd377a2246d04</li>
        <li>Upwork Job ID: 1684480022772416512</li>
        2023-07-31<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25857860</li>
<li>c3024 | Contributor | 25857863</li>
<li>daveSeife | Reporter | 25857866</li>
</ul></li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-07-12 13:07
Definitely not a blocker. Checking it off the [list](https://github.com/Expensify/App/issues/22598).

**Comment by Julesssss** [comment] 2023-07-12 13:11
Odd, I'm not able to reproduce on production. I can see [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689165042426429?thread_ts=1689115720.723609&cid=C049HHMV9SM) that @kbecciv was able to though 😕

**Comment by Julesssss** [comment] 2023-07-12 13:23
@aimane-chnaif sure. It's no longer a blocker so that seems fine.

**Comment by situchan** [comment] 2023-07-12 13:24
I think this is wrong bug report.
In @kbecciv's video, payment is settled in staging, not settled in production.
Grey should happen only when payment is settled and thus amount and description should not be editable.
In original logic, date section is active always no matter settled or not.

But from design perspective, it would be good to make date color follow others. So if greyed, apply grey, if not greyed. apply not grey.

**Comment by Julesssss** [comment] 2023-07-12 14:34
Hmm good point but, I have a feeling our edit existing request PRs are still WIP.

**Comment by Julesssss** [comment] 2023-07-12 14:45
> I think we can close this issue as staging and production actually behave the same.

We should still make sure the UI for 'date' matches 'amount' and 'description'.

**Comment by shawnborton** [comment] 2023-07-12 17:30
I think we are already working on fixing all of this, right @jasperhuangg @thienlnam ? None of this should have been grayed out in the first place. Anyways, I think we can just close this out.

**Comment by thienlnam** [comment] 2023-07-12 17:35
We updated the task view so it floats above the chats like a reportAction, I thought there was a different issue for the IOU details to have the same done - do you happen to know if this issue exists @luacmartins?
<img width="824" alt="Screenshot 2023-07-12 at 10 35 25 AM" src="https://github.com/Expensify/App/assets/30609178/7235a243-180b-438b-987a-8a466f693b5b">

**Comment by luacmartins** [comment] 2023-07-12 20:20
I'm not aware of any issues doing this for IOUs

**Comment by luacmartins** [comment] 2023-07-12 20:24
Ah nice! Thanks for linking that issue @aimane-chnaif

**Comment by Julesssss** [comment] 2023-07-27 08:24
The [linked](https://github.com/Expensify/App/issues/22742#issuecomment-1633156514) PR was merged but the issue still occurs. We should fix this

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:02
doubling price

**Comment by himanshuragi456** [comment] 2023-07-31 13:09
@michaelhaxhiu [this](https://github.com/Expensify/App/issues/22742#issuecomment-1632464444) proposal by @c3024 looks fine. please let me know if that proposal is discarded so I can try some new method.

cc: @aimane-chnaif

**Comment by himanshuragi456** [comment] 2023-07-31 13:12
@aimane-chnaif I think I can go ahead with new proposal then

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:53
@himanshuragi456 appreciate the nudge for the prior proposal :) @c3024 consider the doubling of the price to be your luck this time around, since enough time elapsed before we could review the proposal. You'll get the listed bounty 👍

**Comment by Julesssss** [comment] 2023-07-31 14:15
Okay, let's move forward. I created a separate [issue](https://github.com/Expensify/App/issues/23924) for the component deprecation that we'll handle internally.

**Comment by adelekennedy** [comment] 2023-08-10 18:28
**Payment Summary**

@daveSeife - $250 for reporting bonus (paid via Upwork)
@c3024  - $2000 for fix and $1000 for [speed bonus ](https://github.com/Expensify/App/issues/22742#issuecomment-1659905966)(paid via Upwork)
@aimane-chnaif - $2000 for fix and $1000 for [speed bonus](https://github.com/Expensify/App/issues/22742#issuecomment-1659905966) (paid via Upwork)

**Comment by adelekennedy** [comment] 2023-08-10 18:44
@c3024 I keep trying to process it but Upwork keeps crashing 😬

**Closed** 2023-08-16 00:07 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
