### ISSUE TITLE
 Assign Task - Task assigned for User A can be completed by User B from group chat, but not from the Task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24655] opened 2023-08-16 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to [new.expensify.com](http://new.expensify.com/)
2. Click FAB
3. select New Group
4. Add two new users ( A, B)
5. Click Actions (+ icon) in group chat
6. Create a new task and assign it to User A
7. Login into User B account
8. In the group chat, User B is able to click on the checkbox(:white_check_mark:), and the task can be completed (Invalid)
9. Click on the > icon in the group chat for that task, it opens the task details, but User B can't click the checkbox and complete the task complete action (Valid)

## Expected Result:
User B shouldn't be allowed to complete the task from the group chat because it is assigned to User B

## Actual Result:
User B can complete the task from the group chat even though it is assigned to another User B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/20131277-4622-4b1f-b2c2-8b3dab7989b4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Kaseenadh Reddy Bojja

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691421909179679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-08-17 10:06
Clarifying a couple of things in channel [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692266773404829?thread_ts=1691421909.179679&cid=C049HHMV9SM).

**Comment by trjExpensify** [comment] 2023-08-21 11:53
Bumped in the issue on reproducing: https://expensify.slack.com/archives/C049HHMV9SM/p1692618765810799?thread_ts=1691421909.179679&cid=C049HHMV9SM

As for the expected results, anyone with write access on the task report can complete the task not just the assignee.

**Comment by trjExpensify** [comment] 2023-08-22 13:44
Okay, no reply. I've retested and can't reproduce the expected results. That being, anyone with write access on the taskReport can complete the task. Closing! 

![ddZzJJUH0S](https://github.com/Expensify/App/assets/16232057/958df934-6f61-4880-8a5e-a3d1a8c60f40)

**Closed by trjExpensify** 2023-08-22 13:44 UTC
Labels: Daily, Bug
