### ISSUE TITLE
[$500] Pressing "Done" key triggers the error message for an invalid input but "Continue" button doesn't for subsequent failed attempts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25552] opened 2023-08-20 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the application and navigate to the login page of new.expensify.com
2. Enter invalid text into the designated input field.
3. Tap the "Continue" button.
4. Observe the correct error message being displayed.
5. Clear the input text.
6. Enter the similar text again into the input field.
7. Tap the "Continue" button.
8. Note that no error is displayed and the button does not appear to respond.
9. Press the "Done" key on the mobile keyboard.
10. Observe the expected error message appearing.

## Expected Result: 
After entering invalid text and tapping the "Continue" button, the application should consistently display an error message.
Tapping the "Continue" button after clearing the input text and re-entering the text should also trigger the appropriate error message.
The button should always function as expected, providing consistent behavior throughout the login process.
## Actual Result: 
Tapping the "Continue" button after clearing the input text and re-entering the text does not trigeer the appropriate error message.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/da1d82b8-acc9-470a-ab65-9fcbc091d42c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @saalimzafar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691607811955429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef58406cc60dcd53</li>
        <li>Upwork Job ID: 1697274412859670528</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by saalimzafar** [comment] 2023-08-20 19:24
Login Page Error:Pressing "Done" key triggers the error message for an invalid input but "Continue" button doesn't for subsequent failed attempts

Please consider updating the Issue title @kavimuru and thanks

**Comment by CortneyOfstad** [comment] 2023-08-21 18:46
Had @slafortune test this (as our office Android user) and could not recreate. She saw the error message each time. 

Can we confirm this is still happening?

**Comment by saalimzafar** [comment] 2023-08-21 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Button click is not working as expected
### What is the root cause of that problem?
The unexpected behavior might be caused by incorrect usage of useState.
[src/pages/signin/LoginForm.js](url)

`const [formError, setFormError] = useState(false);`
### What changes do you think we should make in order to solve the problem?
`const [formError, setFormError] = useState(null);`
### What alternative solutions did you explore? (Optional)
NA

**Comment by kavimuru** [comment] 2023-08-24 18:32
@CortneyOfstad I wasn't able to reproduce either.

**Comment by saalimzafar** [comment] 2023-08-24 18:40
@kavimuru it's reproducible on the Android Native  as well, would you like like to share the video so that we can see why you are unable to reproduce it, and what version of the app you are using
cc: @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2023-08-28 11:59
I unfortunately don't have an Android, but going to see if I can get some help in testing this again 👍

**Comment by CortneyOfstad** [comment] 2023-08-31 15:45
Sorry @robertjchen — applied the wrong tag — false alarm!!

**Comment by ishpaul777** [comment] 2023-08-31 16:21
i am not able to reproduce error appear everytime "Continue" is clicked.

**Comment by CortneyOfstad** [comment] 2023-09-01 15:37
@allroundexperts any ideas why this is reproducible for some but not for all? Also wondering if we should close if we cannot get consistent results. Thoughts?

**Comment by CortneyOfstad** [comment] 2023-09-05 13:27
Bump @saalimzafar on the comment above — TIA!

**Comment by CortneyOfstad** [comment] 2023-09-08 14:36
@saalimzafar Bump on the comments above ^^^ - TIA!

**Comment by CortneyOfstad** [comment] 2023-09-11 14:32
@allroundexperts I just confirmed with the team that @saalimzafar is no longer working with Expensify. So going to close this!

**Closed by CortneyOfstad** 2023-09-11 14:32 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
