### ISSUE TITLE
FAB – Blue frame appears when navigate via FAB menu using Up/Down keys

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40398] opened 2024-04-18 08:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Click on +/FAB button
4. Navigate via FAB menu using Up/Down keys

## Expected Result:
Frame do not appears when navigate via FAB menu using Up/Down keys

## Actual Result:
Blue frame appears when navigate via FAB menu using Up/Down keys on keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a2867a30-de71-42b1-a322-844729afc608

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aacec44a086107f8</li>
        <li>Upwork Job ID: 1781073972718292992</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-18 08:05
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 08:05
We think this issue might be related to the #vip-vsb.

**Comment by MahmudjonToraqulov** [comment] 2024-04-18 08:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
FAB – Blue frame appears when navigate via FAB menu using Up/Down keys

### What is the root cause of that problem?
We didn't add `style={styles.noSelect}` here

### What changes do you think we should make in order to solve the problem? 
 We should add `style={styles.noSelect}` here.

### What alternative solutions did you explore? (Optional)
N/A


### Result

**Comment by shahinyan11** [comment] 2024-04-18 08:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB – Blue frame appears when navigate via FAB menu using Up/Down keys
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
Add `styles.boxShadowNone` in [this](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/MenuItem.tsx#L440C1-L449C30) styles array

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-18 08:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB – Blue frame appears when navigate via FAB menu using Up/Down keys
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
Add `styles.boxShadowNone` or `styles.noSelect` in [this](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/MenuItem.tsx#L440C1-L449C30) styles array

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-18 08:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB – Blue frame appears when navigate via FAB menu using Up/Down keys
### What is the root cause of that problem?
We do not set `box-shadow:none` style for [PressableWithSecondaryInteraction](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/MenuItem.tsx#L433)
### What changes do you think we should make in order to solve the problem?
Add `styles.boxShadowNone` or `styles.noSelect` in [this](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/MenuItem.tsx#L440C1-L449C30) styles array

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-04-18 21:38
[Checking on in #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1713476038798349) to see if anyone's been working on FAB that might have caused this regression.  @Santhosh-Sellavel , any thoughts/idea?   I searched E/App for issues with `fab` in the title and nothing looked suspect.

**Comment by mallenexpensify** [comment] 2024-04-18 21:57
Thanks @ishpaul777 , I [commented on that PR](https://github.com/Expensify/App/pull/39201#issuecomment-2065390571), tagged the author and C+ who reviewed for 👀. 

Also, I was able to reproduce on staging and not on production

https://github.com/Expensify/App/assets/22508304/13b54a15-41f8-46f1-84e5-415f7f5eb1fd

**Comment by mallenexpensify** [comment] 2024-04-18 22:03
I think the grey when arrowing through is _enough_ to denote the selection.  I don't see a benefit to the blue border, but maybe I'm missing something. 

Also agree it doesn't _feel_ like it needs to be a blocker. 

https://github.com/Expensify/App/assets/22508304/62560e8b-2e95-43f6-bfd1-b9bf46d7aab7

**Comment by mallenexpensify** [comment] 2024-04-19 23:31
Thanks Fedi, if it's intended behaviour, I'm closing.  Comment/reopen if anyone disagrees.

**Closed by mallenexpensify** 2024-04-19 23:31 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Internal, Bug
