### ISSUE TITLE
 iOS - "New workspace" options disappears and then reappears

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24298] opened 2023-08-08 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign in as a new user on the iOS mobile app
2. Allow the notification permission
3. The option menu is open by default. You can see that the "New workspace" option disappears for a few secon

## Expected Result:
The option stays there and the options don't change

## Actual Result:
You can see that the "New workspace" option disappears for a few seconds

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/f98feb8c-f4fd-4d67-88ee-216c54f54b9a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690968095652719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by manjesh-yadav** [comment] 2023-08-09 03:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - "New workspace" options disappears and then reappears

### What is the root cause of that problem?
When clicking allow notification an API call is to update it on backend and `isLoadingReportData` in Onyx is true before api returns data

That makes the workspace option disappear for a few seconds and after API is complete it appears again

https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L250


### What changes do you think we should make in order to solve the problem?

We don't need to check `!this.props.isLoading` to show workspace option
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L250

**Comment by hannojg** [comment] 2023-08-09 06:06
The issue was reported bz me

**Comment by anmurali** [comment] 2023-08-16 17:18
I am not able to reproduce this because a magic code from a new user requested on native iOS app never arrives, posting [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692206282419589)

**Comment by anmurali** [comment] 2023-08-24 15:57
https://github.com/Expensify/App/assets/14225673/fd58a57a-facf-4246-a764-680365c6fc04

I cannot reproduce this. @hannojg can you take a look at that video?

**Comment by anmurali** [comment] 2023-08-31 02:12
Closing as I cannot reproduce.

**Closed by anmurali** 2023-08-31 02:12 UTC
Labels: Engineering, Daily, Overdue, Bug
