### ISSUE TITLE
[$250] [Accessable Pressables] Migrate ReportActionItemMessageEdit to use new Pressables

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#20023] opened 2023-06-02 00:40 UTC
### Description

Migrate [ReportActionItemMessageEdit](https://github.com/Expensify/App/blob/f4f89a0cac5b07265e82c85e69e48720997ba84b/src/pages/home/report/ReportActionItemMessageEdit.js#L357) to use new Pressables.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d15fe8a243e9da0a</li>
        <li>Upwork Job ID: 1667277357948985344</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by Skalakid** [comment] 2023-06-02 15:43
Can you assign me to this one as well, please?

**Comment by roryabraham** [comment] 2023-06-09 21:09
@AndrewGable and @allroundexperts were already auto-assigned to review the [PR](https://github.com/Expensify/App/pull/20082), so I've assigned them here.

@slafortune The only payment that will be due here is $250 to @allroundexperts for the C+ review. I've lowered the bounty for this simple issue, and have done the same for other similar issues in the same project.

**Comment by AndrewGable** [comment] 2023-06-13 17:01
PR was merged

**Comment by thienlnam** [comment] 2023-06-13 18:11
Linked PR added a regression: https://github.com/Expensify/App/issues/20682

**Comment by slafortune** [comment] 2023-06-16 21:32
looks like we are holding for payment until 6/23 - solution was just deployed

**Comment by slafortune** [comment] 2023-06-21 20:30
Due 6/23

**Comment by slafortune** [comment] 2023-06-23 15:06
Offer sent @allroundexperts https://www.upwork.com/nx/wm/offer/25187065

**Comment by thienlnam** [comment] 2023-06-23 16:21
@slafortune Just a note, payment should be halved for C+ since there was a regression added here!
https://github.com/Expensify/App/issues/20023#issuecomment-1589803418

**Comment by slafortune** [comment] 2023-06-26 16:26
Ah!  Thanks for the heads up @thienlnam !  Paid @allroundexperts

**Closed by slafortune** 2023-06-26 16:26 UTC
Labels: External, Daily, Task, Overdue
