### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] Chat - Popup window appears that can't close tapping outside

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32610] opened 2023-12-07 01:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
**Precondition: use an account you haven't logged in with yet today**
1. Go to URL https://staging.new.expensify.com/
2. Login -> popup appears, sometimes it appears when going through the app or login via Apple/Gmail
3. Click outside the popup

## Expected Result:
The popup closes by tapping outside & focus mode is enabled based on - https://expensify.slack.com/archives/C01SKUP7QR0/p1701987845872109?thread_ts=1701982931.866569&cid=C01SKUP7QR0

About this popup: it has an nvp. it can only be triggered once. anyone with 30 or more chats is the trigger.

## Actual Result:
The popup doesn't close
Focus mode activates automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6303868_1701912055194!image__192_](https://github.com/Expensify/App/assets/78819774/3478479d-d812-4e81-be4e-1c3f821133b7)

https://github.com/Expensify/App/assets/78819774/bb63587d-b725-41ca-b4e4-9d206974fe6c

https://github.com/Expensify/App/assets/78819774/52c136d0-10e2-4cb7-a2f5-1ea483f189a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e281391727f24e86</li>
        <li>Upwork Job ID: 1734278720260624384</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 28064527</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-12-07 01:42
I think it can't really be a blocker really because it's a new feature in any case.

If there is an existing modal that won't close - let's look into it, but otherwise, not a blocker IMO.

**Comment by Pujan92** [comment] 2023-12-07 02:18
@marcaaron Isn't this intended where the user has to click on the Got it button to close the modal as it is not a kind of confirmation modal bcoz we already switched to the focus mode?

**Comment by marcaaron** [comment] 2023-12-07 03:25
>@marcaaron Isn't this intended where the user has to click on the Got it button to close the modal as it is not a kind of confirmation modal bcoz we already switched to the focus mode?

Not sure I understood you, sorry. I think that tapping outside the modal should dismiss it. It's just not a deploy blocker. Thanks!

**Comment by Pujan92** [comment] 2023-12-07 03:35
Ok, I thought the user needed to compulsorily press the button to proceed with this acceptance modal and it should not close on backdrop click.

**Comment by Pujan92** [comment] 2023-12-07 03:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Modal is not dismissing on outside click for focus modal

### What is the root cause of that problem?
We have not provided the logic for `onCancel` for the `ConfirmModal`.
https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/components/FocusModeNotification.js#L20-L25

### What changes do you think we should make in order to solve the problem?
Add `onCancel` for the modal which will call `clearFocusModeNotification` which is the same we are doing for `onConfirm`.
```
onCancel={User.clearFocusModeNotification}
```

**Comment by Christinadobrzyn** [comment] 2023-12-07 23:29
It [sounds like](https://expensify.slack.com/archives/C01SKUP7QR0/p1701982931866569) the behaviour is:

1) They click "Got it" on the popup window and focus is enabled
2) We build a way for them to dismiss the popup (by clicking outside it) but #focus mode will still be enabled. 

Because the behaviour will be the same if they dismiss the pop-up or click "Got it" - we should force them to click "Got it" as an attempt to get them to read about #focus mode. 

So let's do nothing here and come back to this if we want to change it.

**Comment by mallenexpensify** [comment] 2023-12-11 17:44
I don't think the default here should be that, if you click the only green button or outside the box, that the behaviour changes?  The default should be 'shit doesn't change' unless you actively, actually click something that clearly states you want to make the change (which i don't think is what we're doing here, right?)

**Comment by rafecolton** [comment] 2023-12-11 18:04
I agree. I think it's fine to suggest switching to focus mode, but there should be _two_ buttons - perhaps "Try it!" and "No thanks". Clicking outside of the modal should be the same as clicking "No thanks".

**Comment by dubielzyk-expensify** [comment] 2023-12-11 22:51
Here's the mock as requested: 
![image](https://github.com/Expensify/App/assets/145416827/e6b5a607-b99b-4137-a9f1-595f54f76544)

Changed the headline to `Introducing #focus mode` as well.

**Comment by dubielzyk-expensify** [comment] 2023-12-12 00:02
After chatting we'll wanna spruse up the modal a bit with an illustration and new copy as well: 
![image](https://github.com/Expensify/App/assets/145416827/487079a7-9c16-40ee-9ee5-c3d8f2c8ecf1)

**Comment by marcaaron** [comment] 2023-12-12 03:02
Loving the new direction here ✨ 

Anyone want to circle back to [this thread](https://expensify.slack.com/archives/C04JD99283A/p1698463632622219) to just give an update on where things landed? 🙇

**Comment by neonbhai** [comment] 2023-12-12 17:16
@dubielzyk-expensify hey, could you share how would this illustrated modal look on mobile screens?

**Comment by neonbhai** [comment] 2023-12-12 17:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Popup Window redesign.

### What is the root cause of that problem?
New Feature

### What changes do you think we should make in order to solve the problem?
We don't have any component in the app right now that renders an illustration with a modal

We will:

- Extend the Confirm Modal to optionally take in an image prop:
  + We will define an `image` prop [here](https://github.com/Expensify/App/blob/c21f4557026092f49ab908853ce79297aa398241/src/components/ConfirmModal.js#L8)
  + This will be passed to ConfirmContent.

- Extend ConfirmContent to define an `image` Prop [here](https://github.com/Expensify/App/blob/fa504d7f2da620cb86d81c4e8f73ab9e971633f9/src/components/ConfirmContent.js#L14)

- Render the image [here](https://github.com/Expensify/App/blob/fa504d7f2da620cb86d81c4e8f73ab9e971633f9/src/components/ConfirmContent.js#L97) before rest of the content.


- Create a new `ConfirmModalWithIllustrationModal` for this usecase.



We will be changing the `FocusModeNotification.js` file as:

- Remove this useEffect:
  https://github.com/Expensify/App/blob/c21f4557026092f49ab908853ce79297aa398241/src/components/FocusModeNotification.js#L16-L18

- Update prompt [here](https://github.com/Expensify/App/blob/c21f4557026092f49ab908853ce79297aa398241/src/components/FocusModeNotification.js#L26-L41) as in copy.

- Pass `shouldStackButtons` as `false` [here](https://github.com/Expensify/App/blob/798deda1a58c0be7579e5042f745566af58e384f/src/components/FocusModeNotification.js#L42).

**Comment by Christinadobrzyn** [comment] 2023-12-12 21:20
@neonbhai - I reached out to Jon to see if we can get some details on the mobile app layout (I assume it will be the same image but just configured to a mobile app screen). 

Is there something in particular you'd like to see about the mobile app layout?

**Comment by sakluger** [comment] 2023-12-12 21:42
I wanted to take a pause here on the new direction, since it's different from what we discussed in the [original Slack thread](https://expensify.slack.com/archives/C04JD99283A/p1698463632622219). I've invited @rafecolton and @mallenexpensify to discuss this in that Slack thread to make sure we're all in agreement on the right direction.

**Comment by neonbhai** [comment] 2023-12-12 22:13
@Christinadobrzyn hey, just wanted to make sure if the Illustration will require additional configuration for small screens. Thank you for reaching out!

**Comment by dubielzyk-expensify** [comment] 2023-12-13 00:14
I'll hold on the mobile mocks until we got confirmation of the direction we're heading in

**Comment by rafecolton** [comment] 2023-12-14 01:25
@dubielzyk-expensify per [this discussion](https://expensify.slack.com/archives/C04JD99283A/p1702505632112279?thread_ts=1698463632.622219&cid=C04JD99283A), can you please update the mocks to:
* Use the image you suggested above
* Use the following text:
  > Stay on top of things by only seeing unread chats. Chats will be hidden after you read them unless they require your attention. Don't worry, you can change this at any point in settings.
* Keep the word `settings` a link
* Contain only one "Got it" button like it does today.

Thanks!!

**Comment by neonbhai** [comment] 2023-12-14 02:32
## Proposal 
### [Updated](https://github.com/Expensify/App/issues/32610#issuecomment-1852495529)

According to new requirements!

**Comment by dubielzyk-expensify** [comment] 2023-12-14 03:39
New fresh mock from the oven:

![image](https://github.com/Expensify/App/assets/145416827/645d68da-b4c8-4cef-a604-fb8eaa07571e)

**Comment by JmillsExpensify** [comment] 2023-12-14 06:49
I think it'd be good to get a second opinion on copy. Adding the marketing label quick.

**Comment by JmillsExpensify** [comment] 2023-12-14 06:50
cc @GabiHExpensify since I see you're assigned.

**Comment by dubielzyk-expensify** [comment] 2023-12-15 00:02
Realized I didn't upload mobile mocks:

![image](https://github.com/Expensify/App/assets/145416827/45bebb98-a5d2-469a-aa13-5c946a6cddf3)

**Comment by rushatgabhane** [comment] 2023-12-18 13:35
Alright, this is a straightforward issue. Let's assign @neonbhai to this issue https://github.com/Expensify/App/issues/32610#issuecomment-1852495529
🎀 👀 🎀

**Comment by rushatgabhane** [comment] 2023-12-18 13:42
@dubielzyk-expensify @luacmartins which design have we landed on? I think 2 is better because I think we shouldn't change things for the user. Unless they hit the green `Try it` button

| 1 | 2 |
|--------------------|---------|
|            <img width="817" alt="image" src="https://github.com/Expensify/App/assets/29673073/8a89a086-c1f9-4b85-bff9-f7a1dff77559">        |     <img width="809" alt="image" src="https://github.com/Expensify/App/assets/29673073/d225ab7f-c70b-4347-998f-9dcda9229e26">    |

**Comment by luacmartins** [comment] 2023-12-18 14:01
>@luacmartins i think we should look at the implementation in the PR, but let me know if you agree with these requirements
>
>1. Add a prop a image to ConfirmModal.
>2. Dismissing the modal should not change the user's preference. i.e. if the user was using normal mode, they should stay in normal mode.

sound good to me @rushatgabhane. I'll let @dubielzyk-expensify confirm the design changes above though.

**Comment by rafecolton** [comment] 2023-12-18 14:51
@rushatgabhane in Slack we agreed on design 1

**Comment by rushatgabhane** [comment] 2023-12-18 14:58
Thanks for confirming!

@neonbhai let's implement design 1

**Comment by luacmartins** [comment] 2023-12-21 15:57
Waiting on @neonbhai to raise a PR

**Comment by GabiHExpensify** [comment] 2023-12-21 23:34
@rafecolton could you link the slack conversation where design 1 was agreed on? i think design 2 is much better -- it's not clear from the "got it" on design 1 what will happen if you click it.

**Comment by GabiHExpensify** [comment] 2023-12-21 23:37
A few questions/suggestions...
- Why are we calling this `#focus mode` instead of just `Focus Mode` or `focus mode`? I know we use #focus internally at Expensify, but I don't think that's a super obvious thing to anyone external, it seems like it would be stronger to eliminate the hashtag.


Suggested copy update:
Introducing Focus Mode
Keep your mind clear by only seeing conversations that are unread or need your attention. You can change this at any point in your settings under `preferences`. 

<img width="321" alt="Screenshot 2023-12-21 at 3 34 21 PM" src="https://github.com/Expensify/App/assets/19719519/2ecc3b58-a45e-4500-aa62-2b3354b68b42">


(Also as an FYI, I'm going OOO tomorrow and will be out 'til Jan 3. But there are 3+ other marketers who'll be online throughout the next week, so feel free to reassign or drop it in #marketing if you need more eyes while I'm out.)

**Comment by Christinadobrzyn** [comment] 2023-12-22 19:20
@neonbhai let us know where you are with a PR and if you have any questions!

**Comment by quinthar** [comment] 2023-12-26 02:02
I think this is part of wave1, not #vip-vsb.

**Comment by quinthar** [comment] 2023-12-26 02:08
Pinged here for an update: https://expensify.slack.com/archives/C04JD99283A/p1703556117988619?thread_ts=1698463632.622219&cid=C04JD99283A

**Comment by dubielzyk-expensify** [comment] 2024-01-01 22:40
Here's the illustration 
[three_legged_laptop_woman.svg.zip](https://github.com/Expensify/App/files/13806206/three_legged_laptop_woman.svg.zip)

**Comment by GabiHExpensify** [comment] 2024-01-03 18:09
I posted the copy updated to Slack, since it seems like there's still some discussion there: https://expensify.slack.com/archives/C04JD99283A/p1704305370205009?thread_ts=1698463632.622219&cid=C04JD99283A

**Comment by rushatgabhane** [comment] 2024-02-04 18:34
@neonbhai do you need any help? Could you please move forward the PR

**Comment by rushatgabhane** [comment] 2024-03-11 22:55
1. The PR that introduced the bug has been identified. Link to the PR:  new feature

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again
    1. Login to an account that has more than 200 chats so that you see focus modal prompt.
    2. Verify that you see an illustration in the modal.

**Comment by rushatgabhane** [comment] 2024-03-11 22:56
@Christinadobrzyn could you please attach payment summary

**Comment by rushatgabhane** [comment] 2024-03-11 22:57
money request here - https://staging.new.expensify.com/r/7597420492097120

**Comment by Christinadobrzyn** [comment] 2024-03-12 07:49
Payouts due:

Contributor: $500 @neonbhai (paid in Upwork - https://www.upwork.com/nx/wm/workroom/35959554/overview)
Contributor+: $500 @rushatgabhane (in NewDot)

Upwork job is [here](https://www.upwork.com/jobs/~01e281391727f24e86).

Regression test posted - https://github.com/Expensify/Expensify/issues/377899

Closing!

**Closed by Christinadobrzyn** 2024-03-12 07:49 UTC
Labels: Engineering, Daily, Internal, Design, Awaiting Payment, Bug
