### ISSUE TITLE
[$1000] Web - Login -The link for validation appears for OldDot when creating a NewDot Expensify account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14320] opened 2023-01-15 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. In the email field, enter an Expensify email address for a new account Press continue
3. Press continue
4. Navigate to the email inbox of the account and open the validation email
5. Copy the link and change it to staging

## Expected Result:
The link for validation appears for NewDot

## Actual Result:
The link for validation appears for OldDot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome / Safari

**Version Number:** 1.2.54.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212550254-fc29747b-0be2-4dc0-8ca9-fc08dbd4e7c9.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144309f86e01596ea</li>
        <li>Upwork Job ID: 1616488461570203648</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-01-20 17:31
This isn't overdue, i've just applied the labels 👍🏼

**Comment by s77rt** [comment] 2023-01-21 12:01
Isn't this supposed to be internal?

**Comment by priyeshshah11** [comment] 2023-01-21 17:49
I think this is not a bug for prod users, it's only for staging/test environments, either way needs to be internal.

**Comment by zanyrenney** [comment] 2023-01-23 17:53
Thanks @priyeshshah11! Yeah, I was on staging when I reproduced this, so if it's not happening on production, I think we can close this out for now.

**Comment by zanyrenney** [comment] 2023-01-23 17:54
I've removed the listing on Upwork.

**Closed by zanyrenney** 2023-01-23 17:53 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
