### ISSUE TITLE
[HOLD for payment 2024-09-16] [$250] Account Settings- App freezes after sending a log file

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47509] opened 2024-08-15 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4859439
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Account Settings -> Troubleshoot
2. Enable "Client side logging"
3. Press "View debug console"
4. Press "Share log"
5. Press on any conversation
## Expected Result:
The user should be moved to the report and logs should be sent as an attachment.
The app is stable and functional to return to the previous screen or access the user's profile.

## Actual Result:
The user is moved to the report and logs are sent as an attachment.
The back button and the user's profile function become unresponsive. The app sometimes crashes after a few minutes.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Log_1508.txt](https://github.com/user-attachments/files/16627923/Log_1508.txt)

https://github.com/user-attachments/assets/fef148dd-ba00-42f6-85c5-32825f6acab1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f26106fe45b6825</li>
        <li>Upwork Job ID: 1825662708863963045</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103607773</li>
<li>dominictb | Contributor | 103607774</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment] 2024-08-15 17:22
We think that this bug might be related to #wave-collect RELEASE 1

**Comment by IuliiaHerets** [comment] 2024-08-15 17:22
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-08-19 22:35
Able to repro in both mweb/Chrome and MacOS.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cf88f2bb-98b0-4a7a-b7c8-74ba668fa556">

**Comment by strepanier03** [comment] 2024-08-19 22:41
Finally crashed on me:

<img width="419" alt="image" src="https://github.com/user-attachments/assets/563e3760-014a-4d8b-ad4d-4265fdb4be73">

**Comment by trjExpensify** [comment] 2024-08-30 00:38
Not sure why this was put in #wave-collect, moving it to #newdot-quality as it's related to a troubleshooting feature.

**Comment by suneox** [comment] 2024-09-24 16:29
**Bugzero Checklist**

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/45769
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/45769/files#r1773677191)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A: This issue has handled an edge case when updating the log request.​*

**Comment by suneox** [comment] 2024-09-24 16:31
@strepanier03 The checklist is completed, and we can proceed with the payment.​

**Comment by trjExpensify** [comment] 2024-10-01 01:25
Done that for you, @dominictb.

**Comment by puneetlath** [comment] 2024-10-06 14:04
@strepanier03 looks like this is awaiting payment from you.

**Comment by strepanier03** [comment] 2024-10-07 17:28
Both contracts paid and closed with feedback left. I was OoO for a bit and this came due during that time, then the Hold status had it hidden from me and I missed it. Thank you for the bumps.

**Closed by strepanier03** 2024-10-07 17:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
