### ISSUE TITLE
[$500] Web - Request Money - Long description is showing  without  "Paid by" and "Split with" 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28073] opened 2023-09-23 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB -> Request money -> Enter any numbers
2. Select some account -> Add to Split button
3. Enter a long description -> Save -> Split button
4. Click on newly Request money -> Observe this Request money

## Expected Result:
 Request money will display "Paid by" and "Split with" as well as the Description.

## Actual Result:
 Long description is showing only without  "Paid by" and "Split with" 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9ef6c502-fe49-43df-9990-6c27562720bf

[screen-capture (1) (2).webm](https://github.com/Expensify/App/assets/93399543/7cad0d4f-2946-4ef6-b57a-b60b86912f23)

https://github.com/Expensify/App/assets/93399543/bceb7534-1116-408b-b58e-47b80613fd6e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695272345551449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01062695b5b87a83cc</li>
        <li>Upwork Job ID: 1705616890113011712</li>
        <li>Last Price Increase: 2023-10-14</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-09-23 16:15
# Proposal

## Please re-state the issue
Split bill details page is not scrollable and is stuck when a long discription is provided.

## What is the root cause of this issue?
We are not keeping the `MoneyRequestConfirmationList` in a `ScrollView` in `SplitBillDetailsPage.js`
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/SplitBillDetailsPage.js#L82-L94

This makes it imposible to scroll and the page seems stuck.

## What changes do you think should be made to fix this problem?
We should nest the `MoneyRequestConfirmationList` in a double `ScrollView` like we do in `MoneyRequestConfirmPage.js` here:
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L290-L300

We should also add the `pointerEvents='box-none'` to the `ScrollView` which is currently present on the parent `View` in `SplitBillDetailsPage`.

**Result**:
https://github.com/Expensify/App/assets/77237602/91c9fdd4-c3dc-404e-bed0-c3169713f541

## What other alternative options did you explore? (Optional)

**Comment by wholiday777** [comment] 2023-09-23 16:42
Contributor details
Your Expencify account email: williamholiday777@gmail.com
Upwork Profile Link: https://www.upwork.com/ab/proposals/1705602690487279617?success

Please remove horizontal attribute in ScrollView component.

**Comment by wholiday777** [comment] 2023-09-23 17:14
https://www.upwork.com/freelancers/~019a9ce9f3628775b7
Contributor details
Your Expencify account email: [williamholiday777@gmail.com](mailto:williamholiday777@gmail.com)
Upwork Profile Link: https://www.upwork.com/ab/proposals/1705602690487279617?success

Please remove horizontal attribute in ScrollView component.

**Comment by anmurali** [comment] 2023-09-27 02:42
@situchan have you had a chance to reproduce this bug and review proposals?

**Comment by astrohunter62** [comment] 2023-09-27 03:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a lengthy description is entered, the split bill details page becomes unable to scroll.
### What is the root cause of that problem?
In the ``SplitBillDetaislPage``, the ``MoneyRequestConfirmationList`` is enclosed within a ``View`` component. However, in React Native, ``View`` components do not enable scrolling.
### What changes do you think we should make in order to solve the problem?
We can opt for the ``ScrollView`` component instead of ``View``.

```
<ScrollView
  contentContainerStyle={[styles.flexGrow1]}
  >
    {Boolean(participants.length) && (
      <MoneyRequestConfirmationList
          ....
      />
  )}
</ScrollView>
```
Result:

[28073(safari).webm](https://github.com/Expensify/App/assets/136574831/507548e7-f1d6-47a3-8a9c-0ec02f1d511f)

[28073(chrome).webm](https://github.com/Expensify/App/assets/136574831/dd9c6be1-e31f-4c20-9cb1-676e93a2de99)

**Comment by anmurali** [comment] 2023-10-04 00:24
Bumped @situchan [here](https://expensify.slack.com/archives/C049HHMV9SM/p1696379062076469?thread_ts=1695272345.551449&cid=C049HHMV9SM)

**Comment by situchan** [comment] 2023-10-08 03:07
I feel like "Show more" button needs to show without scrolling down. So when collapsed, show only a few lines of description and when expanded, show full description, followed by Date and Merchant.
cc: @Expensify/design

**Comment by esh-g** [comment] 2023-10-08 09:48
@situchan I have updated [my proposal](https://github.com/Expensify/App/issues/28073#issuecomment-1732354440) accordingly

**Comment by situchan** [comment] 2023-10-08 09:51
@esh-g can you share screenshot? The design team will take decision.

**Comment by astrohunter62** [comment] 2023-10-08 09:57
I updated my [proposal](https://github.com/Expensify/App/issues/28073#issuecomment-1736604336)

**Comment by esh-g** [comment] 2023-10-08 11:41
@situchan Here is the screen recording (already added to proposal as result):

https://github.com/Expensify/App/assets/77237602/d156eaef-6229-4ed2-a971-e4400f9e67bd

cc @Expensify/design

**Comment by dubielzyk-expensify** [comment] 2023-10-08 23:59
The last video looks good to me. It does make me think we should also do truncate the description in the chat as well, not just the details panel.

Thoughts from @dannymcclain and @shawnborton ?

**Comment by shawnborton** [comment] 2023-10-09 13:08
My thinking is that for the preview cards, we should truncate after 2-3 lines as the whole point is that it is a preview, and not the full thing. 

Then when viewing the actual expense/task, I feel like we shouldn't truncate anything as that's the full view you would expect. Instead, we should be enforcing a certain character limit for things like descriptions, etc.

**Comment by situchan** [comment] 2023-10-09 13:13
@shawnborton do you agree this is fine? (no truncation)


https://github.com/Expensify/App/assets/108292595/9ac4d878-474d-4548-a489-f65c86a6eda0

**Comment by shawnborton** [comment] 2023-10-09 13:38
Yup, I do agree that it is fine. Again, I think truncation should happen only in previews, and we should enforce character limits in places where we don't want a ton of text. 

Either way, what you are showing above is an edge case, so I'd love to actually experience where customers see this kind of edge case first before making rules for it.

**Comment by situchan** [comment] 2023-10-09 13:41
@shawnborton thanks for the feedback.

In this case, preview can be out of scope and enable scrolling on split bill detail page is the only one to fix here.

**Comment by esh-g** [comment] 2023-10-12 16:07
@situchan Could you please review [my proposal](https://github.com/Expensify/App/issues/28073#issuecomment-1732354440)? This will not cause any console errors and have tested on all platforms.

**Comment by youssef-lr** [comment] 2023-10-13 08:36
Heads up @esh-g I'm currently working on a PR that's gonna make `MoneyRequestConfirmationList` scrollable as we added errors to the fields and they take up space, it's a bit urgent so we'll try to probably merge it today.

**Comment by situchan** [comment] 2023-10-13 16:35
> @situchan Could you please review [my proposal](https://github.com/Expensify/App/issues/28073#issuecomment-1732354440)? This will not cause any console errors and have tested on all platforms. Feel free to ignore the description truncation logic

Your solution will cause console error on native. We should use horizontal scroll view to avoid VirtualizedList warning

**Comment by situchan** [comment] 2023-10-13 16:35
https://github.com/Expensify/App/pull/29568 is fixing this issue as well.
@youssef-lr I can do expedite review right now if urgent.

**Comment by esh-g** [comment] 2023-10-13 16:37
@situchan I mentioned in my proposal to use a "nested scrollView" while also attaching the place where we use the horizontal one.

<img width="825" alt="Screenshot 2023-10-13 at 10 07 01 PM" src="https://github.com/Expensify/App/assets/77237602/10e18205-ee66-4d97-9f70-dd4d58e4c0e7">

**Comment by situchan** [comment] 2023-10-13 16:39
Oh ok, but unfortunately it's being worked internally.

**Comment by thuyle04** [comment] 2023-10-23 11:01
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by situchan** [comment] 2023-10-24 09:46
Not Overdue

**Comment by situchan** [comment] 2023-10-27 13:50
We can close this

**Closed** 2023-10-27 14:37 UTC
Labels: Engineering, Daily, Internal, Bug
