### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] dev: ESC keyboard shortcut shows up in modal on second render on login page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25448] opened 2023-08-17 23:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. signout if you are logged in
2. refresh the page
3. press cmd+j to open shortcut modal
4. now close the modal and observe content while it closes
5. now open it again
## Expected Result: 
ESC shortcut should always be shown in the modal
## Actual Result: 
ESC shortcut is visible for a brief moment while shortcut modal closes, later it is shown consistently
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4e93ed9a-bead-467a-8b89-85a616e2a08d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691493991739999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6b0de738da985ac</li>
        <li>Upwork Job ID: 1693559881555742720</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26508978</li>
<li>chiragxarora | Reporter | 26508980</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-17 23:44
## Proposal by @chiragxarora 

### Please re-state the problem that we are trying to solve in this issue.

ESC keyboard shortcut shows up in modal on second render on login page


### What is the root cause of that problem?

Root cause of this issue is as follows:
We add shortcuts to the modal via `documentedShortcuts` object and a shortcut gets added to it only when that shortcut is subscribed here in subscribe function

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/KeyboardShortcut/index.js#L135-L142

Now coming to the modal, we are subscribing to the ESC shortcut inside `subscribeOpenModalShortcuts` function here 

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L49-L56

And from when the page loads till the point we open the modal once using CMD+J, this piece of code never executes because `isShortcutsModalOpen` remains false till that point

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L128-L131

same case with second useEffect, where it always lands in the else object

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L143-L152

Thus the ESC shortcut is never subscribed until we open the modal once on login screen, unlike other places

Now once you open the modal, it gets subscribed, and now when you close it, you get to see the ESC shortcut for a brief moment and after that, we see it whenever we open the modal

### What changes do you think we should make in order to solve the problem?

We need to subscribe to openmodal shortcuts without any condition on modal mounting which essentially means the following changes: 

replacing this 

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L128-L131

with this 

```js
subscribeOpenModalShortcuts();
```

<details>
  <summary>Results</summary>


</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by Charan-hs** [comment] 2023-08-18 12:17
While reproducing this issue, I found another related bug.

### BUG
When logging out or signing out, the system will redirect to the login page. Now press `CMD+j`, we can see All `shortcuts`. Note that the list will disappear after reloading.

https://github.com/Expensify/App/assets/62904657/613dd205-b452-4a56-90e7-6a15f038c30e


should I report this in #expensify-bugs ?

**Comment by Charan-hs** [comment] 2023-08-18 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
ESC keyboard shortcut shows up in modal on second render on login page 

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L44
When the components load (initial), we call the function `KeyboardShortcut.getDocumentedShortcuts()` and store the result in the constant variable `shortcuts`. In `useEffect` we are calling`subscribeOpenModalShortcuts()` subscribe function but fail to handle any changes in the `shortcuts` variable. Based on changes we are not rendering it.


For this https://github.com/Expensify/App/issues/25448#issuecomment-1683834874 cause is 

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/KeyboardShortcut/index.js#L83-L87

When unsubscribing, we remove event listeners but not shortcuts from the variable `documentedShortcuts`.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L44

we can handle `shortcuts` variable  with `UseState` function so it will take care the onChanges render issue. 
```js
    const [shortcuts,setShortcurts] = useState([])
```
In these two places call `SetState` Function along with `subscribeOpenModalShortcuts()` 
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L143-L146

https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/components/KeyboardShortcutsModal.js#L127-L131

```js
if (isShortcutsModalOpen) {
            subscribeOpenModalShortcuts();
            setShortcurts(KeyboardShortcut.getDocumentedShortcuts())

        } 
```
We are setting the state when the modal is opened, Once the component unmounts reset the state.

https://github.com/Expensify/App/assets/62904657/8c9144e7-dcab-43d2-b3b6-1fca0a2ef9c3

**Comment by Charan-hs** [comment] 2023-08-18 13:15
> Yes, I kept this in notes too, felt unrelated to this so didn't add it here

I apologize, but I could not locate any information pertaining to the subject you mentioned.

**Comment by Charan-hs** [comment] 2023-08-18 13:25
for this https://github.com/Expensify/App/issues/25448#issuecomment-1683834874
here
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/KeyboardShortcut/index.js#L83-L87
we can remove the shortcuts based on the display name when `unsubscribing`
```js 
    documentedShortcuts = _.omit(documentedShortcuts,displayName);

```

**Comment by conorpendergrast** [comment] 2023-08-21 09:44
@Charan-hs, yes please report to #expensify-bugs! I'll hide the comments here for that separate bug, to keep this one focused on the bug in the OP

**Comment by mollfpr** [comment] 2023-08-22 14:26
I'll review the proposals in the morning; I ran out of time and got cold (again) 🙏

**Comment by Charan-hs** [comment] 2023-08-22 14:54
@tienifr 
When `KeyboardShortcutsModal` is mounted, it calls `KeyboardShortcut.getDocumentedShortcuts` to update the state and render changes. Event handlers are handled in [here](https://github.com/Expensify/App/blob/2b2bafd862bef999cf360d17e22535d48799c49f/src/libs/KeyboardShortcut/index.js).  we are only setting the state for viewing purposes, which also saves storage.

**Comment by mollfpr** [comment] 2023-08-23 15:42
@chiragxarora I think there will be a drawback: https://github.com/Expensify/App/pull/18425. Even thought we don't have it now, I'd like to keep the logic as it is.

@tienifr I don't think we need new Onyx keys for this where it can be avoided

I think using the local state seems to be working. It makes sense to me we get the current shortcuts list, and we only care to show the list when the shortcuts modal opens.

The [proposal](https://github.com/Expensify/App/issues/25448#issuecomment-1683898309) from @Charan-hs looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-08-23 15:44
@conorpendergrast Weird. Melvin didn't pull anyone from the internal engineer 🥲

**Comment by mollfpr** [comment] 2023-08-24 10:33
@Charan-hs Isn't it make sense to subscribe to the shortcut keys when the modal start open?

>And from when the page loads till the point we open the modal once using CMD+J, this piece of code never executes because isShortcutsModalOpen remains false till that point

On the sign-in account, `isShortcutsModalOpen` is also false, but the ESC is present in the shortcuts list.

> We don't have to use Onyx, other ways like creating a hook/adding a listener like KeyboardShortcut.onShortcutsUpdate( will also work.

@tienifr I don't know how the hook or listener you mention will be. Also, the issue you mention using the `useState` is that the `CMD + C` is not yet added to `documentedShortcuts` while the modal is open. In the @Charan-hs proposal, at least we got the current shortcuts documented before. 

I'm trying to think the solution doesn't need to be over-engineered, but if @conorpendergrast or @arosiclair thinks the shortcuts listed in the modal should be dynamic, I agree the `useState` solution is not enough.

**Comment by mollfpr** [comment] 2023-08-24 10:51
@tienifr Let's see what you propose in detail so I can get the idea.

**Comment by mollfpr** [comment] 2023-08-24 12:01
Sorry @Charan-hs, I meant to give feedback to @chiragxarora 😅

**Comment by mollfpr** [comment] 2023-08-24 14:51
@tienifr I think there are better choices than the hook solution. It's anti-pattern https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions

@Charan-hs I see that put `KeyboardShortcut.getDocumentedShortcuts()` into the dependencies, which led to the unexpected re-render.

![Screenshot 2023-08-24 at 21 40 39](https://github.com/Expensify/App/assets/25520267/2bc13ec5-a348-4ce7-b92f-c0d90eb9bfe5)

@conorpendergrast Does this shortcuts list need to be dynamic? It means that when the modal opens, there's some key shortcut documented, and the key will be added to the list of the modal. Currently, there is only one edge case when the user immediately opens the keyboard shortcuts modal right after the sign-in.

**Comment by arosiclair** [comment] 2023-08-24 15:05
It sounds like this new problem is that the shortcuts modal does not update if you open it while making some kind of page transition (signing in). IMO this isn't an edge case we need to worry about too much. @conorpendergrast thoughts?

**Comment by mollfpr** [comment] 2023-08-28 17:30
Bump @conorpendergrast to help clarify the expected result.

**Comment by conorpendergrast** [comment] 2023-08-29 08:04
If the sign-in flow is the *only* place that we'll encounter this bug, it does seem like it has limited scope to fix it. To confirm: there are no other places that we'll see this bug at the moment? If not, then I think we can close this out with payment to the bug reporter

**Comment by mollfpr** [comment] 2023-08-30 17:08
> there are no other places that we'll see this bug at the moment

I believe so. IMO, we should fix this 🤔

**Comment by arosiclair** [comment] 2023-08-31 14:57
Yeah we can fix the bug in the OP pretty easily with @Charan-hs's [proposal](https://github.com/Expensify/App/issues/25448#issuecomment-1683898309). The question is whether to "fix" the bug in other places (none of which have been found yet).

I think it's pretty clear to just fix the bug in the OP and if any other bugs are found, we can address them then. Does that sound good @mollfpr @conorpendergrast?

**Comment by conorpendergrast** [comment] 2023-08-31 14:59
Yeah, I agree with that. Let's fix the bug we've found here, and not go beyond that

**Comment by mollfpr** [comment] 2023-08-31 15:09
@arosiclair Sounds good to me 🚀

**Comment by mollfpr** [comment] 2023-08-31 15:57
IMO, the case [here](https://github.com/Expensify/App/issues/25448#issuecomment-1690833992) is a different issue, and I'd prefer to investigate why the shortcuts `CMD+C` is not documented at the same time as the other shortcut. The shortcuts should be documented when the app is ready to use, and the shortcuts modal can't be displayed before all the shortcuts are documented.

**Comment by charan-gowda007** [comment] 2023-09-04 17:39
@conorpendergrast, I mentioned the [bug](https://github.com/Expensify/App/issues/25448#issuecomment-1683834874) and [solution](https://github.com/Expensify/App/issues/25448#issuecomment-1683919324) , i.e while unsubscribing  keyboard shorcuts. 
With [this](https://github.com/Expensify/App/issues/25448#issuecomment-1686242373) approch found some issues.

1. In this approach, calling the `setState` function inside the `keyboard subscribe` function will result in the `keyboardModal` component rendering repeatedly. This means that every time we subscribe to a new keyboard shortcut, the `keyboardModal` component will render again unnecessarily, even if it is not currently mounted to the DOM. This causes unnecessary re-rendering, which can be avoided.
2. Getting Current values from `documentedShortcuts` and Sorting it before setting it and on every subscribed `keyboardShortcut` when setting a new state is a performance issue that needs to be addressed.
```js
shortcutsUpdateCallback(_.sortBy(_.values(documentedShortcuts), 'displayName'));
```
3. As I mentioned [here](https://github.com/Expensify/App/issues/25448#issuecomment-1691548951). This will also require a workaround to resolve this `side effect`.
4. I think it may be over-engineering this issue because it is mainly related to the browser platform, but we need to consider the performance issues it may cause in other platforms, which adds more complexity.
5. For [this](https://github.com/Expensify/App/issues/25448#issuecomment-1690833992) it is working fine as I mentioned [here](https://github.com/Expensify/App/issues/25448#issuecomment-1690875370)

cc: @arosiclair @mollfpr

**Comment by arosiclair** [comment] 2023-09-05 14:52
Sorry been busy never got back to this. Let's stick to the [original proposal we agreed on](https://github.com/Expensify/App/issues/25448#issuecomment-1683898309). @tienifr's solution is cool but adds complexity for not much benefit (opening the shortcuts list while signing in is an edge case to say the least).

**Comment by conorpendergrast** [comment] 2023-09-11 12:04
@Christinadobrzyn I'm on parental leave; re-assigning! A proposal has been accepted and is getting worked on at the moment

**Comment by Christinadobrzyn** [comment] 2023-09-15 19:08
preping for payment.. 

- @mollfpr do you think we need a regression test for this?
- @mollfpr you're paid through Upwork correct?
- @Charan-hs @chiragxarora are you paid through Upwork? if yes, can you please apply for the job here https://www.upwork.com/ab/applicants/1693559881555742720/job-details

**Comment by Christinadobrzyn** [comment] 2023-09-15 20:25
Just bringing up this [comment ](https://github.com/Expensify/App/issues/25448#issuecomment-1716030852)

The speed bonus timeline might need to be reevaluated. 

- Looks like the [PR](https://github.com/Expensify/App/pull/26809) was created on Sept 5th
- Final C+ [review](https://github.com/Expensify/App/pull/26809#pullrequestreview-1617333200) before merge was Sept 8th 
- Then there was a delay with the merge until Sept 11th because of a 'freeze'

So I think the bonus would actually apply here? @arosiclair @mollfpr?

**Comment by arosiclair** [comment] 2023-09-16 23:24
> So I think the bonus would actually apply here? @arosiclair @mollfpr?

Yeah that makes sense to me. There's no hard rule but [here's a thread where we talked about it](https://expensify.slack.com/archives/C01SKUP7QR0/p1693932194530649).

**Comment by mollfpr** [comment] 2023-09-19 15:57
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't make sure if there's a PR causing the regression. The implementation was already there years ago, and a lot of changes on our keyboard shortcut handle.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


The regression step should be enough.

>[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Sign out from the app
2. Refresh the page (for iOS and Android you need to close and reopen the app)
3. Press cmd+j to open the shortcut modal (testing on iOS and Android required to use physical keyboard)
4. Verify escape key has been added
5. 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2023-09-19 22:50
@chiragxarora I sent an Upwork invitation to you - here's the job posting - https://www.upwork.com/jobs/~01a6b0de738da985ac

**Comment by mollfpr** [comment] 2023-09-22 05:47
Friendly bump @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2023-09-22 21:23
Regression test: https://github.com/Expensify/Expensify/issues/319173

This issue was created before Aug 30th so we'll adhere to the old payment scale

Payouts due:

Issue Reporter: $250 @chiragxarora 
Contributor: $1000 + 500 speed bonus @Charan-hs 
Contributor+: $1000 + 500 speed bonus @mollfpr 

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/25448#issuecomment-1721826915

Upwork job is [here](https://www.upwork.com/jobs/~01a6b0de738da985ac). 

Paid! Thanks for all your help!

**Closed by Christinadobrzyn** 2023-09-22 21:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
