### ISSUE TITLE
Workspace - Company type dropdown in Adding bank account page (Step 2) is broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27334] opened 2023-09-13 12:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspace > any workspace > Bank account
3. Click Add manually
4. Proceed to Step 2
5. Click on the Company type dropdown

## Expected Result:
Company type dropdown is not broken

## Actual Result:
Company type dropdown is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-10

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a966e88a-e090-414b-a268-cdc248facf66

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment] 2023-09-13 12:51
## Proposal 
### Problem 
Company type dropdown in Adding bank account page (Step 2) is broken 
 
### Root cause
we are mapping a translation key which is a string to picker items.

### Changes
Create a array with incorporation types in constants, map the array to items like below 
```jsx
                    items={_.map(CONST.INCORPORATION_TYPES, (value) => ({ value: translate(`companyStep.incorporationTypes.${value}`),

```

**Comment by s-alves10** [comment] 2023-09-13 14:15
This is a regression of [this PR](https://github.com/Expensify/App/pull/25846)

**Comment by AndrewGable** [comment] 2023-09-13 16:59
Looks like this is going to be fixed by https://github.com/Expensify/App/pull/27358

**Comment by srikarparsi** [comment] 2023-09-18 01:11
Closing this one out since it's fixed [here](https://github.com/Expensify/App/pull/27358)

**Closed by srikarparsi** 2023-09-18 01:11 UTC
Labels: Reviewing, Engineering, Weekly
