### ISSUE TITLE
[$500] Display name fields aren't sanitized (remove blank space) after lose focus

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#28923] opened 2023-10-05 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/settings/profile/display-name
2. Type several blank space before name
3. Click in another input
4. You will see that the input is not changed (sanitized)
5. When you save and open again it would be sanitized
## Expected Result: 
input should remove any leading spaces (sanitization) before save to show user how it would be saved.
## Actual Result: 
The actual result is that the leading spaces are kept, and it is only removed when we save the inputs and open the edit page again, could be confuse to user.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/dec1115f-bd50-4ef9-9e63-0eeafc488d63

https://github.com/Expensify/App/assets/38435837/c4a2f956-ca98-4121-9f12-3a5c560cdca0

https://github.com/Expensify/App/assets/38435837/6c3fc83a-1dc3-46a1-89e3-9b72117bcd19

https://github.com/Expensify/App/assets/38435837/008db683-4a4f-4ca9-8b3d-2167a94b664a

https://github.com/Expensify/App/assets/38435837/ffc0a9f2-02c7-4dcc-8d01-f21c48a2d5b3

https://github.com/Expensify/App/assets/38435837/1f1f9448-f4c0-41c3-a93d-a7a87aa4261c

https://github.com/Expensify/App/assets/38435837/09d6263c-c54a-4961-91ef-1bed76e5529d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lcsvcn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696436594718049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6ec7bdd9f09b65b</li>
        <li>Upwork Job ID: 1709942839833063424</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 27330339</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-05 14:45
# Proposal by @lcsvcn
## Please re-state the problem that we are trying to solve in this issue
Display name fields aren't sanitized (remove blank space) after lose focus
## What is the root cause of that problem?
The root cause of the problem is that we are not sanitizing the field at the input loses focus, that way the input looks different then when it is saved.
## What changes do you think we should make in order to solve the problem?
We can avoid that bug with a simple solution, by setting the `onBlur` variable for the `TextInput` field. So it could trim any whitespace and do any sanitization we want between the actual input, so any white space before or after text gets removed after user input.
Below is an example on how to add to remove any space before or after the `first name` and `last name` input fields. We need to add that to both `TextInput` components. So that way when user finishes typing and the input loses focus, it will automatically remove any leading spaces, showing similar to how it is shown when user saves and open again.
I would also recommend using `onBlur` because it is good for application performance, since it is called only once the input loses focus.
At src/pages/settings/Profile/ProfilePage.js:
```Javascript
   <TextInput
       (...)
       onBlur={(input) => {
                            input.target.value = input.target.value.trim();
                        }}
    />
```
If we need to perform more actions in the sanitization, we could create a function to sanitize field and put in the `onBlur` function, similar to how I have done in the code above. But as far as I see, the only sanitization applied is to trim the text, removing any leading space.
## What alternative solutions did you explore? (Optional)
N/A

**Comment by zzarcon** [comment] 2023-10-06 10:45
# Proposal
 ## Please re-state the problem that we are trying to solve in this issue
 Display name fields aren't sanitized after lose focus
 
## What is the root cause of that problem?

The root cause of the problem is that we allow the user to type empty spaces which later get trimmed after saving.
 
## What changes do you think we should make in order to solve the problem?
 
We should reuse the exiting `validate` method to sanitize the values by calling `trimStart()`. Since that method already gets called when typing on the text field as well as on blur, we will not introduce new complexity nor new event listeners and the user experience will be more similar to to the end result


```src/pages/settings/Profile/DisplayNamePage.js```

 ```js
const validate = (values) => {
  values.firstName = values.firstName.trimStart()
  values.lastName = values.lastName.trimStart()
}
```
 

https://github.com/Expensify/App/assets/1194982/2223b88c-a6c5-46ef-a8d7-03200dabe53a


 
 ## What alternative solutions did you explore? (Optional)
 N/A

**Comment by zzarcon** [comment] 2023-10-06 11:30
Contributor details
Your Expensify account email: hezarco@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fd9d006e1408b804

**Comment by zzarcon** [comment] 2023-10-11 08:22
@ntdiary I agree with that, to achieve a consistent experience across the app having it built in within the input component will be the best. I just didn't know how big this issue was, also fair point with the mutation, if we want to keep `validate` purely for validation purposes it won't be the best place to do such thing :)

**Comment by zzarcon** [comment] 2023-10-13 08:03
> We can implement it in the generic component first and just enable for this case

I think that approach could work! I was playing with it and added a new opt-in prop to `<BaseTextInput>`, by default false

`src/components/TextInput/baseTextInputPropTypes.js`

```js
const propTypes = {
  /** Indicate whether or not the input should trim empty spaces */
  shouldSanitizeValue: PropTypes.bool,
}
```

and then handled the sanitization on `src/components/TextInput/BaseTextInput.js`

```js
const setValue = (value) => {
        const sanitizedValue = props.shouldSanitizeValue ? value.trimStart() : value;
}
```

and as you suggested, only enabled it from `<DisplayNamePage>`

`src/pages/settings/Profile/DisplayNamePage.js`

```jsx
<InputWrapper
    inputID="firstName"
    name="fname"
    shouldSanitize
/>

<InputWrapper
    inputID="lastName"
    name="lname"
    shouldSanitize
/>
```

It works the same as the video I shared before, let me know what you think about it @ntdiary

**Comment by twisterdotcom** [comment] 2023-10-16 11:45
Just waiting on @ntdiary's thoughts.

**Comment by twisterdotcom** [comment] 2023-10-19 12:40
@ntdiary do you have time for these this week? If not, I'll reassign on Monday.

**Comment by twisterdotcom** [comment] 2023-10-23 14:05
Looking for somebody else: https://expensify.slack.com/archives/C02NK2DQWUX/p1698069885201119

**Comment by situchan** [comment] 2023-10-23 14:08
I am not sure why this is bug. Why should input value be trimmed on blur?

**Comment by lcsvcn** [comment] 2023-10-23 14:17
@MelvinBot https://www.upwork.com/freelancers/~01686d9f62c3ed0541

**Comment by situchan** [comment] 2023-10-23 15:46
@luacmartins as form expert, can you please clarify the expected behavior?

**Comment by luacmartins** [comment] 2023-10-23 17:56
Thanks for the ping @situchan! I agree that this is not a bug. According to our [form guidelines](https://github.com/Expensify/App/blob/fe3e8bc3118816086bde2e28009a9018c41eba71/contributingGuides/FORMS.md#modifying-user-input-on-change):

>User input that may include optional characters (e.g. (, ), - in a phone number) should never be restricted on input, nor be modified or formatted on blur. This type of input jacking is disconcerting and makes things feel broken.
>
>Instead we will format and clean the user input internally before using the value (e.g. making an API request where the user will never see this transformation happen). Additionally, users should always be able to copy/paste whatever characters they want into fields.

**Comment by twisterdotcom** [comment] 2023-10-23 20:54
Nice okay, let's close.

**Closed by twisterdotcom** 2023-10-23 20:54 UTC
Labels: External, Daily, Help Wanted, Bug
