### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Category-Long category is truncated although space available

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30222] opened 2023-10-24 00:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Launch app as employee
2. Tap on Workplace chat
3. Tap plus icon near compose
4.Enter an amount
5.Tap next
6.Tap show more
7.Tap category
8.Select a long category "This: is: a: subcategory: with: lots: and: lots: of: levels: needALongerWordHereToTriggerTheLines"
## Expected Result:
When user selects a long category, for all available space it should be displayed and must not be truncated.

## Actual Result:
Long category selected is truncated although space available.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/43996225/c6478711-c8fd-4b23-957c-f8ca4b7b3dd3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e161f72a3cab57e</li>
        <li>Upwork Job ID: 1716617007537668096</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-10-24 02:55
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

Category-Long category is truncated although space available 
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/components/MoneyRequestConfirmationList.js#L697
here we missed flex1 style 


### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/d28247332f58bb0d4296b0eab49527771c03464c/src/components/MoneyRequestConfirmationList.js#L697
here we need to pass titleStyle={styles.flex1}

### Result
<img width="462" alt="Screenshot 2023-10-24 at 8 24 59 AM" src="https://github.com/Expensify/App/assets/16595846/ab81ed2a-57a5-48c6-a544-e415bf68469a">

**Comment by jjcoffee** [comment] 2023-10-26 14:05
@pradeepmdk's [proposal](https://github.com/Expensify/App/issues/30222#issuecomment-1776419587) LGTM. We do the same for other `MenutItems` on the same page, so it makes sense to do it again for this one. 

We _could_ add it as a prop as @Krishna2323 [suggested](https://github.com/Expensify/App/issues/30222#issuecomment-1776445571), but I think there's not much benefit to it (you still have to type out the prop, unless you have it as a default in which case I'd argue there's more value in requiring it to be actively set).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by pradeepmdk** [comment] 2023-10-27 07:06
@jjcoffee Pr is ready for review

**Comment by jjcoffee** [comment] 2023-10-27 15:34
Thanks! Will review on Monday :bow:

**Comment by pradeepmdk** [comment] 2023-10-31 09:00
@sophiepintoraetz  can you help me get an upwork contract?

**Comment by sophiepintoraetz** [comment] 2023-11-01 03:29
@pradeepmdk - just wait until we hit the regression period - I see it's just merged.

**Comment by jjcoffee** [comment] 2023-11-02 10:24
- The PR that introduced the bug has been identified. Link to the PR: **N/A - looks like a missed case from the beginning**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes - easy enough to test for!**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. Set up a Workspace category that is long enough to exceed the screen width, e.g. "This: is: a: subcategory: with: lots: and: lots: of: levels: needALongerWordHereToTriggerTheLines"
2. On newDot, go to the Workspace chat, tap the plus icon near the composer and request money.
3. Enter any amount and tap next.
4. Tap show more and then tap category.
5. Select the long category from step 1.
6. Verify that the category name displays with all available space filled and the rest being truncated.

Do we agree 👍 or 👎

**Comment by sophiepintoraetz** [comment] 2023-11-09 03:42
Offers sent!

**Closed by sophiepintoraetz** 2023-11-09 03:42 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jjcoffee** [comment] 2023-11-09 09:56
Thanks @sophiepintoraetz! Just a heads up there were two offers sent, I've only accepted one :wink:
