### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500]  Chat - Creating a new line in composer causes the composer to jump when expanding

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27892] opened 2023-09-20 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Click on the composer
4. Create a new line by Shift + Enter

## Expected Result:
The composer does not jump when expanding

## Actual Result:
The composer jumps when expanding

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] MacOS / Desktop
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/59e94b7c-8bbe-444f-9570-28a17e62bce5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199195af3f24f9d73</li>
        <li>Upwork Job ID: 1705074693317824512</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26864648</li>
</ul></li>
    </ul>
</details>

**Comment by tylerkaraszewski** [comment] 2023-09-20 23:05
I've confirmed this happens but I'm not sure where to look to fix it.

**Comment by s-alves10** [comment] 2023-09-21 04:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Creating a new line in the main composer causes the composer to jump while expading

### What is the root cause of that problem?

We determine the vertical padding here based on `numberOfLinesProp`
https://github.com/Expensify/App/blob/5ff88b7cdbee274c0f666e504b73355d0c2737ae/src/components/Composer/index.js#L447

And we pass `numberOfLines` props to `RNTextInput` component here
https://github.com/Expensify/App/blob/5ff88b7cdbee274c0f666e504b73355d0c2737ae/src/components/Composer/index.js#L468

The problem is in the mismatch of `numberOfLines` and `numberOfLinesProp`
When needed, we change both the `numberOfLines` state and `numberOfLinesProp` here
https://github.com/Expensify/App/blob/5ff88b7cdbee274c0f666e504b73355d0c2737ae/src/components/Composer/index.js#L364-L366

but changing `numberOfLinesProp` requires Onyx merge and takes some more time
https://github.com/Expensify/App/blob/5ff88b7cdbee274c0f666e504b73355d0c2737ae/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L232

So `numberOfLinesProps` changes a little bit later than `numberOfLines` state
This makes the composer jump

### What changes do you think we should make in order to solve the problem?

We don't need to calculate the vertical padding based on `numberOfLinesProps` props. We have `numberOfLines` state and get padding based on this. This makes more sense than using props because this value represent the current state of the composer. 

```
    const inputStyleMemo = useMemo(
        () => [
            // We are hiding the scrollbar to prevent it from reducing the text input width,
            // so we can get the correct scroll height while calculating the number of lines.
            numberOfLines < maxLines ? styles.overflowHidden : {},

            StyleSheet.flatten([style, {outline: 'none'}]),
            StyleUtils.getComposeTextAreaPadding(numberOfLines, isComposerFullSize),
        ],
        [style, maxLines, numberOfLines, isComposerFullSize],
    );
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/f2cfcf35-08d7-4657-855e-7743bcda04ef


</details>


### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2023-09-21 08:50
Let's fix this, but removing the blocker as it is a minor bug and shouldn't block deploy

**Comment by robertKozik** [comment] 2023-09-25 11:10
@s-alves10 Great proposal, lets proceed with it! 
🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment] 2023-09-25 19:46
@robertKozik 

PR https://github.com/Expensify/App/pull/28188 is ready for review

**Comment by s-alves10** [comment] 2023-10-03 22:16
The PR was merged without any change

**Comment by johncschuster** [comment] 2023-10-16 20:45
Payment has been issued to @s-alves10

**Comment by johncschuster** [comment] 2023-10-16 20:45
@robertKozik can you complete the BZ Checklist when you get a moment? Thank you!

**Comment by robertKozik** [comment] 2023-10-16 20:59
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR:  **I cannot find any particular PR which introduce it. I believe it was overlooked during implementation**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think we need it here. This bug didn't block any crucial user flow**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

CC. @johncschuster

**Comment by johncschuster** [comment] 2023-10-19 19:52
Sweet! Thank you!

**Closed** 2023-10-19 19:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
