### ISSUE TITLE
[HOLD for payment 2024-06-28] Search - App shows "Nothing to show" card when the sorting is applied for the first time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43899] opened 2024-06-18 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has submitted a few expenses.

1. Go to staging.new.expensify.com
2. Log out and log in again if sorting has been applied before (or reset cache and restart).
3. Go to Search.
4. Click on any sorting.

## Expected Result:
App will not show "Nothing to show" card when the sorting is applied for the first time.

## Actual Result:
App shows "Nothing to show" card when the sorting is applied for the first time.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/27051564-11be-4903-8685-d0bbddc6195d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by m-natarajan** [comment] 2024-06-18 13:02
@arosiclair FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-18 13:02
We think that this bug might be related to  #vip-vsb

**Comment by arosiclair** [comment] 2024-06-18 14:01
I reproduced in staging **v1.4.85-0** and not on prod **v1.4.84-3**

**Comment by arosiclair** [comment] 2024-06-18 14:32
Looks like this is caused by the Onyx upgrade here: https://github.com/Expensify/App/pull/43764. Reverting the PR fixes the issue. cc @luacmartins

**Comment by arosiclair** [comment] 2024-06-18 14:58
I'm looking into a fix without reverting the Onyx upgrade

**Comment by arosiclair** [comment] 2024-06-18 15:19
Alright I think I have an easy fix for this. It looks like we're not doing a good enough job checking if `currentSearchResults.data` is empty [here](https://github.com/Expensify/App/blob/f6085d284bfb69c837fbac7e3b4e3fba9853df26/src/components/Search.tsx#L52-L57). Going to post a PR to fix it.

**Comment by luacmartins** [comment] 2024-06-18 15:47
Thanks for working on this @arosiclair!

**Comment by jnowakow** [comment] 2024-06-19 09:19
I don't think it's a problem with new Onyx version. I installed version `2.0.48` and I'm still able to see the problem. I wasn't able to see complete lack of data but I'm able to reproduce the case where for a short while some rows are missing. Here is the screenshot with version `2.0.48`:

<img width="1613" alt="image" src="https://github.com/Expensify/App/assets/56261019/af152a1f-ac1e-43b4-a2e1-0f5be1c658be">

I was printing data to the console and as you can see the change of column order caused one row to disappear. So I think that the problem is in fact that each change of filter and order is causing hash change and new request to the backend to fetch data. We guard against displaying empty page with this fragment of code: 

```
    const hash = SearchUtils.getQueryHash(query, policyIDs, sortBy, sortOrder);
    const [currentSearchResults, searchResultsMeta] = useOnyx(`${ONYXKEYS.COLLECTION.SNAPSHOT}${hash}`);

    // save last non-empty search results to avoid ugly flash of loading screen when hash changes and onyx returns empty data
    if (currentSearchResults?.data && currentSearchResults !== lastSearchResultsRef.current) {
        lastSearchResultsRef.current = currentSearchResults;
    }

    const searchResults = currentSearchResults?.data ? currentSearchResults : lastSearchResultsRef.current;
 ```

There's problem that if we already have some data for given hash but they are out of date we will show them and when refreshed data arrives the list will be re-rendered.

**Comment by luacmartins** [comment] 2024-06-19 17:10
@jnowakow the issue was that we were always applying an empty object merge, so if we had no data so that `snapshot_.data = undefined`, we'd apply the `{}` merge and then get `snapshot_.data ={}` which would trigger the empty state view. My [fix](https://github.com/Expensify/react-native-onyx/pull/562/files) prevents that unnecessary merge which fixes the empty state issue.

**Comment by dylanexpensify** [comment] 2024-07-01 12:03
Payment summary: 
- Contributor: @allgandalf $250

[Please apply](https://www.upwork.com/jobs/~01b2eb13879f8ba1d5)!

**Comment by dylanexpensify** [comment] 2024-07-03 08:15
Nice! Paying now

**Comment by dylanexpensify** [comment] 2024-07-08 11:21
Sent offer @allgandalf!

**Comment by dylanexpensify** [comment] 2024-07-12 13:12
Done!

**Closed by dylanexpensify** 2024-07-12 13:12 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
