### ISSUE TITLE
Email Tests – Large space between paragraphs in the email formatting

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#50797] opened 2024-10-15 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5051314

**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.expensify.com/
2. Create account using Get started button and select the option “Manage expenses for a small team”
3. Wait 24 hours for the email to be sent few times and view emails

## Expected Result:
Normal space and formatting between paragraphs in the email

## Actual Result:
Large space between paragraphs in the email

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9736b99c-cb62-45df-917d-c3b84fe63a7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment] 2024-10-15 13:26
@marcochavezf assigned you to this one since this was found on the weekly tests for the Email promos. The formatting is off and uncomfortable to read in some of them. Lmk if you would need screenshots for the rest of them and I can post them here.

**Comment by marcochavezf** [comment] 2024-10-15 18:09
Thanks for the issue Isa! We're already addressing the formatting of those emails. I will post an update here when the formatting is fixed.

**Comment by sakluger** [comment] 2024-10-15 21:19
@marcochavezf do you have a PR or another issue that you could link so we can track progress? And is daily the right priority, or would weekly be more appropriate?

**Comment by sakluger** [comment] 2024-10-16 16:14
I'm adding this to the `#convert` project board because it affects emails that are being sent to new leads. It could probably also fall under `#quality`, but it should be fixed soon so doesn't matter too much either way.

**Comment by marcochavezf** [comment] 2024-10-16 17:41
Sure, these are the issues related to this one:
- https://github.com/Expensify/Expensify/issues/433372
- https://github.com/Expensify/Expensify/issues/434797

**Comment by sakluger** [comment] 2024-10-17 20:54
Given we have those two other GH issues, I'm going to close this one as a duplicate.

**Closed by sakluger** 2024-10-17 20:54 UTC
Labels: Daily, Bug
