### ISSUE TITLE
[HOLD for payment 2024-05-02] [Guided Setup] [$125] Minor copy modifications to Stage 1 onboarding

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#40317] opened 2024-04-16 22:23 UTC
Change the intent itself from `I'm just looking around` to `Something else`
Change the intent specific message to 
```
# Welcome to Expensify! 

Hi there, I'm Concierge. Chat with me here for anything you need. 

Expensify is best known for expense and corporate card management, but we do a lot more than that. Let me know what you're interested in and I'll help get you started. 
```

cc @danielrvidal @zsgreenwald @quinthar 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f552ed32ec3ecab0</li>
        <li>Upwork Job ID: 1780786390866116608</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by sufyan-siddiqui** [comment] 2024-04-18 04:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Change the intent message after onboarding from `I'm just looking around` to `Something else`

### What is the root cause of that problem?
The message is defined as a constant variable `CONST.ONBOARDING_CHOICES.LOOKING_AROUND` in the language specific constant files. For English its in 

[App/src/languages/en.ts](https://github.com/Expensify/App/blob/1a20e163dad22c89b1242a4c167216ff034923e6/src/languages/en.ts)
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/languages/en.ts#L1330

And the for Spanish its in

[App/src/languages/en.ts](https://github.com/Expensify/App/blob/1a20e163dad22c89b1242a4c167216ff034923e6/src/languages/es.ts)
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/languages/es.ts#L1329

### What changes do you think we should make in order to solve the problem?


For the quick fix for just the message only, we can change the constant `CONST.ONBOARDING_CHOICES.LOOKING_AROUND`  in the en.ts file to `Something else` and in the es.ts file to `Otra cosa` or any appropriate translation in this case.

### What alternative solutions did you explore? (Optional)

Since the constants were defined with the message `I'm just looking around` in mind, so they're named `LOOKING_AROUND` as well. For further enhancement, the constant names should also be updated to `SOMETHING_ELSE`. Consequently. there references in the below files should be updated.

[src/CONST.ts](https://github.com/Expensify/App/blob/main/src/CONST.ts)

[src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx](https://github.com/Expensify/App/blob/main/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx)

Another update would be the Icon. Currently the Binoculars icon is assigned to the choice because it made more sense given the looking around message. The icon should be updated to any appropriate icon that relates well with the choice "Something else" in the below line

https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L39

**Comment by nkdengineer** [comment] 2024-04-18 05:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Minor copy modifications to Stage 1 onboarding

### What is the root cause of that problem?
This is a new requirement

### What changes do you think we should make in order to solve the problem?

There're 2 changes we need to make:
1. Update the text here https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/languages/en.ts#L1330
to `Something else`, and also the Spanish version

We should also update the key to `CONST.ONBOARDING_CHOICES.SOMETHING_ELSE`

2. The other requirement is `Change the intent specific message`, for which we need to add a new key [here](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/CONST.ts#L3550) for `onboardingChoices.LOOKING_AROUND`, with the text specified in the OP
```
# Welcome to Expensify! 

Hi there, I'm Concierge. Chat with me here for anything you need. 

Expensify is best known for expense and corporate card management, but we do a lot more than that. Let me know what you're interested in and I'll help get you started. 
```
We'll use string concatenation like we did with messages for other use case [here](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/CONST.ts#L3552-L3554)

Then it will be automatically applied because we're adding the text based on `selectedPurpose` as in [here](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L86)

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-18 06:53
[Proposal updated](https://github.com/Expensify/App/issues/40317#issuecomment-2063045339) to add suggestion for the intent message to be consistent with other use cases.

@jjcoffee Just a small note that my proposal is the first one that gets it working for the OP description, in case we want to change the OP, like the intent message, it's just a small text change that can be addressed in the PR phase.

**Comment by jjcoffee** [comment] 2024-04-19 12:23
Thanks for the proposals, everyone! As this is a very small issue, getting the proposal details right is what matters the most. It looks like @GandalfGwaihir was the first to get extra detail regarding the correct text to add to the `onBordingChoices`, so I think we can go with their [proposal](https://github.com/Expensify/App/issues/40317#issuecomment-2060035488).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by rlinoz** [comment] 2024-04-19 14:35
Sounds good, assigning @GandalfGwaihir

**Comment by abekkala** [comment] 2024-05-02 19:47
### PAYMENT SUMMARY:

- FIX: @GandalfGwaihir [$125] payment sent and contract ended - thank you  🎉
- PR REVIEW: @jjcoffee [$125] payment sent and contract ended - thank you 🎉

**Closed by abekkala** 2024-05-02 19:47 UTC
Labels: External, Daily, Awaiting Payment
