### ISSUE TITLE
[HOLD for Payment 2024-08-22][$250] Edit Modal Not Opening by up arrow After Holding Expense and Returning to Thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46391] opened 2024-07-28 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Account Settings > Workspace > Create Workspace
2. From LHN, navigate to Workspace Chat
3. Click the plus sign > Submit Expense > Add Amount > Add Merchant
4. Confirm the expense, go to the thread, and go to details. Click "Hold
5. Add a reason and hold the expense. Exit the thread
6. Return to the thread and click the up arrow. Notice that the edit modal does not open

## Expected Result:
The up arrow should always open the edit modal when the message is edited

## Actual Result:
After holding the expense and exiting the thread, upon returning, the message appears in the composer, but the edit modal does not open when the up arrow is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2138e99c-39a9-4e6a-9d66-4554bbd37066

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ca23291c558a731</li>
        <li>Upwork Job ID: 1817972655286208144</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment] 2024-07-28 23:28
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-28 23:28
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-07-29 02:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing arrow up key doesn't open the edit composer in one-transaction report if the last message is the hold reason message.

### What is the root cause of that problem?
The up arrow key to edit will only work if lastReportAction (editable) exists.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L520-L523

However, in our case, it's undefined.

`lastReportAction` is built from the report `reportActions` + `parentReportAction` then iterated to find the first editable message. But the hold message is the transaction thread message, so it isn't included in `reportActions` of the one-transaction (IOU) report.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/home/ReportScreen.tsx#L325-L331

### What changes do you think we should make in order to solve the problem?

Combine the `reportActions` with the transaction thread report actions like we did in ReportActionsView.
```
const transactionThreadReportID = ...;
const [transactionThreadReportActions = []] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThreadReportID}`, {
    canEvict: false,
    selector: (reportActions) => ReportActionsUtils.getSortedReportActionsForDisplay(reportActions, true), 
});
const lastReportAction: OnyxEntry<OnyxTypes.ReportAction> = useMemo(
    () =>
        reportActions.length
            ? [...ReportActionsUtils.getCombinedReportActions(reportActions, transactionThreadReportID ?? null, transactionThreadReportActions), parentReportAction].find((action) => ReportUtils.canEditReportAction(action) && !ReportActionsUtils.isMoneyRequestAction(action))
            : undefined,
    [reportActions, parentReportAction],
);
```

### What alternative solutions did you explore? (Optional)
Create a new context and wrap it in ReportScreen. This context will hold a ref to the combined report actions. We will update the ref every time the `combinedReportActions` here is changed.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/home/report/ReportActionsView.tsx#L224-L227

```
useEffect(() => {
    // set ref
    return () => // clears the ref
}, [combinedReportActions])
```

Then, when the user presses the arrow up key, we will get the report actions ref and do the filter here.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L520-L523
```
if (key === 'UP && ...) {
    const lastAction = reportActionsContext.reportActions.find((action) => ReportUtils.canEditReportAction(action) && !ReportActionsUtils.isMoneyRequestAction(action));
    ...
}
```
This will prevent any unnecessary and heavy re-render.

**Comment by bernhardoj** [comment] 2024-08-01 02:46
It's still reproducible. You need to do it in a one-transaction report.
https://github.com/user-attachments/assets/941d0cdc-82c4-4215-8a59-ed4398794149

**Comment by puneetlath** [comment] 2024-08-05 17:01
@fedirjh thoughts on the proposal?

**Comment by bernhardoj** [comment] 2024-08-07 03:51
> Why doesn't this bug appear in a multi-transaction report?

It only happens in one-transaction report because the report combines report action from the expense and transaction thread. The hold reason report action message is from the transaction thread.

> Can you please clarify how you intend to get the value of transactionThreadReportID, considering that it is calculated later in the code?

We can just move up the definition.

https://github.com/Expensify/App/blob/de894796363ad1bc42fa360c6d7b74f8a26c4b61/src/pages/home/ReportScreen.tsx#L341-L344

**Comment by bernhardoj** [comment] 2024-08-09 06:29
PR is ready

cc: @fedirjh

**Comment by iwiznia** [comment] 2024-09-04 12:09
Just came here to say that right now I can't edit messages with up arrow at all

**Comment by puneetlath** [comment] 2024-09-11 20:24
Wait, so what's the status of this? Does this need to be paid? Or is there a regression outstanding?

**Comment by bernhardoj** [comment] 2024-09-12 04:34
Yes, the payment is pending. No regression.

**Comment by johncschuster** [comment] 2024-09-12 14:42
I'd also love to get a little clarity on the status of this and how it might affect payment on the [issue I was assigned](https://github.com/Expensify/App/issues/48549).

In the issue assigned to me, @fedirjh called out a regression ([comment](https://github.com/Expensify/App/issues/48549#issuecomment-2329515334)). Is that a regression from the fix from _this_ issue, or from something else?

**Comment by bernhardoj** [comment] 2024-09-12 15:31
It's a regression from another issue (https://github.com/Expensify/App/pull/48234)

**Comment by puneetlath** [comment] 2024-09-13 03:40
Payment summary: 
- C - $250 - @bernhardoj  - to be paid via NewDot
- C+ - 250 - @fedirjh - to be paid via NewDot

Thanks everyone! Please go ahead and request payment.

**Closed by puneetlath** 2024-09-13 03:40 UTC
Labels: Reviewing, External, Monthly, Bug

**Comment by bernhardoj** [comment] 2024-09-13 04:15
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-13 11:29
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-10-23 10:18
$250 approved for @fedirjh
