### ISSUE TITLE
Track expense - "Only visible to you" whisper appears after scanning is complete

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43839] opened 2024-06-17 14:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Go to + > Track expense > Scan.
4. Upload a valid receipt.
5. After 30 minutes, go to Troubleshoot > Clear cache and restart > Reset and refresh (because tracked expense won't update on its own after scanning is complete).
6. Go to self DM.

## Expected Result:
"Only visible to you" whisper will not appear after scanning is complete.

## Actual Result:
"Only visible to you" whisper appears after scanning is complete.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/ef3b787a-fa4b-4022-9ffb-3a190bfbb39e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-06-17 14:54
@rlinoz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-17 14:54
We think that this bug might be related to  #vip-vsb

**Comment by rlinoz** [comment] 2024-06-17 15:20
I am seeing this in both prod and staging, can you please confirm @m-natarajan?

**Comment by m-natarajan** [comment] 2024-06-17 16:53
@rlinoz in production, `only visible to you` is not shown when receipt is scanning and also after completed. But in staging it does show when scanning and even after completed. 
Not sure if this is same RCA as #42169

**Comment by rlinoz** [comment] 2024-06-17 17:46
Oh I got it...yeah, it looks like the same root cause as the issue you pointed to, thanks!

Although it is weird that it doesn't happen in prod, let me investigate.

**Comment by rlinoz** [comment] 2024-06-17 18:38
Ok, it is coming from this changes from 0 to -1: https://github.com/Expensify/App/commit/93a45ce889767c544fec534aa4a5b6adddf62a90#diff-f0bdc7ab41060e24e6bcdc847f25185b372c5f9a072251fe5d3cae2a27887920R519

I don't think they are doing anything wrong, it just uncovers the same problem the other issue linked issue https://github.com/Expensify/App/issues/42169 is addressing.

We can close this in favor of that issue, given the real problem is in the backend since the message has the properties to make it a whisper.

**Comment by rlinoz** [comment] 2024-06-17 18:40
Closing in favor of https://github.com/Expensify/App/issues/42169

**Closed by rlinoz** 2024-06-17 18:40 UTC
Labels: Engineering, Hourly, Bug
