### ISSUE TITLE
[HOLD for payment 2023-05-16] Login - Text "Link sent" doesn't appear and link is not sent after Unlink button clicked, console error appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18526] opened 2023-05-06 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/15811

## Action Performed:
1. Login to account A and add a secondary login B, do not validate it
2. Logout from A
3. Input B email on login screen and click Continue
4. Click Unlink button

## Expected Result:
1. "Link sent" should appear on the screen. Link should be sent.
2. No console error appears

## Actual Result:
Web + mWeb: "Link sent" doesn't appear, link is not sent.
Android and IOS apps: app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** New Feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

**Web issue**

https://user-images.githubusercontent.com/93399543/236636536-42b2b7bd-936f-4fd3-95f2-1955072a4e69.mp4

![image (37)](https://user-images.githubusercontent.com/93399543/236636660-7a6b1c57-567c-4f5b-af46-631ec858dbc6.png)

**App crashed**

https://user-images.githubusercontent.com/93399543/236636619-e68c989d-341f-4eb4-82d4-5d013f1036b5.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @natnael-guchima

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d970f1e853d9ed1</li>
        <li>Upwork Job ID: 1656945072873746432</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-05-07 10:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unlink button doesn't work on web (throw a console error) and crash on Android/iOS.

### What is the root cause of that problem?
The console error already clearly state the error is can't read `METHOD` of undefined. We are reading it from CONST.ONYX, but this PR https://github.com/Expensify/App/pull/18464 already drop that const, and we should use Onyx.METHOD instead.

### What changes do you think we should make in order to solve the problem?

We should replace CONST.ONYX.METHOD with Onyx.METHOD to these functions:
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/libs/actions/Session/index.js#L653-L715

**Comment by roryabraham** [comment] 2023-05-09 00:06
Grabbing this quick fix to get it in before the deploy

**Comment by roryabraham** [comment] 2023-05-09 00:31
Merged [a fix](https://github.com/Expensify/App/pull/18619)

**Comment by Natnael-Guchima** [comment] 2023-05-09 01:03
Helllo @roryabraham. I have reported this issue. Is this eligible for bonus reporting? 
Thanks.

**Comment by roryabraham** [comment] 2023-05-10 06:06
Reopening for reporting bonus

**Comment by roryabraham** [comment] 2023-05-10 06:06
@greg-schroeder the only payment due here is the $250 reporting bonus. Thanks!

**Comment by greg-schroeder** [comment] 2023-05-12 08:32
Got it, I'll take care of it on 5/16~

**Comment by greg-schroeder** [comment] 2023-05-12 08:50
I'm going to apply `Internal` just to generate an Upwork job

**Comment by greg-schroeder** [comment] 2023-05-12 08:53
Started a reporting bonus contract for @Natnael-Guchima

**Comment by Natnael-Guchima** [comment] 2023-05-12 08:56
> Started a reporting bonus contract for @Natnael-Guchima

Accepted. Thanks.

**Closed** 2023-05-12 11:51 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
