### ISSUE TITLE
Web – Chat – The tooltip remain visible for an extended period when two messages are repeatedly marked as "Mark as unread."

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24032] opened 2023-08-02 03:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any chat conversation.
2.	Quickly mark any two messages as "Mark as unread" back and forth.
3.	Notice that the tooltip above "Mark as unread" remains visible for a significant amount of time.

## Expected Result:
The tooltip for "Mark as unread" should disappear promptly after being clicked.

## Actual Result:
The tooltip for "Mark as unread" does not disappear after being clicked.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3 
**Reproducible in staging?:** Y 
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/f74484b0-6c92-495d-a7fb-d6f05a5a8bdf

https://github.com/Expensify/App/assets/43995119/f40be83e-24d6-4264-99b4-ec61a71d8319

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690787341292089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-02 03:28
This issue looks a dupe of https://github.com/Expensify/App/issues/1923

**Comment by mvtglobally** [comment] 2023-08-02 03:32
@s-alves10  Can you pls update the issue id. It would be helpful

**Comment by isabelastisser** [comment] 2023-08-04 20:40
This seems to be the same [issue](https://github.com/Expensify/App/issues/16923). I think this is a dupe, closing!

**Closed by isabelastisser** 2023-08-04 20:40 UTC
Labels: Daily, Overdue, Bug
