### ISSUE TITLE
Workspace - "Manage members" invite list is displaying square grey icons

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9157] opened 2022-05-24 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: User has a workspace created
1. Access staging.new.expensifail.com
2. Sign into an applause.expensifail.com account
3. Turn off the internet connection by enabling "Airplane" mode
4. Tap on the "Profile" icon > "Workspace" > "Manage members"
5. Tap on "Invite" while offline

## Expected Result:
The user expects to see the icon color loaded and if this is not possible the user expects to see a grey circle icon next to each name

## Actual Result:
The user sees grey square icons that change to circles upon scrolling down or upwards

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.66.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any expensifail account

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/170136391-e272f57a-1deb-4122-84fe-56cff79df733.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-06-29 20:14
Most likely will be addressed in the refactor, we can address this again if it comes up still

**Comment by ctkochan22** [comment] 2022-08-01 15:57
Waiting on refactor

**Comment by arosiclair** [comment] 2022-09-16 16:39
Can't reproduce this on staging or in dev I believe this should be fixed by now if it was an issue:

<img width="1912" alt="Screen Shot 2022-09-16 at 12 16 12 PM" src="https://user-images.githubusercontent.com/6833644/190685781-3a34534a-65fa-48dd-8d68-d33fe262f5e0.png">

<img width="1912" alt="Screen Shot 2022-09-16 at 12 17 45 PM" src="https://user-images.githubusercontent.com/6833644/190685786-1890ac8b-4a3d-4126-bdde-7b4686ded654.png">

**Closed by arosiclair** 2022-09-16 16:39 UTC
Labels: Engineering, Monthly, Improvement
