### ISSUE TITLE
[$250] Submit - $0.00 report is shown when moving expense to a new report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48994] opened 2024-09-11 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Create a workspace add an employee

As an employee
1. Go to OD and create a report on the workspace
(make sure to open the ND workspace chat as well.)
2. Add a expense on the report
3. Delete the expense(Not the report)
4. Create a new report on the OD and add two expense
5. Move one of the expense to a new report
6. Go to ND and notice that the moved expense is shown as $0.00.
Note: Switching chats, refreshing and also going to the report brings the correct amount)

## Expected Result:
Moved expense show the correct amount of money.

## Actual Result:
Moved expense shows $0.00 on ND. The correct amount comes only after navigating to the report

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/99f3b352-0bd4-40e9-8182-0e32724d8001

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833945245991752277</li>
        <li>Upwork Job ID: 1833945245991752277</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 16:01
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abhinaybathina** [comment] 2024-09-12 08:51
I'm able to reproduce this, I'll look into this

**Comment by jestinjoshi** [comment] 2024-09-13 00:17
I've investigated the issue, and it appears that the problem lies not with the frontend but with the API call for `GetMissingOnyxMessages`. This API is not returning the updated total for the report, which is why the frontend isn't reflecting the changes. 

However, when a user switches to a different chat and then returns to the original chat, the `OpenReport` API is triggered, and it successfully retrieves the updated total for the report, allowing the user to see the correct information.

@s77rt @greg-schroeder

**Comment by AttockOffice85** [comment] 2024-09-13 05:48
hi @jestinjoshi and other folks 

I’ve tried reproducing the issue following the description and video, but it’s a bit unclear and takes some time to follow. 
In my case, everything seems to work fine. 
Could someone please provide clearer steps or confirm if they can reproduce the issue?

**Comment by s77rt** [comment] 2024-09-13 10:15
@jestinjoshi Were you able to reproduce the bug? In my case I didn't get the moved expense showing up at all, I had to switch chats and got it correctly


https://github.com/user-attachments/assets/1330b8f9-92bc-4f79-99ce-674a2cd7e83c

cc @AttockOffice85 above video may help

**Comment by Michael-Obele** [comment] 2024-09-13 11:40
Hey folks, just as @jestinjoshi mentioned, I also believe it's from the API call, and I think adding a useMemo would fix the problem.

**Comment by Michael-Obele** [comment] 2024-09-13 11:45
Contributor details
Your Expensify account email: amachree9630@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010aff84665e3ea1e9

**Comment by jestinjoshi** [comment] 2024-09-13 13:04
I was able to reproduce the issue, but not following the steps outlined by OP.

To reproduce the issue: 
1. Ensure that the report is visible in the ND workspace chat.
2. Go to OD and update the report by adding additional expenses.
3. While the report is displayed on the ND, add an emoji reaction to the report. This action will trigger the `GetMissingOnyxMessages` API call to refresh the report. Note that sometimes the API gets triggered automatically by Pusher, but I haven't been able to figure out the exact conditions for this behavior.
4. After the API call, note that the number of expenses in the report updates correctly, but the total amount does not reflect the new value.

The total is calculated from `iouReport` which is not being updated with the latest total value. 

To fix this issue, `GetMissingOnyxMessages` API should return `iouReport.total` (`report_{reportKey}`) in its response.

@AttockOffice85 @s77rt @Michael-Obele

**Comment by s77rt** [comment] 2024-09-13 13:44
@Michael-Obele Can you please elaborate how this is a backend issue and were you able to reproduce the bug?

**Comment by s77rt** [comment] 2024-09-13 13:45
@jestinjoshi That's a different bug. I still get the expense itself showing the correct amount

**Comment by Michael-Obele** [comment] 2024-09-13 14:08
> @Michael-Obele Can you please elaborate how this is a backend issue and were you able to reproduce the bug?

Although I have not quite figured it out, I believe the issue is more with how the component retrieves the balance after the money is moved to a different category. 
For this reason, I proposed using a useMemo to include the balance so it is recomputed after the money is moved to a different category.

**Comment by jestinjoshi** [comment] 2024-09-13 14:13
> That's a different bug. I still get the expense itself showing the correct amount

@s77rt OP is highlighting an issue where the correct total amount is not being updated, as described in their `Expected Result` section. If you watch the end of the video shared by OP, you'll notice that when they move the expenses to a new report, the number of expenses is updated, but the total amount in the report does not reflect the correct value.

Although I followed a different set of steps to reproduce the issue, the core problem remains the same.

**Comment by jestinjoshi** [comment] 2024-09-13 16:01
@s77rt I was able to reproduce the issue and have created a video with audio explaining the problem. As mentioned earlier, the issue is still related to the `GetMissingOnyxMessages` API. I hope the video helps clarify the problem.


https://github.com/user-attachments/assets/881f507b-9a0b-48bf-a86d-3ed437af19f3

**Comment by greg-schroeder** [comment] 2024-09-17 01:04
@madmax330 can you confirm this should be an `Internal` issue based on the above discussion? I'm not super sure on the BE requirements here

**Comment by madmax330** [comment] 2024-09-17 17:02
I'll check tomorrow

**Comment by s77rt** [comment] 2024-09-17 17:26
Not overdue

**Comment by s77rt** [comment] 2024-09-20 20:51
@madmax330 Did you get a chance to look at this?

**Comment by greg-schroeder** [comment] 2024-09-27 19:42
I think still waiting on @madmax330 to let us know what he found 👍

**Comment by madmax330** [comment] 2024-10-02 07:46
I'm going to look into this this week, was focused on some fast api issues.

**Comment by greg-schroeder** [comment] 2024-10-08 21:25
Max is still looking!

**Comment by madmax330** [comment] 2024-10-14 13:56
I found the issue, it's because the amount is not correctly updated in the onyx update. 
This is an internal issue.

**Comment by greg-schroeder** [comment] 2024-10-14 21:46
Got it, updated to `Internal`

**Comment by trjExpensify** [comment] 2024-10-15 10:35
I think this is probably a backwards compatibility bug which someone in #migrate could run into (as you can't move expenses to a different report in NewDot), so I'd suggest moving it to that project @greg-schroeder.

**Comment by flaviadefaria** [comment] 2024-10-22 12:05
Based on what we saw in FullStory, quite a few users are experiencing this. So, I'm bumping this priority to `high`.

**Comment by greg-schroeder** [comment] 2024-10-23 09:07
Thanks @flaviadefaria

**Comment by madmax330** [comment] 2024-10-24 09:52
Going to look into this tomorrow, got some audit tasks to finish up today

**Comment by greg-schroeder** [comment] 2024-10-24 19:58
Thanks Max!

**Comment by flaviadefaria** [comment] 2024-10-31 12:53
@greg-schroeder this is a High priority #migrate issue so should we re-apply the internal label to get a new engineer assigned?

**Comment by greg-schroeder** [comment] 2024-11-01 20:34
@flaviadefaria re-applying that label doesn't do anything as far as assignment, sadly. The only way to get someone to take this is for them to volunteer. I'll add `Hot Pick` though.

**Comment by greg-schroeder** [comment] 2024-11-04 18:25
Same as above

**Comment by greg-schroeder** [comment] 2024-11-11 20:23
Same as above

**Comment by MonilBhavsar** [comment] 2024-11-12 07:18
Will take a look

**Comment by greg-schroeder** [comment] 2024-11-13 04:39
Thanks @MonilBhavsar!

**Comment by greg-schroeder** [comment] 2024-11-18 08:28
Any update on this one @MonilBhavsar?

**Comment by MonilBhavsar** [comment] 2024-11-18 11:01
I was able to reproduce. Looking into potential fixes

**Comment by MonilBhavsar** [comment] 2024-11-20 07:34
Found the fix. Working on it

**Comment by MonilBhavsar** [comment] 2024-11-20 08:42
PR is being reviewd

**Comment by greg-schroeder** [comment] 2024-11-20 21:48
Thanks Monil!

**Closed** 2024-11-26 04:28 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug, Hot Pick
