### ISSUE TITLE
[Needs reliable repro] New DMs aren't always showing as unread in the LHN. 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35314] opened 2024-01-29 13:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706485748212549

## Action Performed:
1. Log in to same account both in Web and mobile
2. Send a message to the above account
3. Receive notification in both desktop and mobile
4. Look at the LHN

## Expected Result:
Should appear bold in the LHN

## Actual Result:

1. I get the notification on mobile
2. I see it as unread in mobile (along with other items that don't show as unread on desktop... which might be related?  or different?)
3. The [attachment] message is in Onyx (ie, it shows when I search for Jon)
4. But Jon (sender) isn't showing as unread in the LHN.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (1)](https://github.com/Expensify/App/assets/38435837/72d38f76-b24c-4ae6-aff4-0b9a13704d34)
![image (4)](https://github.com/Expensify/App/assets/38435837/bbf0306c-9e1a-4730-982c-01ed40adb4e4)
![image (3)](https://github.com/Expensify/App/assets/38435837/59049b15-b6fc-4fcd-8e60-b5c7691b6d2e)
![image (2)](https://github.com/Expensify/App/assets/38435837/a75456b4-1151-4854-8ade-2f0de071f2a5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2024-01-29 21:40
Could be dupe of this? https://github.com/Expensify/App/issues/34273

**Comment by strepanier03** [comment] 2024-01-31 22:56
Hmm, it could be @mallenexpensify. I'm trying to repro this now but the steps aren't super clear to me. Will keep working on it.

**Comment by strepanier03** [comment] 2024-01-31 23:20
So the messages are unread in my LHN on mobile and web, but when searching they are unread. Not sure about this one.

<img width="1350" alt="image" src="https://github.com/Expensify/App/assets/10925636/87f250ee-27c9-43b0-aa4e-7e5cf9142a2e">
<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/10925636/d0e76c69-14ce-4572-9817-702cebbe40f8">
<img width="1388" alt="image" src="https://github.com/Expensify/App/assets/10925636/9b36c222-75a9-4688-b3ec-f7809845ffa2">
<img width="698" alt="image" src="https://github.com/Expensify/App/assets/10925636/3dd78cfc-f873-4819-a791-687883e0da46">

**Comment by strepanier03** [comment] 2024-02-05 22:06
Thanks @mallenexpensify - I'm not able to recreate this after 4 unique rounds of testing using multiple different accounts. 

I'm going to close this out.

**Closed by strepanier03** 2024-02-05 22:06 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
