### ISSUE TITLE
[$250] LHN - Action menu isn't opening when long tapping LHN elements with older accounts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47354] opened 2024-08-13 19:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4852333&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** komaromalberlet+1@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an older Gmail account that has a lot of conversations
3. Long tap on and LHN element

## Expected Result:
Action menu should open

## Actual Result:
Action menu isn't opening when long tapping LHN elements with older accounts. The issue isn't affecting new accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e0e91aa1-9d4c-4069-a94e-7958228daf81

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014339b190e93c80f8</li>
        <li>Upwork Job ID: 1823807765920455908</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-13 19:18
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-13 19:18
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-08-14 19:43
We'll try with `External`

**Comment by jjcoffee** [comment] 2024-08-16 09:35
@lanitochka17 I think the issue description is a bit too vague, how old do the accounts have to be? :smile:

**Comment by Amoralchik** [comment] 2024-08-18 00:39
can't reproduced on v9.0.21-2

https://github.com/user-attachments/assets/e3ffce2e-2622-4d8d-a3a1-496e211d8cdd

**Comment by jjcoffee** [comment] 2024-08-20 06:52
@lanitochka17 Friendly bump on [this comment](https://github.com/Expensify/App/issues/47354#issuecomment-2293174978). We need some more details on the age of the account (or maybe it's the size?).

**Comment by garrettmknight** [comment] 2024-08-20 16:23
I was able to reproduce on my test account: gknight@expensifail.com last week.

**Comment by lanitochka17** [comment] 2024-08-20 18:18
@jjcoffee  Hello The account is 9-11 months old. It has a few conversations, IOUs, WS invites.
 account: komaromalberlet+1@gmail.com

**Comment by jjcoffee** [comment] 2024-08-21 07:41
@garrettmknight Hmm, does your test account have a large number of convos? Trying to figure out if it's an age or a size thing.

**Comment by garrettmknight** [comment] 2024-08-21 21:21
My test account has a ton of convos.

**Comment by jjcoffee** [comment] 2024-08-22 13:59
Trying to get some interest [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1724335145772239).

**Comment by garrettmknight** [comment] 2024-08-27 19:17
Still awaiting a volunteer - @jjcoffee you able to reproduce this finally?

**Comment by jjcoffee** [comment] 2024-08-28 06:46
@garrettmknight No I can't repro on my high traffic account. I suspect others may be having trouble reproducing too, but we could try bumping the price to see if it attracts more attention?

**Comment by garrettmknight** [comment] 2024-08-29 11:30
Just retested and I'm not longer able to repro, closing.

**Closed by garrettmknight** 2024-08-29 11:30 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
