### ISSUE TITLE
Chat - To enter link name in multi line, tapping enter key changes link to text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36180] opened 2024-02-08 21:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4293571
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Paste a link and send the message
4. Long press and tap edit comment
5. Select link url name part and delete it
6. Enter a text in url name part and tap enter

## Expected Result:
Deleting url name part, entering a text & tapping enter key to enter link name in multi line, must not change link to text.

## Actual Result:
Deleting url name part, entering a text & tapping enter key to enter link name in multi line, changes link to text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9659089f-910a-480f-a479-ef5859c39722

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-08 21:46
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by tgolen** [comment] 2024-02-08 21:49
This looks like probably an issue from the live markdown feature.

**Comment by tgolen** [comment] 2024-02-08 22:16
@Skalakid Could you help verify if this is a bug with live markdown or not?

**Comment by roryabraham** [comment] 2024-02-08 22:46
According to GitHub newlines _can_ be in the text part of a link:

[valid link](https://google.com)

[another valid
link](https://google.com)

**Comment by roryabraham** [comment] 2024-02-08 22:49
Interestingly, newlines in links work ok, it's just if you remove the text part of an existing link and then insert a newline into what remains that this happens.

**Comment by Skalakid** [comment] 2024-02-09 09:00
@tgolen Yes it is connected with live markdown parsing system, just looking into it

**Comment by robertKozik** [comment] 2024-02-09 11:12
@Skalakid it's probably connected with parser - input is not the same as output and we are not highlighting then

**Comment by thienlnam** [comment] 2024-02-09 18:22
We've reverted the offending PR https://github.com/Expensify/App/pull/35837, so this is no longer a blocker

**Comment by robertKozik** [comment] 2024-02-13 22:54
Cannot reproduce it on staging, will look into it further

**Comment by tgolen** [comment] 2024-02-16 15:09
I'm going to close this since the PR which caused the regression was reverted.

**Closed by tgolen** 2024-02-16 15:09 UTC
Labels: Engineering, Weekly
