### ISSUE TITLE
[HOLD for payment 2024-01-05] [$500] iOS - Attachment - User able to switch to another attachment in PDF zoomed state

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33635] opened 2023-12-26 22:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Open any existing coversation
3. Send an image and PDF attachment in the conversation
4. Open the uploaded PDF attachment (you can access the PDF attachment via arrow navigation between attachments. Open image attachment and tap on left or right arrow to navigate on PDF view)
5. Zoom in the PDF page
6. Tap on the PDF page
7. Try to slide left/right while the PDF is zoomed in

## Expected Result:
According step 10 in the TR, user should not be able to switch to another attachment in PDF zoomed state

## Actual Result:
User able to switch to another attachment in PDF zoomed state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/64580dc9-cd39-4fed-9183-1eb1a253c2d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d96c87f2683da02</li>
        <li>Upwork Job ID: 1739779120396140544</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28070990</li>
<li>tienifr | Contributor | 28070991</li>
</ul></li>
    </ul>
</details>

**Comment by mollfpr** [comment] 2023-12-27 04:30
@abzokhattab Wasn't the issue that the user could slide to the prev/next attachment while on Zoom? It does not slide to the/next attachment while zooming in on the picture attachment.

**Comment by mollfpr** [comment] 2023-12-27 10:07
The [proposal](https://github.com/Expensify/App/issues/33635#issuecomment-1869944335) from @tienifr looks good! I think this issue was a regression from https://github.com/Expensify/App/pull/31308 when it's removed `isUsedInCarousel` from the `AttachmentViewPdf`.

🎀 👀 🎀 C+ reviewed!

**Comment by chrispader** [comment] 2023-12-28 10:36
This PR indeed fixes the problem as described in https://github.com/Expensify/App/pull/31308#discussion_r1437547152

**Comment by bfitzexpensify** [comment] 2024-01-05 17:15
Payment made to @tienifr. @mollfpr, it looks like we're waiting for you to accept the contract in Upwork. Also, a reminder to complete the BZ checklist - thanks!

**Comment by bfitzexpensify** [comment] 2024-01-08 13:04
Bump on contract acceptance in Upwork & BZ checklist @mollfpr

**Comment by mollfpr** [comment] 2024-01-08 13:17
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/31308

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/31308/files#r1436916636

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
> [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the app
2. Open any existing conversation
3. Send an image and PDF attachment in the conversation
4. Open the uploaded PDF attachment
5. Open the image attachment and tap on the left or right arrow to navigate to the PDF view
6. Zoom in the PDF page
7. Tap on the PDF page
8. Try to slide left/right while the PDF is zoomed in
9. **_Verify_** that the user is not able to switch to another attachment in the PDF zoomed state

---

@bfitzexpensify Could you give the payment summary for the manual request? Thanks!

**Comment by bfitzexpensify** [comment] 2024-01-09 15:07
Payment summary:

**Contributor:** @tienifr paid $500 via Upwork ✅ 
**C+:** @mollfpr to be paid $500 via manual request

**Comment by bfitzexpensify** [comment] 2024-01-09 15:07
Added regression tests to https://github.com/Expensify/Expensify/issues/358238, closing this out.

**Closed by bfitzexpensify** 2024-01-09 15:07 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-09 18:40
$500 payment approved for @mollfpr based on comment above.
