### ISSUE TITLE
Welcome message not saved when pressing enter

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21141] opened 2023-06-20 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a room and set the visibility to public
2. Go to the room detail after creating room
3. Settings > Welcome message
4. Type a message and press the enter button

## Expected Result: 
The welcome message should be saved when the enter button is pressed, similar to other input fields
## Actual Result: 
Pressing enter does not save the welcome message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b38ac54f-0289-46e6-ae2c-240149063dee

https://github.com/Expensify/App/assets/43996225/4761486f-6610-44b4-968c-8ed068716410

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686565053877649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-20 17:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Welcome message not saved when pressing enter.
### What is the root cause of that problem?
There is no prop `submitOnEnter` in welcome message TextInput, and the default value is false.
https://github.com/Expensify/App/blob/3b945c052e86e00ca363fa3f7f4a30f370a3483c/src/pages/ReportWelcomeMessagePage.js#L69-L80
### What changes do you think we should make in order to solve the problem?
Add prop `submitOnEnter` to welcome message TextInput will fix the issue.
```javascript
  <TextInput
    ...
   submitOnEnter
  />
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by conorpendergrast** [comment] 2023-06-21 08:48
I'm not confident that this is a bug, so I'm checking for the correct behaviour via [an internal Slack channel](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687337287924499)

**Comment by conorpendergrast** [comment] 2023-06-26 10:32
[Based on that discussion in an internal channel in Slack](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687337287924499), this isn’t a bug; when you’re typing in a textarea and hit enter, that should break lines (not save).

I’ll close this as **not a bug** for now, and when we’re ready to we can propose a change that will review all the text fields, decide which should be compose fields (and all of those will include live markdown previews, and therefore the described behaviour here)

**Closed by conorpendergrast** 2023-06-26 10:32 UTC
Labels: Daily, Overdue, Bug
