### ISSUE TITLE
Web - Workspace image change for a second while adding or removing user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23262] opened 2023-07-20 12:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace if not created
2. Go to Settings > Workspaces > Members
3. Click on invite button
4. Invite userB
5. Check the userB LHN

## Expected Result:
Workspace image should not be change

## Actual Result:
Workspace image change for a second while adding or removing user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aa728167-9d54-4de2-bc40-a99ef8d1a443

https://github.com/Expensify/App/assets/93399543/c5367cab-f12f-482e-8002-398e057ab7e4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689834584194399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-20 12:02
Could be the same root cause of https://github.com/Expensify/App/issues/23189, but correct me if I'm wrong! Thank you

**Comment by hannojg** [comment] 2023-07-20 12:12
Double checking now @kbecciv

**Comment by hannojg** [comment] 2023-07-20 12:16
Hmmmm, I can't reproduce that on `main`. In general I can tell that the `U` icon we are seeing, is because somewhere in the code the report name gets read as `undefined`.
Not sure if its even a bug caused by the PR to be honest.

**Comment by amyevans** [comment] 2023-07-20 15:36
I can't repro on `main` either. Not sure if there's been App code merged since the last deploy to fix it, or maybe there's backend code that's on staging but not production yet 🤔 

Continuing to investigate.

**Comment by amyevans** [comment] 2023-07-20 15:59
I think it's probably [this Web-E PR](https://github.com/Expensify/Web-Expensify/pull/38186) which separates pusher calls that were previously unified, any thoughts @iwiznia?

**Comment by amyevans** [comment] 2023-07-20 18:44
Minor bug so not going to block the deploy on it.

**Comment by amyevans** [comment] 2023-08-04 23:26
No update

**Comment by amyevans** [comment] 2023-08-15 23:01
No update

**Comment by amyevans** [comment] 2023-08-29 20:14
I don't think this one is worth fixing honestly, so I'm going to just close it

**Closed by amyevans** 2023-08-29 20:14 UTC
Labels: Engineering, Weekly, Overdue
