### ISSUE TITLE
[Guided Setup] [$250] Replace Enable your wallet with Add personal bank account task during onboarding

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#46231] opened 2024-07-25 20:18 UTC
There are two intents `Get paid back by my employer` and `Chat and split bills with friends` where one of the onboading tasks we show is `Enable your wallet`. But the wallet flow is onerous and we actually have not cleaned it up to show clear and actionable error messages and this is not a priority either till more people use IOU payments.

So for now, let's replace this task with a `Add personal bank account` 

<img width="992" alt="image" src="https://github.com/user-attachments/assets/375494f7-c261-46dc-80df-1b19fb05e1d4">

**Title**: Add personal bank account
**Description**: 

You’ll need to add your personal bank account to get paid back. Don’t worry, it’s easy!
Here’s how to set up your bank account:

1. Click your profile picture.
2. Click Wallet > Bank accounts > + Add bank account.
3. Connect your bank account.

Once that’s done, you can request money from anyone and get paid back right into your personal bank account.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9b5735e8551a25a</li>
        <li>Upwork Job ID: 1816570512509995571</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103281558</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by trjExpensify** [comment] 2024-07-25 20:53
(we good here, Jon.. copy updates and shizz).

**Comment by mollfpr** [comment] 2024-07-26 15:21
The [proposal](https://github.com/Expensify/App/issues/46231#issuecomment-2251537534) from @nyomanjyotisa looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2024-08-07 05:38
No payments are due yet. The PR is reverted here https://github.com/Expensify/App/pull/46630.

> We check the name of the onboarding tasks to create in Auth, and at the moment Auth doesn't expects any task called addBankAccount

cc @francoisl @Beamanator

**Comment by Beamanator** [comment] 2024-08-08 04:56
Thank you sir, closing!

**Comment by mollfpr** [comment] 2024-08-08 06:14
@Beamanator Should we keep the issue open and get the BE change?

**Comment by trjExpensify** [comment] 2024-08-08 13:16
Yes, this was reverted.

**Comment by Beamanator** [comment] 2024-08-08 17:09
Oh merp my bad for not understanding 🙃

**Comment by tgolen** [comment] 2024-08-09 14:54
OK... so, I'm coming up to speed on this. It sounds like a backend change is necessary to support the front-end PR. Is anyone on that?

**Comment by trjExpensify** [comment] 2024-08-09 15:06
Doesn't look like anyone is on it, and the revert was because Auth expects the task name to match: https://github.com/Expensify/App/pull/46630#issue-2441277658

**Comment by tgolen** [comment] 2024-08-09 15:51
OK, thanks! Any volunteers to do the BE fix? I probably won't be able to get to it until the tail end of next week.

**Comment by tgolen** [comment] 2024-08-12 14:29
Assuming there are no volunteers, I will try to get to this later this week.

**Comment by trjExpensify** [comment] 2024-08-12 23:58
Yeah, that assumption is correct. Thanks, Tim!

**Comment by tgolen** [comment] 2024-08-14 20:15
@francoisl Would you mind pointing me to the right spot in Auth where this needs to be added? I'm not familiar with the flow at all so I'm not sure where to look.

**Comment by trjExpensify** [comment] 2024-08-14 20:23
I believe it's here: https://github.com/Expensify/Auth/blob/29ab63ee487aa54a00f9855c5a76a768e374aa76/auth/lib/GuidedSetup.h#L60

**Comment by francoisl** [comment] 2024-08-14 20:40
That's right but there's a little more too:
1. Create a constant for the new task [here](https://github.com/Expensify/Auth/blob/73d718099a940247d3d5d6dfb3312aec95bd1db9/auth/lib/GuidedSetup.h#L57-L58)
2. Add the constant to [this set](https://github.com/Expensify/Auth/blob/222bd8e7bfad82b1f4b46835c126d3a9dc8e81a2/auth/lib/GuidedSetup.cpp#L11) so that `completeSetupTask()` doesn't throw 
3. Add the logic to auto-complete the task by calling `auth.guidedSetup.completeSetupTask()` when the user takes the corresponding action

**Comment by tgolen** [comment] 2024-08-14 20:41
Ah, cool. Thanks! That should get me started

**Comment by trjExpensify** [comment] 2024-08-14 20:45
Is this a new task or just replacing the existing `enableWallet` task? :/

**Comment by anmurali** [comment] 2024-08-14 20:47
Replace enable wallet task.

**Comment by francoisl** [comment] 2024-08-14 20:50
Oh right, then it's easier, especially for step 3. I'd suggest making the change in multiple steps though:

1. Add a new task const that is essentially a duplicate of `TASK_ENABLE_WALLET` in Auth, deploy that
2. Use the new task in App, wait a bit for most clients to update
3. Remove the old task from Auth

**Comment by tgolen** [comment] 2024-08-14 21:06
hehe, @francoisl you know a lot about this. Are you sure you aren't the volunteer I was looking for? 😉 😉

**Comment by francoisl** [comment] 2024-08-14 21:42
If it can wait until mid next week sure, otherwise I don't think I'll have time until then.

**Comment by tgolen** [comment] 2024-08-14 21:49
OK, I'll see if I have time to get to it before then.

**Comment by tgolen** [comment] 2024-08-15 16:25
# Daily Update
- I created an [Auth PR](https://github.com/Expensify/Auth/pull/12074) which implements the new task as merely a copy of the old enable wallet task. The code change was straight forward, but updating the tests were not as straight forward. I hope I did them justice!

### Next Steps
- @deetergp @francoisl review and merge the Auth PR
- Wait for it to deploy
- @tgolen Re-revert the frontend PR and get it merged
- @tgolen Write another Auth PR to remove the old enable wallet task

#### ETA
- First Auth PR merged by tomorrow, Aug 16
- Frontend PR merged and deployed by Friday, Aug 23
- Second Auth PR merged by Tuesday, Aug 27

**Comment by tgolen** [comment] 2024-08-20 12:48
# Daily Update
- The [Auth PR](https://github.com/Expensify/Auth/pull/12074) has been merged

### Next Steps
- Wait for Auth to deploy
- @nyomanjyotisa can reimplement the original PR that was reverted

#### ETA
- Auth deploy should happen today, Aug 20. I'll post back here when I see it's been deployed.

**Comment by kadiealexander** [comment] 2024-08-23 07:59
@tgolen any further updates on this one? Thanks!

**Comment by tgolen** [comment] 2024-08-23 15:31
Yeah, the auth change was deployed 3 days ago so @nyomanjyotisa can go ahead and reimplement the frontend.

**Comment by kadiealexander** [comment] 2024-08-28 06:30
@nyomanjyotisa bump!

**Comment by nyomanjyotisa** [comment] 2024-08-28 14:43
@mollfpr [PR](https://github.com/Expensify/App/pull/48182) is ready for review, sorry for the delay 🙏

**Comment by VictoriaExpensify** [comment] 2024-09-13 02:12
@mollfpr - have you had a chance to review this yet?

**Comment by mollfpr** [comment] 2024-09-16 13:08
@VictoriaExpensify The changes on the PR look good to me! We are waiting for the BE changes to make the task auto mark working.

**Comment by mollfpr** [comment] 2024-09-26 04:39
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good!

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Login with new account
2. Choose 'Get paid back by my employer or 'Chat and split bills with' on onboarding
3. Enter your name
4. Verify that 'Add personal bank account' task exist in Concierge chat
5. 👍 or 👎 

---

@kadiealexander The PR is deployed to production last week, could you give the payment summary? Thank you!

**Comment by kadiealexander** [comment] 2024-10-14 05:36
Payouts due:

- [ ] Contributor: $250 @nyomanjyotisa ([Offer link](https://www.upwork.com/nx/wm/offer/103281558))
- [ ] Reviewer: $250 @mollfpr via manual request

Upwork job is [here](https://www.upwork.com/jobs/~01a9b5735e8551a25a).

**Closed** 2024-10-14 05:38 UTC
Labels: Reviewing, External, Engineering, Weekly, NewFeature

**Comment by garrettmknight** [comment] 2024-10-15 01:18
$250 approved for @mollfpr
