### ISSUE TITLE
[HOLD for payment 2023-11-06] [$250] Migrate `AuthScreens.js` to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16226] opened 2023-03-20 08:48 UTC
### Filenames
- [ ] [src/libs/Navigation/AppNavigator/AuthScreens.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`shouldComponentUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017dc89ca40fc1d9c6</li>
        <li>Upwork Job ID: 1703672231251259392</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26848673</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @maddylewis</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by s-alves10** [comment] 2023-06-06 11:09
I'd love to work on this.

**Comment by dayana7204** [comment] 2023-06-27 19:37
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment] 2023-07-06 03:55
I can work on this issue.

**Comment by olexyt** [comment] 2023-07-07 14:18
I can work on this issue.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:12
I'm able to work on this if needed!

**Comment by to-ai** [comment] 2023-07-11 21:26
I am able to work on this task.

**Comment by KrAbhas** [comment] 2023-07-19 10:22
Allow me to work on this!

**Comment by barttom** [comment] 2023-09-18 07:24
Hi! I'm Bartek from Callstack - an expert contributor group and I would like to work on this one.

**Comment by alexxxwork** [comment] 2023-09-18 07:30
Dibs

**Comment by carlitose** [comment] 2023-09-18 10:34
Hello Expensify Team,

I am interested in tackling the issue regarding the migration of the AuthScreens component from a class component to a functional one.

Here's my proposed action plan:

Requirement Gathering: I will start by thoroughly analyzing the current code to fully grasp the logic of the existing class component.

Planning: Based on my understanding, I will plan how to convert each part of the class component into a functional one using React hooks, such as useState, useEffect, and useRef.

Implementation: I will perform the actual migration of existing code into a functional component, preserving existing logic. For instance, the component's current state and lifecycle methods will be converted using respective React hooks.

Testing: I will verify the functionality of the new functional component to ensure it works as expected and that there are no regressions. I'll also test to make sure no breaking changes have been introduced.

Code Review and Submission: Once implementation is complete, I'll conduct a final review of the code to ensure everything is in order, create a new branch, and make a Pull Request to your repository on GitHub.

I have a deep knowledge of JavaScript and React, and I have experience in developing applications with both class and functional components. I'm excited about the opportunity to contribute to Expensify and believe I can bring value to this project.

Thank you for considering my proposal
Carlo

**Comment by muratcanyusufoglu** [comment] 2023-09-18 10:42
Hello Expensify Team,

I hope this message finds you well. I'm writing to express my interest in your project, and I'd like to offer my services as an experienced React developer. Here's how I can assist you:
Certainly! Here's a version of the explanation without numbers:

Create a New Functional Component:
   - Start by creating a new functional component with the same name as your class component.
   
Copy Class Component Logic:
   - Copy the logic and code from your class component into your functional component. You will need to make some adjustments as you go along.
   
Remove `this` Keyword:
   - In class components, you often use the `this` keyword to access props and state. In functional components, you can directly access props as arguments and use the `useState` hook to manage state. Replace `this.props` with just `props` and `this.state` with `useState`.
   
Remove Lifecycle Methods:
   - If your class component used lifecycle methods like `componentDidMount`, `componentDidUpdate`, or `componentWillUnmount`, you can replace them with the `useEffect` hook in functional components.
   
Props and Destructuring:
   - In functional components, props are directly available as an argument. You can destructure them if needed.

Clean Up:
   - Remove any unnecessary code related to class components, such as constructor methods or `render` methods.

Test:
   - Thoroughly test your functional component to make sure it behaves as expected.

Expensify account email: muratcan.ysfgl@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/muratcany

**Comment by munsuyog** [comment] 2023-09-18 10:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate AuthScreens.js to function component

### What is the root cause of that problem?
There is no as such any problem but need to migrate to function component.

### What changes do you think we should make in order to solve the problem?
Migrate 'src/libs/Navigation/AppNavigator/AuthScreens.js' into functional component.

### What alternative solutions did you explore? (Optional)

**Comment by SubuktageenKhan** [comment] 2023-09-18 10:56
Proposal
Please re-state the problem that we are trying to solve in this issue.
Migrate AuthScreens.js to function component

What is the root cause of that problem?
There is no as such any problem but need to migrate to function component.

What changes do you think we should make in order to solve the problem?
Migrate 'src/libs/Navigation/AppNavigator/AuthScreens.js' into functional component.

**Comment by SubuktageenKhan** [comment] 2023-09-18 11:45
Contributor details
Your Expensify account email: subuktageen2005@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/subuktageen007

**Comment by 1easyecommerce** [comment] 2023-09-18 14:05
**Here is technical explanation of the changes that I will make to migrate AuthScreens.js to function component**

1.  Local component states, which are currently managed by the component's constructor and methods, will be managed by the `useState `hook. To persist values across renders without causing re-renders, we will use the `useRef `hook.

2. The `componentDidMount `method logic will be moved into the `useEffect `hook with an empty dependency array to ensure it runs once after component mount. The cleanup logic in the `componentWillUnmount `method will be moved into a return statement within the same `useEffect `hook to run when the component unmounts. The logic in `shouldComponentUpdate `will be achieved using a combination of `useMemo `or useCallback hooks, ensuring re-renders happen only when specified props change.

3.  All event listeners added in the `componentDidMount `method will have corresponding removal logic in the cleanup phase of the `useEffect `hook.

4. Onyx connections currently outside the component will be moved inside the component and integrated within the `useEffect `hooks. This ensures that they are set up after the component mounts and cleaned up when it unmounts.

5. In function components, props are received directly as function arguments. All instances of `this.props` will be replaced with the respective props.

**Comment by marcochavezf** [comment] 2023-09-25 02:40
Reassigning @situchan as C+ from this [comment](https://github.com/Expensify/App/pull/27764#issuecomment-1732598698)

**Comment by marcochavezf** [comment] 2023-10-23 20:17
Bumped C+ reviewer in the PR

**Comment by marcaaron** [comment] 2023-11-08 04:55
I believe this issue is just now waiting for payment.

**Comment by maddylewis** [comment] 2023-11-08 18:56
## Payments
- [ ] Reporter: N/A (internal)
- [ ] Contributor: N/A @barttom (contractor)
- [ ] C+: @situchan ($250)

**Comment by situchan** [comment] 2023-11-08 19:21
@maddylewis can we use [this contract](https://github.com/Expensify/App/issues/16226#issuecomment-1732816851)?

**Comment by maddylewis** [comment] 2023-11-08 19:41
sure! paid!

**Comment by situchan** [comment] 2023-11-08 19:42
Thanks. Please close 2 upwork contracts

**Closed** 2023-11-08 19:43 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
