### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#26986] opened 2023-09-07 19:50 UTC
This has been showing for over 2 months on dev. Can we fix it?
 
```
events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onKeyCommand listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///./node_modules/events/events.js:211:15)
    at EventEmitter.addListener (webpack-internal:///./node_modules/events/events.js:227:10)
    at EventEmitter.addListener (webpack-internal:///./node_modules/react-native-key-command/lib/module/KeyCommand/index.js:20:16)
    at Module.addListener (webpack-internal:///./node_modules/react-native-key-command/lib/module/index.js:110:30)
    at eval (webpack-internal:///./src/libs/KeyboardShortcut/index.js:84:57)
    at Function.each (webpack-internal:///./node_modules/underscore/modules/each.js:26:7)
    at eval (webpack-internal:///./src/libs/KeyboardShortcut/index.js:77:52)
    at ./src/libs/KeyboardShortcut/index.js (http://localhost:8082/main-8a767871f57b57b1baee.bundle.js:8113:1)
    at __webpack_require__ (http://localhost:8082/runtime-17296f4671db2b0d6f5f.bundle.js:36:33)
    at fn (http://localhost:8082/runtime-17296f4671db2b0d6f5f.bundle.js:352:21)
```

![2023-09-07_09-50-01](https://github.com/Expensify/App/assets/32969087/ef75cdd2-4473-4729-8ae8-ee3abbe70ac3)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01961f084c190662b2</li>
        <li>Upwork Job ID: 1701152779444531200</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 26743727</li>
</ul></li>
    </ul>
</details>

Slack convo if necessary: https://expensify.slack.com/archives/C049HHMV9SM/p1694421370612589

**Comment by akinwale** [comment] 2023-09-07 20:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"MaxListenersExceededWarning: Possible EventEmitter memory leak detected" warning showing up on dev.

### What is the root cause of that problem?
This is due to the number of keyboard shortcuts being setup exceeding the default number of max listeners.

### What changes do you think we should make in order to solve the problem?
Increase the number of max listeners by setting the EventEmitter's defaultMaxListeners value.

```
EventEmitter.defaultMaxListeners = Object.keys(CONST.KEYBOARD_SHORTCUTS).length;
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by garrettmknight** [comment] 2023-09-11 08:38
I don't have a dev to test this on, but I'll believe @marcaaron. Checking whether it's `External` in this [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1694421370612589)

**Comment by b4s36t4** [comment] 2023-09-11 11:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
MaxListenersExceededWarning: Possible EventEmitter memory leak detected
### What is the root cause of that problem?

We have a limit of 10 max listener for the events package and we're registering total 11 events which is raising this wanring.

### What changes do you think we should make in order to solve the problem?

Instead of going with global override we can update the maxilistener count using `listenerCount` and `setMaxListenerCount` for the event emitter exported by `KeyCommand` package which is isolated and specific limit set to only `KeyCommand` package.

> An example of 20 max listeners
```jsx
KeyCommand.eventEmitter.setMaxListener(20)
```



### What alternative solutions did you explore? (Optional)
Or whenever we're adding a new listener we can check the max and current listener count and increment using a threshold way.

Like if we have 15 listeners we can update it to 20 listeners etc so, Just an alternative approach minding that we might add few more listeners in future so that it won't get clogged and no need to change everytime we reach the limit.

> Tested, this only overrides the listener count of `KeyCommand`.

**Comment by b4s36t4** [comment] 2023-09-11 11:51
@garrettmknight if it's external, you forget to apply `Help Wanted` and now there's no `C+` to review the proposals.

**Comment by danieldoglas** [comment] 2023-09-15 08:17
hey, I think we found out why this is happening.

We're adding a new event listener everytime you access a report, and never removing those. So over time, if you access 10s of reports, it will pass the default limit from the browser.

I think we need to hold this a bit

**Comment by roryabraham** [comment] 2023-09-15 08:23
@danieldoglas are you working on a solution in some other context where I can follow along?

**Comment by roryabraham** [comment] 2023-09-15 08:24
I think this might also be contributing to the bug where the webpack-dev-server crashes intermittantly?

**Comment by b4s36t4** [comment] 2023-09-15 08:41
@danieldoglas I don't think your RCA is correct. We get this warning not in between navigating the reports we're getting this error at the start of application. How does having only report opened causing this issue??

**Comment by b4s36t4** [comment] 2023-09-15 08:43
Also as far as I checked we're only adding 11 event listeners (which everyone one of them required) and the limit is 10 so it's warning. I don't think it's an issue with removing or adding listeners.

**Comment by roryabraham** [comment] 2023-09-19 01:28
I was skeptical about switching the event emitter lib but it has more stars on GitHub and is more actively maintained so let's do it. @hungvu193's proposal LGTM 👍🏼

**Comment by garrettmknight** [comment] 2023-09-21 11:03
Working through the PR.

**Comment by garrettmknight** [comment] 2023-09-25 11:10
PR is merged!

**Comment by garrettmknight** [comment] 2023-10-11 19:34
Summary of payments for this issue:
- Contributor: @hungvu193 $500 paid via Upwork
- Reveiwer: @thesahindia $500

Upwork job: https://www.upwork.com/en-gb/jobs/~01961f084c190662b2

**Comment by garrettmknight** [comment] 2023-10-24 08:53
Sounds good, closing.

**Closed by garrettmknight** 2023-10-24 08:53 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-25 17:03
$500 payment approved for @thesahindia based on BZ summary.
