### ISSUE TITLE
Tag - Inconsistency in tag custom name for "Missing tag" and "Tag no longer valid"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35425] opened 2024-01-30 18:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4253774
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace
- The Collect workspace has tags and Tag has custom name
1. [Employee] Create a manual request with a tag in the workspace chat
2. [Admin] Disable the tag in Step 1
3. [Employee] Navigate to request details page
4. [Employee] Note that it shows "<custom_tag_name> no longer valid"
5. [Employee] Create another manual request with no tag
6. [Employee] Navigate to request details page

## Expected Result:
The violation will show "Missing <custom_tag_name>"

## Actual Result:
The violation will show "Missing tag". There is inconsistency in the behavior between "Missing tag" and "Tag no longer valid"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3cdaca02-6d19-4021-8eed-eb2d5ef4bf6b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2024-01-30 19:57
This looks like expected behavior. Not a blocker. Closing!

**Closed by yuwenmemon** 2024-01-30 19:57 UTC
Labels: DeployBlockerCash, Engineering, Hourly
