### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Search - Search icon is not responsive after tapping on room mention in Chat and exit chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50317] opened 2024-10-06 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat.
3. Send a message containing #admins room mention.
4. Go to Search > Chat.
5. Tap on the #admins mention.
6. Swipe to the right to close the chat.
7. Tap on the Search icon.

## Expected Result:
User should be able to navigate to Search after swiping to right to close the room chat when it is opened from Search.

## Actual Result:
Search icon is not responsive after tapping on room mention in Chat and closing the chat.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a76d437f-143b-4983-aa91-14592dbef9f9

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847130088347504306</li>
        <li>Upwork Job ID: 1847130088347504306</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104596829</li>
<li>Nodebrute | Contributor | 104596830</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment] 2024-10-06 19:53
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-10-06 19:53
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment] 2024-10-07 21:14
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment] 2024-10-11 23:47
Still on my testing list

**Comment by alexpensify** [comment] 2024-10-15 06:00
No update

**Comment by alexpensify** [comment] 2024-10-18 04:18
@rayane-djouah  - can you please identify if this proposal will fix this issue? Thanks! 

## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by Nodebrute** [comment] 2024-10-21 09:39
@rayane-djouahI have previously worked on an issue caused by this PR(https://github.com/Expensify/App/pull/48990): https://github.com/Expensify/App/pull/50254, so I understand this PR well. This bug is not related to that.

**Comment by flaviadefaria** [comment] 2024-10-22 15:32
@alexpensify this is probably an issue for #quality rather than #migrate.

**Comment by alexpensify** [comment] 2024-10-22 18:10
Thanks for the update, I associated this one with Migrate because of last week's update: 

>Preventing someone from migrating to NewDot, it should go in the #migrate

Search is important to use Chat. I'll update to #Quaility now.

**Comment by alexpensify** [comment] 2024-10-28 15:42
@Nodebrute - any update for the PR here? Thanks!

**Comment by Nodebrute** [comment] 2024-10-28 16:54
Pr will be ready in few hours.

**Comment by alexpensify** [comment] 2024-11-15 01:48
Payouts due: 2024-11-14

- [ ] Contributor: $250 @Nodebrute 
- [ ] Reviewer: $250 @rayane-djouah 

Upwork job is [here](https://www.upwork.com/jobs/~021847130088347504306). Everyone has been paid via Upwork.

**Comment by alexpensify** [comment] 2024-11-15 01:48
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by alexpensify** [comment] 2024-11-15 01:49
@rayane-djouah, can you please complete the checklist? thanks!

**Comment by alexpensify** [comment] 2024-11-19 00:29
Thanks! I'll work on the QA test prep later this week.

**Comment by alexpensify** [comment] 2024-11-22 01:13
Other GHs have been a priority; I'll work on the regression test soon.

**Comment by alexpensify** [comment] 2024-11-25 19:52
With the slower week, I'll be working on the last step soon.

**Comment by alexpensify** [comment] 2024-12-03 01:43
Closing - all set here

**Closed by alexpensify** 2024-12-03 01:43 UTC
Labels: External, Weekly, Awaiting Payment, Bug
