### ISSUE TITLE
[Hold #22062] Dev: Email Not Displayed in Tooltip on Workspace Members Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22485] opened 2023-07-08 17:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspace > New workspace
2. Navigate to the Member and Invite Members section
3. Hover over the user's profile image

## Expected Result:
The email should be displayed in the tooltip when hovering over the user's profile picture

## Actual Result:
The email is not showing in the tooltip on the workspace members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3 Dev
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/875ad800-20d0-4b5b-95fd-b8baaa757031

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688760556053339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-07-08 18:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip doesn't show email/display name on Workspace Members page

### What is the root cause of that problem?
account id is not passed here:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/workspace/WorkspaceMembersPage.js#L332-L338

and this causes missing accountID prop in UserDetailsTooltip:
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/UserDetailsTooltip/index.js#L19


### What changes do you think we should make in order to solve the problem?
pass `id: item.accountID` in icons array above.

Updated code will look like this:
```
     { 
         id: item.accountID, 
         source: UserUtils.getAvatar(item.avatar, item.accountID), 
         name: item.login, 
         type: CONST.ICON_TYPE_AVATAR, 
     }, 
```

**Comment by ayazhussain79** [comment] 2023-07-10 09:14
@chiragxarora This bug isn't on staging yet so how is it dupe?

**Comment by deetergp** [comment] 2023-07-10 18:17
Am I missing something? This works fine for me locally running on updated `main`. Can someone who has experienced this already update their `main`, try again, and report back here?
<img width="1774" alt="Screenshot 2023-07-10 at 2 16 12 PM" src="https://github.com/Expensify/App/assets/766197/5c2849c9-bb3b-40aa-8871-756ebe2803b6">

**Comment by ayazhussain79** [comment] 2023-07-10 18:25
@deetergp you can check that first go to the Settings > Workspaces > Members 
You can also reproduce it while creating task on assignee page and also on reacted emoji tooltip https://github.com/Expensify/App/issues/22485#issuecomment-1628560422

**Comment by deetergp** [comment] 2023-07-10 18:29
Ahh, I was looking in the wrong place. Thanks @ayazhussain79 👍

**Comment by deetergp** [comment] 2023-07-10 18:53
I've removed the blocker label because a) it's pretty trivial and b) it looks like the solutions being discussed in https://github.com/Expensify/App/issues/22062 will likely fix this. If it doesn't, we can reopen the discussion here.

**Comment by deetergp** [comment] 2023-07-11 21:19
Downgrading to weekly and putting a hold on it pending the outcome of https://github.com/Expensify/App/issues/22062

**Comment by deetergp** [comment] 2023-07-26 16:24
Still on hold

**Comment by deetergp** [comment] 2023-08-03 21:06
It looks like #22062 did end up resolving this issue. Closing this one out.

**Closed by deetergp** 2023-08-03 21:06 UTC
Labels: Engineering, Weekly, Needs Reproduction, Overdue
