### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] mweb - Hold - Interstitial modal "Got it" is auto-dismissed when hold expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44082] opened 2024-06-20 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a342@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create two manual money request
2. Go to the first expense > Select Hold from 3-Dot menu
2. Add reason to hold and tap Hold button

## Expected Result:
Modal with Got it button should appear and user should tap Got it to dismiss the modal

## Actual Result:
Interstitial modal "Got it" is auto-dismissed when hold expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2967637c-d73b-4d23-be5c-6fdb4f532ea7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1513c97d5b0c258</li>
        <li>Upwork Job ID: 1805314680387652637</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103250020</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify / @alexpensify</details>

**Comment by lanitochka17** [comment] 2024-06-20 14:28
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment] 2024-06-24 22:42
Still on my testing radar

**Comment by alexpensify** [comment] 2024-06-26 21:06
Other GHs and customer tasks have been a higher priority, I'll get to this one soon.

**Comment by alexpensify** [comment] 2024-06-26 21:12
Waiting for proposals here

**Comment by hungvu193** [comment] 2024-06-26 23:36
Waiting for proposals

**Comment by alexpensify** [comment] 2024-06-28 17:58
We need proposals here

**Comment by alexpensify** [comment] 2024-06-28 21:55
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period. 

I'll try to check in a few times. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by hungvu193** [comment] 2024-07-01 02:04
Still waiting for proposal

**Comment by hungvu193** [comment] 2024-07-03 06:48
Same

**Comment by hungvu193** [comment] 2024-07-08 16:01
Same here

**Comment by alexpensify** [comment] 2024-07-08 17:50
I'm back online and will start asking around for help.

**Comment by alexpensify** [comment] 2024-07-10 17:36
No update yet

**Comment by alexpensify** [comment] 2024-07-12 22:39
I've been behind due to other GHs. I'll get to the required actions on Monday.

**Comment by hungvu193** [comment] 2024-07-15 03:37
I'll take a look today

**Comment by puneetlath** [comment] 2024-07-16 17:38
@hungvu193 any luck with the setup?

**Comment by hungvu193** [comment] 2024-07-17 02:07
I'll do another attempt today on a real device

**Comment by hungvu193** [comment] 2024-07-17 09:11
@dominictb Hey can you confirm that you can still reproduce it? 
Tried to reproduce it on my android phone but I don't think I can reproduce this issue.

**Comment by hungvu193** [comment] 2024-07-18 13:44
Thanks for your detailed steps 🙏. Did you test it when StrictMode was enabled?

**Comment by hungvu193** [comment] 2024-07-18 14:11
Cool. Let's me try to reproduce it, I'll ask here if I have any questions. Ty

**Comment by hungvu193** [comment] 2024-07-19 07:34
I still don't think I can reproduce 🤔 Any steps that I missed

https://github.com/user-attachments/assets/7f622e2a-fd19-4691-826f-490047b432b2

**Comment by hungvu193** [comment] 2024-07-19 07:43
Ok, I can reproduce if we a delay on dismiss function, taking a closer look now.

https://github.com/user-attachments/assets/8d2cef98-8044-4198-bf12-d7a72c70f9b9

**Comment by hungvu193** [comment] 2024-07-19 11:53
Thanks @dominictb, your proposal makes sense to me. GotIt modal was rendered before `popstate` was triggered.

<img width="978" alt="Screenshot 2024-07-19 at 18 52 06" src="https://github.com/user-attachments/assets/b0650db7-3eba-4f21-9fe9-ff46ff0062c1">

Since the related changes are inside base component. I'll need to take few more tests to make sure it won't affect other platforms.

**Comment by hungvu193** [comment] 2024-07-21 08:23
@dominictb ['s proposal](https://github.com/Expensify/App/issues/44082#issuecomment-2227286620) looks good to me!

Since https://github.com/Expensify/App/issues/22953 is no longer reproduce, I think we can consider remove this BOC:
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/components/Popover/index.tsx#L38-L50

🎀 👀 🎀  C+ reviewed!

**Comment by hungvu193** [comment] 2024-07-24 02:03
@puneetlath little bump 👋

**Comment by puneetlath** [comment] 2024-07-24 15:19
Sorry for the delay. Assigned @dominictb

**Comment by hungvu193** [comment] 2024-07-26 03:27
@dominictb Do you have any ETA for the PR?

**Comment by alexpensify** [comment] 2024-07-26 22:20
It's not overdue; the PR is on the way.

**Comment by alexpensify** [comment] 2024-07-29 18:58
Awesome, this PR is moving along, and we are waiting for it to go to production.

**Comment by alexpensify** [comment] 2024-08-07 20:38
Payouts due: August 7, 2024

- [x] Contributor: $250 @dominictb - I completed the process in Upwork 
- [ ] Contributor+: $250 @hungvu193 - Please submit a request in Chat 

Upwork job is [here](https://www.upwork.com/jobs/~01e1513c97d5b0c258).

Closing - I completed the payment process in Upwork. I'll revisit this GH for the regression test process.

**Closed by alexpensify** 2024-08-07 20:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-14 17:35
$250 approved for @hungvu193
