### ISSUE TITLE
[HOLD for payment 2024-11-13] [HOLD for payment 2024-11-11] Validate account - Need to click "Didn't receive a magic code?" twice to restart timer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51797] opened 2024-10-31 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, New feature
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** yonghongkok2+diwdwdoiijoj2o@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51663
## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up with a new Gmail account
3. Go to Account settings > Profile
4. Go to Contact method
5. Click on the email
6. Wait 30 seconds
7. Click "Didn't receive a magic code?" link one time

## Expected Result:
Timer will restart after clicking "Didn't receive a magic code?" for the first time

## Actual Result:
Timer only restarts after clicking "Didn't receive a magic code?" for the second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/34e16d53-0936-4594-be6d-e8c2366cb748

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-31 14:33
Production:

https://github.com/user-attachments/assets/fd9d3d74-eea5-42a3-a9c1-9a5f1d040930

**Comment by MuaazArshad** [comment] 2024-10-31 15:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Validate account - Need to click "Didn't receive a magic code?" twice to restart timer
### What is the root cause of that problem?
We are adding this check 
```
 if (hasMagicCodeBeenSent && !isResent) {
            return;
        }
```
where `hasMagicCodeBeenSent` and `!isResent` are not being before updated with the first click.
They update after the first click, so the timer resets on the second click.

### What changes do you think we should make in order to solve the problem?

This should be removed since we aren’t including it on the sign-in page.
https://github.com/Expensify/App/blob/6c33bba59c3305d59c96b265183473bc7ffed2e0/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.tsx#L155-L160
The function should run without the condition since there’s no button to click after the code is resent.
### What alternative solutions did you explore? (Optional)

**Comment by Beamanator** [comment] 2024-11-01 10:22
Thanks your proposals so far, everyone! Can anyone find which PR may have caused this?

**Comment by hungvu193** [comment] 2024-11-01 10:36
cc @getusha

**Comment by hungvu193** [comment] 2024-11-01 10:44
It's still in the regression period so I think @getusha  will handle it.

@Beamanator  Please assign me and @getusha.

**Comment by mountiny** [comment] 2024-11-01 10:51
Thanks! @getusha and @hungvu193 should handle this one

**Comment by Beamanator** [comment] 2024-11-01 10:51
thanks @vitHoracek :D

**Comment by mountiny** [comment] 2024-11-01 10:54
NoProblem @alexBeaman

**Comment by Beamanator** [comment] 2024-11-04 10:14
Merged & CPing

**Comment by Beamanator** [comment] 2024-11-04 11:16
Seems to be working in staging! Checking it off!

**Closed** 2024-11-13 17:58 UTC
Labels: Engineering, Weekly, Awaiting Payment
