### ISSUE TITLE
[$250] Distance - Recent destination list shows more than 5 destinations

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45241] opened 2024-07-11 10:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4709538
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance.
3. Click Start point.
4. Select 6 different waypoints.
5. Note that the recent destination list shows more than 5 destinations.

## Expected Result:
The recent destination list will show at most 5 destinations (production behavior).

## Actual Result:
The recent destination list shows more than 5 destinations on staging.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/da56a621-1caf-43b3-9f9a-cba3e673bb0d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ea8c6fb29aecd8f</li>
        <li>Upwork Job ID: 1811456879870180805</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by izarutskaya** [comment] 2024-07-11 10:15
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-11 10:15
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-07-11 10:15
Production
![image (4)](https://github.com/Expensify/App/assets/115492554/1b36587b-b34a-4c93-8c8d-7a9e1d047f62)

**Comment by etCoderDysto** [comment] 2024-07-11 10:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Recent destination list shows more than 5 destinations
### What is the root cause of that problem?
`CONST.RECENT_WAYPOINTS_NUMBER` value is '20'. And we sliced the array using the value. 
https://github.com/Expensify/App/blob/19922f5d45caa01a95bee0a89c4d8664ac493b43/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L257-L259
### What changes do you think we should make in order to solve the problem?
We should change `CONST.RECENT_WAYPOINTS_NUMBER = 20` to `CONST.RECENT_WAYPOINTS_NUMBER = 5` in `CONST` file. 

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-07-11 14:37
Demoting from blocker

**Comment by arosiclair** [comment] 2024-07-11 22:55
This is not a bug we intentionally increased the number of displayed places to 20. We may need to update regression test steps somewhere though. cc @neil-marcellini

**Comment by danieldoglas** [comment] 2024-07-12 10:47
assigning @neil-marcellini to the issue based on @arosiclair's comment

**Comment by arosiclair** [comment] 2024-07-12 17:53
> @arosiclair, the Save will be pushed down and we need to scroll, to see the scroll button, I don't think thats expected. The button should always be fixed.

I think that's correct, but we did have a long discussion about it and I don't remember where we landed tbh. I'll leave it up to @neil-marcellini if we should change it or not.

**Comment by neil-marcellini** [comment] 2024-07-12 19:11
Ah yeah this stuff again 😅, let me find what we decided.

This is working as expected. I sort of explained it [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1718296537927619?thread_ts=1716990791.744559&cid=C01GTK53T8Q) and we decided to go with the following approach at the end of that thread.

- There is one scrollable container on the page
- We show 20 recent waypoints because that matches the number we store and allows us to filter them when searching
    (I am open to feature requests to show a number of waypoints that will fit on the screen nicely, but use all 20 for searching. It's probably too complicated though and doesn't solve a real problem)
- The user knows there is a save button because it appears before the recent waypoints load
- As long as there are recent or suggested waypoints in the list, the save button isn't needed because selecting one will save it. We also don't need to hide the save button. That's added complexity without any benefit
- The user can always scroll down to find the save button, or hit enter when typing in a value (I think)

@izarutskaya I wasn't able to find a regression test checking that there are only 5 recent waypoints. If so, please update it to 20.

**Closed by neil-marcellini** 2024-07-12 19:11 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
