### ISSUE TITLE
[Hold on 29107] [$500] [MEDIUM] Tag - Selected tag in split request only appears in the Recent list after details are entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34996] opened 2024-01-23 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34236
## Action Performed:
Precondition:
- User is an employee of a Collect workspace
- The workspace has categories and tags
1. Go to workspace chat
2. Create a split bill with category and tag
3. While the scanning is ongoing, open category and tag to check Recent list in manual request confirmation page
4. Click on the split preview
5. Manually enter the details and click Split
6. Repeat Step 3

## Expected Result:
In Step 3, the selected tag will be present in the Recent list, like category

## Actual Result:
In Step 3, the selected tag is missing in the Recent list, unlike category
The selected tag only appears in the Recent list after the details are entered manually in Step 5

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/076e4c88-1ae6-424a-8b20-8a9b5e099372

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01728abc54f34f3deb</li>
        <li>Upwork Job ID: 1749882868272467968</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-23 19:53
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by s-alves10** [comment] 2024-01-24 07:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Previously selected tags doesn't appear in the recent list when editing spilt bill

### What is the root cause of that problem?

When editing tag in split bill edit page, [EditRequestTagPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestTagPage.js) page is displayed as you can see below
https://github.com/Expensify/App/blob/3ce7dc7a407915a4a907b917eaef1ff60547bb27/src/pages/EditSplitBillPage.js#L149-L156

As you can see, we don't pass `tagName` props to the `EditRequestTagPage` component. So the `tagName` value is `undefined` here
https://github.com/Expensify/App/blob/3ce7dc7a407915a4a907b917eaef1ff60547bb27/src/pages/EditRequestTagPage.js#L48

In the [TagPicker](https://github.com/Expensify/App/blob/main/src/components/TagPicker/index.js) component, we  get recently used tags list using this `tag` value
https://github.com/Expensify/App/blob/ecf641ed69d9cb37ff16de3bea129f653211618d/src/components/TagPicker/index.js#L21

`tag` is `undefined` here and so `policyRecentlyUsedTagsList` becomes `[]`

This is the root cause

### What changes do you think we should make in order to solve the problem?

We get the tag value as the first key of `policyTags` as you can see below
https://github.com/Expensify/App/blob/c0fbb9798af00257b3d2fb504be63d797a622087/src/pages/iou/request/step/IOURequestStepTag.js#L55
https://github.com/Expensify/App/blob/c0fbb9798af00257b3d2fb504be63d797a622087/src/pages/iou/MoneyRequestTagPage.js#L59

I think we don't need `tag` props in `TagPicker` component and can get its value from the `policyTags`
Remove `tag` props from the `TagPicker` and update
https://github.com/Expensify/App/blob/ecf641ed69d9cb37ff16de3bea129f653211618d/src/components/TagPicker/index.js#L21
to
```
    const tagListKey = _.first(_.keys(policyTags));
    const policyRecentlyUsedTagsList = lodashGet(policyRecentlyUsedTags, tagListKey, []);
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/24ecf335-e58c-41f7-b516-346601110162


</details>

### What alternative solutions did you explore? (Optional)
Of course we can pass the right value of `tagName` in `EditSplitBillPage` but I think the suggested solution is the best

**Comment by s77rt** [comment] 2024-01-25 16:32
@s-alves10 Thanks for the proposal. Your RCA is correct. However I think we should just put this issue on hold as wave 5 clean up should fix this. `EditSplitBillPage` will be removed.

**Comment by s77rt** [comment] 2024-01-29 18:12
@peterdbarkerUK ^

**Comment by s77rt** [comment] 2024-02-01 22:20
@peterdbarkerUK ^

**Comment by s77rt** [comment] 2024-02-05 14:39
@anmurali Please put this on hold for https://github.com/Expensify/App/issues/29107

**Comment by s77rt** [comment] 2024-02-07 18:06
@anmurali ^

**Comment by s77rt** [comment] 2024-02-12 19:30
Not overdue. Should be put on hold for https://github.com/Expensify/App/issues/29107

**Comment by s77rt** [comment] 2024-02-16 07:25
@anmurali https://github.com/Expensify/App/issues/34996#issuecomment-1939406942

**Comment by anmurali** [comment] 2024-02-16 15:30
Leaving this in my queue since it is held on another issue anyway.

**Comment by s77rt** [comment] 2024-02-26 16:53
Still on hold

**Comment by anmurali** [comment] 2024-03-05 23:46
Held issue still WIP.

**Comment by s77rt** [comment] 2024-03-14 21:45
Still on hold

**Comment by s77rt** [comment] 2024-03-25 16:03
Same ^

**Comment by s77rt** [comment] 2024-04-15 11:08
Same ^

**Comment by s77rt** [comment] 2024-04-23 23:49
Still on hold.

**Comment by s77rt** [comment] 2024-05-03 22:38
Same ^

**Comment by s77rt** [comment] 2024-05-13 22:38
This is fixed. We can close the issue. cc @anmurali

**Closed** 2024-05-22 20:55 UTC
Labels: External, Engineering, Weekly, Help Wanted, Overdue, Bug
