### ISSUE TITLE
[$500] [HOLD for payment 2023-10-31] [HOLD for payment 2023-10-30] Web - Drag and drop feature works on Scan and Distance request money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30148] opened 2023-10-22 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Start the request money flow and select "Scan"
2. Drag and drop a receipt on the scan modal
3. Select Distance option
4. Drag and drop a receipt on the distance modal

## Expected Result:
Drag and drop feature works on Scan and Distance request money

## Actual Result:
Drag and drop feature works on Scan and Distance request money

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/55fd69e7-a40a-4c75-b9f2-22898e2e4034

https://github.com/Expensify/App/assets/93399543/f97e30f2-33ed-4781-882f-0ec74e3fddd2

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ae828d7f55c050d</li>
        <li>Upwork Job ID: 1719123208894443520</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-22 15:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Drag and drop available for distance request as well
### What is the root cause of that problem?
We are subscribing to incorrect key here
```js
    withOnyx({
        selectedTab: {
            key: `${ONYXKEYS.SELECTED_TAB}_${CONST.TAB.RECEIPT_TAB_ID}`,
        },
    }),
```
### What changes do you think we should make in order to solve the problem?
We should subscribe to
```js
selectedTab: {
        key: `${ONYXKEYS.COLLECTION.SELECTED_TAB}${CONST.TAB.RECEIPT_TAB_ID}`,
    },
```
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2023-10-22 16:13
@dukenv0307 are you able to raise quick PR?
`SELECTED_TAB` is moved to collections in #26932 but your [PR](https://github.com/Expensify/App/pull/26149) didn't reflect that.

**Comment by luacmartins** [comment] 2023-10-22 21:51
We merged a fix already

**Comment by mountiny** [comment] 2023-10-22 21:56
Gonna have to pay 25% to @c3024 so $125 for their help! Thanks @alexpensify

**Comment by greg-schroeder** [comment] 2023-10-23 22:56
It seems there was a regression here: https://github.com/Expensify/App/issues/30148

**Comment by greg-schroeder** [comment] 2023-10-23 22:57
(Oops, posted in wrong issue, sorry)

**Comment by mountiny** [comment] 2023-10-25 21:36
Gonna have to pay 25% to @c3024 so $125 for their help! Thanks @alexpensify

**Comment by alexpensify** [comment] 2023-10-25 21:52
Cool, the payment date is 10-31! I'll prepare for that date.

**Comment by alexpensify** [comment] 2023-10-30 22:45
@narefyev91 - disregard this one. I needed to create an Upwork job.

**Comment by alexpensify** [comment] 2023-10-30 22:46
@c3024 - to prepare for the payment date, can you please apply to this Upwork job: 

https://www.upwork.com/jobs/~011ae828d7f55c050d

Thanks!

**Comment by c3024** [comment] 2023-10-31 07:03
Applied. Thanks @alexpensify

**Comment by alexpensify** [comment] 2023-11-01 00:45
@c3024 - thanks, I sent an offer in Upwork.

**Comment by c3024** [comment] 2023-11-01 02:57
Accepted.

**Comment by alexpensify** [comment] 2023-11-01 23:34
Done! I've finished the payment process in Upwork.

**Closed by alexpensify** 2023-11-01 23:34 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
