### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] [HOLD #20512] Web - Mentions don't show the new tooltip on hover

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21683] opened 2023-06-27 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Open a chat.
3. Mention a user using the @ symbol. Send the message.
4. Hover over the mention. It shows the old tooltip with only email.

## Expected Result:
Hovering on mentions should show the new tooltip with email, avatar and display name.

## Actual Result:
Hovering on mentions shows the old tooltip with only email.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0cd25bb2-7f69-44a1-b59b-8eaab9b5dd0e

https://github.com/Expensify/App/assets/93399543/b499550c-9a25-41a2-b97f-eb8716fda79a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687512682797759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123436a96eaad8d30</li>
        <li>Upwork Job ID: 1679594587000627200</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-27 13:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Mentions don't show the new tooltip on hover
### What is the root cause of that problem?
We are using simple tooltip rather than `UserDetailsTooltip`

https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L40-L52

### What changes do you think we should make in order to solve the problem?
We should use `UserDetailsTooltip` but since it is mentions we don't have `accountID` available for us to supply to tooltip, but it is planned to migrate to `accountID` based [mentions](https://github.com/Expensify/App/issues/21054#issuecomment-1604006760)  which then solves this issue we can put this issue on hold for this migration and then solve this issue. If we have to till then we can provide `fallbackUserDetails` for `UserDetailsTooltip` with following values
```javascript
           {
                login,
                displayName: login,
                avatar: UserUtils.getDefaultAvatar(),
            }
``` 

### What alternative solutions did you explore? (Optional)

**Comment by Nikhil-Vats** [comment] 2023-06-27 16:26
@Christinadobrzyn this issue is for the missing tooltip for mentions in chat messages.

The issue that you referenced is for missing tooltip for chats in LHN.

I think both are different.

**Comment by Christinadobrzyn** [comment] 2023-06-27 23:02
There's some big changes to tooltip happening in this GH -https://github.com/Expensify/App/pull/20512 (related to threads here - https://github.com/Expensify/Expensify/issues/290271)

I'm going to put on hold to see if it's resolved after this

**Comment by Christinadobrzyn** [comment] 2023-07-03 22:03
still on hold for https://github.com/Expensify/App/pull/20512

**Comment by Christinadobrzyn** [comment] 2023-07-12 22:22
This is almost in production - https://github.com/Expensify/App/pull/20512 - moving to daily

**Comment by Christinadobrzyn** [comment] 2023-07-13 20:52
https://github.com/Expensify/App/pull/20512 in production - testing this again it's still happening. Adding External

**Comment by Christinadobrzyn** [comment] 2023-07-14 18:34
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're receiving and reviewing proposals.

**Comment by mollfpr** [comment] 2023-07-18 02:48
Reviewing 👀

**Comment by mollfpr** [comment] 2023-07-20 15:11
Sorry for the delay 🙏

It seems we need to replace the old `Tooltip` component with `UserDetailsTooltip` to show the tooltip with account detail. The mentioned feature is only for accounts users already interact with. So we will have that `accountID` and don't need to pass `fallbackUserDetails`.

Since @Nikhil-Vats proposed the solution first [here](https://github.com/Expensify/App/issues/21683#issuecomment-1609480649), we can go with their proposal.

🎀 👀 🎀 C+ reviewed!

**Comment by alitoshmatov** [comment] 2023-07-20 16:42
> The mentioned feature is only for accounts users already interact with. So we will have that accountID and don't need to pass fallbackUserDetails.

You can also mention people you don't have interaction with, and there will be no data in `userDetails`

**Comment by Nikhil-Vats** [comment] 2023-07-20 20:51
Contributor details
Your Expensify account email: whivats5499@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015012a47c23b056bc

**Comment by tjferriss** [comment] 2023-07-25 22:26
Offers have been sent to everyone via Upworks. @mollfpr can you get started on the checklist when you have time?

**Comment by Christinadobrzyn** [comment] 2023-08-01 22:15
I'm back from ooo - happy to take this back @tjferriss - even though we're close to done - whatever is best for you!

**Comment by tjferriss** [comment] 2023-08-01 22:24
@Christinadobrzyn I can finish this one up. All that's left is the payments.

**Comment by tjferriss** [comment] 2023-08-02 03:36
All payments have been made via Upworks. @mollfpr can you complete the checklist?

**Comment by mollfpr** [comment] 2023-08-02 03:49
@tjferriss Thank you! Completing it now 🚀

**Comment by mollfpr** [comment] 2023-08-02 03:57
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. It's not caught while working on the new user detail tooltip component.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

In general, this is not a bug but rather an improvement for the tooltip to show the user detail. So the regression step should be enough.


>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Only testable on the desktop or web**

1. Open the app
2. Go to any chat
3. Mention any user by typing @ in the composer and selecting anyone from the list
4. Hover the cursor on the mentioned user
5. _Verify_ that the user detail displayed inside the tooltip
6. Now mention someone not in the mention suggestion by typing their full email like - `@unexistingperson@gmail.com`
7. Hover the cursor on the mentioned user
8. _Verify_ that the user detail displayed inside the tooltip
9. 👍 or 👎

**Comment by tjferriss** [comment] 2023-08-03 18:51
I've submitted the regression test. We're good to close this one.

**Closed by tjferriss** 2023-08-03 18:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
