### ISSUE TITLE
Login–Welcome to Expensify modal doesn’t opens if login with new Gmail account using magiclink

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38070] opened 2024-03-11 18:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4413849
**Email or phone of affected tester (no customers):** ponikarchuks+1911324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with new Gmail account
3. Copy the Magic link and change it to staging
4. Open a new tab and navigate to the staging magic link
5. Verify the abracadabra page is displayed
6. Navigate to the original tab
7. Verify the user is logged in with the new account

## Expected Result:
The engagement modal "Welcome to Expensify" is displayed. Concierge chat opens

## Actual Result:
The engagement modal "Welcome to Expensify" is displayed. Concierge chat appears only after page refresh.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7ddcfe9f-a1b2-46a4-a604-9f3c76ad8e8e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-11 18:11
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment] 2024-03-14 18:19
I couldn't reproduce this on Mac/iOS but I'm going to try tomorrow on browser stack for android.

**Comment by zanyrenney** [comment] 2024-03-18 18:28
didn't manage to test yet!

**Comment by zanyrenney** [comment] 2024-03-18 18:28
on browserstack. Will do tomorrow!

**Comment by zanyrenney** [comment] 2024-03-19 17:33
can't repro - based on these questions:

>> Is this truly a high enough priority / ROI bug to fix?
Will this affect more than x # of users?
Does it affect users who pay us?
How much of an edge case is it?
If we fix the bug later, in a year or two, will that be OK?

Closing!

**Closed by zanyrenney** 2024-03-19 17:33 UTC
Labels: Daily, Bug

**Comment by zanyrenney** [comment] 2024-03-19 17:35
I still can't reproduce this. i dont know if this is affecting a certain android device, but based on this looking like an edge case, i think we should close this.
