### ISSUE TITLE
[$1000]  Chat - Report context menu actions are not aligned consistently with hovered messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13664] opened 2022-12-16 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed:

1. Open a chat with a decent amount of messages (probably like 10 is enough)
2. Hover your mouse over a few different chats

## Expected Result: 
context menu aligned consistently every time

## Actual Result: 
context menu not aligned consistently over every message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.41-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208153547-c0434a43-b5c1-4dd5-a8a4-a0612d1b4e07.mov

https://user-images.githubusercontent.com/43996225/208153609-b2ae72e6-2740-41a9-8016-a3f933d06703.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671181811431219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176ee25b5f8c6e294</li>
        <li>Upwork Job ID: 1606391887973285888</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2022-12-23 20:42
I'm going to take this one over because Greg is on vacay and I'd like to get this one moving for next week.

**Comment by JmillsExpensify** [comment] 2022-12-23 20:47
Melvin I just said I got it. 😄

**Comment by JmillsExpensify** [comment] 2022-12-23 20:50
Huh, yeah I can also reproduce this pretty reliably. At first I thought it was due to misalignment for multi-line messages, but then I was able to see the same mis-alignment for single messages higher up.

**Comment by JmillsExpensify** [comment] 2022-12-23 20:50
I'm going to go ahead and add the `external` label to get more theories around why this is occurring, and how we can improve the reproduction steps.

**Comment by Pujan92** [comment] 2022-12-23 20:51
**Proposal**

**Issue**: It happens to grouped report action item and occurs from 2nd message onwards due to applying `top: -32px`.

**Solution 1**: Apply `top: -16px` or `top: -19px(for exact center)` for all the items and remove `isReportActionItemGrouped` parameter from the function which isn't required. We can also take this to the `styles.js` and remove the function itself as style not depends on any parameter now.

```diff
@@ -441,10 +441,11 @@ function getReportActionItemStyle(isHovered = false, isLoading = false) {
  * @param {Boolean} isReportActionItemGrouped
  * @returns {Object}
  */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
+function getMiniReportActionContextMenuWrapperStyle() {
     return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
+        ...positioning.tn4,
         ...positioning.r4,
         position: 'absolute',
         zIndex: 1,
     };

diff --git a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js b/src/pages/home/report/ContextMenu/MiniRepor
tActionContextMenu/index.js
index d90b47d71..b86b9914e 100644
--- a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
+++ b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
@@ -23,7 +23,7 @@ const defaultProps = {
 };
 
 const MiniReportActionContextMenu = props => (
-    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle(props.displayAsGroup)}>
+    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle()}>
         {/* eslint-disable-next-line react/jsx-props-no-spreading */}
         <BaseReportActionContextMenu isMini {...props} />
     </View>
```

-----------------

**Solution 2(IMO Preferable)**: Apply translate style on vertical to make it center consistently irrespective of considering the fixed height for the mini context menu.

```diff
@@ -441,10 +441,11 @@ function getReportActionItemStyle(isHovered = false, isLoading = false) {
  * @param {Boolean} isReportActionItemGrouped
  * @returns {Object}
  */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
+function getMiniReportActionContextMenuWrapperStyle() {
     return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
         ...positioning.r4,
+        top: 0,
+        transform: 'translateY(-50%)',
         position: 'absolute',
         zIndex: 1,
     };

```

**Comment by Prince-Mendiratta** [comment] 2022-12-23 20:55
@Pujan92 Hi, really interested how you are able to reply so quickly with a proposal, do you mind sharing some insights? Do you already look at the newly created issues, prepare a proposal for them and the moment they are assigned to external, post the proposal?

**Comment by tienifr** [comment] 2022-12-23 21:00
# Proposal

## Problem

In https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L231-L243 we're using `MiniReportActionContextMenu` to render the report context menu, and using `StyleUtils.getMiniReportActionContextMenuWrapperStyle(props.displayAsGroup)` to get the style of this component. 

Here is the implementation of `getMiniReportActionContextMenuWrapperStyle` function
https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js#L444-L451. 
`isReportActionItemGrouped` makes report context menu actions not aligned consistently with hovered messages. When `isReportActionItemGrouped` is true. `top` is -32, otherwise `top` is -16

## Solution

`top` value should not depends on the hovered message is grouped or not. 

In `MiniReportActionContextMenu`

```diff
...
                            <MiniReportActionContextMenu
                                reportID={this.props.report.reportID}
                                reportAction={this.props.action}
                                isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
-                                displayAsGroup={this.props.displayAsGroup}
                                isVisible={
                                    hovered
                                    && !this.state.isContextMenuActive
                                    && !this.props.draftMessage
                                }
                                draftMessage={this.props.draftMessage}
                                isChronosReport={ReportUtils.chatIncludesChronos(this.props.report)}
                            />
...
```

In `MiniReportActionContextMenu`

```diff
...

const propTypes = {
    ..._.omit(genericReportActionContextMenuPropTypes, ['isMini']),

-    /** Should the reportAction this menu is attached to have the appearance of being
-     * grouped with the previous reportAction? */
-    displayAsGroup: PropTypes.bool,
};

const defaultProps = {
    ..._.omit(GenericReportActionContextMenuDefaultProps, ['isMini']),
-    displayAsGroup: false,
};

const MiniReportActionContextMenu = props => (
-    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle(props.displayAsGroup)}>
+    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle()}>
        {/* eslint-disable-next-line react/jsx-props-no-spreading */}
        <BaseReportActionContextMenu isMini {...props} />
    </View>
);
...
```

In https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js#L444-L451

```diff
/**
 * Generate the wrapper styles for the mini ReportActionContextMenu.
 *
- * @param {Boolean} isReportActionItemGrouped
 * @returns {Object}
 */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
+function getMiniReportActionContextMenuWrapperStyle() {
    return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
+        ...positioning.tn4,
        ...positioning.r4,
        position: 'absolute',
        zIndex: 1,
    };
}
```

## Result

https://user-images.githubusercontent.com/113963320/208377353-9aaab672-d992-40e2-9394-c898ed9b72ed.mp4

**Comment by Pujan92** [comment] 2022-12-23 21:52
> We can also take this to the `styles.js` and remove the function itself as style not depends on any parameter now.

```diff
diff --git a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
index d90b47d71..e099f451f 100644
--- a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
+++ b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
@@ -1,29 +1,23 @@
 import _ from 'underscore';
 import React from 'react';
 import {View} from 'react-native';
-import PropTypes from 'prop-types';
 import {
     propTypes as genericReportActionContextMenuPropTypes,
     defaultProps as GenericReportActionContextMenuDefaultProps,
 } from '../genericReportActionContextMenuPropTypes';
-import * as StyleUtils from '../../../../../styles/StyleUtils';
 import BaseReportActionContextMenu from '../BaseReportActionContextMenu';
+import styles from '../../../../../styles/styles';
 
 const propTypes = {
     ..._.omit(genericReportActionContextMenuPropTypes, ['isMini']),
-
-    /** Should the reportAction this menu is attached to have the appearance of being
-     * grouped with the previous reportAction? */
-    displayAsGroup: PropTypes.bool,
 };
 
 const defaultProps = {
     ..._.omit(GenericReportActionContextMenuDefaultProps, ['isMini']),
-    displayAsGroup: false,
 };
 
 const MiniReportActionContextMenu = props => (
-    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle(props.displayAsGroup)}>
+    <View style={styles.reportActionMiniContextMenu}>
         {/* eslint-disable-next-line react/jsx-props-no-spreading */}
         <BaseReportActionContextMenu isMini {...props} />
     </View>
diff --git a/src/styles/StyleUtils.js b/src/styles/StyleUtils.js
index 3606cdd4e..d229716dd 100644
--- a/src/styles/StyleUtils.js
+++ b/src/styles/StyleUtils.js
@@ -437,21 +437,6 @@ function getReportActionItemStyle(isHovered = false, isLoading = false) {
     };
 }
 
-/**
- * Generate the wrapper styles for the mini ReportActionContextMenu.
- *
- * @param {Boolean} isReportActionItemGrouped
- * @returns {Object}
- */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
-    return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
-        ...positioning.r4,
-        position: 'absolute',
-        zIndex: 1,
-    };
-}
-
 /**
  * @param {Boolean} isSmallScreenWidth
  * @returns {Object}
@@ -667,7 +652,6 @@ export {
     getEmojiPickerStyle,
     getLoginPagePromoStyle,
     getReportActionItemStyle,
-    getMiniReportActionContextMenuWrapperStyle,
     getKeyboardShortcutsModalWidth,
     getPaymentMethodMenuWidth,
     getThemeBackgroundColor,
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 9fe3b6234..1abf3cb43 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1932,6 +1932,14 @@ const styles = {
         borderColor: themeColors.transparent,
     },
 
+    reportActionMiniContextMenu: {
+        ...positioning.r4,
+        top: 0,
+        transform: 'translateY(-50%)',
+        position: 'absolute',
+        zIndex: 1,
+    },
+
     reportActionContextMenuMiniButton: {
         ...spacing.p1,
         ...spacing.mv1,

pujanshah@Pujans-MacBook-Air App % git diff
diff --git a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
index d90b47d71..5f294c4ae 100644
--- a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
+++ b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
@@ -1,29 +1,23 @@
 import _ from 'underscore';
 import React from 'react';
 import {View} from 'react-native';
-import PropTypes from 'prop-types';
 import {
     propTypes as genericReportActionContextMenuPropTypes,
     defaultProps as GenericReportActionContextMenuDefaultProps,
 } from '../genericReportActionContextMenuPropTypes';
-import * as StyleUtils from '../../../../../styles/StyleUtils';
 import BaseReportActionContextMenu from '../BaseReportActionContextMenu';
+import styles from '../../../../../styles/styles';
 
 const propTypes = {
     ..._.omit(genericReportActionContextMenuPropTypes, ['isMini']),
-
-    /** Should the reportAction this menu is attached to have the appearance of being
-     * grouped with the previous reportAction? */
-    displayAsGroup: PropTypes.bool,
 };
 
 const defaultProps = {
     ..._.omit(GenericReportActionContextMenuDefaultProps, ['isMini']),
-    displayAsGroup: false,
 };
 
 const MiniReportActionContextMenu = props => (
-    <View style={StyleUtils.getMiniReportActionContextMenuWrapperStyle(props.displayAsGroup)}>
+    <View style={styles.reportActionMiniContextMenuWrapper}>
         {/* eslint-disable-next-line react/jsx-props-no-spreading */}
         <BaseReportActionContextMenu isMini {...props} />
     </View>
diff --git a/src/styles/StyleUtils.js b/src/styles/StyleUtils.js
index 3606cdd4e..d229716dd 100644
--- a/src/styles/StyleUtils.js
+++ b/src/styles/StyleUtils.js
@@ -437,21 +437,6 @@ function getReportActionItemStyle(isHovered = false, isLoading = false) {
     };
 }
 
-/**
- * Generate the wrapper styles for the mini ReportActionContextMenu.
- *
- * @param {Boolean} isReportActionItemGrouped
- * @returns {Object}
- */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
-    return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
-        ...positioning.r4,
-        position: 'absolute',
-        zIndex: 1,
-    };
-}
-
 /**
  * @param {Boolean} isSmallScreenWidth
  * @returns {Object}
@@ -667,7 +652,6 @@ export {
     getEmojiPickerStyle,
     getLoginPagePromoStyle,
     getReportActionItemStyle,
-    getMiniReportActionContextMenuWrapperStyle,
     getKeyboardShortcutsModalWidth,
     getPaymentMethodMenuWidth,
     getThemeBackgroundColor,
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 9fe3b6234..fb0478231 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1932,6 +1932,14 @@ const styles = {
         borderColor: themeColors.transparent,
     },
 
+    reportActionMiniContextMenuWrapper: {
+        ...positioning.r4,
+        top: 0,
+        transform: 'translateY(-50%)',
+        position: 'absolute',
+        zIndex: 1,
+    },
+
     reportActionContextMenuMiniButton: {
         ...spacing.p1,
         ...spacing.mv1,
```

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-24 03:16
Proposal :-

I believe we should use -32 to for all `MiniReportActionContextMenu` on top instead of -16  as using -16 on single item doesn't look good and gives inconsistent feel on single item due to line height the bottom space is very less and doesn't make it centered.

![Screenshot 2022-12-24 at 8 08 30 AM](https://user-images.githubusercontent.com/81307212/209419214-ce3db332-cac2-41e7-8270-5492d9b82054.png)

![Screenshot 2022-12-24 at 8 12 57 AM](https://user-images.githubusercontent.com/81307212/209419283-3a606881-2ef2-4077-9c23-ab0629631eb0.png)


``` diff

diff --git a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
index d90b47d71..91ed52a4b 100644
--- a/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
+++ b/src/pages/home/report/ContextMenu/MiniReportActionContextMenu/index.js
@@ -14,12 +14,10 @@ const propTypes = {
 
     /** Should the reportAction this menu is attached to have the appearance of being
      * grouped with the previous reportAction? */
-    displayAsGroup: PropTypes.bool,
 };
 
 const defaultProps = {
     ..._.omit(GenericReportActionContextMenuDefaultProps, ['isMini']),
-    displayAsGroup: false,
 };
 
 const MiniReportActionContextMenu = props => (
diff --git a/src/pages/home/report/ReportActionItem.js b/src/pages/home/report/ReportActionItem.js
index 7158f15f3..6bb40add3 100644
--- a/src/pages/home/report/ReportActionItem.js
+++ b/src/pages/home/report/ReportActionItem.js
@@ -232,7 +232,6 @@ class ReportActionItem extends Component {
                                 reportID={this.props.report.reportID}
                                 reportAction={this.props.action}
                                 isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
-                                displayAsGroup={this.props.displayAsGroup}
                                 isVisible={
                                     hovered
                                     && !this.state.isContextMenuActive
diff --git a/src/styles/StyleUtils.js b/src/styles/StyleUtils.js
index 1a14db2e7..4ad841a7d 100644
--- a/src/styles/StyleUtils.js
+++ b/src/styles/StyleUtils.js
@@ -257,15 +257,11 @@ function getBadgeColorStyle(success, error, isPressed = false) {
  * Generate a style for the background color of the button, based on its current state.
  *
  * @param {String} [buttonState] - One of {'default', 'hovered', 'pressed'}
- * @param {Boolean} isMenuItem - whether this icon is apart of a list
  * @returns {Object}
  */
-function getButtonBackgroundColorStyle(buttonState = CONST.BUTTON_STATES.DEFAULT, isMenuItem = false) {
+function getButtonBackgroundColorStyle(buttonState = CONST.BUTTON_STATES.DEFAULT) {
     switch (buttonState) {
         case CONST.BUTTON_STATES.ACTIVE:
-            if (isMenuItem) {
-                return {backgroundColor: themeColors.border};
-            }
             return {backgroundColor: themeColors.buttonHoveredBG};
         case CONST.BUTTON_STATES.PRESSED:
             return {backgroundColor: themeColors.buttonPressedBG};
@@ -444,12 +440,11 @@ function getReportActionItemStyle(isHovered = false, isLoading = false) {
 /**
  * Generate the wrapper styles for the mini ReportActionContextMenu.
  *
- * @param {Boolean} isReportActionItemGrouped
  * @returns {Object}
  */
-function getMiniReportActionContextMenuWrapperStyle(isReportActionItemGrouped) {
+function getMiniReportActionContextMenuWrapperStyle() {
     return {
-        ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
+        ...positioning.tn8,
         ...positioning.r4,
         position: 'absolute',
         zIndex: 1,

```

Using -32 gives more consistent feel.

After Fix:-

![Screenshot 2022-12-24 at 8 13 29 AM](https://user-images.githubusercontent.com/81307212/209419290-bad324eb-c688-45ef-932d-def22208d139.png)

![Screenshot 2022-12-24 at 8 13 57 AM](https://user-images.githubusercontent.com/81307212/209419291-e57b073b-55c1-44e2-8ee1-e3109d81f571.png)

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-24 03:19
I believe we should also add `design label` and get opinion of @shawnborton on it also which looks better according to the `UI` of app.

**Comment by eVoloshchak** [comment] 2022-12-26 13:51
Thank you all for doing awesome work!

@Pujan92's [proposal](https://github.com/Expensify/App/issues/13664#issuecomment-1364326248) (Solution 2):
Looks good, and centers the menu precisely 
<img width="229" alt="Screenshot 2022-12-26 at 15 09 29" src="https://user-images.githubusercontent.com/9059945/209554737-765a04ae-9ea2-42e8-9d03-7f930e26304e.png">

But in this case, menu interferes with the arrow

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/9059945/209554859-ce9f5a88-51b2-481a-a2d7-8ba13e734db1.png">

@Pujan92's second [proposal](https://github.com/Expensify/App/issues/13664#issuecomment-1364356055): 

Has the same issue with arrows, but the menu is a little bit offset from the center
<img width="214" alt="Screenshot 2022-12-26 at 15 07 11" src="https://user-images.githubusercontent.com/9059945/209555068-3be0c3c0-5a5e-4d44-b03d-e457c947ab6d.png">

@syedsaroshfarrukhdot's [propsal](https://github.com/Expensify/App/issues/13664#issuecomment-1364449868):

Fixes interference with the arrows. However, the uncentered menu looks a bit odd, so I agree with @syedsaroshfarrukhdot, we need input from the design team

**Comment by mvtglobally** [comment] 2022-12-26 17:29
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-12-27 03:47
@eVoloshchak Thank you for the review! For clarity, are you looking for design feedback specifically on @syedsaroshfarrukhdot's proposal, and perhaps even more specifically the uncentered menu? I know @shawnborton, our designer, is out at the moment but I believe he's on sporadically this week. I'd like to make sure we have a specific question waiting for him, thanks!

**Comment by eVoloshchak** [comment] 2022-12-27 11:57
> For clarity, are you looking for design feedback specifically on @syedsaroshfarrukhdot's proposal, and perhaps even more specifically the uncentered menu? 

The question is: should we implement an [uncentered menu](https://github.com/Expensify/App/issues/13664#issuecomment-1364449868) or should it be [centered](https://github.com/Expensify/App/issues/13664#issuecomment-1364326248) and we do something with the arrows?

**Comment by JmillsExpensify** [comment] 2022-12-27 16:26
@shawnborton If you wouldn't mind helping move this forward today by chiming in, that'd be appreciated. Thanks!

**Comment by bernhardoj** [comment] 2022-12-28 07:12
### **Proposal**

Maybe we can move the context menu to the left to avoid the arrow to be covered.

```diff
function getMiniReportActionContextMenuWrapperStyle(shouldAvoidOtherView) {
    return {
-       ...(isReportActionItemGrouped ? positioning.tn8 : positioning.tn4),
-       ...positioning.r4,
+       ...positioning.tn4,
+       ...(shouldAvoidOtherView ? positioning.r14 : positioning.r4),
        position: 'absolute',
        zIndex: 1,
    };
}
```

```
r14: {
    right: 52,
},
```

**_ReportActionItem.js_**
```diff
<MiniReportActionContextMenu
    reportID={this.props.report.reportID}
    reportAction={this.props.action}
    isArchivedRoom={ReportUtils.isArchivedRoom(this.props.report)}
-   displayAsGroup={this.props.displayAsGroup}
+   shouldAvoidOtherView={this.props.action.actionName === CONST.REPORT.ACTIONS.TYPE.IOU || this.props.shouldDisplayNewIndicator}
    isVisible={
        hovered
        && !this.state.isContextMenuActive
        && !this.props.draftMessage
    }
    draftMessage={this.props.draftMessage}
    isChronosReport={ReportUtils.chatIncludesChronos(this.props.report)}
/>
```

It will also avoid the `New` message marker to be covered.

**Result**

https://user-images.githubusercontent.com/50919443/209772742-3e67e1da-b33b-4d49-a12b-3909a366bcf3.mov

**Comment by bernhardoj** [comment] 2022-12-28 07:58
I think I understand why the context menu is not aligned to center for a group report. It is to prevent the long report text/message to be covered by the menu.

![image](https://user-images.githubusercontent.com/50919443/209778709-258765e3-10d5-41ca-a5b1-32f142afb87a.png)

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-28 08:35
I just checked slack for reference and noticed we are following current slack behavior to adjust `Context Menu Actions` Position Behavior for long messages and arrow handling.

Slack Behavior :-

https://user-images.githubusercontent.com/81307212/209782956-5cbc7d42-e74d-4a8a-9f99-11775e12f81f.mov

Expensify Behavior 

https://user-images.githubusercontent.com/81307212/209783164-0f79df69-c394-4b78-8c2c-329b30179a2e.mov

I believe this doesn't qualify as a bug and isn't worth fixing it is working completely fine as it is. 

Thoughts @JmillsExpensify @eVoloshchak ?

**Comment by Pujan92** [comment] 2022-12-28 10:04
> I just checked slack for reference and noticed we are following current slack behavior to adjust `Context Menu Actions Position` for long messages and arrow button handling.

Yes, seems the position of the menu is intentionally(inspired by Slack) made this way.

**Comment by JmillsExpensify** [comment] 2022-12-28 20:43
I think you're right! Also tested and saw the same. I'm going to close as a result, and @Beamanator can re-open when he returns if he things we're missing something.

**Closed by JmillsExpensify** 2022-12-28 20:43 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by shawnborton** [comment] 2022-12-30 15:45
Hmm not sure why but my screenshots look different than yours - the hover menu doesn't fully cover the arrow, so I think it looks fine as it is here:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/2319350/210088056-997f92d7-d888-46a9-969c-3e5d91d1d1e2.png">

**Comment by Beamanator** [comment] 2023-01-02 11:05
Ooh now I see why we do this, thanks everyone for the investigation and reasoning 👍
