### ISSUE TITLE
[HOLD for payment 2023-10-18] [$500] Log in - Can't login with google button when open 2 tabs

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26161] opened 2023-08-29 10:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go go Login expensify screen
2. Copy URL on browser
3. Open a new tab and paste the copied URL -> Enter
4. Click Google button -> select account and login

## Expected Result:
Can login to main space of Expensify

## Actual Result:
The page hangs, can't login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7209fc40-02f3-4d60-a8ec-a665e339fd0e

https://github.com/Expensify/App/assets/115492554/bc67ffd0-65f1-4974-83b8-a0bbe972f9ed

https://github.com/Expensify/App/assets/115492554/b5454337-ae5c-4ecd-b580-63431f3ec36d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ Le Thi Thu Thuy

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692681137050609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185c017a22df15531</li>
        <li>Upwork Job ID: 1699385050983682048</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by naveedauliat** [comment] 2023-09-06 12:02
I want to be a contributor

**Comment by naveedauliat** [comment] 2023-09-06 12:05
Your Expensify account email: naveedauliat@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/naveedauliat

**Comment by naveedauliat** [comment] 2023-09-06 12:09
Contributor details
Your Expensify account email: [naveedauliat@gmail.com](mailto:naveedauliat@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/naveedauliat

**Comment by robertKozik** [comment] 2023-09-06 13:49
Hello @naveedauliat, if you'd like to contribute to this issue, please feel free to draft a proposal with your suggested solution. For additional details on contributing, you can refer to our [contribution guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by Selyatin** [comment] 2023-09-06 21:51
Contributor details

Your Expensify account email: selyatinismet@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016e2c0344b1f727ea

**Comment by Selyatin** [comment] 2023-09-07 01:19
@robertKozik @izarutskaya

The _issue_ is caused by [ActiveClientManager](https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/libs/ActiveClientManager/index.js#L67) picking the **most recently** opened browser tab as the **Leader Client**, meaning all the request processing must be handled through the most recently opened tab to keep all tabs synchronized.

Here's the [SequentialQueue line](https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/libs/Network/SequentialQueue.js#L77) that checks if the current client is the leader or not, then processes the request if it's the leader, otherwise it doesn't take any action.

Removing the leader check causes issues in the app, as demonstrated here.

https://github.com/Expensify/App/assets/50295732/2d872806-bc52-4378-a62c-99828bd12791

Using the latest opened tab works as displayed here:

https://github.com/Expensify/App/assets/50295732/d7a5747e-c572-4c1a-bac4-e66a3865b2ee

The most straightforward solution to this problem is disabling the Login form on the page that's **not** the leader and displaying a message to the user such as `You've opened the Login page in a separate tab, please Login from that specific tab.`

The complex path involves implementing a synchronization method. This method would include polling the persistent data stored in IndexDB and removing the task that is executed by the current tab to prevent it from being executed by other tabs.

I'll prepare a PR with the straightforward solution, since the complex path doesn't seem to be a viable solution, it would most likely require quite a bit of changes on how the queue is handled. However I might be wrong since I've only dabbled my feet in the project for merely 3 hours.

**Comment by robertKozik** [comment] 2023-09-11 07:53
Thanks for your proposal @Selyatin ! I think it looks good and for sure fixes the issue here. 
Have you check the possibility of changing activeClient based on the user focus?

**Comment by Selyatin** [comment] 2023-09-11 11:40
@robertKozik 

Using user focus or to be more specific checking page visibility via [`document.hidden`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden) property causes the same black screen issue as the first video displayed in my [first reply](https://github.com/Expensify/App/issues/26161#issuecomment-1709325963).

It seems to be related to [NetworkStore.isSupportRequest](https://github.com/Expensify/App/blob/ef0eb33e4e11340addeedadccddcce859699c578/src/libs/Network/NetworkStore.js#L114C1-L114C1) function, the app simply refuses to make the necessary API calls. 

Though I couldn't understand why it's behaving this way just from looking at the project code. I might have to specifically look into the [Onyx](https://github.com/Expensify/react-native-onyx) project unless someone can provide me some guidance on this matter.

I can also start working on the current proposal if it's not worth pursuing this issue at the moment.

Here are the logs where the app gave me black screen:

<img width="1249" alt="Screenshot 2023-09-11 at 14 02 19" src="https://github.com/Expensify/App/assets/50295732/1aad218a-9d1d-4e34-bfa1-4572c68cc373">

Here's the working example:

<img width="1250" alt="Screenshot 2023-09-11 at 14 01 42" src="https://github.com/Expensify/App/assets/50295732/f9f8e366-5301-43e0-b617-fa88e45fc719">

**Comment by Selyatin** [comment] 2023-09-13 14:56
A PR will be ready to be reviewed by Monday.

**Comment by flaviadefaria** [comment] 2023-09-26 10:07
What's the latest here? Is the PR still being reviewed?

**Comment by yuwenmemon** [comment] 2023-09-29 05:52
@flaviadefaria I'm heading out on sabbatical. Would you be able to find another engineer to review? (You _might_ be able to do this by just applying the `Engineering` label)

**Comment by robertKozik** [comment] 2023-10-11 07:46
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **Cannot determine any particular PR, it's new edge-case which was not handed**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I believe it's highly unlikely for this bug to be reproduced. Therefore, in my opinion, creating a new regression test might be redundant.**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by flaviadefaria** [comment] 2023-10-16 10:01
Payment Summary:

>@Selyatin requires payment
@robertKozik does not require payment (Contractor)

@Selyatin - $500 - 50% penalty = $250
@ Le Thi Thu Thuy - $50 (reporting bonus)

**Comment by situchan** [comment] 2023-10-18 14:40
@thuyle04 is the correct GH handle (found on slack)
cc: @flaviadefaria

**Comment by Selyatin** [comment] 2023-10-18 17:59
@flaviadefaria https://www.upwork.com/freelancers/~016e2c0344b1f727ea

**Comment by flaviadefaria** [comment] 2023-10-19 10:36
@Selyatin offer sent!
@thuyle04 I can't find you in UW can you please send me your profile link? Thanks!

**Comment by flaviadefaria** [comment] 2023-10-23 08:39
@Selyatin you've been paid!
@thuyle04 please reopen this GH once you're ready to share your UW credentials.

**Comment by thuyle04** [comment] 2023-10-23 10:59
Contributor details
Your Expensify account email: [thuy.lethithu@antbuddy.com](mailto:thuy.lethithu@antbuddy.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by thuyle04** [comment] 2023-10-23 10:59
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by flaviadefaria** [comment] 2023-10-23 11:24
@thuyle04 thanks! I sent you an offer, now I just need you to accept it so that I can process your payment.

**Comment by thuyle04** [comment] 2023-10-23 11:42
@flaviadefaria I think I will be paid 250 USD instead of 50 USD (old payment structure ) because the new payment structure was just changed on August 31 while the bug was approved before that.

**Comment by flaviadefaria** [comment] 2023-10-23 12:12
Cool, np! You can accept the contract and I'l pay the 200 difference as a bonus. Can you let me know once you have accepted it?

**Comment by flaviadefaria** [comment] 2023-10-25 07:45
@thuyle04 you've been paid so closing this.

**Closed by flaviadefaria** 2023-10-25 07:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
