### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Expensify card - Expensify card link navigates to wallet instead of virtual card details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49804] opened 2024-09-26 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5012494
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Create a workspace
3. Navigate to the workspace settings > More Features
4. Enable Expensify card option
5. Navigate to the Expensify card and click on Issue card
6. Select Connect online with plaid and add the VBA
7. Issue the virtual Expensify card to the current user
8. Navigate to the workspace chat
9. Click on the Expensify card link

## Expected Result:
User is navigated to the virtual Expensify card details

## Actual Result:
User is navigated to the wallet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/70545897-820d-4677-8a76-7bbf6b575ed4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839673843128973218</li>
        <li>Upwork Job ID: 1839673843128973218</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104214637</li>
<li>truph01 | Contributor | 104214639</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by jais-nikhil** [comment] 2024-09-26 19:54
I will check the redirection logic written there and modify it as per requirements to redirect it to wallets.

**Comment by truph01** [comment] 2024-09-26 23:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is navigated to the wallet

### What is the root cause of that problem?
- We always navigate the user to wallet page via:
https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1750-L1751

### What changes do you think we should make in order to solve the problem?
- We should add additional params ```policyID```, ```cardID``` to:

https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1745


and instead of ```ROUTES.SETTINGS_WALLET``` in:

https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1751
use:

```
ROUTES.WORKSPACE_EXPENSIFY_CARD_DETAILS.getRoute(policyID, cardID)
```

- ```policyID``` and ```cardID``` are passed down in where getCardIssuedMessage is called.
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-09-26 23:24
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
User is navigated to the wallet

### What is the root cause of that problem?
- We always navigate the user to wallet page via:
https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1750-L1751

### What changes do you think we should make in order to solve the problem?
- We should add additional params ```policyID```, ```cardID``` to:

https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1745


and instead of ```ROUTES.SETTINGS_WALLET``` in:

https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/libs/ReportActionsUtils.ts#L1751
use:

```
ROUTES.WORKSPACE_EXPENSIFY_CARD_DETAILS.getRoute(policyID, cardID)
```

- ```policyID``` and ```cardID``` are passed down in where getCardIssuedMessage is called:
https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/components/ReportActionItem/IssueCardMessage.tsx#L45
### What alternative solutions did you explore? (Optional)


- We can navigate to another page instead of ```ROUTES.WORKSPACE_EXPENSIFY_CARD_DETAILS.getRoute(policyID, cardID)``` based on future discussion.

**Comment by jjcoffee** [comment] 2024-09-30 08:45
@truph01's [proposal](https://github.com/Expensify/App/issues/49804#issuecomment-2378111577) LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by iwiznia** [comment] 2024-09-30 14:00
Solution looks good, but I see `getCardIssuedMessage` is called in other places than `IssueCardMessage`, can you include details of all of the places we need to update?
Also, I also don't quite get where will you get the cardID from exactly in [App/src/components/ReportActionItem/IssueCardMessage.tsx](https://github.com/Expensify/App/blob/70a8a16114d68d871a89a2fb0aef841fac1c948d/src/components/ReportActionItem/IssueCardMessage.tsx#L45)

**Comment by truph01** [comment] 2024-10-01 10:49
> getCardIssuedMessage is called in other places than IssueCardMessage, can you include details of all of the places we need to update?

- Logic displays the report's name:
https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/libs/ReportUtils.ts#L3838-L3840

- Logic displays the last message text in LHN:

https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/libs/SidebarUtils.ts#L435-L436

- Logic displays copy message:
https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L482-L483

The ```getCardIssuedMessage``` are used in the above places. If we update ```getCardIssuedMessage``` function, these places will auto work properly.


> I also don't quite get where will you get the cardID from exactly in

We can get cardID can get from the report action data:

![image](https://github.com/user-attachments/assets/5aaf2c0c-2558-447a-b330-794eb15509bf)

**Comment by truph01** [comment] 2024-10-02 08:39
[PR](https://github.com/Expensify/App/pull/50039) is ready

**Comment by slafortune** [comment] 2024-10-07 20:06
PR not yet merged

**Comment by slafortune** [comment] 2024-10-17 18:55
@jjcoffee can you please complete the checklist?

**Comment by jjcoffee** [comment] 2024-10-18 13:31
- The PR that introduced the bug has been identified. Link to the PR: N/A - this was a missing feature in https://github.com/Expensify/App/pull/46281
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. [Admin] On a workspace with Expensify cards enabled, navigate to Workspace Settings > Expensify card
2. [Admin] Click on Issue card and issue a virtual Expensify card to any non-admin workspace member
3. [Admin] Navigate to the workspace chat
4. [Admin] Verify that tapping the `Expensify card` link in the card issued message opens the virtual Expensify card details.
5. [Non-admin] Log in as the user to whom the card was assigned.
6. [Non-admin] Open the same workspace chat.
7. [Non-admin] Verify that tapping the `Expensify card` link in the card issued message opens the virtual Expensify card details.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-10-18 13:32
@slafortune All done!

**Comment by slafortune** [comment] 2024-10-18 18:00
@jjcoffee Role - C+ - Paid $250 via Upwork
@truph01 Role - Contributor - Paid $250 via Upwork

**Closed by slafortune** 2024-10-18 18:00 UTC
Labels: External, Daily, Awaiting Payment, Bug
