### ISSUE TITLE
[HOLD for payment 2023-08-03] [HOLD for payment 2023-08-02] Task - Unable paste from clipboard on share somewhere page after reloading the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23539] opened 2023-07-25 10:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account
2. Click on FAB > Assign task > Give it a title > Click next
3. Click on share somewhere > paste something into the input field > confirm it pastes correctly
4. Reload the page while in the share somewhere page
5. Try to paste text inside the text input field

## Expected Result:
Text should be pasted inside the input field

## Actual Result:
Unable to paste text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12100647-6c79-4dcc-bcd9-2b13df9df91d

https://github.com/Expensify/App/assets/93399543/15b6ee90-2b39-4df6-9477-551ff68eeaae

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690276386534669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2023-07-25 11:30
This is a regression of some PR, but I don't think this is a deploy blocker since it's a super edge case, almost no one would try to paste after reloading the new task page.

**Comment by pecanoro** [comment] 2023-07-25 11:53
Found the PR that caused the regression (https://github.com/Expensify/App/pull/23135), I tested it with and without and it's working with the old changes.

**Comment by mountiny** [comment] 2023-07-25 11:53
@pecanoro there is a Pr up with a follow up, confirming if it solves the issue.

**Comment by pecanoro** [comment] 2023-07-25 11:55
@mountiny Yeah, if the root cause is the same, we should close this one as it's the same bug.

**Comment by mountiny** [comment] 2023-07-25 11:58
The PR fixes this too so I will add this issue to the PR body and add reviewing label

**Comment by pecanoro** [comment] 2023-07-25 11:59
Awesome, thank you so much!!

**Comment by pecanoro** [comment] 2023-08-04 10:37
Hmm this was a duplicate of https://github.com/Expensify/App/issues/23502 and https://github.com/Expensify/App/issues/23537 and we agreed to close it.

**Closed by pecanoro** 2023-08-04 10:37 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
