### ISSUE TITLE
[$1000] IOS - Shows hover effect for recipient in chatting screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23485] opened 2023-07-24 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Click on recipient’s email or name ( or Long press to see the hover effect of clicking)

## Expected Result:
As No other platform has this effect, This hover effect should not be there in iOS app

## Actual Result:
Shows hover effect on click of user’s email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2dd45d8b-ac3e-4415-9bf5-505ab48449a7

https://github.com/Expensify/App/assets/93399543/1ad2ec0d-0f30-46ea-b8ca-6299ba180c57

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690140430810329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01420db962b34cb936</li>
        <li>Upwork Job ID: 1684241290957914112</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-07-26 16:36
Reproducible, triaging to external

**Comment by situchan** [comment] 2023-07-31 16:23
I commented [here](https://github.com/Expensify/App/issues/22103#issuecomment-1658719618).

**Comment by sonialiap** [comment] 2023-08-03 18:12
Agreed, this is a dupe. I missed it on triage. Closing

**Closed by sonialiap** 2023-08-03 18:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
