### ISSUE TITLE
[$1000] Web -  Pressing `esc` when cursor outside report action when attachment carousel open doesn't de-select the report action

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21621] opened 2023-06-26 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send 1-2 attachments
2. Click on an attachment
3. Move the cursor outside the report action beneath
4. Press escape

## Expected Result:
The report action should be de-selected

## Actual Result:
The report action is still selected and mini report action context menu is visible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2674d401-a7ba-4257-a67c-b097b6eb9a00

https://github.com/Expensify/App/assets/93399543/2749a4f5-9ff6-4c6a-a0f7-2534f45db6ec

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687459031260869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c1eceec2b90f3f6</li>
        <li>Upwork Job ID: 1674168482540216320</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-06-28 21:31
No overdue - @Santhosh-Sellavel what do you think of the first proposal that has already come in?

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 23:41
Unassigning due to low bandwidth, as it has a proposal already. I don't want to keep this waiting!

Please assign a new C+ @abekkala by adding external label again thanks!

**Comment by abekkala** [comment] 2023-06-30 19:02
@sonialiap I needed to get a new C+ assigned as Santhosh unassigned and I'm reassigning for sabbatical
___

### CURRENT STATUS: 
We need @rushatgabhane to review the proposals that have come in. 
If we can't find a suitable proposal we can take this to the export contributors.

**Comment by sonialiap** [comment] 2023-07-03 14:48
@rushatgabhane what are your thoughts about the proposals on this issue?

**Comment by sonialiap** [comment] 2023-07-05 16:09
I also can't reproduce anymore

**Comment by sonialiap** [comment] 2023-07-11 14:59
Not reproducible, closing

**Closed by sonialiap** 2023-07-11 14:59 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
