### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Attachment preview does not update dynamically

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21334] opened 2023-06-22 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open user B report
3. Open app in another device and login with user B
4. From user B, send user A any image attachment
5. From user A, open attachment sent by user B
6. From user B, send new attachment
7. Check in user A that new attachment is not visible in attachment preview, close the preview, open latest attachment
8. From user B, delete the latest attachment 
9. Check in user A that we can still access that attachment

## Expected Result:
App should dynamically update attachment preview

## Actual Result:
App does not dynamically update attachment preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/452aeacf-a978-4494-a1e8-f830a84b4bb0

https://github.com/Expensify/App/assets/93399543/da1ecd77-3da8-4241-9c3b-419c4baa3338

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686896537390179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01507a5371aef23c4a</li>
        <li>Upwork Job ID: 1674577622879911936</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-06-22 22:03
Check [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1687471385852519)
> I'm been seeing a lot of bug reports about parts of the app not dynamically updating.  I'm going to continue to treat these individually as bugs, if they should be rolled into a project or tracking GH, please :thread:   cc 
[@Dhanashree Dattaram Sawant](https://expensify.slack.com/team/U04FW4A1RHR)
, since it appears you're reporting a lot of 'em

**Comment by mallenexpensify** [comment] 2023-06-28 02:34
No action the last time I posted so followed up
https://expensify.slack.com/archives/C01GTK53T8Q/p1687919663462329?thread_ts=1687471385.852519&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2023-06-28 16:21
Thanks for the comment on [the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1687921178317009?thread_ts=1687471385.852519&cid=C01GTK53T8Q) @dhanashree-sawant.  
<img width="955" alt="image" src="https://github.com/Expensify/App/assets/22508304/f58642a5-f9da-45a9-8b96-019a4ff6442e">

Can you review the 'update dynamically' bugs you've reported to see if there's a commonality and/or root cause so that we might be able to bunch some together?  If not we can manage them individually, it just takes more time/resources to do so.

**Comment by mallenexpensify** [comment] 2023-06-30 00:37
Thanks for updating that thread @dhanashree-sawant.
Let's move this forward independently, I think it can be external, do you agree @narefyev91 ?

**Comment by narefyev91** [comment] 2023-06-30 09:12
@mallenexpensify sure we can make it external - proposal from @dukenv0307 looks good to me https://github.com/Expensify/App/issues/21334#issuecomment-1603091795
🎀 👀 🎀 C+ reviewed - (any code discussion can be done in PR)

**Comment by narefyev91** [comment] 2023-07-04 12:15
@jasperhuangg Any updates here? cc @mountiny

**Comment by mountiny** [comment] 2023-07-04 19:44
Gonna go ahead and assign @dukenv0307 based on C+ suggestion but all yours @jasperhuangg

**Comment by narefyev91** [comment] 2023-07-06 12:09
> @narefyev91 @mountiny what do you think about my comment above [#21334 (comment)](https://github.com/Expensify/App/issues/21334#issuecomment-1620944577)

Oh sorry - missed that - can you please raise this topic in slack in open-source channel - let's bring more people to get their thoughts

**Comment by jasperhuangg** [comment] 2023-07-10 20:39
@dukenv0307 Looks like [the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1689009994703539?thread_ts=1688646398.596839&cid=C01GTK53T8Q) has consensus that it's fine for us to just close out the modal!

**Comment by jasperhuangg** [comment] 2023-07-28 22:46
PR was merged!

**Comment by mananjadhav** [comment] 2023-07-29 19:53
@jasperhuangg @narefyev91 Any specific reason we decided to use `Navigation.dismissModal`? If I copy the attachment link and paste it directly in the addressbar (or deep link), what happens? 

We added BlockingView in the [PR](https://github.com/Expensify/App/pull/23143), which now shows conflict, hence checking if there was any specific reason for dismissing?


cc - @ahmedGaber93  @marcochavezf

**Comment by Natnael-Guchima** [comment] 2023-07-31 14:23
There seems to be this regression https://github.com/Expensify/App/issues/23896#issuecomment-1658348509 from this pr

**Comment by ahmedGaber93** [comment] 2023-08-01 17:42
We have 2 separator issues:
1. when navigate to delete image by deeplink app crash.
2. attachment preview not update dynamically when attachments list changed (it is a new feature more than issue).

And 3 options for deleted case.
1. dismiss the modal for both (maybe bad UX for deeplink).
2. show NotFound for both (maybe bad UX for dynamic update).
3. use dismiss modal for dynamic update, and NotFound for deeplink.
I think `page == -1` is not this the accurate condition for dynamic update.
This is an idea for that.
```javascript
useEffect(() => {
    const initialState = createInitialState(props);
    // compare initialState.attachments with attachments state.
    // and initialState.page with page state to determind is dynamic update or deeplink.
    if(dynamic update){
        // dismiss modal here not in createInitialState.
        // or show next/prev page
    }
    
    setPage(initialState.page);
    setAttachments(initialState.attachments);
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [props.reportActions]);
```

can you know is it dynamic update or not from initialState(new state) and attachment && page(old state)? @dukenv0307

**Comment by kidroca** [comment] 2023-08-10 08:26
Hello everyone,

I'd like to kindly point out that the behavior addressed in this issue is actually intended and not a bug. We had made a deliberate decision not to update the attachment carousel in real-time while a user is interacting with it. This is especially crucial when an attachment is removed, as it could be disruptive if another user is currently viewing it. 

For clarity, we had previously discussed and concurred that the carousel should remain unchanged while active. Any deletions should only be reflected after the carousel is closed.

For your reference:
- My initial proposal which was agreed upon can be found [here](https://github.com/Expensify/App/issues/17743#issuecomment-1518644347).
- Additionally, @sobitneupane had raised a relevant question [here](https://github.com/Expensify/App/issues/17743#issuecomment-1527516066), to which @cead22 and @JmillsExpensify confirmed our intended behavior regarding the carousel.

I understand the intention behind the recent changes, but given our prior discussions, it might be best to revert to the original behavior. Thank you for your understanding.

**Comment by jasperhuangg** [comment] 2023-08-10 17:06
@kidroca is your main concern that the experience will be jarring to the user if they are viewing an attachment that gets deleted? 

@dukenv0307 I believe that's currently the only action that will dynamically update the modal. If a new attachment is sent then the currently viewed attachment shouldn't change. Perhaps we should make it so that we don't dynamically dismiss the modal if an attachment is deleted?

**Comment by jasperhuangg** [comment] 2023-08-22 18:38
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@jasperhuangg] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@jasperhuangg] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@jasperhuangg] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@narefyev91 / @dukenv0307] Determine if we should create a regression test for this bug.
> * [ ]  [@narefyev91 / @dukenv0307] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@mallenexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

This bug wasn't really directly caused by a PR, it just wasn't considered in the initial design. I think adding a regression test should be plenty.

**Comment by jasperhuangg** [comment] 2023-08-22 18:38
bump @narefyev91, @dukenv0307 on the regression test!

**Comment by narefyev91** [comment] 2023-08-23 06:44
Regression Tests
Case 1: 
1- Open the app and login with user A and user B from different browsers.
2- Start chat between user A and user B.
3- From user A send an attachment in the chat.
4- From user B open the attachment in preview, and copy the URL.
5- From user A delete the attachment and Verify the user B attachment preview is dissmised.
6- Open the URL and Verify that the app displays 'Hmm its not here' page and doesn't crash.

Case 2:
- The attachment modal should update dynamically if another user sends a new attachment
1. Login with user A
2. On another device, login with user B
3. From user B, send an attachment
4. From user A, click on the attachment to open attachment modal
5. From user B, send an attachment again
6. From user A, verify that the user can click on the arrow right button to see the newest attachment that is sent by user B

Case 3
- The attachment modal should dismiss if another user deletes the attachment that is displaying
1. Login with user A
2. On another device, login with user B
3. From user Bm send an attachment
4. From user A, click on the attachment to open attachment modal
5. From user B, delete this attachment
6. From user A, verify that attachment modal closed

**Comment by mallenexpensify** [comment] 2023-08-29 22:59
@jasperhuangg and/or @narefyev91 it looks like @dukenv0307 was assigned on  July 4
<img width="628" alt="image" src="https://github.com/Expensify/App/assets/22508304/ce00e105-2ce5-4e96-8a5d-0a41a5d55cd3">

And the PR merged on July 28th. 
<img width="439" alt="image" src="https://github.com/Expensify/App/assets/22508304/38e230e6-800b-4721-a742-dbd4667b00cb">

Normally there would be a reduction in pay for the length of time, is that the case here or is there something I'm unaware of?

**Comment by jasperhuangg** [comment] 2023-09-01 20:39
@mallenexpensify that is correct, there was some back and forth with the PR that delayed getting it out.

**Comment by mallenexpensify** [comment] 2023-09-05 00:43
@dhanashree-sawant, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01c9714d2d5e8197db

@dukenv0307 paid $500 via Upwork. (will post final payment breakdown once Dhanashree is paid)

**Comment by mallenexpensify** [comment] 2023-09-05 00:45
@strepanier03  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx (it's just paying Dhanashree then posting the payment format as the final post)

**Comment by dhanashree-sawant** [comment] 2023-09-05 05:15
Thanks @mallenexpensify, I have accepted the offer.

**Comment by strepanier03** [comment] 2023-09-05 22:35
I have paid @dhanashree-sawant via Upwork and closed the contract.

----

Looks like so far:

- Bug Reporter - @dhanashree-sawant - $250 - Paid via Upwork
- Contributor - @dukenv0307 - $500 - Paid via Upwork
- C+ - @narefyev91 - $500 - to be paid via Manual Requests (I am pretty sure)

----

@mallenexpensify - Is that what you meant by "posting the payment format as the final post"??

**Comment by strepanier03** [comment] 2023-09-05 22:35
### Payment Summary

- [x] Bug Reporter - @dhanashree-sawant - $250 - Paid via Upwork
- [x] Contributor - @dukenv0307 - $500 - Paid via Upwork
- [ ] C+ - @narefyev91 - $500 - to be paid via Manual Requests (I am pretty sure)

**Comment by strepanier03** [comment] 2023-09-08 00:05
@narefyev91 - Have you submitted your Manual Request for payment? If so let me know and I'll assign over to Jason for payment.

**Comment by narefyev91** [comment] 2023-09-08 06:22
> @narefyev91 - Have you submitted your Manual Request for payment? If so let me know and I'll assign over to Jason for payment.

Hey! I'm from Callstack - no additional payments needed :-)

**Comment by mallenexpensify** [comment] 2023-09-11 07:25
Thanks @strepanier03 , updated the above comment to

Payment Summary
 Bug Reporter - @dhanashree-sawant - $250 - Paid via Upwork
 Contributor - @dukenv0307 - $500 - Paid via Upwork
 C+ - @narefyev91 is due $500 - he's with CallStack and paid outside of Upwork.

**Comment by mallenexpensify** [comment] 2023-09-11 07:27
Thanks @narefyev91 for regression test steps, TestRail GH is here
- https://github.com/Expensify/Expensify/issues/315684

**Closed by mallenexpensify** 2023-09-11 07:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
