### ISSUE TITLE
Web -  Sign in option is missing when user on a public NewDot chat in another tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28540] opened 2023-09-30 16:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In an incognito window, go to https://new.expensify.com/r/3504895439653267
2. Open another incognito tab and go to https://www.expensify.com/

## Expected Result:
User should see the option to sign in.

## Actual Result:
 Sign in option is missing when user on a public NewDot chat in another tab

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/93399543/50ff5b40-8277-4a9c-8d62-3ad021213545)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695891244520119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2023-10-02 21:50
Cannot reproduce on Safari v1.3.75-12:

<img width="1487" alt="image" src="https://github.com/Expensify/App/assets/36425901/88b85dc7-8e6a-4a9f-9b8f-f193e4138749">

**Comment by MitchExpensify** [comment] 2023-10-02 21:51
Can you still reproduce on v1.3.75-12 @sakluger ?

**Comment by MitchExpensify** [comment] 2023-10-05 21:31
Lil bump @sakluger 😄

**Comment by MitchExpensify** [comment] 2023-10-09 22:55
Closing but feel free to reopen if still experiencing this @sakluger !

**Closed** 2023-10-16 17:31 UTC
Labels: Daily, Overdue, Bug
