### ISSUE TITLE
iOS - Singin - The last link sent to reset your password shows an error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11147] opened 2022-09-20 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Enter the login in the signin page
3. Make it send two password reset links
4. Use the old or expired link
5. Ensured appropriate error message is displayed and new link is received in email/sms
6. Used the latest link and updated password and it worked

## Expected Result:
When following the last link we should not see the error of the previous link.

## Actual Result:
The last link sent to reset your password shows an error

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** v1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191329977-19256be3-2b44-427e-b853-60c19194da33.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-09-20 18:29
@kavimuru from the video at around 1:00, it seems like the tester selects the first email that was sent and not the one with the latest validation link (after they tapped `Resend link`). We will invalidate previous links whenever we generate a new one. 

Can you please retest?

**Comment by alex-mechler** [comment] 2022-09-20 18:38
Ah, thanks for pointing that out, that was going to be my first question 😅. This doesn't look like a bug provided the second link that we send works as expected.

**Comment by luacmartins** [comment] 2022-09-20 18:40
@kavimuru I see that you removed the `DeployBlockerCash` label. Does that mean that this is working as expected?

**Comment by kavimuru** [comment] 2022-09-21 14:06
@luacmartins It's happening in production too. So I removed `deployblocker `label.  Yes, at the timeline 1:00 tapping the invalid link proper error message appears, then again when the latest link is tapped the same error message persistent. But able to set password with 2nd link as in the video.

**Comment by luacmartins** [comment] 2022-09-21 14:54
Ah ok I see what you mean now. I think that's the expected behavior since the error still exists. I do think however that we should clear the error once we click SetPassword. I'm putting up a fix to clear the error on submit here - https://github.com/Expensify/App/pull/11165

**Comment by luacmartins** [comment] 2022-09-21 22:01
Closing this one in favor of https://github.com/Expensify/App/issues/11186

**Closed by luacmartins** 2022-09-21 22:01 UTC
Labels: Engineering, Daily
