### ISSUE TITLE
[HOLD for payment 2024-06-28]  [$250] Web - Categorizing - Folder icon in empty state screen is not centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43064] opened 2024-06-04 19:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41344
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Delete all the categories
4. Go to FAB > Track expense > Manual
5. Track an expense
6. Click Categorize it from actionable whisper
7. Select the workspace from Step 2

## Expected Result:
The folder icon in empty state screen should be centered

## Actual Result:
The folder icon in empty state screen is not centered.
It is aligned a bit to the left

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31a3b6f8-4a43-4a4b-81e2-2f8c72955078

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e432e93c8345898</li>
        <li>Upwork Job ID: 1798238220399464448</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 102614841</li>
<li>tienifr | Contributor | 102614843</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment] 2024-06-04 19:44
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hayata-suenaga** [comment] 2024-06-05 06:18
missed this. working on it right now

**Comment by hayata-suenaga** [comment] 2024-06-05 06:19
I don't think we have to block deploy for this. removing the deploy blocker label

**Comment by Tony-MK** [comment] 2024-06-05 06:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Categorizing - Folder icon in empty state screen is not centered

### What is the root cause of that problem?

Unlike the workspace page, the IOURequestStepCaterogy page has a block view with the `contentFitImage` attribute.

https://github.com/Expensify/App/blob/4e4715feb25252b4c47b812807fdd1f071145825/src/pages/iou/request/step/IOURequestStepCategory.tsx#L172-L176

https://github.com/Expensify/App/blob/4e4715feb25252b4c47b812807fdd1f071145825/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L321-L326

### What changes do you think we should make in order to solve the problem?


We should use the <WorkspaceEmptyStateSection> or remove the `contentFitImage="contain"`

```
<BlockingView
    icon={Illustrations.EmptyStateExpenses}
    title={translate('workspace.categories.emptyCategories.title')}
    subtitle={translate('workspace.categories.emptyCategories.subtitle')}
/>
```

**Comment by jjcoffee** [comment] 2024-06-05 11:13
@dragnoir @ZhenjaHorbach Let's try to keep a good tone here. I know it can be frustrating when you notice edits to other proposals, but these will generally be taken into account by the C+ reviewing. If you feel the C+ has missed something in their review, you're welcome to point it out once the review is complete. Too much back and forth before the review leads to a messy issue that's harder for everyone to read through. Thanks! :pray:

**Comment by jjcoffee** [comment] 2024-06-05 13:50
I think @tienifr has provided the tidiest [solution](https://github.com/Expensify/App/issues/43064#issuecomment-2149020754) here. This bug appeared because of essentially reimplementing `WorkspaceEmptyStateSection` with the wrong width attribute, so it makes sense to use it here to prevent future bugs. Happy to go with them!

@dragnoir The SVG doesn't have the wrong width as you claim in your RCA. 
@Tony-MK I'm not sure if your solution would help given the wrong width attribute is used.
@ZhenjaHorbach As above, it makes more sense to just use `WorkspaceEmptyStateSection` as it reduces duplicate code and avoids the potential for future regressions.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by hayata-suenaga** [comment] 2024-06-05 21:30
Thank you very much everyone for your proposals. We'll go with @tienifr's proposal this time 😄

**Comment by hayata-suenaga** [comment] 2024-06-05 23:01
@jjcoffee can you check [the comment above](https://github.com/Expensify/App/issues/43064#issuecomment-2151013778)?

**Comment by jjcoffee** [comment] 2024-06-06 08:18
@dragnoir The need to adjust styles in that component is mentioned in the [proposal](https://github.com/Expensify/App/issues/43064#issuecomment-2149020754) that I have selected. The whole point of having a reusable component is so that we can reuse it across the app. Needing to tweak the style is a necessary part of it being reusable across different screens. The benefit of not having to re-declare the icon sizes (what if they change?) far outweighs having to declare the style.

**Comment by jjcoffee** [comment] 2024-06-06 09:17
@dragnoir `WorkspaceEmptyStateSection` is only used with the `Illustrations.EmptyStateExpenses` icon, so it will always have that specific size that is hardcoded in the component. I'm not sure the reason why the icon isn't also hardcoded in the component given the component's name, but this isn't really a generic component for inserting any old icon.

Again it's not much of a trade-off to have to add a few more props to allow the component and thus the empty state icon to be generic enough to be used in other parts of the app. The benefit is clear - if we ever change the icon we only have one place to update the sizing.

**Comment by jjcoffee** [comment] 2024-06-10 08:00
Nearly there with the PR, just waiting for an additional screenshot and we should be good to go!

**Comment by jjcoffee** [comment] 2024-06-11 12:51
PR approved from my side.

**Comment by hayata-suenaga** [comment] 2024-06-14 06:02
I've been OOO. I approved and merged the PR!

**Comment by abekkala** [comment] 2024-06-25 14:47
### PAYMENT SUMMARY FOR JUN 28

- **Fix:** @tienifr [$250, if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/102614843)
- **PR Review:** @jjcoffee [$250, if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/102614841)
please complete checklist

**Comment by jjcoffee** [comment] 2024-06-26 09:35
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41344
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41344/files#r1654468598
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a new workspace
2. Delete all the categories
3. Go to FAB > Track expense > Manual
4. Track an expense
5. Click `Categorize it` from the actionable whisper
6. Select the workspace from Step 2
7. Verify that the folder icon is centered

Do we agree 👍 or 👎

**Comment by abekkala** [comment] 2024-06-28 16:48
@tienifr @jjcoffee - payments sent and contracts ended - thank you! 🎉

**Closed by abekkala** 2024-06-28 16:48 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
