### ISSUE TITLE
[$1000] Chat - An empty space is visible in the open compose box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14647] opened 2023-01-28 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New Expensify App
2. Open any chat
3. Start typing in the compose box for 3 lines (with a long text)
4. Expand the compose box

## Expected Result:
There should not be any empty space 

## Actual Result:
An empty space is visible in the open compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1,2,61,0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://user-images.githubusercontent.com/43996225/216869178-b7aef061-755a-4ad5-b6bf-0f976db4bd65.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ee28eab6477b4a6</li>
        <li>Upwork Job ID: 1622585301732487168</li>
        <li>Last Price Increase: 2023-02-06</li>
    </ul>
</details>

**Comment by arielgreen** [comment] 2023-02-01 22:17
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by arielgreen** [comment] 2023-02-01 22:21
@kbecciv can you please upload a new screenshot? The original didn't come through, and I am not sure if this is reproducible or not because I'm not sure exactly what I am looking for. E.g., here is what I see:
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/37308300/216176832-8d16a099-e4e0-4931-a853-81bc4b752c3e.png">

**Comment by kbecciv** [comment] 2023-02-04 00:48
@arielgreen Added, please check the screenshot.

**Comment by arielgreen** [comment] 2023-02-06 00:18
Reassigning this -- I'm OOO this week. I still can't see the image in the OP. Raised [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1675642553340659). I don't know if it's local or not.

**Comment by kavimuru** [comment] 2023-02-06 02:27
@arielgreen I have attached a new screenshot.

**Comment by laurenreidexpensify** [comment] 2023-02-06 13:15
I can reproduce on mobile: 

<img width="293" alt="2023-02-06_13-14-55" src="https://user-images.githubusercontent.com/62073721/216980744-2cd707f4-46de-426e-a275-8f56ae20cd0b.png">

**Comment by priyeshshah11** [comment] 2023-02-06 13:25
I feel this might be a design decision, can we get clarification/confirmation from the design team? @shawnborton

**Comment by priyeshshah11** [comment] 2023-02-06 13:37
Will we be ok with this pattern? where there's an empty line at the bottom for the buttons, looks weird when there'e nothing in the box (makes the compose box bigger in height) 

IMO we should do nothing.

<img width="676" alt="Screen Shot 2023-02-07 at 12 33 05 AM" src="https://user-images.githubusercontent.com/38547776/216985292-1a28592f-7bfa-41ed-841c-da9b19b6a215.png">

**Comment by allroundexperts** [comment] 2023-02-06 14:14
Agree @priyeshshah11. We should do nothing here unless there is a design change.

**Comment by shawnborton** [comment] 2023-02-07 12:09
I agree, this is not a bug and we should do nothing.

**Comment by laurenreidexpensify** [comment] 2023-02-07 12:30
thanks! closing

**Comment by quinthar** [comment] 2023-03-03 20:11
FYI, resuming conversation on this here: https://expensify.slack.com/archives/C049HHMV9SM/p1677874209031189?thread_ts=1677476774.053969&cid=C049HHMV9SM

**Comment by luacmartins** [comment] 2023-03-03 20:24
Closing this in favor of https://github.com/Expensify/App/issues/15598

**Closed by luacmartins** 2023-03-03 20:24 UTC
Labels: External, Daily, Help Wanted, Bug
