### ISSUE TITLE
 Login - Animation is slightly jittery when redirected to the 2nd login validation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24604] opened 2023-08-15 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Account A has Account B as secondary login method but Account B is not verified.

1. Launch New Expensify app
2. Enter secondary login email in login page
3. Tap Continue

## Expected Result:
The animation below the login field is smooth

## Actual Result:
The animation is slightly jittery when user is redirected to the validation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.7

**Reproducible in staging?:** Yes
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DrLoopFall** [comment] 2023-08-16 07:25
Duplicate of #24605

**Comment by conorpendergrast** [comment] 2023-08-16 08:18
Agreed, duplicate

**Closed by conorpendergrast** 2023-08-16 08:18 UTC
Labels: Daily, Bug
