### ISSUE TITLE
[$250] Taxes settings – “Hmm…” page appears when delete existing tax rate offline in new workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42535] opened 2024-05-23 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4569937
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Navigate to the workspace editor
5. Navigate to "More Features"
6. Enable the taxes toggle
7. Verify that there are two default tax rates, Tax exempt and Tax Rate 1
8. Go offline on your devise
9. Delete one of tax rate
10. Go back offline and wait a minute

## Expected Result:
Tax rate is deleted

## Actual Result:
“Hmm... it's not here” page appears when delete existing tax rate offline in a new workspace and back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f8896cbd-b9ec-40a3-a885-3eee32ed7b1f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153b42dc9a27cd89e</li>
        <li>Upwork Job ID: 1795533896735948800</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2024-05-28 19:13
Added to wave-collect and triaged

**Comment by johncschuster** [comment] 2024-06-07 22:37
[Posted in Slack to drum up more proposals](https://expensify.slack.com/archives/C01GTK53T8Q/p1717799802603039)

**Comment by brunovjk** [comment] 2024-06-08 15:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user deletes an existing tax rate offline in a new workspace, the application shows a "Hmm... it's not here" page upon reconnecting online.

### What is the root cause of that problem?
The issue occurs due to a mismatch in the order and completion of API calls related to workspace creation and tax settings update, leading to inconsistent states.

### What changes do you think we should make in order to solve the problem?
1. Store pending tax settings in the `pendingFields` object when enabling tax settings.
2. Update the conditional checks in `AccessOrNotFoundWrapper` to use `pendingFields.tax.value` if `pendingFields.tax.action` is `UPDATE`.
3. Ensure write requests (like `EnablePolicyTaxes`) complete before read requests (like `OpenPolicyMoreFeaturesPage`).

### What alternative solutions did you explore? (Optional)
Blocking read requests until all prior write requests are completed, but this approach was deemed less efficient and more complex to implement.

**Comment by brunovjk** [comment] 2024-06-10 11:17
Of course, I need to finish another PR and I'll be back here. I'll let you know.

**Comment by brunovjk** [comment] 2024-06-11 17:59
@parasharrajat I can't produce it anymore, can you?

**Comment by johncschuster** [comment] 2024-06-11 21:04
@parasharrajat bump on the above!

**Comment by johncschuster** [comment] 2024-06-19 19:13
Thanks for attempting to reproduce the issue, @parasharrajat! I'm going to see if the Applause team can reproduce it. If not, let's close the issue.

**Comment by johncschuster** [comment] 2024-06-19 19:14
Asked for a retest in Slack

**Comment by kavimuru** [comment] 2024-06-19 20:00
@johncschuster not able to reproduce.

https://github.com/Expensify/App/assets/43996225/5ac148d8-1031-462e-9d56-96950312c218

**Comment by johncschuster** [comment] 2024-06-19 20:28
Amazing. Thanks for confirming that! Let's close this then.

**Closed by johncschuster** 2024-06-19 20:28 UTC
Labels: External, Daily, Help Wanted, Bug
