### ISSUE TITLE
[HOLD 297303][$1000] Description inconsistency-description missing in some tasks - inside room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22108] opened 2023-07-03 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
There are going to be 3 Users for this test: User A, B and C. User A needs to be a mobile number. User B and C can be email.

1. Login with User A and create a new workspace. Go to settings > workspaces > new workspace
2. Invite User B into that workspace.Go to  Workspace > members > invite
3. Create a room from User A with that workspace in restricted mode.
4. Inside the room, click on the + button >  Assign task
5. Add title, description. In the description use anything. (I used [www.ebay.com](http://www.ebay.com/))
6. After task is created, go inside the task thread and verify if you can see the description from User A and User B. You should be able to
7.. Now, from User A, invite a new person (User C) to the workspace. Go to workspace > members > invite > Search for User C
Once User C has been added to the workspace, he must have access to the room.
8. From User C: search the room > enter the room> enter the task thread
9. From User C, verify if you can see the description.
## Expected Result:
Description should be visible to User C
## Actual Result:
Description was not visible to User C
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/36989786-e253-495c-a693-c27b25c8eb06

https://github.com/Expensify/App/assets/43996225/0939955b-5d0a-4400-8de9-22b63e2e642d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688108522149949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bd23f16e781b3ef</li>
        <li>Upwork Job ID: 1675950097517805568</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by rain2o** [comment] 2023-07-04 11:36
I also found that this is reproducible if UserA or UserB logs out and logs back in. This means that the Description update is only stored in Onyx data, and is not being saved in the backend.

I believe that this might be a backend issue.

**Comment by coderpradp** [comment] 2023-07-04 13:20
I can confirm this is a backend issue. The response from the API endpoint `GET /api?command=OpenReport` doesn't include description field.


https://github.com/Expensify/App/assets/20035221/a5adc377-a021-43f9-b395-ca65dbe3e066

<details>
  <summary>API Response</summary>
  
  ```js
  {
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_957048967020506",
            "value": {
                "reportID": "957048967020506",
                "reportName": "Go Shopping",
                "type": "task",
                "chatType": "",
                "ownerEmail": "+9779841111111@expensify.sms",
                "ownerAccountID": 14961964,
                "policyID": "BF04561FB6E76BB5",
                "participants": [
                    "photoelectric007+user1@gmail.com"
                ],
                "participantAccountIDs": [
                    14961992
                ],
                "isPinned": false,
                "lastReadTime": "2023-07-04 13:03:37.709",
                "lastMentionedTime": null,
                "lastReadSequenceNumber": 0,
                "lastVisibleActionCreated": "2023-07-04 09:02:04.043",
                "lastVisibleActionLastModified": "2023-07-04 09:02:04.043",
                "lastMessageText": "",
                "lastActorEmail": "+9779841111111@expensify.sms",
                "lastActorAccountID": 14961964,
                "notificationPreference": "always",
                "welcomeMessage": "",
                "stateNum": 0,
                "statusNum": 0,
                "oldPolicyName": "",
                "visibility": null,
                "isOwnPolicyExpenseChat": false,
                "isWaitingOnBankAccount": false,
                "lastMessageHtml": "",
                "hasOutstandingIOU": false,
                "policyName": null,
                "hasParentAccess": true,
                "parentReportID": 5609407657412466,
                "parentReportActionID": "960197497704653573",
                "writeCapability": "all",
                "managerID": 0
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_957048967020506",
            "value": {
                "lastReadTime": "2023-07-04 13:06:05.948"
            }
        },
        {
            "onyxMethod": "merge",
            "key": "reportActions_957048967020506",
            "value": {
                "5326382277030511836": {
                    "reportActionID": "5326382277030511836",
                    "actionName": "CREATED",
                    "created": "2023-07-04 09:02:04.043",
                    "reportActionTimestamp": 1688461324043,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_24.png",
                    "message": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "User Main (984-1111111)"
                        },
                        {
                            "type": "TEXT",
                            "style": "normal",
                            "text": " created this report"
                        }
                    ],
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "+9779841111111"
                        }
                    ],
                    "automatic": false,
                    "sequenceNumber": 0,
                    "shouldShow": true,
                    "lastModified": "2023-07-04 09:02:04.043"
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "14961992": {
                    "accountID": 14961992,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_21.png",
                    "displayName": "User One"
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "reportActions_5609407657412466",
            "value": {
                "960197497704653573": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "User Main"
                        }
                    ],
                    "actorEmail": "+9779841111111@expensify.sms",
                    "actorAccountID": 14961964,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "Created a task: Go Shopping",
                            "text": "Created a task: Go Shopping",
                            "isEdited": false,
                            "whisperedTo": [],
                            "isDeletedParentAction": false,
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "Created a task: Go Shopping",
                        "lastModified": "2023-07-04 09:02:04.047",
                        "taskReportID": 957048967020506
                    },
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_24.png",
                    "created": "2023-07-04 09:02:04.047",
                    "timestamp": 1688461324,
                    "reportActionTimestamp": 1688461324047,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "960197497704653573",
                    "lastModified": "2023-07-04 09:02:04.047",
                    "childReportID": 957048967020506,
                    "childType": "task",
                    "childReportName": "Go Shopping",
                    "whisperedTo": [],
                    "whisperedToAccountIDs": []
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_957048967020506",
            "value": {
                "lastReadTime": "2023-07-04 13:06:05.948"
            }
        }
    ],
    "jsonCode": 200,
    "requestID": "7e179561ccf49885-KTM"
  }
  ```
</details>

**Comment by coderpradp** [comment] 2023-07-04 13:22
Contributor details
Your Expensify account email: iampradyp@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d399442e7d0b4557

**Comment by puneetlath** [comment] 2023-07-05 16:05
Ah, looks like you're right.

**Comment by puneetlath** [comment] 2023-07-05 16:06
@thienlnam I'm assigning you since it looks like this is tasks bug. Let me know if I'm mistaken in that!

**Comment by thienlnam** [comment] 2023-07-05 19:17
We're handling this in https://github.com/Expensify/Expensify/issues/297303

**Comment by puneetlath** [comment] 2023-07-06 00:37
@thienlnam should I close this issue then? Since it seems like a dupe?

**Comment by thienlnam** [comment] 2023-07-06 01:01
It seems like we created the internal issue after this was reported so we can keep this open to payout the reporting bonus

**Comment by puneetlath** [comment] 2023-07-06 21:35
Ok sounds good. 

@avi-shek-jha can you go ahead and apply to the Upwork job?

**Comment by avi-shek-jha** [comment] 2023-07-07 04:37
@puneetlath Proposal Submitted. Thanks.

**Comment by puneetlath** [comment] 2023-07-07 18:13
Sent the offer @avi-shek-jha. Ping me here once you've accepted and I'll pay it out.

**Comment by avi-shek-jha** [comment] 2023-07-07 18:21
@puneetlath Accepted the offer. Thanks.

**Comment by puneetlath** [comment] 2023-07-07 18:24
Great. Paid! 

Going to go ahead and close this out since we have a back-end issue already for this bug. Thanks everyone!

**Closed by puneetlath** 2023-07-07 18:24 UTC
Labels: Daily, Internal, Bug
