### ISSUE TITLE
[$500] Deleted reports show TBD report preview instead of [Deleted report]

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33627] opened 2023-12-26 21:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703612869450969

## Action Performed:
1. Create a Collect policy on OldDot, with weekly scheduled submit enabled
2. Invite user A as an employee. Invite user B as a “manager” for submit/approve.
3. Have user A create an expense/report on OldDot
4. Confirm the report and associated preview shows up in NewDot
5. Have user A delete the report in OldDot (no need to do anything with the expense, as it’ll go unreported)
6. View the reports as user B on NewDot.

## Expected Result:
The report previews should be removed and replaced with [Deleted report], consistent with the same for chats/threads

## Actual Result:
The report previews turn up TBD on NewDot, clicking into the report shows the Hmm…it's not here error

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/512cf1cf-fb88-479a-8656-eb9836506902

![Screenshot 2023-12-26 at 11 48 31](https://github.com/Expensify/App/assets/38435837/ac72a2ae-fe1d-47e8-984b-25bda0356f16)

![Screenshot 2023-12-26 at 10 39 51](https://github.com/Expensify/App/assets/38435837/bce8e86d-722a-4be3-8aa7-16156188c27f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015136a56b24f13ec7</li>
        <li>Upwork Job ID: 1739761647412895744</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by jaymerut** [comment] 2023-12-26 22:15
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
When we delete a report, it's displaying TBD when it should be displaying as [Report deleted]. When a report is deleted it should act in the same way as when messages are deleted.

### What is the root cause of that problem?
There's no logic taking in account for deleted reports. We need to update the logic here for the ReportPreview to make sure we update the view accordingly when it is deleted.

### What changes do you think we should make in order to solve the problem?
We need to add the [Report deleted] value to the parentReportAction en.ts language. We also need to update the 'getDisplayAmount' method in ReportPreview to make sure we return the correct string value when it is deleted. 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by puneetlath** [comment] 2023-12-28 23:36
Closing as this is a dupe of https://github.com/Expensify/Expensify/issues/350244

**Closed by puneetlath** 2023-12-28 23:36 UTC
Labels: External, Daily, Help Wanted, Bug
